{100}{}{Vidíš jednoho z obyvatel Adyta.}
{101}{}{Vypadá to na déš... jako obvykle.}
{102}{}{Promiò, ale musím jít. Mám nìjakou práci.}
{103}{}{Cizince tu nevídáme pøíliš èasto.}
{104}{}{Musím se vrátit zpátky do práce.}
{105}{}{Bıt tebou, tak se vrátím zpátky do Hubu.}
{106}{}{Dobrı den... jestli se tomu tedy dá tak øíkat.}
{107}{}{No jo... a co.}
{108}{}{Nemám èas si s tebou povídat.}
{109}{}{Právì teï si nemùu povídat.}
{110}{}{Doufám, e ten déš nebude radioaktivní jako vèera.}
{111}{}{Vypadá to, e nám zase bude chybìt jídlo.}
{112}{}{Doufám, e se tu zase brzy ukáe nìjaká karavana.}
{113}{}{Teï máme šanci to dokázat.}
{114}{}{Adytum teï bude mìstem, o jakém jsme snili.}
{115}{}{Díky za tvou pomoc.}
{116}{}{Díky, e jsi nás zbavil Regulátorù.}
{117}{}{Díky za naši svobodu.}
{118}{}{Je to skvìlé, kdy jsou Regulátoøi pryè.}
{119}{}{Vítej v novém Adytu.}
