{100}{}{Vidíš supermutanta. Hlídá vzduchotìsné dveøe.}
{101}{}{Vidíš supermutanta na strái.}
{102}{}{Jeremiasi, mùeš projít.}
{103}{}{Bì dál.}
{104}{}{Bì rychleji.}
{105}{}{Normálové tu nesmí nosit zbranì! Stùj a identifikuj se!}
{106}{}{Grrr!}
{107}{}{Oh, promiò. Hned to dám pryè.}
{108}{}{Jen procházím. Identifikace není nutná.}
{109}{}{Chcípni! Chcípni! Chcípni! Tohle jsem chtìl vdycky øíct.}
{110}{}{Se mnou takhle mluvit nebudeš. Budeš potrestán.}
{111}{}{Stùj! Co tu dìláš, "Dítì"?}
{112}{}{Hng!}
{113}{}{Já, uh, mám tu práci.}
{114}{}{Plním dùleitı úkol. Nemáš ádné právo mì zastavovat a ptát se.}
{115}{}{Nemluv na mì, ty pøerostlı hovado.}
{116}{}{Tvùj zpùsob odpovídání mì nevzrušuje. Mluv rychle a jasnì nebo budu muset pøedpokládat, e jsi tu za nìjakım podezøelım úèelem. A ujišuju tì, e v tom pøípadì se dál nedostaneš...}
{117}{}{Ehmm, ne. Opravdu, mám tu práci. Èestnı pionırskı. . .}
{118}{}{Pøináším našemu Vùdci dùleitou zprávu.}
{119}{}{Cítím za tvımi slovy le. Dovnitø vpuštìn nebudeš, to ti dám písemnì...}
{120}{}{Mùeš projít, ale pøíštì dodruj pøedepsanı postup...}
{121}{}{OK, díky. Uvidíme se.}
{122}{}{A co je to?}
{123}{}{Poehnání s tebou, bratøe.}
{124}{}{Opravdovı Vùdcùv stoupenec by to mìl znát. Ty jsi jen vetøelec!}
{125}{}{Pohni se. Nemám èas na tvoje otázky.}
{126}{}{Štveš mì.}
{127}{}{Mám práci. Ty ne?}
{128}{}{Dìláš chybu, kdy sem chodíš. Vysvìtli to nebo je po tobì...}
{129}{}{Blázne!}
{130}{}{Nemám co bych øekl.}
{131}{}{Jsem tu, abych chránil lidstvo pøed takovımi, jako jsi ty.}
{132}{}{Dr hubu!}
{133}{}{Nemìl bys mì zkoušet oblafnout tím, e budeš hrát tupce. U mì to unavuje...}
{134}{}{Co je tohle za bláznivı fanatismus, "chráním lidstvo". Já jsem právì takovı èlovìk jako ty.}
{135}{}{Co je tohle za volovinu?}
{136}{}{Nevidím mezi námi ádnou podobnost.}
{137}{}{Jmenuju se Kyle. Narodil jsem se otci a matce, stejnì jako ty. Vùdce pouze dohlíel na mé Znovuzrození. Tyto svaly, tato kùe, tato síla, nic z toho mì nedìlá o nic ménì èlovìkem ne jsi ty. Nesdílím všechny názory, které Jednota zastává, ale tohle je poøád ta nejlepší šance na mír, kterou máme.}
{138}{}{Ne, podle mého názoru není. Jsem tu, abych skonèil s tebou i tvım rodem.}
{139}{}{Moná jsi èlovìk, ale to poøád neospravedlòuje tu tvou Jednotu. Myslím, e z nás pøece jen budou nepøátelé.}
{140}{}{To je mi líto, e se na to takhle díváš. Dál se ale nedostaneš...}
{141}{}{To bude opravdu smutnı pohled, vidìt tvojí hlavu napíchnutou na kùlu.}
{142}{}{Vetøelec!}
{143}{}{S tebou se nebavím.}
{200}{}{Za oklamání stráí jsi obdrel }
{201}{}{ zkušenostních bodù.}
