{100}{}{Vidíš Alexe, noèní hlídku Regulátorù.}
# TRANSLATION NOTE
# The player-character's name is inserted after line 101.
{101}{}{Pojï dál, }
{102}{}{Promiò, ale nemùu tì pustit dovnitø. Pøijï ráno.}
{103}{}{Stát! Kdo je tam?}
{104}{}{Jsem jen obyèejnı poutník. Chci vejít dovnitø.}
{105}{}{Do toho ti nic není.}
{106}{}{Ehm, promiò. Radši u pùjdu.}
{107}{}{Z rozhodnutí starosty není do Adyta povolen vstup ádnému cizinci.}
{108}{}{Hledám jen kousek místa na pøespání.}
{109}{}{Promiò, ale nemùu tì pustit dovnitø. Vypadni, nebo budu muset zaèít støílet.}
{110}{}{Podívej, mım úkolem je slouit jako noèní strá Adyta, a tak je mi do toho setsakramentsky moc. A teï se koukej ztratit nebo to s tebou špatnì dopadne.}
{111}{}{Koukej mi zmizet z oèí.}
{112}{}{Vra se ráno.}
{113}{}{Aha, tak ty takhle. Take konec s veškerımi ohledy!}
{114}{}{Uff-Uff.}
