# The following dialog lines were pulled from these files, which are now blank:
# DEMODOG
# DOG2
# DOGMEAT
# JUNKDOG
###############################################################################
#
# DEMODOG.MSG
#
{100}{}{Vidíš psa. Zdá se, že tì sleduje.}
{101}{}{Vidíš psa.}
{102}{}{Haf!}
{103}{}{Grrr!}
{104}{}{Vypadá to, že máš nového kamaráda.}
{105}{}{Získáváš 200 zkušeností za spøátelení se se psem.}
{106}{}{Získáváš 335 zkušeností za zabití psa a vyøešení Philova problému.}
#
# DOG2.MSG
#
{107}{}{Pojï sem, hochu.}
{108}{}{Haf. Haf.}
{109}{}{Z nìjakého dùvodu tì ten pes má rád.}
#
# DOGMEAT.MSG
#
{110}{}{Vidíš Dogmeata.}
{111}{}{Òaf! Òaf Òaf! Òaf! Òaf! Òaf! Òaf! Òaf! Òaf!}
{112}{}{[Èuch. Èuch.] Grrrr! Vrrr!}
{113}{}{[Èuch. Èuch.] Haf!}
#
# JUNKDOG.MSG
#
{114}{}{ zkušeností za to, že jsi vyøešil Philùv problém se psem.}
{115}{}{Vypadá to, že pes si myslí, že jsi jeho majitel.}
{116}{}{ zkušeností za to, že jsi vyøešil Philùv problém se psem.}
{117}{}{Haf-haf!}
{118}{}{Pojï, kámo.}
{119}{}{Zùstaò tady a èekej, jo?}
{120}{}{Hodný pejsek.}
{121}{}{Štìnátko!!!}
{122}{}{Haf?}
{123}{}{Òaf?}
#
# for Fallout Fixt:
#
#
# for Stupid characters (INT <= 3)
{300}{}{Pejsek!! Pejsek chtít být kamarád?}
{301}{}{Pejsek zùstat! Nehýbat!}
{304}{}{Hodnej pejsek!}
#
#Normal INT
{302}{}{Uhni stranou, kámo. Hodnej hoch.}
#
# space is intentional
{303}{}{ Blbej èokl!}
