{100}{}{Vidíš Amber, uèitelku Následovníkù.}
{101}{}{Teï je èas odpoèinku. Pøijï prosím nìkdy bìhem veèera.}
{102}{}{Vítejte, vznešenı poutníku. Pøišel jste sem studovat?}
{103}{}{Ne. Ve skuteènosti jsem pøišel zabíjet.}
{104}{}{To záleí na tom, èemu mì chcete uèit.}
{105}{}{Ano, chci se uèit.}
{106}{}{To je mi opravdu líto. Následovníci vìøí v mír za kadou cenu. Proto jsem se zøekla všeho násilí. Dobrou noc.}
{107}{}{Jsem vzdìlaná v mnoha jazycích a umìních. Pøejete si nìèemu z toho uèit?}
{108}{}{Lituju, ale potøebuju se nauèit vìci, které mi pomùou pøeít.}
{109}{}{Na takové nesmysly nemám èas. Sbohem.}
{110}{}{Moná bych si mohl poslechnout jednu nebo dvì písnì.}
{111}{}{A mùete mì nauèit i nìco jiného?}
{112}{}{Ach, máme tu studenta ivota. V takovém pøípadì vás mohu nauèit nìco z bylinkáøství, ale vıcvik trvá dlouho a pøinese jen skromné vısledky.}
{113}{}{Fajn, prostì mì uète.}
{114}{}{Prosím, nauète mì všechno, co se dá.}
{115}{}{Lituju, ale na kytky opravdu nemám èas. Sbohem.}
{116}{}{Není nutné chovat se tak hrubì. Omluvte se, nebo vás nebudu uèit.}
{117}{}{Promiòte. Budete mì prosím uèit?}
{118}{}{Zapomeòte na to.}
{119}{}{To u je lepší. Mùeme zaèít s vaším studiem.}
{120}{}{Jste bystrı uèedník. Pøeji vám, a jsou vaše budoucí zkoušky lehké. Jdìte v pokoji.}
{121}{}{Jak uznáte za vhodné. Ké budoucnost obmìkèí vaše srdce a osvítí vaši mysl.}
{122}{}{Vıbornì, budu vás tedy uèit zpùsoby, jak pøeít.}
{123}{}{Jste bystrı uèedník. Pøeji vám, a jsou vaše budoucí zkoušky lehké. Jdìte v pokoji.}
{124}{}{Vaše slova mì nepøesvìdèují. Myslím, e chcete mé dary vyuít pro páchání zla. Sbohem.}
{125}{}{Ach, student umìní. To je v tomhle svìtì velmi vzácné. Moná je pro vás pøece jen nìjaká nadìje. Kadá píseò je ale dosti dlouhá. Kterou z nich chcete slyšet?}
{126}{}{Ve stínu pøízraku.}
{127}{}{Balada o Airesovi.}
{128}{}{Na památku Artemidy.}
{129}{}{Vzestup Jitøního vozu.}
{130}{}{Vskutku pozoruhodné dílo. Udìlím vám audienci.}
{131}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{132}{}{Vskutku pozoruhodné dílo. Udìlím vám audienci.}
{133}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{134}{}{Vskutku pozoruhodné dílo. Udìlím vám audienci.}
{135}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{136}{}{Vskutku pozoruhodné dílo. Udìlím vám audienci.}
{137}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{138}{}{Obávám se, e jsem se u pøíliš vyèerpala. Lituji.}
{139}{}{Mír a krása — to je vše, èemu vás mohu uèit. Je mi líto, e vás nic z toho nezajímá. Pøeji vám krásnı den.}
{140}{}{Mohu vás nauèit zpùsobùm starıch bardù a minstrelù.}
{141}{}{Bylo by mi ctí slyšet jednu z vašich písní.}
{142}{}{Moná nìkdy jindy. Ale díky.}
{143}{}{Doufal jsem, e se tu nauèím nìèemu, co mi v ivotì pomùe trochu víc.}
{144}{}{Nepotøebujete nic z mého umìní. Nauèil jste mírumilovné lidi válèit. Truchlím pro nì.}
