{100}{}{Rozzlobil jsi Barryho!}
{101}{}{Vidíš Barryho.}
{102}{}{Hej! Jen ghúlové mají nárok na pøídìl vody.}
{103}{}{Za to, žes mì vzbudil, teï nìco uvidíš!}
{104}{}{Ten mutant tì ignoruje.}

{1000}{}{Cip}
{1001}{}{Nekropolis}
{1002}{}{Set}
{1003}{}{Vodarna}
{1004}{}{Hala}
{1005}{}{Lou}
{1006}{}{Ghouls|Ghulove}
{1007}{}{Normalove}

{1100}{}{Nevím.}
{1101}{}{Stojíš v ní.}
{1102}{}{Je to srab. Mìli bysme zlikvidovat jeho i ty jeho ghúly.}
{1103}{}{To je tady.}
{1104}{}{Nevím.}
{1105}{}{Von je Harryho šéf.}
{1106}{}{Zbabìlí chudáci.}
{1107}{}{Zbabìlejší než ghúlové.}
