{100}{}{Vidíš stráž.}
{101}{}{Pracuju pro toho obchodníka. Starám se, aby mu nikdo nelezl na nervy.}
{102}{}{Nemáš nìjakej koblížek?}
{103}{}{Jestli to znièíš, budeš to muset koupit!}
{104}{}{Zlodìjíèky tu zabíjíme!}
{105}{}{Koupíš si nìco? A bude to ještì v tomhle století?}
{106}{}{Bez tìhle vìcièek nemùžu bojovat s radškorpióny.}
{107}{}{Pracuju pro toho obchodníka. Starám se, aby mu nikdo nelezl na nervy.}
