{100}{}{Vidíš Boba, majitele „Bobovıch leguánù na špejli“.}
{101}{}{Dobøe, dobøe, tady máš své peníze.}
{102}{}{Mìl jsem nìjaká vydání. Musím zvıšit svoje poadavky.}
{103}{}{Pøitlaè. Chci VŠECHNY tvoje peníze a hned, nebo je z tebe mrtvola.}
{104}{}{Mám vıèitky svìdomí. Odvolávám ty platby.}
{105}{}{Chci nìjaké informace o Deckerovi.}
{106}{}{Chci nìjaké informace o doktoru Morbidovi.}
{107}{}{Dej mi leguána na špejli.}
{108}{}{Lituju. U ti nebudu dál platit. Dìlej si se mnou, co chceš.}
{109}{}{Bobe, já myslel, e jsme kámoši! Vlastnì jsem pøemıšlel o tom, e ti moje organizace poskytne podporu. A tys mì zatím zradil. To je velmi zarmucující...}
{110}{}{Bobe a proè si myslíš, e mi bude staèit jako odpovìï 'ne'? A speciálnì od takovı špíny, jako jsi ty?}
{111}{}{To mì tìší, e se chceš prát.}
{112}{}{Tvoje dobrá povìst je minulost, Bobe. Mi-nu-lost!}
{113}{}{Fajn. Ještì si rozmyslím co s tebou.}
{114}{}{Dobøe, rád jsem tì poznal Bobe. Øekni za mì Satanovi 'ahoj'.}
{115}{}{Co tu chceš tak brzy? Ještì není èas pro zaplacení.}
{116}{}{Ty máš ale nervy, e se tu ukazuješ. Ztra se!}
{117}{}{Hej, nestojím o ádnı problémy!}
{118}{}{Zdravím! Vítejte u Bobovy restaurace pro celou rodinu. Chcete si objednat?}
{119}{}{Zapomeò na to.}
{120}{}{Opravdu? No tak OK...}
{121}{}{To je opravdovej zkurvysyn. Nezkoušej se s ním zaplést. Ještì nìco?}
{122}{}{Fajn. Kolik po mnì chceš?}
{123}{}{Chci }
{124}{}{ zátek kadıch pìt dní.}
{125}{}{Doktor Morbid? Všechno co o nìm vím je, e bydlí nìkde v Junktownu a e je to ten nejlevnìjší dodavatel surovin, kterého bych mohl najít. To je všechno!}
{126}{}{Jen se raète podívat na naší nabídku.}
{127}{}{Mám tu celého leguána za dvacku.}
{128}{}{Mám tu pøímo vybranı nejlepší kousek za osm babek.}
{129}{}{Vezmu si jednoho z tìch opravdovıch.}
{130}{}{Právì teï radši nic. Drím dietu.}
{131}{}{Vezmu si jeden z tìch speciálních kouskù.}
{132}{}{Dal bych si teï jeden z tìch vybranıch kouskù. Zaplatím.}
{133}{}{Uhh... teï zrovna nemám hlad.}
{134}{}{Fajn! Vem si ty peníze a zmiz odsud!}
{135}{}{Polib mi... ! Nic ti nezaplatím! Vypadni odsud!}
{136}{}{Jo, jistì. Proè si na vydírání nenajdeš nìkoho jinıho?}
{137}{}{Nejde se ponoøit do sraèek a myslet si, e se nezamaeš. Padej odsud!}
{138}{}{No to urèitì. Zmiz!}
{139}{}{Lituji. Leguáni u došli.}
{140}{}{Máme pouze celého leguána na špejli. Tøicet babek za jednoho. Lepší peèenıho leguána v celı pustinì nenajdeš, to ti garantuju!}
{141}{}{Máme pouze pøímo vybrané kousky. Ale chutnají skvìle. Osm babek za jeden.}
{142}{}{Jistì. Máme buï celého leguána na špejli za dvacet nebo zvláš vybrané kousky za osm.}
{143}{}{Vezmu si celého leguána.}
{144}{}{Vezmu si jeden z tìch kouskù.}
{145}{}{Slyšel jsem, e tvoje vıbìrovı maso chutná jako kuøe. Je takovı... mìkkı. To do toho melete jenom ty mìkkoty?}
{146}{}{ádné hloupé kousky! Já chtít celı leguán! Ugh!}
{147}{}{Hmm, hezky vonìt! Já chtít ten kousek!}
{148}{}{Nikdy jsem tu nic podobného nevidìl. Obchodníci s vodou je nepotøebují.}
{149}{}{Obchodníci s vodou?}
{150}{}{Pan Decker je vznešenı obchodník, kterı vede trochu ménì vznešenı byznys. Ještì nìco?}
{151}{}{Ehm... Dobøe...}
{152}{}{Jakı je to druh byznysu?}
{153}{}{O èem to mluvíš?}
{154}{}{Tvoje tajné pøísady! Jak èerstvá musí bıt tìla, aby se nedala poznat ta pachu? Pouíváš mutanty, lidi a nebo to mícháš?}
{155}{}{Našel jsem v doupìti doktora Morbida úèet pro tebe. Úèet za mrtvá tìla...}
{156}{}{Jestli snad trpíš ztrátou pamìti, mùu si o tom popovídat se šerifem.}
{157}{}{Ty tvoje speciálnì vybranı kousky jsou dìlanı z lidí! Dìlanı z lidí!}
{158}{}{O nièem. A teï je tu ještì nìco, co pro tebe mùu udìlat?}
{159}{}{Dobøe, teï je mrtvı a o to vyšší je moje hotovost.}
{160}{}{Nìkdo zabil pana Deckera. Všichni máme smutek. [popotahuje]}
{161}{}{Nìkdo sejmul šerifa Greene. Ale nevím, co je s jeho zástupcem.}
{162}{}{Daren Hightower byl zavradìn. Ani všechny ty jeho prachy mu nepomohly. To je ironie, co?}
{163}{}{Nìkdo ukradl ze ètvrti Pahorky vzácnı náhrdelník. Èlovìèe, mùu ti øíct, e ten nìkdo udìlal zatracenì velkou chybu. U teï je po nìm!}
{164}{}{Nìkdo zabil Jain, knìku Dìtí katedrály. Co jsem slyšel, tak to byla hroznì protivná enská!}
{165}{}{No, jediná nová vìc, co vím, je, e Dìti katedrály zabraly Nemocnici. Jinak je tu poslední dobou hrozná nuda.}
{166}{}{Ještì nìco?}
{167}{}{Chlape mizernej, bìhem tıdne budu na mizinì. Ještì nìjaké pøání, ó velikı a mocnı?}
{168}{}{Tvùj tón se mi nelíbí.}
{169}{}{Lituji, ale nemùeš si to dovolit.}
{170}{}{Ano, jeden celı leguánek, u se to nese! Ještì nìco?}
{171}{}{Víš z èeho jsou vyrobeny a pøesto si jeden dáš? Teda ve srovnání s tebou je Decker milosrdná sestra! Ještì nìco?}
{172}{}{Tvùj tón se mi nelíbí.}
{173}{}{Lituji, ale nemùeš si to dovolit.}
{174}{}{Ano, jeden zvláš vybranı kousek z leguána, u se to nese! Ještì nìco?}
{175}{}{Skvìlá volba. Nezaškodilo by ti shodit pár kilo.}
{176}{}{Co...co to?! Aha, u vím, ty si dìláš legraci...}
{177}{}{Jo jasnì, e si...}
{178}{}{No, a já ne. Hned uvidíš, jak zaplatíš za svùj zloèin.}
{179}{}{No, a já ne. A chci z toho taky nìco mít.}
{180}{}{Musíš bıt asi ve mìstì novı, kdy se mì ptáš na Obchodníky s vodou. Voda je ivot a kdo mùe bıt mocnìjší ne ten, kdo vládne nad ivotem a smrtí.}
{181}{}{Kdo vede Obchodníky s vodou?}
{182}{}{Pokud je v Hubu nìco, co pùsobí bolest a utrpení, tak to Decker buï u kontroluje, nebo se to aspoò kontrolovat snaí. Ještì nìco?}
{183}{}{Vùbec nevím, o èem to mluvíš a nehodlám dál poslouchat tvoje pomluvy! Doufám, e u se tu znovu neukáeš.}
{184}{}{Nedìlej to! Fajn, tak pouívám nìjaké ty trochu diskutabilní suroviny. Ale to neznamená, e snad páchám vrady. Zboí doktora Morbida u je mrtvé, nebo ne?}
{185}{}{Ale jistì e jo, Bobe. Pøeju krásnı den...}
{186}{}{Kanibalismus je zloèin proti lidstvu, Bobe. A já podívám, jak za to zaplatíš.}
{187}{}{Moná to tak je. Moná není. Mnì je to fuk. Chci z toho taky nìco mít.}
{188}{}{Ne tak nahlas! Není potøeba vyøvávat to na celı Hub...}
{189}{}{Myslím, e jsem byl zbyteènì hrubı. Mìj se...}
{190}{}{Víš, policejní stanice je pøímo pøes ulici. Moná bych si mìl udìlat malou procházku.}
{191}{}{Mùu mluvit ještì hlasitìji. Ale taky mùu mlèet. Jde o to, jak se to vezme. Hluk je levnı, ticho je drahé.}
{192}{}{Jak ti mám sakra platit, kdy vyereš celı mùj obchod? Fajn! Tady máš dalšího leguána! Doufám, e se s ním zalkneš!}
{193}{}{Tvùj tón se mi nelíbí.}
{194}{}{To je tìkı. Chceš peníze, dám ti je. Chceš jídlo, dám ti ho. Chceš umøít, zaøídím to. Ale 'líbení' není souèást dohody.}
{195}{}{Nic. A teï, kdy mì omluvíš, mám nìjakou práci.}
{196}{}{Lituji, ale leguáni u nám došli.}
{197}{}{Máme pouze leguána na špejli. Dvacet babek.}
{198}{}{Máme jenom kousky z leguána. Osm babek.}
{199}{}{U zase? Èlovìèe, ty musíš mít ale hlad. Máme leguána na špejli za dvacet a naše extra vybrané kousky z leguána za osm babek.}
{200}{}{Vezmu si celého leguána.}
{201}{}{Vezmu si jeden z tìch kouskù.}
{202}{}{Slyšel jsem, e tvoje vıbìrovı maso chutná jako kuøe. Je takovı... mìkkı. To do toho melete jenom ty mìkkoty?}
{203}{}{ádné hloupé kousky! Já chtít celı leguán! Ugh!}
{204}{}{Hmm, hezky vonìt! Já chtít ten kousek!}
{205}{}{Jak ti mám sakra platit, kdy vyereš celı mùj obchod? Fajn! Tady máš dalšího leguána! Doufám, e se s ním zalkneš!}
{206}{}{Tvoje chování se mi nezamlouvá.}
{207}{}{Uh, sbohem.}
{208}{}{Poèkej chvíli. Snad najdeme zpùsob, jak se mùeme dohodnout!}
{209}{}{Abys mì umlèel, musel bys mì nejdøív zabít.}
{210}{}{Lituju, ádnı obchod nebude.}
{211}{}{Fajn. Co z toho budu mít?}
{212}{}{Fajn. Co ode mnì chceš?}
{213}{}{Chci }
{214}{}{50}
{215}{}{75}
{216}{}{100}
{217}{}{150}
{218}{}{200}
{219}{}{ babek kadıch pìt dní.}
{220}{}{Myslím, e tì nebudu vydírat. Nech si to.}
{221}{}{Bıt tebou, pøíteli, tak si to rozmyslím. Tady v Hubu umírají lidé velice rychle a snadno.}
{222}{}{Fajn. Jsme dohodnuti. }
# TRANSLATION NOTE: A number of caps is inserted between lines 222 and 223. The space at the end of line 222 is intentional!
{223}{}{ zátek, splatnıch kadıch pìt dní. Tak se uvidíme za pìt dní...}
{224}{}{Ani nápad. V ádném pøípadì ti nemùu platit víc, ne co platím teï.}
{225}{}{Smùla, Bobe. Nerad, ale budu muset zaèít zpívat.}
{226}{}{Fajn. Zùstaneme na èástce, kterou jsme si dohodli... prozatím.}
{227}{}{Mùeš si dovolit zaplatit pohøeb, Bobe?}
{228}{}{Fajn. Moná by bylo dobøe, kdybychom se u nepotkali.}
{229}{}{Mùeš zpívat jako slavíèek, ale já jsem husa, co snáší zlatá vejce. Ty pøece nebudeš mluvit, kdy jsem tvùj jedinı zdroj pøíjmù. A teï odsud padej!}
{230}{}{To je první rozumná vìc, co tì slyším øíkat. A teï odsud zmiz!}
{231}{}{Dej mi leguána na špejli.}
{232}{}{Víš nìco o vodním èipu?}
{233}{}{Co mi mùeš øíct o Deckerovi?}
{234}{}{Myslím, e bychom si mìli promluvit o doktoru Morbidovi a o nìkterıch tvıch tajnıch pøísadách.}
{235}{}{Víš nìco o tìch ztracenıch karavanách?}
{236}{}{Já a problémy? Co v tobì budí ten dojem?}
{237}{}{Dìje se v Hubu nìco zajímavého?}
{238}{}{Já mít hlad! Grrrrr!}
{239}{}{Hroznı byznys. Ti ubozí lidé. Ach, ti ubozí lidé. Pøijít tak strašnım zpùsobem o ivot! Je tu ještì nìco, co pro tebe mùu udìlat? Nakrmit tì, tøeba?}
{240}{}{Nic, sbohem.}
{241}{}{Já teï jít.}
{242}{}{Nemùu ti dát takové peníze. Sotva se sám uivím.}
##
##Sduibek -- Fallout Fixt
##
{243}{}{Tøicet zátek?! Dìláš si srandu?}
{244}{}{Hele debile, ty jsi ten, kdo znièil moje ziskové mare. Take pokud se ti nelíbí moje ceny, tak kurva vypadni. Je tu spousta dalších stánkù s jídlem. Poèkej... Vlastnì není. Máš smùlu, hovado.}
{245}{}{Špatnì, a je to tvoje vina. Pokud si nehodláš nic koupit, tak vypadni.}
{246}{}{Jak chceš. Sbohem.}
{247}{}{Vlastnì, kdy nad tím tak pøemıšlím, mám docela hlad.}
#
{250}{}{ zkušeností za úspìšné vydírání Boba.}
{251}{}{Jak ti jdou obchody, Bobe?}
#
# 252 to 260 take place while Bob is in jail
{252}{}{Co tu sakra dìláš? Znièil jsi mé podnikání a urèitì jsi dostal velkou odmìnu. To ses pøišel vysmívat, nebo co?}
{253}{}{Jo, pøesnì tak. Jak jdou obchody, Bobe?}
{254}{}{Ne, chci kouknout, jak se ti daøí.}
{255}{}{Pøíšernì a je to tvá vina. Nejspíš mì tady nechají chcípnout.}
{256}{}{Zaslouíš si to.}
{257}{}{Mohl bych tì zabít hned teï a ušetøit ti to pomalé èekání.}
{258}{}{Zeptám se, jestli by tì po tvé popravì nemohli zpracovat do leguánù na špejli!}
{259}{}{Dìlej si co chceš. U se s tebou nehodlám bavit.}
{260}{}{Jdi pryè.}
