{100}{}{Vidíš èlena Blades.}
{101}{}{Ahoj.}
{102}{}{Zdravím.}
{103}{}{Pøeju krásnı den.}
{104}{}{Dneska je ale krásné poèasí.}
{105}{}{Neškodilo by, kdyby trochu zapršelo.}
{106}{}{U jsi nìkdy vidìl svítící déš?}
{107}{}{U musím jít zpátky do práce.}
{108}{}{Nemíváme tu návštìvy moc èasto.}
{109}{}{Musím jít.}
{110}{}{Mìj se.}
{111}{}{Dobrı den.}
{112}{}{Díky za tvou pomoc.}
{113}{}{Nikdy na tebe nezapomeneme.}
{114}{}{Je dobøe, e jsi na naší stranì.}
{115}{}{Teï u bude všechno lepší.}
