{100}{}{Dvouhlavá zmutovaná kráva. Tahle byla domestifikována.}
{101}{}{Pøipadá ti normální.}

{102}{}{Proè se snaíš mluvit s krávou?}
{103}{}{Brahmina na tebe chvíli kouká, ale brzo ztratí zájem.}
{104}{}{Brahmina tì ignoruje.}
{105}{}{Zvíøe funí, ale jinak nereaguje.}

{106}{}{Dvouhlavá zmutovaná kráva. Tenhle kus je divokı.}
{107}{}{Pøipadá ti normální.}
{108}{}{Na tìchhle krávách není nic pøirozeného. Jejich druhá hlava je vısledek nìjaké podivné mutace.}
{109}{}{Búú.}
{110}{}{Búú!}
{111}{}{Búú, pravím.}
# Is this used anywhere?
{113}{}{Kráva se nasrala, protoe jsi zaútoèil na její kamarádku.}

#Fo2
{201}{}{Búúú...}
{202}{}{Búúú Búúú Búúú...}
{203}{}{Búúú...}
{204}{}{Búúúúúú...}
{205}{}{Búúúúúúúúú...}
{206}{}{:: CHROCHTÁNÍ ::}

{210}{}{Nyní jsi expertem na kravské sraèky!}
