{100}{}{Vidíš vedoucího karavany.}
{101}{}{Tak jsme tu. Tady je tvých }
{102}{}{ babek. [Vytahuje starý ohmataný pytlík a podává ti zátky.] Dostaneš dalších }
{103}{}{ zátek, když se s námi vrátíš do Hubu. Nìjakou dobu si tu odpoèineme, ale nevzdaluj se pøíliš daleko, jinak karavana odcestuje bez tebe.}
{104}{}{Aaa... OK.}
{105}{}{Jak dlouho tu zùstanete?}
{106}{}{Co mi mùžeš øíct o Junktownu?}
{107}{}{Co mi mùžeš øíct o L.A. kostnici?}
{108}{}{Co mi mùžeš øíct o Bratrstvu oceli?}
{109}{}{Nevím, jestli tomu budeš rozumìt, ale vyrážíme za dvì hodiny, nebo kdykoliv budeš pøipraven.}
{110}{}{Um...}
{111}{}{Hunh?}
{112}{}{Jít. To dobré.}
{113}{}{Èlovìèe, my teda najímáme poslední dobou blbce.}
{114}{}{Obvykle odjíždíme dvì hodiny po pøíjezdu. Ale protože tu není nic, co už bychom pøedtím nevidìli, tak jestli chceš, mùžeme vyrazit i døív. Hned jak budeš pøipraven.}
{115}{}{Myslím, že se tu nejdøív trochu porozhlédnu. Uvidíme se pozdìji.}
{116}{}{OK. Tak mùžeme vyrazit do Hubu. Ani já tu nemusím nic vidìt.}
{117}{}{Co mi mùžeš øíct o Junktownu?}
{118}{}{Co mi mùžeš øíct o L.A. kostnici?}
{119}{}{Co mi mùžeš øíct o Bratrstvu oceli?}
{120}{}{No, je to tu trochu jako v Hubu, opravdu. Mají tu ty samé problémy: gangy, vrazi, zlodìji, však víš... obvyklé vìci. Tak jako tak, je to mùj typ mìsta. [Smìje se]}
{121}{}{Jak dlouho tu karavana zùstane?}
{122}{}{Myslím, že se tu nejdøív trochu porozhlédnu. Uvidíme se pozdìji.}
{123}{}{Tahle èást L.A. kostnice se jmenuje Adytum. V L.A. kostnici vládnou v podstatì gangy. Je to drsné místo, tak si tu dávej pozor. Adytum øídí Regulátoøi. Snaží se tohle místo udržet pohromadì i pøes všechny ty gangsterský války. K cizincùm se chovají pochopitelnì podezíravì, tak jestli jsi s nimi ještì nemluvil, doporuèuju ti, abys to udìlal døív, než se jim tu zaèneš courat.}
{124}{}{Prázdný}
{125}{}{Jak dlouho tu karavana zùstane?}
{126}{}{Myslím, že se tu nejdøív trochu porozhlédnu. Uvidíme se pozdìji.}
{127}{}{Není toho moc, co bych ti o nich øekl. Bratrstvo je dost uzavøený spolek. Spousta lidí je nemá ráda, ale co já vím, jsou to slušný lidi. Trochu fanatici, možná, ale jinak jsou to dobráci.}
{128}{}{Jak dlouho tu karavana zùstane?}
{129}{}{Myslím, že se tu nejdøív trochu porozhlédnu. Uvidíme se pozdìji.}
{130}{}{Jsi pøipraven vyrazit?}
{131}{}{Jedem!}
{132}{}{Ne. Ještì poøád se tu rozhlížím.}
{133}{}{Jo. Mùžeme jet.}
{134}{}{Tahle èást L.A. kostnice se jmenuje Adytum. V L.A. kostnici vládnou v podstatì gangy. Je to drsné místo, tak si tu dávej pozor.}
{135}{}{Jak dlouho tu karavana zùstane?}
{136}{}{Myslím, že se tu nejdøív trochu porozhlédnu. Uvidíme se pozdìji.}
{137}{}{OK. Zvládl jsi to. Tady je tvých }
{138}{}{ babek. Pokud budeš chtít ještì práci, staèí si promluvit se šéfem. Budu víc než rád, když s tebou budu moct znovu dìlat. Pøimluvím se za tebe u šéfa. Mìj se.}
{139}{}{Pá pá.}
{140}{}{Nashle.}
{141}{}{Hej, jak se vede?}
{142}{}{Jestli chceš víc práce, zajdi se zeptat šéfa.}
{143}{}{Co je to s tebou?}
{144}{}{Ty jsi mizernej a nebezpeènej psychopat!}
{145}{}{S tebou nedìlám!}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{Co mi mùžeš øíct o Nekropolis?}
{150}{}{To je pìknì hnusný místo, kámo!}
{151}{}{Karavana odjela.}
{200}{}{Hmmmpf...}
{201}{}{Hmm... Chtìl bych umìt èíst.}
{300}{}{Hleï si svýho, jasný?}
{400}{}{Za kecání mì neplatí.}
{501}{}{Tak to mi teda øekni, proè jsi tu zatacenou karavanu opustil? Já tomu nemùžu uvìøit! Máš z prdele kliku, že to chlapi dotáhli do konce bez tebe! Vypadni! Nedostaneš ani hovno!}
{502}{}{Já tomu nemùžu uvìøit! Pøišli jsme o celou karavanu! Vypadni! Nedostaneš ode mì ani hovno!}
{504}{}{Jdi za šéfem a snaž se vymyslet nìjakou opravdu dobrou historku o tom, proè jsi musel opustit tu zasranou karavanu. Možná pak dostaneš svoje prachy, ale pochybuju.}
{505}{}{Já tomu nemùžu uvìøit! Pøišli jsme o celou karavanu! Nedostaneš ode mì ani vindru. Vypadni mi z oèí.}
{600}{}{No, tak jsme tady. Nemùžu ti zaplatit normální sazbu, protože jsme ztratili èást karavany. Musíme pokrýt naše ztráty. Tady je tvùj plat }
{601}{}{ zátek. [Vytáhne starý ohmataný pytlík a odpoèítá ti zátky.] Dostaneš dalších }
{602}{}{Pokud chceš další práci, promluv se šéfem. Nevadilo by mi s tebou znovu dìlat. Mìj se.}
{603}{}{ zátek. [Vytáhne starý ohmataný pytlík a odpoèítá ti zátky.] }
{604}{}{Takže jsi to pøežil. Nemùžu ti nic zaplatit, protože jsme ztratili celou karavanu. Musíme pokrýt naše ztráty, však víš. Je mi líto, ale takový jsou pravidla.}
{605}{}{Takže jsi to pøežil. Nemùžu ti nic zaplatit, protože všechny brahmíny chcíply. Stál jsi nás hodnì penìz, chlapèe. Žádný brahmíny, žádná karavana, žádný prachy. Doufám, že tì s náma už nikdy nenechaj dìlat.}
#
# Unload caravan quest - WG@RestorationProject
#
{506}{}{Máš pro mì nìjakou práci?}
{507}{}{Já chtít práce!}
{508}{}{Je tøeba vyložit karavanu. Zaplatím ti }
{509}{}{ zátek.}
{510}{}{Ug!}
{511}{}{Nop.}
{512}{}{Jdu na to.}
{513}{}{To se mi moc nelíbí.}
{520}{}{Vyložení karavany ti trvalo hodinu.}
{521}{}{Za svou pomoc pøi vykládání karavany jsi obdržel }
{522}{}{ zátek.}
