{100}{}{Pøed sebou vidíš hlídajícího zvìda.}
{101}{}{Kdo je tam?}
{102}{}{Já. Já.}
{103}{}{Kdo je tam?}
{104}{}{Pøece já!}
{105}{}{Tvoje smrt!}
{106}{}{Uklidni se. Já jsem pøítel.}
{107}{}{Jája? Jdi odsud! Tohle je majetek Dìtí Katedrály.}
{108}{}{Huh? Já zùstat!}
{109}{}{Huh? Ty umøít!}
{110}{}{Já nechtít odejít.}
{111}{}{Skvìle. Ze všech lidí, které jsem mohl zastavit, jsem narazil zrovna na takovıhle kus rádla pro kanóny. Co pro tebe mùu udìlat?}
{112}{}{Jít noc-noc!}
{113}{}{Nyts.}
{114}{}{Pomoft tobje.}
{115}{}{OK. Navrhuju ti, abys odsud zmizel døív, ne pøijdeš k úrazu.}
{116}{}{Ty mi chceš pomoct? Tomu vìøím. Co máš?}
{117}{}{Nyts.}
{118}{}{Tóodle!}
{119}{}{Vaut.}
{120}{}{Vidím, e s tebou ztrácím èas. Ztra se!}
{121}{}{Vaut. Vaut? Co je to vaut?}
{122}{}{Namnam.}
{123}{}{Nyts.}
{124}{}{Valt! Valt!}
{125}{}{Aha, ty chceš cukøíèek? Sorry, ale ádnej nemám. Sbohem.}
{126}{}{Aha Vault. No to je moc hezké. Moná by sis o tom mohl promluvit s mımi pøedstavenımi. Zrovna teï mám toti dost práce.}
{127}{}{Tady je to hroznì nebezpeènı. Velkı, zlı pøíšery ovládly tohle místo. Zkoušíme zachránit, co se dá, døív ne se sem vrátí.}
{128}{}{Ne jít! Ne jít!}
{129}{}{Uh, oh.}
{130}{}{Sbochem.}
{131}{}{Oukej. Pro mì a za mì si tu zùstaò. A se vrátí, dají si tì k veèeøi.}
{132}{}{Já zabít! Já zabít!}
{133}{}{Sbochem.}
{134}{}{Mùeš to zkusit. Nejsem si ale jistı, e budeš mít nìjakı úspìch. Hodnì štìstí.}
{135}{}{Uh oh je to správné slovo. Jsou hrozní. Snaíme se, aby porozumìli tomu, e lidé i monstra mohou ít spolu.}
{136}{}{Oh. OK. Sbochem.}
{137}{}{Prostì mi jen øekni, kdo jsi, ne ti rozbiju hlavu.}
{138}{}{Jsem Následovník. Kam všichni odešli?}
{139}{}{Jsem jeden z vás. A teï mì nech jít.}
{140}{}{Jsem }
{141}{}{. Zapamatuj si to!}
{142}{}{To nebude potøeba.}
{143}{}{CHCÍPNI!}
{144}{}{Pojï se mnou. Ukáu ti kam všichni odešli.}
{145}{}{Tak ty jsi Následovník?}
{146}{}{Samozøejmì! Kdo jinı bych mìl bıt?}
{147}{}{Ne, já jsem èlen Dìtí Katedrály.}
{148}{}{Neutahuj si ze mnì. Spletl jsem si tì s nìkım jinım. Pojï se mnou. Ukáu ti cestu.}
{149}{}{Nepamatuju si tì. Jak se jmenuješ?}
{150}{}{Jsem }
{151}{}{. Jak jsi na mì mohl zapomenout?}
{152}{}{Do toho ti nic není.}
{153}{}{Jsem tvoje noèní mùra.}
{154}{}{Je mi líto, poøád si na tebe nevzpomínám. Moná si na tebe vzpomene nìkdo jinı.}
{155}{}{Ano, vzpomínám si na tebe. Øíkali nám, abychom tì našli. Pomsta bude má!}
{156}{}{Jsi v mé zónì, take mi do toho je zatracenì moc. Mluv nebo je po tobì!}
{157}{}{Fajn. Jsem }
{158}{}{. U se ti rozsvítilo?}
{159}{}{Hmmm. Myslím . . . ZABÍT!}
{160}{}{Nech mì chvíli pøemıšlet.}
{161}{}{Musím se podívat. Je to }
{162}{}{. Správnì?}
{163}{}{Jo, ty pitomèe.}
{164}{}{Jo.}
{165}{}{Ne hlupáku. Má to bıt Smrt!}
{166}{}{Dobøe. Chtìl jsem se jen ujistit, e ti to správnì vytesáme na náhrobní kámen.}
{167}{}{Tak to tì nemùu nechat ít. Dobrou noc.}
{168}{}{A kdo jsi?}
{169}{}{Jsem Následovník. Kam všichni odešli?}
{170}{}{Jsem jeden z vás. A teï mì nech jít.}
{171}{}{Jsem }
{172}{}{. Zapamatuj si to!}
{173}{}{To nebude potøeba!}
{174}{}{CHCÍPNI!}
{175}{}{Smrt, jo? Spíš mi pøipadáš jak rádlo pro èervy.}
{176}{}{Jestli jsi pøítel, tak to doka.}
{177}{}{Pomohl jsem zlikvidovat Následovníky.}
{178}{}{Pomohl jsem zlikvidovat Rippery.}
{179}{}{Pomohl jsem zlikvidovat mutanty.}
{180}{}{Pomohl jsem zlikvidovat Dìti Katedrály.}
{181}{}{Opravdu? Myslím, e mùj šéf by o tom rád slyšel víc. Jdi najít Orfea. Odmìní se ti za tvou pomoc.}
{182}{}{Na nìkoho, kdo pøichází v míru, jsi dost velkı zabiják. Ale tihle Rippers dìlali spoustu potíí. Orfeo se ti za tvou námahu odmìní.}
{183}{}{Zabiješ neškodné zrùdy, které jsou jen koneènım dùsledkem destruktivní lidské povahy, a ještì máš tu drzost hlásat mír?}
{184}{}{Je mi líto. Byli hroznì oškliví, tak jsem je odstøelil.}
{185}{}{Na spoustì míst ubliovali lidem.}
{186}{}{Jo. A teï oddìlám tebe.}
{187}{}{Nechám tì ít. Myslím, e je lepší nechat tì, aby ses vypoøádal sám se sebou.}
{188}{}{Legraèní. Myslel jsem, e jsem pár z nich vidìl na ulici, jak se to tam snaí vyèistit od gangù.}
{189}{}{Oni napadli Blades?}
{190}{}{Co se stalo v Adytu?}
{191}{}{Chcípni, ty hade!}
{192}{}{Ten dobytek u není.}
{193}{}{To je dobøe. No, mìj se.}
{194}{}{A ani ty u nebudeš.}
{195}{}{To je taky místo, odkud tì znám. Je èas zaplatit!}
{196}{}{To jsi zase ty? Myslel jsem, e ses u pouèil. Ale jak vidím, bylo to pøíliš málo a pøíliš pozdì.}
