{100}{}{Vidíš Uèence Theslina z øádu Dìti Katedrály.}
{101}{}{Vidíš Uèence Slatera z øádu Dìti Katedrály.}
{102}{}{Vidíš Uèence Aunanut z øádu Dìti Katedrály.}
{103}{}{Vidíš Uèence Eikenkoffa z øádu Dìti Katedrály.}
{104}{}{Vidíš Uèence Spikavara z øádu Dìti Katedrály.}
{105}{}{Vidíš Uèence Varalone z øádu Dìti Katedrály.}
{106}{}{Vidíš Uèence Quinonosa z øádu Dìti Katedrály.}
{107}{}{Vidíš Uèence Ziegliffa z øádu Dìti Katedrály.}
{108}{}{Vidíš Uèence Jonesa z øádu Dìti Katedrály.}
{109}{}{Vidíš Uèence Smithe z øádu Dìti Katedrály.}

{110}{}{Nìkde tady v okolí jsou uloeny plány Následovníkù.}
{111}{}{Vsadím se, e Následovníci mají seznam všech svıch spojencù.}
{112}{}{Tihle blázni by mìli dùkladnì poznat, co to znamená zaplést se s naším bohem!}
{113}{}{Zmiz, a nedopadneš jako ti hloupí Následovníci.}
{114}{}{Nikdo nám nebude pøekáet ve vyèištìní Pustin.}
{115}{}{Nabídli jsme jim mír. Vybrali si válku.}
{116}{}{Odkud pøišel ten bláznivı ghúl?}
{117}{}{Nìkde by tu mìl bıt seznam všech Následovníkù.}
{118}{}{Naneštìstí tohle místo mùeme prohledávat jen ve dne.}
{119}{}{Musíme si dávat pozor na Nightkiny, kteøí tu slídí v noci.}
{120}{}{ijeme ve vzrušující dobì!}
