{100}{}{Vidíš zaneprázdnìnou kuchaøku, jak pøipravuje jídlo.}
{101}{}{Teï s tebou nemùžu mluvit. Mám moc práce, musím pøipravit tohle jídlo!}
{102}{}{Hmmm! To voní opravdu skvìle. A vsadím se, že to taky bájeènì chutná!}
{103}{}{Teï s tebou opravdu nemùžu mluvit. Mám moc práce, musím pøipravit tohle jídlo!}
{104}{}{No, díky moc. Jsem si jistá, že ti to bude chutnat. Díky za ten kompliment. Øeknu o tobì všem svým pøátelùm.}
