{100}{}{Vidíš Demetreho.}
{101}{}{Nazdar! Jak se vede? Jmenuju se Demetre, Demetre Romara, šéf sakra nejlepších karavan v pustinách. Hledáš práci?}
{102}{}{Hmmm, nevypadáš zrovna nejsilnìjší, ale... ale MUSÍŠ být hodnì zruènej støelec, abys tam venku pøežil! Sakra, možná, když to pøijde, budeš velkej bojovník!}
{103}{}{Vypadáš celkem zdravì.}
{104}{}{Vypadáš celkem silnì.}
{105}{}{Sakra, vypadáš jako silák!}
{106}{}{Sakra! Vypadá to, že bys mohl trhat skály rukama!}
{107}{}{Jo, máš nìco?}
{108}{}{Co je ti po tom?}
{109}{}{He?}
{110}{}{Nìkoho takového jako ty právì hledáme! Vypadáš, že tì tìší napìtí a vzrušení z bitvy, nemám pravdu?! Kulky hvízdají kolem hlavy, krájíš nepøátele vejpùl, kocháš se jejich strachem! Ahhhh, to je život! Vypadáš, že bys pro nás mohl hodnì udìlat a my za to hodnì zaplatíme! To si piš, že jo! Máme pár nových zakázek, pokud máš zájem, ale to urèitì máš, ne?!}
{111}{}{Jaký je plat?}
{112}{}{Zabiju všechno, co se nám postaví do cesty!}
{113}{}{Ne, díky.}
{114}{}{Potøebuju vodní èip.}
{115}{}{Co víš o mizejících karavanách?}
{116}{}{Musím jít.}
{117}{}{Ugggg uggg!}
{118}{}{Platíme 600 babek za kšeft! A to za každou cestu! Sakra, lidi øíkaj, že bereme ty nejnebezpeènìjší trasy, ale já øíkám, že jsou ty nejvíc vzrušující! Èlovìk potøebuje v životì trochu vzrušení, nemám pravdu? Jasnì, že mám!}
{119}{}{Sakra, to je pøesnì to, co hledám!}
{120}{}{Vždycky takhle øveš?}
{121}{}{Nebezpeèné?}
{122}{}{Ne díky, kámo.}
{123}{}{Sakra, jasný! Jdi si promluvit s Keri, je vedle, ta ti øekne, kdy se vydává na cestu pøíští karavana.}
{124}{}{Kámo? Vo èem to sakra mluvíš? Nesnaž se mì natáhnout.}
{125}{}{Proè, bojíš se hluku nebo co?}
{126}{}{Jo.}
{127}{}{Jen v noci.}
{128}{}{Ne, jen jsem byl zvìdav, jestli jsi hluchej nebo blbej.}
{129}{}{Ne, ale moje uši tím trochu trpí.}
{130}{}{Ha! Nebo oboje! Dobrá, skoè vedle za Keri, pokud chceš nìjakou práci.}
{131}{}{Jseš malej zasranej chytrák, co? Mì je to jedno! Dokud budeš chránit karavany, budu spokojen. Teï skoè vedle za Keri, pokud chceš nìjakou práci.}
{132}{}{Ha! Vtipálek! Jestli se nebojíš temnoty, pøijï za mnou.}
{133}{}{Jistì, že je to nebezpeèné — proè bych jinak cpal 600 babek?}
{134}{}{Aha, jo, sbohem.}
{135}{}{Stejnì tu práci vezmu.}
{136}{}{Vypadni, než ti utrhnu tu tvoji hlavu!}
{137}{}{Vrazím ti tvou hlavu do tvýho vlastního zadku!}
{138}{}{To je ono!}
{139}{}{Jistìže! Skoè vedle za Keri, ta dìlá rozpisy.}
{140}{}{Sakra, to je zklamání, ale dobrá.}
{141}{}{Jo! Líbíš se mi! Máš práci! Teï skoè vedle za Keri, napíše tì do nìkteré karavany.}
{142}{}{Hmm, vodní èip? Hmmm, nikdy jsem o nìm neslyšel. Zkus nìkterej z obchodù okolo, mají spoustu harampádí. Takže, chtìls práci?}
{143}{}{Dobrá, kolik platíte?}
{144}{}{Ne, vlastnì ne.}
{145}{}{Ne, zas tolik jich nezmizelo. Vlastnì jenom dvì. Vážnì nevím, proè si nejèastìji vybírají zrovna Far Go.}
{146}{}{Nìjaká podezøení?}
{147}{}{Co cesty a náklad?}
{148}{}{Jo, dík.}
{149}{}{Kdokoli to dìlá, musí mít pekelnì silnej oddíl. Naše karavany jsou dobøe ozbrojený a èlovìk by øekl, že by aspoò nìkdo utekl. Ale ne. Nezanechají vùbec stopy.}
{150}{}{Takže, kolik platíte?}
{151}{}{A co vaše cesty a náklad?}
{152}{}{Jo, dík.}
{153}{}{Kruci, cestujeme do nebezpeènìjších konèin než oni a naše zboží je lepší!}
{154}{}{Jak je lepší?}
{155}{}{Jenom zkouším, dík.}
{156}{}{Strašnì kecáš!}
{157}{}{Dobrá, možná - možná není lepší, ale máme pestøejší nabídku než oni.}
{158}{}{Jo, dík.}
{159}{}{Víš, Beth nìco kdákala o Páraèi. Na tvým místì bych se po tom porozhlídnul! Z jinejch zdrojù jsem slyšel, že se v noci severozápadnì od Hubu nìco potuluje.}
{160}{}{Platíme dobøe, abychom se ujistili, že práce bude splnìna! Najímáme jen ty nejlepší! Musíme mít spolehlivé posádky našich karavan!}
{161}{}{Jako já chtìl práci, ty uøvanej blbèe!}
{162}{}{Promiò, že jsem obtìžoval.}
{163}{}{Mohu dostat další práci, prosím?}
{164}{}{Huta?}
{165}{}{Øekl jsem, že tì nenajmeme!}
{166}{}{Bohužel, nebudu to s tebou riskovat!}
{167}{}{Ztrácíš tady èas!}
{168}{}{Prosím, pøestaò otravovat!}
{169}{}{Zapomeò na to.}
{170}{}{Demetre tì ignoruje.}
{171}{}{Kurva, nenajímám špinavý narkomany! Jestli chceš práci, radši zkus nejdøív vystøízlivìt!}
{172}{}{Nejsem závislák... Teda... Arg!}
{173}{}{Bla, bla!}
{174}{}{Prášky, co? Sakra, dobøe, že už tì nikdy nenajmeme!}
{175}{}{Sakra, ne! Ty si neuvìdomuješ, co je všechno v sázce! Nemùžeme si dovolit takový riziko! Sakra, nevím, jak se Far Go drží nad vodou po všech tìch zmizelejch karavanách!}
{176}{}{Sory, budeš se muset zeptat jinde. Nemùžu si dovolit vzít dalšího.}
{177}{}{Vypadni, než se z tebe pobleju!}
{178}{}{Hej! Co si myslíš, že dìláš?}
{179}{}{To vede do našeho skladištì.}
{180}{}{Jdou otevøít jenom z druhý strany.}
{181}{}{Ty jsi ale podivín.}
{182}{}{Ztrácíš èas.}
{183}{}{Ignoruje tì.}
{184}{}{Takže? Chceš práci nebo ne? Nabízím ti zábavu a prachy! A obojího není nikdy dost!}
{185}{}{Jo, jo. Kolik to bylo?}
{186}{}{Zabiju všechno, co se nám postaví do cesty!}
{187}{}{Ne, dík.}
{188}{}{Potøebuju vodní èip.}
{189}{}{Co víš o ztracených karavanách?}
{190}{}{Musím jít.}
{191}{}{Ruk luk?}
{192}{}{Hej, dobrá práce minule -- skvìle! Potøebovals nìco?}
{193}{}{Jo, chtìl jsem další práci.}
{194}{}{Potøebuju vodní èip.}
{195}{}{Co víš o ztracených karavanách?}
{196}{}{Nic. Jenom jsem chtìl pozdravit.}
{197}{}{Nic, sbohem.}
{198}{}{Pøišli jsme o celý náklad! Obávám se, že tì už najmout nemùžeme.}
{199}{}{Máš kliku, málem jsme pøišli o karavanu, kterou jsi opustil! Obávám se, že tì už nikdy nemùžeme najmout.}
{200}{}{Nenajímáme, tak co chceš?}
{201}{}{Vodpal! Nenajímáme.}
{202}{}{Potøebuju vodní èip.}
{203}{}{Co víš o ztracených karavanách?}
{204}{}{Chci aby ses mi ztratil z oèí!}
{205}{}{Chci tvoji hlavu napíchnutou na kùlu!}
{206}{}{Hmmm.}
{207}{}{Ruk luk?}
{208}{}{Myslíš si, že jsi drsnej? Nerozesmívej mì!}
{209}{}{Dobrá, mìl by sis promluvit s mou dcerou Keri; ona se o to všechno stará! Je ve vedlejší místnosti.}
{210}{}{Už jsem øekl. Promluv si s Keri, je vedle.}
{211}{}{Tvá dcera?}
{212}{}{Ta nechutnost je tvoje dcera? To mnohé vysvìtluje!}
{213}{}{Jo.}
{214}{}{Ano, je to moje pýcha a radost! Není krásná? Promluv s ní, jestli chceš další práci. Jednou... snad brzy, budu moci skonèit s touhle prací a ona to po mnì pøevezme.}
{215}{}{Ne, pokud budete oba mrtví!}
{216}{}{Jo, dík.}
{217}{}{Troufáš si urážet cizí rodinu? Mìl bych ti vyrvat srdce z tìla!}
{218}{}{Omlouvám se, jen jsem žertoval!}
{219}{}{Udìlám víc, než jen urážky!}
{220}{}{Pøíliš pozdì na omluvy! [Jeho tváø zrudne... pak tichým, ovládajícím se hlasem.] Vypadni, nebo budu muset splnit svoje výhrùžky!}
{221}{}{Je to ubohý pokus o výhrùžku?}
{222}{}{To není výhrùžka! Brzo zemøeš!}
{223}{}{Jo, dobrá, zkus to!}
{224}{}{Ne, promiò, ale musím už jít. Nashle!}
{225}{}{Jo, musím to pøiznat, slyšíval jsem líp.}
{226}{}{Jo, já vím, sbohem.}
{227}{}{Jo, poøád musíš zemøít!}
{228}{}{Hu, tak jo.}
{229}{}{Co je, na co èekáš? Karavany èekají!}
{230}{}{Ještì nejsou pøipraveny k odjezdu.}
{231}{}{Ještì pøedtím musím nìco udìlat.}
{232}{}{Potøebuju vodní èip.}
{233}{}{Co víš o ztracených karavanách?}
{234}{}{Jo, zatím zdar.}
{235}{}{Rik rok?}
{236}{}{Roerow?}
{237}{}{Do háje! Propásnul jsi dobrou akci! Urèitì se na karavanu chystají mraky šelem, lidí a jiných potvor! Nic se nevyrovná poøádné pøestøelce! Na — vezmi si zatím tohle na hraní, než bude nachystaná další karavana. [Podává ti tøíštivý granát.]}
{238}{}{Sakra! Vyjedou vùbec nìkdy naše karavany?}
{239}{}{A co vaše loï?}
{240}{}{Moc se nezdržuj.}
{241}{}{Keri, jsme zapsaní?}
{242}{}{Musíš zabít nepøátele døív, než tì dostanou!}
{243}{}{Nic se nevyrovná ždímání duší z nepøátel!}
{244}{}{Sakra seš!}
{245}{}{Kurva, kde mám zbraò?!}
