{100}{}{Vidíš rolníka.}
{101}{}{Vidíš Phila.}
{102}{}{To není mùj pes!}
{103}{}{K èertu, máš pravdu, oddìlej tu bestii!}
{104}{}{Bejt tebou, tak bych tı potvoøe nevìøil.
 Ta vìc je zabiják.}
{105}{}{Pane,}
{106}{}{Sleèno,}
{107}{}{ byl bych opravdu šastnı, kdybyste mì zbavil toho zatracenıho psa.}
{108}{}{Proè?}
{109}{}{Nah, takové hlouposti mì nezajímají.}
{110}{}{Kde se tady vzal?}
{111}{}{Hnnn.}
{112}{}{Mùeš to tøeba umluvit k smrti.}
{113}{}{Protoe nás to nepustí zpátky do baráku, proto.}
{114}{}{Ok.}
{115}{}{Není to tvùj pes?}
{116}{}{To bylo zvıøe toho poutníka. Kdy zemøel, tak tenhle proklatej pes 
 usadil svou podìlanou prdel na práh mejch dveøí a nechce odejít. 
 Takhle tu sedí u pár dní.}
{117}{}{Oh.}
{118}{}{Co to bylo za poutníka?}
{119}{}{Jak ten poutník vypadal?}
{120}{}{Nevím. Òákej chlápek. Øíkal, e pøišel z vıchodu. Jako by se nìkdo dostal pøes ty mrtvı zemì na vıchodì. Zapletl se s Gizmem, snail se mu lézt do kšeftù.}
{121}{}{Take Gizmo poslal pár svejch chlapù, seøezali ho a hodili ze støechy kasína. Ten pitomec si zlomil vaz a chcíp. Pes byl pìknì nasranej.}
{122}{}{Jak ten poutník vypadal?}
{123}{}{Chlápek byl vysokej, tmavovlasej, trochu šedivìjící po stranách. Celej obleèenej v èernı kùi, jako by to v poušti byl dobrej nápad, a nosil brokovnici.}
{124}{}{Mìl òákej divnej pøízvuk. Ten pes byl jeho stálej parák, chodil s ním všude.}
{125}{}{Zajímavı pøíbìh.}
{126}{}{Nenávidím toho psa.}
{127}{}{Dík za pomoc.}
{128}{}{Získáváš 50 zkušenostních bodù.}
