{100}{}{Vidíš Snakea.}
{101}{}{Vidíš Dolgana.}
{102}{}{}
{103}{}{}
{104}{}{Vidíš èlena Blades.}
{105}{}{Vidíš èlena Blades.}
{106}{}{Tohle musí bıt Books.}
{107}{}{Tohle musí bıt Scars.}
{108}{}{Tohle musí bıt Gunner.}
{109}{}{Tohle musí bıt Twitch.}
{110}{}{Tohle musí bıt Hammer.}
{111}{}{Tohle musí bıt Razor.}
{112}{}{Zmiz! Tohle je jenom pro opravdové bojovníky.}
{113}{}{Take ty si myslíš, e si to mùeš rozdat s Tanklerem a jeho neschopy?
 Dívej, nauèím tì zacházet s touhle zbraní.}
{114}{}{Teï u ti to jde o nìco líp. Jdi a nakopej Tanglera do zadku i za mì.}
{115}{}{Dobrá práce, to vyøízení Regulátorù. Co pro tebe mùu udìlat?}
{116}{}{Mùeš mì nauèit nìjakı další triky s touhle zbraní?}
{117}{}{Jak se dostanu ke Gun Runnerùm?}
{118}{}{Nic, díky.}
{119}{}{Jasnì. Ale zabere to vìtšinu dne s malım vısledkem. Ještì poøád to chceš?}
{120}{}{Jo.}
{121}{}{Ne.}
{122}{}{Tady to máš. Malé vylepšení. Pøeju ti hodnì štìstí.}
{123}{}{Jistì. Vra se, kdy budeš potøebovat procvièit.}
{124}{}{Vypadá to, e jsme vpustili blázna. Dobrá, jestli se tam chceš dostat, je tam tenkı prùchod pøes pøíkop. Najdi ho a makej, co mùeš. Moná se ti ho podaøí pøebìhnout.}
{125}{}{Díky.}
