{100}{}{Vidíš cestujícího kupce asijského pùvodu.}
{101}{}{Vidíš Duca, cestujícího kupce.}
{102}{}{Zdravím tì, poutníku. Jmenuji se Duc, míøím do Shady Sands za obchodem. Možná by tì zajímalo moje zboží?}
{103}{}{Co nabízíš?}
{104}{}{Navštìvuješ Shady Sands èasto?}
{105}{}{Pff!}
{106}{}{Dovol, ukážu ti.}
{107}{}{Ano, Shady Sands leží na mé bìžné obchodní stezce. Mùžeš se k nám pøipojit kvùli svému bezpeèí, pokud máš zájem.}
{108}{}{Jistì, to zní dobøe.}
{109}{}{Ne, díky.}
# Old response to 114 "None of your business" was 110 "Oh, sorry -- didn't realize you were that stupid."
{110}{}{Hmph! Netipoval jsem tì na arogantního kreténa. Kliï se mi z oèí.}
{111}{}{Zabere to maximálnì dva dny. Pojïme!}
{112}{}{SHADYW.MAP}
{113}{}{Moc lidí nezvládne pustinu bez doprovodu. Kdo jsi?}
{114}{}{Do toho ti nic není.}
{115}{}{Jsem }
{116}{}{.}

#TRANSLATION NOTE: 117 & 132 are for Stupid characters,
# they are shouting their name as a greeting. For example "Me John!"
{117}{}{Já }
{132}{}{!}

{118}{}{Buï zdráv! Co pro tebe mohu udìlat?}
{119}{}{Mùžu se k vám pøidat do Shady Sands?}
{120}{}{Co nabízíš?}
{121}{}{Nic, díky.}
{122}{}{Co chceš?}
{123}{}{Nic, díky.}
{124}{}{Co nabízíš?}
{125}{}{Pff!}
{126}{}{Mìl bys být opatrný, když cestuješ bez pøátel. V poslední dobì zmizelo z Shady Sands pár lidí.}
{127}{}{Hej, slyšel jsem, jak jsi zachránil jednu ženu z Shady Sands. Bravo.}
{128}{}{Oh, omlouvám se. Neuvìdomil jsem si, že jsi retard.}
{129}{}{Díky a mìj se.}
{130}{}{Rumph!}
{131}{}{Erf!}
