{100}{}{Vidíš Dumara, akolytu Dìtí katedrály.}
{101}{}{Vítejte, poutníku. Slyšeli jsme pøíbìhy o nìkom, kdo køižuje pustinu. Jak vám dnes mùžeme být k službám?}
{102}{}{Uh? Arrooo?}
{103}{}{Pustina je drsné místo. Byl jsem tìžce zranìný. Mùžete mi s tím pomoci?}
{104}{}{Chci tebe i celou tu vaši sebranku nechat pobít!}
{105}{}{Øekni mi pøíbìh.}
{106}{}{Huh? Moc dobøe jsem ti nerozumìl. Mùžeš to prosím zopakovat?}
{107}{}{Na koho se musím obrátit, abych se stal èlenem tohoto øádu?}
{108}{}{Pøál bych si pochopit moudrost, na které jste ty a tvoji kolegové založili tuto víru.}
{109}{}{Je mi líto, ale v tuto chvíli jsem pøíliš zaneprázdnìn na to, abych vám vyprávìl celý pøíbìh Dìtí katedrály. Nechávají mì èistit lavice. Pokud potøebujete informace, promluvte si s Laurou.}
{110}{}{Omlouvám se, ale vaše slova jsou pro mì pøíliš vznešená, než abych pochopil, co jste øekl. Možná vám naši moudøejší následovníci, jako tøeba Laura, budou schopni pomoci lépe než já.}
{111}{}{Je mi opravdu líto, že slyším o vašem zranìní. Bohužel, jsem pouze akolyta a nejsem schopen vám pomoci s léèením. Pouze øádní èlenové dostávají školení v léèitelském umìní.}
{112}{}{Ach, dítì, zdá se, že vy a já mluvíme na úplnì jiných úrovních. Možná když si promluvíte s Laurou, bude vám schopná pomoci lépe než já. Mír s vámi, dítì.}
{113}{}{Promluvte si s Laurou. Dokáže vám pomoci lépe než já.}
{114}{}{Jsme mírumilovní lidé. Prosím, neprolévejte na tomto svatém místì krev.}
{115}{}{Byl jednou jeden malý cestovatel, který rád chodil po svìtì. Jednou pøišel k mladé dámì jménem Laura a požádal ji, aby mu øekla pøíbìh. Konec.}
{116}{}{Dumar tì prosí, abys pøestal se svými krutými útoky.}
