# Random Encounter - Old Quack

{100}{}{Vidíš šarlatána.}
{101}{}{Vidíš doktora Cleave O. Bukera.}
{102}{}{Vidíš prodejce hadího oleje.}

# dumb dude
{103}{}{Vidíš velkého šamana.}

# map enter
{110}{}{V dálce vidíš osamìlého cestovatele s pomalovanım vozem.}

# floats
{150}{}{Já ti ukáu, ty zdegenerovanej vidláku!}

# Talk
{1000}{}{Pøistup blí, poutníku! Vítej, vítej! Trpíš syfilisem? Støelná zranìní? Skalpování? Otoky? Kurdìje? Moná vzteklina nebo... hadí kousnutí? Pak neváhej ani minutu, doktor Cleave O. Buker má pro tebe ten správnı lék!}
{1001}{}{Ah! Vítej, vítej! Pøistup blí, doktor Cleave O. Buker má pro tebe pøesnì tu správnou medicínu!}
	{1010}{}{To zní jako pøesnì to, co teï potøebuju! Uka mi, co máš.}
	{1011}{}{Uh, WOW!}
	{1020}{}{OK, ale doufám, e nehodláš plıtvat mım èasem.}
	{1030}{}{Ne, díky.}
	{1031}{}{Uh, gaga.}

{1100}{}{Mu, kterı ví, co je pro nìj dobré! To se mi líbí! Pohleï na tento stoprocentnì originální a na dvì stì procent úèinnı zázraènı lék. Zaruèuji, e nikde na svìtì ho tak levnì neseeneš!}
{1101}{}{ena, která ví, co je pro ni dobré! To se mi líbí! Pohleï na tento stoprocentnì originální a na dvì stì procent úèinnı zázraènı lék. Zaruèuji, e nikde na svìtì ho tak levnì neseeneš!}
{1102}{}{Pohleï a asni!}
	{1110}{}{[Pokraèovat]}

{1200}{}{Tento vysoce kvalitní produkt se pouívá PO CELÉM SVÌTÌ, proti revmatismu a problémùm s játry! Je to také lék na zaívací potíe a VŠECHNY krevní onemocnìní!...}
	{1210}{}{Víš ty co? Uka mi ještì jednou svoji nabídku.}
	{1211}{}{Uhm...}
	{1220}{}{Jo jo, to u jsem slyšel. Nashle.}
	{1221}{}{Sbohem!}

{1300}{}{Plıtvat tvım èasem?! Drahı pane! Ujišuji tì, e má medicína ti ivot naopak prodlouí!}
{1301}{}{Plıtvat tvım èasem?! Drahá madam! Ujišuji tì, e má medicína ti ivot naopak prodlouí!}
	{1310}{}{[Pokraèovat]}
