{100}{}{Vidíš barmana.}
{101}{}{Jo, co chceš?}
{102}{}{Vodu.}
{103}{}{Pivo.}
{104}{}{Koøalku.}
{105}{}{Cokoli, co mì voddìlá nejrychlejc.}
{106}{}{Nic.}
{107}{}{He?}
{108}{}{Jestli nemáš zátky, tak koukej zmizet!}
{109}{}{Jak chceš.}
{110}{}{Myslím, e máš dost, kámo.}
{111}{}{Myslím, e máš dost, dámo.}
{112}{}{Jo... zapomeò na to.}
{113}{}{Bude to za dvì zátky.}
{114}{}{Jasnì.}
{115}{}{Ne, díky.}
{116}{}{Bude to za 5.}
{117}{}{Jasnì.}
{118}{}{Bude to za 10.}
{119}{}{Hmmm, pro nìkoho tvıch rozmìrù...}
{120}{}{ }
{121}{}{ deset}
{122}{}{ dvacet}
{123}{}{ tøicet}
{124}{}{ ètyøicet}
{125}{}{ padesát}
{126}{}{ šedesát}
{127}{}{ sedmdesát}
{128}{}{ osmdesát}
{129}{}{ devadesát}
{130}{}{ sto}
{131}{}{ zátek by snad mìlo staèit.}
{132}{}{Perfekt! To bude }
{133}{}{ zátek navíc.}
{134}{}{Sem s tím.}
{135}{}{Mám dost.}
{136}{}{Na. (Barman ti pøisune špinavej plecháèek plnej jakési}
{137}{}{ kalné vody. Po vypití cítíš podivnou}
{138}{}{ pachu v puse.)}
{139}{}{Tady je to. (Barman ti podává špinavı plechovı pohár plnı }
{140}{}{ stejné kalné vody, a po jejím vypití si vzpomínáš}
{141}{}{ jak divnì chutnala naposledy...)}
{142}{}{To by mìlo bıt zábavné... (Barman se s panáky zbyteènì necourá}
{143}{}{ a ty ztrácíš pøehled. Po chvíli slyšíš tupı náraz, a pak}
{144}{}{ zjišuješ, e leíš tlamou k zemi na podlaze...)}
{145}{}{A jedeme znova... (Barman srovnává panáky, zatímco}
{146}{}{ všichni okolo baru skandují...)}
{147}{}{ ...}
{148}{}{ ...}
{149}{}{ ...}
{150}{}{ (Brzy se všechno zatmívá...)}
{151}{}{Nevypadal jsi jako nìkdo, kdo se s tím}
{152}{}{ dokáe poprat.}
{153}{}{Škoda, všichni jsme se tìšili, e tì uvidíme}
{154}{}{ znovu 'v akci'.}
{155}{}{Ouu... u se nám znova nepøedvedeš? Dobrá,}
{156}{}{ tady máš svı pivo. Ještì nìco?}
{157}{}{Jsi si jistı, e odoláš pokušení? Minule jsi}
{158}{}{ se docela pøedvedl. Dobrá, tady to je. (Barman ti podává}
{159}{}{ láhev koøalky.) Ještì nìco?}
{160}{}{Tady je to. (Barman ti podává láhev piva.) Ještì}
{161}{}{ nìco?}
{162}{}{Per to do mì zas!}
{163}{}{Tady je to. (Barman ti podává láhev koøalky.)}
{164}{}{ Ještì nìco?}
{165}{}{Máš pocit, e ti nìco chcíplo v hubì.}
{166}{}{Máš dojem, e ti brzo vybuchne hlava.}
##
##
##
{167}{}{Vidíš krupiéra u kostek.}
{168}{}{Vidíš krupiéra u rulety.}
{169}{}{Vidíš hrací automat.}
{170}{}{Vypadá to, e sázky nejsou úplnì v poøádku.}
{171}{}{Myslíš si, e kostky jsou falešné.}
{172}{}{Myslíš si, e stùl je podvodnì upravenı.}
{173}{}{Vaše sázky. }
{174}{}{5.}
{175}{}{15.}
{176}{}{25.}
{177}{}{50.}
{178}{}{Ne, díky.}
{179}{}{Hrmm.}
##
## SLOT MACHINES
##
{180}{}{Sory, nejsi ve stavu, abys mohl dávat sázky. (Díváš se}
{181}{}{ na hru a jsi totálnì zmatenı.)}
{182}{}{Je mi líto, snad to pøíštì vyjde.}
{183}{}{Vıhra! (1:1.)}
{184}{}{Vıhra! (Zdvojnásobil jsi vklad.)}
{185}{}{Vıhra! (Ztrojnásobil jsi vklad.)}
{186}{}{Na hru potøebuješ peníze, kámo.}
{187}{}{Na hru potøebuješ peníze, krásko.}
{188}{}{Vypadá to, e sázky jsou v poøádku.}
{189}{}{(Kolik chceš vsadit?)}
{190}{}{1.}
{191}{}{2.}
{192}{}{3.}
{193}{}{4.}
{194}{}{5.}
{195}{}{Nic.}
{196}{}{(Nevíš, co s tím, ale vypadá to opravdu pìknì.)}
{197}{}{(Prohra.)}
{198}{}{(Push.)}
{199}{}{(Zdvojnásobil jsi vklad.)}
{200}{}{(Ztrojnásobil jsi vklad.)}
{201}{}{(Nemáš dost penìz.)}
{202}{}{Máš u sebe }
{203}{}{ zátek. Kolik chceš vsadit?}
{204}{}{ Chceš si ještì zahrát?}
##
## Sduibek, Fallout Fixt
##
{205}{}{Pøi prvním otoèení jsi prohrál všechny peníze, ale vyhrál jsi zpátky }
{206}{}{ zátek v Radioaktivním kole!}
{207}{}{Vıhra! Získal jsi zpátky svou sázku a vyhráš }
{208}{}{Ding Ding Ding! Zdvojnásobil jsi svou sázku, a k tomu ještì vyhráváš }
{209}{}{JACKPOT! Ztrojnásobil jsi svou sázku, a k tomu ještì vyhráváš }
{210}{}{ zátek v Radioaktivním kole!}
{211}{}{ zátku v Radioaktivním kole.}
{212}{}{ zátku v Radioaktivním kole.}
