{100}{}{Vidíš farmáøe.}
{101}{}{Zdravím tì, cizinèe. Obdivuješ mou úrodu?}
{102}{}{Dobré ráno!}
{103}{}{Dobré odpoledne!}
{104}{}{Dobrý veèer!}
{105}{}{Krásný den, což?}
{106}{}{Ta pùda je mnohem zdravìjší, než vypadá.}
{107}{}{Snažím se zachránit ty stromy, a snad se to daøí.}
{108}{}{Tam mìl být vùz s hnojivem. Teï jsou tam prachy.}
{109}{}{Pojï dál, je tu dost místa.}
{110}{}{Venku už je trochu chladno; pøijmi místo.}
{111}{}{Farmaøení mi vyhovuje.}
{112}{}{Vìdìls, že rostliny prospívají lépe, když se k nim hezky chováš?}
{113}{}{Kéž by bylo k dispozici trochu víc pùdy.}
{114}{}{Víš, že tu bývaly ohromné zdroje pitné vody?}
{115}{}{Èetl jsem o øekách. Moc bych si pøál, aby tu kolem polí jedna tekla.}
{116}{}{Kéž by byly dny delší, je tady tolik práce.}
