{100}{}{Vidíš Jerryho, zvìda Následovníkù.}
{101}{}{Vidíš Basbeara, zvìda Následovníkù.}
{102}{}{Vidíš Richarda, zvìda Následovníkù.}
{103}{}{Vidíš Jasona, zvìda Následovníkù.}
{104}{}{Vidíš Shadow, zvìda Následovníkù.}
{105}{}{Vidíš Lynne, zvìda Následovníkù.}
{106}{}{Vidíš Gwendolyne, zvìda Následovníkù.}
{107}{}{Vidíš Rosu, zvìda Následovníkù.}
{108}{}{Vidíš Elizabeth, zvìda Následovníkù.}
{109}{}{Vidíš Rebecu, zvìda Následovníkù.}
{110}{}{Kdo prochází sínìmi Následovníkù?}
{111}{}{Huh?}
{112}{}{Jsem }
{113}{}{. Pøicházím v míru.}
{114}{}{Jsem }
{115}{}{. Váš nièitel.}
{116}{}{Kdo jsou Následovníci?}
{117}{}{OK. Vidím, e jsi trochu pomalejší. Kdo ty?}
{118}{}{Já }
{119}{}{. Ty mrtev.}
{120}{}{Já }
{121}{}{. Já pomoc.}
{122}{}{Já zabít!}
{123}{}{Já }
{124}{}{. Já jít.}
{125}{}{Chceš pomoci? Myslím, e si budeš muset promluvit s Nicole nebo Jakem, jestli nám chceš pomoct. Ti mají víc èasu babrat se s pomalımi lidmi.}
{126}{}{OK. Prostì se tu dr dál od prùšvihù.}
{127}{}{Pomùeš ukonèit zlo Dìtí?}
{128}{}{Ano. Vyvradím tu svoloè.}
{129}{}{Ne. Radši zabiju vás, sráèi.}
{130}{}{Kdo jsou Dìti?}
{131}{}{Proè bych mìl chtít zabíjet dìti?}
{132}{}{Vıbornì! Jdi si promluvit s Nicole, ta ti øekne, jak nám mùeš pomoct.}
{133}{}{Dìti jsou okultní skupina vyznávající nìjakého temného boha. Osobnì si myslím, e to zavání peklem.}
{134}{}{Zabiju je.}
{135}{}{Nevím. Zdá se mi, e jsou na mì pøíliš silní.}
{136}{}{Jak mohu pomoct?}
{137}{}{Zapomeò na to! Nijak vám nepomùu.}
{138}{}{Jsou velmi silní, ale myslím, e èlovìk s tvımi schopnostmi bude schopen uspìt a pomoct nám je znièit.}
{139}{}{Tak já to tedy udìlám.}
{140}{}{Ne. Nemyslím si, e bych pomohl.}
{141}{}{Jak myslíš. Jestli zaberou pustinu, neøíkej, e jsme tì nevarovali.}
{142}{}{Kdy si promluvíš s Nicole, øekne ti víc o tom, co se dá dìlat, abychom je zastavili.}
{143}{}{Dìkuji. Nashledanou.}
{144}{}{Ne dìti. Ani by nás nenapadlo jim ublíit. Ne. Tohle jsou Dìti katedrály. Banda pìknì hnusnıch grázlù.}
{145}{}{V tom pøípadì, jasnì – sejmu je.}
{146}{}{Oh. Já myslel, e mluvíte o nìjakıch mròatech. Ale stejnak. Nemyslím si, e pomùu.}
{147}{}{Co mi mùete øíct o tìch Dìtech?}
{148}{}{My jsme Následovníci apokalypsy. Snaíme se pøinést mír do pustiny.}
{149}{}{To zní dobøe. Hodnì štìstí.}
{150}{}{Jak to hodláte udìlat?}
{151}{}{To zní dost nepravdìpodobnì.}
{152}{}{Snaíme se pøinést toleranci lidem v pustinì, tìm nìkolika nešastníkùm, kteøí zmutovali kvùli lidské destruktivní nátuøe.}
{153}{}{To potom hodnì štìstí.}
{154}{}{V prùbìhu historie jsme nikdy nebyli schopni bıt tolerantní. Proè myslíš, e došlo k té Válce?}
{155}{}{To jsou jen kecy!}
{156}{}{Máš pravdu, kdy øíkáš, e my, jako lidé, jsme byli ponìkud pøedpojatí. Ale stále je tu nadìje.}
{157}{}{Pak tedy hodnì štìstí.}
{158}{}{Myslím, e máte pravdu. Podívej, tohle ti moná pomùe bıt trochu míò zaujatı.}
{159}{}{A je to jak chce, o tvùj názor nikdo neádal. Sbohem.}
{160}{}{Cynik v našem støedu. Jsem si jist, e máš své dùvody. Nehledì na to, jsem si jist, e dokáeme vnést jistı druh porozumìní.}
{161}{}{Pak tedy hodnì štìstí. Sbohem.}
{162}{}{Slyšel jsem, e Dìti získávají nìkterá naše tajemství. Zajímalo by mì, jak se to dìje?}
{163}{}{Nìkde tu musí bıt špión.}
{164}{}{Já vím. To já jim prodávám vaše tajemství.}
{165}{}{Myslím, e máte moc ivou pøedstavivost. Jak by mohli nìco vìdìt?}
{166}{}{Skuteènì? Sám jsem o tom dost pøemıšlel, ale bál jsem se, e bych pro svou teorii nezískal moc podpory.}
{167}{}{Máte nìjaké stopy, kdo by to mohl bıt?}
{168}{}{Jsem rád, e to vím. Díky za tvùj èas.}
{169}{}{Ty jsi dvojitı agent!!!}
{170}{}{Ne tak docela. Jediné, co mì napadá, je, e ta osoba by musela mít pøístup k nìjakım informacím a zároveò monost jít ven. Moná by ses chtìl podívat na naše zasvìcence a zvìdy.}
{171}{}{Díky. Sbohem.}
{172}{}{Nicole bude potìšená, a se dozví, e jsem toho agenta zabil.}
{173}{}{Urèitì máš pravdu. Díky es mi otevøel oèi.}
{174}{}{Já myslím, e ty jsi dvojitı agent. Snaíš se mì zmást. A teï ZEMØEŠ!}
{175}{}{Skvìlá práce, jak jsi sejmul toho agenta. Teï bychom mohli mít šanci proti tìm Dìtem.}
{176}{}{Hodnì štìstí.}
{177}{}{Mohu ti pomoci trénovat, abys byl ještì lepší v boji.}
{178}{}{Vánì? To by bylo skvìlé.}
{179}{}{Hleï. Moná to ti pomùe bojovat.}
