{100}{}{Vidíš sestru Francis.}
{101}{}{Áhoj! Oh, to jsi ty! Doufám, e tu nejsi, abys mì zabil. Nevadilo by ti poèkat, ne dokonèím meditaci?}
{102}{}{Oh, to jsi zase ty. Nechci bıt neomalená, ale medituji...}
{103}{}{Promiò, mohl bys odloit zbraò? Nemùu v klidu meditovat, kdy hledím, uh, tváøí v tváø jisté smrti. Mnohokrát dìkuji.}
{104}{}{Víš, jsou lidé, kteøí o tobì øíkají velmi nepìkné vìci. Mìl bys s tím nìco dìlat...}
{105}{}{Áhoj. Medituji. Nevšiml jsi si? Mùu ti nìjak pomoci?}
{106}{}{Jasnì. Zdá se, e je tu nìco neobvyklého?}
{107}{}{Podìlila by ses se mnou o nìkterou z tvıch oblíbenıch meditací?}
{108}{}{Kdo tu velí?}
{109}{}{Kde mohu najít Vùdce?}
{110}{}{Hledám vìtší mnoství likérù. Rád bych ho odstranil z areálu...}
{111}{}{Máš nìjakou munici?}
{112}{}{Pomoci! Mì?}
{113}{}{Ahoj, bratøe. Mohu ti pomoci?}
{114}{}{Áhoj, sestro. Mohu ti pomoci?}
{115}{}{Jasnì. Zdá se, e je tu nìco neobvyklého?}
{116}{}{Podìlila by ses se mnou o nìkterou z tvıch oblíbenıch meditací?}
{117}{}{Kdo tu velí?}
{118}{}{Kde mohu najít Vùdce?}
{119}{}{Hledám vìtší mnoství likérù. Rád bych ho odstranil z areálu...}
{120}{}{Máš nìjakou munici?}
{121}{}{Pomoci! Mì?}
{122}{}{Jasnì. Zdá se, e je tu nìco neobvyklého?}
{123}{}{Podìlila by ses se mnou o nìkterou z tvıch oblíbenıch meditací?}
{124}{}{Kdo tu velí?}
{125}{}{Kde mohu najít Vùdce?}
{126}{}{Hledám vìtší mnoství likérù. Rád bych ho odstranil z areálu...}
{127}{}{Máš nìjakou munici?}
{128}{}{Pomoci! Mì?}
{129}{}{Otec Morpheus u nám dlouho nedal kázání. A to je škoda, protoe já tak miluji jeho øeèi a zdá se, e kadı je velmi zamìstnán nìjakou køíovou vıpravou.}
# Space of " Now" at beginning of line is intentional!
{130}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{131}{}{Mohla bych, ale ti, kdo prošli procesem Sluebníkù, jsou o mnoho lepší ne já... Jejich mysli jsou na Vùdce daleko více soustøedìny ne má. Moná, a se zmìním, budu lepší.}
# Space of " Now" at beginning of line is intentional!
{132}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{133}{}{Vdy to je otec Morpheus! Je to tak skvìlı øeèník, e díky nìmu Mír a Jednota úplnì oívají, a kdy mluví, tak ty Svaté plameny prostì vidím!}
{134}{}{Ten otec Morpheus, ten umí ale mluvit; a je také pìknı!}
{135}{}{Myslím, e to je jedno z tìch vnitøních tajemství, o kterıch knìí mluví nahoøe ve vnitøní svatyni. Zatím se mi nedostalo té vısady onoho zjevení, ale makám na tom!}
# Space of " Now" at beginning of line is intentional!
{136}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{137}{}{Proboha! Alkohol a drogy tady! Urèitì se mılíš. To by Vùdce nikdy nedovolil. Chce, aby všichni jeho následovníci mìli mysl zdravou a èistou.}
# Space of " Now" at beginning of line is intentional!
{138}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{139}{}{Myslím, e svatá munice je k mání v chrámovém obchodì se suvenıry...}
# Space of " Now" at beginning of line is intentional!
{140}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{141}{}{Ne, proè. ádnou pomoc. Sbohem.}
{142}{}{Buï zdráv, bratøe. Ne, meditovala jsem jako správná zasvìcenka a èekala na køest od Sluebníkù. Jsem si jista, e tu není èeho se bát.}
{143}{}{Buï zdráva, sestro. Ne, meditovala jsem jako správná zasvìcenka a èekala na køest od Sluebníkù. Jsem si jista, e tu není èeho se bát.}
{144}{}{Vùdce je mùj pøítel. Jednota je prosperita. Mír je prosperita. Mír a Jednota pøicházejí s poslušností. Poslušnost dokazuje podrobení se autoritì...}
{145}{}{Kdo pøijme, bude pokøtìn Svatım Plamenem, jen vìrní neshoøí. Kdo projde Ohnìm, ani by uhoøel, bude mít ivot vìènı...}
{146}{}{Doufám, e jsem o nic nepøišla...}
{147}{}{To mì zkoušíš? To je Vùdce, ne?}
{148}{}{Slyšela jsem, e Vùdce mùeš najít ve Svatém Ohni, kde èeká dole na Jednotu a Mír, a e ije v srdcích a myslích všech ctnostnıch lidí...}
{149}{}{Nevím, co z toho je metafora. Moná je všude.}
{150}{}{Ale bratøe, nic takového neznesvìcuje Katedrálu. Øekla bych to hned vyšším knìím, kdyby se takové høíchy páchaly.}
{151}{}{Ale sestro, nic takového neznesvìcuje Katedrálu. Øekla bych to hned vyšším knìím, kdyby se takové høíchy páchaly.}
{152}{}{Jsem samozøejmì ozbrojená, pokud rozum neukonejší naše nepøátele, ale neozbrojuji se zbyteènì. V Suvenırech nemají munici?}
{153}{}{Oh ne, bratøe. Nepotøebuji asistenci. Prosím, omluv mì.}
{154}{}{Oh ne, sestro. Nepotøebuji asistenci. Prosím, omluv mì.}
{155}{}{Bylo mi øeèeno, e Mír a Jednota, kterou hledáme pro všechny bytosti, je neobvyklá, ale doufám, e tomu tak nezùstane dlouho.}
# Space of " Now" at beginning of line is intentional!
{156}{}{ Teï, pokud mne omluvíš, se musím vrátit k meditacím.}
{157}{}{Nevím. Snad se odhalí sám v pravı èas.}
{158}{}{[Odejít]}
{159}{}{[Pokraèovat]}
{160}{}{Buï zdráv, pane. Mohu ti pomoci?}
{161}{}{Buï zdráva, sleèno. Mohu ti pomoci?}
