{100}{}{Vidíš zástupce šerifa Tonyho Frye.}
{101}{}{Doufal jsem, e na tebe narazím, vrahu dìtí. Doufám, e tu nezùstaneš dlouho. Dokud tady budeš, budu na tebe dávat poøádnı pozor. Dr se zpátky, frajere, umírám touhou najít si záminku, abych se zbavil póvlu, jako jsi ty.}
{102}{}{Ahoj pøíteli, zástupce Tony Fry k tvım slubám.}
{103}{}{Co je tohle za místo?}
{104}{}{Tìšilo mì. Sbohem.}
{105}{}{Wug.}
{106}{}{Ack!}
{107}{}{Nováèek! Vítej v Hubu! Dorazil jsi do nejvìtšího mìsta na pobøeí. He, moná nejvìtšího mìsta na svìtì. Myslel jsem, e jseš èlen karavany. Pøišel jsi s nimi?}
{108}{}{Ano.}
{109}{}{Ne.}
{110}{}{Nepøekvapuje mì to. Vìtšina našich novıch èlenù pøichází s karavanami. Dokonce i tìmi, které se nám ztratily. Je to pìkné mìsto, ale dávej si pozor, s kım se dáváš dohromady. Lidi jako je Decker a jeho banda tì mùou dostat do spousty problémù.}
{111}{}{Pøekvapivé. Je to tu docela drsné, dokonce se ztratily celé karavany. Teï jsi ale v bezpeèí, jen se dr dál od Maltézského sokola. Jsou to banda potíistù, Decker a jeho banda.}
{112}{}{Kdo je Decker?}
{113}{}{Hmmm, no... jsem docela drsnej.}
{114}{}{Jakı ztracenı karavany?}
{115}{}{Kde si mùu vydìlat nìjakı prachy?}
{116}{}{To je ono, díky.}
{117}{}{Kdy to øíkáš. Máš ještì nìjaké otázky?}
{118}{}{To je skuteèná tragédie. Nìjaké karavany zmizely. Butch z Obchodníkù Far Go nabízí odmìnu za jakékoliv informace. Mìl by ses podívat na Trh, jestli tì to zajímá.}
{119}{}{Vlastní Maltézského sokola na Trhu, ale s ním bych se do paktu nedával, jestli nechceš mít problémy. Není nic ne krvelaèné zvíøe, ale šerif mi nedovolí ho zatknout bez dùkazu.}
{120}{}{ádnı problém. Vìø nebo ne, naše mìsto je klidné a bezpeèné místo a naše policie je velmi dobøe vycvièena. Nemìl bys mít ádné problémy. Prostì se dr dál od Maltézského sokola.}
{121}{}{Lituji, ale nerozumím tomu. Moná potøebuješ vyléèit? Dìti katedrály najdeš na jihu. Jdi smìrem na trh a potom k Obchodníkùm s vodou. Jsou hned vedle nich.}
{122}{}{Furt tì sleduji, vrahu dìtí.}
{123}{}{Krvelaèná bestie!}
{124}{}{Nemùu uvìøit, e šerif neije...}
{125}{}{Tady jsi, ty zlodìjskı hade! Skoro jsem tì nepoznal. Stráe!}
{126}{}{Jasnì.}
{127}{}{Chy si mì.}
{128}{}{Ne.}
{129}{}{ARG!}
{130}{}{Ahoj. Doufám, e se ti líbí naše mìsto. Milı mladı mu jako ty je vdy vítán. Kdyby ses rozhodl zùstat, urèitì bys byl pro Hub pøínosem.}
{131}{}{Ahoj. Doufám, e se ti líbí naše mìsto. Milá mladá ena jako ty je vdy vítána. Kdyby ses rozhodla zùstat, urèitì bys byla pro Hub pøínosem.}
{132}{}{Ahoj, co pro tebe mùu udìlat?}
{133}{}{Ano? Nemám na to celı den. Snaím se hlídat pøední bránu.}
{134}{}{Musím ohlásit zloèin!}
{135}{}{Máte nemocnici, jsem zranìn.}
{136}{}{Kde jsou obchody?}
{137}{}{Je tu nìjaká práce?}
{138}{}{Sbohem.}
{139}{}{Garro?}
{140}{}{Ooga.}
{141}{}{Fakt? Mìl by sis, eee, promluvit se šerifem. Zrovna teï nemùu opustit svùj post. Musím... uch, zlikvidovat všechny nájezdníky, kteøí by mohli pøijít. A navíc nejsem moc dobrı v hlášení.}
{142}{}{Ach, promiò. Nevšiml jsem si. Dìti mají nemocnici hned vedle Obchodníkù s vodou. Jdi kolem Trhu a uvidíš ji na severozápad od Obchodníkù s vodou. Doufám, e je všechno jinak v pohodì.}
{143}{}{Tìko to minout. Je v nejrušnìjším místì mìsta. Trh je nìkolik mil na jih odsud. Nejvíc tì bude zajímat severní sekce, tam nejvíc našich prodává veøejnosti.}
{144}{}{Práci najdeš na Trhu, pár mil na jih. Jsou tam dvì karavaní spoleènosti a tøetí trochu dál na jih. Doporuèuji ti jít k Far Go Traders. Dobøe platí a nejsou to takoví cvoci.}
{145}{}{Mrtví... jsou všichni mrtví...}
{146}{}{Pfffftttt... Chrrrr...}
{147}{}{Nevíš, kde bych mohl najít vodní èip? Èip z mého Vaultu je v háji a nutnì potøebujeme novı.}
{148}{}{Vodní èip? Nikdy jsem o ádném neslyšel. Jestli to má co dìlat s vodou, tak to zajdi k Obchodníkùm s vodou. Jejich vedení je dál na jih, kdy projdeš centrum.}
