{100}{}{Vidíš ghúlího èlena gangu.}
{101}{}{Co tu dìláš? Rozmysli si odpovìï, máš jen jednu šanci...}
{102}{}{Hledám šéfa.}
{103}{}{Tahle budova je urèena k demolici - pøišel jsem s posledním varováním.}
{104}{}{Sorry, jen tak koukám.}
{105}{}{Duh.}
{106}{}{Set tu není, tak zmiz.}
{107}{}{Oh, OK. Èau.}
{108}{}{Až najdu toho zkurvysyna, tak už ho nenajde nikdo jinej.}
{109}{}{To si z tebe udìlám boxovací pytel.}
{110}{}{Máš nìjaký mentální problémy. Set se nenechá sejmout od nìjakýho žabomrda. Má stráže a pušky.}
{111}{}{Kolik stráží?}
{112}{}{Co tu dìláš?}
{113}{}{Má kolem sebe nejmíò dvì stráže, ale když to potøebuje, mùže si jich zavolat víc než deset. A když je ve svým trùnním sálu, jsou tam za vteøinu.}
{114}{}{Tak co tu dìláš?}
{115}{}{To ti neøeknu. Co si myslíš, že jsem debil? Vypadni...}
{116}{}{Mám hlídat, aby nikdo neprošel. Tohle je dùm Zombie.}
{117}{}{Co je Zombie?}
{118}{}{Hm, hezkej den.}
{119}{}{Ne co... KDO. My jsme Zombie. Když budem dobrý, Set z nás udìlá svoje stráže. To je všechno, co ti øeknu.}
{120}{}{Proè chceš být jedním z jeho strážnejch?}
{121}{}{Èau.}
{122}{}{Øek jsem, že je to všechno, co ti øeknu. Teï padej.}
{123}{}{Jsi cvok. Co si myslíš, že je tohle? Radìji padej.}
{124}{}{Ne, chci dovnitø.}
{125}{}{OK, padám.}
{126}{}{Asi ne. Vypadni, než zavolám kluky a zatanèíme si na tvým ksichtì.}
{127}{}{To je výhružka?}
{128}{}{OK.}
{129}{}{Byla. Ale teï je to fakt. ZOMBIE!}
{130}{}{Drž se dál od tohohle místa, jestli si ceníš života.}
{131}{}{HEJ ZOMBÍCI, MÁME BOXOVACÍ PYTEL!}
{132}{}{Mìl bys vypadnout.}
