{100}{}{Naštval jsi Garyho!}
{101}{}{Vidíš Garyho.}
{102}{}{Hej! Jenom ghúlové dostávají pøídìl vody.}
{103}{}{Sklapni!}
{104}{}{Mutant tì ignoruje.}

{1000}{}{Voda}
{1001}{}{Nekropolis}
{1002}{}{Set}
{1003}{}{Studna}
{1004}{}{sin}
{1005}{}{Lou}
{1006}{}{Ghoulove}
{1007}{}{Normalove}
{1008}{}{èip}

{1100}{}{Nevím.}
{1101}{}{Jsi pøímo na místì.}
{1102}{}{Je to slaboch. Mìli bysme sejmout jeho i všechny jeho ghúly.}
{1103}{}{To je tady.}
{1104}{}{Nevím.}
{1105}{}{On Harryho boss.}
{1106}{}{Divný vìci.}
{1107}{}{Divnìjší než ghúlové.}
{1108}{}{Nevím.}
