{100}{}{Vidíš holodisk.}
{101}{}{Pip-Boy 2000 ukazuje: „Naèítám data... ... ... Hotovo. Hezký den!“}
{102}{}{Na tomto disku je uložen nìjaký zábavní program.}
{103}{}{Tento disk je pøíliš znièen, než abys z nìj mohl cokoli pøeèíst.}
{104}{}{Na tomto disku je zaznamenáno heslo pro nìjaký jiný disk.}
{105}{}{Vidíš malý display, na kterém se objevují fragmenty nìjakého filmu z 2. svìtové války.}
#
{106}{}{Disk je prázdný.}
{107}{}{Vyhodil jsi bezcenný disk.}
