{100}{}{Vidíš zombifikovaného ghúla.}
{101}{}{Vidíš zombie.}
{102}{}{Fuj.}
{103}{}{Mooozkyyyy...}
{104}{}{Buuuu...}
{105}{}{Uuhnnng..}
{106}{}{Grrr!}
{107}{}{Uungh.}
{108}{}{Mmmuuh...}
{109}{}{Arrrr!}
{110}{}{Grrrrr!}
{111}{}{*zasténá*}
{112}{}{*bublá*}
{113}{}{Mmmmmmm.}
{114}{}{*zasténá*}

# Examining the ghouls, restored from original Fallout files

{200}{}{Prozkoumáváš tu nebohou vìc, ale ani v nejmenším netušíš, jak z ní mohlo vzniknout to, èím je teï.}
{201}{}{Možná to byl kdysi èlovìk, nebo aspoò jeho pøedkové. Pøedpokládáš, že za jeho úpadkem lze tušit radiaci èi pùsobení kyseliny.}
{202}{}{Tìlo poloèlovìka bylo asi vystaveno tìžké dávce radiace, ale stále drží po hromadì. I když to byl kdysi èlovìk, teï se nenávratnì zmìnil do témìø zvíøecí formy.}
{203}{}{Tìlo poloèlovìka bylo asi vystaveno tìžké dávce radiace, vìtšina svalstva i mozkové hmoty byla jejich pùsobením rozežrána. Ale podle genetických znakù lze pøedpokládat, že stejnì jako ty to kdysi byl obyvatel Vaultu.}
{204}{}{Tato žalostná vìc je vysoce ozáøená. Nedá se øíct, zda se zbláznil z izolace, nebo jednoduše ztratil pøíliš mnoho mozkové hmoty v dùsledku radiaèního poškození.}
{205}{}{Tìlo tohoto humanoida vypadá vysoce ozáøené, ale oèividnì si zachoval dostatek mozkové hmoty a motorických funkcí, aby byl schopen srozumitelnì mluvit.}

# Messages when getting rads during combat with irradiated critters (glowing ones, radrats, etc)
# Listed in different formats, in case I want to implemented user choice of how it displays. --Sduibek

#Not currently used:
{300}{}{Dostal jsi malou dávku radiace.}
{301}{}{Dostal jsi støední dávku radiace.}
{302}{}{Dostal jsi velkou dávku radiace.}

#Not currently used:
{303}{}{Byl jsi mírnì ozáøen.}
{304}{}{Byl jsi ozáøen.}
{305}{}{Byl jsi znatelnì ozáøen.}
{306}{}{Dostal jsi velkou dávku ozáøení.}

# THIS IS THE FORMAT CURRENTLY USED:

{1004}{}{Dostal jsi mírnou dávku radiace.}
{1005}{}{Dostal jsi malou dávku radiace.}
{1006}{}{Dostal jsi støední dávku radiace.}
{1007}{}{Dostal jsi velkou dávku radiace.}
