{100}{}{Vidíš ghoulského uprchlíka.}
{101}{}{Prosím, nezabíjej mì.}
{102}{}{Sklapni a možná budeš žít.}
{103}{}{Neboj, nestojíš mi za to.}
{104}{}{Co se tu stalo?}
{105}{}{Gah.}
{106}{}{Ty . . . Ty mì stejnì zabiješ!}
{107}{}{Ah, oh. dobrá.}
{108}{}{Dobøe, zùstaò tak.}
{109}{}{Teï mi øekni, co se tu stalo.}
{110}{}{Ty mì zabiješ!}
{111}{}{Ah, neøíkal jsi, abych držel hubu?}
{112}{}{Teï chcípneš.}
{113}{}{Jo a teï bych chtìl vìdìt, co se tu stalo.}
{114}{}{Supermutanti zaútoèili. Zlikvidovali nás. Mìli pušky a bomby a dokonce i nìjaké parní vozy. Zabili moje pøátele. Prostì je všechny popravili, tak jako ty teï popravíš mì.}
{115}{}{Supermutanti zaútoèili. Zlikvidovali nás. Mìli pušky a bomby a dokonce i nìjaké parní vozy. Zabili moje pøátele. Prostì je všechny popravili.}
{116}{}{Co je to parní vùz?}
{117}{}{Jak se povedlo pøežít?}
{118}{}{Nevíš proè?}
{119}{}{Nevím.}
{120}{}{Díky.}
{121}{}{Jsi k nièemu.}
{122}{}{Slyšel jsem, že je dožralo, že nìjaký èlovìk pobil jejich místní hlídky.}
{123}{}{Uff, ještì nìco?}
{124}{}{Hmmm. OK. Zmiz odsud.}
{125}{}{Ne.}
{126}{}{Dík.}
{127}{}{Jsi k nièemu.}
{128}{}{Slyšel jsem, že možná pøežili nìkteøí ghoulové ze stok, ale tam dole se mi to nelíbí.}
{129}{}{OK, díky.}
{130}{}{To je ono?}
{131}{}{Jo, to je ono.}
{132}{}{Dobøe, dík.}
{133}{}{Skryl jsem se, dokud vìtšina mutantù nezmizela.}
{134}{}{Ještì nìco?}
{135}{}{Taková obrovská vìc na kolech, co se pohybuje, ale bez pomoci brahminù.}
{136}{}{Hmm, OK. ještì nìco?}
{137}{}{To je blbost.}
{138}{}{Hej, tak proè ses na to ptal?}
{139}{}{Tak! Dost drzostí!}
{140}{}{Chtìl jsem to vìdìt. To je celé.}
{141}{}{Zase ty? Co chceš teï?}
{142}{}{Nìjaké novinky?}
{143}{}{Jen tak si pokecám.}
{144}{}{Nic. No, slyšel jsem ale o dalších blížících se hordách supermutantù.}
{145}{}{Hmm. Dobrá.}
{146}{}{Dìlej si, co chceš. Já se budu skrývat.}
