{100}{}{Hej!}
{101}{}{ádné zbranì!}
{102}{}{Sleduj!}
{103}{}{Chyte je!}
{104}{}{Pøestaò tu èmuchat!}
{105}{}{ádnı èmuchání, jasnı!}
{106}{}{Hej, ty! Jestli se tu chceš schovat, tak radši vypadni!}
{107}{}{Co?}
{108}{}{Hej, mùu se na nìco zeptat?}
{109}{}{Nìjakı drobnı by nebyly?}
{110}{}{Ach, promiò.}
{111}{}{Uuuh?}
{112}{}{Jsem ve slubì. Pospìš si.}
{113}{}{Ne. Zmiz.}
{114}{}{Mùeš mi øíct nìco o svém šéfovi?}
{115}{}{Je tu ve mìstì ještì nìco?}
{116}{}{Co jsi, pitomec? Zmiz.}
{117}{}{Ne. Jdi ebrat jinam.}
{118}{}{Vodpal.}
{119}{}{Pro chudáky tu nemáme místo.}
{120}{}{Gizmo je rovnı chlap. Práce je snadná, platí dobøe. Nedìlej potíe a všichni budou v pohodì.}
{121}{}{Skoè si na pár drinkù do Skum Pitu. Bezva grog. Otvírají ve ètyøi. Teï mì nech na pokoji.}
{122}{}{Proè si nejdeš nakoupit ke Killianovi? Má obchod na jihovıchod odsud. Teï zmiz.}
{123}{}{Promluv si s krupiery.}
{124}{}{Hej, pokud se chceš trochu pobavit, ptej se na Sinthii v Crash House. Stojí za to.}
{125}{}{ádnı triky.}
{126}{}{Dluníci budou zastøeleni.}
{127}{}{Teda, ten krk mì ale bolí.}
{128}{}{Tahle práce je na hovno.}
{129}{}{Miluju tohle místo.}
{130}{}{Myslím, e dnes veèer navštívím Sinthii.}
{131}{}{Vypadni odsud, ty troubo.}
{132}{}{ádné zbranì!}
{133}{}{Hej! Ty! Dej to pryè!}
