{100}{}{Výtahové dveøe se zbytky modré barvy.}
{101}{}{Dostal jsi slabou ránu od zabezpeèovacího systému. Snad je tu nìco, èím by se dal systém obejít.}
{102}{}{Dostal jsi ránu od zabezpeèovacího systému. Snad je tu nìco, èím by se dal systém obejít.}
{103}{}{Dostal jsi silnou ránu od zabezpeèovacího systému. Byl jsi zranìn za }
{104}{}{ hit bodù. Snad je tu nìco, èím by se dal systém obejít.}
{105}{}{Zneškodnil jsi zabezpeèovací systém dveøí.}
{106}{}{Ta vìc nemá na dveøe žádné použití.}
