{100}{}{Toto je hrací automat s obrázkem jaderného výbuchu na boku. Paráda! Jedna hra stojí 20 zátek.}
{101}{}{Do automatu jsi vhodil 20 zátek a zatáhl za umaštìnou páku.}
{102}{}{DING! DING! DING!}
{103}{}{Získáváš tøi nukleární høíbky. Vynikající!}
{104}{}{ zátek spadlo do misky a ty si je hbitì shrábneš.}
{105}{}{Ding! Ding! Ding!}
{106}{}{Získáváš tøi bomby. Jsi vítìz! Do misky padlo 30 zátek a ty si je hbitì shrábneš.}
{107}{}{A sakra! Prohráls.}
{108}{}{Nemáš dost penìz na další hru.}
