{100}{}{Vidíš Harolda.}

{101}{HROLD0}{Nemáš pár drobnıch, kamaráde?  Co takhle trochu pomoct ubohému mutantovi v té jeho bídì? [Kašel]}
{102}{}{Jo, tady máš 25 babek. Uij je ve zdraví.}
{103}{}{Co takhle 5 babek.}
{104}{}{Sorry, ale ádné peníze nemám.}
{105}{}{Dr se ode mnì dál!}
{106}{}{Uhhh?}
{107}{HROLD1}{Jeišmarjá. Ty vypadáš hùø ne já, pøíteli. Pámbu s tebou a zlı pryè.}
{108}{HROLD2}{Oh, to jsi hodnej, kamaráde. Moc hodnej. Víš, kdybych si odtamtud moh vyèistit ten sajrat, tak bys v oku starıho Harolda zahlídnul slzièku.}
{109}{}{Proè to?}
{110}{}{To je dobrı.}
{111}{HROLD3}{[Kašel] Víš, od té doby, co jsem se vrátil do mìsta, se o mì zbytek Hubianù zajímá asi jako o uschlej smrkanec.  Ale nedokáu odsud odejít. Kdy se to tak vezme [sípání], je to poøád mùj domov.}
{112}{}{Co se ti stalo?}
{113}{}{Kdo jsou to ti Hubiani?}
{114}{}{Doufám, e se to zlepší. Mìj se.}
{115}{HROLD4}{No, po Velké válce byl mùj Vault jeden z prvních, které se otevøely. [Zhluboka se nadechl] Hú. To u je ale doba.}
{116}{}{Povìz mi trochu víc o tìch èasech.}
{117}{}{Ne to ne. Myslím, co se stalo s tebou, co tì tak znetvoøilo?}
{118}{HROLD5}{Všechno to zaèalo jeèením sirén. Byl jsem ještì malı, ale ach tohle si dobøe pamatuju.  Pak následovala spousta zlıch rokù.  A ještì si pamatuju, jak jsem jednoho krásnıho rána Vault opustil.}
{119}{}{Co jsi potom dìlal?}
{120}{}{A kde leel tvùj Vault?}
{121}{}{Máš pøedstavu, jak je to dávno?}
{122}{HROLD6}{No víš, [kašel] nejsem si moc jistej.  Myslím, e na západì.  Ne poèkej - na vıchodì?  Oh, já fakt nevím.  [Suchı kašel]}
{123}{}{Co jsi potom dìlal?}
{124}{HROLD7}{Byl jsem obchodník.  Dìlali jsme okruní cesty mezi tìmi, kdo pøeili.  Ale ztratili jsme pøitom spoustu skvìlıch lidí. [Kašle]}
{125}{}{Jak?}
{126}{HROLD8}{Dostali je banditi.  Ti mrchorouti útoèí na všechny karavany.  A pak ti mutanti. Èert mì vem, jestli pøi kadı naší cestì nevyskakovali ze zemì jak králíci. [kašel] Kdy jsi chtìl obchodovat, musel jsi mít s sebou armádu hlídaèù.}
{127}{}{Stráe vám nepomáhali?}
{128}{}{A odkud ti mutanti pøicházeli?}
{129}{HROLD9}{Samozøejmì e pomáhali, ty trotle!  Ale jich bylo moc. Nešlo to zvládnout!}
{130}{}{Jak jsi pøeil ty útoky mutantù?}
{131}{HROLD9A}{Nepøeil.  Zabili mì. [Smìje se a pak kašle] Tenhle fór miluju.}
{132}{}{Uh, no jistì.}
{133}{HROLD10}{Odevšad!  Zatracenì, vypadalo to, e se nemùeš ani vychcat, abys pøitom aspoò jednoho z nich netrefil.  Ale nejvíc jich chodilo ze severozápadu.}
{134}{}{Prozkoumali jste ten smìr?}
{135}{}{A proè jste se tìm místùm jednoduše nevyhıbali?}
{136}{}{Ty jsi prdnul smìrem na severozápad?}
{137}{hrold10a}{[Smìje se] To je dobrı...Nee...}
{138}{HROLD11}{Vyslali jsem tam expedici.  Boe, Richard.  Richard Grey.  Vedl naší malou skupinu tím smìrem.}
{139}{}{Richard Grey?}
{140}{}{Kam pøesnì jste mìli namíøeno?}
{141}{HROLD12}{Chtìli jsme se podívat, co to zpùsobuje.  A moná taky zastavit to, co je chrlilo v takovém poètu do okolí.  Mysleli jsme si, e jsme pøipraveni.  Spletli jsme se.}
{142}{}{Co jste udìlali?}
{143}{HROLD13}{Nepamatuju si u naší pøesnou trasu.  Ale jsem si zatracenì jistej, e to bylo nìkde na severozápadì...aspoò myslím.}
{144}{}{Existuje nìjaká kratší verze tohohle pøíbìhu?}
{145}{}{Co váš vùdce?}
{146}{HROLD14}{Richard Grey byl doktor.  Trochu starší, ne jsem byl já. Pøíteli, jak ten byl chytrı.  Právì on našel jejich zdroj.}
{147}{}{A co to bylo?}
{148}{HROLD15}{Rád to vyprávím po svém, kámo.  Ta kratší verze tì bude stát extra 25.  Tak kterou z nich si vybereš?}
{149}{}{OK, tak tu dlouhou.}
{150}{}{Krátkou.}
{151}{}{Krátkou, ale nemám ty prachy.}
{152}{}{A co takhle ádnou, ty starej prde?}
{153}{HROLD16}{Dobøe, vypadáš na slušnıho èlovìka.  Tak já to trochu zkrátím.}
{154}{}{Díky.}
{155}{hrold16a}{Takhle lhát ubohému starému mutantovi.  Kam jen ten svìt spìje? [kašle]}
{156}{hrold17}{Došly ti fondy, co?}
{157}{hrold17a}{Buï bude po mım nebo mùeš jít.  Je to tvoje volba, pøíteli.}
{158}{}{Jdu.}
{159}{}{OK. Tak tu dlouhou.}
{160}{HROLD18}{Nìjaká stará vojenská základna.  Ztratili jsme spoustu lidí, ne jsme se dostali dovnitø.}
{161}{}{Jak jste vìdìli, e zrovna ta základna je pøíèinou?}
{162}{}{Proti èemu jste bojovali?}
{163}{HROLD19}{Roboti a tak.  Bylo jich tam spousty.  Hroznì nás pøekvapilo, e po všech tìch letech války a všeho okolo poøád fungovali.  Hú, èlovìèe, ti nás pìknì proèesali.}
{164}{}{Co se stalo potom, kdy jste se probili pøes ty roboty?}
{165}{HROLD20}{Protoe to tam vypadalo, jako kdyby na ty mutanty nìkdo dostal zakázku!  Jeíši!  A za kadého poøádnı balík!  Neumím si pøedstavit jinej dùvod, ne e to byla továrna.}
{166}{}{Prozkoumali jste tu základnu dùkladnìji?}
{167}{HROLD21}{Dostali jsme se dovnitø pìknì hluboko.  Ale moc u nás nezbylo.  Grey, já a ještì dva další.}
{168}{}{A potom?}
{169}{HROLD22}{Jeden z tìch robotù dostal Francine.  Mark byl zranìnı, tak jsme ho poslali zpátky na povrch.  Pak jsme zùstali jen já a Grey.}
{170}{}{Co se stalo s Markem?}
{171}{}{Co se stalo potom?}
{172}{HROLD23}{Dodneška nevím.  Nikdy se sem nevrátil, a...no já...u jsem nemohl jít zpátky do Pustiny, take já...nikdy jsem po nìm nepátral.}
{173}{}{Co ty a Grey?}
{174}{HROLD24}{Našli jsme nìjakou centrálu a jakési zvláštní zaøízení.  A potom se to stalo.}
{175}{}{Co?}
{176}{HROLD25}{Zøítil se na nás jeøáb. A to bylo i naposled, co jsem vidìl Greye. Proletìl vzduchem a spadl do nìjaké nádre s kyselinou nebo co to bylo. Byl jsem na tom dost zle a tak...no omdlel jsem.}
{177}{}{Jak jsi to pøeil?}
{178}{}{A u nikdy jsi znovu Greye nevidìl?}
{179}{hrold25a}{Nepøeil jsem.  Umøel jsem...[Smìje se a pak znovu kašle] Boe, tenhle vtip miluju.}
{180}{}{Jo, já taky.}
{181}{HROLD26}{Vlastnì ani nevím.  Vzbudil jsem se v poušti a sotva jsem dokázal chodit.  Mìl jsem štìstí a o pár dní pozdìji mì našli nìjací obchodníci.  Zaplabùh, protoe u jsem se zaèínal mìnit. Pøinesli mì sem a od té doby jsem tady.}
{182}{}{Jak došlo k té tvojí mutaci?}
{183}{}{Úasnı pøíbìh.  Díky.}
{184}{hrold26a}{Není zaè...Dík, e jsi mì poslouchal.}
{185}{}{Tak to byla ta kratší verze?}
{186}{hrold26a}{Není zaè...Dík, e jsi mì poslouchala.}
{187}{hrold26b}{Pro mì jo.}
{188}{HROLD27}{Ne, ty idiote!  Snad jsem øíkal, e u jsem ho nikdy znovu nevidìl, ne?}
{189}{}{Jak jsi to pøeil?}
{190}{HROLD28}{Všechno, co vím, je, e to muselo bıt nìèím z té základny.}
{191}{}{Myslíš, e to mohla zpùsobit radiace?}
{192}{}{To je mi líto, starı brachu. Díky za ten pøíbìh.}
{193}{HROLD29}{Jak to mám sakra vìdìt?  Jestli by to byl mohl nìkdo vìdìt, tak Grey. [sípe] V kadım pøípadì, u se to stalo a nedá se na tom nic zmìnit.}
{194}{}{Díky za ten pøíbìh.}
{195}{HROLD30}{Jo, moná tak za jedno nebo dvì století.}
{196}{}{Co?}
{197}{HROLD31}{To je fuk. Jsem mrzutı, starı a takovı jsem od té doby, co jsem se zmìnil.}
{198}{}{Co jsi dìlal, ne se ti to stalo?}
{199}{HROLD32}{No, zmutoval jsem.  Urèitì jsem nebyl takhle ohyzdnej od narození.  A stalo se mi to, kdy jsme zkoušeli pøijít na to, odkud pocházejí všichni ti mutanti.}
{200}{}{Co se stalo?}
{201}{HROLD33}{To je minulost.  A asi by to tak mìlo i zùstat.}
{202}{}{Øekni mi prosím, co se stalo. Mùeš tím pomoct i pøítomnosti.}
{203}{}{Tak to tak nech.}
{204}{HROLD34}{No dobrá, kdy to tak vidíš.  Uškodit to nemùe.}
{205}{}{Díky.}
{206}{HROLD35}{Ne, ne.  Je to pro mì moc bolestivé a zvláš teï.  Díky za pomoc, pøíteli.  Hodnì štìstí.}
{207}{HROLD36}{Jsi ve mìstì Hub, ne?  A kdo ije v Hubu?  Hubiani.  Chápeš? [kašle] Jeiši!  Díky za pomoc a hodnì štìstí...myslím, e ho budeš potøebovat.}
{208}{HROLD37}{Jsi stejnì zlı, jako ti ostatní. [Sípavì kašle]}
{209}{HROLD38}{No dobøe, stejnì ti dìkuju. [kašel]}
{210}{HROLD39}{Hej, mùeš mi trochu píchnout, pøíteli?}
{211}{}{Jo, tady je 25 babek.}
{212}{}{Tady máš 5 babek.}
{213}{}{Neotravuj mì.}
{214}{}{Uhhh?}
{215}{HROLD40}{Hej, váím si toho! Musím pøiznat, e kdy jsem tì poprvé uvidìl, [kašel] myslel jsem si, e s tebou budou problémy.}
{216}{}{Proè to øíkáš?}
{217}{}{Nah, já ne!}
{218}{HROLD41}{Hej, rád tì zase vidím}
{219}{}{Tady je 20 babek, snad se ti budou hodit.}
{220}{}{Ahoj.}
{221}{}{Uhh?}
{222}{hrold42}{Jen mì zkoušíš, huh?}
{223}{HROLD43}{Mùu pro tebe nìco udìlat?}
{224}{}{Slyšel jsi v poslední dobì nìjaké zajímavé historky?}
{225}{}{Potøebuju nìjaké informace o Páraèích, a ty jsi prı ten pravı, kdo o tom nìco ví.}
{226}{}{Tak jakı je tvùj pøíbìh?}
{227}{}{Ne}
{228}{hrold43a}{Úplnej?  No...}
{229}{HROLD44}{Oooh, dík.  Doufám, e jsem na tebe moc netlaèil. [kašle]}
{230}{HROLD45}{Oooh, tak tohleto tì zajímá.  Pøíteli, tak to je noèní mùra celého mìsta.  Proè se mì na to sakra ptáš?}
{231}{}{Chci to zabít.}
{232}{}{Kdybych se s tím setkal, tak chci vìdìt, co mám dìlat.}
{233}{HROLD47}{Oukej.  No, je to zatracenì velká potvora.  Má drápy a zuby, které projdou skrz to nejtìší brnìní.  Ale nenech se zmást jeho velikostí, je setsakramentsky rychlı.}
{234}{}{Má nìjaké slabiny?}
{235}{HROLD49}{No, z toho co jsem slyšel, co takhle míøit na hlavu?  Já bych zkusil oèi.  Je tu ale jeden problém.}
{236}{}{Jakı problém?}
{237}{HROLD50}{Nesmíš se do nich podívat!  Øíká se, e Páraè mùe èlovìka jedním pohledem zhypnotizovat.  Potom k tobì pøijde a "bum", má tì!}
{238}{}{Vıbornì, díky.}
{239}{HROLD51}{Hodnì štìstí...budeš ho potøebovat.}
{240}{}{Mùe bıt.}
{241}{HROLD52}{Ty nechceš nic vìdìt o Páraèi a já ti o nìm nic neøeknu.}
{242}{HROLD53}{No, slyšel jsem, e jeden z Deckerovıch chlapù drí nìkoho z Bratrstva Oceli pod zámkem. Nìkde tady ve Starém Mìstì.}
{243}{}{Díky.}
{244}{HROLD54}{Já tomu sice moc nevìøím, ale øíká se, e se na nás chystá armáda mutantù. [kašel]}
{245}{}{Díky.}
{246}{HROLD55}{Nech mì na pokoji. [kašel]}
{247}{}{Chci s tebou mluvit.}
{248}{}{Tady máš pár drobnıch.}
{249}{HROLD56}{Dobøe, a já nechci mluvit s tebou.  Jdi pryè!}
{250}{HROLD57}{Nechci tvoje peníze.  Jdi pryè. [kašel]}

{251}{hrold200}{Aèkoliv rád obchoduju, nemám nic, co by tì mohlo zajímat. [kašel]}
{252}{hrold201}{Potøebuju se trochu vyspat.  U jsem unavenej.}
{253}{hrold202}{Mìl bys bıt víc opatrnı. [kašel] Slyšel jsem, e jsi tu zabil pár lidí.}
{254}{hrold203}{Umm...Decker tì hledá.  Chce s tebou mluvit. [kašel]}
{255}{hrold204}{Všechno, co mám, jsou tyhle hadry a moje svoboda. A to poslední je navíc dost diskutabilní.}
{256}{hrold300}{Skvìlı chlapík.  Doktor a filosof.  Pøed dávnımi èasy vedl tu vıpravu, pøi které jsem se zmìnil na mutanta.}
{257}{hrold301}{Kdo?  To je nìjakej druh sexuální terapie?  No to by se mi docela hodilo.}
{258}{hrold302}{Mutanti.  Nezáleí na tom, jak si øíkají.}
{259}{hrold303}{Oh, tenhle.  Vede Cech zlodìjù.  Myslí si o sobì, e je nìco jako Robin Hood. [kašel] Ale myslím, e je celkem v pohodì.}
{260}{hrold304}{U jsem vidìl všelijaká náboenství pøicházet i odcházet a doufám, e tohle odejde.  A brzy.}
{261}{hrold305}{Jo, já pocházím z Vaultu.  Pøíliš mnoho lidí, pøíliš málo jídla a vody.  Ale o tom ty nic nevíš, nebo snad jo?}
{262}{hrold306}{Hrùza.  Celı svìt tenkrát zešílel.  U je to dávno, ale já na to nikdy nezapomenu.  Nikdy.}
{263}{hrold307}{[Kašel] Trable.  Nic ne trable.}
{264}{hrold400}{No, jak u jsem øíkal...}
{265}{}{Nic, díky.}

#
# TRANSLATION NOTE: The following groups of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ('my friend' will be masculine); the second line is
# for the case of the player-character feminine ('my friend' will be feminine).
#

{266}{HROLD0}{Nemáš pár drobnıch, kamaráde?  Co takhle trochu pomoct ubohému mutantovi v té jeho bídì? [Kašel]}
{267}{HROLD0}{Nemáš pár drobnıch, krásko?  Co takhle trochu pomoct ubohému mutantovi v té jeho bídì? [Kašel]}
{268}{HROLD2}{Oh, to jsi hodnej, kamaráde. Moc hodnej. Víš, kdybych si odtamtud moh vyèistit ten sajrat, tak bys v oku starıho Harolda zahlídnul slzièku.}
{269}{HROLD2}{Oh, to jsi hodná, dívenko. Moc hodná. Víš, kdybych si odtamtud moh vyèistit ten sajrat, tak bys v oku starıho Harolda zahlídla slzièku.}
{270}{HROLD35}{Ne, ne.  Je to pro mì moc bolestivé a zvláš teï.  Díky za pomoc, pøíteli.  Hodnì štìstí.}
{271}{HROLD35}{Ne, ne.  Je to pro mì moc bolestivé a zvláš teï.  Díky za pomoc, dámo.  Hodnì štìstí.}
{272}{HROLD39}{Hej, mùeš mi trochu píchnout, pøíteli?}
{273}{HROLD39}{Hej, mùeš mi trochu píchnout, krásko?}

#
# Harold's Tell-Me-Abouts
#

# Knows nothing
{980}{}{Ne. O tom jsem nikdy neslyšel.}
{981}{}{Nemám páru.}
{982}{}{To neznám.}

{1000}{}{Richard}
{1001}{}{Vudce}
{1002}{}{Ghoul}
{1003}{}{Loxley}
{1004}{}{Katedrala}
{1005}{}{Vault}
{1006}{}{Valka}
{1007}{}{Decker}
{1008}{}{Grey}
{1009}{}{Obchod}

{1100}{hrold300}{Skvìlı chlapík.  Doktor a filosof.  Kdysi dávno vedl tu vıpravu, pøi které jsem se zmìnil na mutanta.}
{1101}{hrold301}{Kdo?  To je nìjakej druh sexuální terapie?  No to by se mi docela hodilo.}
{1102}{hrold302}{Mutanti.  Nezáleí na tom, jak si øíkají.}
{1103}{hrold303}{Oh, tenhle.  Vede Cech zlodìjù.  Myslí si o sobì, e je nìco jako Robin Hood. [kašel] Ale myslím, e je celkem v pohodì.}
{1104}{hrold304}{U jsem vidìl všelijaká náboenství pøicházet i odcházet a doufám, e tohle odejde. A brzy.}
{1105}{hrold305}{Jo, já pocházím z Vaultu.  Pøíliš mnoho lidí, pøíliš málo jídla a vody.  Ale o tom ty nic nevíš, nebo snad jo?}
{1106}{hrold306}{Hrùza.  Celı svìt tenkrát zešílel.  U je to dávno, ale já na to nikdy nezapomenu. Nikdy.}
{1107}{hrold307}{[Kašel] Trable.  Nic ne trable.}
{1108}{hrold300}{Skvìlı chlapík.  Doktor a filosof.  Kdysi dávno vedl tu vıpravu, pøi které jsem se zmìnil na mutanta.}
{1109}{hrold200}{I kdy obyèejnì miluju obchodování, teï bohuel nemám nic, co bych ti mohl nabídnout. [kašel]}
