{100}{}{Vidíš šerifa Justina Greena.}
{101}{}{Má úcta, to je ten vrah nevinnıch. Slyšel jsem o tobì a máš štìstí, e mám odznak, kterı mi brání, abych ti jednu vrazil. Nabízím ti, abys hned opustil naše mìsto - hned teï. A nepøibliuj se k našim dìtem.}
{102}{}{Zdravím pane! Mé jméno je Justin Green. Jsem šerifem tohoto krásného mìsta. Mohu pro Vás nìco udìlat v tento nádhernı den?}
{103}{}{Zdravím madam! Mé jméno je Justin Green. Jsem šerifem tohoto krásného mìsta. Mohu pro Vás nìco udìlat v tento nádhernı den?}
{104}{}{Dobrá, tak ven s tím!}
{105}{}{Decker mì najal, abych zabil nìjakého obchodníka a jeho enu.}
{106}{}{Decker se mì pokusil najmout, abych zabil nìkoho jménem Jain.}
{107}{}{Nic, promiòte.}
{108}{}{Promiòte, nemohu to øíci. Zabili by mì.}
{109}{}{Dobrá, dík. Udìlám, co budu moct. Je to skuteèné obtíné v takhle velkém mìstì, ale udìláme, co budeme moct s tím, co máme. Je to ale tìké, kdy ti násilníci mají lepší zbranì ne my.}
{110}{}{Ještì jednou díky.}
{111}{}{Je èas vypadnout, ty vrahu dìtí.}
{112}{}{Takhle to nejde. Ale kdy si to rozmyslíš, dej mi vìdìt. Není tu bezpeèno a kadı musí zastávat to, èemu vìøí.}
{113}{}{Skvìle! U vím z jinıch zdrojù o jeho plánech. Tys mi dal poslední dùkaz, kterı potøebuju, aby se proti nìmu dalo nìco podniknout. Bude to tvrdé a já potøebuju kadou pomoc. Dám ti 1000 babek, kdy nám pomùeš. 200 hned a zbytek a to skonèí. Co tomu øíkáš?}
{114}{}{Jdeš pozdì....Sakra! Vìdìl jsem, e za to mùe, ké bych ho byl mohl zastavit. V kadém pøípadì ty jsi poslední svìdek, kterého jsem potøeboval, abych mohl nìco podniknout. Budeme ho muset zlikvidovat. Bude to tvrdé a já budu potøebovat kadou pomoc. Dám ti 1000 babek, kdy nám pomùeš. 200 hned a zbytek, a to skonèí. Co tomu øíkáš?}
{115}{}{Jdeš pozdì... Ale jak mám vìdìt, e za to nemùeš právì ty? Decker obvykle nenechává ít nikoho, kdo ví o jeho plánech.}
{116}{}{Právì se ke mì doneslo, e je mrtvá... poèkej chvilku. Ale jak mám vìdìt, e za to nemùeš právì ty? Decker obvykle nenechává ít nikoho, kdo ví o jeho plánech.}
{117}{}{Bude mi potìšením.}
{118}{}{Sorry, ale chci to všechno dopøedu.}
{119}{}{To teda ne! Jdi do toho sám.}
{120}{}{Nikdy. Vypadáš sice dùvìryhodnì, ale nemùu vìdìt, jestli nezdrhneš, a pùjde do tuhého. A jeden z nás urèitì pøeije, take se nemusíš bát, e nedostaneš zaplaceno. Takhle to bude naše malá "pojistka".}
{121}{}{Jdeme na to.}
{122}{}{Jdi do toho sám, šerife.}
{123}{}{Skvìlı! Vyrazíme hned, a se pøipravíš.}
{124}{}{Jsem pøipraven.}
{125}{}{OK, Sbohem.}
{126}{}{To mì opravdu mrzí. Kdy zmìníš názor, dej mi vìdìt, ale nemùu èekat moc dlouho.}
{127}{}{OK, udìlám to. Ale poèkejte na mì, ne si obstarám pár vìcièek.}
{128}{}{Jsi blázen.}
{129}{}{Sbohem.}
{130}{}{Skvìlı! Dej mi vìdìt, a se pøipravíš. Poèkáme na tebe, ale spìchej.}
{131}{}{Coe? Ty myslíš, e budu èekat a nechám ho zabíjet nevinné lidi? Já ruèím za tohle mìsto a neèekám, e tomu budeš rozumìt.}
{132}{}{Máš pravdu. Je to na Tobì.}
{133}{}{Jak se opovauješ mì obviòovat!}
{134}{}{Nezajímá mì, co si myslíš.}
{135}{}{Dobrá, o nic se tedy nepokoušel.}
{136}{}{Byli jsme ve Falconu a okolo byla spousta lidí.}
{137}{}{Promiò. Decker nás poštval všechny proti všem. Nevím komu dùvìøovat. Fakt budu potøebovat tvojí pomoc. Bude to tvrdé, ale zaplatím ti 1000. 200 rovnou a 800, a bude po všem.}
{138}{}{Já poznám krysu, kdy smrdí! Máš štìstí, e nemám dùkaz. A teï radši zmiz z mìsta, ne nìjakı najdu.}
{139}{}{To je moc divné. Nikdy jsem neslyšel, e by Decker vyšel ze své kanceláøe. Asi se stal stateènìjším. Kruci, vrada .... fuj! Stejnì ho dostanu. Øeknu ti jak, ty nám pomùeš a já ti zaplatím 1000 - 200 hned a 800 a bude po všem. Co ty na to?}
{140}{}{To je ta nejvìtší snùška kecù, kterou jsem kdy slyšel. Decker nikdy nevychází ze své kanceláøe. Nìco se mi na tobì nezdá. Ale máš štìstí, e nemám ádnı dùkaz. A teï radši vypadni z mìsta, ne si nìjakı najdu!}
{141}{}{OK, jdeme...}
{142}{}{Tak, ty jsi pøišel sám se udat? Jsem unešen.}
{143}{}{Ano, je mi to líto.}
{144}{}{Udat se? Nechtìjte mì rozesmát.}
{145}{}{Chyte ho!}
{146}{}{Chyte ji!}
{147}{}{Dobrá, pùjdeš do své cely.}
{148}{}{Nehıbej se. Nìjakou chvilku si teï nikam nevyjdeš.}
{149}{}{Uprchlík! Chyte ho!}
{150}{}{Uprchlík! Chyte ji!}
{151}{}{Pøipraven?}
{152}{}{Ano.}
{153}{}{Ne.}
{154}{}{Ha.}
{155}{}{Nemùu uvìøit, e je Decker koneènì mrtvı. Nedoufal jsem, e se toho doiju.}
{156}{}{Rozmyslel sis to? Stále se chceme s tvou pomocí zbavit toho svinstva, o kterém jsme mluvili.}
{157}{}{Jdu.}
{158}{}{Ne, sorry.}
{159}{}{Hm?}
{160}{}{Sledujeme Tì.}
{161}{}{Chci nahlásit zloèin!}
{162}{}{Byla to dobrá práce.}
{163}{}{Jen jsem se tu zastavil. Mìjte se?}
{164}{}{Ouha.}
{165}{}{Zdravím znova, pane. Co pro Vás mohu dnes udìlat?}
{166}{}{Zdravím znova, madam. Co pro Vás mohu dnes udìlat?}
{167}{}{Ahoj. Mohu nìjak pomoci?}
{168}{}{Ano?}
{169}{}{Zkus se z toho vyspat, jo?}
