{100}{}{Vidíš Ricka, stráného.}
{101}{}{Co tady chceš?}
{102}{}{No... Hm...}
{103}{}{Promiòte. Mùu se na nìco zeptat?}
{104}{}{Tvojí hlavu na špejli!}
{105}{}{Pardon, hned se ztratím.}
{106}{}{Bì zpátky do vıchodní ètvrti, ty skopová hlavo!}
{107}{}{Mhm?}
{108}{}{U jdu.}
{109}{}{Rychle. Nesmím pøi práci mluvit.}
{110}{}{Kde to jsem?}
{111}{}{Co dìláš?}
{112}{}{Sorry, nechtìl jsem tì rušit. Èau.}
{113}{}{Radši si dávej bacha na to, co øíkáš, grázle!}
{114}{}{NE! Radši dávej bacha. Proenu ti kulku hlavou!}
{115}{}{Nestojíš mi za ten èas.}
{116}{}{Jestli to nevíš, tak tady nemáš bejt. Tady se to jmenuje Pahorky. Bydlí tu pan Hightower a on si zve lidi jenom na schùzky.}
{117}{}{Co dìláš?}
{118}{}{Mùu si domluvit setkání s panem Hightowerem?}
{119}{}{Díky za pomoc.}
{120}{}{Jsem tady, aby všichni nechali pana Hightowera na pokoji.}
{121}{}{No, já mám za úkol zabít pana Hightowera. Je èas, aby sis zaslouil svùj plat!}
{122}{}{Kde to jsem?}
{123}{}{Dík za pomoc. Mìj se.}
{124}{}{Ne.}
{125}{}{Nelíbíš se mi. Vypadni.}
{126}{}{No jo. U jdu.}
{127}{}{Tak pojï, ty vlasatej kreténe!}
{128}{}{Po západu slunce sem nikdo nesmí. Ostatní stráe ti u nedají vıstrahu. Kdy tì chytí, pùjdou po tobì. Radši se vra do centra, dokud máš hlavu na krku.}
{129}{}{OK. U jdu.}
{130}{}{Ne. Nejdu.}
{131}{}{Na to já seru.}
{132}{}{Omlouvám se, nebudu obtìovat.}
{133}{}{Chlape, ty seš tupej jak poleno. Padej!}
