{100}{}{Vidíš George, strá u dveøí.}
{101}{}{Mùu ti pomoct?}
{102}{}{Chci vidìt pana Tower!}
{103}{}{Jo. Chci vidìt pana Hightowera.}
{104}{}{Mám schùzku s panem Hightowerem a jdu dost pozdì.}
{105}{}{Pus mì dovnitø.}
{106}{}{Pan Hightower nepøijímá jen tak nìkoho.}
{107}{}{No, a mì vidìt chce.}
{108}{}{Jak si s ním mám domluvit schùzku?}
{109}{}{Já nejsem jen tak nìkdo, ty idiote!}
{110}{}{Ah tak. Sbohem.}
{111}{}{OK. Tak bì.}
{112}{}{Znám všechny spoleèníky pana Hightowera, ale tebe neznám. Tak radši vypadni. Hned.}
{113}{}{Hele chlape, koleduješ si o potíe! Pan H. nenávidí, kdy nìkdo pøijde na setkání pozdì. Seere tì zaiva. No bì dál.}
{114}{}{Tam se nedostaneš. Vypadni, nièemo!}
{115}{}{Nechci tady ádné potíe, radši vypadni.}
{116}{}{Zmiz!}
{117}{}{Bì pryè od tìch dveøí.}
{118}{}{Co tady sakra slídíš?!? Stráe!}
{119}{}{Jdi od tìch dveøí! Tam se nikdo nedostane, ani by prošel pøes mì!}
{120}{}{Ty máš ale nervy, kdy si sem jen tak pøijdeš! Stráe!}
