# These are the police of the Hub (a large metropolis). They are either gender, but using
# Male is the best approach. They are simpltons who have a badge only because no one else
# would take the badge. Speech has an absent-mindedness about it.

{100}{}{Vidíš policejního dùstojníka.}
# Police Officer is male

{101}{}{Zdravíèko! Radši byste si mìli dávat pozor na svoje... hm, myslím, no jen se podívejte... [dùstojník se divnì dívá na ostatní dùstojníky a ukazuje hlavou ve tvém smìru]}
{102}{}{Zdravíèko, cizinèe... hej poèkej! Já tì znám! Hledáme tì pro kráde! Stùj!}
# Stranger is the player. Consider Male.

{103}{}{OK, vzdávám se.}
{104}{}{Zabiju tì!}
# "Eat lead" is equivalant to "I'm going to kill you."

{105}{}{Chrr Prsk!}
# "Kor Rok" is just garbled sounds a moronic player is saying.

{106}{}{[Vzdát se.]}
{107}{}{Dávej si pozor na svùj zadek, tohle není bezpeèné místo.}

# 108/109, 108/110 are lines which go together. "Watch your scripts, guy." or "Watch your scripts, lady."
{108}{}{Dávej si pozor na prachy, }
# scripts are money

{109}{}{chlapèe.}
{110}{}{sleèno.}
{111}{}{Radši bys ses tu nemìl zdrovat, není tu moc bezpeèno.}
{112}{}{Staré Mìsto se fakt rozpadá.}
# Old Town is another section of town. This is were the poor and down-trodden live.

{113}{}{Tady to nìjak smrdí.}
{114}{}{Mìli bychom to tu všechno zbourat.}
{115}{}{Vím, e ten prokletej Kruh zlodìjù je nìkde tady poblí.}
# the Thieve's Circle is similar to a Thieve's Guild. underground organization for thieves.

{116}{}{Chudák Harold, mìl tìkı ivot.}
# Harold is Male

{117}{}{Do nièeho se nenamoè.}
# == Don't do anything illegal.

{118}{}{Hej. Já tì znám. ádné rvaèky, OK?}
{119}{}{Radši neuvauj o ádné další bitce!}
{120}{}{Jestli tì chytneme v nìjaké další rvaèce, zabásneme tì!}
# "You're going in" equals "You are going to jail"

{121}{}{Slyšel jsi? S Far Go je konec.}
# Far Go Traders is a merchant's guild

{122}{}{Obchodníci s vodou jsou u minulost, zaplapánbùh.}
# Water Merchants is a merchant's guild

{123}{}{Nìkdo vyhladil Karmínovou karavanu.}
# Crimson Caravans is a merchant's guild

{124}{}{U to víš? Podsvìtí bylo definitivnì vyøízeno!}
# Underground is a rough organization for assassins. Akin to the Mafia

{125}{}{Decker je po smrti!}
# Decker is Male

{126}{}{Bez Deckera bude tohle mìsto daleko bezpeènìjší.}
# == "This town would be safer with Decker dead."
