#
# He's fairly short, stocky and self-assured, and looks to be well-traveled.
#
{100}{}{Vidíš malého, podsaditého mue.}
{101}{}{Tobì podobné tady nevidíme rádi.}
{102}{}{Buï zdráv, cizinèe. Zdá se, e jsi tu novı. Jak se jmenuješ?}
{103}{}{To není dùleité.}
{104}{}{Jmenuju se }
{105}{}{.}
{106}{}{He?}
{107}{}{Dobøe, pak ani ty ne.}
{108}{}{Rád tì poznávám. Já jsem Ian.}
{109}{}{Co tady dìláš?}
{110}{}{Chtìl bych se dovìdìt víc o tomhle místì. Pomùeš mi?}
{111}{}{Promiò, ale nemám èas na rozmluvy s pitomci.}
{112}{}{Dìlal jsem ozbrojenı doprovod obchodníkùm z Hubu. A jednou jsem to koupil, kdy nás napadli nájezdníci. Zùstávám tady, lidi mi tu pomohli dát se dohromady. Se svımi znalostmi vnìjšího svìta jsem zdejším lidem dost uiteènı. Shady Sands se stalo mım domovem. Obèas vyrazím do Junktownu nebo do Hubu za nìjakımi obchody. Jsem tu vlastnì jedinı, kdo kdy opustil tohle mìsto.}
{113}{}{Vidíš Iana.}
{114}{}{Mrzí mì, e tì zranili.}
{115}{}{Kde je Hub a Junktown?}
{116}{}{Mùeš mi øíct víc o nájezdnících?}
{117}{}{Shady Sands je malá, sobìstaèná spoleènost. Jedinı problém tu jsou nájezdníci a radškorpióni.}
{118}{}{Co je to za problém s tìmi radškorpióny?}
{119}{}{Je v okolí hodnì nájezdníkù?}
{120}{}{Je jich nìkolik. A jsou to rùzné tlupy. Kradou naše jídlo a obèas i nìkoho zabijí. Seth organizuje hlídky, abychom se jim ubránili.}
{121}{}{Mùeš mi prozradit nìco o Sethovi?}
{122}{}{Rùzné tlupy? Co jsou zaè?}
{123}{}{Radškorpióni jsou velmi nebezpeèní. Mají jedovaté ihadlo na špièce ocasu a jsou hroznì rychlí. Aradesh se pokouší vymyslet zpùsob, jak se jich jednou pro vdy zbavit. Pokud se na to cítíš, mùeš si o nich s Aradeshem promluvit.}
{124}{}{Díky. Dobøe se mi to zahojilo, hlavnì díky Razlovi.}
{125}{}{Seth je vánì stateènej chlap. Obèas vymetá ty jejich jeskynì, aby jich pár oddìlal, ale vdycky se odnìkud vyhrabou další. Sám na nì prostì nestaèí.}
{126}{}{Jsou radškorpióni opravdu tak nebezpeèní?}
{127}{}{S èím ti mùu pomoct?}
{128}{}{Známe tøi skupiny: Khanové, Zmije a Šakalové. Nenávidí se navzájem, ale všichni napadají Shady Sands.}
{129}{}{Øekni mi víc o Shady Sands.}
{130}{}{Má jistı a uvolnìnı postoj zkušeného bojovníka.}

# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 131 and 132.
{131}{}{Áaa, }
{132}{}{, co pro tebe mùu udìlat?}

{133}{}{Øekni mi o nájezdnících.}
{134}{}{Øekni mi o radškorpionech.}
{135}{}{Øekni mi o Shady Sands.}
{136}{}{Øekni mi o Sethovi.}
{137}{}{Prozradíš mi kudy se dostanu do Hubu a do Junktownu?}
{138}{}{Nic, díky.}
{139}{}{Hub je velké obchodní centrum daleko na jih od Shady Sands. Ovládá ho pár skupin karavanních obchodníkù: Obchodníci s vodou, Karmínová karavana a Far Go. Junktown je mírnì na jihozápad. Je menší, ale stejnì se v nìm dá zastavit na pár panákù. Celému mìstu šéfuje chlapík jménem Killian Darkwater, místní majitel obchodu, šerif a starosta v jedné osobì.}
{140}{}{Díky.}
{141}{}{Moná u nejsem tak skvìlı bojovník, ale na tobì podobné ještì poøád staèím!}

# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 142 and 143.
{142}{}{Co pro tebe mùu udìlat, }
{143}{}{?}

{144}{}{Hmm. Nic.}
{145}{}{Víš, chtìl bych bıt chvíli sám...}

{146}{}{Prozradíš mi, kudy se dostanu do Hubu a do Junktownu?}
{147}{}{Dobøe, tak zatím. Ještì se uvidíme.}

{148}{}{Ne, díky. Mì potøebují tady.}
{149}{}{Nepøidal by ses ke mì, na èas? Tvé zkušenosti by se mohly hodit.}
{150}{}{Jasnì. Nebude špatné vyrazit zase na cesty!}

{151}{}{To je Killianùv hlavní obchod. Killian je dobrı chlapík a v obchodì má docela širokı vıbìr.}
{152}{}{Gizmovo kasino. Centrum hazardu a nekalıch rejdù. Pozor; øíká se, e hry jsou zmanipulované.}
{153}{}{Tohle místo je hroznı.}
{154}{}{Co se tu kurva stalo?}
{155}{}{Tohle bude tìkej oøíšek k rozlousknutí.}

{156}{}{Hmm. Zajímavá nabídka, tady u se zaèínám nudit. Nìco ti øeknu. Bìná taxa. 100 babek na ruku a jsem tvùj èlovìk.}
{157}{}{Platí.}
{158}{}{Ne, díky.}
{159}{}{A co takhle místo toho trochu akce?}
{160}{}{Dobrá, pomùu ti vımìnou za podíl na budoucí koøisti.}
{161}{}{Ne, to si nemyslím. Vra se, a budeš mít èím zaplatit.}

{162}{}{Tohle je obchod se zbranìmi. Vede ho Beth. Na zbranì je dobrá, ale na drby ještì lepší.}
{163}{}{Jakeovy zbranì. Vysoké ceny, ale vıborná kvalita.}
{164}{}{Kanceláø Obchodníkù s vodou. To jsou nejvìtší bossové v Hubu, protoe mají pod palcem vodní zásoby, tak to všechno øídí.}
{165}{}{To je Karmínová karavana. Pracoval jsem pro nì. Pouštìjí se do tìch nejriskantnìjších podnikù.}
{166}{}{Far Go vede Butch Harris. Není zrovna ádnej génius, jestli mi rozumíš.}
{167}{}{Á, to je Maltézskı sokol. Dobrá hudba, dobrı pití, vybraná spoleènost.}

{168}{}{To je ale hnusnej zkurvysyn!}

{169}{}{ zkušenostních bodù za pøemluvení Iana, aby se k tobì pøipojil.}

{170}{}{U jsem o podobnejch místech slyšel, ale nikdy jsem v ádnım nebyl. Vypadá pìknì a èistì... trochu moc èistì, na mùj vkus.}

{171}{}{Ne e ses mì ptal, ale èlovìk ti potøebuje dát prostor k nadechnutí.}

{172}{}{Víš, ta enská nedokáe vést v tangu, nato revoluci.}

{173}{}{Jaké zbranì dobøe ovládáš?}
{174}{}{Dobøe støílím s jakoukoli pistolí, umím to i se samopalem. A samozøejmì to umím dost dobøe s noem.}

#
# Translation note
# The following line is directed at Katja, a female scavenger, not at the player.
# Ian is noting that he thinks that L.A. Boneyard was a worse place than the
# mutants' military base.
#

{175}{}{Myslím, e L.A. kostnice je horší.}


{200}{}{Vytáhni v pøíští bitvì nejlepší zbraò, co máš.}
{201}{}{Provedu.}
{202}{}{Mùu pro tebe nìco udìlat, ne pùjdu?}
{203}{}{Uhm, jo. Nakonec si myslím, e bychom mìli zùstat spolu.}
{204}{}{Uh, ne. Díky.}

# Healing
{300}{}{Jsem v pohodì.}
{301}{}{V pohodì, víceménì všechno je zacelené.}
{302}{}{U je mi lépe, ale neodmítnul bych stimpak nebo dva.}
{303}{}{Nejsem na tom moc dobøe. Pokud máš nìjaké stimpaky, rozhodnì bych je vyuil. Ale chodit ještì stále zvládnu.}

# Pushing
{310}{}{Jasnì.}
{311}{}{Pùjdu támhle.}
{312}{}{Jasná vìc.}
{313}{}{Promiò, kámo.}

#
# Ian Tell-Me-Abouts
#

{1000}{}{Waterchip|Water Chip|vodni cip|vodni}
{1001}{}{War|Valka}
{1002}{}{Shady|Shady Sands|Sands}
{1003}{}{Junktown|Junk Town}
{1004}{}{Hub}
{1005}{}{Raiders|Raider|najezdnici|Najezdnik}
{1006}{}{Caravans|Caravan|karavany|karavana}
{1007}{}{Chip|Cip}
{1008}{}{Sands}
{1009}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA|nasledovnici|Nasledovnici apokalypsy|naslednici}
{1010}{}{Children of the Cathedral|Children|Cathedral|CoC|Deti katedraly|Katedrala}
{1011}{}{Garl|Death Hand|Smrtihnat}
{1012}{}{Master|Vudce}
{1013}{}{Unity|Jednota}
{1014}{}{Set}
{1015}{}{Shed|Watershed|Water Shed|vodarna}
{1016}{}{Necropolis|City of the Dead|City of Dead|Nekropolis|Mesto mrtvych}
{1017}{}{Hall|HALL OF THE DEAD|DEADHALL|HALL OF DEAD|hala|sin|Sin mrtvych|hala mrtvych}
{1018}{}{Library|knihovna}
{1019}{}{Overseer|Spravce}
{1020}{}{Razlo|doktor}
{1021}{}{Healing|leceni}
{1022}{}{Water Merchants|Water Merchant|Obchodnici s vodou|obchodnik s vodou}
{1023}{}{Crimson Caravans|Crimson|Crimson Caravan|karminova karavana}
{1024}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go|obchodnik Far Go}
{1025}{}{Killian|Kilian|Killian Darkwaters|Kilian Darkwaters|Killian Darkwater|Kilian Darkwater|Darkwater|Darkwaters}
{1026}{}{Gizmo}
{1027}{}{Boneyard|Angels Boneyard|Kostnice|Andelska kostnice}
{1028}{}{Casino|Kasino}
{1029}{}{Store}
{1030}{}{Deathclaw|Deathclaws|Claw|Claws|parac|paraci}
{1031}{}{Exodus}
{1032}{}{Initiates|Initiate|zasvecenci|Zasvecenec|zasveceni}
{1033}{}{Paladins|Paladin|paladini|paladinove}
{1034}{}{Scribes|Scribe|pisari|Pisar}
{1035}{}{Children|Kid|Kids|Child|deti|Dite}
{1036}{}{Brotherhood|BoS|Brotherhood of Steel|Bratrstvo|Bratrstvo oceli}
{1037}{}{Vats|Nadrze}
{1038}{}{Military|Base|Military Base|armada|vojenska|Zakladna|vojenska zakladna}
{1039}{}{Scorpions|Scorpion|Rad Scorpion|Radscorpions|Radscorpion|skorpioni|skorpion|radskorpion|radskorpioni}
{1040}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|koupit|kupovat|prodat|prodavat|Obchodovani|obchod|smena|Vymenit|Menit|Kseft}
{1041}{}{Apocalypse|apokalypsa}
{1042}{}{Mutants|Mutant|mutanti}
{1043}{}{Morpheus}
{1044}{}{Khans|Khan|Khanove}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Booze|chlast}
{1052}{}{Drugs|Drug|Drogy|chemikalie|prasky|Alkohol|Droga}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Doctor|Medic|Doc|medik}
{1056}{}{Zimmerman|Jon Zimmerman|Jon|Zimermann|Jon Zimmermann|Zimmermann}
{1057}{}{Regulators|Regulator|Regulatori}
{1058}{}{Scavs|Scav|Scavenger|sberaci|sberac|Scavove}
{1059}{}{Blades|Blade}
{1060}{}{Nicole}
{1061}{}{Lieutenant|Lou|Lt|Porucik|Po}
{1062}{}{Psychics|Psychic|Psychika}
{1063}{}{Experiments|Experiment|Experimenty}
{1064}{}{Ian}
{1065}{}{Merchants|Merchant|kupci|kupec}

{1100}{}{Nemám tušení, co je to vodní èip. Promiò, kamaráde.}
{1101}{}{Stalo se to pøed stovkou let. V zásadì se pár státù poøádnì nasralo a následovalo poøádnı BUM!}
{1102}{}{Malá mírumilovná vesnice. Pravdìpodobnì nejslibnìjší spoleènost v pustinách.}
{1103}{}{Støednì velké mìsto postavené ze šrotu, vede to tam šerif Killian. Je to jen pár dní na jihozápad od Shady Sands.}
{1104}{}{Hub je nejvìtší obchodní centrum Nového západu. Hlavní slovo v nìm mají Obchodníci s vodou, ale najdou se tam i jiné skupiny obchodníkù. Je to mìsto na vzestupu, ale je tam spousta politikaøení mezi jednotlivımi obchodnickımi seskupeními.}
{1105}{}{Je tu nìkolik rùznıch skupin nájezdníkù. Nejuspoøádanìjší je tlupa, která si øíká Khanové; ti si snad myslí, e by mohli dobıt celı svìt.}
{1106}{}{Vìtšina karavan vyjídí z Hubu. Cestují do všech koutù. Pracoval jsem pro skupinu zvanou Karmínová karavana, pøed tím zranìním.}
{1107}{}{Nemám tušení, co je to vodní èip. Promiò, kamaráde.}
{1108}{}{Malá mírumilovná vesnice. Pravdìpodobnì nejslibnìjší spoleènost v pustinách.}
{1109}{}{Promiò, kámo. Moc toho nevím.}
{1110}{}{Promiò, kámo. Moc toho nevím.}
{1111}{}{Garl je nìjakej pošahanej zmrd, kterej si myslí, e by mohl s tìma svıma všivıma nájezdníkama vládnout svìtu. Jo, to urèitì.}
{1112}{}{Promiò, kámo. Moc toho nevím.}
{1113}{}{Promiò, kámo. Moc toho nevím.}
{1114}{}{Promiò, kámo. Moc toho nevím.}
{1115}{}{Promiò, kámo. Moc toho nevím.}
{1116}{}{Není to bájné Mìsto mrtvıch?}
{1117}{}{Promiò, kámo. Moc toho nevím.}
{1118}{}{Promiò, kámo. Moc toho nevím.}
{1119}{}{Promiò, kámo. Moc toho nevím.}
{1120}{}{Razlo je vıbornı doktor. Mìl bys ho navštívit, pokud jsi zranìn.}
{1121}{}{Razlo umí uzdravovat fakt dobøe, a jeho kapky jsou proslavenı!}
{1122}{}{Ovládají veškerou vodu v Hubu. Zmocnili se vodojemu a teï musí lidi platit, aby se napili.}
{1123}{}{Jedna z nejvìtších firem v Hubu. Pracoval jsem pro nì, ne jsem skonèil v Shady Sands.}
{1124}{}{Skupinka umírnìnıch obchodníkù v Hubu, kteøí nabízejí férové ceny, ani by se pouštìli do nebezpeèí.}
{1125}{}{Killian je starosta Junktownu. Má tam i obchod. Je to férovej chlap. Nikdy jsem pro nìj nemakal, ale vypadá v pohodì.}
{1126}{}{Gizmo má v Junktownu kasino. Slyšel jsem, e jsou tam krupiéøi svinì, co tì oškubou o poslední zátku a na hracích automaty jaktìiv nikdo nic nevyhrál.}
{1127}{}{Promiò, kámo. Moc toho nevím.}
{1128}{}{Kasino je Gizmùv obøí projekt v Junktownu. Pøináší to mìstu davy turistù a penìz, ale samozøejmì i problémy.}
{1129}{}{Killian má dobrej obchod v Junktownu.}
{1130}{}{Promiò, kámo. Moc toho nevím.}
{1131}{}{Promiò, kámo. Moc toho nevím.}
{1132}{}{Promiò, kámo. Moc toho nevím.}
{1133}{}{Promiò, kámo. Moc toho nevím.}
{1134}{}{Promiò, kámo. Moc toho nevím.}
{1135}{}{Jo, nìjakı dìti jsou v Shady Sands. Ne, ani jedno není moje.}
{1136}{}{Promiò, kámo. Moc toho nevím.}
{1137}{}{Promiò, kámo. Moc toho nevím.}
{1138}{}{Promiò, kámo. Moc toho nevím.}
{1139}{}{Radškorpióni jsou velmi nebezpeèní. Mají jedovaté ihadlo na ocase a jsou hroznì rychlí.}
{1140}{}{Pokud ti budou chybìt zátky, zkus nìkterou z karavanovıch spoleèností v Hubu.}
{1141}{}{Víš, my vdycky povedeme války. Jenome ta pøíští bude bojována s klackama.}
{1142}{}{Vidìl jsem hodnì podivnıch vìcí, kdy jsem hlídal karavany z Hubu. Mutovaní kojoti, kudlanky, radškorpióni a tak.}
{1143}{}{Promiò, kámo. Moc toho nevím.}
{1144}{}{Je to ubohá skupinka nájezdníkù, kteøí pøepadají Shady Sands a myslí si, e by mohli ovládnout svìt nebo podobnou kravinu.}
{1145}{}{Je to Aradeshova dcera. Je dost pìkná, ale na mì u jedna doma èeká.}
{1146}{}{Promiò, kámo. Moc toho nevím.}
{1147}{}{Promiò, kámo. Moc toho nevím.}
{1148}{}{Promiò, kámo. Moc toho nevím.}
{1149}{}{Promiò, kámo. Moc toho nevím.}
{1150}{}{Promiò, kámo. Moc toho nevím.}
{1151}{}{Máš nìjakı pivko?}
{1152}{}{Pouil jsem jednou drogu Psycho, kdy sem doprovázel karavanu. Byl jsem pak dost nervózní. Zvláštní.}
{1153}{}{Seth je kapitán strácù. Jen mezi námi, neohlídal by ani jablko pøibitı k vlastní noze.}
{1154}{}{Aradesh je vùdcem v Shady Sands. Laskavı a trpìlivı èlovìk zároveò, moná trochu bláznivı.}
{1155}{}{Hej, pokud potøebuješ pomoc, Razlo je ten pravı. Razlo je fakt dobrej felèar.}
{1156}{}{Promiò, kámo. Moc toho nevím.}
{1157}{}{Promiò, kámo. Moc toho nevím.}
{1158}{}{Promiò, kámo. Moc toho nevím.}
{1159}{}{Promiò, kámo. Moc toho nevím.}
{1160}{}{Promiò, kámo. Moc toho nevím.}
{1161}{}{Promiò, kámo. Moc toho nevím.}
{1162}{}{Nevím. Moná e nìco, ale nejsou ádnı dùkazy.}
{1163}{}{Promiò, kámo. Moc toho nevím.}
{1164}{}{To jsem já.}
{1165}{}{Nìkteøí kupci pøicházejí z Hubu do Junktownu za obchodem. To je vše, co vím.}

{1999}{}{Nauèil jsem se nìjaké nové triky.}
{2000}{}{Promluvme si o naší taktice v boji.}
{2001}{}{Jo?}
{2010}{}{Schovej svoji zbraò.}
{2011}{}{Sundej si zbroj.}
{2012}{}{Dávej pøednost boji na dálku pøed bojem zblízka.}
{2013}{}{Dávej pøednost boji zblízka pøed bojem na dálku.}
{2014}{}{Vyber si sám, jak chceš bojovat.}
{2015}{}{To je pro teï vše.}
{2100}{}{Jasnì, kámo.}

# Party member stuff / Too many party members
{2500}{}{Sorry kámo, ale tohle je na mì trochu moc velká skupina.}
{2501}{}{Díky za nabídku, ale potøebují mì tady. Kdyby tvá skupina byla trochu menší, tak bych moná zmìnil názor.}
{2510}{}{Dobrá. Promluvíme si nìkdy jindy.}
{2520}{}{Tak jdeme.}

{2600}{}{[Pokraèovat]}
{2601}{}{Ještì nìco?}

# Ask about current town location
# Junktown
{2610}{}{Junktown je støednì velké mìsto. Øídí ho chlápek jménem Killian Darkwater, místní obchodník, šerif a starosta v jedné osobì.}
{2611}{}{Junktown je støednì velké mìsto. Ne natáhnul baèkory, velel tam chlápek jménem Killian.}
{2612}{}{Junktown je støednì velké mìsto. Od tı doby co Killian natáhnul baèkory, velí tam tomu chlápek jménem Gizmo. Ale poøád je to dobrı místo.}
# Hub
{2620}{}{Hub je nejvìtší obchodní centrum na Novém západì. Vede to tam hlavnì skupina zvaná Obchodníci s vodou, ale jsou zde i další obchodníci, napøíklad Karmínová karavana a Far Go. Je to vzkvétající mìsto, ale mezi obchodníky je spousta politickıch bojù.}
# Raiders
{2630}{}{Khanové; opravdu vìøí, e mùou dobıt celı svìt. Moc rozumu nejspíš nepobrali.}
{2631}{}{Khanové si mysleli, e mùou dobıt celı svìt. Teï jsou všichni mrtví.}
# Necropolis
{2640}{}{Tohle je to slavné mìsto mrtvıch? Nevìøil jsem, e se mi ho nìkdy podaøí navštívit.}
# Everything else
{2650}{}{Promiò kámo, ale tady jsem nikdy nebyl.}

# Fo1in2
{3500}{}{Hele kámo, myslím e mi zlomili konèetinu.}
{3501}{}{Pøipadá mi, jako bych hoøel! Asi jsem dostal pøíliš velkou dávku radiace.}
{3502}{}{Myslím, e jsem byl otráven.}
