#############################################################
#  The following lines are for what the player received     #
#  experience for (ie, picking a lock, disarming traps).    #
#############################################################
{102}{}{Úspìšnì jsi zneškodnil past.}
{103}{}{Nepodaøilo se ti zneškodnit past.}
{104}{}{Omylem jsi spustil past.}

# Prepend Lines with NPC name
{105}{}{ úspìšnì zneškodní past.}
{106}{}{ nedokáže zneškodnit past.}
{107}{}{ omylem spustí past.}
