{100}{}{Vidíš Paladina.}
{101}{}{Promiò, máme poplach. Teï s tebou nemùu mluvit.}
{102}{}{Vidíš nìco?}
{103}{}{Za tohle ti mutanti zaplatí.}
{104}{}{Neboj, všechno máme pod kontrolou.}
{105}{}{Bıt tebou, zasvìcenèe, moc bych se tu nepotloukal, pravdìpodobnì tu ještì dojde k poøádnému krveprolití.}
{106}{}{Dr se v dohledu, zasvìcenèe.}
{107}{}{Bıt tebou, cizinèe, moc bych se tu nepotloukal, pravdìpodobnì tu ještì dojde k poøádnému krveprolití.}
{108}{}{Dr se v dohledu, cizinèe, zaèíná jít do tuhého.}
{109}{}{Odejdi.}
{110}{}{Nevyrušuj, máme poplach.}
{111}{}{Potichu.}
{112}{}{Nezdruj mì, zasvìcenèe.}
{113}{}{Zavøi klapku, cizinèe.}
{114}{}{Zmiz, cizáku, ne poteèe další krev.}
{115}{}{Svìt musí bıt zbaven tìchto zrùdnıch ohavností.}
{116}{}{Co to bylo?}
{117}{}{Bolej mì nohy.}
{118}{}{Za tohle zaplatí...}
{119}{}{Jen a to zkusí znovu.}
{120}{}{Co to... Oh, to nic.}
{121}{}{Buï ve støehu!}
{200}{}{Bobe, jaká je situace?}
{201}{}{Všechno èistı.}
{202}{}{Myslím, e u se nevrátí.}
{203}{}{S tím nepoèítej.}
{204}{}{U jsou zprávy od zvìdù?}
{205}{}{Ještì ne.}
{206}{}{Zvìdi hlásí všude klid.}
{207}{}{Dobøe.}
{208}{}{Tak na èem jsi dìlal dneska po ránu, Rayi?}
{209}{}{Jen jsem zkoušel zvìtšit dostøel plazmové pušky.}
{210}{}{U jsi zkontroloval laserovı rotaèák?}
{211}{}{Jo, makal jsem na prvním prototypu.}
{212}{}{Nechte toho vanìní!}
{213}{}{Ano, pane. Pardon, pane.}
