{100}{}{Muž sebou trhanì poškubává.}
{101}{}{Oohhh . . .}
{102}{}{Vidíš bledého, šlachovitého mladíka.}
{103}{}{Vidíš Jarvise, mladšího Sethova bratra.}
{104}{}{Ahoj. Promiò, ale necítím se teï zrovna nejlíp. Prosím, jestli mùžeš pomoci s radškorpióny, vyhledej mého bratra Setha.}
{105}{}{Dìkuji ti mnohokrát. Jmenuju se Jarvis, jsem Sethùv mladší bratr. Pokud je tu cokoli, co bys chtìl vìdìt, prosím, jen se ptej.}
{106}{}{Ahoj. S èím ti mohu pomoct?}
{107}{}{Mùžeš mi øíct více o bratrovi?}
{108}{}{Øekni mi nìco o vesnici.}
{109}{}{Jenom si pokecat, díky.}
{110}{}{Seth je velmi dobrý strážný. Je velmi odhodlaný. Nìkdy možná až moc, øekl bych. Ale jde mu o blaho celé naší vesnice.
Já jen chtìl Sethovi pomoc. Jednou zabiju velkého radškorpióna a stanu se hrdinou! Všichni v Shady Sands mì budou obdivovat...}
{111}{}{Vesnice Shady Sands byla založena pøedchùdcem našeho souèasného vùdce Aradeshe. Já a Seth to tady hlídáme. Máme tady studnu a zavlažovací systém, takže se o sebe dokážeme postarat.}
{112}{}{Tento muž je otráven nebezpeèným jedem.}
{113}{}{Netušíš, co mohlo zachvátit tohoto muže.}
{114}{}{Tento muž je otráven škorpióním jedem.}
{115}{}{Netušíš, co mohlo zachvátit tohoto muže.}
{116}{}{Tahle dovednost tady nepomùže.}
{117}{}{Jen bìhem pár minut se muž zaèal zotavovat.}
{118}{}{Sef je blatl?}
{119}{}{Tohue misto?}
{120}{}{Duh.}
{200}{}{ bodù zkušenosti za vyléèení Jarvise.}
