{100}{}{Nabízíme léèbu tìla k oèistì ducha. Co pro tebe mohu udìlat?}
{101}{}{Ano. Pomoz mi.}
{102}{}{Co jste zaè?}
{103}{}{Co se stalo tìm, co tu byli pøed tebou?}
{104}{}{Uhn...}
{105}{}{To je v poøádku, mé dítì. Teï tì vyšetøíme.}
{106}{}{Poehnaní jsou mírné mysli. Není s tebou nic v nepoøádku, dítì. Mùeš vstát, rozbìhnout se a hrát si.}
{107}{}{Jsi vyléèen. V budoucnu buï opatrnìjší.}
{108}{}{Jsi zranìn.}
{109}{}{Vidím, e jsi uštknut.}
{110}{}{Hmm, radiaèní ozáøení. Tohle naneštìstí léèit nedokáeme.}
{111}{}{Poadujeme pøíspìvek ve vıši}
{112}{}{ zátek. Pøedem. Je to pøijatelné?}
{113}{}{Ano.}
{114}{}{Ne.}
{115}{}{Ale já takovéhle peníze nemám!}
{116}{}{Pøijmete }
{117}{}{ zátek?}
{118}{}{Dìti nesmlouvají. Tak pøijmeš naši cenu?}
{119}{}{Ano. Jistì, pøijímám.}
{120}{}{To mì radši kousni!}
{121}{}{Díky, synu. Pomodlíme se za tvé vyléèení.}
{122}{}{Díky, dcero. Pomodlíme se za tvé vyléèení.}
{123}{}{Prosím. Mír a poehnání Dìtí tì bude vyprovázet.}
{124}{}{Nemáš dost penìz. Pokud dáš vše, co máš, vyléèíme tì. Je to pøijatelné?}
{125}{}{Ano.}
{126}{}{Ne.}
{127}{}{Pokud dáš vše, co máš, vyléèíme tì. Je to pøijatelné?}
{128}{}{Ano.}
{129}{}{Ne.}
{130}{}{Máš víc ne dost na pøíspìvek. Potøebuješ se vzdìlat v matematice, mé dítì.}
{131}{}{My jsme Dìti katedrály. ijeme a pracujeme mezi tìmi nešastníky, kteøí ivoøí v pustinì. Pokud nìkdy dorazíš do L.A. kostnice, zastav se v Katedrále.}
{132}{}{Díky.}
{133}{}{Co dìláš?}
{134}{}{Jsme léèitelé a uèitelé míru. Léèíme tìlo, aby se mohla uzdravit i duše. Vše, co poadujeme, je malı pøíspìvek na nákup léèebnıch potøeb.}
{135}{}{To zní jako dobrá myšlenka.}
{136}{}{To zní jako hromada sraèek.}
{137}{}{Neptali jsme se tì. Vidím, e jsi unavenı z poslouchání naší víry. Pokud chceš nìco jiného, jsme tu k dispozici.}
{138}{}{To je nejsvatìjší z myšlenek. Míøíme k absolutnímu míru v pustinì. Všechna stvoøení budou ít v Jednotì.}
{139}{}{Díky. Hezkı den.}
{140}{}{Vìnovali nám tento dùm, abychom mohli šíøit svaté slovo a plnit naši povinnost léèitelù.}
{141}{}{A není z toho doktor Morbid naštvanej?}
{142}{}{To od nich bylo hroznì pìkné. Díky.}
{143}{}{Cokoli cítí ta pohanská duše, o to se Dìti nestarají. Jsme tu kvùli naší povinnosti, a ta bude splnìna.}
{144}{}{Uh, fíí, díky. Sbohem.}
{145}{}{Proè to dìláš? My ti nijak neubliujeme!}
{146}{}{Nevypadáš, e bys potøeboval jakoukoli pomoc.}
