#
# THIS FILE IS NOT USED!! No need to translate.
#
# Use "BULLBORD.MSG" instead.
#
#
{100}{}{Vidíš nástìnku s pracovními nabídkami.}
{101}{}{ZAMÌSTNÁNÍ! Chcete práci? Potøebujete peníze? PODÍVEJTE SE SEM!}
{102}{}{Prosím, nevylepujte stejné zprávy dvakrát. --Šerif Greene.}
{103}{}{1       Ztracená karavana! Odmìna!}
{104}{}{2       Hledají se noví strážci karavan.}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{[Odejít]}
{110}{}{ODMÌNA: ZTRACENÁ KARAVANA.  Odmìna 500 pro každého, kdo by dostal ty parchanty, kteøí plení naše karavany. Detaily u Butche Harrise, Far Go Traders, severovýchod Kupeckého tržištì.}
