{100}{}{Vidíš Kylea.}
{101}{}{Vidíš rytíøe.}
{102}{}{Ahh... Tak to jsi ty, co?}
{103}{}{Cože?}
{104}{}{No, tak kdo vlastnì si?}
{105}{}{Nic, já jen, že dosud se nikdo z ruin Starobylého øádu nevrátil.}
{106}{}{Copak tady dìláš?}
{107}{}{Co? Tak proè mì tam dolù poslali?}
{108}{}{Bylo to tìžké, ale ne nemožné.}
{109}{}{Heh, heh. Hádám, že se tì chtìli jenom zbavit, jo? Tak to asi nevyšlo.}
{110}{}{Jasnì. Tak mi øekni, co tu dìláš?}
{111}{}{No, v podstatì jsem se k vám pøidal proto, abych získal energo zbroj.}
{112}{}{Vyserte si voko, padám.}
{113}{}{Opravuju vìci, udržuju techniku v chodu, prostì takovýhle blbosti.}
{114}{}{Umìl bys opravit vodní èip?}
{115}{}{Jaký druh 'vìcí'?}
{116}{}{To vypadá jako pøíjemná práce. Mìj se.}
{117}{}{Energo zbroje nebo cokoliv jiného, co potøebuje údržbu.}
{118}{}{Jak bych mohl dostat nìjakou energo zbroj?}
{119}{}{Tady ti mùžu dát tenhle kousek, ale chybí mu systolický motivátor a bez nìj je nepoužitelný.}
{120}{}{A ten bych mohl sehnat kde?}
{121}{}{No, stejnì díky.}
{122}{}{No, dost jich mají v zásobovací sekci, ale Michael s tìma jeho pitomejma formuláøema øíká, že tahle energozbroj nesplòuje specifikace. Pitomí byrokrati.}
{123}{}{Jak to myslíš, že nesplòuje specifikace?}
{124}{}{No a kdybych ti dones ten systolický motivátor, dokázal bys to opravit?}
{125}{}{Vidíš támhle tu oèní souèástku? Tu jsem musel znova pøipájet na místo a hádám, že to nevypadá dost hezky na to, aby to prošlo kontrolou.}
{126}{}{Máš pravdu. Vypadá to jako pìknej šrot. Do takový energo zbroje by mì nedostali ani po smrti.}
{127}{}{Doprèic, padej odsuï, než se...}
{128}{}{Hmm, poèkej minutu, èlovìèe, to ti dá pìknì zabrat... Tady ti pùjèím tenhle manuál a nástroje, no a mùžeš si to zkusit spravit sám.}
{129}{}{No a mimo Michaelùv sklad, dá se sehnat i nìkde jinde?}
{130}{}{Jo, to je dobrý. Ještì se vrátím.}
{131}{}{Heh, no, Rhombus jich pár má. Ale toho bych se radši neptal. Pouze 'vyvolení' mají právo nosit tyhle energo zbroje. Mimo to, zrovna on je na tohle pìknì vysazený.}
{132}{}{Hmm. Jasnì, no díky moc.}
{133}{}{To si nemyslím. Ani nevím, jak vypadá.}
{134}{}{No, stejnì díky.}
{135}{}{Teda, co si to za mechanika, když neumíš ani opravit obyèejný vodní èip?}
{136}{}{A jak mùžu dostat takovou energo zbroj, aniž bych musel roky sloužit Bratrstvu?}
{137}{}{Pøezdívka je Kyle. Ještì nikdy pøedtím jsem se nesetkal s mýtem.}
{138}{}{A co by to mìlo znamenat?}
{139}{}{Co tady dìláš?}
{140}{}{Já taky nemám. No, mìj se.}
{141}{}{Podle Maxsonových pøíbìhù bys øekl, že to tam je devátý okruh pekla.}
{142}{}{Maxson? Ten generál Maxson?}
{143}{}{Ne generál Maxson, jeho dìdeèek, Roger Maxson. Slyšel jsem, že jsi pøines nazpátek disk s informacemi o tìch chlapech, co se proti nìmu vzbouøili a šli tam dolù najít ztracené technologie.}
{144}{}{Jasnì, hádám že jo. Jsem }
{145}{}{, a kdo jsi ty?}
{146}{}{O tom bych radìji nemluvil.}
{147}{}{Jasnì, zavšivený bastardi. Nemùžu pochopit, že tì tam dolù poslali jen tak.}
{148}{}{A jediný, co mi za to dali, je trocha munice!}
{149}{}{Hej, zasvìcenèe, máš nìco pro mì?}
{150}{}{Ne, øíkal jsem mu, že jsi mì poslal, ale stejnì mi tu souèástku nechtìl dát.}
{151}{}{Ne, ještì jsem se tam nepodíval.}
{152}{}{Ne, zatím jsem nemìl to štìstí.}
{153}{}{No doprèic. A to jsem si myslel, že máš aspoò prùmìrný IQ. Øíkal jsem ti, že ten chlap má místo mozku formuláø.}
{154}{}{Dej si bacha, koho nazýváš idiotem!}
{155}{}{Já sem se ho jen snažil ukecat, no.}
{156}{}{Co mám dìlat, když mi to Michael nedá?}
{157}{}{Jdu.}
{158}{}{Noo... Za to bych ti mìl dát medaili. Ale myslím, že sis podìlal šance dostat to nìkdy ze skladu. Teï si už musíš vymyslet, jak to získat jinak. Nebo si najít energo zbroj jinde.}
{159}{}{Dobøe, mìj se.}
{160}{}{A kde jinde bych ho mohl sehnat?}
{161}{}{Hodnì štìstí.}
{162}{}{Zmiz, mám práci.}
{163}{}{Èau, sehnal si tu souèástku?}
{164}{}{Jo. Tady je.}
{165}{}{Jo, myslím že s tím mùžu klidnì ještì chvíli poèkat.}
{166}{}{Super! Tak, teï to jenom zamontujeme a je to.}
{167}{}{OK, tady to máš, vem si i tenhle manuál. Pokud už si nìkdy nìco opravoval, tak bys nemìl mít problém. Hodnì štìstí.}
{168}{}{Po tom všem? No dobøe, jen mi øekni, až budeš potøebovat, a pak si ho mùžeš opravit.}
{169}{}{No, nevím co ti na to øíct. Hádám, že si budeš muset oprášit svoje opraváøské znalosti. Já ti zatím ten motivátor schovám.}
{170}{}{Jo. Díky a mìj se.}
{171}{}{Zase ty. Mùžu ti nìjak pomoct?}
{300}{}{[Pokraèovat]}
