{100}{}{Vidíš nabušeného zjizveného maníka s poøádnım knírem.}
{101}{}{Vidíš Larse, seranta z Junktownské stráe.}
{102}{}{Má ještì nezahojené jizvy od posledních zranìní a vypadá jako poøádnı drsoò.}
{103}{}{Má jizvy od bodnıch i støelnıch zranìní. Jeho svaly budí opravdu respekt.}
{104}{}{To fakt není nejchytøejší vìc, snait se okrást stráe právì v Junktownu!}
{105}{}{Mohu ti nìjak pomoci, cizinèe?}
{106}{}{No, co se tu dá dìlat?}
{107}{}{Mùeš mi øíct nìco o Junktownu?}
{108}{}{Co seš zaè?}
{109}{}{Eergh.}
{110}{}{Pokud jsi jeden ze stránıch tady, tak bych mìl pro tebe informace.}
{111}{}{Hej! Ty! Víme o tobì všechno, ty sadisto!}
{112}{}{Hodnì, dokud zùstaneš na správné stranì. Máme tu obchod Killiana Darkwatera, kde si mùeš nakoupit nejnutnìjší veci. Taky tu je Gizmovo kasino, pokud chceš zkusit svoje štìstí. A nebo jestli chceš nìco ostøejšího k pití, tak mùeš zajít do Skum Pitt. Ale moc se tam nezøiï.}
{113}{}{Hej, poøádná rvaèka, to je ono!}
{114}{}{No, radši by ses mìl ovládat. Máme tady svobodu, ale jenom voca poca. Nedìlej problémy, nebo si na tebe budeme muset došlápnout.}
{115}{}{To jako vánì?!}
{116}{}{Podívej, kámo, mùj úkol je udrovat tady poøádek a pokud budu kvùli tomu muset zlámat pár hnátù, tak to klidnì udìlám. Tak si raèi dej bacha.}
{117}{}{Já a moji mui dìláme pro Killiana Darkwatera. Udrujeme tady poøádek a dríme na uzdì všechny ty vrahy, zlodìje a podobnou paká z pouštì. Pokud pøijmeš mojí radu, tak se radši dr dál od Gizma. To tlustı prase je namoèenı v pìknı špínì, ale zatím na to nemáme dùkazy. On a ta jeho banda Lebkounù si koledují si o poøádnej vıprask.}
{118}{}{Teda pìkná nuda, tady . . .}
{119}{}{Je dobrı vìdìt, e se tu nìkdo stará o poøádek. Díky.}
{120}{}{No, a co vám brání jednoduše Gizma a Lebkouny odprásknout?}
{121}{}{No, je to naše práce. Ale je dobrı vìdìt, e jí dokáe nìkdo i ocenit. Díky.}
{122}{}{To nejde jenom tak. Víme e Gizmo je namoèenej v nìjakı špínì, ale potøebujeme na to dùkaz. To samı s Lebkouny, sem tam nìjakıho zavøeme, ale to jim nebrání otravovat dál. Bohuel jsme zatím nezískali ádnı pøímı dùkaz o tom, e by se chystali nìkoho okrást nebo zavradit.}
{123}{}{Moná bych vám mohl pomoct.}
{124}{}{Dobøe, hodnì štìstí.}
{125}{}{No teda, pokud by se ti podaøilo získat cokoliv, budeme ti zavázaní. Zajdi za Killianem a promluv si s ním o Gizmovi. A kdyby se ti podaøilo zjistit nìco na Lebkouny, tak se jen zastav a my u si to s nima nìjak vyøídíme.}
{126}{}{Dík. A dej si pozor.}
{127}{}{Šéfuju stránım tady ve mìstì. Jmenuju se Lars. A proto musím vìdìt, kdo si ty.}
{128}{}{Já jsem }
{129}{}{.}
{130}{}{Neotravuj, nemám ti co øíct.}
{131}{}{Vítej v Junktownu, }
{132}{}{. S èímpak bych ti mohl pomoct?}
{133}{}{Mùeš mi øíct nìco o Junktownu?}
{134}{}{Hledám nìjakou práci. Nevíš o nìèem?}
{135}{}{Zdravím tì, poutníèe. Potøeboval bys nìco?}
{136}{}{Co?}
{137}{}{Hledám nìjakou práci.}
{138}{}{Jen jsem se zastavil, abych tì pozdravil.}
{139}{}{Mám dùkazy o nelegálních aktivitách Lebkounù.}
{140}{}{Ano, velím tady stráím. Co pro mì máš?}
{141}{}{Nic, jen to tak zkouším.}
{142}{}{Mám nìjaké dùkazy od Sherry, e Lebkouni jsou namoèenı v nìjakı špínì.}
{143}{}{No, pokud máš nìco na Lebkouny, tak se neboj mi to øíct . . .}
{144}{}{Úèastnili se nìkolika vrad a krádeí tady okolo.}
{145}{}{Pøemluvil jsem jednu z nich, Sherry, aby proti nim svìdèila.}
{146}{}{To je sice skvìlı, ale já je nemùu zavøít jenom proto, e nìkdo o nich øíká špinavosti. Potøebuju nìjakı nezvratnı dùkaz nebo nìkoho z nich, kdo bude ochotnı svìdèit.}
{147}{}{Zjistím, co se s tím dá dìlat.}
{148}{}{Mám svìdectví od Sherry, bıvalé èlenky gangu.}
{149}{}{Perfektní. Já si jí vyslechnu a jsem si jistı, e to bude staèit na to, abych je pìknì zavøel a zèernaj.}
{150}{}{Hele, tohle není hra. Tady tì mùe nìkdo sejmout. Pokud najdeš nìjakı opravdovı dùkaz, tak se vra, jinak mì ale neotravuj!}
{151}{}{Pokud ti to není proti mysli, tak bych potøeboval nìjaké dùkazy proti Lebkounùm. Cokoliv co by dokázalo, e dìlají nìco nelegálního. Nebo mùeš zajít za Killianem a ten ti dá nìjakou práci.}
{152}{}{Díky za pomoc. Díky tobì je Junktown teï o trochu bezpeènìjší.}
{153}{}{Padej dál, kámo.}
{154}{}{ zkušenosti za získání dùkazù proti Lebkounùm.}
{155}{}{Si pøipravenı na Gizma?}
{156}{}{Jasnì. Ustøelíme mu ptáka . . .}
{157}{}{Ne, rozmyslel jsem si to.}
{158}{}{Dobøe, jdeme na to.}
{159}{}{No, tak tady radši poèkej, aby tì netrefila nìjaká ta zbloudilá kulka.}
{160}{}{Killian mì poslal, abych pomohl vyhnat Gizma.}
{161}{}{Killian mì poslal. Jdeme sejmout Gizma.}
{162}{}{Díky za všechnu pomoc. Tady je 500 zátek. A v Junktownu si kdykoliv vítán.}
{163}{}{Coo? Hmm. No ještì uvidíme. Pošlu pár chlapù, aby je pøepadli, a se o to pokusí. Pùjdeš taky?}
{164}{}{Ne díky, dneska sem u svùj dobrej skutek udìlal.}
{165}{}{Jasnì.}
{166}{}{Lebkouni plánujou sejmout Neala!}
{167}{}{Larsovi mui Lebkouny rychle rozdrtili.}
{168}{}{Lars zøejmì ještì ije, ale u si nezabojuje.}
{169}{}{Chlape, to si pìknì posral. Potøebovali jsme dùkaz, abychom mohli dostat Gizma èistì a legálnì. Mezi námi, jsem sice rád, e jsi se toho tlusocha zbavil, ale radši mi padej z oèí a ve mìstì se u se neukazuj.}
{170}{}{Lidi jako ty tady nechceme. Máš patnáct sekund, ne ti upálím tu tvojí palici.}
{171}{}{Zdravím tì! Co pro tebe mùu udìlat tentokrát?}
{172}{}{Uh-huh.}
{173}{}{Nuh-uh.}
{174}{}{ zkušenosti za pomoc pøi likvidaci Lebkounù.}

{970}{}{To je moje jméno.}
{971}{}{Mluvíš se mnou.}
{972}{}{To jsem já}

{980}{}{O tom nic nevím.}
{981}{}{Promiò, nemám páru.}
{982}{}{Nikdy jsem o tom neslyšel.}

{1000}{}{Killian|Kilian|Starosta}
{1001}{}{Gizmo}
{1002}{}{Junktown|Junk Town|Junk}
{1003}{}{Shady Sands|Shady|Sands}
{1004}{}{Hub}
{1005}{}{Cip|vodni cip}
{1006}{}{Casino|Kasino}
{1007}{}{obchod}
{1008}{}{parac}
{1009}{}{doktor}
{1010}{}{prodej}
{1011}{}{pustina}
{1012}{}{mesto}
{1013}{}{Fallout}
{1014}{}{zlocin|zlodej}
{1015}{}{Necropolis|Nekropolis}
{1016}{}{Pohrebiste}
{1017}{}{zvesti}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{lebkouni}
{1020}{}{Khanove|zmije|najezdnici}
{1021}{}{Crash House}
{1022}{}{pivo|chlast}
{1023}{}{Brahmina|Brahminy}
{1024}{}{prace}

{1100}{}{Killian je starosta. Vede taky vlastní obchod.}
{1101}{}{On vede kasino. Je to pìknej gauner.}
{1102}{}{Tohle je Junktown.}
{1103}{}{Hmm, myslím e je to nìjaká malá vesnice. Nikdy jsem tam nebyl.}
{1104}{}{Velké mìsto na jihu.}
{1105}{}{Coe co? Promiò, nemám zdání.}
{1106}{}{Je to velká budova v severozápadní èásti mìsta. }
{1107}{}{Killian má obchod v centru mìsta.}
{1108}{}{O tom nic nevím, ale jméno je to pìknì dìsivé.}
{1109}{}{Pokud jsi zranìnı, Doktor Morbid se o tebe postará. Jeho klinika je na jihu.}
{1110}{}{Killian Darkwater vede místní obchod. Tam mùeš nakupovat a prodávat co hrdlo ráèí.}
{1111}{}{V pustinách máme hlídky. Je to nebezpeèné místo, ale zvládáme to. }
{1112}{}{Killian vede místní obchod. Pokud se chceš napít, bar Skunèí díra je na severu. Jestli si chceš zahrát, je tu Gizmovo kasíno.}
{1113}{}{Nejlepší je zálést si do nìjakého Vaultu}
{1114}{}{Pokud tì pøistihnou pøi krádei, tak tì povìsí.}
{1115}{}{Myslíš Mìsto mrtvıch? Slyšel jsme jen zvìsti.}
{1116}{}{Tuším, e leí nìkde daleko na jihu}
{1117}{}{Hmm, nic mì nenapadá.}
{1118}{}{To je náš místní bar. Jídlo ujde, ale pivo je skvìlé.}
{1119}{}{Na ty je tøeba dávat si pozor. Proè se ptáš? Nìco ti udìlali?}
{1120}{}{Tady s nima nemáme moc potíí, ale slyšel jsem, e na severu je to o dost horší.}
{1121}{}{Pokud potøebuješ nìkde hlavu sloit, navštiv Crash House.}
{1122}{}{Ne, díky.}
{1123}{}{Náš hlavní zdroj obivy pøi obchodování s Hubem.}
{1124}{}{Promluv si s Killianem. Je náš starosta a urèitì pro tebe bude nìco mít.}
