{100}{}{Vidíš Lauru.}
{102}{laura0m}{Zdravím tì, bratøe. Mùu ti v tento blahoslavenı den s nìèím pomoci?}
{104}{laura0f}{Zdravím tì, sestro. Mùu ti v tento blahoslavenı den s nìèím pomoci?}
{105}{}{Ty jsi Laura?}
{106}{}{Mùu se tì zeptat na nìco ohlednì Dìtí?}
{107}{}{Jakı druh „pomoci“ nabízíš?}
{108}{}{Mami?}
{110}{laura1a}{To je milé, ale já nejsem tvoje matka. Ale jsem si jistá, e jí tu nìkde najdeš.}
{112}{laura2}{To myslíš asi mì. Potøebuješ nìco?}
{113}{}{Nicole mì poslala, abych si s tebou promluvil.}
{114}{}{Uh... ne.}
{116}{laura3}{Nicole? Promiò, ale já nikoho takového neznám.}
{117}{}{No, øekla mi, abych se prokázal heslem „Red Rider“.}
{118}{}{Ale samozøejmì e znáš. Ona mì poslala!}
{120}{laura4}{Promiò. Já... Já nevím. Pojï radši nìkam, kde nás nikdo neuslyší.}
{122}{laura9}{Hroznì se za ty potíe omlouvám. Doufám, e tì to neobtìovalo.}
{124}{laura10}{Jsi si... jistı? Uh... odpus mi mou zvìdavost, ale pøipadáš mi takovı zvláštní.}
{125}{}{No, poslala mì Nicole.}
{126}{}{U jsem o tobì slyšel, ale pøedstavoval jsem si tì jinak.}
{128}{laura11}{Já... já se omlouvám, ale taková pozornost mì znervózòuje. Nevím proè, ale pøijde mi to hloupé. No, uij si to.}
{130}{laura14}{Och, já nejsem ádná autorita. Spíš jdi za Morpheusem. On je Veleknìz. Jsem si jistá, e ti mùe pomoci víc ne já.}
{132}{laura15}{Ale já jsem jenom myslela... oh... u musím jít.}
{134}{laura16g}{Á, ráda tì vidím. Jenom se procházíš, nebo potøebuješ pomoct?}
{136}{laura16b}{Potøebuješ s nìèím... pomoci?}
{137}{}{Ty jsi Laura?}
{138}{}{Mùu se tì zeptat na nìco ohlednì Dìtí?}
{139}{}{Nic, dìkuji.}
{140}{}{Uh, Mami?}
{142}{laura16a}{Ne. U jsme o tom mluvili. Musíš to zkusit nìkde jinde, pøíteli.}
{144}{laura21}{Oh... jsem ráda, e jsi mì našel. Nicole poslala seznam informací, které jsem mìla vyhledat.}
{145}{}{A co jsi našla?}
{147}{laura22}{Um. Je toho tolik, e si nejsem jistá, no... kde vlastnì zaèít. Je nìco speciálního, co potøebuješ vìdìt pøednostnì?}
{148}{}{Existuje nìjakı tajnı vchod ve Vnitøní svatyni v Chrámu?}
{149}{}{Co jsi zjistila o Vùdci?}
{150}{}{Co plánují Dìti katedrály?}
{151}{}{Co dìlá taková pìkná dívka jako ty na takovém místì?}
{152}{}{Nic víc, díky.}
{154}{laura24}{Ty se nepotøebuješ dostat do Vnitøní Svatynì.}
{155}{}{A kam jinam?}
{157}{laura25}{Sledovala jsem Morpheuse tajnım schodištìm. Ten chlap dole otevøel tajné dveøe a byl pryè.}
{158}{}{A potom?}
{159}{}{Mùeš mi ty dveøe ukázat?}
{161}{laura26}{Otevírá je tím svım zvláštním klíèem a potom zmizí. Radši jsem za ním nikdy nešla.}
{162}{}{A víš, kde má ten klíè?}
{163}{}{Proè ne?}
{165}{laura27}{No, mám dojem, e ho nosí na krku.}
{166}{}{Ukáeš mi teï ty dveøe?}
{168}{laura28a}{Jo, jasnì.}
{169}{}{Perfektní, tak jdeme.}
{170}{}{Mùu se pøedtím zeptat ještì na pár otázek?}
{172}{laura29}{Pojï za mnou.}
{174}{laura30a}{Jasnì, ale musíme spìchat.}
{176}{laura30b}{Jo, ale a to odsejpá.}
{178}{laura31}{Vìø mi, jestli jsi vidìl Nightkina, tak asi máš pøedstavu, o èem mluvím. Pokud teda nejsi blázen.}
{179}{}{Moná sem, ale nebojím se.}
{180}{}{Chápu to. Mùu se ještì na nìco zeptat?}
{182}{laura32}{Heh, to je teda veselı. Hele, jsem tady pøímo ve støedu všeho. Máš problém, jak to dìlám? Nech si ho pro sebe. Pochopils to?}
{183}{}{Co s tím udìláš, budeš jenom skuèet?}
{184}{}{Pokud to tak chceš.}
{185}{}{Máš pravdu, promiò. Vrame se radši k úkolu.}
{187}{laura33}{No, ne moc. Dìti ho uctívají a obèas se v hlavní hale objeví jeho velkı hologram.}
{188}{}{Vypadá skuteènì?}
{189}{}{To zní drsnì.}
{191}{laura34}{Ano a ne. Jednou jsem se protlaèila do pøední øady a objevila jsem velkı pøístroj s èoèkami pod oltáøem.}
{192}{}{Nejspíš nìjakı holo-projektor.}
{193}{}{No?}
{195}{laura35}{Huh... vìø mi, to bylo nejdøív, ale potom jsem to prozkoumala, kdy se nikdo nedíval, a našla jsem pod oltáøem takovı zvláštní pøístroj s kabely a velkıma èoèkama.}
{196}{}{Nejspíš nìjakı holo-projektor.}
{197}{}{No?}
{199}{laura36}{No jsem si docela jistá, e Vùdce opravdu existuje a nejspíš jsem i zjistila, kde je.}
{200}{}{Kde?}
{202}{laura37}{Vdycky chvilku potom pøijde Morpheus skrz tajné schodištì pod Chrámem. Otevøe tajné dveøe nìjakım zvláštním klíèem. Vùdce bude nejspíš tam dole.}
{203}{}{Mùeš mi teï ukázat to schodištì?}
{204}{}{Víš, kde schovává ten klíè?}
{206}{laura38}{A teï to horší. Morpheus káe o tom, e Zemì by mìla bıt zbavena všech nevìøících a podobnıch kecù. Bojím se, e chce nìjak ovládnout celı svìt!}
{207}{}{Mohli by to dokázat?}
{208}{}{Co je jejich první cíl?}
{210}{laura39}{Teï u chápeš, e to mùou udìlat. Myslím, e mají dost èlenù a v kadém mìstì nemocnice plné tajnì schovanıch zbraní a vıbušnin.}
{211}{}{Musíme to oznámit Následovníkùm.}
{212}{}{Co budeš dìlat?}
{214}{laura40}{To jsem plánovala. V podstatì a budeme hotovi, tak tam mám namíøeno.}
{215}{}{Jednu rychlou otázku?}
{216}{}{Tak to tì nechám jít.}
{218}{laura41}{Dobøe. Hodnì štìstí!}
{220}{laura42}{No, já jdu varovat Nicole. A doufejme, e Následovníci budou schopní poslat pomoc do ostatních mìst.}
{221}{}{Rád bych se pøedtím zeptal ještì na pár otázek.}
{222}{}{Dobøe, tak tì nechám jít.}
{224}{laura43}{Adytum, to mìsto naprosto nemá šanci.}
{225}{}{A co Následovníci?}
{226}{}{Mùu pomoct zachránit Adytum?}
{228}{laura44}{Dìti si myslí, e od nás nebezpeèí nehrozí. No, ještì jim ukáeme.}
{229}{}{Dobøe. Co se chystáš udìlat?}
{230}{}{Mùu nìjak pomoci zachránit Adytum?}
{232}{laura45}{Jasnì, mùeš pomoct tak, e najdeš Vùdce a jak by øekla moje babièka: „Ufikneš mu ty jeho ztrouchnivìlı koule“. Ona obèas dokázala perfektnì vystihnout situaci.}
{233}{}{Jak se k nìmu dostanu?}
{234}{}{Promyslím to. Mùu se ale pøedtím ještì na nìco zeptat?}
{235}{}{U jdu.}
{237}{laura46}{Chystají se ovládnout všechny mìsta!}
{238}{}{Která?}
{240}{laura47}{Adytum u padlo. Na øadì je Hub.}
{241}{}{A co pøi tom dìlají Následovníci?}
{242}{}{Kruci. Co mám udìlat?}
{244}{laura48}{Poslali jsme u skupinu, která mìla pomoct v Adytumu, ale oni je všechny dostali. Nicole poslala další do Hubu. Jenom doufám, e tam se dostanou vèas.}
{245}{}{Kruci. Co mám udìlat?}
{247}{laura49}{Oni u obsadili Hub a Adytum! Na øadì ale teï jsou Následovníci, a tak pøipravujeme obranu.}
{248}{}{A co tady potom dìláš ty?}
{249}{}{Co mùu udìlat?}
{251}{laura50}{Já jsem tady, abych dohlíela na Dìti.}
{252}{}{Co mùu udìlat?}
{254}{laura51}{Dìti zakládají nemocnice všude okolo. Pche. Asi se snaí získat dùvìru lidí.}
{255}{}{A zabírá to?}
{256}{}{Mùeme je ještì zastavit?}
{257}{}{To je ta nejvìtší hovadina, co jsem slyšel!}
{259}{laura52}{Ah, u to tak vypadá. Myslím, e lidé u jim zobou z ruky. Jakto e nepøišli na to, jakı podvod tu na nì hrají?}
{260}{}{Seš si jistá?}
{261}{}{Jak je mùu zastavit?}
{263}{laura53}{Jedna vìc — tady okolo se lidé èasto ztrácí, zatímco Nightkinù pomalu pøibıvá.}
{264}{}{Proè?}
{265}{}{To nevypadá dobøe. Ale já potøebuju ještì nìco vìdìt, ne zaènu jednat.}
{267}{laura54}{Nevím. To tady pøece hledáš, ne?}
{269}{laura55}{Najdi Vùdce a zastav ho!}
{270}{}{Co jsi zjistila o tomhle Vùdcovi?}
{271}{}{Budu.}
{273}{laura56}{Huh, to taky doufám. No, ještì nìjaké otázky?}
{275}{laura57}{No, je to perfektní zpùsob, jak manipulovat s lidmi a Vùdce je v tom opravdu dobrı.}
{276}{}{Ne, je to ta nejblbìjší vìc, co jsem od tebe slyšel. Nejseš trochu paranoidní?}
{277}{}{Dobøe, já ho zastavím.}
{278}{}{Jak to mùu zastavit?}
{280}{laura58}{Promiòte?}
{281}{}{Slyšela jsi mì.}
{282}{}{No nic.}
{284}{laura59}{Tak dobøe. Hodnì štìstí!}
{286}{laura60}{Uh heh... Zoufale oèekávám, a na mì nìkdo pouije tenhle alostnej zpùsob.}
{288}{laura61a}{No, co pro tebe mùu udìlat?}
{290}{laura61b}{Oh, co teï?}
{291}{}{Potøebuju se ještì zeptat na pár otázek.}
{292}{}{Nic, díky.}
{294}{laura62}{Co to dìláš? Polo to!}
{296}{laura63}{Hej! Vypadni odtamtud!}
{297}{}{Nebo co?}
{298}{}{Sorry, u jdu.}
{300}{laura64}{Pøestaò!}
{302}{laura65}{Co... co tady dìláš. Musíš vypadnout!}
{303}{}{Ne, ty vypadni!}
{304}{}{Dobøe, pùjdu.}
{306}{laura67}{Uh... nejsem si tím jistá. Jdi se zeptat Nicole.}
{308}{laura67a}{Nejsem si tím jistá. Jdi se zeptat veleknìze.}
{309}{}{No, jak jsem øíkala... }
{310}{}{Øekla jsem...}
{311}{}{No, jak u jsem øíkala pøedtím...}
{312}{}{Jak u jsem øíkala pøedtím...}
{313}{}{No, jsem si docela jistá, e u jsem ti to øíkala, ale...}
{314}{}{Dobøe! U jsem ti to øíkala...}
{315}{}{Ah, ještì jednou? No, øíkala jsem...}
{316}{}{Zase? U jsem to øíkala...}
{317}{}{Ale drahoušku, dost mì to ruší. U ti to prostì nebudu opakovat.}
{318}{}{Ty jsi... Dobøe! Dobøe! Ty jsi hluchı? Poslouchej poøádnì, u to nebudu opakovat!}
{319}{}{Myslím, e to u staèí. U to opakovat nebudu.}
{320}{}{Neposlouchal, co?  To máš blbı, protoe znovu u ti to neøeknu.}
{321}{}{Oh, to jsou strašliví lidé. Radši o nich u nebudu mluvit!}
{322}{}{Nicole ti o nás asi øekla. Snaíme se vštípit nìco dobrého tìmhle tupohlavejm, zabednìnejm násilnickejm parchantùm...
Och, samozøejmì teï nemluvím o tobì.}
{323}{}{No, nevím o kom to mluvíš.}
{324}{}{Ona vede Následovníky. Pìknì drsná enská. Ale vìøím jí.}
{325}{}{Ostatní jsou tak milí. Je to tady pøekrásné. Nìkam náleet, odvádìt dobrou práci...}
{326}{}{Oh, oni jsou jako... nákaza ve svìtì. Spousta jich je odpornıch, ale nìkteøí jsou vtìlené zlo.}
{327}{}{Adytum, není to to mìsto na západ odtud?}
{328}{}{Adytum je trochu na západ odtud. A lidé tam jsou... no trochu paranoidní, tak neèekej nìjaké vøelé pøijetí.}
{329}{}{Oh, on je skvìlı. Vede nás. Musíš si s ním promluvit!}
{330}{}{Káe o míru, osvícení a podobnejch blbinách. Ale je to hajzl. Bez debat.}
{331}{}{Oh, nìjak nevím jak ho popsat. Morpheus nás vede. Jedinì on ti mùe opravdu odpovìdìt na tvé otázky.}
{332}{}{Ó ano, Vùdce, on je bùh pro tyhle bláznivé uctívaèe. Osobnì o jeho boství dost pochybuju. Prostì další hajzl, co se všemi manipuluje.}
{333}{}{Nightkin? Nechápu, o èem to mluvíš.}
{334}{}{Jsou to velké hnusné gorily, slouící Vùdci a Morpheusovi.}
{335}{}{Co?}
{336}{}{Co, nemùeš pøijít na to, e to je Vùdce?}
{337}{}{Je to velké místo v severní èásti Chrámu, kde Morpheus dìlá všechny svoje obøady. Byla jsem tam, je to nádherné!}
{338}{}{Je to v severní èásti Chrámu, sledovala jsem Morpheuse, kdy tam poøádal nìjaké z tìch svıch 'pøedstavení'.}
{339}{}{Oh, tam nemùeš jít. Je to místo Morpheusovıch meditací.}
{340}{}{Tam chodí jenom Morpheus a jeho vyvolení. Nikdo jinı tam ale nesmí!}
{341}{}{Oni u prokázali svou odevzdanost Chrámu. My ostatní se o to zatím snaíme.}
{342}{}{No jasnì, to jsou ty chlapi, co podstoupili muèení a kdoví co ještì. Mají vymyté mozky a udìlají cokoli, co se jim øekne.}
{343}{}{Oni jsou veleknìí.}
{344}{}{Ah, to jsou veleknìí. Co já vím, tak jich je jenom 13, ale nejsem si úplnì jistá.}
{345}{}{To není dùleité.}
{346}{}{To není dùleité.}
{347}{}{Promiò, na to opravdu nemám èas.}
{348}{}{Nemáme èas se o tom bavit.}
{349}{}{Nechápu, proè o tom chceš mluvit.}
{350}{}{Dr se vìci, kámo.}

# added by WG from genchat
{477}{}{Prosím, musíme si pospíšit. Nemáme èas na vykecávání.}
{478}{}{Morpheus je jedinı, kdo má klíè ke dveøím. Teï musím odejít a nahlásit Nicole, co se tady dìje.}
{479}{}{Prosím, musím vypadnout døív, ne zjistí co jsem zaè.}
# added by WG
{480}{}{Morpheus je jedinı, kdo má klíè ke dveøím. U musím jít.}

# Fo1in2
{499}{}{Radši u jdi. Zbytek zvládnu sama.}



#
# Laura Tell-Me-Abouts
#


{1000}{}{Nasledovnici}
{1001}{}{Nicole}
{1002}{}{Katedrala}
{1003}{}{Morpheus}
{1004}{}{Vudce}
{1005}{}{Nightkin}
{1006}{}{Temny)}
{1007}{}{Auditorium}
{1008}{}{Svatyne}
{1009}{}{servitori}
{1010}{}{Rad)}
{1011}{}{Apokalypsa}
{1012}{}{Buh}
{1013}{}{Mutanti}

{1100}{laura74}{Oh, to jsou hrozní lidé. O nich se nebudu bavit!}
{1101}{laura75}{No, nevím o èem to mluvíš.}
{1102}{laura76a}{Ostatní jsou tak milí. Je to tady pøekrásné. Nìkam náleet, odvádìt dobrou práci...}
{1103}{laura78}{Oh, on je skvìlı. Vede nás. Musíš si s ním promluvit!}
{1104}{laura79}{Oh, nìjak nevím, jak ho popsat. Morpheus nás vede. Jedinì on ti mùe opravdu odpovìdìt na tvé otázky.}
{1105}{laura80}{Nightkin? Nechápu, o èem to mluvíš.}
{1106}{laura81}{Co?}
{1107}{laura82}{Je to velké místo v severní èásti Chrámu, kde Morpheus dìlá všechny svoje obøady. Byla jsem tam, je to nádherné!}
{1108}{laura83}{Oh, tam nemùeš jít. Je to místo Morpheusovıch meditací.}
{1109}{laura84}{Oni u prokázali svou odevzdanost chrámu. My ostatní se o to zatím snaíme.}
{1110}{laura85}{Oni jsou veleknìí.}
{1111}{laura74}{Oh, to jsou hrozní lidé. O nich se nebudu bavit!}
{1112}{laura81}{Co?}
{1113}{laura80}{Nightkin? Nechápu, o èem to mluvíš.}
