{100}{}{Vidíš rolníka.}
{101}{}{Oh, heh, velkej chlap utíká pøed hroznym psem. Phile, tys mu to nandal. Jasnì, nandal.}
{102}{}{Copak to dìláš, Phile? Myslíš, že jsou nebezpeèní, tihle lidi?}
{103}{}{Teda, ten pes vypadá hladovì. Ten tì urèitì chce sežrat zaživa, Phile.}
{104}{}{To je trochu moc na takové malé, bezbranné zvíøátko, že jo Phile?}
{105}{}{To je ale pìknej èokl.}
{106}{}{Myslím, že by Phil uvítal, kdybys ho jeho psa zbavil.}
{107}{}{Dík, že jste to vyøídil s tím psem.}
{108}{}{Vidíš Lenore.}
