{100}{}{Vidíš Lyleho.}
{101}{}{Tak ty jsi ten zlodìj vody! Zrádèe!}
{102}{}{Jsem tak rád, že to už je za námi. Díky.}
{103}{}{A hele, }
{104}{}{.}
{105}{}{Zdravím tì, Lyle. Jak se daøí?}
{106}{}{Zatím dobøe, ale doufám, že se ti podaøí najít ten èip brzo. Už nám moc èasu nezbývá.}
{107}{}{Wahnnnngh!}
{108}{}{Nic moc. Od té doby, co mi nedávno nìkdo ukradl mùj vodní pøídìl, tak to jde všechno z kopce. Všichni jsou vystrašení a neví, co dìlat.}
{109}{}{Je to bída. Doufám, že to zas nìkdy bude lepší.}
{110}{}{Podívám se a uvidím, co se dá dìlat.}
{111}{}{Jo, to taky doufám.}
{112}{}{Díky. Vìøím, že se ti to podaøí vyøešit. A prosím tì, pospìš si s tím novým vodním èipem. Všechen ten zmatek vùbec nemusel nastat, kdybychom mìli náhradní èip!}
{113}{}{Díky ti, že jsi chytil toho zlodìje. Vedeš si dobøe. Ale, prosím tì, pospìš si s tím èipem, nebo už nebude záležet na nièem!}
{114}{}{Jak jsi nás mohl takhle zradit? Vypadni!}
