{100}{}{Vidíš ghoulího správce.}
# the examine & look msgs are 200 & 201
{101}{}{Co tady hledáš?}
{102}{}{Hledám pozùstatky budoucí minulosti.}
{103}{}{Jsem badatel.}
{104}{}{Co je ti po tom, ty èervoksichte?}
{105}{}{Dug-duh.}
{106}{}{Co øíkáš?}
{107}{}{Nic.}
{108}{}{Hledám zapomenuté technologie.}
{109}{}{Myslel jsem si, že to øekneš. Vypadni z mého domu.}
{110}{}{Och, nic takového tady. Možná u ten kostel nebo u to vodní místo. Jít tam.}
{111}{}{Grr! Nebudeš se hrabat v nièem, co je moje. Zmiz! Mluvím vážnì.}
{112}{}{Takle nemluvit o má tváø. Nebo ti ukázat.}
{113}{}{Och, ano.}
{114}{}{Stáhnout ti kùže z ksicht a tobì ukázat ji . . .}
{115}{}{Ack! OK, Uznávám. Odcházím.}
{116}{}{Nejsi velká mutant, aby mì velet. Vzít ty si nìco tady a strèit si to do pták!}
{117}{}{Ne mluvit chci s ty.}
{118}{}{Co jsi zaè?}
{119}{}{Jsem ghúl. Ještì si nikdy žádného nevidìl?}
{120}{}{Ano.}
{121}{}{Ne.}
{122}{}{Ty muset s ta teploušský podzemák. Nechali život tobì, aby otravoval jsi mùj život. Teï pryè z mùj dùm.}
{123}{}{Tak teï jsi to pøehnal. A vypal z mého domu!}
#
# by Sduibek for Fallout Fixt:
#
{200}{}{Zdá se být majitelem této budovy. Je jako ztìlesnìní fráze "pod novým vedením".}
{201}{}{Vidíš: Managera hotelu.}
