{100}{}{Vidíš doktora Soloneho.}
{101}{}{Vidíš sestru Marney.}
{102}{}{Vidíš doktora.}
{103}{}{Vidíš sestru.}
{104}{}{Vítejte. Jak vám mùžu pomoci?}
{105}{}{Hurrgh.}
{106}{}{Jsem zranìnej. Mùžete mì dát do poøádku?}
{107}{}{Mùžete mì nauèit nìco o medicínì?}
{108}{}{Ano, vidím, že jste zranìný. Tohle mùže vyžadovat nìjaký èas. Chcete, abych vás ošetøil?}
{109}{}{Uh huh.}
{110}{}{Nuh uh.}
{111}{}{Ano, prosím.}
{112}{}{Ne, dìkuju.}
{113}{}{Tady máte. Tohle by vám mohlo pomoci. A pøíštì si dávejte tam venku vìtší pozor.}
{114}{}{V tom jste dobrej. Poradíte mi, jak se zachovat v pøípadì šoku?}
{115}{}{Okay. Dìkuju.}
{116}{}{Mùžu vás nìco nauèit. Ale bude to vyžadovat nìkolik hodin. Jste ochotný tady zùstat?}
{117}{}{Jo.}
{118}{}{Promiòte, pospíchám.}
{119}{}{Jste velmi dobrý student. Doufám, že zùstanete na naší stranì. Nashledanou.}
{120}{}{Jak si pøejete. Mnoho štìstí tam venku.}
{121}{}{Mùžu vás nìco nauèit, ale ne mnoho. Nebude to ale za chvilku. Jste ochotný tady zùstat?}
{122}{}{Jo.}
{123}{}{Promiòte, ale nemám èas.}
{124}{}{Jste výborný student. Mnoho štìstí.}
{125}{}{Teï nic. Ale pøesto díky.}
