{100}{}{Vidíš Mathiu.}
{101}{}{Ahoj, Zasvìcený. Tak ty jsi ten, co došel do Starého Øádu a vrátil se živý.}
{102}{}{Coo?}
{103}{}{A kdo jsi ty?}
{104}{}{Promiò, to byl omyl. Sbohem.}
{105}{}{Jmenuji se Mathia. Oficiálnì jsem Maxsonova asistentka, ale jsem taky proto, abych zajistila, že si se staøíkem nikdo nebude zahrávat.}
{106}{}{Staøík? To zní trochu neuctivì.}
{107}{}{Co dìlá taková Maxsonova asistentka?}
{108}{}{Prima pokec. Sbohem.}
{109}{}{Ne, ne, ne tak docela. Je to dobrák. (žertovnì) Krom toho, Nemùžu ho pomlouvat, když stojí vedle mì.}
{110}{}{Tak, co je tedy tvoje náplò práce?}
{111}{}{Sbohem.}
{112}{}{Mám na starosti skoro všechno papírování. Jeho by ta úøednièina zabila. Taky vydávám zbranì Bratrùm, tedy pokud Maxson podepíše schvalovací protokol.}
{113}{}{Ok, díky za informace.}
{114}{}{Nepochopím, jak mohl idiot tvého kalibru pøežít cestu do Starého Øádu. Padej.}
{115}{}{Ahoj, Zasvìcený. Jak ti mùžu pomoct?}
{116}{}{Coo?}
{117}{}{Promiò, zapomnìl jsem tvoje jméno.}
{118}{}{Promiò, to byl omyl. Sbohem.}
{119}{}{Dobrá, pojïme. (Bere tì za rameno)}
{120}{}{Uh huh.}
{121}{}{Uh uh.}
{122}{}{Dobøe, dobøe. Už jdu.}
{123}{}{Jdi vode mì, sakra. Nikam nejdu.}
{124}{}{Ok. Maxson podepsal vydání zbranì pro tvou osobu. Kterou si vezmeš?}
{125}{}{Coo?}
{126}{}{Odstøelovaèskou pušku.}
{127}{}{Raketomet.}
{128}{}{Laserovou pistoli.}
{129}{}{Tvrdou pìst.}
{130}{}{Boxer.}
{131}{}{Tady to máš. Jsem ráda, že jsi na naší stranì, Zasvìcený.}
{132}{}{Starší svolali schùzi. Chtìjí se s tebou setkat v konferenèní místnosti, a to hned.}
{133}{}{Kde je konferenèní místnost?}
{134}{}{Ok, díky.}
{135}{}{V tomto patøe. V severovýchodní èásti, pøímo za snìmovnou.}

# Fo1in2
{136}{}{Magneto-laserová pistole.}
{137}{}{Mega-Energo pìst.}
{138}{}{Superkladivo.}

{139}{}{Nemohl bych radìji dostat Energo zbroj?}
{140}{}{Obávám se, že to není možné.}
{141}{}{Nemohla by jsi mi radìji zaøídit ještì jednu Energozbroj pro mého spoleèníka?}
{142}{}{Nezvyklá prosba. Ale už ses døív osvìdèil, tak budiž.}
