{100}{}{Vidíš generála Maxsona.}
{101}{}{Co je to Bratrstvo ve skuteènosti?}
{102}{}{Vsadím se, že o historii Bratrstva víš skoro všechno.}
{103}{}{Slyšel jsi nìjaký dobrý fámy?}
{104}{}{Mám tady jednu dùležitou informaci.}
{105}{}{To je všechno. Díky.}
{106}{Gen_1}{Nazdar, mladíèku. Cabbot øíkal, že si chceš popovídat. Hele já jsem, uch... Jsem teï dost zaneprázdnìný, takže, uch... Budu se s tebou bavit tak dlouho, dokud nezaèneš pøíliš mlít pantem. Víš, cizinci jsou vìtšinou takoví, nikdy nezavøou pusu... Hehehe. Nìco jako já, co?}
{107}{}{Cizinci? Co tím myslíš?}
{108}{}{A co takhle pár otázek?}
{109}{Gen_2}{Nemùžu. Jenom zmíròuji tyhle proklaté nekoneèné mítinky. Víš, jsou tu ètyøi Starší a já. Uklidòuji sváry a pøi nerozhodných volbách je mùj hlas rozhodující. Ale když se všichni ètyøi rozhodnou, že se budeme dloubat v nosech, zatímco se na nás valí cizí armáda, já s tím nemùžu vùbec nic udìlat.}
{110}{}{Aha, jasnì.}
{111}{}{To smrdí. Proè nìco nedìláš?}
{112}{Gen_2a}{Tradice. Je tìžké zmìnit zabìhané zpùsoby. Možná kdyby Starší mìli poøádné informace, otevøeli by svoje zabednìné palice a zaèali nìco dìlat.}
{113}{Gen_3}{Zasvìcený, který se nenarodil tady... Jsi první cizinec, kterého jsme pøijali do svých øad po hroznì dlouhé dobì. No, skoro po dvaceti letech. }
{114}{}{Proè zrovna mì?}
{115}{}{Jsem polichocen. Co takhle pár otázek?}
{116}{Gen_4}{Protože už sakra musíme nìco dìlat. Armáda se formuje, karavany z Hubu mizí a naši zvìdové zatracenì nezvládají odvádìt svou práci... Takže se starší projednou rozhoupali a usoudili, že ten správnej cizinec by mohl mít co nabídnout. A ten cizinec jsi ty... doufáme.}
{117}{}{Jaké armády?}
{118}{}{Co je s tìmi karavanami?}
{119}{}{Hmm. Myslím, že bych se mìl nejdøív ještì na nìco zeptat.}
{120}{}{Co máte za problém se zvìdy?}
{121}{}{Mám nìjaké informace, které by se mohly hodit.}
{122}{Gen_5}{Když jsme se dozvìdìli o mizejících karavanách, poslali jsme pár zvìdù na sever a na východ. Ti ze severu se už nikdy nevrátili. Jeden se vrátil z východu a mluvil o bandì divnejch stvoøení – samej sval a s planoucíma oèima. Starší na to sice úplnì dlabou, ale já se pøipravuju i tak.}
{123}{}{Dvacet, to není armáda. Proè se bojíte?}
{124}{}{Zdá se, že váš hoch byl pøíliš dlouho na sluníèku.}
{125}{}{Udìlám, co budu moci.}
{126}{}{Øekl, kde pøesnì na východì?}
{127}{}{Mám nìjaké informace, které by se mohly hodit.}
{128}{Gen_6}{Mohou nebo nemusejí to být dobøí zvìdové. Ale nepochybuj o pravdomluvnosti mých mužù. Tvùj status Zasvìceného mùžeme kdykoli zrušit.}
{129}{}{Vypadá to, že mì potøebujete víc, než já vás.}
{130}{}{Omlouvám se.}
{131}{Gen_7}{Tak jo. Varoval jsem Starší pøed problémy, které pøinesou cizinci. [stranou zakøièí] Stráže! Je tu jeden Zasvìcený, který potøebuje trochu èasu, aby se nauèil správným zpùsobùm.}
{132}{Gen_8}{Jsi cizinec, ale pøedpokládám, že se nauèíš našim zpùsobùm. Budu tì sledovat. Teï se ptej. }
{133}{Gen_9}{Dobøe. Ještì nìjaké otázky? }
{134}{Gen_10}{Hluboko v horách. Nemohl to upøesnit.}
{135}{}{To je zlé. Mohu se ještì ptát?}
{136}{}{A co na severu?}
{137}{}{Pokraèuj. }
{138}{Gen_11a}{Jo, vodpal.}
{139}{Gen_11b}{Jistì.}
{140}{Gen_11c}{Støílej.}
{141}{Gen_12}{Mám takový pocit, že na východì je jen malá skupina, zatímco na severu se skrývají hlavní síly. Starší mají svázané ruce, protože ze severu se nikdo nevrátil. Nemùžu dìlat nic jiného, než pøihlížet.}
{142}{}{Udìlám, co bude v mých silách.}
{143}{}{Proè nìco neudìláš?}
{144}{}{Myslím, že to je na mì trochu moc. Nepoèítej se mnou.}
{145}{}{O tom nìco vím.}
{146}{Gen_13}{No, kupci z Hubu nás upozornili na mizení karavan, které putovaly na sever. Myslím, že v horách se skrývá armáda, ale Starší nechtìjí nic podniknout, dokud nebudou mít jistotu. }
{147}{}{Kde pøesnì došlo k tìm zmizením?}
{148}{}{Nejsi snad vrchní staøešina? Proè nìco neudìláš?}
{149}{}{Udìlal jsi nìco?}
{150}{}{Mám nìjaké informace, které by se mohly hodit.}
{151}{Gen_14}{Co jsem slyšel, karavany zmizely u jižního výbìžku hor na východì. Obchodníci v Hubu by ti jistì øekli více.}
{152}{}{Díky. Pokud to nevadí, ještì bych mìl otázku.}
{153}{}{Díky. Promluvíme si pozdìji.}
{154}{}{Mám nìjaké informace, které by se mohly hodit.}
{155}{Gen_15g}{Ještì se uvidíme, Zasvìcený. Nejsi tak špatný... na cizince.}
{156}{Gen_15n}{Sbohem, Zasvìcený.}
{157}{Gen_15b}{Sbohem!}
{158}{Gen_16}{Vyrostl jsem tu v pøílišné izolaci. Dovedeš si pøedstavit strávit celý život v tak malém uzavøeném prostoru, a pak být nucen vyjít ven do vnìjšího svìta? }
{159}{}{No, po pravdì øeèeno...}
{160}{}{Zdá se, že mi bylo pøedurèeno být vaším zvìdem.}
{161}{}{Takže protože nezvedli zadky, já mám udìlat tu špinavou práci. Zapomeò na to.}
{162}{Gen_17}{Pak tomu problému rozumíš. Abychom pøežili, potøebujeme nìkoho se znalostí vnìjšího svìta. Nìkoho jako ty. }
{163}{}{Dobøe, udìlám to.}
{164}{}{Mám své vlastní problémy. Vzdávám to.}
{165}{Gen_18}{Hmm... s tím, co se podle mì chystá, nemáme èas na nìkoho, kdo by nebyl... schopen pøispìt. Takže, buï s námi budeš spolupracovat, nebo mùžeš vyrazit svou cestou.}
{166}{}{No, když to stavíš takhle, jdu do toho.}
{167}{}{Vypadá to, že dneska je hezký den na procházku...}
{168}{Gen_19}{Je to tvoje volba. Snad s tím dokážeš žít. }
{169}{Gen_20}{Co? To je to, proè tu jsme a pro co žijeme. Ideály. Až s námi strávíš více èasu, snad porozumíš.}
{170}{}{Jo, ale co vlastnì dìláte?}
{171}{}{Nejsem si tím pøíliš jistý.}
{172}{Gen_21}{Naším hlavním cílem je pøežití. Písaøi kopírují staré plány zbraní, pøípadnì navrhují nové. A Rytíøi pak podle plánù zbranì vyrábìjí. Vìtšina zbraní pochází od nás.}
{173}{}{Prodáváte zbranì do Hubu?}
{174}{}{To je všechno, co dìláte?}
{175}{}{To dává smysl. Ještì se musím na pár vìcí zeptat.}
{176}{Gen_22}{Tak získáváme naše zásoby.}
{177}{}{OK, chápu. Ještì se musím na pár vìcí zeptat.}
{178}{}{OK, no, musím už jít.}
{179}{}{No, moc o tom pøesvìdèený nejsem.}
{180}{Gen_23}{Všechno? Je to sakra dùležitý. Pro naše pøežití je to rozhodující.}
{181}{}{No jasnì. Ještì se musím na pár vìcí zeptat.}
{182}{}{Jo, hmm, to je pitomost.}
{183}{}{Fajn, díky. Radìji bych mìl opravdu jít.}
{184}{Gen_26}{Pak si musíš být jistý. Protože být nejistý znamená brzy zemøít.}
{185}{}{Èím víc vím, tím si budu jistìjší.}
{186}{Gen_28}{Na tak dlouhé povídání teï nemám èas. Tumáš. Všichni jsme s tím vyrostli. }
{187}{Gen_29n}{Jsou tu zvìsti o mizejících karavanách z Hubu, stejnì jako o podivné armádì chystající se ve východních horách. }
{188}{}{Fajn.}
{189}{}{Jaká armáda?}
{190}{}{Co je s tìmi mizejícími karavanami?}
{191}{}{O tom nìco vím.}
{192}{Gen_29b}{Já na klevety nedám.}
{193}{Gen_30}{Ach... Rád tì zase vidím, Zasvìcený. Jde ti to dobøe?}
{194}{}{Docela jo. Mohu se na nìco zeptat?}
{195}{}{Abych øekl pravdu, je to pìknì v hajzlu.}
{196}{}{Ano, díky. Musím už jít.}
{197}{Gen_32}{Je mi líto, že nejsme takoví, jak jsi èekal, ale mohl bys ukázat trochu sebeovládání. }
{198}{}{Omlouvám se. Mùžu se na nìco zeptat?}
{199}{}{Proè? Je tohle místo vtip?}
{200}{}{Musím už jít. Sbohem.}
{201}{Gen_34}{Co chceš tentokrát, sakra? }
{202}{}{Chtìl bych vìdìt, proè tomu tady velí idiot.}
{203}{}{Chtìl bych se na nìco zeptat.}
{204}{}{Nic, díky.}
{205}{Gen_35}{Co máš? }
{206}{}{No, vlastnì nic.}
{207}{}{Karavany z Hubu jsou pøepadány obøími zelenými mutanty. Dokonce se jich shromažïuje celá armáda.}
{208}{}{Na severu je velká armáda øízená nìkým, kdo si øíká Vùdce.}
{209}{Gen_36}{Ty jsi je vidìl? To by mohlo koneènì Starší rozhoupat k èinùm. O to už se postarám, díky!}
{210}{Gen_38}{Uf... Co plánuje s tou... svojí armádou?}
{211}{}{Plánuje zmocnit se Bratrstva, Hubu, Junktownu... všeho a všech.}
{212}{}{Kolik za takovou informaci zaplatíš?}
{213}{Gen_39}{Koneènì! Tohle by mohlo Starším zvednout zadky. Opevníme naši Základnu a pøipravíme tìm proklatým mutantùm nepøíjemné pøivítání.}
{214}{}{Ne! Ty to nechápeš. Oni mìní lidi na mutanty a budují z nich tu svou armádu.}
{215}{}{Fajn.}
{216}{Gen_40}{Takže?}
{217}{}{Takže až sem dorazí, už je nic nezastaví. Mají stejnì dokonalé zbranì jako vy. Nebudete mít šanci.}
{218}{}{Hmm, dobrá. Možná, že nejlepší bude se tu opevnit.}
{219}{Gen_41}{Tak co jiného navrhuješ ty?}
{220}{}{Pomozte mi pøi útoku na Vùdcovu základnu. Vím už, kde je.}
{221}{Gen_42}{Hmmm. To není špatný plán. Zkusím to prosadit u Starších. Nic neslibuji, ale budu se snažit.}
{222}{Gen_43}{Pak tedy zmiz. Mám práci.}
{223}{Gen_44}{Máš docela zajímavý žebøíèek priorit a loajality.}
{224}{}{Jsem loajální k sobì. 500 babek, ber nebo nech být.}
{225}{}{Och... ano. Øeknu ti to. Plánuje ovládnout všechny a všechno.}
{226}{Gen_44a}{Beru. Potøebujeme ty informace k záchranì životù.}
{227}{}{Velmi snadné. Mìní lidi na mutanty a má dokonalé zbranì. Plánuje se zmocnit svìta.}
{228}{Gen_44b}{Hmm, pokud je to tak, pøeju ti, abys našel místo, kde si ty peníze užiješ.}
{229}{Gen_45}{Hmm, co takhle nic. Stráže, vykopejte toho blázna ven. Mùj Bože! Ubráníme Bratrstvo i bez tvé podìlané pomoci.}
{230}{Gen_46}{Co si myslíš, že dìláš? Dej to pryè. Dej to pryè!}
{231}{Gen_47}{Takhle je to. Stráže! Vyhoïte toho idiota!}
{232}{Gen_48}{Hej, hej, hej, hej! Brzdi. Nech toho. Nech toho hned!}
{233}{Gen_49}{Jak jsem øekl...}
{234}{Gen_50}{Øekl jsem...}
{235}{Gen_51}{Nemám ve zvyku opakovat se. Nastraž uši.}
{236}{Gen_52}{Podívej, už jsem ti to øekl. Není moje chyba, že jsi to neslyšel.}
{237}{Gen_52a}{Jsi tady. Pokud chceš delší verzi, promluv si s Vree.}
{238}{Gen_52b}{Mathia je moje asistentka.}
{239}{Gen_53}{Och, je to hodné dítì. I když chce být Písaøem.}
{240}{Gen_54}{Vree je vrchní písaøka. Vìtšinou je v knihovnì, vždycky si ráda popovídá.}
{241}{Gen_55}{Tam je uložena naše historie a specifikace zbraní.}
{242}{Gen_56}{Rhombus je tu už dlouho. Je trochu strohý, ale je to nejlepší voják pod sluncem.}
{243}{Gen_58}{Hehehe. Pøátelský, milý a bezúhonný èlovìk. Vrchní staøešina øídí debaty mezi ostatními Staršími. Víš, pøed dvìma lety mì k té funkci pøemluvili. Kdybych býval vìdìl...}
{244}{Gen_59}{No, jsou tady ètyøi, a to je všechno, na èem se dokážou usnést. Nedokážou se ani shodnout, jestli se jim chce moèit, natož jestli se pøi tom má zvedat prkýnko.}
{245}{Gen_60}{No, to jseš ty. Zasvìcení studují a trénují, aby se z nich stali Rytíøi nebo Písaøi.}
{246}{Gen_61}{Písaøi zapisují zbraòové specifikace. Schraòujeme informace už od dob mého dìda. Nìkdy pøijde Písaø s návrhem nové zbranì. Hehehe. Ne moc èasto. Všichni jsou podøízeni Vree.}
{247}{Gen_62}{Rytíøi vyrábìjí zbranì. Pokud je Rytíø velmi dobrý, mùže se stát Paladinem a potom Starším. V souèasné dobì je hlavou všech Rytíøù Rhombus.}
{248}{Gen_63}{Paladini mají na starost veškerou naši bezpeènost, tady i operace venku. Pamatuji se na dobu, kdy jsme obchodovali s Hubem, podnikali výzvìdy pro Starší. Ach, to byly doby.}
{249}{Gen_64}{Hub je smìrem na jihovýchod. Mìníme s nimi naše zbranì za jídlo a jiné zboží. Pokud Hub nìkdy navštívíš, promluv si s Butchem Harrisem.}
{250}{Gen_65}{Butch je šéfem Obchodníkù Far Go. Je trochu úlisný, ale není úplnì zpustlý. Ne jako ti Obchodníci s vodou. To je parta hnusných supù, všichni do jednoho.}
{251}{Gen_66}{S tìmi obchodujeme nejvíc. Nejsou úplnì dùvìryhodní, ale poøád mnohem lepší než ti ostatní. }
{252}{Gen_67}{Nemùžeš jim vìøit. Pøed pár lety nám nabídli nìjakou vodu za hromadu zbraní. Øekli jsme ne, a víš, co udìlali? Poslali sem zlodìje, aby ty zbranì ukradli! Chytili jsme je, ale Starší zamítli vyrazit do Hubu dát tìm obchodníkùm lekci.}
{253}{Gen_68}{Holodisky? Hmm? Nevidìl jsem je už nìjaký èas.}
{254}{Gen_69}{Vree to má nìkde v knihovnì.}
{255}{Gen_70}{Roger Maxson jo? Dovedl sem naše lidi v létech Velkého Exodu a z trosek vytvoøil Bratrstvo. Opravdový vùdce.}
{256}{Gen_71}{To bylo v dobách, kdy mùj dìd Roger Maxson vedl své vojáky a založil Bratrstvo. Nikdy se nezmínil, odkud pøišli, ale na tom vážnì nezáleží... teï je náš domov tady.}
{257}{Gen_72}{Tuším, že se na severu a ve východních horách sbírá armáda, ale nemám možnost to dokázat. Starší o tom nechtìjí ani slyšet. }
{258}{Gen_73}{Parta náboženských pomatencù, tak to vidím já. Myslím, že mají hlavní kostel nìkde v Kostnici.}
{259}{Gen_75}{No, moc toho nevím. Je tam nìkolik gangù, pak taky Adytum a Dìti katedrály. Nic moc víc. Je to dost znièené.}
{260}{Gen_76}{Není toho moc, co øíct. V žádném jsem nikdy nebyl. Slyšel jsem, že pùsobí mnoho problémù obyvatelùm Adyta.}
{261}{Gen_77}{To je malé sídlo v Kostnici. Byl jsem tam...och tak dávno. Na nìjaké výzvìdné misi pro Starší.}
{262}{Gen_78}{Och. To je další trapná kleveta. Nìkdo tvrdí, že je to obøí pøíšera s tesáky, jiní tvrdí, že je to upír.}
{263}{Gen_79}{Och, o tom vùbec nic nevím.}
{264}{Gen_80}{Co to? Ne. Neslyšel jsem o tom.}
{265}{Gen_81a}{Sakra, nemám ani páru.}
{266}{}{Pøekvapenej, že mì vidíš? To jsem ti mìl jako nechat všechnu tu zábavu?}
{267}{}{Jak jsi dokázal pøesvìdèit Starší?}
{268}{Gen_82a}{Nakonec to nebylo tak tìžké. Jen jsem v klidu popsal situaci a bylo to. A je to tu. Do boje, pøíteli.}
{269}{Gen_83}{Co tady dìláš. Tohle je jen pro Starší.}
{270}{}{Pardon, jsem na odchodu.}
{271}{}{To je mi jedno, zùstávám.}
{272}{Gen_84}{Dobøe, tak koukej zavøít dveøe z druhé strany.}
{273}{Gen_84a}{Øíkám ti, nepøekážej.}
{274}{Gen_85}{Ha! Zapomnìl jsi. Uèíval jsem to.}
{275}{Gen_86}{Oproti mínìní, nechceme vùbec vojáky bez mozku.}
{276}{Gen_87}{Hmm, navrhuji, abys to probral s mou asistentkou Mathiou.}


# Alchemist: I'm not sure about exact naming of the Weapon Store. Check this place.
{278}{}{Výbornì! Vzhledem k úspìšnì dokonèené misi ti udìluji pøístup ke skladu zbraní na první úrovni. Nìjaké další otázky? }
{300}{}{Možná mi to øekneš ty? Všichni tu vypadají nabroušení. Vypadá to, jako byste se chystali do války, ale nikdo neví proti komu.}
{301}{}{Nemáš tušení, co by se mohlo skrývat za mizením karavan?}
{302}{}{Prozkoumám oblast na severu a po návratu podám hlášení.}
{303}{}{Za 500 zátìk zjistím, o co tam jde.}
{304}{}{Za 1000 zátìk zjistím, o co jde na severu.}
{305}{}{Nejsem si jistý, jestli mám zájem.}
{306}{}{Mohl bych získat nìjaké lepší zbranì?}
{307}{}{Nejdøív pár otázek.}
{308}{}{Ne. Uvidíme se, až zjistím, o co tam bìží.}
{309}{}{OK, sbohem.}
{310}{}{Jak víš, že zvìdové prostì nedezertovali?}
{311}{}{Myslím, že už jsem se s takovými potvorami setkal. Nedají se snadno dostat.}
{312}{}{Prosím, odpust mi. Co je, myslíš, za tìmi zmizeními?}
{313}{}{Tak jo. Zruš ho. Uvidíme, co to se mnou udìlá.}
{314}{}{Promiò, ale bylo to pro mì pøíliš riskantní vyrazit tam teï.}
{315}{}{Dobrá, pùjdu, ale nemohl bych dostat nìjaké lepší zbranì?}
{316}{}{Dobøe, udìlám to za 1000.}
{317}{}{Ber nebo nech bejt.}
{318}{}{Tak nic.}
{319}{}{Dobøe, dobøe, udìlám to zadarmo.}
{320}{}{Výbornì, zastavím se, až se vrátím.}
{321}{}{Mám dùkaz, že v mizení karavan má prsty armáda. Armáda mutantù. Je to vážný dùvod ke znepokojení. Jsou hroziví.}
{322}{}{Je zøejmé, že nìkdo by to mìl tam venku prozkoumat.}
{323}{}{Když už mì tam ven posíláte nasazovat krk, chtìlo by to víc, než jen „pocit“.}
{324}{}{Shledávám svùj život pomìrnì dùležitou prioritou.}
{325}{}{Nemyslím, že jsem na tento úkol pøipraven.}
{326}{}{Jsem loajální pouze jediné osobì.}
{327}{}{Mohu.}
{328}{}{Ehe?}
{329}{}{Proè jsou všichni ve stresu? Zdá se, že se chystáte do války, ale nikdo neví proti komu.}
{330}{}{Potøebuju si promluvit o mizejících karavanách. Máš k tomu nìco?}
{331}{}{No nic.}
{332}{}{Potøebuju se na nìco zeptat.}
{333}{}{Ehe?}
{334}{}{Mám nìjaké zprávy ze severu.}
{335}{}{Mohu se na nìco zeptat?}
{336}{}{Hmm.}
{337}{}{Pardon, vlastnì nic nemám.}
{338}{}{Vidìl jsem jejich základnu. Je plná mutantù.}
{339}{}{Vidìl jsem jejich základnu na severu. Následují nìkoho, kdo si øíká Vùdce.}
{340}{}{S tìmihle to nemùžeš hrát na obranu, Maxsone.}
{341}{}{Je zøejmé, že je tøeba nìco udìlat. Nejlépe by bylo zaútoèit na mutanty døív, než oni na nás. Budeme ale potøebovat podporu Starších.}
{342}{}{Nejsem si jistý, co bychom teï mìli udìlat. Shromáždím pár informací, a pak se sem vrátím.}
{343}{}{Chce se zmocnit všech známých lidských sídel.}
{344}{}{Co mi mùžeš øíct o historii Bratrstva?}
{345}{}{Jaký je hlavní zámìr Bratrstva?}
{346}{}{Kdo jsou to Starší?}
{347}{}{Víš nìco o Páraèi?}
{348}{}{No nic.}
{349}{}{Mohu se ještì na nìco zeptat?}
{350}{}{Díky.}
{351}{}{Získal jsi }
{352}{}{ bodù zkušenosti za prùzkum severní oblasti.}

#
# TRANSLATION NOTE: The following groups of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ('my friend' will be masculine); the second line is
# for the case of the player-character feminine ('my friend' will be feminine).
#

{353}{Gen_3}{Zasvìcený, který se nenarodil tady. Jsi první cizinec, kterého jsme pøijali do svých øad po hroznì dlouhé dobì. No, skoro po dvaceti letech. }
{354}{Gen_3}{Zasvìcený, který se nenarodil tady. Jsi první cizinec, kterého jsme pøijali do svých øad po hroznì dlouhé dobì. No, skoro po dvaceti letech. }
{355}{Gen_6}{Mohou nebo nemusejí to být dobøí zvìdové. Ale nepochybuj o pravdomluvnosti mých mužù. Mùžeme kdykoli zrušit tvùj status Zasvìceného.}
{356}{Gen_6}{Mohou nebo nemusejí to být dobøí zvìdové. Ale nepochybuj o pravdomluvnosti mých mužù. Mùžeme kdykoli zrušit tvùj status Zasvìceného.}
{357}{Gen_15n}{Sbohem, Zasvìcený.}
{358}{Gen_15n}{Sbohem, Zasvìcený.}
{359}{Gen_30}{Ach... Rád tì zase vidím, Zasvìcený. Jde to dobøe?}
{360}{Gen_30}{Ach... Rád tì zase vidím, Zasvìcený. Jde to dobøe?}

{400}{}{Navštívil jsem Základnu mutantù na severu. Øeknìme, že už pro nikoho nejsou žádnou hrozbou.}


# General Maxson Tell-Me-Abouts generic responses
{980}{Gen_79}{Och, o tom nic nevím.}
{981}{Gen_80}{Co to? Ne. O tom jsem nic neslyšel.}
{982}{Gen_81a}{Sakra, nemám ani páru.}

#
# General Maxson Tell-Me-Abouts
#


{1000}{}{bratrstvo}
{1001}{}{Mathia}
{1002}{}{Cabbot}
{1003}{}{Vree}
{1004}{}{knihovna}
{1005}{}{Rhombus}
{1006}{}{starsi}
{1007}{}{staresinove}
{1008}{}{zasveceni}
{1009}{}{pisari}
{1010}{}{rytiri}
{1011}{}{Paladinove}
{1012}{}{Hub}
{1013}{}{Butch}
{1014}{}{Traders}
{1015}{}{kupci}
{1016}{}{Disky}
{1017}{}{prehravac}
{1018}{}{Roger}
{1019}{}{Exodus}
{1020}{}{armada}
{1021}{}{katedrala}
{1022}{}{andelske}
{1023}{}{Gangy}
{1024}{}{Adytum}
{1025}{}{parac}
{1026}{}{Harris}
{1027}{}{Maxson}
{1028}{}{andel}
{1029}{}{Boneyard|Kostnice}
{1030}{}{Vudce}
{1031}{}{valka}
{1032}{}{karavany}
{1033}{}{cip}

{1100}{Gen_52a}{Jsi tady. Pokud chceš delší verzi, promluv si s Vree.}
{1101}{Gen_52b}{Mathia je moje asistentka.}
{1102}{Gen_53}{Och, je to hodné dítì. I když chce být Písaøem.}
{1103}{Gen_54}{Vree je vrchní písaøka. Vìtšinou je v knihovnì, vždycky si ráda popovídá.}
{1104}{Gen_55}{Tam je uložena naše historie a specifikace zbraní.}
{1105}{Gen_56}{Rhombus je tu už dlouho. Je trochu strohý, ale je to nejlepší voják pod sluncem.}
{1106}{Gen_58}{Hehehe. Pøátelský, milý a bezúhonný èlovìk. Vrchní staøešina øídí debaty mezi ostatními Staršími. Víš, pøed dvìma lety mì k té funkci pøemluvili. Kdybych býval vìdìl...}
{1107}{Gen_59}{No, jsou tady ètyøi a to je všechno, na èem se dokážou shodnout. Nedokážou se ani shodnout, jestli se jim chce moèit, natož jestli se pøi tom má zvedat prkýnko.}
{1108}{Gen_60}{No, to jseš ty. Zasvìcení studují a trénují, aby se z nich stali Rytíøi nebo Písaøi.}
{1109}{Gen_61}{Písaøi zapisují zbraòové specifikace. Schraòujeme informace už od dob mého dìda. Nìkdy pøijde Písaø s návrhem nové zbranì. Hehehe. Ne moc èasto. Všichni jsou podøízeni Vree.}
{1110}{Gen_62}{Rytíøi vyrábìjí zbranì. Pokud je Rytíø velmi dobrý, mùže se stát Paladinem a potom Starším. V souèasné dobì je hlavou všech Rytíøù Rhombus.}
{1111}{Gen_63}{Paladini mají na starost veškerou naši bezpeènost a èinnosti venku. Pamatuji se na dobu, kdy jsme obchodovali s Hubem a podnikali výzvìdy pro Starší. Ach, to byly doby.}
{1112}{Gen_64}{Hub je smìrem na jihovýchod. Mìníme s nimi naše zbranì za jídlo a jiné zboží. Pokud Hub nìkdy navštívíš, promluv si s Butchem Harrisem.}
{1113}{Gen_65}{Butch je šéfem Obchodníkù Far Go. Je trochu úlisný, ale není úplnì zpustlý. Ne jako ti Obchodníci s vodou. To je parta hnusných supù, všichni do jednoho.}
{1114}{Gen_66}{S tìmi obchodujeme nejvíc. Nejsou úplnì dùvìryhodní, ale poøád mnohem lepší než ti ostatní. }
{1115}{Gen_67}{Chceš slyšet o Obchodnících s vodou. Hehehe, nemùžeš jim vìøit. Pøed pár lety nám nabídli nìjakou vodu za hromadu zbraní. Øekli jsme ne, a víš, co udìlali? Poslali sem zlodìje, aby ty zbranì ukradli! Chytili jsme je, ale Starší zamítli vyrazit do Hubu dát tìm obchodníkùm lekci.}
{1116}{Gen_68}{Holodisky? Hmm? Nevidìl jsem je už nìjaký èas.}
{1117}{Gen_69}{Vree to má nìkde v Knihovnì.}
{1118}{Gen_70}{Roger Maxson jo? Dovedl sem naše lidi v létech Velkého Exodu a z trosek vytvoøil Bratrstvo. Opravdový vùdce.}
{1119}{Gen_71}{To bylo v dobách, kdy mùj dìd Roger Maxson vedl své vojáky a založil Bratrstvo. Nikdy se nezmínil, odkud pøišli, ale na tom vážnì nezáleží... teï je náš domov tady.}
{1120}{Gen_72}{Tuším, že se na severu a ve východních horách sbírá armáda, ale nemám možnost to dokázat. Starší o tom nechtìjí ani slyšet. }
{1121}{Gen_73}{Parta náboženských pomatencù, tak to vidím já. Myslím, že mají hlavní kostel nìkde v Kostnici.}
{1122}{Gen_75}{No, moc toho nevím. Je tam nìkolik gangù, pak taky Adytum a Dìti katedrály. Nic moc víc. Je to dost znièené.}
{1123}{Gen_76}{Není toho moc, co øíct. V žádném jsem nikdy nebyl. Slyšel jsem, že pùsobí mnoho problémù obyvatelùm Adyta.}
{1124}{Gen_77}{To je malé sídlo v Kostnici. Byl jsem tam... och tak dávno. Na nìjaké výzvìdné misi pro Starší.}
{1125}{Gen_78}{Och. To je další trapná kleveta. Nìkdo tvrdí, že je to obøí pøíšera s tesáky, jiní tvrdí, že je to upír.}
{1126}{Gen_65}{Butch je šéfem Obchodníkù Far Go. Je trochu úlisný, ale není úplnì zpustlý. Ne jako ti Obchodníci s vodou. To je parta hnusných supù, všichni do jednoho.}
{1127}{Gen_70}{Roger Maxson jo? Dovedl sem naše lidi v létech Velkého Exodu a z trosek vytvoøil Bratrstvo. Opravdový vùdce.}
{1128}{Gen_75}{No, moc toho nevím. Je tam nìkolik gangù, pak taky Adytum a Dìti katedrály. Nic moc víc. Je to dost znièené.}
{1129}{Gen_75}{No, moc toho nevím. Je tam nìkolik gangù, pak taky Adytum a Dìti katedrály. Nic moc víc. Je to dost znièené.}
{1130}{Gen_80}{Co to? Ne. O tom jsem nic neslyšel.}
{1131}{Gen_71}{To bylo v dobách, kdy mùj dìd Roger Maxson vedl své vojáky a založil Bratrstvo. Nikdy se nezmínil, odkud pøišli, ale na tom vážnì nezáleží... teï je náš domov tady.}
{1132}{Gen_65}{Butch je šéfem Obchodníkù Far Go. Je trochu úlisný, ale není úplnì zpustlý. Ne jako ti Obchodníci s vodou. To je parta hnusných supù, všichni do jednoho.}
{1133}{Gen_81a}{O tom nic nevím.}
