{100}{}{Co chceš?}
{101}{}{Hej, budeš jíst tu mrtvou krysu?}
{102}{}{Co?}
{103}{}{Vidìl jsi mého psa Elvise? Je nìkde kolem.}
{104}{}{Ahoj.}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Ohlodám ti kosti!}
{108}{}{Smrt! Smrt! Smrt!}
{109}{}{Hej, slyšels, že je po Setovi?}
{110}{}{Set je mrtvej. Set je mrtvej. Set je mrtvej. . .}
{111}{}{Je tam spousta vody pro každého. Set se pøesvìdèil.}
{112}{}{Slyšel sem, že mutanti odešli z mìsta.}
{113}{}{Od té doby, co jsou mutanti pryè, je to lepší. }
{114}{}{Ahoj.}
