{100}{}{Nemùžeš se pøenést pøes to, aby ses hrabal v rozházených zbytcích.}
{101}{}{Lednice je plná zmìti orgánù a jiných èástí lidského tìla.}
{102}{}{Kousky v lednici jsou rozsekány na malé špalíèky a zmrazeny k expedici. Z takto rozsekaných kouskù nemùže nikdo udìlat transplantát.}
{103}{}{Lednici zaplòují èásti lidského tìla.}
{104}{}{Lednice je plná èástí lidského tìla, rozsekaných na malé kousíèky a zamražených do ledových kostek. Podivné.}
