{100}{}{Toto je skuteèná jaderná hlavice.}
{101}{}{Z pøístupového poèítaèe vedou kabely do jaderné hlavice za ním.}
{102}{}{Právì jsi aktivoval jadernou hlavici. Ètyøminutové odpoèítávání zaèíná.}
{103}{}{Právì jsi zajistil jadernou hlavici.}
{104}{}{BUUUUUUUUUUUM! [Právì jsi odpálil atomovou bombu!]}
{105}{}{Nezdá se, že by to fungovalo.}
{106}{}{Odpoèítávání stále bìží... možná bys mìl pøestøihnout ten èervený drát.}
{107}{}{Možná musíš také použít ten klíè.}
{108}{}{Toto je jaderná hlavice. Je ovládána poèítaèem pøipojeným tìmi kabely.}
{109}{}{Na této jaderné hlavici není nic, co by potøebovalo opravit.}
{110}{}{Na této jaderné hlavici není nic, co by se dalo odemknout.}
{111}{}{Tohle je dost velká past, která nemùže být odtud zajištìna nebo odjištìna.}
