{100}{}{Hej ty! Stùj, kde jseš, a zodpovídej se zákonu!}
{101}{}{Díky za novı vodní èip. To opravdu pozvedne morálku a lidé nebudou porušovat zákony Vaultu.}
{102}{}{Rád tì zase vidím. Mohu pro tebe nìco udìlat?}
{103}{}{Co máš za práci?}
{104}{}{Jo, potøeboval bych nìjaké zbranì.}
{105}{}{Proè musejí bıt ve Vaultu zamèené dveøe?}
{106}{}{Hrmh!}
{107}{}{Hmmm. Myslím, e bys mìl bıt nìkde jinde. Pøeju pìknı den.}
{108}{}{Zodpovídám za bezpeènost a dodrování práva ve Vaultu. Moná to nevíš, ale nebıt mì, Vault by nefungoval tak dobøe.}
{109}{}{Hmm. Jasnı. Díky.}
{110}{}{To zní dùleitì.}
{111}{}{A taky je. Bez dodrování zákonù by se Vault brzy promìnil v nebezpeèné místo bez správného vedení. To by mohlo ohrozit bezpeènost nás všech.}
{112}{}{Teï, kdy jsem byl venku, jsou tady nìjaké zákony, které by se vztahovaly pøímo na mì?}
{113}{}{Vidìl jsem venku pár míst, kde lidé strádali právì kvùli chybìjící zákonnosti.}
{114}{}{No, i kdy jsou tam venku zbranì nezbytné, nemanipuluj tady s nimi ádnım zpùsobem, kterı by se dal povaovat za vıhrùku. Jinak si myslím, e tady nic specifického není.}
{115}{}{Díky.}
{116}{}{Víš, vìdìl jsem, e se to mùe stát. To, e lidé dodrují zákon, je jediná monost, jak zachránit Vault pøed bídou a znièením. Pokraèuj ve své zásluné práci.}
{117}{}{Správce mi nepovolil otevøít zbrojnici a vydat ti více zbraní. Je mi líto, ale nemohu ti pomoci.}
{118}{}{Prosím! Vánì je potøebuju!}
{119}{}{Ok. I tak díky.}
{120}{}{Ne. To nemohu.}
{121}{}{Pøeju pìknı den.}
{122}{}{Kvùli tomu, aby se zbranì nedostaly do rukou tìm, kdo k nim nemají mít pøístup.}
{123}{}{A kdo pøístup má?}
{124}{}{To nezní moc fér.}
{125}{}{ivot není fér, nìkdy. Ale náš zákon je. Pøeju pìknı den.}
{126}{}{Správce, já a mùj tım. To je vše.}
{127}{}{Zní to, jako by pøístup mìli jen lidé, kteøí ty zbranì potøebují.}
{128}{}{To je docela krátkı seznam.}
{129}{}{Jo, to je. Musím se vrátit do práce.}
{130}{}{Jo, jen lidé, kteøí je potøebují, mají pøístup.}
{131}{}{No, já tu potøebu mám. Otevøi dveøe, prosím.}
{132}{}{Je mi líto, není to špatnı argument, ale nemohu tì vpustit.}
{133}{}{Hmm. Kdy o tom mluvíš, vypadá to, e máš. Tady, otevøu ti dveøe.}
{134}{}{Á, }
{135}{}{. Co pro tebe mohu udìlat?}
{136}{}{Potøebuju víc zbraní.}
{137}{}{Jsi v poøádku?}
{138}{}{Huh-huh.}
{139}{}{Skvìle. Tvoje inteligence mì ohromuje. U asi nebudu moci myslet.}
{140}{}{Promiò, dostal jsi vše, co jsme mohli dát. Hezkı den.}
{141}{}{Nelíbí se mi tobì podobní. Uøvaná chátra. Mìl by ses stydìt.}
{142}{}{Jo, nápodobnì, skopová hlavo.}
{143}{}{Nemyslíš, e jsi trochu hrubı?}
{144}{}{Dej si pozor na jazyk, nebo tì zatknu pro útok na veøejného èinitele.}
{145}{}{Jo, dobøe. Uvidíme se.}
{146}{}{To je to. Mám u toho dost, jak se ke mì chováš.}
{147}{}{Hmm. Moná. Mìl bych bıt sice nestrannı, ale tentokrát jsem nejspíš pøekroèil mez. V budoucnu se polepším.}
{148}{}{Hmm. Ne. Asi ne dost hrubı.}
{149}{}{Hodnì štìstí. Doufám, e na tu práci máš.}
{150}{}{Radìji bys mì nemìl zklamat.}
{151}{}{Dej tu zbraò pryè a to hned.}
{152}{}{Co si asi myslíš, e tu s tím dìláš?}
{153}{}{Jen si zkouším míøení.}
{154}{}{Nic, pardon. Nechtìl jsem tasit.}
{155}{}{Hung.}
{156}{}{Buï opatrnı s tím oslovováním. A netas tady uvnitø zbraò. Vdy jsme proboha ve Vaultu.}
{157}{}{Radìji bys to nemìl zkoušet tady. Budeme spolu mít co dìlat, pokud bys to chtìl udìlat znovu.}
{158}{}{Vìdìl jsem, e ten ivot venku tì pøivede do potíí.}
{159}{}{Stát! Tady nemáš co dìlat!}

{1000}{}{Správce}
{1100}{}{Je nejvyšší autorita Vaultu. ivot Vaultu se øídí jeho rozhodnutími.}
