{100}{}{Paladin}
{101}{}{Dobrý den, Zasvìcenèe.}
{102}{}{Jestli nìco potøebuješ, mìl by sis promluvit s Vree.}
{103}{}{Jestli s nìkým potøebuješ mluvit, tak Vree je támhle.}
{104}{}{Musím si najít èas mezi hlídkováním a tréninkem, abych se mohl vìnovat svému studiu. Mám pocit, že už trochu rezavím.}
{105}{}{Svou mysl a kondici by sis mìl udržovat po celou dobu ve špièkové formì, Zasvìcenèe.}
{106}{}{My písaøi navrhujeme veškeré vybavení, zbranì a zásoby. Je to velmi zajímavé.}
{107}{}{Být paladinem neznamená jen boj, synu.}
{108}{}{Být paladinem neznamená jen boj, dìvèe.}
