{100}{}{Vidíš Petra, vùdce zvìdù Následovníkù.}
{101}{}{Co tady dìláš? Nevidíš, že máme práci?}
{102}{}{Huh?}
{103}{}{Omlouvám se. Už jdu.}
{104}{}{Mùžu ti s nìèím pomoct?}
{105}{}{Chtìl bych vám pomoct. S kým o tom mùžu mluvit?}
{106}{}{Perfektní. Mám práci, a mám za zády nìjakýho troubu. Jestli si chceš s nìkým promluvit, jdi za Jakem.}
{107}{}{Jistì. Mùžeš zaèít tím, že mi uhneš z cesty.}
{108}{}{Jistì. Nìco dalšího?}
{109}{}{Myslím, že bych toho mohl udìlat mnohem víc.}
{110}{}{Neber mì na lehkou váhu.}
{111}{}{Jo. Mùžeš odsud vypadnout.}
{112}{}{Dobøe. Vypadá to, že se tì jinou cestou nelze zbavit. Vypadá to, že tu máme problém s bezpeèností. Jestli nám chceš pomoct, najdi ten problém.}
{113}{}{Ok. Udìlám to.}
{114}{}{Na to zapomeò!}
{115}{}{Fajn. Teï vypadni!}
{116}{}{Podívej, nìkdo odsud vynáší informace. Potøebujeme najít, kdo za tím stojí a skonèit to s ním.}
{117}{}{Jasnì. Jdu na to.}
{118}{}{Na to zapomeò!}
{119}{}{Vypadám snad jako nápovìda? Jestli chceš nìkoho, kdo ti poradí, tak bìž za Jakem.}
{120}{}{Zmiz, zkouším tady nìco dokonèit.}
{121}{}{Musíme toho špióna dostat. Pospìš si!}
{122}{}{S tou Heather to byla dobrá práce. Mìl jsem tušit, že to je ona. Pøi každém nájezdu vždy jakoby na chvíli zmizela. Tady, vem si tohle a bìž.}
