{100}{}{Vidíš Krypáka Phraxe.}
{101}{}{Ta lednièka ti nepatøí. Doporuèuji ti na ni nesahat.}
{102}{}{Proè ne?}
{103}{}{A ty mi v tom jako chceš zabránit?}
{104}{}{Ne, já jen hvízdnu na ostatní kámoše Krypáky a ty pak poznáš pravı vıznam slova bolest.}
{105}{}{Oh.}
{106}{}{Tohle patøí Krypákùm. Nesahej na to.}
{107}{}{Chci si jen dát nìco k pití.}
{108}{}{Oh, dobøe.}
{109}{}{V té lednièce nic k pití nenajdeš. Dr se od ní dál.}
{110}{}{Nemìl si sahat na vìci co ti nepatøí. A tohle ti teda rozhodnì nepatøí. Máš smùlu mladej...}
{111}{}{Moná e patøíš k Krypákùm, ale tohle není tvùj pokoj. Na nic nesahej.}
{112}{}{Pøišel jsi na špatné místo ve špatnı èas!.}
{113}{}{Tohle není tvùj pokoj. Na nic nesahej, nebo se mi budeš zodpovídat.}
{114}{}{[HOTOVO]}
{115}{}{[VÍCE]}
{116}{}{Phil má víc kuráe ne jakıkoliv Harlekın!}
{117}{}{FIALOVİ PAVIÁN!}
{118}{}{Brahminy mají víc rozumu ne Harlekıni.}
{119}{}{Harlekıni jsou slabí, dokonce i Lex je zvládne všechny zmlátit.}
