{100}{}{Vidíš Cindy jak pláèe.}
{101}{}{Vidíš plaèící Lisu.}
{102}{}{Vidíš Sandy jak pláèe.}
{103}{}{Vidíš plaèící Mary.}
{104}{}{Vidíš Stacy jak pláèe.}
{105}{}{Vidíš plaèící Susan.}
{106}{}{Vidíš Cindy.}
{107}{}{Vidíš Lisu.}
{108}{}{Vidíš Sandy.}
{109}{}{Vidíš Mary.}
{110}{}{Vidíš Stacy.}
{111}{}{Vidíš Susan.}
{112}{}{Hleïme, }
{113}{}{. Už jsi našel ten vodní èip?}
{114}{}{Ne, ještì ne.}
{115}{}{Jistì. Jak se vám daøí?}
{116}{}{Ughh!}
{117}{}{Oh... ty mi nerozumíš. Mám pocit, že už nám pøíliš nadìje po tom všem nezbývá. Omluv mì, že pláèu.}
{118}{}{Ugg!}
{119}{}{Prosím najdi to, než moje dítì zemøe žízní.}
{120}{}{[Odejít]}
{121}{}{Musíš ho najít! Nesmíš nás nechat takhle umøít!}
{122}{}{[Odejít]}
{123}{}{Snaž se. Vìøím ti. Vìøím, že udìláš všechno, abys nás zachránil.}
{124}{}{[Odejít]}
{125}{}{Bojím se toho, co se dìje. Nìkdo nám tu krade vodu, takže všichni jedou už jen na rezervu.}
{126}{}{Kdo by takovou vìc udìlal?}
{127}{}{Co se stalo?}
{128}{}{Pár lidí už bylo obvinìno, nìkdo se kvùli tomu i popral, ale poøád se vlastnì neví, kdo to byl.}
{129}{}{Ok. Díky.}
{130}{}{Pár lidí si stìžovalo, že jim nìkdo ukradl vodu. Žádnou další už nedostali, ale jejich kamarádi se s nimi podìlili. Po tom se všichni stali trochu paranoidní a zaèali si svoje pøídìly hlídat. Pár dní potom nìkdo omráèil stráž hlídající naše zásoby a ukradl velké množství vody.}
{131}{}{To je hrozné! Co pro vás mohu udìlat?}
{132}{}{Možná, že se ti toho zlodìje podaøí chytit.}
{133}{}{Porozhlédnu se tady.}
{134}{}{Sbohem.}
