{100}{}{Vidíš Krypáka Rayzeho.}
{101}{}{Jsi blázen, e jsi sem pøišel.}
{102}{}{Nevím z jakı prdele jsi sem pøilez, ale mìl bys mít opravdu dobrej dùvod proè mì obtìuješ. [Zaène se škrábat v rozkroku.]}
{103}{}{Poslal mì Rock.}
{104}{}{Nevšímej si mì, jen procházím.}
{105}{}{Øekni mi o Harlekınech.}
{106}{}{Povìz mi o generátoru.}
{107}{}{Opravdu? A proè to udìlal?}
{108}{}{Øíkal e bych tu mohl dostat jedno pìknı orosenı.}
{109}{}{Rock øíkal e Krypáci zrovna nabírají nové èleny.}
{110}{}{[Vytáhne starou rezavou lopatu] Odprejskni, ne budeš pohøben.}
{111}{}{Moná... Myslíš, e máš na to aby z tebe mohl bıt Krypák? Jsi dost tvrdej na to, aby ses vyškrábal tøeba z vlastního hrobu, pokud budeš muset? Jsi jen maso na poráku nebo smrtonoš, kterı bude pøinášet dìs a zkázu všem našim nepøátelùm? Co mi na to øekneš?}
{112}{}{Ano! Jste lidi pøesnì podle mého gusta!}
{113}{}{Ne... To není nic pro mì.}
{114}{}{Tak to si tì trochu vyzkoušíme. Dám ti takovı malı úkol. Pùjdeš oèihnout Harlekıny na severu a pak mi všechno nahlásíš.}
{115}{}{Máš to mít.}
{116}{}{Na to zapomeò.}
{117}{}{[Vytáhne starou rezavou lopatu] Tak radìji odprejskni, ne tì pohøbíme!}
{118}{}{Cizince na Šrotišti nevidíme moc rádi. Pokud plánuješ zùstat, radìji bys mìl pøidat se k nám. Pokud to neudìláš, zjistíš, e ivot ve mìstì by pro tebe mohl bıt velmi nepøíjemnı.}
{119}{}{A co to obnáší pøidat se k vám?}
{120}{}{[Rayze zaujatì pozvedne oboèí.] Kadı kdo by se k nám chtìl pøidat, musí nejdøív sloit pøísahu vìrnosti. Tyhle vìci u nás bereme fakt vánì, take jestli ji porušíš, budeme z tebe muset udìlat odstrašující pøíklad! Jakmile sloíš pøísahu, tak jsi èlenem gangu.}
{121}{}{Dobrá, pøidám se k vám.}
{122}{}{Nemám zájem se k vám pøidat.}
{123}{}{Nejsi tu vítán. Pokud nechceš bıt pohøbenı, tak vypadni.}
{124}{}{Jsou Harlekıni pøipraveni na náš útok?}
{125}{}{Ano.}
{126}{}{Ne.}
{127}{}{Potøebuju víc èasu.}
{128}{}{Na tom vlastnì ani nezáleí. Nic je nezachrání pøed chladnım objetím hrobu! Pøipravte se k útoku!}
{129}{}{Vıbornì! Zastihneme je pøekvapené. Pøipravte se k útoku!}
{130}{}{Pospìš si! [Ve tváøi se mu obìví nedoèkavı vıraz.] Jediná vìc, která zde po Harlekınech zùstane je náhrobek!}
{131}{}{Jsou naši nepøátelé. Brzo všichni zemøou. Znovu se tì ptám, proè mì obtìuješ?}
{132}{}{Poslal mì Rock.}
{133}{}{Mì si nevšímej. Jen tudy procházím.}
{134}{}{Povìz mi o generátoru.}
{135}{}{Radìji nestrkej nos do vìcí do kterıch ti nic není. Generátor je náš a náš taky zùstane. Dokud ovládáme generátor, tak ovládáme celé mìsto. Pokládáš nìjak moc otázek.}
{136}{}{[hotovo]}
{137}{}{[více]}
{138}{}{Hahaha! Další Harlekıni na zabití!!}
{139}{}{Jediná vìc které budou Harlekıni vládnout jsou jejich hroby...}
{140}{}{Smrdíš hùø ne Brahminí hovna.}
{141}{}{Dokonce i Lenny má lepší mušku ne ty.}
{142}{}{Nezkoušej mi lhát. Moji lidé tì sledují. Udìlej co jsem ti øekl a pak se vra. Nepokoušej mou trpìlivost.}
{143}{}{Nedá se ti vìøit. To je škoda. Teï zemøeš. Tìšilo mì a sbohem.}
{144}{}{Tomuhle mìstu vládneme my!}
{145}{}{Teï není èas na vykecávání. Teï je èas bojovat!}
{146}{}{Tak radìji mazej za maminkou, ne ti nìkdo naplácá na zadek.}
