{100}{}{Vidíš Regulátora, jednoho z hlídaèù Adyta.}
{101}{}{}
{102}{}{Dokud jsi tady, dr své zabijácké choutky na uzdì.}
{103}{}{Vítej v Adytu, cizinèe. Chovej se tu slušnì, protoe tì budeme sledovat.}
{104}{}{Rád bych vešel.}
{105}{}{Mohu se tì na nìco zeptat?}
{106}{}{Uhhh...}
{107}{}{Moná tì k nìèemu vyuije Zimmerman. Pojï dovnitø, ale nezapomeò. Sledujeme tì.}
{108}{}{Vítej zpátky! Ty jsi tady vítán kdykoliv.}
{109}{}{Nemáš nìjakou práci? Vra se, a je dokonèíš.}
{110}{}{Jdi pryè!}
{111}{}{Co teïka chceš?}
{112}{}{Rád bych vešel.}
{113}{}{}
{114}{}{Nic. Zapomeò na to.}
{115}{}{}
{116}{}{Ne.}
{117}{}{O èem bys rád nìco vìdìl?}
{118}{}{Co tady dìláš?}
{119}{}{Mùeš mi øíct nìco o L.A. kostnici?}
{120}{}{Jak se dostanu dovnitø?}
{121}{}{Co víš o Dìtech katedrály a Následovnících apokalypsy?}
{122}{}{Nic, díky.}
{123}{}{Já jsem jedním z Regulátorù. Naše práce je udrovat v Adytu mír a chránit mìsto. Náš šéf, Caleb, by ti mohl øíci víc.}
{124}{}{Západnì od nás jsou Následovníci apokalypsy. Je to banda praštìnıch mírotvùrcù. Na vıchodì jsou Blades, banda ztroskotancù, jestli se ptáš mì. Kus cesty na jih odtud je Katedrála, kde mají své náboenské centrum Dìti katedrály.}
{125}{}{Promiò, ale my si tady musíme na cizince dávat pozor. Je tu pøíliš nebezpeèno. Moná bys ale mohl udìlat nìjakou prácièku pro Zimmermana.}
{126}{}{Dokonèi svoji práci.}
{127}{}{Ty jsi tady samozøejmì vítán kdykoliv!}
{128}{}{Oboje to jsou skupiny bláznù. Následovníci chtìjí, aby byl kadı mírumilovnı a šastnı. Nepochopí, e svìt je na to moc drsnı.}
{129}{}{Dìti mají nìjakého boha, ke kterému se ve své Katedrále dole na jihu modlí. Mají tady nemocnici, ale jsou trochu moc divní na to, aby jim šlo vìøit.}
{130}{}{Varovali jsme tì, abys tady nevytahoval zbranì!}
{131}{}{Dokud jsi tady, bude lepší nevytahovat zbranì.}
{132}{}{Zlodìj, eh? Ukáu ti, co s takovımi jako jsi ty dìláme tady!}
{133}{}{[Odejít]}

{134}{}{Hlídej se.}
{135}{}{Sledujeme tì.}
{136}{}{Nevyboèuj z øady.}
{137}{}{Na co èumíš.}
{138}{}{Co chceš.}

{139}{}{Hádám, e to znamená, e jsme s tebou skonèili, starej.}

{1000}{}{Adytum}
{1001}{}{Naslednici}
{1002}{}{Katedraly}
{1004}{}{Blades}
{1005}{}{Runneri}
{1006}{}{Hub}
{1007}{}{Junktown}
{1008}{}{Cip}
{1009}{}{Skladiste}
{1010}{}{Zimmerman}
{1011}{}{Nekropolis}
{1012}{}{Krater}
{1013}{}{Regulatori}
{1014}{}{Hledaci}
{1015}{}{Boneyard|Kostnice}

{1100}{}{To je tady.}
{1101}{}{ijí na vıchod od nás.}
{1102}{}{Je to kousek na jih.}
{1104}{}{Najdeš je na sever od nás.}
{1105}{}{Jsou na vıchod od Blades a na sever od páraèù.}
{1106}{}{Obchodujeme s nimi.}
{1107}{}{Není to to mìsto na severu?}
{1108}{}{Co?}
{1109}{}{Tinin obchod je v podzemí blízko brány.}
{1110}{}{On je náš starosta.}
{1111}{}{Slyšel jsem, e je to na vıchod.}
{1112}{}{To je povìst.}
{1113}{}{Chráníme Adytum.}
{1114}{}{Hledají venku vìci.}
{1115}{}{Tohle je L.A. kostnice.}
