{100}{}{Vidíš Richieho.}
{101}{}{Tohle nesmíš dìlat. Musím tì zastavit!}
{102}{}{Tady nemáš co dìlat. U jsi zjistil, e tì nejspíš zabiju?}
{103}{}{Tvá smìna skonèila. Já jsem tvoje náhrada.}
{104}{}{Inspektor trezorù z Hubu. Jsem tu, abych zkontroloval trezor. Uhni.}
{105}{}{Poper se s tím hochu. Ukonèi ten kruh násilí hned teï!}
{106}{}{Kdo ti to øekl! Pane, jestli si na mì troufneš, bude to nejvìtší chyba tvıho ivota!}
{107}{}{Ahoj chlapèe! Co je v tom ocelovım trezoru?}
{108}{}{Pøíliš pozdì, hlupáku. Chcípni.}
{109}{}{Uh... jóó... runk...}
{110}{}{Není mou povinností s tebou mluvit! Vysmahni!}
{111}{}{Je na èase! U je tu horko! Taky nuda! Kdybych tuhle práci nepotøeboval, abych uivil rodinu, øekl bych Lorenzovi, a si jí strèí nìkam. Tak zejtra.}
{112}{}{Já odsud odejít nesmím a ty tady nemáš co dìlat. Vypadni!}
{113}{}{Z vašich oficírù z Hubu se mi dìlá na nic! Take kontrola trezoru mıch šéfù! Co bude dál, vyšší danì? Mùe snad tady èlovìk ít klidnım ivotem bez byrokratù, kteøí všechno poøád musej kontrolovat? Jednoho dne toho bude u moc a my øeknem prostì dost. Jo, jednoho dne se nìkdo jako já naštve a vrazí vám koleno do tìch vašich kanceláøskejch koulí, jak u si dávno zaslouíte. Jednoho dne vám to všechno vrátíme... U se nemùu doèkat... Mimochodem, nic osobního. Vím, e prostì dìláš jen svou práci. Zatímco to tady budeš kontrolovat, podívám se nìkam jinam. Èau.}
{114}{}{Nedávej mi tenhle šmejd! Koukej odsud vypadnout, nebo to do tebe napálím!}
{115}{}{No jasnì. Nikdo si nebude na Richieho Glowsteadera dovolovat a myslet si, e mu to jen tak projde!}
{116}{}{Oh, nìco okolo deseti tisíc zátky. Doufám, e nepøemıšlíš o tom, e bys to ukrad. Musel bych tì zabít. U sem jednou málem nìkoho zabil, take si se mnou nezaèínej!}
{117}{}{Paneboe, ty si stupido. Oh, promiò, nechtìl jsem tì urazit. Take znova. „Ano“ znamená, e ti ustøelím hlavu. „Ne“ znamená, e hejbneš zadkem a vypadneš. Take co to bude?}
{118}{}{Ach... ano...}
{119}{}{Uh... ne...}
{120}{}{Runk! Runk!}
{121}{}{Sakra, to nemùu udìlat! To by bylo jako zastøelit slepı zvíøe. Prostì odsud vypadni, jo?}
{122}{}{Správnì. Teï zmizni. Jsem si jistej, e najdeš nìkoho, kdo tì nakrmí...}
{123}{}{Moná, e jeden runk znamená „ano“ a dva runky znamenají „ne“. Ok, „runk“ znamená, e tì zabiju. „Runk, runk“ znamená, e odejdeš. Jasnı?}
{124}{}{Runk}
{125}{}{Runk, runk.}
{126}{}{Runk, runk, runk!}
{127}{}{Tøikrát runk. Do hajzlu, ono to nefunguje. Tak tì budu prostì ignorovat, dokud nevypálíš...}
