{100}{}{Vidíš zvìda Nightkinù.}
{101}{}{Copak to tu máme? Á, normál. Myslím, že pùjdeš se mnou.}
{102}{}{Ne.}
{103}{}{Dobrá.}
{104}{}{Proè bych mìl?}
{105}{}{Zamysli se znovu!}
{106}{}{Je to tak prosté. Když pùjdeš se mnou, pomùžu ti.}
{107}{}{Dobrá. Pùjdu s tebou.}
{108}{}{Radìji mì nasmìruj pøímo k veliteli.}
{109}{}{Nikdy!}
{110}{}{Jak to pùjde nejrychleji. Hledej Utherna. Ten tì srovná.}
{111}{}{Uthern tì chce vidìt. Zdá se, že o tobì už slyšel.}
