{100}{}{Tohle je podivnì vypadající disketa. Moná by se dala pouít ve tvém Pip-Boyi 2000.}
{101}{}{Pip-Boy 2000 zobrazuje: „Stahování... Pøerušuji, data ji existují!“}
{102}{}{Pip-Boy 2000 zobrazuje: „Stahování dat... ... ... Hotovo. Hezkı den!“}
#
#
# For Fallout Fixt:
#
#
# NOTE: In 103, override is spelled improperly on purpose.
#
{103}{}{Tento disk je ve špatném stavu. Nemá ádné oznaèení, ale na boku má naškrábáno slovo „pøepsání“.}
{104}{}{Vidíš bezpeènostní pøemosovací disk.}
#
#TRANSLATION NOTE: In 105, admin is abbreviation for administrator, so use your language's equivalent of "administrator" if abbreviation doesn't exist.
# "muerte" is "death" in Spanish, leave as-is, do not translate. (Wasteland reference)
#
{105}{}{Uivatel: „admin“. Heslo: „muerte“. Pøepsání bezpeènostního protokolu: Gamma Omicron Delta.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Pokraèovat]}
{109}{}{Pip-Boy 2000 zobrazuje: „Uivatel: 'admin'. Heslo: 'muerte'. Pøepsání bezpeènostního protokolu: Gamma Omicron Delta.“}
