{100}{}{Vidíš pevnou zeï.}
{101}{}{Na tomhle kousku zdi je nìco divného.}
{102}{}{Vidíš posuvné dveøe.}
{103}{}{Dveøe jsou zamèené.}
{104}{}{Spustil jsi past na dveøích.}
{105}{}{ objevuje past na dveøích.}
{106}{}{Objevil jsi past na tìchto dveøích.}
{107}{}{Nic to nedìlá.}
{108}{}{Dveøe už jsou odemèeny.}
{109}{}{Paklíèe se na tomto složitém zámku zlámaly.}
{110}{}{Zámek se nepodaøilo odemknout.}
{111}{}{Zámek se podaøilo odemknout.}
{112}{}{Tento zámek je na tebe pøíliš složitý.}
{113}{}{Objevil jsi vysoce výbušnou past na tìchto zamèených dveøích.}
{114}{}{Objevil jsi vysoce výbušnou past na tìchto dveøích.}
{115}{}{Objevil jsi past na tìchto zamèených dveøích.}
{116}{}{Objevil jsi past na tìchto dveøích.}
{117}{}{Nevidíš na tìchto zamèených dveøích nic zvláštního.}
{118}{}{Nevidíš na tìchto dveøích nic zvláštního.}
