{100}{}{Vidíš Sherry.}
{101}{}{Vidíš èlenku gangu.}
{102}{}{}
{103}{}{Kdo jsi a co tu chceš?}
{104}{}{Jsem }
{105}{}{. Pøicestoval jsem sem teprve nedávno.}
{106}{}{Do toho ti nic není, holka!}
{107}{}{Hua?}
{108}{}{Zøejmì ano, kadej pøece ví, e tohle je území Lebkounù. Lepší bude zmizet, ne se nìkdo rozhodne, e ti ublíí.}
{109}{}{Jen to zkuste!}
{110}{}{Pardon, myslel jsem, e je to koupelna. Sbohem.}
{111}{}{Lebkouni? Co jste zaè?}
{112}{}{Nechci problémy... Jen se tu potloukám.}
{113}{}{Zmiz, pako, ne tì nìkdo z nás roztrhne vejpùl.}
{114}{}{Tssss, pardon.}
{115}{}{Jo? Sem s tím!}
{116}{}{Mìl by ses pøidat. Není to tu nijak bezpeènı, zvláš pro nìkoho jako jsi ty, kdo prostì nechápe.}
{117}{}{To jsme my! Nejsilnìjší gang ve mìstì. Vlastnì, jedinı gang. Ale nikdo si s náma nezahrává.}
{118}{}{Take máte mìsto docela pod palcem, co?}
{119}{}{Moc pìknı. Na vidìnou.}
{120}{}{Och. Radìji bys nemìl. Víš, nejsi èlenem gangu, a tohle je jeho území. Take bys mìl zmizet, ne se Victor nasere.}
{121}{}{No, myslím, e zùstanu.}
{122}{}{Kdo je Victor?}
{123}{}{Fajn, u mizím.}
{124}{}{Fajn. Pøiprav se na svùj pohøeb.}
{125}{}{Victor je pøímo támhle. Je ten nejhorší grázl ze všech. Zboòuje muèení leguánù, které loví. Popravdì øeèeno, nemám ho moc ráda, ale je jedním z nás.}
{126}{}{Take, Viktor, a Shark, ten se poflakuje ve Skum Pitt baru. Vinnie, ten taky, a pár dalších chlápkù, kteøí se obèas zastaví.}
{127}{}{Kde je Skum Pitt?}
{128}{}{Och, Skum Pitt je mizernı bar na sever odsud, poblí Gizmova kasina.}
{129}{}{To si piš! Nikdo se nám nepostaví! No, kromì Killiana, ale ten je v pohodì, je tady nìco jako šerif. My si stejnì dìláme, co chceme.}
{130}{}{Jen tak se poflakujeme, obèas si zahrajeme u Gizma nebo se jdeme pobavit do Skum Pitt baru. Nìkdy dìláme špinavou práci pro Gizma nebo nìkterıho cestovatele. Victor s oblibou sleduje lidi. Zamysli se nad tím, snad si ho budeš chtít udret dál od tìla.}
{131}{}{Dìláte pro Gizma? Co mi o nìm mùeš øíct?}
{132}{}{Tak co tady vlastnì dìláte?}
{133}{}{Kdo všechno je vlastnì v gangu?}
{134}{}{Proè se dríš tìhle chlápkù?}
{135}{}{Jsme jako rodina! Staráme se jeden o druhého. No, vlastnì kromì Sharka, kterej furt nìco rozbíjí. A taky Victora, kterej tak divnì civí na lidi. Ale Vinnie je v pohodì. A chlastáme spolu. Víš, jsme kámoši a chlastáme spolu.}
{136}{}{Och, zase ty! Víš, není nejbezpeènìjší potloukat se tu, kdy nejsi èlenem. A to ty rozhodnì nejsi.}
{137}{}{Víš, myslím, e by ti tvoji Lebkouni nedokázali sejmout ani spícího brahmina, nato pak mì.}
{138}{}{A co se tady poslední dobou stalo?}
{139}{}{Vánì? Tak se pøesvìdèíme! Victore!}
{140}{}{Celkem nic moc. Není tu moc co dìlat. No, Shark vyvolal pár rvaèek ve Skum Pittu, jako obvykle, ale co jiného se tu dá dìlat?}
{141}{}{Uf, nic moc, myslím.}
{142}{}{Musíš poøád zkoušet nìco jiného. Musíš mít nìjaké koníèky nebo nìjakı vlohy.}
{143}{}{Obèas nìco nakreslím. A Vinnie øíká, e dost dobøe vaøím. Ale já øíkám, máme chlast i zábavu, rozumíš?}
{144}{}{Jo to je pochopitelné.}
{145}{}{Ale co budeš dìlat, a budeš starší? Co bude s tvım ivotem? Kde vezmeš peníze?}
{146}{}{Hm, o tom nikdy moc nepøemıšlím. Vinnie a Victor nìjakı peníze vydìlají a Shark obèas dìlá ochranku návštìvníkùm. Jinak nevím.}
{147}{}{Nebylo by lepší zmizet, dokud ještì mùeš?}
{148}{}{Hej, sklapni! Jsi stejnej, jako bıvali Vinnieho rodièe. Podporujeme jeden druhého, rozumíš? Tak nemel.}
{149}{}{Asi jo. Nijak moc o tom nepøemıšlím.}
{150}{}{Ahoj! Jak se máš? To byla chvilka.}
{151}{}{Jsem v pohodì, díky.}
{152}{}{U bylo líp.}
{153}{}{Fajn. A co ty?}
{154}{}{To je mi líto! Mìl by sis najmout pokoj a prospat se. Promluv si s Marcelle.Jo, a mùu ti nìco ukuchtit, jestli chceš.}
{155}{}{To by bylo prima, dík.}
{156}{}{Ne, díky, ale ještì se uvidíme.}
{157}{}{Je mi mnohem líp, díky! Vaøím teï ve Skum Pitt baru a v hotelu Crash House. Nìkdy je to docela únavné, ale vaøení se mi prostì líbí a navíc potkám spoustu zajímavıch lidí. A ještì dostanu zaplaceno. Díky za pomoc.}
{158}{}{Tady je to. Dobrou chu. Uvidíme se!}
{159}{}{To je ten tlusoch, co øídí kasino. Chtìl by øídit i celı Junktown, ale Killian ho drí na uzdì. Platí docela obstojnì. Obèas si najímá Vinnieho nebo Victora, aby se postarali o nìkteré problémové lidi. Jako tøeba ten cizinec, co se tu objevil pøed pár tıdny.}
{160}{}{Chceš po mì, abych práskla svoje kamarády?!?}
{161}{}{Jo, potøebuju od tebe informace.}
{162}{}{Ne, zapomeò na tu otázku.}
{163}{}{Ubliují lidem a budou v tom pokraèovat, pokud jim v tom nìkdo nezkusí zabránit. Zmìnila jsi svùj ivot k lepšímu. Teï máš šanci pomoci i ostatním, aby se mìli líp.}
{164}{}{Hmm. Dobøe, myslím, e to jsou mí pøátelé. Ale asi by nemìli mít monost ubliovat lidem tak, jak to dìlají. A tobì vìøím, od té doby co jsi mi pomohl. Dobrá, pomùu ti.}
{165}{}{Ne, to nemùu udìlat! Jsou to mí pøátelé! Moná u nepatøím mezi Lebkouny, ale pøesto svoje staré pøátele nepodrazím.}
{166}{}{Potøebuju tvou pomoc. Musím mít tvoji vıpovìï, abych mìsto zbavil Lebkounù po dobrém?}
