{100}{}{Vidíš pøed sebou Taliuse, èlena Následovníkù apokalypsy.}
{101}{}{Prosím, odejdi. Pokouším se zde odpoèívat. Vra se zpátky bìhem dne.}
{102}{}{Dobrı den, sestro. Jmenuji se Talius. V èem vám mohu bıt dnes nápomocen?}
{103}{}{Dobrı den, bratøe. Jmenuji se Talius. V èem vám mohu bıt dnes nápomocen?}
{104}{}{Hu?}
{105}{}{Já }
{106}{}{. Já }
{107}{}{.}
{108}{}{Já jsem }
{109}{}{. Co tady dìláš?}
{110}{}{Mùeš zemøít!}
{111}{}{Neboj se o mì, mutouši! Jak ses sem dostal?}
{112}{}{Také tì zdravím. Jmenuji se }
{113}{}{. Jak je moné, e jste se dostal na území Následovníkù?}
{114}{}{Mùete mi vysvìtlit, jak se nìkdo tak nestálı, jako vy, mùe stát Následovníkem?}
{115}{}{Vidím, e jsi trochu pomalejší. Ani já jsem vdycky nebyl takovı, jakı jsem dnes. Ale uèení Následovníkù odstranilo všechny mé nedostatky.}
{116}{}{Ne teï.}
{117}{}{Pøíliš chytrı. Teï zemøeš.}
{118}{}{Omlouvám se. Trochu jsem se pozapomnìl. Nepotøebujete nìkoho inteligentního, kdo by vám pomohl?}
{119}{}{Jo. Ty´s!}
{120}{}{Ty hep. Ty hep!}
{121}{}{Tady. Vem si tyhle prášky. Budeš chytøejší.}
{122}{}{Ano, }
{123}{}{Tìší mì, e se hlásíte ke svému jménu. Jak vám mohu za tohoto krásného jitra poslouit?}
{124}{}{Co?}
{125}{}{Mozek bolí. Já zabít ty. Vzít mozek.}
{126}{}{Jsem zde, abych pomohl tìmto dobrım lidem pochopit skutky Dìtí katedrály.}
{127}{}{Take ty pro Dìti katedrály špehuješ?}
{128}{}{Jak o nich mùeš nìco vìdìt?}
{129}{}{Co mùeš udìlat? Vdy jsi mutant.}
{130}{}{Nikoliv, nejsem špión. Aèkoli mnozí tak soudí. V našem skromném pøíbytku špión skuteènì je. Dosud jsme ho však nebyli schopni odhalit.}
{131}{}{Tak jak tedy Následovníkùm pomáháš?}
{132}{}{Øekni mi, co víš o tom špiónovi. Tøeba ti pomùu.}
{133}{}{To je ale štìstí, Mutáèi!}
{134}{}{Myslím, e jsem špióna našel. Teï dám vìci do poøádku.}
{135}{}{Kdysi jsem bıval jako vy. Ale zásahem Nightkinù v Nekropolis jsem byl uvren do tohoto stavu.}
{136}{}{To je strašné. Snad bude líp. Zatím.}
{137}{}{Proè jsi byl v Nekropolis?}
{138}{}{Odkud jsi pùvodnì pøišel?}
{139}{}{A teï tì pøedìlám ještì jednou. Odpoèívej v pokoji.}
{140}{}{Pøed nìjakım èasem jsem il daleko na severu odtud. Mìli tam problémy se zásobami pitné vody, a tak posílali lidi ven, aby nalezli nìjaké øešení.}
{141}{}{Take jsi dobrovolník.}
{142}{}{Kde to místo bylo?}
{143}{}{Našel jsi zpùsob, jak ten problém vyøešit?}
{144}{}{Ale proè Nekropolis?}
{145}{}{Ano. Správce naší komunity mi dal brokovnici a pár nábojù. Nicménì, bìhem tìch mnoha let jsem je ztratil. Nikdy jsem nic nenašel, a tak jsem se nemohl vrátit zpátky.}
{146}{}{To je opravdu hrozné. Pøál bych si, aby tu bylo nìco, v èem bych ti mohl pomoci.}
{147}{}{To je špatné. Mìl bych jít.}
{148}{}{Kde bylo to místo?}
{149}{}{Našel jsi zpùsob, jak ten problém vyøešit?}
{150}{}{Proè jsi šel do Nekropolis?}
{151}{}{Je tady nìco, v èem mùeš pomoct. Ten, co mi to udìlal, musí skonèit.}
{152}{}{Kdo je to?}
{153}{}{Jejich vùdce stojí v èele armády mutantù. Chytá èistokrevné lidi a pøemìòuje je. Pøesnì nevím jak, protoe mì pøed procesem omráèili.}
{154}{}{Pùjdu ho za tebe zabít.}
{155}{}{To zní pøíliš riskantnì. Musím odsud pryè.}
{156}{}{Dìkuji vám za vaši laskavost. Prokázal jste mi velkou slubu. Prosím, pøijmìte toto jako projev mé dobré vùle. Pøivlastnil jsem si to z tìla jednoho zesnulého odpadlíka.}
{157}{}{Buïte v pokoji. Rozumím vašemu problému. Moná vám nìkdo jinı pomùe od vašeho trápení. Hezkı den.}
{158}{}{Místo, ze kterého jsem pøišel, je daleko na severu v horách. Byl to malı Vault, ve kterém ilo hodnì lidí.}
{159}{}{Našel jsi nìkdy øešení toho vodního problému?}
{160}{}{Proè jsi šel do Nekropolis?}
{161}{}{Jak se ten Vault jmenoval?}
{162}{}{To zní hezky. Mìl bych bìet.}
{163}{}{Naneštìstí ne. Slyšel jsem, e se spousta jinıch lidí z Vaultu vydala ven hledat øešení toho problému s vodou.}
{164}{}{Nic víc jsem o nich neslyšel.}
{165}{}{Proè jsi šel do Nekropolis?}
{166}{}{Jak se ten Vault jmenoval?}
{167}{}{To zní hezky. Mìl bych bìet.}
{168}{}{Od jinıch poutníkù jsem slyšel, e v Nekropolis nemají s vodou ádné problémy.}
{169}{}{Tak jsem se tam vydal, abych se podíval, jak to tam vypadá.}
{170}{}{Co jsi našel?}
{171}{}{Zlikvidoval jsi je všechny?}
{172}{}{Cítil ses tam jako doma?}
{173}{}{Našel jsem tam spoustu tìch mutantích potvor. Právì oni mì uvìznili a pøemìnili do mé souèasné podoby.}
{174}{}{Zøejmì to ale nìjak zmršili, protoe má mutace probìhla jinım evoluèním smìrem, take vypadám jinak ne ostatní.}
{175}{}{To je drsnı. Tak zatím.}
{176}{}{Urèitì se po nich podívám. Dík za informace.}
{177}{}{Kdo je vede?}
{178}{}{Ne. Zabil jsem jen pár mutantù. Byl tam ještì jeden mutant, spíš ghoul, jménem Set, kterı mi pomohl dostat vìtšinu z nich.}
{179}{}{Myslím, e tam zbylo ještì pùl tuctu mutantù.}
{180}{}{To zní dobøe. No, uvidíme se pozdìji.}
{181}{}{Vìtšina z nich je u mrtvá. Set se má dobøe.}
{182}{}{To je vskutku skvìlá zpráva. Jsem velmi potìšen, e je celé mìsto osvobozeno od zla. Prosím, vezmi si tohle.}
{183}{}{Sarkasmus a pøezíravost nezastraší mou vstøícnou benevolenci. Nadešel èas, abyste odešel. Sbohem.}
{184}{}{Mùj Vault nemá jméno. Je pouze oznaèen èíslem 13.}
{185}{}{To je to místo, odkud jsem.}
{186}{}{O tom místì jsem nikdy neslyšel.}
{187}{}{Dík za informaci. Teï o tom pùjdu øíct tìm mutantùm.}
{188}{}{Skuteènì? Pochopil koneènì Správce, e jediná cesta, jak pøeít, je vyslat lidi ven z Vaultu?}
{189}{}{Ne, poøád se venkovního svìta bojí.}
{190}{}{Ne, má strach o bezpeènost lidí ve Vaultu.}
{191}{}{Ano, myslí si, e je to bezpeèné.}
{192}{}{Vìøím tomu. Vdycky to byl opatrnı èlovìk. Je mi líto jeho bøemene. Snad se ti povede lépe ne mnì.}
{193}{}{Jsem opravdu rád, e pøišel k rozumu a vypustil lidi ven. Aèkoli venku není bezpeèno, prospìje to obnovì Zemì. Sbohem, pøíteli.}
{194}{}{Pochybuji, e byste o nìm slyšel, kdy pøicházíte z vnìjšího svìta. Nyní se však musím odebrat k odpoèinku. Prosím, dávejte na sebe venku pozor pøed stvoøeními, která touí jen nièit.}
{195}{}{Nikoliv, pochybuji, e byste byl schopnı to tak udìlat.}
{196}{}{Zkus mì zastavit.}
{197}{}{Proè to øíkáš?}
{198}{}{Protoe tì zastavím.}
{199}{}{Vím velmi málo. Jediné, co vím, je, e naši zvìdové jsou jediní, kdo se kdy vydávají k Dìtem katedrály šmírovat. Nikdo jinı nesmí, protoe je to pøíliš nebezpeèné.}
{200}{}{Take by to mohl bıt zvìd. Podívám se na to.}
{201}{}{Myslím, e jsi to ty. Teï zemøeš!}
{202}{}{Pøál bych si, abys byl trochu chytøejší. Co naplat, bez tebe se snadno obejdu.}
{203}{}{Jediné, co o Dìtech vím, je, e jsou ve spojení s Nightkiny, odpornım druhem supermutantù.}
{204}{}{Jsou to právì oni, kteøí mì pøemìnili z pùvodního stavu, kdy jsem byl v Nekropolis.}
{205}{}{To je hrùza. Ale mohlo to bıt horší. Tak zatím.}
{206}{}{Proè jsi byl v Nekropolis?}
{207}{}{Odkud pùvodnì jsi?}
{208}{}{Tak a teï tì pøetransformuju ještì jednou. Spi sladce.}
{209}{}{Aèkoliv vypadám všelijak, mám spoustu vìdomostí, které mohu sdìlit tomu, jen naslouchá.}
{210}{}{Na tohle nemám èas, odcházím.}
{211}{}{Co mi mùeš øíct?}
{212}{}{Ti, které Následníci a Dìti nazıvají Nightkiny, nejsou to, co se zdají. Byli stvoøeni èlovìkem, kterı se jmenuje Poruèík, a vìøím, e nad ním je ještì nìkdo.}
{213}{}{Nìjakou informaci. Dobrá, zmizím.}
{214}{}{Co mi o tomhle Poruèíkovi mùeš øíct?}
{215}{}{Moc toho o nìm nevím. Naposledy jsem ho vidìl pøed mojí pøedèasnou transformací, kdy zrovna pátral po èistokrevnıch lidech.}
{216}{}{Budu o tom chvíli pøemıšlet. Díky.}
{217}{}{Nemùeš si èistì náhodou pøedstavit, proè by to tak mìlo bıt?}
{218}{}{Dosud si nejsem jistı. Snad jiná skupina, která usiluje o narušení jejich zámìrù, by to mohla vìdìt.}
{219}{}{Dìkuju. Hezkı den.}
{220}{}{Lituji, avšak drzost nemohu tolerovat. Jdi.}
{221}{}{Mùj vstup do øad Následovníkù byl prostı. Následovníci mì toti zachránili pøed úplnou transformací v ohavnou bestii.}
{222}{}{Úplnì tomu nerozumím. Prosím pokraèuj.}
{223}{}{Kdysi jsem bıval jako vy – èistokrevnı èlovìk. Ale bìhem útoku Nightkinù jsem byl zavleèen na místo daleko odsud.}
{224}{}{Pokraèuj, prosím.}
{225}{}{Nebyl jsem ve stavu, ve kterém bych byl schopnı pozorovat, co se dìje. Jediné, co si pamatuju, je to, e jsem se tady probudil, opeèováván schopnım doktorem.}
{226}{}{Hroznì mì mrzí, kdy slyším, co se ti stalo. Najdu ty, kteøí ti tohle udìlali, a pokusím se zachránit situaci.}
{227}{}{To mì mrzí. Bohuel, mám dost práce s tím, abych pøeil. Sbohem.}
{228}{}{Prosím, vykonejte spravedlnost nad tím rozvratníkem, jen podkopává dùvìru Následovníkù.}
{229}{}{Vykonali jste skvìlı skutek, kdy jste z našich øad vypudili tu falešnici Heather.}
{230}{}{Vidíš ohavného ghúla.}
{231}{}{Nìkoho ti pøipomíná.}
{232}{}{Bohuel, ji na tebe nemám èas. Hezkı den.}

#Fo1in2
{300}{}{Zdravím, sestro. Jak vám mohu dnes pomoci?}
{301}{}{Zdravím, bratøe. Jak vám mohu dnes pomoci?}
	{302}{}{Co tady dìláš?}
	{303}{}{Jak se nìkdo jako vy pøidal k Následovníkùm?}

{304}{}{Zdravím, sestro. U jste se postarala o toho velitele mutantù v Nekropolis?}
{305}{}{Zdravím, bratøe. U jste se postaral o toho velitele mutantù v Nekropolis?}
	{306}{}{Pracuju na tom. Dám ti pak vìdìt.}
	{307}{}{Zbavil jsem se velitele mutantù.}

# float after Harry is killed
{350}{}{Dìkuji vám za odstranìní tìch mutantù z Nekropolis.}

# Gain x Experience...
{400}{}{ za pomoc Taliusovi.}
