{100}{}{Vidíš jednoho ze stránıch v Shady Sands.}
{101}{}{Hej, myslím, e bys mìl radši jít. Nechceme tady lidi jako ty.}
{102}{}{Nemùu uvìøit tomu, e se Tandi ztratila. Doufám, e ji jdeš hledat. Byla by to nejspíš Aradeshova smrt, kdyby zjistil, e se jí nìco zlého stalo.}
{103}{}{Dík, e jsi Tandi pøivedl zpátky. Je to dobré znamení do budoucna, nemyslíš?}
{104}{}{To s Tandi je po èertech smùla. Doufám, e Aradesh bude v poøádku.}
{105}{}{Vítej cizinèe. Takové jako ty tu nevídáme èasto.}
{106}{}{Uh, díky. Nashle.}
{107}{}{Proè ne?}
{108}{}{Hnnng!}
{109}{}{Ne tak rychle! Tohle je malá komunita. Nevidíme cizince tak èasto a ani je tu nepotøebujeme. Jestli nemáš nìjakı dobrı dùvod tu zùstat, radìji bys mìl jít dál.}
{110}{}{Hej, nikomu jsem neublíil.}
{111}{}{Uh.}
{112}{}{Neøíkal jsem, e tu nejsi vítanı host, ale e bude lepší nechat nás o samotì.}
{113}{}{Pokusím se tu neudìlat ádné problémy.}
{114}{}{U je mi na nic z tìch tvejch blbejch kecù. Pøiprav se na setkání s bohem.}
{115}{}{Podívej, Shady Sands nepotøebuje lidi z Hubu, Junktownu, nebo odkud vlastnì jsi. V pohodì si vystaèíme sami.}
{116}{}{Poslední obchodník z Hubu nám prodal porouchanou zavlaovací pumpu. U máme dost takovejch špinavejch obchodù.}
{117}{}{Já nejsem takovı.}
{118}{}{Hmm... Hlavnì mám tady nedìlej ádné problémy, rozumíš?}
{119}{}{Budu si dávat pozor.}
{120}{}{Rozumím.}
{121}{}{No, moná nejsi. Pøipadáš mi trochu jinı. Dám ti dobrou radu: Jdi si promluvit s Aradeshem. Najdeš ho v centru vesnice na radnici.}
{122}{}{Nechceme tady lidi jako ty. Vra se, odkud jsi pøišel.}
{123}{}{Hej, jen ádné zbranì. Nedíváme se tady na nì pøíliš pøátelsky.}
{124}{}{Hele, nakonec to vypadá, e nejseš tak špatnej. Mìj se fajn.}
{125}{}{Opravdu si pøeji, abys prostì opustil mìsto.}
{126}{}{[DÁL]}
