{100}{}{Pod touto èástí podlahy je umístìn granát.}
{101}{}{Není odjištìn.}
{102}{}{Zneškodnil jsi past a získal plazmový granát.}
{103}{}{Odstraòuješ detonaèní drát omotaný okolo pojistky, když ti vypadl kolík a granát explodoval!}
{104}{}{Pokoušíš se opatrnì vysunout destièku a zneškodnit past, ale je témìø nemožné to udìlat tak, aby ses nedotknul detonaèního drátu.}
{105}{}{Snažíš se pohnout s destièkou, ale granát se ti neustále kvedlá v rukou.}
{106}{}{Vysunul jsi destièku, ale detonaèní drát ti proklouzl mezi prsty, než jsi ho staèil vypojit.}
