{100}{}{Tady nìco nehraje.}
{101}{}{Už to mám.}
{102}{}{Spouštìcí mechanismus je zaseklý.}
{103}{}{To je mnohem lepší.}
{104}{}{Už to skoro mám.}
{105}{}{Bude to chvíli trvat.}
{106}{}{To je ten problém!}
{107}{}{Johne, myslím, že jsem ten problém izoloval.}
{108}{}{K èertu!}
{109}{}{Sakra!}
{110}{}{Moje chyba!}
{111}{}{Jsem v poøádku.}
{112}{}{OK, to bolelo.}
{113}{}{Chtìl jsem to tak udìlat.}
{114}{}{Proè se to poøád stává?}
{115}{}{Moje oèi!}
{116}{}{Ty nejsi rytíø.}
{117}{}{Potøebuju mluvit s rytíøem.}
{118}{}{Tomu nerozumím, napájecí èlánky stále ztrácejí energii.}
{119}{}{Mìl by si stát stranou; je to trochu nebezpeèné.}
{120}{}{Prosím, nevyrušuj mì.}
{121}{}{Dívej se, kde stojíš.}
{122}{}{Ztratil ses?}
{123}{}{Promiò, teï nemùžu mluvit.}
