# quick looks
# unknown
{100}{}{Vidíš podivnı pøístroj. }
# normal
{101}{}{Vidíš hrací automat. }
# high roller
{102}{}{Vidíš blıskající se hrací automat. }
# jackpot
{103}{}{Vidíš svítící hrací automat. }

# examines
# unknown
{130}{}{Má to tøi oèi a jednu ruku.}
# bet amount
{140}{}{Minimální vklad je $}
{141}{}{.}
# normal
{150}{}{Máš pocit, e se na tebe dívá. }
{151}{}{Jeho naleštìnı kryt a pozlacená páka svádivì záøí pod blikajícími svìtly. }
# high roller
{165}{}{Je urèenı pro lidi, kteøí se nebojí riskovat. }
# jackpot
{180}{}{Moná vıše vıhry vypadá velice lákavì. }

# slot machine first play message
{200}{}{(Natahuješ se pro mince a pøi tom se ti chvìje celá ruka. Automat ti neustále šeptá.) 
*No tak, zlato... to je ono... jdeme na to... neškádli mì...*}
{201}{}{Vidíš hrací automat. Jeho naleštìnı kryt a pozlacená páka svádivì záøí pod blikajícími svìtly. 
Štìrbina na mince tì pøitahuje a ty cítíš, jak se ti ruce chvìjí nedoèkavostí.}
{202}{}{(Natahuješ se pro mince a pøi tom se ti chvìje celá ruka. Automat ti neustále šeptá.) 
*No tak, zlato... to je ono... chytni tu páku... chytni ji pevnì... jdeme na to... *}

# insert coin messages
{250}{}{Vloit $}
{251}{}{. }
{252}{}{Hrát posledních $}
{253}{}{.}
{254}{}{Pro dnešek skonèit.}
{255}{}{Jsi na dnì. Musíš pro dnešek skonèit.}
{256}{}{Pro dnešek skonèit.}
{257}{}{Jsi na dnì. Musíš pro dnešek skonèit.}
{258}{}{A dost! Konèím!}
{259}{}{A dost! Konèím!}

# this is the message for when the machine is played
{500}{}{Na obrazovce se objeví... }
# this goes between every symbol, example:   "cherry... orange... melon... "
{599}{}{... }

# pay off types
{600}{}{Nic. }
{601}{}{Jedna tøešnièka. }
{602}{}{Dvì tøešnièky. }
# Three [symbol].
{603}{}{Tøi }
{613}{}{. }
{604}{}{JACKPOT! }
{605}{}{DVOJITİ JACKPOT!!! }

# payoff amount message
{700}{}{Vıhra èiní $}
{701}{}{.}
# symbol types
# singular
{1001}{}{tøešnièka}
{1002}{}{pomeranè}
{1003}{}{švestka}
{1004}{}{zvoneèek}
{1005}{}{bar}
{1006}{}{meloun}
{1007}{}{sedmièka}
# plural
{1101}{}{tøešnièky}
{1102}{}{pomeranèe}
{1103}{}{švestky}
{1104}{}{zvoneèky}
{1105}{}{bary}
{1106}{}{melouny}
{1107}{}{sedmièky}

# float messages
{2000}{}{*Pojï si zahrát ještì jednou, kovboji.*}
{2001}{}{*Ahoj námoøníku.*}
{2002}{}{*Vhoï minci a zatáhni za páku. Budu k tobì hodnı.*}
{2003}{}{*Tik... tik... tíííík...*}
{2004}{}{*Cink*}
{2005}{}{*Bøink*}
{2006}{}{*Klik-cvak*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Cinkylink*}
{2009}{}{*Dindading*}
{2010}{}{*Ahoj zlato. Pojï si zahrát.*}
{2011}{}{*Ahoj zlato.*}
{2012}{}{*Vypadáš roztomile. Proè si nejdeš zahrát?*}

# 3.  NO MONEY (WTG, 9)
# no money to play
{2175}{}{(Jak tak zíráš na automat, uvìdomuješ si, e nemáš dost penìz na hraní a proklínáš svou chudobu. Moná nìkdy jindy...)}
{2176}{}{Odejít.}
# won jackpot block
{2185}{}{(Na pøístroji bliká svìtlo s nápisem 'MIMO PROVOZ'.)}
{2186}{}{Odejít.}

# 4. RETARD (WTG)
{2100}{}{Vidíš podivnou, kovovou, pozlacenou krabici se tøema oèima a jednou rukou. Je to jedna z nejkrásnìjších vìcí, které jsi kdy vidìl.}
{2101}{}{Já }
{2102}{}{ kdo ty?}
{2103}{}{Já chtít MÁMU. }
{2104}{}{ stıskat se po AR-JOJO. Já chtít jít domù.}
{2105}{}{[Potøást si s rukou]}
{2106}{}{Ty divnı mutant.}
{2107}{}{Chvála Vault! Chvála Vault!}
{2108}{}{Ty bıt vodní èip?}
{2109}{}{Odbelhat se jít hledat jiné lesklé vìcièky.}
{2110}{}{Odejít.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{2130}{}{Ta divná pozlacená kovová krabice se tøema oèima a jednou rukou neodpovídá.}
{2131}{}{JÁ }
{2132}{}{! TY ODPOVÌDÌT MNÌ!}
{2133}{}{[Potøást si s tou rukou]}
{2134}{}{Já dítì Zakladatel. Ty se mnou TEÏ mluvit.}
{2135}{}{ty divnı mutant.}
{2136}{}{Ty bıt vodní èip?}
{2137}{}{Odbelhat se jít hledat jiné lesklé vìcièky.}
{2138}{}{Odejít.}

# 6.  RETARD PULLS HANDLE (4, 5)
{2151}{}{Uchopíš jeho ruku a jemnì si s ní potøeseš. Slyšíš nìjaké *bzzzzzzz* a krabice promluví! "Prosím... vlote... peníze."}
{2152}{}{Ajajaj! Robot! Robot! Honééém pryè.}
{2153}{}{Odejít.}

# slot machine taunts loss
# male
{2200}{}{(Slyšíš, jak se ti ten stroj smìje.)}
{2201}{}{*Hehehe, radìji toho nech, zlato.*}
{2202}{}{*Proè k tomu nepustíš nìkoho, kdo to umí?*}
# any
{2203}{}{(Ze stroje vychází sotva slyšitelnı šílenı smích.)}
{2204}{}{(Slyšíš, jak se ti ten stroj smìje.)}
{2205}{}{(Automat se ti smìje.)}
{2206}{}{*Smùla. No tak, nevzdávej to.*}
# female
{2207}{}{*Dostal jsem to, co jsem chtìl, zlato. Proè to prostì nevzdáš?*}
{2208}{}{*Odpad!*}
{2209}{}{*Pozor na dveøe, a budeš odcházet z kasína.*}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{*Áááááá! To je ono, zlato! Ach boe! Ano! Ještì! Rychleji! Víc! Na co èekáš?! Ještì!*}
{2248}{}{*To je ono, zlato... zatáhni za tu páku... rychleji, více, rychleji... no ták...*}
{2249}{}{*Ale no tak, zlato... to se stane kadému... zkus to ještì jednou... prosím...*}
# any
{2250}{}{*Prosím, ještì to nezdávej, zlato! Potøebuju tì teï jako nikdy pøedtím!*}
# female [1X - 3X]
{2251}{}{*No tak, zlato... zkus to ještì jednou... chytni tu páku... pevnì ji stiskni... no ták...*}
{2252}{}{*To je ono, zlato... zatáhni za tu páku... rychleji, více, rychleji... no ták...*}
{2253}{}{*Áách! To je ono, zlato! Ještì jednou! A tentokrát zatáhni poøádnì! Poøádnì!*}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{2280}{}{(Vidíš hrací automat. Jeho naleštìnı povrch a pozlacená páka svádivì záøí pod blikajícími svìtly New Rena. Štìrbina na mince tì pøitahuje a ty cítíš, jak se ti ruce chvìjí nedoèkavostí. Jak na ten stroj zíráš, jedno z jeho tøí oèí na tebe mrkne. Slyšíš jemnı hlas vycházející ze štìrbiny na mince.) *A hele! Nazdááárek, zlato. Chceš se pobavit?*}
{2281}{}{(Vidíš hrací automat. Jeho bytelná skøíò a pozlacená páka záøí pod svìtly New Rena jako sluníèko. Štìrbina na mince tì pøitahuje a ty cítíš, jak se ti ruce chvìjí nedoèkavostí. Jak na ten stroj zíráš, slyšíš drsnı muskı šepot linoucí se ze štìrbiny na mince.) *Takovouhle koèku jsem tady ještì nevidìl. Chceš se pobavit?*}
{2282}{}{::Štípnout se, jestli se ti to jenom nezdá::}
{2283}{}{Ehm... ahoj?}
{2284}{}{::Zhluboka se nadechnout a odejít.::}

# 14. DRUNK CONVERSATION 1 (13)
{2300}{}{*Jsem tu poøád, krásko.* (Automat sníí hlas.) *Tak pojï, jdeme na to... chceš si zahrát?*}
{2301}{}{*Joo, jsem tu poøád, zlato.* (Automat sníí hlas.) *Víš, e jsi poøádnej kus chlapa? Tak pojï... nechceš do mì strèit nìjaké mince?*}
{2302}{}{Co *jseš* zaèè?}
{2303}{}{*Hik* Jasssnììì e chci hrádd.}
{2304}{}{Myslím, e toho radìji nechám, ne do tebe strèím nìco, èeho budu pozdìji litovat. [Odejít]}
{2305}{}{::Zhluboka se nadechnout a odejít.:: [Odejít]}

# 15. DRUNK 2 (14)
{2320}{}{*Jsem tvùj ideální mu.* (Automat na tebe mrkne.) *Dej mi pár mincí a já tì uspokojím tak, jako to ještì ádnı jinı mu pøedtím NIKDY nedokázal.*}
{2321}{}{*Jsem tvoje ideální ena, zlato. Chci jen trochu pozornosti. Pomùeš mi? No ták, jenom pár mincí.*}
{2322}{}{Co takchle si jen povídad?}

# 16. DRUNK 3 (15)
{2340}{}{*To samozøejmì mùeme, zlato.* (Automat se zatváøí soucitnì.) *Copak trápí tu tvoji krásnou hlavièku?*}
{2341}{}{*To samozøejmì mùeme, zlato.* (Automat se zatváøí soucitnì.) *Copak tì trápí, fešáku?*}
{2342}{}{Já chybìt MÁMA a Arroyo a... nemùšu najíd GECK a... *smrk*}
{2343}{}{Já chybìt MÁMA a Arroyo bıt NAPADNOUD a... já nevìdìd, gde bıt... a... *smrk*}
{2344}{}{Já muset spravit véélikou loï... a vùbec nevìdìd JAG... a m-m-moje MÁMA bıt pryè a... *smrk*}
{2345}{}{Dohrál jsem tudle hru... a te se jen potulujù... a bojím se, e je POFŠEM a... *smrk*}
{2346}{}{Já jen, e Faloud dvì nepotporuje moji tøi dé efix kartu, za kerou jsem vyhodil tolik p-penìz a *smrk*}
{2347}{}{chtìl jsem si udìlat dobrou p-p-postavu, ale nìják jsem si špatnì rosdìlil body... a te mám postavu na houno... *smrk*}
{2348}{}{povídám si tady s hracím auto-ma-matem. U sem asi to-ta-tálnì mimo.}

# 17. DRUNK 4 (16)
{2370}{}{*Ale no ták... tak u tím netrap tu svoji roztomilou hlavièku... já se o všechno postarám. No tak, odpoèiò si a vyzpovídej se.*}
{2371}{}{*Ale no ták... tak u se tím netrap, zlato... já se o všechno postarám. No tak, opøi si o mì tu svoji hezkou hlavièku a vyzpovídej se.*}
{2372}{}{Díky, hrací automate. *smrk* Jseš nejlepèí.}
{2373}{}{Tys jediná *hodná* osoba, kerou jsem gdy podkal. Kadej mì jenom chce *ublíšit* nebo okrásd a... *smrk*}

# 18. DRUNK 5 (17)
{2380}{}{*Budeš v poøádku, zlato? Nechci tì nìkam pouštìt v takovém stavu.*}
{2381}{}{(Opøeš o automat svou tìkou hlavu.)}
{2382}{}{*Budeš v poøádku, zlato? Nechci tì nìkam pouštìt v takovém stavu.*}
{2383}{}{Já budu f pohodì... dík za rozhovor, automate, mám tì rát.}

# 19. DRUNK 6 (18)
{2400}{}{*Jsi asi jediná hrdinka v tomhle hrozném svìtì zlodìjù a vrahù! Dávej na sebe pozor, ano zlato?* (Otoèí se.) *Radìji u jdi, ne se zaènu chovat jako baba.*}
{2401}{}{(Zdá se ti, e se v jednom z jeho oken objeví slza.) }
{2402}{}{*Jsi asi jedinı hrdina v tomhle hrozném svìtì zlodìjù a vrahù! Ty... ty... dávej na sebe pozor, ano zlato?* (Otoèí se.) *Radìji u jdi, ne zaènu plakat.*}
{2403}{}{Sbohééém.}

# rollin' messages
{3000}{}{No tak, }
{3001}{}{! Dìti potøebujou novı boty!}
{3002}{}{! Tatínek potøebuje novou plazmovou pušku!}

# can't play
{4000}{}{Zdá se, e nìkdo blokuje automat.}

{5000}{}{Pouít fintu na hrací automat, aby vyklopil všechny peníze.}
{5001}{}{Automat jako by na chvíli zamrzne a poté uslyšíš slabé zarachocení v momentì, kdy se lavina mincí zaèíná valit ze zásobníku.}
{5002}{}{[Sebrat peníze a odejít]}
