# The following dialog lines were pulled from these files, which are now blank:
# DEMODOG
# DOG2
# DOGMEAT
# JUNKDOG
###############################################################################
#
# DEMODOG.MSG
#
{100}{}{Tu vois un chien. On dirait qu'il te suit.}
{101}{}{Tu vois un chien.}
{102}{}{Wouf !}
{103}{}{Grrr !}
{104}{}{Il semblerait que tu t'es lié d'amitié avec ce chien.}
{105}{}{Tu gagnes 200 points d'expérience pour avoir fait ami-ami avec le chien.}
{106}{}{Tu gagnes 335 points d'expérience pour avoir vaincu le chien et permis à Phil de rentrer chez lui.}
#
# DOG2.MSG
#
{107}{}{Viens ici, mon gars.}
{108}{}{Ruff. Ruff.}
{109}{}{Tu ne sais pas trop pourquoi, mais ce chien semble t'apprécier.}
#
# DOGMEAT.MSG
#
{110}{}{Voici Canigou.}
{111}{}{Arf ! Arf Arf ! Arf ! Arf ! Arf ! Arf ! Arf ! Arf !}
{112}{}{[Sniff. Sniff.] Grrrr ! Snarl !}
{113}{}{[Sniff. Sniff] Wouf !}
#
# JUNKDOG.MSG
#
{114}{}{ points d'expérience pour avoir aidé Phil à résoudre son dilemme canin.}
{115}{}{Le chien semble penser que tu es son propriétaire.}
{116}{}{ points d'expérience pour avoir aidé Phil à résoudre son dilemme canin.}
{117}{}{Wouf-wouf !}
{118}{}{Allez, viens, p'tit gars.}
{119}{}{Reste ici et attends-moi, ok ?}
{120}{}{Bon chien.}
{121}{}{Chiot !!!}
{122}{}{Wouf ?}
{123}{}{Arf ?}
#
# for Fallout Fixt:
#
#
# for Stupid characters (INT <= 3)
{300}{}{Toutou !! Toutou être ami ?}
{301}{}{Toutou assis ! Pas bouger !}
{304}{}{Gentil toutou !}
#
#Normal INT
{302}{}{Pousse-toi un peu, mon gars. Bon chien.}
#
# space is intentional
{303}{}{ sale clébard !}

