{100}{}{Voici Mitch du Grand Bazar.}
{101}{}{Je peux t'aider ?}
{102}{}{Je voudrais acheter quelque chose.}
{103}{}{Je voudrais vendre quelque chose.}
{104}{}{Rien. Merci.}
{105}{}{Zou.}
{106}{}{Très bien. Voici ce que j'ai en rayon.}
{107}{}{Très bien, je suis toujours à l'affût des nouveautés.}
{108}{}{Désolé mais je ne comprends rien. Repasse quand tu auras appris le français.}
{109}{}{Merci. A bientôt.}
{110}{}{Voici Jake, le Trafiquant d'Armes.}
