{100}{}{Voici Andrew, le gardien de prison.}
{101}{}{C'est bon, tu peux y aller maintenant.}
{102}{}{Hé ! Toi ! Reste où tu es !}
{103}{}{Qu'est-ce que tu veux ?}
{104}{}{Qui es-tu ?}
{105}{}{Que fais-tu ?}
{106}{}{Non merci.}
{107}{}{Je m'appelle Andrew. Je suis le gardien de la prison.}
{108}{}{Je garde la prison. J'empêche cette racaille de rentrer et de sortir.}
{109}{}{A quoi ça sert d'empêcher les gens d'entrer à l'intérieur de la prison ?}
{110}{}{Oh.}
{111}{}{Bonne journée. Et ne t'attire pas d'ennuis !}
{112}{}{Quelqu'un peut vouloir aider un prisonnier à s'évader en déposant quelque chose. Ou bien chercher à se laisser enfermer à l'intérieur et y rester jusqu'à ce nous ayions trouvé les clés.}
{113}{}{Ben !}
{114}{}{Circule, mec.}
{115}{}{Circulez, mademoiselle.}
{116}{}{Hé ! Suffit !}
