{100}{}{Tu as mis Barry en colère !}
{101}{}{Voici Barry.}
{102}{}{Hé ! Y'a que les Goules qui ont leur ration d'eau.}
{103}{}{T'aurais pas dû me réveiller. Tu vas passer un sale quart d'heure !}
{104}{}{Le mutant fait comme si tu n'étais pas là.}

{1000}{}{Puce}
{1001}{}{Nécropolis}
{1002}{}{Set}
{1003}{}{Réservoir}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Goules}
{1007}{}{Normaux}

{1100}{}{Ch'sais pas.}
{1101}{}{T'es en plein d'dans.}
{1102}{}{C'est qu'une tapette. Faut se débarrasser de lui et de ses Goules.}
{1103}{}{C'est ici.}
{1104}{}{Ch'sais pas.}
{1105}{}{Lui être chef à Harry.}
{1106}{}{Mauviettes.}
{1107}{}{Plus mauviettes que les Goules.}
