{100}{}{Tu vois : Un marchand des Sables Ombragés.}
{101}{}{Salut wastelander ! J'échange et je vends des marchandises aux bonnes âmes des Sables Ombragés. Tu veux faire du commerce ?}
{102}{}{Oui.}
{103}{}{Non.}
{104}{}{Nous sommes en proie à des radscorpions depuis quelques temps. Tous ceux envoyés pour détruire ces monstres ne sont jamais revenus. Je te donnerai des armes si tu vas jusqu'à leur repaire et que tu t'en débarrasses.}
{105}{}{Ca me semble bien.}
{106}{}{Non merci.}
{107}{}{C'est une honte. Va-t'en.}
{108}{}{Excellent. Parles-en à Seth, il te guidera jusqu'à leur repaire. Prends ça, ça pourrait être utile.}
{109}{}{S'il te plaît, aide-nous dès que tu le pourras. C'est urgent.}
{110}{}{Je ne parle pas aux gens de ton espèce, étranger.}
{111}{}{Merci de nous avoir débarrassés des radscorpions, étranger.}
#
# by Sduibek for Fallout Fixt:
#
{112}{}{Tu vois un marchand.}
{113}{}{Je n'ai pas l'intention de te parler tant que tu ne ranges pas ton arme.}
