{100}{}{Voici Billy.}
{101}{}{Salut.}
{102}{}{Salut. Qu'est-ce que tu fais ?}
{103}{}{Est-ce que je peux avoir une brahmine ?}
{104}{}{Salut. Euh, au revoir.}
{105}{}{Ah !}
{106}{}{Salut.}
{107}{}{Qu'est-ce que tu pourrais bien faire d'une brahmine ? T'as une caravane ? Bon, peu importe. Elles appartiennent à Dan et il ne voudra pas t'en vendre.}
{108}{}{Pourquoi ?}
{109}{}{C'était une blague.}
{110}{}{A cause de toutes les caravanes disparues. Il n'en a aucune de disponible, la plupart servent pour les caravanes et les autres sont vendues pour la viande. Bon, j'ferais mieux de la fermer parce que Dan va encore se mettre en pétard s'il me voit causer à quelqu'un qu'est pas du coin.}
{111}{}{Ah bon.}
{112}{}{Rien... Je veux dire.... Je m'occupe des brahmines.}
{113}{}{A quoi sert la lance ? Elles sont dangereuses ?}
{114}{}{C'est quoi une brahmine ?}
{115}{}{C'est quoi une brahmine ? Tu plaisantes ? Elles servent principalement au transport des caravanes et à la bouffe. Dan dit que c'est un boulot important, mais je ne suis pas d'accord.}
{116}{}{Oh, ça je savais !}
{117}{}{Dan a raison. Tu fais du bon boulot.}
{118}{}{Ouais, on dirait. Amuse-toi bien.}
{119}{}{Hé, tu es un de ces skags, pas vrai ?}
{120}{}{Vraiment ? Tu crois ça ? Ah, ben ça alors ! Merci.}
{121}{}{T'es pas d'ici, toi ? Un bon conseil : t'as pas intérêt à te faire prendre la main dans le sac !}
{122}{}{Ouais, merci.}
{123}{}{Je vois pas pourquoi je volerais. C'est pas bien.}
{124}{}{Ouais. Finalement, t'as p't-être raison. En fait, ce boulot, il n'est pas si mal. Y'a même certains trucs qui me plaisent. Bon, je ferais mieux d'y aller pour pas avoir d'ennuis.}
{125}{}{Je t'en prie épargne-nous, ma brahmine et moi. }
{126}{}{Ne me fais pas de mal !}
{127}{}{Arrête !}
{128}{}{S'il te plaît, fous-moi la paix.}
{129}{}{Tu me fais peur.}
{130}{}{Hé, qu'est-ce que tu essaies de faire ? Je n'ai rien à te donner.}
{131}{}{Arrête !}
{132}{}{Dangereuses ? Non, pas vraiment. Elles sont capables de mordre mais en général, elles sont calmes. Elles font que péter et roter. Je ne sais pas pourquoi.}
{133}{}{Alors, à quoi sert la lance ?}
{134}{}{D'accord, merci.}
{135}{}{Oh, elles sont horriblement têtues. Je leur donne juste un petit coup de cravache pour les faire avancer... Et puis je ne m'en approche pas trop parce qu'elles donnent parfois des coups de pied.}
{136}{}{S'il te plaît, ne me parle pas. Dan va encore me crier après. Il pète les plombs... J'veux dire, il se met en colère, quand je ne fais pas attention à ce que je fais.}
{137}{}{Il essaie simplement de t'aider. Travaille dur et il sera sûrement plus sympa.}
{138}{}{Tiens, prends ces 50 caps et barre-toi d'ici.}
{139}{}{D'accord.}
{140}{}{Aaaaaah !}
{141}{}{Hein ?}
{142}{}{S'il te plaît, non. J'ai assez de problèmes comme ça.}
{143}{}{Mais je travaille dur !}
{144}{}{Excuse, c'est pas ce que je voulais dire. Il veut seulement t'aider.}
{145}{}{Non, c'est pas vrai. Tu n'es qu'un gros flemmard !}
{146}{}{D'accord. }
{147}{}{Ouais, t'as p't-être raison... En fait, il paraît sympa mais j'aimerais bien qu'il arrête de me crier dessus.}
{148}{}{Ouais, c'est vrai.}
{149}{}{Va donc, vieux blaireau !}
{150}{}{Va donc, vieux chameau !}
{151}{}{OUAH ! J'en ai pour au moins jusqu'à la fin de ma vie ! Merci beaucoup, m'sieur !}
{152}{}{OUAH ! J'en ai pour au moins jusqu'à la fin de ma vie ! Merci beaucoup, m'dame !}
{153}{}{OUAH ! Merci... Bon... ? Tu essaies de m'attirer des ennuis !}
{154}{}{Je t'en prie, ne me parle pas, Dan est vraiment taré.}
{155}{}{T'en fais pas. Je lui ai parlé. Il sera plus gentil avec toi.}
{156}{}{Et comment ! T'es vraiment infernal !}
{157}{}{Ouac.}
{158}{}{Salut !}
{159}{}{Ces filles là-bas, qu'est-ce qu'elles sont bêtes !}
{160}{}{Salut.}
{161}{}{Les brahmines sont sympa.}
{162}{}{Dan m'emmènera au Faucon si je travaille bien.}
{163}{}{Un jour, Dan m'emmènera avec lui sur la caravane !}
{164}{}{Plus tard, je serai aventurier.}
{165}{}{Vraiment ? Ah, d'accord. J'espère que tu ne lui as fait aucun mal. Il n'est pas si méchant. Il braille un peu trop, c'est tout.}
{166}{}{Salut.}
{167}{}{Qu'est-ce qui t'arrive, encore ?}
{168}{}{Est-ce que je peux avoir une brahmine ?}
{169}{}{Je ne fais que regarder, c'est tout. Salut.}
{170}{}{Arg !}
{171}{}{Salut.}
{172}{}{J'ferais mieux de retourner au boulot.}
{173}{}{Ces filles là-bas, qu'est-ce qu'elles sont bêtes !}
{174}{}{Salut.}
{175}{}{Plus tard, je serai aventurier.}
{176}{}{Les brahmines, ça chie partout... Enfin, j'veux dire que ça fait beaucoup de crottes.}
{177}{}{Je ne peux pas discuter maintenant.}
{178}{}{Je ne veux pas avoir d'ennuis.}
