{100}{}{Tu vois une femme séduisante en blouse de docteur.}
{101}{}{Voici Lorri, médecin en chef du service médical de la Confrérie.}
{102}{}{Bonjour, en quoi puis-je t'aider ?}
{103}{}{Je suis blessé.}
{104}{}{J'ai subi une irradiation.}
{105}{}{Pratiques-tu des opérations ?}
{106}{}{Parle moi encore des opérations.}
{107}{}{Tu peux m'arranger ?}
{108}{}{Tu es blessé ? Laisse moi regarder ça..}
{109}{}{C'était le problème, c'est arrangé. Sois plus prudent à l'avenir.}
{110}{}{Je ne peux pas t'aider si tu ne me dis pas quel est le problème, désolé.}
{111}{}{Tu sembles en bonne santé.}
{112}{}{Et voilà ! j'espère que tu te sens mieux.}
{113}{}{J'ai fini, mais essaie d'éviter les combats à l'avenir.}
{114}{}{Ca devrait le faire !}
{115}{}{Comme neuf !}
{116}{}{Tout va pour le mieux !}
{117}{}{Les radiations sont très dangereuses ; tu devrais faire plus attention.}
{118}{}{J'ai pas de temps à perdre.}
{119}{}{Bien sûr, mais c'est très cher et demande beaucoup de temps.}
{120}{}{Donne moi les détails.}
{121}{}{Ok, tant pis.}
#
# 122 for Fallout Fixt if using Full install and/or Charimsa operation enabled:
{122}{}{Eh bien, je peux te rendre plus fort, développer ta perception et ton agilité, augmenter ton endurance ou encore améliorer tes facultés mentales. J'ai également étudié la chirurgie esthétique. Sur quoi en particulier aimerais-tu plus d' informations ?}
#
# 222 is with "Bug Fixes Only" enabled, or Charisma operation disabled. Same message as VANILLA:
{222}{}{Eh bien, je peux te rendre plus fort, développer ta perception et ton agilité, augmenter ton endurance ou encore améliorer tes facultés mentales. Sur quoi en particulier aimerais-tu plus d'informations ?}
{124}{}{Qui es-tu ?}
{125}{}{Je m'appelle Lorri, je dirige l'équipe médicale et supervise toutes les interventions chirurgicales importantes et procédures médicales. En fait je suis le seul docteur ici, à vrai dire. Et tu es ?}
{126}{}{Très bien, de quelle opération aimerais-tu discuter ?}
{127}{}{La force.}
{128}{}{La perception.}
{129}{}{L'endurance.}
{123}{}{Le charisme.}
{130}{}{L'intelligence.}
{131}{}{L'agilité.}
{132}{}{Oublie ça.}
{133}{}{C'est facilement réalisable mais le temps de récupération est long. Ca coute seulement }
{134}{}{Je suis }
{135}{}{Je le ferai !}
{136}{}{Je passe mon tour.}
{137}{}{C'est une opération délicate qui coute }
#
# TRANSLATION NOTE: Player's name will be inserted after line 138. Then appends 152 and 142.
#                   Brotherhood of Steel calls everyone "Brother ____", even females.
#
{138}{}{C'est un plaisir de faire ta connaissance, Frère }
#
{139}{}{Celle-ci n'est pas très difficile et prends une semaine environ. Ca coutera }
{140}{}{Je souffre d'un empoisonnement !}
{141}{}{C'est la plus compliquée et dangereuse ! Ca prendra 3 semaines et coute }
{142}{}{Que puis-je pour toi ?}
{143}{}{Ce n'est pas l'opération la plus pénible mais elle est très chère et demande beaucoup de temps. Tu en auras pour 3 semaines et }
{144}{}{[Continue]}
{145}{}{Cette opération est moyennement dure mais entraine un long rétablissement. Ca fera }
{146}{}{Ok, c'est parti. J'espère que tu n'es pas allergique à la mousse.}
{147}{}{Je ne peux rien faire pour toi si tu n'as pas l'argent, désolé.}
{148}{}{Tu es un étranger, désolé. Avec dix ans d'ancienneté au sein de la Confrérie je pourrais envisager de t’opérer gratuitement, mais nous avons des frais et tu n'es même pas un membre à part entière.}
{149}{}{Fais moi savoir quand tu auras trouvé l'argent pour cette opération.}
{150}{}{Je ne peux pas évaluer avec précision ta force physique tant que tu portes cette armure. Retire la et parle moi à nouveau }
#
#TRANSLATION NOTE: Player's name will be inserted between lines 151 and 152.
#
{151}{}{Je suis }
{152}{}{.}
#
{153}{}{Veux tu en savoir plus sur une autre ?}
#
# 155 and 157 are for stupid characters.
#
{155}{}{Mon ventre me fait mal !}
{157}{}{Heu ?}
{158}{}{Rebonjour, je peux t'aider ?}
#
#STRENGTH
{154}{}{Ok, ça fait rien... je plaisantais. On peut y aller. (Tu respires dans le masque et tu t'endors profondément)}
{156}{}{Alors, comment on se sent ? (Tu peux déjà sentir la différence) Tu parles pas mal pendant ton sommeil. Tu peux y aller. Bonne journée.}
#
#PERCEPTION
{159}{}{Faire du neuf avec du vieux... où sont mes pinces ? (Tu t'endors comme une pierre)}
{161}{}{Hmm, tu sembles exactement pareil... Comment tu te sens ? (Tes sens semblent bien plus aiguisés) Bon, il faut libérer la place. Bonne journée.}
#
#ENDURANCE
#Translation: "fall under" meaning fade into unconsciousness under the effect of the anesthetic
{164}{}{J'espère que tu as un bon cœur... (Elle te fait un clin d’œil tandis que tu t'endors)}
{166}{}{Bien, un vrai colosse ! (Tu te sens en pleine forme) Fais moi savoir si il y a des complications, et ne nage pas avant au moins une heure !}
#
#CHARISMA
{180}{}{J'espère que tu ne finiras pas borgne comme le dernier... (Tu luttes en vain contre les drogues)}
{181}{}{Tu es resplendissant ! Je me suis vraiment surpassée cette fois... (Elle te regarde de haut en bas à plusieurs reprises puis retrouve ses esprits) Oh, excuse moi, tu peux y aller !}
#182 and 185 are said by player:
{182}{}{Merci !}
{185}{}{Pas aussi resplendissant que toi.}
#
#INTELLIGENCE
{168}{}{Bon, où est le cerveau déjà ? Et qu'est-ce que c'est que ce truc... (Tu luttes en vain pour ne pas t'endormir)}
{170}{}{Bien, on dirait que j'ai tout remis en place. Tout semble marcher parfaitement. (Tes pensées sont claires et tes souvenirs sont plus nets.)}
#
#AGILITY
{174}{}{C'est partit pour un tour ! Essaie de pas flancher. (Les drogues font effet et tu t'endors rapidement)}
{176}{}{Et voilà, prêt à l'emploi ! (Tu bouges tes jambes et ressent une puissance nouvelle) Tout ce que je te demande est de ne pas abîmer mon chef-d’œuvre.}
#
# NOT Lorri
#
{200}{}{Tu vois un auxiliaire médical.}
{233}{}{ caps mais nécessite 3 semaines de soin.}
{237}{}{ caps et le rétablissement pour cette opération n'est que d'une semaine.}
{239}{}{ caps.}
{241}{}{ caps.}
{243}{}{ caps.}
{245}{}{ caps et nécessite 3 semaines de soin.}
{279}{}{Tu devrais voir le docteur.}
{280}{}{C'est elle le médecin, pas moi.}
{281}{}{Je suis en formation.}
{282}{}{Je ne peux pas t'aider.}
{283}{}{Lorri est le médecin.}
{284}{}{Demande au médecin.}
{285}{}{Ne t'inquiète pas, c'est juste une blagueuse.}
{286}{}{Elle aime bien taquiner, ne t'en fais pas.}
#
# Stat is already maxxed:
{500}{}{Je suis désolé mais cette opération ne t'aidera pas.}
#
{400}{}{Hmm. Si quelqu'un ici en a besoin c'est bien toi. Je te le ferai pour 3000 caps au lieu des 6000 que coûte normalement l'opération. Je peux pas garantir que ça t'aidera mais je pense que ça vaut le coup d'essayer. Ca prendra 3 semaines. Ca m'étonnerait que tu comprennes de quoi je parle de toute façon ?}
{401}{}{Moi vouloir Intelligence}
{402}{}{Pas vouloir ! Doc' faire peur...}
{403}{}{Très bien. Es-tu blessé ou irradié ? Je t'aiderai si je peux.}
{404}{}{Moi blessé.}
{405}{}{Rad !}
{406}{}{Non-on.}
{407}{}{Tu es réveillé, voyons ça... te sens tu plus intelligent ?}
{408}{}{Hein ?}
{409}{}{Oui !}
{410}{}{Zut ! c'est un échec. Je n'avais pas beaucoup pour travailler, il faut dire. Navré mais tu es idiot et le restera toujours. On ne peut pratiquer cette opération qu'une fois, désolé de te dire ça.}
{411}{}{Fantastique, ça a marché ! J'ai pu ramener ton QI à un niveau raisonnable. Quel effet ça fait d'avoir un demi-cerveau ?}
{412}{}{C'est super, merci doc. Au revoir.}
{413}{}{Et voilà, tout va bien.}
#
# Fallout Fixt, by Sduibek:
#
#Bionic Man, UNUSED:
{502}{}{Quelles autres opérations pratiques-tu ?}
{503}{}{Eh bien, je ne suis pas censée parler de ça mais effectivement nous avons d'autres opérations disponibles. Je te préviens, certaines sont très dangereuses et ont un risque d'effets secondaires, d'autres sont moins contraignantes mais ont un temps de récupération très important. Tu veux plus d'information ?}
#Poison examine
{504}{}{Ah, voyons voir...}
#
#Sex
#
{300}{}{Mignon... mais je passe mon tour. Reviens si tu as besoin de soins.}
{301}{}{Ne le prend pas mal chéri mais tu es un cran en dessous de mes standards habituels.}
{302}{}{Oh, merci. (Elle rougit) Je ne reçois pas souvent de compliment. Etre docteur pour la Confrérie est un boulot stressant et ingrat la plupart du temps. J'aime plaisanter pour me changer les idées et rester positive.}
{303}{}{Je comprends. Tu devrais décompresser de temps en temps.}
{304}{}{Je t'en prie. Au-revoir !}
{305}{}{Eh bien... c'est vrai que je me sens seule parfois et "temps libre" ne fait pas vraiment partie du langage pour l'unique médecin de la Confrérie. Qu'est-ce que je raconte... c'est stupide.}
{306}{}{Tiens toi le pour dit ! Sois fière de ton travail et le reste suivra.}
{307}{}{La vie est courte. Tu ne veux pas en profiter tant qu'elle dure ?}
{308}{}{Je trouve pas ça bête du tout. (Tu caresses son visage, te penche vers elle et l'embrasse)}
{309}{}{Oui, tu as surement raison... (Elle secoue la tête en soupirant, puis te sourit) Allez, au boulot ! Merci pour le compliment.}
{310}{}{(Elle réfléchit un moment) Tu as raison, et c'est ce que je vais faire ! Donne moi dix minutes - je dois préparer la table. (Elle sourit malicieusement et mordille sa lèvre) }
{311}{}{(Elle prend ta main et te conduis à sa chambre...)}
{312}{}{C'était si beau, je... je suis amoureuse de toi. (Elle glousse) Je te fais marcher ! Il est temps de partir, j'ai du boulot qui m'attend.}
{313}{}{Whoa, j'ai pas pris mon pied comme ça depuis des années ! Je vais mettre une semaine à m'en remettre mais ça valait le coup. (Elle te regarde avec envie) Remettons-ça vite !}
{315}{}{Sans aucun doute. A bientôt.}
{314}{}{Salut beauté On remet ça ?}
{316}{}{Qu'est-ce que tu fa... (D'abord surprise, elle fond rapidement sous ton étreinte et t'embrasse tendrement en retour, gémissant doucement. Comme tes caresses se font plus fougueuses, elle s'arrête et s'éloigne) Viens avec moi. (Elle te conduis à ses quartiers...)}
{317}{}{Oui ! Tu me fais sentir si belle et désirée.}
{318}{}{(Elle sourit et prends ta main...)}
{319}{}{Eh bien, j'ai vraiment besoin de réviser mes cours d'anatomie... (Elle te fais un clin d’œil)}
