{100}{}{Voici un jeune initié à l'air sévère qui tient un livre.}
{101}{}{Voici l'Initié Brenden.}
{102}{}{Bonjour. Je peux t'aider ?}
{103}{}{Je cherche le Grand Scribe Vree.}
{104}{}{Je cherche le Général Maxson.}
{105}{}{Je cherche le Paladin Rhombus.}
{106}{}{Qu'est-ce que tu lis ?}
{107}{}{Bouhh.}
{108}{}{Hmm. Apparemment, je ne peux t'être d'aucune aide.}
{109}{}{Le Grand Scribe Vree est au troisième, dans le labo informatique.}
{110}{}{Le Général Maxson se trouve habituellement au quatrième, dans les chambres du conseil.}
{111}{}{Le Paladin Rhombus passe la majeure partie de son temps au premier, dans la pièce réservée au matériel.}
{112}{}{Je peux t'être utile à autre chose ?}
{113}{}{Merci. Bonne journée.}
{114}{}{En fait, je tiens un journal. Je travaille à un traité sur la dynamique sociale de la Confrérie.}
{115}{}{Hmm. Ca paraît intéressant.}
{116}{}{Pour quoi faire ?}
{117}{}{En effet. J'effectue des recherches sur nos prédécesseurs d'avant la guerre et sur les sociétés du monde extérieur. Je pense que la Confrérie a beaucoup de similitudes avec l'ordre des Templiers du prétendu "Age Noir".}
{118}{}{Pourquoi as-tu décidé d'étudier cela ?}
{119}{}{Les Templiers ?}
{120}{}{Bien que la Confrérie mette davantage l'accent sur les sciences appliquées, peu de choses ont été réalisées en matière de sciences humaines, telles que la psychologie et la sociologie. Pour une éducation harmonieuse, nous devons nous efforcer de toujours appliquer une pensée scientifique à toute chose.}
{121}{}{Et alors, qu'est-ce que t'as découvert ?}
{122}{}{Je suis parvenu à la conclusion que la Confrérie fonctionne avant tout comme une organisation pseudo religieuse. On est en présence d'une forte hiérarchie militaire, associée à des codes d'honneur transmis de génération en génération. Compte tenu de notre savoir-faire technologique, je pense qu'on peut envisager deux orientations possibles en ce qui concerne la Confrérie : une dictature techno-religieuse ou une société de recherche bénévole.}
{123}{}{Qu'est-ce qui pourrait influencer le développement de la Confrérie ?}
{124}{}{En définitive, nous sommes en présence d'une structure du pouvoir très hiérarchisée et dominée par les Anciens. Les postes les plus influents, je disais donc, étant occupés par les Anciens et par les Aînés. Un Aîné suffisamment charismatique pourrait tout à fait prendre la tête de la Confrérie. Nous devons veiller à ce que notre dirigeant soit à la fois homme de trempe et visionnaire. Par bonheur, je pense que ce Général Maxson possède toutes les qualités requises.}
{125}{}{D'après mes recherches, les Templiers étaient une confrérie militaire axée sur l'accumulation des richesses et des connaissances. Bien que leur structure ait eu une connotation religieuse, leur quête du Savoir a fait d'eux une organisation séculaire. Je pense que leur organisation aurait été davantage théocratique s'ils avaient témoigné d'un plus vif intérêt à l'accumulation des richesses et la quête du pouvoir, étant donné que l'église de cette époque, pour sa part, se consacrait principalement à la gestion de l'or et des terres.}
{126}{}{Et quel rapport avec la Confrérie ?}
{127}{}{Nous devons absolument comprendre notre passé si nous voulons préparer notre avenir... mais je suis certain que toutes ces choses t'échappent.}
