{100}{}{Tu croises un homme qui te fixe un instant, puis passe son chemin.}
{101}{}{Voici Greg.}
{102}{}{Qu'est-ce qu'il y a ? Pourquoi me parles-tu ? On pourrait nous entendre.}
{103}{}{Salut. T'es de retour ? Mets-la en sourdine, ils sont partout.}
{104}{}{D'accord, mais mets-la en sourdine ; ils vont se charger de nous si tu n'arrêtes pas de gueuler.}
{105}{}{Qui es-tu ?}
{106}{}{Pourquoi ne tiens-tu pas en place ?}
{107}{}{Tu n'as pas pris tes médicaments, toi ! Peut-être même que ta dose n'est pas suffisante !}
{108}{}{Pas grave.}
{109}{}{Je suis...Greg...mais garde ça pour toi ou bien ils vont me retrouver.}
{110}{}{N'importe quoi ! J'fais gaffe, c'est tout. Ils disent tous que je suis parano mais moi, je serai là quand ils viendront nous chercher.}
{111}{}{Venir vous chercher ? Qui va venir vous chercher ?}
{112}{}{T'es vraiment parano ! Salut, à plus !}
{113}{}{Euh, ils...Tu sais bien...Cette maladie, ça n'était qu'un début. Ils vont venir nous prendre tous. Mais toi, t'es comme les autres. Tu veux pas me croire et bientôt, il sera trop tard. Je t'aurai prévenu. MOI, JE SERAI ENCORE LA ET TOUT CA VA DISPARAITRE, TOI COMPRIS. DISPARAITRE. [Greg se saisit la tête et se tord de douleur en hurlant]}
{114}{}{Mes médicaments... Alors, tu es des leurs ; tu essaies de me faire avaler mes médicaments....Tu n'y arriveras pas. JE NE LES PRENDRAI JAMAIS. LES VOIX, NON, JAMAIS, PERSONNE NE ME FORCERA. [Greg ferme les yeux et secoue la tête tout en parlant à des voix que lui seul entend.]}
{115}{}{JE NE ME LAISSERAI PAS FAIRE !}
{116}{}{Y'A RIEN A FAIRE !}
{117}{}{C'EST FINI !}
{118}{}{ILS ARRIVENT ET RIEN NE PEUT LES ARRETER !}
{119}{}{S'EN SERA FINI DE VOUS !}
