{100}{}{Voici un jeune homme très agité.}
{101}{}{Voici Michael.}
{102}{}{Salut ! T'es pas du coin toi, non ? Je peux t'aider ?}
{103}{}{Bonjour ! Je peux t'être utile à quelque chose ?}
{104}{}{Tu peux m'en dire un peu plus sur le Cimetière ?}
{105}{}{Qui es-tu ?}
{106}{}{Pourquoi vivez-vous tous ici ?}
{107}{}{Merci, salut.}
{108}{}{Ok. Au Sud se trouve le Sanctuaire. En allant vers le Nord-Est, tu trouveras les Contrebandiers mais tu devras d'abord passer les Griffemorts pour les atteindre. A l'Ouest se trouvent les Disciples de l'Apocalypse et à l'extrême Sud, j'ai entendu dire qu'il existe une sorte d'église.}
{109}{}{Je m'appelle Michael. Ma femme Christine et moi vivons ici et en tant qu'Ecorcheurs on fait de notre mieux.}
{110}{}{C'est pas aussi terrible que ça en a l'air. Il se peut que les Régulateurs et les Griffemorts posent des problèmes mais notre chef Razor nous a pas mal aidés ces derniers mois. Et MacRae nous a récemment appris à mieux nous défendre.}
{111}{}{Merci de nous avoir débarrassé des Régulateurs du Sanctuaire. Voilà ce qu'on peut te donner. Tu pourrais en avoir besoin en route.}
{112}{}{Pas de problème. Merci pour le matériel.}
{113}{}{Je t'en prie. Garde le matériel pour toi.}
{114}{}{J'insiste.}
{115}{}{[Michael te tend des boîtes de Stimpak et quelques caps]}
{116}{}{Salut ! Bonne route !}
