{100}{}{Voici le chef de la caravane.}
{101}{}{Ca y est, nous y sommes. Voilà ton paiement: }
{102}{}{ caps. [Il sort une vieille bourse et te donne l'argent.] Tu recevras encore }
{103}{}{ caps si tu retournes avec nous au Centre. Nous allons nous reposer ici un moment, mais ne t'éloigne pas trop si tu ne veux pas que la caravane parte sans toi.}
{104}{}{Aaa... Ok.}
{105}{}{Quand est prévu le départ de la caravane ?}
{106}{}{Que peux-tu me dire sur Dépôtville ?}
{107}{}{Que peux-tu me dire sur le Cimetière ?}
{108}{}{Que peux-tu me dire sur la Confrérie de l'Acier ?}
{109}{}{Je ne sais pas si tu vas comprendre, mais nous partons dans deux heures ou dès que tu seras prêt.}
{110}{}{Hum...}
{111}{}{Gnéé ?}
{112}{}{Al..Allez !}
{113}{}{Hé, on emploie de ces débiles en ce moment.}
{114}{}{Nous partons généralement deux heures après notre arrivée. Nous avons tout vu ici, alors, si tu veux partir plus tôt, nous sommes prêts.}
{115}{}{J'aimerais visiter un peu le coin avant de partir. A tout à l'heure.}
{116}{}{Ok. Regagnons le Centre. J'ai plus rien à voir ici.}
{117}{}{Que peux-tu me dire sur Dépôtville ?}
{118}{}{Que peux-tu me dire sur le Cimetière ?}
{119}{}{Que peux-tu me dire sur la Confrérie de l'Acier ?}
{120}{}{Eh bien, ça ressemble un peu au Centre. Il y a pas mal de problèmes: les bandes, les voyous, les voleurs, tu sais... les trucs habituels. En fait, c'est mon genre de ville. [Rires]}
{121}{}{Quand est prévu le départ de la caravane ?}
{122}{}{J'aimerais visiter un peu le coin avant de partir. A tout à l'heure.}
{123}{}{Cette partie du Cimetière s'appelle le Sanctuaire. Le Cimetière est sous le contrôle des gangs. C'est un drôle d'endroit, alors fais attention. Le Sanctuaire est dirigé par les Régulateurs. Ils essaient de limiter les guerres de gangs. Ils sont méfiants à l'égard des étrangers, et à juste titre. Si tu ne leur as pas encore parlé, je te conseille de le faire avant de te promener dans le coin.}
{124}{}{Vide}
{125}{}{Quand est prévu le départ de la caravane ?}
{126}{}{J'aimerais visiter un peu le coin avant de partir. A tout à l'heure.}
{127}{}{Il n'y a pas grand chose à en dire. La Confrérie garde ses secrets. Beaucoup de gens ne les apprécient guère, mais ce sont des gens bien. Un peu fanatiques, peut-être, mais des gens bien quand même.}
{128}{}{Quand est prévu le départ de la caravane ?}
{129}{}{J'aimerais visiter un peu le coin avant de partir. A tout à l'heure.}
{130}{}{Es-tu en mesure de partir maintenant ?}
{131}{}{Al..Allez !}
{132}{}{Non. Je n'ai pas fini de visiter.}
{133}{}{Ouais, on peut y aller.}
{134}{}{Cette partie du Cimetière s'appelle le Sanctuaire. Le Cimetière est sous le contrôle des gangs. C'est un drôle d'endroit, alors fais attention.}
{135}{}{Quand est prévu le départ de la caravane ?}
{136}{}{J'aimerais visiter un peu le coin avant de partir. A tout à l'heure.}
{137}{}{Ok. Tu as réussi. Voici tes }
{138}{}{ caps. Si tu veux encore du travail, va en reparler au chef. J'aimerais bien retravailler avec toi. Je te recommanderai. Ne t'en fais pas.}
{139}{}{Au revoir.}
{140}{}{A bientôt.}
{141}{}{Alors, comment ça va ?}
{142}{}{Si tu veux encore du travail, adresse-toi au chef.}
{143}{}{Il y a quelque chose que ne va pas chez toi.}
{144}{}{T'es taré !}
{145}{}{Je ne travaille pas avec toi !}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{Que peux-tu me dire sur Nécropolis ?}
{150}{}{Eh bien, c'est un satané endroit !}
{151}{}{La caravane est partie.}
{200}{}{Hmmmpf...}
{201}{}{Hmm... Si seulement je savais lire.}
{300}{}{Occupe-toi de tes affaires, s'il te plaît !}
{400}{}{On ne me paie pas pour discuter.}
{501}{}{Dis-moi seulement, pourquoi as tu abandonné cette putain de caravane ? J'ai du mal à le croire ! Tu as de la chance, elles ont finit le voyage sans ton maudit cul terreux ! Fiche le camp ! Et ne crois pas que je vais te payer !}
{502}{}{Je peux pas le croire ! Nous avons perdu toutes ces putains de caravanes ! Fiche le camp ! Et ne crois pas que je vais te payer !}
{504}{}{Va voir le chef et essaie d'imaginer une histoire crédible sur les raisons d'abandon de cette maudite caravane. Peut-être que tu auras ta récompense.}
{505}{}{Je ne peux pas le croire ! Nous avons perdu toutes les caravanes ! Je crois pas que tu seras payé. Va parler au chef.}
{600}{}{Bon alors, nous y voila. Je ne peux pas te payer le prix habituel, étant donné qu'on a perdu pas mal du chargement d'origine. On doit couvrir nos pertes, tu vois. Voilà ton paiement de : }
{601}{}{ caps. (Il tire un très vieux sac de sa poche et te donne l'argent.) Et voilà aussi }
{602}{}{Si tu veux plus de travail, va voir le chef. Il est d'accord pour travailler avec toi une nouvelle fois. A la prochaine.}
{603}{}{ caps. (Il tire un très vieux sac de sa poche et te donne l'argent.) }
{604}{}{D'accord, t'as gagné ! Je peux pas te payer étant donné qu'on a perdu la caravane. On va devoir compenser les pertes. J'aimerais que ce soit différent mais ce sont les règles.}
{605}{}{D'accord, t'as gagné ! Je peux pas te payer étant donné que toutes les brahmines sont mortes. Tu nous as coûté un paquet de fric, l'andouille. Pas de brahmine, pas de caravane, pas d'argent. J'espère qu'ils ne te laisseront plus travailler avec nous.}
#
# Unload caravan quest - WG@RestorationProject
#
{506}{}{Du travail pour moi ?}
{507}{}{Je... suis... travail.}
{508}{}{On a besoin de tes biceps pour décharger la caravane. On te paiera : }
{509}{}{ caps.}
{510}{}{Ouga !}
{511}{}{Non.}
{512}{}{J'y vais.}
{513}{}{J'aime pas ça.}
{520}{}{Tu passe une heure à décharger la caravane. }
{521}{}{Tu aide à décharger la caravane. }
{522}{}{ caps.}
