{100}{}{Voici un Chantre des Enfants.}
{101}{}{Le Maître te pardonnera tes péchés ! Rejoins-nous pour ta libération ! Prie le  Maître et sa miséricorde !}
{102}{}{Bonjour ! La vision du Maître m'a ouvert à la vie pour la première fois. Puis-je partager mon histoire avec toi ?}
{103}{}{Où puis-je rencontrer ce Maître ?}
{104}{}{Je t'écoute.}
{105}{}{Qui s'occupe de cet endroit ?}
{106}{}{La vision du Maître ? Est-ce meilleur que le jus de radscorpion ?}
{107}{}{Se termine-t-elle par la mort ? Si ce n'est pas le cas, je peux changer ça !}
{108}{}{Moi aimer histoires !}
{109}{}{Le Maître est partout ! Le Maître est omniprésent ! Admire cette paix et  cette unité !}
{110}{}{Il était une fois un homme si plein de haine qu'il en mourut presque. Mais maintenant... Gloire au Maître ! Gloire à la Flamme Sacrée ! Gloire au Vignoble de la Vie ! Ah !}
{111}{}{Le Maître est ton guide. Gloire au Maître ! Gloire à la Flamme Sacrée qui éclaire notre chemin !}
{112}{}{La vision du Maître est meilleure que n'importe quelle boisson... elle est meilleure que le sexe ! Ohhhh ! Il transcende le vice et la vertu ! Ahhhh ! Le Maître est un père pour nous tous !}
{113}{}{Aucune histoire ne se terminera par la mort tant que le Maître nous protégera !}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{114}{}{Mais je dois vénérer le Maître ! Au revoir, mon ami ! Je te raconterai mon  histoire plus tard !}
{115}{}{Mais je dois vénérer le Maître ! Au revoir, mon amie ! Je te raconterai mon  histoire plus tard !}
