{100}{}{Cette personne a dû se trouver très proche de l'explosion.}
{101}{}{Ce corps est si carbonisé qu'il est méconnaissable.}
{102}{}{Les vents changeants ont dispersé les cendres.}
{103}{}{Ces dégâts sont probablement dus à l'explosion nucléaire.}
{104}{}{Les cendres glissent à travers tes doigts.}
