{100}{}{Voici un Ténébreux.}
{101}{}{Meurs !}
{102}{}{Laisse-moi ou meurs !}
{103}{}{Je n'aime pas le ton que tu emploies. Si mon message ne parvient pas au Maître, je te réserverai une mort lente et atroce.}
{104}{}{Je voulais juste te complimenter sur la superbe bosse de ton dos. Quant à ta respiration...}
{105}{}{Peux-tu m'indiquer l'homme qui s'occupe de cet endroit ?}
{106}{}{Tu sais, il y a pire que moi !}
{107}{}{Je reste !}
{108}{}{Ok. Je m'en vais.}
{109}{}{C'est une erreur d'affronter les Ténébreux. Va-t-en !}
{110}{}{Je ne pense pas.}
{111}{}{Je prendrai un réel plaisir à te voir mourir !}
{112}{}{Tu écoutes ? C'est déconseillé d'ignorer les Ténébreux.}
{113}{}{Je dois te parler. C'est urgent !}
{114}{}{Personne n'a jamais osé m'accuser d'être sage !}
{115}{}{Je veux juste parler à la personne qui s'occupe de cet endroit !}
{116}{}{Tu es censé être un dur ou quoi ?}
{117}{}{Excuse-moi. Passe une bonne journée.}
{118}{}{Tu te moques de moi ? Tu as tort de te moquer de moi, crevure !}
{119}{}{Monte. Mes amis évalueront l'importance de ton message.}
{120}{}{Dernier avertissement !}
{121}{}{Certainement ! Une bonne affaire...}
{122}{}{Je dois IMPERATIVEMENT parler à la personne qui s'occupe de cet endroit !}
{123}{}{Ok ! Ok ! Excuse-moi ! Passe une bonne journée.}
{124}{}{Tu sais quelle est ton erreur ? Tu donnes des avertissements. Moi, pas. Meurs !}
{125}{}{[Terminé]}
