{100}{}{Voici un homme à la peau mate portant des foulards clairs et des bijoux.}
{101}{}{Voici Chuck, le forain diseur de bonne aventure.}
{102}{}{Salut, toi qui vient d'ailleurs. Puis-je t'aider ?}
{103}{}{Euh !}
{104}{}{Je ne fais que jeter un oeil, merci.}
{105}{}{Je commence à me faire aux gens du Sanctuaire.}
{106}{}{Pourquoi penses-tu que j'ai besoin d'aide ?}
{107}{}{Hmm. Puisque nous sommes entre amis, laisse-moi te dire que de bonnes choses t'attendent.}
{108}{}{Et que penses-tu de notre ville ?}
{109}{}{Ca va.}
{110}{}{Je ne l'aime pas tellement. Elle n'est pas très chaleureuse.}
{111}{}{Tu as fait un excellent travail compte tenu des circonstances hostiles.}
{112}{}{Je m'appelle Chuck. Bienvenue au Sanctuaire. Je crains que la plupart des gens d'ici ne soient pas très sociables avec les étrangers.}
{113}{}{Ouais, je l'ai remarqué.}
{114}{}{Alors, que fais-tu, Chuck ?}
{115}{}{A plus tard, Chuck.}
{116}{}{Promène-toi bien, nomade.}
{117}{}{Nous cherchons tous quelque chose, pas vrai ? Et tu ne m'aurais pas adressé la parole si tu n'avais pas eu besoin de quelque chose, un renseignement, un conseil. Je sais que tu as vécu beaucoup de choses. De quoi as-tu besoin ?}
{118}{}{Euh, je n'ai besoin de rien, merci.}
{119}{}{Eh bien, puisque tu en parles, tu peux peut-être me donner un conseil.}
{120}{}{[Chuck sort un jeu de tarot.] Laisse-moi consulter les cartes. [Chuck mélange les cartes.]}
#
# This is referring to The Glow
#
{121}{}{[Chuck tire une carte représentant un homme vêtu de blanc et une carte représentant un homme en SuperArmure.] Le Pape et le Magicien au Sud... immense sagesse et noblesse attendent au Sud.}
#
# This is referring to the Military Base
#
{122}{}{[Chuck tire une carte représentant un homme avec une vibro-lame et un drapeau.] Le Roi des Epées au Nord... tu dois affronter un redoutable ennemi au Nord.}
#
# This is referring to The Master
#
{123}{}{[Chuck tire une carte représentant une tour radio et une autre représentant un homme en costume avec un spectre.] La Tour et l'Empereur... un grand changement est à venir, dû à un grand leader. Impossible de dire si ceci annonce la mort.}
{124}{}{[Chuck tire une carte représentant un homme dansant sur une ogive nucléaire.] Le Fou. Je ne peux pas t'aider, tu dois te frayer un chemin dans le monde.}
{125}{}{[Suite]}
{126}{}{Hmm. Merci du conseil.}
{127}{}{Tu crois vraiment à ces trucs-là ?!}
{128}{}{Ca marche pour moi. Mais si tu n'y crois pas, ce n'est même pas la peine d'essayer.}
{129}{}{Sans vouloir t'offenser, je pense que ce n'est que de la superstition.}
{130}{}{Eh bien, je vois que nous avons chacun nos croyances.}
{131}{}{Si c'est ce que tu penses, alors il me semble que nous n'avons rien d'autre à nous dire.}
{132}{}{En effet. Ton univers est forgé par tes croyances et le mien par mes pensées. Nous n'avons pas les mêmes croyances, mais je te souhaite beaucoup de bien dans ton univers.}
{133}{}{C'est chez moi.}
{134}{}{Euh, ouais. A plus tard.}
{135}{}{Les choses sont assez calmes dans le coin.}
{136}{}{Je vois ce que tu veux dire. J'ai vu beaucoup de souffrances.}
{137}{}{Les Régulateurs s'en assurent. Le peuple du Sanctuaire souffre parfois de la sévérité de ses propres règles.}
{138}{}{Je suppose. Eh bien, à plus tard.}
{139}{}{Et ça te va ?}
{140}{}{Puisque je veux rester ici, j'accepte que les Régulateurs fassent partie du Sanctuaire. Mais je fais ce que je peux pour éclairer leurs vies.}
{141}{}{Tu n'as pas l'air d'accord avec ce qu'ils font.}
{142}{}{Y-a-t-il autre chose que tu pourrais faire ?}
{143}{}{Les Régulateurs protègent leurs propres intérêts et je dois le respecter.}
{144}{}{Oui, qu'importe.}
{145}{}{Je n'adhère pas nécessairement à cette thèse, mais je la comprends.}
{146}{}{Ce fut une conversation intéressante. A plus tard.}
{147}{}{Eh bien, je suis seul mais je fais de mon mieux pour rendre service. Je te conseille de te battre pour ce en quoi tu crois mais surtout, choisis les batailles qui en valent la peine et trouve le moment où le compromis et l'espoir te permettront de vaincre.}
{148}{}{As-tu d'autres conseils ?}
{149}{}{Le peuple du Sanctuaire a beaucoup à faire un jour ordinaire. Ils ne veulent pas que le travail soit toujours en attente à la fin de la journée.}
{150}{}{Ouais. Eh bien.}
{151}{}{Les choses semblent tranquilles par ici.}
{152}{}{Merci. Cela a été difficile. Nous perdons parfois des gens à cause des Griffemorts, et les hivers peuvent être rudes, notamment lorsque les marchands du Centre ne viennent pas. Mais nous survivons.}
{153}{}{Bonne chance.}
{154}{}{Quel est le problème avec les Griffemorts ?}
{155}{}{Ils infestent la région située au Nord-Est d'ici et peuvent parfois prendre la vie des gens qui doivent traiter avec les Contrebandiers.}
{156}{}{Heureusement, tu vas trouver une solution.}
{157}{}{Ouais. Qu'importe.}
{158}{}{Peut-être. Je pense que le Sanctuaire sera là. Au lieu d'aller au monde, le monde doit venir à nous, comme toi.}
{159}{}{Hmm. Je suppose.}
{160}{}{Je suis fermier. J'aime également travailler sur les bâtiments, les restaurer et les entretenir, et parfois donner des conseils.}
{161}{}{Quel genre de conseil ?}
{162}{}{Oui, malheureusement. Je pense... c'est une sorte de creuset, et pour survivre en ces temps difficiles, nous devons nous entraider et apprendre de nouvelles choses. Je pense que finalement l'humanité s'en sortira très bien.}
{163}{}{Je ne suis pas d'accord. J'ai rencontré de nombreuses bandes et de nombreux pillards au cours de mes voyages. Ils sont maintenant des misérables tueurs et voleurs. Je pense que nous courons tous ce risque.}
{164}{}{Tu as peut-être raison. Ceux qui survivent s'en sortiront certainement mieux.}
{165}{}{Ils finiront peut-être par s'autodétruire. Et ceux qui resteront travailleront ensemble pour survivre, comme nous.}
{166}{}{Je suis heureux que des étrangers, comme toi, ressentent ces choses. Nous devons trouver des façons de construire ensemble des choses nouvelles. Ce n'est pas ici que cela se fera, nous sommes trop surveillés, mais ailleurs.}
{167}{}{Salut. Que puis-je faire pour toi ?}
{168}{}{Puis-je t'aider ?}
{169}{}{Oui ?}
{170}{}{Je voulais simplement dire bonjour.}
{171}{}{J'ai besoin d'un petit conseil.}
{172}{}{Puis-je te demander ce que tu fais dans le coin ?}
{173}{}{Bonjour. J'espère que tu vas bien.}
