{100}{}{Voici Cindy.}
{101}{}{Elle pleure.}
{102}{}{Bonjour, }
{103}{}{. As-tu trouvé la puce d'eau ?}
{104}{}{Pas encore. Je n'ai pas eu beaucoup de chance.}
{105}{}{Je n'ai pas eu de chance jusque-là, mais je sais que je la trouverai. Et toi, comment vas-tu ?}
{106}{}{Eurr !}
{107}{}{Oh... tu ne me comprends pas. Je crois que nous n'avons plus beaucoup d'espoir. Pardonne mes larmes.}
{108}{}{Eurr !}
{109}{}{S'il te plaît, trouve-la avant que l'on ne meurt de soif.}
{110}{}{Tu dois la trouver ! Ne nous laisse pas mourir comme ça !}
{111}{}{Essaie encore. J'ai confiance en toi. Je sais que tu feras ton possible pour nous sauver.}
{112}{}{Qui est impliqué dans cette histoire selon toi ?}
{113}{}{J'ai peur de ce qui va se passer. Quelqu'un a volé l'eau et maintenant tout le monde est sur la brèche.}
{114}{}{Qui a pu faire une chose pareille ?}
{115}{}{Que s'est-il passé ?}
{116}{}{Certaines personnes ont été accusées et des échauffourées ont éclaté, mais personne ne sait rien.}
{117}{}{D'accord. Merci.}
{118}{}{Des gens ont signalé que leur eau avait été volée. Ils n'en ont pas reçu plus, mais des amis ont partagé avec eux. Après ça, tout le monde est devenu complètement paranoïaque et chacun a commencé à surveiller son eau. Quelques jours plus tard, quelqu'un a tabassé le garde dans le secteur de rationnement et a volé de l'eau.}
{119}{}{C'est terrible ! Que puis-je faire ?}
{120}{}{Tu pourras peut-être arrêter le coupable.}
{121}{}{Je vais voir ce que je peux faire.}
{122}{}{C'est toi qui a volé l'eau ?! Comment as-tu pu ?}
{123}{}{Merci infiniment de nous avoir sauvés.}
{124}{}{Maintenant que tu as arrêté le voleur, dépêche-toi de trouver la puce d'eau.}
{125}{}{Comment as-tu pu nous trahir ? Maintenant, tous les gens d'ici vont mourir ! Mais tu t'en moques, n'est-ce pas ?}
{126}{}{J'ai peur. Je ne sais pas ce qui va nous arriver. S'il te plaît, ne nous laisse pas tomber.}
{127}{}{Ne t'inquiète pas, je ferai de mon mieux. Tu vas t'en sortir.}
{128}{}{Ouais, peu importe.}
