{100}{}{Voici un Conducteur de Caravane.}
{101}{}{Excuse-moi, je te connais pas. Si tu veux du travail, adresse-toi à Rutger.}
{102}{}{Si tu veux du travail, adresse-toi plutôt à Rutger.}
{103}{}{Quoi ? As-tu dépensé tout cet argent pour des drogues ? Si tu continues comme ça , les toxicos viendront t'entourer dans ton nouvel habitat, dans la vieille ville.}
{104}{}{Tu ferais bien de désaouler. Reviens quand tu seras en état de travailler.}
{105}{}{Tu cherches un autre travail ?}
{106}{}{Oui.}
{107}{}{Non, peut-être plus tard.}
{108}{}{Goug.}
{109}{}{Rak !}
{110}{}{Prêt pour le départ ? On part aujourd'hui.}
{111}{}{Ouais !}
{112}{}{Non.}
{113}{}{Hein ?}
{114}{}{Excuse-moi mais on ne traitera plus avec toi. Tente ta chance avec une autre caravane, peut-être que quelqu'un voudra de toi.}
{115}{}{Excuse-moi mais on n'embauche pas.}
{116}{}{Tu as un sacré culot de te repointer ici. Il vaudrait mieux que tu partes.}
{117}{}{J'ai dit : fiche le camp !}
{118}{}{Qu'est-ce que tu veux ? On a fait une grosse erreur en t'embauchant.}
{119}{}{S'il te plaît, donne-moi une autre chance ! Je n'avais pas le choix !}
{120}{}{Ah ouais ? Je pourrais m'en moquer.}
{121}{}{Rien. Au revoir.}
{122}{}{Gah.}
{123}{}{Meuh.}
{124}{}{Ecoute, je ne sais pas ce qui s'est passé là-bas, mais on a perdu toute la caravane ! Tu n'aurais pas dû revenir si tu étais incapable de la protéger.}
{125}{}{Pas question, va au diable !}
{126}{}{J'ai dit : va au diable !}
{127}{}{Qu'est-ce que tu veux ?}
{128}{}{Ah, la ferme et fiche le camp !}
{129}{}{Je veux un autre travail.}
{130}{}{Rien.}
{131}{}{Rra.}
{132}{}{Bah.}
{133}{}{Quoi ? Après avoir abandonné ton dernier boulot ? Tu as de la chance qu'ils aient survécu.}
{134}{}{De la chance, moi ? C'est toi qui as de la chance que je t'ai pas encore tordu le cou !}
{135}{}{Hé ! J'avais des trucs à faire et des gens à voir.}
{136}{}{Je savais pas que j'avais pas le droit de partir. Tout avait l'air en ordre.}
{137}{}{Dis ce que t'as à dire et fiche le camp.}
{138}{}{Pauv' type !}
{139}{}{On n'embauche pas les ivrognes.}
{140}{}{On n'embauche pas les amateurs de drogues.}
{141}{}{(Il t'ignore)}
{142}{}{Reviens quand tu seras sobre.}
{143}{}{Espèce de malade. Rentre chez toi.}
{144}{}{Tout avait l'air en ordre ?! On ne quitte jamais une caravane, même si elle n'est qu'à un kilomètre de sa destination. Ton boulot était de la garder pendant tout le trajet, sinon on aurait prit quelqu'un d'autre.}
{145}{}{Eh bien, personne m'a dit que je devais pas partir !}
{146}{}{Excuse-moi, ça se reproduira pas.}
{147}{}{Va te faire voir !}
{148}{}{Quoi ? C'est ta première caravane ou quoi ? Comment as-tu fait pour te faire embaucher ? C'est un travail très délicat et important; c'est à prendre au sérieux. Des vies sont en jeu au sein de la caravane et dans les villes qu'on ravitaille.}
{149}{}{Et tu dois être fier de toi...}
{150}{}{Quoi ? Tu veux peut-être une médaille ?}
{151}{}{Laisse-moi sauver des vies, s'il te plaît ! Je veux rendre service !}
{152}{}{J'espère bien ! C'est un travail très délicat et important ; c'est très sérieux. Des vies sont en jeu ! Les caravanes et les villes que nous ravitaillons comptent sur nous !}
{153}{}{Tu as l'air fier de toi.}
{154}{}{Quoi ? Tu veux peut-être une médaille ?}
{155}{}{Laisse-moi sauver des vies, s'il te plaît ! Je veux aider !}
{156}{}{Bien sûr.}
{157}{}{Alors, puis-je avoir un autre travail ?}
{158}{}{Imbécile !}
{159}{}{Je dois partir. Salut.}
{160}{}{Euh, ouais. C'est un boulot difficile et salissant ! Nous risquons nos vies pour ceux qui sont moins bien lotis.}
{161}{}{FAchète toi une vie ! }
{162}{}{Oh ? Et que fais-tu des gens les moins chanceux qui passent devant toi ?}
{163}{}{Tu as raison. Je peux avoir un autre travail ou quoi ?}
{164}{}{Quoi ? Je sais pas de quoi tu parles ! Oh, tu veux dire les toxicos ? Ils comptent pas. Ils ont choisi de vivre comme ça.}
{165}{}{Je suppose que tu as raison.}
{166}{}{Tu me dégoûtes.}
{167}{}{Je dois partir.}
{168}{}{Quoi ? Qu'est-ce que j'ai dit ?}
{169}{}{Bien sûr. J'ai bon coeur... en général.}
{170}{}{Bien sûr. Je peux avoir un autre travail ou quoi ?}
{171}{}{Je ne suis déjà plus là.}
{172}{}{C'est la bonne attitude ! Malheureusement, je peux pas te confier un autre travail.}
{173}{}{Quoi ? Après tout ça ? Oh, allez ! S'il te plaît, donne-moi un autre travail !}
{174}{}{Bon, on retourne sauver le monde alors.}
{175}{}{Très bien. Mais n'espère pas retravailler pour nous !}
{176}{}{Oh, s'il te plaît ! Ca se reproduira pas !}
{177}{}{Je le voudrais bien !}
{178}{}{Bon, d'accord, je te donne une autre chance. Notre prochaine caravane part }
{179}{}{aujourd'hui}
{180}{}{demain}
{181}{}{le }
{182}{}{8}
{183}{}{18}
{184}{}{28}
{185}{}{. Fais-moi savoir quand tu pourras partir. Le salaire est de 400 caps.}
{186}{}{Excuse-moi, mais j'ai déjà fait une grosse erreur en te donnant ta chance la dernière fois.}
{187}{}{Génial, quelle destination veux-tu prendre ?}
{188}{}{Salut. La caravane ne part pas avant demain. Reviens demain si tu veux encore de ce travail.}
{189}{}{Je ne veux pas de ce travail.}
{190}{}{Je vais essayer.}
{191}{}{D'accord, à plus tard alors.}
{192}{}{Eugh.}
{193}{}{Salut. Tu arrives tôt. Trop tôt. La prochaine caravane ne part pas avant le }
{194}{}{8}
{195}{}{18}
{196}{}{28}
{197}{}{. Reviens à cette date si ça t'intéresse toujours.}
{198}{}{Je ne veux pas de ce travail.}
{199}{}{Je vais essayer.}
{200}{}{D'accord. Au revoir.}
{201}{}{Euh.}
{202}{}{D'accord. Ca m'est égal.}
{203}{}{Ca m'est bien égal que tu te montres ou pas. Il y a des tas de gens qui cherchent du travail de toute façon. Mais si tu es là, c'est d'accord.}
{204}{}{Je te l'ai déjà dit. Ne t'en fais pas. Si tu n'en veux pas, je me débrouillerai.}
{205}{}{La Confrérie de l'Acier}
{206}{}{Le Cimetière de L.A.}
{207}{}{Dépôtville}
{208}{}{Tant pis. Je ne veux pas de ce travail finalement.}
{209}{}{Super ! Tu arrives à temps. Nos caravanes partent aujourd'hui. Le salaire est de 400 caps. Quelle destination veux-tu prendre ?}
{210}{}{Génial. Notre prochaine caravane part le }
{211}{}{8}
{212}{}{18}
{213}{}{28}
{214}{}{. Reviens à cette date et on t'affectera à une caravane. Le salaire est de 400 caps.}
{215}{}{D'accord.}
{216}{}{Excuse-moi, je ne peux pas attendre si longtemps.}
{217}{}{Génial. Je m'occupe du conducteur et du reste de l'équipe. Attention là-bas, c'est de plus en plus dangereux depuis quelque temps.}
{218}{}{L'équipe est prête. On part tout de suite.}
{219}{}{Très bien, ça va prendre quelques minutes pour rassembler l'équipe.}
{220}{}{Très bien. On sera en route pour la Confrérie dès que l'équipe sera au complet.}
{221}{}{D'accord, on sera en route pour la Confrérie dès que j'aurai rassemblé toute l'équipe.}
{222}{}{Prêts ! L'important est de ne surtout pas s'approcher des montagnes.}
{223}{}{Le Cimetière de L.A. est un endroit dangereux. Fais attention. Veille à ce que chacun reste à sa place.}
{224}{}{L'équipe est presque prête. J'ai entendu dire qu'il y avait eu des problèmes autour du Cimetière de L.A. récemment. Fais attention à toi.}
{225}{}{D'accord, la caravane à destination du Cimetière de L.A. est prête à partir.}
{226}{}{Dépôtville est un voyage généralement court et facile ; tu devrais pas rencontrer de problème sérieux.}
{227}{}{Bon, la caravane pour Dépôtville est prête à partir.}
{228}{}{Très bien. Dépôtville nous attend. Allons-y.}
{229}{}{Tiens, bonjour. J'ai cru comprendre que tu cherchais du travail. Etonnant que Rutger ait accepté de t'embaucher, mais il doit avoir ses raisons. Nos caravanes partent d'ici trois fois par mois : le 8, le 18 et le 28. Nous ravitaillons régulièrement trois endroits : la Confrérie de l'Acier, Dépôtville et le Cimetière de L.A. Le salaire est toujours de 400 caps à l'aller et, si tu veux revenir avec la caravane, de 400 caps au retour.}
{230}{}{Tu arrives à temps, elles partent toutes aujourd'hui.}
{231}{}{Elles partent toutes demain.}
{232}{}{Aucune ne part avant }
{233}{}{ jours.}
{234}{}{Ca t'intéresse ?}
{235}{}{Alors, tu le veux ce boulot ? }
{236}{}{Elles partent toutes aujourd'hui.}
{237}{}{Elles partent toutes demain.}
{238}{}{Aucune ne part avant }
{239}{}{ jours.}
{240}{}{Je suppose que tu veux du travail. J'en ai peut-être un pour toi. Ca t'intéresse ?}
{241}{}{Bien sûr.}
{242}{}{Non.}
{243}{}{Tu sais où tu peux te la mettre ta caravane !}
{244}{}{Je ne sais pas. Je reviendrai te voir.}
{245}{}{Gngnh.}
{246}{}{Quelle destination voulais-tu prendre ?}
{247}{}{La Confrérie de l'Acier.}
{248}{}{Le Cimetière de L.A.}
{249}{}{Dépôtville.}
{250}{}{Excuse-moi, j'ai changé d'avis.}
{251}{}{Eh bien, reviens le }
{252}{}{8}
{253}{}{18}
{254}{}{28}
{255}{}{ et on formera une équipe.}
{256}{}{Quel est le problème ?}
{257}{}{C'est toi le problème, et j'ai la solution.}
{258}{}{Tu devrais faire attention.}
{260}{}{Toi.}
{261}{}{Il n'y a pas de problème.}
{262}{}{Ouais, d'accord. Reviens me voir si tu changes d'avis.}
