{100}{}{Tu réussis à ouvrir le réfrigérateur.}
{101}{}{Tu as des problèmes avec ce verrou.}
{102}{}{Voici un réfrigérateur. Il est fermé et verrouillé.}
{103}{}{Voici un réfrigérateur. Il est ouvert.}
{104}{}{Voici un réfrigérateur. Il est fermé.}
{105}{}{La porte est verrouillée.}
{106}{}{En mouvement !}
{107}{}{Nous les avons tous tué !}
{108}{}{C'était facile !}
