{100}{}{Elimine les bandes de Tas-de-Ferraille.}
{101}{}{Si tu n'extermines pas toutes les bandes, elles chercheront à se venger.}
{102}{}{Les Cryptes et les Fous se disputent la maîtrise du générateur.}
{200}{}{Recherche les Fous}
{201}{}{Tu dois rechercher les Cryptes pour les Fous.}
{300}{}{Recherche les Cryptes}
{301}{}{Tu dois rechercher les Fous pour les Cryptes.}
{400}{}{Le Générateur d'énergie}
{401}{}{Sans le générateur, les paysans vivront dans la misère.}
{402}{}{Le générateur est la clef de voûte de Tas-de-Ferraille. Celui qui a la maîtrise du générateur règne sur Tas-de-Ferraille.}
{403}{}{Des fils dénudés sortent du générateur.}
{500}{}{Le problème de chien de Phil.}
{501}{}{Phil a des problèmes avec un chien.}
{502}{}{Le chien a l'air si affamé qu'il pourrait dévorer Phil.}
