{100}{}{Tu déverouilles le refrigirateur avec succès.}
{101}{}{Tu as des difficultés avec la serrure.}
{102}{}{Tu vois un refrigirateur. Il est fermé et verouillé.}
{103}{}{Tu vois un refrigirateur. Il est ouvert.}
{104}{}{Tu vois un refrigirateur. Il est fermé.}
{105}{}{La porte est fermée.}
{106}{}{Tu vois un refrigerateur.}
{107}{}{C'est deja déverouillé.}
{108}{}{Aucun effet.}