{100}{}{Voici un Crypte.}
{101}{}{Voici un bandit.}
{102}{}{Bienvenue dans la bande.}
{103}{}{Nous les Cryptes, nous allons enterrer tous les Fous.}
{104}{}{Je suis content que tu sois de notre côté.}
{105}{}{Avec ton aide, on va pouvoir massacrer ces Fous.}
{106}{}{Cette ville est entièrement à nous maintenant.}
{107}{}{J'aime ton style.}
{108}{}{Il va falloir que tu te trouves un cuir. Tu es un Crypte maintenant.}
{109}{}{On ne veut pas de types dans ton genre par ici, sale Fou.}
{110}{}{File avant qu'on te jette dehors.}
{111}{}{Si tu cherches des emmerdes, tous les Cryptes vont te tomber dessus.}
{112}{}{Tu as fait le mauvais choix. Maintenant, on va t'enterrer.}
{113}{}{Qu'est-ce que tu fais là ?}
{114}{}{Tas-de-Ferraille nous appartient.}
{115}{}{A Tas-de-Ferraille, si tu n'es pas de notre côté, c'est que tu es soit un perdant, soit un Fou. Alors, quel est ton camp ?}
{116}{}{Tu me parles là ? C'est à moi que tu parles ?}
{117}{}{Dis donc c'est pas un jeu. Soit t'es un Crypte, soit on t'enterre.}
{118}{}{Il n'y a que les Cryptes qui ont le droit de porter des cuirs.}
{119}{}{Filez, Fous, pendant que vous êtes encore en vie.}
{120}{}{Hé, Rayze, c'est l'ouverture de la chasse et les Fous sont sur la liste des proies.}
{121}{}{Hé les mecs, laissez-moi au moins un de ces Fous.}
