{100}{}{Voici un paysan.}
{101}{}{Oh, ouais, un grand bonhomme poursuivi par un chien effrayant. Phil, tu l'as sûrement vu. Ouais, sûrement.}
{102}{}{A quoi tu joues, Phil. Tu testes la solidité de tes basquettes ?}
{103}{}{Eh bien, ce chien a l'air affamé. Je suis sûr qu'il veut te dévorer tout cru, Phil.}
{104}{}{C'est peut-être un peu fort pour un pauvre animal sans défense, tu ne crois pas ?}
{105}{}{C'est un beau toutou que tu as là.}
{106}{}{Je pense que Phil apprécierait si tu le débarrassais de son chien.}
{107}{}{Merci d'avoir régler ce problème.}
{108}{}{Tu reçois 50 points d'expérience.}
