{100}{}{Voici un Fou.}
{101}{}{Voici un bandit.}
{102}{}{On nous appelle les Fous, mais c'est toi qui l'as été assez pour te présenter ici.}
{103}{}{Tu vas faire partie de la bande ?}
{104}{}{Ce n'est pas ta place.}
{105}{}{Ne crois pas que tu puisses te présenter comme ça et faire partie de la bande.}
{106}{}{Attention à toi, ou tu pourrais finir dans une crypte, sale Crypte.}
{107}{}{Ouais, on va s'occuper des Cryptes.}
{108}{}{Tas-de-Ferraille ne sera plus pareil sans ces Cryptes. La ville sera bientôt à nous !}
{109}{}{Ha ha ha ! Ha ha ha ha !}
{110}{}{Fous ! Fous ! Fous ! Ouais !}
{111}{}{Tu connais celle sur le poulet et le terrier de renard ?}
{112}{}{Reste calme.}
{113}{}{Rira bien qui rira le dernier.}
{114}{}{La vie est une farce. Pouah ! }
{115}{}{S'il n'y avait pas ces foutus Cryptes, on régnerait sur cette ville. Ou au moins, on pourrait lui régler son compte à ce maudit Lenny.}
{116}{}{Sois fou.}
{117}{}{Tu crois que ce malheureux cuir va te sauver de Baka ?}
{118}{}{Qu'est-ce qui s'est passé ? T'es tombé sur la tête le jour de ta naissance ?}
{119}{}{Si j'étais si moche, je me suiciderais.}
{120}{}{Vous les Cryptes, on dirait que vous venez d'en sortir d'une.}
{121}{}{Il faut être fou pour tenter un truc aussi stupide. Oh, attends... mais je suis un Fou !}
