{100}{}{Tu déverrouilles la porte.}
{101}{}{Tu as cassé ton passe-partout !}
{102}{}{Tu ne peux pas ouvrir ce verrou.}
{103}{}{Tu n'as pas pu crocheter le verrou.}
{104}{}{La porte est verrouillée.}
{105}{}{La porte est ouverte.}
{106}{}{La porte est fermée mais pas verrouillée.}
{107}{}{La porte est verrouillée.}
{108}{}{La porte grince très fort.}
{109}{}{La porte est déjà déverrouillée.}
{110}{}{Tu n'es pas capable de crocheter le verrou.}

# look_at_proc
{120}{}{Tu vois une porte en métal.}

# Fallout 2 MSG file:
#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################


# look_at_proc
{100}{}{Tu vois une porte en bois.}
{101}{}{Tu vois une porte en métal.}

# description_proc

# Perception Check Critical Success
{1020}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un piège hautement explosif placé sur l'encadrement de la porte.}
{1030}{}{Tu vois une porte solide avec un verrou et un piège hautement explosif placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}
{1040}{}{Tu vois une porte solide sans dispositif de verrouillage apparent et un piège hautement explosif placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}
{1050}{}{Tu vois une porte robuste avec un vieux verrou rouillé et un piège hautement explosif placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}

{1060}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un piège hautement explosif placé sur l'encadrement de la porte.}
{1070}{}{Tu vois une porte solide avec un verrou et un piège placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}
{1080}{}{Tu vois une porte solide sans dispositif de verrouillage apparent et un piège placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}
{1090}{}{Tu vois une porte solide avec un vieux verrou rouillé et un piège placé sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}

{1100}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un fil sectionné dans l'encadrement de la porte.}
{1110}{}{Tu vois une porte solide avec un verrou et un fil sectionné sur l'encadrement de la porte que tu pourrais essayer d'ouvrir avec un passe-partout.}
{1120}{}{Tu vois une porte solide sans dispositif de verrouillage apparent et un fil sectionné sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}
{1130}{}{Tu vois une porte robuste avec un vieux verrou rouillé et un fil sectionné sur l'encadrement de la porte que tu pourrais réussir à ouvrir avec un passe-partout.}

{1140}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout).}
{1150}{}{Tu vois une porte solide avec un verrou que tu pourrais réussir à ouvrir.}
{1160}{}{Tu vois une porte solide sans dispositif de verrouillage apparent que tu pourrais réussir à ouvrir.}
{1170}{}{Tu vois une porte robuste avec un vieux verrou rouillé que tu pourrais réussir à ouvrir.}

# Perception Check Success

{1180}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un piège hautement explosif placé sur l'encadrement de la porte.}
{1190}{}{Tu vois une porte solide avec un verrou et un piège hautement explosif placé sur l'encadrement de la porte.}
{1200}{}{Tu vois une porte solide avec un verrou et un piège hautement explosif dans l'encadrement de la porte.}
{121}{}{Tu vois une porte robuste avec un vieux verrou rouillé et un piège hautement explosif dans l'encadrement de la porte.}

{122}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un piège dans l'encadrement de la porte.}
{123}{}{Tu vois une porte solide avec un verrou et un piège dans l'encadrement de la porte.}
{124}{}{Tu vois une porte solide sans dispositif de verrouillage apparent et un piège placé sur l'encadrement de la porte.}
{125}{}{Tu vois une porte robuste avec un vieux verrou rouillé et un piège placé sur l'encadrement de la porte.}

{126}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout) et un fil sectionné sur l'encadrement de la porte.}
{127}{}{Tu vois une porte robuste avec un verrou et un fil sectionné sur l'encadrement de la porte.}
{128}{}{Tu vois une porte solide sans dispositif de verrouillage apparent et un fil sectionné sur l'encadrement de la porte.}
{129}{}{Tu vois une porte solide avec un vieux verrou rouillé et un fil sectionné sur l'encadrement de la porte.}

{130}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout).}
{131}{}{Tu vois une porte solide munie d'un verrou.}
{132}{}{Tu vois une porte solide sans dispositif de verrouillage apparent.}
{133}{}{Tu vois une porte solide munie d'un vieux verrou rouillé.}

# Perception Check Critical Failure

{134}{}{Tu vois une porte abîmée avec un verrou (pouvant être ouvert avec un passe-partout) et un piège hautement explosif sur l'encadrement de la porte.}
{135}{}{Tu vois une porte abîmée avec un verrou et un piège hautement explosif sur l'encadrement de la porte.}
{136}{}{Tu vois une porte abîmée sans dispositif de verrouillage apparent et un piège hautement explosif sur l'encadrement de la porte.}
{137}{}{Tu vois une porte abîmée avec un vieux verrou rouillé et un piège hautement explosif sur l'encadrement de la porte.}

{138}{}{Tu vois une porte abîmée avec un verrou (pouvant être ouvert avec un passe-partout) et un piège sur l'encadrement de la porte.}
{139}{}{Tu vois une porte abîmée avec un verrou et un piège sur l'encadrement de la porte.}
{140}{}{Tu vois une porte abîmée sans dispositif de verrouillage apparent et un piège sur l'encadrement de la porte.}
{141}{}{Tu vois une porte abîmée avec un vieux verrou rouillé et un piège sur l'encadrement de la porte.}

{142}{}{Tu vois une porte abîmée avec un verrou (pouvant être ouvert avec un passe-partout) et un fil sectionné sur l'encadrement de la porte.}
{143}{}{Tu vois une porte abîmée avec un verrou et un fil sectionné sur l'encadrement de la porte.}
{144}{}{Tu vois une porte abîmée sans dispositif de verrouillage apparent et un fil sectionné sur l'encadrement de la porte.}
{145}{}{Tu vois une porte abîmée avec un vieux verrou rouillé et un fil sectionné sur l'encadrement de la porte.}

{146}{}{Tu vois une porte abîmée avec un verrou (pouvant être ouvert avec un passe-partout).}
{147}{}{Tu vois une porte abîmée munie d'un verrou.}
{148}{}{Tu vois une porte abîmée sans dispositif de verrouillage apparent.}
{149}{}{Tu vois une porte abîmée munie d'un vieux verrou rouillé.}

# Perception Check Failure

{150}{}{Tu vois une vieille porte avec un verrou (pouvant être ouvert avec un passe-partout) et un piège hautement explosif sur l'encadrement de la porte.}
{151}{}{Tu vois une vieille porte avec un verrou et un piège hautement explosif sur l'encadrement de la porte.}
{152}{}{Tu vois une vieille porte sans dispositif de verrouillage apparent et un piège hautement explosif sur l'encadrement de la porte.}
{153}{}{Tu vois une vieille porte avec un vieux verrou rouillé et un piège hautement explosif sur l'encadrement de la porte.}

{154}{}{Tu vois une vieille porte avec un verrou (pouvant être ouvert avec un passe-partout) et un piège sur l'encadrement de la porte.}
{155}{}{Tu vois une vieille porte avec un verrou et un piège sur l'encadrement de la porte.}
{156}{}{Tu vois une vieille porte sans dispositif de verrouillage apparent et un piège sur l'encadrement de la porte.}
{157}{}{Tu vois une vieille porte avec un vieux verrou rouillé et un piège sur l'encadrement de la porte.}

{158}{}{Tu vois une vieille porte avec un verrou (pouvant être ouvert avec un passe-partout) et un fil sectionné sur l'encadrement de la porte.}
{159}{}{Tu vois une vieille porte avec un verrou et un fil sectionné sur l'encadrement de la porte.}
{160}{}{Tu vois une vieille porte sans dispositif de verrouillage apparent et un fil coupé sur l'encadrement de la porte.}
{161}{}{Tu vois une vieille porte avec un vieux verrou rouillé et un fil sectionné sur l'encadrement de la porte.}

{162}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout).}
{163}{}{Tu vois une vieille porte avec un verrou.}
{164}{}{Tu vois une vieille porte sans dispositif de verrouillage apparent.}
{165}{}{Tu vois une vieille porte munie d'un vieux verrou rouillé.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Tu as déclenché le piège et as subi }
{167}{}{ points de dégâts.}

# NPC sets off the trap
{168}{}{ déclenche le piège et subit }
{169}{}{ points de dégâts.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Tu crochètes adroitement le verrou de la porte.}
{171}{}{A cause de ton manque de dextérité, tu bloques le verrou de la porte.}
{172}{}{Tu n'as pas réussi à crocheter le verrou de la porte.}

# Lock Door
{189}{}{Tu verrouilles adroitement la porte.}
{190}{}{Tu ne réussis pas à verrouiller la porte.}

# Find Trap on the Door
{194}{}{Tu trouves un piège sur la porte.}
{195}{}{Tu ne trouves aucun piège sur la porte.}

# Disarm the Trap on the Door
{196}{}{Tu désamorces adroitement le piège.}
{198}{}{Tu ne réussis pas à désarmer le piège.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ crochète adroitement le verrou de la porte.}
{174}{}{ bloque le verrou de la porte à cause de son manque de dextérité.}
{175}{}{ n'a pas réussi à crocheter le verrou de cette porte.}

# Lock Door
{191}{}{ verrouille adroitement la porte.}
{192}{}{ n'a pas réussi à verrouiller la porte.}

# Find Trap on the Door
{199}{}{ trouve un piège sur la porte.}
{2000}{}{ ne réussit pas à trouver de piège sur la porte.}

# Fo2 - Disarm the Trap on the Door
{2010}{}{ désactive adroitement le piège.}
{2020}{}{ ne réussit pas à désactiver le piège.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Tu fais sauter la serrure de la porte.}
{177}{}{Tu te fais un tour de reins en essayant de faire sauter la serrure et tu subis un point de dégâts.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Tu te fais un tour de reins en essayant de faire sauter la serrure et tu subis }
{179}{}{ points de dégâts.}
{180}{}{Tu es trop faible pour faire sauter la serrure.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ fait sauter la serrure de la porte.}
{182}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit un point de dégâts.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit }
{184}{}{ points de dégâts.}

{185}{}{ est trop faible pour faire sauter la serrure.}
{186}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit un point de dégâts.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit }
{188}{}{ points de dégâts.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Ca n'occasionne même pas une égratignure à la porte.}

# Fo1 the master hidden door:
{200}{}{Cette porte n'a pas de verrou à crocheter.}
{201}{}{Tu remarques des irrégularités sur le mur.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{La porte est verrouillée.}
{204}{}{Tu remarques un piège sur l'encadrement de la porte.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jam.

{205}{}{ remarque un piège sur l'encadrement de la porte.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Tu ne peux pas mettre de piège sur cette porte car elle est ouverte.}

# NPC tries to set a trap on an open door
{207}{}{ ne peut pas mettre de piège sur cette porte car elle est ouverte.}

# Player tries to set a trap on a closed door
{208}{}{Tu places adroitement un piège sur l'encadrement de la porte.}
{209}{}{Tu ne réussis pas à placer de piège sur l'encadrement de la porte.}

# NPC tries to set a trap on a closed door
{210}{}{ place adroitement un piège sur l'encadrement de la porte.}
{211}{}{ ne réussit pas à placer de piège sur l'encadrement de la porte.}

{300}{}{Tu déverrouilles la porte.}
{301}{}{Tu verrouilles la porte.}
{302}{}{Tu n'arrives pas à verrouiller cette porte quand elle est ouverte.}
{303}{}{La clef ne correspond pas à cette serrure.}

# for broken doors
{320}{}{Il n'est pas possible de verrouiller cette porte.}
{330}{}{La porte est bloquée et ouverte.}

# Using a key on the door. (YES THIS IS A DUPLICATE BUT PLEASE DO NOT REMOVE..
# IT MOST LIKELY IS BEING USED BY A DOOR SCRIPT SOMEWHERE)
{400}{}{Tu déverrouilles la porte.}

{414}{}{Tu vois une porte solide avec un verrou (pouvant être ouvert avec un passe-partout), que tu pourrais réussir à ouvrir.}
{415}{}{Tu vois une porte solide avec un verrou que tu pourrais réussir à ouvrir.}
{416}{}{Tu vois une porte solide sans dispositif de verrouillage apparent que tu pourrais réussir à ouvrir.}
{417}{}{Tu vois une porte solide. Tu pourrais réussir à l'ouvrir.}

{500}{}{Cette porte est trop difficile à forcer.}
{501}{}{On dirait que tu vas d'abord devoir faire fonctionner le générateur.}
{502}{}{Tu vois : la porte de l'ascenseur.}
{503}{}{On dirait qu'il va te falloir un dispositif électrique pour ouvrir ce verrou.}
