# Cave encounter - Super Mutant centaur handler 

{100}{}{Tu vois : Dresseur de Centaure}
{101}{}{Tu vois un SuperMutant dresseur de Centaure.}

# Floats
{200}{}{Va chercher !}

# Can see
{210}{}{Tiens mon petit chien.}
{211}{}{T'es un bon chien !}
{212}{}{Bon chien !}
{213}{}{Tiens, tiens, voilà.}

# Can't see
{220}{}{Ou est-ce qui ne va pas doggie ?}
{221}{}{Hein ? Où est-ce que tu vas ?}
{222}{}{Mon toutou ?}
{223}{}{Hein, toutou ?}
{224}{}{Toutou, toutou, toutou..?}

# Disguised
{230}{}{Uhhhh...}
{231}{}{Tu regarde toutou ?}
{232}{}{Lou est fier, oui.}
{233}{}{Toi partir ! Pas le droit d'être ici.}

# Cover blown
{240}{}{Lou fier, moi attraper intrus !}