# Encounter - Gecko hunter, the Father

{100}{}{Tu vois : Chasseur expérimenté.}
{101}{}{Tu vois : Irataba, le Chasseur.}
{102}{}{Il ressemble à un chasseur expérimenté.}

# Give x experience
{150}{}{ points d'expérience pour avoir appris comment retirer la peau des geckos.}

# Float
{200}{}{NOOOOOOON !}
{201}{}{Nous n'avons pas le temps pour toi. S'il te plait vas-t-en.}
{202}{}{Bon voyage.}
{203}{}{Je suis désolé, mais je n'ai pas le temps ni les peaux pour faire ça maintenant.}
{204}{}{Vous allez payé pour ce que vous avez fait !}
{205}{}{Rangez votre arme, et nous pourrons parler.}

{1000}{}{Bonjour voyageur. Que puis-je faire pour vous ?}
{1001}{}{Que pouvons nous faire pour vous ?}
	{1010}{}{Qui êtes vous ?}
	{1020}{}{Que faites vous ici ?}
	{1030}{}{Preparez vous à mourrir !}

{1100}{}{Je suis Irataba, et voici mon fils Cairook.}
	{1110}{}{D'où venez vous ?}
	{1120}{}{Je suis }
	{1121}{}{. Ravi de faire votre connaissance.}
	{1130}{}{Que faites vous ici ?}

{1200}{}{Notre village est pas très loin d'ici. Ne le prends pas mal, mais je ne te dirais pas où il est.}
	{1210}{}{Dommage, j'avais envie de tous vous massacrer.}

{1300}{}{Merci. C'est agréable de rencontrer une personne sympa pour une fois.}
{1301}{}{Voulez-vous vous joindre à nous ? Je montre à mon fils comment retirer la peau des geckos.}
	{1310}{}{Oui avec plaisir.}
	{1320}{}{Je n'ai pas le temps pour ça, mais merci d'avoir proposé.}

{1400}{}{Très bien. Bon voyage, }
{1401}{}{.}
{1402}{}{Très bien. Bon voyage, étranger.}

{1500}{}{Nous sommes en train de chasser du geckos et je montre mon fils comment retirer la peau des geckos.}
	{1510}{}{Intéressant. Vous pouvez me montrer comment vous faites ?}
	{1511}{}{Si votre offre tiens toujours, vous pourriez me montrer comment retirer la peau des geckos ?}
	{1520}{}{Je vois. Et bien, au revoir.}

{1600}{}{Je n'ai pas le temps de vous apprendre, voyageur.}
	{1610}{}{Et bien, au revoir.}

{1700}{}{Très bien. Asseyez-vous, prenez ce couteau et regardez moi ... [Vous regardez et apprenez]}

{1800}{}{... Oui, c'est ça. On dirait que vous avez pris le coup. Maintenant avec un peu de pratique, vous pourriez bien être aussi bon que moi.}
	{1810}{}{Merci, de m'avoir montré ça, Irataba. Je pense que je vais aller m'entrainer sur quelques geckos. Salut.}

{1900}{}{... Non, non pas comme ça. Tu vois cette coupure ici ? Tu as ruiné la peau et ça la rend inutile.}
{1901}{}{Ne t'inquiète pas, cette peau ne valait pas grand chose. Mais tu devrais t'entrainer à la vie en plein air. Pour le moment, je ne crois pas que je puisse vous aider.}
	{1910}{}{Euh, okay. Je vais m'entrainer encore un peu alors. Au revoir.}

