{100}{}{Tu ne vois pas de tableau de commandes pour cet émetteur.}
{101}{}{Tu désactives temporairement le champ de force en endommageant l'émetteur.}
{102}{}{Tu détruit l'émetteur de champ de force. Le champ disparaît.}
{103}{}{Tu désactives provisoirement l'émetteur de champ de force.}
{104}{}{Tu échoues à faire quoi que ce soit avec l'émetteur de champ de force.}
{105}{}{Tu actives l'émetteur de champ de force.}
{150}{}{Tu échoues dans ta tentative de rebrancher l'émetteur de champ de force.}
{151}{}{Tu coupes l'émetteur de champ de force.}
{200}{}{Tu vois un émetteur de champ de force horriblement endommagé.}
{201}{}{L'émetteur est trop endommagé pour pouvoir être utilisé.}
{202}{}{L'émetteur est trop endommagé pour pouvoir être réparer.}
{203}{}{Tu remarques que le champ est maintenant assez faible pour être franchi.}
#
# Fallout Fixt
#
{204}{}{Une charge explosive bien placée devrait venir définitivement à bout de l'émetteur.}
{205}{}{Tu ne trouves aucun moyen de fixer les explosifs à l'émetteur. Tu devras les placer au plus près.}

# Fo1in2
{206}{}{Tu échoues à faire des dégats sur l'émetteur.}
