{100}{}{Voici le Paladin Farli.}
{101}{}{Bonjour.}
{102}{}{Chad'ra chu ka ?}
{103}{}{Katja chu nee ka Chak'ra Farli.}
{104}{}{Farli, nee ko }
{105}{}{ mat'chak o Drake.}
{106}{}{Ah, Drake ko mat'chak.}
{107}{}{Donne le bonjour à notre ami si tu le revois.}
{108}{}{La Confrérie, ça me rappelle chez moi.}
