{100}{}{Tu vois Fire, un membre des Ecorcheurs.}
{101}{}{}
{102}{}{}
{103}{}{Tu vois un membre des Ecorcheurs.}
{104}{}{Tu vois un membre des Ecorcheurs.}
{105}{}{Tu penses apercevoir Books.}
{106}{}{Tu penses apercevoir Scars.}
{107}{}{Tu penses apercevoir Gunner.}
{108}{}{Tu penses apercevoir Twitch.}
{109}{}{Tu penses apercevoir Hammer.}
{110}{}{Tu penses apercevoir Razor.}
{111}{}{Tu veux quoi, bouseux ?}
{112}{}{Err.}
{113}{}{Je veux devenir un Ecorcheur.}
{114}{}{Qu'est-ce que ça va me demander pour que vous fassiez la paix avec le Sanctuaire ?}
{115}{}{Ca ! [Tu le baffes]}
{116}{}{Rien. Désolé de t'avoir dérangé.}
{117}{}{Je visite juste.}
{118}{}{Bien, encore un attardé, on dirait un Eventreur.}
{119}{}{Rrrrr.}
{120}{}{Arrrr.}
{121}{}{Arrooo ?}
{122}{}{Toi non plus tu les aimes pas ? On a peut-être un 'boulot' pour toi.}
{123}{}{Urroo.}
{124}{}{Un nah.}
{125}{}{Ok, va parler à notre tête pensante. Razor te mettra directement dans le bain et te dira quoi faire.}
{126}{}{Stupide comme un poulet. Je vais mettre un terme à ta misérable existence.}
{127}{}{Alors t'es un Eventreur ! Je suis désolé d'entendre ça, mais je savais déjà qu'ils étaient stupides. Bonne nuit !}
{128}{}{Les Eventreurs, ces consanguins de l'autre coté de la ville. Laisse tomber, t'es trop stupide pour comprendre quoi que ce soit.}
{129}{}{Tu veux être un Ecorcheur ? Bonne chance. Mais, si tu croises Razor, parles en lui. Elle te laissera peut-être sauter le pas.}
{130}{}{Ok, merci.}
{131}{}{Ca ne m’intéresse pas !}
{132}{}{Que veux tu dire par 'sauter le pas'?}
{133}{}{Tu ne peux pas simplement faire de moi un Ecorcheur ?}
{134}{}{Ta mère ne t'a jamais voulu, et c'est pareil pour nous.}
{135}{}{Simple. Tu auras à tuer quelqu'un pour nous rejoindre. Elle te dira qui.}
{136}{}{Ok, merci.}
{137}{}{Laisse tomber. Je ne veux pas devenir membre de ton stupide gang.}
{138}{}{Non. Je ne peux pas. Je ne dirige pas. Je garde juste Razor dans le droit chemin.}
{139}{}{Simple. Extermine nos ennemis, et ensuite nous ferons une trêve avec le Sanctuaire.}
{140}{}{Qui sont vos ennemis ?}
{141}{}{D'accord. Tu as des preuves ?}
{142}{}{Se battre est mal ! Je ne le ferai pas !}
{143}{}{Les Régulateurs qui gouvernent le Sanctuaire. Ils ne sont pas stupides et sont très dangereux.}
{144}{}{Ok, je tuerai les Régulateurs.}
{145}{}{Oublie ça.}
{146}{}{Si tu comptes faire ça, tu devrais le faire savoir à Razor. Dans le cas contraire, elle aura ta tête avant que tu ne sortes d'ici.}
{147}{}{Comme tu le sens. Salut.}
{148}{}{Je fais pas de marché, seulement des suggestions. Parle à Razor si tu veux agir.}
{149}{}{Alors te tuer maintenant t'évitera de longues années de souffrance.}
{150}{}{Visite ça pour voir !}
{151}{}{Casse-toi de là si tu tiens à la vie.}
{152}{}{Silence. Nous essayons d'espionner les Eventreurs.}
{153}{}{Si tu récupères la tête, amène là à Razor. Elle veut toujours jouer au football. Dans le cas contraire, dégage !}
{154}{}{Yo, l'ami !}
