{100}{}{Voici un garçon maigre et débraillé.}
{101}{}{J'ai pas le droit d'te parler. Va-t'en.}
{102}{}{Pourquoi que tu sors ton arme ? On n'a rien, même pas de poisson !}
{103}{}{Salut. C'est quoi que tu veux ?}
{104}{}{Alors, ça mord ?}
{105}{}{Je commence à être un peu à cours de provisions...}
{106}{}{Rien remarqué d'anormal ces temps-ci ?}
{107}{}{Tu veux connaître mes aventures dans les grottes des radscorpions ?}
{108}{}{Runk !}
{109}{}{Salut. C'est pas toi qui te balades un peu partout pour aider les gens ? Tu dois en avoir plein des histoires à raconter !}
{110}{}{D'où tu viens ?}
{111}{}{Salut. Je vois que t'es pas assez bête pour pêcher ici. Qu'est-ce que tu fabriques ?}
{112}{}{Pas sûr. P'pa et moi, ça fait tellement longtemps qu'on s'trimballe dans l'désert. On avait un ami avec nous, un chasseur de radscorpions, mais il est dev'nu dingue et on a dû l'tuer, et puis on...}
{113}{}{Hum, peut-être que j'devrais pas parler d'ça.}
{114}{}{Parle-moi de ton papa.}
{115}{}{Et les radscorpions ?}
{116}{}{Des conneries. Pardon, faut pas que j'dise 'conneries'. P'pa, y pense que les gens qui disent toujours ce mot-là sont soit des tarés soit des illettrés irrécupérables. P'pa, il essaie toujours de bien causer.}
{117}{}{Ton père a raison.}
{118}{}{Désolé. C'est pas à moi qu'il faut s'adresser pour les provisions.}
{119}{}{J'ai vu un truc énorme, comme une araignée géante avec deux têtes, et y'en a une, on aurait dit une tête d'humain. P'pa, y pense que j'ai pompé trop d'radiations. Ch'sais pas. L'eau contaminée, ça fait des trucs bizarres dans l'cerveau.}
{120}{}{Ah ouais, quoi par exemple ?}
{121}{}{C'est quoi un runk ?}
{122}{}{Biensûr !}
{123}{}{Le plus dur quand on chasse les radscorpions, c'est d'attendre qu'ils s'fourrent dans un endroit piégé.}
{124}{}{Le plus dur quand on chasse les radscorpions, c'est de courir après quand ils s'échappent !}
{125}{}{Le plus dur quand on chasse les radscorpions, c'est quand ils te piquent la figure avec leur dard.}
{126}{}{Ouais. T'as entendu parler des pillards qui sont tombés dans un nid de radscorpions et qui se sont fait piquer et bouffer cru, sauf un qui s'est échappé avec la figure à moitié dévorée !}
{127}{}{Bon dieu, en voilà une bonne !}
{128}{}{Oh, il est casse-pieds sur les bords, et j'crois pas qu'c'est mon vrai père. J'pense qu'y m'a volé quand j'étais bébé. Mais y fait son possible pour m'nourrir, alors peut-êtr' que j'l'aime bien après tout.}
{129}{}{Ils sont énormes et mauvais, et on n'arrive plus à les contrôler. P'pa disait qu'avant, y'avaient des héros qui parcouraient le désert pour les abattre, mais sans doute que maintenant, ils sont presque tous morts.}
{130}{}{Quel genre de héros ?}
{131}{}{Ouais, les adultes se tiennent toujours les coudes. C'est idiot.}
{132}{}{Avant, le Gros Henri venait avec nous, il était meilleur que 'pa et moi ; et puis il est dev'nu fou et il a essayé d'm'étrangler. P'pa a dû l'tuer !}
{133}{}{C'est un bon tireur ton papa ?}
{134}{}{Qui c'est le Gros Henri ?}
{135}{}{Ouais, super ! Vaudrait mieux que j'retourne à la pêche, sinon on va crever d'faim et faudra qu'on t'mange !}
{136}{}{Un tas de héros. Le type qu'a fondé la Confrérie de l'Acier, Roger Maxim, c'était un sacré tueur de radscorpions. Quand j'serai grand, j'irai les rejoindre !}
{137}{}{Très bien tout ça.}
{138}{}{C'est vraiment dur d'entrer dans la Confrérie. Et c'est un voyage long et périlleux.}
{139}{}{J'crois qu'il est bien. En fait, j'l'ai vu toucher un radscorpion entre les deux yeux à plus de 60 mètres, mais c'était un coup d'pot.}
{140}{}{Y v'nait du Sud. Une sorte de pillard qu'essayait de vivre d'la terre, pas des gens. C'était vraiment un mec super, mais ça lui arrivait d'dérailler, et un jour, il... euh... oh, rien.}
{141}{}{Ouais. J'vais dev'nir un hé-ros, exactement comm' lui. Pas qu'un peu !}
{142}{}{Tu crois que vivre comm' ça, c'est facile ? J'suis pas une poule mouillée et ici, c'est pas du tout cuit, alors ce s'ra pas par frousse si je pars. Faut seul'ment que j'sois assez vieux pour m'débrouiller seul.}
{143}{}{Et le combat entre un radscorpion et un homme ?}
{144}{}{Seulement une douzaine de fois...}
{145}{}{Euh, oui.}
{146}{}{Je crois qu'cette fois, j'vais attraper un rhume...}
{147}{}{Dépêche-toi ! J'crève de faim !}
{148}{}{Ca fait tellement longtemps que t'as pris quequ' chose, j'ai oublié le goût qu'ça a.}
{149}{}{P'pa, t'as entendu quequ' chose...}
