{100}{}{You light the flare.}
{101}{}{This flare has been expended.}
{102}{}{The flare runs out of fuel and is extinguished.}
{103}{}{You see a lit flare.}
{104}{}{You see a spent flare.}
{105}{}{You see a flare.}
