{100}{}{Surveille tes manières chez le Doc, si tu veux pas que je t'arrange le portrait.}
{101}{}{C'est fermé. Reviens plus tard.}
{102}{}{Faut que j'vois l'toubib.}
{103}{}{D'accord.}
{104}{}{Il faut absolument que je vois le médecin.}
{105}{}{Humm.}
{106}{}{Beau temps, hein ?}
{107}{}{Tant pis pour toi. Dehors ! Et ne reviens pas avant demain matin, le cabinet n'ouvre pas le soir.}
{108}{}{Attends, faut que j'vois le toubib.}
{109}{}{Qu'est-ce tu veux ?}
{110}{}{Faut que j'vois l'toubib.}
{111}{}{Le docteur reçoit-il ?}
{112}{}{Hum !}
{113}{}{Pas question, Doc roupille. Reviens plus tard.}
{114}{}{Chais pas, pourquoi tu lui demandes pas toi-même.}
{115}{}{Oui, oui, c'est ça. Dégage !}
{116}{}{Eh, c'est une propriété privée ici. Tu ferais mieux de sortir.}
{117}{}{Mon cul !}
{118}{}{Si tu bouges pas de mon chemin, t'auras d'autres raisons de voir le médecin.}
{119}{}{Tu sais donc pas que les femmes sont le sexe faible ?}
{120}{}{Tu me prends pour une mauviette ? Vise un peu ça...}
{121}{}{Je m'en vais.}
{122}{}{Ravale tes menaces de débile et rentre chez maman. Tu parles à un homme, un vrai.}
{123}{}{Tu me prends pour une mauviette ? Vise un peu ça...}
{124}{}{Je m'en vais.}
{125}{}{Whoa ! Si tu tiens vraiment à le voir, c'est tout droit.}
{126}{}{Bien, quand le docteur est-il là ?}
{127}{}{Le docteur consulte de 8 à 17. Maintenant, sors.}
{128}{}{Quand le docteur est-il là ?}
{129}{}{Je t'avais dit de ne pas revenir.}
