{100}{}{Voici Flipper.}
{101}{}{Voici un énorme mutant.}
{102}{}{Arrrghhh ! Meurs, infidèle !}
{103}{}{Tu devrais être dans la salle de contrôle. T'attarde pas.}
{104}{}{Un humain, tiens, tiens ! Très intéressant. Tu me suis chez le Lieutenant ou tu péris sur le champ.}
{105}{}{Jamais !}
{106}{}{D'accord, je me rends. Allons-y.}
{107}{}{Bof !}
{108}{}{Excellent. Suis-moi si tu tiens à la vie.}
{109}{}{D'accord. Allons-y.}
{110}{}{Après toi.}
{111}{}{Tu me prends pour un débile, comme beaucoup des miens. Mais, tu te trompes. C'est un problème de terminal, je crois.}
{112}{}{Alors, te re-voilà. Cette fois, tu ne m'échapperas pas.}
{113}{}{Si tu t'approches de moi, je te tue !}
{114}{}{Flipper, quand vais-je sortir d'ici ?}
{115}{}{Bientôt. Très bientôt. Ton heure approche.}
{116}{}{J'ai hâte de nous voir enfin réunis.}
{117}{}{Tu ne regretteras pas ta décision. L'immersion est douloureuse...}
{118}{}{Pas trop, j'espère.}
{119}{}{Le FEV est très douloureux, mais tu survivras.}
{120}{}{Et tu seras des nôtres. Corps et âme.}
{121}{}{Serons-nous de nouveau réunis ?}
{122}{}{Oui, je te le promets.}
{123}{}{Je t'aime.}
{124}{}{Moi aussi.}
