{100}{}{On n'est pas là pour parler.}
{101}{}{Je te suivrai jusqu'à la mort.}
{102}{}{C'est important ce travail, hein ?}
{103}{}{Nicole dit qu'on doit faire autant de dégâts que possible.}
{104}{}{Qui dois-je tuer ensuite ?}
{105}{}{Qu'est-ce qu'on fait là à bavarder ?}
{106}{}{J'aime pas ces ordures dans leurs sacs marron, sans façons.}
{107}{}{Ca pourrait être dangereux.}
{108}{}{Faut pas traîner ici.}
{109}{}{Cet endroit est vraiment nul.}
{110}{}{Je sens que je vais être malade.}
{111}{}{Nicole nous a dit de revenir dès que t'as quitté la Cathédrale.}
{112}{}{Un plaisir de te rencontrer. Allons-y.}
