{100}{}{Voici un homme costaud et bien armé.}
{101}{}{Voici Gabriel, chef des Contrebandiers.}
{102}{}{C'est pas souvent qu'on a de la visite... Je peux t'aider ?}
{103}{}{Pourquoi vous avez pas souvent de visites ?}
{104}{}{Qu'est-ce que vous faites ici ?}
{105}{}{Cet endroit est pas facile d'accès, avec ce nid de Griffemorts juste en dehors de l'usine.}
{106}{}{Vous semblez bien équipés, pourquoi ne pas les exterminer ?}
{107}{}{C'est ce qu'on a essayé de faire, mais quand y'en a plus, y'en a encore. Et puis, on est des machinistes, pas des guerriers.}
{108}{}{Et si je m'en charge à votre place, qu'est-ce que vous me donnez ?}
{109}{}{On fabrique des armes et des munitions ; ça fait 30 ans. Mais depuis 10 ans, c'est l'enfer.}
{110}{}{Pourquoi ça ?}
{111}{}{On a écumé les environs de l'usine de tous les déchets métalliques hérités de la guerre. Maintenant, c'est le Sanctuaire qui nous approvisionne en matières premières.}
{112}{}{Et que le Sanctuaire vous approvisionne, ça pose un problème ?}
{113}{}{Au début, rien à redire. Ils nous fournissaient les matières premières et nous, on fabriquait et on vendait les armes. Et puis il y a 3 ans, Zimmerman a embauché des mercenaires pour protéger le Sanctuaire contre les Griffemorts et les pillards. Et ces milices sont sans foi ni loi, elles nous exploitent au maximum ! On fabrique les fusils et eux s'engraissent...}
{114}{}{Pourquoi ne pas partir et vous installer ailleurs ?}
{115}{}{Dur. Qu'est-ce que vous me donnez si je me charge des Griffemorts ?}
{116}{}{Ah, on demanderait pas mieux ! Mais déménager, avec toutes nos machines et nos installations, t'imagines ! Pas facile à déplacer tout ça. On partirait bien, mais avec les Griffemorts, impossible !}
{117}{}{Vous semblez assez bien équipés, pourquoi ne pas les exterminer ?}
{118}{}{Si tu réussissais à nous débarrasser des Griffemorts pour de bon, ton prix serait le nôtre.}
{119}{}{Je veux des armes et des munitions... et beaucoup.}
{120}{}{}
{121}{}{Si tu nettoies le coin, on partira mais on laissera derrière nous plus d'armes et de munitions qu'il t'en faudrait.}
{122}{}{Ok. Marché conclu.}
{123}{}{Faut que je réfléchisse.}
{124}{}{Des gens qui régleraient tous les problèmes que le Sanctuaire nous pose.}
{125}{}{Tu élimines les Griffemorts, jusqu'au dernier, et ça marche !}
{126}{}{D'accord, je m'en charge.}
{127}{}{Faut que je réfléchisse.}
{128}{}{Re-bonjour.}
{129}{}{Qu'est-ce que vous faites ici ?}
{130}{}{Au revoir.}
{131}{}{}
{132}{}{Tout s'est bien passé.}
{133}{}{Je pense avoir tué tous les Griffemorts.}
{134}{}{Faut être sûr. On en a tué plus de 20 en 2 ans, et on dirait qu'il en revient toujours. Comment ? Ca, mystère. S'ils donnent plus signe de vie d'ici quelques jours, on verra ce qu'on peut faire pour toi.}
{135}{}{D'accord. Merci.}
{136}{}{Fais-nous signe dès que t'as réglé le compte des Griffemorts.}
{137}{}{D'accord. A un de ces quatre.}
{138}{}{Je sais bien.}
{139}{}{A un de ces quatre.}
{140}{}{C'est pas souvent qu'on a de la visite... Je peux t'aider ?}
{141}{}{Pourquoi vous avez pas souvent de visites ?}
{142}{}{Qu'est-ce que vous faites ici ?}
{143}{}{Cet endroit est pas facile d'accès, avec ce nid de Griffemorts juste en dehors de l'usine.}
{144}{}{J'ai tué tous les Griffemorts. Même toutes leurs saletés d'œufs.}
{145}{}{Ah, on demanderait pas mieux ! Mais déménager, avec toutes nos machines et nos installations, t'imagines. Pas facile à déplacer tout ça. On partirait bien, mais avec les Griffemorts, impossible !}
{146}{}{J'ai tué tous les Griffemorts. Même toutes leurs saletés d'œufs.}
{147}{}{}
{148}{}{Je veux des armes et des munitions... et beaucoup.}
{149}{}{}
{150}{}{Je demande rien. Votre gratitude me suffit.}
{151}{}{Tu les as eus ; prends ce que tu veux. On part dans un ou deux jours, mais on laissera plus d'armes et de munitions que tu ne peux en porter. Reviens te servir quand t'as besoin.}
{152}{}{}
{153}{}{}
{154}{}{Merci.}
{155}{}{}
{156}{}{Pas de problème.}
{157}{}{}
{158}{}{}
{159}{}{Vous deviez pas partir ?}
{160}{}{Je viens juste prendre deux ou trois trucs. Qu'est-ce que t'as aujourd'hui ?}
{161}{}{Rien. Merci.}
{162}{}{}
{163}{}{Super. Alors les mecs, qu'est-ce que vous avez aujourd'hui ?}
{164}{}{Bon allez, à un de ces quatre.}
{165}{}{}
{166}{}{Je viens juste prendre deux ou trois trucs. Qu'est-ce que tu m'proposes aujourd'hui ?}
{167}{}{Rien. Merci.}
{168}{}{Désolé, j'ai pas le temps de discuter, je suis très occupé.}
{169}{}{Les fusils, j'aime les fusils !}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{170}{}{J'ai des amis qui sauront bien quoi faire de vos armes.}
{171}{}{J'ai des amis qui sauront bien quoi faire de vos armes.}
{172}{}{Comment ça va ?}
{173}{}{Comment ça va, l'amie ?}
{174}{}{Tu quoi ?! Tu les a tous tués ? Les dieux sont avec nous ! Maintenant, on peut partir. On a plus à dépendre de ces vermines du Sanctuaire pour nos matières premières. Ton prix sera le nôtre, l'ami.}
{175}{}{Tu quoi ?! Tu les a tous tués ? Les dieux sont avec nous ! Maintenant, on peut partir. On a plus à dépendre de ces vermines du Sanctuaire pour nos matières premières. Ton prix sera le nôtre, l'amie.}
{176}{}{Parfait. Ravi d'avoir eu affaire à toi, l'ami.}
{177}{}{Parfait. Ravi d'avoir eu affaire à toi, l'amie.}
{178}{}{Tu les as eus. Fais savoir à tes amis qu'ils ont leurs armes.}
{179}{}{Tu les as eus. Fais savoir à tes amis qu'ils ont leurs armes.}
{180}{}{Merci, l'ami.}
{181}{}{Merci, l'amie.}
{182}{}{Désolé l'ami, j'ai pas le temps de te parler ; on est occupés à déménager. Sers-toi à ton aise.}
{183}{}{Désolé l'amie, j'ai pas le temps de te parler ; on est occupés à déménager. Sers-toi à ton aise.}
{184}{}{C'est plus la peine de partir maintenant que nous sommes débarrassés de ces maudits mercenaires.}
{185}{}{C'est plus la peine de partir maintenant que nous sommes débarrassés de ces maudits mercenaires.}
{186}{}{Bienvenue l'ami. Je peux t'aider ?}
{187}{}{Bienvenue l'amie. Je peux t'aider ?}

#
# Following Line is just to be translated normally.
#
{188}{}{Pour les achats, adresse-toi à Zack.}

# Fo1in2
{300}{}{Génial ! Si tu cherches quelque chose, Zack juste ici sera ravi de t'aider.}
