{100}{}{Voici Garl, le chef des pillards.}
{101}{}{Tu crois donc pouvoir venir ici sans crainte ? Ici, le foyer de tes plus farouches ennemis ? Tu vas mourir. Et je t'arracherai le cœur pour le dévorer sous les yeux de mes fiers guerriers !}
{102}{}{Je t'avais fait la peau !}
{103}{}{Je saisis pas.}
{104}{}{C'est vrai. Mais je suis là pour te hanter.}
{105}{}{T'aurais pas dû faire ça.}
{106}{}{Je t'ai tué !}
{107}{}{Je saisis pas.}
{108}{}{C'est vrai. Mais je suis là pour te hanter.}
{109}{}{T'aurais pas dû faire ça.}
{110}{}{Non, car tu n'es pas mon père. Tu lui ressembles, mais seulement par les traits. Il ne reste de lui aucune image. Il va falloir que tu disparaisses.}
{111}{}{J'y crois pas ! Je peux pas y croire !}
{112}{}{Crois ça mon pote, et tu vas bientôt me rejoindre en enfer !}
{113}{}{Me dis pas ce que j'avais à faire, père. Je suis maintenant le chef des Khans, et t'es rien que de la bidoche à asticots.}
{114}{}{Je vis toujours.}
{115}{}{J'aurais dû te tuer quand t'étais jeune.}
{116}{}{Me dis pas ce que j'avais à faire, père. Je suis maintenant le chef des Khans, et t'es rien que de la bidoche à asticots.}
{117}{}{Je vis toujours.}
{118}{}{J'aurais dû te tuer quand t'étais jeune.}
{119}{}{T'aurais dû. Mais c'est trop tard. Je suis Garl Mainmorte. Le chef des Khans. Tu devrais être couché dans ta tombe, et tu vas y retourner !}
{120}{}{T'es devant mes yeux, mais j'y crois pas. Qu'est-ce que tu veux ?}
{121}{}{Que tu libères la fille. Maintenant.}
{122}{}{Que tu démissionnes.}
{123}{}{De quoi acheter ma place au Paradis.}
{124}{}{Jure de retourner dans ta tombe, et il sera fait comme tu l'exiges.}
{125}{}{Je jure que je partirai.}
{126}{}{Qu'il en soit ainsi. Relâchez la femme des Sables Ombragés et emmenez-le...}
{127}{}{Tu n'es pas le maître ici. Tu n'as rien à faire ici. Mort aux revenants !}
{128}{}{Jamais !}
{129}{}{Voilà qui me plaît. L'esprit d'initiative. Mais tu n'aurais pas dû les tuer sans ma permission. Trop d'initiative nuit.}
{130}{}{Qu'est-ce que tu veux ?}
{131}{}{Que tu libères la fille.}
{132}{}{Que tu meurs.}
{133}{}{Je suis venu pour négocier entre amis la liberté de Tandi.}
{134}{}{Houngh !}
{135}{}{Qu'est-ce qui te fait croire que je l'ai ?}
{136}{}{Je le sais. Je t'ai suivi jusqu'ici.}
{137}{}{Un de tes disciples me l'a dit.}
{138}{}{Je sais.}
{139}{}{J'ai horreur de ça. Je ferai payer ce braillard. Dès que j'en aurai fini avec toi.}
{140}{}{Hum. Et qu'offres-tu pour sa liberté ?}
{141}{}{Je représente une menace dont tu n'as même pas idée. Veux-tu vraiment risquer notre colère.}
{142}{}{Quelque chose d'égale valeur.}
{143}{}{Ce serait bien pour l'éternité de ton âme.}
{144}{}{Ton sang, répandu sur ce sol.}
{145}{}{Hum. Je ne sais pas pourquoi, mais je te crois. Emmène la fille, mais ne reviens pas sous peine de déclencher notre fureur.}
{146}{}{Ah ! Tu ne devrais pas menacer tes supérieurs.}
{147}{}{Alors, cela doit être précieux. Montre.}
{148}{}{Ca me plaît. Emmène la fille, mais ne reviens pas.}
{149}{}{Ton offre n'en vaut pas la peine. Tuez-le.}
{150}{}{Tu penses qu'un homme comme moi croit à la vie après la mort ? Ce monde se meurt et je prendrai ce que je veux ! Tu ne sauras jamais la force qu'exige une telle décision !}
{151}{}{Qu'est-ce que tu veux encore ?}
{152}{}{Rien.}
{153}{}{La fille.}
{154}{}{Ben.}
{155}{}{Tu me déranges. Va-t'en.}
{156}{}{Ta présence nous est indésirable. Pourquoi alors te donner l'un de nos biens les plus précieux ?}
{157}{}{Ce n'est que justice.}
{158}{}{Je propose quelque chose d'égale valeur.}
{159}{}{Tu auras le droit de vivre.}
{160}{}{Justice ?! C'est moi qui décide de ce qui est juste. Tu t'avances en terrain dangereux.}
{161}{}{Pardon.}
{162}{}{Qu'est-ce que j'en ai à faire ? J'emmène la fille.}
{163}{}{Oui, je le vois. Je n'admets pas les chiffes molles. Et ce qui n'est pas admis doit être détruit. A mort !}
{164}{}{Tu me défierais au combat pour elle ?}
{165}{}{Non, j'aime et ne me bats point.}
{166}{}{Bien sûr. Sur le champ, toi et moi.}
{167}{}{Je te défie, toi et toute ta bande.}
{168}{}{Parfait. Alors, à mains nues. Si tu gagnes, tu emmènes la femme. Si je gagne, tu pars sans elle.}
{169}{}{Très bien.}
{170}{}{Intéressant, mais pas très sportif. D'accord, allons-y.}
{171}{}{D'accord.}
{172}{}{Hum, tu te bats mieux que je ne le pensais. J'ai pas reçu de raclée depuis que mon père me donnait la fessée. Tu mérites la femme des Sables Ombragés. Prends-la et pars. Définitivement.}
{173}{}{Va promener ta misérable carcasse loin d'ici. Si jamais tu reviens, ça se passera moins bien.}
{174}{}{Qu'est-ce que tu veux ?}
{175}{}{J'explore le monde.}
{176}{}{Je veux m'enrôler.}
{177}{}{Nous n'aimons pas les gens de ton espèce. Indésirable. A mort !}
{178}{}{Toi ? Te joindre à nous ? Pourquoi diable ?}
{179}{}{Pour les bastons.}
{180}{}{Vous me plaisez, les mecs. Je veux m'unir à vous.}
{181}{}{Les Pillards n'acceptent que la pire des racailles. Il faut être sanguinaire, violent, prêt à tout. Tu crois vraiment en être capable ?}
{182}{}{Oui.}
{183}{}{Non.}
{184}{}{Dans ce cas, file. Et ne reviens pas.}
{185}{}{J'en ai marre de ces femmes. Tuez-les.}
{186}{}{Non !}
{187}{}{D'accord.}
{188}{}{Tu viens de me donner raison. Seuls les Pillards ont la volonté de survivre ! Toi, non. Tuez-le !}
{189}{}{Tu viens de me donner raison. Seuls les Pillards ont la volonté de survivre ! Toi, non. Tuez-la !}
{190}{}{Ordure ! Tu vas me le payer !}
{191}{}{Ah ! Ton style me plaît. Un peu trop sensible, mais bon... considère les Pillards comme tes amis. Hors de ma vue maintenant.}
{192}{}{Qu'est-ce que tu veux encore ?}
{193}{}{Rien.}
{194}{}{Des armes et une armure.}
{195}{}{Ben.}
{196}{}{Tu dois te défendre seul.}
{197}{}{Comment oses-tu reparaître devant moi ? Tuez-le !}
{198}{}{Comment oses-tu reparaître devant moi ? Tuez-la !}
{200}{}{Je viens faire la fête avec vous les mecs !}
{201}{}{Bon, va chercher à boire et des femmes pour notre petite fête.}
{203}{}{Je veux me battre avec toi pour Tandi.}
{204}{}{Tu ne fais pas partie des Pillards, tu ne mérites aucun honneur.}
{205}{}{Ton offre n'en vaut pas la peine. Tuez-la.}
{206}{}{Nous n'aimons pas les gens de ton espèce. Indésirable. A mort !}
{207}{}{Waaaoug !}
{208}{}{D'accord, t'as gagné. Prends la fille et tire-toi.}
{209}{}{Que le combat pour l'honneur commence !}

# Tell Me About generic responses
{980}{}{Qu'est-ce que tu veux ?}
{981}{}{Je ne vais pas te répondre.}
{982}{}{Tu ferait mieux de dégager et de partir d'ici.}

{1000}{}{Khans|KHANS|KHAN|PILLARD|PILLARDS|GRANDS KHANS}
{1001}{}{Garl|GARL}
{1002}{}{Dépôtville}
{1003}{}{Sables|Sables Ombragés|Les sables ombragés}
{1004}{}{Centre|Le Centre}
{1005}{}{Eau}
{1006}{}{Tandi}
{1007}{}{Puce d'eau|Puce}
{1008}{}{Aide|Blessure|Docteur|Doc}
{1009}{}{Rejoindre|Devenir Khan}

{1100}{}{C'est nous, espèce d'idiot.}
{1101}{}{Je suis le chef des Khans. La terreur du désert.}
{1102}{}{Ils sont au Sud-Ouest. On y va parfois se reposer après une dure journée de pillage.}
{1103}{}{Une misérable fourmilière de minus. Je pourrais les écraser.}
{1104}{}{Ils sont au Sud. On fait du commerce avec eux. Surtout pour l'eau et les munitions, et parfois pour les armes.}
{1105}{}{Qu'est-ce que j'en ai à faire ?}
{1106}{}{Je connais personne de ce nom.}
{1107}{}{Une quoi ?}
{1108}{}{Va pleurer ailleurs}
{1109}{}{Toi rejoindre les Grands Khans ? Haha ne me fait pas rire !}