{100}{}{T'as foutu Gary en rogne !}
{101}{}{Voici Gary.}
{102}{}{Eh ! Y'a que les Goules qu'ont droit à une ration d'eau.}
{103}{}{La ferme !}
{104}{}{Le mutant t'ignore.}

{1000}{}{Eau}
{1001}{}{Nécropolis}
{1002}{}{Set}
{1003}{}{Réservoir}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Goules}
{1007}{}{Normaux}
{1008}{}{Puce}

{1100}{}{J'sais pas.}
{1101}{}{Tu es en plein dedans.}
{1102}{}{Une lavette. On devrait juste les éliminer, lui et ses Goules.}
{1103}{}{C'est ici.}
{1104}{}{J'sais pas.}
{1105}{}{Le patron de Harry.}
{1106}{}{Des débiles.}
{1107}{}{Plus débiles que des Goules.}
{1108}{}{J'sais pas.}
