{100}{}{Tu vois un Goule zombifié.}
{101}{}{Tu vois un zombie.}
{102}{}{Hurk.}
{103}{}{Ceeerrrveeellle }
{104}{}{Beuu...}
{105}{}{gnnuuu..}
{106}{}{Grrrrr !}
{107}{}{Hagn.}
{108}{}{Euuuhh...}
{109}{}{Ahhh !}
{110}{}{Grrr !}
{111}{}{*grogne* }
{112}{}{*gargouillis* }
{113}{}{Mmmm }
{114}{}{*grogne* }

# Examining the ghouls, restored from original Fallout files

{200}{}{Tu examines la misérable créature, mais tu ne comprends pas ce qui l'a mis dans un état pareil.}
{201}{}{Elle semble avoir été humaine, ou du moins descendre d'humains. Tu supposes que la détérioration du corps est due à l'acide ou aux radiations.}
{202}{}{Le corps de l'humanoïde a l'air très irradié mais il fonctionne encore. D'humain, il semble avoir régressé vers un mode de vie plus animal.}
{203}{}{Le corps de l'humanoïde a l'air très irradié et les muscles et le cerveau semblent détériorés. Pourtant, d'après les indicateurs génétiques, tu penses qu'il descend, comme toi, des êtres entrés dans les Abris.}
{204}{}{La misérable créature est grandement irradiée. Tu n'arrives pas à savoir si sa folie est dû à l'enfermement ou aux dégâts irrémédiables causés à son cerveau par les radiations.}
{205}{}{Le corps de la créature est grandement irradié, cependant elle a conservé assez de matière grise et de fonction motrice pour pouvoir parler.}

# Messages when getting rads during combat with irradiated critters (glowing ones, radrats, etc)
# Listed in different formats, in case I want to implemented user choice of how it displays. --Sduibek

#Not currently used:
{300}{}{Tu reçois une faible dose de radiation.}
{301}{}{Tu reçois une dose modérée de radiation.}
{302}{}{Tu reçois une dose importante de radiation.}

#Not currently used:
{303}{}{Tu as été légèrement irradié.}
{304}{}{Tu as été irradié.}
{305}{}{Tu as été moyennement irradié.}
{306}{}{Tu as été grandement irradié.}

# THIS IS THE FORMAT CURRENTLY USED:

{1004}{}{Tu as reçu une faible dose de radiation.}
{1005}{}{Tu as reçu une légère dose de radiation.}
{1006}{}{Tu as reçu une dose modérée de radiation.}
{1007}{}{Tu as reçu une importante dose de radiation.}
