{100}{}{Meurs donc, vermine !}
{101}{}{Ma défaite sera vengée !}
{102}{}{Attends, Initié ! Qu'as-tu à déclarer ?}
{103}{}{Tout est calme sur le front Ouest.}
{104}{}{Des radscorpions et une chaleur insupportable...}
{105}{}{En fait, je voulais savoir si t'avais entendu quelque chose.}
{106}{}{Rien à signaler !}
{107}{}{Euhh ?}
{108}{}{Attends ! Je te reconnais ; on s'est vu à la Confrérie. Y'en a peut-être qui te font confiance, mais pas moi. Quelles sont tes activités ?}
{109}{}{C'est mes oignons, pas les tiens.}
{110}{}{Je voulais voir un visage amical.}
{111}{}{J'erre dans le désert, j'essaie de survivre.}
{112}{}{J'extermine la vermine du désert. Ca te convient pas ?}
{113}{}{Je ne parlerai qu'en présence de ton chef. Conduis-moi à la Confrérie.}
{114}{}{Activités ?}
{115}{}{Attends ! Je te reconnais et tu m'inspires pas confiance. Attention : tu nous causes le moindre ennui et c'est la mort. Ouste !}
{116}{}{Halte ! Qui va là ? Nom et activités !}

# TRANSLATION NOTES
# The player-character's name is inserted after line 117, and then has
# line 118, 119, 120, or 121 appended.
{117}{}{Je m'appelle }
{118}{}{ et je cherche une puce d'eau pour mon Abri. Peux-tu m'aider ?}
{119}{}{ et j'essaie de trouver l'origine des attaques de mutants.}
{120}{}{ et ça te regarde pas !}
{121}{}{ et je suis en quête d'aventures.}
{122}{}{Va te faire foutre, abruti de soldat.}
{123}{}{Euh !}
{124}{}{Halte ! Ces terres appartiennent à la Confrérie de l'Acier. File ou on t'abat pour intrusion.}
{125}{}{Très bien. Continue, Initié.}
{126}{}{Je vois. Continue, Initié.}
{127}{}{Des grands humains mutants attaquent les voyageurs, alors on redouble de vigilance. Surveille bien le secteur et, au besoin, réfugie-toi dans l'enceinte ! Initié, rompez !}
{128}{}{Les temps sont agités ! Les mutants sont sur le pied de guerre ; ils attaquent les caravanes ! On a besoin d'infos, et vite ! RAS, ça suffit pas !}
{129}{}{Bon, remue-toi le cul et rapporte des infos utiles ! Initié, rompez !}
{130}{}{Oh oui, j'ai entendu parler de toi. QI zéro, mais pour le combat, chapeau. Dommage.}
{131}{}{T'es chez nous et ici tes oignons sont nos oignons. Je répète : quelles sont tes activités ?}
{132}{}{Je cherche une puce d'eau pour mon Abri. Peux-tu m'aider ?}
{133}{}{J'essaie de trouver l'origine des attaques de mutants.}
{134}{}{Tu es peut-être chez toi, mais je suis pas ton esclave.}
{135}{}{J'erre dans le désert depuis longtemps. Je voulais savoir si vous avez des nouvelles.}
{136}{}{Un visage amical ? Pas le mien, en tout cas. Je te conseille de filer.}
{137}{}{Comme nous tous. Tant que tu ne nuis pas à la Confrérie, tu ne crains rien ; mais prends garde.}
{138}{}{Tout dépend si tu nous prends ou non pour de la vermine. Si tu attaques nos ennemis, tu pourras voyager sur notre territoire. Si tu nous offenses, tu mourras. Considère cela comme un avertissement.}
{139}{}{Ca me paraît raisonnable. Marché conclu.}
{140}{}{Puce d'eau ? Tu plaisantes, j'espère ! Tu ferais mieux de lutter au lieu de t'asservir à une pièce détachée.}
{141}{}{Comme nous. Selon la thèse la plus courante, ils seraient originaires du Rayon, mais je doute que quiconque puisse y survivre longtemps, mutant ou pas mutant. Si tu découvres quelque chose, fais-nous signe.}
{142}{}{Comment oses-tu insinuer une chose pareille ! La Confrérie de l'Acier n'a jamais forcé quiconque à nous servir. Ca va à l'encontre de toutes nos croyances. Hors de ma vue !}
{143}{}{On a trouvé une épave de caravane à une journée d'ici vers l'Ouest. Un seul survivant - une pauvre fille. Elle parlait d'humains mutants qui les auraient attaqués, des humains dotés d'une force incroyable.}
{144}{}{On a entendu assez de rapports pour être... inquiets. A ta place, j'irais avec prudence.}
{145}{}{Il va falloir que je t'enseigne les bonnes manières, mon gars. Ca va nous divertir un peu.}
{146}{}{Il va falloir que je t'enseigne les bonnes manières, ma fille. Ca va nous divertir un peu.}
{147}{}{T'es en plein délire. Malheureuse créature.}
{148}{}{Arrête de me faire perdre mon temps, imbécile !}
{149}{}{Que veux-tu ?}
{150}{}{Rien.}
{151}{}{Alors va-t-en.}
