{100}{}{Attention, ici la Maison des Gardes. Personne. Dehors !}
{101}{}{Crève !}
{102}{}{Une intrusion !}
{103}{}{Un hu-main !}
{104}{}{Halte. Secteur réservé. Toi, pas venir ici.}
{105}{}{Tu ferais mieux de te rendre.}
{106}{}{Toi arrêter. Moi t'emmener chez Lieutenant. Pas d'histoires sinon toi mourir.}
{107}{}{Euh !}
{108}{}{Crève, créature de l'enfer !}
{109}{}{Je souhaite parler à ton Maître.}
{110}{}{Je suis un mutant en mission pour le compte de ton Maître. Si tu me laisses pas passer, tu risques de le regretter.}
{111}{}{Je suis avec la Cathédrale. Laisse-moi passer.}
{112}{}{Crève !}
{113}{}{Comme tu veux.}
{114}{}{Bien. Alors, à la mort.}
{115}{}{Bon. Suis-moi, et pas de blague.}
{116}{}{D'accord. Allons-y.}
{117}{}{Pas de blague ? Mais t'auras l'air drôlement marrant quand je t'aurai boxé !}
{118}{}{Je te crois pas.}
{119}{}{Ca m'étonnerait.}
{120}{}{Non. Toi humain. Toi mourir.}
{121}{}{Si toi mentir, moi tuer toi.}
{122}{}{Oh, d'accord. Avance.}
{123}{}{Euh, bon. Peut-être mieux si toi voir Lieutenant.}
{124}{}{T'as tué mon frère. Je me vengerai !}
{125}{}{Crève !}
{126}{}{Meurtrier !}
{127}{}{Assassin !}
