{100}{}{Voici un membre de la bande des Skulz.}
{101}{}{Eh ! Où tu t'crois ?!}
{102}{}{T'es chez les Skulz. Tu ferais mieux de dégager.}
{103}{}{T'as pas quelques caps ?}
{104}{}{Qu'est-ce que tu reluques ?}
{105}{}{Fous le camp.}
{106}{}{Zzzzz}
{107}{}{Bon dieu, il fait chaud aujourd'hui.}
{108}{}{J'ai faim.}
{109}{}{Bon, faut faire quelque chose.}
{110}{}{Et si on emmerdait quelqu'un ?}
{111}{}{J'ai envie de me marrer un coup.}
{112}{}{Bâillement...}
