{100}{}{Voici un habitant de l'Abri.}
{101}{}{Je peux pas croire que tu nous aies trahis !}
{102}{}{Traître !}
{103}{}{Je te hais. T'aurais mieux fait de jamais revenir !}
{104}{}{J'espère que ta vilenie t'étouffera !}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Merci de nous avoir sauvés.}
{110}{}{Je doutais un peu de tes capacités, mais plus maintenant.}
{111}{}{Merci ! Merci !}
{112}{}{Tu es un héros. Mon petit garçon veut être comme toi plus tard. Je sais pas si c'est une bonne idée.}
{113}{}{Tu es une héroïne. Ma petite fille veut être comme toi plus tard. Je sais pas si c'est une bonne idée.}
{114}{}{T'es un type super !}
{115}{}{T'es une fille super !}
{116}{}{Tu crois vraiment en avoir besoin ici ?}
{117}{}{C'est une arme !}
{118}{}{Elle t'a vraiment servi contre quelqu'un ?}
{119}{}{Pourquoi crois-tu nécessaire de porter une arme ici ?}
{120}{}{Ca fait plaisir de te revoir.}
{121}{}{Je me réjouis de savoir que tu vas bien.}
{122}{}{Moi, tu me parais Ok. Toutes ces rumeurs doivent être fausses.}
{123}{}{Salut }
{124}{}{. Continue à faire du bon boulot.}
{125}{}{J'espère que tout va bien là-bas. Sûr que l'eau nous serait utile.}
{126}{}{L'eau commence à manquer. C'est terrible !}
{127}{}{Je t'en prie, dépêche-toi de trouver cette puce. On a besoin de toi.}
{128}{}{Je me réjouis de savoir que tu vas bien. Continue à faire du bon boulot.}
{129}{}{C'est navrant à dire, mais si tu tardes à trouver la puce d'eau, on va tous mourir.}
{130}{}{Mon bébé se réveille toutes les nuits pour réclamer de l'eau et j'ai rien à lui donner.}
{131}{}{On n'y arrivera pas, hein ?}
{132}{}{Les rations d'eau touchent à leur fin.}
{133}{}{Le service hydroponique vient de fermer. Ca veut dire qu'on va être à court de nourriture.}
{134}{}{Humm. T'as toujours l'air d'un humain. Ca peut pas être si méchant que ça dehors.}
{135}{}{Salut }
{136}{}{.}
{137}{}{J'espère que tu progresses dans ta quête.}
{138}{}{A un de ces quatre.}
{139}{}{T'as parlé au Dirigeant récemment ?}
{140}{}{Le Dirigeant s'inquiète beaucoup de la progression de ta mission.}
{141}{}{Faut te dépêcher. On compte tous sur ton succès.}
{142}{}{J'espère que tu fais tout ton possible.}
{143}{}{C'est pas le moment de se reposer, retourne dehors.}
{144}{}{Mais, c'est pas ça que tu dois faire !}
{145}{}{On va mourir, par ta faute.}
{146}{}{Reste pas là comme ça, retourne dehors ! Allez !}
{147}{}{Si on meurt, ce sera ta faute.}
{148}{}{Le monde extérieur a fait de toi un être corrompu, hein ?}
{149}{}{Qu'on me laisse tranquille !}
{150}{}{Je crois que tu devrais nous ficher la paix, à moi et ma famille, }
{151}{}{. Ce serait certainement mieux.}
{152}{}{Tu devrais avoir honte.}
{153}{}{Quand je pense que je t'estimais.}
{154}{}{L'habitant de l'Abri refuse de te parler.}
{155}{}{Tu reçois un regard vide en réponse à ta demande.}
{156}{}{Je regrette qu'on ait pu te choisir pour aller dehors.}
{157}{}{L'eau est infecte mais plus supportable que ta présence.}
{158}{}{Va-t'en. Illico. Tu peux te racheter en trouvant cette puce d'eau.}
{159}{}{J'espère que cela te satisfait.}
{160}{}{L'habitant de l'Abri refuse de te parler.}
{161}{}{C'est de ta faute ! C'est sans doute toi, aussi, qui avait détruit la puce d'eau !}
{162}{}{Je te hais. Vraiment, tu me fais horreur.}
{163}{}{L'habitant de l'Abri pleure à grosses larmes.}
{164}{}{Tu reçois un regard froid en réponse à ta demande.}
{165}{}{Merci.}
{166}{}{Il est tard. Reviens une autre fois.}
{167}{}{L'habitant de l'Abri se repose.}
