{100}{}{Un cadavre gît par terre.}
{101}{}{Une âme misérable gît ici.}
{102}{}{Les restes d'un humain muté gisent sur le sol.}
{103}{}{De la bonne terre à charognes.}
{104}{}{Il semble que cette personne ait défié Thanatos et perdu.}
