{100}{}{Voici Gidéon, un humain ordinaire. Il porte une couronne.}
{101}{}{Jason est un dieu vivant ! Seuls les annulés peuvent passer !}
{102}{}{Annulés ? Ce serait pas ces machins que tu portes qui limitent tes capacités psychiques ?}
{103}{}{Qui est Jason ?}
{104}{}{Qu'est-ce que tu veux dire par "annulés" ?}
{105}{}{Je viens de le tuer, alors ça doit être un dieu mort maintenant. Tu veux le rejoindre ?}
{106}{}{Hein ?}
{107}{}{Les murs aussi ont des esprits... Je t'ai vu... demain ?}
{108}{}{Y'en a d'autres comme toi dans le mur ?}
{109}{}{Laisse tomber.}
{110}{}{J'aimerais bien te tuer maintenant. Tu pourrais ouvrir ce champ de force ?}
{111}{}{Ouvre ce champ de force et je te laisse partir.}
{112}{}{Euh, ouais. Je cherche une 'expérience'... c'est peut-être toi ?}
{113}{}{Jason ? Qui est Jason ?}
{114}{}{Mais, tu viens de dire... non, rien.}
{115}{}{Arrête.}
{116}{}{Oui, les murs portent ceux qui les ont habités.}
{117}{}{Qu'est-ce qu'il leur est arrivé ?}
{118}{}{Euh, faut que j'y aille.}
{119}{}{La rencontre de l'âme... soudée, pour protéger, le Maître de tout.}
{120}{}{Je vois. Comment me protéger contre les protecteurs du Maître ?}
{121}{}{Et les chiens de guerre ?}
{122}{}{Je dois protéger le Maître. Comment arriver jusqu'à lui ?}
{123}{}{Je peux tuer n'importe qui, n'importe quoi. Ouvre ce champ de force et je vais te montrer.}
{124}{}{Au revoir.}
{125}{}{Il n'y a que la paix et se joindre à... le prix... la douleur... on doit être aveugle... annulé.}
{126}{}{Bon, il faut que me joigne à vous. Où est-ce que je peux trouver un de ces annulateurs ?}
{127}{}{Super ! Comment puis-je me joindre à vous ?}
{128}{}{Ca me plairait de joindre mon flingue et ta tête !}
{129}{}{J'ai pas de temps pour ça. Salut.}
{130}{}{Je dois te bénir... Je dois donner ce que je ne dois pas.}
{131}{}{Merci.}
{132}{}{Personne va me bénir, espèce de débile !}
{133}{}{Bénir ? Me bénir avec quoi ?}
{134}{}{Non, merci.}
{135}{}{Tu ne peux pas tuer le génie de... le tout... tu... euh !}
{136}{}{Ouais, mais je peux lui faire des grosses misères.}
{137}{}{Je ne veux pas tuer. Je veux adorer.}
{138}{}{Manifestement. Salut.}
{139}{}{Flegme ! Développement chimérique... communication, annul... fin de la mort.}
{140}{}{Les murs aussi ont des esprits... On s'est vu... demain, non ?}
{141}{}{Je prends ça pour un 'oui'.}
{142}{}{Super ! Comment faire pour s'unir ?}
{143}{}{Les blasphémateurs... se décomposent... la mort sera... le salut... forte !}
{144}{}{Les esprits... les murs... avant l'immense, le grand... }
{145}{}{Ceux qui sont déjà passés... doivent arrêter ton voyage.}
{146}{}{Faut que je change ça.}
{147}{}{Je dois terminer mon voyage ; le Maître l'exige.}
{148}{}{Qui ? A fait quoi ?!}
{149}{}{Ouais, mais je peux leur faire des grosses misères.}
{150}{}{Pardon de te déranger encore. Au revoir.}
{151}{}{J'aimerais t'aider à t'échapper.}
{200}{}{Voici Moore, un type à l'allure minable. Il porte une couronne.}
{201}{}{Voici un type à l'allure minable.}
{202}{}{L'asphalte sera rouge ! J'écraserai tout !}
{203}{}{Parfaitement.}
{204}{}{De quoi tu parles ?}
{205}{}{Ouais, il sera rouge de ton sang.}
{206}{}{Euh, ouais. Salut.}
{207}{}{Ourgh !}
{208}{}{J'arrêterai le moteur ! La Maître m'a donné le pouvoir...}
{209}{}{D'accord. J'aimerais rencontrer ton Maître, comment je fais ?}
{210}{}{Quel moteur ?}
{211}{}{Bien sûr ! Je comprends parfaitement...}
{212}{}{J'aimerais te fendre la caboche, pauvre cloche.}
{213}{}{Oh non, encore toi ! Salut.}
{214}{}{Seuls les puissants peuvent passer, mais ils en seront empêchés.}
{215}{}{Ouvre ce champ de force, je veux te montrer mon pouvoir.}
{216}{}{Mais faut que je voie le Maître !}
{217}{}{Tu peux me montrer comment ?}
{218}{}{Gidéon... Gidéon sait.}
{219}{}{Parfaitement.}
{300}{}{Voici Lucy, une humaine ordinaire. Elle porte une couronne.}
{301}{}{Voici une humaine. Elle regarde fixement tes chaussures.}
{302}{}{On n'est vraiment bien que chez soi, que chez soi, que chez soi... [Elle fait les cent pas.]}
{303}{}{Arg !}
{304}{}{Arrête !}
{305}{}{Et ici ? C'est pas chez toi ?}
{306}{}{Je suis d'accord. Parfaitement d'accord. Tu as raison... [Elle s'arrête un instant.] Qu'est-ce que t'as dit ? Oh, aucune importance.}
{307}{}{[Elle te fixe du regard.] Tu périras pour cela ! Ton sang, je le ferai couler rouge. Attends une minute. Le sang est rouge, comment je pourrais le faire couler rouge ? Difficile. Humm. Faut que je réfléchisse. Va-t'en !}
{308}{}{Chez moi, c'est, euh, ouais. Ici. Ouais, c'est ici. Je suis chez moi ! [Elle fait des bonds.] Je suis tellement contente ! Tu peux pas savoir. Tiens, je vais aller taper dans le mur quelques instants.}
{309}{}{Arrh, je travaille. J'ai presque la solution aux problèmes d'environnement qui empoisonnent ce monde, mais je peux pas m'empêcher de penser à ces dinosaures pourpres. Est-ce un problème ?}
{310}{}{Arrête de m'embêter, je réfléchis...}
{400}{}{Voici Wiggum, un parfait raté. Il porte une couronne.}
{401}{}{Voici un exemple de parfait raté.}
{402}{}{Je suis fatigué.}
{403}{}{Ma vie est un enfer.}
{404}{}{Je suis fatigué de vivre.}
{405}{}{L'obscurité revient.}
{406}{}{C'est ça.}
{500}{}{Sur les murs, on peut lire : 'Attention ! Ne pas déranger !'}
{501}{}{Tu gagnes }
{502}{}{ points d'expérience pour avoir persuadé le psy de te donner un Annulateur.}
