{100}{}{Tu vois un coffre.}
{101}{}{Ce coffre semble équipé d'une fermeture électronique.}
{102}{}{Tu déverrouilles le coffre sans problème.}
{103}{}{Ce verrou a l'air plus compliqué que tu ne le pensais.}
{104}{}{Tu viens facilement à bout du verrou du coffre.}
{105}{}{Ce verrou a l'air plus compliqué que tu ne le pensais.}
{106}{}{Cette compétence ne te permet pas d'ouvrir le coffre.}
