{100}{}{Voici un nain replet.}
{101}{}{Voici Gretch, l'assistant de Doc Morbide.}
{102}{}{Qu'est-ce tu viens faire ici ?}
{103}{}{Euhh ?}
{104}{}{Ton patron m'envoie.}
{105}{}{Me cause pas comme ça, imbécile.}
{106}{}{Prendre de tes nouvelles.}
{107}{}{Rien. Salut.}
{108}{}{Je te connais... non ?}
{109}{}{Non.}
{110}{}{Oui.}
{111}{}{T'occupes.}
{112}{}{Hum... ça va pas mal.}
{113}{}{Qu'est-ce que tu fais ?}
{114}{}{Pas mal ? Ca veut dire que t'es pratiquement foutu ?}
{115}{}{T'es un peu long à la détente, non ?}
{116}{}{Oui, oui, pratiquement foutu.}
{117}{}{Avec quoi ?}
{118}{}{Il est temps.}
{119}{}{Super. A plus tard.}
{120}{}{Les morceaux d'humain sont presque prêts à être expédiés au Centre.}
{121}{}{Pour quoi faire ?}
{122}{}{Bien sûr. C'est pour ça que je suis là.}
{123}{}{Bon, je préfère pas entendre parler de ça.}
{124}{}{Pour l'iguane, Bob t'envoie... content, plein de bonne viande...}
{125}{}{Il sert de la chair humaine à ses clients ?}
{126}{}{Imbécile, je vais te transformer en andouille !}
{127}{}{Bien sûr... Je reviens dans une minute.}
{128}{}{C'est pour Bob, les vendre, les manger, un point c'est tout... Pourquoi tu veux des détails ?}
{129}{}{Oh, pour rien. Salut.}
{130}{}{Je savais pas trop où Bob se procurait sa viande humaine.}
{131}{}{Parfois, j'ai un peu de mal à réfléchir.}
{132}{}{Moi aussi, j'ai le cerveau lent... de quoi on parle ?}
{133}{}{Je sais plus. Salut.}
{134}{}{Tu me parlais de ce que tu fais.}
{135}{}{On parlait de ta connerie.}
{136}{}{J'sais pas.}
{137}{}{Je te parle plus.}
{138}{}{Oui... Doc Morbide a les meilleurs corps d'humain du coin. Imbattables.}
{139}{}{Euh... Je reviens pour prendre les... corps... dans un petit moment. Salut.}
{140}{}{Je retourne au boulot maintenant.}
{141}{}{Ah, plaisante pas avec les affaires du Docteur !}
