# Necropolis motorcycle npc

{100}{}{Tu vois : Griffith.}
{101}{}{Cette goule porte une vieille veste de moto rapiécée. Tu peux voir des anciennes trace de tatouages sur sa peau pourrie.}

{125}{}{Tu gagnes  }
{126}{}{ points d'expérience pour avoir aidé Griffith à quitter Necropolis.}
{127}{}{ points d'expérience pour avoir volé la moto.}
{128}{}{ points d'expérience pour avoir obtenu la moto.}

# Float: (When using the bike without owning it and having talked to Griffith at least once.)
{160}{}{Tu es une enflure de VOLEUR !}
{161}{}{De quoi ? Où est ma ... ?!}

{200}{}{Griffith ne semble pas revenir. Peut-être que vous devriez essayer de le retrouver ?}
{201}{}{Il prend vraiment son temps ...}
{202}{}{Euh ... chii-aannt.}

# Dialog:
{500}{}{Retire tes sales pates de ma bécanne, peaudouce !}
{501}{}{Je t'ai dit de ne pas y toucher !}
   {510}{}{Va caguer !}
   {520}{}{Oh, Ok.}

{1000}{}{Hé peaudouce, qu'est-ce que tu regardes ?}
{1001}{}{T'es toujours là, peaudouce ?}
{1002}{}{Vous avez changé d'avis, peaudouce ?}
   {1010}{}{Qui êtes vous ?}
   {1020}{}{Qu'est-ce que vous faites ici ?}
   {1030}{}{Est-ce que c'est votre moto ?}
   {1031}{}{Vous pourriez me parler de votre moto à nouveau ?}
   {1040}{}{D'accord, je vais garder votre moto.}
   {1050}{}{Eeeeuhh... Toi qui ??}

{1100}{}{Il m'appellent Griffith.}
   {1110}{}{Qu'est-ce que tu fait là, Griffith ?}
   {1120}{}{Excellent. A plus tard, Griffith !}
   
{1200}{}{Qu'est-ce que tu crois que je fait ?}
   {1210}{}{Aucune idée. Vous attendez quelqu'un ?}
   
{1300}{}{Exactement ! Et vous savez quoi ? J'ai trouvé la personne que j'attendais !}
   {1310}{}{Vraiment ?}
   
{1400}{}{Il y a quelque chose que je dois faire. Cela va me prendre quelques heures, et je ne peux pas laisser ma bécanne sans surveillance.}
   {1410}{}{Tu veux que je garde ta moto ?}
   {1420}{}{Que dois-je faire ?}
   
{1500}{}{Les autres goules ici, elles en ont rien à foutre et je peux pas leur faire confiance.}
{1501}{}{Toi en revanche, je peux dire que tu fait attention à ce que tu fait ! Et puis, je te paierai si tout est encore là à mon retour.}
   {1510}{}{C'est combien la paie ?}
   {1520}{}{Oui je pense pouvoir faire ça.}

{1600}{}{Un sac de capsules ? Ce n'est pas un travail si compliqué. Cela va juste te demander du temps.}
   {1610}{}{Je suppose que je peux faire ça.}
   {1620}{}{Désolé, mais je n'ai pas le temps pour ça. A plus tard.}
   
{1700}{}{Génial ! Je reviendrais dans quelques heures.}
   {1710}{}{[Tu regardes la goule disparaitre dans les égouts]}
   
{1800}{}{Peaudouce, tu es débile ou quoi ? J'ai besoin que quelqu'un garde ma bécanne !}
   {1810}{}{Hé, ne me traite pas de déile !}
   {1820}{}{Oh.}

{1900}{}{C'est ma bécanne, ouais.}
   {1910}{}{Est-ce que tu peux m'en parler ?}
   {1920}{}{On dirait une Chryslus Motors Cruiser originale. J'en ai vu sur des vieilles holobandes !}
   
{2000}{}{Ce que tu vois c'est une Chryslus Motors Cruiser originale, fabriquée en... Euh... En fait j'en sais rien, mais c'est de la super tech d'Avant-Guerre ! J'ai réussi à la conserver et à la faire fonctionner toutes ces années déjà.}
   {2010}{}{Tu la vends ?}
   
{2100}{}{Si je ... quoi ? Est-ce que tu te fiche de moi, peaudouce ? Je ne vendrais jamais ma bécanne !}

{2200}{}{Et ben merde. Tu es aussi inutile que tout le monde ici.}

{2300}{}{Exactement, peaudouce ! Une des plus belles machines que l'humanité ait réussi à fabriquer !}

{2400}{}{On dirait que tu connais mieux ces bécannes d'Avant-Guerre que moi.}


# Dumb dialog:
{3000}{}{Sacré nom d'une brahmine en rut, tu es aussi stupide que tu en a l'air, n'est-ce pas ?}
	{3010}{}{Ehh...}

{3100}{}{Je vais te dire, peaudouce... Il y a quelque chose que tu dois faire. Hé, tu m'écoute ?}
{3101}{}{Si tu fais ce que je te dit, je te donnerai de jolies bling-bling, tu comprend ? Tiens, plein de capsules ! Tu aime les capsules non ?}
	{3110}{}{Moi aimer !}
	{3120}{}{No-ohn.}

{3200}{}{Tu quoi ? Tu n'aime pas les capsules peaudouce ? Bordel t'es vraiment pire que ce que je pensais.}
	{3210}{}{Moi partir.}
	{3220}{}{Euh, moi aimer caps !}

{3300}{}{Parfait, parfait ! Ecoute. Je dois partir pour un moment. Tu comprends ? *Moi* partir. *Toi* rester ici. Personne ne touche à ma bécanne, okay ? Bien. Je ne serai pas long, attends juste ici.}
   {3310}{}{[Tu regardes la goule disparaitre dans les égouts]}
