{100}{}{Malheureusement y'a pas de boxe aujourd'hui.}
{101}{}{Hum.}
{102}{}{D'accord.}
{103}{}{C'est quand le prochain match ?}
{104}{}{Tu peux peut-être essayer chez Gizmo. On dit qu'il recherche toujours de la viande fraîche pour le ring.}
{105}{}{Essaie demain. Y'a Saul qui boxe.}
{106}{}{Tu viens de le manquer. Essaie après-demain. Saul boxe tous les trois jours.}
{107}{}{Merci.}
{108}{}{Qui c'est, Saul ?}
{109}{}{Saul, c'est le champion local, le favori actuel de Gizmo.}
{110}{}{Eh, là ! Y'a pas de boxe aujourd'hui.}
{111}{}{ Reviens demain.}
{112}{}{ Reviens après-demain.}
{113}{}{Alors ! On veut parier sur le combat ?}
{114}{}{J'ai mieux à faire de mon argent. Salut.}
{115}{}{Qui part favori ?}
{116}{}{Non, merci. Par contre, est-ce que je peux te poser quelques questions ?}
{117}{}{}
{118}{}{Malheureuseemnt le match d'aujourd'hui est déjà fini.}
{119}{}{Oh. Bon, tant pis.}
{120}{}{Sur qui tu veux parier, Saul ou son challenger ? C'est Saul le favori. Ca coûte 25 caps de parier ; t'en reçois 50 si tu gagnes en misant sur Saul, 100 si tu gagnes en pariant sur le challenger !}
{121}{}{Je mise sur Saul.}
{122}{}{Je mise sur le challenger.}
{123}{}{C'est bon.}
{124}{}{Qui est le boxeur ?}
{125}{}{Qui organise ces matchs ?}
{126}{}{Euh, n'importe.}
{127}{}{Ah, j'ai pas le temps. Peut-être plus tard.}
{128}{}{Saul, le poing le plus rapide de Dépôtville ! Une merveille musculaire ! Un punch écrasant !}
{129}{}{C'est aussi un chouette type.}
{130}{}{Hum, ouais. Alors, qui organise ces matchs ?}
{131}{}{Merci. A un de ces quatre.}
{132}{}{Gizmo, le proprio du casino, emploie Saul. Ca lui arrive de regarder un match ou deux pour le plaisir, mais c'est surtout parce que ça rapporte - les gens parient gros sur un combat. Et personne se fait buter, pas comme ces matchs de la mort qu'ils organisent, paraît-il, au Centre.}
{133}{}{Des matchs de la mort ?}
{134}{}{Merci.}
{135}{}{Oh, à ce qu'il paraît. Il y aurait un ring clandestin où on paie pour regarder les gens se battre à mort. C'est pas mon truc.}
{136}{}{Hum. Merci.}
{137}{}{Eh, qu'est-ce que tu fous ?}
{138}{}{Euh, rien.}
{139}{}{Tu cherches les ennuis, imbécile ?}
{140}{}{Arrête ça.}
{141}{}{Euh, rien. Oublie ce que je t'ai dit.}
{142}{}{Ah, ah ! On dirait que t'as de la veine. Voilà tes caps.}
{143}{}{Reviens quand t'auras assez d'argent !}
{144}{}{Tu veux attendre ici jusqu'à ce le combat commence, à 2 :00 ?}
{145}{}{Oh ma foi oui.}
{146}{}{Non, j'ai des trucs à faire. Je reviendrai.}
{147}{}{D'accord, mais si tu manques le combat, tu perds ton pari !}
{148}{}{Que le match commence !}
{149}{}{S'il te plaît, me dérange pas pendant le match.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{150}{}{Et bien l'ami, on peut pas toujours gagner ! Tu seras plus chanceux la prochaine fois.}
{151}{}{Et bien l'amie, on peut pas toujours gagner ! Tu seras plus chanceuse la prochaine fois.}

{152}{}{Un seul pari par combat. Désolé.}
