{100}{}{Voici un garde la Confrérie.}
{101}{}{De la vigilance, Initié ! Toujours !}
{102}{}{Ca m'a l'air bien. Continue à faire du bon travail.}
{103}{}{Bonjour, Initié, tout est en ordre.}
{104}{}{Désolé, je dois parler à personne. Tu sais ce que c'est.}
{105}{}{Si t'as des questions, adresse-toi à Talus ou à Maxson.}
{106}{}{Si t'as des questions techniques, Vree est dans la bibliothèque pendant la journée.}
{107}{}{Rhombus est mon idole.}
{108}{}{Ah, si je pouvais m'entraîner maintenant, au lieu de perdre mon temps à monter la garde.}
{109}{}{Vree est mon idole.}
{110}{}{Salut, Frère }
{111}{}{.}
{200}{}{Seuls les Scribes et les Paladins sont autorisés dans cette salle.}
{201}{}{On t'avait pourtant dit de ne pas essayer d'entrer. Maintenant, on va s'occuper de ton cas.}
{202}{}{Désolé, seuls les membres de la Confrérie peuvent entrer.}
