# Beth is female. She speaks with a normal accent. She is a friendly person
# who is mostly interested in selling equipment and information.
{100}{}{Voici Beth, propriétaire de l'Armurerie.}
{101}{}{Bonjour. Je peux t'aider ?}
{102}{}{Je peux te poser quelques questions ?}
{103}{}{Je peux te poser encore quelques questions ?}
{104}{}{Je voudrais acheter quelque chose.}
{105}{}{J'ai quelque chose à vendre.}
{106}{}{Comment peut-on faire de l'argent dans le coin ?}
{107}{}{Oh, non. Au revoir.}
{108}{}{Hein ?}
{109}{}{Quelle est la rumeur sur les caravanes disparues ?}
# the Deathclaw is male
{110}{}{Qu'est-ce que tu sais sur le Griffemort ?}
{111}{}{Peux-tu me redire ce que tu sais sur le Griffemort ?}
# Decker is male
{112}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{113}{}{Qu'est-ce que tu peux me dire sur les différents marchands ?}
{114}{}{T'as entendu des rumeurs intéressantes ?}
{115}{}{Merci, c'est tout. Au revoir.}
{116}{}{Hmm, aucune importance.}
# Jain is a female religious figure
{117}{}{Eh bien, les commérages c'est pas mon genre... mais il paraît que la mort de Decker serait liée à l'assassinat de Jain.}
# The Maltese Falcon is a bar
{118}{}{Eh bien, c'est pas mon genre de colporter les ragots, mais je connais quelqu'un qui connaît quelqu'un qui dit avoir vu trois silhouettes vêtues d'immenses robes entrer au Faucon Maltais juste avant les meurtres.}
# the Children of the Cathedral is an organization - religious
{119}{}{Eh bien, c'est pas mon genre de colporter les ragots, mais quelqu'un à tué Jain, la Grande Prêtresse des Enfants de la Cathédrale. C'est pas que je les aie à la bonne, mais je sais pas ce qu'elle avait pu faire pour mériter ça.}
# The Brotherhood of Steel is an organization - religious
{121}{}{Eh bien, c'est pas mon genre de colporter les ragots, mais un ami à moi, un marchand, a vu un groupe de mutants rôder dans le désert, au-delà de la Confrérie de l'Acier, tout au Nord-Ouest.}
{122}{}{Eh bien, c'est pas mon genre de colporter les ragots, mais les Enfants de la Cathédrale demandent aux gens où tu es. Prends garde. Ils sont pas nets.}
{123}{}{Eh bien, les commérages c'est pas mon genre, mais il paraît que la mort de Decker serait liée à l'assassinat de Jain.}
{124}{}{C'est pas tout. je connais quelqu'un qui connaît quelqu'un qui dit avoir vu trois silhouettes vêtues d'immenses robes entrer au Faucon Maltais juste avant les meurtres.}
{125}{}{Quelqu'un à tué Jain, la Grande Prêtresse des Enfants de la Cathédrale. C'est pas je les aie à la bonne, mais je sais pas ce qu'elle avait pu faire pour mériter ça.}
{126}{}{C'est pas tout. Un ami à moi, un marchand, a vu un groupe de mutants rôder dans le désert, au-delà de la Confrérie de l'Acier, tout au Nord-Ouest.}
{127}{}{C'est pas tout. Les Enfants de la Cathédrale demandent aux gens où tu es. Prends garde. Ils sont pas nets.}
{128}{}{C'est tout ?}
{129}{}{Merci. Je peux encore te poser une question ?}
{130}{}{D'accord, merci.}
{131}{}{De quoi s'agit-il ?}
# Klug and Ruk are a stupid person saying something incomprehensible
{132}{}{Hein ? }
{133}{}{Euh !}
{134}{}{Je regrette, je comprends rien. Reviens quand tu iras mieux.}
# The Merchant Market is a location
{135}{}{Ah, moi j'embauche pas, mais tu trouveras une agence pour l'emploi au centre du Grand Marché. Va te renseigner.}
{136}{}{D'accord, merci.}
{137}{}{Non, rien d'intéressant en tout cas. Laisse-moi le temps de chercher un peu. <Elle te fait un clin d'oeil >. Autre chose ?}
{138}{}{Oui.}
{139}{}{Non.}
{140}{}{Je peux faire autre chose pour toi ?}
{141}{}{Bien sûr, sois pas bête.}
{142}{}{Certainement, si je peux rendre service. Qu'est-ce que tu veux savoir ?}
{143}{}{C'est bon. Tout le plaisir était pour moi, bonne journée.}
{144}{}{Non, c'est tout. Tu voulais parler d'autre chose ?}
{145}{}{Oui.}
{146}{}{Non.}
{147}{}{Eh bien, tarde pas à revenir. Sois pas timide.}
{148}{}{Ah, en voilà un à éviter, il me fait peur. C'est le 'propriétaire' du Faucon Maltais.}
{149}{}{Pourquoi tu dis ça comme ça : le 'propriétaire' du Faucon Maltais ?}
{150}{}{Pourquoi te fait-il peur ? }
{151}{}{Désolée, c'est juste qu'il me rappelle un ami qu'était propriétaire avant lui. Decker voulait la boîte à tout prix, mais mon ami refusait de vendre. Deux jours après, on l'a retrouvé mort dans une ruelle de la Vieille Ville.}
{152}{}{Pourquoi tu crois que c'est un coup de Decker ?}
{153}{}{Ah, il aurait pas dû prendre le risque de se frotter à Decker.}
{154}{}{Malheureusement faut que je parte.}
{155}{}{Cet ami, un vrai phénomène. Il se serait pas approché à cent mètres de la Vieille Ville. Il a été flingué par un Magnum, et y'a personne dans la Vieille Ville qu'aurait pu s'en offrir un. Et puis, il a reçu une balle dans la tête et deux dans le dos. Ca sent le vol ça ? Non, mon ami essayait seulement de retrouver son indépendance.}
{156}{}{Eh, il me plaît bien. Une fois que tu l'auras tué, dépose son corps à l'endroit qu'il déteste le plus.}
{157}{}{Son indépendance ?}
{158}{}{C'est triste d'entendre ça.}
{159}{}{Ah bon.}
{160}{}{Tu comprends sans doute pas, mais nous n'attendons qu'une seule chose : le jour où nous prendrons notre vie en main. Le jour où nos vies n'appartiendront plus aux marchands ou aux prêteurs sur gages.}
{161}{}{Oh, merci.}
{162}{}{Ca t'arrive d'arrêter de causer ?}
{163}{}{Jamais j'ai entendu pareille idiotie !}
{164}{}{Puis-je faire autre chose pour toi ?}
{165}{}{Ah, excuse-moi. C'est toi qu'a demandé.}
{166}{}{C'est le plus dangereux du Centre. La plupart disent que c'est lui qui y fait la loi, pas les marchands ni la police. Si jamais tu le croises, fais gaffe.}
{167}{}{Ca lui donne pas le droit de tuer.}
{168}{}{Ah, tu me fatigues, décampe. Sûr que tu lui manques.}
{169}{}{Bon, il y a trois principaux groupes de marchands : les Marchands d'Eau, la Caravane Ecarlate et les Marchands du Lointain. Ils dirigent aussi le conseil municipal. Qu'est-ce que tu veux savoir ?}
{170}{}{Les Marchands d'Eau.}
{172}{}{La Caravane Ecarlate.}
{173}{}{Les Marchands du Lointain.}
{174}{}{Le conseil municipal.}
{175}{}{C'est tout. Merci pour les informations.}
{176}{}{Oh, aucune importance.}
{177}{}{Ils ont la main mise sur toute l'eau. Des rapaces, je voudrais pas travailler pour eux. Ils offrent la paie la plus minable et le boulot vaut pas mieux.}
{178}{}{Ils ont toujours contrôlé l'eau ? }
{179}{}{C'est eux les responsables des caravanes disparues ?}
{180}{}{Merci, encore une question sur les marchands.}
{181}{}{Merci, au revoir.}
{182}{}{Qu'est-ce que tu veux savoir d'autre ?}
{183}{}{Non. A ce qu'il paraît, y'a longtemps de ça, un groupe de marchands s'est emparé du château d'eau et ils se sont proclamés "marchands d'eau". Pour avoir de l'eau, fallait passer par eux. La guerre des marchands a fait rage pendant des années, jusqu'à l'intervention d'un homme, Roy Greene... ouais, le grand-père de Justin, c'est ça. Grâce à lui, on a pu négocier un accord qu'a mis fin à cette guerre.}
{184}{}{Quelle sorte d'accord ?}
{185}{}{Bon sang ! Je regrette ma question.}
{186}{}{Merci, encore une question sur les marchands...}
{187}{}{Merci, au revoir.}
{188}{}{Eh bien, il a établi le conseil municipal et fixé une limite sur le prix de l'eau. Personnellement, je pense qu'ils auraient dû leur arracher tripes et boyaux... Oh, pardon. Enfin, leur montrer qui était le patron.}
{189}{}{Super. J'en demandais pas tant mais merci quand même pour tous ces renseignements.}
{190}{}{Merci, encore une question sur les marchands...}
{191}{}{Merci, au revoir.}
{192}{}{Désolée, je me laisse souvent emporter. Autre chose que tu voulais savoir ?}
{193}{}{La Caravane Ecarlate, une bande de cinglés ! Ils feraient n'importe quel boulot, risque ou pas risque. C'est étonnant qu'ils n'aient pas plus de caravanes qui disparaissent.}
{194}{}{Ils ont aussi des caravanes qui disparaissent ?}
{195}{}{Quel genre de risque ?}
{196}{}{Merci, encore une question sur les marchands...}
{197}{}{Merci, au revoir.}
{198}{}{Ils n'hésitent pas à traverser une région connue pour être attaquée par les pillards. Ils vendent cher, comme ça, ils ont les moyens d'embaucher plus de personnel. Le salaire est bon, mais encore faut-il rester en vie pour le dépenser, pas vrai ?}
{199}{}{Ils ont aussi des caravanes qui disparaissent ?}
{200}{}{Merci, encore une question sur les marchands.}
{201}{}{Merci, au revoir.}
{202}{}{En fait, tous les marchands ont des caravanes qui disparaissent. Sans doute que les Marchands du Lointain n'ont pas de chance.}
{203}{}{Quel genre de risque ?}
{204}{}{Merci... encore une question sur les marchands...}
{205}{}{Merci, au revoir.}
{206}{}{Les Marchands du Lointain paient bien et le boulot est pas trop déplaisant. C'est Butch qui possède le magasin, un brave homme. Ils sont corrects et ils me laissent faire ce que je veux. J'aime bien travailler avec eux. Et puis, t'as des remises sur tout ce que t'achètes ici si tu travailles pour Butch.}
{207}{}{A mon avis, non. Ce serait plutôt le Griffemort ou peut-être la Confrérie de l'Acier.}
{208}{}{Pourquoi tu crois pas que c'est les Marchands d'Eau ?}
{209}{}{C'est quoi au juste, un Griffemort ?}
{210}{}{Tu peux me reparler du Griffemort ? }
{211}{}{C'est quoi, la Confrérie ?}
{212}{}{La Confrérie de l'Acier ? Pourquoi ?}
{213}{}{Merci, revenons à nos marchands.}
{214}{}{Ok. Bon, faut que je parte.}
{215}{}{Certains pensent que les Marchands d'Eau sont responsables, mais je crois pas. Ce serait plutôt ce maudit Griffemort, ou peut-être les gens de la Confrérie de l'Acier.}
{216}{}{Ah, je pensais qu'il détruisait les caravanes, mais peut-être pas. N'empêche qu'il rôde toujours. Avec toutes ces rumeurs, on ne peut pas douter de son existence.}
{217}{}{Ca doit être ça qui fait disparaître les caravanes. A moins que... la Confrérie de l'Acier... encore pas nets ceux-là. Certains disent que ce sont les Marchands d'Eau qui ont fait le coup mais ils ont tort.}
{218}{}{Certainement.}
{219}{}{Parce que, comme je le répète souvent, certaines de leurs caravanes ont aussi disparu. Pas autant que pour les Marchands du Lointain, mais quand même...}
{220}{}{Peut-être qu'ils mentent ou qu'ils ont manigancé ça pour qu'on les croie.}
{221}{}{Pourquoi les Marchands du Lointain seraient-ils plus touchés que les autres ?}
{222}{}{Encore une question sur les caravanes disparues...}
{223}{}{Merci, revenons à nos marchands.}
{224}{}{Tu racontes n'importe quoi !}
{225}{}{Merci, mais faut que j'y aille.}
{226}{}{Excuse, mais t'as le jugement bien hâtif... c'est la vérité qui te gêne ?}
{227}{}{Il y a six représentants : deux pour chaque principal groupe de marchands. Pour la moindre décision, il leur faut toujours au moins quatre votes, jamais ils arrivent à s'entendre.}
{228}{}{Pas bête, mais ça m'étonnerait fort. Ca fait des années qu'ils se tirent dans les pattes. Mais ça, c'est pas leur style, ils dépenseraient pas tant d'argent pour voler les caravanes. Sans compter qu'elles sont bien gardées. Quelqu'un réussirait à s'échapper. Ils ont pas les moyens, ni en hommes ni en argent, pour un coup pareil. Il y aurait au moins un survivant.}
{229}{}{Pourquoi les Marchands du Lointain seraient-ils plus touchés que les autres ?}
{230}{}{Encore une question sur les caravanes disparues...}
{231}{}{Merci, revenons à nos marchands.}
{232}{}{Merci, mais faut que je m'en aille.}
{233}{}{Malchance ? Ou peut-être qu'ils suivent pas les mêmes itinéraires que les autres. Peut-être parce qu'ils sont pas aussi bien gardés que la Caravane Ecarlate ou... qu'ils ont un meilleur chargement que les Marchands d'Eau. Qui sait. On voit pas trop la différence entre les trois.}
{234}{}{Peut-être que les Marchands d'Eau mentent ou qu'ils ont manigancé ça pour que tu les croies.}
{235}{}{Encore une question sur les caravanes disparues...}
{236}{}{Merci, revenons à nos marchands.}
{237}{}{Ca t'arrive donc jamais d'arrêter de parler !}
{238}{}{Merci, mais faut que je parte.}
{239}{}{Excuse-moi ! Personne te retient. Si la réponse te gêne, fallait pas demander.}
{240}{}{Le Griffemort est la pire chose qui soit née des cendres de la guerre. Certains disent que c'est un puissant fantôme de la guerre qui hante le pays. Mais ce n'est pas plus fantôme que toi et moi. Six mètres de haut, avec des dents aussi grosses que ton bras. Une espèce de démon qu'a profité de la guerre pour s'introduire ici.}
{241}{}{Euh, je regrette ma question.}
{242}{}{Tu délires ! Je devrais mettre fin à tes maux illico presto.}
{243}{}{Tu sais autre chose sur le Griffemort ?}
{244}{}{Waouh ! Tu sais où il est ?}
{245}{}{Ben, je connais ce vieux mutant dans la Vieille Ville, Harold. Il l'a vu. Il est le "seul" à l'avoir vu et à être encore en vie.}
{246}{}{Le seul qui l'ait vu et qui soit en vie ?}
{247}{}{Certes, et moi je suis le papa du Griffemort !}
{248}{}{Certes, et moi je suis la maman du Griffemort !}
{249}{}{Encore une question sur les caravanes disparues...}
{250}{}{Merci, revenons à nos marchands.}
{251}{}{Je vais jeter un oeil. A un de ces quatre.}
{252}{}{Y'a aussi l'Oncle Slappy, dans la Vieille Ville, qui en parle des fois. Mais c'est un vieux gâteux.}
{253}{}{Encore une question sur les caravanes disparues...}
{254}{}{Merci, revenons à nos marchands.}
{255}{}{Merci. Je vais jeter un oeil. Au revoir.}
{256}{}{Tu verras !}
{257}{}{Ouais, plutôt étonnant, non ? C'est quelque part au Sud-Ouest. Y'a un vieux mutant dans la Vieille Ville, Harold, qui a vu de ses yeux vu cette chose dans son repaire. Le Skag le plus sympa que je connaisse.}
{258}{}{Encore une question sur les caravanes disparues...}
{259}{}{Merci, revenons à nos marchands.}
{260}{}{Merci. Je vais jeter un oeil. Au revoir.}
{261}{}{La Confrérie de l'Acier, une bande de fous qui vénèrent la technologie. Ils sont un peu plus au Nord-Ouest. Il font des sacrifices humains et toutes sortes de choses horribles.}
{262}{}{C'est absurde ! Qui t'a raconté ça ?}
{263}{}{Encore une question sur les caravanes disparues...}
{264}{}{Merci, revenons à nos marchands.}
{265}{}{C'est horrible ! Merci de me prévenir. Au revoir.}
{266}{}{Hmm, j'ai oublié. Mais en tout cas, il ou elle était pas du genre à mentir... Bref, ça pourrait être vrai ! Méfie-toi tout de même.}
{267}{}{Encore une question sur les caravanes disparues...}
{268}{}{Bon, revenons à nos marchands.}
{269}{}{Imbécile !}
{270}{}{Eh, t'as vu l'heure, faut que je parte ! A un de ces quatre.}
{271}{}{Quoi, t'es pas au courant ? [tout bas] Il paraît qu'ils font des sacrifices humains et toutes sortes de choses horribles !}
{272}{}{Oui, c'est vrai. Où est le mal ?}
{273}{}{En tant que MEMBRE de la Confrérie, je peux te JURER qu'il ne se passe RIEN de tel !}
{274}{}{Ah bon ? J'y ai fait un tour. C'est vrai qu'ils ont l'air étranges, mais tout de même !}
{275}{}{Ah bon ? J'aurais pas cru.}
{276}{}{Comme si t'en savais rien ! T'en fais partie, c'est évident, à te promener comme ça en combinaison métallique. Vous êtes tous une bande de désaxés.}
{277}{}{Je sais pas où tu veux en venir, mais je peux te jurer qu'il n'y a pas de "désaxés" à la Confrérie.}
{278}{}{Ouais, c'est vrai. On l'est tous, non ?}
{279}{}{J'aurais pas cru.}
{280}{}{S'il vous plaît, monsieur. Posez votre arme.}
{281}{}{S'il vous plaît, madame. Posez votre arme.}
{282}{}{Pardon, mais je ne t'aiderai que quand t'auras posé ton arme. C'est une boutique ici, pas un champ de tir.}
{283}{}{Euh... enfin, hmm... Tu... Je... Tu voulais autre chose ?}
{284}{}{On ne sait jamais ce que font les gens, derrière les portes closes. Surveille tes fréquentations. Tu voulais autre chose ?}
# Not believing the player for a moment, then getting nervous
{285}{}{Tu es... ? Je veux dire. Je voulais pas... hum... Belle journée, n'est-ce pas ? Euh, autre chose pour ton service ?}
{286}{}{Encore une question sur les caravanes disparues... }
{287}{}{Merci, revenons à nos marchands.}
{288}{}{Non, c'est tout. Au revoir.}
{289}{}{Certainement, c'est comme tu l'entends. Autre chose pour ton service ?}
{290}{}{Parfait ! Attends, je vais te montrer ce que j'ai.}
{291}{}{J'ai les meilleures marchandises de la région. Qu'est-ce que tu cherches ?}
{292}{}{Ah, ça fait plaisir à entendre. Qu'est-ce qu'il te faut ?}
{293}{}{Bien, faisons affaire.}
{294}{}{Si t'as de l'argent, tu m'intéresses.}
{295}{}{Un client comme je les adore !}
{296}{}{Tu veux acheter quelque chose ? Peut-être que je me suis trompée sur ton compte.}
{297}{}{Oh, exact. Tu travailles pour Butch, ça te fait 15% de réduction.}
{298}{}{Je te fais quand même une remise de 15%, parce tu m'es sympathique.}
{299}{}{Désolée, plus de remise.}
{300}{}{Montre ce que t'as.}
{301}{}{T'as quelque chose d'intéressant ?}
{302}{}{Bon, voyons ça.}
{303}{}{Certainement.}
{304}{}{Qu'est-ce que t'as à me proposer aujourd'hui ?}
{305}{}{Magnifique ! J'ai jamais trop de marchandise.}
{306}{}{Je me ferai un plaisir de voir ce que t'as.}
{307}{}{Essaie pas de m'arnaquer.}
{308}{}{Si tu me vends quelque chose, je veux de la qualité.}
{309}{}{Attention, me fais pas perdre mon temps.}
{310}{}{J'espère cette fois que t'as quelque chose qui m'intéresse.}
{311}{}{Ah, re-bonjour. Qu'est-ce qui me vaut le plaisir par une si belle journée ?}
{312}{}{Tiens, bonjour ! Ca fait plaisir de te revoir. Qu'y a-t-il pour ton service ?}
{313}{}{Ah, si seulement je pouvais prendre un jour de congé, il fait tellement beau !}
{314}{}{Tiens, re-bonjour ! On est sur son trente et un, aujourd'hui !}
{315}{}{Déjà de retour ?}
{316}{}{Tu viens juste de partir. Je te manque déjà ?}
{317}{}{T'as déjà besoin de quelque chose ?}
{318}{}{Alors, tu te fais rare ! Qu'est-ce qu'il te faut aujourd'hui ?}
{319}{}{Eh bien ! Ca fait longtemps ! J'espère que tu vas bien.}
{320}{}{Eh bien ! Toujours en vie ! Qu'est-ce qu'il te faut aujourd'hui ?}
{321}{}{Te voilà. Ca fait plus d'une semaine depuis ta dernière visite. Faut pas te volatiliser, tu sais bien que c'est pas tous les jours que j'ai des clients comme toi !}
{322}{}{Ah oui ?}
{323}{}{Quoi ?}
{324}{}{T'es ici pour acheter ou quoi ?}
{325}{}{T'es dans ma boutique, alors pas d'histoires.}
{326}{}{C'est à quel sujet ?}
{327}{}{Encore toi ?}
{328}{}{Le temps, c'est de l'argent ! C'est à quel sujet ?}
{329}{}{Tu désirais ?}
{330}{}{T'as entendu ? Il est mort ! Sensationnel ! C'est la meilleure chose qui soit jamais arrivée à cette ville.}
{331}{}{Je te l'ai déjà dit. Il est mort ! N'en parlons plus, son nom rappelle des mauvais souvenirs.}
{332}{}{Oh, ouais.}
{333}{}{Ouais, il le méritait et j'ai pas de remords.}
# Sid works for Beth. Sid is male.
{334}{}{Tu l'as fait ? C'est vrai ? Je t'adore ! [Beth jette un coup d'oeil à Sid] N'y pense  pas gros malin... Tiens, pour te montrer ma reconnaissance... [Beth te donne six Stimpaks]. C'est pas grand-chose, mais ça me fait tellement plaisir !}
{335}{}{Tu l'as fait ? C'est vrai ? Tu es magnifique ! Tu peux pas savoir ma joie quand j'ai appris qu'il était mort. Tiens, prends ça... [Beth te donne six Stimpaks]. C'est pas grand-chose, mais ça me fait tellement plaisir !}
{336}{}{Je regrette, je n'ai rien à ton goût.}
{337}{}{Tu vois rien qui te plaît ? J'essaierai d'avoir de meilleures marchandises.}
{338}{}{Je regrette que mon offre te plaise pas, mais faut aussi que je fasse un bénéfice.}
{339}{}{Finalement, tu veux plus vendre ? Pas de problème.}
{340}{}{Je regrette de pas pouvoir t'aider. Bonne journée.}
{341}{}{Peut-être la prochaine fois. Au revoir.}
{342}{}{J'espère t'être plus utile la prochaine fois.}
{343}{}{Bon, tu me fais perdre mon temps.}
{344}{}{Si tu comptes rien acheter, va-t'en, s'il te plaît.}
{345}{}{Si tu comptes rien acheter, laisse-moi tranquille.}
{346}{}{Si t'as rien à vendre, va-t'en, s'il te plaît.}
{347}{}{Viens pas me déranger si t'as rien à vendre.}
{348}{}{Va-t'en, s'il te plaît.}
{349}{}{Je savais que t'allais encore me faire perdre mon temps.}
{350}{}{Je m'en doutais que t'avais pas d'argent.}
{351}{}{Merci pour tout. Pour une fois, je pourrai peut-être rentrer tôt.}
{352}{}{Tu m'as presque dévalisée !}
{353}{}{J'espère que tu pourras tout porter !}
{354}{}{Merci, j'espère arriver à tout vendre !}
{356}{}{Ca devrait bien se vendre. Merci.}
{357}{}{Ca, ça me sera utile. Merci.}
{358}{}{J'espère réussir à ranger tout ça !}
{359}{}{Eh bien, merci beaucoup ! Je te souhaite une excellente journée !}
{360}{}{Merci, t'as fait ma journée. Repasse quand tu veux.}
{361}{}{N'hésite pas à passer... Enfin, pendant les heures d'ouverture.}
{362}{}{Merci et bonne journée.}
{363}{}{Au revoir ! Et merci !}
{364}{}{C'est tout, juste des munitions ? Je suis déçue. Bon, la prochaine fois, faudra voir à dépenser plus !}
{365}{}{Des stocks de munitions ? Bonne idée. On n'en a jamais trop.}
{366}{}{Juste l'essentiel, pas vrai ? Au revoir !}
{367}{}{Ah vrai dire, je pensais que t'allais rien acheter.}
{368}{}{Merci bien. Finalement, t'es pas si mal.}
{369}{}{Merci pour les marchandises.}
{370}{}{Bonne journée.}
{371}{}{Au revoir.}
{372}{}{Merci.}
{373}{}{Merci pour les achats, bonne journée.}
{374}{}{J'ai entendu !}
{375}{}{Sans blague !}
{376}{}{Sid ! Arrête !}
{377}{}{Tu vas m'entendre si tu te tais pas.}
{378}{}{J'ai entendu ! T'es viré !}
{379}{}{Fais pas attention à lui.}
{380}{}{Oh, t'es vraiment tordant Sid.}
{381}{}{C'est ça !}
{382}{}{La ferme !}
{383}{}{Eh. Du calme Sid.}
{384}{}{Ca m'étonnerait !}
{385}{}{Tu vas le regretter si tu laisses pas mes clients tranquilles.}
{386}{}{Excusez mon "abominable" assistant.}
{387}{}{Quel abruti !}
{388}{}{Sid !}
{389}{}{Mon coeur ? Où est-ce que tu vas pêcher tous ces vilains noms ?}
{390}{}{[Beth soupire] Je...}
{391}{}{ devrais l'enfermer. Tu penses pas ?}
{392}{}{Je crois qu'il est jaloux !}
{393}{}{Sid ! Sois pas grossier avec les clients !}
{394}{}{Tu vois personne d'autre qu'aurait des informations sur le Griffemort ?}
{395}{}{Au revoir.}
{396}{}{Merci.}
{397}{}{D'accord.}
{398}{}{Est-ce qu'il y a des endroits à éviter en ville ?}
{399}{}{Oh oui. Evite surtout le Faucon Maltais. Vaut mieux pas rencontrer Decker et son chien galeux de Kane. Ils te boufferont tout cru si tu fais pas gaffe. A ta place, je m'éloignerais aussi de Lorenzo, des Amis Prêteurs.}
