{100}{}{Voici un garde des Enfants.}
{101}{}{Phillips ! Faut qu'on vire cet énergumène !}
{102}{}{Hors de ma vue !}
{103}{}{Qu'est-ce que tu veux ?}
{104}{}{Parle-moi de ton travail.}
{105}{}{Qu'est-ce qu'on fait dans cet endroit ?}
{106}{}{Tu saurais pas où je peux trouver une puce d'eau ?}
{107}{}{Qu'est-ce que tu peux me dire sur un certain Decker ?}
{108}{}{Hum, c'est une sacrée arme que t'as là...}
{109}{}{Euh... du lait.}
{110}{}{Je suis un mercenaire. Si quelqu'un embête ces élèves astronautes, je le tue. T'y vois un problème ?}
{111}{}{Alors, t'es garde du corps...}
{112}{}{Qui t'a embauché ?}
{113}{}{Il se passe des trucs intéressants au Centre ?}
{114}{}{Qu'est-ce que tu fabriques ?}
{115}{}{Ouais. Un gros problème.}
{116}{}{Pas de problème, l'ami.}
{117}{}{Ouais, une soi-disant Flamme Sacrée. Ecoute pas ces salades, ça va te rendre malade !}
{118}{}{Quel est tno avis sur cette Flamme Sacrée ?}
{119}{}{Mec, que ces gens sont cons !}
{120}{}{Il se passe des trucs intéressants au Centre ?}
{121}{}{D'ou ils viennent, ces mecs ?}
{122}{}{Une puce d'eau ? Tu veux dire le volatile ? Au bord de la mer, peut-être.}
{123}{}{Non, je parle d'une puce d'ordinateur pour faire fonctionner un système de purification d'eau.}
{124}{}{Pas ce genre de puce, pauvre crétin !}
{125}{}{Euh, merci.}
{126}{}{T'as déjà été à la mer ?}
{127}{}{Ouais, j'ai entendu parler de lui. Une vrai crapule, mais il paie ses dettes. Phillips a bossé pour lui plusieurs fois.}
{128}{}{Alors, tu crois que c'est un sale mec ?}
{129}{}{Phillips ?}
{130}{}{T'accepterais un boulot de lui ?}
{131}{}{Merci !}
{132}{}{Ouais, c'est la seule dont j'ai besoin dans une fusillade. Qu'est-ce que je peux faire pour toi ?}
{133}{}{Où est-ce qu'on peut trouver des armes de qualité ?}
{134}{}{Ils font quoi au juste ceux de la Cathédrale ?}
{135}{}{Où est-ce qu'il y a de l'action dans le coin ?}
{136}{}{Tu saurais pas où je peux trouver une puce d'eau ?}
{137}{}{Qu'est-ce que tu peux me dire d'un certain Decker ?}
{138}{}{Mes excuses, mais je suis en service. Pas le droit de bavarder.}
{139}{}{Hors de ma vue avant que je te tue.}
{140}{}{T'y es presque, la flèche ! Qui d'autre je pourrais être, Doc Morbide ? Bon dieu !}
{141}{}{La chienne du curé. Qui d'autre tu croyais ? Bon dieu !}
{142}{}{Ca m'ennuie de te dire ça, mais ça fait des semaines que je suis plus dans la course. Vaudrait mieux qu'tu demandes à quelqu'un d'autre.}
{143}{}{Nourri logé, c'est à peu près tout. Ces curés, des vrais radins !}
{144}{}{Alors, trouvons une solution !}
{145}{}{Parfait. Parce qu'ici, personne aime les problèmes.}
{146}{}{C'est sûrement des escrocs. Faudrait être débile pour croire à toutes ces salades de dévots. Non ?}
{147}{}{Ouais. Encore heureux qu'ils me paient pas pour les approuver. Flamme Sacrée... mon cul !}
{148}{}{J'sais pas. J'vais te dire, on peut dire ce qu'on veut sur la religion, mais c'est pas des amateurs. Ils sont arrivés et ils ont réglé cet endroit comme une horloge. Faut pas les prendre pour des crétins de zombies.}
{149}{}{Bon dieu, je croyais que seuls les Abris utilisaient ce genre de conneries !}
{150}{}{Surveille tes paroles, imbécile. Si ces gens croient à la paix et à l'amour, c'est pas mon cas !}
{151}{}{Aucun problème.}
{152}{}{Hmm. Plus tu montes en hauteur, pires sont les radiations.}
{153}{}{Euh, si t'aimes bien les barjots sans foi ni loi, alors c'est ton homme.}
{154}{}{Mon collègue. Le mec qui garde Jain.}
{155}{}{Ca dépend jusqu'où t'aimes le risque. J'ai eu une vie pas mal agitée ces temps-ci, alors je suis venu me mettre au vert. Mais si t'aimes l'action, c'est bon. Simplement, pas d'entourloupe ou c'est la mort.}
{156}{}{On dit que les Marchands d'Eau transportent toujours la meilleure came. Mais on dit n'importe quoi sur eux. En tout cas, pas ici, ça non !}
{157}{}{J'ai observé ces mecs pendant des semaines. Au début, je les prenais pour des fous, mais maintenant... j'sais pas. Ils sont organisés et ils mijotent quelque chose. Je le sens !}
{158}{}{Il paraît que chez Decker, y'a de l'action, mais bon dieu, quel boulot de merde ! Tu fais une gaffe et tu vas en enfer.}
{159}{}{Une puce de purification d'eau ? Vous utilisez pas l'eau de puits ? Bon sang ! J'ai entendu parler d'un Abri, près des Sables Ombragés, où tu pourrais peut-être en trouver une, mais l'endroit est complètement bloqué. Je crois pas que je peux t'aider.}
{160}{}{Impossible de parler. Le patron aime pas ça. Mes excuses.}
{161}{}{Eh, toi !}
{162}{}{Eh ! Qu'est-ce que tu fabriques !}
{163}{}{Pourquoi cette porte est verrouillée ?}
{164}{}{Eh, d'accord, j'insiste pas !}
{165}{}{Tu peux me filer un coup de main ? La porte est coincée !}
{166}{}{T'as vu ce que je faisais ! Tant pis pour toi...}
{167}{}{C'est pas tes oignons ! Fiche le camp !}
{168}{}{Bien ! Maintenant, tire-toi !}
{169}{}{Va te faire foutre ! Si tu recommences ce genre d'idioties, je me charge de te descendre !}
{170}{}{On a pas le droit de te causer. Barre-toi.}
{171}{}{Eh ! Qu'est-ce que tu fous !}
{172}{}{Pourquoi cette porte est verrouillée ?}
{173}{}{Eh, d'accord, j'insiste pas !}
{174}{}{Tu peux me filer un coup de main ? Cette porte est coincée !}
{175}{}{T'as vu ce que je faisais ! Tant pis pour toi...}
{176}{}{C'est pas tes oignons ! Barre-toi !}
{177}{}{Bien ! Maintenant, tire-toi !}
{178}{}{Va te faire foutre ! Si tu recommences ce genre d'idioties, je me charge de te descendre !}
