# this is a door. Neutral/male. no tone of voice.

{100}{}{Il semble que cette porte possède un verrou.}
{101}{}{La porte n'est pas fermée à clé.}
{102}{}{Ce matériel ne convient pas.}
{103}{}{Tu as réussi à débloquer la fermeture électronique.}
{104}{}{Tu n'as pas réussi à débloquer la fermeture électronique.}
{105}{}{La porte est fermée à clé.}
