# Hot spots are intense concentrations of radiation. Consider Neutral or Male.
# Tone of Voice should be automated and flat.

# Lines are "You sustain [2 or more] points of radiation damage"
{100}{}{Tu subis }
{101}{}{ points de dégât par radiation.}
{102}{}{Tu subis }
{103}{}{ points de dégât par radiation.}
{104}{}{Il y a une forte concentration de radiations près d'ici.}
{105}{}{Tu subis }
{106}{}{ points de dégât par radiation.}
