{100}{}{Voici un habitant du Centre.}
{101}{}{Oh ! J'ai appris que tu as tué le Griffemort, joli travail !}
{102}{}{C'est vrai ? Le Griffemort existe... existait vraiment ?}
{103}{}{J'ai appris que tu es }
{104}{}{l'homme}
{105}{}{la femme}
{106}{}{ qui a tué le Griffemort. Joli travail !}
{107}{}{Merci d'avoir détruit ce cauchemar, maintenant on a tous un peu moins de mal à s'endormir.}
{108}{}{Y'a intérêt que ce Griffemort soit bien mort.}
{109}{}{J'espère que ces mutants qui détruisaient ces caravanes nous laisseront tranquilles.}
