{100}{}{Voici un routier.}
{101}{}{La journée sera longue !}
{102}{}{Je n'ai vraiment pas envie de travailler aujourd'hui.}
{103}{}{J'espère qu'on ne va pas être pillés... ou pire.}
{104}{}{Je regrette mais on n'a pas besoin d'autres gardes... Je pense.}
{105}{}{Impossible, on est au complet.}
{106}{}{Pour du boulot, tu devrais aller voir au Grand Marché.}
{107}{}{J'espère qu'on arrivera à tout vendre.}
{108}{}{Vivement qu'on ait terminé.}
{109}{}{Prêt pour la baston.}
{110}{}{On met les voiles !}
{111}{}{Chaude journée, non ?}
{112}{}{Bon sang que j'ai soif !}
{113}{}{On est quel jour ?}
{114}{}{Dès que j'ai terminé, je vais au Faucon !}
{115}{}{Désolé mais on revient juste d'une tournée.}
{116}{}{Pour un boulot, tu devrais aller te renseigner au Grand Marché.}
{117}{}{Aujourd'hui, c'est le jour de la paie !}
# 118 Bob's Iguana Bits
{118}{}{Je vais directement chez Bob !}
{119}{}{Il faut que je rembourse le prêt aujourd'hui !}
{120}{}{J'en peux plus.}
{121}{}{Quel long voyage !}
