{100}{}{Voici un enfant des fleurs.}
{101}{}{Bonjour ! Est-ce que... oh, pardon...}
{102}{}{Toi ! J'ai entendu parler de toi ! Tu tues les gens et après tu les manges ! Mère Jain ! Mère Jain ! A l'aide !}
{103}{}{Est-ce que tu veux une fleur, monsieur ?}
{104}{}{Est-ce que tu veux une fleur, madame ?}
{105}{}{Vide}
{106}{}{Que se passe-t-il de particulier ici ?}
{107}{}{Qu'a-t-elle de particulier cette fleur ?}
{108}{}{Combien veux-tu ?}
{109}{}{Bien sûr !}
{110}{}{Non merci.}
{111}{}{Bien sûr. Je pourrais me faire un plaisir de la réduire en bouillie !}
{112}{}{[sniff, sniff]. Ca sent bon !}
{113}{}{[sniff, sniff]. Beurk !}
{114}{}{T'es bête. Tu as déjà une fleur !}
{115}{}{Tu veux la fleur ou pas ?}
{116}{}{Je prendrai ta fleur si tu me parles un peu de cet endroit.}
{117}{}{Qu'a-t'elle de particulier cette fleur ?}
{118}{}{Bien sûr !}
{119}{}{Arrête avec tes satanées fleurs. Réponds juste à ma question !}
{120}{}{}
{121}{}{C'est une Rose de l'Unité. Elle est de la couleur de la Flamme Sacrée et elle représente la paix et l'harmonie que nous aurons quand les Enfants de la Cathédrale aideront chacun dans le monde à se montrer amical et courageux ! Euh, t'en veux une ?}
{122}{}{Vide}
{123}{}{Et comment une rose pourrait-elle avoir tout ce pouvoir ?}
{124}{}{Parle-moi de la Flamme Sacrée...}
{125}{}{Combien ça fait ?}
{126}{}{Bien sûr !}
{127}{}{}
{128}{}{Ecoute. Je veux pas de ta putain de fleur.}
{129}{}{C'est gratuit. L'argent ne signifie rien pour nous. La Flamme Sacrée répond à tous nos besoins. C'est si merveilleux ! Tu devrais te joindre à nous, au sein de notre Cathédrale du Bonheur ! Euh, t'en veux une ?}
{130}{}{Parle-moi de la Cathédrale...}
{131}{}{Parle-moi de la Flamme Sacrée...}
{132}{}{Bien sûr gamin !}
{133}{}{}
{134}{}{}
{135}{}{Merci, merci beaucoup ! J'ai fait cadeau d'une fleur ! N'est-ce pas magnifique...}
{136}{}{C'est méchant ! Je te déteste ! J'espère que la Flamme Sacrée t'engloutira !}
{137}{}{Bien sûr ! Prends-en une ! J'ai fait cadeau d'une fleur ! N'est-ce pas magnifique...}
{138}{}{Tu es stupide ! J'espère que la Flamme Sacrée te tuera avant que tu puisses encore dire des choses aussi stupides. Mère Jain, protège nous cette personne stupide !}
{139}{}{Nous sommes les Enfants de la Cathédrale. C'est la Flamme Sacrée elle-même qui nous exhorte à nourrir ceux qui ont faim et soigner ceux qui souffrent. Nous allons répandre la paix et l'unité... et tout sera siiiiiii beau ! Cette fleur est pour toi. Prend-la !}
{140}{}{J'ai l'impression que tu veux pas de fleur. Méchant !}
{141}{}{Mais non idiot ! Seuls les hommes peuvent changer le monde. Et avec la Flamme Sacrée pour maître, nous pouvons être sûrs que tout deviendra beau et spécial ! Alors, est-ce que tu veux une fleur ?}
{142}{}{Parle-moi de la Cathédrale...}
{143}{}{Parle-moi de la Flamme Sacrée...}
{144}{}{D'accord !}
{145}{}{Non merci.}
{146}{}{Idiot ? Viens par ici espèce de petit...}
{147}{}{C'est le feu qui a purifié le monde et si nous lui obéissons, il n'aura plus à le faire ! Elle veut que nous soyons intelligents, paisibles, unis et tout ça ! Alors, tu veux pas une fleur ?}
{148}{}{Parle-moi de cette unité...}
{149}{}{Bien sûr gamin !}
{150}{}{Non merci.}
{151}{}{Arrête avec cette satanée fleur !}
{152}{}{C'est un monde merveilleux, tout près de l'océan, là où les gens passent leur temps à louer la Flamme Sacrée et s'attachent à être bons. Et tout le monde est gentil là bas, à part le Père Lasher peut-être. Euh... est-ce que tu veux une fleur ?}
{153}{}{Parle-moi de Père Lasher...}
{154}{}{Bien sûr !}
{155}{}{Non merci.}
{156}{}{Arrête avec cette satanée fleur !}
