{100}{}{Voici un garde du Centre.}
{101}{}{Est-ce que je peux t'aider ?}
{102}{}{Oui. Pourrais-tu me dire où je suis ?}
{103}{}{Au revoir.}
{104}{}{Euhhhhhhh. Euh euh. Euhhhhh. Euh.}
{105}{}{Mince, il te manque une case ou quoi ?! Débarrasse le plancher !}
{106}{}{Tu te trouves à l'extrémité Sud du Centre. Si tu regardes autour de toi, tu verras les Marchands d'Eau et un petit hôpital.}
{107}{}{Qui sont les Marchands d'Eau ?}
{108}{}{Un hôpital ?}
{109}{}{Merci. Salut.}
{110}{}{Les salauds ! Ils pensent que le Centre leur appartient juste parce qu'ils contrôlent le château d'eau.}
{111}{}{Un hôpital ?}
{112}{}{Merci. Salut.}
{113}{}{Les Enfants de la Cathédrale dirigent un petit hôpital ici dans le Centre. Ils semblent former une bonne équipe.}
{114}{}{Qui sont les Marchands d'Eau ?}
{115}{}{Merci. Salut.}
