{101}{}{Les marchands de caravanes n'ont pas eu la moindre chance. Ils sont tous morts.}
{102}{}{Les mutants étaient vraisemblablement lourdement armés. Les marchands de caravanes n'avaient pas la moindre chance de s'en sortir sous ce déluge de feu.}
{103}{}{Ils sont morts.}
{104}{}{Pour toi, il n'y a aucun doute. Cette personne est morte.}
{105}{}{Derrière cet amas de chair et de muscles transgéniques, l'un d'eux te paraît familier. C'est l'un des éclaireurs que l'Abri a envoyés à l'extérieur et qui n'est jamais revenu...}
{106}{}{Derrière cet amas de chair et de muscles transgéniques, tu reconnais l'un des mutants. Il s'agit de Sean, l'un des éclaireurs que ton Abri a envoyés à l'extérieur quelques mois avant que tu ne partes.}
{107}{}{Tous ces mutants sont morts. Pourtant, l'un d'eux te fait penser à quelqu'un mais tu ne vois pas qui exactement.}
{108}{}{Des mutants morts.}
