{100}{}{Voici Jennifer.}
{101}{}{Voici un Paladin.}
{102}{}{Excuse-moi, Frère. Tu dois ranger tes armes quand tu es à l'intérieur de la Confrérie. Nous sommes un ordre amical, mais comme tu le sais, les temps sont difficiles.}
{103}{}{Certains membres de la Confrérie se sentiraient offensés si un étranger... je veux dire, un nouvel initié... s'approchait d'eux avec une arme.}
{104}{}{Bonjour, initié. Puis-je t'être utile ?}
{105}{}{Bonjour, Soeur. C'est bon de voir que cette organisation compte des femmes dans ses rangs. Je ne savais pas à quoi m'attendre avec un nom tel que la Confrérie.}
{106}{}{Ouah, ces jambes ! A quelle heure je passe te prendre ?}
{107}{}{Oooooga !}
{108}{}{Peux-tu me dire où trouver notre Ainé ?}
{109}{}{Qui est le responsable de ce trou ?}
{110}{}{Où il est cet Ainé ?}
{111}{}{Gr !}
{112}{}{Maxson, l'Ainé, est visible au Quatrième Etage. Si tu prends l'ascenseur, tu pourras le trouver soit dans la Salle du Conseil soit dans les Chambres des Ainés.}
{113}{}{Demande à l'un des gardes ; ils devraient savoir où il se trouve en ce moment.}
{114}{}{Merci.}
{115}{}{Où pourrais-je trouver de meilleures armes ?}
{116}{}{Tu devrais voir Talus. Je pense qu'il pourra t'aider ou au moins te dire à qui t'adresser.}
{117}{}{Pendant la journée, Talus surveille d'ordinaire la salle d'entraînement. Est-ce que tu sais où ça se trouve ?}
{118}{}{Oui. Merci.}
{119}{}{Non.}
{120}{}{Bien sûr que oui !}
{121}{}{La salle d'entraînement se trouve juste à l'angle. Longe ce couloir, tourne à gauche et passe la porte qui se trouve au bout sur ta droite.}
{122}{}{Ton aide m'a été infiniment précieuse. Merci beaucoup. J'espère te revoir bientôt. Bonne journée.}
{123}{}{La salle d'entraînement ? Est-ce que tu crois que je pourrais m'y entraîner moi-même ? Je suis membre de la Confrérie désormais, n'est-ce pas ?}
{124}{}{Merci de ton aide, Soeur. C'est bon de voir que cette organisation compte des femmes dans ses rangs. Je ne savais pas à quoi m'attendre avec un nom tel que la Confrérie.}
{125}{}{Merci, mon sucre. Tu es splendide. Qu'est-ce que tu dirais d'une petite 'inspection' mutuelle plus tard. A quelle heure tu termines ?}
{126}{}{Ah, là-bas. D'accord, merci.}
{127}{}{Excuse-moi ? Il y a quelque chose qui ne va pas ?}
{128}{}{Euh...}
{129}{}{Excuse-moi. Je ne pense pas pouvoir t'aider. Tu devrais voir le docteur. Elle est au second.}
{130}{}{Evidemment qu'il y a des femmes. Deux des Aînés sont des femmes, notre grand scribe est une femme et il y a des femmes qui occupent diverses fonctions.}
{131}{}{Les femmes de la Confrérie sont également appelées 'Frères'. On ne les appelle pas Soeurs. Après tout, c'est la Confrérie de l'Acier et pas la Con-frère&soeur-ie de l'Acier.}
{132}{}{Tu ne trouves pas ça bizarre que ça s'appelle la Confrérie, sous entendant qu'il n'y a que des hommes ?}
{133}{}{Mais pourquoi ça s'appelle la Confrérie, alors ?}
{134}{}{Eh ben, ça paraissait étrange. Voilà tout.}
{135}{}{Je ne sais pas. Ca s'est toujours appelé comme ça. Il doit bien y avoir une raison.}
{136}{}{Tu as sans doute raison.}
{137}{}{Eh bien, moi je trouve ça étrange.}
{138}{}{C'est étrange. Je n'y avais jamais réfléchi. Toute ma vie, on a appelé ça la Confrérie. Nos ancêtres devaient certainement avoir une raison pour l'appeler ainsi.}
{139}{}{Mais rien ne dit que les choses ne changeront jamais.}
{140}{}{Ouais, t'as sans doute raison.}
{141}{}{Alors, est-ce que tu as encore besoin de moi ?}
{142}{}{Oui. Où puis-je trouver l'Aîné ?}
{143}{}{Où puis-je trouver de meilleures armes ?}
{144}{}{Non, c'est tout. Salut.}
{145}{}{Non. Nous sommes très stricts en matière de traditions. Je ne pense pas que ça puisse changer un jour. Moi, ça ne m'embête pas du tout qu'on m'appelle Frère. Même si ça sonne bizarre.}
{146}{}{Je pense qu'il faut que j'en touche deux mots à Vree. Peut-être qu'elle pourra me dire pourquoi nos ancêtres ont décidé de s'appeler ainsi.}
{147}{}{Qui c'est Vree ? L'un des Aînés ?}
{148}{}{Vree est le Grand Scribe. C'est à elle que tu devrais t'adresser si tu as des questions d'ordre technique mais ne la dérange pas au cours de ses méditations nocturnes.}
{149}{}{Elle passe le plus clair de son temps dans sa chambre, là où se trouve également l'ordinateur central, au troisième.}
{150}{}{Ce trou ? Comment oses-tu parler ainsi de la Confrérie ! Tu es désormais membre de notre ordre et c'est un immense honneur que d'appartenir à la Confrérie de l'Acier.}
{151}{}{Un honneur ? N'importe quoi ! Vous n'êtes qu'une bande de robots débiles qui se cachent du monde réel. Je ne comprends pas ta fierté.}
{152}{}{Excuse. Je me laisse emporter parfois.}
{153}{}{Ouais, c'est vrai.}
{154}{}{Ca arrive à tout le monde.}
{155}{}{Alors, qui est le responsable ici ?}
{156}{}{Ouais. Bon, il y faut que j'y aille.}
{157}{}{Maxson, l'Aîné. Il est au quatrième.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{T'es mignon... Mais je ne pense pas que ça soit une bonne idée de fréquenter un étranger. Dommage, tu me plaisais vraiment...}
{164}{}{Je ne sais pas si c'est parce que tu es pas d'ici ou si c'est à cause de ton manque total de tact. Alors, 'poussin', tu désires autre chose ?}
{165}{}{Ouais, euh, j'imagine. Euh, qui est le responsable ici ?}
{166}{}{Euh, oui... hum. Qu'en est-il des armes sinon ? comment pourrais-je mettre la main sur certaines d'entre elles ?}
{167}{}{Hmmff !}
{168}{}{Non.}
{169}{}{C'est... très drôle. Tu plaisantes, j'espère ! En fait... Ne réponds pas. Je n'ai pas envie de savoir.}
{170}{}{Ouais. TRES drôle. Presque aussi drôle que ta tête !}
{171}{}{Merci beaucoup. C'est exactement ce que j'avais envie d'entendre.}
{172}{}{Je m'en vais.}
{173}{}{Excuse. Mais vous autres, les étrangers, vous avez une telle façon de parler aux gens. Est-ce que je peux t'aider ?}
{174}{}{Eh bien, je crois que je devrais parler à cette personne qu'on appelle l'Aîné. Où est-elle ?}
{175}{}{J'aimerais trouver de meilleures armes. Qui faut-il que je vois pour ça ?}
{176}{}{Non.}
{177}{}{Tu plaisantes ? Je n'ai jamais entendu une telle bêtise de ma vie !}
{178}{}{Ouais ? Je ne sors pas souvent. T'as compris ?}
{179}{}{Hors de ma vue, espèce de poubelle ambulante !}
{180}{}{Pfft !}
{181}{}{Eh bien, oui, tu es membre de la Confrérie mais les Aînés ont suspendu l'entraînement des nouveaux Initiés.}
{182}{}{Pourquoi ?}
{183}{}{Oh, c'est GENIAL ! Qu'est-ce qui m'a pris de rejoindre ce groupe stupide ? Où est la porte ?!}
{184}{}{Il y a des rumeurs qui circulent sur une certaine armée. Je pense que les Anciens veulent concentrer leur moyens sur ceux qui sont suffisamment entraînés pour faire la différence en cas d'une grande bataille.}
{185}{}{Nous pensons fermement qu'il est préférable d'entraîner un groupe restreint au plus haut niveau plutôt que de dispenser un entraînement médiocre à toute une série de combattants. Ce que nous cherchons avant tout, c'est de sauver le maximum de vies.}
{186}{}{Tu pourrais certainement en apprendre pas mal rien qu'en regardant. Frère Thomas est le meilleur entraîneur que l'on n'ait jamais eu à la Confrérie.}
{187}{}{Alors, on me demande de travailler à l'extérieur de la Confrérie, c'est ça ? C'est un monde hostile où je risque ma vie à chaque instant. Ne penses-tu pas que je mérite d'avoir l'entraînement nécessaire ou bien est-ce que ce n'est qu'une façon de parler pour toi quand tu dis 'sauver le maximum de vies' ?}
{188}{}{Merci du conseil. Je le ferai.}
{189}{}{Vous n'êtes qu'une bande de fous.}
{190}{}{Peux-tu me dire où se trouve Maxson ?}
{191}{}{Je ne fais que répéter ce qu'on m'a dit. Si tu parles à Thomas ou à Talus, ils pourront peut-être faire une exception.}
{192}{}{D'accord, merci.}
{193}{}{Ils feraient mieux. Vous m'avez suffisamment mis sur la sellette.}
{194}{}{Alors, peux-tu me dire où trouver Maxson ?}
{195}{}{Oh, mon amour. Quand est-ce qu'on se marie ?}
{196}{}{Tu es magnifique, comme toujours.}
{197}{}{Embrasse-moi.}
{198}{}{Tu m'as tellement manqué.}
{199}{}{C'est quand tu veux.}
{200}{}{Je n'ai pas arrêté de penser à toi aujourd'hui.}
{201}{}{J'aime tellement la manière que tu as de me regarder.}
{202}{}{Ne me fais pas peur comme ça, j'ai cru que je ne te reverrai jamais !}
{203}{}{Même pas une petite visite la nuit dernière !}
{204}{}{Ca m'a paru une éternité depuis la dernière fois.}
{205}{}{Tu m'as tellement manqué.}
{206}{}{Viens te coucher, trésor.}
{207}{}{On peut se marier dans la matinée.}
{208}{}{Que dirais-tu d'avoir cinq marmots ensemble ?}
{209}{}{Où aimerais-tu aller pour notre lune de miel ? On m'a dit beaucoup de bien des Enfants de la Cathédrale.}
{210}{}{Mes parents aimeraient tellement te rencontrer.}
{211}{}{Te revoilà ! J'espère que tout va bien pour toi. J'espère que tu as parlé à Vree.}
{212}{}{Bonjour, Frère }
{213}{}{.}
{214}{}{Fais attention si tu vas dans le Nord. Nos éclaireurs n'en sont jamais revenus.}
{215}{}{Frère }
{216}{}{, c'est bon de te revoir.}
{217}{}{As-tu parlé à Rhombus ? C'est le Grand Chevalier. Il est dans la pièce en face.}
{218}{}{Je n'ai pas le temps de discuter. J'ai à faire.}
{219}{}{Excuse, mais je ne suis pas d'humeur à parler aux malotrus.}
{220}{}{Laisse-moi tranquille.}
{221}{}{Quoi ? Tu veux pas aller voir ailleurs si j'y suis ?}
{222}{}{Va-t-en.}
{223}{}{Je n'ai pas envie de te parler.}
{224}{}{Initié, va faire tes devoirs.}
{225}{}{Pas le temps de discuter, Initié.}
{226}{}{Viens par là, bel étalon !}
{227}{}{Chéri, par ici !}
{228}{}{Tu m'as manqué.}
{229}{}{J'ai préparé la chambre des enfants, trésor.}
{230}{}{Salut, beauté.}
{231}{}{Je te vois.}
{232}{}{Il faut que je te présente à mes parents.}
{233}{}{Hou hou !}
{234}{}{Viens ici, mon loukhoum.}
{235}{}{Tu me taquines ?}
{236}{}{Tu te fais désirer, ou quoi ?}
{237}{}{Par ici, mon sucre d'orge !}
{238}{}{Bonjour mon trésor !}
{239}{}{Ah, te voilà. Je commençais à m'inquiéter.}
{240}{}{Viens m'embrasser, mon poussin.}
{241}{}{Entre donc, mon chou.}
