{100}{}{Voici Jérémie, un messager pour les Enfants.}
{101}{}{Voici un Enfant. Il a l'air pensif.}
{102}{}{Excuse-moi, frère. Je n'avais pas vu qu'il y avait quelqu'un. Comment puis-je servir le Maître ?}
{103}{}{Quel sarcasme !}
{104}{}{Qu'est-ce que tu fais ?}
{105}{}{Ah, oui, un super mutant en rodage. Je vais retourner à ma tâche.}
{106}{}{Si tu ne le sais pas, c'est que tu n'as pas à le savoir. Si tu cherches à savoir quelque chose que tu ne dois pas savoir, il faudra que je le rapporte à nos surveillants.}
{107}{}{Je suis une personne très importante.}
{108}{}{Je ne voulais pas te déranger.}
{109}{}{Je viens d'arriver.}
{110}{}{Tu te prends pour qui pour me questionner ainsi ?! Tu as de la chance que je ne fasse pas un rapport sur toi à la flamme sacrée !!}
{111}{}{Chargé des transmissions de rapports, bien sûr.}
{112}{}{Les rapports sur quoi ? Si je me permets.}
{113}{}{Tu dois avoir de lourdes responsabilités.}
{114}{}{C'est tout. Merci.}
{115}{}{Très bien. Que la Paix soit avec toi.}
{116}{}{Toutes mes excuses. A quoi puis-je être utile ?}
{117}{}{Que fais-tu au juste ?}
{118}{}{Commence par répondre à ma question.}
{119}{}{Tu peux toujours crever !}
{120}{}{Gardes !!}
{121}{}{Il est évident que tu n'es pas d'ici. Qui es-tu ?}
{122}{}{Je suis un Habitant de l'Abri et je voudrais parler au Maître.}
{123}{}{Emm... Dorpheus... hmm... je viens de la part de Morpheus.}
{124}{}{Je suis Loki. Un initié du Sud.}
{125}{}{Non, je ne suis pas d'ici. Mais je sais où cette balle va aller... dans ta tête.}
{126}{}{Je transmets des rapports sur la pureté des humains pour les zones aux alentours. Mais tu devrais être au courant de ça. [il te jette un regard soupçonneux] Qui es-tu ?}
{127}{}{J'ai un message de Morpheus pour le Maître.}
{128}{}{Tu n'as pas à savoir qui je suis... Réponds juste à mes questions !}
{129}{}{Tu ne dois pas savoir qui je suis, c'est la volonté du Maître.}
{130}{}{Tu oses me demander qui je suis ? Imbécile, je devrais t'abattre sur place.}
{131}{}{C'est surprenant... Je n'ai jamais entendu parler de toi.}
{132}{}{J'ai un message de la part de Morpheus pour le Maître.}
{133}{}{J'appartiens au Grand Ordre. Pour garantir ma sécurité à l'extérieur, le Maître et Morpheus sont les seuls à savoir qui je suis. Mais je suis de retour sur ordre du Maître.}
{134}{}{S'il te plaît, excuse-moi. Pardonne mes questions. Je ne veux pas te déranger plus longtemps. Si je peux t'être utile à quelque chose, n'hésite pas.}
{135}{}{Je ne sais pas qui tu es et tu n'es pas d'ici. Gardes !!}
{136}{}{Qui es-tu et que fais-tu ici ?}
{137}{}{Je suis un fidèle et j'ai perdu mon chemin.}
{138}{}{J'ai un message de Morpheus pour le Maître.}
{139}{}{Je cherche une âme en peine à envoyer au ciel.}
{140}{}{Erk !}
{141}{}{Tu n'as pas le droit de te trouver dans cette zone. Seuls les serviteurs et les gradés ont le droit d'être ici. Retourne à la Cathédrale immédiatement.}
{142}{}{Excuse-moi pour les problèmes causés.}
{143}{}{Est-ce que je peux te poser quelques questions avant de partir ?}
{144}{}{Ok, mais pas avant que je n'aie pu de te fracasser la figure.}
{145}{}{Morpheus n'enverrait jamais en mission une crapule de ton espèce. Gardes !!}
{146}{}{Imbécile ! Tu n'as pas le droit de te trouver dans cette zone. Retourne à la Cathédrale immédiatement !}
{147}{}{Oké.}
{148}{}{Rrr.}
{149}{}{Nan.}
{150}{}{Je transmets des rapports pour le Maître. C'est tout ce que tu as à savoir, mon enfant. Maintenant, file.}
{151}{}{Je m'en vais tout de suite.}
{152}{}{J'aimerais juste te poser encore quelques questions.}
{153}{}{J'y vais, j'y vais. Mais pas avant de t'avoir fait sauter la cervelle.}
{154}{}{Comment as-tu fait pour entrer ici ?! Qu'est-ce qui te prends à fouiner partout ?}
{155}{}{J'aimerais juste te poser quelques questions.}
{156}{}{Non. Tu n'as pas à me questionner. Va-t-en immédiatement.}
{157}{}{Halte ! Tu n'as rien à faire ici !}
{158}{}{Bah ?}
{159}{}{Pardon. J'ai perdu mon chemin. Je m'en vais tout de suite.}
{160}{}{Bien sûr que si. Je suis ici sur ordre de Morpheus pour voir le Maître.}
{161}{}{J'étais à la poursuite d'un personnage louche. Tu ne l'aurais pas vu ?}
{162}{}{Non. Mais tuer, c'est mon truc.}
{163}{}{Non, je n'ai vu personne. A quoi ressemblait-il ?}
{164}{}{Tant pis. Je pense qu'il est déjà loin.}
{165}{}{C'était un petit homme vert.}
{166}{}{De ta taille mais il portait une veste en cuir... Qu'est-ce que tu as sous ces habits ?}
{167}{}{Il te ressemblait, tête de noeud !}
{168}{}{Um... Je... Je... Tu ne penses quand même pas que c'était m... moi ? C'est ridicule !}
{169}{}{C'est bon. Je m'en vais mais si tu vois quelque chose, préviens-moi...}
{170}{}{Oui ! Je pense que c'était toi ! A terre et écarte-les !}
{171}{}{Non, je ne pense pas que c'était toi mais est-ce que je peux te poser quelques questions ?}
{172}{}{Oui, mon frère. A quoi puis-je t'être utile ?}
{173}{}{Oui, ma soeur. A quoi puis-je t'être utile ?}
{174}{}{Qu'est-ce que tu fais ici, frère ?}
{175}{}{Je ne fais que servir le Maître. Je ne demande que ça, frère.}
{176}{}{Non, je fais erreur. Tout le monde se ressemble sous ces habits.}
{177}{}{C'est en crevant que tu pourrais me servir, espèce d'ordure !}
{178}{}{Je transmets des rapports sur la pureté des humains pour les zones aux alentours.}
{179}{}{C'est tout. Merci.}
{180}{}{J'aimerais te poser d'autres questions, frère.}
{181}{}{Oui, et c'est un travail très important. Comprends-tu l'importance des devoirs que tu as à l'égard du Maître et de chacun de nous ?}
{182}{}{Evidemment. Je suis celui qui informe le Maître de la présence de nouveaux humains purs et non atteints par les radiations. C'est moi qui ai informé le Maître de l'existence d'un possible Abri Oublié. Il se peut que des humains de race pure y habitent encore.}
{183}{}{Oui, mon frère. Tu as compris. Merci. C'est tout.}
{184}{}{J'aimerais de poser d'autres questions.}
{185}{}{Tu ne reconnaîtrais même pas un homme de race pure si tu l'avais en face de toi. Imbécile.}
{186}{}{Tu ne reconnaîtrais même pas une femme de race pure si tu l'avais en face de toi. Imbécile.}
{187}{}{Tu te comportes de manière suspecte. Je ne crois pas que tu sois ce que tu prétends être. Gardes !}
{188}{}{Tu poses beaucoup trop de questions. Je ne crois pas que tu sois ce que tu prétends être. Gardes !}
{189}{}{Hé ! Je t'ai dit que tu n'avais pas le droit d'être ici ! Gardes !}
{190}{}{Tu poses beaucoup trop de questions. Qui es-tu ?}
{192}{}{Excuse-moi, soeur. Je n'avais pas vu qu'il y avait quelqu'un. Comment puis-je servir le Maître ?}
