#
# THIS FILE IS NOT USED !! No need to translate.
#
# Use "BULLBORD.MSG" instead.
#
#
{100}{}{Voici l'Agence pour l'Emploi}
{101}{}{POSTES A POURVOIR ! Besoin de travailler ? Besoin d'argent ? NOUS AVONS CE QU'IL VOUS FAUT !}
{102}{}{Prière de ne déposer aucun message en double exemplaire. - Le Shérif Greene.}
{103}{}{1- Caravane Disparue ! Récompense !}
{104}{}{2- Besoin de Gardes de Caravane.}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Sortie}
{110}{}{RECOMPENSE : CARAVANE DISPARUE. Une récompense de 500 scripts du Centre sera offerte à toute personne capable d'attraper ces fumiers qui ont mis à sac nos caravanes. Pour plus d'informations, s'adresser à Butch Harris, Marchand du Lointain, Nord-Est du Grand Marché.}
