{100}{}{Qu'est-ce que tu veux ?}
{101}{}{Tes gardes m'ont dit que tu avais du boulot pour moi.}
{102}{}{Mon vieux, je n'aime pas ton attitude.}
{103}{}{Rien.}
{104}{}{Euh...}
{105}{}{Ca se pourrait... As-tu jamais eu affaire à une bande de sales voleurs et assassins vicieux ?}
{106}{}{Ne m'en parle pas. T'as un problème avec un gang.}
{107}{}{Qu'est-ce qui se passe ici ? Existe-t-il un seul endroit dans ce désert où il n'y a pas un problème de gangs ?}
{108}{}{Ouais, ça m'est arrivé.}
{109}{}{Euh... Tu as déjà eu affaire aux gangs ?}
{110}{}{Tu peux dire ça comme ça.}
{111}{}{C'est quoi ton problème, vieux ? Je t'ai déjà dit que oui, non ?}
{112}{}{Non, jamais et j'entends bien que ça dure. Bonne journée, monsieur.}
{113}{}{Bien, alors tu sais combien ils peuvent être cruels et sanguinaires. Les Ecorcheurs sont les pires de tous, j'en ai peur. Nous, on ne demande rien à personne. On essaie tout simplement de survivre et ces... ces... monstres... ils nous martyrisent. [Il soupire] Et nos enfants...}
{114}{}{Ouais, ouais, c'est super. C'est quoi ce boulot et c'est quoi ton intérêt ?}
{115}{}{Qu'est-ce que tu veux dire par 'ils nous martyrisent' ?}
{116}{}{Pourquoi ne demandes-tu pas à tes gardes d'intervenir ?}
{117}{}{Bon, les Régulateurs font ce qu'ils peuvent pour limiter les dégâts mais c'est tout ce qu'ils peuvent faire pour que notre petite communauté puisse vivre en paix. Ils tentent de s'introduire la nuit pour assassiner nos concitoyens... ou enlever nos enfants... et... [Il se reprend un instant avant de poursuivre] Pas plus tard que la semaine dernière, l'un d'eux a forcé le portail Nord au milieu de la nuit. Il portait sur lui de la dynamite pour faire exploser les baraques des Régulateurs... Sans aucun doute pour nous affaiblir et lancer une attaque d'envergure.}
{118}{}{Que lui est-il arrivé ?}
{119}{}{Ca semble un peu exagéré, non ?}
{120}{}{Par bonheur, les Régulateurs ont pu l'arrêter avant qu'il ne mette son plan à exécution. J'ai vu son cadavre de mes propres yeux.}
{121}{}{Je vois. Qu'attends-tu de moi ?}
{122}{}{Alors tu n'as pas réellement vu ce type bourré d'explosifs pénétrer dans votre ville ?}
{123}{}{Je t'offrirai 2000 caps si tu tues leur chef. Je veux la tête de cette chienne !}
{124}{}{On dirait que tu lui en veux personnellement.}
{125}{}{Pourquoi leur chef uniquement ?}
{126}{}{Ca me va.}
{127}{}{Sans elle, ils ne sont rien... sans l'influence qu'elle a sur eux.}
{128}{}{Ca doit être une drôle de nana.}
{129}{}{J'en ai suffisamment entendu. Je vais le faire.}
{130}{}{Euh, c'est bon. Je ne veux pas m'en mêler.}
{131}{}{Elle a fait enlever mon fils. Elle l'a torturé puis tué. Ils l'ont empalé. Là, juste en face des grilles.}
{132}{}{Ah, les ordures ! Je m'en charge.}
{133}{}{Je crois que ça ne me regarde pas, après tout.}
{134}{}{Le ciel soit loué. Mon fils sera enfin vengé. Les Ecorcheurs ont établi leur campement au Nord d'ici. Reviens lorsque tu auras accompli le boulot.}
{135}{}{C'était au milieu de la nuit, je t'ai dit. Je dormais. Heureusement, les Régulateurs parviennent en général à attraper ces barbares avant même qu'ils ne puissent entrer dans notre ville.}
{136}{}{Ouais, c'est une chance. Et c'est bien commode aussi.}
{137}{}{Tout ça ne me dit rien qui vaille. Ne compte pas sur moi.}
{138}{}{Alors, tire-toi d'ici ! Si tu ne veux pas aider le Sanctuaire, le Sanctuaire saura bien se passer de toi !}
{139}{}{Je n'ai pas de temps à perdre avec des idiots. Sors d'ici.}
{140}{}{Je pourrais ignorer cette remarque si tu veux bien résoudre mes problèmes.}
{141}{}{C'est quoi le problème ?}
{142}{}{Que tu es vieux et stupide ?}
{143}{}{As-tu jamais eu affaire à une bande de sales voleurs et assassins vicieux ?}
{144}{}{Laisse-moi deviner : tu as un problème avec des gangs.}
{145}{}{Que se passe-t-il ici ? N'y a-t-il donc pas un seul endroit dans le désert sans un problème de gangs ?}
{146}{}{J'ai réglé leur compte à certains.}
{147}{}{Encore un trou perdu avec des problèmes de gangs ! C'est ridicule !}
{148}{}{Ce qui serait commode, c'est de mettre un terme à leur folie une bonne fois pour toutes !}
{149}{}{Laisse-moi deviner - tu veux les voir crever.}
{150}{}{Que puis-je pour toi ?}
{151}{}{C'est plus que je ne voulais en savoir. J'y vais maintenant.}
{152}{}{Quoi ?! Encore toi ? Qu'est-ce que tu veux encore ?}
{153}{}{J'ai changé d'avis. J'accepte le boulot.}
{154}{}{Mon vieux, je n'aime pas ton attitude.}
{155}{}{Rien.}
{156}{}{[Il te regarde avec circonspection.] Les Ecorcheurs ont établi leur campement au Nord d'ici. Reviens lorsque tu auras accompli le boulot et je t'offrirai 2000 caps.}
{157}{}{Pourquoi n'as-tu pas encore réglé le problème ?}
{158}{}{J'ai changé d'avis.}
{159}{}{Je m'en occupe.}
{160}{}{Hé, n'insiste pas, vieux !}
{161}{}{Bon, agis plus vite ! Ne viens plus me déranger avant que tu aies mis fin à sa misérable vie !}
{162}{}{Ca y est ?!? Elle est morte ? Elle est morte ?}
{163}{}{Tu as besoin d'aide, mon vieux. Ouais, elle est morte.}
{164}{}{Bien sûr. Tu peux me croire : je lui en ai fait baver.}
{165}{}{Oui.}
{166}{}{Le ciel soit loué !! Voici ton argent. Le Sanctuaire te sera toujours ouvert, mon fils.}
{167}{}{Maintenant, elle a eu son compte ! Sois béni, mon fils. [Il essuie une larme]. Voici 500 caps de plus pour tes efforts. Notre maison te sera toujours ouverte.}
{168}{}{Ca y est ?!? Elle est morte ? Elle est morte ?}
{169}{}{Essuie-moi cette bave que tu as sur la bouche et assieds-toi. Il y a quelque chose dont il faut que nous parlions.}
{170}{}{J'ai quelque chose à te faire écouter.}
{171}{}{J'en ai marre de ton impudence ! Elle est morte, oui ou non ?!}
{172}{}{Hé, écoute ça.}
{173}{}{[En écoutant le holodisque, il se met à trembler et à bouillir de rage. Tu penses que la haine va le foudroyer sur place.] Je vais tous les tuer, ces connards !}
{174}{}{Ordure ! C'est le diable qui est en toi !}
{175}{}{Voici un homme de la quarantaine en tenue civile.}
{176}{}{Voici Jon Zimmerman, le maire du Sanctuaire.}
{177}{}{Ouais, qu'est-ce que tu veux ?}
{178}{}{J'ai quelque chose pour toi au sujet de ton fils.}
{179}{}{Laisse tomber.}
{180}{}{Bah.}
{181}{}{Qui es-tu ?}
{182}{}{Je suis Jon Zimmerman, maire du Sanctuaire. Que veux-tu ?}
{183}{}{Salut.}
{184}{}{C'est bon de te revoir.}
{185}{}{Merci de ton aide.}
{186}{}{Mon fils peut enfin reposer en paix.}
{187}{}{Mon fils est vengé.}
