{100}{}{Voici Kane.}
{101}{}{En quoi consiste le travail et quel est le salaire ?}
{102}{}{Travailler pour cette crapule ? C'est une blague.}
{103}{}{Bon sang, mais j'ai bien l'impression que je vais devoir te botter le cul.}
{104}{}{Je regrette, mais peut-être plus tard.}
{105}{}{Non merci.}
{106}{}{Heiin ?}
{107}{}{Je crois qu'une erreur s'est glissée dans les rapports. Fiche le camp. On n'engage pas les pauvres types.}
{108}{}{C'est pas un travail d'amateur. Tu devras le fair' vite et proprement. Le chef va te donner les détails, mais si t'es bon, tu gagneras beaucoup plus d'argent qu'en un mois dans les caravanes. On ne tolère pas l'échec, si tu vois ce que je veux dire.}
{109}{}{Ca semble correct.}
{110}{}{Je peux pas tout de suite. Je te recontacterai.}
{111}{}{Qui dois-je tuer ?}
{112}{}{Non merci. Je n'ai pas besoin d'argent.}
{113}{}{Je suis sûr que tu connais ce genre de travail, alors laisse-moi te dire qu'il est dans ton intérêt de n'en parler à personne. D'accord ?}
{114}{}{J'espère pour toi que c'était de l'humour. Evite de te trouver de nouveau sur notre chemin, tu le regretterais.}
{115}{}{D'accord. Bon, mais qu'est-ce que ce 'travail' implique ?}
{116}{}{Ouais, laisse tomber, dur à cuire.}
{117}{}{Je crois pas que tu m'aies bien compris. Laisse moi clarifier les choses; si tu surveilles pas tes manières, tu vas mourir, imbécile.}
{118}{}{Je crois pas que tu m'aies bien compris. Laisse moi clarifier les choses; si tu surveilles pas tes manières, tu vas mourir, imbécile.}
{119}{}{Non, laisse-moi clarifier les choses. Si tu fais pas attention, je vais me faire des bottes avec la peau de tes fesses..}
{120}{}{Ok. J'ai compris. Bon alors, que veux-tu que je fasse ?}
{121}{}{Je te parlerai plus tard. Il faut que j'y aille.}
{123}{}{Alors, vas-y. Ne nous fais pas mariner.}
{124}{}{Bien sûr, bonne journée.}
{125}{}{Tu as pas besoin d'argent ? Tu dois plaisanter, mais d'après ce que j'ai entendu sur toi, tu devrais adorer le boulot que j'ai à te proposer.}
{126}{}{Vraiment ? Ca peut m'intéresser, continue.}
{127}{}{Non merci.}
{128}{}{Je te recontacterai.}
{129}{}{Voilà... Veux-tu m'accompagner en bas ? Il y a trop d'oreilles indiscrètes ici.}
{130}{}{Bien sûr.}
{131}{}{Ca ne m'intéresse pas.}
{132}{}{Pas pour le moment, je te recontacterai.}
{133}{}{Va-t'en, je n'ai pas la patience.}
{134}{}{Ta vie a-t-elle de l'importance à tes yeux ?}
{135}{}{Tu as eu ta chance, maintenant dégage.}
{136}{}{Tu cherches des ennuis ?}
{137}{}{Tu as besoin d'une leçon, pas vrai ? Je vais t'apprendre le respect.}
{138}{}{J'ai entendu parler de toi. On dit que tu es une ordure. Si tu cherches du boulot, je peux te présenter quelqu'un. Cela t'intéresse ?}
{139}{}{J'ai entendu parler de toi. On dit que tu es une ordure. Si tu cherches du travail, je peux te présenter quelqu'un. Cela t'intéresse ?}
{140}{}{J'ai entendu parler de toi. C'est toi qui as débarrassé Dépôtville de Killian. Joli travail. Gizmo a dû bien te payer pour ce boulot. Qu'est-ce qui t'amène au Centre, tu cherches du travail ?}
{141}{}{J'ai entendu parler de toi. C'est toi qui as débarrassé Dépôtville de Gizmo. Killian a dû te payer une petite fortune pour ce travail. Tu cherches peut-être du travail ?}
{142}{}{J'ai entendu parler de toi. C'est toi la fille qui s'est occupée de Killian et de Gizmo. C'est la manière de régler les problèmes maintenant. Alors que fais-tu au Faucon Maltais ? Tu cherches du travail ?}
{143}{}{J'ai entendu parler de toi. T'es le type qui s'est occupé de Killian et de Gizmo. C'est la manière de régler les problèmes maintenant. Alors que fais-tu au Faucon Maltais ? Tu cherches du travail ?}
{144}{}{J'ai entendu parler de toi. Tu commences à être célèbre. Qu'est-ce qui t'amène au Centre ?}
{145}{}{Je cherche une puce d'eau.}
{146}{}{Je dois parler à Decker.}
{147}{}{C'est toi qui tient ce tripot ? }
{148}{}{Je suis ici pour te botter le cul.}
{149}{}{Bon, je crois que je vais employer la force maintenant.}
{150}{}{Tu n'auras plus à te soucier pour ta santé lorsque je t'aurai réglé ton compte.}
{151}{}{Je nettoie le monde de tout ce qui est mal !}
{152}{}{Je dois partir, au revoir.}
{153}{}{C'est ça, au revoir.}
{154}{}{Euh ?}
{155}{}{Bazookaaa !}
{156}{}{Une puce d'eau ? J'en ai jamais entendu parler, on ne vend que des boissons. Et si t'as faim, va voir Bob à l'Iguane Rôti.}
{157}{}{C'est un dispositif électronique qui régule le système de filtrage d'un épurateur d'eau et empêche toute contamination. Le mien est cassé et j'en cherche un autre.}
{158}{}{Non, c'est une petite pièce qui permet de faire fonctionner un épurateur d'eau.}
{159}{}{Une autre question... }
{160}{}{Ok, merci. Au revoir.}
{161}{}{Est-ce que j'ai l'air d'un marchand ambulant ? Arrête de me faire perdre mon temps.}
{162}{}{Tu devrais t'adresser aux Marchands d'Eau. Ils se trouvent au Sud du Grand Marché. Tu ne peux pas les louper. Ils sont installés autour d'un gigantesque château d'eau.}
{163}{}{Toi ? C'est la chose la plus amusante que j'ai jamais entendue.}
{164}{}{Tu seras bien amusé quand je t'aurai refait la face !}
{165}{}{Rira bien qui rira le dernier.}
{166}{}{Tu crois que tu peux m'avoir ? Tu as peut-être du cran, mais ça protège pas des balles.}
{167}{}{Tu as raison. Excuse-moi. Je t'en prie, ne tire pas.}
{168}{}{Je vois. Tu te caches derrière ton arme, pas vrai ?}
{169}{}{Tu me fais pitié. Je devrais peut-être te mettre une balle dans la tête pour abréger tes souffrances. Alors, que dirais-tu d'un joli trou dans ton crâne vide ?}
{170}{}{Excuse-moi. Je ne le pensais pas. Je t'en prie, ne tire pas.}
{171}{}{Une arme, c'est donc ça. Mais moi, j'en ai pas besoin pour te botter le cul !}
{172}{}{Quoi ? Tu as peur d'une petite fille comme moi, tu dois utiliser une arme ? }
{173}{}{Bien sûr.}
{174}{}{Bon, si tu crois connaître la souffrance, attends de voir quand j'en aurai fini avec toi.}
{175}{}{Surveille cette andouille ou je lui fais la peau.}
{176}{}{Laisse tes camarades en dehors de tout ça. }
{177}{}{Laisse tes potes en dehors de tout ça ou ils sont morts.}
{178}{}{Arrière les gars, il est à moi.}
{179}{}{Arrière les gars, elle est à moi.}
{180}{}{Tu me déçois. Je te croyais plus costaud que ça.}
{181}{}{Me cacher ? J'ai pas besoin de me cacher ! Et j'ai pas besoin d'une arme pour m'occuper de toi !}
{182}{}{Surveille cette andouille ou je lui fais la peau.}
{183}{}{Laisse tes camarades en dehors de tout ça. }
{184}{}{Laisse tes potes en dehors de tout ça ou ils crèvent.}
{185}{}{(Par-dessus son épaule) Arrière les gars, il est à moi.}
{186}{}{(Par-dessus son épaule) Arrière les gars, elle est à moi.}
{187}{}{Tout ça c'est du baratin. Ecoute p'tit gars, je vais mettre ce joujou de côté et on verra bien qui va l'emporter.}
{188}{}{Tout ça c'est du baratin. Ecoute p'tite fille, je vais mettre ce joujou de côté et on verra bien qui va l'emporter.}
{189}{}{Excuse-moi. Vraiment, j'en pensais pas un mot. Par pitié, ne me fais pas de mal.}
{190}{}{Alors viens par ici ; je t'attends.}
{191}{}{Ok, mais j'veux surtout pas te faire pleurer.}
{192}{}{Non merci. J'ai pas le temps. Au revoir.}
{193}{}{Si j'étais toi, je ne tournerais pas le dos après ce que tu viens de dire. Tu devrais me remercier de te pardonner... pour cette fois. Jusqu'à notre prochaine rencontre.}
{194}{}{Je vais adorer ça.}
{195}{}{Surveille cette andouille ou je lui fais la peau.}
{196}{}{Laisse tes camarades en dehors de tout ça.}
{197}{}{Laisse tes potes en dehors de tout ça ou ils sont morts. }
{198}{}{(Par-dessus son épaule) Arrière les gars, elle est à moi.}
{199}{}{(Par-dessus son épaule) Arrière les gars, il est à moi.}
{200}{}{Du nettoyage ? C'est une bonne idée, mais le 'mal' est très subjectif. Ce que tu juges mauvais est peut-être bon pour une autre personne.}
{201}{}{Oui, c'est vrai. Mais cela veut-il dire que nous devons rester là sans rien faire parce-que nous ne sommes pas sûrs ?}
{202}{}{C'est ridicule. Ce qui est mal est mal. Et tout avis contraire est stupide.}
{203}{}{Laisse tomber. Je ne faisais que plaisanter.}
{204}{}{J'espère. Il y a assez de problèmes dans le monde sans devoir supporter les fanatiques aveugles prêts à tuer tout ce qui bouge.}
{205}{}{Quel dommage ! Le fanatisme est dangereux.. J'espère que tu ne resteras pas trop longtemps au Centre. On n'aime pas les meurtriers, quels qu'ils soient. Au revoir.}
{206}{}{Non.}
{207}{}{Bonne réponse imbécile. Qui s'occupe de cet endroit ?}
{208}{}{Qui ?}
{209}{}{Imbécile ? Sais-tu à qui tu t'adresses ? J'espère pour toi que non. C'est pas moi le proprio mais qui gère le Faucon Maltais. Qu'est-ce que tu veux, avant que je m'énerve ?}
{210}{}{Je sais qui tu es et crois-moi, tu es un imbécile.}
{211}{}{Oh, désolé. Qui est le boss ?}
{212}{}{On verra. Bonne journée...}
{213}{}{Si tu ne sais pas, tu ne devrais pas poser la question. Tu pourrais te blesser.}
{214}{}{C'est par rapport à quoi ?}
{215}{}{Un travail.}
{216}{}{C'est un secret.}
{217}{}{Cela ne te concerne pas. Maintenant, conduis-moi à lui.}
{218}{}{Méfie-toi, si tu veux rencontrer Decker vivant, fais pas l'idiot. Je t'ai à l'œil.}
{219}{}{Méfie-toi, si tu veux rencontrer Decker vivant, fais pas l'idiote. Je t'ai à l'œil.}
{220}{}{Je pense que ça me concerne et je ne crois pas que je te montrerai quoi que ce soit... enfin si tu as de la chance. Maintenant, va te faire voir.}
{221}{}{Désolé mais tout ce que tu as à dire à Decker tu peux me le dire. Je suis son bras droit et rien ne se passe ici sans que nous soyons tous les deux au courant.}
{222}{}{C'est à propos d'un boulot.}
{223}{}{Je regrette mais j'ai juré que je n'en parlerais qu'à Decker.}
{224}{}{Bon et bien, tu ne le verras pas.}
{225}{}{Qui t'envoie ?}
{226}{}{Beth.}
{227}{}{Lorenzo.}
{228}{}{Loxley.}
{229}{}{Le Shérif.}
{230}{}{Personne.}
{231}{}{Beth qui ?}
{232}{}{Tu le sais bien.}
{233}{}{Elle ne m'a pas dit son nom. Elle tient l'armurerie.}
{234}{}{Hors de ma vue. Je n'ai pas de temps à perdre.}
{235}{}{Alors, tu ne verras personne.}
{236}{}{Dis au Shérif Greene que l'emploi du temps de Decker est un peu surchargé et qu'il n'a qu'à réessayer dans quelques mois. Désolé, mais je crois que tu ferais mieux de partir... pour de bon.}
{237}{}{Je te crois pas. Va t'en.}
{238}{}{Et alors ? Sont-il prêts à accepter notre protection ? Es-tu des leurs ?}
{239}{}{Je sais pas de quoi tu parles. Il a juste dit que Decker aurait du travail pour moi.}
{240}{}{Moi ? Travailler pour ces voleurs, jamais ! L'argent n'est pas tout.}
{241}{}{Toi ? Nous protéger ? JAMAIS !}
{242}{}{Ecoute, camarade. Je cherche juste un bon boulot, propre et honnête.}
{243}{}{Ah bon ? Eh bien, tu as frappé à la mauvaise porte. Le Centre est tout sauf honnête. Retourne d'où tu viens. Tu y seras bien mieux.}
{244}{}{D'accord. Eh bien, suis-moi et nous verrons comment tu peux te rendre utile. N'oublie pas que tu as intérêt à garder pour toi tout ce que tu entendras.}
{245}{}{Ca se pourrait bien. Fais-tu partie de leur 'Cercle des Voleurs ?'}
{246}{}{Oui.}
{247}{}{Non.}
{248}{}{Eh bien, désolé, mais nous ne travaillons pas avec tes petits amis. Nous avons déjà du mal à les supporter, alors pas question de travailler avec eux.}
{249}{}{Très bien. Tu pourrais être utile après tout. Mais n'oublie pas que c'est dans ton intérêt de ne pas divulguer ce que tu apprendras}
{250}{}{Peut-être. Quel genre de travail recherches-tu ?}
{251}{}{As-tu besoin d'un autre garde ?}
{252}{}{Oh, je n'ai pas d'idée précise. Je me demandais juste.}
{253}{}{Tout ce qui se présente, du moment que ça paie bien.}
{254}{}{Tout ce qui se présente, du moment que c'est légal.}
{255}{}{Pourquoi n'essaies-tu pas les marchands. J'ai entendu dire qu'ils payaient plutôt bien.}
{256}{}{Non, nous avons ce qu'il nous faut. Au revoir.}
{257}{}{Bon, c'est ce que j'aime entendre. Nous serons peut-être amis après tout. Suis-moi. Mais souviens-toi que tu ne devras rien révéler de ce que tu entendras. }
{258}{}{Très bien. Suis-moi, mais n'oublie pas que tu as intérêt à garder pour toi tout ce que tu entendras.}
{259}{}{Mais oui, cause toujours. Allez, au revoir... Oh,  et ne t'avise plus de me mentir. Je n'aime pas les gens qui mentent. Peu de personnes sont restées assez longtemps en vie pour entendre ce conseil.}
{260}{}{Un homme d'action. J'aime ça, même si tu es un peu fêlé.}
{261}{}{Une femme d'action. J'aime ça, même si tu es un peu fêlée.}
{262}{}{Ouais, qu'est-ce que tu veux ? J'espère pour toi que ça vaut la peine.}
{263}{}{Si tu veux me parler, tu ferais mieux de poser ton arme.}
{264}{}{T'as entendu ce que je t'ai dit ? Range ton arme si tu veux me parler.}
{265}{}{Ton arme !}
{266}{}{Pas mal, pas mal du tout, tu m'as surpris. Je ne pensais pas que tu serais si difficile à battre. D'ordinaire, je suis plus doué pour juger les gens. Tu feras peut-être l'affaire. Veux-tu du travail ?}
{267}{}{Bon sang ! Quel combat ! Je n'ai pas participé à un si bon match depuis longtemps et je ne me souviens pas de la dernière fois où je me suis fait battre. Joli ! Alors, tu veux du travail ?}
{268}{}{Certainement, de quoi s'agit-il ?}
{269}{}{Non merci.}
{270}{}{Je ne peux pas pour le moment. Je te recontacterai.}
{271}{}{C'est pas un travail d'amateur. Tu devras le fair' vite et proprement. Le chef va te donner les détails, mais si t'es bon, tu gagneras beaucoup plus d'argent qu'en un mois dans les caravanes. On ne tolère pas l'échec, si tu vois ce que je veux dire.}
{272}{}{Ca a l'air intéressant, continue.}
{273}{}{Hum, je peux y réfléchir ? J'ai un tas d'autres choses en cours.}
{274}{}{Non, je ne pense pas.}
{275}{}{Certainement, fais-moi signe dès que tu peux. Le plus tôt sera le mieux.}
{276}{}{Ok, préviens-moi si tu changes d'avis. Ce serait dommage de perdre ton temps à garder des caravanes.}
{277}{}{Bien, tout se passera comme sur des roulettes. Mais n'oublie pas que tu dois garder tout ce que tu entendras pour toi. Allons-y.}
{278}{}{D'après ce que j'ai compris, tu es responsable de la mort d'un marchand et de sa femme. Je ne sais pas ce qu'il y avait entre vous et cela m'est égal.}
{279}{}{Qui te l'a dit ?}
{280}{}{Je ne sais pas de quoi tu parles.}
{281}{}{Hmm Hein ?}
{282}{}{A ta place, je me ferais du souci. Personne ne s'attaque à qui que ce soit sans avoir reçu notre aval. Je te conseille de quitter la ville avant qu'il ne soit trop tard.}
{283}{}{Je te préviens, tu devrais quitter la ville pendant que tu le peux encore.}
{284}{}{J'avais pas compris que tu voulais ce boulot... C'est un malentendu... Bon, je te paie la moitié et estime-toi heureux d'être engagé. [Kane te donne 1500 caps]}
{285}{}{Merci.}
{286}{}{Oh, je croyais l'avoir obtenu ce boulot. Pourrais-je travailler pour toi une autre fois ?}
{287}{}{Donne-moi immédiatement le reste de l'argent où tu le regretteras !}
{288}{}{Hein ?}
{289}{}{On verra. Descends, Decker veut te parler.}
{290}{}{Tu n'auras rien de plus.}
{291}{}{Je ne sais pas à quoi tu joues, mais tu ferais bien de quitter la ville pendant qu'il en est encore temps.}
{292}{}{Tu as dit que tu ne voulais pas de ce travail. Je suis surpris de te revoir ici. Tu as fait une erreur en agissant seul. Je te conseille de quitter la ville tant que tu le peux encore.}
{293}{}{D'après ce que j'ai compris, tu es responsable de la mort d'un marchand et de sa femme. Je ne sais pas ce qu'il y avait entre vous et cela m'est égal., mais nous te sommes néanmoins reconnaissants. (Kane te donne 1000 caps)}
{294}{}{Qui te l'a dit ?}
{295}{}{Je ne sais pas de quoi tu veux parler.}
{296}{}{Hmm Hein ?}
{297}{}{Cela ne te regarde pas et je crains que nous ne puissions rien faire pour toi. Tu as violé nos lois, mais tu nous as aussi enlevé une épine du pied et nous ne te tuerons pas. Je te conseille cependant de partir.}
{298}{}{Mentir est un méchant pêché. Tu as violé nos lois, mais tu nous as aussi enlevé une épine du pied et nous ne te tuerons donc pas. Je te conseille cependant de partir.}
{299}{}{Je ne sais pas à quoi tu joues, mais ça ne m'amuse pas du tout. Tu as violé nos lois mais tu nous as aussi enlevé une épine du pied et nous ne te tuerons donc pas. Je te conseille cependant de partir.}
{300}{}{Ne touche pas cette porte si tu tiens à la vie. Je suis le seul à pouvoir l'ouvrir.}
{301}{}{Le marchand et sa femme vivent à l'Ouest d'ici, à l'angle de Barter Street et Thunder Avenue, sur les Hauteurs. Ils sont probablement protégés par des gardes. Essaie d'être discret et ne te fais pas remarquer. Si quelqu'un te voit, tu devras l'éliminer pour qu'il ne parle pas. Une fois ta mission terminée, reviens ici. Encore une chose. Pense surtout pas à aller voir la police, ce serait une grave erreur. Si tu le peux, tâche de ne pas attirer leur attention, ils peuvent être très gênants parfois. [Kane te donne 500 capsules]}
{302}{}{Beau travail. Voilà les caps qui te reviennent pour ce premier boulot. [Kane te tend 2500 caps].}
{303}{}{Beau travail pour le marchand. J'attends de toi les mêmes résultats pour ta prochaine mission. Voici ce que je te dois pour ce premier boulot et un accompte pour le deuxième. (Kane te tend 3500 caps). Tu dois le savoir, les Enfants de la Cathédrale se trouvent au Sud, un peu plus au Nord que les Marchands d'Eau... Encore une fois, aucun témoin.}
{304}{}{Tu as hâte de quitter cet endroit ou quoi ? T'as pas pris tes caps ! Voilà, ce que je te dois plus une prime de réussite. (Kane te tend 3000 caps)}
{305}{}{Hé, bon travail ! Tu as oublié ta paie. Voici l'argent, ainsi qu'une prime de réussite. Tu nous a été très utile. }
{306}{}{(Kane te tend 5000 caps)}
{307}{}{C'est tout ce que tu auras. Et maintenant, va-t'en ou tu pourrais le regretter.}
{308}{}{Voici ton premier salaire. (Kane te tend 1000 caps) Tu dois le savoir, les Enfants de la Cathédrale se trouvent au Sud, un peu plus au Nord que les Marchands d'Eau... Encore une fois, aucun témoin.}
{309}{}{Bon sang, ça en fait du fric ! Decker voulait vraiment la peau de cette ordure, voici tes caps. (Kane te donne 4000 caps) Tu nous a été très utile.}
{310}{}{Qu'est-ce que tu veux ? Je croyais que tu ne voulais pas rencontrer Decker.}
{311}{}{C'est vrai, mais peux-tu lui transmettre un message pour moi ?}
{312}{}{Si, je veux le rencontrer pour lui faire éclater la cervelle !}
{313}{}{Excuse-moi, mais je ne comprends pas.}
{314}{}{Bordel, pourquoi est-ce que je voudrais rencontrer un pareil imbécile ?!}
{315}{}{Hmm.}
{316}{}{Hmm Hein ?}
{317}{}{On n'engage pas les pauv'types. Maintenant file avant que je m'énerve.}
{318}{}{Tout dépend du message.}
{319}{}{Dis-lui qu'il n'est qu'un sale trouillard qui se cache sous terre. S'il veut être un homme, il devrait essayer d'affronter le monde réel.}
{320}{}{Dis-lui de bien prier pour un miracle, parce qu'il en aura besoin lorsque je le verrai.}
{321}{}{J'ai oublié.}
{322}{}{Dis-lui qu'il est mon idole et que j'admire son travail.}
{323}{}{Dis-lui que je vais lui faire ce qu'il a fait au dernier type qui a dirigeait cet endroit avant lui !}
{324}{}{Ah oui ? Ca l'amusera beaucoup.}
{325}{}{T'es un idiot !}
{326}{}{T'es quel genre de taré ? Fiche le camp d'ici !}
{327}{}{Oh, je ne manquerai pas de lui transmettre le message. Il sera certainement très intéressé par... tu as bien parlé de 'prière', n'est-ce pas ? Tu as ma parole : je lui transmettrai.}
{328}{}{Je croyais t'avoir dit d'aller te faire voir ! Ma patience a des limites ! Tu vas enfin me dire pourquoi tu voulais voir Decker, oui ou non ?}
{330}{}{Rien ne m'oblige à te dire quoi que ce soit.}
{331}{}{Je voulais juste un travail.}
{332}{}{Je te l'ai déjà dit, c'est un secret !}
{333}{}{Non !}
{334}{}{Heu ?}
{335}{}{Reviens me voir quand tu seras dans ton état normal.}
{336}{}{Je vais te laisser le voir, mais je te conseille de surveiller ton langage !}
{337}{}{N'importe quoi. Au revoir.}
{338}{}{Alors c'est un secret que tu emporteras dans la tombe. Decker parle pas aux cloches de ton espèce.}
{339}{}{Alors je te conseille de partir.}
{340}{}{Oui ?}
{341}{}{Lorenzo m'a fait venir pour un travail.}
{342}{}{Salut !}
{343}{}{Je veux du travail.}
{344}{}{Nn rien. Au revoir.}
{345}{}{Grr.}
{346}{}{Salut.}
{347}{}{Comment ça va ?}
{348}{}{Salut.}
{349}{}{Très bien.}
{350}{}{Comment vont les enfants ?}
{351}{}{Belle journée, n'est-ce pas ?}
{352}{}{Tu as l'air en super forme aujourd'hui.}
{353}{}{Au revoir... (Kane t'observe comme s'il essayait de deviner ce que tu veux.)}
{354}{}{Je suppose. (Kane commence à te regarder bizarrement)}
{355}{}{Tu as l'heure ?}
{356}{}{Les pieds des brahmines sont vraiment délicieux.}
{357}{}{Non... Tu voulais quelque chose ? (On dirait que tu l'agaces de plus en plus)}
{358}{}{Oui.}
{359}{}{Non.}
{360}{}{Je crois que tu as besoin d'un autre verre, mon gars.}
{361}{}{Je crois que tu as besoin d'un autre verre, ma fille.}
{362}{}{(Kane attend quelques secondes) Eh bien... de quoi s'agit-il ? (Kane a l'air très agacé.)}
{363}{}{De quoi s'agit-il ?}
{364}{}{J'ai oublié.}
{365}{}{Oh, rien.}
{366}{}{(On dirait presque que de la fumée sort des oreilles de Kane et les veines de son cou battent avec furie.) FICHE LE CAMP ! (Quelques secondes plus tard, tu l'entends encore.)... VIENS ICI ! PAUVRE IDIOT !}
{367}{}{(Kane grince des dents et t'ignore.)}
{368}{}{Tu as oublié ? (soupir) Pourquoi ne suis-je pas surpris ? (Secouant la tête d'un air incrédule). A présent... DEGAGE !}
{369}{}{(Kane regarde un des gardes et passe le doigt sur une oreille.)}
{370}{}{Mais bon sang, de quoi tu parles ?}
{371}{}{Ce n'est pas la bonne réponse !}
{372}{}{Je vois... Tu ne fais pas partie de leur bande.}
{373}{}{La réponse... A quoi ? (Kane a l'air étonné et légèrement agacé.)}
{374}{}{Le mot de passe secret !}
{375}{}{Excuse-moi, mais je ne peux pas en parler. Au revoir.}
{376}{}{(Kane semble en colère, va savir pourquoi pourquoi.) Fiche le camp d'ici, pauvre con.}
{377}{}{(Kane semble en colère, va savoir pourquoi.) Fiche le camp d'ici, pauvre conne.}
{378}{}{Je t'ai dit de foutre le camp d'ici, pauvre con.}
{379}{}{Je t'ai dit de foutre le camp d'ici, pauvre conne.}
{380}{}{Non, je ne crois pas. Maintenant, DEGAGE. (Il n'a pas l'air de rigoler.)}
{381}{}{Mais j'ai pas d'enfant !}
{382}{}{On dirait que ça t'ennuie. Tu veux en parler ?}
{383}{}{Eh bien tu devrais, ils font de bons serviteurs.}
{384}{}{Ce n'est pas ce que dit Mary.}
{385}{}{Vraiment ? C'est étrange... Très étrange...}
{386}{}{QUOI ? TU... JE... NON ! Je ne veux pas en 'parler'. Mais bon sang, pour qui te prends-tu ? Hors de ma vue !}
{387}{}{JE TE REPETE que je ne veux pas en 'parler'.}
{388}{}{Ah ouais ouais, c'est ça... Cause toujours, mon pote.}
{389}{}{Ah ouais ouais, c'est ça... Cause toujours, ma jolie.}
{390}{}{Sinon, t'en as à vendre, des enfants ?}
{391}{}{Très bien, alors au revoir !}
{392}{}{(Kane regarde une de ses brutes et hausse les épaules)}
{393}{}{NON ! Maintenant, fiche le camp.}
{394}{}{Mary ? Je ne connais pas de Mary. Je n'ai pas de temps à perdre avec ça ! Je ne sais même pas de qui tu parles. Et si elle veut de l'argent, dis-lui de venir me parler elle-même !}
{395}{}{(Tu reçois 100 points d'expérience pour avoir tapé sur les nerfs de Kane.)}
{396}{}{(Pendant une fraction de seconde, tu as l'impression que Kane rougit) C'est... (il te dévisage) ok. Alors, que voulais-tu ?}
{397}{}{Que dirais-tu d'un rencart ? }
{398}{}{Oh, rien. Au revoir.}
{399}{}{Oui, enfin je veux dire non. Je ne... Je ne peux pas... Je... (Soudain, Kane donne un coup de poing dans la mâchoire d'un de ses gardes.) Qu'est-ce qui te fait sourire ! (Il te regarde de nouveau.) Que fais-tu encore ici ?}
{400}{}{(Kane t'ignore...) Que veux-tu ?}
{401}{}{Comment vont les enfants ?}
{402}{}{Belle journée, n'est-ce pas ?}
{403}{}{Par là.}
{404}{}{Tu connais le chemin, allons-y.}
{405}{}{Ouvrez les gars.}
{406}{}{Très bien.}
{407}{}{Ok.}
{408}{}{Tu peux avoir tous ceux que tu veux. Maintenant, va voir ailleurs.}
{409}{}{As-tu encore du travail à me proposer ?}
{410}{}{Salut !}
{411}{}{Rien, au revoir.}
{412}{}{Crr !}
{413}{}{Rebonjour.}
{414}{}{Quoi ? Tu n'en as pas eu le courage, n'est-ce pas ? (Il soupire) Ne t'inquiète pas, on finit par s'habituer. S'il a des gardes, essaie d'attendre qu'ils s'en aillent. Ils finiront bien par aller manger. Si tu le peux, distrais-les. Débrouille-toi comme tu veux, mais pas question d'échouer. Fais ce que tu as à faire, tu auras ton argent et tu pourras partir d'ici. Bon... tu avais besoin de quelque chose ?}
{415}{}{Pourquoi le boulot n'est-il pas encore fait ? Règle ça au plus vite. Je ne veux pas te revoir avant que tu aies de bonnes nouvelles à nous annoncer, sinon nous allons avoir un problème. Ne nous déçois pas.}
{416}{}{Voilà. Tu as commis ta dernière erreur. Tu ferais mieux de quitter la ville, si tu ne veux pas y rester... six pieds sous terre.}
{417}{}{Alors, tu vas le faire ce travail ou pas ? Ils sont juste là. (Kane désigne encore l'écran de ton Pip-Boy ou est affichée la carte de la ville.) Tu devrais te dépêcher. Le chef s'impatiente.}
{418}{}{BON SANG... (Kane regarde autour de lui et murmure :) Bon sang, mais que fais-tu ici ? Tu dois en finir au plus vite et veille à ce qu'il ne reste pas de témoins.}
{419}{}{Voilà. T'as medré. Et maintenant, tu vas devoir payer pour tes erreurs. J'espère que tu n'envisageais pas de passer la nuit ici.}
{420}{}{Tu n'as pas fini ton petit boulot. (en soupirant) Tu connais l'enjeu. Tu le fais, tu t'enrichis et tout le monde est content. Mais si tu échoues, personne ne sera content.}
{421}{}{Si tu ne sais pas comment t'y prendre, attends qu'elle soit seule.}
{422}{}{Le temps passe et je m'impatiente.}
{423}{}{Je ne le ferai pas.}
{424}{}{Elle sera bientôt morte.}
{425}{}{Hmm.}
{426}{}{Ah non ? C'est dommage ! Nous n'aimons pas les gens qui ne tiennent pas leurs promesses. Je regrette que nous n'ayons pas pu travailler ensemble. Passe une bonne journée...}
{427}{}{Ok ! Je ferai ce fichu travail. Mais y'a intérêt que l'on me donne cet argent quand tout sera terminé.}
{428}{}{Merci.}
{429}{}{Oh, tu l'auras. Ne t'inquiète pas.}
{430}{}{Toujours en vie à ce que je vois ! Eh bien, tu n'as pas dû te faire beaucoup d'amis récemment. J'espère que tu gardes l'oeil ouvert.}
{431}{}{(Kane semble satisfait. Il reste immobile et arbore un regard malveillant.)}
{432}{}{Eh bien ! Je suis très surpris de te voir en vie. Tu as survécu, impressionnant. Je crois que je vais te laisser vivre. Tu en vaux la peine. A présent, va-t'en.}
{433}{}{N'y pense même pas.}
{434}{}{Je ne rate jamais ma cible.}
{435}{}{Tu as de la chance que je te laisse la vie, tu devrais être reconnaissant.}
{436}{}{Je ne pense pas que tu veuilles prendre ce risque.}
{437}{}{J'espère pour toi que tu n'envisages pas d'utiliser ça.}
{438}{}{Tu devrais partir.}
{439}{}{Ne sois pas bête.}
{440}{}{Tu vas le regretter.}
{441}{}{Soit tu as du cran, soit tu es totalement stupide pour te montrer ici, mais rassure-toi, tu auras de nos nouvelles.}
{442}{}{(Kane te fixe du regard.)}
{443}{}{Tu as survécu à ma petite fête d'adieu... Je ne sais pas comment tu as fait, mais j'ai dû te sous-estimer. Tu as encore une chance de partir.}
{444}{}{(Kane t'ignore, mais tient son arme, prêt à tirer.)}
{445}{}{Très bien ! Dehors !}
{446}{}{Je ne le dirai pas deux fois. Va-t'en.}
{447}{}{Je t'avais prévenu. Ok les gars, emparez-vous de lui !}
{448}{}{Je t'avais prévenue. Ok, les gars, emparez-vous d'elle !}
{449}{}{Ne me dérange pas, mets-toi au boulot. Tu as un travail à faire et je te conseille de le faire.}
{450}{}{Est-ce que tu vas enfin terminer le boulot ? Je t'ai déjà dit ce que tu avais à faire. Alors fais-le.}
{451}{}{Je sais que tu as terminé ce fichu travail. Pas la peine de me le dire. C'est à Decker que tu dois parler.}
{452}{}{Je t'ai dit que tu dois parler à Decker !}
{453}{}{(Kane te lance un terrible regard.) Eh bien... Je vais t'envoyaer à lui prochainement. Je ferai en sorte de te présenter à lui morceau par morceau.}
{454}{}{Je suis désolé que tu le prennes comme ça. J'espère que tu apprécieras le reste de ton séjour dans cette ville merveilleuse. }
{455}{}{(Kane t'ignore.)}
{456}{}{(Kane te fixe quelques secondes) Très bien. Je vais te donner une dernière chance d'aller le voir. Suis-moi.}
{457}{}{(Kane te fixe quelques secondes) Tu as manqué ta chance. Tant pis pour toi.}
{458}{}{Bon sang, mais qu'est-ce que tu fous là ?! Tu dois être encore plus bête que je ne le pensais. Je savais que Decker n'aurait pas dû embaucher un inconnu.}
{459}{}{De quoi parles-tu ?}
{460}{}{Hein ?}
{461}{}{[Kane baisse la voix] Tu as tout fait foiré, imbécile ! Tu devais les tuer, pas les blesser ! Bon sang ! A la seconde ou tu as quitté les Hauteurs, ils se sont enfuis avec leurs gardes. Et crois-moi, ils n'ont pas prit el temps de faire leurs valises. Dieu seul sait où ils sont à l'heure qu'il est !}
{462}{}{Eh bien, que puis-je dire ? Je m'excuse.}
{463}{}{EuH. Pardoon.}
{464}{}{Je me fiche de tes excuses. Tu as mis Decker en danger et c'est inacceptable. Tu fais désormais partie de nos ennemis. Je ne veux plus te voir ici.}

{465}{}{Tu ne peux pas franchir cette porte si Kane est ici.}

