{100}{}{Le bandit ne fait pas attention à toi.}
{101}{}{Le bandit se moque de toi en passant.}
{102}{}{Voici un bandit armé à l'air louche.}
{103}{}{Gizmo te fait ses hommages !}
{104}{}{ points d'expérience pour avoir aidé Killian à lutter contre l'assassin.}
