{100}{}{Voici le Député Kenny.}
{101}{}{Pour les questions relatives à la police du Centre, adresse-toi au Shérif Greene. Je ne m'occupe de ses affaires qu'en son absence.}
{102}{}{Je ne peux pas croire que le Shérif soit vraiment mort.}
{103}{}{Te voilà. Je t'attendais. Nous avons entendu dire que le Shérif avait été tué au cours de la bataille. J'ai du mal à croire qu'il n'est plus là. Il était comme un père pour moi.}
{104}{}{Le Shérif m'a donné des instructions à suivre au cas où il ne reviendrait pas de sa mission. Il m'a demandé de te remettre le reste de ta récompense. Je crois qu'il s'agissait de 1000 caps. [L'adjoint te tend 1000 caps.]}
{105}{}{Cette ville te doit une fière chandelle. J'aimerais tant que le Shérif soit là pour te remercier personnellement. Au revoir.}
{106}{}{Oh mon Dieu ! Ils ont tué Kenny ! Les enfoirés !}
