{100}{}{Chevalier}
{101}{}{J'aime travailler sur de nouveaux prototypes.}
{102}{}{Lorsque nos réserves sont limitées, utiliser ce que nous avons relève parfois du défi.}
{103}{}{Je ne comprends pas pourquoi mon dernier prototype n'a pas fonctionné.}
{104}{}{Excuse-moi, je ne peux pas parler pour le moment.}
{105}{}{Vree est là-bas.}
{106}{}{Bon, où ai-je rangé ce fichier ?}
{107}{}{Où est ce schéma ?}
{108}{}{Eh bien, d'après l'ordinateur ça devrait fonctionner. Bon, j'ai dû faire quelque chose de travers !}
