{100}{}{Tu ouvres la plaque d'égout et sort des égouts humides.}
{101}{}{Tu passes les épaules par la plaque d'égout et t'agrippes à l'échelle.}
{102}{}{Tu n'arrives pas à bouger la plaque d'égout.}
{103}{}{Tu manques de tomber de l'échelle.}
{104}{}{Tu tombes par terre.}
