# Kids in Boneyard / Blades territory
# Will spawn if the player enters with motorcycle

# Floats ini
{110}{}{WOOOAAAAAH!}
{111}{}{C'EST QUOI ?!!}
{112}{}{WAAAH !}
{113}{}{REGARDE !}
{114}{}{BRRRRRRRR !}
{115}{}{TROOOP COOOOL !}
{116}{}{WOOOAH !}
{117}{}{C'EST POUR DE VRAI ??}
{118}{}{}
{119}{}{COOL !}
{120}{}{WOOW !}

# Floats scared
{125}{}{AAAAAAAHHHH !}
{126}{}{AAAAH !}
{127}{}{MAMAN !}
{128}{}{AAAAAH !}
{129}{}{A l'aide !}
{130}{}{Tu fait trop peur !}


# Floats cool
{150}{}{Est-ce que c'est à toi, Monsieur ?}
{151}{}{Est-ce que c'est à toi, Madame ?}
{152}{}{T'es trop cool !!}
{153}{}{Trop cool !}
{154}{}{Mon oncle dit que tu te la raconte !}
{155}{}{Je veux être comme toi quand je serai grand !}
{156}{}{Il faut que Jason voit ça !}
{157}{}{Je peux venir avec toi ?}
{158}{}{C'est parti ! BRRRRR !}
{159}{}{C'est mieux que ces foutus chariots à Brahmine toute la journée.}
{160}{}{Tu habite dans la région ?}
{161}{}{Je ne t'ai jamais vu avant.}
{162}{}{Tu es nouveau ici, non ?}
{163}{}{Est-ce que tu va rester longtemps ?}
{164}{}{Tu as pas l'air méchant ?}
{165}{}{ ! }
{166}{}{Je ne volerai rien ! Promis !}
{167}{}{}
