{100}{}{Voici Lasher, des Enfants.}
{101}{}{Je sais qui tu es. Tu es un homme méchant et diabolique. Tu dois être puni.}
{102}{}{Je sais qui tu es. Tu es le diable réincarné en femme, mais ton apparence ne te sauvera pas.}
{103}{}{Je sais qui tu es. Ta méchanceté te précède. Tu envoies des âmes d'enfants en Enfer, avant même qu'ils n'aient eu le temps de se purifier de leurs perfidies. Tu propages le mal et tu vas le payer.}
{104}{}{Je sais qui tu es. Tu es la mort personnifiée, un fléau ayant revêtu une enveloppe humaine. Tu répands des torrents de sang sur ton passage. Mais une âme vertueuse vengera tes iniquités !}
{105}{}{Comment oses-tu me déranger ! Ne connais-tu pas mon rang ? Sors !}
{106}{}{Ce n'est pas très prudent de pointer ton arme sur moi. Je porte le bouclier du Maître et toute personne qui m'atteint est châtiée !}
{107}{}{Je revêtirais volontiers le bouclier du Maître moi aussi.}
{108}{}{Personne ne m'a jamais accusé de prudence !}
{109}{}{Je veux juste parler au responsable.}
{110}{}{Tu as là une bien jolie baguette, Lasher.}
{111}{}{Est-il vrai que tu aimes maltraiter les enfants ?}
{112}{}{Tu veux savoir ce qui est imprudent ? Il est très imprudent de se moquer de moi !}
{113}{}{Pourquoi tu parles comme ça ?}
{114}{}{Pourquoi es-tu là, Initié ? Tu sais que je n'aime pas qu'on me dérange.}
{115}{}{Pardonne-moi, Père, mais quelque chose m'inquiète.}
{116}{}{Je souhaite que la Cathédrale me guide dans mon action.}
{117}{}{Je suis là pour te parler des mauvais traitements que tu infliges aux enfants.}
{118}{}{Je voulais seulement discuter.}
{119}{}{Tu as là une bien jolie baguette, Lasher.}
{120}{}{Qu'est-ce que tu dirais de ne plus jamais être dérangé ? Eh bien, je peux arranger ça !}
{121}{}{Je sais pas. Pourquoi je suis venu ? Tu as une idée ?}
{122}{}{Comment oses-tu entrer dans mon sanctuaire avec une arme à la main ! Rustre ! Sors !}
{123}{}{Pour qui te prends-tu pour oser entrer dans mon sanctuaire une arme à la main. Sors !}
{124}{}{Pardonnez-moi. Mais les forces obscures sont partout et on ne sait jamais à quel moment on devra se défendre.}
{125}{}{Je souhaite que la Cathédrale me guide dans mon action.}
{126}{}{Je suis là pour te parler des mauvais traitements que tu infliges aux enfants.}
{127}{}{Je voulais seulement discuter.}
{128}{}{Tu as là une bien jolie baguette, Lasher.}
{129}{}{Si tu n'aimes pas les armes, tu vas détester ce que je vais en faire !}
{130}{}{Sortir ? Par où ?}
{131}{}{Mes quartiers ne sont pas ouverts à ceux qui n'ont pas été sacrés. Je dois te demander de sortir immédiatement.}
{132}{}{Pardonne mon intrusion : j'ai d'importantes questions à te poser.}
{133}{}{Je suis là pour te parler des mauvais traitements que tu infliges aux enfants.}
{134}{}{Je voulais te poser des questions sur le sacre.}
{135}{}{Tu as là une bien jolie baguette, Lasher.}
{136}{}{Cet endroit est pas sacré. J'ai tué personne pour l'instant.}
{137}{}{Imbécile ! De nombreuses con... sé... crations ont eu lieu...}
{138}{}{C'est un privilège réservé aux serviteurs les plus fidèles. Le baptème est le seul honneur qui le dépasse.}
{139}{}{Et comment accède-t-on au baptême ?}
{140}{}{Je suppose que tu prépares les Enfants au baptême.}
{141}{}{Peux-tu m'aider à me faire baptiser ?}
{142}{}{Ouah ! Tu dois être quelqu'un d'important !}
{143}{}{Dommage qu'une fois mort ces privilèges ne valent pas mieux que la queue d'un radscorpion.}
{144}{}{Je n'ai pas de temps à perdre en causeries avec les imbéciles. Va t'en.}
{145}{}{Tu devrais t'adresser au Père Morpheus. Il est dans la tour, mais il y a peu de chances que les Ténébreux te laissent passer.}
{146}{}{Pourrais-tu les convaincre de me laisser passer ?}
{147}{}{Que peux-tu me dire sur Morpheus ?}
{148}{}{Que peux-tu me dire sur les Ténébreux ?}
{149}{}{Merci, monsieur.}
{150}{}{Je sais comment régler ce genre de problèmes.}
{151}{}{La baguette est le saint instrument qui me permet de dispenser mes enseignements. La souffrance purge les esprits de leurs pensées malveillantes et leur permet de mieux appréhender la gloire du Maître.}
{152}{}{Je vois. Alors le Maître est une plaie ?}
{153}{}{C'est monstrueux de faire ça à des enfants !}
{154}{}{Ca me semble bizarre. Tu veux essayer sur moi ?}
{155}{}{J'instruis les enfants. C'est mon travail. Tous les enfants sont méchants. Il est de mon devoir de les aider à devenir des êtres humains. Peut-être as-tu entendu dire que je ne tolérais pas la frivolité. C'est vrai. Je veux que mes élèves souffrent le plus possible.}
{156}{}{Et les mutants ? Sont-ils plus évolués que les êtres humains ?}
{157}{}{Espèce de monstre !}
{158}{}{On ne t'a jamais passé dessus, n'est-ce pas ?}
{159}{}{Parle-moi de tes méthodes d'enseignement.}
{160}{}{Et le plaisir de tuer alors ? C'est autorisé ?}
{161}{}{Espèce d'abomination écervelée ! Comment oses-tu salir ma présence ! Sors ! Dehors ! Immédiatement !}
{162}{}{Tu es une femme, tu es donc toujours troublée. C'est un état endémique chez le sexe faible. Expose-moi ton problème, et je le résoudrai.}
{163}{}{Si ton coeur n'était pas si rempli de méchanceté, tu aurais l'esprit tranquille. Un coeur vertueux ne connaît point les tourments. Expose-moi ton problème, mais vite !}
{164}{}{Dis-moi comment accéder à la vertu !}
{165}{}{Je veux en savoir plus sur la Cathédrale.}
{166}{}{Je veux en savoir plus sur le Maître.}
{167}{}{T'es toujours en vie. C'est ça mon problème, espèce d'ordure !}
{168}{}{Apprends à apprivoiser la souffrance comme s'il s'agissait de ton meilleur ami, car la souffrance est la force la plus édifiante de l'univers. Détruis-toi jusqu'à ne plus exister en tant qu'individu, puis tu renaîtras sous forme d'outil du Maître. Voilà la solution à tous tes problèmes.}
{169}{}{Et la plaie suprême, où vais-je pouvoir la trouver ?}
{170}{}{C'est ça, je vais subir un lavage de cerveau pour rejoindre un culte de zombies ! Tu rêves !}
{171}{}{Je n'y aurais jamais pensé !}
{172}{}{Vraiment ? C'est de la merde, mec !}
{173}{}{J'ai déjà apprivoisé la souffrance. Je voudrais maintenant la partager avec mes amis.}
{174}{}{Les bêtes jacassent sans réfléchir. Les êtres humains, eux, réfléchissent avant de parler. Tu dois devenir un être humain avant que je n'accepte de te parler. Va-t'en.}
{175}{}{Ce que tu dis est vrai. Très bien, je vais t'aider. Mais vite.}
{176}{}{Je dois rencontrer le Père Morpheus d'urgence.}
{177}{}{Parle-moi de la Cathédrale.}
{178}{}{Je me demandais où je pourrais trouver le Maître.}
{179}{}{Parle-moi des Enfants.}
{180}{}{La seule chose rapide que je connaisse, c'est la Mort.}
{181}{}{Il arrive un moment où tu dois trouver toi-même les réponses aux questions fondamentales et ce moment est arrivé. Va-t'en !}
{182}{}{Ce n'est pas mon travail. Va t'en maintenant.}
{183}{}{En endurant la souffrance, en atteignant la sagesse et en accédant à la servilité. La Souffrance c'est la connaissance, la Sagesse : l'obéissance,  et la Servilité : le courage.}
{184}{}{[Suite]}
{185}{}{Tu dois rejeter la Lumière qui nous a presque tous détruits et te vouer à l'Obscurité dans laquelle nous sommes égaux. A présent, tu peux entamer ta quête, ta quête du Maître et de sa sagesse.}
{186}{}{Je ne l'ai pas consulté, mais je pense qu'il est satisfait des âmes vertueuses que je lui ai confiées. C'est un travail difficile, mais je le fais bien. Hélas, ça me prend beaucoup de temps, c'est pourquoi je dois te demander de partir.}
{187}{}{Une langue flatteuse dans la bouche d'un démon ! Le démon qui est en toi ! Hors de ma vue !}
{188}{}{Espèce de langue de vipère ! Va-t'en ! Et apprends les bonnes manières avant de revenir.}
{189}{}{C'est une requête raisonnable. Prends ce signe et montre-le aux Ténébreux quand tu voudras passer.}
{190}{}{Je ne peux rien pour toi. Va t'en.}
{191}{}{C'est notre chef. Il est proche des conseillers du Maître et il en sait beaucoup à son sujet. C'est tout ?}
{192}{}{Pourrais-tu convaincre les Ténébreux de me laisser passer ?}
{193}{}{Peux-tu m'en dire plus sur Morpheus ?}
{194}{}{Peux-tu me parler des Ténébreux ?}
{195}{}{Merci, monsieur.}
{196}{}{Alors, pourquoi tu le suis ce Morpheus ?}
{197}{}{Ils servent le Maître. Ils cultivent la souffrance pour guérir le monde. Les Anges de la Nuit purgent le monde en versant le sang. La curiosité est une émotion audacieuse, et particulièrement lorsqu'il s'agit des Ténébreux. Je ne te le dirai pas deux fois. Bien, j'ai à faire à présent. Va t'en.}
{198}{}{Ta courtoisie te fait honneur. Tu es peut-être digne de parler à Morpheus. Si les Ténébreux t'arrêtent, montre-leur ce signe. Maintenant, va-t'en !}
{199}{}{Tu as tort de croire que ce petit subterfuge trompera les Ténébreux. Sors d'ici !}
{200}{}{La décadence et la désinvolture font obstacle à l'évolution, l'évolution qui est nécessaire à la survie dans ce monde si rude. Heureusement, je suis un homme endurci qui se moque des plaisirs de la séduction. Je vois que tu n'es pas d'accord avec moi. Je me moque de ton opinion. Sors d'ici !}
{201}{}{Il ne faut pas avoir peur de la mutation. Chaque naissance est une mutation de l'ADN de nos parents. Nous sommes tous des mutants. La seule chose qui compte, c'est que le mutant soit guidé sur un chemin moral et utile. C'est mon travail. Voilà qui met fin à cette discussion. Laisse-moi maintenant.}
{202}{}{Je dispense la souffrance. Si l'animal en est digne et s'il peut en tirer des enseignements, il évolue en âme vertueuse. Sinon, il ne mérite pas d'exister. Parfois, l'animal est retiré du bassin génétique, mais pas aussi souvent que je le voudrais. Ceci se produit souvent avec les animaux dont l'évolution a échoué.}
{203}{}{Et le Maître approuve ces méthodes d'enseignement ?}
{204}{}{Tu es un monstre !}
{205}{}{Je crois que je vais m'en aller.}
{206}{}{Enseignes-tu à des adultes ?}
{207}{}{L'évolution des animaux ?}
{208}{}{Eh, je peux les en retirer à ta place ! Personne d'autre n'a besoin de savoir !}
{209}{}{Tu es une femme diabolique. Tu ferais bien d'être vigilante ici. Les Ténébreux n'aiment pas la rivalité. Va t'en maintenant !}
{210}{}{Tu es un homme diabolique. Tu ferais bien d'être vigilant ici. Les Ténébreux n'aiment pas la rivalité. Va t'en maintenant !}
{211}{}{On accède à la vertu par la lutte, le traumatisme et la guérison. Nous sommes des animaux voués à être brisés jusqu'à ce que nous acceptions sans hésiter la vérité du Maître. Maintenant que tu as entendu la vérité, cherche-la à travers tes expériences. Sors d'ici.}
{212}{}{Tu n'as que la méchanceté à la bouche, sans aucune rédemption possible. Hors de ma vue !}
{213}{}{La Cathédrale enseigne de nombreux concepts qu'un esprit non-discipliné est incapable d'appréhender. Maintenant, j'ai à faire. Au revoir !}
{214}{}{Comme moi. Il semble que nous ayons beaucoup de points communs, mais hélas, je ne te supporte plus. Va t'en d'ici tout de suite.}
{215}{}{Ce n'est pas à moi de juger. Tu dois convaincre les Ténébreux. Bonne chance. Tu en auras besoin.}
{216}{}{La Cathédrale est le sanctuaire de l'espèce humaine. Lorsque l'apocalypse a frappé cette ville, la Cathédrale a été épargnée, ce qui a permis la naissance du Maître. C'est ainsi qu'une obscurité curative a émergé d'une lumière abominable.}
{217}{}{A mon arrivée, j'ai vu que cet endroit manquait de repères moraux, c'est pourquoi j'ai pris l'initiative d'enseigner la souffrance aux victimes des plaisirs oisifs. C'est tout ce que tu dois savoir.}
{218}{}{On dit que le Maître attend en dessous, dans l'Obscurité : la Lumière du dessus a en effet trahi les Hommes et les a presque détruits. Mais beaucoup bénissent la Lumière qui selon eux a donné naissance au Maître.}
{219}{}{Je n'ai aucune certitude et je n'ai jamais eu le privilège de le voir. Maintenant, si tu veux bien m'excuser, j'ai du travail.}
{220}{}{Ta présence n'a jamais été particulièrement la bienvenue. Bon débarras.}
{221}{}{Ca m'est arrivé une fois, mais de nombreuses méthodes ont été abandonnées au profit de ces bruits que tu peux entendre dans l'amphithéâtre de l'Auditorium. C'est une source d'amertume. Heureusement, je peux toujours enseigner aux enfants. Maintenant, excuse-moi, je dois préparer mes cours.}
{222}{}{Euh... cela se produit rarement, et l'animal a toutes les chances d'évoluer. Maintenant, va t'en ! Va t'en tout de suite !}
{223}{}{[Terminé]}
{224}{}{Ceci peut t'être utile. Prends ce signe. Montre-le aux Ténébreux quand tu voudras passer. Ca te permettra de rencontrer le Père Morpheus.}

# Weapon-drawn timer is up, let's attack:
{250}{}{Je t'avais dit de t'en aller !}