{100}{}{Oh non.}
{101}{}{Tu t'es pris dans un câble laser qui a déclenché une sorte de mécanisme de défense. Tu prends un point de dégât.}
{102}{}{Tu t'es pris dans un câble laser qui a déclenché une sorte de mécanisme de défense. Tu prends }
{103}{}{ points de dégât.}
{104}{}{Tu t'es pris dans un câble laser qui a déclenché une sorte de mécanisme de défense.}

{105}{}{ s'est pris dans un câble laser qui a déclenché une sorte de mécanisme de défense.}

