{100}{}{Voici un personnage à l'air sournois.}
{101}{}{Pssst ! Viens là.}
{102}{}{Alors, qu'est-ce tu fais au Centre ?}
{103}{}{Ca te regarde pas.}
{104}{}{Pourquoi ?}
{105}{}{Je cherche quelque chose dont j'ai besoin.}
{106}{}{Où est ma Maman ?}
{107}{}{Pas sûr. A plus tard.}
{108}{}{Ah.}
{109}{}{Me fatigue pas. J'voulais juste voir si je pouvais t'être utile. [Lemmy s'en va]}
{110}{}{Eh, tu as l'air d'un homme d'affaires. Moi, j'suis un homme d'affaires. Et je pensais qu'on pourrait parler, euh, affaires.}
{111}{}{Alors, qu'est-ce que tu fais par ici ?}
{112}{}{Je crois que je vais te confier cette affaire !}
{113}{}{Je veux pas me mêler de tes "affaires".}
{114}{}{Eh bien, nous avons tous des besoins. Je peux peut-être t'aider. Quels sont tes besoins ?}
{115}{}{Eh bien, je cherche une puce d'eau. J'ai besoin d'en rapporter une à mon peuple.}
{116}{}{Des besoins, hein ? Je comprends, mais comment saurais-tu les satisfaire ?}
{117}{}{J'ai besoin de certains renseignements.}
{118}{}{Je n'ai certainement besoin de rien de ce que tu me proposeras.}
{119}{}{Je fais un peu de tout. Je recueille des trucs et des informations pour les gens.}
{120}{}{Eh bien, j'ai besoin de certains trucs.}
{121}{}{Quelque chose de précis ?}
{122}{}{Je cherche une puce d'eau. Je suppose que tu n'as pas ça, n'est-ce pas ?}
{123}{}{A plus tard.}
{124}{}{Une puce d'eau, hmmmm. J'ai jamais entendu parler de ça. Si j'tais toi, j'm'en irais voir les Marchands d'Eau. Ils s'occupent de tout ce qui a trait à l'eau par ici.}
{125}{}{Alors, que fais-tu ici ?}
{126}{}{Alors, que sais-tu d'autre ?}
{127}{}{Merci des renseignements.}
{128}{}{Pas de problème. Si tu as besoin d'autre chose, adresse-toi d'abord à Lemmy.}
{129}{}{Alors, tu cherches certaines informations, hein ? Etant homme d'affaires respectable, j'ai pas mal de frais, c'est pourquoi je te demanderai quelques caps en échange des informations qu'il te faut. Maintenant que les choses sont claires, qu'est-ce tu savoir ?}
{130}{}{Alors, tu crois que je peux te donner des renseignements sur cette histoire de puce d'eau, hein ? Eh bien, tu as sans doute raison. Mais va falloir m'payer. 500 caps d'vraient faire l'affaire.}
{131}{}{D'accord, quelles sont ces informations ?}
{132}{}{Disons 400.}
{133}{}{Tu vas me dire ce que tu sais tout de suite, et pas question de te payer !}
{134}{}{Trop cher pour moi.}
{135}{}{Voyons. Je ne serais pas ce que j'suis si je bradais mes informations. Reviens quand tu auras d'quoi payer.}
{136}{}{T'essaies d'intimider c'pauvre vieux Lemmy, hein ? Tu sais, les gens comme toi y m'font pas peur. On se r'verra.}
{137}{}{[Lemmy prend ton argent]}
{138}{}{Ca me va. D'accord.}
{139}{}{Ok, ok, ok, tu sais, cet argent en échange de mes renseignements, c'était pour plaisanter. Bonne blague, non ?}
{140}{}{Eh bien, voilà ce que je sais sur les puces d'eau. Ce que je sais, c'est qu'elles viennent toutes des Abris. Alors, si ça t'intéresse tu d'vrais te renseigner. Je ne connais pas leurs emplacements exacts, mais j'ai entendu dire qu'il y en a 4 dans les environs.}
{141}{}{Je voudrais te poser d'autres questions.}
{142}{}{Merci.}
{143}{}{Oui, qu'est-ce tu savoir de plus ?}
{144}{}{Tu sais quelque chose sur les puces d'eau ?}
{145}{}{Que sais-tu sur Decker ?}
{146}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{147}{}{Eh bien, j'ai un besoin urgent, si tu vois ce que je veux dire.}
{148}{}{Rien pour l'instant.}
{149}{}{D'habitude, ça n'me dérange pas de vendre mes informations, mais, Lemmy il te dira jamais rien sur m'sieur Decker !}
{150}{}{Ok, mais je peux quand même te poser d'autres questions ?}
{151}{}{Merci.}
{152}{}{Les caravanes disparues, hein ? Ben, j'sais p't-être quequ'chose. Mais, ça va te coûter 300 caps.}
{153}{}{D'accord, que sais-tu ?}
{154}{}{Je t'en donne 240.}
{155}{}{Tu vas me dire ce que tu sais tout de suite, et pas question de te payer !}
{156}{}{Trop cher pour moi.}
{157}{}{Eh bien, ce n'est pas sûr, mais d'après ce que j'ai entendu dire, les gens se font des illusions. Un type dont on n'a jamais entendu parler serait dans le coup, lui et des espèces de mutants ou je n'sais quoi. Mais je ne suis pas sûr de moi.}
{158}{}{Cherchez la logique... Es-tu sûr de quelque chose, Lemmy ?}
{159}{}{Puis-je te poser une autre question ?}
{160}{}{Merci.}
{161}{}{Tu veux sans doute insinuer que Lemmy n'est pas honnête. Eh ben t'as raison. Mais Lemmy il est VIVANT !}
{162}{}{Ok, laisse tomber. Est-ce que je peux te poser une autre question ?}
{163}{}{Eh bien, on peut changer ça !}
{164}{}{Laisse tomber. A plus.}
{165}{}{Des trucs dont tu as besoin, hein ? Eh bien, je connais un type dans la Vieille Ville qui pourrait sans doute quelque chose pour toi. Mais tu sais, il doit savoir qui tu es avant que tu te présentes chez lui.}
{166}{}{Laisse-moi deviner. Cette "invitation" va me "coûter" quelque chose ?}
{167}{}{Je vois où tu veux en venir. Je le trouverai moi-même.}
{168}{}{Exactement. Alors, j'pensais... 1 000 caps - tarif spécial. Ca d'vra  suffire pour t'présenter devant ce type et pour quy t'fasse pas sauter la cervelle.}
{169}{}{Très bien, je paierai ce que tu veux.}
{170}{}{Que dirais-tu de 800 caps ?}
{171}{}{[En échauffant tes muscles :] Puisque tu m'aimes tellement Lemmy, pourquoi ne le ferais-tu pas gratuitement ?}
{172}{}{Je ne peux pas me le permettre.}
{173}{}{Alors, ce que tu vas faire, c'est te rendre dans la Vieille Ville. Là-bas, y'a un type qui s'appelle Vance. Va le voir. Comme j'ai dit, je le préviendrai d'ta visite.}
{174}{}{Quel bon coeur ! Je peux te demander autre chose ?}
{175}{}{Merci.}
{176}{}{Malheureusement j'ai à faire. Mais ça m'a fait plaisir de discuter.}
{177}{}{Alors, tu r'viens voir ton vieil ami Lemmy, hein ? Qu'est-ce que j'peux faire pour toi ?}
{178}{}{Eh, tu as l'air d'une femme d'affaires. Moi, j'suis un homme d'affaires. Et je pensais qu'on pourrait parler, euh, affaires.}
