{100}{}{Ce n'est pas parce que tu pointes une arme sur moi que je vais te donner ce que tu veux...}
{101}{}{Je suis à ta merci ! Bon sang, que veux-tu de plus ?}
{102}{}{J'ai rien à dire ! Y'a que les faibles qui parlent !}
{103}{}{Je ne sais pas qui tu es, mais je te préviens : tous ceux qui cherchent des histoires aux Khans y crèvent.}
{104}{}{Tu sais, si tu pensais vraiment avoir le dessus, tu me tuerais.}
{105}{}{Ca tombe mal, c'est à toi que je cherche des histoires !}
{106}{}{Bien. Je propose qu'on arrête de se chercher des histoires, ça sera mieux pour nous deux.}
{107}{}{Je me rends. S'il te plaît, ne me tue pas !}
{108}{}{Argh !}
{109}{}{Hein ?}
{110}{}{Salut frère Khan ! Comment va la chasse ? Beaucoup de mauviettes sont mortes aujourd'hui ?}
{111}{}{Salut soeur Khan ! Comment va la chasse ? Beaucoup de mauviettes sont mortes aujourd'hui ?}
{112}{}{Je réserve mes vantardises pour le feu de camp, mais j'ai des tas d'histoires à raconter !}
{113}{}{J'ai pillé et fait coulé le sang.}
{114}{}{Pas mal. Et toi ?}
{115}{}{J'ai fait encore mieux...}
{116}{}{Tu es un ennemi des Khans ! Tu attaques nos guerriers et tu enlèves nos femmes ! Donne-moi une seule bonne raison de t'épargner !}
{117}{}{Assez ! Où est Tandi ? Dis-le-moi ou tu mourras !}
{118}{}{Je n'arrive pas à réfléchir. Battons-nous !}
{119}{}{Parce que nous vivrons tous les deux si tu n'essaies pas.}
{120}{}{Je ne suis pas en état de me battre. Je me rends.}
{121}{}{En es-tu un ? Es-tu un de ces mutants ?}
{122}{}{Que sais-tu sur les mutants ?}
{123}{}{Ouais, je suis un mutant !}
{124}{}{Est-ce que j'ai l'air d'un mutant ?}
{125}{}{Non.}
{126}{}{Peut-être. Si tu veux te battre, je me battrai. Si tu veux partir en paix, je te donne ma parole de Khan que je ne t'attaquerai pas.}
{127}{}{Battons-nous.}
{128}{}{Evitons de nous battre.}
{129}{}{Ta parole de Khan ? Laisse-moi rire !}
{130}{}{Je ne fais pas le poids face à toi et je n'en peux plus après tout ce temps passé dans le désert. Je ne veux pas mourir. J'ai honte de dire ça mais je me rends.}
{131}{}{D'accord. Je te promets que tu pourras partir en paix, à condition que tu ne me provoques pas. Ne me cherche plus d'histoires.}
{132}{}{Je ne veux rien de quelqu'un d'aussi lâche, même pas sa vie ! Va t'en !}
{133}{}{Stupide animal ! Je vais me faire un plaisir de te tuer !}
{134}{}{Euh, oui...}
{135}{}{Ca me fera plaisir de les entendre. Adieu, mon frère !}
{136}{}{Ca me fera plaisir de les entendre. Adieu, ma soeur !}
{137}{}{Vraiment ? Alors, je veux être le seul à entendre ça !}
{138}{}{Oui, j'ai entendu dire que tu avais beaucoup de chance. C'est uniquement pour cette raison que je ne te défie pas. Adieu, mon frère ! Peut-être qu'un jour nous combattrons ensemble contre l'ennemi.}
{139}{}{Oui, j'ai entendu dire que tu avais beaucoup de chance. C'est uniquement pour cette raison que je ne te défie pas. Adieu, ma soeur ! Peut-être qu'un jour nous combattrons ensemble contre l'ennemi.}
{140}{}{Je n'en peux plus après ce voyage qui a duré plus longtemps que prévu. Les radscorpions ont tué mes compagnons. J'ai hâte de retrouver le confort du camp et les soins de nos femmes.}
{141}{}{Que la chance soit de nouveau avec toi. Adieu, mon frère.}
{142}{}{Que la chance soit de nouveau avec toi. Adieu, ma soeur.}
{143}{}{Ils ont détruit les Sables Ombragés. Ils tuent tous ceux qu'ils rencontrent sur leur passage. Une telle férocité est inimaginable. Nous sommes tous condamnés...}
{144}{}{Chien meurtrier !}
{145}{}{Non, mais j'ai entendu dire qu'ils se glissent dans la nuit, qu'ils enveloppent les esprits des hommes et qu'ils prennent l'apparence de jolies femmes ! Nous sommes tous perdus !}
{146}{}{Tant mieux. J'ai hâte de venger nos morts et ceux des Sables Ombragés. Tous les mutants que je rencontrerai mourront ! En avant ! En avant et à l'attaque ! Mort aux mutants !}
{147}{}{Tu mourras pour ces paroles !}