{100}{}{Voici Lorenzo.}
{101}{}{Ici c'est un établissement respectable. Nous ne traitons pas avec les types comme toi. Va t'en.}
{102}{}{Ici c'est un établissement respectable. Nous ne traitons pas avec les femmes comme toi. Va t'en.}
{103}{}{T'as du retard pour le remboursement de ton emprunt. Si tu paies pas immédiatement, je risque de m'énerver. Et je n'aime pas quand on m'énerve.}
{104}{}{Mon vieux, me menace pas. Moi aussi, j'ai des amis.}
{105}{}{J'ai besoin d'un peu de temps. S'il te plaît !}
{106}{}{Je veux rembourser mon emprunt de }
{107}{}{ caps.}
{108}{}{Je n'ai pas ça sur moi.}
{109}{}{Salut. Alors, tu viens rembourser ton emprunt ?}
{110}{}{En fait, j'espérais que tu pourrais me fournir quelques informations...}
{111}{}{Je suis là pour faire un nouvel emprunt.}
{112}{}{Peut-être plus tard.}
{113}{}{Gné ?}
{114}{}{Je t'avais pourtant dit de ne pas revenir. Ok les gars, vous savez ce qu'il vous reste à faire !}
{115}{}{Eh bien, voilà un client potentiel ! Je m'appelle Lorenzo le Généreux, à ton service. Je prête des caps au taux imbattable de seulement 10% par jour, avec un délai de remboursement de 10 jours maximum. Tu ne trouveras pas mieux dans tout le Centre !}
{116}{}{Je suis là pour faire un emprunt.}
{117}{}{Tu m'as l'air d'un escroc !}
{118}{}{Eh bien, peut-être. Que veux-tu savoir ?}
{119}{}{Parle-moi des caravanes disparues.}
{120}{}{Parle-moi de Decker.}
{121}{}{Parle-moi de la police locale.}
{122}{}{Parle-moi des Enfants de la Cathédrale.}
{123}{}{Parle-moi de toi.}
{124}{}{Où peut-on trouver du travail par ici ?}
{125}{}{Désolé mais je suis pas du genre à alimenter les rumeurs. Ne redemande pas.}
{126}{}{Je t'ai déjà dit que j'aimais pas alimenter les rumeurs. Si tu ne me prends pas au sérieux, tant pis pour toi. Fiche le camp et ne remets plus les pieds ici, crapule !}
{127}{}{Désolé mais je n'accorde jamais plus d'un prêt à la fois. Si tu veux te l'argent, tu dois d'abord rembourser tes dettes. Je fais des affaires, pas la charité.}
{128}{}{Bien. C'est un plaisir de faire des affaires avec toi. Autre chose ?}
{129}{}{Imbécile ! Tu n'as pas assez d'argent pour rembourser tes dettes ! Tu pensais peut-être à autre chose... ?}
{130}{}{En fait, j'espérais que tu puisses me fournir quelques informations...}
{131}{}{Je suis là pour faire un nouvel emprunt.}
{132}{}{Peut-être plus tard.}
{133}{}{Ok ! N'hésite pas à repasser. Nous sommes toujours prêts à rendre service.}
{134}{}{Va voir ailleurs si j'y suis. Allez ! Et ne remets plus les pieds ici !}
{135}{}{Eh ! Pas de menaces ! Il n'y a que des gens civilisés ici. Guido, Léone, montrez à ce monsieur à quel point nous sommes civilisés.}
{136}{}{Eh ! Pas de menaces ! Il n'y a que des gens civilisés ici. Guido, Léone, montrez à cette dame à quel point nous sommes civilisés.}
{137}{}{Guido, Leone, j'ai a vous parler un moment...}
{138}{}{Tu as de la chance.}
{139}{}{En fait, j'espérais que tu puisses me fournir quelques informations...}
{140}{}{Je voudrais un autre prêt.}
{141}{}{Peut-être plus tard.}
{142}{}{Tu n'as pas assez ! Comment oses-tu essayer de me rouler ! Guido, Léone, occupez-vous de cette crapule.}
{143}{}{Ok. Tu n'as aucune dette envers nous. Nous prêtons par tranches de deux cents caps, le maximum étant de mille caps. Mais je ne te prêterai pas de grosses sommes tant que tu n'auras pas prouvé que tu peux rembourser les petits emprunts.}
{144}{}{Je voudrais }
{145}{}{1 000}
{146}{}{800}
{147}{}{600}
{148}{}{400}
{149}{}{200}
{150}{}{ caps.}
{151}{}{Je ferais mieux de renoncer à cet emprunt.}
{152}{}{Guido, Léone, montrez-lui comment nous traitons les voleurs !}
{153}{}{Désolé mais je ne prends jamais le risque de prêter aux imbéciles dans ton genre. Sors d'ici !}
{154}{}{Les Griffemorts ! C'est sûrement les Griffemorts ! Personne n'est plus en sécurité de nos jours !}
{155}{}{Parle-moi des Griffemorts.}
{156}{}{Parle-moi de Decker.}
{157}{}{Parle-moi de la police locale.}
{158}{}{Parle-moi des Enfants de la Cathédrale.}
{159}{}{Parle-moi de toi.}
{160}{}{Où peut-on trouver du travail par ici ?}
{161}{}{C'est un type bien. Une source intarissable d'emplois pour rembourser mes prêts. Dis-lui que tu viens de ma part, il te donnera peut-être une prime !}
{162}{}{Parle-moi des caravanes disparues.}
{163}{}{Une prime ? Que veux-tu dire ?}
{164}{}{Parle-moi de la police locale.}
{165}{}{Parle-moi des Enfants de la Cathédrale.}
{166}{}{Parle-moi de toi.}
{167}{}{Où peut-on trouver du travail par ici ?}
{168}{}{Ce sont des types bien ! C'est vrai que parfois il y a des malentendus mais je pense qu'ils font honneur à leur espèce... [tout bas]... quelle qu'elle soit...}
{169}{}{Parle-moi des caravanes disparues.}
{170}{}{Parle-moi de Decker.}
{171}{}{Des malentendus ? Quel genre ?}
{172}{}{Parle-moi des Enfants de la Cathédrale.}
{173}{}{Parle-moi de toi.}
{174}{}{Où peut-on trouver du travail par ici ?}
{175}{}{Ils m'impressionnent pas ! Je dirige une affaire honnête et respectable et ils me traitent d'escroc ! Quel culot ! S'ils croient qu'avoir fait voeu de pauvreté leur donne le droit de me juger !}
{176}{}{Parle-moi des caravanes disparues.}
{177}{}{Parle-moi de Decker.}
{178}{}{Parle-moi de la police locale.}
{179}{}{Voeu de pauvreté ?}
{180}{}{Parle-moi de toi.}
{181}{}{Où peut-on trouver du travail par ici ?}
{182}{}{Je ne suis qu'un homme d'affaires respectable, c'est tout. Nous, les Giovanni, on était déjà dans les affaires bien avant la bombe. C'est une tradition !}
{183}{}{Parle-moi des caravanes disparues.}
{184}{}{Parle-moi de Decker.}
{185}{}{Parle-moi de la police locale.}
{186}{}{Parle-moi des Enfants de la Cathédrale.}
{187}{}{Quelle est ta définition du mot respectable ?}
{188}{}{Où peut-on trouver du travail par ici ?}
{189}{}{Tu devrais aller voir M. Decker. Il offre des emplois passionnants et très bien payés ! Tu ne trouveras pas mieux ailleurs ! Et il se trouve juste en face ! Ca ne peut pas être plus pratique !}
{190}{}{Parle-moi des caravanes disparues.}
{191}{}{Parle-moi de Decker.}
{192}{}{Parle-moi de la police locale.}
{193}{}{Parle-moi des Enfants de la Cathédrale.}
{194}{}{Parle-moi de toi.}
{195}{}{Passionnants ! Comment ça ?}
{196}{}{Laisse tomber, ce serait trop risqué de te faire un prêt. Va t'en et ne reviens pas.}
{197}{}{Bien. Mille caps. Tu as 10 jours pour rembourser.}
{198}{}{Bien. Huit cents caps. Tu as 10 jours pour rembourser.}
{199}{}{Bien. Six cents caps. Tu as 10 jours pour rembourser.}
{200}{}{Bien. Quatre cents caps. Tu as 10 jours pour rembourser.}
{201}{}{Bien. Deux cents caps. Tu as 10 jours pour rembourser.}
{202}{}{Dommage. Reviens nous voir plus tard.}
{203}{}{Oh, certaines des histoires qu'on raconte sont carrément... enfin, c'est quelque chose !}
{204}{}{Parle-moi de Decker.}
{205}{}{Parle-moi de la police locale.}
{206}{}{Parle-moi des Enfants de la Cathédrale.}
{207}{}{Parle-moi de toi.}
{208}{}{Où peut-on trouver du travail par ici ?}
{209}{}{Eh bien, au revoir !}
{210}{}{Enfin, peut-être pas une prime. Mais c'est un type bien, fais-moi confiance !}
{211}{}{Parle-moi des caravanes disparues.}
{212}{}{Parle-moi de la police locale.}
{213}{}{Parle-moi des Enfants de la Cathédrale.}
{214}{}{Parle-moi de toi.}
{215}{}{Où peut-on trouver du travail par ici ?}
{216}{}{Eh bien, au revoir !}
{217}{}{Tu te rends compte qu'on m'a accusé d'extorsion ? Heureusement que mon vieil ami Decker était là !}
{218}{}{Parle-moi des caravanes disparues.}
{219}{}{Parle-moi de Decker.}
{220}{}{Parle-moi des Enfants de la Cathédrale.}
{221}{}{Parle-moi de toi.}
{222}{}{Où peut-on trouver du travail par ici ?}
{223}{}{Eh bien, au revoir !}
{224}{}{Ca m'étonnerait que leur chef, ce Morpheus, soit fauché ! Non ! Et je parie qu'il est en train de faire la fête, là-bas, au Cimetière de L.A. !}
{225}{}{Parle-moi des caravanes disparues.}
{226}{}{Parle-moi de Decker.}
{227}{}{Parle-moi de la police locale.}
{228}{}{Parle-moi de toi.}
{229}{}{Où peut-on trouver du travail par ici ?}
{230}{}{Eh bien, au revoir !}
{231}{}{Nous nous manque de respect, t'as des problèmes. Peut-on se montrer plus respectable que ça ?}
{232}{}{Parle-moi des caravanes disparues.}
{233}{}{Parle-moi de Decker.}
{234}{}{Parle-moi de la police locale.}
{235}{}{Parle-moi des Enfants de la Cathédrale.}
{236}{}{Où peut-on trouver du travail par ici ?}
{237}{}{Eh bien, au revoir !}
{238}{}{De l'aventure, du danger. Tu peux en tirer de sacrés bénéfices !}
{239}{}{Parle-moi des caravanes disparues.}
{240}{}{Parle-moi de Decker.}
{241}{}{Parle-moi de la police locale.}
{242}{}{Parle-moi des Enfants de la Cathédrale.}
{243}{}{Parle-moi de toi.}
{244}{}{Eh bien, au revoir !}
{245}{}{A plus tard !}
{246}{}{Eh... enlève tes sales pattes de cette porte !}
{247}{}{Eh ! Cette fois tu vas le payer !}
{248}{}{Désolé mais je n'ai pas de temps à perdre. Si tu ne peux pas tout rembourser, donne-moi ce que tu as. Sache que plus jamais je ne traiterai avec toi.}
{249}{}{Eh bien, d'accord. Tu peux prendre tous mes caps.}
{250}{}{Oh ! Ca me revient ! J'ai juste assez pour te payer !}
{251}{}{[Tu essaies de tromper Lorenzo en ne lui donnant que }
{252}{}{ caps]}
{253}{}{N'y pense pas ! Je ne te donnerai pas un seul cap !}
{254}{}{[Tu donnes tous tes caps à Lorenzo]}
{255}{}{[Tu lui donnes }
{256}{}{ caps]}
{257}{}{Tas de merde ! Tu m'avais caché ça ! Tu vas me le payer !}
{258}{}{Quel dommage ! Eh bien, ça va te coûter cher. Guido ! Léone !}
{259}{}{Très bien. Je suppose qu'il faudra s'en contenter. J'espère que t'as bien compris que je ne pourrai jamais plus traiter avec toi ? Et si je te revois ici, je risque d'être moins indulgent.}
{260}{}{Tu m'énnèrve. Donne-moi cet argent et va t'en ! Et que je ne te revois pas ici !}
{261}{}{T'as pas assez !}

# New:
	{300}{}{Ce sera tout. Salut !}
{310}{}{Bonjour. Comment puis-je vous aider ?}
	{311}{}{J'aimerai bien rembourser mon emprunt.}
{312}{}{Un autre emprunt ? Est-ce que tu as quitté le building au moins ? Et si tu allait faire quelque chose d'autre d'abord ? Peut-être aller voir au Faucon Maltais ? Reviens me voir plus tard.}
{313}{}{Déjà ? As-tu au mois quitté le building ? Je suis occupé, reviens me voir à un autre moment !}


