{100}{}{Voici le Lieutenant de l'armée du Maître.}
{101}{LIEUT1}{Bon, que se passe-t-il ? Tu aurais des informations de la plus haute importance à me confier. J'espère que c'est vrai.}
{102}{}{Euh, ouais.}
{103}{}{Pas à un affreux comme toi.}
{104}{}{A une condition.}
{105}{}{Ben !}
{106}{LIEUT1A}{Des insultes. Hilarant ! Bon, si tu comprends pas, cherche pas. Venons-en à tes deux alternatives : soit tu me dis gentiment ce que je veux savoir, soit tu le craches... à ma manière.}
{107}{}{C'est ni l'un ni l'autre.}
{108}{}{Ok, mais à une condition.}
{109}{}{D'accord, je parle. C'est de l'autre côté des montagnes, loin vers le Nord. Tu le trouveras près d'un rocher bizarre, en forme de dôme... Alors, ma récompense ?}
{110}{LIEUT1B}{J'avais promis quelque chose ? Je te remercie pour m'avoir dit où est ton Abri. Je suis sûr que le Maître saura... apprécier.}
{111}{LIEUT2}{Comme ça, on est content tous les deux. Bon, suffit... l'emplacement de ton Abri.}
{112}{}{C'est, euh... c'est, euh...}
{113}{}{A une condition, mon pote.}
{114}{}{Je t'ai bien eu, hein ? Tu sauras jamais !}
{115}{}{Ok, ok ! Mais me tue pas ! Je te dirai tout ce que je sais !}
{116}{LIEUT3}{Des conditions ? Charmant. Vas-y, amuse-moi encore avec tes... conditions.}
{117}{}{Je veux partir librement.}
{118}{}{Fous-toi un sac sur la tête pour que je supporte ta binette.}
{119}{}{D'abord, je veux pouvoir te poser quelques questions.}
{120}{LIEUT4}{Quel sens de l'humour ! Dommage que je n'en aie pas. Alors... ton Abri se trouve où, je te prie.}
{121}{}{D'accord, mais je peux d'abord te poser quelques questions ?}
{122}{}{Je te dirai pas et tu pourras pas me forcer.}
{123}{}{C'est, euh... C'est, euh...}
{124}{LIEUT5}{Mais certainement, chère petite chose humaine. Je suis curieux de voir ce que tu vas demander.}
{125}{}{C'est quoi que tu fais ici ?}
{126}{}{Pour qui tu travailles ?}
{127}{}{Qu'est-ce que tu veux de moi ?}
{128}{}{Et si je partais maintenant ?!}
{129}{LIEUT7}{Chère petite chose humaine, c'est le grand procréateur ! Ici, nous perpétuons la race des maîtres et nous assurerons l'unité. Rien que des desseins sublimes, je t'assure.}
{130}{}{Parle-moi de l'Unité.}
{131}{}{On dirait. Pourquoi vous avez besoin de tout ça pour, euh, procréer ?}
{132}{}{Mais alors, qui commande ?}
{133}{LIEUT8}{Pour l'instant, il y a un léger... problème dans le processus de reproduction. Mais, on s'en occupe. En attendant, on a recours aux Cuves pour changer les humains en Super Mutants. Toi-même, tu vas vivre cette expérience sublime.}
{134}{}{Oh, chouette. Encore quelques questions avant que je ne... m'embrase ?}
{135}{lieut8a}{Comment refuser une demande si gentiment formulée ?}
{136}{LIEUT9}{Certainement. Nous avons tout le temps... Crois-moi.}
{137}{LIEUT10}{L'Unité est notre but. Tu vois, c'est simple. Même toi, tu as dû remarqué cette pente savonneuse que suit la civilisation ?}
{138}{}{Euh, ouais, mais...}
{139}{LIEUT11}{Le Super Mutant est le prochain progrès dans l'évolution humaine. Pour sauver le monde, nous convertirons les individus de valeur. Simple, efficace, sublime.}
{140}{}{Alors comme ça, vous transformez tous les gens en affreux mutants verts pour sauver le monde ?}
{141}{}{Où il est, votre progrès ?}
{142}{}{Mais, le choix dans tout ça ?}
{143}{LIEUT12}{Ton esprit humain ne peut saisir tout cela, donc, pour l'heure, contente-toi d'un simple "oui". Bientôt, le monde entier sera converti, et la paix régnera.}
{144}{}{Mais, et le libre arbitre ?}
{145}{}{Tu me dis qu'il n'y aura pas de guerre ?}
{146}{LIEUT13}{As-tu choisi de naître dans ce monde en cendres ? Nous, les Super Mutants, sommes les mieux armés pour le monde à venir. Qu'est-ce que le libre arbitre, comparé à la vie ?}
{147}{}{Ca se discute. Mais en quoi êtes-vous mieux armés que les humains normaux ?}
{148}{}{Mais c'est monstrueux de forcer les gens à vivre comme vous !}
{149}{LIEUT14}{Ca saute aux yeux de l'observateur le plus naïf. Nous sommes supérieurement intelligents et immunisés contre la maladie. Les forts survivent ! Notre but est d'améliorer la race humaine.}
{150}{}{Un but rudement élevé. Et qu'est-ce qui vous rend comme ça ?}
{151}{LIEUT15}{Ahh, les merveilles de la technologie. Avant la guerre, les scientifiques humains ont fabriqué un stimulant, le FEV. Il devait rendre l'homme parfait.}
{152}{}{Alors, tu es l'homme parfait ?}
{153}{LIEUT16}{Mieux. Plus qu'humain. Moi aussi, j'ai été humain. Comme toi, j'étais une limace vautrée dans la fange, avant d'être exposé au FEV et de passer par cette sublime transformation.}
{154}{}{Alors, vous avez l'intention de plonger tout le monde dans ce FEV ?}
{155}{LIEUT17}{T'as tout compris.}
{156}{}{Euh, certainement. Je peux encore te poser quelques questions ?}
{157}{}{Mais c'est mal !}
{158}{LIEUT18}{Oh, tu me déçois. J'espérais tellement que tu verrais la lumière avant... Ah, quand tu seras des nôtres, je sais que tu comprendras. Alors, tu épouseras l'Unité.}
{159}{}{Jamais ! C'est mal. Mal, j'te préviens !}
{160}{}{Peut-être. D'abord, je peux encore te poser quelques questions ?}
{161}{LIEUT19}{Ni guerre ni maladie. Tous les Super Mutants sont liés par l'Unité. Nous sommes l'espoir du monde.}
{162}{}{Pour moi, c'est plutôt du délire.}
{163}{}{En quoi êtes-vous l'espoir du monde ?}
{164}{LIEUT20}{Tous, nous servons le Maître pour défendre la gloire de l'Unité. C'est lui qui nous a montré la voie.}
{165}{}{Comment es-tu venu à son service ?}
{166}{}{Qu'est-ce que c'est, l'Unité ?}
{167}{LIEUT21}{Le destin. Le hasard des choses. Quand on nous a plongés dans le virus, j'étais le plus fort du lot ; et puis, de l'Unité et du Maître j'ai toujours soutenu les idéaux, car il détient la vérité. Et pour mon dévouement, j'ai été récompensé.}
{168}{}{Quel virus ?}
{169}{}{Et à quoi il ressemble, ce Maître ?}
{170}{LIEUT22}{Avant la guerre, les humains ont fabriqué un virus, le FEV, pour créer l'homme parfait. Tu le vois bien, ils ont réussi. Le Maître a été le premier à vraiment exploiter toutes les possibilités du FEV.}
{171}{}{Et où est-il, ce Maître ?}
{172}{}{Comment ça marche ?}
{173}{LIEUT23}{Il est occupé avec les Enfants de la Cathédrale. En fait, ils nous considèrent comme des dieux. Mais, qui pourrait les en blâmer ?}
{174}{}{Ca par exemple, c'est pas un peu prétentieux ?}
{175}{}{Vous vous prenez pour des dieux ?}
{176}{LIEUT24}{Honnêteté est-elle vanité ? Nous sommes la prochaine étape de l'évolution. Par notre Unité, le monde survivra. Où vois-tu de la prétention ?}
{177}{}{Peut-être bien dans ta grosse tête de bouffon ?}
{178}{}{Ah, si tu le dis. Je peux encore te poser quelques questions ?}
{179}{LIEUT25}{Bien sûr que non. Nous sommes tout simplement l'avenir.}
{180}{}{Je ne te crois pas.}
{181}{}{Bon, en attendant l'avenir, y'a encore deux ou trois choses que j'aimerais savoir.}
{182}{LIEUT26}{Oh, je crains que tout cela ne dépasse ton entendement. Mais ne t'inquiète pas. Bientôt, tes yeux s'ouvriront à une vie entièrement nouvelle.}
{183}{}{Qu'est-ce que tu veux dire !?}
{184}{}{Bon, en attendant l'avenir, y'a encore deux ou trois choses que j'aimerais savoir.}
{185}{LIEUT27}{[Le lieutenant soupire] N'as-tu pas encore compris ? Dans la race des normaux, tu es de premier choix. Bientôt, tu seras des nôtres.}
{186}{}{"Pas de ça Lisette", ça te dit quelque chose ?}
{187}{}{Avant de devenir un fondu comme toi, y'a encore deux ou trois choses que j'aimerais savoir.}
{188}{}{Pourquoi je suis "de premier choix" ?}
{189}{LIEUT28}{Vas-y, pose tes questions. Nous avons tout le temps.}
{190}{LIEUT29}{Il fut notre guide vers le virus de vie, et il est notre Père à tous. Et il veut te rencontrer. C'est un honneur pour toi.}
{191}{}{Euh... d'accord. Et le virus ? Qu'est-ce que c'est ?}
{192}{}{Avant d'accorder cet honneur, ça t'ennuie pas de répondre à d'autres questions ?}
{193}{}{Où il est ?}
{194}{LIEUT30}{Le FEV a muté avec les radiations de la guerre. Les habitants de cette contrée désertique exposés à ce FEV muté en ont reçu les effets de plein fouet.}
{195}{}{Et alors ?}
{196}{}{Et donc, vous cherchez ceux qui ne sont pas contaminés pour en faire des Super Mutants ?}
{197}{LIEUT31}{Alors, comme tu viens d'un Abri ce virus muté n'a pas pu te contaminer. Dans les Cuves, le FEV d'origine devrait bien marcher sur toi.}
{198}{}{Et comment tu sais ça ?}
{199}{LIEUT32}{Nous avons fait des expériences approfondies sur des humains pour aboutir à cette conclusion. Depuis longtemps, mon Maître recherche des Abris encore fermés pour prouver ses théories. Et te voilà. Comme c'est gentil à toi !}
{200}{}{Tu le trouveras pas.}
{201}{}{En attendant tout ça, y'a encore deux ou trois choses que j'aimerais savoir.}
{202}{LIEUT33}{Ca par exemple, tu as plus de cervelle que je ne croyais. Maintenant, tu sais pourquoi il nous faut ton Abri.}
{203}{}{Dommage, vous l'aurez pas.}
{204}{}{C'est un grand Abri. Ca mériterait d'abord quelques petites réponses supplémentaires, non ?}
{205}{LIEUT34}{Tu pars ? Je pense... attends que je vérifie...Ah, j'ai failli rire ! Mon dieu, que c'est amusant. Si tu vas quelque part, c'est aux Cuves. Mais d'abord, tu vas me dire où est ton Abri.}
{206}{}{J'espère que tu ne t'offenseras pas d'un refus.}
{207}{LIEUT35}{C'est ce que nous verrons, d'accord ?}
{208}{lieut35a}{C'est bizarre, mais j'ai comme l'impression que tu n'as pas l'intention de parler. Nous allons devoir y remédier !}
{209}{LIEUT36}{Tu te sens mieux ? Comme la torture est une technique décidément grossière, quoique étrangement satisfaisante et efficace, je vais t'interroger plus... humainement. Où... est... l'Abri ?}
{210}{}{Je Ne Dirai Rien.}
{211}{}{T'as gagné. C'est de l'autre côté des montagnes, à l'Ouest. J'vais te faire un dessin.}
{212}{LIEUT37}{J'espérais bien que tu réagirais ainsi.}
{213}{LIEUT37b}{Tiens, et ça ? Alors, d'humeur plus... bavarde ? Au fait, où en étions-nous ? Ah, suis-je bête... l'Abri.}
{214}{}{C'est... C'est... dans tes rêves.}
{215}{}{T'as gagné. C'est de l'autre côté des montagnes, à l'Ouest. J'vais te faire un dessin.}
{216}{LIEUT38}{Ah, ça va mieux ! Et toi... ? Bon, sois une bonne petite chose humaine et Dis-moi où est ton Abri. Cette conversation devient lassante.}
{217}{}{Va te faire foutre.}
{218}{}{Je dirai tout ! Pitié !}
{219}{}{Quelle volonté ! Mes compliments. Gardes, ramenez-le dans sa cellule et préparez-le à l'immersion. Il parlera quand il sera des nôtres.}
{220}{}{Si t'es si sûr que je vais parler après l'immersion, alors pourquoi toutes ces simagrées ?}
{221}{LIEUT39a}{Vois-tu, il y a un petit inconvénient. Parfois, pas toujours, il arrive que la mémoire soit... comment dire, interrompue par l'immersion. D'où un léger risque que tu oublies l'emplacement.}
{222}{}{Alors, tu peux pas te permettre de m'immerger.}
{223}{}{On dirait qu'on est tous les deux coincés.}
{224}{LIEUT39b}{Malheureusement, où nous en sommes, je dois prendre le risque. Il me faut cette information.}
{225}{}{Je vais parler.}
{226}{}{Vaudrait mieux pour toi que j'oublie. Sinon, gare à tes abattis.}
{227}{LIEUT40}{Excellent. Je crois que tu comprends. Alors, c'est sûr, tu veux dire où est l'Abri ? La torture est parfois si agréable.}
{228}{}{Oui.}
{229}{}{Maintenant que t'en causes, finalement, non.}
{230}{}{D'abord, je peux encore te poser quelques questions ?}
{231}{LIEUT40a}{J'aurais cru que tu te rendrais à mes raisons. T'as bien réfléchi ?}
{232}{}{Je te dirai tout.}
{233}{}{Oui, j'ai changé d'avis et jamais je parlerai.}
{234}{}{D'abord, je peux te poser quelques questions ?}
{235}{LIEUT41}{Oh, excellent. Tu sais, j'ai d'abord douté de mes officiers quand ils m'ont dit avoir capturé un normal de premier choix. Me voilà rassuré.}
{236}{}{Va te faire foutre.}
{237}{}{Qu'est-ce que tu veux de moi ?}
{238}{}{Ben !}
{239}{LIEUT42}{Oui, pas à dire, tu sais y faire avec les mots. Et c'est justement des mots qu'il nous faut, avant...}
{240}{}{Qu'est-ce que tu veux dire, "avant" ?}
{241}{}{Tu tireras rien de moi !}
{242}{LIEUT43}{Mais si, quand tu seras des nôtres, bien entendu ! Imagine, avoir entre les mains un normal de tout premier choix et ne pas en faire l'un des Elus ! Non, impossible. Ensuite, tu me diras où est ton Abri.}
{243}{}{Je vais te dire... T'es presque marrant.}
{244}{}{A une condition.}
{245}{LIEUT44}{Oh, comme c'est louable ! Mais, assez de sottises. Où est ton Abri ?}
{246}{}{Je parlerai pas.}
{247}{}{Eh bien... à une condition.}
{248}{LIEUT45f}{Hmm, j'avoue que tu m'impressionnes. Mes espions m'avaient annoncé quelqu'un d'intelligent, mais ils semblent avoir sous-estimé tes talents. Gardes, capturez-la !}
{249}{LIEUT46}{Alors, la sieste était bonne ? J'espère. Bon, maintenant, à nos affaires.}
{250}{}{Va te faire foutre.}
{251}{}{Qu'est-ce que tu veux de moi ?}
{252}{LIEUT48}{On croit rêver devant pareil intellect. A se demander comment les légions ne se sont pas encore prosternées à tes pieds. Gardes, emmenez cette andouille !}
{253}{LIEUT50}{Comme je l'ai dit...}
{254}{lieut51}{Comme je te l'ai déjà dit...}
{255}{LIEUT52}{S'il te plaît, ouvre grand tes oreilles cette fois. J'ai dit...}
{256}{lieut53}{Je t'ai dit...}
{257}{LIEUT54}{Tu sais, tu me rappelles une blatte que j'avais. Un jour, je l'ai écrasée parce je ne supportais plus ses vilains petits bruits. A bon entendeur...}
{258}{LIEUT55}{Tu es une vraie peste humaine, tu ne crois pas ? Je vais pas le répéter deux fois.}
{259}{LIEUT56}{L'Unité est le but de tous les Super Mutants. Grâce au virus FEV, nous unirons l'humanité dans la paix.}
{260}{LIEUT57}{Le virus FEV a été découvert par le Maître il y a bien des années. C'est ce qui fait de nous les Elus. Mais tu ne vas tarder à l'apprendre, promis.}
{261}{LIEUT58}{Le Maître est notre père à tous.}
{262}{LIEUT59}{Rien d'autre qu'un moyen de parfaire nos desseins. Peu importe, tous les humains seront Elus... ou morts.}
{263}{LIEUT60}{Les Cuves, c'est là que le FEV est entreposé et où vous, les normaux, devenez des nôtres. Bien sûr, certains meurent dans d'atroces douleurs mais... c'est au petit bonheur.}
{264}{LIEUT61}{Ce sont des humains qui n'ont pas été exposés aux radiations. En général, ils s'en sortent mieux que les autres dans les Cuves. Tu en es le parfait exemple.}
{265}{LIEUT62}{Leur construction date d'avant la guerre. C'est aussi notre principale source de Normaux de Premier Choix.}
{266}{LIEUT63}{ Très amusant. Cette limace se prend pour je ne sais quoi, au point que le Maître l'a embauché pour commander cette idiotie des Enfants de la Cathédrale. Ah, lui aussi plongera dans les Cuves et mourra d'une mort horrible... J'espère.}
{267}{LIEUT64}{Aucune importance pour l'instant.}
{268}{LIEUT65}{Cette question ne concerne pas l'Unité.}
{269}{LIEUT66}{Cela ne mérite même pas de réponse.}
{270}{LIEUT45m}{Hmm, j'avoue que tu m'impressionnes. Mes espions m'avaient annoncé quelqu'un d'intelligent, mais ils semblent avoir sous-estimé tes talents. Gardes, capturez-le !}
{271}{LIEUT39f}{Quelle volonté. Mes compliments. Gardes, emmenez-la et préparez-la à l'immersion. Elle parlera quand elle sera des nôtres.}
{272}{LIEUT39m}{Quelle volonté. Mes compliments. Gardes, ramenez-le dans sa cellule et préparez-le à l'immersion. Il parlera quand il sera des nôtres.}

# Fo1in2
{300}{}{Ce n'est pas terminé.}

# Lieutenant Tell-Me-Abouts generic responses
{980}{LIEUT64}{Aucune importance pour l'instant.}
{981}{LIEUT65}{Cette question ne concerne pas l'Unité.}
{982}{LIEUT66}{Cela ne mérite même pas de réponse.}

#
# Lieutenant Tell-Me-Abouts
#


{1000}{}{Unité}
{1001}{}{FEV|VIRUS FEV|VIRUS EVOLUTION FORCE}
{1002}{}{Maître|LE MAITRE|MAITRE}
{1003}{}{Cathédrale}
{1004}{}{Cuves}
{1005}{}{Normaux}
{1006}{}{Abris}
{1007}{}{Morpheus}
{1008}{}{Virus}

{1100}{LIEUT56}{L'Unité est le but de tous les Super Mutants. Grâce au virus FEV, nous unirons l'humanité dans la paix.}
{1101}{LIEUT57}{Le virus FEV a été découvert par le Maître il y a bien des années. C'est ce qui fait de nous les Elus. Mais tu ne vas tarder à l'apprendre, promis.}
{1102}{LIEUT58}{Le Maître est notre père à tous.}
{1103}{LIEUT59}{Rien d'autre qu'un moyen de parfaire nos desseins. Peu importe, tous les humains seront Elus... ou morts.}
{1104}{LIEUT60}{Les Cuves, c'est là que le FEV est entreposé et où vous, les normaux, devenez des nôtres. Bien sûr, certains meurent dans d'atroces douleurs mais... c'est au petit bonheur.}
{1105}{LIEUT61}{Ce sont des humains qui n'ont pas été exposés aux radiations. En général, ils s'en sortent mieux que les autres dans les Cuves. Tu en es le parfait exemple.}
{1106}{LIEUT62}{Leur construction date d'avant la guerre. C'est aussi notre principale source de Normaux de Premier Choix.}
{1107}{LIEUT63}{Très amusant. Cette limace se prend pour je ne sais quoi, au point que le Maître l'a embauché pour commander cette idiotie des Enfants de la Cathédrale. Ah, lui aussi plongera dans les Cuves et mourra d'une mort horrible... J'espère.}
{1108}{LIEUT57}{Le virus FEV a été découvert par le Maître il y a bien des années. C'est ce qui fait de nous les Elus. Mais tu ne vas tarder à l'apprendre, promis.}

{1109}{LIEUT65}{Cette question ne concerne pas l'Unité.}
{1110}{LIEUT66}{Cela ne mérite même pas de réponse.}
{1111}{lieut45m}{Hmm, j'avoue que tu m'impressionnes. Mes espions m'avaient annoncé quelqu'un d'intelligent, mais ils semblent avoir sous-estimé tes talents. Gardes, capturez-le !}
{1112}{lieut39f}{Quelle volonté. Mes compliments. Gardes, emmenez-la et préparez-la à l'immersion. Elle parlera quand elle sera des nôtres.}
{1113}{lieut39m}{Quelle volonté. Mes compliments. Gardes, ramenez-le dans sa cellule et préparez-le à l'immersion. Il parlera quand il sera des nôtres.}
