{100}{}{Tu vois le Dr Solone, M.D.}
{101}{}{Tu vois la Nurse Marney.}
{102}{}{Tu vois un médecin.}
{103}{}{Tu vois une infirmière.}
{104}{}{Bienvenue. Comment pourrais-je vous aider aujourd'hui ?}
{105}{}{Hurrgh.}
{106}{}{je suis blessé. Pouvez-vous me soigner ?}
{107}{}{Pouvez-vous m'apprendre des choses en médecine ?}
{108}{}{Oui, je vois que vous souffrez de quelques dommages. Les soins vont prendre un certain temps. Voulez-vous que j'essaie de soigner vos blessures ?}
{109}{}{Uh huh.}
{110}{}{Nuh uh.}
{111}{}{Oui, s'il vous plaît.}
{112}{}{Non, merci.}
{113}{}{Et voilà. Vous devriez être entièrement rétabli. Soyez plus prudent dehors s'il vous plaît.}
{114}{}{Vous êtes bon pour ça. Pouvez-vous m'apprendre sur les soins de traumatisme ?}
{115}{}{Ok. Merci.}
{116}{}{Je peux vous enseigner un peu. Mais il faudra plusieurs heures. Etes-vous prêt à rester ?}
{117}{}{Oui.}
{118}{}{Désolé, je suis trop occupé.}
{119}{}{Vous êtes un très bon élève. J'espère que vous resterez à nos côtés. Bonne journée.}
{120}{}{Comme vous voudrez. Bonne chance là-bas.}
{121}{}{Je peux vous enseigner un peu, mais pas beaucoup. Il faudra un certain temps. Etes-vous prêt à rester ?}
{122}{}{Oui.}
{123}{}{Je suis désolé, mais je n'ai pas assez de temps.}
{124}{}{Vous êtes un excellent étudiant. Bonne chance à vous.}
{125}{}{Rien de plus pour le moment. Merci beaucoup.}
