{100}{}{off}
{101}{}{off}
{102}{}{on}
{103}{}{off}
{104}{}{Temps restant :  }
{105}{}{ secondes.}
{106}{}{Là, c'est la mort assurée.}
{107}{}{on}
{108}{}{Temps restant :  }
{109}{}{ secondes.}
{110}{}{Là, c'est la mort assurée.}
{111}{}{Temps restant :  }
{112}{}{ secondes.}
{113}{}{Là, c'est la mort assurée.}
