{100}{}{Voici Michael.}
{101}{}{Eh bien, je suppose que c'était ça le problème. Tu devrais consulter le Médecin, elle est au deuxième étage.}
{102}{}{Tu m'as l'air d'aller bien.}
{103}{}{Nous ne sommes que trois à avoir accès à la réserve, mon petit gars. Si tu veux quelque chose, adresse-toi à moi.}
{104}{}{Nous ne sommes que trois à avoir accès à la réserve, ma petite demoiselle. Si tu veux quelque chose, adresse-toi à moi.}
{105}{}{Tu as entendu ? Je t'ai dit que l'accès à la réserve était limité.}
{106}{}{Bonjour, Frère. Que puis-je pour toi ?}
{107}{}{Excuse-moi de te demander ça, mais que fais-tu pour notre Confrérie ?}
{108}{}{Que fais-tu ici ?}
{109}{}{Mes blessures me font mal. Peux-tu me soigner ?}
{110}{}{Urak Chufar !}
{111}{}{Désolé mais je ne comprends pas ce que tu veux. Si tu veux quelque chose, tu dois te procurer une autorisation.}
{112}{}{Taga ma.}
{113}{}{Caroo !}
{114}{}{Je ne te comprends toujours pas. Tu devrais peut-être aller consulter le Médecin. Elle est au deuxième étage.}
{115}{}{Tu devrais consulter le Médecin. Elle est au deuxième étage.}
{116}{}{Oh, il n'y a rien de plus glorieux que nos Paladins. Je m'occupe de la réserve, je vérifie l'accès au matériel.}
{117}{}{Je viens de la part de... Bob. Il voulait que je lui rapporte... cette nouvelle arme ultra-sophistiquée. Il a dit qu'il la voulait tout de suite.}
{118}{}{Je voudrais vérifier quelque chose. Qu'est-ce que je dois faire ?}
{119}{}{Oh, c'est bien. Au revoir.}
{120}{}{[Il ne croit pas à ton mensonge.] Bob ? Bob qui ? De quoi parles-tu ? Quelle nouvelle arme ultra-sophistiquée ? Il me faut plus de détails que ça et tu dois dire à ton monsieur 'je-ne-sais-plus-qui' de me fournir une autorisation. Je ne peux rien te donner sans autorisation.}
{121}{}{[Il croit à ton mensonge] Oh, tu veux dire le pistolet laser ? D'accord, un instant s'il te plaît. Aucun Bob ne m'a autorisé à donner un laser à qui que ce soit. Oh, attends une seconde. J'y suis. Les filles d'en bas se croient drôles, hein ? J'espère qu'elles vont arrêter de me harceler.}
{122}{}{Eh bien, tu sais. Elles m'ont dit de ne rien te dire, mais c'est juste parce qu'elles t'aiment bien. Je crois qu'une d'elles a le béguin pour toi.}
{123}{}{Excuse-moi, je ne savais pas ce qu'elles mijotaient. Elles m'ont juste demandé de venir ici et de te dire ça.}
{124}{}{Excuse-moi. C'était une mauvaise blague. Je voulais juste plaisanter avec toi.}
{125}{}{[Il ne croit pas à ton mensonge] Tu remets ça ! Arrête de me harceler ! Elles sont vraiment cruelles ! Je n'arrive pas à croire que tu entres dans leur jeu. Nous, les hommes, on est censé se soutenir.}
{126}{}{Tu mens ! Tu es de mèche avec elles. Comment peux-tu être si vache ?}
{127}{}{[Il croit à ton mensonge] Vraiment ? Tu me fais marcher ou quoi ? Non, tu m'as l'air d'un type bien. Elles ont dû t'obliger à faire ça. Tu sais, j'ai surpris Lara en train de me regarder pendant l'entraînement. Je parie que c'est elle, n'est-ce pas ?}
{128}{}{Ouais, c'est ça. C'est elle. Ne lui dis pas que je te l'ai dit. Elle me tuerait.}
{129}{}{Non, excuse-moi. Je te faisais marcher. Personne ne m'envoie.}
{130}{}{Tu remets ça ! Arrête de me harceler ! Ah, les femmes sont si cruelles !}
{131}{}{[Il croit à ton mensonge] Vraiment ? Tu me fais marcher ou quoi ? Non, tu as l'air d'être une fille sympa. Elles ont dû t'obliger à faire ça. Tu sais, j'ai surpris Lara en train de me regarder pendant l'entraînement. Je parie que c'est elle, non ?}
{132}{}{Ouais, c'est ça. C'est elle. Ne lui dis pas que je te l'ai dit. Elle me tuerait.}
{133}{}{Non, excuse-moi. Je te faisais marcher. Personne ne m'envoie.}
{134}{}{Eh bien, je ne sais pas quoi dire. J'ai toujours eu le béguin pour elle, mais je n'ai jamais rien tenté parce que je ne savais pas si c'était réciproque. La prochaine fois que je la verrai, je crois que je le lui demanderai. J'essaierai d'être affecté à la même patrouille qu'elle et je lui ferai une surprise en l'invitant à un dîner romantique. Merci beaucoup. Cela me met du baume au coeur. Tiens, prends ça. Ca peut t'être utile. Ce sont des grenades à impulsions. Elles sont très utiles contre les robots. Avec un peu de chance, tu n'auras jamais à t'en servir. Au revoir.}
{135}{}{Ce n'est pas très gentil de ta part. Pourquoi m'avoir dit ça si ce n'était pas vrai ? Ah, les gens !}
{136}{}{Oh. Tu as un drôle de sens de l'humour. Surtout ne reviens pas me voir sans motif valable.}
{137}{}{Oh, ces filles me donnent toujours du fil à retordre. Je ne sais pas pourquoi elles continuent à faire ça. En tout cas, cette Lara est très mignonne. J'ai le béguin pour elle depuis un bout de temps. Je l'ai connue quand elle était jeune. Elle était tellement adorable. Maintenant, elle est plus âgée et elle me traite si mal... Je n'ai pourtant pas mérité ça.}
{138}{}{Eh bien, peut-être que tu lui plais. Y as-tu déjà pensé ? Peut-être qu'elle ne sait pas comment t'aborder. Tu devrais lui parler. Si elle te plaît vraiment, tu n'as rien à perdre.}
{139}{}{Peut-être que tu lui plais.}
{140}{}{Euh, ouais. D'accord. Au revoir.}
{141}{}{Tu sais, tu as raison. Qu'est-ce que j'ai à perdre ? La prochaine fois que je la verrai, je crois que je lui en parlerai. J'essaierai d'être affecté à la même patrouille qu'elle et je lui ferai une surprise en l'invitant à un dîner romantique. Merci beaucoup. Cela me met du baume au coeur. Tiens, prends ça. Ca peut t'être utile. Ce sont des amplificateurs de dextérité. Mais attention, ils peuvent créer une dépendance. Au revoir.}
{142}{}{Non, c'est invraisemblable. C'est vrai que les femmes me troublent parfois. Je suis capable de lire et de comprendre n'importe quel schéma complexe, mais quand il s'agit des femmes, je suis complètement perdu. Merci quand même.}
{143}{}{Non, c'est invraisemblable. C'est vrai que vous, les femmes, vous me troublez parfois. Je suis capable de lire et de comprendre n'importe quel schéma complexe, mais quand il s'agit des femmes, je suis complètement perdu. Merci quand même.}
{144}{}{Tu dois te procurer une autorisation spéciale. Seul le personnel autorisé peut entrer dans la réserve.}
{145}{}{Oh. D'accord, merci. A qui dois-je m'adresser alors ?}
{146}{}{J'ai une autorisation. Peux-tu consulter le terminal pour voir si elle a été transmise ?}
{147}{}{Qui peut me fournir une autorisation ?}
{148}{}{Eh bien, plusieurs personnes, en fait. Mais je crois que tu devrais t'adresser à Talus. Ou à Mathia, elle aussi devrait pouvoir t'aider.}
{149}{}{Où puis-je trouver Mathia ?}
{150}{}{Où est Talus ?}
{151}{}{D'accord, merci.}
{152}{}{Mathia est l'assistante de Maxson. Elle est officiellement l'assistante de l'Aîné, mais elle travaille avec tous les autres Anciens. Elle se trouve généralement dans les Chambres des Anciens, au quatrième étage.}
{153}{}{D'accord. Où est Talus ?}
{154}{}{D'accord. Merci. Au revoir.}
{155}{}{Il se trouve dans la salle d'entraînement à ma gauche.}
{156}{}{Génial. Maintenant, peux-tu m'indiquer où trouver Mathia ?}
{157}{}{Et Mathia ?}
{158}{}{Merci. A plus tard.}
{159}{}{Oui, dans la journée, elle se trouve généralement dans les Chambres des Anciens, au quatrième étage.}
{160}{}{Merci de ton aide.}
{161}{}{Eh bien, voilà le stimulant pour lequel tu avais une autorisation. Attention, car il provoque une dépendance si tu en utilises trop souvent. La désintoxication et la réinsertion ne sont pas très drôles, mais je pense que c'est à peu près la même chose. C'est à tes risques et périls. Puis-je autre chose pour toi ?}
{162}{}{Non, c'est tout. Merci.}
{163}{}{Oui, il me faut autre chose.}
{164}{}{Eh bien, voilà le stimulant que tu as demandé. Il est pratique. Je pense qu'il te sera très utile. Tu as besoin d'autre chose ?}
{165}{}{Non, c'est tout. Merci.}
{166}{}{Oui, il me faut autre chose.}
{167}{}{D'accord, j'en ai. On n'a jamais assez de munitions, hein ? Eh bien, voilà. Autre chose ?}
{168}{}{Non, c'est tout. Merci.}
{169}{}{Oui, il me faut autre chose.}
{170}{}{Oh, ils peuvent être très dangereux. Eloigne-toi bien lorsque tu les utilises. Voilà. Autre chose ?}
{171}{}{Non, c'est tout. Merci.}
{172}{}{Oui, il me faut autre chose.}
{173}{}{Ah, rien de tel qu'une bonne arme sur soi. Autre chose ?}
{174}{}{Non, c'est tout. Merci.}
{175}{}{Oui, il me faut autre chose.}
{176}{}{La défense est la meilleure des attaques. A moins que ce ne soit l'inverse ? Enfin, peu importe. Voilà ton armure. Prends-en bien soin. Tu n'en auras pas d'autre. Tu as besoin d'autre chose ?}
{177}{}{Non, c'est tout. Merci.}
{178}{}{Oui, il me faut autre chose.}
{179}{}{Eh bien, ceci peut être très utile entre de bonnes mains. Voilà. Autre chose ?}
{180}{}{Non, c'est tout. Merci.}
{181}{}{Oui, il me faut autre chose.}
{182}{}{Oh, autre chose ? Pardon, j'ai dû l'oublier. Fais voir.}
{183}{}{Rebonjour. Comment vas-tu aujourd'hui ? Que puis-je faire pour toi ?}
{184}{}{Veux-tu que je t'aide ? Tu as l'air de crouler sous le travail.}
{185}{}{Il me faut autre chose.}
{186}{}{Rien, au revoir.}
{187}{}{Rien du tout. Ecarte-toi de mon chemin.}
{188}{}{Ok, voyons ça.}
{189}{}{Ah, oui. Tu as une autorisation.}
{190}{}{Eh bien, Sophia a besoin de grenades à impulsions mais je n'ai pas encore eu le temps de les lui apporter. Pourrais-tu le faire pour moi ?}
{191}{}{Bien sûr. Donne-les-moi.}
{192}{}{Je n'ai malheureusement pas le temps. J'espère que tu trouveras quelqu'un d'autre.}
{193}{}{Pour qui me prends-tu, ton laquais ?}
{194}{}{Ok. Sophia est l'une des deux Scribes Assistants pour Vree. Elle est généralement à la bibliothèque, au troisième étage.}
{195}{}{Pourquoi n'as-tu pas livré les éléments que je t'avais confiés ? Sophia les attend.}
{196}{}{Excuse-moi. Peux-tu me réexpliquer où elle se trouve.}
{197}{}{Je les ai perdus. Puis-je en avoir d'autres ?}
{198}{}{Excuse-moi, je n'ai pas vu le temps passer.}
{199}{}{Ha ! Tu croyais vraiment que j'allais les livrer ? Tu es encore plus bête que je croyais !}
{200}{}{Elle se trouve généralement à la bibliothèque au troisième étage.}
{201}{}{Gardes ! Au voleur ! Montrez-lui ce que nous réservons à ceux qui trahissent la Confrérie.}
{202}{}{Gardes ! Au voleur ! Montrez-lui ce que nous réservons à ceux qui trahissent la Confrérie.}
{203}{}{Je ne parle pas aux gens comme toi.}
{204}{}{C'est une histoire vraisemblable. Je savais que je n'aurais pas dû faire confiance à quelqu'un comme toi.}
{205}{}{Je n'arrive pas à croire que tu oses encore te montrer ici. J'espère que les grenades t'ont été utiles, car tu n'obtiendras plus rien de moi dorénavant. Je me moque de savoir qui t'a donné cette autorisation.}
{206}{}{Tiens, rebonjour. Sophia dit que tu as livré les grenades. C'est très gentil de ta part. Elle travaille sur une version améliorée et elle voulait savoir si les circuits étaient compatibles.}
{207}{}{Que veux-tu ?}
{208}{}{Donne-moi juste ce dont j'ai besoin et je m'en vais.}
{209}{}{Rien.}
{210}{}{Très bien. Laisse-moi vérifier si j'ai une commande.}
{211}{}{Ok, tu as besoin de munitions, c'est ça ? Quel genre de munitions ?}
{212}{}{Je ne sais pas.}
{213}{}{Charge Creuse à Manchon 10 mm.}
{214}{}{Balles Perforants 10 mm.}
{215}{}{Charge Creuse à Manchon Magnum .44.}
{216}{}{Manchon Entièrement Métallique Magnum .44.}
{217}{}{Balles Perforantes 14 mm}
{218}{}{Manchon Entièrement Métallique .223.}
{219}{}{Charge Creuse à Manchon 5 mm.}
{220}{}{Balles Perforantes 5 mm.}
{221}{}{Cartouches de fusil de chasse.}
{222}{}{Eh bien, tu dois savoir de quelles munitions tu as besoin pour que je t'en donne. Examine l'arme en question. Lorsque tu auras la réponse, reviens me voir.}
{223}{}{Ah, un lance-roquettes... rien de tel qu'une bonne arme sur soi. Alors, autre chose ?}
{224}{}{Non, c'est tout. Merci.}
{225}{}{Oui, il me faut autre chose.}
{226}{}{Ah oui, voilà le pistolet que tu voulais. Alors, autre chose ?}
{227}{}{Non, c'est tout. Merci.}
{228}{}{Oui, il me faut autre chose.}
{229}{}{La défense est la meilleure des attaques. A moins que ce ne soit l'inverse ? Enfin, peu importe. Voilà ton armure. Prends-en bien soin. Tu n'en auras pas d'autre. Tu as besoin d'autre chose ?}
{230}{}{Non, c'est tout. Merci.}
{231}{}{Oui, il me faut autre chose.}
{232}{}{Hmmm... Une SuperArmure. Prends-en bien soin. Tu n'en auras pas d'autre. Tu as besoin d'autre chose ?}
{233}{}{Non, c'est tout. Merci.}
{234}{}{Oui, il me faut autre chose.}
{235}{}{Eh bien, ceci peut être très utile entre de bonnes mains. Voilà. Autre chose ?}
{236}{}{Non, c'est tout. Merci.}
{237}{}{Oui, il me faut autre chose.}
{240}{}{Je cherche un Motivateur Systolique.}
{241}{}{Tu as l'autorisation ?}
{242}{}{Oui. On m'envoie pour prendre un Motivateur Systolique.}
{243}{}{Non, mais je dois impérativement en avoir un.}
{244}{}{Kyle m'envoie retirer cette pièce.}
{245}{}{Non. Comment puis-je obtenir une autorisation ?}
{246}{}{Attends. (il consulte son terminal) Eh bien, je ne vois aucune demande de Motivateur Systolique. Tu dois te procurer une autorisation.}
{247}{}{Ecoute ! Je ne veux pas d'ennuis. Donne-moi cette pièce.}
{248}{}{Allez ! S'il te plaît. J'en ai vraiment besoin.}
{249}{}{Ok. Pardon de t'avoir dérangé.}
{250}{}{Quoi ? L'autorisation était censée partir hier. Ecoute, est-ce que tu peux m'aider ? Si je ne reviens pas avec cette pièce, ça va être ma fête. Je t'assure que le formulaire sera là un peu plus tard.}
{251}{}{Ok. Voilà. Mais ne dis à personne que je te l'ai donné. Rhombus me tuerait s'il apprenait que je te t'ai remis une pièce sans autorisation.}
{252}{}{Merci. Au revoir.}
{253}{}{Je te donnerais cette pièce si je le pouvais. Mais je ne peux pas. Pas sans autorisation.}
{254}{}{Tu sais Michael, tu es sans doute le gars le plus brillant que je connaisse ici. Mais je ne comprends pas pourquoi tu t'entêtes à ce point. J'ai vraiment besoin de cette pièce.}
{255}{}{Oh... Très bien. Je crois que je comprends. Mais, je ne sais pas comment faire.}
{256}{}{Donne-moi cette pièce.}
{257}{}{Sans autorisation, je ne peux pas te donner de pièces de rechange.}
{258}{}{Allez. S'il te plaît. J'ai vraiment besoin de cette pièce.}
{259}{}{Ok. Pardon de t'avoir dérangé. Au revoir.}
{260}{}{Kyle ? C'est à propos de cette vieille SuperArmure rouillée ?}
{261}{}{Oui.}
{262}{}{Non.}
{263}{}{Tu peux lui dire que tant qu'il n'aura pas redonné à cette unité sa splendeur d'antan, il n'obtiendra pas cette autorisation. Au revoir.}
{264}{}{Non. Kyle doit d'abord s'occuper de l'unité à réparer. S'il pense qu'il peut la réparer, alors il pourra faire une demande de pièces détachées. Rhombus passe les demandes en revue et détermine celles qui en valent la peine. Va le dire à Kyle. Au revoir.}
{265}{}{Au revoir.}
{266}{}{Oh... ouais. Eh bien, je viens de la part de Kyle. Peux-tu consulter ton terminal une dernière fois.}
{267}{}{Mais je viens de la part de Rhombus.}
{268}{}{Tu n'auras pas cette pièce. Point final. Je t'ai dit ce que tu devais faire et je n'ai pas l'intention de te le répéter.}
{300}{}{On dirait que Sophia t'apprécies vraiment. Elle m'a demandé de te donner ces batteries en fin de vie. On devait faire de la place dans les stocks de toute façon.}

{500}{}{[Plus]}
{501}{}{[Retour]}

# Fo1in2:
{600}{}{Calibre : 7.62mm.}