{100}{}{Voici Mike, le garde de la Vieille Ville.}
{101}{}{Ouais, qu'est-ce que tu veux ?}
{102}{}{ah...euh...um...}
{103}{}{Je ne suis pas d'ici. Dans quel quartier sommes-nous ?}
{104}{}{Sais-tu où je pourrais trouver une puce d'eau ?}
{105}{}{Um... Au revoir.}
{106}{}{Ha ! Encore un toxico. Fiche le camp !}
{107}{}{Ouais. Tu as dû te perdre. Tu risques d'avoir des ennuis dans cette partie de la ville. Tu es dans le quartier Est que certains appellent aussi la Vieille Ville. La Décharge des Décharges.}
{108}{}{Sais-tu où je pourrais trouver une puce d'eau ?}
{109}{}{Merci du renseignement. Au revoir.}
{110}{}{Une Puce d'Eau ? Tu te sens bien ? Tu as pris des stimulants ou quoi ? Une puce faite d'eau ?}
{111}{}{Tu te fiches de moi, crapule. Je vais m'occuper de toi, tu vas voir.}
{112}{}{Je ne suis pas d'ici. Dans quel quartier sommes-nous ?}
{113}{}{Laisse tomber. Salut.}
