{100}{}{Voici un garde.}
{101}{}{Qu'est-ce que tu fous ici ?}
{102}{}{Beuf ?}
{103}{}{Oh rien, je jetais un coup d'oeil.}
{104}{}{Je veux acheter des armes.}
{105}{}{}
{106}{}{}
{107}{}{J'ai pas le temps de plaisanter. Tu files ou je te troue la cervelle !}
{108}{}{On n'aime pas les fouineurs. Disparais immédiatement et je t'épargne.}
{109}{}{}
{110}{}{}
{111}{}{T'as la même odeur que les brahmines mais pas leur intelligence.}
{112}{}{}
{113}{}{Ah, très bien. Les clients sont toujours les bienvenus. Entre mais garde tes armes au chaud. Adresse-toi à Zack, il te fournira tout ce que tu veux.}
{114}{}{}
{115}{}{Faut que je parle à ton patron. C'est très important.}
{116}{}{Oh, d'accord. Gabriel va te parler. Entre.}
{117}{}{Ouais, je me souviens de toi. Entre.}
{118}{}{Faut que je parle à Gabriel. C'est très important.}
{119}{}{Je veux acheter des armes à Zack.}

# Fo1in2:
{200}{}{Va voir Zack, il peut t'avoir tout ce dont tu as besoin.}
