{100}{}{Devant toi se trouve un ordinateur Mach IV.}
{101}{}{Le système semble en cours de réinitialisation.}
{102}{}{Le système semble s'être verrouillé.}
{103}{}{L'écran scintille.}
{104}{}{Sur l'écran apparaissent des formes aux couleurs bizarres.}
{105}{}{Sur l'écran de l'ordinateur, on voit des petites bombes vertes qui s'écrasent sans fin sur le sol.}
{106}{}{Tu n'arrives pas à contourner le mot de passe de l'écran.}
{107}{}{Tu accèdes à des messages électroniques. Le plus intéressant est une requête du Lieutenant : "...d'autres sujets humains à immerger. Envoyez-les immédiatement à la Base militaire."}
