{100}{}{Voici Morpheus.}
{101}{MORP02}{Je ne me souviens pas avoir invité quelqu'un dans mes appartements. Qu'est-ce qui me vaut ta présence ?}
{102}{}{Oh, pardon. J'ai dû m'égarer.}
{103}{}{Parce que j'ai une affaire géniale à te proposer...}
{104}{}{Je m'appelle }
{105}{}{. Et toi ?}
{106}{}{C'est un des Frères qui m'envoie.}
{107}{}{Maman ?}
{108}{MORP02A}{Non. Je suis le Père LaMort...}
{109}{MORP03}{Eh bien, mon enfant, il est fort dangereux d'explorer des lieux étrangers. Où te rendais-tu pour atterrir ainsi dans mes appartements privés ?}
{110}{}{Je viens d'arriver, et je cherchais les toilettes. Un des Grand Prêtres m'a indiqué ce chemin.}
{111}{}{Je cherchais le confessionnal. Un des Grand Prêtres m'a indiqué cette direction. Pardonne-moi.}
{112}{}{Euh, j'ai pas vraiment perdu mon chemin.}
{113}{}{Je venais ici pour te tuer.}
{114}{}{Je sais plus. Je m'en vais.}
{115}{MORP04}{Ahh...Hé, hé, hé ! Ce sera Lasher. Il adore mettre les fidèles dans l'embarras. C'est ton jour de chance, enfant sans malice. Va, je ne te veux point de mal.}
{116}{MORP04A}{Tu as eu un avertissement. Gardes !}
{117}{MORP05A}{Misérables mensonges ! Dis-moi la vraie raison de cette intrusion... avant que je ne te fasse écorcher sur le champ !}
{118}{}{Non, juré ! J'ai dû m'égarer !}
{119}{}{D'accord, j'avoue. Je suis ici pour te proposer un marché.}
{120}{}{Oh, simple curiosité...}
{121}{MORP06}{Serait-ce les Disciples qui t'envoient m'espionner ? Peut-être me trompé-je, mais je ne prends pas de risques inutiles. Tu dois mourir.}
{122}{MORP07}{Que peux-tu donc avoir à m'offrir ?}
{123}{}{Je viens d'un Abri. Tu sais ce que c'est, pas vrai ?}
{124}{}{Je te propose des infos sur tes ennemis.}
{125}{}{C'est le Maître qui m'envoie t'espionner.}
{126}{morp08}{Poursuis.}
{127}{}{Je voudrais donner à ton maître des infos sur mon Abri.}
{128}{}{J'ai pour le Maître des infos sur mon Abri.}
{129}{}{Doucement. Qu'est-ce que j'aurai en échange de mes infos ?}
{130}{MORP09}{Je n'ai pas de maître, imbécile !}
{131}{}{Alors, qu'est-ce que t'appelles le Maître ? T'es pas sous ses ordres ?}
{132}{}{Tu m'as pourtant bien l'air sous les ordres du Maître.}
{133}{}{Holà. Doucement les insultes !!}
{134}{}{On dirait que j'ai touché un point sensible.}
{135}{MORP10}{Personne ne me commande. Lui et moi sommes... partenaires.}
{136}{}{Tu parles ! T'es un toutou en laisse !}
{137}{}{Peu importe. J'ai des informations sur un Abri. Ca l'intéresserait ?}
{138}{}{Il donne des ordres, pas vrai ? Et t'obéis au doigt et à l'œil...}
{139}{MORP11}{Je ne tolère pas les insultes. Gardes !}
{140}{MORP12}{Très bien. Je te conduis au Maître. Mais si tu mens, il le saura.}
{141}{}{D'accord, ça me va.}
{142}{}{Tu me conduis nulle part !}
{143}{MORP13}{Ca ne te regarde pas ! Mais si tu viens vraiment d'un Abri, le Maître le saura. Gardes !}
{144}{MORP14}{Tu peux avoir la vie sauve. Mais, dis-moi ce que tu sais.}
{145}{}{Je viens d'un Abri, et je suis d'accord pour indiquer l'emplacement au Maître.}
{146}{}{Sinon ?}
{147}{}{Je te dirai rien.}
{148}{MORP15}{Non ? Alors, il va falloir que je t'extorque moi-même ces informations. Gardes !}
{149}{MORP16}{Et qui seraient donc mes ennemis ?}
{150}{}{Et bien, d'abord, les Disciples.}
{151}{}{J'ai bien l'impression que c'est tout le monde.}
{152}{MORP17}{Dis-moi ce que tu sais.}
{153}{}{Euh, non. Conduis-moi à ton Maître. A lui, je parlerai.}
{154}{}{Oh, disons que je sais un truc qui vous aiderait à les combattre.}
{155}{MORP18}{Tu me donnes les informations ou tu meurs d'une mort... très, très... lente.}
{156}{}{Tu crois que le Maître serait content si tu tuais l'habitant d'un Abri ?}
{157}{}{Je ne parlerai qu'au Maître.}
{158}{MORP19}{Ah...Alors c'est toi l'habitant d'Abri dont on m'a parlé. Ca t'étonne ? J'ai mes sources. Bon, je vais t'offrir au Maître. Il sera ravi.}
{159}{}{Et si on t'emmenait dans un sac, plutôt ?}
{160}{}{Et moi donc.}
{161}{MORP20}{Tu espionnes ? Très imprudent de ta part. Quand je t'aurai réglé ton compte, tu auras du mal à lui faire ton rapport, non ?}
{162}{MORP21}{Tu mens mal ! Bon, dis-moi ce que tu veux.}
{163}{}{Je viens d'un Abri. Tu sais ce que c'est, pas vrai ?}
{164}{}{Je te propose des infos sur tes ennemis.}
{165}{MORP23}{Tiens donc ! Bon, dis-moi ce qui t'amène.}
{166}{}{Je viens d'un Abri, et je suis d'accord pour indiquer l'emplacement au Maître.}
{167}{}{Je te propose des infos sur tes ennemis.}
{168}{}{T'es pas très impressionnant.}
{169}{}{Je ne te dirai rien.}
{170}{MORP24}{Oh, vraiment ? Et comment comptes-tu t'y prendre ? Avec ton ingéniosité et ta langue de vipère ?}
{171}{}{Non, avec ça...}
{172}{}{Ce serait trop facile. Pour toi, je préfère une solution plus subtile.}
{173}{}{Une balle dans la tête devrait suffire...}
{174}{MORP26}{Bon, je t'offre un marché. Tu me dis ce que tu sais, et tu sors d'ici en entier.}
{175}{}{Je viens d'un Abri, et je suis d'accord pour indiquer l'emplacement au Maître.}
{176}{}{Je te propose des infos sur tes ennemis.}
{177}{}{T'es pas très impressionnant.}
{178}{}{Je ne te dirai rien.}
{179}{MORP27}{C'est moi qui pose les questions ! Bon, dis-moi ce que tu fais ici.}
{180}{}{J'ai dû me perdre.}
{181}{}{Je suis là pour te faire une proposition.}
{182}{morp28}{Ah oui ?}
{183}{}{Bonjour ! Je suis une nouvelle recrue chez les Enfants et je me demandais si je pouvais te poser quelques questions ?}
{184}{}{T'occupe.}
{185}{}{Hein }
{186}{morp29}{Bien sûr, mon enfant.}
{187}{}{Merci...}
{188}{}{T'occupe.}
{189}{}{Quelles sont les intentions des Enfants ?}
{190}{}{J'ai changé d'avis. Plus de questions.}
{191}{}{Qu'est-ce t'en dis si je t'annonce que je viens d'un Abri ?}
{192}{MORP31}{Nos intentions ? Nous sommes les messagers du changement, mon enfant. Nous suivons le Maître dans sa quête infinie pour guérir la terre et ses habitants.}
{193}{}{Vraiment ? C'est quoi, au juste, le changement que vous enseignez ?}
{194}{}{Quelle sorte de guérison ?}
{195}{MORP32}{Nous savons qu'il existe un niveau supérieur, un sommet glorieux que l'humanité doit s'efforcer d'atteindre. Nous voulons trouver une vie meilleure, plus satisfaisante que celle-ci, pourrie par la misère et les querelles.}
{196}{}{Non, dis, tu blagues ?}
{197}{}{Et ce niveau supérieur, vous l'avez trouvé ?}
{198}{MORP33}{[En colère] Ahhh, toi ! ... [Calmement] Le pardon te soit accordé. Tout le monde ne voit point la lumière. Mais, dis-moi mon enfant, pourquoi nous as-tu rejoints ?}
{199}{}{Je voulais savoir si c'était la fumisterie dont on m'a parlé. Maintenant, je sais.}
{200}{}{Pardon. J'ai dû faire erreur...}
{201}{morp34}{Tu ne sais rien.}
{202}{MORP35}{Oui, c'est vrai, mais le pardon te soit accordé. Bon, si tu n'as plus de questions, des tâches m'attendent.}
{203}{}{Euh, si justement, j'en ai d'autres...}
{204}{}{Non, merci.}
{205}{MORP36}{Bien sûr, je t'en prie. Poursuis.}
{206}{MORP37}{Oui, mais que le pardon te soit... accordé. Va en paix, mon enfant.}
{207}{MORP38}{Non, mais à force de foi et d'espoir, nous le trouverons. Mais tu devrais savoir tout ceci, mon enfant.}
{208}{}{Je sais, mais juste encore quelques questions, s'il te plaît.}
{209}{}{Je sais. Au revoir.}
{210}{MORP39}{D'abord, nous guérissons le corps. Tu as certainement vu nos hôpitaux. Ensuite, nous offrons l'espoir et la guérison de l'esprit.}
{211}{}{Waouh. J'ai failli y croire. Bref, la bonté même !}
{212}{}{Où il sont, ces hôpitaux ?}
{213}{MORP40}{Nos glorieux efforts viennent d'atteindre le Sanctuaire, et, bien sûr, le Centre resplendit de notre oeuvre. Mais j'ai l'impression que ta curiosité n'est pas rassasiée.}
{214}{MORP41}{Nous vivons des jours merveilleux ! Dépôtville rejoint maintenant le Sanctuaire et le Centre dans notre quête pour sauver l'âme et le corps. D'autres questions, mon enfant ?}
{215}{}{En fait...}
{216}{}{Non rien. Faut que j'y aille.}
{217}{MORP42}{La vision des Enfants s'étend maintenant au Sanctuaire, au Centre, à Dépôtville, et elle vient effleurer les Sables Ombragés. Pourquoi ces questions ?}
{218}{}{Simple curiosité. Je peux encore te poser quelques questions ?}
{219}{}{Pour rien. Faut que j'y aille.}
{220}{MORP42A}{Tu es quoi ?}
{221}{}{T'as entendu. Conduis-moi au Maître, immédiatement !}
{222}{MORP42B}{Euh, oui. Bon. Suis-moi.}
{223}{MORP42C}{Oh, mon enfant, tout cela n'a ni queue ni tête. Demande à l'un de nos médecins de t'aider.}
{224}{MORP45}{Mon enfant, parle à Lasher. Il t'aidera.}
{225}{MORP46}{J'ai dit...}
{226}{MORP47}{Tu entends ? J'ai dit...}
{227}{MORP48}{Je ne me répéterai pas !}
{228}{MORP49}{Je ne vais pas le répéter !}
{229}{MORP50}{Les Ténébreux sont venus il y a quelque temps. Ce sont peut-être d'affreux mutants, mais... extrêmement loyaux envers les Enfants. Comme nous tous, d'ailleurs.}
{230}{MORP51}{C'est lui qui m'a apporté la vision de l'Unité et c'est lui qui apportera la paix sur cette région troublée.}
{231}{MORP52}{Mon enfant, tu devrais connaître l'Auditorium. C'est là que je prononce mes sermons.}
{232}{MORP53}{Ne t'en préoccupe point. Seuls les Grands Prêtres peuvent y entrer.}
{233}{MORP54}{Je ne suis qu'un humble serviteur de l'Unité.}
{234}{MORP55}{Nous sommes les grands prêtres du Dieu des Ténèbres. Treize d'entre nous ont l'honneur de transmettre ses divines paroles au reste des Enfants.}
{235}{MORP56}{Je vois pas du tout de quoi tu parles.}
{236}{MORP57}{Les hôpitaux des Enfants de la Cathédrale procurent dans toute cette contrée ravagée les meilleurs des soins. Des soins vitaux à l'Unité.}
{237}{MORP58}{L'Unité, c'est notre quête pour un niveau de vie supérieur et pour l'union avec l'homme.}
{238}{MORP59}{Un autre Grand Prêtre. Il consacre beaucoup de son temps à l'étude.}
{239}{MORP60}{Mon cœur saigne pour eux. Fourvoyés. Ils ignorent que leurs efforts n'apporteront que douleur et misère à leurs semblables.}
{240}{MORP61}{Nicole, la malheureuse, l'égarée, est le chef des Disciples de Apocalypse.}
{241}{MORP62}{Le Sanctuaire est la ville au Nord-Est d'ici.}
{242}{MORP63}{C'est sans importance.}
{243}{MORP64}{Ce n'est rien. Passe à une autre question.}
{244}{morp65}{Rien d'important.}
{245}{}{Maître, je pense que tu vas apprécier ce...}
{500}{}{ points d'expérience pour la destruction du chef des Enfants de la Cathédrale.}


# Morpheus Tell-Me-Abouts generic responses
{980}{MORP63}{Sans importance. }
{981}{MORP64}{Ce n'est rien. Passe à une autre question. }
{982}{morp65}{Rien d'important.}


#
# Morpheus Tell-Me-Abouts
#


{1000}{}{Ténébreux}
{1001}{}{Maître}
{1002}{}{Auditorium}
{1003}{}{Sanctuaire}
{1004}{}{Morpheus}
{1005}{}{Ordre}
{1006}{}{Caravanes}
{1007}{}{Hôpitaux}
{1008}{}{Unité}
{1009}{}{Lasher}
{1010}{}{Disciples}
{1011}{}{Nicole}
{1012}{}{Sanctuaire}
{1013}{}{Apocalypse}
{1014}{}{Mutants}
{1015}{}{La Flamme sacrée}
{1016}{}{Enfants}
{1017}{}{Base}
{1018}{}{Puce}


{1100}{MORP50}{Les Ténébreux sont venus, il y a quelque temps. Ce sont peut-être d'affreux mutants, mais... extrêmement loyaux envers les Enfants. Comme nous tous, d'ailleurs.}
{1101}{MORP51}{C'est lui qui m'a apporté la vision de l'Unité et c'est lui qui apportera la paix sur cette région troublée.}
{1102}{MORP52}{Mon enfant, tu devrais connaître l'Auditorium. C'est là que je prononce mes sermons.}
{1103}{MORP53}{Ne t'en préoccupe point. Seuls les Grands Prêtres peuvent y entrer. }
{1104}{MORP54}{Je ne suis qu'un humble serviteur de l'Unité. }
{1105}{MORP55}{Nous sommes les grands prêtres du Dieu des Ténèbres. Treize d'entre nous ont l'honneur de transmettre ses divines paroles au reste des Enfants. }
{1106}{MORP56}{Je vois pas du tout de quoi tu parles. }
{1107}{MORP57}{Les hôpitaux des Enfants de la Cathédrale procurent dans toute cette contrée ravagée les meilleurs des soins. Des soins vitaux à l'Unité.}
{1108}{MORP58}{L'Unité, c'est notre quête pour un niveau de vie supérieur et pour l'union avec l'homme. }
{1109}{MORP59}{Un autre Grand Prêtre. Il consacre beaucoup de son temps à l'étude. }
{1110}{MORP60}{Mon cœur saigne pour eux. Fourvoyés. Ils ignorent que leurs efforts n'apporteront que douleur et misère à leurs semblables.}
{1111}{MORP61}{Nicole est la leader troublée des Disciples de Apocalypse.}
{1112}{MORP62}{Le Sanctuaire est la ville au Nord-Est d'ici.}
{1113}{MORP60}{Mon coeur saigne pour eux. Ils se sont fourvoyés et ignorent que leurs efforts n'apporteront que douleur et misère à leurs semblables.}
{1114}{MORP50}{Les Ténébreux sont venus, il y a quelque temps. Ce sont peut-être d'affreux mutants, mais... extrêmement loyaux envers les Enfants. Comme nous tous, d'ailleurs.}
{1115}{morp65}{Pas de quoi s’inquiéter.}
{1116}{morp65}{Pas de quoi s’inquiéter.}
{1117}{morp65}{Pas de quoi s’inquiéter.}
{1118}{morp65}{Pas de quoi s’inquiéter.}
