{100}{}{Tu vois une porte à sas.}
{101}{}{La porte est verrouillée par une fermeture électronique.}
{102}{}{La porte n'est pas verrouillée.}
{103}{}{Tu réussis à court-circuiter la fermeture électronique.}
{104}{}{Tu ne réussis pas à neutraliser la fermeture électronique.}
