{100}{}{Voici une tête nucléaire.}
{101}{}{Des câbles relient l'ordinateur d'accès à la tête nucléaire qui se trouve derrière.}
{102}{}{Tu as amorcé la tête nucléaire. Une minuterie réglée à quatre minutes s'est déclenchée.}
{103}{}{Tu as désamorcé la tête nucléaire.}
{104}{}{BOOOOOOOOOM ! [Tu as déclenché l'arme nucléaire !]}
{105}{}{On dirait que ça ne marche pas.}
{106}{}{Le compte à rebours continue... peut-être devrais-tu couper ce fil rouge.}
{107}{}{Peut-être dois-tu aussi utiliser la clé.}
{108}{}{C'est une tête nucléaire. Elle est sous contrôle de l'ordinateur connecté par les câbles.}
{109}{}{Il n'y a rien à réparer sur cette tête nucléaire.}
{110}{}{Il n'y a rien à crocheter sur cette tête nucléaire.}
{111}{}{C'est un très gros piège impossible à désamorcer ou à amorcer d'ici.}
