{100}{}{La pompe à eau est réparée et fonctionne bien.}
{101}{}{La pompe à eau ne fonctionne pas parce qu'une pompe à vide est cassée.}
{102}{}{La pompe à eau ne fonctionne pas.}
{103}{}{Une pièce de mécanique.}
{104}{}{Cette pompe à eau ne fonctionne pas parce qu'une pompe à vide est cassée.}
{105}{}{Peut-être faut-il un nouveau fusible.}
{106}{}{La pompe à eau ne fonctionne pas.}
{107}{}{Impossible de réparer la pompe à eau sans pompe à vide de rechange.}
{108}{}{Tu n'as pas réussi à réparer la pompe à eau. Peut-être faut-il un nouveau fusible.}
{109}{}{Tu n'as pas réussi à réparer la pompe à eau.}
{110}{}{Cette pompe à eau ne fonctionne pas parce qu'une pompe à vide est cassée.}
{111}{}{Cette pompe à eau a peut-être besoin d'un nouveau fusible.}
{112}{}{La pompe à eau ne fonctionne pas.}
{113}{}{Tu ne remarques rien d'anormal.}
{114}{}{Tu installes les pièces manquantes et la lourde pompe se remet péniblement en marche.}
{115}{}{Tu réussis quand même à détruire les pièces mais tu te coupes la main et prends 1 point de dégât.}
{116}{}{Tu as du mal à faire fonctionner ces pièces.}
{117}{}{Cet objet est inutilisable sur la pompe.}
{118}{}{ points d'expérience pour avoir réparé la pompe.}
