{100}{}{Voici Orfeo, Membre Senior des Enfants de la Cathédrale.}
{101}{}{Ah. Une nouvelle recrue. Bienvenue.}
{102}{}{Moi, tuer !!}
{103}{}{Je ne suis pas une recrue !}
{104}{}{Merci, Frère.}
{105}{}{Dans ce cas, nous allons très vite remédier à ce problème.}
{106}{}{Nous devons d'abord te débarrasser des impuretés du désert. Viens.}
{107}{}{Nous allons te purifier !}
