{100}{}{Paladin}
{101}{}{Salut, Initié.}
{102}{}{Si tu as besoin de quelque chose, adresse-toi à Vree.}
{103}{}{Vree est juste là-bas si tu veux parler à quelqu'un.}
{104}{}{Faut que je trouve du temps entre les patrouilles et l'entraînement pour étudier. Je commence un peu à me rouiller.}
{105}{}{Ton esprit et ton corps doivent toujours être au top, Initié.}
{106}{}{C'est nous, les Scribes, qui concevons tous les équipements, les armes et les accessoires. C'est passionnant.}
{107}{}{Mon gars, être Paladin, c'est pas simplement combattre.}
{108}{}{Ma fille, être Paladin, c'est pas simplement combattre.}
