{100}{}{Voici un garde Paladin.}
{101}{}{Pssst, y'a pas quelques affaires juteuses ?}
{102}{}{Je regrette, je suis en service. Impossible de parler.}
{103}{}{Quelle belle journée ! J'espère qu'on n'aura pas d'attaques.}
{104}{}{Salut.}
{105}{}{Certains des marchands des Caravanes sont un peu bizarres.}
{106}{}{Salut beauté.}
{107}{}{Salut à toi, Initié.}
{108}{}{Si t'as des questions sur notre ordre, adresse-toi à Cabbot, là-bas près de la porte.}
{109}{}{C'est à Cabbot que tu dois t'adresser. C'est le p'tit jeune près de la porte.}
{110}{}{Si t'es là pour faire du commerce, c'est pas à moi qu'il faut s'adresser.}
{111}{}{Quoi ?}
{112}{}{Me dérange pas, tête de piaf.}
{113}{}{J'ai l'air d'être intéressé par tes offres ?}
{114}{}{Hum. Quel culot !}
{115}{}{Je suis de garde, me dérange pas !}
{116}{}{Initié, tu ferais mieux de pas nous déranger quand on est de garde.}
{117}{}{Si t'as des questions sur notre ordre, adresse-toi à Cabbot, là-bas près de la porte.}
{118}{}{Initié, t'as rien d'utile à faire ?}
{119}{}{Je crois que t'as rien à faire ici.}
