{100}{}{Sors d'ici !}
{101}{}{C'est vrai, les vilaines choses qu'on dit sur ton compte ?}
{102}{}{Bonjour.}
{103}{}{C'est chez moi, tu veux rester un peu ?}
{104}{}{Hum, t'as l'air sexy...}
{105}{}{J'espère que tu vas pas me jeter dehors.}
{106}{}{Non.}
{107}{}{Drôle de manière d'entamer la conversation !}
{108}{}{Hum.}
{109}{}{Oh, si tu veux rester un moment, te gêne pas. Je pense qu'on risque rien ici.}
{110}{}{Ah, faut être prudent de nos jours. J'espère que tu vis mieux que moi.}
{111}{}{Damne, c'est vrai. Avec ce qu'est arrivé à mes amis, faut que j'protège mon territoire. Mais j'espère que tu vas pas me tuer.}
{112}{}{Non, je te ferai pas de mal. Pas trop.}
{113}{}{Pourquoi tu dis ça ?}
{114}{}{Ah !}
{115}{}{Pour rien, je t'assure.}
# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
{116}{}{Ces soit-disant "guérisseurs", ils voulaient l'endroit de mon ami et ils l'ont pris. J'sais point ce qu'est arrivé à mes amis.}
{117}{}{ Et Killian il a pas le temps de m'aider.}
{118}{}{ Killian il est trop occupé avec les histoires de Gizmo pour m'aider.}
{119}{}{ Gizmo m'a rigolé au nez quand je l'ai prié de m'aider.}
{120}{}{ Y'a personne dans le coin pour m'aider.}
{121}{}{T'es en sécurité ?}
{122}{}{Ah, c'est désolant.}
{123}{}{Ah, j'espère bien !}
{124}{}{S'il te plaît, m'laisse pas tout seul !}
