{100}{}{Tu vois un paysan.}
{101}{}{Merci de t'être débarassé de ces voyous, mais sans générateur, notre vie risque de devenir encore plus misérable.}
{102}{}{J'ai froid.}
{103}{}{J'ai besoin de lumière.}
{104}{}{Je devrais te remercier... Je crois...}
{105}{}{Si tu ne tue pas tout les gangs, ils vont se venger sur nous!}
{106}{}{Tu as commencé ce massacre. Termine-le.}
{107}{}{Je t'aiderais bien, mais mon genou me fait souffrir.}
{108}{}{Tout est de ta faute.}
{109}{}{La violence ne résout rien.}
{110}{}{Je pensais que tu étais un type bien.}
{111}{}{Encore un Crypt. J'imagine que tu vas aussi t'en prendre a moi.}
{112}{}{Je me tiendrais a carreaux.}
{113}{}{S'il te plait. Laisse-moi tranquille.}
{114}{}{J'ai apris que tu avais rejoins les Fools.}
{115}{}{Mais quel idiot ! Oups, ce n'est pas ce que je voulais dire...}
{116}{}{Je me tiendrais à carreaux.}
{117}{}{S'il te plait. Laisse-moi tranquille.}
{118}{}{Je te promet de rire à tes blagues !}
{119}{}{J'ai faim.}
{120}{}{Où sont parti les gens bien ?}
{121}{}{Phil a-t-il toujours des ennuis avec ce chien ?}
{122}{}{Scrapheap va finir par exploser si ces bandits continuent dans cette direction.}
{123}{}{Les nuits sont fraîches, sans chauffage.}
{124}{}{Les Brahmines sentent sacrément mauvais en été...}
{125}{}{Électricité, électricité.}
{126}{}{Salut.}
{127}{}{[Fait]}