{100}{}{Voici un prisonnier Goule.}
{101}{}{Qu...qque veux-tu ?}
{102}{}{Euh, rien.}
{103}{}{Ben.}
{104}{}{Je suis là pour te délivrer.}
{105}{}{T'espère quoi ?}
{106}{}{Eh, je m'en fous, fais-moi juste sortir d'ici !}
{107}{}{Super ! Vas-y !}
{108}{}{J'ai volé de l'eau. Eh, j'avais soif ! J'ai fait de mal à personne !}
{109}{}{T'as pris plus que ta part.}
{110}{}{Ah, c'est rien. Je vais te faire sortir.}
{111}{}{Sans cette eau, c'était la mort. C'était juste une tasse. Juste assez pour vivre. Fais-moi sortir ! Je vais devenir dingue.}
{112}{}{D'accord, un instant...}
{113}{}{Je pense que je vais laisser la loi s'occuper de ton cas.}
{114}{}{Je t'en prie, fais-moi sortir.}
{115}{}{Merci de m'avoir fait sortir.}
{116}{}{Y'a pas d'quoi.}
{117}{}{D'où vient l'eau ?}
{118}{}{Ouais.}
{119}{}{Ils la pompent des sources souterraines. Y'a une bouche d'égout dans la cellule d'à côté qui mène à l'ancien abri. C'est de là que vient l'eau. S'il y avait pas ceux d'en dessous, tout irait mieux pour nous.}
{120}{}{Que veux-tu dire ?}
{121}{}{Merci.}
{122}{}{C'est parfois difficile de bien faire marcher la vieille technique. Les Rayonnants nous frappent dès qu'on descend. Nous, on les laisse tranquilles. Et les grands mutants ont pas l'air de se faire de bile.}
{123}{}{Bonne chance. Salut.}
{124}{}{Tu as gagné }
{125}{}{ points d'expérience pour avoir libéré le prisonnier Goule.}
{126}{}{Encore merci.}
