{100}{}{radio}
{101}{}{[On entend un bruit aigu de parasites, puis une voix grave.] Commandement à patrouille, commandement à patrouille. Quel est votre statut ? Terminé.}
{102}{}{Bouh !}

##103 - Uh, nothing is wrong here. We're fine, uh, how are you ?

{103}{}{Euuh, rien d'anormal ici. Tout va bien. On a eu un tir accidentel. Mais personne n'est blessé. Euh, et vous ?}
{104}{}{Commandement, nous sommes attaqués par un important groupe d'humains armés. Demandons aide. Terminé.}
{105}{}{Au secours ! Des attaquants inconnus ! Lourds dégâts ! Coordonnées : 10... Ahhh !}
{106}{}{Compris, patrouille. Nous envoyons de l'aide immédiatement. Terminé.}
{107}{}{Qui est là ? Quel est votre objectif ?}
{108}{}{Mon objectif est de te faire fermer la gueule.}
{109}{}{Je suis, euh, laisse tomber. De toute façon, je vais tous vous tuer sans tarder.}
{110}{}{C'est, hum, Fred. Mon objectif est de patrouiller. Heuu... je crois que je suis un peu, euh, étourdi après... cette chute.}
{111}{}{Compris, patrouille. Quelles sont vos coordonnées ?}
{112}{}{224 sur 104.}
{113}{}{Quatre miles, Sud - Sud-Ouest.}
{114}{}{Secteur Gamma, à Omicron-Delta-Beta.}
{115}{}{Compris, patrouille. Commandement, terminé.}
{116}{}{Compris, patrouille. Nous envoyons des renforts.}
{117}{}{Ah, ça explique tout. Nous envoyons de l'aide immédiatement.}
{118}{}{Roger, patrouille. Nous envoyons de l'aide immédiatement ! Tenez bon !}
{119}{}{On n'entend que des parasites sur la radio.}
{120}{}{Ca bavarde sur la radio. Tu écoutes un instant mais tu ne découvres rien d'important.}
{121}{}{Une lumière rouge clignote sur la radio. Un son aigu couvre la voix qui parle.}
{122}{}{On dirait des messages cryptés.}
{123}{}{Tu envoies le code de commande pour modifier les paramètres de champ de force.}

##124 - There is only quiet static on the radio [channel].

{124}{}{Ca bavarde sur la radio. Tu écoutes un instant mais tu ne découvres rien d'important.}
{125}{}{La radio ne fonctionne pas.}
{126}{}{Cette radio est en parfait état. La cause du problème doit être externe.}
{127}{}{On n'entend rien d'autre sur la radio que le bruit de données cryptées.}
{128}{}{[Bruit aigu - bruit sec] Ici commandement, avancez patrouille.}
{129}{}{Gnné !}
{130}{}{Euh, pardon, commandement. J'ai appuyé par erreur sur le bouton émetteur.}
{131}{}{Des intrus dans la base ! Déclenchez l'alarme !}
{132}{}{Roger Patrouille, Commandement fin.}
{133}{}{[Tu changes la fréquence de la radio sur le canal de contrôle de sécurité] [Clic !] Entrer numéro d'accès. [Clic !]}
{134}{}{Hagoo !}
{135}{}{Euh, 69.}
{136}{}{5566534571}
{137}{}{Fin accès.}
{138}{}{Canal de sécurité automatique fermé.}
{139}{}{ points d'expérience pour avoir roulé les gardes mutants.}
{140}{}{ points d'expérience pour t'être introduit au coeur de la base militaire sans te faire prendre (pour l'instant)...}
