{100}{}{Bonjour, en quoi je peux t'aider ?}
{101}{}{Qui es-tu ?}
{102}{}{Es-tu le chef de ce gang ?}
{103}{}{Peu importe.}
{104}{}{Un... quoi ?}
{105}{}{On m'appelle Razor... Je suis ce qu'on pourrait appeler le chef.}
{106}{}{Alors, t'es le chef de ce gang ?}
{107}{}{Qu'est-ce que c'est que cette histoire de Secteur clos au Sud ?}
# Player's name follows 108
{108}{}{Un vrai plaisir de te rencontrer ! Je m'appelle }
{109}{}{Un vrai plaisir de te rencontrer ! Mais faut que j'y aille.}
{110}{}{Un gang ? Pas vraiment, non. Mais c'est moi le chef ici.}
{111}{}{Si vous êtes pas un gang, alors vous êtes quoi ?}
{112}{}{Euh, pour moi, vous avez tout d'un gang.}
{113}{}{Au revoir}
{114}{}{C'est le Sanctuaire. Un camp d'esclaves dirigé par une bande appelée les Régulateurs... mais ils disent partout que c'est une "ville". Ils n'arrêtent pas de venir ici pour emmener les nôtres et les faire mourir à la tâche.}
{115}{}{Vous pouvez pas y faire une descente pour libérer les vôtres ?}
{116}{}{Mais, je sais pas pourquoi je te parle ! C'est avec ces mecs que je dois m'associer.}
{117}{}{Je vais voir ce que je peux apprendre sur le Sanctuaire. Salut.}
{118}{}{Alors, que viens-tu faire dans ce coin du désert ?}
{119}{}{Je cherche une Puce d'eau. Tu sais où je peux en trouver ?}
{120}{}{Je parcours le monde.}
{121}{}{J'admire le paysage. Salut.}
{122}{}{On essaie seulement de survivre. Le Sanctuaire nous a mis dans cette position. Ils nous dominent et nous traitent comme des bêtes. Et même pas moyen de nous défendre.}
{123}{}{Pourquoi vous luttez pas contre eux ?}
{124}{}{Vous défendre contre qui ?}
{125}{}{Oh, les gens du Sanctuaire sont plus forts et plus intelligents que vous; c'est leur droit d'exploiter les faibles.}
{126}{}{Je vais voir aux alentours ce que je peux découvrir. Salut.}
{127}{}{Ah, si seulement on était un gang ! Au moins, on aurait des armes convenables pour se défendre.}
{128}{}{Vous défendre contre qui ?}
{129}{}{Ouais, je suis pas dupe ! Vous êtes juste une bande de dégénérés, prêts à faire le mal.}
{130}{}{Pour moi, vous avez tout d'un gang.}
{131}{}{Ah, là-dessus, je peux pas t'aider.}
{132}{}{Qu'est-ce que c'est que cette histoire de Secteur clos au Sud ?}
{133}{}{Es-tu le chef de ce gang ?}
{134}{}{Il nous faut de meilleures armes. Les Contrebandiers, pas très loin d'ici, ont des armes, mais impossible d'en avoir.}
{135}{}{Pourquoi ?}
{136}{}{Je vais voir si je peux apprendre quelque chose.}
{137}{}{Les Régulateurs. C'est eux en fait qui dirigent le Sanctuaire. Pas Zimmerman. Ils viennent ici et emmènent les nôtres au Sanctuaire comme esclaves. Ils nous tuent quand on essaie de les repousser. Parfois, ils viennent juste pour tuer quelques-uns d'entre nous et les rapporter à Zimmerman; comme ça, ils peuvent dire qu'on a tenté de pénétrer dans leur ville, ou je ne sais quelle imbécillité. Ces salauds ont même tué le fils de Zimmerman !}
{138}{}{Le fils de Zimmerman ? Et pourquoi ça ?}
{139}{}{Tu dis que vous n'avez jamais rien fait contre le Sanctuaire ?}
{140}{}{Il y a un nid de Griffemorts entre eux et nous. On n'a même jamais parlé aux Contrebandiers. Les Régulateurs ont les moyens d'éliminer les Griffemorts, mais je ne sais pas pourquoi, ils ne font rien.}
{141}{}{Où je peux trouver les Contrebandiers ?}
{142}{}{D'accord. Salut.}
{143}{}{Josh habitait ici avec moi... et... enfin... je veux dire avec nous. Il savait ce qui se tramait derrière tout ça. Les Régulateurs l'ont menacé: si jamais il essayait de contacter son père ou de retourner au Sanctuaire, ils le tueraient.}
{144}{}{Ils l'ont tué ? Qu'avait-il fait ?}
{145}{}{Je vais au Sanctuaire pour éclaircir tout ça.}
{146}{}{Tard un soir, il a essayé de s'introduire dans la ville pour dire à son père ce qui se passait vraiment. Je contrôlais les transmissions par radio des Régulateurs le soir où ils ont... il a été... pris. [Elle baisse les yeux et secoue lentement la tête.] Tiens, tout est sur ce holodisque.}
{147}{}{Pourquoi t'as pas donné ça au père de Josh ?}
{148}{}{Tu crois donc qu'on peut s'approcher du Sanctuaire ? On se ferait tirer comme des lapins avant d'atteindre les portes.}
{149}{}{Et si moi je lui donnais ce disque ?}
{150}{}{Pourquoi tu réunis pas une foule pour prendre le Sanctuaire de force ?}
{151}{}{Tu risquerais ta vie pour nous aider ?}
{152}{}{Bien sûr. Demande-moi ce que tu veux.}
{153}{}{Peut-être. Il faut d'abord que j'aille vérifier quelques trucs.}
{154}{}{Merci. Ca pourrait vraiment nous aider. Bonne chance. [Elle te tend le holodisque.]}
{155}{}{A plus tard.}
{156}{}{Très bien. J'espère que t'as pris la bonne décision.}
{157}{}{Au revoir.}
{158}{}{Les Contrebandiers sont au Nord-Est d'ici. Mais sois prudent; il ne faut pas prendre les Griffemorts à la légère. J'en ai vu un couper un homme en deux d'un seul coup.}
{159}{}{Je vais voir ce que je peux découvrir.}
{160}{}{Je regrette que tu le prennes comme ça. Mieux vaut que tu partes.}
{161}{}{Au revoir.}
{162}{}{Je peux t'aider ?}
{163}{}{Es-tu le chef de ce gang ?}
{164}{}{Peu importe.}
{165}{}{Un... quoi ?}
{166}{}{Un gang ? Pas vraiment, non. Mais c'est à moi qu'on vient demander quoi faire.}
{167}{}{Zimmerman m'envoie.}
{168}{}{Oh, pour moi, vous avez tout d'un gang.}
{169}{}{Au revoir.}
{170}{}{(L'air un peu nerveux) Quoi ? Est-ce qu'il...}
{171}{}{... veut te loger une balle dans la tête.}
{172}{}{... veut te faire payer d'avoir tué son fils.}
{173}{}{QUOI !!! TOUS CES FILS DE PUTE ! JE LES TUERAI, JE LES ENVERRAI TOUS EN ENFER !!}
{174}{}{Non, c'est toi qui va aller en enfer.}
{175}{}{Euh... qui tu vas envoyer en enfer ?}
{176}{}{...les Régulateurs. C'est eux qui ont tué Josh ! Jamais j'aurais touché à un cheveu de Josh. C'est les Régulateurs qui dirigent le Sanctuaire, pas Zimmerman.}
{177}{}{Si tu crois que tu vas t'en tirer avec des accusations !}
{178}{}{Pourquoi les Régulateurs iraient-ils tuer le fils de Zimmerman ?}
{179}{}{Josh habitait ici avec moi... et... enfin... je veux dire avec nous. Il savait ce qui se tramait derrière tout ça. Les Régulateurs l'ont menacé: si jamais il essayait de contacter son père ou de retourner au Sanctuaire, ils le tueraient. Ils se moquaient de lui... Ils étaient tellement sûrs qu'il ne pouvait pas rejoindre son père...}
{180}{}{Ils l'ont tué ? Qu'avait-il fait ?}
{181}{}{Comment se déroule notre plan ?}
{182}{}{J'essaie encore de tout mettre au point.}
{183}{}{Un... quoi ?}
{184}{}{Je ne sais pas si ça marcherait sans une menace de violence. Ce qu'il faut, c'est que les Contrebandiers nous passent des armes.}
{185}{}{Bon, où sont ces Contrebandiers ? Pourquoi vous leur demandez pas des armes ?}
{186}{}{Oh, bon ! C'était une proposition. Salut.}
{187}{}{Ils sont un peu à l'Est d'ici, mais il y a un nid de Griffemorts entre eux et nous. On leur a même jamais parlé à ces Contrebandiers. }
{188}{}{D'accord, donne-moi le holodisque et je vais aller parler aux Contrebandiers avant d'approcher Zimmerman.}
{189}{}{J'espère que tu vas trouver un moyen de nous aider. Au revoir.}
{190}{}{Que se passe-t-il ?}
{191}{}{Ils ont tué Zimmerman !}
{192}{}{Un... quoi ?}
{193}{}{Dans ce cas, il ne nous reste plus qu'à demander des armes aux Contrebandiers. Tu veux nous aider ?}
{194}{}{Oui.}
{195}{}{Non.}
{196}{}{Merci. Que les dieux t'accompagnent dans ton voyage.}
{197}{}{Merci de ton aide. Nous allons envahir le Sanctuaire, tu pourrais nous être très utile...}
{198}{}{Non merci, la semaine a déjà été assez agitée.}
{199}{}{Certainement, ce serait un plaisir de démolir ces Régulateurs.}
{200}{}{Un... quoi ?}
{201}{}{J'aimerais d'abord parler à Zimmerman.}
{202}{}{Eh bien, encore merci de ton aide. Au revoir.}
{203}{}{Super. Allons-y.}
{204}{}{Ca ne me paraît pas une bonne idée, mais essaie toujours.}
{205}{}{Espèce d'ordure ! Si les Contrebandiers sont partis, jamais on ne pourra s'armer. Fous le camp, tu n'as rien à faire ici.}
{206}{}{Je regrette.}
{207}{}{J't'emmerde.}
{208}{}{Je vais parler à Zimmerman lui donner ce holodisque tout ira bien !}
{209}{}{Tu sais quoi ? Je vais te tuer !}
{210}{}{Un... quoi ?}
{211}{}{Continue et ça va être tes obsèques ! Sans ces fusils, on est à leur merci.}
{212}{}{Fous le camp !}
{213}{}{Tu n'as rien à faire ici.}
{214}{}{Va te faire foutre.}
{215}{}{Merci.}
{216}{}{Mon peuple est libre.}
{217}{}{Bonjour.}
{218}{}{Qu'est-ce que t'as à la tête ? Tu t'es fait tirer dessus ?}
{219}{}{Hein ?}
{220}{}{Voici Razor, chef des Ecorcheurs.}
{221}{}{Tu vois une très belle femme au regard triste.}
{222}{}{S'il te plaît, va-t'en. J'ai à faire.}
{223}{}{Merci de ton aide pour les Régulateurs. Reste autant que tu veux. Pourquoi ne pas t'adresser à Miles et La Forge ? Ils peuvent peut-être t'aider pour tes prochains voyages.}
{224}{}{Bonjour, je peux t'aider ?}
{225}{}{Qui es-tu ?}
{226}{}{Houplah !}
{227}{}{On m'appelle Razor, je suis le chef de ce peuple. Nous vivons ici à la merci des Régulateurs du Sanctuaire.}
{228}{}{Les Régulateurs ? Je leur ai tous réglé leur compte. Ca pose un problème ?}
{229}{}{Tu les a tous tués ? Oh non, aucun problème. Mon peuple peut maintenant vivre librement avec les gens du Sanctuaire.}
{230}{}{J'arrive pas à y croire ! Tu as pu tous les tuer ! Les Ecorcheurs et moi te remercions.}
{231}{}{Il paraît que les Régulateurs contrôlent toujours le Sanctuaire. Tu ne peux donc pas les tuer tous comme tu l'espérais ?}
{232}{}{T'en fais pas, je vais m'en occuper.}
{233}{}{Je crois pas que je pourrai.}
{234}{}{On irait bien avec toi, mais sans armes, les Régulateurs auraient vite fait de tous nous liquider. Une autre possibilité... [Razor réfléchit]. Si tu pouvais faire en sorte que les Contrebandiers nous fournissent des armes, alors certains d'entre nous pourraient t'accompagner.}
{235}{}{Pas une mauvaise idée... J'irai leur parler.}
{236}{}{Je vais bousiller les Régulateurs moi-même.}
{237}{}{Te revoilà. J'ai entendu dire que tu en as fini avec les Régulateurs. Je voulais te remercier pour ce bon débarras. Mon peuple pourra enfin vivre en toute liberté avec les gens du Sanctuaire.}
{238}{}{Je vais m'occuper moi-même des Régulateurs.}
{239}{}{C'est vrai ? Bon, si t'as besoin d'aide ou si tu règles l'affaire, reviens me voir.}

# to male player
{240}{}{T'es qu'un batard !}
# to female player
{241}{}{T'es qu'une pétasse !}

# Fo1in2
{300}{}{Est-ce que vous avez parlé au Contrebandiers ? Nous aurions vraiment besoin de leurs armes.}
	{301}{}{Où est-ce que je peux les trouver ?}
	{302}{}{J'y travaille.}

{400}{}{Est-ce que vous avez parlé à Zimmerman ?}
	{401}{}{J'ai changé d'avis. C'est à vous de vous en occuper maintenant.}
	{402}{}{Ca vaut pas le coup. Nous devrions attaquer les Régulateurs maintenant.}
	{403}{}{Pas maintenant. je dois y aller.}