{100}{}{Tu vois The Rock.}
{101}{}{Tu vois un homme armé.}
{102}{}{Tu ferais mieux de ranger ton arme, fiston. Les Crypts n'aiment pas quand quelqu'un agite des objets brillants dans leur direction.}
{103}{}{Oh, vraiment ?  Je vais leur en parler alors. Où sont-ils?}
{104}{}{Ah, ok.  Ou est-ce que je peux prendre un verre ?}
{105}{}{Qui sont les Crypts?}
{106}{}{T'as l'air d'avoir besoin d'une boisson fraîche.}
{107}{}{[Fait]}
{108}{}{Ouais, va dans le grand bâtiment à l'entrée de la ville et dis-leur que Rock t'envoie.}
{109}{}{Ok.}
{110}{}{Les Crypts ? C'est la bande la plus grosse et la plus balèze dans les environs. Joue pas aux cons avec eux, si tu veux quitter Scrapheap en un seul morceau.}
{111}{}{Qui sont-ils?}
{112}{}{Ils sont dans le grand bâtiment, juste aux portes de la ville. Tu veux un boulot d'avenir ?  Un endroit pour manier ton flingue ?}
{113}{}{Non.}
{114}{}{Oui, bien sûr.}
{115}{}{Alors, je te suggère de quitter la ville au plus vite. Il n'y a pas de place à Scrapheap pour ceux qui veulent s'opposer aux Crypts. Tu peux les rejoindre si tu veux -- Mais c'est ta vie.}
{116}{}{Ok.}
{117}{}{Parfait. Va dans la grande maison et dis-leur que tu viens de la part de Rock.}
{118}{}{Ok.}
{119}{}{Heureux d'apprendre que tu es du bon côté de Scrapheap. Bienvenue dans la bande.}
{120}{}{Merci.}
{121}{}{Tu as commis une erreur. Une grave erreur.}
{122}{}{Bienvenue à Scrapheap, fiston. Joue pas au con et tout ira bien.}
{123}{}{Merci. Quel est cet endroit ?}
{124}{}{Qui est le patron içi ?}
{125}{}{Scrapheap est le bras armé du désert. Pas de meilleur endroit pour élever ses enfants, a mon avis. [Rires]  Cette endroit ferait passer Dépôtville pour une majestueuse cité des Anciens.}
{126}{}{Merci.}
{127}{}{Disons que c'est une commune, dirigée par Lex. Mais le vrai pouvoir est toujours derrière le trône. Içi, les gens savent se tenir en présence des Crypts.}
{128}{}{Merci.}
{129}{}{Tu pose vraiment beaucoup de questions ! Je pense que tu devrais faire un tour, maintenant.}
{130}{}{Ok.}
{131}{}{[Fait]}
{132}{}{Les Crypts vont t'envoyer dans ta tombe!}
{133}{}{Les idiots n'ont pas le droit de vivre.}
{134}{}{L'idiotie va disparaître.}
{135}{}{Regarde qui vient de se prendre un joli coup de bâton !}
{136}{}{Tu ferais mieux de ranger ton arme. Les Crypts n'aiment pas quand quelqu'un agite des objets brillants dans leur direction.}
{137}{}{Bienvenue à Scrapheap, ma grande. Joue pas à la conne et tout ira bien.}
