{100}{}{La cage d'ascenseur n'est pas facile à escalader sans corde.}
{101}{}{Tu réussis à suspendre une corde dans la cage d'ascenseur.}
{102}{}{Tu ne peux pas redescendre la cage en n'utilisant que la poutre métallique.}
{103}{}{Tu réussis à attacher la corde à la poutre métallique.}
{104}{}{La cage d'ascenseur n'est pas facile à descendre sans corde.}
{105}{}{Tu réussis à suspendre une corde dans la cage d'ascenseur.}
{106}{}{Inutile de fixer une autre corde dans la cage d'ascenseur.}
