{100}{}{Tu es en mesure d'affirmer que le Centre de Commandement et de Contrôle a bel et bien été enseveli sous d'autres pierres. Tu devras rechercher la puce d'eau ailleurs.}
{101}{}{La masse de décombres bloquant ce couloir est impressionnante. Tu ne penses pas pouvoir le dégager, même avec de puissants explosifs.}
{102}{}{Tu reçois }
{103}{}{ points d'expérience.}
