{100}{}{Voici Rufus.}
{101}{}{S'il te plaît, ne me tue pas...}
{102}{}{Chut ! J'essaie de jouer !}
{103}{}{Silence ! J'essaie de jouer. Cyberbois, le Prince de la Matrice, c'est un classique !}
{104}{}{Oh non ! Mon personnage a encore été battu. Roger est tellement nul...}
{105}{}{Où est la clé du Cyberespace ? J'ai parcouru tous les recoins de ce fichu bâtiment Kruz...}
{106}{}{Tu ne connaîtrais pas le mot de passe du Malibu Stu's ? Oh, tant pis...}
{107}{}{Ce Kaira, quel renard !}
{108}{}{Laisse-moi tranquille. J'essaie de résoudre cette fichue énigme...}
