{100}{}{Voici Saul, le boxeur.}
{101}{}{Voici un homme robuste et musclé.}
{102}{}{Sa musculature s'est développée au fil des années de combats et sa stature agile est caractéristique d'un boxeur confirmé.}
{103}{}{Oh ! Eh bien, bonne chance.}
{104}{}{Ce n'est ni le lieu ni le moment pour utiliser des armes. Mais si tu veux m'affronter un jour sur un ring, pas de problème !}
{105}{}{Que veux-tu ?}
{106}{}{Oui ?}
{107}{}{Que fais-tu ici ?}
{108}{}{Un type robuste, hein ? Je parie que je pourrais te battre.}
{109}{}{Je m'appelle }
{110}{}{. Je jetais juste un oeil.}
{111}{}{[Saul rit de bon coeur.] Je suis boxeur !}
{112}{}{Ah, je pourrais te botter le train.}
{113}{}{Hmm. Alors ?}
{114}{}{Euh, non merci.}
{115}{}{Saul est inconscient.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{}
{122}{}{}
{123}{}{}
{124}{}{ [Saul rit de bon coeur.]}
{125}{}{ [Saul rit d'un air menaçant.]}
{126}{}{Très bien. Ca ne devrait pas être bien long.}
{127}{}{Vas-y ou tais-toi.}
{128}{}{Eh bien, si tu cherchais quelqu'un pour te refaire le portrait, tu l'as trouvé.}
{129}{}{Je m'appelle Saul.}
{130}{}{Euh, non merci. Puis-je te poser quelques questions ?}
{131}{}{Alors, tu vis à Dépôtville depuis longtemps ?}
{132}{}{Eh bien, ça m'a fait plaisir de te rencontrer. A plus tard.}
{133}{}{Oui.}
{134}{}{J'y ai toujours vécu. J'y ai grandi.}
{135}{}{Que peux-tu me dire sur Dépôtville ?}
{136}{}{Comment es-tu devenu boxeur ?}
{137}{}{Hmm. Eh bien, je travaille pour Gizmo. C'est le propriétaire du grand casino, là-bas. Les combats rapportent bien ici ! Que veux-tu savoir d'autre ?}
{138}{}{Qu'y a-t-il à faire ici ?}
{139}{}{Peux-tu m'en dire un peu plus sur Gizmo et sur ce casino ?}
{140}{}{Je boxe depuis plusieurs années.}
{141}{}{Je me bagarrais toujours avec mes frères quand j'étais petit. Un jour, une petite bande de pillards a attaqué Dépôtville, et j'ai réussi à en battre un avant qu'il ne pointe son arme sur moi. Par chance, Gizmo parrainait des combats de boxe, et j'avais besoin d'argent. Depuis, je boxe en professionnel.}
{142}{}{Qu'est-il arrivé à tes frères ?}
{143}{}{Alors, qu'y a-t-il à faire dans cette ville ?}
{144}{}{Peux-tu me parler de ton chef ?}
{145}{}{Si tu as besoin de provisions, tu peux te rendre au magasin de Killian Darkwater, au Sud-Est d'ici. Si tu cherches une chambre pour la nuit, va à la Crash House, juste à côté. Et si tu envisages de séjourner ici quelque temps, tu peux aller prendre un verre au Skum Pitt. Mais attention aux Skulz !}
{146}{}{Qui sont les Skulz ?}
{147}{}{Parle-moi du casino.}
{148}{}{Le casino de Gizmo accueille tous ceux qui aiment le jeu. Il y a des tas de jeux et on s'y amuse bien ! C'est l'endroit le plus sympa de cette partie de la ville !}
{149}{}{Qu'y a-t-il d'autre à faire par ici ?}
{150}{}{Mon frère James a été tué lors d'une attaque des pillards il y a quelques années. Peu de temps après, mon autre frère, Darrell, a rassemblé ses affaires et il est parti pour le Sud en direction d'un lieu mythique appelé le Rayon, en quête du trésor des anciens, ou un truc du genre. Il n'en est jamais revenu.}
{151}{}{Pourquoi restes-tu à Dépôtville ?}
{152}{}{Euh, peut-on changer de sujet ?}
{153}{}{Ca m'attriste pour toi.}
{154}{}{Que sais-tu sur cet endroit légendaire, le Rayon ?}
{155}{}{Merci. Les années ont passé mais j'ai toujours du mal à en parler.}
{156}{}{Alors, puis-je te poser quelques questions ?}
{157}{}{Je vis ici. J'aime boxer, je mène une vie agréable avec Trish, et je n'ai pas envie d'aller vivre ailleurs.}
{158}{}{Oh. Eh bien, c'est parfait. Ca te dérangerait si on changeait de sujet ?}
{159}{}{Oui, j'ai rencontré Trish.}
{160}{}{Quoi ?}
{161}{}{En quoi puis-je t'être utile ?}
{162}{}{Qu'y a-t-il à faire ici ?}
{163}{}{Peux-tu me parler un peu de ton chef ?}
{164}{}{[Tu tapotes ton arme] J'aimerais que tu rencontres ma petite amie.}
{165}{}{Merci d'avoir parlé avec moi. A bientôt.}
{166}{}{Les Skulz sont une bande de vauriens qui traînent à l'arrière de la Crash House et au Skum Pitt. Fais attention à eux ; ils aiment bien jouer du couteau.}
{167}{}{Merci du conseil. Je ferai attention.}
{168}{}{Je vois. As-tu autre chose à me dire ?}
{169}{}{Eh bien, fais attention, hein ?}
{170}{}{Elle représente beaucoup pour moi.}
{171}{}{[Saul fronce les sourcils.] Mais elle n'aime pas me voir boxer. Elle n'a pas l'air de comprendre que c'est ce que je veux faire.}
{172}{}{Elle pense à ton bien-être. Elle ne doit pas supporter de te voir te battre et risquer ta vie pour Gizmo. Si tu ne trouves pas de compromis, tu risques de la perdre.}
{173}{}{Je pense qu'elle s'inquiète pour toi.}
{174}{}{Alors, peut-on parler d'autre chose ?}
{175}{}{Eh bien, à plus tard.}
{176}{}{Je n'avais jamais vu les choses comme ça. Je pensais qu'elle détestait la boxe, c'est tout. Je suppose que je devrais en parler avec elle. Merci.}
{177}{}{Ah, elle n'aime pas la boxe, c'est tout.}
{178}{}{Eh bien, peut-on parler d'autre chose ?}
{179}{}{A bientôt.}
{180}{}{Encore toi. Qu'est-ce qu'il y a ?}
{181}{}{Rebonjour.}
{182}{}{Je suis là pour t'apprendre les bonnes manières.}
{183}{}{Je dois te parler de Trish.}
{184}{}{Peux-tu me parler de Dépôtville ?}
{185}{}{D'après ce que j'ai entendu, le Rayon est un immense cratère d'où se dégage une lueur la nuit. On dit qu'il est très loin au Sud, mais je n'en sais pas plus. On dit aussi qu'il est habité par toutes sortes de monstres mutants qui veillent sur la technologie d'avant Guerre.}
{186}{}{Je vois. Merci des renseignements.}
{187}{}{Intéressant. Peux-tu me fournir d'autres renseignements ?}
{188}{}{Sans ta tête, ce sera dur, minable.}

# Fo1in2
{200}{}{J'ai parlé à Trish.}
