{100}{}{Tu remarques une caméra de sécurité apparemment en fonctionnement.}
{101}{}{Tu remarques des armes à feu dissimulées qui suivent tes mouvements.}
{102}{}{Des armes cachées ouvrent le feu ! En te tordant et en te faufilant, tu parviens à éviter les balles !}
{103}{}{Des armes cachées ouvrent le feu ! En te tordant et en essayant d'esquiver les tirs, une balle t'érafle.}
{104}{}{Tu as subi }
{105}{}{ de dégât.}
{106}{}{Des armes cachées ouvrent le feu ! Dans la panique, tu trébuches et tu tombes, mais tes blessures sont bénignes.}
{107}{}{Tu as subi }
{108}{}{ de dégât.}
{109}{}{Des armes cachées ouvrent le feu ! Une balle te touche !}
{110}{}{Tu as subi }
{111}{}{ de dégât.}
