{100}{}{Tu vois un Paladin solitaire. Il à l'air en colère et effrayé à la fois.}

{101}{}{Arrête toi, étranger ! Identifie-toi !}

# low IQ
{102}{}{Moi }
{103}{}{.}

{104}{}{Je suis }
{105}{}{. Qu'est-ce qui s'est passé ici ?}
{106}{}{Mon nom n'est pas important.}

# low IQ
{107}{}{Sois prudent, }
{108}{}{, tu pourrais te blesser. Une armée de méchants mutants est venue est a fait un grand Boom. Tu comprends ?}
{109}{}{Heuu-heu.}
{110}{}{Voilà. Donc, tu devrais trouver un autre endroit où aller. C'est pas sûr ici.}
{111}{}{Moi partir.}

{112}{}{Des mutants. C'était une grande armée. Ils sont venus, ils ont tué tout le monde, prit tout ce qu'ils pouvaient emporter, et laissé cet endroit en ruine.}
{113}{}{Et comment as-tu fait pour survivre à tout ça ?}
{114}{}{Je revenais d'une longue patrouille. Quand je suis arrivé la bataille était déjà terminée. Je ne pouvais plus rien faire. Alors je me suis caché et je les ai observés.}
{115}{}{Tu veux dire que tu avais trop peur pour faire quoi que ce soit ?}
{116}{}{Personne d'autre n'a survécu ?}
{117}{}{Ecoute, je suis peut-être pas le mec le plus courageux de la Confrérie, mais je ne suis pas un idiot. Il y avait vraiment rien que j'aurais pu faire.}
{118}{}{Lâche ! Alors reste là et garde ce tas de ruines. Je ferai mieux d'y aller et de tuer quelques mutants pour toi.}
{119}{}{J'en suis désolé. Est-ce que quelqu'un d'autre a survécu à l'attaque ?}
{120}{}{Quelques troupes d'éclaireurs, quelques Paladins en patrouille... trop peu pour faire quelque-chose. La Confrérie de l'Acier est presque morte. Je vais rester ici pour le moment, à essayer de réunir le maximum de survivants possible. Je leur expliquerai ce qui s'est passé. Ensuite... ensuite je ne sais pas. J'ai jamais eu l'opportunité d'y penser.}
{121}{}{Je comprends. Continue à faire du bon travail, Paladin, je dois y aller.}
{122}{}{Au revoir, }
{123}{}{. Si tu rencontres des survivants de la Confrérie pendant tes déplacements, dis leur ce qui s'est passé ici.}

{124}{}{Arrête toi... Oh, c'est toi, }
{125}{}{.}
{126}{}{Heuu-heu.}
{127}{}{Oui, c'est moi. Qu'est-ce qui s'est passé ici ?}

{130}{}{Au revoir, }
{131}{}{. Si tu rencontres des survivants de la Confrérie pendant tes déplacements, dis leur ce qui s'est passé ici.}
{132}{}{Bien sûr. Je dois vraiment y aller maintenant.}

{133}{}{Alors tu devrais y aller. Je n'ai rien à te dire.}

{150}{}{Le Paladin t'ignore. Il semble absorbé par ses pensées.}
