{100}{}{Tu crochètes le verrou.}
{101}{}{Tu ne peux pas ouvrir ce verrou.}
{102}{}{Tu brises ton passe-partout.}
{103}{}{Tu ne sais pas comment crocheter le verrou.}
{104}{}{La porte est verrouillée.}
{105}{}{La porte est ouverte.}
{106}{}{La porte est fermée, mais déverrouillée.}
{107}{}{crîîîk}
