{100}{}{Voici Sid, l'assistant de Beth.}
{101}{}{Bonjour.}
{102}{}{Bonjour, monsieur !}
{103}{}{Bonjour, madame !}
{104}{}{Bonsoir.}
{105}{}{Je sais, je sais... [chuchotement] elle parle beaucoup, tu ne trouves pas ?}
{106}{}{Bienvenue à l'Armurerie et au Moulin à Rumeurs de Beth.}
{107}{}{Beth, il y a quelqu'un pour toi.}
{108}{}{Bienvenue au Palais des Plaisirs de Beth.}
{109}{}{As-tu apporté des cadeaux ?}
{110}{}{[chuchotement] Ne te confie pas à elle si tu ne veux pas que toute la ville soit au courant.}
{111}{}{Encore ?}
{112}{}{Des armes gratuites ! Viens les prendre !}
{113}{}{Le bleu clair spécial se trouve dans l'allée trois.}
{114}{}{Elle est à moi, alors laisse tomber !}
{115}{}{Elle aime se faire désirer.}
{116}{}{Pause petit déjeuner.}
{117}{}{Pause déjeuner !}
{118}{}{Bonsoir.}
{119}{}{C'est une belle combinaison bleue, hein ? Le 13 est-il ton chiffre porte-bonheur ?}
{120}{}{Oh, c'est un homme mystérieux !}
{121}{}{Oh, c'est une femme mystérieuse !}
{122}{}{Lis-tu les lignes de la main ?}
{123}{}{Oh, Beth adore le cuir !}
{124}{}{Eh trésor, achète son blouson de cuir pour moi.}
{125}{}{Eh trésor, achète son blouson de cuir pour moi.}
{126}{}{Belle armure !}
{127}{}{C'est du camouflage. Attends ! Où vas-tu ?}
{128}{}{Eh, cet équipement semble redoutable !}
{129}{}{Non !}
{130}{}{Eh ! C'est la boîte en métal ! Comment vas-tu ?}
