{100}{}{La porte du Skum Pitt est fermée à clé.}
{101}{}{Tu réussis à ouvrir la porte.}
{102}{}{Tu essaies de crocheter la serrure, mais tu ne parviens pas à ouvrir la porte.}
{103}{}{Tu entends quelque chose craquer. On dirait que la serrure est bloquée.}
{104}{}{La porte n'est pas fermée à clé.}
