{100}{}{Voici des mutants et des enfants agenouillés devant un écran vidéo.}
{101}{}{Prie avec nous pour la paix, mon enfant.}
{102}{}{L'Unité vaincra si nous sommes forts. Médite sur la qualité de la force.}
{103}{}{Pour mener à bien notre mission et sauver l'humanité, nous devons avoir la foi. Prie avec nous.}
{104}{}{Impie ! Tu blasphèmes ! Ta punition sera terrible !}
{105}{}{Nous devons prier pour être forts ! Le changement est proche.}
{106}{}{L'Unité est notre avenir, mon frère.}
{107}{}{L'Unité est notre avenir, ma soeur.}
{108}{}{Je crois en notre Maître. Il est notre salut.}
