{100}{}{Voici Sophia, une instructrice des Initiés de la Confrérie.}
{101}{}{Ok, des questions ?}
{102}{}{N'hésitez pas à poser des questions si vous ne comprenez pas quelque chose. Ne soyez pas timides.}
{103}{}{Relisez vos notes.}
{104}{}{Demain, nous ferons un nouveau test pour les élèves travaillant sur la section 14.}
{105}{}{Désolée, mais je ne peux pas te parler pour le moment. J'ai un cours à donner.}
{106}{}{Je crois que tu as quelque chose pour moi.}
{107}{}{Oui. Voilà.}
{108}{}{Oui, mais je ne l'ai pas sur moi.}
{109}{}{Toi.}
{110}{}{Désolée, mais j'ai un cours à donner. Ne me dérange pas, s'il te plaît.}
{111}{}{Tu ne devrais pas être ici. Vree n'aime pas être dérangée pendant la nuit. C'est le moment où nous méditons.}
{112}{}{Nous méditons. Va t'en, s'il te plaît. Reviens demain matin.}
{113}{}{Laisse-nous.}
{114}{}{Aie un peu de respect. Tu ne dois pas déranger ceux qui méditent.}
{115}{}{Les Initiés ont décidément beaucoup à apprendre. Va t'en, s'il te plaît.}
{116}{}{Ne me dérange pas.}
{117}{}{Nous ne sommes pas disponibles la nuit. Reviens nous voir demain matin.}
{118}{}{Il fait nuit. Tu devrais être au lit, à moins que tu ne sois de garde, auquel cas tu devrais être à ton poste.}
{200}{}{Bonjour initié. Que puis-je pour toi ?}
{201}{}{Je crois que tu as quelque chose pour moi ?}
{202}{}{Oui, voilà.}
{203}{}{Oui, mais je ne l'ai pas sur moi.}
{204}{}{Moi ? Non, excuse-moi. Tu dois me confondre avec quelqu'un d'autre.}
{205}{}{Euh...}
{206}{}{Merci beaucoup. C'est gentil à toi de m'avoir donné ça.}
{207}{}{Hmm, merci. Ca va ? En tout cas, c'est gentil à toi de m'avoir donné ça.}
{208}{}{Mes recherches auraient été retardées sans ça. C'est une bonne chose de savoir que nous comptons parmi nous une jeune recrue digne de confiance. Je savais que ce ne serait pas une mauvaise idée d'accepter les étrangers parmi nous. Va voir Michael, il aura quelque chose pour toi.}
{301}{}{Salut. C'est la première fois que je te vois ici, tu cherches ton chemin ? Que puis-je pour toi ?}
{302}{}{Euh......}
{303}{}{Peux-tu me dire où est la bibliothèque ?}
{304}{}{Je cherche Vree.}
{305}{}{Où sommes-nous ?}
{306}{}{Si je cherchais mon chemin, ce n'est pas à quelqu'un d'aussi stupide que toi que je m'adresserais !}
{307}{}{Quand je pense au genre de personnes que nous acceptons comme initiés en ce moment ! Que dieu nous aide !}
{308}{}{La bibliothèque, c'est ici. C'est ici que nous conservons nos archives sur les armes, sur la technologie et, bien sûr, sur l'histoire de la Confrérie.}
{309}{}{Je dois faire réparer une puce d'eau. Peux-tu m'aider ?}
{310}{}{J'aimerais en savoir plus sur les armes que vous fabriquez ici.}
{311}{}{Est-ce l'endroit où je peux trouver des holodisques ?}
{312}{}{Tant pis, merci de m'avoir accordé à un peu de ton temps.}
{313}{}{Je cherche un gros fusil pour améliorer mes compétences meurtrières.}
{314}{}{Je suis l'aide de Vree. Vree est là-bas.}
{315}{}{Merci.}
{316}{}{En quoi consiste ton travail avec Vree ?}
{317}{}{Mon domaine de compétences est l'histoire de la Confrérie. Ton problème concerne la fabrication : tu devrais plutôt t'adresser à Vree.}
{318}{}{Je pensais que les scribes connaissaient ce genre de choses.}
{319}{}{J'aimerais connaître l'histoire de la Confrérie.}
{320}{}{Ton aide m'est très précieuse !}
{321}{}{Ok, merci de ton aide.}
{322}{}{Pour ça, tu dois t'adresser à Vree, la responsable des scribes. J'ai plus important à faire.}
{323}{}{Je vais aller voir Vree.}
{324}{}{Plus important à faire ? Quoi donc ?}
{325}{}{Tu ne considères pas l'armement de la Confrérie comme important ?}
{326}{}{Nous avons beaucoup de holodisques ici dans la bibliothèque. Ils sont classés par domaines : histoire, technologie et armes.}
{327}{}{Je voudrais voir un holodisque sur votre technologie.}
{328}{}{Je voudrais voir un holodisque sur les armes.}
{329}{}{Je voudrais voir un holodisque sur l'histoire de la Confrérie.}
{330}{}{On m'envoie interroger Vree sur l'histoire de la Confrérie.}
{331}{}{Ma spécialité est l'histoire de la Confrérie. Beaucoup de gens semblent ici avoir oublié l'importance de notre histoire.}
{332}{}{Que peux-tu me dire sur l'histoire de la Confrérie ?}
{333}{}{Qu'y a-t-il de plus important que l'histoire ?}
{334}{}{On dirait que tu ne vas pas tarder à avoir tes règles, hein ?}
{335}{}{Je voudrais interroger quelqu'un sur les armes.}
{336}{}{Entretenir l'histoire de la Confrérie. Beaucoup de gens semblent ici avoir oublié combien notre histoire est importante.}
{337}{}{Vree semble penser que les recherches sur les nouvelles armes et les informations rassemblées au cours des autopsies de Mutants sont plus importantes que notre histoire. Elle a oublié que notre histoire fait partie de nous. La plupart des nouveaux initiés ne savent même pas qui est Roger Maxson, et encore moins ce qu'il a fait pour nous.}
{338}{}{Je voudrais en savoir plus sur l'histoire de la Confrérie. Pourrais-tu me fournir des informations ?}
{339}{}{Hmm, je crois que je devrais m'adresser à Vree. Au revoir.}
{341}{}{Je crois que Vree a raison ! A quoi servent toutes ces conneries de toute façon !?!}
{342}{}{Il est vrai que l'histoire est importante mais je recherche surtout de nouvelles technologies et de meilleures armes.}
{343}{}{Pour ce genre de choses, tu dois t'adresser à Vree.}
{344}{}{Seuls les Scribes et les Paladins ont accès à ce genre de choses. Vree pourra peut-être t'aider.}
{345}{}{Merci, je vais interroger Vree.}
{346}{}{Puis-je avoir accès à certains holodisques ?}
{347}{}{Tu n'es apparemment pas la personne qu'il me faut. Au revoir.}
{348}{}{Eh bien, ça fait plaisir de voir que quelqu'un s'intéresse à notre grande histoire. Ce n'est pas comme certains. Voilà. Ce disque contient certains de nos écrits les plus anciens.}
{349}{}{Merci.}
{350}{}{Je me moque de ce genre de trucs. Merci quand même.}
{351}{}{Nos archives sont accessibles à tous ceux qui veulent connaître notre grande histoire... Mais personne ne les consulte jamais.}
{352}{}{Je voudrais voir quelque chose sur l'histoire de la Confrérie.}
{353}{}{Vraiment ? Je m'en moque aussi, montre-moi les armes.}
{354}{}{Salut. C'est la première fois que je te vois ici, tu cherches ton chemin ? Puis-je quelque chose pour toi ?}
{355}{}{Euh......}
{356}{}{Peux-tu me dire où est la bibliothèque ?}
{357}{}{On m'envoie interroger Vree sur l'histoire de la Confrérie.}
{358}{}{Si je cherchais mon chemin, ce n'est pas à quelqu'un d'aussi stupide que toi que je m'adresserais !}
{359}{}{Tu n'as pas trouvé ce que tu cherchais, n'est-ce pas ? Vree est bien trop occupée avec ses "expériences" pour s'intéresser encore à l'histoire.}
{360}{}{Eh bien alors, qui puis-je interroger sur l'histoire de la Confrérie ?}
{361}{}{Ouais, la Confrérie semble remplie d'idiots.}
{362}{}{Moi non plus. Au revoir.}
{363}{}{Je ne parlerai pas avec toi.}
{364}{}{Que puis-je pour toi ?}
{365}{}{Que fais-tu ici ?}
{366}{}{Peux-tu me parler de l'histoire de la Confrérie ?}
{367}{}{Excuse-moi, je te prenais pour quelqu'un d'autre. Au revoir.}
{368}{}{Je suis l'aide de Vree.}
{369}{}{Merci.}
{370}{}{En quoi consiste ton travail avec Vree ?}
{371}{}{Eh bien, ça fait plaisir de voir que quelqu'un s'intéresse à notre grande histoire. Ce n'est pas comme certains. Voilà. Ce disque contient certains de nos écrits les plus anciens.}
{372}{}{Merci.}
{373}{}{Je me moque de ce genre de trucs. Merci quand même.}
{374}{}{Le disque que je t'ai confié contient certains de nos écrits les plus anciens. Pour lire les données qu'il renferme, charge-le dans ton Pip-Boy 2000.}
{375}{}{Merci.}
{376}{}{Je me moque de ce genre de trucs. Merci quand même.}
{377}{}{Ton attitude ne me plaît pas du tout, et je préfère ne pas te parler.}
{378}{}{Bien. Au revoir !}
{379}{}{Pardon, j'ai manqué de tact et je te présente mes excuses.}
{380}{}{J'accepte tes excuses. Bon, que puis-je pour toi ?}
{381}{}{Que fais-tu ici ?}
{382}{}{Peux-tu me parler de l'histoire de la Confrérie ?}
{383}{}{Pardon, je te prenais pour quelqu'un d'autre. Au revoir.}
{384}{}{Je suis l'aide de Vree. Vree est au Centre d'Etudes.}
{400}{}{Voici une instructrice des Initiés de la Confrérie.}
