# Now split to allow different exp reward amount:  (Sduibek)
{100}{}{Tu reçois }
{101}{}{ points d'expérience pour avoir arrêté les radscorpions.}
{102}{}{On dirait qu'ils proviennent de la race des Scorpions Empereurs.}
# From GENCHAT.MSG:  (Sduibek)
{188}{}{Les radscorpions sont maintenant enfermés dans leur caverne, ils ne sont plus une menace pour les Sables Ombragés.}
{189}{}{}
{200}{}{L'entrée de la grotte vous attire dans l'antre des radscorpions...}
