{100}{}{Voici Mme Stapleton, la bibliothécaire.}
{101}{}{Voici une femme d'un certain âge.}
{102}{}{Bonjour. Bienvenue à la Bibliothèque. Il me semble que c'est la première fois que je te vois ici. Que cherches-tu pour approfondir tes connaissances ?}
{103}{}{Ca me fait plaisir de te revoir. Que cherches-tu aujourd'hui ?}
{104}{}{Qu'as-tu comme livres à me proposer ?}
{105}{}{Je cherche une puce d'eau.}
{106}{}{Rien, merci.}
{107}{}{Eh bien, laisse-moi te présenter ma sélection.}
{108}{}{Eh bien, au cours de mes recherches, j'ai déjà trouvé des références à ce sujet. En fait, je dispose d'un Holodisque contenant des informations qui pourraient t'être utiles.}
{109}{}{Un Holodisque, qu'est-ce que c'est ?}
{110}{}{Puis-je voir cet Holodisque ?}
{111}{}{Un Holodisque contient des informations qui ne peuvent être lues que par certains appareils électroniques. Je vois que tu as un PoP-Boy. Tu peux l'utiliser pour décoder, lire et stocker les informations contenues sur les Holodisques.}
{112}{}{Génial ! Puis-je avoir cet Holodisque ?}
{113}{}{Les informations sont difficiles à obtenir de nos jours. Je dois te demander 750 caps en échange de ce disque.}
{114}{}{Très bien. Voilà l'argent.}
{115}{}{Cet Holodisque ne me semble pas en très bon état. Je t'en offre 500.}
{116}{}{Que penserais-tu plutôt d'un bon coup de chalumeau dans la bibliothèque ! Hein, ma petite dame ?!}
{117}{}{Je regrette mais je n'ai pas d'argent.}
{118}{}{Désolée mais je ne peux pas brader cet Holodisque. Reviens quand tu auras la somme que je te demande.}
{119}{}{Désolée mais tu ferais mieux d'oublier tes tendances pyromanes. Je te prie de sortir.}
{120}{}{[Mme Stapleton prend ton argent.]}
{121}{}{Tu as raison, le disque n'est pas en très bon état. Les choses étant ce qu'elles sont, c'est d'accord pour 500. [Mme Stapleton prend ton argent.]}
{122}{}{Normalement, je ne cède pas à ce genre de menaces, mais pour protéger ma collection, je préfère te donner le disque. En échange, je te demanderai de ne jamais revenir ici.}
{123}{}{Comme je te l'ai déjà expliqué, pour accéder aux informations, tu devras utiliser ton Pip-Boy. [Mme Stapleton te tend le holodisque]}
{124}{}{Désolée mais j'ai des recherches à faire.}
{125}{}{Ben ?}
{126}{}{Pardon, je ne te comprends pas. Je dois avoir quelque part un Holodisque pour apprendre le français, si ça t'intéresse.}
{127}{}{Au revoir.}
{128}{}{Merci.}
{129}{}{Euh...}
{130}{}{As-tu des exemplaires des Journaux de Chimie ? Miles, du Sanctuaire, m'a dit que tu devais en avoir.}
{131}{}{Oui, j'ai entendu parler de Miles et j'ai ce qu'il lui faut. Cela te coûtera 750 caps.}
{132}{}{Voilà. Dis bonjour à Miles de ma part.}
{133}{}{Malheureusement, tu n'as pas assez d'argent. Reviens quand tu auras de quoi payer.}

# Fo1in2
{1000}{}{J'ai entendu dire que tu avais arrêté ces mutants. Tu es un véritable héro ! Il y a quelque chose que je voudrais te donner !}
	{1010}{}{[Continue]}
{1100}{}{Il y a un certain temps, cet homme mysterieux est venu au Centre et m'a vendu un livre très spécial. Je n'ai jamais bien compris ce qu'il y avait écrit, mais peut-être que ça te parlera toi ? [Mrs. Stapleton te donne ce qui ressemble à un vieux manuel]}
	{1110}{}{[Terminé]}
	{1111}{}{[Terminé]}

{1200}{}{Non. Merci ! Sans ton aide, nous serions probablement tous mort ou transformé en ces... choses.}

