#
# Lines for the Mysterious Stranger.
# These used to be in GENCHAT.MSG
#
{100}{}{C'est parti !}
{101}{}{Il semblerait que vous puissiez utiliser un peu d'aide.}
{102}{}{Je vous aiderai.}
{103}{}{Je ne parle pas beaucoup. Désolé.}
