{100}{}{C'est une sorte d'énorme super mutant ! Et il a un énorme fusil !}
{101}{}{Tu es sur le territoire de l'Unité. Je ferais mieux de te faire rentrer.}
{102}{}{Ok.}
{103}{}{Je ne crois pas.}
{104}{}{Quoi ?}
