{100}{}{Voici un ordinateur très perfectionné de la Confrérie.}
{101}{}{Tu n'as pas accès à ce terminal.}
{102}{}{La leçon se termine dans six heures. La fatigue te tiraille.}
{103}{}{Tu as déjà ingurgité tout ce que tu pouvais.}
#
{200}{}{Voici un ordinateur. Il semble pourvu de pièces en chair humaine.}
#
{201}{}{Tu joues un moment avec l'ordinateur mais tu ne parviens pas à contourner le système de sécurité.}
{202}{}{Cet ordinateur fonctionne parfaitement.}
{203}{}{Tu trouves un fichier de données intéressant concernant une base secrète au Nord-Ouest.}
#
# A number is inserted between 204 and 205
{204}{}{Tu reçois }
{205}{}{ points d'expérience pour avoir piraté cet ordinateur.}
