{100}{}{Tu vois Therax, un Ténébreux d'élite.}
{101}{}{Tu vois Justin, un Ténébreux d'élite.}
{102}{}{Tu vois Sereine, un Ténébreux d'élite.}
{103}{}{Tu vois Dolkarn, un Ténébreux d'élite.}
{104}{}{Tu vois Hort, un Ténébreux d'élite.}
{105}{}{Tu vois Chris, un Ténébreux d'élite.}
{106}{}{Tu vois Jaunita, un Ténébreux d'élite.}
{107}{}{Tu vois Lesley, un Ténébreux d'élite.}
{108}{}{Tu vois Renfield, un Ténébreux d'élite.}
{109}{}{Tu vois Timothy, un Ténébreux d'élite.}
{110}{}{Bienvenue ô travailleur. Tu arrives juste à temps pour nous aider.}
{111}{}{Gnéé ?}
{112}{}{Ok. D'accord.}
{113}{}{Désolé. Je suis bien trop occupé.}
{114}{}{Pourquoi je vous aiderais ?}
{115}{}{Aucune importance. Viens avec moi, je vais te mettre au travail.}
{116}{}{Ce n'était pas une requête. Tu vas nous aider.}
{117}{}{Tu n'es pas celui qui cherche à ramener la paix dans le désert ?}
{118}{}{Oui, sauf que je vois pas en quoi vous aider aménera la paix.}
{119}{}{Non. Je préfère la destruction de masse.}
{120}{}{Nous pensons qui si tout le monde, Ténébreuxs et humains, pouvaient apprendre à travailler ensemble, nous pourrions résoudre beaucoup de problèmes.}
{121}{}{Ca à l'air intéressent. J'en suis.}
{122}{}{Oublie ça.}
{123}{}{Il y a quelque chose qui sonne faux dans tout ça.}
{124}{}{Tout va très bien. Peut-être que ton intelligence limitée empêche ta conscience d'évoluer.}
{125}{}{Tu as probablement raison. J'en suis.}
{126}{}{Peut-être. Laisse-moi inspecter ton crâne...}
{127}{}{Si c'est ton désir, alors tu es comblé.}
{128}{}{Bienvenue à nouveau. Tu pourrais nous aider maintenant.}
