{100}{}{Voici Troy.}
{101}{}{Félicitations, humain. Le sort a voulu que tu rejoignes une bande élite de disciples. Suis-moi.}
{102}{}{Ca n'aurait pas avoir avec les rumeurs faisant état d'une armée Super Mutante déchaînée ?}
{103}{}{Où allons-nous ?}
{104}{}{Qu'attends-tu ? Allons-y !}
{105}{}{Je ne pense pas.}
{106}{}{D'où vient cette puanteur indescriptible ? Oh, c'est toi !}
{107}{}{Rrr ?}
{108}{}{Suis-moi et tu le sauras. Ou en d'autres termes, suis-moi et tu vivras, imbécile !}
{109}{}{Alors si je n'y vais pas, je meurs ? Ca a l'air formel.}
{110}{}{Tu as su me convaincre. C'est parti !}
{111}{}{Je ne pense pas.}
{112}{}{Ne commence pas ce que tu ne peux pas terminer, imbécile !}
{113}{}{Parfait !}
{114}{}{Tu ne devrais pas jouer avec Lady Jain ou les Enfants.}
{115}{}{Tu ne devrais pas insulter ce que tu ne peux pas tuer. Bon maintenant, que veux-tu : venir avec moi et vivre ou rester ici et mourir ?}
{116}{}{Je viens !}
{117}{}{Oublie ça.}
{118}{}{Mon dieu ! Les mutants peuvent bien plaisanter, non ?}
{119}{}{Si je continue à te sentir, je vais tomber comme une mouche !}
{120}{}{Imbécile ! Alors tu viens ou tu restes ici ?}
{121}{}{Euh... Venir !}
{122}{}{Euh... Moi rester !}
{123}{}{Ne m'agace pas avec tes hésitations ! Que décides-tu, humain ?}
{124}{}{Je viens avec toi. Allons-y.}
{125}{}{Oublie ça.}
{126}{}{Comment oses-tu me pousser ?! Personne ne me dit ce que j'ai à faire !}
{127}{}{Quelle insolence ! Tu vas mourir !}
{128}{}{Ne m'agace pas avec tes plaisanteries ! Que décides-tu, humain ?}
{129}{}{Je viens avec toi. Allons-y.}
{130}{}{Oublie ça.}
{131}{}{Ne me pousse pas. J'essaie de me concentrer.}
{132}{}{Le mutant t'ignore.}
