{100}{}{Voici un Goule rayonnant.}
{101}{}{Le Goule t'ignore.}
{102}{}{Le liquide ne coule plus. Sans ce liquide, nous allons tous mourir.}
#
# Sduibek, Fallout Fixt:
#
{103}{}{Tu nous a tous condamné.}
{104}{}{Tu vas payer pour tes actions, avec ton sang...}
{105}{}{L'écoulement s'est arrêté. Tout comme ta vie dans peu de temps.}
