{100}{}{A l'Ouest, tu vois une lumière naturelle. Pour la première fois de ta vie, tu vois le monde extérieur.}
{101}{}{A l'Ouest, tu vois un ciel étoilé. Pour la première fois de ta vie, tu vois le monde extérieur.}
