{100}{}{Voici un citoyen de l'Abri 13.}
{101}{}{A quoi ressemble le monde extérieur ?}
{102}{}{Tu dois avoir du courage pour t'aventurer hors de l'Abri.}
{103}{}{Le Dirigeant dit que le monde extérieur est dangereux.}
{104}{}{Fais attention à toi une fois dehors.}
{105}{}{N'oublie pas d'aller consulter le médecin si tu te blesses.}
{106}{}{Le Dirigeant veille à ce que tous les habitants de l'Abri soient bien soignés.}
