{100}{}{Voici un membre des Enfants de la Cathédrale.}
{101}{}{Je ne parle pas aux âmes païennes comme toi.}
{102}{}{Ton rapport, VanHagan.}
{103}{}{Le Maître est satisfait de tes progrès mais ses désirs sont grands et le temps est compté.}
{104}{}{Le Maître devrait savoir que nous manquons de matières premières. Nous ne pouvons pas créer de soldats sans stock suffisant.}
{105}{}{Il est conscient de tes problèmes. Il tente en ce moment même d'y remédier.}
{106}{}{Parle-moi de ses plans. Si nous voulons que l'Unité soit un succès, nous allons devoir coordonner nos activités.}
{107}{}{Le Maître a entendu parler d'un Abri habité, jusque-là inconnu. Grâce à ces matières premières, nous pourrons former une force immense. Selon le logiciel de prédiction, cet Abri contient le nombre d'habitants qu'il nous faut pour réussir.}
{108}{}{Excellent. C'est une nouvelle imprévue. Les habitants sont-ils contaminés ?}
{109}{}{Oh, c'est ce qu'il y a de plus intéressant. A en voir leur représentant, ils sont sains. De pure souche.}
{110}{}{Oh, c'est passionnant. Quel est cet Abri que nous allons piller ?}
{111}{}{L'Abri 13. Et nous devrions en disposer bientôt. Très bientôt.}
{112}{}{ points d'expérience pour avoir entendu toute la conversation au sujet de ton Abri.}
