{100}{}{Cette partie du sol a quelque chose d'étrange.}
{101}{}{Tu ne remarques rien d'anormal.}
{102}{}{Une alarme retentit au loin.}
{103}{}{Une sorte de détecteur se trouve à tes pieds.}
{104}{}{Tu désarmes le détecteur.}
{105}{}{Tu ne parviens pas à désarmer le détecteur.}
