{100}{}{Sur la porte, tu remarques un écriteau indiquant que l'ascenseur est en panne.}
{101}{}{Sur la porte, tu vois un écriteau indiquant que l'ascenseur est en panne.}
{102}{}{Un écriteau porte l'inscription suivante : Attention - cage d'ascenseur en construction. Veuillez emprunter un autre ascenseur.}
