{100}{}{Voici Vree.}
{101}{Vree00}{Désolée. Tu déranges ma méditation. Pars, je te prie.}
{102}{}{Pardon. Je reviendrai une autre fois.}
{103}{}{Je reviendrai.}
{104}{}{COmment pourrais-je connaître ton emploi du temps.}
{105}{}{Hein ?}
{106}{Vree01}{Ne parle pas si fort. Faut-il qu'un des Frères t'apprenne les bonnes manières.}
{107}{}{Pardon.}
{108}{}{Ouais, d'accord. C'est comme tu le sens.}
{109}{}{Oh, j'ai peur.}
{110}{Vree02}{Salut à toi. Belle journée pour apprendre. Puis-je t'aider ?}
{111}{}{Je sais que t'es le Grand Scribe, mais qu'est-ce que ça veut dire ?}
{112}{}{J'ai besoin de quelques informations techniques.}
{113}{}{Euh...}
{114}{Vree03}{Je consigne le savoir de nos ancêtres pour les générations futures.}
{115}{}{Intéressant. Donc, tu sais des trucs.}
{116}{Vree03a}{Oui. Je suppose qu'on peut dire que je sais "des trucs".}
{117}{Vree17}{Que puis-je faire pour toi ?}
{118}{Vree17a}{Parle.}
{119}{}{J'ai une puce d'eau à faire réparer. Tu peux m'aider ?}
{120}{}{Je voudrais des informations sur les armes fabriquées ici.}
{121}{}{J'ai entendu parler des holodisques. Comment je peux les lire ?}
{122}{}{Comment je peux empêcher l'empoisonnement par radiations ?}
{123}{}{Qu'est-ce qui provoque toutes les mutations ?}
{124}{Vree18}{Demande aux chevaliers. Ils te montreront l'un des derniers pistolets laser de ma conception.}
{125}{}{Merci !}
{126}{}{J'ai une autre question...}
{127}{Vree19}{Tu es encore incapable de faire bon usage du savoir sacré.}
{128}{Vree21}{Pour lire les disques, sers-toi de ton Pip-Boy 2000. Il suffit d'insérer le disque dans le lecteur. Si tu sais te servir d'un ordinateur, tu dois pouvoir numériser les données.}
{129}{}{Où je peux apprendre à me servir d'un ordinateur ?}
{130}{}{Merci.}
{131}{}{Je peux poser encore une question ?}
{132}{Vree22}{La Confrérie offre des cours automatisés. Attends, je vais te montrer.}
{133}{Vree23}{Sers-toi de ce terminal pour apprendre les rudiments informatiques.}
{134}{Vree24}{Tu ne m'as pas l'air d'une lumière ! Tu portes un lecteur de holodisques au bras.}
{135}{Vree25}{Il te faut des stimulants anti-radiations. J'en ai. Prends-en dès que tu penses être proche d'une zone radioactive.}
{136}{}{Merci !}
{137}{}{Je peux te demander autre chose ?}
{138}{Vree26}{Ne bois pas d'eau qui brille.}
{139}{Vree27}{Avec les armes nucléaires et biogénétiques utilisées pendant la Guerre, c'est même étonnant qu'il n'y ait pas plus de mutations. Mais si on tient bon, tout ira bien.}
{140}{}{Pourquoi dis-tu ça ?}
{141}{}{T'as raison. Ca ira.}
{142}{}{J'ai une autre question...}
{143}{Vree28}{Tous les mutants que j'ai examinés sont stériles : ils ne peuvent pas se reproduire. Si on arrivait à éliminer les sources des mutations, on devrait pouvoir survivre et enterrer tous les mutants !}
{144}{}{Ca m'a tout l'air d'un plan.}
{145}{}{Intéressant cette théorie. Des preuves ?}
{146}{}{J'ai une autre question...}
{147}{Vree29}{Tiens, prends ce holodisque. Tu y trouveras des copies de mes autopsies des cadavres de mutant. C'est évident que pas un mutant ne peut avoir d'enfant.}
{148}{}{Merci.}
{149}{}{Je peux te demander autre chose ?}
{150}{Vree30}{Je peux rien te révéler. Plus tard peut-être, si tu sais te montrer digne de la Confrérie.}
{151}{Vree31}{Je suis sûre que tu n'es pas au bon endroit. S'il te plaît, pars, je suis très occupée.}
{152}{Vree32}{Tu détruiras le savoir qui peut sauver le monde !}
{153}{}{Ouais, à commencer par toi.}
{154}{}{Non. Je combats ceux qui risquent de provoquer une nouvelle guerre nucléaire.}
{155}{Vree33}{Jamais ! La Confrérie veillera à ce que cela n'arrive plus jamais !}
{156}{}{C'est ce que tout le monde dit... sauf toi. Tu sera morte.}
{157}{Vree34}{Que puis-je faire pour toi ?}
{158}{}{J'ai pour toi d'importantes nouvelles sur Cedrick. C'est un traître.}
{159}{}{Qu'est-ce que tu ferais si t'apprenais que la corruption mine la Confrérie ?}
{160}{}{Beuf, ben, euh !}
{161}{Vree35}{Très bien. Je vois que les leçons ont porté.}
{162}{Vree36}{Cedrick ? Il a toujours été un membre loyal de la Confrérie. Je doute que tu comprennes même ce que ça signifie.}
{163}{}{Si, si. Cedrick est un traître et il a l'intention de renverser les chefs.}
{164}{}{Ca se peut.}
{165}{Vree37}{C'est sûr et certain ? Peut-être devrais-tu parler à l'Aîné.}
{166}{Vree38}{Ne m'importune pas avec tes insinuations. Apporte des preuves à l'Aîné, ou tais-toi.}
{167}{Vree39}{Ce qui doit être fait. Eliminer l'hérésie et ses responsables.}
{168}{}{Même s'il s'agissait d'un membre de confiance dans la Confrérie ?}
{169}{}{Et qui se chargerait de l'élimination ?}
{170}{Vree40}{Même dans ce cas. Mais il faudrait des preuves.}
{171}{}{Cedrick est un traître. Il a l'intention de tuer les Anciens.}
{172}{}{J'apporterai la preuve.}
{173}{Vree41}{Alors, apporte ta preuve et nous irons parler à l'Aîné.}
{174}{Vree42}{L'Aîné et Rhombus, bien sûr.}
{175}{Vree43}{Tu as entendu parler de l'Initié disparu ? C'est affreux !}
{176}{}{C'est vrai.}
{177}{}{Ben...}
{178}{Vree44}{Si tu m'aides, tu auras toute ma reconnaissance.}
{179}{Vree45}{Les bonnes actions méritent récompense. Pour ton aide à l'Initié, prends ceci je te prie.}
{180}{Vree46}{Oh, c'est toi. Que veux-tu ?}
{181}{}{Je viens te présenter mes excuses.}
{182}{}{Pardon, j'ai dû me tromper de salle.}
{183}{Vree47}{Merci de tes excuses.}
{184}{Vree47a}{Bonne journée.}
{185}{Vree48}{Ca doit être un problème de fabrication. Nous maîtrisons seulement la théorie et la conception. Demande à un chevalier de t'aider.}
{186}{}{Merci quand même.}
{187}{}{Je peux te demander autre chose ?}
{188}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{189}{Vree201}{Je n'en sais fichtre rien. Mais je pense que ça mérite d'être approfondi.}
{190}{Vree202}{Désolée, ça n'est pas mon rayon. Peut-être que l'un des autres Frères saurait.}
{191}{Vree203}{Gardes ! Gardes !}
{192}{Vree204}{Tu as détruit ma salle !}
{193}{Vree205}{Qu'est-ce qui te prend de toucher à mes affaires ?}
{194}{Vree300}{Qui ? Attends, ce nom me dit quelque chose. Peut-être le chef de certains des mutants.}
{195}{Vree301}{Tu fais sans doute allusion à la dernière guerre nucléaire. La Confrérie fait tout ce qu'elle peut pour rétablir ce qui a été perdu.}
{196}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et fabriqués en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{197}{Vree303}{L'unique salut de cette planète torturée et de ses habitants ! Sans nous, l'humanité court à sa perte.}
{198}{Vree304}{Je l'ignore. Demande à la Fabrique.}
{199}{Vree305}{Il veille à ce que la Confrérie demeure sur la voie de la vertu.}
{200}{Vree306}{Il fait appliquer les désirs de l'Aîné. De force, s'il le faut.}
{300}{}{Intéressant.}
{301}{}{Ca devrait faire l'affaire.}
{302}{}{Ca devrait être bon.}
{303}{}{Bien.}
{304}{}{Je savais que ça marcherait.}
{305}{}{Redonne-moi la formule.}
{306}{}{Mauvais algorithme. C'est impossible. L'ordinateur déboîte !}
{307}{}{Ca y est.}
{308}{}{Bon, alors si on fait ça... oui, ça devrait marcher.}
{400}{}{Utilise ce terminal pour améliorer tes compétences informatiques.}
{401}{}{La leçon se termine six heures plus tard. Tu meurs de fatigue.}



{980}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}


#
# Vree Tell-Me-Abouts
#


{1000}{}{Maître}
{1001}{}{Guerre}
{1002}{}{Disques}
{1003}{}{Confrérie}
{1004}{}{Puce}
{1005}{}{Ancien}
{1006}{}{Rhombus}
{1007}{}{Exode}
{1008}{}{Armée}
{1009}{}{Marchands}
{1010}{}{Caravanes}
{1011}{}{Centre}
{1012}{}{Cathédrale}
{1013}{}{Initié}
{1014}{}{Scribe}
{1015}{}{Chevalier}
{1016}{}{Paladin}
{1017}{}{Holodisque}
{1018}{}{Holodisque}
{1019}{}{Holodisque}
{1020}{}{Holodisque}
{1021}{}{Holodisque}


{1100}{Vree300}{Qui ? Attends, ce nom me dit quelque chose. Peut-être le chef de certains des mutants.}
{1101}{Vree301}{Tu fais sans doute allusion à la dernière guerre nucléaire. La Confrérie fait tout ce qu'elle peut pour rétablir ce qui a été perdu.}
{1102}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et fabriqués en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{1103}{Vree303}{L'unique salut de cette planète torturée et de ses habitants ! Sans nous, l'humanité court à sa perte.}
{1104}{Vree304}{Je l'ignore. Demande à la Fabrique.}
{1105}{Vree305}{Il veille à ce que la Confrérie demeure sur la voie de la vertu.}
{1106}{Vree306}{Il fait appliquer les désirs de l'Aîné. De force, s'il le faut.}
{1107}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1108}{Vree201}{Je n'en sais fichtre rien. Mais je pense que ça mérite d'être approfondi.}
{1109}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1110}{Vree201}{Je n'en sais fichtre rien. Mais je pense que ça mérite d'être approfondi.}
{1111}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1112}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1113}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1114}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1115}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1116}{Vree200}{S'il te plaît, adresse-toi à un autre scribe. J'essaie de finir ces rapports pour les autres Anciens.}
{1117}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{1118}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{1119}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{1120}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}
{1121}{Vree302}{Ce sont des dispositifs de stockage à haute densité, à lecture laser et en cristal. Chacun peut contenir plus de 4000 giga-octets d'informations.}

