{100}{}{Voici un conducteur de caravane.}
{101}{}{Salut, si tu cherches du travail dans l'une de nos caravanes, va voir le marchand en chef dans ce bâtiment, à l'Est.}
{102}{}{Excuse-moi, mais tu dois aller voir le Marchand en chef.}
{103}{}{Bien, tu as l'autorisation. Je savais qu'il n'y aurait pas de problème. Elle est si débordée depuis quelque temps, surtout depuis que Daren Hightower s'enferme dans son bureau. C'est un homme étrange. Nos départs se font d'habitude tous les cinq jours. Le 1er, le 5, le 10, le 15, le 20 et le 25 de chaque mois. En ce moment, nous n'allons qu'à Dépôtville et au Cimetière de LA.}
{104}{}{Alors, quel est le salaire ?}
{105}{}{Hmm.}
{106}{}{Le salaire est de 200 caps. Ce n'est pas énorme, mais les départs sont fréquents et nos itinéraires ne sont pas très dangereux. Bien sûr, c'est 200 à l'aller et 200 au retour, m'enfin... on t'oblige pas à faire les deux trajets. }
{107}{}{Nous partons aujourd'hui. Ca t'intéresse ?}
{108}{}{Nous partons en }
{109}{}{Vide}
{110}{}{}
{111}{}{. Ca t'intéresse ?}
{112}{}{Je vais quand même te donner du travail, même si... tant pis. Ca t'intéresse ?}
{113}{}{Bien sûr.}
{114}{}{Non.}
{115}{}{Peut-être.}
{116}{}{Ouais ouais.}
{117}{}{Gné ?}
{118}{}{Oh, d'accord. Pas de problème. Mais préviens-moi si tu changes d'avis.}
{119}{}{J'aimerais que tu te décides.}
{120}{}{Eh bien, reviens si tu décides de travailler pour nous. Nous partons le 1er, le 5, et ainsi de suite. Au revoir.}
{121}{}{Excuse-moi, mais je ne peux pas t'engager tant que tu n'es pas capable de communiquer correctement avec le reste de l'équipe.}
{122}{}{Reviens quand tu te sentiras mieux.}
{123}{}{Hé, tu te sens bien ? Tu devrais aller manger quelque chose. Mais ne va pas chez Bob...}
{124}{}{Va te faire voir ailleurs !}
{125}{}{Mais pourquoi as-tu fait ça ? Au voleur ! Tu me déçois...}
{126}{}{Parce que je suis une vilaine créature toute verte venue de l'espace !}
{127}{}{Je n'en avais pas l'intention mais je meurs de faim et j'ai des enfants à nourrir.}
{128}{}{Je vais te découper le coeur avec une cuillère ! }
{129}{}{(Reddition)}
{130}{}{(Attaque)}
{131}{}{J'ai essayé de t'aider, mais je crois qu'on ne peut rien pour certaines personnes. Excuse-moi de te dire ça, mais nous allons devoir employer la manière forte.}
{132}{}{Je comprends, mais cela ne justifie pas ton acte. Je dois te demander de partir. Nous ne pouvons pas engager des gens incapables de se contrôler.}
{133}{}{Mais à quoi tu t'attendais ? Gardes !}
{134}{}{Je regrette mais parfois un petit séjour en prison peut se révéler bénéfique. Gardes ! Essayez de ne pas la tuer. Te rendras-tu à mes gardes ?}
{135}{}{On se retrouvera en enfer !}
{136}{}{Oui. Pardon.}
{137}{}{Quoi ? As-tu encore l'intention de te battre ?}
{138}{}{Je regrette mais tu dois partir tout de suite ou j'appelle la police !}
{139}{}{Gardes ! Police !}
{140}{}{Je crois que tu devrais partir...}
{141}{}{Je regrette mais je n'ai pas le droit de t'engager.}
{142}{}{S'il te plaît, tu ne me facilites pas la tâche.}
{143}{}{Va t'en, s'il te plaît.}
{144}{}{Mystérieux, mais tu n'es pas mon genre.}
{145}{}{Parfait ! Le salaire sera de 200 caps. Quel itinéraire préfères-tu ?}
{146}{}{Fabuleux. Reviens en }
{147}{}{le 1er}
{148}{}{le 5}
{149}{}{le 10}
{150}{}{le 15}
{151}{}{le 20}
{152}{}{le 25}
{153}{}{. Tu partiras à ce moment-là. Comme toujours, le salaire sera de 200 caps.}
{154}{}{D'accord.}
{155}{}{Excuse-moi, je ne peux pas attendre.}
{156}{}{C'est une tragédie. Nous avons perdu toute la caravane, et tu as survécu ? Ca n'aurait pas dû arriver. Je ne sais pas ce qui s'est passé là-bas, mais nous ne pouvons pas te garder. Excuse-moi.}
{157}{}{Dépôtville}
{158}{}{Cimetière de L.A.}
{159}{}{Hmm, pas tout de suite. Peut-être une autre fois.}
{160}{}{Incroyable, je vais chercher le reste de l'équipe.}
{161}{}{Génial.}
{162}{}{Vas-y. Bonne chance !}
{163}{}{Essaie d'éviter les ennuis, et surtout, ne les cherche pas.}
{164}{}{Attention, je n'aime pas le Cimetière L.A.. Cet endroit me donne la chair de poule.}
{165}{}{C'est bien. Ces routes noires sont étranges, mais elles sont parfaites pour circuler.}
{166}{}{Je crois qu'il y a des bandes étranges, là-bas. Ne parle pas à n'importe qui.}
{167}{}{Génial. Dépôtville est un endroit correct.}
{168}{}{Oh, dis bonjour à ce... Kill... comment déjà ? J'ai oublié son nom, mais c'est un type bien. Je me demande comment il va.}
{169}{}{C'est un endroit intéressant. J'ai entendu dire qu'il y avait là-bas une sorte de médecin qui réveille les morts, ou quelque chose comme ça.}
{170}{}{Mais pourquoi as-tu quitté la dernière caravane ? Il n'est rien arrivé, mais tu n'aurais pas dû.}
{171}{}{Puis-je avoir une autre chance ?}
{172}{}{Rien.}
{173}{}{Merde !}
{174}{}{Roo Rrr heu ?}
{175}{}{Grr...}
{176}{}{Excuse-moi, mais tu es vraiment quelqu'un de décevant. Tu n'as pas l'air d'être très responsable, et cela ne convient pas au travail que nous demandons.}
{177}{}{Pourquoi ?}
{178}{}{Tu ne devrais pas.}
{179}{}{Parce que sinon je vais te trouer la cervelle.}
{180}{}{J'avais mieux à faire que de suivre cette fichue caravane.}
{181}{}{Je ne savais pas que je n'avais pas le droit de partir. Tout était en ordre.}
{182}{}{Je vois... tu as pris des stimulants. Eh bien, mène ta vie comme tu l'entends.}
{183}{}{Ca me fait de la peine que tu le prennes comme ça.}
{184}{}{Ca m'étonne que tu n'aies jamais travaillé dans une caravane auparavant, mais je ne pense que c'est pas un problème... alors, d'accord. Je vais te donner une autre chance.}
{185}{}{Tu as fait du bon travail ! Veux-tu travailler dans une autre caravane ?}
{186}{}{Bien sûr.}
{187}{}{Non.}
{188}{}{Peut-être.}
{189}{}{Eh... !}
{190}{}{Euh...}
{191}{}{Nous partons aujourd'hui. Ca te convient ?}
{192}{}{Oui.}
{193}{}{Non !}
{194}{}{Pfa !}
{195}{}{Sinon, je confierai ce travail à quelqu'un d'autre, ne t'inquiète pas. Tu n'as aucune obligation envers moi... tant que tu n'es pas engagé avec une caravane, d'accord ?}
{196}{}{Tu es un peu en avance. La prochaine caravane ne part pas avant }
{197}{}{le 1er}
{198}{}{le 5}
{199}{}{le 10}
{200}{}{le 15}
{201}{}{le 20}
{202}{}{le 25}
{203}{}{. Reviens à ce moment-là si ce travail t'intéresse toujours. }
{204}{}{janvier }
{205}{}{février }
{206}{}{mars }
{207}{}{avril }
{208}{}{mai }
{209}{}{juin }
{210}{}{juillet }
{211}{}{août }
{212}{}{septembre }
{213}{}{octobre }
{214}{}{novembre }
{215}{}{décembre }

# invasion - WastelandGhost@RestorationMOD
{300}{}{Bien, t'as le feu vert. Je savais que ce serait pas un problème. Elle est débordée depuis que Daren Hightower s'est mis à fureter dans son bureau. C'est un homme étrange. Nous partons tous les 5 jours. c'est-à-dire le 1er, le 5, le 10, le 15, le 20 et le 25 du mois. Nous n'allons qu'à Dépotville. Il y a des rumeurs selon lesquelles des mutants auraient envahi le Cimetière de L.A., c'est pour ça qu'on y va plus.}
