{100}{}{Voici un employé des Marchands d'Eau.}
{101}{}{Adresse-toi à Martha si tu veux du travail.}
{102}{}{Ces périples en caravanes deviennent trop dangereux.}
{103}{}{Hé, t'aurais pas des cigarettes ?}
{104}{}{J'ai besoin de prendre un bain.}
{105}{}{Va t'en, s'il te plaît.}
{106}{}{Fais attention à toi. On ne paie pas nos gardes à ne rien faire.}
{107}{}{Va voir quelqu'un d'autre si tu veux du travail.}
