{100}{}{Ca ne va pas du tout.}
{101}{}{Allons-y.}
{102}{}{Le mécanisme de mise à feu n'arrête pas de se bloquer.}
{103}{}{C'est beaucoup mieux.}
{104}{}{Presque.}
{105}{}{Ca va prendre un certain temps.}
{106}{}{Voilà d'où vient le problème !}
{107}{}{John, je crois que j'ai trouvé d'où vient le problème.}
{108}{}{Bon sang !}
{109}{}{Merde !}
{110}{}{C'est de ma faute !}
{111}{}{Je vais bien.}
{112}{}{Ca fait mal.}
{113}{}{C'est ce que je voulais.}
{114}{}{Mais pourquoi ça se produit tout le temps ?}
{115}{}{Mon oeil !}
{116}{}{Tu n'es pas un chevalier.}
{117}{}{Je dois parler à un chevalier.}
{118}{}{Je ne comprends pas, les cellules n'arrêtent pas de se décharger.}
{119}{}{Tu devrais reculer, ça pourrait être dangereux.}
{120}{}{Ne me dérange pas, s'il te plaît.}
{121}{}{Regarde où tu mets les pieds.}
{122}{}{Tu cherches ton chemin ?}
{123}{}{Excuse-moi, je ne peux pas parler pour l'instant.}
