{100}{}{Voici un garde des Marchands d'Eau.}
{101}{}{Arrête-toi. Seuls les marchands sont autorisés à s'approcher du château d'eau et des pompes.}
{102}{}{Tu n'as pas le droit d'être ici, va t'en !}
{103}{}{L'accès à cette zone est restreint ! Eloigne-toi des pompes.}
{104}{}{Va t'en si tu ne veux pas d'ennuis.}
{105}{}{Dernier avertissement ! Va t'en.}
{106}{}{Tu ferais bien de t'en aller avant qu'il ne soit trop tard.}
{107}{}{Tu n'as plus que quelques secondes pour partir ou mourir.}
{108}{}{T'as compris ? Fiche le camp immédiatement !}
{109}{}{C'est comme ça.}
{110}{}{Rien n'est facile.}
{111}{}{Tu n'en fais qu'à ta tête.}
{112}{}{Donne-lui une leçon.}
{113}{}{Donne-lui une leçon.}
{114}{}{Seuls les marchands sont autorisés à s'approcher du château d'eau et des pompes.}
{115}{}{Tu devrais t'en aller.}
{116}{}{Nous ne faisons confiance à personne et surtout pas à toi.}
{117}{}{Je te conseille de ne pas t'approcher des pompes.}
{118}{}{Si tu as besoin de quelque chose, rends-toi à la Salle des Marchands.}
{119}{}{Nous allons tirer. N'y pense même pas.}
{120}{}{Nous ne laisserons personne mettre en danger l'organe vital du Centre.}
