{100}{}{Voici Zack.}
{101}{}{Voici un Contrebandier.}
{102}{}{Bonjour, je m'appelle Zack. Tu veux acheter des armes ? Laisse-moi voir ce que tu as.}
{103}{}{Non.}
{104}{}{D'accord.}
{105}{}{Peux-tu me faire une remise ?}
{106}{}{Tu veux acheter des armes ? Laisse-moi voir ce que tu as.}
{107}{}{Excuse-moi de te déranger.}
{108}{}{C'est agréable de traiter avec toi.}
{109}{}{}
{110}{}{D'accord. Reviens si tu as besoin de quelque chose.}
{111}{}{Tu ferais bien de te décider rapidement. Es-tu ici pour acheter du matériel ou juste pour te faire descendre ?}
{112}{}{Tu as un sérieux problème.}
{113}{}{Je pourrais peut-être utiliser du matériel après tout.}
{114}{}{Bon sang, mais qu'est-ce que tu fais ici ?!}
{115}{}{Rien.}
{116}{}{Certainement.}
{117}{}{Ouais, à moins que Gabriel ne soit d'accord, tu vas devoir payer le prix fort comme tout le monde.}
{118}{}{Je ne sais rien à ce sujet.}
{119}{}{Montre-moi ce que tu as.}
{120}{}{Formidable ! Montre-moi ce que tu as.}
{121}{}{Je reviendrai plus tard pour cette remise.}
{122}{}{Puis-je avoir une meilleure remise ?}
{123}{}{Désolé mais je t'ai fait la meilleure remise qui soit.}

# Fo1in2
   {998}{}{Zack, ton stuff est de super qualité, mais je cherche quelque chose *d'encore plus* spécial..}
   {999}{}{Est-ce qu'on peut parler de cet équipement *encore plus* spécial à nouveau ?}
   
{1000}{}{Désolé, mais c'est tout ce que j'ai pour le moment.}
{1001}{}{Je pourrais essayer de trouver du matériel encore meilleur, maintenant que les Griffemorts nous laissent tranquille. Ça va prendre un moment, par contre.}
   {1010}{}{Il y a quelque chose que je puis-je faire pour aider ?}
   
{1100}{}{Payer des nouveau mercenaires, ce n'est pas grauit. Si tu veux accélérer les choses, un investissement de 10000 caps pourrait éventuellement le faire.}
   {1110}{}{Je n'ai pas du tout cet argent.}
   {1120}{}{J'espère que ça vaudra le coup, Zack ! [Payer 10 000 caps]}
   {1130}{}{Ooof. Peut-être plus tard.}

{1200}{}{Reviens me voir quand tu auras l'argent.}
{1300}{}{Je ne peux pas te promettre quoi que ce soit. Tu dois revenir de temps en temps, parce que ce genre d'équipement se vend extrêmement bien.}
{1400}{}{D'accord.}
