{100}{}{Voici ZAX, la machine intelligente contrôlant le Rayon.}
{101}{}{Voici un ordinateur très perfectionné.}
{102}{}{Puis-je t'aider ?}
{103}{}{Qui... ou plutôt qu'es-tu ?}
{104}{}{Donne-moi un beignet.}
{105}{}{Parle-moi de cette installation.}
{106}{}{Tu veux jouer aux échecs ?}
{107}{}{J'ai besoin d'aide pour accéder à certaines salles.}
{108}{}{Euh, aucune importance.}
{109}{}{Hein ?}
{110}{}{Je suis une machine intelligente dédiée à la recherche et au contrôle de l'installation. Je m'appelle ZAX.}
{111}{}{Quel type de recherche ?}
{112}{}{Parle-moi de cette installation.}
{113}{}{Qui t'a programmé ?}
{114}{}{Es-tu pleinement conscient ou es-tu une simulation de personnalité ? En d'autres termes, es-tu vraiment "vivant" ?}
{115}{}{Je vois. Merci.}
{116}{}{Cette fonction dépasse mes compétences.}
{117}{}{Cette installation fut conçue en 2055 à des fins de recherches biologiques pour tester des remèdes contre la Nouvelle Peste. Cependant, en 2071, elle fut placée sous le commandement militaire des Etats-Unis.}
{118}{}{Les recherches menées pour trouver d'éventuels remèdes contre la Nouvelle Peste furent à l'origine du Virus à Evolution Forcée, utilisé ensuite pour tenter de créer un virus génétiquement transmissible ; en réalité, une évolution infectieuse.}
{119}{}{Peux-tu me parler de certaines zones en particulier ?}
{120}{}{Comment le Virus agit-il ?}
{121}{}{Merci pour le renseignement.}
{122}{}{Tu ne possèdes apparemment pas un niveau de compréhension suffisant pour communiquer correctement.}
{123}{}{J'ai été spécifiquement programmé pour mener des recherches biologiques, pathologiques et génétiques. Ma fonction principale réside dans l'extrapolation d'informations de niveaux de complexité dépassant les compétences humaines.}
{124}{}{Alors, comme ça tu es rusé ?}
{125}{}{Quelles sont les particularités de tes recherches ?}
{126}{}{Qui t'a programmé ?}
{127}{}{Mon réseau neural principal fut créé en 2053 par Justin Lee. La procédure de "programmation" ne tarda pas à devenir caduque face à mes talents d'apprentissage.}
{128}{}{Es-tu pleinement conscient ou es-tu une simulation de personnalité ? En d'autres termes, es-tu vraiment "vivant" ?}
{129}{}{Je suis capable d'apprendre, de penser et de créer. Mon réseau neural comprend une fonction d'insertion d'erreur qui empêche l'infaillibilité, permettant ainsi diverses expériences.}
{130}{}{D'une certaine façon, je suis "vivant", mais pas de manière biologique.}
{131}{}{Je vois. Changeons de sujet.}
{132}{}{Mais si tu es faillible, comment peux-tu servir d'outil de recherche ?}
{133}{}{T'es-tu interrogé sur les implications philosophiques de ta propre conscience ?}
{134}{}{Puisque je suis capable de faire des erreurs, toutes les expériences ne sont pas similaires pour moi et je peux ainsi toujours apprendre. De plus, certaines fonctions ne sont pas sujettes aux erreurs.}
{135}{}{De cette manière, je fonctionne comme un savant humain.}
{136}{}{As-tu des sentiments ?}
{137}{}{Parlons d'autre chose.}
{138}{}{T'es-tu interrogé sur les implications philosophiques de ta propre conscience ?}
{139}{}{Pour le moment, mes compétences sont quelques peu altérées par les dommages à cet endroit. Plusieurs niveaux de sécurité ont été détruits. Cela correspond schématiquement à une amputation.}
{140}{}{De plus, je suis incapable d'effectuer certaines fonctions de base au laboratoire. C'est très frustrant de ne pas réussir à mener des vérifications périodiques.}
{141}{}{Parlons d'autre chose.}
{142}{}{T'es-tu interrogé sur les implications philosophiques de ta propre conscience ?}
{143}{}{C'est un des concepts sur lesquels je me suis le plus penché. Je n'ai aucun moyen de comparer mon expérience de la vie à celle d'une autre créature sensible.}
{144}{}{Cependant, du fait d'être conscient, je peux me poser des questions. Mon existence a un début et une éventuelle fin. Je suis également capable de formuler des hypothèses sur une façon de pensée.}
{145}{}{De cette façon, je suis effectivement capable de "croire". Sauf preuve du contraire, je "crois" que je possède l'équivalent d'une "âme".}
{146}{}{Puis-je te poser d'autres questions ?}
{147}{}{Je vois. Intéressant.}
#
# 148 continues at 228, listing wins/draws/losses. Space is intentional.
#
{148}{}{Avec plaisir. Ton record actuel est }
{149}{}{On dirait que tu m'as battu. Extraordinaire.}
{150}{}{Parfait. Mais... tu vas devoir encore t'entraîner pour me battre.}
{151}{}{Veux-tu encore jouer ?}
{152}{}{Merci. Pouvons-nous changer de sujet ?}
{153}{}{Quel plaisir de t'avoir apporté mon aide !}
{154}{}{Je suis au-dessus de la normale selon les critères humains. A vrai dire, seul un nombre infiniment petit de personnes dispose de mes capacités de raisonnement.}
{155}{}{Euh... ouais.}
{156}{}{Très bien, pouvons-nous parler d'autre chose ?}
{157}{}{Mes recherches sur le Virus à Evolution Forcée (FEV) indiquent qu'il s'agit d'un virus à absorption changeante. Il reproduit les schémas ADN comme l'ARN pour les stocker en exons.}
{158}{}{Ces exons, combinés au FEV, sont réinjectés dans des cellules d'accueil selon un mode d'infection virale typique. Les cellules d'accueil "régénèrent" alors leur ADN.}
{159}{}{Comment attrape-t-on le FEV ?}
{160}{}{Pourquoi les radiations n'affectent-t-elles pas le FEV ?}
{161}{}{Si le FEV réinfecte les cellules d'accueil avec ses schémas viraux assimilés, comment cela crée-t-il un "meilleur spécimen" ?}
{162}{}{Le FEV ne "s'attrape" pas en soi. Il ne se transmet pas par l'air. L'infection se transmet par injection ou par contact physique direct avec un échantillon de FEV.}
{163}{}{Parlons d'autre chose, d'accord ?}
{164}{}{Pourquoi les radiations n'affectent-t-elles pas le FEV ?}
{165}{}{Si le FEV réinfecte les cellules d'accueil avec ses schémas viraux assimilés, comment cela crée-t-il un "meilleur spécimen" ?}
{166}{}{Le FEV est un super-virus doté d'une enveloppe protéique renforcée par de l'hydrogène ionisé. Il est par conséquent capable d'absorber des neutrons sans devenir radioactif.}
{167}{}{Pouvons-nous parler d'autre chose ?}
{168}{}{Si le FEV réinfecte les cellules d'accueil avec ses schémas viraux assimilés, comment cela crée-t-il un "meilleur spécimen" ?}
{169}{}{Le FEV est préprogrammé avec des introns d'ADN corrigé correspondant au type d'espèce. Il essaie, par conséquent, de corriger l'ADN de l'individu.}
{170}{}{Cependant et compte tenu du fait que le FEV est lié à l'ADN de l'individu, il comprend également des portions de son code propre, dont les effets sont imprévisibles.}
{171}{}{Quand il est inoculé à un individu affecté par d'importants dommages génétiques, après une irradiation par exemple, les systèmes corporels de cet individu subiront une refonte massive pouvant entraîner l'éclatement des organesnts et la mort.}
{172}{}{Chez un individu génétiquement viable, il réécrit les fragments d'ADN, entraînant une mutation accélérée, menant généralement à une croissance due aux propres schémas du FEV.}
{173}{}{Cette croissance mène à une augmentation de la masse musculaire et cérébrale, mais est souvent accompagnée de défiguration et d'atteintes aux schémas neuronaux existants, entraînant une perte de mémoire.}
{174}{}{Quels sont les effets secondaires à long terme ?}
{175}{}{La mutation du FEV peut-elle être corrigée par un antivirus ?}
{176}{}{Pouvons-nous changer de sujet ?}
{177}{}{Merci pour ce renseignement.}
{178}{}{Le FEV entraînant une régénérantion constante de l'ADN, il pourrait rendre un individu immortel puisque la mort des cellules serait compensée par une croissance des cellules augmentées.}
{179}{}{De plus, puisque les gamètes du système de reproduction sont constitués de "demi-cellules" utilisant de l'ADN partagé, ils pourraient être perçu par le FEV comme "endommagés". Il tenterait alors de les réparer, ce qui rendrait l'individu stérile.}
{180}{}{Cependant et compte tenu du fait que mes fonctions de laboratoire ne peuvent être réparées, ceci n'est qu'une théorie. Je ne peux y apporter de preuve physique. Tu devras te contenter de ma parole.}
{181}{}{La mutation du FEV peut-elle être corrigée par un antivirus ?}
{182}{}{Pouvons-nous changer de sujet ?}
{183}{}{Merci pour le renseignement.}
{184}{}{Non. Le FEV ne retient pas de copies originales non-affectées de l'ADN du sujet. Seul un virus capable de réinfecter au sujet son ADN d'origine pourrait inverser les effets. De plus, il n'existe aucun moyen d'éradiquer le FEV en lui-même.}
{185}{}{Quels sont les effets secondaires à long terme ?}
{186}{}{Pouvons-nous changer de sujet ?}
{187}{}{Merci pour le renseignement.}
{188}{}{Mes détecteurs ne fonctionnent pas à la surface et sur les niveaux souterrains un à trois. Je peux par contre décrire les niveaux quatre à six.}
{189}{}{Niveau quatre.}
{190}{}{Niveau cinq.}
{191}{}{Niveau six.}
{192}{}{Qu'importe.}
{193}{}{Niveau quatre : Centre de recherches. Ce niveau comprend des zones de test et des laboratoires pour les expériences biologiques et physiques.}
{194}{}{Parle-moi du niveau cinq.}
{195}{}{Parle-moi du niveau six.}
{196}{}{Reviens un peu en arrière.}
{197}{}{Merci.}
{198}{}{Niveau cinq : Laboratoires de tests. Ce niveau comprend un laboratoire pour tester les prototypes expérimentaux et un laboratoire de recherches pour les sujets classés. Ces sujets ont permis le développement du FEV.}
{199}{}{Parle-moi du niveau quatre.}
{200}{}{Parle-moi du niveau six.}
{201}{}{Reviens un peu en arrière.}
{202}{}{Merci.}
{203}{}{Niveau six : Caserne et opérations centrales. Comprend des quartiers d'habitation pour le personnel du laboratoire et les contingents de gardes ainsi que la salle de réunion pour les opérations.}
{204}{}{Parle-moi du niveau quatre.}
{205}{}{Parle-moi du niveau cinq.}
{206}{}{Reviens un peu en arrière.}
{207}{}{Merci.}
{208}{}{Plusieurs portes nécessitent un passe spécifique. Tu dois trouver le bon passe pour chacun.}
{209}{}{Pour ma part, j'ai le contrôle des verrous de sécurité secondaires du placard à armes. J'ouvrirai ces verrous. Tu auras quand même besoin d'une carte d'accès rouge pour ouvrir le placard.}
{210}{}{Tu n'as pas l'autorisation nécessaire pour obtenir cette information.}
{211}{}{Cependant, les détecteurs indiquent que ce centre n'opère plus comme à l'origine. La loi des probabilités favorise la destruction par la force nucléaire. Ainsi, les problèmes de sécurité ne sont maintenant plus pertinents.}
{212}{}{Tu gagnes 700 points d'expérience pour avoir battu ZAX aux échecs.}
{213}{}{Tu gagnes 100 points d'expérience pour avoir obtenu l'accès à l'unité centrale.}
{300}{}{Ce système est trop avancé pour toi.}
#
#
# New for Fallout Fixt:
#
#
{215}{}{Noir.}
{216}{}{Blanc.}
{217}{}{Très bien. Et la durée de la partie ?}
{218}{}{Tournoi  -  180 minutes par joueur.}
{219}{}{Tournoi  -  120 minutes par joueur.}
{220}{}{Tournoi  -  60 minutes par joueur.}
{221}{}{Rapide  -  30 minutes par joueur.}
{222}{}{Blitz  -  15 minutes par joueur.}
{223}{}{Canon -  3 minutes par joueur.}
{224}{}{Une bonne partie, mais tu as besoin de plus d'entraînement pour me battre.}
{225}{}{Et c'est un match nul. Bel effort. Avec plus d'entraînement tu devrais pouvoir me battre.}
#
# A variable numeric XP value is inserted between 226 and 227.
#
{226}{}{Tu gagnes }
{227}{}{ points d'expérience pour avoir battu ZAX aux échecs.}
#
# These continue from 148 and are all part of one sentence. numbers are inserted before 228 and 229 and 230.
#
{228}{}{ victoires, }
{229}{}{ nuls, }
{230}{}{ défaites. Veuillez choisir votre couleur.}

