#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Burst}
{1}{}{Run Away}
{2}{}{Weapon Pref.}
{3}{}{Distance}
{4}{}{Attack Who}
{5}{}{Chem Use}

{10}{}{Done}
{11}{}{Cancel}

#
# Burst options.
#
{99}{}{Not Applicable.}
{100}{}{Always!}
{101}{}{Sometimes, don't worry about hitting me}
{102}{}{Be sure you won't hit me}
{103}{}{Be careful not to hit me}
{104}{}{Be absolutely sure you won't hit me}

#
# Run away options.
#
{200}{}{Abject coward}
{201}{}{Your finger hurts}
{202}{}{You're bleeding a bit}
{203}{}{Not feeling good}
{204}{}{You need a tourniquet}
{205}{}{Never!}

#
# Weapon pref options.
#
{300}{}{None}
{301}{}{Melee}
{302}{}{Melee then ranged}
{303}{}{Ranged then melee}
{304}{}{Ranged}
{305}{}{Unarmed}

#
# Distance options.
#
{400}{}{Stay close to me}
{401}{}{Charge!}
{402}{}{Snipe the enemy}
{403}{}{On your own}
{404}{}{Stay where you are}

#
# Attack who options.
#
{500}{}{Whomever is attacking me}
{501}{}{The strongest}
{502}{}{The weakest}
{503}{}{Whomever you want}
{504}{}{Whomever is closest}

#
# Chem use options.
#
{600}{}{I'm clean}
{601}{}{Stimpacks when hurt a bit}
{602}{}{Stimpacks when hurt a lot}
{603}{}{Any drug some of the time}
{604}{}{Any drug any time}