#include "..\headers\define.h"

procedure start;
procedure spatial_p_proc;//    script_action == 2


procedure start
begin
	if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
		call spatial_p_proc;
	end
end

procedure spatial_p_proc
begin
	if source_obj == dude_obj then begin
		if ((anim_busy(dude_obj) == 0) or (anim_busy(dude_obj) == 1)) then begin
			script_overrides;
			load_map("mbent.map", 1);
		end
	end
end

