/*

   Brotherhood - Brotherhood Honor Code

   NOTE:
      Proto 195

*/

#include "define.h"

#define NAME                    SCRIPT_CODEDISK

#include "command.h"

procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_p_proc;

procedure use_disk;

#define LVAR_Used          (0)

procedure start begin
end

procedure description_p_proc begin
   call use_disk;
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure use_p_proc begin
   call use_disk;
end

procedure use_disk begin
   script_overrides;
   if (local_var(LVAR_Used) == 1) then begin
      display_msg(mstr(101));
   end
   else begin
      set_local_var(LVAR_Used, 1);
      display_msg(mstr(102));
      set_global_var(GVAR_HONOR_HOLODISK_USED, 1);
      give_xp(100);
   end
end
