/*

   Holodisk for deactivation of the Glow traps
   (Tylier terminal - this is cut content)

*/

#include "..\headers\define.h"

#define NAME                    SCRIPT_SECDISK

#include "..\headers\command.h"

procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_p_proc;

#define LVAR_Used          (0)

procedure start begin
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure description_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure use_p_proc begin
   script_overrides;
   if (local_var(LVAR_Used) == 1) then begin
      display_msg(mstr(101));
   end
   else begin
      display_msg(mstr(102));
      set_global_var(GVAR_SECDISK_HOLODISK_USED, 1);

      set_global_var(GVAR_HOLODISK_ACCESS_CODE, 1); // This is for the Tylier terminal in the Glow - to disable the traps.

      set_local_var(LVAR_Used, 1);
      //rm_obj_from_inven(dude_obj, self_obj);
      display_msg(message_str(SCRIPT_GENCHAT, 103) + "100" + message_str(SCRIPT_GENCHAT, 104));
      give_exp_points(100);
   end
end
