/*

	Hub - Caravan 2

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\MAPNECRO.h"

#define NAME                    SCRIPT_HCARAVN2
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "..\headers\command.h"
#include "..\headers\ModReact.h"

/* Standard Script Procedures */

procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc;
procedure damage_p_proc;

procedure CaravanMorning;
procedure CaravanEvening;
procedure CaravanNight;
procedure SendToWork;
procedure SendToSleep;
procedure WakeUpCall;

variable tmp_hostile;
variable Only_Once := 1;
variable SetDayNight;
variable Sleeping;
variable LastMove;

procedure start begin
	if Only_Once then begin
		Only_Once := 0;
		set_self_team(TEAM_HUB_CARTS_GUARD );
		set_self_ai( AI_MERCHANT );
		call SendToWork;
	end
end

procedure combat
begin
	tmp_hostile := 1;
end

procedure critter_p_proc
begin
	if (tmp_hostile) then begin// This must come FIRST as an if/then/else before "attack dude" type code, otherwise it runs too soon and can override other attack calls
		tmp_hostile := 0;
		attack(dude_obj);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		tmp_hostile := 1;
	end
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	get_reaction
	if ((game_time_hour >= 2200) or (game_time_hour < 600)) then begin
		call CaravanNight;
	end
	else begin
		if (game_time_hour >= 1400) then begin
			call CaravanEvening;
		end
		else begin
			if (game_time_hour >= 600) then begin
				call CaravanMorning;
			end
		end
	end
end

procedure destroy_p_proc
begin
	rm_timer_event(self_obj);

	inc_good_critter
	rm_timer_event(self_obj);
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HGENCVAN, 502));
end

procedure timed_event_p_proc
begin
	if ((game_time_hour >= 600) and (game_time_hour < 700) or ((game_time_hour >= 700) and (game_time_hour < 1800))) then begin
		call SendToWork;
	end
end

procedure damage_p_proc
begin
	if (source_obj == dude_obj) then begin
		set_global_var( GVAR_ENEMY_HUB, 1 );
	end
end

procedure CaravanMorning
begin
	script_overrides;
	float_msg(self_obj, message_str(SCRIPT_HGENCVAN, random(101, 111)), 3);
end

procedure CaravanEvening
begin
	script_overrides;
	float_msg(self_obj, message_str(SCRIPT_HGENCVAN, random(112, 122)), 3);
end

procedure CaravanNight
begin
	variable LVar0 := 0;
	LVar0 := random(1, 3);
	if (LVar0 == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_HGENCVAN, random(201, 202)), 3);
	end
	if (LVar0 == 2) then begin
		float_msg(self_obj, message_str(SCRIPT_HGENCVAN, random(123, 126)), 3);
	end
	if (LVar0 == 3) then begin
		float_msg(self_obj, message_str(SCRIPT_HGENCVAN, 401), 3);
	end
end

procedure SendToWork
begin
	variable LVar0 := 0;
	variable LVar1 := 0;
	LVar0 := 0;
	LVar1 := random(10, 30);
	while(LVar0 == 0) do begin
		LVar0 := random(1, 12);
		if (LVar0 == 1) then begin
			LVar0 := 12718;
		end
		else begin
			if (LVar0 == 2) then begin
				LVar0 := 12915;
			end
			else begin
				if (LVar0 == 3) then begin
					LVar0 := 11514;
				end
				else begin
					if (LVar0 == 4) then begin
						LVar0 := 11914;
					end
					else begin
						if (LVar0 == 5) then begin
							LVar0 := 12120;
						end
						else begin
							if (LVar0 == 6) then begin
								LVar0 := 11720;
							end
							else begin
								if (LVar0 == 7) then begin
									LVar0 := 11518;
								end
								else begin
									if (LVar0 == 8) then begin
										LVar0 := 12520;
									end
									else begin
										if (LVar0 == 9) then begin
											LVar0 := 12313;
										end
										else begin
											if (LVar0 == 10) then begin
												LVar0 := 11716;
											end
											else begin
												if (LVar0 == 11) then begin
													LVar0 := 11712;
												end
												else begin
													if (LVar0 == 12) then begin
														LVar0 := 11721;
													end
												end
											end
										end
									end
								end
							end
						end
					end
				end
			end
		end
		if (LVar0 == LastMove) then begin
			LVar0 := 0;
		end
	end
	LastMove := LVar0;
	reg_anim_func(2, self_obj);
	reg_anim_func(1, 1);
	reg_anim_obj_move_to_tile(self_obj, LVar0, -1);
	reg_anim_func(3, 0);
	add_timer_event(self_obj, game_ticks(LVar1), 1);
end

procedure SendToSleep
begin
	if (Sleeping == 0) then begin
		Sleeping := 1;
		if ((SetDayNight == 1) and (random(0, 100) >= 80)) then begin
			float_msg(self_obj, message_str(SCRIPT_HGENCVAN, 123), 3);
		end
		SetDayNight := 0;
	end
end

procedure WakeUpCall
begin
	if (SetDayNight == 0) then begin
		SetDayNight := 1;
		if not(is_loading_game) then begin    set_obj_visibility(self_obj, 0);    end//  MAKE VISIBLE
		add_timer_event(self_obj, game_ticks(2), 1);
		if ((Sleeping == 1) and (random(0, 100) >= 80)) then begin
			float_msg(self_obj, message_str(SCRIPT_HGENCVAN, 125), 3);
		end
		Sleeping := 0;
	end
end




