{100}{}{Estás viendo a un Supermutante. Está vigilando la cámara.}
{101}{}{Estás viendo a un guardia Supermutante.}
{102}{}{Jeremiah, deberías pasar.}
{103}{}{Circula.}
{104}{}{Muévete más rápido, mensajero.}
{105}{}{¡Los Normales no pueden llevar armas aquí! ¡Deténte e identifícate!}
{106}{}{¡Grrr!}
{107}{}{Uh, lo siento. Ahora me la quito.}
{108}{}{Sólo pasaba por aquí. Aquí no se necesitan identificaciones.}
{109}{}{¡Muere! ¡Muere! ¡Muere! Siempre he querido decir eso.}
{110}{}{No te dirigirás a mí de ese modo. Te castigaré.}
{111}{}{¡Para! ¿Qué haces aquí, "niño"?}
{112}{}{¡Ung!}
{113}{}{Estoy, uh, arreglando algunas cosillas.}
{114}{}{Tengo un asunto importante entre manos. Y tú no tienes derecho a pararme e interrogarme.}
{115}{}{No me hables, grandullón.}
{116}{}{Tu respuesta no me tranquiliza. Habla rápido y claro o asumiré que tus propósitos aquí son siniestros. Te garantizo que no
 te gustará que...}
{117}{}{Uh, no, de verdad que sí. Estoy arreglando algunas cosillas.}
{118}{}{Traigo un mensaje para nuestro jefe.}
{119}{}{Noto la mentira oculta en tus palabras. No te permitirán entrar.
 Y ahora lo que te prometí...}
{120}{}{Puedes pasar, pero la próxima vez, sigue el procedimiento adecuado...}
{121}{}{Vale, gracias. Nos vemos por ahí.}
{122}{}{¿Y qué es eso?}
{123}{}{Te bendigo, hermano.}
{124}{}{Un verdadero seguidor del Maestro habría tenido esos conocimientos. ¡Eres un intruso!}
{125}{}{Circula. No tengo tiempo para preguntas.}
{126}{}{Me estás mosqueando.}
{127}{}{Tengo trabajo que hacer. ¿Y tú?}
{128}{}{Cometes un error viviendo aquí. Explícate o muere...}
{129}{}{¡Nasti!}
{130}{}{No tengo nada que decir.}
{131}{}{Estoy aquí para proteger a la humanidad de tus semejantes.}
{132}{}{Oh, ¡cállate!}
{133}{}{No intentes volverme loco haciéndote el tonto. Estoy cansado de esto...}
{134}{}{¿Qué clase de fanatismo estúpido es ése?. Nosotros somos la "humanidad". Somos tan
 humanos como tú.}
{135}{}{¿Qué clase de mierda es ésa?}
{136}{}{No puedes ser humano, de ninguna manera.}
{137}{}{Me llamo Kyle. Nací de una madre y de un padre como tú.
 El Maestro simplemente supervisó mi renacimiento. Estos músculos, esta piel,
 esta fuerza, no me hacen menos humano que tú. No me gusta lo que la Unidad
 significa pero es la única oportunidad que tenemos para conseguir la paz.}
{138}{}{Creo que no es nada de eso. Estoy aquí para acabar contigo y con tus semejantes.}
{139}{}{Puede que seas humano, pero eso no hace de tu Unidad algo bueno. Creo
 que seremos enemigos.}
{140}{}{Es una pena que te comportes de esa manera pero ya no tendrás más oportunidades...}
{141}{}{Será una verdadera pena ver tu cabeza colgando de una lanza.}
{142}{}{¡Intrusos!}
{143}{}{No hablo contigo.}
{200}{}{Ganas }
{201}{}{ puntos de experiencia por colarte sin que te pillen los guardias.}