{100}{}{Ves a: Alex, el guardia nocturno Regulador.}
# TRANSLATION NOTE
# The player-character's name is inserted after line 101.
{101}{}{Vamos entra, }
{102}{}{Lo siento, no puedo dejarte entrar. Vuelve por la mañana.}
{103}{}{¡Alto! ¿Quién está ahí?}
{104}{}{Solo pasaba por aquí. Me gustaría entrar.}
{105}{}{No es asunto tuyo.}
{106}{}{Eee, lo siento. Me marcharé.}
{107}{}{No se permiten extranjeros dentro de los muros de Adytum, por orden del alcalde.}
{108}{}{Solo necesito un lugar para dormir por la noche.}
{109}{}{Lo siento, pero no puedo dejarte entrar. Vete de aquí o tendré que
 disparar.}
{110}{}{Mira, mi deber y honor es servir como guardia nocturno para Adytum,
 así que es asunto mío. Ahora date la vuelta y márchate, o tendré que ponerme serio.}
{111}{}{Apártate de mi vista, John Sinley.}
{112}{}{Intenta volver por la mañana.}
{113}{}{Oh, ya está. ¡Ahora se apagan las luces!}
{114}{}{Nghgh.}