{100}{}{Estás viendo a Andrew, el guardia de la prisión.}
{101}{}{Vale, ya puedes irte.}
{102}{}{¡Eh! ¡Tú! ¡Para!}
{103}{}{¿Puedo ayudarte?}
{104}{}{¿Quién eres?}
{105}{}{¿Qué estás haciendo?}
{106}{}{No, gracias.}
{107}{}{Soy Andrew. Mi trabajo es vigilar la prisión.}
{108}{}{Estoy vigilando la prisión. Me aseguro de que nadie indebido entra o sale de aquí.}
{109}{}{¿Por qué no dejas que la gente entre en la prisión?}
{110}{}{Oh.}
{111}{}{Que tengas un buen día. Y no te metas en líos.}
{112}{}{Alguien puede dejar algo que ayude a un prisionero a escapar. O se puede encerrar dentro y quedarse ahí hasta que encontremos las llaves.}
{113}{}{¡Agg!}
{114}{}{Circula, tío.}
{115}{}{Circula, tía.}
{116}{}{¡Eh! ¡Basta ya!}

