{100}{}{Estás viendo a Ton.}
{101}{}{Estás viendo a un gran miembro de los Niños.}
{102}{}{hombre}
{103}{}{mujer}
{104}{}{[Hecho]}
{105}{}{[Más]}
{106}{}{Lo siento, tío, has pasado el punto sin retorno con nosotros. ¡Hora de abrirse!}
{107}{}{Lo siento, tía, has pasado el punto sin retorno con nosotros. ¡Hora de abrirse!}
{108}{}{¿Por qué querría yo hablar con alguien que va por ahí asesinando niños?
 ¡Fuera de mi vista!}
{109}{}{Aunque he oído que eres guapa. Pero eso no impresiona a Ton.
 ¿Tienes algo que decir o quieres entrar en acción? ¡Hagámoslo!}
{110}{}{¡Paz, hermano! Sólo estoy echando un vistazo.}
{111}{}{No me interesa impresionarte. Si tienes algo inteligente que
 decir, ¡dilo!}
{112}{}{¿Continuar? Señor, no me interesan los pequeñajos repulsivos.}
{113}{}{¿Qué quieres?}
{114}{}{Hablas demasiado.}
{115}{}{Tú quieres morir y yo quiero matar a alguien. Perfecto.}
{116}{}{¡Ahh!}
{117}{}{Colega, ¡ya he terminado de hablar contigo! ¡Mueve tu culo a otra parte!}
{118}{}{niño}
{119}{}{niña}
{120}{}{Eh, ¿piensas que con tu arma vas a conseguir algo de respeto? Todo lo que vas
 a conseguir es un ataúd, tío. Olvídalo.}
{121}{}{Eh, ¿piensas que con tu arma vas a conseguir algo de respeto? Todo lo que vas
 a conseguir es un ataúd, tía. Olvídalo.}
{122}{}{¿Qué quieres, zombi subnormal? Quita tu jeta de aquí antes de que te la parta.}
{123}{}{¡Buscaba a alguien lo bastante listo para contarme lo que realmente
 ocurre por aquí!}
{124}{}{¿Qué dirían los sacerdotes si te oyeran hablar así?}
{125}{}{En cualquier momento, colega. ¡He estado esperando una bronca!}
{126}{}{¡Eh! ¿Cuál es el problema? ¡Un par de botellas y somos colegas!}
{127}{}{¿Sabías que incluso un niño puede atizarte en el lugar exacto
 de la rótula y dejarte cojo para siempre? Pensé que te gustaría saberlo.}
{128}{}{¿Quieres hablar con Ton? Vale. Pero si oigo la palabra "alabanza",
 te mataré.}
{129}{}{¿No eres un gran amigo de los servicios religiosos?}
{130}{}{¿Cual es tu problema, colega?}
{131}{}{Quiero hablar con el encargado.}
{132}{}{Eso seguro. Lo único que se parece a las alabanzas es una botella de Escorpión Rad.}
{133}{}{Vale. El primero que diga esa palabra, muere. ¿Trato hecho?}
{134}{}{Hola, señorita. Soy Ton, 2.000 libras; el mejor luchador del Maestro.
 También me he convertido por el VEF en algo que tienes que comprobar.
 Pasemos a la acción, muñeca.}
{135}{}{No hay elección.}
{136}{}{Es demasiado pronto. Conozcámonos un poco primero.}
{137}{}{Hola. Debido al VEF he cambiado y los que me cabrean mueren. No me cabrees, pequeño idiota.}
{138}{}{Averígualo en otro lugar. A Ton no le gusta tu compañía.}
{139}{}{Vale. ¿Quieres seguir? A veces es necesario matar
 A veces incluso me gusta. Pero he oído que a ti te gusta matar... siempre.
 Cada vez que topo con un psicópata, muere él o muere Ton. Ton aún
 está aquí. ¿Así que por qué no te vas a otra parte?}
{140}{}{Colega, podría intentar hacer que me gustaras. O eres totalmente imbécil
 o tienes muchas agallas. De todos modos le va bien a Ton, mientras no me
 traigas problemas. ¿Quieres unirte a mi?}
{141}{}{¿Qué hay de la paz y del amor?}
{142}{}{¿De qué se trata?}
{143}{}{No hay opción, colega.}
{144}{}{Daré los problemas que quiera cuando quiera. ¡Así que pasemos de problemas!}
{145}{}{Para verte sufrir. Vamos, boy, dame lo que quiero.}
{146}{}{Cuidado con lo que quieres. Quizás no te guste lo que obtengas.}
{147}{}{Preferiría que fuéramos amigos.}
{148}{}{No mereces que pierda mi tiempo contigo.}
{149}{}{Continúa. Haz el primer movimiento. El último es mío.}
{150}{}{Bueno. Déjate ya de hablar y muévete.}
{151}{}{Sólo quería hablar.}
{152}{}{Vas a morir...}
{153}{}{¡Mierda! ¡Eres aún más idiota que los zombis! ¡Lárgate ya!}
{154}{}{El Maestro quiere paz y quiere que nosotros la obtengamos de él, así que
 vamos a divertirnos. ¿Capisco?}
{155}{}{Sí, pero tiene que ocurrir algo más que eso.}
{156}{}{¿Quiere el Maestro paz de verdad o sólo quiere matar?}
{157}{}{¿Quién es el Maestro?}
{158}{}{Me parece bien.}
{159}{}{¡Que se pudra el Maestro! ¡Nos vamos a cargar a todos!}
{160}{}{Es peligroso hacer malas preguntas, compadre. Ellos
 tienen todas las respuestas que quieres oír. Los que hacen malas preguntas, o
 que dan el coñazo, no duran mucho tiempo por aquí.}
{161}{}{Hago mi trabajo. Están contentos cuando hago mi trabajo. Están contentos cuando la basura
 callejera y los Seguidores desaparecen. Así los Nocturnos pueden hacer otras cosas.
 No juegues conmigo... es peligroso.}
{162}{}{¿Qué haces con trapitos de zombi? Si tienes esa apariencia,
 ¡tienes que mostrarla!}
{163}{}{No me preocupan los trapitos, tío. ¡Sólo quiero saber lo que ocurre
 por aquí!}
{164}{}{Ellos no te molestarían tanto si no tuvieras pinta de querer
 convertirte.}
{165}{}{Nadie que te importe, colega.}
{166}{}{Estoy pensando en convertirme.}
{167}{}{No es
 apariencia. Es una forma de morir.}
{168}{}{Aquí no bebemos. A los Nocturnos no les gusta. Será mejor que encuentres unas cuantas
 pistas más antes de volver a hablar con Ton.}
{169}{}{¡Has perdido la cabeza! Incluso podrías gustarme, pero me da la impresión
 que la gente que te rodea no dura mucho. Vete de aquí de una vez.}
{170}{}{Si te quedas unos meses por aquí, te vuelves igual de loco que ellos. ¿Qué
 quieres de Ton?}
{171}{}{¿Cómo pueden comportarse así?}
{172}{}{Quiero sexo y violencia, pero sin el sexo. ¿Sabes dónde puedo encontrarlos?}
{173}{}{Estoy perdiendo la cabeza en este lugar de zombis y no necesito tu ayuda.
 Aléjate de mí de una vez.}
{174}{}{Ese es Morfeo. Siempre está arriba, excepto cuando da sermones, lo que ocurre cada vez menos. Es listo y es un ganador, y eso es todo
 lo que cuenta. Ve a verlo por tu cuenta.}
{175}{}{Necesitas darte una vuelta por el Cementerio, colega. No hay sustancia por aquí,
 ¡y eso que he buscado!}
{176}{}{Vale. ¿Qué puede hacer Ton por ti?}
{177}{}{¡Zorra! ¡No sabes lo que te estás perdiendo! ¡Vete!}
{178}{}{La vida es demasiado corta para eso. Déjame enseñarte porqué no quieres esperar.}
{179}{}{Pero quiero a alguien que sepa lo que está ocurriendo.}
{180}{}{No, gracias. Pero no me importaría que fuésemos amigos.}
{181}{}{Piérdete, basura humana.}
{182}{}{Seguro.}
{183}{}{La vida ES más corta de lo que crees. ¡Muere, gilipollas!}
{184}{}{No soy PEQUEÑO, ¡zorra!}
{185}{}{¿Quién se cree ese cuento chino? Tienen que programar a esos borregos para
 que se crean toda esa historia.}
{186}{}{¿Cómo ocurrió?}
{187}{}{¿De verdad?}
{188}{}{Vaya panda de perdedores.}
{189}{}{Cuéntame algo más de tu pandilla.}
{190}{}{Vale, me uniré a vosotros.}
{191}{}{Alguien debería sacarlos de su miseria. Como yo...}
{192}{}{Cuando nos den la orden, saldremos a matar. A la gente le
 gustan los Seguidores o bandas más peligrosas.}
{193}{}{¿Así que lo Seguidores son un problema?}
{194}{}{Eso me suena fatal.}
{195}{}{¿Quién necesita la orden? ¿Por qué no matarlos simplemente?}
{196}{}{Bien. Haz lo que quieras. Pero yo me iré antes de que las cosas se compliquen
 por aquí.}
{197}{}{Me estás cabreando, pedazo de mierda. Eres peor que los de Ciudad Vertedero,
 cobarde. Lárgate ya.}
{198}{}{¿Qué más hay que saber? Me limito a comer y a dormir bien
 y a matar a los que me molestan. ¿Esperas algo más
 de la vida?}
{199}{}{¿Quién sabe? ¿A quién le importa? Me limito a comer y a dormir bien y
 a matar a algunos de los que me molestan. ¿Esperas algo más
 de la vida?}
{200}{}{Ummm, Ton nunca pensó en eso. Pero si me molestan demasiado,,
 les parto la cara. Entonces ellos dejarán de molestar a Ton. ¿Qué quieres?}
{201}{}{¿Convertirte? Bien, buena suerte. La necesitarás.}
{202}{}{¿Por qué necesitaré suerte?}
{203}{}{Eso no suena bien.}
{204}{}{Gracias. Eres un verdadero amigo.}
{205}{}{No necesitaré suerte mientras tenga municiones.}
{206}{}{Esta gente, estos zombis, no han sido siempre así. Incluso podía
 soportar a unos pocos. Pero un día se convirtieron. Algunos de ellos se convirtieron en lo que ves. Otros no volvieron a aparecer. A Ton no les gusta, pero ellos pagan bien a Ton.}
{207}{}{¿Por qué no dejas de mezclar la primera y la tercera persona?}
{208}{}{Dime algo más sobre el proceso de conversión.}
{209}{}{¿Experimentaste el proceso de conversión?}
{210}{}{Este lugar es muy barato.}
{211}{}{¿Sí?, ¿cómo de barato?}
{212}{}{¡Nadie va a hacerme esto!}
{213}{}{Habla con Morfeo o con Fustigador, o se enfada Ton,
 y Ton te dará más caña de la que puedes imaginar.}
{214}{}{Bien, muñeca, lo que pasa es que hay un montón de zombis cantando,
 un montón de gente muriendo y los Niños van a hacerse con todo.
 ¡Estamos aquí tú y yo y nada más importa!}
{215}{}{Pero Barracus, cariño, seguramente está sucediendo algo más que eso...}
{216}{}{¡Oh, Ton!}
{217}{}{Olvídalo, idiota. No eres mi tipo.}
{218}{}{¿No importa nada más? ¡Diablos, no! ¡Quiero saber algo más sobre los que se están muriendo!}
{219}{}{Desgraciadamente, este es el peor lugar de la tierra para comprobar las
 cualidades de Ton. Hay demasiados zombis que me cortan las alas. Te avisaré en cuanto
 piense en un lugar más conveniente...}
{220}{}{Pronto descubrirás lo que ocurre ahí arriba. Si eres fuerte, lo
 harás bien. Eso le pasó a Ton, ¡y Ton está bien!}
{221}{}{Oh... No he dicho nada. O te olvidas de lo que Ton te ha contado,
 ¡o Ton te lo hará olvidar para siempre!}
{222}{}{Antes eran unos llorones. Pero Ton habla demasiado. Fuera
 de mi vista.}
{223}{}{Bien. Quédate quieto hasta que te dé la orden. Entonces nos divertiremos.}
{224}{}{Son unos cobardes. Tienden emboscadas a nuestras patrullas. Mandan espías
 y saboteadores. Saben que no pueden ganar una lucha real. El Maestro dice que
 tendríamos que sentir compasión por ellos, pero Ton sólo quiere matarlos. Eres inteligente,
 Ton.}
{225}{}{¡Necesitamos disciplina, idiota! ¡Ahora somos soldados! Obedecemos órdenes. Los asesinos
 mueren, pero los soldados ganan sus batallas. Venceremos a los Seguidores.
 ¡Los venceremos a TODOS!}
{226}{}{¿Quién demonios lo sabe? Puede que sólo sea Morfeo moviendo los hilos.
 Todo va bien. Pero si las cosas se complican, Ton se va a otro lugar.}
{227}{}{Bien, no te impacientes. Incluso con los Nocturnos, la lucha es aún
 dura. Pero si hacemos una jugada inteligente, saldremos victoriosos. Ésa es la única cosa
 que le preocupa a Ton.}
{228}{}{La conversión no es fácil. ¿Ves a esta gente, a todos estos zombis?
 Antes eran como tú y yo. Ton sobrevivió pero ellos no.
 Pero, ¿por qué se iba a preocupar por ti Ton?}
{229}{}{¿No te gusta cómo habla Ton? ¡Entonces Ton te matará!}
{230}{}{Ton lo hace bien. Yo... eh, yo... uh... Yo... uh...
 Ton... Ton está bien.}
{231}{}{Yo iba con la banda del Perro Muerto. Siempre hambriento, siempre cansado.
 Este lugar es mucho mejor para Ton. ¿Por qué me iba a preocupar por alguien más?
 Nadie se preocupa por mí.}
{232}{}{¡Perro asqueroso! ¡Lárgate de aquí antes de que Ton te mate!}
{233}{}{Entonces vete de aquí antes de que sea demasiado tarde.}
{234}{}{Nadie es tan importante como tú y yo. Desgraciadamente este es el peor lugar
 de la tierra para conocer las cualidades de Ton. Demasiados zombis me cortan las alas.
 Te lo haré saber cuando piense en un lugar más conveniente...}
{235}{}{¡Eres una zorra manipuladora! ¡Nadie molesta a Ton de este modo!}