{100}{}{¡Has mosqueado a Barry!}
{101}{}{Estás viendo a Barry.}
{102}{}{¡Eh! La ración de agua es sólo para los Necrófagos.}
{103}{}{¡Te la vas a ganar por despertarme!}
{104}{}{El mutante te ignora.}

{1000}{}{Chip}
{1001}{}{Necrópolis}
{1002}{}{Set}
{1003}{}{Almacén de Agua}
{1004}{}{Sala}
{1005}{}{Teni}
{1006}{}{Necrófagos}
{1007}{}{Normales}

{1100}{}{No tengo ni idea.}
{1101}{}{Estás encima de ella.}
{1102}{}{Es un indeseable. Deberíamos liquidarlo a él y a sus Necrófagos.}
{1103}{}{Es aquí.}
{1104}{}{No tengo ni idea.}
{1105}{}{Es el jefe de Harry.}
{1106}{}{Debiluchos.}
{1107}{}{Más débiles que los Necrófagos.}

