{100}{}{Estás viendo a Billy.}
{101}{}{Hola.}
{102}{}{Hola, ¿qué estas haciendo?}
{103}{}{¿Puedo coger un Brahmin?}
{104}{}{Hola. Oh, adiós.}
{105}{}{¡Arg!}
{106}{}{Ta.}
{107}{}{¿Por qué quieres un Brahmin? ¿Tienes una caravana? Bueno, no importa. Yo sólo cuido de ellos.
 Dan es su propietario y, además, no te los venderá.}
{108}{}{¿Por qué?}
{109}{}{Sólo estaba bromeando.}
{110}{}{Por lo de las caravanas desaparecidas. A él no le sobra ninguno, las caravanas los necesitan casi todos. Los otros,
 se venden por comida. Bueno, será mejor que pare de hablar; Dan se enfadará si me ve hablando con un extraño.}
{111}{}{Oh, vale.}
{112}{}{Nada... quiero decir, yo cuidaré del Brahmin.}
{113}{}{¿Para qué quieres la lanza? ¿Son peligrosos?}
{114}{}{¿Qué es un Brahmin?}
{115}{}{¿Que qué es un Brahmin? Debes estar bromeando. Son la
 principal fuente de alimentos y de transporte por aquí.
 Tiran de las caravanas. Dan dice que es un trabajo muy importante,
 pero es mentira.}
{116}{}{Oh, ¡ya lo sabía!}
{117}{}{Dan tiene razón. Estás haciendo un magnífico trabajo.}
{118}{}{Sí, eso parece. Pásalo bien.}
{119}{}{Eh, tú no serás un yonqui de esos ¿verdad?}
{120}{}{¿De verdad? ¿Eso crees? Sí, gracias.}
{121}{}{Tú no eres de por aquí, ¿verdad? Te daré un consejo:
 ¡Qué no te cojan robando!}
{122}{}{Claro, gracias.}
{123}{}{Ni se me ocurriría robar. Robar no está bien.}
{124}{}{Sí, creo que empiezo a estar de acuerdo contigo. La verdad es que este trabajo no está tan mal.
 Por alguna razón me hace sentir bien. Bueno, mejor que me vaya antes de que me
 meta en problemas.}
{125}{}{Por favor, no nos hagas daño ni a mí ni a mi Brahmin.}
{126}{}{¡No me hagas daño!}
{127}{}{¡Para!}
{128}{}{Por favor, déjame en paz.}
{129}{}{Me estás asustando.}
{130}{}{¡Eh! ¿Qué quieres hacer? No tengo nada de lo que tu buscas.}
{131}{}{¡Para!}
{132}{}{¿Peligrosos? No demasiado. A veces pueden morderte pero
 no son malos. Se tiran pedos y eructan un montón. No sé por qué.}
{133}{}{Y bien, ¿para qué es la lanza?}
{134}{}{Vale, gracias.}
{135}{}{Oh, pueden ser muy cabezotas cuando les pides que hagan algo. Entonces, los golpeo suavemente para que se muevan... pero no quiero
 acercarme demasiado porque a veces dan
 patadas.}
{136}{}{Por favor, no me hables. Dan me va a gritar otra vez. Se cabrea... quiero decir... se enfadada cuando
 no presto atención a lo que estoy haciendo.}
{137}{}{Solamente intentaba ayudar. Trabaja duro y seguro que será más amable.}
{138}{}{Toma chico, aqui tienes 50 chapas. Lárgate de este agujero.}
{139}{}{Vale.}
{140}{}{¡Aaaaaarg!}
{141}{}{¿Rhu?}
{142}{}{Por favor no lo hagas; ya tengo suficientes problemas.}
{143}{}{¡ESTOY trabajando duro!}
{144}{}{Lo siento, no quería decir eso. Sólo intentaba ayudarte.}
{145}{}{Seguro, ¡tío vago!}
{146}{}{Vale.}
{147}{}{Sí, quizá tengas razón... de hecho, parece buena persona,
 pero ojalá no me gritase tanto.}
{148}{}{Sí, de acuerdo.}
{149}{}{¡Cállate, pesado!}
{150}{}{¡Cállate, bruja!}
{151}{}{¡Guau! ¡Puedo vivir de esto el resto de mi vida! ¡Muchas gracias, señor!}
{152}{}{¡Guau! ¡Puedo vivir de esto el resto de mi vida! ¡Muchas gracias, señora!}
{153}{}{¡Guau! Gracias... ¿Bien?... ¡Sólo estás intentando meterme en líos otra vez!}
{154}{}{Por favor no me hables; Dan está muy enfadado.}
{155}{}{No te preocupes. He tenido una charla con él e intentará ser más amable contigo.}
{156}{}{¡Y debe enfadarse! ¡Eres un chico terrible!}
{157}{}{Bah.}
{158}{}{¡Hola!}
{159}{}{Esas niñas de ahí deben ser tontas.}
{160}{}{Hola otra vez.}
{161}{}{Los Brahmin están muy bien.}
{162}{}{Dan me va a llevar al Halcón si hago un buen trabajo.}
{163}{}{¡Dan me va a llevar en una caravana algún día!}
{164}{}{Seré aventurero cuando sea mayor.}
{165}{}{¿De verdad? Oh, vale. Espero que no le hayas hecho daño. No es tan malo.
 Sólo grita demasiado.}
{166}{}{Hola otra vez.}
{167}{}{¿Qué haces esta vez?}
{168}{}{¿Puedo coger un Brahmin?}
{169}{}{Sólo pasaba para ver cómo iban las cosas. Adiós.}
{170}{}{¡Arg!}
{171}{}{Ta.}
{172}{}{Será mejor que regrese al trabajo.}
{173}{}{Esas niñas deben tontas.}
{174}{}{Hola otra vez.}
{175}{}{Seré un aventurero de mayor.}
{176}{}{Los Brahmin seguro que van dejando mier... uh, se hacen muchas caquitas.}
{177}{}{No puedo hablar ahora mismo.}
{178}{}{No me quiero meter en líos.}
