{100}{}{Los escombros se han ido acumulando en el camino de la entrada.
 Pesan demasiado para ser movidos. Te preguntas si el Chip del Agua ha estado ahí
 alguna vez. Si lo estuvo, ya no se puede usar.}
{101}{}{Piedras grandes y pesadas bloquean la entrada de la sala. Intentas mover una roca pero no lo consigues.}

