{100}{}{Estás viendo a un Caballero.}
{101}{}{La sala de aprendizaje está justo allí si es eso lo que
 estás buscando.}
{102}{}{¿Te has perdido? La sala de aprendizaje está justo allí.}
{103}{}{El Laboratorio médico está justo a la vuelta de la esquina.}
