{100}{}{Cerrado por orden del Sheriff Justin Greene.}
{101}{}{Hay una pequeña señal en la cabina.}
{102}{}{Se busca: Iguana Bob Frazier, vivo o muerto. Si tiene información
 sobre su paradero actual o sobre la persona responsable de su huida, por
 favor, informe al Sheriff inmediatamente.}
