{100}{}{La estantería está llena de libros religiosos y filosóficos. También
 está llena de polvo.}
{101}{}{Coges un libro, le echas un vistazo y rápidamente lo vuelves a poner en su lugar en la estantería. La estantería parece muy sólida.}
{102}{}{Encuentras un pestillo oculto.}
{103}{}{No sirve para nada.}
{104}{}{La pared junto a la estantería se desliza silenciosamente hacia afuera.}
{105}{}{Toqueteas la estantería un poco, pero no consigues nada.}
{200}{}{La estantería está llena de libros religiosos y filosóficos.}
{201}{}{El pestillo no se moverá.}
 
