{100}{}{Es un animal doméstico.}
{101}{}{No hay nada natural en estas vacas. La segunda cabeza sólo puede ser
 el resultado de una extraña mutación.}
{102}{}{A ti te parece normal.}
{103}{}{Muuu.}

