{100}{}{Estás viendo a un Anciano de la Hermandad.}
{101}{}{Saludos, Iniciado.}
{102}{}{Maxson parece un poco nervioso últimamente.}
{103}{}{Vree ha descubierto cosas muy innovadoras.}
{104}{}{Me pregunto si Maxson está en lo cierto sobre ese ejército en el norte.}
{105}{}{Buenos días, Iniciado.}

