{100}{}{Estoy aquí para patear culos y masticar chicle. Me he quedado sin chicle.}
{101}{}{La Hermandad está rezando por nuestro éxito, señor.}
{102}{}{Salgamos.}
{103}{}{Mantén tu presencia táctica, señor.}
{104}{}{Será mejor que nos vayamos.}
{105}{}{No tengo tiempo para charlar, señor.}
{106}{}{Estoy aquí para patear culos y masticar chicle. Me he quedado sin chicle.}
{107}{}{La Hermandad está rezando por nuestro éxito, señora.}
{108}{}{Salgamos.}
{109}{}{Mantén tu presencia táctica, señora.}
{110}{}{Será mejor que nos vayamos.}
{111}{}{No tengo tiempo para charlar, señora.}
{112}{}{Bien, estás aquí. Arrasemos este lugar.}
{113}{}{Hay algo raro en esta sala.}
{114}{}{Este lugar está empezando a darme repelús.}
{115}{}{Es hora de volverse a la Hermandad.}
