{100}{}{Estás viendo a una mujer joven y muy guapa.}
{101}{}{Estás viendo a Christine, la mujer de Michael.}
{102}{}{¿Hola? ¿Puedo ayudarte?}
{103}{}{¿Quién eres?}
{104}{}{¿Quién está al mando aquí?}
{105}{}{¿Puedes contarme algo de esta zona?}
{106}{}{No, gracias}
{107}{}{¿Y tú, mami?}
{108}{}{Me llamo Christine, vivo aquí con mi marido Michael.}
{109}{}{Cuchilla se encarga de la mayoría de los asuntos de los Navajas y ayuda a organizarnos.}
{110}{}{Michael y yo nos acabamos de mudar y no he visto mucho de la zona. He oído hablar de una gran iglesia al sur, pero creo que son sólo rumores.}
{111}{}{¿Hay algo más que debiera saber?}

#
# TRANSLATION NOTE: Do NOT translate the next 4 lines.  They will NOT make any
#					sense in any other language.
#
{112}{}{C D E D B D Ducks}
{113}{}{M R Not Ducks}
{114}{}{O S M R                                                                   C D E D B D Wings}
{115}{}{Y I B M R Ducks}

{116}{}{¿En qué más puedo ayudarte?}
{117}{}{No soy tu mami. Ahora desaparece y vete a jugar.}
