{100}{}{Estás viendo a un Guardia de las Caravanas.}
{101}{}{No puedo creer que hayamos perdido al jefe. ¿Quieres volver con nosotros?
 Aún podemos pagarte las 400 chapas.}
{102}{}{Es una pena que hayamos perdido al conductor; a Rutger no le hará nada de gracia.
 Si quieres, podemos pagarte lo mismo para que vuelvas con nosotros al
 Eje.}
{103}{}{¿Vas a volver con nosotros? Yo conduciré esta cosa. La paga es la misma.}
{104}{}{Bien, no te conozco, pero creo que esperaré a otra
 caravana. No quiero volver solo. Si quieres volver, iré contigo,
 pero si no lo consigo no obtendrás las 400 chapas.}
{105}{}{Fue horrible. Si quieres, puedo conseguirte otras
 400 chapas si vuelves al Eje conmigo. Resulta muy peligroso para una sola
 persona.}
{106}{}{Obtendrás otras 400 chapas si puedes llevarme a mí y a la caravana al
 Eje sanos y salvos, pero sólo si lo consigues. Has de cubrirme
 si nos metemos en líos.}
{107}{}{Vale; iré contigo.}
{108}{}{No gracias, ya he hecho muchas guardias.}
{109}{}{Tuk.}
{110}{}{¡Fantástico! ¡Vámonos de aquí!}
{111}{}{Vale, entiendo.}
{112}{}{Lo haré.}
{113}{}{Vale.}
{114}{}{¿Estás bien?}
{115}{}{Creo que necesitas descansar.}
{116}{}{Oh, creo que deberías visitar al Doctor de la Hermandad.}
{117}{}{Hemos perdido al Jefe. ¿Te vienes con nosotros? Aún podemos pagarte
 las 400 chapas.}
{118}{}{Nuestro conductor era una buena persona... una gran pérdida.
 Aún puedo pagarte las 400 chapas si quieres volver con nosotros al Eje.}
{119}{}{Volveremos si quieres venir con nosotros. La paga será la
 misma.}
{120}{}{Guau, no puedo creer que seamos los únicos que quedemos. Iré contigo,
 pero si no llegamos no obtendrás esas 400 chapas.}
{121}{}{Eso fue horrible. Si quieres, puedo conseguirte
 otras 400 chapas si vuelves al Eje conmigo. Es demasiado
 peligroso para una sola persona.}
{122}{}{Obtendrás otras 400 chapas si puedes llevarme a mí y a la caravana al
 Eje sanos y salvos, pero sólo si lo consigues. Has de cubrirme
 si nos metemos en líos.}
{123}{}{¿Así que has cambiado de opinión?}
{124}{}{Sí, cogeré el trabajo.}
{125}{}{No.}
{126}{}{¿Eh?}
{127}{}{Lo siento, no vamos a volver al Eje hoy.}
{128}{}{Um, lo siento. No creo que te necesitemos para el viaje de vuelta.}
{129}{}{Habla con nuestro conductor de caravanas para que te contrate.}
{130}{}{Hola. Si buscas trabajo, habla con nuestro conductor de
 caravanas.}
{131}{}{Hola.}
{132}{}{Lo siento, no puedo hablar.}
{133}{}{¿Vas a volver al Eje con nosotros?}
{134}{}{Me gusta trabajar en las caravanas, mucha acción y muchas chapas.}
{135}{}{Los Comerciantes de Ultramar son buenos jefes.}
{136}{}{Me gusta trabajar con los Comerciantes de Ultramar, no se arriesgan inútilmente.}
{137}{}{Las caravanas de la Caravana Carmesí son las mejores.}
{138}{}{La Caravana Carmesí paga muy bien. Me jubilaré dentro de un año.}
{139}{}{Habla con el otro guardia si quieres venir con nosotros.}
{140}{}{Aquí están tus chapas. Si puedes, échanos una mano en el regreso.}