{100}{}{Estás viendo a un Nocturno delante de ti.}
{101}{}{¡Muere!}
{102}{}{¡Déjame o morirás!}
{103}{}{No me gusta tu tono de voz. Si mi mensaje no llega al Maestro,
 haré que tu muerte sea lenta y dolorosa.}
{104}{}{Sólo quería felicitarte por tu joroba tan elegante.
 Pero te costará respirar, ¿no?...}
{105}{}{¿Puedes llevarme ante el jefe?}
{106}{}{¡Puedes usar una bebida peor que yo!}
{107}{}{¡No me voy!}
{108}{}{Vale, me voy.}
{109}{}{Resulta peligroso jugar con los Nocturnos. ¡Vete de aquí!}
{110}{}{No lo creo.}
{111}{}{¡Me encantará verte morir!}
{112}{}{¿Es que no escuchas? Resulta peligroso jugar con los nocturnos.}
{113}{}{Debo hablar contigo ¡Es urgente!}
{114}{}{¡Nadie me ha acusado nunca de ser prudente!}
{115}{}{¡Sólo quiero hablar con el jefe!}
{116}{}{¿Piensas que eres fuerte o algo así?}
{117}{}{¡Lo siento! Que tengas un buen día.}
{118}{}{¿Quieres cagarla? La cagarás si no me dejas en paz, ¡imbécil!}
{119}{}{Sube. Otros de mi especie juzgarán el valor de tu mensaje.}
{120}{}{¡Esta es mi última advertencia!}
{121}{}{¡Seguro que sí! Un buen trato...}
{122}{}{¡REALMENTE necesito hablar con el jefe!}
{123}{}{¡Vale! ¡Vale! ¡Lo siento! Hasta luego.}
{124}{}{¿Sabes cuál fue tu error? Das advertencias y yo no. ¡Muere!}
{125}{}{[Hecho]}
