{100}{}{Estás viendo a un Niño de muy mal humor.}
{101}{}{¡Fuera de mi vista, hijoputa!}
{102}{}{¡Vete de aquí!}
{103}{}{¿Qué diablos quieres?}
{104}{}{¿Dónde puedo encontrar al Maestro?}
{105}{}{Descubrir lo que ocurre por aquí.}
{106}{}{¿Quién manda aquí?}
{107}{}{Eh, ¡anciana! ¡Bebamos algo!}
{108}{}{Añadir tus orejas a mi colección.}
{109}{}{¡No querer diablos! ¡Idiota!}
{110}{}{Al diablo, perdeor.}
{111}{}{¿Siempre haces preguntas estúpidas, gili?}
{112}{}{Diablos, seguro que tú no, idiota.}
{113}{}{¿Qué te hace pensar que quiero beber contigo, rata de cloaca?}
{114}{}{¡Vete antes de que te mate!}
{115}{}{[Hecho]}
