{100}{}{Estás viendo a un niño pequeño.}
{101}{}{¡Hola!}
{102}{}{Hola.}
{103}{}{¿Dónde están tus padres?}
{104}{}{Erf.}
{105}{}{No zé. Por aquí, supongo.}
{106}{}{¡Qué simpático!}
{107}{}{Oye, ¿vas a matar a alguien?}
{108}{}{Sí.}
{109}{}{¡No!}
{110}{}{Erf.}
{111}{}{¡Se lo diré a mi mamá!}
{112}{}{Entonces no deberías llevar un arma como esa.}

{980}{}{¿Eh?}
{981}{}{No zé. Pregúntale a mi mamá.}
{982}{}{Pregúntale a mi papá.}

{1000}{}{Garra Mortal}
{1001}{}{Piratas}
{1002}{}{Ciudad Vertedero}
{1003}{}{Brahmin}
{1004}{}{Chip}
{1005}{}{Mercaderes}
{1006}{}{Khans}
{1007}{}{Garl}
{1008}{}{Arenas Sombrías}
{1009}{}{Eje}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Policía}
{1015}{}{Caravanas}
{1016}{}{Comerciantes}
{1017}{}{Niños}
{1018}{}{Necrópolis}
{1019}{}{Zona}
{1020}{}{Hermandad}
{1021}{}{Cementerio}
{1022}{}{Torres}
{1023}{}{Ciudad}
{1024}{}{Centro ciudad}
{1025}{}{Alturas}

{1100}{}{¡Uh! ¡Un monstruo de pesadilla!}
{1101}{}{¡Viejos agarrados!}
{1102}{}{No lo sé.}
{1103}{}{Bichos asquerosos.}
{1104}{}{Pregúntale a mi mamá.}
{1105}{}{Canciones alegres.}
{1106}{}{¡Viejos agarrados!}
{1107}{}{Hombre malo.}
{1108}{}{No te lo digo.}
{1109}{}{Menuda ciudad.}
{1110}{}{¡No te lo digo!}
{1111}{}{No, no te lo digo.}
{1112}{}{Mamá no quiere que hable de él.}
{1113}{}{Papá piensa que es gracioso.}
{1114}{}{Gente simpática.}
{1115}{}{Estos bichos asquerosos los están molestando.}
{1116}{}{Buena gente, me dan golosinas.}
{1117}{}{No les gusta jugar al escondite.}
{1118}{}{Un lugar espantoso.}
{1119}{}{Un lugar asqueroso.}
{1120}{}{Un lugar espantoso.}
{1121}{}{Un lugar espantoso.}
{1122}{}{Mamá no nos dejará jugar allí.}
{1123}{}{Papá nos dice que juguemos allí.}
{1124}{}{Gente simpática.}
{1125}{}{Gente simpática.}
