{100}{}{Estás viendo a un técnico de los Niños de la Catedral.}
{101}{}{Deja tus armas y los Nocturnos te dejarán vivir.}
{102}{}{No luches contra nosotros, únete.}
{103}{}{¡Te convertirás en uno más de la Unidad!}
{104}{}{Nocturno, aquí tienes a este prisionero estúpido. Nuestro Maestro estará encantado.}
{105}{}{Por favor no me mates. Sólo trabajo aquí.}
{106}{}{No matarías a un hombre desarmado, ¿verdad? ¡¿Lo harías?!}
{107}{}{¡Me rindo!}
{108}{}{No tienes derecho a estar aquí. ¿Qué quieres?}
{109}{}{Hne.}
{110}{}{¿Quién eres tú?}
{111}{}{¡Estúpidos! ¡Estoy cansado de vosotros!}
{112}{}{¿Qué lugar es éste?}
{113}{}{Ahora eres casi un Nocturno. Espero que tu inteligencia no haya
 sido dañada aún más.}
{114}{}{Soy parte de la Unidad. Soy un glorioso sirviente de nuestro Maestro.
 Soy el que verá cómo te conviertes en parte de la Unidad.}
{115}{}{Lo descubrirás bastante pronto.}
{116}{}{¡Aquí apareció la raza superior! ¡Ésta es la cuna
 de la que surgirán los ejércitos de Dios! De la carne de los débiles florecerá
 una raza de hombres. Aquellos que sobrevivan, se convertirán en soldados de Dios y con sus manos construiremos la Unidad.}
{117}{}{¡Estás loco! ¡Estás completamente loco! ¡Muere!}
{118}{}{¿Cómo funciona?}
{119}{}{Te someterás a las limitaciones sagradas. Te sumergiremos en una
 cuba llena de sangre de Dios, lo más sagrado de lo sagrado. El VEF te dará forma y
 te convertirá. Serás fuerte. Si eres afortunado y te mereces ese honor,
 te convertirás en Nocturno. Si no, tendrás la muerte más dolorosa que
 existe. Pronto, seré honrado. Seré más fuerte. Y entonces no temeré
 a nadie.}
{120}{}{Has estado con los Nocturnos demasiado tiempo. Adiós.}
{121}{}{¿Y por qué me estás contando eso?}
{122}{}{¿Dónde conseguiste el VEF?}
{123}{}{¡O formas parte de la Unidad o haremos que tu alma se pierda en el Infierno! [Pausa] Además, estoy aquí con un puñado de
 conversos. Hicimos bien en deshacernos de ello.}
{124}{}{¿Dónde conseguiste el VEF?}
{125}{}{Has matado a la Mano Derecha de Dios. El Maestro estará muy enfadado. ¡Ahora ha llegado el momento de unirnos a la Llama Sagrada!}
{126}{}{Mataste al Maestro. La muerte de la Unidad es culpa tuya.
 Has provocado la muerte de la raza humana. Espero que estés satisfecho.}
{127}{}{Hnnn.}
{128}{}{En realidad sí.}
{129}{}{Te unirás a él enseguida. Rézale al dios que se hizo con el mando de
 este lugar.}
{130}{}{¡Voy a unirme a él en la Llama Sagrada!}

