{100}{}{Estás viendo a un hombre de piel oscura adornado con bufandas de colores brillantes y baratijas.}
{101}{}{Estás viendo a Chuck, el adivino gitano.}
{102}{}{Hola, forastero. ¿Puedo ayudarte en algo?}
{103}{}{¡Ahg!}
{104}{}{Solamente estaba echando un vistazo, gracias.}
{105}{}{Estoy aprendiendo a conocer a la gente de Adytum.}
{106}{}{¿Por qué piensas que necesito algo?}
{107}{}{Mmm. No te preocupes, inocente, te quedan muchas cosas buenas por hacer.}
{108}{}{¿Qué piensas de nuestra ciudad?}
{109}{}{Está bien.}
{110}{}{No me gusta mucho. No es muy amistosa.}
{111}{}{Lo has hecho muy bien, si tenemos en cuenta las circunstancias hostiles.}
{112}{}{Me llaman Chuck. Bienvenido a Adytum. Me temo que la mayoría de la gente de aquí no es muy amable con los extranjeros.}
{113}{}{Sí, ya me he dado cuenta.}
{114}{}{Bueno, ¿y en qué trabajas Chuck?}
{115}{}{Hasta luego, Chuck.}
{116}{}{Buen viaje, vagabundo.}
{117}{}{Todos necesitamos algo, ¿no? Y no te habrías dirigido a mí si no hubieses querido algo, ya sea información, conversación o quizá un consejo.
 Creo que te has metido donde no te llaman. ¿Qué necesitas?}
{118}{}{Oh, no necesito nada, gracias.}
{119}{}{Ahora que lo dices, quizás puedas darme algún consejo.}
{120}{}{[Chuck saca una baraja de cartas de Tarot.] Déjame consultar las cartas. [Chuck baraja las cartas.]}
{121}{}{[Chuck saca dos cartas: una de un hombre con bata sentado ante un ordenador y otra de un hombre con una Armadura de Energía.] El Jerofante y el Príncipe de la Magia en el sur... una gran sabiduría y nobleza esperan en algún lugar al sur.}
{122}{}{[Chuck saca una carta con el dibujo de un hombre con una espada eléctrica y una bandera.] El Príncipe de las Espadas en el norte... tienes que enfrentarte a un enemigo poderoso, muy lejos, al norte.}
{123}{}{[Chuck saca una carta con el dibujo de una torre de radio y otra con el dibujo de un hombre en traje con un cetro.] La Torre y el Emperador... grandes cambios debidos a un jefe poderoso.
 Si se trata de la muerte o no, no te lo puedo decir.}
{124}{}{[Chuck saca una carta con un dibujo de un hombre bailando encima de una cabeza nuclear.] El Loco. No puedo ayudarte; tienes que seguir tu propio camino en este mundo.}
{125}{}{[Más]}
{126}{}{Mmm. Gracias por el consejo.}
{127}{}{¡¿De verdad que crees en eso?!}
{128}{}{Conmigo funciona. Pero si no te lo crees de verdad, no te servirá de nada.}
{129}{}{No quiero ofenderte, pero sólo me parece superstición.}
{130}{}{Bueno, creo que cada uno tiene sus propias creencias.}
{131}{}{Si así piensas, supongo que se acabó la discusión.}
{132}{}{Claro que sí. Tus creencias dan forma a tu universo, mientras que mis pensamientos dan forma al mío. Aunque no compartamos las mismas creencias espero que te vaya bien en tu universo.}
{133}{}{Es mi hogar.}
{134}{}{Oh, sí. Hasta luego.}
{135}{}{Este lugar parece tranquilo.}
{136}{}{Sé lo que quieres decir. He visto mucho sufrimiento.}
{137}{}{Los Reguladores se aseguran de ello. La gente de Adytum
 sufre a causa de sus leyes demasiado duras.}
{138}{}{Creo que sí. Bueno, nos vemos por ahí.}
{139}{}{¿Y estás bien?}
{140}{}{Como deseo quedarme aquí, acepto a los Reguladores como parte de lo que Adytum significa. Sin embargo, hago todo lo que puedo por hacer más fáciles sus vidas.}
{141}{}{No pareces estar de acuerdo con lo que hacen.}
{142}{}{¿Hay algo más que puedas hacer?}
{143}{}{Los Reguladores protegen sus propios intereses, y yo debo respetar eso.}
{144}{}{Sí, lo que sea.}
{145}{}{No estoy de acuerdo con ese punto de vista, pero puedo comprenderlo.}
{146}{}{La charla ha sido muy interesante. Nos vemos por ahí.}
{147}{}{Bueno, sólo soy humano pero hago lo que puedo para ayudar. Debes luchar por aquello en lo que crees, pero sobre todo, debes elegir bien
 las batallas que merecen la pena. No olvides que tanto la esperanza como las concesiones pueden llevarte a la victoria.}
{148}{}{¿Tienes algún otro consejo?}
{149}{}{La gente de Adytum tiene mucho que hacer un día normal.
 No quiere que llegue el final del día y que su trabajo haya sido inútil.}
{150}{}{Sí, bueno, lo que sea.}
{151}{}{Este lugar parece tranquilo.}
{152}{}{Gracias. Ha sido complicado. A veces perdemos gente a causa de las Garras
 Mortales y los inviernos pueden ser duros, especialmente si no vienen los
 comerciantes del Eje. Pero sobrevivimos.}
{153}{}{Buena suerte.}
{154}{}{¿Qué pasa con las Garras Mortales?}
{155}{}{Infestan una zona al noreste de aquí y a menudo capturan a los que comercian con los Pistoleros.}
{156}{}{Espero que encuentres una solución.}
{157}{}{Sí. Lo que sea.}
{158}{}{Quizás. Creo que Adytum estará aquí. En vez de ir al mundo, el
 mundo debe venir a nosotros, como tú lo hiciste.}
{159}{}{Mmm. Imagino que sí.}
{160}{}{Soy un granjero. También me gusta hacer trabajitos en las construcciones,
 restaurándolas y manteniéndolas intactas, y a veces, doy algunos consejos.}
{161}{}{¿Qué clase de consejos?}
{162}{}{Sí, desgraciadamente. Creo que... es como un
 crisol. Al sobrevivir a estos tiempos difíciles, hemos llegado a confiar los unos
 en los otros y hemos aprendido las técnicas necesarias para sobrevivir.
 Creo que la humanidad va mejorando.}
{163}{}{No estoy de acuerdo. He visto a muchas bandas y Piratas en
 mis viajes. Ellos se han convertido en ladrones y asesinos.
 Creo que todos corremos este tipo de riesgo.}
{164}{}{Quizás tengas razón. Es verdad que aquellos que sobreviven se hacen más fuertes.}
{165}{}{Acabarán destruyéndose a sí mismos. Sólo sobrevivirán los que unan sus fuerzas, como nosotros.}
{166}{}{Estoy contento que algunos extranjeros, como tú, piensen así. Debemos trabajar juntos para
 construir algo nuevo. No podrá empezar aquí porque estamos demasiado controlados pero empezará en otro sitio.}
{167}{}{Hola. ¿Qué puedo hacer por ti?}
{168}{}{¿Puedo ayudarte?}
{169}{}{¿Sí?}
{170}{}{Sólo venía a saludarte.}
{171}{}{Necesito un consejo.}
{172}{}{¿Puedo preguntarte lo que estás haciendo por aquí?}
{173}{}{Hola, entonces. Espero que te vaya bien.}
