{100}{}{Una mesa destartalada con un ordenador polvoriento y viejo
 colocado encima de cualquier manera.}
{101}{}{Según parece el ordenador está tan estropeado que no se puede reparar.}
{102}{}{Muchos circuitos se han quemado por un incendio del EMP.}
{103}{}{No funciona.}
{104}{}{Te cortas las manos con la carcasa.}
