{100}{}{La puerta está cerrada con cerrojo. Nunca has visto un cerrojo como éste.}
{101}{}{La puerta está cerrada, pero sin cerrojo.}
{102}{}{Intentas abrir la puerta, pero no puedes. Te das cuenta de que la puerta está cerrada con cerrojo.}
{103}{}{No puedes forzar el cerrojo de la puerta.}
{104}{}{Fuerzas el cerrojo de la puerta.}
