{100}{}{Nos dirigimos de vuelta al Eje.}
{101}{}{¿Vas a volver con nosotros?}
{102}{}{¡Me encanta este trabajo!}
{103}{}{Espero tener suficientes balas.}
{104}{}{Estoy listo para partir.}

{105}{}{¡Vámonos!}
{106}{}{¡Pongámonos en marcha!}
{107}{}{¡Los hemos matado a todos!}
{108}{}{¡Eso fue fácil!}
{109}{}{¡No hables, mueve el culo!}