{100}{}{Estás viendo a uno del Eje.}
{101}{}{¡No puedo creer que esté vivo y TAMPOCO que los eliminaras a todos! Espera, ¿qué estoy diciendo? Estoy vivo,
 ¿no es verdad? Ahora creeré cualquier cosa que me digas.}
{102}{}{Ahora voy a matarte.}
{103}{}{¡Dame todas tus chapas!}
{104}{}{¡Sal de aquí o te mataré a ti también!}
{105}{}{¡Eh?}
{106}{}{Uh, ¿pero? ¿Tú? [Suspira] Vale, hazlo rápido por favor. Odio el dolor.}
{107}{}{¿No me hagas daño!}
{108}{}{Vale. [Te da 20 chapas.] ¿Puedo irme ya?}
{109}{}{Sí.}
{110}{}{No.}
{111}{}{Uh, ¿por qué?}
{112}{}{¡Por que me da la gana! ¿Tienes algún problema con eso?}
{113}{}{Vale, puedes irte.}
{114}{}{¡No, lo siento, señor! Por favor, no me haga daño... ¡no me gusta el dolor!}
{115}{}{¡No, lo siento, señora! Por favor, no me haga daño... ¡no me gusta el dolor!}
{118}{}{¿Eres imbécil? Quiero decir, un montón de gracias por haberme salvado la vida, amable señor. Debería irme ya. Adiós.}
{119}{}{¿Eres imbécil? Quiero decir, un montón de gracias por haberme salvado la vida, amable señora. Debería irme ya. Adiós.}
{122}{}{Sí... sí... sí señor. ¡Nunca más haré nada malo! Yo... No haré trampas. No mentiré, chantajearé, robaré, asesinaré ni secuestraré.}
{123}{}{Sí... sí... sí señora. ¡Nunca más haré nada malo! Yo... No haré trampas. No mentiré, chantajearé, robaré, asesinaré ni secuestraré.}
{126}{}{¡Sal de aquí!}
{127}{}{¡Eres un mentiroso!}
{128}{}{¡Sí, señor!}
{129}{}{¡Sí, señora!}
