{100}{}{Estás viendo a uno de los guardias de Decker.}
{101}{}{Debes hablar con el jefe.}
{102}{}{Será mejor que estés de nuestra parte.}
{103}{}{Te estaremos vigilando.}
{104}{}{Ni se te ocurra tocar tus armas.}
{105}{}{Si lo miras mal, eres hombre muerto.}
{106}{}{Ten cuidado.}
{107}{}{¡Me rindo!}
{108}{}{De todas formas nunca me gustó trabajar para ese Decker.}
{109}{}{Ahora que Decker y Kane se han ido, ¡ocuparé su lugar!}
{110}{}{Será mejor que, a partir de ahora, tengas cuidado en el Eje. Te estaré vigilando.}

