{100}{}{Estás viendo a Demetre.}
{101}{}{¡Eh tú! ¿Qué tal estás? Me llamo Demetre, Demetre Romara y soy el jefe de la mejor caravana de los yermos. ¿Estás buscando un trabajo?}
{102}{}{Mmm, no pareces demasiado fuerte pero... ¡Debes ser genial
 con un arma si has sobrevivido ahí fuera! ¡Demonios, seguramente eres una fiera cuando llega el momento!}
{103}{}{Pareces estar en forma.}
{104}{}{Pareces bastante fuerte.}
{105}{}{¡Demonios, pareces fuerte!}
{106}{}{¡Demonios, según parece eres capaz de levantar una montaña!}
{107}{}{Sí, ¿y qué?}
{108}{}{¿Y a ti que te importa?}
{109}{}{¿Huh?}
{110}{}{¡Es precisamente lo que estaba buscando! ¡Seguro que te gusta la emoción de la batalla! ¡Balas por todas partes silbando en tus oídos, partiendo a tu enemigo en dos y viendo el miedo en sus ojos! Ahhhh, ¡eso sí que es vida! Pareces el tipo de persona que se ajusta a nuestras necesidades, ¡y pagamos bien! ¡Claro que pagamos bien! Tenemos algunas nuevas ofertas si te interesa; aunque por supuesto que te interesa, ¿no?}
{111}{}{¿Cuál es el sueldo?}
{112}{}{¡Mataré cualquier cosa que se cruce en nuestro camino!}
{113}{}{No gracias.}
{114}{}{Necesito un Chip de agua.}
{115}{}{¿Qué sabes de las caravanas desaparecidas?}
{116}{}{Tengo que irme.}
{117}{}{¡Ugggg, uggg!}
{118}{}{¡Pagamos 600 chapas por trabajo! ¡Eso es! Demonios, la gente
 dice que seguimos las rutas más peligrosas, pero yo digo que son las
 más emocionantes. Hay que poner algo de emoción en la vida, ¿no tengo razón? ¡Claro que la tengo!}
{119}{}{Demonios, ¡creo que es lo que andaba buscando!}
{120}{}{¿Siempre hablas tan alto?}
{121}{}{¿Peligrosas?}
{122}{}{No gracias, tío.}
{123}{}{¡Demonios, claro que sí! Ve a hablar con Keri ahí al lado y ella te dirá
 cuando parte la próxima caravana.}
{124}{}{¿Bub? ¿De qué demonios hablas? Bueno, a mi me importa un comino.}
{125}{}{¿Tienes miedo a los ruidos fuertes o algo así?}
{126}{}{Sí.}
{127}{}{Sólo de noche.}
{128}{}{No, me preguntaba si eres mudo o tonto.}
{129}{}{No, pero me estaban empezando a doler los oídos.}
{130}{}{¡Ja! ¡Quizás las dos cosas! Bueno, si quieres un trabajo, ve a hablar con Keri que está ahí al lado.}
{131}{}{Te crees muy listo, ¿verdad? Bueno, ¡eso no me importa!
 Mientras defiendas las caravanas, yo estaré satisfecho. Si quieres un trabajo, vete a hablar con Keri que está ahí al lado.}
{132}{}{¡Ja! ¡Qué gracia! Bueno, si piensas que puedes soportar
 la oscuridad, ven a verme.}
{133}{}{Por supuesto que es peligroso... ¿por qué otra razón iba a soltar 600 chapas?}
{134}{}{Oh, vale. Adiós.}
{135}{}{Aún así, cogeré el trabajo.}
{136}{}{¡Lárgate de aquí antes de que te vuele la cabeza!}
{137}{}{¡Te volaré la cabeza!}
{138}{}{¡Eso es!}
{139}{}{¡Por supuesto que lo harás! Ve a hablar con Keri que está en la sala contigua, ella lleva la organización.}
{140}{}{Demonios, qué decepción, pero bueno.}
{141}{}{¡Sí! ¡Me gustas! ¡Te contrato! Ve a hablar con Keri, está ahí al lado. Ella te asignará una
 caravana.}
{142}{}{¿Un Chip de agua? Mmm, nunca lo he oído nombrar antes. Quizás quieras
 mirar una de esas tiendas de ahí fuera... tienen de todo. Bueno,
 ¿querías un trabajo?}
{143}{}{Bueno. ¿Cuál es el sueldo?}
{144}{}{La verdad es que no.}
{145}{}{No mucho, yo he perdido sólo dos. No sé por qué
 están molestando sobre todo a los Comerciantes de Ultramar.}
{146}{}{¿Alguna sospecha?}
{147}{}{¿Qué hay de las rutas y el cargamento?}
{148}{}{Vale, gracias.}
{149}{}{Quien quiera que esté haciendo esto tiene que tener muy mala uva.
 Nuestras caravanas están bien armadas y las que desaparecen
 no dejan ni rastro.}
{150}{}{Bueno, ¿cuánto pagan en ese trabajo?}
{151}{}{¿Qué hay de las rutas y el cargamento?}
{152}{}{Vale, gracias.}
{153}{}{Demonios, ¡vamos a lugares más peligrosos que ellos y nuestro cargamento es mejor!}
{154}{}{¿Cómo es que vuestro cargamento es mejor?}
{155}{}{Simplemente estaba comprobando, gracias.}
{156}{}{¡Eres idiota!}
{157}{}{Bueno, vale... quizás no sea mejor,
 pero tenemos más variedad.}
{158}{}{Vale, gracias.}
{159}{}{Ya sabes, Beth se ha enterado de algo sobre las Garras Mortales. ¡Yo lo
 comprobaría si fuese tú! Me han llegado algunos rumores de otras
 fuentes sobre algo que se arrastra durante la noche hacia el noroeste.}
{160}{}{Lo siento, pero nos pagan muchas chapas para asegurarnos de
 que el trabajo está hecho. ¡Sólo contrataremos a los mejores! ¡Necesitamos
 hombres y mujeres de confianza en esas caravanas!}
{161}{}{Como si de verdad quisiera un trabajo, ¡bocazas!}
{162}{}{Disculpa si te he molestado.}
{163}{}{Por favor, ¿puedo elegir otro trabajo?}
{164}{}{¿Huta?}
{165}{}{¡Ya te dije que no te contrataríamos!}
{166}{}{Lo siento, ¡ya he hecho suficiente arriesgándome contigo!}
{167}{}{¡Estás perdiendo el tiempo aquí!}
{168}{}{¡Por favor deja de molestarme!}
{169}{}{Destrózalo.}
{170}{}{Demetre te ignora.}
{171}{}{Demonios, ¡no contrato a drogadictos asquerosos! ¡Si quieres un trabajo será mejor que se te pase el colocón!}
{172}{}{No soy ningún drogadicto... quiero decir... ¡Arg!}
{173}{}{¡Blah!}
{174}{}{Con que de subidón, ¿eh? Demonios, ¡he hecho bien en no contratar otra vez a un maldito yonqui como tú!}
{175}{}{¡Demonios, no! ¡No te imaginas lo que eso significa!
 ¡No podemos permitirnos correr el riesgo! Demonios, ¡yo no sé cómo
 los Comerciantes de Ultramar todavía hacen negocios con todo el lío de esas caravanas desaparecidas!}
{176}{}{Lo siento, pero tendrás que ver si alguna otra casa quiere correr el
 riesgo contigo. No puedo permitirme coger a nadie más.}
{177}{}{Sal de aquí. ¡Me pones enfermo!}
{178}{}{¡Eh! ¡Qué crees que estás haciendo?}
{179}{}{Eso lleva a nuestro almacén.}
{180}{}{Sólo puede abrirse desde el otro lado.}
{181}{}{Tú eres de fuera.}
{182}{}{Estás perdiendo el tiempo.}
{183}{}{Él te ignora.}
{184}{}{Bueno, ¿quieres un trabajo o qué? ¡Te estoy ofreciendo grandes emociones y montones de chapas! ¡Nunca tendrás demasiado de ninguno de los dos!}
{185}{}{Oh, sí. ¿Cuántas serán?}
{186}{}{¡Mataré cualquier cosa que se ponga en mi camino!}
{187}{}{No, gracias.}
{188}{}{Necesito un Chip de agua.}
{189}{}{¿Qué sabes de las caravanas desaparecidas?}
{190}{}{Tengo que irme.}
{191}{}{¿Ruk luk?}
{192}{}{Eh, hiciste un buen trabajo en la última caravana... ¡buen viaje!
 ¿Querías algo?}
{193}{}{Sí, quería otro trabajo.}
{194}{}{Necesito un Chip de agua.}
{195}{}{¿Qué sabes de las caravanas desaparecidas?}
{196}{}{No. Sólo he pasado para saludar.}
{197}{}{Nada, adiós.}
{198}{}{¡Perdimos todo nuestro cargamento! Lo siento, pero me temo que ya no podamos contratarte.}
{199}{}{Tienes suerte, casi te pierdes con aquella caravana.
 Lo siento, pero me temo que no podamos contratarte más.}
{200}{}{No estamos contratando, entonces, ¿qué es lo que quieres?}
{201}{}{¡Piérdete! No estamos contratando.}
{202}{}{Necesito un Chip de agua.}
{203}{}{Dime qué sabes de las caravanas perdidas.}
{204}{}{¡Quiero que te quites de mi vista!}
{205}{}{¡Quiero ver tu cabeza rodando!}
{206}{}{No importa.}
{207}{}{¿Ruk luk?}
{208}{}{¿Crees que eres muy machote? ¡No me hagas reír!}
{209}{}{Bueno, deberías hablar con mi hija, Keri; ¡ella es la que se ocupa de todo eso! Está ahí al lado.}
{210}{}{Ya te lo he dicho. Habla con Keri que está en la sala contigua.}
{211}{}{¿Tu hija?}
{212}{}{¿Esa cosa fea es tu hija? ¡Ahora entiendo muchas cosas!}
{213}{}{Vale.}
{214}{}{Sí, ¡ella es mi orgullo y mi alegría! ¿No es preciosa? Habla con
 ella cuando quieras otro trabajo. Algún día... ojalá sea pronto,
 me podré retirar y ella cuidará de mí.}
{215}{}{¡No podrás hacerlo si los dos estáis muertos!}
{216}{}{Vale, gracias.}
{217}{}{¿Te atreves a insultar a mi familia? ¡Debería arrancarte el corazón!}
{218}{}{¡Lo siento, sólo estaba bromeando!}
{219}{}{¡Yo haré más que insultarte!}
{220}{}{¡Demasiado tarde para disculparte! [Su cara se pone colorada... y con
 voz calmada y controlada.] ¡Sal antes de que cumpla mi amenaza!}
{221}{}{¿Ésas es tu amenaza?}
{222}{}{¡No es una amenaza! ¡Estás a punto de morir!}
{223}{}{Sí, bueno, ¡te daré la última oportunidad!}
{224}{}{No, lo siento. Tengo que irme. ¡Adiós!}
{225}{}{Bueno, tengo que admitir que me he enterado mejor.}
{226}{}{Sí, claro. Nos vemos.}
{227}{}{Bueno, ¡todavía vas a morir!}
{228}{}{Uh, vale.}
{229}{}{Bueno, ¿a qué estás esperando? ¡Hay que llevar las caravanas!}
{230}{}{Todavía no están listas para salir.}
{231}{}{Todavía tengo que hacer algo antes.}
{232}{}{Necesito un Chip de agua.}
{233}{}{Dime qué sabes de las caravanas desaparecidas.}
{234}{}{Vale, adiós.}
{235}{}{¿Rik rok?}
{236}{}{¿Roerow?}
{237}{}{¡Demonios! ¡Te estás perdiendo un montón de emociones! ¡Estoy seguro
 de que hay un montón de gente, criaturas y cosas listas para atacar a
 las caravanas! ¡Nada como un buen tiroteo! Bueno... te daré algo para que
 te entretengas antes de que las caravanas se marchen. [Te lanza una granada
 de mano.]}
{238}{}{¡Demonios! ¿Saldrán alguna vez nuestras caravanas?}
{239}{}{¿Y qué pasa con eso?}
{240}{}{No tardes mucho.}
{241}{}{Keri, ¿nos han contratado ya?}
{242}{}{¡Tienes que matar a tu enemigo antes de que te capture!}
{243}{}{¡Nada como eliminar a nuestros enemigos!}
{244}{}{¡Claro que sí!}
{245}{}{Demonios, ¡¿dónde está mi arma?!}
