{100}{}{Eliminas las Bandas de Chatarra de la Pila.}
{101}{}{Si no eliminas a todas las bandas, se vengarán.}
{102}{}{Los Enterradores y los Locos luchan por controlar el generador de energía.}
{200}{}{Busca a los Locos.}
{201}{}{Los Locos quieren que encuentres a los Enterradores.}
{300}{}{Busca a los Enterradores.}
{301}{}{Los Enterradores quieren que encuentres a los Locos.}
{400}{}{El Generador de Energía.}
{401}{}{Sin el generador, la calidad de vida de los campesinos empeorará.}
{402}{}{El generador es lo más importante de Chatarra. Quien lo controle, controlará Chatarra.}
{403}{}{Hay cables pelados que salen del generador.}
{500}{}{El problema de Phil con el perro.}
{501}{}{Phil tiene algunos problemas con un perro.}
{502}{}{El perro tiene tanta hambre que se comería a Phil.}
