{100}{}{Estás viendo a un Loco.}
{101}{}{Estás viendo a un bandido.}
{102}{}{Nos llaman Locos y tú has cometido un error al aparecer por aquí.}
{103}{}{¿Quieres empezar algo con nosotros?}
{104}{}{Éste no es tu lugar.}
{105}{}{No creas que puedes llegar aquí y empezar algo tan fácilmente.}
{106}{}{Ten cuidado o acabarás enterrado, Enterrador.}
{107}{}{Sí, esos Enterradores se van a enterar.}
{108}{}{Chatarra de la Pila no será lo mismo sin esos Enterradores. ¡Este lugar será nuestro!}
{109}{}{¡Ja, ja, ja, ja! ¡Ja, ja, ja, ja!}
{110}{}{¡Locos! ¡Locos! ¡Locos! ¡Sí!}
{111}{}{¿Te sabes el chiste del pollo y la zorra?}
{112}{}{Calma.}
{113}{}{Quien ríe el último, ríe mejor.}
{114}{}{La vida es un chiste, ¿o no?.}
{115}{}{Si no fuera por los Enterradores, controlaríamos la ciudad. O al menos ese Lenny sabría lo que vale un peine.}
{116}{}{Vuélvete loco.}
{117}{}{¿Crees que eso te salvará de Baka?}
{118}{}{¿Qué te pasó? ¿Tu madre te daba en la cabeza cuando eras niño?}
{119}{}{Si fuera tan feo, me suicidaría.}
{120}{}{Vosotros los Enterradores sois todos iguales.}
{121}{}{Sólo un loco haría algo tan estúpido. Oh, espera, yo soy un Loco.}

