{100}{}{Estás viendo a Diana, una Pirata del desierto.}
{101}{}{Soy Diana. ¿Cómo puedo ayudarte hoy?}
{102}{}{Estoy buscando a una mujer llamada Tandi. ¿La has visto?}
{103}{}{No importa, gracias.}
{104}{}{¿Qué tal una cita?}
{105}{}{¿Qué haces aquí?}
{106}{}{¿Qué me puedes decir de este campamento?}
{107}{}{¿Eurrreh?}
{108}{}{Si ella es una de esas mujeres de las Arenas Sombrías, quizás deberías buscar por ahí.
 Yo sólo trabajo aquí.}
{109}{}{Oh. Bueno, gracias de todos modos.}
{110}{}{¿Puedes arreglarme el equipo?}
{111}{}{Como puedes ver, estoy demasiado ocupada en este momento para atender tu
 petición.}
{112}{}{Garl me tiene arreglando el equipo del campamento en este momento. 
 No tengo tiempo para reparar nuestras cosas y las de todos los que pasan por aquí. Lo siento.}
{113}{}{Soy la armera de este campamento. Soy la única con la destreza
 necesaria para reparar y mantener las armas y equipos
 de los hombres de Garl.}
{114}{}{¿Puedes arreglarme el equipo?}
{115}{}{¿Qué me puedes decir de este campamento?}
{116}{}{Lo lleva Garl Mano Letal. Es un jefe terrible y
 despiadado. Se asegura de que todos sobrevivamos a la cruda realidad
 del desierto.}
{117}{}{Estoy buscando a una mujer llamada Tandi. ¿La has visto?}
{118}{}{¿Puedes repararme el equipo?}
{119}{}{Ahora estoy ocupada. Por favor vete a otro sitio.}
{120}{}{Tu eres el nuevo amigo de Garl, ¿verdad? ¿Qué quieres?}
{121}{}{Mmm. Parece que tu equipo funciona. Tengo obligaciones más importantes.}

