{100}{}{Aquí hay algo raro. Parece que se puede utilizar con tu PIPBoy.}
{101}{}{PIPBoy muestra: Archivo encontrado en Sistema. Abortando la carga.}
{102}{}{PIPBoy muestra: Cargando datos del disco.}

