{100}{}{La taquilla está bajo llave.}
{101}{}{Detectas una trampa en la taquilla y la desactivas.}
{102}{}{Detectas una trampa en la taquilla, pero no consigues desactivarla.}
{103}{}{Detectas una trampa en la taquilla, ¡pero la activas accidentalmente!}
{104}{}{Desactivas la trampa.}
{105}{}{No consigues desarmar la trampa.}
{106}{}{¡Activas la trampa accidentalmente!}
{107}{}{Abres la taquilla.}
{108}{}{No consigues abrir el cerrojo de la taquilla.}
{109}{}{La taquilla ya está abierta.}
{110}{}{Al tocar el cerrojo echas el seguro. Ahora ya no hay manera de abrir el cerrojo.}
{111}{}{Te das cuenta de que hay un dispositivo explosivo ordinario en la taquilla.}

