{100}{}{Estás viendo a Dugan, un adicto a la Nuka-Cola.}
{101}{}{Estás viendo a un hombre muy alto y delgado con gafas.
 Tiene un botella de Nuka-Cola entre las manos.}
{102}{}{¿Sí?}
{103}{}{Sólo estaba echando un vistazo, gracias.}
{104}{}{¿Qué haces por aquí?}
{105}{}{¿Qué pasa con la Nuka-Cola?}
{106}{}{¿Quién manda aquí?}
{107}{}{Ah, no importa.}
{108}{}{Dah, Cola, ¿buena?}
{109}{}{Bueno, entonces no malgastes mi tiempo.}
{110}{}{Me dedico a filosofar sobre la vida y a ayudar a los Navajas a
 comprender el verdadero significado de la Nuka-Cola.}
{111}{}{¿Qué tiene de maravilloso la Nuka-Cola?}
{112}{}{¿Eso es todo? No parece que eso ayude mucho a nadie.}
{113}{}{¿Cuanta te bebes cada día?}
{114}{}{¿Puedo preguntarte algo más?}
{115}{}{Ah, vale. Nos vemos.}
{116}{}{Así es la vida... Bueno, en realidad, si no me la tomo cada hora,
 me entra un dolor de cabeza horrible.}
{117}{}{¿Y? [Dugan levanta las cejas.]}
{118}{}{Unos cinco litros al día.}
{119}{}{Cuchilla es la mujer con la que deberías hablar.}
{120}{}{Soy la persona más tonta del mundo... bueno, igual que tú. ¡Sal de aquí!}
{121}{}{¡Necesito otra Nuka-Cola!}
{122}{}{¡Qué le ha pasado a mi pelo!}
{123}{}{Agua Carbonatada, Color de Caramelo, Aspartamo, Ácido Fosfórico,
 Benzoato de Potasio (para proteger el sabor), Sabores Naturales, Ácido Cítrico, Cafeína...}
{124}{}{Es una lástima que no nos quede Light.}
{125}{}{¿Dónde han ido esas mujeres?}
