{100}{}{No ves ningún panel de control en este emisor. Quizás hay otro
 modo para reducir este campo de fuerza.}
{101}{}{Desactivas temporalmente el campo de fuerza, con el consiguiente daño para el emisor.}
{102}{}{Destruyes completamente el emisor de campo de fuerza y el campo de fuerza desaparece.}
{103}{}{Desactivas temporalmente el emisor de campo de fuerza.}
{104}{}{No puedes hacer nada con el emisor de campo de fuerza.}
{105}{}{Activas el emisor de campo de fuerza.}
