{100}{}{Estás viendo al Camarero.}
{101}{}{Sí, ¿qué quieres?}
{102}{}{Agua.}
{103}{}{Cerveza.}
{104}{}{Alcohol.}
{105}{}{Cualquier cosa que me coloque enseguida.}
{106}{}{Nada.}
{107}{}{¿Eh?}
{108}{}{Si no tienes chapas, ¡ya puedes marcharte!}
{109}{}{Sírvete tú mismo.}
{110}{}{Creo que ya has tenido suficiente, muchacho.}
{111}{}{Creo que ya has tenido suficiente, muchacha.}
{112}{}{Sí... buena elección.}
{113}{}{Serán dos chapas.}
{114}{}{Vale.}
{115}{}{No, gracias.}
{116}{}{Serán cinco chapas.}
{117}{}{Vale.}
{118}{}{Serán diez chapas.}
{119}{}{Ummm, para uno de tu tamaño...}
{120}{}{ }
{121}{}{ diez}
{122}{}{ veinte}
{123}{}{ treinta}
{124}{}{ cuarenta}
{125}{}{ cincuenta}
{126}{}{ sesenta}
{127}{}{ setenta}
{128}{}{ ochenta}
{129}{}{ noventa}
{130}{}{ cien}
{131}{}{ chapas serán suficientes.}
{132}{}{¡Bien! Serán }
{133}{}{ chapas otra vez.}
{134}{}{¡Vuelve otra vez!}
{135}{}{No importa.}
{136}{}{Toma. [El camarero te sirve una pequeña taza sucia llena de}
{137}{}{ agua turbia. Tras beber el agua, tienes un extraño}
{138}{}{ sabor en la boca.]}
{139}{}{Toma. [El camarero te sirve otra taza llena del mismo}
{140}{}{ líquido, y tras beberlo, te acuerdas del}
{141}{}{ extraño sabor de la última vez...]}
{142}{}{Debe ser entretenido... [El camarero te sigue dando y}
{143}{}{ pierdes la cuenta. Al rato oyes un ruido seco, luego te}
{144}{}{ das cuenta de que estás tumbado en el suelo, boca abajo...]}
{145}{}{Aqui tienes más... [El camarero sigue poniendo vasos mientras todos}
{146}{}{ en el bar cantan...]}
{147}{}{ ...}
{148}{}{ ...}
{149}{}{ ...}
{150}{}{ [De repente todo empieza a desvanecerse...]}
{151}{}{No parecías capaz de tolerar tal cantidad de}
{152}{}{ alcohol.}
{153}{}{Es una pena. Todos estábamos impacientes por verte}
{154}{}{ "actuar" de nuevo.}
{155}{}{Oh... ¿no nos vas a enseñar tu material de nuevo? Bien,}
{156}{}{ vale, aquí tienes tu cerveza. ¿Algo más?}
{157}{}{¿Estás seguro que puedes resistir la tentación? Porque diste la}
{158}{}{ nota la última vez. Vale, aquí tienes. [El camarero te tiende}
{159}{}{ una botella de alcohol.] ¿Algo más?}
{160}{}{Aquí tienes. [El camarero te tiende una botella de cerveza.] ¿Algo}
{161}{}{ más?}
{162}{}{¡Emborráchame de nuevo!}
{163}{}{Aquí tienes. [El camarero te tiende una botella de alcohol.]}
{164}{}{ ¿Algo más?}
{165}{}{Tienes muy mal sabor de boca.}
{166}{}{Piensas que te va a estallar la cabeza.}
{167}{}{Ves a un croupier de dados.}
{168}{}{Ves a un croupier de ruleta.}
{169}{}{Ves una máquina tragaperras.}
{170}{}{Te das cuenta de que los tipos no tienen muy buena pinta.}
{171}{}{Piensas que los dados están amañados.}
{172}{}{Piensas que la mesa está trucada.}
{173}{}{Hagan sus apuestas. }
{174}{}{5 chapas.}
{175}{}{15 chapas.}
{176}{}{25 chapas.}
{177}{}{50 chapas.}
{178}{}{No gracias.}
{179}{}{Rurh.}
{180}{}{Lo siento, pero no estás en condiciones de apostar [Miras al}
{181}{}{ juego y te sientes muy confuso.]}
{182}{}{Lo siento, ojalá tengas más suerte la próxima vez.}
{183}{}{¡Ganas! [Pulsas.]}
{184}{}{¡Ganas! [Duplicas tus chapas.]}
{185}{}{¡Ganas! [Triplicas tus chapas.]}
{186}{}{Necesitas tener chapas para jugar, tío.}
{187}{}{Necesitas tener chapas para jugar, tía.}
{188}{}{Te das cuenta de que el tipo tiene razón.}
{189}{}{[¿Cuántas chapas quieres meter?]}
{190}{}{1 chapa.}
{191}{}{2 chapas.}
{192}{}{3 chapas.}
{193}{}{4 chapas.}
{194}{}{5 chapas.}
{195}{}{Nada.}
{196}{}{[No sabes qué hacer con él, pero es bonito.]}
{197}{}{[Pierdes.]}
{198}{}{[Pulsas.]}
{199}{}{[Duplicas tus chapas.]}
{200}{}{[Triplicas tus chapas.]}
{201}{}{[No tienes chapas suficientes.]}
{202}{}{Actualmente tienes }
{203}{}{ chapas.
 ¿Cuántas quieres apostar?}
{204}{}{ ¿Quieres jugar de nuevo?}