{100}{}{Estás viendo al Paladín Farli.}
{101}{}{Saludos.}
{102}{}{¿Chad'ra chu ka?}
{103}{}{Katja chu nee ka Chak'ra Farli.}
{104}{}{Farli, nee ko }
{105}{}{ mat'chak o Drake.}
{106}{}{Ah, Drake ko mat'chak.}
{107}{}{Saluda a nuestro amigo común si lo vuelves a ver.}
{108}{}{La hermandad me recuerda a casa.}
