{100}{}{Bomba de hidropresurización, alambre electro-fibroso, sello de aspersión
 magnética, banda conductora, adaptadores de tres salidas... una buena colección de
 piezas.}
{101}{}{Estas partes pueden ser utilizadas por Miles para arreglar las granjas hidropónicas.}
