{100}{}{Estás viendo a un granjero.}
{101}{}{Hola, forastero. ¿Te gustan mis cultivos?}
{102}{}{¡Buenos días!}
{103}{}{¡Buenas tardes!}
{104}{}{¡Buenas noches, amigo!}
{105}{}{¿No hace un buen día?}
{106}{}{El suelo es mucho más fértil de lo que parece.}
{107}{}{Estoy intentando salvar estos árboles. Creo que funciona.}
{108}{}{Tendría que haber una caravana fertilizadora. Ahora hay chapas.}
{109}{}{Pasa, hay mucho espacio.}
{110}{}{Hace un poco de fresco ahí fuera. Siéntate.}
{111}{}{Me gusta la agricultura.}
{112}{}{¿Sabías que las plantas crecen más si eres amable con ellas?}
{113}{}{Ojalá tuviera más terreno.}
{114}{}{¿Sabías que había grandes cantidades de agua potable?}
{115}{}{He leído algo sobre los ríos. Ojalá hubiera uno cerca de mis terrenos.}
{116}{}{Ojalá los días fueran más largos; hay mucho que hacer.}
