{100}{}{Parece raro. Crees que puede utilizarse en tu PIPBoy.}
{101}{}{PIPBoy muestra: Archivo encontrado en Sistema. Abortando la carga.}
{102}{}{PIPBoy muestra: Transmitiendo datos desde el disco.}
