{100}{}{Estás viendo al conductor de caravanas de los Comerciantes de Ultramar.}
{101}{}{Eh, si buscas un trabajo en una caravana, deberías hablar con Rutger. Justo ahí.}
{102}{}{Vas a tener que hablar con Rutger.}
{103}{}{Así que has firmado. Me alegro. Así que ya sabes, salimos cada diez días aproximadamente:
 el 8, el 18 y el 28 de cada mes. Ahora mismo hacemos expediciones hacia la Hermandad, Ciudad Vertedero y al Cementerio de Angel.}
{104}{}{¿Y cuánto pagan?}
{105}{}{Um.}
{106}{}{Te daremos 400 chapas. Dirás que no es mucho, pero viajamos a menudo y no te
 vas a jugar la vida por menos. Pero ganas esas chapas por cada viaje; no es que tengas que ir y volver, pero
 ganarás 800 chapas si lo haces.}
{107}{}{ Partimos hoy. ¿Te interesa?}
{108}{}{ Salimos en }
{109}{}{Vacío }
{110}{}{}
{111}{}{. ¿Te interesa?}
{112}{}{Aún te ofrezco trabajo, aunque... no importa. ¿Te interesa?}
{113}{}{Claro.}
{114}{}{No.}
{115}{}{Puede.}
{116}{}{Sí, sí.}
{117}{}{¿Eh?}
{118}{}{Vale. No hay problema. Házmelo saber si cambias de idea.}
{119}{}{¿Cambiarás de opinión?}
{120}{}{Vuelve si continúas buscando algo que hacer. Los días 8, 18, y 28. Adiós.}
{121}{}{Uh, no vas a funcionar si no sabes ni dónde tienes los pies. Lo siento, tío.}
{122}{}{Asómate por aquí cuando te encuentres mejor.}
{123}{}{Colega, no pareces hacerlo demasiado bien. Deberías comer algo, vete a ver a Bob.}
{124}{}{¡Vete de aquí!}
{125}{}{Yo no podría abandonar mi material, ¿y tú? ¿Por qué lo has hecho?}
{126}{}{Mira, soy un bicho raro del espacio exterior, ¡y soy malo!}
{127}{}{No quería hacerlo, pero tengo hambre y tengo hijos que alimentar.}
{128}{}{¡Te sacaré el corazón con una cuchara!}
{129}{}{[Te rindes]}
{130}{}{[Atacas]}
{131}{}{Así que me escupes en la cara, ¿eh? Creo que la única manera de meterlo en tu cerebro, es sacártelo
 del cuello.}
{132}{}{Vale, pero eso no lo soluciona todo. Aún tienes que largarte de aquí.}
{133}{}{¿Crees que me trago tus mentiras? ¡Guardias!}
{134}{}{Puede que adquieras mejores modales si te metemos en el tanque. ¿Te vienes por las buenas o tendremos
 que recurrir a métodos más drásticos?}
{135}{}{¡Te veré en el infierno!}
{136}{}{Sí. Lo siento.}
{137}{}{Así que eres un tipo duro, ¿eh? ¿Buscas otra bronca?}
{138}{}{Si no te largas de aquí, ¡tendré que llamar a la policía!}
{139}{}{¡Guardias! ¡Policía!}
{140}{}{Creo que deberías irte.}
{141}{}{Lo siento, pero no voy a darte un empleo.}
{142}{}{Me encantaría darte un empleo, pero no va a ser posible.}
{143}{}{Vete.}
{144}{}{Pareces un buen chico, pero no soy tu tipo.}
{145}{}{¡Vale entonces! Se pagan 400 chapas. ¿Qué trayecto prefieres?}
{146}{}{Me alegro. Vuelve en }
{147}{}{8}
{148}{}{18}
{149}{}{28}
{150}{}{}
{151}{}{}
{152}{}{Hermandad del Acero.}
{153}{}{. Saldrás entonces. Como siempre, se pagan 400 chapas.}
{154}{}{Vale.}
{155}{}{Lo siento, no puedo esperar.}
{156}{}{No estoy seguro de lo que ocurrió, se perdió toda la caravana. Qué raro que tal cosa pasara y que tú fueras el único en sobrevivir. Las cosas no ocurren así por lo general. No creo que pueda contratarte
 más por eso. Seguro que entiendes mis razones.}
{157}{}{Ciudad Vertedero.}
{158}{}{Cementerio de Angel.}
{159}{}{Um, ahora no. Puede que en otra ocasión.}
{160}{}{Me alegro, reuniré al resto del equipo.}
{161}{}{Bien.}
{162}{}{Lárgate de aquí. ¡Suerte!}
{163}{}{Intenta evitar los problemas. Ten cuidado.}
{164}{}{Ten cuidado ahí fuera, el Cementerio no es el lugar más seguro.}
{165}{}{Está bien. Esas carreteras negras son muy extrañas, pero son muy cómodas para viajar.}
{166}{}{Definitivamente hay algo malo ahí fuera. Yo tendría cuidado con las amistades por ahí.}
{167}{}{Bien. Ciudad Vertedero no es un mal sitio.}
{168}{}{Oh, y vete a ver a Killain, y salúdale de mi parte. Colega, qué momentos pasamos en las caravanas...}
{169}{}{He oído que hay un doctor por ahí. Trabaja con muertos, o eso es lo que dicen.}
{170}{}{¿En qué estabas pensando al abandonar la caravana? Regresó sana y salva, pero sólo fue cuestión de suerte.}
{171}{}{¿Me das otra oportunidad?}
{172}{}{Nada.}
{173}{}{¡Yo no la cago!}
{174}{}{¿Ig wa neeka rooola?}
{175}{}{Lig.}
{176}{}{La has vuelto a cagar. Simplemente no eres el más indicado para este trabajo.}
{177}{}{¿Por qué debería?}
{178}{}{No deberías.}
{179}{}{Porque voy a abrirte una brecha en la cabeza si no lo haces.}
{180}{}{Tenía cosas mejores que hacer que vigilar una estúpida caravana.}
{181}{}{No sabía que no podía irme. Todo parecía ir bien.}
{182}{}{Ya veo... estás enganchado. Bien, haz lo que quieras con tu vida.}
{183}{}{Lamento que te sientas así.}
{184}{}{Me sorprende que no lo hayas hecho antes. Pero si es así, no le haré daño a nadie si te doy
 otra oportunidad.}
{185}{}{Has hecho un buen trabajo. ¿Quieres hacer otro?}
{186}{}{Claro.}
{187}{}{No.}
{188}{}{Puede.}
{189}{}{¡Eeeh!}
{190}{}{Lub.}
{191}{}{¿Ya estás equipado? Partimos hoy.}
{192}{}{Sí.}
{193}{}{¡No!}
{194}{}{¡Ajj!}
{195}{}{Si no, se lo daré a otro, no te preocupes por eso. No estás obligado a nada...
 hasta que salgas con la caravana, ¿vale?}
{196}{}{La próxima caravana no sale hasta }
{197}{}{día 8}
{198}{}{día 18}
{199}{}{día 28}
{200}{}{}
{201}{}{}
{202}{}{}
{203}{}{. Vuelve por aquí si aún quieres el trabajo. }
{204}{}{Enero, }
{205}{}{Febrero, }
{206}{}{Marzo, }
{207}{}{Abril, }
{208}{}{Mayo, }
{209}{}{Junio, }
{210}{}{Julio, }
{211}{}{Agosto, }
{212}{}{Septiembre, }
{213}{}{Octubre, }
{214}{}{Noviembre, }
{215}{}{Diciembre, }
{216}{}{La Hermandad del Acero, ¡allá vamos! Bien... No voy contigo, pero sabes a lo que me refiero.}
{217}{}{Vale, sal de mi vista inmediatamente. Esos fanáticos de la Hermandad te esperan.}
{218}{}{¡Espero que te gusten las montañas! Te diriges hacia ellas. Encontrarás mucho movimiento allí.}
{219}{}{Listo para partir; ¡te encaminarás hacia las montañas! ¡Te divertirás de lo lindo!}