{100}{}{Estás viendo a un mercader del grupo de caravanas de los Comerciantes de Ultramar.}
{101}{}{Estás viendo a un mercader del grupo de caravanas de la Caravana Carmesí.}
{102}{}{Estás viendo a un mercader del grupo de caravanas de los Mercaderes de Agua.}
{103}{}{¿Querías volver al Eje? Te pagaré otros 400 vales.}
{104}{}{¿Querías volver al Eje? Te pagaré otros 600 vales.}
{105}{}{¿Querías volver al Eje? Te pagaré otros 200 vales.}
{106}{}{Sí.}
{107}{}{No.}
{108}{}{Ug.}
