{100}{}{Estás viendo a un chico flaco y descuidado.}
{101}{}{Creo que no tengo que hablar contigo. Vete de aquí.}
{102}{}{¿Por qué llevas un arma? Nosotros no tenemos nada, ni siquiera pescado.}
{103}{}{Hola. ¿Qué quieres?}
{104}{}{¿Cómo va la pesca?}
{105}{}{Estoy un poco escaso de suministros...}
{106}{}{¿Has visto algo raro últimamente?}
{107}{}{¿Quieres conocer mis aventuras en las cuevas de los Escorpiones Rad?}
{108}{}{¡Colre!}
{109}{}{Hola. ¡No eres tú quien va por ahí ayudando a la gente? Debes
 tener muchas historias interesantes que contar.}
{110}{}{¿De dónde vienes?}
{111}{}{Hola. Veo que no eres tan estúpido como para estar pescando aquí. ¿Qué ocurre?}
{112}{}{No lo sé. Papá y yo hemos estado recorriendo los yermos mucho tiempo. Teníamos un amigo, un cazador de escorpiones, pero se volvió loco y tuvimos que matarlo
 y entonces...}
{113}{}{Mmm, puede que no deba hablar de esto.}
{114}{}{Háblame de tu padre.}
{115}{}{¿Qué pasa con los escorpiones?}
{116}{}{Menuda mierda. Lo siento. No debería usar la palabra "mierda". Papá cree que la gente
 que dice mierda todo el tiempo son o idiotas o fracasados. Papá siempre intenta parecer fino.}
{117}{}{Estoy de acuerdo con tu padre.}
{118}{}{Lo siento, no soy el más indicado para hablar de suministros.}
{119}{}{Vi una cosa grande parecida a una araña gigante con dos cabezas, y una de ellas
 cabeza perecía humana. Papá cree que he recibido muchas radiaciones. No lo sé. El agua
 contaminada sienta mal al coco.}
{120}{}{¿Sí, como qué?}
{121}{}{¿Qué es colre?}
{122}{}{¡Claro!}
{123}{}{¡Lo peor cuando se cazan Escorpiones Rad es tener que esperar a que
 caigan en la emboscada!}
{124}{}{¡Lo peor cuando se cazan Escorpiones Rad es perseguirlos cuando escapan!}
{125}{}{Lo peor cuando se cazan Escorpiones Rad es ser picado en la
 cara con su aguijón.}
{126}{}{Sí. ¿Has oído hablar de los Piratas que cayeron en las garras
 de los Escorpiones Rad. Los maltrataron y se los comieron vivos a todos menos a uno que escapó con media cara comida.}
{127}{}{Tío, ¡ésta si que ha sido buena!}
{128}{}{Bien, es un tío aburrido y pesado y no estoy seguro de que sea mi verdadero padre.
 Creo que me raptó cuando yo era un bebé. Pero me da de comer casi siempre,
 entonces supongo que me cae bien.}
{129}{}{Son grandes y horribles y cada vez más peligrosos. Papá dice
 que eran héroes que deambulaban por los yermos y lo mataban todo,
 pero la mayoría de ellos están ya muertos, supongo.}
{130}{}{¿Qué tipo de héroes?}
{131}{}{Sí, los adultos siempre están de acuerdo. Es bastante estúpido.}
{132}{}{El Gran Henry iba con nosotros, pero era mejor que papá y que yo; hasta que
 se volvió loco e intentó estrangularme. ¡Papá tuvo que dispararle!}
{133}{}{¿Tiene buena puntería tu padre?}
{134}{}{¿Quién es el Gran Henry?}
{135}{}{Bien, eso me gusta. Pero debería volver a la pesca, o empezaremos
 a tener mucha hambre y ¡tendremos que comerte!}
{136}{}{Muchos héroes. El tipo que fundó la Hermandad del Acero, Roger
 Maxim, era un buen asesino de escorpiones. ¡Cuando sea mayor, descubriré dónde
 están y me uniré a ellos!}
{137}{}{Suena bien.}
{138}{}{Es realmente difícil unirse a la Hermandad. Y un viaje muy peligroso.}
{139}{}{Está bien, supongo. En realidad, le vi meter una bala entre los ojos de un
 Escorpión Rad a unas setenta yardas, pero fue un disparo con suerte.}
{140}{}{Era un tipo del sur. Una especie de Pirata que intentaba evitar
 la tierra, no a la gente. Era realmente un tipo fantástico, pero a veces perdía la cabeza
 y una vez... eh... no importa.}
{141}{}{Sí, voy a ser un héroe como él. ¡Puedes apostar a que sí!}
{142}{}{¿Piensas que resulta fácil vivir así? No le tengo miedo a las dificultades y
 nada es seguro ahí fuera, así que no estoy de broma. Ya soy lo suficientemente mayor
 como para mantenerme solo.}
{143}{}{¿Y qué hay de la pelea entre un Escorpión Rad y un hombre?}
{144}{}{Sólo unas doce veces...}
{145}{}{Oh, sí, señor.}
{146}{}{Creo que esta vez pescaré un resfriado. }
{147}{}{¡Date prisa! ¡Me muero de hambre!}
{148}{}{Hace mucho tiempo que no coges nada. Me he olvidado de
 su sabor.}
{149}{}{Papá, ¿has oído algo...?}