{100}{}{Ve a que te examine el doctor y no tendré que
 preocuparme de ver tu cara por aquí.}
{101}{}{Está cerrado. Vuelve después.}
{102}{}{Tengo que ver al doctor.}
{103}{}{Vale, lo haré.}
{104}{}{Es imprescindible que vea al doctor.}
{105}{}{Unnn.}
{106}{}{Hace buen tiempo, ¿eh?}
{107}{}{¡Qué pena! Márchate de aquí de una vez y no vuelvas hasta mañana. Esta consulta no abre por las noches.}
{108}{}{Espera un momento, tengo que consultarlo con el doctor.}
{109}{}{¿Qué quieres ahora?}
{110}{}{Tengo que ver al doctor.}
{111}{}{¿Está libre el doctor?}
{112}{}{¡Unnn!}
{113}{}{No puedes. El doctor está durmiendo. Vuelve luego.}
{114}{}{No sé por qué no hablas personalmente con él.}
{115}{}{Vale, de acuerdo. Vete.}
{116}{}{Oye, esto es una propiedad privada. Deberías irte ahora.}
{117}{}{Véte a la mierda.}
{118}{}{Si no desapareces de mi vista, yo mismo te daré una razón para
 visitar al doctor.}
{119}{}{¿No sabes que las mujeres son el sexo débil?}
{120}{}{¿Piensas que soy débil? Entonces mira...}
{121}{}{Ya me voy.}
{122}{}{Guárdate tus absurdas amenazas y vuelve con mamá. Estás hablando
 con un machote.}
{123}{}{¿Piensas que estoy débil? Entonces mira...}
{124}{}{Ya me voy.}
{125}{}{¡Ehh! Si de verdad quieres verlo, pasa ahora.}
{126}{}{Bien, ¿cuándo estará aquí el doctor?}
{127}{}{El doctor recibe pacientes de 8 a 17. Ahora vete de aquí.}
{128}{}{¿Cuándo estará aquí el doctor?}