{100}{}{No estamos aquí para hablar.}
{101}{}{Te seguiré hasta la muerte.}
{102}{}{Es un trabajo muy importante, ¿no?}
{103}{}{Nicole dice que debemos causar el máximo daño posible.}
{104}{}{Quién será mi próxima víctima.}
{105}{}{¿Por qué estamos charlando así?}
{106}{}{No me gustan esas cabezas oscuras sin seso, gracias.}
{107}{}{Esto podría ser peligroso.}
{108}{}{Tiempo de irse.}
{109}{}{Este lugar parece una mierda colgada de la pared.}
{110}{}{Creo que voy a vomitar.}
{111}{}{Nicole nos dijo que volviéramos en cuanto abandonaras la Catedral.}
{112}{}{Me alegro de verte. Dejémoslo así.}
