{100}{}{Estás viendo a un Seguidor del Apocalipsis muy estudioso al parecer.}
{101}{}{Por favor, no me molestes. Intento estudiar.}
{102}{}{Buscamos conocimientos para protegernos del los Niños.}
{103}{}{Nicole dice que el conocimiento de nuestros enemigos nos ayudará a ser superiores.}
{104}{}{Hola.}
{105}{}{Bienvenido a los Seguidores del Apocalipsis. Por favor, respeta la santidad de nuestra biblioteca.}
{106}{}{Que tengas un glorioso día.}
{107}{}{Todo conocimiento es sagrado.}
{108}{}{Debemos protegernos.}
{109}{}{¿Quién sabe lo que ocurre en la Catedral de los Niños?}
{110}{}{El conocimiento es vida.}
{111}{}{Nicole nos ayuda a comprender la santidad del conocimiento.}
{112}{}{Nicole nos guía para recuperar lo perdido.}
{113}{}{Debo encontrar ese libro para Nicole.}
{114}{}{Katja debe de andar por aquí cerca. ¡Katja!}
{115}{}{Los Niños han sido expulsados de la Catedral.}
{116}{}{Fuiste tú, ¿verdad?}
{117}{}{Ahora, estamos a salvo y podemos descubrir el conocimiento necesario para volver a construir la civilización.}
{118}{}{¿No es glorioso que los Niños ya no representen una amenaza?}
{119}{}{Que tengas un glorioso día.}

