{100}{}{Estás viendo al Suplente Fry.}
{101}{}{Tenía muchas ganas de encontrarte, asesino. Espero que no te quedes mucho tiempo. Te vigilaré muy de cerca mientras estés aquí. No te metas en líos en mi cuidad. Estoy buscando cualquier excusa para echarte.}
{102}{}{Hola, colega. El Suplente Tony Fry a tu servicio.}
{103}{}{¿Qué lugar es éste?}
{104}{}{Me ha encantado conocerte. Adiós.}
{105}{}{Wug.}
{106}{}{¡Ack!}
{107}{}{Oh, ¡uno nuevo! ¡Bienvenido al Eje! Has llegado a la mayor ciudad de
 la costa y por lo que sabemos la mayor cuidad del mundo.
 Pensé que formabas parte de la caravana. ¿Has venido con ellos?}
{108}{}{Sí.}
{109}{}{No.}
{110}{}{No me sorprende. La mayoría de los nuevos miembros de nuestra ciudad vienen con
 las caravanas, a pesar de las caravanas desaparecidas. Es una bonita ciudad,
 pero ten cuidado con tus amistades. La gente como Decker y sus seguidores
 puede traerte problemas.}
{111}{}{Estoy sorprendido. Las cosas están chungas ahí, especialmente
 por lo de las caravanas desaparecidas. Pero ahora estás a salvo. Limítate a apartarte del
 Halcón Maltés. Son una panda de camorristas. Decker y su panda.}
{112}{}{¿Quién es Decker?}
{113}{}{Sí, bien... Estoy bastante fuerte.}
{114}{}{¿Qué es eso de que han desaparecido caravanas?}
{115}{}{¿Cómo puedo conseguir algunas chapas?}
{116}{}{Eso es todo, gracias.}
{117}{}{Si tú lo dices. Pero, ¿tenías otras preguntas?}
{118}{}{Realmente es una tragedia. Algunas caravanas han desaparecido.
 Butch, que está con los Comerciantes de Ultramar, ofrece una recompensa a cambio de información.
 Deberías acercarte al mercado de mercaderes si te interesa.}
{119}{}{Es el dueño del Halcón Maltés, en el Mercado de Mercaderes, pero no me
 uniría a él si no quieres líos. No es más que una
 bestia asesina, pero el Sheriff no me dejará arrestarlo si no tengo pruebas.}
{120}{}{No hay problema. Lo creas o no, nuestra ciudad es bastante segura y nuestros policías
 son unos buenos defensores de la paz y están muy preparados. No deberías tener problemas,
 sólo evita el Halcón Maltés.}
{121}{}{Lo siento, no te entiendo. ¿Puede que necesites curarte?
 Los Niños de la Catedral están al Sur. Justo abajo, pasando el
 Mercado de Mercaderes hasta donde los Mercaderes de Agua. Están al lado de los Mercaderes
 de Agua.}
{122}{}{Sigo vigilándote, asesino.}
{123}{}{¡Bestia asesina!}
{124}{}{No puedo creer que el Sheriff haya muerto...}
{125}{}{¡Aquí estás, víbora, ladrón! Casi no te conocía.
 ¡Guardias!}
{126}{}{Claro.}
{127}{}{Cógeme si puedes.}
{128}{}{No.}
{129}{}{¡ARJ!}
{130}{}{Hola de nuevo. Espero que te guste nuestra ciudad. Un chico como tú siempre es bien recibido. Si decides quedarte, estoy seguro de que serás una ayuda valiosa para el Eje.}
{131}{}{Hola de nuevo. Espero que te guste nuestra ciudad. Una chica como tú siempre es bien recibida. Si decides quedarte, estoy seguro de que serás una ayuda valiosa para el Eje.}
{132}{}{Hola de nuevo. ¿Qué puedo hacer por ti?}
{133}{}{¿Sí? No tengo todo el día. Intento vigilar la puerta principal.}
{134}{}{¡He de denunciar un delito!}
{135}{}{¿Hay un hospital? Estoy herido.}
{136}{}{¿Dónde están las tiendas?}
{137}{}{¿Dónde hay trabajo por aquí?}
{138}{}{Adiós.}
{139}{}{¿Ehho?}
{140}{}{Ooga.}
{141}{}{¿En serio? Oh, deberías hablar con el Sheriff. No puedo abandonar mi puesto
 ahora. Tengo que... eem, ahuyentar a cualquier Pirata que pueda venir.
 Además, no soy demasiado sociable.}
{142}{}{Oh, lo siento, no me había dado cuenta. Los Niños dirigen el hospital cerca de los Mercaderes de Agua. Ve hacia el sur, pasa el Mercado de Mercaderes y lo verás
 justo al noroeste de los Mercaderes de Agua. Espero que todo te vaya bien.}
{143}{}{Es difícil de olvidar. Es de lejos la parte más bulliciosa de la ciudad.
 El Mercado de Mercaderes está a unas millas al sur. Te gustará más
 la sección norte, allí compra y vende
 al público la mayoría de la gente de aquí.}
{144}{}{Bueno, puedes mirar en el Mercado de Mercaderes, a unas millas al sur de aquí.
 Dos de las sedes de las caravanas se encuentran allí, y hay otra más al sur.
 Te recomiendo a los Comerciantes de Ultramar. Pagan bien y no están tan locos.}
{145}{}{Muertos... todos están muertos...}
{146}{}{Pfffftttt... Chrrrr...}
{147}{}{¿Sabes dónde puedo encontrar un Chip de agua? El chip de mi refugio
 está deteriorado y necesitamos otro enseguida.}
{148}{}{¿Un Chip de agua? Nunca he oído hablar de eso. Pero si tiene algo que ver
 con el agua, deberías hablar con los Mercaderes de Agua. Su sede se encuentra lejos hacia el sur, pasando el centro de la cuidad.}