{100}{}{Estás viendo a un hombre alto y armado.}
{101}{}{Estás viendo a Gabriel, el líder de los Pistoleros.}
{102}{}{No recibimos visitas muy a menudo. ¿En qué puedo ayudarte?}
{103}{}{¿Por qué no recibís muchas visitas?}
{104}{}{¿Qué haces por aquí?}
{105}{}{Este lugar no es muy accesible con esa manada de malditas Garras Mortales fuera de nuestra fábrica.}
{106}{}{Disponéis de muchas armas. ¿Por qué no las extermináis a todas?}
{107}{}{Hemos salido y acabado con unas cuantas, pero siempre vuelven. Además, somos maquinistas, no luchadores.}
{108}{}{¿Qué me daríais si saliera ahí y me ocupara de ellas por vosotros?}
{109}{}{Fabricamos armas y municiones. Nos hemos dedicado a esto los últimos 30 años. Pero los últimos 10 han sido un infierno.}
{110}{}{¿Por qué?}
{111}{}{Acabamos con toda la chatarra abandonada tras la guerra que se encontraban alrededor de la fábrica. Ahora dependemos de Adytum para el abastecimiento de materias primas.}
{112}{}{¿Cuál es el problema si Adytum os abastece de materiales?}
{113}{}{Al principio no había ningún problema. Ellos nos suministraban materias primas, nosotros fabricábamos y vendíamos las armas. Pero, hace tres años, Zimmerman contrató a unos mercenarios para que protegiesen Adytum de las Garras Mortales y del habitual ataque de los Piratas. Estos Reguladores son unos cabrones de sangre fría que nos arrebatan todo lo que tenemos. Nosotros hacemos las armas y ellos se enriquecen.}
{114}{}{¿Por qué no os vais y os instaláis en otra parte?}
{115}{}{Es difícil. ¿Qué me daríais por encargarme de las Garras Mortales?}
{116}{}{Lo haríamos si pudiéramos. Pero la mudanza es imposible con todos los tornos y molinos. No son cosas que puedan desmontarse y moverse fácilmente. Podríamos irnos pero las Garras Mortales nos lo impiden.}
{117}{}{Tenéis muchas armas. ¿Por qué no vais y las extermináis?}
{118}{}{Si consigues acabar con las Garras Mortales de una vez, podrás pedir lo que quieras.}
{119}{}{Quiero armas y municiones en gran cantidad.}
{120}{}{}
{121}{}{Si limpias esta zona, nos iremos, pero dejaremos aquí más armas y municiones que jamás podrás utilizar.}
{122}{}{Vale. Trato hecho.}
{123}{}{Tendré que pensármelo.}
{124}{}{Gente que arreglará tus problemas con Adytum.}
{125}{}{Tu acaba con todas las Garras Mortales y trato hecho.}
{126}{}{Vale, lo haré.}
{127}{}{Tendré que pensarlo.}
{128}{}{Hola de nuevo.}
{129}{}{¿Qué haces por aquí?}
{130}{}{Adiós.}
{131}{}{}
{132}{}{Todo va bien.}
{133}{}{Creo que he matado a todas las Garras Mortales.}
{134}{}{Tenemos que estar seguros. Hemos matado a unas 20 en los últimos 2 años y siempre vuelven. Nunca hemos descubierto cómo lo hacían. ¡Dejemos pasar unos días y si no aparecen veremos lo que podemos hacer por ti!}
{135}{}{Vale. Gracias.}
{136}{}{Avísanos en cuanto te hayas encargado de las Garras Mortales.}
{137}{}{Vale. Hasta la vista.}
{138}{}{Lo sé, cuéntame.}
{139}{}{Sí. Puede que nos veamos por aquí.}
{140}{}{No recibimos visitas con frecuencia. ¿En qué puedo ayudarte?}
{141}{}{¿Por qué no recibís muchas visitas?}
{142}{}{¿Qué haces por aquí?}
{143}{}{Este lugar no es muy accesible con esa manada de malditas Garras Mortales fuera de nuestra fábrica.}
{144}{}{He matado a todas las Garras Mortales, incluso todos esos malditos huevos.}
{145}{}{Lo haríamos si pudiéramos. Pero la mudanza es imposible con todos los tornos y molinos. No son cosas que puedan desmontarse y moverse fácilmente. Podríamos irnos pero las Garras Mortales nos lo impiden.}
{146}{}{He matado a todas las Garras Mortales, incluso todos esos malditos huevos.}
{147}{}{}
{148}{}{Quiero armas y municiones, en grandes cantidades.}
{149}{}{}
{150}{}{No has de pagarme. Me basta con que me digas gracias.}
{151}{}{Vale. Coge lo que quieras. Nos marchamos de aquí dentro de un par de días, pero dejaremos más armas y municiones de las que te puedas llevar ahora. Vuelve en cuanto te hagan falta.}
{152}{}{}
{153}{}{}
{154}{}{Gracias.}
{155}{}{}
{156}{}{Vale.}
{157}{}{}
{158}{}{}
{159}{}{¿No os ibais, chicos?}
{160}{}{Estoy aquí para llevarme un par de cosas. ¿Qué tienes hoy?}
{161}{}{Nada. Gracias de todos modos.}
{162}{}{}
{163}{}{Bien. ¿Qué tenéis hoy, chicos?}
{164}{}{Bien, os veré más tarde, chicos.}
{165}{}{}
{166}{}{Sólo vengo a coger un par de cosas. ¿Qué tienes hoy?}
{167}{}{Nada. Gracias de todos modos.}
{168}{}{Lo siento, no puedo hablar contigo. Estoy muy ocupado.}
{169}{}{Armas, ¡Me gustan las armas!}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{170}{}{Tengo algunos amigos que de veras pueden usar algunas de tus armas.}
{171}{}{Tengo algunas amigas que de veras pueden usar algunas de tus armas.}
{172}{}{¿Qué tal, amigo?}
{173}{}{¿Qué tal, amiga?}
{174}{}{¿Qué? ¡Las has matado a todas? ¡Gracias a Dios! Ahora iremos a donde podamos conseguir nuestros propios materiales y no confiaremos en esas víboras de Adytum. Pide lo que quieras, amigo.}
{175}{}{¿Qué? ¡Las has matado a todas? ¡Gracias a Dios! Ahora iremos a donde podamos conseguir nuestros propios materiales y no confiaremos en esas víboras de Adytum. Pide lo que quieras, amiga.}
{176}{}{Ya vale. Ha sido un placer hacer negocios contigo, querido amigo.}
{177}{}{Ya vale. Ha sido un placer hacer negocios contigo, querida amiga.}
{178}{}{Ya está. Dile a tus amigos que ya tienen sus armas.}
{179}{}{Ya está. Dile a tus amigas que ya tienen sus armas.}
{180}{}{Gracias, amigo mío.}
{181}{}{Gracias, amiga mía.}
{182}{}{Lo siento, no puedo hablar contigo, amigo. Estamos liados preparando cosas para la mudanza. Sírvete tú mismo.}
{183}{}{Lo siento, no puedo hablar contigo, amiga. Estamos liados embalando cosas para la mudanza. Coge lo que quieras.}
{184}{}{No hay motivo para irse ahora que tus amigos nos han librado de esos Reguladores.}
{185}{}{No hay motivo para irse ahora que tus amigas nos han librado de esos Reguladores.}
{186}{}{Bienvenido, amigo. ¿Puedo ayudarte en algo?}
{187}{}{Bienvenida, amiga. ¿Puedo ayudarte en algo?}

#
# Following Line is just to be translated normally.
#
{188}{}{Tienes que hablarle a Zack de la compra de material.}