{100}{}{Estás viendo a un hombre mejicano de aspecto descuidado con el pelo liso.}
{101}{}{Estás viendo a Hernández, el pícaro jugador.}
{102}{}{Oye, muchacho, déjame presentarme. Soy Hernández,
 ¡un tio de mucho gusto! Parece que eres nuevo aquí. Por favor,
 permíteme hablarte del Casino.}
{103}{}{¿Qué me puedes contar del Casino?}
{104}{}{No, gracias.}
{105}{}{¿Ehh?}
{106}{}{¡Por supuesto! Este establecimiento elegante está dirigido por
 el famoso Gizmo. Un verdadero visionario y un hombre muy
 rico.}
{107}{}{Gracias.}
{108}{}{Dices que Gizmo es un visionario. ¿Cuál es su visión?}
{109}{}{¿Cuáles son las posibilidades en el juego de aquí?}
{110}{}{Amigo, no me gusta imponerme, pero quizás puedas ayudarme.
 He inventado un sistema infalible porque he descubierto
 cómo lleva las mesas Gizmo, pero no tengo chapas para
 jugar.}
{111}{}{[Te da la impresión de que quiere engañarte.]}
{112}{}{Quizás quieras invertir unas cuantas chapas. Puedo asegurarte que ganarás.}
{113}{}{Claro, suena bien.}
{114}{}{No, gracias.}
{115}{}{Creo que mientes. Quieres engañarme.}
{116}{}{Lo siento, manito. Eh, déjame enseñarte un juego...}
{117}{}{Muchas gracias, ¡manito! Dentro de unos días podré devolverte tus chapas con intereses. Mi sistema es lento, ya ves;
 exige mucha paciencia, ¡pero seguro que trae muchas chapas!}
{118}{}{Muy bien, ¡pero te garantizo el éxito! Si quieres formar parte de los ricos, vuelve pronto; o ¡me buscaré a otro compañero!}
{119}{}{Amigo, veo que también eres un hombre de gustos selectos.
 ¿Qué tal una simple partida de dados?}
{120}{}{¡Vale!}
{121}{}{No, gracias, preferiría probar otra cosa.}
{122}{}{Gizmo soñaba en crear un lugar donde la gente
 pudiera encontrarse y divertirse. Tenía la ambición de
 llevarlo a la práctica. El resultado es el casino que ves aquí.}
{123}{}{Le da a la gente la oportunidad de olvidar sus preocupaciones
 de este mundo exterior asqueroso. ¡Y encima trae chapas a Ciudad Vertedero!}
{124}{}{Parece una buena idea.}
{125}{}{La vida ya es muy dura de por sí. No comparto la causa de alguien
 que anima a la gente a perder sus chapas.}
{126}{}{Obviamente no eres tan listo como Gizmo. En este lugar se puede uno escapar de la dura vida diaria.}
{127}{}{Bueno, Gizmo posee un sitio muy bueno, aunque al parecer, la suerte esté,
 digamos, demasiado en favor de la casa. Lo que no significa por lo tanto que hagan trampas. Pero a no ser que tengas
 un sistema, como yo, tendrás que ser muy listo.}
{128}{}{Gracias.}
{129}{}{}
{130}{}{¿Cómo va tu sistema?}
{131}{}{Nada, gracias.}
{132}{}{Mi sistema se desarrolla lentamente. Tengo un montón de gastos, ya sabes, ¡pero funciona!}
{133}{}{¿Fantástico?}
{134}{}{Creo que eres un mentiroso y un tramposo. ¿Dónde están mis chapas?}
{135}{}{Así que piensas que me has ganado, ¿eh? Entonces, ¡no
 obtendrás nada de mí!}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{136}{}{¡Buenos dias, manito! ¿Qué puedo hacer por ti hoy?}
{137}{}{¡Buenos dias, manita! ¿Qué puedo hacer por ti hoy?}