{100}{}{Estás viendo a un jugador.}
{101}{}{¡Ah! ¡Es un atraco!}
{102}{}{No quiero líos contigo.}
{103}{}{¡Va armado!}
{104}{}{¡Va armada!}
{105}{}{Oh, ¡eres tú!}
{106}{}{Cuentan muchas cosas feas de ti.}
{107}{}{Has tenido un mal comienzo, ¿eh?}
{108}{}{Eres horrible. Has matado a esa gente; no puedo creerlo.}
{109}{}{He oído que había unos cazadores que te perseguían. ¿También los mataste?}
{110}{}{No me hables.}
{111}{}{Sí, liquidaste al Alcalde, ¿verdad?}
{112}{}{Oh, cuando Killian estaba vivo no me gustaba este sitio. Ahora da gusto venir.}
{113}{}{Vete.}
{114}{}{¿Qué tal estás hoy? Yo estoy fenomenal.}
{115}{}{¿Qué tal estás esta noche? Yo estoy fenomenal.}
{116}{}{Déjame solo. Estoy de racha.}
{117}{}{Muñeca, domino estas tragaperras.}
{118}{}{¿Por qué no me das algo de beber?}
{119}{}{¡Grrr! ¡Este lugar es asqueroso!}
{120}{}{Ahora estoy teniendo una buena racha.}