{100}{}{Estás viendo a un Caballero.}
{101}{}{Me pregunto cómo eran las viejas turbinas.}
{102}{}{Sería fantástico si tuviéramos un coche que funcionase.}
{103}{}{¿Sabías que el hombre ha estado en la luna? O algo así me contaron.}
{104}{}{No puedo encontrar el archivo que necesito.}
{105}{}{Algún día seré Paladín.}
{106}{}{Talus es un guerrero cualificado. No me gustaría tener que enfrentarme a él.}
{107}{}{Thomas es el mejor luchador de la Hermandad. Apuesto a que puede vencer a Rhombus.}
{108}{}{Me gustaría echarles el guante a esos Piratas. Enseñarles lo que hacemos con los ladrones.}
{109}{}{Eso es... ¿qué? Oh, lo siento. Ahora mismo no puedo hablar.}
{110}{}{Me pregunto... ¿uh? Oh, has hecho que me distraiga.}
{111}{}{Me encanta trabajar en los nuevos prototipos.}
{112}{}{Cuando nuestros suministros están limitados, es un verdadero desafío encontrar la manera de aprovechar lo que tenemos.}
{113}{}{No tengo ni idea de por qué no funcionó mi último prototipo.}
{114}{}{Lo siento. Ahora mismo no puedo hablar.}
{115}{}{Vree está por allí.}
{116}{}{Bueno, dónde puse ese archivo...}
{117}{}{¿Dónde está ese esquema?}
{118}{}{Bueno, el ordenador dice que debería funcionar; entonces, ¿qué hice mal?}

