{101}{}{No necesito tus servicios ahora. Quizás más tarde.}
{102}{}{¡Socorro! ¡Sálvame!}
{103}{}{¡Debes morir por lo que has hecho!}
{104}{}{¡Sálvame! ¡Por favor!}
{105}{}{¿Están todos muertos ya? ¡Quizás quede alguno más!}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{106}{}{Tu llegada fue muy oportuna, amigo mío. Déjame que te ofrezca una pequeña muestra de mi gratitud.}
{107}{}{Tu llegada fue muy oportuna, amiga mía. Déjame que te ofrezca una pequeña muestra de mi gratitud.}

