{100}{}{¡Muere, perro!}
{101}{}{¡Mi derrota será vengada!}
{102}{}{¡Hola, Iniciado! Espero que les vaya bien a tus tropas.}
{103}{}{¡Espera! Si todavía no has hablado con nuestro Capitán, hazlo y luego, ¡vete!}
{104}{}{¡Espera! Te reconozco y no confío en ti. Te daré un buen consejo:
 si nos traes problemas, te mataremos. ¡Ahora, muévete!}

