{100}{}{Estás viendo a un Paladín.}
{101}{}{Lo siento, no puedo hablar, Iniciado.}
{102}{}{Buenos días.}
{103}{}{¿Sabes que puedes sobrevivir semanas sin agua si llevas una armadura de energía?}
{104}{}{¿No te encanta una buena pelea?}
{105}{}{Me encantan los nuevos rifles láser, pero las pistolas láser antiguas son mis favoritas.}
{106}{}{Las tropas que patrullan por las noches son muy peligrosas. Yo en tu lugar no me alejaría demasiado.}
{107}{}{Ten cuidado, porque hay un mundo muy peligroso ahí fuera.}
{108}{}{¡Creo que mi armadura tiene una mancha!}
{109}{}{La Hermandad es fantástica. No sé lo que hay ahí fuera, pero seguro que no es mejor que esto.}
{110}{}{Buenos días, Iniciado.}
{111}{}{Si necesitas algo, deberías hablar con Vree.}
{112}{}{Vree está justo allí, si necesitas hablar con alguien.}
{113}{}{Tengo que sacar tiempo para estudiar. Entre patrullar y entrenar, me estoy quedando algo "oxidado".}
{114}{}{Tengo que mantener mi cuerpo y mi mente en las mejores condiciones,
 Iniciado.}
{115}{}{Hijo mío, ser un Paladín no es sólo luchar.}
{116}{}{Hija mía, ser un Paladín no es sólo luchar.}

