{100}{}{Comando, aquí la Casa de Guardia. Todo claro. Corto.}
{101}{}{¡Muérete!}
{102}{}{¡Intrusos!}
{103}{}{¡Hu-ma-no!}
{104}{}{Alto. Ésta es una zona prohibida. No deberías estar aquí.}
{105}{}{Será mejor que te rindas.}
{106}{}{Para. Voy a ver al Teniente. Ven en son de paz o muere.}
{107}{}{¡Luggi!}
{108}{}{¡Muere, escoria!}
{109}{}{Vengo a hablar con tu maestro.}
{110}{}{Soy un mutante especial en una misión encomendada por tu Maestro.
 Déjame pasar o afronta las consecuencias.}
{111}{}{Estoy con los de la Catedral. Dalo por seguro.}
{112}{}{¡Muere!}
{113}{}{Hazlo a tu modo.}
{114}{}{Bueno. En realidad, la muerte es así.}
{115}{}{Bueno. Ven conmigo, miserable mosquito.}
{116}{}{Vale. Vámonos.}
{117}{}{¿Graciosillo? ¡No te va a parecer tan gracioso cuando te empapele!}
{118}{}{No te creo.}
{119}{}{Yo no lo creo.}
{120}{}{No. Tú, humano. Muere.}
{121}{}{Si mientes, te mato.}
{122}{}{Oh, vale. Lárgate de aquí.}
{123}{}{Uh, bueno. Imagino que sí. Quizás sea mejor que veas al Teniente.}
{124}{}{Mataste a mi hermano. ¡Me vengaré!}
{125}{}{¡Muerte a ellos!}
{126}{}{¡Asesino!}
{127}{}{¡Asesina!}

