{100}{}{Estás viendo a un habitante del Refugio.}
{101}{}{¡No puedo creer que nos hayas traicionado!}
{102}{}{¡Traidor!}
{103}{}{Te odio. ¡¿Por qué tuviste que volver?!}
{104}{}{¡Espero que tu propia maldad acabe contigo!}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Gracias por salvarnos.}
{110}{}{No estaba seguro de que pudieras hacerlo,
 pero ahora confío en ti.}
{111}{}{¡Gracias! ¡Gracias!}
{112}{}{Eres un héroe. Mi hijo pequeño quiere ser como tú cuando sea mayor.
 No sé si la idea me gusta demasiado.}
{113}{}{Eres una heroína. Mi hija pequeña quiere ser como tú cuando sea mayor.
 No sé si la idea me gusta demasiado.}
{114}{}{¡Eres un tío fantástico!}
{115}{}{¡Eres una tía fantástica!}
{116}{}{¿Seguro que necesitas eso aquí?}
{117}{}{¡Eso es un arma!}
{118}{}{¿La has usado contra alguien?}
{119}{}{¿Por qué crees que es necesario
 llevar un arma aquí?}
{120}{}{Qué bueno verte de nuevo.}
{121}{}{Estoy contento de estés bien.}
{122}{}{Me resultas simpático. Todos esos rumores debían ser
 falsos.}
{123}{}{Hola }
{124}{}{. Sigue
 trabajando así de bien.}
{125}{}{Espero que todo vaya bien ahí fuera.
 Seguro que podemos contar con el agua.}
{126}{}{Estamos empezando a quedarnos sin agua. ¡Es
 terrible!}
{127}{}{Por favor, date prisa y encuentra ese chip. Te
 necesitamos.}
{128}{}{Estoy contento de que lo estés haciendo bien. Sigue trabajando
 así de bien.}
{129}{}{Odio decir eso pero si no encontramos
 el Chip de agua pronto, todos
 moriremos.}
{130}{}{Mi hijita siempre llora por la noche porque quiere agua,
 y yo tengo nada
 que darle.}
{131}{}{No lo vamos a hacer, ¿verdad?}
{132}{}{Las raciones de agua se están acabando.}
{133}{}{La sección hidropónica está ahora mismo cerrada. Eso significa que
 que nuestro suministro de alimentos se está acabando.}
{134}{}{Mmm. Todavía me pareces humano. Las cosas no pueden ir tan mal
 ahí fuera.}
{135}{}{Hola }
{136}{}{.}
{137}{}{Espero que te salga bien tu búsqueda.}
{138}{}{Nos vemos por ahí.}
{139}{}{¿Has hablado últimamente con el Supervisor?}
{140}{}{El Supervisor está muy preocupado por el
 estado de la misión.}
{141}{}{Tenemos que darnos prisa. No podemos permitirnos
 ningún error.}
{142}{}{Espero que estés haciéndolo lo mejor que sabes.}
{143}{}{No es momento para descansos; sal de aquí.}
{144}{}{Esto no es lo que deberías estar haciendo,
 ¿verdad?}
{145}{}{Vamos a morir y la culpa es tuya.}
{146}{}{No te quedes ahí parado, ¡sal de aquí! ¡Ahora!}
{147}{}{Si morimos, será tu culpa.}
{148}{}{El exterior te ha corrompido, ¿no es verdad?}
{149}{}{Déjame en paz.}
{150}{}{Creo que deberías dejarnos solos a mi familia y a mí, }
{151}{}{. Sería
 lo mejor.}
{152}{}{Debería darte vergüenza.}
{153}{}{Y pensar que me gustabas.}
{154}{}{El habitante del Refugio se niega a hablar contigo.}
{155}{}{Te lanza una mirada vacía cuando intentas hablar.}
{156}{}{Me arrepiento de haberte traído aquí fuera.}
{157}{}{El agua es mala, pero tu compañía es aún peor.}
{158}{}{Vete. Lárgate. Puedes redimir tu culpa
 encontrando el Chip de agua.}
{159}{}{Espero que estés satisfecho.}
{160}{}{El morador del Refugio se niega a hablar contigo.}
{161}{}{¡Es tu culpa! ¡Seguramente fuiste tú quien rompió
 el Chip de agua¡}
{162}{}{Te odio. Te odio muchísimo.}
{163}{}{El morador del Refugio solloza dejando caer grandes lágrimas.}
{164}{}{Te lanza una mirada fría cuando intentas hablar.}
{165}{}{Gracias.}
{166}{}{Es tarde. Vuelve en otro momento.}
{167}{}{El habitante del Refugio está descansando.}