{100}{}{Estás viendo a un guardia Necrófago.}
{101}{}{¡Vete! No te queremos aquí.}
{102}{}{Vale. También ha sido un placer conocerte.}
{103}{}{¿Eh?}
{104}{}{Estoy trabajando. Si quieres ver a Set, tendrás que hacerlo ahí dentro.}
{105}{}{La puerta está cerrada. Tendrás que volver de noche.}
{106}{}{Gracias.}
{107}{}{¿Eh?}
{108}{}{Te he dicho que te fueras. Los de tu raza no son bienvenidos aquí.}
{109}{}{De acuerdo.}
{110}{}{¡Miau!}
{111}{}{Las puertas no se abren hasta que oscurece.}
{112}{}{Necesito entrar ahí. ¿Me puedes ayudar de alguna manera?}
{113}{}{Mmm, vale.}
{114}{}{¡Ugh!}
{115}{}{Bueno, no creo que duela.}
{116}{}{Ojalá pudiese ayudarte pero Set me liquidará si lo hago.
 Ya sabes cómo son las cosas... siempre hay que hacer lo que dice
 el grandullón.}
{117}{}{Sí, comprendo. Gracias.}

