{100}{}{Estás viendo un cuerpo inerte tirado en el suelo.}
{101}{}{Un alma desgraciada yace ahí.}
{102}{}{Los restos de un humano mutante están en el suelo.}
{103}{}{Los alimentos son básicamente carroña.}
{104}{}{Parece que desafió a Thanatos y perdió.}

