{100}{}{Estás viendo a un Necrófago refugiado.}
{101}{}{Por favor, no me mates.}
{102}{}{Cállate y puede que te deje vivir.}
{103}{}{No te preocupes, no mereces la pena.}
{104}{}{¿Qué ha pasado aquí?}
{105}{}{Gah.}
{106}{}{Tú... ¡me vas a matar de todas maneras!}
{107}{}{Ah, oh. Vale.}
{108}{}{Bien, quédate así.}
{109}{}{Ahora dime que ha pasado aquí.}
{110}{}{¡Vas a matarme!}
{111}{}{Ah, ¿no me habías dicho que me callara?}
{112}{}{Muere ahora.}
{113}{}{Sí, y ahora quiero saber qué ha pasado aquí.}
{114}{}{Los Supermutantes atacaron. Estábamos perdidos. Tenían pistolas y bombas, incluso algunas vagonetas a vapor. Mataron a mis amigos. Los
 mutantes nos machacaron como tú probablemente harás conmigo.}
{115}{}{Los Supermutantes atacaron. Estábamos perdidos. Tenían pistolas y bombas, incluso algunas vagonetas a vapor. Mataron a mis amigos. Los mutantes nos machacaron.}
{116}{}{¿Qué es una vagoneta a vapor?}
{117}{}{¿Cómo sobreviviste?}
{118}{}{¿Sabes por qué?}
{119}{}{No lo sé.}
{120}{}{Gracias.}
{121}{}{Eres un inútil.}
{122}{}{Me he enterado de que fueron liquidados; un humano mató a sus hombres aquí.}
{123}{}{Oh, uh, ¿algo más?}
{124}{}{Mmm. Vale. Sal de aquí.}
{125}{}{No.}
{126}{}{Gracias.}
{127}{}{Eres un inútil.}
{128}{}{Me he enterado de que algunos de esos necrófagos asquerosos puede haber sobrevivido, y la idea no me gusta nada.}
{129}{}{Vale, gracias.}
{130}{}{¿Es eso?}
{131}{}{Sí, eso es.}
{132}{}{Vale, gracias.}
{133}{}{Me escondí hasta que casi todos los mutantes se marcharon.}
{134}{}{¿Algo más?}
{135}{}{Una cosa grande que se movía con ruedas, pero no estaba tirada por un Brahmin.}
{136}{}{Mmm, vale. ¿Algo más?}
{137}{}{Es una tontería.}
{138}{}{Eh, entonces ¿por qué preguntaste sobre eso?}
{139}{}{¡Eso es! ¡Bastante insolente!}
{140}{}{Sólo quería saber. Eso es todo.}
{141}{}{¿Tú otra vez? ¿Qué quieres ahora?}
{142}{}{¿Más noticias?}
{143}{}{Sólo charlaba.}
{144}{}{No. Bueno, me he enterado de que llegan más Supermutantes.
 No sé cuando.}
{145}{}{Mmm. Vale.}
{146}{}{Entonces hazlo en otro sitio. Aquí no te dejaré.}

