{100}{}{¡Eh!}
{101}{}{¡Nada de armas aquí!}
{102}{}{¡Vigila eso!}
{103}{}{¡Cogedlos!}
{104}{}{¡Deja de curiosear!}
{105}{}{¡Deja de curiosear por aquí!}
{106}{}{¡Eh, tú! Deja de esconderte y sal de una vez!}
{107}{}{¿Qué?}
{108}{}{Eh, ¿puedo hacerte algunas preguntas?}
{109}{}{¿Tienes algunas chapas sueltas?}
{110}{}{No importa, disculpa.}
{111}{}{¿Uuuh?}
{112}{}{Estoy trabajando. Date prisa.}
{113}{}{No. Vete.}
{114}{}{¿Me puedes hablar de tu jefe?}
{115}{}{¿Qué más hay por esta ciudad?}
{116}{}{Y tú que eres, ¿idiota? Anda vete.}
{117}{}{No. Vete a suplicar a otro sitio.}
{118}{}{Lárgate.}
{119}{}{Aquí no necesitamos pobres.}
{120}{}{Gizmo es un hombre justo. El sueldo es bueno y el trabajo fácil. No causes problemas y
 todos tan contentos.}
{121}{}{Ve a buscar algo de beber al Fosa Común. Buen sitio. Abre a
 las cuatro.
 Ahora, déjame solo.}
{122}{}{¿Por qué no te vas de compras al almacén de Killian? Está al
 sudeste de aquí.
 Ahora, lárgate.}
{123}{}{Habla con los comerciantes.}
{124}{}{Eh, si quieres divertirte un poco, pásate por la Posada y pregunta por
 Sinthia. Merece la pena.}
{125}{}{Nada de trampas.}
{126}{}{Liquidaremos a los deudores.}
{127}{}{Colega, me duele el cuello.}
{128}{}{Este trabajo es una mierda.}
{129}{}{Me encanta este sitio.}
{130}{}{Creo que esta noche visitaré a Sinthia.}
{131}{}{Sal de aquí, imbécil.}
{132}{}{¡Aquí no se permiten armas!}
{133}{}{¡Eh! ¡Tú! ¡Aparta eso!}

