{100}{}{Estás viendo a Gizmo, el dueño del Casino.}
{101}{gizmo_1}{Trae tu culo aquí y siéntate.
 Tenemos negocios que discutir.}
{102}{}{Me parece que aquí ya hay demasiados culos...}
{103}{}{Me lo estaba temiendo. ¿Qué es lo que quieres?}
{104}{}{¿Qué negocio?}
{105}{}{Bah.}
{106}{gizmo_1b}{¡Largo de aquí, idiota!}
{107}{gizmo_2}{¿Besas a tu madre con esa boca? Un poco de respeto.}
{108}{}{¿Haces algo aparte de zampar?}
{109}{}{Tienes razón, lo siento. Pues hablemos de negocios.}
{110}{gizmo_4}{Está bien, [Gizmo resopla] este es el trato. Ciudad Vertedero,
 ya no es lo que era. No seguiría en pie de no
 ser por mi casa de juegos. Aun así,
 Killian me está tocando las narices y estoy empezando a
 hartarme. [Gizmo resopla] Y ahí es donde entras tú, bolinche.}
{111}{}{¿Qué quieres que haga?}
{112}{}{Si crees que te voy a ayudar, además de gordo eres estúpido.}
{113}{gizmo_4a}{Qué gracia.}
{114}{gizmo_5}{Lo que yo creo es que tú me lo vas a quitar de encima, ¿sabes?
 Sin testigos, entrar, hacer, salir.}
{115}{}{¿Por qué no mandas a uno de tus propios matones?}
{116}{}{No trabajaría para ti aunque me ofrecieses
 todas las chapas de este asqueroso lugar.}
{117}{}{Claro. Puedo necesitar las chapas.}
{118}{}{No lo creo. Gracias de todas formas.}
{119}{}{¿Cuánto deseas pagar?}
{120}{gizmo_6}{Lo haría, pero no debe haber nada que me relacione con la
 desafortunada muerte de Killian.}
{121}{}{Tiene sentido. Claro que lo haré.}
{122}{}{Está bien, lo haré.}
{123}{}{Vaya cobarde. ¿Tienes miedo no gustar a la gente? Demasiado tarde.}
{124}{}{¿Cuánto piensas pagar?}
{125}{}{De ninguna manera.}
{126}{}{No estoy de acuerdo. Gracias de todas formas.}
{127}{gizmo_7}{[Gizmo respira profundamente.] Sabía que comprenderías mi punto de vista. Como prueba quiero las placas de identificación que Killian lleva en el cuello.
 Si las coges, recibirás tus chapas. Anda, vete y no me cabrees. Todavía conservo las rótulas del último que lo
 intentó.}
{128}{gizmo_8}{Mil chapas. Ni más, ni menos.}
{129}{}{Me parece bien. Lo haré.}
{130}{}{¿A eso lo llamas recompensa? Si tengo que eliminar al tío, necesitaré
 más que eso.}
{131}{}{Ni siquiera te has acercado. No me interesa este trato.}
{132}{}{No me fío de ti. Olvídalo, flaco.}
{133}{gizmo_9}{[Gizmo se ríe y tose] Quizás tengas razón.
 Creo que vales más. 1.500.}
{134}{}{Ahora nos entendemos.}
{135}{}{¿Eso cuánto es, una chapa la libra para ti? Olvídalo.}
{136}{}{Gracias, pero no.}
{137}{}{Ni de coña.}
{138}{gizmo_10}{Siento que pienses así. Aunque no tanto como lo vas a sentir tú.
 Que no salga ni una palabra de aquí. Izo, muéstrale
 a nuestro nuevo amigo lo que hacemos con la gente que me dice que no.}
{139}{gizmo_11}{Una vez, vale. Dos son demasiado. Y han sido dos.
 Izo, consígueme un par de rótulas.}
{140}{gizmo_13}{¿Has terminado ya el trabajo?}
{141}{}{Sí, claro que sí.}
{142}{}{No, aún no.}
{143}{gizmo_14}{Veamos las placas.}
{144}{gizmo_15}{Oh, sí. ¡Oh, sí! Izo tiene tus chapas. ¡Oh, esto está bien!
 Je, je, je... deberías dejar la ciudad por un tiempo.
 Ya sabes, por si las moscas.}
{145}{}{Vale, me largo.}
{146}{}{No me des órdenes, gordito. ¿Te enteras?}
{147}{}{¿Y si no lo hago?}
{148}{}{Claro, me iré. Pero recuerda que me debes una.}
{149}{gizmo_16}{Si no te largas de la ciudad acabarás bajo ella. ¿Te enteras?}
{150}{}{Vale, vale, me largo.}
{151}{}{¿Quién va a hacerlo? ¿Tú? Si ni siquiera puedes levantar tu fofo
 trasero para ir a por un bocadillo, como para matarme.}
{152}{}{Está bien, vale. Pero recuerda que me la debes.}
{153}{gizmo_17}{¿Entonces me darás las placas de identificación?}
{154}{}{Emm... bueno... yo... eh, las he perdido.}
{155}{}{¿Qué pasa si no te las quiero dar?}
{156}{}{Mentí. No las tengo.}
{157}{}{Las tenía, pero luego las perdí.}
{158}{gizmo_18}{[Gizmo se ríe.] Menudo mentiroso estás hecho. Ahora ve a por las placas. No quiero volver
 a verte hasta que hayas acabado con Killian.}
{159}{gizmo_19}{No hay problema, las arrancaré de tu cadáver.}
{160}{}{Eh... bueno, supongo que mentí. No las tengo.}
{161}{}{¿Sí? ¿Vas a contratar a alguien para que te haga el trabajo sucio?}
{162}{}{Las he perdido.}
{163}{}{Bueno, las tenía pero me las robaron.}
{164}{gizmo_20}{No hay placas, no hay chapas. Si vuelves de nuevo sin las placas
 Izo se pondrá creativo con tu anatomía. ¡Ahora lárgate!}
{165}{gizmo_21}{¿Qué quieres? Soy un hombre ocupado.}
{166}{}{Estoy aquí para decirte que tu asesino falló.}
{167}{}{En realidad nada. Es hora de irme.}
{168}{}{Me gustaría saber cómo puede seguir vivo alguien tan estúpido como tú.}
{169}{}{Estoy aquí para hablar del intento de asesinar a Killian.}
{170}{gizmo_22}{No sé de que estás hablando.}
{171}{}{Claro que lo sabes. Contrataste a alguien para matar a Killian,
 y la jodió.}
{172}{}{¿No recuerdas haber contratado a nadie para matar a Killian, caracol cornudo baboso arrastrao?}
{173}{}{Bueno, pongamos como hipótesis...}
{174}{}{¡Eres un mentiroso!}
{175}{}{Tienes razón. Adiós.}
{176}{gizmo_23}{No sé quién eres, pero no me llevo bien con los desconocidos
 que entran en mi oficina acusándome de cosas de las que no tienen ni idea.}
{177}{}{Ah, pero ahí te equivocas, Gizmo.
 No te estoy acusando. He venido para ayudarte.}
{178}{}{Lo sé todo. ¡Así que confiesalo!}
{179}{}{Tienes razón. Me largo.}
{180}{gizmo_24}{¿De verdad? [Gizmo sonríe.] ¿Él va a ayudarme?
 ¿De que tipo de ayuda estamos hablando?}
{181}{}{Fácil. Mandaste a alguien para matar a Killian y falló. Necesitas alguien que haga el trabajo... mejor.}
{182}{}{Nada. Olvida lo que he dicho.}
{183}{gizmo_25}{Déjame adivinar. ¿Tú eres ese alguien?}
{184}{}{Muy bien... Por un buen precio, claro.}
{185}{}{Puedo matarle más rápido de lo que tú escupes.}
{186}{gizmo_26}{Bueno, ¿por qué habría de confiar en ti?}
{187}{}{Estoy aquí. Y tú necesitas a alguien de fuera para que haga el
 trabajo sucio, ¿verdad?}
{188}{}{No puedes... O sea puedes... Quiero decir...}
{189}{}{Porque he estado por ahí. Ya he matado.}
{190}{gizmo_27}{Emm... está bien. Podemos hacerlo. Pero ahora que trabajas para mí, debes saber que
 nadie traiciona a Gizmo y vive para contarlo. ¿Me has entendido?}
{191}{}{Oh, engañarte es fácil... lo difícil
 es abarcarte.}
{192}{}{Claro, pero primero necesito saber por qué quieres que se muera.}
{193}{gizmo_28}{Eh. Eso es fácil. Quiero verle muerto porque me fastidia el negocio. Entonces, ¿te encargarás
 de él por mí?}
{194}{}{Para eso estoy aquí. Estará muerto antes de que caiga el sol.}
{195}{}{Claro. Es un trabajo.}
{196}{}{Puedes repetir eso, por favor... ¿esta vez en mi bolsillo?}
{197}{}{Bueno, esto... No, no puedo.}
{198}{gizmo_29}{Bien. Regresa con las placas de identificación que lleva en el cuello como prueba.
 Y nunca hemos mantenido esta conversación, no
 se la menciones a nadie. A mí nadie me traiciona. Nadie.}
{199}{gizmo_30}{O eres realmente idiota... o eres un espía realmente idiota. De todas formas no importa,
 porque Izo se va a encargar de que estés realmente muerto.}
{200}{gizmo_32}{No me gusta la gente que me hace perder el tiempo. ¡No vuelvas pronto!}
{201}{gizmo_33}{¿Cómo qué?}
{202}{}{Bueno, digamos que sí que intentaste matar a Killian, y tu
 asesino falló. Eso significa que necesitas a otro para que termine el trabajo.}
{203}{}{¿Eh? Oh, no importa.}
{204}{gizmo_34}{Sabes, [Gizmo suspira] no me gusta la gente que me insulta en mi propia casa. Izo, muéstrale a nuestro invitado... la ventana.}
{205}{gizmo_35}{Has vuelto. Sabes, tuve que contratar a otro para que hiciese tu trabajo.
 No me hizo nada de gracia. De hecho, Izo te mostrará la poco gracia que me hizo. Espero
 que hayas tenido un buen día, porque es el último.}
{206}{gizmo36a}{[Gizmo gruñe.] Killian es el alcalde de esta ciudad.
 Cree que lo sabe todo... bueno, vamos a ver cuánto sabe, ¿qué te parece?}
{207}{gizmo_37}{[Gizmo tose.] Ese soy yo, idiota. Yo llevo esta... casa de juegos.}
{208}{gizmo_38}{Esa es la tienducha de Killian en el extremo norte de la ciudad. Vende porquerías.}
{209}{gizmo_39}{Bueno, la mayoría de la gente juega aquí. Haces preguntas estúpidas.}
{210}{gizmo_42}{¿No te gustaría saberlo?}
{211}{gizmo_43}{No te preocupes por eso.}
{212}{gizmo_44}{[Gizmo sorbe.] Yo eh... No me apetece hablar de ello ahora.}
{213}{gizmo_45m}{Eh, ¿qué diablos crees que estás haciendo? ¡Izo, arráncale los brazos!}
{214}{gizmo_45f}{Eh, ¿qué diablos crees que estás haciendo? ¡Izo, arráncale los brazos!}
{215}{gizmo_47}{¿Qué, estás sordo?, he dicho...}
{216}{gizmo_48}{¡Oye, no pienso repetirlo!}
{217}{}{Ganas 600 puntos de experiencia por haber participado en la derrota de Gizmo.
 Que en piezas descanse el bastardo.}
{218}{}{Es posiblemente el tío más corpulento que jamás has visto.}
{219}{}{¿Sabes? Encontré algo muy interesante cuando te marchaste la última vez.
 Si hay algo que me dé más asco que una hamburguesa recalentada es un
 chivato. ¡Chicos!}
{220}{}{Hasta aquí hemos llegado, Killian. Bueno, nunca soporté tu olor y
 ahora, ¡lo voy a arreglar!}
{221}{}{Me he ocupado de Killian. Dicen que sabrás apreciarlo.}
{222}{}{¿Oh, en serio?}
{223}{}{Oye, está bien, si no lo quieres muerto, estupendo. Sólo intentaba ayudar.}
{224}{}{Estaba pensando en un cuchillo en la espalda o una bala entre los ojos.}
{225}{}{Lo pillo. ¿Por qué le quieres muerto?}
{226}{gizmo_24}{¿De verdad? [Gizmo sonríe.] ¿Ella va a ayudarme?
 ¿De que tipo de ayuda estamos hablando?}

# Gizmo's Tell-Me-Abouts generic responses
{980}{gizmo_42}{¿No te gustaría saberlo?}
{981}{gizmo_43}{No te preocupes por eso.}

#
# Gizmo's Tell-Me-Abouts
#

{1000}{}{Killian}
{1001}{}{Gizmo}
{1002}{}{Darkwaters}
{1003}{}{Gizmo}
{1004}{}{Darkwater}
{1005}{}{Gizmo}
{1006}{}{Casino}
{1007}{}{Ciudad Vertedero}

{1100}{gizmo36a}{[Gizmo gruñe.] Killian es el alcalde de esta ciudad
 Cree que lo sabe todo... bueno, ¿vamos a ver cuánto sabe?}
{1101}{gizmo_37}{[Gizmo tose.] Ese soy yo, idiota. Yo llevo esta... casa de juegos.}
{1102}{gizmo_38}{Esa es la tienducha de Killian, en el extremo norte de la ciudad. Vende porquerías.}
{1103}{gizmo_39}{Bueno, la mayoría juega aquí. Haces preguntas estúpidas.}
{1104}{gizmo36a}{[Gizmo gruñe.] Killian es el alcalde de esta ciudad
 Cree que lo sabe todo... bueno, ¿vamos a ver cuánto sabe?}
{1105}{gizmo_39}{Bueno, la mayoría juega aquí. Haces preguntas estúpidas.}
{1106}{gizmo_39}{Bueno, la mayoría juega aquí. Haces preguntas estúpidas.}
{1107}{gizmo_39}{Bueno, la mayoría juega aquí. Haces preguntas estúpidas.}
