{100}{}{Estás viendo una puerta que parece muy segura.}
{101}{}{Tu destreza no tiene efecto sobre la puerta.}
{102}{}{Recibes un descarga del sistema de seguridad y también }
{103}{}{ puntos de daño.}
{104}{}{Abres la puerta con la Llave Maestra Roja.}
{105}{}{Ese objeto no tiene efecto sobre la puerta. Quizá con otro tengas más suerte.}
{106}{}{Recibes una descarga del sistema de seguridad y también }
{107}{}{ puntos de daño.}
{108}{}{Parece que un campo de energía protege la puerta. Quizás puedas desactivarlo de alguna manera.}
{109}{}{Parece que la puerta tiene un segundo cerrojo.}
{110}{}{Te das cuenta de que hay unas marcas rojas en la puerta.}
{111}{}{Te das cuenta de que hay unas marcas rojas en la puerta.}
{112}{}{Te preguntas como se puede abrir la puerta.}
{113}{}{Has evitado el sistema de seguridad.}
{114}{}{Activas el sistema de seguridad y recibes una descarga eléctrica sufriendo }
{115}{}{ puntos de daño.}
{116}{}{No detectas ninguna trampa en la puerta.}
{117}{}{Evitas el sistema de seguridad.}
{118}{}{Activas el sistema de seguridad y recibes una descarga eléctrica sufriendo }
{119}{}{ puntos de daño.}
{120}{}{No detectas ninguna trampa en la puerta.}
{121}{}{Activas el sistema de seguridad y recibes una descarga eléctrica sufriendo }
{122}{}{ puntos de daño.}
{123}{}{Parece que un campo de energía protege la puerta. Quizás puedas desactivarlo de alguna manera.}
{124}{}{Abres la puerta.}
{125}{}{No consigues forzar el cerrojo de la puerta.}

