{100}{}{Estás viendo una cabina.}
{101}{}{Parece que esta cabina tiene un cerrojo electrónico.}
{102}{}{Abres la cabina con facilidad.}
{103}{}{Este cerrojo parece más problemático de lo que habías pensado en un principio.}
{104}{}{Abres el cerrojo de la cabina sin ningún problema.}
{105}{}{Este cerrojo parece más problemático de lo que habías pensado en un principio.}
{106}{}{Esa destreza no tiene efecto en la cabina.}

