{100}{}{Estás viendo un generador.}
{101}{}{Los generadores están encendidos.}
{102}{}{Estos generadores parecen estar desconectado. Te preguntas si
 podrás conectarlos.}
{103}{}{Los generadores ya están encendidos.}
{104}{}{Conectas los generadores y todos los sistemas parecen
 volver a estar en línea.}
{105}{}{No puedes conectar los generadores.}
{106}{}{No tienes los conocimientos necesarios para reparar el sistema.}
