{100}{}{Estás viendo una bomba de agua.}
{101}{}{El diseño de esta bomba parece muy diferente al que
 hay en tu Refugio.}
{102}{}{Te das cuenta de que las piezas de la bomba serán incompatibles
 con las de tu Refugio.}
