{100}{}{Esto es una máquina tragaperras con un dibujo de una explosión nuclear.
 Jugar cuesta 20 chapas.}
{101}{}{Metes 20 chapas en la máquina tragaperras y bajas la manivela grasienta.}
{102}{}{¡DING! ¡DING! ¡DING!}
{103}{}{Obtienes tres fresas ¡Excelente! }
{104}{}{ chapas caen en la bandeja y las vuelves a meter.}
{105}{}{¡Ding! ¡Ding! ¡Ding!}
{106}{}{Obtienes tres naranjas. ¡Ganas! Caen 30 chapas en la bandeja y las vuelves a meter.}
{107}{}{¡Oh, mala suerte! Has perdido.}
{108}{}{No tienes suficientes chapas para jugar.}
