{100}{}{Estás viendo a un tonto perdido.}
{101}{}{Estás viendo a Gretch, el ayudante del Doc Mórbid.}
{102}{}{¿Para qué has bajado?}
{103}{}{¿Ergh?}
{104}{}{Tu jefe me ha mandado.}
{105}{}{No me hables así, cretino.}
{106}{}{Para ver qué tal te va todo.}
{107}{}{Nada. Adiós.}
{108}{}{Te conozco, ¿eh?}
{109}{}{No.}
{110}{}{Sí.}
{111}{}{No importa.}
{112}{}{Um... vale.}
{113}{}{¿Qué haces?}
{114}{}{¿Bien? ¿Significa eso que estás casi listo?}
{115}{}{Eres un poco lento, ¿no?}
{116}{}{Si, si, casi listo.}
{117}{}{¿Con qué?}
{118}{}{Ya es hora.}
{119}{}{Vale. Te veré después.}
{120}{}{Trozos de cadáveres casi listos para ir al Eje.}
{121}{}{¿Para qué?}
{122}{}{Por supuesto. Por eso estoy aquí.}
{123}{}{Creo que no me apetece oír hablar de eso.}
{124}{}{Te envía el hombre iguana, Bob... feliz; mucha comida buena...}
{125}{}{¿Vende partes humanas para que se la coma la gente?}
{126}{}{So asqueroso. Te voy a cortar en pedazos y luego te comeré.}
{127}{}{Por supuesto. Volveré en un minuto.}
{128}{}{Para que Bob la venda... para comer... ¿Por qué lo preguntas?}
{129}{}{No hay de qué. Adiós.}
{130}{}{No estaba seguro que esta fuera la procedencia de la carne humana de Bob.}
{131}{}{A veces me cuesta mucho pensar.}
{132}{}{A mí también... ¿de qué hablábamos?}
{133}{}{No me acuerdo. Adiós.}
{134}{}{Me estabas contando lo que haces.}
{135}{}{Hablábamos de lo idiota que eres.}
{136}{}{No lo sé.}
{137}{}{Ya no quiero hablar contigo.}
{138}{}{Sí... Doc Mórbid tiene los mejores cuerpos humanos.}
{139}{}{Ah... Volveré para coger los cuerpos... dentro de un
 rato. Adiós.}
{140}{}{Tengo que volver al trabajo.}
{141}{}{¡No te metas en los asuntos de Doc!}
