{100}{}{No tengo miedo.}
{101}{}{Tengo miedo.}
{102}{}{Estoy de servicio. Vete.}
{103}{}{Pórtate bien o habrás de responder ante mí.}
{104}{}{¿Tienes donuts?}
{105}{}{¿No tuviste la impresión de que te observaban? ¿Como si estuvieras controlado a distancia? Yo sí.}
{106}{}{¿Sabes lo que los Escorpiones Rad le hicieron a Bill? Aún está
 buscando sus piernas.}
{107}{}{Así que crees que puedes derrotar a un Escorpión, ¿eh?}
{108}{}{No me pareces demasiado fuerte.}