{100}{}{Esta taquilla está cerrada.}
{101}{}{Abres la taquilla.}
{102}{}{Quitas el cerrojo de la taquilla.}
{103}{}{No puedes quitar el cerrojo de la taquilla.}
{104}{}{Rompes tu ganzúa al intentar abrir la puerta.}
{105}{}{Este cerrojo parece demasiado complicado para ti.}
