{100}{}{Lo siento, hoy no hay boxeo.}
{101}{}{Unn.}
{102}{}{Vale, vale.}
{103}{}{¿Cuándo es el próximo combate?}
{104}{}{Podrías intentar hablar con Gizmo. He oído que siempre está buscando
 carne fresca para el ring.}
{105}{}{Prueba mañana. Es cuando Saúl boxeará.}
{106}{}{Te lo has perdido. Prueba de nuevo dentro de un par de días. Saúl boxea cada tres
 días.}
{107}{}{Gracias.}
{108}{}{¿Quién es Saúl?}
{109}{}{Saúl es el campeón local. Actualmente es el favorito de Gizmo.}
{110}{}{Oye. Hoy no hay combate.}
{111}{}{Prueba de nuevo mañana.}
{112}{}{Prueba pasado mañana.}
{113}{}{¿Quieres apostar en el combate?}
{114}{}{Tengo cosas mejores que hacer con mis chapas. Adiós.}
{115}{}{¿Cuales son las probabilidades?}
{116}{}{No, gracias. ¿Pero te importa que te haga algunas preguntas?}
{117}{}{}
{118}{}{Lo siento, pero el combate de hoy ha terminado.}
{119}{}{Oh. Bien, entonces no importa.}
{120}{}{¿Quieres apostar por Saúl o por el desafiador? Dicen que va a ganar Saúl.
 La apuesta está en 25 chapas, son 50 si ganas apostando por Saúl, ¡100 si ganas
 apostando por el desafiador!}
{121}{}{Apostaré por Saul.}
{122}{}{Apostaré por el desafiador.}
{123}{}{Supongo que no.}
{124}{}{¿Quién es el boxeador?}
{125}{}{¿Quién lleva esos combates?}
{126}{}{Oh, no importa.}
{127}{}{Lo siento, no tengo tiempo. Puede que más tarde.}
{128}{}{Saúl, el puño más rápido de Ciudad Vertedero. Es puro músculo.
 Un luchador implacable.}
{129}{}{Él también es un buen tipo.}
{130}{}{Um, sí. ¿Quién lleva esos combates?}
{131}{}{Gracias. Nos veremos.}
{132}{}{Gizmo, el dueño del Casino, utiliza a Saúl. De vez en cuando le gusta ver un
 combate o dos, pero casi siempre se trata de chapas. La gente apuesta muchas chapas en los combates.
 Y nadie muere, excepto en esos combates a muerte que teóricamente se mantienen
 en el Eje.}
{133}{}{¿Combates a muerte?}
{134}{}{Gracias.}
{135}{}{Bueno, sólo es un rumor. Pero dicen que hay un ring subterráneo
 donde puedes pagar para ver a la gente luchar a muerte. No es mi tipo de
 lucha.}
{136}{}{Umm. Gracias.}
{137}{}{Oye, ¿Qué haces?}
{138}{}{Oh, nada.}
{139}{}{¿Quieres empezar algo, idiota?}
{140}{}{Por favor, deja eso.}
{141}{}{Oh, no. No importa. Olvida lo que he dicho.}
{142}{}{Bien, bien. ¡parece que has ganado! Aquí tienes tus chapas.}
{143}{}{¡Vuelve cuando tengas suficientes chapas para apostar!}
{144}{}{¿Quieres esperar aquí hasta que empiece el combate a las 2:00?}
{145}{}{Claro, qué diablos importa.}
{146}{}{No, tengo cosas que hacer. Volveré más tarde.}
{147}{}{Vale, pero si pierdes el combate, ¡pierdes la apuesta!}
{148}{}{¡Que empiece el combate!}
{149}{}{Por favor, no me molestes durante el combate.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{150}{}{Bueno, no se puede ganar siempre, amigo. Que tengas suerte la próxima vez.}
{151}{}{Bueno, no se puede ganar siempre, amiga. Que tengas suerte la próxima vez.}

{152}{}{Lo siento, una apuesta por combate.}