{100}{}{Estás viendo a Gwen, una bandida del desierto.}
{101}{}{Soy Gwen. Formo parte de los consejeros de Garl. ¿Quién eres tú?}
{102}{}{Soy }
{103}{}{. ¿Qué haces por aquí?}
{104}{}{No soy nadie especial. ¿Qué me puedes contar sobre tu campo?}
{105}{}{¿Ehh?}
{106}{}{Soy quien te va a volar los sesos, muñeca.}
{107}{}{Como buena consejera, me aseguro que los tipos insignificantes
 no le causan problemas a Garl.}
{108}{}{¿Y cómo lo haces?}
{109}{}{¿Tú y qué ejército?}
{110}{}{Dudo que puedas hacer algo para detener a nadie.}
{111}{}{Vienen a parar aquí todos los tipos de vida corta.}
{112}{}{Umm. Si no eres nadie especial no voy a molestarme en
 hablar contigo. Vete.}
{113}{}{Me encargo de que tipos como tú no molesten a Garl. ¡Vete!}
{114}{}{Tengo medios para hacer desaparecer a los indeseables.}
{115}{}{Veo que me equivoqué. Probablemente puedas hacer un
 buen trabajo. Adiós.}
{116}{}{¡Toma!}
{117}{}{¡Muere!}
{118}{}{Ha pasado mucho tiempo desde mi última buena pelea. Te
 advierto que vas a perder. ¡Comprueba mis habilidades!}
{119}{}{Te arrepentirás de ese comentario. ¡Será el último que hagas!}
{120}{}{Si eso es todo lo que puedes hacer, le haré un favor al
 mundo si te liquido.}
{121}{}{¡Mi ejército y yo!}
{122}{}{Me desesperas. Vete antes de que me enfade de verdad.}