{100}{}{Estás viendo Harold.}
{101}{HROLD0}{
Dame algo, colega, viejo amigo. Ayuda a un pobre mutante que ha caído en desgracia. [Tose]}
{102}{}{Claro, aquí tienes 25 chapas. Que tengas buena suerte.}
{103}{}{¿Qué tal 5 chapas?}
{104}{}{Lo siento, no llevo encima chapas.}
{105}{}{¡Apártate de mí!}
{106}{}{¿Ehhh?}
{107}{HROLD1}{
Vaya. Amigo, estás todavía peor que yo. Tú sí que necesitas suerte.}
{108}{HROLD2}{
Oh, muy amable de tu parte colega. ¿Sabes? Si pudiese limpiar la porquería de ahí afuera, puede que encontrases una lágrima en el ojo del viejo Harold.}
{109}{}{¿Y eso?}
{110}{}{De nada.}
{111}{HROLD3}{
[Tose] El resto de los Ejeros han estado metiéndose conmigo desde que volví a la ciudad. Pero aún no puedo marchar. Cuando los tratos estén hechos [Respira]. Este es mi hogar.}
{112}{}{¿Qué te sucedió?}
{113}{}{¿Quiénes son los Ejeros?}
{114}{}{Espero que las cosas mejoren. Ya nos veremos.}
{115}{HROLD4}{
Bueno, tras la Gran Guerra, mi Refugio fue el primero en abrirse. [Respira hondo] Vaya. Hace mucho de eso.}
{116}{}{Cuéntame más de aquellos tiempos.}
{117}{}{No, no. Quiero decir, ¿qué te hizo cambiar?}
{118}{HROLD5}{
Todo empezó con las sirenas. Yo era muy joven, pero, oh, me acuerdo de eso. Después vinieron años terribles. Y recuerdo que una mañana salí caminando del Refugio.}
{119}{}{¿Qué hiciste entonces?}
{120}{}{¿Dónde estaba ubicado tu Refugio?}
{121}{}{¿Te das cuenta de lo viejo que te hace eso?}
{122}{HROLD6}{
¿Sabes? [Tose] Ya no estoy realmente seguro. Al oeste, creo. O, espera, al este. Oh, no lo sé. [Tos seca]}
{123}{}{¿Qué hiciste entonces?}
{124}{HROLD7}{
Bueno, era un comerciante. Me lo monté bastante bien haciendo un circuito entre los supervivientes. Aunque perdí a buena gente. [Tose]}
{125}{}{¿Cómo?}
{126}{HROLD8}{
Los de las bandas les cogieron. Carroñeros que atacaban las caravanas. Y mutantes, hijos de perra, cuando no estaban correteando por ahí con una misión. [Tose] Necesitaba un ejército de guardas, sólo para hacer un trato.}
{127}{}{¿Tener guardas no ayudaba?}
{128}{}{¿De dónde venían los mutantes?}
{129}{HROLD9}{
¡Claro que ayudaba, cabeza hueca! ¡Pero los otros eran demasiados!}
{130}{}{¿Cómo sobreviviste a los ataques mutantes?}
{131}{HROLD9A}{
No lo hice. Me mataron. [Tos con risa] Me encanta esa broma.}
{132}{}{Ah, sí.}
{133}{HROLD10}{
¡De todas partes! Demonios, no te podías tirar un pedo sin darle a uno. Pero sobre todo por el noroeste.}
{134}{}{¿Exploraste el área?}
{135}{}{¿Por qué no evitaste el área?}
{136}{}{¿Te tirabas pedos por el noroeste?}
{137}{hrold10a}{[Ríe] No está mal... Noo...}
{138}{HROLD11}{
Organizamos una expedición. Dios, Richard. Richard Grey. Llevó un grupo de nosotros hasta allí.}
{139}{}{¿Richard Grey?}
{140}{}{¿Dónde fuisteis exactamente?}
{141}{HROLD12}{
Teníamos que ver lo que había allí. Intentar detener lo que que hacía aparecer a los mocosos. Pensamos que estábamos preparados. Pero nos equivocamos.}
{142}{}{¿Qué hicisteis?}
{143}{HROLD13}{
No recuerdo la ruta ni nada. Pero, por la virgen, que era al noroeste.... Creo.}
{144}{}{¿Hay una versión abreviada de esta historia?}
{145}{}{¿Qué hay de tu líder?}
{146}{HROLD14}{
Richard Grey era un médico. Era algo más mayor, y amigo, era listo. Encontró el origen.}
{147}{}{¿Y qué era?}
{148}{HROLD15}{
Me gusta contarlo a mi manera. La versión corta te costará 25 más, colega. ¿Cuál prefieres?}
{149}{}{Vale, que sea larga.}
{150}{}{La corta.}
{151}{}{La corta, pero no tengo las chapas.}
{152}{}{¿Qué tal si no es ninguna, pedorro?}
{153}{HROLD16}{
Bueno, pareces buena gente. Intentaré no enrollarme demasiado.}
{154}{}{Gracias.}
{155}{hrold16a}{Mentirle a un pobre viejo mutante. ¿Dónde va a llegar el mundo? [Tose]}
{156}{hrold17}{Escaso de fondos, ¿eh?}
{157}{hrold17a}{A mi manera o te largas. Tú eliges, colega.}
{158}{}{Andando.}
{159}{}{Vale. Que sea larga.}
{160}{HROLD18}{
Una especie de vieja base militar. Perdimos a muchos hombres allí dentro.}
{161}{}{¿Cómo sabes que esa base era la causa?}
{162}{}{¿Con qué os encontrasteis?}
{163}{HROLD19}{
Robots y cosas así. Un montón. Nos sorprendimos de que siguiesen funcionando después de tanto tiempo, tras la guerra y eso. ¡Oh, muchacho, nos dieron una buena!}
{164}{}{¿Que hicisteis cuando acabasteis con los Robots?}
{165}{HROLD20}{
¡Porque era como si alguien hubiese ido de rebajas a mutantelandia! ¡Maldita sea! ¡Más baratos por docenas! No se me ocurre ninguna otra razón, aparte de que aquello fuese la fábrica.}
{166}{}{¿Examinasteis cuidadosamente la base?}
{167}{HROLD21}{
Nos adentramos bastante. No quedábamos muchos. Grey, yo y un par más.}
{168}{}{¿Y entonces?}
{169}{HROLD22}{
Uno de los robots cogió a Francine. Hirieron a Mark y le mandamos a la superficie. Sólo quedábamos Grey y yo.}
{170}{}{¿Qué le sucedió a Mark?}
{171}{}{¿Entonces qué ocurrió?}
{172}{HROLD23}{
No tengo ni idea. No consiguió regresar aquí, y... bueno, yo... no podía volver a los yermos, así que... nunca le busqué.}
{173}{}{¿Qué fue de ti y de Grey?}
{174}{HROLD24}{
Llegamos a una especie de núcleo central, como una planta de energía o algo así. Entonces es cuando ocurrió.}
{175}{}{¿El qué?}
{176}{HROLD25}{
Un robot grúa se estrelló contra nosotros. La última vez que vi a Grey volaba por los aires hacia un baño ácido o algo por el estilo. Yo estaba muy mal, y bueno... salí del paso.}
{177}{}{¿Cómo pudiste sobrevivir?}
{178}{}{¿Y nunca más volviste a ver a Grey?}
{179}{hrold25a}{No lo hice. Me mataron...[Tose y se ríe] Dios, me encanta esa broma.}
{180}{}{Sí, ya veo.}
{181}{HROLD26}{
No tengo ni idea. Me desperté en los yermos, medio muerto. Tuve suerte, unos días después me encontraron unos comerciantes. Menos mal, porque ya estaba empezando a cambiar. Ellos me trajeron aquí y aquí estoy desde entonces.}
{182}{}{¿Cómo mutaste?}
{183}{}{Una buena historia. Gracias.}
{184}{hrold26a}{Bueno... gracias a ti por dejarme contarla.}
{185}{}{¿Esa era la versión corta?}
{186}{hrold26a}{Bueno... gracias a ti por dejarme contarla.}
{187}{hrold26b}{Para mí lo era.}
{188}{HROLD27}{
¡No, idiota! Acabo de decir que no le volví a ver, ¿no?}
{189}{}{¿Cómo sobreviviste?}
{190}{HROLD28}{
Todo lo que sé es que había algo dentro de aquella base.}
{191}{}{¿Piensas que pudo ser la radiación?}
{192}{}{Lo siento, mal rollo. Gracias por la historia.}
{193}{HROLD29}{
¿Cómo demonios podía saberlo? Grey es el único que podía saberlo. [Suspira] De todas formas ese fue el final del trato.}
{194}{}{Gracias.}
{195}{HROLD30}{
Sí, como un siglo o dos, en años de perro.}
{196}{}{¿Qué?}
{197}{HROLD31}{
No hagas caso, eso era de mi época. Estoy viejo y chiflado y he estado así desde que cambié.}
{198}{}{¿Qué hacías antes de que te pasase esto?}
{199}{HROLD32}{
Bueno, sufrí una mutación. No pude haber nacido tan feo. Ocurrió cuando intentábamos descubrir de dónde salían todos los mutantes.}
{200}{}{¿Qué sucedió?}
{201}{HROLD33}{
Eso pertenece al pasado. Y ahí es donde debe quedarse.}
{202}{}{Por favor cuéntame lo que ocurrió, puede que me ayude ahora.}
{203}{}{Como quieras.}
{204}{HROLD34}{
Bueno, si lo pones así. Supongo que no puede hacer daño.}
{205}{}{Gracias.}
{206}{HROLD35}{
No, no. Incluso ahora, es demasiado doloroso. Gracias por la ayuda, amigo. Te deseo buena suerte.}
{207}{HROLD36}{
Estás en el Eje, ¿no? ¿La gente que vive en el Eje? Ejeros. ¿Lo coges? [Tose] ¡Chiist! Gracias por la ayuda y buena suerte... la vas a necesitar.}
{208}{HROLD37}{
Eres tan malo como los demás. [Respira pesadamente]}
{209}{HROLD38}{
Oh, vaya, gracias de todas formas. [Tose]}
{210}{HROLD39}{
Oye, ¿puedes ayudarme, amigo?}
{211}{}{Sí, aquí tienes 25 chapas.}
{212}{}{Toma 5 chapas.}
{213}{}{No me des el coñazo.}
{214}{}{¿Eh?}
{215}{HROLD40}{
¡Oye, aprécialo! Tengo que admitir que cuando te vi por primera vez, [Tose] me imaginé que igual intentabas abusar de mí.}
{216}{}{¿Por qué dices eso?}
{217}{}{¡Nah, yo no! Soy uno de los buenos.}
{218}{HROLD41}{
Oh, vaya, eres tú otra vez.}
{219}{}{Aquí hay 20 chapas, por si las necesitas.}
{220}{}{Hola.}
{221}{}{¿Ehh?}
{222}{hrold42}{Quedándote conmigo, ¿eh?}
{223}{HROLD43}{
¿Puedo hacer algo por ti?}
{224}{}{¿Tienes alguna novedad que contarme?}
{225}{}{Necesito información sobre la Garra Mortal. Me han dicho que tú eres mi hombre.}
{226}{}{¿Cuál es tu historia?}
{227}{}{No.}
{228}{hrold43a}{¿Toda entera? Bueno...}
{229}{HROLD44}{
Oooh, vaya, gracias. Espero que no haya sido un esfuerzo demasiado grande. [Tose]}
{230}{HROLD45}{Oooh, sobre eso. Es una pesadilla. ¿Por qué diablos preguntas por ella?}
{231}{}{Voy a ponerle fin.}
{232}{}{Si me topo con una, quiero saber lo que debo hacer.}
{233}{HROLD47}{Vale. Bueno, es jodidamente grande, macho, sí que lo es. Tiene pinchos y garras que pueden cortar la armadura más pesada. Pero no te dejes engañar por el tamaño, es muy rápida.}
{234}{}{¿Alguna debilidad?}
{235}{HROLD49}{Bueno, por lo que he oído, quizás si le arreas en la cabeza... Yo probaría con los ojos. Claro que, hay un problema.}
{236}{}{¿Qué clase de problema?}
{237}{HROLD50}{¡No puedes mirarlas a los ojos! Se cuenta que la Garra Mortal puede hipnotizarte sólo con la mirada. Luego se acerca y "bum", ¡estás muerto!}
{238}{}{Estupendo, gracias.}
{239}{HROLD51}{Buena suerte... la vas a necesitar.}
{240}{}{Puede que sí.}
{241}{HROLD52}{No quieres saber nada sobre la Garra Mortal y no seré yo quien te lo cuente.}
{242}{HROLD53}{Bueno, he oído que uno de los hombres de Decker tiene a alguien de la Hermandad del Acero atrapado en la Ciudad Antigua.}
{243}{}{Gracias.}
{244}{HROLD54}{Yo no me lo creo, pero dicen que un ejército de mutantes está en camino. [Tose]}
{245}{}{Gracias.}
{246}{HROLD55}{Déjame en paz. [Tose]}
{247}{}{Quiero hablar contigo.}
{248}{}{Toma algunas chapas.}
{249}{HROLD56}{Pues yo no quiero hablar contigo. ¡Lárgate!}
{250}{HROLD57}{No quiero tus chapas. ¡Lárgate! [Tose]}
{251}{hrold200}{Con lo que me gusta comerciar y no tengo nada que darte a cambio. [Tose]}
{252}{hrold201}{Necesito dormir un rato. Estoy un poco cansado.}
{253}{hrold202}{Quizás deberías tener más cuidado. [Tose] He oído que hace poco perdiste varios hombres.}
{254}{hrold203}{Emm... Decker te anda buscando. Quiere hablar contigo. [Tose]}
{255}{hrold204}{Todo lo que tengo es mi ropa y mi libertad y la segunda es discutible.}
{256}{hrold300}{Un tipo muy listo. Médico y filósofo. Hace mucho lideró la expedición durante la cual me convertí en un mutante.}
{257}{hrold301}{¿Quién? ¿Es una especie de terapeuta sexual? Puede que necesite uno.}
{258}{hrold302}{Mutantes. Por muchos nombres que se pongan.}
{259}{hrold303}{Oh, él. Es el jefe del Gremio de los Ladrones. Se cree Robin Hood. [Tose] No es mal tipo, supongo.}
{260}{hrold304}{He visto religiones nacer y desaparecer y espero que ésta desaparezca. Pronto.}
{261}{hrold305}{Sí, vengo de un Refugio. Demasiada gente, poca comida y poca agua. Pero tú no sabrás nada de eso, ¿verdad?}
{262}{hrold306}{Terrible. El mundo se volvió loco. Fue hace mucho, pero nunca lo olvidaré. Jamás.}
{263}{hrold307}{[Tose] Problemas. Sólo problemas.}
{264}{hrold400}{Bueno, como ya he dicho...}
{265}{}{Nada, gracias.}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{266}{HROLD0}{Dame algo, colega, viejo amigo. Ayuda a un pobre mutante
 que ha caído en desgracia. [Tose]}
{267}{HROLD0}{Dame algo, colega, vieja amiga. Ayuda a un pobre mutante
 que ha caído en desgracia. [Tose]}
{268}{HROLD2}{Oh, muy amable de tu parte amigo. ¿Sabes? Si pudiese
 limpiar la porquería de ahí afuera, puede que encontrases una lágrima en el ojo del viejo Harold.}
{269}{HROLD2}{Oh, muy amable de tu parte amiga. ¿Sabes? Si pudiese
 limpiar la porquería de ahí afuera, puede que encontrases una lágrima en el ojo del viejo Harold.}
{270}{HROLD35}{No, no. Incluso ahora, es demasiado doloroso. Gracias por la ayuda, amigo.
 Te deseo buena suerte.}
{271}{HROLD35}{No, no. Incluso ahora, es demasiado doloroso. Gracias por la ayuda, amiga.
 Te deseo buena suerte.}
{272}{HROLD39}{Oye, ¿puedes ayudarme, amigo?}
{273}{HROLD39}{Oye, ¿puedes ayudarme, amiga?}

#
# Harold's Tell-Me-Abouts
#


{1000}{}{Richard}
{1001}{}{Maestro}
{1002}{}{Necrófagos}
{1003}{}{Loxley}
{1004}{}{Catedral}
{1005}{}{Refugio}
{1006}{}{Guerra}
{1007}{}{Decker}
{1008}{}{Grey}

{1100}{hrold300}{Un tipo genial. Médico y filósofo. Hace mucho lideró la expedición durante la cual me convertí en un mutante.}
{1101}{hrold301}{¿Quién? ¿Es una especie de terapeuta sexual? Puede que necesite uno.}
{1102}{hrold302}{Mutantes. Por muchos nombres que se pongan.}
{1103}{hrold303}{Oh, él. Es el jefe del Gremio de los Ladrones. Se cree Robin Hood. [Tose] Supongo que no es un mal tipo.}
{1104}{hrold304}{He visto religiones nacer y desaparecer y espero que esta desaparezca. Pronto.}
{1105}{hrold305}{Sí, vengo de un Refugio. Demasiada gente, poca comida y poca agua. Pero tú no sabrás nada de eso, ¿verdad?}
{1106}{hrold306}{Terrible. El mundo se volvió loco. Fue hace mucho, pero nunca lo olvidaré. Jamás.}
{1107}{hrold307}{[Tose] Problemas. Sólo problemas.}
{1108}{hrold300}{Un tipo genial. Médico y filósofo. Hace mucho lideró la expedición durante la cual me convertí en un mutante.}