# These are people who are running caravans. either gender, but majority Male
# Tone of voice similar to truck drivers of California-- rough and partially
# harsh.

{100}{}{Estás viendo a un conductor de caravanas.}
{101}{}{¡Hoy va a ser un día muy largo!}
{102}{}{Hoy no tengo ningunas ganas de trabajar.}
{103}{}{Espero que no nos ataquen los Piratas.}
# attacked by raiders

{104}{}{Lo siento, no necesitamos más guardias, creo.}
{105}{}{Lo siento, ya estamos completos.}
# we have enough people for this trip

{106}{}{Deberías probar en el Mercado de Mercaderes si quieres un trabajo.}
# Merchant Market is a section of town in which people gather.

{107}{}{Espero que lo vendamos todo.}
{108}{}{No puedo esperar a que terminemos.}
# finish this job.

{109}{}{Tomemos la carretera.}
{110}{}{Estoy preparado para pelear.}
# i'm ready for some brawling

{111}{}{¡Estamos fuera!}
{112}{}{Hoy hace mucho calor.}
{113}{}{Tengo mucha sed.}
# i am very thirsty

{114}{}{¿Qué día es hoy?}
{115}{}{¡Me iré al Halcón en cuanto termine!}
# Falcon is short for Maltese Falcon--Drinking and gambling hall

{116}{}{Lo siento, volvemos de una expedición.}
{117}{}{Deberías probar en el Mercado de Mercaderes si quieres un trabajo.}
# Merchant Market is a section of town in which people gather.

{118}{}{¡Hoy es día de pago!}
{119}{}{Me voy directamente al chiringuito de Bob.}
# Bob's is short for Bob's Iguana Bits -- eating establishment
{120}{}{¡Tengo que devolver el préstamo hoy!}
{121}{}{Estoy muy cansado.}
{122}{}{¡Ha sido un largo viaje!}

{123}{}{Ya ha llegado la noche, supongo.}
{124}{}{Os veo mañana, amigos.}
{125}{}{Jo, colega, vaya noche.}
{126}{}{Me estoy haciendo viejo.}

{200}{}{Estás viendo a Mat.}
{201}{}{Os veré mañana, chicos. No dejéis que el perro os muerda...}
{202}{}{Ha sido un sueño extraño.}

{203}{}{¿Sí? ¿En qué puedo ayudarte?}
{204}{}{¿Eh?}
{205}{}{¿Qué lugar es éste?}
{206}{}{¿Puedes decirme dónde puedo encontrar un Chip de agua?}
{207}{}{¿Qué hacen esos carros ahí?}
{208}{}{Oh. Perdóname. Creía que eras otra persona. Adiós.}
{209}{}{Sí. Podrías morir.}

{210}{}{Demasiado tiempo en el desierto, ¿eh? Qué lastima.}
{211}{}{Esto es el Eje. Es el centro comercial del desierto. Es la ciudad más grande que conozco, aquí puedes encontrar todo lo que quieras. Y si estás buscando trabajo, éste es el lugar idóneo. Es como si todo el mundo aquí quisiera contratarte para algo, sea legal o no.}

{212}{}{¿Puedes decirme dónde puedo encontrar un Chip de agua?}
{213}{}{¿Qué hacen esos carros ahí?}
{214}{}{¿Comercio? ¿Qué es lo que comercias?}
{215}{}{¿Dónde debo ir para conseguir un trabajo?}
{216}{}{Adiós.}

{217}{}{¿Un Chip de agua? Guau. No tengo ni idea. Nunca he oído hablar de eso. Quizás debas preguntar en el Almacén General; allí pueden ayudarte.}
{218}{}{¿Qué hacen esos carros ahí?}
{219}{}{Gracias. Adiós.}

{220}{}{Son caravanas. Llevamos productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares. Necrópolis y el Ardor son los únicos dos sitios a los que no vamos. Dirijo a este grupo y ya partimos. El grupo de enfrente acaba de llegar.}
{221}{}{¿Es la misma caravana que he visto antes?}
{222}{}{¿Qué es lo que comercias?}
{223}{}{¿Qué lugar es éste?}
{224}{}{¿Dónde puedo encontrar trabajo?}
{225}{}{Gracias. Adiós.}

{226}{}{Umm... Mucho material. Materias primas que la gente necesita. Comida, agua, mucha agua. El agua es probablemente el producto más apreciado en el desierto.}
{227}{}{¿Podrías decirme dónde puedo encontrar un Chip de agua?}
{228}{}{¿Dónde puedo encontrar trabajo?}
{229}{}{Gracias. Adiós.}

{230}{}{Puedes preguntarle a cualquiera aquí en el Eje. O puedes mirar en un boletín de ofertas de empleo. Hay unos cuantos en el Eje. Una cosa está clara, hay más trabajo que gente.}
{231}{}{¿Qué lugar es éste?}
{232}{}{¿Podrías decirme dónde puedo encontrar un Chip de agua?}
{233}{}{¿Qué hacen aquí todos estos carros?}
{234}{}{Gracias. Adiós.}
{235}{}{[Risas] Sí, supongo que tienes razón. Cuando pasa el tiempo todo parece igual. Pero créeme, no todo es igual.}
{236}{}{¡¡¡Morirás por reírte de mí!!!}
{237}{}{¿Dónde puedo encontrar trabajo?}
{238}{}{Adiós.}

{300}{}{Estás viendo a Luke.}
{301}{}{Son caravanas. Llevamos productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares. Acabamos de llegar y ha sido un duro viaje. El grupo de enfrente se está preparando para partir.}

{400}{}{Estás viendo a John.}
{401}{}{¿Qué haces aquí a estas horas?}
{402}{}{Eres idiota. Vete de aquí.}
{403}{}{¿Un Chip de agua? No sé de qué me hablas.}
{404}{}{Son las caravanas que estoy vigilando. Llevan productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares.}
{405}{}{Umm... Mucho material. Materias primas que la gente necesita. Comida, agua, mucha agua. El agua es probablemente el producto más apreciado en el desierto.}
{406}{}{Puedes preguntarle a cualquiera aquí en el Eje. O puedes mirar en un boletín de ofertas de empleo. Hay unos cuantos en el Eje.}
{407}{}{Soy un guardia de seguridad contratado por los mercaderes dueños de las cosas que hay en los carros. Es un trabajo peligroso, pero se paga bien. La otra noche asesinaron a uno de mis colaboradores mientras vigilaba las Caravanas.}
{408}{}{¿Qué son las Caravanas?}
{409}{}{Ahhhh. [Sarcástico.] Vaya historia más triste. Te encantará acompañar a tu amigo.}
{410}{}{Adiós.}