{100}{}{Estás viendo a un guardia.}
{101}{}{¡Oye! Tú no trabajas aquí.}
{102}{}{¿No ves que intento descansar?}
{103}{}{Es momento de descanso y relajación.}
{104}{}{No contratamos a nadie. Habla con los mercaderes.}
{105}{}{El servicio ha sido muy tranquilo últimamente.}
{106}{}{¡Estas son las dependencias de los guardias! Nada de yonquis.}
{107}{}{¿Eres nuevo?}
{108}{}{Déjame solo. Estoy cansado.}
{109}{}{¿Alguien quiere jugar a las cartas?}
{110}{}{¿Quién me cambia el turno de noche?}
{111}{}{Mañana iremos al Halcón.}
{112}{}{Claro.}
{113}{}{¿Quién quiere ir a cazar escorpiones esta semana?}
{114}{}{Me duelen los pies.}
{115}{}{Creo que necesito dormir.}
{116}{}{¿Se paga a diario?}
{117}{}{No tengo servicio de caravanas.}