{100}{}{Estás viendo al Sheriff Justin Greene.}
{101}{}{Oh, el asesino de inocentes. He oído hablar de ti y tienes suerte de que la estrella me impida
 liquidarte de inmediato. Te sugiero que abandones nuestra ciudad ahora mismo. Y aléjate de nuestros hijos.}
{102}{}{¡Hola, señor! Me llamo Justin Greene. Soy el Sheriff de esta bonita ciudad. ¿Hay algo que pueda
 hacer por ti ahora?}
{103}{}{¡Hola, señora! Me llamo Justin Greene. Soy el Sheriff de esta bonita ciudad. ¿Hay algo que pueda
 hacer por ti ahora?}
{104}{}{Sí, ¡desaparece!}
{105}{}{Decker me contrató para matar a un mercader y a su mujer.}
{106}{}{Decker intentó contratarme para matar a una tal Jain.}
{107}{}{Nada, gracias.}
{108}{}{Lo siento, no puedo decirte nada. Me matarían.}
{109}{}{Gracias. Intentamos hacerlo bien. Es muy difícil en una ciudad de este tamaño, pero hacemos lo que podemos con los
 recursos disponibles. Es difícil cuando esos tipos tienen mejores armas de fuego que nosotros.}
{110}{}{Gracias de nuevo.}
{111}{}{Es hora de irse, matón.}
{112}{}{No podemos aceptar. Pero si cambias de opinión, házmelo saber. Este lugar es muy
 peligroso y alguien tiene que velar por que las cosas funcionen bien.}
{113}{}{¡Excelente! Ya había oído rumores sobre su plan. Tú eres la confirmación final que necesitaba
 para hacer algo contra él. Va a ser difícil y puedo utilizar toda la ayuda disponible. Te pagaré 1.000
 chapas, 200 ahora y el resto cuando hayas terminado el trabajo. ¿Qué dices?}
{114}{}{¡Llegas demasiado tarde! Sabía que era culpable, sólo quería saberlo a tiempo para detenerle. En cualquier caso,
 eres el testigo que necesitaba para actuar. Tendremos que "acabar con él". Va a ser duro y puedo
 utilizar toda la ayuda disponible. Te pagaré 1.000 chapas, 200 ahora y el resto cuando hayas terminado el trabajo. ¿Qué dices?}
{115}{}{Llegas demasiado tarde. ¿Cómo sé que no eres culpable? Seguro que a Decker no le gusta que nadie conozca sus
 planes y su vida.}
{116}{}{Acabo de oír que ella ya está muerta... espera un minuto. ¿Cómo sé que tú no eres culpable?
 Seguro que a Decker no le gusta que alguien conozca sus planes y su vida.}
{117}{}{Será un placer.}
{118}{}{Lo siento, lo quiero todo por adelantado.}
{119}{}{¡Ni hablar! Es tu problema y no el mío.}
{120}{}{No. Aunque parezcas digno de confianza no puedo estar seguro de que te quedarás con nosotros cuando las cosas empeoren. Por lo menos uno de nosotros tiene que sobrevivir para asegurarse de que cobras. De este modo se contará con un "poco" de seguridad.}
{121}{}{Vale.}
{122}{}{Hazlo tú solo, Sheriff.}
{123}{}{¡Vale! Podemos irnos cuando quieras.}
{124}{}{Ya mismo.}
{125}{}{Bien. Adiós.}
{126}{}{Lamento oír eso. Si cambias de opinión, por favor, házmelo saber, pero no puedo esperar mucho.}
{127}{}{Vale, lo haré. Espera a que coja algunos suministros.}
{128}{}{Estás mal de la cabeza.}
{129}{}{Adiós.}
{130}{}{¡Vale! Avísame cuando quieras salir. Te esperaremos, pero no tardes mucho.}
{131}{}{¿Qué? ¡Pretendes que me dedique a matar a gente inocente? Tengo una deuda contraída con esta ciudad,
 que no espero que entiendas.}
{132}{}{Tienes razón. Ahora te toca a ti.}
{133}{}{¿Cómo te atreves a acusarme?}
{134}{}{No me importa lo que pienses.}
{135}{}{Bien. Él no ha intentado nada.}
{136}{}{Estábamos en el Halcón y había mucha gente alrededor.}
{137}{}{Lo siento. Decker ha estado enfrentándonos los unos a los otros durante años. Ya no sé en quién confiar.
 Pero podrías serme de gran ayuda. Será duro, pero te pagaré 1.000 chapas, 200 ahora y el resto cuando
 hayamos terminado el trabajo.}
{138}{}{¡Conozco a una rata de lejos! Tienes suerte de que no tenga pruebas, y te recomiendo abandonar la ciudad antes de que encuentre alguna.}
{139}{}{Es muy raro. Nunca he oído que Decker salga de su despacho. Debe de coger valor. Ese maldito,
 ha asesinando... ¡Argh! ¡Pero lo cogeré! Te diré una cosa, tú nos ayudas y te pagaré 1.000 chapas...
 200 ahora y 800 cuando hayamos terminado el trabajo. ¿Qué dices?}
{140}{}{Es la mayor montaña de mierda de Brahmin que he oído en mi vida. Decker nunca sale de su despacho. Sabía que algo
 andaba mal contigo. Tienes suerte de que no tenga pruebas. Te recomiendo que abandones la ciudad antes de que encuentre alguna.}
{141}{}{Vale, vamos...}
{142}{}{Así que has vuelto para entregarte, ¿eh? Me impresionas.}
{143}{}{Sí, lo siento.}
{144}{}{¿Entregarme? No me hagas reír.}
{145}{}{¡Cogedlo!}
{146}{}{¡Cogedla!}
{147}{}{Vale, te meteré en tu celda.}
{148}{}{No muevas ni un dedo. No te vas a mover en una temporada.}
{149}{}{¡Fugitivo! ¡Cogedle!}
{150}{}{¡Fugitiva! ¡Cogedla!}
{151}{}{¿Todo listo?}
{152}{}{Sí.}
{153}{}{No}
{154}{}{Ug.}
{155}{}{No me puedo creer que Decker haya muerto por fin. Creía que nunca llegaría este día.}
{156}{}{¿Has cambiado de opinión? ¿Aún podemos utilizarte para deshacernos de esa enfermedad de la que hablamos?}
{157}{}{Iré.}
{158}{}{No, lo siento.}
{159}{}{¿Eh?}
{160}{}{Te estaremos vigilando.}
{161}{}{¡Tengo que denunciar un crimen.}
{162}{}{Tienes un buen trabajo.}
{163}{}{Venga, ya nos volveremos a ver.}
{164}{}{Vale.}
{165}{}{Hola de nuevo, señor. ¿En qué puedo ayudarte hoy?}
{166}{}{Hola de nuevo, señora. ¿En qué puedo ayudarte hoy?}
{167}{}{Hola, ¿en qué puedo ayudarte?}
{168}{}{¿Sí?}
{169}{}{Desaparece, ¿vale?}