# Hot spots are intense concentrations of radiation. Consider Neutral or Male.
# Tone of Voice should be automated and flat.

# Lines are "You sustain [2 or more] points of radiation damage"
{100}{}{Sufres }
{101}{}{ puntos de daño por las radiaciones.}
{102}{}{Sufres }
{103}{}{ puntos de daño por las radiaciones.}
{104}{}{Cerca hay una alta concentración radioactiva.}
{105}{}{Sufres }
{106}{}{ puntos de daño por las radiaciones.}

