{100}{}{Estás viendo a León, un guardia.}
{101}{}{¿Qué haces aquí?}
{102}{}{Debo hablar con el Sr. Hightower.}
{103}{}{He venido a matar al Sr. Hightower.}
{104}{}{¿A qué te dedicas?}
{105}{}{Vale. Pero te estaré vigilando. Está en su despacho.}
{106}{}{Gracias.}
{107}{}{Sí... Apuesto a que me estarás vigilando.}
{108}{}{No me gustan tus modales. Tendré que pedirte que te marches.}
{109}{}{Me marcharé cuando me dé la gana, colega.}
{110}{}{Vale, me voy.}
{111}{}{¿Modales? ¡¡Yo te enseñaré modales!!}
{112}{}{Sea lo que sea, dímelo a mí. El Sr. H. está ocupado ahora.}
{113}{}{¿Por qué tienes que ser tan difícil?}
{114}{}{Preferiría decírselo en persona. Es un asunto de vida o muerte.}
{115}{}{Decker ha puesto precio a la cabeza de Hightower.}
{116}{}{Puedes decírmelo o marcharte.}
{117}{}{¿Quién ha muerto y te ha deificado?}
{118}{}{Decker ha puesto precio a la cabeza de Hightower.}
{119}{}{Mira, no voy a soltar ni una palabra.}
{120}{}{Me iré.}
{121}{}{¿Otra vez? Lo imbécil que es Decker. ¿Y?... Supongo que no es tan imbécil como esos chicos que contrata para esos trabajos. Mira,
 observa mi arma.}
{122}{}{[León te enseña un lado de su pistola donde pueden observarse 5 profundas muescas.]}
{123}{}{Estas muescas recuerdan los anteriores intentos de asesinato de Hightower. Frustré todos y cada uno de ellos. Dime,
 ¿sabes qué aspecto tienen los tipos que ha contratado Decker?}
{124}{}{No.}
{125}{}{¡Soy yo, idiota!}
{126}{}{¡Oye! ¡Guau! ¡Tienes muescas en tu arma! ¡Eres alucinante!}
{127}{}{Gracias por la advertencia, pero al Sr. Hightower no le gusta que los extranjeros anden por aquí. Tendré que pedirte que te vayas.}
{128}{}{¿Eso es todo? ¿No hay recompensa? ¿Qué cuernos os pasa?}
{129}{}{De nada. Adiós.}
{130}{}{El Sr. Hightower no recibe visitas. ¡Ahora vete!}
{131}{}{Me iré cuando me dé la gana, colega.}
{132}{}{Vale, me iré.}
{133}{}{Necesito hablar con el Sr. Hightower.}
{134}{}{Vale, colega. Vamos. [León te agarra del brazo.]}
{135}{}{¡Quita tus asquerosas manos de mí!}
{136}{}{¡Vale, vale! Me voy.}
{137}{}{¡Espera! ¡No he terminado!}
{138}{}{¡Uh!}
{139}{}{¡Ay!}
{140}{}{Tengo noticias urgentes para el Sr Hightower.}
{141}{}{¿Qué haces aquí? Ya no estoy de servicio. Vete a incordiar a otro.}
{142}{}{Pensaba que ibas a estar ausente durante más tiempo. ¡Guardias!}
