{100}{}{Estás viendo a Rick, un guardia.}
{101}{}{¿Qué quieres?}
{102}{}{Da... Um...}
{103}{}{Perdona. ¿puedo hacerte unas preguntas?}
{104}{}{¡Vete de aquí!}
{105}{}{No importa.}
{106}{}{¡Vuelve a la parte Este, descerebrado!}
{107}{}{¿Qué?}
{108}{}{Me voy.}
{109}{}{Hazlo rápido. No puedo hablar mientras trabajo.}
{110}{}{¿Dónde estoy?}
{111}{}{¿En qué trabajas?}
{112}{}{Lamento molestarte. Adiós.}
{113}{}{Deberías irte y callarte, ¡cerebro de mosquito!}
{114}{}{¡NO! ¡Deberías tener cuidado! ¡Voy a meterte una bala en la cabeza!}
{115}{}{No voy a perder el tiempo contigo.}
{116}{}{Si no lo sabes, no deberías estar aquí. Estás en las Alturas. El Señor Hightower vive aquí
 y sólo recibe con cita previa.}
{117}{}{¿En qué trabajas?}
{118}{}{¿Puedo concertar una cita con el Sr. Hightower?}
{119}{}{Gracias por dedicarme tu tiempo.}
{120}{}{Estoy aquí para asegurarme que nadie se mete con el Sr. Hightower.}
{121}{}{Bueno, realmente estoy interesado en asesinar al Sr. Hightower. ¡Es hora de que te ganes tu paga!}
{122}{}{¿Dónde estoy?}
{123}{}{Gracias por dedicarme tu tiempo. Adiós.}
{124}{}{No.}
{125}{}{No me gusta tu comportamiento. Deberías irte.}
{126}{}{Vale. Ya me voy.}
{127}{}{¡Déjame en paz, despiadado mastodonte!}
{128}{}{Después de anochecer nadie puede entrar aquí. Los otros guardias ni siquiera te avisarán. Si te cogen,
 acabarán contigo. Deberías volver al centro de la ciudad ahora que tienes todavía la cabeza sobre los hombros.}
{129}{}{Vale. Me voy.}
{130}{}{No. Me quedo.}
{131}{}{No voy a ninguna parte.}
{132}{}{Lo siento, seguiré mi camino.}
{133}{}{Colega, eres imbécil, ¿verdad? ¡Piérdete!}