{100}{}{Estás viendo a George, el guardia de la puerta.}
{101}{}{¿Puedo ayudarte?}
{102}{}{Quiero ver al Sr. Tower.}
{103}{}{Sí. Estoy aquí para ver al Sr. Hightower.}
{104}{}{Tengo una cita con el Sr. Hightower y llego tarde.}
{105}{}{Déjame entrar.}
{106}{}{El Sr. Hightowerr no recibe a nadie.}
{107}{}{Bien, quiere verme.}
{108}{}{¿Cómo puedo concertar una cita con él?}
{109}{}{Yo no soy nadie, ¡idiota!}
{110}{}{Oh, bien. Adiós.}
{111}{}{Vale. Pasa.}
{112}{}{Conozco a todos los socios del Sr. Hightower y no te había visto antes, por lo que será mejor que te vayas. Ahora.}
{113}{}{¡Te has metido en un buen lío! El Sr. H. odia la falta de puntualidad. Permitiré que te lo diga él mismo.
 Pasa.}
{114}{}{No vas a entrar. ¡Lárgate, idiota!}
{115}{}{No quiero problemas aquí, así que será mejor que te vayas.}
{116}{}{¡Piérdete!}
{117}{}{No vas a cruzar esta puerta.}
{118}{}{¿Qué crees que estás haciendo? ¡¡Guardias!!}
{119}{}{¡Aléjate de esa puerta! ¡Nadie entra ahí sin pasar por encima de mi cadáver!}
{120}{}{¡Demuestras mucho valor al venir aquí! ¡¡Guardias!!}
