{100}{}{Estás viendo una caja fuerte cerrada.}
{101}{}{Estás viendo una caja fuerte que no está cerrada.}
{102}{}{La caja fuerte está cerrada.}
{103}{}{Al abrir la caja fuerte detectas y desactivas una alarma.}
{104}{}{Al abrir la caja fuerte detectas una alarma, pero la activas sin querer.}
{105}{}{Al abrir la caja fuerte detectas una alarma, pero no puedes desactivarla.}
{106}{}{La caja fuerte ya no está cerrada.}
{107}{}{Consigues abrir la caja fuerte.}
{108}{}{Tus numerosos intentos para abrir la caja fuerte han activado la alarma.}
{109}{}{No has podido abrir la caja fuerte porque el cierre se ha roto.}
{110}{}{No has podido abrir la caja fuerte.}
{111}{}{Descubres una alarma en la caja fuerte y la desactivas.}
{112}{}{Descubres una alarma en la caja fuerte.}
{113}{}{Al abrir alarmas en las caja fuerte, activas una sin querer.}
{114}{}{No encuentras ninguna alarma en la caja fuerte.}
{115}{}{Has desactivado la alarma.}
{116}{}{Has activado la alarma sin querer.}
{117}{}{No has podido desactivar la alarma.}
