# These are the police of the Hub (a large metropolis). They are either gender, but using
# Male is the best approach. They are simpltons who have a badge only because no one else
# would take the badge. Speech has an absent-mindedness about it.

{100}{}{Estás viendo a un Oficial de Policía.}
# Police Officer is male

{101}{}{¡Saludos! Deberías tener cui... uh, quiero decir, vigila... [El oficial mira de forma extraña
 a los otros oficiales y menea la cabeza en tu dirección.]}
{102}{}{Hola, forastero... ¡Espera! ¡Te conozco! ¡Te buscan por robo!... ¡No te muevas!}
# Stranger is the player. Consider Male.

{103}{}{Vale, me voy.}
{104}{}{¡Vas a probar mi plomo!}
# "Eat lead" is equivalant to "I'm going to kill you."

{105}{}{¡Kor Rok!}
# "Kor Rok" is just garbled sounds a moronic player is saying.

{106}{}{[Te das por vencido.]}
{107}{}{Ten cuidado, éste no es un lugar seguro.}

# 108/109, 108/110 are lines which go together. "Watch your scripts, guy." or "Watch your scripts, lady."
{108}{}{Vigila tus vales, }
# scripts are money

{109}{}{señor.}
{110}{}{señora.}
{111}{}{No deberías estar aquí, no es seguro.}
{112}{}{La Ciudad Antigua está en ruinas.}
# Old Town is another section of town. This is were the poor and down-trodden live.

{113}{}{Este lugar huele.}
{114}{}{Deberíamos acabar con toda esta zona.}
{115}{}{Estoy seguro de que ese maldito Gremio de Ladrones está por aquí.}
# the Thieve's Circle is similar to a Thieve's Guild. underground organization for thieves.

{116}{}{Pobre Harold, ha tenido una vida dura.}
# Harold is Male

{117}{}{No hagas nada ilegal.}
# == Don't do anything illegal.

{118}{}{Eh. Te conozco. Nada de peleas, ¿vale?}
{119}{}{¡Ni pienses en empezar otra pelea!}
{120}{}{¡Si te pillamos luchando otra vez, estarás entre rejas!}
# "You're going in" equals "You are going to jail"

{121}{}{¿Te has enterado? Los Comerciantes de Ultramar han sido eliminados.}
# Far Go Traders is a merchant's guild

{122}{}{Los Mercaderes de Agua son historia y es una bendición.}
# Water Merchants is a merchant's guild

{123}{}{Alguien eliminó la Caravana Carmesí.}
# Crimson Caravans is a merchant's guild

{124}{}{¿Te has enterado? ¡Los Clandestinos por fin han sido eliminados!}
# Underground is a rough organization for assassins. Akin to the Mafia

{125}{}{¡Decker está Muerto!}
# Decker is Male

{126}{}{Esta ciudad sería más segura con Decker fuera del mapa.}
# == "This town would be safer with Decker dead."
