{100}{}{Estás viendo a un prisionero.}
{101}{}{¡No maté a nadie!}
{102}{}{¡Soy inocente!}
{103}{}{¿Qué estás mirando?}
{104}{}{Sólo lo estaba tomando prestado. ¡Es justo!}
{105}{}{¿Dónde está mi pan y mi agua?}
{106}{}{¡Me han acusado!}
{107}{}{Nadie sabe los problemas que tengo...}

