{100}{}{Estás viendo a Herreriano.}
{101}{}{¿Quieres hablar después de todo lo que has largado? ¡Vete de paseo!}
{102}{}{El jefe ha dicho que te pierdas, ¡así que piérdete!}
{103}{}{¡No hablamos con extranjeros!}
{104}{}{Ahora te saludará otro. Vete a la mierda.}

