{101}{}{Los comerciantes de la caravana no tuvieron ninguna oportunidad. Están todos muertos.}
{102}{}{Parece como si los mutantes estuvieran muy bien armados. Los comerciantes de la caravana no tuvieron ninguna oportunidad para luchar en contra de este tipo de potencia de fuego.}
{103}{}{Están muertos.}
{104}{}{Puedes tener por seguro que esta muerto.}
{105}{}{Entre toda la carne y músculo que ha mutado, uno de ellos te parece familiar. Es uno de los exploradores que el Refugio envió y que nunca volvió a casa...}
{106}{}{Entre toda la carne y músculo, reconoces a uno de los mutantes: es Sean, uno de los exploradores que el Refugio envió unos meses antes de que te marcharas.}
{107}{}{Todos los mutantes están muertos, pero uno, aunque parezca extraño, te parece familiar; sin embargo no reconoces su "cara".}
{108}{}{Mutantes muertos.} 

