{100}{}{Estás viendo a Jake, de los Seguidores.}
{101}{}{Estás viendo a un Seguidor del Apocalipsis.}
{102}{}{¡Bienvenido! ¿En qué puedo ayudarte en el día de hoy?}
{103}{}{¡Yo ayuda! ¡Yo ayuda!}
{104}{}{He oído que eres un guerrero decente. Averigüémoslo.}
{105}{}{He oído que necesitas ayuda. ¿Cuál es el problema?}
{106}{}{¿Qué puedes contarme de los Seguidores?}
{107}{}{Quieres ayudar. No creo que seas lo bastante bueno para
 ayudarme. Ve a hablar con Neil.}
{108}{}{Me encantaría luchar contigo, pero estoy muy liado ahora mismo
 ayudando a Nicole.}
{109}{}{Que te lo crees. Me pareces un gusano más.}
{110}{}{Tú mismo. Adiós.}
{111}{}{¿Cómo un gusano como tú es el segundo en el mando?}
{112}{}{Ey. Solo porque no quiera luchar no significa que sea un
 gusano. No creo que ni me parezca.}
{113}{}{Tenía razón. Eres un gusano.}
{114}{}{Algunos de nosotros usamos nuestros cerebros para llegar más lejos.
 Se puede hacer mucho pacíficamente y pensando.}
{115}{}{Entonces, ¿cuándo vas a usar el tuyo?}
{116}{}{Tienes razón. Lo siento.}
{117}{}{Eso es todo. No voy a hablar más contigo.}
{118}{}{Así está mejor... Tengo un problema con un espía que ronda por aquí.
 ¿Me ayudarás?}
{119}{}{Sí. ¿Qué pasa?}
{120}{}{Apáñatelas tú si eres tan genial.}
{121}{}{Solo he dicho que tenemos un espía por aquí. Creo que uno
 de los guardias podría ser el espía. Aunque podría ser un explorador.
 Esos son los únicos grupos que tienen acceso a los
 Niños.}
{122}{}{Vale. Iré a coger a tu espía y acabar con el problema.}
{123}{}{¿Tienes alguna pista de este espía?}
{124}{}{Olvídalo. No te ayudaré.}
{125}{}{Muchas gracias. ¡Ahora vete!}
{126}{}{En realidad nada. Lo único que sé sobre él es
 que montones de información de bajo nivel está llegando a los
 Niños. Eso no es bueno. Heather piensa que puede ser tanto
 Neil como Peter.}
{127}{}{Vale. Iré a comprobar eso.}
{128}{}{Olvídalo. No te ayudaré.}
{129}{}{Entonces no puedo dejar que te vayas.}
{130}{}{Lo haré. ¡Adiós!}
{131}{}{Estamos teniendo problemas con parte de nuestra información
 y vemos como cae en manos de los Niños. Creo que hay un espía.}
{132}{}{Vale. Entonces, ¿cuál es el problema?}
{133}{}{Vale, me encargaré de este espía.}
{134}{}{¿Tienes ya alguna pista?}
{135}{}{Olvídalo. No te ayudaré.}
{136}{}{En este momento, no puedo decirte nada. Adiós.}
{137}{}{Estoy intentando dormir. No me molestes.}
{138}{}{¡Date prisa y encuentra esa basura vil!}
{139}{}{Ya sabía que era Heather. Desde el principio que ha sido
 una embustera. Debería haberles dicho a todos lo que pensaba desde un principio.}
{140}{}{No aprendí nada de ti. Tu entrenamiento
 fue inútil.}
{141}{}{Tengo un paquete para ti de parte de Gabriel.}
{142}{}{Mmm. Ya veo. Gracias.}
{143}{}{Por todos los diablos, vete.}
{144}{}{Es el camino difícil. Siempre es el camino difícil.}