{100}{}{Estás viendo a Jennifer.}
{101}{}{Estás viendo a una Paladín.}
{102}{}{Discúlpame, Hermano. Deberías apartar tu arma cuando estés
 en la Hermandad. Somos una orden amistosa pero, ya sabes, estos son tiempos difíciles.}
{103}{}{Algunos miembros de la Hermandad pueden sentirse ofendidos si un extraño... quiero decir, un recién Iniciado... se
 les acerca con un arma.}
{104}{}{Buenos días, Iniciado. ¿Puedo ayudarte?}
{105}{}{Hola, Hermana, es bueno ver que hay mujeres de rango en esta organización. No sabía a qué atenerme, como todo el mundo habla
 de los "Hermanos".}
{106}{}{Eh, para un momento. Parece que todo va bien. ¿A qué hora tengo que recogerte?}
{107}{}{¡Oooooga!}
{108}{}{¿Puedes decirme dónde puedo encontrar al Anciano Mayor?}
{109}{}{¿Quién está al cargo de esto?}
{110}{}{¿Dónde está ese Anciano Mayor?}
{111}{}{¡Gruk!}
{112}{}{A Maxson, el Anciano Mayor, podrás encontrarlo en la Cuarta Planta.
 Si coges el otro ascensor para bajar al nivel cuatro, lo encontrarás
 o en la Sala del Consejo o en las habitaciones de los Ancianos.}
{113}{}{Puedes preguntarles a alguno de los guardias de ese nivel; ellos deben saber dónde está en este momento.}
{114}{}{Gracias.}
{115}{}{¿Dónde puedo conseguir armas mejores?}
{116}{}{Debes hablar con Talus. Puede que él te ayude o,
 al menos, te diga con quién debes hablar.}
{117}{}{Durante el día, Talus normalmente supervisa la Sala de Entrenamiento.
 ¿Sabes dónde está eso?}
{118}{}{Sí. Gracias.}
{119}{}{No.}
{120}{}{¡Por supuesto que sí!}
{121}{}{La Sala de Entrenamiento está nada más girar la esquina. Baja por este pasillo, gira a la izquierda, ve hacia la puerta que está al final del pasillo y la encontrarás al otro lado de la puerta, a mano derecha.}
{122}{}{Me has ayudado mucho. Muchas gracias.
 Espero que charlemos otro día. Buenos días.}
{123}{}{¿Sala de entrenamiento? ¿Sabes si puedo entrenarme allí?
 Ahora soy un miembro de la Hermandad, ¿verdad?}
{124}{}{Gracias por tu ayuda, Hermana. Es bueno ver que hay mujeres de rango en esta organización. No sabía a qué atenerme con todo el mundo hablando de los "Hermanos".}
{125}{}{Gracias, Cielo. ¿Sabes que no estás nada mal? ¿Qué tal si nos revisáramos mutuamente el "equipo"?
 ¿A qué hora te vas?}
{126}{}{Ah, ese lugar. Vale, adiós.}
{127}{}{¿Perdona? ¿Pasa algo?}
{128}{}{¿Muk lug?}
{129}{}{Lo siento, no creo que pueda ayudarte. Deberías ir a ver a la doctora. Está en el segundo nivel.}
{130}{}{Por supuesto que sí. Dos de nuestros Ancianos son mujeres, nuestro Maestro Escriba es una mujer y tenemos muchas mujeres en los demás niveles.}
{131}{}{A las mujeres de la Hermandad también se las llama Hermanos. A las mujeres no las
 llamamos Hermanas. Después de todo, ésta es una Hermandad con mayoría de hombres y no de mujeres.}
{132}{}{¿No te parece raro que sea una hermandad mayormente de hombres? Menos mal que hay algunas mujeres.}
{133}{}{¿Entonces por qué se llama la Hermandad?}
{134}{}{Bueno, es bastante extraño.}
{135}{}{No lo sé. Ése ha sido siempre nuestro nombre. Estoy segura de que existe una razón.}
{136}{}{Creo que tienes razón.}
{137}{}{Bueno, me sigue pareciendo algo extraño.}
{138}{}{Es algo raro. En realidad nunca he pensado mucho en ello.
 Hemos estado en la Hermandad del Acero toda nuestra vida. Nuestros antepasados tuvieron que tener una razón para llamarla así.}
{139}{}{Pero eso no significa que las cosas no puedan cambiar.}
{140}{}{Sí, puede que tengas razón.}
{141}{}{Bueno, ¿Puedo ayudarte en algo más?}
{142}{}{Sí, ¿dónde puedo encontrar al Anciano Mayor?}
{143}{}{¿Dónde puedo conseguir mejores armas?}
{144}{}{No, eso es. Adiós}
{145}{}{No, somos muy estrictos cuando se trata de tradiciones. No
 creo que pueda cambiar nunca. No me preocupa demasiado que se dirijan a mí llamándome Hermano, es curioso.}
{146}{}{Creo que tendré una charla con Vree. Creo que ella puede darme alguna pista de porqué nuestros antepasados decidieron denominarse la Hermandad del Acero.}
{147}{}{¿Quién es Vree? ¿Una de los Ancianos?}
{148}{}{Vree es una Maestro Escriba. Tienes que hablar con ella si tienes problemas técnicos, pero no la molestes durante sus meditaciones nocturnas.}
{149}{}{Casi siempre está en su habitación, ubicada en la tercera planta, formando parte de la infraestructura principal.}
{150}{}{¡Una porquería! ¿Cómo te atreves a hablar así de la Hermandad?
 Ahora eres un miembro de nuestra orden, y como tal, debes estar orgulloso de ser un miembro de la Hermandad del Acero.}
{151}{}{¿Orgulloso? ¿Por qué? Sois una panda de tíos robotizados que se esconde del mundo real. Yo no veo nada de que sentirme orgulloso.}
{152}{}{Lo siento. Algunas veces se me va la
 olla.}
{153}{}{Sí, vale.}
{154}{}{Bueno, creo que nos pasa a todos de vez en cuando.}
{155}{}{Bueno, ¿quién se encarga de este lugar?}
{156}{}{Sí. Bueno, tengo que irme.}
{157}{}{Maxson, el Anciano Mayor. Está en la cuarta planta.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Bueno, no estás mal... pero no estoy del todo segura. De todas maneras no creo que sea una buena idea liarme con alguien extraño.
 Eres guapo y algo atractivo. }
{164}{}{No sé si es por que eres extranjero o por tu extremada... ¿falta de tacto? Bueno, "cariño", ¿puedo hacer algo más por ti?}
{165}{}{Sí, uh, ya veo. Uh, ¿quién está al mando por aquí?}
{166}{}{Uh, vale... um. Bueno, ¿y qué tal algunas armas? ¿Cómo puedo hacerme con unas de ésas?}
{167}{}{¡Hmmph!}
{168}{}{No.}
{169}{}{Eso es... bastante gracioso. Estarás bromeando, ¿verdad? De hecho... prefiero que no contestes. No creo que quiera saberlo.}
{170}{}{Sí, MUY divertido. ¡Casi tanto como tu cara!}
{171}{}{Muchas gracias. Es exactamente lo que necesitaba oír ahora mismo.}
{172}{}{No soy de aquí.}
{173}{}{Lo siento. Es que tienes una forma muy extraña de hablar, extranjero. ¿Te puedo ayudar
 en algo?}
{174}{}{Bueno, creo que tendré que hablar con el tal Anciano Mayor.
 ¿Dónde está?}
{175}{}{Me gustaría conseguir mejores armas. ¿Con quién
 tengo que hablar?}
{176}{}{No.}
{177}{}{¿Estás de broma? ¡Nunca he oído mayor tontería en
 toda mi vida!}
{178}{}{¿Sí? Bueno, no salgo mucho. ¿Vale?}
{179}{}{Sal de mi vista, ¡viejo verde!}
{180}{}{¡Pfft!}
{181}{}{Bueno, vale, eres un miembro de la Hermandad, pero los Ancianos
 han participado en el entrenamiento de los nuevos Iniciados.}
{182}{}{¿Por qué?}
{183}{}{Oh, ¡eso es FANTÁSTICO! ¿Por qué demonios me unría a este estúpido
 grupo? ¡¿Dónde está la puerta?!}
{184}{}{Hay rumores sobre no sé qué de un ejército. Creo que los Ancianos quieren centrar sus esfuerzos en los que ya llevan bastante tiempo de entrenamiento, para que actúen en caso de una gran batalla.}
{185}{}{Estamos convencidos que entrenar muy bien a unos pocos luchadores es mucho mejor que entrenar mal a un montón de ellos. Salvar vidas es uno de nuestros objetivos principales.}
{186}{}{Puede que aprendas algo del entrenamiento sólo mirando.
 El Hermano Thomas es el mejor entrenador
 que jamás tuvimos en la Hermandad.}
{187}{}{Bueno, voy a tener que trabajar fuera de la Hermandad, ¿verdad? Es un mundo muy hostil y me arriesgaré el pellejo en todo momento.
 ¿No crees que debería entrenarme si me apetece o si lo necesito?
 ¿No seguís manteniendo que vuestro objetivo
 principal es "salvar" vidas?}
{188}{}{Gracias por la sugerencia, me lo pensaré.}
{189}{}{Estáis todos locos.}
{190}{}{¿Puedes decirme dónde está Maxson?}
{191}{}{Bueno, sólo estoy repitiendo lo que me han dicho. Si hablas con Thomas
 o Talus puede que ellos hagan una excepción.}
{192}{}{Vale, gracias.}
{193}{}{Eso espero porque ya os he sacado las castañas del fuego demasiadas veces.}
{194}{}{Bueno, ¿me puedes decir dónde está Maxson?}
{195}{}{Oh, cariño. ¿Cuándo vamos a casarnos?}
{196}{}{Como siempre, estás genial.}
{197}{}{Dame un beso.}
{198}{}{Te he echado mucho de menos.}
{199}{}{Te esperaré.}
{200}{}{He estado pensando en ti todo el día.}
{201}{}{Estás tan guapo cuando me miras así.}
{202}{}{Nunca más me asustes así. Pensé que nunca te volvería a ver.}
{203}{}{No viniste anoche.}
{204}{}{¿Cuánto tiempo ha pasado desde que te vi por última vez? Parece que ha pasado una eternidad.}
{205}{}{Nunca te he echado tanto de menos.}
{206}{}{Ven a la cama, cariño.}
{207}{}{Podemos casarnos por la mañana.}
{208}{}{Creo que deberíamos tener cinco hijos.}
{209}{}{¿Dónde quieres ir de luna de miel? Me he enterado de que los Niños de la Catedral viven en un bonito lugar.}
{210}{}{Mis padres todavía están esperando a conocerte.}
{211}{}{¿Por qué me saludas otra vez? Espero que las cosas te vayan bien y
 que hayas hablado con Vree.}
{212}{}{Hola, Hermano }
{213}{}{.}
{214}{}{Ten cuidado si vas al norte. Nuestros exploradores nunca han vuelto.}
{215}{}{Hermano }
{216}{}{, qué bueno verte de nuevo.}
{217}{}{¿Has hablado con Rhombus? Es el Caballero Jefe. Está justo ahí en esa sala.}
{218}{}{No tengo tiempo para hablar. Estoy ocupada.}
{219}{}{Lo siento, no estoy de humor para hablar con maleducados.}
{220}{}{No me molestes.}
{221}{}{¿Qué? ¿Por qué no vas a molestar a otra?}
{222}{}{Vete.}
{223}{}{No quiero hablar contigo.}
{224}{}{Iniciado, vuelve a tus deberes.}
{225}{}{No tengo tiempo para hablar, Iniciado.}
{226}{}{Ven aquí, ¡tonto!}
{227}{}{Querida, ¡por aquí!}
{228}{}{Te he echado de menos.}
{229}{}{Querida, ya tengo preparada la guardería.}
{230}{}{Hola cariño.}
{231}{}{Nos vemos.}
{232}{}{Tienes que conocer a mis padres.}
{233}{}{¡Yoo hoo!}
{234}{}{Ven aquí, cielito.}
{235}{}{¿Me estás tomando el pelo?}
{236}{}{Estás luchando con uñas y dientes, ¿verdad?}
{237}{}{¡Por aquí, corazón!}
{238}{}{¡Eh, cariño!}
{239}{}{Eso es. Estaba empezando a preocuparme.}
{240}{}{Acércate y dame un beso, guapetón.}
{241}{}{Acércate, querida.}