{100}{}{Estás viendo a Jeremiah, un mensajero de los Niños.}
{101}{}{Estás viendo a un Niño. Parece pensativo.}
{102}{}{Discúlpame, hermano. Me has asustado. ¿Cómo puedo servir al Maestro?}
{103}{}{¡Tonterías!}
{104}{}{¿Qué estás haciendo?}
{105}{}{Ah, sí, un Supermutante entrenándose. Volveré a mis deberes.}
{106}{}{Si no lo sabes, no es asunto tuyo. Si estás preguntando sobre algo que no deberías saber, tendré que informar a nuestros supervisores. Eso si que deberías saberlo.}
{107}{}{Soy una persona de gran importancia.}
{108}{}{Siento haberte molestado.}
{109}{}{Soy nuevo aquí.}
{110}{}{¡¿Quién demonios eres para hacerme preguntas a mí?! ¡¡Tienes suerte de que
 no te denuncie a la Llama sagrada!!}
{111}{}{Transfiriendo los informes.}
{112}{}{¿Informes de qué?, si se puede preguntar.}
{113}{}{Estás haciendo un buen trabajo.}
{114}{}{Eso es todo. Gracias.}
{115}{}{Muy bien. Que la paz esté contigo.}
{116}{}{Discúlpame. ¿Cómo puedo servir de ayuda?}
{117}{}{¿Qué haces?}
{118}{}{Puedes empezar contestando a mi pregunta.}
{119}{}{¡Muere!}
{120}{}{¡¡¡Guardias!!!}
{121}{}{Es obvio que no eres de aquí. ¿Quién eres?}
{122}{}{La verdad es que soy un Morador del Refugio y me gustaría hablar con el Maestro.}
{123}{}{Um... Morfeo... hmm... Morfeo me envió.}
{124}{}{Soy Loki. Un Iniciado del sur.}
{125}{}{No, no pertenezco a este lugar. Pero sé dónde encaja esta bala... en
 tu cabeza.}
{126}{}{Me encargo de llevar los informes sobre la pureza humana por estos alrededores. Pero eso ya deberías saberlo [Mirando con cara de sospecha.] ¿Quien eres?}
{127}{}{Morfeo me envió aquí con un mensaje para el Maestro.}
{128}{}{No es asunto tuyo quién soy... ¡sólo contesta a mis preguntas!}
{129}{}{No debes saber quién soy. Ése es el deseo del Maestro.}
{130}{}{¿Dudas de mi identidad? Idiota, debería liquidarte
 ahí mismo.}
{131}{}{Eso es bastante raro... Nunca he oído hablar de ti.}
{132}{}{Morfeo me envió con un mensaje para el Maestro.}
{133}{}{Soy de la Alta Orden. Sólo el Maestro y Morfeo conocen mi existencia
 para velar por mi seguridad en el exterior. Pero he sido llamado por
 orden del Maestro.}
{134}{}{Por favor, perdóname. Perdona que te haya interrogado. Por favor, sigue con tus asuntos y si te puedo ayudar en algo, házmelo saber.}
{135}{}{No sé quién eres y además, no eres de aquí. ¡¡¡Guardias!!!}
{136}{}{¿Quién eres y qué haces aquí abajo?}
{137}{}{Soy un adorador y estoy perdido.}
{138}{}{Morfeo me envió con un mensaje para el Maestro.}
{139}{}{Buscando un alma solitaria que enviar al cielo.}
{140}{}{¡Urk!}
{141}{}{No puedes estar aquí. Sólo los Servidores y superiores pueden estar aquí abajo. Vuelve a la Catedral ahora mismo.}
{142}{}{Discúlpame si te he creado problemas.}
{143}{}{¿Puedo hacerte algunas preguntas antes de irme?}
{144}{}{Vale, pero no antes de que te abra la cabeza.}
{145}{}{Morfeo no enviaría a un pardillo como tú a tal misión. ¡¡¡Guardias!!!}
{146}{}{¡Tú idiota! No puedes estar aquí. ¡Vuelve a la Catedral ahora mismo!}
{147}{}{Vale.}
{148}{}{Hunh.}
{149}{}{Nah.}
{150}{}{Me encargo de transmitir informes para el Maestro. Eso es todo lo que necesitas saber, hijo mío. Ahora debes irte.}
{151}{}{Me iré ahora.}
{152}{}{Sólo me gustaría hacerte algunas preguntas más.}
{153}{}{Me iré. Me iré. Pero no hasta que te haya volado la cabeza.}
{154}{}{¡¿Cómo has llegado hasta aquí?! ¿Qué haces metiendo las narices por ahí?}
{155}{}{Sólo quiero hacer algunas preguntas.}
{156}{}{No, no puedes hacerme preguntas. Ahora vete.}
{157}{}{¡Para! ¡No tienes porqué estar aquí! }
{158}{}{¿Duh?}
{159}{}{Lo siento. Estoy perdido. Me iré ahora.}
{160}{}{Pero sí tengo porqué estar aquí. Morfeo me envió en misión para el
 Maestro.}
{161}{}{Seguí a un tipo con aspecto sospechoso hasta aquí. ¿Lo habéis visto?}
{162}{}{No. Matar es mi negocio y el negocio es bueno.}
{163}{}{No he visto a nadie. ¿Cómo era?}
{164}{}{No importa. Creo que se fue.}
{165}{}{Era un hombrecillo bajito y verde.}
{166}{}{Era más o menos de tu estatura, pero llevaba una chaqueta de cuero... ¿Qué llevas debajo de esos ropajes?}
{167}{}{Se parecía a ti, ¡mierdas!}
{168}{}{Um... Yo... Yo... No te pensarás que soy yo... ¿yo? Qué ridículo.
 ¡Nunca!}
{169}{}{Vale. Entonces me iré, pero dime si ves algo...}
{170}{}{¡Sí! ¡Creo que eras tú! ¡Ve allí abajo y acaba con ellos!}
{171}{}{No, no creo que fueras tú, pero ¿puedo hacerte algunas preguntas?}
{172}{}{Sí, hermano. ¿En qué puedo ayudarte?}
{173}{}{Sí, hermana. ¿En qué puedo ayudarte?}
{174}{}{¿Qué haces aquí, hermano?}
{175}{}{Simplemente servir al Maestro. Eso es todo lo que pido, hermano.}
{176}{}{Lo siento, pero te has equivocado de tipo. Todos os parecéis mucho con esos ropajes.}
{177}{}{Puedes servirme muriendo, ¡bastardo de mierda!}
{178}{}{Me encargo de llevar los informes sobre la pureza humana por estos alrededores.}
{179}{}{Eso es todo. Gracias.}
{180}{}{Hermano, me gustaría hacerte algunas preguntas más.}
{181}{}{Sí, y es un trabajo muy importante. ¿Comprendes ahora la importancia de tus deberes para con el Maestro y todos nosotros?}
{182}{}{Porque sí. Soy el que le trae al Maestro informaciones sobre los humanos capturados todavía no contaminados por las radiaciones. También fui yo quien trajo al Maestro las últimas noticias sobre un Refugio posiblemente perdido. Puede que todavía haya humanos no contaminados dentro.}
{183}{}{Sí, hermano. Lo has comprendido. Gracias. Eso es todo.}
{184}{}{Me gustaría hacerte algunas otras preguntas.}
{185}{}{No reconocerías a un humano no contaminado aunque estuviera justo delante de tus narices. Idiota.}
{186}{}{No reconocerías a un humano no contaminado aunque estuviera justo delante de tus narices. Idiota.}
{187}{}{Actúas de un modo raro. No creo que seas quien dices ser. ¡Guardias!}
{188}{}{Haces demasiadas preguntas. No creo que seas quien dices ser. ¡Guardias!}
{189}{}{¡Eh! Te he dicho que no se te permite la entrada aquí abajo! ¡Guardias!}
{190}{}{Haces demasiadas preguntas. ¿Quién eres?}
{192}{}{Disculpa, hermana. Me has asustado. ¿Cómo puedo servir al Maestro?}
