{100}{}{Estás viendo a un viajero.}
{101}{}{¿Qué quieres, extranjero?}
{102}{}{¿Quién eres?}
{103}{}{¿Qué estás haciendo aquí?}
{104}{}{¿Dónde está la ciudad más cercana?}
{105}{}{Nada, gracias.}
{106}{}{Uhh...}
{107}{}{Soy un explorador.}
{108}{}{Estoy buscando a Piratas y a monstruos.}
{109}{}{Eso debe ser Ciudad Vertedero. No está lejos de aquí.}
{110}{}{Estás viendo a un guardia de Ciudad Vertedero.}

