{100}{}{Estás viendo el Tablón de Puestos de Trabajo.}
{101}{}{¡TRABAJO! ¿Necesitas un trabajo? ¿Necesitas chapas? ¡MIRA AQUÍ!}
{102}{}{Por favor no pongas mensajes por duplicado. -El Sheriff Greene-}
{103}{}{1      ¡Caravana desaparecida! ¡Recompensa!}
{104}{}{2      Se buscan guardianes de caravanas.}
{105}{}{8a}
{106}{}{8b}
{107}{}{8c}
{108}{}{8d}
{109}{}{9       Salida}
{110}{}{el      RECOMPENSA: CARAVANA DESAPARECIDA. Se recompensará con 500 chapas a quien sea capaz de capturar
 a los cabrones que están saqueando las caravanas. Para más detalles, consulte a Butch Harris, Comerciante de Ultramar, al noreste
 del Mercado de Mercaderes.}

