{100}{}{Estás viendo a Bob. Parece cansado.}
{101}{}{¡Por favor no me mates! ¡Te juro que conseguiré tus chapas!}
{102}{}{Duh-huh.}
{103}{}{Sí, será mejor que pagues.}
{104}{}{Creo que se equivocaron de habitación.}
{105}{}{¿De qué estás hablando?}
{106}{}{¡Ack! Debes ser Fred el Mudo, el despiadado Asesino de la Escoria. ¡Por favor no me mates!}
{107}{}{Aquí. Aquí. Toma esto. Es todo lo que tengo.}
{108}{}{¿Quieres decir que no estás aquí para matarme?}
{109}{}{No. Es tu día de suerte.}
{110}{}{No. ¿Quién te está amenazando?}
{111}{}{Gracias. Me puse algo nervioso al verte entrar aquí con una }
{112}{}{ en la mano.}
{113}{}{Gracias. Me puse algo nervioso al verte entrar aquí con una }
{114}{}{ en la mano.}
{115}{}{Caray, creí que venías del Casino. Les debo un montón de chapas.}
{116}{}{¿Por qué les debes tantas chapas?}
{117}{}{¿A quién del Casino le debes tantas chapas?}
{118}{}{¿Cuántas chapas les debes?}
{119}{}{Mmm. Gracias por la información.}
{120}{}{Hacen trampas. Jugué a las tragaperras y al póker. Pero soy mejor jugador que ellos. Te juro que esas máquinas están amañadas. Perdí un montón de chapas.}
{121}{}{¿A quién del Casino le debes tantas chapas?}
{122}{}{¿Cuántas chapas les debes?}
{123}{}{Mmm. Gracias por la información.}
{124}{}{A un par de tontos. Dicen que trabajan para el Jefe del Casino pero nunca le he visto. Uno se llamaba Izo, o algo así, y el otro era un tal
 Guido. Tramposos de mierda.}
{125}{}{¿Por qué les debes tantas chapas?}
{126}{}{¿Cuántas chapas les debes?}
{127}{}{Mmm. Gracias por la información.}
{128}{}{Oh, no demasiado. Un par de miles. Sólo jugué cuatro o cinco horas. Bueno, quizás un poco más. Me pusieron límites y, aún así, no tengo suficiente aquí para cubrirlo. Tengo que volver al Eje y conseguir algo de pasta. Me temo que intenten liquidarme si intento marcharme.}
{129}{}{¿Por qué les debes tantas chapas?}
{130}{}{¿A quién del Casino le debes las chapas?}
{131}{}{Mmm. Gracias por la información.}
{132}{}{Oh, eres tú otra vez. Pensé que lo habías hecho mejor que yo.}
{133}{}{Eh, ¿qué haces en mi habitación? ¿Eres del Casino?}
{134}{}{¡Hnnn!}
{135}{}{Sí, soy del Casino.}
{136}{}{No, sólo estoy echando un vistazo.}
{137}{}{¿Qué pasa con el Casino?}
{138}{}{Oh, ¡cielos!. Pensé que eras del Casino. Me has asustado.}
{139}{}{Oh, Vale. Adiós.}
{140}{}{¿Por qué?}
{141}{}{Bueno, me he metido en algún que otro lío. Les debo un montón de chapas.}
{142}{}{¿Por qué les debes tantas chapas?}
{143}{}{¿A quién del Casino le debes las chapas?}
{144}{}{¿Cuántas chapas les debes?}
{145}{}{Mmm. Gracias por la información.}
{146}{}{Oh, eres tú otra vez. Durante un momento me has asustado. No has visto a nadie del Casino por aquí, ¿verdad?}
{147}{}{¡Hnnn!}
{148}{}{No.}
{149}{}{Sí, claro que sí.}
{150}{}{Eh, tengo que hacerte algunas preguntas.}
{151}{}{Bien, bien. Sólo necesito un par de días más y les devolveré sus chapas y mucho más. Soy mejor jugador de lo que ellos creían.}
{152}{}{¡Ack! ¡Oh, Dios mío! ¡Estoy en un lío! Adiós.}
{153}{}{Vamos, dispara. Oh, elegiste mal las palabras, Bob. Elegiste mal las palabras.}
{154}{}{¿Por qué les debes tantas chapas?}
{155}{}{¿A quién del Casino le debes tantas chapas?}
{156}{}{¿Cuántas chapas les debes?}
{157}{}{Mmm. Gracias por la información.}
