{100}{}{Estás viendo a un campesino de Ciudad Vertedero.}
{101}{}{¡Sal de aquí!}
{102}{}{Nunca he oído nada bueno de ti. ¿No es así?}
{103}{}{Hola.}
{104}{}{Éste es nuestro lugar. ¿Quieres quedarte un tiempo?}
{105}{}{Mmm, mi postre...}
