{100}{}{El pistolero no te presta atención.}
{101}{}{El pistolero se burla de ti y pasa de largo.}
{102}{}{Estás viendo a un pistolero de aspecto siniestro.}
{103}{}{¡Gizmo os manda recuerdos!}
{104}{}{Consigues 400 puntos de experiencia por ayudar a Killian a luchar contra el asesino.}

