{100}{}{Estás viendo al Suplente Kenny.}
{101}{}{Si tienes asuntos con la policía del Eje, por favor habla con el Sheriff Greene. Yo sólo me ocupo de sus asuntos cuando el
 Sheriff no está.}
{102}{}{No puedo creer que el Sheriff esté muerto.}
{103}{}{Eso es. He estado esperando a que volvieras. Nos hemos enterado de que han asesinado al Sheriff durante una pelea.
 Es difícil creer que se ha ido de verdad. Era un padre para mí.}
{104}{}{El Sheriff me dio instrucciones para actuar en caso de que no volviese de la misión.
 Me pidió que te diera el resto de la recompensa. Creo que eran 1.000 chapas. [El Suplente te entrega 1.000 chapas.]}
{105}{}{Esta ciudad te da las gracias. Ojalá el Sheriff estuviera aquí para darte las gracias él mismo. Adiós.}
{106}{}{¡Oh Dios mío! ¡Ellos mataron a Kenny! ¡Esos bastardos!}

