{100}{}{Estás viendo una caja fuerte.}
{101}{}{La caja fuerte está abierta.}
{103}{}{¡Lo tienes!}
{104}{}{¡Huy! Casi lo logras.}
{105}{}{La caja fuerte está cerrada.}
{106}{}{Ganas 500 puntos de experiencia por acabar con el personal de seguridad de Killian.}
{107}{}{Mueves los botones de la caja fuerte y das con la combinación. Fantástico.}
