{100}{}{Caballero}
{101}{}{Me encanta trabajar en prototipos nuevos.}
{102}{}{Cuando se agotan nuestros suministros resulta difícil
 encontrar un modo de utilizar lo que tenemos.}
{103}{}{No logro averiguar por qué no funcionó mi último prototipo.}
{104}{}{Lo siento, no puedo hablar ahora.}
{105}{}{Vree está allí.}
{106}{}{¿Dónde he puesto ese archivo?}
{107}{}{¿Dónde está ese esquema?}
{108}{}{Bien, el ordenador dice que debería funcionar. ¿Qué he
 hecho mal?}
