{100}{}{Estás viendo a un enorme mutante.}
{101}{}{¡Alto! ¡No tienes escapatoria!}
{102}{}{No deberías estar aquí. Esta zona está fuera de la de los Niños.}
{103}{}{¿Por qué? ¿Qué lugar es éste?}
{104}{}{Tengo el control absoluto del salón. ¡Prueba mi arma!}
{105}{}{Unn.}
{106}{}{Eres demasiado estúpido para ser un Niño. Debes de ser un intruso.}
{107}{}{Es el bloque de celdas para prisioneros. Aquí guardamos a los humanos hasta 
 que los metemos en remojo. Está bien, ¿verdad?}
{108}{}{¿Qué es el remojo?}
{109}{}{Vale, gracias.}
{110}{}{Tienes que irte.}
