{100}{}{Has enfadado a Larry.}
{101}{}{Estás viendo a Larry.}
{102}{}{Si molestas al jefe, te dará una paliza.}
{103}{}{No se admiten humanos en Necrópolis. Ven conmigo.}
{104}{}{Pero...}
{105}{}{¡Nunca!}
{106}{}{¡¡Unnn!!}
{107}{}{¡Muere, humano!}
{108}{}{El mutante te ignora.}

{1000}{}{Agua}
{1001}{}{Necrópolis}
{1002}{}{Set}
{1003}{}{Almacén de Agua}
{1004}{}{Sala}
{1005}{}{Teni}
{1006}{}{Necrófagos}
{1007}{}{Normales}

{1100}{}{No lo sé}
{1101}{}{Estás ahí.}
{1102}{}{Es un impresentable. Nos mantenemos alejados de él y de sus necrófagos.}
{1103}{}{Es aquí.}
{1104}{}{No lo sé.}
{1105}{}{Es el jefe de Harry.}
{1106}{}{Debiluchos.}
{1107}{}{Más debiluchos que los necrófagos.}
