{100}{}{Estás viendo a Fustigador, pertenece a los Niños.}
{101}{}{Sé quién eres. Eres un hijo de satanás y debes ser castigado.}
{102}{}{Sé quién eres. Eres una mujer sádica y despiadada y debes ser castigada.}
{103}{}{Sé quien eres. Tu crueldad te delata. Envías las almas de los Niños al Hades, antes de que puedan eliminar su perfidia. Eres una bestia negra y debes ser castigado por ello.}
{104}{}{Sé quién eres. Eres un muerto viviente, una plaga en forma humana. Allí por donde pisas mana la sangre
 enormemente. ¡Pero esas barbaridades pueden llegar a término por un alma honrada!}
{105}{}{¿Cómo te atreves a molestarme? ¿No sabes lo importante que es mi posición? ¡Fuera!}
{106}{}{No eres demasiado inteligente al apuntarme. El Maestro me protege, ¡y no puedo ser tocado sin retribución!}
{107}{}{No me importaría gozar de la protección del Maestro.}
{108}{}{Nadie me ha acusado jamás de ser inteligente.}
{109}{}{Quiero hablar con el encargado.}
{110}{}{¡Esa vara es muy bonita! ¿Por eso es por lo que te llaman Fustigador?}
{111}{}{¿Es verdad que te gusta abusar de los niños?}
{112}{}{¿Quieres ser poco inteligente? Es poco inteligente molestarme, ¡zorra!}
{113}{}{¿Por qué hablas de ese modo tan raro?}
{114}{}{¿Cómo has entrado, iniciado? Ya sabes que no me gusta ser molestado.}
{115}{}{Perdóname, padre, pero estoy en problemas.}
{116}{}{Busco el camino a la Catedral.}
{117}{}{Estoy aquí para hablar sobre tu tratamiento de los Niños.}
{118}{}{Sólo quería hablar.}
{119}{}{¡Esa vara es muy bonita! ¿Por eso es por lo que te llaman Fustigador?}
{120}{}{¿Quieres que no se te vuelva a molestar? ¡Puedo solucionarlo!}
{121}{}{No lo sé. ¿Por qué he venido? ¿Lo sabes?}
{122}{}{¿Cómo te atreves a entrar a mi santuario con un arma en la Mano? ¡Fuera!}
{123}{}{¿Quién te crees que eres, entrando en mi santuario con un arma? ¡Fuera ahora mismo!}
{124}{}{Perdóname. Pero las fuerzas de la oscuridad están por todas partes y uno nunca sabe cuándo ha de defenderse.}
{125}{}{Busco el camino a la Catedral.}
{126}{}{Estoy aquí para hablar sobre tu tratamiento de los Niños.}
{127}{}{Sólo quería hablar.}
{128}{}{Este lugar no parece consagrado. Aún no he matado a nadie.}
{129}{}{No te gustan las armas. ¡Pues vas a odiar lo que hago ahora con ésta!}
{130}{}{¿A fuera? ¿A dónde de fuera?}
{131}{}{Mis residencias no están abiertas a aquellos que no han sido consagrados. Debo pedirte que te vayas de una vez.}
{132}{}{Perdona mi intrusión, pero tengo dudas importantes.}
{133}{}{Estoy aquí para hablar sobre tu tratamiento de los Niños.}
{134}{}{Quería preguntarte sobre la consagración.}
{135}{}{¡Esa vara es muy bonita! ¿Por eso es por lo que te llaman Fustigador?}
{136}{}{Este lugar no parece consagrado. Aún no he matado a nadie.}
{137}{}{¡Estúpido! Tengo mucha consa... gra... ción...}
{138}{}{Es un privilegio reservado sólo para los siervos más creyentes. Sólo el bautismo es un alto honor.}
{139}{}{¿Y cómo se merece uno el bautismo?}
{140}{}{Supongo que estás enseñando a los niños y preparándolos para el bautismo.}
{141}{}{¿Puedes ayudarme a bautizarme?}
{142}{}{¡Guau! ¡Debes ser especial!}
{143}{}{Esos malos privilegios no valen el culo de un Escorpión Rad cuando estás muerto.}
{144}{}{No veo razón para conversar con un imbécil. Vete de aquí.}
{145}{}{Deberías hablar con el Padre Morfeo. Está en la torre, pero es muy probable que los Nocturnos no te
 dejen pasar.}
{146}{}{¿Podrías convencer a los Nocturnos para que me dejaran pasar?}
{147}{}{¿Qué puedes contarme de Morfeo?}
{148}{}{¿Qué puedes contarme de los Nocturnos?}
{149}{}{Gracias, señor.}
{150}{}{Sé cómo acabar con este tipo de problemas.}
{151}{}{La vara es un instrumento sagrado con el que instruyo a mis subordinados. Aparta los pensamientos
 perversos y les permite comprender mejor la gloria del Maestro.}
{152}{}{Ya veo. ¿Así que el Maestro es un dolor?}
{153}{}{¡Hacerle eso a los niños es horrible!}
{154}{}{Suena raro. ¿Por qué no lo probamos conmigo?}
{155}{}{Instruyo a los niños. Es mi deber. Todos los niños son bestias en esencia. Es mi deber forzarlos
 a evolucionar a seres humanos. Quizás has oído que no soporto la frivolidad. Eso es cierto. Quiero mis
 cargas para sufrir tanto como sea posible.}
{156}{}{¿Y los mutantes están más desarrollados que los seres humanos?}
{157}{}{¡Bastardo sin corazón!}
{158}{}{Nunca te han vencido, ¿no?}
{159}{}{Cuéntame algo más de tus métodos didácticos.}
{160}{}{¿Qué ocurre con el placer de matar? ¿No se permite?}
{161}{}{¡Eres un esperpento sin corazón! ¿Cómo te atreves a aparecer ante mí? ¡Fuera! ¡Ahora!}
{162}{}{Eres una mujer, y por la tanto siempre estás en problemas. Es una condición endémica de tu género.
 Cuéntame tu problema, señorita, y te lo resolveré.}
{163}{}{Si tu corazón no estuviera tan lleno de maldad, estarías relajado. Un corazón honrado sabe
 preocuparse. Cuéntame tu problema, ¡pero rápido!}
{164}{}{¡Cuéntame cómo alcanzar la honradez!}
{165}{}{Quiero saber más de las Catedral.}
{166}{}{Quiero saber cosas del Maestro.}
{167}{}{Estás vivo; ese es mi problema, ¡hijo de puta!}
{168}{}{Aprende a aceptar el dolor como tu compañero más fiel, ya que el dolor es
 la fuerza más instructiva del universo. Castígate hasta que no puedas
 vivir como ente aislado, entonces intégrate en la maquinaria del Maestro.
 Es la solución a todos tus problemas.}
{169}{}{¿Dónde puedo encontrar el máximo dolor?}
{170}{}{Sí, quiero dañarme tanto el cerebro que voy a unirme a una secta de zombies. ¡Tu sueñas, colega!}
{171}{}{¡Nunca había pensado en eso!}
{172}{}{¿Sí? ¡Eso apesta, colega!}
{173}{}{Aún acepto el dolor. Me gusta compartirlo con mis amigos.}
{174}{}{Las Bestias hablan sin sentido. Los seres humanos piensan primero y luego hablan. Debes evolucionar
 a ser humano antes de que quiera hablar contigo. Vete.}
{175}{}{Tus palabras son ciertas. Vale, te ayudaré. Pero date prisa.}
{176}{}{Debo ver al Padre Morfeo por un asunto urgente.}
{177}{}{Háblame de la Catedral.}
{178}{}{Me pregunto dónde puedo encontrar al Maestro.}
{179}{}{Me inquietan los Niños.}
{180}{}{Lo único que sé es que la rapidez implica la muerte.}
{181}{}{Llega un momento en el que debes encontrar por ti mismo las respuestas a la vida, y ese momento ha llegado. ¡Ahora vete!}
{182}{}{Esa no es mi obligación. Ahora vete.}
{183}{}{Mediante la resistencia al dolor, la adquisición de la sabiduría y la prestación de servicio. El dolor
 es conocimiento; la sabiduría es obediencia y el servicio es valor. }
{184}{}{[Más]}
{185}{}{Debes rechazar la luz que casi nos destruye a todos y dedica tu persona a la Oscuridad en la que
 todos son iguales. Ahora que te he contado esto, ve y búscalo. Busca al Maestro y su sabiduría.}
{186}{}{No lo he consultado con él, pero estoy seguro de que le gustan las almas honradas que le he llevado.
 Es un trabajo difícil, pero lo hago bien. Por desgracia también se pierde mucho tiempo, por lo que
 debo ordenarte que te vayas.}
{187}{}{¡La boca del diablo alberga una lengua viperina! ¡Un demonio como tú! ¡Vete de aquí!}
{188}{}{¡Bestia bocazas! ¡Lárgate! Aprende modales antes de volver.}
{189}{}{Una solicitud razonable. Coge este símbolo. Enséñalo a los Nocturnos cuando quieras pasar.}
{190}{}{No puedo ayudarte con eso. Márchate.}
{191}{}{Es nuestro líder. Se acerca a los consejos del Maestro y conoce muchos de sus propósitos. ¿Eso es todo?}
{192}{}{¿Podrías convencer a los Nocturnos para que me dejaran pasar?}
{193}{}{Cuéntame algo más de Morfeo.}
{194}{}{¿Qué puedes contarme de los Nocturnos?}
{195}{}{Gracias, señor.}
{196}{}{¿Por qué te obsesionas con Morfeo?}
{197}{}{Sirven al Maestro. Llevan el dolor de la curación la mundo. Los Ángeles de la Noche, que redimen
 al mundo con el derramamiento de sangre. La curiosidad es un defecto sin sentido, pero no lo es tanto cuando procede de los Nocturnos.
 Es tu única advertencia. Tengo muchas cosas que hacer. Vete.}
{198}{}{Tu cortesía no es creíble. Quizás merece la pena hablar con Morfeo. Si los Nocturnos te paran,
 muéstrales este símbolo. ¡Ahora vete!}
{199}{}{Eres imbécil si crees que esos subterfugios ablandarán a los Nocturnos. ¡Ahora vete!}
{200}{}{La decadencia y la vagancia impiden la evolución que es necesaria para la supervivencia en un mundo duro.
 Por fortuna, soy un hombre duro que no se deja camelar por placeres sugerentes. Veo que discrepas.
 No me importa tu opinión. ¡Ahora largo de aquí!}
{201}{}{No hay que temer a la Mutación. Cada nacimiento es una mutación del ADN de nuestros padres. Todos somos mutantes. La
 única cosa que importa es que el mutante sea guiado por un camino moral y productivo. Este es mi camino. Y
 hemos terminado de hablar. Déjame en paz.}
{202}{}{Trabajo con el dolor. Si el animal es valioso y puede aprender de él, evoluciona a un alma honrada. Si
 no lo hace, no merece vivir. En contadas ocasiones, el animal es eliminado en la piscina genética,
 aunque no con la frecuencia deseada. Ocurre más a menudo con los animales engordados fallidos.}
{203}{}{¿Y el Maestro aprueba los métodos didácticos?}
{204}{}{¡Eres un monstruo!}
{205}{}{Pienso que te dejaré.}
{206}{}{¿Aleccionas a adultos?}
{207}{}{¿Animales engordados?}
{208}{}{Oye, no puedo librarte de ellos. ¡Nadie más ha de saberlo!}
{209}{}{Eres perversa. Harías bien si te andaras con cuidado. Los Nocturnos no agradecen la rivalidad.
 ¡Ahora vete!}
{210}{}{Eres perverso. Harías bien si te andaras con cuidado. Los Nocturnos no agradecen la rivalidad.
 ¡Ahora vete!}
{211}{}{La honradez se obtiene a base de lucha, fracaso y recuperación. Somos animales que deben ser
 continuamente derrotados hasta que aceptemos la verdad del Maestro sin dudar. Ahora que conoces
 la verdad, búscala en el interior de tus propias experiencias. Vete de aquí.}
{212}{}{Tu lengua te condena sin opción a redimirte. ¡Fuera de mi vista!}
{213}{}{La Catedral enseña muchas cosas que una mente indisciplinada es incapaz de comprender.
 Ahora tengo otros deberes que cumplir. ¡Vete!}
{214}{}{Como yo. Parece que tenemos muchas cosas en común, pero desgraciadamente superas los límites
 de mi enorme paciencia. Vete de aquí. Ahora.}
{215}{}{No me corresponde juzgar. Debes convencer a los Nocturnos. Buena suerte. La necesitarás.}
{216}{}{La Catedral es un santuario para la raza humana. Cuando el Apocalipsis llegó a esta ciudad de cretinos,
 la Catedral sobrevivió, lo que permitió el nacimiento del Maestro. Pero la oscuridad sanadora nació de
 una luz terrible.}
{217}{}{ Cuando llegué, este lugar carecía de un centro moral, y por ello he procurado imponer la enseñanza del
 dolor en un lugar que estuvo consumido por el lujurioso placer. Eso es todo lo que necesitas saber.}
{218}{}{Se dice que el Maestro espera abajo, en la Oscuridad, ya que la Luz de arriba traicionó a la Humanidad y casi
 nos destruye. Pero hay muchos que bendicen la luz, ya que bautizó al Maestro.}
{219}{}{ No conozco esas cosas con certeza y nunca he tenido la fortuna de verlo. Ahora
 si me disculpas tengo cosas que hacer.}
{220}{}{No eras muy bien acogido aquí antes. Ya era hora.}
{221}{}{Una vez sí, pero muchos métodos se abandonaron a favor de los graves ruidos que oyes en el
 anfiteatro del Auditorio. Es una fuente de crueldad para mí. Por suerte, aún puedo aleccionar a los
 niños. Ahora si me permites, tengo que preparar sus clases.}
{222}{}{Oh... por supuesto es un fenómeno extraño, y el animal ha tenido la oportunidad de evolucionar. ¡Ahora vete de aquí!
 ¡Vete de una vez!}
{223}{}{[Hecho]}
{224}{}{Esto puede serte de utilidad. Coge este símbolo. Enséñalo a los Nocturnos cuando quieras pasar. Te
 permitirá ver al Padre Morfeo.}