{100}{}{Estás viendo a Laura.}
{102}{laura0m}{Hola, hermano. ¿Te puedo ayudar en este glorioso día?}
{104}{laura0f}{Hola, hermana. ¿Te puedo ayudar en este glorioso día?}
{105}{}{¿Eres Laura?}
{106}{}{¿Puedo hacerte unas preguntas sobre los Niños?}
{107}{}{¿Qué tipo de "ayuda" ofreces?}
{108}{}{¿Mamá?}
{110}{laura01a}{Eso es muy dulce de tu parte, pero no, no soy yo.
 Seguro que la puedes encontrar en alguna otra parte.}
{112}{laura2}{Soy yo, sin duda. ¿Querías algo?}
{113}{}{Nicole me envió para hablar contigo.}
{114}{}{Eh... no. Da lo mismo.}
{116}{laura3}{¿Nicole? Lo siento. Creo que no conozco a nadie con ese nombre.}
{117}{}{Bueno, ella me dijo que te dijese "Jinete Rojo".}
{118}{}{¡Claro que la conoces! ¡Ella me envió!}
{120}{laura4}{Lo siento. Yo... yo no lo sé.
 Sígueme, vamos a un sitio donde podamos hablar.}
{122}{laura9}{Perdóname por los inconvenientes. Espero que no te moleste demasiado.}
{124}{laura10}{¿Estás... seguro? Eh... disculpa mi curiosidad
 pero parecía que me buscabas específicamente a mí.}
{125}{}{Bueno, Nicole me envió.}
{126}{}{Había oído hablar de ti y quería saber cómo eras.}
{128}{laura11}{Lo... lo siento pero ese tipo de detalles
 me pone un poco nerviosa. No sé por qué,
 es una tontería, lo sé. En fin, disfruta de tu paseo.}
{130}{laura14}{Oh, yo no tengo mucha autoridad. Deberías ver a Morfeo,
 el Sumo Sacerdote. Estoy segura de que él te ayudará mejor que yo.}
{132}{laura15}{Yo sólo quería decir... oh... tengo que irme.}
{134}{laura16g}{¡Vaya, hola de nuevo! ¿Sólo paseabas o puedo ayudarte en algo?}
{136}{laura16b}{¿Hay algo en lo que pueda ayudarte?}
{137}{}{¿Eres Laura?}
{138}{}{¿Puedo hacerte unas preguntas sobre los Niños?}
{139}{}{No, gracias.}
{140}{}{¿Mamá?}
{142}{laura16a}{No. Ya hemos hablado de esto. Tendrás que buscar en
 otro sitio, amigo.}
{144}{laura21}{Oh... Me alegro de que me hayas encontrado. Nicole
 me envió una lista con la información que tenía que recoger.}
{145}{}{¿Qué conseguiste?}
{147}{laura22}{Esto... hay tanto que... no estoy segura de lo que
 necesitas o de por dónde empezar. ¿Hay algo en especial
 que quieras saber?}
{148}{}{¿Hay una entrada secreta al Santa Sanctórum de la Iglesia?}
{149}{}{¿Qué has aprendido sobre el Maestro?}
{150}{}{¿Qué planes tienen los Niños?}
{151}{}{¿Qué hace una chica como tú en un sitio como este?}
{152}{}{Nada más, gracias.}
{154}{laura24}{No es en el Santa Sanctórum donde has de entrar.}
{155}{}{¿Entonces en dónde?}
{157}{laura25}{Seguí a Morfeo por una escalera secreta trasera.
 Le vi activar una puerta secreta en la parte de abajo.}
{158}{}{¿Y después qué?}
{159}{}{¿Me puedes mostrar esta puerta?}
{161}{laura26}{Usa una extraña llave para abrirla y desaparece.
 Nunca he intentado seguirle.}
{162}{}{¿Sabes dónde está esa llave?}
{163}{}{¿Por qué no?}
{165}{laura27}{Diría que la lleva encima.}
{166}{}{¿Me enseñarías la puerta ahora?}
{168}{laura28a}{Por supuesto.}
{169}{}{Genial. Vamos.}
{170}{}{¿Puedo hacerte algunas preguntas antes?}
{172}{laura29}{Sígueme.}
{174}{laura30a}{Vale, pero nos tenemos que dar prisa.}
{176}{laura30b}{Oh, que sea rápido.}
{178}{laura31}{Créeme, si hubieses visto a los Nocturnos
 lo comprenderías. A no ser que seas estúpido.}
{179}{}{Quizá lo sea, pero no tengo miedo.}
{180}{}{Eso puedo entenderlo. ¿Podemos volver a las preguntas?}
{182}{laura32}{Oh, muy gracioso. Mira, estoy en medio
 de un problema. Si no
 crees que lo hago bien, guárdatelo
 para ti. ¿Te enteras?}
{183}{}{¿Qué vas a hacer, seguir quejándote?}
{184}{}{Si así lo quieres.}
{185}{}{Tienes razón, lo siento. ¿Que tal si volvemos a lo nuestro?}
{187}{laura33}{Uh, no mucho. Los Niños le veneran y a veces una
 inmensa visión suya aparece en la nave principal de la iglesia.}
{188}{}{¿Así que es real?}
{189}{}{Da miedo.}
{191}{laura34}{Sí y no, un día me coloqué delante
 y encontré un extraño mecanismo con una lente bajo el altar.}
{192}{}{Probablemente una especie de proyector holográfico.}
{193}{}{¿Y?}
{195}{laura35}{Oh... al principio, claro que lo era, pero entonces
 me colé y observé el altar cuando nadie miraba.
 Y resulta que debajo hay un mecanismo con
 cables y una gran lente.}
{196}{}{Probablemente una especie de proyector holográfico.}
{197}{}{¿Y?}
{199}{laura36}{Y estoy segura de que este Maestro es de carne y hueso.
 Y también creo saber dónde se encuentra.}
{200}{}{¿Dónde?}
{202}{laura37}{De vez en cuando, Morfeo baja por una escalera
 secreta que conduce a la cripta de la Iglesia. Y entra
 por una puerta secreta con una especie de llave. Creo
 que el Maestro está allí abajo.}
{203}{}{¿Puedes enseñarme esa escalera ahora mismo?}
{204}{}{¿Sabes dónde está esa llave?}
{206}{laura38}{Ahora es peligroso. Morfeo predica que la tierra
 debe ser "purgada de los infieles", y cosas por el
 estilo. ¡Creo que están planeando
 hacerse con todo!}
{207}{}{¿Lo pueden hacer?}
{208}{}{¿Cual es su primer objetivo?}
{210}{laura39}{Sabes, podría ser. Bueno, tienen miembros
 suficientes y los distintos hospitales
 en las ciudades están repletos de armas y explosivos.}
{211}{}{Debemos contárselo a los Seguidores.}
{212}{}{¿Qué vas a hacer?}
{214}{laura40}{Lo estaba planeando. De hecho, cuando acabemos esto me iré a dar una vuelta por allí.}
{215}{}{¿Una pregunta rápida?}
{216}{}{Entonces te dejo ir.}
{218}{laura41}{Está bien. ¡Buena suerte!}
{220}{laura42}{Vale, voy a avisar a Nicole.
 Y, con un poco de suerte, los Seguidores pueden mandar ayuda a las otras ciudades.}
{221}{}{Primero me gustaría hacerte algunas preguntas.}
{222}{}{Entonces te dejaré ir.}
{224}{laura43}{Adytum, esa ciudad no tiene una maldita oportunidad.}
{225}{}{¿Qué hay de los Seguidores?}
{226}{}{¿Puedo ayudar Adytum?}
{228}{laura44}{Los Niños no creen que seamos una amenaza.
 Se lo demostraremos.}
{229}{}{Bien. ¿Qué piensas hacer?}
{230}{}{¿Puedo ayudar Adytum, como sea?}
{232}{laura45}{Sí, puedes ayudarles llegando al Maestro. Como decía
 mi abuela, "muerto el perro se acabó la rabia".
 Era muy práctica.}
{233}{}{¿Cómo llego hasta él?}
{234}{}{Lo parece. Necesito más respuesta antes de que te vayas.}
{235}{}{Estoy de camino.}
{237}{laura46}{¡Planean apoderarse de todas las ciudades!}
{238}{}{¿De cuáles?}
{240}{laura47}{Adytum ya ha caído. El Eje es la próxima.}
{241}{}{¿Qué hacen los Seguidores mientras tanto?}
{242}{}{Maldita sea. ¿Qué puedo hacer yo?}
{244}{laura48}{Mandamos un grupo para ayudar en Adytum,
 y todos fueron eliminados. Nicole ha enviado a otro al
 Eje. Espero que lleguen a tiempo.}
{245}{}{Maldita sea. ¿Qué puedo hacer yo?}
{247}{laura49}{¡Ya han tomado el Eje y Adytum!
 Creo que los próximos son los Seguidores, así que preparamos nuestra defensa.}
{248}{}{¿Entonces, por qué estás aquí?}
{249}{}{¿Qué puedo hacer?}
{251}{laura50}{Estoy aquí para vigilar a los Niños.}
{252}{}{¿Qué puedo hacer?}
{254}{laura51}{Los Niños están montando hospitales por todas partes.
 Bah. Creo que están intentando ganarse la confianza de la gente.}
{255}{}{¿Y funciona?}
{256}{}{¿Hay algún modo de pararles los pies?}
{257}{}{¡Eso es lo más estúpido que he oído nunca!}
{259}{laura52}{Ah, desde luego lo parece. O sea, la gente se arremolina ante
 su Iglesia. ¿No se dan cuenta de que es una farsa?}
{260}{}{¿Estás segura de que lo es?}
{261}{}{¿Cómo puedo pararles los pies?}
{263}{laura53}{Por una razón, parece que la gente desaparece
 por aquí, mientras que el número de Nocturnos crece lentamente.}
{264}{}{¿Por qué?}
{265}{}{No tiene buena pinta. Pero necesito más respuestas antes de actuar.}
{267}{laura54}{No lo sé. Eso es lo que has venido a averiguar, ¿no?}
{269}{laura55}{¡Encuentra al Maestro y deténle!}
{270}{}{¿Qué has averiguado acerca del Maestro?}
{271}{}{Lo haré.}
{273}{laura56}{Sí, demonios, eso espero. ¿Alguna pregunta más?}
{275}{laura57}{La verdad es que es una buena manera de manipular a la gente,
 y el Maestro este sabe cómo hacerlo.}
{276}{}{No, quiero decir que es la cosa más tonta que te he oído decir.
 Estás paranoica, ¿verdad?}
{277}{}{Bueno, le dentedré.}
{278}{}{¿Cómo puedo detener esto?}
{280}{laura58}{¿Perdón?}
{281}{}{Ya me has oído.}
{282}{}{No importa.}
{284}{laura59}{Vale entonces. ¡Buena suerte!}
{286}{laura60}{Uh, eh... Estaba esperando que
 alguien me soltase ese rollo patético.}
{288}{laura61a}{¿Qué puedo hacer por ti ahora?}
{290}{laura61b}{¿Qué pasa ahora?}
{291}{}{Necesito hacerte algunas preguntas más.}
{292}{}{Nada, gracias.}
{294}{laura62}{¿Qué haces? ¡Baja eso!}
{296}{laura63}{¡Oye! ¡Fuera de aquí!}
{297}{}{¿Y si no, qué?}
{298}{}{Lo siento, me voy.}
{300}{laura64}{¡Para!}
{302}{laura65}{¿Qué... qué estás haciendo aquí? ¡Tienes que irte!}
{303}{}{¡No, tú te vas!}
{304}{}{Vale, me iré.}
{306}{laura67}{Eh... No estoy segura de eso. Ve a hablar con Nicole.}
{308}{laura67a}{No estoy segura de eso. Ve a hablar con un Sumo Sacerdote.}
{309}{}{Bueno, como dije...}
{310}{}{He dicho...}
{311}{}{Bueno, como dije antes...}
{312}{}{Como dije antes...}
{313}{}{Estoy casi segura de que ya te lo he dicho, pero...}
{314}{}{¡Vale! Ya te lo he dicho...}
{315}{}{¿Ah, otra vez? Bueno, te dije...}
{316}{}{¿Otra vez? Ya te he dicho esto...}
{317}{}{Oh Dios, eres un plasta. No pienso decírtelo otra vez.}
{318}{}{¿Estás...? ¡Vale! ¡Vale! ¿Estás sordo?
 Lee mis labios. No te lo repetiré.}
{319}{}{Creo que ya es suficiente. No lo voy a repetir.}
{320}{}{No escuchas, ¿eh? Peor para ti, no pienso repetirlo.}
{321}{}{Oh, esa horrible gente. ¡No pienso hablar de ellos!}
{322}{}{Nicole te debió hablar de nosotros.
 Estamos intentando hacer entrar en razón a esos
 descerebrados pistoleros, traficantes de violencia...
 Oh, mejorando lo presente, por supuesto.}
{323}{}{No sé de lo que estás hablando.}
{324}{}{Encabeza a los Seguidores. Muy voluntariosa. Me fío de ella.}
{325}{}{¡Los otros son todos tan buenos! Aquí todo es maravilloso.
 Esta es nuestra tierra, trabajamos por ella...}
{326}{}{Oh, son como una... plaga en el mundo. La mayoría
 son un desperdicio y unos pocos son simplemente perversos.}
{327}{}{¿Adytum no está al oeste de aquí?}
{328}{}{Adytum está al oeste de aquí. Y la gente de allí...
 bueno, está un poco paranoica, así que
 no esperes una calurosa bienvenida.}
{329}{}{Oh, es maravilloso. Él es nuestro líder. ¡Deberías hablar con él!}
{330}{}{Predica la paz, la espiritualidad y esas chorradas,
 pero es escoria. Lo mires por donde lo mires. No hay que darle más vueltas.}
{331}{}{Oh, no sé siquiera como empezar a describirle. Morfeo es nuestro líder.
 No hay palabras para ello.}
{332}{}{Ah sí, el Maestro, es el dios que veneran estos idiotas. Personalmente no creo
 que sea un dios, sino alguien que sabe manipular a los demás.}
{333}{}{¿Nocturnos? No sé de lo que hablas.}
{334}{}{Son grandes y feos esbirros del Maestro
 y de Morfeo.}
{335}{}{¿El qué?}
{336}{}{¿No has caído en que es el Maestro?}
{337}{}{Es el sitio grande al final, en el norte de la Iglesia,
 donde Morfeo celebra sus ceremonias. He estado allí,
 es maravilloso.}
{338}{}{Está al final, en la parte norte de la Iglesia.
 He visto a Morfeo hacer su numerito de circo allí.}
{339}{}{Oh, no puedes ir allí. Es donde Morfeo medita.}
{340}{}{Es donde Morfeo y sus compinches suelen ir.
 No dejan entrar a nadie.}
{341}{}{Se han entregado a la Iglesia. El resto de nosotros aspira a hacer lo mismo.}
{342}{}{Oh si, estos tipos han sobrevivido a la tortura y quién sabe a qué
 más. Les han lavado el cerebro completamente y harán
 todo lo que se les ordene.}
{343}{}{Son los sumos sacerdotes.}
{344}{}{Ah, esos son los sumos sacerdotes. Creo que sólo hay 13, pero no estoy completamente segura.}
{345}{}{Eso no es importante.}
{346}{}{Eso no es importante.}
{347}{}{Lo siento. No tengo tiempo para esto.}
{348}{}{¡No tenemos tiempo para hablar de eso! Cíñete al tema.}
{349}{}{No tengo claro por qué quieres hablar de eso.}
{350}{}{No te vayas por las ramas, amigo.}




#
# Laura Tell-Me-Abouts
#


{1000}{}{Seguidores}
{1001}{}{Nicole}
{1002}{}{Catedral}
{1003}{}{Morfeo}
{1004}{}{Maestro}
{1005}{}{Nocturnos}
{1006}{}{Dios}
{1007}{}{Auditorio}
{1008}{}{Sánctum}
{1009}{}{Servidores}
{1010}{}{Orden}
{1011}{}{Apocalipsis}
{1012}{}{Oscuro}
{1013}{}{Mutantes}

{1100}{laura74}{Oh, esa horrible gente. ¡No pienso hablar de ellos!}
{1101}{laura75}{No sé de quien estás hablando.}
{1102}{laura76a}{¡Los otros son todos tan buenos! Aquí todo es maravilloso.
 Esta es nuestra tierra, trabajamos por ella...}
{1103}{laura78}{Oh, es maravilloso. Él es nuestro líder. ¡Deberías hablar con él!}
{1104}{laura79}{Oh, no sé siquiera como empezar a describirle. Morfeo es nuestro líder.
 No hay palabras para ello.}
{1105}{laura80}{¿Nocturnos? No sé de que hablas.}
{1106}{laura81}{¿Qué?}
{1107}{laura82}{Es el sitio grande al final de la Iglesia, donde Morfeo
 celebra sus ceremonias. He estado allí, es maravilloso!}
{1108}{laura83}{Oh, no puedes ir allí. ¡Es donde Morfeo medita!}
{1109}{laura84}{Se han entregado a la Iglesia. El resto de nosotros aspira a hacer lo mismo.}
{1110}{laura85}{Son sumos sacerdotes.}
{1111}{laura74}{Oh, esa horrible gente. ¡No pienso hablar de ellos.}
{1112}{laura81}{¿El qué?}
{1113}{laura80}{¿Nocturnos? No sé de que hablas.}