{100}{}{Estás viendo a Lorenzo.}
{101}{}{Señor, éste es un establecimiento respetable. No tratamos con personas como tú. Vete.}
{102}{}{Señora, éste es un establecimiento respetable. No tratamos con personas como tú. Vete.}
{103}{}{Has sobrepasado tu crédito. Por favor, paga ahora o me enfadaré. No me gusta enfadarme.}
{104}{}{No me amenaces. No eres el único que tienes amigos.}
{105}{}{Necesito más tiempo. ¡Por favor!}
{106}{}{Quiero liquidar mi deuda de }
{107}{}{ chapas.}
{108}{}{No las llevo encima.}
{109}{}{Hola. Así que has venido a saldar tu deuda, ¿eh?}
{110}{}{Realmente esperaba que me pudieras proporcionar información...}
{111}{}{Vengo a por otro préstamo.}
{112}{}{Quizás después.}
{113}{}{¿Qué?}
{114}{}{Te avisé que nunca volvieras. Vale, chicos, ¡ya sabéis lo que tenéis que hacer!}
{115}{}{¡Que me aspen si no es un cliente potencial! Soy Lorenzo el Magnífico, a tu servicio. Doy créditos.
 Sólo un interés diario de un diez por ciento y un máximo de diez días para la devolución. ¡No encontrarás
 una mejor casa de préstamos en todo el Eje!}
{116}{}{Vengo a por un préstamo.}
{117}{}{¡Me pareces un chupóptero!}
{118}{}{Sí, supongo. ¿Qué es lo que necesitas saber?}
{119}{}{¿Y esas caravanas desaparecidas?}
{120}{}{Háblame de Decker.}
{121}{}{¿Y la policía local?}
{122}{}{¿Qué ocurre con los Niños de la Catedral?}
{123}{}{Háblame de ti.}
{124}{}{¿Dónde se puede encontrar trabajo por aquí?}
{125}{}{Lo siento. No me gusta cotillear. No vuelvas a preguntarme.}
{126}{}{Ya te he dicho que no cotilleo. Si piensas que hablaba por hablar,
 te equivocas. Vete y no vuelvas, so imbécil.}
{127}{}{Lo siento, colega, pero no hago más de un préstamo a la vez. Si quieres más, primero págame. Esto
 es un negocio, no una obra benéfica.}
{128}{}{Vale. Ha sido un placer tratar contigo. ¿Algo más?}
{129}{}{¡Idiota! No tienes bastantes chapas para saldar tu deuda. Quizás pensabas en otra cosa...}
{130}{}{Realmente esperaba que me pudieras proporcionar información...}
{131}{}{Vengo a por otro préstamo.}
{132}{}{Quizás después.}
{133}{}{¡Claro! Eres libre de hacerlo. Siempre estamos encantados de ayudar.}
{134}{}{Piérdete y molesta al personal en otro lado. ¡Lárgate de una vez! Y no vuelvas.}
{135}{}{Oye, ¡sin amenazas! Somos personas civilizadas. Guido, Leone, ¿por qué no le enseñáis a este señor
 lo civilizados que somos?}
{136}{}{Oye, ¡sin amenazas! Somos personas civilizadas. Guido, Leone, ¿por qué no le enseñáis a esta señorita
 lo civilizados que somos?}
{137}{}{Se te acabó el tiempo. Guido, Leone, entretenedme un minuto...}
{138}{}{Tienes suerte, amigo.}
{139}{}{En realidad esperaba que me pudieras proporcionar información...}
{140}{}{Vengo a por otro préstamo.}
{141}{}{Quizás después.}
{142}{}{¿No has tenido suficiente? ¿Cómo te atreves a molestarme? Guido, Leone, cargaros a este perdedor.}
{143}{}{Vale. No tienes deudas pendientes con nosotros. Dejamos unidades de doscientas
 chapas, con un máximo de mil chapas. Pero recuerda, no te haré un préstamo importante
 hasta que me demuestres que puedes reembolsar uno menor.}
{144}{}{Quisiera }
{145}{}{1000}
{146}{}{800}
{147}{}{600}
{148}{}{400}
{149}{}{200}
{150}{}{ chapas.}
{151}{}{Debería pasar del crédito.}
{152}{}{Guido, Leone, enseñadle lo que significa un timo de verdad. Comenzad con los brazos.}
{153}{}{Lo siento, colega, pero es demasiado peligroso prestarle chapas a un idiota. Lárgate ya.}
{154}{}{¡La Garra Mortal! Ha de ser la Garra Mortal. ¡Nadie está seguro!}
{155}{}{¿Y la Garra Mortal?}
{156}{}{Háblame de Decker.}
{157}{}{¿Y la policía local?}
{158}{}{¿Qué ocurre con los Niños de la Catedral?}
{159}{}{Háblame de ti.}
{160}{}{¿Dónde se puede encontrar trabajo por aquí?}
{161}{}{Es un buen tipo. Un buen tipo de trabajos para saldar mis préstamos. Dile que vas de mi parte, ¡puedes conseguir un extra!}
{162}{}{¿Y esas caravanas desaparecidas?}
{163}{}{¿Extra? ¿Qué quieres decir?}
{164}{}{¿Y la policía local?}
{165}{}{¿Qué ocurre con los Niños de la Catedral?}
{166}{}{Háblame de ti.}
{167}{}{¿Dónde se puede encontrar trabajo por aquí?}
{168}{}{¡Son fantásticos! Es verdad que hemos tenido algunos malentendidos, pero creo que les hacen honor a su especie... [Con la voz baja]... cualquiera que sea...}
{169}{}{¿Y esas caravanas desaparecidas?}
{170}{}{Háblame de Decker.}
{171}{}{¿Malentendidos? ¿Cómo qué?}
{172}{}{¿Qué ocurre con los Niños de la Catedral?}
{173}{}{Háblame de ti.}
{174}{}{¿Dónde se puede encontrar trabajo por aquí?}
{175}{}{No puedo decir que esté muy impresionado. Llevo un negocio honesto y respetable y me acusan de ser un
 ladrón. ¡Qué cara tiene esa gente! ¡Se piensan que su voto de pobreza les da derecho a juzgarme!}
{176}{}{¿Y esas caravanas desaparecidas?}
{177}{}{Háblame de Decker.}
{178}{}{¿Y la policía local?}
{179}{}{¿Voto de pobreza?}
{180}{}{Háblame de ti.}
{181}{}{¿Dónde se puede encontrar trabajo por aquí?}
{182}{}{Sólo soy un hombre de negocios respetable y nada más. Los Giovanni hemos sido respetables hombres de negocios desde
 los días del holocausto... ¡Ahora es una tradición!}
{183}{}{¿Y esas caravanas desparecidas?}
{184}{}{Háblame de Decker.}
{185}{}{¿Y la policía local?}
{186}{}{¿Qué ocurre con los Niños de la Catedral?}
{187}{}{¿Cuál es tu idea de respetable?}
{188}{}{¿Dónde se puede encontrar trabajo por aquí?}
{189}{}{Deberías intentarlo con el Sr. Decker. ¡Un trabajo excitante y muchas chapas! ¡Lo mejor de la ciudad! ¡Y está cruzando la
 calle! ¡No encontrarás nada mejor!}
{190}{}{¿Y esas caravanas desaparecidas?}
{191}{}{Háblame de Decker.}
{192}{}{¿Y la policía local?}
{193}{}{¿Qué ocurre con los Niños de la Catedral?}
{194}{}{Háblame de ti.}
{195}{}{¿Qué tipo de animación?}
{196}{}{Olvídalo, eres demasiado grande para fiarte. Vete de mi vista y no vuelvas.}
{197}{}{Vale. Mil chapas. Tienes 10 días para devolverlas.}
{198}{}{Vale. Ochocientas chapas. Tienes 10 días para devolverlas.}
{199}{}{Vale. Seiscientas chapas. Tienes 10 días para devolverlas.}
{200}{}{Vale. Cuatrocientas chapas. Tienes 10 días para devolverlas.}
{201}{}{Vale. Doscientas chapas. Tienes 10 días para devolverlas.}
{202}{}{¡Qué pena! Eres libre de contratarnos más adelante.}
{203}{}{Tío, algunas de las historias que cuentan sobre eso son sólo... bien, ¡son algo!}
{204}{}{Háblame de Decker.}
{205}{}{¿Y la policía local?}
{206}{}{¿Qué ocurre con los Niños de la Catedral?}
{207}{}{Háblame de ti.}
{208}{}{¿Dónde se puede encontrar trabajo por aquí?}
{209}{}{Bien, ¡adiós!}
{210}{}{Bueno, quizás no sea de gran ayuda pero es un buen tipo, ¡confía en mí!}
{211}{}{¿Y esas caravanas desaparecidas?}
{212}{}{¿Y la policía local?}
{213}{}{¿Qué ocurre con los Niños de la Catedral?}
{214}{}{Háblame de ti.}
{215}{}{¿Dónde se puede encontrar trabajo por aquí?}
{216}{}{Bien, ¡adiós!}
{217}{}{¿Te puedes creer que alguien me haya acusado de extorsión? ¡Por suerte, mi buen amigo Decker acabó con ellos!}
{218}{}{¿Y esas caravanas desaparecidas?}
{219}{}{Háblame de Decker.}
{220}{}{¿Qué ocurre con los Niños de la Catedral?}
{221}{}{Háblame de ti.}
{222}{}{¿Dónde se puede encontrar trabajo por aquí?}
{223}{}{Bien, ¡adiós!}
{224}{}{Juraría que su Líder, ese tipo, Morfeo, no está muerto. ¡No, señor! Apostaría a que abajo en el
 Cementerio está haciendo su vida.}
{225}{}{¿Y esas caravanas desaparecidas?}
{226}{}{Háblame de Decker.}
{227}{}{¿Y la policía local?}
{228}{}{Háblame de ti.}
{229}{}{¿Dónde se puede encontrar trabajo por aquí?}
{230}{}{Bien, ¡adiós!}
{231}{}{Si no nos respetas, acabarás herido. ¿Cuánto respeto puede exigir un hombre?}
{232}{}{¿Y esas caravanas desaparecidas?}
{233}{}{Háblame de Decker.}
{234}{}{¿Y la policía local?}
{235}{}{¿Qué ocurre con los Niños de la Catedral?}
{236}{}{¿Dónde se puede encontrar trabajo por aquí?}
{237}{}{Bien, ¡adiós!}
{238}{}{La aventura es peligrosa. ¡Puede acabar en baño de sangre!}
{239}{}{¿Y esas caravanas desaparecidas?}
{240}{}{Háblame de Decker.}
{241}{}{¿Y la policía local?}
{242}{}{¿Qué ocurre con los Niños de la Catedral?}
{243}{}{Háblame de ti.}
{244}{}{Bien, adiós.}
{245}{}{¡Nos veremos, colega!}
{246}{}{Oye, oye.. ¡quita las manos de esa puerta, monstruo!}
{247}{}{Eso es, ¡monstruo! ¡Pagarás por eso!}
{248}{}{Lo siento, pero no tengo tiempo para eso. Si no puedes pagarlo todo, dame las chapas
 que tengas y nuestra relación comercial habrá terminado para siempre.}
{249}{}{Bien, vale. Puedes quedarte con todas mis chapas.}
{250}{}{¡Oh! Acabo de acordarme. ¡Tengo lo justo para saldar toda la deuda!}
{251}{}{[Intentas engañar a Lorenzo dándole sólo }
{252}{}{ chapas.]}
{253}{}{¡Olvídalo! No vas a obtener ni una chapa de mí.}
{254}{}{[Le das a Lorenzo todas tus chapas.]}
{255}{}{[Le das a Lorenzo }
{256}{}{ chapas]}
{257}{}{¡Eres un mierda! ¡Te has reído de mí! ¡Te voy a sacar esas chapas a mamporros!}
{258}{}{Es una pena. Me imagino que tendremos que hacerte tragar unas chapas. ¡Guido! ¡Leone!}
{259}{}{Vale. Supongo que tendrá que ser así. ¿Te das cuenta de que no puedo volver a tratar contigo? Si te vuelvo
 a ver aquí me veré obligado a imponerte una pena mucho más estricta.}
{260}{}{Me pones enfermo. ¡Dame las chapas y vete! ¡No quiero volver a verte nunca!}
{261}{}{¡No has tenido suficiente!}