{100}{}{Estás viendo a Loxley, el líder del Gremio de los Ladrones.}
{101}{LOX_0}{Es un pequeño regalo de Papi y Mami. De hecho, procede de generaciones algo anteriores a ellos. ¿Te gusta?}
{102}{}{Te queda bien.}
{103}{}{No, me duele oír eso.}
{104}{LOX_0A}{Vaya, gracias. Me cuesta mantenerlo con el poco refinamiento que hay por aquí, ¿sabes? Pero dejemos ese tema. Me llamo Loxley. ¿Y tú?}
{105}{}{Soy }
{106}{}{.}
{107}{}{¿A ti qué te importa?}
{108}{}{¿Qué sitio es este?}
{110}{LOX_1F}{¡Caray, fue impresionante cómo atravesaste las defensas! ¿Cómo te llamas, encanto?}
{109}{LOX_1M}{¡Una forma cojonuda de atravesar las defensas, colega! Me has impresionado bastante. ¡Venga ese nombre!}
{111}{}{Soy }
{112}{}{.}
{113}{}{¿A ti qué te importa?}
{114}{}{¿Qué sitio es este?}

# TRANSLATION NOTE: The following line is the player addressing Loxley (who is male).
{115}{}{Tienes un acento muy interesante, amigo mío.}

{116}{}{Hablas como un idiota.}
{117}{}{¿Nahh?}
{118}{LOX_2F}{De hecho estoy encantado de conocerte... por ahora. Podríamos ser más cuidadosos con la educación, ¿no? ¡Pero qué coño estás haciendo aquí!}
{119}{}{Quiero unirme al Gremio.}
{120}{}{Tengo que preguntarte algunas cosas.}
{121}{}{Te voy a llevar de cabeza a la cárcel.}
{122}{LOX_3}{Oh, qué bonito. Un aspirante, has trabajado duro para que te tenga en cuenta. Pero si quieres unirte tendrás que superar una Segunda Prueba.}
{123}{}{¿Qué es eso?}
{124}{}{Suena aterrador... ¿Qué tal si paso?}
{125}{}{Eh... ¿cuál fue la primera prueba?}
{126}{LOX_4}{En realidad es bastante simple. Tienes que demostrar que eres un ladrón. Si triunfas, ¡el mundo es tuyo! Si no, nunca nos volverás a ver. A no ser que nos andes buscando. Y por si no lo entiendes, la última parte es una amenaza.}
{127}{}{¿En qué consiste la prueba?}
{128}{}{¿Quieres decir que si fracaso cambiaréis todo este lugar de sitio o que intentaréis matarme?}
{129}{}{¿Me estás amenazando?}
{130}{LOX_5}{Es tan, tan sencillo. En las Alturas encontrarás la casa de Daren Hightower lista y madura para la cosecha. ¡Estás preparado para vivir! ¿Aceptas el reto?}
{131}{}{¡Estoy listo!}
{132}{}{¡Y un huevo!}
{134}{LOX_6F}{¡Esa es la actitud, encanto!}
{133}{LOX_6M}{¡Esa es la actitud, colega!}
{135}{LOX_6B}{Habla con Jasmine en la habitación que hay fuera de esta cámara. Ella te dará los detalles, un mapa y algunas cosillas que te ayudarán en el camino. Pero recuerda, si se te ocurre chivarte de nosotros a la poli, seremos un recuerdo antes de que aparezcan. Pero basta de malos rollos. ¡Hasta luego, buena suerte y andando!}
{136}{LOX_7}{¿Entonces por qué demonios estás aquí? ¿Por el paisaje? ¿El ambiente? ¿Por mi cara bonita?}
{137}{}{No, he venido para hacerte unas cuantas preguntas.}
{138}{}{Desde luego que no es por tu cara bonita.}
{139}{}{Tienes razón. Me gustaría unirme al Gremio.}
{140}{LOX_8}{¿Eso es todo? ¡Unas preguntas! Bueno, o eres increíblemente valiente o eres subnormal. ¡Pregunta, pregunta...! y luego te acompañaremos a la puerta, ¿vale?}
{141}{LOX_9}{¡Debes estar bromeando! ¡Creías que me iba a tragar eso! ¡Fuera de aquí, plebeyo!}
{142}{LOX_10}{¡Oh, vaya una actitud! Pero aquí todos somos amigos, ¿no es así?}
{143}{}{No veo porqué.}
{144}{}{Tienes razón. Lo siento.}
{145}{LOX_11}{Oh, me partes el corazón. Ya no podemos ser colegas. [Suspiro] Jasmine, muéstrale la salida a esta cucaracha.}
{146}{LOX_12}{Ooh, un tira y afloja. Me gustan los que juegan al límite. Creo que serás una buena adquisición para nuestra feliz y pequeña banda... ¿Qué me dices?}
{147}{}{¡Vale!}
{148}{}{Digo que eres un completo lunático.}
{149}{lox_12b}{¡Vale!}
{150}{LOX_13}{Oh, me ha salido rana. En fin, lamento oír eso, de verdad. Habrías sido un buen ladrón. Pero el Gremio no es para imbéciles terminales. Así pues, Jasmine, muéstrale la salida a nuestro invitado.}
{151}{LOX_14}{¿Oh, por quién me tomas? Si buscas asesinos a sangre fría, habla con Decker y su panda. Si fracasas, lo más probable, llegados a este punto, sólo desapareceremos. Entonces, ¿vas a intentarlo o no?}
{152}{}{Claro que sí.}
{153}{}{No.}
{154}{LOX_16}{Oh, no. Tengo tanto miedo. La vida es tan dura. Loxley, prefiero ser un cobarde toda mi vida a gozar de un solo momento de triunfo. Bah, no eres más que otro gilipollas, ¿no? ¡Largo de aquí!}
{155}{LOX_17}{No nos hemos enterado todavía, ¿eh? ¡La primera prueba consistía en llegar hasta aquí! Es la única razón por la que te estoy haciendo caso.}
{156}{}{¡¡Vale, haré lo que quieras!!}
{157}{}{¿En qué consiste la siguiente prueba?}
{158}{}{Todo lo que necesito es hacerte un par de preguntas.}
{159}{LOX_18}{Ja, ja, ja. Oh, muy divertido. Llévanos a la cárcel, por favor. ¿Y cómo, si puedo preguntar, pensabas llevar a cabo semejante hazaña?}
{160}{}{Ven conmigo sin armar bulla y nadie saldrá herido.}
{161}{}{Bueno, quizás por esta vez lo deje pasar.}
{162}{LOX_21}{¿Que qué me importa? En realidad es muy sencillo. O me dices tu nombre o te mostramos la puerta.}
{163}{}{Vale. Soy }
{164}{}{.}
{165}{}{¿Qué tal si te enseño mi bota?}
{166}{LOX_22}{¡Esto es el famoso Gremio de los Ladrones! Suponía que lo sabrías, viendo cómo conseguiste pasar por las defensas y todo lo demás. Pero no importa. Eres bastante prometedor y el Gremio te podrá usar para algo.}
{167}{}{Vale, ¿qué tengo que hacer?}
{168}{}{No gracias. Pero quisiera hacerte unas preguntas.}
{169}{}{Ni de coña.}
{170}{LOX_23}{Bueno, si has pasado por mi sistema de defensas tendrás cualidades. ¿Cómo te llamas?}
{171}{}{Soy }
{172}{}{.}
{173}{}{¿A ti qué te importa?}
{174}{}{¿Qué sitio es este?}

# TRANSLATION NOTE: The following line is the player addressing Loxley (who is male).
{175}{}{Tienes un acento muy interesante, amigo mío.}

{176}{}{Hablas como un idiota.}
{177}{LOX_24}{¿Qué diablos quieres?}
{178}{}{¿Qué he hecho? ¿Por qué esa hostilidad?}
{179}{}{Alejarme de ti.}

# TRANSLATION NOTE: The following line is the player addressing Loxley (who is male)
{180}{}{Oye, estoy de tu lado. Estoy aquí como un amigo.}

{181}{LOX_25}{No me gustas. No se por qué y no me importa.}
{182}{}{¡Dame una oportunidad!}
{183}{}{Bueno, entonces eres un idiota, ¿no?}
{184}{LOX_26}{Gracias por este momento tan encantador. Jasmine, enséñale la salida a nuestro invitado.}
{185}{LOX_27}{Oh, me alegro de volver a verte. ¿Tienes alguna cosilla para mí?}
{186}{}{Mi dimisión. He decidido no pasar por tu estúpida prueba.}
{187}{}{Aún no lo he conseguido.}
{188}{}{Aquí está el collar...}
{189}{LOX_29}{¡Ja! ¡Ja! ¡Bien hecho! Enhorabuena. Ahora eres miembro del mundialmente famoso Gremio de los Ladrones. Traigamos a Jasmine y echemos un trago, ¿de acuerdo?}
{190}{LOX_30}{Oh, qué gracioso. Pero he de decirte que no me gustan este tipo de bromas. Este tipo de gracietas. Del estilo vamos-a-tomarle-el-pelo-al-viejo-Loxley. Te diré una cosa. Es tu última oportunidad. Tráeme el collar.}
{191}{LOX_31}{Eres como un grano en el culo, ¿lo sabías?}
{192}{LOX_32}{¡Estúpido! Oh. Me decepciona tanto que lo veas así. Ah, en fin, nuestro humilde Gremio tendrá que seguir sin tu deslumbrante presencia. Qué pena. Jasmine, acompaña a nuestro invitado. Y no esperes privilegios, ¿eh?}
{193}{LOX_33}{¿Entonces qué coño haces aquí? ¡Buhh! Lárgate. Pero esta vez regresa con el collar.}
{194}{}{¿Pasa algo interesante por aquí?}
{195}{}{Háblame del Eje.}
{196}{}{¿Has oído rumores interesantes últimamente?}
{197}{}{Cuéntame más cosas sobre el Gremio.}
{198}{}{Estoy buscando las caravanas desaparecidas. ¿Alguna sugerencia?}
{199}{LOX_35}{Toda la ciudad está alborotada, bueno, con lo de las caravanas desaparecidas y eso. Qué mal rollo. Interfiere en el negocio del Gremio, ¿no lo sabías?}
{200}{}{¿Sabes quién puede ser el responsable?}
{201}{}{Gracias, ¿puedo hacerte algunas preguntas más?}
{202}{LOX_36}{No lo sé, pero espero que lo averigüen pronto. La gente está nerviosa y eso nos dificulta el trabajo. Por no mencionar las estúpidas supersticiones que proliferan.}
{203}{}{¿Qué tipo de supersticiones?}
{204}{}{Gracias. ¿Puedo hacerte algunas preguntas más?}
{205}{LOX_37}{Oh, algún rollazo como que una Garra Mortal agarró las caravanas y se las llevó a su guarida para ofrecerles un té.}
{206}{}{Muy jugoso. ¿Puedo hacerte más preguntas?}
{207}{LOX_38A}{Oh, por supuesto. Aquí todos somos amigos.}
{208}{lox_38b}{[Suspira] ¿Por qué no?}
{209}{LOX_38C}{Pregunta, pregunta.}
{210}{LOX_39}{De hecho no. Sólo tenías una, considérate afortunado. Adiós, andando.}
{211}{lox_40}{Nada que te pueda interesar.}
{212}{}{Prueba.}
{213}{}{Vale, gracias. ¿Puedo hacerte algunas preguntas más?}
{214}{LOX_41}{Oh nada. Sólo que toda la ciudad se ha puesto histérica con lo de las caravanas. Eso es todo.}
{215}{}{Vaya, gracias. ¿Puedo hacerte algunas preguntas más?}
{216}{LOX_42}{Oh, sólo lo normal. Las caravanas de mercaderes se forran a costa de los pobres, mientras ese villano de Decker se aprovecha de todo el mundo.}
{217}{LOX_43}{Bueno, tienes la cantidad normal de tiendas y esas cosas. Eso lo mezclas con esos locos de los Niños de la Catedral. Y añades un pellizco de Decker y sus clandestinos haciéndonos la vida imposible a todos. Además lo espolvoreas con mercaderes codiciosos y ya está listo.}
{218}{}{Los mercaderes son escoria, ¿no?}
{219}{}{Parece que eres un fiel admirador de Decker.}
{220}{LOX_43A}{Siguiente pregunta, por favor.}
{221}{LOX_44}{¡Sin duda! Por eso se formó el Gremio, ¿sabes? Es decir, tienes a todos esos puñeteros ricos matando de hambre a los pobres. Y esos pobres sólo esperan un héroe. Nosotros les ayudamos, ellos besan el suelo que pisamos.}
{222}{}{¿Qué hay de malo en hacer chapas?}
{223}{}{Como Robin Hood.}
{224}{LOX_47}{¡¿Qué hay de malo?! Pedazo de... bueno, me he equivocado contigo, ¿verdad? ¡Jasmine acompaña a este lameculos de mercader!}
{225}{LOX_48}{¡Conoces la historia! Sabía que tenías algo especial. Ah, mi abuelo me lo contó hace mucho tiempo. ¡Ese sí que era un ladrón! Pero ya está bien de historias. ¿Quieres preguntar algo más?}
{226}{LOX_51}{Aparte de las caravanas desaparecidas, no mucho. Oh, espera. Uno de mis amigos regresó ayer todo luminiscente por la radiación venenosa. Mal asunto. Seguramente merodeó demasiado cerca de la antigua Zona Caliente.}
{227}{LOX_53}{Robamos a los ricos, simple y llanamente. Repartimos entre el diez y el veinte por ciento a los pobres de la Ciudad Antigua. El Gremio se lleva otro veinte y el resto es para el ladrón. No es un mal negocio.}
{228}{LOX_54}{¡Somos una panda de delincuentes! ¿Pensabas que éramos una panda de monjitas?}
{229}{LOX_55A}{Puedes probar con los mercaderes, aunque creo que aprovecharías más el tiempo fichándolos para un trabajito nocturno. Aunque yo creo que es una estupidez, puedes preguntar por ahí sobre la Garra Mortal. O incluso, si estás completamente loco, puedes seguir a una caravana.}
{230}{LOX_55B}{Bueno, ¿cómo demonios podría saberlo? ¿Acaso te parezco un mercader?}
{231}{LOX_56}{Un par de reglas del juego. Una: Nunca te dejes atrapar. Y dos: Jamás se te ocurra robar al Gremio. Recuérdalas.}
{232}{LOX_57}{No le terminas de coger el tranquillo a esto, ¿verdad? Jasmine, acompaña a nuestro estúpido amigo; y no quiero volver a ver su careto.}
{233}{LOX_58}{Me parece que no lo entiendes. Guárdatelo para los mercaderes, ¿vale?}
{234}{LOX_59}{¿Qué demonios estás haciendo aquí? ¡Lárgate!}
{235}{LOX_60}{Ves, es como yo decía...}
{236}{LOX_61}{Bueno, como decía...}
{237}{LOX_62}{¿Eres imbécil? Ya te he dicho que...}
{238}{LOX_63}{¿Eres idiota o estás sordo? Te he dicho que...}
{239}{LOX_64}{No me hace gracia tener que repetir las cosas.}
{240}{LOX_65}{¡Agh! No hay manera contigo. Es evidente que aunque me desgañite, esa información no entrará en tu cabezota.}
{241}{LOX_66}{No. Decker es un listillo. Tiene a toda la ciudad metida en el bolsillo. Da su "protección" a los mercaderes, mientras que los pone a unos contra otros. Es mejor no tener líos con él, aunque se le puede encontrar en el Halcón Maltés.}
{242}{LOX_67}{Es un comerciante de armas de la parte norte de la Ciudad Antigua. Un individuo muy peligroso, su armamento es letal.}
{243}{LOX_68}{No nos quieren mucho, la verdad.}
{244}{LOX_69}{¿Harold? No es un mal tipo, para ser un Necrófago y todo eso. Vive en el sur.}
{245}{LOX_70}{La mano derecha de Decker, mejor no tener líos con él. Suele estar en el Halcón Maltés.}
{246}{LOX_71}{Ellos. Están sentados en lo alto de su Torre de Agua, al sur del centro de la ciudad. Cobrándonos a los trabajadores honrados por cada gota de agua que sale del suelo. Deberían ser fusilados, sí que deberían serlo.}
{247}{LOX_72}{Tienen un pequeño establecimiento general en el centro. Pero no te puedes fiar de ellos. Se esconden en su maldito almacén la mayor parte del tiempo. Aunque venden algunas drogas y botiquines. Y mucho más barato que los estúpidos Niños de la Catedral, eso te lo aseguro.}
{248}{LOX_73}{La más decente de las tres caravanas. Se escapó por unos kilómetros.}
{249}{LOX_74}{Son unos criminales. Uno auténticos criminales. Están despojando de vida a la ciudad. Los Comerciantes de Ultramar, la Caravana Carmesí y los peores, los Mercaderes de Agua. Te puedes quedar con todos.}
{250}{lox_75}{Está en el centro de la ciudad.}
{251}{LOX_76}{No hay mucho que contar, la verdad. Un cuento para no dormir, para asustar a los niños con una bestia que vive al norte y se alimenta de los niños malos de todas partes.}
{252}{LOX_77}{Parece que cada día desaparece una nueva. A la gente le da miedo abandonar la ciudad sin protección. Algunos incluso culpan a la Garra Mortal.}
{253}{LOX_78}{Hace tres años, un mercader viajó al sur en busca de otras ciudades. Cuando volvió, se le caían los dientes y el pelo y hablaba de un inmenso foco de radiaciones. Quién sabe, quizás había algo especial allí antes de la guerra.}
{254}{LOX_79}{La mayoría de los pobres que trabajan para los mercaderes viven aquí, en edificios tan estrechos que no hacen ni sombra. Mientras tanto, esos bastardos con chapas viven cómodamente en sus bonitas casas de las Alturas. Me pone malo.}
{255}{LOX_80}{Bonitos edificios. Construidos con la sangre de los pobres.}
{256}{LOX_81}{Siempre puedes encontrar a Bob en el centro del Mercado de Mercaderes. Probablemente seguirá vendiendo esas Delicias de Iguana suyas hasta que se caiga muerto.}
{257}{LOX_82}{Un atajo de colgados. Se pasan el día hablando de su Dios de la Noche, como si fuese lo mejor después de los agujeros en los bolsillos de los mercaderes. Te pueden curar a buen precio, eso lo admito. Les encontrarás en ese hospital suyo del centro.}
{258}{LOX_83}{Oh, otra panda de colgados. Se sientan en su gran fortaleza negra del norte, esperando la próxima guerra.}
{259}{LOX_84}{Tienes que tener cuidado allí. Los Destripadores y los Navajas te rajarían sólo por pasar el rato. Mientras, esa ciudad, Adytum, intenta sobrevivir. Si cuando andes por allí te topas con Cuchilla, salúdala de mi parte. Pensar en ella me trae tantos recuerdos.}
{260}{LOX_85}{Son los calvorotas del Cementerio. Han estado luchando tantos años que ya no saben por qué lo hacen. Es totalmente absurdo.}
{261}{LOX_86}{¡Oh, qué mujer! Solía ser una ladrona aquí, hasta que decidió mudarse al sur del Cementerio. Lo último que supe de ella es que se había unido a los Navajas. En fin, no destacaba precisamente por su cerebro.}
{262}{LOX_87}{Mmm, no tengo ni idea.}
{263}{LOX_88}{La verdad es que no lo sé.}
{264}{LOX_89}{Mmm. La verdad es que no tengo ni idea.}
{265}{LOX_90}{Bueno, [Irónico] ¿cómo pudo alguien tan idiota como tú atravesar mis defensas? Lo siento, no admitimos idiotas aquí, nos gusta la buena conversación. Jasmine, por favor, muéstrale la salida a esta sabandija.}
{266}{LOX_91}{Habla con Jasmine y ella te dará los detalles.}
{267}{}{Loxley parece estar demasiado ocupado para hablar.}
{268}{}{Jasmine te dará tu recompensa.}


# Loxley Tell-Me-Abouts generic responses
{980}{LOX_87}{Mmm, no tengo ni idea.}
{981}{LOX_88}{La verdad es que no lo sé.}
{982}{LOX_89}{Mmm. La verdad es que no tengo ni idea.}
{983}{LOX_90}{Bueno, [Irónico] ¿cómo pudo alguien tan idiota como tú atravesar mis defensas? Lo siento, no admitimos idiotas aquí, nos gusta la buena conversación. Jasmine, por favor, muéstrale la salida a esta sabandija.}


#
# Loxley Tell-Me-Abouts
#

{1000}{}{Decker}
{1001}{}{Jacob}
{1002}{}{Policía}
{1003}{}{Harold}
{1004}{}{Kane}
{1006}{}{Carmesí}
{1007}{}{Comerciantes}
{1008}{}{Caravanas}
{1009}{}{Mercado}
{1010}{}{Garra}
{1011}{}{Desaparecidas}
{1012}{}{Caliente}
{1013}{}{Ciudad}
{1014}{}{Alturas}
{1015}{}{Bob}
{1016}{}{Catedral}
{1017}{}{Hermandad}
{1018}{}{Angel}
{1019}{}{Navajas}
{1020}{}{Cuchilla}
{1021}{}{Mercaderes}
{1022}{}{Zona}
{1023}{}{Iguana}
{1024}{}{Delicias}
{1025}{}{de Bob}
{1026}{}{Acero}
{1027}{}{Ángeles}
{1028}{}{Cementerio}
{1029}{}{Caravana}
{1030}{}{Mortal}
{1031}{}{Garra Mortal}
{1032}{}{Ardor}
{1033}{}{Ciudad Antigua}
{1034}{}{Antigua}

{1100}{LOX_66}{No. Decker es un listillo. Tiene a toda la ciudad metida en el bolsillo. Da su "protección" a los mercaderes, mientras que los pone a unos contra otros. Es mejor no tener líos con él, aunque se le puede encontrar en el Halcón Maltés.}
{1101}{LOX_67}{Es un comerciante de armas de la parte norte de la Ciudad Antigua. Un individuo muy peligroso, su armamento es letal.}
{1102}{LOX_68}{No nos quieren mucho, la verdad.}
{1103}{LOX_69}{¿Harold? No es un mal tipo, para ser un Necrófago y todo eso. Vive en el sur.}
{1104}{LOX_70}{La mano derecha de Decker, conviene no tener líos con él. Se le suele encontrar en el Halcón Maltés.}
{1106}{LOX_72}{Tienen un pequeño establecimiento general en el centro. Pero no te puedes fiar de ellos. Se quedan escondidos en su maldito almacén la mayor parte del tiempo. Aunque venden algunas drogas y botiquines. Y mucho más barato que los estúpidos Niños de la Catedral, eso te lo aseguro.}
{1107}{LOX_73}{La más decente de las tres caravanas. Se escapó por unos kilómetros.}
{1108}{LOX_74}{Son unos criminales. Unos auténticos criminales. Están despojando de vida a la ciudad. Los Comerciantes de Ultramar, la Caravana Carmesí y los peores, los Mercaderes de Agua. Puedes tener a todos.}
{1109}{lox_75}{Está en el centro de la ciudad.}
{1110}{LOX_76}{No hay mucho que contar, la verdad. Un cuento para no dormir, para asustar a los niños con una bestia que vive al norte y se alimenta de los niños malos de todas partes.}
{1111}{LOX_77}{Parece que cada día desaparece una nueva. A la gente le da miedo abandonar la ciudad sin protección. Algunos incluso culpan a la Garra Mortal.}
{1112}{LOX_78}{Hace tres años, un mercader viajó al sur en busca de otras ciudades. Cuando volvió, se le caían los dientes y el pelo y hablaba de un inmenso foco de radiaciones. Quién sabe, quizás había algo especial allí antes de la guerra.}
{1113}{LOX_79}{La mayoría de los pobres que trabajan para los mercaderes viven aquí, en edificios tan estrechos que no hacen ni sombra. Mientras, esos bastardos con chapas viven cómodamente en sus bonitas casas de las Alturas. Me pone malo.}
{1114}{LOX_80}{Bonitos edificios. Construidos con la sangre de los pobres.}
{1115}{LOX_81}{Siempre puedes encontrar a Bob en el centro del Mercado de Mercaderes. Probablemente seguirá vendiendo esas Delicias de Iguana suyas hasta que se caiga muerto.}
{1116}{LOX_82}{Un atajo de colgados. Se pasan el día hablando de su Dios de la Noche, como si fuese lo mejor después de los agujeros en los bolsillos de los mercaderes. Pero te pueden curar a buen precio, eso lo admito. Les encontrarás en ese hospital suyo del centro.}
{1117}{LOX_83}{Oh, otra panda de colgados. Se sientan en su gran fortaleza negra del norte, esperando la próxima guerra.}
{1118}{LOX_84}{Tienes que tener cuidado allí. Los Destripadores y los Navajas te rajarían sólo por pasar el rato. Mientras, esa ciudad, Adytum, intenta sobrevivir. Si cuando andes por allí te topas con Cuchilla salúdala de mi parte. Pensar en ella me trae tantos recuerdos.}
{1119}{LOX_85}{Son los calvorotas del Cementerio. Han estado luchando tantos que ya no saben por qué lo hacen. Es totalmente absurdo.}
{1120}{LOX_86}{¡Oh, qué mujer! Solía ser una ladrona aquí, hasta que decidió mudarse al sur del Cementerio. Lo último que supe de ella es que se había unido a los Navajas. En fin, no destacaba precisamente por su cerebro.}
{1121}{LOX_71}{Ellos. Pretenciosamente sentados en lo alto de su Torre de Agua, al sur del centro de la ciudad. Cargándonos a los trabajadores honrados por cada gota de agua que sale del suelo. Deberían ser fusilados, sí que deberían serlo.}
{1122}{LOX_78}{Hace unos tres años, un mercader viajó al sur en busca de otras ciudades. Volvió desdentado y sin pelo, farfullando algo sobre un inmenso foco de radiación. Quién sabe, quizás había algo especial allí antes de la guerra.}
{1123}{LOX_81}{Siempre puedes encontrar a Bob en el centro del Mercado de Mercaderes. Probablemente seguirá vendiendo esas Delicias de Iguana suyas hasta que se caiga muerto.}
{1124}{LOX_81}{Siempre puedes encontrar a Bob en el centro del Mercado de Mercaderes. Probablemente seguirá vendiendo esas Delicias de Iguana suyas hasta que se caiga muerto.}
{1125}{LOX_81}{Siempre puedes encontrar a Bob en el centro del Mercado de Mercaderes. Probablemente seguirá vendiendo esas Delicias de Iguana suyas hasta que se caiga muerto.}
{1126}{LOX_83}{Oh, otra panda de colgados. Se sientan en su gran fortaleza negra del norte, esperando la próxima guerra.}
{1127}{LOX_84}{Tienes que tener cuidado allí. Los Destripadores y los Navajas te rajarían sólo por pasar el rato. Mientras, esa ciudad, Adytum, intenta sobrevivir. Si cuando andes por allí te topas con Cuchilla, salúdala de mi parte. Pensar en ella me trae tantos recuerdos.}
{1128}{LOX_84}{Tienes que tener cuidado allí. Los Destripadores y los Navajas te rajarían sólo por pasar el rato. Mientras, esa ciudad, Adytum, intenta sobrevivir. Si cuando andes por allí te topas con Cuchilla, salúdala de mi parte. Pensar en ella me trae tantos recuerdos.}
{1129}{LOX_74}{Son unos criminales. Unos auténticos criminales. Están despojando de vida a la ciudad. Los Comerciantes de Ultramar, la Caravana Carmesí y los peores, los Mercaderes de Agua. Te puedes quedar con todos.}
{1130}{LOX_76}{No hay mucho que contar, la verdad. Un cuento para no dormir, para asustar a los niños con una bestia que vive al norte y se alimenta de los niños malos de todas partes.}
{1131}{LOX_76}{No hay mucho que contar, la verdad. Un cuento para no dormir, para asustar a los niños con una bestia que vive al norte y se alimenta de los niños malos de todas partes.}
{1132}{LOX_78}{Hace tres años, un mercader viajó al sur en busca de otras ciudades. Cuando volvió, se le caían los dientes y el pelo y hablaba de un inmenso foco de radiaciones. Quién sabe, quizás había algo especial allí antes de la guerra.}
{1133}{LOX_79}{La mayoría de los pobres que trabajan para los mercaderes viven aquí, en edificios tan estrechos que no hacen ni sombra. Mientras, esos bastardos con chapas viven cómodamente en sus bonitas casas de las Alturas. Me pone malo.}
{1134}{LOX_79}{La mayoría de los pobres que trabajan para los mercaderes viven aquí, en edificios tan estrechos que no hacen ni sombra. Mientras, esos bastardos con chapas viven cómodamente en sus bonitas casas de las Alturas. Me pone malo.}
