{100}{}{Estás viendo al Teniente del ejército del Maestro.}
{101}{LIEUT1}{Veamos, ¿qué tenemos aquí? Me han dicho que quieres divulgar
 información de lo más importante. Espero que sea así.}
{102}{}{Eh, sí.}
{103}{}{No a alguien tan feo como tú.}
{104}{}{Con una condición.}
{105}{}{¡Bah!}
{106}{LIEUT1A}{Un insulto. Qué gracioso. Te explicaría lo que significa, pero
 sería una pérdida de tiempo, ¿no crees? Veamos tus dos opciones: Puedes
 contarme lo que quiero saber. O, puedo hacerlo... a mi manera.}
{107}{}{Me quedo con "ninguna de las dos".}
{108}{}{Vale, pero con una condición.}
{109}{}{Está bien, te lo diré. Está al otro lado de las montañas, lejos al
 norte. Lo encontrarás cerca de un raro tipo de roca semiabovedada...
 Y ahora, ¿qué voy a obtener?}
{110}{LIEUT1B}{No te he ofrecido nada. Pero te daré las gracias por contarme
 dónde está tu Refugio. Estoy seguro de que el Maestro te estará... eternamente agradecido.}
{111}{LIEUT2}{Que bien para los dos. Ahora, por favor, la ubicación de tu Refugio.}
{112}{}{Está... está...}
{113}{}{Con una condición, amigo.}
{114}{}{Te he tomado el pelo. ¡Nunca te lo diré!}
{115}{}{¡Vale, vale! ¡Pero no me mates! ¡Te contaré todo lo que sé!}
{116}{LIEUT3}{¿Con una condición? Qué encanto. Adelante, entretenme con
 tu... condición.}
{117}{}{Quiero quedar libre.}
{118}{}{Deberás ponerte una bolsa en la cabeza para que pueda soportar tu presencia.}
{119}{}{Primero querría poder hacerte unas preguntas.}
{120}{LIEUT4}{¡Qué maravilloso sentido del humor! Es una lástima que yo
 no tenga. La ubicación de tu Refugio, por favor.}
{121}{}{Está bien, ¿pero primero puedo hacerte unas preguntas?}
{122}{}{No te lo voy a decir y no puedes obligarme.}
{123}{}{Está... está...}
{124}{LIEUT5}{Oh, por supuesto, querido ser humano. Siento curiosidad sobre lo que me puedes querer preguntar.}
{125}{}{¿Qué es lo que haces aquí?}
{126}{}{¿Para quién trabajas?}
{127}{}{¿Para qué me quieres?}
{128}{}{¿Qué tal si me marcho ahora mismo?}
{129}{LIEUT7}{Mi querido ser humano, ¡esto es el gran procreador! Aquí
 crearemos a otros de la raza del Maestro para asegurar la Unidad. Todo
 muy glorioso, te lo aseguro.}
{130}{}{Háblame de la Unidad.}
{131}{}{Sí que lo parece. ¿Por qué necesitáis todo esto para procrear?}
{132}{}{¿Quién está al mando?}
{133}{LIEUT8}{En este momento hay un pequeño... problema en el proceso
 reproductor. Ya se están ocupando de eso. Por ahora, necesitamos los
 Tanques para convertir a los humanos en Supermutantes. A ti también te llegará ese momento de gloria.}
{134}{}{Oh, bien. Quiero hacerte unas preguntas antes de... ¿resplandecer?}
{135}{lieut8a}{¿Cómo podría negarme ante una petición estructurada de tal manera?}
{136}{LIEUT9}{Desde luego. Tenemos todo el tiempo del mundo... Créeme.}
{137}{LIEUT10}{La Unidad es nuestra meta. Es muy sencillo. Seguro que
 incluso tú te has percatado de la constante decadencia de la civilización.}
{138}{}{Bueno, sí, pero...}
{139}{LIEUT11}{El Supermutante es el siguiente avance en la evolución del
 hombre. Salvaremos el mundo, convirtiendo a todos los individuos que
 merezcan la pena. Sencillo, eficiente, glorioso.}
{140}{}{¿Así que estáis convirtiendo a la gente en mutantes grandes y feos para salvar el mundo?}
{141}{}{¿Cómo es que estáis más avanzados?}
{142}{}{Pero no hay elección posible.}
{143}{LIEUT12}{Vuestra mente humana está demasiado subdesarrollada para entenderlo,
 porque sí, es suficiente por ahora. Pronto todo el mundo habrá sido
 transformado y la paz reinará de nuevo.}
{144}{}{¿Pero qué hay de la libertad individual?}
{145}{}{¿Me estás diciendo que no habrá guerra?}
{146}{LIEUT13}{¿Elegiste nacer en este mundo cubierto de cenizas? Nosotros,
 los Supermutantes, somos los mejor preparados para el mundo que viene.
 ¿Qué es la libertad individual comparada con la vida?}
{147}{}{Eso es discutible. ¿Pero por qué estáis más preparados que los humanos normales?}
{148}{}{¡Pero es perverso obligar a las personas a vivir como vosotros queréis!}
{149}{LIEUT14}{Resulta evidente hasta para el más distraído. Somos extremadamente
 inteligentes e inmunes a la enfermedad. ¡Sólo los fuertes sobreviven!
 Nuestro objetivo es perfeccionar la raza humana.}
{150}{}{Un objetivo muy ambicioso. ¿Cómo estáis hechos así?}
{151}{LIEUT15}{Ahh, maravillas de la técnica. Antes de la guerra los
 científicos humanos fabricaron una droga llamada VEF. Estaba diseñada para crear al humano perfecto.}
{152}{}{¿O sea que tú eres el humano perfecto?}
{153}{LIEUT16}{Mejor. Más que humano. Yo también fui un humano.
 Como tú, era un gusano, revolcándome en el fango, antes de ser expuesto
 al VEF y llevar a cabo mi gloriosa transformación.}
{154}{}{¿Estáis planeando usar el VEF con todo el mundo?}
{155}{LIEUT17}{Exactamente. Ahora lo entiendes.}
{156}{}{Desde luego. ¿Puedo hacerte algunas preguntas más?}
{157}{}{¡Pero eso es un error!}
{158}{LIEUT18}{Oh, qué desilusión. Deseaba tanto que vieses la luz antes
 de... Bueno, cuando seas uno de los nuestros, estoy seguro de que lo comprenderás.
 Entonces abrazarás la Unidad.}
{159}{}{¡Nunca! Es malvado. ¡Malvado, como lo oyes!}
{160}{}{Quizás. ¿Primero puedo hacerte unas preguntas más?}
{161}{LIEUT19}{Ni guerra ni enfermedad. Todos los Supermutantes ligados
 por la Unidad. Somos la esperanza del mundo.}
{162}{}{A mí me parece una ilusión vana.}
{163}{}{¿Cómo podéis ser la esperanza del mundo?}
{164}{LIEUT20}{Todos trabajamos para que el Maestro mantenga la gloria de
 la Unidad. Él fue el primero, ¿sabes?}
{165}{}{¿Cómo llegaste a trabajar para él?}
{166}{}{¿Qué es la Unidad?}
{167}{LIEUT21}{El destino. Un golpe de suerte. Del lote que bañaron
 en el virus, yo era el más fuerte. Y siempre he apoyado los ideales
 de la Unidad y el Maestro, porque tiene razón. Mi devoción ha sido
 recompensada.}
{168}{}{¿Qué virus?}
{169}{}{¿Y cómo es este Maestro?}
{170}{LIEUT22}{Antes de la guerra los humanos crearon un virus llamado VEF
 para fabricar al hombre perfecto. Tuvieron éxito, como puedes ver con tus
 propios ojos. El Maestro ha sido el primero en utilizar todo el potencial del VEF.}
{171}{}{¿Dónde está ese Maestro?}
{172}{}{¿Cómo funciona?}
{173}{LIEUT23}{Está ocupado con los Niños de la Catedral. Lo cierto es que
 nos consideran dioses. Pero no se les puede culpar por ello.}
{174}{}{Vaya, ¿no eres un poco engreído?}
{175}{}{¿Créeis que sois dioses?}
{176}{LIEUT24}{¿Es la honestidad engreída? Somos el nuevo paso de la
 evolución. Gracias a nuestra Unidad el mundo sobrevivirá. ¿Dónde está el engreimiento?}
{177}{}{¿Quizá dentro de esa grotesca cabezota tuya?}
{178}{}{Sí, claro, lo que tú digas. ¿Puedo hacerte unas preguntas más?}
{179}{LIEUT25}{Claro que no. Somos, simplemente, el futuro.}
{180}{}{No te creo.}
{181}{}{Antes de que llegue el futuro, hay un par de cosas por las que
 siento curiosidad.}
{182}{LIEUT26}{Oh, supongo que está por encima de tu capacidad de
 comprensión. Pero no te preocupes. Pronto tus ojos se abrirán a una nueva vida.}
{183}{}{¿¡Qué quieres decir!?}
{184}{}{Antes de que eso ocurra, hay un par de cosas más por las que siento
 curiosidad.}
{185}{LIEUT27}{[El Teniente suspira.] ¿Aún no te lo has imaginado?
 Eres un normal puro. Dentro de poco serás uno de nosotros.}
{186}{}{¿Cómo te suena "ni en broma"?}
{187}{}{Antes de convertirme en lo que tú eres, hay un par de cosas que
 despiertan mi curiosidad.}
{188}{}{¿Por qué soy un humano puro?}
{189}{LIEUT28}{Adelante, pregunta lo que quieras. No tenemos prisa.}
{190}{LIEUT29}{Él fue nuestro guía hacia el virus de la vida y es el Padre
 de todos nosotros. También quiere reunirse contigo. Espero que te sientas honrado.}
{191}{}{Eh... vale. ¿Y qué hay de ese virus? ¿Qué es?}
{192}{}{Antes de gozar de este honor, ¿qué tal si me respondes a algunas preguntas más?}
{193}{}{¿Dónde está?}
{194}{LIEUT30}{El VEF mutó con las radiaciones de la guerra. Los que vivían en
 estos yermos desolados se han expuesto a esta mutación del VEF, quedando
 prácticamente inmunizados a sus efectos.}
{195}{}{¿Y?}
{196}{}{Y, por lo tanto, ¿necesitáis a los que no están contaminados para obtener Supermutantes?}
{197}{LIEUT31}{Por ejemplo tú, provienes de un Refugio y tu exposición a la
 mutación del virus es limitada. El VEF original de los Tanques debería funcionar bastante bien contigo.}
{198}{}{¿Y cómo sabes eso?}
{199}{LIEUT32}{Hemos realizado varios experimentos con humanos para alcanzar
 estas conclusiones. Mi Maestro ha estado buscando Refugios no abiertos para
 demostrar sus teorías. Y ahora apareces tú. Es tan amable de tu parte.}
{200}{}{No lo encontrarás.}
{201}{}{Bien, antes de que eso ocurra, siento curiosidad por un par de
 cosas más.}
{202}{LIEUT33}{Oh, vaya, eres más listo de lo que pensaba. Ahora ya
 sabes porqué queremos tu Refugio.}
{203}{}{Qué pena que no lo vayáis a tener.}
{204}{}{Es un Refugio grande. ¿Que tal primero unas cuantas respuestas de nada?}
{205}{LIEUT34}{¿Irte? Espera... creo que... sí, vaya, ¡casi me río! Qué
 deliciosamente humorístico. El único sitio al que vas a ir es al Tanque. Pero
 antes me vas a decir dónde está tu Refugio.}
{206}{}{Espero que aceptes una negativa.}
{207}{LIEUT35}{Eso ya lo veremos, ¿verdad?}
{208}{lieut35a}{Eso es bastante raro, me parece que no tienes intención de decírmelo.
 ¡Habrá que arreglar eso!}
{209}{LIEUT36}{¿Te sientes mejor ahora? Como la tortura es una estupidez,
 aunque extrañamente grata y muy efectiva, te lo preguntaré por las buenas
 una vez más. ¡Dónde... está... el Refugio!}
{210}{}{¡No... te lo voy... a decir!}
{211}{}{Tú ganas. Está al otro lado de las montañas, al oeste. Te dibujaré un mapa.}
{212}{LIEUT37}{Esperaba que dijeras eso.}
{213}{LIEUT37b}{¿Qué te parece? ¿Vamos teniendo ganas de hablar? ¿Dónde
 lo habíamos dejado? Ah, claro... en el Refugio.}
{214}{}{Está... está... en tus sueños.}
{215}{}{Tú ganas. Está cruzando las montañas al oeste. Te dibujaré un mapa.}
{216}{LIEUT38}{Ah, me siento mucho mejor. ¿Y tú? Ahora pórtate bien
 y dime dónde está tu Refugio. Esto comienza a resultar tedioso.}
{217}{}{Vete al infierno.}
{218}{}{¡Lo diré! ¡Pero no me hagas más daño!}
{219}{}{Admiro tu fortaleza. Guardias, llevadlo a su celda y preparadlo
 para el baño. Nos dirá dónde
 se encuentra su Refugio cuando sea uno de los nuestros.}
{220}{}{Si estás tan seguro de que hablaré después del baño, ¿a qué viene todo esto?}
{221}{LIEUT39a}{Bueno, verás, hay un pequeño inconveniente. A veces, el baño,
 no siempre, mmm... cómo lo diría, estropea un poco la memoria de la
 persona. Así que hay una pequeña posibilidad de que olvides la ubicación.}
{222}{}{Así que no puedes arriesgarte a darme el baño.}
{223}{}{Parece que los dos lo tenemos chungo.}
{224}{LIEUT39b}{Por desgracia, llegados a este punto, tendré que arriesgarme.
 Necesito esa información.}
{225}{}{Te lo diré.}
{226}{}{Más te vale que olvide. Porque si recuerdo algo de todo esto, tu trasero será mío.}
{227}{LIEUT40}{Excelente. Creo que lo has entendido. ¿Seguro que me vas
 a decir dónde está tu Refugio? La tortura también puede ser divertida.}
{228}{}{Sí, seguro.}
{229}{}{Ahora que lo dices, no.}
{230}{}{¿Primero puedo hacerte unas preguntas más?}
{231}{LIEUT40a}{Pensé que lo verías a mi manera. ¿No te lo quieres pensar mejor?}
{232}{}{Te lo contaré todo.}
{233}{}{Sí, he cambiado de idea y no te lo diré nunca.}
{234}{}{Primero, ¿puedo hacerte unas preguntas más?}
{235}{LIEUT41}{Oh, esto es fantástico. Sabes, de hecho, dudé de mis
 oficiales cuando me dijeron que habían capturado un normal puro. Me alegra tanto verte.}
{236}{}{Vete al infierno.}
{237}{}{¿Qué quieres de mí?}
{238}{}{¡Anda!}
{239}{LIEUT42}{Sí, tienes tacto con las palabras. Y son palabras
 lo que queremos antes de...}
{240}{}{¿Qué quieres decir con "antes de"?}
{241}{}{¡No vas a conseguir nada de mí!}
{242}{LIEUT43}{¡Antes de convertirte en uno de los nuestros, claro! No puedo
 tener a un perfecto normal puro y no convertirlo en uno de los Elegidos,
 ¿no? Después de que me digas dónde está tu Refugio.}
{243}{}{¿Decírtelo? Casi eres gracioso.}
{244}{}{Con una condición.}
{245}{LIEUT44}{Oh, qué encomiable. Ya está bien de tonterías. ¿Dónde está tu Refugio?}
{246}{}{No te lo pienso decir.}
{247}{}{Bueno... con una condición.}
{248}{LIEUT45f}{Vaya, estoy impresionado. Mis espías me dijeron que tenías muchos recursos,
 pero parece que subestimaron tu talento. ¡Guardias, capturadla!}
{249}{LIEUT46}{Ah, ¿una buena siesta? Espero que sí. Pero ahora tenemos que volver
 a nuestro asunto.}
{250}{}{Vete al infierno.}
{251}{}{¿Qué quieres de mí?}
{252}{LIEUT48}{Tu intelecto es sorprendente. Por qué no tienes legiones de seguidores
 en este momento es algo que nunca comprenderé. ¡Guardias, sacad de aquí a
 este idiota!}
{253}{LIEUT50}{Como te he dicho...}
{254}{lieut51}{Como ya te he dicho antes...}
{255}{LIEUT52}{Por favor, presta atención esta vez, te he dicho que...}
{256}{lieut53}{Te dije que...}
{257}{LIEUT54}{Sabes, me recuerdas a una cucaracha que tenía.
 La aplasté porque me ponían nervioso los ruiditos que emitía. Recuerda eso.}
{258}{LIEUT55}{Eres un pequeño humano muy pesado, ¿no es así?
 No lo voy a repetir otra vez.}
{259}{LIEUT56}{La Unidad es el objetivo de todos los Supermutantes. Con el
 virus VEF conduciremos a toda la humanidad hacia la paz.}
{260}{LIEUT57}{El virus VEF fue descubierto por el Maestro hace muchos años.
 Es lo que hizo de nosotros los Elegidos. Pero enseguida comprenderás lo que te digo, te lo aseguro.}
{261}{LIEUT58}{El Maestro es el padre de todos nosotros.}
{262}{LIEUT59}{Nada más que un dispositivo para extender nuestros planes.
 No importa, todos los humanos serán Elegidos o... muertos.}
{263}{LIEUT60}{En los Tanques es donde se almacena el VEF y donde vosotros
 los normales os transformáis en uno de los nuestros. Por supuesto, algunos mueren de
 una muerte extremadamente dolorosa, pero son los riesgos del oficio.}
{264}{LIEUT61}{Son los humanos que no han estado expuestos a las radiaciones.
 Les suele ir mejor que a los demás en los Tanques. Tú eres un ejemplo perfecto.}
{265}{LIEUT62}{Fueron construidos antes de la guerra. Además son nuestra
 principal fuente de Normales Puros.}
{266}{LIEUT63}{Morfeo. Es muy gracioso. Se cree que es mucho más que simplemente
 una babosa que el Maestro reclutó para encabezar su idea absurda de los Niños de la Catedral.
 Ah, en fin. Él también se bañará en los Tanques y probablemente tendrá una
 muerte horrible... al menos eso espero.}
{267}{LIEUT64}{Ahora mismo eso no tiene importancia.}
{268}{LIEUT65}{Esa es una pregunta irrelevante para la Unidad.}
{269}{LIEUT66}{Ni siquiera me dignaré a dar una respuesta.}
{270}{lieut45m}{Vaya, estoy bastante impresionado. Mis espías me dijeron que tenías muchos recursos,
 pero parece que subestimaron tu talento. ¡Guardias, capturadlo!}
{271}{lieut39f}{Admiro tu fuerza de voluntad. Guardias, llevadla a su celda y preparadla para el baño.
 Nos dirá donde se encuentra su Refugio cuando sea una de los nuestros.}
{272}{lieut39m}{Admiro tu fuerza de voluntad. Guardias, llevadlo a su celda y preparadlo para el baño.
 Nos dirá donde se encuentra su Refugio cuando sea uno de los nuestros.}


# Lieutenant Tell-Me-Abouts generic responses
{980}{LIEUT64}{Ahora mismo eso no es importante.}
{981}{LIEUT65}{Esa es una pregunta irrelevante para la Unidad.}
{982}{LIEUT66}{Ni siquiera me dignaré a dar una respuesta.}

#
# Lieutenant Tell-Me-Abouts
#


{1000}{}{Unidad}
{1001}{}{VEF}
{1002}{}{Maestro}
{1003}{}{Catedral}
{1004}{}{Tanques}
{1005}{}{Normales}
{1006}{}{Refugios}
{1007}{}{Morfeo}
{1008}{}{Virus}

{1100}{LIEUT56}{La Unidad es el objetivo de todos los Supermutantes. Con el virus VEF conduciremos a toda la humanidad hacia la paz.}
{1101}{LIEUT57}{El virus VEF fue descubierto por el Maestro hace muchos años. Es lo que nos hace ser los Elegidos. Pero enseguida comprenderás lo que te digo, te lo aseguro.}
{1102}{LIEUT58}{El Maestro es el padre de todos nosotros.}
{1103}{LIEUT59}{Nada más que un dispositivo para extender nuestros planes. No importa, todos los humanos serán Elegidos o... muertos.}
{1104}{LIEUT60}{En los Tanques es donde se almacena el VEF y donde vosotros los normales os transformáis en nosotros. Por supuesto, algunos mueren con una muerte extremadamente dolorosa, pero son los riesgos del oficio.}
{1105}{LIEUT61}{Son los humanos que no han estado expuestos a la radiación. Les suele ir mejor que a los demás en los Tanques. Tú eres un ejemplo perfecto.}
{1106}{LIEUT62}{Fueron construidos antes de la guerra. Además son nuestra principal fuente de Normales Puros.}
{1107}{LIEUT63}{Morfeo. Es muy gracioso. Se cree que es mucho más que simplemente una babosa que el Maestro reclutó para encabezar su idea absurda de los Niños de la Catedral. Ah, en fin. Él también se bañará en los Tanques y probablemente tendrá una muerte horrible... al menos eso espero.}
{1108}{LIEUT57}{El virus VEF fue descubierto por el Maestro hace muchos años. Es lo que nos hace ser los Elegidos. Pero enseguida comprenderás lo que te digo, te lo aseguro.}

{1109}{LIEUT65}{Esa es una pregunta irrelevante para la Unidad.}
{1110}{LIEUT66}{Ni siquiera me dignaré a dar una respuesta.}
{1111}{LIEUT45m}{Vaya, estoy impresionado. Mis espías me dijeron que tenías muchos recursos, pero parece que subestimaron tu talento. ¡Guardias, capturadlo!}
{1112}{LIEUT39f}{Oh, admiro tu fuerza de voluntad. Guardias, llevadla a su celda y preparadla para el baño. Nos dirá donde se encuentra su Refugio cuando sea una de los nuestros.}
{1113}{LIEUT39m}{Oh, admiro tu fuerza de voluntad. Guardias, llevadlo a su celda y preparadlo para el baño. Nos dirá donde se encuentra su Refugio cuando sea uno de los nuestros.}
