{100}{}{Estás viendo al Encargado de los necrófagos.}
{101}{}{¿Qué estás haciendo aquí?}
{102}{}{Buscando los vestigios del futuro pasado.}
{103}{}{Soy un explorador.}
{104}{}{¿Qué quieres, cara de gusano?}
{105}{}{Dug-duh.}
{106}{}{¿Qué has dicho?}
{107}{}{Nada.}
{108}{}{Busco tecnología perdida.}
{109}{}{Eso es lo que había entendido. Vete de mi casa.}
{110}{}{Oh, nada de eso por aquí. Puede que arriba en el
 templo o en un lugar con agua. Vete.}
{111}{}{¡Eh! No te metas en mis asuntos.
 Vete de aquí. En serio.}
{112}{}{No quiero ver una cara como la tuya por aquí.}
{113}{}{Oh, sí.}
{114}{}{Te voy a arrancar la cara y voy a utilizarla como...}
{115}{}{¡Eh! Vale, me rindo. Me voy.} 
{116}{}{No me vas a dar ninguna orden. ¡Coge algo de ahí y vete de aquí!}
{117}{}{No quiero hablar contigo.}
{118}{}{¿Qué eres?}
{119}{}{Soy un necrófago. ¿Nunca habías visto a un necrófago?}
{120}{}{Sí.}
{121}{}{No.}
{122}{}{Debes haber sido un miembro de los Clandestinos. Te han dejado con vida y por eso
 puedes contagiarme. Ahora vete de mi casa.}
{123}{}{Ahora lo tienes. ¡Vete de aquí!}
