{100}{}{Estás viendo al Maestro de los Supermutantes.}
{101}{Mast00}{¿Qué va a ser? ¿Te unes a la Unidad o mueres aquí mismo? ¡Únete! ¡Muere! ¡Únete! ¡Muere!}
{102}{}{No puedo ganar. Me uniré a vosotros.}
{103}{}{Si me demuestras que vuestra Unidad es el mejor curso que puede tomar la humanidad, os ayudaré.}
{104}{}{¿Qué tal si tú mueres y yo me largo?}
{105}{}{Oh, alguien va a morir hoy, pero no seré yo. Tengo un plan.}
{106}{}{Aj. Feo.}
{107}{Mast01}{Magnífico. Tu talento nos será útil. Pero, antes, debes contármelo
 todo sobre tu Refugio.}
{108}{}{¿Por qué?}
{109}{}{Vale. Te contaré todo lo que quieras saber.}
{110}{Mast02}{Conquistaré y convertiré a todo esos humanos puros en mutantes.
 Ellos serán el ejército que necesito para traer la paz a todos los yermos.}
{111}{}{Lo siento, no me gusta mucho ese plan.}
{112}{}{Parece razonable. Hagámoslo.}
{113}{Mast03}{Que así sea. Has cavado tu propia tumba. ¡Tumba! ¡Tumba!}
{114}{Mast04}{¡No te tengo que demostrar nada! Demostrar.}
{115}{}{Tu propio ego te pide que me lo cuentes. Todos los villanos tienen esta extraña necesidad de explicarlo todo.}
{116}{}{No puedo saber si representáis el mejor futuro posible si no me lo demuestras.}
{117}{Mast05}{Muy exigente para alguien en una posición tan delicada como la tuya, pero
 respetaré tu necesidad.}
{118}{}{Pues cuéntame.}
{119}{Mast06}{La Unidad traerá la raza superior. ¡Maestro! ¡Maestro! Capaz de
 sobrevivir o incluso de desarrollarse, en los yermos. Mientras existan
 diferencias, nos condenaremos a luchar unos contra otros. Necesitamos
 una sola raza. ¡Raza! ¡Raza! Una meta. ¡Meta! ¡Meta! Un pueblo... para
 caminar hacia nuestro destino. Destino.}
{120}{}{Se trata de la raza de los mutantes, por supuesto.}
{121}{}{Espero que no acabemos pareciéndonos a ti.}
{122}{Mast07}{Por supuesto. Los Mutantes son los mejor equipados para ocuparse del mundo hoy en día.
 ¿Quién si no? ¿Los Necrófagos? Por favor... ¿Los Normales? Ellos nos trajeron la
 muerte nuclear. Ésta será la era de los mutantes. Los Mutantes.}
{123}{}{¿Estás diciendo que transformaréis a todos los demás en mutantes?}
{124}{}{Eres un fanático.}
{125}{}{¿Qué pasará con aquellos que se opongan a vosotros?}
{126}{Mast08}{A todos los que se resistan, sí. A todos los que sean requeridos para la Unidad, también.
 Al resto se les permitirá vivir hasta el final de sus días, pero bajo
 el control y la protección de la Unidad. Pero nadie procreará por lo cual serán
 los últimos especímenes de sus razas.}
{127}{}{Hay un problema con tu plan.}
{128}{}{Al parecer lo tenéis todo bajo control. Me uniré a vosotros.}
{129}{}{Creo que todos vosotros estáis chiflados. Os tengo que detener.}
{130}{Mast09}{¿Cuál es?}
{131}{}{¡No contasteis conmigo! ¡Os voy a detener aquí mismo, ahora mismo!}
{132}{}{No podéis apoderaros de todo el mundo.}
{133}{}{Resulta que sé que tus mutantes son estériles.}
{134}{Mast10}{Todavía no quiero dominar el mundo entero. Cuando convierta en mutantes a los habitantes de los Refugios,
 mis fuerzas serán tan poderosas que no encontrarán oponente.
 Pero no te preocupes, no te importará. ¡Importará! ¡Importará!}
{135}{Mast11}{¡Ridículo! El virus VEF-2 no destruye los órganos reproductores
 de aquellos que modifica.}
{136}{}{Quizás antes el virus no dejaba estériles a las personas, pero ahora lo hace.}
{137}{}{¿Has hablado de esto con alguno de tus mutantes?}
{138}{}{Quizá sea por todas esas radiaciones suplementarias.}
{139}{Mast12}{¿Tienes pruebas?}
{140}{}{¡Claro que sí! Aquí están...}
{141}{}{Te doy mi palabra, pasa así.}
{142}{}{Pregúntales a tus mutantes.}
{143}{Mast13}{¡Esto no prueba nada! Pagarás por tu insolencia. ¡Insolencia!}
{144}{}{Tengo que digerir esta información. Un momento.}
{145}{Mast14}{Tengo que digerir esta información. Un momento... Ya lo entiendo. Es una buena falsificación. Has inventado todo esto
 para engañarme. ¡Engañarme!}
{146}{}{¿¡Qué!? No lo entiendo. ¡Creía que era correcto!}
{147}{}{¡Mientes! ¡Estas negando la evidencia que tienes delante!}
{148}{Mast16}{¡Pagarás por lo que has hecho! ¡Paga! Hecho.}
{149}{Mast17}{Pero no puede ser. Significaría que todo mi trabajo ha sido para
 nada. Todo lo que he intentado... ¡un fracaso! No puede Ser. Ser.
 Ser. Ser. Ser.}
{150}{}{Lo siento, no tienes elección. Tu raza desaparecerá después de esta generación.}
{151}{}{Quizás se pueda hacer algo. Quizás necesites más sujetos de prueba.}
{152}{Mast18}{Sí. Más sujetos. Creo que empezaré contigo. ¡Hacer! ¡Hacer!}
{153}{Mast19}{Creo que no puedo continuar. ¿Continuar? Haber hecho las
 cosas que he hecho en el nombre del progreso y la medicina. Fue
 una locura. Ahora lo sé. Una locura. ¿Una locura? No hay esperanza.
 Vete ahora, vete mientras te queda esperanza...}
{154}{Mast20}{Creo que debería. No te muevas.}
{155}{Mast21}{Mis científicos me han asegurado que nada está mal. ¿Qué tienes que decir a eso?
 ¡Di! ¡Di!}
{156}{}{¿Se te ocurrió preguntarle a una mutante hembra?}
{157}{}{Pregúntaselo a uno de tus Tenientes.}
{158}{}{Te tienen miedo. ¿Pensabas que te dirían la verdad?}
{159}{Mast22}{Un momento. No le encontramos. Debe estar muerto y puedo
 adivinar quién lo ha matado. ¡Muerto! ¡Matar!}
{160}{Mast23}{Lo niega todo. Y dice saber quién inició este rumor...}
{161}{Mast24}{Creo que sé quién es el mentiroso. ¡Mentiroso!}
{162}{Mast25}{Es razonable. Un momento. ¿Estás seguro? ¿Qué hay de las otras hembras?
 No puede ser. Ser.}
{163}{}{Lo siento, tu raza está condenada.}
{164}{}{Perdona que me ría... ¡Ya te lo dije!}
{165}{Mast26}{Me parece que sin pruebas no puedo creerte. Ahora, te unirás a
 mi ejercito como un mutante o morirás. ¡Muere! ¡Únete!}
{166}{}{Mejor estar muerto que ser como tú.}
{167}{}{Supone abandonar todo lo que conozco, pero me uniré.}
{168}{Mast27}{Tú humor no te salvará ahora. ¿Aceptas o no mi oferta? ¡Aceptas!
 ¡No aceptas!}
{169}{}{No acepto.}
{170}{}{Vale, es mejor que morir...}
{171}{Mast28}{La radiación no nos afecta. El virus VEF nos hace inmunes.
 Tu argumento es débil, tú también.}
{172}{Mast29}{Oh, creo que te equivocas. Pero, sólo para asegurarme ordenaré que se investigue
 este asunto. Después de ocuparme de ti. Ocuparme. ¡Ocuparme!}
{173}{Mast30}{Mi único problema eres tú. ¿Trabajarás para la Unidad o no?}
{174}{}{No.}
{175}{}{Claro.}
{176}{Mast31}{Serán castigados por su insolencia.}
{177}{}{¿Quieres matarlos a todos?}
{178}{}{¡Entonces tengo que detenerte ahora mismo!}
{179}{Mast32}{Claro que no. A la mayoría se les dará la oportunidad de convertirse en mutantes. A aquellos
 que rechacen esta posibilidad se les esterilizará y se les dejará ir. Los
 que se resistan, serán ejecutados.}
{180}{}{Eres un cachorro enfermo. Es hora de acabar contigo.}
{181}{}{Emm, no me gusta la idea de ser ejecutado. Me uno.}
{182}{Mast33}{Somos todos unos interesados, ¿verdad? Nos preocupamos más de nuestras propias comunidades
 que de las otras personas. No hemos cambiado. Y te diré
 algo más...}
{183}{}{¿El qué?}
{184}{Mast34}{No cambiaremos. No hasta que no seamos un solo pueblo. Uno. Uno. Una
 raza. Una. Una. Una. La Unidad nos permitirá elevarnos sobre estas
 pequeñas preocupaciones y ocuparnos de los problemas mayores. Tú
 quieres formar parte de ello, ¿no? Parte. No.}
{185}{}{Me has convencido. Entraré en la Unidad.}
{186}{}{Quiero una parte de... ¡tu cabeza!}
{187}{Mast35}{¡Desde luego! !Los mutantes sobrevivirán! ¡Los mutantes reconstruirán este
 mundo! ¡Y sólo como mutante, te será permitido vivir! ¡Vive! ¡Muere!}
{188}{}{¡Vive!}
{189}{}{¡Muere!}
{190}{}{Todo lo que te preocupa son tus mutantes y su Unidad.}
{191}{Mast36}{No soy un villano. No tienes ni idea de lo que yo y la Unidad significamos.}
{192}{}{Entonces dime lo que significáis.}
{193}{}{Eres un villano. Sólo que estás negando tus verdaderos sentimientos.}
{194}{Mast37}{No tengo que demostrarte nada. Si usas tu lógica, eso demostrará
 que no soy un villano. Sería inútil intentar explicártelo.}
{195}{Mast38}{¿Oh? Por favor, ¿qué tipo de plan podría ser ese?}
{196}{}{Voy a activar un mecanismo nuclear en este Refugio. Explotará en breve,
 ¡os mandará a todos al infierno!}
{197}{}{Te mataré, eso te lo pone difícil para seguir, ¿no?}
{198}{}{Convencí a la Hermandad del Acero para que invadiesen este lugar
 si yo era capturado y no me poníais en libertad. Llegarán de un momento a otro.}
{199}{Mast39}{Puede que estés diciendo la verdad. No importa, pero te dejaré ir
 por ahora.}
{200}{Mast40}{Estás mintiendo. Pero será la última mentira que digas.}
{201}{Mast41}{Un momento, voy a comprobar tu historia. Puede que digas la
 verdad. ¡Guardias! Llevad a este humano al corazón del reactor. Ocupémonos
 del problema antes de que sea tarde.}
{202}{Mast42}{Dudo incluso que el VEF te pueda ayudar. ¿Por qué sigo hablando?
 Seguro que ni siquiera me entiendes...}
{203}{Mast43}{Debes estar bromeando.}
{204}{Mast44}{Estás acabando con mi paciencia. Ahora, ¿vas a unirte a la Unidad o
 no? Unirte. ¡O no!}
{205}{}{Sí.}
{206}{}{No.}
{207}{Mast45}{Bien. Entonces puedes morir aquí y ahora.}
{208}{Mast46}{Has desactivado el mecanismo. Excelente. Dime, ¿hay algo qué quieras decirme
 antes de que te mate?}
{209}{}{Sí, ¿puedo unirme a vosotros ahora?}
{210}{}{Incluso muerto, estaré más guapo que tú.}
{211}{Mast47}{No. No. No. No.}
{212}{Mast200}{Soy el Maestro. No tengo por qué responderte.}
{213}{Mast201}{No estoy aquí para responder a tus preguntas. Tú estás aquí para responder a las mías.}
{214}{Mast202}{¡Una vez sepa la ubicación de tu Refugio, completaré mi destino!
 ¡Destino! ¡Destino! ¡Destino!}
{215}{Mast203}{¿¡Piensas que puedes destruirme!? ¡Destruirme! ¿A mí?}
{300}{}{¡Bah!}


# Master Tell-Me-Abouts generic response
{980}{Mast200}{Soy el Maestro. No tengo porqué responderte.}

#
# Master Tell-Me-Abouts
#


{1000}{}{Unidad}
{1001}{}{Maestro}
{1100}{Mast200}{Soy el Maestro. No tengo por qué responderte.}
{1101}{Mast201}{No estoy aquí para responder a tus preguntas. Tú estás aquí para responder a las mías.}
