{100}{}{Estás viendo a Mathia.}
{101}{}{Hola, Iniciado. Así que tu eres el que ha salido de la Orden Antigua
 con vida.}
{102}{}{¿Qué?}
{103}{}{¿Y tú quién eres?}
{104}{}{Lo siento. Pensé que eras otra persona. Adiós.}
{105}{}{Me llamo Mathia. Oficialmente soy el ayudante de Maxson, pero
 también estoy aquí para asegurarme que nadie se mete con el viejo.}
{106}{}{¿El viejo? Eso suena un poco irreverente.}
{107}{}{¿Qué haces como ayudante de Maxson?}
{108}{}{Encantado de conocerte. Adiós.}
{109}{}{No, no, en absoluto. Es un buen tipo. [Jocosamente] Además,
 no hablaría mal de él teniéndolo a mi lado.}
{110}{}{Pero, ¿qué es lo que haces como ayudante de Maxson?}
{111}{}{Adiós.}
{112}{}{Me encargo de la documentación escrita. Él no podría hacerlo aunque fuera para salvarse la vida. Además si realiza una mejora en las armas para
 los Hermanos, yo ejecuto la orden.}
{113}{}{Vale, gracias por la información.}
{114}{}{No puedo creer que un idiota como tú fuera uno de los que
 gobernaba la Orden Antigua.}
{115}{}{Hola de nuevo, Iniciado. ¿Puedo ayudarte?}
{116}{}{¿Qué?}
{117}{}{Lo siento, he olvidado tu nombre.}
{118}{}{Lo siento. Pensé que eras otra persona. Adiós.}
{119}{}{Bien, vamos. [Te agarra de un brazo.]}
{120}{}{Uh huh.}
{121}{}{Uh uh.}
{122}{}{Vale, vale, ya me muevo.}
{123}{}{Suéltame de una vez. No pienso ir a ninguna parte.}
{124}{}{Vale, Maxson ha realizado una mejora en las armas para ti. ¿Qué
 quieres?}
{125}{}{¿Qué?}
{126}{}{Un Rifle de Francotirador.}
{127}{}{Un Lanzamisiles.}
{128}{}{Una Pistola Láser.}
{129}{}{Un Puño de Energía.}
{130}{}{Un Destripador.}
{131}{}{Aquí tienes. Me alegro de tenerte con nosotros, Iniciado.}
{132}{}{Los Ancianos han concertado una cita. Quieren encontrarse contigo en
 la sala de conferencias de ahí.}
{133}{}{¿Dónde está la sala de conferencias?}
{134}{}{Vale, gracias.}
{135}{}{Está en esta planta. En la esquina noreste, justo detrás de la sala de reuniones.}