{100}{}{Estás viendo al General Maxson.}
{101}{}{¿De qué va realmente la Hermandad?}
{102}{}{Apuesto a que sabes mucho sobre la historia que hay detrás de la Hermandad.}
{103}{}{¿Has oído rumores interesantes?}
{104}{}{Tengo información que darte.}
{105}{}{Eso es todo. Gracias.}
{106}{Gen_1}{Hola, adolescente. Cabbot dijo que querías hablar. Mira, estoy... bastante
 liado ahora mismo, así es que, eh... te ayudaré con tal de que no empieces a darle mucho al
 pico. Ya sabes, los forasteros siempre son así, parlotean todo el rato...
 Ja, ja, ja. Un poco como yo, ¿eh?}
{107}{}{¿Forasteros? ¿Qué quieres decir con eso?}
{108}{}{¿Entonces, qué tal unas preguntas?}
{109}{Gen_2}{No puedo. Sólo modero estas malditas e interminables asambleas. Hay cuatro Ancianos
 y yo, ¿comprendes? Yo soluciono las peleas y desempato los votos. Pero, si los cuatro votan que
 nos hurguemos las narices mientras un ejército enemigo entra aquí y patea nuestro colectivo trasero, no hay mucho
 que yo pueda hacer al respecto.}
{110}{}{Oh, vaya.}
{111}{}{¡Qué mal! ¿Por qué no haces nada?}
{112}{Gen_2a}{Es la tradición. Es difícil cambiar nuestras costumbres. Ahora bien, si los Ancianos tuvieran información real, saldrían de su error y harían algo.}
{113}{Gen_3}{Un Iniciado no nacido aquí. Eres el primer Forastero al que hemos dejado unirse desde
 hace mucho, mucho tiempo. Casi veinte años. }
{114}{}{¿Por qué yo?}
{115}{}{Me honra. ¿Qué tal algunas preguntas ahora?}
{116}{Gen_4}{Porque tenemos que hacer algo. Se está reuniendo un ejército, las caravanas del Eje
 desaparecen, y nuestros exploradores no están haciendo su puñetero
 trabajo. Los Ancianos por fin hicieron algo cuando se les ocurrió que
 quizás el Forastero adecuado tuviese algo que ofrecer. Ese forastero eres tú... bueno, eso esperamos.}
{117}{}{¿Qué ejército?}
{118}{}{¿Qué pasa con las caravanas desaparecidas?}
{119}{}{Mmm. Entonces supongo que tengo que hacer algunas preguntas más.}
{120}{}{¿Qué problema hay con los exploradores?}
{121}{}{Tengo información que quizás te interese.}
{122}{Gen_5}{Cuando nos enteramos de lo de las caravanas desaparecidas mandamos a algunos
 exploradores al este y al norte. Los que fueron hacia el norte nunca regresaron. Sin embargo uno regresó
 del este. Nos habló de una veintena de seres extraños, todo musculosos y con los
 ojos inyectados. Los Ancianos no están moviendo un dedo, pero yo me estoy
 preparando de todas formas.}
{123}{}{Veinte no hacen un ejército. ¿Por qué te preocupas?}
{124}{}{Parece que el tipo se coció demasiado bajo el sol.}
{125}{}{Haré lo que pueda.}
{126}{}{¿Dijo en qué lugar del este?}
{127}{}{Tengo información que te puede interesar.}
{128}{Gen_6}{Puede que sean, o no, buenos exploradores, pero no
 dudes de la sinceridad de mis hombres. Podemos revocar tu estado de Iniciado en cualquier momento.}
{129}{}{Parece que tú me necesitas más de lo que yo te necesito a ti.}
{130}{}{Lo siento.}
{131}{Gen_7}{Eso es. Advertí a los Ancianos que introducir a un Forastero podría traer problemas. [Gritando a un lado] ¡Guardias! Aquí hay un Iniciado que necesita un poco de tranquilidad para refinar sus modales. }
{132}{Gen_8}{Eres un Forastero, pero espero que aprendas nuestras costumbres. Te estaré vigilando. Ahora haz tus preguntas. }
{133}{Gen_9}{Bien. ¿Algo más que preguntar? }
{134}{Gen_10}{En la profundidad de las montañas. No pudo ser más específico.}
{135}{}{Qué pena. ¿Puedo hacerte más preguntas?}
{136}{}{¿Cuánto hacia el norte?}
{137}{}{Adelante. }
{138}{Gen_11a}{Sí, dispara.}
{139}{Gen_11b}{Claro.}
{140}{Gen_11c}{Dispara.}
{141}{Gen_12}{Tengo la sensación que hay una pequeña fuerza
 en el este y una mucho mayor en el norte. Los Ancianos están hechos
 polvo porque ninguno de los exploradores ha regresado del norte. No puedo hacer nada salvo vigilar.}
{142}{}{Haré lo que pueda.}
{143}{}{¿Por qué no haces nada?}
{144}{}{Creo que esto es demasiado para mí. No cuentes conmigo.}
{145}{}{Tengo información sobre eso.}
{146}{Gen_13}{Bueno, los Mercaderes del Eje nos contaron que un puñado de caravanas
 desaparecieron cuando se dirigían al norte. Creo que hay un ejército en las montañas,
 pero los Ancianos no quieren actuar hasta que no estén seguros.}
{147}{}{¿Dónde desaparecieron?}
{148}{}{¿No eres tú el Anciano Mayor? ¿Por qué no haces nada?}
{149}{}{¿No hiciste nada?}
{150}{}{Tengo información sobre eso.}
{151}{Gen_14}{Por lo que yo sé, las caravanas desaparecieron por la
 cima meridional de las montañas al este. Imagino que los mercaderes del Eje podrán
 decirte más.}
{152}{}{Gracias. Tengo más preguntas, si te parece bien.}
{153}{}{Gracias, hablaré contigo más tarde.}
{154}{}{Tengo información sobre eso.}
{155}{Gen_15g}{Ya nos veremos, Iniciado. No eres tan malo... por ser un forastero.}
{156}{Gen_15n}{Adiós, Iniciado.}
{157}{Gen_15b}{¡Adiós!}
{158}{Gen_16}{Crecí muy aislado aquí. ¿Te puedes imaginar lo que es pasarse la vida en un lugar pequeño, y luego tener que salir al mundo? }
{159}{}{Bueno, de hecho...}
{160}{}{Entonces, supongo que estoy destinado a ser tu explorador.}
{161}{}{O sea, que como no salieron de esa, yo tengo que hacer el trabajo sucio. Olvídalo.}
{162}{Gen_17}{Entonces comprendes el problema. Para sobrevivir, necesitamos a alguien que conozca el exterior. Como tú. }
{163}{}{Vale, lo haré.}
{164}{}{Tengo mis propios problemas. Paso.}
{165}{Gen_18}{Pues... con lo que me temo que se avecina, no podemos perder el tiempo en nadie
 que no... contribuya. Así es que, o trabajas para nosotros o te vas de paseo.}
{166}{}{Bueno, si lo pones así, estoy con vosotros.}
{167}{}{Hace un buen día para pasear.}
{168}{Gen_19}{Tú verás. Espero que puedas vivir con ello.}
{169}{Gen_20}{¿Qué? Es lo que somos y por lo que vivimos. Es un ideal. A medida que
 pases más tiempo con nosotros lo comprenderás, con suerte.}
{170}{}{Sí, pero en realidad, ¿qué es lo que hacéis?}
{171}{}{No lo tengo muy claro.}
{172}{Gen_21}{Nuestro objetivo principal es sobrevivir. Los Escribas copian viejos planos de armas, o diseñan otros nuevos y los Caballeros fabrican las pistolas a partir de ellos. La mayoría de las armas salen de aquí.}
{173}{}{¿Vendéis las armas al Eje?}
{174}{}{¿Eso es todo lo que hacéis?}
{175}{}{Tiene sentido. Hay un par de cosas más que quisiera preguntarte.}
{176}{Gen_22}{Así es como nos abastecemos.}
{177}{}{Vale, lo he cogido. Hay un par de cosas más que quisiera preguntarte.}
{178}{}{Está bien, pero ahora me tengo que ir.}
{179}{}{Creo que no estoy muy seguro de esto.}
{180}{Gen_23}{¿Todo? Es muy importante. Es decisivo para nuestra supervivencia.}
{181}{}{Lo que sea. Necesito hacer más preguntas.}
{182}{}{Sí, bueno, es una idiotez.}
{183}{}{Vale, gracias, pero ahora me tengo que ir.}
{184}{Gen_26}{Entonces tienes que asegurarte de ello. Porque la inseguridad puede costarte la muerte.}
{185}{}{Cuanto más sepa, más seguro estaré.}
{186}{Gen_28}{Mira, ahora no tengo tiempo para una historia tan larga. Aquí. Todos nosotros crecimos creyendo esto. }
{187}{Gen_29n}{Hay rumores sobre las caravanas desaparecidas en el Eje, además del extraño ejército que se está preparando en las montañas del este. }
{188}{}{Vale.}
{189}{}{¿Qué ejército?}
{190}{}{¿Qué pasa con las caravanas desaparecidas?}
{191}{}{Tengo información sobre eso.}
{192}{Gen_29b}{No creo en los rumores. }
{193}{Gen_30}{Ahh... Hola otra vez, Iniciado. ¿Va todo bien? }
{194}{}{Bastante bien. ¿Puedo hacerte más preguntas?}
{195}{}{La verdad es que no me apetece nada.}
{196}{}{Sí, gracias, pero tengo que irme.}
{197}{Gen_32}{Siento que no estés acostumbrado a nosotros, pero podrías mostrar un poco de autodisciplina. }
{198}{}{Lo siento. ¿Puedo hacerte otra pregunta?}
{199}{}{¿Por qué? ¿Este sitio es una broma?}
{200}{}{Tengo que irme, adiós.}
{201}{Gen_34}{¿Qué diablos quieres ahora? }
{202}{}{Quiero saber por qué hay un idiota al mando.}
{203}{}{Necesito hacer algunas preguntas más.}
{204}{}{No importa, gracias.}
{205}{Gen_35}{¿Qué te pasa?}
{206}{}{Lo siento, la verdad es que no me pasaba nada.}
{207}{}{Las caravanas del Eje se las están llevando enormes mutantes verdes. Están reuniendo un ejército.}
{208}{}{Al norte de aquí hay un ejército enorme controlado por un tío que se hace llamar el Maestro.}
{209}{Gen_36}{¿Los has visto? Puede que esto haga reaccionar a los Ancianos.
 Voy a ponerme manos a la obra. ¡Gracias!}
{210}{Gen_38}{Eh... ¿qué está planeando hacer con su... ejército?}
{211}{}{Planea apoderarse de la Hermandad, del Eje, de Ciudad Vertedero... de todo el mundo.}
{212}{}{¿Cuánto estás dispuesto a pagar por esta información?}
{213}{Gen_39}{¡Por fin! ¡Así reaccionarán los Ancianos! Fortificaremos la Fortaleza y sorprenderemos a esos malditos mutantes.}
{214}{}{¡No! No lo entiendes. Transforman a la gente en mutantes para incorporarlos a su ejército.}
{215}{}{Vale.}
{216}{Gen_40}{¿Y?}
{217}{}{Cuando lleguen aquí serán imparables. Y tienen armas tan avanzadas como las vuestras. No tenéis ninguna oportunidad.}
{218}{}{Está bien, quizás atrincherarse sea lo correcto.}
{219}{Gen_41}{¿Cuál es tu alternativa?}
{220}{}{Ayúdame a atacar la base del Maestro. Sé donde está.}
{221}{Gen_42}{¡Ejem! No es un mal plan. Te diré una cosa, intentaré convencer a los Ancianos. No te lo garantizo, pero lo intentaré.}
{222}{Gen_43}{Entonces vete. Tengo cosas que hacer.}
{223}{Gen_44}{Bonitas prioridades y lealtades las tuyas.}
{224}{}{Lealtad a mí mismo. 500 en chapas del Eje. Lo tomas o lo dejas.}
{225}{}{Oh... vale, te lo diré. Está planeando apoderarse de todo y de todos.}
{226}{Gen_44a}{Trato hecho. Necesitamos esa información para salvar vidas.}
{227}{}{Es muy sencillo. Está transformando a humanos en mutantes y tiene armas avanzadas. Quiere apoderarse de todo.}
{228}{Gen_44b}{Pues, si lo consigue, espero que encuentres dónde usar tus chapas.}
{229}{Gen_45}{¡Caray! ¿Qué tal si lo dejamos en nada? Guardias, echad a este idiota. ¡Por Dios!
 Defenderemos la Hermandad sin tu maldita ayuda.}
{230}{Gen_46}{¿Qué crees que estás haciendo? ¡Deja eso! ¡Deja eso ahora mismo!}
{231}{Gen_47}{Eso es. ¡Guardias! ¡Llevaos a esta rata de cloaca!}
{232}{Gen_48}{¡Oye, oye, oye! Quietas esas manos. Para. ¡Para ahora mismo!}
{233}{Gen_49}{Como ya he dicho...}
{234}{Gen_50}{He dicho...}
{235}{Gen_51}{No estoy acostumbrado a repetir. Así que abre esas orejas.}
{236}{Gen_52}{Mira, ya te lo he dicho. No es culpa mía si no lo cogiste.}
{237}{Gen_52a}{Es donde estás. Si quieres la versión larga, ve a hablar con Vree.}
{238}{Gen_52b}{Mathia es mi ayudante.}
{239}{Gen_53}{Oh, es un buen chico, aunque quiera ser Escriba.}
{240}{Gen_54}{Vree es la Escriba jefe. Suele estar en la Biblioteca, le gusta mucho hablar.}
{241}{Gen_55}{Ahí guardamos las características y la historia de las armas.}
{242}{Gen_56}{Rhombus ha estado aquí mucho tiempo. Un poco seco, pero un pedazo de soldado.}
{243}{Gen_58}{Je, je, je. Un buen mozo gallardo. El trabajo del Anciano Mayor es mediar entre los Ancianos en las asambleas. Sabes, hace dos años me convencieron. Si lo hubiese sabido entonces...}
{244}{Gen_59}{Verás, hay cuatro de ellos y eso es en lo único en que se ponen de acuerdo. No pueden ponerse de acuerdo para saber si quieren mear, así que imagínate para ir a por un orinal.}
{245}{Gen_60}{Eso es lo que tú eres. Los Iniciados aprenden y se entrenan para convertirse en Escribas y Caballeros.}
{246}{Gen_61}{Los Escribas copian las características de las armas. Tenemos información desde la época de
 mi abuelo. A veces a un Escriba se le ocurre una nueva idea para un arma. Je, je, je. No pasa muy a menudo.
 Todos responden a Vree.}
{247}{Gen_62}{Los Caballeros hacen las armas. Cuando un Caballero es lo suficientemente bueno, puede convertirse en un Paladín y luego en Anciano y así. En este momento, Rhombus es el jefe de los Caballeros.}
{248}{Gen_63}{Los Paladines se encargan de toda la seguridad y de las actividades exteriores. Recuerdo cuando comerciaba con el Eje, cuando iba en misión de exploración. Aquellos sí que eran buenos tiempos.}
{249}{Gen_64}{El Eje está al sudeste. Comercian con comida y otras cosas a cambio de las armas que hacemos aquí. Si alguna vez te pasas por allí ve a hablar con Butch Harris.}
{250}{Gen_65}{Butch es el jefe de los Comerciantes de Ultramar. Es un poco asqueroso pero no es malo del todo. No como esos Mercaderes de Agua. Todos ellos son un maldito atajo de buitres.}
{251}{Gen_66}{Son nuestros colaboradores principales. No son de confianza, pero no son tan malos como el resto.}
{252}{Gen_67}{No puedes fiarte de ellos. Hace unos años, nos ofrecieron Agua a cambio de un montón de armas. Les dijimos que no, ¿y sabes lo que hicieron? ¡Mandaron ladrones para que robasen las armas! Los atrapamos pero los Ancianos votaron ir al Eje para dar una lección a los Mercaderes.}
{253}{Gen_68}{¿Holodiscos? ¿Ejem? Hace mucho que no veo uno de esos. }
{254}{Gen_69}{Vree lo tiene en algún sitio de la Biblioteca.}
{255}{Gen_70}{Roger Maxson, ¿eh? Él condujo a nuestra gente hasta aquí durante el Gran Éxodo y fundó la Hermandad a partir de la nada. Todo un líder.}
{256}{Gen_71}{Eso fue cuando mi abuelo, Roger Maxson, condujo a sus soldados hasta aquí y formó la Hermandad. Nunca mencionó de dónde vinieron, pero eso no importa, porque... bueno, este es nuestro hogar ahora.}
{257}{Gen_72}{Creo que se está reuniendo un ejército al norte y en las montañas del este, pero no tengo ninguna prueba de ello. Los Ancianos ni siquiera quieren escucharme.}
{258}{Gen_73}{Si me preguntas te diré que son un atajo de religiosos fanáticos. Creo que su iglesia principal está en el Cementerio.}
{259}{Gen_75}{No sé mucho. Hay unas cuantas bandas por ahí, además de Adytum y los Niños de la Catedral. No mucho más. Está bastante desolado.}
{260}{Gen_76}{No hay mucho que contar. Nunca me he topado con ninguna de ellas. Aunque he oído que son un problema para la gente de Adytum.}
{261}{Gen_77}{Es un campamento en el Cementerio. Fui... oh... hace mucho tiempo. Era una misión de exploración para los Ancianos.}
{262}{Gen_78}{Oh. Otro rumor estúpido. Unos dicen que es un monstruo enorme con colmillos y otros que es un vampiro.}
{263}{Gen_79}{No tengo ni la más remota idea.}
{264}{Gen_80}{¿Qué has dicho? No. Creo que nunca lo he oído.}
{265}{Gen_81a}{Que me muera si lo sé.}
{266}{}{¿Te sorprende verme? ¿Y dejarte a ti todo lo divertido?}
{267}{}{¿Cómo convenciste a los Ancianos?}
{268}{Gen_82a}{Oh, no fue difícil. Les expliqué la situación con calma. Y, ¡bingo!, aquí estamos. Vamos allá, colega.}
{269}{Gen_83}{¿Qué estás haciendo aquí? Esto es para Ancianos.}
{270}{}{Lo siento, me iré.}
{271}{}{Me da igual, me quedo.}
{272}{Gen_84}{Bien y cierra la puerta cuando salgas.}
{273}{Gen_84a}{Te aviso, no te metas en esto.}
{274}{Gen_85}{¡Ja! Olvidas que yo solía enseñar esto.}
{275}{Gen_86}{A pesar de los rumores, queremos soldados con cerebro.}
{276}{Gen_87}{Te sugiero que hables de eso con mi ayudante, Mathia.}


{300}{}{¿Quizás tú me lo puedas decir? Parece que todo el mundo tiene los nervios de punta. Es como si
 os prepararais para la guerra, pero que nadie supiera contra quien.}
{301}{}{¿Tienes alguna pista sobre el origen de la desaparición de las caravanas?}
{302}{}{Exploraré la zona norte y te comunicaré lo que descubra.}
{303}{}{Por 500 chapas, comprobaré lo que pasa allí arriba.}
{304}{}{Por 1.000 chapas, comprobaré lo que pasa por el norte.}
{305}{}{Todavía no sé con seguridad si quiero implicarme ahora.}
{306}{}{¿Sería posible para mí hacerme con mejores armas?}
{307}{}{Primero unas preguntitas.}
{308}{}{No, te veré cuando averigüe que está pasando allí arriba.}
{309}{}{Vale, adiós.}
{310}{}{¿Cómo sabes que tus exploradores no desertaron?}
{311}{}{Creo que he tropezado con esas criaturas que describes. No son moco
 de pavo.}
{312}{}{Perdóname, por favor. ¿Según tú, cuál es la causa de la desaparición?}
{313}{}{Adelante. Revócame. A ver si me importa.}
{314}{}{Lo siento, pero me parece demasiado arriesgado subir allí ahora.}
{315}{}{Está bien, iré, pero... ¿puedo coger algunas armas antes de marcharme?}
{316}{}{Vale, lo haré por 1.000 chapas.}
{317}{}{Lo tomas o lo dejas.}
{318}{}{No importa.}
{319}{}{Vale, vale, lo haré gratis.}
{320}{}{Muy bien, te veré cuando vuelva.}
{321}{}{He encontrado pruebas que demuestran que este ejército es el que provoca la desaparición
 de las caravanas. Es un ejército de mutantes. Tenéis motivos para preocuparos. Parecen ser
 formidables.}
{322}{}{Parece que alguien debería ir allí arriba para comprobarlo.}
{323}{}{Hace falta algo más que una corazonada para que arriesgue mi vida
 subiéndome allí.}
{324}{}{Considero que mi vida es bastante prioritaria.}
{325}{}{Creo que no soy capaz de asumir esta tarea.}
{326}{}{Sólo soy leal a una persona.}
{327}{}{Puedo.}
{328}{}{¿Duh?}
{329}{}{Parece que todo el mundo tiene los nervios de punta. Es como si
 os preparaseis para la guerra, pero que nadie supiese contra quien.}
{330}{}{Necesito hablar contigo de la desaparición de las caravanas. ¿Tienes alguna opinión
 sobre el asunto?}
{331}{}{No importa.}
{332}{}{Necesito hacerte unas preguntas.}
{333}{}{¿Duh?}
{334}{}{Tengo información sobre la zona situada al norte de aquí.}
{335}{}{¿Puedo hacerte unas preguntas?}
{336}{}{No importa.}
{337}{}{Perdona, la verdad es que no tenía nada.}
{338}{}{Vi su base. Está llena de mutantes.}
{339}{}{Vi la base mutante del norte. Siguen a un líder al que llaman el Maestro.}
{340}{}{No puedes jugar a defenderte con ésto Maxson.}
{341}{}{Es evidente que hay que hacer algo. Lo mejor sería atacar a los mutantes antes de que ellos nos
 ataquen a nosotros. Esta vez necesitamos que los Ancianos se pongan de nuestra parte.}
{342}{}{No estoy seguro de lo que debemos hacer ahora mismo. Déjame recoger más información y luego volveré.}
{343}{}{Planea hacerse con todos los asentamientos humanos que pueda.}
{344}{}{¿Qué puedes contarme de la historia de la Hermandad?}
{345}{}{¿Cuál es el principal objetivo de la Hermandad?}
{346}{}{¿Quiénes son los Ancianos?}
{347}{}{¿Sabes algo de la Garra Mortal?}
{348}{}{No importa.}
{349}{}{¿Puedo hacerte otra pregunta?}
{350}{}{Gracias.}
{351}{}{Ganas }
{352}{}{ puntos de experiencia por explorar el área norte.}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{353}{Gen_3}{Un Iniciado no nacido aquí. Eres el primer Forastero al que hemos dejado unirse desde
 hace mucho, mucho tiempo. Casi veinte años.}
{354}{Gen_3}{Una Iniciada no nacida aquí. Eres la primera Forastera a la que hemos dejado unirse desde
 hace mucho, mucho tiempo. Casi veinte años.}
{355}{Gen_6}{Puede que sean, o no, buenos exploradores, pero no dudes de
 la sinceridad de mis hombres. Podemos revocar tu estado de Iniciado en cualquier momento.}
{356}{Gen_6}{Puede que sean, o no, buenos exploradores, pero no dudes de
 la sinceridad de mis hombres. Podemos revocar tu estado de Iniciada en cualquier momento.}
{357}{Gen_15n}{Adiós, Iniciado.}
{358}{Gen_15n}{Adiós, Iniciada.}
{359}{Gen_30}{Ahh... Hola otra vez, Iniciado. ¿Todo va bien? }
{360}{Gen_30}{Ahh... Hola otra vez, Iniciada. ¿Todo va bien? }

{400}{}{He estado en la base Mutante del norte. Digamos que ya no son una
 amenaza.}


# General Maxson Tell-Me-Abouts generic responses
{980}{Gen_79}{No tengo ni la más remota idea.}
{981}{Gen_80}{¿Qué has dicho? No. Creo que nunca lo había oído.}
{982}{Gen_81a}{Que me muera si lo sé.}


#
# General Maxson Tell-Me-Abouts
#

{1000}{}{Hermandad}
{1001}{}{Mathia}
{1002}{}{Cabbot}
{1003}{}{Vree}
{1004}{}{Biblioteca}
{1005}{}{Rhombus}
{1006}{}{Anciano}
{1007}{}{Ancianos}
{1008}{}{Iniciados}
{1009}{}{Escribas}
{1010}{}{Caballeros}
{1011}{}{Paladines}
{1012}{}{Eje}
{1013}{}{Butch}
{1014}{}{Comerciantes}
{1015}{}{Mercaderes}
{1016}{}{Discos}
{1017}{}{Reproductor}
{1018}{}{Roger}
{1019}{}{Éxodo}
{1020}{}{Ejército}
{1021}{}{Catedral}
{1022}{}{Ángeles}
{1023}{}{Bandas}
{1024}{}{Adytum}
{1025}{}{Garra}
{1026}{}{Harris}
{1027}{}{Maxson}
{1028}{}{Angel}
{1029}{}{Cementerio}
{1030}{}{Maestro}
{1031}{}{Guerra}
{1032}{}{Caravanas}
{1033}{}{Chip}

{1100}{Gen_52a}{Aquí estás. Si quieres la versión larga, vete a hablar con Vree.}
{1101}{Gen_52b}{Mathia es mi ayudante.}
{1102}{Gen_53}{Oh, es un buen chico, aunque quiera ser Escriba.}
{1103}{Gen_54}{Vree es la Escriba jefe. Suele estar en la Biblioteca, le gusta mucho hablar. }
{1104}{Gen_55}{Ahí guardamos las características y la historia de las armas.}
{1105}{Gen_56}{Rhombus ha estado aquí mucho tiempo. Un poco seco, pero un pedazo de soldado.}
{1106}{Gen_58}{Je, je, je. Un buen mozo gallardo. El trabajo del Anciano Mayor es mediar entre los Ancianos en las asambleas. Sabes, hace dos años me convencieron. Si lo hubiese sabido entonces...}
{1107}{Gen_59}{Verás, hay cuatro de ellos y eso es en lo único en que se ponen de acuerdo. No pueden ponerse de acuerdo para saber si quieren mear, así que imagínate para ir a por un orinal.}
{1108}{Gen_60}{Eso es lo que tú eres. Los Iniciados aprenden y se entrenan para convertirse en Escribas y Caballeros.}
{1109}{Gen_61}{Los Escribas copian las características de las armas. Tenemos información desde la época de
 mi abuelo. A veces a un Escriba se le ocurre una nueva idea para un arma. Je, je, je. No pasa muy a menudo.
 Todos responden a Vree.}
{1110}{Gen_62}{Los Caballeros hacen las armas. Cuando un Caballero es lo suficientemente bueno, puede convertirse en un Paladín y luego en Anciano y así. En este momento, Rhombus es el jefe de los Caballeros.}
{1111}{Gen_63}{Los Paladines se encargan de toda la seguridad y de las actividades exteriores. Recuerdo cuando comerciaba con el Eje, cuando iba en misión de exploración. Aquellos sí eran buenos tiempos.}
{1112}{Gen_64}{El Eje está al sudeste. Comercian con comida y otras cosas a cambio de las armas que hacemos aquí. Si alguna vez pasas por allí ve a hablar con Butch Harris.}
{1113}{Gen_65}{Butch es el jefe de los Comerciantes de Ultramar. Es un poco zalamero, pero no es malo del todo. No como esos Mercaderes de Agua. Maldito atajo de buitres, todos ellos.}
{1114}{Gen_66}{Son con los que comerciamos principalmente. No de toda confianza, pero no tan malos como el resto. }
{1115}{Gen_67}{Quieres saber sobre los Mercaderes de Agua. Je, je, je. Bueno, no puedes fiarte de ellos.
 Hace unos años, nos ofrecieron Agua a cambio de un montón de armas. Pues les dijimos que no, ¿y sabes lo que hicieron? ¡Mandaron ladrones para que robasen las armas! Los atrapamos pero los Ancianos votaron ir al Eje para dar una lección a los Mercaderes.}
{1116}{Gen_68}{¿Holodiscos? ¿Mmm? Hace mucho que no veo uno de esos. }
{1117}{Gen_69}{Vree lo tiene en algún sitio de la Biblioteca.}
{1118}{Gen_70}{Roger Maxson, ¿eh? Él condujo a nuestra gente hasta aquí durante el Gran Éxodo y fundó la Hermandad a partir de la nada. Todo un líder.}
{1119}{Gen_71}{Eso fue cuando mi abuelo, Roger Maxson, condujo a sus soldados hasta aquí y formó la Hermandad. Nunca mencionó de dónde vinieron, pero eso no importa, porque... bueno, este es nuestro hogar ahora.}
{1120}{Gen_72}{Creo que se está reuniendo un ejército al norte y en las montañas del este, pero no tengo pruebas que lo demuestren. Los Ancianos ni siquiera quieren escucharme. }
{1121}{Gen_73}{Un atajo de fanáticos religiosos, ya que me lo preguntas. Creo que su iglesia principal está en el Cementerio.}
{1122}{Gen_75}{No sé mucho. Hay unas cuantas bandas por ahí, además de Adytum y los Niños de la Catedral. No mucho más. Está bastante desolado.}
{1123}{Gen_76}{No hay mucho que contar. Nunca me he topado con ninguna de ellas. Aunque he oído que son un problema para la gente de Adytum.}
{1124}{Gen_77}{Es un campamento en el Cementerio. Fui... oh... hace mucho tiempo. Era una misión de exploración para los Ancianos.}
{1125}{Gen_78}{Oh. Otro rumor estúpido. Unos dicen que es un monstruo enorme con colmillos y otros que es un vampiro.}
{1126}{Gen_65}{Butch es el jefe de los Comerciantes de Ultramar. Es un poco zalamero, pero no es malo del todo. No como esos Mercaderes de Agua. Todos ellos son un maldito atajo de buitres.}
{1127}{Gen_70}{Roger Maxson, ¿eh? Él condujo a nuestra gente hasta aquí durante el Gran Éxodo y fundó la Hermandad a partir de la nada. Todo un líder.}
{1128}{Gen_75}{No sé mucho. Hay unas cuantas bandas por ahí, además de Adytum y los Niños de la Catedral. No mucho más. Está bastante desolado.}
{1129}{Gen_75}{No sé mucho. Hay unas cuantas bandas por ahí, además de Adytum y los Niños de la Catedral. No mucho más. Está bastante desolado.}
{1130}{Gen_80}{¿Qué has dicho? No. Creo que nunca lo había oído.}
{1131}{Gen_71}{Eso fue cuando mi abuelo, Roger Maxson, condujo a sus soldados hasta aquí y formó la Hermandad. Nunca mencionó de dónde vinieron, pero eso no importa, porque... bueno, este es nuestro hogar ahora.}
{1132}{Gen_65}{Butch es el jefe de los Comerciantes de Ultramar. Es un poco zalamero, pero no es malo del todo. No como esos Mercaderes de Agua. Todos ellos son un maldito atajo de buitres.}
{1133}{Gen_81a}{Que me muera si lo sé.}