{100}{}{La puerta está cerrada. Se necesita un código de seguridad para abrirla.}
{101}{}{Introduces el código de la cinta y abres la puerta.}
{102}{}{La puerta no está cerrada.}
{103}{}{Descubres el código de seguridad y abres la puerta.}
{104}{}{No puedes abrir la puerta.}
{105}{}{No puedes abrir la puerta. Sería más fácil si
 utilizaras un juego de herramientas de cerrajería electrónica.}
{106}{}{La explosión es fuerte, pero ni siquiera ha dañado ni marcado
 la puerta.}
