{100}{}{Apagado}
{101}{}{Quedan: }
{102}{}{ segundos.}
{103}{}{Aquí es donde deberías darte por muerto.}
{104}{}{Apagado}
{105}{}{Encendido}
{106}{}{Apagado}
{107}{}{Quedan: }
{108}{}{ segundos.}
{109}{}{Aquí es donde deberías darte por muerto.}
{110}{}{Quedan: }
{111}{}{ segundos.}
{112}{}{Aquí es donde deberías darte por muerto.}
