{100}{}{Estás viendo a Miles, el químico de Adytum.}
{101}{}{Estás viendo a un hombre delgado con una bata blanca.}
{102}{}{No creo que nos conozcamos. Soy Miles. ¿Qué puedo hacer por ti?}
{103}{}{Sólo estoy mirando, gracias.}
{104}{}{Con esa bata pareces un científico. ¿Qué estás estudiando?}
{105}{}{¿Um?}
{106}{}{Bueno, disfruta de tu estancia en nuestra pequeña ciudad.}
{107}{}{Soy químico. Hago principalmente cartuchos y pólvora y así
 podemos aprovechar los casquillos de las balas. Pero también soy aficionado
 a otros productos químicos.}
{108}{}{Así que fabricas balas para Adytum.}
{109}{}{¿Dónde consigues el azufre, el nitrato de potasio y los demás productos químicos?}
{110}{}{¿Con qué otros productos químicos trabajas?}
{111}{}{Gracias por la información.}
{112}{}{Sí, aunque Herreriano es el que en realidad funde las balas.
 Yo sólo relleno los casquillos.}
{113}{}{Pero los mercaderes del Eje sacan beneficios contigo y la ciudad.}
{114}{}{¡Es difícil encontrar a alguien que aprecie la química!
 Pero para contestar a tu pregunta, los mercaderes me facilitan una parte de los productos. Lo demás lo fabrico yo o los encuentro en esta zona. Por ejemplo, el estiércol
 de los Brahmins son una buena fuente de productos, así como algunas especies de hongos
 que me dedico a cultivar.}
{115}{}{Bueno, he intentado conseguir ácidos fuertes para que Herreriano grabe al aguafuerte. También he intentado fabricar tintes y colorantes permanentes. Pero sin acceso a los tintes naturales es bastante difícil.}
{116}{}{Cuando quieras.}
{117}{}{Oh, querido. Me temo que no puedo ayudarte.}
{118}{}{Hola otra vez. ¿Puedo ayudarte?}
{119}{}{Sí, bueno, de algo tenemos que vivir. Ya que las granjas hidropónicas no funcionan, tenemos que comprar la comida a los mercaderes y es lo único que podemos vender.}
{120}{}{Puedo intentar conseguir las piezas que necesitas para las granjas hidropónicas.}
{121}{}{Oh. ¡Qué pena!}
{122}{}{¿De verdad? ¡Sería maravilloso! Sólo nos faltan un par de piezas pero seguro que si consigues las piezas adecuadas podremos ser autosuficientes. Quizás te pueda ayudar Sammael.}
{123}{}{¿Aún no has encontrado las piezas?}
{124}{}{Sí, aquí están.}
{125}{}{Todavía no, ¿a quién dijiste que debía preguntarle sobre ellas?}
{126}{}{Tienes que hablar con Sammael. Durante el día, lo encontrarás en
 una tienda ahí abajo en las granjas.}
{127}{}{[Miles inspecciona las piezas] Son ésas, pero
 parece que Herreriano tendrá que hacerles algunos cambios.
 ¿Puedes llevárselas?}
{128}{}{Tengo otras cosas que hacer ahora. ¿Puedes hacerlo tú?}
{129}{}{Claro, volveré cuando las haya arreglado.}
{130}{}{Claro, te agradezco que las hayas encontrados para nosotros.}
{131}{}{Y...}
{132}{}{No es problema.}
{133}{}{Oh. Casi se me olvida. Aquí tienes esto por si te sirve de ayuda.
 [Miles te da algunas chapas y algunos medicamentos.]}
{134}{}{¿Pudiste llevarle las piezas a Herreriano?}
{135}{}{[Miles coge las piezas arregladas.] Parece que Herreriano ha hecho un buen
 trabajo.
 Gracias por la ayuda y aquí tienes esto por si te sirve de ayuda.}
{136}{}{[Miles te da algunas chapas y algunos medicamentos.]}
{137}{}{Si vuelves a pasar por aquí, puede que
 necesites vernos a Herreriano y a mí.
 Te podremos ayudar arreglando tu equipo.
 Herreriano puede hacer maravillas con algunas armas y yo puedo arreglar ciertos tipos de armadura.}
{138}{}{Parece que has encontrado una Armadura de Energía. He oído hablar de un proceso químico que se puede emplear para endurecer la
 superficie de la armadura. Sin embargo, he perdido la información que me
 dará las últimas pistas para conseguir la fórmula y los reactivos necesarios.
 También me he enterado de que la Bibliotecaria del Eje, la señora Stapleton,
 tiene algunos periódicos y libros que podrían serme útiles. Si
 puedes conseguir algunos, podría hacer una prueba con tu armadura.}
{139}{}{Me parece bien. Iré a hablar con la señora Stapleton.}
{140}{}{Tengo mejores cosas que hacer que buscarte cosas.}
{141}{}{Bueno, si cambias de opinión, ve a ver a la señora Stapleton
 y luego vuelve aquí.}
{142}{}{¿Todavía no has podido ir al Eje a visitar a la señora Stapleton?}
{143}{}{Sí, aquí están los libros.}
{144}{}{Todavía no.}
{145}{}{[Miles te quita los libros y empieza a hojearlos.]
 Mmm...
 Sí, Mmm. [Murmura para sí mismo unos minutos más.]
 Bueno, creo que puedo imaginármelo, pero la fusión tardará un día completo. ¿Te parece bien?}
{146}{}{Perfecto.}
{147}{}{Lo siento, no tengo tiempo.}
{148}{}{Bueno, cuando tengas tiempo, vuelve y trataremos tu
 armadura.}
{149}{}{[Miles te coge la armadura.]}
{150}{}{[Miles te devuelve la armadura; parece que brilla un poco más
 que antes.] Bueno, ¡creo que funciona! Espero que te
 ayude.}
{151}{}{¿Qué le pasó a tu Armadura de Energía? Sólo puedo ayudarte
 si tienes una.}
{152}{}{Encantado de verte, pero ahora mismo estoy en plena investigación.}
{153}{}{No puedo hacer nada con ese tipo de armaduras. Lo siento.}
