{100}{}{Estás viendo a un hombre destrozado.}
{101}{}{¡Gracias extranjero! No sé cuántas semanas, quizás
 meses, me ha tenido aquí
 esta gente. Te agradezco mucho tu ayuda y seguro que la Hermandad del Acero también lo estará.}
{102}{}{¿Hermandad del Acero?}
{103}{}{Bien, estoy contento de haber podido ayudar en algo.}
{104}{}{¿Estarás bien?}
{105}{}{Soy de la Hermandad. He estado buscándote.}
{106}{}{De nada. Adiós.}
{107}{}{Uh.}
{108}{}{¿No has oído hablar de nosotros? Estoy
 realmente sorprendido. No saldrás del Eje muy a menudo. Deberías hacerlo. Estamos al noroeste de aquí, en la ladera oeste de la montaña.}
{109}{}{Agradezco tu ayuda pero, ¿por qué intentas mentirme? ¿No sabes
 que conozco a todos los miembros de nuestro orden?}
{110}{}{Talus me envió.}
{111}{}{Bueno, tú no me conoces porque me acabo de incorporar.}
{112}{}{Evidentemente no sabes de lo que estás hablando.}
{113}{}{¡Gracias otra vez! Si te pasas por la Hermandad, te agradecería que le dijeses a Talus que estoy bien. Estoy seguro de que está preocupado.
 Adiós y cuídate.}
{114}{}{Oh, ahora estaré bien, gracias. Tengo algunos amigos aquí con los que me puedo quedar hasta que recupere las
 fuerzas. Intentaré escribir a la Hermandad para que sepan que estoy vivo. Gracias. Adiós}
{115}{}{Como... Oh, lo siento. Debes haber superado esa "prueba" que los Ancianos crearon. Se me olvidaba completamente. Bueno, te estoy todavía más agradecido. Menos mal que no abandonaste. Mi vida pudo haber estado en peligro en cualquier momento. Habrías tardado un rato en encontrarme. Esta ciudad es enorme. Tienes que haber superado muchísimos obstáculos.}
{116}{}{Bueno, ya sabes... Soy así de bueno.}
{117}{}{De hecho fue bastante fácil. Talus sabía dónde habías ido.}
{118}{}{Creo que tuve suerte.}
{119}{}{Bueno, de nada. Estoy contento de haberte encontrado.}
{120}{}{Oh... Bueno, todavía te estoy muy agradecido.}
{121}{}{Eso creo yo también. Lo que hiciste fue un trabajo de artesanía.}
{122}{}{Bueno, estoy contento de haberte servido de ayuda.}
{123}{}{¿Estarás bien?}
{124}{}{Bueno, gracias otra vez. Voy a quedarme con un amigo hasta que recupere las fuerzas. Por cierto,
 echaré un vistazo por aquí. He oído a mis huéspedes hablar del Gremio de los Ladrones. Supongo que estamos cerca
 de su territorio o algo así. Me parece que pensaban mudarse a otro sitio por ese motivo.
 Adiós.}
{125}{}{Bien, estoy contento de que la suerte te haya durado. No he oído nada bueno sobre la Ciudad Antigua. Los yonquis son terribles; y creo que hay
 algo peor aún.}
{126}{}{Sea lo que sea, estoy agradecido porque soy libre otra vez. No echo de menos la tortura.}
{127}{}{No. De verdad. Me envió Talus.}
{128}{}{Bueno, estoy contento de haber servido de ayuda.}
{129}{}{¿Estarás bien?}
{130}{}{Quizás no. Me cuesta recordar algunas cosas. Creo
 que fue algo que me dieron de comer.}
{131}{}{No. De verdad. Me envió Talus.}
{132}{}{Bueno, estoy contento de haber servido de ayuda.}
{133}{}{¿Estarás bien?}
{134}{}{Hola otra vez.}
{135}{}{Me marcharé pronto. Sólo estoy recuperando las fuerzas.}
{136}{}{Gracias otra vez.}

## Tell me abouts
{1000}{}{Hermandad}
{1001}{}{Acero}
{1002}{}{Talus}

## Answers
{1100}{}{La única salvación para este planeta torturado y sus habitantes. Sin ellos, la humanidad perecerá.}
{1101}{}{La única salvación que este torturado planeta y sus pueblos tienen. Sin ellos, la humanidad seguramente perecerá.}
{1102}{}{Él es mi mentor y un hombre fantástico. Estoy
 deseando verlo de nuevo.}