{100}{}{Se te erizan los pelos de la nuca. Te da una sensación desde
 el pasillo. El pánico aumenta cuando descubres una masa de carne delante de ti...
 ves trozos humanos en la pared. Lo peor es que se está moviendo a la vez
 que te llama.}
{101}{}{Tu nariz comienza a sangrar. Oyes voces en tu interior. Te están
 llamando. La oscuridad nubla tu vista durante un momento, pero te
 recuperas.}
{102}{}{Una voz te llama. Giras la cabeza y ves la imagen de una
 antigua amiga, obviamente muerta. De su mandíbula caen gusanos, en tanto que tu
 dolor de cabeza aumenta.}
{103}{}{Cada vez te cuesta avanzar. Parece que tus pies están pegados al
 suelo. Miras hacia abajo y ves que el suelo te está atrapando la pierna.
 Unos dientes te muerden las rodillas. Tu dolor de cabeza empeora.}
{104}{}{Algo llama tu atención, un movimiento rápido desde el
 techo y luego una astilla de hueso atraviesa tu ojo. ¡Con ella te vienen
 los pensamientos de los muertos y los ultrajados!}
{105}{}{Tu dolor de cabeza va creciendo. Sientes los pecados de otras personas
 atravesar tu alma. Y todo empeora cuando tus pecados les responden. Frenéticamente,
 luchan dentro de tu espíritu y de paso destruyen tu personalidad.}
{106}{}{Tu cabeza está llena de los pensamientos intrusos de otras personas. El
 dolor crece y crece y de repente, como si nunca hubiera existido, desaparece.
 Te caes al suelo y lloras. Pero sientes que algo no va bien.}
{107}{}{Tu dolor de cabeza ha disminuido. Los efectos de
 este extraño pasillo ya no son tan fuertes.}