{100}{}{Estás viendo a un prisionero mugriento y desaliñado.}
{101}{}{Un prisionero de la segunda celda no se parece a los otros. Está de
 pie y te mira fijamente a los ojos.}
{102}{}{El prisionero mira fijamente a la pared.}
{103}{}{El prisionero ignora tus intentos de charlar.}
{104}{}{Te mira desafiante un momento y luego se da media vuelta.}
{105}{}{Te mira un momento y luego se da la vuelta.}
{106}{}{No obtienes respuesta.}
{107}{}{¡Somos libres! ¡Somos libres!}
{108}{}{Me resultas asqueroso. No me hables.}
{109}{}{¡Vete!}
{110}{}{No tienes derecho a hablarme de esa manera.}
{111}{}{No lo entiendes. Estoy aquí para liberarte.}
{112}{}{No me molestes.}
{113}{}{No tengo derechos y debería preocuparme menos. Vete y déjanos en paz.}
{114}{}{Me niego a darte cualquier información. Déjame solo.}
{115}{}{!!UM!!}
{116}{}{Estoy aquí para liberarte, de veras. Soy un humano normal.}
{117}{}{Si lo quieres así, de acuerdo. Adiós.}
{118}{}{¿No recuerdas que ya lo intentaste la semana pasada? No caí en
 la trampa y tampoco lo pienso hacer ahora.}
{119}{}{¿Qué? ¿No hay una capucha para camuflarse? Tu aspecto de traidor es demasiado evidente.}
{120}{}{Estoy aquí para liberarte.}
{121}{}{Entonces adiós.}
{122}{}{Eres cruel. Déjanos en paz.}
{123}{}{No pondré en peligro a mi gente. No puedes obligar a un hombre a
 traicionarse a sí mismo. Sólo puedes obligarle a morir.}
{124}{}{Realmente no lo entiendes. Soy un ser humano y estoy aquí para rescatarte.}
{125}{}{Ni siquiera tengo que forzarte para que te pudras en el infierno. Lo haces muy
 bien tú solito.}
{126}{}{Aún me estás molestando.}
{127}{}{De la boca de un hombre salen palabras de víbora.}
{128}{}{Vale. Podía imaginarlo. Vete y déjanos tranquilos.}
{200}{}{El prisionero está sucio y cansado. Lleva un collar brillante y nuevo
 alrededor del cuello.}
{201}{}{El prisionero te devuelve la mirada fijamente. Observas un
 collar alrededor de su cuello.}
{300}{}{Hay un letrero en la pared que pone: "Prohibida la entrada. Zona de Seguridad.
 ¡Sólo Guardias!"}
{301}{}{Ganas }
{302}{}{ puntos de experiencia por sacar de la miseria a los prisioneros.}