{100}{}{Te sientes incapaz de rebuscar entre los trozos que ves.}
{101}{}{La nevera está repleta de trocitos de órganos y carne humana.}
{102}{}{Los pedazos que están en la nevera están cortados en trocitos y congeladas.
 Estas partes de cuerpo no podrán ser transplantadas a nadie.}
{103}{}{La nevera está llena de partes de un cuerpo humano.}
{104}{}{La nevera está repleta de partes de un cuerpo humano cortadas en trocitos
 y conservadas en bolsas de hielo. Muy extraño.}
