{100}{}{Estás viendo a Doc Mórbid.}
{101}{}{Soy Doc Mórbid, ¿puedo ayudarte?}
{102}{}{Sí, necesito ayuda.}
{103}{}{Necesito asistencia médica.}
{104}{}{Hoy no.}
{105}{}{No.}
{106}{}{Sí.}
{107}{}{Vale entonces. Vuelve.}
{108}{}{Si hoy no, quizás en un futuro próximo.}
{109}{}{Espero que no. Adiós.}
{110}{}{Tendremos que verlo. Pero en cualquier caso, no creo.}
{111}{}{Umm, echemos un vistazo.}
{112}{}{Pareces gozar de perfecta salud. Serán 10 chapas
 por el reconocimiento.}
{113}{}{¿Diez chapas por decirme eso? Estás de broma.}
{114}{}{Aquí tienes. Coge tus chapas.}
{115}{}{Nunca bromeo. Sobre todo cuando puede tratarse de traumas físicos.
 Me pagarás o tendré que recurrir a otras formas de
 compensación mucho más dolorosas que el pago de mis tarifas.}
{116}{}{Vale, aquí tienes tus chapas.}
{117}{}{Olvídame. Me voy.}
{118}{}{Recibirás lo que mereces. Cougar, Flash, enseñadle a nuestro "paciente"
 el laboratorio.}
{119}{}{Gracias por venir. Vuelve otro día.}
{120}{}{No tienes chapas suficientes. Tengo una manera especial
 de tratar a los morosos. Flash, Cougar
 llevad al laboratorio a nuestra nueva fuente de ingresos
 para que lo procesemos.}
{121}{}{Aquí tengo los resultados del análisis.}
{122}{}{Estás }
{123}{}{El costo total será de }
{124}{}{ chapas. El pago se efectúa antes
 del tratamiento. Sin excepción. ¿Pagarás?}
{125}{}{Sí, lo haré.}
{126}{}{No, no tengo las chapas. ¿Te fías de mí?}
{127}{}{No.}
{128}{}{Sí.}
{129}{}{No.}
{130}{}{No. No me fío de nadie, de nadie, por ninguna cantidad de chapas.
 Vete, pordiosero asqueroso.}
{131}{}{Es tu vida. Adiós.}
{132}{}{Excelente. Empecemos. Esto te dolerá un poco...}
{133}{}{Ya está. ¡Vuelve otro día!}
{134}{}{Oh, has vuelto pronto. ¿En qué puedo ayudarte?}
{135}{}{Necesito curarme.}
{136}{}{Nada, sólo quería charlar un rato.}
{137}{}{¡Ahh!}
{138}{}{Hazlo en otro sitio. Estoy muy ocupado.}
{139}{}{Ummm. No me gusta tu aspecto, forastero. Pero, ¿en qué
 puedo ayudarte? No trato mal a los pacientes que pagan.}
{140}{}{Necesito ayuda.}
{141}{}{Sí, necesito ayuda.}
{142}{}{Necesito asistencia médica.}
{143}{}{Ayuda.}
{144}{}{Oh, Eres tú otra vez. Me gusta tu estilo, aunque no me gustas
 tú. ¿En qué puedo ayudarte ahora?}
{145}{}{Necesito curarme.}
{146}{}{Nada, sólo quería hablar un rato.}
{147}{}{¡Ayy!}
{148}{}{Oh, ¡es un paciente! ¿En qué puedo ayudarte?}
{149}{}{Necesito curarme.}
{150}{}{Nada, sólo quería hablar un rato.}
{151}{}{Pareces emocionado por verme. ¿Por qué?}
{152}{}{¡Ayy!}
{153}{}{Mi consulta ha ido a peor últimamente. Me alegra ver a un
 paciente en estos días tan duros. Además, aprecio tu compañía, por supuesto.}
{154}{}{Excelente. Necesito curarme.}
{155}{}{¿Por qué ha ido tu consulta a peor?}
{156}{}{Por supuesto. Lo entiendo. Que pases un buen día.}
{157}{}{Bien, si necesitas cualquier cosa, pásate por aquí. ¡Soy el mejor!}
{158}{}{Por si no lo has notado, hay mucha competencia.}
{159}{}{ Quejarse a Killian no solucionará nada. No tiene nada
 que objetar a los que acaban de llegar.}
{160}{}{ Esos malditos niños se han mudado a la puerta de
 al lado y se han llevado a la mayoría de mis pacientes. No me gustan nada, pero no
 puedo bajar mis precios para competir. Me limito a ofrecer un servicio mejor.}
{161}{}{Ahh, necesito curarme.}
{162}{}{Mmm, precios más bajos, interesante. Gracias.}
{163}{}{Ahh, un antiguo paciente. ¡Cómo se agradece! ¿En qué
 puedo ayudarte?}
{164}{}{Necesito curarme.}
{165}{}{Nada, sólo quería charlar un rato.}
{166}{}{¡Ayy!}
{167}{}{Tú de nuevo. Espero que tengas un buen motivo para molestarme...}
{168}{}{¡Me estoy muriendo! ¡Ayúdame!}
{169}{}{Lamento molestarte, pero necesito ayuda.}
{170}{}{¡Ay!}
{171}{}{No me hace gracia tu tipo de humor. Vete y déjame volver a mi trabajo.}
{172}{}{Umm. Bueno, a mí me pareces sano. Puede que necesites descansar. Prueba en
 la Posada, ahí en la esquina. Buenas noches.}
{173}{}{Lo siento, no atiendo a idiotas a estas horas de la noche. Supongo que será por la luna llena
 y la locura. Que duermas bien.}
{174}{}{Tú de nuevo. Espero que tengas una razón de peso para molestarme...}
{175}{}{¡Me estoy muriendo! ¡Ayúdame!}
{176}{}{Lamento molestarte, pero necesito ayuda.}
{177}{}{¡Ay!}
# TRANSLATION NOTES
# When the player gets help from the Doctor, it will build a diagnosis report
# from the lines below. First, it uses one of lines 178-182 to report
# the character's status. Second, it adds on one of lines 183-186.
# If the player is poisoned, it appends one of lines 187-190; if
# the player is irradiated, it adds a line from 191-194 depending on
# the severity of the radiation, and then adds line 195 as well.
{178}{}{muy sano,}
{179}{}{ligeramente herido,}
{180}{}{moderadamente herido,}
{181}{}{seriamente herido,}
{182}{}{a punto de morir,}
{183}{}{ según mi punto de vista profesional.}
{184}{}{ según mis exploraciones.}
{185}{}{ sin duda alguna.}
{186}{}{ según mi punto de vista.}
{187}{}{ Sin duda alguna te han envenenado.}
{188}{}{ Te han envenenado.}
{189}{}{ ¿Sabías que te habían envenenado?}
{190}{}{ Tienes una toxina letal en tu sangre.}
{191}{}{ Padeces de envenenamiento por radiación en grado leve.}
{192}{}{ Padeces de envenenamiento por radiación en grado moderado.}
{193}{}{ Tu cuerpo ha absorbido una cantidad increíble de radiaciones.}
{194}{}{ Nunca he visto nada igual en mi escáner de radioactividad.
 Creo que estás a punto de morir. Te quedan un par de semanas.}
{195}{}{ No puedo hacer gran cosa.}
{196}{}{Espero que tengas una razón de peso para molestarme. Mi tiempo es muy
 valioso.}
{197}{}{¡Me estoy muriendo! ¡Ayúdame!}
{198}{}{Lamento molestarte, pero necesito ayuda.}
{199}{}{¡Agh!}
{200}{}{No me gusta tu tipo de humor. Vete y déjame volver a mi trabajo.}
{201}{}{Umm. Bien, creo que estás sano. Puede que necesites descansar. Prueba en
 la Posada, ahí en la esquina. Buenas noches.}
{202}{}{Lo siento pero no atiendo a idiotas por la noche. Será por la luna llena
 y la locura, supongo. Que duermas bien.}
{203}{}{Tú de nuevo. Espero que tengas una razón de peso para molestarme...}
{204}{}{¡Intruso! ¡Esto es un cuarto privado!}
{205}{}{}
{206}{}{}
{207}{}{¡Vete, carnicero!}
{208}{}{¡Espera!}
{209}{}{¡Ah!}
{210}{}{¡No intentes cambiar de tema!}
{211}{}{¿Por qué?}
{212}{}{¡No soy un peligro para ti!}
{213}{}{¡Voy a acabar con tu operación ahora mismo!}
{214}{}{¡No! ¡No te dejaré interrumpir mi operación! ¡Lárgate! }
{215}{}{¿Por qué?}
{216}{}{Sé lo que estás haciendo aquí y no te interrumpiré.}
{217}{}{Evidentemente eres más poderoso que yo.}
{218}{}{Eso es cierto. Por desgracia, has visto demasiado. Umm.}
{219}{}{ Tendrás que desaparecer. Lo siento.}
{220}{}{ Debes probar tu sinceridad. Y entonces puede que me decida a
 negociar.}
{221}{}{¿Qué quieres decir?}
{222}{}{No hay trato posible.}
{223}{}{Vale. Tú ganas.}
{224}{}{Me quedaré con algo tuyo. Y entonces puede que negociemos.}
{225}{}{Vale.}
{226}{}{De ninguna manera.}
{227}{}{¡Excelente!}
{228}{}{Doc Mórbid coge un instrumento quirúrgico y antes de que te des cuenta
 te saca un ojo. Te duele horrorosamente.}
{229}{}{Ahora la mitad de lo que has visto me pertenece.}
{230}{}{¡ME HAS SACADO UN OJO! ¡HIJO DE...!}
{231}{}{Eh, eh. Vigila tus modales.}
{232}{}{El doctor ha salido.}
{233}{}{Sé lo que estás tramando con Iguana Bob, carnicero.}
{234}{}{Qu... ¿a qué te refieres?}
{235}{}{He hablado un rato con tu gnomo...}
{236}{}{[Mira de lado a lado] Eso no prueba nada. Gretch es un
 poco... corto de mente. Nadie le presta atención aquí. Será mejor
 que te vayas.}
