{100}{}{Delante ti ves un ordenador Mach IV.}
{101}{}{Al parecer está seleccionado el modo reinicialización.}
{102}{}{Parece que el sistema está bloqueado.}
{103}{}{El monitor parpadea.}
{104}{}{La pantalla muestra extraños patrones de color.}
{105}{}{La pantalla del ordenador presenta pequeñas bombas verdes que caen
 interminablemente al suelo.}
{106}{}{No consigues encontrar el código de acceso de la pantalla.}
{107}{}{Tienes acceso a unas notas electrónicas. La más interesante es
 una solicitud del Teniente que pide "más sujetos humanos para ser sumergidos.
 Enviarlos inmediatamente a la Base Militar".}
