{100}{}{Estás viendo un robot roto.}
{101}{}{Estás viendo un robot que funciona.}
{102}{}{Arreglas el robot roto. Inmediatamente se enciende
 y vuelve a la vida.}
{103}{}{La reparación está por encima de tus posibilidades.}
