{100}{}{Este ordenador recibe el nombre de Ordenador de Acceso Atómico.}
{101}{}{Unos cables conectan el ordenador de acceso
 a la cabeza nuclear que está detrás de él.}
{102}{}{Has activado la cabeza. Un contador de cuatro minutos ha
 comenzado la cuenta atrás.}
{103}{}{Has desactivado la cabeza nuclear.}
{104}{}{¡BUUUUUUUUM! [¡Has echo estallar la bomba!]}
{105}{}{No funciona al parecer.}
{106}{}{La cuenta atrás continúa... puede que debas cortar ese cable rojo.}
{107}{}{Puede que también debas usar la llave.}
{108}{}{Este ordenador dispone de un dispositivo de bloqueo de hardware que impide
 la activación de la bomba sin la llave correcta.}
{109}{}{Es imposible quitar este cierre de seguridad porque pesa mucho.}
{110}{}{Este ordenador no se puede arreglar.}
{111}{}{No puedes utilizar tu habilidad con las trampas en este ordenador.}
{112}{}{No eres capaz de desactivar el mecanismo de seguridad.}
