{100}{}{Esto es una cabeza nuclear.}
{101}{}{Hay cables que van desde el ordenador de acceso hasta
 la cabeza nuclear, colocada detrás.}
{102}{}{Has activado la cabeza. Un temporizador de cuatro minutos
 ha comenzado la cuenta atrás.}
{103}{}{Has desactivado la cabeza nuclear.}
{104}{}{¡BUUUUUUUUM! [¡Has provocado la explosión de la bomba!]}
{105}{}{Parece que no funciona.}
{106}{}{La cuenta atrás continúa... puede que debas cortar ese cable rojo.}
{107}{}{Puede que también necesites usar la llave.}
{108}{}{Esto es una cabeza nuclear. Está controlada por el ordenador conectado
 por los cables.}
{109}{}{No hay nada en esta cabeza nuclear que necesite una reparación.}
{110}{}{No hay nada en esta cabeza nuclear que necesite el uso de una ganzúa.}
{111}{}{Esto es una trampa grande que no puede ser montada o desmontada desde aquí.}