{100}{}{Estás viendo una puerta de acero. Un letrero dice: "Sala de Control de Reactor.
 Sólo Personal Autorizado."}
{101}{}{La puerta está cerrada electrónicamente.}
{102}{}{La puerta no está cerrada.}
{103}{}{Consigues desactivar el cierre electrónico.}
{104}{}{No puedes desactivar el cierre electrónico.}
