{100}{}{Estás viendo a Neil, el jefe de los guardias de los Seguidores.}
{101}{}{Estás viendo a Neil, el jefe de los guardias de los Seguidores.}
{102}{}{Si buscas a alguien con quien hablar, habla con Peter. Estoy
 intentando dormir algo.}
{103}{}{¿Por qué estás aquí?}
{104}{}{Grr. ¿Arrooo?}
{105}{}{Noh noh.}
{106}{}{¡¡MATAR!!}
{107}{}{Soy }
{108}{}{. Me enviaron a que te buscara.}
{109}{}{Soy }
{110}{}{. Y tu estás muerto.}
{111}{}{¿Qué puedes decirme de los Seguidores?}
{112}{}{He venido a ofrecerte mi ayuda.}
{113}{}{Busco formas de instaurar la paz en este yermo tan desolado.}
{114}{}{Lo siento, pero no puedo entenderte. Y ahora, ¿qué estás haciendo aquí?}
{115}{}{Noh noh.}
{116}{}{¡¡Yo Matar!!}
{117}{}{Ayua. Yo ayuda.}
{118}{}{Si no estás haciendo nada, entonces te sugiero que te marches. ¡Ahora!}
{119}{}{¿Quieres ayudar? Quizás me seas de utilidad.}
{120}{}{Sí. ¡Yo ayua! ¡Yo ayua!}
{121}{}{No. ¡No ayua!}
{122}{}{Eres lo bastante simple para encontrar a esta persona que otros son
 demasiado listos para encontrar. Por los alrededores hay un espía que está entregando
 nuestros secretos a los Niños. Busca al espía. Mata al espía. Vete..}
{123}{}{Ya he pensado demasiado. Vete ahora.}
{124}{}{Imagínate, Jake no cree que pueda hacer el trabajo
 correctamente. Él es el único que podría haberte enviado.
 Entonces ya sabes lo del espía.}
{125}{}{Jake no me envía. Es de parte de uno de tus guardias.}
{126}{}{Conozco a algunos. Jake casi no me dijo nada.}
{127}{}{¿De qué va todo esto del espía? Quizás pueda ayudar.}
{128}{}{Mis guardias no son tontos. Te enviaron a la persona adecuada.
 Aquí hay una filtración, y necesitamos averiguar dónde está y cerrarla.}
{129}{}{¿Tienes alguna pista?}
{130}{}{Soy un guerrero, no un fontanero. Si tenéis filtraciones, hablad con otra persona.}
{131}{}{Creo que tú eres la filtración. ¡¡Muere!!}
{132}{}{Olvídalo. No soy el lacayo de nadie.}
{133}{}{Lo único que sabemos por ahora es que esa persona tiene acceso
 a los Niños de la Catedral. Creo que podría ser uno de nuestros exploradores.}
{134}{}{Vale. Ahora mismo iré a comprobarlo.}
{135}{}{¿Estás seguro que no es uno de los guaridas?}
{136}{}{Entonces mala suerte. Ahora nunca podrás capturar a esa persona.}
{137}{}{Lo tengo bastante claro. Ellos solo tienen acceso a las salas de
 los Seguidores. No se les permite salir fuera.}
{138}{}{Entonces no sé quién podría ser.}
{139}{}{Entonces echaré un vistazo a los exploradores.}
{140}{}{Creo que aquí ocultas algo. ¡Ahora muere!}
{141}{}{Por eso te estoy pidiendo que mires por los alrededores y veas
 si puedes encontrar a alguien. ¿Me ayudarás?}
{142}{}{Sí.}
{143}{}{No.}
{144}{}{Gracias. Eso significa mucho para nosotros.}
{145}{}{Entonces debo detenerte para que no adviertas a nadie.}
{146}{}{Cómo llegó él a ser el segundo no lo sé. Como resulta que
 está tan escueto de palabras, te dejaré entrar. Tenemos una filtración que hace
 disponer a los Niños con algunas de nuestras rutas de patrulla.}
{147}{}{¿Tienes alguna pista?}
{148}{}{Soy un guerrero, no un fontanero. Si tenéis filtraciones, hablad con otra persona.}
{149}{}{Creo que tú eres la filtración. ¡¡Muere!!}
{150}{}{Olvídalo. No soy el lacayo de nadie.}
{151}{}{¿Ni siquiera lo sabes? Creo que es mejor que no; mucha gente
 de aquí no lo es. Alguien está robando información de nuestros movimientos
 a los Niños. Necesitamos que esa persona se vaya.}
{152}{}{¿Tienes pistas?}
{153}{}{Creo que tú eres la filtración. ¡¡Muere!!}
{154}{}{Olvídalo. No soy el lacayo de nadie.}
{155}{}{¿Cuánto estás dispuesto a ofrecer?}
{156}{}{No tengo mucho dinero. ¿Qué te parecen 200 chapas?}
{157}{}{Lo siento, estoy arruinado.}
{158}{}{Tu vida.}
{159}{}{Me parece bien.}
{160}{}{¡Ahora acabaré con esta filtración de los Seguidores!}
{161}{}{Entonces mala suerte.}
{162}{}{¿Qué te gustaría saber?}
{163}{}{¿Quién es el líder?}
{164}{}{¿Por qué estáis atacando a los Niños?}
{165}{}{¿Dónde puedo conseguir primeros auxilios?}
{166}{}{Nada. Solo estaba comprobando algo.}
{167}{}{Nada. Gracias.}
{168}{}{Nuestra líder es Nicole. Una persona encantadora, pero un poco caprichosa.
 ¿Quieres saber algo más?}
{169}{}{¿Por qué estáis atacando a los Niños?}
{170}{}{¿Dónde puedo conseguir algo de curación?}
{171}{}{Nada. Solo estaba comprobando algo. *manotazo*}
{172}{}{Nada. Gracias.}
{173}{}{Los Niños no son lo que parecen. Están
 escondiendo algo. Algo relacionado con esos Nocturnos. ¿Algo más?}
{174}{}{¿Quién es el líder?}
{175}{}{¿Dónde puedo conseguir algo de curación?}
{176}{}{Nada. Solo comprobaba algo. *manotazo*}
{177}{}{Nada. Gracias.}
{178}{}{Hay el sanador de los Niños, pero no confío en ellos. Nosotros
 también tenemos aquí a un doctor o a una enfermera en todo momento. ¿Algo más?}
{179}{}{¿Quién es el líder?}
{180}{}{¿Por qué estáis atacando a los Niños?}
{181}{}{Nada. Solo comprobaba algo. *manotazo*}
{182}{}{Nada. Gracias.}
{183}{}{Lamento mucho oír eso. ¡Que las piezas estén contigo!}
{184}{}{¿Quién te ha enviado?}
{185}{}{Me ha enviado uno de tus guardias.}
{186}{}{Me ha enviado Jake.}
{187}{}{Me he enviado yo.}
{188}{}{No importa. Adiós.}
{189}{}{Estás bastante seguro de ti mismo. No te necesito.
 Habla con Nicole si quieres ofrecer tus servicios. Buenas noches.}
{190}{}{Entonces debes querer hablar con Nicole. Ella te puede ayudar
 mejor con eso. Buenas tardes.}
{191}{}{Ve a buscar al espía. Todavía necesitamos mantener nuestros planes en secreto.}
{192}{}{Buen trabajo al encontrar y eliminar a Heather. Su intromisión
 casi hace que mueran todos. Ojalá pudiéramos haber hecho algo más.}
{193}{}{Quizás pueda ayudarte una vez más.}
{194}{}{Que tengas buena suerte.}
{195}{}{¿Y eso?}
{196}{}{Puedo entrenar a los Seguidores en algunas técnicas para la guerra. Quizás
 mejoren tus posibilidades.}
{197}{}{Debo irme. Adiós.}
{198}{}{Eso sería maravilloso. Gracias.}
{199}{}{Ahora estás un poco mas preparado. Buenas tardes.}
{200}{}{Gracias por tus clases. Ahora tenemos una oportunidad de patearles
 el trasero a esos Niños.}