{100}{}{La nevera está cerrada.}
{101}{}{La nevera ya está abierta.}
{102}{}{Abres la nevera.}
{103}{}{Aún no has conseguido quitar este cerrojo.}
{104}{}{¡Alguien se ha dejado la nevera abierta!}
