{500}{}{Tras destruir al Maestro y el laboratorio en el que creaba su ejército de Supermutantes,
 vuelves a casa para descubrir que te expulsan del Refugio por ser demasiado destructivo. Gracias por
 jugar a Fallout. }

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#      "my name"       #
#      (970-979)       #
#                      #
#                      #
{970}{}{Así me llamo.}
{971}{}{Me hablas a mí.}
{972}{}{Por qué haces esas preguntas estúpidas. Yo soy esa persona.}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#     "don't know"     #
#      (970-979)       #
#                      #
#                      #
{980}{}{No sé nada sobre eso.}
{981}{}{Lo siento. Ni idea.}
{982}{}{Nunca lo había oído.}

# DESERT1.MAP (1000)
# DESERT2.MAP (1600)
# DESERT3.MAP (2200)

#
# HALLDED.MAP
# The Necropolis Hall of the Dead Tell-Me-Abouts
#
{2800}{}{Maestro}
{2801}{}{Chip de agua}
{2802}{}{Necrópolis}
{2803}{}{Set}
{2804}{}{Almacén de Agua}
{2805}{}{Sala}
{2900}{}{¿No es ese un tipo bastante importante?}
{2901}{}{No lo sé, pero en el Almacén de Agua podría haber uno.}
{2902}{}{Estás en ella. O por lo menos es lo que queda. Este
 lugar se está muriendo poco a poco.}
{2903}{}{Oh, me cae bien. Puedes encontrarlo en la Sala.}
{2904}{}{Está al norte. Ten cuidado con los guardias. Se toman su
 trabajo muy en serio.}
{2905}{}{La Sala de los Difuntos. Allí hace Set sus trabajos. Queda
 justo en el centro de Necrópolis.}


#
# HOTEL.MAP
# The Necropolis Hotel Tell-Me-Abouts
#
{3400}{}{Maestro}
{3401}{}{Chip de agua}
{3402}{}{Necrópolis}
{3403}{}{Set}
{3404}{}{Almacén de Agua}
{3405}{}{Sala}
{3500}{}{¿No es ese un tipo bastante importante?}
{3501}{}{No lo sé, pero en el almacén de agua podría haber uno.}
{3502}{}{Estás en ella. O por lo menos es lo que queda. Este
 lugar se está muriendo poco a poco.}
{3503}{}{Oh, me cae bien. Puedes encontrarlo en la Sala.}
{3504}{}{Está al norte. Ten cuidado con los guardias. Se toman su
 trabajo muy en serio.}
{3505}{}{La Sala de los Difuntos. Allí hace Set sus trabajos. Queda
 justo en el centro de Necrópolis.}


#
# WATRSHD.MAP
# The Necropolis Watershed Tell-Me-Abouts
#
{4000}{}{Maestro}
{4001}{}{Chip de agua}
{4002}{}{Necrópolis}
{4003}{}{Set}
{4004}{}{Almacén de Agua}
{4005}{}{Sala}
{4100}{}{¿No es ese un tipo bastante importante?}
{4101}{}{No lo sé, pero en el almacén de agua podría haber uno.}
{4102}{}{Estás en ella. O por lo menos es lo que queda. Este
 lugar se está muriendo poco a poco.}
{4103}{}{Oh, me cae bien. Puedes encontrarlo en la Sala.}
{4104}{}{ Ten cuidado con los guardias. Se toman su
 trabajo muy en serio.}
{4105}{}{La Sala de los Difuntos. Allí hace Set sus trabajos. Queda
 justo en el centro de Necrópolis.}


#
# VAULT13.MAP
# Vault 13 Tell-Me-Abouts
#
{4600}{}{Refugio}
{4601}{}{Agua}
{4602}{}{Supervisor}
{4603}{}{Chip}
{4604}{}{Chip de agua}
{4605}{}{Refugio 13}
{4606}{}{Refugio13}
{4607}{}{Médico}
{4608}{}{Curación}
{4609}{}{Biblioteca}
{4700}{}{Es donde vivimos. Deberías entenderlo.}
{4701}{}{El chip controla el nivel de pureza del suministro de agua
 subterránea. Es una pieza muy importante que no podemos reparar.}
{4702}{}{Un buen hombre que hace un trabajo difícil.}
{4703}{}{El chip controla el nivel de pureza del suministro de agua
 subterránea. Es una pieza muy importante que no podemos reparar.}
{4704}{}{El chip controla el nivel de pureza del suministro de agua
 subterránea. Es una pieza muy importante que no podemos reparar.}
{4705}{}{Es donde vivimos. Deberías entenderlo.}
{4706}{}{Es donde vivimos. Deberías entenderlo.}
{4707}{}{El médico está en la primera planta, en el laboratorio médico. Vete allí si estás
 herido.}
{4708}{}{El médico está en la primera planta, en el laboratorio médico. Vete allí si estás
 herido.}
{4709}{}{La Biblioteca está en el ala oeste de la tercera planta. Allí están los
 ordenadores de consulta.}

# VAULTENT.MAP (5200)
# VAULTBUR.MAP (5800)
# VAULTNEC.MAP (6400)

#
# JUNKENT.MAP
# Junktown Entrance Tell-Me-Abouts
#
{7000}{}{Killian}
{7001}{}{Gizmo}
{7002}{}{Ciudad Vertedero}
{7003}{}{Arenas Sombrías}
{7004}{}{Eje}
{7005}{}{Chip de agua}
{7006}{}{Casino}
{7007}{}{Tienda}
{7008}{}{Garra Mortal}
{7100}{}{Killian es el alcalde. Lleva un establecimiento.}
{7101}{}{Gizmo lleva un Casino. No está mal.}
{7102}{}{Esto es Ciudad Vertedero.}
{7103}{}{Mmm, creo que es un sitio bastante pequeño. Nunca he estado allí.}
{7104}{}{Es una gran ciudad que está al sur de aquí.}
{7105}{}{¿Qué? Lo siento.}
{7106}{}{Es un edificio grande al noroeste de la ciudad.}
{7107}{}{¿El establecimiento de Killian? Está en el centro de la ciudad.}
{7108}{}{No sé, pero sólo el nombre me pone los pelos de punta.}


#
# JUNKCSNO.MAP
# Junktown Casino Tell-Me-Abouts
#
{7600}{}{Killian}
{7601}{}{Gizmo}
{7602}{}{Ciudad Vertedero}
{7603}{}{Arenas Sombrías}
{7604}{}{Eje}
{7605}{}{Chip de agua}
{7606}{}{Casino}
{7607}{}{Tienda}
{7608}{}{Garra Mortal}
{7700}{}{Killian es el alcalde. Ocupó ese puesto al morir su padre.}
{7701}{}{Gizmo es un hombre importante en Ciudad Vertedero. Regenta el Casino, y el
 ring de boxeo. Gana muchas chapas y compra muchas cosas en el
 Eje.}
{7702}{}{Esto es Ciudad Vertedero.}
{7703}{}{Pues es una pequeña comunidad que está al norte. La mayor parte de
 los que viven allí son granjeros. A veces comerciamos con ellos, pero generalmente
 quieren que los dejemos en paz.}
{7704}{}{El Eje es el centro de todo el comercio de por aquí. Casi todos los
 comerciantes vienen del Eje. Algunas compañías todavía fabrican cosas.
 Si quieres, puedes volver al Eje con alguno de sus grupos
 de comercio.}
{7705}{}{No sé nada sobre eso.}
{7706}{}{Gizmo lo lleva. Cuidado con las máquinas tragaperras, puedes perder
 muchas chapas si juegas.}
{7707}{}{¿La de Darkwater? Está en el centro de la ciudad. Puedes pagar con chapas o
 intercambiar cosas.}
{7708}{}{He oído a la gente hablar de ella pero nunca la he visto. Dicen
 que vaga por el desierto y ataca principalmente por la noche.}


#
# JUNKKILL.MAP
# Junktown Killian's Tell-Me-Abouts
#
{8200}{}{Killian}
{8201}{}{Gizmo}
{8202}{}{Ciudad Vertedero}
{8203}{}{Arenas Sombrías}
{8204}{}{Eje}
{8205}{}{Chip de agua}
{8206}{}{Casino}
{8207}{}{Tienda}
{8208}{}{Garra Mortal}
{8300}{}{Killian es el alcalde. Ocupó ese puesto al morir su padre.}
{8301}{}{Gizmo es un hombre importante en Ciudad Vertedero. Lleva el Casino, y el
 ring de boxeo. Gana muchas chapas y compra muchas cosas en el
 Eje.}
{8302}{}{Esto es Ciudad Vertedero.}
{8303}{}{Pues es una pequeña comunidad que está al norte. La mayor parte de
 los que viven allí son granjeros. A veces comerciamos con ellos, pero generalmente
 lo que quieren es que los dejemos en paz.}
{8304}{}{El Eje es el centro de todo el comercio de por aquí. Casi todos los
 comerciantes vienen del Eje. En algunas compañías todavía se
 fabrican cosas. Si quieres, puedes volver al Eje con
 alguno de sus grupos de comercio.}
{8305}{}{No sé nada sobre eso.}
{8306}{}{Gizmo lo lleva. Cuidado con las máquinas tragaperras, puedes perder
 muchas chapas si juegas.}
{8307}{}{¿La de Darkwater? Está en el centro de la ciudad. Puedes pagar con chapas o
 intercambiar cosas.}
{8308}{}{He oído a la gente hablar de ella pero nunca la he visto. Dicen
 que vaga por el desierto y ataca principalmente por la noche.}


# BROHDENT.MAP  (8800)
{8800}{}{Maestro}
{8801}{}{Guerra}
{8802}{}{Éxodo}
{8803}{}{Extraño Ejército}
{8804}{}{Hermandad}
{8805}{}{Mercaderes}
{8806}{}{Caravanas perdidas}
{8807}{}{Eje}
{8808}{}{Niños de la Catedral}
{8809}{}{Iniciados}
{8810}{}{Escribas}
{8811}{}{Caballeros}
{8812}{}{Paladines}
{8813}{}{Chip de agua}
{8900}{}{No tengo ni idea de lo que me estás diciendo.}
{8901}{}{Un punto negro en la historia de la humanidad que dio lugar a nuestro mundo actual. Recordamos lo que ocurrió en
 la Guerra para evitar otro holocausto.}
{8902}{}{Una decisión difícil y triste. Perdimos a mucha gente que decidió irse por su cuenta
 en vez de viajar con nuestro grupo en busca de un refugio en el que vivir.}
{8903}{}{No sé mucho de eso. Por lo que he oído se están reuniendo en algún lugar al norte de aquí.}
{8904}{}{Es donde estamos.}
{8905}{}{Esos Mercaderes de Agua son unos ladrones bastardos, pero de los demás grupos no tengo formada una opinión.}
{8906}{}{No sé mucho acerca de eso.}
{8907}{}{Un infierno de lodo para esos viles mercaderes. Aunque de vez en cuando dejamos que alguna de las compañías más civilizadas
 intercambien productos con nosotros.}
{8908}{}{Son un culto.}
{8909}{}{Son el futuro de la Hermandad.}
{8910}{}{Son los guardianes del conocimiento.}
{8911}{}{Son los que hacen las armas para la Hermandad.}
{8912}{}{Son los protectores de la Hermandad.}
{8913}{}{No tengo ni idea de lo que estás diciendo.}

# BROHD12.MAP   (9400)

{9400}{}{Maestro}
{9401}{}{Guerra}
{9402}{}{Éxodo}
{9403}{}{Extraño Ejército}
{9404}{}{Hermandad}
{9405}{}{Mercaderes}
{9406}{}{Caravanas desaparecidas}
{9407}{}{Eje}
{9408}{}{Niños del la Catedral}
{9409}{}{Iniciados}
{9410}{}{Escribas}
{9411}{}{Caballeros}
{9412}{}{Paladines}
{9413}{}{Chip de agua}
{9500}{}{No tengo ni idea de lo que me estás diciendo.}
{9501}{}{Un punto negro en la historia de la humanidad que dio lugar a nuestro mundo actual. Recordamos lo que ocurrió en
 la Guerra para evitar otro holocausto.}
{9502}{}{Una decisión difícil y triste. Perdimos a mucha gente que decidió irse por su cuenta
 en vez de viajar con nuestro grupo en busca de un refugio en el que vivir.}
{9503}{}{No sé mucho de eso. Por lo que he oído se están reuniendo en algún lugar al norte de aquí.}
{9504}{}{Es donde estamos.}
{9505}{}{Esos Mercaderes de Agua son unos ladrones bastardos, pero de los demás grupos no tengo formada una opinión.}
{9506}{}{No sé mucho acerca de eso.}
{9507}{}{Un infierno de lodo para esos viles mercaderes. Aunque de vez en cuando dejamos que alguna de las compañías más civilizadas
 intercambien productos con nosotros.}
{9508}{}{Son un culto.}
{9509}{}{Son el futuro de la Hermandad.}
{9510}{}{Son los guardianes del conocimiento.}
{9511}{}{Son los que hacen las armas para la Hermandad.}
{9512}{}{Son los protectores de la Hermandad.}
{9513}{}{No tengo ni idea de lo que estás hablando.}

# BROHD34.MAP  (10000)

{10000}{}{Maestro}
{10001}{}{Guerra}
{10002}{}{Éxodo}
{10003}{}{Extraño Ejército}
{10004}{}{Hermandad}
{10005}{}{Mercaderes}
{10006}{}{Caravanas desaparecidas}
{10007}{}{Eje}
{10008}{}{Niños del la Catedral}
{10009}{}{Iniciados}
{10010}{}{Escribas}
{10011}{}{Caballeros}
{10012}{}{Paladines}
{10013}{}{Chip de agua}
{10100}{}{No tengo ni idea de lo que estás diciendo.}
{10101}{}{Un punto negro en la historia de la humanidad que dio lugar a nuestro mundo actual. Recordamos lo que ocurrió en
 la Guerra para evitar otro holocausto.}
{10102}{}{Una decisión difícil y triste. Perdimos a mucha gente que decidió irse por su cuenta
 en vez de viajar con el gran grupo en busca de un refugio en el que vivir.}
{10103}{}{No sé mucho sobre eso. Por lo que he oído se están reuniendo en algún lugar al norte de aquí.}
{10104}{}{Es donde estamos.}
{10105}{}{Esos Mercaderes de Agua son unos ladrones bastardos, pero de los demás grupos no tengo formada una opinión.}
{10106}{}{No sé mucho acerca de eso.}
{10107}{}{Un infierno de lodo para esos viles mercaderes. Aunque de vez en cuando dejamos que alguna de las compañías más civilizadas
 intercambien productos con nosotros.}
{10108}{}{Son un culto.}
{10109}{}{Son el futuro de la Hermandad.}
{10110}{}{Son los guardianes el conocimiento.}
{10111}{}{Son los que hacen las armas para la Hermandad.}
{10112}{}{Son los protectores de la Hermandad.}
{10113}{}{No tengo ni idea de lo que estás hablando.}


# CAVES.MAP    (10600)
# CHILDRN1.MAP (11200)

{11200}{}{Llama Sagrada}
{11201}{}{Unidad}
{11202}{}{Niños del la Catedral}
{11203}{}{Morfeo}
{11204}{}{Mutantes}
{11205}{}{Maestro}
{11206}{}{Seguidores del Apocalipsis}
{11207}{}{Base Militar}
{11208}{}{Tanques}
{11209}{}{Chip de agua}

{11300}{}{La Llama Sagrada es la que nos guiará
 hacia un nuevo mundo en el que no habrá odio ni guerras.}
{11301}{}{Todos formamos parte de la Unidad. Es el amor y
 la paz que ofrecemos a nuestra amada gente... tanto a humanos como a mutantes.}
{11302}{}{Esos somos nosotros.}
{11303}{}{Morfeo es el Sumo Sacerdote de los Niños.
 Normalmente cuando no está en sus aposentos nos predica.}
{11304}{}{Sufrieron una mutación durante el holocausto nuclear
 Pero siguen siendo buena gente.}
{11305}{}{Todos tenemos maestros, ¿no?}
{11306}{}{Intentan acabar con la paz que
 el Maestro intenta establecer.}
{11307}{}{Lo siento, nunca he oído hablar de eso.}
{11308}{}{Lo siento, no sé de qué estás hablando.}
{11309}{}{No tengo ni idea de lo que me dices.}

# CHILDRN2.MAP (11800)

{11800}{}{Llama Sagrada}
{11801}{}{Unidad}
{11802}{}{Niños de la Catedral}
{11803}{}{Morfeo}
{11804}{}{Mutantes}
{11805}{}{Maestro}
{11806}{}{Seguidores del Apocalipsis}
{11807}{}{Base Militar}
{11808}{}{Tanques}
{11809}{}{Chip de agua}

{11900}{}{La Llama Sagrada es la que nos guiará
 hacia un nuevo mundo en el que no habrá odio ni guerras.}
{11901}{}{Todos formamos parte de la Unidad. Es el amor y
 la paz que ofrecemos a nuestra amada gente... tanto a humanos como a mutantes.}
{11902}{}{Esos somos nosotros.}
{11903}{}{Morfeo es el Sumo Sacerdote de los Niños.
 Normalmente cuando no está en sus habitaciones, nos da un sermón.}
{11904}{}{Sufrieron una mutación durante el holocausto nuclear
 Pero aún son buena gente.}
{11905}{}{Todos tenemos maestros, ¿no?}
{11906}{}{Intentan acabar con la paz que
 el Maestro intenta lograr.}
{11907}{}{Lo siento, nunca he oído hablar de eso.}
{11908}{}{Lo siento, no sé de qué estás hablando.}
{11909}{}{No tengo ni idea de lo que me dices.}

# CITY1.MAP    (12400)
# COAST1.MAP   (13000)
# COAST2.MAP   (13600)
# COLATRUK.MAP (14200)
# FSAUSER.MAP  (14800)

#
# RAIDERS.MAP
# Raiders Tell-Me-Abouts
#
{15400}{}{Khans}
{15401}{}{Garl}
{15402}{}{Ciudad Vertedero}
{15403}{}{Arenas Sombrías}
{15404}{}{Eje}
{15405}{}{Chip de agua}
{15406}{}{Tandi}
{15407}{}{Alya}
{15408}{}{Diana}
{15409}{}{Gwen}
{15410}{}{Petrox}
{15411}{}{Tolya}
{15412}{}{Bebidas}
{15413}{}{Drogas}
{15500}{}{Somos nosotros, siervo.}
{15501}{}{Es el líder de los Khans. Es el hombre más temido de los
 yermos.}
{15502}{}{Están al sudoeste. A veces vamos allí para relajarnos tras
 un duro día de saqueo.}
{15503}{}{Por qué no los machacamos por completo es algo que no comprendo.}
{15504}{}{Están al sur. Comerciamos con ellos, principalmente
 agua y municiones, pero a veces también tienen buenas armas.}
{15505}{}{¿Por qué iba a importarme?}
{15506}{}{No conozco a nadie que se llame así.}
{15507}{}{Es una consejera. Ella planea los ataques.}
{15508}{}{Es la armera. Repara nuestros equipos.}
{15509}{}{Es la segunda al mando.}
{15510}{}{Se encarga de conseguir provisiones.}
{15511}{}{Es el cocinero.}
{15512}{}{¿Tienes alguna?}
{15513}{}{¿Tienes alguna?}


#
# SHADYE.MAP
# Shady Sands East Tell-Me-Abouts
#
{16000}{}{Khans}
{16001}{}{Garl}
{16002}{}{Ciudad Vertedero}
{16003}{}{Arenas Sombrías}
{16004}{}{Eje}
{16005}{}{Chip de agua}
{16006}{}{Tandi}
{16007}{}{Aradesh}
{16008}{}{Seth}
{16009}{}{Razlo}
{16100}{}{Son un grupo sin ley que finge ser gente del pasado
 lejano.}
{16101}{}{Es el líder de los Khans. Es uno de los hombres más peligrosos que
 nunca se ha visto en Arenas Sombrías. Lidera los clanes Piratas con
 dureza.}
{16102}{}{Está a 4 ó 6 días hacia el sudoeste. A veces hay buenas mercancías pero
 lo más normal es que intenten dejarnos tiesos.}
{16103}{}{Estás aquí mismo.}
{16104}{}{Bastante más al sur que Ciudad Vertedero. El Eje es la mayor
 ciudad que conozco. Habrá por lo menos mil personas.}
{16105}{}{Lo siento, no puedo ayudarte.}
{16106}{}{Es la hija de Aradesh. Algún día podría ser nuestra líder, pero
 antes debe aprender a mejorar sus modales.}
{16107}{}{Es el líder de nuestra comunidad y un verdadero héroe.
 Lo encontrarás en el Ayuntamiento. Siempre está trabajando.}
{16108}{}{Trabaja con Aradesh por nuestra seguridad.}
{16109}{}{Nuestro Doctor. Si estás herido, ve a verle.}

#
# SHADYW.MAP
# Shady Sands West Tell-Me-Abouts
#
{16600}{}{Khans}
{16601}{}{Garl}
{16602}{}{Ciudad Vertedero}
{16603}{}{Arenas Sombrías}
{16604}{}{Eje}
{16605}{}{Chip de agua}
{16606}{}{Tandi}
{16607}{}{Aradesh}
{16608}{}{Seth}
{16609}{}{Razlo}
{16700}{}{Son un grupo sin ley que finge ser gente del pasado
 lejano.}
{16701}{}{Es el líder de los Khans. Es uno de los hombres más peligrosos que
 nunca se ha visto en Arenas Sombrías. Lidera los clanes Piratas con
 dureza.}
{16702}{}{Está a 4 ó 6 días hacia el sudoeste. A veces hay buenas mercancías pero
 lo más normal es que intenten dejarnos tiesos.}
{16703}{}{Estás aquí mismo.}
{16704}{}{Bastante más al sur que Ciudad Vertedero. El Eje es la mayor
 ciudad que conozca. Debe haber allí por lo menos mil personas.}
{16705}{}{Lo siento, no puedo ayudarte.}
{16706}{}{Es la hija de Aradesh. Algún día podría ser nuestra líder, pero
 debe aprender a mejorar sus modales.}
{16707}{}{Es el líder de nuestra comunidad y un verdadero héroe.
 Lo encontrarás en el Ayuntamiento. Siempre está trabajando.}
{16708}{}{Trabaja con Aradesh por nuestra seguridad.}
{16709}{}{Nuestro Doctor. Si estás herido, ve a verlo.}

# GLOWENT.MAP  (17200)


#
# LAADYTUM.MAP
#
#

#  ======================================================================
#     ADYTUM
# Info Level 1 [People who know nothing]
{17800}{}{Adytum}
{17801}{}{Seguidores}
{17802}{}{Catedral}
{17803}{}{Destripadores}
{17804}{}{Navajas}
{17805}{}{Pistoleros}
{17806}{}{Eje}
{17807}{}{Ciudad Vertedero}
{17808}{}{Chip de agua}
{17809}{}{Establecimiento}
{17810}{}{Zimmerman}
{17811}{}{Necrópolis}
{17812}{}{Ardor}
{17813}{}{Reguladores}
{17814}{}{Carroñeros}
{17815}{}{Cementerio}
{17900}{}{Es esto.}
{17901}{}{Viven al norte de aquí.}
{17902}{}{Está al sur de aquí.}
{17903}{}{Están en el lado oeste.}
{17904}{}{Están en el lado este.}
{17905}{}{Están hacia el norte, pasados los Seguidores.}
{17906}{}{Comerciamos con ellos.}
{17907}{}{¿No es una ciudad que está al norte de aquí?}
{17908}{}{¿Un qué?}
{17909}{}{El establecimiento de Tine está subterráneo, cerca de la puerta.}
{17910}{}{Es el alcalde.}
{17911}{}{Me han dicho que está hacia el este.}
{17912}{}{Eso es un mito.}
{17913}{}{Ellos nos protegen.}
{17914}{}{Van al exterior a por provisiones.}
{17915}{}{Esto es el Cementerio.}


# Info level 2 [People who know something]
{18000}{}{Adytum}
{18001}{}{Seguidores}
{18002}{}{Catedral}
{18003}{}{Destripadores}
{18004}{}{Navajas}
{18005}{}{Pistoleros}
{18006}{}{Eje}
{18007}{}{Ciudad Vertedero}
{18008}{}{Chip de agua}
{18009}{}{Tienda}
{18010}{}{Zimmerman}
{18011}{}{Necrópolis}
{18012}{}{Ardor}
{18013}{}{Reguladores}
{18014}{}{Carroñeros}
{18015}{}{Cementerio}
{18100}{}{Estás en Adytum, forastero.}
{18101}{}{Los Seguidores viven en un vieja Biblioteca justo al norte. Predican
 la tolerancia y la paz.}
{18102}{}{La Catedral está al sur, junto a la bahía. Los Niños son
 una religión pacífica.}
{18103}{}{Están en la zona oeste. Son muy viciosos y tienen un montón de trampas.}
{18104}{}{Están en la zona este. Son una especie de navajas de alta tecnología.}
{18105}{}{Están al norte, pasados los Seguidores. Venden armas a las bandas.}
{18106}{}{Comerciamos con ellos. Es la ciudad más grande que conozco.}
{18107}{}{Es una pequeña ciudad que está al noroeste de aquí.}
{18108}{}{Nunca he oído hablar de eso.}
{18109}{}{La tienda de Tine está subterránea, cerca de la verja. Puede venderte muchas provisiones.}
{18110}{}{Es el alcalde. Hace un buen trabajo.}
{18111}{}{Es la ciudad de los muertos, está a varios días de camino al este de aquí.}
{18112}{}{He oído que está bastante al sur de aquí.}
{18113}{}{Nos protegen de las bandas y mantienen la paz.}
{18114}{}{Van al exterior a buscar cosas.}
{18115}{}{Estamos en el Cementerio.}


# Info level 3 [People who know more than something but less than everything]
{18200}{}{Adytum}
{18201}{}{Seguidores}
{18202}{}{Catedral}
{18203}{}{Destripadores}
{18204}{}{Navajas}
{18205}{}{Pistoleros}
{18206}{}{Eje}
{18207}{}{Ciudad Vertedero}
{18208}{}{Chip de agua}
{18209}{}{Tienda}
{18210}{}{Zimmerman}
{18211}{}{Necrópolis}
{18212}{}{Ardor}
{18213}{}{Reguladores}
{18214}{}{Carroñeros}
{18215}{}{Cementerio}
{18300}{}{Somos los descendientes de un viejo Refugio que estaba bajo tierra en la zona sur
 de esta ciudad.}
{18301}{}{Los Seguidores son gente pacífica y culta. Viven en una vieja
 Biblioteca al norte de aquí.}
{18302}{}{Los Niños rinden culto a un misterioso dios, el Dios Oscuro. Parecen inofensivos, pero
 hay algo extraño en su religión. La Catedral está
 al sur de aquí.}
{18303}{}{Los Destripadores son consanguíneos. Tienen un edificio fortificado con trampas
 alrededor con las que cogen prisioneros que luego torturan y matan.}
{18304}{}{Los Navajas son conocidos por sus vibro-cuchillos. Son los
 peores enemigos de los Destripadores. Su líder es una mujer llamada Cuchilla.}
{18305}{}{Antes eran una banda, pero se establecieron en un almacén en la zona
 norte y empezaron a comerciar armas con la gente.}
{18306}{}{El Eje es un centro de comercio. Allí hay compañías que
 producen cosas. Están al este de aquí.}
#{18306 alternate If hydroponic farms aren't fixed:}{Vendemos balas al Eje.}
{18307}{}{Ciudad Vertedero es una ciudad mediana situada al este de aquí y justo al norte de
 El Eje.}
{18308}{}{Lo siento, no puedo ayudarte en eso.}
{18309}{}{Tine lleva los almacenes que están cerca de la puerta principal. Puede venderte
 armas y ustensilios de viaje.}
{18310}{}{Jon es nuestro alcalde. Firma contratos comerciales, define las políticas y
 delega responsabilidades a los Reguladores y a los Carroñeros.}
{18311}{}{¿La Ciudad de los Muertos? Dicen que es un lugar habitado por extraños
 caníbales lejos hacia el este. Yo que tú, no iría allí de visita.}
{18312}{}{Es un lugar muy radioactivo situado bastante al sur de aquí, o al menos eso me han dicho.}
{18313}{}{Son los policias de Adytum. Nos protegen de las bandas.
 Caleb es su líder.}
{18314}{}{Los Carroñeros tienen la misión de explorar el Cementerio en busca de objetos
 de valor. Su jefe es Sammael.}
{18315}{}{El Cementerio de Angel es lo que queda de la ciudad de Los Ángeles.
 Estamos en el centro del Cementerio.}
#  ======================================================================


#
# LAFOLLWR.MAP  (18400)
#
#

#======================================================================
#    FOLLOWERS OF THE APOCALYPSE
# Info Level 1 [People who know nothing]
{18400}{}{Adytum}
{18401}{}{Seguidores}
{18402}{}{Catedral}
{18403}{}{Destripadores}
{18404}{}{Navajas}
{18405}{}{Pistoleros}
{18406}{}{Eje}
{18407}{}{Ciudad Vertedero}
{18408}{}{Chip de agua}
{18409}{}{Nicole}
{18410}{}{Cementerio}
{18500}{}{Es un pueblo que está al sur de aquí.}
{18501}{}{Nosotros somos los Seguidores del Apocalipsis.}
{18502}{}{Un lugar de culto al sur, pasado Adytum.}
{18503}{}{Una banda del oeste.}
{18504}{}{Una banda del este.}
{18505}{}{Una banda al norte.}
{18506}{}{Una ciudad comercial importante al noreste de aquí.}
{18507}{}{Una ciudad de tamaño medio situada al norte del Eje.}
{18508}{}{No puedo ayudarte, lo siento.}
{18509}{}{Ella es nuestro líder.}
{18510}{}{Esto es el Cementerio.}

# Info level 2 [People who know something]
{18600}{}{Adytum}
{18601}{}{Seguidores}
{18602}{}{Catedral}
{18603}{}{Destripadores}
{18604}{}{Navajas}
{18605}{}{Pistoleros}
{18606}{}{Eje}
{18607}{}{Ciudad Vertedero}
{18608}{}{Chip de agua}
{18609}{}{Nicole}
{18610}{}{Cementerio}
{18700}{}{Una pequeña ciudad situada al sur. A veces nos visitan.}
{18701}{}{Nosotros somos los Seguidores del Apocalipsis. Nos llamamos así porque
 resurgimos de la tormenta de la guerra para traer el bálsamo de la paz.}
{18702}{}{Un extraño lugar de culto al sur de Adytum y el resto del Cementerio. Nicole
 dice que son capaces de cualquier cosa.}
{18703}{}{Una banda ultra-violenta del oeste.}
{18704}{}{Una banda del este. Usan vibro-cuchillos.}
{18705}{}{Una banda que procede del Eje y vende armas. Están al norte de aquí.}
{18706}{}{El Eje es una gran ciudad de comerciantes y negocios situada al este.}
{18707}{}{Ciudad Vertedero es una pequeña ciudad situada al norte del Eje.}
{18708}{}{No puedo ayudarte en eso.}
{18709}{}{Es nuestra líder. Quiere restaurar la paz en un mundo dividido por la guerra.}
{18710}{}{Esto es el Cementerio de Angel, los restos de la vieja ciudad de
 Los Ángeles.}

# Info level 3 [People who know more than something but less than everything]
{18800}{}{Adytum}
{18801}{}{Seguidores}
{18802}{}{Catedral}
{18803}{}{Destripadores}
{18804}{}{Navajas}
{18805}{}{Pistoleros}
{18806}{}{Eje}
{18807}{}{Ciudad Vertedero}
{18808}{}{Chip de agua}
{18809}{}{Nicole}
{18810}{}{Cementerio}
{18900}{}{Una pequeña ciudad situada al sur. Son buena gente, aunque algo
 paranoicos. Algunos de ellos trabajan con nosotros de vez en cuando.}
{18901}{}{Nosotros somos los Seguidores del Apocalipsis. Nuestro deber es devolver la paz
 y el conocimiento al mundo y asegurarnos de que
 las armas de guerra nunca volverán a amenazar la tierra.}
{18902}{}{La Catedral es un gran edificio situado al sur del Cementerio. Los Niños
 rinden culto a un dios malvado y oscuro. Tenemos que detenerlos
 antes de que extiendan su religión usando violencia.}
{18903}{}{Consanguíneos y chacales. Atacan a cualquier cosa que se les ponga delante que no sea uno
 de ellos. Viven al oeste de aquí en una fortaleza rodeada de trampas.}
{18904}{}{Un grupo singularmente peligroso que vive al este y lucha con
 vibro-cuchillos. Su líder, Cuchilla, vino del Eje e hizo de ellos
 una fiera familia.}
{18905}{}{Son una banda que vive en un almacén al norte de aquí, en un foso de
 barro radiactivo. Venden armas a las demás bandas.}
{18906}{}{El Eje es una enorme ciudad dedicada al comercio situada al este de aquí. Envían
 caravanas a muchos lugares, incluido Adytum.}
{18907}{}{Es una pequeña ciudad situada al norte del Eje. Me han dicho
 que es un buen lugar de descanso para el viajero cansado.}
{18908}{}{Aunque he leído algo sobre la tecnología de los Refugios, no llego a tanto.}
{18909}{}{Nicole es nuestra líder. La espiritualidad y la contemplación interior la obligan a
 traer la paz a un mundo roto por la guerra.}
{18910}{}{Este es el corazón del Cementerio de Angel, llamado así por la vieja ciudad de
 Los Ángeles, y por los esqueletos de los muertos que cubrían el lugar
 después de la Bomba.}
#======================================================================


# MBENT.MAP     (19000)

{19000}{}{Maestro}
{19001}{}{Teniente}
{19002}{}{Niños de la Catedral}
{19003}{}{Seguidores del Apocalipsis}
{19004}{}{Nocturnos}
{19005}{}{Supermutantes}
{19006}{}{Psíquicos}
{19007}{}{Experimentos}
{19008}{}{Chip de agua}

{19100}{}{No tengo nada que decirte.}
{19101}{}{Tal conocimiento no corresponde a seres inferiores.}
{19102}{}{No necesitas preocuparte por ellos.}
{19103}{}{Eres demasiado modesto para preguntarme.}
{19104}{}{No te incumbe.}
{19105}{}{No te interesa.}
{19106}{}{Eres demasiado idiota para conocerlos.}
{19107}{}{No estás autorizado a conocerlos.}
{19108}{}{No me interesan los juguetitos.}

# MBSTRG12.MAP  (19600)

{19600}{}{Maestro}
{19601}{}{Teniente}
{19602}{}{Niños de la Catedral}
{19603}{}{Seguidores del Apocalipsis}
{19604}{}{Nocturnos}
{19605}{}{Supermutantes}
{19606}{}{Psíquicos}
{19607}{}{Experimentos}
{19608}{}{Chip de agua}
{19700}{}{No tengo nada que decirte.}
{19701}{}{Tal conocimiento no corresponde a seres inferiores.}
{19702}{}{No necesitas relacionarte con ellos.}
{19703}{}{Eres demasiado modesto para preguntarme.}
{19704}{}{No te incumbe.}
{19705}{}{No te interesa.}
{19706}{}{Eres demasiado idiota para conocerlos.}
{19707}{}{No estás autorizado a conocerlos.}
{19708}{}{No me interesan los juguetitos.}

# MBVATS12.MAP  (20200)

{20200}{}{Maestro}
{20201}{}{Teniente}
{20202}{}{Niños del la Catedral}
{20203}{}{Seguidores del Apocalipsis}
{20204}{}{Nocturnos}
{20205}{}{Supermutantes}
{20206}{}{Psíquicos}
{20207}{}{Experimentos}
{20208}{}{Chip de agua}
{20300}{}{No tengo nada que decirte.}
{20301}{}{Tal conocimiento no corresponde a seres inferiores.}
{20302}{}{No necesitas relacionarte con ellos.}
{20303}{}{Eres demasiado modesto para preguntarme.}
{20304}{}{No te incumbe.}
{20305}{}{No te interesa.}
{20306}{}{Eres demasiado idiota para conocerlos.}
{20307}{}{No estás autorizado a conocerlos.}
{20308}{}{No me interesan los juguetitos.}


# MSTRLR12.MAP  (20800)

{20800}{}{Maestro}
{20801}{}{Teniente}
{20802}{}{Niños del la Catedral}
{20803}{}{Seguidores del Apocalipsis}
{20804}{}{Nocturnos}
{20805}{}{Supermutantes}
{20806}{}{Psíquicos}
{20807}{}{Experimentos}
{20808}{}{Chip de agua}
{20900}{}{No tengo nada que decirte.}
{20901}{}{Tal conocimiento no corresponde a seres inferiores.}
{20902}{}{No necesitas relacionarte con ellos.}
{20903}{}{Eres demasiado modesto para preguntarme.}
{20904}{}{No te incumbe.}
{20905}{}{No te interesa.}
{20906}{}{Eres demasiado idiota para conocerlos.}
{20907}{}{No estás autorizado a conocerlos.}
{20908}{}{No me interesan los juguetitos.}

# MSTRLR34.MAP  (21400)

{21400}{}{Maestro}
{21401}{}{Teniente}
{21402}{}{Niños de la Catedral}
{21403}{}{Seguidores del Apocalipsis}
{21404}{}{Nocturnos}
{21405}{}{Supermutantes}
{21406}{}{Psíquicos}
{21407}{}{Experimentos}
{21408}{}{Chip de agua}
{21500}{}{No tengo nada que decirte.}
{21501}{}{Tal conocimiento no corresponde a seres inferiores.}
{21502}{}{No necesitas relacionarte con ellos.}
{21503}{}{Eres demasiado modesto para preguntarme.}
{21504}{}{No te incumbe.}
{21505}{}{No te interesa.}
{21506}{}{Eres demasiado idiota para conocerlos.}
{21507}{}{No estás autorizado a conocerlos.}
{21508}{}{No me interesan los juguetitos.}


# V13ENT.MAP    (22000)

# HUBENT.MAP    (22600)

{22600}{}{Policía}
{22601}{}{Mercaderes de Agua}
{22602}{}{Caravana Carmesí}
{22603}{}{Comerciantes de Ultramar}
{22604}{}{Niños del la Catedral}
{22605}{}{Necrópolis}
{22606}{}{Zona Caliente}
{22607}{}{Ciudad Vertedero}
{22608}{}{Hermandad del Acero}
{22609}{}{Arenas Sombrías}
{22610}{}{Cementerio de Angel}
{22611}{}{Torres de Agua}
{22612}{}{Ciudad Antigua}
{22613}{}{Centro de la ciudad}
{22614}{}{Alturas}
{22615}{}{Garra Mortal}
{22616}{}{Chip de agua}
{22700}{}{El Sheriff Greene dirige la Policía. Su deber es mantener el orden y la ley en el Eje. Algunos
 creen que, más que una ayuda, son un estorbo.}
{22701}{}{Controlan toda el agua en el Eje. Ejercen el control de las Torres de Agua y ahora
 la gente tiene que pagarles para conseguir agua.}
{22702}{}{Son un grupo de comerciantes locos que se arriesgan mucho para llegar a lo más alto.}
{22703}{}{Son un grupo de comerciantes poco dispuestos, que ofrecen precios interesantes sin tener que correr grandes riesgos.}
{22704}{}{Son un grupo religioso que veneran a algo llamado el Maestro. Dirigen un hospital en la zona sudeste de la ciudad,
 cerca de los Mercaderes de Agua.}
{22705}{}{Un lugar horripilante. Algunos dicen que lo frecuentan mutantes que se alimentan con sesos de humanos normales. Está
 en algún lugar al este del Eje. }
{22706}{}{Algunas leyendas dicen que en un lugar al sudeste de aquí cayó una cabeza nuclear.}
{22707}{}{Está al norte de aquí. Solemos comerciar bastante con ellos. Hay rumores de que Killian y
 Gizmo se atacan unos a otros todo el tiempo.}
{22708}{}{Está al noroeste de aquí. Son un puñado de locos de la tecnología que se pasan el día venerándola. Son bastante horripilantes.}
{22709}{}{Una ciudad primitiva que está bastante al norte de aquí. No se sabe mucho de ellos, porque no tienen suficientes chapas
 para comerciar con nosotros.}
{22710}{}{Ese lugar infectado de ratas está acribillado por las guerras de bandas. Si no fuera por todo el comercio con Adytum y los Pistoleros,
 ningún comerciante se atrevería a ir allí.}
{22711}{}{Esos roban el agua para el Eje. Los Mercaderes de Agua controlan las torres.}
{22712}{}{Ciudad Antigua está al noreste de la ciudad. Los únicos que merodean por allí son mutantes y yonquis. He oído que
 hay una guarida de ladrones por ahí.}
{22713}{}{Allí venden cosas los Mercaderes. Los Almacenes Todo en Uno, la Armería, la Compañía de Crédito Amistoso y el Halcón Maltés están
 en esa zona.}
{22714}{}{Allí viven los mercaderes ricos. El líder de los Mercaderes de Agua, Daren Hightower, tiene una casa enorme allí.}
{22715}{}{Es un mito para asustar a los niños y hacer que se porten bien.}
{22716}{}{No sé nada de eso.}

# DETHCLAW.MAP  (23200)

# HUBDWNTN.MAP  (23800)

{23800}{}{Policía}
{23801}{}{Mercaderes de Agua}
{23802}{}{Caravana Carmesí}
{23803}{}{Comerciantes de Ultramar}
{23804}{}{Niños de la Catedral}
{23805}{}{Necrópolis}
{23806}{}{Zona Caliente}
{23807}{}{Ciudad Vertedero}
{23808}{}{Hermandad del Acero}
{23809}{}{Arenas Sombrías}
{23810}{}{Cementerio de Angel}
{23811}{}{Torres de Agua}
{23812}{}{Ciudad Antigua}
{23813}{}{Centro de la ciudad}
{23814}{}{Alturas}
{23815}{}{Garra Mortal}
{23816}{}{Chip de agua}
{23900}{}{El Sheriff Greene dirige la Policía. Su deber es mantener el orden y la ley en el Eje. Algunos
 creen que, más que una ayuda, son un estorbo.}
{23901}{}{Controlan toda el agua en el Eje. Ejercen el control de las Torres de Agua y ahora
 la gente tiene que pagarles para conseguir agua.}
{23902}{}{Son un grupo de comerciantes locos que se arriesgan mucho para llegar a lo más alto.}
{23903}{}{Son un grupo de comerciantes poco dispuestos, que ofrecen buenos precios sin tener que correr grandes riesgos.}
{23904}{}{Son un grupo religioso que veneran a algo llamado el Maestro. Dirigen un hospital en la zona sudeste de la ciudad,
 cerca de los Mercaderes de Agua.}
{23905}{}{Un lugar horripilante. Algunos dicen que lo frecuentan mutantes que se alimentan con sesos de humanos normales. Está
 en algún lugar al este del Eje.}
{23906}{}{Algunas leyendas dicen que en un lugar al sudeste de aquí cayó una cabeza nuclear.}
{23907}{}{Está al norte de aquí. Solemos comerciar bastante con ellos. Hay rumores de que Killian y
 Gizmo se atacan unos a otros todo el tiempo.}
{23908}{}{Está al noroeste de aquí. Son un puñado de locos de la tecnología que se pasan el día venerándola. Son bastante horripilantes.}
{23909}{}{Una primitiva ciudad que está bastante al norte de aquí. No se sabe mucho de ellos, porque no tienen suficientes chapas
 para comerciar con nosotros.}
{23910}{}{Ese lugar infectado de ratas está acribillado por las guerras de bandas. Si no fuera por todo el comercio con Adytum y los Pistoleros,
 dudo mucho que ningún comerciante se atreviera a ir allí.}
{23911}{}{Esos roban el agua para el Eje. Los Mercaderes de Agua controlan las torres.}
{23912}{}{Ciudad Antigua está en el lado noreste de la ciudad. Los únicos que merodean por allí son mutantes y yonquis. He oído que
 hay una guarida de ladrones en algún lugar.}
{23913}{}{Es donde los Mercaderes venden cosas. Los Almacenes Todo en Uno, la Armería, la Compañía de Crédito Amistoso y el Halcón Maltés están
 en esa zona.}
{23914}{}{Es el lugar de residencia de los mercaderes ricos. El líder de los Mercaderes de Agua, Daren Hightower, tiene una casa enorme allí.}
{23915}{}{Es un mito para asustar a los niños y hacer que se porten bien.}
{23916}{}{No sé nada de eso.}

# HUBHEIGT.MAP  (24400)

{24400}{}{Policía}
{24401}{}{Mercaderes de Agua}
{24402}{}{Caravana Carmesí}
{24403}{}{Comerciantes de Ultramar}
{24404}{}{Niños de la Catedral}
{24405}{}{Necrópolis}
{24406}{}{Zona Caliente}
{24407}{}{Ciudad Vertedero}
{24408}{}{Hermandad del Acero}
{24409}{}{Arenas Sombrías}
{24410}{}{Cementerio de Angel}
{24411}{}{Torres de Agua}
{24412}{}{Ciudad Antigua}
{24413}{}{Centro de la ciudad}
{24414}{}{Alturas}
{24415}{}{Garra Mortal}
{24416}{}{Chip de agua}
{24500}{}{El Sheriff Greene dirige la Policía. Su deber es mantener el orden y la ley en el Eje. Algunos
 creen que, más que una ayuda, son un estorbo.}
{24501}{}{Controlan toda el agua en el Eje. Ejercen el control de las Torres de Agua y ahora
 la gente tiene que pagarles para conseguir agua.}
{24502}{}{Son un grupo de comerciantes locos que se arriesgan mucho para llegar a lo más alto.}
{24503}{}{Son un grupo de comerciantes poco dispuestos, que ofrecen buenos precios sin tener que correr grandes riesgos.}
{24504}{}{Son un grupo religioso que veneran a algo llamado el Maestro. Dirigen un hospital en la zona sudeste de la ciudad
 cerca de los Mercaderes de Agua.}
{24505}{}{Un lugar horripilante. Algunos dicen que lo frecuentan mutantes que se alimentan con sesos de humanos normales. Está
 en algún lugar al este del Eje.}
{24506}{}{Algunas leyendas dicen que en un lugar al sudeste de aquí cayó una cabeza nuclear.}
{24507}{}{Está al norte de aquí. Solemos comerciar bastante con ellos. Hay rumores de que Killian y
 Gizmo se atacan unos a otros todo el tiempo.}
{24508}{}{Está al noroeste de aquí. Son un puñado de locos de la tecnología que se pasan el día venerándola. Son bastante horripilantes.}
{24509}{}{Una ciudad primitiva que está bastante al norte de aquí. No se sabe mucho de ellos, porque no tienen suficientes chapas
 para comerciar con nosotros.}
{24510}{}{Ese lugar infectado de ratas está acribillado por las guerras de bandas. Si no fuera por todo el comercio con Adytum y los Pistoleros,
 ningún comerciante se atrevería a ir allí.}
{24511}{}{Esos roban el agua para el Eje. Los Mercaderes de Agua controlan las torres.}
{24512}{}{Ciudad Antigua está en el lado noreste de la ciudad. Los únicos que merodean por allí son mutantes y yonquis. He oído que
 hay una guarida de ladrones por allí.}
{24513}{}{Allí venden cosas los Mercaderes. Los Almacenes Todo en Uno, la Armería, la Compañía de Crédito Amistoso y el Halcón Maltés están
 en esa zona.}
{24514}{}{Allí viven los mercaderes ricos. El líder de los Mercaderes de Agua, Daren Hightower tiene una casa enorme allí.}
{24515}{}{Es un mito para asustar a los niños y hacer que se porten bien.}
{24516}{}{No sé nada de eso.}

# HUBOLDTN.MAP  (25000)

{25000}{}{Policía}
{25001}{}{Mercaderes de Agua}
{25002}{}{Caravana Carmesí}
{25003}{}{Comerciantes de Ultramar}
{25004}{}{Niños de la Catedral}
{25005}{}{Necrópolis}
{25006}{}{Zona Caliente}
{25007}{}{Ciudad Vertedero}
{25008}{}{Hermandad del Acero}
{25009}{}{Arenas Sombrías}
{25010}{}{Cementerio de Angel}
{25011}{}{Torres de Agua}
{25012}{}{Ciudad Antigua}
{25013}{}{Centro de la ciudad}
{25014}{}{Alturas}
{25015}{}{Garra Mortal}
{25016}{}{Chip de agua}
{25100}{}{El Sheriff Greene dirige la Policía. Su deber es mantener el orden y la ley en el Eje. Algunos
 creen que, más que una ayuda, son un estorbo.}
{25101}{}{Controlan toda el agua en el Eje. Ejercen el control en las Torres de Agua y ahora
 la gente tiene que pagarles para conseguir agua.}
{25102}{}{Son un grupo de comerciantes locos que se arriesgan mucho para llegar a lo más alto.}
{25103}{}{Son un grupo de comerciantes poco dispuestos que ofrecen buenos precios sin tener que correr grandes riesgos.}
{25104}{}{Son un grupo religioso que veneran a algo llamado el Maestro. Dirigen un hospital en la zona sudeste de la ciudad
 cerca de los Mercaderes de Agua.}
{25105}{}{Un lugar horripilante. Algunos dicen que lo frecuentan mutantes que se alimentan con sesos de humanos normales. Está
 en algún lugar al este del Eje.}
{25106}{}{Algunas leyendas dicen que en un lugar al sudeste de aquí cayó una cabeza nuclear.}
{25107}{}{Está al norte de aquí. Solemos comerciar bastante con ellos. Hay rumores de que Killian y
 Gizmo se atacan unos a otros todo el tiempo.}
{25108}{}{Está al noroeste de aquí. Son un puñado de locos de la tecnología que se pasan el día venerándola. Son bastante horripilantes.}
{25109}{}{Una ciudad primitiva que está bastante al norte de aquí. No se sabe mucho de ellos, porque no tienen suficientes chapas
 para comerciar con nosotros.}
{25110}{}{Ese lugar infectado de ratas está acribillado por las guerras de bandas. Si no fuera por todo el comercio con Adytum y los Pistoleros,
 ningún comerciante se atrevería a ir allí.}
{25111}{}{Esos roban el agua para el Eje. Los Mercaderes de Agua controlan las torres.}
{25112}{}{Ciudad Antigua está en el lado noreste de la ciudad. Los únicos que merodean por allí son mutantes y yonquis. He oído que
 hay una guarida de ladrones por allí.}
{25113}{}{Allí venden cosas los Mercaderes. Los Almacenes Todo en Uno, la Armería, la Compañía de Crédito Amistoso y el Halcón Maltés están
 en esa zona.}
{25114}{}{Allí viven todos los mercaderes ricos. El líder de los Mercaderes de Agua, Daren Hightower, tiene una casa enorme allí.}
{25115}{}{Es un mito para asustar a los niños y hacer que se porten bien.}
{25116}{}{No sé nada de eso.}

# HUBWATER.MAP  (25600)

{25600}{}{Policía}
{25601}{}{Mercaderes de Agua}
{25602}{}{Caravana Carmesí}
{25603}{}{Comerciantes de Ultramar}
{25604}{}{Niños de la Catedral}
{25605}{}{Necrópolis}
{25606}{}{Zona Caliente}
{25607}{}{Ciudad Vertedero}
{25608}{}{Hermandad del Acero}
{25609}{}{Arenas Sombrías}
{25610}{}{Cementerio de Angel}
{25611}{}{Torres de Agua}
{25612}{}{Ciudad Antigua}
{25613}{}{Centro de la ciudad}
{25614}{}{Alturas}
{25615}{}{Garra Mortal}
{25616}{}{Chip de agua}
{25700}{}{El Sheriff Greene dirige la Policía. Su deber es mantener el orden y la ley en el Eje. Algunos
 creen que, más que una ayuda, son un estorbo.}
{25701}{}{Controlan toda el agua en el Eje. Ejercen el control en las Torres de Agua y ahora
 la gente tiene que pagarles para conseguir agua.}
{25702}{}{Son un grupo de comerciantes locos que se arriesgan mucho para llegar a lo más alto.}
{25703}{}{Son un grupo de comerciantes poco dispuestos, que ofrecen buenos precios sin tener que correr grandes riesgos.}
{25704}{}{Son un grupo religioso que veneran a algo llamado el Maestro. Dirigen un hospital en la zona sudeste de la ciudad
 cerca de los Mercaderes de Agua.}
{25705}{}{Un lugar horripilante. Algunos dicen que lo frecuentan mutantes que se alimentan con sesos de humanos normales. Está
 en algún lugar al este del Eje.}
{25706}{}{Algunas leyendas dicen que en un lugar al sudeste de aquí cayó una cabeza nuclear.}
{25707}{}{Está al norte de aquí. Solemos comerciar bastante con ellos. Hay rumores de que Killian y
 Gizmo se atacan unos a otros todo el tiempo.}
{25708}{}{Está al noroeste de aquí. Son un puñado de locos de la tecnología que se pasan el día venerándola. Son bastante horripilantes.}
{25709}{}{Una ciudad primitiva que está bastante al norte de aquí. No se sabe mucho de ellos, porque no tienen suficientes chapas
 para comerciar con nosotros.}
{25710}{}{Ese lugar infectado de ratas está acribillado por las guerras de bandas. Si no fuera por todo el comercio con Adytum y los Pistoleros,
 ningún comerciante se atrevería a ir allí.}
{25711}{}{Esos roban el agua para el Eje. Los Mercaderes de Agua controlan las torres.}
{25712}{}{Ciudad Antigua está en el lado noreste de la ciudad. Los únicos que merodean por allí son mutantes y yonquis. He oído que
 hay una guarida de ladrones por allí.}
{25713}{}{Es donde los Mercaderes venden cosas. Los Almacenes Todo en Uno, la Armería, la Compañía de Crédito Amistoso y el Halcón Maltés están
 en esa zona.}
{25714}{}{Es el lugar de residencia de los mercaderes ricos. El líder de los Mercaderes de Agua, Daren Hightower, tiene una casa enorme allí.}
{25715}{}{Es un mito para asustar a los niños y hacer que se porten bien.}
{25716}{}{No sé nada sobre eso.}

# GLOW1.MAP     (26200)
# GLOW2.MAP     (26800)


#
# LABLADES.MAP
#
#

#  ======================================================================
#    BLADES
# Info Level 1 [People who know nothing]
{27400}{}{Adytum}
{27401}{}{Seguidores}
{27402}{}{Catedral}
{27403}{}{Destripadores}
{27404}{}{Navajas}
{27405}{}{Pistoleros}
{27406}{}{Eje}
{27407}{}{Ciudad Vertedero}
{27408}{}{Chip de agua}
{27409}{}{Cuchilla}
{27410}{}{Necrópolis}
{27411}{}{Ardor}
{27412}{}{Cementerio}
{27500}{}{Es una ciudad situada al oeste.}
{27501}{}{Un puñado de imbéciles.}
{27502}{}{Son unos fanáticos.}
{27503}{}{¡Nuestros malditos enemigos!}
{27504}{}{¡Esos somos nosotros!}
{27505}{}{A veces nos venden armas.}
{27506}{}{Creo que es un lugar para hacer negocios.}
{27507}{}{Nunca he oído hablar de ese sitio.}
{27508}{}{¿Un qué?}
{27509}{}{Es nuestra jefa, ¡la perra con más malas pulgas de toda la ciudad!}
{27510}{}{¿Necro qué? Eso es enfermizo.}
{27511}{}{Estás bromeando, ¿verdad?}
{27512}{}{Esto es el Cementerio.}


# Info Level 2 [People who know something]
{27600}{}{Adytum}
{27601}{}{Seguidores}
{27602}{}{Catedral}
{27603}{}{Destripadores}
{27604}{}{Navajas}
{27605}{}{Pistoleros}
{27606}{}{Eje}
{27607}{}{Ciudad Vertedero}
{27608}{}{Chip de agua}
{27609}{}{Cuchilla}
{27610}{}{Necrópolis}
{27611}{}{Ardor}
{27612}{}{Cementerio}
{27700}{}{Es un pueblo de debiluchos que está al sudoeste.}
{27701}{}{Patéticos predicadores de la paz, en dirección oeste. Los machacaríamos si no estuviésemos
 tan ocupados con los Destripadores.}
{27702}{}{Extraños religiosos. Inofensivos e inútiles.}
{27703}{}{¡Machacaremos pronto a nuestros grandes enemigos del oeste!}
{27704}{}{¡Nosotros somos los Navajas! ¡Nunca lo olvides!}
{27705}{}{Durante un tiempo fueron una banda pero se volvieron débiles. Pero venden buenas
 armas.}
{27706}{}{Comerciantes y mercaderes.}
{27707}{}{He oído hablar de ese sitio pero no sé nada más.}
{27708}{}{¿Un qué?}
{27709}{}{Cuchilla es la mejor guerrera de todos nosotros. Nos conduce hacia la
 victoria.}
{27710}{}{Con esa historia de una ciudad llena de caníbales solíamos asustar a los niños.}
{27711}{}{Debe ser donde cayó la cabeza nuclear.}
{27712}{}{Esto es el Cementerio.}


# Info level 3 [People who know more than something but less than everything]
{27800}{}{Adytum}
{27801}{}{Seguidores}
{27802}{}{Catedral}
{27803}{}{Destripadores}
{27804}{}{Navajas}
{27805}{}{Pistoleros}
{27806}{}{Eje}
{27807}{}{Ciudad Vertedero}
{27808}{}{Chip de agua}
{27809}{}{Cuchilla}
{27810}{}{Necrópolis}
{27811}{}{Ardor}
{27812}{}{Cementerio}
{27900}{}{No caigas en la trampa. Adytum parece un pequeño pueblo, pero sus
 Reguladores son muy duros.}
{27901}{}{Hmph. No me provoques. No tienen el estómago ni el coraje necesarios para
 luchar.}
{27902}{}{Se dedican al culto en una gran iglesia situada al sur. Parecen inofensivos, pero
 algo horrible se está tramando allí.}
{27903}{}{Los Destripadores son como perros sarnosos... viciosos, consanguíneos y estúpidos.}
{27904}{}{¿Ves mi espada? Las hacemos nosotros mismos. Cada uno tiene la suya.
 De ahí nuestro nombre.}
{27905}{}{Vinieron del Eje buscando tierras, pero decidieron
 convertirse en vendedores en vez de guerreros.}
{27906}{}{Es una ciudad comercial situada al este. A veces vienen Mercaderes de allí
 para comerciar con Adytum y con los Pistoleros.}
{27907}{}{Creo que está al noreste de aquí. Es una ciudad pequeña.}
{27908}{}{¿Un qué?}
{27909}{}{Cuchilla es nuestra líder y campeona. Estoy seguro de que su experiencia
 al final nos hará ganar a esos Destripadores.}
{27910}{}{Está bastante al este de aquí. Supuestamente, viven allí demonios que comen carne humana.
 No me gustaría tener que luchar contra esos necrófagos.}
{27911}{}{Se supone que son las ruinas de un lugar en el que cayó
 una cabeza nuclear. Creo que está hacia el sur.}
{27912}{}{Esto es el Cementerio.}
#  ======================================================================


#
# LARIPPER.MAP  (28000)
#
#

#======================================================================
#
#RIPPERS
#
#The Rippers will not engage in dialog, and thus have no
#tell-me-abouts.
#
#======================================================================


#
# LAGUNRUN.MAP  (28600)
#
#

#  ======================================================================
#   GUN RUNNERS
#Info Level 1 [People who know nothing]
{28600}{}{Adytum}
{28601}{}{Seguidores}
{28602}{}{Catedral}
{28603}{}{Destripadores}
{28604}{}{Navajas}
{28605}{}{Pistoleros}
{28606}{}{Eje}
{28607}{}{Ciudad Vertedero}
{28608}{}{Chip de agua}
{28609}{}{Cementerio}
{28700}{}{Un pequeño pueblo que está al sur de aquí.}
{28701}{}{Un grupo de hippies que están en el sur.}
{28702}{}{¿Te refieres a esos tipos con trajes marrones?}
{28703}{}{Una banda de provocadores del oeste.}
{28704}{}{Una banda de ladronzuelos del este.}
{28705}{}{¿Sí? ¿Qué?}
{28706}{}{¡Les compramos armas y te las vendemos directamente!}
{28707}{}{Sí, una pequeña ciudad al norte del Eje.}
{28708}{}{¿Un qué?}
{28709}{}{Esto es el Cementerio.}

# Info Level 2 [People who know something]
{28800}{}{Adytum}
{28801}{}{Seguidores}
{28802}{}{Catedral}
{28803}{}{Destripadores}
{28804}{}{Navajas}
{28805}{}{Pistoleros}
{28806}{}{Eje}
{28807}{}{Ciudad Vertedero}
{28808}{}{Chip de agua}
{28809}{}{Cementerio}
{28900}{}{Es un pequeño pueblo situado al sur. Está bastante bien fortificado.}
{28901}{}{Un grupo de amantes de la paz que se esconden al sur de aquí. Deberíamos
 deshacernos de ellos.}
{28902}{}{Oh sí, eso viejos monjes locos. Están chiflados. Tienen una iglesia enorme
 al sur del Cementerio.}
{28903}{}{¡Eh, serán estúpidos, pero compran un montón de armas!}
{28904}{}{Siempre usan esos vibro-cuchillos que fabrican. Me gustaría
 meterle las zarpas a uno. Al menos compran algunas armas.}
{28905}{}{Estás hablando con nosotros.}
{28906}{}{Es un gran centro comercial situado al este. Comerciamos con los mercaderes del Eje para
 comprar y vender armas.}
{28907}{}{Una pequeña ciudad al norte del Eje. Algo estricta.}
{28908}{}{Nunca he oído hablar de eso.}
{28909}{}{Estamos en la zona norte del Cementerio.}

# Info Level 3 [People who know more than something but less than everything]
{29000}{}{Adytum}
{29001}{}{Seguidores}
{29002}{}{Catedral}
{29003}{}{Destripadores}
{29004}{}{Navajas}
{29005}{}{Pistoleros}
{29006}{}{Eje}
{29007}{}{Ciudad Vertedero}
{29008}{}{Chip de agua}
{29009}{}{Cementerio}
{29100}{}{Es una pequeña ciudad situada al sur. No tratan con nosotros.
 No me importan nada.}
{29101}{}{Intentan convertir a todos a su ideal de paz mientras se esconden
 en su Biblioteca al sur. ¡No nos ayudan en los negocios!}
{29102}{}{La Catedral es esa iglesia grande situada al sur del Cementerio, donde algunos
 rinden culto de forma extraña al Dios Oscuro. Creo que están locos.}
{29103}{}{Los Destripadores son literalmente una gran familia. Es imposible tratar con ellos
 si no te conocen, así que ni siquiera lo intentes. Viven en una gran
 fortaleza al sur de aquí. Si eres tan estúpido como para ir,
 ten cuidado con las minas.}
{29104}{}{Han convertido varios edificios pequeños del sudeste en su
 hogar. Están bastante bien organizados y son más listos que los Destripadores.
 A veces dejan que los forasteros se unan a ellos. Su líder, Cuchilla, es una
 mujer dura.}
{29105}{}{Esos somos nosotros. Sacamos bastantes chapas vendiendo armas a los Navajas y a los Destripadores.}
{29106}{}{Esa es la ciudad comercial situada al este de aquí donde conseguimos nuestras armas
 y comerciamos. Envían caravanas a todos sitios. Probablemente podrás
 viajar con una caravana cuando se pare en Adytum.}
{29107}{}{Es una pequeña ciudad fronteriza situada al norte del Eje. Hay un Casino
 enorme allí, pero el Sheriff es demasiado
 autoritario.}
{29108}{}{No tengo ni idea de lo que es.}
{29109}{}{Esta es la zona norte del Cementerio. Es gracioso, la gente de
 fuera usa la expresión "Morder el polvo".
 Pero cuando te acostumbras a vivir aquí no está tan mal.}
#  ======================================================================


# CHILDEAD.MAP  (29200)

# MBDEAD.MAP    (29800)

# MOUNTN1.MAP   (30400)
# MOUNTN2.MAP   (31000)
# FOOT.MAP      (31600)
# TARDIS.MAP    (32200)
# TALKCOW.MAP   (32800)
# USEDCAR.MAP   (33400)
# BRODEAD.MAP   (34000)
# DESCRVN1.MAP  (34600)
# DESCRVN2.MAP  (35200)
# MNTCRVN1.MAP  (35800)
# MNTCRVN2.MAP  (36400)
