{100}{}{¡Tú! ¡Detente y enfréntate a la ley!}
{101}{}{Gracias por traer el Chip de agua. Así subirá la moral de los habitantes del refugio y respetarán la ley del refugio.}
{102}{}{Me alegro de volver a verte. ¿Hay algo que pueda hacer por ti?}
{103}{}{¿Qué haces?}
{104}{}{Sí, necesito algunas armas.}
{105}{}{¿Por qué iba a haber una puerta cerrada en el Refugio?}
{106}{}{¡Glop!}
{107}{}{Mmm. Creo que deberías estar en otro sitio lejos de aquí. Que tengas un buen día.}
{108}{}{Estoy encargado de la seguridad y del cumplimiento de la ley en el Refugio.
 Por si no lo sabes, el Refugio no funcionaría tan bien si no fuera por mí.}
{109}{}{Mmm. Claro. Gracias.}
{110}{}{Parece importante.}
{111}{}{Lo es. Sin el justo cumplimiento de las leyes, el Refugio
 sería pronto un lugar sin ley, sin reglas. Eso pondría en peligro
 la seguridad de todos nosotros.}
{112}{}{Ahora que he estado en el exterior, ¿hay alguna ley que se me aplique
 específicamente a mí?}
{113}{}{He visto algunos lugares en el mundo exterior que sufren
 porque les faltan leyes.}
{114}{}{Bueno, aunque en el mundo exterior se necesiten armas, haz el favor de no enseñarlas de modo amenazador aquí.
 Es lo único que se me ocurre.}
{115}{}{Gracias.}
{116}{}{¿Lo ves? Sabía que ocurriría. La obediencia a la ley
 es lo único que ha salvado al Refugio de la miseria
 y la destrucción. Adelante con el buen trabajo.}
{117}{}{El Supervisor no me ha dejado abrir la armería y
 conseguir más armas para tí. Lo siento, pero no puedo ayudarte.}
{118}{}{¡Por favor! ¡Las necesito!}
{119}{}{De acuerdo. Gracias de todos modos.}
{120}{}{No. No puedo hacerlo.}
{121}{}{Que tengas un buen día.}
{122}{}{Para mantener las armas alejadas de aquellos que no tienen
 acceso a ellas.}
{123}{}{¿Quién tiene acceso?}
{124}{}{Eso no me parece muy justo.}
{125}{}{La vida no es justa, a veces. Pero nuestra ley sí. Que tengas
 un buen día.}
{126}{}{El Supervisor, mi equipo de seguridad y yo. Así es.}
{127}{}{Parece que sólo tiene acceso la gente que lo necesita.}
{128}{}{La lista es realmente corta.}
{129}{}{Sí, en efecto. Tengo que volver al trabajo.}
{130}{}{Sí, sólo la gente que lo necesita tiene acceso.}
{131}{}{Pues yo lo necesito. Por favor, abre la puerta.}
{132}{}{Lo siento, es un buen argumento, pero no te puedo dejar entrar.}
{133}{}{Mmm. Ahora que lo mencionas, parece que es cierto. Voy a
 a abrirte la puerta.}
{134}{}{¿Qué puedo hacer por ti, }
{135}{}{?}
{136}{}{Necesito más armas.}
{137}{}{¿Te encuentras bien?}
{138}{}{Ajá.}
{139}{}{Estupendo. Tu inteligencia es asombrosa. Posiblemente no puedo
 pensar más.}
{140}{}{Lo siento, ya tienes todo lo que podemos ofrecerte. Buen día.}
{141}{}{No me gustan los tipos como tú. Agitadores. Deberíais avergonzaros.}
{142}{}{Pues lo mismo te digo, tonto del culo.}
{143}{}{¿No crees que eres demasiado severo?}
{144}{}{Vigila tu lenguaje o te arrestaré por falta de
 respeto a un oficial encargado del cumplimiento de la ley.}
{145}{}{Sí, eso. Hasta la vista.}
{146}{}{Eso es. Estoy harto que me provoques.}
{147}{}{Mmm. Posiblemente. Debería ser imparcial en mi trabajo,
 pero esta vez voy a pasarme de la raya.
 Intentaré hacerlo mejor en el futuro.}
{148}{}{Mmm. No. Probablemente no lo suficiente.}
{149}{}{Buena suerte. Espero que puedas hacer el trabajo.}
{150}{}{Será mejor que no me decepciones.}
{151}{}{Aparta el arma ahora mismo.}
{152}{}{¿Qué crees que estás haciendo con eso aquí?}
{153}{}{Sólo practicando mi puntería.}
{154}{}{Nada, lo siento. No tenía intención de hacerlo.}
{155}{}{Colgado.}
{156}{}{Cuidado con lo que me dices. Y no lleves armas
 aquí dentro. Por dios, ¡esto es el Refugio!}
{157}{}{Será mejor que no practiques aquí. Tú y yo
 tendremos serios problemas si vuelves a hacerlo.}
{158}{}{Sabía que la vida del exterior te traería problemas.}
{159}{}{¡Alto! ¡No puedes entrar ahí!}

{1000}{}{Supervisor}
{1100}{}{Es la autoridad suprema del Refugio. El Refugio obedece a sus
 decisiones.}
