{100}{}{Estás viendo a Orfeo, uno de los miembros más antiguos de los Niños de la Catedral.}
{101}{}{¡Ah!, un nuevo converso. Bienvenido.}
{102}{}{¡¡¡Yo Matar!!!}
{103}{}{¡No soy un converso!}
{104}{}{Gracias, Hermano.}
{105}{}{Entonces nos ocuparemos de ese problema dentro de poco.}
{106}{}{Antes debemos limpiar las impurezas que los yermos han dejado en ti. Ven aquí.}
{107}{}{¡Te purificaremos!}
