{100}{}{Paladín}
{101}{}{Buen día, Iniciado.}
{102}{}{Si necesitas algo, debes hablar con Vree.}
{103}{}{Si necesitas hablar con alguien, Vree está justo ahí.}
{104}{}{Tengo que encontrar tiempo entre patrulla y patrulla y entrenarme para seguir
 con mis estudios. Creo que estoy falto de práctica.}
{105}{}{Iniciado, tienes que mantener tu mente y tu cuerpo en las mejores
 condiciones en todo momento.}
{106}{}{Nosotros los Escribas diseñamos todo el equipo, armas y suministros.
 Es muy emocionante.}
{107}{}{Ser Paladín no es sólo luchar, hijo.}
{108}{}{Ser Paladín no es sólo luchar, hija.}
