{100}{}{¡Fuera de aquí!}
{101}{}{He oído cosas malas de ti, ¿son verdad?}
{102}{}{Hola.}
{103}{}{Aquí mando yo. ¿Quieres estar colgado un ratito?}
{104}{}{Mmm, mi postre...}
{105}{}{Espero que no me eches de aquí.}
{106}{}{No.}
{107}{}{Es un modo extraño de empezar una conversación.}
{108}{}{Mmm.}
{109}{}{Oh, bueno, si quieres quedarte un rato, sigue todo recto. Creo que aquí
 estamos a salvo.}
{110}{}{En los tiempos que corren hay que andar con cuidado. Espero que tengas una vida mejor
 que la mía.}
{111}{}{Es verdad. Después de lo que les ocurrió a mis amigos, tengo que proteger mi territorio. Sólo espero que no vengas a matarme.}
{112}{}{No, no voy a hacerte mucho... daño.}
{113}{}{¿Por qué dices eso?}
{114}{}{¡Gack!}
{115}{}{No hay motivo. De verdad.}
# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
{116}{}{Aquellos tíos tan "generosos" querían las tierras de mi amigo, entonces se la quedaron.
 No sé que fue de mis amigos.}
{117}{}{ Y Killian está demasiado ocupado para ayudarme.}
{118}{}{ Killian está demasiado ocupado aclarando el asunto de Gizmo para ayudarme.}
{119}{}{ Gizmo se rió de mí cuando le pedí ayuda.}
{120}{}{ No hay nadie por aquí que pueda ayudarme.}
{121}{}{¿Estás a salvo?}
{122}{}{Es una pena.}
{123}{}{Eso espero, de verdad lo espero.}
{124}{}{Por favor, ¡déjame en paz!}
