{100}{}{Estás viendo a un campesino.}
{101}{}{Ah, ya, un hombre grande huyendo de un perro asustado. Seguro que era Phil. Sí, seguro que sí.}
{102}{}{¿Qué haces, Phil? Estás comprobando las huellas de esas
 zapatillas, ¿verdad?}
{103}{}{Tío, ese perro parece hambriento. Seguro que te comería vivo,
 Phil.}
{104}{}{Eso sería abusar de un pobre
 animal indefenso, ¿no crees?}
{105}{}{Seguro que ese animal que tienes ahí es un buen chucho.}
{106}{}{Seguro que Phil se pondría muy contento si te
 deshicieras de su perro.}
{107}{}{Gracias por ocuparte del perro.}
