{100}{}{Esta persona parece haber formado parte de la Hermandad del Acero.}
{101}{}{Te preguntas por qué esta persona de metal está aquí.}
{102}{}{Esta persona parece haber muerto por grandes cantidades de radiación.}
{103}{}{No puedes determinar la causa de la muerte de esta persona.}
{104}{}{Con esta destreza no obtienes más información sobre esa persona.}
