{100}{}{Estás viendo a un campesino.}
{101}{}{No tengo nada que decirte, extraño.}
{102}{}{Seguro que los Brahmins apestan en esta época del año.}
{103}{}{Todavía necesitamos expandir la irrigación.}
{104}{}{No me molestes.}
{105}{}{He oído que los Escorpiones Rad volvieron a matar anoche.}
{106}{}{¿Tienes alguna hamburguesa de Brahmin?}
{107}{}{Últimamente no he sido atacado por Piratas. Cuestión de suerte, supongo.}
