{100}{}{Radio}
{101}{}{[En la radio se oyen ruidos de interferencias y a continuación una voz
 de fondo.] Comandante a patrulla, comandante a patrulla. ¿Cuál es su estado?
 Cambio.}
{102}{}{¡Eek!}
{103}{}{Eh, todo va bien por aquí. Estamos bien, eh, ¿y usted?}
{104}{}{Comandante, nos está atacando un grupo importante de humanos
 armados. Necesitamos refuerzos. Cambio.}
{105}{}{¡Ayuda! ¡Atacantes desconocidos! ¡Daños graves! Las coordenadas son: 10... ¡Aaah!}
{106}{}{Entendido, patrulla. Enviamos refuerzos. Corto.}
{107}{}{¿Quién es? ¿Qué es lo que quiere?}
{108}{}{Lo que quiero es acabar con este infierno.}
{109}{}{Yo, eh, oh, da igual. Os voy a matar a todos de todas formas.}
{110}{}{Aquí, mmm, Fred. Mi obligación es patrullar. Supongo que estoy, eh,
 un poco aturdido por la caída.}
{111}{}{Entendido, patrulla. ¿Cuáles son sus coordenadas?}
{112}{}{224 - 104.}
{113}{}{Cuatro millas al sur - sudoeste.}
{114}{}{Sector Gamma, en Omicron-Delta-Beta.}
{115}{}{Entendido, patrulla. Cambio y corto.}
{116}{}{Entendido, patrulla. Enviamos refuerzos.}
{117}{}{Ah, eso lo explica. Ahora mismo enviamos ayuda.}
{118}{}{Recibido, patrulla. ¡Enseguida enviamos ayuda! ¡Ánimos!}
{119}{}{En la radio sólo se oyen interferencias.}
{120}{}{Oyes una conversación en la radio. Escuchas un rato,
 pero no te enteras de nada importante.}
{121}{}{La radio tiene una luz roja parpadeando. Por el altavoz,
 oyes interferencias estridentes.}
{122}{}{Parece un mensaje de audio codificado.}
{123}{}{Envías el código de comando para visualizar el campo
 de fuerza.}
{124}{}{En el canal de radio sólo se oyen interferencias normales.}
{125}{}{La radio no funciona.}
{126}{}{Esta radio funciona perfectamente. La causa
 del problema debe ser externa.}
{127}{}{En la radio sólo se oyen las interferencias de datos
 codificados.}
{128}{}{[Se oyen interferencias y el ruido de un golpe.] Aquí el comandante, adelante, patrulla.}
{129}{}{¡Ack!}
{130}{}{Oh, lo siento Comandante. Golpeé el botón de comunicación por error.}
{131}{}{¡Intrusos en la base! ¡Alerta!}
{132}{}{Recibido, patrulla, cambio y corto.}
{133}{}{[Marcas la frecuencia de la radio para el canal del control de
 seguridad] [¡Clic!] Introducir número de acceso. [¡Clic!]}
{134}{}{¡Hng!}
{135}{}{Uh, 69.}
{136}{}{5566534571.}
{137}{}{Fin del acceso.}
{138}{}{Cerrado canal de seguridad automático.}
{139}{}{Ganas 1.500 puntos de experiencia por engañar a los guardias mutantes.}
{140}{}{Ganas 2.000 puntos de experiencia por meterte a escondidas en las profundidades de
 la base militar sin ser capturado (todavía)...}