{100}{}{Ves a Cindy llorando.}
{101}{}{Ves a Lisa llorando.}
{102}{}{Ves a Sandy llorando.}
{103}{}{Ves a Mary llorando.}
{104}{}{Ves a Stacy llorando.}
{105}{}{Ves a Susan llorando.}
{106}{}{Ves a Cindy.}
{107}{}{Ves a Lisa.}
{108}{}{Ves a Sandy.}
{109}{}{Ves a Mary.}
{110}{}{Ves a Stacy.}
{111}{}{Ves a Susan.}
{112}{}{Hola, }
{113}{}{.
 ¿Ya has encontrado el Chip de agua?}
{114}{}{No, todavía no.}
{115}{}{Lo encontraré. ¿Cómo te va?}
{116}{}{¡Bah!}
{117}{}{Oh... no me comprendes. Supongo que después de todo
 no tenemos muchas esperanzas. Discúlpame por llorar.}
{118}{}{¡Ugg!}
{119}{}{Por favor, encuéntralo antes de que mi bebé muera de sed.}
{120}{}{[Hecho]}
{121}{}{¡Tienes que encontrarlo! ¡No nos dejes morir así!}
{122}{}{[Hecho]}
{123}{}{Sigue intentándolo. Creo en ti. Sé que harás todo lo posible
 para salvarnos.}
{124}{}{[Hecho]}
{125}{}{Tengo miedo de lo que está ocurriendo. Alguien está robando
 agua y ahora todos tienen los nervios de punta.}
{126}{}{¿Quién haría una cosa así?}
{127}{}{¿Qué pasó?}
{128}{}{Algunos han sido acusados y empieza a haber peleas,
 pero nadie sabe lo que pasa realmente.}
{129}{}{Vale. Gracias.}
{130}{}{Algunos dijeron que les habían robado el agua.
 No se les dio más agua, pero algunos amigos la compartieron
 con ellos. Después de eso la gente se volvió paranoica y
 empezó a guardar el agua. Unos días después
 alguien golpeó al guardia en la zona de racionamiento del suministro
 y robó agua.}
{131}{}{¡Eso es terrible! ¿Qué puedo hacer yo?}
{132}{}{Quizás puedas detener al culpable.}
{133}{}{Echaré un vistazo por ahí.}
