{100}{}{Hola, ¿qué puedo hacer por ti?}
{101}{}{¿Quién eres?}
{102}{}{¿Eres el líder de esta banda?}
{103}{}{No importa.}
{104}{}{¿Que... qué?}
{105}{}{Me llamo Cuchilla. Soy lo más parecido a un líder.}
{106}{}{¿Así que eres la jefa de la banda?}
{107}{}{¿Cuál es la historia de la zona vallada del sur?}
# Fixed with patch 1.2 from TeamX. Player's name will be substitued at the end of the line 108.
{108}{}{Me alegro de conocerte. Soy }
{109}{}{Me alegro de conocerte. Pero debo irme.}
{110}{}{¿Banda? Apenas somos una banda. Pero yo soy la jefa.}
{111}{}{Si no sois una banda, entonces ¿qué sois?}
{112}{}{Bueno, a mí me parecéis una banda.}
{113}{}{Adiós.}
{114}{}{Eso es Adytum. Es un campo de trabajo de esclavos dirigido por un grupo llamado los Reguladores, pero ellos dicen a todo el mundo que es una "ciudad". Vienen aquí, se llevan a nuestra gente y la hacen trabajar hasta que mueren. Luego vuelven y se llevan a más de nosotros.}
{115}{}{¿No podéis ir allí y liberar a vuestra gente?}
{116}{}{¿Entonces para qué hablo contigo? Esos son los tipos a los que necesito enganchar.}
{117}{}{Intentaré descubrir todo lo que pueda sobre Adytum. Adiós.}
{118}{}{Bueno ¿qué te trae por este lugar?}
{119}{}{Estoy buscando un Chip de agua. ¿Sabes dónde puedo encontrar uno?}
{120}{}{Estoy recorriendo los yermos.}
{121}{}{Sólo miraba. Adiós.}
{122}{}{Sólo somos gente que intenta sobrevivir. Adytum nos puso en esta situación. Nos utilizan y usan a nuestros amigos y familiares como si fueran animales. Ni siquiera tenemos un modo de defendernos.}
{123}{}{¿Por qué no lucháis contra ellos?}
{124}{}{¿Defenderos de quién?}
{125}{}{Bueno, la gente de Adytum es más fuerte y lista que vosotros, por eso explotan a los débiles.}
{126}{}{Voy a ir a echar un vistazo a ver lo que descubro. Adiós.}
{127}{}{Ojalá fuéramos una banda. Al menos tendríamos armas decentes con las que defendernos.}
{128}{}{¿Defenderos de quién?}
{129}{}{No te estarás riendo de mí... Sois un puñado de degenerados y no creo que acabéis bien.}
{130}{}{Pues a mí me recordáis bastante a una banda.}
{131}{}{No puedo ayudarte con eso.}
{132}{}{¿Cuál es la historia de la zona vallada del sur?}
{133}{}{¿Eres la jefa de esta banda?}
{134}{}{Necesitamos mejores armas. Los Pistoleros, no muy lejos de aquí, tienen, pero no podemos llegar hasta ellos.}
{135}{}{¿Por qué no?}
{136}{}{Voy a ver lo que puedo descubrir de esta situación.}
{137}{}{Los Reguladores. Son los que de verdad dirigen Adytum. No Zimmerman. Vienen aquí y se llevan a nuestra gente a Adytum para usarlos como esclavos. Nos matan cuando intentamos oponernos. A veces vienen y matan a un par de nosotros para llevárselos a Zimmerman, y así pueden decir que intentamos entrar en su ciudad o cualquier otra historia ridícula como esa. ¡Esos malditos incluso mataron al hijo de Zimmerman!}
{138}{}{¿Al hijo de Zimmerman? ¿Y por qué querrían matarlo?}
{139}{}{¿Quieres decir que nunca habéis hecho nada contra Adytum?}
{140}{}{Hay un nido de Garras Mortales entre nosotros y ellos. Ni siquiera hemos hablado nunca con ninguno de ellos. Los Reguladores tienen el poder para acabar con las Garras Mortales pero por algún motivo no lo hacen.}
{141}{}{¿Dónde puedo encontrar a los Pistoleros?}
{142}{}{De acuerdo. Adiós.}
{143}{}{Josh vivía aquí conmigo... mm... yo...nosotros. Él sabía la verdad sobre lo que estaba pasando. Los Reguladores le dijeron que si alguna vez intentaba ponerse en contacto con su padre o volver a Adytum lo matarían.}
{144}{}{¿Que lo matarían? ¿Qué hizo?}
{145}{}{Voy a Adytum a aclarar esto.}
{146}{}{Una noche intentó introducirse en la ciudad para decirle a su padre lo que estaba pasando. Yo dirigía las transmisiones de radio la noche que... ellos... lo... cogieron. [Parece triste y mueve la cabeza lentamente.] Aquí, está todo en los holodiscos.}
{147}{}{¿Por qué no le has dado esto al padre de Josh?}
{148}{}{No es tan fácil que ninguno de nosotros nos acerquemos a Adytum. Caeríamos muertos antes de alcanzar las puertas.}
{149}{}{¿Por qué no le doy el disco?}
{150}{}{¿Por qué no reunes un grupo grande de gente y tomáis Adytum por la fuerza?}
{151}{}{¿Arriesgarías tu vida por ayudarnos?}
{152}{}{Claro. Cualquier cosa por ayudar.}
{153}{}{Podría. Necesito ir a comprobar algunas cosas antes de hacer nada.}
{154}{}{Gracias. Eso sería de gran ayuda. Buena suerte. [Te da el holodisco.]}
{155}{}{Hasta luego.}
{156}{}{Muy bien. Espero que hayas tomado la decisión adecuada.}
{157}{}{Adiós.}
{158}{}{Los Pistoleros están al este y luego al norte de aquí. Pero ten cuidado: A las Garras Mortales hay que tomarlas en serio. He visto cómo una Garra Mortal partía a un hombre en dos de un solo golpe.}
{159}{}{Voy a ir a ver qué descubro.}
{160}{}{Siento que te lo tomes así. Creo que será mejor que te vayas.}
{161}{}{Adiós.}
{162}{}{¿Puedo ayudarte?}
{163}{}{¿Eres la jefa de esta banda?}
{164}{}{No importa.}
{165}{}{¿Un... qué?}
{166}{}{¿Banda? Apenas somos una banda. Pero acuden a mí cuando necesitan a un jefe.}
{167}{}{Zimmerman me envió.}
{168}{}{Bueno, a mí me parecéis una banda.}
{169}{}{Adiós}
{170}{}{[Con aspecto nervioso] ¿Qué? ¿ÉL...?}
{171}{}{Para meterte una bala en la cabeza.}
{172}{}{Por matar a su hijo.}
{173}{}{¡¡¡QUÉ!!! ¡ESOS MALDITOS BASTARDOS DE MIERDA! ¡LOS MATARÉ, LOS ENVIARÉ AL INFIERNO A TODOS!}
{174}{}{No, tú eres quien irá al infierno.}
{175}{}{Eh... ¿a quién vas a mandar al infierno?}
{176}{}{... los Reguladores. ¡Ellos mataron a Josh! Yo nunca habría hecho nada que hiciera daño a Josh. Son los Reguladores los que gobiernan Adytum, no Zimmerman.}
{177}{}{Esto es un intento patético para salirte de esta.}
{178}{}{¿Por qué iban los Reguladores a matar a Zimmerman?}
{179}{}{Josh vivía aquí conmigo... yo... yo...nosotros. Él sabía lo que estaba pasando de verdad. Los Reguladores le dijeron que si alguna vez intentaba ponerse en contacto con su padre o regresaba a Adytum, lo matarían. Se rieron de él... estaban seguros de que no podría llegar hasta su padre...}
{180}{}{¿Que lo matarían? ¿Qué hizo?}
{181}{}{¿Cómo va nuestro plan?}
{182}{}{Todavía intento organizarlo todo.}
{183}{}{¿Un... qué?}
{184}{}{No estoy segura de que funcione sin amenazas. Lo que de verdad necesitamos son armas de los Pistoleros.}
{185}{}{¿Dónde están los Pistoleros? ¿Por qué no obtenéis algunas armas de ellos?}
{186}{}{Oh, bueno, me ofrecí. Adiós.}
{187}{}{Están un poco al este de aquí, pero hay un nido de Garras Mortales entre ellos y nosotros. Ni siquiera hemos hablado con algún Pistolero.}
{188}{}{Vale, dame el holodisco e iré a hablar con los Pistoleros antes de acercarme a Zimmerman.}
{189}{}{Espero que encuentres un modo de ayudarnos. Adiós.}
{190}{}{¿Qué ocurre?}
{191}{}{¡Mataron a Zimmerman!}
{192}{}{¿Eh... qué?}
{193}{}{... Ahora la única opción que nos queda es obtener esas armas de los Pistoleros. ¿Nos ayudarás?}
{194}{}{Sí.}
{195}{}{No.}
{196}{}{Gracias. Que los dioses te acompañen en tu viaje.}
{197}{}{Gracias por tu ayuda. Vamos a invadir Adytum, nos ayudaría alguien como tú de nuestro lado.}
{198}{}{No gracias, ya he visto bastante acción esta semana.}
{199}{}{Claro, me encantaría acabar con los Reguladores.}
{200}{}{Qué... ¿qué?}
{201}{}{Primero me gustaría hablar con Zimmerman.}
{202}{}{Bueno, gracias de nuevo por tu ayuda. Adiós.}
{203}{}{Fantástico. Vamos.}
{204}{}{No creo que sea una buena idea, pero puedes intentarlo si quieres.}
# 205 fixed with patch 1.3 from TeamX. 240 or 241 will be substituted BEFORE this line.
{205}{}{Sin los Pistoleros no tendremos la oportunidad de conseguir armas. Fuera de aquí, no eres bienvenido.}
{206}{}{Lo siento.}
{207}{}{Vete de paseo.}
{208}{}{Voy a hablar con Zimmerman para darle este holodisco y todo irá bien.}
{209}{}{¿Sabes? Te voy a matar.}
{210}{}{¿Un... qué?}
{211}{}{Adelante. Es tu funeral. Sin armas no tenemos nada que nos sirva de apoyo.}
{212}{}{¡Fuera!}
{213}{}{No eres bienvenido aquí.}
{214}{}{Piérdete.}
{215}{}{Gracias.}
{216}{}{Mi gente está libre.}
{217}{}{Hola.}
{218}{}{¿Qué te pasó? ¿Te disparó alguien a la cabeza?}
{219}{}{¿Ehh?}
{220}{}{Ves a Cuchilla, líder de los Navajas.}
{221}{}{Ves a una mujer muy guapa con mirada triste.}
{222}{}{Por favor, vete. Estoy muy ocupada.}
{223}{}{Gracias por ayudarnos con los Reguladores. Por favor, quédate el tiempo que quieras. Puede que quieras hablar con Miles y Herreriano, ellos pueden ayudarte con tus próximos viajes.}
{224}{}{Hola, ¿puedo ayudarte?}
{225}{}{¿Quién eres?}
{226}{}{¡Hootzpah!}
{227}{}{Mi nombre es Cuchilla, soy la jefa de la gente que ves aquí. Vivimos aquí a la disposición de los Reguladores de Adytum.}
{228}{}{¿Reguladores? Me he encargado de todos ellos. ¿Supone algún problema?}
{229}{}{¿Los has matado a todos? No, en absoluto, no es problema. Mi pueblo puede ahora vivir libremente con la gente de Adytum.}
{230}{}{No puedo creerlo. Has podido matarlos a todos. Los Navajas y yo te lo agradecemos.}
{231}{}{He oído que los Reguladores todavía controlan Adytum. ¿No has podido matarlos a todos como esperabas?}
{232}{}{No te preocupes, me ocuparé de ello.}
{233}{}{Creo que no seré capaz de hacerlo.}
{234}{}{Iríamos contigo, pero sin armas, los Reguladores nos matarían a todos. Puede que haya otra posibilidad. [Cuchilla reflexiona un momento]. Si consigues que los Pistoleros nos proporcionen armas, algunos de nosotros irán contigo.}
{235}{}{Me parece bien. Iré a hablar con ellos.}
{236}{}{Intentaré quitar del medio a los Reguladores.}
{237}{}{Hola otra vez. He oído que has estado jugando con los Reguladores. Quería darte las gracias por deshacerte de ellos. Mi pueblo puede ahora vivir en libertad con la gente de Adytum.}
{238}{}{Me ocuparé yo mismo de los Reguladores.}
{239}{}{¿Lo harás? Bien, si necesitas ayuda o los consigues, regresa y dímelo.}

# 240-241 added with patch 1.3 from TeamX.
# TRANSLATION NOTE: Following two lines are gender dependent.
{240}{}{¡Bastardo!}
{241}{}{¡Puta!}