{100}{}{Ves a Jerry, un joven Iniciado.}
{101}{}{Ves a un Iniciado Caballero.}
{102}{}{Ves a un Iniciado Escriba.}
{103}{}{¡Hola! Debes ser el Hermano }
{104}{}{, el nuevo Iniciado del exterior. Me llamo Jerry, soy tu
 nuevo compañero de habitación. ¡Yo también soy un Iniciado! He estudiado mucho. ¿Eres
 un Iniciado Caballero o Escriba?}
{105}{}{Todavía no lo he decidido.}
{106}{}{Caballero.}
{107}{}{Escriba.}
{108}{}{Uk.}
{109}{}{Sí, ser Caballero sería estupendo, ven mucha acción y
 construyen un montón de cosas. Todavía no he tomado mi decisión, pero me inclino
 por lo de Caballero. ¿Te estoy aburriendo? Algunos dicen que hablo mucho
 pero no creo que me entiendan. Lo que pasa es que tengo mucho que decir.}
{110}{}{No, en absoluto.}
{111}{}{Tengo que irme. Encantado de conocerte.}
{112}{}{Sí, los Escribas tienen un papel tan creativo. Sería estupendo
 diseñar nuevas armas, modificar las antiguas y guardar informes con los
 detalles de cada objeto de la Hermandad. ¿Te estoy aburriendo? Algunos dicen
 que hablo mucho, pero creo que no me entienden. Tengo mucho
 que decir.}
{113}{}{Sí, todavía intento tomar una decisión. Es difícil, ya que ambas
 son emocionantes. Por cierto, si quieres la litera de arriba dímelo,
 me da igual.}
{114}{}{Gracias, adiós.}
{115}{}{¿Estás bien? Quizá necesitarías ver al doctor o puede
 que sólo te haga falta dormir. Será mejor que siga estudiando. Adiós.}
{116}{}{Oh, por cierto, me alegro de que seas mi nuevo compañero de habitación. El anterior
 siempre llevaba tapones en los oídos, no sé por qué. De cualquier manera, puedes
 dejar aquí lo que quieras, yo no necesito mucho sitio. ¿Quieres
 la litera de arriba? Me cambiaré si quieres... No roncas, ¿verdad? Oh,
 no importa. Hasta luego.}
{117}{}{Sí, justo lo que pensaba. Bueno, me alegro de que seas mi nuevo
 compañero de habitación. El anterior siempre llevaba tapones en los oídos, no sé por qué. Puedes
 dejar aquí lo que quieras, yo no necesito mucho sitio.
 ¿Quieres la litera de arriba? Me cambiaré si quieres... No roncas,
 ¿verdad? Oh, da igual. Hasta luego.}
{118}{}{Despiértame si ronco.}
{119}{}{Thomas dice que hablo demasiado.}
{120}{}{Talus dice que sería un buen Caballero si no hablara tanto.}
{121}{}{¡Me alegro de verte otra vez, compañero de habitación!}
{122}{}{Anoche no dormí muy bien.}
{123}{}{Hola otra vez.}
{124}{}{Mañana tengo que ir de patrulla.}
{125}{}{Dentro de unos años seré un Iniciado Superior.}
{126}{}{Esta no es tu habitación. Vete por favor.}
{127}{}{Creo que estás en la habitación de Jerry.}
{128}{}{Buena suerte, compartes habitación con Jerry el Bocazas.}
{129}{}{¿Qué haces aquí?}
{130}{}{¿Eres también un Iniciado?}
{131}{}{¿De visita?}
{132}{}{Tu habitación es la primera a mano izquierda según entras.}
