{100}{}{Ves a Kathy, la dueña de esta tienda.}
{101}{}{Lo siento, hoy no tengo mucho tiempo.}
{102}{}{¿Qué buscas hoy?}
{103}{}{¿Sí? ¿Puedo ayudarte?}
{104}{}{Lo siento, todavía no tenemos nuevas existencias.}
{105}{}{¿Vendes armaduras?}
{106}{}{Saludos.}
{107}{}{Que tengas un buen día.}
{108}{}{¿Ves algo que te guste?}
{109}{}{Gracias por pararte aquí.}
{110}{}{Me alegro de conocerte.}
{111}{}{Vuelve por aquí.}
{112}{}{Hasta pronto.}
{113}{}{Adiós.}
{114}{}{Lo siento, intentaré tener pronto nuevos productos.}
{115}{}{Creo que debería diversificarme.}
{116}{}{Gracias.}
{117}{}{Gracias por detenerte aquí.}
{118}{}{Siento no tener lo que buscabas.}
{119}{}{Que pases un buen día.}
