{100}{}{Ves a un borracho.}
{101}{}{Ves a un cliente.}
{102}{}{Ves a una chica muy guapa.}
{103}{}{Ves a un hombre de aspecto extraño.}
{104}{}{Ves a un jugador.}
{105}{}{Ves a una mujer que parece muy ocupada.}
{106}{}{Ves a una mujer.}
{107}{}{Ves a un hombre.}
{108}{}{Ves a un jugador de aspecto triste.}
{109}{}{Ves a un mercenario.}
{110}{}{Déjame con mi dolor.}
{111}{}{Mi mejó amigo.}
{112}{}{¿Po'qué estásh... hip... 'onde eshtoy?}
{113}{}{¿Quién eres?}
{114}{}{¿Te conozco?}
{115}{}{Me shiento un poshquito ma´eado.}
{116}{}{La bebida me pone, digo te pone.}
{117}{}{¿Po´qué hash venido con tu doble?}
{118}{}{¡Señorita, quédese quieta!}
{119}{}{¡Chica, quédate quieta!}
{120}{}{¡A por el caballo!}
{121}{}{Contigo, este sitio pierde categoría.}
{122}{}{¡Fuera, me traes mala suerte!}
{123}{}{No perturbes mi concentración.}
{124}{}{¡Ganaré en este maldito juego!}
{125}{}{¿Se te da bien esto?}
{126}{}{¿Has visto eso? ¡Es imposible!}
{127}{}{Creo que están haciendo trampas.}
{128}{}{Esa es una buena apuesta.}
{129}{}{Es algo seguro.}
{130}{}{¿Qué? ¿Cómo puedo haber perdido?}
{131}{}{¡Esta mesa está gafada!}
{132}{}{Estoy ocupado.}
{133}{}{¿No ves que estoy jugando?}
{134}{}{Apuesta o afuera.}
{135}{}{Déjanos en paz o llamo a los guardias.}
{136}{}{Cuidado, soy amigo íntimo del Suplente Fry.}
{137}{}{¿Te importa?}
{138}{}{¡Nada de espectáculos!}
{139}{}{No hago grupos.}
{140}{}{Estoy demasiado cansado para otra.}
{141}{}{Estás soñando, colega, ¡lárgate!}
{142}{}{¡Fuera de aquí!}
{143}{}{¿Qué diablos crees que estás haciendo?}
{144}{}{¡Cuida tu modales!}
{145}{}{¡Voy a llamar a la poli!}
{146}{}{¡Ni lo pienses!}
{147}{}{¡Lárgate de aquí!}
{148}{}{¡Fuera!}
{149}{}{¿Qué estás mirando?}
{150}{}{¿Te importa?}
{151}{}{¡Lárgate de aquí!}
{152}{}{¡Fuera!}
{153}{}{¿Formas parte de ese grupo?}
{154}{}{¡Fuera de aquí, pervertido!}
{155}{}{¿Qué problema tienes?}
{156}{}{Fuera de aquí antes de que me entre hambre.}
{157}{}{Arréglatelas tú sólo.}
{158}{}{Ella es mía.}
{159}{}{¡Maldita sea!}
{160}{}{¿Estás haciendo trampa?}
{161}{}{Esa tenía que haber sido mía.}
{162}{}{¡Casi!}
{163}{}{¡Qué poco ha faltado!}
{164}{}{¿Puedes repetirme las reglas?}
{165}{}{Solía ser bueno en esto.}
{166}{}{Gracias por nada.}
{167}{}{¡No lo creo!}
{168}{}{Lo he hecho a propósito.}
{169}{}{Hagan sus apuestas.}
{170}{}{Quite sus manos de ahí, señor.}
{171}{}{¡Ganaste!}
{172}{}{Lo siento, amigos, quizá la próxima vez.}
{173}{}{¡Otro ganador!}
{174}{}{¡Esas manos!}
{175}{}{Le toca, señor.}
{176}{}{Lo siento, esa apuesta no es válida.}
{177}{}{Eso es.}
{178}{}{¿Alguien más?}
