{100}{}{Ves a un Regulador, uno de los guardias de Adytum.}
{101}{}{}
{102}{}{Ten tus armas bajo control mientras estés aquí.}
{103}{}{Bienvenido a Adytum, extranjero. Contrólate porque te vigilaremos.}
{104}{}{Me gustaría entrar.}
{105}{}{¿Puedo hacerte algunas preguntas?}
{106}{}{Uhhh...}
{107}{}{Puede que Zimmerman te necesite. Entra, pero
 recuerda, estamos vigilándote.}
{108}{}{¡Bienvenido de nuevo! Eres bienvenido siempre que quieras.}
{109}{}{¿No tienes nada que hacer? Regresa cuando lo hayas
 terminado.}
{110}{}{¡Vete!}
{111}{}{¿Qué quieres ahora?}
{112}{}{Me gustaría entrar.}
{113}{}{}
{114}{}{Nada. No importa.}
{115}{}{}
{116}{}{No.}
{117}{}{¿Qué es lo que quieres saber?}
{118}{}{¿Qué haces aquí?}
{119}{}{¿Puedes hablarme más del Cementerio?}
{120}{}{¿Cómo puedo entrar?}
{121}{}{¿Qué sabes de los Niños de la Catedral
 y de los Seguidores del Apocalipsis?}
{122}{}{Nada, gracias.}
{123}{}{Soy uno de los Reguladores. Nuestra obligación es mantener la paz
 en Adytum, y proteger la ciudad. Nuestro jefe, Caleb,
 podría contarte más.}
{124}{}{Al este de nosotros están los Seguidores. Son un puñado de chiflados que predican por la paz.
 Al norte están los Navajas, un puñado de yonquis, si me permites la expresión. Al sur de aquí está la Catedral,
 donde los Niños tienen su centro religioso.}
{125}{}{Lo siento, pero aquí tenemos que tener cuidado con los extraños. Es
 demasiado peligroso. Quizá puedas hacer algún trabajo para Zimmerman.}
{126}{}{Termina tu trabajo.}
{127}{}{¡Por supuesto, eres bienvenido siempre que quieras!}
{128}{}{Ambos grupos están colgados. Los Seguidores quieren que todos vivamos
 felices y en paz. No se dan cuenta de que el mundo es demasiado
 cruel para eso.}
{129}{}{Los Niños tienen una especie de dios al que adoran
 en su Catedral del sur. Tienen un hospital,
 pero son demasiado raros para ser serios.}
{130}{}{¡Te advertimos que vigilaras tus armas!}
{131}{}{Será mejor que mantengas tus armas apartadas mientras estés aquí.}
{132}{}{Un ladrón, ¿eh? ¡Deja que te enseñe lo que hacemos aquí a los de tu calaña!}
{133}{}{[Hecho]}

{134}{}{Contrólate.}
{135}{}{Te estamos vigilando.}
{136}{}{Mantente a raya.}
{137}{}{¿Qué miras?}
{138}{}{¿Qué quieres?}

{139}{}{Supongo que esto significa que hemos acabado contigo, viejo.}

{1000}{}{Adytum}
{1001}{}{Seguidores}
{1002}{}{Catedral}
{1004}{}{Navajas}
{1005}{}{Pistoleros}
{1006}{}{Eje}
{1007}{}{Ciudad Vertedero}
{1008}{}{Chip}
{1009}{}{Establecimiento}
{1010}{}{Zimmerman}
{1011}{}{Necrópolis}
{1012}{}{El Ardor}
{1013}{}{Reguladores}
{1014}{}{Carroñeros}
{1015}{}{Cementerio}

{1100}{}{Aquí está.}
{1101}{}{Viven al este de aquí.}
{1102}{}{Está al sur de nosotros.}
{1104}{}{Están al norte de aquí.}
{1105}{}{Están al este de los Navajas y al norte de las Garras Mortales.}
{1106}{}{Comerciamos con ellos.}
{1107}{}{¿No se trata de una ciudad que está al norte de aquí?}
{1108}{}{¿Un qué?}
{1109}{}{El establecimiento de Tine está en el subterráneo cerca de la puerta.}
{1110}{}{Es el alcalde.}
{1111}{}{Me han dicho que está hacia el este.}
{1112}{}{Eso es un mito.}
{1113}{}{Protegemos Adytum.}
{1114}{}{Ellos salen al exterior para coger cosas.}
{1115}{}{Este es el Cementerio.}