{100}{}{Los pelillos del cogote se te erizan. Sientes algo que avanza
 por el pasillo. La bilis te llena la boca cuando reconoces la masa de carne
 de partes humanas de la pared. Lo peor de todo es que se mueve y
 te llama.}
{101}{}{Tu nariz empieza a sangrar. Oyes voces en tu cabeza. Te llaman por tu nombre. Por un momento la oscuridad inunda tus ojos, pero
 te recuperas.}
{102}{}{Una voz te llama. Vuelves la cabeza y ves la imagen de una
 amiga olvidada, obviamente muerta. Le salen gusanos por la boca corrompida. Cada vez te duele más la cabeza.}
{103}{}{Te cuesta cada vez más avanzar. Tus pies parecen pegados al
 suelo. Miras hacia abajo y la carne del suelo te sube por la pierna.
 Unos dientes te roen las rodillas. Te quedas de piedra; tu dolor de cabeza empeora.}
{104}{}{¡Algo atrae tu atención, un movimiento rápido en el
 techo, y una astilla de hueso te atraviesa el ojo! Con ella vienen
 pensamientos de muerte y tortura.}
{105}{}{El dolor de cabeza te vuelve loco. Sientes que los pecados de los demás
 riegan tu alma. Y lo que es peor: tus pecados les contestan. Como
 locos luchan contra tu alma y destruyen tu personalidad.}
{106}{}{Tu cabeza vibra con los pensamientos intrusos de los demás. El
 dolor no cesa de aumentar. Y de repente, como si nunca hubiera existido, desaparece.
 Te caes al suelo y lloras. Pero notas que algo va mal.}
{107}{}{Ya no sientes tanto el dolor de cabeza. Los efectos de
 este extraño pasillo ya no se sienten con tanta fuerza.}
