{100}{}{¡Has caído en una emboscada de Supermutantes!}
{101}{}{¡Parece que has caído en plena guerra de bandas!}
{102}{}{¡Un grupo de invasores hostiles se abre paso!}
{103}{}{¡Una miríada de ratas corre por las calles!}
{104}{}{¡Un grupo de bandidos hostiles aparece!}
{105}{}{¡Las ratas te atacan repentinamente!}

