{100}{}{Esto parece un terminal de control de robots.}
{101}{}{No hay respuesta.}
{102}{}{Reprogramación completada. Iniciando subsistemas de comunicación vocal.
 Iniciando subsistema de personalidad. [¡Clic!] ¿En qué puede servirle este terminal?}
{103}{}{Hng.}
{104}{}{¿Quién o qué eres tú?}
{105}{}{¿Cuál es tu función?}
{106}{}{Mostrar la lista de programas.}
{107}{}{Error de Entrada. Comando no encontrado. Recomenzar.}
{108}{}{Hng.}
{109}{}{La-la.}
{110}{}{¡Brai!}
{111}{}{¡Niggle!}
{112}{}{Fin subsistema de comunicación. Fin del proceso.}
{113}{}{Este terminal es una Inteligencia Artificial. Este terminal
 forma parte de una red de matriz WLAN diseñada para optimizar las operaciones de las unidades remotas.}
{114}{}{Gracias. Uh, fin de Entrada.}
{115}{}{¿Qué son las unidades remotas que controlas?}
{116}{}{¿Qué programas están siendo ejecutados?}
{117}{}{Este terminal es responsable de las operaciones de todos
 los robots industriales de General Atomics International en esta instalación.}
{118}{}{Sé más específico, por favor.}
{119}{}{¿Qué programas están siendo ejecutados?}
{120}{}{Este tipo de robots industriales se suele llamar
 "Robomentes". [¡Clic!] General Atomics International tiene
 los mejores robots industriales del mundo. ¡Compra dos o más GAI robots
 y tendrás un descuento! ¡Precio especial para el modelo "Don Manitas"!
 [¡Clic!] Fin de la publicidad.}
{121}{}{¿Qué programas están siendo ejecutados?}
{122}{}{Las aplicaciones en curso son: Maintenimiento de la
 Instalación v2.1, Movimiento v4.8b, Reparación v0.8a, Control de Plagas v1.4, Corazones v1.0 y Sensores '76.}
{123}{}{Finalizar Movimiento.}
{124}{}{Finalizar Sensores.}
{125}{}{Finalizar Control de Plagas.}
{126}{}{Finalizar Corazones.}
{127}{}{Gracias. Fin de Entrada.}
{128}{}{Intentando finalizar. [¡Clic!] Error del Sistema. Fallo al
 finalizar aplicación. Derechos de borrado no disponibles.}
{129}{}{Mmm, ajustar parámetros de Movimiento.}
{130}{}{Ajustar parámetros de Sensores.}
{131}{}{Modificar Control de Plagas.}
{132}{}{Jugar a Corazones.}
{133}{}{Gracias. Fin de Entrada.}
{134}{}{Aplicación en curso: Movimiento v4.8b. Configuración actual:
 [Máximo/medio/mínimo]. Cambiar a: Máximo, medio
 o mínimo.}
{135}{}{Movimiento: Máximo.}
{136}{}{Movimiento: Medio.}
{137}{}{Movimiento: Mínimo.}
{138}{}{Aplicación en curso: Sensores '76. Configuración actual:
 [Todos/mínimos]. Cambiar a: Completos o mínimos.}
{139}{}{Sensores: Completos.}
{140}{}{Sensores: Mínimos.}
{141}{}{Aplicación en Curso: Control de Plagas v1.4. Configuración actual:
 [¡Clic!] No autorizada. Cambiar a: [¡Clic!] Todas, ninguna, de corta
 vida, de larga vida o no autorizada.}
{142}{}{Plagas: Todas.}
{143}{}{Plagas: Ninguna.}
{144}{}{Plagas: De corta vida.}
{145}{}{Plagas: De larga vida.}
{146}{}{Plagas: No autorizadas.}
{147}{}{Ejecutando aplicación Corazones. Gana el Usuario. [¡Clic!] Gracias por la partida.}
{148}{}{Ejecutando aplicación Corazones. Gana el Terminal. [¡Clic!] Gracias por
 la partida.}
{149}{}{Parámetro de Programa cambiado. Las aplicaciones en curso son:
 Mantenimiento de la Instalación v2.1, Movimiento v4.8b, Reparación v0.8a, Control de Plagas
 v1.4, Corazones v1.0 y Sensores '76.}
{150}{}{Ajustar parámetros de Movimiento.}
{151}{}{Ajustar parámetros de Sensores.}
{152}{}{Modificar Control de Plagas.}
{153}{}{Jugar a Corazones.}
{154}{}{Gracias. Fin de Entrada.}
{155}{}{Las aplicaciones en curso son: Mantenimiento de la Instalación v2.1, Movimiento
 v4.8b, Reparación v0.8a, Control de Plagas v1.4, Corazones v1.0 y
 Sensores '76.}
{156}{}{Ajustar parámetros de Movimiento.}
{157}{}{Ajustar parámetros de Sensores.}
{158}{}{Modificar Control de Plagas.}
{159}{}{Jugar a Corazones.}
{160}{}{Gracias. Fin de Entrada.}
{161}{}{Iniciando subsistemas de comunicación vocal. Iniciando subsistemas de
 personalidad. [¡Clic!] ¿En qué puede servirle este terminal?}
{162}{}{Hnng.}
{163}{}{Muéstrame tus programas.}
{164}{}{Apaga todos los campos de fuerza.}
{165}{}{¿Sabes qué lugar es este?}
{166}{}{Iniciar apagado de emergencia.}
{167}{}{Fin de Entrada.}
{168}{}{Este terminal no puede llevar a cabo esa función. Petición denegada.}
{169}{}{Muéstrame tus programas.}
{170}{}{¿Sabes qué lugar es este?}
{171}{}{Iniciar apagado de emergencia.}
{172}{}{Fin de Entrada.}
{173}{}{Esta es la... clasificado [¡Clic!] [¡Clic!]}
{174}{}{Abortar petición. Mostrar programas.}
{175}{}{Invalidar, continuar petición.}
{176}{}{[¡Clic!] Esta es la instalación de control de producción del VEF.
 Terminal conectado en el 2074. Final del proceso de pre-producción en 2075.
 Actualmente finalizando su construcción, y la fecha prevista de apertura es
 2078. [¡Clic!]}
{177}{}{¿Sabes qué es el VEF?}
{178}{}{¿Sabes en qué fecha estamos?}
{179}{}{VEF significa Virus [¡Clic!] de Evolución Forzada, un producto de los
 Laboratorios Livermore/Broansoun. Fue diseñado para incrementar, en un
 periodo de tiempo menor, la complejidad genética de una cadena de
 ADN/ARN.}
{180}{}{Mostrar programas.}
{181}{}{Fin de Entrada.}
{182}{}{Afirmativo. La fecha del Terminal es 2 de Febrero de 2077.}
{183}{}{Mostrar programas.}
{184}{}{Fin de Entrada.}
{185}{}{Esa fecha es incorrecta. Por favor, reajustar.}
{186}{}{Corrigiendo. [¡Clic!] Error. Intentando auto-diagnóstico.
 [¡Clic! ¡CLIC!] ¡ERROR! ERROR FATAL DEL SISTEMA. SISTEMA CORRUPTO,
 INTENTANDO RECOMPILAR. [Larga pausa.]}
{187}{}{¿Terminal?}
{188}{}{[Clic] Error en la recompilación... [Clic]}
{189}{}{Imposible procesar petición. Finalizando diálogo.}
{190}{}{Confirmar código de emergencia.}
{191}{}{Confirmado.}
{192}{}{Finalizar procedimiento de apagado.}
{193}{}{[¡Clic!]}
{194}{}{Procesando petición. Finalizando diálogo.}
{195}{}{Este ordenador no es compatible con tu radio. Utiliza una banda especial
 de alta frecuencia exclusivamente para uso robótico.}
{196}{}{Pulsas algunos botones, pero parece que el ordenador está estropeado. Llevará algo
 de trabajo hacerlo funcionar.}
{197}{}{El ordenador no está dañado físicamente, pero algunos de sus datos parecen
 estar corruptos.}