{100}{}{Estás viendo a Romero.}
{103}{}{Estás viendo a un miembro de los Navajas.}
{104}{}{Estás viendo a un miembro de los Navajas.}
{105}{}{Piensas que puede ser Libros.}
{106}{}{Piensas que puede ser Cicatrices.}
{107}{}{Piensas que puede ser Pistolón.}
{108}{}{Piensas que puede ser Tembleque.}
{109}{}{Piensas que puede ser Martillo.}
{110}{}{Piensas que puede ser Cuchilla.}
{111}{}{¡Quédate quieto!}
{112}{}{¿Qué? ¿Qué quieres decir?}
{113}{}{¡Nunca!}
{114}{}{Estoy aquí para hablar de paz.}
{115}{}{Vale.}
{116}{}{Yo soy quien hace aquí las preguntas. ¿Qué estás haciendo aquí?}
{117}{}{Estoy aquí buscando a un amigo.}
{118}{}{Estoy aquí para hablar sobre la paz.}
{119}{}{¡Quiero poner fin a la guerra de bandas!}
{120}{}{¡Quiero beberme la sangre de los Navajas!}
{121}{}{Entonces buscas en el lugar equivocado. Piérdete.}
{122}{}{Tu debes ser uno de esos cobardicas con túnicas púrpura. Largo
 de aquí antes de que te machaque.}
{123}{}{¡Espera! No sé de que estás hablando. Estoy aquí de parte de
 Adytum. Quieren que consiga que todos los dejen en paz.}
{124}{}{¡Pacifica ESTO!}
{125}{}{Lo siento. Ahora me marcho.}
{126}{}{Mmm. Si realmente eres de Adytum, entonces sigues siendo un perdedor.
 Allí nunca podrá haber paz mientras esos Destripadores estén por los alrededores.}
{127}{}{¿Qué quieres decir?}
{128}{}{Uh, claro.}
{129}{}{Habla con Cuchilla. Te explicará cosas de esos endogámicos sedientos de sangre.}
{130}{}{¡Piérdete!}
{131}{}{Ey, ahora que eres un Navaja, necesito pedirte un favor.}
{132}{}{Claro.}
{133}{}{¿Cuál es?}
{134}{}{No me interesa.}
{135}{}{Genial. Lleva este relicario a Julianna. Dile que espero
 verla pronto.}
{136}{}{Resulta que me he enamorado de una chica de Adytum. A causa de
 los Reguladores y que nos disparan nada más vernos, no puedo acercarme a ella.}
{137}{}{¿Cómo puedo ayudarte?}
{138}{}{Continúa.}
{139}{}{Lo siento por ti.}
{140}{}{Si llevas este relicario a Julianna, estaría en deuda contigo.}
{141}{}{Tenlo por seguro.}
{142}{}{Búscate a otro.}
{143}{}{Con aliados como tú, ¿quién necesita enemigos? ¡Adiós!}
{144}{}{Creo que ella también me quiere, pero no lo sé. Los Navajas no se
 arriesgarán a dejarme entrar en Adytum.}
{145}{}{Lo siento por ti.}
{146}{}{Vale, te ayudaré.}
{147}{}{¡Gracias! Ella me envió una nota. Nos vamos a encontrar en el lugar de
 los Seguidores y nos casaremos.}
{148}{}{Bienvenido de nuevo.}
{149}{}{Muchas gracias. Ahora nos quedaremos aquí con los Seguidores,
 donde nos podremos casar felizmente.}
