{100}{}{Estás viendo a Sally.}
{101}{}{¿¿Por qué todo el mundo me habla de forma rara??}
{102}{}{El mutante te ignora.}

{1000}{}{Chip}
{1001}{}{Necrópolis}
{1002}{}{Set}
{1003}{}{Almacén de Agua}
{1004}{}{Sala}
{1005}{}{Teni}
{1006}{}{Necrófagos}
{1007}{}{Normales}

{1100}{}{No sé.}
{1101}{}{T´a pisándola.}
{1102}{}{Es un pesao. Deberíamos acabar con él y sus necrófagos.}
{1103}{}{Eso es aquí.}
{1104}{}{No sé.}
{1105}{}{Él, jefe de Harry.}
{1106}{}{Debiluchos.}
{1107}{}{Más débiles que los necrófagos.}
