{100}{}{Estás viendo a Sammael, uno de los Carroñeros de Adytum.}
{101}{}{Estás viendo a un hombre desaliñado vestido de azul oscuro.}
{102}{}{Oye, no puedo creer que nos hayamos encontrado. ¿Y tú eres?}
{103}{}{Soy }
{104}{}{.}
{105}{}{¿Quién lo pregunta?}
{106}{}{¿Eruh?}
{107}{}{El placer es mío. Me llamo Sammael.}
{108}{}{¿Qué haces aquí?}
{109}{}{Me ha gustado hablar contigo.}
{110}{}{Nadie especial. No te preocupes.}
{111}{}{Soy un Carroña... un carroñero. Mi trabajo es rebuscar por todo
 el Cementerio artículos útiles e información. Un trabajo peligroso.}
{112}{}{¿Por qué es peligroso?}
{113}{}{¿Cómo evitas a las Garras Mortales?}
{114}{}{¿Has explorado otras áreas?}
{115}{}{Gracias, adiós.}
{116}{}{Ya nos veremos. Si es que me ves. Ja.}
{117}{}{Bueno, ahí fuera están las Garras Mortales, y luego de vuelta en
 Adytum están los Reguladores. Ni las unas, ni los otros, son angelitos.}
{118}{}{¿Cómo evitas a las Garras Mortales?}
{119}{}{¿Has explorado otras áreas?}
{120}{}{Gracias, adiós.}
{121}{}{Sólo trabajamos de noche, y somos buenos en lo nuestro.
 Pero reconozco que no volvemos todos. La semana pasada mandé
 a un tipo a buscar unas piezas para Miles, y todavía no hemos tenido noticias suyas.
 En la última transmisión me decía que había encontrado las piezas,
 y que regresaba.}
{122}{}{Yo he explorado un poco. ¿De quién quieres saber cosas?}
{123}{}{Los Navajas.}
{124}{}{Las Garras Mortales.}
{125}{}{Los Pistoleros.}
{126}{}{Los Seguidores del Apocalipsis.}
{127}{}{Los Niños de la Catedral.}
{128}{}{De nadie, gracias.}
{129}{}{Los Navajas son un grupo patético.
 Pero salen adelante, y algunos terminan aquí, en Adytum, si aceptan lo que
 los Reguladores les ofrecen.}
{130}{}{Mejor si no las has visto nunca. Son más malas que el demonio,
 y nada les gusta más que arrancarle el corazón a un pobre Carroña.}
{131}{}{He oído que tienen un nido al este de los Navajas,
 pero yo no lo he visto.}
{132}{}{Los Pistoleros se instalaron hace poco en una fábrica del noreste. No te puedo decir más porque tienen un foso
 lleno de residuos radiactivos, y hay que pasar por la zona de las Garras
 Mortales para entrar allí.}
{133}{}{Los Seguidores predican la paz y la tolerancia. Bonita idea, pero
 poco práctica. Viven en una gran biblioteca al noroeste de nosotros.}
{134}{}{Los Niños de la Catedral tienen su base en una gran iglesia
 muy al sur de aquí. Allí están pasando cosas muy
 raras. He visto criaturas que no pueden ser humanas
 entrando y saliendo de allí.}
{135}{}{Si las historias son ciertas, la iglesia está construida sobre
 un viejo Refugio, en el que vivían los predecesores de Adytum.}
{136}{}{Yuju. Nos encontramos una vez más. ¿Qué pasa?}
{137}{}{¿En qué me dijiste que consistía tu trabajo?}
{138}{}{Nada, gracias.}
{139}{}{Oh, ya veo. Bien. ¡Adiós!}
