{100}{}{La puerta de seguridad está cerrada.}
{101}{}{La puerta de seguridad no está cerrada.}
{102}{}{Consigues abrir la puerta de seguridad.}
{103}{}{No consigues abrir la puerta de seguridad.}
{104}{}{Consigues accionar la alerta pasiva en la puerta, al intentar desactivar el
 cerrojo electrónico. Buen trabajo.}
{105}{}{Ganas 25 puntos de experiencia por forzar el cerrojo.}
