{100}{}{Estás viendo a Set, el Líder de Necrópolis.}
{101}{Set00}{Más vale que tengas una razón de peso para pisar mi
 sombra. Supongo que te suena lo de "vas a ser mi postre..."
 normalucho.}
{102}{}{Oh, sin duda pesa. Es evidente que he encontrado
 la cabeza, eh, tío.}
{103}{}{Caray, ¿qué le ha pasado a tu cara?}
{104}{}{Vaya, eres muy listo por ser un Necrófago.}
{105}{}{¿Nah-ah?}
{106}{Set01}{Ahorra saliva. Soy Set. Estoy al mando. ¿Lo pillas?}
{107}{}{Según mi información no eres más que un segundón.}
{108}{}{Lo pillo. }
{109}{}{¿Hay algo más que deba saber?}
{110}{Set01a}{Bien.}
{111}{}{¿Qué puedo hacer por ti?}
{112}{Set02}{¿Qué dices? ¿Fastidiando? Mira, caminante, no
 hago tratos con normales, así es que hacerme la pelota
 no te va a servir de nada.}
{113}{}{El humo te saldrá por todos tus agujeros cuando acabe
 contigo.}
{114}{}{Oh, discúlpame. Sólo quería dar una buena impresión.}
{115}{}{No he querido decir nada.}
{116}{Set03}{[Gruñe] Te voy a comer y cantaré esa canción de la "Tripita Contenta".
 Tengo mi tripita contenta...}
{117}{Set04}{¿La hora de la verdad, puta? Voy a disfrutar estrujándote.}
{118}{}{Más te vale que lo que llevas en el cinto sea más grande que
 tu boca... Aunque parezca improbable.}
{119}{}{Estruja esto...}
{120}{}{¿Nah-ah?}
{121}{Set05}{Bueno. Parece que tenemos un diamante en bruto... je... tengo unos amiguitos
 para ti, mi deslumbrante normalucho. Castiga a los mutantes que están en el
 Almacén de Agua por mí. Claro, si, puedes... ¿si?}
{122}{}{Eh, vale.}
{123}{}{Nah-ah.}
{124}{Set06}{Excelente. Dales una última lección a esos mutantes, luego
 vuelve aquí... Mmm. Si les digo a mis necrófagos que te dejen en paz,
 los mutantes podrían oírlo y sospechar. Así que, es hora de
 que me eches una mano. Yo me callo. ¿Lo pillas?}
{125}{}{Lo pillo.}
{126}{}{¿Qué pasa con los necrófagos?}
{127}{}{¡Ehn, vale!}
{128}{}{¿Eh?}
{129}{Set07}{Evita a mis necrófagos, si quieres salvar tu pellejo. Cualquiera de los míos que no pueda
 con un normalucho, merece la muerte. Arréglatelas como puedas.}
{130}{Set08}{¡Me haces perder mi tiempo! ¡Vas a dejar de existir, de una u otra forma!}
{131}{Set09}{No tienes ni idea de quién es la sombra que pisas.}
{132}{}{Un segundón. Conozco a tu jefe. No feliz.}
{133}{}{Y tú tampoco.}
{134}{}{Perdona, tengo un peculiar sentido del humor.}
{135}{Set10}{¿Trabajas para él? Eres su chivato, ¿verdad? Estás aquí para fastidiarme, ¿no?
 Oh, te juro que tú también morirás.}
{136}{}{Guau, no me malinterpretes. No le pertenezco. Sólo estoy aquí para ayudar.}
{137}{}{Inténtalo, cara de morcilla.}
{138}{Set10a}{No lo parecía.}
{139}{}{Lo entiendo. Él también es mi problema. Habla conmigo.}
{140}{Set11}{Necrópolis era mía. No era la leche,
 pero estaba bien para alguien como yo. Entonces apareció
 el Maestro. Me podría haber dado una buena paliza, pero era más
 fácil para él coger a unos pocos mutantes y quedarse al acecho.}
{141}{}{¿Qué puedo hacer y qué harás tú por mí?}
{142}{}{Se sale un poco de mi rollo. Paso de esto.}
{143}{Set12}{Los Mutantes que están en el Almacén de Agua necesitan una siesta. Hace que
 mi sombra crezca. Los troceas y tendrás tu recompensa.
 Información incluida.}
{144}{}{Hecho.}
{145}{}{Demasiados problemas. Ya nos veremos por ahí.}
{146}{Set13}{¿Buscas trabajo, caminante? Demuestra que sabes pelear.
 Acaba con los mutantes que hay en el Almacén de Agua. Hazles pasar
 un mal rato, si eres bueno.}
{147}{}{Estoy en ello.}
{148}{}{Ni de coña, cara de morcilla.}
{149}{Set14}{No. ¿Más preguntas? }
{150}{}{Ahhh, supongo que no. ¿Qué puedo hacer por ti?}
{151}{}{Sí. ¿Te cuesta limpiarte los dientes?}
{152}{Set15}{Tienes tanta gracia, que me duele la mandíbula. Inténtalo otra vez y mis Élites te
 exprimirán. ¿Lo pillas?}
{153}{}{Lo pillo.}
{154}{}{Pues aún no lo tengo muy claro...}
{155}{}{Está claro que tu cara te debe doler.}
{156}{Set16}{Mi nombre es Set. El tuyo es Todo-me-duele. Hagamos un
 trato, yo te cambio el mote. ¿Me estás escuchando?}
{157}{}{Claro. Es mejor que desangrarse en el suelo.}
{158}{}{Naaa. Trae a tus fantasmones.}
{159}{}{Ajá.}
{160}{}{¡Nah-ah!}
{161}{Set17}{Date un rulo por el Almacén de Agua, haz que los mutantes duerman la siesta.
 Hazlo, sigues siendo un caminante. No lo haces, te irás a descansar.}
{162}{}{Parece que estos tíos te asustan un poco,
 ¿quieres que hablemos de ello?}
{163}{}{Soy un enrollado. Trato hecho.}
{164}{}{Eres raro y hablas raro.}
{165}{Set18}{Bien hecho. Mereces verme, caminante. Sigue
 a Garret para tu recompensa. Ahora. Estoy ocupado.}
{166}{}{Vale, gracias.}
{167}{}{¡Eso es todo! Gracias, y ahora, ¿te largas?}
{168}{}{¿Mamá?}
{169}{Set19}{Ojo antes de chillar. Lo preferirás. Sería una pena
 cabrearme ahora... que estoy tan contento.}
{170}{}{Discúlpa mi exceso de cólera pero estoy un poco
 preocupado.}
{171}{}{Perdona, no pasa nada.}
{172}{}{Oye, no me conformo con las sobras.}
{173}{Set20}{[Gruñe] Si, si. Sigue a Garret y continúa mostrando tus perlitas blancas.
 Y no temas, mantengo la palabra. El Maestro es el retorcido.}
{174}{}{¿El Maestro?}
{175}{}{Vale, gracias.}
{176}{Set21}{Si no vigilas tus espaldas lucirás su cuchillo y él lucirá tu piel.
 Sus mutantes ensombrecen los yermos, sobre todo al sur.}
{177}{}{Si el Maestro es tan fuerte, ¿quién puede desafiarlo?}
{178}{}{A mí no me asusta.}
{179}{Set21a}{Debería.}
{180}{Set22}{Los Niños de la Catedral, los del Eje, incluso nosotros,
 los Necrófagos. Nadie puede empujar su sombra ahora. Pero
 nuestra luz brillará más la próxima vez. Oh, sí.}
{181}{}{Buena suerte.}
{182}{Set23}{Sigue a Garret y lárgate.}
{183}{}{Correcto.}
{184}{}{Que te den.}
{185}{Set24}{Podrías dejar las sobras. Ahora largo, sin tu recompensa,
 o estarás sobre mi mesa esta noche.}
{186}{}{Si así lo quieres.}
{187}{}{Que te den.}
{188}{Set25}{No he tenido noticia de que los mutantes del
 Almacén de Agua hayan dejado de respirar. Fundamental
 para mis planes. Dime que es un problema enterrado.}
{189}{}{Oh, sí. No te preocupes, me estoy ocupando de todo.
 Confía en mí.}
{190}{}{No, todavía estoy en ello.}
{191}{}{Nah-ah.}
{192}{Set26}{Ahhh, reconforta. Sigue a Garret para tu recompensa. }
{193}{Set27}{Me haces perder el tiempo con tus mentiras. Deja mi
 sombra antes de... morir. ¡Muere! ¡Sólo muere! }
{194}{Set28}{Ahora anda. Ocúpate de lo mutantes y luego
 vuelve. No antes.}
{195}{Set29}{Te han cogido los míos, ¿eh? Ya te advertí
 sobre ellos. Ahora pagas. Sin crédito.}
{196}{Set30}{Soy Set. ¿Por qué vas tras mi sombra?}
{197}{}{Soy el portador de la muerte. Arrodíllate y suplica
 misericordia.}
{198}{}{Soy el portador de la muerte. Arrodíllate y suplica
 misericordia... o dame un bocata, me muero de hambre.}
{199}{}{Estoy aquí para ver al jefe. ¿Eres tú?}
{200}{}{¡Guau, un caso de acné gravísimo!}
{201}{}{Ah, nonsé.}
{202}{Set31}{Normaluchos. Si me hicierais temblar,
 ¿estarían mis puertas abiertas así?}
{203}{}{He matado necrófagos. He matado mutantes. He matado
 cosas que jamás podrías imaginar. Nadie se interpone en
 mi camino.}
{204}{}{¿Qué tal un lifting...? Quedaría bien en mi pared.}
{205}{Set32}{Has acabado con los del Almacén. Lo encuentro reconfortante.
 Por ello te elogiaré. Después, separaremos nuestros
 caminos.}
{206}{}{¿Por qué no "separamos nuestros caminos" ahora?}
{207}{}{Por mí vale.}
{208}{Set33}{Una advertencia. El Sur hace que un perro de presa esconda el rabo entre las
 patas. Si tienes ideas en el cráneo, yo puedo hacer
 que los perros de presa se hagan los muertos. Por otra parte,
 limpiaste el Almacén. Garret te llevará a la gratitud.}
{209}{Set34}{La risa se me hace difícil. ¿Has limpiado el
 Almacén?}
{210}{}{Ese es el hecho.}
{211}{}{Oh, no. No fui yo.}
{212}{Set35}{Mi error, tu pérdida. Aumenta el trabajo, deberías caminar
 ahora.}
{213}{Set36}{Ah, sí. Sin huellas en la arena. Bien. Reconforta. Camina
 con Garret a la gratitud.}
{214}{Set38}{Yo proyecto la sombra. Si eso es todo, quítate tú. }
{215}{}{Estoy aquí para recoger la prima por unos mutantes.}
{216}{}{Gracias, creo que me marcharé.}
{217}{}{Sería más rápido quitarte a ti de en medio.}
{218}{Set39}{Factible. Sigue a Garret a la gratitud, luego vete
 por otro camino.}
{219}{Set40}{¿Motivos para las agresiones? Camina y los míos se estarán quietos.
 Habla y los míos se moverán.}
{220}{}{Lo siento, un mal intento de humor.}
{221}{}{Ya era hora. Me estaba aburriendo de ver que tu cara no mejora.}
{222}{Set41}{Ah, el normalucho-pensante. Has matado a los del
 Almacén, ¿no? ¿Vienes por la recompensa?}
{223}{}{A-já.}
{224}{}{Nah-ah, venir a patear tu culo.}
{225}{Set42a}{Ahora es malo. Camina. }
{226}{}{Merezco alguna información.}
{227}{}{¿Qué tal si te piso la cara?}
{228}{}{Lo pillo.}
{229}{}{¿Nah-ah?}
{230}{Set43}{Vale. Rápido. ¿Qué?}
{231}{}{Tú no harías lo de los mutantes por ti mismo. Y yo me
 pregunto, ¿por qué? La respuesta, alguien te tiene asustado. ¿Por qué?}
{232}{}{¿Por qué me necesitabas a mí para matar a los mutantes? ¿Por qué
 no usar a tus necrófagos?}
{233}{}{¿Como diablos osas llamar recompensa a esta porquería?}
{234}{Set44}{No tiemblo. Uso los instrumentos del tiempo. Tú eres
 usado, tu eres recompensado, tu caminas.}
{235}{}{Te estás tirando un farol.}
{236}{}{Si tu lo dices.}
{237}{}{¡Creo que eso es una amenaza!}
{238}{Set45}{Ni siquiera lees las líneas. A no ser que Necrópolis
 vaya a ser tu hogar permanente, camina. No tengo tiempo para un
 tonto saco de carne.}
{239}{}{¿Qué tal tu propio cadáver en un saco?}
{240}{}{Lo pillo.}
{241}{}{Muérdeme.}
{242}{Set45a}{Con mucho gusto...}
{243}{Set46}{Sin farol, sin truco. El Maestro no me hace temblar.
 Camina. Tu bienvenida aquí ya lo ha hecho.}
{244}{}{Gracias por tu tiempo.}
{245}{}{¿Crees que humillarte te devolverá la bienvenida?
 Funciona conmigo.}
{246}{Set47}{¿Por qué enviar a un necrófago para un trabajo de niños?
 Déjame.}
{247}{Set48}{Estoy cansado. Tú te vas.}
{248}{Set49}{¡Siembra y llora! ¡Te quiero muerto! ¡Muerto!}
{249}{Set50}{He descubierto tu truco y nos hace daño a uno de nosotros.
 Elección corta: Elimina a los mutantes o muere.}
{250}{}{Ahora mismo lo hago.}
{251}{}{La lista es más larga. El nº 3 es: ¿y si por el
 contrario giro tu cabeza?}
{252}{Set51}{¿Todavía tras mi sombra? ¿Por qué se menearán las lenguas
 de los normaluchos y se mueve según sus huesos? Hora de irse, ahora camina.}
{253}{Set52}{¿Tu presencia significa?}
{254}{}{No mucho, sólo difundo la noticia de que el
 Maestro ha muerto.}
{255}{}{Se me han acabado los culos que patear y he pensado en tu cara.}
{256}{}{Eh. Maestro hacer ¡pum!}
{257}{Set52a}{¿Quieres decir muerto?}
{258}{}{A-já.}
{259}{Set53}{Gustito. Reconforta. Tus necesidades son mis deseos.
 Nómbralas.}
{260}{}{Necesito información acerca de los Tanques.}
{261}{}{Podría necesitar más armas y equipo.}
{262}{}{No. Gracias.}
{263}{}{Necesito algunas cosas.}
{264}{}{Nouu.}
{265}{Set54}{Algunos de los míos escaparon del cautiverio. Funcionó
 esa tarea mutante.}
{266}{}{¿Qué dijeron?}
{267}{}{Mutantes, ¿eh? Probablemente necesitaré más pistolas.}
{268}{Set55}{Gran noroeste, lejos de la vida. Lleno de guardias
 y difícil llegar. Si ese es tu camino, te doy el pésame.}
{269}{Set56}{Garret te pasará lo que esté disponible.}
{270}{Set57}{Tú. Esfumaste nuestro chip procesador de agua. Cámbialo...
 ¡por tu vida!}
{271}{}{Ambos necesitamos chips operantes. Aparentemente sólo hay
 uno. ¿Hay otro método en el que no hemos pensado?}
{272}{}{Necesitaba el chip para salvar mi propio refugio. Lo siento.}
{273}{}{¿Bastará con un... lo siento?}
{274}{}{¿Lo quieres de vuelta?}
{275}{}{¿Eh?}
{276}{Set58}{Un camino, quizás. Existe una bomba alternativa, pero no
 acciona. Ninguno de los míos puede traerla a la vida.}
{277}{}{Quizás podría echar una ojeada a esa bomba.}
{278}{}{Qué pena. Supongo que estaréis sedientos.}
{279}{Set59}{Garret caminará contigo. Reavivas la bomba, te quedas
 el chip.}
{280}{}{Gracias.}
{281}{Set60}{Beberé de ti caliente, luego te quitaré el frío.}
{282}{}{No lo llevo encima.}
{283}{}{Qué tal si en vez de eso comes polvo.}
{284}{Set61}{¡Entonces muere antes que los míos!}
{285}{Set62}{No te volverán a preocupar las ideas.}
{286}{}{¿Lo tomo como un "no"?}
{287}{Set63}{El precio es pertenecer a Necrópolis para siempre.}
{288}{}{Un poco caro. ¿Qué tal si en vez de eso te retiro del
 cargo?}
{289}{}{¡Nah-ah!}
{290}{Set64}{A cambio del chip, podrás caminar.}
{291}{}{¡Te engañé! ¡Ya no lo tengo!}
{292}{}{Vale, aquí está.}
{293}{}{Prefiero verte muerto.}
{294}{Set65}{[Set le pasa el Chip del agua a un necrófago que
 escapa con él.] Si tu sombra toca Necrópolis de nuevo, desaparecerá
 para siempre.}
{295}{Set200}{Como dije...}
{296}{Set201}{Antes he declarado...}
{297}{Set202}{No hago tratos con normaluchos.}
{298}{Set203}{Parlotea con Garret. Mi tiempo vuela.}
{299}{Set204}{¿Está hueca tu cabeza?}
{300}{Set205}{Tuyo es el único beneficio. Este intercambio está falto.}
{301}{Set206}{Pensamientos que no poseo.}
{302}{Set207}{No es el momento. La tarde es más apropiada para tu sombra.}
{303}{Set208}{¡Guardias! ¡Capturad al normal!}
{304}{Set209}{Guardias, ¡acabad con esta molestia!}
{305}{Set300}{Su significado no tiene lugar aquí. Ninguno.}
{306}{Set301}{El futuro. Supervivencia en cualquier sitio. Superamos a los normaluchos.}
{307}{Set302}{Un error del mundo. Un borrón en mi vista. Odio cada careto.}
{308}{Set303}{Donde yace tu sombra. Mi hogar. Mi reino. Un lugar donde la fuerza
 aumenta.}
{309}{Set304}{El principio. El mundo en cenizas, las cenizas se expanden. Nuestra vida.}
{310}{Set305}{Ideales malogrados. Nada que me importe, nada en absoluto.}
{311}{Set306}{Muchos de los tuyos. Algunos útiles, pero demasiados chiflados.}
{312}{Set307}{Reliquias. Nosotros superamos, ellos no lo saben. Su visión es estrecha, sólo en
 lo que creen.}
{313}{Set308}{Centro del suministro de agua de Necrópolis. Envenenado con la presencia de
 mutantes. Pensar en ello me pone malo.}
{314}{Set309}{Proporciona lo que se necesita.}
{315}{Set310}{Por debajo de mis pensamientos.}
{316}{Set311}{No en mis pensamientos.}



#
# Set Tell-Me-Abouts
#
{970}{Set01}{Ahorra saliva. Soy Set. Estoy al mando. ¿Lo pillas?}

{980}{Set206}{Pensamientos que no poseo.}
{981}{Set310}{Por debajo de mis pensamientos.}
{982}{Set311}{No en mis pensamientos.}

{1000}{}{Maestro}
{1001}{}{Necrófagos}
{1002}{}{Mutantes}
{1003}{}{Necrópolis}
{1004}{}{Guerra}
{1005}{}{Unidad}
{1006}{}{Eje}
{1007}{}{Hermandad}
{1008}{}{Almacén}
{1009}{}{Catedral}
{1010}{}{Chip}
{1011}{}{Sala}
{1012}{}{Niños}
{1013}{}{Garret}
{1014}{}{Set}
{1015}{}{Mutantes}
{1016}{}{Hermandad del Acero}
{1017}{}{Almacén de Agua}
{1018}{}{Niños de la Catedral}
{1019}{}{Niños}
{1020}{}{Almacén de Agua}
{1021}{}{Agua}

{1100}{Set300}{Su significado no tiene lugar aquí. Ninguno.}
{1101}{Set301}{El futuro. Supervivencia en cualquier sitio. Superamos a los normaluchos.}
{1102}{Set302}{Un error del mundo. Un borrón en mi vista. Odio cada careto.}
{1103}{Set303}{Donde descansa tu sombra. Mi hogar. Mi reino. Un lugar donde la fuerza aumenta.}
{1104}{Set304}{El principio. El mundo en cenizas, las cenizas se expanden. Nuestra vida.}
{1105}{Set305}{Ideales malogrados. Nada que me importe, nada en absoluto.}
{1106}{Set306}{Muchos de los tuyos. Algunos útiles, pero demasiados chiflados.}
{1107}{Set307}{Reliquias. Nosotros superamos, ellos no lo saben. Su visión es estrecha, sólo en lo que
 creen.}
{1108}{Set309}{Proporciona lo que se necesita.}
{1109}{Set310}{Por debajo de mis pensamientos.}
{1110}{Set311}{No en mis pensamientos.}
{1111}{Set204}{¿Tienes la cabeza hueca?}
{1112}{Set310}{Por debajo de mis pensamientos.}
{1113}{Set204}{¿Tienes la cabeza hueca?}
{1114}{Set01}{Ahorra saliva. Soy Set. Estoy al mando. ¿Lo pillas?}
{1115}{Set302}{Un error del mundo. Un borrón en mi vista. Odio cada careto.}
{1116}{Set307}{Reliquias. Nosotros superamos, ellos no lo saben. Su visión es estrecha, sólo en
 lo que creen.}
{1117}{Set309}{Proporciona lo que se necesita.}
{1118}{Set310}{Por debajo de mis pensamientos.}
{1119}{Set310}{Por debajo de mis pensamientos.}
{1120}{Set309}{Proporciona lo que se necesita.}
{1121}{Set309}{Proporciona lo que se necesita.}
