{100}{}{Tu destreza no sirve de nada aquí.}
{101}{}{Encuentras un tosco dispositivo explosivo conectado a la taquilla.}
{102}{}{¡Activas una trampa explosiva!}
{103}{}{Desactivas la trampa.}
{104}{}{No desactivaste la trampa.}
{105}{}{¡Activaste accidentalmente el explosivo!}
{106}{}{Activaste accidentalmente el explosivo porque fuiste lo bastante inteligente
 como para encontrarlo, pero no lo suficiente como para no tocarlo.}
{107}{}{¡Uf!}
{108}{}{¡Aaagh!}
{109}{}{Estás viendo la taquilla de Set.}
