{100}{}{Encuentras un tosco dispositivo explosivo en el marco de la puerta.}
{101}{}{¡Activas una trampa explosiva!}
{102}{}{Desactivas la trampa.}
{103}{}{No desactivaste la trampa.}
{104}{}{¡Activas accidentalmente el explosivo!}
{105}{}{Activas accidentalmente el explosivo, fuiste lo bastante inteligente
 como para encontrarlo, pero no lo suficiente como para dejarlo en paz.}
{106}{}{¡Uf!}
{107}{}{¡Aagh!}
{200}{}{Ganas }
{201}{}{ puntos de experiencia por encontrar la puerta secreta.}
