{100}{}{Ganas 400 puntos de experiencia por traer a Tandi.}
{101}{}{Al sur ves una pared de adobe alrededor de una aldea de aspecto
 pacífico.}
{102}{}{Todo lo que queda en esta zona es una pequeña choza. Afortunadamente,
 tus notas indican que hay una entrada secundaria del Refugio 15 aquí.}
{103}{}{Estás viendo una pequeña construcción situada al lado de una serie de tiendas. Los habitantes parecen sucios y hostiles.}
{104}{}{Atraviesas un pueblo de tamaño mediano. Un muro de coches de
 desguace bloquea la entrada. Una neblina de humo yace sobre el pueblo.}
{105}{}{Ves una ciudad grande al sur. En las afueras unas granjas rodean la ciudad.
 Hay mucha vida en este oasis del desierto.}
{106}{}{Te acercas a una ciudad oscura destruida. No hay mucha vida. Un halo de
 muerte rodea el área.}
{107}{}{Al norte hay una pequeña construcción rodeada por una alambrada. Guardias
 amenazadores con pesadas armaduras, patrullan en el área.}
{108}{}{Un gran cráter se extiende al norte.}
{109}{}{Se ven guardias mutantes al noreste, en frente de una fortificación
 construida en la falda de la montaña.}
{110}{}{Un edificio recargado se alza hasta el cielo. Una multitud camina sin
 rumbo hacia él.}
{111}{}{Al norte puedes ver un almacén, rodeado por un foso lleno de un potingue reluciente.}
{112}{}{Delante de ti ves una gran fábrica fortificada, con graffitis en las paredes
 y puestos de vigilancia amenazadores.}
{113}{}{Hay signos evidentes de actividad de bandas en el club nocturno medio reconstruido
 y en los pequeños puestos fronterizos.}
{114}{}{En el corazón de la ciudad se alza, fortificada y restaurada, una
 biblioteca, inasequible pero grandiosa. Una sensación de paz te inunda.}
{115}{}{Al sur te espera a la defensiva una aldea rodeada con una alambrada y patrullada por guardias.}
{116}{}{Ves una huella gigante en el suelo. Buscas, pero no encuentras otros
 rastros en la zona.}
{117}{}{Restos de fuego y cenizas cubren este sitio.}
{118}{}{Parece que esta zona fue alcanzada por una bomba de fuego de alta presión.}