{100}{}{Ves a Sid, el ayudante de Beth.}
{101}{}{Buenos días.}
{102}{}{¡Buenas tardes, señor!}
{103}{}{¡Buenas tardes, señora!}
{104}{}{Buenas noches.}
{105}{}{Lo sé, lo sé... [Susurra] Es horrible todo lo que habla, ¿verdad?}
{106}{}{Bienvenido a la Armería de Beth y Rumor Mill.}
{107}{}{Beth, alguien ha venido a verte.}
{108}{}{Bienvenido al Palacio del Placer de Beth.}
{109}{}{¿Traes algún regalo?}
{110}{}{[Susurra] No le digas nada que no quieras que sepa toda la ciudad.}
{111}{}{¿Otra vez?}
{112}{}{¡Armas gratis! ¡Ven y coge las que quieras!}
{113}{}{Luz azul especial en el pasillo tres.}
{114}{}{¡Es mía, ni lo pienses!}
{115}{}{Le gusta jugar duro.}
{116}{}{Hora del desayuno.}
{117}{}{Hora de la comida}
{118}{}{Buenas noches.}
{119}{}{Bonito traje azul, ¿eh?. ¿El 13 es tu número de la suerte?}
{120}{}{¡Oh, es el hombre misterioso!}
{121}{}{¡Oh, es la mujer misteriosa!}
{122}{}{¿Lees el porvenir en las manos?}
{123}{}{¡Oh, a Beth le encanta el cuero!}
{124}{}{Oye, cariño, cómprale la chaqueta de cuero para mí.}
{125}{}{Oye, cariño, cómprale la chaqueta de cuero para mí.}
{126}{}{¡Bonita armadura!}
{127}{}{Es camuflaje, te va muy bien. ¡Espera! ¿Dónde crees que vas?}
{128}{}{Eh, ese es un conjunto de aspecto cortante.}
{129}{}{¡En absoluto!}
{130}{}{¡Ah! Es la lata de metal. ¿Cómo te va?}
