{100}{}{La puerta del Fosa Común está cerrada.}
{101}{}{Consigues abrir la puerta.}
{102}{}{Intentas abrir la puerta pero no lo consigues.}
{103}{}{Oyes un chasquido. Parece que el cerrojo está atrancado.}
{104}{}{La puerta no está cerrada.}
