{100}{}{Ves a Slappy.}
{101}{}{Bugi, Bugi, Bugi.}
{102}{}{Es como una apisonadora, machacando, machacando.}
{103}{}{Juguemos a la Guerra Mundial Termo-Nuclear.}
{104}{}{¡¿¡Dónde está mi maldito!?!}
{105}{}{Ahí... ahí... ahí...}
{106}{}{La Luna está ahí fuera.}
{107}{}{Dame la miel, nena.}
{108}{}{Oooh, bonito, bonito. ¿Por qué está la luna?}
{109}{}{Uh, hablé con Harold. Eso de la Garra Mortal suena a algo bastante malo. ¿Qué puedes decirme de ello?}
{110}{}{Beth me dijo que hablara contigo sobre la Garra Mortal.}
{111}{}{¿Qué haces por aquí?}
{112}{}{¿Cuál es tu problema?}
{113}{}{¡Luna Grande, mi gustar Luna!}
{114}{}{Todo brillante, todo está brillante, el brillo viene a nosotros y luego nos condenamos.}
{115}{}{Ahh.}
{116}{}{Garra Mortal, Garra Mortal, Ga Ga Garra Mortal.}
{117}{}{Venga, ¿qué es lo que sabes de la Garra Mortal?}
{118}{}{¿Cuál es tu problema?}
{119}{}{¡No me obligues a que te lo saque a golpes!}
{120}{}{Yo hago, yo, hago, luego tú haces, entonces todos nosotros hacemos.}
{121}{}{Realmente no, tú qué haces.}
{122}{}{Estás chiflado.}
{123}{}{Los problemas son como los platos de sopa, anchos y poco profundos.}
{124}{}{Como tu inteligencia.}
{125}{}{La Garra Mortal asusta, asusta mucho. Pero parece limpia. ¿Quieres verla?}
{126}{}{¿Puedes llevarme hasta la Garra Mortal?}
{127}{}{¡Diablos, no!}
{128}{}{Sí, Garra Mortal, Garra Mortal, vamos a ver a la Garra Mortal.}
{129}{}{Cállate y llévame allí.}
{130}{}{Ah, da igual. Y a partir de ahora, cuídate.}
{131}{}{Hago esto, luego hago aquello. ¿Has visto a Harold? Harold es diver, se le cae el pelo, se lo lleva el viento. Eso es
 el... viento, viento.}
{132}{}{Cualquier cosa.}
{133}{}{Golpear y golpear y golpear y golpear.}
{134}{}{¿Por qué hay viento? Por qué, por qué, por qué.}
{135}{}{Beth, Beth, gua paa Beth. Gusta Harold, habla Harold. Harold contar a ti historia. Slappy ayudar a ellos.}
{136}{}{De acuerdo, primero iré a hablar con Harold.}
