{100}{}{Ves a dos Supermutantes. Uno parece herido y el otro le atiende.}
{101}{}{Bueno, ¿cómo te sientes ahora?}
{102}{}{[Mueve el hombro] Uh, todavía me duele un poco. Pero por lo menos
 ya no sangra.}
{103}{}{Perfecto. Sigue con la medicación y te sentirás como nuevo.}
{104}{}{Excelente. Cuando coja a ese humano de mierda, lo
 aplastaré.}
{105}{}{Excelente. Cuando coja a esa humana de mierda, la
 aplastaré.}
{106}{}{Causó bastantes daños la última vez. Espero que lo cojan pronto.}
{107}{}{Causó bastantes daños la última vez. Espero que la cojan pronto.}
{108}{}{Imagina si todas nuestras plantas se estropearan por culpa de un humano de mierda.}
{109}{}{[Ríe] Sí, menuda vergüenza.}
{110}{}{[Risitas]}