{100}{}{Ves a unos mutantes y niños arrodillados delante de una pantalla de vídeo.}
{101}{}{Reza con nosotros por la paz, hijo.}
{102}{}{La Unidad vencerá si somos fuertes. Meditad sobre la calidad de
 la fuerza.}
{103}{}{Tenemos que tener fe para salvar a la humanidad.}
{104}{}{¡Incrédulo! ¡Blasfemo! ¡Serás castigado!}
{105}{}{Debemos rezar para ser fuertes. El día del cambio está cerca.}
{106}{}{La Unidad es nuestro futuro, hermano.}
{107}{}{La Unidad es nuestro futuro, hermana.}
{108}{}{Creo en el Maestro. Su voluntad es nuestra salvación.}
