{100}{}{Ves a Sophia, instructora de los Iniciados de la Hermandad.}
{101}{}{Bueno, ¿quiere hacer alguien alguna pregunta?}
{102}{}{Podéis hacer preguntas si no entendéis algo. No seáis tímidos.}
{103}{}{Repasad vuestras notas.}
{104}{}{Los que estéis en la sección 14 tendréis mañana otro examen.}
{105}{}{Lo siento, pero no puedo hablar ahora. Tengo que dar una clase.}
{106}{}{Creo que tienes algo para mí.}
{107}{}{Sí. Aquí tienes.}
{108}{}{Sí, pero no lo tengo conmigo en este momento.}
{109}{}{Tú.}
{110}{}{Lo siento, pero tengo que dar una clase. Por favor, no me molestes.}
{111}{}{No deberías estar aquí. A Vree no le gusta que la molesten por la noche. A esta hora meditamos.}
{112}{}{Estamos meditando. Por favor, vete. Vuelve por la mañana.}
{113}{}{Déjanos.}
{114}{}{Ten un poco de respeto. No molestes a la gente cuando está meditando.}
{115}{}{Vosotros los Iniciados tenéis mucho que aprender. Vete por favor.}
{116}{}{No me molestes.}
{117}{}{No podemos atenderte por la noche. Por favor, ven a vernos por la mañana.}
{118}{}{Es de noche. Deberías estar en la cama, a menos que estés de guardia, en cuyo caso deberías estar en tu puesto.}
{200}{}{Hola, Iniciado. ¿En qué puedo ayudarte?}
{201}{}{¿Tienes algo para mí?}
{202}{}{Sí, aquí tienes.}
{203}{}{Sí, pero no lo llevo conmigo ahora.}
{204}{}{¿Yo? No, lo siento. Debes confundirme con otra persona.}
{205}{}{Vale.}
{206}{}{Muchas gracias. Ha sido muy amable de tu parte el desprenderte de eso.}
{207}{}{Emm, gracias. ¿Estás bien? Bueno, de todas formas gracias por desprenderte de eso.}
{208}{}{Mi investigación se habría retrasado sin ellas. Es bueno ver que tenemos a un Iniciado en el que se puede confiar.
 Sabía que meter a un extraño no sería una mala decisión. Ve a ver a Michael, tiene algo para ti.}
{301}{}{Saludos. No te había visto antes por aquí, ¿te has perdido?
 ¿Puedo ayudarte en algo?}
{302}{}{Eh......}
{303}{}{¿Podrías decirme dónde está la biblioteca?}
{304}{}{Estoy buscando a Vree.}
{305}{}{¿Qué es este lugar?}
{306}{}{¡Si me hubiera perdido no le pediría ayuda a una idiota como tú!}
{307}{}{¿Esta es la clase de gente que aceptamos como iniciados ahora?
 ¡Que dios nos ayude!}
{308}{}{Esta es la biblioteca. Aquí guardamos todo tipo de datos técnicos sobre
 armamento y tecnología y, por supuesto, sobre la historia de la Hermandad.}
{309}{}{Necesito reparar un Chip de agua. ¿Puedes ayudarme?}
{310}{}{Me gustaría saber algo más sobre las armas que fabricáis aquí.}
{311}{}{¿Es aquí donde puedo encontrar los holodiscos?}
{312}{}{Da igual, gracias por tu tiempo.}
{313}{}{Busco un arma muy grande para mejorar mi destreza matando gente.}
{314}{}{Yo soy la ayudante de Vree. Vree está ahí.}
{315}{}{Gracias.}
{316}{}{¿Cuál es tu trabajo como ayudante de Vree?}
{317}{}{Soy experta en la historia de la Hermandad. Para
 problemas de fabricación debes hablar con Vree.}
{318}{}{Pensé que los escribas sabíais este tipo de cosas.}
{319}{}{Me gustaría saber cosas de la historia de la Hermandad.}
{320}{}{¡Eres de gran ayuda!}
{321}{}{Bien, gracias por tu ayuda.}
{322}{}{Debes hablar con Vree, la jefa de los escribas. Yo tengo cosas
 más importantes que hacer.}
{323}{}{Iré a preguntarle a Vree.}
{324}{}{¿Cosas más importantes que hacer? ¿Como qué?}
{325}{}{¿No consideras importante el armamento de la Hermandad?}
{326}{}{Tenemos muchos holodiscos aquí en la biblioteca. Están divididos
 en historia, tecnología y diseño de armas.}
{327}{}{Me gustaría ver un holodisco sobre vuestra tecnología.}
{328}{}{Me gustaría ver un holodisco sobre diseño de armas.}
{329}{}{Me gustaría ver un holodisco sobre la historia de la Hermandad.}
{330}{}{Me han enviado aquí para preguntar a Vree sobre la historia de la Hermandad.}
{331}{}{Estoy especializada en historia de la Hermandad. Parece que
 algunos de por aquí han olvidado la importancia de nuestra historia.}
{332}{}{¿Qué puedes decirme de la historia de la Hermandad?}
{333}{}{¿Qué podría ser más importante que la historia?}
{334}{}{Tienes el síndrome premenstrual, ¿eh?}
{335}{}{Me gustaría preguntar a alguien sobre las armas.}
{336}{}{Cómo guardar la historia de la Hermandad. Parece que algunos
 de por aquí han olvidado la importancia de nuestra historia.}
{337}{}{Vree parece pensar que la investigación de nuevas armas y la
 información sacada de las autopsias de mutantes es más importante que nuestra
 historia. Se olvida que nuestra historia es una parte vital de nuestras vidas.
 Están tan mal las cosas que algunos de los nuevos iniciados ni siquiera saben quién
 es Roger Maxson ni qué es lo que hizo por nosotros.}
{338}{}{Me gustaría aprender algo más de la historia de la Hermandad. ¿Tienes
 alguna información más?}
{339}{}{Mmm, parece que Vree es la persona con la que quiero hablar. Adiós.}
{341}{}{¡Parece que Vree tiene razón! ¡¿Quién necesita saber
 toda esta basura!?}
{342}{}{Estoy de acuerdo con que la historia es importante, pero lo que busco son
 nuevas tecnologías y armas.}
{343}{}{Para cosas de ese tipo tienes que hablar con Vree.}
{344}{}{Eso son cosas a las que sólo tienen acceso los Escribas y los Paladines.
 Vree quizá pueda ayudarte.}
{345}{}{Gracias, irá a hablar con Vree.}
{346}{}{¿Hay algún holodisco al que pueda tener acceso?}
{347}{}{Es obvio que no eres la persona con la que debo hablar. Adiós.}
{348}{}{Bueno, me alegra ver que todavía le interesa a alguien nuestra magnífica historia,
 al contrario que otros de por aquí. Aquí tienes. Este holodisco contiene algunos de nuestros primeros escritos.}
{349}{}{Gracias.}
{350}{}{No me importa esta mierda. Gracias por nada.}
{351}{}{Nuestra historia está disponible para cualquiera. Así se puede aprender de
 ella... bueno se aprendería si alguien los usara.}
{352}{}{Me gustaría ver lo que tienes sobre la historia de los Hermanos.}
{353}{}{¿De verdad? Tampoco me importa. Sólo te pido que me enseñes las armas.}
{354}{}{Saludos. No te había visto antes, ¿te has perdido? ¿Puedo
 ayudarte en algo?}
{355}{}{Eh......}
{356}{}{¿Podrías decirme cómo llegar a la biblioteca?}
{357}{}{Me enviaron aquí para hablar con Vree sobre la historia de la Hermandad.}
{358}{}{¡Si me hubiera perdido no le pediría ayuda a una idiota como tú!}
{359}{}{No has llegado muy lejos con eso, ¿verdad? Vree está demasiado ocupada con
 sus "experimentos" como para preocuparse de la historia.}
{360}{}{¿Y entonces con quién se puede hablar de la historia de la Hermandad?}
{361}{}{Sí, al parecer la Hermandad está llena de idiotas.}
{362}{}{Yo tampoco. Adiós.}
{363}{}{No hablaré contigo.}
{364}{}{¿En qué puedo ayudarte?}
{365}{}{¿Qué haces aquí?}
{366}{}{¿Podrías hablarme la historia de la Hermandad?}
{367}{}{Lo siento, te he confundido con otra persona. Adiós.}
{368}{}{Soy la ayudante de Vree.}
{369}{}{Gracias.}
{370}{}{¿En qué consiste tu trabajo como ayudante de Vree?}
{371}{}{Bien, me gusta saber que se interesa alguien en nuestra historia,
 No como otros. Aquí tienes. Este disco contiene algunas de nuestros primeros escritos.}
{372}{}{Gracias.}
{373}{}{No me interesa esta mierda. Gracias por nada.}
{374}{}{Te di el disco con algunos de nuestros primeros escritos. Sólo
 tienes que cargarlo en tu PIPBoy 2000 y podrás leer su contenido.}
{375}{}{Gracias.}
{376}{}{No me importa esta mierda. Gracias por nada.}
{377}{}{No me gusta tu actitud. Y ya no pienso hablar contigo.}
{378}{}{Así sea. ¡Adiós!}
{379}{}{Lo siento, he sido un maleducado, te pido disculpas.}
{380}{}{Acepto tus disculpas. ¿En qué puedo ayudarte? }
{381}{}{¿Qué haces aquí?}
{382}{}{¿Podrías hablarme de la historia de la Hermandad?}
{383}{}{Lo siento, te he confundido con otra persona. Adiós.}
{384}{}{Soy la ayudante de Vree. Ella está en el Centro de Aprendizaje.}
{400}{}{Ves a una instructora de los Iniciados de la Hermandad.}
