{100}{}{Yo podría hacerlo.}
{101}{}{Es fácil.}
{102}{}{Déjame enseñarte cómo se hace.}
{103}{}{Bien.}
{104}{}{Ah, ya veo.}
{105}{}{Oh, no está mal ese movimiento.}
{106}{}{Con que se hace así...}
{107}{}{Nunca podría hacerlo.}
{108}{}{Estás en buena forma.}
{109}{}{Casi.}
{110}{}{Presta atención.}
{111}{}{No seas desagradable.}
{112}{}{Escucha.}
{113}{}{¡Shhhh!}
{114}{}{Por favor, apártate de mi camino.}
{115}{}{Gracias.}
