{100}{}{Ves a Katrina. Tiene una bonita sonrisa.}
{101}{}{No llevo armas, por favor, aparta la tuya.}
{102}{}{¡Hng!}
{103}{}{¿Por qué habría de hacerlo? Este mundo parece muy peligroso.}
{104}{}{¿Para qué sirve eso?}
{105}{}{Quizá sí, quizá no.}
{106}{}{Tomaré eso como un sí.}
{107}{}{Debería estar de acuerdo contigo. Es muy peligroso viajar
 sin armas. Pero esto es Arenas Sombrías y somos gente pacífica. No hay
 necesidad de ir armado.}
{108}{}{De acuerdo. Gracias.}
{109}{}{Si no apartas tu arma, no hablaré contigo. Hay
 mucha gente como yo. Sólo debes usar la fuerza si la situación lo
 requiere.}
{110}{}{Mmm, vale.}
{111}{}{Bienvenido a Arenas Sombrías, viajero. Me llamo Katrina. Mi trabajo consiste
 en dar la bienvenida a los forasteros y ayudarlos a entender nuestro pueblo. Sabemos que tendrás menos problemas si escuchas lo que tengo que decir.}
{112}{}{¡Yupi!}
{113}{}{Cuéntame algo más sobre ti.}
{114}{}{Ayúdame, por favor...}
{115}{}{Estoy buscando un Chip de agua. ¿Has visto uno?}
{116}{}{Necesito ayuda para encontrar a Tandi.}
{117}{}{Estoy tratando de resolver el problema que tenéis con los Escorpiones Rad. ¿Alguna pista?}
{118}{}{Gracias, puede que más tarde.}
{119}{}{Es una pena que seas tan tonto. Será muy difícil
 que nos entendamos. Espero que los demás habitantes de tu refugio no sean como tú.}
{120}{}{¿Wubba-val?}
{121}{}{Sí, puedo decirte que vienes de un Refugio. Se te nota enseguida.
 Yo vengo del Refugio 15, al este. Pero tuve que abandonar mi hogar y ahora
 vivo aquí. Con suerte encontrarás los que buscas, aunque sólo sea un lugar donde vivir. Espero que no te echaran del refugio
 por ser demasiado inteligente. De verdad espero que no fuera por eso.}
{122}{}{Hng.}
{123}{}{Tendrás que encontrar otro modo de obtener respuestas ya que no se te da muy bien conversar. Espero que no hagas sufrir a demasiada gente
 en tu viaje. Por favor, sé amable con la gente de por aquí, no te deseamos ningún mal.}
{124}{}{Ahhh.}
{125}{}{Me encantaría ayudarte. Antes era como tú. Por suerte,
 mi conocimiento será útil.}
{126}{}{¿Qué debo hacer si me hieren?}
{127}{}{¿Dónde puedo conseguir un equipo mejor?}
{128}{}{Háblame de este lugar.}
{129}{}{Háblame del resto del mundo.}
{130}{}{Háblame de ti.}
{131}{}{Eso es todo por ahora, gracias.}
{132}{}{Bueno, si no consigues ir a ver a un médico, tendrás que curarte sólo. Los medicamentos son muy prácticos. Tómatelos en caso de herida leve.
 También puedes utilizar los Primeros Auxilios que actúan más lentamente pero que están siempre disponibles. Para heridas
 más importantes, como una pierna rota, tendrás que usar la técnica de Médico.}
{133}{}{Tendrás que hacer lo que nosotros. Busca o comercia para conseguirlo.
 Si te atacan, tus enemigos pueden proporcionarte equipo, si vives lo suficiente
 como para saquearlos. Somos una comunidad pacífica, así que normalmente
 comerciamos o trocamos objetos que no podemos producir.}
{134}{}{Háblame del trueque.}
{135}{}{Estás en Arenas Sombrías. Sólo somos una pequeña ciudad en un mundo
 enorme. Lo único que queremos es que nos dejen en paz. Quitando algunos animales mutados
 y otras criaturas del desierto, sólo los Piratas nos causan problemas.
 Aradesh es nuestro líder. Está en la gran casa central, habla con él.}
{136}{}{Sé muy poco del mundo exterior. Escapé de un Refugio cuando
 fue atacado. Por desgracia, estaba malherida y no recuerdo
 mucho de lo que pasó. Pero Dharma me cuidaba; me
 encontraron habitantes de Arenas Sombrías. Ahora vivo aquí. ¿Ya has
 hablado con Ian? Es un guardia mercader que fue herido. Se está
 recuperando ahí en el cuartel. [Señala al este]
 Él ha viajado mucho más que yo.}
{137}{}{Mi vida era muy aburrida. Me crié en el Refugio. Viví allí
 muchos años. Por desgracia, éramos muchos y la vida era muy mala.
 Hubo un cisma y mucha gente se fue, llevándose consigo los mejores
 equipos. Aún así, algunos de nosotros intentamos seguir en el Refugio. Pero fuimos
 atacados. Me hirieron y aquí terminé. Ahora intento
 ayudar a la gente...}
{138}{}{¿Dónde estaba tu Refugio?}
{139}{}{El trueque es el intercambio de cosas. Tú me das algunos objetos,
 y yo te doy otros a cambio. Como tú iniciaste el trueque,
 te dejo elegir lo que quieras coger. Pero el trato debe
 gustarme, así que probablemente querrás darme bienes más
 valiosos que no necesitas a cambio de cosas de menos valor que te hagan falta.
 Y si no tienes suficientes objetos valiosos para comerciar, están las chapas.
 Las chapas de botella son la única moneda que se utiliza por aquí. Las chapas son garantizadas por
 los mercaderes del Eje, así que puedes utilizarlas en todos los lugares.}
{140}{}{Era el Refugio 15. Está al este de aquí. Intentamos ponernos en
 contacto con otros Refugios, pero nunca lo conseguimos. Creo que fueron los
 Piratas los que atacaron a mis conciudadanos. ¡Ten cuidado!}
{141}{}{Espero que la encuentres. Es como una hermana pequeña para mí. Creo
 que fue uno de los grupos Piratas quien se la llevó. Busca toda la información
 que puedas sobre ellos y equípate antes de ir a buscarlos. Pero no tengas
 prisa por luchar, hasta ellos se atienen a razones de vez en cuando...}
{142}{}{Seth ha intentado seguir a los Escorpiones Rad. Dice que
 incluso conoce el camino hasta su guarida, pero creo que tiene miedo
 de salir ahí fuera. Su hermano fue gravemente herido por uno de
 los mutantes, y Seth no sabe que hacer.}
{143}{}{En realidad, sí. Mi antiguo hogar, el Refugio 15, tenía uno.
 No he vuelto allí desde que me hirieron, pero puede que allí encuentres
 lo que buscas. Me dijo alguien que intentaron ir al Refugio
 para echar un vistazo, pero era demasiado oscuro y el ascensor estaba
 estropeado. Espero que tú estés mejor preparado.}
{144}{}{Hola otra vez. Espero que te vaya bien. ¿Puedo ayudarte en algo?}
{145}{}{¿Es que nunca vas a dormir?}
{146}{}{Cuando no estás por aquí me echo una siesta. Además, encuentro el aire
 del desierto muy saludable y estimulante. Y nunca me canso de mirar a las
 estrellas. ¿Te imaginas no haber visto en toda tu vida el cielo de la noche?
 [Hace una pausa y te mira] Oh, supongo que sí.}
{147}{}{Ah, sí. Gracias.}
{148}{}{¿Hay un médico por aquí?}
{149}{}{Los lugares pequeños como Arenas Sombrías no podrían sobrevivir sin
 la ayuda de un curandero. Nuestro médico, Razlo, vive en la casa que está más hacia el sur. Si
 estás gravemente herido, ve a verlo. Intenta no molestarlo por la noche. Si no duerme
 se vuelve muy irritable.}
{150}{}{Ganas 250 puntos de experiencia por lo que has aprendido de
 Katrina.}
{151}{}{Por aquí suelen colgar a los ladrones. Pórtate bien.}
