{100}{}{Ves a la señora Stapleton, la bibliotecaria.}
{101}{}{Ves una mujer de mediana edad.}
{102}{}{Hola, bienvenido a la Biblioteca. Creo que no te he visto antes por aquí.
 Dime, ¿qué tema te interesa?}
{103}{}{Me alegro de volver a verte. ¿Qué es lo que buscas hoy?}
{104}{}{¿Qué tipo de libros tienes?}
{105}{}{Estoy buscando un Chip de agua.}
{106}{}{Nada, pero gracias por preguntar.}
{107}{}{Bueno, ahora te enseño lo que tengo.}
{108}{}{Bueno, en el transcurso de mis estudios he encontrado algunas referencias a estas cosas. De hecho, tengo en mi poder un Holodisco que contiene cierta información que
 podría serte útil.}
{109}{}{Un Holodisco, ¿qué es eso?}
{110}{}{¿Puedes darme el Holodisco?}
{111}{}{Un Holodisco contiene información pero se necesitan unos cuantos dispositivos electrónicos para poder leerlo. Veo que tienes una PIPBoy. Puedes usarla para descodificar, leer
 y almacenar la información que contiene el Holodisco.}
{112}{}{¡Es estupendo! ¿Puedes darme el Holodisco?}
{113}{}{Hoy en día es muy difícil conseguir información. Tendré que cobrarte 750
 chapas por el disco.}
{114}{}{No está mal. Aquí tienes tus chapas.}
{115}{}{Este Holodisco está muy usado. Te doy 500 por
 él.}
{116}{}{¡¿Y si en vez de eso le prendiera fuego a este sitio?! ¡¿Qué le parece señora?!}
{117}{}{Lo siento, no tengo tantas chapas.}
{118}{}{Lo siento, pero no rebajaré mi precio por el Holodisco. Por favor, vuelve
 cuando tengas las chapas.}
{119}{}{Lo siento, pero tendrás que guardar para ti tus tendencias pirómanas.
 Vete, por favor.}
{120}{}{[La señora Stapleton coge las chapas.]}
{121}{}{Tienes razón, el disco ya tiene sus días. Puesto que así es, aceptaré
 500 en vez de mi precio original. [La señora Stapleton coge las chapas.]}
{122}{}{Normalmente, no sucumbo ante tales métodos, pero para proteger mi colección de tal
 amenaza te daré el disco. A cambio, te pediré que no vuelvas nunca por aquí.}
{123}{}{Como he dicho, tendrás que usar esto y acceder a la información
 con tu PIPBoy. [La señora Stapleton te da el holodisco]}
{124}{}{Tienes que perdonarme, pero tengo que seguir investigando.}
{125}{}{¿Ruk?}
{126}{}{Lo siento pero no te entiendo. En alguna parte tengo un Holodisco para aprender el idioma, por si te interesa.}
{127}{}{Adiós.}
{128}{}{Gracias.}
{129}{}{Ug.}
{130}{}{¿Tienes revistas de Química? Miles en Adytum me dijo que tendrías.}
{131}{}{Sí, conozco a Miles y tengo lo que buscas. Te costarán 750 chapas.}
{132}{}{Aquí tiene, señor. Saluda a Miles de mi parte.}
{133}{}{Lo siento pero no tienes bastantes chapas. Por favor, vuelve cuando las tengas.}