{100}{}{Estás viendo a Tandi.}
{101}{}{¿Qué más hay por esta zona?}
{102}{}{¿Qué pasa por aquí?}
{103}{}{¿Te han llegado rumores del sur?}
{104}{}{¿Qué te parece esto?}
{105}{}{Bueno eso es todo. Gracias por tu tiempo.}
{106}{TAND_1}{¡Hola! Oí decir que había un viajero en la ciudad, pero
 no me lo creí hasta que te vi. Me llamo Tandi. ¿Y tú?}
{107}{}{Mi nombre es }
{108}{}{.}
{109}{}{El nombre es }
{110}{}{.
 Recuérdalo.}
{111}{}{¿Ehhh?}
{112}{tand_2}{¿Te gusta nuestra pequeña ciudad? ¿Ya te ha aburrido?}
{113}{}{Está bien. ¿Puedo hacerte unas preguntas?}
{114}{}{Sí, desde luego. No hay nada que hacer aquí, salvo mirar como copulan los Brahmins.}
{115}{}{Supongo que está bien.}
{116}{}{Bueno, es un poco aburrido.}
{117}{TAND_3}{Claro, supongo. Nunca he salido de aquí, así que no sé si puedo
 ayudarte en algo. ¿Qué necesitas?}
{118}{TAND_4}{Sí. Bueno, tú no
 vives aquí. No hay nada interesante que hacer y créeme, te hartas
 enseguida de los Vertidos de los Brahmins.}
{119}{}{Si tanto te aburres, ¿por qué no te marchas?}
{120}{}{Seguro que estás exagerando.}
{121}{}{A mí esto me parece bonito y seguro.}
{122}{TAND_5}{¿Yo, marcharme? Lo estoy deseando. Pero no sé lo bastante
 como para irme sola y nadie más quiere irse. Y lo peor de todo, ¡mi padre dice
 que le dará un ataque al corazón si me ocurre algo! }
{123}{}{Difícil situación. ¿Puedo hacerte unas preguntas?}
{124}{}{Caray. Tengo que irme. Buena suerte.}
{125}{TAND_6}{Eh... ahora tengo que estar por aquí. }
{126}{TAND_12}{¡Pásate aquí toda la vida y veremos si te gusta! ¿Quieres
 saber algo más?}
{127}{TAND_13}{Sí, muy seguro... y tan aburrido que me puede chorrear el cerebro por las orejas en cualquier momento.}
{128}{}{¿Por qué no te marchas entonces?}
{129}{}{Siento oír eso, pero no tengo mucho tiempo.
 ¿Puedo hacerte unas preguntas?}
{130}{TAND_14}{¡Por fin! ¡Alguien que también
 lo entiende! Claro que probablemente tú hayas estado en todas partes y esto te debe parecer el
 infierno.}
{131}{}{¿Si te aburres tanto, por qué no te marchas?}
{132}{}{Seguro que estás exagerando.}
{133}{}{Este lugar me parece bonito y seguro.}
{134}{TAND_15}{Ciudad Vertedero está al sudoeste, pero no sé a qué distancia.
 Debajo hay un extraño lugar llamado la Ciudad de la Muerte. Oh, oh
 sí, también está ese otro sitio... Oh, caray, ¿cómo se llamaba? Ah sí, el
 Eje.}
{135}{tand_15a}{Hay un par de ciudades al sur. Pero como viajas tanto,
 seguro que ya lo sabes.}
{136}{}{Gracias.}
{137}{TAND_16}{No hay problema. ¿Algo más?}
# {300}{tand_16a}{Sí, lo que sea.} Wrong number! Removed with patch 1.3 from TeamX.
{138}{TAND_20}{¡Tenemos Escorpiones
 Rad! A ver si me entiendes, sé que no es nada bueno, pero nadie se ha muerto por sus
 picaduras. ¡Y es lo más excitante que tenemos aquí!}
{139}{TAND_21}{No mucho desde que acabaste con esos Escorpiones Rad. Caray, me
 hubiera encantado verlo.}
{140}{TAND_22}{Como siempre. A-bu-rri-do.}
{142}{tand_23b}{Cosas.}
{141}{tand_23g}{La historia más rara que he oído es sobre una Garra Mortal.}
{143}{}{Gracias.}
{144}{}{¿Una Garra Mortal?}
{145}{TAND_24}{Supongo que no está mal. Es mi hogar y todo eso, ¡pero es tan
 aburrido! ¿Sabes? Quiero conocer el mundo.}
{146}{}{¿Si te aburres tanto, por qué no te marchas?}
{147}{}{Bueno, seguro que no es para tanto.}
{148}{}{Este sitio me parece bonito y seguro.}
{150}{tand_27f}{Pero... esto... o sea... eh... a mí me gustan los tíos, ¿vale? ¡Vaya! Eh,
 discúlpame, tengo cosas que hacer.}
{149}{tand_27m}{No soy ese tipo de chica,
 señor, vete a buscar un Brahmin o algo.}
{151}{TAND_28}{En fin, gracias por hablar conmigo.
 No pasan muchos forasteros por aquí, así que siempre se agradece hablar con gente nueva.
 ¡Nos vemos! }
{152}{}{Hasta luego.}
{153}{TAND_29}{Oye, mira. Tengo que cuidar de los
 Brahmins. Me ha, eh, encantado hablar contigo. }
{154}{tand_30a}{¡Hola otra vez! ¿En qué
 puedo ayudarte ahora?}
{155}{}{¿Puedo hacerte unas preguntas?}
{156}{}{Nada. Adiós.}
{157}{TAND_35}{Eh... oye, gracias. Más tarde.}
{158}{TAND_36}{¡Hola! Temía que te hubieses ido y no tener
 la oportunidad de agradecerte por haberme rescatado.
 ¡Caray! ¡Fue genial! Acción, aventura... Si hay algo que pueda hacer
 por ti, dímelo.}
{159}{}{¿Qué tal algunas preguntas más?}
{160}{}{Qué te parece si tú y yo... bueno, ya sabes... nos juntamos.}
{161}{}{No, eso es todo, gracias.}
{162}{}{¡¡Caray!!}
{163}{TAND_37}{¿Quién eres? ¿Qué quieres?}
{164}{}{Me llamo }
{165}{}{, y me ha enviado tu padre.}
{166}{}{Soy tu hada madrina. ¿Qué te parece?}
{167}{}{Bah.}
{168}{TAND_38}{¿¡Mi padre te ha enviado!? ¿Estás aquí para sacarme?}
{169}{}{Sí, así es que estate quietecita. Yo te sacaré.}
{170}{}{No, me envió para que te buscase.}
{171}{TAND_39}{Bueno, ¿qué plan tienes?}
{172}{}{Sólo esperar a que se abran las puertas. Luego, ¡corre!}
{173}{}{Estoy aquí para luchar con el líder de los Khans
 a cambio de tu libertad.}
{174}{TAND_40}{¿Eso es todo? Ese es tu plan.
 ¡Ah! Está bien. Pero date prisa. Les he oído hablar y no me gustaron sus
 planes. }
{175}{TAND_41}{¿Tú? ¿Luchar contra él? ¡Me
 tomas el pelo! [Suspira] Mira, si se te ocurre otro plan, házmelo
 saber, ¿vale? }
{176}{TAND_42}{Oh, ¿me vienes con sarcasmos? ¿¡Me vas a sacar de
 aquí o qué!?}
{177}{}{Sí. Espera un poco y cuando veas que se abre la puerta, corre hacia ella.}
{178}{}{Lucharé contra el líder de los Khans a cambio de tu libertad.}
{179}{TAND_43}{¡Oh, eres tú otra vez! ¿Me vas a sacar de
 aquí?}
{180}{}{Sí, tú estate quietecita. Yo te sacaré.}
{181}{}{No, sólo venía a saludarte.}
{182}{}{Bah.}
{183}{tand_43a}{Hola, ¿hay alguien en casa? ¿Me puedes sacar de aquí?
 ¡Me puedes SACAR DE AQUÍ!}
{184}{tand_43b}{No hay tiempo para hablar, tenemos que salir de aquí.}
{185}{TAND_44}{Aradesh es mi padre. Como padre no está mal.}
{186}{TAND_45}{Esa soy yo. ¿Quién creías que era?}
{187}{TAND_46}{Razlo es el tipo viejo del lado este de la ciudad. Es un médico bastante
 bueno, a pesar de ser un fósil. }
{188}{TAND_47}{Seth es el Capitán de los guardias. Mi padre intentó
 juntarnos una vez, pero no es mi tipo.}
{189}{TAND_48}{Agatha es la que lleva más tiempo aquí. Todos la adoramos, sobre todo
 a sus cuentos. Vete a verla, especialmente si te gustan las historias.}
{190}{TAND_49}{Un atajo de
 indeseables, según he oído. Mi padre sabe más acerca de ellos. Nunca me
 cuenta casi nada del mundo exterior.}
{191}{TAND_50}{Allí es donde conseguimos toda nuestra agua. Es más viejo que yo.}
{192}{TAND_51}{De hecho he visto uno, aunque fuese de lejos. Son
 criaturas desagradables con pinzas y un gran aguijón. Y su veneno puede ser
 mortal si no se trata rápido. Deberías hablar con mi padre, Aradesh, él sabe
 más sobre ellos. }
{193}{TAND_52}{Oí una historia de un viajero del sur. Contaba que
 la Garra Mortal es una criatura que mata gente por la noche. Dijo que nadie la puede
 capturar porque desaparece como el humo. Pero yo no me lo trago.}
{194}{TAND_53}{Vertedero es una pequeña ciudad al sudoeste. Se supone que
 tiene un buen comercio, pero mi padre no quiere ni oír hablar de ello. Dice que
 tenemos que permanecer "protegidos". Sí, claro. "Enjaulados" convendría mejor. }
{195}{TAND_54}{Se supone que el Eje es una gran ciudad al sur. Siempre he querido visitarla, pero nunca he tenido la oportunidad de hacerlo.}
{196}{TAND_55}{No lo
 sé, pero el tío que me habló de ella estaba realmente asustado. ¡Me dijo que
 los zombis paseaban por las calles! }
{197}{TAND_62}{No lo sé. Pero podrías preguntárselo a Seth o a mi padre.}
{198}{TAND_63}{Emm... no me suena. }
{199}{TAND_64}{Emm... no. Nunca oí hablar de ello. }
{200}{TAND_65}{¡Oye! ¿Qué crees que estás haciendo? ¡Deja eso! }
{201}{TAND_66}{¡Ya está bien! ¡Se lo diré a mi padre! }
{202}{TAND_67}{¿Qué demonios te crees que estás haciendo? ¡Para! }
{203}{TAND_68}{¿Qué estás haciendo aquí? Más vale que te
 vayas antes de que mi padre se despierte.}
{204}{TAND_69}{Como ya te dije...}
{205}{TAND_70}{Escucha, ya te dije que... }
{206}{TAND_71}{¿Otra vez? ¿Hola? ¿Cuántas veces tengo que
 decírtelo? ¿Tienes cera en los oídos o qué?}
{207}{TAND_72}{Oh sí, he oído hablar de eso, pero deberías ir a ver a Agatha.
 Ella sabrá más que yo.}
{208}{}{Salgamos de aquí.}

{300}{}{¡Guau! Esto no se parece nada a Arenas Sombrías.}
{301}{}{¿Oye, qué es eso de ahí?}
{302}{}{No puedo esperar a contarles a los de Arenas Sombrías como es el mundo exterior.}
{303}{}{¿Has visto más Escorpiones Rad?}
{304}{}{¿Dónde vamos ahora?}
{305}{}{¿Cuándo vamos a llegar?}


{980}{TAND_62}{No lo sé. Pero se lo puedes preguntar a Seth o a mi padre.}
{981}{TAND_63}{Emm... no me suena. }
{982}{TAND_64}{Emm... no. Nunca lo he oído. }

{1000}{}{Aradesh}
{1001}{}{Tandi}
# "1002 Razlo" Wrong number! Removed with patch 1.3 from TeamX.
{1002}{}{Seth}
{1003}{}{Piratas}
{1004}{}{Pozo}
{1005}{}{Escorpiones}
{1006}{}{Garra}
{1007}{}{Ciudad Vertedero}
{1008}{}{Eje}
{1009}{}{Ciudad}
{1010}{}{Escorpión}
{1011}{}{Khans}
# 1012 added with patch 1.3 from TeamX.
{1012}{}{Razlo}

{1100}{TAND_44}{Aradesh es mi padre. Como padre no está mal.}
{1101}{TAND_45}{Esa soy yo. ¿Quién creías que era?}
#{1102}{TAND_46}{Razlo es el tipo viejo del lado este de la ciudad. Es un médico bastante
# bueno, a pesar de ser un fósil. } Wrong number! Removed with patch 1.3 from TeamX.
{1102}{TAND_47}{Seth es el Capitán de los guardias. Mi padre intentó
 juntarnos una vez, pero no es mi tipo de hombre.}
{1103}{TAND_49}{Un atajo de indeseables, según he oído. Mi padre sabe más acerca de
 ellos. Nunca me cuenta casi nada del mundo exterior.}
{1104}{TAND_50}{Allí es donde conseguimos toda nuestra agua. Es más viejo que yo.}
{1105}{TAND_51}{De hecho, he visto uno, aunque fuese de lejos. Son criaturas
 desagradables con garras y un gran aguijón. Y su veneno puede ser
 mortal si no se trata rápido. Deberías hablar con mi padre, Aradesh, él sabe
 más sobre ellos. }
{1106}{TAND_52}{Oí una historia de un viajero del sur. Contaba que
 la Garra Mortal es una criatura que mata gente por la noche. Dijo que nadie la puede
 capturar porque desaparece como el humo. Pero yo no me lo trago.}
{1107}{TAND_53}{Vertedero es una pequeña ciudad al sudoeste. Se supone que tiene un
 buen comercio, pero mi padre no quiere ni oír hablar de ello. Dice que tenemos
 que permanecer "protegidos". Sí, claro. "Enjaulados" lo describiría mejor. }
{1108}{TAND_54}{Se supone que el Eje es una gran ciudad al sur. Siempre
 quise visitarla, pero nunca tuve la oportunidad de hacerlo. }
{1109}{TAND_55}{No lo sé, pero el tipo que me habló de ella estaba realmente
 asustado. ¡Dijo que los zombis paseaban por las calles! }
{1110}{TAND_51}{De hecho he visto uno, aunque fuese de lejos. Son
 criaturas desagradables con garras y un gran aguijón. Y su veneno puede ser
 mortal si no se trata rápido. Deberías hablar con mi padre, Aradesh, él sabe
 más sobre ellos. }
{1111}{TAND_49}{Un atajo de
 indeseables, según he oído. Mi padre sabe más acerca de ellos. Nunca me
 cuenta casi nada del mundo exterior. }
# 1112 added with patch 1.3 from TeamX.
{1112}{TAND_46}{Razlo es el tipo viejo del lado este de la ciudad. Es un médico bastante
 bueno, a pesar de ser un fósil.}