{100}{}{Estás viendo a Therax, de los Pensadores Nocturnos.}
{101}{}{Estás viendo a Justin, de los Pensadores Nocturnos.}
{102}{}{Estás viendo a Sereine, de los Pensadores Nocturnos.}
{103}{}{Estás viendo a Dolkarn, de los Pensadores Nocturnos.}
{104}{}{Estás viendo a Hort, de los Pensadores Nocturnos.}
{105}{}{Estás viendo a Chris, de los Pensadores Nocturnos.}
{106}{}{Estás viendo a Jaunita, de los Pensadores Nocturnos.}
{107}{}{Estás viendo a Lesley, de los Pensadores Nocturnos.}
{108}{}{Estás viendo a Renfield, de los Pensadores Nocturnos.}
{109}{}{Estás viendo a Timothy, de los Pensadores Nocturnos.}
{110}{}{Bienvenido, Oh Despejador. Has llegado a tiempo para ayudarnos.}
{111}{}{¿Uh?}
{112}{}{Claro. No hay problema.}
{113}{}{Lo siento. Estoy muy ocupado.}
{114}{}{¿Por qué querría ayudaros?}
{115}{}{No importa, ingenuo. Ven conmigo, y te llevaré a que hagas el trabajo.}
{116}{}{Eso no fue una petición. Tu presencia se realizará.}
{117}{}{¿No eres tu el que busca traer la paz a los yermos?}
{118}{}{Sí, sin embargo, no veo cómo ayudaros, hará que eso ocurra.}
{119}{}{No. Prefiero la destrucción de masas.}
{120}{}{Creemos que si todo el mundo, tanto mutantes como humanos, aprendieran a trabajar juntos,
 se podrían resolver muchos problemas.}
{121}{}{Suena prometedor. Cuenta conmigo.}
{122}{}{Olvídalo.}
{123}{}{Hay algo que no me parece bien de todo esto.}
{124}{}{Todo está perfectamente bien. Quizás es la visión limitada de tu cabeza que detiene tus
 avances en el pensamiento.}
{125}{}{Probablemente estés en lo cierto. Cuenta conmigo.}
{126}{}{Quizás. Deja que inspeccione tu cráneo.}
{127}{}{Si es lo que deseas, entonces tendrás tu plenitud.}
{128}{}{Bienvenido de nuevo. Ahora nos ayudarás.}
