{100}{}{Estás viendo a Tolya, un bandido del desierto.}
{101}{}{Hola, soy Tolya. Parece que vienes de recorrer el
 desierto. ¿Quién eres?}
{102}{}{Soy }
{103}{}{. ¿Qué haces?}
{104}{}{¿Me puedes hablar de tu campamento?}
{105}{}{¿Ugh?}
{106}{}{Soy un Pirata y exploro las tierras en busca de nuevos suministros. Algunas poblaciones
 ya han sido honradas con nuestra presencia.}
{107}{}{En otras palabras, robáis a la gente que visitáis.}
{108}{}{Hombre, eso es estupendo de tu parte. Seguro que Garl estará encantado contigo.}
{109}{}{¿Dónde has estado?}
{110}{}{Sabes, Garl siempre me dice que no hable con extraños. Deberías al menos
 decirme tu nombre.}
{111}{}{Tienes razón. Soy }
{112}{}{.
 ¿Me cuentas algo de tu banda?}
{113}{}{Mira imbécil, no tengo porqué contarte nada.}
{114}{}{Vete, idiota.}
{115}{}{Nunca robamos. Sólo cogemos lo que les sobra a los demás y lo redistribuimos
 entre nuestra gente hambrienta.}
{116}{}{O sea que, básicamente, lo robáis.}
{117}{}{Es una idea estupenda.}
{118}{}{He estado en muchos sitios de los yermos. Los más cercanos
 son Arenas Sombrías y Ciudad Vertedero. Están muy agradecidos por
 las visitas que les hacemos.}
{119}{}{¿Has visitado Arenas Sombrías?}
{120}{}{¿Dónde está Ciudad Vertedero?}
{121}{}{Te estás poniendo pesado. Creo que acabaré con ese
 problemilla.}
{122}{}{Somos los Khans y nuestro líder es Garl. Somos los más temidos
 del desierto, y con razón. Cogemos lo que queremos
 y aquellos que se interponen en nuestro camino lo pagan caro.}
{123}{}{Sí, de vez en cuando vamos a Arenas Sombrías. Le pone un poco de
 emoción en las vidas de todos los interesados.}
{124}{}{¿Qué hay de Ciudad Vertedero?}
{125}{}{Ciudad Vertedero está un poco más al Sur.
 Camina unas pocas millas y gira a la derecha después del cactus moribundo. ¡No tiene perdida!}
{126}{}{También dijiste que habías visitado Arenas Sombrías.}
{127}{}{No me molestes ahora. Me estoy preparando para el próximo saqueo.}
