{100}{}{ siente que hay una trampa cerca.}
{101}{}{Sientes que hay una trampa cerca.}
{102}{}{ activa una trampa, alertando a la base de tu presencia.}
{103}{}{Activas una trampa, alertando a la base de tu presencia.}
