{100}{}{¡Aléjate de mí! ¡Déjame en paz!}
{101}{}{Hola forastero. No deberías estar aquí fuera. ¡Sólo encontrarás muerte!}
{102}{}{¿No sabrás algo sobre las caravanas desaparecidas?}
{103}{}{¿Quién eres?}
{104}{}{¿Qué tipo de muerte?}
{105}{}{Necesito provisiones. ¡Dámelas!}
{106}{}{Estoy buscando un Chip de agua. ¿Puedes ayudarme?}
{107}{}{Me preguntaba si sabrías algo sobre las Garras Mortales.}
{108}{}{¿Rurr? ¿Esnifa?}
{109}{}{¡Qué quieres! ¡Déjame tranquilo!}
{110}{}{Rrr. Snrg.}
{111}{}{¡Grande, grandísima! ¡Como tres hombres! ¡Garras como brazos! ¡Rajando
 por aquí! ¡Rajando por allá!}
{112}{}{Sí. ¿Qué más?}
{113}{}{Tranquilízate, hombre. Ahora estás a salvo.}
{114}{}{¡Menudo pedazo de monstruo debe ser!}
{115}{}{¿La mataste?}
{116}{}{Soy Trent. Trabajo como guardia para los Mercaderes del Agua. Nuestra
 caravana fue atacada... ¡por un monstruo! Gigantesco, rapidísimo. ¡Se comió a Joe! ¡Y ni siquiera se inmutó con
 los disparos! ¡Era enorme!}
{117}{}{¿Qué fue lo que os atacó?}
{118}{}{Al parecer se trata de una especie de mutante.}
{119}{}{¡Al parecer se trata de una Garra Mortal!}
{120}{}{¡Bueno, ahora sabes que deberían subirte el sueldo!}
{121}{}{Gracias. No es como si los necesitara todavía.}
{122}{}{¡Chip de agua! ¡Soy un guardia, no un ingeniero! Pregúntale a los
 mercaderes de agua del Eje, ¡ellos sabrán!}
{123}{}{¡Una Garra Mortal!}
{124}{}{¿Qué estás haciendo? ¡Déjame en paz!}
{125}{}{No... no lo sé. Hace tanto tiempo que no duermo. Hambre. Sed. Cansancio.
 Necesito irme a casa.}
{126}{}{}
{127}{}{Cuernos enormes, piel roja asquerosa, como sacada de un cuento de demonios,
 y se comió a Joe en tres bocados...}
{128}{}{¡Nadie está a salvo! Nadie está a salvo, ya no estamos a salvo, y que voy
 a hacer...}
{129}{}{¡Estás mal de la cabeza! ¡Le disparé tres veces con mi Águila del Desierto y ni
 siquiera pestañeó!}
{130}{}{No me importa si era un mutante, un marciano, o un demonio del Infierno.
 ¡No quiero volver a ver una cosa de esas en mi vida!}
{131}{}{¡Sólo soy un guardia, corcho! ¡No me culpes a mí! ¡Y pagan bien! ¡No
 tengo ningún problema con ellos!}
{132}{}{¿Cómo puedo ayudarte?}
{133}{}{Las Garras Mortales las tienen. Creía que eran cuentos, pero... no
 te imaginas lo grandes que son, y lo rápidas. Primero las olimos, luego
 aparecieron y nos atacaron. Todos echamos a correr. No sé cómo conseguí escapar.}
{134}{}{Trent, Trent Barrister. Vivo en el Eje. Últimamente no hay mucho
 trabajo y soy bastante bueno disparando, así que me puse a trabajar como guardia para
 los Mercaderes de Agua. Buen sueldo, bajo riesgo... o por lo menos eso creía.}
{135}{}{No tengo ni idea. ¿Eso es vieja tecnología, no? Supongo que los
 Carroñeros pueden encontrar uno, pero yo no sabría por dónde empezar a buscar.
 Nadie los usa ya... ¿o sí?}
{136}{}{Son enormes. Como lagartos gigantes, pero de cuero. Garras enormes, dientes enormes y cuernos enormes. Además les encanta la carne humana. Y son rápidos, Dios mío, qué rápidos son. Menos mal que no me persiguieron a mí, sino estaría muerto.}
{137}{}{Gracias. Quizás fue un malentendido lo que ocurrió. No tengo muchas
 chapas, pero ahora son tuyas.}
{138}{}{Gracias. Oh Dios, eso está bien... No tengo muchas chapas, pero
 ahora son tuyas.}
{139}{}{Gracias. Quizás lo que ocurrió fue un malentendido. No tengo muchas
 chapas, pero... ¡qué diablos! Se me debieron caer. Ahora son tuyas.}
{140}{}{Gracias. Oh Dios, eso está bien... No tengo muchas chapas, pero... ¡qué diablos!
 Se me debieron caer. Ahora son tuyas.}
{141}{}{¡Ayúdame!}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{142}{}{El olor de la muerte, amigo mío. El olor de la muerte...}
{143}{}{El olor de la muerte, amiga mía. El olor de la muerte...}
