{100}{}{Estás viendo a un hombre con una armadura de cuero polvorienta, una gabardina y una máscara de gas.}
{101}{}{Estás viendo a Tycho.}
{102}{}{Otra cara nueva. Aquí das una patada y salen mil viajeros. Pero tú
 pareces distinto. ¿Te tomas un trago conmigo?}
{103}{}{Lo siento, no tengo mucho tiempo.}
{104}{}{Claro.}
{105}{}{¿Quá-ah?}
{106}{}{Maravilloso. Espero que no te importe que la bebida esté aguada... aquí
 riegan los barriles de cerveza como si fueran maceteros.}
{107}{}{¿Cuál es tu historia?}
{108}{}{Sí, un vaso de agua. Da igual.}
{109}{}{Yo te podría preguntar lo mismo. Por la amistad, yo hablaré primero.
 Me llamo Tycho. Vengo del este, de lo que solía ser Nevada.}
{110}{}{Es un viaje largo.}
{111}{}{¿Cómo sobreviviste a los peligros?}
{112}{}{En efecto. Por eso he decidido parar un poco. Este lugar promete,
 sólo hace falta que alguien limpie la basura.}
{113}{}{¿Por qué no tú?}
{114}{}{Sí, me he dado cuenta. ¿Qué sabes de esos idiotas?}
{115}{}{Se han entrenado mucho y tienen buenas armas. Mi abuelo
 era un Ranger entonces y le enseñó todo lo que sabía a mi padre. Papá
 hizo lo mismo conmigo. O sea que sé bastante como para no beber agua que reluce y esas cosas.}
{116}{}{Interesante. Gracias por el trago.}
{117}{}{¿En serio? Es duro sobrevivir en estos tiempos. Debes tener muchos conocimientos.}
{118}{}{No es mi sitio. Preferiría no cruzarme con Killian. Él limpiará esta
 ciudad cuando venga. Un buen hombre, fíjate lo que te digo. Pero ten cuidado
 con el amigo Gizmo. Me recuerda a otro bicho gordo del que me habló mi
 padre allá en Las Vegas.}
{119}{}{Gracias por el consejo, y por el trago.}
{120}{}{Aquí hay dos tipos de basura. Primero están los Kalaveras, un atajo que anda siempre en
 la parte trasera de la posada de Marcelles. Son escoria de segunda clase. Pero los otros
 responden ante el gordo asqueroso cuyo nombre ya habrás adivinado. Lleva el Casino.
 Esos tíos están organizados y son peligrosos.}
{121}{}{Ya veo. Gracias por la información.}
{122}{}{Sí, bueno, mi familia me enseñó todo lo que hay que saber sobre supervivencia.
 No bebas el agua que está completamente limpia y libre de insectos y moho, por ejemplo.
 Sólo el agua venenosa o radioactiva estaría tan limpia en un entorno salvaje.
 Muchas cositas que hay que mirar, ¿sabes?}
{123}{}{¿Como qué?}
{124}{}{Si tienes tiempo podemos repasar algunos consejos.}
{125}{}{Claro, sería estupendo.}
{126}{}{Lo siento, estoy justo de tiempo.}
{127}{}{Guau, no tan rápido. ¿Nunca terminamos de presentarnos, recuerdas? ¿Cómo
 te llamas, forastero?}
{128}{}{Soy }
{129}{}{.}
{130}{}{No es asunto tuyo, caraculo.}
{131}{}{Qué bien encontrarte. Pisa con cuidado, colega.}
{132}{}{Vaya, vaya, no hace falta ser maleducado. Con esa actitud será mejor
 que te vayas.}
{133}{}{Vete al cuerno.}
{134}{}{Lo que sea. Nos vemos.}
{135}{}{¿Qué quieres?}
{136}{}{Siento molestarte en tu tiempo de descanso. Vete por ahí.}
{137}{}{Necesito información sobre las bandas de por aquí.}
{138}{}{Necesito información sobre la ciudad.}
{139}{}{Hola otra vez. ¿En qué puedo ayudarte?}
{140}{}{Killian me ha pedido que limpie esta ciudad, y me gustaría contar con tu ayuda.}
{141}{}{Esto es el Fosa Común, un condenado hervidero de villanos y demás. Al
 oeste de aquí está lo de Gizmo, un gran Casino. Dicen que los juegos están amañados. Un poco al sur
 está la Posada de Marcelles, donde puedes conseguir un sueño reparador,
 pero resulta un poco caro. Pasado eso está lo de Killian. Killian tiene un establecimiento general, y
 se ocupa de la ley en la ciudad... un buen hombre. Al sur de eso tienes a
 Doc Mórbid, su forma de operar es un poco rara, no sé si me entiendes.}
{142}{}{Espero que mi pequeño curso introductorio te haya servido de ayuda.}
{143}{}{}
{144}{}{Cuentan por ahí que has estado en contacto con Gizmo. Yo andaría
 con mucho ojo con ese saco de manteca si fuera tú.}
{145}{}{No te metas en mis asuntos.}
{146}{}{Sí, trabajo para Gizmo ahora. ¿A ti que te importa?}
{147}{}{Está bien. Pero vigila tus espaldas. Gizmo no es famoso por ser considerado
 con sus empleados.}
{148}{}{Sobra decir que tu jefe ha provocado más sufrimiento y dolor del
 necesario en esta ciudad. No esperes mucha ayuda de nadie, sobre todo de Gizmo.
 Qué pena. Tú podrías haber cambiado esta ciudad para mejor.}
{149}{}{¿Qué puedo hacer por ti?}
{150}{}{¿Alguna recomendación?}
{151}{}{Gracias por tu ayuda. Creo que es hora de separarnos.}
{152}{}{Sí, yo me mantendría totalmente alejado de quien haya hecho eso.
 En serio, nunca he visto nada parecido. Creo que lo mejor que podemos hacer es seguir adelante, rápido.}
{153}{}{Muy bien. He de decir que ha sido un honor y un placer.}
{154}{}{Ten cuidado con las zonas radioactivas. Este lugar fue evidentemente el objeto de un ataque nuclear directo, y las secuelas radioactivas pueden ser muy malas. Yo procuraría evitar este sitio completamente.}
{155}{}{Como ves no hay ningún tipo de vida animal por aquí. Y observa las
 pilas de huesos. La criatura que viva aquí tiene que ser una mala bestia. Ten el arma a mano.}
{156}{}{Una plaza militar como esta debe tener una Sala de Mando central en algún sitio.}
{157}{}{Apuesto a que podemos atravesar esos generadores de campos de fuerza
 con una derivación o encontrando el ordenador que controla los campos.}
{158}{}{Hay muchas historias extrañas sobre Necrópolis, la ciudad de los muertos. Mantente
 alerta porque el peligro está por todas partes.}
{159}{}{Necesito cambiar la formación.}
{160}{}{¿A qué distancia quieres que me ponga?}
{161}{}{Quédate cerca.}
{162}{}{Guarda una distancia moderada.}
{163}{}{Mantén una distancia de largo alcance.}
{164}{}{¿Qué tipo de técnicas con las armas tienes?}
{165}{}{Tengo una buena formación de soldado: Puedo usar la lanza llegado el momento;
 también soy hábil con las pistolas pequeñas y los rifles.}
{166}{}{Uh, no importa.}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

{167}{}{Sí, si te gusta el lagarto muy hecho.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{Bueno, ya es hora. Continuemos, amigo mío, barramos las calles.
 Recomiendo acabar con Gizmo, si no te importa.}
{169}{}{Bueno, ya es hora. Continuemos, amiga mía, barramos las calles.
 Recomiendo acabar con Gizmo, si no te importa.}

{170}{}{¿Sí?}
{171}{}{Después de todo, quizás deberíamos seguir juntos.}
{172}{}{Nada. No importa.}
{173}{}{Ganas 300 puntos de experiencia por reclutar a Tycho, el ranger del desierto.}

#
# Tycho tell-me-abouts
#

{1000}{}{Ciudad Vertedero}
{1001}{}{Rangers}
{1002}{}{Chip}
{1003}{}{Guerra}
{1004}{}{Yermos}
{1005}{}{Seguidores}
{1006}{}{Catedral}
{1007}{}{Garl}
{1008}{}{Maestro}
{1009}{}{Unidad}
{1010}{}{Set}
{1011}{}{Almacén de Agua}
{1012}{}{Necrópolis}
{1013}{}{Sala}
{1014}{}{Biblioteca}
{1015}{}{Supervisor}
{1016}{}{Médico}
{1017}{}{Curación}
{1018}{}{Refugio}
{1019}{}{Refugio 13}
{1020}{}{Refugio13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Cementerio}
{1024}{}{Arenas}
{1025}{}{Sombrías}
{1026}{}{Eje}
{1027}{}{Casino}
{1028}{}{Establecimiento}
{1029}{}{Garras Mortales}
{1030}{}{Éxodo}
{1031}{}{Iniciados}
{1032}{}{Paladines}
{1033}{}{Escribas}
{1034}{}{Niños}
{1036}{}{Hermandad}
{1037}{}{Tanques}
{1038}{}{Militar}
{1039}{}{Base}
{1041}{}{Apocalipsis}
{1042}{}{Mutantes}
{1043}{}{Morfeo}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Bebida}
{1052}{}{Drogas}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Reguladores}
{1058}{}{Carroñeros}
{1059}{}{Navajas}
{1060}{}{Nicole}
{1061}{}{Teniente}
{1062}{}{Psíquicos}
{1063}{}{Experimentos}
{1064}{}{Policía}
{1065}{}{Mercaderes}

{1100}{}{Ciudad Vertedero no es un verdadero hogar, pero es una ciudad interesante. Tiene
 potencial, aunque no estoy seguro de que construir con las sobras del pasado
 sea la mejor manera de edificar el futuro.}
{1101}{}{Nosotros los Rangers venimos del este, lo que solía ser Nevada.
 Nuestra tradición se remonta a los gloriosos días de los Rangers de Texas. Aprendimos técnicas de supervivencia y de combate para tener la oportunidad de salir al
 mundo y mejorarlo.}
{1102}{}{Hace mucho tiempo que no veo una reliquia tecnológica como un Chip de
 agua. Yo que tú me fiaría más de tus propias manos que de una estúpida pieza de tecnología que ni siquiera puedes
 arreglar.}
{1103}{}{La Guerra fue el resultado de la locura y la avaricia humana. Espero
 que hayamos aprendido la lección y nunca se repita tal disparate.}
{1104}{}{Los yermos son hostiles y peligrosos, incluso para el viajero
 más intrépido. Las radiaciones y las extrañas criaturas causarán muchas muertes. Anda con
 cuidado y recuerda que todo lo que ves y todo lo que oyes puede ser una pista.}
{1105}{}{Lo siento, no puedo ayudarte.}
{1106}{}{Lo siento, no puedo ayudarte.}
{1107}{}{Lo siento, no puedo ayudarte.}
{1108}{}{Lo siento, no puedo ayudarte.}
{1109}{}{Lo siento, no puedo ayudarte.}
{1110}{}{Lo siento, no puedo ayudarte.}
{1111}{}{Lo siento, no puedo ayudarte.}
{1112}{}{La Ciudad de los Muertos se llama así con razón. Se ubica sobre lo que solía ser el pequeño
 pueblo de Bakersfield. Pero, ahora, es el hogar de Necrófagos y cosas aún peores.}
{1113}{}{Lo siento, no puedo ayudarte.}
{1114}{}{Lo siento, no puedo ayudarte.}
{1115}{}{Lo siento, no puedo ayudarte.}
{1116}{}{Lo siento, no puedo ayudarte.}
{1117}{}{Lo siento, no puedo ayudarte.}
{1118}{}{He oído hablar de los grandes Refugios subterráneos. Pero no sé mucho
 sobre ellos.}
{1119}{}{He oído hablar de los grandes Refugios subterráneos. Pero no sé mucho
 sobre ellos.}
{1120}{}{He oído hablar de los grandes Refugios subterráneos. Pero no sé mucho
 sobre ellos.}
{1121}{}{Killian es un hombre bueno con un trabajo difícil.}
{1122}{}{Gizmo es... a mí me repatea. Pero tendrá su merecido.}
{1123}{}{¿El Cementerio? He oído que es un lugar de bandas y vida dura
 cerca de la costa.}
{1124}{}{Lo siento, no puedo ayudarte.}
{1125}{}{Lo siento, no puedo ayudarte.}
{1126}{}{El Eje es una comunidad mercantil gigante, un poco al sur de Ciudad 
 Vertedero.}
{1127}{}{El Casino de Gizmo es uno de los últimos sitios donde yo iría,
 a no ser que fuese para clavarle un cuchillo. Suponiendo que pudiese atravesar la capa de grasa, claro.}
{1128}{}{Killian tiene un establecimiento general decente en Ciudad Vertedero.}
{1129}{}{He oído algunas historias sobre una criatura más rápida, más grande y más
 mala que otra cualquiera. Aunque no demasiadas, lo que significa que
 no dejan muchos supervivientes. Tienen grandes garras y son muy feroces.}
{1130}{}{Lo siento, no puedo ayudarte.}
{1131}{}{Lo siento, no puedo ayudarte.}
{1132}{}{Lo siento, no puedo ayudarte.}
{1133}{}{Lo siento, no puedo ayudarte.}
{1134}{}{Lo siento, no puedo ayudarte.}
{1136}{}{Lo siento, no puedo ayudarte.}
{1137}{}{Lo siento, no puedo ayudarte.}
{1138}{}{Los militares tenían varias bases militares desperdigadas por ahí.
 Pero no sé dónde.}
{1139}{}{Los militares tenían varias bases militares desperdigadas por ahí.
 Pero no sé dónde.}
{1141}{}{El Armaggedón nuclear fue el resultado de la soberbia y la estupidez. Ahora, pagamos
 el precio.}
{1142}{}{Desde luego hay bastantes cosas raras allí fuera. He visto escorpiones
 y vacas mutantes, y he oído que Necrópolis es el hogar de los Necrófagos, que parecen
 humanos, pero no lo son.}
{1143}{}{Lo siento, no puedo ayudarte.}
{1144}{}{Lo siento, no puedo ayudarte.}
{1145}{}{Lo siento, no puedo ayudarte.}
{1146}{}{Lo siento, no puedo ayudarte.}
{1147}{}{Lo siento, no puedo ayudarte.}
{1148}{}{Lo siento, no puedo ayudarte.}
{1149}{}{Lo siento, no puedo ayudarte.}
{1150}{}{Lo siento, no puedo ayudarte.}
{1151}{}{Yo prefiero un buen trago, o quizás una Nuka-Cola.}
{1152}{}{Yo en tu lugar me mantendría alejado de las drogas. Claro que te dan un subidón estupendo,
 pero al final siempre lo pagas caro.}
{1153}{}{Lo siento, no puedo ayudarte.}
{1154}{}{Lo siento, no puedo ayudarte.}
{1155}{}{Lo siento, no puedo ayudarte.}
{1156}{}{Lo siento, no puedo ayudarte.}
{1157}{}{Lo siento, no puedo ayudarte.}
{1158}{}{Lo siento, no puedo ayudarte.}
{1159}{}{Lo siento, no puedo ayudarte.}
{1160}{}{Lo siento, no puedo ayudarte.}
{1161}{}{Lo siento, no puedo ayudarte.}
{1162}{}{¿Estás hablando de telepatía? Eh... en serio, no me lo trago.}
{1163}{}{Lo siento, no puedo ayudarte.}
{1164}{}{Lo siento, no puedo ayudarte.}
{1165}{}{Algunos mercaderes del Eje visitan Ciudad Vertedero y otras ciudades
 regularmente.}
