{100}{}{Estás viendo ante ti a Uthern, el líder de los Supermutantes.}
{101}{}{¡Normi! ¿Cómo te atreves a entrar en los confines de tus mejores?}
{102}{}{¿Uh?}
{103}{}{¡Escoria como vosotros nunca podría ser mejor que los humanos!}
{104}{}{¡¡Muere Muti!!}
{105}{}{¿De veras? Dices ser mejor, pero, ¿qué pruebas tienes?}
{106}{}{Si tú te consideras mejor que el resto, caerás en la falacia de generalizar.}
{107}{}{Es un milagro que tu raza haya sobrevivido tanto tiempo. Empezaré contigo para su limpieza.}
{108}{}{Solamente demuestras mi punto de vista al usar tales comentarios. Personalmente, ojalá no te estuviera viendo,
 aunque mi maestro querrá charlar contigo.}
{109}{}{Muéstrame a tu maestro.}
{110}{}{Prueba con estas palabras... ¡Cáete muerto!}
{111}{}{Seguramente uno de tu inteligencia podrá ver que esas cosas no resuelven nada.}
{112}{}{Será un placer.}
{113}{}{¿Estás diciendo que hablar no solucionará nada? Eres más tonto de lo que pensaba.}
{114}{}{Aunque seas un tonto, me estaba refiriendo a tu forma de decir las cosas.}
{115}{}{Ah, el tonto por fin se da cuenta de algo.}
{116}{}{Las palabras solo harán algo. Esto solucionará más.}
{117}{}{Empiezo a creer que todavía podrías tener algo de sangre superior en ti. Déjame averiguar si es cierto.}
{118}{}{Efectivamente lo hará, ya que la muerte será la gracia que te salvará.}
{119}{}{Es la prueba más sencilla. Yo soy más listo, más fuerte y más rápido que tu. ¿Te importaría
 probar mis habilidades?}
{120}{}{No, gracias. Te creo.}
{121}{}{Te olvidaste de arrogante, estúpido y feo.}
{122}{}{Claro. Vamos a ver que puedes hacer.}
{123}{}{Bien. ¿Te gustaría tener una oportunidad de obtener grandes poderes?}
{124}{}{¡Apuesta algo!}
{125}{}{¡Ni de lejos!}
{126}{}{Eso no lo tengo claro.}
{127}{}{¡Muere!}
{128}{}{Entonces te llevaré con mi maestro.}
{129}{}{Hasta casi me da pena. No importa, no llevará mucho tiempo.}
{130}{}{Le ofreces todo el poder del mundo y todavía está asustado. Te ayudaré con tu decisión.}
{131}{}{Comentarios como ese solo demuestran que soy más inteligente que tu. Ahora, ¡pagarás por esa insolencia!}
{132}{}{¿Aceptas tarjetas de crédito, o solo chapas?}
{133}{}{¡¡Nunca!!}
{134}{}{Lo siento, ahora mismo ando algo falto de chapas. ¿Puedo dejarlo para otro momento?}
{135}{}{¿Qué? Creo que no llego a tanto... ahora vas a venir conmigo.}
{136}{}{Me alegro de volverte a ver. Me dijeron que andabas por aquí. Tengo órdenes de dejarte entrar.}