{100}{}{Podrías sacar más información de esta terminal con un método
 más científico.}
{101}{}{Esta terminal regula las funciones y suministros del Refugio y realiza
 trabajos rutinarios de administración.}
{102}{}{Los terminales de este nivel se encargan del control de la temperatura y la atmósfera. También refuerzan el mantenimiento del laboratorio médico.}
