{100}{}{Ves a un ciudadano del Refugio 13.}
{101}{}{No creímos que fueras a volver. Tienes
 una habitación tan bonita y nosotros estamos tan apretados con
 sus padres... Espero que no te importe.}
{102}{}{Claro que me importa. ¡Sal de mi habitación!}
{103}{}{Noo, no me importa. Disfrutad de la habitación.}
{104}{}{Sería tranquilizador recuperar mis propios aposentos.
 Por favor, encuentra otro lugar donde vivir.}
{105}{}{Hng.}
{106}{}{Mira, no quiero discutir contigo, pero es obvio
 que no merecéis quedaros en esta habitación. Por favor, marcharos.}
{107}{}{Mira, podríamos aprovechar el espacio. Piénsatelo.}
{108}{}{Bueno, dejame pensar un rato.
 Mmm... No. ¡Fuera!}
{109}{}{Bien, de acuerdo. Vosotros la necesitáis más que yo.}
{110}{}{¡Gracias! Te lo agradecemos mucho. Pondremos todas tus cosas en la maleta.}
{111}{}{Bueno, no sé. No parece que la uses muy a menudo
 y nosotros podríamos aprovechar el espacio.}
{112}{}{Vale. Es vuestra.}
{113}{}{Necesito este lugar para recordar mis raíces. Y además,
 es un buen sitio para descansar.}
{114}{}{Caramba, no creí que todavía te preocupara este lugar después de
 lo que he oído. Es tu día de suerte. Volvemos con mamá.}
{115}{}{Nos gusta mucho.}
{116}{}{Debes irte. Esta ya no es tu habitación.}
