{100}{}{Ves a un Miembro de los Niños de la Catedral.}
{101}{}{Yo no hablo con almas paganas como la tuya.}
{102}{}{Tu informe, Van Hagan.}
{103}{}{El Maestro está contento con tus progresos, pero
 su necesidad es grande y el tiempo limitado.}
{104}{}{El Maestro debería saber que la materia prima es limitada.
 No podemos crear nuestros soldados sin más suministros.}
{105}{}{Está al tanto de nuestros problemas. Mientras hablamos, él trabaja
 sobre ello.}
{106}{}{Háblame de sus planes. Tendremos que coordinar
 actividades, si queremos que la Unidad tenga éxito.}
{107}{}{El Maestro se ha enterado de la existencia de un refugio con vida
 no descubierto todavía. Con toda esa materia prima, podemos
 crear una gran fuerza. Según el programa de predicción, es precisamente lo que necesitamos para ganar.}
{108}{}{Excelente. Esto es más que fortuito. ¿Están contaminados
 los habitantes?}
{109}{}{Oh, ésa es la mejor parte. Si su representante sirve
 de ejemplo, están limpios. Son puros.}
{110}{}{Oh, ¡qué emocionante! ¿Cuál de los Refugios hemos
 saqueado?}
{111}{}{Refugio 13. Y pronto los tendremos. Muy pronto.}
{112}{}{Ganas 1.000 puntos de experiencia por oír por casualidad toda la conversación
 sobre tu Refugio.}
