{100}{}{Estás viendo a Víctor.}
{101}{}{Estás viendo al miembro de una banda.}
{102}{}{Aaaaggghhh...}
{103}{}{Sangre nueva. Je, je, je...}
{104}{}{Um, sí. Uh, creo que me voy.}
{105}{}{No eres una persona feliz, ¿verdad?}
{106}{}{¡Huh huh!}
{107}{}{En realidad no. Creo que te mantendré por aquí un rato.}
{108}{}{¿Por qué dices eso? Estoy bastante feliz. Estoy muy feliz por la cantidad de sangre que veo.}
{109}{}{Eres un psicópata, ¿lo sabías?}
{110}{}{Um, sí. Adiós.}
{111}{}{Ah, sí, buena apreciación. Eh, puedo entenderlo. Bueno, por lo menos lo creo.}
{112}{}{¡No digas eso! ¡Me lo decía mi madre! ¡Lo pagarás! Soy un chico bueno,
 ¿verdad, mami?}
{113}{}{¡Alguien que me comprende! ¡Por fin!}
{114}{}{Hola otra vez, amigo artista.}
{115}{}{¡Ja, ja! ¡Je, je, je! ¡Oh, oh, oh!}
{116}{}{Zzzzz...}
{117}{}{Víctor, ¿te he dicho alguna vez que eres un verdadero psicópata?}
{118}{}{Oh, hola.}