#  TRANSLATION NOTES
# Vinnie is a gang leader, who is young and ruthless. He tries to sound tough
# and is quite mean. He only respects people who are as ruthless and violent as
# himself.

{100}{}{Ves a Vinnie, de la banda de los Kalaveras.}
{101}{}{Ves a un hombre joven con un tatuaje y aspecto de malo.}
{102}{}{Me gustaría unirme a vosotros, muchachos.}
{103}{}{Estás en territorio de los Kalaveras, forastero. Será mejor que hables rápido.}
{104}{}{Lo siento, te equivocas de habitación.}
{105}{}{¿Los Kalaveras? ¿Quiénes sois, muchachos?}
{106}{}{¿Urgh?}
{107}{}{¡No sabes hasta que punto te has equivocado de sitio!}
{108}{}{Somos la única banda de Ciudad Vertedero. Tenemos el control de las calles,
 y gobernamos en la ciudad por la noche.}
{109}{}{Oh. Lo siento. Adiós.}
{110}{}{No pudiste controlar el patio del colegio, Cromo.}
{111}{}{Creía que esta ciudad la dirigía Gizmo fuera de horas.}
{112}{}{¡Largo de aquí, imbécil!}
{113}{}{Ese patán ni siquiera puede mantenerse en pie. Somos los musculitos de la ciudad.
 Tenemos lo que queremos.}
{114}{}{Ya veo.}
{115}{}{¿Tienes algún tipo de trato con Killian?}
{116}{}{¡¿Qué?! ¡Me las pagarás por ese comentario!}
{117}{}{Nosotros no molestamos a Killian y él no nos molesta a nosotros mientras lo tengamos
 pillado. ¿Lo coges?}
{118}{}{Sí. Adiós.}
{119}{}{Sí, lo cojo. Tenéis que esconderos de él.}
{120}{}{¡A nadie y menos a Killian! ¡Sólo porque
 piense que es un Sheriff glorioso no significa que controle a los Kalaveras!}
{121}{}{Lo siento, no quería ofenderos.}
{122}{}{Así que te corta las alas, ¿eh? A mí también. De hecho estoy pensando
 darle una paliza. ¿Estás conmigo?}
{123}{}{¿Quieres dar una paliza a Killian? Tío, estás loco. Macho, no sé...
 vale, lo haré.}
{124}{}{Eres un perdedor, dijiste que íbamos a darle una paliza a Killian. Largo de aquí.}
{125}{}{Venga, destrocemos a Killian.}
{126}{}{¿Y ahora qué quieres?}
{127}{}{Nada, lo siento.}
{128}{}{Busco a alguien que me ayude a deshacerme de Killian. Los Kalaveras me parecieron
 una buena elección.}
{129}{}{¡Mierda, no creí que fueras a hacerlo! ¡Los Kalaveras dirigen ahora esta ciudad! ¡Guau!}
{130}{}{Ya hemos pasado por esto. Tú no tienes cojones, así que
 ¡largo de aquí!}
{131}{}{¿O sea que quieres unirte a nosotros? ¿Cómo sabemos que eres lo bastante duro como para ser uno de los
 Kalaveras?}
{132}{}{¡Yo te enseñaré lo que es ser duro, hijo de puta!}
{133}{}{Deja que os lo demuestre.}
{134}{}{Confía en mía, soy lo bastante fuerte.}
{135}{}{[Vinnie te mira y se ríe.] No lo creo.}
{136}{}{Te lo demostraré.}
{137}{}{Ya está. Te ha llegado la hora de morir.}
{138}{}{Tienes razón, ya me iba.}
{139}{}{¿Qué hace tan duros a los Kalaveras?}
{140}{}{[Vinnie piensa un momento.] Si quieres demostrarnos que eres bastante bueno para ser de los Kalaveras,
 tienes que robar las cenizas de la mujer de ese viejo bastardo. Je. [Vinnie habla entre dientes.]
 Hagamos que Neal sufra en sus dos últimas horas de vida...}
{141}{}{Vale, lo haré.}
{142}{}{Ni hablar.}
{143}{}{Oh, creo que no podría hacer eso.}
{144}{}{Ya las he robado.}
{145}{}{Eso no sería tan duro como crees. Ya he matado a ese bastardo.}
{146}{}{Si eres lo bastante fuerte como para hacer eso, puede que después de todo seas uno de los Kalaveras.
 Trae lo que tengas.}
{147}{}{Sabía que no podrías ser de los Kalaveras. Lárgate ahora mismo de aquí.}
{148}{}{¿Lo tienes?}
{149}{}{Sí.}
{150}{}{No.}
{151}{}{Tuve que matar a Neal para conseguirlas. Lloró como una niña pequeña.}
{152}{}{¡Ja, ja! ¡Hagamos sufrir al viejo hasta que lo liquidemos esta noche. ¿Te apuntas?}
{153}{}{He pensado que no quiero tener nada que ver con canallas como vosotros.}
{154}{}{Venga, vamos a aplastarlo.}
{155}{}{Tengo que hacer algo antes. Te veré allí.}
{156}{}{¿Por qué me haces perder el tiempo?}
{157}{}{Eso enseñará a este jodido viejo. Gracias por ocuparte de él.
 [A Vinnie se le saltan las lágrimas.] Ahora eres de los Kalaveras.}
{158}{}{Eh, de acuerdo... reúnete con nosotros más tarde, pero no tardes mucho.}
{159}{}{Pronto, Neal tendrá lo que se merece, ¿verdad?}
{160}{}{¡Dijimos que volveríamos, viejo mamón!}
{161}{}{Ha llegado un montón de gente al bar...}
{162}{}{¡Que te follen, guindilla!}
{163}{}{Ganas 400 puntos de experiencia por robar la urna de Neal. La muerta nunca
 descansará en paz.}
{164}{}{Ganas 300 puntos de experiencia por meterle una chapa por el culo a Neal, de los Kalaveras.}
{165}{}{¿Listo para encargarte de Neal?}
{166}{}{Sí, vamos a cargarnos a ese bastardo.}
{167}{}{Noo, tengo otras cosas que hacer.}
{168}{}{Ni hablar. No quiero seguir.}
{169}{}{Es demasiado tarde para eso, cobarde. Si estás fuera, estás fuera.}
{170}{}{Nosotros dirigimos esta ciudad.}
{171}{}{¡Eh, colega, nosotros controlamos esta ciudad!}