{100}{}{Estás viendo a Vree.}
{101}{Vree00}{Perdona, estás interrumpiendo mi meditación. Por favor, vete.}
{102}{}{Lo siento. Volveré en otro momento.}
{103}{}{Volveré.}
{104}{}{¿Cómo iba a saber tu agenda?}
{105}{}{¿Ehhh?}
{106}{Vree01}{No me levantes la voz. ¿Tendré que llamar a un Hermano para que te enseñe modales?}
{107}{}{Perdona.}
{108}{}{Sí, vale. Lo que sea.}
{109}{}{Oh, ¡qué miedo!}
{110}{Vree02}{Saludos. Es un buen día para aprender. ¿Puedo ayudarte?}
{111}{}{Sé que eres la Maestro Escriba, ¿pero qué significa?}
{112}{}{Necesito información técnica.}
{113}{}{Eh...}
{114}{Vree03}{Registro los conocimientos de nuestros ancestros para las generaciones futuras.}
{115}{}{Interesante. Eso significa que sabes muchas cosas.}
{116}{Vree03a}{Sí, supongo que se puede decir que sé "cosas".}
{117}{Vree17}{¿En qué puedo ayudarte?}
{118}{Vree17a}{Adelante.}
{119}{}{Necesito reparar un Chip de agua. ¿Puedes ayudarme?}
{120}{}{Me gustaría saber más sobre las armas que se hacen aquí.}
{121}{}{He oído algo sobre los holodiscos, ¿cómo se leen?}
{122}{}{¿Cómo puede prevenirse el envenenamiento radiactivo?}
{123}{}{¿Qué está provocando todas las mutaciones?}
{124}{Vree18}{Habla con los Caballeros. Diles que te enseñen una
 de la últimas pistolas láser que he diseñado.}
{125}{}{¡Gracias!}
{126}{}{Tengo otra pregunta...}
{127}{Vree19}{Todavía no eres capaz de usar apropiadamente los conocimientos sagrados.}
{128}{Vree21}{Usa tu PIPBoy 2000 para leer los discos. Introduce el disco en el
 lector. Si tienes los conocimientos informáticos adecuados, deberías ser
 capaz de descargar los datos.}
{129}{}{¿Dónde puedo aprender los conocimientos informáticos?}
{130}{}{Gracias.}
{131}{}{¿Puedo hacerte otra pregunta?}
{132}{Vree22}{La Hermandad tiene unos cursos automatizados que podrías seguir.
 Ven, te lo enseñaré.}
{133}{Vree23}{Usa esta terminal para aprender lo básico sobre las operaciones del ordenador.}
{134}{Vree24}{¿No eres muy listo, verdad? Llevas un reproductor de
 holodiscos en el brazo.}
{135}{Vree25}{Necesitarás algunas drogas anti-radiación. Toma éstas.
 Tómatelas en cuanto pienses estar cerca de las radiaciones.}
{136}{}{¡Gracias!}
{137}{}{¿Puedo preguntarte algo más?}
{138}{Vree26}{No bebas el agua que reluce.}
{139}{Vree27}{Con todas las armas nucleares y biogenéticas usadas durante la Guerra, lo
 sorprendente es que no haya más mutaciones. De todas formas, si
 conseguimos resistir, todo irá bien.}
{140}{}{¿Por qué dices eso?}
{141}{}{Tienes razón. Estaremos bien.}
{142}{}{Tengo otra pregunta...}
{143}{Vree28}{Todos los mutantes que he estudiado han resultado ser estériles: no pueden procrear con
 otra criatura. Si pudiésemos acabar con la fuente de mutantes, seríamos
 capaces de hacer, sencillamente, que se extinguiesen.}
{144}{}{Suena como un plan.}
{145}{}{Interesante teoría. ¿Alguna prueba?}
{146}{}{Tengo otra pregunta...}
{147}{Vree29}{Toma, ten este holodisco, contiene copias de mis autopsias de cadáveres
 mutantes. Muestra claramente que ningún mutante podría reproducirse con éxito.}
{148}{}{Gracias.}
{149}{}{¿Puedo preguntar otra cosa?}
{150}{Vree30}{No creo que deba contarte nada. Quizás más adelante,
 cuando te hayas entregado a la causa de la Hermandad. }
{151}{Vree31}{Estoy segura de que te encuentras en el lugar equivocado. Vete, por favor. Estoy
 ocupada.}
{152}{Vree32}{¡Destruirás la sabiduría que puede salvar al mundo!}
{153}{}{Sí, empezando por ti.}
{154}{}{No. Estoy deteniendo a quienes podrían provocar otra guerra nuclear.}
{155}{Vree33}{¡Nunca! ¡La Hermandad verá que no sucede de nuevo!}
{156}{}{Eso es lo que dicen todos... excepto tú. Tú estarás muerta.}
{157}{Vree34}{¿En qué te puedo ayudar?}
{158}{}{Tengo noticias importantes que comunicarte en cuanto a Kedrick. Es un traidor.}
{159}{}{Qué harías si hubiese corrupción dentro de la Hermandad.}
{160}{}{¡Nahh! ¡Nah-ah-nah!}
{161}{Vree35}{Muy bien. Se nota que las lecciones te han ayudado.}
{162}{Vree36}{¿Kedrick? Siempre ha sido un miembro leal a la Hermandad. Dudo
 que sepas lo que significa.}
{163}{}{Sí, lo sé. Kedrick es un traidor y está planeando matar a
 vuestros líderes.}
{164}{}{Puede que sí.}
{165}{Vree37}{¿Estás seguro? Quizás deberíamos hablar con el Anciano Mayor.}
{166}{Vree38}{No me molestes con tonterías. Tráele pruebas al Anciano Mayor, o no
 mientas.}
{167}{Vree39}{Haz lo que debas. Limpia la herejía y elimina a los responsables
 de la mancha.}
{168}{}{Aunque fuera un miembro de la Hermandad digno de confianza.}
{169}{}{¿Y quien llevaría a cabo la eliminación?}
{170}{Vree40}{Aun así. Pero tendrías que demostrarlo.}
{171}{}{Kedrick es un traidor. Está planeando asesinar a los Ancianos.}
{172}{}{Conseguiré las pruebas.}
{173}{Vree41}{Entonces debemos ir ante el Anciano Mayor. Trae tu evidencia y hablaremos
 con él.}
{174}{Vree42}{El Anciano Mayor y Rhombus, desde luego.}
{175}{Vree43}{¿Has oído hablar del Iniciado desaparecido? ¡Es terrible!}
{176}{}{Estoy de acuerdo.}
{177}{}{Nah-ah.}
{178}{Vree44}{Si puedes ayudarle, estaré muy agradecida.}
{179}{Vree45}{Las buenas acciones deben ser recompensadas. Toma esto por haber ayudado al Iniciado,
 por favor.}
{180}{Vree46}{Oh, eres tú. ¿Qué quieres?}
{181}{}{He venido para disculparme.}
{182}{}{Lo siento, habitación equivocada.}
{183}{Vree47}{Gracias por tus disculpas. }
{184}{Vree47a}{Buen día.}
{185}{Vree48}{Eso parece un problema de fabricación. Nosotros sólo manejamos la teoría y el
 diseño. Pídele ayuda a uno de los Caballeros.}
{186}{}{Gracias de todas maneras.}
{187}{}{¿Puedo preguntarte otra cosa?}
{188}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{189}{Vree201}{No sé nada de eso. Pero parece que debería
 investigarlo.}
{190}{Vree202}{Lo siento, no es una de mis especialidades. Quizás lo sepa algún otro Hermano.}
{191}{Vree203}{¡Guardias! ¡Guardias!}
{192}{Vree204}{¡Has destruido mi habitación!}
{193}{Vree205}{¿Qué crees que estás haciendo con mis cosas?}
{194}{Vree300)}{¿Quién? Espera, ese nombre me parece familiar. Quizás sea el líder
 de un grupo de mutantes.}
{195}{Vree301}{Supongo que te refieres a la última guerra nuclear. La Hermandad hace todo lo que
 puede para restaurar lo que se perdió.}
{196}{Vree302}{Son dispositivos de almacenaje fabricados en cristal, de alta densidad y que se leen con láser.
 Cada uno contiene 4.000 gigabytes de información.}
{197}{Vree303}{La única salvación para este torturado planeta y sus gentes.
 Sin nosotros, la humanidad desaparecerá.}
{198}{Vree304}{No lo sé. Pregunta en Fabricación sobre ello.}
{199}{Vree305}{Se asegura que la Hermandad permanece en el buen camino.}
{200}{Vree306}{Él hace que se cumplan los deseos del Anciano Mayor. Usando la fuerza, si es necesario.}
{300}{}{Interesante.}
{301}{}{Bien, con esto bastará.}
{302}{}{Esto lo arreglará.}
{303}{}{Bien.}
{304}{}{Sabía que funcionaría.}
{305}{}{¿Me puedes repetir la fórmula?}
{306}{}{El algoritmo está mal, no puede ser. El ordenador debe tener un problema.}
{307}{}{Aquí estamos.}
{308}{}{Sí hacemos así... sí, creo que funcionará.}
{400}{}{Puedes usar este terminal para mejorar tu habilidad con ordenadores.}
{401}{}{La clase termina seis horas después. Ha sido agotadora.}



{980}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}


#
# Vree Tell-Me-Abouts
#


{1000}{}{Maestro}
{1001}{}{Guerra}
{1002}{}{Discos}
{1003}{}{Hermandad}
{1004}{}{Chip}
{1005}{}{Anciano}
{1006}{}{Rhombus}
{1007}{}{Éxodo}
{1008}{}{Extraño Ejército}
{1009}{}{Mercaderes}
{1010}{}{Caravanas desaparecidas}
{1011}{}{Eje}
{1012}{}{Niños de la Catedral}
{1013}{}{Iniciados}
{1014}{}{Escribas}
{1015}{}{Caballeros}
{1016}{}{Paladines}
{1017}{}{Holo}

{1100}{Vree300}{¿Quién? Espera, ese nombre me parece familiar. Quizás sea el líder
 de un grupo de mutantes.}
{1101}{Vree301}{Supongo que te refieres a la última guerra nuclear. La Hermandad hace todo lo que
 puede para restaurar lo que se perdió.}
{1102}{Vree302}{Son dispositivos de almacenaje fabricados en cristal, de alta densidad y que se leen con láser.
 Cada uno contiene 4.000 gigabytes de información.}
{1103}{Vree303}{La única salvación para este torturado planeta y sus gentes.
 Sin nosotros, la humanidad desaparecerá.}
{1104}{Vree304}{No lo sé. Pregunta en Fabricación sobre ello.}
{1105}{Vree305}{Asegura que la Hermandad permanezca en el buen camino.}
{1106}{Vree306}{Él hace que se cumplan los deseos del Anciano Mayor. Usando la fuerza, si es necesario.}
{1107}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1108}{Vree201}{No sé nada sobre eso. Pero suena como algo que quizás debería
 investigar.}
{1109}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1110}{Vree201}{No sé nada de eso. Pero suena como algo que quizás debería
 investigar.}
{1111}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1112}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1113}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1114}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1115}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1116}{Vree200}{Por favor, habla con otro de los Escribas. Estoy intentando terminar unos informes
 para los otros Ancianos.}
{1117}{Vree302}{Son dispositivos de almacenaje fabricados en cristal, de alta densidad y que se leen con láser.
 Cada uno contiene 4.000 gigabytes de información.}

