{100}{}{Estás viendo a un conductor de caravanas.}
{101}{}{Hola, si buscas trabajo en una de nuestras caravanas, debes hablar con la Maestra Mercader. Está en aquel edificio del este.}
{102}{}{Lo siento, pero tienes que hablar con la Maestra Mercader.}
{103}{}{Bien, tienes el visto bueno. Sabía que no iba a ser un problema. Últimamente está muy agobiada, sobre todo
 desde que Daren Hightower empezó a ocultarse en su oficina. Un tipo extraño. Nos vamos cada cinco días, es decir
 los días 1, 5, 10, 15, 20, y 25. Ahora sólo vamos a Ciudad Vertedero y al Cementerio de Angel.}
{104}{}{¿Y cuál es el sueldo?}
{105}{}{Um.}
{106}{}{El sueldo es de 200 chapas. No es tanto, salimos a menudo y nuestras rutas no son demasiado peligrosas,
 y sí, es sólo para la ida pero no estás obligado a hacer el viaje de ida y vuelta. }
{107}{}{Nos vamos hoy. ¿Te interesa?}
{108}{}{Nos vamos en }
{109}{}{Vacío}
{110}{}{}
{111}{}{. ¿Te interesa?}
{112}{}{Todavia estoy dispuesto a darte trabajo, aunque... no importa. ¿Te interesa?}
{113}{}{Claro.}
{114}{}{No.}
{115}{}{Quizás.}
{116}{}{Yaya.}
{117}{}{¿A?}
{118}{}{Oh, vale. No hay problema. Házmelo saber si cambias de opinión.}
{119}{}{A ver si tomas una decisión.}
{120}{}{Bien, vuelve si decides trabajar para nosotros. Recuerda, los días 1, 5, etc. Adiós.}
{121}{}{Lo siento, pero no puedo contratarte a menos que puedas comunicarte de forma clara con el resto de los empleados.}
{122}{}{Por favor, vuelve cuando te sientas mejor.}
{123}{}{Eh, ¿estás bien? Creo que necesitas algo de comer, pero no vayas al establecimiento de Bob.}
{124}{}{¡Te he dicho que te largues!}
{125}{}{Estoy muy decepcionado... ¡Tú robando! ¿Me vas a decir por qué lo hiciste?}
{126}{}{Porque soy una cosa verde del espacio exterior, ¡y soy... malo!}
{127}{}{No quería hacerlo, pero estoy hambriento y tengo hijos que alimentar.}
{128}{}{¡Te sacaré el corazón con una cuchara!}
{129}{}{[Te rindes]}
{130}{}{[Atacas]}
{131}{}{Intenté ayudarte, pero supongo que es demasiado tarde para algunos. Siento decir esto, pero tendremos
 que resolverlo de forma violenta.}
{132}{}{Lo entiendo, pero eso no es un motivo. Todavía te tengo que pedir que te vayas. No podemos
 contratar a gente que no puede controlarse.}
{133}{}{¿De veras esperas que caiga en esa mierda? ¡Guardias!}
{134}{}{Lo siento, pero a veces una temporada en una celda puede sanar a una persona. ¡Guardias! Intentad "no" matarla.
 ¿Te rendirás a mis guardias?}
{135}{}{¡Te veré en el infierno!}
{136}{}{Sí. Lo siento.}
{137}{}{¿Qué? ¿Te vas a meter en otra pelea?}
{138}{}{¡Lo siento pero debes irte inmediatamente o me veré forzada a llamar a la policía!}
{139}{}{¡Guardias! ¡Policía!}
{140}{}{Creo que deberías irte...}
{141}{}{Lo siento, pero no puedo contratarte.}
{142}{}{Por favor, me lo estás poniendo muy difícil.}
{143}{}{Por favor, vete.}
{144}{}{Intrigante, pero no eres mi tipo.}
{145}{}{¡Excepcional! La paga será de 200 chapas. ¿Qué ruta prefieres?}
{146}{}{Maravilloso. Por favor, pásate por aquí... [Mira su calendario] en }
{147}{}{día 1}
{148}{}{día 5}
{149}{}{día 10}
{150}{}{día 15}
{151}{}{día 20}
{152}{}{día 25}
{153}{}{. Entonces saldrás. La paga será como siempre de 200 chapas.}
{154}{}{Vale.}
{155}{}{Lo siento, no puedo esperar.}
{156}{}{Es una tragedia. Perdimos la caravana completa, ¿pero tú sobreviviste? Eso no debería haber pasado.
 No sé qué pasó ahí fuera, pero no podemos contratarte más. Lo siento.}
{157}{}{Ciudad Vertedero.}
{158}{}{Cementerio de los Ángeles.}
{159}{}{Emm, ahora no. Quizá en otra ocasión.}
{160}{}{Excelente, llamaré al resto del equipo.}
{161}{}{Estupendo.}
{162}{}{¡Adiós! ¡Buena suerte!}
{163}{}{Intenta evitar los problemas, no los vayas buscando.}
{164}{}{Ten cuidado, no me gusta el aspecto del Cementerio. Es horripilante.}
{165}{}{Está bien. Esos pasadizos oscuros son muy extraños, pero es fantástico viajar por ellos.}
{166}{}{Creo que ahí abajo hay algunas bandas. Yo que tu no hablaba con cualquiera.}
{167}{}{Genial. Ciudad Vertedero es un lugar decente.}
{168}{}{Oh, decir "hola" a ese... asesi.. ¿otra vez? He olvidado su nombre pero es un tipo decente. Me pregunto cómo
 le va.}
{169}{}{Un lugar interesante. Me han dicho que allí hay un doctor perverso que reanima a los muertos o algo así.}
{170}{}{¿Por qué diablos abandonaste la última caravana? No ocurrió nada terrible, pero algo pudo
 pasar.}
{171}{}{¿Puedo tener otra oportunidad?}
{172}{}{Nada.}
{173}{}{¡No apuesto una mierda!}
{174}{}{¿Ig wa neeka rooola?}
{175}{}{Lig.}
{176}{}{Lo siento, me has vuelto a fallar. No pareces ser muy responsable, y esa no es una buena
 combinación para nuestro perfil de empleado.}
{177}{}{¿Por qué?}
{178}{}{No debes.}
{179}{}{Porque si no, te voy a hacer un agujero en la cabeza.}
{180}{}{Tenía cosas mejores que hacer que esperar a una aburrida caravana.}
{181}{}{No sabía que no me estuviera permitido irme. Todo parecía en orden.}
{182}{}{Ya veo... estabas con el mono. Pues, lleva ese tipo de vida si quieres.}
{183}{}{Siento que lo veas así.}
{184}{}{Me sorprende que no hayas ido en un caravana antes, pero supongo que no tiene nada de malo... claro.
 Te daré otra oportunidad.}
{185}{}{¡Hiciste un buen trabajo! ¿Quieres otra caravana?}
{186}{}{Claro.}
{187}{}{No.}
{188}{}{Quizás.}
{189}{}{¡Eeek!}
{190}{}{Lub.}
{191}{}{¿Listo? Nos vamos hoy.}
{192}{}{Sí.}
{193}{}{¡No!}
{194}{}{¡Ack!}
{195}{}{Si no se lo daré a otro, no te preocupes. No estás obligado...
 hasta que salgas con la caravana, ¿de acuerdo?}
{196}{}{Vienes algo pronto. La próxima caravana no sale hasta }
{197}{}{día 1}
{198}{}{día 5}
{199}{}{día 10}
{200}{}{día 15}
{201}{}{día 20}
{202}{}{día 25}
{203}{}{. Vuelve entonces si todavía te interesa el trabajo. }
{204}{}{Enero, }
{205}{}{Febrero, }
{206}{}{Marzo, }
{207}{}{Abril, }
{208}{}{Mayo, }
{209}{}{Junio, }
{210}{}{Julio, }
{211}{}{Agosto, }
{212}{}{Septiembre, }
{213}{}{Octubre, }
{214}{}{Noviembre, }
{215}{}{Diciembre, }