{100}{}{Estás viendo al guardián del agua.}
{101}{}{Hola, }
{102}{}{.}
{103}{}{Hola. ¿Cómo te va?}
{104}{}{¡Gahh!}
{105}{}{¡Bien Gahh! Sigo contigo... siento que nunca aprendieras a
 hablar. Podríamos haber sido buenos amigos.}
{106}{}{Ouph.}
{107}{}{No me siento muy bien. Alguien me golpeó la cabeza
 con un enorme palo. Fui al médico pero todavía me duele la cabeza.
 Espero que alguien coja al cabrón que me golpeó.}
{108}{}{¿Por qué lo han hecho?}
{109}{}{Guck.}
{110}{}{Pues me atacaron una noche que estuve aquí hasta muy tarde. Normalmente me
 voy a casa a las ocho o así, pero aquella noche me quedé hasta tarde porque alguien había robado agua
 y tenía que comprobar las existencias. Lo siguiente que recuerdo es que me desperté en el laboratorio con
 un gran chichón en la cabeza. Las cosas se están yendo de las manos por aquí.
 Pronto alguien va a morir por un poco de agua y no sé
 qué podemos hacer.}
{111}{}{Sé lo que podemos hacer.}
{112}{}{Lo siento. Espero que te sientas mejor pronto.}
{113}{}{Aquí está tu agua.}
{114}{}{Esta es tu ración para hoy.}
{115}{}{¡Ey! ¿¡Qué crees que estás haciendo!?}
{116}{}{Por favor, no te lleves las reservas. Necesitamos el agua.}
{117}{}{Apuntaste tus informes en el ordenador de la biblioteca. Deberías
 volver con el Supervisor para finalizar tus progresos.}
# TRANSLATION NOTE
# The player-character's name is inserted by code between lines 118 and 119.
{118}{}{Buenos días, }
{119}{}{.}
{120}{}{Hola. ¿Cómo han ido las cosas últimamente?}
{121}{}{Dime, ¿qué estás haciendo aquí?}
{122}{}{Todo el mundo está muy nervioso, claro, pero no hemos tenido demasiados
 problemas. Espero que encuentres pronto un chip nuevo.}
{123}{}{Reparto las raciones de agua, claro. Y me aseguro de que nadie intenta
 coger más agua de la que le corresponde, por lo que no creo que vayamos a tener problemas.}
{124}{}{Mmm. Bien, sigue así.}
{125}{}{Tú también. Espero que encuentres pronto ese chip para que todos podamos recuperar
 nuestra vida normal.}
{126}{}{Puedes coger provisiones si las necesitas pues tu trabajo es muy
 importante, pero por favor, no te lleves demasiadas. No nos quedan muchas.}
{127}{}{¿Puedo llevarme algunas provisiones?}

{1000}{}{Ración}
{1001}{}{Raciones}
{1002}{}{Provisiones}
{1003}{}{Agua}

{1100}{}{Reparto raciones de agua por la mañana. No deberías necesitarlas, ahora que
 te vas al Exterior.}
{1101}{}{Reparto raciones de agua por la mañana. No deberías necesitarlas, ahora que
 te vas al Exterior.}
{1102}{}{Sólo nos quedan algunas provisiones. Puedes coger algunas si las necesitas para
 tu misión, pero por favor, no cojas demasiadas.}
{1103}{}{Reparto raciones de agua por la mañana. No deberías necesitarlas, ahora que
 te vas al Exterior.}
