{100}{}{Estás viendo a un guardia de los Mercaderes de Agua.}
{101}{}{Alto. Sólo los miembros de los mercaderes pueden acceder a la zona de la Torre de agua
 o de las bombas.}
{102}{}{No se te permite el paso, ¡fuera!}
{103}{}{¡Esta zona está fuera de los límites! Aléjate de las bombas.}
{104}{}{Vuélvete si aprecias tu pellejo.}
{105}{}{¡Último aviso! ¡Fuera!}
{106}{}{Será mejor que te vayas mientras puedas.}
{107}{}{Tienes unos segundos para irte o morirás.}
{108}{}{¿Estás sordo? ¡Vete ahora!}
{109}{}{Eso es.}
{110}{}{Tendrás que aprender de mala manera.}
{111}{}{¿Es que no oyes?}
{112}{}{Hay que darle una lección.}
{113}{}{Hay que darle una lección.}
{114}{}{Sólo los miembros de los mercaderes pueden acceder a la zona de la Torre de agua o de los surtidores.}
{115}{}{Debes irte.}
{116}{}{No confiamos en nadie y no vamos a empezar contigo.}
{117}{}{Será mejor que te alejes de los surtidores.}
{118}{}{Si necesitas algo, vete a la Cámara de los Mercaderes.}
{119}{}{Nos matarán. Ni lo pienses.}
{120}{}{No dejaremos que nadie ponga en peligro la sangre de la vida del Eje.}
