{100}{}{You see: Slappy.}
{101}{}{Boogie, Boogie, Boogie.}
{102}{}{It's a bitty spider, smashin', smashin'.}
{103}{}{Let's play Global Thermo-Nuclear War.}
{104}{}{Where's my blankie!?!}
{105}{}{Da... Da... Da...}
{106}{}{The Moon is out there.}
{107}{}{Gimme' the Sugar Baby.}
{108}{}{Oooh, pretty, pretty stuff. Why is the moon?}
{109}{}{Uh, I talked with Harold. The Deathclaw sounds pretty nasty. What can you tell me about it?}
{110}{}{Beth told me to talk to you about the Deathclaw.}
{111}{}{What do you do around here?}
{112}{}{What's your problem?}
{113}{}{Moon Big, me like Moon!}
{114}{}{All bright, it's all bright, the bright comes down, and then we are doomed.}
{115}{}{Ahh.}
{116}{}{Deathclaw, Deathclaw, Dah Dah Deathclaw.}
{117}{}{Come on, what do you know about the Deathclaw?}
{118}{}{What's your problem?}
{119}{}{Don't make me pound it out of you!}
{120}{}{Do, I, do, then you do, then we all do.}
{121}{}{No really, what do you do.}
{122}{}{You're a loony.}
{123}{}{Problems are like Soup Bowls, wide and shallow.}
{124}{}{That's more like your mind.}
{125}{}{Deathclaw scary, really scary. Looks neat though. Wanna' see it?}
{126}{}{You can take me to the Deathclaw?}
{127}{}{Hell no!}
{128}{}{Yeah, Deathclaw, Deathclaw, going to see the Deathclaw.}
{129}{}{Just shut up and take me there.}
{130}{}{Ah, never mind. You take care, now.}
{131}{}{I do this, then I do that. You see Harold? Harold's fun, his hair falls out, falls in the wind. There it goes... wind, wind.}
{132}{}{Whatever.}
{133}{}{Pound and Pound, and Pound and Pound.}
{134}{}{Why is the wind? Why why why why why.}
{135}{}{Beth, Beth, shoo sha Beth. Like Harold, you talk Harold. Harold tell you story. Slappy help then.}
{136}{}{Okay, I'll go talk to Harold first.}

# Fo1in2:
{150}{}{You earn }
{151}{}{ experience for learning about the Deathclaw.}
{2000}{}{Ohhh! No. No... No... No... Not going to see the Deathclaw. No.}
{2010}{}{Just shut up and show me on my PipBoy where it is.}
{2100}{}{Ahh. Show! Da... Da... Da...}
{2110}{}{[It takes a while to figure out Slappy's directions, but eventually you are able to nail it down to the mountain range west of the Hub]}

