{100}{}{You see: Vasquez, the mercenary desperado.}
{101}{}{You see a seedy-looking gunman.}
{102}{}{What do you want?}
{103}{}{Who are you?}
{104}{}{Hnn.}
{105}{}{I do not work for the weak of mind. You leave now.}
{106}{}{You have not heard of me? I am hurt! My name is Vasquez Villanova Hernandez Ortega. I am a famous desperado, my friend. And, if you have need, I am a gun for hire.}
{107}{}{Really? How much do you cost?}
{108}{}{See you around, maybe. Good luck. Heh.}
{109}{}{Ahh, straight to the point, my friend. Excellent. I will help you around town for a measly 500 caps a week. My services are not cheap, but then again, I am worth it.}
{110}{}{Great, I'll hire you. Here's 500 caps.}
{111}{}{Sorry to bother you, but I don't think I need your services.}
{112}{}{I am sorry, my friend, but I do not work for imaginary money. I need cold, hard cash.}
{113}{}{Excellent. I am yours. Let us go, this place bores me.}
{114}{}{Lead on, I am yours to command!}
{115}{}{Let us get something to drink!}
{116}{}{Where shall we go first?}
{117}{}{As long as you stay in Junktown, I am yours. I do not like leaving this town.}
{118}{}{Did you know that I have a bounty on my head? It is too small, however.}
{119}{}{Ah, my friend. It is good to see you again.}
{120}{}{I want to hire you for a week.}
{121}{}{Nice meeting you again.}
{122}{}{Hnn.}
{123}{}{Well, maybe it is not so good to see you again. Have a good day.}
{124}{}{Of course you do. My bill is small, and my worth is so large. 500 caps, please.}
{125}{}{Here you go.}
{126}{}{You should not have done that, my soon-to-be-dead friend.}
