{100}{}{Du siehst einen Supermutanten. Er bewacht die Tür der Luftschleuse.}
{101}{}{Du siehst eine Wache der Supermutanten.}
{102}{}{Jeremiah, du kannst passieren.}
{103}{}{Beweg' dich.}
{104}{}{Beweg' dich schneller, Bote.}
{105}{}{Normalos dürfen hier keine Waffen tragen! Bleib' stehen und weise dich aus!}
{106}{}{Grrr!}
{107}{}{Äh ... Entschuldigung. Ich pack' sie weg.}
{108}{}{Ich geh' einfach durch. Hier braucht man keinen Ausweis.}
{109}{}{Stirb! Stirb! Stirb! Das wollte ich schon immer mal sagen.}
{110}{}{Sprich nicht so mit mir. Dafür kommst du nicht ungestraft davon.}
{111}{}{Halt! Was treibst du hier?}
{112}{}{Hng!}
{113}{}{Ich ... äh ... hab' zu tun.}
{114}{}{Ich habe Wichtiges zu tun. Du hast kein Recht, mich anzuhalten und auszufragen.}
{115}{}{Sprich mich nicht an, Big Boy.}
{116}{}{Deine Antwort beruhigt mich nicht. Sprich schnell und klar, oder ich muss denken, dass du Übles im Sinn hast. Ich garantiere dir, dass du so nicht ...}
{117}{}{Äh ... nein ... wirklich nicht, ehrlich. Ich hab' zu tun.}
{118}{}{Ich hab' eine Botschaft für unseren Anführer.}
{119}{}{Du lügst doch. Du kommst hier nicht rein. Das schwör' ich dir ...}
{120}{}{Du darfst durch, aber das nächste Mal musst du dich richtig verhalten ...}
{121}{}{Okay, danke. Bis bald.}
{122}{}{Und was ist das?}
{123}{}{Sei gesegnet, Bruder.}
{124}{}{Ein echter Anhänger des Meisters würde das wissen. Du bist ein Eindringling!}
{125}{}{Beweg' dich. Ich hab' keine Zeit für deine Fragen.}
{126}{}{Du bringst mich in Rage.}
{127}{}{Ich hab' zu tun. Und was ist mit dir?}
{128}{}{Du hast einen Fehler gemacht, als du hierhergekommen bist. Erklär', was du hier machst, oder stirb ...}
{129}{}{Kopfnuss!}
{130}{}{Ich hab' nichts zu sagen.}
{131}{}{Ich bin hier, um die Menschheit vor Typen wie dir zu schützen.}
{132}{}{Oh, halt' den Mund!}
{133}{}{Versuch' nicht, mich reinzulegen, indem du dich dumm stellst. Ich hab's satt ...}
{134}{}{Was soll das heißen? Wir sind die 'Menschheit', wie uneinsichtig du doch bist.  Wir sind genauso menschlich wie du.}
{135}{}{Was soll das für ein Mist sein?}
{136}{}{Du bist bestimmt nicht menschlich.}
{137}{}{Mein Name ist Kyle. Ich habe eine Mutter und einen Vater, genau wie du. Der Meister hat nur meine Wiedergeburt übersehen. Diese Muskeln, diese Haut und diese Stärke, all das macht mich kein bisschen weniger menschlich, als du es bist. Ich mag nicht alles, wofür die Einheit steht, aber eine größere Chance auf Frieden gibt es nicht.}
{138}{}{Das sehe ich ganz anders. Ich bin hier, um dich und deinesgleichen auszulöschen.}
{139}{}{Meinetwegen bist du menschlich, aber deswegen ist deine Einheit auch nicht besser. Ich denke, wir werden Feinde sein.}
{140}{}{Schade, dass du dich so aufführst, aber ich werde dich aufhalten ...}
{141}{}{Echt schade, dass du bald sterben wirst.}
{142}{}{Eindringlinge!}
{143}{}{Ich spreche nicht mit dir.}
{200}{}{Du erhältst }
{201}{}{ Erfahrungspunkte für das Vorbeikommen an den Wachen.}
