{100}{}{Du siehst einen Knight.}
{101}{}{Der Unterrichtsraum ist dort drüben, falls du danach suchst.}
{102}{}{Hast du dich verlaufen? Der Unterrichtsraum ist dort drüben.}
{103}{}{Das medizinische Labor ist gleich um die Ecke.}
