{100}{}{Eine zweiköpfige mutierte Kuh, diese hier ist ein Haustier.}
{101}{}{Sieht normal aus.}

{102}{}{Warum redest du mit Brahmin?}
{103}{}{Das Brahmin starrt dich für einen moment an, und schaut dann weg.}
{104}{}{Das Tier ignoriert dich.}
{105}{}{Das Tier grunzt, reagiert aber ansonsten nicht.}

{106}{}{Eine zweiköpfige mutierte Kuh, diese hier ist ein wildes Tier.}
{107}{}{Dir kommen sie recht normal vor.}
{108}{}{An denen ist doch nichts echt. Diese zwei Köpfe können doch nur durch irgendeine eigenartige Mutation entstanden sein.}
{109}{}{Muh.}
{110}{}{Muh!}
{111}{}{Muh, sag ich.}
{112}{}{ES *GIBT* EINEN GEHEIMEN KUH-LEVEL!!!}
# Is this used anywhere?
{113}{}{Du hast die Kuh wütend gemacht indem du ihren Freund angegriffen hast.}

#Fo2
{201}{}{Muuh...}
{202}{}{Muuh Muuh Muuh...}
{203}{}{Muuh...}
{204}{}{Muuuuuh...}
{205}{}{Muuuuuuuuh...}
{206}{}{:: GRUNZ ::}

{210}{}{Du bist zum Experten-Exkrementschleuderer geworden!}
