{100}{}{Du siehst einen Elder der Brotherhood.}
{101}{}{Sei gegrüßt, Neuling.}
{102}{}{Maxson wirkt in letzter Zeit ein wenig gestresst.}
{103}{}{Vree hat ein paar sehr beunruhigende Entdeckungen gemacht.}
{104}{}{Ich frage mich, ob Maxson recht hat mit dieser Armee im Norden.}
{105}{}{Guten Tag, Neuling.}
