{100}{}{Das ist Caleb, der Anführer der Regulatoren.}
{101}{}{Du siehst einen ernsten Mann um die dreißig.}
{102}{}{Du solltest wissen, dass wir hier keine Fremden mögen. Was willst du?}
{103}{}{Guten Tag. Kann ich dir behilflich sein?}
{104}{}{Ich bin }
{105}{}{Du scheinst jemand Wichtiges zu sein.}
{106}{}{Kannst du mir was über Adytum erzählen?}
{107}{}{Kannst du mir sagen, was hier im Boneyard los ist?}
{108}{}{Erzähl mir was über die Regulatoren.}
{109}{}{Erzähl mir mehr über die Children of the Cathedral und ihre Anhänger.}
{110}{}{Wo finde ich Zimmerman?}
{111}{}{Schönen Tag noch. Danke.}
{112}{}{Nette kleine Stadt. Ich und die Regulatoren haben auch hart genug dafür gearbeitet. Suchst du jemand Bestimmtes?}
{113}{}{Wer regiert hier in Adytum?}
{114}{}{Und wer macht hier die Geschäfte?}
{115}{}{Das war's. Danke.}
{116}{}{Mach bloß keinen Ärger, klar? Ich bin Caleb, und das ist ein Name, den du dir merken solltest, denn wenn du Ärger machst, kriegst du es mit mir zu tun.}
{117}{}{Ich bin Caleb. Ich trainiere und organisiere die Regulatoren hier.}
{118}{}{Es gibt die Blades im Norden, ein ziemlich mitleiderregender Haufen und die Gunrunner etwas weiter nordöstlich quer über die Spielwiese der Deathclaw.}
{119}{}{Etwas südlich von hier gibt es die Children of the Cathedral, die ein Krankenhaus und eine Kathedrale haben. Noch ein wenig weiter nordöstlich gibt es die etwas abgedrehten Followers of the Apocalypse, ein friedliches Volk.}
{120}{}{Pass auf dich auf!}
{121}{}{Schönen Tag noch!}
{122}{}{Schon wieder da?}
{123}{}{Was kann ich für dich tun, mein Junge?}
{124}{}{Was kann ich für dich tun, mein Mädchen?}
{125}{}{Du steckst besser deine Waffen weg, solange du in der Stadt bist.}
{126}{}{Hagahaga.}
{127}{}{Tut mir leid, aber ich hab' jetzt keine Zeit. Geh jetzt.}
{128}{}{Adytum wird von Jon Zimmerman regiert. Er ist ein ehrlicher Kerl, der gut für die Stadt sorgt. Du solltest dich mit ihm treffen. Noch was?}
{129}{}{Tine hat einen Laden in der Nähe der Tore, etwas unterhalb vom kleinen Bunker. Er handelt mit den Leuten vom Hub und auch mit Fremden wie dir. Noch was?}
{130}{}{Wir sind die Polizei von Adytum. Die meisten Leute hier halten sich aus Ärger raus.}
{131}{}{Ich bilde die Regulatoren aus und sorge dafür, dass die Skags ihre Arbeit tun und dass uns niemand aus dem Hinterhalt überfällt. Noch was?}
{132}{}{Die Children of the Cathedral leben alle in diesem großen, schwarzen, kirchenähnlichen Gebäude. Sie verehren irgendeinen Gott und versuchen ständig, alle von ihrem Glauben zu überzeugen.}
{133}{}{Du findest ihn in diesem großen Gebäude südwestlich von der Stadt. Er kann dir vielleicht genauer sagen, warum wir Hilfe beim Kampf mit den Blades brauchen.}
{134}{}{Wieso? Was ist da los?}
{135}{}{Kann ich dich noch was fragen?}
{136}{}{Danke für die Aukunft. Tschüss dann!}
{137}{}{Na, sicher. Was willst du wissen?}
{138}{}{Sie haben Zimmermans beschränktem Sohn irgendwas angetan. Aber wie ich schon sagte, sprich mit Zimmerman selbst darüber.}
{139}{}{Kann ich dich noch was fragen?}
{140}{}{Hab' schon verstanden. Ich werd' mit Zimmerman sprechen.}
{141}{}{Zimmerman hat dich also über die Lage aufgeklärt. Er will sicherlich wissen, wann du den Job erledigt hast.}
{142}{}{Wo sind denn die Blades?}
{143}{}{Warum habt ihr euch nicht selbst drum gekümmert?}
{144}{}{Ja, ich komm' wieder, wenn der Job erledigt ist.}
{145}{}{Du findest die alle im Norden. Immer dem Gestank nach. Noch was?}
{146}{}{Weil es einfach eine Zeitverschwendung ist. Ich hab' besseres zu tun, als ein paar Skags umzulegen. An denen mach' ich mir nicht die Finger dreckig ... Noch was?}
{147}{}{Ah ja, du bist wieder da. Sprich mit Zimmerman.}
