{100}{}{Dies ist ein notdürftig reparierter Spielautomat. Ein Spiel kostet 10 Deckel.}
{101}{}{Du wirfst 10 Deckel ein und ziehst am Griff.}
{102}{}{DING! DING! DING!}
# TRANSLATION NOTE: The space at the end of 103 is intentional. Do not remove it.
{103}{}{Du bekommst drei Granaten. Ausgezeichnet! }
# TRANSLATION NOTE: The space at the beginning of 104 is intentional. Do not remove it.
{104}{}{ Deckel fallen in die Ausgabe, und du steckst sie ein.}
{105}{}{DING! DING! DING!}
{106}{}{Du hast drei Kugeln. Gewonnen! 15 Deckel fallen in die Ausgabe und du steckst sie ein.}
{107}{}{Ahh, so was blödes! Du hast verloren.}
{108}{}{Dein Geld reicht nicht, um weiterzuspielen.}
