{100}{}{Du siehst einen Nightkin.}
{101}{}{Stirb!}
{102}{}{Lass' mich' in Ruhe, oder du bist des Todes!}
{103}{}{Ich mag' deinen Ton nicht. Wenn du meine Nachricht nicht dem Meister überbringst, sorge ich dafür, dass man sich um dich 'kümmert'.}
{104}{}{Ich wollte dich gerade zu deinem tollen Buckel beglückwünschen. Aber gegen deinen Mundgeruch könntest du wirklich was tun.}
{105}{}{Könntest du mich zum Anführer bringen?}
{106}{}{Mann, du hast einen Drink nötiger als ich!}
{107}{}{Ich gehe nicht!}
{108}{}{OK. Bin schon weg.}
{109}{}{Nicht gerade klug, sich auf ein Spielchen mit den Nightkin einzulassen. Hau' ab!}
{110}{}{Ich denk' nicht dran.}
{111}{}{Es wird mir Freude machen, dir beim Sterben zuzusehen!}
{112}{}{Willst du nicht hören? Es ist nicht klug, die Nightkin zu ignorieren!}
{113}{}{Ich muss mit dir reden. Es ist dringend!}
{114}{}{Niemand hat mich je für klug gehalten!}
{115}{}{Ich will doch nur mit dem Anführer reden!}
{116}{}{Du hältst dich wohl für besonders stark, was?}
{117}{}{Tut mir leid! Schönen Tag noch.}
{118}{}{Leg' dich nicht mit mir an, du Klugscheißer!}
{119}{}{Geh' nach oben. Meine Freunde werden den Wert deiner Nachricht beurteilen.}
{120}{}{Das ist die letzte Warnung!}
{121}{}{Ja klar! Mein Gott. . .}
{122}{}{Ich will jetzt UNBEDINGT mit dem Anführer sprechen!}
{123}{}{OK! OK! Tut mir leid! Schönen Tag noch.}
{124}{}{Weißt du, was dein Fehler ist? Du hältst lange Reden. Ich nicht. Stirb!}
{125}{}{[OK]}
