{100}{}{Eine Holodisk mit dem Ehrenkodex der Brotherhood of Steel.}
{101}{}{Der PIPBoy zeigt an: Datei im System gefunden. Ladevorgang abgebrochen.}
{102}{}{Der PIPBoy zeigt an: Daten werden von Disk geladen.}
{103}{}{Du siehst eine Verschlüsselungsdekodier-Disk.}
{104}{}{Eine Holodisk. Sie kann von deinem PIPBoy gelesen werden.}

{105}{}{Sieht so aus, als wäre diese Disk dazu gedacht in ein Computerterminal gesteckt zu werden, um Entschlüsselungsalgorithmen auszuführen.}
