{100}{}{Du siehst Cougar, den Assistenten von Doc Morbid.}
{101}{}{Wie geht's?}
{102}{}{Ganz gut und dir?}
{103}{}{Ich will zum Doktor.}
{104}{}{Ung.}
{105}{}{Cougar geht's immer gut.}
{106}{}{Hey, ich muss wissen, ....}
{107}{}{Du solltest mit Flash hier reden. Der kann dir sicher weiterhelfen.}
{108}{}{Au! Red' doch nicht so viel. Da bekommt Cougar ja Kopfschmerzen von.
 Sprich lieber mit Flash.}
{109}{}{Da bist du ja wieder. Cougar hat dir nichts mehr zu sagen.}
{110}{}{Cougar beobachtet dich, Mann!}
{111}{}{Nette Ausrüstung, hast du das alles alleine erbeutet?}
