{100}{}{Du siehst einen von Wind und Wetter gezeichneten Bauern.}
{101}{}{Guten Tag.}
{102}{}{Hallo.}
{103}{}{Hubip.}
{104}{}{Hallo nochmal.}
{105}{}{Was kann ich für dich tun?}
{106}{}{Wie heißt du?}
{107}{}{Erzähl' mir was über dein Dorf.}
{108}{}{Was machst du so?}
{109}{}{Nichts, danke.}
{110}{}{Ich heiße Curtis.}
{111}{}{Unser Dorf ist ziemlich klein, aber wir können uns selbst ernähren. Mal abgesehen von
 den Angriffen durch die Raiders und den gelegentlichen Radscorpion haben wir eigentlich
 keine Probleme. Aradesh ist ein guter Anführer.}
{112}{}{Ich bin Bauer. Wir haben die Wüste schon vor vielen Jahren bewässert.
 Obwohl das Ödland eigentlich nichts hergibt, ist es uns gelungen mit Zeit und viel Geduld
 einiges anzubauen.}
{113}{}{Aha. Euch scheint es ziemlich gut zu gehen.}
{114}{}{Ihr habt alle eure Felder bepflanzt? Es wäre besser, wenn ihr gelegentlich
 eine andere Fruchtfolge verwenden würdert.}
{115}{}{Fruchtfolge? Was ist das?}
{116}{}{Ach, lass' mal.}
{117}{}{Ihr bepflanzt nur einige eurer Felder und ermöglicht es somit den anderen, die
 von den Pflanzen verbrauchten Nährstoffe wieder zu reproduzieren. Ihr lasst die Felder wieder
 fruchtbar werden, indem ihr nur das erntet, was da gerade wächst.}
{118}{}{Häh. Hab ich ja noch nie dran gedacht. Hört sich gut an.}
{119}{}{Kann ich dich noch was fragen?}
{200}{}{ Erfahrungspunkte für das verbessern der Landwirtschaft von Shady Sands.}
