{100}{}{Hallo! Willkommen in meinem Gebrauchtwagenladen. Für welche von diesen Schönheiten interessierst du dich?}
{101}{}{Machst du Witze. Das sind doch alles Wracks.}
{102}{}{Äh, nichts, danke.}
{103}{}{Lug!}
{104}{}{Oh, tut mir leid, ich glaube nicht, dass du dir unsere Finanzierung leisten kannst.}
{105}{}{Aber Sir, dies sind feinste Beispiele des Automobilbaus.}
{106}{}{Madam, dies sind ausgezeichnete Fahrzeuge.}
{107}{}{Die funktionieren doch bestimmt nicht mehr.}
{108}{}{Ja, klar. Okay. Tschüss.}
{109}{}{Diese Wagen wurden vollständig von unserer speziellen Serviceabteilung gewartet.}
{110}{}{Und wo ist diese Serviceabteilung?}
{111}{}{Du hast doch einen Knall.}
{112}{}{Auf Wiedersehen.}
{113}{}{Dort drüben, Sir. [Der Händler zeigt ins Nichts.]}
{114}{}{Dort drüben, Madam. [Der Händler zeigt ins Nichts.]}
{115}{}{Wo? Da drüben ist nichts.}
{116}{}{Du bist verrückt.}
{117}{}{Was meinen Sie? Unsere Leute arbeiten an einer Neuerwerbung, einem '56er Corvega. Ein ausgezeichneter Kauf, wenn ich mir die Bemerkung erlauben darf.}
{118}{}{Okay, wie du meinst.}
{119}{}{Du tickst doch nicht richtig.}
{120}{}{Tschüss.}
{121}{}{Und wir bieten eine ausgezeichnete Garantie. Sie können ihn auch zum Ölwechsel vorbeibringen. Der erste ist gratis. Wie meinen Sie?}
{122}{}{Noch 'n voller Benzintank dazu und wir machen den Deal.}
{123}{}{Du brauchst Hilfe.}
{124}{}{Ich muss jetzt gehen.}
{125}{}{Tut mir leid, wir haben kein Benzin. Nächstes Mal vielleicht. Auf Wiedersehen.}
{126}{}{Jetzt bin ich beleidigt. Das muss ich mir von einem Kunden nicht gefallen lassen. Guten Tag.}
{127}{}{Ich mache jetzt Mittag, kommen Sie später wieder.}
{128}{}{Na los schon, machen Sie doch eine Probefahrt.}
{129}{}{Dazu gehört eigentlich noch ein Rostschutzmittel.}
{130}{}{Haben Sie Interesse an einer Alarmanlage?}
{131}{}{Hallo! Ich heiße Bob.}
