{100}{}{Du siehst einen Hund. Er scheint dir zu folgen.}
{101}{}{Du siehst einen Hund.}
{102}{}{Wuff!}
{103}{}{Grrr!}
{104}{}{Du scheinst dich mit dem Hund angefreundet zu haben.}
{105}{}{ Erfahrungspunkte, weil du dich mit dem Hund angefreundet hast.}
{106}{}{ Erfahrungspunkte, weil du den Hund besiegt und Phil wieder ins Haus gelassen hast.}
{107}{}{ Erfahrungspunkte für das Töten des Hundes.}
{108}{}{You earn 200 experience points for befriending the dog.}
