{100}{}{Der Schrank ist zugesperrt.}
{101}{}{Du siehst eine Falle am Schrank und entschärfst sie.}
{102}{}{Du siehst eine Falle am Schrank, kannst sie aber nicht entschärfen.}
{103}{}{Du siehst eine Falle am Schrank und löst sie versehentlich aus!}
{104}{}{Du entschärfst die Falle.}
{105}{}{Du schaffst es nicht, die Falle zu entschärfen.}
{106}{}{Du löst versehentlich die Falle aus!}
{107}{}{Du sperrst den Schrank auf.}
{108}{}{Du schaffst es nicht, das Schrankschloss zu öffnen.}
{109}{}{Der Schrank ist schon offen.}
{110}{}{Während du am Schloss bastelst, aktivierst du die Verriegelung. Dieses Schloss kann
 nun nicht mehr geöffnet werden.}
{111}{}{Du bemerkst eine gefährliche Sprengladung am Schrank.}

+# Fo1in2
+{200}{}{ unlocks the locker.}
