{100}{}{Du schließt die Tür auf.}
{101}{}{Du hast deine Dietriche zerbrochen!}
{102}{}{Du kannst dieses Schloss nicht öffnen.}
{103}{}{Du konntest das Schloss nicht aufbrechen.}
{104}{}{Die Tür ist verschlossen.}
{105}{}{Die Tür ist offen.}
{106}{}{Die Tür ist zu aber nicht verschlossen.}
{107}{}{Die Tür ist verschlossen.}
{108}{}{Die Tür quietscht laut.}
{109}{}{Die Tür ist schon aufgeschlossen.}
{110}{}{Du kannst dieses Schloss nicht aufbrechen.}

# Fo1in2
{111}{}{The lock is beyond }
{112}{}{'s ability to pick.}

{120}{}{Du siehst eine Metalltür.}

# look_at_proc
{1000}{}{Du siehst eine Holztür.}
{1010}{}{Du siehst eine Metalltür.}

# description_proc

# Perception Check Critical Success
{1020}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einem hochexplosiven Sprengsatz im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1030}{}{Du siehst eine stabile Tür mit einem Schloss und einem hochexplosiven Sprengsatz im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1040}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einem hochexplosiven Sprengsatz im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1050}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einem hochexplosiven Sprengsatz im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}

{1060}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer Falle im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1070}{}{Du siehst eine stabile Tür mit einem Schloss und einer Falle im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1080}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einer Falle im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1090}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einer Falle im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}

{1100}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einem durchgeschnittenen Kabel im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1110}{}{Du siehst eine stabile Tür mit einem Schloss und einem durchtrennten Kabel im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1120}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einem durchtrennten Kabel im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1130}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einem durchgeschnittenen Kabel im Türrahmen. Vielleicht schaffst du es, die Tür aufzukriegen.}

{1140}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann). Vielleicht schaffst du es, die Tür aufzukriegen.}
{1150}{}{Du siehst eine stabile Tür mit einem Schloss. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1160}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss. Vielleicht schaffst du es, die Tür aufzukriegen.}
{1170}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss. Vielleicht schaffst du es, die Tür aufzukriegen.}

# Perception Check Success

{1180}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer hochexplosiven Sprengladung im Türrahmen.}
{1190}{}{Du siehst eine stabile Tür mit einem Schloss und einer hochexplosiven Sprengladung im Türrahmen.}
{1200}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einer hochexplosiven Sprengladung im Türrahmen.}
{121}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einer hochexplosiven Sprengladung im Türrahmen.}

{122}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer Falle im Türrahmen.}
{123}{}{Du siehst eine stabile Tür mit einem Schloss und einem Zünder im Türrahmen.}
{124}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einer Falle im Türrahmen.}
{125}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einer Falle im Türrahmen.}

{126}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einem durchgeschnittenen Kabel im Türrahmen.}
{127}{}{Du siehst eine stabile Tür mit einem Schloss und einem durchtrennten Kabel im Türrahmen.}
{128}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss, mit einem durchtrennten Kabel im Türrahmen.}
{129}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss und einem durchtrennten Kabel im Türrahmen.}

{130}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann).}
{131}{}{Du siehst eine stabile Tür mit einem Schloss.}
{132}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss.}
{133}{}{Du siehst eine stabile Tür mit einem alten, rostigen Schloss.}

# Perception Check Critical Failure

{134}{}{Du siehst eine beschädigte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer hochexplosiven Sprengladung im Türrahmen.}
{135}{}{Du siehst eine beschädigte Tür mit einem Schloss und einer hochexplosiven Sprengladung im Türrahmen.}
{136}{}{Du siehst eine beschädigte Tür, scheinbar ohne Schloss, mit einer hochexplosiven Sprengladung im Türrahmen.}
{137}{}{Du siehst eine beschädigte Tür mit einem alten, rostigen Schloss und einer hochexplosiven Sprengladung im Türrahmen.}

{138}{}{Du siehst eine beschädigte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer Falle im Türrahmen.}
{139}{}{Du siehst eine beschädigte Tür mit einem Schloss und einer Falle im Türrahmen.}
{140}{}{Du siehst eine beschädigte Tür, scheinbar ohne Schloss und mit einer Falle im Türrahmen.}
{141}{}{Du siehst eine beschädigte Tür mit einem alten, rostigen Schloss und einer Falle im Türrahmen.}

{142}{}{Du siehst eine beschädigte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einem durchgeschnittenen Kabel im Türrahmen.}
{143}{}{Du siehst eine beschädigte Tür mit einem Schloss und einem durchtrennten Kabel im Türrahmen.}
{144}{}{Du siehst eine beschädigte Tür, scheinbar ohne Schloss, mit einem durchtrennten Kabel im Türrahmen.}
{145}{}{Du siehst eine beschädigte Tür mit einem alten, rostigen Schloss und einem durchgeschnittenen Kabel im Türrahmen.}

{146}{}{Du siehst eine beschädigte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann).}
{147}{}{Du siehst eine beschädigte Tür mit einem Schloss.}
{148}{}{Du siehst eine beschädigte Tür, scheinbar ohne Schloss.}
{149}{}{Du siehst eine beschädigte Tür mit einem alten, rostigen Schloss.}

# Perception Check Failure

{150}{}{Du siehst eine alte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer hochexplosiven Sprengladung im Türrahmen.}
{151}{}{Du siehst eine alte Tür mit einem Schloss und einer hochexplosiven Sprengladung im Türrahmen.}
{152}{}{Du siehst eine alte Tür, scheinbar ohne Schloss, mit einer hochexplosiven Sprengladung im Türrahmen.}
{153}{}{Du siehst eine alte Tür mit einem alten, rostigen Schloss und einer hochexplosiven Sprengladung im Türrahmen.}

{154}{}{Du siehst eine alte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einer Falle im Türrahmen.}
{155}{}{Du siehst eine alte Tür mit einem Schloss und einer Falle im Türrahmen.}
{156}{}{Du siehst eine alte Tür, scheinbar ohne Schloss, mit einer Falle im Türrahmen.}
{157}{}{Du siehst eine alte Tür mit einem alten, rostigen Schloss und einer Falle im Türrahmen.}

{158}{}{Du siehst eine alte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann) und einem durchgeschnittenen Kabel im Türrahmen.}
{159}{}{Du siehst eine alte Tür mit einem Schloss und einem durchtrennten Kabel im Türrahmen.}
{160}{}{Du siehst eine alte Tür, scheinbar ohne Schloss, mit einem durchtrennten Kabel im Türrahmen.}
{161}{}{Du siehst eine alte Tür mit einem alten, rostigen Schloss und einem durchtrennten Kabel im Türrahmen.}

{162}{}{Du siehst eine alte Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann).}
{163}{}{Du siehst eine alte Tür mit einem Schloss.}
{164}{}{Du siehst eine alte Tür, scheinbar ohne Schloss.}
{165}{}{Du siehst eine alte Tür mit einem alten, rostigen Schloss.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Du hast die Falle ausgelöst und erhältst einen Treffer für }
{167}{}{ Trefferpunkte.}

# NPC sets off the trap
{168}{}{ löst die Falle aus und erhält einen Treffer für}
{169}{}{ Trefferpunkte.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Geschickt öffnest du das Schloss an der Tür.}
{171}{}{Du bist nicht besonders geschickt. Deshalb verklemmt sich das Schloss an der Tür.}
{172}{}{Du schaffst es nicht, das Schloss dieser Tür zu öffnen.}

# Lock Door
{189}{}{Du sperrst die Tür geschickt ab.}
{190}{}{Du schaffst es nicht, die Tür abzusperren.}

# Find Trap on the Door
{194}{}{Du findest eine Falle an der Tür.}
{195}{}{Du findest keine Fallen an der Tür.}

# Disarm the Trap on the Door
{196}{}{Geschickt schaffst du es, die Falle zu entschärfen.}
{198}{}{Du schaffst es nicht, die Falle zu entschärfen.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{öffnet geschickt das Schloss an der Tür.}
{174}{}{ist nicht besonders geschickt. Deshalb verklemmt sich das Schloss an der Tür.}
{175}{}{ schafft es nicht, das Schloss an der Tür zu öffnen.}

# Lock Door
{191}{}{ sperrt die Tür geschickt ab.}
{192}{}{ hat es nicht geschafft, die Tür abzusperren.}

# Find Trap on the Door
{199}{}{ findet eine Falle an der Tür.}
{2000}{}{ findet keine Fallen an der Tür.}

# Disarm the Trap on the Door
{2010}{}{ entschärft die Falle geschickt.}
{2020}{}{ schafft es nicht, die Falle zu entschärfen.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Du hast das Schloss von der Tür abgebrochen.}
{177}{}{Beim Aufbrechen des Schlosses verrenkst du dir den Rücken und wirst mit einem Trefferpunkt bestraft.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Beim Aufbrechen des Schlosses verrenkst du dir den Rücken und erhältst }
{179}{}{ Trefferpunkte.}
{180}{}{Du bist zu schwach, das Schloss aufzubrechen.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ bricht das Schloss von der Tür ab.}
{182}{}{ verrenkt sich den Rücken, während er versucht, das Schloss aufzubrechen und wird
 mit einem Trefferpunkt bestraft.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ verrenkt sich den Rücken, während er versucht, das Schloss aufzubrechen und erhält}
{184}{}{ Trefferpunkte.}

{185}{}{ ist zu schwach, das Schloss aufzubrechen.}
{186}{}{ verrenkt sich den Rücken, während sie versucht, das Schloss aufzubrechen und wird
 mit einem Trefferpunkt bestraft.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ verrenkt sich den Rücken, während sie versucht, das Schloss aufzubrechen und erhält}
{188}{}{ Trefferpunkte.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Das hat nicht mal einen Kratzer an der Tür hinterlassen.}

{200}{}{An dieser Tür ist kein Schloss, das man aufbrechen könnte.}
{201}{}{Du stellst einige Unregelmäßigkeiten in der Mauer fest.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Die Tür scheint verschlossen zu sein.}
{204}{}{Du bemerkst eine Falle am Türrahmen.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jam.

{205}{}{ bemerkt eine Falle am Türrahmen.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Du kannst keine Falle an der Tür anbringen, weil die Tür offen ist.}

# NPC tries to set a trap on an open door
{207}{}{ kann keine Falle an der Tür anbringen, weil die Tür offen ist.}

# Player tries to set a trap on a closed door
{208}{}{Du bringst geschickt eine Falle am Türrahmen an.}
{209}{}{Du schaffst es nicht, die Falle richtig am Türrahmen anzubringen.}

# NPC tries to set a trap on a closed door
{210}{}{ bringt geschickt eine Falle am Türrahmen an.}
{211}{}{ schafft es nicht, die Falle richtig am Türrahmen anzubringen.}

{300}{}{Du sperrst die Tür auf.}
{301}{}{Du schließt die Tür ab.}
{302}{}{Du kannst die Tür nicht abschließen, solange sie offen ist.}
{303}{}{Der Schlüssel passt nicht in dieses Schloss.}

# for broken doors
{320}{}{Es gibt keine Möglichkeit, diese Tür abzuschließen.}
{330}{}{Diese Tür ist offen und klemmt.}

# Using a key on the door. (YES THIS IS A DUPLICATE BUT PLEASE DO NOT REMOVE..
# IT MOST LIKELY IS BEING USED BY A DOOR SCRIPT SOMEWHERE)
{400}{}{Du sperrst die Tür auf.}

{414}{}{Du siehst eine stabile Tür mit einem Schloss (das mit einem Dietrich geöffnet werden kann). Vielleicht schaffst du es, die Tür aufzukriegen.}
{415}{}{Du siehst eine stabile Tür mit einem Schloss. Vielleicht schaffst du es, die Tür aufzukriegen.}
{416}{}{Du siehst eine stabile Tür, scheinbar ohne Schloss. Vielleicht schaffst du es, die Tür aufzukriegen.}
{417}{}{Du siehst eine solide Tür, die du vielleicht aufstemmen kannst.}

{500}{}{Diese Tür ist zu massiv zum Aufbrechen.}
{501}{}{Sieht aus, als müsstest du zuerst den Generator zum Laufen bringen.}
{502}{}{Du siehst: Fahrstuhltür.}
{503}{}{Sieht aus, als bräuchtest du ein elektrisches Gerät, um das Schloss aufzukriegen.}
