{100}{}{You see Fire.}
{101}{}{}
{102}{}{}
{103}{}{You see a member of the Blades.}
{104}{}{You see a member of the Blades.}
{105}{}{You think that might be Books.}
{106}{}{You think that might be Scars.}
{107}{}{You think that might be Gunner.}
{108}{}{You think that might be Twitch.}
{109}{}{You think that might be Hammer.}
{110}{}{You think that might be Razor.}
{111}{}{Whatcha want, loser?}
{112}{}{Err.}
{113}{}{I want to become a Blade.}
{114}{}{What would it take for me to get peace between you and
 Adytum?}
{115}{}{This! *smack*}
{116}{}{Nothing. Sorry I bothered you.}
{117}{}{I am just inspecting your place.}
{118}{}{Great. Another stupid one. You have the sound of a Ripper.}
{119}{}{Rrrrr.}
{120}{}{Arrrr.}
{121}{}{Arrooo?}
{122}{}{Don't like them much either? Maybe we can use you for a little
 'work.'}
{123}{}{Urroo.}
{124}{}{Un nah.}
{125}{}{Okay, talk to the head wench. Razor'll set you
 straight as to what ta do.}
{126}{}{Stupid and a chicken. I'll put you out of your misery now.}
{127}{}{So you are a Ripper! I'd be sorry to hear that, but then
 I already knew they were stupid. Goodnight!}
{128}{}{The Rippers. Those inbreds on the other side of town.
 Never mind. You're too stupid to know anything.}
{129}{}{You want to be a Blade? Good luck. But, if you can find
 Razor, talk to her about that. Maybe she'll let you get
 jumped in.}
{130}{}{Okay, thanks.}
{131}{}{Then I don't want in!}
{132}{}{What do you mean, 'jumped in?'}
{133}{}{Can't you just make me a Blade?}
{134}{}{Your momma never wanted you, and we don't either.}
{135}{}{Simple. You'll have to kill someone to get in here.
 She will tell you who you're gonna need to kill.}
{136}{}{Okay, thanks.}
{137}{}{Never mind. I don't want to be part of your stupid gang.}
{138}{}{No. I can't. I don't lead. I just keep Razor going straight.}
{139}{}{Simple. Slaughter our enemies, then we will give Adytum
 a break.}
{140}{}{Who are your enemies?}
{141}{}{Fair enough. Will you give me proof of this?}
{142}{}{Fighting is wrong! I won't do it!}
{143}{}{The Rippers. Those Gun Runners are just a pain, but nothing
 important. They are a  bunch of soft-sellers, anyway.}
{144}{}{Okay, I'll kill the Rippers.}
{145}{}{Never mind.}
{146}{}{If you plan on doing that, you may want to let Razor know.
 Otherwise, she will have your head before you get out of here.}
{147}{}{Suit yourself. Goodbye.}
{148}{}{I don't make the deals. I only make suggestions. Talk to Razor
 if you want to deal.}
{149}{}{Then killing you now would save you many years of suffering.}
{150}{}{Then inspect this!}
{151}{}{Get lost if you want to live.}
{152}{}{Quiet. We are trying to sneak up on the Rippers.}
{153}{}{If ya' got the head, take it to Razor. She still wants
 to play soccer. Otherwise, get out!}
{154}{}{Yo, homie!}