{100}{}{Du siehst Garret.}
{101}{}{Du solltest dich hier tagsüber nicht aufhalten. Set sieht das nicht gerne. Komm nachts wieder.}
{102}{}{Oh, okay.}
{103}{}{Er sollte lernen, mit seinen Problemen fertig zu werden.}
{104}{}{Das ist unwichtig. Wichtig ist nur, dass ich mit ihm spreche.}
{105}{}{Du solltest mit Set reden.}
{106}{}{Du erhältst: ein Gewehr, 10 Gewehrpatronen, 4 Leuchtraketen,
 4 Flaschen Cola und 200 Dollar.}
{107}{}{Du erhältst: ein Gewehr, 10 Gewehrpatronen und 100 Dollar.}
{108}{}{Du erhältst: 4 Leuchtraketen, 4 Flaschen Cola und 50 Dollar.}
{109}{}{Du solltest jetzt besser gehen.}
{110}{}{Man sieht sich.}
{111}{}{Das ist alles? Ich habe mehr verdient, und du solltest mir besser geben, was ich verdiene!}
{112}{}{Urg.}
{113}{}{Du musst von hier verschwinden ... sofort.}
{114}{}{Du kommst mit mir. Ich hol' mir die Belohnung für dich.}
{115}{}{Für dich hoffe ich das nicht. Set war nicht gerade glücklich darüber, dich einsetzen zu müssen. Es wäre vielleicht besser, Necropolis zu verlassen ... und zwar bald.}
{116}{}{Ich hab' dir doch gesagt, du sollst gehen.}
{117}{}{Egal.}
{118}{}{Vielleicht. Hmm. Hier, nimm auch dies.}
{119}{}{Du erhältst 100 Dollar.}
{120}{}{Geh jetzt.}
{121}{}{Hmm. Es fehlen einige Sachen aus dem Kühlschrank. Man hat uns offensichtlich bestohlen.}
{200}{}{Garret ignoriert dich.}
{201}{}{Hier ist deine Belohnung.}
{202}{}{Du erhälst eine hohe Belohnung.}
{203}{}{Du erhältst: }
{204}{}{ein Gewehr}
{205}{}{einige Gewehrpatronen}
{206}{}{einige Leuchtraketen}
{207}{}{ein Leuchtsignal}
{208}{}{einige Flaschen Cola}
{209}{}{eine Flasche Cola}
{210}{}{ Dollar}
