{100}{}{Du siehst einen Polizisten vom Hub.}
{101}{}{Ich wünschte, ich wäre näher an Zuhause stationiert.}
{102}{}{Ich frage mich, was mit diesen Caravans geschehen ist.}
{103}{}{Geh weiter!}
{104}{}{Lass deine Waffen besser stecken, Fremder!}
{105}{}{Keinen Ärger!}
{106}{}{Hast du etwas zu verzollen?}
{107}{}{Fuchtle nicht mit deiner Waffe in meinem Gesicht herum!}
{108}{}{Steck das weg, wenn du nicht eingelocht werden willst!}
{109}{}{Hast du das etwa auf mich gerichtet?}
{110}{}{Ich hab' schon von dir gehört. Pass auf!}
{111}{}{Wir werden dich im Auge behalten.}
{112}{}{Keine Schlägereien in unserer Stadt, Muskelprotz!}
{113}{}{Wir mögen keine Mörder.}
{114}{}{Wenn du einem nur ein Haar krümmst, machen wir dich fertig!}
{115}{}{Ich hasse Typen wie dich.}
{116}{}{Du brauchst nicht um Hilfe zu rufen, wenn du in Schwierigkeiten bist.}
{117}{}{He, danke, dass du unsere Arbeit erledigst.}
{118}{}{Wir tolerieren hier keinen Mord, auch wenn er gerechtfertigt ist.}
{119}{}{Wenn du derjenige bist, der die Deathclaw getötet hat ... Danke.}
{120}{}{Keinen Ärger, solange du in unserer Stadt bist!}
{121}{}{An deiner Stelle würde ich mich von Decker fernhalten.}
{122}{}{Angenehmen Aufenthalt!}
{123}{}{Willkommen im Hub!}
{124}{}{Sei gegrüßt, Fremder!}
{125}{}{Geh in den 'Maltese Falcon', wenn dir nach einem kühlen Drink ist.}
{126}{}{Geh immer der Hauptstraße nach, wenn du zum Markt willst.}
{127}{}{Geh weiter!}
{128}{}{Geh weiter, immer weiter!}
{129}{}{Wir sind hier, um aufzupassen und Schlimmes zu vermeiden.}
{130}{}{Halt deine Waffe unter Kontrolle, solange du in unserer Stadt bist.}
{131}{}{Lass dich damit bloß nicht in einen Kampf verwickeln.}
{132}{}{Ich schlag' vor, du steckst deine Waffe weg.}
{133}{}{Steck sie lieber weg ... deine Waffe meine ich.}
{134}{}{Willkommen, Paladin! Lange nicht mehr gesehen.}
{135}{}{Du bist also dieser Schläger. Keine Schlägereien mehr, verstanden?}
{136}{}{Fang bloß nicht noch 'ne Schlägerei an!}
{137}{}{Du bist der Störenfried ... Gerat bloß nicht wieder aus der Fassung!}
{138}{}{Die Far Go Traders wurden vernichtet. Ich kann's einfach nicht glauben.}
{139}{}{Die Water Merchants sind weg. Gott sei Dank!}
{140}{}{Der Crimson Caravan wurde zerstört.}
{141}{}{Hast du das gehört? Den Untergrund gibt's nicht mehr!}
{142}{}{Decker ist tot!}
{143}{}{Das Problem 'Decker' ist damit endgültig abgehakt.}
{144}{}{Pass auf! Das ist kein sicherer Ort hier!}
{145}{}{Pass auf deine Scripts auf!}
{146}{}{Pass auf deine Scripts auf!}
{147}{}{Der alte Harold ist immer für eine Geschichte gut.}
{148}{}{Du solltest dich hier nicht aufhalten. Du bist hier nicht sicher.}
{149}{}{Old Town ist wirklich ganz schön zerstört.}
{150}{}{Hier stinkt's.}
{151}{}{Wir sollten das Ganze hier dem Erdboden gleichmachen!}
{152}{}{Ich weiß, dass dieser verdammte Thieves Circle hier irgendwo sein muss.}
{153}{}{Armer Harold ... Er hat's schwer im Leben gehabt.}
{154}{}{Keinen Ärger!}
{155}{}{He, dich kenn' ich. Keine Schlägereien mehr, verstanden?}
{156}{}{Komm bloß nicht auf die Idee, noch 'ne Schlägerei anzufangen!}
{157}{}{Wenn wir dich noch mal bei einer Schlägerei erwischen, landest du im Knast!}
{158}{}{Hast du das gehört? Die Far Go Traders wurden vernichtet.}
{159}{}{Die Water Merchants gehören der Vergangenheit an. Was für ein Segen!}
{160}{}{Jemand hat den Crimson Caravan zerstört.}
{161}{}{Hast du das gehört? Den Untergrund gibt's nicht mehr!}
{162}{}{Decker ist tot!}
{163}{}{Diese Stadt wäre sicherer, wenn Decker von der Bildfläche verschwinden würde.}
