{100}{}{Du siehst einen Spieler.}
{101}{}{Ack! Das ist ein Überfall!}
{102}{}{Ich will keinen Ärger!}
{103}{}{Er hat eine Waffe!}
{104}{}{Sie hat eine Waffe!}
{105}{}{Ach, du bist's!}
{106}{}{Ich hab' schon viel Schlechtes über dich gehört. Nicht übel!}
{107}{}{Bist wohl auf die schiefe Bahn geraten, was?}
{108}{}{Was bist du bloß für ein Mensch? Ich kann einfach nicht glauben, dass du diese unschuldigen Menschen getötet hast.}
{109}{}{Ich hab' gehört, dass einige Kopfgeldjäger hinter dir her sind. Hast du die etwa auch umgelegt?}
{110}{}{Ich will nichts von dir hören.}
{111}{}{Oh Gott, du hast den Bürgermeister getötet, nicht wahr?}
{112}{}{Als Killian noch lebte, konnte ich diesen Ort nicht leiden. Jetzt macht es mir nichts mehr aus hierherzukommen.}
{113}{}{Verschwinde!}
{114}{}{He, wie geht's dir? Bei mir ist alles in Ordnung.}
{115}{}{He, wie läuft's? Bei mir ist alles in Ordnung.}
{116}{}{Lass mich in Ruhe. Ich hab' gerade 'ne Glückssträhne.}
{117}{}{Baby, diese Spielautomaten gehören mir.}
{118}{}{Los, gib mir was zu trinken!}
{119}{}{Grrr! Dieser Ort nervt!}
{120}{}{Jetzt räum' ich ab!}
