{100}{}{Halt!}
{101}{}{Stirb, Mensch!}
{102}{}{Auf Leben und Tod!}
{103}{}{Du wirst für deine Sünden büßen!}
{104}{}{Du darfst hier keine Waffen tragen, kleiner Bruder. Was hast du zu deiner Rechtfertigung zu sagen?}
{105}{}{Du darfst hier keine Waffen tragen, kleine Schwester. Was hast du zu deiner Rechtfertigung zu sagen?}
{106}{}{Hngg.}
{107}{}{Ist schon in Ordnung. Ich arbeite hier.}
{108}{}{Ist schon in Ordnung. Ich habe einen Ausweis.}
{109}{}{Ich habe Erlaubnis vom Leutnant, Waffen zu tragen.}
{110}{}{Was ist das für ein verräterisches Verhalten?!}
{111}{}{Dann zeig mir deinen Ausweis!}
{112}{}{Äh, ich hab' ihn in meiner anderen Uniform.}
{113}{}{Er ist hier vorne an meiner Waffe befestigt.}
{114}{}{Ok, aber ich warne dich! Ich werd' dich im Auge behalten.}
{115}{}{Ja, kleiner Bruder. Was willst du von mir?}
{116}{}{Ja, kleine Schwester. Was willst du von mir?}
{117}{}{Hng!}
{118}{}{Hmm, wo ist dieser Meister?}
{119}{}{Gelobt sei die Einheit, Bruder.}
{120}{}{Tut mir leid, aber du musst den Weg zur Einheit selbst finden.}
{121}{}{Du bist offenbar ein Heide. Zahle für deine Sünden!}
{122}{}{Er befindet sich auf der dritten Ebene, wie es seine Pflicht ist. Warum stellst du solche dumme Fragen?}
{123}{}{Oh, uh, einfach nur so.}
{124}{}{Ich werd' ihm so einen Tritt verpassen, dass er sonstwo landet!}
{125}{}{Welche Frage? Ich sagte: 'Sei gegrüßt, Meister!'.}
{126}{}{Du beleidigst mich! Stirb!}
{127}{}{Gelobt sei die Einheit!}
{128}{}{Man könnte meinen, du glaubst nicht, was du sagst. Ist das so? Oder bist du vom rechten Pfad abgekommen?}
{129}{}{Du glaubst, meine Stimme zittert, weil ich Angst habe. Dabei habe ich nur eine Erkältung!}
{130}{}{Ihr seid dem Untergang geweiht. Ich werd' es euch mit Hilfe meiner Freunde beweisen ...}
{131}{}{Wenn du erst einer von uns bist, wirst du dich nicht mehr vor solchen Kleinigkeiten fürchten. Fort!}
{132}{}{Was willst du diesmal? Ich hab' keine Zeit für dein Gerede.}
{133}{}{Labbo!}
{134}{}{Ich hab' keine Zeit für dein Leben ... Stirb!}
{135}{}{Nichts, tut mir leid.}
{136}{}{Gelobt sei die Einheit, Bruder.}
{137}{}{Wer bist du nur? Mal sehen ... Argh! Ein Eindringling ...}
{138}{}{Geh weiter. Tu deinen Teil für die Einheit, und geh mir nicht auf die Nerven!}
{139}{}{Mach weiter.}
{140}{}{Mach weiter. Tu deinen Teil für die Einheit.}
