{100}{}{Du siehst einen Skag.}
{101}{}{Hier ist es schön! Viel schöner als mein altes Zuhause.}
{102}{}{Hier gefällt's mir!}
{103}{}{Hier ist so viel Platz. Wenn ich irgendwelches Zeugs hätte, wäre hier genügend Platz dafür.}
{104}{}{Wo ist mein Hund?}
{105}{}{Ich hab' Durst.}
{106}{}{Hast du was zu essen?}
{107}{}{Ich hab' Hunger.}
{108}{}{Ist es schon Zeit für mich, ins Bett zu gehen?}
{109}{}{Du kannst mein altes Zuhause haben.}
{110}{}{Ich bin müde. Weshalb bist du hier?}
{111}{}{Das ist mein Zuhause. Verschwinde!}
{112}{}{Das ist mein Zuhause. Verschwinde!}
{113}{}{Wo ist mein Kissen?}
{114}{}{Ich bin müde.}
{115}{}{Tu mir nicht weh.}
{116}{}{Du gehörst zu den Menschen, die anderen weh tun!}
