{100}{}{Du siehst ein Mitglied der Skulz-Gang.}
{101}{}{He! Was glaubst du, was du hier tust?!}
{102}{}{Du befindest dich auf Skulz-Boden, Fremder. Verschwinde besser!}
{103}{}{Hast du ein paar Deckel übrig?}
{104}{}{Was gibt's da zu sehen?}
{105}{}{Hau ab!}
{106}{}{Zzzzz}
{107}{}{Mann, ist das heute heiß.}
{108}{}{Ich hab' Hunger.}
{109}{}{Los, lass uns was unternehmen.}
{110}{}{Warum schlagen wir nicht jemanden zusammen?}
{111}{}{Ich will ein bisschen Spaß haben.}
{112}{}{Gähn ...}
