{100}{}{Du siehst eine Aufzugtür mit blauen Farbspuren.}
{101}{}{Das Sicherheitssystem versetzt dir einen Stromschlag, verletzt dich aber nicht. Vielleicht solltest du das Sicherheitssystem mit irgend etwas ausschalten.}
{102}{}{Das Sicherheitssystem versetzt dir einen Stromschlag, der einen Trefferpunkt ausmacht. Vielleicht solltest du das Sicherheitssystem mit irgend etwas ausschalten.}
{103}{}{Das Sicherheitssystem versetzt dir einen Stromschlag, der }
{104}{}{ Trefferpunkte ausmacht. Vielleicht solltest du das Sicherheitssystem mit irgend etwas ausschalten.}
{105}{}{Du deaktivierst das Sicherheitssystem der Tür.}
{106}{}{Bei dieser Tür kannst du mit diesem Gegenstand nichts anfangen.}
