{100}{}{Du siehst einen Schrank.}
{101}{}{Dieser Schrank hat offensichtlich ein elektronisches Schloss.}
{102}{}{Mühelos öffnest du den Schrank.}
{103}{}{Dieses Schloss ist offensichtlich schwieriger zu knacken, als du dachtest.}
{104}{}{Mühelos öffnest du das Schloss am Schrank.}
{105}{}{Dieses Schloss ist offensichtlich schwieriger zu knacken, als du dachtest.}
{106}{}{Bei diesem Schrank kannst du mit dieser Fähigkeit nichts anfangen.}
