{100}{}{Am Rahmen dieser Sicherheitstür befinden sich Reste blauer Farbe.}
{101}{}{Das elektrische Feld der Tür versetzt dir einen leichten Stromschlag, der einen Trefferpunkt ausmacht.}
{102}{}{Das elektrische Feld der Tür versetzt dir einen starken Stromschlag, der }
{103}{}{ Trefferpunkte ausmacht.}
{104}{}{Du öffnest die Tür mit Gewalt.}
{105}{}{Die Tür ist verschlossen.}
{106}{}{Zutritt gewährt. Elektrisches Feld wird deaktiviert.}
{107}{}{Du bist nicht berechtigt, diesen Raum zu betreten.}
{108}{}{Bei diesem Sicherheitssystem kannst du mit diesem Gegenstand nichts anfangen.}
{109}{}{Du öffnest das Schloss der Sicherheitstür.}
{110}{}{Diese Tür scheint durch irgendein Sicherheitssystem gesichert zu sein.}
{111}{}{Du konntest das Türschloss nicht öffnen.}
{112}{}{Bei dieser Tür kannst du mit dieser Fähigkeit nichts anfangen.}
{113}{}{Du deaktivierst das elektrische Feld an der Tür.}
{114}{}{Du hast das elektrische Feld verstärkt.}
{115}{}{Du kannst das elektrische Feld nicht deaktivieren.}
{116}{}{Du öffnest das Türschloss, ohne das Sicherheitssystem zu aktivieren.}
{117}{}{Du kannst das Schloss nicht öffnen und wirst vom Sicherheitssystem schwer verletzt.}
{118}{}{Du kannst das Schloss nicht öffnen und wirst vom Sicherheitssystem verletzt.}
{119}{}{Das Sicherheitssystem versetzt dir einen Stromschlag, so dass du dich nicht mehr darauf konzentrieren kannst, das Schloss zu öffnen.}
{120}{}{Das Sicherheitssystem versetzt dir einen starken Stromschlag, so dass du dich nicht mehr darauf konzentrieren kannst, das Schloss zu öffnen.}
{121}{}{Du scheiterst kläglich beim Versuch, das Schloss zu öffnen, und ruinierst deine Dietriche.}
{122}{}{Du kannst das Schloss nicht öffnen.}
{123}{}{Du siehst eine schwere, verrostete Tür.}

{124}{}{Du siehst eine unverschlossene grüne Tür.}
{125}{}{Du siehst eine unverschlossene grüne Tür.}
{126}{}{Du siehst eine unverschlossene Tür mit einem sich bewegenden grünen Feld davor.}
{127}{}{Du siehst eine unverschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{128}{}{Du siehst eine grüne Tür.}
{129}{}{Du siehst eine grüne Tür.}
{130}{}{Du siehst eine Tür mit einem sich bewegenden grünen Feld davor.}
{131}{}{Du siehst eine Tür mit einem Hochspannungs-Sicherheitssystem.}
{132}{}{Du siehst eine verschlossene grüne Tür.}
{133}{}{Du siehst eine verschlossene grüne Tür.}
{134}{}{Du siehst eine verschlossene Tür mit einem sich bewegenden grünen Feld davor.}
{135}{}{Du siehst eine verschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{136}{}{Für diese grüne Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{137}{}{Für diese grüne Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{138}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du ein schimmerndes grünes Feld vor der Tür.}
{139}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du, dass die Tür durch ein Hochspannungs-Sicherheitssystem gesichert ist.}

{140}{}{Du siehst eine unverschlossene Tür.}
{141}{}{Du siehst eine unverschlossene Tür.}
{142}{}{Du siehst eine unverschlossene Tür mit einem sich bewegenden Feld davor.}
{143}{}{Du siehst eine unverschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{144}{}{Du siehst eine Tür.}
{145}{}{Du siehst eine Tür.}
{146}{}{Du siehst eine Tür mit einem sich bewegenden Feld davor.}
{147}{}{Du siehst eine Tür mit einem Hochspannungs-Sicherheitssystem.}
{148}{}{Du siehst eine verschlossene Tür.}
{149}{}{Du siehst eine verschlossene Tür.}
{150}{}{Du siehst eine verschlossene Tür mit einem sich bewegenden Feld davor.}
{151}{}{Du siehst eine verschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{152}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{153}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{154}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du ein schimmerndes Feld vor der Tür.}
{155}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du, dass die Tür durch ein Hochspannungs-Sicherheitssystem gesichert ist.}

{156}{}{Du siehst eine unverschlossene gelbe Tür.}
{157}{}{Du siehst eine unverschlossene gelbe Tür.}
{158}{}{Du siehst eine unverschlossene Tür mit einem sich bewegenden gelben Feld davor.}
{159}{}{Du siehst eine unverschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{160}{}{Du siehst eine gelbe Tür.}
{161}{}{Du siehst eine gelbe Tür.}
{162}{}{Du siehst eine Tür mit einem sich bewegenden gelben Feld davor.}
{163}{}{Du siehst eine Tür mit einem Hochspannungs-Sicherheitssystem.}
{164}{}{Du siehst eine verschlossene gelbe Tür.}
{165}{}{Du siehst eine verschlossene gelbe Tür.}
{166}{}{Du siehst eine verschlossene Tür mit einem sich bewegenden gelben Feld davor.}
{167}{}{Du siehst eine verschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{168}{}{Für diese gelbe Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{169}{}{Für diese gelbe Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{170}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du ein schimmerndes gelbes Feld vor der Tür.}
{171}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du, dass die Tür durch ein Hochspannungs-Sicherheitssystem gesichert ist.}

{172}{}{Du siehst eine unverschlossene gelbe Tür.}
{173}{}{Du siehst eine unverschlossene gelbe Tür.}
{174}{}{Du siehst eine unverschlossene Tür mit einem sich bewegenden gelben Feld davor.}
{175}{}{Du siehst eine unverschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{176}{}{Du siehst eine gelbe Tür.}
{177}{}{Du siehst eine gelbe Tür.}
{178}{}{Du siehst eine Tür mit einem sich bewegenden gelben Feld davor.}
{179}{}{Du siehst eine Tür mit einem Hochspannungs-Sicherheitssystem.}
{180}{}{Du siehst eine verschlossene gelbe Tür.}
{181}{}{Du siehst eine verschlossene gelbe Tür.}
{182}{}{Du siehst eine verschlossene Tür mit einem sich bewegenden gelben Feld davor.}
{183}{}{Du siehst eine verschlossene Tür mit einem Hochspannungs-Sicherheitssystem.}
{184}{}{Für diese gelbe Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{185}{}{Für diese gelbe Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel.}
{186}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du ein schimmerndes gelbes Feld vor der Tür.}
{187}{}{Für diese Tür brauchst du offensichtlich einen besonderen Sicherheitsschlüssel. Außerdem bemerkst du, dass die Tür durch ein Hochspannungs-Sicherheitssystem gesichert ist.}

{188}{}{Du siehst eine grüne Tür.}
{189}{}{Du siehst eine Tür mit einem sich bewegenden grünen Feld davor.}
{190}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser grünen Tür.}
{191}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser grünen Tür. Du fragst dich, ob man es mit einem bestimmten Schlüssel ausschalten kann.}

{192}{}{Du siehst eine Tür.}
{193}{}{Du siehst eine Tür mit einem sich bewegenden Feld davor.}
{194}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser Tür.}
{195}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser Tür. Du fragst dich, ob man es mit einem bestimmten Schlüssel ausschalten kann.}

{196}{}{Du siehst eine gelbe Tür.}
{197}{}{Du siehst eine Tür mit einem sich bewegenden gelben Feld davor.}
{198}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser gelben Tür.}
{199}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser gelben Tür. Du fragst dich, ob man es mit einem bestimmten Schlüssel ausschalten kann.}

{200}{}{Du siehst eine gelbe Tür.}
{201}{}{Du siehst eine Tür mit einem sich bewegenden gelben Feld davor.}
{202}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser gelben Tür.}
{203}{}{Du siehst ein Hochspannungs-Sicherheitssystem an dieser gelben Tür. Du fragst dich, ob man es mit einem bestimmten Schlüssel ausschalten kann.}

{204}{}{Du bemerkst eine Falle an dieser Tür.}
{205}{}{Der Aufzug funktioniert nicht. Er benötigt offensichtlich Strom.}
