{100}{}{System:                                                         Hauptstrom:                  AUS                           Notstrom:               EIN}
{101}{}{Stromversorgung}
{102}{}{Str*mv*rs*rg*ng}
{103}{}{Beenden}
{104}{}{Verwaltung der Stromversorgungssysteme}
{105}{}{Hauptstrom}
{106}{}{Notstrom}
{107}{}{ZURÜCK}
{108}{}{Hauptstromversorgung:       AUS}
{109}{}{Hauptstrom erneut einschalten}
{110}{}{ZURÜCK}
{111}{}{Hauptstromversorgung:                                          FEHLER! FEHLER! FEHLER!                                               Fehler beim Einschalten des Hauptstroms}
{112}{}{Diagnose}
{113}{}{ZURÜCK}
{114}{}{Fehler:        Generatorebene 6                                       0 Rückmelder:  Außer Betrieb                                          Reparatur erforderlich}
{115}{}{ZURÜCK}
{116}{}{Notstromversorgung:     EIN}
{117}{}{Notstrom ausschalten}
{118}{}{ZURÜCK}
{119}{}{System:                                                         Hauptstrom:                  EIN                           Notstrom:                BEREIT}
{120}{}{Stromversorgung}
{121}{}{Beenden}
{122}{}{Hauptstromversorgung:       EIN}
{123}{}{Hauptstrom ausschalten}
{124}{}{ZURÜCK}
{125}{}{System:                                                         Hauptstrom:                  EIN}
{126}{}{H**ptstr*m **ssch*lt*n}
{127}{}{Hauptstrom ausschalten}
{128}{}{Beenden}
{129}{}{V*rw*lt*ng d*r Str*mv*rs*rg*ngss*st*m*}
{130}{}{H**ptstr*m}
{131}{}{N*tstr*m}
{132}{}{ZURÜCK}
{133}{}{H**ptstr*mv*rs*rg*ng}
{134}{}{H**ptstr*m *rn**t **nsch*lt*n}
{135}{}{ZURÜCK}
{136}{}{H**ptstr*mv*rs*rg*ng:                                          F*HL*R! F*HL*R! F*HL*R!                                              G*n*r*t*rr*p*r*t*r *rf*rd*rl*ch}
{137}{}{ZURÜCK}
{138}{}{N*tstr*mv*rs*rg*ng:     **N}
{139}{}{System:                                                         Hauptstrom:                  AUS                           Notstrom:               AUS}
{140}{}{Notstrom einschalten}
{141}{}{H**ptstr*md**gn*s*}
{142}{}{H**ptstr*msch*tz*ng}
{143}{}{N*tstr*m **nsch*lt*n}
{144}{}{Str*mv*rs*r*ngsqu*ll*}
{145}{}{Beenden}
{146}{}{S*st*mf*hl*r!                                                         *ng*lt*g*r B*n*tz*r. V*rw*lt*ng b*n*chr*cht*g*n.                          S*st*m g*st*ppt.}
{147}{}{Beenden}
{148}{}{N*tstr*m **ssch*lt*n}

{200}{}{Erbitte Zugriff auf Großrechner.}
{201}{}{Zugriff verweigert. Eingabe wird beendet.}
{202}{}{Zugriff erteilt.}
{203}{}{Hauptmenü}
{204}{}{Großrechner verlassen}
{205}{}{Programm beenden}
{206}{}{Option auswählen}
{207}{}{Basisinformationen}
{208}{}{Sicherheitsinformationen}
{209}{}{Forschungsinformationen}
{210}{}{Stromende}
{211}{}{West Tech-Forschungszentrum:                                     Das 2002 als privates Subunternehmen der US-Regierung gegründete Unternehmen bestand ursprünglich aus den beiden Abteilungen 'Waffenforschung' und 'Biomedizin'.}
{241}{}{ Im Jahre 2069 war West Tech das größte private Subunternehmen der US-Regierung; sein größte Auftrag war das Infanteriepowerrüstungs-Modell T-51b. }
{242}{}{Angesichts der bedeutenden Fortschritte des NBC beim Panimmunitäts- Virus-Projekt im Jahre 2076 hat das US-Verteidigungs- ministerium aus Angst vor internationaler Spionage}
{243}{}{ ein Team vor Ort abgestellt, um das Projekt - jetzt FEV-Projekt genannt - zu überwachen.}
{212}{}{Sicherheit:                                                     Sicherheitsroboter: Aktiv}
{213}{}{Sicherheit:                                                     Sicherheitsroboter: Inaktiv}
{214}{}{Sicherheitsroboter deaktivieren}
{215}{}{Sicherheitsroboter aktivieren}
{216}{}{Forschung:                                                     Aktuellste Akten des West Tech-Forschungszentrums}
{217}{}{Akten - Forschungsabteilungsangestellte}
{218}{}{Powerrüstung. Status: Abgeschlossen}
{219}{}{FEV (Force Evolutionary Virus). Status: Noch nicht abgeschlossen}
{220}{}{Akten - Forschungspersonal}
{221}{}{Robert Anderson                                                     Forschungsassistent                                                 Sicherheitsstufe: Blau                                    Stationiert: Mariposa-Militärbasis}
{222}{}{Nick Davis                                                         Leiter NBC-Abteilung, West Tech-Forschungszentrum         Sicherheitsstufe: Blau                                        Stationiert: West Tech-Forschungszentrum}
{223}{}{John Isaac                                                     Forschungsassistent                                             Sicherheitsstufe: Rot                                    Stationiert: West Tech-Forschungszentrum}
{224}{}{Steve Remco                                                     Forschungsassistent                                             Sicherheitsstufe: Blau                                    Stationiert: Mariposa-Militärbasis}
{225}{}{Charles Rignhold                                                     Forschungsleiter Laserabteilung                           Sicherheitsstufe: Blau                                       Stationiert: West Tech-Forschungszentrum}
{226}{}{Michele Santose                                                     Labortechniker                                                      Sicherheitsstufe: Rot                                        Stationiert: West Tech-Forschungszentrum}
{227}{}{Erin Shellman                                                           Labortechniker                                                      Sicherheitsstufe: Blau                                        Stationiert: Mariposa-Militärbasis}
{228}{}{Leon VonFelden                                                     Forschungsleiter FEV-Virus                                       Sicherheitsstufe: Blau                                       Stationiert: Mariposa-Militärbasis}
{229}{}{Akten in PIP-Boy laden}
{230}{}{ZURÜCK}
{231}{}{Powerrüstungsspezifikation:                                     Die T-51b-Powerrüstung ist mit den neuesten passiven Verteidigungsfunktionen für zivile und militärische Zwecke ausgestattet. }
{250}{}{Das am Rücken befestigte TX-28 Mikro- fusionspaket erzeugt 60.000 Watt zum Antrieb der in den Anzug eingebauten HiFlo-Hydrauliksysteme. }
{251}{}{Die äußere Schutzschicht der T-51b, gefertigt aus den neuesten Polylaminat-Verbundstoffen, ist extrem leicht und kann Energie von mehr als 2.500 Joule absorbieren. }
{252}{}{Die 10 Mikron dicke ablative Silberschicht kann Laser- und Strahlen- emissionen reflektieren, ohne die Verbundoberfläche zu beschädigen.}
{232}{}{FEV-Zusammenfassung:                                              2073. Als China seine biologischen Waffen immer aggressiver einsetzte, wurde die Notwendigkeit einer Gegenmaßnahme für die Regierung der Vereinigten Staaten von Amerika immer unabdingbarer. Am 15. September 2073 wurde das Panimmunitätsvirusprojekt (PVP) offiziell gegründet. }
{233}{}{2075. Es wurde deutlich, dass die beste Art der Bekämpfung der neu hergestellten biologischen Waffen darin bestand, nicht infizierte DNA so zu verändern, dass diese nicht mehr auf normale Virusinfektionen ansprach. }
{234}{}{2076. In dem PVP-Projekt traten unvorhergesehene Nebenwirkungen erstmals Anfang 2076 auf. Die Versuchstiere zeigten ein anomales Wachstum und eine erhöhte Hirntätigkeit.}
{235}{}{Die US-Regierung nahm diese Ergebnisse zur Kenntnis und stellte im Interesse der nationalen Sicherheit ein Team vor Ort ab, um die Sicherheit des Projekts zu gewährleisten, das von nun an als FEV-Projekt (Forced Evolutionary Virus) bezeichnet wurde. }
{236}{}{2077. Das FEV-Projekt steht vor dem Abschluss. Versuche mit Labortieren erzielten eine Erfolgsrate von fast 100 %. Köpergröße und Muskeldichte nehmen um ca. 60 % zu und die potentielle Intelligenz um 200 %. }
{237}{}{Die Auswirkungen auf menschliche Organismen bleiben unbekannt; rein theoretisch sind sie jedoch sehr vielversprechend. }
{238}{}{Das Militär, das weitere Tests plant, baut eine große Anlage nahe der Mariposa-Militärbasis in Mittelkalifornien. Dort werden die Versuche mit dem FEV-Virus an freiwilligen Personen des Militärs fortgeführt.}
{239}{}{Befehl erhalten:                           Befehl ausgeführt}
{240}{}{Zugriff verweigert}
