# Heather is a female. She has a sweet, yet discerning quality about her.
# She acts as though she is trying to hide something and does a really good
# job of confusing the matter for people. Elusive and evasive. She will play
# on anything that you give her to work with.

{100}{}{You see: Heather, of the Follower's Scouts.}
{101}{}{What are you doing here?}
{102}{}{Dis!}
# moronic line for This

{103}{}{Go bye.}
# moronic line for "Goodbye".

{104}{}{I'm just looking around.}
{105}{}{I am here to kill you!}
{106}{}{Just curious as to what is going on around here.}
{107}{}{Really? And what might you be looking for?}
{108}{}{I think I have already found her.}
{109}{}{I am looking for a spy.}
{110}{}{Nothing really. Just looking around.}
{111}{}{Just information.}
{112}{}{Thank you, but I am already spoken for. I think it is time for you to leave.}
# "I am already spoken for" == "i am already dating someone else"

{113}{}{Yes, the spy. I have heard of that bothersome pest. I really wish we could catch him.}
# Spy is considered male

{114}{}{I kept hearing that it was a female spy.}
# Spy is considered female

{115}{}{Have you heard anything about this spy?}
# spy is considered male

{116}{}{You are the spy!}
# spy is considered female

{117}{}{Good luck to you. Sorry I bothered you.}
{118}{}{I bet it was the braggart Neil that said as much. I'll have to have a talk with him later.}
# Neil is male

{119}{}{You think that Neil is the spy?}
# spy is male. Neil is male.

{120}{}{Then who do you think the spy is?}
# spy is male

{121}{}{You sound a bit defensive. Any reason why?}
{122}{}{I am almost sure of it. I just need some proof.}
{123}{}{I will get you proof.}
{124}{}{He seems like a nice person. I don't know.}
{125}{}{Why do you think it is him?}
{126}{}{Thank you. You don't know how much this means to me. Once you get proof, kill him.}
{127}{}{What is there not to know? He has access to the Children. He works during the night when most are asleep. It has to be him.}
# Children is short for Children of the Cathedral. Religous cult who believe in destroying
# anyone who gets in there way or acts against thier wishes. They are really bad people.
# consider Male.

{128}{}{Okay, I will check into it.}
{129}{}{Forget it. I think you are trying to divert me!}
{130}{}{I am truly sorry that you think that way. I cannot have someone think I am a spy. I will remove you from service.}
# Spy is female. "I will remove you from service" == "i am going to have to kill you now"

{131}{}{He has access to the Children during the night. No one ever sees him on duty. It must be him.}
# Children is short for Children of the Cathedral. Religous cult who believe in destroying
# anyone who gets in there way or acts against thier wishes. They are really bad people.
# consider Male.

{132}{}{Okay, I will check into it.}
{133}{}{Forget it. I think you are trying to divert me!}
{134}{}{I am not certain as to whom it is. I think it may either be a guard or a scholar. They keep sneaking into the Children's Cathedral at night.}
# Guard is considered male. Scholar is considered female.
# Children is short for Children of the Cathedral. Religous cult who believe in destroying
# anyone who gets in there way or acts against thier wishes. They are really bad people.
# consider Male.

{135}{}{Any other leads that you can think of?}
# == is there any other information that you can think of?

{136}{}{But I've heard talk that only the scouts do raids on the Children}
# scouts is male
# Children is short for Children of the Cathedral. Religous cult who believe in destroying
# anyone who gets in there way or acts against thier wishes. They are really bad people.
# consider Male.

{137}{}{Okay. Thank you for your help.}
{138}{}{Not really. Just that I think it is a male and probably a scholar or guard.}
# is is refering to a male spy. Scholar and guard are male.

{139}{}{Okay. Thank you for your help.}
{140}{}{True. We scouts do many raids on the Children, and to much loss lately. This spy costs us dearly.}
# scouts is male. spy is male.
# Children is short for Children of the Cathedral. Religous cult who believe in destroying
# anyone who gets in there way or acts against thier wishes. They are really bad people.
# consider Male.

{141}{}{You seem really torn up about this. I will look for the spy and kill him.}
# "you seem really torn up about this." == "you seem emotionally distraught over this"
# spy == male

{142}{}{Could the spy be a scout?}
# spy and scout == male

{143}{}{Thank you for your help.}
{144}{}{Why would one of us do that?}
#us referres to the scouts

{145}{}{If you kill off the scouts, then you stop the raids.}
{146}{}{I don't know. Why would you do that?}
{147}{}{Don't know. Just wondering.}
{148}{}{Sounds like a good thought. I've noticed Peter never gets attacked much in the raids. I think he may be the one.}
# Peter is male. She thinks that Peter may be the male spy.

{149}{}{Okay, I will check into it.}
{150}{}{Forget it. I think you are trying to divert me!}
{151}{}{You think that it is me?}
# it referring to the female spy.

{152}{}{I'm sorry. I'm just a bit jumpy.}
# under a bit of stress.

{153}{}{Yes! Now you will die!}
{154}{}{Then wonder somewhere else. I must get back to work.}
# then think about it somewhere else

{155}{}{I think he thinks I am the spy. But I'm not.}
# spy is female

{156}{}{Maybe he is right.}
{157}{}{Why would he think that?}
{158}{}{Because I am the new scout. I've only been here for about a year and the trouble started about five months ago.}
# scout is female

{159}{}{I think Neil may be right.}
# Neil is male. right == correct.

{160}{}{I think Neil might be the spy. I'll go check into it.}
# spy is male.

{161}{}{Then look elsewhere. This is no place for you.}
{162}{}{If you need information, look to Nicole. She thinks she knows everything.}
# Nicole is female. said in a snotty manner.

{163}{}{I can be persuaded to tell you something that's going on. For a price.}
{164}{}{How much?}
{165}{}{You would sell secrets?}
{166}{}{Forget it. I have no money.}
{167}{}{Three hundred caps and the information is yours.}
{168}{}{Sure.}
{169}{}{No way.}
{170}{}{There will be a raid on the south end of the Children's stronghold. Now go.}
{171}{}{Trying to cheat me? I'll show you!}
{172}{}{I'm sorry you feel that way. But, good day to you.}
{173}{}{I need to get by somehow. Now, do you want in or not?}
# do you want me to give you the information?

{174}{}{Sure.}
{175}{}{No way.}
{176}{}{Nothing. Now leave.}
{177}{}{Leave me. I am trying to get some rest.}

# new:
{200}{}{I don't have any new infos right now.}

