# These are Male farmers who work and toil under the sun. Tone of voice is busy, yet friendly.
# Accent, if any would be akin to Midwestern United States, a little slow and drawn out, but not
# a Southern drawl.

{100}{}{Du siehst einen Farmer.}
{101}{}{Ich brauch' besseren Boden.}
{102}{}{Ich brauch' niemanden.}
{103}{}{Ich brauch' kein Wasser, geh jetzt bitte.}
{104}{}{Der Boden ist zu hart.}
{105}{}{Diese blöden Pflanzen werden nicht überleben.}
{106}{}{Warum bin ich bloß Farmer geworden?}
{107}{}{Diese Köter sollten mir besser nicht aufs Feld pinkeln.}
# pissing == urinating

{108}{}{Ich hasse Hunde!}
{109}{}{Ich hasse Hunde! Äh ... außer deinen natürlich.}
{110}{}{Du bist hier nicht zu Hause.}
{111}{}{Was? Gehst du jedem so auf die Nerven?}
{112}{}{Was für ein Tag! Ich bin echt fertig.}
{113}{}{Ich ruf' die Polizei.}
{114}{}{Ich bin müde. Geh jetzt bitte.}
