{100}{}{Du siehst einen Elder der Brotherhood.}
{101}{}{Sei gegrüßt, Neuling. Ich muss mit dir sprechen. [Er winkt dich heran.]}
{102}{}{Worüber denn?}
{103}{}{Dafür habe ich jetzt keine Zeit.}
{104}{}{Ähm?}
{105}{}{Es gibt eine dringende Sache, bei der ich deine Hilfe brauche. Es geht um Maxson. Wir sind sicher, dass er durchgedreht ist. Er lallt die ganze Zeit von einer Armee, die sich im Norden sammelt.}
{106}{}{Ich werde unsere Truppen nicht in vielleicht verstrahlte Gebiete schicken, solange ich nicht absolut sicher weiß, dass es diese Armee auch wirklich gibt.}
{107}{}{Ich brauche jemanden, der kein Freund vom Alten ist. Jemanden, der mir ehrlich berichtet. Bist du bereit, das nördliche Gebiet auszukundschaften?}
{108}{}{Ich mach's.}
{109}{}{Ich hab' jetzt keine Zeit, ich muss mich um andere Sachen kümmern.}
{110}{}{Ich habe schon eine Basis im Norden gesehen, die von einer Armee von Mutanten geführt wird.}
{111}{}{Gut. Sprich erst mit Maxson, wenn du nicht schon mit ihm gesprochen hast. Melde dich bei mir, wenn du aus dem Norden zurück bist. Danach entscheiden wir, was wir mit Maxson machen.}
{112}{}{Drück mir die Daumen!}
{113}{}{Hast du schon den gesamten Norden abgesucht?}
{114}{}{Ja.}
{115}{}{Nein.}
{116}{}{Und was kannst du berichten?}
{117}{}{Ich habe eine Basis gefunden, die von schwer bewaffneten Mutanten bewacht wird. Schaut ziemlich schlimm aus.}
{118}{}{Dachte ich mir doch. Du warst nicht lange weg. Jetzt mach dich noch einmal auf den Weg, und komm mit einem VOLLSTÄNDIGEN Bericht zurück.}
{119}{}{Jawohl!}
{120}{}{Ich informiere die Elder. Wir warten ab, was Maxson vorschlägt. Informiere ihn darüber, was du gefunden hast. Danke für deine Hilfe, Neuling.}
{121}{}{Gern geschehen.}
{122}{}{Dann nimm dir Zeit, mir zuzuhören.}
{123}{}{Ich bin ganz aufmerksam.}
{124}{}{Fahr zur Hölle, Alter!}
{125}{}{Vergiss es! Ich hab' Wichtigeres zu tun.}
{126}{}{Ich verstehe. Wenn du in dieses Gebiet reist und etwas findest, lass es mich bitte wissen.}
{127}{}{Wenn ich im Norden was finde, das wie eine Armee aussieht, lasse ich es dich wissen.}
{128}{}{Gut gemacht, das mit den Mutanten. Wir haben schon gehört, dass du ihre Produktionsanlagen zerstört hast. Danke, dass du das Problem für uns gelöst hast.}
{129}{}{Keine Ursache.}
{130}{}{Ähm? Was soll das für eine Antwort sein? Raus! Sofort!}
{131}{}{Wenn ich was zu sagen hätte, müsstest du hier verschwinden.}
{132}{}{Ich habe dir nichts zu sagen.}
{133}{}{Du solltest etwas mehr Respekt haben!}
{134}{}{Die Versammlung möge zur Ruhe kommen. Alle Elder sind anwesend und hören die Behauptungen von Bruder }
{135}{}{. Wir entscheiden, welche Maßnahmen getroffen werden. Bruder }
{136}{}{, erzähl uns, was du im Norden gesehen hast.}
{137}{}{Während meiner Erkundungen habe ich eine militärische Anlage gefunden, die von Mutanten genutzt wird. Sie ist schwer bewacht, und es gibt regelmäßige Patrouillen.}
{138}{}{Norfa?}
{139}{}{Und wie sahen diese Mutanten aus?}
{140}{}{Sie sind große Humanoide. Ihre Muskelmasse übertrifft alles, was ein normaler Mensch je erreichen könnte. Mehrere von ihnen scheinen das Tor in organisierten Truppen zu bewachen.}
{141}{}{Sie waren groß, grünlich und trugen Waffen.}
{142}{}{Wie du weißt, hat die Anführerin der Scribes, Vree, eine Autopsie an einem Wesen durchgeführt, das dieser Beschreibung sehr ähnelt. Glaubst du, das sind die gleichen?}
{143}{}{Ja. Die Beschreibung des Wesens ist fast identisch.}
{144}{}{Welche Bedrohung stellen diese Mutanten deiner Meinung nach dar?}
{145}{}{Genauso wie sich die Brotherhood für den Kampf rüstet, bereitet sich diese Mutantenarmee auf etwas Großes vor.}
{146}{}{Ehrlich gesagt, hat dein Bericht uns keinen Beweis erbracht, dass sie eine Bedrohung für uns sind. Womit kannst du beweisen, dass sie feindlich gesinnt sind?}
{147}{}{Sie haben Necropolis besetzt. Das wird ihnen nicht reichen.}
{148}{}{Sie ziehen eine Armee zusammen, schwer bewaffnet. Damit wollen sie sicher nicht nur eine Parade veranstalten. Sie wollen sie einsetzen.}
{149}{}{Ist es bei den Maßnahmen, die sie getroffen haben, denkbar, dass sie irgendwann hierher kommen?}
{150}{}{Es ist möglich, dass sie schon unterwegs sind. Die Brotherhood ist der einzige richtige Gegner, den sie haben.}
{151}{}{Ich glaube nicht, dass dies feindliche Absichten sind. Sie könnten sich einfach vor Angriffen schützen wollen. Auch wir haben gelegentlich mit Angriffen zu tun.}
{152}{}{Wenn sie angreifen, wird es NICHT VERGLEICHBAR sein mit den gelegentlichen Angriffen der Raiders. Es wird ein Blutbad.}
{153}{}{Da sie von der alten Militäranlage kommen, nehme ich an, dass sie Waffen besitzen, die mit den unseren vergleichbar sind.}
{154}{}{Was schlägst du vor? Einen Präventivschlag gegen ihre Militärbasis?}
{155}{}{Ja. Ich will aber nicht, dass sie wissen, dass wir kommen. Ein kleines Team hätte eine größere Chance, unentdeckt einzudringen.}
{156}{}{Damit wird nur ein Teil des Problems gelöst. Ihre Anführer sind eine Gruppe aus der Boneyard-Kathedrale.}
{157}{}{So sei es. Drei Paladine meiner Wahl werden an der Militärbasis zu dir stoßen, um dir beim Eindringen zu helfen. Verehrte Elder, danke für eure Zeit. Viel Glück, Neuling.}
{158}{}{Wenn sie von einer Gruppe aus der Boneyard-Kathedrale angeführt werden, dann haben sie da unten wahrscheinlich auch eine kleine Armee.}
{159}{}{Wenn wir sie im Norden angreifen, ist unsere Südseite verwundbar. Ich kann für dieses Unternehmen nur wenige Männer entbehren.}
{160}{}{Gebt mir einige Paladins, damit ich die Basis im Norden zerstören kann.}
{161}{}{Gebt mir einige Paladins, damit ich die Basis im Süden zerstören kann.}
{162}{}{So sei es. Zwei Paladins meiner Wahl werden an der Boneyard-Kathedrale zu dir stoßen. Verehrte Elder, danke für eure Zeit. Viel Glück, Neuling.}
{163}{}{So sei es. Drei Paladins meiner Wahl werden an der Militärbasis zu dir stoßen, um dir beim Eindringen zu helfen. Verehrte Elder, danke für eure Zeit. Viel Glück, Neuling.}
{164}{}{Wir haben offensichtlich einen Fehler gemacht. Verehrte Elder, es tut mir leid, eure Zeit verschwendet zu haben. Würde bitte jemand diesen Irren hier entfernen?}
{165}{}{Ich habe genug damit zu tun, eine Verteidigungsstrategie auszuarbeiten.}
{166}{}{Du erhältst }
{167}{}{ Erfahrungspunkte, weil du die Brotherhood zur Hilfe überreden konntest.}

# Fo1in2
{168}{}{ experience for convincing the Brotherhood of Steel to help you take out the Boneyard Cathedral.}
