{100}{}{Du siehst einen Gefangenen.}
{101}{}{Ich hab' niemanden umgebracht!}
{102}{}{Ich bin unschuldig!}
{103}{}{Was gibt's da zu gucken?}
{104}{}{Ich wollt's mir nur ausleihen. Ehrlich!}
{105}{}{Wo sind mein Wasser und Brot?}
{106}{}{Man hat mich reingelegt!}
{107}{}{Niemand weiﬂ, was ich alles durchgemacht hab' ...}
