{100}{}{You see a young man with sharp features.}
{101}{}{You see Jason Zimmerman.}
{102}{}{Hey, are you from really far away? Have you had a lot
 of adventures?}
{103}{}{Yes, I'm from a Vault far to the north.}
{104}{}{Actually, I'm from Mars. Want to see my firelance?}
{105}{}{I've had some adventures.}
{106}{}{Haven't done all that much, really.}
{107}{}{Uh, far. Vault.}
{108}{}{Oh. I thought someone who'd been through the wastes
 outside would be, well, smarter. Never mind.}
{109}{}{Miles says that now that you got those parts,
 he can get the farms working, so that we don't have to
 sell bullets to the Hub. I never thought much about it
 until Smitty pointed out that the bullets he made were }
{110}{}{sold to the Hub, who sold them to the gangs. I guess you
 found a good solution.}
{111}{}{I never thought that we would be able to stop fighting
 the gangs. My father told me how you got them to promise
 to leave us alone. You know, I thought I always wanted
 to go adventuring, but I think that I like . . . well, the }
{112}{}{feeling of security here now. No more worrying about the
 gangs suddenly attacking and wondering who's going to be killed.}
{113}{}{Lorraine says that there was a Vault south of here,
 where a lot of my grandparents lived. What's it like
 living in a Vault?}
{114}{}{It's pretty boring, actually.}
{115}{}{It's very exciting. We have all sorts of technology
 you wouldn't believe!}
{116}{}{Oh. Well, you must have had some adventures after leaving, right?}
{117}{}{Not really.}
{118}{}{Yes, there's quite a bit of danger out there.}
{119}{}{As someone once wrote, 'Adventure is someone else far
 away having a very unpleasant time.'}
{120}{}{Huh. The Hub merchants talk about radscorpions and stuff.}
{121}{}{Actually, it's mostly just desert.}
{122}{}{Well, actually, there are all sorts of monsters out there.}
{123}{}{Really? What kinds of monsters have you fought?}
{124}{}{Not much, just some rats and stuff.}
{125}{}{Yeah, the Hub guards said that there are lots of radioactive
 mutant things living in the desert. Monster hunting must be
 a real blast!}
{126}{}{Yes, it's a real kick!}
{127}{}{No; it's more of a pain. Venom, bites, radiation . . . it's deadly.}
{128}{}{I wish that I could go adventuring sometime.}
{129}{}{I never though about that. I rather like having
 clean water and a place to stay.}
{130}{}{I thought that living in the wasteland would be . . .
 you know . . . rugged, and dangerous, and everything.
 But I suppose we have enough to keep us busy here, with
 the gangs and all.}
{131}{}{What, are you some kind of weirdo or something? Caleb never
 should have let you in the gates!}
{132}{}{That's cool. All we have here is this stupid well
 and those underground farms that Miles keeps trying
 to get working.}
{133}{}{Yeah, I noticed that you don't have a bedroll or anything.
 It must get pretty dirty and uncomfortable out there.}
{134}{}{Hello again. Have any interesting stories to tell?}
{135}{}{What do you want to know about?}
{136}{}{Not really.}
{137}{}{Well, if you do anything interesting, tell me all about it!}
{138}{}{Leave me alone!}
{139}{}{Thank goodness you're here! Please help me get out of here!}
{140}{}{Ayuh.}
{141}{}{Don't worry, I'll get us out of here.}
{142}{}{Sorry kid, you're on your own!}
{143}{}{What are you doing here?}
{144}{}{Thank you!}
{145}{}{Please don't leave me!}
{146}{}{I thought that it would be fun to leave Adytum and
 explore the world. But the Rippers caught me and
 have been holding me here. Please, help me!}
{147}{}{All right, let's get out of here!}
{148}{}{No way. You got yourself into this, you get out.}
{149}{}{I hope we get out of here soon!}