{100}{}{Du siehst Kyle.}
{101}{}{Du siehst einen Knight.}
{102}{}{Ähh... Du bist das also, was?}
{103}{}{Was?}
{104}{}{Na, wer bist du?}
{105}{}{Nichts. Bis jetzt ist bloß noch niemand jemals vom Alten Orden zurückgekehrt.}
{106}{}{Was tust du hier?}
{107}{}{Was? Warum hat man mich dann da hinunter geschickt?}
{108}{}{Es war schwierig, aber nicht unmöglich.}
{109}{}{Hehe. Wollten dich wohl loswerden, was? Hast die ganz schön verarscht.}
{110}{}{Ja. Sag' mal, was machst du hier?}
{111}{}{Der einzige Grund, warum ich beigetreten bin, ist, weil ich die Powerrüstung wollte.}
{112}{}{Ihr könnt mich alle. Ich hau' ab.}
{113}{}{Ich repariere Zeug, mache Wartungsarbeiten, der ganze Müll eben.}
{114}{}{Könntest du einen Steuerchip reparieren?}
{115}{}{Welche Art von "Zeug"?}
{116}{}{Hört sich ja wirklich lustig an. Wir sehen uns später.}
{117}{}{Powerrüstungen und alles, was gerichtet werden muss.}
{118}{}{Wie kriege ich 'ne Powerrüstung in die Finger?}
{119}{}{Ich würd' dir ja die Rüstung da geben, aber es fehlt der Systolische Motivator. Ohne den ist die nutzlos.}
{120}{}{Wo kriegt man sowas her?}
{121}{}{Naja, trotzdem danke.}
{122}{}{Im Vorratsraum liegen mehr als genug davon herum, aber Michael und seine blöden Formulare meinen, dass dieser besondere Anzug nicht den Anforderungen entspricht. Scheißbürokraten.}
{123}{}{Was meinst du, den Anforderungen nicht entspricht?}
{124}{}{Wenn ich dir einen Systolischen Motivator bringe, würdest du sie mir dann
 reparieren?}
{125}{}{Siehst du das Augenstück da? Ich musste es wieder anlöten, und es schaut nicht so schön aus, wie es für die Inspektion nötig ist, nehm' ich an.}
{126}{}{Du hast recht. Schaut bescheiden aus. Ich würde mich in der Powerrüstung nicht sehen lassen.}
{127}{}{Hau' bloß hier ab, Alter.}
{128}{}{Boa, wart' mal 'ne Minute, Alter, das würde 'n paar Stunden dauern. Ich kann dir 'ne Anweisung und meine Werkzeuge leihen, aber reparieren musste schon selber.}
{129}{}{Wo, außer von Michael, kann ich einen herbekommen?}
{130}{}{Das ist gerecht. Ich komm' wieder.}
{131}{}{He, naja, Rhombus hat 'n paar. Ich würde ihn aber nich' drum bitten. Nur die "Geehrten" dürfen die Poweranzüge da tragen. Übrigens glaube ich, dass er 'ne unnatürliche Neigung zu denen hat.}
{132}{}{Hmm. Okay, herzlichen Dank.}
{133}{}{Glaub' ich nicht. Weiß nich' mal, was das is'.}
{134}{}{Trotzdem danke.}
{135}{}{Was für ein mieser Mechaniker bist du denn, kannst nicht mal 'nen Steuerchip richten?}
{136}{}{Wie komme ich an eine Powerrüstung, ohne hundert Jahre studieren zu müssen?}
{137}{}{Man nennt mich Kyle. Ich hab' noch nie 'nen Mythos kennengelernt.}
{138}{}{Was soll denn das heißen?}
{139}{}{Was tust du hier?}
{140}{}{Ich auch nicht. Wir sehen uns.}
{141}{}{Wenn man Maxsons Geschichten hört, könnte man meinen, das ist die neunte Stufe
 der Hölle.}
{142}{}{Maxson? General Maxson?}
{143}{}{Nicht General Maxson, sein Großvater, Roger Maxson. Ich hab gehört, du hast 'ne Scheibe gebracht, auf der erzählt wird, was mit den Typen geschehen ist, die gegen ihn rebelliert haben, und bist nach unten gegangen, um die verlorene Technik hochzuholen.}
{144}{}{Ja, stimmt. Ich bin, }
{145}{}{. Wer bist du?}
{146}{}{Ich würde lieber nicht darüber reden.}
{147}{}{Ja, dreckige Schweine. Ich kann's nicht glauben, dass die dich einfach so da runter
 geschickt haben.}
{148}{}{Und alles, was die mir gegeben haben, war 'ne Handvoll Munition!}
{149}{}{Hey, Neuling, hast du was für mich?}
{150}{}{Nein, ich hab' dem gesagt, dass du mich schickst, und er wollte mir das Teil nicht geben.}
{151}{}{Nein, ich hab's auch noch nicht probiert.}
{152}{}{Noch kein Glück.}
{153}{}{Ohne Scheiß. Und ich hab' geglaubt, du bist clever. Ich hab' dir doch gesagt, der Typ
 hat nix als Formulare im Hirn.}
{154}{}{Pass' auf, wen du Idiot nennst.}
{155}{}{Ich hab' versucht, ihn Michael aus dem Kreuz zu leiern.}
{156}{}{Was kann ich tun, wenn Michael ihn mir nicht gibt?}
{157}{}{Ich gehe.}
{158}{}{Naja... Da muss ich dir Recht geben. Aber ich glaub', du hast jetzt deine Chancen verspielt, ihn aus dem Vorratsraum zu kriegen. Du musst ihn auf 'ne andere Weise finden. Oder such' dir 'ne Powerrüstung woanders.}
{159}{}{OK, bis später.}
{160}{}{Wo kann ich noch eine ausgraben?}
{161}{}{Viel Glück.}
{162}{}{Verzieh' dich, ich hab' zu tun.}
{163}{}{Hallo, hast du das Teil kriegen können?}
{164}{}{Ja. Da ist es.}
{165}{}{Ja, aber ich glaube, ich behalt's noch eine Weile.}
{166}{}{Super! Lass' es mich schnell in die Einheit einbauen.}
{167}{}{OK, jetzt kann's losgehen. Da, nimm die Anweisungen. Wenn du 'n bisschen geschickt bist, was zu reparieren, dürftest du keine Schwierigkeiten haben. Viel Glück.}
{168}{}{Nach all dem? Okay, lass' es mich einfach wissen, wenn ich's einbauen soll. Dann kannst du anfangen, die Rüstung zu reparieren.}
{169}{}{Tja, ich weiß nicht, was ich dir sagen soll. Du musst wohl deine Reparaturfähigkeiten 'n bisschen aufpolieren. Ich behalt' die Einheit für dich da.}
{170}{}{OK. Danke dir. Auf Wiedersehen.}
{171}{}{Grüß' dich. Kann ich dir helfen?}
{300}{}{[mehr]}
