{100}{}{Du siehst einen Wachposten der Ghuls.}
{101}{}{Ich kann jetzt nicht reden. Ich bin auf Wache.}
{102}{}{Ein menschlicher Spion!}
{103}{}{Was machst du hier unten?}
{104}{}{Hmm, nicht viel. Was machst du?}
{105}{}{Ich halte Ausschau.}
{106}{}{Häh.}
{107}{}{Na, nichts. Ich lebe hier.}
{108}{}{Hier findest du nichts. Geh' weg.}
{109}{}{[OK]}
{200}{}{Ohne Wasser werden wir nicht überleben können.}
{201}{}{Rede bitte mit unserem Anführer, bevor du gehst.}
