{100}{}{You see Dr. Solone, M.D.}
{101}{}{You see Nurse Marney.}
{102}{}{You see a doctor.}
{103}{}{You see a nurse.}
{104}{}{Welcome. How might I help you today?}
{105}{}{Hurrgh.}
{106}{}{I'm hurt. Can you fix me up?}
{107}{}{Can you teach me about medicine?}
{108}{}{Yes, I see that you are suffering from some damage. This
 may take some time. Would you like me to try to mend your
 wounds?}
{109}{}{Uh huh.}
{110}{}{Nuh uh.}
{111}{}{Yes, please.}
{112}{}{No, thank you.}
{113}{}{There you go. That should have you all set. Please be more
 careful out there.}
{114}{}{You're good at that. Can you teach me about trauma care?}
{115}{}{Okay. Thank you.}
{116}{}{I can teach you a little. But it will take several hours. Are you
 willing to stay?}
{117}{}{Yes.}
{118}{}{Sorry, too busy.}
{119}{}{You are a very good student. I hope you remain on our
 side. Good bye.}
{120}{}{As you wish. Good luck out there.}
{121}{}{I can teach you a little, but not much. It will take some time.
 Are you willing to stay?}
{122}{}{Yes.}
{123}{}{I'm sorry, but I lack extra time.}
{124}{}{You are an excellent student. Good luck to you.}
{125}{}{Nothing right now. Thanks though.}