{100}{}{Du siehst den Meister der Supermutanten.}
{101}{Mast00}{Du hast die Wahl: Trittst du der Einheit bei, oder stirbst du hier? Beitritt! Tod! Beitritt! Tod!}
{102}{}{Ich kann eh nur verlieren, also tret' ich der Einheit bei.}
{103}{}{Wenn du mir beweist, dass eure Einheit das Beste für die Menschheit ist, dann helfe ich euch.}
{104}{}{Wie wär's, wenn ich dich einfach umlege und abhaue?}
{105}{}{Heute wird jemand sterben, aber ich bin's nicht! Ich habe nämlich einen Plan.}
{106}{}{Uff.}
{107}{Mast01}{Sehr gut. Dein Können wird mir nützen. Nützen! Doch sag mir erst alles über deine Vault.}
{108}{}{Warum?}
{109}{}{Okay, ich sag' dir alles, was du wissen willst.}
{110}{Mast02}{Ich erobere sie und verwandle alle Menschen in Mutanten. Sie werden die Armee sein, mit der ich dem ganzen Ödland Frieden bringe.}
{111}{}{Tut mir leid, aber irgendwie gefällt mir das nicht.}
{112}{}{Klingt vernünftig. So machen wir's!}
{113}{Mast03}{So sei es. Du schaufelst dir dein Grab. Grab! Grab!}
{114}{Mast04}{Ich muss dir gar nichts beweisen. Beweisen!}
{115}{}{Schon dein Ego sagt dir, dass du es beweisen musst! Alle Schurken haben diesen seltsamen Drang, alles erklären zu müssen.}
{116}{}{Wie soll ich dir glauben, dass du eine bessere Zukunft schaffst, ohne Beweis?}
{117}{Mast05}{Ganz schön dreist für jemanden in deiner Position. Aber ich achte deine Bedürfnisse.}
{118}{}{Also sag schon!}
{119}{Mast06}{Die Einheit wird die Meisterrasse schaffen. Meister! Meister! Überlebensfähig, ja sogar wachsend im Ödland. Solange es Unterschiede gibt, werden wir uns im Kampf in Stücke reißen. Wir brauchen eine Rasse. Rasse! Rasse! Ein Ziel. Ziel! Ziel! Ein Volk ... um unserem Schicksal zu begegnen. Schicksal!}
{120}{}{Und diese Rasse sind natürlich die Mutanten!}
{121}{}{Ich hoffe, wir sehen am Ende nicht so aus wie du!}
{122}{Mast07}{Natürlich. Mutanten bewähren sich bestens in dieser Welt. Wer sonst? Die Ghuls? Bitte! Normale? Sie brachten uns den Strahlentod! Dies wird die Ära der Mutanten. Mutanten!}
{123}{}{Du willst also alle zu Mutanten machen?}
{124}{}{Du bist ganz schön selbstherrlich!}
{125}{}{Willst du etwa auch Widerständler zu Mutanten machen?}
{126}{Mast08}{Die Widerständler ja. Und alle, die für die Einheit nötig sind. Die Übrigen dürfen ihr Leben zu Ende leben, aber unter Aufsicht und Schutz der Einheit. Fortpflanzung ist nicht erlaubt. Sie sind die Letzten.}
{127}{}{Leider hast du etwas bei deinem Plan nicht bedacht ...}
{128}{}{Offensichtlich hast du alles unter Kontrolle. Ich bin dabei!}
{129}{}{Ihr seid doch alle total verrückt und müsst gestoppt werden.}
{130}{Mast09}{Und was ist das?}
{131}{}{Du hast die Rechnung ohne mich gemacht! Ich werd' dich stoppen, und zwar sofort!}
{132}{}{Du kannst wohl kaum die ganze Welt übernehmen!}
{133}{}{Zufällig weiß ich, dass deine Mutanten unfruchtbar sind.}
{134}{Mast10}{Die Welt kommt später dran. Wenn ich deine Vaultgenossen mutiere, wird sich niemand meiner Macht entziehen können! Können! Keine Sorge, du spürst nichts. Nichts! Nichts!}
{135}{Mast11}{Lächerlich! Das FEV 2-Virus zerstört die Fortpflanzungsorgane der Mutanten nicht. Lächerlich!}
{136}{}{Früher vielleicht nicht, aber jetzt schon.}
{137}{}{Hast du vielleicht mal mit deinen Mutanten darüber geredet?}
{138}{}{Aber vielleicht diese ganze Strahlung ...}
{139}{Mast12}{Und? Beweise?}
{140}{}{Na klar! Hier ...}
{141}{}{Glaub mir, es ist so.}
{142}{}{Frag deine Mutanten!}
{143}{Mast13}{Das beweist nichts! Nun zahl für deine Frechheit. Zahl!}
{144}{}{Ich muss das erst einmal verdauen ... Moment mal ...}
{145}{Mast14}{Ich muss das erst einmal verdauen ... Moment mal ... Jetzt verstehe ich. Das ist eine Fälschung! Das dient nur, mich zu täuschen. Täuschen! Mich!}
{146}{}{Was!? Ich verstehe nicht ganz. Ich war davon ausgegangen, dass das stimmt.}
{147}{}{Du lügst! Du leugnest klare Tatsachen!}
{148}{Mast16}{Zahl für das, was du getan hast! Zahl! Getan!}
{149}{Mast17}{Das kann nicht sein. Sein! Dann wäre all meine Arbeit umsonst. All meine Mühen ... ein Fehlschlag! Darf nicht sein. Sein! Sein! Sein!}
{150}{}{Bedaure, du hast keine Chance! Deine Rasse wird nach dieser Generation aussterben.}
{151}{}{Vielleicht kann man doch was machen. Vielleicht brauchst du mehr Testpersonen.}
{152}{Mast18}{Ja, mehr Personen! Ich fang' gleich bei dir an. Dir! Dir! Dir!}
{153}{Mast19}{Ich ... glaube, ich kann nicht weitermachen. Weitermachen? Die Dinge zu tun, die ich für Fortschritt und Heilung getan habe ... Es war verrückt. Das seh' ich jetzt ein. Verrückt. Verrückt? Es gibt keine Hoffnung. Geh, solange du noch hoffst ...}
{154}{Mast20}{Das werd' ich tun. Genau! Nicht bewegen!}
{155}{Mast21}{Meine Forscher sagen mir, dass alles gut läuft. Was sagst du dazu? Sag! Sag!}
{156}{}{Hast du schon mal eine Frau ... äh ... Mutantin befragt?}
{157}{}{Frag einen deiner Leutnants.}
{158}{}{Sie haben doch Angst vor dir. Glaubst du etwa, sie sagen dir die Wahrheit?}
{159}{Mast22}{Moment mal! Er ist nicht mehr da. Er ist tot, und ich ahne, wer der Mörder ist. Mord! Tot!}
{160}{Mast23}{Er leugnet alles. Und er sagt, er weiß, wer das Gerücht erfand ...}
{161}{Mast24}{Ich glaub', ich weiß, wer der Lügner ist. Lügner!}
{162}{Mast25}{Vernünftig. Moment mal ... Sicher? Und die anderen Frauen? Es kann nicht sein. Sein!}
{163}{}{Tut mir leid, aber deine Rasse ist dem Untergang geweiht.}
{164}{}{Verzeih, wenn ich schadenfroh bin ... Hab' ich's dir nicht gleich gesagt?}
{165}{Mast26}{Ohne Beweis kann ich dir leider nicht glauben. Schließ dich als Mutant meiner Armee an, oder du stirbst! Tod? Ha! Armee?}
{166}{}{Bevor ich so wie du werde, sterb' ich lieber ...}
{167}{}{Auch wenn ich alles aufgeben muss, ich schließ' mich deiner Armee an.}
{168}{Mast27}{Dein Humor wird dich nicht retten. Nimmst du mein Angebot an? Nicht? Nimm an! Nicht?}
{169}{}{Nein.}
{170}{}{Okay, ist doch noch besser als sterben.}
{171}{Mast28}{Strahlung schadet uns nicht. Das FEV-Virus macht uns immun. Dein Argument ist schwach ... genau wie du.}
{172}{Mast29}{Oh, da täuschst du dich. Doch zur Sicherheit lasse ich diese Sache prüfen, nachdem ich mit dir fertig bin. Fertig! Fertig! Fertig!}
{173}{Mast30}{Mein einziges Problem bist du. Also, wirst du der Einheit dienen oder nicht?}
{174}{}{Nein.}
{175}{}{Klar doch!}
{176}{Mast31}{Ihre Frechheiten werden bestraft. Ha!}
{177}{}{Du willst sie also alle töten?}
{178}{}{Dann muss ich dich jetzt stoppen!}
{179}{Mast32}{Natürlich nicht. Die meisten erhalten die Chance, ein Mutant zu werden. Wer diese Möglichkeit ablehnt, wird sterilisiert und entlassen. Wer sich widersetzt, wird exekutiert.}
{180}{}{Du bist doch krank im Kopf. Höchste Zeit, dich auszuschalten!}
{181}{}{Wenn das so ist ... Ich trete bei!}
{182}{Mast33}{Jeder ist befangen, nicht wahr? Jeder denkt mehr an seine eigene Gemeinschaft als an andere Leute. So war es immer, und ich sag' dir noch etwas ...}
{183}{}{Und das wäre?}
{184}{Mast34}{Nichts wird sich ändern. Nicht bevor wir ein Volk sind. Eins! Eins! Eins! Eine Rasse. Eine! Eine! Eine! Die Einheit macht es möglich, diese Nichtigkeiten zu vergessen und an die wahren Probleme zu denken. Du willst doch auch dazugehören. Dazu? Oder nicht?}
{185}{}{Du hast mich überzeugt. Ich trete der Einheit bei.}
{186}{}{Ich sag' dir, was ich will ... Deinen Kopf!}
{187}{Mast35}{Natürlich, die Mutanten überleben. Die Mutanten bauen die Welt wieder auf. Und nur als Mutant wirst du leben können. Leben? Sterben?}
{188}{}{Leben!}
{189}{}{Sterben!}
{190}{}{Dich Schurken interessieren doch nur die Mutanten und die Einheit.}
{191}{Mast36}{Ich bin kein Schurke! Du weißt nichts über mich oder die Einheit. Einheit! Einheit!}
{192}{}{Dann klär mich auf!}
{193}{}{Du bist ein Schurke. Du leugnest gerade deine innersten Gefühle.}
{194}{Mast37}{Ich muss mich dir nicht beweisen. Denk nach, und du siehst ein, dass ich kein Schurke bin. Es wäre hoffnungslos, es dir zu erklären.}
{195}{Mast38}{Oh! Und welcher Plan wäre das bitte?}
{196}{}{Ein Gerät hier in der Vault ist mit einem nuklearen Sprengsatz verbunden, der in Kürze hochgehen wird. Dann fahrt ihr alle zur Hölle!}
{197}{}{Ich werd' dich töten. Dann dürfte es schwer für dich sein weiterzumachen, stimmt's?}
{198}{}{Die Brotherhood of Steel hat Anweisung, hier einzumarschieren, wenn ihr mich gefangennehmt und nicht freilasst. Sie sind jeden Moment hier.}
{199}{Mast39}{Vielleicht ist wahr, was du sagst. Wie auch immer, ich lass dich vorerst gehen.}
{200}{Mast40}{Du lügst. Das wird deine letzte Lüge sein!}
{201}{Mast41}{Moment mal ... Ich prüfe deine Geschichte. Vielleicht ist wahr, was du sagst. Achtung! Wachen! Führt diesen Menschen zum Reaktorkern. Beseitigt das Problem, bevor es zu spät ist.}
{202}{Mast42}{Ich glaube, nicht einmal das FEV hilft dir. Was red' ich da? Du verstehst es ja doch nicht.}
{203}{Mast43}{Machst du Scherze?}
{204}{Mast44}{Nun reißt mir aber die Geduld mit dir. Schließt du dich jetzt der Einheit an oder nicht? Eingabe: Ja! Eingabe: Nein!}
{205}{}{Ja.}
{206}{}{Nein.}
{207}{Mast45}{Gut, dann stirbst du auf der Stelle!}
{208}{Mast46}{Du hast das Gerät entschärft. Sehr gut! Sag, willst du noch etwas sagen, bevor ich dich töte?}
{209}{}{Ja. Kann ich doch noch beitreten?}
{210}{}{Sogar tot sehe ich noch besser aus als du.}
{211}{Mast47}{Nein! Nein! Nein! Nein!}
{212}{Mast200}{Ich bin der Meister. Ich muss dir nicht antworten.}
{213}{Mast201}{Es ist nicht an dir, Fragen zu stellen. Du sollst mir nur antworten!}
{214}{Mast202}{Wenn ich erst den Standort deiner Vault weiß, wird sich mein Schicksal erfüllen! Schicksal! Schicksal! Schicksal!}
{215}{Mast203}{Du denkst, du kannst mich zerstören? Zerstören! Mich?}
{300}{}{Däh!}

# Master Tell-Me-Abouts generic response
{980}{Mast200}{Ich bin der Meister. Ich muss dir nicht antworten.}
#
# Master Tell-Me-Abouts
#
{1000}{}{Einheit}
{1001}{}{Meister}

{1100}{Mast200}{Ich bin der Meister. Ich muss dir nicht antworten.}
{1101}{Mast201}{Es ist nicht an dir, Fragen zu stellen. Du sollst mir nur antworten!}

