{100}{}{aus}
{101}{}{Verbleibende Zeit:  }
{102}{}{ Sekunden.}
{103}{}{Hier würde man dich wohl als tot betrachten.}
{104}{}{aus}
{105}{}{ein}
{106}{}{aus}
{107}{}{Verbleibende Zeit:  }
{108}{}{ Sekunden.}
{109}{}{Hier würde man dich wohl als tot betrachten.}
{110}{}{Verbleibende Zeit: }
{111}{}{ Sekunden.}
{112}{}{Hier würde man dich wohl als tot betrachten.}
