{100}{}{You see Michelle.}
{101}{}{}
{102}{}{}
{103}{}{You see a member of the Blades.}
{104}{}{You see a member of the Blades.}
{105}{}{You think that might be Books.}
{106}{}{You think that might be Scars.}
{107}{}{You think that might be Gunner.}
{108}{}{You think that might be Twitch.}
{109}{}{You think that might be Hammer.}
{110}{}{You think that might be Razor.}
{111}{}{What are you doing here?}
{112}{}{Hhrrrnnn.}
{113}{}{Nothing. Honest.}
{114}{}{I'm just looking around.}
{115}{}{This! *smack*}
{116}{}{A moron. I think that you'd best get out of here. Otherwise,
 you may become target practice.}
{117}{}{Arroo!}
{118}{}{Arook.}
{119}{}{Nothing, eh? I think you're hiding something. Out with it
 before you see your guts.}
{120}{}{I'm really a Martian.}
{121}{}{I'm here to stop the gang wars.}
{122}{}{I'm not up to anything.}
{123}{}{I'm up to THIS! *smack*}
{124}{}{Everyone knows there are no such things as Martians.
 All real aliens are from Venus. Now, you die!}
{125}{}{Sure, and I'm the Queen of Mexico.}
{126}{}{Honest. I want to stop the wars so I can help Adytum.}
{127}{}{Your Majesty, I truly seek to end the wars.}
{128}{}{If your intelligence were greater, I would try to
 explain the benefits of peace.}
{129}{}{If you're here to do that, then you'll need to try and find
 Razor. She'll let you know what we think of that.}
{130}{}{Uh, thanks. I think.}
{131}{}{Okay. Good bye.}
{132}{}{Mock me, will you? I guess I should expect as much from a
 child. Oh, by the way. Here!}
{133}{}{Fancy talk will only get you so far. Here, it will get
 you about six feet under.}
{134}{}{If you are up to nothing, then we will put you up to
 something. I think 'target' makes a good something.}
{135}{}{You looked. Now, what do you want? Think quick. It may mean
 the difference between walking out of here and becoming
 a permanent resident.}
{136}{}{I'd like to live here.}
{137}{}{I'm really a Ripper in disguise.}
{138}{}{I want to bring peace to the gangs.}
{139}{}{Leaving.}
{140}{}{Nothing special. Just looking at the garbage to be
 recycled.}
{141}{}{We never said anything about living. You would just
 reside here. Indefinitely. Enjoy your stay.}
{142}{}{I'm glad you said that. I've been meaning to sharpen this. }
{143}{}{Soon I will have a hide to sharpen it on.}
{144}{}{Not so fast. The only way someone leaves here is if they
 are a Blade, or in a bag.}
{145}{}{Then I want to be a Blade.}
{146}{}{How big is this bag?}
{147}{}{You forget the third option. Me!}
{148}{}{Fat chance. But, he's a test. If you can find Razor, then
 you can talk to her about that.}
{149}{}{Big enough to stuff your body parts in when we finish.}
{150}{}{I am not Sleeping Beauty. I do not need to be awakened.
 Get out or die.}
{151}{}{Hear you're out for the bastard's head. Give him an extra
 knife twist for me.}
{152}{}{Welcome back. The Hole is open and ready to house you once more.}