{100}{}{Du siehst einen misshandelten Mann.}
{101}{}{Ich danke dir, Fremder! Ich weiß nicht wieviele Wochen oder sogar Monate
 diese Schlägertypen mich hier gefangengehalten haben. Ich bin dir sehr dankbar für deine
 Hilfe und bin sicher die Brotherhood of Steel empfindet genauso.}
{102}{}{Brotherhood of Steel?}
{103}{}{Ich bin froh, dass ich helfen konnte.}
{104}{}{Bist du in Ordnung?}
{105}{}{Ich komme von der Brotherhood. Ich hab nach dir gesucht.}
{106}{}{Bitte. Wiedersehen.}
{107}{}{Ah.}
{108}{}{Du hast noch nie von uns gehört? Das überrascht mich nun wirklich. Du kommst
 wohl nicht oft aus dem Hub raus. Du solltest öfter mal rausgehen. Wir befinden uns
 nordwestlich von hier, auf der westlichen Seite der Gebirgskette.}
{109}{}{Ich bin wirklich froh darüber, dass du mir hilfst, aber warum versuchst du, mich
 anzulügen? Du kannst dir doch denken, dass ich jedes Mitglied unseres Ordens kenne.}
{110}{}{Talus hat mich gesandt.}
{111}{}{Naja, du kennst mich nicht, weil ich noch nicht lange dabei bin.}
{112}{}{Du weißt doch gar nicht, was du da redest.}
{113}{}{Danke noch mal! Wenn du bei der Brotherhood vorbeikommst, wär´s nett, wenn du
 Talus sagen könntest, dass es mir gutgeht. Er hat sich bestimmt Sorgen gemacht. Ciao und
 pass gut auf dich auf.}
{114}{}{Oh, jetzt geht´s mir wieder gut, danke. Ich habe Freunde hier, bei denen ich
 bleiben kann, bis ich wieder bei Kräften bin. Ich werd versuchen, der Brotherhood die
 Nachricht zu schicken, dass ich jetzt, dank deiner Hilfe, wieder in Sicherheit bin. Wiedersehen.}
{115}{}{Wie... oh, tut mir leid. Du musst diesen "Test" der Elder gemacht haben. Das hab
 ich total vergessen. Ich bin dir zutiefst dankbar. Ich bin froh, dass du niemals aufgegeben hast.
 Ich war ständig in Lebensgefahr. Es muss dich einige Zeit gekostet haben, mich aufzuspüren. Die
 Stadt ist riesengroß. Außerdem hast du sicher viele Hindernisse überwinden müssen.}
{116}{}{Naja,... ich bin halt einfach gut.}
{117}{}{Eigentlich war es gar nicht so schwer. Talus hat gewusst wo du hin bist.}
{118}{}{Glück gehabt, schätz ich.}
{119}{}{Gut, ist schon in Ordnung. Ich bin froh, dass ich dich gefunden hab.}
{120}{}{Oh... Also, ich bin einfach dankbar.}
{121}{}{Ich glaub schon. Du hast wirklich gute Arbeit geleistet.}
{122}{}{Ich bin froh, dass ich helfen konnte.}
{123}{}{Bist du in Ordnung?}
{124}{}{Danke noch mal. Ich habe Freunde hier, bei denen ich bleiben kann, bis ich
 wieder bei Kräften bin. Übrigens werd ich die Augen offenhalten. Ich hab gehört, wie
 meine "Gastgeber" sich über einen Thieves' Circle unterhalten haben. Ich denke,
 wir befinden uns in der Nähe ihres Gebiets. Das ist vermutlich der Grund für
 ihren Plan, woanders hinzugehen. Wiedersehen.}
{125}{}{Also ich bin froh, dass du Glück hattest. Ich hab schlimme Sachen über
 die Old Town gehört. Die Skags sind unheimlich und ich denke, es ist was anderes.}
{126}{}{Egal, was du sagst. Ich bin einfach glücklich darüber, wieder frei zu
 sein. Die Folter war furchtbar.}
{127}{}{Nein, ich bin wirklich von Talus gesandt worden.}
{128}{}{Ich bin froh, dass ich helfen konnte.}
{129}{}{Bist du in Ordnung?}
{130}{}{Ich fürchte nein. Ich hab Gedächtnislücken. Ich glaub, sie haben mir was
 ins Essen gemischt.}
{131}{}{Nein, ich bin wirklich von Talus gesandt worden.}
{132}{}{Ich bin froh, dass ich helfen konnte.}
{133}{}{Bist du in Ordnung?}
{134}{}{Hallo.}
{135}{}{Ich werd bald gehen. Muss nur erst wieder zu Kräften kommen.}
{136}{}{Danke noch mal.}

## Tell Me Abouts
{980}{}{Ich bin wirklich nicht in der Stimmung zu reden.}
{981}{}{Entschuldigung, aber ich bin wirklich nicht in der Stimmung zu reden.}

{1000}{}{Brotherhood}
{1001}{}{Steel}
{1002}{}{Talus}

## Answers
{1100}{}{Die einzige Rettung, die es für diesen gepeinigten Planeten und seine Bewohner gibt.
 Ohne sie würde die Menschheit mit Sicherheit ausgerottet werden.}
{1101}{}{Die einzige Rettung, die es für diesen gepeinigten Planeten und seine Bewohner gibt.
 Ohne sie würde die Menschheit mit Sicherheit ausgerottet werden.}
{1102}{}{Er ist mein Lehrer und ein ganz großartiger Mann. Ich hoffe, dass ich ihn noch einmal
 wiedersehe.}
