{100}{}{Du siehst einen Techniker. Er arbeitet gewissenhaft für die Einheit und den Meister.}
{101}{}{Wir machen die Arbeit des Meisters.}
{102}{}{Wir machen die Arbeit des Meisters und dürfen nicht gestört werden!}
{103}{}{Meister! Ein Eindringling!}
{200}{}{Du siehst Viscious, einen Supermutantenführer. Er sieht böse aus.}
{201}{}{Du siehst einen bösartig aussehenden Supermutanten.}
{202}{}{Der Wille des Meisters siegt. Welche Neuigkeiten bringst du?}
{203}{}{Hng!}
{204}{}{Ach, der Krieg läuft ganz gut.}
{205}{}{Ich hab' eine Nachricht für den Meister von seinem Leutnant. Ich muss sofort den Meister
 sprechen.}
{206}{}{Die einzige Nachricht, die ich habe, ist, dass du gleich zu Düngemittel verarbeitet wirst.}
{207}{}{Ein Eindringling!}
{208}{}{Dein Verhalten verrät dich, Eindringling. Ich mach' meine Drohung jetzt wahr.}
{209}{}{Das kann nicht dein Ernst sein. Ja, du musst lügen.}
{210}{}{Hä, ja, na und?}
{211}{}{Nein. Der Leutnant konnte diese Nachricht nicht auf die übliche Art und Weise überbringen. Ich muss den Meister unbedingt sofort sprechen! Wir dürfen keine Zeit verlieren!}
{212}{}{Dann geh' durch diese Tür, und pass' im Korridor auf. Ich nehm' an, du hast eine Waffe dabei?}
{213}{}{Klar. Danke. Sieg der Einheit.}
{214}{}{Nein, ehrlich gesagt nicht. Ist das wichtig?}
{215}{}{Natürlich! Du glaubst doch nicht, dass du ohne Schutz durch den Korridor kommst? Was hast du mit deinem Annullierer gemacht?}
{216}{}{Ich hab' ihn in meinen anderen Klamotten vergessen.}
{217}{}{Der Leutnant hatte keine Zeit mir einen zu geben.}
{218}{}{Ah, er hat auch noch Humor, das gefällt mir. [hält inne] Ich hab' natürlich keinen, ist ja klar. Du musst dir bei den Gehirnwäschern auf dem zweiten Level einen besorgen. Sieg der Einheit.}
{219}{}{Dann war er ein Narr, oder du bist nicht der, der du vorgibst zu sein. Was ist los?}
{220}{}{Natürlich ist er ein Narr.}
{221}{}{Der zweite Teil.}
{222}{}{Geh' schon und beende deine Mission. Ich hab' keine Zeit für dich.}
{300}{}{In der Ecke des Zimmers befindet sich ein kleiner Haufen Zigarettenkippen.}
{301}{}{Der Supermutant geht auf die eine Seite des Zimmers und zündet sich eine Zigarette an.}
{302}{}{Du siehst einen Supermutanten mit einer Zigarette, die in seinem Mundwinkel hängt.}
{303}{}{Der Supermutant schnippt die Zigarettenkippe in die Ecke.}
