#############################################################
#  Message File: ktgoo.msg                                  #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: March 1, 1998                                   #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Du siehst toxischen Glibber.}
{101}{}{Du siehst toxischen Glibber.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

{110}{}{Autsch; dieser Glibber brennt.}
{120}{}{Diese alten Gummistiefel lassen diesen ekligen Glibber sicher nicht durch.}
{130}{}{Deine Stiefel sind gerade geschmolzen.}
{140}{}{Deine Füße fangen an zu brennen und zu jucken.}
{150}{}{Deine Füße fangen an, wirklich sehr zu brennen und zu jucken, aber dann fühlen sie sich wieder besser an.}