{100}{}{Du siehst einen kaputten Roboter.}
{101}{}{Du siehst einen funktionsfähigen Roboter.}
{102}{}{Du reparierst den kaputten Roboter. Er lädt sich sofort auf
 und erwacht zu neuem Leben.}
{103}{}{Die Reparaturen übersteigen deine Fähigkeiten.}
