{100}{}{Der Weg nach Norden ist durch Trümmer und Schutt versperrt. Du musst
 einen anderen Weg finden.}
{101}{}{Der Weg nach Süden ist durch Trümmer und Schutt versperrt. Du musst
 einen anderen Weg finden.}
{102}{}{Der Weg nach Osten ist durch Trümmer und Schutt versperrt. Du musst
 einen anderen Weg finden.}
{103}{}{Der Weg nach Westen ist durch Trümmer und Schutt versperrt. Du musst
 einen anderen Weg finden.}
{104}{}{Der Weg geradeaus ist durch Trümmer und Schutt versperrt. Du musst
 einen anderen Weg finden.}
