{100}{}{Du siehst Orfeo, ein ehrwürdiges Mitglied der Children of the Cathedral.}
{101}{}{Aah. Ein frisch Bekehrter. Willkommen.}
{102}{}{Mich töten!!!}
{103}{}{Ich bin kein Bekehrter!}
{104}{}{Danke Bruder.}
{105}{}{Dann sollten wir das Problem bald in Angriff nehmen.}
{106}{}{Zuerst müssen wir die Verunreinigungen des Ödlandes von dir abwaschen. Komm.}
{107}{}{Wir werden dich reinigen!}