{100}{}{Paladin}
{101}{}{Du hast hier nichts verloren, Neuling.}
{102}{}{Was machst du hier drinnen?}
{103}{}{Der Wachraum ist für die Wachen bestimmt. Du bist aber keine Wache. Trotzdem bist du im Wachraum. Also: Verschwinde.}
{104}{}{Bitte geh'. Du hast hier nichts zu suchen.}
{105}{}{Hey, kein Zutritt für Neulinge.}
{106}{}{Das hier ist nicht die Bibliothek, mein Junge. Wenn du in Büchern herumstöbern  möchtest, dann geh' in die Bibliothek.}
{107}{}{Das hier ist nicht die Bibliothek, meine Frau. Wenn du in Büchern herumstöbern möchtest, dann geh' in die Bibliothek.}
