{100}{}{Du siehst einen Bauern.}
{101}{}{Oh, sieh an, so ein großer Mann und rennt vor einem verängstigten Hund davon. Tja, Phil, ich hab's gesehen. Ich hab's wirklich gesehen.}
{102}{}{Was machst du, Phil? Testest du das Profil deiner Turnschuhe, oder was?}
{103}{}{Mann, der Hund sieht ganz schön hungrig aus. Er verschlingt dich bestimmt bei lebendigem Leib, Phil.}
{104}{}{Das sind etwas harte Geschütze, die du da für einen armen, hilflosen Hund auffährst, findest du nicht?}
{105}{}{Einen feinen Hund hast du da.}
{106}{}{Ich bin sicher, Phil wäre sehr dankbar, wenn du ihn von diesem Köter befreien könntest.}
{107}{}{Danke für deine Hilfe mit dem Hund.}