{100}{}{Du siehst einen Bauern.}
{101}{}{Ich hab' dir nichts zu sagen, Fremder.}
{102}{}{In dieser Jahreszeit stinken die Brahmin wirklich bis zum Himmel.}
{103}{}{Wir müssen die Bewässerung noch ausweiten.}
{104}{}{Nerv mich nicht.}
{105}{}{Ich hab' gehört, die Radscorpions haben letzte Nacht wieder getötet.}
{106}{}{Hast du ein paar Brahmin-Burger?}
{107}{}{Ich hatte in letzter Zeit keine Angriffe von den Gangstern zu beklagen. Wahrscheinlich hab' ich einfach Glück gehabt.}