{100}{}{You see Rock.}
{101}{}{You see a man.}
{102}{}{You might want to think about putting that gun away, son.
 The Crypts don't like it when people flash hardware that way.}
{103}{}{Oh, really.  I'll just go have a talk to them about it.  Where are they?}
{104}{}{Oh, ok.  Where can I get a drink?}
{105}{}{Who are the Crypts?}
{106}{}{You look like you could use a cool drink.}
{107}{}{[done]}
{108}{}{Yeah, go to the big building just inside town, and tell 'em Rock sent you.}
{109}{}{Ok.}
{110}{}{The Crypts?  They are the biggest, baddest crew around.
 Don't mess with them, if you want to leave Scrapheap in one piece.}
{111}{}{Where are they?}
{112}{}{They are in the big building just inside the gate.
 You looking for some steady work?  Someplace to use that gun of yours?}
{113}{}{No.}
{114}{}{Yeah, sure am.}
{115}{}{Then I suggest you turn right back around and leave.
 Scrapheap is no place for those who ain't with the Crypts.
 If you want to go in, you can -- but it's your life.}
{116}{}{Ok.}
{117}{}{Great.  Tell them Rock sent you, up at the big house.}
{118}{}{Ok.}
{119}{}{Glad to hear that you are on the good side in Scrapheap.
 Welcome to the gang.}
{120}{}{Thanks.}
{121}{}{You made a mistake.  A terrible, terrible mistake.}
{122}{}{Welcome to Scrapheap, son.  Don't be a fool, and you will do ok.}
{123}{}{Thanks, what is this place?}
{124}{}{Who's in charge here?}
{125}{}{Scrapheap is the armpit of the desert.
 No better place to raise children, in my opinion.
 [Chuckles]  This place makes Junktown look like a living city of the ancients.}
{126}{}{Thanks.}
{127}{}{Well, there is a commune, run by Lex.  But the real power
 is always behind the throne.  In this case, the people
 not to mess around with are the Crypts.}
{128}{}{Thanks.}
{129}{}{Well, you sure do ask a lot of questions.  I think you
 should just move along now.}
{130}{}{Ok.}
{131}{}{[done]}
{132}{}{The Crypts will bury you!}
{133}{}{Fools got no reason to live.}
{134}{}{The Foolish shall perish.}
{135}{}{Look who got hit with the ugly stick.}
{136}{}{You might want to think about putting that gun away. The Crypts don't like it when people flash hardware that way.}
{137}{}{Welcome to Scrapheap.  Don't be a fool, and you will do ok.}
