{100}{}{Du siehst eine Wache der Brotherhood.}
{101}{}{Du hast hier nichts verloren.}
{102}{}{Was willst du hier?}
{103}{}{Der Wachraum ist für die Wachen bestimmt. Du bist keine Wache. Du bist im Wachraum. Deswegen solltest du verschwinden.}
{104}{}{Geh bitte, du hast hier nichts verloren.}
{105}{}{Hey, Neulinge haben keinen Zutritt.}
{106}{}{Hier ist nicht die Bibliothek, mein Junge. Geh in die Bibliothek, wenn du in Büchern  herumstöbern willst.}
{107}{}{Hier ist nicht die Bibliothek, mein Mädchen. Geh in die Bibliothek, wenn du in Büchern  herumstöbern willst.}
