{100}{}{Das Bücherregal ist voller zerfledderter Romane.}
{101}{}{Das Bücherregal ist voller zerfledderter Romane.}
{102}{}{Leider bist du zu sehr unter Zeitdruck, um in einem dieser Romane schmökern zu können.}