{100}{}{Das kann ich auch.}
{101}{}{Das ist einfach.}
{102}{}{Ich zeig' dir, wie's geht.}
{103}{}{Schön.}
{104}{}{Ach so.}
{105}{}{Oh, kein schlechter Zug.}
{106}{}{Ach so geht das.}
{107}{}{Das könnte ich nie.}
{108}{}{Gut in Form.}
{109}{}{Stimmt.}
{110}{}{Pass' auf.}
{111}{}{Benimm' dich.}
{112}{}{Hör' zu.}
{113}{}{Shhhh!}
{114}{}{Geh' mir bitte aus dem Weg.}
{115}{}{Danke.}
