{100}{}{Du siehst die Wasserversorgung von Shady Sands. Dieses Wasser reicht für die Versorgung deiner Vault nicht aus.}
{101}{}{Du hast keinen Grund, den Brunnen hinunterzuklettern, aber vielleicht kannst du mit dem Seil Löcher hinuntersteigen.}
{102}{}{Der Brunnen gibt keine weiteren Informationen preis.}
{103}{}{Als du die Flaschendeckel in das Wasser fallen hörst, wünschst du dir etwas.}
