{100}{}{Du siehst Tandi.}
{101}{}{Was gibt es hier noch so?}
{102}{}{Was kann man hier so machen?}
{103}{}{Hast du irgendwas aus dem Süden gehört?}
{104}{}{Wie gefällt es dir hier?}
{105}{}{Nun, das war's. Danke schön.}
{106}{TAND_1}{Hi! Ich hörte, es sei ein Reisender im Ort, aber war etwas skeptisch, bis ich dich sah. Ich bin Tandi. Und du?}
{107}{}{Ich heiße }
{108}{}{.}
{109}{}{Mein Name ist }
{110}{}{. Vergiss ihn nicht!}
{111}{}{Hääh?}
{112}{tand_2}{Magst du unseren kleinen Ort? Gelangweilt?}
{113}{}{Ist ganz in Ordnung. Kann ich dich vielleicht was fragen?}
{114}{}{Und wie! Hier kann man nichts machen, außer den Brahma bei der Paarung zuzusehen.}
{115}{}{Ist wahrscheinlich ganz okay, denk' ich.}
{116}{}{Ja, ich bin schon etwas gelangweilt.}
{117}{TAND_3}{Ja, ich war noch nie woanders, weiß also nicht, wie ich helfen kann. Was brauchst du?}
{118}{TAND_4}{Nun, ja, du lebst nicht hier. Man kann hier nichts Gescheites tun, und glaub mir, Brahma-Tippen wird ganz schnell fad.}
{119}{}{Wenn's so langweilig ist, warum gehst du nicht einfach weg von hier?}
{120}{}{Du übertreibst bestimmt.}
{121}{}{Scheint ruhig und sicher zu sein hier.}
{122}{TAND_5}{Ich? Weg? Schön wär's! Ich weiß zu wenig, um allein zu gehen, keiner will mit. Und mein Vater sagt, er kriegt 'nen Herzanfall, wenn was passiert!}
{123}{}{Schwierige Lage. Kann ich dich vielleicht noch was fragen?}
{124}{}{Zu dumm, ich muss gehen. Mach's gut!}
{125}{TAND_6}{Ahh ... Ich muss mich mal hier rüberstellen.}
{126}{TAND_12}{Leb du mal dein ganzes Leben hier! Willst du noch was wissen?}
{127}{TAND_13}{Ja, echt, sicher ... Und so fad, dass ich glaub', mein Hirn kommt mir bald zu den Ohren raus.}
{128}{}{Warum gehst du nicht einfach weg von hier?}
{129}{}{Das tut mir leid. Ich hab's leider eilig, kann ich dich noch schnell was fragen?}
{130}{TAND_14}{Endlich! Noch wer, der's kapiert! Sicher warst du schon überall, dann muss dies für dich die Hölle sein.}
{131}{}{Wenn's so langweilig ist, warum gehst du nicht einfach weg von hier?}
{132}{}{Du übertreibst bestimmt.}
{133}{}{Scheint ruhig und sicher zu sein hier.}
{134}{TAND_15}{Junktown ist südwestlich, doch weiß ich nicht, wie weit. Darunter ist ein schauriger Ort, die City of Death. Oh, oh ja ... Dann gibt's noch 'nen Ort ... Oh, Mist, wie war das? Ach ja! Der Hub.}
{135}{tand_15a}{Im Süden sind viele Städte. Doch da du so weit gereist bist, weißt du das bestimmt schon.}
{136}{}{Danke.}
{137}{TAND_16}{Schon gut. Noch was?}
{138}{TAND_20}{Es gibt Radscorpions. Ich weiß, es ist nicht gerade gut, aber noch ist niemand gestorben. Und sie sind das Aufregendste, was wir haben!}
{139}{TAND_21}{Nicht viel, seit du die Radscorpions gekillt hast. Mann, hätte ich das gern gesehen!}
{140}{TAND_22}{So wie immer. Fa-de!}
{142}{tand_23b}{Zeug ...}
{141}{tand_23g}{Die schlimmste Geschichte ist die über die Deathclaw.}
{143}{}{Danke.}
{144}{}{Die Deathclaw?}
{145}{TAND_24}{Schon okay. Gut, es ist Heimat und so, aber es ist so fad! Ich will die Welt sehen!}
{146}{}{Wenn's so langweilig ist, warum gehst du nicht einfach weg von hier?}
{147}{}{So schlimm wird's schon nicht sein.}
{148}{}{Scheint ruhig und sicher zu sein hier.}
{150}{tand_27f}{Hör mal ... äh ... aber ich ... äh ... ich ... ich mag Jungs, okay? Äh ... 'tschuldige, ich hab' viel zu tun.}
{149}{tand_27m}{So ein Mädchen bin ich nicht, ja? Such dir 'ne Brahma oder sowas.}
{151}{TAND_28}{Also ... vielen Dank. Fremde sind nur selten hier, und ich höre gern neue Stimmen. Nun ... bis dann!}
{152}{}{Tschüss!}
{153}{TAND_29}{Äh, hör mal. Ich muss gehen und nach den Brahma sehen. Schön ... hmm ... mit dir zu reden.}
{154}{tand_30a}{Hallo noch mal! Wie kann ich dir jetzt helfen?}
{155}{}{Kann ich dir noch ein paar Fragen stellen?}
{156}{}{Nichts. Tschüss dann!}
{157}{TAND_35}{Ähh ... He, danke. Später!}
{158}{TAND_36}{Hi! Ich hatte Angst, dass du weg bist und ich dir nicht mehr dafür danken kann, dass du mich gerettet hast. Oh, das war toll! Action, Abenteuer ... Wenn ... wenn ich etwas für dich tun kann, lass es mich wissen.}
{159}{}{Vielleicht könntest du mir noch ein paar Fragen beantworten.}
{160}{}{Wie wär's, wenn du und ich ... naja ... du weißt schon.}
{161}{}{Danke, das war's.}
{162}{}{Däh!}
{163}{TAND_37}{Wer bist du? Was willst du?}
{164}{}{Ich heiße }
{165}{}{. Dein Vater schickt mich.}
{166}{}{Deine Märchenprinz! Was hast du denn gedacht?}
{167}{}{Däh!}
{168}{TAND_38}{Vater schickt dich!? Willst du mich befreien?}
{169}{}{Ja. Also halt dich bereit. Ich werd' dich hier rausholen.}
{170}{}{Nein, ich wollte nur gucken, wie du aussiehst!}
{171}{TAND_39}{Und? Wie ist der Plan?}
{172}{}{Warte, bis die Türen aufgehen. Dann renn um dein Leben!}
{173}{}{Ich kämpfe gegen den Khan-Anführer um deine Freiheit.}
{174}{TAND_40}{Das war's? Das ist dein Plan? Na gut, beeil dich! Ich hörte sie reden, und was ich hörte, war schlimm.}
{175}{TAND_41}{Du? Gegen ihn? Du machst wohl Scherze! [Sie seufzt.] Hör zu, wenn du einen neuen Plan hast, sag Bescheid, okay?}
{176}{TAND_42}{Oh ... sind wir jetzt sarkastisch? Holst du mich jetzt raus oder was!?}
{177}{}{Klar doch. Warte, bis die Türen aufgehen. Dann renn um dein Leben!}
{178}{}{Ich kämpfe gegen den Khan-Anführer um deine Freiheit.}
{179}{TAND_43}{Oh, du bist's wieder! Holst du mich jetzt raus?}
{180}{}{Ja. Also halt dich bereit. Ich werd' dich hier rausholen.}
{181}{}{Nein, ich wollte nur kurz hallo sagen.}
{182}{}{Däh!}
{183}{tand_43a}{Hallo!? Verstehst du mich? Kannst du mich hier rausholen? Kannst du MICH HIER RAUSHOLEN!}
{184}{tand_43b}{Wir haben keine Zeit zum Reden, wir müssen hier raus!}
{185}{TAND_44}{Aradesh ist mein Papa. Nicht übel für einen Vater.}
{186}{TAND_45}{Na ich! Was hast du denn gedacht?}
{187}{TAND_46}{Razlo ist der alte Kerl im Osten der Stadt. Er ist ein ganz guter Arzt, obwohl er steinalt ist.}
{188}{TAND_47}{Seth ist der Hauptmann der Wachen. Mein Vater wollte uns verkuppeln, doch ... er ist nicht mein Typ.}
{189}{TAND_48}{Agatha ist die Älteste. Wir alle lieben sie und ihre Geschichten. Schau mal bei ihr rein, wenn du Unterhaltung willst.}
{190}{TAND_49}{Ganz übler Haufen, hab' ich gehört. Mein Vater weiß mehr über sie. Er erzählt nie viel von der Welt da draußen.}
{191}{TAND_50}{Dort kommt unser Wasser her. Er war da, bevor ich zur Welt kam.}
{192}{TAND_51}{Ich hab' mal einen gesehen, allerdings nur von weitem. Gemeine Biester mit Scheren und einem Stachel. Ihr Gift kann tödlich sein, wenn man nichts unternimmt. Frag mal meinen Papa, Aradesh, er weiß mehr darüber.}
{193}{TAND_52}{Ein Reisender aus dem Süden hat's mir erzählt. Er sagte, die Deathclaw sei eine Bestie, die nachts Menschen tötet. Niemand kann sie fangen, weil sie verschwinden kann wie Rauch. Natürlich ... glaub' ich das nicht.}
{194}{TAND_53}{Junktown ist eine Stadt im Südwesten. Man sagt, es gibt dort regen Handel, aber mein Vater will davon nichts wissen. Er sagt, wir müssen 'geschützt' bleiben. Von wegen! Wir sind eingesperrt!}
{195}{TAND_54}{Der Hub soll eine tolle Stadt im Süden sein. Ich wollte schon immer mal hin, aber es hat nie geklappt.}
{196}{TAND_55}{Weiß nicht, aber der Kerl, der das sagte, hatte echt Angst davor. Da sind Untote auf den Straßen!}
{197}{TAND_62}{Ich weiß nicht. Frag mal Seth oder meinen Vater danach.}
{198}{TAND_63}{Hmm ... Sagt mir nichts.}
{199}{TAND_64}{Hmmmm ... nee! Nie davon gehört.}
{200}{TAND_65}{He! Was machst du denn da? Stell das hin!}
{201}{TAND_66}{Das war's! Das sag' ich meinem Vater!}
{202}{TAND_67}{Was zum Teufel machst du da? Lass das!}
{203}{TAND_68}{Was machst du denn hier? Geh, bevor mein Vater aufwacht!}
{204}{TAND_69}{Wie gesagt ...}
{205}{TAND_70}{Hör zu, ich sagte doch schon ...}
{206}{TAND_71}{Noch mal?! Hallo?! Wie oft muss ich dir das denn noch sagen? Hast du Watte in den Ohren oder was?}
{207}{TAND_72}{Ja, ich hab' davon gehört, aber geh lieber zu Agatha. Sie weiß mehr als ich.}

{208}{}{Lass uns von hier verschwinden.}
{300}{}{Wau! Nichts geht über Shady Sands!}
{301}{}{He, was ist das da drüben?}
{302}{}{Ich kann es kaum erwarten, den Menschen in Shady Sands über die Welt da draußen zu berichten.}
{303}{}{Hast du noch mehr Radscorpions gesehen?}
{304}{}{Wohin gehen wir jetzt?}
{305}{}{Wann werden wir dort ankommen?}


#
# Sex msgs, by Sduibek for Fallout Fixt:
#
{350}{TAND_16a}{Ja, was auch immer.}

{399}{}{[Folge ihr]}
{407}{}{[Weiter]}
{412}{}{[Sie lächelt und führt dich in ihr Zimmer]}

{400}{TAND_3}{Ja, ich war noch nie woanders, weiß also nicht, wie ich helfen kann. Was brauchst du?}
# no {401}{TAND_29}{[Über die Schulter, so das Aradesh sie hören kann] Äh, hör mal. Ich muss gehen und nach den Brahma sehen. Schön ... hmm ... mit dir zu reden. [Dreht sich zu dir zurück und winkt dir, ihr zu folgen ...]}

{402}{TAND_28}{Also ... vielen *Dank*. [Sie zwinkert dir zu und lächelt] Fremde sind nur selten hier, und ich *höre* gern neue Stimmen. Nun ... bis dann!}
# probably not {403}{TAND_35}{Ähh ... He, danke. Später! [Sie sieht erschöpft aus]}

{404}{}{Etwas, was andere nicht mithören sollen. Lass uns irgendwo stilles zurück ziehen und ich sage es dir...}
{405}{}{Du siehst eher ... unerfahren aus. Ich möchte dir so viel beibringen, wie ich kann. Wir sollten anfangen, es gibt eine Menge zu bedenken. [zwinker]}
{406}{}{[seufz] Mehr als du zur Verfügung stellen kannst, aber es wird schon gehn'.}

{410}{TAND_14}{Endlich! Noch wer, der's kapiert! Sicher warst du schon überall, dann muss dies für dich die Hölle sein. [Sie zuckt die Achseln und führt dich in ihr Zimmer]}

{415}{}{Ich hätte gerne mehr Spaß, wenn du die Zeit dazu hast.}

##############


{980}{TAND_62}{Ich weiß nicht. Frag mal Seth oder meinen Vater danach.}
{981}{TAND_63}{Hmm ... Sagt mir nichts.}
{982}{TAND_64}{Hmmmm ... nee! Nie davon gehört.}

{1000}{}{Aradesh|Vater|Dad|Anführer}
{1001}{}{Tandi}
{1002}{}{Seth|Captain}
{1003}{}{Raiders|Raider|Khans|Khan}
{1004}{}{Brunnen}
{1005}{}{Skorpione|Skorpion|Rad Scorpion|Radscorpions|Radscorpion|Monsters|Monster}
{1006}{}{Claw|DEATHCLAW|DEATHCLAWS|CLAWS}
{1007}{}{Junktown|Junk Town}
{1008}{}{Hub}
{1009}{}{Necropolis|Nekropolis|City of the Dead|City of Dead|City|CoD}
{1010}{}{Razlo|Sanitäter|Arzt|Doktor|Hilfe|Heilung|Verletzt|Verwundet|}
{1011}{}{Sex|Fick|Ficken|Rotators}
{1012}{}{Shady Sands|Shady|Sands|Stadt|Heimat|zu Hause|zuhause}
{1013}{}{Richtung|Richtungen|Wohin|Wo hin}
{1014}{}{Agatha}
{1015}{}{Langweilig}

{1100}{TAND_44}{Aradesh ist mein Papa. Nicht übel für einen Vater.}
{1101}{TAND_45}{Na ich! Was hast du denn gedacht?}
{1102}{TAND_47}{Seth ist der Hauptmann der Wachen. Mein Vater wollte uns verkuppeln, doch ... er ist nicht mein Typ.}
{1103}{TAND_49}{Ganz übler Haufen, hab' ich gehört. Mein Vater weiß mehr über sie. Er erzählt nie viel von der Welt da draußen.}
{1104}{TAND_50}{Dort kommt unser Wasser her. Er war da, bevor ich zur Welt kam.}
{1105}{TAND_51}{Ich hab' mal einen gesehen, allerdings nur von weitem. Gemeine Biester mit Scheren und einem Stachel. Ihr Gift kann tödlich sein, wenn man nichts unternimmt. Frag mal meinen Papa, Aradesh, er weiß mehr darüber.}
{1106}{TAND_52}{Ein Reisender aus dem Süden hat's mir erzählt. Er sagte, die Deathclaw sei eine Bestie, die nachts Menschen tötet. Niemand kann sie fangen, weil sie verschwinden kann wie Rauch. Natürlich ... glaub' ich das nicht.}
{1107}{TAND_53}{Junktown ist eine Stadt im Südwesten. Man sagt, es gibt dort regen Handel, aber mein Vater will davon nichts wissen. Er sagt, wir müssen 'geschützt' bleiben. Von wegen! Wir sind eingesperrt!}
{1108}{TAND_54}{Der Hub soll eine tolle Stadt im Süden sein. Ich wollte schon immer mal hin, aber es hat nie geklappt.}
{1109}{TAND_55}{Weiß nicht, aber der Kerl, der das sagte, hatte echt Angst davor. Da sind Untote auf den Straßen!}
# 1110 added with patch 1.3 from TeamX.
{1110}{TAND_46}{Razlo ist der alte Kerl im Osten der Stadt. Er ist ein ganz guter Arzt, obwohl er steinalt ist.}
{1111}{tand_27m}{So ein Mädchen bin ich nicht, ja? Such dir 'ne Brahma oder sowas.}
{1112}{TAND_24}{Schon okay. Gut, es ist Heimat und so, aber es ist so fad! Ich will die Welt sehen!}
{1113}{tand_15a}{Im Süden sind viele Städte. Doch da du so weit gereist bist, weißt du das bestimmt schon.}
{1114}{TAND_48}{Agatha ist die Älteste. Wir alle lieben sie und ihre Geschichten. Schau' mal bei ihr rein, wenn du Unterhaltung willst.}
{1115}{TAND_24}{Schon okay. Gut, es ist Heimat und so, aber es ist so fad! Ich will die Welt sehen!}

# Fo1in2
{3500}{}{Ich glaube, ich hab' was gebrochen. Schau dir das mal an.}
{3501}{}{Ich fühl' mich fiebrig. Ich glaube ich bin verstrahlt.}
{3502}{}{Ich fühl' mich sehr krank. Ich glaube ich bin vergiftet.}

