{100}{}{Du siehst einen Bürger von Vault 13.}
{101}{}{Wir dachten nicht, dass du zurückkommen würdest. Du hast so ein schönes Zimmer, und es war ein wenig eng bei ihren Eltern. Ich hoffe, du hast nichts dagegen.}
{102}{}{Ja, ich hab' was dagegen. Raus aus meinem Zimmer!}
{103}{}{Nö, ist mir egal. Viel Spaß damit.}
{104}{}{Es wäre schön, wenn ich meine eigene Unterkunft zurück haben könnte. Sucht euch bitte ein anderes Zuhause.}
{105}{}{Hng.}
{106}{}{Hör' zu, ich möchte keinen Streit, aber ganz offensichtlich verdienst du dieses Zimmer nicht mehr. Geh' bitte.}
{107}{}{Wir könnten den Platz wirklich gebrauchen. Ich hoffe, du überlegst es dir noch mal.}
{108}{}{Also, lass' mich einen Augenblick überlegen. Hmmm. Nein. Raus!}
{109}{}{Also, OK. Ihr habt es nötiger als ich.}
{110}{}{Danke! Wir wissen das wirklich zu schätzen. Deine Sachen legen wir in die Truhe.}
{111}{}{Also, ich weiß nicht. Du scheinst es nicht sehr oft zu benutzen, und wir könnten den Platz wirklich gebrauchen.}
{112}{}{OK. Nehmt es.}
{113}{}{Ich brauche dieses Zimmer, um mich meiner Herkunft zu erinnern. Und außerdem kann man sich hier gut ausruhen.}
{114}{}{Gott, ich hätte nicht gedacht, dass dir dieses Zimmer noch was bedeutet, nach allem was ich alles gehört habe. Schönen Tag noch. Wir ziehen wieder zu ihrer Mutter.}
{115}{}{Uns gefällt es hier wirklich.}
{116}{}{Geh' lieber. Dieses Zimmer gehört dir nicht mehr.}
