{100}{}{Dieser Computer reinigt das Wasser für die Vault.}
{101}{}{Der Steuercomputer ist ohne den Steuerchip für die Trinkwasseranlage, der sich nicht reparieren lässt, nutzlos. Du brauchst einen Ersatz.}
{102}{}{Du hantierst am Computer herum, kannst aber nichts herausfinden.}
{103}{}{Auf diesem Ding befinden sich viele blinkende Lämpchen.}
{104}{}{Mit dem Ersatzchip scheint der Computer gut zu funktionieren.}
