{100}{}{Du siehst Vree.}
{101}{Vree00}{Entschuldige, du störst meine Meditation. Bitte geh!}
{102}{}{Entschuldigung. Ich komm' dann ein andermal wieder.}
{103}{}{Ich komme später wieder.}
{104}{}{Woher soll ich denn deinen Terminplan kennen?}
{105}{}{Häh?}
{106}{Vree01}{Sprich nicht in diesem Ton! Soll ich einen der Brüder holen, dich Manieren zu lehren?}
{107}{}{Entschuldigung.}
{108}{}{Okay, schon gut.}
{109}{}{Oh, da hab' ich aber Angst!}
{110}{Vree02}{Guten Tag. Ein schöner Tag zum Lernen! Kann ich dir helfen?}
{111}{}{Ich weiß, du bist der Master Scribe, aber was machst du genau?}
{112}{}{Ich hab' eine technische Frage.}
{113}{}{Ähh ...}
{114}{Vree03}{Ich sammle das Wissen unserer Vorfahren für kommende Generationen.}
{115}{}{Interessant! Dann weißt du bestimmt 'ne Menge Zeugs.}
{116}{Vree03a}{Ja, man kann wohl sagen, dass ich 'Zeugs' weiß!}
{117}{Vree17}{Wie kann ich dir helfen?}
{118}{Vree17a}{Fang an!}
{119}{}{Ich muss einen Steuerchip reparieren. Kannst du mir dabei helfen?}
{120}{}{Erzähl mir was über die Waffen, die hier hergestellt werden.}
{121}{}{Ich hab' was von Holo-CDs gehört. Wie kann ich die Daten darauf lesen?}
{122}{}{Wie kann ich mich vor Verstrahlung schützen?}
{123}{}{Wie kommt es zu all diesen Mutationen?}
{124}{Vree18}{Sprich mit den Knights. Sie sollen dir eine meiner neuesten Laserpistolen zeigen.}
{125}{}{Danke.}
{126}{}{Ich hab' da noch eine Frage ...}
{127}{Vree19}{Noch kannst du das heilige Wissen nicht richtig einsetzen.}
{128}{Vree21}{Nimm den PIPBoy 2000 und lies die CDs. Leg die CD ins Gerät ein. Wenn du was über Computer weißt, solltest du's schaffen, die Daten zu lesen.}
{129}{}{Wo kann ich etwas über Computer lernen?}
{130}{}{Danke.}
{131}{}{Kann ich dich noch was fragen?}
{132}{Vree22}{Die Brotherhood bietet einige Lernprogramme an. Hier, ich zeig's dir.}
{133}{Vree23}{Nimm dieses Terminal, um die Grundlagen der Bedienung zu lernen.}
{134}{Vree24}{Du bist nicht sehr helle, oder? Du trägst ein Holo-CD-Laufwerk am Arm!}
{135}{Vree25}{Du brauchst Arznei gegen die Strahlung. Hier! Nimm das sofort, wenn du glaubst, du näherst dich der Strahlung.}
{136}{}{Danke.}
{137}{}{Kann ich dich noch was fragen?}
{138}{Vree26}{Trink nie leuchtendes Wasser.}
{139}{Vree27}{Nach all den nuklearen und biogenetischen Waffen gibt es überraschend wenige Mutationen. Aber wenn wir durchhalten, wird alles wieder gut.}
{140}{}{Wie kommst du darauf?}
{141}{}{Stimmt. Alles wird wieder gut.}
{142}{}{Ich hab' da noch eine Frage ...}
{143}{Vree28}{Die Mutanten, die ich sah, waren steril. Sie können sich nicht mehr fortpflanzen. Wenn wir die Gründe der Mutation loswerden, können wir sie schlicht ... überleben.}
{144}{}{Klingt fast wie ein Plan!}
{145}{}{Interessante Theorie. Gibt's Beweise?}
{146}{}{Ich hab' da noch eine Frage ...}
{147}{Vree29}{Hier, nimm die Holo-CD! Darauf sind die Autopsien von toten Mutanten. Sie zeigen deutlich, dass wohl kein Mutant sich fortpflanzen kann.}
{148}{}{Danke.}
{149}{}{Kann ich dich noch was fragen?}
{150}{Vree30}{Ich sollte dir eigentlich nichts sagen. Vielleicht später, wenn du der Brotherhood treu ergeben bist.}
{151}{Vree31}{Ich glaube, du bist hier falsch! Geh, ich hab' viel zu tun.}
{152}{Vree32}{Du wirst das Wissen zerstören, das uns retten kann!}
{153}{}{Und du und dein Wissen sind als erstes dran!}
{154}{}{Nein, ich verhindere nur, dass es wieder zu einem Atomkrieg kommt.}
{155}{Vree33}{Niemals! Die Brotherhood verhindert, dass es noch mal geschieht!}
{156}{}{Jaja, das sagen alle ... außer dir, denn du bist gleich tot!}
{157}{Vree34}{Wie kann ich dir helfen?}
{158}{}{Ich hab' wichtige Neuigkeiten über Kedrick: Er ist ein Verräter.}
{159}{}{Was würdest du zu Korruption innerhalb der Brotherhood sagen?}
{160}{}{Ähm ...}
{161}{Vree35}{Sehr gut! Ich muss schon sagen, du hast viel gelernt.}
{162}{Vree36}{Kedrick? Er war schon immer ein treues Mitglied der Brotherhood. Du weißt doch nicht mal, was das bedeutet!}
{163}{}{Doch! Kedrick ist ein Verräter und will die Macht an sich reißen.}
{164}{}{Vielleicht ...}
{165}{Vree37}{Bist du da sicher? Dann sollten wir das dem High Elder sagen.}
{166}{Vree38}{Verschone mich mit Andeutungen. Beweis es dem High Elder oder schweig still!}
{167}{Vree39}{Tu, was getan werden muss! Vernichte die Ketzerei und die, die für die Schande verantwortlich sind.}
{168}{}{Auch wenn es sich dabei um ein ehrwürdiges Mitglied der Brotherhood handelt?}
{169}{}{Und wer übernimmt das?}
{170}{Vree40}{Selbst dann. Nur Beweise zählen!}
{171}{}{Kedrick ist ein Verräter. Er will die Elder töten.}
{172}{}{Ich werd's beweisen.}
{173}{Vree41}{Dann müssen wir zum High Elder. Bring den Beweis, und wir sprechen mit ihm.}
{174}{Vree42}{Der High Elder und Rhombus natürlich.}
{175}{Vree43}{Weißt du von dem verschwundenen Neuling? Wie schrecklich!}
{176}{}{Einverstanden.}
{177}{}{Nee.}
{178}{Vree44}{Wenn du ihm helfen kannst, wär' ich dir dankbar.}
{179}{Vree45}{Gute Taten sollten belohnt werden. Hier, nimm! Das ist für deine Hilfe.}
{180}{Vree46}{Oh! Du! Was willst du?}
{181}{}{Ich wollte mich entschuldigen.}
{182}{}{Oh! Bin im falschen Zimmer gelandet!}
{183}{Vree47}{Danke für die Entschuldigung.}
{184}{Vree47a}{Guten Tag!}
{185}{Vree48}{Das klingt nach Produktionsproblemen. Wir forschen und entwickeln nur. Soll dir einer der Knights helfen!}
{186}{}{Trotzdem danke.}
{187}{}{Kann ich dich noch was fragen?}
{188}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{189}{Vree201}{Davon weiß ich gar nichts. Klingt, als ob ich dem nachgehen sollte.}
{190}{Vree202}{Bedaure, nicht mein Fachgebiet. Vielleicht weiß ein anderer Bruder mehr.}
{191}{Vree203}{Wachen! Wachen!}
{192}{Vree204}{Du hast mein Zimmer zerstört!}
{193}{Vree205}{Was machst du da mit meinen Sachen?}
{194}{Vree300)}{Wer? Warte, der Name sagt mir was. Vielleicht ist er ein Anführer von ein paar Mutanten.}
{195}{Vree301}{Ich schätze, du meinst den letzten Atomkrieg. Die Brotherhood tut alles, um wiederherzustellen, was verlorenging.}
{196}{Vree302}{Es sind laserlesbare High-Density-Datenträger aus Fertigkristall. Darauf sind über 4.000 Gigabyte Informationen.}
{197}{Vree303}{Die einzige Rettung für die Bewohner dieses geschundenen Planeten. Ohne uns wird die Menschheit aussterben.}
{198}{Vree304}{Ich weiß nicht. Frag in der Produktion nach.}
{199}{Vree305}{Er hält die Brotherhood auf dem Pfad der Rechtschaffenheit.}
{200}{Vree306}{Er vollstreckt die Wünsche der Elder. Wenn nötig, mit Gewalt.}
{300}{}{Interessant.}
{301}{}{Okay, das sollte reichen.}
{302}{}{Das sollte es tun.}
{303}{}{Gut.}
{304}{}{Ich wusste, es würde funktionieren.}
{305}{}{Wie war die Formel noch mal?}
{306}{}{Der Algorithmus ist falsch. Das kann aber doch gar nicht sein. Irgendwas stimmt mit dem Computer nicht.}
{307}{}{Aha!}
{308}{}{Okay, also wenn wir das machen ... denke ich, wird's funktionieren.}
{400}{}{Du kannst dieses Terminal benutzen, um deine Computerkenntnisse zu verbessern.}
{401}{}{Das Lernprogramm hat sechs Stunden gedauert. Du fühlst dich erschöpft.}

{980}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}

#
# Vree Tell-Me-Abouts
#
{1000}{}{Meister}
{1001}{}{Krieg}
{1002}{}{Disks|Holodisk|Holodisks|Disk|Holo|CD|Holo CD|Holo-CD}
{1003}{}{Brotherhood|BoS|Brotherhood of Steel}
{1004}{}{Steuerchip|Chip|Wasserchip}
{1005}{}{High Elder|Elder}
{1006}{}{Rhombus|Paladin-Anführer|Anführer der Paladine|Anführer der Paladins}
{1007}{}{Exodus}
{1008}{}{Armee|Mutanten|Mutantenarmee}
{1009}{}{Händler}
{1010}{}{Caravan|Verschwundene Caravans|Caravans}
{1011}{}{Hub}
{1012}{}{Children of the Cathedral|Cathedral|Children|CoC}
{1013}{}{Neuling|Neulinge}
{1014}{}{Scribes|Scribe}
{1015}{}{Knights|Knight}
{1016}{}{Paladins|Paladin}
{1017}{}{Holodisk|Holo-disk|Holo-disc|Holodisc|Holo}

{1100}{Vree300}{Wer? Warte, der Name sagt mir was. Vielleicht ist er ein Anführer von ein paar Mutanten.}
{1101}{Vree301}{Ich schätze, du meinst den letzten Atomkrieg. Die Brotherhood tut alles, um wiederherzustellen, was verlorenging.}
{1102}{Vree302}{Es sind laserlesbare High-Density-Datenträger aus Fertigkristall. Darauf sind über 4.000 Gigabyte Informationen.}
{1103}{Vree303}{Die einzige Rettung für die Bewohner dieses geschundenen Planeten. Ohne uns wird die Menschheit aussterben.}
{1104}{Vree304}{Ich weiß nicht. Frag in der Produktion nach.}
{1105}{Vree305}{Er hält die Brotherhood auf dem Pfad der Rechtschaffenheit.}
{1106}{Vree306}{Er vollstreckt die Wünsche der Elder. Wenn nötig, mit Gewalt.}
{1107}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1108}{Vree201}{Davon weiß ich gar nichts. Klingt, als ob ich dem nachgehen sollte.}
{1109}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1110}{Vree201}{Davon weiß ich gar nichts. Klingt, als ob ich dem nachgehen sollte.}
{1111}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1112}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1113}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1114}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1115}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1116}{Vree200}{Sprich bitte mit 'nem anderen Scribe. Ich mache gerade Berichte für die anderen Elder fertig.}
{1117}{Vree302}{Es sind laserlesbare High-Density-Datenträger aus Fertigkristall. Darauf sind über 4.000 Gigabyte Informationen.}
