{100}{}{Du siehst eine Wache der Water Merchants.}
{101}{}{Halt. Nur Mitglieder der Merchants sind in der Nähe des Wasserturms oder der Pumpen zugelassen.}
{102}{}{Du hast hier keine Erlaubnis, geh' jetzt!}
{103}{}{Unbefugten ist der Zutritt zu diesem Bereich verboten. Geh' von den Pumpen weg.}
{104}{}{Geh' zurück, wenn dir deine Haut was wert ist.}
{105}{}{Letzte Warnung. Geh'.}
{106}{}{Du solltest lieber gehen, solange du noch kannst.}
{107}{}{Du hast nur Sekunden, um zu gehen oder erschossen zu werden.}
{108}{}{Bist du taub? Geh' jetzt!}
{109}{}{Jetzt reicht's.}
{110}{}{Wer nicht hören will, muss fühlen.}
{111}{}{Du hörst einfach nicht.}
{112}{}{Erteil' ihm eine Lektion.}
{113}{}{Erteil' ihr eine Lektion.}
{114}{}{Nur Mitglieder der Merchants sind in der Nähe des Wasserturms oder der Pumpen zugelassen.}
{115}{}{Du solltest gehen.}
{116}{}{Wir trauen niemandem und wir machen auch bei dir keine Ausnahme.}
{117}{}{Bleib' lieber von den Pumpen weg.}
{118}{}{Wenn du was brauchst, geh' zum Rat der Merchants.}
{119}{}{Wir schießen. Denk' nicht mal dran.}
{120}{}{Wir lassen niemanden die Lebensader des Hubs gefährden.}
