#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\updatmap.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
	Lighting;
	if (map_first_run) then begin
		override_map_start(109, 121, 0, 5);
		display_msg(message_str(SCRIPT_RNDDESRT, 314));
	end

	set_global_var(GVAR_SPECIAL_FSAUSER,1);
end

procedure map_update_p_proc begin
	Lighting;
end
