#include "..\headers\define.h"
#include "..\headers\updatmap.h"

procedure start;

export variable Beth_Box_Ptr;
export variable Beth_Ptr;
export variable BitsBob_Dialog_Ptr;
export variable BitsBob_Ptr;
export variable BitsBob_Stand_Ptr;
export variable Decker_Ptr;
export variable Fry_Stub_Ptr;
export variable Guido_Ptr;
export variable Justin_Ptr;
export variable Kane_Ptr;
export variable Leon_Ptr;
export variable Lorenzo_Safe_Ptr;
export variable Mitch_Box_Ptr;
export variable Richie_Ptr;
export variable Sid_Ptr;
export variable Staple_Box_Ptr;
export variable Vault_Ptr;

procedure map_exit_p_proc;
variable dude_start_hex;
variable party_elevation;

procedure start begin

	if (script_action == 15) then begin
		set_global_var(MARK_HUB_2, 1);
		if (elevation(dude_obj) == 1) then begin
			Darkness;
		end
		else begin
			Lighting;
		end
		if (global_var( GVAR_LOAD_MAP_INDEX ) == 3) then begin
			//override_map_start(99, 59, 0, 2);
		end
		if hub_invaded and (map_var(57) == 0) then begin
			if not(is_loading_game) then begin
				variable invaderPtr;
				set_map_var(57, 1);
				kill_critter_type(PID_GUARD_HMLTHR, 1);
				kill_critter_type(PID_GUARD_HFLTHR, 1);
				kill_critter_type(PID_DECKER, 1);
				kill_critter_type(PID_FRY, 0);
				kill_critter_type(PID_GUARD_HFMAXX, 1);
				kill_critter_type(PID_KERI, 1);
				kill_critter_type(PID_DEMETRE, 1);
				kill_critter_type(PID_GUARD_HMMAXX, 1);
				kill_critter_type(PID_PEASANT_FEMALE_CUTE, 1);
				kill_critter_type(PID_PEASANT_1, 1);
				kill_critter_type(PID_LEATHER_ARMOR_MALE, 1);
				kill_critter_type(PID_CITIZEN_2, 1);
				kill_critter_type(PID_TRAVELER_2, 1);
				kill_critter_type(PID_MERCHANT_3, 1);
				kill_critter_type(PID_TRAVELER_1, 1);
				kill_critter_type(PID_KANE, 1);
				kill_critter_type(PID_MERCHANT_4, 1);
				kill_critter_type(PID_LORENZO, 1);
				kill_critter_type(PID_GUARD_HMMETL, 1);
				kill_critter_type(PID_MERCHANT_7, 1);
				kill_critter_type(PID_MERCHANT_2, 1);
				kill_critter_type(PID_BUTCH, 1);
				kill_critter_type(PID_RUTGER, 1);
				kill_critter_type(PID_GUARD_NMPEAS, 1);
				kill_critter_type(PID_STRANGER_NFMAXX, 1);
				kill_critter_type(PID_PEASANT_5, 1);
				kill_critter_type(PID_GREENE, 1);
				kill_critter_type(PID_STRANGER_HMLTHR, 1);
				kill_critter_type(PID_GABRIEL, 1);
				kill_critter_type(PID_MERCHANT_NMBRLP, 1);
				kill_critter_type(PID_LOSER, 1);
				invaderPtr := create_object_sid(PID_MAD_SUPER_MUTANT, 0, 0, SCRIPT_INVADER);
				set_ai( invaderPtr, AI_SUPER_MUTANT_AGGRESSIVE );
				critter_attempt_placement(invaderPtr, 16294, 0);
				invaderPtr := create_object_sid(PID_MAD_SUPER_MUTANT, 0, 0, SCRIPT_INVADER);
				set_ai( invaderPtr, AI_SUPER_MUTANT_AGGRESSIVE );
				critter_attempt_placement(invaderPtr, 20723, 0);
				invaderPtr := create_object_sid(PID_MAD_SUPER_MUTANT, 0, 0, SCRIPT_INVADER);
				set_ai( invaderPtr, AI_SUPER_MUTANT_AGGRESSIVE );
				critter_attempt_placement(invaderPtr, 27080, 0);
				invaderPtr := create_object_sid(PID_MAD_SUPER_MUTANT, 0, 0, SCRIPT_INVADER);
				set_ai( invaderPtr, AI_SUPER_MUTANT_AGGRESSIVE );
				critter_attempt_placement(invaderPtr, 19658, 0);
			end
		end

	end
	else begin
		if (script_action == 23) then begin
			if (elevation(dude_obj) == 1) then begin
				Darkness;
			end
			else begin
				Lighting;
			end
			if ((combat_is_initialized == 0) and (global_var(UNDERGROUND_STATUS) == 1) and (map_var(52) == 1) and not(is_loading_game)) then begin
				set_map_var(52, 0);
				set_map_var(53, 1);

				gfade_out(1);
				if not(is_loading_game) then begin	set_obj_visibility(Fry_Stub_Ptr, 1);	end
				if (global_var(GREENE_DEAD) != 1) then begin
					move_to(Justin_Ptr, 24064, 0);
					set_team( Justin_Ptr, 67 );
				end
				move_to(dude_obj, 24267, 0);
				if (global_var(GREENE_DEAD) != 1) then begin
					anim(Justin_Ptr, 1000, rotation_to_tile(tile_num(Justin_Ptr), tile_num(dude_obj)));
					anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(Justin_Ptr)));
				end
				gfade_in(1);
			end

		end

	end
end

procedure map_exit_p_proc begin
	if map_var(58) == 1 then begin
		set_map_var(58, 0);
		//game_time_advance((0 - (10 * 60 * 60 * 24 * 6)));
	end
end



