/*

   Junktown - Gizmo the crime boss

*/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_GIZMO
#define TOWN_REP_VAR            (GVAR_TOWN_REP_JUNKTOWN)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure Critter_Action;
procedure description_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure map_enter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure damage_p_proc;

procedure Gizmo01;
procedure Gizmo01_1;
procedure Gizmo01b;
procedure Gizmo02;
procedure Gizmo04;
procedure Gizmo04a;
procedure Gizmo04_1;
procedure Gizmo05;
procedure Gizmo05_1;
procedure Gizmo06;
procedure Gizmo07;
procedure Gizmo08;
procedure Gizmo09;
procedure Gizmo10;
procedure Gizmo11;
procedure Gizmo13;
procedure Gizmo13_1;
procedure Gizmo14;
procedure Gizmo15;
procedure Gizmo15_1;
procedure Gizmo16;
procedure Gizmo16a;
procedure Gizmo17;
procedure Gizmo18;
procedure Gizmo19;
procedure Gizmo20;
procedure Gizmo21;
procedure Gizmo22;
procedure Gizmo23;
procedure Gizmo24;
procedure Gizmo25;
procedure Gizmo26;
procedure Gizmo27;
procedure Gizmo28;
procedure Gizmo29;
procedure Gizmo30;
procedure Gizmo32;
procedure Gizmo33;
procedure Gizmo34;
procedure Gizmo35;
procedure Gizmo36;
procedure Gizmo37;
procedure Gizmo38;
procedure Gizmo39;
procedure Gizmo42;
procedure Gizmo43;
procedure Gizmo44;
procedure Gizmo45;
procedure Gizmo47;
procedure Gizmo48;
procedure Gizmo19a;
procedure Gizmox;
procedure Gizmox1;
procedure Gizmox2;
procedure GizmoPay;
procedure badmouth;

variable tmp_hostile;
variable INSISTS;
variable CRIME;
variable stealing;

import variable Killian_ptr;
import variable Gizmo_is_angry;
import variable show_to_door;
import variable Gizmo_ptr;
import variable payment;

#define float(x)                    float_msg(self_obj, mstr(x), FLOAT_MSG_NORMAL)

procedure start begin
end

procedure critter_p_proc begin
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
   else begin
      if (Killian_ptr != 0) then begin
         float(220);
         attack(Killian_ptr);
      end
      else if (self_item_count(PID_ELECTRONIC_BUG)) then begin
         set_global_var(GVAR_BUG_PLANTED, 1);
      end
      else if (global_var(GVAR_ENEMY_GIZMOS_GANG) == 1) then begin// - ENEMY_GIZMOS_GANG
         if (self_can_see_dude) then begin
            attack(dude_obj);
         end
      end
      else if (global_var(GVAR_GIZMO_TALKED_ONCE) != 1) then begin
         if (tile_distance_objs(self_obj, dude_obj) <= 14) then begin
            if dude_can_see_self or self_can_see_dude /*or self_can_hear_dude*/ then begin
               set_global_var(GVAR_GIZMO_TALKED_ONCE, 1);
               float_msg(self_obj, mstr(227), FLOAT_MSG_RED);
            end
         end
      end
   end
end

procedure description_p_proc begin
   script_overrides;
   display_msg(mstr(218));
   script_overrides;
end

procedure destroy_p_proc begin
   if source_obj == dude_obj then begin
      inc_junktown_rep(REP_BONUS_KILLED_GIZMO);
      set_global_var(GVAR_ENEMY_GIZMOS_GANG, 1);
   end
   inc_evil_critter
   set_global_var(GVAR_GIZMO_DEAD, 1);
end

procedure look_at_p_proc begin
   script_overrides;
   if (local_var(10) != 1) then begin
      set_local_var(10, 1);
      display_msg(mstr(228));
   end
   else
      display_msg(mstr(100));
end

procedure map_enter_p_proc begin
   variable LVar0 := 0;
   Gizmo_ptr := self_obj;
   if (local_var(7) == 0) then begin
      set_local_var(7, 1000);
   end
   if (local_var(9) == 1) then begin
      payment := local_var(7);
   end
   set_self_team(TEAM_JUNKTOWN_GIZMO);
   set_self_ai(AI_GIZMO);
   if (global_var(GVAR_CAPTURE_GIZMO) == 2) then begin
      LVar0 := create_object(PID_GIZMO_REMAINS, self_tile, 0);
      kill_critter(self_obj, ANIM_stand);
   end
end

procedure pickup_p_proc begin
   stealing := 1;
   dialogue_system_enter;
end

procedure talk_p_proc begin
   dude_look_at_self;
   get_reaction
   if (local_var(8) == 1) then begin
      float_msg(self_obj, message_str(SCRIPT_ENEMY, 104), FLOAT_MSG_RED);
   end
   else begin
      if (global_var(GVAR_HIRED_BY_GIZMO) == 2) then begin
         float_msg(self_obj, message_str(SCRIPT_ENEMY, 101), FLOAT_MSG_NORMAL);
      end
      else begin
         start_gdialog(44, self_obj, 4, 21, 7);
         gsay_start;
         if (stealing) then begin
            call Gizmo45;
         end
         else if not(is_killian_alive) then begin
            call Gizmo21;
         end
         else if (local_var(4) == 1) then begin
            call Gizmo13;//  msg 140
         end
         else if (local_var(4) >= 2) then begin
            if (is_killian_alive) then begin
               call Gizmo35;//  msg 205
            end
            else begin
               call Gizmo13;//  msg 140
            end
         end
         else begin
            if (not(is_killian_alive) or (global_var(GVAR_HIRED_BY_KILLIAN) == 1)) then begin
               call Gizmo21;
            end
            else begin
               call Gizmo01;
            end
         end
         gsay_end;
         end_dialogue;
      end
   end
end

procedure damage_p_proc begin
   if source_obj == dude_obj then begin
      set_global_var(GVAR_ENEMY_GIZMOS_GANG, 1);
   end
end

procedure Gizmo01 begin
   Reply(101);
   BOption(102, Gizmo01_1, 5);//  was 49
   NOption(103, Gizmo04, 7);
   NOption(104, Gizmo04, 4);
   BLowOption(105, Gizmo01b);
end

procedure Gizmo01_1
begin
   DownReactLevel// was Up
   set_local_var(5, 1);
   call Gizmo02;
end

procedure Gizmo01b
begin
   BMessage(106);
   call Gizmox2;
end

procedure Gizmo02
begin
   Reply(107);
   BOption(108, Gizmo11, 5);
   NOption(109, Gizmo04, 4);
end

procedure Gizmo04
begin
   Reply(110);
   NOption(111, Gizmo05, 4);
   BOption(112, Gizmo04_1, 4);
end

procedure Gizmo04a
begin
   NMessage(113);
   call Gizmo05;
end

procedure Gizmo04_1
begin
   set_local_var(5, local_var(5) + 1);
   if (local_var(5) > 1) then begin
      call Gizmo11;
   end
   else begin
      call Gizmo04a;
   end
end

procedure Gizmo05
begin
   Reply(114);
   NOption(115, Gizmo06, 7);
   if (not(is_success(do_check(dude_obj, STAT_lu, 0)))) then begin
      BOption(116, Gizmo05_1, 6);
   end
   GOption(117, Gizmo07, 4);
   NOption(118, Gizmo10, 4);
   NOption(119, Gizmo08, 5);
end

procedure Gizmo05_1
begin
   DownReactLevel
   call Gizmo10;
end

procedure Gizmo06
begin
   Reply(120);
   GOption(121, Gizmo07, 7);
   GOption(122, Gizmo07, 4);
   BOption(123, badmouth, 6);
   NOption(124, Gizmo08, 5);
   BOption(125, Gizmo10, 4);
   NOption(126, Gizmo10, 4);
end

procedure Gizmo07
begin
   set_local_var(4, 1);
   set_global_var(GVAR_HIRED_BY_GIZMO, 1);
   GMessage(127);
   set_global_var(GVAR_GIZMO_NICE_SHOWDOOR, 1);
   call Gizmox;
end

procedure Gizmo08
begin
   Reply(128);
   GOption(129, Gizmo07, 4);
   NOption(130, Gizmo09, 6);
   NOption(131, Gizmo10, 4);
   BOption(132, badmouth, 5);
end

procedure Gizmo09
begin
   set_local_var(7, 1500);
   Reply(133);
   GOption(134, Gizmo07, 4);
   BOption(135, badmouth, 6);
   NOption(136, Gizmo10, 5);
   BOption(137, Gizmo10, 4);
end

procedure Gizmo10
begin
   BMessage(138);
   call Gizmox1;
end

procedure Gizmo11
begin
   BMessage(139);
   call Gizmox1;
end

procedure Gizmo13
begin
   set_local_var(4, local_var(4) + 1);
   Reply(140);
   NOption(141, Gizmo13_1, 4);
   BOption(142, Gizmo20, 4);//   was 50
end

procedure Gizmo13_1
begin
   if (dude_item_count(PID_DOG_TAGS) or not(is_killian_alive)) then begin
      call Gizmo14;
   end
   else begin
      call Gizmo17;
   end
end

procedure Gizmo14
begin
   Reply(143);
   if (dude_item_count(PID_DOG_TAGS)) then begin
      gsay_option(SCRIPT_MODREACT, 106, Gizmo15, 49);
   end
   else begin
      gsay_option(SCRIPT_MODREACT, 106, Gizmo17, 51);
   end
end

procedure Gizmo15
begin
   destroy_object(dude_item(PID_DOG_TAGS));
   set_global_var(GVAR_HIRED_BY_GIZMO, 2);
   Reply(144);
   NOption(145, GizmoPay, 4);
   BOption(146, Gizmo15_1, 6);
   NOption(147, Gizmo16, 6);
   NOption(148, GizmoPay, 7);
end

procedure Gizmo15_1
begin
   set_local_var(5, local_var(5) + 1);
   if (local_var(5) > 1) then begin
      call Gizmo11;
   end
   else begin
      call Gizmo16;
   end
end

procedure Gizmo16
begin
   Reply(149);
   NOption(150, GizmoPay, 4);
   if (not(is_success(do_check(dude_obj, STAT_lu, 0)))) then begin
      BOption(151, Gizmo16a, 7);
   end
   NOption(152, GizmoPay, 6);
end

procedure Gizmo16a
begin
   DownReactLevel
   call badmouth;
end

procedure Gizmo17
begin
   Reply(153);
   NOption(154, Gizmo18, 4);
   BOption(155, Gizmo19, 6);
   NOption(156, Gizmo20, 5);
   NOption(157, Gizmo20, 6);
end

procedure Gizmo18
begin
   if (local_var(6) > 0) then begin//  was "> 1"
      call Gizmo11;
   end
   else begin
      set_local_var(6, local_var(6) + 1);
      if (dude_item_count(PID_TAPE_RECORDER) and (global_var(GVAR_HIRED_BY_KILLIAN) == 1)) then begin
         set_global_var(GVAR_GOT_CONFESSION, 1);
      end
      NMessage(158);
      call Gizmox;
   end
end

procedure Gizmo19
begin
   Reply(159);
   NOption(160, Gizmo20, 4);
   if (not(is_success(do_check(dude_obj, STAT_lu, 0)))) then begin
      BOption(161, Gizmo19a, 7);
   end
   NOption(162, Gizmo18, 5);
   NOption(163, Gizmo20, 6);
end

procedure Gizmo20
begin
   if (local_var(6) > 0) then begin//  was "> 1"
      call Gizmo11;
   end
   else begin
      set_local_var(6, local_var(6) + 1);
      NMessage(164);
      call Gizmox;
   end
end

procedure Gizmo21
begin
   Reply(165);
   if (is_killian_alive) then begin
      NOption(166, Gizmo22, 7);
      NOption(169, Gizmo22, 4);
   end
   else begin
      GOption(221, Gizmo15, 4);
   end
   NOption(167, Gizmo32, 4);
   BOption(168, Gizmo34, 6);
   BLowOption(105, Gizmo01b);
end

procedure Gizmo22
begin
   Reply(170);
   if (dude_iq >= 7) then begin
      NOption(171, Gizmo23, 7);
   end
   else begin
      NOption(222, Gizmo23, 4);
   end
   BOption(172, Gizmo34, 6);
   NOption(173, Gizmo33, 5);
   BOption(174, Gizmo34, 4);
   BOption(175, Gizmo32, 4);
end

procedure Gizmo23
begin
   Reply(176);
   GOption(177, Gizmo24, 7);
   BOption(178, Gizmo34, 5);
   NOption(179, Gizmo32, 4);
   GOption(223, Gizmo24, 4);
end

procedure Gizmo24
begin
   if (dude_is_male) then begin
      Reply(180);
   end
   else begin
      Reply(226);
   end
   GOption(181, Gizmo25, 7);
   NOption(182, Gizmo32, 4);
   GOption(224, Gizmo26, 4);
end

procedure Gizmo25
begin
   Reply(183);
   NOption(184, Gizmo26, 7);
   NOption(185, Gizmo26, 4);
end

procedure Gizmo26
begin
   Reply(186);
   NOption(187, Gizmo27, 7);
   NOption(188, Gizmo30, 4);
   NOption(189, Gizmo27, 4);
end

procedure Gizmo27
begin
   Reply(190);
   BOption(191, Gizmo34, 6);
   NOption(192, Gizmo28, 6);
   NOption(225, Gizmo28, 4);
end

procedure Gizmo28
begin
   Reply(193);
   if (global_var(GVAR_HIRED_BY_KILLIAN) == 1) then begin
      if (dude_item_count(PID_TAPE_RECORDER)) then begin
         set_global_var(GVAR_GOT_CONFESSION, 1);
      end
   end
   NOption(194, Gizmo29, 6);
   NOption(195, Gizmo29, 4);
   BOption(196, Gizmo30, 4);
   NOption(197, Gizmo30, 4);
end

procedure Gizmo29
begin
   set_global_var(GVAR_HIRED_BY_GIZMO, 1);
   NMessage(198);
   call Gizmox;
end

procedure Gizmo30
begin
   BMessage(199);
   call Gizmox1;
end

procedure Gizmo32
begin
   BMessage(200);
   call Gizmox2;
end

procedure Gizmo33
begin
   Reply(201);
   NOption(202, Gizmo25, 5);
   NOption(203, Gizmo32, 4);
end

procedure Gizmo34
begin
   NMessage(204);
   call Gizmox1;
end

procedure Gizmo35
begin
   BMessage(205);
   call Gizmox1;
end

procedure Gizmo36
begin
   NMessage(206);
end

procedure Gizmo37
begin
   NMessage(207);
end

procedure Gizmo38
begin
   NMessage(208);
end

procedure Gizmo39
begin
   NMessage(209);
end

procedure Gizmo42
begin
   NMessage(210);
end

procedure Gizmo43
begin
   NMessage(211);
end

procedure Gizmo44
begin
   NMessage(212);
end

procedure Gizmo45
begin
   Gizmo_is_angry := 1;
   set_local_var(8, 1);
   stealing := 0;
   if (dude_is_male) then begin
      NMessage(213);
   end
   else begin
      NMessage(214);
   end
end

procedure Gizmo47
begin
   NMessage(215);
end

procedure Gizmo48
begin
   NMessage(216);
end

procedure Gizmo19a
begin
   DownReactLevel
   call Gizmo11;
end

procedure Gizmox begin
   set_global_var(GVAR_GIZMO_NICE_SHOWDOOR, 1);
   show_to_door := 1;
end

procedure Gizmox1
begin
   Gizmo_is_angry := 1;
   set_local_var(8, 1);
end

procedure Gizmox2
begin
   set_local_var(8, 1);
end

procedure GizmoPay
begin
   payment := local_var(7);
   set_local_var(9, 1);
end

procedure badmouth begin
   set_local_var(5, local_var(5) + 1);
   if (local_var(5) > 1) then begin
      call Gizmo11;
   end
   else begin
      call Gizmo10;
   end
end
