/*

   Elevator script for Glow #1 - Red Elevator

*/

#include "define.h"
#include "command.h"

procedure start;
procedure spatial_p_proc;

procedure start begin
end

procedure spatial_p_proc begin
   if source_is_dude then begin
      // Fake it till you make it.
      // We need to fake this elevator, otherwise the red arrow on
      // elevation 3 will point to the RIGHT and not LEFT as it should be.
      // This bug only appears on this one elevation and nowhere else.
      if (CUR_MAP_GLOW1 and dude_elevation == 2) then begin
         elevator(ELEV_GLOW1A);
      end
      else begin
         elevator(ELEV_GLOW1);
      end
   end
end

