/*

   Glow generic computer terminals

      UNUSED

*/

#include "define.h"
#include "area/glow.h"

#define NAME                     SCRIPT_GLOCOMP

#include "command.h"

/* Standard Script Procedures */
procedure start;
procedure look_at_p_proc;
procedure description_p_proc;

procedure investigate;

variable description := 0;

procedure start begin
   description := random(1, 4);
end

procedure look_at_p_proc begin
   //call investigate;
end

procedure description_p_proc begin
   call investigate;
end

procedure investigate begin
   script_overrides;

   if (description == 1) then begin
      display_msg(mstr(100));
   end
   else if (description == 2) then begin
      display_msg(mstr(101));
   end
   else if (description == 3) then begin
      display_msg(mstr(102));
   end
   else if (description == 4) then begin
      display_msg(mstr(103));
   end
end

