/*

   The Glow water pump

      !CUT CONTENT - UNUSED!

*/

#include "define.h"
#include "glow.h"

#define NAME                     SCRIPT_GLOWPUMP

#include "command.h"

/* Standard Script Procedures */
procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure description_p_proc begin
   script_overrides;
   display_msg(mstr(101));
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_REPAIR) then begin
      script_overrides;
      display_msg(mstr(102));
   end
end

