/*

   The Glow spatial script to inform about automated weapon systems

      !CUT CONTENT - UNUSED!

*/

/* Include Files */
#include "define.h"
#include "area/glow.h"

#define NAME                    SCRIPT_WEAPSYS

#include "command.h"

/* Standard Script Procedures */
procedure start;
procedure spatial_p_proc;

procedure start begin
end

procedure spatial_p_proc begin
   if source_is_dude then begin
      if (glow_quest_power_restored and glow_traps_active) then begin
         if (local_var(0) == 0) then begin
            if (dude_stat_success(STAT_pe, 0)) then begin
               display_msg(mstr(100));
            end
         end
         set_local_var(0, 1);
      end
   end
end
