#
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#

#
# Special holiday dates
#
{100}{}{Ein gutes neues Jahr!}      # New years
{101}{}{Alles Gute zum Valentinstag!}     # April fools
{102}{}{April, April!}      # April fools
{103}{}{Fröhlicher Versandtag!}            # Shipping day!
{104}{}{Fröhlicher Unabhängigkeitstag!}    # Independence day
{105}{}{Fröhliches Halloween!}           # Halloween
{106}{}{Fröhliches Erntedankfest!}    # Thanksgiving
{107}{}{Frohe Weihnachten!}           # X-mas

#
# System messages
#
{200}{}{WEITER}
{201}{}{ZURÜCK}
{202}{}{STATUS}
{203}{}{Keine aktuellen Aufgaben.}
{204}{}{TIPS}  # clues gone
{205}{}{KARTENANSICHT}
{206}{}{VIDEOARCHIVE}
{207}{}{DATEN}
{208}{}{}
{209}{}{}
{210}{}{Status}
{211}{}{DATEN}
{212}{}{von}
{213}{}{Seite}
{214}{}{OK}
{215}{}{Du kannst dich hier nicht ausruhen!}

#
# Alarm clock
#
{300}{}{WECKER}
{301}{}{Trefferpunkte}
{302}{}{Ruh dich zehn Minuten aus}
{303}{}{Ruh dich dreißig Minuten aus}
{304}{}{Ruh dich eine Stunde aus}
{305}{}{Ruh dich zwei Stunden aus}
{306}{}{Ruh dich drei Stunden aus}
{307}{}{Ruh dich vier Stunden aus}
{308}{}{Ruh dich fünf Stunden aus}
{309}{}{Ruh dich sechs Stunden aus}
{310}{}{Ruh dich bis zum Morgen (06:00) aus}
{311}{}{Ruh dich bis Mittag (12:00) aus}
{312}{}{Ruh dich bis zum Abend (18:00) aus}
{313}{}{Ruh dich bis Mitternacht (00:00) aus}
{314}{}{Ruh dich aus, bis du geheilt bist}
{315}{}{Bis zur Heilung der Gruppe ausruhen}

#
# Holodisk titles
#
{400}{}{FEV Experiment-Disk}
{401}{}{Sicherheitsprotokoll}
{402}{}{BoS-Disk}
{403}{}{Alpha Experiment-Disk}
{404}{}{Delta Experiment-Disk}
{405}{}{Vrees Autopsiebericht}
{406}{}{BoS-Ehrenkodex}
{407}{}{Mutantenübertragung}
{408}{}{Militärbasis-Disk}
{409}{}{Sophias Disk}
{410}{}{Maxsons Disk}
{411}{}{Richard Greys Tagebuch}
{412}{}{Maxsons Tagebuch}
{413}{}{FEV-Projekt}
{414}{}{Powerrüstungsspezifikation}
{415}{}{West Tech-Personalakten}
{416}{}{Vaultstandorte}
{417}{}{Regulatorübertragung}
{418}{}{RESERVED (available)}
{419}{}{RESERVED (available)}
{420}{}{RESERVED (available)}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{InterPlay Logo}                 # Not show in Pip-Boy 2000
{501}{}{MacPlay Logo}                   # MacPlay version ,Not show in Pip-Boy 2000
{502}{}{Aufseher-Briefing}
{503}{}{Containerzerstörung}
{504}{}{Kathedralenzerstörung}
{505}{}{In Container eingetaucht}
{506}{}{Vault 13-Invasion}
{507}{}{ }
{508}{}{ }
{509}{}{ }
{510}{}{Vault verlassen}                    # Male
{511}{}{Vault verlassen}                    # Female
{512}{}{Vault 13-Wasser}
{513}{}{Vault 13-Wasserknappheit}
{514}{}{Vault 13-Wasserverlust}
{515}{}{ }
{516}{}{ }

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Tips}  # Clues gone
{602}{}{Kartenansicht}
{603}{}{Archive}
{604}{}{Wecker}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Willkommen zu Rob Co PIP-Boy 2000.}
{607}{}{Bis dann.}
{608}{}{Aufwachen.}


#
# Status thread text
#
# Format:
# 0 City name
# 1 ... 9 thread/quest name
#
{700}{}{Vault 13}
{701}{}{Beruhige die Rebellengruppe.}
{702}{}{Vernichte den Mutantenanführer.}
{703}{}{Zerstöre die Quelle der Mutanten.}
{704}{}{Suche den Steuerchip.}
{705}{}{Suche den Wasserdieb.}
{706}{}{Hilf dem Sanitäter ein Gegengift herzustellen.}
{707}{}{Lerne aus den Vault-Archiven über die Außenwelt.}
#
{710}{}{Vergrabene Vault}
{711}{}{Suche nach Hinweisen und Informationen.}
{712}{}{Suche einen Steuerchip.}
#
{720}{}{Shady Sands}
{721}{}{Heile Jarvis vom Radscorpion-Gift.}
{722}{}{Stelle ein Gegengift her.}
{723}{}{Rette Tandi vor den Raiders.}
{724}{}{Halte die Radscorpions auf.}
{725}{}{Hilf die Ernte von Shady Sands zu verbessern.}
{726}{}{Rede mit Katrina.}
{727}{}{Heuere Ian.}
#
{730}{}{Junktown}
{731}{}{Hilf Saul.}
{732}{}{Töte Killian.}
{733}{}{Rette Sinthia.}
{734}{}{Bring Trish in Sicherheit.}
{735}{}{Halte Gizmo auf.}
{736}{}{Lass die Skulz-Gang auffliegen.}
#
{740}{}{Raiders}
{741}{}{Trete den Khans bei.}
{742}{}{Vernichte die Khans.}
{743}{}{Töte die Sklaven.}
{744}{}{Rette die Sklaven.}
#
{750}{}{Necropolis}
{751}{}{Vernichte die Supermutanten an der Wasserstelle.}
{752}{}{Repariere die Wasserpumpe von Necropolis.}
#
{760}{}{Hub}
{761}{}{Vernichte die Deathclaw.}
{762}{}{Erledige Jain.}
{763}{}{Erledige den Händler.}
{764}{}{Suche die verschwundenen Caravans.}
{765}{}{Stiehl dem Händler die Halskette.}
#
{770}{}{Brotherhood}
{771}{}{Werde ein Neuling.}
{772}{}{Rette den Neuling aus dem Hub.}
#
{780}{}{Militärbasis}
#
{790}{}{Glow}
{791}{}{Entschärfe die Fallen für die Basis.}
{792}{}{Schalte den Strom für den Glow ein.}
#
{800}{}{Boneyard}
{801}{}{Werde ein Blades-Gangmitglied.}
{802}{}{Gib ein Medaillon für Romero ab.}
{803}{}{Gib ein Paket von den Gunrunners ab.}
{804}{}{Suche den Children-Spion bei den Followers.}
{805}{}{Setze die Hydrofarmen in Adytum wieder instand.}
{806}{}{Rette Jason Zimmerman.}
{807}{}{Halte die Gangs von einem Angriff auf Adytum ab.}
#
{810}{}{Kathedrale}


#
# Holodisk text
#

# *** FEV Experiment Disk ***
{1000}{}{• Protokoll vom 21. März 2075:}
{1001}{}{Major Barnett hat Experimente mit der Probe 10-011}
{1002}{}{des Panimmunitätsvirus, kurz FEV-Virus, angeordnet.}
{1003}{}{Seine größte Sorge gilt den Nebenwirkungen der Vier-}
{1004}{}{fachhelixstruktur und nicht der Hauptwirkung der Re-}
{1005}{}{plikationsstabilität. Er glaubt, dass die neue Struktur}
{1006}{}{der nächste logische Schritt in der Entwicklung von}
{1007}{}{Säugetierzellkernen ist. Die Experimente mit Einzel-}
{1008}{}{lern sind ein großer Erfolg. Obwohl ihr Grundstoff-}
{1009}{}{wechsel unverändert scheint, übertrifft ihre Infek-}
{1010}{}{tions- und Strahlungsimmunität alle Erwartungen. Zu-}
{1011}{}{satz: Chloroplasten sind gegen das Virus offensicht-}
{1012}{}{lich immun. Weitere Experimente mit Pflanzenzellen}
{1013}{}{wurden auf Anordnung von Major Barnett abgebrochen.}
{1014}{}{ }
{1015}{}{**END-PAR**}
# -
{1016}{}{• Protokoll vom 9. Mai 2075}
{1017}{}{Wir infizierten mehrere Plattwurmarten mit dem FEV-}
{1018}{}{Virus. Innerhalb weniger Stunden wuchsen die Würmer}
{1019}{}{um 28 %, und die Population war gegen 39 andere Vi-}
{1020}{}{rusinfektionen immun. Jede Probe pflanzte sich über}
{1021}{}{mehrere Generationen fort, und die neue DNA-Struktur}
{1022}{}{wurde erfolgreich an die Nachkommen der Würmer ver-}
{1023}{}{erbt, obwohl in den Proben nur ungeschlechtliche}
{1024}{}{Fortpflanzung beobachtet werden konnte. Experimente}
{1025}{}{mit Insekten waren weniger erfolgreich. Major Barnett}
{1026}{}{hat diese Experimente bis auf weiteres verschoben.}
{1027}{}{**END-PAR**}
# -
{1028}{}{• Protokoll vom 30. Juni 2075}
{1029}{}{Mehrere Laborarten weißer Mäuse wurden erfolgreich mit}
{1030}{}{dem FEV-Virus infiziert. Auch hier war ein Wachstum}
{1031}{}{nach wenigen Stunden festzustellen. Nach neun Tagen}
{1032}{}{waren alle Mäuse 31 % größer als die Vergleichsgruppe.}
{1033}{}{Eine Sezierung ergab, dass das Wachstum in dem gestreif-}
{1034}{}{ten Muskelgewebe und bestimmten Innenorganen wie Le-}
{1035}{}{ber, Herz und Nieren am größten war. Ein überraschen-}
{1036}{}{des Ergebnis war, dass die infizierten Mäuse Labyrinthe}
{1037}{}{in der Hälfte der Zeit durchliefen wie die Vergleichs-}
{1038}{}{gruppe. Weitere Tests sind erforderlich, um die Bedeu-}
{1039}{}{tung dieses Ergebnisses zu bestätigen.}
{1040}{}{**END-PAR**}
# -
{1041}{}{• Protokoll vom 9. November 2075}
{1042}{}{Wir infizierten 218 Hasen mit dem FEV-Virus. Der Hälfte}
{1043}{}{wurden Elektroden eingepflanzt, um die EEG-Aktivität}
{1044}{}{vor und nach der Infektion zu beobachten. Eine erhöhte}
{1045}{}{EEG-Aktivität des Hirns konnte (durchschnittlich) 3,2}
{1046}{}{Sekunden nach der Injektion beobachtet werden. Erneut}
{1047}{}{konnte ein Wachstum festgestellt werden. Es konnte}
{1048}{}{auch eine erhöhte Aggressivität (besonders bei den}
{1049}{}{Männchen) beobachtet werden. Veränderungen im Hirn-}
{1050}{}{gewebe konnten nachgewiesen werden, so eine erhöhte}
{1051}{}{Dendritverbindung, vor allem im limbischen System und}
{1052}{}{in der vorderen Hirnrinde.}
{1053}{}{**END-PAR**}
# -
{1054}{}{• Protokoll vom 12. Januar 2076}
{1055}{}{Mit der Probe 11-011 konnten wir die mitotische Zyklen-}
{1056}{}{effizienz um 43 % verbessern. Wir infizierten 53 Wasch-}
{1057}{}{bären mit dem neuen Stoff. Zusätzlich zum erwarteten}
{1058}{}{Wachstum bestätigten die Verhaltensexperimente eine um}
{1059}{}{19 Punkte auf dem Schuler-Kapp-Index höhere Intelligenz}
{1060}{}{und Geschicklichkeit der Hände. Leider konnten einige}
{1061}{}{Versuchstiere ausbrechen und mussten eingefangen und}
{1062}{}{getötet werden. Major Barnett ordnete das Töten der}
{1063}{}{übrigen Versuchstiere an. Zwei Paare konnten nicht ge-}
{1064}{}{funden werden.}
{1065}{}{**END-PAR**}
# -
{1066}{}{• Protokoll vom 13. Mai 2076}
{1067}{}{Wir mischten einige neue Gensequenzen, die Major}
{1068}{}{Barnetts Beraterteam bereitstellte, mit dem FEV-Virus.}
{1069}{}{Mit der Probe 11-101a infizierten wir 23 Rasse- und}
{1070}{}{Mischlingshunde, bei denen sich sofort Wachstum ein-}
{1071}{}{stellte, das von erhöhter Aggressivität begleitet war.}
{1072}{}{Es war jedoch keine wesentliche Intelligenzzunahme}
{1073}{}{festzustellen. Als nächstes planen wir einen Genaus-}
{1074}{}{tausch bei 92 Allelenpaaren mit der Probe 11-011. Alle}
{1075}{}{Versuchstiere wurden nach 14 Wochen getötet.}
{1076}{}{**END-PAR**}
# -
{1077}{}{• Protokoll vom 4. Oktober 2076}
{1078}{}{Der Genaustausch ist abgeschlossen. 15 Schimpansen}
{1079}{}{wurden mit der Probe 11-111 infiziert. Wachstum und}
{1080}{}{Immunität sind unübertroffen hoch. Experimente, durch}
{1081}{}{Bestrahlung und Chemikalien Krebs bei den Versuchs-}
{1082}{}{tieren auszulösen, schlugen fehl. Wegen erhöhter}
{1083}{}{Aggressivität mussten die Versuchstiere isoliert werden.}
{1084}{}{Zwei Versuchstiere litten unter Epilepsieanfällen und}
{1085}{}{starben. Alle anderen Versuchstiere wurden getötet.}
{1086}{}{**END-PAR**}
# -
{1087}{}{• Protokoll vom 7. Januar 2077}
{1088}{}{Major Barnett ordnete die Verlegung der FEV-Forschung}
{1089}{}{zur Militärbasis Mariposa an. Er beabsichtigt, die Expe-}
{1090}{}{rimente an freiwilligen Versuchspersonen fortzuführen.}
{1091}{}{Ich bin strikt dagegen und möchte hiermit festhalten,}
{1092}{}{dass Versuche an Menschen weder von mir noch von mei-}
{1093}{}{nem Team empfohlen werden.}
{1094}{}{**END-DISK**}

# *** Security Disk ***
{2000}{}{Sicherheitsübertretung Gamma Omicron Delta.}
{2001}{}{**END-DISK**}

# *** Ancient Brotherhood Disk ***
{3000}{}{Captain Maxson hatte recht. Dieser Ort bedeutet Tod.}
{3001}{}{Ich schreibe dies alles auf, damit vielleicht irgendwann}
{3002}{}{jemand herausfindet, was mit uns geschehen ist, falls}
{3003}{}{wir nicht zurückkehren.}
{3004}{}{**END-PAR**}
# -
{3005}{}{Nach 20 Tagen in der Hölle kamen wir endlich im West}
{3006}{}{Tech-Forschungszentrum an. Aber das war erst der ein-}
{3007}{}{fache Teil! Die Strahlung nahm erst richtig zu, als}
{3008}{}{wir den riesigen Krater sehen konnten. Wir überprüften}
{3009}{}{unsere Vorräte und stellten fest, dass wir mit unseren}
{3010}{}{Waffen und Antistrahlenmitteln mindestens einen For-}
{3011}{}{schungstag überleben könnten. Das war zwar ein Risiko,}
{3012}{}{aber die Technologie, die wir finden wollten, war es wert.}
{3013}{}{**END-PAR**}
# -
{3014}{}{Wir stiegen den Krater bis zur ersten Ebene hinab. Alles}
{3015}{}{verlief offenbar nach Plan. Der Strom war abgeschaltet,}
{3016}{}{so dass wir uns nicht um das Sicherheitssystem kümmern}
{3017}{}{mussten, dachten wir zumindest! Auf dieser Ebene gab es}
{3018}{}{nichts Interessantes, also stiegen wir weiter hinab.}
{3019}{}{**END-PAR**}
# -
{3020}{}{Die zweite Ebene glich der ersten.}
{3021}{}{**END-PAR**}
# -
{3022}{}{Als Jensen auf der dritten Ebene ankam, passierte et-}
{3023}{}{was Furchtbares. Die Sicherheitssensoren der ersten}
{3024}{}{beiden Ebenen waren ausgebrannt, aber nicht die der}
{3025}{}{dritten. Jensen wurde in Stücke geschnitten, bevor er}
{3026}{}{wusste, was los war. Noch nie hatten wir Waffen gesehen,}
{3027}{}{die so leicht durch eine Powerrüstung schneiden. Einige}
{3028}{}{Männer fielen links und rechts runter, andere drehten}
{3029}{}{einfach durch. Ich wollte alle sammeln, aber nur ich, Soto}
{3030}{}{und Camarillo schafften es zurück zur ersten Ebene.}
{3031}{}{**END-PAR**}
# -
{3032}{}{Dass ich Sotos brennendes Fleisch dort riechen kann, wo}
{3033}{}{er seinen Arm verlor, bedeutet, dass meine Powerrüstung}
{3034}{}{undicht ist. So bekomme ich also viel mehr radioaktive}
{3035}{}{Strahlung ab als geplant. Die Löcher in meiner Rüstung}
{3036}{}{werden immer größer. Wir müssen hier weg, bevor meine}
{3037}{}{Rüstung ganz kaputt ist.}
{3038}{}{**END-PAR**}
# -
{3039}{}{Camarillo schien körperlich okay. Er verließ uns vor ca.}
{3040}{}{einer Stunde und murmelte etwas von Gehenna. Dieser}
{3041}{}{Dreckskerl hat alle unsere Antistrahlenmittel!}
{3042}{}{**END-PAR**}
# -
{3043}{}{So sind nur noch Soto und ich übrig. Ohne Antistrahlen-}
{3044}{}{mittel kommen wir nicht besonders weit, also müssen wir}
{3045}{}{Camarillo finden, bevor es zu spät ist.}
{3046}{}{ }
{3047}{}{**END-PAR**}
# -
{3048}{}{Sergeant D. Allen, US-Streitkräfte.}
{3049}{}{**END-DISK**}


#  *** Alpha Experiment Disk ***
{4000}{}{Prototyp Panimmunitätsvirus-Projekt}
{4001}{}{**END-PAR**}
# -
{4002}{}{In der Hoffnung, die aktuellen Bakterien- und Viren-}
{4003}{}{stoffe zu bekämpfen, die von der chinesischen Regie-}
{4004}{}{rung eingesetzt werden, haben wir ein Virusfragment}
{4005}{}{bestehend aus Ribonukleinsäure (RNA) in einer Pro-}
{4006}{}{teinlipidhülle hergestellt. Dieses Virus enthält eine}
{4007}{}{spezielle Anordnung bestrahlter Aminosäuren (RAA),}
{4008}{}{die sich an unspezifischen Bindestellen der Desoxy-}
{4009}{}{ribonukleinsäure (DNA) anlagern und zu einer nicht-}
{4010}{}{replizierenden Mitose führen: Die neue Wirtszelle}
{4011}{}{hat eine Vierfachhelix-DNA-Struktur.}
{4012}{}{ }
{4013}{}{**END-PAR**}
# -
{4014}{}{Die ersten Versuche sind vielversprechend. Das Virus}
{4015}{}{durchdringt die Zellmembran mühelos und lagert sich}
{4016}{}{direkt an die Wirts-DNA im Zellkern an. Die Mitose der}
{4017}{}{Struktur beginnt fast unmittelbar. Die Zytokinese}
{4018}{}{wird verhindert, indem die Anordnung der Kinetochor-}
{4019}{}{fasern während der Anaphase gesteuert wird. Der ge-}
{4020}{}{samte Mitosezyklus dauert ca. zwei Stunden. Es kann}
{4021}{}{aber Tage oder Wochen dauern, bis der phenotypische}
{4022}{}{Ausdruck der neuen Struktur deutlich wird.}
{4023}{}{**END-PAR**}
# -
{4024}{}{Neben der effektiven Immunität gegen Bakterien- und}
{4025}{}{Virenstoffe ist die Vierfachhelixstruktur aufgrund der}
{4026}{}{Vielfalt der Basissequenz völlig immun gegen Fehler bei}
{4027}{}{der Basispaarung in der Replikationsphase. Bestrahltes}
{4028}{}{Gewebe wies keine Mutation der Basissequenz auf, und}
{4029}{}{die Proteinsynthesemechanismen in den Ribosomen wurden}
{4030}{}{nicht beeinträchtigt.}
{4031}{}{**END-PAR**}
# -
{4032}{}{Über 80 % des Gewebes enthielt Vierfachhelix-DNA. Am}
{4033}{}{meisten war das Muskel- und Knochengewebe betroffen,}
{4034}{}{aber auch sekretorische Zellen, da diese Zellen am}
{4035}{}{stärksten auf das Virus ansprachen. Sensorische Zellen}
{4036}{}{sind am wenigsten betroffen. Überraschenderweise fand}
{4037}{}{die Mitose auch bei normalerweise nichtreplizierenden}
{4038}{}{Nervenzellen und nichtsomatischen Zellen statt. Die}
{4039}{}{Auswirkungen hierauf sind noch genauer zu untersuchen.}
{4040}{}{**END-DISK**}


# *** Delta Experiment Disk ***
{5000}{}{Das Militär hält es für notwendig, dass wir die Auswir-}
{5001}{}{kungen der Wellentechnologie auf lebende Organismen ge-}
{5002}{}{nauer untersuchen. Licht- und Schallwellen sind Grund-}
{5003}{}{lage unserer Studien. Durch Veränderung der Amplitude}
{5004}{}{von Lichtwellen und Erhöhung der Frequenz konnten wir}
{5005}{}{Laser entwickeln, die durch mehrere Meter Stahl schnei-}
{5006}{}{den können. Leider wurden die darin liegenden Möglich-}
{5007}{}{keiten nicht voll ausgeschöpft. Andere Wissenschaftler}
{5008}{}{beschäftigen sich jetzt mit diesem Thema.}
{5009}{}{**END-DISK**}


# *** Vree's Experiment Disk ***
{6000}{}{• Erste Beobachtungen}
{6001}{}{**END-PAR**}
# -
{6002}{}{Das ist wirklich erstaunlich: Einige der patroullierenden}
{6003}{}{Knights entdeckten ein seltsames Lebewesen. Es scheint}
{6004}{}{humanoid zu sein und war wahrscheinlich mal ein Mensch.}
{6005}{}{Es gibt jedoch viele Unterschiede zwischen der Struktur}
{6006}{}{dieses Lebewesens und der eines normalen Menschen.}
{6007}{}{**END-PAR**}
# -
{6008}{}{Eine erste Untersuchung dieses Lebewesens ergab, dass}
{6009}{}{die Zellstruktur der von Menschen ähnelt. Bevor eine}
{6010}{}{mögliche Verwesung stattfindet, halte ich die wesent-}
{6011}{}{lichen Merkmale des Lebewesens fest:}
{6012}{}{**END-PAR**}
# -
{6013}{}{• Angaben zu Subjekt A:}
{6014}{}{**END-PAR**}
# -
{6015}{}{Größe:       3,2 m}
{6016}{}{Gewicht:     363,21 kg}
{6017}{}{Geschlecht: Ungeklärt}
{6018}{}{Hautfarbe:  Überwiegend grau, stellenweise grün im ak-}
{6019}{}{tuellen Licht. Unklar, ob dies auf die Verwesung oder}
{6020}{}{das Leben im Ödland zurückzuführen ist. Hinweis: Die}
{6021}{}{Haut ist für Skalpelle extrem zäh.}
{6022}{}{**END-PAR**}
{6023}{}{Zusammensetzung:}
{6024}{}{Muskeln:     77,41 %}
{6025}{}{Knochen:    10,23 %}
{6026}{}{Fett:         3,02 %}
{6027}{}{Gewebe:     9,34 %}
{6028}{}{**END-PAR**}
{6029}{}{Zellstruktur:}
{6030}{}{Schnellere Zellteilung.}
{6031}{}{Mitose um 15 % schneller als bei normalen Menschen.}
{6032}{}{Sehr ähnliche Zellstruktur wie Menschen.}
{6033}{}{Starke Übereinstimmung in der genetischen Struktur des}
{6034}{}{Lebewesens und der des Homo Sapiens. Möglicherweise}
{6035}{}{eine Mutation durch die im Krieg übriggebliebenen nu-}
{6036}{}{klearen biochemischen Stoffe.}
{6037}{}{DNA-Stränge offenbar vollständig. Alle rezessiven Gene}
{6038}{}{für Krankheiten scheinen aus dem System entfernt wor-}
{6039}{}{den zu sein.}
{6040}{}{RNA-Stränge sind offensichtlich auch verändert worden,}
{6041}{}{um eine größere Signalübertragung zu ermöglichen.}
{6042}{}{ }
{6043}{}{ }
{6044}{}{**END-PAR**}
# -
{6045}{}{• Erste Hypothese}
{6046}{}{**END-PAR**}
# -
{6047}{}{Aufgrund der vergrößerten Neurotransmitter und Synap-}
{6048}{}{senrezeptoren nehme ich an, dass das Lebewesen höher}
{6049}{}{entwickelte Reflexe und Sinne besessen hat. Angesichts}
{6050}{}{der Angaben der Knights über den Fundort - Ödland mit}
{6051}{}{hoher Strahlung und einer extrem hohen Konzentration}
{6052}{}{chemischer Stoffe - ist es ein Wunder, dass das Lebe-}
{6053}{}{wesen so lange überleben konnte. Es werden Tests zur}
{6054}{}{Klärung der Todesursache durchgeführt.}
{6055}{}{**END-PAR**}
# -
{6056}{}{• Testergebnisse zu Subjekt A:}
{6057}{}{**END-PAR**}
# -
{6058}{}{Visuelle Untersuchung:}
{6059}{}{Schwarzpulverspuren um die Wunde lassen auf eine Kugel}
{6060}{}{schließen.}
{6061}{}{1,2 cm lange Fleischwunden an der Wade des rechten Beins}
{6062}{}{stammen offensichtlich von Bissen. Untersuchung auf Toll-}
{6063}{}{wut wird durchgeführt.}
{6064}{}{Ausgetrocknete und schuppige Haut. Bestrahlung möglich.}
{6065}{}{**END-PAR**}
# -
{6066}{}{Testergebnisse:}
{6067}{}{Strahlung:              12 rad}
{6068}{}{Tollwut:                 Negativ}
{6069}{}{Chlorwasserstoffgas: Negativ}
{6070}{}{Chlorgehalt:            0,7 %}
{6071}{}{Schwefelgehalt:        0,02 %}
{6072}{}{Phasenvirus:           Negativ}
{6073}{}{Gammazyklotronvirus: Negativ}
{6074}{}{FEV II-Virus:           Große Überdosis}
{6075}{}{**END-PAR**}
# -
{6076}{}{• Hypothese}
{6077}{}{**END-PAR**}
# -
{6078}{}{Aufgrund meiner Beobachtungen nehme ich an, dass das}
{6079}{}{Testsubjekt in einem Kampf mit mindestens zwei Men-}
{6080}{}{schen und drei Tieren in der Größe von Hunden getötet}
{6081}{}{wurde. Erstaunlich ist das Ausmaß der Vireninfektion}
{6082}{}{des Subjekts. Ich habe einmal gelesen, dass Wissenschaft-}
{6083}{}{ler vor dem Krieg Experimente mit solchen Viren durch-}
{6084}{}{führten. Allerdings wurden alle Forschungsaufzeichnungen}
{6085}{}{vernichtet.}
{6086}{}{**END-PAR**}
# -
{6087}{}{Die Untersuchung des Virus hat zu interessanten Ent-}
{6088}{}{deckungen geführt. Die Überdosis des Virus ist Ursache}
{6089}{}{für die vielen Mutationen des Subjekts. Dies wäre eine}
{6090}{}{Erklärung für die verbesserte Muskel- und Knochenstruk-}
{6091}{}{tur. Außerdem wurden rezessive Gene, die beim Menschen}
{6092}{}{typisch sind, so manipuliert, dass eine optimale Kombi-}
{6093}{}{nation entstand. Der dazu erforderliche Prozess ist zwar}
{6094}{}{noch unklar, bekannt sind aber die enormen Nebenwir-}
{6095}{}{kungen. Als Hauptnebenwirkung ist Sterilität zu nennen.}
{6096}{}{Das Subjekt hätte sich mit keinem, d. h. weder mit einem}
{6097}{}{nicht infizierten noch einem mutierten Lebewesen fort-}
{6098}{}{pflanzen können. Eine weitere Nebenwirkungen ist die}
{6099}{}{Pigmentveränderung der Epidermis. Die Lebenserwartung}
{6100}{}{ist um 10 % höher, die Intelligenz um 30 % niedriger.}
{6101}{}{**END-PAR**}
# -
{6102}{}{• Schlussfolgerungen}
{6103}{}{**END-PAR**}
# -
{6104}{}{Aufgrund dieser Daten gehe ich davon aus, dass wir diese}
{6105}{}{Mutanten problemlos überleben können. Da diese Mutan-}
{6106}{}{ten jedoch eine extrem hohe Konzentration des Virus}
{6107}{}{aufweisen, ist es naheliegend, dass es einen Ort gibt, wo}
{6108}{}{diese Lebewesen erzeugt werden. Ich wage allerdings}
{6109}{}{keine Prognose darüber, wo dieser Ort sein könnte.}
{6110}{}{**END-DISK**}


# *** Brotherhood of Steel Honor Code ***
# *** Maxson's History ***
{7000}{}{Mein Vater gehörte zur Wache einer geheimen Militärba-}
{7001}{}{sis in der Wüste Südkaliforniens. Er war ein typischer}
{7002}{}{Militärpolizist, dessen Kraft mich am meisten beein-}
{7003}{}{druckte. Als die Revolution begann, respektierte ich sei-}
{7004}{}{ne Überzeugungen. Er blieb zurück, um den Verletzten zu}
{7005}{}{helfen. Er legte mein Schicksal und das meiner Mutter in}
{7006}{}{die Hände seines besten Freundes und befahl uns, mit}
{7007}{}{den anderen Rebellen in die Wüste zu ziehen.}
{7008}{}{**END-PAR**}
# -
{7009}{}{Wir, eine Hand voll Leute, marschierten in die Wüste. Mein}
{7010}{}{einzige Gedanke war, dass ich meinen Vater nie mehr wie-}
{7011}{}{dersehen würde. Er wusste, dass das Zurückbleiben sein si-}
{7012}{}{cherer Tod sein würde, und trotzdem blieb er. Er achtete}
{7013}{}{die Fahne, das CIC und das Abzeichen, das er trug.}
{7014}{}{**END-PAR**}
# -
{7015}{}{Was für ein Idiot!}
{7016}{}{**END-PAR**}
# -
{7017}{}{Er starb für die Sünden anderer. So etwas soll uns nicht}
{7018}{}{passieren. Wir werden unabhängig sein. Wir werden das}
{7019}{}{Wissen in unseren Händen halten. Wir werden das Ende}
{7020}{}{der Zivilisation überleben. Wir werden die Verantwortung}
{7021}{}{für unsere Taten übernehmen, und wir werden andere für}
{7022}{}{ihre Taten zur Rechenschaft ziehen.}
{7023}{}{**END-PAR**}
# -
{7024}{}{Dies schwöre ich dir, Maxson, mein Sohn. Die Brotherhood}
{7025}{}{of Steel hat diesen Namen verdient. Wir sind eine Bruder-}
{7026}{}{schaft. Anders als bei meinem Vater stehen wir Rücken}
{7027}{}{an Rücken mit denen, die unsere Überzeugungen teilen.}
{7028}{}{Wir sind aus Stahl, und wir sind dafür geschaffen!}
{7029}{}{**END-PAR**}
# -
{7030}{}{Vergiss nie das Feuer, in dem wir geschmiedet wurden.}
{7031}{}{Vergiss niemals das Motto der Vergangenheit und unser}
{7032}{}{Motto der Gegenwart.}
{7033}{}{**END-DISK**}

# *** Mutant disk ***
{8000}{}{Nachricht gesendet: Basis, hier Scavenger-Team Zwei.}
{8001}{}{Over.}
{8002}{}{**END-PAR**}
# -
{8003}{}{Nachricht erhalten: Der Empfang ist laut und deutlich.}
{8004}{}{Weitermachen. Over.}
{8005}{}{**END-PAR**}
# -
{8006}{}{Nachricht gesendet: Wir haben vier Männer und zwei}
{8007}{}{Frauen mit ihren Vorräten aus dem Caravan aufgelesen.}
{8008}{}{Sie sind nicht allzu verseucht. Sagt dem Leutnant, dass}
{8009}{}{wir sie vorausschicken, sie werden das Ganze vielleicht}
{8010}{}{überleben. Wir werden hier noch ein paar Tage warten,}
{8011}{}{um einen weiteren Caravan abzufangen. Over.}
{8012}{}{**END-PAR**}
# -
{8013}{}{Nachricht erhalten: Roger. Gab es Verluste bei der Über-}
{8014}{}{nahme? Over.}
{8015}{}{**END-PAR**}
# -
{8016}{}{Nachricht gesendet: Negativ. Wieder ein sauberes Manö-}
{8017}{}{ver. Basis, teilt Scavenger-Team Eins mit, dass wir auf}
{8018}{}{dasselbe Problem stießen. Einer unserer Späher ist von}
{8019}{}{seiner Peripherie-Patrouille nicht zurückgekehrt. Eini-}
{8020}{}{ge andere Späher berichteten, dass letzte Nacht etwas}
{8021}{}{Großes und Schnelles in der Nähe des Lagers gesichtet}
{8022}{}{wurde. Ich werde es morgen um 06:00 Uhr erkunden. Over.}
{8023}{}{**END-PAR**}
# -
{8024}{}{Nachricht erhalten: Verstanden. Wir warten auf euren}
{8025}{}{Bericht. Versucht es abzufangen, wenn möglich. Der}
{8026}{}{Meister wäre sehr erfreut. Over.}
{8027}{}{**END-DISK**}


# *** Military Base Disk***
{9000}{}{• 10. Oktober 2077}
{9001}{}{Ich, Roger Maxson, Captain, Seriennummer 072389, habe}
{9002}{}{dieses Protokoll begonnen, weil es für keinen von uns}
{9003}{}{gut aussieht, und ich möchte, dass die Menschen erfahren,}
{9004}{}{was hier wirklich passiert ist.}
{9005}{}{**END-PAR**}
# -
{9006}{}{Es war der Teufel los, als wir herausfanden, was diese}
{9007}{}{Wissenschaftler vorhatten. Der Colonel hat sich in sei-}
{9008}{}{nem Büro eingeschlossen und hat wohl anscheinend einen}
{9009}{}{Zusammenbruch. Die Männer schreien nach Kampf. Sie er-}
{9010}{}{warten von mir eine Antwort, und ich weiß nicht genau,}
{9011}{}{was ich tun soll. Aber irgend jemand muss etwas tun, be-}
{9012}{}{vor dieser Ort in einem anarchistischen Blutbad versinkt.}
{9013}{}{**END-PAR**}
# -
{9014}{}{• 12. Oktober 2077}
{9015}{}{Immer, wenn wir von weiter oben einen Bericht erhalten,}
{9016}{}{wird alles noch schlimmer. Der Krieg wird immer schreck-}
{9017}{}{licher. Eine Meuterei steht unmittelbar bevor, die Chaos}
{9018}{}{bedeutet. Ich konnte heute einen der Männer daran hin-}
{9019}{}{dern, einen Wissenschaftler zu töten, und ordnete ein}
{9020}{}{Verhör an, um herauszufinden, wie ihr Auftrag lautete.}
{9021}{}{**END-PAR**}
# -
{9022}{}{• 13. Oktober 2077}
{9023}{}{Ich habe heute einen Mann getötet. Beim Verhör des wis-}
{9024}{}{senschaftlichen Leiters Anderson erfuhr ich alles über}
{9025}{}{ihre unmenschlichen Experimente. Anderson behauptete,}
{9026}{}{ihr Auftrag käme von der Regierung, aber das nahm ich}
{9027}{}{ihm nicht ab. Er schrie, dass er als Soldat doch nur seine}
{9028}{}{Befehle befolgt habe, woraufhin ich ihn einfach erschoß.}
{9029}{}{Jetzt rede ich mir ein, dass ich es nur tat, damit er keine}
{9030}{}{Meuterei anzetteln konnte, aber ich bin mir nicht sicher.}
{9031}{}{**END-PAR**}
# -
{9032}{}{• 15. Oktober 2077}
{9033}{}{Ich versuchte erneut, mit dem Colonel durch die Tür zu}
{9034}{}{sprechen, aber er scheint jeglichen Bezug zur Realität}
{9035}{}{verloren zu haben. Mit einigen Männern trat ich die Tür}
{9036}{}{ein, gerade rechtzeitig, um mitanzusehen, wie er sich er-}
{9037}{}{schoß. Bevor er abdrückte, sagte er, es täte ihm leid.}
{9038}{}{**END-PAR**}
# -
{9039}{}{• 18. Oktober 2077}
{9040}{}{Indem ich diesen Typ tötete, habe ich anscheinend meine}
{9041}{}{Stellung als Anführer der Männer bestätigt. Sie folgen}
{9042}{}{mir, ohne Fragen zu stellen. Die Verhöre enden stets mit}
{9043}{}{Tod. Shellman hat am längsten durchgehalten, aber das}
{9044}{}{Endergebnis war dasselbe. Ihre Angaben über die Befehle}
{9045}{}{waren ein bisschen zu detailliert, um völlig erfunden zu}
{9046}{}{sein. Ich habe ein wirklich ungutes Gefühl im Magen, wie}
{9047}{}{das wohl alles enden wird. Ich belüge mich nicht einmal}
{9048}{}{mehr selbst, warum ich die Wissenschaftler töte.}
{9049}{}{**END-PAR**}
# -
{9050}{}{• 20. Oktober 2077}
{9051}{}{Ich nahm schließlich mit der Außenwelt über Funk Kontakt}
{9052}{}{auf. Ich weiß nicht, weshalb sie keinen schickten, um}
{9053}{}{herauszufinden, warum wir nicht mehr auf ihre Meldungen}
{9054}{}{reagierten. Keine Ahnung. Naja, sie werden wohl schon}
{9055}{}{kommen. Ich erklärte unsere Unabhängigkeit von der Uni-}
{9056}{}{on. Jefferson Davis würde sich im Grab umdrehen!}
{9057}{}{**END-PAR**}
# -
{9058}{}{• 22. Oktober 2077}
{9059}{}{Was zum Teufel ist hier los? Wir erklären unsere Deser-}
{9060}{}{tation aus der Armee und unsere Unabhängigkeit von}
{9061}{}{allen Regierungsbefehlen, und was passiert? Nichts!}
{9062}{}{Irgend etwas liegt in der Luft.}
{9063}{}{**END-PAR**}
# -
{9064}{}{• 23. Oktober 2077}
{9065}{}{Ich kann nicht fassen, dass diese Schweine es tatsächlich}
{9066}{}{fertigbrachten. Zur Hölle mit ihnen! Sie haben also wirk-}
{9067}{}{lich die Atombomben losgeschickt. Wir waren gerade dabei,}
{9068}{}{die Wahrheit aus von Felden herauszuholen, als der Kon-}
{9069}{}{takt ganz abbrach. Ich glaube, das Forschungszentrum}
{9070}{}{hat es schlimm erwischt. Ich weiß nicht warum, nur so ein}
{9071}{}{Gefühl im Magen. Unbegreiflicherweise waren wir nicht die}
{9072}{}{Zielscheibe, aber ich bin sicher, China wird dieses Ver-}
{9073}{}{sehen bald nachholen. Zum Glück brachten wir unsere Fa-}
{9074}{}{milien vorgestern zur Basis. Wir wissen nicht, ob dort}
{9075}{}{schon radioaktiver Niederschlag niedergegangen ist.}
{9076}{}{**END-PAR**}
# -
{9077}{}{• 25. Oktober 2077}
{9078}{}{Sgt. Platner meldete sich freiwillig, heute nach draußen}
{9079}{}{zu gehen und Luftmessungen durchzuführen. Anscheinend}
{9080}{}{hat sich die radioaktive Strahlung nicht so weit ausge-}
{9081}{}{breitet. Da er seine Powerrüstung trug, bestand für ihn}
{9082}{}{keine Verstrahlungsgefahr. Hätte er jedoch Strahlung}
{9083}{}{abbekommen, hätten wir ihn verbannen müssen, denn wir}
{9084}{}{haben keine geeigneten Dekontaminierungsmöglichkeiten.}
{9085}{}{**END-PAR**}
# -
{9086}{}{• 26. Oktober 2077}
{9087}{}{Ich überredete die Männer, die Wissenschaftler zu begra-}
{9088}{}{ben. Ich weiß nicht warum, vielleicht um mein Gewissen zu}
{9089}{}{beruhigen. Ich fing langsam an, ihnen ihre Geschichten zu}
{9090}{}{glauben, als der letzte starb.}
{9091}{}{**END-PAR**}
# -
{9092}{}{Was ist nur aus mir geworden?}
{9093}{}{**END-PAR**}
# -
{9094}{}{• 27. Oktober 2077}
{9095}{}{Wir verlassen heute diesen gottverlassenen Ort. Ich leite}
{9096}{}{den Rückzug zum alten Regierungsbunker bei Lost Hills.}
{9097}{}{Ich lasse dieses Protokoll zurück, damit es begraben wird,}
{9098}{}{wenn dieser Ort untergeht. Wer weiß, vielleicht findet es}
{9099}{}{eines Tages irgend jemand ...}
{9100}{}{**END-DISK**}

# *** Sophia Disk ***
{10000}{}{Der Rückzug von dieser verfluchten Basis war hart für}
{10001}{}{die Männer und ihre Familien. Es gab zwar keinen radio-}
{10002}{}{aktiven Niederschlag, aber unsere Gruppe wurde häufig}
{10003}{}{Opfer von Übergriffen. Umherziehende Banden psycho-}
{10004}{}{tischer Plünderer griffen unsere Gruppe mehrfach an.}
{10005}{}{ }
{10006}{}{**END-PAR**}
# -
{10007}{}{Die Gruppe an sich befand sich nicht in Gefahr, da alle}
{10008}{}{Powerrüstungen trugen. Die Familienmitglieder waren je-}
{10009}{}{doch nicht so gut dran. Sobald die Dreckskerle heraus-}
{10010}{}{hatten, wie leicht sie zu schlagen waren, begannen sie,}
{10011}{}{auf die unbewaffneten Zivilisten zu schießen.}
{10012}{}{**END-PAR**}
# -
{10013}{}{Es gab viele Verluste, jedoch wurde jedes verlorene}
{10014}{}{Leben eines Gruppenmitglieds von unseren Brüdern mit}
{10015}{}{zwei Leben aus dem Ödland vergolten.}
{10016}{}{**END-PAR**}
# -
{10017}{}{Schließlich erreichten die Vorfahren den sicheren Bunker.}
{10018}{}{Captain Maxson, der große Befreier, erklärte diesen zu}
{10019}{}{unserem neuen Zuhause, und alles war gut.}
{10020}{}{**END-PAR**}
# -
{10021}{}{Im Laufe der Zeit wurde der Bunker unser Zuhause, un-}
{10022}{}{ser Tempel, unsere Zuflucht vor den Schrecken der Au-}
{10023}{}{ßenwelt. Wir begannen, unsere Festung zu etwas Großar-}
{10024}{}{tigem aufzubauen. So etwas Schönes hatte diese Welt,}
{10025}{}{die der Technologie beraubt war, noch nie gesehen.}
{10026}{}{**END-PAR**}
# -
{10027}{}{Und dennoch gab es welche, die nach mehr strebten. Die-}
{10028}{}{se unruhigen Seelen verlangten von uns, nach Südosten}
{10029}{}{zu blicken und dort die fortschrittliche Technologie zu}
{10030}{}{suchen, die dort angeblich zu finden war.}
{10031}{}{**END-PAR**}
# -
{10032}{}{Captain Maxson warnte diese Hitzköpfe, dass das For-}
{10033}{}{schungsgelände dem Angriff zum Opfer gefallen sei, aber}
{10034}{}{sie wollten nicht auf ihn hören. Sie nahmen ihre gehei-}
{10035}{}{ligte Rüstung und machten sich auf, den Heiligen Gral}
{10036}{}{zu finden. Zuvor riefen sie vergebens den Namen des}
{10037}{}{Befreiers und stellten seine Tapferkeit in Frage!}
{10038}{}{**END-PAR**}
# -
{10039}{}{Von diesen Männern hatte man nie wieder etwas gehört.}
{10040}{}{**END-DISK**}

# *** Maxson Disk ***
{11000}{}{Ich, befehlshabender Offizier und Nachfolger des ver-}
{11001}{}{storbenen Colonel Robert Spindel in dieser Krisenzeit,}
{11002}{}{ordnete an, dass das gesamte Sicherheitsteam der Basis}
{11003}{}{zum Bunker bei Lost Hills verlegt wurde.}
{11004}{}{**END-PAR**}
# -
{11005}{}{Dieser Befehl erstreckte sich auch auf die Familien der}
{11006}{}{Offiziere und Unteroffiziere.}
{11007}{}{**END-PAR**}
# -
{11008}{}{Solange keine anders lautende Anweisung von einem or-}
{11009}{}{dentlichen Stellvertreter des Kriegsministeriums kommt,}
{11010}{}{gilt dieser Befehl weiterhin.}
{11011}{}{**END-PAR**}
# -
{11012}{}{Anweisung 1: Alle Militärangehörigen und ihre Familien}
{11013}{}{müssen die Basis bis 08:00 Uhr, 25. Oktober 2077, ver-}
{11014}{}{lassen. Das gesamte Personal hat sich zur Basis Lost Hill}
{11015}{}{zu begeben. Ausnahmen werden nicht gewährt.}
{11016}{}{**END-PAR**}
# -
{11017}{}{Anweisung 2: Das gesamte zivile Personal bleibt solange}
{11018}{}{an der Basis, bis es Befehle von seinem Vorgesetzten}
{11019}{}{erhält.}
{11020}{}{**END-PAR**}
# -
{11021}{}{Anweisung 3: Die Ausrüstung, die zum Überleben der Mili-}
{11022}{}{tärangehörigen der Basis erforderlich ist, ist aus Ge-}
{11023}{}{schäftsbeständen zusammenzustellen. Eine schriftliche}
{11024}{}{Genehmigung folgt, sofern es die Zeit erlaubt.}
{11025}{}{**END-PAR**}
# -
{11026}{}{Anweisung 4: Das Militärrecht wird strikt durchgesetzt,}
{11027}{}{und zwar sowohl bei Militärangehörigen als auch bei Zivi-}
{11028}{}{listen in gemeinsamen militärischen Operationen.}
{11029}{}{**END-PAR**}
# -
{11030}{}{Anweisung 5: Bis eine kontinuierliche Kommunikation mit}
{11031}{}{dem Kriegsministerium hergestellt werden kann, haben}
{11032}{}{diese Befehle Vorrang vor jeglichen zuvor erteilten Be-}
{11033}{}{fehlen.}
{11034}{}{**END-PAR**}
# -
{11035}{}{Captain Maxson}
{11036}{}{24. Oktober 2077}
{11037}{}{**END-DISK**}

# *** Richard Grey audio diary ***
{12000}{}{                                                    0000 - 0004}
{12001}{}{Mein Tod ist nahe. Ich muss all dies aufschreiben, bevor}
{12002}{}{mich die Schmerzen überwältigen.}
{12003}{}{**END-PAR**}
# -
{12004}{}{                                                    0005 - 0020}
{12005}{}{Ich kann kaum glauben, dass ich mich schließlich aus diesem}
{12006}{}{Container befreien konnte. Der Schleim konnte mir nichts}
{12007}{}{anhaben, aber dafür bin ich fast ertrunken. Ich weiß}
{12008}{}{nicht, was Harold zustieß. Er stand direkt neben mir, als}
{12009}{}{mich der Kran in den Container stieß. Er muss umgekommen}
{12010}{}{sein; er hätte mir sonst bestimmt geholfen. Francine ist}
{12011}{}{tot. Sie wurde von einem dieser Roboter getötet.}
{12012}{}{**END-PAR**}
# -
{12013}{}{                                                    0021 - 0027}
{12014}{}{Ich habe keine Ahnung, wieviel Zeit vergangen ist. Ich}
{12015}{}{konnte den Computer knacken, um die Roboter auszu-}
{12016}{}{schalten und dies alles aufzuzeichnen, aber jetzt ver-}
{12017}{}{liere ich das Bewusstsein. Zu große Schmerzen ...}
{12018}{}{**END-PAR**}
# -
{12019}{}{                                                    0028 - 0043}
{12020}{}{Der grüne Schleim, in den ich fiel, ist die Ursache für all}
{12021}{}{die Mutationen, die wir bis hierher verfolgten. Meine Haut}
{12022}{}{eitert und schält sich. An einigen Stellen haben sich Bla-}
{12023}{}{sen gebildet, und eine grüne schleimartige Substanz tritt}
{12024}{}{aus. An manchen Tagen ist der Schmerz fast erträglich.}
{12025}{}{**END-PAR**}
# -
{12026}{}{                                                    0044 - 0057}
{12027}{}{Ich kann jetzt wieder ein paar Schritte gehen ... Es ist}
{12028}{}{kaum zu glauben, dass ich mich den ganzen Weg von dem}
{12029}{}{Containerraum bis hierher schleppen konnte. Eigenarti-}
{12030}{}{gerweise fühle ich mich stärker, obwohl ich immer noch}
{12031}{}{große Schmerzen habe. Alles scheint kleiner zu werden.}
{12032}{}{**END-PAR**}
# -
{12033}{}{                                                    0058 - 0096}
{12034}{}{Ich glaube, ich habe heute eines dieser mutierten Dinger}
{12035}{}{gegessen, die hier herumlaufen. Bevor ich mich versah,}
{12036}{}{sprang eine Art Fangarm aus meinem Magen und erfasste}
{12037}{}{die arme Kreatur. Sobald er das Nagetier in meinen Ma-}
{12038}{}{gen gezogen hatte, konnte ich seine Gedanken spüren -}
{12039}{}{glaube ich zumindest. Vielleicht werde ich langsam ver-}
{12040}{}{rückt und kann nicht mehr richtig zwischen Wirklichkeit}
{12041}{}{und Einbildung unterscheiden. Vielleicht vegetiere ich}
{12042}{}{noch immer in dem Container vor mich hin und bilde mir}
{12043}{}{das alles nur ein.}
{12044}{}{**END-PAR**}
# -
{12045}{}{                                                    0097 - 0111}
{12046}{}{Für mich wird von Tag zu Tag alles klarer. Dieses Toxin}
{12047}{}{hat meine geistige Verfassung wirklich verbessert. Ich}
{12048}{}{habe das Gefühl, ich kann sogar die komplexesten philo-}
{12049}{}{sophischen Fragen mühelos verstehen. Es ist so, als wä-}
{12050}{}{ren alle Schichten um das Gehirn herum abgetragen. Was}
{12051}{}{würde wohl passieren, wenn ich ein Tier länger in die}
{12052}{}{Container tauche? Würde es sein Bewusstsein steigern?}
{12053}{}{**END-PAR**}
# -
{12054}{}{                                                    0112 - 0134}
{12055}{}{Es geschehen die seltsamsten Dinge mit den Tieren. Sie}
{12056}{}{werden wirklich intelligenter und nehmen ihre Umgebung}
{12057}{}{besser wahr. Ich habe heute einen Hund und eine Ratte}
{12058}{}{gleichzeitig eingetaucht, und sie sind miteinander ver-}
{12059}{}{schmolzen. Jetzt sind es zwar keine zwei Lebewesen}
{12060}{}{mehr, aber dennoch mehr als eins. Vielleicht ist das ja}
{12061}{}{die Zukunft - die Verschmelzung verschiedener Lebewe-}
{12062}{}{sen zu einer harmonischen Einheit. Ich benutze die Tiere,}
{12063}{}{die ich erzeuge, nicht mehr als Nahrungsmittel. Ich bin}
{12064}{}{nun das Instrument, mit dem diese Einheit erzielt wer-}
{12065}{}{den kann. Ich bin jetzt viel mehr als nur ein Mensch.}
{12066}{}{**END-PAR**}
# -
{12067}{}{                                                    0135 - 0139}
{12068}{}{Es ist an der Zeit, anderen die Herrlichkeit der Einheit}
{12069}{}{näherzubringen.}
{12070}{}{**END-PAR**}
# -
{12071}{}{                                                    0140 - 0153}
{12072}{}{Eine verlorene Seele hatte sich zu mir verirrt. Leider}
{12073}{}{aß ich das Wesen, bevor ich es eintauchen konnte. Das}
{12074}{}{passiert mir nicht noch mal. Sein Verstand war so primi-}
{12075}{}{tiv, dass er auf meine kognitiven Sinne negativ wirkte.}
{12076}{}{**END-PAR**}
# -
{12077}{}{                                                    0154 - 0172}
{12078}{}{Für die Einheit nehme ich jetzt an mir selbst Verände-}
{12079}{}{rungen vor, indem ich mir das Virus injiziere. Der Schleim}
{12080}{}{in den Containern ist ein von Menschen geschaffenes Vi-}
{12081}{}{rus, das FEV-Virus. Dies erfuhr ich über meine neu ge-}
{12082}{}{schaffene Neuroverbindung zum Computer der Basis.}
{12083}{}{**END-PAR**}
# -
{12084}{}{                                                     0173 - 0198}
{12085}{}{Die wenigen Umherirrenden, die ihren Weg hierher gefun-}
{12086}{}{den haben, waren eine Enttäuschung für mich. Sie mutier-}
{12087}{}{ten nicht richtig. Das Beste, was ich produzieren konnte,}
{12088}{}{waren einige große, dumme Mutanten. Die meisten können}
{12089}{}{sich nicht einmal an ihr Leben vor der wundersamen Ein-}
{12090}{}{heit erinnern. Ich ernähre mich nur noch von ihnen. Ihr}
{12091}{}{Verstand bedeutet mir gar nichts.}
{12092}{}{**END-PAR**}
# -
{12093}{}{                                                     0199 - 0236}
{12094}{}{Endlich! Ich habe es geschafft, die Freude der Einheit}
{12095}{}{auf eine andere Seele zu übertragen! Anders als bei den}
{12096}{}{anderen war die Verstrahlung sehr niedrig. Ich denke,}
{12097}{}{diesen Faktor haben wir die ganze Zeit übersehen. Weni-}
{12098}{}{niger verstrahlte Kreaturen lassen sich viel besser um-}
{12099}{}{wandeln. Ich habe mich noch nie so gut gefühlt wie in}
{12100}{}{dem Moment, als ich seinen Verstand in uns aufnahm.}
{12101}{}{**END-PAR**}
# -
{12102}{}{                                                     0237 - 0281}
{12103}{}{Wir erschaffen nun eine Armee, die sich der Einheit der}
{12104}{}{wunderbaren Lebensvielfalt widmet. Wir haben ihnen ge-}
{12105}{}{zeigt, unsere Arbeit fortzuführen, während wir nach}
{12106}{}{Gebieten suchen, die wir in uns aufnehmen können. Wir}
{12107}{}{spüren langsam die Grenzen eines beweglichen Körpers.}
{12108}{}{Wir brauchen ein dauerhaftes Zuhause, mit mehr Wissen}
{12109}{}{und einem unerschöpflichen Vorrat an Biomasse.}
{12110}{}{**END-PAR**}
# -
{12111}{}{                                                     0282 - 0303}
{12112}{}{Wir wollen uns nicht mehr weiter vergrößern, bis wir das}
{12113}{}{neue Vereinigungszentrum gefunden haben. Dann werden}
{12114}{}{wir wieder wachsen und uns ernähren, bis wir der ganzen}
{12115}{}{Welt Frieden und Einheit gebracht haben.}
{12116}{}{**END-DISK**}

# *** Captain Maxson's Diary ***
{13000}{}{• 10. Oktober 2077}
{13001}{}{Ich, Roger Maxson, Captain, Seriennummer 072389, habe}
{13002}{}{dieses Protokoll begonnen, weil es für keinen von uns}
{13003}{}{gut aussieht, und ich möchte, dass die Menschen erfahren,}
{13004}{}{was hier wirklich passiert ist. Es war der Teufel los,}
{13005}{}{als wir herausfanden, was diese Wissenschaftler vor-}
{13006}{}{hatten. Der Colonel hat sich in seinem Büro eingeschlos-}
{13007}{}{sen und hat wohl anscheinend einen Zusammenbruch. Die}
{13008}{}{Männer schreien nach Kampf. Sie erwarten von mir eine}
{13009}{}{Antwort, und ich weiß nicht genau, was ich tun soll.}
{13010}{}{Aber irgend jemand muss etwas tun, bevor dieser Ort in}
{13011}{}{in einem anarchistischen Blutbad versinkt.}
{13012}{}{**END-PAR**}
# -
{13013}{}{• 12. Oktober 2077}
{13014}{}{Immer, wenn wir von weiter oben einen Bericht erhalten,}
{13015}{}{wird alles noch schlimmer. Der Krieg wird immer schreck-}
{13016}{}{licher. Eine Meuterei steht unmittelbar bevor, die Chaos}
{13017}{}{bedeutet. Ich konnte heute einen der Männer daran hin-}
{13018}{}{dern, einen Wissenschaftler zu töten, und ordnete ein}
{13019}{}{Verhör an, um herauszufinden, wie ihr Auftrag lautete.}
{13020}{}{**END-PAR**}
# -
{13021}{}{• 13. Oktober 2077}
{13022}{}{Ich habe heute einen Mann getötet. Beim Verhör des wis-}
{13023}{}{senschaftlichen Leiters Anderson erfuhr ich alles über}
{13024}{}{ihre unmenschlichen Experimente. Anderson behauptete,}
{13025}{}{ihr Auftrag käme von der Regierung, aber das nahm ich}
{13026}{}{ihm nicht ab. Er schrie, dass er als Soldat doch nur seine}
{13027}{}{Befehle befolgt habe, woraufhin ich ihn einfach erschoß.}
{13028}{}{Jetzt rede ich mir ein, dass ich es nur tat, damit er keine}
{13029}{}{Meuterei anzetteln konnte, aber ich bin mir nicht sicher.}
{13030}{}{**END-PAR**}
# -
{13031}{}{• 15. Oktober 2077}
{13032}{}{Ich versuchte erneut, mit dem Colonel durch die Tür zu}
{13033}{}{sprechen, aber er scheint jeglichen Bezug zur Realität}
{13034}{}{verloren zu haben. Mit einigen Männern trat ich die Tür}
{13035}{}{ein, gerade rechtzeitig, um mitanzusehen, wie er sich er-}
{13036}{}{schoß. Bevor er abdrückte, sagte er, es täte ihm leid.}
{13037}{}{**END-PAR**}
# -
{13038}{}{• 18. Oktober 2077}
{13039}{}{Indem ich diesen Typ tötete, habe ich anscheinend meine}
{13040}{}{Stellung als Anführer der Männer bestätigt. Sie folgen}
{13041}{}{mir, ohne Fragen zu stellen. Die Verhöre enden stets mit}
{13042}{}{Tod. Shellman hat am längsten durchgehalten, aber das}
{13043}{}{Endergebnis war dasselbe. Ihre Angaben über die Befehle}
{13044}{}{waren ein bisschen zu detailliert, um völlig erfunden zu}
{13045}{}{sein. Ich habe ein wirklich ungutes Gefühl im Magen, wie}
{13046}{}{das wohl alles enden wird. Ich belüge mich nicht einmal}
{13047}{}{mehr selbst, warum ich die Wissenschaftler töte.}
{13048}{}{**END-PAR**}
# -
{13049}{}{• 20. Oktober 2077}
{13050}{}{Ich nahm schließlich mit der Außenwelt über Funk Kontakt}
{13051}{}{auf. Ich weiß nicht, weshalb sie keinen schickten, um}
{13052}{}{herauszufinden, warum wir nicht mehr auf ihre Meldungen}
{13053}{}{reagierten. Keine Ahnung. Naja, sie werden wohl schon}
{13054}{}{kommen. Ich erklärte unsere Unabhängigkeit von der Uni-}
{13055}{}{on. Das erinnert irgendwie an Jefferson Davis. Was wird}
{13056}{}{wohl mal über mich in den Geschichtsbüchern stehen?}
{13057}{}{**END-PAR**}
# -
{13058}{}{• 22. Oktober 2077}
{13059}{}{Was zum Teufel ist hier los? Wir erklären unsere Deser-}
{13060}{}{tation aus der Armee und unsere Unabhängigkeit von}
{13061}{}{allen Regierungsbefehlen, und was passiert? Nichts!}
{13062}{}{Irgend etwas liegt in der Luft.}
{13063}{}{**END-PAR**}
# -
{13064}{}{• 23. Oktober 2077}
{13065}{}{Ich kann nicht fassen, dass diese Schweine es tatsächlich}
{13066}{}{fertigbrachten. Zur Hölle mit ihnen! Sie haben also wirk-}
{13067}{}{lich die Atombomben losgeschickt. Wir waren gerade dabei,}
{13068}{}{die Wahrheit aus von Felden herauszuholen, als der Kon-}
{13069}{}{takt ganz abbrach. Ich glaube, das Forschungszentrum}
{13070}{}{hat es schlimm erwischt. Ich weiß nicht warum, nur so ein}
{13071}{}{Gefühl im Magen. Unbegreiflicherweise waren wir nicht die}
{13072}{}{Zielscheibe, aber ich bin sicher, China wird dieses Ver-}
{13073}{}{sehen bald nachholen. Zum Glück brachten wir unsere Fa-}
{13074}{}{milien vorgestern zur Basis. Wir wissen nicht, ob dort}
{13075}{}{schon radioaktiver Niederschlag niedergegangen ist.}
{13076}{}{**END-PAR**}
# -
{13077}{}{• 25. Oktober 2077}
{13078}{}{Sgt. Platner meldete sich freiwillig, heute nach draußen}
{13079}{}{zu gehen und Luftmessungen durchzuführen. Anscheinend}
{13080}{}{hat sich die radioaktive Strahlung nicht so weit ausge-}
{13081}{}{breitet. Da er seine Powerrüstung trug, bestand für ihn}
{13082}{}{keine Verstrahlungsgefahr. Hätte er jedoch Strahlung}
{13083}{}{abbekommen, hätten wir ihn verbannen müssen, denn wir}
{13084}{}{haben keine geeigneten Dekontaminierungsmöglichkeiten.}
{13085}{}{**END-PAR**}
# -
{13086}{}{• 25. Oktober 2077}
{13087}{}{Ich überredete die Männer, die Wissenschaftler zu begra-}
{13088}{}{ben. Ich weiß nicht warum, vielleicht um mein Gewissen zu}
{13089}{}{beruhigen. Ich fing langsam an, ihnen ihre Geschichten zu}
{13090}{}{glauben, als der letzte starb. Was ist nur aus mir geworden?}
{13091}{}{**END-PAR**}
# -
{13092}{}{• 27. Oktober 2077}
{13093}{}{Wir verlassen heute diesen gottverlassenen Ort. Ich leite}
{13094}{}{den Rückzug zum alten Regierungsbunker bei Lost Hills.}
{13095}{}{Ich lasse dieses Protokoll zurück, damit es begraben wird,}
{13096}{}{wenn dieser Ort untergeht. Wer weiß, vielleicht findet es}
{13097}{}{eines Tages irgend jemand ...}
{13098}{}{**END-DISK**}


# Computer Download of the FEV project
# Uses the global var COMPUTER_FEV

{14000}{}{FEV-Zusammenfassung:}
{14001}{}{**END-PAR**}
{14002}{}{2073. Als China seine biologischen Waffen immer aggres-}
{14003}{}{siver einsetzte, wurde die Notwendigkeit einer Gegen-}
{14004}{}{maßnahme für die Regierung der Vereinigten Staaten}
{14005}{}{immer unabdingbarer. Am 15. September 2073 wurde das}
{14006}{}{Panimmunitätsvirusprojekt (PVP) offiziell gegründet.}
{14007}{}{**END-PAR**}
#
{14008}{}{2075. Es wurde deutlich, dass die beste Art der Bekämp-}
{14009}{}{fung der neu hergestellten biologischen Waffen darin}
{14010}{}{bestand, nicht infizierte DNA so zu verändern, dass sie}
{14011}{}{nicht mehr auf normale Virusinfektionen ansprach.}
{14012}{}{**END-PAR**}
#
{14013}{}{2076. In dem PVP-Projekt traten unvorhergesehene Ne-}
{14014}{}{benwirkungen erstmals Anfang 2076 auf. Die Versuchs-}
{14015}{}{tiere zeigten ein anomales Wachstum und eine erhöhte}
{14016}{}{Hirntätigkeit. Die US-Regierung nahm diese Ergebnisse}
{14017}{}{zur Kenntnis und stellte im Interesse der nationalen}
{14018}{}{Sicherheit ein Team vor Ort ab, um die Sicherheit des}
{14019}{}{Projekts zu gewährleisten, das von nun an als FEV-Pro-}
{14020}{}{jekt (Forced Evolutionary Virus) bezeichnet wurde.}
{14021}{}{**END-PAR**}
#
{14022}{}{2077. Das FEV-Projekt steht vor dem Abschluss. Versu-}
{14023}{}{che mit Labortieren erzielten eine Erfolgsquote von}
{14024}{}{fast 100 %. Körpergröße und Muskeldichte nehmen um ca.}
{14025}{}{60 % zu und die potentielle Intelligenz um 200 %. Die}
{14026}{}{Auswirkungen auf menschliche Organismen bleiben unbe-}
{14027}{}{kannt; rein theoretisch sind sie jedoch sehr vielver-}
{14028}{}{sprechend. Das Militär, das weitere Tests plant, baut}
{14029}{}{eine große Anlage nahe der Mariposa-Militärbasis in}
{14030}{}{Mittelkalifornien. Dort werden die Versuche mit dem FEV-}
{14031}{}{Virus an freiwilligen Personen des Militärs fortgeführt.}
{14032}{}{**END-DISK**}


# Computer Downlod of the Power Armor Specs
# Uses the global var COMPUTER_POWER_ARMOR

{15000}{}{Die T 51b-Powerrüstung ist mit den neuesten Verteidi-}
{15001}{}{gungsfunktionen für zivile und militärische Zwecke aus-}
{15002}{}{gestattet. Das am Rücken befestigte TX28-Mikrofusi-}
{15003}{}{onspaket erzeugt 60.000 Watt, um die in den Anzug ein-}
{15004}{}{gebauten HiFlo-Hydrauliksysteme anzutreiben. Die T 51b-}
{15005}{}{Panzerung aus dem neuesten Polylaminat-Verbundstoffen}
{15006}{}{ist extrem leicht und kann kinetische Enerigie von mehr}
{15007}{}{als 2.500 Joules absorbieren. Die 10 Mikron dicke ablati-}
{15008}{}{ve Silberschicht kann Laser- und Strahlenemissionen re-}
{15009}{}{flektieren, ohne die Verbundoberfläche zu beschädigen.}
{15010}{}{**END-DISK**}


# Computer Download of the Personel Records
# Uses the global var COMPUTER_RECORDS

{16000}{}{Robert Anderson}
{16001}{}{Forschungsassistent}
{16002}{}{Sicherheitsstufe: Blau}
{16003}{}{Stationiert: Mariposa-Militärbasis}
{16004}{}{**END-PAR**}
#
{16005}{}{Nick Davis}
{16006}{}{Leiter NBC-Abteilung, West Tech-Forschungszentrum}
{16007}{}{Sicherheitsstufe: Blau}
{16008}{}{Stationiert: West Tech-Forschungszentrum}
{16009}{}{**END-PAR**}
#
{16010}{}{John Isaac}
{16011}{}{Forschungsassistent}
{16012}{}{Sicherheitsstufe: Rot}
{16013}{}{Stationiert: West Tech-Forschungszentrum}
{16014}{}{**END-PAR**}
#
{16015}{}{Steve Remco}
{16016}{}{Forschungsassistent}
{16017}{}{Sicherheitsstufe: Blau}
{16018}{}{Stationiert: Mariposa-Militärbasis}
{16019}{}{**END-PAR**}
#
{16020}{}{Charles Rignhold}
{16021}{}{Forschungsleiter Laserabteilung}
{16022}{}{Sicherheitsstufe: Blau}
{16023}{}{Stationiert: West Tech-Forschungszentrum}
{16024}{}{**END-PAR**}
#
{16025}{}{Michele Santose}
{16026}{}{Labortechniker}
{16027}{}{Sicherheitsstufe: Rot}
{16028}{}{Stationiert: West Tech-Forschungszentrum}
{16029}{}{**END-PAR**}
#
{16030}{}{Erin Shellman}
{16031}{}{Labortechniker}
{16032}{}{Sicherheitsstufe: Blau}
{16033}{}{Stationiert: Mariposa-Militärbasis}
{16034}{}{**END-PAR**}
#
{16035}{}{Leon von Felden}
{16036}{}{Forschungsleiter FEV-Virus}
{16037}{}{Sicherheitsstufe: Blau}
{16038}{}{Stationiert: Mariposa-Militärbasis}
{16039}{}{**END-DISK**}

# Holodisk from the Brotherhood Library
# uses the global var BROTHERHOOD_LIBRARY_DISK

{17000}{}{Vaultstandorte v34.129 Revision C (West-USA)}
{17001}{}{**END-PAR**}
#
{17002}{}{Willkommen zur neuesten Ausgabe der Broschüre 'Vault-}
{17003}{}{Standorte der West-USA'! Wir hoffen, dass Ihnen die Bro-}
{17004}{}{schüre gefällt und Sie immer daran denken, dass Vaults}
{17005}{}{nicht nur für Erfolgreiche, sondern für alle da sind.}
{17006}{}{**END-PAR**}
#
{17007}{}{Vault 12}
{17008}{}{**END-PAR**}
#
{17009}{}{Unter der wachsenden Metropole Bakersfield liegt der}
{17010}{}{technologische Glanz der Vault 12. Ausgestattet mit}
{17011}{}{allem, was der künftige Vaultbewohner begehrt, erhielt}
{17012}{}{die Vault 12 für ihre Sicherheitsvorkehrungen den Preis}
{17013}{}{'Beste Vaultausstattung'. Der Schutz, den diese tief}
{17014}{}{unter der Erde liegende Vault ihren Bewohnern bietet,}
{17015}{}{ist beispiellos. Wie alle Vaults wurde auch die Vault}
{17016}{}{12 mit den neuestem Wasserreinigungssystem ausgestat-}
{17017}{}{tet. Da dieses System sogar die Abwässer aus der Kana-}
{17018}{}{lisation von Bakersfield aufbereiten kann, stehen täg-}
{17019}{}{lich über 15.000 Gallonen reines Trinkwasser zur Ver-}
{17020}{}{fügung.}
{17021}{}{**END-PAR**}
#
{17022}{}{Vault 13}
{17023}{}{**END-PAR**}
#
{17024}{}{In einer landschaftlich schönen Bergregion nordwestlich}
{17025}{}{der Vault 12 gelegen, bietet diese Vault seinen Bewoh-}
{17026}{}{nern einen endlosen Vorrat reinen Wassers. Die Gerüchte,}
{17027}{}{dass das Wasser in diesem Gebiet in einem Atomkrieg ver-}
{17028}{}{seucht werden könnte, wurden vom Ministerium für Wasser}
{17029}{}{und Strom als völlig unbegründet zurückgewiesen. Für den}
{17030}{}{unwahrscheinlichen Fall, dass das Wasser in diesem Gebiet}
{17031}{}{verschmutzt werden sollte, wurde die Vault 13 mit dem}
{17032}{}{von der Regierung genehmigten Wasserreinigungssystem}
{17033}{}{ausgestattet. Da dieses System ohne großen Verlust}
{17034}{}{mehr als 250.000 Stunden arbeiten kann, haben die künf-}
{17035}{}{tigen Vaultbewohner nichts zu befürchten.}
{17036}{}{**END-PAR**}
#
{17037}{}{Vault 15}
{17038}{}{**END-PAR**}
#
{17039}{}{Östlich der Vault 13 konnte das Bauvorhaben 'Vault 15'}
{17040}{}{problemlos umgesetzt werden. In die Verstärkung der}
{17041}{}{Wände auf der dritten Ebene wurde viel Arbeit gesteckt.}
{17042}{}{So können die zukünftigen Vaultbewohner sicher sein,}
{17043}{}{dass der Steuercomputer der Vault selbst bei einem}
{17044}{}{starken Erdbeben weiterhin funktioniert. Bei der Be-}
{17045}{}{sichtigung der neu erbauten Vault haben viele poten-}
{17046}{}{tielle Vaultbewohner die Verbesserungen dieser ohnehin}
{17047}{}{schon beeindruckenden Vault ehrfürchtig bestaunt.}
{17048}{}{ }
{17049}{}{**END-DISK**}

#Regulator Disk from Blades

{18000}{}{Funkübertragungsprotokoll des Regulators:}
{18001}{}{**END-PAR**}
{18002}{}{Nachricht gesendet: Regulatorpatrouille an Regulator-}
{18003}{}{basis. Verstanden? Over.}
{18004}{}{**END-PAR**}
{18005}{}{Nachricht erhalten: Hier Regulatorbasis, Hauptregulator}
{18006}{}{Caleb antwortet. Bericht? Over.}
{18007}{}{**END-PAR**}
{18008}{}{Nachricht gesendet: Sir. Ja, Sir! Regulator zweiter Klas-}
{18009}{}{se Cravotta berichtet. Wir haben diesen Zimmerman fest-}
{18010}{}{genommen, als er erneut versuchte, unsere Peripherie}
{18011}{}{zu durchdringen, Sir. Befehle? Over.}
{18012}{}{**END-PAR**}
{18013}{}{Nachricht erhalten: Mist! Schon wieder! Na, das war das}
{18014}{}{letzte Mal! Eliminieren Sie ihn, und lassen Sie es so aus-}
{18015}{}{sehen, als hätten es die Blades getan. Verstanden?}
{18016}{}{Over.}
{18017}{}{**END-PAR**}
{18018}{}{Nachricht gesendet: Sir? Hä ... habe ich das richtig ver-}
{18019}{}{standen, Sir? Ihn töten? Over.}
{18020}{}{**END-PAR**}
{18021}{}{Nachricht erhalten: Positiv, Regulator. Es soll grausam}
{18022}{}{aussehen. Fesseln Sie ihn an einen Pfahl ... und bringen}
{18023}{}{Sie ihn zum Schweigen, so dass er nicht reden kann, wäh-}
{18024}{}{rend wir uns um ihn 'kümmern'. Over.}
{18025}{}{ }
{18026}{}{**END-PAR**}
{18027}{}{Nachricht gesendet: Wird gemacht, Sir. Over.}
{18028}{}{**END-PAR**}
{18029}{}{Ende der Übertragung.}
{18030}{}{**END-DISK**}


