##
## NOTE: Each line in the description box holds roughly 40 characters in English. Meaning to add a blank line, add 40 spaces and then reduce as needed.
##       This will differ based on words used (since it wraps based on the word length)  --Sduibek, Fallout Fixt
##
#
#  Messages from perk.c
#
#
#  PERK NAMES
#
#
{101}{}{Intuition}
{102}{}{Bonus attaques en Rixe}
{103}{}{Bonus dégâts en Rixe}
{104}{}{Bonus déplacement}
{105}{}{Bonus dégâts à distance}
{106}{}{Bonus cadence de tir}
{107}{}{Meilleure position}
{108}{}{Guérison plus rapide}
{109}{}{Plus de coups critiques}
{110}{}{Vision nocturne}
{111}{}{Présence}
{112}{}{Résistance aux rad.}
{113}{}{Résistance}
{114}{}{Dos résistant}
{115}{}{Tireur d'élite}
{116}{}{Course silencieuse}
{117}{}{Survivant}
{118}{}{Maître marchand}
{119}{}{Erudit}
{120}{}{Guérisseur}
{121}{}{Découvreur de trésor}
{122}{}{Meilleurs coups critiques}
{123}{}{Empathie}
{124}{}{Tueur}
{125}{}{Tireur embusqué}
{126}{}{Mort silencieuse}
{127}{}{Homme d'action}
{128}{}{Bloc mental}
{129}{}{Donneur de vie}
{130}{}{Tire-au-flanc}
{131}{}{Mangeur de serpents}
{132}{}{M. Réparetout}
{133}{}{Médecin}
{134}{}{ERREUR - DÉSACTIVÉ} # was -- Master Thief
{135}{}{Orateur}
{136}{}{Oh Hisse !}
{137}{}{ERREUR - LIBRE}  # was -- Friendly Foe
{138}{}{Pickpocket}
{139}{}{Fantôme}
{140}{}{Culte de la personnalité}
{141}{}{Chapardeur}
{142}{}{Explorateur}
{143}{}{Enfant des Fleurs}
{144}{}{Pionnier}
{145}{}{Ami des animaux}
{146}{}{Eclaireur}
{147}{}{Etranger mystérieux}
{148}{}{Commando}
{149}{}{Poches}
{150}{}{Beau parleur}
{151}{}{Elève vif}
{152}{}{Atout !}
{153}{}{Mutation !}
{154}{}{Obsédé du Nuka Cola}    # Other ideas: "Sodalicious", "Cola Fiend".  (Sduibek's was "Coke Fiend" previously, which - oops - doesn't work because it's not COCA-Cola.)
{155}{}{Taré de la gonflette (dépendance au Buffout)}     # TRANSLATORS: Slang word for a person who uses/abuses steroids.
{156}{}{Fondu du crâne (dépendance au Mentats)}    # Other ideas: "Mental", "Mentalist", "Brainiac", etc.  TRANSLATORS: Slang for "totally crazy"
{157}{}{Psychopathe ! (dépendance au Psycho)}    # Other ideas: Could add stylized emphasis such as "Psycho !" or "PSYCHO".
{158}{}{Rayonnant (dépendance au RadAway)}      # Could use suggestions for other ideas on this.
{159}{}{Armes à longue portée}
{160}{}{Armes de précision}
{161}{}{Armes pénétrantes}
{162}{}{Armes contondantes (Pousser)}
{163}{}{SuperArmure}
{164}{}{Armure de combat}
{165}{}{Arme à lunette}
{166}{}{Arme à recharge rapide}
{167}{}{Arme avec viseur de nuit}
{168}{}{Arme lance-flamme (Torche Humaine)}
{169}{}{Armure avancée I}
{170}{}{Armure avancée II}
{171}{}{Dépendance au Jet}
{172}{}{Dépendance aux cartes Tragic}
{173}{}{Charisme d'armure}
{174}{}{Ecorchage de gecko}
{175}{}{Armure à impact dermique}
{176}{}{Meilleure attaque à impact dermique}
{177}{}{Implants d'armure de Phoenix}
{178}{}{Amélioration de l'attaque Phoenix}
{179}{}{Inoculations de la Cité de l'Abri}
{180}{}{Poussée d'adrénaline}
{181}{}{Nature prudente}
{182}{}{Compréhension}
{183}{}{Expert en démolition}
{184}{}{Joueur}
{185}{}{Gain de force}
{186}{}{Gain de perception}
{187}{}{Gain d'endurance}
{188}{}{Gain de charisme}
{189}{}{Gain d'intelligence}
{190}{}{Gain d'agilité}
{191}{}{Gain de chance}
{192}{}{Sans danger}
{193}{}{Ici et là}
{194}{}{Evasion}
{195}{}{Maître du Kama Sutra}
{196}{}{Signal du Karma}
{197}{}{Pas léger}
{198}{}{Anatomie vivante}
{199}{}{Personnalité magnétique}
{200}{}{Négociateur}
{201}{}{Voyageur organisé}
{202}{}{Pyromane}
{203}{}{Récupération rapide}
{204}{}{Vendeur}
{205}{}{Muraille}
{206}{}{Maître Voleur} # was -- Thief
{207}{}{Manipulation des armes}
{208}{}{Entraînement de la Cité}
{209}{}{PI accrus par l'alcool}
{210}{}{PI accrus par l'alcool II}
{211}{}{PI réduits par l'alcool}
{212}{}{PI réduits par l'alcool II}
{213}{}{PI accrus par l'autodoc}
{214}{}{PI accrus par l'autodoc II}
{215}{}{PI réduits par l'autodoc}
{216}{}{PI réduits par l'autodoc II}
{217}{}{Expéditeur d'Excréments Expert}
{218}{}{Chances de K.O accrues}
{219}{}{La-Poisse}

#
#  PERK DESCRIPTIONS
#
##
## NOTE: Each line in the description box holds roughly 40 characters in English. Meaning to add a blank line, add 40 spaces and then reduce as needed.
##       This will differ based on words used (since it wraps based on the word length)  --Sduibek, Fallout Fixt
##
#
{1101}{}{Grâce à l'Intuition, tu recevras des informations détaillées sur toutes les créatures que tu examineras. Tu peux ainsi connaître leur nombre exact de points d'impact et obtenir des informations sur leurs armes.}
{1102}{}{Soit tu as appris les secrets des arts martiaux, soit tu cognes plus vite que tout le monde. Dans les deux cas, chaque attaque en Rixe (CàC ou Mêlée) te coûte 1 PA de moins.}
{1103}{}{Ton expérience du Corps à Corps fait de toi un adversaire redoutable. A chaque niveau de cette aptitude, tes attaques au Corps à Corps ou en Mêlée infligent +2 points de dégâts à ton adversaire.}
{1104}{}{A chaque niveau de cette aptitude, tu reçois 2 PA gratuits à chaque tour, uniquement utilisables pour te déplacer. Autrement dit, tu peux te déplacer de deux cases gratuitement pour chaque niveau de cette aptitude.}
{1105}{}{Ton expérience des armes à feu et des autres armes à distance te rend redoutable. A chaque niveau de cette aptitude, tu infliges +2 points de dégâts avec des armes à distance.}
{1106}{}{Cette aptitude te permet de tirer un peu plus vite tout en conservant la même précision. Chaque attaque avec une arme à distance te coûte 1 PA de moins.}
{1107}{}{Tu augmentes tes chances de précéder tes adversaires au combat, car à chaque niveau de cette aptitude, ta position (Séquence) augmente de +2.}
{1108}{}{A chaque niveau de cette aptitude, ta vitesse de guérison augmente de +2, ce qui te permet de guérir plus vite. Ceci vient s'ajouter à ta vitesse de guérison normale.}
{1109}{}{Avec cette aptitude, tu augmentes tes chances d'infliger des coups critiques au combat. Chaque niveau de cette aptitude augmente tes chances de +5%.}
{1110}{}{Grâce à la vision nocturne, tu vois mieux dans l'obscurité. Chaque niveau de cette aptitude réduit l'obscurité générale de 20%.}
{1111}{}{Tu attires l'attention simplement en traversant une pièce. La réaction initiale des personnes qui t'entourent est améliorée de 10% à chaque niveau de cette aptitude.}
{1112}{}{Tu échappes plus facilement aux radiations et à leurs effets nocifs. A chaque niveau de cette aptitude, ta résistance aux radiations augmente de 15%.}
{1113}{}{Lorsque ta résistance est élevée, tu subis moins de dégâts. A chaque niveau de cette aptitude, ta résistance générale augmente de +10%.}
{1114}{}{Alias Mulet. A chaque niveau de cette aptitude, tu peux transporter 25 Kg (50 lbs) de matériel en plus.}
{1115}{}{Tu as la capacité de toucher ta cible sur de plus longues distances. A chaque niveau de cette aptitude, tu reçois un bonus de +2 en Perception dans le but de déterminer la portée.}
{1116}{}{Avec cette aptitude, tu peux désormais courir tout en restant silencieux. Tu peux utiliser ta compétence Esquive et courir en même temps. Sans cette aptitude, tu ne pourrais pas faire les deux.}
{1117}{}{Cette aptitude te permet de survivre dans un environnement hostile. Tu reçois un bonus de +25% dans la compétence Vie en plein air.}
{1118}{}{Maître dans l'art de négocier, tu achètes des marchandises à des prix plus intéressants que quiconque. Tu bénéficies de 25% de remise sur les achats effectués dans un magasin ou auprès d'un marchand.}
{1119}{}{A chaque niveau de cette aptitude, tu reçois +2 points de compétence par niveau d’expérience supplémentaire acquis. Pour tirer le meilleur parti de cette aptitude, tâche de l'acheter au début de ton aventure.}
{1120}{}{Cette aptitude te permet de guérir plus efficacement les blessures. A chaque niveau de cette aptitude, tu reçois 4 à 10 points d'impact guéris supplémentaires lorsque tu utilises les compétences Secourisme ou Médecin.}
{1121}{}{Tu as le talent de trouver de l'argent, ou bien tu es juste chanceux. Tu trouveras plus d'argent au cours des rencontres aléatoires.}
{1122}{}{Les coups critiques que tu infliges au combat sont plus redoutables. Bonus de 20% sur le tableau des coups critiques. Tu crées donc plus de dégâts. Ceci n'affecte pas tes chances d'infliger des coups critiques.}
{1123}{}{Tu as étudié les autres êtres humains, ce qui te permet d'évaluer leurs réactions émotionnelles à ton égard. Tu peux voir le niveau de réaction de la personne avec qui tu parles lorsque tu entames avec elle une conversation approfondie.}
{1124}{}{La Mort est parmi nous ! Lors des combats en Rixe, tous tes coups sont transformés en coups critiques. Tu sèmes alors la terreur et la destruction sur ton passage.}
{1125}{}{Tu maîtrises le maniement des armes à feu pour semer la terreur. Avec cette aptitude, chaque tir réussi avec une arme à distance se transforme en coup critique, à condition de réussir un test de chance.}
{1126}{}{Avec cette aptitude, la compétence Esquive te permet de lancer une attaque en Rixe (CàC ou Mêlée) qui, si tu attaques ton adversaire par derrière, lui infligera deux fois plus de dégâts. C'est ça l'aptitude Mort Silencieuse !}
{1127}{}{A chaque niveau de l'aptitude Homme (ou Femme) d'action, tu reçois +1 PA supplémentaire à dépenser à chaque tour de combat. Ces PA peuvent être utilisés pour n'importe quelle tâche.}
{1128}{}{Le Bloc mental est l'aptitude à déjouer toute interférence mentale extérieure. Ce talent doit t'avoir été enseigné par un gourou de passage ou à la fin d'une soirée dans un bar.}
{1129}{}{A chaque niveau de cette aptitude, ton maximum de points d'impact augmente de 4. Tu reçois aussi un bonus de 4 points pour chaque niveau d'expérience supplémentaire. C'est peu, mais additionnés ces points peuvent t'être très utiles.}
{1130}{}{Lorsque tu possèdes cette aptitude, tes chances d'être touché(e) au combat diminuent. Tu reçois un bonus de Classe d'armure de +5, en plus du bonus de l'armure que tu portes.}
{1131}{}{Miam-miam ! Ca a le goût de poulet. Pour chaque niveau de cette aptitude, ta résistance au poison augmente de +25%.}
{1132}{}{Avec cette aptitude, tu reçois un bonus de +10% aux compétences Réparation et Science. Travailler tard le soir n'a jamais fait de mal personne, surtout pas toi !}
{1133}{}{Avec l'aptitude Médecin, tu reçois un bonus de +10% lorsque tu utilises les compétences Secourisme et Médecin. Etre capable de soigner est une bonne chose.}
{1134}{}{Sorry, due to technical reasons, this perk is now disabled.}
{1135}{}{Avec l'aptitude Orateur, tu reçois un bonus de +20% lorsque tu utilises la compétence Discours. La vérité sort de la bouche des enfants, il paraît...}
{1136}{}{A chaque niveau de cette aptitude, tu reçois +2 en Force (jusqu'à 10) pour déterminer la portée avec des armes de jet uniquement. Cet avantage ne permet pas de dépasser la portée maximale d'une arme.}
{1137}{}{ERREUR.LIBRE !}
{1138}{}{Avec cette aptitude, tu peux voler mieux que n'importe quel escroc, car ni la taille de l'objet ni l'angle d'attaque ne t'importent lorsque tu détrousses une personne.}
{1139}{}{Lorsque le soleil se couche, ou lorsque tu te trouves dans un lieu mal éclairé, cette aptitude te permet de te déplacer tel un fantôme. Dans l'obscurité, ta compétence de furtivité augmente de +20%.}
{1140}{}{Ta réputation est toujours positive. Sans cette aptitude, une mauvaise réputation aurait des effets négatifs sur les personnes bienveillantes. Même chose pour une bonne réputation face à des personnes malveillantes.}
{1141}{}{Tu peux trouver plus de munitions que n'importe quel survivant de la Grande Guerre. Cette aptitude double la quantité de munitions que tu trouveras au cours des rencontres aléatoires.}
{1142}{}{L'objectif de l'explorateur est de trouver de nouveaux sites intéressants. Avec cette aptitude, tu as plus de chances de découvrir des lieux ou des gens sortant de l'ordinaire.}
{1143}{}{Avec cette aptitude, tu as deux fois moins de chances de devenir accro aux stimulants et leurs effets secondaires durent deux fois moins longtemps que sur une personne normale.}
{1144}{}{Un Pionnier est plus apte que quiconque à trouver le chemin le plus court. A chaque niveau de cette aptitude, le temps qu'il te faut pour voyager sur la Carte du Monde est réduit de 25%.}
{1145}{}{Les animaux n'attaquent jamais leurs amis à moins d'être menacés ou attaqués. Quant à la définition du mot animal dans ce monde, le débat est ouvert.}
{1146}{}{Tu as amélioré ta capacité repérer des endroits éloignés, ce qui augmente la taille de tes explorations sur la carte du monde d'un carré dans chaque direction. Tu as aussi plus de chances de faire des rencontres spéciales.}
{1147}{}{Avec cette aptitude, tu as attiré l'attention d'un étranger mystérieux, qui apparaîtra de temps en temps pour t'aider. Si cet allié meurt au combat, ne t'attends pas à ce qu'on le remplace.}
{1148}{}{Tu gagnes +15% dans la compétence Vie en plein air. Tu as une meilleure capacité à éviter les rencontres aléatoires quand tu le désires, et tu as plus de chances de faire des rencontres spéciales.}
{1149}{}{Tu as appris à mieux ranger ton équipement. L'accès à ton inventaire en cours de combat ne te coûte que 2 points d'action au lieu de 4.}
{1150}{}{Les beaux parleurs s'expriment bien, sans forcément comprendre de quoi ils parlent. A chaque niveau de cette aptitude, tu reçois 1 point d'Intelligence à des fins de dialogue uniquement.}
{1151}{}{Tu apprends plus vite. A chaque niveau de cette aptitude, tu reçois un bonus de +5% lorsque tu gagnes des points d'expérience. A choisir de préférence au cours des premiers niveaux.}
{1152}{}{Compte tenu de l'amélioration de tes compétences, tu peux sélectionner un nouvel atout personnel. Les atouts peuvent être améliorés deux fois plus vite.}
{1153}{}{Les radiations du désert ont eu de l'influence sur toi ! Une de tes qualités s'est transformée en quelque chose d'autre...}
{1154}{}{Tu as une envie terrible de Nuka-Cola.}
{1155}{}{Tu as la tremblote.}
{1156}{}{Tu as les jambes en coton.}
{1157}{}{Tu as la tête qui tourne.}
{1158}{}{Tu as la nausée.}
{1159}{}{Armes à longue portée}
{1160}{}{Armes de précision}
{1161}{}{Armes pénétrantes}
{1162}{}{Armes contondantes (Pousser)}
{1163}{}{SuperArmure}
{1164}{}{Armure de combat}
{1165}{}{Arme à lunette}
{1166}{}{Arme à recharge rapide}
{1167}{}{Arme avec viseur de nuit}
{1168}{}{Arme lance-flamme (Torche Humaine)}
{1169}{}{Armure avancée I}
{1170}{}{Armure avancée II}
{1171}{}{Tout bouge si len-te-ment... Tu as besoin d'un bon coup de Jet, TOUT DE SUITE !}
{1172}{}{Tu ressens une envie irrépressible d'ouvrir une autre boîte de cartes Tragic.}
{1173}{}{Charisme d'armure}
{1174}{}{Tu sais comment dépouiller les geckos pour utiliser leur cuir.}
{1175}{}{Tu possèdes une protection inhérente contre les attaques physiques.}     # Dermal Impact Armor
{1176}{}{Tu possèdes une protection inhérente supplémentaire contre les attaques physiques.}  # Dermal Impact Assault Enhancement
{1177}{}{Tu possèdes une protection inhérente contre les attaques énergétiques.}     # Phoenix Armor Implants
{1178}{}{Tu possèdes une protection inhérente supplémentaire contre les attaques énergétiques.}   # Phoenix Assault Enhancement
{1179}{}{Tu as acquis une résistance de +10 % au poison et aux radiations.}  # Vault City Inoculations
{1180}{}{Avec cette aptitude, tu ajoutes +1 à ta force lorsque tu descends sous la moitié du maximum de tes points d'impact.}  # Adrenaline Rush
{1181}{}{Tu es plus alerte à l'extérieur et tes ennemis risquent moins de te surprendre. Avec cette aptitude, tu ajoutes +3 à ta perception pour déterminer le placement (Séquence) lors des rencontres aléatoires.}  # Cautious Nature
{1182}{}{Tu fais bien plus attention aux petits détails lorsque tu lis. Tu augmentes ton total de points de compétence gagnés de 50% en lisant des livres.}  # Comprehension
{1183}{}{Tu es un pro pour la manipulation d'explosifs. ce qui te permet de toujours les faire détonner au moment voulu. De plus, les explosions causent des dégâts supplémentaires.}  # Demolition Expert
{1184}{}{Tu peux jouer avec les meilleurs. Ta compétence Jeu augmente de 20 %.}  # Gambler
{1185}{}{Cette aptitude ajoute +1 à ta Force.}     # Gain Strength
{1186}{}{Cette aptitude ajoute +1 à ta Perception.}   # Gain Perception
{1187}{}{Cette aptitude ajoute +1 à ton Endurance.}    # Gain Endurance
{1188}{}{Cette aptitude ajoute +1 à ton Charisme.}     # Gain Charisma
{1189}{}{Cette aptitude ajoute +1 à ton Intelligence.} # Gain Intelligence
{1190}{}{Cette aptitude ajoute +1 à ton Agilité.}      # Gain Agility
{1191}{}{Cette aptitude ajoute +1 à ta Chance.}         # Gain Luck
{1192}{}{Ton air innocent t'aide à détrousser ton prochain. Ta compétence Voleur s'accroît de +20%.}  # Harmless
{1193}{}{Cette aptitude te fait aussitôt gagner un niveau d'expérience.}  # Here and Now
{1194}{}{Si les deux emplacements d'objet sont vides, chaque point d'action restant à la fin du tour donne +2 (au lieu de +1) à ta Classe d'armure, plus 1/12ème de ta compétence Corps à Corps.}  # HtH Evade
{1195}{}{Pour ce qui est du plaisir sexuel, tu es au sommet.}  # Kama Sutra Master
{1196}{}{Ton karma est deux fois plus puissant. Qu'il soit positif ou négatif, il est doublé en ce qui concerne les réactions et les modificateurs afférents.}  # Karma Beacon
{1197}{}{Tu es agile, tu as de la chance et tu fais preuve de prudence. Cette aptitude réduit de moitié tes chances de déclencher un piège.}  # Light Step
{1198}{}{Tu as une meilleure compréhension des créatures vivantes, de leurs points forts et de leurs points faibles. Tu obtiens un bonus unique de +10% en Médecine et tu infliges +5 de dégâts par attaque sur des créatures vivantes.}  # Living Anatomy
{1199}{}{Tu bénéficies d'un emplacement supplémentaire dans ta liste de compagnons. Mais attention, à plus de cinq, on commence à se sentir serré...}  # Magnetic Personality
{1200}{}{Tu es un négociateur très habile. Tu peux marchander avec les plus durs et te sortir des pires situations juste en parlant. Grâce à cette aptitude, tu gagnes +10% à Troc et à Discours.}  # Negotiator
{1201}{}{Préparer ton sac à dos et gérer ton inventaire, ça te connaît. Il devient donc plus facile de transporter ces petits riens dont on a toujours besoin.} # Pack Rat
{1202}{}{Tu occasionnes plus de dégâts par le feu et tes ennemis semblent toujours mourir de la manière la plus douloureuse imaginable.}  # Pyromaniac
{1203}{}{Tu récupères vite après avoir été mis K.O.} # Quick Recovery
{1204}{}{Tu as la fibre commerciale ! Grâce à cette aptitude, tu bénéficies de +20% pour ta compétence Troc.}  # Salesman
{1205}{}{Tu risques beaucoup moins de te faire mettre à terre lors d'un combat.}  # Stonewall
{1206}{}{Avec l'aptitude Maître Voleur, tu reçois un bonus de +10% lorsque tu utilises les compétences Esquive, Passe-partout, Voleur, et Pièges.}
{1207}{}{Tu sais manier des armes bien plus grosses que la normale. Tu reçois un bonus de +3 à tes tests de Force quand il s'agit de manier une arme.}  # Weapon Handling
{1208}{}{Tu as reçu une formation médicale à la Cité de l'Abri.}  # Vault City Training
{1209}{}{Tes points d'impact sont quelque peu accrus par ton ivrognerie.}  # Alcohol Enhanced hit points
{1210}{}{Tes points d'impact sont accrus encore un peu plus par ton ivrognerie.}  # Alcohol Enhanced hit points II
{1211}{}{Tes points d'impact sont quelque peu réduits par ton ivrognerie.}  # Alcohol Lowered hit points
{1212}{}{Tes points d'impact sont réduits encore un peu plus par ton ivrognerie.}  # Alcohol Lowered hit points II

{1213}{}{Tes points d'impact sont quelque peu accrus par l'usage répété de l'autodoc.}  # Autodoc Enhanced hit points
{1214}{}{Tes points d'impact sont accrus encore un peu plus par l'usage répété de l'autodoc.}  # Autodoc Enhanced hit points II
{1215}{}{Tes points d'impact sont quelque peu réduits par l'usage répété de l'autodoc.}  # Autodoc Lowered hit points
{1216}{}{Tes points d'impact sont réduits encore un peu plus par l'usage répété de l'autodoc.}  # Autodoc Lowered hit points II

{1217}{}{Tu peux te mesurer aux meilleurs.}
{1218}{}{Chances de K.O accrues avec l'utilisation d'une arme.}
{1219}{}{L'avantage, c'est que tout le monde autour de toi a plus d'échecs critiques en combat. L'inconvénient, c'est que... toi aussi !}
