{100}{}{Armure en cuir}
{101}{}{Ton vêtement de base, tout en cuir. Superbement confectionné à partir de peau de brahmine tannée. C'est le même genre que portaient les motards d'avant-guerre. }
{200}{}{Armure métallique}
{201}{}{Plaques de métal polies formant une armure grossière. Elle procure une meilleure protection que les armures en cuir, mais entrave quelque peu la mobilité du porteur. Ce modèle est bardé de pics sur les épaules, à la mode cette année !}
{300}{}{SuperArmure}
{301}{}{Armure spéciale ultra-sophistiquée T-51b de West Tek. Alimentée par un réacteur à micro-fusion qui contient assez de combustible pour fonctionner une centaine d'années. Sa structure est renforcée par des nanoparticules d'argent. Le casque est renforcé contre les balles.}
{400}{}{Couteau}
{401}{}{Arme blanche à lame ultra-tranchante. FO min : 2.}
{500}{}{Matraque}
{501}{}{Bâton militaire ou policier. En bois. FO min : 3.}
{600}{}{Massue}
{601}{}{Grande massue avec poignée. Très populaire chez les individus musclés. FO min : 6.}
{700}{}{Lance}
{701}{}{Arme blanche à lame tranchante. Le manche est en bois et la lame en acier. FO min : 4.}
{800}{}{Pistolet 10 mm}
{801}{}{Pistolet Colt 6520 10 mm à rechargement automatique. A chaque détente, l'arme se recharge automatiquement jusqu'à ce que le chargeur soit vide. Arme à tir simple utilisant des balles 10 mm. FO min : 3.}
{900}{}{Mitraillette 10 mm}
{901}{}{Mitraillette H&K MP9 (variante 10 mm). Mitraillette de taille moyenne utilisable en mode tir simple ou rafale. FO min : 4.}
{1000}{}{Carabine}
{1001}{}{Carabine semi-automatique Colt Rangemaster, calibre .223. Tir simple uniquement. FO min : 5.}
{1100}{}{Lance-flammes}
{1101}{}{Un lance-flammes Flambe-Tout modèle 450, variante Varmiter. Pulvérise et enflamme un court jet de liquide inflammable. Requiert un combustible spécial. Cette arme a tendance à tuer vos ennemis de chair et d'os dans d'atroces souffrances en se tordant de douleur, ce qui est plutôt hilarant. FO min : 6.}
{1200}{}{Minigun}
{1201}{}{Mini-canon personnel Rockwell CZ53. Fusil à chaîne avec multiples canons tirant des cartouches 5 mm à plus de 60 000 tours/minute. FO min : 7.}
{1300}{}{Lance-roquettes}
{1301}{}{Lance-roquettes Rockwell BigBazooka, avec détente de luxe modèle 3 lb. Tire des roquettes perforantes ou explosives. FO min : 6.}
{1400}{}{Roquette explosive}
{1401}{}{Roquette dotée d'une grosse ogive explosive.}
{1500}{}{Fusil à plasma}
{1501}{}{Fusil à plasma Winchester modèle P94. Arme à énergie de qualité industrielle, tirant des salves de plasma surchauffé via un canon supraconducteur. Alimenté par des Cellules à Micro Fusion. FO min : 6.}
{1600}{}{Pistolet laser}
{1601}{}{Pistolet laser Wattz 1000. Modèle civil à la puissance en watts inférieure aux versions de l'armée et de la police. Utilise des petites cellules énergétiques. FO min : 3.}
{1700}{}{Armure de combat}
{1701}{}{Armure ultra-sophistiquée composée de polymères défensifs avancés. Créée en 2051, cette armure au poids léger dispose d'une thermorégulation avancée.}
{1800}{}{Desert Eagle .44}
{1801}{}{Ancien pistolet Desert Eagle, version .44 Magnum. Il est devenu l'un des pistolets les plus populaires de tous les temps grâce aux films de la fin du 20è siècle FO min : 4.}
{1900}{}{Pierre}
{1901}{}{Et bien, c'est une pierre. Le modèle Granite & Cie est une version améliorée. FO min. : 1.}
{2000}{}{Pince à levier}
{2001}{}{Pièce de métal solide et lourde utilisée comme levier ou pour assommer des adversaires. FO min : 5.}
{2100}{}{Protections cuivrées}
{2101}{}{Protections renforcées en acier. Elles protègent les mains et sont très efficaces lors des combats au Corps à Corps. FO min : 1.}
{2200}{}{Pistolet 14 mm}
{2201}{}{Pistolet automatique Sig-Sauer 14 mm. Arme de gros calibre à tir simple. De conception excellente. FO min : 4.}
{2300}{}{Fusil d'assaut}
{2301}{}{Fusil d'assaut AK-112 5 mm. Ancien modèle militaire hors service au moment de la guerre. S'utilise en mode tir simple ou rafale avec des balles 5 mm à grande vitesse. FO min : 5.}
{2400}{}{Pistolet à plasma}
{2401}{}{Pistolet à plasma Glock 86. Fut conçu par l'IA Gaston Glock. Lance des petites salves de plasma surchauffé. Alimenté par une petite cellule énergétique. FO min : 4.}
{2500}{}{Grenade (à frag.)}
{2501}{}{Grenade à fragmentation standard. Contient une petite quantité d'explosifs de grande puissance, le contenant lui-même générant la majorité des fragments destructeurs. Explose au contact de la cible. FO min : 3.}
{2600}{}{Grenade (à plasma)}
{2601}{}{Unité de plasma à capsules magnétiques avec explosifs. Surchauffé, le plasma explose au contact de la cible. FO min : 4.}
{2700}{}{Grenade (à impulsions)}
{2701}{}{Grenade à impulsions électromagnétiques générant un champ magnétique intense à la détonation. N'affecte pas les créatures biologiques. S'amorce au contact de la cible. FO min : 4.}
{2800}{}{Laser Gatling}
{2801}{}{Laser Gatling H&K L30. Spécialement conçues à des fins militaires, ces armes n'étaient encore que des prototypes au début de la Guerre. Les canons multiples permettent des tirs plus longs avant la surchauffe. Alimenté par des Cellules à Micro Fusion. FO min : 6.}
{2900}{}{CCM 10 mm}
{2901}{}{Munitions. Calibre : 10 mm, charges creuses à manchon.}
{3000}{}{OP 10 mm}
{3001}{}{Munitions. Calibre : 10 mm. Ogives perforantes.}
{3100}{}{CCM .44 Magnum}
{3101}{}{Munitions, .44 Magnum, charges creuses à manchon.}
{3200}{}{Combustible pour lance-flammes}
{3201}{}{Cylindre contenant un liquide combustible inflammable pour lance-flammes.}
{3300}{}{OP 14 mm}
{3301}{}{Munitions de gros calibre. Ogives perforantes 14 mm.}
{3400}{}{MEM .223}
{3401}{}{Munitions, calibre .223, Manchon Entièrement Métallique.}
{3500}{}{CCM 5 mm}
{3501}{}{Petites munitions légères. Calibre : 5 mm, charges creuses à manchon.}
{3600}{}{OP 5 mm}
{3601}{}{Munitions de petit calibre. Ogives perforantes 5 mm.}
{3700}{}{Roquette perforante}
{3701}{}{Une roquette avec une charge explosive plus réduite conçue pour percer les plaques de blindage.}
{3800}{}{Cellule énergétique}
{3801}{}{Petite unité de stockage d'énergie.}
{3900}{}{Cellule MF}
{3901}{}{Unité de production d'énergie de taille moyenne. Dispositif de fusion intégré.}
{4000}{}{Stimpak}
{4001}{}{Curatif. Lorsqu'il est injecté, il guérit immédiatement les blessures bénignes.}
{4100}{}{Capsules}
{4101}{}{Ce sac contient tes capsules. C'est la seule monnaie acceptée du monde post-apocalyptique, parfois aussi appelée "script" ou "buck" en référence aux appellations archaïques d'Avant-Guerre.}
{4200}{}{Réfrigérateur}
{4201}{}{Un réfrigérateur. Il n'y a plus de liquide de refroidissement.}
{4300}{}{Coffre de glace}
{4301}{}{Coffre de glace de style ancien. Les charnières sont en bon état.}
{4400}{}{Coffre de glace}
{4401}{}{Coffre de glace de style ancien. Les charnières sont en bon état.}
{4500}{}{Couteau de lancer}
{4501}{}{Un couteau conçu spécifiquement pour le lancer. Composé de titane et affûté au laser. FO min. : 3.}
{4600}{}{Sac}
{4601}{}{Sac de taille moyenne. Confectionné avec des poils de brahmines tissés.}
{4700}{}{Trousse de secours}
{4701}{}{Une petite trousse contenant du matériel médical de base. Bandages, couvertures, désinfectant etc.}
{4800}{}{RadAway}
{4801}{}{Une solution chimique absorbant les particules radioactives pour les faire quitter ton organisme. Nécessite du temps avant de fonctionner.}
{4900}{}{Antidote}
{4901}{}{Un flacon contenant un antidote de fabrication artisanale contre le poison. Liquide laiteux avec des morceaux flottants de chair de radscorpion.}
{5000}{}{Elément réservé}
{5001}{}{Elément réservé. NE PAS UTILISER.}
{5100}{}{Dynamite}
{5101}{}{Un explosif à grande puissance composé de nitroglycérine mélangée à de la substance absorbante à base de kiselguhr. Contient une minuterie.}
{5200}{}{Compteur Geiger}
{5201}{}{Un compteur Geiger Wattz Electronics, modèle C-Radz. Cet appareil détecte et indique le taux des radiations.}
{5300}{}{Mentats}
{5301}{}{Pilules agissant sur le cerveau. Accroît les fonctions relatives à la mémoire et accélère les autres procédés mentaux. Hautement addictif.}
{5400}{}{Homme Invisible}
{5401}{}{Appareil de furtivité personnel Homme Invisible 3001 de RobCo. Génère un champ de modulation transmettant la lumière réfléchie d'un côté à l'autre d'un objet, ce qui rend son porteur beaucoup plus difficile à voir.}
{5500}{}{Puce d'eau}
{5501}{}{Puce informatisée pour le contrôle de la purification de l'eau. Ressemble étonnamment à la puce dont ton Abri a besoin.}
{5600}{}{Plaques d'identification militaires}
{5601}{}{Série de plaques d'identification militaires. On peut seulement y lire le nom de Darkwater.}
{5700}{}{Microphone}
{5701}{}{Microphone et dispositif de transmission miniatures.}
{5800}{}{Holodisque}
{5801}{}{Voici un Holodisque Wattz Electronics pour lecteurs THT. Aussi appelée "Holobande" ou "Cassette", ce sont des appareils de stockage de longue durée sur des bandes holographiques lisibles au laser. Elles permettent la conservation de texte, de sons ou de vidéos et possèdent 64 ou 256 kilo-octets de données.}
{5900}{}{Détecteur de mouvements}
{5901}{}{Un détecteur de mouvements Wattz Electronics, modèle C-U. Détecte les mouvements des créatures biologiques sur plusieurs mètres à la ronde grâce à un radar spécialement conçu.}
{6000}{}{Bibliothèque}
{6001}{}{Une bibliothèque en bon état. Elle est faite de bois et peut supporter le poids de livres.}
{6100}{}{Bibliothèque}
{6101}{}{Cette bibliothèque en bois est en très mauvais état et menace de s'effondrer à tout moment.}
{6200}{}{Bibliothèque}
{6201}{}{Vous n'aimez pas la manière dont cette bibliothèque penche...}
{6300}{}{Bibliothèque}
{6301}{}{Une bibliothèque en bon état. Elle est faite de bois et peut supporter le poids de livres.}
{6400}{}{Bibliothèque}
{6401}{}{Cette bibliothèque en bois est en très mauvais état et menace de s'effondrer à tout moment.}
{6500}{}{Bibliothèque}
{6501}{}{Vous n'aimez pas la manière dont cette bibliothèque penche...}
{6600}{}{Bureau}
{6601}{}{Un bureau en bois. Il y a des tiroirs et on peut y ranger des trucs.}
{6700}{}{Bureau}
{6701}{}{Ce bureau en bois a vu des jours meilleurs. Tu ne lui ferais pas confiance pour supporter une feuille de papier.}
{6800}{}{Commode}
{6801}{}{Une commode en bois. Il y a des tiroirs et on peut y ranger des trucs.}
{6900}{}{Commode}
{6901}{}{Cette commode en bois semble fatiguée.}
{7000}{}{Commode}
{7001}{}{Une commode en bois. Un seul tiroir fonctionne. Pas très excitant.}
{7100}{}{Fruit irradié}
{7101}{}{Un fruit étrange. Il n'a pas l'air particulièrement bon. Sans conservateur ni colorant ajouté. Pauvre en calories.}
{7200}{}{Porte-documents}
{7201}{}{Porte-documents portant la mention Made-in-the-USA. En cuir. En bon état mais la serrure à combinaison est cassée.}
{7300}{}{Grand Livre des Sciences}
{7301}{}{Une série de livres contenant des informations sur différents domaines scientifiques.}
{7400}{}{Veste en cuir}
{7401}{}{Lourde veste en cuir noir. Tu ne peux t'empêcher de penser à quel point tu aurais l'air cool en la portant, même dans la chaleur étouffante du désert.}
{7500}{}{Multi-Outil}
{7501}{}{Super trousse à outils contenant divers outils utiles. Un vrai bricoleur ne sort jamais sans.}
{7600}{}{L'Electronique}
{7601}{}{Rapport sur l'électronique. Sur la couverture, une note indique que le livre est destiné à tous "les électroniciens en herbe !"}
{7700}{}{Kit de serrurier}
{7701}{}{Kit électronique de serrurier Micromanipulateur FingerStuff Wattz Electronics. Destiné à forcer les verrous électroniques et autres systèmes de sécurité.}
{7800}{}{Peinture floue}
{7801}{}{Illustration d'un chanteur. Evidemment très ancienne. L'illustration est recouverte d'une pellicule en feutre encore en bon état.}
{7900}{}{Fusée éclairante}
{7901}{}{Une fusée éclairante. Produit de la lumière pour une courte période. Le carton est un peu écorné, mais elle est en bon état. Tordre l'extrémité pour l'activer.}
{8000}{}{Guide de secourisme}
{8001}{}{Brochure sur les notions et la pratique du secourisme. La plupart des informations datent d'Avant-Guerre, mais elles sont toujours applicables.}
{8100}{}{Brochette d'iguane}
{8101}{}{Iguane rôti et farci.}
{8200}{}{Clé}
{8201}{}{Une clé. Elle sert à ouvrir une serrure spécifique.}
{8300}{}{Porte-clés}
{8301}{}{Trousseau de clés.}
{8400}{}{Trousse de serrurier}
{8401}{}{Trousse de serrurier comprenant tous les outils requis pour ouvrir des serrures conventionnelles.}
{8500}{}{Plastic}
{8501}{}{Un morceau de Cordex, une marque militaire d'explosifs au plastic. Très stable, très dévastateur. Comprend une minuterie.}
{8600}{}{Guide de l'Eclaireur}
{8601}{}{Ouvrage sur les méthodes et les idéaux des Eclaireurs. Informations très pratiques pour la survie dans la nature.}
{8700}{}{Buffout}
{8701}{}{Stéroïdes ultra-sophistiqués. Avant-Guerre, ils étaient surtout utilisés clandestinement par les athlètes. Augmentent la force et les réflexes. Hautement addictif.}
{8800}{}{Montre}
{8801}{}{Montre de valeur. Elle fonctionne mal mais elle est encore jolie.}
{8900}{}{Moteur}
{8901}{}{Moteur électrique 40 CV.}
{9000}{}{Sac à dos}
{9001}{}{Sac à dos ordinaire avec sangles supplémentaires.}
{9100}{}{Trousse de médecin}
{9101}{}{Cette trousse contient des instruments et des produits chimiques utilisés par les médecins dans l'exercice de leur art.}
{9200}{}{Queue de radscorpion}
{9201}{}{La queue tranchée d'un radscorpion.}
{9300}{}{Sac}
{9301}{}{Sac de taille moyenne. Confectionné avec des poils de brahmines tissés.}
{9400}{}{Fusil de chasse}
{9401}{}{Fusil de chasse Winchester Widowmaker. Double canon calibre 12. Canon court avec support en acajou. FO min : 4.}
{9500}{}{Cartouches calibre 12}
{9501}{}{Munitions pour fusil de chasse. Ces munitions spéciales portent la mention : "Cartouches calibre 12. Ne pas laisser à la portée des enfants de moins de 3 ans."}
{9600}{}{Passe rouge}
{9601}{}{Clé de sécurité électronique portant le code de couleur rouge.}
{9700}{}{Passe bleu}
{9701}{}{Clé de sécurité électronique portant le code de couleur bleue.}
{9800}{}{Ferraille}
{9801}{}{Amas de vieilleries contenant un peu de tout.}
{9900}{}{Médaillon en or}
{9901}{}{Médaillon en or de valeur.}
{10000}{}{Radio}
{10001}{}{Système de communication radio modèle 2043B de Wattz Electronics. Fiable et robuste, avec camouflage. Interface optionnelle RS-121.}
{10100}{}{Briquet}
{10101}{}{Briquet au butane en argent, en bon état.}
{10200}{}{Armes et Munitions}
{10201}{}{Magazine spécialisé dans la pratique des armes à feu.}
{10300}{}{Brochette d'iguane}
{10301}{}{Viande d'iguane et légumes grillés sur une brochette.}
{10400}{}{Magnétophone}
{10401}{}{Magnétophone Lisez-Pour-Moi de chez Wattz Electronics. Lit et enregistre des bandes haute densité de 30 minutes. A enregistrement unique, ne pas confondre avec les holodisques modernes.}
{10500}{}{Clé}
{10501}{}{Clé spéciale.}
{10600}{}{Nuka-Cola}
{10601}{}{Bouteille de Nuka-Cola, le soda du monde post-nucléaire : chaud et plat.}
{10700}{}{Os}
{10701}{}{Collection d'os étranges.}
{10800}{}{Os}
{10801}{}{Collection d'os étranges.}
{10900}{}{Rad-X}
{10901}{}{Produit anti-radiations à absorber avant toute exposition. Aucun effet secondaire connu. Sans accoutumance.}
{11000}{}{Psycho}
{11001}{}{Système unique rempli de produits chimiques étranges et inconnus, probablement d'origine militaire, et censé accroître le potentiel de combat des soldats.}
{11100}{}{MEM .44 Magnum}
{11101}{}{Munitions, calibre .44 Magnum, manchon entièrement métallique.}
{11200}{}{Urne}
{11201}{}{Belle urne dorée portant l'inscription "Harriet" et contenant des cendres.}
{11300}{}{Robe}
{11301}{}{Robe des Enfants de la Cathédrale.}
{11400}{}{Main de Tangler}
{11401}{}{Manipulateur cybernétique en forme de main. Endommagé à cause de la "méthode" d'extraction.}
{11500}{}{SuperMassue}
{11501}{}{SuperMassue fabriquée par la Confrérie de l'Acier et utilisant la technologie d'armement la plus avancée qui existe. Comprend un système de stockage d'énergie cinétique. FO min : 5.}
{11600}{}{Ripper}
{11601}{}{Vibro-lame Ripper(tm). Alimentée par une petite cellule énergétique, la lame en chaîne déchire sa cible. FO min : 4.}
{11700}{}{Fleur}
{11701}{}{Jolie fleur.}
{11800}{}{Fusil laser}
{11801}{}{Fusil laser Wattz 2000. Utilise des cellules à micro fusion pour des lasers plus puissants et un canon amélioré pour une portée maximale. FO min : 6.}
{11900}{}{Collier}
{11901}{}{Collier apparemment de valeur en argent, or et diamants.}
{12000}{}{Arme Alien}
{12001}{}{Etrange arme à feu apparemment d'origine extraterrestre. Il semble toutefois pouvoir contenir des petites cellules énergétiques. FO min : 2.}
{12100}{}{Balles de 9 mm}
{12101}{}{Ensemble de cartouches anciennes de 9x19 mm. Elle ont été graissées afin de les protéger de l'environnement. Balles clasiques.}
{12200}{}{Mauser 9 mm}
{12201}{}{Mauser M/96 avec Parabellum 9x19 mm. En excellent état. Extrêmement précis. FO min : 3.}
{12300}{}{Anihilateur psychique}
{12301}{}{Etrange système issu d'une technologie singulière.}
{12400}{}{Bière}
{12401}{}{Type de bière brassée artisanalement.}
{12500}{}{Alcool}
{12501}{}{Liqueur ancienne d'avant-guerre.}
{12600}{}{Fiole d'eau}
{12601}{}{Récipient permettant de conserver de l'eau ou d'autres liquides. Aussi appelé "contenant".}
{12700}{}{Corde}
{12701}{}{Grosse corde résistante. Environ 6 mètres de long.}
{12800}{}{Coffre}
{12801}{}{Ton coffre standard. Contient différents objets, se trouve au pied du lit, peut être cadenassé.}
{12900}{}{Coffre}
{12901}{}{Ton coffre standard. Contient différents objets, se trouve au pied du lit, peut être cadenassé.}
{13000}{}{Coffre}
{13001}{}{Ton coffre standard. Contient différents objets, se trouve au pied du lit, peut être cadenassé.}
{13100}{}{Coffre}
{13101}{}{Ton coffre standard. Contient différents objets, se trouve au pied du lit, peut être cadenassé.}
{13200}{}{Placard}
{13201}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13300}{}{Placard}
{13301}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13400}{}{Placard}
{13401}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13500}{}{Placard}
{13501}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13600}{}{Placard}
{13601}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13700}{}{Placard}
{13701}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13800}{}{Placard}
{13801}{}{Placard de rangement. En métal, contient différents objets, peut être cadenassé.}
{13900}{}{Placard}
{13901}{}{Placard de rangement.}
{14000}{}{Carte d'accès}
{14001}{}{Carte d'accès de sécurité. Encore en bon état.}
{14100}{}{Badge EDLC}
{14101}{}{Badge portant le symbole des Enfants de la Cathédrale. Un côté porte des dentelures rappelant celles d'une clé.}
{14200}{}{Badge EDLC}
{14201}{}{Badge portant le symbole des Enfants de la Cathédrale. Un côté porte des dentelures rappelant celles d'une clé.}
{14300}{}{Fusil d'embuscade}
{14301}{}{Fusil d'embuscade DKS-501. Excellente arme à longue portée. A l'origine de calibre .308, celui-ci est de calibre plus courant .223. FO min : 5.}
{14400}{}{SuperStimpak}
{14401}{}{Curatif avancé. Très fort. Aussi appelés Superstim, provoque quelques dommages au bout d'un certain temps en raison de la puissance des produits chimiques utilisés.}
{14500}{}{Etagère}
{14501}{}{Etagère en bois. Fidèle au poste.}
{14600}{}{Etagère}
{14601}{}{Etagère en bois. Fidèle au poste.}
{14700}{}{Etagère}
{14701}{}{Etagère en bois. Fidèle au poste.}
{14800}{}{Etagère}
{14801}{}{Etagère en bois. Fidèle au poste.}
{14900}{}{Etagère}
{14901}{}{Etagère en bois. Fidèle au poste.}
{15000}{}{Etagère}
{15001}{}{Etagère en bois. Fidèle au poste.}
{15100}{}{Etagères}
{15101}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15200}{}{Etagères}
{15201}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15300}{}{Etagères}
{15301}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15400}{}{Etagères}
{15401}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15500}{}{Etagères}
{15501}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15600}{}{Etagères}
{15601}{}{Rangée d'étagères en bois. Tu ne pourras pas transporter ça avec toi.}
{15700}{}{Etabli}
{15701}{}{Vieil établi standard et ordinaire. Il semble agréable de s'y asseoir.}
{15800}{}{Panneau à outils}
{15801}{}{Ce panneau situé au-dessus de l'établi contient différents outils.}
{15900}{}{Cocktail Molotov}
{15901}{}{Grenade inflammable de fabrication artisanale. FO min : 3.}
{16000}{}{Bâton d'élevage}
{16001}{}{Bâton d'élevage, modèle Meilleur Ami du Fermier de Wattz Electronics. Alimenté par de petites cellules énergétiques. FO min : 4.}
{16100}{}{Arme Red Ryder BB}
{16101}{}{Arme Red Ryder BB. Une carabine à air comprimé. Un classique. FO min : 3.}
{16200}{}{Arme Red Ryder LE BB}
{16201}{}{Version limitée de l'arme Red Ryder BB. Chargeur de 100 coups et boussole intégrée, un vrai classique. Faites attention aux yeux. FO min : 3.}
{16300}{}{Billes BB}
{16301}{}{Munitions. Une boîte contenant des billes BB datant d'avant guerre. En excellent état. Acier inoxydable.}
{16400}{}{Disque de la Confrérie}
{16401}{}{Holodisque concernant la Confrérie de l'Acier.}
{16500}{}{Stand d'Iguanes}
{16501}{}{A l'Iguane Rôti, chez Bob. Rien de tel qu'un bon steak d'iguane bien frais !}
{16600}{}{Table}
{16601}{}{Table standard. Evite de poser les choses par terre.}
{16700}{}{Table}
{16701}{}{Table standard. Evite de poser les choses par terre.}
{16800}{}{Objets divers}
{16801}{}{Diverses choses, aussi appelées "trucs".}
{16900}{}{Objets divers}
{16901}{}{Diverses choses, aussi appelées "trucs".}
{17000}{}{Objets divers}
{17001}{}{Diverses choses, aussi appelées "trucs".}
{17100}{}{Objets divers}
{17101}{}{Diverses choses, aussi appelées "trucs".}
{17200}{}{Objets divers}
{17201}{}{Diverses choses, aussi appelées "trucs".}
{17300}{}{Objets divers}
{17301}{}{Diverses choses, aussi appelées "trucs".}
{17400}{}{Objets divers}
{17401}{}{Diverses choses, aussi appelées "trucs".}
{17500}{}{Objets divers}
{17501}{}{Diverses choses, aussi appelées "trucs".}
{17600}{}{Objets divers}
{17601}{}{Diverses choses, aussi appelées "trucs".}
{17700}{}{Objets divers}
{17701}{}{Diverses choses, aussi appelées "trucs".}
{17800}{}{Objets divers}
{17801}{}{Diverses choses, aussi appelées "trucs".}
{17900}{}{Objets divers}
{17901}{}{Diverses choses, aussi appelées "trucs".}
{18000}{}{Cageot}
{18001}{}{Cageot en bois rempli d'objets ordinaires.}
{18100}{}{Bureau}
{18101}{}{Bureau standard. Tous les bureaux sont identiques.}
{18200}{}{Bureau}
{18201}{}{Bureau standard.}
{18300}{}{Bureau}
{18301}{}{Bureau standard.}
{18400}{}{Bureau}
{18401}{}{Bureau standard.}
{18500}{}{Bureau}
{18501}{}{Bureau standard.}
{18600}{}{Bureau}
{18601}{}{Bureau standard.}
{18700}{}{Bureau}
{18701}{}{Bureau standard.}
{18800}{}{Placard}
{18801}{}{Un placard}
{18900}{}{Placard}
{18901}{}{Un placard}
{19000}{}{Disque sur le FEV}
{19001}{}{Un holodisque contenant des informations médicales. Peut être utilisé pour entrer des informations dans ton Pip-Boy 2000.}
{19100}{}{Disque de sécurité}
{19101}{}{Un holodisque avec une étiquette portant la mention "Accès sécurisé". Peut être utilisé pour transférer les données qu'il contient vers ton Pip-Boy 2000.}
{19200}{}{Disque sur les expériences Alpha}
{19201}{}{L'étiquette de cet holodisque porte la mention : "Journal d'expériences Alpha".}
{19300}{}{Disque sur les expériences Delta}
{19301}{}{L'étiquette de cet holodisque porte la mention : "Journal d'expériences Delta".}
{19400}{}{Les flingues du Maitre}
{19401}{}{Ils sont attachés au Maître. On dirait des Gatling Laser H&K L30, mais tu n'en es est pas sûr.}
{19500}{}{Code d'honneur de la Confrérie.}
{19501}{}{Un holodisque portant le symbole de la Confrérie de l'Acier. Il peut être utilisé pour transférer les données vers ton Pip-Boy 2000.}
{19600}{}{Transmissions des Mutants}
{19601}{}{Cet holodisque semble être réglé pour enregistrer des données audio depuis une radio. Il peut être utilisé pour transférer les informations vers ton Pip-Boy 2000.}
{19700}{}{Boîte}
{19701}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{19800}{}{Boîte}
{19801}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{19900}{}{Boîte}
{19901}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20000}{}{Boîte}
{20001}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20100}{}{Boîte}
{20101}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20200}{}{Boîte}
{20201}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20300}{}{Boîte}
{20301}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20400}{}{Boîte}
{20401}{}{Une boite de haute technologie faite en matériel composite ultra-léger et résistant. Elle est probablement utilisée pour le rangement d'armes ou d'équipement médical.}
{20500}{}{Fusée éclairante (Allumée)}
{20501}{}{Une fusée éclairante. Produit de la lumière pour une courte période. Le carton est un peu écorné, mais elle est en bon état. Elle est allumée.}
{20600}{}{Dynamite (Minuterie activée)}
{20601}{}{Un explosif à grande puissance composé de nitroglycérine mélangée à de la substance absorbante à base de kiselguhr. Comprend une minuterie, qui est activée.}
{20700}{}{Compteur Geiger (Activé)}
{20701}{}{Un compteur Geiger Wattz Electronics, modèle C-Radz. Cet appareil détecte et indique le taux des radiations. Il est activé.}
{20800}{}{Détecteur de mouvements}
{20801}{}{Un détecteur de mouvements Wattz Electronics, modèle C-U. Détecte les mouvements des créatures biologiques sur plusieurs mètres à la ronde grâce à un radar spécialement conçu. Il est activé.}
{20900}{}{Plastic (Minuterie activée)}
{20901}{}{Un morceau de Cordex, une marque militaire d'explosifs au plastic. Très stable, très dévastateur. Comprend une minuterie, qui est activée.}
{21000}{}{Homme Invisible (Activé)}
{21001}{}{Appareil de furtivité personnel Homme Invisible 3001 de RobCo. Génère un champ de modulation transmettant la lumière réfléchie d'un côté à l'autre d'un objet, ce qui rend son porteur beaucoup plus difficile à voir.}
{21100}{}{Os}
{21101}{}{Voici Ed. Ed est mort.}
{21200}{}{Tandi}
{21201}{}{Tu marchandes la libération de Tandi.}
{21300}{}{Restes de Gizmo}
{21301}{}{Gizmo, ancien responsable du crime de Dépôtville, est mort. Et c'est d'une puanteur !}
{21400}{}{Bureau}
{21401}{}{Bureau. Après observation, tu décides que c'est encore un bureau.}
{21500}{}{Histoire de la Confrérie}
{21501}{}{Holodisque contenant des informations sur la Confrérie de l'Acier. Peut être utilisé pour entrer des informations dans ton Pip-Boy 2000.}
{21600}{}{Histoire de Maxson}
{21601}{}{RESERVE}
{21700}{}{Journal de Maxson}
{21701}{}{RESERVE}
{21800}{}{Soins légers}
{21801}{}{Marchande cette option si tu veux des soins légers.}
{21900}{}{Soins moyens}
{21901}{}{Marchande cette option si tu veux des soins moyens.}
{22000}{}{Soins poussés}
{22001}{}{Marchande cette option si tu veux beaucoup de soins et une vraie guérison.}
{22100}{}{Carte de sécurité}
{22101}{}{Carte contenant un code de sécurité électronique.}
{22200}{}{Interrupteur de champ}
{22201}{}{Système de transmission électronique composé d'un gros bouton. Semble être de conception récente et destiné à de très grandes mains.}
{22300}{}{Passe jaune}
{22301}{}{Clé de sécurité électronique portant le code de couleur jaune.}
{22400}{}{Petite statuette}
{22401}{}{Tu penses qu'il s'agit d'une sculpture de "l'Habitant de l'Abri", mais ce n'est qu'une supposition.}
{22500}{}{Tu-n'en-sais-rien}
{22501}{}{Après inspection, tu ne sais toujours pas de quoi il s'agit.}
{22600}{}{Paquet de nouilles}
{22601}{}{Tu ne sais pas ce que signifie "Spaghettis instantanés".}
{22700}{}{Boîte poussiéreuse}
{22701}{}{Dîner TV. Tu doutes que ce soit comestible. Tu penses que ça ne l'a peut-être jamais été.}
{22800}{}{Manuel technique}
{22801}{}{Manuel de réparation technique sur la SuperArmure T-51b. Il explique en long et en large, avec tous les détails ennuyeux, tout ce que vous avez besoin de savoir pour utiliser, maintenir, et réparer une SuperArmure.}
{22900}{}{Petite pièce détachée}
{22901}{}{Voici un motivateur systolique. Cette pièce détachée peu commune est très petite pour son poids. C'est une technologie très avancée, tu n'as aucune idée de ce à quoi elle pourrait servir.}
{23000}{}{Enregistrements Abri}
{23001}{}{Recueil d'événements et d'enregistrements importants issus d'un ordinateur de l'Abri. Probablement endommagé.}
{23100}{}{Mot de Passe Base Mil.}
{23101}{}{La sécurité avant tout. Rappelez-vous, ne jamais écrire son mot de passe sur un morceau de papier.}
{23200}{}{SuperArmure renforcée}
{23201}{}{Une SuperArmure T-51b modifiée. Le procédé de renforcement a amélioré les possibilités de défense de ce système ultra-sophistiqué, sans limiter le mouvement et tout en gardant la même protection contre les radiations.}
{23300}{}{Fusil à turbo-plasma}
{23301}{}{Fusil à plasma Winchester P94 modifié. La chambre à plasma a été modifiée pour accélérer le processus de formation de la salve. FO min : 6.}
{23400}{}{Protections aiguisées}
{23401}{}{Version améliorée des Protections cuivrées classiques. Les Protections aiguisées sont plus redoutables et déchirent la chair de ton adversaire lors des combats au Corps à Corps. FO min : 1.}
{23500}{}{SuperPoing}
{23501}{}{SuperPoing 'Big Frigger' de BeatCo. Considéré par beaucoup comme l'arme ultime des combats au Corps à Corps. D'autres en ont juste peur. Alimenté par de petites cellules énergétiques. FO min : 1.}
{23600}{}{Couteau de combat}
{23601}{}{Couteau de combat de qualité optimale, le Stallona fut conçu par SharpWit, Inc. Le tranchant de cette lame est garanti plus de 10 ans ! FO min : 2.}
{23700}{}{Journaux de Chimie}
{23701}{}{Pile de documentation relative à la Chimie. Les articles sur la Chimie moléculaire sont particulièrement intéressants.}
{23800}{}{Transmission des Régulateurs}
{23801}{}{Une holobande contenant une transmission audio.}
{23900}{}{Armure de la Confrérie}
{23901}{}{Version supérieure de l'Armure de Combat. La Confrérie de l'Acier a effectué de nombreuses améliorations sur la version standard.}
{24000}{}{Armure Tesla}
{24001}{}{Cette armure luisante protège des attaques énergétiques. Les trois Systèmes d'attraction Tesla dispersent un fort pourcentage de l'énergie provenant des attaques énergétiques.}
{24100}{}{Pistolet .223}
{24101}{}{Fusil calibre .223 modifié et transformé en pistolet. Une arme à feu classique, conçue avec amour et talent. FO min : 5.}
{24200}{}{Fusil de combat}
{24201}{}{Fusil de Combat Winchester City-Killer calibre 12, variante Bullpup. En excellent état, il est doté de la modification environnementale Guerre-du-Désert pour une meilleure fiabilité. FO min : 5.}
{24300}{}{Pot}
{24301}{}{Un pot en argile travaillé finement travaillé.}
{24400}{}{Pot}
{24401}{}{Un pot en argile travaillé finement travaillé.}
{24500}{}{Coffre}
{24501}{}{Un coffre en bois.}
{24600}{}{Etagère}
{24601}{}{Une étagère en bois comportant différents objets.}
{24700}{}{Etagère}
{24701}{}{Une étagère en bois comportant différents objets.}
{24800}{}{Pot}
{24801}{}{Un pot en argile travaillé finement travaillé.}
{24900}{}{Pot}
{24901}{}{Un pot en argile travaillé finement travaillé.}
{25000}{}{Os}
{25001}{}{Une pile d'ossements humains.}
{25100}{}{Os d'Anna}
{25101}{}{Ces ossements ont été dérangés.}
{25200}{}{Médaillon en or d'Anna}
{25201}{}{Ce médaillon en or très usé s'ouvre sur un charmant portrait.}
{25300}{}{Contrôleur de transmission}
{25301}{}{Cette puce contrôle le débit d'énergie dans un moteur électrique de voiture. De nombreux conducteurs la cramaient à force d'appuyer sur le champignon. C'est une pièce qui garde de sa valeur... tant qu'on a la voiture qui va avec.}
{25400}{}{Régulateur de carburant}
{25401}{}{Certains propriétaires installaient ce régulateur qui double la distance que parcourt une voiture entre deux mises en charge, mais la plupart se fichaient du jus que leur bagnole consommait : on en aura toujours plein de toute façon, hein, pas vrai ?}
{25500}{}{Pistolet Zip}
{25501}{}{Un pistolet fait main avec tir au coup par coup. FO min. : 4.}
{25600}{}{Faux papiers de citoyen}
{25601}{}{Un jeu de faux papiers de citoyenneté. Ils ont l'air authentiques, mais tu doutes qu'ils trompent un examinateur attentif.}
{25700}{}{Montre en or de Cornélius}
{25701}{}{On appelle cet objet du temps jadis une montre de gousset. Le temps a rattrapé cette antiquité il y a déjà bien longtemps.}
{25800}{}{Pièce hydroélectrique}
{25801}{}{Il s'agit d'un régulateur de magnétosphère hydroélectrique.}
{25900}{}{Jet}
{25901}{}{Le Jet est une méta amphétamine puissante stimulant le système nerveux central. La montée initiale d'euphorie dure rarement plus de quelques minutes. Pendant ce temps, l'utilisateur ressent une force et une euphorie incroyables.}
{26000}{}{Antidote contre le Jet}
{26001}{}{Cette antidote permet de guérir la dépendance au Jet.}
{26100}{}{Carabine de Jonny}
{26101}{}{Une carabine à air Red Ryder. On a gravé tant bien que mal « Jonny » sur le manche. FO min : 3.}
{26200}{}{Bottes en caoutchouc}
{26201}{}{Une vieille paire de robustes bottes de chantier en caoutchouc. Elles devraient rester étanches à la boue pendant quelque temps.}
{26300}{}{Message crasseux}
{26301}{}{Un message du chef des Slags aux citadins de Modoc.}
{26400}{}{L'objet cool de Smith}
{26401}{}{DESCRIPTION LONGUE ICI.}
{26500}{}{Veste de combat en cuir}
{26501}{}{Cette veste en cuir dotée d'un épais rembourrage s'illustre surtout par le fait qu'elle possède, chose inhabituelle, deux manches. Voilà qui va faire de toi une vraie « fashion victim ».}
{26600}{}{Radio de Vic}
{26601}{}{Ce poste de radio portatif ne marche plus, mais il est encore en assez bon état. Il serait sans doute possible d'en récupérer les pièces détachées pour réparer d'autres radios.}
{26700}{}{Fiole d'eau de Vic}
{26701}{}{Cette relique de l'Abri contenait sans doute un sacrement. Le Saint nombre 13 est gravé sur un des côtés de cet objet qui te relie au passé de ton peuple et, il faut l'espérer, à son avenir.}
{26800}{}{H&K CAWS}
{26801}{}{Le fusil CAWS est un outil indispensable pour le combat rapproché. Sa conception a permis d'obtenir une arme ramassée, facile à manier, mais au canon assez long pour ses balles à haute vélocité. FO min : 6.}
{26900}{}{Pièces de robot}
{26901}{}{Une pile de pièces de robot endommagées.}
{27000}{}{Lance-roquettes robotisé}
{27001}{}{Utilisé uniquement par les robots équipés de roquettes.}
{27100}{}{Fleur de Broc}
{27101}{}{Ces fleurs abondantes servent à concocter la poudre de guérison.}
{27200}{}{Racine de Xandre}
{27201}{}{Cette racine rare apporte ses vertus curatives à la poudre de guérison.}
{27300}{}{Poudre de guérison}
{27301}{}{Une puissante solution de guérison magique vaguement soporifique.}
{27400}{}{Roquette pour robots}
{27401}{}{Utilisée uniquement par les robots équipés de lance-roquettes robotisés.}
{27500}{}{Trophée du mérite}
{27501}{}{Un solide trophée en or portant l'inscription « A : Dave, De : DC, Pour : Une personne qui m'est chère. »}
{27600}{}{Peau de gecko}
{27601}{}{La peau séchée et tannée d'un gecko.}
{27700}{}{Peau de gecko doré}
{27701}{}{La peau séchée et tannée d'un gecko doré.}
{27800}{}{Silex}
{27801}{}{Une pierre utilisée pour aiguiser les armes.}
{27900}{}{Interface neuronale}
{27901}{}{Ressemble à un jeu d'électrodes intégrées à une unité cérébrale et disposant d'un connecteur informatique standard.}
{28000}{}{Lance}
{28001}{}{Une perche avec un bout tranchant comme un rasoir. Le manche est en bois et le bout est en acier aiguisé. FO min. : 4.}
{28100}{}{Oeil de Dixon}
{28101}{}{Un petit bocal renfermant un oeil humain en suspension dans un liquide non identifié. Caporal Dixon est inscrit sur une étiquette.}
{28200}{}{Oeil de Clifton}
{28201}{}{Un petit bocal renfermant un oeil humain en suspension dans un liquide non identifié. Général Clifton est inscrit sur une étiquette.}
{28300}{}{Mitraillette}
{28301}{}{Cette mitraillette Thompson M1928 est une arme sinistre. Lorsqu'on la tient, on est pris d'une irrésistible envie de mettre un chapeau mou et de faire craquer nos articulations. La Thompson est bien alimentée par un large magasin à tambour de 50 balles. FO min. : 6.}
{28400}{}{Viande séchée}
{28401}{}{Ces lanières de chair animale fumée et séchée restent comestibles, voire nutritives, pendant des années et des années... et des années...}
{28500}{}{Pinces de radscorpion}
{28501}{}{Ces pinces géantes de radscorpion ont été vidées et possèdent une lanière avec une boucle afin de pouvoir les porter.}
{28600}{}{Bûches}
{28601}{}{Une pile de bûches et de fagots.}
{28700}{}{Fusil de chasse avec viseur}
{28701}{}{Il n'y a rien de mieux que de lire la surprise sur le visage de sa cible. Le viseur Meurtrière x20 de ce fusil de chasse en facilite encore davantage l'emploi. Précis du premier au dernier coup, quel que soit le gibier. FO. min : 5.}
{28800}{}{Carburant pour voiture}
{28801}{}{Du carburant pour voiture.}
{28900}{}{Pelle}
{28901}{}{Cette pelle permet de creuser des fossés etc.}
{29000}{}{Arme de Mêlée pour robot n°1}
{29001}{}{Pour les robots à oeil flottant. Provoque des dégâts électriques.}
{29100}{}{Arme de Mêlée pour robot n°2}
{29101}{}{Pour les robots à oeil flottant. Provoque des dégâts électriques.}
{29200}{}{Gants de boxe}
{29201}{}{Une paire de gants de boxe qui sentent encore la sueur. Ils semblent avoir pas mal vécu : de nombreuses taches de sang sont encore visibles.}
{29300}{}{Gants de boxe renforcés}
{29301}{}{Quelqu'un a glissé par « mégarde » des plaques de métal dans ces gants de boxe. Techniquement c'est de la triche mais d'un autre côté il est toujours rassurant de savoir que l'on peut briser quelques os.}
{29400}{}{Holodisque de l'Abri 13}
{29401}{}{Un holodisque qui est censé désigner l'emplacement de l'Abri 13.}
{29500}{}{Cheezy Poofs}
{29501}{}{Une boîte de chips au fromage. Ca a l'air extrêmement bon.}
{29600}{}{H&K P90c}
{29601}{}{Le Heckler & Koch P90c est arrivé sur le marché peu avant la guerre. Cette arme ramassée est d'un maniement très simple. Le P90c, robuste, est apprécié pour sa fiabilité, sa puissance de feu et son encombrement réduit. Munitions : 10 mm. FO min. : 4.}
{29700}{}{Perche métallique}
{29701}{}{Une longue perche métallique. Tu t'attendais à quoi ?}
{29800}{}{Clé des portes de Trapper Town}
{29801}{}{Une clé standard.}
{29900}{}{Fusil à pipe}
{29901}{}{Ce fusil est fait main et tire au coup par coup. FO min. : 5.}
{30000}{}{Pistolet Zip}
{30001}{}{Un pistolet fait main avec tir au coup par coup. FO min. : 4.}
{30100}{}{Ecritoire}
{30101}{}{Cet écritoire comporte un rapport sur le liquide de refroidissement.}
{30200}{}{Holodisque de Gecko}
{30201}{}{L'étiquette de cet holodisque porte l'inscription : « Disque de données économiques de Gecko ». Les tableaux, les plans et les formules mathématiques sont difficiles à interpréter, mais semblent souligner les avantages d'une alliance entre Gecko et la Cité de l'Abri.}
{30300}{}{Holodisque du réacteur}
{30301}{}{L'étiquette de cet holodisque porte l'inscription : « Gecko : Performances du réacteur ». Si tu ne comprends rien à ces lignes interminables de chiffres, il y a là beaucoup de données qui doivent donc être importantes pour quelqu'un.}
{30400}{}{Jeu de cartes « Tragic : The Garnering »}
{30401}{}{Ce jeu de cartes fait partie d'une collection. Attention à ne pas devenir accro à ce passe-temps onéreux.}
{30500}{}{Passe jaune du réacteur}
{30501}{}{Une clé de sécurité électronique utilisant le code de couleur jaune.}
{30600}{}{Passe rouge du réacteur}
{30601}{}{Une clé de sécurité électronique utilisant le code de couleur rouge.}
{30700}{}{Transformateur de plasma}
{30701}{}{Transformateur de plasma à trois voies.}
{30800}{}{Super kit à outils}
{30801}{}{Un kit impressionnant fabriqué par « Snap-Off ».}
{30900}{}{Talisman}
{30901}{}{Un talisman porté par les disciples du Cerveau.}
{31000}{}{Bière Gamma Gulp}
{31001}{}{Une bouteille de bière Gamma Gulp. Elle est phosphorescente dans le noir !}
{31100}{}{Rhum Roentgen}
{31101}{}{Une bouteille de rhum Roentgen. Elle est phosphorescente dans le noir !}
{31200}{}{Formulaire de réquisition de pièces}
{31201}{}{Il s'agit d'un formulaire de réquisition de pièces.}
{31300}{}{Revolver calibre .44 Magnum}
{31301}{}{Vu que c'est l'arme de poing la plus puissante du monde et qu'elle peut t'arracher la tête, tu as une question à te poser : est-ce que c'est mon jour de chance ? Alors, crapule, à ton avis ?}
{31400}{}{Préservatif (sachet bleu)}
{31401}{}{Préservatif de la marque Jimmy Hats, une très bonne marque. Nervuré pour plus de sensations.}
{31500}{}{Préservatif (sachet vert)}
{31501}{}{Préservatif de la marque Jimmy Hats, une très bonne marque. Celui-ci contient de la teinture vert phosphorescent n° 2 et a été imprégnée de lubrifiant spermicide pour plus de sécurité.}
{31600}{}{Préservatif (sachet rouge)}
{31601}{}{Préservatif de la marque Jimmy Hats, une très bonne marque. Celui-ci contient de la teinture rouge phosphorescente n°5 et a un goût alléchant de petit pain à la cannelle... du moins à ce qu'il paraît.}
{31700}{}{Produits de beauté}
{31701}{}{Véritable trousse de produits de beauté Mary May.}
{31800}{}{Seringue hypodermique vide}
{31801}{}{C'est une seringue hypodermique vide.}
{31900}{}{Couteau à cran d'arrêt}
{31901}{}{La lame de ce petit couteau est retenue par un ressort. Lorsque tu appuies sur le bouton situé sur le côté du manche, la lame ressort en faisant un petit « Cccchhhak » très plaisant. FO min. : 1.}
{32000}{}{Piquet aiguisé}
{32001}{}{Un piquet en bois aiguisé à l'une de ses extrémités. FO min. : 4.}
{32100}{}{Cerveau cybernétique}
{32101}{}{Un cerveau humain qui a été amélioré en greffant des composants électroniques et cybernétiques.}
{32200}{}{Cerveau humain}
{32201}{}{Un cerveau humain ordinaire. Se trouve généralement dans les crânes humains. Pouah.}
{32300}{}{Cerveau de chimpanzé}
{32301}{}{Un cerveau de singe. Mou au toucher.}
{32400}{}{Cerveau anormal}
{32401}{}{Semble bien être un cerveau humain. La couleur est un peu bizarre et l'hémisphère gauche s'est effondré.}
{32500}{}{Dés}
{32501}{}{Une paire de dés standard. Ce serait sympa d'en avoir une paire pour votre voiture.}
{32600}{}{Dés pipés}
{32601}{}{Une paire de dés pipés. Evitez de les sortir dans un casino.}
{32700}{}{Oeuf de Pâques}
{32701}{}{Oeufs de poule durs, peints avec des couleurs chatoyantes.}
{32800}{}{Boule de cristal 8}
{32801}{}{Cette sphère noire est une espèce de mécanisme de prédiction... une petite fenêtre sur le dessus semble permettre de lire l'avenir ! La civilisation d'Avant-guerre devait vraiment être très avancée pour avoir produit une telle merveille !}
{32900}{}{Sérum mutagénique}
{32901}{}{Une étrange décoction organique qui pourrait peut-être inverser le Facteur de Mutation chez les êtres humains.}
{33000}{}{Hélico écrasé}
{33001}{}{L'épave d'un verti. On dirait qu'il s'est écrasé il y a déjà plusieurs mois.}
{33100}{}{Magazine 'Cat's Paw' n° 5}
{33101}{}{Le numéro 5 de 'Cat's Paw' est devenu pratiquement introuvable. En dehors des images, ce numéro a un article formidable sur les armes à énergie.}
{33200}{}{Mitraillette "Grease Gun" M3A1}
{33201}{}{Cette mitraillette, après sa réforme par l'armée, est allée remplir les arsenaux de la Garde Nationale. Mais le « Grease Gun » était simple et peu coûteux à fabriquer, de sorte qu'on en voit encore pas mal en circulation. FO min. : 4.}
{33300}{}{Pilules pour le coeur}
{33301}{}{Ces pilules sont destinées aux personnes cardiaques.}
{33400}{}{Poison}
{33401}{}{Une seringue hypodermique pleine de poison.}
{33500}{}{Valise de Moore}
{33501}{}{Thomas Moore t'a demandé d'apporter cette valise en peau de Brahmine aux Bishop à New Reno. Elle est fermée à clé, et tu n'arrives pas à l'ouvrir.}
{33600}{}{Valise de Moore}
{33601}{}{Thomas Moore t'a demandé d'apporter cette valise en peau de Brahmine aux Bishop à New Reno. Elle est fermée à clé, et tu n'arrives pas à l'ouvrir.}
{33700}{}{Holodisque de Lynette}
{33701}{}{Lynette t'a transmis cet holodisque.}
{33800}{}{Holodisque de Westin}
{33801}{}{Westin t'a transmis cet holodisque.}
{33900}{}{Holodisque d'espionnage}
{33901}{}{Cet holodisque comporte les horaires des caravanes RNC ainsi que toutes les informations sur la sécurité. Il est adressé à Darion et signé « F ». Avec ce genre d'informations, on comprend comment les pillards ont pu échapper à la justice.}
{34000}{}{Papiers du médecin}
{34001}{}{Les plans d'une Unité de Garde Canine Cybernétique. Muni de ces plans et du laboratoire adéquat, on peut construire un robochien.}
{34100}{}{Passe présidentiel}
{34101}{}{Ce document, qui atteste que le porteur est titulaire d'une Autorisation A-1 sous l'autorité de la Présidence de la République de la Nouvelle Californie, porte la signature de la présidente Tandi.}
{34200}{}{Code commando}
{34201}{}{Ce badge atteste que tu es Commando en Nouvelle Californie. Regarde, il a même une fermeture à code !}
{34300}{}{Carte de commando}
{34301}{}{Une carte des environs qui ne te sert pas à grand-chose... sauf qu'elle comporte les noms de code des repaires dont disposent les Commandos dans le Nord.}
{34400}{}{Cimetière}
{34500}{}{Cimetière}
{34600}{}{Cimetière}
{34700}{}{Cimetière}
{34701}{}{}
{34800}{}{SuperArmure avancée}
{34801}{}{Cette armure est faite d'un alliage léger renforcé d'un revêtement en céramique au niveau des points sensibles. Les servomoteurs d'aide aux mouvements semblent de toute première qualité.}
{34900}{}{SuperArmure avancée Mk II}
{34901}{}{Cette armure paraît entièrement faite de céramique composite légère plutôt que de la combinaison habituelle de métal et de plaques de céramique. Elle semble fournir une protection encore meilleure que la SuperArmure avancée ordinaire.}
{35000}{}{Bozar}
{35001}{}{Le raffinement ultime dans l'art du sniper. Fragile et prompte à s'enrayer, cette arme massive rachète la difficulté de son entretien laborieux par une précision sans faille. FO min. : 6.}
{35100}{}{FN FAL}
{35101}{}{Ce fusil d'assaut a été le plus utilisé au monde par les forces armées. Il convient à n'importe quel terrain et à n'importe quelle situation. FO min. : 5.}
{35200}{}{H&K G11}
{35201}{}{Fusil d'assaut. Il tire des cartouches sans étui qui se composent d'un bloc de poudre propulsive dans lequel est enchâssée une balle. L'économie de poids et d'espace qui en résulte a permis d'augmenter le nombre de munitions dans le chargeur. FO min. : 5.}
{35300}{}{XL70E3}
{35301}{}{Une arme encore expérimentale au moment de la guerre. Faite principalement de polymères à haute résistance, elle est pratiquement indestructible, légère, rapide, précise, et démontable sans le moindre outil. FO min. : 5.}
{35400}{}{Marteau-piqueur Pancor}
{35401}{}{Le Marteau-piqueur, malgré son nom, est un fusil de chasse facile à manier, même en mode automatique. Très ramassé, avec son chargeur installé juste derrière la gâchette, il est bien équilibré. FO min. : 5.}
{35500}{}{Arme de support légère}
{35501}{}{Cette arme de soutien balistique est d'une utilisation difficile en position couchée, ce qui explique qu'on l'ait réservée à la Garde Nationale. Elle a toutefois acquis une réputation de fiabilité et de grande puissance pour sa taille réduite. FO min. : 6.}
{35600}{}{Module de voix synthétique}
{35601}{}{Un circuit imprimé dont tu n'arrives pas à identifier plusieurs composants, un micro, et une inscription : « Module de reconnaissance vocale Vault-Tek ».}
{35700}{}{Calibre .45}
{35701}{}{Munitions. Calibre .45.}
{35800}{}{EC de 2 mm}
{35801}{}{Munitions. Balles précises et perforantes.}
{35900}{}{4,7 mm sans douille}
{35901}{}{Munitions. Calibre : 4,7 mm, sans douille.}
{36000}{}{9 mm}
{36001}{}{Munitions. Calibre : 9 mm.}
{36100}{}{Cartouches HN Needler}
{36101}{}{Munitions. Cette cartouche est utilisable avec le pistolet à aiguilles HN. Les 'cartouches' sont en fait des seringues hypodermiques conçues pour injecter leur contenu au point d'impact.}
{36200}{}{Cartouches HN Needler perforantes}
{36201}{}{Munitions. Cette cartouche semble être une version perforante, utilisable avec le pistolet à aiguilles HN. Les extrémités hypodermiques utilisent un alliage étrange et sont incroyablement effilées.}
{36300}{}{7,62 mm}
{36301}{}{Munitions. Calibre : 7,62 mm.}
{36400}{}{Motivateur de robot}
{36401}{}{Le mécanisme d'entraînement des robots.}
{36500}{}{Graine de plante à spores}
{36501}{}{Des graines crachées par les plantes carnivores vers les proies potentielles ou les porteurs de graines.}
{36600}{}{J.E.K.}
{36601}{}{Jardin d'Eden en Kit. Cette unité se trouve dans tous les abris Vault-Tek. Le JEK sert à rebâtir la civilisation après la bombe. Il suffit d'ajouter de l'eau et de touiller.}
{36700}{}{Caisse de munitions}
{36800}{}{Caisse de munitions}
{36900}{}{Caisse de munitions}
{37000}{}{Caisse de munitions}
{37100}{}{Griffe}
{37101}{}{Griffe}
{37200}{}{Griffe}
{37201}{}{Griffe}
{37300}{}{Passe de l'Abri 15}
{37301}{}{Une clé de sécurité électronique utilisant le code de couleur rouge.}
{37400}{}{Cimetière}
{37500}{}{Cimetière}
{37600}{}{Cimetière}
{37700}{}{Composants informatiques de l'Abri 15}
{37701}{}{Pièces détachées d'ordinateur de toutes sortes. Le rêve d'un mordu d'informatique.}
{37800}{}{Biscuit}
{37801}{}{Un biscuit aux éclats de chocolat. Miam !}
{37900}{}{Armure en cuir Modèle II}
{37901}{}{Une version améliorée de l'armure de base en cuir, avec des couches de protection supplémentaires. Fabriquée avec du cuir de Brahmine tanné et patiemment travaillé.}
{38000}{}{Armure métallique Modèle II}
{38001}{}{Des plaques de métal polies forment une armure intégrale finement travaillée.}
{38100}{}{Armure de combat Modèle II}
{38101}{}{Armure d'une technologie de pointe, constituée de polymères défensifs avancés.}
{38200}{}{Combustible Mk II pour lance-flammes}
{38201}{}{Ce combustible utilise un mélange super inflammable très élaboré.}
{38300}{}{Surin}
{38301}{}{Ce couteau de fabrication artisanale est aussi dangereux que discret. On ne peut pas le repérer. FO min. : 1.}
{38400}{}{Clé}
{38401}{}{Une grosse clé généralement utilisée par les mécaniciens. FO min. : 3.}
{38500}{}{Fusil à canon scié}
{38501}{}{Quelqu'un a pris le temps de raccourcir de quelques centimètres le canon de ce fusil de chasse. Les coups qu'il tire sont désormais suffisamment dispersés pour en faire l'arme idéale du maintien de l'ordre. FO min. : 4.}
{38600}{}{Cogneur de Louisville}
{38601}{}{Cette batte de baseball typiquement américaine en bois dur peut assommer n'importe qui. FO min. : 4.}
{38700}{}{M60}
{38701}{}{Cette mitrailleuse relativement légère faisait le bonheur des soldats du monde entier pour sa vitesse de tir. On utilisait cette arme, qui a subi l'épreuve du feu à maintes reprises, en couverture, ou montée sur un véhicule. FO min. : 7.}
{38800}{}{Pistolet à aiguilles}
{38801}{}{Tu penses que ce pistolet à aiguilles Bringham a été utilisé pour des études scientifiques sur le terrain. Ses munitions sont en fait de petites fléchettes hypodermiques en plastique dur. FO min. : 3.}
{38900}{}{Minigun Avenger}
{38901}{}{Rockwell a conçu l'Avenger comme le remplaçant du Mini-canon personnel CZ53. Il dispose d'un système de refroidissement à ailettes et de canons chromés, ce qui accroît sa puissance de feu et son efficacité. FO min. : 7.}
{39000}{}{Rôtisseur à énergie solaire}
{39001}{}{Privée des rayons du soleil, cette arme n'allumerait pas une allumette. Mais, en plein jour, les cellules photoélectriques expérimentales qui l'alimentent en énergie lui permettent de griller à peu près n'importe quoi. FO min. : 3.}
{39100}{}{H&K G11E}
{39101}{}{Fusil de soutien. Il tire des cartouches sans étui qui se composent d'un bloc de poudre propulsive dans lequel est enchâssée une balle. L'économie de poids et d'espace qui en résulte a permis d'augmenter le nombre de munitions dans le chargeur. FO min. : 6.}
{39200}{}{Fusil Gauss M72}
{39201}{}{Le fusil M72, de fabrication allemande, se sert d'un champ électromagnétique pour propulser ses cartouches à une vitesse incroyable... et perforer n'importe quel obstacle. Sa portée, sa précision et sa puissance sont inégalées. FO min. : 6.}
{39300}{}{Phaseur}
{39301}{}{Cette arme d'une technologie mystérieuse semble avoir une sorte de générateur d'énergie. Si elle n'était pas endommagée, ce serait l'arme ultime. Le module d'énergie de secours se compose d'une petite pile remplaçable. FO min. : 3.}
{39400}{}{Pistolet Gauss PPK12}
{39401}{}{Apprécié pour sa portée et sa puissance, le pistolet Gauss PPK12 est de fabrication allemande. Il se sert d'un champ magnétique pour propulser ses cartouches à une vitesse incroyable et perforer n'importe quelle armure. FO min. : 4.}
{39500}{}{Minigun Vindicator}
{39501}{}{La société allemande Rheinmetal AG a créé le minigun ultime. Le Vindicator tire jusqu'à 90 000 cartouches à la minute par ses six canons en polymère de carbone. Sommet de l'ingéniosité teutonne, il est l'arme de poing la plus mortelle qui soit. FO min. : 7.}
{39600}{}{Pistolet à impulsions YK32}
{39601}{}{Le YK32 est une arme à impulsions électriques conçue par le Consortium Yuma Flats Energy. Quoique puissant, le YK32 n'a pas convaincu, car gros consommateur d'énergie et trop encombrant. FO min. : 3.}
{39700}{}{Fusil à impulsions YK42B}
{39701}{}{Le YK42B est une arme à impulsions électriques conçue par le Consortium Yuma Flats Energy. Il est considéré comme une bien meilleure arme que le pistolet YK32, du fait de sa meilleure capacité de charge et de sa portée supérieure. FO min. : 6.}
{39800}{}{Revolver calibre .44 Magnum (chargement rapide)}
{39801}{}{Un revolver calibre .44 Magnum avec chargeur rapide. FO min. : 5.}
{39900}{}{Super bâton d'élevage}
{39901}{}{Un bâton d'élevage « Meilleur Ami du Fermier » de chez Wattz Electronics. Ce modèle modifié délivre une décharge électrique plus puissante. FO min. : 4.}
{40000}{}{Lance-flammes amélioré}
{40001}{}{Un lance-flammes Flambe-Tout modèle 450, variante Varmiter. Nécessite un combustible spécial. Pulvérise et enflamme un court jet de liquide inflammable. Ce modèle a été modifié pour mieux exploiter le combustible Mk II. FO min : 6.}
{40100}{}{Fusil laser (Cap. Aug.)}
{40101}{}{Ce fusil laser Wattz 2000 dispose d'un système de recharge amélioré et d'une puce de recyclage spécifique qui réduit de 50% la quantité d'énergie consommée par la cellule à micro fusion. FO min. : 6.}
{40200}{}{Pistolet magnéto-laser}
{40201}{}{Ce pistolet laser Wattz 1000 dispose d'un système de visée à champ magnétique qui réduit la dispersion du rayon laser et lui donne une force de pénétration supérieure. FO min. : 3.}
{40300}{}{FN FAL (vision de nuit)}
{40301}{}{Ce fusil d'assaut a été le plus utilisé au monde par les forces armées. Il convient à n'importe quel terrain et à n'importe quelle situation. Celui-ci est équipé d'un viseur nocturne pour plus de précision dans l'obscurité. FO min. : 5.}
{40400}{}{Desert Eagle (Exp. Mag.)}
{40401}{}{Ancien pistolet Desert Eagle, version .44 Magnum. Grâce aux films de la fin du 20ème siècle, il est devenu l'un des pistolets les plus populaires de tous les temps. Celui-ci est muni d'un chargeur surdimensionné, juste pour rire ! FO min. : 4.}
{40500}{}{Fusil d'assaut (Exp. Mag.)}
{40501}{}{Ce fusil d'assaut a un chargeur surdimensionné de type militaire. Sa capacité accrue rend son utilisation encore plus amusante. FO min. : 5.}
{40600}{}{Pistolet à plasma (Cap. Aug.)}
{40601}{}{Ce pistolet à plasma Glock 86 possède un chargeur magnétique modifié de telle sorte qu'il épuise la cellule énergétique beaucoup moins vite. Son efficacité est doublée. FO min. : 4.}
{40700}{}{Méga SuperPoing}
{40701}{}{Un SuperPoing « Fracasseur » de chez BeatCo, souvent considéré comme la meilleure arme de combat au corp à corp. Les servomoteurs qu'il inclut accroissent sa puissance. Alimenté par de petites cellules énergétiques. FO min. : 1.}
{40800}{}{Trousse de secours pour médecin sur le terrain}
{40801}{}{Une trousse contenant tout l'équipement médical d'urgence de base. Bandages, pansements, antiseptique etc.}
{40900}{}{Sac d'instruments médicaux}
{40901}{}{Ce sac permet de transporter tous les instruments et stimulants utilisés par le personnel médical sur le terrain. Les instruments sont conçus spécialement pour les traumatismes graves et les cas d'urgence.}
{41000}{}{Jeu de passe-partout amélioré}
{41001}{}{Un jeu d'outils de serrurerie. Comprend tous les pics et clés à enrouleur nécessaires pour ouvrir les serrures à gorge ou à broche conventionnelles. Ce jeu comprend également des outils spéciaux pour les mécanismes plus difficiles.}
{41100}{}{Passe-partout électronique Mk II}
{41101}{}{La deuxième génération du passe-partout électronique Micromanipulator FingerStuff de Wattz Electronics. Pour tous les problèmes de verrous électroniques et systèmes de sécurité. La version modèle II comprend un logiciel mis à niveau et des outils d'interfaçage.}
{41200}{}{Bidon d'huile}
{41201}{}{Ceci est un bidon d'Armor-Go. Un lubrifiant polymère pour les super armures de l'époque interplanétaire.}
{41300}{}{Badge d'accès à l'étable}
{41301}{}{Un passe temporaire. Il comporte une bande rouge qui semble indiquer que tu fais partie de l'équipe des « Chercheurs des Etables ».}
{41400}{}{Clé de la cabane de l'Abri 15}
{41401}{}{Une clé standard.}
{41500}{}{Lunettes}
{41501}{}{Une paire de lunettes de vue.}
{41600}{}{Boîte de Jet vide}
{41601}{}{Cette boîte vide a été découverte dans la chambre de Richard Wright. Elle comporte toujours des traces de Jet.}
{41700}{}{Réservoir à oxygène}
{41701}{}{Il s'agit du réservoir contenant l'oxygène de l'appareil respiratoire de Salvatore.}
{41800}{}{Réservoir à poison}
{41801}{}{Ce réservoir ressemble étrangement à un réservoir à oxygène mais un crâne et deux tibias croisés sont gravés au fond. Si tu n'avais pas regardé avec attention, tu n'aurais pas vu ce symbole.}
{41900}{}{Pièces détachées pour la mine}
{41901}{}{Un jeu de pièces détachées qui porte l'inscription « Purificateur d'air GX-9 ». Après mûre réflexion, tu te dis qu'il s'agit là de pièces détachées de purificateur d'air.}
{42000}{}{Titre de la Mine Morningstar}
{42001}{}{Un récépissé qui doit servir à payer les ouvriers de la Mine Morningstar.}
{42100}{}{Grenade à main sacrée}
{42101}{}{Une sainte relique de la puissance divine.}
{42200}{}{Puce d'excavateur}
{42201}{}{Cette puce semble être une pièce allant sur une sorte de gros engin industriel. Chose curieuse, elle paraît en bon état sous sa croûte de saleté et de poussière.}
{42300}{}{Pépite d'or}
{42301}{}{Une pépite d'or.}
{42400}{}{Fragment de monument}
{42401}{}{Un morceau de pierre trouvé dans le désert et provenant d'un ancien monument. Bien que de nombreux membres de votre village le prennent pour une relique, tu es plus circonspect et penses qu'on t'a berné.}
{42500}{}{Tête en pierre}
{42501}{}{Un énorme monument en pierre.}
{42600}{}{Minerai d'uranium}
{42601}{}{Un morceau de minerai d'uranium, non traité.}
{42700}{}{Souffle de feu}
{42800}{}{Fournitures médicales}
{42801}{}{Une boîte contenant différentes fournitures médicales. Rien de bien utile cependant.}
{42900}{}{Dent en or}
{42901}{}{Cette dent en or appartenait à Jules. Maintenant, elle est à toi.}
{43000}{}{Obus}
{43001}{}{Un obus de 75 mm. L'enveloppe en métal est presque complètement rouillée mais tu discernes les lettres EXP. 9-25-98.}
{43100}{}{Boîte de Ramirez, fermée}
{43101}{}{Tu as reçu cette boîte de la part de Big Jesus Mordino et dois la donner à Ramirez, à l'étable.}
{43200}{}{Boîte de Ramirez, ouverte}
{43201}{}{Tu as reçu cette boîte de la part de Big Jesus Mordino et dois la donner à Ramirez, à l'étable. Elle est ouverte et tu as retiré tout le Jet qu'elle contenait.}
{43300}{}{Lunettes de soleil}
{43301}{}{Ces lunettes réfléchissantes te donnent un air plus martial tout en restant à la mode. L'idée des les avoir dans ton inventaire te met à l'aise.}
{43400}{}{Chariot}
{43401}{}{Un wagon de caravane assemblé à partir des restes d'une vieille voiture.}
{43500}{}{Chariot}
{43501}{}{Un wagon de caravane assemblé à partir des restes d'une vieille voiture.}
{43600}{}{Jeu de cartes}
{43601}{}{Un jeu de cartes ordinaire.}
{43700}{}{Jeu de cartes truqué}
{43701}{}{Ce jeu de carte ne comporte que des reines rouges. Ca doit faire des parties plutôt ennuyeuses.}
{43800}{}{Clé du temple}
{43801}{}{La clé de la porte du temple d'Arroyo.}
{43900}{}{Peluches}
{43901}{}{Divers débris trouvés au fond d'une poche.}
{44000}{}{Gel Bio Med}
{44001}{}{Un flacon de bio-gel utilisé dans le domaine biomédical.}
{44100}{}{Plaques de Blondie}
{44101}{}{Le nom du propriétaire de ces plaques d'identification a été rayé et le nom « Blondie » est gravé derrière. En dessous de ce nom figure le numéro « 11 ».}
{44200}{}{Plaques Angel-Eyes}
{44201}{}{Le nom du propriétaire de ces plaques d'identification est « Angel-Eyes ». En dessous de ce nom figure le numéro « 16 ».}
{44300}{}{Plaques de Tuco}
{44301}{}{Ces plaques d'identification nauséabondes portent le nom « Tuco Benedicto Pacifico Juan Maria Ramirez » suivi du numéro du numéro « 27 ».}
{44400}{}{Carte des Pillards}
{44401}{}{Une carte froissée de la Californie du Nord avant-guerre. Reno et les pistes de caravanes avoisinantes sont surlignées et rouge, et il y a une croix rouge à l'Est de Reno avec gribouillé en dessous le mot « Pillards ».}
{44500}{}{Badge du shérif}
{44501}{}{Un badge porté par le shérif d'une ville.}
{44600}{}{Plans d'hélico}
{44601}{}{Des plans permettant de construire un hélicoptère.}
{44700}{}{Holodisque de Bishop}
{44701}{}{Il recèle des informations sur le pacte secret conclu par Bishop avec la RNC. Il semble que Bishop ait engagé des mercenaires pour attaquer la Cité de l'Abri dans l'espoir que celle-ci demande une aide militaire à la RNC. C'est un holodisque audio. Il pourrait intéresser la Cité de l'Abri.}
{44800}{}{Livre de comptes}
{44801}{}{Ce livre de comptes répertorie des versements mensuels de la Famille Bishop de New Reno à un groupe de mercenaires. Leur montant est fortement lié à la « pression » exercée par les mercenaires sur la Cité de l'Abri... que ce document pourrait intéresser.}
{44900}{}{Fusil de combat (Exp. Mag.)}
{44901}{}{Fusil de Combat Winchester City-Killer calibre 12, variante Bullpup. En excellent état. Il possède un chargeur à tambour pour des rafales plus étendues. FO min : 5.}
{45000}{}{Bout de papier 1}
{45001}{}{Un bout de papier sur lequel est écrit un code... incomplet, hélas. Il doit te manquer deux autres morceaux... Tu parviens tout de même à déchiffrer les inscriptions suivantes : 1. Mot de passe Physique KSLJ, 2. Mot de passe Chimie TIU, 3. Mot de passe Biologie INTL}
{45100}{}{Bout de papier 2}
{45101}{}{Un bout de papier sur lequel est écrit un code... incomplet, hélas. Il doit te manquer deux autres morceaux... Tu déchiffres les inscriptions suivantes : KJ : Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Bout de papier 3}
{45201}{}{Un bout de papier sur lequel est écrit un code... incomplet, hélas. Il doit te manquer deux autres morceaux... Tu déchiffres les inscriptions suivantes : 7313, hi-S12908, 98790}
{45300}{}{Feuille de mots de passe}
{45301}{}{Trois morceaux de papier qui, réunis, forment une page entière sur laquelle figurent trois mots de passe : 1. Mot de passe Physique KSLJKJ : Ken-Lee-97313, 2. Mot de passe Chimie TIUASPO- Lo-Shi-S12908, 3. Mot de passe Biologie INTLVR- Dnky-Pnch-98790}
{45400}{}{Détonateur}
{45401}{}{Ce détonateur est l'élément terminal d'un dispositif explosif.}
{45500}{}{Coffre de voiture}
{45501}{}{Ce coffre est un bon endroit où stocker tes affaires.}
{45600}{}{Clé d'une porte de cellule}
{45601}{}{Cette clé ouvre la Porte de la cellule à Collines Brisées.}
{45700}{}{Rapport Hubologiste}
{45701}{}{Un rapport sur les motivations des membres de la Vraie Foi.}
{45800}{}{B.M. Holodisque 5}
{45801}{}{Sur l'étiquette, tu lis : Message à QGC, Confidentiel.}
{45900}{}{B.M. Holodisque 1}
{45901}{}{Sur l'étiquette, tu lis : Transcriptions échanges radio poste de contrôle 1.}
{46000}{}{B.M. Holodisque 2}
{46001}{}{Sur l'étiquette, tu lis : Transcriptions échanges radio poste de contrôle 2.}
{46100}{}{B.M. Holodisque 3}
{46101}{}{Sur l'étiquette, tu lis : Transcriptions échanges radio poste de contrôle 3.}
{46200}{}{B.M. Holodisque 4}
{46201}{}{Sur l'étiquette, tu lis : Transcriptions échanges radio poste de contrôle 4.}
{46300}{}{Holodisque d'évacuation}
{46301}{}{Sur l'étiquette, tu lis : Procédures d'évacuation de la base.}
{46400}{}{Holodisque des expériences}
{46401}{}{Sur l'étiquette, tu lis : Comptes rendus des recherches.}
{46500}{}{Holodisque médical}
{46501}{}{Sur l'étiquette, tu lis : Comptes rendus médicaux.}
{46600}{}{Feuille de mots de passe}
{46601}{}{Une feuille de papier pliée avec dessus le mot « TCHAIKOVSKY »}
{46700}{}{Conteneur de Jesse}
{46701}{}{}
{46800}{}{Repas de Smitty}
{46801}{}{Une sorte de salade, et un sandwich à ce qui te paraît être de la viande de Brahmine recouverte d'une épaisse sauce gris-jaune et accompagnée d'un légume vert bizarre conservé dans la saumure.}
{46900}{}{Tord-boyaux}
{46901}{}{Un alcool très fort ou du liquide de refroidissement, à toi d'en décider.}
{47000}{}{Bâillon à boule}
{47001}{}{Un accessoire sexuel. Il te faut vraiment une explication ?}
{47100}{}{« La Lavande »}
{47101}{}{Un roman à l'eau de rose écrit par une certaine Dorothy Rixon. La couverture représente une femme étendue sur un lit et entourée de dizaines de fleurs.}
{47200}{}{Holodisque Hubologiste}
{47201}{}{L'étiquette de cet holodisque dit : « L'Hubologie : La Vérité Est Ici. » Il doit être compatible avec ton Pip-Boy.}
{47300}{}{Orteil muté}
{47301}{}{Tu vois ton sixième orteil, une portion minuscule, mais mutée, de toi-même. Curieusement, la vue de ce membre amputé t'emplit de nostalgie.}
{47400}{}{Marguerites}
{47401}{}{Un pot de marguerites. Ne sont-elles pas jolies ?}
{47500}{}{Inutilisé}
{47501}{}{Inutilisé}
{47600}{}{Lettre de l'Eclairée}
{47601}{}{Un rapport adressé à AHS-9 à San Francisco. C'est ennuyeux à mourir : tableaux, tables, courbes et graphiques dont tu arriveras très bien à te passer.}
{47700}{}{Holodisque de journaux}
{47701}{}{Sur l'étiquette, tu lis : Galaxy News Network ».}
{47800}{}{Holodisque de la base Sierra}
{47801}{}{Sur l'étiquette, tu lis : « Ordre de mission. »}
{47900}{}{Pièces détachées NavCom}
{47901}{}{Ces pièces doivent pouvoir s'adapter dans un ordinateur. Le fait qu'elles soient étiquetées « Poséidon Oil » et « Ordinateur de navigation » te font penser qu'elles sont destinées à un Ordinateur de Navigation Poséidon Oil.}
{48000}{}{Bonus +1 Agilité}
{48100}{}{Bonus +1 Intelligence}
{48200}{}{Bonus +1 Force}
{48300}{}{Recueil d'indices pour Fallout 2}
{48301}{}{Voilà un bouquin que tu aurais préféré avoir au DEBUT de cette fichue partie.}
{48400}{}{Oreille de Joueur}
{48401}{}{Ton oreille. Le Mastiquateur te l'a arrachée d'un coup de dents au cours du combat et l'a crachée sur ton corps inconscient. Si tu lis ceci, cela signifie que tu risques de devoir recharger le jeu très bientôt. Il se peut également que cet objet ait une valeur quelconque.}
{48500}{}{Oreille du Mastiquateur}
{48501}{}{L'oreille du Mastiquateur. Tu la lui as arrachée d'un coup de dents après l'avoir assommé à coups de poing. Félicitations ! C'est l'un des PNJ les plus durs de tout le jeu, surtout quand on l'affronte sans armes ni armure.}
{48600}{}{Minerai d'uranium raffiné}
{48601}{}{Un fragment de minerai d'uranium. On a dû lui faire subir un traitement, car il te semble plus lourd que la normale.}
{48700}{}{Mot de Francis}
{48701}{}{"Zaius, Marcus ne fait rien contre cet anti-mutant de Jacob et ses comploteurs. Ils ont mis le purificateur en panne. Ensuite, j'ai trouvé les tunnels secrets où ils se réunissent. Un cadavre suffirait à impliquer Jacob. Si ça t'intéresse, fais-moi signe. Et brûle ce fichu mot, cette fois !" Signé: Francis.}
{48800}{}{Motivateur K-9}
{48801}{}{Le mécanisme d'entraînement d'un robot modèle K-9.}
{48900}{}{Arme spéciale pour boxeur}
{49000}{}{Holodisque d'histoire}
{49001}{}{Sur l'étiquette, tu lis : « Histoire de la RNC ».}
{49100}{}{Poupée M. Nixon}
{49101}{}{Tu vois un petite poupée au gros nez rouge. Bizarrement, tu ne te fies pas à l'air innocent de ce jouet d'enfant.}
{49200}{}{Passe électronique du pétrolier}
{49201}{}{Un passe codé qui donne accès aux zones de haute sécurité.}
{49300}{}{Holodisque des enseignements}
{49301}{}{Sur l'étiquette, tu lis : « Enseignements Hubologiste ».}
{49400}{}{Titre de la Mine Kokoweef}
{49401}{}{Un récépissé qui doit servir à payer les ouvriers de la Mine Kokoweef.}
{49500}{}{Passe présidentiel}
{49501}{}{Ce passe porte ce qui semble bien être le sceau présidentiel. Il doit conférer un privilège d'accès de niveau présidentiel aux ordinateurs.}
{49600}{}{Gants de boxe}
{49601}{}{Une paire de gants de boxe qui sentent encore la sueur. Ils semblent avoir pas mal vécu : de nombreuses taches de sang sont encore visibles.}
{49700}{}{Gants de boxe renforcés}
{49701}{}{Quelqu'un a glissé par « mégarde » des plaques de métal dans ces gants de boxe. Techniquement c'est de la triche mais d'un autre côté il est toujours rassurant de savoir que l'on peut briser quelques os.}
{49800}{}{Double canon à plasma}
{49801}{}{A n'utiliser que sur la créature de la Tourelle d'armement.}
{49900}{}{Amplificateur linguistique du Pip-Boy}
{49901}{}{Inclus l'holodisque, le cordon monofilament, le casque, et le capteur optique qui se place sur l'oeil gauche. Quand utilisé, un flash optique transmet le contenu d'un dictionnaire entier dans la mémoire de l'utilisateur, ce qui accroît ses talents oratoires.}
{50000}{}{FN FAL HPFA}
{50001}{}{Ce fusil d'assaut a été le plus utilisé au monde par les forces armées. Il convient à n'importe quel terrain et à n'importe quelle situation. La version HPFA est plus puissante que le FN FAL classique. Min ST: 5.}
{50100}{}{Coffre-fort mural}
{50200}{}{Coffre-fort au sol}
{50300}{}{Module de mémoire bleu}
{50301}{}{Un module de mémoire en lecture seule qui contient des informations médicales. Celui-ci traite de l'augmentation du charisme.}
{50400}{}{Module de mémoire vert}
{50401}{}{Un module de mémoire en lecture seule qui contient des informations médicales. Celui-ci traite de l'augmentation de la perception.}
{50500}{}{Module de mémoire rouge}
{50501}{}{Un module de mémoire morte qui contient des informations médicales. Celui-ci traite de l'augmentation de la force.}
{50600}{}{Module de mémoire jaune}
{50601}{}{Un module de mémoire en lecture seule qui contient des informations médicales. Celui-ci traite de l'augmentation de l'intelligence.}
{50700}{}{Cadavre}
{50701}{}{Le cadavre en décomposition d'une créature humanoïde.}
{50800}{}{Poupée gonflable}
{50801}{}{Une poupée gonflable. Ce modèle s'appelle « Tandi ».}
{50900}{}{Poupée gonflable endommagée}
{50901}{}{Cette poupée gonflable est crevée. Elle a dû beaucoup servir.}
{51000}{}{Billard}
{51100}{}{Billard}
{51200}{}{Billard}
{51300}{}{Billard}
{51400}{}{Billard}
{51500}{}{Billard}
{51600}{}{Amplificateur médical du Pip-Boy}
{51601}{}{Inclus l'holodisque, le cordon monofilament, le casque, et le capteur optique qui se place sur l'oeil gauche. Quand utilisé, un flash optique transmet le contenu d'un manuel de médecine dans la mémoire de l'utilisateur, ce qui accroît sa compétence Médecin.}
{51700}{}{« P'tit Jésus »}
{51701}{}{Ce méchant couteau appartenait à P'tit Jésus Mordino. La surface de la lame présente un grand nombre d'entailles et d'ébréchures, mais son tranchant est intact. « P'tit Jésus » a été gravé sur la poignée.}
{51800}{}{Mini-canon double}
{51801}{}{A n'utiliser que sur les canons automatiques.}
{51900}{}{Capsules de bouteille}
{51901}{}{Des capsules de bouteille sans valeur. Tu as entendu dire qu'on s'en servait de monnaie à une époque, mais ce n'est sans doute qu'une histoire.}
{52000}{}{Mini-canon double lourd}
{52001}{}{A n'utiliser que sur les canons automatiques.}
{52100}{}{Tronc des pauvres}
{52101}{}{Une petite boîte qui sert à la collecte de l'argent pour les pauvres}
{52200}{}{Wakizashi}
{52201}{}{Un superbe poignard court. La pointe semble conçue pour percer une armure.}
{52300}{}{Carte d'état-major}
{52301}{}{Carte d'état-major des environs de la Baie, avec un accent sur la géologie de la région}
{52400}{}{Toge du gardien du pont}
{52401}{}{Ce vêtement doit être fait d'un tissu spécial pour avoir mieux résisté que le cadavre du gardien du pont. Bizarre. Il présente des traces de brûlure au plasma et au lance-flammes, mais il a résisté à ça AUSSI. Quant à savoir pour quelle raison il est violet...}
{52500}{}{Seringue hypodermique}
{52501}{}{Une sorte d'injecteur médical hi-tech. Tu ne sais pas ce qu'il y a dedans, mais il n'en reste qu'une dose.}
{52600}{}{Chemise-rouge mort}
{52601}{}{Ce type a un drôle d'uniforme rouge qui t'est inconnu. Il semble qu'il soit mort de déshydratation.}
{52700}{}{Chemise-rouge mort}
{52701}{}{Ce type a un drôle d'uniforme rouge qui t'est inconnu. Il semble qu'il soit mort de déshydratation.}
{52800}{}{Chemise-rouge mort}
{52801}{}{Ce type a un drôle d'uniforme rouge qui t'est inconnu. Il semble qu'il soit mort de déshydratation.}
{52900}{}{Machine minière}
{53000}{}{Couteau du grand méchant}
{53100}{}{Fusil à plasma du grand méchant}
{53200}{}{Coffre de la Moto}
{53201}{}{The trunk is a great place to store your little bit of stuff.}
{53300}{}{Sidecar}
{53301}{}{Ce sidecar permet de prendre un passager. C'est aussi un super endroit pour stocker plein de trucs.}
{53400}{}{Clé de Moto}
{53401}{}{Une clé d'une moto de marque Chrysalis.}
{53500}{}{Pièces détachées}
{53501}{}{Pompe à pression hydraulique, bobine de fil fibro-électrique, joint hermétique magnétique, alimentation multiprise, adaptateurs trois broches... une sacré collection de pièces de rechange.}
{53600}{}{Combinaison de l'Abri}
{53601}{}{Une combinaison d'Abri classique. Le nombre 13 est imprimé au dos.}
{53700}{}{Faible Déshydratation}
{53701}{}{DO NOT USE}
{53800}{}{Forte Déshydratation}
{53801}{}{DO NOT USE}
{53900}{}{Peau de Gecko de Feu}
{53901}{}{La peau séchée et tannée d'un gecko de feu. Elle est salement brulée et par conséquent, sans aucune valeur.}
