{100}{}{Roquette}
{200}{}{Balle à plasma}
{300}{}{Explosion}
{400}{}{Sang}
{500}{}{Carreau Non-Trans}
{501}{}{}
{600}{}{Couteau}
{700}{}{Lance}
{800}{}{Explosion électromag.}
{900}{}{Rafale laser}
{1000}{}{Rafale de plasma}
{1100}{}{Explosion}
{1200}{}{Bloqueur de défilement}
{1300}{}{Eclair d'électricité}
{1400}{}{Explosion}
{1500}{}{Explosion}
{1600}{}{Zone de sortie}
{1700}{}{Zone de sortie}
{1800}{}{Zone de sortie}
{1900}{}{Zone de sortie}
{2000}{}{Zone de sortie}
{2100}{}{Zone de sortie}
{2200}{}{Zone de sortie}
{2300}{}{Zone de sortie}
{2400}{}{Fusée éclairante}
{2500}{}{Grenade}
{2600}{}{Pierre}
{2700}{}{Explosion}
{2800}{}{Explosion}
{2900}{}{Explosion}
{3000}{}{Cocktail Molotov}
{3100}{}{Zone de sortie}
{3200}{}{Zone de sortie}
{3300}{}{Zone de sortie}
{3400}{}{Zone de sortie}
{3500}{}{Zone de sortie}
{3600}{}{Zone de sortie}
{3700}{}{Zone de sortie}
{3800}{}{Zone de sortie}
{3900}{}{Zone de sortie}
{4000}{}{Zone de sortie}
{4100}{}{Zone de sortie}
{4200}{}{Zone de sortie}
{4300}{}{Zone de sortie}
{4400}{}{Zone de sortie}
{4500}{}{Zone de sortie}
{4600}{}{Zone de sortie}
{4700}{}{Roquette de robot}
{4701}{}{}
{4800}{}{Ka-Pow !}
{4801}{}{}
{4900}{}{Graine de plante à spores}
{4901}{}{}
{5000}{}{Double Rayon de plasma}
{5100}{}{Sol}
