/*

        Shady Sands - Merchant inventory container

*/

/* Include Files */
#include "define.h"

#define NAME                    SCRIPT_BARTRBOX

#include "command.h"

#define LVAR_RESTOCK_TIME                       (0)

procedure start;
procedure map_enter_p_proc;

import variable Barter_Box_Ptr;

procedure start begin
   Barter_Box_Ptr := self_obj;
end

procedure map_enter_p_proc begin
   Barter_Box_Ptr := self_obj;

   // Fo2-style merchant inventory:
   /*if fo1in2_merch_restock_enabled then begin
      if (is_loading_game == false) then begin
         if (local_var(LVAR_RESTOCK_TIME) < game_time) then begin
            self_caps_adjust(random(10, 25) - self_caps);

            check_restock_item(PID_STIMPAK, 4, 10, 100)
            check_restock_item(PID_FIRST_AID_KIT, 1, 3, 100)
            check_restock_item(PID_RADAWAY, 6, 18, 100)
            check_restock_item(PID_ANTIDOTE, 3, 6, 100)
            check_restock_item(PID_MENTATS, 3, 9, 100)
            check_restock_item(PID_BUFFOUT, 2, 7, 100)
            check_restock_item(PID_RAD_X, 4, 26, 100)
            check_restock_item(PID_PSYCHO, 1, 9, 100)
            check_restock_item(PID_SUPER_STIMPAK, 2, 8, 100)
            check_restock_item(PID_ZIP_GUN, 1, 1, 50)
            check_restock_item(PID_FLARE, 1, 10, 35)

            set_local_var(LVAR_RESTOCK_TIME, (random(1, 2) * ONE_GAME_DAY) + game_time);
         end
      end
   end

   // Fo1-style merchant inventory:
   else*/ if (local_var(LVAR_RESTOCK_TIME) == 0) then begin
      set_local_var(LVAR_RESTOCK_TIME, 1);

      give_pid_qty(self_obj, PID_BOTTLE_CAPS, random(10, 30))

      give_pid_qty(self_obj, PID_ROCK, 2)
      give_pid_qty(self_obj, PID_FLARE, 3)
      give_pid_qty(self_obj, PID_ZIP_GUN, 1)
      give_pid_qty(self_obj, PID_10MM_JHP, 1)
      give_pid_qty(self_obj, PID_10MM_AP, 1)
      give_pid_qty(self_obj, PID_BAG, 1)
      give_pid_qty(self_obj, PID_MULTI_TOOL, 1)
      give_pid_qty(self_obj, PID_SCOUT_HANDBOOK, 1)
      give_pid_qty(self_obj, PID_MUTATED_FRUIT, 4)
      give_pid_qty(self_obj, PID_STIMPAK, 1)
      give_pid_qty(self_obj, PID_FIRST_AID_KIT, 1)
      give_pid_qty(self_obj, PID_SPEAR, 4)
      give_pid_qty(self_obj, PID_SLEDGEHAMMER, 1)
      give_pid_qty(self_obj, PID_KNIFE, 2)
      give_pid_qty(self_obj, PID_THROWING_KNIFE, 3)
      give_pid_qty(self_obj, PID_CROWBAR, 1)
      give_pid_qty(self_obj, PID_BRASS_KNUCKLES, 2)
      give_pid_qty(self_obj, PID_CATTLE_PROD, 1)
      give_pid_qty(self_obj, PID_SPRINGER_RIFLE, 1)
      give_pid_qty(self_obj, PID_FLARE, 8)
   end
end
