/*

   Brahmin pen stench.
   Currently only used in Shady Sands.

*/

#include "define.h"

procedure start;
procedure spatial_p_proc;

#define LVAR_Herebefore              (0)

procedure start begin
end

procedure spatial_p_proc begin
   if (source_obj == dude_obj) then begin
      if (local_var(LVAR_Herebefore) == 0) then begin
         set_local_var(LVAR_Herebefore, 1);
         display_msg(message_str(SCRIPT_PENSMELL, 100));
      end
   end
end
