{100}{}{Du siehst Abel.}
{101}{}{Du siehst einen großen Mutanten.}
{102}{}{Du solltest nicht hier sein.}
{103}{}{Hng.}
{104}{}{Natürlich nicht. Ich bin hier, um dich zu töten!}
{105}{}{Warum sagst du das?}
{106}{}{Oh, ja? Deine Mami!}
{107}{}{Schwein!}
{108}{}{Ich trete dir in den Hintern, wenn du das nochmal sagst!}
{109}{}{Schwein! Schwein!}
{110}{}{Okay, jetzt zeig' ich's dir!}
{111}{}{Du Mensch. Ich Mutant. Mutant tötet Mensch.}
{112}{}{Wie machst du das? Was ist mit dem Kraftfeld?}
{113}{}{Abel passt darauf auf. Dann tritt dir Abel in den Hintern!}
{114}{}{Children sind hier nicht erlaubt. Das ist ein Mutanten-Ort. Hau ab!}
{115}{}{Hng!}
{116}{}{Ich muss durch das Kraftfeld kommen. Mach' es bitte niedriger.}
{117}{}{Nein.}
{118}{}{Du schon wieder. Abel tritt dir in den Hintern!}
#
# Tell Me About name
#
# Duplicates are needed due to how engine processes the Tell-Me-Abouts.  -Sduibek
{970}{}{Ich Abel.}
#
# Tell Me About, "don't know what that is"
#
{980}{}{Hng.}
{981}{}{Warum sagst du das?}
