{100}{}{Du siehst einen Einwohner von Adytum.}
{101}{}{Sieht nach Regen aus ... wie immer.}
{102}{}{Tut mir leid, aber ich muß gehen. Ich hab' zu tun.}
{103}{}{Wir haben nicht viele Leute von draußen hier.}
{104}{}{Ich muß zurück zur Arbeit.}
{105}{}{Ich an deiner Stelle würde zurück zum Hub gehen.}
{106}{}{Schönen Tag noch ... wenn man das so nennen kann.}
{107}{}{Ja ... was auch immer.}
{108}{}{Keine Zeit zum Labern.}
{109}{}{Ich kann mich jetzt nicht unterhalten.}
{110}{}{Ich hoffe, der Regen ist nicht so verstrahlt wie gestern.}
{111}{}{Sieht ganz so aus, als wären wir wieder mal erledigt.}
{112}{}{Ich hoffe, die Caravans fahren bald vorbei.}
{113}{}{Jetzt können wir es schaffen.}
{114}{}{Adytum wird zu einer Stadt, wie wir sie uns immer gewünscht haben.}
{115}{}{Danke für deine Hilfe.}
{116}{}{Danke, daß du uns von den Regulatoren befreit hast.}
{117}{}{Danke für unsere Freiheit.}
{118}{}{Es ist gut, daß die Regulatoren weg sind.}
{119}{}{Willkommen in New Adytum.}
