{100}{}{Du siehst Mitch aus dem All-N-One Laden.}
{101}{}{Wie kann ich dir heute helfen?}
{102}{}{Ich möchte etwas kaufen.}
{103}{}{Ich möchte etwas verkaufen.}
{104}{}{Nichts. Danke.}
{105}{}{Runk.}
{106}{}{Großartig. Schau', was ich habe.}
{107}{}{Großartig, ich suche ständig nach neuen Sachen.}
{108}{}{Tut mir leid, aber ich kann dich nicht verstehen. Komm wieder, wenn du mehr Hirn hast.}
{109}{}{Danke, komm' wieder.}
{110}{}{Du siehst Jake, den Waffenhändler.}
