{100}{}{Du siehst Ton.}
{101}{}{Du siehst ein riesiges Mitglied der Children.}
{102}{}{Mann}
{103}{}{Frau}
{104}{}{[OK]}
{105}{}{[Mehr]}
{106}{}{Tut uns leid, Mann, es gibt jetzt kein Zurück mehr. Die Zeit ist abgelaufen!}
{107}{}{Tut uns leid, Lady, es gibt jetzt kein Zurück mehr. Die Zeit ist abgelaufen!}
{108}{}{Wieso sollte ich mit jemanden reden, der herumläuft und Leute umbringt?
 Geh' mir aus den Augen!}
{109}{}{Ich höre, du bist ziemlich hart. Aber Härte beeindruckt Ton nicht.
 Hast du was zu sagen oder willst du weitermachen? Los geht's!}
{110}{}{Frieden, Bruder! Ich schaue mir nur den Ort an.}
{111}{}{Ich will dich nicht beeindrucken. Wenn du was Intelligentes zu sagen hast,
 so sag' es!}
{112}{}{Was? Mister, ich interessiere mich nicht für dürre kleine Jungs.}
{113}{}{Was willst du?}
{114}{}{Du redest zuviel.}
{115}{}{Du willst sterben und ich möchte jemanden killen. Trifft sich doch gut.}
{116}{}{Waas!}
{117}{}{Typ, mit dir hab ich doch schon gesprochen! Lad' deinen Müll woanders ab!}
{118}{}{Junge}
{119}{}{Mädchen}
{120}{}{Hey, du denkst, deine Waffen bringen dir Respekt? Sie bringen dich ins Grab, Mann.
 Nimm sie weg.}
{121}{}{Hey, du denkst, deine Waffen bringen dir Respekt? Sie bringen dich ins Grab, Mädel.
 Nimm sie weg.}
{122}{}{Was willst du, du beschränkter Zombie? Geh' mir aus dem Licht, bevor ich einen
 Schreikrampf bekomme.}
{123}{}{Ich hab' nach jemandem gesucht, der klug genug ist, mir zu sagen, was hier im Laden
 los ist!}
{124}{}{Was werden die Priester sagen, wenn sie dich so reden hören?}
{125}{}{Jederzeit, Kumpel. Ich warte auf eine gute Rauferei!}
{126}{}{Hey, was ist los? Ein paar Drinks und wir sind Kumpel!}
{127}{}{Hast du gewusst, dass sogar ein Kind genug Kraft hat, um dich mit einem Druck auf den
 richtigen Punkt in deiner Kniekehle zum Krüppel zu machen? Dachte nur, das könnte dich
 interessieren.}
{128}{}{Du möchtest mit Ton reden? Schön. Aber, wenn ich das Wort "loben" hör', mach' ich dich alle.}
{129}{}{Du bist kein großer Fan von Gottesdiensten?}
{130}{}{Was ist los, Kumpel?}
{131}{}{Ich möchte mit dem Boss sprechen.}
{132}{}{Allerdings. Das einzige, das ich lobe, ist eine Flasche Radscorpion.}
{133}{}{Schön. Der erste von uns, der das Wort sagt, stirbt. Abgemacht?}
{134}{}{Hallo, Miss. Ich bin Ton, 2000 Pfund schwer und des Meisters härtester Kämpfer.
 Außerdem bin ich vom FEV entwickelt worden, und du musst mich überprüfen. Also los, Baby.}
{135}{}{Vergiss es.}
{136}{}{Das geht mir ein wenig zu schnell. Wir sollten uns erst noch ein wenig beschnuppern.}
{137}{}{Hallo. Ich bin vom FEV so entwickelt worden, dass jeder, der mich reizt, des Todes
 ist. Hör' lieber auf mich zu reizen, kleiner Mann.}
{138}{}{Bring' das woanders in Erfahrung. Ton legt keinen Wert auf deine Gesellschaft.}
{139}{}{Schön. Du möchtest es genau wissen? Manchmal muss man eben töten.
 Manchmal gefällt es mir auch. Aber ich höre, du liebst das Töten... immer.
 Jedesmal, wenn ich einen Verrückten treffe, stirbt entweder er oder Ton. Ton ist
 noch hier. Also, warum verschwindest du nicht?}
{140}{}{Mann, ich könnt' mich an dich gewöhnen. Du bist entweder ein unglaubliches
 Arschloch oder hast Stärkepillen eingeworfen. Beides ist ok für Ton, solange du mich nicht
 nervst. Willst du dich anschließen?}
{141}{}{Was ist mit dem Frieden und der Liebe geschehen?}
{142}{}{Was gehört dazu?}
{143}{}{Vergiss es, Kumpel.}
{144}{}{Ich nerve, wann ich will und wen ich will. Also, raus mit den Störenfrieden!}
{145}{}{Um dich leiden zu sehen. Komm' schon, Fremder, gib mir, was ich will.}
{146}{}{Hüte dich mit dem, was du willst. Kann sein, dass dir nicht gefällt, was du bekommst.}
{147}{}{Ich wäre lieber dein Freund.}
{148}{}{Du verschwendest meine Zeit.}
{149}{}{Fang' schon an. Mach' den ersten Zug. Den letzten mache ich.}
{150}{}{Schön. Das Labern ist vorbei. Mach' deinen Zug.}
{151}{}{Ich möchte mich nur unterhalten.}
{152}{}{Du bist tot...}
{153}{}{Mist! Du bist dümmer als die Zombies! Verschwinde hier!}
{154}{}{Der Meister will Frieden und er möchte, dass wir ihn schaffen, also haben wir
 gefälligst Spaß. Kapiert?}
{155}{}{Ja, aber da passiert doch mehr als das.}
{156}{}{Will der Meister wirklich Frieden oder will er einfach töten?}
{157}{}{Wer ist dieser Meister?}
{158}{}{Gefällt mir.}
{159}{}{Pfeif' auf den Meister! Bringen wir lieber alle um!}
{160}{}{Es kann ungesund sein, wenn man die falschen Fragen stellt, Kumpel. Sie sagen alles, was du hören willst. Gestalten, die die falschen Fragen stellen oder rumspinnen, nun ja,
 solche Typen werden hier nicht alt.}
{161}{}{Ich mach' meinen Job. Und das mögen sie. Sie mögen es, wenn Straßenmüll
 und Followers den Löffel abgeben. Dann haben die Nightkin Zeit für andere Dinge.
 Leg' dich nicht mit mir an... das bekommt dir nicht.}
{162}{}{Was treibst du da in den Klamotten eines Zombies? Wenn du so bist, zeig's gefälligst!}
{163}{}{Ich interessiere mich nicht für die Klamotten, Mann. Ich will nur wissen, was hier
 vorgeht!}
{164}{}{Sie lassen dich in Ruhe, wenn du sie nicht mit deinem Aussehen dazu reizt, dich
 zu verwandeln.}
{165}{}{Geht dich nichts an, Kumpel.}
{166}{}{Ich hab' mir schon überlegt, ob ich mich verwandeln soll.}
{167}{}{Ich bin nicht so. Es ist eine Art des Todes.}
{168}{}{Wir trinken hier nicht. Die Nightkin mögen das nicht. Du solltest dich
 besser informieren, bevor du erneut mit Ton sprichst.}
{169}{}{Du spinnst doch! Ich könnte fast genauso sein wie du, aber ich glaube, dass Leute,
 die so rumhängen wie du, nicht allzu lange leben. Verschwinde hier.}
{170}{}{Du stehst monatelang so rum und du wirst genauso verrückt wie die. Was willst du von
 Ton?}
{171}{}{Wie sind diese Leute bloß so geworden?}
{172}{}{Ich will Sex und Gewalt, aber ohne Sex. Weißt du, wo ich das bekommen kann?}
{173}{}{Ich hab es in dieser Zombiegrube verloren und ich brauche deine Hilfe nicht.
 Geh mir aus den Augen.}
{174}{}{Das ist Morpheus. Er ist oben, außer, wenn er predigt. Aber das macht er nicht
 mehr oft. Er ist klug und ein Gewinner und das ist alles, was zählt. Geh' doch mal zu ihm.}
{175}{}{Du musst in den Boneyard gehen, Kumpel. Hier ist nix los und ich hab' wirklich gesucht!}
{176}{}{Einverstanden. Was kann Ton für dich tun?}
{177}{}{Schlampe! Du weißt nicht, was dir entgeht! Raus!}
{178}{}{Das Leben ist zu kurz für sowas. Komm, ich zeig' dir, warum du nicht warten solltest.}
{179}{}{Aber ich brauche jemanden, der weiß, was hier vorgeht.}
{180}{}{Nein danke. Aber wir könnten Freunde sein.}
{181}{}{Verschwinde, du Stück Abfall.}
{182}{}{Sicherlich.}
{183}{}{Das Leben IST kürzer, als du denkst. Stirb, Arschloch!}
{184}{}{Ich bin nicht KLEIN, Schlampe!}
{185}{}{Wer glaubt an diesen Scheiß? Sie müssen sogar diese Schwachköpfe programmieren, damit sie an dieses Zeugs glauben.}
{186}{}{Wie ist das passiert?}
{187}{}{Wirklich?}
{188}{}{Was für eine Horde Idioten.}
{189}{}{Erzähl' mir mehr über deine Truppe.}
{190}{}{Okay, ich mach mit.}
{191}{}{Jemand sollte sie aus dieser Misere befreien. Jemand wie ich...}
{192}{}{Wenn wir das Zeichen bekommen, gehen wir raus und killen Leute. Leute wie die
 Followers oder einige der noch gefährlicheren Gangtypen.}
{193}{}{Sind die Followers ein Problem?}
{194}{}{Das klingt übel.}
{195}{}{Wer braucht ein Zeichen? Warum killen wir sie nicht gleich?}
{196}{}{Schön. Mach', was du willst. Aber ich verschwinde lieber, bevor es hier zu
 ungemütlich wird.}
{197}{}{Du nervendes Stück Abfall. Du Feigling. Du bist ja schlimmer wie die Leute aus Junktown. Verpiss' dich.}
{198}{}{Was sollte ich sonst noch wissen? Ich gehe jetzt gut essen. Ich esse gut, schlafe
 ausgezeichnet und töte einige der Leute, die mir auf den Wecker gehen. Was kann man mehr
 vom Leben erwarten?}
{199}{}{Wer weiß? Wen juckt's? Ich esse gut, schlafe ausgezeichnet und töte einige
 der Leute, die mir auf den Wecker gehen. Was kann man mehr vom Leben erwarten?}
{200}{}{Hmmm, daran hat Ton noch gar nicht gedacht. Aber wenn sie mich zu sehr nerven,  mach' ich sie alle. Dann werden sie aufhören, Ton zu nerven. Was willst du?}
{201}{}{Umwandeln? Naja, viel Glück. Du kannst es brauchen.}
{202}{}{Warum sollte ich Glück brauchen?}
{203}{}{Das klingt nicht gut.}
{204}{}{Danke. Du bist ein wahrer Freund.}
{205}{}{Solange ich Munition hab, brauch' ich kein Glück.}
{206}{}{Diese Leute, diese Zombies, waren nicht schon immer so. Ich konnte nur
 ein paar von ihnen helfen, bevor sie umgewandelt wurden. Einige kamen so, wie sie
 jetzt sind, zurück. Einige kamen gar nicht mehr zurück. Ton gefällt das nicht, aber
 diese Leute zahlen Ton sehr gut.}
{207}{}{Warum sprichst du abwechselnd in der ersten und dritten Person?}
{208}{}{Erzähl mir mehr über den Umwandlungsprozess.}
{209}{}{Bist du auch umgewandelt worden?}
{210}{}{Dieser Ort kostet keine hohe Miete.}
{211}{}{Wirklich, wieviel?}
{212}{}{Das tut mir keiner an!}
{213}{}{Du kannst mit Morpheus oder mit Lasher sprechen, oder du kannst Ton
 belästigen. Von Ton kriegst du mehr Gewalt als dir gut tut.}
{214}{}{Ok, Baby, ich sag' dir, was vorgeht. Viele der Zombies singen, eine Menge Leute sterben und die Children übernehmen alles. Und da sind du und ich und sonst zählt nichts!}
{215}{}{Aber Barracas, Schätzchen, klar geht hier mehr vor als das...}
{216}{}{Oh, Ton!}
{217}{}{Vergiss es, Widerling. Du bist nicht mein Typ.}
{218}{}{Sonst zählt nichts? Zum Teufel, nein! Ich will mehr über das Töten hören!}
{219}{}{Bedauerlicherweise ist dies hier der schlechteste Ort, um zu erfahren, was
 Ton am besten kann. Zu viele Zombies verpfuschen meinen Stil. Ich informiere dich, wenn
 mir ein besserer Ort eingefallen ist...}
{220}{}{Du wirst noch früh genug herausfinden, was da oben vorgeht. Wenn du stark bist,
 steckst du es weg. Es ist Ton passiert und Ton geht's gut!}
{221}{}{Äh... ich hab' nichts gesagt. Du vergisst alles, was Ton dir erzählt hat
 oder Ton sorgt dafür, dass du alles für immer vergisst!}
{222}{}{Sie waren die Gewinner. Aber Ton labert zu viel. Geh' mir aus den Augen.}
{223}{}{Schön. Du tauchst solange unter, bis ich dir das Zeichen gebe. Dann werden wir
 echt Spaß haben.}
{224}{}{Sie sind Feiglinge. Sie überfallen unsere Patrouillen aus dem Hinterhalt.
 Sie senden Spione und Saboteure. Sie wissen, dass sie bei einem echten Kampf keine Chance haben. Der Meister sagt, wir sollen Mitleid mit ihnen haben, aber Ton möchte sie einfach nur killen. Kluger Mann, Ton.}
{225}{}{Wir brauchen Disziplin, Trottel! Wir sind jetzt Soldaten! Wir gehorchen den
 Befehlen. Killer sterben, aber Soldaten gewinnen ihre Schlachten. Wir werden die Followers
 schlagen. Wir werden ALLE schlagen!}
{226}{}{Wer zum Teufel weiß das schon? Vielleicht ist es Morpheus, der die Hebel zieht.
 Die Dinge laufen gut und wenn das hier austrocknet, geht Ton woanders hin.}
{227}{}{Nun ja, werd' mal nicht zu eifrig. Auch mit den Nightkins, es ist immer noch
 ein harter Kampf. Aber wenn wir klug vorgehen, werden wir an der Spitze stehen. Das ist alles, worum Ton sich sorgt.}
{228}{}{Die Umwandlung ist nicht leicht. Siehst du diese Leute, all diese Zombies?
 Sie waren wie du und ich. Ton hat überlebt. Diese Leute nicht. Aber warum sollte Ton sich
 um dich scheren?}
{229}{}{Du magst nicht, wie Ton redet? Dann wird dich Ton killen!}
{230}{}{Ton hat's gut hinter sich gebracht. Ich... äh... ich... äh...
 Ton... Ton geht's gut.}
{231}{}{Ich war immer mit der Dead Dog Gang zusammen. Immer hungrig, immer müde.
 Dieser Ort ist viel besser für Ton. Warum sollten mich andere was scheren?
 Um mich hat sich auch nie jemand geschert.}
{232}{}{Du gieriges Arschloch! Verpiss' dich, bevor Ton dich auslöscht!}
{233}{}{Also, verschwinde hier, bevor es zu spät ist.}
{234}{}{Nichts ist so wichtig wie du und ich. Bedauerlicherweise ist dies hier
 der schlechteste Ort, um zu erfahren, was Ton am besten kann. Zu viele Zombies
 verpfuschen meinen Stil. Ich informiere dich, wenn mir ein besserer Ort eingefallen
 ist...}
{235}{}{Na warte, du manipulierendes Dreckstück! Ton lässt sich nicht so einfach verarschen!}
