{100}{}{Die Explosion verschließt den Tunnel mit einer gewaltigen Druckwelle!}
{101}{}{Du wirfst den Sprengstoff und er explodiert!}
{102}{}{Die Explosion vergrößert nur die Öffnung. Sie kann jetzt nicht mehr verschlossen werden.}
{103}{}{ Erfahrungspunkte für das erfolgreiche Benutzen des Sprengstoffs.}
