{100}{}{Geschlossen auf Anweisung von Sheriff Justin Greene.}
{101}{}{Da ist ein kleines Schild an der Zelle.}
{102}{}{Gesucht: Iguana Bob Frazier, tot oder lebendig. Wenn du Hinweise auf seinen
 derzeitigen Aufenthaltsort hast oder weiﬂt, wo sich die Leute befinden, die ihm zur Flucht
 verholfen haben, informier' bitte sofort den Sheriff.}
