{100}{}{Du siehst die Ärztin der Brotherhood of Steel.}
{102}{}{Hallo, wie kann ich dir helfen?}
{103}{}{Ich bin verletzt.}
{104}{}{Ich bin verstrahlt.}
{105}{}{Operierst du auch?}
{106}{}{Erzähl mir das mit den Operationen noch mal.}
{107}{}{Ägh!}
{108}{}{Bist du verletzt? Laß mal sehen ...}
{109}{}{Aha, das war also das Problem! Sei in Zukunft vorsichtiger da draußen.}
{110}{}{Tut mir leid, aber ich kann dir nicht helfen, wenn du mir nicht sagst, was dir fehlt.}
{111}{}{Dir scheint nichts zu fehlen.}
{112}{}{So, das war's schon ... Ich hoffe, du fühlst dich jetzt besser.}
{113}{}{So, fertig ... Laß dich in Zukunft nicht mehr auf Kämpfe ein.}
{114}{}{Jetzt solltest du wieder in Ordnung sein.}
{115}{}{Wie neugeboren!}
{116}{}{Alles geheilt!}
{117}{}{Radioaktive Strahlung ist sehr gefährlich, du solltest daher vorsichtiger sein.}
{118}{}{Ich habe keine Zeit für Spielchen.}
{119}{}{Aber natürlich, allerdings kosten Operationen viel Geld und Zeit.}
{120}{}{Einzelheiten?}
{121}{}{Okay, schon gut.}

{122}{}{Gut, ich kann dir zu mehr Stärke, einer besseren Wahrnehmung und mehr Ausdauer verhelfen, deinen Lernprozeß beschleunigen und dein Geschick steigern. Ich habe außerdem Prozeduren zur Schönheitschirurgie studiert. Über was willst du mehr wissen? Ich kann jede Operation nur einmal durchführen.}
{222}{}{Gut, ich kann dir zu mehr Stärke, einer besseren Wahrnehmung und mehr Ausdauer verhelfen, deinen Lernprozeß beschleunigen und dein Geschick steigern. Über was willst du mehr wissen? Ich kann jede Operation nur einmal durchführen.}


{126}{}{Okay, für welche Operation interessierst du dich?}

{127}{}{Stärke.}
{128}{}{Wahrnehmung.}
{129}{}{Ausdauer.}
{130}{}{Intelligenz.}
{131}{}{Beweglichkeit.}
{132}{}{Schon gut.}
{133}{}{Diese Operation ist ganz einfach, aber die Genesung dauert ziemlich lange. Sie kostet nur 2000 Scripts, aber du mußt mit 3 Wochen für die Genesung rechnen.}
{135}{}{Okay, ich lass' es machen.}
{136}{}{Ich lass' es lieber.}
{137}{}{Nun, das ist eine schwierige Operation. Sie kostet 4000 Scripts, aber die Genesung dauert dafür nur eine Woche.}
{139}{}{Diese Operation ist nicht so schwierig. Sie kostet 3000 Scripts, und die Genesung dauert ungefähr eine Woche.}
{141}{}{Das ist die schwierigste und gefährlichste Operation. Sie kostet 6000 Scripts, und die Genesung dauert 3 Wochen.}
{143}{}{Das ist keine sehr schwierige Operation, aber sie kostet viel Geld und Zeit. Sie kostet 5000 Scripts, und die Genesung dauert 3 Wochen.}
{146}{}{Okay, das war's schon ... Ich hoffe, der Schaum hat deiner Haut nicht geschadet.}
{147}{}{Tut mir leid, aber ohne Geld kann ich dich nicht behandeln.}
{148}{}{Tut mir leid, aber du bist keiner von uns. Nach 10 Jahren oder mehr in der Brotherhood kann ich dich umsonst operieren. So entstehen uns nur Kosten, und du bist noch kein arbeitendes Mitglied der Brotherhood.}
{149}{}{Sag mir, wenn du das Geld hast.}
{153}{}{Wolltest du dich über eine andere Operation informieren?}
{154}{}{Da läßt sich leider gar nichts mehr machen ... War nur'n Witz! Wir können sofort anfangen. [Sie betäubt dich, und du verlierst langsam das Bewußtsein.]}
{156}{}{Wie geht's uns denn so? [Du spürst schon einen Unterschied zu vorher.] Du bist übrigens sehr gesprächig im Schlaf. Du kannst jetzt gehen. Schönen Tag noch!}
{159}{}{Aus alt mach neu ... [Du fällst wie ein Felsen tief in einen Abgrund.]}
{161}{}{Du siehst unverändert aus, aber wie fühlst du dich? [Deine Sinne sind viel schärfer.] Jetzt brauchen wir allerdings dein Bett, also geh!}
{164}{}{Ich hoffe, du hast ein Herz ... [Sie zwinkert dir zu, während du einschläfst.]}
{166}{}{Du siehst ein bißchen stämmiger aus. [Du fühlst dich großartig!] Laß es mich wissen, wenn es irgendwelche Komplikationen gibt.}
{168}{}{Wo war das Gehirn noch mal? Und was macht man damit? [Du versuchst, dich mit deinem benommenen Kopf zu konzentrieren, aber vergebens.]}
{170}{}{Alles scheint wieder an seinem richtigen Platz zu sein und zu funktionieren. [Es ist so, als ob deine Gedanken in deinem Kopf miteinander verbunden und deine Erinnerungen viel schärfer sind.] Kein Grund zur Panik.}
{174}{}{Okay, schauen wir mal ... [Man verabreicht dir Präparate, die dich langsam in einen tiefen Schlaf fallen lassen.]}
{176}{}{Okay, du bist wieder einsatzbereit. [Du spannst deine Muskeln an und spürst, daß du mehr Kraft und Körperbeherrschung hast.] Alles, worum ich dich bitte, ist, mein bestes Stück nicht zu demolieren.}

{200}{}{Du siehst die Arzthelferin.}
{279}{}{Du solltest zum Arzt gehen.}
{280}{}{Sie ist die Ärztin, nicht ich.}
{281}{}{Ich bin noch in der Ausbildung.}
{282}{}{Offiziell kann ich dir nicht helfen.}
{283}{}{Lori ist die Ärztin.}
{284}{}{Du mußt einen Arzt fragen.}
{285}{}{Keine Panik, sie ist nur ein kleiner Witzbold.}
{286}{}{Sie macht nur gerne mal 'nen Witz, keine Sorge.}

{400}{}{Hmmm, wenn hier irgend jemand mehr Intelligenz braucht, dann du! Ich mache es für 3000 statt der 6000 Deckel, die du normalerweise für die Operation zahlen müßtest. Ich kann zwar keinen Erfolg versprechen, aber ich finde, es ist einen Versuch wert. Deine Genesung dauert 3 Wochen. Wahrscheinlich kapierst du gar nicht, was ich dir hier erzähle, was?}
{401}{}{Ich wollen schlau sein.}
{402}{}{Nicht wollen.}
{403}{}{Bist du verstrahlt oder verletzt? Ich werde dir helfen, wenn ich kann.}
{404}{}{Ich verletzt.}
{405}{}{Haare fallen aus.}
{406}{}{Nein.}
{407}{}{Okay, du bist wach. Laß mal sehen. Fühlst du dich jetzt schlauer?}
{408}{}{Häh?}
{409}{}{Ja!}
{410}{}{Scheiße, schiefgegangen ... Naja, wenigstens hatte ich nicht viel Arbeit  damit. Tut mir leid, aber du bist nun mal ein Idiot und wirst wahrscheinlich auch immer einer bleiben. Wir können die Operation leider nicht wiederholen.}
{411}{}{Es hat geklappt! Ich konnte deinen IQ auf ein akzeptables Niveau bringen. Wie fühlt man sich denn so mit einem halben Gehirn?}
{412}{}{Einfach großartig. Danke, Doktor. Tschüß dann!}
{413}{}{Wird schon wieder.}

# Stat is already maxxed:
{500}{}{Tut mir leid, aber diese Operation wird dir nicht helfen.}

#Poison examine
{504}{}{Ah ja, lass mich sehen...}

#
#Sex
#
{300}{}{Süß, aber ich bin nicht interessiert. Komm wieder vorbei, wenn du medizinische Hilfe brauchst.}
{301}{}{Nimms nicht persönlich. Ich fühle mich geschmeichelt aber du erfüllst nicht ganz meine Ansprüche.}
{302}{}{Oh, vielen Dank. (Sie errötet) Ich bekomme nicht gerade häufig Komplimente. Ärztin der Brotherhood of Steel zu sein ist meistens ein stressiger, undankbarer Job. Ich reiße gerne witze um mich vom Alltag abzulenken}
{303}{}{Ich verstehe. Würde es nicht helfen, ab und zu etwas Dampf abzulassen?}
{304}{}{Gern geschehen. Auf Wiedersehen!}
{305}{}{Nun...ich fühle mich manchmal einsam und du kriegst keine freien Tage als einzige Ärztin in der Brotherhood. Aber was rede ich da? Das ist so albern.}
{306}{}{Du solltest dich damit abfinden. Sei stolz auf deine Arbeit und alles Andere ergibt sich von selbst.}
{307}{}{Das Leben ist kurz. Willst du es nicht genießen so lange es geht?}
{308}{}{Es ist überhaupt nicht albern. (Berühr sanft ihr Gesicht, lehn dich nach vorn und küsse sie)}
{309}{}{Ja, ich nehme an du hast Recht. (Sie schüttelt den Kopf, seufzt, reißt sich zusammen und lächelt) Gut, zurück an die Arbeit. Danke!}
{310}{}{(Sie überlegt einen Moment) Du hast Recht. Will ich. Gib mir zehn Minuten - Ich muss den Untersuchungstisch vorbereiten. (Sie lächelt und beißt auf ihre Unterlippe)}
{311}{}{Sie nimmt deine Hand und führt dich in ihr Quartier...}
{312}{}{Das war wunderschön. Ich...glaube ich liebe dich. (Sie kichert) Ich scherze nur! Alles klar, Zeit zu gehen. Ich muss wieder an die Arbeit.}
{313}{}{Oh wow. So guten Sex hatte ich seit Jahren nicht mehr. Ich werd eine Woche lang wund sein, aber das war's wert. (Sie sieht dich schmachtend an) Lass uns das bald wiederholen!}
{315}{}{Auf jeden Fall! Bis bald.}
{314}{}{Hey Schöne. Mal wieder Lust auf ein bisschen Spaß?}
{316}{}{Was machst d- ... (Sie erschrickt zuerst, gibt sich aber schnell deiner Umarmung hin und erwidert den Kuss) Als eure Berührungen heftiger werden, hält sie inne) Komm mit. (Sie steht auf und zieht dich in ihr Quartier...)}
{317}{}{Oh ja! Und ob!}
{318}{}{(Sie lächelt und nimmt deine Hand...)}
{319}{}{(Also, ich sollte meine Anatomiekenntnisse auffrischen... (Sie zwinkert))