{100}{}{Du siehst eine wunderschöne junge Frau.}
{101}{}{Du siehst Christine, Michaels Frau.}
{102}{}{Hallo? Kann ich dir helfen?}
{103}{}{Wer bist du?}
{104}{}{Wer ist hier der Boss?}
{105}{}{Kannst du mir ein wenig von diesem Gebiet erzählen?}
{106}{}{Nein, danke.}
{107}{}{Bist du meine Mami?}
{108}{}{Mein Name ist Christine, Ich lebe hier mit meinem Mann Michael.}
{109}{}{Razor wacht über die meisten Belange der Blades und hilft uns bei der Organisation.}
{110}{}{Michael und ich sind erst kürzlich hergezogen und ich kenne mich hier noch nicht
 gut aus. Ich hab von einer großen Kirche im Süden gehört, aber das können auch nur Gerüchte sein.}
{111}{}{Gibt es noch was, was ich wissen sollte?}

#
# TRANSLATION NOTE: Do NOT translate the next 4 lines.  They will NOT make any
#sense in any other language.
#
{112}{}{C D E D B D Ducks}
{113}{}{M R Not Ducks}
{114}{}{O S M R C D E D B D Wings}
{115}{}{Y I B M R Ducks}

{116}{}{Kann ich dir sonst noch irgendwie helfen?}
{117}{}{Nein, ich bin nicht deine Mami. Geh' nun spielen.}
