# Junktown
{100}{}{Die haben nie, was ich will.}
{101}{}{Ich glaub', die Auswahl wird auch immer schlechter.}
{102}{}{Diese Preise sind ja völlig überhöht.}
{103}{}{Ich find' nie, was ich will.}
{105}{}{Ich finde die Auswahl des Crimson Caravan besser.}
# BOS
{105}{}{Die haben nie, was ich will.}
{106}{}{Ich glaub', die Auswahl wird auch immer schlechter.}
{107}{}{Diese Preise sind ja völlig überhöht.}
{108}{}{Tut mir leid, ich darf nicht mit Fremden reden.}
{109}{}{Du solltest mit Cabbot oder Darrell reden, wenn du Fragen hast.}
# Necropolis
{110}{}{Mach' dich weg!}
{111}{}{Ich will nicht mit dir reden!}
{112}{}{Ich mag keine Normalos.}
{113}{}{Arrrr!}
{114}{}{Grrrrr!}
# LABone
{115}{}{Die haben nie, was ich will.}
{116}{}{Ich glaub', die Auswahl wird auch immer schlechter.}
{117}{}{Diese Preise sind ja völlig überhöht.}
{118}{}{Ich find' nie, was ich will.}
{119}{}{Ich finde die Auswahl des Crimson Caravan besser.}
#
# by Sduibek, for Fallout Fixt, from original entries:
#
{1100}{}{Du siehst einen Caravankunden.}
{1103}{}{Tut mir leid, ich darf nicht mit Fremden reden.}
{1105}{}{Wenn du irgendwelche Redaleks siehst, sag' mir Bescheid.}
{1107}{}{Ich bin froh, daß die Water Merchants hier nicht mehr herkommen.}
{1109}{}{Cabbot ist unser Grüßer. Du solltest mit ihm oder Darrell sprechen.}
{1110}{}{Mir gefällt das Angebot vom Crimson Caravan besser.}
{1111}{}{Sind die Far Go Traders nicht ein angenehmes Volk?}
{1112}{}{Die Crimson Caravan sind mir zu ordinär.}
