{100}{}{Du siehst einen Sänger der Children.}
{101}{}{Der Meister vergibt dir deine Sünden! Schließ dich uns an und sei frei! Gelobt sei
 der Meister und seine Gnade!}
{102}{}{Hallo, mein Freund! Die Vision des Meisters hat mich erleuchtet.
 Darf ich dir meine wunderbare Geschichte mitteilen?}
{103}{}{Wo kann ich diesen Meister kennenlernen?}
{104}{}{Nur los.}
{105}{}{Wer ist hier der Anführer?}
{106}{}{Ist die Vision des Meisters besser als der Saft der Radscorpions?}
{107}{}{Endet sie etwa mit dem Tod? Wenn nicht, kann ich das ändern!}
{108}{}{Ich mögen Geschichte!}
{109}{}{Der Meister sieht alles! Der Meister ist unter uns! Sieh, wie der Frieden und die
 Einheit wachsen!}
{110}{}{Es war einmal ein Mensch, der war so voller Haß, daß er fast daran zugrunde gegangen
 wäre. Aber jetzt. . . Gelobt sei der Meister! Gelobt sei die Heilige Flamme! Gelobt sei der Weinberg des
 Lebens! Jaaaah!}
{111}{}{Es ist an dir, mein Freund, doch der Meister führt dich. Gelobt sei der Meister!
 Gelobt sei die Heilige Flamme, die uns den Weg erleuchtet!}
{112}{}{Die Vision des Meisters ist viel besser als irgendein Drink, sogar besser als Sex!
 Ohhhh! Er übersteigt sowohl Laster als auch Tugend! Ahhhh! Der Meister ist sowohl Vater
 als auch Geliebter für uns alle!}
{113}{}{Keine Geschichte endet tödlich, solange der Meister hier ist, um uns zu beschützen!}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{114}{}{Ich muß den Meister lobpreisen! Auf bald, mein Freund! Ich erzähl' dir meine
 Geschichte später!}
{115}{}{Ich muß den Meister lobpreisen! Auf bald, meine Liebe! Ich erzähl' dir meine
 Geschichte später!}