{100}{}{Du siehst ein Mitglied der Children of the Cathedral, das sich von niemandem was vormachen läßt.}
{101}{}{Geh' mir aus den Augen, du Schwein!}
{102}{}{Verschwinde!}
{103}{}{Was zum Teufel willst du?}
{104}{}{Wo finde ich diesen Meister?}
{105}{}{Ich will wissen, was hier vor sich geht.}
{106}{}{Wer ist hier der Anführer?}
{107}{}{He, beruhig dich mal! Laß uns was trinken gehen!}
{108}{}{Ich will deinen Skalp für meine Sammlung!}
{109}{}{Ich will keinen Ärger, du Blödmann!}
{110}{}{Fahr zur Hölle, du Idiot!}
{111}{}{Stellst du immer so dumme Fragen, du Idiot?}
{112}{}{Du bist es sicher nicht.}
{113}{}{Warum sollte ich mit dir was trinken gehen, du Kotzbrocken?!}
{114}{}{Verschwinde lieber, bevor ich dich umlege!}
{115}{}{[OK]}
