{100}{}{Du sieht ein kleines Kind.}
{101}{}{Hallo!}
{102}{}{Hallo.}
{103}{}{Wo sind denn deine Eltern?}
{104}{}{Hmpf.}
{105}{}{Weiﬂ nicht. Irgendwo hier.}
{106}{}{Du bist ja witzig!}
{107}{}{He, willst du jemanden umlegen?}
{108}{}{Ja.}
{109}{}{Nein!}
{110}{}{Hmpf.}
{111}{}{Das sag' ich meiner Mami!}
{112}{}{Dann solltest du nicht mit so einer Waffe rumlaufen.}

{980}{}{H‰h?}
{981}{}{Weiﬂ nicht. Frag Mami.}
{982}{}{Frag Papi.}

# Shady Sands kids
{1000}{}{Deathclaw}
{1001}{}{Raiders}
{1002}{}{Junktown}
{1003}{}{Brahmin} 
{1004}{}{Steuerchip}
{1005}{}{Water Merchants}
{1006}{}{Khans}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Hub}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}

{1100}{}{W‰‰! Alptraum-Monster!}
{1101}{}{Fieslinge!}
{1102}{}{Weiﬂ nicht.}
{1103}{}{Stinktiere.}
{1104}{}{Frag Mami.}
{1105}{}{Lustige Seemannslieder.}
{1106}{}{Fieslinge!}
{1107}{}{Bˆser Mann.}
{1108}{}{Sag' ich dir nicht.}
{1109}{}{Groﬂe Stadt.}
{1110}{}{Erz‰hl' ich nicht.}
{1111}{}{Nˆˆ, sag' ich dir nicht.}
{1112}{}{Mami will nicht, daﬂ ich von ihm spreche.}
{1113}{}{Papi findet ihn witzig.}
{1114}{}{Groﬂe Leute.}

# Hub kids
{2000}{}{Polizei}
{2001}{}{Caravan}
{2002}{}{Far Go Traders}
{2003}{}{Children of the Cathedral}
{2004}{}{Necropolis}
{2005}{}{Hot Spot}
{2006}{}{Brotherhood of Steel}
{2007}{}{Boneyard}
{2008}{}{Wasserturm}
{2009}{}{Stadt}
{2010}{}{Downtown}
{2011}{}{Heights}

{2100}{}{Werden von diesen Stinktieren gezogen.}
{2101}{}{Nette Leute. Haben mir Bonbons geschenkt.}
{2102}{}{Sie spielen nicht so gerne Verstecken.}
{2103}{}{Gruseliger Ort.}
{2104}{}{Ekliger Ort.}
{2105}{}{Gruseliger Ort.}
{2106}{}{Gruseliger Ort.}
{2107}{}{Mami l‰ﬂt uns da nicht spielen.}
{2108}{}{Papa will immer, daﬂ wir dort spielen.}
{2109}{}{Wo die Groﬂen sind.}
{2110}{}{Wo die Groﬂen sind.}

# Fo1in2
# Razlo's kids
{300}{}{Papa ist gleich da dr¸ben! Kannst du schlecht gucken?}
{301}{}{Mama ist gleich da dr¸ben! Kannst du schlecht gucken?}
