{100}{}{Du siehst ein frommes Mitglied der Children of the Cathedral.}
{101}{}{Wir heilen dein Fleisch, um deine Seele zu retten. Kann ich dir helfen?}
{102}{}{Ja, hilf mir.}
{103}{}{Wer seid ihr?}
{104}{}{Ööh.}
{105}{}{Schon gut. Wir untersuchen dich jetzt.}
{106}{}{Gesegnet sind die Schwachen im Geiste. Es fehlt dir nichts. Geh dann!}
{107}{}{Du bist geheilt. Sei in Zukunft vorsichtiger!}
{108}{}{Du bist verletzt.}
{109}{}{Du bist nicht verletzt. Gut.}
{110}{}{Du bist vergiftet worden.}
{111}{}{Hmm, eine Strahlungsvergiftung. Leider können wir das nicht heilen.}
{113}{}{Wir brauchen eine Spende von }
{114}{}{ Deckel, bevor wir dich heilen können. Ist das in Ordnung?}
{115}{}{Ja.}
{116}{}{Nein.}
{117}{}{Aber ich habe kein Geld!}
{118}{}{Nehmt ihr auch }
{119}{}{ Deckel?}
{120}{}{Die Children feilschen nicht. Also akzeptierst du unseren Preis?}
{121}{}{Ja, natürlich.}
{122}{}{Nein, danke.}
{123}{}{Dank dir, mein Sohn. Lass uns beten, dass du gesund wirst.}
{124}{}{Dank dir, meine Tochter. Lass uns beten, dass du gesund wirst.}
{125}{}{So, bitte. Frieden und Segen der Children sei mit dir.}
{126}{}{Du hast nicht genug Geld. Wenn du alles gibst, was du hast, können wir dich heilen. Ist das in Ordnung?}
{127}{}{Ja.}
{128}{}{Nein.}
{129}{}{Wenn du uns alles gibst, was du hast, können wir dich heilen. Ist das in Ordnung?}
{130}{}{Ja.}
{131}{}{Nein}
{132}{}{Du hast mehr als genug. Du brauchst wohl Nachhilfe im Rechnen!}
{133}{}{Wir sind die Children of the Cathedral. Wir leben und arbeiten mit den Unglückseligen, die hier im Ödland leben. Solltest du jemals zum Boneyard kommen, kehr bei der Kathedrale ein.}
{134}{}{Danke.}
{135}{}{Was macht ihr?}
{136}{}{Wir sind die Heiler und Lehrer des Friedens. Wir heilen das Fleisch, um den Geist zu retten. Alles, worum wir bitten, ist eine kleine Spende für unsere Medikamente.}
{137}{}{Hört sich gut an.}
{138}{}{Hört sich nach ziemlichem Schwachsinn an, wenn du mich fragst.}
{139}{}{Wir haben dich aber nicht gefragt. Ich sehe, dass du nichts mehr über unseren Glauben hören willst. Wenn du was brauchst, du weißt ja, wo du uns findest.}
{140}{}{Es ist die heiligste aller Ideen. Wir versuchen, dem Ödland Frieden zu bringen. Alle Kreaturen sollen in Frieden miteinander leben.}
{141}{}{Danke, bis bald dann!}
{142}{}{Wir haben leider keine Zeit für lange Reden. Dieser Ort ist zu gefährlich.}
{143}{}{Warum tust du das? Wir wollen dir nicht schaden!}

{980}{}{Darüber weiß ich nichts.}
{981}{}{Entschuldige, keine Ahnung.}
{982}{}{Nie davon gehört.}

{1000}{}{Children of the Cathedral|Children|Cathedral|CoC}
{1001}{}{Mutanten|Mutant|Ghul|Ghuls|Ghule}
{1002}{}{Meister}
{1003}{}{Boneyard|Der Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard}
{1004}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{1005}{}{Steuerchip|Wasserchip|Chip}
{1006}{}{Necropolis|Nekropolis|Stadt der Toten|Todesstadt}
{1007}{}{Set|Seth}
{1008}{}{Quelle|Stelle|Wasserstelle|Wasser Stelle}
{1009}{}{Halle|Halle der Toten|Todeshalle|Totenhalle}
{1010}{}{Hilfe|Hilf mir|Doktor|Sanitäter|Arzt}
{1011}{}{Einheit}
{1012}{}{Kauf|Kaufen|Einkaufen|Verkauf|Verkaufen|Handel|Handeln|Geschäft|Warenhandel|Waren handel|Waren}
{1013}{}{Wasser}
{1014}{}{Vault|Vault12|Vault 12|Vault-12|Bunker|Bunker12|Bunker 12|Bunker-12}
{1015}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land}
{1016}{}{Richtung|Richtungen|Wohin|wo hin|wo bin ich|hier|dort|Wegbeschreibung|Wegbeschreibungen|Anweisung|Anweisungen}
{1017}{}{Stehlen|Dieb|Diebe|Verbrechen|Verbrecher|Kriminelle|Kriminalität}
{1018}{}{Heilige Flamme|Heilig|Flamme|Flame Deluge}
{1019}{}{Fallout|Fall out|nuklearer fallout|nuklearer niederschlag|strahlung|Rads|Rem}
{1020}{}{Rippers|Ripper}
{1021}{}{Blades|Blade}
{1022}{}{Gun Runners|Gunrunners|Gun Runner|Gunrunner|Gun-Runners|Gun-Runner}
{1023}{}{Adytum|Adytown}

{1100}{}{Das sind wir.}
{1101}{}{Das sind Leute, die vom Atomkrieg mutiert wurden, aber sie sind trotzdem in Ordnung.}
{1102}{}{Wir haben alle einen Meiser, oder?}
{1103}{}{Der Boneyard ist ein Ort des Hasses. Es gibt die Followers of the Apocalypse, verschiedene Banden wie die Rippers, Blades und Gunrunner sowie eine kleine Siedlung namens Adytum.}
{1104}{}{Das sind Leute, die den Frieden zerstören wollen, den unser Meister bewahren will.}
{1105}{}{Ich habe keine Ahnung, wovon du redest.}
{1106}{}{Das ist hier. Die traurigen Überreste einer alten Welt.}
{1107}{}{Ich glaub', er ist einer von den Ghuls.}
{1108}{}{Das ist dort drüben im Nordosten.}
{1110}{}{Natürlich. Für eine kleine Spende können wir dir helfen.}
{1111}{}{Wir sind alle Teil der Einheit. Es ist die Liebe und der Frieden, die wir an unsere Mitmenschen weitergeben, unabhängig davon, ob wir Menschen oder Mutanten sind.}
{1112}{}{Vielleicht können wir ein paar Vorräte erübrigen.}
{1113}{}{Natürlich werden wir teilen ... für eine kleine Spende.}
{1114}{}{Die Ghuls sprechen manchmal über alte Zeiten. Ich weiß jedoch nichts darüber.}
{1115}{}{Wenn du wirklich gläubig bist, führt dich die Heilige Flamme durch das Wasteland in Sicherheit.}
{1116}{}{Mein Kind, gibt es anderen Ort, an den ich gehen kann?}
{1117}{}{Du solltest nicht an so etwas Böses denken, mein Kind.}
{1118}{}{Die Heilige Flamme ist diejenige, die uns in eine schöne neue Welt führen wird, die weder Hass noch Krieg kennt.}
{1119}{}{Der nukleare Niederschlag. Es bringt uns allen den Tod.}
{1120}{}{Eine der Gangs im Boneyard. Das letze was ich gehört habe war, dass sie von etwas oder jemandem ausgelöscht wurden.}
{1121}{}{Das ist eine Gang im Boneyard.}
{1122}{}{Eine der Gangs des Boneyard.}
{1123}{}{Eine kleine Siedling im Boneyard.}
