{100}{}{Du siehst einen dunkelhäutigen Mann, der bunte Schals trägt und mit Schmuck behangen ist.}
{101}{}{Du siehst Chuck, den Zigeunerwahrsager.}
{102}{}{Hallo, Fremder. Womit kann ich dienen?}
{103}{}{Uugh!}
{104}{}{Ich schau' nur rum, danke.}
{105}{}{Langsam lerne ich die Leute von Adytum kennen.}
{106}{}{Warum denkst du, daß ich etwas brauche?}
{107}{}{Hmm. Mach dir keine Sorgen, mein Freund, dich erwarten große Dinge.}
{108}{}{Und was hältst du von unserer Stadt?}
{109}{}{Schon in Ordnung.}
{110}{}{Nicht so mein Ding. Ziemlich unfreundlich.}
{111}{}{Du hast dich wacker geschlagen, trotz des feindlichen Empfangs.}
{112}{}{Ich heiße Chuck. Willkommen in Adytum. Ich fürchte, die meisten Leute hier sind Fremden gegenüber nicht allzu aufgeschlossen.}
{113}{}{Ja, ist mir auch schon aufgefallen.}
{114}{}{So, was machst du hier so, Chuck?}
{115}{}{Bis bald mal wieder, Chuck.}
{116}{}{Gute Reise, Fremder.}
{117}{}{Wir brauchen doch alle etwas, oder? Und du hättest mich nicht angesprochen, wenn du nicht irgend etwas suchen würdest, sei es Informationen, Unterhaltung oder Unterstützung. Man sieht dir an, daß du eine Menge mitgemacht hast. Was brauchst du also?}
{118}{}{Öööh, ich brauche überhaupt nichts, danke.}
{119}{}{Jetzt wo du es sagst ... Vielleicht kannst du mir ja doch weiterhelfen.}
{120}{}{[Chuck holt seine Tarotkarten raus.] Laß mich die Karten befragen. [Chuck mischt seine Karten.]}
{121}{}{[Chuck zieht zwei Karten. Eine zeigt einen Mann in einem weißen Laborkittel mit einem Computer auf dem Arm, und die andere zeigt einen Mann in edler Rüstung.] Der Hierophant und der Prinz der Stäbe im Süden. Große Weisheit und Ehre erwarten dich an einem Ort im Süden.}
{122}{}{[Chuck zieht eine Karte. Sie zeigt einen Mann mit einem Vibro-Schwert und einer Flagge.] Der Prinz der Schwerter im Norden. Du mußt einen mächtigen Feind im Norden haben.}
{123}{}{[Chuck zieht zwei Karten. Die eine zeigt einen Funkturm und die andere einen Mann im Anzug mit Zepter.] Der Turm und der Kaiser ... Große Veränderungen werden durch einen mächtigen Anführer geschehen. Ob das deinen Tod bedeutet, kann ich nicht sagen.}
{124}{}{[Chuck zieht eine Karte. Sie zeigt einen Mann, der auf einem atomaren Sprengkopf tanzt.] Der Joker. Ich kann dir nicht weiterhelfen. Du mußt deinen eigenen Weg finden.}
{125}{}{[Mehr]}
{126}{}{Hmm. Danke für den Rat.}
{127}{}{Glaubst du wirklich daran?!}
{128}{}{Mir hilft es. Wenn du nicht daran glaubst, dann ist das nichts für dich.}
{129}{}{Nimm es mir nicht übel, aber das hört sich schwer nach Aberglaube an.}
{130}{}{Ich denke, jeder glaubt an das, was ihm gefällt.}
{131}{}{Wenn du so denkst, dann brauchen wir uns nicht mehr länger zu unterhalten.}
{132}{}{Ja, so ist es. Aber deine Welt ist durch deinen Glauben geprägt, während meine Welt durch meine Gedanken geprägt ist. Wir haben vielleicht nicht denselben Glauben, aber ich wünsche dir trotzdem Glück in deiner Welt.}
{133}{}{Es ist mein Zuhause.}
{134}{}{Öh, ja. Bis bald mal wieder.}
{135}{}{Hier ist recht wenig los.}
{136}{}{Ich weiß, was du meinst. Ich habe viele Leute leiden sehen.}
{137}{}{Die Regulatoren sorgen schon dafür. Das Volk von Adytum leidet manchmal unter ihren strengen Gesetzen.}
{138}{}{Das stimmt wohl. Bis bald.}
{139}{}{Und das ist für dich in Ordnung?}
{140}{}{Ich möchte hierbleiben, deshalb akzeptiere ich die Regulatoren als einen Teil von Adytum. Jedoch tue ich, was ich kann, um ihnen das Leben zu erleichtern.}
{141}{}{Du scheinst nicht einer Meinung mit ihnen zu sein.}
{142}{}{Gibt es sonst noch was, was man tun kann?}
{143}{}{Die Regulatoren schützen nur ihre eigenen Interessen, und das muß ich respektieren.}
{144}{}{Ja, sicher.}
{145}{}{Das ist nicht unbedingt meine Meinung, aber ich verstehe das.}
{146}{}{War interessant, mit dir zu reden. Bis bald.}
{147}{}{Ich bin allein, aber ich tue, was ich kann. Ich rate dir, um das zu kämpfen, an das du glaubst. Aber vor allem denke dran: Der Kampf muß sich auch lohnen, und manchmal liegt der Sieg im Kompromiß und in der Hoffnung.}
{148}{}{Sonst noch was?}
{149}{}{Das Volk von Adytum ist am Tag ziemlich beschäftigt. Nach dem Motto: Was du heute kannst besorgen, das verschiebe nicht auf morgen.}
{150}{}{Ja, sicher. Wie du meinst.}
{151}{}{Hier ist recht wenig los.}
{152}{}{Danke. Es war nicht so ganz einfach. Manchmal verlieren wir Leute durch die Deathclaw, und der Winter ist hier ziemlich hart, besonders wenn die Händler vom Hub nicht zu uns kommen. Aber wir halten durch.}
{153}{}{Viel Glück.}
{154}{}{Was ist los mit der Deathclaw?}
{155}{}{Sie hat sich nordöstlich von hier angesiedelt und überfällt des öfteren die Leute, die mit den Gunrunnern Geschäfte machen.}
{156}{}{Na, hoffentlich findest du dafür bald eine Lösung.}
{157}{}{Ja, sicher.}
{158}{}{Vielleicht. Adytum wird jedenfalls hier sein. Ich glaub', bevor wir auf die anderen zugehen, sollen die eher auf uns zukommen, so wie du.}
{159}{}{Hmm. Denke schon.}
{160}{}{Ich bin Bauer. Manchmal arbeite ich auch an Häusern, baue neue oder halte sie Instand, und seh' zu, daß sie ganz bleiben. Und manchmal gebe ich einen guten Rat.}
{161}{}{Was für einen Rat?}
{162}{}{Ja, leider. Ich denke ... Es ist ziemlich wichtig, daß wir in harten Zeiten zusammenhalten und voneinander lernen, was wir zum Überleben brauchen. Am Ende kann die Menschheit dadurch nur gewinnen.}
{163}{}{Der Meinung bin ich nicht. Ich bin vielen Banden und Gangstern auf meinen Reisen begegnet - alles Mörder und Diebe. So was kann uns auch bevorstehen.}
{164}{}{Vielleicht hast du ja recht. Natürlich überleben nur die Starken.}
{165}{}{Sie werden sich letztendlich alle umbringen. Und die Leute, die überleben werden, sind die, die zusammenhalten. So wie wir.}
{166}{}{Ich bin froh, daß manche der Fremden so wie du denken. Wir müssen einen Weg finden, zusammen etwas Neues aufzubauen. Von hier wird der Neubeginn jedoch nicht ausgehen, denn wir werden zu sehr unterdrückt, aber irgendwo wird schon jemand den Anfang machen.}
{167}{}{Hallo. Was kann ich für dich tun?}
{168}{}{Kann ich dir helfen?}
{169}{}{Ja?}
{170}{}{Bin nur vorbeigekommen, um einen guten Tag zu wünschen.}
{171}{}{Ich brauche deinen Rat.}
{172}{}{Darf ich fragen, was du hier machst?}
{173}{}{Hallo, du da! Ich hoffe, dir geht es gut.}
