{100}{}{Du siehst einen Bewohner von Shady Sands.}
{101}{}{Willkommen in Shady Sands, Fremder!}
{102}{}{Ööh, danke.}
{103}{}{Und was geht hier ab?}
{104}{}{Hmmmh!}
{105}{}{Wir sind eine echte Gemeinde. Wir arbeiten und teilen alles zusammen.}
{106}{}{Wie könnt ihr hier draußen überleben?}
{107}{}{Wer ist euer Anführer?}
{108}{}{Wir haben hier Bauernhöfe und Bewässerungsanlagen. Außerdem halten wir Brahmin. Jeder
 trägt seinen Teil dazu bei.}
{109}{}{Aradesh ist unser jetziger Elder. Mit seiner Erfahrung hilft er, die Gemeinde zu führen.}
{110}{}{Hi.}
{111}{}{Hallo.}
{112}{}{Wie geht's?}
{113}{}{Schön, dich zu treffen.}
{114}{}{Guten Tag.}
