{100}{}{Das hier sieht aus wie ein alter Energiefeldcomputer.}
{101}{}{Er hat anscheinend einen Transmitter für Funkkontakt, einen Empfänger und einen Standardanschluß für Funkdaten.}
{102}{}{Wenn du den Energiefeldcomputer anstellst, hörst du ein tiefes Brummen, das den ganzen Komplex durchdringt.}
{103}{}{Du bedienst den Computer nicht richtig.}
{104}{}{Du kannst den Energiefeldcomputer deaktivieren. Alle Steuerelemente sind verschlüsselt und gesperrt.}
{105}{}{Du verstehst das Betriebssystem des Computers nicht.}
{106}{}{Die Energiefeld-Subsysteme können es natürlich nicht mit dir aufnehmen. Du schaltest alle Energiefelder auf diesem Level aus.}
{107}{}{Die Energiefeld-Subsysteme sind zu gut gesichert, aber du schaffst es, einen Teil davon auszuschalten. Das ist im Moment alles, was du tun kannst.}
{108}{}{Die Energiefeld-Subsysteme sind zu gut gegen unerlaubten elektronischen Zugriff gesichert. Du versuchst es eine Weile, kannst sie aber nicht durchbrechen.}
{109}{}{Du sprengst die Bank bei einem 17-und-4-Spiel und schleichst dich über den Ende-Bildschirm in das Hauptsystem.}
{110}{}{Du läßt dich auf ein 17-und-4-Spiel ein, schaffst es aber nicht, die Bank zu knacken.}
{111}{}{Der einzige ungesicherte Ordner, den man als Hintertürchen hernehmen könnte, heißt Freizeitspiele.}
{112}{}{Der einzige ungesicherte Ordner heißt Freizeitspiele.}
{113}{}{Der Computer widert dich an.}
{114}{}{Du glaubst, das alle Ordner gesichert sind, hast aber deine Suche noch nicht beendet.}
{115}{}{Du hast das Hauptsystem geknackt und mußt nun die Energiefeldsteuerung umprogrammieren.}
{116}{}{Du hast 800 Bonuspunkte für dein außergewöhnliches Computerhacking gewonnen. Sieg!}
{117}{}{Du verbindest das Funkgerät mit dem Energiefeldcomputer.}
{118}{}{Dein Versuch, das Funkgerät mit dem Energiefeldcomputer zu verbinden, schlägt fehl.}