
#
# Talking cows special encounter text
#

{100}{}{Muh.}
{101}{}{Muh!}
{102}{}{Muh, sag ich.}
{103}{}{Das ist ein wildes Brahmin.}
{104}{}{An denen ist doch nichts echt. Diese zwei Köpfe können doch nur durch irgendeine
 eigenartige Mutation entstanden sein.}
{105}{}{Dir kommen sie recht normal vor.}
