{100}{}{Die Tür ist vergeschlossen. Du hast so ein Schloss noch nie gesehen.}
{101}{}{Die Tür ist zu, aber nicht vergeschlossen.}
{102}{}{Du versuchst die Tür zu öffnen, aber es gelingt dir nicht. Auf einmal merkst du, dass die Tür verschlossen ist.}
{103}{}{Es gelingt dir nicht, das Türschloss zu knacken.}
{104}{}{Du knackst das Türschloss.}
