{100}{}{Die Person könnte von der Brotherhood of  Steel sein.}
{101}{}{Du fragst dich, was einem Mitglied der Brotherhood so viel Schaden zurichten konnte.}
{102}{}{Der das getan hat scheint nicht mehr hier zu sein.}
{103}{}{Der das getan hat könnte noch unten im Komplex lauern. Du solltest ein bißchen
 vorsichtig sein, wenn du hier durchgehst.}
{104}{}{Du fragst dich, was diesen Roboter getötet haben könnte.}
{105}{}{Du fragst dich, ob der Roboter vielleicht durch die Explosion getötet wurde.}
{106}{}{Daran haben vielleicht die Wissenschaftler hier gearbeitet.}
