{100}{}{Decker will nicht mehr mit dir sprechen.}
{101}{}{Du siehst Decker.}
{102}{}{Decker hat zuviel zu tun, um mit dir zu reden. Mach deine Arbeit und komm später wieder.}
{103}{DECK_1}{Du suchst also einen Job? Was für ein Zufall! Ich hätte was für dich. Ach, wo sind bloß meine Manieren? Wie heißt du?}
{104}{}{Ich heiße }
{105}{}{.}
{106}{}{Was geht dich das an?}
{107}{DECK_2}{Also, Schluss jetzt mit den Floskeln. Möchtest du etwas über den Job wissen?}
{108}{}{Deshalb bin ich hier.}
{109}{}{Nicht unbedingt.}
{110}{DECK_3}{Hintergrund: Es gibt da einen gewissen Händler, der ... äähh ... nicht völlig mit dem Untergrund kooperiert.}
{111}{}{Und der Job?}
{112}{DECK_4}{Ganz einfach. Finde den Händler und seine Frau, und mach sie alle.}
{113}{}{Heißt das etwa, sie töten?}
{114}{}{Wieviel springt dabei raus?}
{115}{}{Das kann ich nicht machen.}
{116}{DECK_5}{Alles eine Frage der Semantik. Töte sie. Und machst du's?}
{117}{}{Hmm, klar. Warum nicht?}
{118}{}{Nein! Das wäre falsch.}
{119}{}{Wieviel?}
{120}{DECK_6}{Oh, prima. Die übliche Bezahlung ist 500 Scripts vorab und noch mal 2500 nach ... Ausführung.}
{121}{}{Wo kann ich diesen Händler und seine Frau finden?}
{122}{DECK_7}{In den Heights, Ecke Barter Street und Thunder Avenue. Töte sie und komm zurück.}
{123}{}{Okay, wird erledigt.}
{124}{}{Woher weißt du, dass ich sie wirklich getötet habe?}
{125}{}{Ich glaube nicht.}
{126}{DECK_8}{Ausgezeichnet. Mein Assistent gibt dir auf dem Weg nach draußen das Geld. Bitte mach die Tür hinter dir zu.}
{127}{deck_9}{Vertrau mir. Ich weiß es.}
{128}{}{Okay, ich mach's.}
{129}{}{Ich lass' es lieber.}
{130}{DECK_10}{Ich bin ein wenig ... enttäuscht von dir. Aber das kann passieren. Vergiss nicht, das hier ist vertraulich. Schönen Tag noch!}
{131}{DECK_11}{Die übliche Bezahlung: 500 Deckel vorab, weitere 2500, wenn der Job erledigt ist. Machst du's?}
{132}{}{Nein, danke.}
{133}{}{Ja, ich mach's.}
{134}{DECK_12}{Sehr schön! Der Händler lebt in den Heights, Ecke Barter Street und Thunder Avenue. Deine erste Gage erhältst du auf dem Weg nach draußen.}
{135}{DECK_13}{Alles ist meine Angelegenheit im Hub. Erzähl's mir oder geh.}
{136}{}{Ich heiße }
{137}{}{.}
{138}{}{Ich muss dir nicht alles erzählen.}
{139}{DECK_14}{Aha ... Mein Assistent wird dich hinausbegleiten.}
{140}{DECK_15}{Ich bin stolz auf dich. Du bist unbarmherzig, das bewundere ich. Kane wird dich bezahlen. Ich hoffe, du hilfst uns auch in Zukunft.}
{141}{}{Kann ich dir ein paar Fragen stellen?}
{142}{}{Danke.}
{143}{DECK_16}{Unter diesen Umständen, ja.}
{144}{}{Was gibt es im Hub?}
{145}{}{Irgendwelche Neuigkeiten?}
{146}{}{Schon gut.}
{147}{Deck_16b}{Fasse dich kurz, bitte.}
{148}{DECK_17}{Der Merchant Market ist im Stadtzentrum, umgeben von Gebäuden. Die Heights sind im Westen, und Old Town ist im Osten.}
{149}{}{Was für Gebäude?}
{150}{}{Danke für die Auskunft. Kann ich dich vielleicht noch was fragen?}
{151}{DECK_18}{Du bist hier im 'Maltese Falcon'. Es gibt noch den Krämerladen, den Waffenladen, die Friendly Lending Company, die Polizei und - leider - das Krankenhaus der Children.}
{152}{}{Du scheinst nicht gerade begeistert von den Children of the Cathedral zu sein. Was ist los?}
{153}{}{Danke. Kann ich dich vielleicht noch was fragen?}
{154}{DECK_19}{Sie ... mischen sich ein. Mehr sag' ich jetzt nicht, ja?}
{155}{}{Okay. Kann ich dir vielleicht noch ein paar Fragen stellen?}
{156}{DECK_20}{Ich bin kein Fremdenführer. Sieh dich selbst um.}
{157}{}{Kann ich dir noch ein paar Fragen stellen?}
{158}{}{Stimmt. Fremdenführer sind gewöhnlich auch viel netter.}
{159}{DECK_21}{Nein. Hol deine Bezahlung ab und geh.}
{160}{DECK_22}{Wie bitte?}
{161}{}{Ich glaub', du hast mich verstanden.}
{162}{}{Nichts. Kann ich dir vielleicht noch ein paar Fragen stellen?}
{163}{DECK_23}{Du bist arrogant. Mein Assistent wird dir zeigen, wo es lang ... ähm ... hinausgeht.}
{164}{deck_24}{Nein.}
{165}{}{Kann ich dich was anderes fragen?}
{166}{}{Du bist ja ein komischer Typ.}
{167}{DECK_25}{Jemand scheint den Far Go Traders ganze Caravans zu stehlen, und der Thieves Circle verursacht die üblichen kleinen Probleme.}
# Line 168 has been changed due to gender issues. See lines 232-233.
{168}{}{}
{169}{}{Klar.}
{170}{}{Für nichts in der Welt!}
{171}{DECK_27}{Ausgezeichnet. Weißt du, dein letzter Job war ein Test, und du hast dich gut bewährt. Dieser Job ist echt wichtig.}
{172}{}{Und der wäre?}
{173}{}{Klingt unheimlich. Ich glaub', ich hab' kein Interesse.}
{174}{DECK_28}{Wie du vielleicht ... äh ... weißt, nimmt der Einfluss der Children of the Cathedral zu, und - ehrlich - ich dulde das nicht.}
{175}{}{Was soll ich also machen?}
{176}{DECK_29}{Eine Kleinigkeit. Töte die Hohepriesterin Jain. Sobald sie weg ist, wird dieses kleine Ärgernis ein Ende haben. Interessiert?}
{177}{}{Klar.}
{178}{}{Aber das wäre unmoralisch.}
{179}{DECK_30}{Ich glaube, ich fange an, dich zu mögen. Die Bezahlung beträgt 1000 vorab und 4000 bei Abschluss. Vertrau mir, ich weiß, wenn's erledigt ist.}
{180}{}{Okay.}
{181}{DECK_31}{Sprich mit Kane auf dem Weg hinaus. Er sagt dir mehr.}
{182}{DECK_32}{Und den Händler zu töten etwa nicht?}
{183}{}{Also, okay, ich mach's.}
{184}{}{Mag sein, aber ich mach's nicht.}
{185}{DECK_33}{Die Bezahlung beträgt 1000 vorab und 4000 bei ... Vollstreckung. Glaub mir, ich weiß, wenn's vorbei ist.}
{186}{}{Okay.}
# Line 187 has been changed due to gender issues. See 234-235.
{187}{}{}
{188}{DECK_35}{Wie schade. Willst du nicht einmal wissen, worum es geht?}
{189}{}{So ist es. Ich mach's nicht.}
{190}{}{Okay, worum geht's?}
{191}{DECK_36}{Wir haben nichts weiter zu besprechen.}
{192}{DECK_37}{Ausgezeichnete Arbeit. Ich glaube nicht, dass die religiöse Fraktion sich noch einmal einmischt. Kane gibt dir die Belohnung. Ich danke dir ... und werde in Zukunft an dich denken.}
{193}{DECK_38}{Stell das hin!}
{194}{DECK_39}{Meine Geduld ist groß, doch hat sie auch Grenzen. Kane, erteile diesem Einfallspinsel eine Lektion.}
{195}{DECK_40}{Lass das!}
{196}{DECK_42}{Sprich mit Kane darüber. Er kann dir mehr erzählen.}
{197}{DECK_43}{Ich sagte ...}
{198}{DECK_44}{Wie ich sagte ...}
{199}{DECK_45}{Ich hab' dir bereits gesagt ...}
{200}{DECK_46}{Hast du denn nicht zugehört? Ich sagte ...}
{201}{DECK_47}{Pass auf. Ich bin es nicht gewohnt, mich zu wiederholen.}
{202}{DECK_48}{Ich sage es nicht noch einmal.}
{203}{DECK_49}{Sonst brauchst du nichts über mich zu wissen.}
{204}{DECK_50}{Die meisten werfen mit dem Namen meiner Organisation nicht einfach so um sich. Wir beherrschen den Hub.}
{205}{DECK_51}{Meine Mutter, die hinreißendste Frau überhaupt, hat mich auf die Idee für das größte Vergnügen im ganzen Hub gebracht.}
{206}{DECK_52}{Sie stehlen von den Händlern und geben es den Armen oder so was Dummes. Unlogisch! Der alte Mutant Harold weiß mehr darüber.}
{207}{DECK_53}{Er ist der Polizeichef. Netter Kerl, wenn einem der aufrichtige, ehrliche Typ zusagt. Nicht wie sein Vater, der war uns immer treu.}
{208}{DECK_54}{Harold ist schon eine Weile dabei. Er ist drüben in Old Town. Eine gute Quelle für gewisse Informationen.}
{209}{DECK_55}{Sie kontrollieren das Wasser. Sie sind am Südende des Merchant Market.}
{210}{DECK_56}{Chef der Water Merchants.}
{211}{DECK_57}{Sie hatten das Krankenhaus unter sich, bis die Children es übernahmen. Jetzt sitzen und brüten sie im Lagerhaus - schon komisch. Sie sind am nordwestlichen Ende des Merchant Market.}
{212}{DECK_58}{Er ist der Chef des Crimson Caravan.}
{213}{DECK_59}{Sie sind die letzten Händler, und ich meine das wortwörtlich. Haben fast nur Kleinkram. Sind nordöstlich vom Merchant Market.}
{214}{DECK_60}{Witzig. Er hält sich für den Anführer der Far Go Traders. Ist aber eigentlich eine Marionette. Der wagt es nicht, sich in meine Geschäfte einzumischen.}
{215}{DECK_61}{Sie leitet den Waffenladen.}
{216}{DECK_62}{Irgend etwas lässt die Caravans der Far Go Traders verschwinden. Ich wüsste gerne was, denn es stört auch meine Geschäfte.}
{217}{Deck_63}{Er ist im Stadtzentrum.}
{218}{DECK_64}{Fabeln und Märchen. Die Deathclaw ist wohl ein Geist oder so was.}
{219}{DECK_65}{Old Town erstreckt sich über die Ostseite. Die Skags leben dort.}
{220}{DECK_66}{Die meisten Händler leben dort. Richtung Westen.}
{221}{DECK_67}{Eine lästige Organisation. Ich muss denen mal zeigen, wie man mit Macht umgeht.}
{222}{DECK_68}{Morpheus ist der Chef der Children of the Cathedral. Er wohnt unten im Boneyard.}
{223}{DECK_69}{Sie ist derzeit die Chefin der Children of the Cathedral im Hub. Ich habe Grund zur Annahme, dass sich das bald ändern wird.}
{224}{DECK_70}{Eine der Erfindungen der Children. Ein kleiner, unwichtiger Gott oder so was.}
{225}{DECK_71}{Ein kleiner Laden mit ganz guten Waffen, drüben bei den Far Go Traders.}
{226}{DECK_72}{Zur Tür raus und dann nach Norden. Ganz einfach.}
{227}{DECK_73}{Das ist unwichtig.}
{228}{DECK_74}{Was? Das ist jetzt nicht wichtig.}
{229}{DECK_75}{Wirklich. Und warum sollte ich das tun?}
{230}{}{Du hast meinen Sekundanten beseitigt. Da muss ich mich wohl selbst um dich kümmern.}
{231}{}{Gut, Sie zu sehen, Sheriff Greene! Wie ich sehe, wollen Sie sich verabschieden.}
#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{232}{DECK_26}{Guten Tag, mein Freund. Ich hätt' noch 'nen Job für dich. Interessiert?}
{233}{DECK_26}{Guten Tag, meine Freundin. Ich hätt' noch 'nen Job für dich. Interessiert?}

{234}{DECK_34}{Ich hatte große Hoffnungen in dich gesetzt! Aber du darfst die Children nicht warnen. Kane, entferne unseren Freund, und sorge für ... äh ... Ruhe.}
{235}{DECK_34}{Ich hatte große Hoffnungen in dich gesetzt! Aber du darfst die Children nicht warnen. Kane, entferne unsere Freundin, und sorge für ... äh ... Ruhe.}

# Decker Tell-Me-Abouts generic responses
{980}{DECK_73}{Das ist unwichtig.}
{981}{DECK_74}{Was? Das ist jetzt nicht wichtig.}
#
# Decker Tell-Me-Abouts
#
{1000}{}{Decker}
{1001}{}{Untergrund}
{1002}{}{Maltese Falcon}
{1003}{}{Thieves Circle}
{1004}{}{Justin}
{1005}{}{Harold}
{1006}{}{Water Merchants}
{1007}{}{Daren}
{1008}{}{Crimson Caravan}
{1009}{}{Demetre}
{1010}{}{Traders}
{1011}{}{Butch}
{1012}{}{Beth}
{1013}{}{Caravan}
{1014}{}{Merchant Market}
{1015}{}{Deathclaw}
{1016}{}{Old Town}
{1017}{}{Heights}
{1018}{}{Children}
{1019}{}{Morpheus}
{1020}{}{Jain}
{1021}{}{Meister}
{1022}{}{Waffenladen}
{1023}{}{General Store}
{1024}{}{Maltese Falcon}
{1025}{}{Vergnügen}
{1026}{}{Greene}
{1027}{}{Hightower}
{1028}{}{Caravans}
{1029}{}{Romara}
{1030}{}{Far Go}
{1031}{}{Far Go Traders}
{1032}{}{Harris}
{1033}{}{Death Claw}
{1034}{}{Deathclaw}
{1035}{}{Old Town}
{1036}{}{Oldtown}
{1037}{}{Children of the Cathedral}
{1038}{}{Krämerladen}

{1100}{DECK_49}{Sonst brauchst du nichts über mich zu wissen.}
{1101}{DECK_50}{Die meisten werfen mit dem Namen meiner Organisation nicht einfach so um sich. Wir beherrschen den Hub.}
{1102}{DECK_51}{Meine Mutter, die hinreißendste Frau überhaupt, hat mich auf die Idee für das größte Vergnügen im ganzen Hub gebracht.}
{1103}{DECK_52}{Sie stehlen von den Händlern und geben es den Armen oder so was Dummes. Unlogisch! Der alte Mutant Harold weiß mehr darüber.}
{1104}{DECK_53}{Er ist der Polizeichef. Netter Kerl, wenn einem der aufrichtige, ehrliche Typ zusagt. Nicht wie sein Vater, der war uns immer treu.}
{1105}{DECK_54}{Harold ist schon eine Weile dabei. Er ist drüben in Old Town. Eine gute Quelle für gewisse Informationen.}
{1106}{DECK_55}{Sie kontrollieren das Wasser. Sie sind am Südende des Merchant Market.}
{1107}{DECK_56}{Chef der Water Merchants.}
{1108}{DECK_57}{Sie hatten das Krankenhaus unter sich, bis die Children es übernahmen. Jetzt sitzen und brüten sie im Lagerhaus - schon komisch. Sie sind am nordwestlichen Ende des Merchant Market.}
{1109}{DECK_58}{Er ist der Chef des Crimson Caravan.}
{1110}{DECK_59}{Sie sind die letzten Händler, und ich meine das wortwörtlich. Haben fast nur Kleinkram. Sind nordöstlich vom Merchant Market.}
{1111}{DECK_60}{Witzig. Er hält sich für den Anführer der Far Go Traders. Ist aber eigentlich eine Marionette. Der wagt es nicht, sich in meine Geschäfte einzumischen.}
{1112}{DECK_61}{Sie leitet den Waffenladen.}
{1113}{DECK_62}{Irgend etwas lässt die Caravans der Far Go Traders verschwinden. Ich wüsste gerne was, denn es stört auch meine Geschäfte.}
{1114}{Deck_63}{Er ist im Stadtzentrum.}
{1115}{DECK_64}{Fabeln und Märchen. Die Deathclaw ist wohl ein Geist oder so was.}
{1116}{DECK_65}{Old Town erstreckt sich über die Ostseite. Die Skags leben dort.}
{1117}{DECK_66}{Die meisten Händler leben dort. Richtung Westen.}
{1118}{DECK_67}{Eine lästige Organisation. Ich muss denen mal zeigen, wie man mit Macht umgeht.}
{1119}{DECK_68}{Morpheus ist der Chef der Children of the Cathedral. Er wohnt unten im Boneyard.}
{1120}{DECK_69}{Sie ist derzeit die Chefin der Children of the Cathedral im Hub. Ich habe Grund zur Annahme, dass sich das bald ändern wird.}
{1121}{DECK_70}{Eine der Erfindungen der Children. Ein kleiner, unwichtiger Gott oder so was.}
{1122}{DECK_71}{Ein kleiner Laden mit ganz guten Waffen, drüben bei den Far Go Traders.}
{1123}{DECK_72}{Zur Tür raus und dann nach Norden. Ganz einfach.}
{1124}{DECK_51}{Meine Mutter, die hinreißendste Frau überhaupt, hat mich auf die Idee für das größte Vergnügen im ganzen Hub gebracht.}
{1125}{DECK_51}{Meine Mutter, die hinreißendste Frau überhaupt, hat mich auf die Idee für das größte Vergnügen im ganzen Hub gebracht.}
{1126}{DECK_53}{Er ist der Polizeichef. Netter Kerl, wenn einem der aufrichtige, ehrliche Typ zusagt. Nicht wie sein Vater, der war uns immer treu.}
{1127}{DECK_56}{Chef der Water Merchants.}
{1128}{DECK_62}{Irgend etwas lässt die Caravans der Far Go Traders verschwinden. Ich wüsste gerne was, denn es stört auch meine Geschäfte.}
{1129}{DECK_58}{Er ist der Chef des Crimson Caravan.}
{1130}{DECK_59}{Sie sind die letzten Händler, und ich meine das wortwörtlich. Haben fast nur Kleinkram. Sind nordöstlich vom Merchant Market.}
{1131}{DECK_59}{Sie sind die letzten Händler, und ich meine das wortwörtlich. Haben fast nur Kleinkram. Sind nordöstlich vom Merchant Market.}
{1132}{DECK_60}{Witzig. Er hält sich für den Anführer der Far Go Traders. Ist aber eigentlich eine Marionette. Der wagt es nicht, sich in meine Geschäfte einzumischen.}
{1133}{DECK_64}{Fabeln und Märchen. Die Deathclaw ist wohl ein Geist oder so was.}
{1134}{DECK_64}{Fabeln und Märchen. Die Deathclaw ist wohl ein Geist oder so was.}
{1135}{DECK_65}{Old Town erstreckt sich über die Ostseite. Die Skags leben dort.}
{1136}{DECK_65}{Old Town erstreckt sich über die Ostseite. Die Skags leben dort.}
{1137}{DECK_67}{Eine lästige Organisation. Ich muss denen mal zeigen, wie man mit Macht umgeht.}
{1138}{DECK_72}{Zur Tür raus und dann nach Norden. Ganz einfach.}

