{100}{}{Du siehst eine von Deckers Wachen.}
{101}{}{Du mußt mit dem Boß reden.}
{102}{}{Stell dich besser gut mit uns.}
{103}{}{Wir werden dich im Auge behalten.}
{104}{}{Faß deine Waffen ja nicht an.}
{105}{}{Wenn du ihn schief ansiehst, bist du tot.}
{106}{}{Paß bloß auf!}
{107}{}{Ich ergebe mich!}
{108}{}{Ich hab' sowieso nie gerne für diesen Deckertyp gearbeitet.}
{109}{}{Jetzt, wo Decker und Kane weg sind, übernehm' ich den Laden!}
{110}{}{Von jetzt an paßt du im Hub besser auf. Ich werd' dich im Auge behalten.}
