{100}{}{Du siehst Demetre.}
{101}{}{Ja, hallo! Wie geht's so? Mein Name ist Demetre, Demetre Romara, Anführer des bei weitem besten Caravans im Ödland. Suchst du 'nen Job?}
{102}{}{Hmmm, siehst ja nicht besonders kräftig aus, aber ... du MUSST toll mit Gewehren umgehen können, wenn du da draußen überlebt hast! Wenn's drauf ankommt, bist du bestimmt 'n richtiger Kämpfer!}
{103}{}{Du siehst ganz fit aus.}
{104}{}{Du siehst recht kräftig aus.}
{105}{}{Mann, siehst du kräftig aus!}
{106}{}{Mann! Du siehst aus, als ob du Bäume ausreißen könntest!}
{107}{}{Ja und?}
{108}{}{Und? Was soll's?}
{109}{}{Häh?}
{110}{}{Genau das suchen wir! Im Kampfgetümmel fühlst du dich pudelwohl, stimmt's?! Überall pfeifen Kugeln um deinen Kopf, du zerfetzt deinen Feind, siehst die Angst in seinen Augen! Ahhhh, das ist Leben! Du schaust so aus, als ob du uns nützlich sein könntest, und wir zahlen gut! Oh ja, das tun wir! Wir haben gerade ein paar freie Stellen, du bist doch bestimmt interessiert, stimmt's?!}
{111}{}{Was ist mit der Kohle?}
{112}{}{Ich leg' alles um, was sich uns in den Weg stellt!}
{113}{}{Nein, danke.}
{114}{}{Ich brauche einen Steuerchip.}
{115}{}{Was weißt du über die verschwundenen Caravans?}
{116}{}{Ich muss los.}
{117}{}{Ugs ugs!}
{118}{}{Wir zahlen 600 Hub-Scheine pro Job! Garantiert! Man sagt von uns, dass wir immer den gefährlichen Weg gehen. Ich sage, dass das am aufregendsten ist! Man braucht doch 'n bisschen Aufregung im Leben, hab' ich recht? Natürlich hab' ich recht!}
{119}{}{Das ist doch genau das, was ich suche!}
{120}{}{Schreist du immer so rum?}
{121}{}{Gefährlich?}
{122}{}{Nein, danke, Bubi!}
{123}{}{Recht so! Sprich mit Keri nebenan, sie kann dir sagen, wann der nächste Caravan losfährt.}
{124}{}{Bubi? Was faselst du da? Na, macht jetzt auch nichts.}
{125}{}{Was? Hast du Angst vor lauten Geräuschen, oder was?}
{126}{}{Ja.}
{127}{}{Nur bei Nacht.}
{128}{}{Nein, ich würde bloß gerne wissen, ob du taub oder dumm bist.}
{129}{}{Nein, aber meine Ohren tun schon langsam weh.}
{130}{}{Ha! Vielleicht beides! Jetzt geh nebenan zu Keri, wenn du einen Job willst.}
{131}{}{Klugscheißer, was? Macht mir aber gar nichts aus! So lange du die Caravans verteidigst, bin ich zufrieden. Sprich jetzt mit Keri nebenan, wenn du einen Job willst.}
{132}{}{Ha! Der war gut! Wenn du dich im Dunkeln nicht fürchtest, komm doch mal zu mir.}
{133}{}{Natürlich ist es gefährlich. Warum würde ich sonst 600 Scheine löhnen?}
{134}{}{Oh, okay. Tschüss.}
{135}{}{Ich nehm' den Job doch.}
{136}{}{Hau ab, sonst passiert was!}
{137}{}{Ich blas' dir dein Licht aus!}
{138}{}{Das reicht!}
{139}{}{Aber klar doch! Sprich mit Keri nebenan, sie hat alle Pläne.}
{140}{}{Das ist enttäuschend, aber naja.}
{141}{}{He! Ich mag dich! Du hast den Job! Sprich mit Keri nebenan, sie teilt dich einem Caravan zu.}
{142}{}{Steuerchip? Hmmm, von denen hab' ich noch nie was gehört. Frag doch mal in einem der Läden draußen nach - die wissen alles mögliche. Wolltest du eigentlich einen Job?}
{143}{}{Was zahlt ihr denn so?}
{144}{}{Nee, eigentlich nicht.}
{145}{}{Nicht besonders viel, ich habe nur zwei verloren. Ich hab' nicht die geringste Ahnung, warum es die Far Go Traders mehr trifft als alle anderen.}
{146}{}{Irgendeinen Verdacht?}
{147}{}{Wie steht's mit euren Routen und der Ladung?}
{148}{}{Okay, danke.}
{149}{}{Wer das macht muss eine supergute Truppe haben. Unsere Caravans sind gut bewaffnet, und man sollte meinen, dass es mal jemanden entwischt. Sie hinterlassen keine Spuren.}
{150}{}{Wieviel gibt's also für den Job?}
{151}{}{Wie steht's mit euren Routen und der Ladung?}
{152}{}{Okay, danke.}
{153}{}{Also, wir fahren viel gefährlichere Routen, und unsere Ladung ist besser!}
{154}{}{Inwiefern ist eure Ladung besser?}
{155}{}{Wollte das nur prüfen, danke.}
{156}{}{Du bist doch nur Scheiße!}
{157}{}{Also gut, vielleicht ist sie nicht besser, aber wir liefern viele unterschiedliche Sachen.}
{158}{}{Okay, danke.}
{159}{}{Beth faselt die ganze Zeit von irgendeiner Deathclaw. Hak da doch mal nach! Ich habe auch von anderen gehört, dass nachts irgendwas im Nordwesten herumkriecht.}
{160}{}{Tut mir leid, aber wir kriegen gutes Geld, damit dieser Job erledigt wird! Wir nehmen nur die besten! Wir brauchen zuverlässige Männer und Frauen für diese Caravans!}
{161}{}{Als ob ich den Job gern hätte, du blöder Schreihals!}
{162}{}{Tut mir leid wegen der Belästigung.}
{163}{}{Kann ich bitte einen anderen Job haben?}
{164}{}{Häh?}
{165}{}{Ich sag' doch, wir nehmen dich nicht!}
{166}{}{Tut mir leid, ich will kein Risiko mit dir eingehen!}
{167}{}{Du vergeudest deine Zeit hier!}
{168}{}{Lass mich jetzt bitte in Ruhe!}
{169}{}{Hau ab.}
{170}{}{[Demetre ignoriert dich.]}
{171}{}{Zum Teufel, ich heuer' keine Typen wie dich an! Wenn du einen Job willst, musst du schon besser drauf sein!}
{172}{}{Ich bin ... gähn ... ups ... gut drauf!}
{173}{}{Blah!}
{174}{}{Du? Gut drauf? Haha! Nur gut, dass wir dich nicht mehr anheuern!}
{175}{}{Oh nein! Du schnallst wohl nicht, wieviel auf dem Spiel steht! Wir können kein Risiko eingehen! Keine Ahnung, warum die Far Go Traders immer noch im Geschäft sind, wo denen so viele Caravans fehlen!}
{176}{}{Tut mir leid ... Vielleicht gehen ja andere das Risiko ein und heuern dich an. Ich kann es mir nicht noch einmal leisten.}
{177}{}{Raus mit dir, du kotzt mich an!}
{178}{}{He! Was soll das werden?}
{179}{}{Da geht's zu unserem Lager.}
{180}{}{Die kann man nur von der anderen Seite öffnen.}
{181}{}{Du bist vielleicht seltsam.}
{182}{}{Ich habe keine Zeit für dich.}
{183}{}{[Er ignoriert dich.]}
{184}{}{Also? Willst du einen Job? Ich geb' dir die Riesenchance auf ein bisschen Spannung und viel Kohle! Von beidem kann man nie genug haben!}
{185}{}{Ja klar. Wie viel war das nochmal?}
{186}{}{Ich leg' alles um, was sich uns in den Weg stellt!}
{187}{}{Nein, danke.}
{188}{}{Ich brauche einen Steuerchip.}
{189}{}{Was weißt du über die verschwundenen Caravans?}
{190}{}{Ich muss los.}
{191}{}{Ruk? Luk?}
{192}{}{He, gute Arbeit mit dem letzten Caravan. Gut gemacht! Brauchst du irgendwas?}
{193}{}{Ja, ich wollte wieder einen Job.}
{194}{}{Ich brauche einen Steuerchip.}
{195}{}{Was weißt du über die verschwundenen Caravans?}
{196}{}{Nee. Wollte mich nur wieder mal blicken lassen.}
{197}{}{Nichts, tschüss.}
{198}{}{Wir haben unsere gesamte Ladung verloren! Wir können dich nicht mehr einstellen. Tut mir leid.}
{199}{}{Wir haben den Caravan fast verloren, von dem du abgehauen bist! Wir können dir keine Jobs mehr geben. Tut mir leid.}
{200}{}{Wir stellen niemanden ein, was willst du?}
{201}{}{Hau ab! Wir brauchen niemanden.}
{202}{}{Ich brauche einen Steuerchip.}
{203}{}{Erzähl mir, was du über die verschwundenen Caravans weißt.}
{204}{}{Ich will deine Visage nicht mehr sehen!}
{205}{}{Ich hätte gerne deinen Kopf!}
{206}{}{Schon gut.}
{207}{}{Ruk? Luk?}
{208}{}{Du hältst dich wohl für stark? Da muss ich aber lachen!}
{209}{}{Du solltest mal mit meiner Tochter Keri reden, sie kümmert sich um all das! Sie ist nebenan.}
{210}{}{Hab' ich dir doch schon gesagt. Rede mit Keri nebenan.}
{211}{}{Deine Tochter?}
{212}{}{Diese hässliche Schachtel ist deine Tochter? Jetzt wird mir einiges klar!}
{213}{}{Okay.}
{214}{}{Ja, mein ganzer Stolz! Ist sie nicht wunderschön? Rede mit ihr, wenn du noch einen Job willst. Eines Tages, hoffentlich bald, kann ich mich zurückziehen, und sie übernimmt alles.}
{215}{}{Nicht, wenn ihr beide tot seid!}
{216}{}{Okay, danke.}
{217}{}{Du wagst es, die Familie zu beleidigen? Ich mach' dich fertig!}
{218}{}{Tut mir  leid, war nur Spaß!}
{219}{}{Ich kann noch mehr als nur beleidigen!}
{220}{}{Zu spät! [Sein Gesicht wird sehr rot. Dann spricht er mit ruhiger, kontrollierter Stimme.] Hau ab, bevor ich meine Drohung in die Tat umsetze!}
{221}{}{Das soll eine Drohung sein?}
{222}{}{Keine Drohung! Du stirbst gleich!}
{223}{}{Naja, ich wollt' es halt mal probieren!}
{224}{}{Nein, tut mir leid. Ich muss los. Tschüss!}
{225}{}{Da hab' ich aber schon Besseres gehört.}
{226}{}{Ja, ich weiß. Bis die Tage.}
{227}{}{Trotzdem wirst du sterben!}
{228}{}{Äh, okay.}
{229}{}{Auf was wartest du? Jemand muss sich um die Caravans kümmern!}
{230}{}{Die sind noch nicht abfahrtbereit.}
{231}{}{Erst muss ich noch was erledigen.}
{232}{}{Ich brauche einen Steuerchip.}
{233}{}{Erzähl mir, was du über die verschwundenen Caravans weißt.}
{234}{}{Okay, tschüss.}
{235}{}{Rik? Rok?}
{236}{}{Hääh?}
{237}{}{Verflixt! Da verpasst du was! Ich bin sicher, es gibt 'ne Menge Menschen, Kreaturen, Sachen, die darauf warten, die Caravans anzugreifen! Es geht nichts über einen guten Kampf! Da ... Jetzt hast du was zum Spielen, bis der nächste Caravan abfahrtbereit ist. [Er gibt dir eine Splittergranate.]}
{238}{}{Verflucht! Fahren unsere Caravans denn nie ab?}
{239}{}{Was ist los?}
{240}{}{Komm nicht zu spät.}
{241}{}{Keri, sind wir schon voll?}
{242}{}{Du musst den Feind töten, bevor er dich kriegt!}
{243}{}{Es gibt nichts Schöneres, als einen Feind alle zu machen!}
{244}{}{Nein, wirst du nicht!}
{245}{}{Verdammt, wo ist meine Kanone!}
