{100}{}{Der Stromgenerator wurde manipuliert. Er funktioniert nicht mehr.}
{101}{}{Du siehst einen Stromgenerator. Er ist die einzige Stromquelle in Scrapheap.}
{102}{}{Du kappst einige Drähte am Transformator. Der Stromgenerator funktioniert nicht mehr.}
{103}{}{Die Zange brauchst du nicht mehr.}
{104}{}{Dieser Gegenstand ist am Generator nutzlos.}
{105}{}{Du siehst nichts besonderes am Generator.}
{106}{}{Der Generator scheint gegen Eingriffe ganz gut gesichert, doch du bemerkst mehrere Drähte zwischen dem Transformator und dem Generator.}
{107}{}{An diesem großen Generator fällt dir nichts besonderes auf.}
{108}{}{Du kannst nichts weiter am Generator entdecken.}
{109}{}{Die Drähte könnten gerichtet werden, doch das dauert ein bißchen, und es ist nicht sicher, ob er dann funktioniert.}
{110}{}{An dem beschädigten Generator fällt dir nichts besonderes auf.}
{111}{}{Weitere Reparaturen sind nicht möglich.}
{112}{}{Der Stromgenerator muß nicht repariert werden. Er funktioniert ausgezeichnet.}
{113}{}{Du kannst den funktionierenden Generator nicht reparieren.}
{114}{}{Es dauert zwar einige Stunden, aber du reparierst den Stromgenerator. Strom ist wieder da, die Gangs sind weg, die Stadtbewohner sind dankbar. Sie geben dir wertvolle Informationen. Deine Aufgabe in Scrapheap ist erfüllt. Die Mission, den Steuerchip zu finden, muß noch erledigt werden.}
{115}{}{Du kannst den Generator nicht reparieren. Die Bewohner von Scrapheap leben zwar ohne Strom schlechter, doch da die Gangs weg sind, leben sie wenigstens. Deine Aufgabe in Scrapheap ist erfüllt. Die Mission, den Steuerchip zu finden, muß noch erledigt werden.}
{116}{}{Weiteres Basteln am Generator führt zu nichts.}
{117}{}{Diese Fähigkeit hat keine Wirkung auf den Generator.}
{118}{}{Der Generator läuft schon.}
{119}{}{Du bringst den Generator nicht in Gang, er ist kaputt.}
