{100}{}{Du schaffst es, den Kühlschrank aufzuschließen.}
{101}{}{Du hast Probleme mit diesem Schloss.}
{102}{}{Du siehst einen Kühlschrank. Er ist geschlossen und verriegelt.}
{103}{}{Du siehst einen Kühlschrank. Er ist offen.}
{104}{}{Du siehst einen Kühlschrank. Er ist geschlossen.}
{105}{}{Die Tür ist verschlossen.}
{106}{}{You see a refrigerator.}
{107}{}{It is already unlocked.}
{108}{}{That does nothing.}

