{100}{}{Du siehst einen Narren.}
{101}{}{Du siehst ein Bandenmitglied.}
{102}{}{Man nennt uns Narren, aber du bist einfach nur dumm, hier aufzutauchen.}
{103}{}{Willst du dich mit uns anlegen?}
{104}{}{Das hier ist nichts für dich.}
{105}{}{Glaub' nicht, daß du hier reinspazieren und Rabbatz machen kannst.}
{106}{}{Paß' auf, oder du kommst ins Grab, Gruftie.}
{107}{}{Klar, wir kümmern uns um die Gruftie.}
{108}{}{Scrapheap wird ohne die Grufties nicht mehr das gleiche sein. Es gehört dann uns!}
{109}{}{Ha ha ha! Ha ha ha ha!}
{110}{}{Narren! Narren! Narren! Yeah!}
{111}{}{Kennste den mit dem Hühnchen und dem Fuchsbau?}
{112}{}{Bleib cool.}
{113}{}{Wer zuletzt lacht, lacht zuletzt.}
{114}{}{Das Leben ist ein Witz, scheiß' drauf.} 
{115}{}{Wenn's die Grufties nicht gäbe, hätten wir hier das Sagen. Oder könnten zumindest Lenny in die wohin treten.}
{116}{}{Sei ein Narr.}
{117}{}{Glaubst du, das lachhafte Ding rettet dich vor Baka?}
{118}{}{Was ist los? Bist du bei deiner Geburt auf den Kopf gefallen?}
{119}{}{Wenn ich so häßlich wäre, würde ich mich umbringen.}
{120}{}{Ihr Grufties schaut aus, als ob ihr gerade vom Friedhof kommt.}
{121}{}{Nur ein Narr würde so was dummes tun. He, halt, ich bin doch ein Narr.}
