{100}{}{Du siehst einen umherwandernden Händler asiatischer Abstammung.}
{101}{}{Du siehst Duc, den umherwandernden Händler.}
{102}{}{Ah, hallo, Wanderer. Ich heiße Duc, und ich bin auf dem Weg nach Shady Sands,
 um dort Handel zu treiben. Vielleicht kann ich dir meine Waren zeigen?}
{103}{}{Was verkaufst du?}
{104}{}{Gehst du oft nach Shady Sands?}
{105}{}{Erf!}
{106}{}{Ich zeig' dir was.}
{107}{}{Ja, Shady Sands liegt auf der Handelsroute, die ich gewöhnlich entlangwandere. Wenn du magst, kannst du mit uns reisen, das ist sicherer.}
{108}{}{Oh ja, hört sich gut an.}
{109}{}{Nein danke.}
{110}{}{Oh, 'tschuldigung - hab' gar nicht bemerkt, daß du so blöd bist.}
{111}{}{Es sollte nur einen Tag oder so dauern. Gehen wir!}
{112}{}{ShadyW.Karte}
{113}{}{Nur wenige Menschen trauen sich allein in das Ödland. Wer bist du?}
{114}{}{Geht dich nichts an.}
{115}{}{Ich bin }
{116}{}{.}

{117}{}{Ich }
{132}{}{!}


{118}{}{Hallo, du wieder! Wie kann ich dir helfen?}
{119}{}{Kann ich mich eurer Gruppe nach Shady Sands anschließen?}
{120}{}{Was verkaufst du?}
{121}{}{Nichts, danke.}
{122}{}{Was willst du?}
{123}{}{Nichts, 'tschuldigung.}
{124}{}{Was verkaufst du?}
{125}{}{Erf!}
{126}{}{Paß' gut auf, wenn du alleine unterwegs bist.
 Seit kurzem werden ein paar Leute in Shady Sands vermißt.}
{127}{}{Hey, ich hab' gehört, daß du diese Frau von Shady Sands gerettet hast. Gut gemacht.}
 
{128}{}{Oh, tut mir leid. Ich wusste nicht, dass du ein Idiot bist.}
{129}{}{Danke. Bis dann.}
{130}{}{Rumph!}
{131}{}{Erf!}
