{100}{}{Du siehst einen Bauern.}
{101}{}{Hallo Fremder. Gefallen dir meine Felder?}
{102}{}{Guten Morgen!}
{103}{}{Guten Tag!}
{104}{}{Abend, Freund!}
{105}{}{Schöner Tag heute, nicht wahr?}
{106}{}{Dieser Boden ist viel gesünder als er aussieht.}
{107}{}{Ich versuche, diese Bäume zu retten, und ich glaube, es funktioniert.}
{108}{}{Ich glaube, es gibt da einen Caravan mit Dünger. Hier hast du ein bißchen Geld.}
{109}{}{Komm' rein, hier ist viel Platz.}
{110}{}{Da draußen ist es ein bißchen kühl. Setz' dich.}
{111}{}{Die Landwirtschaft gefällt mir.}
{112}{}{Hast du gewußt, daß Pflanzen besser gedeihen, wenn man nett zu ihnen ist?}
{113}{}{Ich wünschte, ich hätte ein bißchen mehr Land.}
{114}{}{Hast du gewußt, daß es mal so was wie große Behälter mit Trinkwasser gegeben hat?}
{115}{}{Ich hab' von Flüssen gehört. Ich hätte gerne einen in der Nähe meiner Felder.}
{116}{}{Wenn die Tage nur länger wären, ich hab' so viel zu tun.}
