{100}{}{Du siehst einen zwielichtig aussehenden Mexikaner mit geschniegeltem Haar.}
{101}{}{Du siehst Hernandez, den schurkenhaften Spieler.}
{102}{}{Oye, Muchacho, erlaub' mir, daß ich mich dir vorstelle. Ich bin Hernandez,
 ein Mann mit mucho Gusto! Du siehst aus als wärst du neu hier. Bitte,
 erlaube mir, daß ich dich über das Kasino informiere.}
{103}{}{Kannst du mir etwas über das Kasino erzählen?}
{104}{}{Nein, danke.}
{105}{}{Bluh?}
{106}{}{Aber natürlich! Diese hochklassige Einrichtung steht unter der Leitung des berühmten Gizmo. Ein echter Visionär und ein sehr reicher Mann.}
{107}{}{Danke.}
{108}{}{Du sagst, Gizmo sei ein Visionär. Was für eine Vision hat er denn?}
{109}{}{Wie stehen denn die Chancen, daß man bei den Spielen hier gewinnt?}
{110}{}{Mein Freund, ich will mich ja nicht aufdrängen, aber vielleicht kannst du mir helfen.
 Ich habe ein todsicheres System entwickelt, ich habe nämlich herausgefunden, was Gizmo
 mit seinen Spieltischen macht, aber ich habe zum Spielen nicht genug Deckel.}
{111}{}{ [Du hast den Eindruck, daß er versucht, dich über den Tisch zu ziehen.]}
{112}{}{Vielleicht kannst du mir ja ein paar Deckel geben? Ich garantiere dir, daß ich Erfolg haben werde.}
{113}{}{Klar, hört sich gut an.}
{114}{}{Nein, danke.}
{115}{}{Ich glaube, du lügst. Du versuchst doch, mich über den Tisch zu ziehen.}
{116}{}{Tut mir leid, mi Amigo. Komm', ich zeig' dir mal ein Spiel. . .}
{117}{}{Vielen Dank, mi Amigo! In ein paar Tagen geb' ich dir dein Geld zurück,
 und zwar mit Zinsen. Weißt du, mein System ist langsam, man braucht viel Geduld, aber es bringt ganz sicher große Gewinne ein!}
{118}{}{Ist ja schön und gut, aber ich garantiere, daß ich Erfolg haben werde! Wenn du durch Warten reich werden willst, dann komm' bald wieder, oder ich such' mir einen anderen Partner!}
{119}{}{Mein Freund, wie ich sehe, bist auch du ein Mann mit viel Geschmack. Wie wär's mit einem kleinen Würfelspiel?}
{120}{}{In Ordnung!}
{121}{}{Nein danke, ich würde lieber etwas anderes ausprobieren.}
{122}{}{Es war Gizmos Traum, etwas aufzubauen, wo die Leute sich treffen und Spaß haben können. Das war sein Ehrgeiz. Das Ergebnis ist das Kasino hier.}
{123}{}{Er gibt den Leuten hier die Möglichkeit, ihre Sorgen in der kaputten Welt zu
 lassen und hier Spaß zu haben. Und er bringt Geld nach Junktown!}
{124}{}{Hört sich gut an.}
{125}{}{Das Leben ist schon schlimm genug. Ich traue keinem, der Menschen dazu ermutigt, ihr Geld zu verlieren.}
{126}{}{Offensichtlich bist du nicht so brillant wie Gizmo. Hier können sich Menschen
 von der Härte des Alltags erholen.}
{127}{}{Gizmo hat ein echt gutes Haus, obwohl die Spiele, nun, äh, wie soll ich sagen,
 zugunsten das Hauses leicht manipuliert sind.
 Es ist aber nicht so, daß seine Leute betrügen. Wenn du jedoch kein System hast, wie ich eins habe, mußt du extrem clever sein.}
{128}{}{Danke.}
{129}{}{}
{130}{}{Und, wie läuft's denn mit deinem System?}
{131}{}{Nichts, danke.}
{132}{}{Mein System geht nur langsam voran. Ich hab' ja auch Lebenshaltungskosten und so, du weißt schon, aber es funktioniert!}
{133}{}{Das ist ja großartig!}
{134}{}{Du bist doch ein Lügner und Betrüger. Wo ist mein Geld?}
{135}{}{Du denkst also, du hast's kapiert, hä? Also, von mir kriegst du überhaupt nichts!}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{136}{}{Buenos Dias, mein Freund! Was kann ich heute für dich tun?}
{137}{}{Buenos Dias, meine Liebe! Was kann ich heute für dich tun?}