{100}{}{Du schließt die Tür auf.}
{101}{}{Du verstopfst aus Versehen das Türschloß.}
{102}{}{Du kannst dieses Schloß nicht öffnen.}
{103}{}{Du konntest das Schloß nicht öffnen.}
{104}{}{Die Tür ist verschlossen.}
{105}{}{Die Tür ist unverschlossen.}
