{100}{}{Du siehst einen Sänger der Children.}
{101}{}{Der Meister wird dir deine Sünden vergeben! Schließ dich uns an und sei frei. Gelobt sei der Meister und seine Gnade!}
{102}{}{Hallo, mein Freund! Willst du ein Loblied mit mir anstimmen? ... Einst wanderte ich blind umher, in einem Land so kalt und leer ...}
{103}{}{Ich unterbrech' dein Loblied nur ungern, aber wo kann ich den Meister finden?}
{104}{}{Du solltest deinen eigentlichen Job auf jeden Fall behalten!}
{105}{}{Wer ist hier zuständig?}
{106}{}{... doch nun küss' ich des Meisters Hinterteil ...}
{107}{}{Freude! Freude! Ich bin ein guter Sänger!}
{108}{}{Er findet dich, wann und wo du es am wenigsten erwartest. Gelobt sei der Meister! Gelobt sei die Heilige Flamme! Gelobt sei die Welt!}
{109}{}{Was für ein toller Witz! Früher hatte ich keinen Sinn für Humor, aber dank des Meisters bin ich wieder voller Freude. Gelobt sei der Meister!}
{110}{}{Er wacht von oben und unten und ist unter uns. Gelobt sei der Meister für diesen Weitblick!}
{111}{}{Oh, wenn ich doch auch so viel Glück hätte! Vielleicht kommt der Tag, an dem ich den Meister küssen darf. Gelobt sei der Meister! Gelobt sei die Heilige Flamme!}
{112}{}{Hmm, das hatt' ich mir anders vorgestellt. Du solltest noch ein bisschen üben, mein Freund. Gelobt sei der Meister! Gelobt sei die Heilige Flamme!}
{113}{}{[OK]}
