{100}{}{Du siehst eine Holo-CD vor dir.}
{101}{}{PipBoy-Anzeige: Daten werden von der CD heruntergeladen.}
{102}{}{Auf dieser CD befinden sich anscheinend Unterhaltungsprogramme.}
{103}{}{Die CD ist zu stark beschädigt, um die Daten lesen zu können.}
{104}{}{Diese CD enthält offensichtlich einen Verweis auf einen Sicherheitscode auf einer anderen CD.}
{105}{}{Ein kleines Anzeigefenster öffnet sich, in dem Ausschnitte aus einem Film über den Zweiten Weltkrieg erscheinen.}
{106}{}{Die CD ist anscheinend leer.}
{107}{}{Du wirfst diese nutzlose CD weg.}
