# Player gains [x] of experience points
// In Fo2 it is "You gain " ... in Fo1 it is "You earn "
{10}{}{Du erhältst }

// In Fo2 it is " experience points." ... in Fo1 it is " experience."
{11}{}{ Erfahrungspunkte.}

{100}{}{Was willst du?}
{101}{}{Laß mich in Ruhe!}
{102}{}{Was?}
{103}{}{Faß meine Sachen nicht an!}
{104}{}{Hallo!}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Uungh.}
{108}{}{Uhh.}
{109}{}{He, hast du schon gehört, daß Set tot ist?}

{110}{}{Set ist tot. Set ist tot. Set ist tot ...}
{111}{}{Es ist genug Wasser für alle da. Dafür hat Set gesorgt.}
{112}{}{Ich hab' gehört, daß die Mutanten aus der Stadt vertrieben wurden.}
{113}{}{Seit die Mutanten weg sind, ist alles besser.}
{114}{}{Hallo!}

{200}{}{Du untersuchst das bedauernswerte Geschöpf, kannst aber nicht
 herausfinden, was es zu dem gemacht hat, was es jetzt ist.}
{201}{}{Es scheint einmal ein Mensch gewesen zu sein oder zumindest vom Menschen abzustammen. Du vermutest, daß der schlechte Zustand des Körpers auf Säure oder Strahlung zurückzuführen ist.}
{202}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt, aber dennoch funktionsfähig zu sein. Auch wenn es einmal ein Mensch gewesen ist, scheint es doch eher wie ein Tier gelebt zu haben.}
{203}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt und der Großteil der Muskel- und Hirnmasse zerstört zu sein. Genetische Merkmale sprechen deiner Meinung nach dafür, daß es wie du von Vaultbewohnern abstammt.}

{204}{}{Nein danke.}
{205}{}{Nein danke.}
{206}{}{Sicher.}
{207}{}{Ja.}
{208}{}{Nein.}
{209}{}{OK.}

#############################################################
#  The following lines are generic noises that the player   #
#  makes when he/she has a low i.q. level.                  #
#############################################################
{300}{}{Ug.}
{301}{}{Og.}
{302}{}{Uga.}
{303}{}{Urg.}

#############################################################
#  The following lines are generic non-spoken dialogs       #
#############################################################
{350}{}{[ENDE]}
{351}{}{[TSCHÜß]}
{352}{}{[MEHR]}
{353}{}{[FORTFAHREN]}
{354}{}{[KAMPF]}
{355}{}{[GELD]}

#############################################################
#  The following lines are generic departure dialogs        #
#############################################################
{375}{}{Tschüß.}
{376}{}{Wiedersehn.}

#############################################################
#  The following lines are for special events in the        #
#  dude_obj                                                 #
#############################################################
{450}{}{Die Luft ist rein. Los, raus!}

#############################################################
#  The following lines are for miscellaneous things needed    #
#  throughout the game.                                     #
#############################################################

{900}{}{Die alte, klapprige Tür sieht so aus, als könnte man sie mit einer richtig plazierten Sprengladung zerstören.}

{905}{}{Wuff! Wuff!}

{910}{}{Du erhältst einen Schock durch den elektrisch geladenen Boden.}
{911}{}{ erhält einen Schock durch den elektrisch geladenen Boden.}
{912}{}{Die Spannung fällt auf Null und steigt anschließend auf 50%, sobald die Sicherungsgeneratoren wieder aktiv werden.}
{913}{}{Ein leises Summen ist zu hören, als der Strom wieder durch die Basis fließt.}

{930}{}{Heuuuuul!}

{950}{}{Du nimmst dir ein wenig Zeit, um ein paar Bewegungen zu üben. Deine Fähigkeiten für den unbewaffneten Kampf nehmen um 5% zu.}

{951}{}{Die kämpfende Maulwurfsratte bekommt ihren Todesstoß versetzt.}
{952}{}{Der Kampf ist vorbei.}

{953}{}{You take some time out to practice some moves.}
{954}{}{You put your night vision goggles on.}
{955}{}{You take your night vision goggles off.}
{956}{}{You learn nothing new.}
{957}{}{You learn a lot about handling heavy weapons.}
{958}{}{You learn a lot about handling energy weapons.}
{959}{}{You learn a lot about medical techniques.}
{960}{}{You learn a lot about picking locks.}
{961}{}{You learn a lot about science and technology.}
{962}{}{You learn a lot about explosives and booby-traps.}
{963}{}{Your communication skills improve.}
{964}{}{You learn a lot about trading.}
{965}{}{You lack the intelligence needed to understand this book.}
{966}{}{This book is a bit too advanced for your current knowledge of this subject.}
{967}{}{You gain new abilities through persistent study.}
{968}{}{Your vocabulary improves.}
{969}{}{Your eloquence improves.}
{970}{}{You learn a lot about outdoor survival.}
{971}{}{You learn a lot about advanced electronics.}

#############################################################
#  Quest Information. Mainly used for solving quests        #
#############################################################

{1003}{}{Du deaktivierst die Kraftfelder.}
{1004}{}{Du hackst in den Computer.}
{1012}{}{WARNUNG! Völlige Reaktor-KERNSCHMELZE!}
{1013}{}{WARNUNG! GIFTSTOFFE in Belüftungskanäle freigesetzt.}

{1050}{}{Du zerreibst das Skorpiongift zu einem Gegengift.}

#############################################################
#  These are for converting numeric values to number words. #
#  You want it to go further, add 'em yourself.             #
#############################################################
{2000}{}{null}
{2001}{}{eins}
{2002}{}{zwei}
{2003}{}{drei}
{2004}{}{vier}
{2005}{}{fünf}
{2006}{}{sechs}
{2007}{}{sieben}
{2008}{}{acht}
{2009}{}{neun}
{2010}{}{zehn}
{2011}{}{elf}
{2012}{}{zwölf}
{2013}{}{dreizehn}
{2014}{}{vierzehn}
{2015}{}{fünfzehn}
{2016}{}{sechzehn}
{2017}{}{siebzehn}
{2018}{}{achtzehn}
{2019}{}{neunzehn}
{21020}{}{zwanzig}
{2021}{}{einundzwanzig}
{2022}{}{zweiundzwanzig}
{2023}{}{dreiundzwanzig}
{2024}{}{vierundzwanzig}
{2025}{}{fünfundzwanzig}
{2026}{}{sechsundzwanzig}
{2027}{}{siebenundzwanzig}
{2028}{}{achtundzwanzig}
{2029}{}{neunundzwanzig}
{2030}{}{dreißig}
{2031}{}{einunddreißig}
{2032}{}{zweiunddreißig}
{2033}{}{dreiunddreißig}
{2034}{}{vierunddreißig}
{2035}{}{fünfunddreißig}
{2036}{}{sechsunddreißig}
{2037}{}{siebenunddreißig}
{2038}{}{achtunddreißig}
{2039}{}{neununddreißig}
{2040}{}{vierzig}
{2041}{}{einundvierzig}
{2042}{}{zweiundvierzig}
{2043}{}{dreiundvierzig}
{2044}{}{vierundvierzig}
{2045}{}{fünfundvierzig}
{2046}{}{sechsundvierzig}
{2047}{}{siebenundvierzig}
{2048}{}{achtundvierzig}
{2049}{}{neunundvierzig}
{2050}{}{fünfzig}
{2051}{}{einundfünfzig}
{2052}{}{zweiundfünfzig}
{2053}{}{dreiundfünfzig}
{2054}{}{vierundfünfzig}
{2055}{}{fünfundfünfzig}
{2056}{}{sechsundfünfzig}
{2057}{}{siebenundfünfzig}
{2058}{}{achtundfünfzig}
{2059}{}{neunundfünfzig}
{2060}{}{sechzig}
{2061}{}{einundsechzig}
{2062}{}{zweiundsechzig}
{2063}{}{dreiundsechzig}
{2064}{}{vierundsechzig}
{2065}{}{fünfundsechzig}
{2066}{}{sechsundsechzig}
{2067}{}{siebenundsechzig}
{2068}{}{achtundsechzig}
{2069}{}{neunundsechzig}
{2070}{}{siebzig}
{2071}{}{einundsiebzig}
{2072}{}{zweiundsiebzig}
{2073}{}{dreiundsiebzig}
{2074}{}{vierundsiebzig}
{2075}{}{fünfundsiebzig}
{2076}{}{sechsundsiebzig}
{2077}{}{siebenundsiebzig}
{2078}{}{achtundsiebzig}
{2079}{}{neunundsiebzig}
{2080}{}{achtzig}
{2081}{}{einundachtzig}
{2082}{}{zweiundachtzig}
{2083}{}{dreiundachtzig}
{2084}{}{vierundachtzig}
{2085}{}{fünfundachtzig}
{2086}{}{sechsundachtzig}
{2087}{}{siebenundachtzig}
{2088}{}{achtundachtzig}
{2089}{}{neunundachtzig}
{2090}{}{neunzig}
{2091}{}{einundneunzig}
{2092}{}{zweiundneunzig}
{2093}{}{dreiundneunzig}
{2094}{}{vierundneunzig}
{2095}{}{fünfundneunzig}
{2096}{}{sechsundneunzig}
{2097}{}{siebenundneunzig}
{2098}{}{achtundneunzig}
{2099}{}{neunundneunzig}
{2100}{}{einhundert}

#############################################################
#  These are generic Reactions to the player's actions in   #
#  the game to other NPC's. NPC's float these lines.        #
#############################################################

######
#  Caught Pickpocketing (Warning)  (3000-3299)
######

# Tough Guard (3000-3024)
{3000}{}{}

# Guard (3025-3049)
{3025}{}{}

# Tough Citizen (3050-3074)
{3050}{}{Wenn du das noch mal versuchst, muß ich dich töten.}
{3051}{}{Bei mir ist nichts zu holen, du Idiot.}
{3052}{}{*So* gut kennen wir uns nun auch wieder nicht.}
{3053}{}{Faß das noch einmal an und du wirst es bereuen.}
{3054}{}{Nimm deine Hände weg!}
{3055}{}{Wenn du das noch mal machst, bist du einen Kopf kürzer.}
{3056}{}{Hände weg!}
{3057}{}{Willst du Ärger?}
{3058}{}{Wenn du mich noch einmal anfaßt, bist du tot.}
{3059}{}{Nur Ärger gibt's umsonst.}
{3060}{}{He! Hau ab.}
{3061}{}{Paß auf!}
{3062}{}{Bist du lebensmüde?}
{3063}{}{Versuch das noch mal und ich verpaß dir eine.}
{3064}{}{Das gehört mir, Hände weg!}

# Citizen (3075-3099)
{3075}{}{}

# Custom (3100-3299)
{3100}{}{ has joined party}
{3101}{}{ has left party}

######
#  Caught Stealing from Something (Warning)   (3300-3599)
######

# Tough Guard (3300-3324)
{3300}{}{}

# Guard (3325-3349)
{3325}{}{Warum legst du nicht alles an seinen Platz zurück?}
{3326}{}{Du weißt doch, man soll sich nicht an Dingen anderer vergreifen.}
{3327}{}{Weg da, Niete!}
{3328}{}{Jetzt erzähl mir nicht, du "suchst nur deine Schlüssel". Mach daß du hier raus kommst!}
{3329}{}{Was immer du suchst, es ist nicht hier, verstanden?}

# Tough Citizen (3350-3374)
{3350}{}{}

# Citizen (3375-3399)
{3375}{}{}

# Custom (3400-3599)
{3400}{}{Cpt. Corpse's Cheating Tool.}
{3401}{}{Add to party: Adds target object to your party.  Valid targets: critters and items. (don't use on player)}
{3402}{}{Remove from party: Removes target object from party. (don't use on player)}
{3403}{}{Give armor and wield: Create a suit of Adv Power Armor MkII on target and wear. (Player and NPCs only)}
{3404}{}{Remove armor: Removes targets armor from armor slot}
{3405}{}{Set Max HP to 250 (does not work)}
{3406}{}{Create Resistance Booster Drugs (Needs Add-On Patch to work)}
{3407}{}{ to wield this item?}
{3408}{}{Remove Weapon: Causes an NPC to put away his/her weapon}
{3409}{}{Change NPCs appearance}
{3410}{}{Destroy Scenery or Wall: Good for clearing paths}
{3411}{}{Give Experience}
{3412}{}{Push target NPC}
{3413}{}{Give Money}
{3414}{}{Create Item: Creates an specific item on target}
{3415}{}{Heal Player or NPC: Also heals crippled limbs}
{3416}{}{Change NPC Stats}
{3417}{}{Select Category}
{3418}{}{Basic Stats}
{3419}{}{Strength}
{3420}{}{Perception}
{3421}{}{Endurance}
{3422}{}{Charisma}
{3423}{}{Intelligence}
{3424}{}{Agility}
{3425}{}{Luck}
{3426}{}{Hit Points}
{3427}{}{Action Points}
{3428}{}{Melee Damage}
{3429}{}{Carry Amount}
{3430}{}{Sequence}
{3431}{}{Healing Rate}
{3432}{}{Critical Chance}
{3433}{}{Better Criticals}
{3434}{}{Age}
{3435}{}{Gender}
{3436}{}{PC Stats}
{3437}{}{Skill Points}
{3438}{}{Reputation}
{3439}{}{Karma}
{3499}{}{Team Number Set}
{3500}{}{Team Number: }
{3501}{}{Quantity}
{3502}{}{+1}
{3503}{}{+10}
{3504}{}{+100}
{3505}{}{-1}
{3506}{}{-10}
{3507}{}{-100}
{3508}{}{+1000}
{3509}{}{+10000}
{3510}{}{+100000}
{3511}{}{Boxes (2)}
{3512}{}{Boxes (1)}
{3513}{}{Fridge}
{3514}{}{Ice Chest}
{3515}{}{Ammo Crate (Big)}
{3516}{}{Order }
{3517}{}{Wagon(Red)}
{3518}{}{Wagon(White)}
{3519}{}{Floor Safe}
{3520}{}{Chest}
{3521}{}{Give Item}

######
#  Caught Lockpicking Door (Warning)   (3600-3899)
######

# Tough Guard (3600-3624)
{3600}{}{}

# Guard (3625-3649)
{3625}{}{Hey, you! What're you poking around that for?}
{3626}{}{If you ain't got a key in your hand, you'd better be stepping away.}
{3627}{}{It's locked for a reason, punk.}
{3628}{}{Knock it off before there's trouble!}

# Tough Citizen (3650-3674)
{3650}{}{}

# Citizen (3675-3699)
{3675}{}{}

# FRM function (3700-3899)
{3700}{}{Change target FRM}
{3701}{}{Power Armor}
{3702}{}{Purple Robes}
{3703}{}{Combat Armor (F)}
{3704}{}{V13 Suit(F)}
{3705}{}{Leather Armor (F)}
{3706}{}{Mad Maxx (F)}
{3707}{}{Metal Armor (F)}
{3708}{}{V13 Suit(MB)}
{3709}{}{Metal Armor (MB)}
{3710}{}{Combat Armor (M)}
{3711}{}{V13 Suit (M)}
{3712}{}{Leather Armor (M)}
{3713}{}{Mad Maxx (M)}
{3714}{}{Metal Armor (M)}
{3715}{}{Brahmin}
{3716}{}{Dog}
{3717}{}{Mr Handy}
{3718}{}{Lt Lou (Needs patch by ColJack)}
{3719}{}{Mole Rat}
{3720}{}{Black Leather (SM)}
{3721}{}{Green Mutant}
{3722}{}{Big Radscorpion}
{3723}{}{Floater}
{3724}{}{Rat}
{3725}{}{Centaur}
{3726}{}{Blue Robe}
{3727}{}{Child}
{3728}{}{Green Ghoul}
{3729}{}{Glowing One}
{3730}{}{Power Armor (No Helmet)}
{3731}{}{Monk}
{3732}{}{Blonde}
{3733}{}{Punk}
{3734}{}{Metal Armor (F Yellow Pants)}
{3735}{}{Tandi}
{3736}{}{Slut}
{3737}{}{V13 Suit (F Red Head)}
{3738}{}{Black peasant (Red Shirt)}
{3739}{}{Peasant (Yellow Shirt)}
{3740}{}{Bald Peasant (Green Shirt)}
{3741}{}{Red Haired Midget}
{3742}{}{Loser}
{3743}{}{Leather Armor (M Bald)}
{3744}{}{Leather Jacket (Long Haired Lout)}
{3745}{}{Peasant (Blue Cap)}
{3746}{}{Mature Deathclaw}
{3747}{}{Mantis}
{3748}{}{Robobrain}
{3749}{}{Floating Eye}
{3750}{}{Pig Rat}
{3751}{}{Brown Robes}
{3752}{}{Bald Doctor}
{3753}{}{Egg}
{3754}{}{Small Radscorpion}
{3755}{}{Small Deathclaw}
{3761}{}{Sentry Robot}
{3764}{}{Citizen Male}
{3769}{}{Citizen Female}
{3774}{}{Neutral Ghoul}
{3778}{}{Vault Suit (F Black)}
{3779}{}{Black Robes}
{3782}{}{Cop}
{3784}{}{Technician}
{3798}{}{[END]}
{3799}{}{ }
{3800}{}{[BACK]}
{3801}{}{[BACK TO MAIN]}
{3802}{}{[EXIT]}
{3803}{}{Input item PID (4 digit format:0000) }
{3804}{}{First Number (1000)}
{3805}{}{Second Number (100)}
{3806}{}{Third Number   (10)}
{3807}{}{Fourth Number   (1)}
{3808}{}{PID: }
{3809}{}{Item Name: }
{3810}{}{Invalid Target Object}

######
#  Caught Sneaking (Warning)    (3900-4199)
######

# Tough Guard (3900-3925)
{3900}{}{}

# Guard (3925-3949)
{3925}{}{Hey you! What're you doing there?}
{3926}{}{You're not supposed to be here!}
{3927}{}{If you think you're just walking by me, you can forget that!}
{3928}{}{You better not be planning what I think you're planning, stranger.}
{3929}{}{What? Like you think I don't notice you? Get outta here!}

# Tough Citizen (3950-3974)
{3950}{}{}

# Citizen (3975-3999)
{3975}{}{}

# Custom (4000-4199)
{4000}{}{Check damage resistances and thresholds.}
{4001}{}{%}
{4002}{}{ has been healed.}
{4003}{}{The crippled left leg has healed.}
{4004}{}{The crippled right leg has healed.}
{4005}{}{The crippled left arm has healed.}
{4006}{}{The crippled right arm has healed.}
{4007}{}{The damaged eye has healed.}
{4008}{}{ is not injured.}
{4010}{}{THRESHOLDS AND RESISTANCES:}
{4011}{}{/}
{4012}{}{--}
{4100}{}{Normal:     }
{4101}{}{Laser:      }
{4102}{}{Fire:       }
{4103}{}{Plasma:     }
{4104}{}{Electrical: }
{4105}{}{EMP:        }
{4106}{}{Explode:    }
{4107}{}{Radiation:  }
{4108}{}{Poison:     }
{4109}{}{ looks healthy.}

######
#  Being Attacked by the player (Warning)    (4200-4499)
######

# Tough Guard (4200-4225)
{4200}{}{}

# Guard (4225-4249)
{4225}{}{}

# Tough Citizen (4250-4274)
{4250}{}{}

# Citizen (4275-4299)
{4275}{}{}

# Custom (4300-4499)
{4300}{}{Yes Master?}
{4301}{}{}

######
#  Call for Help Guards  (4500-4799)
######

# Tough Guard (4500-4525)
{4500}{}{}

# Guard (4525-4549)
{4525}{}{}

# Tough Citizen (4550-4574)
{4550}{}{}

# Citizen (4575-4599)
{4575}{}{}

# Custom (4600-4799)
{4600}{}{}

######
# Call for Help Others    (4800-5099)
######

# Tough Guard (4800-4825)
{4800}{}{}

# Guard (4825-4849)
{4825}{}{}

# Tough Citizen (4850-4874)
{4850}{}{}

# Citizen (4875-4899)
{4875}{}{}

# Custom (4900-5099)
{4900}{}{}

######
#  Attack Player  [War Cries]   (5100-5399)
######

# Tough Guard (5100-5125)
{5100}{}{}

# Guard (5125-5149)
{5125}{}{}

# Tough Citizen (5150-5174)
{5150}{}{}

# Citizen (5175-5199)
{5175}{}{}


########################################
########################################
########################################
# Custom (5200-5399)
# END GAME MOD BY CORPSE, W/ ADDITIONS BY SDUIBEK

{5201}{}{Do you wish to continue playing Fallout Fixt with this character?}
{5203}{}{Yes.  [CONTINUE PLAYING: This dialog window will close and you'll stay on this map. Play continues normally.]}
{5202}{}{No.  [END GAME: Play movie sequence & credits, then EXIT TO MAIN MENU.]}

########################################
########################################
########################################


# Watched Comments(5400-5599)
{5400}{}{Bleib da weg!}

# For Repair Bots
{9000}{}{Reparaturen abgeschlossen.}
{9001}{}{Neubewaffnung abgeschlossen.}
{9002}{}{Strukturelle Schäden werden repariert.}

{9003}{}{No Structural Damage Detected.}
{9004}{}{Repair function.}
{9005}{}{Input Command.}
{9006}{}{Guard this location.}
{9007}{}{Initializing Sentry Function.}
{9008}{}{Equip Armament.}
{9009}{}{You don't have one in your inventory.}
{9010}{}{Plasma Rifle.}
{9011}{}{Laser Rifle.}
{9012}{}{Minigun.}
{9013}{}{Gatling Laser.}
{9014}{}{Weapons.}
{9015}{}{Ammo.}
{9016}{}{5mm JHP.}
{9017}{}{5mm AP.}
{9018}{}{Energy Cell.}
{9019}{}{Mr. Handy is programmed to use energy weapons and miniguns.}

# default options for party members
{10000}{}{Erzähl mir was.}
{10001}{}{Du solltest dich jetzt selber heilen.}
{10002}{}{Du mußt hier warten, bis ich zurück bin.}
{10003}{}{Leg deine Waffe weg.}
{10004}{}{Bleib in meiner Nähe.}
{10005}{}{Beweg dich nicht zu weit weg.}
{10006}{}{Wir sollten uns ein bißchen verteilen.}
{10007}{}{Das wär's erst mal.}
{10008}{}{Wir müssen unseren Abstand ändern.}
{10009}{}{Ich muß mit dir über deine Ausrüstung reden.}
{10010}{}{Andererseits ist der Abstand fürs erste wohl doch ganz OK so.}
{10011}{}{Ach, eigentlich ist es gar nicht nötig, irgendwas über deine Ausrüstung zu erfahren.}
{10012}{}{Ich möchte, daß du deine Rüstung ablegst.}
{10013}{}{Ich möchte wissen, mit was für Waffen du umgehen kannst.}

# default join me again message
{10100}{}{Gehn wir.}

