{100}{}{Du kommst gerade rechtzeitig, mein Freund. Viel Glück und gute Reise!}
{101}{}{Wir könnten deine Hilfe gebrauchen!}
{102}{}{Ich werd' dich umbringen!}
{103}{}{Lass mich in Ruhe!}
{104}{}{Beschütze den Caravan!}
