{100}{}{Du siehst einen zombifizierten Ghul.}
{101}{}{Du siehst einen Zombie.}
{102}{}{Ugh.}
{103}{}{Hiiiiirrrn}
{104}{}{Buuuu...}
{105}{}{Uuhnnng..}
{106}{}{Grrr!}
{107}{}{Uungh.}
{108}{}{Mmmuuh...}
{109}{}{Arrrr!}
{110}{}{Grrrrr!}
{111}{}{*stöhn*}
{112}{}{*röchel*}
{113}{}{Mmmmmmm.}
{114}{}{*stöhn*}

# Examining the ghouls, restored from original Fallout files

{200}{}{Du untersuchst das bedauernswerte Geschöpf, kannst aber nicht
 herausfinden, was es zu dem gemacht hat, was es jetzt ist.}
{201}{}{Es scheint einmal ein Mensch gewesen zu sein oder zumindest vom Menschen abzustammen. Du vermutest, dass der schlechte Zustand des Körpers auf Säure oder Strahlung zurückzuführen ist.}
{202}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt, aber dennoch funktionsfähig zu sein. Auch wenn es einmal ein Mensch gewesen ist, scheint es doch eher wie ein Tier gelebt zu haben.}
{203}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt und der Großteil der Muskel- und Hirnmasse zerstört zu sein. Genetische Merkmale sprechen deiner Meinung nach dafür, dass es wie du von Vaultbewohnern abstammt.}
{204}{}{Dieses bedauerndswerte Geschöpft ist stark verstrahlt. Du kannst nicht feststellen ob es verrückt geworden ist durch die Haltung im Käfig, oder dem Verlust von zu viel Gehirnmasse durch Strahlenschäden.}
{205}{}{Der Körper des menschenähnlichen Wesens ist stark verstrahlt, aber es hat noch genügend Hirnsubstanz und Motorik bewahrt um sprechen zu können.}

# Messages when getting rads during combat with irradiated critters (glowing ones, radrats, etc)
# Listed in different formats, in case I want to implemented user choice of how it displays. --Sduibek

#Not currently used:
{300}{}{Du erleidest eine leichte Strahlendosis.}
{301}{}{Du erleidest eine mittlere Strahlendosis.}
{302}{}{Du erleidest eine große Strahlendosis.}

#Not currently used:
{303}{}{Du wurdest leicht verstrahlt.}
{304}{}{Du wurdest verstrahlt.}
{305}{}{Du wurdest mäßig verstrahlt.}
{306}{}{Du wurdest schwer verstrahlt.}

# THIS IS THE FORMAT CURRENTLY USED:

{1004}{}{Du wurdest einer milden Strahlendosis ausgesetzt.}
{1005}{}{Du wurdest einer leichten Strahlendosis ausgesetzt.}
{1006}{}{Du wurdest einer mäßigen Strahlendosis ausgesetzt.}
{1007}{}{Du wurdest einer schweren Strahlendosis ausgesetzt.}
