{100}{}{Du siehst einen Paladin.}
{101}{}{Tut mir leid, Neuling, ich kann im Moment nicht reden.}
{102}{}{Guten Tag.}
{103}{}{Wußtest du, daß du in einer Powerrüstung Wochen ohne Wasser überleben kannst?}
{104}{}{Ein guter Kampf hat was, nicht wahr?}
{105}{}{Ich mag diese neuen Lasergewehre wirklich gerne, aber am liebsten sind mir doch noch die alten Laserpistolen.}
{106}{}{Die Grenzpatrouillen bei Nacht sind sehr gefährlich. An deiner Stelle würde ich mich nachts nicht zu weit von hier entfernen.}
{107}{}{Sei vorsichtig! Da draußen lauern tödliche Gefahren.}
{108}{}{Ich glaub', auf meiner Rüstung ist ein Fleck!}
{109}{}{Die Brotherhood ist großartig. Ich hab' zwar keine Ahnung, wie es ohne die Brotherhood ist, aber es kann gar nicht besser sein.}
{110}{}{Guten Tag, Neuling.}
{111}{}{Falls du irgend etwas brauchst, wende dich an Vree.}
{112}{}{Vree ist dort drüben, falls du mit jemandem reden willst.}
{113}{}{Ich muß mir zwischen den Patrouillen und der Ausbildung einfach die Zeit für mein Studium nehmen. Ich glaub', ich roste ein bißchen ein.}
{114}{}{Neuling, dein Körper und Geist müssen immer in Topform sein!}
{115}{}{Ein Paladin zu sein, bedeutet nicht nur, kämpfen zu können, mein Sohn.}
{116}{}{Ein Paladin zu sein, bedeutet nicht nur, kämpfen zu können, meine Liebe.}
