{100}{}{Stirb, du Hund!}
{101}{}{Meine Niederlage wird gerächt werden!}
{102}{}{Halt, Neuling! Was hast du zu berichten?}
{103}{}{Alles ruhig an der westlichen Front.}
{104}{}{Radscorpions und unerträgliche Hitze. Uh ... Sir.}
{105}{}{Eigentlich wollte ich wissen, ob du irgend etwas gehört hast.}
{106}{}{Nichts zu berichten, Sir!}
{107}{}{Ruh?}
{108}{}{Halt! Ich erkenne dich - du warst schon mal bei der Brotherhood. Mag sein, daß manche dir vertrauen, aber ich nicht. Was willst du?}
{109}{}{Das geht niemanden was an. Ich misch' mich ja auch nicht in eure Angelegenheiten ein.}
{110}{}{Ich wollte nur mal ein freundliches Gesicht sehen.}
{111}{}{Ich zieh' einfach durchs Ödland und versuch' zu überleben.}
{112}{}{Ich töte das Ungeziefer in der Wüste. Was dagegen?}
{113}{}{Das verrat' ich nur eurem Anführer. Führ mich zur Brotherhood.}
{114}{}{Biz?}
{115}{}{Halt! Ich weiß, wer du bist, und ich traue dir nicht. Ich warne dich: Wenn du hier Ärger machst, wirst du getötet. Geh jetzt weiter!}
{116}{}{Halt! Wer da? Nenn deinen Namen und sag, was du willst!}
# TRANSLATION NOTES
# The player-character's name is inserted after line 117, and then has
# line 118, 119, 120, or 121 appended.
{117}{}{Mein Name ist }
{118}{}{, und ich suche einen Steuerchip für meine Vault. Kannst du mir helfen?}
{119}{}{, und ich suche nach dem Ursprung der Mutantenangriffe.}
{120}{}{, und was ich hier tue, geht dich nichts an!}
{121}{}{, und ich bin auf der Suche nach Abenteuern.}
{122}{}{Hände hoch, Soldat.}
{123}{}{Runk!}
{124}{}{Halt! Dieses Land gehört der Brotherhood of Steel. Wenn du nicht sofort verschwindest, werden wir dich Eindringling erschießen.}
{125}{}{Sehr gut. Mach weiter, Neuling.}
{126}{}{Verstehe. Mach weiter, Neuling.}
{127}{}{Berichten zufolge sollen große Mutantenmenschen Reisende angreifen. Deshalb sind wir besonders wachsam. Behalte das Gebiet im Auge und kehr notfalls zum Lager zurück. Wegtreten, Neuling!}
{128}{}{Wir leben in schwierigen Zeiten, Neuling! Die Mutanten sind im Vormarsch. Sie greifen Caravans an! Wir benötigen Informationen, und zwar sofort. Die Antwort 'Nichts zu berichten.' ist einfach nicht genug!}
{129}{}{Beweg deinen Hintern und bring uns ein paar nützliche Informationen! Wegtreten, Neuling!}
{130}{}{Ja, richtig, ich hab' von dir gehört. Nicht gerade mit Intelligenz gesegnet, aber ein verdammt guter Kämpfer. Schade eigentlich!}
{131}{}{Dies ist unser Land, und deshalb geht es uns sehr wohl etwas an, was du hier zu suchen hast. Also, was willst du?}
{132}{}{Ich suche einen Steuerchip für meine Vault. Kannst du mir helfen?}
{133}{}{Ich suche nach dem Ursprung der Mutantenangriffe.}
{134}{}{Dies ist vielleicht euer Land, aber ich bin noch lange nicht euer Sklave.}
{135}{}{Ich bin sehr lange durchs Ödland gezogen. Ich wollte nur wissen, ob es Neuigkeiten gibt.}
{136}{}{Ein freundliches Gesicht? Wirst du von mir nicht sehen. Ich rat' dir zu gehen.}
{137}{}{So wie wir alle. Solange du dich nicht gegen die Brotherhood wendest, geschieht dir nichts. Aber sieh dich vor!}
{138}{}{Das hängt davon ab, ob du uns als Ungeziefer ansiehst oder nicht. Wenn du unsere Feinde angreifst, darfst du durch unser Gebiet reisen. Greifst du jedoch uns an, wirst du getötet. Das dürfte als Warnung reichen!}
{139}{}{Das ist ein vernünftiges Anliegen. Tritt ein!}
{140}{}{Steuerchip? Das meinst du doch hoffentlich nicht ernst! Kämpf besser draußen, als dich zum Sklaven eines Maschinenteils zu machen.}
{141}{}{So wie wir. Die meisten glauben, daß sie vom Glow kommen, aber ich bezweifle das. Nicht einmal Mutanten könnten dort lange überleben. Laß es uns wissen, wenn du etwas herausfindest.}
{142}{}{Wie kannst du mich dessen beschuldigen? Die Brotherhood of Steel hat noch nie jemandem gegen seinen Willen gezwungen, ihr zu dienen. Das verstößt gegen all unsere Grundsätze. Verschwinde! Ich will dich nicht mehr sehen!}
{143}{}{Wir haben im Westen - ungefähr eine Tagesreise von hier - die Überreste eines Caravans gefunden. Es gab nur eine Überlebende - ein armes Mädchen. Sie behauptete, von Mutantenmenschen mit unglaublichen Kräften angegriffen worden zu sein.}
{144}{}{Wir haben genug Berichte gehört und sind daher ... besorgt. An deiner Stelle würde ich vorsichtig sein.}
{145}{}{Ich werd' dir Manieren beibringen, Junge! Das wird bestimmt ein netter Zeitvertreib!}
{146}{}{Ich werd' dir Manieren beibringen, Mädchen! Das wird bestimmt ein netter Zeitvertreib!}
{147}{}{Du kannst dich an gar nichts mehr erinnern, du armes Geschöpf.}
{148}{}{Verschwende nicht meine Zeit, du Idiot!}
{149}{}{Was willst du?}
{150}{}{Nichts.}
{151}{}{Dann schlag' ich vor, du gehst besser.}
