{100}{}{Du siehst Gizmo, den Kasinobesitzer.}
{101}{gizmo_1}{Beweg deinen Hintern hier rein und setz dich. Wir müssen was besprechen.}
{102}{}{Sind wohl schon genug Ärsche hier drinnen ...}
{103}{}{Verstanden. Was willst du?}
{104}{}{Was besprechen?}
{105}{}{Hng.}
{106}{gizmo_1b}{Raus hier, du Vollidiot!}
{107}{gizmo_2}{Ganz schön frech! Mehr Respekt!}
{108}{}{Machst du noch was anderes als essen?}
{109}{}{Du hast recht, tut mir leid. Lass uns zum Geschäft kommen.}
{110}{gizmo_4}{Pass auf ... [Gizmo keucht.] ... Folgendes: Junktown ist nicht mehr das, was es mal war. Ohne meiner Spielhalle wäre es gar nicht mehr hier. Egal, jedenfalls hab' ich Killian am Hals, und er geht mir auf den Geist. Genau deshalb bist du jetzt hier.}
{111}{}{Was soll ich machen?}
{112}{}{Wenn du glaubst, ich helf' dir, bist du schön blöd, Dicker!}
{113}{gizmo_4a}{Witzig.}
{114}{gizmo_5}{Ich will, dass du ihn für mich um die Ecke bringst, klar? Keine Zeugen, einfach rein, bumm und raus.}
{115}{}{Warum lässt du das nicht von deinen Schlägern erledigen?}
{116}{}{Nicht für alles Geld dieser miesen Welt würde ich für dich arbeiten.}
{117}{}{Klar. Ich kann das Geld gut gebrauchen.}
{118}{}{Nee, lass mal. Trotzdem danke.}
{119}{}{Wieviel springt dabei raus?}
{120}{gizmo_6}{Würde ich ja ... Aber es darf keine Verbindung zwischen mir und Killians unglücklichem Ableben geben. [Gizmo hustet.]}
{121}{}{Leuchtet ein. Also, ich mach's.}
{122}{}{Na gut, ich mach's.}
{123}{}{Feigling! Hast du etwa Angst, die Leute mögen dich dann nicht mehr? Zu spät!}
{124}{}{Wieviel springt dabei raus?}
{125}{}{Nie und nimmer!}
{126}{}{Nee, lass mal. Trotzdem danke.}
{127}{gizmo_7}{[Gizmo keucht.] Schön, dass du mich verstehst. Als Beweis will ich die Marken, die Killian um den Hals trägt, sonst kriegst du kein Geld. Und verarsch mich nicht! Ich hab' immer noch die Kniescheiben vom letzten, der's versucht hat.}
{128}{gizmo_8}{Tausend Deckel, nicht mehr, nicht weniger.}
{129}{}{Klingt gut. Ich mach's.}
{130}{}{Das nennst du eine Belohnung?! Wenn ich den Kerl kaltmachen soll, musst du mir schon mehr bieten.}
{131}{}{Naja ... Ehrlich gesagt, gefällt mir das Geschäft nicht.}
{132}{}{Ich trau' dir nicht mal so weit, wie dich zwei Männer werfen könnten. Vergiss es!}
{133}{gizmo_9}{[Gizmo lacht und hustet.] Vielleicht hast du recht. Ich denke, du bist mehr wert: 1500.}
{134}{}{Das hört sich schon besser an.}
{135}{}{Was ist das denn für 'ne Bezahlung?! Pro Pfund Körpergewicht von dir 'nen Dollar, oder was? Vergiss es!}
{136}{}{Danke, aber ich lass' lieber die Finger davon.}
{137}{}{Nie und nimmer!}
{138}{gizmo_10}{Schade, dass du so denkst. Das wird dir noch leid tun. Davon darf kein Wort nach draußen. Izo, zeig ihm, was wir mit Leuten machen, die mir eine Abfuhr erteilen!}
{139}{gizmo_11}{Einmal ist okay. Zweimal ist zuviel. Das war das zweite Mal. Izo, bring mir einen Satz Kniescheiben!}
{140}{gizmo_13}{Hast du den Auftrag schon erledigt?}
{141}{}{Klar doch.}
{142}{}{Nee, noch nicht.}
{143}{gizmo_14}{Zeig mir die Marken.}
{144}{gizmo_15}{Oh, ja! Oh, ja ... hahaha ... Izo hat dein Geld. Oh, das ist gut! He, he, äh ... du solltest die Stadt für eine Weile verlassen - für alle Fälle.}
{145}{}{Okay, ich gehe.}
{146}{}{Du kommandierst mich nicht rum, Fettsack. Kapiert?}
{147}{}{Und wenn nicht?}
{148}{}{Klar, ich gehe, aber vergiss nicht: Du schuldest mir noch was.}
{149}{gizmo_16}{Wenn du die Stadt nicht verlässt, macht sie dich fertig. Kapiert?}
{150}{}{Okay, okay. Ich geh' ja schon.}
{151}{}{Fertigmachen? Wer? Du etwa? Du kriegst doch nicht mal deinen fetten Arsch hoch, um dir ein Sandwich zu holen, geschweige denn, um mich zu töten!}
{152}{}{Okay, ist ja schon gut, aber vergiss nicht: Du schuldest mir noch was.}
{153}{gizmo_17}{He, gibst du mir die Marken?}
{154}{}{Hmm ... also ... ich ... hab' sie verloren.}
{155}{}{Und wenn ich sie dir nicht gebe?}
{156}{}{Ich hab' gelogen. Ich hab' sie nicht.}
{157}{}{Ich hatte sie wirklich, aber dann hab' ich sie verloren.}
{158}{gizmo_18}{[Gizmo lacht dreckig.] Du bist ein mieser Lügner. Jetzt hau ab und hol die Marken. Und lass dich nicht wieder blicken, bevor du Killian kaltgemacht hast.}
{159}{gizmo_19}{Kein Problem, dann hol' ich sie von deiner Leiche.}
{160}{}{Äh ... naja ... ich hab' nicht ganz die Wahrheit gesagt. Ich hab' sie nämlich nicht.}
{161}{}{Ach ja? Willst du dir etwa 'nen anderen für deine Drecksarbeit suchen?}
{162}{}{Ich hab' sie verloren.}
{163}{}{Ich hatte sie wirklich, aber jemand hat sie mir gestohlen.}
{164}{gizmo_20}{Keine Marken, keine Kohle. Kommst du ohne die Marken zurück, wird sich Izo an dir zu schaffen machen. Und jetzt raus!}
{165}{gizmo_21}{Was willst du? Ich hab' zu tun.}
{166}{}{Ich muss dir sagen, dass dein Plan schiefgegangen ist.}
{167}{}{Eigentlich nichts. Ich geh' dann wieder.}
{168}{}{Mich interessiert einfach, wie ein Blödmann wie du so überleben kann!}
{169}{}{Ich will über den Mordanschlag auf Killian reden.}
{170}{gizmo_22}{Was redest du da?}
{171}{}{Du weißt genau, wovon ich rede. Du hast einen Killer auf Killian angesetzt, und er hat's vergeigt.}
{172}{}{Du erinnerst dich nicht mehr, einen Killer auf Killian angesetzt zu haben, du Schnarchbacke?}
{173}{}{Also, nehmen wir mal an ...}
{174}{}{Tu nicht so, als wüßtest du von nichts, du verlogenes Schwein!}
{175}{}{Schon gut. Auf Wiedersehen.}
{176}{gizmo_23}{Ich kenne dich nicht. Aber ich mag keine Fremden, die in mein Büro kommen und mir Dinge vorwerfen, von denen sie keine Ahnung haben.}
{177}{}{Ganz so ist es aber nicht, Gizmo. Ich werf' dir nichts vor, ich will dir nur helfen.}
{178}{}{Ich weiß alles. Also gib's zu!}
{179}{}{Schon gut. Ich geh' dann.}
{180}{gizmo_24}{Wirklich? [Gizmo lacht dreckig.] Er will mir helfen? Von welcher Art von Hilfe reden wir denn hier?}
{181}{}{Du hattest einen Killer auf Killian angesetzt. Er hat's vergeigt. Nun brauchst du jemanden, der den Job erledigt, und zwar richtig.}
{182}{}{Nichts. Vergiss es einfach!}
{183}{gizmo_25}{Lass mich mal raten! Bist du derjenige?}
{184}{}{Sehr richtig ... Aber ich hab' natürlich meinen Preis.}
{185}{}{Ich mach' ihn schneller kalt, als du spucken kannst.}
{186}{gizmo_26}{Und wie kann ich dir trauen?}
{187}{}{Was bleibt dir anderes übrig? Schließlich brauchst du ja jemanden von außerhalb für deine Drecksarbeit, stimmt's?}
{188}{}{Kannst du nicht ... Ich meine, kannst du ... Ich meine ...}
{189}{}{Weil ich ein Profi bin. Ich hab' so was schon öfter gemacht.}
{190}{gizmo_27}{Hmm ... in Ordnung, machen wir. Aber denk dran, dass mit Gizmo keiner jemals ein falsches Spiel treibt und dann darüber auspackt. Kapiert?}
{191}{}{Oh, ich könnt' dich schon verarschen. Obwohl ... bei deinem großen Arsch ...}
{192}{}{Klar, aber zuerst will ich wissen, warum du ihn loswerden willst.}
{193}{gizmo_28}{Hmm. Einfach! Ich will ihn tot sehen ... Er stört meine Geschäfte. Also, machst du ihn nun alle?}
{194}{}{Deshalb bin ich hier. Noch vor Sonnenuntergang ist er tot.}
{195}{}{Klar. Wird erledigt.}
{196}{}{Kannst du das noch mal sagen ... und zwar was deutlicher?}
{197}{}{Also, ähm ... nein, ich mach's nicht.}
{198}{gizmo_29}{Gut. Komm als Beweis mit den Marken wieder, die er um den Hals trägt. Und erzähl niemandem von diesem Gespräch. Niemand treibt ein falsches Spiel mit mir. Niemand!}
{199}{gizmo_30}{Enweder bist du dumm ... oder ein echt dummer Spion. Egal, denn Izo macht dich jetzt echt kalt.}
{200}{gizmo_32}{Ich mag Leute nicht, die meine Zeit verschwenden. Komm so schnell nicht wieder!}
{201}{gizmo_33}{Beispiel?}
{202}{}{Also, angenommen, du hast einen Killer auf Killian angesetzt und er hat's vergeigt. Dann brauchst du doch 'nen anderen, der den Job richtig erledigt.}
{203}{}{Häh? Oh, schon gut.}
{204}{gizmo_34}{Weißt du ... [Gizmo seufzt.] ... Ich mag's nicht, wenn Leute mich in meinem Haus beleidigen. Izo, führ unseren Gast hinaus ... durch's Fenster.}
{205}{gizmo_35}{Du wieder! Ich musste jemand anders anheuern, um deine Arbeit zu erledigen. Darüber bin ich unglücklich. Izo wird dir zeigen, wie unglücklich ich bin. Ich hoffe, du hattest einen schönen Tag. Es war dein letzter!}
{206}{gizmo36a}{Ahhh ... Killian ist der Bürgermeister dieser Stadt. Glaubt, er weiß alles ... Nun, wir werden ja sehen, wieviel er weiß, oder?}
{207}{gizmo_37}{[Gizmo räuspert sich.] Das bin ich, du Idiot! Ich leite die ... Spielhalle hier.}
{208}{gizmo_38}{Das ist Killians Revier im Norden der Stadt. Der hat nur Schund.}
{209}{gizmo_39}{Die meisten Leute spielen hier. Du stellst dämliche Fragen.}
{210}{gizmo_42}{Möchtest du das nicht wissen?}
{211}{gizmo_43}{Das geht dich nichts an, kapiert?}
{212}{gizmo_44}{[Gizmo schnieft.] Ich ... ähm ... Ich möchte jetzt nicht darüber sprechen.}
{213}{gizmo45m}{He, was zum Teufel machst du denn? Izo, reiß ihm die Arme aus!}
{214}{gizmo45f}{He, was zum Teufel machst du denn? Izo, reiß ihr die Arme aus!}
{215}{gizmo_47}{Bist du taub? Ich sagte ...}
{216}{gizmo_48}{He, ich sag's nicht noch einmal!}
{217}{}{ Erfahrungspunkte für die Vernichtung von Gizmo. Möge der Dreckskerl in Unfrieden ruhen!}
{218}{}{Das ist ungelogen der dickste Mensch, den du je gesehen hast.}
{219}{gizmo_46}{Weißt du, nach deinem letzten Besuch hab' ich was Interessantes entdeckt: Das einzige, das ich noch mehr verabscheue als kalten Kaffee, sind Verräter. Jungs!!!}
{220}{}{Eins sag' ich dir, Killian. Ich konnte dich noch nie riechen, und jetzt werd' ich deinem Gestank ein Ende machen.}
{221}{}{Ich hab' mich um Killian gekümmert. Das ist doch ganz in deinem Sinne, stimmt's?}
{222}{}{Oh, wirklich?}
{223}{}{He, okay, wenn du seinen Tod nicht willst, auch gut. Ich wollte nur helfen.}
{224}{}{Ich hatte an ein Messer im Rücken oder eine Kugel im Kopf gedacht.}
{225}{}{Verstanden. Warum soll er sterben?}
{226}{gizmo_24}{Wirklich? [Gizmo lacht dreckig.] Sie will mir helfen? Von welcher Art Hilfe reden wir denn hier?}

# for Fallout Fixt:

{227}{}{Wer bist du? Was willst du?}
{228}{}{Du siehst die erbärmliche Gestalt eines Mannes. Das muss Gizmo sein.}

# Gizmo's Tell-Me-Abouts generic responses
{980}{gizmo_42}{Möchtest du das nicht wissen?}
{981}{gizmo_43}{Das geht dich nichts an, kapiert?}
#
# Gizmo's Tell-Me-Abouts
#
{1000}{}{Killian}
{1001}{}{Gizmo}
{1002}{}{Krämerladen}
{1003}{}{Spielhalle}
{1004}{}{Darkwater}
{1005}{}{Spielen}
{1006}{}{Kasino}
{1007}{}{Junktown}

{1100}{gizmo36a}{Ahhh ... Killian ist der Bürgermeister dieser Stadt. Glaubt, er weiß alles ... Nun, wir werden ja sehen, wieviel er weiß, oder?}
{1101}{gizmo_37}{[Gizmo räuspert sich.] Das bin ich, du Idiot! Ich leite die ... Spielhalle hier.}
{1102}{gizmo_38}{Das ist Killians Revier im Norden der Stadt. Der hat nur Schund.}
{1103}{gizmo_39}{Die meisten Leute spielen hier. Du stellst dämliche Fragen.}
{1104}{gizmo36a}{Ahhh ... Killian ist der Bürgermeister dieser Stadt. Glaubt, er weiß alles ... Nun, wir werden ja sehen, wieviel er weiß, oder?}
{1105}{gizmo_39}{Die meisten Leute spielen hier. Du stellst dämliche Fragen}
{1106}{gizmo_39}{Die meisten Leute spielen hier. Du stellst dämliche Fragen}
{1107}{gizmo_39}{Die meisten Leute spielen hier. Du stellst dämliche Fragen}

