{100}{}{Die Tür ist bereits aufgeschlossen.}
{101}{}{Du kannst das Schloss öffnen.}
{102}{}{Offensichtlich kannst du das Schloss nicht öffnen.}
{103}{}{Das elektronische Sicherheitssystem versetzt dir einen Stromschlag!}
{104}{}{Du hast einen Alarm an den Versorgungstüren ausgelöst.}
{105}{}{Die Tür besitzt ein mechanisches Schloss, das geöffnet werden muss.}
{106}{}{Das elektronische Sicherheitssystem ist bereits deaktiviert.}
{107}{}{Du deaktivierst das elektronische Sicherheitssystem.}
