{100}{}{Eine Wache von Junktown.}
{101}{}{Das hier ist Junktown. Ein netter Ort zum Leben, zumindest solange
 du auf der unserer, der guten Seite stehst}
{102}{}{Nimm dich vor Gizmo und seinen Kumpanen in Acht.}
{103}{}{Ich mag meinen Boss.}
{104}{}{Steck das besser weg. Junktown ist ein freundlcher Ort,
 mein Freund, und wir sollen das das so bleibt.}
{105}{}{Was wegstecken?}
{106}{}{Sag mir nicht was ich tun soll, Verlierer.}
{107}{}{Klingt fair. Apropos, was sagt das hiesige Gesetz zu Waffenbesitz?}
{108}{}{Äh oh.}
{109}{}{Deine Waffe, Idiot! Killian wird dir deine Waffen nicht wegnehmen,
 aber du solltest sie besser im Halfter lassen, klar.}
{110}{}{Oh, tut mir Leid.}
{111}{}{Auf keinen Fall! Ich steck meine Waffen für niemanden weg!}
{112}{}{Du benimmst dich besser, denn es ist Gesetz und ich vertrete das Gesetz.
 Steck deine Waffe weg, zieh sie höchstens zur Selbstverteidigung, und
 wirst mit uns Wachen keine Probleme haben.}
{113}{}{[mehr]}
{114}{}{Missachte das Gesetz und wir werden dich in die gesetzlose Einöde
 zurückbringen - tot oder lebendig.}
{115}{}{Sicher, wenn du es so sagst.}
{116}{}{Ich preiff auf deine Gesetze!}
{117}{}{Also, äh, von mir aus. Aber sei besser vorsichtig.}
{118}{}{Na gut, Hah.}
{119}{}{Gut dass du fragst. Außer zur Selbstverteidigung dürfen keine Waffen
 gezogen werden. Wenn du einen Kampf anfängst ist das deine Schuld. Abgesehen
 davon ist es dein Recht, bewaffnet rumzulaufen. Zieh nur nicht ohne triftigen
 Grund ein Messer oder eine Pistole. Schönen Tag noch.}
{120}{}{Danke, dir auch.}
{121}{}{He du, keine Waffen! Und es ist mir egal ob dich deine Mamma als Kind
 auf den Kopf fallen ließ. Keine Waffen.}
{122}{}{Depp!}
{123}{}{Du erhälst 150 Erfahrungspunkte für das Töten der Wache.}
