{100}{}{He! Was glaubst du eigentlich, was du da machst?!}
{101}{}{He, hast du 'ne Nuka Cola?}
{102}{}{Geschäft läuft gut.}
{103}{}{Gabriel ist ein großartiger Boß.}
{104}{}{Schöner Tag, ne?}
{105}{}{Sprich mit Zack, wenn du Ausrüstung brauchst.}
{106}{}{Zack verkauft Waffen.}
{107}{}{Laß deine Waffen stecken!}
{108}{}{Versuch keine krummen Dinger!}
{109}{}{Hier drinnen können wir's mit ganzen Armeen aufnehmen.}
{110}{}{Ein Typ ist schon mal im Graben geendet. War wirklich schrecklich!}
{111}{}{Verdammter Graben, der Rauch brennt mir in den Augen.}
{112}{}{Ich hasse diesen Job.}
{113}{}{Aus meinem Weg!}
{114}{}{Geh mir nicht auf die Nerven!}
{115}{}{Siehst du nicht, daß ich beschäftigt bin?}
{116}{}{Du siehst einen typischen Gunrunner.}
