{100}{}{Du siehst Gunther.}
{101}{}{Du siehst einen harten Kerl in seinen Dreißigern.}
{102}{}{Willkommen in meinem bescheidenen Heim. Was kann ich für dich tun?}
{103}{}{Kannst du mir etwas über den Hub erzählen?}
{104}{}{Wo kann ich hier Munition und Waffen kriegen?}
{105}{}{Was macht man hier so?}
{106}{}{Wer ist hier der Gesetzeshüter?}
{107}{}{Was willst du sonst noch so wissen?}
{108}{}{Dies ist eine große Stadt, die größte, die ich je gesehen habe. Das Zentrum liegt im Süden, und die einzelnen Stadtteile verzweigen sich von dort in alle Richtungen.}
{109}{}{Wo kann ich mich mit Sachen eindecken?}
{110}{}{Wenn ich einen Job bräuchte, wo geh' ich da am besten hin?}
{111}{}{Kann ich dich noch was fragen?}
{112}{}{Danke für die Auskunft. Auf Wiedersehen.}
{113}{}{Alles, was ich brauche, krieg' ich bei Mitch unten im 'Maltese Falcon'. Geh von hier einfach weiter in Richtung Süden.}
{114}{}{Ich arbeite manchmal für einen der Caravans, die von hier losziehen. Wenn du so eine Arbeit suchst, geh am besten zu einem der Handelshäuser. Mir liegen die Far Go Traders besonders, aber ich hab' schon für alle gearbeitet.}
{115}{}{Also, ich kaufe das meiste bei Beth drüben im Waffenladen. Sie hat eine ziemlich große Auswahl.}
{116}{}{Was mach' ich, wenn ich etwas 'Exotischeres' suche?}
{117}{}{Meinst du, dein Name kann mir beim Feilschen nützlich sein?}
{118}{}{Ich hab' gehört, drüben in Old Town gibt es einen Typen, der mit schweren Kalibern handelt.}
{119}{}{Wahrscheinlich nicht, sie steht ziemlich auf ihren Leibwächter Sid. Aber versuch's doch mal bei Butch. Er ist der Anführer der Far Go Traders, denen ihr Laden gehört.}
{120}{}{Ich schlag' mich so durch. Ich heuer bei den Caravans an, wenn ich knapp bei Kasse bin, und arbeite ab und zu für die Bauern unten im Süden.}
{121}{}{Wahrscheinlich bist du Deputy Fry schon über den Weg gelaufen. Sein Boß ist Sheriff Greene. Du findest ihn meistens auf der Polizeiwache.}
{122}{}{Keeeeks!}
{123}{}{Entschuldige, aber du sprichst in Rätseln. Vielleicht kann dir Dr. Thorndyke von den Children helfen.}
