# Beth is female. She speaks with a normal accent. She is a friendly person
# who is mostly interested in selling equipment and information.
{100}{}{Du siehst Beth, die Besitzerin des Waffenladens.}
{101}{}{Hallo! Womit kann ich dir helfen?}
{102}{}{Kann ich dir ein paar Fragen stellen?}
{103}{}{Kann ich dich noch was fragen?}
{104}{}{Ich möchte etwas kaufen.}
{105}{}{Ich möchte etwas verkaufen.}
{106}{}{Wie kann man in dieser Gegend Geld verdienen?}
{107}{}{Nichts. Tschüß!}
{108}{}{Ruk?}
{109}{}{Was erzählt man sich hier so über die verschwundenen Caravans? }
# the Deathclaw is male
{110}{}{Was weißt du über die Deathclaw?}
{111}{}{Kannst du mir das über die Deathclaw noch mal erzählen?}
# Decker is male
{112}{}{Was kannst du mir über Decker erzählen?}
{113}{}{Was kannst du mir über die verschiedenen Händler erzählen?}
{114}{}{Hast du irgendwelche Gerüchte gehört?}
{115}{}{Danke, das ist alles. Tschüß!}
{116}{}{Hmm, schon gut.}
# Jain is a female religious figure
{117}{}{Ich bin ja eigentlich keine Klatschbase, aber ich hab' gehört, daß Deckers Tod etwas mit dem Mordanschlag auf Jain zu tun hat.}
# The Maltese Falcon is a bar
{118}{}{Normalerweise rede ich ja nicht hinter dem Rücken anderer, aber ich kenne jemanden, der wiederum jemanden kennt, der sagt, daß sie kurz vor den Morden drei extrem große Personen in Roben in den 'Maltese Falcon' reingehen haben sehen.}
# the Children of the Cathedral is an organization - religious
{119}{}{Normalerweise rede ich ja nicht hinter dem Rücken anderer, aber jemand hat Jain, die Hohepriesterin der Children of the Cathedral, umgebracht. Mir persönlich ist das ja egal, aber ich weiß wirklich nicht, warum man ihr das angetan hat.}
# The Brotherhood of Steel is an organization - religious
{121}{}{Normalerweise rede ich ja nicht hinter dem Rücken anderer, aber ein Freund von mir, ein Händler, hat eine Gruppe umherwandernder Mutanten in der Wüste jenseits der Brotherhood of Steel gesehen, weit im Nordwesten.}
{122}{}{Normalerweise rede ich ja nicht hinter dem Rücken anderer, aber die Children of the Cathedral haben nach dir gefragt. Ich wäre an deiner Stelle vorsichtig. Sie sind ein seltsames Pack.}
{123}{}{Ich bin ja eigentlich keine Klatschbase, aber ich hab' gehört, daß Deckers Tod etwas mit dem Mordanschlag auf Jain zu tun hat.}
{124}{}{Da gibt es noch was. Ich kenne jemanden, der wiederum jemanden kennt, der sagt, daß sie kurz vor den Morden drei extrem große Personen in Roben in den 'Maltese Falcon' reingehen haben sehen.}
{125}{}{Da gibt es noch etwas. Jemand hat Jain, die Hohepriesterin der Children of the Cathedral, umgebracht. Mir persönlich ist das ja egal, aber ich weiß wirklich nicht, warum man ihr das angetan hat.}
{126}{}{Da gibt es noch etwas. Ein Freund von mir, ein Händler, hat eine Gruppe umherwandernder Mutanten in der Wüste jenseits der Brotherhood of Steel gesehen, weit im Nordwesten.}
{127}{}{Da gibt es noch was. Die Children of the Cathedral haben nach dir gefragt. Ich wäre an deiner Stelle vorsichtig. Sie sind ein seltsames Pack.}
{128}{}{Noch was?}
{129}{}{Danke. Kann ich dich noch was fragen?}
{130}{}{Okay, danke.}
{131}{}{Entschuldigung, wie war das?}
# Klug and Ruk are a stupid person saying something incomprehensible
{132}{}{Klug?}
{133}{}{Ruk!}
{134}{}{Tut mir leid, aber ich verstehe nicht. Komm doch wieder, wenn's dir besser geht.}
# The Merchant Market is a location
{135}{}{Also, ich brauche im Moment niemanden, aber es gibt ein schwarzes Brett in der Mitte des Merchant Market. Vielleicht findest du dort was.}
{136}{}{Okay, danke.}
{137}{}{Nein, zumindest nichts Gutes. Aber laß mich ein paar Nachforschungen anstellen. [Sie blinzelt dir zu.] Noch was?}
{138}{}{Ja.}
{139}{}{Nein.}
{140}{}{Was kann ich sonst noch für dich tun?}
{141}{}{Klar ... sei doch nicht albern!}
{142}{}{Na klar, ich helfe gern. Was willst du denn wissen?}
{143}{}{War wirklich nett, mit dir zu reden. Schönen Tag noch!}
{144}{}{Nein, das ist alles. Wolltest du über noch was sprechen?}
{145}{}{Ja.}
{146}{}{Nein.}
{147}{}{Du bist jederzeit willkommen. Fühl dich wie zu Hause!}
{148}{}{Also, es gibt da jemanden, mit dem du dich nie anlegen solltest, er macht mir Angst. Ihm 'gehört' der 'Maltese Falcon'.}
{149}{}{Warum sagst du das so? Ihm 'gehört' der 'Maltese Falcon'.}
{150}{}{Warum macht er dir Angst? }
{151}{}{Das erinnert mich halt an meinen Freund, dem er vorher gehörte. Decker wollte den 'Maltese Falcon' unbedingt haben, aber mein Freund wollte nicht verkaufen. Zwei Tage später hat man ihn tot in einem finsteren Seitengäßchen von Old Town gefunden.}
{152}{}{Warum denkst du, daß es Decker war?}
{153}{}{Naja, er hätte wissen sollen, daß man sich mit Decker nicht anlegt.}
{154}{}{Tut mir leid, aber ich muß los.}
{155}{}{Mein Freund hatte eine saubere Weste. Er hätte sich nie in Old Town aufgehalten. Er wurde mit einer Magnum erschossen. Die könnte sich niemand in Old Town leisten. Außerdem hat man ihm einmal in den Kopf und zweimal in den Rücken geschossen. Hört sich das nach einem Überfall an? Mein Freund wollte nur sein Leben zurückhaben.}
{156}{}{He, das gefällt mir. Nach dem Mord bringt man seinen Körper an den Ort, den er am meisten verachtet.}
{157}{}{Sein Leben zurückhaben?}
{158}{}{Das tut mir leid.}
{159}{}{Oh, okay.}
{160}{}{Du verstehst das vielleicht nicht, aber die meisten von uns freuen sich auf den Tag, an dem uns unser Leben selbst gehört, an dem wir nicht mehr den Händlern oder Geldverleihern gehören.}
{161}{}{Oh, danke.}
{162}{}{Hörst du eigentlich nie auf zu reden?!}
{163}{}{Das ist das Dümmste, was ich je gehört habe!}
{164}{}{Kann ich sonst noch was für dich tun?}
{165}{}{Entschuldige bitte, aber DU hast doch gefragt.}
{166}{}{Er ist der gefährlichste Mann im Hub. Es wird gesagt, daß er dort das eigentliche Sagen hat, nicht die Händler oder die Polizei. Solltest du ihm jemals über den Weg laufen, nimm dich in acht!}
{167}{}{Das gibt ihm noch lange nicht das Recht, jemanden umzubringen.}
{168}{}{Du machst mich ganz krank. Geh! Ich bin sicher, er vermißt dich.}
{169}{}{Also, es gibt im wesentlichen drei Händlergruppen: Die Water Merchants, den Crimson Caravan und die Far Go Traders. Sie sitzen auch im Stadtrat. Über wen möchtest du etwas wissen?}
{170}{}{Über die Water Merchants.}
{172}{}{Über den Crimson Caravan.}
{173}{}{Über die Far Go Traders.}
{174}{}{Über den Stadtrat.}
{175}{}{Das ist alles. Danke für die Auskunft.}
{176}{}{Schon gut.}
{177}{}{Sie haben die Kontrolle über das gesamte Wasser. Gierige Leute, für die ich nicht arbeiten wollte. Sie zahlen sauschlecht und die Jobs sind auch nicht besser.}
{178}{}{Hatten sie schon immer die Kontrolle über das Wasser?}
{179}{}{Stecken sie hinter den verschwundenen Caravans?}
{180}{}{Danke, noch eine Frage zu den Händlern ...}
{181}{}{Danke. Tschüß dann!}
{182}{}{Was willst du sonst noch wissen?}
{183}{}{Nein. Was ich so gehört habe, hat vor Zeiten eine Gruppe von Händlern den Wasserturm in Beschlag genommen und sich als Water Merchants ausgegeben, und die Menschen mußten ihr Wasser von ihnen beziehen. Der Krieg zwischen den Händlern dauerte Jahre, bis ein Mann namens Roy Greene - ja genau, Justins Großvater - eine Vereinbarung aushandelte, die den Krieg beendete.}
{184}{}{Was für eine Vereinbarung?}
{185}{}{Verdammt! Entschuldige die Frage.}
{186}{}{Danke. Noch eine Frage zu den Händlern ...}
{187}{}{Danke. Tschüß dann!}
{188}{}{Naja, er gründete den Stadtrat und setzte einen Höchstpreis für das Wasser fest. Meiner Meinung nach hätten sie sie fertigmachen sollen - oh, entschuldige - ich meine natürlich, sie hätten ihnen zeigen sollen, wer hier das Sagen hat.}
{189}{}{Klasse, ich hatte gar nicht so viele Informationen erwartet, aber trotzdem vielen Dank!}
{190}{}{Danke. Noch eine Frage zu den Händlern ...}
{191}{}{Danke. Tschüß dann!}
{192}{}{Entschuldige, aber manchmal geht's mit mir durch. Wolltest du sonst noch was wissen?}
{193}{}{Dem Crimson Caravan gehören verrückte Typen an. Sie machen alles, egal, wie gefährlich es ist. Es wundert mich, daß sie nicht mehr Caravans vermissen.}
{194}{}{Sie vermissen auch Caravans?}
{195}{}{Wie gefährlich?}
{196}{}{Danke. Noch eine Frage zu den Händlern ...}
{197}{}{Danke. Tschüß dann!}
{198}{}{Sie fahren mitten durch ein Gebiet, in dem bekanntermaßen Gangster ihr Unwesen treiben. Sie verlangen viel Geld, damit sie weitere Leute anheuern können. Die Bezahlung ist super, aber was nützt einem das Geld, wenn man's nicht mehr ausgeben kann?}
{199}{}{Sie vermissen auch Caravans?}
{200}{}{Danke. Noch eine Frage zu den Händlern ...}
{201}{}{Danke. Tschüß dann!}
{202}{}{Eigentlich sind bei allen Händlern Caravans verschwunden. Ich nehm' an, die Far Go Traders haben einfach kein Glück gehabt.}
{203}{}{Wie gefährlich?}
{204}{}{Danke. Noch eine Frage zu den Händlern ...}
{205}{}{Danke. Tschüß dann!}
{206}{}{Die Far Go Traders zahlen gut, und die Jobs sind nicht allzu gefährlich. Butch gehört dieser Laden, ein guter Mann. Sie sind fair, und ich kann hier tun und lassen, was ich will. Ich arbeite gerne für sie. Außerdem bekommst du einen Rabatt für alles, was du hier kaufst, wenn du für Butch arbeitest.}
{207}{}{Ich persönlich glaube das nicht. Ich denk', es war die Deathclaw oder vielleicht die Brotherhood of Steel.}
{208}{}{Warum glaubst du nicht, daß es die Water Merchants waren?}
{209}{}{Was ist die Deathclaw genau?}
{210}{}{Kannst du mir das über die Deathclaw noch mal erzählen?}
{211}{}{Wer ist die Brotherhood?}
{212}{}{Warum glaubst du, daß es die Brotherhood of Steel war?}
{213}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{214}{}{Okay, ich muß jetzt los.}
{215}{}{Manche meinen, die Water Merchants sind verantwortlich, aber das glaub' ich nicht. Ich denk', es war diese verdammte Deathclaw oder die Leute drüben in der Brotherhood of Steel.}
{216}{}{Naja, ich dachte, sie zerstört die Caravans, aber das stimmt vielleicht nicht. Sie hält sich aber immer noch da draußen auf. Zu viele Gerüchte weisen auf ihre Existenz hin.}
{217}{}{Ich glaube, das ist es, was die Caravans verschwinden läßt. Es könnte auch die Brotherhood of Steel sein. Sie sind ein seltsames Pack. Manche glauben, es sind die Water Merchants, aber sie irren sich.}
{218}{}{Klar.}
{219}{}{Weil - wie ich bereits sagte - ihnen auch Caravans fehlen. Nicht zu vergleichen mit den Far Go Traders, aber sie sind doch auch betroffen.}
{220}{}{Sie könnten ja lügen oder dich absichtlich in die Irre führen.}
{221}{}{Warum sind die Far Go Traders häufiger betroffen als die anderen?}
{222}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{223}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{224}{}{Du erzählst nur Scheiße!}
{225}{}{Danke, aber ich muß jetzt los.}
{226}{}{Wie bitte? Du fällst deine Urteile ziemlich schnell. Hast du etwa Angst vor der Wahrheit?}
{227}{}{Es gibt sechs Vertreter, zwei aus jeder Händlergruppe. Jede Entscheidung braucht mindestens vier Stimmen. Sie können sich nie über irgend etwas einigen.}
{228}{}{Guter Gedanke, aber ich bezweifle das. Sie sabotieren sich schon seit Jahren, aber das ist nicht ihre Art. Sie würden nie so viel Geld ausgeben, um die Caravans verschwinden zu lassen. Außerdem sind alle Caravans gut bewacht. Man könnte meinen, jemand wäre abgehauen. Sie haben nicht genügend Leute oder Geld, um so was durchzuziehen. Da hätte mindestens einer überlebt.}
{229}{}{Ja, aber warum sind die Far Go Traders häufiger betroffen als die anderen?}
{230}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{231}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{232}{}{Danke, aber ich muß jetzt los. }
{233}{}{Kein Glück? Ich weiß nicht, aber vielleicht fahren sie woanders lang als die anderen. Vielleicht weil sie nicht so gut bewacht sind wie der Crimson Caravan, aber ... sie haben vielleicht wertvollere Ladungen als die Water Merchants. Wer weiß? Die drei scheinen sich nicht allzusehr zu unterscheiden.}
{234}{}{Die Water Merchants könnten ja lügen oder dich absichtlich in die Irre führen.}
{235}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{236}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{237}{}{Hörst du eigentlich NIE auf zu reden?!}
{238}{}{Danke, aber ich muß jetzt los.}
{239}{}{Entschuldige, aber du kannst jederzeit gehen. Wenn dich die Antwort nicht interessiert, hättest du nicht fragen sollen.}
{240}{}{Die Deathclaw ist das schrecklichste Wesen, das aus der Asche des Krieges entstehen konnte. Manche sagen, sie ist ein mächtiger Geist aus dem Krieg, der das Land heimsucht. Aber sie ist kein Geist, sie ist so echt wie du und ich. Sie ist ca. 6 Meter groß und hat Zähne so groß wie deine Arme. Sie ist eine Art Dämon, der sich hier breitgemacht hat, als die Welt im Feuermeer versank.}
{241}{}{Oh, entschuldige die Frage.}
{242}{}{Du bist verrückt! Ich sollte deinem Elend hier und jetzt ein Ende machen.}
{243}{}{Weißt du sonst noch was über die Deathclaw?}
{244}{}{Wau! Weißt du, wo sie ist?}
{245}{}{Also, ich kenne diesen alten Mutanten in Old Town namens Harold. Er hat sie schon mal gesehen. Er ist der einzige, der sie je gesehen hat und noch lebt.}
{246}{}{Der einzige, der sie je gesehen hat und noch lebt?}
{247}{}{Ja, klar, und ich bin der Vater der Deathclaw!}
{248}{}{Ja, klar, und ich bin die Mutter der Deathclaw!}
{249}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{250}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{251}{}{Ich werd's mir ansehen. Bis dann!}
{252}{}{Uncle Slappy drüben in Old Town spricht manchmal drüber, aber er ist nur ein verrückter alter Narr.}
{253}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{254}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{255}{}{Danke. Ich werd's mir ansehen. Tschüß dann!}
{256}{}{Du wirst schon sehen!}
{257}{}{Ja, ganz schön verblüffend, was? Irgendwo unten im Südwesten. Es gibt einen alten Mutanten in Old Town namens Harold, der dieses Wesen in seinem Versteck gesehen hat. Der netteste Skag den ich kenne.}
{258}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{259}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{260}{}{Danke. Ich werd's mir ansehen. Tschüß dann!}
{261}{}{Die Brotherhood of Steel besteht aus lauter Technik-Freaks. Sie leben nordwestlich von hier. Menschenopfer und ähnlich schreckliche Dinge gehören zu ihren Ritualen.}
{262}{}{Das ist ja absurd! Wer hat dir das erzählt?}
{263}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{264}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{265}{}{Das ist ja schrecklich. Danke für die Warnung. Tschüß dann!}
{266}{}{Naja, also ... ich erinner' mich nicht, aber wer es auch war, es war kein Lügner ... Ich meine, es könnte was dran sein! Du solltest auf jeden Fall vorsichtig sein!}
{267}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{268}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{269}{}{Du bist ein Idiot!}
{270}{}{Schau mal auf die Uhr, ich muß los! Bis dann!}
{271}{}{Warum, weißt du das denn nicht? [Flüsternd.] Ich hab' gehört, Menschenopfer und ähnlich schreckliche Dinge gehören zu ihren Ritualen!}
{272}{}{Ja, das stimmt. Was ist daran so schlimm?}
{273}{}{Als MITGLIED der Brotherhood kann ich VERSICHERN, daß NICHTS dergleichen wahr ist!}
{274}{}{Wirklich? Ich bin dort gewesen. Sie sind zwar seltsam, aber nicht so schrecklich.}
{275}{}{Wirklich? Ich hatte ja keine Ahnung.}
{276}{}{Als ob du es nicht wüßtest! Du bist doch auch einer von ihnen mit deinem Metallanzug! Ihr seid doch alle krank!}
{277}{}{Ich weiß nicht, auf was du hinauswillst, aber ich kann dir versichern, daß in der Brotherhood nichts 'Krankes' vor sich geht.}
{278}{}{Tja, sind wir das nicht alle?}
{279}{}{Ich hatte ja keine Ahnung.}
{280}{}{Entschuldigung, aber bitte leg deine Waffe ab.}
{281}{}{Entschuldigung, aber bitte leg deine Waffe ab.}
{282}{}{Tut mir leid, aber solange du deine Waffe nicht ablegst, kann ich dir nicht helfen. Dies ist ein Laden, keine Arena!}
{283}{}{Ohh ... ach ja ... hmm ... Du ... Ich ... Brauchst du sonst noch was?}
{284}{}{Man weiß nie, wie sich jemand wirklich hinter verschlossenen Türen verhält. Man muß immer vorsichtig sein, auf wen man sich einläßt. Brauchst du sonst noch was?}
# Not believing the player for a moment, then getting nervous
{285}{}{Du bist ein ...? Ich mein', ich wollte damit nicht sagen ... Hmm ... Schöner Tag heute, nicht? Kann ich sonst noch was für dich tun?}
{286}{}{Noch eine Frage zu den verschwundenen Caravans ...}
{287}{}{Danke. Jetzt aber zurück zu den Händlern ...}
{288}{}{Nein, das war's. Tschüß dann!}
{289}{}{Klar, wie du willst. Kann ich sonst noch was für dich tun?}
{290}{}{Klasse! Ich zeig' dir, was ich habe.}
{291}{}{Ich hab' die besten Waren. Nach was hältst du denn Ausschau?}
{292}{}{Das hör' ich gern! Was brauchst du?}
{293}{}{Nun zum Geschäft.}
{294}{}{Wenn du Geld hast, hast du meine volle Aufmerksamkeit.}
{295}{}{Das sind meine liebsten Kunden!}
{296}{}{Du möchtest was kaufen? Vielleicht hab' ich mich in dir getäuscht.}
{297}{}{Ja, das stimmt. Du arbeitest für Butch, du bekommst also 15 % Rabatt.}
{298}{}{Ich geb' dir trotzdem 15 % Rabatt, weil du mir sympathisch bist.}
{299}{}{Tut mir leid, aber du kriegst keinen Rabatt mehr.}
{300}{}{Zeig mir, was du alles hast.}
{301}{}{Hast du irgend etwas Nützliches?}
{302}{}{Hmm, mal sehen.}
{303}{}{Klar.}
{304}{}{Was hast du heute für mich?}
{305}{}{Klasse! Waren kann ich immer gebrauchen.}
{306}{}{Ich würde mir gerne ansehen, was du so alles hast.}
{307}{}{Versuch nicht, mich übers Ohr zu hauen.}
{308}{}{Vielleicht kauf' ich dir ja was ab, wenn es was taugt.}
{309}{}{Verschwende nicht meine Zeit.}
{310}{}{Ich hoffe, du hast diesmal was Brauchbares.}
{311}{}{Hallo! Schön, dich wiederzusehen. Womit kann ich an diesem schönen Tag dienen?}
{312}{}{Hallo! Schön, dich wiederzusehen. Womit kann ich heute dienen?}
{313}{}{Ich wünschte, ich hätte einen Tag frei, es ist so schön draußen.}
{314}{}{Hallo! Sehen wir nicht heute blendend aus?}
{315}{}{So schnell wieder zurück?}
{316}{}{Du bist doch gerade erst aufgebrochen. Vermißt du mich schon?}
{317}{}{Ich brauch' jetzt schon was.}
{318}{}{Lange nicht mehr gesehen! Womit kann ich heute dienen?}
{319}{}{Lange nicht mehr gesehen! Ich hoffe, dir geht's gut.}
{320}{}{Noch am Leben, wie's scheint. Ich hab' mir schon Sorgen gemacht. Womit kann ich heute dienen?}
{321}{}{Da bist du ja endlich! Ist schon über 'ne Woche her, seit du das letzte Mal hier warst. Wir müssen unbedingt in Kontakt bleiben, du BIST mein Lieblingskunde!}
{322}{}{Ja?}
{323}{}{Was?}
{324}{}{Willst du was kaufen oder was?}
{325}{}{Das ist mein Laden, benimm dich also besser!}
{326}{}{Was gibt's?}
{327}{}{Du schon wieder?}
{328}{}{Zeit ist Geld, also was gibt's?}
{329}{}{Brauchst du was?}
{330}{}{Hast du das gehört? Er ist tot! Ich bin begeistert! Das ist das Beste, was dieser Stadt je passiert ist.}
{331}{}{Ich hab's dir ja schon gesagt. Er ist tot! Vergessen wir ihn einfach. Sein Name weckt nur schlechte Erinnerungen.}
{332}{}{Oh, ja.}
{333}{}{Ja, er hat es verdient, und es tut mir nicht leid, daß ich's getan habe.}
# Sid works for Beth. Sid is male.
{334}{}{Du hast es getan? Wirklich? Ich liebe dich! [Beth schaut zu Sid rüber.] Denk erst gar nicht weiter drüber nach, mein Lieber ... Hier ein Zeichen meiner Dankbarkeit ... [Beth gibt dir sechs Stimpaks.] Es ist nicht viel, aber vielen Dank!}
{335}{}{Du hast es getan? Wirklich? Du bist der Beste! Du kannst dir gar nicht vorstellen, wie glücklich ich war, als ich von seinem Tod erfuhr. Hier, nimm dies ... [Beth gibt dir sechs Stimpaks.] Es ist nicht viel, aber vielen Dank!}
{336}{}{Tut mir leid, aber ich hab' nichts, was dir gefallen könnte.}
{337}{}{Siehst du nichts, was dir gefällt? Ich werd' versuchen, bessere Waren zu bekommen.}
{338}{}{Tut mir leid, wenn dir mein Angebot nicht gefällt, aber ich muß auch an meinen Gewinn denken.}
{339}{}{Willst du denn doch nichts verkaufen? Geht in Ordnung.}
{340}{}{Tut mir leid, daß ich nicht behilflich sein konnte. Schönen Tag noch!}
{341}{}{Vielleicht beim nächsten Mal. Tschüß dann!}
{342}{}{Ich hoffe, ich kann dir das nächste Mal besser helfen.}
{343}{}{Verschwende nicht meine Zeit.}
{344}{}{Wenn du nichts kaufen willst, dann geh bitte.}
{345}{}{Wenn du nichts kaufen willst, dann laß mich bitte in Ruhe.}
{346}{}{Wenn du nichts verkaufen willst, dann geh bitte.}
{347}{}{Laß mich in Ruhe, wenn du nichts verkaufen willst.}
{348}{}{Geh bitte.}
{349}{}{Ich wußte, daß du meine Zeit wieder verschwenden würdest.}
{350}{}{Ich hab' mir schon gedacht, daß du kein Geld hast.}
{351}{}{Danke für das gute Geschäft. Vielleicht geh' ich heute früher nach Hause.}
{352}{}{Du hast mich fast leergekauft!}
{353}{}{Ich hoffe, du kannst das alles tragen!}
{354}{}{Danke, ich hoffe, ich kann das ganze Zeug verkaufen!}
{356}{}{Das sollte sich problemlos verkaufen lassen. Danke.}
{357}{}{Das kann ich gut gebrauchen. Danke.}
{358}{}{Ich hoffe, ich hab' genügend Platz für das alles!}
{359}{}{Vielen Dank auch! Ich wünsch' dir noch einen schönen Tag!}
{360}{}{Danke für das gute Geschäft. Du bist jederzeit willkommen.}
{361}{}{Du bist hier jederzeit willkommen, allerdings nur während der Geschäftszeiten!}
{362}{}{Danke! Und einen schönen Tag noch!}
{363}{}{Auf Wiedersehen! Und danke!}
{364}{}{Das ist alles? Nur Munition? Ich bin enttäuscht. Nächstes Mal mußt du aber mehr ausgeben!}
{365}{}{Du legst einen Munitionsvorrat an? Gute Idee! Man kann nie genug davon haben.}
{366}{}{Nur das Notwendigste, was? Tschüß dann!}
{367}{}{Also, ich hab' nicht damit gerechnet, daß du wirklich was kaufst.}
{368}{}{Danke für das gute Geschäft. Du bist gar nicht so übel.}
{369}{}{Danke für die Waren.}
{370}{}{Schönen Tag noch!}
{371}{}{Tschüß!}
{372}{}{Danke.}
{373}{}{Danke für die Einkäufe. Einen schönen Tag noch!}
{374}{}{Das hab' ich gehört!}
{375}{}{Ohne Scheiß'!}
{376}{}{Sid! Hör auf!}
{377}{}{Ich werd' dir was geben, wenn du nicht den Mund hältst.}
{378}{}{Das hab' ich gehört! Du bist gefeuert!}
{379}{}{Ignorier ihn einfach. Das mach' ich immer so.}
{380}{}{Oh, du bist einfach zum Totlachen, Sid.}
{381}{}{Das hättest du wohl gern.}
{382}{}{Halt's Maul!}
{383}{}{He, rühr dich nicht vom Fleck, Sid.}
{384}{}{Ich denk' nicht so raffiniert.}
{385}{}{Ich schlag' dich blau, wenn du meine Kunden nicht in Ruhe läßt.}
{386}{}{Entschuldigung für meine 'nervige' Wache.}
{387}{}{Du bist so ein Arsch!}
{388}{}{Sid!}
{389}{}{Liebling? Wo hast du diese schrecklichen Ausdrücke her?}
{390}{}{[Beth seufzt.] Ich}
{391}{}{ sollte ihn einsperren, findest du nicht?}
{392}{}{Ich glaub', er ist eifersüchtig!}
{393}{}{Sid! Sei zu den Kunden nicht so unverschämt!}
{394}{}{Kennst du sonst noch jemanden, der Informationen über die Deathclaw haben könnte?}
{395}{}{Tschüß!}
{396}{}{Danke.}
{397}{}{Okay.}
{398}{}{Gibt es in dieser Stadt einen Ort, den ich meiden sollte?}
{399}{}{Oh, ja! Du solltest dem 'Maltese Falcon' so weit wie möglich fernbleiben. Decker und sein schleimiger Schoßhund Kane sind üble Gesellen. Die fressen dich bei lebendigem Leibe, wenn du nicht aufpaßt. Ich würde auch um Lorenzo von der Friendly Lending Company einen weiten Bogen machen.}
