{100}{}{Du siehst eine Wache der Children.}
{101}{}{Phillips! Knallen wir diesen Typen ab!}
{102}{}{Aus meinen Augen!}
{103}{}{Was willst du?}
{104}{}{Erzähl mir was über deine Arbeit.}
{105}{}{Was ist das hier für ein Ort?}
{106}{}{Du weißt nicht zufällig, wo ich einen Steuerchip finden kann?}
{107}{}{Was kannst du mir über einen Mann namens Decker sagen?}
{108}{}{Nette Waffe, die du da hast ...}
{109}{}{Äh ... Milch.}
{110}{}{Ich bin hier der Mann fürs Grobe. Wenn jemand diese Weltraumkadetten blöd anmacht, töte ich ihn. Hast du ein Problem damit?}
{111}{}{Du bist also ein Leibwächter ...}
{112}{}{Für wen arbeitest du?}
{113}{}{Irgendwelche interessanten Neuigkeiten vom Hub?}
{114}{}{Was machst du da?}
{115}{}{Ja, ein großes Problem.}
{116}{}{Kein Problem, mein Freund.}
{117}{}{Etwas, das Heilige Flamme genannt wird. Hör dir diese Scheiße nicht an. Das macht dich krank im Hirn!}
{118}{}{Was hast du mit der Heiligen Flamme zu tun?}
{119}{}{Mann, sind diese Leute blöd!}
{120}{}{Irgendwelche interessanten Neuigkeiten vom Hub?}
{121}{}{Woher kommen diese Typen?}
{122}{}{Steuerchip für Wasser? So wie für Eis? Vielleicht oben in den Bergen.}
{123}{}{Nein, ich mein' den Computerchip zur Steuerung der Trinkwasseranlage.}
{124}{}{Das mein' ich nicht, du Vollidiot!}
{125}{}{Ah, danke. Ich werd' drüber nachdenken.}
{126}{}{Warst du schon mal in den Bergen?}
{127}{}{Ja, ich hab' von ihm gehört. Er soll ein echter Scheißkerl sein, aber er bezahlt seine Rechnungen. Phillips hat schon ein paar mal für ihn gearbeitet.}
{128}{}{Er ist also ein Arschloch?}
{129}{}{Phillips?}
{130}{}{Würdest du einen Job von ihm annehmen?}
{131}{}{Danke!}
{132}{}{Ja, die einzige, auf die ich mich verlassen kann. Was kann ich für dich tun?}
{133}{}{Wo kann man hier gute Waffen bekommen?}
{134}{}{Was hat es mit diesen Cathedral-Typen auf sich?}
{135}{}{Wo ist hier was los?}
{136}{}{Du weißt nicht zufällig, wo ich einen Steuerchip finden kann?}
{137}{}{Was kannst du mir über einen Mann namens Decker sagen?}
{138}{}{Tut mir leid, Kumpel, aber ich bin im Dienst. Keine Zeit zum Quatschen.}
{139}{}{Scher dich zum Teufel, sonst bring' ich dich um.}
{140}{}{Genau, du Klugscheißer! Wer könnte ich noch sein, Doc Morbid? Hm!}
{141}{}{Die Priesterschlampe. An wen hast du denn noch gedacht? Hm!}
{142}{}{Ich geb's nur ungern zu, aber ich war schon seit Wochen nicht mehr auf der Piste. Frag besser jemand anderen.}
{143}{}{Kost und Logie, sonst nichts. Diese religiösen Typen sind wirklich billig!}
{144}{}{Dann lass es uns angehen!}
{145}{}{Gut. Denn niemand will hier Probleme haben.}
{146}{}{Das muss eine Verarschung sein. So blöd kann doch keiner sein, dass er an diese ganze religiöse Scheiße glaubt, oder?}
{147}{}{Zum Glück werde ich nicht dafür bezahlt, ihrer Meinung zu sein. Ich scheiß' auf die Heilige Flamme!}
{148}{}{Keine Ahnung. Eins kann ich dir aber sagen: Was man auch immer über Religion sagen mag, sie sind keine Amateure. Sie haben diesen Ort genau organisiert. Das sind keine hirnlosen Zombies!}
{149}{}{He, ich dachte, nur Vaults benutzen diese Scheiße!}
{150}{}{Pass auf, was du sagst, du Arschloch. Diese Typen mögen ja an Frieden und Liebe glauben, ich aber nicht!}
{151}{}{Kein Problem.}
{152}{}{Nee. Je höher man klettert, desto schlimmer wird die Strahlung.}
{153}{}{Uh, wenn du auf eiskalte, abgedrehte Dreckskerle stehst, dann ist er genau der Richtige.}
{154}{}{Mein Partner. Der Typ, der auf Jain aufpasst.}
{155}{}{Kommt ganz drauf an, welches Risiko du eingehen willst. Ich hatte in letzter Zeit viel um die Ohren, deshalb bin ich hierhergekomemn, um mich auszuruhen. Aber wenn du was erleben willst, bitte. Bau nur keinen Mist, sonst bist du tot. Das ist alles.}
{156}{}{Ich hab' gehört, die Water Merchants nehmen sich immer das Beste. Aber die Leute erzählen ja alles Mögliche über die Water Merchants. Nicht diese Leute hier, das ist klar.}
{157}{}{Ich versuche schon seit Wochen, diese Typen zu durchschauen. Zuerst hab' ich sie für Idioten gehalten ... aber jetzt ... Sie sind organisiert, und sie haben einen Plan. Das spür' ich!}
{158}{}{Ich hab' gehört, dass man bei Decker was erleben kann, aber ich sag' dir, das ist Scheißarbeit, und wenn du Mist baust, bist du so gut wie tot.}
{159}{}{Chip zur Wassereinigung? Benutzt ihr denn kein Brunnenwasser? Mein Gott! Ich hab' von einer Vault in der Nähe von Shady Sands gehört, wo du vielleicht einen finden kannst, aber dieser Ort ist total abgeschottet. Ich glaub', ich kann dir da nicht weiterhelfen.}
{160}{}{Ich kann nicht reden. Der Boss mag das nicht. Tut mir leid.}
{161}{}{He, du!}
{162}{}{He! Was glaubst du eigentlich, was du da machst?}
{163}{}{Wazu das Schloss?}
{164}{}{He, ich geh' ja schon!}
{165}{}{Kannst du mir mit dieser Tür helfen? Sie klemmt!}
{166}{}{Du hast mich gesehen! Schade für dich ...}
{167}{}{Geht dich nichts an! Hau ab!}
{168}{}{Gut! Jetzt hau aber ab!}
{169}{}{Verschwinde! Wenn du noch mal so einen Mist machst, bring' ich dich persönlich um!}
{170}{}{Wir sollen nicht mit dir sprechen. Mach dich aus dem Staub, Kumpel!}
{171}{}{He! Was glaubst du eigentlich, was du da machst?}
{172}{}{Wozu das Schloss?}
{173}{}{He, ich geh' ja schon!}
{174}{}{Kannst du mir mit dieser Tür helfen? Sie klemmt!}
{175}{}{Du hast mich gesehen! Schade für dich ...}
{176}{}{Geht dich nichts an! Hau ab!}
{177}{}{Gut! Jetzt hau aber ab!}
{178}{}{Verschwinde! Wenn du noch mal so einen Mist machst, bring' ich dich persönlich um!}
