# These are various People combined into one file.
# They are split into the groups of what they are.

################
# Flat monotonic people. Nothing interesting. they are apathic.
{106}{}{Du siehst eine Frau.}
{107}{}{Du siehst einen Mann.}

################
# The drunk has slurred speech. he's been hitting the booze a bit too hard
# and is having problems standing and remembering his name

{100}{}{Du siehst einen Betrunkenen.}
{110}{}{Lass mich mit meinen Sorgen allein!}
{111}{}{Bischt mein beschter Freund ... hick.}
# best friend (slurred)

{112}{}{Warum bist du ... hick ... Wo bin ich?}
{113}{}{Wer bist du?}
{114}{}{Kennen wir uns?}
{115}{}{Mir ist ein bisschen übel.}
{116}{}{Geht alles auf mich ... hick ... dich.}
{117}{}{Warum gibt's dich zweimal?}
{118}{}{Bleib stehen, Junge!}
# laddy is male

{119}{}{Bleib stehen, Mädchen!}

#################
# Customer and gamble are both genders. Consider male for translation. They are agitated, yet happy to
# be spending all their money. Consider the people in Las Vegas gambling away their money.

{101}{}{Du siehst einen Kunden.}
{104}{}{Du siehst einen Spieler.}
{120}{}{Hau ab, du Niete!}
# == "Get out of here loser"

{121}{}{Du bist rufschädigend für diesen Laden.}
# == "you are dropping the class of this place"

{122}{}{Hau ab, du bringst mir nur Pech!}
# == "get away. you will bring me bad luck"

{123}{}{Stör mich nicht, ich muss mich konzentrieren.}
{124}{}{Ich werd' in diesem verfluchten Spiel noch gewinnen!}
{125}{}{Kannst du das?}
{126}{}{Hast du das gesehen? Das war unglaublich!}
# referring to dice roll

{127}{}{Ich glaub', die bescheißen.}
# they is referring to the owners of the Maltese Falcon, the drinking/gambling establishment
# They is Male

{128}{}{Die Chancen stehen gut.}
{129}{}{Eine todsichere Sache.}
# referring to a bet.

{130}{}{Was? Wie konnte ich verlieren?}
{131}{}{Auf diesem Tisch liegt ein Fluch!}
# == "this table is cursed/unlucky"

{132}{}{Ich hab' zu tun.}
{133}{}{Siehst du nicht, dass ich hier spiele?}
{134}{}{Spiel mit oder hau ab!}

#################
# This is a sleazy prostitute who will have sex with anyone who will give
# her $20. She will be talking a sexy, but lewd voice.

{102}{}{Du siehst eine sehr hübsche Frau.}
{105}{}{Du siehst eine Frau. Sie scheint beschäftigt zu sein.}
{135}{}{Lass uns in Ruhe, oder ich ruf' die Wachen.}
{136}{}{Pass auf! Ich bin mit Deputy Fry eng befreundet.}
{137}{}{Was dagegen?}
{138}{}{Keine Peep-Shows!}
# == "I don't allow people to watch me having sex with someone else."

{139}{}{Gruppen nehm' ich nicht.}
# == "I don't have sex with more than one person."

{140}{}{Ich bin zu müde für noch 'ne Runde.}
# referring to having another round of sex.

{141}{}{Du träumst, Junge! Hau ab!}
{142}{}{Scher dich zum Teufel!}
{143}{}{Was zum Teufel machst du da?}
{144}{}{Reiß dich mal zusammen!}
{145}{}{Ich ruf' die Polizei!}
{146}{}{Komm bloß nicht auf die Idee ...}
{147}{}{Raus!}
{148}{}{Hau ab!}
{149}{}{Was glotzt du so blöd?}
{150}{}{Was dagegen?}

#####################
# This is a customer for the Hooker. Gender is male. He is aburpt and is really not
# interested in the player, only having sex with the prostitute

{109}{}{Du siehst einen Söldner.}
{151}{}{Raus aus unserem Zimmer!}
{152}{}{Hau ab!}
{153}{}{Gehörst du auch dazu?}
# == "are you part of the group of three/threesome/orgy"

{154}{}{Hau ab, du perverses Schwein!}
# == "get out of here, perverse person"

{155}{}{Was ist mit dir los?}
{156}{}{Hau ab, bevor ich wütend werde!}
# "Beat it" == "get out of here"

{157}{}{Such dir deine eigene!}
# ==  "get your own hooker"

{158}{}{Das ist meine.}
# "She" is referring to the hooker.

######################
# Gambler is Male. The gambler has lost a lot of money and is really upset about
# having done so.

{108}{}{Du siehst einen ziemlich aufgebrachten Spieler.}
{159}{}{Verflucht!}
{160}{}{Bescheißt du?}
# referring to the player

{161}{}{Das war eigentlich für mich gedacht.}
# someone else won a bet, this person thinks they should have won instead

{162}{}{Fast!}
# nearly got his number on the roulette wheel

{163}{}{Knapp vorbei.}
# pulled up a 19 to the dealers 20 in blackjack

{164}{}{Wie waren die Regeln noch mal?}
# in referrence to a gambling game

{165}{}{Ich war da mal echt gut drin.}
# in referrence to a gambling game

{166}{}{Keine Ursache!}
{167}{}{Ich glaub's einfach nicht!}
{168}{}{Das war Absicht!}
# he meant to lose.

######################
# This is the dealer/roulette shooter for the casino. Monotonic voice and trying to
# pretend to be happy about being here.

{103}{}{Du siehst einen seltsamen Mann.}
{169}{}{Ihr Einsatz, bitte.}
{170}{}{Hände weg, bitte!}
# in referrence to taking money from the table while the bet is going on

{171}{}{Gewonnen!}
{172}{}{Vielleicht habt ihr beim nächsten Mal mehr Glück ...}
# maybe next time someone can win

{173}{}{Noch ein Gewinner!}
{174}{}{Hände weg!}
# don't take the dice off the table while someone is rolling them

{175}{}{Ihr Einsatz, bitte.}
# your turn to bet
{176}{}{Tut mir leid, aber das ist nicht erlaubt.}
{177}{}{Das war's.}
{178}{}{Noch jemand?}
