{100}{}{Vor dir siehst du einen Würfelspieltisch. Mindesteinsatz ist 40 Dollar.}
{101}{}{Du hast eine 7 gewürfelt. Du hast gewonnen!}
{102}{}{Du hast Schlangenaugen gewürfelt. Du hast verloren.}
{103}{}{Du hast eine }
{104}{}{ gewürfelt. Du hast gewonnen!}
{105}{}{Du hast eine }
{106}{}{ gewürfelt. Du hast verloren.}
{107}{}{Du hast eine }
{108}{}{ gewürfelt und keinen Punkt gemacht. Du hast verloren.}
{109}{}{Du hast einen Punkt gemacht. Du hast gewonnen!}
{110}{}{Du hast eine }
{111}{}{ gewürfelt und einen Punkt gemacht. Würfel noch einmal!}
{112}{}{Du erhältst 70 Erfahrungspunkte, weil du den Croupier umgelegt hast.}
