{100}{}{Du siehst Daren Hightower.}
{101}{}{Wer bist du?!? Und wer hat dich reingelassen?}
{102}{}{Ich habe eine Nachricht von einem Freund.}
{103}{}{Dein Leben ist in Gefahr, ich muß mit dir reden.}
{104}{}{Ich heiße }
{105}{}{. Leon hat mich reingelassen.}
{106}{}{Mein Name? Tod!}
{107}{}{Ich bin dein schlimmster Alptraum!}
{108}{}{Bobo?}
{109}{}{Ich habe keine Freunde. Wie lautet die Nachricht?}
{110}{}{Decker läßt dich grüßen.}
{111}{}{Äh ... Bob schickt mich ... äh ... er sagt, daß du ihm 100 Deckel zuviel gezahlt hast, und ich soll sie dir geben.}
{112}{}{Es gibt eigentlich keine Nachricht, ich wollte mich nur rausreden.}
{113}{}{Ich liebe dich!}
{114}{}{Laß dir was Neues einfallen, du Schwachkopf!}
{115}{}{Schwachkopf? Ich wollte dir helfen. Zum Teufel mit dir!}
{116}{}{Decker will deinen Tod und hat mich dafür engagiert.}
{117}{}{Du weißt offenbar nicht, daß du gleich sterben wirst!}
{118}{}{Vergiß es! Ich wollte nur helfen.}
{119}{}{War nett, dich kennenzulernen, }
{120}{}{. Mein Assistent Leon führt dich jetzt nach draußen.}
{121}{}{Ich kenne keinen Bob, aber ich nehm' die 100 Deckel, und du kannst abhauen.}
{122}{}{Zum Teufel mit dir!}
{123}{}{Okay, bitte schön. Danke für deine Zeit.}
{124}{}{Ähh ... Dieses SCHWEIN Bob hat mir nicht genug Deckel gegeben! Ich hol sie schnell, Mr. Hightower, ganz ehrlich!}
{125}{}{Ha! Ich mag es, wenn Fremde hereinspazieren und mir Geld geben. Leon, zeig diesem Dummkopf die Tür! Wenn du noch einmal kommst, bringen mir meine Wachen deinen Kopf!}
{126}{}{Leon, zeig diesem Dummkopf die Tür! Wenn du noch einmal kommst, bringen mir meine Wachen deinen Kopf!}
{127}{}{Wachen! Mörder!}
