{100}{}{Was willst du?}
{101}{}{Laß mich in Ruhe!}
{102}{}{Waaas?}
{103}{}{Pack meine Sachen nich' an.}
{104}{}{Hi.}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Uungh.}
{108}{}{Uhh.}
{109}{}{Hey, hast du gehört, dass Set ausgeknipst wurde?}
{110}{}{Set ist tod. Set ist tod. Set ist tod...}
{111}{}{Es gibt genug Wasser für alle hier, Set sorgt schon dafür.}
{112}{}{Ich habe gehört, dass die Mutanten aus der Stadt vertrieben wurden.}
{113}{}{Seit die Mutanten weg sind, ist es besser.}
{114}{}{Hallo.}
{200}{}{Du untersuchst das bedauernswerte Geschöpf, kannst aber nicht herausfinden, was es zu dem gemacht hat, was es jetzt ist.}
{201}{}{Es scheint einmal ein Mensch gewesen zu sein oder zumindest vom Menschen abzustammen. Du vermutest, daß der schlechte Zustand des Körpers auf Säure oder Strahlung zurückzuführen ist.}
{202}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt, aber dennoch funktionsfähig zu sein. Auch wenn es einmal ein Mensch gewesen ist, scheint es doch eher wie ein Tier gelebt zu haben.}
{203}{}{Der Körper des menschenähnlichen Wesens scheint stark verstrahlt und der Großteil der Muskel- und Hirnmasse zerstört zu sein. Genetische Merkmale sprechen deiner Meinung nach dafür, daß es wie du von Vaultbewohnern abstammt.}
