{100}{}{Du siehst Leon, eine Wache.}
{101}{}{Was führt dich hierher?}
{102}{}{Ich muß mit Mr. Hightower reden.}
{103}{}{Ich möchte gerne Mr. Hightower umbringen.}
{104}{}{Und was geht dich das an?}
{105}{}{Okay, aber ich behalte dich im Auge. Er ist in seinem Büro.}
{106}{}{Danke schön.}
{107}{}{Ja ... Darauf hätte ich wetten können.}
{108}{}{Ich mag deine Art nicht. Ich muß dich bitten, zu gehen.}
{109}{}{Ich geh', wenn ich dazu Lust und Laune hab', Alter!}
{110}{}{Okay, ich gehe.}
{111}{}{Meine Art? Ich zeig' dir meine Art!!!}
{112}{}{Du kannst auch mit mir reden. Mr. Hightower ist gerade beschäftigt.}
{113}{}{Warum mußt du solche Schwierigkeiten machen?}
{114}{}{Ich würde lieber persönlich mit ihm reden. Es geht um Leben und Tod.}
{115}{}{Decker hat eine Belohnung auf Hightowers Leben ausgesetzt.}
{116}{}{Entweder erzählst du es mir, oder du verschwindest.}
{117}{}{Wer ist gestorben und hat dich zum Gott gemacht?}
{118}{}{Decker hat eine Belohnung auf Hightowers Leben ausgesetzt.}
{119}{}{Hör mal, ich werde dir absolut nichts erzählen!}
{120}{}{Ich gehe.}
{121}{}{Schon wieder? Decker ist doch ein Idiot. Also? Ich glaube, er ist nicht so dumm wie die Leute, die er für diese Jobs anwirbt. Sieh mal, das hier ist meine Waffe.}
{122}{}{[Leon zeigt dir die Seite seines Revolvers, wo fünf tiefe Kerben zu sehen sind.]}
{123}{}{Jede dieser Kerben steht für ein Attentat auf Hightower. Ich habe jeden einzelnen erwischt. Erzähl mal ... Weißt du, wie dieser Schwachkopf, den Decker engagiert hat, aussieht?}
{124}{}{Nö.}
{125}{}{Ich bin's, du Idiot!}
{126}{}{He! Wau! Du hast ja tolle Kratzer auf deinem Gewehr! Du bist echt cooool!}
{127}{}{Danke für die Vorwarnung, doch Mr. Hightower mag es nicht, wenn Fremde herumlungern. Ich muß dich bitten, zu gehen.}
{128}{}{Das war's? Keine Belohnung? Was ist denn mit euch los?}
{129}{}{Gern geschehen. Tschüß dann!}
{130}{}{Mr. Hightower empfängt keine Besucher. Geh jetzt!}
{131}{}{Ich geh', wenn ich dazu Lust und Laune hab', Alter!}
{132}{}{Okay, ich geh' dann.}
{133}{}{Ich muß wirklich mit Mr. Hightower reden.}
{134}{}{Okay, Kumpel. Gehen wir. [Leon greift dich am Arm.]}
{135}{}{Nimm deine Pfoten da weg!}
{136}{}{Schon gut, schon gut! Ich geh' ja.}
{137}{}{Warte! Ich bin noch nicht fertig!}
{138}{}{Arg!}
{139}{}{Ruk!}
{140}{}{Ich hab' dringende Nachrichten für Mr. Hightower.}
{141}{}{Was machst du hier? Ich habe keinen Dienst mehr. Belästige jetzt jemand anderes.}
{142}{}{Ich hatte gehofft, daß deine traurige Gestalt hier einmal herumirrt! Wachen!!!}
