{100}{}{Du siehst einen Hub-Bewohner.}
{101}{}{Wau! Ich hab' gehört, du hast die Deathclaw getötet. Gute Arbeit!}
{102}{}{Stimmt das? Gibt ... gab es die Deathclaw wirklich?}
{103}{}{Ich hab' gehört, du bist }
{104}{}{ der Mann, der}
{105}{}{ die Frau, die}
{106}{}{ die Deathclaw getötet hat. Gute Arbeit!}
{107}{}{Danke, daß du uns von diesem Alptraum befreit hast. Jetzt können wir alle wieder besser schlafen.}
{108}{}{Hoffentlich ist diese Deathclaw auch wirklich tot.}
{109}{}{Hoffentlich suchen diese Mutanten, die die Caravans zerstört haben, nicht nach uns.}
