{100}{}{Du siehst einen Caravan-Fahrer.}
{101}{}{Wird 'n langer Tag heute!}
{102}{}{Hab' heute wirklich keinen Bock zu arbeiten.}
{103}{}{Hoffentlich werden wir nicht überfallen ... oder schlimmer.}
{104}{}{Tut mir leid, aber ich glaub', wir brauchen keine Wachen mehr ...}
{105}{}{Tut mir leid, aber wir haben schon genug.}
{106}{}{Geh doch mal zum Merchant Market, wenn du 'nen Job suchst.}
{107}{}{Hoffentlich können wir alles verkaufen.}
{108}{}{Ich will das endlich hinter mich bringen.}
{109}{}{Ich bin bereit für 'ne Prügelei.}
{110}{}{Nichts wie weg!}
{111}{}{Das war ein heißer Tag heute.}
{112}{}{Mann, hab' ich 'nen Durst.}
{113}{}{Was für ein Tag ist heute?}
{114}{}{Wenn ich hier fertig bin, geht's ab in den 'Falcon'!}
{115}{}{Tut mir leid, aber wir sind gerade erst von 'ner Tour zurückgekommen.}
{116}{}{Geh doch mal zum Merchant Market, wenn du 'nen Job suchst.}
{117}{}{Heute gibt's Kohle!}
{118}{}{Gleich geht's ab zu 'Bob's'!}
{119}{}{Ich muss heute den Kredit zurückzahlen!}
{120}{}{Ich bin so müde.}
{121}{}{War das 'ne lange Fahrt!}
