{100}{}{Du siehst ein Blumenkind.}
{101}{}{Hallo! Würdest du ... Oh, Entschuldigung ...}
{102}{}{Du! Ich hab' von dir gehört! Du sollst ganz grausam sein! Mutter Jain! Mutter Jain! Hilfe!}
{103}{}{Möchtest du eine Blume?}
{104}{}{Möchtest du eine Blume?}
{105}{}{Leer}
{106}{}{Gibt es an diesem Ort irgendwas Besonderes?}
{107}{}{Was ist so besonders an dieser Blume?}
{108}{}{Was verlangst du dafür?}
{109}{}{Aber klar!}
{110}{}{Nein, danke.}
{111}{}{Klar! Sie zu zertreten, würde mir wirklich Spaß machen!}
{112}{}{Schnüffel ... Riecht gut!}
{113}{}{Schnüffel ... Riecht pfui!}
{114}{}{Du Dummkopf! Du hast doch schon eine Blume!}
{115}{}{Willst du eine Blume oder nicht?}
{116}{}{Ich nehme eine Blume, wenn du mir ein bißchen über diesen Ort erzählst.}
{117}{}{Was ist so besonders an dieser Blume?}
{118}{}{Aber klar!}
{119}{}{Genug von der blöden Blume. Beantworte meine Frage!}
{120}{}{}
{121}{}{Es ist eine Einheitsrose. Sie hat die Farbe der Heiligen Flamme und steht für den Frieden und die Harmonie, die wir haben werden, wenn die Children of the Cathedral jedem in der Welt helfen, freundlich und stark zu werden! Äh, willst du eine?}
{122}{}{}
{123}{}{Wie soll denn eine Rose das alles schaffen?}
{124}{}{Erzähl mir von der Heiligen Flamme ...}
{125}{}{Was soll sie denn kosten?}
{126}{}{Aber klar!}
{127}{}{}
{128}{}{Paß auf, ich will deine blöde Blume nicht.}
{129}{}{Sie ist umsonst. Wir glauben nicht an Geld. Die Heilige Flamme sorgt für uns! Es ist so wunderbar! Du solltest unserer Cathedral of Happiness beitreten! Äh, willst du eine?}
{130}{}{Erzähl mir über die Cathedral ...}
{131}{}{Erzähl mir über die Heilige Flamme ...}
{132}{}{Aber klar!}
{133}{}{}
{134}{}{}
{135}{}{Danke, oh, danke! Ich habe eine Blume verschenkt! Ist das nicht toll ...}
{136}{}{Du bist gemein! Ich hasse dich! Hoffentlich frißt dich die Heilige Flamme!}
{137}{}{Aber natürlich! Nimm eine! Ich habe eine Blume verschenkt! Ist das nicht toll ...}
{138}{}{Du bist dumm! Hoffentlich tötet dich die Heilige Flamme, bevor du noch mehr dummes Zeug sagst. Mutter Jain, paß auf den dummen Typ auf!}
{139}{}{Wir sind die Children of the Cathedral. Die Heilige Flamme selbst befiehlt uns, die Hungrigen zu speisen und die Kranken zu heilen. Wir werden Frieden und Einheit überallhin bringen ... und alles wird gaaaanz toll! Da! Nimm deine Blume!}
{140}{}{Ich glaube, du willst gar keine Blume. Du bist gemein zu mir!}
{141}{}{Rosen können das nicht, du Dummkopf! Nur Menschen können die Welt ändern. Und mit der Heiligen Flamme als unserem Meister machen wir alles schön und besonders! Willst du jetzt eine Blume ...}
{142}{}{Erzähl mir über die Cathedral ...}
{143}{}{Erzähl mir über die Heilige Flamme ...}
{144}{}{Aber klar!}
{145}{}{Nein, danke.}
{146}{}{Ich zeig dir, wer dumm ist, du kleines ...}
{147}{}{Das ist das Feuer, das die Welt gereinigt hat, und wenn wir ihm gehorchen, macht es das nie wieder! Es will, daß wir klug und friedlich und vereint sind und so'n Zeugs! Willst du jetzt eine Blume?}
{148}{}{Erzähl mir über diese Einheit ...}
{149}{}{Aber klar!}
{150}{}{Nein, danke.}
{151}{}{Genug von der blöden Blume!}
{152}{}{Das ist ein wunderschöner Ort am Meer, wo die Leute die ganze Zeit die Heilige Flamme verehren und gut sind. Und jeder dort ist nett, außer vielleicht Pater Lasher. Äh ... möchtest du eine Blume?}
{153}{}{Erzähl mir über Pater Lasher ...}
{154}{}{Aber klar!}
{155}{}{Nein, danke.}
{156}{}{Genug von der blöden Blume!}
