{100}{}{Du siehst eine Hub-Wache.}
{101}{}{Kann ich dir helfen?}
{102}{}{Ja. Kannst du mir sagen, wo ich bin?}
{103}{}{Tschüß!}
{104}{}{Ähh. Häh. Ähh. Häh.}
{105}{}{Mann, bist du blöder als ein Sack voll Nägel? Hau bloß ab!}
{106}{}{Du bist am südlichen Ende des Hubs. Wenn du dich umguckst, siehst du die Water Merchants und ein kleines Krankenhaus.}
{107}{}{Wer sind die Water Merchants?}
{108}{}{Ein Krankenhaus?}
{109}{}{Danke schön. Tschüß dann!}
{110}{}{Schweine! Die glauben, daß ihnen der ganze Hub gehört, nur weil sie den Wasserturm unter Kontrolle haben.}
{111}{}{Ein Krankenhaus?}
{112}{}{Danke schön. Tschüß dann!}
{113}{}{Die Children of the Cathedral führen ein kleines Krankenhaus hier im Hub. Die scheinen ganz okay zu sein.}
{114}{}{Wer sind die Water Merchants?}
{115}{}{Danke schön. Tschüß dann!}
