{100}{}{Du siehst einen eindringenden Supermutanten.}
{101}{}{Hierher, Mensch!}
{102}{}{Halt!}

{103}{}{Stirb, Mensch!}
{104}{}{Stirb!}
{105}{}{Meee-eensch!}
{106}{}{Ich dich zerquetschen jetzt!}
{107}{}{Alle Normalos werden sterben!}
