{100}{}{Du siehst Irwin.}
{101}{}{Ach Junge, kannst du mich nicht in Ruhe lassen? Ich hab' schon genug Probleme.}
{102}{}{Probleme? Vielleicht kann ich helfen.}
{103}{}{Als ob nur du Probleme hättest.}
{104}{}{Okay, okay. Mußt mich ja nicht gleich anbrüllen.}
{105}{}{Hmm ... Ich weiß nicht. Ich brauch' 'ne andere Sorte Held als dich. Hör mal, warum kommst du nicht wieder, wenn du ein bißchen Erfahrung gesammelt hast?}
{106}{}{Es ist eine Tragödie, kannst du mir glauben. Nichts ist so, wie es mal war. Ich habe 'nen kleinen Bauernhof vor der Stadt, und vor ein paar Tagen ist ein Haufen Raiders aufgekreuzt und benutzt mein Heim jetzt als Lager. Sie haben Pugsley, meinen Esel, getötet und mir gedroht, daß sie mit mir dasselbe machen, wenn ich es wage zurückzukehren.}
{107}{}{Sag mir wo, und ich kümmer' mich um den Rest.}
{108}{}{Tut mir leid, Irwin, aber ich habe Wichtigeres zu tun.}
{109}{}{Wirklich, würdest du das tun? Weißt du, ich trau' mich nicht mehr zurück. Warum kommst du nicht wieder und sagst mir, wenn ich wieder sicher nach Hause kann?}
{110}{}{Hör zu, du Typ! Ich hab' von Anfang an gesagt, daß du mich in Ruhe lassen sollst. Jetzt hau ab!}
{111}{}{Ich hab' gewußt, daß du kneifst. Jeder kneift vor den Raiders.}
{112}{}{Hast du den Raiders eine Lektion erteilt? Ist mein Zuhause wieder sicher?}
{113}{}{Aber klar doch, Kumpel!}
{114}{}{Ich hatte noch nicht die Zeit, mich darum zu kümmern.}
{115}{}{Oh, herzlichsten Dank. Ich kann dir leider keine Reichtümer schenken, aber da, nimm das Gewehr als Belohnung dafür, daß du mein Heim gerettet hast.}
{116}{}{Du willst mich auf den Arm nehmen, stimmt's? Spiel bitte nicht mit mir. Komm zurück und sag's mir, wenn ich wieder sicher nach Hause kann, okay?}
{117}{}{Vielen Dank, daß du mir hilfst.}

# Nimrod
{200}{}{Du erhältst }
{201}{}{ Erfahrungspunkte dafür, dass du Irwin's Farm gerettet hast.}

#for Stupid characters
{118}{}{Grunk?}
{119}{}{Hör zu, ich habe keine Zeit für Idioten. Komm zurück, wenn du schlauer bist.}
{120}{}{Äh. Häh. Äh. Häh. Getan.}
{121}{}{Ich noch nichts gemacht.}
{123}{}{Nicht finde Farm. Du zeigen?}
{403}{}{Dank-e!}

# the Raiders at his farm
{300}{}{Tritt vor deinen Schöpfer!}
{301}{}{Schnappt ihn ... tot!}
{302}{}{Da war dein letztes Käsebrot!}
{303}{}{Gleich siehst du aus wie Schweizer Käse, voller Löcher!}

# TODO: TRANSLATE
# Sduibek
{400}{}{Not quite. Could you tell me again how to get there?}
{401}{}{I will, but please hurry. I want to go back to my home.}
{402}{}{Danke.}

# Fo1in2:
{2000}{}{First, right after leaving the Hub you will follow the main road eastwards for a few miles, past the old rail road station. Then circle down south, you will find the old Cooper farm (you can't miss it). Walk right past it, and then ... }
{2001}{}{[More]}
{2002}{}{[Irwine explains the directions in great detail. So much so, you're almost falling asleep. Minutes go by till you finally plotted the directions on your PipBoy]}
# Floats, Irwine is back at his farm:
{2500}{}{Thank your for giving me my farm back.}
{2501}{}{Thanks again.}
{2502}{}{There is much work to do.}
{2503}{}{These raiders trashed my table.}
{2504}{}{Oh god, will you look at this?}
{2505}{}{Hello.}
{2506}{}{You're still here?}
{2507}{}{Hope you're put that gun to good use!}
{2508}{}{Getting my farm running again will take a while.}
{2509}{}{Good to see you.}
{2510}{}{How's it going?}

