{100}{}{Du siehst einen dünnen, wütend aussehenden Mann.}
{101}{}{Du siehst Ismarc.}
{102}{}{Was ist?}
{103}{}{Ja, was willst du?}
{104}{}{He, gut gesungen!}
{105}{}{Von deinem Gesang krieg' ich Ohrenschmerzen.}
{106}{}{Schon gut.}
{107}{}{Huu!}
{108}{}{Oh, super. Du weißt nicht, wie dankbar mich das macht. Verzieh dich!}
{109}{}{Danke. Was kann ich für dich tun?}
{110}{}{Machst du auch woanders Musik?}
{111}{}{Mir war gerade danach, Geld in den Hut zu werfen ... sozusagen.}
{112}{}{Wo hast du Singen gelernt?}
{113}{}{Danke für deine Zeit.}
{114}{}{Was?!? Dafür habe ich keine Zeit.}
{115}{}{Ja, ich singe manchmal im Hub, und ich habe die Brotherhood of Steel und Adytum mit den Caravans besucht. Warum fragst du?}
{116}{}{Kannst du mir sagen, wie ich zum Hub komme?}
{117}{}{Ich muss wissen, wie man zur Brotherhood kommt.}
{118}{}{Wie kommt man nach Adytum?}
{119}{}{Äh, schon gut, danke.}
{120}{}{Der Hub? Oh, das ist gar nicht weit südlich von Junktown. Noch was?}
{121}{}{Die Brotherhood ist ein paar Tagesreisen nordwestlich von hier. Geh da besser nicht hin! Die lassen dich nur mit einem Caravan rein. Brauchst du noch was?}
{122}{}{Hmm, halte dich südwestlich vom Hub. Adytum ist Teil des Boneyards. Es ist eine kleine Stadt mit ein bisschen Industrie. Mir gefällt's dort nicht besonders. Was brauchst du noch?}
{123}{}{He, danke. Das Leben als hungernder Künstler ist hart. Wenn du was wissen willst, frag einfach.}
{124}{}{Vielen Dank, aber dir geht's doch noch schlechter als mir.}
{125}{}{Ach, das hab' ich da und dort aufgeschnappt. Hab' ein bisschen von einem alten Sänger im Hub gelernt, und ein bisschen Musik bei den Scavengers in Adytum im Boneyard mitbekommen. Weißt schon. Man muss halt ein bisschen üben.}
{126}{}{In der Ecke singt ein Mann falsch.}
{127}{}{Dein Kopf ist eine Schale!}
{128}{}{Er ist rund wie der Mond!}
{129}{}{Ich möcht' lieber kochen!}
{130}{}{Als dir Tribut zu zollen!}
{131}{}{Ich weiß, wie du denkst ...}
{132}{}{Dein Geist ist ein Stahlkäfig ...}
{133}{}{Darin wütet ...}
{134}{}{die Deathclaw ...}
{135}{}{Ich brauche dich ...}
{136}{}{wie eine Dosis Gift ...}
{137}{}{Ich brauche dich ...}
{138}{}{wie den Stich eines Radscorpions!}
