{100}{}{Du siehst Jain.}
{101}{JAIN00}{Warum störst du einen Elder der Cathedral?}
{102}{}{Ich will gesegnet werden.}
{103}{}{Ich interessiere mich für eure Kirche und hätte gern einige Informationen. Habt ihr Flugblätter?}
{104}{}{Ich seh' mich nur um.}
{105}{}{Mutter?}
{106}{JAIN01}{Ich bin wohl kaum deine Mutter!}
{107}{}{Nicht?}
{108}{}{Dumme Nuß!}
{109}{JAIN02}{Wie kannst du es wagen, so mit mir zu sprechen? Du wirst für deine Unverschämtheit büßen! Wachen!}
{110}{JAIN03}{Vielleicht bespricht einer unserer Priester deine nötige Ausbildung mit dir. Geh jetzt!}
{111}{JAIN04}{Hast du die Sakramente gelernt, Kind?}
{112}{}{Ja.}
{113}{}{Nein.}
{114}{JAIN05}{Du solltest wissen, daß die High Elders der Cathedral nicht einfach so Segnungen 'verteilen'. Geh jetzt!}
{115}{JAIN07}{Mach dich weiter über mich lustig, und ich laß dich hinauswerfen!}
{116}{}{Aber ich mach' mich doch gar nicht über dich lustig. Ehrlich.}
{117}{}{Mich über dich lustig machen? Warum sollte ich so was tun?}
{118}{}{Offensichtlich sind Freundlichkeit und Gutmütigkeit nicht Teil dieser Religion.}
{119}{}{Schon gut. Ich denk', ich geh' dann mal.}
{120}{JAIN08}{Für solch ketzerische Worte wirst du bezahlen!}
{121}{JAIN09}{Du sprichst mit falscher Zunge, und deine Worte zeugen von deiner ketzerischen Einstellung. Du wirst geläutert und dann vergessen.}
{122}{JAIN10}{Warum bist du hier? Was führt dich zu den Children of the Cathedral?}
{123}{}{Ich bin wißbegierig und will immer Neues dazulernen.}
{124}{}{Ich wollte nur wissen, wie man diesen Ort am besten niederbrennt. Deshalb hab' ich mich schon mal nach Schwachstellen umgesehen.}
{125}{}{Ich seh' mich nur um.}
{126}{JAIN11}{Bist du ein Child?}
{127}{}{Seh' ich etwa so aus?}
{128}{}{Ich? Ein Child der Children of the Cathedral? Nein!}
{129}{}{Ich bin fromm und gläubig.}
{130}{JAIN12}{Dann solltest du nicht hier sein. Ich verwarne dich wegen deiner Manieren. Hinfort!}
{131}{}{Okay.}
{132}{}{Leck mich!}
{133}{JAIN13}{Würdest du zu unserem Glauben konvertieren? Wir können dir etwas Einzigartiges bieten ...}
{134}{}{Und das wäre?}
{135}{}{Kein Interesse. Ihr seid doch nur eine Bande verrückter Spinner.}
{136}{JAIN14}{Ein Leben lang Zufriedenheit. Erfüllung im Wissen, daß du diesen Planeten neu aufbaust, um ihn in einen besseren Ort zu verwandeln.}
{137}{}{Klingt sehr interessant. Kannst du mir mehr darüber erzählen? Ich such' nämlich Erfüllung.}
{138}{}{Klar, ich wette, ihr seid schon ganz weggetreten vor Erfüllung!}
{139}{}{Glaub' ich nicht dran. Da ist doch irgendwas faul dran.}
{140}{JAIN15}{Glaube, was du willst, aber woanders! Du kannst gehen.}
{141}{JAIN17}{Mach dich nicht über unsere Heilige Sache lustig. Du wirst bestraft, wenn du weitermachst!}
{142}{}{Und wer übernimmt die Bestrafung? Ich hätt' dann gern die extraharte Peitsche, falls es dir nichts ausmacht.}
{143}{}{Tut mir leid.}
{144}{JAIN18}{Wenn die Children ins wiedergeborene Land ziehen, stirbt deine Art aus, Ketzer! Geh jetzt!}
{145}{JAIN19}{Ich bin nicht völlig humorlos, aber die Children anzuführen, ist etwas, das ich ernst nehme. Vergiß das nicht!}
{146}{}{Tut mir leid, aber ich kenn' mich mit den Children nicht so gut aus.}
{147}{}{Okay. Tschüß dann!}
{148}{JAIN20}{Hier ist der Ort der spirituellen Erfüllung. Die Children of the Cathedral suchen eine friedliche Lösung der Probleme unserer Welt und könnten deine Hilfe brauchen.}
{149}{}{Was haben die Children mit den Mutanten vor?}
{150}{}{Wie können die Children Frieden in diesem Ödland finden?}
{151}{JAIN21}{Willige werden in die Gemeinde eingegliedert. Aufständische werden leiden.}
{152}{}{Klingt nach harter Arbeit.}
{153}{}{Nun ist die Zeit gekommen, da du ein wenig leiden sollst.}
{154}{}{So soll es auch sein. Möge euer Kreuzzug erfolgreich sein!}
{155}{}{Ähhh, ich muß gehen.}
{156}{JAIN22}{Mit Beharrlichkeit können die Children alles erreichen. Wir schaffen es!}
{157}{}{Das hoffe ich auch.}
{158}{}{Von mir aus!}
{159}{}{Okay. Tschüß dann!}
{160}{JAIN26}{Gotteslästerer! Dieses Haus ist heilig! Wie kannst du das nur denken?}
{161}{}{Beruhig dich mal wieder. War nicht so gemeint.}
{162}{}{Ganz einfach. Ich zeig's dir.}
{163}{JAIN27}{Der Segen der Heiligen Flamme sei mit dir.}
{164}{}{Was ist die Heilige Flamme?}
{165}{}{Dieser Ort ist scheinheilig.}
{166}{}{Und mit dir, Priesterin Jain! Leb wohl!}
{167}{}{Häh?}
{168}{}{Ooookay!}
{169}{JAIN28}{Du hattest Potential, doch nun bist du hier nicht mehr willkommen!}
{170}{JAIN29}{Du bist hier nicht willkommen! Bitte geh!}
{171}{JAIN30}{Was führt dich her?}
{172}{}{Ich habe den Meister getötet, und ich glaube, daß er sich als Heilige Flamme verkleidet hat.}
{173}{}{Ihr seid von der Unterdrückung durch den Meister befreit.}
{174}{}{Häh?}
{175}{}{Hmm.}
{176}{JAIN31}{Was ist passiert? An der Heiligen Flamme sollst du für deine Sünde bezahlen.}
{177}{JAIN32}{Wen?}
{178}{}{Den Meister. Er wollte die Mutanten vereinen und die Herrschaft über die Welt ergreifen.}
{179}{}{Mach dir darüber keine Sorgen.}
{180}{JAIN33}{Du hast Wahnvorstellungen. Geh mal zu 'nem Berater! Der rückt dir den Kopf zurecht!}
{181}{JAIN204}{Jetzt geh schon! Bist du taub oder blöd?}
{182}{JAIN200}{Sofort raus hier, oder ich lasse dich von der Heiligen Flamme läutern!}
{183}{JAIN202}{Keiner ist größer als die Heilige Flamme, und wir sind ihre Diener.}
{184}{}{Wirklich? Wau! Weshalb treten denn Leute eurem Orden bei?}
{185}{}{Okay. Tschüß dann!}
{186}{JAIN27}{Der Segen der Heiligen Flamme sei mit dir.}
{187}{JAIN22}{Mit Beharrlichkeit können die Children alles erreichen. Wir schaffen es!}
{188}{JAIN201}{Das ist eine unpassende Frage!}

#Tell Me Abouts

{1000}{}{Krieg}
{1001}{}{Meister}
{1002}{}{Children}
{1003}{}{Mutanten}
{1004}{}{Hub}
{1005}{}{Brotherhood}
{1006}{}{Container}
{1007}{}{Flamme}
{1008}{}{Einheit}
{1009}{}{Brotherhood of Steel}
{1010}{}{Heilige Flamme}
{1011}{}{Children of the Cathedral}

{1100}{JAIN300}{Es war die Läuterung des Planeten. Die Unaufmerksamkeit derer, die davor kamen, verursachten die Heiligen Feuer. Das war gerecht.}
{1101}{JAIN301}{Die Heilige Flamme ist der einzige Meister. Sie ist unser Meister, der Meister von allem.}
{1102}{JAIN302}{Durch den Willen des Heiligen wird der Planet neu geboren. Wir, seine Kinder, führen seinen Plan aus.}
{1103}{JAIN303}{Heilig, denn sie tragen die Zeichen vergangener Sünden als Zeugnis für uns.}
{1104}{JAIN304}{Wie auch andere Städte erkennen sie die Überlegenheit der Cathedral an.}
{1105}{JAIN305}{Sie behaupten, religiös zu sein, aber es mangelt ihnen an Rechtschaffenheit. Ihr Eifer ist jedoch erfrischend.}
{1106}{JAIN306}{Von so was hab' ich nie gehört.}
{1107}{JAIN308}{Das Allerheiligste. Der Leitstern, dem wir folgen. Wenn der Nexus der Wiedergeburt erreicht ist, wird er die Ungläubigen läutern.}
{1108}{JAIN309}{Es ist die Vereinigung aller Menschen, aller Rassen und das Läutern der Heiden durch die Heilige Flamme.}
{1109}{JAIN305}{Sie behaupten, religiös zu sein, aber es mangelt ihnen an Rechtschaffenheit. Ihr Eifer ist jedoch erfrischend.}
{1110}{JAIN308}{Das Allerheiligste. Der Leitstern, dem wir folgen. Wenn der Nexus der Wiedergeburt erreicht ist, wird er die Ungläubigen läutern.}
{1111}{JAIN302}{Durch den Willen des Heiligen wird der Planet neu geboren. Wir, seine Kinder, führen seinen Plan aus.}

