{100}{}{Wir bieten die Heilung des Körpers zur Heilung des Geistes an. Kann ich dir helfen?}
{101}{}{Ja. Hilf mir.}
{102}{}{Was für Leute seid ihr?}
{103}{}{Was ist mit den Leuten geschehen, die vorher hier waren?}
{104}{}{Ähm}
{105}{}{Das ist fein. Wir werden dich jetzt untersuchen.}
{106}{}{Gesegnet sind die Sanftmütigen. Es ist alles in Ordnung mit dir.
 Lauf' nur und spiel'.}
{107}{}{Du bist geheilt. Sei zukünftig vorsichtiger.}
{108}{}{Du bist verwundet.}
{109}{}{Ich sehe, daß du vergiftet bist.}
{110}{}{Hmm, eine Strahlenvergiftung. Leider können wir das nicht heilen.}
{111}{}{Wir benötigen eine Spende von }
{112}{}{ Dollar, bevor wir dich heilen können. Bist du damit einverstanden?}
{113}{}{Ja.}
{114}{}{Nein.}
{115}{}{Soviel Geld habe ich aber nicht!}
{116}{}{Nimmst du }
{117}{}{ Dollar?}
{118}{}{Die Children handeln nicht. Nimmst du den Preis an?}
{119}{}{Ja. Aber natürlich.}
{120}{}{Du kannst mich mal!}
{121}{}{Danke dir, mein Sohn. Laß' uns für deine Heilung beten.}
{122}{}{Danke dir, meine Tochter. Laß' uns für deine Heilung beten.}
{123}{}{Das war's. Friede und der Segen der Children sei mit dir.}
{124}{}{Du hast nicht genug Geld. Wenn du alles spendest, was du hast, werden wir dich heilen. Bist du damit einverstanden?}
{125}{}{Ja.}
{126}{}{Nein.}
{127}{}{Wenn du alles spendest, was du hast, werden wir dich heilen. Bist du damit einverstanden?}
{128}{}{Ja.}
{129}{}{Nein.}
{130}{}{Du hast mehr als genug für eine Spende. Du brauchst Unterricht im Rechnen.}
{131}{}{Wir sind die Children of the Cathedral. Wir leben und arbeiten unter den Unglücklichen im Ödland. Kommst du jemals zum Boneyard, geh' in die Kathedrale.}
{132}{}{Danke schön.}
{133}{}{Was macht ihr?}
{134}{}{Wir sind die Heiler und Lehrer des Friedens. Wir heilen den Körper, um den
 Geist zu heilen. Alles, was wir erbitten, ist eine kleine Spende für unsere Heilmittel.}
{135}{}{Hört sich nach einer guten Idee an.}
{136}{}{Hört sich wie vollkommener Mist an.}
{137}{}{Wir haben dich nicht gefragt. Ich merke, daß du unserem Glaubensbekenntnis nicht mehr zuhören willst. Wenn du etwas anderes brauchst, dann komm' zu uns.}
{138}{}{Es ist der heiligste aller Gedanken. Wir wollen den ultimativen Frieden im Ödland
 schaffen. Alle Wesen sollen die gleichen Rechte haben und in Gemeinschaft leben.}
{139}{}{Vielen Dank. Auf Wiedersehen.}
{140}{}{Sie haben uns dieses Haus gestiftet, damit wir die Botschaft verbreiten und
 unsere Pflicht als Heiler erfüllen können.}
{141}{}{Ist Doc Morbid darüber nicht sauer?}
{142}{}{Das war furchtbar nett von denen. Danke.}
{143}{}{Was die Seele der Heiden fühlt, geht die Children nichts an. Wir sind hier, um
 unsere Pflicht zu erfüllen, und das werden wir tun.}
{144}{}{Äh, Mensch, danke. Tschüß.}
{145}{}{Warum machst du das? Wir werden dir nichts tun!}
{146}{}{Dein Zustand erfordert keine Hilfe.}