{100}{}{Du siehst Jennifer.}
{101}{}{Du siehst einen Paladin.}
{102}{}{Entschuldigung, Bruder. Du solltest deine Waffe ablegen, wenn du bei der Brotherhood bist. Wir sind ein freundlicher Orden, doch du weißt, dass die Zeiten hart sind.}
{103}{}{Einige Mitglieder der Brotherhood könnten beleidigt sein, wenn ein Fremder ... ich meine, ein richtiger Neuling ... mit einer Waffe auf sie zugeht.}
{104}{}{Guten Tag, Neuling. Wie kann ich dir helfen?}
{105}{}{Hallo, Schwester, schön, dass es in dieser Organisation auch Frauen in höheren Positionen gibt. Ich habe nicht gewusst, was ich von dem Namen Brotherhood halten soll.}
{106}{}{He, Schöne. Gut siehst du aus. Wann kann ich dich abholen?}
{107}{}{Uuuuuga!}
{108}{}{Kannst du mir sagen, wo ich unseren High Elder finde?}
{109}{}{Wer hat denn in dem Loch hier das Sagen?}
{110}{}{Wo ist denn dieser High Elder?}
{111}{}{Gruk!}
{112}{}{Maxson, der High Elder, ist im vierten Stock zu finden. Wenn du den anderen Aufzug ins vierte Stockwerk nimmst, sollte er entweder im Ratsraum oder im Zimmer der Elders sein.}
{113}{}{Du kannst eine der Wachen auf diesem Stockwerk fragen, die sollten wissen, wo er sich im Moment aufhält.}
{114}{}{Vielen Dank.}
{115}{}{Wo kriege ich bessere Waffen her?}
{116}{}{Du solltest mit Talus reden. Er kann dir vielleicht helfen oder zumindest sagen, an wen du dich wenden kannst.}
{117}{}{Tagsüber hat Talus normalerweise Aufsicht in der Trainingshalle. Weißt du, wo die ist?}
{118}{}{Ja, weiß ich. Danke.}
{119}{}{Nein.}
{120}{}{Aber natürlich!}
{121}{}{Die Trainingshalle ist gleich um die Ecke. Geh diesen Gang entlang, dann nach links, durch die Tür am Ende des Gangs und durch die rechte Tür. Dort ist sie.}
{122}{}{Du warst mir eine Riesenhilfe. Danke dir vielmals. Hoffentlich sehen wir uns bald wieder einmal. Tschüss!}
{123}{}{Trainingshalle? Glaubst du, ich könnte dort zum Training gehen? Ich bin doch jetzt ein Mitglied der Brotherhood, oder?}
{124}{}{Danke für deine Hilfe, Schwester. Schön, dass es in dieser Organisation auch Frauen in höheren Positionen gibt. Ich habe nicht gewusst, was ich von dem Namen Brotherhood halten soll.}
{125}{}{Danke, Süße. Weißt du, du siehst richtig gut aus. Was hältst du davon, wenn wir beide uns dann treffen und gegenseitig unsere 'Ausrüstung' zeigen? Wann hast du aus?}
{126}{}{Ach, dort. Okay, tschüss.}
{127}{}{Entschuldigung? Stimmt etwas nicht?}
{128}{}{Muk? Lug?}
{129}{}{Tut mir leid, ich kann dir wohl nicht helfen. Du solltest unbedingt zur Ärztin gehen. Sie ist im zweiten Stock.}
{130}{}{Natürlich gibt es die. Zwei der fünf Elders sind Frauen, unser Master Scribe ist eine Frau, und es gibt viele andere Frauen in allen Dienstgraden.}
{131}{}{Die Frauen der Brotherhood heißen auch Brüder. Wir nennen die Frauen meist nicht Schwestern. Schließlich ist das die Brotherhood of Steel, und nicht die Sisterhood of Steel.}
{132}{}{Findest du es nicht seltsam, dass sie Brotherhood heißt, was andeutet, dass sie ausschließlich aus Männern besteht?}
{133}{}{Aber warum heißt sie dann Brotherhood?}
{134}{}{Ich fand es halt seltsam.}
{135}{}{Ich weiß es nicht. Sie hieß schon immer so. Ich bin sicher, dass es einen Grund dafür gibt.}
{136}{}{Du hast wohl recht.}
{137}{}{Also, ich finde es ein bisschen seltsam.}
{138}{}{Das ist eigenartig. Ich habe noch nie darüber nachgedacht. Mein ganzes Leben lang waren wir die Brotherhood of Steel. Unsere Vorväter müssen einen Grund für diesen Namen gehabt haben.}
{139}{}{Das heißt aber nicht, dass man das nicht ändern kann.}
{140}{}{Ja, du hast wahrscheinlich recht.}
{141}{}{Kann ich dir noch bei was anderem helfen?}
{142}{}{Ja, wo finde ich den High Elder?}
{143}{}{Wo krieg' ich bessere Waffen her?}
{144}{}{Nein, das war's. Tschüss.}
{145}{}{Nein, mit Traditionen sind wir sehr streng. Ich glaube nicht, dass das je geändert werden könnte. Es macht mir überhaupt nichts, als Bruder angesprochen zu werden. Seltsam ist es aber doch.}
{146}{}{Ich glaube, ich muss einmal mit Vree reden. Sie kann mir vielleicht klarmachen, warum unsere Vorväter sich auf den Namen Brotherhood of Steel geeinigt haben.}
{147}{}{Wer ist Vree? Einer der Elders?}
{148}{}{Vree ist der Master Scribe. Du solltest sie fragen, wenn du technische Fragen hast, doch stör sie nicht, wenn sie nachts meditiert.}
{149}{}{Sie bleibt fast immer in ihrem Zimmer im dritten Stock, in dem auch der
 Großrechner ist.}
{150}{}{Loch? Wie kannst du es wagen, so über die Brotherhood zu reden! Du bist jetzt Mitglied der Brotherhood of Steel und solltest stolz darauf sein.}
{151}{}{Stolz? Warum? Ihr seid doch alle nur ein Haufen Roboter-Idioten, die sich vor dem echten Leben verstecken. Da gibt es nichts, worauf man stolz sein könnte.}
{152}{}{Tut mir leid. Ich lass' mich manchmal ein bisschen gehen.}
{153}{}{Ja, klar.}
{154}{}{Naja, das geht uns doch allen manchmal so.}
{155}{}{Wer hat hier also das Sagen?}
{156}{}{Ja. Also, ich muss jetzt gehen.}
{157}{}{Maxson, der High Elder. Er ist im vierten Stock.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Du bist süß ... aber ich glaube nicht. Es wäre auf jeden Fall wohl keine gute Idee, sich mit jemanden von draußen einzulassen. Aber du bist süß und nicht unattraktiv.}
{164}{}{Ich weiß nicht, ob es daran liegt, dass du von draußen bist, oder an deiner extremen ... Taktlosigkeit. Also, Schnuckelchen, kann ich noch was für dich tun?}
{165}{}{Ja, äh, wahrscheinlich. Äh, wer hat denn hier das Sagen?}
{166}{}{Äh, okay ... ähm. Wie steht's dann mit den Waffen? Wo krieg' ich welche her?}
{167}{}{Hmmf!}
{168}{}{Nein.}
{169}{}{Das ist ... sehr komisch. Das ist doch hoffentlich ein Witz. Obwohl ... gib mir keine Antwort. Ich glaube, ich will's gar nicht wissen.}
{170}{}{Ja, SEHR witzig. Fast so wie deine Visage!}
{171}{}{Vielen Dank. Das ist genau das, was ich jetzt hören wollte.}
{172}{}{Ich hau' hier ab.}
{173}{}{Tut mir leid. Ihr von draußen redet bloß manchmal so komisch. Kann ich dir irgendwie behilflich sein?}
{174}{}{Ich sollte wohl mit diesem High Elder reden. Wo ist er?}
{175}{}{Ich hätte gerne bessere Waffen. Mit wem muss ich darüber reden?}
{176}{}{Nein.}
{177}{}{Ist das dein Ernst? So eine miese Anmache habe ich mein ganzes Leben noch nie gehört!}
{178}{}{Ja? Ich komme eben nicht oft raus. Okay?}
{179}{}{Geh' mir aus den Augen, du wandelnder Mülleimer!}
{180}{}{Pfft!}
{181}{}{Also, ja, du bist ein Mitglied der Brotherhood, doch die Elders haben das
 ganze Training für Neueinsteiger auf Eis gelegt.}
{182}{}{Warum?}
{183}{}{Oh, das ist ja SUPER! Warum bin ich diesem blöden Verein bloß beigetreten? Wo ist die Tür?!}
{184}{}{Es gibt Gerüchte über irgendeine Armee. Ich glaube, die Elders wollen ihre Ressourcen auf die konzentrieren, die im Training schon weit genug sind, um uns im Kampf wirklich nützen zu können.}
{185}{}{Wir glauben fest daran, dass es besser ist, wenige Kämpfer extrem gut auszubilden, als vielen Kämpfern ein mittelmäßiges Training zukommen zu lassen. Die Lebensrettung ist eines unserer Hauptziele.}
{186}{}{Dir nutzt es wahrscheinlich schon was, wenn du beim Training nur zuschaust. Bruder Thomas ist der beste Ausbilder, den wir je in der Brotherhood gehabt haben.}
{187}{}{Ich soll doch außerhalb der Brotherhood eingesetzt werden, stimmt's? Die Welt da draußen ist sehr gefährlich, und ich werde mein Leben in jeder Minute aufs Spiel setzen. Findest du nicht, ich sollte eine Ausbildung erhalten, wenn ich sie will oder brauche, oder sagst du nur so, dass es euer Hauptziel ist, Leben zu retten?}
{188}{}{Danke für den Vorschlag, ich schau's mir an.}
{189}{}{Ihr seid ein Haufen Idioten.}
{190}{}{Kannst du mir sagen, wo Maxson ist?}
{191}{}{Ich wiederhole nur, was mir gesagt wird. Wenn du mit Thomas oder Talus sprichst, machen sie vielleicht eine Ausnahme.}
{192}{}{Okay, danke.}
{193}{}{Na, hoffentlich. Ich habe für euch schon genug Faxen gemacht.}
{194}{}{Kannst du mir also sagen, wo Maxson ist?}
{195}{}{Ach, mein Liebling. Wann wollen wir heiraten?}
{196}{}{Du siehst so gut aus wie immer.}
{197}{}{Gib mir einen Kuss.}
{198}{}{Ich habe dich so vermisst.}
{199}{}{Ich warte auf dich.}
{200}{}{Ich denke schon den ganzen Tag an dich.}
{201}{}{Du bist so süß, wenn du mich so ansiehst.}
{202}{}{Erschrick mich nicht so. Ich habe geglaubt, ich sehe dich nie wieder.}
{203}{}{Du bist letzte Nacht nicht mehr gekommen.}
{204}{}{Wann habe ich dich das letzte Mal gesehen? Es scheint eine Ewigkeit her.}
{205}{}{Ich habe dich so vermisst.}
{206}{}{Komm' ins Bett, Schatz.}
{207}{}{Wir können am Morgen heiraten.}
{208}{}{Ich finde, wir sollten fünf Kinder zeugen.}
{209}{}{Wohin sollen die Flitterwochen gehen? Ich habe gehört, dass es bei den Children of the Cathedral sehr schön sein soll.}
{210}{}{Meine Eltern haben dich immer noch nicht kennengelernt.}
{211}{}{Ja, du wieder. Hoffentlich geht es dir gut. Hoffentlich hast du mit Vree geredet.}
{212}{}{Hallo, Bruder }
{213}{}{.}
{214}{}{Sei vorsichtig, wenn du in den Norden reist. Unsere Späher sind nie zurückgekehrt.}
{215}{}{Bruder }
{216}{}{, schön dich wieder zu sehen.}
{217}{}{Hast du mit Rhombus gesprochen? Er ist der oberste Knight. Er ist in dem Zimmer da drüben.}
{218}{}{Ich hab' keine Zeit zu reden. Ich hab' zu tun.}
{219}{}{Tut mir leid, ich bin nicht in der Stimmung, mit unhöflichen Leuten zu reden.}
{220}{}{Lass mich in Ruhe!}
{221}{}{Was? Kannst du nicht jemand andres belästigen?}
{222}{}{Hau ab!}
{223}{}{Ich möchte nicht mit dir reden.}
{224}{}{Neuling, kehre zu deinen Studien zurück.}
{225}{}{Keine Zeit zum Reden, Neuling.}
{226}{}{Komm hierher, du Adonis!}
{227}{}{Liebling, hier drüben!}
{228}{}{Ich habe dich vermisst.}
{229}{}{Das Kinderzimmer ist schon fertig, Liebling.}
{230}{}{Hallo, Süße.}
{231}{}{Wir sehen uns.}
{232}{}{Du musst meine Eltern kennenlernen.}
{233}{}{Juhu!}
{234}{}{Komm her, mein kleines Mäuschen.}
{235}{}{Willst du mich ärgern?}
{236}{}{Du willst dich rar machen, stimmt's?}
{237}{}{Hier drüben, Spatz!}
{238}{}{Hallo, Süße!}
{239}{}{Da bist du ja. Ich habe mir schon Sorgen gemacht.}
{240}{}{Komm hierher und gib mir einen Kuss, Hübscher.}
{241}{}{Komm schon rein, Liebling.}
