{100}{}{Du siehst den Stellenaushang der Arbeitsvermittlung.}
{101}{}{JOBS! Brauchst du Arbeit? Brauchst du Geld? SCHAU HIERHER! }
{102}{}{Bitte Anzeigen nicht doppelt anbringen. - Sheriff Greene.}
{103}{}{1       Verschwundener Caravan! Belohnung!}
{104}{}{2       Caravan-Wächter gesucht.}
{105}{}{8a}
{106}{}{8b}
{107}{}{8c}
{108}{}{8d}
{109}{}{9       Ausgang}
{110}{}{1a      BELOHNUNG: VERSCHWUNDENER CARAVAN. Eine Belohnung von 500 Hub-Scheinen erhält derjenige, der es schafft, die Schweine zu fangen, die unsere Caravans überfallen. Näheres dazu von Butch Harris, Far Go Trader, nordöstlich vom Merchant Market.}
