{100}{}{Du siehst die ausgemergelte Gestalt von Bob.}
{101}{}{Bring' mich bitte nicht um! Ich schwöre, dass ich dir dein Geld besorge!}
{102}{}{Häh.}
{103}{}{Klar, das rückst du lieber raus.}
{104}{}{Ich glaub', ich bin im falschen Zimmer.}
{105}{}{Wovon sprichst du?}
{106}{}{Ach! Du musst der Dumme Fred sein, der Gnadenlose Dreckskiller. Bitte,
 töte mich nicht!}
{107}{}{Hier. Nimm' das. Mehr hab' ich nicht.}
{108}{}{Heißt das, du wolltest mich gar nicht töten?}
{109}{}{Nöö. Is' dein Glückstag heut'.}
{110}{}{Nein. Wer bedroht dich denn so?}
{111}{}{Danke. Ich wurde nur ein bisschen nervös, als du hier mit}
{112}{}{ in der Hand reinmarschiert bist.}
{113}{}{Danke. Ich wurde nur ein bisschen nervös, als du hier mit}
{114}{}{ in der Hand reinmarschiert bist.}
{115}{}{Puuh, ich dachte, du kommst vom Kasino. Klar wie Kloßbrühe,
 denen schulde ich 'ne Menge Knete.}
{116}{}{Warum schuldest du denen so viel Geld?}
{117}{}{Wem im Kasino schuldest du das Geld?}
{118}{}{Wieviel Schulden hast du?}
{119}{}{Hmmm. Danke für die Info.}
{120}{}{Die bescheißen. Ich hab ein bisschen am Spielautomaten und Poker gespielt.
 Aber ich kann das besser. Ich schwör', dass die Maschinen manipuliert sind. Ich habe eine Menge Geld verloren.}
{121}{}{Wem im Kasino schuldest du das Geld?}
{122}{}{Wieviel Schulden hast du?}
{123}{}{Hmmm. Danke für die Info.}
{124}{}{Irgendwelchen Typen, die behaupten, dass sie für den Kasino-Boss arbeiten, aber
 ich hab ihn nie gesehen. Einer hieß Izo, glaub' ich, und der andere irgendwie Guido
 oder so. Verdammte Betrüger.}
{125}{}{Warum schuldest du denen so viel Geld?}
{126}{}{Wieviel schuldest du?}
{127}{}{Hmmm. Danke für die Info.}
{128}{}{Ach, nicht viel. 'N paar Tausender. Ich hab nur vier oder fünf
 Stunden gespielt. Naja, vielleicht ein bisschen länger. Die haben's mir angeschrieben,
 und ich hab' nicht genug da, um's zu bezahlen. Ich muss zurück zum Hub und mir
 Bargeld holen. Ich hab' Angst, dass die mich zusammenschlagen, wenn ich abhauen will.}
{129}{}{Warum schuldest du denen so viel Geld?}
{130}{}{Wem im Kasino schuldest du das Geld?}
{131}{}{Hmmm. Danke für die Info.}
{132}{}{Oh, du schon wieder. Hoffentlich ging's dir besser als mir.}
{133}{}{Hey, was machst du in meinem Zimmer? Bist du vom Kasino?}
{134}{}{Nhhh!}
{135}{}{Ja, ich komm' vom Kasino.}
{136}{}{Nein, ich schau' mich bloß um.}
{137}{}{Is' was mit dem Kasino?}
{138}{}{Oh Gott. Ich dachte, du bist vom Kasino. Hast du mich erschreckt!}
{139}{}{Oh, OK. Tschüss.}
{140}{}{Warum?}
{141}{}{Naja, ich hab' dort ein paar Schwierigkeiten. Ich schulde denen 'ne Menge Knete.}
{142}{}{Warum schuldest du denen so viel Geld?}
{143}{}{Wem im Kasino schuldest du das Geld?}
{144}{}{Wieviel Schulden hast du?}
{145}{}{Hmmm. Danke für die Info.}
{146}{}{Oh, du schon wieder. Du hast mich ein bisschen erschreckt. Hast du hier jemanden
 vom Kasino gesehen?}
{147}{}{Hm!}
{148}{}{Nein.}
{149}{}{Na klar.}
{150}{}{Hey, ich muss dich was fragen.}
{151}{}{Gut, gut. Ich brauch' nur noch ein paar Tage, dann hab' ich das Geld wieder
 und noch einiges obendrauf. Ich bin ein besserer Spieler als die glauben.}
{152}{}{Ach! Jesusmaria! Ich sitz' in der Tinte! Tschüss.}
{153}{}{Mach' schon, schieß'. Oh, so was sagt man nicht, Bob. Das sagt man nicht.}
{154}{}{Warum schuldest du denen so viel Geld?}
{155}{}{Wem im Kasino schuldest du das Geld?}
{156}{}{Wieviel Schulden hast du?}
{157}{}{Hmmm. Danke für die Info.}
