{100}{}{Er sieht wie eine erfahrene Wache aus.}
{101}{}{Ich an deiner Stelle wäre hier vorsichtig.}
{102}{}{In dieser Stadt machst du besser keinen Ärger.}
{103}{}{Benimm dich, dann müssen wir nicht sauer werden.}
{104}{}{Du bist okay.}
{105}{}{Weiter so.}
{106}{}{Schöner Tag heute, nicht wahr?}
{107}{}{Das ist Junktown. Man kann hier gut leben, wenn man auf der richtigen Seite steht.}
{108}{}{Nimm dich vor Gizmo und seinen Kumpanen in acht.}
{109}{}{Ich mag meinen Boss.}
{110}{}{Steck das lieber weg. Junktown ist ein friedlicher Ort, und das soll auch so bleiben.}
{111}{}{Was wegstecken?}
{112}{}{Erzähl mir nicht, was ich zu tun habe, du Niete!}
{113}{}{Aha. Was sagt denn das Gesetz hier so zu Waffen?}
{114}{}{Ah! Oh!}
{115}{}{Deine Waffe natürlich, du Idiot! Killian nimmt dir deine Waffen nicht weg, aber du solltest sie besser steckenlassen.}
{116}{}{Oh, Entschuldigung.}
{117}{}{Auf gar keinen Fall! Ich steck' meine Knarren für niemanden weg!}
{118}{}{Benimm dich lieber, denn das ist Gesetz, und ich vertrete das Gesetz. Steck also deine Waffen weg, dann wirst du mit uns Wachen keine Probleme haben. Du darfst deine Waffen höchstens zur Selbstverteidigung ziehen. Wenn du dich nicht ans Gesetz hälst, landest du wieder im gesetzlosen Ödland - tot oder lebendig.}
{119}{}{Klar, wenn das so ist ...}
{120}{}{Steck dir dein Gesetz sonstwohin!}
{121}{}{Naja ... äh ... okay. Aber sei lieber vorsichtig.}
{122}{}{Gut, dass du fragst. Du darfst zwar bewaffnet rumlaufen, aber die Waffen höchstens zur Selbstverteidigung ziehen. Wenn du einen Kampf anzettelst, bist du selbst schuld. Ich rate dir, zieh einfach kein Messer oder Gewehr ohne guten Grund. Einen schönen Tag noch!}
{123}{}{He, du da, keine Waffen! Und es ist mir egal, ob du als Kind mal auf den Kopf gefallen bist. Keine Waffen!}
{124}{}{He, du da! Was schleichst du hier so rum?}
{125}{}{Nur so.}
{126}{}{Ich schleiche nicht rum. Ich gehe nur gerne vorsichtig.}
{127}{}{Ähhh.}
{128}{}{Was immer du vorhast, in dieser Stadt tust du es jedenfalls nicht.}
{129}{}{[Die Wache starrt dich einen Augenblick an. Er scheint dich erkannt zu haben, dann zieht er seine Waffe.]}
{130}{}{Naja ... äh ... aber benimm dich.}
{131}{}{Danke. Tschüss dann!}
{132}{}{Klar doch, aber ich scheiß' auf Vorsicht.}
{133}{}{Klar doch, aber ich scheiß' auf Vorsicht.}
{134}{}{Steck deine Waffe weg, sonst kann ich für nichts garantieren.}
{135}{}{Okay, jetzt reicht's. Verlass sofort die Stadt und komm nie wieder, sonst kann ich für nichts garantieren.}
{136}{}{He! Was machst du da?}
{137}{}{Das war's, es reicht jetzt!}
{138}{}{Jetzt gibt's Ärger ...}
{139}{}{Ihr Skulz seid verhaftet!}
