{100}{}{Du bist aus dem Gefängnis ausgebrochen. Jetzt bist du wirklich ein Flüchtling in
 Junktown!}
{101}{}{Die Tür schaut massiv aus und hat ein stabiles Schloß. Aber Schlösser lassen sich   öffnen, und Türen können zerstört werden.}
{102}{}{Die Tür ist verschlossen.}
{103}{}{Du schließt die Tür auf.}
{104}{}{Du schließt die Tür zu.}
{105}{}{Du kannst die Tür nicht aufschließen.}
{106}{}{Du kannst die Tür nicht verschließen.}
{107}{}{ Erfahrungspunkte, weil du aus dem Gefängnis abhaust!}