{100}{}{Du siehst Kane.}
{101}{}{Was ist das für ein Job, und was bringt er ein?}
{102}{}{Für den Haufen arbeiten? Du machst Witze.}
{103}{}{Stimmt, und ich glaub', ich muss dir einfach so mal in den Arsch treten.}
{104}{}{Tut mir leid, später vielleicht.}
{105}{}{Nein, danke.}
{106}{}{Tuk?}
{107}{}{Die Berichte haben wohl nicht gestimmt, hau' ab. Wir nehmen keine Skags.}
{108}{}{Das ist keine Arbeit für Skags. 'Es' muss schnell und sauber erledigt werden. Der Boss kann dir Einzelheiten sagen, doch es bringt mehr Geld als du in einem Monat bei den Caravans verdienen würdest, aber nur, wenn du gut genug bist. Nieten können wir nicht ab, wenn du mich verstehst.}
{109}{}{Klingt gut.}
{110}{}{Ich kann gerade nicht. Ich melde mich wieder bei dir.}
{111}{}{Wen muss ich umlegen?}
{112}{}{Nein, danke. Ich brauche das Geld nicht.}
{113}{}{Ich bin sicher, du kennst unsere Art von Geschäft und weißt, dass es in deinem eigenen Interesse liegt, das für dich zu behalten. Kapiert?}
{114}{}{Ich hoffe für dich, dass du versucht hast, witzig zu sein. Komm uns nicht in die Quere, du wirst es sonst bereuen.}
{115}{}{Klar. Also, worum geht's bei der 'Arbeit'?}
{116}{}{Ja, wie du willst, du harter Bursche.}
{117}{}{Ich glaube, du verstehst nicht. Im Klartext: Wenn sich deine Manieren nicht bessern, wirst du dich bald tot fühlen, du harter Bursche.}
{118}{}{Ich glaube, du verstehst nicht. Im Klartext: Wenn sich deine Manieren nicht bessern, wirst du dich bald tot fühlen, du hartes Mädel.}
{119}{}{Nein, lass es mich so formulieren - wenn du nicht aufpasst, mach' ich mir Schuhe aus deinem Arsch.}
{120}{}{Okay. Ich hab's kapiert. Was soll ich machen?}
{121}{}{Ich spreche später mit dir. Ich muss jetzt weg.}
{123}{}{Oh ja, bitte. Wir sind gespannt.}
{124}{}{Aber natürlich. Tschüss dann!}
{125}{}{Du brauchst das Geld nicht? Du scherzt wohl, soweit ich gehört habe, würde dir die Arbeit, die mir für dich vorschwebt, Spaß machen.}
{126}{}{Ach ja? Vielleicht bin ich interessiert, mach weiter.}
{127}{}{Nein, danke.}
{128}{}{Ich melde mich wieder bei dir.}
{129}{}{Es ... Magst du mich nach unten begleiten? Es gibt hier zu viele offene Ohren.}
{130}{}{Klar.}
{131}{}{Kein Interesse.}
{132}{}{Nicht jetzt, ich melde mich wieder bei dir.}
{133}{}{Hau ab, ich hab' keine Geduld.}
{134}{}{Hängst du an deinem Leben?}
{135}{}{Du hattest deine Chance, jetzt verschwinde.}
{136}{}{Suchst du Streit?}
{137}{}{Du bist nicht lernfähig, stimmt's? Respekt wirst du aber bald lernen.}
{138}{}{Ich hab' von dir gehört. Du bist angeblich ein fieser Bursche. Wenn du Arbeit suchst, kann ich dir vielleicht was besorgen. Bist du interessiert?}
{139}{}{Ich hab' von dir gehört. Du bist angeblich ein fieses Mädel. Wenn du Arbeit suchst, kann ich dir vielleicht was besorgen. Bist du interessiert?}
{140}{}{Ich hab' von dir gehört. Du hast doch Killian in Junktown erledigt, gute Arbeit. Gizmo muss dafür tief in die Tasche gegriffen haben. Was bringt dich denn in den Hub, suchst du Arbeit?}
{141}{}{Ich hab' von dir gehört. Du hast doch Gizmo in Junktown erledigt. Killian muss dafür tief in die Tasche gegriffen haben. Suchst du hier vielleicht Arbeit?}
{142}{}{Ich hab' von dir gehört. Du bist doch das Mädel, das Killian und Gizmo erledigt hat. Ja, so löst man Probleme ... Was bringt dich denn in den 'Maltese Falcon'? Suchst du Arbeit?}
{143}{}{Ich hab' von dir gehört. Du bist doch der Scheißkerl, der Killian und Gizmo erledigt hat. Ja, so löst man Probleme ... Was bringt dich denn in den 'Maltese Falcon'? Suchst du Arbeit?}
{144}{}{Ich hab' von dir gehört. Du hast dir schon 'nen schönen Namen gemacht. Was bringt dich denn in den Hub?}
{145}{}{Ich suche einen Steuerchip.}
{146}{}{Ich muss mit Decker reden.}
{147}{}{Führst du den Laden?}
{148}{}{Ich bin hier, um dir in den Arsch zu treten.}
{149}{}{Ich glaub', ich muss dir jetzt sehr weh tun.}
{150}{}{Wenn ich mit dir fertig bin, musst du dich nicht mehr um deine Gesundheit kümmern.}
{151}{}{Ich reinige die Welt von allem Übel!}
{152}{}{Ich muss gehen, tschüss.}
{153}{}{Das war's, tschüss.}
{154}{}{Tuk?}
{155}{}{Baruka!}
{156}{}{Einen Steuerchip? Nie gehört, wir verkaufen nur Drinks. Geh zu 'Bob's Iguana Bits', wenn du Hunger hast.}
{157}{}{Das ist ein elektronisches Gerät, das das Filtersystem einer Wasserreinigungsanlage steuert und das Wasser auf Verunreinigungen überprüft. Meiner ist kaputt, und ich suche Ersatz.}
{158}{}{Nein, es ist ein kleines Gerät, das eine Wasserreinigungsanlage steuert.}
{159}{}{Noch eine Frage ...}
{160}{}{Okay, danke. Tschüss.}
{161}{}{Seh' ich aus wie ein Händler? Du vergeudest meine Zeit.}
{162}{}{Frag doch mal die Water Merchants. Die befinden sich südlich vom Merchant Market. Du kannst sie nicht verfehlen. Die sind bei einem riesigen Wasserturm.}
{163}{}{Du? So was Lustiges habe ich ja noch nie gehört.}
{164}{}{So richtig lustig wird's für dich, wenn ich dein Gesicht neu gestaltet habe!}
{165}{}{Mal sehen, wer zuletzt lacht ...}
{166}{}{Du glaubst, du kannst dich mit mir anlegen? Du bist vielleicht kräftig, aber das hilft nicht gegen eine Kugel.}
{167}{}{Du hast recht, tut mir leid. Erschieß mich bitte nicht.}
{168}{}{Ich verstehe. Du musst dich hinter 'ner Knarre verstecken, was?}
{169}{}{Du bist erbärmlich. Vielleicht sollte ich dich von deinem Elend zu erlösen.}
{170}{}{Tut mir leid, war nicht so gemeint. Erschieß mich bitte nicht.}
{171}{}{Traust du dich nur mit 'ner Knarre? Hast du Angst, dass ich dir das Fell über die Ohren zieh'?}
{172}{}{Was? Hast du Angst vor einem kleinen Mädel, brauchst du 'ne Knarre?}
{173}{}{Klar.}
{174}{}{Das reicht! Wenn du glaubst, du weißt, was Schmerzen und Leiden bedeuten, dann warte, bis ich mit dir fertig bin.}
{175}{}{Beruhig deinen Köter, oder er ist tot.}
{176}{}{Halt deinen Freund da raus.}
{177}{}{Halt deine Kumpel da raus, oder sie sind tot.}
{178}{}{Zurück, Jungs, der gehört mir.}
{179}{}{Zurück, Jungs, die gehört mir.}
{180}{}{Du enttäuschst mich, ich hab' gedacht, du bist besser.}
{181}{}{Verstecken? Ich muss mich hinter nichts verstecken, und ich brauche KEINE Knarre, um mit dir fertig zu werden.}
{182}{}{Beruhig deinen Köter, oder er ist tot.}
{183}{}{Halt deinen Freund da raus.}
{184}{}{Halt deine Kumpel da raus, oder sie sind tot.}
{185}{}{[Über die Schulter.] Zurück, Jungs, der gehört mir.}
{186}{}{[Über die Schulter.] Zurück, Jungs, die gehört mir.}
{187}{}{Harte Worte, Kleiner. Ich sag' dir was, ich leg' das Spielzeug weg, und wir schauen mal, wer am Ende noch steht.}
{188}{}{Harte Worte, Kleine. Ich sag' dir was, ich leg' das Spielzeug weg, und wir schauen mal, wer am Ende noch steht.}
{189}{}{Tut mir leid, war nicht so gemeint. Tu mir bitte nichts.}
{190}{}{Komm und hol's dir.}
{191}{}{Okay, aber ich möchte dich nicht zum Weinen bringen.}
{192}{}{Nein, danke. Keine Zeit dafür, tschüss.}
{193}{}{Du drehst mir lieber nicht den Rücken zu, nach dem, was du gesagt hast. Du solltest dankbar sein, dass ich so nachsichtig bin... jetzt zumindest. Bis wir uns wiedersehen.}
{194}{}{Das wird Spaß machen.}
{195}{}{Beruhig deinen Köter, oder er ist tot.}
{196}{}{Halt bloß deinen Freund da raus.}
{197}{}{Halt bloß deine Kumpel da raus, oder sie sind tot.}
{198}{}{[Über die Schulter.] Zurück, Jungs, der gehört mir.}
{199}{}{[Über die Schulter.] Zurück, Jungs, die gehört mir.}
{200}{}{Reinigen? Das ist lieb von dir, aber 'übel' ist sehr subjektiv. Was oder wen du als übel bezeichnest, könnte von jemand anderen genau andersherum gesehen werden.}
{201}{}{Ja, das stimmt, aber sollen wir deshalb nur dasitzen und nichts machen, nur weil wir uns nicht sicher sind?}
{202}{}{Das ist doch lächerlich. Was übel ist, ist böse. Wer was anderes behauptet, ist nur dumm.}
{203}{}{Egal. War nur Spaß.}
{204}{}{Das hoffe ich doch. Es gibt genug Probleme auf der Welt, da brauchen wir nicht noch einen blinden Fanatiker, der alle möglichen Leute abknallt.}
{205}{}{Schade. Ein blinder Fanatiker ist wirklich gefährlich. Hoffentlich musst du nicht zu lange im Hub bleiben. Wir mögen keine Mörder, die keine Erlau ... keine Mörder, egal welcher Art. Guten Tag.}
{206}{}{Nein.}
{207}{}{Nette Antwort, Schwachkopf. Wer bestimmt hier?}
{208}{}{Ja, ja, wer schon?}
{209}{}{Schwachkopf? Weißt du eigentlich, mit wem du redest? Ich hoffe für dich, dass es nicht so ist. Ich 'führe' nicht den 'Maltese Falcon', sondern ich BESTIMME hier. Was willst du, bevor ich ausraste?}
{210}{}{Ich weiß, wer du bist, und glaub' mir, du BIST ein Schwachkopf.}
{211}{}{Oh, tut mir leid. Wer führt denn den Laden?}
{212}{}{Mal schauen. 'Schönen' Tag noch.}
{213}{}{Wenn du es nicht weißt, solltest du nicht fragen. Kann schlecht für deine Gesundheit sein.}
{214}{}{In bezug auf was?}
{215}{}{Ein Job.}
{216}{}{Ist ein Geheimnis.}
{217}{}{Das geht dich nichts an. Jetzt führ mich zu ihm.}
{218}{}{Strapazier dein Glück nicht, Bursche, oder du siehst Decker erst, wenn du im Sarg liegst. Hier lang, und mach keine Faxen. Ich beobachte dich.}
{219}{}{Strapazier dein Glück nicht, Mädel, oder du siehst Decker erst, wenn du im Sarg liegst. Hier lang, und mach keine Faxen. Ich beobachte dich.}
{220}{}{Ich glaube wohl, dass es mich was angeht, und ich führ' dich nirgendwohin ... wenn du Glück hast. Jetzt hau bloß ab.}
{221}{}{Tut mir leid, aber du kannst mir alles sagen, was du Decker mitteilen musst. Ich bin seine rechte Hand, und hier geschieht nichts, ohne dass wir beide davon erfahren.}
{222}{}{Es geht um 'nen Job.}
{223}{}{Tut mir leid, ich musste Geheimhaltung schwören. Ich kann's nur Decker sagen.}
{224}{}{Dann wirst du ihn eben nicht sehen.}
{225}{}{Wer schickt dich?}
{226}{}{Beth schickt mich.}
{227}{}{Lorenzo schickt mich.}
{228}{}{Loxley schickt mich.}
{229}{}{Der Sheriff schickt mich.}
{230}{}{Niemand.}
{231}{}{Beth wer?}
{232}{}{Du weißt schon.}
{233}{}{Hat sie nicht gesagt. Ihr gehört der Waffenladen.}
{234}{}{Verzieh dich. Für deine Spielchen habe ich keine Zeit.}
{235}{}{Dann wirst du niemanden sehen.}
{236}{}{Sag unserem freundlichen Sheriff Greene, dass Deckers Terminkalender sehr voll ist, und dass er es noch einmal in ein paar Monaten probieren soll. Tut mir leid, aber du solltest jetzt gehen ... für immer.}
{237}{}{Ich glaube nicht, dass sie dich schickt. Geh jetzt, bitte.}
{238}{}{Hat er das? Wollen die endlich unseren Schutz? Gehörst du zu denen?}
{239}{}{Ich habe keine Ahnung, wovon du sprichst. Er hat nur erwähnt, dass Decker vielleicht Arbeit für mich hat.}
{240}{}{Ich? Für die Gauner arbeiten, niemals! Mit so was will ich nichts zu tun haben.}
{241}{}{Du uns schützen? NIEMALS!}
{242}{}{Schau, Kumpel. Ich suche einfach gute, saubere, ehrliche Arbeit.}
{243}{}{Ach ja? Dann bist du hier falsch, der Hub ist alles andere als ehrlich. Kriech wieder in das Loch zurück, aus dem du kommst. Dort wirst du glücklicher.}
{244}{}{Stimmt. Also gut, folge mir, und wir schauen einmal, wie nützlich du uns bist. Denk aber daran, dass es in deinem eigenen Interesse ist, dass du alles, was du hörst, für dich behältst.}
{245}{}{Kann sein. Bist du Mitglied des Thieves Circle?}
{246}{}{Ja.}
{247}{}{Nein.}
{248}{}{Tja, tut mir leid, aber wir arbeiten nicht mit deinen kleinen Freunden. Wir tolerieren kaum ihre Existenz, und wir würden nie mit ihnen zusammenarbeiten.}
{249}{}{Also gut. Du könntest uns vielleicht doch nützlich sein. Denk aber daran, dass es in deinem eigenen Interesse ist, dass du alles, was du hörst, für dich behältst}
{250}{}{Kann sein. Nach welcher Art Arbeit suchst du?}
{251}{}{Braucht ihr noch eine Wache?}
{252}{}{Ach, nichts Besonderes. Ich frage bloß so.}
{253}{}{Egal was, wenn es gut bezahlt ist, mach' ich's.}
{254}{}{Egal was, solange ich nicht Schwierigkeiten mit dem Gesetz bekomme.}
{255}{}{Warum versuchst du's nicht bei den Händlern? Die sollen recht vernünftig zahlen.}
{256}{}{Nein, haben wir genug. Auf Wiedersehen.}
{257}{}{So was höre ich doch gerne. Vielleicht können wir doch Freunde werden. Ich führ' dich nach unten. Denk aber daran, dass es in deinem eigenen Interesse ist, dass du alles, was du hörst, für dich behältst}
{258}{}{Gut. Folge mir, doch denk daran, dass es in deinem eigenen Interesse ist, dass du alles, was du hörst, für dich behältst.}
{259}{}{Aber klar doch, auf Wiedersehen ... Oh, übrigens: Lüg mich nie wieder an. Ich kann es nicht leiden, wenn man mich verschaukeln will. Nicht viele haben diesen Ratschlag bisher noch erlebt.}
{260}{}{Ein Mann der Tat. Das gefällt mir, auch wenn du nicht alle Tassen im Schrank hast.}
{261}{}{Eine Frau der Tat. Das gefällt mir, auch wenn du nicht alle Tassen im Schrank hast.}
{262}{}{Ja, was willst du? Lass dir was Gutes einfallen.}
{263}{}{Wenn du mit mir reden willst, steck lieber die Waffe weg.}
{264}{}{Hast du Alzheimer? Steck deine Waffe weg, wenn du mit mir reden willst.}
{265}{}{Deine Waffe?}
{266}{}{Nicht schlecht, gar nicht schlecht, du überrascht mich. Ich habe nicht geglaubt, dass du so ein harter Brocken bist. Ich habe normalerweise eine gute Menschenkenntnis, vielleicht bist du genau das, was wir suchen. Bist du an einem Job interessiert?}
{267}{}{Verflixt! Das war ein guter Kampf! Ich hatte schon lange keinen gleichwertigen Gegner mehr, und ich kann mich nicht erinnern, wann ich zum letzten Mal geschlagen wurde. Gut gemacht! Wie wär's mit einem Job?}
{268}{}{Klar, was für ein Job?}
{269}{}{Nein, danke.}
{270}{}{Gerade jetzt kann ich nicht. Ich melde mich wieder bei dir.}
{271}{}{Das ist keine Arbeit für Skags. 'Es' muss schnell und sauber erledigt werden. Der Boss kann dir Einzelheiten sagen, doch es bringt mehr Geld, als du in einem Monat bei den Caravans verdienen würdest. Genau das Richtige für dich.}
{272}{}{Klingt gut, mach weiter.}
{273}{}{Hm, kann ich darüber nachdenken? Ich habe noch 'ne Menge anderes Zeug laufen.}
{274}{}{Nein, glaube ich nicht.}
{275}{}{Klar, aber melde dich so bald wie möglich wieder. Je eher der Job erledigt wird, desto besser.}
{276}{}{Lass es mich wissen, wenn du deine Meinung änderst. Es wäre schade, wenn so ein Talent mit der Bewachung von Caravans vergeudet würde.}
{277}{}{Super, ich glaube, alles läuft genau richtig. Denk aber daran, dass nichts, was unten gesagt wird, nach oben dringt. Okay, auf geht's.}
{278}{}{Ich habe gehört, dass du für den Tod eines Händlers und seiner Frau verantwortlich bist. Ich weiß nicht, worüber ihr euch gestritten habt, und es ist mir auch egal.}
{279}{}{Wer hat dir das erzählt?}
{280}{}{Ich habe keine Ahnung, wovon du sprichst.}
{281}{}{Wuk?}
{282}{}{Lass dir darüber keine grauen Haare wachsen. Niemand hier erledigt so was ohne unser Einverständnis. Es wäre wohl am besten für dich, wenn du unsere Stadt verlässt, solange du noch kannst.}
{283}{}{Glaube ich schon, und wenn du weißt, was gut für dich ist, verlässt du die Stadt, solange du noch kannst.}
{284}{}{Ich dachte, du wolltest den Job nicht. Hoffentlich war es nur ein Missverständnis. Ich zahl' dir die Hälfte, und sei bloß dankbar, dass ich dir überhaupt was gebe. [Kane gibt dir 1500 Hub-Scheine.]}
{285}{}{Danke.}
{286}{}{Oh, tut mir leid, ich dachte, ich habe den Job. Kann ich trotzdem für euch arbeiten?}
{287}{}{Gib mir jetzt den Rest vom Geld, oder du bereust es noch!}
{288}{}{Häh?}
{289}{}{Mal schauen. Decker will unten mit dir reden.}
{290}{}{Du kriegst nichts.}
{291}{}{Ich weiß nicht, was für ein Spiel du spielst, aber wenn du weißt, was gut für dich ist, verlässt du die Stadt, solange du noch kannst.}
{292}{}{Du hast gesagt, du willst den Job nicht. Es überrascht mich, dass du zurückgekommen bist. Es war ein schlimmer Fehler, allein zu kommen. Ich schlage vor, du verlässt die Stadt, solange du noch kannst.}
{293}{}{Ich habe gehört, du bist verantwortlich für den Tod von Jain, der Hohepriesterin. Ich weiß nicht, worüber ihr euch gestritten habt, und es ist mir auch egal, aber wir sind trotzdem dankbar. [Kane gibt dir 1000 Hub-Scheine.]}
{294}{}{Wer hat dir das erzählt?}
{295}{}{Ich habe keine Ahnung, wovon du sprichst.}
{296}{}{Ws?}
{297}{}{Lass dir darüber keine grauen Haare wachsen, und wir können dich wohl nicht einsetzen. Du hast unsere Gesetze gebrochen, doch weil du ein Problem für uns gelöst hast, werden wir dich nicht töten, aber du solltest dich aus dem Staub machen.}
{298}{}{Glaube ich schon, Lügen kann zur gefährlichen Gewohnheit werden. Du hast unsere Gesetze gebrochen, doch weil du ein Problem für uns gelöst hast, werden wir dich nicht töten, aber du solltest dich aus dem Staub machen.}
{299}{}{Ich weiß nicht, was für ein Spiel du spielst, aber ich finde es nicht witzig. Du hast unsere Gesetze gebrochen, doch weil du ein Problem für uns gelöst hast, werden wir dich nicht töten, aber du solltest dich aus dem Staub machen.}
{300}{}{Berühr die Tür nicht, wenn dir dein Leben lieb ist. Ich bin der einzige, der diese Tür öffnen darf.}
{301}{}{Der Kaufmann und seine Frau wohnen westlich von hier. Sie sind an der Ecke Barter Street und Thunder Avenue in den Heights; er hat wahrscheinlich Wachen. Versuch, leise zu sein, und sorg dafür, dass du nicht gesehen wirst. Doch wenn dich jemand sieht, dürfen sie nicht lang genug leben, um es weiterzuerzählen. Wenn du deine kleine Aufgabe erledigt hast, komm wieder hierher. Noch was: Denk nicht einmal daran, zur Polizei zu gehen, das wäre der schlimmste Fehler, den du je machen könntest. Wenn du kannst, versuch, nicht ihre Aufmerksamkeit auf dich zu ziehen, das kann manchmal ziemlich nervtötend sein. [Kane gibt dir 500 Deckel.]}
{302}{}{Gute Arbeit. Hier hast du deine Scripts für deinen ersten Job. [Kane gibt dir 2500 Hub-Scheine.]}
{303}{}{Gute Arbeit beim Händler. Ich erwarte das gleiche Ergebnis bei deinem nächsten Job. Da hast du die letze Zahlung für den ersten Job und die erste Zahlung für den zweiten. [Kane gibt dir 3500 Hub-Scheine.] Du weißt es sicher schon, aber die Children of the Cathedral sind im Süden, etwas nördlich von den Water Merchants. Auch hier gilt: keine 'lebenden' Zeugen.}
{304}{}{Hattest du es eilig, abzuhauen? Du hast deine Scripts nicht bekommen. Da ist dein Geld, Anzahlung und Provision für die Erledigung des ersten Jobs. [Kane gibt dir 3000 Hub-Scheine.]}
{305}{}{He, tolle Arbeit! Du hast vergessen, die Anzahlung für den Job abzuholen, da ist sie mit der Provision. Du hast dich als sehr nützlich erwiesen.}
{306}{}{[Kane gibt dir 5000 Hub-Scheine.]}
{307}{}{Und mehr kriegst du nicht. Jetzt zieh Leine, bevor du es noch bereust.}
{308}{}{Hier ist deine Anzahlung. [Kane gibt dir 1000 Hub-Scheine.] Du weißt es sicher schon, aber die Children of the Cathedral sind im Süden, etwas nördlich von den Water Merchants. Auch hier gilt: keine 'lebenden' Zeugen.}
{309}{}{Mann, das ist eine Menge Kohle. Decker wollte die Zicke endlich tot, da sind deine Scripts. [Kane gibt dir 4000 Hub-Scheine.] Du hast dich als sehr nützlich erwiesen.}
{310}{}{Was zum Teufel willst du? Ich dachte, du wolltest Decker nicht sehen.}
{311}{}{Wollte ich nicht, aber kannst du ihm eine Nachricht von mir übermitteln?}
{312}{}{Klar, ich will ihn sehen, damit ich ihn alle machen kann!}
{313}{}{Tut mir leid, ich habe dich falsch verstanden.}
{314}{}{Stimmt genau, warum sollte ich mich mit so einem Schwachkopf treffen?!}
{315}{}{Grug.}
{316}{}{Taa?}
{317}{}{Wir nehmen keine Skags. Jetzt hau ab, bevor ich mich über dich ärgere.}
{318}{}{Kommt auf die Nachricht an.}
{319}{}{Sag ihm, dass er ein feiges Schwein ist, weil er sich in seiner kleinen Höhle versteckt. Wenn er ein Mann ist, sollte er einmal versuchen, in die echte Welt zu kommen.}
{320}{}{Sag ihm, dass er schon mal um ein Wunder beten kann, denn das braucht er, wenn ich mit ihm fertig bin.}
{321}{}{Habe ich vergessen.}
{322}{}{Sag ihm, dass er mein Vorbild ist und ich seine Arbeit bewundere.}
{323}{}{Sag ihm, dass ich das gleiche mit ihm mache, was er mit dem Kerl gemacht hat, der zuletzt den Laden hier geführt hat!}
{324}{}{Ach ja? Das kann ja amüsant werden.}
{325}{}{Du bist ein Idiot.}
{326}{}{Was bist du, irgendeine Art von Freak? Hau hier bloß ab!}
{327}{}{Oh, das werde ich ihm sicher sagen. Er wird sicher sehr daran interessiert sein ... 'Beten' sagtest du? Ich gebe dir mein 'Wort', er erhält die Nachricht.}
{328}{}{Habe ich dir nicht gesagt, du sollst dich verdrücken? Meine Geduld lässt nach! Wirst du mir jetzt sagen, warum du Decker sehen wolltest oder nicht?}
{330}{}{Ich muss dir gar nichts sagen.}
{331}{}{Tut mir leid, ich wollte einfach einen Job.}
{332}{}{Ich hab' doch schon gesagt, dass es ein Geheimnis ist!}
{333}{}{Nöö!}
{334}{}{Ru?}
{335}{}{Wenn du wieder bei dir bist, kannst du wiederkommen.}
{336}{}{Du kannst ihn sehen, aber gib acht, was du sagst ... Nach dir?}
{337}{}{Nein. Auf Wiedersehen.}
{338}{}{Dieses Geheimnis nimmst du mit ins Grab. Decker wird nie mit einem Skag wie dir sprechen.}
{339}{}{Dann solltest du lieber gehen.}
{340}{}{Ja?}
{341}{}{Lorenzo schickt mich für einen Job.}
{342}{}{Hallo!}
{343}{}{Ich will einen Job.}
{344}{}{Nichts, tschüss.}
{345}{}{Kru.}
{346}{}{Hallo!}
{347}{}{Wie geht's?}
{348}{}{Tschüss.}
{349}{}{Gut.}
{350}{}{Wie geht's den Kindern?}
{351}{}{Schöner Tag heute, nicht wahr?}
{352}{}{Du schaust aber gut aus heute.}
{353}{}{Tschüss ... [Kane blinzelt dich an, als ob er herausfinden wollte, was du im Schilde führst.]}
{354}{}{Nehm ich an. [Kane sieht dich seltsam an.]}
{355}{}{Hast du Zeit dafür?}
{356}{}{Brahmin-Schuhe sind sehr geschmackvoll.}
{357}{}{Nein ... Wolltest du was? [Kane scheint sich langsam über dich zu ärgern.]}
{358}{}{Ja.}
{359}{}{Nein.}
{360}{}{Ich glaub', du brauchst noch 'nen Drink, Bursche.}
{361}{}{Ich glaub', du brauchst noch 'nen Drink, Mädel.}
{362}{}{[Kane wartet ein paar Sekunden.] Also ... was ist los? [Kane schaut sehr verärgert aus.]}
{363}{}{Was ist was?}
{364}{}{Hab' ich vergessen.}
{365}{}{Ach, nichts.}
{366}{}{[Es scheint fast so, als ob Dampf aus Kanes Ohren austritt, und die Adern in seinem Hals treten deutlich hervor.] RAUS MIT DIR! [Ein paar Sekunden später hörst du ihn wieder.] ... HIER! DU SCHWACHKOPF!}
{367}{}{[Kane ignoriert dich zähneknirschend.]}
{368}{}{Hast du's vergessen? [Seufzt.] Warum überrascht mich das nicht? [Schüttelt seinen Knopf ungläubig.] Jetzt aber ... RAUS!}
{369}{}{[Kane schaut eine Wache an und lässt einen Finger um sein Ohr kreisen.]}
{370}{}{Wovon sprichst du eigentlich, zum Henker?}
{371}{}{Das ist KEINE passende Antwort!}
{372}{}{Ich verstehe ... Du gehörst nicht zu ihnen.}
{373}{}{Antwort ... auf WAS? [Kane schaut verwirrt und leicht verärgert.]}
{374}{}{Auf das geheime Kennwort!}
{375}{}{Tut mir leid, aber ich darf nicht darüber reden. Auf Wiedersehen.}
{376}{}{[Kane schaut verärgert, du weißt nicht warum.] Raus hier, du beknackter Arsch!}
{377}{}{[Kane schaut verärgert, du weißt nicht warum.] Raus hier, du beknackte Sau!}
{378}{}{Ich hab' gesagt RAUS HIER, du beknackter Arsch!}
{379}{}{Ich hab' gesagt RAUS HIER, du beknackte Sau!}
{380}{}{Nein, wahrscheinlich nicht. Jetzt HAU AB. [Er schaut nicht belustigt aus.]}
{381}{}{Ich habe keine Kinder!!!!}
{382}{}{Das scheint dich zu belasten. Willst du darüber reden?}
{383}{}{Solltest du aber, die sind sehr nützlich.}
{384}{}{Mary hat was anderes gesagt.}
{385}{}{Wirklich? Das ist seltsam ... Sehr seltsam ...}
{386}{}{WAS? DU ... ICH ... NEIN! Ich will nicht darüber reden!!! Für wen hältst du dich eigentlich? Mach, dass du mir aus den Augen kommst.}
{387}{}{Ich HABE GESAGT, ich will nicht darüber reden!!!}
{388}{}{Äh, ja. Klar, Bursche. Wie du meinst.}
{389}{}{Äh, ja. Klar, Mädel. Wie du meinst.}
{390}{}{Hast du denn welche?}
{391}{}{Also gut. Tschüss!}
{392}{}{[Kane schaut einen seiner Schläger an und zuckt mit den Schultern.]}
{393}{}{Nein, NEIN! Jetzt, raus!}
{394}{}{Mary? Ich kenne keine Mary ... Dafür habe ich keine Zeit!!! Ich weiß nicht einmal, von wem du sprichst. Wenn sie Geld will, soll sie selber mit mir reden!}
{395}{}{ Erfahrungspunkte, weil Kane jetzt richtig schlecht drauf ist.}
{396}{}{[Für einen Sekundenbruchteil meinst du, Kane erröten zu sehen.] Das ist ... [ Er schaut sich schnell um.] ... lieb. Was wolltest du?}
{397}{}{Wann treffen wir uns mal?}
{398}{}{Ach, nichts. Tschüss.}
{399}{}{Ja, ich meine, nein. Ich meine, ich ... Ich kann nicht. Ich ... [Kane verpasst einem seiner Wachen plötzlich einen Kinnhaken.] Worüber grinst du so? [Dann schaut er wieder dich an.] Was machst du noch hier?}
{400}{}{[Kane ignoriert dich.] Was willst du?}
{401}{}{Wie geht's den Kindern?}
{402}{}{Schöner Tag heute, nicht wahr?}
{403}{}{Da lang.}
{404}{}{Du kennst den Weg, gehen wir.}
{405}{}{Aufmachen, Jungs.}
{406}{}{In Ordnung.}
{407}{}{Okay.}
{408}{}{Du kannst wollen, soviel du magst, jetzt zieh Leine.}
{409}{}{Hast du noch weitere Jobs?}
{410}{}{Hallo!}
{411}{}{Nichts, tschüss.}
{412}{}{Acru!}
{413}{}{Hallo nochmals.}
{414}{}{Was? Du hattest nicht den Nerv, stimmt's? [Er flüstert dir zu.] Keine Sorge, man gewöhnt sich daran. Wenn er Wachen hat, versuch' zu warten, bis sie weg sind. Irgendwann müssen die auch essen, klar? Versuch, sie abzulenken. Tu alles, was notwendig ist. Versager akzeptieren wir nicht. Mach's, dann kriegst du dein Geld, und dann kannst du 'ne Fliege machen. Also ... brauchst du wirklich was?}
{415}{}{Warum ist 'es' noch nicht erledigt? Mach's lieber bald. Ich möchte dich erst wieder sehen, wenn du gute Nachrichten bringst, sonst haben wir ein Problem. Enttäusch uns lieber nicht.}
{416}{}{Das war's. Du hast deinen letzten Fehler gemacht. Verlass lieber die Stadt, wenn du nicht hier bleiben willst ... zwei Meter unter der Erde.}
{417}{}{Also ... machst du den Job oder nicht? Sie sind genau da. [Kane zeigt noch einmal auf die Stadtkarte in deinem PIPBoy.] Beeil dich, der Boss möchte es bald erledigt haben.}
{418}{}{WAS ZUM TEUFEL ... [Kane blickt sich um, dann flüstert er.] Was zum Teufel machst du hier? Erledige lieber den anderen, und lass bloß 'keine' Zeugen davonkommen.}
{419}{}{Das war's. Du hast's vermasselt. Jetzt musst du für deine Fehler zahlen. Hoffentlich hast du nicht geplant, hier zu übernachten.}
{420}{}{Du hast deinen kleinen Job noch nicht erledigt. [Er flüstert.] Du weißt, was auf dem Spiel steht. Du tust es und wirst reich, und wir sind alle glücklich. Wenn du versagst, wird niemand glücklich.}
{421}{}{Wenn du Probleme mit deinem Job hast, warte ab, bis sie allein ist.}
{422}{}{Dir läuft die Zeit davon, und ich verlier' die Geduld.}
{423}{}{Ich mach's nicht.}
{424}{}{Sie ist bald tot.}
{425}{}{Häh.}
{426}{}{Ach nicht? Wie schade. Wir brauchen keine Leute, die ihr Wort geben und es dann brechen. Schade, dass wir nicht zusammenarbeiten konnten. 'Schönen' Tag noch.}
{427}{}{Okay! Ich mach' den blöden Job. Aber halt lieber das Geld parat, wenn ich fertig bin.}
{428}{}{Danke.}
{429}{}{Oh, das habe ich dann. Keine Sorge.}
{430}{}{Du lebst also noch! Tja, in letzter Zeit hast du dir nicht allzu viele Freunde geschaffen. Hoffentlich hältst du die Augen offen.}
{431}{}{[Kane schaut selbstzufrieden aus. Er steht da und grinst böse.]}
{432}{}{Na also! Ich bin überrascht, dass du noch am Leben bist. Du hast also überlebt, das ist sehr beeindruckend. Ich lass' dich wohl leben, soviel hast du verdient. Jetzt mach dich auf die Socken.}
{433}{}{Denk nicht mal daran.}
{434}{}{Ich verfehle nie.}
{435}{}{Ich erlaube dir zu leben, sei dankbar.}
{436}{}{Ich glaube nicht, dass du mich prüfen willst.}
{437}{}{Ich hoffe für dich, dass du das nicht benutzen willst.}
{438}{}{Du solltest gehen.}
{439}{}{Sei nicht dumm.}
{440}{}{Das wirst du bereuen.}
{441}{}{Du bist entweder mutig oder SEHR blöd, dass du deine Visage hier zeigst, aber keine Sorge, wir kommen mal vorbei, um 'hallo' zu sagen.}
{442}{}{[Kane funkelt dich an.]}
{443}{}{Du hast meine Abschiedsfeier überlebt ... Ich weiß nicht, wie du das geschafft hast, ich muss dich unterschätzt haben. Geh jetzt, und ich lass' dich vielleicht leben.}
{444}{}{[Kane ignoriert dich, hat aber seine Waffe schußbereit.]}
{445}{}{In Ordnung! Raus mit dir!}
{446}{}{Ich sag's nicht noch einmal. Hau bloß ab.}
{447}{}{Ich habe dich gewarnt. Okay, Jungs, schnappt ihn euch!}
{448}{}{Ich habe dich gewarnt. Okay, Jungs, schnappt sie euch!}
{449}{}{Lass mich in Ruhe, mach deine Arbeit. Du musst einen Job erledigen, also mach das lieber.}
{450}{}{Würdest du endlich was machen? Ich hab' dir schon gesagt, was zu tun ist. Also tu's!}
{451}{}{Ich weiß, dass du den blöden Job erledigt hast. Musst du mir nicht erzählen. Mit Decker musst du reden.}
{452}{}{Ich hab' dir gesagt, dass du mit Decker reden musst!}
{453}{}{[Kane wirft dir einen tödlichen Blick zu.] Also dann ... Ich versuch', dich reinzubringen, damit du ihn bald siehst. Ich kann dich ihm auch 'Stück für Stück' zeigen.}
{454}{}{Schade, dass du das so siehst. Hoffentlich 'genießt' du den restlichen Aufenthalt hier in unserer wunderschönen Stadt.}
{455}{}{[Kane ignoriert dich.]}
{456}{}{[Kane starrt dich einige Sekunden an.] In Ordnung. Ich geb' dir eine letzte Chance, ihn zu sehen. Komm mit mir.}
{457}{}{[Kane starrt dich einige Sekunden an.] Du hast deine Chance vertan. Verzieh dich.}
{458}{}{Was machst du bloß da hinten?!?! Du bist ja wohl ein noch größerer Idiot, als ich dachte. Ich hab' gewusst, dass Decker keinen Unbekannten hätte anheuern sollen.}
{459}{}{Worüber sprichst du?}
{460}{}{Häh?}
{461}{}{[Kane senkt die Stimme.] Du hast den Auftrag verbockt, du Schwachkopf! Du hättest beide Hightowers umlegen sollen! Nicht verwunden zum Teufel noch mal! Sobald du die Heights verlassen hattest, sind die mit ihren Wachen abgehauen. Glaub mir, die haben keine Zeit mit dem Packen verschwendet. Keine Ahnung, wo die jetzt sind!}
{462}{}{Naja, was kann ich da sagen? Tut mir leid.}
{463}{}{Ugh ... Leid.}
{464}{}{Leid tun reicht nicht. Du setzt Decker einem nicht akzeptablem Risiko aus. Du kannst dich von jetzt an als Feind des Untergrunds betrachten. Ich möchte deine Visage hier nie mehr sehen.}
{465}{}{Du kommst nicht durch die Tür, solange Kane noch da ist.}
