{100}{}{Die Tür ist verschlossen.}
{101}{}{Du brichst das Schloß auf.}
{102}{}{Du versuchst, das Schloß aufzubrechen, schaffst es aber nicht.}
{103}{}{Du fummelst so lange am Schloß herum, bis es klemmt.}
{104}{}{Die Tür ist unverschlossen.}
