{100}{}{Du hast Larry erzürnt.}
{101}{}{Du siehst Larry.}
{102}{}{Wenn du den Boss störst, schlägt er dich.}
{103}{}{Menschen sind in Necropolis nicht erlaubt. Du kommst mit mir.}
{104}{}{Aber . . .}
{105}{}{Niemals!}
{106}{}{Hngh!!}
{107}{}{Stirb, Mensch!}
{108}{}{Der Mutant ignoriert dich.}

{1000}{}{Wasser}
{1001}{}{Necropolis}
{1002}{}{Set}
{1003}{}{Wasserstelle}
{1004}{}{Halle}
{1005}{}{Lou}
{1006}{}{Ghuls}
{1007}{}{Normalos}

{1100}{}{Keine Ahnung.}
{1101}{}{Du bist mittendrin.}
{1102}{}{Er ist ein Schwächling. Wir sollten ihn und seine Ghuls einfach ausradieren.}
{1103}{}{Das ist hier.}
{1104}{}{Keine Ahnung.}
{1105}{}{Er Harrys Boss.}
{1106}{}{Mieses Zeugs.}
{1107}{}{Feiger als Ghuls.}
