{100}{}{Du siehst einen Knight.}
{101}{}{Hallo, Neuling. Ich bin Larry, wie kann ich dir helfen?}
{102}{}{Vree hat gesagt, du könntest mir eine Laserpistole zeigen.}
{103}{}{Vree hat gesagt, du könntest mir eine Laserpistole geben.}
{104}{}{Ägh.}
{105}{}{Äh, okay ...}
{106}{}{Äh ... ja. Die Dinger sind einfach toll. Sie haben eine Reichweite von ... naja ... so weit man eben sehen kann ... [Es scheint Stunden zu dauern, bis Larry mit seinem Vortrag fertig ist, doch du konntest sogar ein paar nützliche Dinge über den Gebrauch von Energiewaffen aufschnappen.]}
{107}{}{Häh? Aber sie weiß doch, dass die noch nicht fertig sind ... Ach, sie hat wahrscheinlich 'zeigen' gemeint. Klar, ich kann sie dir zeigen. Schau, die brauchen Energiezellen, die hergestellt sind aus ... [Es scheint Stunden zu dauern, bis Larry mit seinem Vortrag fertig ist, doch du konntest sogar ein paar nützliche Dinge über den Gebrauch von Energiewaffen aufschnappen.]}
{108}{}{Klar hat sie das! Ich finde, du solltest jetzt gehen, du Eindringling.}
{109}{}{Ich mag keine Lügner, also hau ab!}
{200}{}{Das kann überhaupt nicht stimmen.}
{201}{}{Bitte schön.}
{202}{}{Der Feuermechanismus klemmt immer mal.}
{203}{}{So ist es viel besser.}
{204}{}{Ich hab's fast.}
{205}{}{Das dauert ein Weilchen.}
{206}{}{Das ist das Problem!}
{207}{}{John, ich glaub', ich weiß jetzt, was das Problem ist.}
{208}{}{Scheiße!}
{209}{}{Mist!}
{210}{}{Mein Fehler!}
{211}{}{Ich bin in Ordnung.}
{212}{}{Okay, das hat weh getan.}
{213}{}{Das war meine Absicht.}
{214}{}{Warum passiert das immer wieder?}
{215}{}{Meine Augen!}
{216}{}{Du bist kein Knight.}
{217}{}{Ich muss mit einem Knight reden.}
{218}{}{Das versteh' ich nicht, die Energiezellen haben immer wieder mal einen Kurzschluss.}
{219}{}{Geh lieber ein bisschen weiter weg, die können nämlich gefährlich werden.}
{220}{}{Lenk mich bitte nicht ab.}
{221}{}{Pass auf, wo du dich hinstellst.}
{222}{}{Verlaufen?}
{223}{}{Tut mir leid, aber ich kann mich jetzt nicht unterhalten.}
{300}{}{Deine Fähigkeit 'Energiewaffen' steigt um 5 %.}
