{100}{}{Du siehst einen zwielichtigen Typen.}
{101}{}{Pssst! Komm' her.}
{102}{}{Also, was machst'n im Hub?}
{103}{}{Ich glaube nicht, dass dich das irgendwas angeht.}
{104}{}{Warum?}
{105}{}{Ich suche was, was ich brauche.}
{106}{}{Wo is' meine Mami?!?}
{107}{}{Bin mir nicht so sicher, du Kerl. Wir sehen uns.}
{108}{}{Ähh.}
{109}{}{Is' schon gut. Wollt' nur sehen, ob ich als guter Nachbar helfen kann. [Lemmy dreht sich weg]}
{110}{}{Also, du schaust aus wie 'n Geschäftsmann. Ich bin auch ein Geschäftsmann, und ich hab' gedacht, wir könnten über, äh, Geschäfte, äh, reden.}
{111}{}{Na, was machst du so hier?}
{112}{}{Ich beschäftige mich mit dir!}
{113}{}{Mit deinen "Geschäften" will ich nichts zu tun haben.}
{114}{}{Na, wir haben doch alle unsere Bedürfnisse. Vielleicht kann ich dir 'n bisschen helfen. Was für Bedürfnisse hast'n du?}
{115}{}{Also, ich suche nach einem Steuerchip. Ich brauche einen für meine Leute.}
{116}{}{Bedürfnisse, was? Ich höre Bedürfnisse, aber was verstehst du schon von Bedürfnisbefriedigung?}
{117}{}{Ich habe das Bedürfnis nach Informationen.}
{118}{}{Ich brauche sicher nichts von dem, von dem du sprichst.}
{119}{}{Ich mach' ein bisschen dies, ein bisschen das. Ich besorge Informationen und Sachen für Leute, egal, was die brauchen oder suchen.}
{120}{}{Ich brauche einiges.}
{121}{}{Irgendwas, was du mir genauer beschreiben kannst?}
{122}{}{Ich suche einen Steuerchip zur Wasserreinigung. Du hast nicht zufällig einen?}
{123}{}{Wir sehen uns.}
{124}{}{Steuerchip, hmmmm. Ich glaub', von den Dingern hab' ich noch nie gehört. Wenn ich du wär', würd' ich's bei den Water Merchants versuchen. Die haben das ganze Wasser hier im Griff.}
{125}{}{Was machst du hier so?}
{126}{}{Was willst du noch wissen?}
{127}{}{Danke für die Information.}
{128}{}{Kein Problem. Wenn's noch was gibt, was du willst, komm' gleich zu Lemmy und sprich mit ihm.}
{129}{}{Du suchst Informationen, was? Als ehrwürdiger Geschäftsmann habe ich Ausgaben, deshalb brauch' ich ein paar Deckel, damit ich dir sagen kann, was du wissen musst. Gut, das wäre geklärt. Was willste denn wissen?}
{130}{}{Du glaubst also, dass ich ein bisschen mehr über dieses Steuerchip-Dingsbums weiß, was? Du könntest recht haben. Das kostet dich aber was. Ich glaub', 500 Deckel sollten reichen.}
{131}{}{In Ordnung, was ist die Info?}
{132}{}{Ich geb' dir 400.}
{133}{}{Ich glaub, du musst es mir gleich sagen, ohne die Scheiß-Deckel!}
{134}{}{Zu viel für meinen Geschmack.}
{135}{}{Na, na, na. Ich wär' nicht der, der ich bin, wenn ich Information für weniger hergäb' als sie wert is'. Komm' wieder, wenn du die Deckel hast.}
{136}{}{Willste den armen alten Lemmy einschüchtern, was? Also, ich hab' keine Angst vor Typen wie dir. Wir sehen uns.}
{137}{}{[Lemmy nimmt dein Geld]}
{138}{}{Also gut, ich nehm' eben das.}
{139}{}{OK, OK, OK, schau', ich hab' nur 'n Spaß gemacht mit dem Geld. Guter Witz, was?}
{140}{}{Pass' auf, das weiß ich über die Steuerchips: Soweit ich gehört hab', kamen die mal alle aus den Vaults. Wenn ich einen suchen würd', würd' ich schauen, wo der Rest von den Vaults ist. Ich weiß nich' genau, wo die ganzen Vaults sind, doch ich hab' gehört, dass es hier in der Gegend so um die 4 gibt.}
{141}{}{Ich möchte dir noch ein paar Fragen stellen.}
{142}{}{Danke.}
{143}{}{Klar, was willste noch wissen?}
{144}{}{Gibt's was über die Steuerchips, das du mir erzählen kannst?}
{145}{}{Was weißt du über Decker?}
{146}{}{Weißt du irgendwas über die fehlenden Caravans?}
{147}{}{Ich suche nach einem gewissen Gut, wenn du weißt, was ich meine.}
{148}{}{Jetzt gerade nichts.}
{149}{}{Also, normalerweise bin ich nicht dagegen, Information zu verkaufen, aber über Mr. Decker kriegst du nichts aus Lemmy raus.}
{150}{}{OK, aber kann ich dich noch ein paar Sachen fragen?}
{151}{}{Danke.}
{152}{}{Fehlende Caravans, was? Darüber könnte ich 'n bisschen wissen. Das kostet dich aber 300 Deckel.}
{153}{}{In Ordnung, was weißt du?}
{154}{}{Ich geb' dir 240.}
{155}{}{Ich glaub', du musst es mir gleich sagen, ohne die Scheiß-Deckel!}
{156}{}{Zu viel für meinen Geschmack.}
{157}{}{Also, ich bin nicht ganz sicher, aber was man so hört, ist es nicht das, was jeder glaubt. Irgendein neuer Typ mit Mutanten rum. Aber erzähl' nicht rum, dass du das von mir hast.}
{158}{}{Klar. Kann man irgendwas von dir herumerzählen, Lemmy?}
{159}{}{Kann ich dir noch 'ne Frage stellen?}
{160}{}{Danke.}
{161}{}{Spielst du vielleicht drauf an, dass Lemmy kein Rückgrat hat? Da hast du recht. Aber Lemmy LEBT noch.}
{162}{}{OK, vergiss es. Kann ich dir noch 'ne Frage stellen?}
{163}{}{Wenn's nach mir geht, liegst du bald unter der Erde und lebst nicht mehr!}
{164}{}{Vergiss es. Bis bald.}
{165}{}{Zeug für Bedürfnisse, was? Also, ich kenn' einen Typen in der Old Town drüben, der kann dir wahrscheinlich so'n Zeug besorgen. Weißte was? Der will wissen, wer du bist, bevor du bei ihm aufkreuzt.}
{166}{}{Lass mich raten. Diese "Einladung" wird mich "was kosten"?}
{167}{}{Ich she' schon, wohin das führt. Ich finde ihn auf eigene Faust.}
{168}{}{Genau. Also, ich glaub'... nur für dich, klar... 1000 Deckel, damit du mit dem Typ reden kannst, ohne, dass er dich gleich fertig macht.}
{169}{}{In Ordnung, ich zahl' deinen Preis.}
{170}{}{Wie wär's statt dessen mit 800 Deckeln?}
{171}{}{Wenn du mich so magst, Lemmy, warum machst du's nicht umsonst? [Du spannst gleichzeitig deine Muskeln an]}
{172}{}{Kann ich mir nicht leisten.}
{173}{}{Also, du musst rüber in die Old Town. Da gibt's 'nen Typen, der heißt Vance. Red' mit ihm. Wie gesagt, ich lass' ihn wissen, dass du kommst.}
{174}{}{Du hast ein Herz aus Gold. Kann ich dich noch ein paar Sachen fragen?}
{175}{}{Danke.}
{176}{}{Tut mir leid, Mann, ich hab' zu tun. War aber nett, mit dir zu plaudern.}
{177}{}{Na, biste zurückgekommen, um mit deinem alten Freund Lemmy zu reden, was? Womit kann ich dir helfen?}
{178}{}{Also, du schaust aus wie 'ne Geschäftsfrau. Ich bin auch ein Geschäftsmann, und ich hab gedacht, wir könnten über, äh, Geschäfte, äh, reden.}
