{100}{}{Du siehst einen Bauern.}
{101}{}{Oh, klar, großer Mann läuft vor schlimmen Hund weg. Phil, du hast's ihm aber gezeigt. Wirklich toll.}
{102}{}{Was machst du da, Phil? Prüfst die Sohle von deinen Turnschuhen, was?}
{103}{}{Mann, schaut der Hund hungrig aus. Der will dich sicher bei lebendigem Leib auffressen, Phil.}
{104}{}{Das ist doch ein bisschen übertrieben für ein armes wehrloses Tier, findest du nicht?}
{105}{}{Da hast du aber einen netten Köter.}
{106}{}{Ich bin sicher, dass Phil dankbar wäre, wenn du ihm den Hund vom Hals schaffst.}
{107}{}{Danke, dass du das mit dem Hund geregelt hast.}
{108}{}{Du siehst Lenore.}
