{100}{}{Du siehst Leone.}
{101}{}{Wenn du Gesellschaft brauchst, such' dir 'ne Nutte. Ich hab' zu tun.}
{102}{}{Erst wenn's der Boss sagt. Ignorier' ihn, und er wird sich schon verziehen.}
{103}{}{Erst wenn's der Boss sagt. Ignorier' sie, und sie wird sich schon verziehen.}
{105}{}{Lass' mich in Ruhe. Jeder kann ein Knie kaputtmachen oder 'nen Finger brechen. Hat aber nich' mehr die gleiche Wirkung wie früher.}
