{100}{}{Du siehst Lyle.}
{101}{}{Du bist also der Wasserdieb! Du Verräter!}
{102}{}{Ich bin so froh, dass die Tortur endlich vorbei ist. Danke.}
{103}{}{Hallo, }
{104}{}{.}
{105}{}{Hallo Lyle. Wie läuft´s so?}
{106}{}{Uns geht´s hier ganz gut. Aber ich hoffe, dass du den Steuerchip bald findest.
 Alle sind total überreizt, und wir haben nicht mehr viel Zeit.}
{107}{}{Wahnnnngh!}
{108}{}{Nicht besonders gut. Seit man mir neulich eine meiner Wasserrationen
 geklaut hat, geht alles den Bach runter. Alle sind verängstigt, und niemand
 weiß, wie es weitergehen soll.}
{109}{}{Das ist wirklich hart. Ich hoffe, es geht bald wieder aufwärts.}
{110}{}{Ich kümmere mich darum und schau mal, was ich tun kann.}
{111}{}{Ja, das hoffe ich auch.}
{112}{}{Danke. Ich hoffe wirklich, dass du dem Ganzen auf den Grund gehen
 kannst. Aber mach schnell und finde einen neuen Steuerchip. Dieser Wahnsinn
 wäre nicht passiert, wenn wir einen funktionierenden Chip hätten!}
{113}{}{Ich danke dir dafür, dass du diesen Dieb geschnappt hast. Gute Arbeit! Aber
 bitte beeile dich und finde den Chip, sonst war alles vergebens!}
{114}{}{Wie konntest du uns so verraten? Geh mir aus den Augen!}
