{100}{}{Du siehst einen kräftigen und massigen Mann mit einem buschigen Bart.}
{101}{}{Du siehst MacRae.}
{102}{}{Hallo Junge, nach was suchst du heute?}
{103}{}{Hallo, Mädchen, nach was suchst du heute?}
{104}{}{Hi, was möchtest du noch wissen?}
{105}{}{Wer bist du?}
{106}{}{Was kannst du mir über die Blades erzählen?}
{107}{}{Nichts, danke.}
{108}{}{Also ich bin MacRae. Ich helf den Blades ein bißchen gegen die Deathclaws
 und diese Regulatortruppe. Bring denen ein paar Sachen bei, damit
 sie sich gegen diese teuflischen Typen schützen können.}
{109}{}{Was für Zeug bringst du ihnen bei?}
{110}{}{Hast du die Deathclaws gesehen?}
{111}{}{Was ist mit den Regulators?}
{112}{}{Kann ich dich was anderes fragen?}
{113}{}{Also meine Spezialität ist der Faustkampf, und ich kann
 ein paar Schläge mehr einstecken, als jeder Bursche, der gegen mich antritt.}
{114}{}{Klingt ziemlich bescheuert, ich würde dazu lieber eine Waffe benutzen.}
{115}{}{Denkst du, du könntest mir was beibringen?}
{116}{}{Kann ich dich was anderes fragen?}
{117}{}{Also, wenn du so denkst, kannst du gleich wieder umkehren und verschwinden.}
{118}{}{Naja, scheinst ein guter Junge zu sein, aber ich hab keine Zeit,
 denn ich muß den Blades was beibringen. Aber wenn sich alles geklärt hat,
 hab ich vielleicht mehr Zeit.}
{119}{}{Ok, kann ich dich was anderes fragen?}
{120}{}{Danke für die Auskunft.}
{121}{}{Gesehen hab ich sie. Gerannt, als wär der Teufel hinter mir her, bin ich.
 Wenn du sie suchst, dort findest du sie. [MacRae deutet in Richtung Osten]}
{122}{}{Ich hab gedacht, die Deathclaws sind eine unnatürliche Brut, aber in
 Wirklichkeit sind die Regulatoren das Böse. Komm einmal im Monat oder so
 her, und sie zeigen dir ihr wahres Gesicht. Die schleifen einen Vater von
 seinen Kindern weg.}
{123}{}{Kann ich dir irgendwie helfen?}
{124}{}{Klingt nicht gut. Kann ich dir noch eine andere Frage stellen?}
{125}{}{Danke für die Auskunft.}
{126}{}{Du willst mit Razor sprechen. Wenn´s hier jemals ein gutes Mädchen gegeben
 hat, dann sie.}
{127}{}{Die Blades sind eine gute Truppe. Hier zwischen den verdammten
 Regulatoren und den Deathclaws festzuhängen - das ist kein sehr
 glückliches Dasein. Aber sie haben´s überlebt.}
{128}{}{[MacRae klopft dir auf die Schulter] Dir ist es zu verdanken,
 daß die Blades bald ein besseres Leben führen können. Also, was kann
 ein alter Schotte für dich tun?}
{129}{}{Du hast vorhin gesagt, daß du mir was beibringen könntest,
 wenn du mehr freie Zeit hättest.}
{130}{}{Was hast du bis jetzt gemacht?}
{131}{}{Was treibst du hier?}
{132}{}{Kein Problem.}
{133}{}{Naja, es ist ein kleines bißchen still hier geworden, seit die Blades Adytum mit den
 Regulatoren geholfen haben. Meine Lehrerdienste sind nicht mehr so sehr gefragt.}
{134}{}{Was lehrst du?}
{135}{}{Das tut mir aber leid. Ich hoffe es wird wieder aufregender.}
{136}{}{Kannst du mir was beibringen?}
{137}{}{Klingt zwar interessant, aber ich muß jetzt gehen.}
{138}{}{Also ich denk mal, ich hab die Zeit übrig. Warum fangen wir nicht gleich an? [MacRae beginnt
 damit, einige Kampfstellungen zu demonstrieren und zeigt dir, wie du Schläge genauso einstecken
 kannst wie ein echter Schotte.]}
{139}{}{Du lernst schnell. Hoffe, das hilft dir auf deinen Reisen.}
{140}{}{Naja, ich hab den Blades ein bißchen geholfen. Hab ihnen
 beigebracht, wie sie sich vor den Deathclaws und den Regulatoren
 schützen können. Seitdem du das jetzt übernommen hast, ist
 es hier ziemlich fad geworden.}
{141}{}{Ok. Bis bald.}
#
##Sduibek, Fallout Fixt:
#
{200}{}{ Erfahrungspunkte für das Lernen, wie ein Schotte zu kämpfen.}
