{100}{}{Du siehst einen durchgedrehten Wissenschaftler. Er arbeitet eifrig an etwas herum.}
{101}{}{Guten Abend, Bruder. Was verschlägt dich in unser himmlisches Nest?}
{102}{}{Guten Abend, Schwester. Was verschlägt dich in unser himmlisches Nest?}
{103}{}{Ich will mir euren Fortschritt ansehen.}
{104}{}{Was willst du hier?}
{105}{}{Was?! Du wagst es, mich auszufragen? Was würdest du davon halten, wenn
 ich dein Gehirn für ein Experiment benutzen würde, du närrischer Hornochse?!}
{106}{}{Würg.}
{107}{}{Du schon wieder? Und aus welchem Grund störst du die ruhmreiche Zukunft des
 Meisters dieses Mal?}
{108}{}{Deine Mißerfolge lassen den Meister langsam ungeduldig werden, und mir geht´s
 mit deinem unverschämten Benehmen genauso.}
{109}{}{Ich möchte wissen, was aus deinen Versuchen geworden ist.}
{110}{}{Das war´s, ich blas dir das Licht aus und zwar hier und jetzt, Hornochse!}
{111}{}{Uuahh!}
{112}{}{Es hat nicht geklappt. Ich hab den FEV direkt in die
 Zirbeldrüse injiziert, aber ich hab nicht die gewünschten Ergebnisse erzielt.}
{113}{}{Warum hast du ihn nicht direkt in die Amygdala injiziert?}
{114}{}{Warum hast du ihn nicht direkt in die Medula injiziert?}
{115}{}{Welche Ergebnisse hast du erzielt?}
{116}{}{Hmmm. Und?}
{117}{}{Bitte verzeihen Sie mir, Sir. Wie kann ich dienen?}
{118}{}{Bitte verzeihen Sie mir, meine Liebe. Wie kann ich dienen?}
{119}{}{Entweder du sprichst das nächste mal respektvoller mit mir, oder
 du sprichst überhaupt nie mehr mit irgendjemanden!}
{120}{}{Die Wahrheit des Meisters hat sich offenbart und hat die psychischen
 Fähigkeiten gesteigert. [Er schüttelt den Kopf] Aber die armen Seelen sind schließlich
 wahnsinnig geworden und mußten abgetrennt und vernichtet werden. Nur so konnte
 verhindert werden, daß sie sich selber oder anderen Leuten was antun.}
{121}{}{Oh, wie rücksichtsvoll von dir...}
{122}{}{Wo sind sie?}
{123}{}{Du herzloser Metzger! Ich glaub ich löse dein Hirn auch auf und trenne
 es vom Rest deines Körpers. Fahr zur Hölle, Dreckskerl!}
{124}{}{In einem Raum, nordwestlich von hier. Kann ich noch etwas für dich tun?}
{125}{}{Danke für deine Hilfe. Wiedersehen.}
{126}{}{Ja, äh. Was ist FEV?}
{127}{}{Fahr zur Hölle!}
{128}{}{Ich hab keine Zeit für deinen Unfug!}
{129}{}{Was für eine faszinierende Idee! Das muß ich sofort ausprobieren!}
{130}{}{Äh, wo hast du die mißlungenen Versuche?}
{131}{}{Reden wir nicht darüber.}
{132}{}{Ja! Versuchen wir es an dir!}
{133}{}{Vincent! Bereite unseren neuesten Freiwilligen vor!}
{134}{}{Wie bitte? Das ist das Lächerlichste, das ich jemals gehört habe! [Das kommt dir
 verdächtig vor] Wer bist du nun wirklich?}
{135}{}{Oh, tut mir leid. Muß jetzt gehen.}
{136}{}{Ich bin ein neuer..äh...Bursche.... Ich bin geschickt worden, um rauszufinden, wie´s dir
 geht.}
{137}{}{Ich hab dir doch schon erzählt, daß der Meister mich hergeschickt hat, um
 dich zu überprüfen.}
{138}{}{Ich bin hier, um dir deine Milz rauszunehmen... und zwar ohne Narkose!}
{139}{}{Na, wenn das so ist. Wie läuft´s denn nun?}
{140}{}{Dein Verhalten reicht mir als Antwort. Wiedersehen.}
{141}{}{Aha! Ein Eindringling! Wie ich vermutet hab. Vincent!}
{142}{}{Wer bist du? Und warum hast du diesen Anzug an? [Zu sich selber] So einen hab ich
 schon eine Ewigkeit nicht mehr gesehen.}
{143}{}{Das ist eine Verkleidung. Eindringlinge sind in das Heiligtum des Meisters
 eingefallen, und ich habe ihre Klamotten angezogen, um mir ihr Vertrauen zu erschleichen.}
{144}{}{Wie kannst du es wagen, einen der besten Leute des Meisters auszufragen!}
{145}{}{Wann hast du so einen Anzug wie diesen schon mal gesehen?}
{146}{}{Er ist aus Gummi. Ich kann dein Blut ganz leicht abwischen,
 nachdem ich dich ausgelöscht hab!}
{147}{}{Ach, weißt du, als wir die letzte Lieferung von reinrassigen Menschen
 reinbekamen....ich glaube da ist sogar noch einer in den Käfigen. Warum willst du das wissen?}
{148}{}{Nur so. Wie läuft´s mit den Versuchen?}
{149}{}{Ich muß meinen Bericht beim Meister abliefern. Hab keine Zeit für sowas.}
{150}{}{[schüttelt den Kopf] Leider sind die armen Seelen schließlich
 wahnsinnig geworden und mußten getrennt und vernichtet werden. Nur so konnte
 verhindert werden, daß sie sich selber oder anderen Leuten was antun.}
{151}{}{Oh, wie rücksichtsvoll von dir...}
{152}{}{Du herzloser Dreckskerl! Ich glaub ich löse dein Hirn auch auf und trenne
 es vom Rest deines Körpers. Fahr zur Hölle, Hundesohn!}
{200}{}{Du siehst Vincent, einen Wächter der Supermutanten. Er sieht gelangweilt aus.}
{201}{}{Du siehst einen Supermutanten, der offensichtlich die Wissenschaftler bewacht. Er
 sieht gelangweilt aus.}
{202}{}{Eindringlinge!}
{203}{}{Ich bewache nur die Verrückten. Sprich mich nicht an.}
{204}{}{Laß mich allein.}
{300}{}{Du siehst einen schlafenden, verrückten Wissenschaftler.}
{301}{}{Zzzzzz}
{302}{}{Hä! Was? [Reibt sich die Augen] Vincent, entferne diesen Heiden aus unseren Räumen!}
{303}{}{Hä? [schnarcht] ...zzzzzzzzz}
{400}{}{Du siehst Vincent. Er bewacht die schlafenden Verrückten.}
{401}{}{Du siehst einen Wächter der Supermutanten. Er steht fast direkt über den liegenden Körpern.}
{402}{}{Laß sie in Ruhe und verschwinde von hier. Niemand darf hier rein, während sie schlafen.}
{403}{}{Du schon wieder! Hab ich dir nicht gesagt, du sollst die Wissenschaftler in Ruhe lassen?}
{404}{}{Du bist schon länger hier als erwünscht.}