# This file is new for Fallout Fixt. Most entries moved here from ARTIFACT.MSG!
#
{100}{}{Du siehst die Holo-Disk, die Maxson dir gegeben hat.}
{101}{}{Der PIPBoy zeigt an: Datei im System gefunden. Ladevorgang abgebrochen.}
{102}{}{Der PIPBoy zeigt an: Daten werden von Disk geladen.}
#
# for Fallout Fixt:
#
{103}{}{Diese Holodisk hat das Symbol der Brotherhood of Steel eingraviert und ist in einwandtfreiem Zustand. Kann in den PIPBoy geladen werden.}
{104}{}{Du siehst: Maxsons Disk.}
