{100}{}{Die Tür ist verschlossen. Um sie zu öffnen, brauchst du einen
 Sicherheitscode.}
{101}{}{Du gibst den Code ein, der auf dem Band ist und öffnest die Tür.}
{102}{}{Die Tür ist nicht verschlossen.}
{103}{}{Du umgehst den Sicherheitscode und öffnest die Tür.}
{104}{}{Es gelingt dir nicht, die Tür zu öffnen.}
{105}{}{Es gelingt dir nicht, die Tür zu öffnen. Du solltest es vielleicht
 mal mit elektronischen Dietrichen versuchen.}
{106}{}{Die Explosion ist zwar gewaltig, aber sie hinterlässt noch nicht
 mal eine Beule in der Sicherheitstür.}
