{100}{}{Du siehst Miles, den Chemiker von Adytum.}
{101}{}{Du siehst einen dünnen Mann in einem weißen Kittel.}
{102}{}{Ich kann es nicht fassen, dass wir uns getroffen haben. Ich bin Miles. Was kann ich für dich tun?}
{103}{}{Ach, ich schau nur so rum, danke.}
{104}{}{In diesem Kittel siehst du aus wie ein Wissenschaftler. Mit was beschäftigst du dich?}
{105}{}{Wie?}
{106}{}{Gut, schönen Aufenthalt in unserer kleinen Stadt.}
{107}{}{Ich bin Chemiker. Meistens stelle ich Zündmasse und Pulver her. So können wir die Messinghüllen der Kugeln wiederbenutzen. Aber ich plansche auch noch mit anderen Chemikalien rum.}
{108}{}{Also stellst du Kugeln für Adytum her?}
{109}{}{Woher bekommst du Schwefel, Kaliumnitrat und all die anderen Chemikalien?}
{110}{}{Mit welchen Chemikalien arbeitest du noch?}
{111}{}{Danke für die Auskunft.}
{112}{}{Ja, obwohl Smitty derjenige ist, der die Kugeln gießt. Ich fülle nur die Messinghüllen wieder auf.}
{113}{}{Aber die Hub-Händler profitieren von dir und der Stadt.}
{114}{}{Es ist schwer jemanden zu finden, der die Chemie zu schätzen weiß! Aber, um auf deine Frage zurückzukommen: Einige Materialien bekommen wir von den Hub Händlern, andere stelle ich selber her oder finde sie irgendwo in der Gegend. Die Misthaufen der Brahmin sind z.B. eine gute Quelle. Oder einige der Pilzarten, die ich anbaue.}
{115}{}{Also ich hab versucht, eine starke Säure herzustellen, die Smitty für seine Kupferstiche verwenden könnte. Außerdem wollte ich einige dauerhafte Farben und Tinte machen, aber das ist nicht so einfach, weil ich nicht an natürliche Tinte rankomme.}
{116}{}{Jederzeit.}
{117}{}{Ohje. Ich fürchte da kann ich dir nicht weiterhelfen.}
{118}{}{Hallo, du wieder. Kann ich dir helfen?}
{119}{}{Naja, wir müssen ja von was leben. Seitdem die Hydroponik-Farmen nicht mehr funktionieren, müssen wir die Lebensmittel von den Händlern kaufen. Das Einzige, was wir zum Verkauf anbieten können, sind die Kugeln.}
{120}{}{Ich könnte versuchen, die Teile zu besorgen, die man braucht, um Hydroponik-Farmen zu reparieren.}
{121}{}{Oh. Das ist wirklich schade.}
{122}{}{Ehrlich? Das wäre wunderbar! Uns fehlen nur noch ein paar Teile, aber wenn du die richtigen Teile auftreiben könntest, wären wir bestimmt in der Lage, autark zu leben! Sammael könnte dir dabei sicher eine Hilfe sein.}
{123}{}{Hast du die Teile schon gefunden?}
{124}{}{Ja, hier sind sie.}
{125}{}{Noch nicht. Wen kann ich schnell wieder nach ihnen fragen?}
{126}{}{Du musst mit Sammael sprechen. Tagsüber findest du ihn normalerweise in einem Zelt, unten bei den Bauernhöfen.}
{127}{}{[Miles sieht sich die Teile an] Das sind sie, aber es sieht aus, als müsste Smitty sie noch bearbeiten. Kannst du sie ihm bringen?}
{128}{}{Ich hab andere Probleme. Kannst du es selber machen?}
{129}{}{Klar, ich komm zurück, wenn er sie fertig hat.}
{130}{}{Klar, ich bin sehr froh, dass du sie für uns gefunden hast.}
{131}{}{Und . . .}
{132}{}{Kein Problem.}
{133}{}{Oh. Das hätte ich fast vergessen. Hier hast du eine Entschädigung für den Aufwand. [Miles gibt dir einige Deckel und Stimpaks.]}
{134}{}{Könntest du die Teile zu Smitty bringen?}
{135}{}{[Miles nimmt dir die fertigen Teile ab] Sieht ganz so aus, als hätte Smitty sie gut hingekriegt. Danke für deine Hilfe. Hier hast du eine Entschädigung für den Aufwand.}
{136}{}{[Miles gibt dir einige Deckel und Stimpaks.]}
{137}{}{Wenn du auf dem Rückweg wieder hier vorbeikommst, kannst du jederzeit bei Smitty und mir reinschauen. Wir könnten dir eventuell mit einigen guten Änderungen deiner Ausrüstung behilflich sein. Smitty vollbringt mit einigen Waffen wahre Wunder und ich kann dir helfen, wenn es um bestimmte Rüstungsarten geht.}
{138}{}{Sieht so aus, als hättest du eine Powerrüstung gefunden. Ich hab von einem chemischen Prozess gehört, mit dem ich die Oberfläche härter machen könnte. Allerdings fehlen mir noch ein paar Anhaltspunkte, die ich brauche, um die Formel und die notwendigen Reagensen zu bekommen. Soviel ich weiß hat Mrs. Stapleton, die Bibliothekarin des Hubs, einige Zeitschriften und Bücher, die mir weiterhelfen könnten.Wenn du mir die besorgen würdest, könnte ich den Prozess an deiner Rüstung ausprobieren.}
{139}{}{Klingt gut. Ich spreche mal mit Mrs. Stapleton.}
{140}{}{Ich hab echt wichtigere Sachen zu erledigen, als noch was für dich zu besorgen.}
{141}{}{Naja, wenn du deine Meinung mal ändern solltest, geh zu Mrs. Stapleton und komm danach zurück zu mir.}
{142}{}{Warst du schon im Hub bei Mrs. Stapleton?}
{143}{}{Ja, hier sind die Bücher.}
{144}{}{Noch nicht.}
{145}{}{[Miles nimmt dir die Bücher aus der Hand und blättert sie durch.] Hmmmm. Ja, hmmmm. [Er murmelt ein paar Minuten lang vor sich hin.] Gut, ich denke, ich kann damit was anfangen, aber es wird einen ganzen Tag dauern, bis die Verknüpfung zustande kommt. Ist das in Ordnung für dich?}
{146}{}{Kein Problem.}
{147}{}{Sorry, soviel Zeit hab ich nicht.}
{148}{}{Na gut, komm zurück, wenn du die Zeit hast, und ich probiere den Prozess an deiner Rüstung aus.}
{149}{}{[Miles nimmt dir die Rüstung ab.]}
{150}{}{[Miles übergibt dir die Rüstung wieder. Sie scheint etwas mehr zu glänzen als vorher.] So, ich glaub es hat geklappt. Ich hoffe es hilft dir.}
{151}{}{Was ist mit deiner Powerrüstung passiert? Ich kann dir nur helfen, wenn du eine Powerrüstung hast.}
{152}{}{Schön, dich zu sehen, aber ich bin gerade inmitten von Forschungsarbeiten.}
{153}{}{Mit so einer Rüstung kann ich nichts anfangen. Tut mir leid.}

# TODO: TRANSLATE
# Fo1in2:
{154}{}{[Fertig]}

{2000}{}{Ich sehe, du hast eine weitere Powerrüstung auftreiben können. Soll ich sie mir ansehen? 1.000 Deckel sollten meine Kosten decken.}
{2010}{}{Ja, bitte.}
{2020}{}{Ich habe nicht so viel Geld.}
{2030}{}{Nein, danke.}

{2100}{}{Es wird einen ganzen Tag dauern, bis die Verknüpfung zustande kommt. Ist das in Ordnung für dich?}
{2110}{}{Kein Problem.}
{2120}{}{Sorry, soviel Zeit hab ich nicht.}

{2200}{}{Na gut, komm zurück, wenn du die Deckel hast, und ich wende den Prozess auf deine Rüstung an.}

# Upgrade Weapons
{3000}{}{Sure. I could probably do that if you get me some regular fuel. With the chemicals I'd need, this would cost }
{3001}{}{ caps a batch.}
	{3010}{}{Sounds good. I'll take one for }
	{3011}{}{I'll take another batch of improved fuel for }
	{3020}{}{I'll take }
	{3021}{}{I'll take another }
	{3022}{}{ for }
	{3023}{}{ caps.}
	{3030}{}{Looks like I don't have the caps for that.}
	{3040}{}{I've changed my mind. I'll be back later.}

{4000}{}{[Miles takes the flamer fuel from you and starts the refining process.]}
{4001}{}{Here it is. You need anything else?}
	{4010}{}{That's all. Thanks.}

{4100}{}{I see. Well, get back to me once you have the caps and we'll talk again.}

