{100}{}{Du siehst einen dreckigen, schmuddeligen Gefangenen.}
{101}{}{Einer der Gefangenen in der zweiten Zelle ist anders als die anderen. Er steht aufrecht und sieht dir direkt in die Augen.}
{102}{}{Der Gefangene starrt mit einem leeren Blick die Wand an.}
{103}{}{Der Gefangene ignoriert deine Versuche, mit ihm zu sprechen.}
{104}{}{Er sieht dich einen kurzen Augenblick lang wütend an und dreht sich dann weg.}
{105}{}{Sie sieht dich kurz an und sabbert dann.}
{106}{}{Du bekommst keine Antwort.}
{107}{}{Wir sind frei! Wir sind frei!}
{108}{}{Du bist widerlich. Sprich nicht mit mir.}
{109}{}{Quib!}
{110}{}{Du hast nicht das Recht, so mit mir zu sprechen.}
{111}{}{Verstehst du denn nicht? Ich bin gekommen, um euch zu befreien.}
{112}{}{Verarsch' mich nicht.}
{113}{}{Ich habe keine Rechte, und es ist mir egal. Geh' weg, laß' uns in Frieden.}
{114}{}{Ich weigere mich, dir irgendwelche Informationen zu geben. Laß' mich in Ruhe.}
{115}{}{Hng!!}
{116}{}{Ich bin wirklich hier, um euch zu befreien. Ich bin ein normaler Mensch.}
{117}{}{Wenn du meinst. Sicherlich. Wiedersehen.}
{118}{}{Erinnerst du dich nicht, daß du letzte Woche schon diesen Trick probiert hast? Ich bin damals nicht drauf reingefallen, und ich werd´s auch jetzt nicht tun.}
{119}{}{Was? Keine Verkleidung, hinter der du dich verstecken kannst? Deine verräterische Natur ist  offensichtlich.}
{120}{}{Ich bin gekommen, um euch zu befreien.}
{121}{}{Also dann, Wiedersehen.}
{122}{}{Du bist grausam. Laß' uns in Frieden.}
{123}{}{Ich plaudere nicht alles über meine Leute aus. Du kannst einen Mann nicht dazu zwingen, sich selbst zu verraten, du kannst ihn höchstens soweit bringen, daß er aufhört zu leben.}
{124}{}{Du verstehst es einfach nicht. Ich bin ein Mensch, ich bin gekommen, um euch zu retten.}
{125}{}{Ich muß dich nicht einmal dazu bringen, in der Hölle zu verrecken. Du kriegst das schon alleine ganz gut hin.}
{126}{}{Du machst dich immer noch über mich lustig.}
{127}{}{Aus dem Mund eines Mannes kommen nur Lügen.}
{128}{}{Klar, wer´s glaubt. Hau' ab, und laß' uns in Frieden.}
{200}{}{Der Gefangene sieht dreckig und müde aus. Die Bänder, die die Gefangenen um den Hals tragen, 
 glänzen jedoch wie neu.}
{201}{}{Der Gefangene dreht sich um und starrt dich verdutzt an. Du bemerkst, daß er ein Halsband trägt.}
{300}{}{An der Wand befindet sich das Schild: "Kein Eintritt. Sicherheitszone. Nur für Gefängniswärter!"}
{301}{}{Du erhältst}
{302}{}{ Erfahrungspunkte, weil du Gefangene von ihrem Elend befreit hast.}
