{100}{}{Du siehst eine Wache.}
{101}{}{Was treibst du hier so?}
{102}{}{Urg?}
{103}{}{Ich sehe mich nur um.}
{104}{}{Ich möchte ein paar Waffen kaufen.}
{105}{}{}
{106}{}{}
{107}{}{Ich hab' keine Zeit für Witze. Wenn du diese Zone nicht sofort verläßt, schieß ich!}
{108}{}{Wir mögen neugierige Leute nicht. Hau' jetzt ab, sonst schieß ich.}
{109}{}{}
{110}{}{}
{111}{}{Du riechst wie ein Brahma, aber ich wette, du bist nur halb so intelligent.}
{112}{}{}
{113}{}{Ahh, sehr gut. Kunden sind immer willkommen.
 Komm' herein, aber laß' bitte deine Waffe stecken.
 Geh' und suche Zack, er kann dir alles besorgen, was du brauchst.}
{114}{}{}
{115}{}{Ich muß mit deinem Boß sprechen. Es ist sehr wichtig.}
{116}{}{Oh, ok. Gabriel wird mit dir sprechen. Geh' rein.}
{117}{}{Ja, ich erinnere mich an dich. Geh' rein.}
{118}{}{Ich muß mit Gabriel sprechen. Es ist sehr wichtig.}
{119}{}{Ich möchte Zack Waffen abkaufen.}

# Fo1in2:
{200}{}{Sprich mit Zack im Lagerhaus.}
{201}{}{Du kannst reingehen.}
