{100}{}{Dieses Motorrad scheint nicht fahrtüchtig zu sein. Es sieht besser aus als die anderen Fahrzeuge in der Gegend. Vielleicht kann man es reparieren.}
{101}{}{Das Motorrad scheint zur Zeit nicht fahrtüchtig zu sein. Es braucht einen Brennstoffzellencontroller.}

{200}{}{Mit Hilfe des Brennstoffzellencontroller gelingt es dir, das Auto wieder in Gang setzen.}
{210}{}{Du schaffst es nicht, das Motorrad mit dem Brennstoffzellencontroller zu reparieren.}

{220}{}{Du hast den Brennstoffzellenregulator erfolgreich installiert.}
{230}{}{Du schaffst es nicht, den Brennstoffzellenregulator zu installieren.}

{250}{}{Das Motorrad hat keine Energie mehr. Lade es auf um es wieder in Betrieb zu nehmen.}

{300}{}{Du schaffst es nicht, das Motorrad zu reparieren. Vielleicht kann man es mit dem Brennstoffzellencontroller reparieren, von dem Smitty gesprochen hat.}

{400}{}{Es würde zu viel Lärm machen, die Haube aufzumachen und an dem Motorrad rumzubasteln.}

# SD3:
{450}{}{Das Motorrad ist nicht betriebsbereit.}
{451}{}{Das Motorrad braucht keine reparaturen.}
{452}{}{Der Schlüssel passt!}
{453}{}{Es sieht so aus, als ob der Brennstoffzellencontroller vorsorglich entfernt wurde. Vielleicht ist er hier noch irgendwo?}

{500}{}{Das Motorrad ist nicht groß genug für deine Gruppe!}
{501}{}{Nicht alle von uns werden auf die Maschine passen.}
{502}{}{Jemand wird hier warten müssen.}
{503}{}{Das Motorrad ist nicht groß genug für uns alle.}
{504}{}{Das wird nicht für uns alle funktionieren.}
{505}{}{Ich habe ein mieses Gefühl bei der Sache.}

{510}{}{Du lädst das Motorrad mit mehr Energie.}
{511}{}{Das Motorrad ist schon voll aufgeladen.}
{512}{}{Das Motorrad hat einen Energiestand von }
{513}{}{%.}

{520}{}{Der Brennstoffzellenregulator fehlt.}


