{100}{}{Du siehst eine Disk mit seltsamen Markierungen darauf.}
{101}{}{Der PIPBoy zeigt an: Datei im System gefunden. Ladevorgang abgebrochen.}
{102}{}{Der PIPBoy zeigt an: Daten werden von Disk geladen.}
{103}{}{Diese Holodisk scheint verwendet worden zu sein, um Audiodaten von einem militärischen Funkrelais aufzuzeichnen.}
# TODO: TRANSLATE
#
# for Fallout Fixt:
#
{104}{}{Du siehst: Mutantenübertragung.}
{105}{}{Die Disk hat seltsame Markierungen und ein paar Flecken, die wie Blut ausehen.}
