{100}{}{Du siehst eine CD mit einer seltsamen Markierung darauf.}
{101}{}{PIPBoy zeigt an: Informationen bereits gespeichert.}
{102}{}{PIPBoy zeigt an: Daten werden geladen.}

# TODO: TRANSLATE
#
# for Fallout Fixt:
#
{104}{}{Du siehst: Mutantenübertragung.}
{105}{}{Die Disk hat ein paar seltsame Markierungen und ein paar Flecken, die wie Blut ausehen.}
