{100}{}{Du siehst Nicole.}
{101}{}{Erzähl mir was über die Followers of the Apocalypse.}
{102}{}{Was betet ihr an?}
{103}{}{Was ist gibt es hier so?}
{104}{}{Ich hab' ein paar Informationen für dich.}
{105}{Nic_1}{Grüß dich! He! Schön, dass du zu uns gekommen bist. Hoffentlich stellt dich unser einfaches Heim zufrieden.}
{106}{}{Danke. Was betet ihr hier an?}
{107}{}{'Einfach' ist gut! 'Schrottreif' trifft's wohl besser!}
{108}{}{Natürlich. Kann ich dir ein paar Fragen stellen?}
{109}{}{Ist ganz okay, find' ich.}
{110}{}{Häh? Äh, äh, äh. Häh?}
{111}{Nic_2}{Wir beten nichts an, sondern folgen einigen Prinzipien. Wir wollen dem Ödland Frieden bringen. Die Welt steht vor der Zerstörung, und wir versuchen, etwas zu ändern.}
{112}{}{Wie das?}
{113}{Nic_4}{Wir erinnern die Menschen daran, warum der Große Krieg stattgefunden hat, und tragen dazu bei, dass so etwas nie mehr passiert.}
{114}{}{Und habt ihr Erfolg damit?}
{115}{}{Klingt nach Wunschdenken - nicht sehr realistisch!}
{116}{Nic_5}{Wir geben nicht auf - niemals. Auch wenn die meisten heute nur den Waffen trauen. Und wir sind besorgt wegen der Children of the Cathedral ...}
{117}{}{Was ist mit den Children of the Cathedral?}
{118}{Nic_6}{Auch sie wollen den Frieden. Doch wer nicht ihrer Meinung ist, verschwindet einfach. Ihr Dunkler Gott ist anders, als er scheint. Glaub mir.}
{119}{}{Woher weißt du das?}
{120}{}{Bist du nicht einfach nur ein bisschen paranoid?}
{121}{}{Denken alle Followers so, oder ist das nur deine Meinung?}
{122}{Nic_7}{Nenn es Instinkt. In unseren Augen sehen Morpheus und die Nightkin nicht wie Friedensstifter aus. Ihre Krankenhäuser und Friedensbotschaften sind zwar schön, doch das Böse lauert dort.}
{123}{}{Bist du nicht einfach nur ein bisschen paranoid?}
{124}{}{Hast du irgendwelche Anhaltspunkte?}
{125}{}{Du sollst alles wissen, was ich herausfinde.}
{126}{}{Ich höre immer nur 'Wir'! Legst du allen dein Wort in den Mund?}
{127}{Nic_8}{Mag sein, doch genau darum sind wir noch am Leben.}
{128}{Nic_8a}{Wir sind vereint. Wenn nicht, sterben wir. Tut mir leid, wenn dich das verwirrt.}
{129}{Nic_8b}{Willst du noch etwas wissen?}
{130}{}{Ja.}
{131}{}{Nein, danke. Ich geh' jetzt.}
{132}{Nic_9}{Frag! Wenn ich kann, antworte ich.}
{133}{Nic_10}{Wir haben keine Zeit für Leute wie dich. Mein Assistent bringt dich hinaus.}
{134}{Nic_11}{He! Ich mag das nicht, aber ... ich vergesse es, wenn du dich entschuldigst.}
{135}{}{Ich bedaure, je mit dir geredet zu haben.}
{136}{}{Okay, es tut mir leid.}
{137}{Nic_12}{Gut. Keine Zeit zum Babysitten. Geh jetzt!}
{138}{Nic_13}{Entschuldigung angenommen. Denk dran, du bist Gast hier. Nun, gibt es sonst noch etwas?}
{139}{}{Kann ich dich noch was fragen?}
{140}{}{Nein, ich geh' dann.}
{141}{Nic_14}{Wir wünschen dir viel Glück für deine Reisen. Nutze unseren Stützpunkt, sooft du willst.}
{142}{Nic_15}{Ja, es könnte besser sein. Doch wenn man sich zum Krieg rüstet ...}
{143}{}{Krieg mit wem?}
{144}{Nic_16}{Den Children of the Cathedral. Unser Ziel ist es, dem Land Frieden zu bringen, aber es gibt Dinge, die man einfach nicht ändern kann.}
{145}{}{Ich verstehe nicht ganz. Was haben sie denn gemacht?}
{146}{}{Warum glaubt ihr an Frieden?}
{147}{Nic_17}{Seit die Children aufgetaucht sind, verschwindet jeder, der nicht an ihre Vision glaubt. Unheimlich! Angeblich wollen sie Frieden, doch glauben wir das nicht.}
{148}{}{Woher weißt du das?}
{149}{}{Was wollt ihr dagegen machen?}
{150}{}{Woher kommen die Children of the Cathedral?}
{151}{Nic_18}{Wir können uns nur vorbereiten. Doch die Zeit wird kommen, da wir die Children bekämpfen müssen. Und ihren Dunklen Gott.}
{152}{}{Klingt gefährlich. Du sollst alles wissen, was ich herausfinde.}
{153}{}{Hast du nicht gerade gesagt, ihr glaubt an Frieden?}
{154}{Nic_19}{Toll! Jede Information ist nützlich. Hast du sonst noch eine Frage?}
{155}{}{Ja.}
{156}{}{Nein, danke.}
{157}{Nic_20}{Wir glauben an den Frieden, doch werden wir für unser Land kämpfen. Auch wenn wir Followers in den Krieg ziehen müssen. Auch dann!}
{158}{}{Klingt für mich wie ein Widerspruch.}
{159}{}{Das ist irgendwie heuchlerisch, oder?}
{160}{}{Verstanden. Kann ich dich vielleicht noch was fragen?}
{161}{Nic_21}{Eigentlich nicht. Wir wollen Frieden bringen, doch wir verteidigen uns, wenn nötig. Uns und unseren Glauben!}
{162}{Nic_21b}{Das verstehst du nicht.}
{163}{}{Hmm, okay. Kann ich dich vielleicht noch was fragen?}
{164}{}{Okay, es wird Zeit für mich zu gehen.}
{165}{Nic_22}{Sie kamen etwa zur gleichen Zeit wie wir, doch niemand weiß, woher sie sind. Ihr Anführer, Morpheus, gehörte wahrscheinlich zu den Rippers, bevor er von ihrem Dunklen Gott 'erleuchtet' wurde.}
{166}{}{He, man kann sich doch verändern!}
{167}{}{Hört sich nicht gerade nach einem netten Typ an.}
{168}{}{Ich glaub', ich werd' dem nachgehen.}
{169}{Nic_23}{Eine schmeichelhafte Beschreibung! Und sonst noch etwas?}
{170}{}{Ja.}
{171}{}{Nein, danke.}
{172}{Nic_24}{Pass gut auf! Natürlich würden wir gerne wissen, was da drüben los ist.}
{173}{}{Kann ich dich noch was fragen?}
{174}{}{Ich geh' dann.}
{175}{Nic_25}{Wir gründeten diese Gruppe angesichts des Blutvergießens im Land. Alles schien hoffnungslos. Ohne Hoffnung kann man nicht leben.}
{176}{}{Und ihr gebt den Menschen Hoffnung?}
{177}{}{Du klingst wie einer von den Children!}
{178}{}{Wann habt ihr diese Gruppe gegründet?}
{179}{Nic_26}{Oh ja! Wir versuchen es, doch die meisten Menschen hören nicht auf uns.}
{180}{}{Kann ich dich vielleicht noch was fragen?}
{181}{}{Es wird Zeit für mich zu gehen.}
{182}{Nic_27}{Ahhh ... Es ist bestimmt langweilig, die ganze Geschichte der Followers zu hören. Es gibt hier genug Bücher, in denen sie drin steht.}
{183}{}{Kann ich dich noch was fragen?}
{184}{}{Okay, danke. Ich muss jetzt gehen.}
{185}{Nic_28}{Unsere Spione haben gesehen, wie Nightkin im Hinterzimmer des Tempels der Children ein- und ausgegangen sind. Dort hinten gibt es was Wichtiges.}
{186}{}{Du sollst alles wissen, was ich herausfinde.}
{187}{}{Kann ich dich noch was fragen?}
{188}{}{Wirklich interessant, aber ich muss jetzt gehen.}
{189}{Nic_29}{Was willst du wissen?}
{190}{}{Wo wurden die Followers of the Apocalypse gegründet?}
{191}{}{Wer hat sie gegründet?}
{192}{}{Was sind eure Ziele?}
{193}{Nic_30}{Tief im Süden beim Great Glow. Es waren harte Zeiten, doch wir haben überlebt. Wir haben erkannt, dass der Große Krieg nie wiederkehren darf.}
{194}{}{Dann hast du also die Followers of the Apocalypse gegründet?}
{195}{}{Warum seid ihr nach Norden gezogen?}
{196}{Nic_31}{Als meine Eltern von Verbrechern getötet wurden ... [Sie seufzt.] ... sollte Schluss mit dem Töten sein. Es ist unser Ziel, das Land wieder zu dem zu machen, was es war.}
{197}{}{Das mit deinen Eltern tut mir leid.}
{198}{}{Ein zweiter Großer Krieg wäre also möglich? Das ist doch idiotisch!}
{199}{}{Wer waren diese Verbrecher?}
{200}{}{Warum bist du mit den Followers nach Norden gezogen?}
{201}{Nic_32}{Wissen wir nicht. Aber wir haben gehört, dass eine Gruppe nördlich in einer alten Stadt lebt. Dabei haben wir's belassen.}
{202}{}{Warum? Du könntest dich doch rächen!}
{203}{}{Warum bist du mit den Followers nach Norden gezogen?}
{204}{Nic_33}{Wir wollen Frieden schaffen, nicht aus Hass töten.}
{205}{}{Hört sich für mich an, als ob ihr Angst habt.}
{206}{}{Wie edel von dir! An deiner Stelle würde ich sie alle töten.}
{207}{}{Warum seid ihr jetzt hier oben?}
{208}{Nic_34}{[Sie seufzt.] Dachte ich mir! Es ist unsere Aufgabe, Leuten wie dir Vernunft beizubringen.}
{209}{}{Viel Glück dabei! Wird bestimmt nicht leicht! Ist das übrigens der Grund, warum ihr jetzt hier oben seid?}
{210}{}{Und du meinst, Gewalt ist nie das richtige Mittel?}
{211}{}{Kannst du mir noch ein paar Fragen beantworten?}
{212}{}{Tja, ich muss jetzt gehen.}
{213}{Nic_35}{Hmm! Noch kannst du den Unterschied nicht verstehen. Okay, denk doch mal drüber nach, und - wenn du willst - komm dann zurück.}
{214}{Nic_36}{Im Süden sind nicht mehr viele. Fast alles dort ist radioaktiv verseucht. Die meisten Überlebenden sind unserer Organisation beigetreten.}
{215}{}{Wie konnte deine Familie überleben?}
{216}{}{Ist dort noch immer alles radioaktiv verseucht? Nach 80 Jahren?}
{217}{Nic_37}{Wir lebten am Rande des Great Glow. Seuchen waren ausgebrochen, also zogen wir mit allen Leuten nach Norden. [Sie seufzt.] Meine Eltern wurden getötet.}
{218}{}{Das tut mir leid.}
{219}{}{Warum ist da unten die Strahlung nach all der Zeit noch immer so hoch?}
{220}{Nic_39}{Danke, das ist nett von dir. Und willst du mich noch mehr fragen?}
{221}{}{Ja.}
{222}{}{Nein, ich muss schnell weg.}
{223}{Nic_41}{Naja, angeblich gibt's so was Wichtiges dort, dass das Gebiet mit Bomben übersät wurde, um es dem Erdboden gleichzumachen.}
{224}{}{Kann ich dir noch ein paar Fragen stellen?}
{225}{}{Wirklich interessant, aber ich muss jetzt gehen.}
{226}{Nic_42}{Also, der Boneyard ist ziemlich karg, wie du siehst. Ähm ... Adytum liegt im Westen. Die Children of the Cathedral sind im Norden. Ich rate dir, nicht zu weit in den Süden der Stadt zu gehen, denn die Rippers und die Blades haben ein Schlachtfeld daraus gemacht.}
{227}{Nic_43}{Worüber?}
{228}{}{Ich hab' alles über die Children of the Cathedral herausgefunden.}
{229}{}{Was zahlst du?}
{230}{}{Nichts, schon gut.}
{231}{Nic_44}{Endlich! Was weißt du?}
{232}{}{Ich bin jetzt der Anführer der Children!}
{233}{}{Nicht Morpheus, sondern der Meister ist der Anführer der Children.}
{234}{}{Kennst du die Nightkin?}
{235}{Nic_45}{Was? Der Dunkle Gott? Sag bloß nicht, es gibt ihn wirklich.}
{236}{}{Es gibt ihn wirklich, nur ist er kein Gott, sondern ein Mutant. Er will alle für seine Sache zu Nightkin machen.}
{237}{}{Ja, es gibt ihn. Du solltest den allmächtigen Dunklen Gott fürchten!}
{238}{Nic_46}{Was haben die Nightkin damit zu tun?}
{239}{}{In Wirklichkeit sind sie Supermutanten. Der Meister ist ihr Anführer.}
{240}{Nic_47}{Was haben sie denn vor?}
{241}{}{Der Meister ist von der Überlegenheit der Nightkin überzeugt und glaubt, er kann die Menschheit retten, indem er alle in Nightkin verwandelt.}
{242}{}{Ich bin mir nicht ganz sicher, aber ich weiß, dass der Meister Leute in Nightkin verwandelt.}
{243}{Nic_49}{Was tun?}
{244}{}{Ich werd' mit dem Meister reden.}
{245}{}{Ich werd' jetzt sofort die Kathedrale angreifen.}
{246}{}{Ich hab' den Ort zerstört, wo sie die Supermutanten schaffen, aber bei meinem Angriff auf die Kathedrale benötige ich Hilfe.}
{247}{Nic_50}{Wir müssen diese Gelegenheit ergreifen. Erkunde die Kathedrale! Wir werden dir helfen, sie zu stürmen.}
{248}{}{Nein, so nicht! Weißt du, ob es einen Geheimeingang gibt?}
{249}{}{Okay, wir treffen uns dort.}
{250}{}{Nein! Ich will nicht, dass es noch mehr Verletzte gibt.}
{251}{Nic_52a}{Nein, aber ich kenne jemanden, der's weiß. Geh zur Kathedrale und suche Laura. Sag ihr 'Red Rider'. Wenn's geht, lenken wir sie ab.}
{252}{}{Danke. Ich hoffe, das Glück ist auf unserer Seite.}
{253}{Nic_53}{Das hat nichts mit Glück zu tun. Ich zähle auf dich.}
{254}{Nic_56}{Unser Schicksal liegt vor uns. Hoffentlich sind wir seiner würdig.}
{255}{Nic_57}{Was? Das ist unser Schicksal! Die Followers werden das Böse bekämpfen, und nur dann kann die Heilung des Landes beginnen.}
{256}{}{Nein, so nicht!}
{257}{}{Okay, wir treffen uns an der Kathedrale.}
{258}{Nic_58}{Hahaha! Du hast uns gar nichts zu sagen. Wir greifen an, mit oder ohne deinen Segen!}
{259}{Nic_59}{Mit ihm reden? Bist du krank?}
{260}{}{Bist du nicht diejenige, die immer Frieden predigt?}
{261}{}{Nein, und du kannst mich nicht aufhalten.}
{262}{Nic_60}{Ja, schon, aber ...}
{263}{}{Ich denke, ich kann das ohne Blutvergießen erledigen. Haltet euch aber bereit, falls ich euch doch brauchen sollte.}
{264}{Nic_61a}{Ich sehe, du hast dich entschieden. Jetzt pass auf! Geh zur Kathedrale und suche eine Frau namens Laura. Sag zu ihr 'Red Rider'. Und bitte ... komm heil zurück!}
{265}{Nic_63}{Du hast einen komischen Sinn für Humor. Komm erst wieder, wenn du etwas Wichtiges zu sagen hast.}
{266}{}{Entschuldige, das war nur ein Witz. Es hat mit den Nightkin zu tun.}
{267}{Nic_65a}{Ach so, du bist Söldner! Gut, hier sind 500 Deckel.}
{268}{Nic_66b}{Und? Was hast du für mich?}
{269}{}{Ich weiß, dass dir jemand Geld abknöpfen will. Danke!}
{270}{}{Morpheus ist nicht der Anführer der Children. Ihr eigentlicher Anführer ist der Meister.}
{271}{}{Kennst du die Nightkin?}
{272}{}{Die Children unterstehen Außerirdischen.}
{273}{Nic_67}{Viel Glück! Jetzt müssen wir unsere Möglichkeiten prüfen.}
{274}{Nic_68}{Wie edel! Wie beeindruckend! Phh ... Und wir dachten, du seist anders. Jetzt nimm dein Geld und schwirr ab!}
{275}{Nic_69}{Hallo! Wie kann ich dir jetzt helfen?}
{276}{}{Ich muss dich noch was fragen.}
{277}{}{Schon gut, ich muss jetzt gehen.}
{278}{}{Häh? Äh, äh, äh. Häh??}
{279}{Nic_70}{Was willst du jetzt?}
{280}{}{Ich wollte mich nur bei dir entschuldigen.}
{281}{}{Ich wollte dich nur wiedersehen.}
{282}{Nic_70a}{Hau ab!}
{283}{Nic_71}{Entschuldigung angenommen. Was willst du?}
{284}{}{Kann ich dich noch was fragen?}
{285}{}{Das war's. Ich muss gehen.}
{286}{Nic_72}{Wir sind beschäftigt. Hast du sonst nichts zu tun?}
{287}{Nic_74}{Was machst du da? Stell das hin!}
{288}{Nic_75}{Stopp!}
{289}{Nic_76}{Lass das!}
{290}{Nic_77}{He! Schaff dich weg!}
{291}{Nic_78}{Gut, wenn du meinst. Jetzt verschwinde! Wir haben viel zu tun.}
{292}{Nic_79}{Sprich mit Jake. Er weiß mehr davon.}
{293}{Nic_80}{Ich sagte ...}
{294}{Nic_81}{Wie ich bereits sagte ...}
{295}{Nic_82}{Ich sagte ...}
{296}{Nic_83}{Nun, wie ich sagte ...}
{297}{Nic_84}{He! Bist du blöd?}
{298}{Nic_85}{Ich hab' dir das schon oft gesagt. Putz mal deine Ohren aus!}
{299}{Nic_86}{Morpheus ist der Anführer der Children of the Cathedral. Er ist böse, und jeder sollte das wissen.}
{300}{Nic_87}{Da gibt's nichts zu sagen.}
{301}{Nic_87a}{Laura ist einer der Insider in der Kathedrale. Sie hat sich uns voll und ganz verschrieben.}
{302}{Nic_87b}{Jake ist der Stellvertreter.}
{303}{Nic_88}{Hier drin sind historische und philosophische Texte ... einfach alles! Schau dich doch mal um!}
{304}{Nic_89}{Die Children of the Cathedral beten ihn an. Sie sagen, er will die Menschheit heilen, doch das ist gelogen.}
{305}{Nic_90}{Ich weiß nicht viel über ihn.}
{306}{Nic_91}{Das sind Morpheus' persönliche Diener. Das sind riesige, scheußliche Bestien. Uuäh!}
{307}{Nic_92}{Du hast doch ihre Krankenhäuser gesehen. Sie predigen Frieden, aber etwas stimmt mit ihnen nicht. Wir müssen rausfinden was.}
{308}{Nic_93}{Eine kleine Siedlung. Du findest sie im Westen im Boneyard.}
{309}{Nic_94}{Vor dem Großen Krieg war es eine blühende Stadt. Meine Mutter hat mir davon erzählt, doch jetzt ist fast alles weg. Nur Ruinen und Tod!}
{310}{Nic_95}{Sie kämpfen mit den Blades im Süden. Die Rippers sind die schlimmste Bande im Boneyard. Als wir unsere Leute zum Bekehren hinschickten, kam nur eins zurück: ihre Köpfe!}
{311}{Nic_96}{Die Blades kämpfen mit den Rippers unten im Süden. Sie sind das kleinere Übel der beiden, aber das will nichts heißen. Wir haben ein paar von ihnen bekehrt.}
{312}{Nic_97}{Unsere Geschichte steht ganz oben im letzten Regal.}
{313}{Nic_98}{Alles war verbrannt. Alles war zerstört. Wir wollen den Menschen Frieden lehren, damit so was nie wieder passiert.}
{314}{Nic_99}{Das ist die Handelsstadt im Norden. Wir versuchen, dort Handel zu treiben.}
{315}{Nic_100}{Wir können sie nicht einschätzen. Sie verkaufen Waffen, wir Frieden. Ahh ... Aber ihre Motive?}
{316}{Nic_101}{Davon wissen wir nichts.}
{317}{Nic_102}{Noch nie davon gehört.}
{318}{Nic_103}{Wir wissen nicht, wovon du redest.}
{319}{}{Was weißt du sonst noch über die Children of the Cathedral?}
{320}{}{Kann ich dich noch was über sie fragen?}
{321}{}{Kann ich dich noch was anderes fragen?}
{322}{}{Weißt du, wer ihr Anführer ist?}
{323}{}{Hast du sie irgendwie im Verdacht?}
{324}{}{Kannst du mir helfen, sie zu vernichten?}
{325}{}{Danke. Mir hilft jede Information, die ich kriegen kann.}
{326}{}{Danke für die Informationen. Ich geh' dann.}

# Fo1in2
{500}{}{Danke, aber ich bin effektiver, wenn ich den Ort alleine infiltriere.}

# Nicole Tell-Me-Abouts generic responses
{980}{Nic_101}{Davon wissen wir nichts.}
{981}{Nic_102}{Noch nie davon gehört.}
{982}{Nic_103}{Wir wissen nicht, wovon du redest.}
#
# Nicole Tell-Me-Abouts
#
{1000}{}{Morpheus}
{1001}{}{Nicole}
{1002}{}{Laura}
{1003}{}{Jake}
{1004}{}{Bibliothek}
{1005}{}{Dunkler Gott}
{1006}{}{Meister}
{1007}{}{Nightkin|Nightkins}
{1008}{}{Children of the Cathedral|Children|Cathedral|CoC}
{1009}{}{Adytum|Adytown}
{1010}{}{Boneyard|LA|Los Angeles|Angels Boneyard|Angel's Boneyard}
{1011}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{1012}{}{Krieg|2077}
{1013}{}{Hub}
{1014}{}{Brotherhood|Brotherhood of Steel|Steel|BOS}
{1015}{}{Rippers|Ripper}
{1016}{}{Blades|Blade}
{1017}{}{Hub}
{1018}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}

{1100}{Nic_86}{Morpheus ist der Anführer der Children of the Cathedral. Er ist böse, und jeder sollte das wissen.}
{1101}{Nic_87}{Da gibt's nichts zu sagen.}
{1102}{Nic_87a}{Laura ist einer der Insider in der Kathedrale. Sie hat sich uns voll und ganz verschrieben.}
{1103}{Nic_87b}{Jake ist der Stellvertreter.}
{1104}{Nic_88}{Hier drin sind historische und philosophische Texte ... einfach alles! Schau dich doch mal um!}
{1105}{Nic_89}{Die Children of the Cathedral beten ihn an. Sie sagen, er will die Menschheit heilen, doch das ist gelogen.}
{1106}{Nic_90}{Ich weiß nicht viel über ihn.}
{1107}{Nic_91}{Das sind Morpheus' persönliche Diener. Das sind riesige, scheußliche Bestien. Uuäh!}
{1108}{Nic_92}{Du hast doch ihre Krankenhäuser gesehen. Sie predigen Frieden, aber etwas stimmt mit ihnen nicht. Wir müssen rausfinden was.}
{1109}{Nic_93}{Eine kleine Siedlung. Du findest sie im Westen im Boneyard.}
{1110}{Nic_94}{Vor dem Großen Krieg war es eine blühende Stadt. Meine Mutter hat mir davon erzählt, doch jetzt ist fast alles weg. Nur Ruinen und Tod!}
{1111}{Nic_97}{Unsere Geschichte steht ganz oben im letzten Regal.}
{1112}{Nic_98}{Alles war verbrannt. Alles war zerstört. Wir wollen den Menschen Frieden lehren, damit so was nie wieder passiert.}
{1113}{Nic_99}{Das ist die Handelsstadt im Norden. Wir versuchen, dort Handel zu treiben.}
{1114}{Nic_100}{Wir können sie nicht einschätzen. Sie verkaufen Waffen, wir Frieden. Ahh ... Aber ihre Motive?}
{1115}{Nic_95}{Sie kämpfen mit den Blades im Süden. Die Ripper sind die rücksichtsloseste Bande im Boneyard. Als wir Leute schickten, um sie zu bekehren, bekamen wir nur ihre Köpfe zurück.}
{1116}{Nic_96}{Die Blades kämpfen gegen die Ripper im Süden. Sie sind die angenehmste der beiden Banden, obwohl das nicht viel sagt. Wir haben einige davon konvertiert.}
{1117}{Nic_99}{Das ist die Handelsstadt im Norden. Wir versuchen, dort Handel zu treiben.}
{1118}{Nic_100}{Wir können sie nicht einschätzen. Sie verkaufen Waffen, wir Frieden. Ahh ... Aber ihre Motive?}

