# Added for Fo1in2 TMA
{1}{}{Was willst du wissen?}
{2}{}{Ok}
{3}{}{Abbrechen}

#############################################################
# Fo2 stuff                                                 #
#############################################################
{110}{}{Deine Füße jucken fürchterlich.}
{120}{}{Du entdeckst störende Schwellungen an jedem Fuß.}
{130}{}{Deine Schuhe sind plötzlich zu eng, diese Schwellungen entzünden sich.}
{140}{}{Diese Schwellungen an den Füßen scheinen sich zu einem sechsten Zeh auszuwachsen. Aber zumindest ist der ständige brennende Schmerz weg.}
{141}{}{Oh mein Gott, es ist Bess!}

#################################################################################
# This file is just for "Tell Me About..." queries and responses.  -Sduibek     #
#################################################################################
#
# TRANSLATORS: Copy the blank entries into your language's OBJ_DUDE.MSG,
#              But leave them blank! It is intentional.
##########################
#    "TELL ME ABOUT"     #
#      "my name"         #
#      (970-979)         #
##########################
{970}{}{So heiße ich.}
{971}{}{Du sprichst mit mir.}
{972}{}{Warum stellst du dumme Fragen. Ich bin die Person.}

##########################
#    "TELL ME ABOUT"     #
#     "don't know"       #
#      (980-999)         # <-- goes to 999, even though original game didn't indicate this.
##########################
{980}{}{Darüber weiß ich überhaupt nichts.}
{981}{}{Tut mir leid. Keine Ahnung.}
{982}{}{Nie davon gehört.}

#
# TRANSLATORS: Copy the blank entries into your language's OBJ_DUDE.MSG,
#              But leave them blank! It is intentional.
#
#
# HALLDED.MAP
# The Necropolis Hall of the Dead Tell-Me-Abouts
#
{2800}{}{Meister}
{2801}{}{Steuerchip|Wasserchip|Chip}
{2802}{}{Necropolis|Nekropolis|City of the Dead|City of Dead}
{2803}{}{Set|Seth}
{2804}{}{Wasserstelle}
{2805}{}{Halle|Halle der Toten|Totenhalle|Halle des Todes}
{2806}{}{Hilfe|Hilf mir}
{2807}{}{Doktor|Sanitäter|Arzt}
{2808}{}{Kaufen|Einkaufen|Verkaufen|Handel|Handeln|Geschäft|Laden}
{2809}{}{Wasser}
{2810}{}{Vault|Vault12|Vault 12|Vault-12|Bunker|Bunker12|Bunker 12|Bunker-12}
{2811}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land}
{2812}{}{Richtung|Richtungen|wo ist|wo hin|wohin}
{2813}{}{Fallout|Fall out|nuklearer fallout}
{2814}{}{Stehlen|Diebstahl|Dieb|Diebe|Verbrechen|Verbrecher|Kriminelle}
{2815}{}{Hub}
{2816}{}{Strahlung|Rads|Rad}
{2817}{}{Hotel|Motel}
{2818}{}{Supermutant|Supermutanten|Super Mutant|Super Mutanten|Mutant|Mutanten}
{2819}{}{Brei|klump}
{2820}{}{Brahmin|Brahmins|Brahma}
{2821}{}{Job|Arbeit|Aufgabe|Geld|Geld verdienen}
{2822}{}{Kanal|Kanäle|Abwasserkanal|Untergrund|Kanalisation}
{2823}{}{Ghul|Ghuls}

{2900}{}{Ist er nicht ein großer wichtiger Mann?}
{2901}{}{Ich weiß nicht, aber die Wasserstelle hat vielleicht einen.}
{2902}{}{Du bist mittendrin. Besser gesagt in dem, was davon übrig ist. Dieser Ort stirbt aus, langsam aber sicher.}
{2903}{}{Oh, ich mag ihn, wirklich. Du findest ihn in der Halle.}
{2904}{}{Es liegt im Norden. Pass' auf die Wachen auf. Sie nehmen ihren Job wirklich ernst.}
{2905}{}{Die Totenhalle. Wo Set arbeitet. Liegt mitten im Zentrum von Necropolis.}
{2906}{}{Dort wirst du keine Hilfe finde.}
{2907}{}{Du bist auf dich allein gestellt.}
{2908}{}{Wir handeln nicht mit deiner Art.}
{2909}{}{Von mir wirst du keines bekommen.}
{2910}{}{Die meisten von uns stammen aus dieser Vault.}
{2911}{}{Die Strahlung macht es gefährlich für Glatthäute. Uns jedoch ist das egal.}
{2912}{}{Wenn du durch die Stadt reisen willst, musst du durch die Abwasserkanäle gehen.}
{2913}{}{Ist das wenn der Regen glüht?}
{2914}{}{Wenn du erwischt wirst, schneiden sie dich auf.}
{2915}{}{Weiß nicht, ist mir egal.}
{2916}{}{Anders als Glatthäuten ist uns die Strahlung egal.}
{2917}{}{Östlich von hier. Du kommst durch den Untergrund dahin.}
{2918}{}{Die an der Wasserstelle? Die hau'n dich zu Brei.}
{2919}{}{Ich habe gesehen, wie einmal einer der Mutanten eine Glatthaut zu klump geschlagen hat.}
{2920}{}{Sicher, ich mag den Geschmack.}
{2921}{}{Set hat vielleicht 'ne Aufgabe für dich.}
{2922}{}{Die Kanalisation ist der einzige Weg an den meisten Trümmern der Stadt vorbei.}
{2923}{}{Das sind wir.}

#
# HOTEL.MAP
# The Necropolis Hotel Tell-Me-Abouts
#
{3400}{}{Meister}
{3401}{}{Steuerchip|Wasserchip|Chip}
{3402}{}{Necropolis|Nekropolis|City of the Dead|City of Dead}
{3403}{}{Set|Seth}
{3404}{}{Wasserstelle}
{3405}{}{Halle|Halle der Toten|Totenhalle|Halle des Todes}
{3406}{}{Hilfe|Hilf mir}
{3407}{}{Doktor|Sanitäter|Arzt}
{3408}{}{Kaufen|Einkaufen|Verkaufen|Handel|Handeln|Geschäft|Laden}
{3409}{}{Wasser}
{3410}{}{Vault|Vault12|Vault 12|Vault-12|Bunker|Bunker12|Bunker 12|Bunker-12}
{3411}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land}
{3412}{}{Richtung|Richtungen|wo ist|wo hin|wohin}
{3413}{}{Fallout|Fall out|nuklearer fallout}
{3414}{}{Stehlen|Diebstahl|Dieb|Diebe|Verbrechen|Verbrecher|Kriminelle}
{3415}{}{Hub}
{3416}{}{Strahlung|Rads|Rad}
{3417}{}{Hotel|Motel}
{3418}{}{Supermutant|Supermutanten|Super Mutant|Super Mutanten|Mutant|Mutanten}
{3419}{}{Brei|klump}
{3420}{}{Brahmin|Brahmins|Brahma}
{3421}{}{Job|Arbeit|Aufgabe|Geld|Geld verdienen}
{3422}{}{Kanal|Kanäle|Abwasserkanal|Untergrund|Kanalisation}
{3423}{}{Ghul|Ghuls}

{3500}{}{Ist er nicht ein großer wichtiger Mann?}
{3501}{}{Ich weiß nicht, aber die Wasserstelle hat vielleicht einen.}
{3502}{}{Du bist mittendrin. Besser gesagt in dem, was davon übrig ist. Dieser Ort stirbt aus, langsam aber sicher.}
{3503}{}{Oh, ich mag ihn, wirklich. Du findest ihn in der Halle.}
{3504}{}{Es liegt im Norden. Pass' auf die Wachen auf. Sie nehmen ihren Job wirklich ernst.}
{3505}{}{Die Totenhalle. Wo Set arbeitet. Liegt mitten im Zentrum von Necropolis.}
{3506}{}{Hier wirst du keine Hilfe finde.}
{3507}{}{Du bist auf dich allein gestellt.}
{3508}{}{Wir handeln ab und zu mit den Crimson Caravan. Sie kommen aus dem Hub.}
{3509}{}{Von mir wirst du keines bekommen.}
{3510}{}{Die meisten von uns stammen aus dieser Vault.}
{3511}{}{Die Strahlung macht es gefährlich für Glatthäute. Uns jedoch ist das egal.}
{3512}{}{Du bist am Hotel. Wenn du durch die Stadt reisen willst, musst du durch die Abwasserkanäle gehen.}
{3513}{}{Ist das wenn der Regen glüht?}
{3514}{}{Wenn du erwischt wirst, schneiden sie dich auf.}
{3515}{}{Weiß nicht, ist mir egal.}
{3516}{}{Anders als Glatthäuten ist uns die Strahlung egal.}
{3517}{}{Bist du dumm? Du bist am Hotel!}
{3518}{}{Die an der Wasserstelle? Die hau'n dich zu Brei.}
{3519}{}{Ich habe gesehen, wie einmal einer der Mutanten eine Glatthaut zu klump geschlagen hat.}
{3520}{}{Sicher, ich mag den Geschmack.}
{3521}{}{Hier gibt's keine Arbeit für dich.}
{3522}{}{Die Kanalisation ist der einzige Weg an den meisten Trümmern der Stadt vorbei.}
{3523}{}{Das sind wir.}

# WATRSHD.MAP
# The Necropolis Watershed Tell-Me-Abouts
{4000}{}{Meister}
{4001}{}{Steuerchip|Wasserchip|Chip}
{4002}{}{Necropolis|Nekropolis|City of the Dead|City of Dead}
{4003}{}{Set|Seth}
{4004}{}{Wasserstelle}
{4005}{}{Halle|Halle der Toten|Totenhalle|Halle des Todes}
{4006}{}{Hilfe|Hilf mir}
{4007}{}{Doktor|Sanitäter|Arzt}
{4008}{}{Kaufen|Einkaufen|Verkaufen|Handel|Handeln|Geschäft|Laden}
{4009}{}{Wasser}
{4010}{}{Vault|Vault12|Vault 12|Vault-12|Bunker|Bunker12|Bunker 12|Bunker-12}
{4011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land}
{4012}{}{Richtung|Richtungen|wo ist|wo hin|wohin}
{4013}{}{Fallout|Fall out|nuklearer fallout}
{4014}{}{Stehlen|Diebstahl|Dieb|Diebe|Verbrechen|Verbrecher|Kriminelle}
{4015}{}{Hub}
{4016}{}{Strahlung|Rads|Rad}
{4017}{}{Hotel|Motel}
{4018}{}{Supermutant|Supermutanten|Super Mutant|Super Mutanten|Mutant|Mutanten}
{4019}{}{Brei|klump}
{4020}{}{Brahmin|Brahmins|Brahma}
{4021}{}{Job|Arbeit|Aufgabe|Geld|Geld verdienen}
{4022}{}{Kanal|Kanäle|Abwasserkanal|Untergrund|Kanalisation}
{4023}{}{Ghul|Ghuls}

{4100}{}{Ist er nicht ein großer wichtiger Mann?}
{4101}{}{Ich weiß nicht, aber die Wasserstelle hat vielleicht einen.}
{4102}{}{Du bist mitten drin. Besser gesagt in dem, was davon übrig ist. Dieser Ort stirbt aus, langsam aber sicher.}
{4103}{}{Oh, ich mag ihn, wirklich. Du findest ihn in der Halle.}
{4104}{}{Pass' auf die Wachen auf. Sie nehmen ihren Job wirklich ernst.}
{4105}{}{Die Totenhalle. Wo Set arbeitet. Liegt mitten im Zentrum von Necropolis.}
{4106}{}{Hier wirst du keine Hilfe finde.}
{4107}{}{Die Children of the Cathedral können dir vielleicht helfen.}
{4108}{}{Wir handeln ab und zu mit den Crimson Caravan. Sie kommen aus dem Hub.}
{4109}{}{Von mir wirst du keines bekommen.}
{4110}{}{Hast du schon gewusst? Es gibt hier unter uns eine alte Vault, direkt unter der Wasserstelle.}
{4111}{}{Die Strahlung macht es gefährlich für Glatthäute. Uns jedoch ist das egal.}
{4112}{}{Wenn du durch die Stadt reisen willst, musst du durch die Abwasserkanäle gehen.}
{4113}{}{Ist das wenn der Regen glüht?}
{4114}{}{Wenn du erwischt wirst, schneiden sie dich auf.}
{4115}{}{Es ist ein Ort ein paar Tage westlich von hier.}
{4116}{}{Anders als Glatthäuten ist uns die Strahlung egal.}
{4117}{}{Irgendwo östlich von hier. Du kommst durch den Untergrund dahin.}
{4118}{}{Set ist wütend, weil sie die Wasserstelle besetzen und er nichts dagegen tun kann.}
{4119}{}{Sie haben sich in einem Gebäude südwestlich der Wasserstelle niedergelassen..}
{4120}{}{Sicher, ich mag den Geschmack.}
{4121}{}{Set hat vielleicht 'ne Aufgabe für dich.}
{4122}{}{Die Kanalisation ist der einzige Weg an den meisten Trümmern der Stadt vorbei.}
{4123}{}{Das sind wir.}

#
# VAULT13.MAP
# Vault 13 Tell-Me-Abouts
#
{4600}{}{Vault}
{4601}{}{Wasser}
{4602}{}{Aufseher}
{4603}{}{Chip}
{4604}{}{Steuerchip}
{4605}{}{Vault-13}
{4606}{}{Vault13}
{4607}{}{Sanitäter}
{4608}{}{Heilung}
{4609}{}{Bibliothek}
{4700}{}{Hier leben wir. Dafür solltest du Verständnis haben.}
{4701}{}{Der Chip überwacht den Reinheitsgrad der unterirdischen Wasserversorgung. Er ist eine entscheidende Komponente und kann nicht repariert werden.}
{4702}{}{Ein guter Mann, der einen schwierigen Job hat.}
{4703}{}{Der Chip überwacht den Reinheitsgrad der unterirdischen Wasserversorgung. Er ist eine entscheidende Komponente und kann nicht repariert werden.}
{4704}{}{Der Chip überwacht den Reinheitsgrad der unterirdischen Wasserversorgung. Er ist eine entscheidende Komponente und kann nicht repariert werden.}
{4705}{}{Hier leben wir. Dafür solltest du Verständnis haben.}
{4706}{}{Hier leben wir. Dafür solltest du Verständnis haben.}
{4707}{}{Der Arzt ist in der ersten Etage, im medizinischen Labor. Geh dort hin, wenn du verletzt bist.}
{4708}{}{Der Arzt ist in der ersten Etage, im medizinischen Labor. Geh dort hin, wenn du verletzt bist.}
{4709}{}{Die Bibliothek ist im Westflügel der dritten Etage. Wo sich die Forschungscomputern befinden.}

# JUNKENT.MAP
# Junktown Entrance Tell-Me-Abouts
{7000}{}{Killian}
{7001}{}{Gizmo}
{7002}{}{Junktown|Junk Town}
{7003}{}{Shady Sands|Shady|Sands}
{7004}{}{Hub}
{7005}{}{Steuerchip}
{7006}{}{Kasino}
{7007}{}{Laden}
{7008}{}{Deathclaw}
{7100}{}{Killian ist der Bürgermeister. Er hat einen Laden.}
{7101}{}{Gizmo führt ein Kasino. Er scheint in Ordnung zu sein.}
{7102}{}{Das ist Junktown.}
{7103}{}{Hmm, ist ziemlich klein. Ich war noch nie dort.}
{7104}{}{Es ist eine größere Stadt irgendwo im Süden.}
{7105}{}{Was? Tut mir leid.}
{7106}{}{Es ist ein großes Gebäude im Nordwesten der Stadt.}
{7107}{}{Killians Laden? Liegt in der Stadtmitte.}
{7108}{}{Ich hab' keine Ahnung, aber der Name macht mir Angst.}

# JUNKCSNO.MAP
# Junktown Casino Tell-Me-Abouts
{7600}{}{Killian}
{7601}{}{Gizmo}
{7602}{}{Junktown|Junk Town}
{7603}{}{Shady Sands|Shady|Sands}
{7604}{}{Hub}
{7605}{}{Steuerchip}
{7606}{}{Kasino}
{7607}{}{Laden}
{7608}{}{Deathclaw}
{7700}{}{Killian ist der Bürgermeister. Als sein Vater starb wurde er Bürgermeister.}
{7701}{}{Gizmo ist ein mächtiger Mann in Junktown. Er leitet das Kasino und den Boxring. Er macht viel Geld und kauft viel vom Hub.}
{7702}{}{Das ist Junktown.}
{7703}{}{Also, es ist eine wirklich kleine Gemeinde im Norden. Die Menschen, die dort leben, sind hauptsächlich Bauern. Wir treiben gelegentlich mit ihnen Handel, aber meistens wollen sie ihre Ruhe.}
{7704}{}{Der Hub ist das Handelszentrum in dieser Gegend. Fast alle Händler kommen vom Hub. Sie haben dort einige Firmen, die noch Produkte herstellen. Wenn du möchtest, kannst du mit einem der Händler zurück zum Hub fahren.}
{7705}{}{Darüber weiß ich überhaupt nichts.}
{7706}{}{Gizmo leitet es. Geh' den Spielautomaten aus dem Weg, du kannst viel Geld damit verlieren.}
{7707}{}{Darkwaters? Liegt in der Stadtmitte. Du kannst mit ihm Tauschhandel treiben oder bar zahlen.}
{7708}{}{Ich höre die Leute immer davon reden, aber ich hab' es noch nie gesehen. Sie sagen, es durchstreift die Wüste und schlägt meistens nachts zu.}

# JUNKKILL.MAP
# Junktown Killian's Tell-Me-Abouts
{8200}{}{Killian}
{8201}{}{Gizmo}
{8202}{}{Junktown|Junk Town}
{8203}{}{Shady Sands|Shady|Sands}
{8204}{}{Hub}
{8205}{}{Steuerchip}
{8206}{}{Kasino}
{8207}{}{Laden}
{8208}{}{Deathclaw}
{8300}{}{Killian ist der Bürgermeister. Als sein Vater starb wurde er Bürgermeister.}
{8301}{}{Gizmo ist ein mächtiger Mann in Junktown. Er leitet das Kasino und den Boxring. Er macht viel Geld und kauft viel vom Hub.}
{8302}{}{Das ist Junktown.}
{8303}{}{Also, es ist eine wirklich kleine Gemeinde im Norden. Die Menschen, die dort leben, sind hauptsächlich Bauern. Wir treiben gelegentlich mit ihnen Handel, aber meistens wollen sie ihre Ruhe.}
{8304}{}{Der Hub ist das Handelszentrum in dieser Gegend. Fast alle Händler kommen vom Hub. Sie haben dort einige Firmen, die noch Produkte herstellen.Wenn du möchtest, kannst du mit einem der Händler zurück ins Hub fahren.}
{8305}{}{Darüber weiß ich überhaupt nichts.}
{8306}{}{Gizmo leitet es. Geh' den Spielautomaten aus dem Weg, du kannst viel Geld damit verlieren.}
{8307}{}{Darkwaters? Liegt in der Stadtmitte. Du kannst mit ihm Tauschhandel treiben oder bar zahlen.}
{8308}{}{Ich höre die Leute immer davon reden, aber ich hab' es noch nie gesehen. Sie sagen, es durchstreift die Wüste und schlägt meistens nachts zu.}

# BROHDENT.MAP  (8800)
{8800}{}{Meister}
{8801}{}{Krieg}
{8802}{}{Exodus}
{8803}{}{Seltsame Armee|Armee}
{8804}{}{Brotherhood|BOS|Brotherhood of Steel}
{8805}{}{Merchants|Water Merchants}
{8806}{}{fehlende Caravans|fehlenden Caravans|fehlende Karawanen}
{8807}{}{Hub}
{8808}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{8809}{}{Neulinge}
{8810}{}{Scribes}
{8811}{}{Knights}
{8812}{}{Paladins}
{8813}{}{Steuerchip}
{8900}{}{Ich hab' keine Ahnung, wovon du sprichst.}
{8901}{}{Eine schreckliche, dunkle Zeit in der Geschichte der Menschheit, aus der unsere heutige Zeit hervorging. Wir bewahren das Wissen des Krieges, um einen weiteren Holocaust zu vermeiden.}
{8902}{}{Eine schwierige und bedauerliche Entscheidung. Wir haben einige gute Leute verloren, die sich unbedingt alleine anstatt mit der Haupttruppe auf die Suche nach einem sicheren Ort machen wollten.}
{8903}{}{Ich weiß nicht viel darüber. Berichten zufolge treffen sie sich irgendwo nördlich von uns.}
{8904}{}{An diesem Punkt befinden wir uns gerade.}
{8905}{}{Diese Water Merchants sind stehlende Dreckskerle, aber von den anderen Gruppen weiß ich nichts.}
{8906}{}{Darüber weiß ich überhaupt nichts.}
{8907}{}{Eine dreckige Grube für diese bösartigen Händler. Obwohl wir gelegentlich schon mit einer der zivilen Handelsfirmen Waren tauschen.}
{8908}{}{Sie sind ein Kult.}
{8909}{}{Sie sind die Zukunft der Brotherhood.}
{8910}{}{Sie sind die Wissensträger.}
{8911}{}{Sie sind diejenigen, die die Waffen für die Brotherhood herstellen.}
{8912}{}{Sie sind die Beschützer der Brotherhood.}
{8913}{}{Ich hab' keine Ahnung, wovon du sprichst.}

# BROHD12.MAP   (9400)
{9400}{}{Meister}
{9401}{}{Krieg}
{9402}{}{Exodus}
{9403}{}{Seltsame Armee|Armee}
{9404}{}{Brotherhood|BOS|Brotherhood of Steel}
{9405}{}{Merchants|Water Merchants}
{9406}{}{fehlende Caravans|fehlenden Caravans|fehlende Karawanen}
{9407}{}{Hub}
{9408}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{9409}{}{Neulinge}
{9410}{}{Scribes}
{9411}{}{Knights}
{9412}{}{Paladins}
{9413}{}{Steuerchip}
{9500}{}{Ich hab' keine Ahnung, wovon du sprichst.}
{9501}{}{Eine schreckliche, dunkle Zeit in der Geschichte der Menschheit, aus der unsere heutige Zeit hervorging. Wir bewahren das Wissen des Krieges, um einen weiteren Holocaust zu vermeiden.}
{9502}{}{Eine schwierige und bedauerliche Entscheidung. Wir haben einige gute Leute verloren, die sich unbedingt alleine anstatt mit der Haupttruppe auf die Suche nach einem sicheren Ort machen wollten.}
{9503}{}{Ich weiß nicht viel darüber. Berichten zufolge, treffen sie sich irgendwo nördlich von uns.}
{9504}{}{An dem Punkt befinden wir uns gerade.}
{9505}{}{Diese Water Merchants sind stehlende Dreckskerle, aber von den anderen Gruppen weiß ich nichts.}
{9506}{}{Darüber weiß ich überhaupt nichts.}
{9507}{}{Eine dreckige Grube für diese abscheulichen Händler. Obwohl wir gelegentlich schon mit einer der zivilen Handelsfirmen Waren tauschen.}
{9508}{}{Sie sind ein Kult.}
{9509}{}{Sie sind die Zukunft der Brotherhood.}
{9510}{}{Sie sind die Wissensträger.}
{9511}{}{Sie sind diejenigen, die die Waffen für die Brotherhood herstellen.}
{9512}{}{Sie sind die Beschützer der Brotherhood.}
{9513}{}{Ich hab' keine Ahnung, wovon du sprichst.}

# BROHD34.MAP  (10000)
{10000}{}{Meister}
{10001}{}{Krieg}
{10002}{}{Exodus}
{10003}{}{Seltsame Armee|Armee}
{10004}{}{Brotherhood|BOS|Brotherhood of Steel}
{10005}{}{Merchants|Water Merchants}
{10006}{}{fehlende Caravans|fehlenden Caravans|fehlende Karawanen}
{10007}{}{Hub}
{10008}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{10009}{}{Neulinge}
{10010}{}{Scribes}
{10011}{}{Knights}
{10012}{}{Paladins}
{10013}{}{Steuerchip}
{10100}{}{Ich hab' keine Ahnung, wovon du sprichst.}
{10101}{}{Eine schreckliche, dunkle Zeit in der Geschichte der Menschheit, aus der unsere heutige Zeit hervorging. Wir bewahren das Wissen des Krieges, um einen weiteren Holocaust zu vermeiden.}
{10102}{}{Eine schwierige und bedauerliche Entscheidung. Wir haben einige gute Leute verloren, die sich unbedingt alleine anstatt mit der Haupttruppe auf die Suche nach einem sicheren Ort machen wollten.}
{10103}{}{Ich weiß nicht viel darüber. Berichten zufolge treffen sie sich irgendwo nördlich von uns.}
{10104}{}{An dem Punkt befinden wir uns gerade.}
{10105}{}{Diese Water Merchants sind stehlende Dreckskerle, aber von den anderen Gruppen weiß ich nichts.}
{10106}{}{Darüber weiß ich überhaupt nichts.}
{10107}{}{ Eine dreckige Grube für diese bösartigen Händler. Obwohl wir gelegentlich schon mit einer der zivilen Handelsfirmen Waren tauschen.}
{10108}{}{Sie sind ein Kult.}
{10109}{}{Sie sind die Zukunft der Brotherhood.}
{10110}{}{Sie sind die Wissensträger.}
{10111}{}{Sie sind diejenigen, die die Waffen für die Brotherhood herstellen.}
{10112}{}{ Sie sind die Beschützer der Brotherhood.}
{10113}{}{Ich hab' keine Ahnung, wovon du sprichst.}

# CHILDRN1.MAP (11200)
{11200}{}{Heilige Flamme}
{11201}{}{Einheit}
{11202}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{11203}{}{Morpheus}
{11204}{}{Mutanten}
{11205}{}{Meister}
{11206}{}{Follower of the Apocalypse|Follower|Followers|Apocalypse|FOA}
{11207}{}{Militärstützpunkt}
{11208}{}{Container}
{11209}{}{Steuerchip}
{11300}{}{Die Heilige Flamme wird uns in eine schöne neue Welt führen, in der es weder Hass noch Krieg gibt.}
{11301}{}{Wir gehören alle zur Einheit. Wir geben Liebe und Frieden an unsere Mitmenschen weiter - ob Mensch oder Mutant.}
{11302}{}{Das sind wir.}
{11303}{}{Morpheus ist der Hohepriester der Children. Er ist in der Regel auf seinem Zimmer, wenn er keine Predigt hält.}
{11304}{}{Es sind Menschen, die vom radioaktiven Niederschlag mutiert wurden. Aber es sind trotzdem gute Menschen.}
{11305}{}{Wir haben doch alle einen Meister, oder etwa nicht?}
{11306}{}{Es sind Menschen, die den Frieden zerstören möchten, den der Meister herzustellen versucht.}
{11307}{}{Tut mir leid, aber davon habich noch nie was gehört.}
{11308}{}{Tut mir leid, aber ich weiß nicht, wovon du sprichst.}
{11309}{}{Ich hab' keine Ahnung, wovon du sprichst.}

# CHILDRN2.MAP (11800)
{11800}{}{Heilige Flamme}
{11801}{}{Einheit}
{11802}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{11803}{}{Morpheus}
{11804}{}{Mutanten}
{11805}{}{Meister}
{11806}{}{Follower of the Apocalypse|Follower|Followers|Apocalypse|FOA}
{11807}{}{Militärstützpunkt}
{11808}{}{Container}
{11809}{}{Steuerchip}
{11900}{}{Die Heilige Flamme wird uns in eine schöne neue Welt führen, in der es weder Hass noch Krieg gibt.}
{11901}{}{Wir gehören alle zur Einheit. Wir geben Liebe und Frieden an unsere Mitmenschen weiter - ob Mensch oder Mutant.}
{11902}{}{Das sind wir.}
{11903}{}{Morpheus ist der Hohepriester der Children. Er ist in der Regel auf seinem Zimmer, wenn er keine Predigt hält.}
{11904}{}{Es sind Menschen, die vom radioaktiven Niederschlag mutiert wurden. Aber es sind trotzdem gute Menschen.}
{11905}{}{Wir haben doch alle einen Meister, oder etwa nicht?}
{11906}{}{Es sind Menschen, die den Frieden zerstören möchten, den der Meister herzustellen versucht.}
{11907}{}{Tut mir leid, aber davon hab' ich noch nie was gehört.}
{11908}{}{Tut mir leid, aber ich weiß nicht, wovon du sprichst.}
{11909}{}{Ich hab' keine Ahnung, wovon du sprichst.}

# RAIDERS.MAP
# Raiders Tell-Me-Abouts
{15400}{}{Khans}
{15401}{}{Garl}
{15402}{}{Junktown|Junk Town}
{15403}{}{Shady Sands|Shady|Sands}
{15404}{}{Hub}
{15405}{}{Steuerchip}
{15406}{}{Tandi}
{15407}{}{Alya}
{15408}{}{Diana}
{15409}{}{Gwen}
{15410}{}{Petrox}
{15411}{}{Tolya}
{15412}{}{Alkohol}
{15413}{}{Präparat}
{15414}{}{Shady Sands|Shady|Sands}
{15415}{}{Shady}
{15416}{}{Gangster}

{15500}{}{Das sind wir, du Idiot.}
{15501}{}{Er ist der Führer der Khans. Er ist der gefürchtetste Mann im Ödland.}
{15502}{}{Sie sind im Südwesten. Manchmal fahren wir nach einem harten Tag des Plünderns dorthin.}
{15503}{}{Warum wir sie nicht vollständig auslöschen, ist mir absolut schleierhaft.}
{15504}{}{Sie sind im Süden. Wir treiben mit ihnen Handel. Meistens handeln wir um Wasser und Munition, aber manchmal bekommen sie auch bessere Waffen.}
{15505}{}{Warum sollte mir das was ausmachen?}
{15506}{}{Ich kenne niemanden, der so heißt.}
{15507}{}{Sie ist Beraterin. Sie plant die Überfälle.}
{15508}{}{Sie ist für die Waffen und Rüstungen zuständig. Sie repariert unsere Ausrüstung.}
{15509}{}{Sie ist zweite Befehlshaberin.}
{15510}{}{Er kümmert sich um unsere Vorräte.}
{15511}{}{Er ist der Koch.}
{15512}{}{Hast du welche?}
{15513}{}{Hast du welche?}
{15514}{}{Warum wir sie nicht vollständig auslöschen, ist mir absolut schleierhaft.}
{15515}{}{Warum wir sie nicht vollständig auslöschen, ist mir absolut schleierhaft.}
{15516}{}{Das sind wir, du Idiot.}


# SHADYE.MAP
# Shady Sands East Tell-Me-Abouts
{16000}{}{Khans}
{16001}{}{Garl}
{16002}{}{Junktown|Junk Town}
{16003}{}{Shady Sands|Shady|Sands}
{16004}{}{Hub}
{16005}{}{Steuerchip}
{16006}{}{Tandi}
{16007}{}{Aradesh}
{16008}{}{Seth}
{16009}{}{Razlo}
{16100}{}{Sie sind eine gesetzlose Gruppe, die behauptet, aus der Vergangenheit zu kommen.}
{16101}{}{Er ist der Anführer der Khans. Er ist einer der gefährlichsten Männer, der jemals in Shady Sands gelebt hat. Er führt die Gangsterclans mit fester Hand.}
{16102}{}{Es liegt 4 - 6 Tagesreisen im Südwesten. Gelegentlich macht man dort ganz gute Geschäfte, aber die meiste Zeit versuchen die, uns übers Ohr zu hauen.}
{16103}{}{Du bist mittendrin.}
{16104}{}{Viel weiter südlich als Junktown. Der Hub ist die größte Stadt, von der ich jemals gehört habe. Dort müssen mindestens tausend Menschen leben.}
{16105}{}{Tut mir leid, aber ich kann dir nicht helfen.}
{16106}{}{Sie ist die Tochter von Aradesh. Vielleicht wird sie eines Tages unsere Führerin, allerdings muss sie lernen, ihr Temperament zu zügeln.}
{16107}{}{Er ist der Führer unserer Gemeinde und ein wahrer Held. Du triffst ihn immer bei der Arbeit im Gemeindehaus an.}
{16108}{}{Er arbeitet für Aradesh, um unsere Sicherheit zu gewährleisten.}
{16109}{}{Unser Arzt. Geh' zu ihm, wenn du verletzt bist.}

# SHADYW.MAP
# Shady Sands West Tell-Me-Abouts
{16600}{}{Khans}
{16601}{}{Garl}
{16602}{}{Junktown|Junk Town}
{16603}{}{Shady Sands|Shady|Sands}
{16604}{}{Hub}
{16605}{}{Steuerchip}
{16606}{}{Tandi}
{16607}{}{Aradesh}
{16608}{}{Seth}
{16609}{}{Razlo}
{16700}{}{Sie sind eine gesetzlose Gruppe, die behauptet, aus der Vergangenheit zu kommen.}
{16701}{}{Er ist der Anführer der Khans. Er ist einer der gefährlichsten Männer, der jemals in Shady Sands gelebt hat. Er führt die Gangsterclans mit fester Hand.}
{16702}{}{Es liegt 4 - 6 Tagesreisen im Südwesten. Gelegentlich macht man dort ganz gute Geschäfte, aber die meiste Zeit versuchen die, uns übers Ohr zu hauen.}
{16703}{}{Du bist mittendrin.}
{16704}{}{Viel weiter südlich als Junktown. Der Hub ist die größte Stadt, von der ich jemals gehört habe. Dort müssen mindestens tausend Menschen leben.}
{16705}{}{Tut mir leid, aber ich kann dir nicht helfen.}
{16706}{}{Sie ist die Tochter von Aradesh. Vielleicht wird sie eines Tages unsere Führerin, allerdings muss sie lernen, ihr Temperament zu zügeln.}
{16707}{}{Er ist der Führer unserer Gemeinde und ein wahrer Held. Du triffst ihn immer bei der Arbeit im Gemeindehaus an.}
{16708}{}{Er arbeitet für Aradesh, um unsere Sicherheit zu gewährleisten.}
{16709}{}{Unser Arzt. Geh' zu ihm, wenn du verletzt bist.}

#  ADYTUM
# Info Level 1 [People who know nothing]
{17800}{}{Adytum}
{17801}{}{Followers}
{17802}{}{Children}
{17803}{}{Rippers}
{17804}{}{Blades}
{17805}{}{Gunrunner}
{17806}{}{Hub}
{17807}{}{Junktown|Junk Town}
{17808}{}{Steuerchip}
{17809}{}{Laden}
{17810}{}{Zimmerman}
{17811}{}{Necropolis}
{17812}{}{Glow}
{17813}{}{Regulatoren}
{17814}{}{Scavengers}
{17815}{}{Boneyard}
{17900}{}{Das ist hier.}
{17901}{}{Sie leben nördlich von hier.}
{17902}{}{Es liegt ein ganzes schönes Stück südlich von uns.}
{17903}{}{Sie leben im Westen.}
{17904}{}{Sie leben im Osten.}
{17905}{}{Sie leben im Norden hinter den Followern.}
{17906}{}{Wir treiben Handel mit ihnen.}
{17907}{}{Ist das nicht eine Stadt nördlich von hier?}
{17908}{}{Eine was?}
{17909}{}{Tines Laden befindet sich in der Nähe des Tores unter der Erde.}
{17910}{}{Er ist der Bürgermeister.}
{17911}{}{Ich habe gehört, dass es im Osten ist.}
{17912}{}{Das ist ein Gerücht.}
{17913}{}{Sie beschützen uns.}
{17914}{}{Sie gehen nach draußen, um sich Dinge zu besorgen.}
{17915}{}{Dies ist der Boneyard.}

# Info level 2 [People who know something]
{18000}{}{Adytum}
{18001}{}{Followers}
{18002}{}{Children}
{18003}{}{Rippers}
{18004}{}{Blades}
{18005}{}{Gunrunner}
{18006}{}{Hub}
{18007}{}{Junktown|Junk Town}
{18008}{}{Steuerchip}
{18009}{}{Laden}
{18010}{}{Zimmerman}
{18011}{}{Necropolis}
{18012}{}{Glow}
{18013}{}{Regulatoren}
{18014}{}{Scavengers}
{18015}{}{Boneyard}
{18100}{}{Du bist in Adytum, Außenseiter.}
{18101}{}{Die Follower leben in einer alten Bibliothek ein Stück weiter nördlich. Sie predigen Toleranz und Frieden.}
{18102}{}{Die Kathedrale liegt ein Stück weiter südlich, an der Bucht. Die Children sind eine friedliche Religion.}
{18103}{}{Sie leben im Westen. Sie sind heimtückisch und haben viele Fallen.}
{18104}{}{Sie leben im Osten. Sie verwenden eine Art High-Tech-Messer.}
{18105}{}{Sie leben im Norden hinter den Followern. Sie verkaufen Waffen an die Gangs.}
{18106}{}{Wir treiben Handel mit ihnen. Die größte mir bekannte Stadt.}
{18107}{}{Eine kleine Stadt nordöstlich von uns.}
{18108}{}{Nie davon gehört.}
{18109}{}{Tines Laden ist unterirdisch in der Nähe des Tors. Er kann dir viele Vorräte verkaufen.}
{18110}{}{Er ist der Bürgermeister. Er macht seine Arbeit gut.}
{18111}{}{Es ist eine Totenstadt, einige Tagesreisen in Richtung Osten entfernt.}
{18112}{}{Ich habe gehört, es ist ganz weit im Süden.}
{18113}{}{Sie beschützen uns vor den Gangs und bewahren den Frieden.}
{18114}{}{Sie gehen nach draußen, um Dinge zu besorgen.}
{18115}{}{Wir sind im Boneyard.}

# Info level 3 [People who know more than something but less than everything]
{18200}{}{Adytum}
{18201}{}{Followers}
{18202}{}{Children}
{18203}{}{Rippers}
{18204}{}{Blades}
{18205}{}{Gunrunner}
{18206}{}{Hub}
{18207}{}{Junktown|Junk Town}
{18208}{}{Steuerchip}
{18209}{}{Laden}
{18210}{}{Zimmerman}
{18211}{}{Necropolis}
{18212}{}{Glow}
{18213}{}{Regulatoren}
{18214}{}{Scavengers}
{18215}{}{Boneyard}
{18300}{}{Wir sind Nachkommen einer alten Vault, die sich unterhalb des südlichen Teils der Stadt befand.}
{18301}{}{Die Follower sind ein gelehrtes und friedliches Volk. Sie leben in einer alten Bibliothek nördlich von hier.}
{18302}{}{Die Children beten einen mysteriösen Dunklen Gott an. Sie scheinen harmlos zu sein, aber irgendetwas ist seltsam an ihrer Religion. Die Kathedrale liegt südlich von hier.}
{18303}{}{Die Rippers wurden alle durch Inzucht gezeugt. Sie leben in einem befestigten Gebäude  mit Fallen rund herum, wo sie Gefangene halten, foltern und töten.}
{18304}{}{Die Blades sind für ihre Vibro-Messer bekannt. Sie sind die Erzfeinde der Rippers. Ihre Anführerin ist eine Frau namens Razor.}
{18305}{}{Sie waren einmal eine Gang, aber sie haben sich in einem Lagerhaus im Norden  niedergelassen und begonnen, mit Waffen zu handeln.}
{18306}{}{Der Hub ist ein Handelszentrum. Hier gibt es Firmen, die tatsächlich etwas herstellen. Sie leben östlich von uns.}
#18306 alternate If hydroponic farms aren't fixed: We sell bullets to the Hub.
{18307}{}{Junktown ist eine mittelgroße Stadt östlich von hier und nördlich vom Hubs.}
{18308}{}{Tut mir leid, da kann ich dir nicht helfen.}
{18309}{}{Tine führt den Laden in der Nähe des vorderen Tors. Er verkauft Waffen und Reiseausstattung.}
{18310}{}{Jon ist unser Bürgermeister. Er trifft Handelsvereinbarungen, bestimmt die Politik und delegiert Verantwortung an die Regulatoren und die Scavengers.}
{18311}{}{Die Totenstadt? Es ist angeblich ein Ort im Osten an dem seltsame Kannibalen leben. An deiner Stelle würde ich da nicht hin fahren.}
{18312}{}{Es ist ein großer radioaktiver Ort ganz weit im Süden, hat man mir erzählt.}
{18313}{}{Die Polizei von Adytum. Sie beschützen uns vor den Gangs. Caleb ist der Anführer.}
{18314}{}{Die Scavengers haben die Aufgabe, den Boneyard nach wertvoller Ausrüstung zu durchstöbern. Sie werden von Sammael angeführt.}
{18315}{}{Der Angel's Boneyard ist der Rest der alten Stadt Los Angele s.Wir sind mitten im Boneyard.}

#    FOLLOWERS OF THE APOCALYPSE
# Info Level 1 [People who know nothing]
{18400}{}{Adytum}
{18401}{}{Follower}
{18402}{}{Kathedrale}
{18403}{}{Ripper}
{18404}{}{Blades}
{18405}{}{Gunrunner}
{18406}{}{Hub}
{18407}{}{Junktown|Junk Town}
{18408}{}{Steuerchip}
{18409}{}{Nicole}
{18410}{}{Boneyard}
{18500}{}{Ein Dorf südlich von hier.}
{18501}{}{Wir sind die Follower of the Apocalypse.}
{18502}{}{Ein Kult im Süden, an Adytum vorbei.}
{18503}{}{Eine Gang im Westen.}
{18504}{}{Eine Gang im Osten.}
{18505}{}{Eine Gang im Norden.}
{18506}{}{Eine große Handelsstadt im Nordosten.}
{18507}{}{Eine mittelgroße Stadt nördlich des Hub.}
{18508}{}{Ich kann dir da nicht helfen, tut mir leid.}
{18509}{}{Sie ist unsere Anführerin.}
{18510}{}{Dies ist der Boneyard.}

# Info level 2 [People who know something]
{18600}{}{Adytum}
{18601}{}{Follower}
{18602}{}{Kathedrale}
{18603}{}{Ripper}
{18604}{}{Blades}
{18605}{}{Gunrunner}
{18606}{}{Hub}
{18607}{}{Junktown|Junk Town}
{18608}{}{Steuerchip}
{18609}{}{Nicole}
{18610}{}{Boneyard}
{18700}{}{Eine kleine Stadt im Süden. Gelegentlich kommen Besucher dorthin.}
{18701}{}{Wir sind die Follower of the Apocalypse. Wir nennen uns so, weil wir nach dem Sturm des Krieges kommen und den Trost des Friedens bringen.}
{18702}{}{Ein seltsamer Kult südlich von Adytum und der Rest von Boneyard. Nicole sagt, die führen etwas im Schilde.}
{18703}{}{Eine extrem gewalttätige Gang westlich von uns.}
{18704}{}{Eine Gang im Osten. Sie verwenden Vibro-Messer.}
{18705}{}{Eine Gang vom Hub, die Waffen verkauft. Sie leben nördlich von hier.}
{18706}{}{Der Hub ist eine große Handelsstadt im Osten.}
{18707}{}{Junktown ist eine kleine Stadt nördlich des Hub.}
{18708}{}{Da kann ich dir nicht helfen.}
{18709}{}{Sie ist unsere Anführerin. Sie hat die Vision in einer zersplitterten Welt den Frieden wiederherzustellen.}
{18710}{}{Dies ist Angel's Boneyard, die Überreste der alten Stadt Los Angeles.}

# Info level 3 [People who know more than something but less than everything]
{18800}{}{Adytum}
{18801}{}{Follower}
{18802}{}{Kathedrale}
{18803}{}{Ripper}
{18804}{}{Blades}
{18805}{}{Gunrunner}
{18806}{}{Hub}
{18807}{}{Junktown|Junk Town}
{18808}{}{Steuerchip}
{18809}{}{Nicole}
{18810}{}{Boneyard}
{18900}{}{Eine kleine Stadt im Süden. Es sind gute Menschen, auch wenn sie ein bisschen paranoid sind. Manche arbeiten gelegentlich mit uns.}
{18901}{}{Wir sind die Follower of the Apocalypse. Es ist unsere Pflicht, der Welt Frieden und Wissen zu bringen und sicherzustellen, dass die Waffen des Krieges nie wieder auf der Erde Schaden anrichten.}
{18902}{}{Die Kathedrale ist ein großes Gebäude südlich des Boneyard. Die Children sind ein Kult, der einem bösen Gott huldigt. Sie müssen aufgehalten werden, bevor sie ihre Religion mit Gewalt verbreiten.}
{18903}{}{Durch Inzucht gezeugte Menschen und Schakale. Sie greifen alles in Sichtweite an, was nicht mit ihnen verwandt ist. Sie leben westlich von hier in einer von Fallen umgebenen Festung.}
{18904}{}{Eine sehr gefährliche Gruppe im Osten, die mit Vibro-Messern kämpft. Ihr Anführer, Razor, kommt aus dem Hub und hat aus ihnen eine gefährliche Familie gemacht.}
{18905}{}{Sie sind eine Gang, die in einem Lager im Norden lebt, in einer Grube mit radioaktiven Schlamm. Sie verkaufen Waffen an andere Gangs.}
{18906}{}{Der Hub ist eine große Marktstadt östlich von uns. Sie schicken an viele Orte Caravans, auch nach Adytum.}
{18907}{}{Eine kleine Stadt nördlich vom Hub. Ich habe gehört, es ist ein netter Ort für müde Reisende.}
{18908}{}{Ich hab' zwar etwas über die Vault-Technologie gelesen, aber mir ist das zu hoch.}
{18909}{}{Nicole ist unsere Anführerin. Sie wird angetrieben von Spiritualität und der Bemühung, einer vom Krieg gebrochenen Welt den Frieden zu bringen.}
{18910}{}{Dies ist das Herz des Angel's Boneyard, benannt nach der alten Stadt Los Angeles und nach den Skeletten der Toten, die überall nach der Bombe hier herumlagen.}

# MBENT.MAP     (19000)
{19000}{}{Master}
{19001}{}{Leutnant}
{19002}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{19003}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{19004}{}{Nightkin}
{19005}{}{Supermutanten}
{19006}{}{Hellseher}
{19007}{}{Experimente}
{19008}{}{Steuerchip}

{19100}{}{Ich muss dir gar nichts sagen.}
{19101}{}{Solch Wissen ist nicht für niedere Lebewesen bestimmt.}
{19102}{}{Du brauchst dir um sie keine Gedanken machen.}
{19103}{}{Du bist es nicht würdig, mir Fragen zu stellen.}
{19104}{}{Geht dich nichts an.}
{19105}{}{Das geht dich nichts an.}
{19106}{}{Du bist zu dumm, um etwas über sie zu erfahren.}
{19107}{}{Du bist nicht berechtigt, etwas über sie zu erfahren.}
{19108}{}{Bleib' mir mit Spielzeug vom Hals.}

# MBSTRG12.MAP  (19600)
{19600}{}{Meister}
{19601}{}{Leutnant}
{19602}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{19603}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{19604}{}{Nightkin}
{19605}{}{Supermutanten}
{19606}{}{Hellseher}
{19607}{}{Experimente}
{19608}{}{Steuerchip}
{19700}{}{Ich muss dir gar nichts sagen.}
{19701}{}{Solch Wissen ist nicht für niedere Lebewesen bestimmt.}
{19702}{}{Du brauchst dir um sie keine Gedanken machen.}
{19703}{}{Du bist es nicht würdig, mir Fragen zu stellen.}
{19704}{}{Geht dich nichts an.}
{19705}{}{Das geht dich nichts an.}
{19706}{}{Du bist zu dumm, um etwas über sie zu wissen.}
{19707}{}{Du bist nicht berechtigt, etwas über sie zu wissen.}
{19708}{}{Bleib' mir mit Spielzeug vom Hals.}

# MBVATS12.MAP  (20200)
{20200}{}{Meister}
{20201}{}{Leutnant}
{20202}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{20203}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{20204}{}{Nightkin}
{20205}{}{Supermutanten}
{20206}{}{Hellseher}
{20207}{}{Experimente}
{20208}{}{Steuerchip}

{20300}{}{Ich muss dir gar nichts sagen.}
{20301}{}{Solch Wissen ist nicht für niedere Lebewesen bestimmt.}
{20302}{}{Du brauchst dir um sie keine Gedanken zu machen.}
{20303}{}{Du bist es nicht würdig, mir Fragen zu stellen.}
{20304}{}{Geht dich nichts an.}
{20305}{}{Das geht dich nichts an.}
{20306}{}{Du bist zu dumm, um etwas über sie zu erfahren.}
{20307}{}{Du bist nicht berechtigt, etwas über sie zu erfahren.}
{20308}{}{Bleib' mir mit Spielzeug vom Hals.}

# MSTRLR12.MAP  (20800)
{20800}{}{Meister}
{20801}{}{Leutnant}
{20802}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{20803}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{20804}{}{Nightkin}
{20805}{}{Supermutanten}
{20806}{}{Hellseher}
{20807}{}{Experimente}
{20808}{}{Steuerchip}

{20900}{}{Ich muss dir gar nichts sagen.}
{20901}{}{Solch Wissen ist nicht für niedere Lebewesen bestimmt.}
{20902}{}{Du brauchst dir um sie keine Gedanken zu machen.}
{20903}{}{Du bist es nicht würdig, mir Fragen zu stellen.}
{20904}{}{Geht dich nichts an.}
{20905}{}{Das geht dich nichts an.}
{20906}{}{Du bist zu dumm, um etwas über sie zu erfahren.}
{20907}{}{Du bist nicht berechtigt, etwas über sie zu erfahren.}
{20908}{}{Bleib' mir mit Spielzeug vom Hals.}

# MSTRLR34.MAP  (21400)
{21400}{}{Meister}
{21401}{}{Leutnant}
{21402}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{21403}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{21404}{}{Nightkin}
{21405}{}{Supermutanten}
{21406}{}{Hellseher}
{21407}{}{Experimente}
{21408}{}{Steuerchip}

{21500}{}{Ich muss dir gar nichts sagen.}
{21501}{}{Solch Wissen ist nicht für niedere Lebewesen bestimmt.}
{21502}{}{Du brauchst dir um sie keine Gedanken zu machen.}
{21503}{}{Du bist es nicht würdig, mir Fragen zu stellen.}
{21504}{}{Geht dich nichts an.}
{21505}{}{Das geht dich nichts an.}
{21506}{}{Du bist zu dumm, um etwas über sie zu erfahren.}
{21507}{}{Du bist nicht berechtigt, etwas über sie zu erfahren.}
{21508}{}{Bleib' mir mit Spielzeug vom Hals.}

# HUBENT.MAP    (22600)
{22600}{}{Polizei}
{22601}{}{Water Merchants|Water Merchant}
{22602}{}{Crimson Caravans|Crimson|Crimson Caravan}
{22603}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go}
{22604}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{22605}{}{Necropolis}
{22606}{}{Glow|Hot Spot|Spot|Hot Spots}
{22607}{}{Junktown|Junk Town}
{22608}{}{Brotherhood of Steel}
{22609}{}{Shady Sands|Shady|Sands}
{22610}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{22611}{}{Water Towers}
{22612}{}{Old Town|Oldtown}
{22613}{}{Downtown}
{22614}{}{Heights}
{22615}{}{Deathclaw}
{22616}{}{Steuerchip}

{22700}{}{Der Polizeichef Sheriff Greene ist für Recht und Ordnung im Hub zuständig. Manche glauben, die Polizei ist eher ein Hindernis als eine Hilfe.}
{22701}{}{Sie überwachen das gesamte Wasser im Hub. Sie haben die Water Towers übernommen, und jetzt müssen die Menschen sie dafür bezahlen, von ihnen Wasser zu bekommen.}
{22702}{}{Eine verrückte Gruppe von Händlern, die große Risiken eingehen, um nach oben zu gelangen.}
{22703}{}{Eine mittelmäßig gefährliche Gruppe von Händlern, die faire Preise anbieten, ohne sich selbst in Gefahr zu bringen.}
{22704}{}{Ein religiöser Kult, der etwas verehrt, was Meister oder so genannt wird. Sie haben ein Krankenhaus im Südwesten der Stadt bei den Water Merchants.}
{22705}{}{Ein gruseliger Ort. Manche behaupten, dass dort mutierte Menschen herumgeistern, die sich vom Gehirn normaler Menschen ernähren. Liegt etwas östlich vom Hub.}
{22706}{}{Es gibt Geschichten über einen Ort südöstlich von hier, der angeblich von einem atomaren Sprengkopf getroffen wurde.}
{22707}{}{Das liegt nördlich von uns. Es wird ziemlich viel Handel zwischen uns und denen getrieben. Gerüchten zufolge gehen sich Killian und Gizmo ständig an die Kehle.}
{22708}{}{Dieser Ort liegt im Nordwesten von hier. Es ist eine Handvoll Technofreaks, die nur an Technologie denken. Ziemlich schaurige Typen.}
{22709}{}{Eine primitive Stadt weit im Norden von hier. Man weiß nicht viel über sie, weil sie nicht genügend Geld haben, um mit uns Handel zu treiben.}
{22710}{}{An diesem rattenverseuchten Ort tobt der Bandenkrieg. Würde es dort keinen Handel mit Adytum und den Gunrunnern geben, bezweifle ich, dass überhaupt jemals ein Händler dorthin fahren würde.}
{22711}{}{Sie speichern das Wasser für den Hub. Die Water Merchants bewachen die Türme.}
{22712}{}{Die Old Town ist im Nordosten der Stadt. Da hängen nur Skags und Mutanten 'rum. Ich habe gehört, dass dort irgendwo ein Nest voller Diebe sein soll.}
{22713}{}{Dort machen alle Händler gute Geschäfte. Der Waffenladen, das Waffenlager, die Friendly Lending Company und der Maltese Falcon sind in dieser Gegend.}
{22714}{}{Dort leben alle reichen Händler. Der Anführer der Water Merchants, Daren Hightower, hat dort einen riesigen Palast.}
{22715}{}{Ein Mythos, mit dem kleine Kinder erschreckt werden, damit sie sich ordentlich benehmen.}
{22716}{}{Davon weiß ich überhaupt nichts.}

# HUBDWNTN.MAP  (23800)
{23800}{}{Polizei}
{23801}{}{Water Merchants|Water Merchant}
{23802}{}{Crimson Caravans|Crimson|Crimson Caravan}
{23803}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go}
{23804}{}{Cathedral}
{23805}{}{Necropolis}
{23806}{}{Glow|Hot Spot|Spot|Hot Spots}
{23807}{}{Junktown|Junk Town}
{23808}{}{Brotherhood}
{23809}{}{Shady Sands|Shady|Sands}
{23810}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{23811}{}{Water Towers}
{23812}{}{Oldtown}
{23813}{}{Downtown}
{23814}{}{Heights}
{23815}{}{Claw}
{23816}{}{Steuerchip}
{23900}{}{Der Polizeichef Sheriff Greene ist für Recht und Ordnung im Hub zuständig. Manche glauben, die Polizei ist eher ein Hindernis als eine Hilfe.}
{23901}{}{Sie überwachen das gesamte Wasser im Hub. Sie haben die Water Towers übernommen, und jetzt müssen die Menschen sie dafür bezahlen, von ihnen Wasser zu bekommen.}
{23902}{}{Eine verrückte Gruppe von Händlern, die große Risiken eingehen, um nach oben zu gelangen.}
{23903}{}{Eine mittelmäßig gefährliche Gruppe von Händlern, die faire Preise anbieten, ohne sich selbst in Gefahr zu bringen.}
{23904}{}{Ein religiöser Kult, der etwas verehrt, was Meister oder so genannt wird. Sie haben ein Krankenhaus im}
{23905}{}{Ein gruseliger Ort. Manche behaupten, dass dort mutierte Menschen herumgeistern, die sich vom Gehirn normaler Menschen ernähren. Liegt etwas östlich vom Hub.}
{23906}{}{Es gibt Geschichten über einen Ort südöstlich von hier, der angeblich von einem atomaren Sprengkopf getroffen wurde.}
{23907}{}{Das liegt nördlich von uns. Es wird ziemlich viel Handel zwischen uns und denen getrieben.}
{23908}{}{Dieser Ort liegt im Nordwesten von hier. Es ist eine Handvoll Technofreaks, die nur an Technologie denken. Ziemlich schaurige Typen.}
{23909}{}{Eine primitive Stadt weit im Norden von hier. Man weiß nicht viel über sie, weil sie nicht genügend Geld haben, um mit uns Handel zu treiben.}
{23910}{}{An diesem rattenverseuchten Ort tobt der Bandenkrieg. Würde es dort keinen Handel mit}
{23911}{}{Sie speichern das Wasser für den Hub. Die Water Merchants bewachen die Türme.}
{23912}{}{Die Old Town ist im Nordosten der Stadt. Da hängen nur Skags und Mutanten 'rum. Ich habe gehört, dass dort irgendwo ein Nest voller Diebe sein soll.}
{23913}{}{Dort machen alle Händler gute Geschäfte. Der Waffenladen, das Waffenlager, die Friendly Lending Company}
{23914}{}{Dort leben alle reichen Händler. Der Anführer der Water Merchants, Daren Hightower, hat dort einen riesigen Palast.}
{23915}{}{Ein Mythos, mit dem kleine Kinder erschreckt werden, damit sie sich ordentlich benehmen.}
{23916}{}{Ich weiß darüber nichts.}

# HUBHEIGT.MAP  (24400)
{24400}{}{Polizei}
{24401}{}{Water Merchants|Water Merchant}
{24402}{}{Crimson Caravans|Crimson|Crimson Caravan}
{24403}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go}
{24404}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{24405}{}{Necropolis}
{24406}{}{Glow|Hot Spot|Spot|Hot Spots}
{24407}{}{Junktown|Junk Town}
{24408}{}{Brotherhood of Steel}
{24409}{}{Shady Sands|Shady|Sands}
{24410}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{24411}{}{Water Towers}
{24412}{}{Old Town|Oldtown}
{24413}{}{Downtown}
{24414}{}{Heights}
{24415}{}{Deathclaw}
{24416}{}{Steuerchip}
{24500}{}{Der Polizeichef Sheriff Greene ist für Recht und Ordnung im Hub zuständig. Manche glauben, die Polizei ist eher ein Hindernis als eine Hilfe.}
{24501}{}{Sie überwachen das gesamte Wasser im Hub. Sie haben die Water Towers übernommen, und jetzt müssen die Menschen sie dafür bezahlen, von ihnen Wasser zu bekommen.}
{24502}{}{Eine verrückte Gruppe von Händlern, die große Risiken eingehen, um nach oben zu gelangen.}
{24503}{}{Eine mittelmäßig gefährliche Gruppe von Händlern, die faire Preise anbieten, ohne sich selbst in Gefahr zu bringen.}
{24504}{}{Ein religiöser Kult, der etwas verehrt, was Meister oder so genannt wird. Sie haben ein Krankenhaus im Südwesten der Stadt bei den Water Merchants.}
{24505}{}{Ein gruseliger Ort. Manche behaupten, dass dort mutierte Menschen herumgeistern, die sich vom Gehirn normaler Menschen ernähren. Liegt etwas östlich vom Hub.}
{24506}{}{Es gibt Geschichten über einen Ort südöstlich von hier, der angeblich von einem atomaren Sprengkopf getroffen wurde.}
{24507}{}{Das liegt nördlich von uns. Es wird ziemlich viel Handel zwischen uns und denen getrieben. Gerüchten zufolge gehen sich Killian und Gizmo ständig an die Kehle.}
{24508}{}{Dieser Ort liegt im Nordwesten von hier. Es ist eine Handvoll Technofreaks, die nur an Technologie denken. Ziemlich schaurige Typen.}
{24509}{}{Eine primitive Stadt weit im Norden von hier. Man weiß nicht viel über sie, weil sie nicht  genügend Geld haben, um mit uns Handel zu treiben.}
{24510}{}{An diesem rattenverseuchten Ort tobt der Bandenkrieg. Würde es dort keinen Handel mit Adytum und den Gunrunnern geben, bezweifle ich, dass überhaupt jemals ein Händler dorthin fahren würde.}
{24511}{}{Sie speichern das Wasser für den Hub. Die Water Merchants bewachen die Türme.}
{24512}{}{Die Old Town ist im Nordosten der Stadt. Da hängen nur Skags und Mutanten 'rum. Ich habe gehört, dass dort irgendwo ein Nest voller Diebe sein soll.}
{24513}{}{Dort machen alle Händler gute Geschäfte. Der Waffenladen, das Waffenlager, die Friendly Lending Company und der Maltese Falcon sind alle in dieser Gegend.}
{24514}{}{Dort leben alle reichen Händler. Der Anführer der Water Merchants, Daren Hightower, hat dort einen riesigen Palast.}
{24515}{}{Ein Mythos, mit dem kleine Kinder zu erschreckt werden, damit sie sich ordentlich benehmen.}
{24516}{}{Davon weiß ich überhaupt nichts.}

# HUBOLDTN.MAP  (25000)
{25000}{}{Polizei}
{25001}{}{Water Merchants|Water Merchant}
{25002}{}{Crimson Caravans|Crimson|Crimson Caravan}
{25003}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go}
{25004}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{25005}{}{Necropolis}
{25006}{}{Glow|Hot Spot|Spot|Hot Spots}
{25007}{}{Junktown|Junk Town}
{25008}{}{Brotherhood of Steel}
{25009}{}{Shady Sands|Shady|Sands}
{25010}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{25011}{}{Water Towers}
{25012}{}{Old Town|Oldtown}
{25013}{}{Downtown}
{25014}{}{Heights}
{25015}{}{Deathclaw}
{25016}{}{Steuerchip}
{25100}{}{Der Polizeichef Sheriff Greene ist für Recht und Ordnung im Hub zuständig. Manche glauben, die Polizei ist eher ein Hindernis als eine Hilfe.}
{25101}{}{Sie überwachen das gesamte Wasser im Hub. Sie haben die Water Towers übernommen, und jetzt müssen die Menschen sie dafür bezahlen, von ihnen Wasser zu bekommen.}
{25102}{}{Eine verrückte Gruppe von Händlern, die große Risiken eingehen, um nach oben zu gelangen.}
{25103}{}{Eine mittelmäßig gefährliche Gruppe von Händlern, die faire Preise anbieten, ohne sich selbst in Gefahr zu bringen.}
{25104}{}{Ein religiöser Kult, der etwas verehrt, was Meister oder so genannt wird. Sie haben ein Krankenhaus im Südwesten der Stadt bei den Water Merchants.}
{25105}{}{Ein gruseliger Ort. Manche behaupten, dass dort mutierte Menschen herumgeistern, die sich vom Gehirn normaler Menschen ernähren. Liegt etwas östlich vom Hub.}
{25106}{}{Es gibt Geschichten über einen Ort südöstlich von hier, der angeblich von einem atomaren Sprengkopf getroffen wurde.}
{25107}{}{Das liegt nördlich von uns. Es wird ziemlich viel Handel zwischen uns und denen getrieben. Gerüchten zufolge gehen sich Killian und Gizmo ständig an die Kehle.}
{25108}{}{Dieser Ort liegt im Nordwesten von hier. Es ist eine Handvoll Technofreaks, die nur an Technologie denken. Ziemlich schaurige Typen.}
{25109}{}{Eine primitive Stadt weit im Norden von hier. Man weiß nicht viel über sie, weil sie nicht genügend Geld haben, um mit uns Handel zu treiben.}
{25110}{}{An diesem rattenverseuchten Ort tobt der Bandenkrieg. Würde es dort keinen Handel mit Adytum und den Gunrunnern geben, bezweifle ich, dass überhaupt jemals ein Händler dorthin fahren würde.}
{25111}{}{Sie speichern das Wasser für den Hub. Die Water Merchants bewachen die Türme.}
{25112}{}{Die Old Town ist im Nordosten der Stadt. Da hängen nur Skags und Mutanten 'rum. Ich habe gehört, dass dort irgendwo ein Nest voller Diebe sein soll.}
{25113}{}{Dort verkaufen alle Händler. Der Waffenladen, das Waffenlager, die Friendly Lending Company und der Maltese Falcon sind alle in dieser Gegend.}
{25114}{}{Dort leben alle reichen Händler. Der Anführer der Water Merchants, Daren Hightower, hat dort einen riesigen Palast.}
{25115}{}{Ein Mythos, mit dem kleine Kinder erschreckt werden, damit sie sich ordentlich benehmen.}
{25116}{}{Davon weiß ich überhaupt nichts.}

# HUBWATER.MAP  (25600)
{25600}{}{Polizei}
{25601}{}{Water Merchants|Water Merchant}
{25602}{}{Crimson Caravans|Crimson|Crimson Caravan}
{25603}{}{Far Go Traders|Fargo|Fargo Trader|Fargo Traders|FAR-GO-TRADERS|Far Go|Far-Go}
{25604}{}{Children of the Cathedral|Children|Cathedral|CoC|Kathedrale}
{25605}{}{Necropolis}
{25606}{}{Glow|Hot Spot|Spot|Hot Spots}
{25607}{}{Junktown|Junk Town}
{25608}{}{Brotherhood of Steel}
{25609}{}{Shady Sands|Shady|Sands}
{25610}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{25611}{}{Water Towers}
{25612}{}{Old Town|Oldtown}
{25613}{}{Downtown}
{25614}{}{Heights}
{25615}{}{Deathclaw}
{25616}{}{Steuerchip}
{25700}{}{Der Polizeichef Sheriff Greene ist für Recht und Ordnung im Hub zuständig. Manche glauben, die Polizei ist eher ein Hindernis als eine Hilfe.}
{25701}{}{Sie überwachen das gesamte Wasser im Hub. Sie haben die Water Towers übernommen, und jetzt müssen die Menschen sie dafür bezahlen, von ihnen Wasser zu bekommen.}
{25702}{}{Eine verrückte Gruppe von Händlern, die große Risiken eingehen, um nach oben zu gelangen.}
{25703}{}{Eine mittelmäßig gefährliche Gruppe von Händlern, die faire Preise anbieten, ohne sich selbst in Gefahr zu bringen.}
{25704}{}{Ein religiöser Kult, der etwas verehrt, was Meister oder so genannt wird. Sie haben ein Krankenhaus im Südwesten der Stadt bei den Water Merchants.}
{25705}{}{Ein gruseliger Ort. Manche behaupten, dass dort mutierte Menschen herumgeistern, die sich vom Gehirn normaler Menschen ernähren. Liegt etwas östlich vom Hub.}
{25706}{}{Es gibt Geschichten über einen Ort südöstlich von hier, der angeblich von einem atomaren Sprengkopf getroffen wurde.}
{25707}{}{Das liegt nördlich von uns. Es wird ziemlich viel Handel zwischen uns und denen getrieben. Gerüchten zufolge gehen sich Killian und Gizmo ständig an die Kehle.}
{25708}{}{Dieser Ort liegt im Nordwesten von hier. Es ist eine Handvoll Technofreaks, die nur an Technologie denken. Ziemlich schaurige Typen.}
{25709}{}{Eine primitive Stadt weit im Norden von hier. Man weiß nicht viel über sie, weil sie nicht  genügend Geld haben, um mit uns Handel zu treiben.}
{25710}{}{An diesem rattenverseuchten Ort tobt der Bandenkrieg. Würde es dort keinen Handel mit Adytum und den Gunrunnern geben, bezweifle ich, dass überhaupt jemals ein Händler dorthin fahren würde.}
{25711}{}{Sie speichern das Wasser für den Hub. Die Water Merchants bewachen die Türme.}
{25712}{}{Die Old Town ist im Nordosten der Stadt. Da hängen nur Skags und Mutanten 'rum. Ich habe gehört, dass dort irgendwo ein Nest voller Diebe sein soll.}
{25713}{}{Dort verkaufen alle Händler. Der Waffenladen, das Waffenlager, die Friendly Lending Company und der Maltese Falcon sind alle in dieser Gegend.}
{25714}{}{Dort leben alle reichen Händler. Der Anführer der Water Merchants, Daren Hightower, hat dort einen riesigen Palast.}
{25715}{}{Ein Mythos, mit dem kleine Kinder erschreckt werden, damit sie sich ordentlich benehmen.}
{25716}{}{Davon weiß ich überhaupt nichts.}

#    BLADES
# Info Level 1 [People who know nothing]
{27400}{}{Adytum}
{27401}{}{Follower}
{27402}{}{Kathedrale}
{27403}{}{Ripper}
{27404}{}{Blades}
{27405}{}{Gunrunner}
{27406}{}{Hub}
{27407}{}{Junktown|Junk Town}
{27408}{}{Steuerchip}
{27409}{}{Razor}
{27410}{}{Necropolis}
{27411}{}{Glow}
{27412}{}{Boneyard}
{27500}{}{Eine Stadt im Westen.}
{27501}{}{Eine Hand voll Waschlappen.}
{27502}{}{Religiöse Hohlköpfe.}
{27503}{}{Unsere eingeschworenen Feinde!}
{27504}{}{Das sind wir!}
{27505}{}{Sie verkaufen uns manchmal Waffen.}
{27506}{}{Ich glaube, es ist ein Ort zum Handeln.}
{27507}{}{Nie davon gehört.}
{27508}{}{Was?}
{27509}{}{Sie ist unsere Anführerin, das größte Miststück in der Stadt!}
{27510}{}{Necro- was? Das ist doch verrückt.}
{27511}{}{Du machst wohl Scherze?}
{27512}{}{Dies ist der Boneyard.}

# Info Level 2 [People who know something]
{27600}{}{Adytum}
{27601}{}{Follower}
{27602}{}{Kathedrale}
{27603}{}{Ripper}
{27604}{}{Blades}
{27605}{}{Gunrunner}
{27606}{}{Hub}
{27607}{}{Junktown|Junk Town}
{27608}{}{Steuerchip}
{27609}{}{Razor}
{27610}{}{Necropolis}
{27611}{}{Glow}
{27612}{}{Boneyard}
{27700}{}{Ein Dorf voller Weichlinge im Südwesten.}
{27701}{}{Jämmerliche Friedensprediger im Westen. Wir würden sie niedermetzeln, wenn wir nicht schon mit den Rippern beschäftigt wären.}
{27702}{}{Religiöse Freaks. Harmlos und nutzlos.}
{27703}{}{Unsere Erzfeinde im Westen werden bald erledigt sein!}
{27704}{}{Wir sind die Blades! Vergiss das nie!}
{27705}{}{Sie waren mal eine Gang, aber sie wurden weich. Sie verkaufen aber gute Waffen.}
{27706}{}{Händler und Kaufleute.}
{27707}{}{Ich habe schon von dem Ort gehört, aber nichts darüber erfahren.}
{27708}{}{Was?}
{27709}{}{Razor ist die beste Kämpferin von uns allen. Sie wird uns den Sieg bringen.}
{27710}{}{Eine Geschichte über eine Stadt von Kannibalen, die Kinder erschrecken.}
{27711}{}{Muss dort sein, wo die Bombe eingeschlagen hat.}
{27712}{}{Dies ist der Boneyard.}

# Info level 3 [People who know more than something but less than everything]
{27800}{}{Adytum}
{27801}{}{Follower}
{27802}{}{Kathedrale}
{27803}{}{Ripper}
{27804}{}{Blades}
{27805}{}{Gunrunner}
{27806}{}{Hub}
{27807}{}{Junktown|Junk Town}
{27808}{}{Steuerchip}
{27809}{}{Razor}
{27810}{}{Necropolis}
{27811}{}{Glow}
{27812}{}{Boneyard}
{27900}{}{Lass' dich nicht in die Irre führen. Adytum sieht zwar wie ein kleines Dorf aus, die Regulatoren sind jedoch knallhart.}
{27901}{}{Hmph. Frag erst gar nicht. Kämpfen haben sie nicht den Zum Mut.}
{27902}{}{Sie sind Kultanhänger in einer großen Kirche im Süden. Sie machen einen harmlosen Eindruck, aber dort geht irgendetwas Seltsames vor sich.}
{27903}{}{Die Rippers sind wie räudige Hunde - bösartig, inzüchtig und dumm.}
{27904}{}{Siehst du meine Klinge? Wir stellen sie selbst her. Jeder von uns fertigt seine eigene an. Daher unser Name.}
{27905}{}{Sie kamen vom Hub herunter und haben nach einem Revier Ausschau gehalten, aber sie entschlossen sich, Händler anstelle von Kriegern zu werden.}
{27906}{}{Es ist eine Handelsstadt im Osten. Manchmal kommen Händler von dort hierher, um mit Adytum und den Gunrunnern Handel zu treiben.}
{27907}{}{Ich glaube, es liegt nordöstlich von hier. Es ist eine Kleinstadt.}
{27908}{}{Was?}
{27909}{}{Razor ist unsere Führerin und unsere Siegerin. Ich zweifle keine Sekunde daran,  dass wir durch ihre Erfahrung die Rippers besiegen werden.}
{27910}{}{Weit östlich von hier. Angeblich leben dort Ghuls, die Menschenfleisch essen. Ich würde nicht gegen die Ghuls kämpfen wollen.}
{27911}{}{Das sind angeblich die Ruinen eines Ortes, der direkt von einer Atombombe getroffen wurde. Ich glaube, es liegt ziemlich weit im Süden.}
{27912}{}{Dies ist der Boneyard.}

#   GUN RUNNERS
#Info Level 1 [People who know nothing]
{28600}{}{Adytum}
{28601}{}{Follower}
{28602}{}{Kathedrale}
{28603}{}{Ripper}
{28604}{}{Blades}
{28605}{}{Gunrunner}
{28606}{}{Hub}
{28607}{}{Junktown|Junk Town}
{28608}{}{Steuerchip}
{28609}{}{Boneyard}
{28700}{}{Ein kleines Dorf südlich von hier.}
{28701}{}{Eine Gruppe Hippies im Süden.}
{28702}{}{Meinst du die Typen in braunen Roben?}
{28703}{}{Eine Gang im Westen.}
{28704}{}{Eine hinterlistige Gang im Osten.}
{28705}{}{Ja? Was?}
{28706}{}{Wir kaufen Waffen von denen und verkaufen sie direkt an dich!}
{28707}{}{Ja, kleine Stadt nördlich vom Hub.}
{28708}{}{Was?}
{28709}{}{Dies ist der Boneyard.}

# Info Level 2 [People who know something]
{28800}{}{Adytum}
{28801}{}{Follower}
{28802}{}{Kathedrale}
{28803}{}{Ripper}
{28804}{}{Blades}
{28805}{}{Gunrunner}
{28806}{}{Hub}
{28807}{}{Junktown|Junk Town}
{28808}{}{Steuerchip}
{28809}{}{Boneyard}
{28900}{}{Ein kleines Dorf im Süden. Ganz gut befestigt.}
{28901}{}{Eine Gruppe von friedliebenden Typen südlich von hier. Wir sollten sie  einfach loswerden.}
{28902}{}{Oh ja, diese verrückten alten Mönche. Die spinnen ganz schön. Ihre große Kirche befindet sich südlich vom Boneyard.}
{28903}{}{Naja, sie sind vielleicht dumm, aber sie kaufen trotzdem eine Menge Waffen!}
{28904}{}{Sie verwenden immer diese seltsamen Vibro-Messer, die sie selbst herstellen. Ich hätte gerne mal so eins. Aber sie kaufen zumindest auch Waffen.}
{28905}{}{Du sprichst mit uns.}
{28906}{}{Es ist ein großes Handelszentrum im Osten. Wir treiben mit Händlern aus dem Hub Handel, um Waffen und Rüstungen zu kaufen und zu verkaufen.}
{28907}{}{Eine kleine Stadt nördlich des Hub. Bisschen streng.}
{28908}{}{Nie davon gehört.}
{28909}{}{Wir sind nördlich vom Boneyard.}

# Info Level 3 [People who know more than something but less than everything]
{29000}{}{Adytum}
{29001}{}{Follower}
{29002}{}{Kathedrale}
{29003}{}{Ripper}
{29004}{}{Blades}
{29005}{}{Gunrunner}
{29006}{}{Hub}
{29007}{}{Junktown|Junk Town}
{29008}{}{Steuerchip}
{29009}{}{Boneyard}
{29100}{}{Eine kleine Stadt im Süden. Hat nichts mit uns zu tun. Die sind mir völlig gleichgültig.}
{29101}{}{Sie versuchen, jeden für ihre Friedenssache zu gewinnen, während sie sich in ihren Bibliotheken im Süden verstecken. Sie tragen nicht gerade zu den Geschäften bei!}
{29102}{}{Die Kathedrale ist diese große Kirche südlich des Boneyard, wo ein seltsamer Kult dem Dunklen Gott huldigt. Ich halte sie für ziemlich ausgeflippt.}
{29103}{}{Die Rippers sind sprichwörtlich eine große Familie. Mit denen kann man überhaupt nicht handeln, wenn sie dich nicht kennen, also versuch´s erst gar nicht. Sie leben in einer großen Festung mit Todesfallen südwestlich von uns. Pass auf Landminen auf, wenn du so blöd bist, dorthin zu gehen.}
{29104}{}{Ihr Zuhause sind mehrere kleine Gebäude im Südosten. Sie sind sehr gut organisiert und klüger als die Ripper.Manchmal können auch Fremde Mitglied werden. Ihr Anführer, Razor, ist eine knallharte Frau.}
{29105}{}{Das sind wir. Man verdient gutes Geld durch den Verkauf von Waffen an die Blades und die Rippers.}
{29106}{}{Das ist die Handelsstadt im Osten von hier, wo wir unsere Waffen herkriegen und  Handel treiben. Sie schicken in alle Richtungen Caravans aus. Du könntest wahrscheinlich mit einem Caravan fahren, wenn einer in Adytum aufkreuzt.}
{29107}{}{Es ist eine kleine Grenzstadt nördlich vom Hub. Dort gibt es ein großes Kasino, aber der Sheriff der Stadt ist ein bisschen zu arrogant.}
{29108}{}{Ich hab' keine Ahnung, was das ist.}
{29109}{}{Die Nordseite des Boneyard. Es ist sonderbar, für Leute von außerhalb ist es ein Fluch - wenn etwas schlecht ist, sagen sie "Das sollte in den Boneyard geschicht werden". Aber es ist gar nicht mal so schlecht, wenn man sich daran gewöhnt hat.}
