{100}{}{Du! Bleib sofort stehen und stell dich dem Gesetz!}
{101}{}{Danke, daß du den Steuerchip zurückgebracht hast. Er ist wirklich sehr nützlich, wenn es um die Erhaltung der Moral geht und er hält die Leute davon ab, die Gesetze der Vault zu brechen.}
{102}{}{Schön, dich wiederzusehen. Kann ich was für dich tun?}
{103}{}{Was machst du?}
{104}{}{Ja, ich brauch' ein paar Waffen.}
{105}{}{Warum sollte es in der Vault eine verschlossene Tür geben?}
{106}{}{Glop!}
{107}{}{Hmmm. Ich find', du hast hier nichts verloren. Schönen Tag noch.}
{108}{}{Ich kümmere mich hier in der Vault um die Sicherheit und um die Einhaltung
 des Gesetzes. Du glaubst es vielleicht nicht, aber ohne mich würde die Vault nicht
 so gut laufen.}
{109}{}{Hmm. Klasse. Danke.}
{110}{}{Hört sich wichtig an.}
{111}{}{Das ist es auch. Würde das Gesetz nicht gewahrt werden, wäre die Vault bald ein gesetzloser und chaotischer Ort. Unser aller Sicherheit wäre in Gefahr.}
{112}{}{Gibt es jetzt, nachdem ich draußen war, irgendwelche Gesetze, die speziell für mich gelten?}
{113}{}{Ich habe in der Außenwelt einige Orte gesehen, denen es sehr schlecht geht, weil sie keine Gesetze haben.}
{114}{}{Du brauchst die Waffen zwar in der Außenwelt, aber zeig' sie hier lieber nicht herum. Das ist alles, was du noch beachten solltest.}
{115}{}{Danke.}
{116}{}{Ich hab' gewußt, daß das passieren würde. Gesetzestreue Leute sind das einzige
 funktionierende Mittel, um die Vault vor Elend und Zerstörung zu bewahren. Mach' weiter so.}
{117}{}{Der Aufseher hat es mir nicht erlaubt, die Waffenkammer zu öffnen und dir
 weitere Waffen auszuhändigen. Tut mir leid, aber ich kann dir nicht helfen. }
{118}{}{Bitte! Ich brauch' sie wirklich!}
{119}{}{OK. Trotzdem danke.}
{120}{}{Nein, das kann ich nicht machen.}
{121}{}{Einen schönen Tag noch.}
{122}{}{Die Waffen von denjenigen fernhalten, die keinen Zugang dazu haben dürfen.}
{123}{}{Wer hat denn Zugang?}
{124}{}{Das ist doch unfair.}
{125}{}{Das Leben ist halt nicht immer fair. Aber unsere Gesetze sind es. Einen schönen Tag noch.}
{126}{}{Der Aufseher, mein Sicherheitsteam und ich. Mehr nicht.}
{127}{}{Klingt so, als hätten nur die Leute Zugang, die wirklich welche brauchen.}
{128}{}{Das ist aber eine sehr kleine Liste.}
{129}{}{Ja, stimmt. Ich muß zurück an die Arbeit.}
{130}{}{Ja, es dürfen nur die Leute rein, die wirklich welche brauchen.}
{131}{}{Also, ich brauch' unbedingt welche. Öffne bitte die Tür.}
{132}{}{Tut mir leid, ist zwar ein gutes Argument, aber ich kann dich nicht reinlassen.}
{133}{}{Hmm. Also jetzt, wo du es sagst, kommt es mir auch so vor. OK. Ich öffne dir die Tür.}
{134}{}{Wie kann ich dir helfen, }
{135}{}{?}
{136}{}{Ich brauch' mehr Waffen.}
{137}{}{Geht's dir gut?}
{138}{}{Huh-huh.}
{139}{}{Großartig. Deine Intelligenz haut mich um. Ich glaub', ich kann gar nicht mehr klar denken.}
{140}{}{Tut mir leid, du hast alles bekommen, was wir dir geben können. Schönen Tag noch.}
{141}{}{Ich kann Typen wie dich nicht ausstehen. Lauter Störenfriede. Du solltest dich wirklich schämen.}
{142}{}{Ja, du auch, Schafskopf.}
{143}{}{Denkst du nicht, daß du ein bißchen zu streng bist?}
{144}{}{Paß' auf was du sagst, oder ich nehme dich wegen Beamtenbeleidigung fest.}
{145}{}{Ja, OK. Bis bald.}
{146}{}{Das war's. Ich hab's satt, mich von dir blöd anreden zu lassen.}
{147}{}{Hmm. Vielleicht. Es gehört eigentlich zu meinem Job, gerecht zu sein, aber ich glaub' dieses Mal bin ich zu weit gegangen. Ich werd' mich bessern.}
{148}{}{Hmm. Nein. Wahrscheinlich noch nicht streng genug.}
{149}{}{Viel Glück. Ich hoffe, du schaffst den Job.}
{150}{}{Enttäusch' mich nicht!}
{151}{}{Nimm sofort deine Waffe weg.}
{152}{}{Was machst du eigentlich hier drinnen damit?}
{153}{}{Ich übe nur das Zielen.}
{154}{}{Nichts, tut mir leid. Ich wollte sie gar nicht ziehen.}
{155}{}{Hung.}
{156}{}{Paß' auf, was du sagst. Und zieh' da drinnen keine Waffe. Das hier ist die Vault, verdammt noch mal.}
{157}{}{Es wäre besser, wenn du hier drinnen nicht üben würdest. Wenn du das
 noch mal machst, kriegen wir beide ernsthafte Probleme miteinander.}
{158}{}{Ich wußte, daß du in der Außenwelt nicht zurechtkommen würdest.}
{159}{}{Halt! Du hast hier keinen Zutritt!}

{1000}{}{Aufseher}
{1100}{}{Er hat die Macht in der Vault, und wir alle befolgen seine Anweisungen.}