{100}{}{Du siehst Petrox, einen Wüstenbanditen.}
{101}{}{Sei gegrüßt! Ich bin Petrox. Ich bin einer von Garls Top-Gangstern. Wer bist du?}
{102}{}{Ich bin }
{103}{}{. Was treibt man so als Gangster?}
{104}{}{Mein Name tut im Moment nichts zur Sache. Kannst du mir etwas über euer Lager erzählen?}
{105}{}{Hroo?}
{106}{}{Als Gangster reise ich durch viele Orte des Ödlands. Auf diesen Reisen besorge ich
 Vorräte für das Lager.}
{107}{}{Mit anderen Worten: Du klaust es von den Leuten, die du besuchst.}
{108}{}{Hey, das ist ja toll. Sicher ist Garl sehr zufrieden mit dir.}
{109}{}{Wo warst du denn überall?}
{110}{}{Das ist aber nett, daß du dich für wichtig genug hältst, um ohne Namen hier herumlaufen zu können. Dann werd' ich dir zumindest ein bißchen was über uns erzählen. Wir sind die härtesten Kerle des Ödlands. Gegen uns kommt niemand an. Wir sind keine solchen Feiglinge wie diese Leute aus Shady Sands oder Junktown.}
{111}{}{Was ist mit Shady Sands?}
{112}{}{Was ist Junktown?}
{113}{}{Ich bedaure, aber ich kann meine Zeit nicht mit so lahmen Leuten verschwenden.
 Wiedersehen.}
{114}{}{Wir stehlen niemals. Wir nehmen uns nur das, was die anderen übrig haben und verteilen es unter unseren hungrigen Leuten.}
{115}{}{Also, genau genommen stiehlt ihr es.}
{116}{}{Das klingt nach einer wirklich guten Idee.}
{117}{}{Ich war an vielen Orten des Ödlands. Die am nächsten gelegenen Orte von hier aus, wo ich schon war, heißen Shady Sands und Junktown. Dort ist zwar nicht viel los, aber es gibt immer eine Menge Informationen und Vorräte.}
{118}{}{Erzähl' mir was über Shady Sands.}
{119}{}{Erzähl' mir was über Junktown.}
{120}{}{Du gehst mir langsam auf den Wecker. Ich denk', ich werd' das Problem mal in die Hand nehmen.}
{121}{}{Shady Sands ist eine sehr fruchtbare Gemeinde. Sie, äh, teilen ihren Ertrag wirklich gerne mit uns.}
{122}{}{Was kannst du mir über Junktown erzählen?}
{123}{}{Junktown ist etwas südlich von hier. Gibt 'ne Menge schöner Frauen dort.}
{124}{}{Junktown ist etwas südlich von hier. Gibt 'ne Menge schöner Frauen dort. Ich kann dich gerne mal herumführen. Vielleicht könnten wir uns dabei auch noch etwas besser kennenlernen . . . was meinste?}
{125}{}{Nein, danke, ein andermal vielleicht.}
{126}{}{Klar, später vielleicht.}
{127}{}{OK, später vielleicht.}
{128}{}{Ich hab dir alles erzählt, was ich sagen darf. Geh' jetzt bitte.}

#
# Fallout Fixt:
#
{200}{}{Du siehst: Petrox, Khan scavenger.}
