{100}{}{Du siehst einen gefangenen Ghul.}
{101}{}{Wa-was willst du.}
{102}{}{Äh, nichts.}
{103}{}{Hng.}
{104}{}{Ich bin hier, um dich zu befreien.}
{105}{}{Was erwartest du.}
{106}{}{Hey, das interessiert mich nicht. Hol' mich einfach hier raus!}
{107}{}{Großartig! Mach' es!}
{108}{}{Ich hab' Wasser gestohlen. Hey, ich hab' niemanden verletzt, ich hatte einfach Durst.}
{109}{}{Du hast dir mehr genommen als dir zustand.}
{110}{}{Ach, kein Problem für mich. Ich hol' dich raus.}
{111}{}{Ohne das Wasser wäre ich verdurstet. Es war nur eine Tasse. Gerade genug, um
 zu überleben. Du mußt mich hier rausholen. Ich werd' hier drinnen noch wahnsinnig!}
{112}{}{OK. Wart' einen Moment.}
{113}{}{Ich glaub', ich überlaß' dich den Behörden.}
{114}{}{Laß' mich bitte gehen.}
{115}{}{Danke, daß du mich rausgelassen hast.}
{116}{}{Ist schon gut.}
{117}{}{Woher kommt das Wasser?}
{118}{}{Ja.}
{119}{}{Sie pumpen es von den unteren Brunnen hoch. In der Zelle nebenan ist ein Einstiegsloch, durch das man in die alte Vault gelangt. Von dort stammt das Wasser. Wenn die da unten nicht wären, wären wir hier besser dran.}
{120}{}{Was meinst du damit?}
{121}{}{Danke.}
{122}{}{Manchmal ist es schwierig, dafür zu sorgen, daß die alte Technologie richtig
 arbeitet. Sobald wir runtergehen, schlagen die Verstrahlten Ghuls zu. Wir Ghuls lassen sie einfach in Ruhe. Und die großen Mutanten kümmern sich einen feuchten Kehricht darum.}
{123}{}{Viel Glück. Wiedersehen.}
{124}{}{Du erhältst }
{125}{}{ Erfahrungspunkte für die Befreiung des gefangenen Ghuls.}
{126}{}{Nochmals danke.}