{100}{}{Du siehst Gideon, einen normal aussehenden Menschen. Er trägt eine Krone.}
{101}{}{Jason ist ein lebendiger Gott! Nur die Annullierten dürfen passieren!}
{102}{}{Annulliert? Werden eure hellseherischen Kräfte durch die Geräte beeinträchtigt, die ihr da tragt?}
{103}{}{Wer ist Jason?}
{104}{}{Was meinst du mit annulliert?}
{105}{}{Ich habe ihn soeben getötet. Deshalb ist er jetzt wohl ein toter Gott. Möchtest du ihm folgen?}
{106}{}{Huh?}
{107}{}{Die Wände haben auch ein Gedächtnis... Ich habe dich gesehen... morgen?}
{108}{}{Sind noch mehr solche Typen wie du in der Wand?}
{109}{}{Egal.}
{110}{}{Ich hätte wirklich Lust, dich zu töten. Könntest du dieses Kraftfeld öffnen?}
{111}{}{Wenn du das Kraftfeld öffnest, lasse ich dich raus.}
{112}{}{Uh, ja. Bist du das "Experiment", nach dem ich suche?}
{113}{}{Jason? Wer ist Jason?}
{114}{}{Du sagtest doch... Egal.}
{115}{}{Oh.}
{116}{}{Ja, die Wände sind durch diejenigen lebendig, die bereits gegangen sind.}
{117}{}{Was ist mit ihnen geschehen?}
{118}{}{Oh, ich muss gehen.}
{119}{}{Treffen der Seele... vereint, um den großartigen Meister zu schützen.}
{120}{}{Ah so. Wie schütze ich mich vor den Beschützern des Meisters?}
{121}{}{Was ist mit den Söldnern?}
{122}{}{Ich muss den Meister beschützen. Wie komme ich zu ihm?}
{123}{}{Ich kann jeden und alles töten. Öffne dieses Kraftfeld, dann werde ich es dir beweisen.}
{124}{}{Wiedersehen.}
{125}{}{Es gibt nur Frieden und Eintracht... der Preis... der Schmerz... man muss blind sein... annulliert.}
{126}{}{Gut, ich muss dabei sein. Wo kann ich einen dieser tollen Annullierer finden?}
{127}{}{Großartig! Was muss ich tun, um mitzumachen?}
{128}{}{Ich würde dir nur allzu gerne meine Knarre an den Kopf halten!}
{129}{}{Dafür habe ich jetzt keine Zeit. Auf Wiedersehen.}
{130}{}{Ich werde dich salben... Ich muss geben, was ich nicht geben darf.}
{131}{}{Danke.}
{132}{}{Niemand salbt mich, du verrückter Bastard!}
{133}{}{Salben? Salben womit?}
{134}{}{Nein, danke.}
{135}{}{Du kannst das Genie nicht töten... das Alles...  du... Hehf!}
{136}{}{Ja, aber ich kann ihm eine Menge Schmerzen zufügen.}
{137}{}{Ich möchte nicht töten. Ich möchte verehren.}
{138}{}{Offensichtlich. Wiedersehen.}
{139}{}{Phlegma! Nicht substantielle Entwicklung... Kommunikation, Null... Ende des Todes.}
{140}{}{Die Wände haben auch ein Gedächtnis... ich habe dich gesehen... gestern, nicht wahr?}
{141}{}{Das heißt also ja.}
{142}{}{Großartig! Was muss ich tun, um mitzumachen?}
{143}{}{Die über Gott lästern... zerfallen... der Tod wird... Erlösung... stark!}
{144}{}{Die Gedächtnisse... die Wände... vor dem Großen.}
{145}{}{Diejenigen, die bereits gegangen sind... müssen deine Reise unterbrechen.}
{146}{}{Ich muss das ändern.}
{147}{}{Ich muss meine Reise zu Ende bringen - das ist der Wille des Meisters.}
{148}{}{Wer? Hat was getan?}
{149}{}{Ja, aber ich kann ihnen eine Menge Schmerzen zufügen.}
{150}{}{Entschuldige, dass ich dich noch mal störe. Auf Wiedersehen.}
{151}{}{Ich möchte dir helfen, zu entkommen.}
{200}{}{Du siehst Moore, einen vergammelten Zeitgenossen. Er hat eine Krone auf dem Kopf.}
{201}{}{Du siehst einen vergammelten Typen.}
{202}{}{Der Asphalt soll sich rot färben. Ich werde zuschlagen!}
{203}{}{Genau.}
{204}{}{Wovon sprichst du?}
{205}{}{Ja, er wird rot von deinem Blut sein.}
{206}{}{Uh, ja. Auf Wiedersehen.}
{207}{}{Urgh!}
{208}{}{Ich werde den Motor anhalten. Der Meister hat mir die Kraft gegeben. . .}
{209}{}{OK, Hank. Ich möchte den Meister sehen. Wie komme ich zu ihm?}
{210}{}{Welcher Motor?}
{211}{}{Natürlich! Ich habe vollkommen verstanden. . .}
{212}{}{Ich würde dir gerne heimleuchten, du Vollidiot.}
{213}{}{Oh, nicht du schon wieder. Auf Wiedersehen.}
{214}{}{Nur die Starken können durchgehen, aber sie werden am Durchgehen gehindert.}
{215}{}{Öffne das Kraftfeld. Ich möchte dir zeigen, wie stark ich bin.}
{216}{}{Aber ich muss den Meister sehen!}
{217}{}{Kannst du mir zeigen wie?}
{218}{}{Gideon... was Gideon sagt, ist Gesetz.}
{219}{}{Genau.}
{300}{}{Du siehst Lucy, einen normal aussehenden weiblichen Menschen. Sie hat eine Krone auf dem Kopf.}
{301}{}{Du siehst einen weiblichen Menschen. Sie starrt auf deine Schuhe.}
{302}{}{Nirgends ist es so wie zu Hause, nirgends ist es so wie zu Hause, nirgends ist es so wie zu Hause... [sie schreitet vor und zurück]}
{303}{}{Hng!}
{304}{}{Hör auf damit!}
{305}{}{Was ist mit diesem Ort? Ist er nicht dein Zuhause?}
{306}{}{Ich stimme dir voll und ganz zu. Du hast recht... [sie hält einen Augenblick inne.] Was hast du gesagt? Oh, macht nichts.}
{307}{}{[sie blickt dich intensiv an] Dafür werde ich dich töten. Ich werde dafür sorgen, dass dein Blut rot fließt. Moment. Blut ist rot, wie soll ich es dann rot fließen lassen. Ich glaube nicht, dass ich das kann. Hmmm, darüber muss ich nachdenken. Verschwinde jetzt!}
{308}{}{Mein Zuhause ist, uh, ja. Hier. Ja, es ist hier. Dies ist mein Zuhause! [sie springt auf und ab] Ich bin so glücklich. Du kannst dir nicht vorstellen, wie glücklich mich das macht. Ich glaube, ich werde eine Weile auf die Wand einschlagen.}
{309}{}{Ich bin beschäftigt. Ich habe fast eine Lösung für die Umweltprobleme gefunden, die diese Welt ruinieren. Ich kann es aber nicht lassen, über lilafarbene Dinosaurier nachzudenken. Ist das ein Problem?}
{310}{}{Hör auf, mich zu nerven, ich denke nach. . .}
{400}{}{Du siehst Wiggum, einen absoluten Versager. Er hat eine Krone auf dem Kopf.}
{401}{}{Du siehst jemanden, der wie ein kompletter Versager aussieht.}
{402}{}{Ich bin müde.}
{403}{}{Mein Leben ist die Hölle.}
{404}{}{Ich habe das Leben satt.}
{405}{}{Die Dunkelheit kommt.}
{406}{}{Egal.}
{500}{}{Auf einem Schild an der Wand steht: "Warnung! Nicht stören!"}
