{100}{}{Funkgerät}
{101}{}{[Aus dem Funkgerät ertönt zuerst ein Rauschen und anschließend eine tiefe Stimme] Kommando an Patrouille, Kommando an Patrouille. Bitte um Statusmeldung? Over.}
{102}{}{Iik!}
## 103 - Hier ist alles in Ordnung. Uns geht's gut, äh, wie geht's euch?
{103}{}{Äh, wir haben alles unter Kontrolle. Situation normal. Eine unbedeutende Waffenfunktionsstörung... aber, äh, alles in Ordnung. Alles in Ordnung... alles wie gewohnt. Vielen Dank. Und wie geht's bei Ihnen?}
{104}{}{Kommando, eine große Gruppe bewaffneter Menschen hält uns unter Beschuß. Brauchen Verstärkung. Over.}
{105}{}{Hilfe! Unbekannte Angreifer! Große Verluste! Die Koordinaten sind: 10... Argh!}
{106}{}{Verstanden, Patrouille. Wir schicken sofort Verstärkung. Over.}
{107}{}{Wer bist du? Was hast du vor?}
{108}{}{Ich hab vor, mein verdammtes Maul zu halten.}
{109}{}{Ich, uh, oh, na egal. Ich werd' euch sowieso auslöschen.}
{110}{}{Ich bin, hmm, Fred. Ich gehör' zur Patrouille. Ich ah, oh, ich glaub', ich bin noch etwas benommen von dem Sturz.}
{111}{}{Verstanden, Patrouille. Gebt eure Koordinaten durch!}
{112}{}{224 zu 104.}
{113}{}{Vier Meilen, südsüdwest.}
{114}{}{Gamma-Sektor im Omicron-Delta-Beta.}
{115}{}{Verstanden, Patrouille. Kommando, Ende.}
{116}{}{Verstanden, Patrouille. Wir schicken Verstärkung.}
{117}{}{Ah, das erklärt alles. Wir schicken sofort Hilfe.}
{118}{}{Roger, Patrouille. Wir schicken sofort Hilfe! Haltet durch!}
{119}{}{Aus dem Funkgerät dringt nur Rauschen.}
{120}{}{Du hörst Geplapper aus dem Funkgerät. Du lauscht einen Moment und stellst fest, dass es nichts von Bedeutung ist.}
{121}{}{Am Funkgerät blinkt ein rotes Licht auf. Aus dem Lautsprecher ertönt ein hohes Kreischen.}
{122}{}{Es hört sich nach einer verschlüsselten Tonfrequenz an.}
{123}{}{Du gibst den Kommandocode ein, um die Einstellungen das Kraftfeld einzuschalten.}
# TODO: TRANSLATE
##124 - Der Funkkanal bleibt still..
{124}{}{Du hörst Geplapper aus dem Funkgerät. Du lauscht einen Moment und stellst fest, dass es nichts von Bedeutung ist.}
{125}{}{Das Funkgerät funktioniert nicht.}
{126}{}{Dieses Funkgerät funktioniert einwandfrei. Die Ursache für das Problem muss also woanders liegen.}
{127}{}{Aus dem Funkgerät ertönt nur das Rauschen von verschlüsselten Daten.}
{128}{}{[Pfeif -Quietsch-Knall] Kommando hier, Patrouille bitte fortfahren.}
{129}{}{Knack!}
{130}{}{Oh, tut mir leid, Kommando. Ich bin aus Versehen auf den Sprechknopf gekommen.}
{131}{}{Eindringlinge im Stützpunkt! Löse den Alarm aus!}
{132}{}{Roger, Patrouille, Kommando, Ende.}
{133}{}{[Du wählst die Funkfrequenz des Kanals der Sicherheitskontrolle.] [Klick!] Gib die Zugangsnummer ein. [Klick!]}
{134}{}{Hmm!}
{135}{}{Äh, 69.}
{136}{}{5566534571}
{137}{}{Zugang beendet.}
{138}{}{Der Sicherheitskanal schaltet automatisch ab.}
{139}{}{ Erfahrungspunkte für das Austricksen der Mutanten-Wachen.}
{140}{}{ Erfahrungspunkte für das Vordringen in den Militärstützpunkt, ohne dabei geschnappt worden zu sein (bis jetzt)...}
