{100}{}{Hallo, was kann ich für dich tun?}
{101}{}{Wer bist du?}
{102}{}{Bist du der Anführer dieser Gang?}
{103}{}{Schon gut.}
{104}{}{Äh ... was?}
{105}{}{Razor ist mein Name. Ich bin so was wie der Anführer.}
{106}{}{Also bist du der Anführer dieser Gang?}
{107}{}{Was weißt du über diese eingezäunte Stadt im Süden?}
# Player's name follows 108
{108}{}{Gut, dich zu treffen. Ich bin }
{109}{}{Gut, dich zu treffen, aber ich muss schon wieder gehen.}
{110}{}{Gang? Wir sind keine richtige Gang. Aber ich bin hier der Anführer.}
{111}{}{Wenn ihr keine Gang seid, was seid ihr dann?}
{112}{}{Also, auf mich wirkt ihr wie eine Gang.}
{113}{}{Tschüss.}
{114}{}{Das ist Adytum. Dort schuften Leute für einige Typen, die sich Regulatoren nennen. 'Stadt' würde ich das allerdings nicht gerade nennen ... Diese Regulatoren holen sich unsere Leute, die sie dann bis an ihr Lebensende für sich schuften lassen. Dann kommen sie wieder und holen sich neue Leute.}
{115}{}{Könnt ihr nicht hingehen und eure Leute befreien?}
{116}{}{Wieso red' ich dann eigentlich mit dir? Das sind die Typen, die ich finden muss.}
{117}{}{Ich geh' dann und versuche, soviel wie möglich über Adytum herauszufinden. Tschüss!}
{118}{}{Aha. Was hat dich in diese Ecke des Ödlands verschlagen?}
{119}{}{Ich suche nach einem Steuerchip. Weißt du vielleicht, wo ich einen finden kann?}
{120}{}{Ich bin ein Weltenbummler.}
{121}{}{Ich schau' mich nur so um. Tschüss dann!}
{122}{}{Wir versuchen nur zu überleben. Adytum hat uns in diese Lage gebracht. Sie unterwerfen uns und halten unsere Freunde und Familien wie Vieh. Wir können uns noch nicht mal verteidigen.}
{123}{}{Warum kämpft ihr nicht gegen sie?}
{124}{}{Gegen wen verteidigen?}
{125}{}{Also, die Typen von Adytum sind stärker und gewitzter als ihr. Es ist ihr gutes Recht, die Schwächeren auszubeuten.}
{126}{}{Ich seh' mich mal um und versuche, was rauszufinden. Tschüss!}
{127}{}{Wenn wir nur eine Gang wären! Dann hätten wir wenigstens anständige Waffen, mit denen wir uns verteidigen könnten.}
{128}{}{Gegen wen verteidigen?}
{129}{}{Also, mich legst du nicht aufs Kreuz. Ihr seid doch nur ein Haufen Schwachköpfe und habt bestimmt nichts Gutes im Sinn.}
{130}{}{Also, auf mich wirkt ihr wie eine Gang.}
{131}{}{Tja, ich kann euch da auch nicht helfen.}
{132}{}{Was weißt du über diese eingezäunte Stadt im Süden?}
{133}{}{Bist du der Anführer dieser Gang?}
{134}{}{Wir brauchen bessere Waffen. Die Gunrunner sind nicht weit von hier entfernt. Die haben Waffen, aber zu denen können wir nicht gehen.}
{135}{}{Warum könnt ihr dort nicht hin?}
{136}{}{Ich versuch', soviel wie möglich über die aktuelle Situation herauszufinden.}
{137}{}{Adytum wird in Wirklichkeit von den Regulatoren angeführt, nicht von Zimmerman. Sie kommen einfach und verschleppen unsere Leute nach Adytum. Wenn wir Widerstand leisten, töten sie uns einfach. Manchmal legen sie einfach ein paar von uns um, schleppen sie dann zu Zimmerman und behaupten, wir wären in ihre Stadt eingefallen oder so 'nen Quatsch. Diese Schweine haben auch Zimmermans Sohn getötet!}
{138}{}{Zimmermans Sohn? Warum sollten sie ihn umgebracht haben?}
{139}{}{Willst du damit sagen, dass ihr niemals etwas gegen Adytum unternommen habt?}
{140}{}{Zwischen uns und ihnen liegt ein Deathclaw-Nest. Wir haben noch nie mit den Gunrunnern selbst gesprochen. Die Regulatoren könnten die Deathclaw erledigen, aber aus irgendeinem Grund tun sie das nicht.}
{141}{}{Wo sind die Gunrunner?}
{142}{}{Okay. Tschüss dann!}
{143}{}{Josh hat hier mit mir ... äh ... ich ... ich mein ... mit uns gelebt. Er kannte die Wahrheit über das, was hier vorging. Die Regulatoren haben ihm gesagt, dass sie ihn sofort töten würden, wenn er Kontakt zu seinem Vater aufnähme oder nach Adytum zurückkehren würde.}
{144}{}{Sie haben ihn umgebracht? Was hat er getan?}
{145}{}{Ich mach mich auf nach Adytum, um dem nachzugehen.}
{146}{}{Eines Nachts hat er versucht, sich in die Stadt zu schleichen, um seinem Vater zu erzählen, was wirklich vorgeht. Ich hab' in jener Nacht, als ... man sie ... äh ... ihn geschnappt hat, den Funkverkehr der Regulatoren verfolgt. [Sie senkt den Blick und schüttelt langsam den Kopf.] Hier, es ist alles auf dieser Holodisk.}
{147}{}{Warum hast du die Disk nicht Joshs Vater gegeben?}
{148}{}{Keiner von uns hat die Chance, auch nur in die Nähe von Adytum zu kommen. Wir sind schon tot, bevor wir die Tore erreicht haben.}
{149}{}{Warum gebe ich ihm nicht die Disk?}
{150}{}{Warum trommelst du keine große Truppe zusammen, mit deren Hilfe ihr Adytum einnehmen könnt?}
{151}{}{Du würdest dein Leben aufs Spiel setzen, um uns zu helfen?}
{152}{}{Klar. Ich würde alles tun, um euch zu helfen.}
{153}{}{Vielleicht. Bevor ich irgend etwas unternehme, muss ich allerdings erst noch einiges abklären.}
{154}{}{Danke. Das könnte uns wirklich helfen. Viel Glück! [Sie übergibt dir die Holodisk.]}
{155}{}{Bis später!}
{156}{}{Sehr gut. Ich hoffe, du triffst die richtige Entscheidung.}
{157}{}{Tschüss!}
{158}{}{Wenn du zu den Gunrunnern willst, musst du erst nach Osten und dann nach Westen gehen. Aber sei vorsichtig, die Deathclaw ist nicht zu unterschätzen. Ich hab' eine Deathclaw gesehen, die einen Mann mit einem einzigen Schlag vernichtet hat.}
{159}{}{Ich seh' mal, was ich rausfinden kann.}
{160}{}{Tut mir leid, dass du das so siehst. Verschwinde lieber.}
{161}{}{Tschüss!}
{162}{}{Kann ich dir helfen?}
{163}{}{Bist du der Anführer dieser Gang?}
{164}{}{Schon gut.}
{165}{}{Äh ... was?}
{166}{}{Gang? Wir sind keine richtige Gang, aber ich hab' hier das Sagen.}
{167}{}{Zimmerman hat mich geschickt.}
{168}{}{Also, auf mich wirkt ihr wie eine Gang.}
{169}{}{Tschüss!}
{170}{}{[Wirkt ein wenig nervös.] Was? Hat er ...}
{171}{}{Um dich umzubringen.}
{172}{}{Um sich dafür zu rächen, dass du seinen Sohn getötet hast.}
{173}{}{WAS!!! DIESE VERFLUCHTEN DRECKSKERLE! ICH MACH' SIE ALLE, ICH SCHICK' SIE ALLE ZUR HÖLLE!!}
{174}{}{Du täuschst dich. Du bist derjenige, der zur Hölle fährt.}
{175}{}{Äh ... Wer bist du, dass du es wagst, solche Drohungen auszustoßen?}
{176}{}{Es waren die Regulatoren, sie haben Josh getötet! Ich hätte Josh niemals etwas antun können. Die Regulatoren leiten Adytum, nicht Zimmerman.}
{177}{}{Das ist ein wirklich erbärmlicher Versuch, sich rauszureden.}
{178}{}{Warum sollten die Regulatoren Zimmermans Sohn getötet haben?}
{179}{}{Josh hat hier mit mir ... äh ... ich ... ich mein ... mit uns gelebt. Er kannte die Wahrheit über das, was hier vorging. Die Regulatoren haben ihm gesagt, dass sie ihn sofort töten würden, wenn er Kontakt zu seinem Vater aufnähme oder nach Adytum zurückkehren würde. Sie haben ihn ausgelacht ... Sie waren davon überzeugt, dass er niemals zu seinem Vater gelangen könnte ...}
{180}{}{Sie haben ihn getötet? Was hat er getan?}
{181}{}{Wie läuft's mit unserem Plan?}
{182}{}{Ich versuch' immer noch, alles hinzukriegen.}
{183}{}{Äh ... was?}
{184}{}{Das klappt doch nur, wenn wir mit Gewalt drohen können. Was wir wirklich brauchen, sind Waffen von den Gunrunnern.}
{185}{}{Okay, wo sind diese Gunrunner? Warum besorgst du nicht ein paar Waffen von den Typen?}
{186}{}{Oh, okay. War nur ein Angebot. Tschüss dann!}
{187}{}{Sie befinden sich ein wenig östlich von hier, aber dazwischen liegt ein Deathclaw-Nest. Wir haben noch nie mit den Gunrunnern selbst gesprochen.}
{188}{}{Okay, gib mir die Holodisk. Ich spreche erst mit den Gunrunnern, bevor ich zu Zimmerman gehe.}
{189}{}{Hoffentlich kannst du uns helfen. Tschüss dann!}
{190}{}{Was ist los?}
{191}{}{Sie haben Zimmerman getötet!}
{192}{}{Äh ... was?}
{193}{}{Jetzt haben wir nur noch eine Chance. Wir brauchen diese Waffen von den Gunrunnern. Hilfst du uns?}
{194}{}{Ja.}
{195}{}{Nein.}
{196}{}{Danke. Und alles Gute für deine Reise.}
{197}{}{Danke für deine Hilfe. Wir werden in Adytum einfallen! Es hilft uns bestimmt, wenn wir dich an unserer Seite haben.}
{198}{}{Nein, danke. Ich hab' diese Woche schon genug erlebt ...}
{199}{}{Klar! Macht bestimmt Spaß, die Regulatoren fertigzumachen.}
{200}{}{Äh ... was?}
{201}{}{Ich möchte zuerst mit Zimmerman sprechen.}
{202}{}{Gut. Noch mal danke für deine Hilfe. Tschüss dann!}
{203}{}{Großartig! Gehen wir!}
{204}{}{Ich glaub' zwar nicht, dass das eine so tolle Idee ist, aber du kannst es gerne versuchen.}
{205}{}{Du Schwein! Jetzt, wo die Gunrunner weg sind, haben wir keine Chance mehr, Waffen zu kriegen. Verschwinde! Du bist hier nicht mehr willkommen.}
{206}{}{Tut mir leid.}
{207}{}{Ich will kein Wort mehr hören!}
{208}{}{Ich rede mit Zimmerman. Wenn ich ihm diese Holodisk gebe, geht alles in Ordnung.}
{209}{}{Weißt du was? Ich mach' dich kalt.}
{210}{}{Äh ... was?}
{211}{}{Komm schon, das wird dein Begräbnis. Ohne diese Waffen haben wir keine Chance mehr.}
{212}{}{Mach dich vom Acker!}
{213}{}{Du bist hier nicht mehr willkommen.}
{214}{}{Verschwinde!}
{215}{}{Danke.}
{216}{}{Meine Leute sind frei.}
{217}{}{Hallo!}
{218}{}{Was ist denn mit dir passiert? Hast du eine Kugel in den Kopf bekommen?}
{219}{}{Häh?}
{220}{}{Du siehst Razor, die Anführerin der Blades.}
{221}{}{Du siehst eine wunderschöne Frau mit traurigen Augen.}
{222}{}{Geh bitte. Ich bin beschäftigt.}
{223}{}{Danke für deine Hilfe mit den Regulatoren. Bleib hier, solange du willst. Du kannst mal bei Miles und Smitty reinschauen. Die könnten dir eventuell bei deinen weiteren Reisen behilflich sein.}
{224}{}{Hallo, kann ich dir helfen?}
{225}{}{Wer bist du?}
{226}{}{Hutzpah!}
{227}{}{Ich heiße Razor. Ich bin die Anführerin der Leute, die du hier siehst. Wir sind hier vollkommen den Launen der Regulatoren von Adytum ausgeliefert.}
{228}{}{Regulatoren? Um die hab' ich mich gekümmert. Gibt es da ein Problem?}
{229}{}{Du hast sie alle getötet? Ein Problem? Ganz und gar nicht. Dann können meine Leute jetzt Seite an Seite mit den Menschen von Adytum ein freies Leben führen.}
{230}{}{Ich fasse es nicht. Du hast es geschafft, alle zu töten? Die Blades und ich danken dir!}
{231}{}{Ich hab' gehört, dass die Regulatoren Adytum noch immer kontrollieren. Konntest du nicht alle töten?}
{232}{}{Keine Panik, ich kümmer' mich darum.}
{233}{}{Ich glaub' nicht, dass mir das gelingen wird.}
{234}{}{Wir würden dir folgen, aber wenn wir ohne Waffen ankommen, bringen uns die Regulatoren alle um. Es gibt vielleicht eine andere Möglichkeit. [Razor denkt einen Augenblick nach.] Wenn du die Gunrunner dazu bewegen könntest, uns mit Waffen zu beliefern, könnten ein paar von uns mit dir gehen.}
{235}{}{Klingt gut. Ich geh' und red' mit ihnen.}
{236}{}{Ich versuch' noch mal, die Regulatoren allein fertig zu machen.}
{237}{}{Hallo, du wieder! Ich hab' gehört, dass du die Regulatoren fertig gemacht hast. Ich möchte dir dafür danken. Jetzt können meine Leute mit den Bewohnern von Adytum in Frieden zusammenleben.}
{238}{}{Ich kümmer' mich allein um die Regulatoren.}
{239}{}{Wirklich? Okay, komm hierher zurück, wenn du Unterstützung brauchst oder wenn du die Sache erledigt hast.}

# to male player
{240}{}{Du Hurensohn!}
# to female player
{241}{}{Du Schlampe!}
