{100}{}{Du siehst Mitch, den Manager des All-In-One-Store.}
{101}{}{Suchst du was?}
{102}{}{Was suchst du heute?}
{103}{}{Kann ich dir irgendwie helfen?}
{104}{}{Ich hab' alles da, also was brauchst du?}
{105}{}{Brauchst du Vorräte?}
{106}{}{Möchtest du was kaufen?}
{107}{}{Was darf es sein?}
{108}{}{Hast du was Gutes zum Handeln?}
{109}{}{Was hast du?}
{110}{}{Mach' mir ein Angebot.}
{111}{}{Ich schlag' dir einen Deal vor.}
{112}{}{Komm' wieder.}
{113}{}{Danke und bis bald.}
{114}{}{Wiedersehen.}
{115}{}{Pass' auf deine Moneten auf.}
{116}{}{Lass' es mich wissen, wenn du was brauchst.}
{117}{}{Pass' auf dich auf.}
{118}{}{Finde was Passendes und bring' es zurück.}
{119}{}{Fühl' dich wie zu Hause.}
{120}{}{Ich hab' nur gute Waren.}
{121}{}{Was?}
{122}{}{Mitch hat hier die Oberhand, nicht ich.}
{123}{}{Wenn ich frei hab', bin ich im Falcon!}
{124}{}{Vermeide jeden Streit.}
{125}{}{Pass' auf!}
{126}{}{Beobachtest du mich?}
{127}{}{Lass' dich bloß nicht beim Stehlen erwischen.}
{128}{}{Willkommen im All-In-One Store.}
{129}{}{Jetzt kauf' schon was!}
{130}{}{Suchst du Streit?}
{131}{}{Wir haben geschlossen.}
{132}{}{Wir haben geschlossen.}
