{100}{}{Du siehst einen Betrunkenen.}
{101}{}{Du siehst einen Kunden.}
{102}{}{Du siehst eine wunderschöne Lady.}
{103}{}{Du siehst einen merkwürdig aussehenden Mann.}
{104}{}{Du siehst einen Spieler.}
{105}{}{Du siehst eine Frau. Sie scheint beschäftigt zu sein.}
{106}{}{Du siehst eine Frau.}
{107}{}{Du siehst einen Mann.}
{108}{}{Du siehst einen sehr aufgeregten Spieler.}
{109}{}{Du siehst einen Söldner.}
{110}{}{Lass mich mit meinen düsteren Gedanken allein.}
{111}{}{Du bist mein bestester Freund.}
{112}{}{Warum bist du... (hick) wo bin ich?}
{113}{}{Wer bist du?}
{114}{}{Kennen wir uns?}
{115}{}{Mir ist ein bisschen übel.}
{116}{}{Die Getränke zahle ich. Dich da meine ich.}
{117}{}{Warum gibt es dich denn doppelt?}
{118}{}{Steh still, Junge!}
{119}{}{Steh still, Mädel!}
{120}{}{Hau ab, Skag!}
{121}{}{Du hast das Klassenziel leider nicht erreicht.}
{122}{}{Geh weg, du verhext mich!}
{123}{}{Stör mich nicht - ich muss mich konzentrieren.}
{124}{}{Ich werd dieses verdammte Spiel gewinnen!}
{125}{}{Bist du gut darin?}
{126}{}{Hast du das gesehen? Das war unglaublich!}
{127}{}{Ich glaub, dass sie mogeln.}
{128}{}{Also, das sind gute Chancen.}
{129}{}{Das ist sicher.}
{130}{}{Was? Wie kann ich verloren haben?}
{131}{}{Dieser Tisch ist verhext!}
{132}{}{Ich hab zu tun.}
{133}{}{Ich kann nicht. Du siehst doch, dass ich hier am Spielen bin!}
{134}{}{Schließ 'ne Wette ab oder verschwinde.}
{135}{}{Verschwinde oder ich rufe die Wachen.}
{136}{}{Sieh dich vor, ich bin ein enger Freund von Deputy Fry.}
{137}{}{Hast du was dagegen?}
{138}{}{Keine Peepshow!}
{139}{}{Keine Gruppen.}
{140}{}{Ich hab keine Lust mehr.}
{141}{}{Hau ab, du Traumtänzer!}
{142}{}{Mach dich vom Acker!}
{143}{}{Was zum Teufel treibst du hier?}
{144}{}{Benimm dich!}
{145}{}{Ich ruf die Bullen!}
{146}{}{Daran solltest du noch nicht einmal denken!}
{147}{}{Verschwinde!}
{148}{}{Hau ab!}
{149}{}{Was glotzt du so?}
{150}{}{Hast du was dagegen?}
{151}{}{Verschwinde aus unserem Zimmer!}
{152}{}{Mach dich vom Acker!}
{153}{}{Gehörst du zur Musikband?}
{154}{}{Hau ab, Perversling!}
{155}{}{Was willst du?}
{156}{}{Hau ab, oder ich werd böse.}
{157}{}{Such dir deine eigene.}
{158}{}{Sie gehört mir.}
{159}{}{Verdammt!}
{160}{}{Mogelst du?}
{161}{}{Das gehört eigentlich mir.}
{162}{}{Fast!}
{163}{}{Knapp daneben.}
{164}{}{Wie lauten die Spielregeln schnell wieder?}
{165}{}{Ich war sonst immer so gut darin.}
{166}{}{Besten Dank auch.}
{167}{}{Ich fasse es nicht!}
{168}{}{Genau das hatte ich vor.}
{169}{}{Bitte jetzt wetten.}
{170}{}{Hände weg, Sir.}
{171}{}{Sieger!}
{172}{}{Tut mir leid, Leute, vielleicht beim nächsten Mal.}
{173}{}{Noch ein Sieger!}
{174}{}{Hände weg!}
{175}{}{Sie sind dran, Sir.}
{176}{}{Ich bedaure, aber das ist eine ungültige Wette.}
{177}{}{Das war's.}
{178}{}{Sonst noch wer?}
