# This file is new for Fallout Fixt.
#
{100}{}{Du siehst die Holo-Disk, die Razor dir gegeben hat.}
#
{101}{}{Der PIP-Boy zeigt an: Datei im System gefunden. Download abgebrochen}
{102}{}{Der PIP-Boy zeigt an: Daten werden von der CD geladen.}
#
{103}{}{Diese Disk enthält Informationen über das wahre Schicksal von Jon Zimmermans Sohn.}
{104}{}{Du siehst: Regulatorenübertragung.}
