
#
# Coastal encounter messages
#

{100}{}{Du siehst mehrere merkwürdig schwimmende Kreaturen...}
{101}{}{Du siehst einen kleine Schar Ratten, die mit großer Geschwindigkeit näherkommen.}
{102}{}{Du siehst eine Gruppe von Bauern, die von Gangstern angegriffen werden!}
{103}{}{Du siehst einige Leute, die beim Fischen sind.}
{104}{}{Du siehst ganz in der Nähe eine grausige Leiche, die bereits angeknabbert ist.}
{105}{}{Du findest einige Wasserlachen..}
{106}{}{Du hast schrecklichen Durst und trinkst etwas Wasser... Es schmeckt nicht besonders gut.}
{107}{}{Das Wasser sieht hoch radioaktiv und faulig aus.}
{108}{}{Ahhh..}
{109}{}{Arrgg..}
{110}{}{Igitt!}
