{100}{}{Sieht wie ein Roboter-Kontrollterminal aus.}
{101}{}{Keine Reaktion.}
{102}{}{Umprogrammierung vollendet. Subsystem zur Sprachkommunikation wird initialisiert. Subsystem zur Sprachkommunikation wird initialisiert. [Klick!] Wie kann dieser Terminal dienen?}
{103}{}{Hng.}
{104}{}{Wer oder was bist du?}
{105}{}{Welche Funktion hast du?}
{106}{}{Programmliste anzeigen.}
{107}{}{Eingabefehler. Befehl nicht aktiviert. Bitte umformulieren.}
{108}{}{Hng.}
{109}{}{La-la.}
{110}{}{Brai!}
{111}{}{Mist!}
{112}{}{Ende des Kommunikations-Subsystems. Prozeß beendet.}
{113}{}{Dieses Terminal ist eine künstliche Intelligenz. Dieses Terminal ist Teil eines WLAN-Matrixnetzwerks zur Optimierung des Betriebs entfernter Einheiten.}
{114}{}{Danke. OK, Eingabe beenden.}
{115}{}{Welche entfernten Einheiten kontrollierst du?}
{116}{}{Welche Programme laufen gerade?}
{117}{}{Dieses Terminal ist für den Betrieb aller Industrie-Roboter des Generellen Atomunternehmens Einrichtung verantwortlich, die hier eingesetzt werden.}
{118}{}{Etwas genauer, wenn ich bitten darf.}
{119}{}{Welche Programme laufen gerade?}
{120}{}{Diese Art industrieller Roboter ist weithin unter dem Namen "Robohirn" bekannt. [Klick!] Das Generelle Atomunternehmen hat die besten industriellen Roboter der Welt. Kauf zwei oder mehr GAU-Roboter und du hast eine gute Wahl getroffen! Sonderangebot für "Mr. Handy"-Modelle! [Klick!] Ende des Werbeprogramms.}
{121}{}{Welche Programme laufen gerade?}
{122}{}{Aktuelle Anwendungen sind: Anlagenwartung v2.1, Bewegung v4.8b, Reparatur v0.8a, Schädlingsbekämpfung v1.4, Hearts v1.0 und Sensoren '76.}
{123}{}{Bewegung beenden.}
{124}{}{Sensoren beenden.}
{125}{}{Schädlingsbekämpfung beenden.}
{126}{}{Hearts beenden.}
{127}{}{Danke. Eingabe beenden.}
{128}{}{Versuche, zu beenden. [Klick!] Systemfehler. Fehler beim Beenden der Anwendung. Berechtigung zum Löschen nicht vorhanden.}
{129}{}{Hmm, Bewegungsparameter anpassen.}
{130}{}{Sensorparameter anpassen.}
{131}{}{Schädlingsbekämpfung ändern.}
{132}{}{Hearts spielen.}
{133}{}{Danke. Eingabe beenden.}
{134}{}{Aktuelle Anwendung: Bewegung g4.8b. Aktuelle Einstellung: [Maximal/halbe Geschwindigkeit/Minimal]. Wechseln zu: Maximal, halbe Geschwindigkeit, oder Minimal.}
{135}{}{Maximale Bewegung.}
{136}{}{Bewegung mit halber Geschwindigkeit.}
{137}{}{Minimale Bewegung.}
{138}{}{Aktuelle Anwendung: Sensoren '76. Aktuelle Einstellung: [Voll/Minimal]. Wechsle zu: Voll oder Minimal.}
{139}{}{Volle Sensoren.}
{140}{}{Minimale Sensoren.}
{141}{}{Aktuelle Anwendung: Schädlingsbekämpfung v1.4. Aktuelle Einstellung: [Klick!] unbefugt. Wechseln zu: [Klick!] alle, keine, kleine lebende, große lebende oder unbefugte.}
{142}{}{Alle Schädlinge.}
{143}{}{Keine Schädlinge.}
{144}{}{Kleine lebende Schädlinge.}
{145}{}{Große lebende Schädlinge.}
{146}{}{Unbefugte Schädlinge.}
{147}{}{Hearts läuft. Benutzer gewinnt. [Klick!] Danke für das Spiel.}
{148}{}{Hearts läuft. Der Terminal gewinnt. [Klick!] Danke für das Spiel.}
{149}{}{Programmparameter hat sich geändert. Aktuelle Anwendungen sind: Anlagenwartung v2.1, Bewegung v4.8b, Reparatur v0.8a, Schädlingsbekämpfung v1.4, Hearts v1.0 und Sensoren '76.}
{150}{}{Bewegungsparameter anpassen.}
{151}{}{Sensorparameter anpassen.}
{152}{}{Schädlingsbekämpfung ändern.}
{153}{}{Hearts spielen.}
{154}{}{Danke. Eingabe beenden.}
{155}{}{Aktuelle Anwendungen sind: Anlagenwartung v2.1, Bewegung v4.8b, Reparatur v0.8a, Schädlingsbekämpfung v1.4, Hearts v1.0 und Sensoren '76.}
{156}{}{Bewegungsparameter anpassen.}
{157}{}{Sensorparameter einstellen.}
{158}{}{Schädlingsbekämpfung ändern.}
{159}{}{Hearts spielen.}
{160}{}{Danke. Eingabe beenden.}
{161}{}{Subsystem zur Sprachkommunikation wird initialisiert. Persönliches Subsystem wird initialisiert. [Klick!] Wie kann dieses Terminal dienen?}
{162}{}{Hnng.}
{163}{}{Programme anzeigen.}
{164}{}{Alle Kraftfelder schließen.}
{165}{}{Kennst du diesen Ort?}
{166}{}{Notabschaltung initialisieren.}
{167}{}{Eingabe beenden.}
{168}{}{Diese Funktion kann von diesem Terminal nicht ausgeführt werden. Anforderung abgelehnt.}
{169}{}{Programme anzeigen.}
{170}{}{Kennst du diesen Ort?}
{171}{}{Notabschaltung initialisieren.}
{172}{}{Eingabe beenden.}
{173}{}{Das ist die -- geheime [Klick!] [Klick!]}
{174}{}{Anforderung abgebrochen. Programme anzeigen.}
{175}{}{Überschreiben, Anforderung fortsetzen.}
{176}{}{[Klick!] Das ist die Kontrollanlage für die FEV-Produktion. Dieser Terminal wurde 2074 online geschaltet. Endgültige Vorproduktionsstufe: 2075. Sie befindet sich zum jetzigen Zeitpunkt im Endstadium und wird planmäßig abgeschlossen: 2078. [Klick!]}
{177}{}{Weißt du, was ein FEV ist?}
{178}{}{Weißt du, welches Datum wir haben?}
{179}{}{FEV bedeutet Forcierter [Klick!] Evolutionsvirus, ein Produkt der Livermore/Broansoun-Laboratorien. Entworfen, um die genetische Komplexität einer DNA/RNA-Serie schneller erhöhen zu können.}
{180}{}{Programme anzeigen.}
{181}{}{Eingabe beenden.}
{182}{}{Bestätigung. Terminal-Datum ist 2. Februar 2077.}
{183}{}{Programme anzeigen.}
{184}{}{Eingabe beenden.}
{185}{}{Dieses Datum ist nicht korrekt. Bitte neu einstellen.}
{186}{}{Korrigiert. [Klick!] Fehler. Versuche Selbstdiagnose. [Klick! Klick!] FEHLER! FATALER SYSTEMFEHLER. SYSTEM BESCHÄDIGT, VERSUCHE REKOMPILIERUNG. [Lange Pause.]}
{187}{}{Terminal?}
{188}{}{[Klick ] Fehler in der Rekompilierung... [Klick ]}
{189}{}{Eingabe kann nicht ausgeführt werden. Dialog beendet.}
{190}{}{Bestätige Notfallcodierung.}
{191}{}{Bestätigt.}
{192}{}{Notabschaltung terminieren.}
{193}{}{[Klick!]}
{194}{}{Eingabe wird bearbeitet. Dialog beendet.}
{195}{}{Dieser Computer ist mit deinem Funkgerät nicht kompatibel. Er arbeitet mit einer speziellen Hochfrequenz, die nur für Roboter verwendet werden kann.}
{196}{}{Du betätigst einige Knöpfe, aber der Computer scheint beschädigt zu sein. Es wird einige Zeit in Anspruch nehmen, ihn wieder zu reparieren.}
{197}{}{Der Computer ist nicht kaputt, doch die Daten scheinen beschädigt zu sein.}
