{100}{}{[Klick] Frieden mit dir. [Biep!]}
{101}{}{Vernichten! Vernichten!}
{102}{}{Tötet den Menschen!}
{103}{}{Tötet den Eindringling!}
{104}{}{[Brrzk!] Tod dem Fleisch!}
{105}{}{[Briep!] Kein Frieden. Kein Frieden.}
