{100}{}{Du siehst Sammael, einen der Scavenger von Adytum.}
{101}{}{Du siehst einen Mann in dunkelblauen Klamotten.}
{102}{}{He, ich kann gar nicht fassen, dass wir uns getroffen haben. Wer bist du?}
{103}{}{Ich bin }
{104}{}{.}
{105}{}{Wer fragt mich das?}
{106}{}{Eruh?}
{107}{}{Sehr erfreut. Man nennt mich Sammael.}
{108}{}{Was machst du hier?}
{109}{}{War schön, mit dir zu reden.}
{110}{}{Unwichtig. Vergiss es einfach!}
{111}{}{Ich bin ein Scavenger. Meine Aufgabe ist es, den Boneyard nach nützlichen Sachen und nach Informationen abzusuchen. Gefährlicher Job!}
{112}{}{Warum gefährlich?}
{113}{}{Wie umgehst du die Deathclaws?}
{114}{}{Hast du auch eines der anderen Gebiete ausgekundschaftet?}
{115}{}{Danke. Tschüss dann!}
{116}{}{Bis später - falls wir uns noch mal sehen. Ha!}
{117}{}{Naja, die Deathclaws sind da draußen, und hier in Adytum sind die Regulatoren. Beides nicht gerade die versöhnlichsten Typen.}
{118}{}{Wie umgehst du die Deathclaws?}
{119}{}{Hast du auch eines der anderen Gebiete ausgekundschaftet?}
{120}{}{Danke. Tschüss dann!}
{121}{}{Wir arbeiten nur nachts, und wir leisten echt gute Arbeit. Aber ich muss zugeben, dass nicht immer alle wieder zurückkommen. Letzte Woche hab' ich einen Kerl ausgesandt, der nach ein paar Teilen für Miles suchen sollte. Seitdem ist er verschwunden. Das letzte, was ich von ihm gehört habe, ist, dass er die Teile gefunden hat und sich auf dem Rückweg befindet.}
{122}{}{Ich hab' ein bisschen was ausgekundschaftet. Über wen willst du was wissen?}
{123}{}{Über die Blades.}
{124}{}{Über die Deathclaws.}
{125}{}{Über die Gunrunner.}
{126}{}{Über die Followers of the Apocalypse.}
{127}{}{Über die Children of the Cathedral.}
{128}{}{Über niemanden, danke.}
{129}{}{Die Blades sind eher eine erbärmliche Erscheinung. Irgendwie kommen sie aber doch zurecht, und einige von ihnen enden hier in Adytum, wenn sie tun, was die Regulatoren wollen.}
{130}{}{Naja, wenn du sie noch nie gesehen hast ... Sie sind das Böse in Person und machen nichts lieber, als einem armen Scavenger das Herz aus dem Leib zu reißen.}
{131}{}{Mir ist zu Ohren gekommen, dass hier irgendwo östlich der Blades ein Nest von denen sein soll, aber ich hab's noch nicht selbst gesehen.}
{132}{}{Die Gunrunner sind kürzlich in eine große Fabrik im Nordosten gezogen. Ich kann dir leider nicht viel erzählen, weil diese Fabrik von einem Wassergraben umgeben ist, der mit radioaktivem Schlamm gefüllt ist. Außerdem muss man an den Deathclaws vorbei, um dorthin zu kommen.}
{133}{}{Die Followers predigen Frieden und Toleranz. Nette Idee, aber leider nicht zu verwirklichen. Sie leben in einer großen Bibliothek nordwestlich von uns.}
{134}{}{Die Children of the Cathedral leben in einer großen Kirche ein Stück südlich von hier. Dort gehen die merkwürdigsten Sachen vor. Es gehen Kreaturen ein und aus, die absolut nichts Menschliches an sich haben.}
{135}{}{Und wenn man den Geschichten Glauben schenkt, dann wurde die Kirche auf einer alten Vault errichtet, in der die Vorfahren Adytums lebten.}
{136}{}{Hallo! Da treffen wir uns also doch wieder! Was gibt's Neues?}
{137}{}{Was machst du noch mal?}
{138}{}{Nichts. Danke.}
{139}{}{Oh, ich verstehe. Okay, tschüss dann!}

# TODO: TRANSLATE
# Added by Sduibek for Fallout Fixt:

{140}{}{Miles sagte, ich solle mit dir über Teile für die Hydroponik-Farmen reden. Weißt du etwas darüber?}
{141}{}{Ah, in der Tat tue ich das. Erst letzte Woche hatte ich einen meiner Scrapper in den Norden geschickt, um nach Teilen zu suchen, allerdings haben wir seitdem nichts mehr von ihm gehört. Die letzte Übetragung die ich von ihm bekam, war, dass er entsprechende Teile gefunden hatte und er auf dem Rückweg war. Ich hatte noch keine Zeit es persönlich zu überprüfen, aber bis jetzt ist er nicht aufgetaucht, und ich möchte auch niemand anderes an der Suche nach ihm verlieren.}
{142}{}{So ein Pech. Tut mir leid das zu hören, aber danke für die Info. Tschüss.}
{143}{}{Wenn ich an Informationen über ihn komme, gibt es vielleicht eine Art Finderlohn?}
{144}{}{Prima, Danke. Ich werde im Norden nach den Teilen suchen, und dich wissen lassen, falls ich etwas über deinen Scrapper herausfinde.}
{145}{}{Jederzeit, Tschüss.}
{146}{}{Würdest du das tun? Das wäre großartig. Wie gesagt, hier war in letzter Zeit viel los, und wir können es uns nicht leisten noch mehr Leute zu verlieren.}
{147}{}{[lacht] Nicht wirklich. Wenn ich die Deckel dafür hätte, hätte ich bereits jemand anderes geschickt ihn aufzuspüren. [denkt einen Moment nach] Ich mag deine Einstellung. Ich sag dir was: Wenn du ihn finden kannst, werde ich sehen was ich für dich tun kann.}
{148}{}{Die gute Nachricht ist, ich habe ihn gefunden. Die schlechte, er ist ziemlich tot.}
{149}{}{Tut mir leid dir das sagen zu müssen, aber dein Scapper wurde von den Deathclaws am Lagerhaus getötet.}
{150}{}{Verdammt! [seufzt] Das hatte ich mir schon gedacht, trotzdem danke.}
{151}{}{Oh, bevor ich's vergesse, hier ist deine Belohnung. [Er gibt dir etwas, dass wie eine handgroße Mini-Kettensäge aussieht.] Früher gab's hier mal eine Gang die diese benutzt hat. Du dir keinen Zwang an, und töte ein paar der Bastard-Deathclaws damit. Wir seh'n uns .}
{152}{}{Nimm dies für deine Mühen, es ist das Mindeste was ich tun kann. [Er überreicht dir 200 Deckel]}
