{100}{}{Die Sicherheitstür ist verschlossen.}
{101}{}{Die Sicherheitstür ist nicht verschlossen.}
{102}{}{Es gelingt dir, die Sicherheitstür zu öffnen.}
{103}{}{Es gelingt dir nicht, die Sicherheitstür zu öffnen.}
{104}{}{Du bringst es fertig, den passiven Alarm an der Tür auszulösen,
 dadurch wird das elektronische Schloß geschlossen. Gute Arbeit, Chromo.}
{105}{}{ Erfahrungspunkte für das Öffnen des Schlosses.}
