{100}{}{Du siehst Set, den Anführer von Necropolis.}
{101}{Set00}{Hoffentlich hast du einen guten Grund, mir im Weg zu stehen. Sagt dir 'Der Nächste bitte' was, Normie?}
{102}{}{Einen sehr guten sogar! Offenbar hab' ich den Anführer gefunden.}
{103}{}{Wau! Was ist denn mit deinem Gesicht passiert?}
{104}{}{Wau! Du bist ganz schön helle für einen Ghul!}
{105}{}{Häh?}
{106}{Set01}{Easy! Ich bin Set, ich bin der Boß. Kapiert?}
{107}{}{Soweit ich weiß, bist du nur ein zweitrangiger Günstling.}
{108}{}{Kapiert.}
{109}{}{Sonst noch was?}
{110}{Set01a}{Gut.}
{111}{}{Was kann ich für dich tun?}
{112}{Set02}{Was soll das? Schleimerei? Hör zu, ich pfeif' auf Normalos. Mit heißer Luft verdienst du dir den Chefsessel bestimmt nicht.}
{113}{}{Wenn ich fertig bin, wird aus vielen Löchern heiße Luft kommen.}
{114}{}{Entschuldigung, ich wollte nur Eindruck schinden.}
{115}{}{Hatte nichts zu bedeuten.}
{116}{Set03}{Ahahh ... Ich fress' dich mit Haut und Haar und halt dann einen Mittagsschlaf. Miammiammiam, schnarch, schnarch ...}
{117}{Set04}{Stunde der Wahrheit? Ich press' dich aus wie 'ne Zitrone!}
{118}{}{Was auch immer in deinem Halfter steckt, es sollte größer sein als dein Maul ... so unwahrscheinlich das auch ist.}
{119}{}{Jetzt paß mal gut auf ...}
{120}{}{Ähm?}
{121}{Set05}{Hmm, du bist gar nicht so dumm ... Hähähä, ich hab' Spielgefährten für dich, Normie! Ärger die Mutanten an der Wasserstelle. Ja, ja, mach das ... ja?}
{122}{}{Oh, okay.}
{123}{}{Ähm.}
{124}{Set06}{Sehr gut. Zeig's den Mutanten ein letztes Mal, dann komm zurück. Hmm ... Wenn ich den Ghuls sage, sie sollen dir nichts tun, riechen die Muties Lunte. Na gut, ich tu dir den Gefallen, ich halt's Maul. Kapiert?}
{125}{}{Kapiert.}
{126}{}{Was ist mit den Ghuls?}
{127}{}{Äh .. okay!}
{128}{}{Häh?}
{129}{Set07}{Meide meine Ghuls, wenn dir dein Leben lieb ist. Ein Ghul, der 'nen Normalo nicht aufhalten kann, hat 'nen Grabstein verdient. Versuch mal dein Glück!}
{130}{Set08}{Du stiehlst meine Zeit! Auch du wirst in Frieden ruhen!}
{131}{Set09}{Du raffst doch gar nicht, wen du vor dir hast.}
{132}{}{Einen zweitrangigen Günstling. Ich kenne deinen Boß. Ist gar nicht zufrieden.}
{133}{}{Du auch nicht.}
{134}{}{Tut mir leid, aber ich hab' einen etwas seltsamen Humor.}
{135}{Set10}{Du arbeitest für ihn? Wohl sein Spitzel, was? Willst mir die Haut abziehen? Auf dich wartet ein Grabstein!}
{136}{}{He, versteh das nicht falsch. So einer bin ich nicht. Ich will dir helfen.}
{137}{}{Versuch's doch, Spaghetti-Gesicht!}
{138}{Set10a}{Klang ganz anders.}
{139}{}{Ich verstehe. Er ist auch mein Problem, also sprich mit mir.}
{140}{Set11}{Necropolis war meins. Nicht gerade das Tollste, aber ... echt cool. Dann ließ sich der Meister blicken. Er hätte aus mir Hackfleisch machen können, doch es war leichter, ein paar Mutanten hierzulassen ... als Wachen.}
{141}{}{Was kann ich für dich tun, und was ist deine Gegenleistung?}
{142}{}{Ist nicht ganz mein Ding. Ich geh' dann lieber.}
{143}{Set12}{Die Mutanten an der Wasserstelle sollen unter der Erde schlafen. Das törnt mich echt an. Mach sie kalt, und du machst mich heiß! Kriegst auch Infos!}
{144}{}{Einverstanden.}
{145}{}{Hört sich nach Ärger an. Ich geh' dann lieber.}
{146}{Set13}{Du suchst 'nen Job, Kumpel? Zeig mir deinen Mut und zeig den Mutanten am Wasser deine Muskeln. Gib ihnen Saures, dann bist du süß!}
{147}{}{Ich bin dabei.}
{148}{}{Auf gar keinen Fall, Spaghetti-Gesicht!}
{149}{Set14}{Nein. Noch Fragen?}
{150}{}{Ahh ... Was kann ich für dich tun?}
{151}{}{Ja. Erschreckst du dich eigentlich, wenn du in den Spiegel guckst?}
{152}{Set15}{Ich krieg' gleich 'nen Lachkrampf. Noch mal, und wir machen Saft aus dir. Klar?}
{153}{}{Klar.}
{154}{}{Ich weiß noch immer nicht ...}
{155}{}{Paß lieber auf, daß du dich nicht totlachst.}
{156}{Set16}{Ich heiße Set. Du heißt 'Grab-ist-kühl'. Nimm an, und ich tauf dich um. Verstanden?}
{157}{}{Klar! Ich freu' mich schon auf die Taufe!}
{158}{}{Nee, laß mal. Das kannst du mit Idioten machen.}
{159}{}{Ahä.}
{160}{}{Ähm.}
{161}{Set17}{Spazier zur Wasserstelle und mach die Mutanten richtig naß. Tu's, und du darfst leben. Tu's nicht, und du stirbst.}
{162}{}{Du scheinst Angst vor diesen Kerlen zu haben. Willst du darüber reden?}
{163}{}{Okay, einverstanden.}
{164}{}{Du siehst wirklich komisch aus, und du redest komisch.}
{165}{Set18}{Sehr gut! Hast dir ein Lob verdient. Garret führt dich zu deiner Belohnung. Ich hab' zu tun.}
{166}{}{Okay, danke.}
{167}{}{Das ist alles? Und jetzt soll ich einfach gehen?}
{168}{}{Mami?}
{169}{Set19}{Wart mit dem Jammern! Gefällt dir bestimmt. Enttäusch mich nicht, jetzt ... da mein Herz lacht.}
{170}{}{Entschuldige, aber ich mach' mir etwas Sorgen hier.}
{171}{}{Alles klar, kein Problem.}
{172}{}{He, ich geb' mich nicht mit Resten zufrieden.}
{173}{Set20}{Ahh ... Ja, ja. Geh mit Garret und zeig ihm deine Goldzähne. Keine Panik, ich halte mein Wort. Der Meister denkt und lenkt.}
{174}{}{Der Meister?}
{175}{}{Okay, danke.}
{176}{Set21}{Paß auf dich auf, sonst hast du sein Messer und er deine Haut. Die Mutanten, die er rief, verdunkeln das südliche Ödland.}
{177}{}{Wenn der Meister so stark ist, wer kann es dann mit ihm aufnehmen?}
{178}{}{Er jagt mir keine Angst ein.}
{179}{Set21a}{Sollte er aber.}
{180}{Set22}{Children of the Cathedral, Kinder des Hubs, selbst wir Ghuls ... keiner entkommt seinem Schatten. Doch unser Licht wird hell erstrahlen. Oh ja!}
{181}{}{Viel Glück!}
{182}{Set23}{Folge Garret und hau ab!}
{183}{}{Okay.}
{184}{}{Verpiß dich!}
{185}{Set24}{Du landest bald im Biomüll! Hau ab, ohne Belohnung, oder wir machen aus dir Jägerschnitzel!}
{186}{}{Wenn das so ist ...}
{187}{}{Verpiß dich!}
{188}{Set25}{Ich hab' noch nicht gehört, daß den Mutanten das Licht ausgeknipst wurde. Das ist für mich wichtig. Sag mir, daß das Problem beerdigt ist!}
{189}{}{Oh, ja, alles in Ordnung. Ich hab' micht drum gekümmert. Ehrlich.}
{190}{}{Nee, ich arbeite noch dran.}
{191}{}{Ähm.}
{192}{Set26}{Ahhh, vorzüglich! Garret führt dich zu deiner Belohnung.}
{193}{Set27}{Du raubst mir den letzten Nerv mit deinen Lügen. Los, verschwinde, bevor ... Stirb! Stirb! So stirb doch!}
{194}{Set28}{Geh jetzt! Zeig's den Mutanten, dann komm zurück! Vorher nicht!}
{195}{Set29}{Erwischt worden, heh? Ich hab's dir doch gesagt. Jetzt zahlst du! Keine Tricks!}
{196}{Set30}{Ich bin Set. Warum muß ich deinen Anblick ertragen?}
{197}{}{Ich bin der Bote des Todes. Auf die Knie und flehe um Gnade!}
{198}{}{Ich bin der Bote des Todes. Auf die Knie und flehe um Gnade ... Oder gib mir ein Sandwich, ich hab' riesigen Hunger.}
{199}{}{Ich will den Boß sprechen. Bist du das?}
{200}{}{Wau! Schwerer Fall von Akne!}
{201}{}{Äh ... weiß nicht.}
{202}{Set31}{Hm! Normalos! Würde ich dir die Tür öffnen, wenn ich Angst vor dir hätte?}
{203}{}{Ich habe Ghuls getötet. Ich habe Mutanten getötet. Ich habe Dinge getötet, die deine Vorstellungskraft übersteigen. Niemand stellt sich mir in den Weg.}
{204}{}{Wie wär's mit einer Schönheitsoperation? Dein Gesicht würde sich gut an meiner Wand machen!}
{205}{Set32}{Du hast die an der Wasserstelle erledigt. Imponiert mir! Dafür sag' ich dir was ... Dann gehen wir getrennte Wege.}
{206}{}{Warum gehen wir nicht gleich 'getrennte Wege'?}
{207}{}{Von mir aus.}
{208}{Set33}{Vorsicht! Sein oder nicht sein ist im Süden die Frage. Eine falsche Bewegung, und es war deine letzte. Aber ... Du hast das Wasser geputzt. Garret wird's dir vergüten.}
{209}{Set34}{Hier wird nicht viel gelacht. Du hast das Wasser geputzt?}
{210}{}{So ist es.}
{211}{}{Oh, nein. Das bin nicht ich gewesen.}
{212}{Set35}{Ich falsch, dein Pech! Die Arbeit wächst, geh jetzt!}
{213}{Set36}{Ah, ja! Keine Spuren im Sand. Gut, sehr gut. Garret wird's dir vergüten.}
{214}{Set38}{Ich sag', wo's langgeht! Wenn's das war, verzieh dich jetzt!}
{215}{}{Ich bin hier, um das Kopfgeld für ein paar Mutanten abzukassieren.}
{216}{}{Danke, ich denke, ich geh' dann mal.}
{217}{}{Es wäre irgendwie leichter, wenn ich dich einfach beseitige.}
{218}{Set39}{Machbar. Folge Garret zu deiner Belohnung, dann geh einen anderen Weg.}
{219}{Set40}{Grund für Aggressionen? Geh, und nichts passiert. Steh, und du wirst massakriert!}
{220}{}{Tut mir leid, war ein schlechter Witz.}
{221}{}{Wurde auch Zeit, daß endlich mal was passiert!}
{222}{Set41}{Ahh, der Denker-Normalo! Am Wasser plattgemacht, ja? Willst 'ne Belohnung?}
{223}{}{Ähäh.}
{224}{}{Ähm, bin eigentlich hier, um dir in deinen häßlichen Arsch zu treten.}
{225}{Set42a}{Jetzt ist schlecht. Geh!}
{226}{}{Du bist mir einige Informationen schuldig.}
{227}{}{Wie wär's, wenn ich dir die Nase breche?}
{228}{}{Verstanden.}
{229}{}{Ähm?}
{230}{Set43}{Schlau! Schnell! Was?}
{231}{}{Du erledigst die Mutanten nicht selbst. Und warum? Weil dir jemand Angst macht. Warum?}
{232}{}{Warum soll ich die Mutanten für dich töten? Warum tun das nicht deine Ghuls?}
{233}{}{Wie zum Teufel kannst du diese Scheiße als Belohnung bezeichnen?}
{234}{Set44}{Nichts bringt mich zum Zittern. Sei deines Glückes Schmied! Du dienst, du kassierst, du gehst.}
{235}{}{Das ist doch nur ein Bluff!}
{236}{}{Wenn du meinst ...}
{237}{}{Ich glaub', das ist 'ne Drohung!}
{238}{Set45}{Du verstehst gar nichts. Wenn du nicht in Necropolis versauern willst, geh! Ich hab' keine Zeit für 'nen dummen Blutsack!}
{239}{}{Und wie sieht's mit deinem Sack aus?}
{240}{}{Verstanden.}
{241}{}{Leck mich!}
{242}{Set45a}{Mit Vergnügen ...}
{243}{Set46}{Kein Bluff, kein Trick! Der Meister läßt mich nicht erzittern. Geh! Die Zeit ist um.}
{244}{}{Danke für deine Zeit.}
{245}{}{Wenn ich dich jetzt fertigmache, sollte Zeit kein Problem mehr sein!}
{246}{Set47}{Ein Ghul? Für Kinderspiele? Hau ab!}
{247}{Set48}{Mir langt's! Verzieh dich!}
{248}{Set49}{Du Wurm! Ich will dich tot! Tot!}
{249}{Set50}{Ich sehe, daß du lügst, und einer von uns wird leiden! Du hast die Wahl: Vernichte die Mutanten oder stirb!}
{250}{}{Ich mach' mich gleich an die Arbeit.}
{251}{}{Da gibt's noch 'ne Möglichkeit: Ich könnte dir den Kopf abschrauben!}
{252}{Set51}{Noch immer hier? Warum reden Normalos dauernd, anstatt ihre Knochen zu bewegen? Aus jetzt! Geh! Geh!}
{253}{Set52}{Deine Anwesenheit bedeutet?}
{254}{}{Wollte nur sagen, daß der Meister tot ist.}
{255}{}{Ich hab' keine Ärsche mehr zum Reintreten, und da fiel mir dein Gesicht ein!}
{256}{}{Hah! Meister machen BUMM!}
{257}{Set52a}{Du meinst tot?}
{258}{}{Mhm.}
{259}{Set53}{Gut, sehr gut! Dein Wunsch ist mir Befehl. Sag ihn!}
{260}{}{Ich muß mehr über die Container wissen.}
{261}{}{Ich könnte noch mehr Waffen und Ausrüstung gebrauchen.}
{262}{}{Nichts, danke.}
{263}{}{Ich brauch' Zeugs.}
{264}{}{Nee.}
{265}{Set54}{Manche von uns konnten entkommen. Mutantenjob!}
{266}{}{Was haben sie gesagt?}
{267}{}{Mutanten? Häh? Brauch' wohl mehr Knarren!}
{268}{Set55}{Der Nordwesten ... weit ab vom Leben. Überall Wachen, kaum Durchkommen. Wenn dies dein Weg ist, werden dich meine Gedanken begleiten.}
{269}{Set56}{Garret sagt dir alles Nötige.}
{270}{Set57}{Du ... hast den Steuerchip verhökert. Eingetauscht ... für dein Leben!}
{271}{}{Wir beide brauchen Steuerchips, offensichtlich gibt's aber nur einen. Gibt es noch einen Weg, an den wir vielleicht nicht gedacht haben?}
{272}{}{Ich hab' den Steuerchip für meine eigene Vault gebraucht. Tut mir leid.}
{273}{}{Reicht eine Entschuldigung?}
{274}{}{Willst du ihn zurückhaben?}
{275}{}{Häh?}
{276}{Set58}{Ein Weg ... vielleicht ... Es gibt eine zweite Pumpe, aber sie geht nicht. Wir können sie nicht zum Laufen bringen.}
{277}{}{Vielleicht sollte ich mir diese Pumpe mal ansehen.}
{278}{}{Was für ein Pech auch! Hast wohl Durst, was?}
{279}{Set59}{Garret führt dich. Schalt die Pumpe ein, behalt' den Chip!}
{280}{}{Danke.}
{281}{Set60}{Erst saug' ich dich aus, dann fress' ich dich auf!}
{282}{}{Ich hab' ihn nicht bei mir.}
{283}{}{Wie wär's statt dessen mit Dreck fressen?}
{284}{Set61}{Dann stirb ... vor meinen Augen!}
{285}{Set62}{Gedanken brauchst du dann nicht mehr!}
{286}{}{Ich vermute mal, das soll nein heißen.}
{287}{Set63}{Dein Lohn ist es, für immer in Necropolis zu bleiben.}
{288}{}{Ziemlich mieser Lohn! Wie wär's, wenn ich dich statt dessen einfach beseitige?}
{289}{}{Ähm!}
{290}{Set64}{Für den Chip darfst du gehen ...}
{291}{}{Haha! Ich hab' ihn nicht mehr.}
{292}{}{Okay, hier ist er.}
{293}{}{Ich würde dich lieber tot sehen.}
{294}{Set65}{[Set gibt den Steuerchip einem Ghul, der damit wegläuft.] Wenn du je wieder Necropolis betrittst, ist's um dich geschehen!}
{295}{Set200}{Wie gesagt ...}
{296}{Set201}{Ich sagte schon ...}
{297}{Set202}{Laß mich nicht mit Normies ein!}
{298}{Set203}{Belästige Garret, ich bin's leid.}
{299}{Set204}{Hast du Stroh im Kopf?}
{300}{Set205}{Da hast nur du was von. Schlechter Deal!}
{301}{Set206}{Daran würde ich nie denken.}
{302}{Set207}{Unpassender Zeitpunkt. Der Abend kann deinen Anblick ertragen.}
{303}{Set208}{Wachen! Greift zu!}
{304}{Set209}{Wachen! Beendet mein Leiden!}
{305}{Set300}{Dafür ist hier kein Platz. Keiner!}
{306}{Set301}{Die Zukunft ... Überleben ... irgendwo. Wir übertreffen alle!}
{307}{Set302}{Ein Schönheitsfehler. Ein Dorn in meinem Auge. Ich hasse jedes bißchen!}
{308}{Set303}{Wo dein Schatten liegt. Mein Heim. Meine Regeln. Ein Ort, wo Stärke wächst.}
{309}{Set304}{Der Anfang. Welt zu Asche, Asche zu Wachstum. Unser Leben.}
{310}{Set305}{Falsche Ideale! Nichts in meinen Augen, gar nichts.}
{311}{Set306}{Viele von euch. Einige nützlich, aber zu viele Lügen.}
{312}{Set307}{Relikte! Wir sind besser, doch sie merken's nicht. Sie sehen nur, was sie glauben.}
{313}{Set308}{Zentrum der Wasserversorgung von Necropolis. Vergiftet durch die Mutanten. Will gar nicht daran denken!}
{314}{Set309}{Liefert alles Nötige.}
{315}{Set310}{Meiner nicht würdig.}
{316}{Set311}{Nicht mal im Traum!}
#
# Set Tell-Me-Abouts
#
{970}{Set01}{Easy! Ich bin Set, ich bin der Boß. Kapiert?}
{980}{Set206}{Daran würde ich nie denken.}
{981}{Set310}{Meiner nicht würdig.}
{982}{Set311}{Nicht mal im Traum!}

{1000}{}{Meister}
{1001}{}{Ghuls}
{1002}{}{Mutanten}
{1003}{}{Necropolis}
{1004}{}{Krieg}
{1005}{}{Einheit}
{1006}{}{Hub}
{1007}{}{Brotherhood of Steel}
{1008}{}{Wasserstelle}
{1009}{}{Children of the Cathedral}
{1010}{}{Steuerchip}
{1011}{}{Halle}
{1012}{}{Children}
{1013}{}{Garret}
{1014}{}{Set}
{1015}{}{Muties}
{1016}{}{Brotherhood}
{1017}{}{Wasserversorgung}
{1018}{}{Cathedral}
{1019}{}{Children of the Cathedral}
{1020}{}{Stelle}
{1021}{}{Wasser}

{1100}{Set300}{Dafür ist hier kein Platz. Keiner!}
{1101}{Set301}{Die Zukunft ... Überleben ... irgendwo. Wir übertreffen alle!}
{1102}{Set302}{Ein Schönheitsfehler. Ein Dorn in meinem Auge. Ich hasse jedes bißchen!}
{1103}{Set303}{Wo dein Schatten liegt. Mein Heim. Meine Regeln. Ein Ort, wo Stärke wächst.}
{1104}{Set304}{Der Anfang. Welt zu Asche, Asche zu Wachstum. Unser Leben.}
{1105}{Set305}{Falsche Ideale! Nichts in meinen Augen, gar nichts.}
{1106}{Set306}{Viele von euch. Einige nützlich, aber zu viele Lügen.}
{1107}{Set307}{Relikte! Wir sind besser, doch sie merken's nicht. Sie sehen nur, was sie glauben.}
{1108}{Set309}{Liefert alles Nötige.}
{1109}{Set310}{Meiner nicht würdig.}
{1110}{Set311}{Nicht mal im Traum!}
{1111}{Set204}{Hast du Stroh im Kopf?}
{1112}{Set310}{Meiner nicht würdig.}
{1113}{Set204}{Hast du Stroh im Kopf?}
{1114}{Set01}{Easy! Ich bin Set, ich bin der Boß. Kapiert?}
{1115}{Set302}{Ein Schönheitsfehler. Ein Dorn in meinem Auge. Ich hasse jedes bißchen!}
{1116}{Set307}{Relikte! Wir sind besser, doch sie merken's nicht. Sie sehen nur, was sie glauben.}
{1117}{Set309}{Liefert alles Nötige.}
{1118}{Set310}{Meiner nicht würdig.}
{1119}{Set310}{Meiner nicht würdig.}
{1120}{Set309}{Liefert alles Nötige.}
{1121}{Set309}{Liefert alles Nötige.}

