{100}{}{Du öffnest das Schloß.}
{101}{}{Du kannst dieses Schloß nicht öffnen.}
{102}{}{Du brichst deine Dietriche ab.}
{103}{}{Du weißt nicht, wie du das Schloß aufbekommen kannst.}
{104}{}{Die Tür ist versperrt.}
{105}{}{Die Tür ist offen.}
{106}{}{Die Tür ist geschlossen, aber nicht abgesperrt.}
{107}{}{Quieeeeetsch}
