{100}{}{Du bringst Seth, den Anführer, zurück nach Shady Sands.}
{101}{}{Wir müssen uns beeilen und diese Radscorpions loswerden.}
{102}{}{Laß uns nach Shady Sands zurückkehren und ihnen sagen, daß die Radscorpions weg sind.}
