#
# Shady Sands:
#
{100}{}{ Erfahrungspunkte für das Zurückbringen von Tandi.}
{101}{}{Im Süden siehst du eine Mauer aus Lehmstein, die ein friedlich aussehendes Dorf umgibt.}
#
# Vault 15:
#
{102}{}{Eine kleine Hütte ist das einzige Überbleibsel in dieser Gegend. Glücklicherweise
 wird in deinen Aufzeichnungen auf einen zweiten Eingang in die Vault-15 hingewiesen.}
#
# Raiders:
#
{103}{}{Du siehst ein kleines Gebäude, in dessen Nähe einige Zelte stehen. Die Bewohner
 machen einen schmutzigen und schäbigen Eindruck.}
#
# Junktown:
#
{104}{}{Du kommst an einer mittelgroßen Stadt vorüber. Eine Mauer aus Schrottautos versperrt
 den Eingang. Über der Stadt hängt eine Dunstglocke.}
#
# The Hub:
#
{105}{}{Im Süden siehst du eine große Stadt, die von einsamen Bauernhöfen umgeben ist.
 In dieser Wüstenoase herrscht reges Treiben.}
#
# Necropolis:
#
{106}{}{Du näherst dich einer dunklen, heruntergekommenen Stadt, in der nur wenig
 los ist. Über der Gegend hängt der Geruch des Todes.}
#
# Brotherhood of Steel:
#
{107}{}{Im Norden siehst du ein kleines Gebäude, das von einem Drahtzaun umgeben ist.
 Bedrohlich aussehende Wachen in schweren Rüstungen patrouillieren das Gebiet.}
#
# The Glow:
#
{108}{}{In Richtung Norden erstreckt sich ein großer Krater.}
#
# Military Base:
#
{109}{}{Im Nordosten kannst du vor einem befestigten Platz, der in eine Seite des Berges
 gebaut ist, Mutantenwachen sehen.}
#
# Cathedral:
#
{110}{}{Ein großes, prunkvolles Gebäude ragt in den Himmel. Vor dem Gebäude läuft
 eine Menschenmenge ziellos herum.}
#
# Gun Runners/Adytum/Followers/Rippers:
#
{111}{}{Im Norden siehst du ein Lagerhaus, das von einem Graben voll glühendem Schleim
 umgeben ist.}
{112}{}{Vor dir siehst du eine große, befestigte Fabrik mit Graffiti an
 den Mauern und bedrohlich aussehenden Schießscharten.}
{113}{}{In dem teilweise wiederaufgebauten Nachtclub und den kleinen Vorposten haben
 die Gangs deutliche Zeichen hinterlassen.}
{114}{}{Im Stadtzentrum ragt eine große, befestigte und restaurierte Bibliothek auf, die
 zugleich abschreckend und anmutig wirkt. In dir steigt ein wohliges, friedliches Gefühl hoch.}
{115}{}{Im Süden siehst du ein eingezäuntes Dorf, das von Wachen patrouilliert wird. Es macht
 einen widerstandsfähigen Eindruck.}
#
# StealthBoy:
#
{116}{}{Du siehst einen riesigen Fußabdruck auf dem Boden. Du suchst die Gegend nach
 weiteren Spuren ab, findest jedoch nichts mehr.}
#
# ???
#
{117}{}{Verbrannte Stellen und Asche überziehen das Gebiet.}
{118}{}{Diese Gegend sieht aus, als wäre hier eine Brandbombe von gewaltigem Druck niedergegangen.}
{119}{}{Du siehst das Lager von umher wandernden Raiders. Sieht so aus, als wärst du zur falschen Zeit am falschen Ort.}

# TODO: TRANSLATE
#
# WastelandGhost, Restoration Mod
#
{150}{}{Vor dir liegt eine stille Stadt voller Leichen und überall Blut. Etwas Schreckliches ist hier passiert.}
{155}{}{Eine von einem Maschendrahtzaun umgebene Struktur befindet sich im Norden. Sieht aus on es durch eine Explosion beschädigt wurde. Der Gestank des Todes ist hier fast unerträglich.}
#
# Sduibek, Fallout Fixt:
#
{151}{}{Diese Stadt ist bedrohlich still und übersät mit Leichen. Hier ist etwas Schreckliches passiert...}
{152}{}{Der Gestank des Todes ist hier fast unerträglich. Supermutanten patrollieren das Gebiet.}
{153}{}{Du kommst an deinem Ziel an, nur um Tod und den heulenden Wüstenwind zu finden.}
{154}{}{Sie siehst die Szenen eines Gemetzels. Es scheint keine Überlebenden zu geben, obwohl du leise Bewegungsgeräusche hören kannst.}
#

# Fo1in2
{200}{}{Geräusche dringen aus den Höhlen heraus.}
{201}{}{Du betrittst eine dunkle Höhle. Überall liegt Rattenkot.}
