{100}{}{Du siehst Sherry.}
{101}{}{Du siehst ein Gang-Mitglied.}
{102}{}{}
{103}{}{Wer bist du und was machst du hier?}
{104}{}{Ich bin }
{105}{}{. Ich bin neu in dieser Stadt.}
{106}{}{Geht dich nichts an, Weib!}
{107}{}{Puwah?}
{108}{}{Jeder scheint zu wissen, dass das Gebiet der Skulz ist. Du machst besser eine Fliege, bevor es jemandem einfällt, dir weh zu tun.}
{109}{}{Na los doch!}
{110}{}{Tut mir leid, ich dachte, das sei das Badezimmer. Tschüss.}
{111}{}{Die Skulz? Wer sind die denn?}
{112}{}{Ja, weiß ich. Ich halt' mich hier nur auf.}
{113}{}{Mach' dich weg, du Verlierer, bevor dich einer von uns in Stücke reißt.}
{114}{}{Puuh, tut mir leid.}
{115}{}{Ja? Na los doch!}
{116}{}{Du jämmerliches Ding. Du solltest einfach weitergehen. Es ist hier nicht sicher, vor allem nicht für jemanden wie dich, der das eh nicht verstehen würde.}
{117}{}{Das sind wir. Wir sind die härteste Gang in der Stadt. Eigentlich sind wir die einzige Gang. Keiner legt sich mit uns an.}
{118}{}{Also, ihr habt hier in der Stadt das Sagen, hey?}
{119}{}{Wie schön. Bis dann.}
{120}{}{Oh. Also, mach' das lieber nicht. Ich will nur sagen, du gehörst nicht zu den Skulz, und das ist unser Territorium. Also, verzieh' dich lieber, bevor Victor nervös wird.}
{121}{}{Nein, ich glaube, ich werde bleiben.}
{122}{}{Wer ist Victor?}
{123}{}{Gut. Ich hau' ab.}
{124}{}{Gut. Das ist dein Begräbnis.}
{125}{}{Victor ist gleich hier drüben. Er ist der Gemeinste von uns allen. Er quält gerne die Leguane, die er fängt. Ehrlich gesagt mag ich ihn nicht besonders, aber er ist einer von uns.}
{126}{}{Das ist also Victor, und dort ist Shark, der immer im Skum Pitt ist. Und Vinnie und ein
 paar andere Kerle, die ab und zu vorbeischauen.}
{127}{}{Wo ist das Skum Pitt?}
{128}{}{Ohm, das Skum Pitt ist ein verruchte Bar nördlich von hier, in der Nähe von Gizmos Kasino.}
{129}{}{Da kannst du Gift drauf nehmen! Niemand legt sich mit uns an! Bis auf Killian, aber der ist einfach cool. Er ist wie ein Sheriff. Wir machen, was wir wollen.}
{130}{}{Wir hängen hier einfach nur rum und manchmal machen wir ein paar Spielchen bei Gizmos oder vergnügen uns im Skum Pitt. Ab und zu erledigen wir ein paar Jobs für Gizmo oder für irgendeinen Reisenden. Victor gefällt es auch, Leuten aufzulauern. Eigentlich wäre es ganz ratsam, wenn du dich von ihm fernhalten würdest.}
{131}{}{Du arbeitest für Gizmo? Was kannst du mir über ihn sagen?}
{132}{}{Was genau machen denn diese Kerle?}
{133}{}{Wer ist alles in der Gang?}
{134}{}{Warum treibst du dich mit diesen Kerlen rum?}
{135}{}{Wir sind wie eine Familie! Wir passen aufeinander auf. Bis auf Shark, der immer was kaputt macht. Und Victor, der die Leute so komisch anstarrt. Aber Vinnie ist einfach cool. Und wir machen was zusammen. Du weißt schon, wir sind so was wie Freunde.}
{136}{}{Oh, du schon wieder. Du weißt, es ist wahrscheinlich nicht gut für deine Gesundheit, wenn du dich hier aufhältst und kein Skulz bist. Und du bist kein Skulz.}
{137}{}{Naja, ihr Skulz könntet wahrscheinlich nicht mal ein schlafendes Brahmin umhauen, geschweige denn, es mit mir aufnehmen.}
{138}{}{Und was treibst du immer so?}
{139}{}{Wirklich? Wir werden schon sehen! Victor!}
{140}{}{Nicht sehr viel, eigentlich. Es gibt nicht viel zu tun. Shark hat wie immer ein paar Schlägereien im Skum Pitt angefangen, aber was könnte man hier denn sonst noch machen?}
{141}{}{Uh, ich denke, nicht sehr viel.}
{142}{}{Du könntest immer noch etwas anderes machen. Hast du irgendwelche Begabungen oder Hobbys?}
{143}{}{Also, ich male gerne. Und Vinnie sagt, ich bin ein ziemlich guter Koch. Hey, und wir haben viel Spaß, verstehst du?}
{144}{}{Das kann ich schon verstehen.}
{145}{}{Aber was machst du, wenn du älter wirst? Wo führt dein Leben hin? Wie wirst du dein Geld verdienen?}
{146}{}{Mmm, also, hab' nie viel drüber nachgedacht. Vinnie und Victor verdienen etwas Geld, und Shark spielt manchmal den Leibwächter für einige Besucher, die hierher kommen. Ich weiß nicht.}
{147}{}{Du solltest vielleicht hier raus kommen, solange du noch kannst.}
{148}{}{Hey, hör' auf! Du hörst dich an wie damals Vinnies Eltern. Wir halten alle zusammen, klar? Also, lass' das.}
{149}{}{Kann schon sein. Hab' nie viel darüber nachgedacht.}
{150}{}{Hallo! Wie geht's? Schon 'ne Weile her.}
{151}{}{Gut, danke.}
{152}{}{Ging schon mal besser.}
{153}{}{Gut. Und dir?}
{154}{}{Tut mir aber leid, das zu hören! Vielleicht solltest du dir ein Zimmer nehmen und dich ausschlafen. Rede mit Marcelles. Oh, und hier kann ich dir etwas zum Essen machen, wenn du willst.}
{155}{}{Das wär' toll, danke.}
{156}{}{Nein, danke, aber man sieht sich.}
{157}{}{Oh, es geht mir schon viel besser, danke! Ich arbeite jetzt als Koch im Skum Pitt und im Crash House. An manchen Abenden ist es zwar etwas langweilig, aber ich koche gerne und treffe viele interessante Leute. Und ich werde dafür bezahlt. Danke für deine Hilfe.}
{158}{}{Da, bitte. Lass' es dir schmecken. Man sieht sich!}
{159}{}{Er ist dieser riesige Fettwanst, dem das Kasino gehört. Er möchte auch Junktown kontrollieren, aber Killian hält ihn unter Kontrolle. Er zahlt aber ziemlich gut. Gelegentlich heuert er Vinnie oder Victor an, um bestimmte Leute zur Vernunft zu bringen, falls es irgendwelche Probleme gegeben hat, wie z.B. diesen Fremden, der vor ein paar Wochen hier aufgetaucht ist.}
{160}{}{Du willst, dass ich meine Freunde verrate?!?}
{161}{}{Ja, ich brauche deine Informationen.}
{162}{}{Tut mir leid. Vergiss es.}
{163}{}{Sie haben Leuten weh getan und sie werden es weiterhin tun, wenn sie nicht aufgehalten werden. Du hast dein Leben positiv verändert. Jetzt hast du die Möglichkeit, anderen dabei zu helfen, ihr Leben ebenfalls zu verbessern.}
{164}{}{Hmm. Also, ja, es sind meine Freunde. Aber man sollte ihnen nicht erlauben, Leuten auf diese Weise weh zu tun. Und ich glaub', ich kann dir vertrauen, denn du hast mir geholfen. In Ordnung.}
{165}{}{Nein, das geht nicht! Das sind meine Freunde! Ich bin zwar kein Skulz mehr, aber ich verrate meine alten Freunde nicht.}
{166}{}{Ich brauche deine Hilfe. Ich brauche deine Aussage, um die Skulz für immer hinter Schloss und Riegel zu bringen.}
