{100}{}{Du siehst Sinthia, die verführerische Frau für gewisse Stunden.}
{101}{}{Du siehst eine wohlgeformte Frau mit einem Schmollmund.}
{102}{}{He, Darling, wie geht's?}
{103}{}{Okay. Tschüss dann!}
{104}{}{Ganz gut, aber es könnte besser gehen.}
{105}{}{Uhh.}
{106}{}{Uh, Baby, ich verstehe. Du musst nach Hause zur Mami. Komm' wieder, wenn du etwas Liebe brauchst!}
{107}{}{Ja, Darling, gleichfalls.}
{108}{}{Du findest schon, nach was oder nach wem du suchst, Darling, und dann geht es dir viel besser. Da bin ich mir sicher.}
{109}{}{Vielleicht kann ich dir dabei helfen.}
{110}{}{Vielleicht. Was ist dein Preis?}
{111}{}{Ich würde nicht einmal meinem Hund an dich ranlassen.}
{112}{}{Uh, Baby, wenn du schon so fragst ... etwas zu teuer für dich. Vielleicht das nächste Mal, Darling. Man sieht sich.}
{113}{}{Oh, Darling, das ist einfach ekelhaft.}
{114}{}{Oh, nein, Hilfe, Hilfe.}
{115}{}{Bitte sorg dafür, dass er mich nicht tötet.}
{116}{}{Ich bin zu jung zum Sterben.}
{117}{}{Oh Gott! Ich bin zu hübsch zum Sterben.}
{118}{}{Danke für deine Hilfe. Noch nie hat sich jemand so um mich gekümmert.}
{119}{}{Ich kann mich wirklich auch später um dich kümmern.}
{120}{}{Ist schon in Ordnung.}
{121}{}{Unh.}
{122}{}{Nochmals danke.}
{123}{}{Fällt dir nichts Besseres ein? Meine Güte, Leute gibt's!}
{124}{}{Mein Boss hat nicht mal ein paar seiner Schläger zu Hilfe geschickt. Man könnte meinen, dass er bei dem ganzen Geld, das ich für diesen Verlierer verdiene, wenigstens zu seinem Teil des Handels steht.}
{125}{}{Wer ist dein Boss?}
{126}{}{Welcher Handel?}
{127}{}{Gizmo natürlich. Er kontrolliert den Sündenpfuhl dieser Stadt. Killian würde verdammt sicher Leute wie mich nicht akzeptieren. Wenn ich für Gizmo nicht eine Menge Geld verdienen würde, dann hätte er sicherlich einen anderen Verwendungszweck für mich.}
{128}{}{Und, Darling, bei diesem Gedanken wird mir ehrlich gesagt schlecht.}
{129}{}{Was kontrolliert Gizmo sonst noch?}
{130}{}{Du solltest dein Geschäft an den Nagel hängen und dein eigenes Leben führen.}
{131}{}{Du hast recht, aber was soll ich sonst machen? Ich habe das Gefühl, mein Leben wird von anderen Menschen bestimmt. Naja, aber man muss sich halt irgendwie durchschlagen.}
{132}{}{Aber dieses Mal ist es kostenlos.}
{133}{}{Nochmals danke, Darling. Wir Frauen müssen zusammenhalten.}
{134}{}{Fast alles Schlechte, was man in dieser Stadt machen kann. Ihm gehört das Kasino. Er lässt mich und ein paar andere anschaffen. Man sagt, er möchte die Bar übernehmen.}
{135}{}{Du hältst dich von ihm fern, okay? Glaub mir, er ist nicht die Art von Schutzpatron, für den er sich ausgibt. Halt dich von ihm fern.}
{136}{}{Gizmo möchte sich um Killian kümmern, wenn du weißt, was ich meine.}
{137}{}{Oh, Darling. Ich kümmere mich um Männer, und sie kümmern sich um mich. Gizmo bekommt 25 % und ich angeblich seinen Schutz. Du hast gesehen, wie das funktioniert hat, nicht wahr?}
{138}{}{Was kontrolliert Gizmo sonst noch?}
{139}{}{Du möchtest Sinthia noch einen Besuch abstatten?}
{140}{}{Vielleicht wünscht sich Sinthia ein wenig Gesellschaft ...}
{141}{}{Du Scheißkerl! Du hast ihn umgebracht! Warum musstest du ihn töten? Du Dreckskerl! Ich glaub' es einfach nicht. Er wollte doch nur mit jemandem reden. Das Leben eines Menschen ist dir egal, oder?}
{142}{}{Du Ekel! Du hast ihn umgebracht! Warum musstest du ihn töten? Du Schlampe! Ich glaub' es einfach nicht. Er wollte doch nur mit jemandem reden. Das Leben eines Menschen ist dir egal, oder?}
{143}{}{Verschwinde verdammt noch mal aus meinem Zimmer!}
{144}{}{Du hast ihn umgebracht. Ich glaub' es einfach nicht. Er wollte doch nur mit jemandem reden.}
{145}{}{Er ist nicht tot. Ihm wird nur der Schädel brummen, wenn er aufwacht.}
{146}{}{Hnnn.}
{147}{}{Ja, wie auch immer. Verschwinde verdammt noch mal aus meinem Zimmer.}
{148}{}{Oh, tut mir leid, ich dachte, er sei tot. Ich dachte, du hättest ihn umgebracht. Er ist gar kein so schlechter Kerl. Nur ein bisschen einsam.}
{149}{}{Kein Problem}
{150}{}{Du schon wieder. Womit kann ich dir diesmal dienen?}
{151}{}{Ich schau' nur vorbei, wie's dir geht.}
{152}{}{Ich hab' 40 Deckel, hast du zehn Minuten Zeit?}
{153}{}{Ich brauch' noch ein paar Informationen über deinen Boss.}
{154}{}{Ah, Darling, lieber nicht. Denk nur, was für Kinder dabei rauskommen würden.}
{155}{}{Mir geht's gut, dank deiner Hilfe.}
{156}{}{Was willst du wissen, aber mach's kurz, meine Stoppuhr läuft.}
{157}{}{Wie viele Wachen hat er?}
{158}{}{Wo versteckt er sein Geld?}
{159}{}{Hat er irgendwelche Schwächen?}
{160}{}{Danke, Puppe, ich brauche keine weiteren Informationen.}
{161}{}{Hmm, persönlich kenn' ich acht, wenn du weißt, was ich meine. Ich glaube, er hat noch zehn oder so.}
{162}{}{Geld? Wie soll ich das wissen? Er nimmt nur mein Geld, aber er zeigt mir nicht seins. Ich denk' mal, es ist in seinem Schlafzimmer, aber soviel ich weiß, könnte er es an jedem dunklen Ort aufbewahren. Und für Gizmo gibt es da viele Möglichkeiten.}
{163}{}{Er glaubt, er hat gar keine. Er ist ein fetter Sack, der sich kaum bewegen kann. Und wenn, dann nur mit Hilfe seiner Wachen. Selbst die brauchen dazu ein kleines Dreirad. Hähähä!}
{164}{}{Okay, Darling, ausgemacht.}
{165}{}{Sicher, Darling, für dich doch immer.}
{166}{}{Du wirst dich bei mir wohl fühlen.}
{167}{}{Darling, du brauchst etwas mehr. Ich mag dich und alles, aber ich muss Geld verdienen.}
{168}{}{Ich behalte es mir vor, den Eintritt zu verweigern, und du, Darling, kommst nicht in meine Nähe!}
{169}{}{Sinthia schläft.}
{170}{}{Sinthia ist beschäftigt.}
{171}{}{Sinthia weigert sich, mit dir zu sprechen.}
{172}{}{Tut mir leid, Darling, keine Idioten!}
{173}{}{Geh mit deinem Geld, deinen Ansichten und deinem kleinen Schwanz woandershin!}
{174}{}{Oh Gott, Hilfe!}
{175}{}{Du erhältst }
{176}{}{ Erfahrungspunkte für die erfolgreiche Rettung von Sinthia.}
{177}{}{Die Wachen entfernen den bewusstlosen Gangster.}
