{100}{}{Du siehst Smitty,}
{101}{}{Du siehst einen großen, muskulösen Mann.}
{102}{}{Guten Tag, was kann ich für dich tun?}
{103}{}{Was willst du?}
{104}{}{Darf ich nach deinen Namen fragen?}
{105}{}{Du müßtest diese Teile für mich reparieren, damit ich eure Hydro-Farmen wieder in Ordnung bringen kann.}
{106}{}{Ich möchte etwas kaufen.}
{107}{}{Kann ich dir ein paar Fragen stellen?}
{108}{}{Nichts, danke. Man sieht sich.}
{109}{}{Uhhh . . .}
{110}{}{Ich schlag' vor, du schaust mal im Geschäft von Tine vorbei, gleich auf der anderen Seite der Tore. Ich verkaufe hier nichts. Ich tausche nur Sachen mit Tine oder den anderen Hub-Händlern gegen Waren aus.}
{111}{}{Warum? Alle nennen mich einfach Smitty. Wahrscheinlich, weil ich der örtliche Schmied bin.}
{112}{}{Frag' nur.}
{113}{}{Wo hast du deine ganze Ausstattung herbekommen?}
{114}{}{Was stellst du hier alles her?}
{115}{}{Kannst du Waffen und Munition herstellen?}
{116}{}{Das ist alles, danke.}
{117}{}{Es tut mir leid, aber ich glaube nicht, daß ich dir helfen kann. Versuch' es bei Zimmerman.}
{118}{}{Gewiß.}
{119}{}{Warum? Jeder kompetente Schmied kann seinen eigenen Amboß herstellen! Natürlich hab' ich das Handwerk rein durch Praxis erlernt, aber ich habe die meisten meiner Werkzeuge allein hergestellt.}
{120}{}{Meistens stelle ich hier Werkzeuge und Vorrichtungen her und repariere sie. Ich mache auch Dinge für die Hub-Händler. Mit Hilfe von Miles, dem Chemiker, lade ich manchmal Kugeln nach.}
{121}{}{Für das Herstellen von Waffen und Munition braucht man die nötigen Werkzeuge, und
 die hab ich nicht. Aber zusammen mit Miles, dem Chemiker, kann ich altes Messing eneut laden, da ich Kugeln gießen kann.}
{122}{}{Ja, das kann ich reparieren. Gib mir ein wenig Zeit.}
{123}{}{Hier bitte. [Smitty übergibt dir die reparierten Teile.]}
{124}{}{Ich habe die Teile bereits repariert. Du mußt sie jetzt Miles geben.}
{125}{}{Vielen Dank für das Wiederherstellen der Farmen. Wenn du jemals ein Plasma-Gewehr findest, bring' es hier her. Ich kenn' nämlich ein paar Tricks, wie man die Einspritzung verbessern kann.}
{126}{}{Hier hab' ich gleich eins für dich.}
{127}{}{Du hast also ein Plasma-Gewehr gefunden!}
{128}{}{Gib's rüber, dann schau' ich's mir mal an.[Smitty nimmt das Plasma-Gewehr, holt sein Werkzeug heraus und fängt an, daran herumzubasteln.]}
{129}{}{Hier, das sollte es gewesen sein. [Smitty gibt dir das Plasma-Gewehr zurück.] Versuch's mal damit.}
{130}{}{Wie gesagt, wenn du jemals ein Plasma-Gewehr in die Hände bekommst, bring' es her, und ich kann da was dran machen.}
{131}{}{Schön, dich mal wieder zu sehen. Ich hoffe, es geht dir gut.}

# TODO: TRANSLATE
# New: Motorcycle
{1000}{}{Oh damn, it's you! I've watched you coming down the road with that bike. Doesn't happen that often anymore nowadays. Usually it's just the brahim carts ... }
	{1010}{}{[More]}
{1100}{}{If you ever feel the bike 's too small, just hit me up, you hear? Got an old sidecart sitting around in a warehouse not far from here. The scavs could fetch it and I'll fix it up for you!}
	{1110}{}{How much would that cost me?}
	{1120}{}{Thanks for the offer. I'll keep that in mind.}

{1200}{}{It will take a day, and a few people need getting paid ... I'd say about 1.000 caps should cover it.}
{1201}{}{ ... On a second thought, you got us rid of the Regulators. So tell you what, I'll call in a few favors. What do you say?}
	{1210}{}{Here's the money. Get going!}
	{1220}{}{Maybe another time.}
	{1230}{}{Thanks, Smitty!}

{1300}{}{Doesn't look like you've got the caps. See me when you're stocked up.}
{1301}{}{Great! I'll get the bike into my workshop. [Smitty takes your keys.] }
	{1310}{}{[Wait]}

{1400}{}{That bike 's as good as new! [Smitty hands you back your keys.] I took the liberties to modify a few things here and there. Nothing super fancy, just a new fender as you can see, and I fixed that broken speedo. Now take good care of it!}

{1500}{}{Don't forget. I'll be here!}
	{1510}{}{Can you upgrade my motorcycle?}
	

