{100}{}{Du siehst Mrs. Stapleton, die Bibliothekarin.}
{101}{}{Du siehst eine Frau in mittleren Jahren.}
{102}{}{Hallo, willkommen in der Bibliothek. Ich glaube, ich habe dich hier
 noch nie gesehen. Welches Wissen suchst du denn?}
{103}{}{Schön dich wieder zu sehen. Nach was suchst du denn heute?}
{104}{}{Was für Bücher hast du?}
{105}{}{Ich suche nach einem Steuerchip.}
{106}{}{Nichts, aber danke.}
{107}{}{Also, hier ist meine Auswahl.}
{108}{}{In meinen Forschungen bin ich auf einige Verweise auf solche Dinge gestoßen. Ich habe eine Holo-Disk mit einigen Informationen, die für dich vielleicht von Nutzen ist.}
{109}{}{Eine Holo-Disk, was ist das?}
{110}{}{Kann ich die Holo-Disk haben?}
{111}{}{Eine Holo-Disk enthält Informationen, aber sie kann nur von bestimmten elektronischen Geräten gelesen werden. Ich sehe, du hast einen PIPBoy. Du kannst ihn zum Dekodieren, Betrachten und Speichern der Informationen verwenden, die eine Holo-Disk enthält.}
{112}{}{Hört sich großartig an! Kann ich die Holo-Disk haben?}
{113}{}{Informationen sind heutzutage sehr schwierig zu bekommen. Ich muß für die Disk 750 Hub-Scheine verlangen.}
{114}{}{Hört sich gut an. Hier ist das Geld.}
{115}{}{Diese Holo-Disk sieht aber schon ziemlich abgenutzt aus. Ich gebe dir 500.}
{116}{}{Wie wär's, wenn ich statt dessen diesen Laden mit einem Schweißbrenner besuche, Lady?}
{117}{}{Tut mir leid, ich hab' das Geld nicht.}
{118}{}{Tut mir leid, aber ich kann dir die Holo-Disk nur für den vollen Betrag geben. Komm' bitte wieder, wenn du das Geld hast.}
{119}{}{Tut mir leid, aber behalte deine pyromanischen Neigungen für dich. Geh' jetzt bitte.}
{120}{}{[Mrs Stapleton nimmt dein Geld.]}
{121}{}{Du hast recht. Die Disk hat schon bessere Zeiten gesehen. In diesem Fall nehme ich
 die 500 statt des ursprünglichen Preises. [Mrs Stapleton nimmt dein Geld.]}
{122}{}{Im Normalfall lasse ich mich nicht auf solche Methoden ein, aber um meine Sammlung vor einer solchen Bedrohung zu schützen, gebe ich dir die Disk. Als Gegenleistung möchte ich dich bitten, hier nie wieder aufzutauchen.}
{123}{}{Wie ich vielleicht schon erklärt habe, mußt du die darauf gespeicherten Informationen mit Hilfe deines PIPBoys lesen. [Mrs. Stapleton gibt dir die Holo-Disk.]}
{124}{}{Du mußt mich jetzt entschuldigen, aber ich muß weiterarbeiten.}
{125}{}{Ruk?}
{126}{}{Tut mir leid, ich verstehe dich nicht. Irgendwo habe ich eine Holo-Disk zum Erlernen der deutschen Sprache, falls dich das interessiert.}
{127}{}{Auf Wiedersehen.}
{128}{}{Danke.}
{129}{}{Ug.}
{130}{}{Hast du vielleicht irgendwelche Chemie-Zeitschriften? Miles in Adytum hat gesagt, du hättest welche.}
{131}{}{Ja, ich habe von Miles gehört und ich habe auch die Zeitschriften, die du suchst. Sie kosten dich 750 Dollar.}
{132}{}{Hier bitte, mein Herr. Grüß' Miles von mir.}
{133}{}{Tut mir leid, aber dein Geld reicht nicht. Komm' bitte wieder, wenn du das Geld hast.}

# TODO: TRANSLATE
# Fo1in2
{1000}{}{Ich habe über dich gehört, und wie du diese scheußlichen Mutanten gestoppt hast. Du bist ein echter Held! Da ist etwas, was ich dir gerne geben würde!}
	{1010}{}{[Mehr]}
{1100}{}{Vor langer Zeit kam dieser mysteriöse Mann durch den Hub und verkaufte mir ein ganz besonderes Buch. Ich habe nie viel damit anfangen können können, aber vielleicht hat es einen Nutzen für dich? [Mrs. Stapleton reicht dir eine zerfledderte alte Anleitung]}
	{1110}{}{[Fertig]}
	{1111}{}{[Fertig]}

{1200}{}{Nein danke! Ohne deine Hilfe wären wir wahrscheinlich alle schon tot oder wären in in diese ... Dinge verwandelt worden.}

