{100}{}{Du siehst Talus.}
{101}{}{Hallo, du bist bestimmt der Neuling von draußen. Freut mich, deine Bekanntschaft zu machen. Was kann ich für dich tun?}
{102}{}{Wer ist der Anführer eurer Organisation?}
{103}{}{Also, hast du hier das Sagen?}
{104}{}{Wo bekomme ich bessere Waffen und Ausrüstung?}
{105}{}{Chagga!}
{106}{}{Das ist die Vereinigung der Elder, ihr Anführer ist der High Elder, Maxson. Die Elder treffen hier alle wichtigen Entscheidungen. Sie sind im vierten Stock, falls du sie sprechen willst.}
{107}{}{Was machst du?}
{108}{}{Nein, wir unterstehen der Vereinigung der Elder. Maxson, der High Elder, hat hier das Sagen. Er ist im vierten Stock, falls du mit ihm sprechen willst.}
{109}{}{Ich könnte wirklich etwas mehr Feuerkraft brauchen.}
{110}{}{Ich bin der Ehrwürdige Paladin, die rechte Hand von Rhombus. Wir haben die Paladins und Knights unter Kontrolle. Momentan überwache ich die Trainingsübungen. Wir bereiten uns auf .... alles vor.}
{111}{}{Auf was bereitet ihr euch vor?}
{112}{}{Wie komme ich an Waffen und Ausrüstung?}
{113}{}{Es geht ein Gerücht von einer großen Macht um, die sich in den Bergen und der Wüste aufhält. Angesichts der verschwundenen Caravans und dieser Gerüchte gehen wir nur auf Nummer Sicher.}
{115}{}{Wirklich? Okay, danke.}
{116}{}{Wir haben es aber eilig! Als Neuling hast du auf ein paar Dinge Anspruch. Ich stell' dir eine Zulassung für eine Kampfrüstung und drei Runden Munition aus, Kugeln kannst du dir selbst aussuchen. Die Vorräte erhältst du von Michael im Zimmer nebenan.}
{117}{}{Ich bin dir sehr dankbar, aber hast du vielleicht eine Waffe übrig, die meine Überlebenschancen dort draußen verbessern könnte?}
{118}{}{Danke, wie sieht's mit ein paar High-Tech-Waffen aus?}
{119}{}{Ist das alles? Du machst wohl Witze!}
{120}{}{Ich verstehe, aber ich habe wirklich wenig Zeit und ich brauche mehr Feuerkraft.}
{121}{}{Großartig! Was soll ich jetzt tun? Den höchsten Berg hinaufklettern?}
{122}{}{Klingt super. Warum fängst du nicht gleich damit an?}
{123}{}{Also, ich könnte eine Ausnahme machen. Du bist offensichtlich gut ausgebildet, sonst hättest du die verrückte Suchaktion, auf die dich der High Elder geschickt hat, nicht erfolgreich überstanden.}
{124}{}{Manchmal weiß ich nicht ob er versucht, Hilfe von draußen zu bekommen oder nur die Blöden aus dem Weg räumen will. Nimm's nicht persönlich. Ich sag' dir was: Ich hab' hier ein kleines Problem wegen der Späher, die ich ausgesendet habe und die nicht mehr zurückgekommen sind.}
{125}{}{Es war meine Idee, und ich bekomme deswegen ein bißchen Druck von oben. Wenn du herausfinden kannst, was mit ihnen geschehen ist, soll es nicht dein Schaden sein.}
{126}{}{Ich überleg' es mir.}
{127}{}{Verzeihung, Neuling. Erhebe bitte nicht deine Waffe. Steck' sie weg, es sei denn, du willst sie benutzen.}
{128}{}{Steck' deine Waffe ein, Neuling. Du bist in keiner Trainingsübung, steck' sie ein.}
{129}{}{Würdest du bitte aufhören, mit deiner Waffe so herumzufuchteln? Du solltest... ach was, vergiß es.}
{130}{}{Hallo, Bruder }
{131}{}{. Wie kann ich dir helfen?}
{132}{}{Wer sind hier die wichtigen Leute?}
{133}{}{Könntest du mir noch einmal etwas über diese wichtigen Leute erzählen?}
{134}{}{Wie komme ich an bessere Waffen und Ausrüstung?}
{135}{}{Bekomme ich noch etwas mehr Munition?}
{136}{}{Nichts, danke.}
{137}{}{Damit kann ich dir behilflich sein. Als Neuling hast du auf ein paar Dinge Anspruch. Ich stell' dir eine Zulassung für eine Kampfrüstung und drei Runden Munition aus, die Kugeln kannst du dir selbst aussuchen.}
{138}{}{Die Vorräte erhältst du von Michael im Zimmer nebenan.}
{139}{}{Wie wär's mit dem Metallanzug, den du trägst?}
{140}{}{Danke, wie wär's mit ein paar High-Tech-Waffen?}
{141}{}{Also, wir sind alle wichtig, aber ich weiß, wen du meinst.}
{142}{}{Kein Problem. Du wirst die anderen Brüder gut kennenlernen. Ich weiß, es sind viele, und es kann manchmal schwer sein, sich alle zu merken.}
{143}{}{Da ist Rhombus. Er ist unserer oberster Paldin, auch bekannt als der Master Knight. Dann ist da Vree, sie ist der Master Scribe. Und dann ist da natürlich
 unser ehrwürdiger High Elder Maxson.}
{144}{}{Sag' mir etwas über Rhombus.}
{145}{}{Sag' mir etwas über Vree.}
{146}{}{Sag' mir etwas über Maxson.}
{147}{}{Rhombus ist bester Freund, Lehrer und Vaterfigur in einem. Er ist ein bißchen schroff, aber das ist in seiner Position wohl erforderlich.}
{148}{}{Falls du mit ihm sprechen willst, findest du ihn normalerweise in seinem Büro... ich meine Zimmer. Das befindet sich auf der anderen Seite von diesem Level, gegenüber vom Wachraum.}
{149}{}{Natürlich. Sie befindet sich auf dem zweiten Level. Neben dem Studierzimmer.}
{150}{}{Danke und auf Wiedersehen.}
{151}{}{Danke. Das ist alles, was ich wissen wollte.}
{152}{}{Ich kenne keinen so intelligenten Menschen wie Vree. Ich glaube, sie wurde mit dem Verständnis für Physik und Chemie schon geboren.}
{153}{}{Sie verbringt ihre ganze Zeit damit, alles, was sie in die Hände bekommt, zu erforschen oder zu analysieren oder neu zu analysieren. Falls du mit ihr sprechen willst, findest du sie für gewöhnlich in ihrem Zimmer, im dritten Stock.}
{154}{}{Sie befindet sich auf Level 2. Geh' einfach in den zweiten Stock hinunter und dann nach links. Falls du irgendwelche Fragen hast, frag' einfach.}
{155}{}{Ich sagte doch schon, daß sie auf Level 2 ist. Du kannst ihr Zimmer nicht verfehlen. Es ist das einzige größere Zimmer auf dem zweiten Stockwerk neben dem Studierzimmer.}
{156}{}{Okay, bis dann.}
{157}{}{Maxson ist ein harter alter Mann. Er ist der Ururgroßenkel - oder war es Urururgroßenkel? Egal, auf jeden Fall ist er ein Nachkomme von einem der Gründerväter. Er ist der High Elder.}
{158}{}{Du hast ein ziemlich gutes Ansehen erlangt. Die Leute, mit denen ich geredet habe, halten sehr viel von dir. Ich glaube, du brauchst keine Hilfe, du kannst dir durchaus selber helfen. Wenn du mir jedoch bei einem kleinen Problem hilfst, kann ich dir vielleicht eine kleine Belohnung zukommen lassen.}
{159}{}{Vielen Dank und auf Wiedersehen.}
{160}{}{Das wär alles, danke.}
{161}{}{Du gehst mir auf die Nerven, Kleiner. Was willst du jetzt schon wieder?}
{162}{}{Nichts, ich wollte nur deine angenehme Stimme hören.}
{163}{}{Tut mir leid, hab' dich dort nicht gesehen.}
{164}{}{Cha Toh Weh Lo!}
{165}{}{Ug.}
{166}{}{Hör auf, meine Zeit zu verschwenden!}
{167}{}{Wie bist du hier reingekommen? Geh' mir aus den Augen.}
{168}{}{Ich kann dir ein bißchen mehr Munition geben, falls du unbedingt welche brauchst. Bis du mit Michael redest, hab' ich die Erlaubnis fertig. }
{169}{}{Ich habe dir gerade welche gegeben. Du solltest lernen, mit deiner Munition etwas sparsamer umzugehen.}
{170}{}{Tut mir leid, aber du hast diese Woche schon mehr bekommen, als dir zusteht. Du mußt mit dem auskommen, was du hast. Wir haben keinen unbegrenzten Munitionsvorrat.}
{171}{}{Mir sind einige deiner Taten zu Ohren gekommen, und wir mögen Mörder nicht besonders. Die Elder glauben wohl, daß du uns vielleicht nützen kannst, aber ich will nichts mit dir zu tun haben.}
{172}{}{Ich habe nur eins getötet.}
{173}{}{Du kennst die ganzen Umstände nicht.}
{174}{}{Ich bin dir keine Antwort schuldig.}
{175}{}{Du hast ein ziemlich gutes Ansehen erlangt. Die Leute, mit denen ich geredet habe, halten sehr viel von dir. Ich glaube, du brauchst keine Hilfe, du kannst dir durchaus selber helfen. Es gibt da aber eine Sache, um die ich mich kümmern muß, und ich kann dir vielleicht helfen, wenn du mir helfen kannst.}
{176}{}{Sicher. Was ist das Problem?}
{177}{}{Nein, besten Dank auch.}
{178}{}{Kann ich nicht, tut mir leid. Aber vielen Dank für die Rüstung.}
{179}{}{Da du im Ödland alleine überleben konntest, denke ich, daß du dir durchaus selbst helfen kannst. Ich habe jedoch ein Problem, bei dem ich etwas Hilfe gebrauchen könnte, ich würde dich dafür auch belohnen.}
{180}{}{Nein. Ich denke, du solltest gehen.}
{181}{}{Ich habe einen unserer Neulinge vor kurzem zum Hub geschickt, und wir haben seitdem nichts mehr von ihm gehört. Wenn du herausfinden könntest, was mit ihm geschehen ist, wäre ich dir sehr dankbar.}
{182}{}{Ich werde dem mal nachgehen.}
{183}{}{Ich werde es versuchen, kann aber nichts versprechen.}
{184}{}{Ich sagte, du sollst gehen.}
{185}{}{Ist das alles? Ich glaube nicht, daß dir unser Orden helfen kann. Guten Tag.}
{186}{}{Ich brauche die Umstände nicht zu kennen. Guten Tag.}
{187}{}{Danke. Das werde ich dir nicht vergessen, und wenn ich sehe, daß du genügend Erfahrungspunkte gesammelt hast, kann ich dir vielleicht etwas Besonderes von unserem Orden geben.}
{188}{}{Wirklich? Was?}
{189}{}{Gib' es mir jetzt!}
{190}{}{Klingt gut. Auf Wiedersehen.}
{191}{}{Ich sollte es nicht sagen, aber es ist keine Waffe. Es ist etwas, auf das nur die Elite unseres Ordens Anspruch hat, aber da du von draußen kommst und es besser gebrauchen kannst, werde ich vielleicht eine Ausnahme machen können.}
{192}{}{Kannst du es mir nicht sagen?}
{193}{}{Okay, auf Wiedersehen.}
{194}{}{Ich glaube, du kannst dir denken, was es ist. Belassen wir es dabei.}
{195}{}{Nein, das werde ich nicht, ich glaube, du solltest jetzt gehen, "Neuling".}
{196}{}{Nur Paladins tragen eine Powerrüstung, und eines Tages verdienst du dir vielleicht auch das Recht, sie zu tragen.}
{197}{}{Danke, wie wär's mit ein paar High-Tech-Waffen?}
{198}{}{Also, ich sehe, unser Orden hat doch auch einmal klugen Zuwachs bekommen... [Talus starrt dich an.] Werd' nicht frech mit mir, Neuling. Ich hab' weder die Lust noch die Geduld, mich mir dir abzugeben!}
{199}{}{Ich dachte, du wärst etwas klüger. Ich brauche dir gar nichts zu geben. Du kannst von Glück sagen, daß ich dich nicht gleich rauswerfe. Geh' lieber, bevor ich es mir anders überlege.}
{200}{}{Schon in Ordnung. Alles, was du findest, könnte nützlich sein.}
{201}{}{Bruder }
{202}{}{! Ich habe Nachricht von Bruder Jonathan erhalten. Danke für seine Rettung.}
{203}{}{Soviel ich weiß ist Decker tot. Du hast mehr Talent als ich dachte, und das will was heißen.}
{204}{}{Decker soll dafür bezahlen, was er getan hat. Das versprech ich dir.}
{205}{}{Gern geschehen.}
{206}{}{Lup?}
{207}{}{Hallo Fremder! Man sagt, daß man dir für die sichere Rückkehr des vermißten Neulings zu danken hat.}
{208}{}{Ich hab' auch gehört, daß Decker tot ist. Du bist ein großer Gewinn für unsere Brotherhood.}
{209}{}{Wir tolerieren hier keine Gierhälse. Ich schlage vor, du gehst zu einem Arzt und wirst wieder gesund.}
{210}{}{Was deine Belohnung angeht, so kannst du eine der folgenden wählen:}
{211}{}{Also was möchtest du lieber?}
{212}{}{Raketenwerfer.}
{213}{}{Laserpistole.}
{214}{}{Super-Vorschlaghammer.}
{215}{}{Ich überleg' es mir.}
{216}{}{Ich gebe deine Erlaubnis sofort ein. Hol' dir deine Belohnung von Michael ab.}
{217}{}{, es ist an der Zeit, daß du deine eigene Powerrüstung trägst. Das ist ein ganz besonderes Privileg für jemanden, der so neu in unserem Orden ist. Trage die Powerrüstung bei deinen Streifzügen durch das Ödland als Symbol der Hoffnung. Denn eines Tages, wenn die Welt bereit ist, werden wir auferstehen und die geschundene Erde wiederherstellen. Gratuliere, wir sind sehr stolz auf dich. Ich sende die Erlaubnis an Michael.}
{218}{}{Ich sehe, dir hat bereits jemand einen Poweranzug gegeben. Ich wollte ihn dir eigentlich selbst geben, aber das ist schon OK. Ich hoffe, er ist dir bei deiner Suche behilflich.}
{219}{}{Bleibt fit!}
{220}{}{Aufpassen, Leute.}
{221}{}{Nicht nachlassen!}
{222}{}{Benehmt euch, dort drüben, sonst kommt ihr auf die Nachtpatrouille.}
{223}{}{Ruhe, sonst muß ich Rhombus reinholen. Er reißt euch den Arsch auf.}
{300}{}{Wenn du etwas brauchst, komme bitte morgen früh wieder.}
{301}{}{Ich bin morgen früh in der Turnhalle. Dann reden wir.}
{302}{}{Was machst du hier. Dies ist nicht deine Unterkunft.}
{303}{}{Gute Nacht, Neuling, wir sprechen morgen früh. So dringend kann es doch gar nicht sein.}
{304}{}{Ich bin müde und will ins Bett. Geh' bitte.}
{305}{}{Belästigst du die Leute immer in ihren Unterkünften?}
{400}{}{Du kannst immer... Moment. Sieh mir in die Augen. Ich wußte es. Du solltest mit dem Zeugs aufhören. Das kann dich wirklich fertigmachen. Wenn du nicht aufpaßt, dann endest du wie die Skags beim Hub. Also, was wolltest du?}
{401}{}{Habt ihr einen Arzt? Ich bin verletzt.}
{402}{}{Habt ihr einen Arzt?}
{403}{}{Dieser Berg hat mich total fertig gemacht.}
{404}{}{Wo befindet sich euer Arzt?}
{406}{}{Hmmm, ich weiß nicht. Du hast dich zwar als Neuling bewährt, aber wir wollen nicht gleich Waffen an jemanden aushändigen, der vielleicht nicht qualifiziert ist, vor allem, wenn es einer von draußen ist, du verstehst schon.}
{407}{}{Powerrüstung.}
{408}{}{Du erhältst }
{409}{}{ Erfahrungspunkte für die Rettung des Neulings.}

#Fo1in2
{410}{}{Magneto-Laserpistol.}
