{100}{}{Du siehst einen heiteren Mann mit kurzen Haaren.}
{101}{}{Du siehst den Händler der Stadt, Tine.}
{102}{}{Hier kommen nicht viele Fremde vorbei, was willst du?}
{103}{}{Hallo Fremder! Was kann ich heute für dich tun?}
{104}{}{Ich heiße }
{105}{}{.}
{106}{}{Kann ich dich etwas über die Händler vom Hub fragen?}
{107}{}{Ich würde gerne etwas Handel treiben.}
{108}{}{Was verschlägt dich nach Adytum?}
{109}{}{Nix.}
{110}{}{Ja, ich treibe Handel mit ihnen.}
{111}{}{Ich handle manchmal mit ihnen. Meistens tausche ich Kugeln gegen Essen.}
{112}{}{Ich bin Tine. Du hast ein Geschäft zu erledigen?}
{113}{}{Erfreut, dich kennenzulernen. Ich bin Tine.}
{114}{}{Es ist toll, mit dir Geschäfte zu machen. Komm' wieder.}
{115}{}{Was auch immer.}
{116}{}{Rühr' dich mal wieder!}
{117}{}{Was?}
{118}{}{Hallo. Wie kann ich dir helfen?}
{119}{}{Es ist eine gute Stadt. Wäre ein bißchen lustiger hier, wenn die Regulatoren kein so strenges Regiment führten. Aber was soll's, so sind sie eben.}
{120}{}{Keine schlechte Stadt hier. Zimmerman ist ein gerechter Mann, wenn auch nicht gerade der hellste.
 Und dann ist das natürlich nur Miles, wahrscheinlich der einzige weit und breit, der etwas von Wissenschaft versteht.}