{100}{}{Du siehst Bruder Thomas.}
{101}{}{Hallo. Du mußt der Neue sein, von dem mir Neuling Talus erzählt hat. Es ist schrecklich spät für einen Besuch. Was kann ich für dich tun?}
{102}{}{Ich brauche ein paar Vorräte.}
{103}{}{Ich benötige etwas Training.}
{104}{}{Ich benötige medizinische Hilfe.}
{105}{}{Nichts, entschuldige die Störung.}
{106}{}{Yuk Yuk?}
{107}{}{Ruh.}
{108}{}{Was kannst du nur zu dieser Stunde wollen?}
{109}{}{Ich habe keine Zeit für so was.}
{110}{}{Was? She' ich aus wie der Mann, der alles weiß? Ich weiß nicht mal, wer ich bin. Also, warum belästigst du mich? Geh' jetzt bitte!}
{111}{}{Verdammt.}
{112}{}{, ich bin ein Ausbilder und kein Arzt. Sie ist auf Level 2.}
{113}{}{Also, warum belästigst du mich? Michael schläft jetzt wahrscheinlich, außer Talus hat ihn auf Wache geschickt. Probier's mal am Morgen beim Vorratsraum.}
{114}{}{Also, die Elder haben zwar die Ausbildung von Neulingen untersagt, aber gut. Du scheinst ein netter junger Kerl zu sein. Ich möchte nicht, daß dir da draußen was passiert, wenn ich dir hätte helfen können. Auf welchem Gebiet möchtest du ausgebildet werden?}
{115}{}{Also, die Elder haben zwar die Ausbildung von Neulingen untersagt, aber gut. Du scheinst ein netter junger Kerl zu sein. Ich möchte nicht, daß dir da draußen was passiert, wenn ich dir hätte helfen können. Auf welchem Gebiet möchtest du ausgebildet werden?}
{118}{}{Kleine Waffen.}
{119}{}{Große Waffen.}
{120}{}{Energiewaffen.}
{121}{}{Unbewaffneter Kampf.}
{122}{}{Nahkampfwaffen.}
{123}{}{Werfen.}
{124}{}{Nichts, danke.}
{125}{}{Also, ich sollte dich sofort rauswerfen, aber ich bin ein freundlicher alter Mann. Die Elder haben zwar die Ausbildung von Neulingen untersagt, aber ich kann dir vielleicht helfen. Sie haben wahrscheinlich nicht an dich gedacht, als sie das bestimmt haben. Auf welchem Gebiet suchst du Ausbildung?}
{126}{}{Hallo. Schön, dich zu sehen. Du brauchst nicht scheu zu sein. Ich schlafe nicht mehr viel. Suchst du nach weiterer Ausbildung? Was soll es heute sein...ich meine, heute abend.}
{127}{}{Ich wußte, du würdest zurückkommen. Auf was hast du heute abend Lust?}
{128}{}{Stellst du mir wieder blöde Fragen? Ich hab' wirklich keine Zeit.}
{129}{}{Also, es ist so. Waffen unterschiedlichen Kalibers...}
{130}{}{Nach einem Tag intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im Umgang mit kleinen Waffen zugenommen haben.}
{131}{}{Das...}
{132}{}{Nach zwei Tagen intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im Umgang mit großen Waffen zugenommen haben.}
{134}{}{Nach einigen Tagen intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im Umgang mit Energiewaffen zugenommen haben.}
{135}{}{Nach einem Tag intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im unbewaffneten Kampf zugenommen haben.}
{136}{}{Nach zwei Tagen intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im Umgang mit Nahkampfwaffen zugenommen haben.}
{137}{}{Nach einem Tag intensiver Ausbildung hast du das Gefühl, daß deine Fähigkeiten im Werfen von Objekten zugenommen haben.}
{138}{}{Kein Problem. Sag' mir, wenn du es dir anders überlegst.}
{139}{}{Ich weiß nicht, warum ich meine Zeit mit dir verschwende.}
{140}{}{Ja? Oh, ich vermute, du willst noch mehr Ausbildung. Also, ich schlafe sowieso nicht mehr viel, warum also nicht? Was soll es sein?}
{141}{}{Was denn jetzt schon wieder? Mehr blöde Fragen?}
{142}{}{Oh, das ist schon in Ordnung. Wie gesagt, ich schlafe eh kaum noch. Du kannst jederzeit wiederkommen.}
{143}{}{Hör endlich auf, mich zu belästigen. Ich bin ein alter Mann und ich brauche meinen Schönheitsschlaf.}