# Special Encounter

{100}{}{Du siehst jemanden in einer Robe.}

{150}{}{Vater! Der Auserwählte ist dem Weg. Bekommt er deinen Segen? Bist du deshalb hier?}
{151}{}{Mutter! Der Auserwählte ist dem Weg. Bekommt er deinen Segen? Bist du deshalb hier?}
{152}{}{Ugh!}

{200}{}{Du erhälst }
{201}{}{ Erfahrungspunkte für das überleben des Tempels der Erprobungen.}





