{100}{}{ spürt, daß eine Falle in der Nähe ist.}
{101}{}{Du spürst, daß eine Falle in der Nähe ist.}
{102}{}{ löst eine Falle aus und alarmiert dadurch den Stützpunkt.}
{103}{}{Du löst eine Falle aus und alarmierst dadurch den Stützpunkt.}

# TODO: TRANSLATE
{104}{}{You earn }
{105}{}{ experience for successful use of your Traps skill.}
{106}{}{ disarms the trap.}
{107}{}{You disarm the trap.}
{108}{}{ sets off a trap!}
{109}{}{You set off a trap!}
{110}{}{You detect a trap here, but fail to disarm it.}
{111}{}{You fail to disarm it.}
{112}{}{ fails to disarm it.}
{113}{}{ sets off the trap!}
{114}{}{You set off the trap!}
