{100}{}{Hau ab! Lass mich allein!}
{101}{}{Hallo, Fremder, du solltest nicht hier draußen sein. Hier gibt es nur Tod.}
{102}{}{Du weißt nicht zufällig etwas über die verschwundenen Caravans?}
{103}{}{Wer bist du?}
{104}{}{Was für einen Tod?}
{105}{}{Ich brauche ein paar Vorräte. Gib sie her!}
{106}{}{Ich suche nach einem Steuerchip. Kannst du mir helfen?}
{107}{}{Weißt du zufällig etwas über die Deathclaw?}
{108}{}{Rurr? Sniff?}
{109}{}{Was willst du? Lass mich in Ruhe!}
{110}{}{Rrr. Snrg.}
{111}{}{Groß! Groß! So groß wie drei Männer! Klauen so lang wie mein Unterarm! Reißt alles in Stücke! Reißt alles in Stücke!}
{112}{}{Ja. Sonst noch was?}
{113}{}{Beruhig dich mal wieder, Mann. Du bist jetzt in Sicherheit.}
{114}{}{Mann, hört sich nach einem widerlichen Monster an.}
{115}{}{Hast du sie getötet?}
{116}{}{Ich bin Trent. Ich bin eine Wache der Water Merchants. Unser Caravan wurde von einem Monster angegriffen. So riesig, so schnell! Es hat Joe gefressen und selbst Gewehrschüsse abbekommen und dabei nicht mal mit der Wimper gezuckt! Wahnsinnig riesig!}
{117}{}{Was hat euch angegriffen?}
{118}{}{Hört sich nach einer Art Supermutant an.}
{119}{}{Hört sich nach der Deathclaw an!}
{120}{}{Das soll euch lehren, eure Preise weiter hoch zu treiben.}
{121}{}{Gut. Ich brauch' sie eigentlich nicht mehr.}
{122}{}{Steuerchip! Ich bin eine Wache, kein Ingenieur! Frag die Water Merchants im Hub, die wissen es wahrscheinlich.}
{123}{}{Deathclaw!}
{124}{}{Was machst du? Lass mich gehen!}
{125}{}{Ich ... ich weiß nicht. Ich hab' schon so lange nicht mehr geschlafen. Hungrig, durstig, müde. Ich muss nach Hause.}
{126}{}{}
{127}{}{Riesige Hörner, widerliche rote Haut, wie eine Figur aus einer Gruselgeschichte, und es hat Joe mit drei Bissen verschlungen.}
{128}{}{Niemand ist sicher! Niemand ist sicher, niemand ist mehr sicher. Was soll ich nur machen ...}
{129}{}{Bist du verrückt? Ich habe drei Schuss aus meiner Desert Eagle auf dieses Monster abgefeuert, und es hat noch nicht einmal gezuckt.}
{130}{}{Mir ist es egal, ob es ein Mutant, ein Außerirdischer oder ein Teufel aus der Hölle ist! Ich will in meinem ganzen Leben nicht noch einmal so ein Monster sehen.}
{131}{}{Ich bin nur eine Wache, verdammt! Gib nicht mir die Schuld! Und sie bezahlen mich gut! Ich habe keine Problem mit ihnen!}
{132}{}{Wie kann ich dir helfen?}
{133}{}{Sie wurden von Deathclaws angegriffen. Ich dachte immer, das wären nur Geschichten, aber du glaubst nicht, wie groß und schnell die sind. Zunächst haben wir sie nur gerochen, dann kamen sie über den Berg auf uns zu. Wir sind alle gerannt, und irgendwie konnte ich entkommen.}
{134}{}{Trent, Trent Barrister. Ich lebe im Hub. In letzter Zeit gab es nur sehr wenig Arbeit. Ich bin ein ziemlich guter Schütze, also hab' ich mich bei den Water Merchants als Wache beworben. Das Geld ist nicht schlecht, das Risiko gering. Wenigstens dachte ich das ...}
{135}{}{Keine Ahnung. Das ist eine alte Technologie, stimmt's? Vielleicht findet ein Scavenger hin und wieder mal einen, aber ich wüsste nicht, wo ich mit der Suche beginnen würde. Heutzutage werden die doch gar nicht mehr benutzt, oder?}
{136}{}{Sie sind riesig. Wie große Eidechsen. Riesige Krallen und Zähne, riesige Hörner und sie lieben den Geschmack von Menschen. Und schnell, mein Gott, schnell sind die. Ich bin nur froh, dass sie nicht mich gejagt haben, sonst wär' ich jetzt tot.}
{137}{}{Danke. Vielleicht war das alles nur ein Missverständnis. Ich hab' nicht viel Geld, aber es gehört jetzt dir.}
{138}{}{Danke. Oh Gott, das ist gut. Ich hab' nicht viel Geld, aber es gehört jetzt dir.}
{139}{}{Danke. Vielleicht war das alles nur ein Missverständnis. Ich hab' nicht viel Geld, aber verdammt! Es muss mir runtergefallen sein. Jedenfalls gehört es jetzt dir.}
{140}{}{Danke. Vielleicht war das alles nur ein Missverständnis. Ich hab' nicht viel Geld, aber verdammt! Es muss mir runtergefallen sein. Jedenfalls gehört es jetzt dir.}
{141}{}{Hilf mir!}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{142}{}{Der Geruch des Todes, mein Freund. Der Geruch des Todes ...}
{143}{}{Der Geruch des Todes, meine Freundin. Der Geruch des Todes ...}
