{100}{}{Du siehst einen Mann in einer staubigen Lederrüstung mit einem Trenchcoat und einer Gasmaske.}
{101}{}{Du siehst Tycho.}
{102}{}{Wieder ein neues Gesicht. Reisende sehen hier alle gleich aus. Aber du bist etwas anders. Willst du mir bei einem Drink Gesellschaft leisten?}
{103}{}{Tut mir leid, ich hab's etwas eilig.}
{104}{}{Sicher.}
{105}{}{Duh-wah?}
{106}{}{Vorzüglich. Ich hoffe, dir macht es nichts aus, wenn dein Drink ein bißchen verwässert ist - man behandelt hier Bier wie Topfpflanzen.}
{107}{}{Also, was ist deine Geschichte?}
{108}{}{Ja, auf einen Schluck Wasser. Ist egal.}
{109}{}{Ich könnte dich das Gleiche fragen. Aber um der Freundschaft willen fang' ich an.
 Ich heiße Tycho, komm' aus einem Gebiet im Osten, das einmal Nevada genannt wurde.}
{110}{}{Das ist eine ziemlich lange Reise.}
{111}{}{Wie hast du all die Gefahren überlebt?}
{112}{}{Ja, war es auch. Ich beschloß, mich etwas auszuruhen. Dieser Ort wär' nicht schlecht,
 wenn nur einer mal mit dem Gesindel aufräumen würde.}
{113}{}{Warum tust du es nicht?}
{114}{}{Ja, ist mir auch aufgefallen. Was weißt du über diese Idioten?}
{115}{}{Hatte eine ziemlich gute Ausbildung und auch ein paar gute Waffen. Mein Großvater war vor langer Zeit Ranger, und er brachte meinem Vater alles bei, was er wußte. Mein Vater hat es dann an mich weitergegeben. Ich weiß also sozusagen genug, um kein glühendes Wasser
 zu trinken.}
{116}{}{Interessant. Danke für den Drink.}
{117}{}{Wirklich? Das Überleben ist hart heutzutage. Du mußt ein beträchtliches Wissen haben.}
{118}{}{Nicht mein Auftrag. Ich möchte Killian nicht in die Quere kommen. Er wird diese Stadt aufräumen, wenn er Zeit dazu hat. Ein guter Mann, denk an meine Worte. Aber paß' auf diesen Gizmo auf. Erinnert mich an einen anderen fetten Freak, von dem mir mein Vater in Las Vegas erzählt hat.}
{119}{}{Danke für den Tip und den Drink.}
{120}{}{Es gibt hier zwei Arten von Gesindel. Eine davon sind die Skulz, eine Gang, die sich im hinteren Teil von Marcelles Crash House aufhält. Dabei handelt es sich nur um durchschnittliche Idioten. Aber die anderen hören auf diesen fetten Freak, dessen Namen du wahrscheinlich erraten kannst. Leitet das Kasino. Diese Jungs sind organisiert und gefährlich.}
{121}{}{Ah ja. Danke für die Info.}
{122}{}{Also meine Familie hat mir alles beigebracht, was ich zum Überleben wissen muß.
 Trinke zum Beispiel kein Wasser, das völlig klar und frei von Insekten und Moos ist. Nur giftiges oder radioaktives Wasser wäre in der Wildnis so sauber. Sie haben mir auch viele andere Kleinigkeiten beigebracht, auf die man achten muß.}
{123}{}{Was zum Beispiel?}
{124}{}{Also, wenn du etwas Zeit hast, kann ich ein paar Tips mit dir durchgehen.}
{125}{}{Sicher, das wär toll.}
{126}{}{Tut mir leid, meine Zeit ist etwas knapp.}
{127}{}{Halt, halt, nicht so schnell. Wir sind noch nicht mit dem Vorstellen fertig, schon vergessen?
 Wie heißt du, Fremder?}
{128}{}{Ich bin }
{129}{}{.}
{130}{}{Geht dich nichts an, du Schwachkopf.}
{131}{}{Erfreut, deine Bekanntschaft zu machen. Paß' auf dich auf, Freund.}
{132}{}{Hey, hey, kein Grund, gleich unhöflich zu werden. Aber mit dieser Einstellung machst du dich am besten gleich wieder fort.}
{133}{}{Leck mich.}
{134}{}{Was auch immer. Man sieht sich.}
{135}{}{Was willst du?}
{136}{}{Tut mir leid, daß ich dich gestört habe. Geh' und hol' dir woanders einen runter.}
{137}{}{Ich brauche ein paar Informationen über die Gangs hier.}
{138}{}{Ich brauche ein paar Informationen über die Stadt.}
{139}{}{Hallo, wie kann ich dir helfen?}
{140}{}{Killian hat mich gebeten, in dieser Stadt aufzuräumen, und ich hätte gerne deine Hilfe.}
{141}{}{Also, das hier ist das Skum Pitt, ein Tummelplatz für Verbrechen und Ganoven. Gleich westlich von hier ist Gizmos, ein großes Kasino. Die Spiele sollen aber manipuliert sein. Ein wenig südlich von hier ist das Crash House, das von Marcelles geleitet wird, man kann da
 für einen Wucherpreis übernachten. Dahinter ist Killians Laden. Killian hütet auch das Gesetz in dieser Stadt - ein guter Mann. Südlich davon befindet sich Doc Morbid, der auf etwas seltsame Art operiert, wenn du weißt, was ich meine.}
{142}{}{Ich hoffe, meine kleine Unterweisung hat dir ein wenig geholfen.}
{143}{}{}
{144}{}{Man sagt, daß du Kontakte mit Gizmo gehabt hast. Wenn ich du wäre, würde ich vorsichtig mit diesem Fettsack umgehen.}
{145}{}{Meine Sache und geht dich nichts an.}
{146}{}{Ja, ich arbeite jetzt für Gizmo. Was schert dich das?}
{147}{}{Schon OK. Aber paß' auf. Gizmo ist nicht gerade dafür bekannt, daß er auf seine Mitarbeiter achtet.}
{148}{}{Es reicht, wenn ich sage, daß dein Arbeitgeber mehr als genug Elend und Streit in dieser Stadt angerichtet hat. Erwarte nicht viel Hilfe von irgendjemanden, am wenigsten von Gizmo. Schade auch. Du hättest diese Stadt zum Guten ändern können.}
{149}{}{Was kann ich für dich tun?}
{150}{}{Irgendwelche Empfehlungen?}
{151}{}{Danke für deine Hilfe. Es wird Zeit, daß sich unsere Wege wieder trennen.}
{152}{}{Ja, ich würde mich verdammt noch mal von dem Ding fernhalten, von dem das hier stammt. Im Ernst, ich hab' so etwas noch nie gesehen. Am besten gehen wir schnell weiter.}
{153}{}{OK. Ich muß sagen, es war mir eine Ehre und ein Vergnügen.}
{154}{}{Paß' auf die radioaktiven Hot Spots auf. Dieser Ort hat einen Nuklearschlag erhalten und die sekundäre Kaskadenstrahlung kann sehr hoch sein.
 Wir sollten diesen Ort nach Möglichkeit ganz und gar vermeiden.}
{155}{}{Beachte das Fehlen jeglicher Fauna über eine ziemlich große Fläche hinweg. Und die Knochenhaufen. Was auch immer hier lebt, es ist ein echtes Tier. Halte deine Waffe bereit.}
{156}{}{Eine militärische Anlage wie diese muß irgendwo über eine zentrale Leitstelle verfügen.}
{157}{}{Ich wette, wir könnten durch diese Kraftfeld-Generatoren mit Hilfe einer kleinen Kurzschlußverbindung hindurch kommen oder wir könnten den Kraftfeld-
 Steuerungscomputer finden.}
{158}{}{Es gibt viele seltsame Geschichten über Necropolis, die Stadt der Toten. Bleib wachsam, denn es kann sehr schnell gefährlich werden.}
{159}{}{Ich muß die Formation ändern.}
{160}{}{In welchem Abstand soll ich bleiben?}
{161}{}{Bleib nahe bei mir.}
{162}{}{Halte etwas Abstand.}
{163}{}{Geh' etwas weiter weg.}
{164}{}{Welche Waffenfähigkeiten hast du erlernt?}
{165}{}{Ziemlich gutes Ranger-Training. Ich kann einen Speer blitzschnell benutzen. Außerdem kann ich mit kleinen Pistolen und Gewehren umgehen.}
 {166}{}{Uh, vergiß es.}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

{167}{}{Ja, wenn du deine Eidechse gut durchgebraten magst.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{Also langsam wird's Zeit. Geh' voran, mein Freund, und laß' uns die Straßen ein bißchen kehren. Meine Empfehlung ist es, Gizmo umzuhauen.}
{169}{}{Also langsam wird's Zeit. Geh' voran, meine Liebe, und laß' uns die Straßen ein bißchen kehren. Meine Empfehlung ist es, Gizmo umzuhauen.}

{170}{}{Ja?}
{171}{}{Ich glaube, wir sollten trotzdem zusammenhalten.}
{172}{}{Nichts. Vergiß es.}
{173}{}{Du erhältst 300 Erfahrungspunkte für die Rekrutierung von Tycho, einem Wüsten-Ranger.}

# for Fallout Fixt:
{174}{}{Wir freunde?}

# TODO: TRANSLATE
{175}{}{You're going down}
{176}{}{Time for payback.}
{177}{}{Junktown's citizens will be avenged!}
{178}{}{Do you think you're above the law?}
{179}{}{I don't approve of scum like you}
{180}{}{All actions have consequences.}

{181}{}{Du siehst: Tycho.}

# Healing
{300}{}{I'm all set.}
{301}{}{Got nothing that'll slow us down.}
{302}{}{You got anything to help?}
{303}{}{Maybe you should have a look at this.}

# Pushing
{310}{}{I'm moving.}
{311}{}{If you say so.}
{312}{}{That's better?}
{313}{}{Relax, be happy.}

#
# Tycho tell-me-abouts
#

{1000}{}{Junktown}
{1001}{}{Ranger}
{1002}{}{Chip}
{1003}{}{Krieg}
{1004}{}{Ödland}
{1005}{}{Follower}
{1006}{}{Cathedral}
{1007}{}{Garl}
{1008}{}{Meister}
{1009}{}{Einheit}
{1010}{}{Set}
{1011}{}{Wasserstelle}
{1012}{}{Necropolis}
{1013}{}{Halle}
{1014}{}{Bibliothek}
{1015}{}{Aufseher}
{1016}{}{Sanitäter}
{1017}{}{Heilen}
{1018}{}{Vault}
{1019}{}{Vault-13}
{1020}{}{Vault13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Boneyard}
{1024}{}{Shady}
{1025}{}{Sands}
{1026}{}{Hub}
{1027}{}{Kasino}
{1028}{}{Laden}
{1029}{}{Deathclaw}
{1030}{}{Exodus}
{1031}{}{Neulinge}
{1032}{}{Paladins}
{1033}{}{Scribes}
{1034}{}{Children}
{1036}{}{Brotherhood}
{1037}{}{Container}
{1038}{}{Militär}
{1039}{}{Stützpunkt}
{1041}{}{Apocalypse}
{1042}{}{Mutanten}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Alkohol}
{1052}{}{Präparat}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulatoren}
{1058}{}{Scavengers}
{1059}{}{Blades}
{1060}{}{Nicole}
{1061}{}{Leutnant}
{1062}{}{Hellseher}
{1063}{}{Experimente}
{1064}{}{Polizei}
{1065}{}{Merchants}

{1100}{}{Also, Junktown ist nicht gerade mein Zuhause, aber trotzdem eine interessante Stadt. Sie hat Potential, obwohl ich mir nicht sicher bin, ob es die beste Methode ist, die Zukunft aus dem Müll der Vergangenheit zu erbauen.}
{1101}{}{Wir Rangers kommen aus einem Gebiet im Osten, das einmal Nevada hieß. Wir stammen von
 den Texas Rangers ab. Wir haben Überlebens- und Kampffähigkeiten, mit denen  wir draußen überleben und die Dinge zum Guten wenden können.} 
{1102}{}{Ich habe schon lange kein Relikt der alten Technologie wie einen Steuerchip gesehen. Meiner Meinung nach ist es besser, wenn man sich auf sich selbst verläßt und nicht auf ein Stück Technologie, das man nicht reparieren kann.}
{1103}{}{Der Krieg war ein Zeugnis für die Gier und den Wahnsinn des Menschen. Hoffen wir, daß wir genug gelernt haben, um eine solche Dummheit nie wieder zu begehen.}
{1104}{}{Das Ödland ist feindlich und gefährlich, selbst für den vorsichtig Reisenden. Strahlung und seltsame Kreaturen fordern ihren Tribut. Paß' auf und denke daran, das alles, was du siehst und hörst, ein Hinweis ist.}
{1105}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1106}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1107}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1108}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1109}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1110}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1111}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1112}{}{Die Stadt des Todes hat einen zutreffenden Namen. Sie liegt dort, wo einmal die kleine Stadt Bakersfield war. Nun ist es das Zuhause von Ghuls und schlimmeren Kreaturen.}
{1113}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1114}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1115}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1116}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1117}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1118}{}{Ich habe von den großen, unterirdischen Vaults gehört. Ich weiß jedoch nicht viel darüber.}
{1119}{}{Ich habe von den großen, unterirdischen Vaults gehört. Ich weiß jedoch nicht viel darüber.}
{1120}{}{Ich habe von den großen, unterirdischen Vaults gehört. Ich weiß jedoch nicht viel darüber.}
{1121}{}{Killian ist ein guter Mann mit einem schweren Job.}
{1122}{}{Gizmo ist . . ., also, er scheint mir ein Verbrecher zu sein. Er wird seinen Lohn schon kriegen.}
{1123}{}{Der Boneyard? Man hat mir gesagt, daß es ein Ort in der Nähe der Küste ist, wo es Gangs gibt und das Leben hart ist.}
{1124}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1125}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1126}{}{Der Hub ist eine riesige Gemeinde, die Handel treibt und nicht weit südlich von Junktown liegt.}
{1127}{}{Gizmos Kasino ist wahrscheinlich so das letzte, wo ich hingehen würde, es sei denn, um mich um Gizmo zu kümmern. Wenn du verstehst was ich meine.}
{1128}{}{Killian hat einen ordentlichen Laden in Junktown.}
{1129}{}{Habe ein paar Geschichten über etwas gehört, daß schneller, größer und bösartiger ist, als es je eine lebende Kreatur sein kann. Die Geschichten halten sich jedoch in Grenzen, das heißt, es überleben nur wenige. Große Klauen, grausame Art.}
{1130}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1131}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1132}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1133}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1134}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1136}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1137}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1138}{}{Ich weiß, daß das Militär mehrere geheime Stützpunkte hatte. Wo genau, weiß ich nicht.}
{1139}{}{Ich weiß, daß das Militär mehrere verstreute geheime Stützpunkte hatte. Wo genau, weiß ich nicht.}
{1141}{}{Die nukleare Katastrophe war ein Ergebnis von Stolz und Dummheit. Jetzt zahlen wir den Preis dafür.}
{1142}{}{Sicherlich gibt es da draußen ein paar seltsame Dinge. Ich habe  mutierte Skorpione gesehen und Kühe. Außerdem soll Necropolis das Zuhause von Ghuls sein. Sie sehen zwar menschlich aus, sind aber ganz anders.}
{1143}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1144}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1145}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1146}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1147}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1148}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1149}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1150}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1151}{}{Ich bevorzuge ein starkes Bier oder vielleicht eine Nuka-Cola.}
{1152}{}{Ich würde mich davon fernhalten. Sicherlich können sie dir helfen, aber das Ganze hat seinen Preis.}
{1153}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1154}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1155}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1156}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1157}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1158}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1159}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1160}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1161}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1162}{}{Du meinst Telepathie? Heh . . . mal im Ernst, ich glaub' nicht daran.}
{1163}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1164}{}{Tut mir leid, da kann ich dir nicht weiterhelfen.}
{1165}{}{Einige Händler vom Hub besuchen regelmäßig Junktown und einige andere Städte.}


# TODO: TRANSLATE
{1999}{}{I feel more powerful now!}
{2000}{}{Let's discuss our combat tactics.}
{2001}{}{Yes?}
{2010}{}{Draw your best weapon.}
{2011}{}{Change your armor.}
{2012}{}{Prefer ranged combat against close.}
{2013}{}{Prefer close combat against ranged.}
{2014}{}{Choose distance on your own.}
{2015}{}{That's all for now.}
{2100}{}{All right.}
{2101}{}{Sure thing.}
{2102}{}{Well it's about time.}

# Any recommendations? NEW
{2200}{}{I'd recommend knocking over Gizmo, if I may.}

# Too many party members
{2500}{}{Thinking about it, you know what? I don't like the idea of travelling in a big squad like that. A smaller team and I'm with you.}
{2510}{}{Alright.}
{2511}{}{[Done]}
