{100}{}{Du benutzt den Türcomputer. Dein Zugriffscode wird vom Computer nicht erkannt.}
{101}{}{Du benutzt den Türcomputer. Ein Lautsprecher schaltet sich mit einem Rauschen ein.}
{102}{}{Tut uns leid, wir können dich momentan nicht hereinlassen. Uh, technische Probleme. Versuch's später noch mal.}
{103}{}{Du siehst den Eingangscomputer der Tür zu Vault-13.}

# TODO: TRANSLATE
#
# Cast out:
#
{104}{}{Wir sind dankbar, daß du uns gerettet hast, aber wir können dich nicht wieder herein lassen.}
{105}{}{Es tut uns leid, aber du kannst nicht wieder zurück. Wir wünschen dir alles Gute.}
{106}{}{Der Aufseher hat gesprochen, du mußt gehen!}
{107}{}{Schau, viele von uns sind empört über die Entscheidung des Aufsehers, aber wir müssen seinen Wünschen nachkommen.}
{108}{}{Du mußt von nun an dein Glück in der Außenwelt suchen. Viel Glück, mein Freund.}
#
# Killed Overseer:
#
{109}{}{Du bist eine Gefahr für die Zukunft dieser Vault! Laß uns in Ruhe!}
{110}{}{Du bist hier nicht mehr willkommen! HAU AB!}
{111}{}{Wir erlauben keine Mörder in der Vault! Geh weg!}
{112}{}{Wir fürchten uns vor dem was du geworden bist, und was du uns antun könntest. Geh Bitte.}
{113}{}{Glaubst du wirklich, daß wir dich nach dem, was du dem Aufseher angetan hast, wieder zurücklassen werden?}
{114}{}{Wie konntest du uns nur auf diese Weise betrügen?!}
{115}{}{VERSCHWINDE, DU WAHNSINNIGER!}
#
#
# Fallout Fixt:
#
#
{116}{}{Der Computer explodiert in einem spektakulären Regen aus Funken und Einzelteilen. Das ganze System ist komplett kurzgeschlossen.}
{117}{}{Du siehst den zerstörten Eingangscomputer der Tür zu Vault-13.}
{118}{}{Er ist komplett zerstört und eine Reperatur ist hoffnungslos.}
#Spaces at beginning of 119 and 120 and end of 121/122 are intentional
{119}{}{ Die Tür wird sich nie wieder schliessen.}
{120}{}{ Die Tür wird sich nie wieder öffnen.}
{121}{}{Direkter Treffer! }
{122}{}{Oh-oh! }
{123}{}{Der Computer ist unbrauchbar.}
{124}{}{Mit der Tür für immer versiegelt und keinem Steuerchip in Ersatz, werden die Einwohner von Vault-13 bald lernen, das ihr sicherer Bunker zu einer Grabkammer geworden ist.}
