{100}{}{Du siehst einen Bewohner der Vault 13.}
{101}{}{Wie ist es denn da draußen?}
{102}{}{Du mußt aber mutig sein, daß du dich aus der Vault rauswagst.}
{103}{}{Der Aufseher sagt, daß es da draußen gefährlich ist.}
{104}{}{Sei auf der Hut, wenn du außerhalb der Vault bist.}
{105}{}{Vergiß nicht, den Sanitäter aufzusuchen, wenn du verletzt bist.}
{106}{}{Der Aufseher sorgt dafür, daß es allen in der Vault gut geht.}
