{100}{}{Du siehst Vasquez, einen Söldner-Desperado.}
{101}{}{Du siehst einen verwahrlosten Revolverhelden.}
{102}{}{Was willst du?}
{103}{}{Wer bist du?}
{104}{}{Hnn.}
{105}{}{Ich arbeite nicht für die Geisteskranken. Geh' jetzt.}
{106}{}{Hat man dir noch nicht von mir erzählt? Ich bin Vasquez Villanova Hernandez Ortega. Ich bin ein berühmter Desperado, mein Freund. Und bei Bedarf kann man mich mieten.}
{107}{}{Wirklich? Was ist dein Preis?}
{108}{}{Man sieht sich, vielleicht . . .viel Glück. Hey.}
{109}{}{Ahh, du kommst gleich zur Sache, mein Freund. Hervorragend. Ich helfe dir für magere 500 Deckel die Woche, dich in der Stadt zurechtzufinden. Meine Dienste sind nicht billig, aber ich bin es wert.}
{110}{}{Großartig. Ich stell' dich an. Hier sind 500 Deckel.}
{111}{}{Entschuldige die Störung, aber ich benötige deine Dienste nicht.}
{112}{}{Tut mir leid, mein Freund, aber ich arbeite nicht für imaginäres Geld. Ich brauche Bargeld.}
{113}{}{Super. Du hast mich überzeugt. Gehen wir, dieser Ort langweilt mich.}
{114}{}{Geh' voraus, dein Wunsch ist mir Befehl.}
{115}{}{Lass' uns erst was trinken!}
{116}{}{Wo sollen wir zuerst hingehen?}
{117}{}{So lange du in Junktown bleibst, bin ich für dich da. Ich verlass' diese Stadt nicht gern.}
{118}{}{Hast du gewusst, dass auf meinen Kopf eine Belohnung ausgesetzt ist? Aber nur eine ganz kleine.}
{119}{}{Ah, mein Freund. Schön, dich wiederzusehen.}
{120}{}{Ich möchte dich für eine Woche anstellen.}
{121}{}{Schön, dich wiederzusehen.}
{122}{}{Hnn.}
{123}{}{Naja, vielleicht ist es doch nicht schön, dich wiederzusehen. Schönen Tag noch.}
{124}{}{Gewiss. Meine Rechnung ist klein, mein Wert ist so groß. 500 Deckel bitte.}
{125}{}{Hier bitte.}
{126}{}{Das hättest du nicht tun sollen, mein bald toter Freund.}
