{100}{}{Du bemerkst ein Schild an der Tür, auf dem steht, daß der Aufzug außer Betrieb ist.}
{101}{}{Du siehst ein Schild an der Tür, auf dem steht, daß dieser Aufzug außer Betrieb ist.}
{102}{}{Auf einem Schild steht: Warnung: Bauarbeiten im Aufzugschacht. Bitte anderen Aufzug benutzen.}
