{100}{}{Du siehst den Container-Steuercomputer.}
{101}{}{Zugriff verweigert.}
{102}{}{Zugriff erlaubt. Befehl?}
{103}{}{Sicherheitscodes anzeigen.}
{104}{}{Protokolle durchsuchen.}
{105}{}{Verbindung zu medizinischen Computern herstellen.}
{106}{}{Basis in Alarmzustand versetzen.}
{107}{}{17652-1028-1285362}
{108}{}{67209-5574-7805564}
{109}{}{55658-8678-1251533}
{110}{}{31914-1041-1251514}
{111}{}{53478-2565-7763929}
{112}{}{44309-3674-1254730}
{113}{}{[Versuche, die Firewall zu durchbrechen, um weitere Daten zu erhalten] Verschlüsselungstabelle für Sicherheitscode anzeigen.}
{114}{}{17652-1028-1285362 wird ausgeführt}
{115}{}{67209-5574-7805564 wird ausgeführt}
{116}{}{55658-8678-1251533 wird ausgeführt}
{117}{}{31914-1041-1251514 wird ausgeführt}
{118}{}{53478-2565-7763929 wird ausgeführt}
{119}{}{44309-3674-1254730 wird ausgeführt}
{120}{}{[Du hast die Verschlüsselungstabelle erfolgreich geknackt] Befehl?}
{121}{}{17652-1028-1285362 Stumme Selbstzerstörungssequenz mit Dauer 1 Minute einleiten.}
{122}{}{67209-5574-7805564 Selbstzerstörungssequenz mit Dauer 30 Sekunden einleiten und Basis in Alarmzustand versetzen.}
{123}{}{55658-8678-1251533 Basis in Alarmzustand versetzen}
{124}{}{31914-1041-1251514 Stumme Selbstzerstörungssequenz mit Dauer 3 Minuten einleiten}
{125}{}{53478-2565-7763929 Selbstzerstörungssequenz mit Dauer 3 Minuten einleiten und Basis in Alarmzustand versetzen.}
{126}{}{44309-3674-1254730 sofortige Selbstzerstörung}
{127}{}{Ungültiger Befehl. Eingabesitzung wird beendet.}
{128}{}{Anzuzeigendes Protokoll angeben.}
{129}{}{Grey}
{130}{}{Boyarsky}
{131}{}{Maxson}
{132}{}{Anderson}
{133}{}{Protokoll von Richard Grey herunterladen?}
{134}{}{Ja.}
{135}{}{Zurück zum Hauptmenü.}
{136}{}{Protokoll von Capt. Maxson herunterladen?}
{137}{}{Ja.}
{138}{}{Zurück zum Hauptmenü.}
{139}{}{Unerwartetes Zeilenende. Fehlerhafte Daten aufgetreten. Befehl?}
{140}{}{Befehl?}
{141}{}{Verbindung erfolgreich hergestelllt. Befehl?}
{142}{}{Wie lautet der aktuelle Status der Patienten?}
{143}{}{Aktueller Status der Patienten wie folgt: FEV-Batch #23872-A besteht aus zwei männlichen und zwei weiblichen Einheiten. Alle Individuen leiden an FEV-Aussetzung. Vitalfunktionen innerhalb normaler Parameter. FEV-Prozeß bei allen Subjekten ungefähr zu 50% abgeschlossen. Erwarte vollständige FEV-Transformation innerhalb 12 Stunden.}
{144}{}{Ich glaube, irgend etwas passiert mit einem der Patienten. Kann ich etwas tun?}
{145}{}{Patient leidet an Arrhythmie. Statusprotokolle des Patienten anzeigen.}
{146}{}{Verfügbare Optionen:}
{147}{}{Statusbericht zu einzelnen Patienten.}
{148}{}{Lebenserhaltende Systeme abschalten.}
{149}{}{Dosis der ursprünglichen DNA-Stränge von Subjekten auf 100% erhöhen.}
{150}{}{Abmelden.}
{151}{}{Bitte Autorisierungscode eingeben.}
{152}{}{Autorisierung 3578X287A.}
{153}{}{Z876342BCD}
{154}{}{Alpha Delta 287 Foxtrot}
{155}{}{[Versuche, in das Computersystem zu hacken]}
{156}{}{Ungültiger Autorisierungscode. Befehl?}
{157}{}{Autorisierungscode bestätigt. Bitte warten. Daten werden aufgerufen. Bereit für Anfrageverarbeitung.}
{158}{}{Lebenserhaltende Systeme von FEV-Batch #23872-A terminieren.}
{159}{}{Dosis der ursprünglichen DNA-Stränge bei allen Subjekten um 100% erhöhen.}
{160}{}{Zugriff erlaubt. Welche Patientendatei soll angezeigt werden?}
{161}{}{Patientendatei #23869.}
{162}{}{Patientendatei #23870.}
{163}{}{Patientendatei #23871.}
{164}{}{Patientendatei #23872.}
{165}{}{Patientendatei #23869. Subjekt: Männlich. Alter 25. Strahlungswert: 40. FEV-Aussetzung: 50%. Verbleibende ursprüngliche DNA-Stränge: 50%. Vitalfunktionen hoch, aber innerhalb normaler Parameter.}
{166}{}{Ich möchte eine weitere Patientendatei untersuchen.}
{167}{}{Patientendatei #23870. Subjekt: Männlich. Alter 23. Strahlungswert: 15. FEV-Aussetzung: 60%. Verbleibende ursprüngliche DNA-Stränge: 40%. Vitalfunktionen innerhalb
 normaler Parameter.}
{168}{}{Patientendatei #23781. Subjekt: Weiblich. Alter 20. Strahlungswert: 10. FEV-Aussetzung: 55%. Verbleibende ursprüngliche DNA-Stränge: 45%. Vitalfunktionen innerhalb
 normaler Parameter.}
{169}{}{Patientendatei #23782. Subjekt: Männlich. Alter 26. Strahlungswert: 35. FEV-Aussetzung: 60%. Verbleibende ursprüngliche DNA-Stränge: 40%. Vitalfunktionen über normal, aber innerhalb akzeptabler Parameter.}
{170}{}{Wollen Sie die lebenserhaltenden Systeme von FEV-Batch #23872-A wirklich terminieren?}
{171}{}{FEV-Batch #23872-A terminiert. Befehl?}
{172}{}{Ja.}
{173}{}{Nein.}
{174}{}{Wollen Sie die Dosis wirklich erhöhen? Autokorrektur wird in diesem Fall deaktiviert.}
{175}{}{Ursprüngliche DNA-Dosis wird auf 100% erhöht. ACHTUNG: Autokorrektur wurde
 deaktiviert.}
{176}{}{Dir gelingt es, eine Benutzeroberfläche für den Container-Steuercomputer zu bekommen.}
{177}{}{Du versuchst zwar, den Computer zu benutzen, aber dir gelingt es nicht, irgendwelche nützliche Informationen aus ihm herauszubekommen.}
{178}{}{Du versuchst zwar, den Computer zu benutzen, aber das System ist zu komplex für dich, um es leicht verstehen zu können. Du mußt es weiter versuchen.}
{179}{}{Die Explosion zerstört das Container-Steuersystem. Ohne Regulierung wird es mit Sicherheit in wenigen Minuten außer Kontrolle geraten.}
{180}{}{Du ziehst einen Sicherheitsausweis durch das Lesegerät des Terminals. Der Terminal klickt und schnurrt. Dann erscheint ein unverschlüsselter Bildschirm.}
{181}{}{[System beenden]}
{182}{}{Basis in Alarmzustand versetzen und Terminal deaktivieren.}
{183}{}{10710-8971-2014510 Basis in Alarmzustand versetzen und Terminal deaktivieren.}
{184}{}{31914-1041-1251514 Stumme Selbstzerstörungssequenz mit Dauer 5 Minuten einleiten.}
{185}{}{10710-8971-2014510}
{186}{}{76223-4533-2540092}
{187}{}{76223-4533-2540092 Selbstzerstörungssequenz mit Dauer 1 Minute einleiten.}
{188}{}{76223-4533-2540092 wird ausgeführt}
{189}{}{Die Explosion zerstört den Container-Kontrollcomputer.}
#
{200}{}{Du bemerkst, daß die Wartungsblende entfernt wurde und die zerbrechlichen Computerkomponenten frei liegen.}
{201}{}{Alarmzustand der Basis beenden.}
{202}{}{Befehl erfolgreich ausgeführt.}
{203}{}{[Weiter]}
{204}{}{[zurück zum Hauptmenü] Schon gut.}
{205}{}{536475-69-62656B wird ausgeführt... ... Befehl erfolgreich ausgeführt.}
{206}{}{10710-8971-2014510 wird ausgeführt}
{207}{}{FEHLER: Datei im PIPBoy 2000 gefunden. Ladevorgang abgebrochen.}
{208}{}{[zurück zum Hauptmenü] Schon gut.}
#
{300}{}{10810-1103-9799121}
{301}{}{10810-1103-9799121 Selbstzerstörungssequenz mit Dauer 5 Minuten einleiten.}
{302}{}{10810-1103-9799121 wird ausgeführt}
{303}{}{83100-1171-0539115}
{304}{}{[83100-1171-0539115] Stumme Selbstzerstörungssequenz mit Dauer 10 Minuten einleiten.}
{305}{}{83100-1171-0539115 wird ausgeführt}