{100}{}{Sieht aus wie die Tür zum Container-Kontrollraum.}
{101}{}{Die Tür hat ein elektronisches Schloß.}
{102}{}{Du schließt die Tür auf.}
{103}{}{Du versuchst es mit einen Kurzschluß im elektronischen Schloß, aber es bleibt verschlossen. Das war's dann wohl.}
{104}{}{Die Tür ist bereits geöffnet.}
{105}{}{Pech. Hier benötigst du die elektronischen Dietriche.}
{106}{}{Du machst am Schloß herum, kannst aber den Code noch nicht umgehen. Du mußt es weiter versuchen.}
