{100}{}{Du siehst Victor.}
{101}{}{Du siehst ein Gang-Mitglied.}
{102}{}{Aaaaggghhh . . .}
{103}{}{Frisches Blut. Heh. Heh heh.}
{104}{}{Hmmm, ja. Uh, ich glaube, ich geh' jetzt.}
{105}{}{Du bist nicht gerade ein fröhlicher Mensch, nicht wahr?}
{106}{}{Huh huh!}
{107}{}{Nein, ich glaub', ich laß' dich noch ein bißchen am Leben.}
{108}{}{Warum sagst du das? Ich bin ziemlich fröhlich. Ich bin sehr fröhlich, weil es nämlich viele Dinge gibt, die bluten.}
{109}{}{Du bist ziemlich krank im Kopf, weißt du das?}
{110}{}{Hmm, ja. Auf Wiedersehen.}
{111}{}{Ah, ja, ein Kunstverständiger. Uh, ich kann das verstehen. Glaub' ich zumindest.}
{112}{}{Sag' das nicht! Meine Mutter hat das gesagt! Du wirst dafür bezahlen! Ich bin ein guter Junge, nicht wahr, Mammi?}
{113}{}{Endlich jemand, der mich versteht!}
{114}{}{Hallo noch mal, mein kunstverständiger Freund.}
{115}{}{Ha! Ha! Heh heh hee! Ho ho ha!}
{116}{}{Zzzzz}
{117}{}{Victor, hab' ich dir jemals gesagt, daß du wirklich sehr krank im Kopf bist?}
{118}{}{Uh, hi.}