{100}{}{Das ist die Disk mit Vrees Autopsiebericht.}
{101}{}{PipBoy zeigt an: Datei im System gefunden. Download abgebrochen.}
{102}{}{PipBoy zeigt an: Daten werden von Disk geladen.}

# TODO: TRANSLATE
{103}{}{Diese Holodisk enthält medizinische Beweise von Scribe Vree von der Brotherhood of Steel, die belegen, dass Supermutanten steril sind.}
#
# for Fallout Fixt:
#
{104}{}{Du siehst: Vree's Autopsie Report.}
