{100}{}{Du siehst durcheinander aus. Brauchst du Hilfe?} 
{101}{}{Ich brauche Heilung.}
{102}{}{Urrr.}
{103}{}{Mein Mann Razlo kann dir helfen . . . frag' ihn.}
{104}{}{Tut mir leid, aber ich versteh' dich nicht.}
{105}{}{Du mußt morgen früh wieder kommen. Laß' uns bitte in Ruhe schlafen.}
{106}{}{Nein danke.}
{107}{}{Nein, ich brauche keine Hilfe.}
