{100}{}{Da ist was ganz faul.}
{101}{}{Es geht schon wieder los.}
{102}{}{Der Zündmechanismus klemmt immer.}
{103}{}{Das ist schon viel besser.}
{104}{}{Hab's fast geschafft.}
{105}{}{Das wird einige Zeit dauern.}
{106}{}{Hier haben wir das Problem!}
{107}{}{John, ich glaube, ich habe das Problem gefunden.}
{108}{}{Verdammt!}
{109}{}{Verflucht!}
{110}{}{Mein Fehler!}
{111}{}{Ich bin OK.}
{112}{}{Okay, das hat weh getan.}
{113}{}{Ich wollte das tun.}
{114}{}{Warum passiert das immer?}
{115}{}{Meine Augen!}
{116}{}{Du bist kein Knight.}
{117}{}{Ich muss mit einem Knight sprechen.}
{118}{}{Das versteh' ich nicht, die Energiezellen setzen immer wieder aus.}
{119}{}{Bleib' zurück. Die können gefährlich sein.}
{120}{}{Lenk' mich bitte nicht ab.}
{121}{}{Pass' auf, wo du stehst.}
{122}{}{Hast du dich verirrt?}
{123}{}{Tut mir leid, ich kann momentan nicht sprechen.}
