{100}{}{Du siehst Zack.}
{101}{}{Du siehst einen Gunrunner.}
{102}{}{Hallo, ich bin Zack. Willst du Waffen kaufen? Zeig' mir, was du zu tauschen hast.}
{103}{}{Nein.}
{104}{}{OK.}
{105}{}{Bekomme ich einen Rabatt?}
{106}{}{Willst du Waffen kaufen? Zeig' mir, was du zu tauschen hast.}
{107}{}{Entschuldige bitte die Störung.}
{108}{}{Freut mich, mit dir Geschäfte zu machen.}
{109}{}{}
{110}{}{OK. Komm' zurück, wenn du irgendetwas brauchst.}
{111}{}{Du solltest dich lieber schnell entscheiden. Bist du hergekommen, um Ausrüstung zu kaufen oder um erschossen zu werden?}
{112}{}{Du hast ein echtes Problem mit deinen Ansichten.}
{113}{}{Tut mir leid, vielleicht kann ich doch etwas Gerät brauchen.}
{114}{}{Was zum Teufel machst du dann hier?}
{115}{}{Nichts.}
{116}{}{Sicher.}
{117}{}{Also, bis Gabriel was sagt, musst du, wie alle, den vollen Preis zahlen.}
{118}{}{Da bin ich mir nicht sicher.}
{119}{}{Zeig' mir trotzdem, was du hast.}
{120}{}{Toll! Zeig' mir, was du hast.}
{121}{}{Ich komme später wegen des Rabatts.}
{122}{}{Bekomm' ich ein besseren Rabatt?}
{123}{}{Tut mir leid, aber ich hab' dir bereits den besten Rabatt gegeben.}
