{100}{}{Du siehst Zack.}
{101}{}{Du siehst einen Gunrunner.}
{102}{}{Hallo, ich bin Zack. Willst du Waffen kaufen? Zeig' mir, was du zu tauschen hast.}
{103}{}{Nein.}
{104}{}{OK.}
{105}{}{Bekomme ich einen Rabatt?}
{106}{}{Willst du Waffen kaufen? Zeig' mir, was du zu tauschen hast.}
{107}{}{Entschuldige bitte die Störung.}
{108}{}{Freut mich, mit dir Geschäfte zu machen.}
{109}{}{}
{110}{}{OK. Komm' zurück, wenn du irgendetwas brauchst.}
{111}{}{Du solltest dich lieber schnell entscheiden. Bist du hergekommen, um Ausrüstung zu kaufen oder um erschossen zu werden?}
{112}{}{Du hast ein echtes Problem mit deinen Ansichten.}
{113}{}{Tut mir leid, vielleicht kann ich doch etwas Gerät brauchen.}
{114}{}{Was zum Teufel machst du dann hier?}
{115}{}{Nichts.}
{116}{}{Sicher.}
{117}{}{Also, bis Gabriel was sagt, musst du, wie alle, den vollen Preis zahlen.}
{118}{}{Da bin ich mir nicht sicher.}
{119}{}{Zeig' mir trotzdem, was du hast.}
{120}{}{Toll! Zeig' mir, was du hast.}
{121}{}{Ich komme später wegen des Rabatts.}
{122}{}{Bekomm' ich ein besseren Rabatt?}
{123}{}{Tut mir leid, aber ich hab' dir bereits den besten Rabatt gegeben.}

# Fo1in2
   {998}{}{Zack, your gear is top quality, but I am looking for something *even more* special.}
   {999}{}{Can we talk about the *even more* special gear again?}
   
{1000}{}{Sorry, but that's all I got right now.}
{1001}{}{Could try to get our hands on better materials again, now that the Deathclaws don't bother us anymore. It'll take a while, though.}
   {1010}{}{Anything you need help with?}
   
{1100}{}{Paying new scavs will cost. If you want to speed up the process ... an investment of 10.000 caps would probably help.}
   {1110}{}{I don't have that kind of money.}
   {1120}{}{Really hope it'll be worth it, Zack! [Pay 10.000 caps]}
   {1130}{}{Uff. Maybe later.}

{1200}{}{Come back if you have that kind of money.}
{1300}{}{Can't promise anything. You'll have to check back from time to time, because this kind of inventory usually sells fast.}
{1400}{}{Okay.}
