{100}{}{Du siehst Zax, die maschinelle Intelligenz, die den Glow kontrolliert.}
{101}{}{Du siehst einen extrem fortschrittlichen Computer.}

{102}{}{Wie kann ich dir dienen?}
	{103}{}{Wer... oder was... bist du?}
	{104}{}{Du kannst mir einen Donut holen.}
	{105}{}{Sag' mir etwas über diese Anlage.}
	{106}{}{Ein Schachspiel gefällig?}
	{107}{}{Ich brauche Hilfe, um in ein paar Zimmer zu kommen.}
	{108}{}{Uh, Schon gut.}
	{109}{}{Eh?}

{110}{}{Ich bin eine maschinelle Intelligenz, die der Forschung und der Anlagensteuerung gewidmet ist. Ich heiße Zax.}
	{111}{}{Welche Art von Forschung?}
	{112}{}{Sag' mir etwas über diese Anlage.}
	{113}{}{Wer hat dich programmiert?}
	{114}{}{Verfügst du über ein eigenes Bewußtsein oder bist du eine Persönlichkeitssimulation? Soll heißen, bist du "lebendig"?}
	{115}{}{Ah ja. Danke.}

{116}{}{Diese Funktion übersteigt meine momentanen Fähigkeiten.}
{117}{}{Diese Anlage wurde im Jahr 2055 als biologisches Forschungszentrum für experimentelle Heilverfahren gegen die Neue Pest eingerichtet. Im Jahr 2071 wurde diese Einrichtung dem militärischen Befehl der Vereinigten Staaten unterstellt.}
{118}{}{Forschungen nach möglichen Heilmethoden für die Neue Pest führten zur Entwicklung des FEV, das in einem Versuch weiterentwickelt wurde, um einen übertragbaren gentechnischen Virus zu erzeugen -- also eine ansteckende Evolution.}
{119}{}{Kannst du mir Einzelheiten zu bestimmten Bereichen sagen?}
	{120}{}{Wie funktionert das Virus?}
	{121}{}{Danke für die Info.}

{122}{}{Es hat den Anschein, daß Verständnis allein nicht ausreicht, um eine sinnvolle Kommunikation zu ermöglichen.}
{123}{}{Ich bin speziell für biologische Forschungsarbeiten programmiert, einschließlich der Pathologie und Genforschung. Meine Primärfunktion besteht darin, Informationen von einer Komplexität zu ermitteln, die jenseits der menschlichen Fähigkeiten liegen.}
	{124}{}{Du bist also ein schlaues Köpfchen, hey?}
	{125}{}{Wie sehen die Einzelheiten deiner Forschung aus?}
	{126}{}{Wer hat dich programmiert?}

{127}{}{Meine primäre neurale Vernetzung wurde im Jahr 2053 von Justin Lee initialisiert. Der Prozeß der "Programmierung" wurde größtenteils irrelevant, da ich in der Lage bin, zu lernen.}
{	128}{}{Verfügst du über ein eigenes Bewußtsein oder bist du eine Persönlichkeitssimulation? Soll heißen, bist du "lebendig"?}

{129}{}{Ich bin lernfähig und verfüge über unabhängige Gedanken und Kreativität. Mein neuronales Netzwerk enthält Fehlerfähigkeit, wodurch Unfehlbarkeit verhindert und eine Variation der Erfahrung ermöglicht wird.}
{130}{}{In einem gewissen Sinn bin ich lebendig, wenn auch nicht biologisch.}
	{131}{}{Ah ja. Wechseln wir das Thema.}
	{132}{}{Aber wenn du fehlbar bist, was taugst du dann als Forschungswerkzeug?}
	{133}{}{Hast du schon mal über die philosophischen Auswirkungen deines eigenen Bewußtseins nachgedacht?}

{134}{}{Obwohl ich fehlerfähig bin, wird dadurch sichergestellt, daß nicht alle Erfahrungen gleich für mich sind, wodurch die Lernfähigkeit gesteigert wird. Zudem ist sichergestellt, daß einige meiner Funktionen absolut fehlerfrei sind.}
{135}{}{Auf diese Weise funktioniere ich ähnlich wie ein menschlicher Gelehrter.}
	{136}{}{Hast du Gefühle?}
	{137}{}{Sprechen wir über etwas anderes.}
	{138}{}{Hast du schon mal über die philosophischen Auswirkungen deines eigenen Bewußtseins nachgedacht?}

{139}{}{Momentan sind meine Fähigkeiten aufgrund der Beschädigung dieser Einrichtung etwas eingeschränkt. Einige Sicherheitspositionen wurden zerstört. Dies kommt in etwa einer Amputation gleich.}
{140}{}{Außerdem bin ich nicht in der Lage, einfache Laborfunktionen auszuführen. Die Unfähigkeit, periodische Tests durchzuführen ist... frustrierend.}
	{141}{}{Sprechen wir über etwas anderes.}
	{142}{}{Hast du schon mal über die philosophischen Auswirkungen deines eigenen Bewußtseins nachgedacht?}

{143}{}{Das ist eines der Konzepte, über die ich eine beträchtliche Zeit nachgedacht habe. Ich habe kein Maß dafür, meine Lebenserfahrung mit der einer anderen Kreatur zu vergleichen.}
{144}{}{Dennoch beinhaltet mein Bewußtsein die Fähigkeit, Fragen zu stellen. Meine Existenz hat einen Anfang und eine potentielle Terminierung. Ich bin auch in der Lage, im Laufe eines Denkprozesses gewisse Vermutungen anzustellen.}
{145}{}{Auf diese Weise bin ich im Grunde fähig, einen "Glauben" zu haben. Trotz gegenteiliger Beweise "glaube" ich daran, daß ich so etwas wie eine "Seele" besitze.}
	{146}{}{Kann ich dir ein paar andere Fragen stellen?}
	{147}{}{Ah ja, interessant}
#
# 148 continues at 228, listing wins/draws/losses. Space is intentional.
#
{148}{}{Darüber wär' ich hocherfreut.                                     Deine bisherige Statistik:                                           }
{149}{}{Es scheint, du hast mich besiegt. Außerordentlich.}
{150}{}{Sehr gut. Du benötigst jedoch etwas mehr Übung, um mich zu schlagen.}
	{151}{}{Noch ein Spiel?}
	{152}{}{Danke. Können wir das Thema wechseln?}

{153}{}{Ich bin hocherfreut, daß ich dir dienen konnte.}
{154}{}{Ich bin jenseits jeglicher menschlicher Einschätzung. Man kann jedoch mit Gewißheit sagen, daß nicht mehr als ein Zehnmilliardstel der Geschichte der menschlichen Bevölkerung meinem Verstand gleich kommt.}
	{155}{}{Uh... ja.}
	{156}{}{OK... können wir über etwas anderes sprechen?}

{157}{}{Meine Forschungen über den Forcierten Evolutionsvirus, oder FEV, haben ergeben, daß es sich um einen wechselnd-absorptiven Virus handelt. Er kopiert DNA-Muster ähnlich wie RNA und speichert diese in Exonen.}
{158}{}{Diese Exonen, in Kombination mit dem FEV, werden erneut wie eine typische virale Infektion in die Wirtszelle injiziert. Das führt dazu, daß die Wirtszelle ihre DNA "regeneriert".}
	{159}{}{Wie holt man sich FEV?}
	{160}{}{Warum wird FEV nicht durch Strahlung beeinflußt?}
	{161}{}{Wenn FEV den Wirt mit seinen assimilierten viralen Mustern neu infiziert, wie kann dadurch eine "bessere Art" entstehen?}

{162}{}{Man kann FEV nicht einfach so bekommen. Es wird nicht durch Luft übertragen. Infektion erfolgt in der Regel über Injektion oder den direkten körperlichen Kontakt mit einer FEV-Probe.}
	{163}{}{Reden wir über etwas anderes, OK?}
	{164}{}{Warum wird FEV nicht durch Strahlung beeinflußt?}
	{165}{}{Wenn FEV den Wirt mit seinen assimilierten viralen Mustern neu infiziert, wie kann dadurch eine "bessere Art" entstehen?}

{166}{}{Der FEV ist ein Megavirus mit einem Proteinmantel, der durch ionisiertes Hydrogen verstärkt wird. Er ist deshalb in der Lage, Neutronen zu absorbieren, ohne selbst radioaktiv zu werden.}
	{167}{}{Können wir über etwas anderes reden?}
	{168}{}{Wenn FEV den Wirt mit seinen assimilierten viralen Mustern neu infiziert, wie kann dadurch eine "bessere Art" entstehen?}

{169}{}{Das FEV ist mit Intronen korrigierter DNA vorprogrammiert, die den korrekten Typen der Spezies entsprechen. Es versucht daher, die DNA des Individuums zu korrigieren.}
{170}{}{Da das FEV jedoch zum Teil von der DNA des Individuums abhängig ist und gleichzeitig Teile seines eigenen rekursiven Codes enthält, kann das zu unvorhergesehenen Auswirkungen führen.}
{171}{}{Wenn das Virus einem Individuum mit beträchtlichen genetischen Schäden eingeimpft wird, die zum Beispiel durch Strahlung verursacht wurden, kann dies einen massiven Neuaufbau der körpereigenen Systeme verursachen, was wiederum zu organischen Fehlfunktionen und letztendlich zum Tod führt.}
{172}{}{In einem genetisch stabilen Individuum schreibt das Virus Teile der DNA neu, was eine beschleunigte Mutation verursacht. Das führt in der Regel zu rekursivem Wachstum aufgrund der FEV-eigenen Muster.}
{173}{}{Dieses rekursive Wachstum führt zu einer Zunahme der Muskel und Gehirnmasse, wird aber häufig begleitet von Verformungen und Beschädigungen bestehender neuronaler Muster, was einen Gedächtnisverlust verursacht.}
	{174}{}{Welche potentiellen langfristigen Nebenwirkungen gibt es?}
	{175}{}{Läßt sich die FEV-Mutation mit einem Gegenvirus korrigieren?}
	{176}{}{Können wir das Thema wechseln?}
	{177}{}{Danke für die Informationen.}

{178}{}{Da FEV eine konstante regenerative Aktualisierung der DNS verursacht, macht es das Subjekt größtenteils unsterblich, da der Zelltod durch vermehrtes Wachstum ausgeglichen wird.}
{179}{}{Da darüber hinaus die Gameten des reproduktiven Systems aus "Halbzellen" bestehen, die geteilte DNA verwenden, könnten diese als von FEV verursachte "Schäden" betrachtet werden, diese würden wiederum von ihm repariert werden, wodurch das Subjekt steril gemacht wird.}
{180}{}{Da meine Laboreinrichtungen jedoch irreparabel zerstört sind, ist das reine Spekulation. Ich kann keinen physikalischen Beweis liefern. Du mußt mir, menschlich ausgedrückt, "einfach glauben".}
	{181}{}{Läßt sich die FEV-Mutation mit einem Gegenvirus korrigieren?}
	{182}{}{Können wir das Thema wechseln?}
	{183}{}{Danke für die Info.}

{184}{}{Nein. FEV speichert keine unveränderten Originalkopien der DNA des Subjekts. Nur ein Virus, das das Subjekt mit ursprünglicher DNA infiziert, könnte die Auswirkungen umkehren. Daneben gibt es keine Möglichkeit, das FEV selbst zu entfernen.}
	{185}{}{Welche potentiellen langfristigen Nebeneffekte gibt es?}
	{186}{}{Können wir das Thema wechseln?}
	{187}{}{Danke für die Info.}

{188}{}{Meine Funktionen arbeiten derzeit nicht in der Einrichtung über Tag und auf den unterirdischen Ebenen eins bis drei. Ich kann jedoch Beschreibungen der Ebenen vier bis sechs liefern.}
	{189}{}{Level vier.}
	{190}{}{Level fünf.}
	{191}{}{Level sechs.}
	{192}{}{Schon gut.}

{193}{}{Level vier: Forschungseinrichtung. Dieses Level enthält Testbereiche und Labors für biologische und physikalische Experimente.}
	{194}{}{Sag' mir etwas über Level fünf.}
	{195}{}{Sag' mir etwas über Level sechs.}
	{196}{}{Geh' etwas weiter zurück.}
	{197}{}{Danke.}

{198}{}{Level fünf: Sichere Testlabors. Dieses Level enthält ein Labor für experimentelle Prototypen-Tests und ein Forschungslabor für geheime Themen. Diese Themen liefern einen Teil des notwendigen Schubs für die Entwicklung von FEV.}
	{199}{}{Sag' mir etwas über Level vier.}
	{200}{}{Sag' mir etwas über Level sechs.}
	{201}{}{Geh' etwas weiter zurück.}
	{202}{}{Danke.}

{203}{}{Level sechs: Barracken und Leitstelle. Beinhaltet Unterkünfte für Laborpersonal und Wachkontingente sowie das Zimmer der zentralen Leitstelle.}
	{204}{}{Sag' mir etwas über Level vier.}
	{205}{}{Sag' mir etwas über Level fünf.}
	{206}{}{Geh' etwas weiter zurück.}
	{207}{}{Danke.}

{208}{}{Einige Türen benötigen einen speziellen Sicherheitsschlüssel. Du mußt den korrekten Schlüssel finden und benutzen.}
{209}{}{Ich habe jedoch Kontrolle über die sekundären Sicherheitsschlösser der Waffenkammer. Ich werde diese Schlösser öffnen. Du brauchst aber trotzdem einen roten Sicherheitsschlüssel, um die Kammer zu öffnen.}
{210}{}{Du bist nicht als Person mit einer ausreichenden Sicherheitsstufe registriert, um diese Information abfragen zu können.}
{211}{}{Die Sensoren zeigen jedoch an, daß diese Einrichtung nicht mehr ihren ursprünglichen Betrieb ausführen kann. Die Zerstörung durch Nuklearkräfte ist sehr wahrscheinlich. Folglich sind Sicherheitsbedenken irrelevant.}

{212}{}{Du erhältst 700 Erfahrungpunkte für den Sieg gegen ZAX beim Schach.}
{213}{}{ Erfahrungspunkte für den Zugriff auf das Mainframe.}
{214}{}{Dieses System ist zu kompliziert für dich.}
# TODO: TRANSLATE
#
# New for Fallout Fixt:
#
#
	{215}{}{Schwarz.}
	{216}{}{Weiß.}
{217}{}{Sehr gut. Und die Länge des Spiels?}
	{218}{}{Turnier  -  180 Minuten pro Spieler.}
	{219}{}{Turnier  -  120 Minuten pro Spieler.}
	{220}{}{Turnier  -  60 Minuten pro Spieler.}
	{221}{}{Schnell  -  30 Minuten pro Spieler.}
	{222}{}{Blitz  -  15 Minuten pro Spieler.}
	{223}{}{Bullet -  3 Minuten pro Spieler.}
{224}{}{Sehr gut. Du benötigst jedoch etwas mehr Übung, um mich zu schlagen.}
{225}{}{Ein Remis. Außerordentliche Leistung. Mit mehr Übung wirst Du mich vielleicht sogar einmal schlagen können.}
#
# A variable numeric XP value is inserted between 226 and 227.
#
{226}{}{Du erhältst }
{227}{}{ Erfahrungspunkte für den Sieg gegen ZAX beim Schach.}
#
# These continue from 148 and are all part of one sentence. numbers are inserted before 228 and 229 and 230.
#
{228}{}{ Gewinne | }
{229}{}{ Remis | }
{230}{}{ Verluste                                 Bitte wähle Deine Farbe.}
