# 0. QUICK LOOK
{100}{}{Du siehst einen Croupier.}
{101}{}{Du siehst einen Würfeltisch.}
# has no gambling skill messages
{110}{}{Du siehst ein Mädchen.}
{111}{}{Du siehst einen Tisch.}

# 0. EXAMINES
# table
{140}{}{Du siehst einen Tisch, an dem gewürfelt wird.}
# no skill
{141}{}{Du siehst einen Tisch, auf dem lauter Sachen liegen.}

# dealer
{150}{}{Du siehst eine der Kasino-Croupiers.}
{151}{}{Du siehst eine der Kasino-Croupiers. Sie bedeutet dir, rüberzukommen und zu spielen.}
{152}{}{Du siehst eine der Kasino-Croupiers. Ihr Kleid bedeckt ihren Körper nur unzureichend.}
{153}{}{Du siehst eine der Kasino-Croupiers. Sie hat echt schöne Beine.}
{154}{}{Du siehst eine der Kasino-Croupiers. Sie zwinkert dir zu.}
{155}{}{Du siehst eine der Kasino-Croupiers. Sie riecht umwerfend gut.}
# no skill
{160}{}{Du siehst eine schöne Frau.}
{161}{}{Sie winkt dich zu ihr.}
{162}{}{Ihr Kleid ist ziemlich kurz.}
{163}{}{Sie hat ein echt schöne Beine.}
{164}{}{Sie zwinkert dir zu.}
{165}{}{Sie riecht umwerfend gut.}

# use gambling skill on dealer
# dealer dice amounts are screwed up
{175}{}{KEINE WÜRFEL!!!}
{176}{}{ZU VIELE WÜRFEL!!!}
# dealer has loaded dice planted by player
{177}{}{Die Chancen stehen gut, seit du die Würfel ausgetauscht hast.}
{178}{}{Die Chancen stehen nicht so gut.}
{179}{}{Du kannst nicht genau einschätzen, wie deine Chancen stehen.}
# dealer has regular dice
{185}{}{Die Chancen stehen ganz gut.}
{186}{}{Du kannst nicht genau einschätzen, wie deine Chancen stehen.}
{187}{}{Die Chancen stehen nicht so gut.}

# 2. FLOAT [ENCLAVE_DESTROYED == TRUE]
{200}{}{::Jubel::}
{201}{}{::Klatschen::}
{202}{}{::Pfiffe::}
{203}{}{}
{204}{}{Ich dacht schon, du hättest uns beim Retten der Welt ganz und gar vergessen.}

# 3. FLOAT [MADE MAN, SAME CASINO] (WTG)
{215}{}{Hallo, }
{216}{}{Wenn du später etwas Gesellschaft brauchst....}
{217}{}{Hey, du...[zwinkert]...willste spielen?}
{218}{}{Er sieht so...[schaudert]...gefährlich aus.}
{219}{}{Willkommen im Kasino, }
{220}{}{Kannst du beim Boss ein gutes Wort für mich einlegen?}
{221}{}{Hallo, meine Liebe. Kann ich irgendwie behilflich sein?}
{222}{}{Interessiert an einem Spielchen, meine Liebe?}
{223}{}{Sie sieht so...[schaudert]...gefährlich aus.}

# 5. FLOAT [MADE MAN, WRONG CASINO] (WTG)
{235}{}{Sieht so aus, als ob der hier schon mit seinem Leben spielt.}
{236}{}{Äh, ich glaub, er ist grad ins falsche Kasino geraten...}
{237}{}{Wenn er nicht verschwindet, bevor die Jungs ihn entdecken...}
{238}{}{Oh-oh. Ärger...}
{239}{}{Sieht so aus, als ob die hier schon mit ihrem Leben spielt.}
{240}{}{Äh, ich glaub, sie ist grad ins falsche Kasino geraten...}
{241}{}{Wenn sie nicht verschwindet, bevor die Jungs sie entdecken...}

# 7. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{250}{}{Hey, Muskelmann. Willste 'n paar Jetons setzen?}
{251}{}{Hey, Meister...[zwinkert]...willste spielen?}
{252}{}{Hey, Meister...[lächelt]...willste dein Glück versuchen?}
{253}{}{Wenn du später etwas Gesellschaft brauchst....}
{254}{}{Vielleicht sollt ich mal mit ihm reden...}
{255}{}{He, }
{256}{}{Wenn du 'n paar Jetons gewinnen willst, biste hier genau richtig.}
{257}{}{Wir haben heut die Glücksfee im Haus...nichts als Gewinner!}
{258}{}{Tritt näher, }
{259}{}{Noch 'n Drink?}
{260}{}{Willkommen im Kasino, }
{261}{}{Hallo, }
{262}{}{Interesse an einem Spielchen, }
{263}{}{Willkommen im Kasino, }

# 9. FLOAT [PORN STAR] (WTG)
{270}{}{Hey, Leinwandheld. Willste 'n paar Jetons setzen?}
{271}{}{He, }
{272}{}{He, }
{273}{}{Wenn du 'n paar Jetons gewinnen willst }
{274}{}{Wir haben heut die Glücksfee im Haus...nichts als Gewinner!}
{275}{}{Tritt näher, }
{276}{}{Noch 'n Drink?}
{277}{}{Willkommen im Kasino, }
{278}{}{Na, Diva. Haste Lust, dein Geld unter die Leute zu bringen?}
{279}{}{Willste heut abend tanzen?}

# 11. FLOAT [MALE, NO REP] (WTG)
{290}{}{Hey, Süße. Willste 'n paar Jetons setzen?}
{291}{}{Hey, Süße...[zwinkert]...Lust zu zocken?}
{292}{}{Hey, Süße...[lächelt]...willste dein Glück versuchen?}
{293}{}{Wenn du 'n paar Jetons gewinnen willst, biste hier genau richtig.}
{294}{}{Wir haben heut die Glücksfee im Haus...nichts als Gewinner!}
{295}{}{Tritt näher, versuch dein Glück.}
{296}{}{Noch 'n Drink, Schätzchen?}
{297}{}{Willkommen im Kasino, Schätzchen.}
{298}{}{Der Tisch ist frei, falls du 'n Spielchen wagen willst...}
{299}{}{Hey, Schätzchen. Willste 'n paar Jetons setzen?}
{300}{}{Willste spielen, Schätzchen?}
{301}{}{Willkommen im Kasino, Schätzchen.}

# 13.  PLACE YOUR BETS (WTG)
{320}{}{[Die Croupier-Dame sieht dich nervös an und beißt dann auf ihre Lippe.] Hm, bitte
 setzen...Mindesteinsatz $}
{321}{}{Bitte setzen, Sir. Mindesteinsatz $}
{322}{}{Bitte setzen, meine Dame. Mindesteinsatz $}
{323}{}{Bitte setzen, Mindesteinsatz $}
{324}{}{Ich bes-ser als du}
{325}{}{Ich spielen Blödsinn}
{326}{}{Was dieses Spiel? Kann einsetzen Geckohaut? Ich haben Geck...ooooh...schöne Lichter!
 [Du gehst weiter.]}
{327}{}{[Du hast $}
{328}{}{Setze $}
{329}{}{Wow, nee, das ist zu viel für mich.}
{330}{}{Heute kein Einsatz, danke.}
{331}{}{Ohhh, tut mir leid. Ich weiß nicht, wie man diese verrückten Spiele spielt.}

# 14.  RETARD (14)
{340}{}{Hm...Ich hab gehört, dass sie da draußen Hirn ausgeben. Vielleicht solltest du ja mal
 nachschauen.}
{341}{}{Äh, ja, Sir. Schau bald wieder bei uns vorbei.}
{342}{}{Äh, ja, gnädige Frau. Schau bald wieder bei uns vorbei.}
{343}{}{Tschüüüss}
{344}{}{Tschau. }
{345}{}{Äh...Hirn...was das?! Ich gehn sehn!}

# 15. POOR MAN (13)
{350}{}{Jawohl, Sir, komm bald wieder.}
{351}{}{Jawohl, gnädige Frau, komm bald wieder.}
{352}{}{[Der Croupier zieht eine Augenbraue nach oben.] $}
{354}{}{Werd ich, danke.}
{355}{}{Vielleicht.}

# 16. LOOOOOOSER (13)
{400}{}{Tut mir leid, vielleicht klappt's beim nächsten Mal.}
{401}{}{Tut mir leid, Sir, vielleicht klappt's beim nächsten Mal.}
{402}{}{Tut mir leid, gnädige Frau, vielleicht klappt's beim nächsten Mal.}

{410}{}{Gewonnen!}
{411}{}{Gewonnen! Herzlichen Glückwunsch, Sir!}
{412}{}{Gewonnen! Herzlichen Glückwunsch, meine Dame!}

{420}{}{Gewonnen! Du hast deinen Einsatz verdoppelt.}
{421}{}{Gewonnen! Du hast deinen Einsatz verdoppelt! Herzlichen Glückwunsch, Sir.}
{422}{}{Gewonnen! Du hast deinen Einsatz verdoppelt! Herzlichen Glückwunsch, meine Dame!}

{430}{}{Gewonnen! Du hast deinen Einsatz verdreifacht!}
{431}{}{Gewonnen! Du hast deinen Einsatz verdreifacht! Wir haben heut wohl 'ne Glücksfee im Haus! Herzlichen Glückwunsch, Sir.}
{432}{}{Gewonnen! Du hast deinen Einsatz verdreifacht! Wir haben heut wohl 'ne Glücksfee im Haus! Herzlichen Glückwunsch, Sir.}

{440}{}{Mach Schluss für heute.}
{441}{}{Mach Schluss.}

#17. TABLE TAMPER
{450}{}{Tut mir leid, dieser Tisch ist geschlossen. Jemand hat die Würfel gezinkt.}
{451}{}{Tut mir leid, Sir, dieser Tisch ist geschlossen. Jemand hat die Würfel gezinkt.}
{452}{}{Tut mir leid, meine Dame, dieser Tisch ist geschlossen. Jemand hat die Würfel gezinkt.}
{453}{}{Ohhh, OK.}
{454}{}{Tut mir leid, das zu hören. Danke.}

# message parts
{2203}{}{! Willkommen im Kasino, Held!}
{2215}{}{. Kann ich dir...*irgendwie* behilflich sein?}
{2219}{}{.}
{2255}{}{. Haste Lust, 'n paar Jetons einzusetzen?}
{2258}{}{, 'n paar Jetons gewinnen.}
{2260}{}{.}
{2261}{}{. Lass mich wissen, wenn ich dir irgendwie behilflich sein kann.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. Ihr Einsatz, bitte...}
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ könnt immer neue Inventarobjekte gebrauchen [Du gehst.]}
{2352}{}{? 'Zu viel für dich?' [Spottend.] Junge, du bist eindeutig in der falschen Stadt.}
{2353}{}{? 'Zu viel für dich?' [Spottend.] Hey, Mädchen, du bist eindeutig in der falschen Stadt.}

# new
{5000}{}{ Das ist die letzte Gewinnauszahlung. Das Haus macht Schluss für heute!}
{5001}{}{ Das ist die letzte Gewinnauszahlung. Das Haus macht Schluss für heute!}

{5100}{}{Es tut mir leid, aber dieser Tisch wurde geschlossen.}
{5101}{}{Es tut mir leid, werter Herr, aber dieser Tisch wurde geschlossen.}
{5102}{}{Es tut mir leid, werte Frau, aber dieser Tisch wurde geschlossen.}
