# lockpick
# dude
{100}{}{Du hast erfolgreich das Schloß geöffnet.}
{101}{}{Du hast das Schloß nicht öffnen können.}
{102}{}{Du hast das Objekt erfolgreich abgeschlossen.}
{103}{}{Du hast das Objekt nicht abschliessen können.}
# other critter
{200}{}{ hat erfolgreich das Schloß geöffnet.}
{201}{}{ kann das Schloß nicht öffnen .}
{202}{}{ hat erfolgreich das Objekt abgeschlossen.}
{203}{}{ kann das Objekt nicht abschliessen.}

# explosion
{300}{}{Die Explosion zerstört das Schloß an dem Objekt.}
{301}{}{Die Explosion hat das Schloß an dem Objekt nicht entfernt.}

# pry
# dude
{400}{}{Du hast erfolgreich das Schloß an dem Objekt aufgebrochen.}
{401}{}{Du hast das Schloß an dem Objekt nicht aufbrechen können.}
# other critter
{500}{}{ erfolgreich das Schloß an dem Objekt aufgebrochen.}
{501}{}{ das Schloß an dem Objekt nicht aufbrechen können.}

