# quick looks
# unknown
{100}{}{Du siehst eine seltsame Maschine. }
# normal
{101}{}{Du siehst einen Spielautomaten. }
# high roller
{102}{}{Du siehst einen glitzernden Spielautomaten. }
# jackpot
{103}{}{Du siehst einen schimmernden Spielautomaten. }

# examines
# unknown
{130}{}{Der hat drei Augen und einen Arm.}
# bet amount
{140}{}{Mindesteinsatz beträgt }
{141}{}{ Dollar.}
# normal
{150}{}{Du bist dir sicher, aus dem Augenwinkel zu sehen, daß er dich ansieht. }
{151}{}{Der glänzende Rahmen und der goldene Hebel schimmern verführerisch im Licht. }
# high roller
{165}{}{Ist für Leute, denen das Geld locker sitzt. }
# jackpot
{180}{}{Die hohe Gewinnsumme ist verdammt verlockend. }

# slot machine first play message
{200}{}{(Deine Hand zittert, während du nach deinen Münzen suchst. Die Maschine flüstert dir weiter zu.) *Komm schon, Schätzchen...trau dich....los...sei kein Feigling...*}
{201}{}{Du siehst einen Spielautomaten. Der glänzende Rahmen und der goldene Hebel schimmern verführerisch im Licht. Der Münzschlitz glänzt einladend. Dir wird vor Erregung ganz heiß.}
{202}{}{(Deine Hand zittert, während du nach deinen Münzen suchst. Die Maschine flüstert dir immer noch zu.) *Komm schon, Baby...trau dich...nimm den Hebel in die Hand...halt ihn ganz fest...los...*}

# insert coin messages
{250}{}{Wirf }
{251}{}{ Dollar ein. }
{252}{}{Spiel die letzten }
{253}{}{ Dollar.}
{254}{}{Mach Schluß für heute.}
{255}{}{Du bist pleite. Dir bleibt nichts anderes übrig, als aufzuhören. }
{256}{}{Mach Schluß.}
{257}{}{Du bist pleite. Dir bleibt nichts andres übrig, als aufzuhören. }
{258}{}{Jetzt reicht's! Ich gehe!}
{259}{}{Jetzt reicht's! Ich gehe!}

# this is the message for when the machine is played
{500}{}{Die Räder im Automat drehen sich... }
# this goes between every symbol, example:   "cherry... orange... melon... "
{599}{}{... }

# pay off types
{600}{}{Nichts. }
{601}{}{Eine Kirsche. }
{602}{}{Zwei Kirschen. }
# Three [symbol].
{603}{}{Drei }
{613}{}{ ein. }
{604}{}{JACKPOT! }
{605}{}{DOPPELTER JACKPOT!!! }

# payoff amount message
{700}{}{Gewinnsumme }
{701}{}{ Dollar.}
# symbol types
# singular
{1001}{}{Kirsche}
{1002}{}{Orange}
{1003}{}{Pflaume}
{1004}{}{Glocke}
{1005}{}{Balken}
{1006}{}{Melone}
{1007}{}{Sieben}
# plural
{1101}{}{Kirschen}
{1102}{}{Orangen}
{1103}{}{Pflaumen}
{1104}{}{Glocken}
{1105}{}{Balken}
{1106}{}{Melonen}
{1107}{}{Siebenen}

# float messages
{2000}{}{*Hey, Cowboy, wie wär's mit 'nem Spielchen.*}
{2001}{}{*Hey, Seemann.*}
{2002}{}{*Wirf einen Chip ein und zieh den Arm. Ich werd nett zu dir sein.*}
{2003}{}{*Tick... Tick... Tiiiiick...*}
{2004}{}{*Ding*}
{2005}{}{*Bing*}
{2006}{}{*Kaaa-tsching*}
{2007}{}{*Tzzzzzz*}
{2008}{}{*Klingeling*}
{2009}{}{*Dingiti-ding*}
{2010}{}{*Hey, meine Schöne, wie wär's mit 'nem Spielchen.*}
{2011}{}{*Hallo, meine Schöne.*}
{2012}{}{*Was bist du für ein hübsches Ding. Warum spielen wir nicht 'ne Runde?*}

# 3.  NO MONEY (WTG, 9)
# no money to play
{2175}{}{(Du starrst den Spielautomaten an und merkst, du hast nicht genug Geld. Du verfluchst deine Armut. Vielleicht ein andermal...)}
{2176}{}{Du gehst.}
# won jackpot block
{2185}{}{(Die Anzeige "AUSSER BETRIEB" am Spielautomaten blinkt.)}
{2186}{}{Du gehst.}

# 4. RETARD (WTG)
{2100}{}{Du siehst eine seltsame goldene Metallkiste mit drei Augen und einem Arm. Du hast selten so was Schönes gesehen.}
{2101}{}{Ich }
{2102}{}{ wer du?}
{2103}{}{Ich vermissen MAMA. }
{2104}{}{ vermissen VAUL-T. Ich wollen nach Haus}
{2105}{}{(Du schüttelst seine Hand.)}
{2106}{}{du komischer Mutant}
{2107}{}{Gelobt sei der Bunker! Gelobt sei der Bunker!}
{2108}{}{Bist du ein Steuerchip?}
{2109}{}{Geh weiter, such nach andern glänzenden Dingen}
{2110}{}{Du gehst.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{2130}{}{Die seltsame, schöne und goldene Metallkiste mit drei Augen und einem Arm antwortet nicht.}
{2131}{}{ICH }
{2132}{}{! DU MIR ANTWORTEN!}
{2133}{}{(Du schüttelst seine Hand.)}
{2134}{}{Ich Bunkerbewohner. Du SOFORT reden.}
{2135}{}{du komischer Mutant}
{2136}{}{Bist du ein Steuerchip?}
{2137}{}{Geh weiter, such nach andern glänzenden Dingen}
{2138}{}{Du gehst.}

# 6.  RETARD PULLS HANDLE (4, 5)
{2151}{}{Du nimmst seinen Arm und schüttelst ihn freundlich. Dabei hörst du ein *bzzzzzzz* und die Kiste spricht! "Bitte... wirf... Geld ein."}
{2152}{}{Aighhhhh! Roboter! Roboter! Laaaaauuuf }
{2153}{}{(Du gehst.)}

# slot machine taunts loss
# male
{2200}{}{(Du hörst, daß sie dich auslacht.)}
{2201}{}{*Hahaha, warum läßt du's nicht lieber bleiben, Kleiner.*}
{2202}{}{*Vielleicht läßt du lieber jemand andern an meinem Hebel ziehen.*}
# any
{2203}{}{(Ein leises, manisches Lachen dringt aus der Maschine.)}
{2204}{}{(Du hörst, daß dich der Spielautomat auslacht.)}
{2205}{}{(Der Spielautomat kichert.)}
{2206}{}{*Komm schon, alter Verlierer, gib uns noch 'ne Chance.*}
# female
{2207}{}{*Ich hab von dir gekriegt, was ich wollte, Baby. Warum gibste nicht auf?*}
{2208}{}{*Schund!*}
{2209}{}{*Paß auf, daß dir die Kasinotür beim Rausgehen nicht auf den Hintern schlägt.*}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{*Jiiiiaah! Ja, Baby! Oh Gott, ja! Ja! Ja, noch mal! Schneller! Fester! Worauf wartest du?! Noch mal!*}
{2248}{}{*Ja, Baby... zieh immer weiter am Hebel... schneller, fester, schneller...  komm schon...*}
{2249}{}{*Komm schon, Schätzchen... jeder schafft's mindestens einmal...versuch's noch mal... bitte...*}
# any
{2250}{}{*Gib noch nicht auf, Baby! Ich brauch dich jetzt mehr denn je!*}
# female [1X - 3X]
{2251}{}{*Komm schon, Liebling... versuch's noch mal... nimm den Hebel... halt ihn ganz fest ... komm schon...*}
{2252}{}{*Ja, genau, Liebling... immer schön weiter ziehen... schneller, fester, schneller... komm schon...*}
{2253}{}{* Ennnnghhhh! Geschafft, Kleiner! Du bist der Beste?! Du bist der Größte?!! Mach's noch mal! Zieh diesmal fester! Fester!*}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{2280}{}{(Du siehst einen Spielautomaten. Der glänzende Rahmen und der goldene Hebel schimmern verführerisch unter den Lichtern. Der Münzschlitz glitzert verführerisch. Dir wird vor Erregung ganz heiß. Während du auf den Automaten starrst, zwinkert dir eines der drei Fenster zu. Aus dem Münzschlitz hörst du eine erotische Stimme.) *Hallooo, Süßer. Haste Lust, mit 'nem Mädel wie mir mal richtig Spaß zu haben?*}
{2281}{}{(Du siehst einen Spielautomaten. Der robuste, stabile Rahmen und der goldene Hebel schimmern verführerisch im Licht. Der Münzschlitz glitzert verführerisch. Du merkst, wie deine Oberschenkel voller Erwartung brennen. Während du auf den Automaten starrst, flüstert dir eine aufregende männliche Stimme aus dem Einwurfschlitz zu.) *Du bist die faszinierendste Frau, die ich je gesehn hab. Willste dein Glück versuchen?*}
{2282}{}{::Zwick dich selbst::}
{2283}{}{Äh...hallo?}
{2284}{}{::Hol tief Luft, geh weiter.:: }

# 14. DRUNK CONVERSATION 1 (13)
{2300}{}{*Ich bin immer noch hier, schöne Frau.* (Der Spielautomat senkt seine Stimme.) *Na komm  schon...willste 'n Spielchen wagen?*}
{2301}{}{*Ich bin immer noch hier, Süßer.* (Der Spielautomat senkt seine Stimme.) *Weißte, daß du 'n faszinierender Typ bist? Hey...Lust, 'n paar Münzen in mich reinzustecken?*}
{2302}{}{Weeer duuuu *sein*?}
{2303}{}{Klaaar, ich wagen Spiiieelchen.}
{2304}{}{Ich hau lieber ab, bevor ich was in dich reinsteck, das ich später bereu. (Du gehst.)}
{2305}{}{::Hol tief Luft, geh weiter.:: (Du gehst.)}

# 15. DRUNK 2 (14)
{2320}{}{*Ich bin der perfekte Mann für dich.* (Der Spielautomat zwinkert dir zu.) *Gib mir 'n paar Münzen, und ich werd dich so befriedigen, wie das noch KEIN Mann geschafft hat.*}
{2321}{}{*Ich bin die perfekte Frau für dich. Ich brauch nur 'n bißchen Aufmerksamkeit. Kannste mir nicht helfen? Komm, nur ein, zwei Münzen.*}
{2322}{}{Könn' wir nich' einfach reden?}

# 16. DRUNK 3 (15)
{2340}{}{*Klar, Süße, klar.* (Der Spielautomat schaut verständnisvoll.) *Was geht in deinem hübschen kleinen Kopf denn vor?*}
{2341}{}{*Klar, Süßer, klar.*(Der Spielautomat sieht verständnisvoll aus.) *Worüber machste dir denn Sorgen, Kleiner?*}
{2342}{}{Ich vermissen MAMA und VAULT und ich...nix finden Steuerchip...*schnief*}
{2343}{}{Ich vermissen MAMA und VAULT wurde ANGEGRIFFEN und ich...weiß nicht, wo sie sein...und ...*schnief*}
{2344}{}{Ich müssen große Mutanten stoppen... und nicht wissen WIE... und mei-mei-meine Mama WEG, und....*schnief*}
{2345}{}{Des Spiel is' aus...un' jetz' lauf ich einfach rum...un' Angst, daß jetz' alles AUS is' ...*schnief*}
{2346}{}{Ach, Fhallaut swei unterstützt meine 3D Fxxxx-Karte nich' und ich hab so viel *Moneten* dafür ausgegeben und...*schnief*}
{2347}{}{Ich hab versucht, 'ne gute Figur zu kriegen, aber irgendwie hab ich die Punkte alle *falsch* verteilt...un' jetz' hab ich 'ne Mistfigur...un'...*schnief*}
{2348}{}{Wenn ich schon mit Spiehlautomaten red, mussich echt ziiiemlich üübel dran sein.}

# 17. DRUNK 4 (16)
{2370}{}{*Schon gut...zerbrich dir deinen hübschen kleinen Kopf nicht länger... ich werd mich um alles kümmern. Komm, leg deinen Kopf hierher. Schon gut, laß es raus.*}
{2371}{}{* Schon gut...du mußt dir keine Gedanken mehr machen, Kleiner... ich werd mich um alles kümmern. Komm, leg deinen Kopf hierher. Schon gut, laß es raus.*}
{2372}{}{Danke, Spielautomaat *schnief* du bis' echt klasse}
{2373}{}{Duu bis' die einsig *nette* Persoon, die mir begegnet is'. Bisheer warn alle andern gans
 gemein un' wollten mir *weh* tun un' mein Gelt ham un'...*schnief*}

# 18. DRUNK 5 (17)
{2380}{}{*Bist du OK, Schätzchen? Mir ist nicht wohl bei dem Gedanken, dich so gehen zu lassen.*}
{2381}{}{(Du ruhst deinen müden Kopf auf dem Automaten aus.)}
{2382}{}{* Bist du OK, Kleiner? Mir ist nicht wohl bei dem Gedanken, dich so gehn zu lassen.*}
{2383}{}{Bin schon OK...Danke förs Geschpräch, Spiiielautomaat, du bis' soooo nett!}

# 19. DRUNK 6 (18)
{2400}{}{*Du bist die einzige Heldin in dieser miesen Welt, in der's nur Bastarde und Diebe gibt. Du mußt auf dich aufpassen, hörst du, Kleine?* (Dreht sich weg.) *Geh jetzt besser, bevor ich zur Heulsuse werde.*}
{2401}{}{[Auf einem der Fenster scheint sich eine Träne zu bilden.]}
{2402}{}{*Du bist der einzige Held in dieser miesen Welt, in der's nur Bastarde und Diebe gibt. Du mußt auf dich aufpassen, hörst du, Kleiner?* (Dreht sich weg.) *Geh jetzt besser, bevor ich losheul.*}
{2403}{}{Tschühüs}

# rollin' messages
{3000}{}{Komm schon, }
{3001}{}{! Baby braucht ein neues Paar Schuhe!}
{3002}{}{! Papa braucht ein neues Plasmagewehr!}

# can't play
{4000}{}{Da blockiert doch jemand die Maschine.}
{5000}{}{Manipulier die Maschine das ganze Geld auszuspucken.}
{5001}{}{Die Maschine scheint einzufrieren und dann hört man ein leises Grollen als eine Lawine von Münzen beginnt aus dem Ausgabefach fallen.}
{5002}{}{[Sammel das Geld und geh.]}