/*

	Hub - the missing Brotherhood initiate

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\mapnecro.h"

#define NAME                    SCRIPT_MISSBRO
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;

procedure Brother00;
procedure Brother01;
procedure Brother02;
procedure Brother03;
procedure Brother04;
procedure Brother05;
procedure Brother06;
procedure Brother07;
procedure Brother08;
procedure Brother09;
procedure Brother10;
procedure Brother11;
procedure Brother12;
procedure BrotherEnd;

variable tmp_hostile;
variable Only_Once := 1;
variable visible := 1;

procedure start begin
	if Only_Once then begin
		Only_Once := 0;
		if (local_var(5) == 1) then begin
			visible := 0;
		end
		set_self_team(TEAM_BROTHERHOOD );
		set_self_ai( AI_BROTHERHOOD_INITIATE );
	end
end

procedure combat begin
	tmp_hostile := 1;
end

procedure critter_p_proc begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		attack(dude_obj);
	end
	if (local_var(5) == 1) then begin
		if (self_tile != 17145) then begin
			self_walk_to_tile( 17145 );
		end
	end
end

procedure pickup_p_proc begin
	if (source_obj == dude_obj) then begin
		tmp_hostile := 1;
	end
end

procedure talk_p_proc begin
	dude_look_at_self;
	get_reaction
	if (local_var(4) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_MISSBRO, random(134, 136)), 2);
	end
	else begin
		set_local_var(4, 1);
		start_gdialog(651, self_obj, 4, -1, -1);
		gsay_start;
		call Brother00;
		gsay_end;
		end_dialogue;
	end
	self_walk_to_tile( 17145 );
	set_local_var(5, 1);
end

procedure destroy_p_proc begin
	set_global_var( GVAR_QUEST_BROHOOD_2_FIND_LOST, 5 );
	inc_good_critter
end

procedure look_at_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_MISSBRO, 100));
end

procedure Brother00 begin
	gsay_reply(651, 101);
	if (global_var( GVAR_WORLDMAPLIST_BROTHERHOOD ) < 1) then begin
		NOption( 102, Brother01, 4 );
	end
	else begin
		if (global_var( GVAR_QUEST_BROHOOD_2_FIND_LOST ) == 0) then begin
			NOption( 103, Brother03, 4 );
			NOption( 104, Brother04, 4 );
		end
		else begin
			NOption( 105, Brother02, 4 );
		end
	end
	NOption( 106, Brother03, 4 );
	NOption( 107, BrotherEnd, -3 );
	set_global_var( GVAR_QUEST_BROHOOD_2_FIND_LOST, 2 );
end

procedure Brother01 begin
	gsay_reply(651, 108);
	if (global_var( GVAR_WORLDMAPLIST_BROTHERHOOD ) < 1) then
		set_global_var( GVAR_WORLDMAPLIST_BROTHERHOOD, 1 );
	mark_on_map(AREA_BROTHERHOOD)

	call Brother08;
end

procedure Brother02 begin
	gsay_reply(651, 109);
	NOption( 110, Brother05, 4 );
	NOption( 111, Brother11, 4 );
	NOption( 112, Brother12, 4 );
end

procedure Brother03 begin
	gsay_message(651, 113, 50);
end

procedure Brother04 begin
	gsay_message(651, 114, 50);
end

procedure Brother05 begin
	gsay_reply(651, 115);
	NOption( 116, Brother07, 4 );
	NOption( 117, Brother06, 4 );
	NOption( 118, Brother10, 4 );
	NOption( 119, Brother09, 4 );
end

procedure Brother06 begin
	gsay_reply(651, 120);
	call Brother08;
end

procedure Brother07 begin
	gsay_reply(651, 121);
	call Brother08;
end

procedure Brother08 begin
	NOption( 122, Brother03, 4 );
	NOption( 123, Brother04, 4 );
end

procedure Brother09 begin
	gsay_message(651, 124, 50);
end

procedure Brother10 begin
	gsay_message(651, 125, 50);
end

procedure Brother11 begin
	gsay_reply(651, 126);
	NOption( 127, Brother05, 4 );
	NOption( 128, Brother03, 4 );
	NOption( 129, Brother04, 4 );
end

procedure Brother12 begin
	gsay_reply(651, 130);
	NOption( 131, Brother05, 4 );
	NOption( 132, Brother03, 4 );
	NOption( 133, Brother04, 4 );
end

procedure BrotherEnd begin
end
