#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Explosion}
{1}{}{Weglaufen}
{2}{}{Bevorz. Waffen}
{3}{}{Distanz}
{4}{}{Wen angreifen}
{5}{}{Pr‰parat Nehmen}

{10}{}{OK}
{11}{}{Abbrechen}

#
# Burst options.
#
{99}{}{Nicht anwendbar}
{100}{}{Immer!}
{101}{}{Manchmal, mach dir keine Sorgen, dass du mich triffst}
{102}{}{Triff mich ja nicht}
{103}{}{Pass auf, dass du mich nicht triffst}
{104}{}{Sei ganz sicher, dass du mich nicht triffst}

#
# Run away options.
#
{200}{}{Widerlicher Feigling}
{201}{}{Dein Finger schmerzt}
{202}{}{Du blutest etwas}
{203}{}{Dir geht es nicht gut}
{204}{}{Du brauchst einen Druckverband}
{205}{}{Niemals!}

#
# Weapon pref options.
#
{300}{}{Keine}
{301}{}{Nahkampf}
{302}{}{Nahkampf, dann Distanz}
{303}{}{Distanz, dann Nahkampf}
{304}{}{Distanz}
{305}{}{Unbewaffnet}

#
# Distance options.
#
{400}{}{Bleib in meiner N‰he}
{401}{}{Angriff!}
{402}{}{Aus dem Hinterhalt auf Gegner schieﬂen}
{403}{}{Alleine}
{404}{}{Bleib, wo du bist}

#
# Attack who options.
#
{500}{}{Wer mich angreift}
{501}{}{Den St‰rksten}
{502}{}{Den Schw‰chsten}
{503}{}{Wen du willst}
{504}{}{Wer am n‰chsten ist}

#
# Chem use options.
#
{600}{}{Ich bin sauber}
{601}{}{Stimpaks, wenn etwas verletzt}
{602}{}{Stimpaks, wenn schwer verletzt}
{603}{}{Irgendeine Medizin manchmal}
{604}{}{Irgendeine Medizin jederzeit}
