#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
#
{100}{}{OK}
{101}{}{OPTIONEN}
{102}{}{ABBRECHEN}
{103}{}{DRUCKEN}
{104}{}{ALTER}
{105}{}{GESCHLECHT}
{106}{}{NAME}
{107}{}{MÄNNLICH}
{108}{}{WEIBLICH}
{109}{}{BONUS}
{110}{}{KARMA}
{111}{}{OPFER}
{112}{}{FÄHIGKEITSPUNKTE}
{113}{}{Level:}
{114}{}{Erf.:}
{115}{}{Nächst. Lev.:}
{116}{}{FIGURENPUNKTE}
{117}{}{FÄHIGKEITEN}
{118}{}{Du musst alle Figurenpunkte vergeben,} # 1
{119}{}{bevor du das Spiel beginnst!}         # 2
#
{120}{}{Figurenpunkte}
{121}{}{Anzahl der übrigen Punkte, die zu einem der Werte hinzugezählt werden können.}
{122}{}{Nächstes Level}
{123}{}{Anzahl der Erfahrungspunkte, die für das nächste Level erforderlich sind.}
{124}{}{Bonus}
{125}{}{Karma}
{126}{}{Opfer}
{127}{}{Ein Bonus bedeutet zusätzliche Fähigkeiten. Bei jedem dritten Erfahrungslevel kannst du einen Bonus wählen.}
{128}{}{Zeigt an, wie sich die Entscheidungen auswirken, die du während des Spiels getroffen hast.}
{129}{}{Ein Zähler hält die Art und Anzahl der Kreaturen fest, die von dir oder in deiner Gegenwart getötet wurden.}
{130}{}{Fähigkeitspunkte}
{131}{}{Benutze die noch übrigen Fähigkeitspunkte, um deine Fähigkeiten zu verbessern.}
#
{132}{}{Maximum erreicht.}        # 1
{133}{}{Keine Steigerung möglich.}  # 2
{134}{}{Minimum erreicht.}        # 1
{135}{}{Keine Verringerung möglich.}  # 2
{136}{}{Keine Fähigkeitspunkte mehr verfügbar.}
{137}{}{Basis:}
{138}{}{SPEZIALKENNTNISSE}
{139}{}{ZUSATZMERKMALE}
{140}{}{Du hast bereits die maximale Anzahl von} # 1
{141}{}{drei Spezialkenntnissen!}               # 2
{142}{}{Du musst alle Spezialkenntnisse auswählen,}  # 1
{143}{}{bevor du das Spiel beginnst!}       # 2
{144}{}{Spezialkenntnisse}
{145}{}{Spezialkenntnisse sind Dinge, die deine Figur besonders gut kann. Jede Spezialkenntnis erhält 20 % und erhöht sich doppelt so schnell. Du musst drei Spezialkenntnisse auswählen.}
{146}{}{Zusatzmerkmale}
{147}{}{Zusatzmerkmale beschreiben deine Figur genauer. Alle Zusatzmerkmale haben positive und negative Auswirkungen. Bei der Erstellung kannst du bis zu zwei Zusatzmerkmale auswählen.}
{148}{}{Du hast bereits die maximale Anzahl von} # 1
{149}{}{zwei Zusatzmerkmalen!}                     # 2
{150}{}{Fähigkeiten}
{151}{}{Fähigkeiten bezeichnen erlerntes Wissen. Sie nehmen durch Erfahrung oder besondere Ereignisse während des Spiels zu. Je höher der Wert einer Fähigkeit, desto besser beherrschst du diese Fähigkeit.}
#
{152}{}{WÄHLE EINEN BONUS}
{153}{}{WÄHLE EIN NEUES ZUSATZMERKMAL}
{154}{}{LEGE EIN ZUSATZMERKMAL AB}
{155}{}{WÄHLE EINE NEUE SPEZIALKENNTNIS}
{156}{}{ZUSATZMERKMALE}
#
{157}{}{Alle Werte müssen zwischen 1 und 10 liegen,} # 1
{158}{}{bevor du das Spiel beginnst!}          # 2


#
# Abbreviated basic stat levels
#
{200}{}{Übel}  # Terrible
{201}{}{Mies}    # Bad
{202}{}{Dürftig}   # Poor
{203}{}{Leidlich}   # Fair
{204}{}{Mittel}   # Average
{205}{}{Gut}   # Good
{206}{}{Toll} # Very Good
{207}{}{Klasse}  # Great
{208}{}{Super} # Excellent
{209}{}{Spitze} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Trefferpkte}
{301}{}{Aktionspunkte}
{302}{}{Rüstung}
{303}{}{Schad./Unbew.}
{304}{}{Schad./Nahk.}
{305}{}{Verletz.-Res.}
{306}{}{Giftresistenz}
{307}{}{Strahlungsres.}
{308}{}{Reaktion}
{309}{}{Heilung}
{310}{}{Krit. Treffer}
{311}{}{Tragekapazität}
{312}{}{Vergiftet}
{313}{}{Verstrahlt}
{314}{}{Augenverletzung}
{315}{}{Armverletz. (rechts)}
{316}{}{Armverletz. (links)}
{317}{}{Beinverletz. (rechts)}
{318}{}{Beinverletz. (links)}

#
# Damage info texts
#
# Poisoned
{400}{}{Deine Figur wurde vergiftet. Die Wirkung des Gifts hält an, bis ein Gegenmittel gefunden wird oder es deinen Körper verlässt.}
# Radiation
{401}{}{Deine Figur wurde erheblich verstrahlt. Je intensiver die Strahlung, desto tödlicher die Wirkung.}
# Eye Damage
{402}{}{Deine Figur wurde an einem oder beiden Augen schwer verletzt. Dies beeinträchtigt deine Fähigkeit 'Wahrnehmung'.}
# Crippled right arm
{403}{}{Der rechte Arm wurde schwer verletzt und ist nicht voll einsatzfähig. Ist ein Arm schwer verletzt, kannst du keine beidhändigen Waffen benutzen. Sind beide Arme schwer verletzt, kannst du gar keine Angriffe mit Waffen durchführen.}
# Crippled left arm
{404}{}{Der linke Arm wurde schwer verletzt und ist nicht voll einsatzfähig. Ist ein Arm schwer verletzt, kannst du keine beidhändigen Waffen benutzen. Sind beide Arme schwer verletzt, kannst du gar keine Angriffe mit Waffen durchführen.}
# Crippled right leg
{405}{}{Deine Figur hat ein schwer verletztes rechtes Bein.}
# Crippled left leg
{406}{}{Deine Figur hat ein schwer verletztes linkes Bein.}

# Month strings
{500}{}{Januar}
{501}{}{Februar}
{502}{}{März}
{503}{}{April}
{504}{}{Mai}
{505}{}{Juni}
{506}{}{Juli}
{507}{}{August}
{508}{}{September}
{509}{}{Oktober}
{510}{}{November}
{511}{}{Dezember}

#
# Option menu text
#
{600}{}{SPEICHERN}
{601}{}{LADEN}
{602}{}{IN DATEI DRUCKEN}
{603}{}{LÖSCHEN}
{604}{}{OK}
{605}{}{Willst du die aktuelle Figur}      # line 1
{606}{}{wirklich löschen?}                 # line 2
{607}{}{ wurde erfolgreich gespeichert.}
{608}{}{ wurde erfolgreich geladen.}
{609}{}{ existiert bereits.}
{610}{}{Überschreiben?}
{611}{}{Fehler beim Speichern von }
{612}{}{Fehler beim Laden von }
{613}{}{Figurdatei ungültig.}
{614}{}{Figurdaten ungültig.}
{615}{}{Fehler beim Lesen der Dateiliste!}
{616}{}{DRUCKEN}
{617}{}{SPIELER}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}                   # Title line 1
{621}{}{VAULT 13-PERSONALAKTE} # Title line 2
{622}{}{Uhr} # Title line 3
# -
# -
#{000}{}{      Strength: 00        Hit Points: 000/000          Sequence: 00}
#{000}{}{    Perception: 00       Armor Class: 000          Healing Rate: 00}
#{000}{}{     Endurance: 00     Action Points: 000       Critical Chance: 000%}
#{000}{}{      Charisma: 00      Melee Damage: 000          Carry Weight: 000 lbs.}
#{000}{}{  Intelligence: 00       Damage Res.: 000%}
#{000}{}{       Agility: 00    Radiation Res.: 000%}
#{000}{}{          Luck: 00       Poison Res.: 000%}
#
{623}{}{ ::: Statistik :::}
{624}{}{       Stärke:}
{625}{}{        Trefferpunkte:}
{626}{}{        Reaktion:}
# -
{627}{}{     Wahrnehmung:}
{628}{}{       Rüstung:}
{629}{}{        Heilung:}
# -
{630}{}{      Ausdauer:}
{631}{}{     Aktionspunkte:}
{632}{}{      Kritische Treffer:}
# -
{633}{}{       Charisma:}
{634}{}{      Schaden im Nahkampf:}
{635}{}{         Tragekapazität:}
# -
{636}{}{   Intelligenz:}
{637}{}{       Verletzungsresistenz:}
# -
{638}{}{        Beweglichkeit:}
{639}{}{    Strahlungsresistenz:}
# -
{640}{}{           Glück:}
{641}{}{       Giftresistenz:}
# -
# -
#{000}{}{ Name: 01234567890        Age: 00         Gender: Female}
{642}{}{  Name:}
{643}{}{Alter:}
{644}{}{               Geschlecht:}
{645}{}{Mann}
{646}{}{Frau}
#-
#{000}{}{ Level: 00                 Exp: 000,000    Next Level: 000,000}
{647}{}{ Level:}
{648}{}{                Erf.:}
{649}{}{Nächst. Lev.:}
#-
{650}{}{ ::: Zusatzmerkmale :::           ::: Bonus :::           ::: Karma :::}
#-
{651}{}{ ::: Fähigkeiten :::                ::: Opfer :::}
#-
{652}{}{ ::: Inventar :::}
#-
{653}{}{                                      Gesamtgewicht:}

#
# Karma name strings
#
{1000}{}{Ruf (allgemein)}
{1001}{}{Wilder Kämpfer}
{1002}{}{Held}
{1003}{}{Mörder}
{1004}{}{Nuka Cola-abhängig}
{1005}{}{Buffout-abhängig}
{1006}{}{Mentats-abhängig}
{1007}{}{Psycho-abhängig}
{1008}{}{RadAway-abhängig}
{1009}{}{Alkoholabhängig}
#
# Karma description strings
#
{1100}{}{Diese Statistik gibt dein Ansehen wieder. Je höher die Zahl, desto bekannter und angesehener bist du. Hat dein Ansehen einen negativen Wert, wirst du wegen deiner schrecklichen Taten gehasst.}
{1101}{}{Du hast viele Menschen getötet. Gewöhnlich nicht unbedingt das, wofür man bekannt werden will! Du bist jedoch bei Leuten, die auf die schiefe Bahn geraten sind, beliebt.}
{1102}{}{Deine Taten lassen dich zum Helden des Volkes werden. Dein Kampf gegen das Böse und Schlechte ist allseits bekannt. Ehrenwerte Leute respektieren dich.}
{1103}{}{Du hast junge Menschen getötet, die Jugend des Ödlands. Das wird als äußerst schlimmes Vergehen angesehen. Du böser und verkommener Mensch!}
{1104}{}{Du trinkst sehr gerne Nuka Cola, die Cola der postnuklearen Welt.}
{1105}{}{Dein Körper verlangt nach Buffout. Wenn du Buffout nicht regelmäßig einnimmst, geht es dir dreckig.}
{1106}{}{Dein Körper verlangt nach Mentats. Ohne Mentats geht es dir dreckig.}
{1107}{}{Dein Körper verlangt nach Psycho. Wenn du Psycho nicht regelmäßig einnimmst, leidest du sehr. Wenn du es allerdings einnimmst, haben andere zu leiden!}
{1108}{}{Dein Körper verlangt nach RadAway. Das ist zwar nicht lebensgefährlich, aber du musst RadAway doch regelmäßig einnehmen.}
{1109}{}{Du hast ein Alkoholproblem. Genaugenommen hast du eine ganze Reihe Probleme mit deinen Trinkgewohnheiten!}
{1110}{}{TEMPORÄR - Was ist das?}


#
# Special Demo version only text
#
{5000}{}{Du kannst deine Figur nur in}   # 1
{5001}{}{der Vollversion ausdrucken.}   # 2
{5002}{}{Du kannst deine Figur nur in}    # 1
{5003}{}{der Vollversion speichern.}   # 2
{5004}{}{Du kannst eine gespeicherte Figur} # 1
{5005}{}{nur in der Vollversion laden.}   # 2
{5006}{}{MOGELMODUS}
{5007}{}{In der Demoversion nicht verfügbar.}



