#
# Item.c messages
#
{1}{}{Du erhältst %d %s.}
{2}{}{Du verlierst %d %s.}
{3}{}{Dir geht es besser.}
{4}{}{Du erleidest einen tödlichen Herzanfall aufgrund einer Präparat-Überdosis.}
{5}{}{%s hat keine Ladung mehr.}
{6}{}{%s ist eingeschaltet.}
{7}{}{%s ist ausgeschaltet.}
{8}{}{Du tastest deinen Körper mit dem Geigerzähler ab. Als Rem-Wert erhältst du: %d}
{9}{}{Dieses Objekt kann nur von der Symbolleiste aus eingesetzt werden.}
{10}{}{Nichts passiert.}

{50}{}{Das sah nach garnicht so viel aus.}

#
# Fallout 2
#
{500}{}{Es gibt nicht genügend Licht, um dieses Objekt nachzuladen.}
{600}{}{%s erliegt den Nebenwirkungen.}
# Weapon Damage strings
{800}{}{Leicht}
{801}{}{Mittel}
{802}{}{Schwer}
{803}{}{Extrem}
# Weapon Range strings
{820}{}{Kurz}
{821}{}{Mittel}
{822}{}{Lang}
