#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{Willst du das Spiel wirklich beenden?}
{1}{}{Demoversion}
{2}{}{Standardfigur wird benutzt.}
{3}{}{Screenshot gespeichert.}
{4}{}{Schnelladen erfolgreich ausgeführt.}
{5}{}{Schnellspeichern erfolgreich ausgeführt.}
{6}{}{Zeitlimit für Demo überschritten.}
{7}{}{PIPBoy im Kampf nicht verfügbar!}
{8}{}{Fehler beim Speichern des Screenshots.}
{9}{}{INTRO}
{10}{}{NEUES SPIEL}
{11}{}{SPIEL LADEN}
{12}{}{OPTIONEN}
{13}{}{MITARBEITER}
{14}{}{BEENDEN}
{15}{}{Aktionspunkte}
{16}{}{Trefferpunkte}
{17}{}{Kein Scanner installiert.}
{18}{}{Scanner ist nicht mehr geladen.}
{20}{}{Copyright(c) 1997 Interplay Productions. Alle Rechte vorbehalten.}

{30}{}{Möchtest du weiterspielen?}
#
# Game config text. Defined in gconfig.c
#
{100}{}{Fehler beim Speichern der Konfigurationsdatei!}
{101}{}{Spieleinstellungen nicht gespeichert.}
#
# Some radiation messages used in critter.c
#
{1000}{}{Dir ist sehr übel.}
{1001}{}{Dir ist sehr übel, und du fühlst dich nach leichtem Erbrechen etwas erschöpft.}
{1002}{}{Du bist sehr erschöpft, du erbrichst dich ständig, und deine Genesung ist beeinträchtigt.}
{1003}{}{Du hast starke Blutungen. Du bist sehr krank und hast Haarausfall.}
{1004}{}{Du blutest ständig stark. Das Erbrochene ist mit Blut vermischt. Deine Haut löst sich von deinen Knochen.}
{1005}{}{Du hast Darmblutungen und starken Durchfall. Du hast Blähungen und leidest unter furchtbaren Schmerzen.}
{1006}{}{Du bist an der Strahlenkrankheit gestorben.}
{1007}{}{Du hast eine starke Strahlendosis abbekommen.}
{1008}{}{Der Geigerzähler tickt.}
{1009}{}{Der Geigerzähler tickt wie verrückt.}
#
# Message used in actions.c
#
{2000}{}{Da kannst du nicht hin.}
{2001}{}{Das Schloß klemmt.}
#
# poison messages from critter.c
#
{3000}{}{Du wurdest vergiftet!}
{3001}{}{Das Gift schädigt deinen Körper.}
{3002}{}{Es geht dir etwas besser.}
{3003}{}{Dir geht es besser.}
#
# from queue.c
#
{4000}{}{Wegen unsachgemäßer Bedienung explodiert der Sprengstoff zu früh.}
#
# from combatai.c
#
{5000}{}{benutzt:}
{5001}{}{hat keine Munition mehr für:}
{5002}{}{lädt:}
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{Was willst du wissen?}

#
# from pipboy.c -- Fallout 2
#
// Fallout 2:  For Pipboy
{7000}{}{You aren't wearing the pipboy!}

#
# from anim.c -- Fallout 2
#
{8000}{}{Du bist überladen.}  # Carrying too much weight
{8001}{}{%s ist überladen.}

#
# from worldmap.c -- Fallout 2
#
{8500}{}{You gain %d experience points for successful use of the outdoorsman skill.}

#
# from party.c -- Fallout 2
#
{9000}{}{%s hat bei einigen Fähigkeiten dazugelernt.} # Party Member has gained experience/level
# Individuals

{9010}{}{Plötzlich fällt mir das alles wieder ein...} # pMIan_PID
{9011}{}{Ich glaube, ich lerne hier wirklich ein oder zwei Sachen.}
{9012}{}{Ich werde immer besser.}
{9013}{}{Siehst du. Alles Gute wird mit der Zeit noch besser.}

{9020}{}{Wuff WUFF WUUFFF!} # pMDog_PID
{9021}{}{Wuff WUFF WUUFFF!}
{9022}{}{Wuff WUFF WUUFFF!}
{9023}{}{Wuff WUFF!}

{9030}{}{Ich bin mir sicher, dass ist ein gutes Zeichen.} # pMTycho_PID
{9031}{}{Heh. Sieht aus, als könne man einem alten Hund doch ein paar neue Tricks beibringen.}
{9032}{}{Sieht aus, als hätte sich die ganze Herumreiserei bezahlt gemacht.}
{9033}{}{Ich hab ein paar neue Tricks gelernt.}

{9040}{}{Au Mann...da hab ich jetzt echt was draus gelernt.} # pMKatja_PID
{9041}{}{There is so much we can still learn.}
{9042}{}{Ich glaube, daß ich das allmählich alles kapiere.}
{9043}{}{Kaum zu glauben, daß ich so lange überlebt habe.}

{9050}{}{DATA ANALYSIS COMPLETE. UPGRADING ALL SYSTEMS.} # pMMrHandyC_PID
{9051}{}{NEW DATA COLLECTED. ENHANCING TARGETING SYSTEMS.}
{9052}{}{SYSTEM RETROFITTING COMPLETED.}
{9053}{}{OPTIMAL PERFORMANCE REACHED.}

{9060}{}{} # pMCarTrunk_PID
