{100}{}{Brennendes Metallfaß}
{101}{}{Dieses Faß enthält brennendes Papier oder anderen brennenden Müll.}
{200}{}{Holztür}
{201}{}{Eine Tür aus Holz.}
{300}{}{Holztisch}
{301}{}{Ein Tisch aus Holz.}
{400}{}{Holztisch}
{401}{}{Ein Tisch aus Holz.}
{500}{}{Metallfaß}
{501}{}{Ein altes Faß aus Stahl.}
{600}{}{Metallfaß}
{601}{}{Ein altes Faß aus Stahl.}
{700}{}{Stapel Reifen}
{701}{}{Ein Stapel alter Gummireifen. Sie sind porös und hart geworden, wahrscheinlich wegen der Hitze.}
{800}{}{Sicherheitstür}
{801}{}{Diese Tür läßt sich fest verriegeln. Sie bietet Schutz vor Elementen der Außenwelt und gefährlichen Kreaturen.}
{900}{}{Computer}
{901}{}{Ein Vaultcomputerterminal, das mit dem Hauptcomputer der Vault verbunden ist.}
{1000}{}{Säule}
{1001}{}{Eine Stützsäule, die den Druck auf den gesamten Komplex ausgleicht.}
{1100}{}{Computer}
{1101}{}{Ein Vaultcomputerterminal, das mit dem Hauptcomputer der Vault verbunden ist.}
{1200}{}{Computer}
{1201}{}{Ein Vaultcomputerterminal, das mit dem Hauptcomputer der Vault verbunden ist.}
{1300}{}{Monitor}
{1301}{}{Ein grüner Bildschirm, der verschiedene Daten anzeigt. Manchmal erscheinen einige Bytes.}
{1400}{}{Monitor}
{1401}{}{Ein grüner Bildschirm, der verschiedene Daten anzeigt.}
{1500}{}{Hologenerator}
{1501}{}{Ein großformatiges THT-Abspielgerät für Unterhaltungsfilme. Seit 80 Jahren wurden keine neuen Filme mehr gemacht.}
{1600}{}{Bildschirme}
{1601}{}{Drei Bildschirme, die verschiedene Daten anzeigen.}
{1700}{}{Bildschirme}
{1701}{}{Drei Bildschirme, die verschiedene Vaultdaten anzeigen.}
{1800}{}{Tür}
{1801}{}{Auch nach genauerer Betrachtung ist es noch immer eine Tür.}
{1900}{}{Tür}
{1901}{}{Auch nach genauerer Betrachtung ist es noch immer eine Tür.}
{2000}{}{Lüftungsschlitz}
{2001}{}{Ein Lüftungsschlitz, der den gesamten Komplex mit aufbereiteter, gereinigter Luft versorgt.}
{2100}{}{Lüftungsschlitz}
{2101}{}{Ein Lüftungsschlitz, der den gesamten Komplex mit aufbereiteter, gereinigter Luft versorgt.}
{2200}{}{Vault 13-Tür}
{2201}{}{Eine schwere Tür, die alle Arten von Beschädigungen und Stößen aushalten kann.}
{2300}{}{Vault 13-Tür}
{2301}{}{Eine schwere Tür, die alle Arten von Beschädigungen und Stößen aushalten kann.}
{2400}{}{Podest}
{2401}{}{Eine hydraulischer Lift, über den die Plattform des Aufsehers mit Nachschub, Strom und Kommunikationsleitungen versorgt wird.}
{2500}{}{Monitor}
{2501}{}{Hast du einen gesehen, hast du alle gesehen.}
{2600}{}{Monitor}
{2601}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{2700}{}{Gitter}
{2701}{}{Standardgitter von Vault-Tec, das die Basis für das Podest des Aufsehers bildet.}
{2800}{}{Rohrleitungen}
{2801}{}{Mehrere Rohrleitungen. Auch nach genauerer Betrachtung sind es immer noch Rohrleitungen.}
{2900}{}{Lüftungsschlitz}
{2901}{}{Standardventilationssystem von Vault-Tec.}
{3000}{}{Säule}
{3001}{}{Standardsäulenstützsystem von Vault-Tec.}
{3100}{}{Säule}
{3101}{}{Standardsäulenstützsystem von Vault-Tec.}
{3200}{}{Lüftungsschlitz}
{3201}{}{Standardventilationssystem von Vault-Tec.}
{3300}{}{Ventilator}
{3301}{}{Standardventilationssystem von Vault-Tec.}
{3400}{}{Bett}
{3401}{}{Ein Bett, das im Vergleich zu deinen bisherigen Schlafstätten ziemlich bequem aussieht.}
{3500}{}{Bett}
{3501}{}{Ein normales Bett. Sieht bequem aus.}
{3600}{}{Bett}
{3601}{}{Ein normales Bett. Sieht bequem aus.}
{3700}{}{Bett}
{3701}{}{Ein normales Bett. Sieht bequem aus.}
{3800}{}{Vaultaufzug}
{3801}{}{Ein Aufzug. Er fährt zwischen den verschiedenen Ebenen des Vaultkomplexes hin und her.}
{3900}{}{Stuhl}
{3901}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4000}{}{Stuhl}
{4001}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4100}{}{Stuhl}
{4101}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4200}{}{Stuhl}
{4201}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4300}{}{Monitor}
{4301}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4400}{}{Monitor}
{4401}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4500}{}{Monitor}
{4501}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4600}{}{Monitor}
{4601}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4700}{}{Monitor}
{4701}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4800}{}{Monitor}
{4801}{}{Ein Computermonitor, der verschiedene Daten anzeigt.}
{4900}{}{Kartenmarkierung - Ausgang}
{4901}{}{Kartenmarkierung - Ausgang}
{5000}{}{Luftaufbereitungsanlage}
{5001}{}{Eine LAA bereitet die alte Luft auf und versorgt den Komplex mit frischer Luft. Diese hier ist defekt.}
{5100}{}{Stuhl}
{5101}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5200}{}{Stuhl}
{5201}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5300}{}{Stuhl}
{5301}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5400}{}{Stuhl}
{5401}{}{Ein Stuhl. Schade, daß du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5500}{}{VA}
{5501}{}{Zu dieser Videoanzeige gehören mehrere Computermonitore und andere Bildschirme. Hier scheint sehr, sehr viel abzulaufen.}
{5600}{}{VA}
{5601}{}{Zu dieser Videoanzeige gehören mehrere Computermonitore und andere Bildschirme. Hier scheint sehr, sehr viel abzulaufen.}
{5700}{}{Stuhl}
{5701}{}{Ein Stuhl. Sieht verdammt bequem aus.}
{5800}{}{Stuhl}
{5801}{}{Ein Stuhl. Sieht verdammt bequem aus.}
{5900}{}{Stuhl}
{5901}{}{Ein Stuhl. Sieht verdammt bequem aus.}
{6000}{}{Stuhl}
{6001}{}{Ein Stuhl. Sieht verdammt bequem aus.}
{6100}{}{Tisch}
{6101}{}{Ein Tisch. Bevor es Tische gab, mußten die Menschen ihre Sachen auf den Boden legen.}
{6200}{}{Tisch}
{6201}{}{Dies ist mit Sicherheit ein Tisch.}
{6300}{}{Steppenläufer}
{6301}{}{Ein Steppenläufer. Natürlich hast du noch nie zuvor einen echten Steppenläufer gesehen. Du solltest ihn besser genau im Auge behalten.}
{6400}{}{Kaktus}
{6401}{}{An diesem Kaktus ist nichts Besonderes zu erkennen.}
{6500}{}{Kaktus}
{6501}{}{An diesem Kaktus ist nichts Wichtiges zu erkennen.}
{6600}{}{Baum}
{6601}{}{Ein toter Baum. Hier wächst einfach nichts richtig.}
{6700}{}{Geheimes Block-Hex}
{6701}{}{Wenn du diesen Text siehst, hat der technische Designer gepennt!}
{6800}{}{Vaulttreppen}
{6801}{}{Ein Treppenaufgang.}
{6900}{}{Stalagmit}
{6901}{}{Eine natürliche Erweiterung des Steinbodens.}
{7000}{}{Stalagmit}
{7001}{}{Eine natürliche Erweiterung des Steinbodens.}
{7100}{}{Blutfleck}
{7101}{}{An diesem Blutfleck gibt es nichts Ungewöhnliches, außer daß hier jemand oder etwas gestorben ist.}
{7200}{}{Steinsäule}
{7201}{}{Diese dicke Steinsäule reicht vom Boden bis zur Decke.}
{7300}{}{Steinsäule}
{7301}{}{Diese dünne Steinsäule reicht vom Boden bis zur Decke.}
{7400}{}{Steine}
{7401}{}{Du betrachtest die Steine einen Augenblick lang, aber sie bewegen sich nicht.}
{7500}{}{Steine}
{7501}{}{Du behältst diese Steine für den Fall im Auge, daß sie sich bewegen und angreifen.}
{7600}{}{Autoboden}
{7601}{}{ENTFERNT}
{7700}{}{Autodach}
{7701}{}{ENTFERNT}
{7800}{}{Steine}
{7801}{}{Ein großer Haufen Steine. Sie sehen für diese Region typisch aus.}
{7900}{}{Steine}
{7901}{}{Ein kleiner Haufen Steine.}
{8000}{}{Steine}
{8001}{}{Ein kleiner Haufen Steine.}
{8100}{}{Steine}
{8101}{}{Ein großer Haufen Steine.}
{8200}{}{Knochen}
{8201}{}{Ein großer Haufen ausgebleichter Tierknochen. Zumindest glaubst du, daß es sich um Tierknochen handelt ...}
{8300}{}{Knochen}
{8301}{}{Ein großer Haufen ausgebleichter Tierknochen. Zumindest glaubst du, daß es sich um Tierknochen handelt ...}
{8400}{}{Knochen}
{8401}{}{Ein sehr großer Haufen ausgebleichter Knochen. Du kannst nicht feststellen, von was für einer Kreatur sie stammen.}
{8500}{}{Knochen}
{8501}{}{Du glaubst, daß es sich um die Knochen gehörnter Känguruhs handelt, bist dir aber nicht ganz sicher. Die Knochen sind einfach zu verwittert, um sie genau bestimmen zu können.}
{8600}{}{Knochen}
{8601}{}{Die Knochen einer großen zweiköpfigen Kuh.}
{8700}{}{Tor}
{8701}{}{Ein Tor aus Holz. Es geht auf und zu, auf und zu, auf und zu ...}
{8800}{}{Metalleistruhe}
{8801}{}{ENTFERNT}
{8900}{}{Metalleistruhe}
{8901}{}{ENTFERNT}
{9000}{}{Steine}
{9001}{}{Ein sehr großer Haufen Steine. Sie sehen gefährlich aus, wie sie so daliegen.}
{9100}{}{Steine}
{9101}{}{Eine großer Haufen Steine. Wenn du genau hinsiehst, kannst du an den Seiten die Gesichter kleiner, alter Männer erkennen.}
{9200}{}{Steine}
{9201}{}{Steine, Steine, Steine! Wohin du auch siehst, überall Steine!}
{9300}{}{Steine}
{9301}{}{Ein kleiner Haufen Steine.}
{9400}{}{Bar}
{9401}{}{Diese moderne Version einer Brennerei könnte man durchaus als Großbrauerei bezeichnen.}
{9500}{}{Sessel}
{9501}{}{Ein verrotteter, alter Sessel, der aus einem alten Autositz hergestellt ist.}
{9600}{}{Sessel}
{9601}{}{Ein stinkender, alter Sessel, der einmal als Autositz gedient hat. Die Federn haben schon Federn gelassen.}
{9700}{}{Sessel}
{9701}{}{Ein verrotteter, stinkender, alter Sessel, der von Steinen gestützt wird. Sieht ziemlich unbequem aus.}
{9800}{}{Couch}
{9801}{}{Ein verrotteter, stinkender, alter Sessel, der von Steinen gestützt wird. Sieht ziemlich unbequem aus.}
{9900}{}{Couch}
{9901}{}{Ein sehr unbequem aussehendes Sitzmöbel, das manchmal auch als Couch bezeichnet wird.}
{10000}{}{Couch}
{10001}{}{Ein sehr unbequem aussehendes Sitzmöbel, das manchmal auch als Couch bezeichnet wird.}
{10100}{}{Reifen}
{10101}{}{Ein alter Gummireifen, der mitten in irgendwelchem Unkraut liegt.}
{10200}{}{Gestrüpp}
{10201}{}{Irgendein Wüstenunkraut.}
{10300}{}{Gestrüpp}
{10301}{}{Irgendein Wüstenunkraut.}
{10400}{}{Gestrüpp}
{10401}{}{Irgendein Wüstenunkraut.}
{10500}{}{Gestrüpp}
{10501}{}{Irgendein Wüstenunkraut.}
{10600}{}{Schrott}
{10601}{}{Eine verrostete Autotür, die an einem verrosteten Metallfaß lehnt. Hier ist alles ziemlich rostig.}
{10700}{}{Schrott}
{10701}{}{Eine kaputte Kloschüssel, die halb im Sand vergraben ist. Das Leben ist Scheiße, und dann stirbst du.}
{10800}{}{Unkraut}
{10801}{}{Irgendein Wüstengestrüpp. Vielleicht ist es noch vor kurzem gewachsen, aber jetzt bestimmt nicht mehr.}
{10900}{}{Schrott}
{10901}{}{Ein Autoreifen, der im Sand vergraben ist. Um ihn herum liegen ein paar Holzstücke.}
{11000}{}{Steine}
{11001}{}{Nach genauerer Betrachtung glaubst du, daß es sich um versteinertes Holz handelt.}
{11100}{}{Erde}
{11101}{}{Ein kleiner Haufen Erde, aus dem ein vergetrocknetes Unkraut hervorragt.}
{11200}{}{Erde}
{11201}{}{Ein kleiner Haufen Erde.}
{11300}{}{Erde}
{11301}{}{Ein kleiner Haufen Erde.}
{11400}{}{Erde}
{11401}{}{Ein kleiner Haufen Erde.}
{11500}{}{Unkraut}
{11501}{}{Ein kleiner Haufen Erde, aus dem ein vergetrocknetes Unkraut hervorragt.}
{11600}{}{Schrott}
{11601}{}{Ein verbogenes Stück rostiges Metall.}
{11700}{}{Müll}
{11701}{}{Einige zerbrochene Holzstücke.}
{11800}{}{Schrott}
{11801}{}{Ein kleiner Haufen aus undefinierbarem Schrott.}
{11900}{}{Erde}
{11901}{}{Ein kleiner Haufen Erde.}
{12000}{}{Erde}
{12001}{}{Ein kleiner Haufen Erde.}
{12100}{}{Erde}
{12101}{}{Ein kleiner Haufen Erde.}
{12200}{}{Erde}
{12201}{}{Ein kleiner Haufen Erde.}
{12300}{}{Erde}
{12301}{}{Ein kleiner Haufen Erde.}
{12400}{}{Erde}
{12401}{}{Ein kleiner Haufen Erde.}
{12500}{}{Unkraut}
{12501}{}{Ein häufig vorkommendes Wüstenunkraut.}
{12600}{}{Unkraut}
{12601}{}{Ein häufig vorkommendes Wüstenunkraut.}
{12700}{}{Unkraut}
{12701}{}{Ein häufig vorkommendes Wüstenunkraut.}
{12800}{}{}
{12900}{}{Wand}
{13000}{}{Wand}
{13100}{}{Wand}
{13200}{}{Wand}
{13300}{}{Wand}
{13400}{}{Wand}
{13500}{}{Abfluß}
{13501}{}{Aus diesem Abfluß dringt ein übler, ekelerregender Geruch. Nach einiger Zeit läßt der Gestank etwas nach.}
{13600}{}{Abfluß}
{13601}{}{Du nimmst die Bewegung hinter diesem Abflußgitter kaum wahr. Kleine, rote Augen starren dich an. Rattenaugen.}
{13700}{}{Abfluß}
{13701}{}{Aus diesem Abfluß dringen gurgelnde Wassergeräusche. Und ein echt übler Gestank.}
{13800}{}{Abfluß}
{13801}{}{Aus diesem Abfluß dringen gurgelnde Wassergeräusche. Und ein echt übler Gestank.}
{13900}{}{Leiter}
{13901}{}{Eine alte, ziemlich wackelige Leiter. Sie sieht nicht so aus, als ob sie dein Gewicht tragen könnte.}
{14000}{}{Kanaleinstieg}
{14001}{}{Sieht wie der Einstieg zu einer Kanalisation aus.}
{14100}{}{Lichtquelle}
{14200}{}{Tür}
{14201}{}{Sieht wie eine normale Vaulttür aus, die beschädigt wurde, eventuell durch Feuer. Sie funktioniert jedoch noch.}
{14300}{}{Tür}
{14301}{}{Sieht wie eine normale Vaulttür aus, die beschädigt wurde, eventuell durch Feuer. Sie funktioniert jedoch noch.}
{14400}{}{Deckel}
{14401}{}{Ein schwerer Schachtdeckel. Sieht gut erhalten aus. Wurde anscheinend vor kurzem bewegt.}
{14500}{}{Loch}
{14501}{}{In diese Tür wurde ein großes Loch gesprengt.}
{14600}{}{Loch}
{14601}{}{In diese Tür wurde ein großes Loch gesprengt.}
{14700}{}{Kugelsicheres Glas}
{14701}{}{Völlig unzerbrechliches Glas. Ein Versuch wäre sinnlos.}
{14800}{}{Kugelsicheres Glas}
{14801}{}{Völlig unzerbrechliches Glas. Ein Versuch wäre sinnlos.}
{14900}{}{Kugelsicheres Glas}
{14901}{}{Völlig unzerbrechliches Glas. Ein Versuch wäre sinnlos.}
{15000}{}{Kugelsicheres Glas}
{15001}{}{Völlig unzerbrechliches Glas. Ein Versuch wäre sinnlos.}
{15100}{}{Tür}
{15101}{}{Diese Tür ist eine Hi-Tech-Konstruktion. Sie öffnet sich durch Ausdehnung, während sich die drei Türelemente gleichzeitig drehen.}
{15200}{}{Tür}
{15201}{}{Diese Tür ist eine Hi-Tech-Konstruktion. Sie öffnet sich durch Ausdehnung, während sich die drei Türelemente gleichzeitig drehen.}
{15300}{}{Tür}
{15301}{}{Diese Tür trägt das Symbol der Brotherhood of Steel.}
{15400}{}{Tür}
{15401}{}{Diese Tür trägt das Symbol der Brotherhood of Steel.}
{15500}{}{Aufzug}
{15501}{}{Das Innere eines Aufzugs der Brotherhood. Er ist total sauber!}
{15600}{}{Aufzug}
{15601}{}{Das Innere eines Aufzugs der Brotherhood. Er ist total sauber!}
{15700}{}{Symbol}
{15701}{}{Das Symbol der Brotherhood of Steel. Dieses Symbol kennzeichnet das Territorium der Brotherhood, welches sofort zu verlassen ist.}
{15800}{}{Monitor}
{15801}{}{Ein Computermonitor. Seine Technologie stammt von der Brotherhood.}
{15900}{}{Monitor}
{15901}{}{Ein Computermonitor. Seine Technologie stammt von der Brotherhood.}
{16000}{}{Computer}
{16001}{}{Eine Computerdatenbank. Offensichtlich stammt ihre Technologie von der Brotherhood.}
{16100}{}{Computer}
{16101}{}{Eine Computerdatenbank. Offensichtlich stammt ihre Technologie von der Brotherhood.}
{16200}{}{Computer}
{16201}{}{Ein Hi-Tech-Computer, der zur Speicherung moderne Magnetbänder statt antiquierter Lochkarten benutzt.}
{16300}{}{Computer}
{16301}{}{Ein Hi-Tech-Computer, der zur Speicherung moderne Magnetbänder statt antiquierter Lochkarten benutzt.}
{16400}{}{Monitor}
{16401}{}{Ein Computermonitor. Seine Technologie stammt von der Brotherhood.}
{16500}{}{Monitor}
{16501}{}{Ein Computermonitor. Seine Technologie stammt von der Brotherhood.}
{16600}{}{Kabel}
{16601}{}{Verschiedene Computerkabel.}
{16700}{}{Kabel}
{16701}{}{Verschiedene Computerkabel.}
{16800}{}{Kabel}
{16801}{}{Verschiedene Computerkabel.}
{16900}{}{Säule}
{16901}{}{Eine Stützsäule.}
{17000}{}{Säule}
{17001}{}{Eine Stützsäule.}
{17100}{}{Türsteuerungscomputer}
{17101}{}{Dieser Computer steuert die große Vaulttür. Du mußt einen bestimmten Zugangscode eingeben, damit sich die Tür öffnet.}
{17200}{}{Kasinoschild}
{17201}{}{Sieht wie eine Werbetafel für Gizmos Kasino aus.}
{17300}{}{Vault 13-Außentür}
{17301}{}{Diese mächtige Tür verbindet die Vault mit der Außenwelt.}
{17400}{}{Vault 13-Außentür}
{17401}{}{Diese mächtige Tür verbindet die Vault mit der Außenwelt.}
{17500}{}{Kasinoschild}
{17501}{}{Dieses Neonschild wird von einem Elektromotor langsam gedreht.}
{17600}{}{Nach unten weisender Pfeil}
{17700}{}{Nach oben weisender Pfeil}
{17800}{}{Kiste}
{17900}{}{Kiste}
{18000}{}{Kiste}
{18100}{}{Aufzugoberseite}
{18101}{}{Ein Teil eines Aufzugs.}
{18200}{}{Computerkonsole}
{18201}{}{Ein einfaches Terminal, das über ein Kabel mit einem Großrechner verbunden ist. Seine Technologie stammt von der Brotherhood.}
{18300}{}{Computerkonsole}
{18301}{}{Ein einfaches Terminal, das über ein Kabel mit einem Großrechner verbunden ist. Seine Technologie stammt von der Brotherhood.}
{18400}{}{Symbol}
{18401}{}{Das Symbol der Brotherhood. Die Zahnräder stehen für ihr Wissen über die Technik, das Schwert für ihre Verteidigungsbereitschaft und die Flügel für die Hoffnung, die sie stärkt.}
{18500}{}{Symbol}
{18501}{}{Das Symbol der Brotherhood. Die Zahnräder stehen für ihr Wissen über die Technik, das Schwert für ihre Verteidigungsbereitschaft und die Flügel für die Hoffnung, die sie stärkt.}
{18600}{}{Schild 'Ebene 1'}
{18601}{}{Du glaubst, daß du dich auf der ersten Ebene der Brotherhood befindest.}
{18700}{}{Schild 'Ebene 2'}
{18701}{}{Du befindest dich auf der zweiten Ebene der Brotherhood.}
{18800}{}{Schild 'Ebene 3'}
{18801}{}{Das muß bedeuten, daß du dich auf der dritten Ebene der Brotherhood befindest.}
{18900}{}{Schild 'Ebene 4'}
{18901}{}{Du mußt auf der vierten Ebene der Brotherhood sein.}
{19000}{}{Etagenbett}
{19001}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{19100}{}{Etagenbett}
{19101}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{19200}{}{Etagenbett}
{19201}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{19300}{}{Kiste}
{19400}{}{Nuka Cola-Automat}
{19401}{}{An der Seite des Automats befindet sich eine Werbung für das beliebte Erfrischungsgetränk.}
{19500}{}{Wand}
{19600}{}{Falltür}
{19601}{}{Sieht wie eine einwandfreie Falltür aus.}
{19700}{}{Schacht}
{19701}{}{Die Leiter in diesem Schacht führt nach unten in die Dunkelheit. Uhhh, wie furchterregend!}
{19800}{}{Altar}
{19801}{}{Ein Altar.}
{19900}{}{Kanzel}
{19901}{}{Es stehen Leute dahinter und reden. Hat anscheinend eine kleine Ablage für das Manuskript des Redners.}
{20000}{}{Kirchenbank}
{20001}{}{Sieht wie erwartet aus. An dieser Kirchenbank gibt es nichts Besonderes.}
{20100}{}{Schild}
{20101}{}{Dieses Schild sieht etwas verrostet aus.}
{20200}{}{Schild}
{20201}{}{Dieses Schild sieht etwas verrostet aus.}
{20300}{}{Schild}
{20301}{}{Dieses Schild sieht etwas verrostet aus.}
{20400}{}{Schild}
{20401}{}{Dieses Schild sieht etwas verrostet aus.}
{20500}{}{Schild}
{20501}{}{Dieses Schild sieht etwas verrostet aus.}
{20600}{}{Alte Matratze}
{20601}{}{Ein alte, heruntergekommene Matratze. Du glaubst darin ein kleines käferähnliches Lebewesen gesehen zu haben.}
{20700}{}{Alte Matratze}
{20701}{}{Selbst wenn du auf diesem Ding alleine schlafen würdest, wärst du nicht allein.}
{20800}{}{Bett}
{20801}{}{Ein provisorisches Bett. Das Material stammt von irgendwoher.}
{20900}{}{Bett}
{20901}{}{Ein provisorisches Bett. Das Material stammt von irgendwoher.}
{21000}{}{Bett}
{21001}{}{Dieses Bett hat schon bessere Tage gesehen. Und Nächte wohl auch!}
{21100}{}{Bett}
{21101}{}{Nach genauerer Betrachtung kommst du zu dem Schluß, daß die Laken schon sehr, sehr lange nicht mehr gewechselt wurden.}
{21200}{}{Bett}
{21201}{}{Auf diesem heruntergekommenen Bett befinden sich ein paar Flecken ungewissen Ursprungs.}
{21300}{}{Bett}
{21301}{}{Dieses Bett ist ziemlich heruntergekommen. Irgend etwas muß in die Matratzenritzen gekrochen und dort verendet sein.}
{21400}{}{Regal}
{21500}{}{Regal}
{21600}{}{Regal}
{21700}{}{Regal}
{21800}{}{Regal}
{21900}{}{Regal}
{22000}{}{Kisten}
{22001}{}{Diese Holzkisten sind so verwittert, daß sie auseinanderfallen.}
{22100}{}{Kisten}
{22101}{}{An diesen Holzkisten gibt es nichts Nennenswertes.}
{22200}{}{Kisten}
{22201}{}{Du hast sehr viel Zeit, dir diesen verrotteten Müll genau anzusehen.}
{22300}{}{Kisten}
{22301}{}{Diese Holzkisten sind so verwittert, daß sie auseinanderfallen.}
{22400}{}{Auto}
{22401}{}{Dieses Auto befindet sich in fürchterlichem Zustand. Du kannst dir nicht vorstellen, daß es noch zu reparieren ist.}
{22500}{}{Auto}
{22501}{}{Aus diesem verrosteten Schrotthaufen läßt sich nichts mehr machen.}
{22600}{}{Auto}
{22601}{}{Du kommst zu dem Schluß, daß dieses Fahrzeug bestimmt nicht mehr in Gang zu setzen ist.}
{22700}{}{Auto}
{22701}{}{Es ist ausgeschlossen, daß dieser Schrotthaufen jemals wieder fahren wird.}
{22800}{}{Auto}
{22801}{}{Selbst wenn der Automechaniker des Jahres plötzlich neben dir auftauchen würde, könntet ihr beide diesen Rosthaufen nicht flottmachen.}
{22900}{}{Sessel}
{22901}{}{Ein bequemer Sessel.}
{23000}{}{Sessel}
{23001}{}{Dieser Sessel hat wohl auch schon bessere Zeiten gesehen.}
{23100}{}{Sessel}
{23101}{}{Dieser Sessel ist verrottet und dreckig. Und wie man sich vorstellen kann, riecht er auch ziemlich übel.}
{23200}{}{Sessel}
{23201}{}{Dieser Sessel löst sich in seine Bestandteile auf. Schnell.}
{23300}{}{Sessel}
{23301}{}{Du würdest dich vielleicht auf diesen Sessel setzen, wenn dir jemand dafür eine Menge Deckel bieten würde und du Hosen aus Stahl tragen könntest.}
{23400}{}{Stuhl}
{23401}{}{Sieht wie ein alter Bürostuhl aus, der nach all den Jahren noch in ziemlich gutem Zustand ist.}
{23500}{}{Stuhl}
{23501}{}{Ein alter Bürostuhl. Er könnte vielleicht sogar das Gewicht einer Person aushalten.}
{23600}{}{Stuhl}
{23601}{}{Dieser Bürostuhl hat auch schon bessere Zeiten gesehen. Jetzt hat er nur noch Schrottwert.}
{23700}{}{Stuhl}
{23701}{}{Sieht wie ein Stuhl aus, den man im Büro eines Leichenbestatters antreffen würde - tot.}
{23800}{}{Schreibtisch}
{23900}{}{Schreibtisch}
{24000}{}{Kommode}
{24100}{}{Kommode}
{24200}{}{Kommode}
{24300}{}{Wasserhydrant}
{24301}{}{Ein Wasserhydrant. Ohne die Vaultsprenkleranlage müßte man damit Feuer löschen.}
{24400}{}{Laterne}
{24401}{}{Diese Laterne scheint noch zu funktionieren. Man stelle sich vor, hier funktioniert noch was!}
{24500}{}{Laterne}
{24501}{}{Diese Laterne wird wohl nie mehr wieder funktionieren.}
{24600}{}{Laterne}
{24601}{}{Eine funktionierende Laterne. Nachts wirft sie ein zartes, bleiches Licht, das dich an rein gar nichts erinnert.}
{24700}{}{Laterne}
{24701}{}{Eine kaputte Laterne. Sie läßt sich nicht mehr reparieren.}
{24800}{}{Laterne}
{24801}{}{Diese Beleuchtung funktioniert noch.}
{24900}{}{Laterne}
{24901}{}{Die Lampe ist so kaputt, daß sie sich nicht mehr reparieren läßt.}
{25000}{}{Laterne}
{25001}{}{Eine funktionierende Laterne.}
{25100}{}{Tor}
{25101}{}{Das Schloß an diesem Tor klemmt, und die Stäbe sehen sehr stabil aus.}
{25200}{}{Schrott}
{25201}{}{Mit Sicherheit nutzloser Schrott. Kein Zweifel!}
{25300}{}{Schrott}
{25301}{}{Mit Sicherheit nutzloser Schrott. Kein Zweifel!}
{25400}{}{Schrott}
{25401}{}{Mit Sicherheit nutzloser Schrott. Kein Zweifel!}
{25500}{}{Schrott}
{25501}{}{Mit Sicherheit nutzloser Schrott. Kein Zweifel!}
{25600}{}{Schrott}
{25601}{}{Mit Sicherheit nutzloser Schrott. Kein Zweifel!}
{25700}{}{Briefkasten}
{25701}{}{Der Briefkasten ist leer. Du hast das Gefühl, daß er schon seit einer ganzen Weile leer ist.}
{25800}{}{Tür}
{25801}{}{Eine kunstvoll gefertigte Holztür in gutem Zustand.}
{25900}{}{Tür}
{25901}{}{Eine kunstvoll gefertigte Holztür in gutem Zustand.}
{26000}{}{Tür}
{26001}{}{Eine kunstvoll gefertigte Holztür in gutem Zustand.}
{26100}{}{Tür}
{26101}{}{Eine kunstvoll gefertigte Holztür in gutem Zustand.}
{26200}{}{Kirchenbank}
{26201}{}{Diese hölzerne Kirchenbank fällt langsam auseinander.}
{26300}{}{Kirchenbank}
{26301}{}{Diese Kirchenbank sieht vergammelt und abgenutzt aus.}
{26400}{}{Kirchenbank}
{26401}{}{Eine hölzerne Kirchenbank, die altersschwach und abgenutzt ist.}
{26500}{}{Zeitungsautomat}
{26501}{}{Der Zeitungsautomat ist leer.}
{26600}{}{Zeitungsautomat}
{26601}{}{Der Zeitungsautomat ist leer.}
{26700}{}{Zeitungsautomat}
{26701}{}{Der Zeitungsautomat ist leer.}
{26800}{}{Zeitungsautomat}
{26801}{}{Der Zeitungsautomat ist leer.}
{26900}{}{Zeitungsautomat}
{26901}{}{Der Zeitungsautomat ist leer.}
{27000}{}{Zeitungsautomat}
{27001}{}{Der Zeitungsautomat ist leer. Darin befanden sich anscheinend einmal Zeitschriften für Erwachsene.}
{27100}{}{Müll}
{27101}{}{Eine Bettdecke in furchtbarem Zustand. Selbst Ratten würden darin oder darauf nicht schlafen.}
{27200}{}{Müll}
{27201}{}{Eine große Bettdecke, die schon bessere Zeiten als diese gesehen hat.}
{27300}{}{Müll}
{27301}{}{Ein Haufen verrottetes, verwittertes Holz. Ist nicht mal sein Gewicht in irgend etwas wert.}
{27400}{}{Müll}
{27401}{}{Ein Haufen Holz, in dem einige nutzlose rostige Nägel vergraben sind.}
{27500}{}{Kartons}
{27501}{}{Ein Haufen alter Pappkartons. Du kannst kaum fassen, daß sie hier so lange überlebt haben.}
{27600}{}{Kartons}
{27601}{}{Ein Haufen alter Pappkartons.}
{27700}{}{Müll}
{27701}{}{Ein Haufen Müll, der vor seiner Zerstörung durch Unwelteinflüsse eine Bettdecke hätte gewesen sein können.}
{27800}{}{Steine}
{27900}{}{Steine}
{28000}{}{Steine}
{28100}{}{Schutt}
{28101}{}{Ein kleiner Haufen Schutt und Steine. Paß auf, wo du hintrittst!}
{28200}{}{Becken}
{28201}{}{Ein Becken aus Porzellan, das schon lange kaputt ist.}
{28300}{}{Becken}
{28301}{}{Ein kaputtes Becken aus Porzellan. Darin steht eine kleine braune Wasserpfütze, in der eine tote Ratte treibt.}
{28400}{}{Becken}
{28401}{}{Dieses Becken ist kaputt. Du siehst dies an dem großen Sprung in der Mitte.}
{28500}{}{Becken}
{28501}{}{Ein kaputtes Becken aus Porzellan. Darin steht eine kleine braune Wasserpfütze, in der eine tote Ratte treibt.}
{28600}{}{Stoppschild}
{28601}{}{Ein rotes Schild, auf dem das Wort STOP in großen Blockbuchstaben steht.}
{28700}{}{Stoppschild}
{28701}{}{Ein rotes Schild, auf dem das Wort STOP in großen Blockbuchstaben steht. Das große Einschußloch ist erst später entstanden.}
{28800}{}{Ampel}
{28801}{}{Ein altes Gerät zur Regelung des Autoverkehrs.}
{28900}{}{Ampel}
{28901}{}{Ein altes Gerät zur Regelung des Autoverkehrs.}
{29000}{}{Ampel}
{29001}{}{Ein altes Gerät zur Regelung des Autoverkehrs.}
{29100}{}{Straßenlaterne}
{29101}{}{Diese Straßenlaterne sorgt bei Nacht oder in dunklen Gegenden für Licht.}
{29200}{}{Straßenlaterne}
{29201}{}{Diese Straßenlaterne sorgt bei Nacht oder in dunklen Gegenden für Licht.}
{29300}{}{Straßenlaterne}
{29301}{}{Diese Straßenlaterne sorgt bei Nacht oder in dunklen Gegenden für Licht.}
{29400}{}{Straßenlaterne}
{29401}{}{Diese Straßenlaterne sorgt bei Nacht oder in dunklen Gegenden für Licht.}
{29500}{}{Straßenlaterne}
{29501}{}{Diese Straßenlaterne könnte bei Nacht oder in dunklen Gegenden für Licht sorgen, wenn sie nicht völlig kaputt wäre.}
{29600}{}{Straßenlaterne}
{29601}{}{Diese Straßenlaterne könnte bei Nacht oder in dunklen Gegenden für Licht sorgen, wenn sie nicht völlig kaputt wäre.}
{29700}{}{Straßenlaterne}
{29701}{}{Diese Straßenlaterne könnte bei Nacht oder in dunklen Gegenden für Licht sorgen, wenn sie nicht völlig kaputt wäre.}
{29800}{}{Straßenschild}
{29801}{}{Auf diesem Schild sollte eigentlich der Straßenname stehen, aber die Buchstaben sind nicht mehr zu entziffern.}
{29900}{}{Straßenschild}
{29901}{}{Auf diesem Schild sollte eigentlich der Straßenname stehen, aber die Buchstaben sind nicht mehr zu entziffern.}
{30000}{}{Tisch}
{30001}{}{Ein Holztisch in gutem bis mittelmäßigem Zustand.}
{30100}{}{Tisch}
{30101}{}{Ein Holztisch in gutem bis mittelmäßigem Zustand.}
{30200}{}{Tisch}
{30201}{}{Ein Holztisch in mittelmäßigem bis schlechtem Zustand.}
{30300}{}{Tisch}
{30301}{}{Ein Holztisch mit einer Kunststoffplatte, der schon seit einiger Zeit kaputt ist.}
{30400}{}{Tisch}
{30401}{}{Ein mit kotzgrüner Farbe angestrichener Holztisch, der nicht mehr zu reparieren ist.}
{30500}{}{Tisch}
{30501}{}{Sieht wie ein alter Couchtisch aus. Ziemlich niedrig, gerade richtig für diese winzigen Mutanten.}
{30600}{}{Tisch}
{30601}{}{Sieht wie ein alter Couchtisch aus. Ziemlich niedrig, gerade richtig für diese winzigen Mutanten.}
{30700}{}{Toilette}
{30701}{}{Die scharfen Kanten an der Klobrille laden nicht gerade zum Hinsetzen ein.}
{30800}{}{Toilette}
{30801}{}{Diese Toilette ist kaputt.}
{30900}{}{Toilette}
{30901}{}{Igitt! Der letzte Benutzer hat nicht abgezogen!}
{31000}{}{Toilette}
{31001}{}{Diese Toilette ist kaputt und bestimmt nicht für Frauen geeignet.}
{31100}{}{Schrott}
{31101}{}{Einige zerborstene Rohrleitungen, die halb im Sand vergraben sind. Hier gibt es nichts Wichtiges zu sehen. Geh weiter.}
{31200}{}{Müll}
{31201}{}{Ein paar Glasscherben und anderer wertloser Müll.}
{31300}{}{Müll}
{31301}{}{Ein paar Glasscherben und anderer wertloser Müll.}
{31400}{}{Schrott}
{31401}{}{Ein Rohr, das in zwei Teile gebrochen ist. Es scheint vor lauter Rost unter seinem eigenen Gewicht zusammengebrochen zu sein.}
{31500}{}{Mülltonne}
{31501}{}{Eine Mülltonne. Du kannst kaum die Aufschrift darauf lesen.}
{31600}{}{Baum}
{31601}{}{Ein toter Baum.}
{31700}{}{Baum}
{31701}{}{Ein Baumstumpf. Nichts Aufregendes, wahrscheinlich das Unspektakulärste, was du je gesehen hast.}
{31800}{}{Baum}
{31801}{}{Ein toter Baum.}
{31900}{}{Baum}
{32000}{}{Baum}
{32100}{}{Baum}
{32200}{}{LKW}
{32300}{}{LKW}
{32301}{}{Die verrotteten Überreste eines Diesel-LKW. Dieser Metallkoloß wird wohl nie wieder rollen.}
{32400}{}{LKW}
{32401}{}{Für diesen Diesel-LKW kommt jede Hilfe zu spät. Viel zu spät.}
{32500}{}{Badewanne}
{32501}{}{Diese Badewanne ist kaputt und hat Sprünge.}
{32600}{}{Badewanne}
{32601}{}{Nach genauerer Betrachtung kommst du zu dem Schluß, daß du in dieser Wanne doch kein Bad nehmen willst.}
{32700}{}{Pissoir}
{32701}{}{Nur ein Pissoir.}
{32800}{}{Pissoir}
{32801}{}{Nur ein Pissoir.}
{32900}{}{Pissoir}
{32901}{}{Nur ein Pissoir. Nichts Besonderes daran.}
{33000}{}{Pissoir}
{33001}{}{Nur ein Pissoir. Nichts Besonderes daran.}
{33100}{}{Wassertank}
{33101}{}{Ein großer Tank für Flüssigkeiten. In diesem Fall glaubst du, daß er für Wasser benutzt wurde.}
{33200}{}{Tür}
{33201}{}{Eine Holztür. Nichts besonderes Interessantes daran.}
{33300}{}{Tür}
{33301}{}{Eine Holztür. Sie dient als Eingang und Ausgang für dieses Gebäude.}
{33400}{}{Wandleuchte}
{33401}{}{Diese Leuchte scheint noch zu funktionieren.}
{33500}{}{Wandleuchte}
{33501}{}{Eine kaputte Leuchte. Es überrascht nicht, daß sie nicht mehr funktioniert.}
{33600}{}{Wandleuchte}
{33601}{}{Diese Leuchte scheint noch zu funktionieren.}
{33700}{}{Wandleuchte}
{33701}{}{Eine kaputte Leuchte. Es überrascht nicht, daß sie nicht mehr funktioniert.}
{33800}{}{Wandleuchte}
{33801}{}{Diese Leuchte scheint noch zu funktionieren.}
{33900}{}{Wandleuchte}
{33901}{}{Eine kaputte Leuchte. Es überrascht nicht, daß sie nicht mehr funktioniert.}
{34000}{}{Wandleuchte}
{34001}{}{Diese Leuchte scheint noch zu funktionieren.}
{34100}{}{Wandleuchte}
{34101}{}{Eine kaputte Leuchte. Es überrascht nicht, daß sie nicht mehr funktioniert.}
{34200}{}{Vorfahrtsschild}
{34201}{}{Dieses Schild wurde zur Regelung des Verkehrs eingesetzt.}
{34300}{}{Vorfahrtsschild}
{34301}{}{Dieses Schild ist verblichen, aber du kannst noch erkennen, daß es sich um ein Vorfahrtsschild handelt.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{Wenn du diesen Text siehst, hat der technische Designer gepennt!}
{34500}{}{Boden}
{34600}{}{Tür}
{34601}{}{Eine verzierte Holztür. Offensichtlich das Ergebnis großer Handwerkskunst.}
{34700}{}{Kirchenbank}
{34701}{}{Diese Bank wird von großen Betonklötzen gestützt. Das ist zwar unwichtig, aber du wolltest es ja wissen!}
{34800}{}{Treppe}
{34801}{}{Diese Treppe führt nach oben.}
{34900}{}{Treppe}
{34901}{}{Diese Treppe führt nach oben.}
{35000}{}{Treppe}
{35001}{}{Diese Treppe führt nach oben.}
{35100}{}{Treppe}
{35101}{}{Diese Treppe führt nach oben.}
{35200}{}{Treppe}
{35201}{}{Diese Treppe führt nach oben.}
{35300}{}{Treppe}
{35301}{}{Diese Treppe führt nach oben.}
{35400}{}{Treppe}
{35401}{}{Diese Treppe führt nach oben.}
{35500}{}{Treppe}
{35501}{}{Diese Treppe führt nach oben.}
{35600}{}{Treppe}
{35601}{}{Diese Treppe führt nach unten.}
{35700}{}{Wand}
{35701}{}{Du siehst die Außenseite der Kathedrale.}
{35800}{}{Wand}
{35801}{}{Du siehst die Außenseite der Kathedrale.}
{35900}{}{Wand}
{35901}{}{Du siehst die Außenseite der Kathedrale.}
{36000}{}{Wand}
{36001}{}{Du siehst die Außenseite der Kathedrale.}
{36100}{}{Vorhang}
{36101}{}{Dieser Vorhang scheint mit primitiven Mitteln gefertigt worden zu sein, aber er erfüllt seine Funktion.}
{36200}{}{Vorhang}
{36201}{}{Dieser Vorhang scheint mit primitiven Mitteln gefertigt worden zu sein, aber er erfüllt seine Funktion.}
{36300}{}{Schale}
{36301}{}{Eine kunstvoll gefertigte Holzschale. Diente wahrscheinlich zum Zermahlen und Trennen von Körnern.}
{36400}{}{Schale}
{36401}{}{Eine kunstvoll gefertigte Holzschale.}
{36500}{}{Topf}
{36501}{}{Ein kunstvoll gefertigter Topf.}
{36600}{}{Pflanze}
{36601}{}{Sieht für dich wie ein mutierter Kohl aus. Scheint bei dem warmen Wetter gut zu gedeihen.}
{36700}{}{Pflanze}
{36701}{}{Sieht für dich wie ein mutierter Kohl aus. Scheint bei dem warmen Wetter gut zu gedeihen.}
{36800}{}{Karren}
{36801}{}{Ein einfacher, aber praktischer Karren für die Landwirtschaft.}
{36900}{}{Pflanze}
{36901}{}{Eine mutierte Maispflanze. Scheint bei diesen Bedingungen gut zu gedeihen.}
{37000}{}{Pflanze}
{37001}{}{Eine mutierte Maispflanze. Scheint bei diesen Bedingungen gut zu gedeihen.}
{37100}{}{Pflanze}
{37101}{}{Eine mutierte Maispflanze. Scheint bei diesen Bedingungen gut zu gedeihen.}
{37200}{}{Topf}
{37201}{}{Ein kunstvoll gefertigter Tontopf.}
{37300}{}{Rechen}
{37301}{}{Dieser Rechen gehört seinen Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{37400}{}{Rechen}
{37401}{}{Dieser Rechen gehört seinen Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{37500}{}{Rechen}
{37501}{}{Dieser Rechen gehört seinen Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{37600}{}{Teppich}
{37601}{}{Ein einfacher Teppich, offensichtlich von talentierten Händen gewebt.}
{37700}{}{Teppich}
{37701}{}{Ein einfacher Teppich, offensichtlich von talentierten Händen gewebt.}
{37800}{}{Teppich}
{37801}{}{Ein einfacher Teppich, offensichtlich von talentierten Händen gewebt.}
{37900}{}{Schaufel}
{37901}{}{Diese Schaufel gehört ihren Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{38000}{}{Schaufel}
{38001}{}{Diese Schaufel gehört ihren Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{38100}{}{Schaufel}
{38101}{}{Diese Schaufel gehört ihren Eigentümern. Du hast keinen blassen Schimmer, was man damit machen kann.}
{38200}{}{Vase}
{38201}{}{Eine sehr hübsche Tonvase.}
{38300}{}{Brunnen}
{38301}{}{Dir fällt einfach keine Möglichkeit ein, wie man diesen Brunnen zur Vault transportieren könnte.}
{38400}{}{Stange}
{38401}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{38500}{}{Stange}
{38501}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{38600}{}{Stange}
{38601}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{38700}{}{Stange}
{38701}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{38800}{}{Stange}
{38801}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{38900}{}{Stange}
{38901}{}{Diese Stange stützt die Zeltkonstruktion ab.}
{39000}{}{Vaulttür}
{39001}{}{Diese Vaulttür besteht jetzt nur noch aus ein paar schweren Schrotteilen.}
{39100}{}{Wand}
{39101}{}{Der Mechanismus zum Öffnen und Schließen der schweren Vaulttür wurde komplett zerstört.}
{39200}{}{Stütze}
{39201}{}{Diese Stütze verstärkt die Verteidigungsmauer.}
{39300}{}{Stütze}
{39301}{}{Diese Stütze verstärkt die Verteidigungsmauer.}
{39400}{}{Stütze}
{39401}{}{Diese Stütze verstärkt die Verteidigungsmauer.}
{39500}{}{Stütze}
{39501}{}{Diese Stütze verstärkt die Verteidigungsmauer.}
{39600}{}{Metallfaß}
{39601}{}{Ein leeres, rostiges Metallfaß.}
{39700}{}{Metallfaß}
{39701}{}{Dem hohlen Klang nach zu schließen, ist dieses Faß wohl leer.}
{39800}{}{Metallfässer}
{39801}{}{Dem hohlen Klang nach zu schließen, sind diese Fässer wohl leer.}
{39900}{}{Metallfässer}
{39901}{}{Dem hohlen Klang nach zu schließen, sind diese Fässer wohl leer.}
{40000}{}{Kuppel}
{40001}{}{Auf einem kleinen Etikett kannst du entziffern, daß dies das Eigentum der Area-51 ist, das beim Eigentümer abzugeben ist.}
{40100}{}{Kiste}
{40101}{}{Eine Holzkiste. Gar nicht mal in so schlechtem Zustand.}
{40200}{}{Kiste}
{40201}{}{Eine einfache Holzkiste. In ziemlich gutem Zustand.}
{40300}{}{Kiste}
{40301}{}{Diese einfache Holzkiste ist unter ihrem eigenen Gewicht zusammengebrochen.}
{40400}{}{Schreibtisch}
{40401}{}{Ein einfacher Schreibtisch mit einem Computer.}
{40500}{}{Schreibtisch}
{40501}{}{Ein einfacher Schreibtisch mit einem Computer.}
{40600}{}{Tür}
{40601}{}{Eine Holztür in relativ gutem Zustand.}
{40700}{}{Schutt}
{40701}{}{Ein großer Haufen Steine, die sich nur schwer beseitigen lassen.}
{40800}{}{Auto}
{40801}{}{Dieses versunkene Auto läßt sich nicht mehr reparieren.}
{40900}{}{Auto}
{40901}{}{Dieses Auto ist etwas feucht und läßt sich nicht mehr reparieren.}
{41000}{}{Auto}
{41001}{}{Dieses Auto wurde schlecht geparkt. Leider läßt es sich nicht mehr reparieren.}
{41100}{}{Schrott}
{41101}{}{Dieser Schrott ist von dem verseuchten Meerwasser zerfressen.}
{41200}{}{Schrott}
{41201}{}{Dieser Schrott ist fast schon weggespült.}
{41300}{}{Schrott}
{41301}{}{Eine besondere Auswahl nutzlosen Schrotts.}
{41400}{}{Rohrleitungen}
{41401}{}{Über diese Rohrleitungen wurde Kraftstoff von einem unterirdischen Tank zur Tankstelle geleitet. Sie werden schon lange nicht mehr benutzt.}
{41500}{}{Rohrleitungen}
{41501}{}{Über diese Rohrleitungen wurde Kraftstoff von einem unterirdischen Tank zur Tankstelle geleitet. Sie werden schon lange nicht mehr benutzt.}
{41600}{}{Rohrleitungen}
{41601}{}{Über diese Rohrleitungen wurde Kraftstoff von einem unterirdischen Tank zur Tankstelle geleitet. Sie werden schon lange nicht mehr benutzt.}
{41700}{}{Aufzugschacht}
{41701}{}{Teil eines Aufzugsystems.}
{41800}{}{Aufzugschacht}
{41801}{}{Ein Aufzugschacht, der tief in die Erde reicht. Er ist beschädigt.}
{41900}{}{Aufzug}
{41901}{}{Ein Aufzug, mit dem du von einer Ebene zur anderen fahren kannst.}
{42000}{}{Aufzugschacht}
{42001}{}{Ein Aufzugschacht, der tief in die Erde reicht. Er ist beschädigt.}
{42100}{}{Aufzugtür}
{42101}{}{Diese Tür führt zur Aufzugkabine. Wenn du den Aufzug benutzen willst, mußt du zuerst diese Tür öffnen.}
{42200}{}{Rohr}
{42201}{}{Ein Metallrohr. Weitere Einzelheiten sind unwichtig.}
{42300}{}{Erde}
{42400}{}{Kiste}
{42500}{}{Kiste}
{42600}{}{Kiste}
{42700}{}{Kiste}
{42800}{}{Steine}
{42801}{}{Ein Haufen Steine. Nicht sehr interessant.}
{42900}{}{Steine}
{42901}{}{Ein Haufen Steine. Nicht sehr interessant.}
{43000}{}{Steine}
{43001}{}{Ein kleiner Haufen Steine. Für dich nicht von geringstem Interesse.}
{43100}{}{Steine}
{43101}{}{Ein sehr kleiner Haufen Steine.}
{43200}{}{Steine}
{43201}{}{Ein sehr kleiner Haufen Steine.}
{43300}{}{Steine}
{43301}{}{Ein sehr kleiner Haufen Steine.}
{43400}{}{Steine}
{43401}{}{Ein sehr kleiner Haufen Steine.}
{43500}{}{Steine}
{43501}{}{Ein sehr kleiner Haufen Steine.}
{43600}{}{Vaulttür}
{43601}{}{Diese Vaulttür ähnelt der Tür von Vault 13 ziemlich. Der Türmechanismus wurde deaktiviert.}
{43700}{}{Tür}
{43701}{}{Eine aufwendig konstruierte Holztür, verstärkt durch Metallbeschläge mit fast hypnotischem Design.}
{43800}{}{Tür}
{43801}{}{Eine aufwendig konstruierte Holztür, verstärkt durch Metallbeschläge mit fast hypnotischem Design.}
{43900}{}{Container}
{43901}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44000}{}{Container}
{44001}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44100}{}{Container}
{44101}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44200}{}{Container}
{44201}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44300}{}{Container}
{44301}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44400}{}{Container}
{44401}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44500}{}{Container}
{44501}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44600}{}{Container}
{44601}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{44700}{}{Wand}
{44800}{}{Tür}
{44801}{}{Eine Sicherheitstür. Sieht schwer gepanzert aus.}
{44900}{}{Atomarer Sprengkopf}
{45000}{}{Brunnen}
{45001}{}{Dir fällt einfach keine Möglichkeit ein, wie man diesen Brunnen zur Vault transportieren könnte.}
{45100}{}{Würfelspieltisch}
{45101}{}{Ein Tisch, an dem man spielen kann.}
{45200}{}{Würfelspieltisch}
{45201}{}{Ein Tisch, an dem man spielen kann.}
{45300}{}{Würfelspieltisch}
{45301}{}{Ein Tisch, an dem man spielen kann.}
{45400}{}{Würfelspieltisch}
{45401}{}{Ein Tisch, an dem man spielen kann.}
{45500}{}{Würfelspieltisch}
{45501}{}{Ein Tisch, an dem man spielen kann.}
{45600}{}{Würfelspieltisch}
{45601}{}{Ein Tisch, an dem man spielen kann.}
{45700}{}{Würfelspieltisch}
{45701}{}{Ein Tisch, an dem man spielen kann.}
{45800}{}{Würfelspieltisch}
{45801}{}{Ein Tisch, an dem man spielen kann.}
{45900}{}{Würfelspieltisch}
{45901}{}{Ein Tisch, an dem man spielen kann.}
{46000}{}{Würfelspieltisch}
{46001}{}{Ein Tisch, an dem man spielen kann.}
{46100}{}{Stein}
{46101}{}{Ein kleiner Stein. Im Rahmen dieser Geschichte völlig uninteressant!}
{46200}{}{Stein}
{46300}{}{Stein}
{46400}{}{Stein}
{46500}{}{Spielautomat}
{46501}{}{Ein Automat, an dem man spielen kann.}
{46600}{}{Spielautomat}
{46601}{}{Ein Automat, an dem man spielen kann.}
{46700}{}{Türöffnung}
{46800}{}{Aufzug}
{46900}{}{Aufzug}
{47000}{}{Aufzugtür}
{47100}{}{Fenster}
{47101}{}{Statt Glas wurde in dieses Fenster Wachspapier eingesetzt.}
{47200}{}{Fenster}
{47201}{}{Statt Glas wurde in dieses Fenster Wachspapier eingesetzt.}
{47300}{}{Fenster}
{47301}{}{Statt Glas wurde in dieses Fenster Wachspapier eingesetzt.}
{47400}{}{Fenster}
{47401}{}{Statt Glas wurde in dieses Fenster Wachspapier eingesetzt.}
{47500}{}{Tür}
{47501}{}{Diese große Metallschiebetür wurde von innen verriegelt.}
{47600}{}{Tür}
{47601}{}{Diese große Metallschiebetür wurde von innen verriegelt.}
{47700}{}{Tür}
{47701}{}{Diese große Metallschiebetür wurde von innen verriegelt. Du liest darauf, daß hier ausschließlich Be- und Entladebereich ist.}
{47800}{}{Tür}
{47801}{}{Diese große Metallschiebetür wurde von innen verriegelt.}
{47900}{}{Tür}
{47901}{}{Diese große Metallschiebetür wurde von innen verriegelt.}
{48000}{}{Tür}
{48001}{}{Diese große Metallschiebetür wurde von innen verriegelt. Du liest darauf, daß hier ausschließlich Be- und Entladebereich ist.}
{48100}{}{Tür}
{48101}{}{Diese Tür sieht verdächtig nach der Tür eines Lagerhauses aus.}
{48200}{}{Tür}
{48201}{}{Diese Tür sieht verdächtig nach der Tür eines Lagerhauses aus.}
{48300}{}{Wetterfahne}
{48301}{}{Diese einfache Wetterfahne zeigt den Menschen von Shady Sands das Wetter an.}
{48400}{}{Altar}
{48401}{}{Ein einfacher Altar aus lackiertem Holz.}
{48500}{}{Podium}
{48501}{}{Dieses Podium sieht ganz normal aus, mit der Ausnahme, daß das Symbol der Children of the Cathedral auf der Vorderseite eingraviert ist.}
{48600}{}{Altar}
{48700}{}{Bildschirm}
{48701}{}{Ein großer Schwarz-Weiß-Bildschirm, leider keine Farbe. Recht guter Empfang dafür, daß er drinnen steht und keine Antenne hat.}
{48800}{}{Bildschirm}
{48801}{}{Ein großer Schwarz-Weiß-Bildschirm, leider keine Farbe. Die Person mit der Robe rezitiert religiöse Dogmen in fieberhafter Geschwindigkeit.}
{48900}{}{Kraftfeld}
{48901}{}{Ein starkes Energiefeld.}
{49000}{}{Kraftfeld}
{49001}{}{Ein starkes Energiefeld.}
{49100}{}{Kraftfeld}
{49101}{}{Ein starkes Energiefeld.}
{49200}{}{Kraftfeld}
{49201}{}{Ein starkes Energiefeld.}
{49300}{}{Tisch}
{49301}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49400}{}{Tisch}
{49401}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49500}{}{Tisch}
{49501}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49600}{}{Tisch}
{49601}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49700}{}{Tisch}
{49701}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49800}{}{Tisch}
{49801}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49900}{}{Regal}
{50000}{}{Regal}
{50100}{}{Regal}
{50200}{}{Regal}
{50300}{}{Regal}
{50400}{}{Regal}
{50500}{}{Regal}
{50501}{}{Ein einfacher Altar aus lackiertem Holz.}
{50600}{}{Altar}
{50601}{}{Ein einfacher Altar aus lackiertem Holz.}
{50700}{}{Altar}
{50701}{}{Ein einfacher Altar aus lackiertem Holz.}
{50800}{}{Altar}
{50801}{}{Ein einfacher Altar aus lackiertem Holz.}
{50900}{}{Schutt}
{50901}{}{Dieser Schutthaufen besteht aus Teilen, die von einem Dach heruntergebrochen sind. Dein Seil führt zurück an die Oberfläche.}
{51000}{}{Regal}
{51100}{}{Regal}
{51200}{}{Regal}
{51300}{}{Regal}
{51400}{}{Regal}
{51500}{}{Regal}
{51600}{}{Tisch}
{51601}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{51700}{}{Tisch}
{51701}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{51800}{}{Tisch}
{51801}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{51900}{}{Tisch}
{51901}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{52000}{}{Tisch}
{52001}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{52100}{}{Tisch}
{52101}{}{Dieser Tisch sieht wichtig aus. Vielleicht werden hier Besprechungen abgehalten.}
{52200}{}{Altar}
{52201}{}{Ein Altar der Brotherhood of Steel. Ihr Symbol wird offen gezeigt.}
{52300}{}{Altar}
{52301}{}{Ein Altar der Brotherhood of Steel. Ihr Symbol wird offen gezeigt.}
{52400}{}{Altar}
{52401}{}{Ein Altar der Brotherhood of Steel. Ihr Symbol wird offen gezeigt.}
{52500}{}{Kirchenbank}
{52501}{}{Eine sehr schöne, aber auch sehr unbequem aussehende Kirchenbank.}
{52600}{}{Podium}
{52601}{}{Ein schönes Podium aus Holz. Es ist mit einem Teleprompter für den Redner ausgestattet.}
{52700}{}{Anhänger}
{52701}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{52800}{}{Anhänger}
{52801}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{52900}{}{Anhänger}
{52901}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{53000}{}{Anhänger}
{53001}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{53100}{}{Anhänger}
{53101}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{53200}{}{Anhänger}
{53201}{}{Ein Caravan-Anhänger, der aus den Überresten eines alten Autos zusammengebaut wurde.}
{53300}{}{Matte}
{53301}{}{Eine Trainingsmatte.}
{53400}{}{Matte}
{53401}{}{Eine Trainingsmatte.}
{53500}{}{Matte}
{53501}{}{Eine Trainingsmatte.}
{53600}{}{Matte}
{53601}{}{Eine Trainingsmatte.}
{53700}{}{Sandsack}
{53701}{}{Ein Sandsack der Firma StrongMan(tm).}
{53800}{}{Stepper}
{53801}{}{Ein Fitneßgerät.}
{53900}{}{Stepper}
{54000}{}{Tretmühle}
{54001}{}{Ein Fitneßgerät.}
{54100}{}{Tretmühle}
{54101}{}{Ein Fitneßgerät.}
{54200}{}{Hantelbank}
{54201}{}{Ein Fitneßgerät.}
{54300}{}{Hantelbank}
{54301}{}{Ein Fitneßgerät.}
{54400}{}{Brücke}
{54401}{}{Über diese provisorische Holzbrücke kann man den Graben mit dem grün leuchtenden Schleim überqueren.}
{54500}{}{Brücke}
{54501}{}{Über diese provisorische Holzbrücke kann man den Graben mit dem grün leuchtenden Schleim überqueren.}
{54600}{}{Roulette-Tisch}
{54601}{}{Ein Tisch, an dem man spielen kann.}
{54700}{}{Roulette-Tisch}
{54701}{}{Ein Tisch, an dem man spielen kann.}
{54800}{}{Roulette-Tisch}
{54801}{}{Ein Tisch, an dem man spielen kann.}
{54900}{}{Roulette-Tisch}
{54901}{}{Ein Tisch, an dem man spielen kann.}
{55000}{}{Roulette-Tisch}
{55001}{}{Ein Tisch, an dem man spielen kann.}
{55100}{}{Faß}
{55101}{}{Auf der Seite dieses leeren Metallfasses befindet sich ein hellgelber Aufkleber mit dem Atomsymbol.}
{55200}{}{Faß}
{55201}{}{Dieses Faß enthält einen grün leuchtenden Schleim. Das Atomsymbol läßt auf die Art der darin enthaltenen Substanz schließen.}
{55300}{}{Computer}
{55301}{}{Ein sehr modern aussehender Computer.}
{55400}{}{Computer}
{55401}{}{Ein sehr modern aussehender Computer.}
{55500}{}{Tauchbehälter}
{55501}{}{Irgendein Medizin- oder Versuchsbehälter. Der Größe nach könnte sich darin ein menschlicher oder ähnlich großer Körper befinden.}
{55600}{}{Kaputter Tauchbehälter}
{55601}{}{Eine kaputter Behälter, der sich nicht mehr reparieren läßt.}
{55700}{}{Großrechner}
{55701}{}{Ein großer Supercomputer. Wahrscheinlich der schnellste Computer, den du je gesehen hast.}
{55800}{}{Unterbau}
{55801}{}{Auf diesem Unterbau steht der große Supercomputer über den Kühltanks.}
{55900}{}{Nicht benutzen}
{56000}{}{Nicht benutzen}
{56100}{}{Bett}
{56101}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{56200}{}{Bett}
{56201}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{56300}{}{Bett}
{56301}{}{Ein Etagenbett wie beim Militär. Sieht äußerst unbequem aus. Das Bettuch ist so straff gespannt, daß man darauf eine Münze hüpfen lassen könnte.}
{56400}{}{Kabel}
{56401}{}{Sieht wie irgendein serielles Kabel aus.}
{56500}{}{Kabel}
{56501}{}{Sieht wie irgendein serielles Kabel aus.}
{56600}{}{Schild}
{56601}{}{Auf dem Schild steht 'BAR'. Ziemlich selbsterklärend.}
{56700}{}{Balken}
{56701}{}{Dieser starke Balken befindet sich über dem Kraterloch.}
{56800}{}{Balken}
{56801}{}{An dem Balken ist ein Seil befestigt. Sieht so aus, als ob du jetzt in den Krater hinuntersteigen kannst.}
{56900}{}{Regale}
{56901}{}{Einige vollkommen leere Metallregale.}
{57000}{}{Regale}
{57001}{}{Einige vollkommen leere Metallregale.}
{57100}{}{Regale}
{57101}{}{Einige vollkommen leere Metallregale.}
{57200}{}{Regale}
{57201}{}{Einige vollkommen leere Metallregale.}
{57300}{}{Busch}
{57301}{}{Irgendein Wüstenunkraut. Nicht wichtig für diese Geschichte.}
{57400}{}{Busch}
{57401}{}{Irgendein Wüstenunkraut.}
{57500}{}{Busch}
{57501}{}{Irgendein Wüstenunkraut.}
{57600}{}{Boden}
{57601}{}{Eine schöne Sicht auf die Boneyards von diesem Turm aus. Du kriegst ein gutes Gefühl dafür, wie hoch du bist.}
{57700}{}{Boden}
{57701}{}{Eine schöne Sicht auf die Boneyards von diesem Turm aus.}
{57800}{}{Mauer}
{57801}{}{Eine gute Sicht auf das Äußere der Kathedrale.}
{57900}{}{Mauer}
{57901}{}{Eine gute Sicht auf das Äußere der Kathedrale.}
{58000}{}{Mauer}
{58001}{}{Eine gute Sicht auf das Äußere der Kathedrale.}
{58100}{}{Tür}
{58101}{}{Eine Tür, die perfekt zu einer Zelle passen würde.}
{58200}{}{Schild}
{58201}{}{Auf diesem Schild steht, daß dieser Laden 'Darkwater's' heißt.}
{58300}{}{Leiter}
{58301}{}{Diese Leiter führt in die Dunkelheit nach unten.}
{58400}{}{Leiter}
{58401}{}{Diese Leiter führt in die Dunkelheit nach unten.}
{58500}{}{Maschinen}
{58501}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{58600}{}{Maschinen}
{58601}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{58700}{}{Maschinen}
{58701}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{58800}{}{Maschinen}
{58801}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{58900}{}{Maschinen}
{58901}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{59000}{}{Maschinen}
{59001}{}{Sieht wie eine alte Druckerpresse oder sonstein Gerät aus.}
{59100}{}{Tisch}
{59101}{}{Dieser Metalltisch ist in gutem Zustand. In seiner Mitte befindet sich ein Abfluß.}
{59200}{}{Tisch}
{59201}{}{Dieser Metalltisch ist in gutem Zustand. In seiner Mitte befindet sich ein Abfluß.}
{59300}{}{Tisch}
{59301}{}{Auf diesem Metalltisch befindet sich eine Art Biomasse.}
{59400}{}{Tisch}
{59401}{}{Auf diesem Metalltisch befindet sich eine Art Biomasse.}
{59500}{}{Tisch}
{59501}{}{Auf diesem Metalltisch befindet sich eine Art Biomasse.}
{59600}{}{Schwarzes Brett}
{59601}{}{An das Brett sind Stellenanzeigen gepinnt. Scheint häufig benutzt zu werden.}
{59700}{}{Wachhäuschen}
{59701}{}{Obwohl dieses Wachhäuschen über 100 Jahre alt ist, ist es in exzellentem Zustand.}
{59800}{}{Schild}
{59801}{}{Das Schild des Krämerladens.}
{59900}{}{Schild}
{59901}{}{Das Schild des Krämerladens.}
{60000}{}{Schild}
{60001}{}{Dieses Schild verweist auf den Markt.}
{60100}{}{Schleim-Pool}
{60101}{}{Sieht sehr ungesund aus. Bevor du hineinspringst, solltest du besser einen Panzerbadeanzug anziehen!}
{60200}{}{Schleim-Pool}
{60201}{}{Sieht sehr ungesund aus. Bevor du hineinspringst, solltest du besser einen Panzerbadeanzug anziehen!}
{60300}{}{Schleim-Pool}
{60301}{}{Sieht sehr ungesund aus. Bevor du hineinspringst, solltest du besser einen Panzerbadeanzug anziehen!}
{60400}{}{Tisch}
{60401}{}{Ein hübsch aussehender Metalltisch.}
{60500}{}{Tisch}
{60501}{}{Ein hübsch aussehender Metalltisch.}
{60600}{}{Tisch}
{60601}{}{Ein hübsch aussehender Metalltisch.}
{60700}{}{Tisch}
{60701}{}{Ein hübsch aussehender Metalltisch.}
{60800}{}{Tisch}
{60801}{}{Dieser Metalltisch wurde nicht gut gepflegt. Der Rost ist schon überall.}
{60900}{}{Tisch}
{60901}{}{Ein hübsch aussehender Metalltisch, sieht man vom Rost ab.}
{61000}{}{Tisch}
{61001}{}{Ein hübsch aussehender Metalltisch, sieht man vom Rost ab.}
{61100}{}{Tisch}
{61101}{}{Ein hübsch aussehender Metalltisch, sieht man vom Rost ab.}
{61200}{}{Feuerstelle}
{61201}{}{Es brennt Feuer.}
{61300}{}{Spiegel}
{61301}{}{Du betrachtest dich eine Zeit lang darin.}
{61400}{}{Spiegel}
{61401}{}{Du starrst eine Zeit lang dein Spiegelbild an.}
{61500}{}{Becken}
{61501}{}{Ein vollkommen intaktes Becken. Und obendrein noch schön und sauber.}
{61600}{}{Toilette}
{61601}{}{Diese Toilette ist sehr sauber. Sie funktioniert auch noch.}
{61700}{}{Pissoir}
{61701}{}{Dieses Pissoir funktioniert noch.}
{61800}{}{Toilette}
{61801}{}{Wenn du Toilettenfetischist wärst, wäre das doch was Nettes für dich!}
{61900}{}{Becken}
{61901}{}{Dieses Waschbecken ist in einwandfreiem Zustand.}
{62000}{}{Pissoir}
{62001}{}{Dieses Pissoir ist in einwandfreiem Zustand.}
{62100}{}{Dusche}
{62101}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62200}{}{Dusche}
{62201}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62300}{}{Dusche}
{62301}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62400}{}{Dusche}
{62401}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62500}{}{Dusche}
{62501}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62600}{}{Dusche}
{62601}{}{Eine Dusche wie beim Militär. Nichts für bescheidene Menschen.}
{62700}{}{Bett}
{62701}{}{Ein sehr bequem aussehendes Bett.}
{62800}{}{Bett}
{62801}{}{Ein sehr bequem aussehendes Bett.}
{62900}{}{Bett}
{62901}{}{Ein verstärktes Etagenbett.}
{63000}{}{Bett}
{63001}{}{Ein verstärktes Etagenbett.}
{63100}{}{Bett}
{63101}{}{Ein verstärktes Etagenbett.}
{63200}{}{Terminal}
{63300}{}{Terminal}
{63400}{}{Fahne}
{63401}{}{Diese Fahne trägt das Symbol der Children of the Cathedral.}
{63500}{}{Fahne}
{63501}{}{Diese Fahne trägt das Symbol der Children of the Cathedral.}
{63600}{}{Fahne}
{63601}{}{Diese Fahne trägt das Symbol der Children of the Cathedral.}
{63700}{}{Computer}
{63701}{}{Ein großer Computer.}
{63800}{}{Computer}
{63801}{}{Ein großer Computer.}
{63900}{}{Computer}
{63901}{}{Ein großer Computer.}
{64000}{}{Terminal}
{64001}{}{Das Terminal eines großen Computers.}
{64100}{}{Leiche}
{64101}{}{Sieht aus, als ob diese Person sehr qualvoll gestorben ist.}
{64200}{}{Leiche}
{64201}{}{Sieht aus, als ob diese Person sehr qualvoll gestorben ist.}
{64300}{}{Leiche}
{64301}{}{Sieht aus, als ob diese Person sehr qualvoll gestorben ist.}
{64400}{}{Leiche}
{64401}{}{Sieht aus, als ob diese Person sehr qualvoll gestorben ist.}
{64500}{}{Tür}
{64501}{}{Diese Gittertür eignet sich gut als Tür für eine Gefängniszelle.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Gabelstapler}
{64801}{}{Der Gabelstapler funktioniert nicht mehr.}
{64900}{}{Gabelstapler}
{64901}{}{Der Gabelstapler funktioniert nicht mehr.}
{65000}{}{Geräte}
{65100}{}{Untersuchungstisch}
{65101}{}{Dieser Tisch ist sehr rostig. Der Abfluß in seiner Mitte ist verstopft.}
{65200}{}{Untersuchungstisch}
{65201}{}{Dieser Tisch ist sehr rostig.}
{65300}{}{Tor}
{65301}{}{Dieses Tor verfügt über eine Schranke, die sich hebt und senkt.}
{65400}{}{Rohrleitung}
{65500}{}{Rohrleitung}
{65600}{}{Stromgenerator}
{65601}{}{Ein Wattz ElectroBox-Stromgenerator. War als Notstromgenerator vor dem Krieg ziemlich verbreitet.}
{65700}{}{Tank}
{65701}{}{Ein großer Wassertank. Sieht gut gewartet aus, was wahrscheinlich ganz nützlich ist.}
{65800}{}{Polizeihäuschen}
{65801}{}{Ein Polizeihäuschen aus Großbritannien von ca. 1960.}
{65900}{}{Tisch}
{65901}{}{Ein kunstvoll handgefertigter Tisch. Sieht viel schöner aus als alle Tische, die du je gesehen hast.}
{66000}{}{Tisch}
{66001}{}{Ein kunstvoll handgefertigter Tisch. Sieht viel schöner aus als alle Tische, die du je gesehen hast.}
{66100}{}{Tisch}
{66101}{}{Ein kunstvoll handgefertigter Tisch. Sieht viel schöner aus als alle Tische, die du je gesehen hast.}
{66200}{}{Stuhl}
{66201}{}{Ein sehr schön aussehender Stuhl.}
{66300}{}{Stuhl}
{66301}{}{Ein sehr schön aussehender Stuhl.}
{66400}{}{Stuhl}
{66401}{}{Ein sehr schön aussehender Stuhl.}
{66500}{}{Stuhl}
{66501}{}{Ein sehr schön aussehender Stuhl.}
{66600}{}{Stuhl}
{66601}{}{Ein sehr schön aussehender Stuhl.}
{66700}{}{Stuhl}
{66701}{}{Ein sehr schön aussehender Stuhl.}
{66800}{}{Stuhl}
{66801}{}{Ein sehr schön aussehender Stuhl.}
{66900}{}{Stuhl}
{66901}{}{Ein sehr schön aussehender Stuhl.}
{67000}{}{Stuhl}
{67001}{}{Ein sehr schön aussehender Stuhl.}
{67100}{}{Stuhl}
{67101}{}{Ein sehr schön aussehender Stuhl.}
{67200}{}{Stuhl}
{67201}{}{Ein sehr schön aussehender Stuhl.}
{67300}{}{Stuhl}
{67301}{}{Ein sehr schön aussehender Stuhl.}
{67400}{}{Stuhl}
{67401}{}{Ein sehr schön aussehender Stuhl.}
{67500}{}{Stuhl}
{67501}{}{Ein sehr schön aussehender Stuhl.}
{67600}{}{Stuhl}
{67601}{}{Ein sehr schön aussehender Stuhl.}
{67700}{}{Stuhl}
{67701}{}{Ein sehr schön aussehender Stuhl.}
{67800}{}{Bett}
{67801}{}{Ein sehr schön aussehendes Bett.}
{67900}{}{Bett}
{67901}{}{Ein sehr schön aussehendes Bett.}
{68000}{}{Bett}
{68001}{}{Ein sehr schön aussehendes Bett.}
{68100}{}{Bett}
{68101}{}{Ein sehr schön aussehendes Bett.}
{68200}{}{Ofen}
{68201}{}{Ein funktionierender Holzofen.}
{68300}{}{Ofen}
{68301}{}{Ein funktionierender Holzofen.}
{68400}{}{Ofen}
{68401}{}{Ein funktionierender Holzofen.}
{68500}{}{Ofen}
{68501}{}{Ein funktionierender Holzofen.}
{68600}{}{Kaputter Pfosten}
{68700}{}{Zerstörter Eingang}
{68800}{}{Steine}
{68801}{}{Eine große Steinformation. Dies ist kein natürliches Phänomen.}
{68900}{}{Steine}
{68901}{}{Eine große Steinformation. Dies ist kein natürliches Phänomen.}
{69000}{}{Toilette}
{69001}{}{Eine primitive, aber funktionierende Toilette. Es wurden einige Blätter in das Loch geworfen, um den Geruch zu überdecken.}
{69100}{}{Berg}
{69101}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69200}{}{Berg}
{69201}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69300}{}{Berg}
{69301}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69400}{}{Berg}
{69401}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69500}{}{Berg}
{69501}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69600}{}{Berg}
{69601}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69700}{}{Schleim}
{69701}{}{Ein seltsamer giftiger Bioschleim.}
{69800}{}{Schleim}
{69801}{}{Ein seltsamer giftiger Bioschleim.}
{69900}{}{Schleim}
{69901}{}{Ein seltsamer giftiger Bioschleim.}
{70000}{}{Schleim}
{70001}{}{Ein seltsamer giftiger Bioschleim.}
{70100}{}{Schleim}
{70101}{}{Ein seltsamer giftiger Bioschleim.}
{70200}{}{Schleim}
{70201}{}{Ein seltsamer giftiger Bioschleim.}
{70300}{}{Schleim}
{70301}{}{Ein seltsamer giftiger Bioschleim.}
{70400}{}{Schleim}
{70401}{}{Ein seltsamer giftiger Bioschleim.}
{70500}{}{Schleim}
{70501}{}{Ein seltsamer giftiger Bioschleim.}
{70600}{}{Schleim}
{70601}{}{Ein seltsamer giftiger Bioschleim.}
{70700}{}{Schleim}
{70701}{}{Ein seltsamer giftiger Bioschleim.}
{70800}{}{Schleim}
{70801}{}{Ein seltsamer giftiger Bioschleim.}
{70900}{}{Schleim}
{70901}{}{Ein seltsamer giftiger Bioschleim.}
{71000}{}{Schleim}
{71001}{}{Ein seltsamer giftiger Bioschleim.}
{71100}{}{Schleim}
{71101}{}{Ein seltsamer giftiger Bioschleim.}
{71200}{}{Schleim}
{71201}{}{Ein seltsamer giftiger Bioschleim.}
{71300}{}{Schleim}
{71301}{}{Ein seltsamer giftiger Bioschleim.}
{71400}{}{Schleim}
{71401}{}{Ein seltsamer giftiger Bioschleim.}
{71500}{}{Schleim}
{71501}{}{Ein seltsamer giftiger Bioschleim.}
{71600}{}{Schleim}
{71601}{}{Ein seltsamer giftiger Bioschleim.}
{71700}{}{Schleim}
{71701}{}{Ein seltsamer giftiger Bioschleim.}
{71800}{}{Schleim}
{71801}{}{Ein seltsamer giftiger Bioschleim.}
{71900}{}{Schleim}
{71901}{}{Ein seltsamer giftiger Bioschleim.}
{72000}{}{Schleim}
{72001}{}{Ein seltsamer giftiger Bioschleim.}
{72100}{}{Schleim}
{72101}{}{Ein seltsamer giftiger Bioschleim.}
{72200}{}{Schleim}
{72201}{}{Ein seltsamer giftiger Bioschleim.}
{72300}{}{Schleim}
{72301}{}{Ein seltsamer giftiger Bioschleim.}
{72400}{}{Schleim}
{72401}{}{Ein seltsamer giftiger Bioschleim.}
{72500}{}{Schleim}
{72501}{}{Ein seltsamer giftiger Bioschleim.}
{72600}{}{Schleim}
{72601}{}{Ein seltsamer giftiger Bioschleim.}
{72700}{}{Schleim}
{72701}{}{Ein seltsamer giftiger Bioschleim.}
{72800}{}{Schleim}
{72801}{}{Ein seltsamer giftiger Bioschleim.}
{72900}{}{Schleim}
{72901}{}{Ein seltsamer giftiger Bioschleim.}
{73000}{}{Schleim}
{73001}{}{Ein seltsamer giftiger Bioschleim.}
{73100}{}{Schleim}
{73101}{}{Ein seltsamer giftiger Bioschleim.}
{73200}{}{Schleim}
{73201}{}{Ein seltsamer giftiger Bioschleim.}
{73300}{}{Schleim}
{73301}{}{Ein seltsamer giftiger Bioschleim.}
{73400}{}{Schleim}
{73401}{}{Ein seltsamer giftiger Bioschleim.}
{73500}{}{Schleim}
{73501}{}{Ein seltsamer giftiger Bioschleim.}
{73600}{}{Schleim}
{73601}{}{Ein seltsamer giftiger Bioschleim.}
{73700}{}{Schleim}
{73701}{}{Ein seltsamer giftiger Bioschleim.}
{73800}{}{Schleim}
{73801}{}{Ein seltsamer giftiger Bioschleim.}
{73900}{}{Schleim}
{73901}{}{Ein seltsamer giftiger Bioschleim.}
{74000}{}{Schleim}
{74001}{}{Ein seltsamer giftiger Bioschleim.}
{74100}{}{Schleim}
{74101}{}{Ein seltsamer giftiger Bioschleim.}
{74200}{}{Schleim}
{74201}{}{Ein seltsamer giftiger Bioschleim.}
{74300}{}{Schleim}
{74301}{}{Ein seltsamer giftiger Bioschleim.}
{74400}{}{Schleim}
{74401}{}{Ein seltsamer giftiger Bioschleim.}
{74500}{}{Schleim}
{74501}{}{Ein seltsamer giftiger Bioschleim.}
{74600}{}{Schleim}
{74601}{}{Ein seltsamer giftiger Bioschleim.}
{74700}{}{Schleim}
{74701}{}{Ein seltsamer giftiger Bioschleim.}
{74800}{}{Schleim}
{74801}{}{Ein seltsamer giftiger Bioschleim.}
{74900}{}{Computer}
{74901}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75000}{}{Computer}
{75001}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75100}{}{Computer}
{75101}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75200}{}{Computer}
{75201}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75300}{}{Computer}
{75301}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75400}{}{Computer}
{75401}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75500}{}{Computer}
{75501}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75600}{}{Computer}
{75601}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75700}{}{Computer}
{75701}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75800}{}{Computer}
{75801}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{75900}{}{Computer}
{75901}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{76000}{}{Computer}
{76001}{}{Der Zugriff auf diesen Computer wird durch den vielen Schleim darauf erschwert.}
{76100}{}{Monitore}
{76101}{}{Die Anzeige ist nicht lesbar, weil die Bildschirme mit Schleim vollgespritzt sind.}
{76200}{}{Monitore}
{76201}{}{Die Anzeige ist nicht lesbar, weil die Bildschirme mit Schleim vollgespritzt sind.}
{76300}{}{Monitore}
{76301}{}{Die Anzeige ist nicht lesbar, weil die Bildschirme mit Schleim vollgespritzt sind.}
{76400}{}{Monitore}
{76401}{}{Die Anzeige ist nicht lesbar, weil die Bildschirme mit Schleim vollgespritzt sind.}
{76500}{}{Boden}
{76501}{}{Du könntest schwören, daß sich auf dem Boden etwas bewegt.}
{76600}{}{Podest}
{76601}{}{Dieses Podest scheint langsam ein- und auszuatmen.}
{76700}{}{Boden}
{76800}{}{Bombe}
{76801}{}{Eine Atombombe. Sie sieht sehr gefährlich aus, wie sie so daliegt.}
{76900}{}{Unterbau}
{76901}{}{Auf diesem Unterbau liegt eine Atombombe.}
{77000}{}{Computerkonsole}
{77001}{}{Ein Steuerungscomputer für Atomwaffen. Der Computer sieht sehr sicher aus. Er hat einen Schlitz für einen seltsam geformten Schlüssel.}
{77100}{}{Kabel}
{77101}{}{Diese Kabel verbinden die Bombe mit dem Computer.}
{77200}{}{Stuhl}
{77201}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77300}{}{Stuhl}
{77301}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77400}{}{Stuhl}
{77401}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77500}{}{Stuhl}
{77501}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77600}{}{Stuhl}
{77601}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77700}{}{Stuhl}
{77701}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77800}{}{Stuhl}
{77801}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{77900}{}{Stuhl}
{77901}{}{An diesem Stuhl gibt es nichts Ungewöhnliches.}
{78000}{}{Pfeiler}
{78001}{}{Ein Stützpfeiler.}
{78100}{}{Pfeiler}
{78101}{}{Ein Stützpfeiler.}
{78200}{}{Pfeiler}
{78201}{}{Ein Stützpfeiler.}
{78300}{}{Pfeiler}
{78301}{}{Ein Stützpfeiler.}
{78400}{}{Bett}
{78401}{}{Dieses Bett ist in erbärmlichem Zustand.}
{78500}{}{Bett}
{78501}{}{Dieses Bett ist in sehr schlechtem Zustand.}
{78600}{}{Bett}
{78601}{}{Dieses Bett ist in schlechtem Zustand.}
{78700}{}{Bett}
{78701}{}{Dieses Bett ist in ziemlich schlechtem Zustand.}
{78800}{}{Monitore}
{78801}{}{Diese Monitore sind defekt und funktionieren nicht mehr.}
{78900}{}{Monitore}
{78901}{}{Diese Monitore sind defekt und funktionieren nicht mehr.}
{79000}{}{Monitore}
{79001}{}{Diese Monitore sind defekt und funktionieren nicht mehr.}
{79100}{}{Monitore}
{79101}{}{Diese Monitore sind defekt und funktionieren nicht mehr.}
{79200}{}{Lüftungsschlitz}
{79201}{}{Aus diesem Lüftungsschlitz kommt sehr wenig Frischluft.}
{79300}{}{Lüftungsschlitz}
{79301}{}{Aus diesem Lüftungsschlitz kommt fast keine Frischluft.}
{79400}{}{Lüftungsschlitz}
{79401}{}{Aus diesem Lüftungsschlitz kommt keine Frischluft.}
{79500}{}{Lüftungsschlitz}
{79501}{}{Aus diesem Lüftungsschlitz kommt nur ganz wenig Frischluft.}
{79600}{}{Tisch}
{79601}{}{An diesem Tisch gibt es nichts Ungewöhnliches, bis auf die Tatsache, daß er fast kaputt ist.}
{79700}{}{Tisch}
{79701}{}{Dieser Tisch wurde schwer beschädigt.}
{79800}{}{Tisch}
{79801}{}{Dieser Tisch ist in sehr schlechtem Zustand.}
{79900}{}{Tisch}
{79901}{}{Es gibt keinen Grund, diesen Tisch zu durchsuchen.}
{80000}{}{Monitore}
{80001}{}{Die Anzeigen dieser Monitore wurden zerstört.}
{80100}{}{Monitore}
{80101}{}{Die Anzeigen dieser Monitore wurden komplett zerstört.}
{80200}{}{Monitore}
{80201}{}{Der Monitor hat einen Sprung und ist defekt.}
{80300}{}{Monitor}
{80301}{}{Dieser Monitor mit seinem defekten Bildschirm ist wertlos.}
{80400}{}{Computer}
{80401}{}{Dieser Computer ist defekt.}
{80500}{}{Computer}
{80501}{}{Dieser Computer ist defekt.}
{80600}{}{Computer}
{80601}{}{Dieser Computer ist defekt.}
{80700}{}{Stuhl}
{80701}{}{Dieser Stuhl ist kaputt.}
{80800}{}{Stuhl}
{80801}{}{Dieser Stuhl ist kaputt.}
{80900}{}{Stuhl}
{80901}{}{Dieser Stuhl ist kaputt.}
{81000}{}{Stuhl}
{81001}{}{Dieser Stuhl ist kaputt.}
{81100}{}{Lüftungsschlitz}
{81101}{}{Dieser Lüftungsschlitz ist komplett zerstört.}
{81200}{}{Lüftungsschlitz}
{81201}{}{Dieser Lüftungsschlitz ist zerstört und läßt sich nicht mehr reparieren.}
{81300}{}{Lüftungsschlitz}
{81301}{}{Dieser Lüftungsschlitz funktioniert überhaupt nicht mehr.}
{81400}{}{Computer}
{81401}{}{Dieser Computer scheint kaum noch zu funktionieren.}
{81500}{}{Computer}
{81501}{}{Dieser Computer scheint kaum noch zu funktionieren.}
{81600}{}{Monitor}
{81601}{}{Dieser Monitor funktioniert kaum noch.}
{81700}{}{Monitor}
{81701}{}{Dieser Monitor funktioniert kaum noch.}
{81800}{}{Computer}
{81801}{}{Dieser Computer funktioniert nicht mehr.}
{81900}{}{Computer}
{81901}{}{Dieser Computer funktioniert nicht mehr.}
{82000}{}{Monitor}
{82001}{}{Dieser Monitor funktioniert nicht mehr.}
{82100}{}{Monitor}
{82101}{}{Dieser Monitor funktioniert nicht mehr.}
{82200}{}{Türrahmen}
{82201}{}{Sieht wie ein sehr schöner Türrahmen aus. Er erfüllt seinen Zweck - nämlich eine Tür zu halten - sehr gut.}
{82300}{}{Monitore}
{82301}{}{Diese Monitore sind in gutem Zustand.}
{82400}{}{Monitore}
{82401}{}{Diese Monitore sind in gutem Zustand.}
{82500}{}{Wall}
{82600}{}{Banktür}
{82601}{}{Eine sehr stabile Tür einer Bank. Die Tür sieht sehr sicher aus.}
{82700}{}{Leuchte}
{82701}{}{Eine Warnleuchte.}
{82800}{}{Leuchte}
{82801}{}{Eine Warnleuchte.}
{82900}{}{Säule}
{82901}{}{Diese Säule ist die Hauptattraktion von Shady Sands. Sie erzählt Geschichten, um die Menschen an Hoffnung und Frieden zu erinnern.}
{83000}{}{Robotorladestation}
{83001}{}{Eine Ladestation für Roboter. Wenn die Roboter nicht im Einsatz sind, docken sie hier an, fahren herunter und werden aufgeladen.}
{83100}{}{Robotorladestation}
{83101}{}{Eine Ladestation für Roboter. Wenn die Roboter nicht im Einsatz sind, docken sie hier an, fahren herunter und werden aufgeladen.}
{83200}{}{Robotorladestation}
{83201}{}{Eine Ladestation für Roboter. Wenn die Roboter nicht im Einsatz sind, docken sie hier an, fahren herunter und werden aufgeladen.}
{83300}{}{Robotorladestation}
{83301}{}{Eine Ladestation für Roboter. Wenn die Roboter nicht im Einsatz sind, docken sie hier an, fahren herunter und werden aufgeladen.}
{83400}{}{Robotorladestation}
{83401}{}{Eine Ladestation für Roboter. Wenn die Roboter nicht im Einsatz sind, docken sie hier an, fahren herunter und werden aufgeladen.}
{83500}{}{Maschine}
{83501}{}{Diese Maschine hat etwas mit den Wartungsstationen für Roboter zu tun. Sieht nicht besonders interessant aus.}
{83600}{}{Maschine}
{83601}{}{Diese Maschine hat etwas mit den Wartungsstationen für Roboter zu tun. Sieht nicht besonders interessant aus.}
{83700}{}{Streifen}
{83800}{}{Streifen}
{83900}{}{Streifen}
{84000}{}{Streifen}
{84100}{}{Streifen}
{84200}{}{Streifen}
{84300}{}{Streifen}
{84400}{}{Streifen}
{84500}{}{Streifen}
{84600}{}{Streifen}
{84700}{}{Streifen}
{84800}{}{Tür}
{84801}{}{Eine ganz normale Holztür.}
{84900}{}{Tür}
{84901}{}{Eine ganz normale Holztür.}
{85000}{}{Tür}
{85001}{}{Eine ganz normale Holztür.}
{85100}{}{Schild}
{85101}{}{Das Schild der 'Friendly Lending Company'.}
{85200}{}{Symbol}
{85201}{}{Dieses Symbol wird von den Followers of the Apocalypse benutzt.}
{85300}{}{Untersuchungstisch}
{85301}{}{Sieht wie ein Untersuchungstisch aus.}
{85400}{}{Schild}
{85401}{}{Das Neonschild des 'Maltese Falcon'.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Schild}
{86901}{}{Dieses Schild läßt darauf schließen, daß es hier vielleicht Waffen gibt.}
{87000}{}{Schild}
{87001}{}{Das Schild der Polizeiwache.}
{87100}{}{Schild}
{87101}{}{Das Schild der 'Far Go Traders'.}
{87200}{}{Schild}
{87201}{}{Das Schild der 'Gunrunners'.}
{87300}{}{Schild}
{87301}{}{Das Schild der Handelsfirma 'Crimson Caravan'.}
{87400}{}{Schild}
{87401}{}{Das Schild des Krankenhauses. Sollte man sich merken!}
{87500}{}{Schild}
{87501}{}{Das Schild des 'Crash House'.}
{87600}{}{Schild}
{87601}{}{Dieses Schild verweist auf Bobs Gebrauchtwagengeschäft.}
{87700}{}{Schild}
{87701}{}{Das Schild der 'Water Merchants', einer Handelsfirma des Hub.}
{87800}{}{Eierschale}
{87801}{}{Stücke zerbrochener Eierschale.}
{87900}{}{Eierschale}
{87901}{}{Stücke zerbrochener Eierschale.}
{88000}{}{Eierschale}
{88001}{}{Stücke zerbrochener Eierschale.}
{88100}{}{Eierschale}
{88101}{}{Stücke zerbrochener Eierschale.}
{88200}{}{Eierschale}
{88201}{}{Stücke zerbrochener Eierschale.}
{88300}{}{Eierschale}
{88301}{}{Stücke zerbrochener Eierschale.}
{88400}{}{Eierschale}
{88401}{}{Stücke zerbrochener Eierschale.}
{88500}{}{Eierschale}
{88501}{}{Stücke zerbrochener Eierschale.}
{88600}{}{Laterne}
{88601}{}{Eine Laterne. Scheint noch gut zu funktionieren.}
{88700}{}{Schild}
{88701}{}{Das Schild eines Motels.}
{88800}{}{Pilze}
{88801}{}{Dieser Topf wurde mit Mist gefüllt, aus dem lustig Pilze sprießen.}
{88900}{}{Pilze}
{88901}{}{Dieser Topf wurde mit Mist gefüllt, aus dem lustig Pilze sprießen.}
{89000}{}{Skelett}
{89100}{}{Schild}
{89101}{}{Das Schild des Gefängnisses.}
{89200}{}{Schild}
{89201}{}{Das Schild des 'Skum Pitt' - Bar und Tollhaus in einem.}
{89300}{}{Schild}
{89301}{}{Eine Werbetafel für Blades-Rasierklingen.}
{89400}{}{Dusche}
{89401}{}{Eine ziemlich normale Duschkabine.}
{89500}{}{Dusche}
{89501}{}{Eine ziemlich normale Duschkabine.}
{89600}{}{Schild}
{89601}{}{Das Schild der 'Friendly Lending Company'.}
{89700}{}{Schild}
{89701}{}{Das Schild der 'Friendly Lending Company'.}
{89800}{}{Poster}
{89801}{}{Ein Kinoposter für einen Horrorfilm aus der Vorkriegszeit.}
{89900}{}{Poster}
{89901}{}{Ein Kinoposter für einen Horrorfilm aus der Vorkriegszeit.}
{90000}{}{Theke}
{90001}{}{Auf dieser Theke steht eine Urne. Sie sieht zwar ein bißchen mitgenommen aus, könnte aber durchaus etwas wert sein.}
{90100}{}{Aufzugschacht}
{90101}{}{Im Schacht hängt ein Seil herab.}
{90200}{}{Aufzugschacht}
{90201}{}{Im Schacht hängt von der Seite ein Seil herab.}
{90300}{}{Krankenhausbett}
{90301}{}{Dieses Bett hat eine integrierte Anzeige zur Überwachung der Genesung der Patienten.}
{90400}{}{Wasserpumpe}
{90401}{}{Dieses Gerät pumpt Wasser von unten nach oben.}
{90500}{}{Krankenhausbett}
{90501}{}{Dieses Bett hat eine integrierte Anzeige zur Überwachung der Genesung der Patienten.}
{90600}{}{Powerrüstungsteile}
{90601}{}{Diese Teile gehören zu einer Powerrüstung.}
{90700}{}{Leuchte}
{90701}{}{Diese Warnleuchte leuchtet hellrot auf.}
{90800}{}{Leuchte}
{90801}{}{Diese Warnleuchte leuchtet hellrot auf.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Rope}
{91600}{}{Rope}
{91700}{}{Rope}
{91800}{}{Rope}
{91900}{}{Rope}
{92000}{}{Rope}
{92100}{}{Rope}
{92200}{}{Rope}
{92300}{}{Canyon}
{92400}{}{Canyon}
{92500}{}{Canyon}
{92600}{}{Canyon}
{92700}{}{Canyon}
{92800}{}{Canyon}
{92900}{}{Canyon}
{93000}{}{Canyon}
{93100}{}{Cave Floor}
{93200}{}{Impenetrable Door}
{93201}{}{This door appears to have no opening mechanism.}
{93300}{}{Destroyed Door}
{93301}{}{The door has been blown open.}
{93400}{}{Door}
{93401}{}{A door with an intricate lock.}
{93500}{}{Torch}
{93501}{}{A lit torch in a wall sconce.}
{93600}{}{Torch}
{93601}{}{A lit torch in a wall sconce.}
{93700}{}{Stone Monument}
{93800}{}{Stone Monument}
{93900}{}{Stone Monument}
{94000}{}{Skull Pole}
{94001}{}{A pole with human skulls attached.}
{94100}{}{Skull Pole}
{94101}{}{A pole with human skulls attached.}
{94200}{}{Skull Pole}
{94201}{}{A pole with human skulls attached.}
{94300}{}{Plant}
{94301}{}{}
{94400}{}{Plant}
{94500}{}{Tree}
{94600}{}{Tree}
{94700}{}{Tree}
{94800}{}{Bed}
{94900}{}{Bed}
{95000}{}{Hole}
{95001}{}{A suspicious hole in the wall.}
{95100}{}{Raised Stone Plate}
{95101}{}{A raised stone plate.}
{95200}{}{Disabled Stone Plate}
{95201}{}{A disabled stone plate.}
{95300}{}{Triggered Stone Plate}
{95301}{}{A triggered stone plate.}
{95400}{}{Door}
{95500}{}{Door}
{95600}{}{Door}
{95700}{}{Door}
{95800}{}{Door}
{95900}{}{Door}
{96000}{}{Door}
{96100}{}{Door}
{96200}{}{Door}
{96300}{}{Plant}
{96301}{}{A mutated cornstalk.}
{96400}{}{Plant}
{96401}{}{A mutated cornstalk.}
{96500}{}{Plant}
{96501}{}{A mutated cornstalk. This one is sick.}
{96600}{}{Plant}
{96601}{}{A mutated cornstalk.}
{96700}{}{Plant}
{96701}{}{A mutated cornstalk.}
{96800}{}{Plant}
{96801}{}{A mutated cornstalk.}
{96900}{}{Wood Support}
{97000}{}{Wood Support}
{97100}{}{Wood Support}
{97200}{}{Wood Support}
{97300}{}{Wood Support}
{97400}{}{Wood Support}
{97500}{}{Damaged Wood Support}
{97501}{}{This support looks like it could collapse if stressed.}
{97600}{}{Collapsed Floor}
{97601}{}{The stone floor has collapsed here into the lower level.}
{97700}{}{Ladder Down}
{97701}{}{A manmade hole with a ladder leading down.}
{97800}{}{Door}
{97900}{}{Wall}
{98000}{}{Reactor 5 Sign}
{98100}{}{Door}
{98200}{}{Door}
{98300}{}{Door}
{98400}{}{Door}
{98500}{}{Radioactive Goo}
{98600}{}{Radioactive Goo}
{98700}{}{Radioactive Goo}
{98800}{}{Radioactive Goo}
{98900}{}{Security Door}
{99000}{}{Vault Door}
{99100}{}{Utility Crane}
{99200}{}{Utility Crane}
{99300}{}{Well}
{99400}{}{Well}
{99500}{}{Outhouse}
{99600}{}{Hole}
{99601}{}{You can't see the bottom of this pit.}
{99700}{}{Floor Plate}
{99701}{}{You see a floor plate trap.}
{99800}{}{Disabled Floor Plate}
{99801}{}{This floor plate trap has been disabled.}
{99900}{}{Triggered Floor Plate}
{99901}{}{This floor plate trap has been triggered. Opps!}
{100000}{}{Still}
{100001}{}{This looks like a wood-burning alcohol still.}
{100100}{}{Rad Scorpion Parts}
{100101}{}{You see a large pile of Radscorpion parts. They've been hollowed out and have straps attached to them.}
{100200}{}{Powerplant Machinery}
{100201}{}{This is the Plutonium-Gamma Shield machine for the reactor.}
{100300}{}{Powerplant Machinery}
{100301}{}{This is the Jupiter Wave Compiler machine for the reactor.}
{100400}{}{Powerplant Machinery}
{100401}{}{This is the Uranium-Rod Driver machine for the reactor.}
{100500}{}{Powerplant Machinery}
{100501}{}{This is the Neptunium Impeller machine for the reactor.}
{100600}{}{Powerplant Machinery}
{100601}{}{This is the Saturn-Class Capacitor machine for the reactor.}
{100700}{}{Powerplant Pump Control}
{100701}{}{This is the coolant pumping machine for the reactor.}
{100800}{}{Side of Brahmin}
{100900}{}{Car}
{101000}{}{Chrysalis Motors Car}
{101001}{}{This Chrysalis Motors Highwayman looks to be in pretty good shape for its age.}
{101100}{}{Car}
{101200}{}{Gravesite}
{101201}{}{A grave is located here.}
{101300}{}{Headstone}
{101301}{}{Headstone}
{101400}{}{Headstone}
{101401}{}{Headstone}
{101500}{}{Headstone}
{101501}{}{Headstone}
{101600}{}{Headstone}
{101601}{}{Headstone}
{101700}{}{Plow}
{101701}{}{This plow is designed to be dragged by a Brahmin.}
{101800}{}{Plow}
{101801}{}{This plow is designed to be dragged by a Brahmin.}
{101900}{}{Water}
{102000}{}{Sign}
{102001}{}{The entry sign for New Reno.}
{102100}{}{Sign}
{102101}{}{The entry sign for New Reno.}
{102200}{}{Sign}
{102201}{}{The entry sign for New Reno.}
{102300}{}{Sign}
{102301}{}{The entry sign for New Reno.}
{102400}{}{Sign}
{102401}{}{The entry sign for New Reno.}
{102500}{}{Sign}
{102501}{}{The entry sign for New Reno.}
{102600}{}{Shadow}
{102700}{}{Shadow}
{102800}{}{Shadow}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Sign}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Sign}
{111100}{}{Sign}
{111200}{}{Sign}
{111300}{}{Sign}
{111400}{}{Sign}
{111500}{}{Sign}
{111600}{}{Sign}
{111700}{}{Sign}
{111800}{}{Wallpaper}
{111900}{}{Wallpaper}
{112000}{}{Wallpaper}
{112100}{}{Wallpaper}
{112200}{}{Wallpaper}
{112300}{}{Wallpaper}
{112400}{}{Wallpaper}
{112500}{}{Wallpaper}
{112600}{}{Wallpaper}
{112700}{}{Wallpaper}
{112800}{}{Wallpaper}
{112900}{}{Wallpaper}
{113000}{}{Wallpaper}
{113100}{}{Wallpaper}
{113200}{}{Wallpaper}
{113300}{}{Wallpaper}
{113400}{}{Wallpaper}
{113500}{}{Wallpaper}
{113600}{}{Wallpaper}
{113700}{}{Wallpaper}
{113800}{}{Wallpaper}
{113900}{}{Wallpaper}
{114000}{}{Wallpaper}
{114100}{}{Movie Camera}
{114200}{}{Coffin}
{114300}{}{Coffin}
{114400}{}{Coffin}
{114500}{}{Coffin}
{114600}{}{Steel Bars}
{114700}{}{Steel Bars}
{114800}{}{Steel Window Cover}
{114900}{}{Steel Window Cover}
{115000}{}{Laser Tripwire}
{115100}{}{Laser Tripwire}
{115200}{}{Mining Cart}
{115300}{}{Mining Cart with Steel Pole}
{115400}{}{Mining Cart with Dynamite}
{115500}{}{"Out of Business" Sign}
{115600}{}{"Out of Business" Sign}
{115700}{}{Buckner House Sign}
{115800}{}{Vic's Sign}
{115900}{}{Wall}
{116000}{}{Wall}
{116100}{}{Retinal Scanner}
{116101}{}{This is a security device that scans a person's retinal pattern.}
{116200}{}{Control Room Sign}
{116300}{}{Control Room Sign}
{116400}{}{Control Room Sign}
{116500}{}{Construction Zone Sign}
{116600}{}{Construction Zone Sign}
{116700}{}{Machine}
{116701}{}{A non-functional machine.}
{116800}{}{Machine}
{116801}{}{A non-functional machine.}
{116900}{}{Door}
{117000}{}{Door}
{117100}{}{Pipes}
{117101}{}{A set of pipes going into the reactor.}
{117200}{}{Tank}
{117300}{}{Tanks}
{117400}{}{Tanks}
{117500}{}{Tanks}
{117600}{}{Vent}
{117700}{}{Vent}
{117800}{}{Harp Sign}
{117900}{}{Sawhorse}
{118000}{}{Sawhorse}
{118100}{}{Sawhorse}
{118200}{}{Vent}
{118300}{}{Vent}
{118400}{}{Machine Shop Sign}
{118500}{}{Manager's Office Sign}
{118600}{}{Supply Room Sign}
{118700}{}{Radiation Warning Sign}
{118800}{}{Steam}
{118900}{}{Machine}
{118901}{}{A misc. piece of equipment for the power plant.}
{119000}{}{Tank}
{119100}{}{Fire}
{119200}{}{Water}
{119300}{}{Trapper Town Sign}
{119400}{}{Golden Gecko Sign}
{119500}{}{Bath House Sign}
{119600}{}{Cave Art}
{119700}{}{Cave Art}
{119800}{}{Cave Art}
{119900}{}{Cave Art}
{120000}{}{Firepit}
{120100}{}{Cave Wall}
{120200}{}{Cave Wall}
{120300}{}{Cave Wall}
{120400}{}{Cave Wall}
{120500}{}{Cave Wall}
{120600}{}{Cave Wall}
{120700}{}{Cave Wall}
{120800}{}{Cave Wall}
{120900}{}{Cave Wall}
{121000}{}{Cave Wall}
{121100}{}{Cave Wall}
{121200}{}{Cave Wall}
{121300}{}{Cave Wall}
{121400}{}{Cave Wall}
{121500}{}{Cave Wall}
{121600}{}{Stake}
{121601}{}{This stake appears to have a person impaled on the top!}
{121700}{}{Stake}
{121701}{}{This stake appears to have a person impaled on the top!}
{121800}{}{Stake}
{121801}{}{This stake appears to have a person impaled on the top!}
{121900}{}{Stake}
{121901}{}{This stake appears to have a person impaled on the top!}
{122000}{}{Stake}
{122001}{}{This stake appears to have a person impaled on the top!}
{122100}{}{Stake}
{122101}{}{This stake appears to have a person impaled on the top!}
{122200}{}{Stake}
{122201}{}{This stake appears to have a human skull placed on the top.}
{122300}{}{Stake}
{122301}{}{This stake appears to have a human skull placed on the top.}
{122400}{}{Stake}
{122401}{}{This empty stake looks ready for an unwilling victim.}
{122500}{}{Stake}
{122501}{}{This empty stake looks ready for an unwilling victim.}
{122600}{}{Stake}
{122601}{}{This empty stake looks ready for an unwilling victim.}
{122700}{}{Stake}
{122701}{}{This empty stake looks ready for an unwilling victim.}
{122800}{}{Wanted Sign}
{122801}{}{The picture on this sign looks oddly like you!}
{122900}{}{Floor}
{123000}{}{Deactivated Robobrain}
{123001}{}{An incomplete cybernetic body that is missing several parts.}
{123100}{}{Howitzer}
{123101}{}{This strange-looking cannon looks like a relic from the pre-War days. You wonder how it ended up here.}
{123200}{}{Sign}
{123300}{}{Sign}
{123400}{}{Sign}
{123500}{}{Sign}
{123600}{}{Power Switch}
{123700}{}{Cross}
{123800}{}{Cross}
{123900}{}{Cross}
{124000}{}{Cross}
{124100}{}{Cross}
{124200}{}{Cross}
{124300}{}{Gas Pump}
{124400}{}{Gas Pump}
{124500}{}{Gas Pump}
{124600}{}{Pep Gas Sign}
{124700}{}{Sign Shadow}
{124800}{}{Haybed}
{124900}{}{Haybed}
{125000}{}{Haybed}
{125100}{}{Haybed}
{125200}{}{Haybed}
{125300}{}{Haybed}
{125400}{}{Dusty's Cantina Sign}
{125500}{}{Son of Bob's Store}
{125501}{}{A street vendor's stand.}
{125600}{}{Son of Bob's Store}
{125601}{}{A street vendor's stand.}
{125700}{}{Son of Bob's Store}
{125701}{}{A street vendor's stand.}
{125800}{}{Son of Bob's Store}
{125801}{}{A street vendor's stand.}
{125900}{}{NCR Sign}
{126000}{}{Hall of Congress Sign}
{126100}{}{Hall of Congress Sign}
{126200}{}{NCR Poster}
{126300}{}{NCR Poster}
{126400}{}{NCR Poster}
{126500}{}{NCR Poster}
{126600}{}{Rawhide Saloon Sign}
{126700}{}{Casino Sign}
{126800}{}{Casino Sign}
{126900}{}{Casino Sign}
{127000}{}{Casino Sign}
{127100}{}{Casino Sign}
{127200}{}{Casino Sign}
{127300}{}{Pile of Rocks}
{127301}{}{These rocks appear to be keeping something in.}
{127400}{}{Beam}
{127500}{}{Beam}
{127600}{}{Beam}
{127700}{}{Beam}
{127800}{}{Beam}
{127900}{}{Beam}
{128000}{}{Beam}
{128100}{}{Beam}
{128200}{}{Beam}
{128300}{}{Beam}
{128400}{}{Shadow}
{128500}{}{Shadow}
{128600}{}{Shadow}
{128700}{}{Shadow}
{128800}{}{Shadow}
{128900}{}{Shadow}
{129000}{}{Shadow}
{129100}{}{Shadow}
{129200}{}{Shadow}
{129300}{}{Elevator Stub}
{129400}{}{Gas Pump}
{129500}{}{Gas Pump}
{129600}{}{Gas Pump}
{129700}{}{Rope}
{129800}{}{Hole}
{129900}{}{Brahmin Meat}
{130000}{}{Brahmin Meat}
{130100}{}{Brahmin Meat}
{130200}{}{Brahmin Meat}
{130300}{}{Brahmin Meat}
{130400}{}{Brahmin Meat}
{130500}{}{Beam}
{130600}{}{Beam}
{130700}{}{Beam}
{130800}{}{Beam}
{130900}{}{Beam}
{131000}{}{Beam}
{131100}{}{Beam}
{131200}{}{Beam}
{131300}{}{Shadow}
{131400}{}{Shadow}
{131500}{}{Shadow}
{131600}{}{Shadow}
{131700}{}{Shadow}
{131800}{}{Shadow}
{131900}{}{Shadow}
{132000}{}{Shadow}
{132100}{}{Blood}
{132200}{}{Blood}
{132300}{}{Blood}
{132400}{}{Blood}
{132500}{}{Blood}
{132600}{}{Blood}
{132700}{}{Blood with Bones}
{132800}{}{Blood with Bones}
{132900}{}{Blood with Bones}
{133000}{}{Cave Mouth}
{133100}{}{Equipment Access}
{133200}{}{Equipment Access}
{133300}{}{Equipment Access}
{133400}{}{Equipment Access}
{133500}{}{Computer}
{133501}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133600}{}{Computer}
{133601}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133700}{}{Vault City Gate}
{133800}{}{Vault City Gate}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Wall}
{134700}{}{Door}
{134800}{}{Blown Open Door}
{134900}{}{Door Debris}
{135000}{}{Building}
{135100}{}{Building}
{135200}{}{Building}
{135300}{}{Building}
{135400}{}{Building}
{135500}{}{Building}
{135600}{}{Building}
{135700}{}{Building}
{135800}{}{Door}
{135900}{}{Temple}
{136000}{}{Temple}
{136100}{}{Temple}
{136200}{}{Temple}
{136300}{}{Temple}
{136400}{}{Temple}
{136500}{}{Firepit}
{136600}{}{Firepit}
{136700}{}{Howitizer}
{136701}{}{This strange-looking cannon looks like a relic from the pre-War days. You wonder how it ended up here.}
{136800}{}{Temple}
{136900}{}{Temple}
{137000}{}{Mountain}
{137100}{}{Cavern}
{137200}{}{Door Track}
{137300}{}{Torch}
{137301}{}{A lit torch in a wall sconce.}
{137400}{}{Torch}
{137401}{}{A lit torch in a wall sconce.}
{137500}{}{Torch}
{137501}{}{A lit torch in a wall sconce.}
{137600}{}{Torch}
{137601}{}{A lit torch in a wall sconce.}
{137700}{}{Vertibird}
{137701}{}{NEED LONG DESCRIPTION.}
{137800}{}{Destroyed Door}
{137801}{}{The power station door is destroyed.}
{137900}{}{Destroyed Door}
{137901}{}{The power station door is destroyed.}
{138000}{}{Wall}
{138100}{}{Wall}
{138200}{}{Wall}
{138300}{}{Wall}
{138400}{}{Wall}
{138500}{}{Wall}
{138600}{}{Light}
{138700}{}{Door}
{138800}{}{Door}
{138900}{}{Door}
{139000}{}{Door}
{139100}{}{Door}
{139200}{}{Door}
{139300}{}{Banner}
{139400}{}{Post}
{139500}{}{Post}
{139600}{}{Banner}
{139700}{}{Banner}
{139800}{}{Post}
{139900}{}{Post}
{140000}{}{Banner}
{140100}{}{Shadow}
{140200}{}{Shadow}
{140300}{}{Banner}
{140400}{}{Banner}
{140500}{}{Banner}
{140600}{}{Banner}
{140700}{}{Cat's Paw Sign}
{140800}{}{Cat's Paw Sign}
{140900}{}{Sign}
{141000}{}{Jungle Gym Sign}
{141100}{}{Jungle Gym Sign}
{141200}{}{Jungle Gym Sign}
{141300}{}{Renesco's Pharmacy Sign}
{141400}{}{New Reno Arms Sign}
{141500}{}{Salvatore's Bar Sign}
{141600}{}{Statue}
{141700}{}{Warehouse Door}
{141800}{}{Warehouse Door}
{141900}{}{Doc Johnson Sign}
{142000}{}{Sheriff Sign}
{142100}{}{Malamute Saloon Sign}
{142200}{}{Morningstar Mine Sign}
{142300}{}{Kokowebe Mine Sign}
{142400}{}{Kokowebe Mine Sign}
{142500}{}{Kokowebe Mine Sign}
{142600}{}{Signpost}
{142601}{}{This wooden sign points towards New Reno and "Hell." You suspect the directions are reversed.}
{142700}{}{Number 1 Sign}
{142800}{}{Number 2 Sign}
{142900}{}{Number 3 Sign}
{143000}{}{Number 4 Sign}
{143100}{}{Number 5 Sign}
{143200}{}{Number 6 Sign}
{143300}{}{Rope}
{143301}{}{You can climb over the wall with this rope.}
{143400}{}{Door}
{143500}{}{Door}
{143600}{}{Window}
{143700}{}{Window}
{143800}{}{Window}
{143900}{}{Window}
{144000}{}{Window}
{144100}{}{Window}
{144200}{}{Window}
{144300}{}{Window}
{144400}{}{Window}
{144500}{}{Window}
{144600}{}{Window}
{144700}{}{Window}
{144800}{}{Pool Ladder}
{144900}{}{Door}
{145000}{}{Arch}
{145100}{}{Arch}
{145200}{}{Arch}
{145300}{}{Arch}
{145400}{}{Arch}
{145500}{}{Arch}
{145600}{}{Arch}
{145700}{}{Arch}
{145800}{}{Shadow}
{145900}{}{Shadow}
{146000}{}{Shadow}
{146100}{}{Arch}
{146200}{}{Arch}
{146300}{}{Arch}
{146400}{}{Shadow}
{146500}{}{Shadow}
{146600}{}{Fence Door}
{146700}{}{Fence Door}
{146800}{}{Command Seat}
{146801}{}{This is where the Overseer normally sits.}
{146900}{}{Chasm}
{147000}{}{Chasm}
{147100}{}{Chasm}
{147200}{}{Chasm}
{147300}{}{Casino Entrance}
{147400}{}{Casino Entrance}
{147500}{}{Carpet}
{147600}{}{Casino Entrance}
{147700}{}{Casino Entrance}
{147800}{}{Casino Entrance}
{147900}{}{Casino Door}
{148000}{}{Casino Door}
{148100}{}{Casino Entrance}
{148200}{}{Casino Entrance}
{148300}{}{Casino Entrance}
{148400}{}{Casino Entrance}
{148500}{}{Casino Entrance}
{148600}{}{Casino Entrance}
{148700}{}{Casino Entrance}
{148800}{}{Casino Entrance}
{148900}{}{Casino Entrance}
{149000}{}{Casino Entrance}
{149100}{}{Casino Door}
{149200}{}{Casino Door}
{149300}{}{Wall Light}
{149400}{}{Wall Light}
{149500}{}{Wall Light}
{149600}{}{Wall Light}
{149700}{}{Wall Light}
{149800}{}{Wall}
{149900}{}{Wall}
{150000}{}{Fan}
{150100}{}{Fan}
{150200}{}{Fire Ext.}
{150300}{}{Fire Ext.}
{150400}{}{Pipe}
{150500}{}{Power Distributor}
{150600}{}{Power Distributor}
{150700}{}{Wall}
{150800}{}{Wall}
{150900}{}{Wall}
{151000}{}{Wall}
{151100}{}{Wall}
{151200}{}{Wall}
{151300}{}{Wall}
{151400}{}{Wall}
{151500}{}{Wall}
{151600}{}{Wood Paneling}
{151700}{}{Wood Paneling}
{151800}{}{Pipe}
{151900}{}{Pipe}
{152000}{}{Pipe}
{152100}{}{Pipe}
{152200}{}{Pipe}
{152300}{}{Pipe}
{152400}{}{Pipe}
{152500}{}{Pipe}
{152600}{}{Pipe}
{152700}{}{Pipe}
{152800}{}{Pipe}
{152900}{}{Air Vent}
{153000}{}{Air Vent}
{153100}{}{Door}
{153200}{}{Door}
{153300}{}{Door}
{153400}{}{Door}
{153500}{}{Door}
{153600}{}{Door}
{153700}{}{Shower}
{153800}{}{Shuttle Wall}
{153900}{}{Shuttle Wall}
{154000}{}{Shuttle Wall}
{154100}{}{Shuttle Wall}
{154200}{}{Shuttle Wall}
{154300}{}{Shuttle Wall}
{154400}{}{Shuttle Wall}
{154500}{}{Shuttle Wall}
{154600}{}{Shuttle Wall}
{154700}{}{Shuttle Wall}
{154800}{}{Forcefield}
{154900}{}{Forcefield}
{155000}{}{Organ Extraction Unit}
{155001}{}{The latest model in Vault-Tec's "Do It Yourself" surgery series. Removes organs automatically with the press of a button.}
{155100}{}{Shuttle}
{155200}{}{Shuttle}
{155300}{}{Shuttle}
{155400}{}{Shuttle}
{155500}{}{Shuttle}
{155600}{}{Shuttle}
{155700}{}{Shuttle}
{155800}{}{Shuttle}
{155900}{}{Shuttle}
{156000}{}{Shuttle}
{156100}{}{Shuttle}
{156200}{}{Shuttle}
{156300}{}{Shuttle}
{156400}{}{Shuttle}
{156500}{}{Shuttle}
{156600}{}{Shadow}
{156700}{}{Shadow}
{156800}{}{Shadow}
{156900}{}{Shadow}
{157000}{}{Shadow}
{157100}{}{Shadow}
{157200}{}{Throne}
{157300}{}{Door}
{157400}{}{Door}
{157500}{}{Door}
{157600}{}{Door}
{157700}{}{Air Vent}
{157800}{}{Auto-Doc}
{157801}{}{This Auto-Doc is designed to heal illnesses and adminster various drugs.}
{157900}{}{Statue}
{157901}{}{A small statue of the famous Vault Dweller.}
{158000}{}{Pile of Rocks}
{158100}{}{Forcefield}
{158101}{}{An energy field is blocking your path.}
{158200}{}{Forcefield}
{158201}{}{An energy field is blocking your path.}
{158300}{}{Forcefield}
{158301}{}{An energy field is blocking your path.}
{158400}{}{Forcefield}
{158401}{}{An energy field is blocking your path.}
{158500}{}{Tanker}
{158600}{}{Tanker}
{158700}{}{Tanker}
{158800}{}{Tanker}
{158900}{}{Tanker}
{159000}{}{Tanker}
{159100}{}{Tanker}
{159200}{}{Tanker}
{159300}{}{Tanker}
{159400}{}{Tanker}
{159500}{}{Tanker}
{159600}{}{Tanker}
{159700}{}{Tanker}
{159800}{}{Tanker}
{159900}{}{Tanker}
{160000}{}{Wall}
{160100}{}{Wall}
{160200}{}{Floor Depression}
{160300}{}{Stone Bench}
{160400}{}{Stone Bench}
{160500}{}{Incense Burner}
{160600}{}{Satellite Dish}
{160700}{}{Satellite Dish}
{160800}{}{Shadow}
{160900}{}{Dock Shadow}
{161000}{}{Dock Shadow}
{161100}{}{Dock Shadow}
{161200}{}{Dock Shadow}
{161300}{}{Beam}
{161400}{}{Beam}
{161500}{}{Dock Shadow}
{161600}{}{Dock Shadow}
{161700}{}{Dock Shadow}
{161800}{}{Dock Shadow}
{161900}{}{Stairs}
{162000}{}{Deactivated Cyberdog}
{162001}{}{You see a deactivated Cyberdog.}
{162100}{}{Destroyed Power Generator}
{162101}{}{You see a destroyed power generator.}
{162200}{}{Track}
{162300}{}{Track}
{162400}{}{Track}
{162500}{}{Mine Cart}
{162600}{}{Mine Cart with Steel Pole}
{162700}{}{Mine Cart with Dynamite}
{162800}{}{Destroyed Mine Cart}
{162900}{}{Mine Cart}
{163000}{}{Pool Table}
{163100}{}{Pool Table}
{163200}{}{Pool Table}
{163300}{}{Pool Table}
{163400}{}{Pool Table}
{163500}{}{Pool Table}
{163600}{}{Desk}
{163700}{}{Flag}
{163800}{}{Wall}
{163900}{}{Wall}
{164000}{}{Wall}
{164100}{}{Wall}
{164200}{}{Exhaust Port}
{164300}{}{Desk}
{164400}{}{Desk}
{164500}{}{Stairs Down}
{164600}{}{Stairs Up}
{164700}{}{Stairs Up}
{164800}{}{Stairs Up}
{164900}{}{Mainframe Computer}
{165000}{}{Mainframe Computer}
{165100}{}{Mainframe Computer}
{165200}{}{Caravan Office Sign}
{165300}{}{Coffin Table}
{165400}{}{Coffin Table}
{165500}{}{Mine Elevator}
{165600}{}{Mine Elevator}
{165700}{}{Flagpole}
{165800}{}{NCR Flag}
{165900}{}{Poseidon Gasoline Sign}
{166000}{}{Stairs Down}
{166100}{}{Clinic Sign}
{166200}{}{Corrections Center Sign}
{166300}{}{Customs Sign}
{166400}{}{Customs Sign}
{166500}{}{Greeting Office Sign}
{166600}{}{Happy Harry's Sign}
{166700}{}{The Hole Sign}
{166800}{}{Information Center Sign}
{166900}{}{Information Center Sign}
{167000}{}{Vault City Logo}
{167100}{}{Main Council Sign}
{167200}{}{Main Council Sign}
{167300}{}{Maintenance Center}
{167400}{}{Parlor Room Sign}
{167500}{}{Tap House Sign}
{167600}{}{Westin Ranch Sign}
{167700}{}{Amenities Sign}
{167800}{}{Building A Sign}
{167900}{}{Building B Sign}
{168000}{}{Servant Allocation Center}
{168100}{}{Servant Allocation Center}
{168200}{}{Amenities Office Sign}
{168300}{}{Amenities Office Sign}
{168400}{}{Mine Elevator}
{168500}{}{Mine Elevator}
{168600}{}{Mine Elevator}
{168700}{}{Mine Elevator}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Shadow}
{169400}{}{Shadow}
{169500}{}{Shadow}
{169600}{}{Shadow}
{169700}{}{Crashed Vertibird}
{169800}{}{Crashed Vertibird}
{169900}{}{Crashed Vertibird}
{170000}{}{Crashed Vertibird}
{170100}{}{Crashed Vertibird}
{170200}{}{Crashed Vertibird}
{170300}{}{Shadow}
{170400}{}{Shadow}
{170500}{}{Shadow}
{170600}{}{Destroyed Bridge}
{170601}{}{You see what's left of the Arroyo bridge. There's no way back to the village now.}
{170700}{}{Destroyed Bridge}
{170701}{}{You see what's left of the Arroyo bridge. There's no way back to the village now.}
{170800}{}{Canyon}
{170900}{}{Door}
{171000}{}{Door}
{171100}{}{Wall}
{171200}{}{Wall}
{171300}{}{Wall}
{171400}{}{Wall}
{171500}{}{Wall}
{171600}{}{Wall}
{171700}{}{Wall}
{171800}{}{Wall}
{171900}{}{Air Vent}
{172000}{}{Air Vent}
{172100}{}{Bullet Proof Glass}
{172200}{}{Bullet Proof Glass}
{172300}{}{Bullet Proof Glass}
{172400}{}{Heavy Laser Turret}
{172500}{}{Heavy Laser Turret}
{172600}{}{Rocks}
{172700}{}{Rocks}
{172800}{}{Rocks}
{172900}{}{Rocks}
{173000}{}{Rocks}
{173100}{}{Rocks}
{173200}{}{Rocks}
{173300}{}{Rocks}
{173400}{}{Rocks}
{173500}{}{Rocks}
{173600}{}{Rocks}
{173700}{}{Becky's Casino Sign}
{173800}{}{Becky's Sign}
{173900}{}{Last Gasp Saloon Sign}
{174000}{}{Mom's Diner Sign}
{174100}{}{Slaver's Guild Sign}
{174200}{}{Survival/Gear Locker Sign}
{174300}{}{Tubby's Sign}
{174400}{}{Tubby's Sign}
{174500}{}{Mine Elevator Gate}
{174600}{}{Fan}
{174700}{}{Fan}
{174800}{}{President's Office Door}
{174900}{}{Eye Chart}
{175000}{}{Ruins}
{175100}{}{Guardian of Forever}
{175200}{}{Out of Order Sign}
{175300}{}{Collapsed Floor}
{175400}{}{Toilet}
{175500}{}{Cross}
{175600}{}{Wall}
{175700}{}{Wall}
{175800}{}{Wall}
{175900}{}{Wall}
{176000}{}{Wall}
{176100}{}{Wall}
{176200}{}{Wall}
{176300}{}{Wall}
{176400}{}{Building}
{176500}{}{Building}
{176600}{}{Building}
{176700}{}{Building}
{176800}{}{Building}
{176900}{}{Building}
{177000}{}{Steel Supports}
{177100}{}{Steel Supports}
{177200}{}{Steel Supports}
{177300}{}{Water}
{177400}{}{Water}
{177500}{}{Water}
{177600}{}{Water}
{177700}{}{Water}
{177800}{}{Water}
{177900}{}{Waterfall}
{178000}{}{Road}
{178100}{}{Road}
{178200}{}{Road}
{178300}{}{Road}
{178400}{}{Road}
{178500}{}{Road}
{178600}{}{Road}
{178700}{}{Bridge Support}
{178800}{}{Bridge Support}
{178900}{}{Bridge Support}
{179000}{}{Fence}
{179100}{}{Lamp}
{179200}{}{Lamp}
{179300}{}{Dead Whale}
{179301}{}{This whale appeared to have fallen from a great height.}
{179400}{}{Dead Whale}
{179401}{}{This whale appeared to have fallen from a great height.}
{179500}{}{Whale Fin}
{179501}{}{The fin of a dead whale.}
{179600}{}{Whale Eye}
{179601}{}{The eye of a dead whale.}
{179700}{}{Whale Chunk}
{179701}{}{A chunk of whale!}
{179800}{}{Whale Chunk}
{179801}{}{A chunk of whale!}
{179900}{}{Whale Chunk}
{179901}{}{A chunk of whale!}
{180000}{}{Whale Chunk}
{180001}{}{A chunk of whale!}
{180100}{}{Whale Chunk}
{180101}{}{A chunk of whale!}
{180200}{}{Boss Legs}
{180300}{}{Rocks}
{180400}{}{Rocks}
{180500}{}{Rocks}
{180600}{}{Rocks}
{180700}{}{Tannery Sign}
{180800}{}{Rose's B&B Sign}
{180900}{}{Vortis Holding Sign}
{181000}{}{Vortis Holding Sign}
{181100}{}{Great Wamamingo Mine Sign}
{181200}{}{Ascorti's Sign}
{181300}{}{Crashed Shuttle}
{181301}{}{A space vehicle of some kind. It looks like it crashed here recently.}
{181400}{}{Coffin}
{181500}{}{Stockman's Assoc. Sign}
{181600}{}{Slaughter-House Sign}
{181700}{}{Plank}
{181800}{}{Wood Door}
{181900}{}{Wood Door}
{182000}{}{Cola Fridge}
{182100}{}{Cola Fridge}
{182200}{}{Stove}
{182300}{}{Stove}
{182400}{}{Stove}
{182500}{}{Stove}
{182600}{}{Stuff}
{182700}{}{Stuff}
{182800}{}{Stuff}
{182900}{}{Stuff}
{183000}{}{Stuff}
{183100}{}{Stuff}
{183200}{}{Stuff}
{183300}{}{Stuff}
{183400}{}{President's Chair}
{183500}{}{Stairs}
{183600}{}{World Map}
{183700}{}{Situation Map}
{183800}{}{War Room Table}
{183900}{}{Council Room Table}
{184000}{}{Council Room Table}
{184100}{}{War Room Table}
{184200}{}{Tree}
{184300}{}{Tree}
{184400}{}{Ramp}
{184500}{}{Golden Globes Porn Sign}
{184600}{}{Ship Wheel}
{184700}{}{Ship Speed Control}
{184800}{}{Comm Station}
{184900}{}{Computer Console}
{185000}{}{Viewport Shutters}
{185100}{}{Steam}
{185200}{}{Container}
{185201}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185300}{}{Container}
{185301}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185400}{}{Container}
{185401}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185500}{}{Container}
{185501}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185600}{}{Container}
{185601}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185700}{}{Container}
{185701}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185800}{}{Container}
{185801}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{185900}{}{Container}
{185901}{}{Eine Art Gebäudekomplex. Du bist dir nicht sicher, aber du siehst große Container mit einem grünlichen Schleim, der irgendwie wichtig aussieht.}
{186000}{}{Motorcycle}
{186001}{}{This Chrysalis Motors Cruiser looks to be in pretty good shape for its age.}
{186100}{}{Motorcycle}
{186101}{}{This Chrysalis Motors Cruiser looks to be in pretty good shape for its age.}
{186200}{}{Sidecar}
{186201}{}{An old motorcycle sidecar. It appears to be in a good shape.}
{186300}{}{Wand}
{186400}{}{Kasinoschild}
{186401}{}{Sieht wie eine Werbetafel für Gizmos Kasino aus. Ausgeschaltet.}
