#
#   Messages from skill.c
#
#
#   SKILL NAMES
#
{100}{}{Kleine Waffen}
{101}{}{Große Waffen}
{102}{}{Energiewaffen}
{103}{}{Unbewaffnet}
{104}{}{Nahkampfwaffen}
{105}{}{Werfen}
{106}{}{Erste Hilfe}
{107}{}{Arzt}
{108}{}{Schleichen}
{109}{}{Öffnen}
{110}{}{Stehlen}
{111}{}{Fallen}
{112}{}{Wissenschaft}
{113}{}{Reparieren}
{114}{}{Reden}
{115}{}{Handeln}
{116}{}{Spielen}
{117}{}{Naturbursche}
#
#   SKILL DESCRIPTIONS
#
{200}{}{Die Handhabung, Wartung und Kenntnis kleiner Feuerwaffen wie Pistolen, Klein-MGs und Gewehre.}
{201}{}{Die Handhabung und Wartung richtig großer Waffen wie Kleingeschütze, Raketenwerfer, Flammenwerfer u. ä.}
{202}{}{Die Handhabung und Wartung von Energiewaffen. Wie man Waffen lädt und bedient, die Laser- oder Plasmatechnologie benutzen.}
{203}{}{Eine Kombination aus Karate, Boxen und anderen asiatischen Kampfsportarten. Der Kampf mit Händen und Füßen.}
{204}{}{Die Verwendung von Nahkampfwaffen wie Messer, Vorschlaghämmer, Speere, Knüppel usw.}
{205}{}{Das Werfen von Waffen aus eigener Kraft; z. B. Wurfmesser, Speere und Granaten.}
{206}{}{Zur Heilung kleiner Schnitt- und Schürfwunden sowie anderer kleiner Verletzungen. Mit der Fähigkeit 'Erste Hilfe' können im gleichen Zeitraum mehr Trefferpunkte geheilt werden als durch Ausruhen.}
{207}{}{Zur Heilung großer Wunden und schwer verletzter Gliedmaßen. Ohne diese Fähigkeit dauert es wesentlich länger, bis schwer verletzte Gliedmaßen wieder einsatzfähig sind.}
{208}{}{Unauffälliges Bewegen und die Fähigkeit, unerkannt zu bleiben. Im Erfolgsfall bist du schwerer ausfindig zu machen. Gleichzeitiges Laufen und Schleichen ist nicht möglich.}
{209}{}{Die Fähigkeit, Schlösser ohne den richtigen Schlüssel zu öffnen. Die Verwendung mechanischer oder elektronischer Dietriche steigert diese Fähigkeit erheblich.}
{210}{}{Die Fähigkeit, sich die Sachen anderer anzueignen. Zum Bestehlen von Leuten oder Lokalitäten.}
{211}{}{Das Finden und Entfernen von Fallen sowie das Legen von Sprengsätzen.}
{212}{}{Beinhaltet eine Vielfalt von Hi-Tech-Fähigkeiten wie den Umgang mit Computern und Biologie-, Physik- und Geologiekenntnisse.}
{213}{}{Die praktische Anwendung der Fähigkeit 'Wissenschaft'. Das Reparieren defekter Geräte, Maschinen und elektronischer Bauteile.}
{214}{}{Die Fähigkeit, sachlich und effizient zu kommunizieren und dabei andere von der Richtigkeit seiner Position zu überzeugen. Die Fähigkeit, zu lügen und dabei nicht erwischt zu werden.}
{215}{}{Handel treiben und damit verwandte Aufgaben. Die Fähigkeit, einen höheren Verkaufspreis und einen niedrigeren Einkaufspreis auszuhandeln.}
{216}{}{Das Know-How und die praktische Kenntnis des Glücksspiels. Karten spielen, Würfeln und andere Glücksspiele.}
{217}{}{Praktisches Wissen über die Natur und die Fähigkeit, sich von den Gaben der Natur zu ernähren. Das Wissen über Pflanzen und Tiere.}
#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{300}{}{+ BE}
{301}{}{+ BE}
{302}{}{+ BE}
{303}{}{+ (BE + ST)/2}
{304}{}{+ (BE + ST)/2}
{305}{}{+ BE}
{306}{}{+ (WA + IN)}
{307}{}{+ (WA + IN)/2}
{308}{}{+ BE}
{309}{}{+ (WA + BE)/2}
{310}{}{+ BE}
{311}{}{+ (WA + BE)/2}
{312}{}{+ (2 x IN)}
{313}{}{+ IN}
{314}{}{+ (2 x CH)}
{315}{}{+ (2 x CH)}
{316}{}{+ (3 x GL)}
{317}{}{+ (AU + IN)/2}
#
#   Skill Use Text
#
{500}{}{Du heilst %d Trefferpunkte.}
{501}{}{Du siehst bereits gesund aus.}
{502}{}{%s sieht bereits gesund aus.}
{503}{}{Bei dir stellt sich keine Heilung ein.}
{505}{}{Du erhälst %d Erfahrungspunkte für die Verbesserung deiner Fähigkeiten.}
{510}{}{\nskill_use: Ungültige Fähigkeit benutzt.}
{512}{}{Du kannst die Toten nicht heilen!}
{513}{}{Laß die Toten ruhen!}
{514}{}{Das ist tot. Find dich damit ab!}
{520}{}{Du heilst dein %s.}
{521}{}{Du heilst %s.}
{525}{}{Du kannst nicht dein %s heilen.}
{526}{}{Du kannst nicht %s heilen.}
{530}{}{verletztes Auge}    # Lines 530-534 are the endings to lines 525 & 526.
{531}{}{verletzten linken Arm}
{532}{}{verletzten rechten Arm}
{533}{}{verletztes rechtes Bein}
{534}{}{verletztes linkes Bein}
{550}{}{Du kannst das Schloß nicht öffnen.}
{551}{}{Du kannst keine Fallen finden.}
{552}{}{Du kannst nichts dazulernen.}
{553}{}{Du kannst das nicht reparieren.}
{570}{}{Du wirst beim Stehlen von %s erwischt.}
{571}{}{Du stiehlst %s.}
{572}{}{Du wirst beim Legen von %s erwischt.}
{573}{}{Du legst %s.}
{590}{}{Du hast dich mit dieser Fähigkeit überanstrengt. Warte einen Augenblick.}
{591}{}{Du bist zu müde.}
{592}{}{Die Anstrengung könnte dich töten.}

# Fallout 2!
{600}{}{Du verfügst nicht über die Fähigkeiten, schwere Verletzungen zu heilen.}
{601}{}{Die Robotereinheit ist nicht mehr zu reparieren.}



#
# Fallout 2: Party Member skill use generic responses
#

#   I'll try
{1000}{}{Laß mich helfen.}
{1001}{}{Ich kann das machen.}
{1002}{}{Ich hab's.}
{1003}{}{Ist mir ein Vergnügen.}
{1004}{}{Okay.}
{1005}{}{Ich versuch's.}

#   Player wants to do it
{1100}{}{Sag Bescheid, wenn's Probleme gibt.}
{1101}{}{Hast du's?}
{1102}{}{Wenn du das willst.}
{1103}{}{Los, versuch's.}
{1104}{}{Mach du nur.}
