{100}{}{You see: Aradesh.}
{101}{Ara_1g}{Greetings, wanderer. Please do not be offended if the gentlefolk about seem rude. As Dharma said, 'Tough times tan the human hide.' Your business in Shady Sands might be?}
{102}{Ara_1n}{Greetings. Your business in Shady Sands might be?}
{103}{Ara_1b}{We don't take to strangers much. Your business in Shady Sands?}
{104}{}{I'm from a small village west of here. I'm just exploring and mean you no harm.}
{105}{}{What's it to you?}
{106}{}{My reasons are mine to keep.}
{107}{}{I'm from a Vault to the west. My people are dying of thirst and I need to find a water purifier chip for them to survive.}
{108}{}{I'm saving an entire people from destruction!}
{109}{}{Shady Sands? Whoops, I'm lost! I'll just be going now.}
{110}{}{Hunh?}
{111}{Ara_2}{I know of no village to the west.}
{112}{}{Have you been through the mountains west of here?}
{113}{}{So?}
{114}{}{Are you saying you know every location from here to the ocean?}
{115}{}{I'm sure you've been many places, but you must have missed my tiny village.}
{116}{Ara_3}{Ah well, to my regret, I have not. Which begs the question: How did you make that passage?}
{117}{}{It was pretty tough, but I made it.}
{118}{}{What's it to you?}
{119}{}{Look, all I wanted was a few supplies and things, but I will gladly go elsewhere.}
{120}{}{I don't need to answer you.}
{121}{Ara_4}{Yes, hmmm, yes, yes, yes. I shall believe you... for now. But we do not trust easily, especially those who might be dangerous. Know that Seth and I will be watching you.}
{122}{Ara_5}{It is my town, wanderer. You must answer my questions or leave. This is not a matter of choice.}
{123}{}{I don't have to tell you anything.}
{124}{}{I mean you no harm, really.}
{125}{}{Don't worry, I'm leaving.}
{126}{Ara_6}{You are quite insolent. I believe you should leave. Do not return. You will not be welcome.}
{127}{Ara_7}{So be it, wanderer. Seth will show you out.}
{128}{Ara_8}{You must think me quite gullible, wanderer. You conquered the mountains by yourself?}
{129}{}{Doesn't matter how I think. It's true, I came from the mountains.}
{130}{}{No, just stupid.}
{131}{Ara_9}{As Dharma said, 'Caution is life in troubled times.' Your origin is not the issue. Your intent is.}
{132}{}{Okay.}
{133}{Ara_9A}{I will let you pass, but know this: Seth and I will watch you very, very closely. Do not even consider bringing trouble here.}
{134}{Ara_10}{And keep them you may. But this is not a city of open hospitality. If you desire that, go to Junktown. You may enter, but know we have our eyes on you.}
{135}{Ara_11}{A Vault. How shall I trust you, wanderer, when you are not honest with me?}
{136}{}{No, honestly, I come from a Vault!}
{137}{}{The Vault is... the name of my village.}
{138}{}{You're right, I was lying.}
{139}{Ara_12}{Hmmm, yes, yes, yes. Then tell me of this Vault.}
{140}{}{Well... the Vault is actually the name of my town. We name it that because it's in between two big cliffs.}
{141}{}{It's a big place built into a mountain far to the west. My people have been there for the last 80 years.}
{142}{}{Why do you want to know?}
{143}{Ara_13}{Wanderer, I shall believe you... for now. You may enter Shady Sands, but be warned your every move will be watched.}
{144}{Ara_14}{I will not be lied to, wanderer.}
{145}{}{I don't have to tell you anything.}
{146}{}{I mean you no harm, really.}
{147}{}{Don't worry, I'm leaving.}
{148}{Ara_15}{Hmmm. You may enter. But stay out of trouble.}
{149}{}{What can you tell me about the other towns around here?}
{150}{}{What's going on around here?}
{151}{}{Thanks. Bye.}
{152}{Ara_17}{Greetings again, young wanderer. I hope your stay here has been pleasant.}
{153}{}{It's been great. Can I ask you some questions?}
{154}{}{It has. I gotta run though.}
{155}{}{If you like sewers.}
{156}{}{Nuh-huh.}
{157}{Ara_18n}{Greetings. What may I help you with this fine day?}
{158}{Ara_18b}{Is there something you want?}
{159}{}{Can you tell me about Shady Sands?}
{160}{}{I was wondering if I could ask you a few questions?}
{161}{}{Nothing, really, I was just leaving.}
{162}{}{Nuh-uh.}
{163}{Ara_19}{Certainly. What do you wish to know?}
{164}{Ara_19b}{You may ask, but please hurry. There are more important uses for my time.}
{165}{}{What can you tell me about the other towns around here?}
{166}{}{What's going on around here?}
{167}{}{Thanks. Bye.}
{168}{Ara_20g}{Ah. Happy journeys, wanderer.}
{169}{Ara_20n}{Goodbye.}
{170}{Ara_20b}{I certainly hope so.}
{171}{Ara_21}{Dharma said, 'A man and his wayward tongue are soon parted.' Come back when you have learned some manners.}
{172}{Ara_22}{That is quite enough, wanderer. Seth will show you out of the city. Do not return. Your welcome will not be pleasant.}
{173}{Ara_23g}{Shady Sands is much like a family, one that keeps to itself.}
{174}{Ara_23b}{We are a very protective community. As Dharma said, 'Many sticks can be broken. A bundle cannot.'}
{175}{}{What kind of things do you have around here?}
{176}{}{Interesting. Are there any other cities around here?}
{177}{}{How cute. Well, I better be going.}
{178}{Ara_24}{The Gardens are on the south side. The Brahma Pens are north, although the smell is, I fear, quite intense this time of year.}
{179}{}{Anything else?}
{180}{Ara_24a}{We are small and self-sufficient so there is little else to tell.}
{181}{}{Thanks. Can I ask you a few more questions?}
{182}{}{Thanks. Bye.}
{183}{Ara_24b}{It is a small place. You have feet.}
{184}{}{Thanks. Can I ask you a few more questions?}
{185}{Ara_25b}{Dharma said, 'Heed not the call of the wolf when the fox is raiding the hen house.'}
{186}{Ara_25g}{Junktown lies south of here, though there is little in the way of visitation. From stories, I'm certain there are cities south of that.}
{187}{}{Thanks. I... Can I ask you a few more questions?}
{188}{Ara_26}{It is a quiet time, thankfully.}
{189}{}{Sounds... boring.}
{190}{}{Well, then, can I ask you a few more questions?}
{191}{}{Good. Hopefully it will stay that way for a while.}
{192}{Ara_27}{Yes. We like it that way.}
{193}{}{What can you tell me about the other towns around here?}
{194}{}{What's going on around here?}
{195}{}{Thanks. Bye.}
{196}{Ara_28}{Oh my yes. Great packs of radscorpions are killing our herds. We don't know where they're from, and no matter how many we kill, there's always more!}
{197}{}{Go on.}
{198}{Ara_28a}{And now the monsters are attacking my people! Razlo is trying to find a cure for their poison, but I'm not sure how it goes.}
{199}{}{Well, I'll help you get rid of these things!}
{200}{}{I can help you for a price.}
{201}{}{That's terrible. Can I ask you a few more questions?}
{202}{Ara_29}{Ummm, yes, yes, yes, yes, yes! Please talk to Razlo. He possesses far more information on these creatures than I.}
{203}{Ara_30}{As Dharma said, 'Those who tend their own flock, know the shepherd.'}
{204}{}{I know it's hard for you to trust, but I would like to help.}
{205}{}{Your choice. Can I ask you some more questions?}
{206}{Ara_30a}{Please hurry and rid us of those radscorpions!}
{207}{Ara_31}{Things are much more settled now. Razlo has been working on a cure for radscorpion poison, and with that, we should be able to fight what's left of them.}
{208}{}{It was nothing. Can I ask you some more questions?}
{209}{}{You don't need to worry anymore. I destroyed the nest.}
{210}{Ara_32}{You are truly a hero! Know that the people of Shady Sands are most grateful.}
{211}{}{Thanks. Can I ask you a few more questions, though?}
{212}{}{Thanks. Bye!}
{213}{Ara_33}{If you can understand me, please try to find my daughter.}
{214}{Ara_35}{Since you brought my Tandi back to me, things are quite fine. My eternal gratitude to you, wanderer.}
{215}{}{What can you tell me about the other towns around here?}
{216}{}{What's going on around here?}
{217}{}{Thanks. Bye.}
{218}{Ara_36}{Yes, yes. Umm. Have a good stay.}
{219}{Ara_37}{Ahh, wanderer. How goes the search for my daughter?}
{220}{}{Sorry, but I haven't found her. I will, though.}
{221}{}{I'm sorry, but she is dead.}
{222}{}{Duh-nada.}
{223}{}{Sorry, but I haven't found her. I will, though.}
{224}{}{Slow, but I am making some progress. Can I ask you a few more questions?}
{225}{}{Guunngggg!}
{226}{Ara_37a}{Thank you for trying. Please leave me to my grief.}
{227}{Ara_38}{May my thoughts be wings to your feet. Please hurry.}
{228}{Ara_39}{Thank goodness you came! I am in desperate need of assistance. My daughter, Tandi, is missing. I do not know what to do!}
{229}{}{Have you tried to save her?}
{230}{}{Uhh?}
{231}{Ara_39a}{My people are not skilled in this. Already three patrols have gone out to look, but none returned. Will you help me?}
{232}{}{Okay. Who could have taken her?}
{233}{}{I'll do it... for a fee.}
{234}{}{I am sorry, but I have other things I have to do.}
{235}{Ara_40}{Seth and I believe one of the raider clans is responsible - retribution for our resistance to them. Take this spear. It was found where my daughter was last seen.}
{236}{}{Okay, I'll check it out.}
{237}{Ara_40A}{Please, talk to Seth. He knows much about these raiders. And God speed, wanderer.}
{238}{Ara_41}{Of course, I will reward you. Bring her and you will receive 500 in Hub script. Will you help me?}
{239}{}{Okay. Who could have taken her?}
{240}{}{Ah... no thanks. I got other stuff I gotta take care of.}
{241}{Ara_42}{As Dharma said, 'While you are out hunting the wolves, do not bring the lion to your den.' If you will not help, you must leave here.}
{242}{Ara_43}{I will be forever in your debt for your courage and bravery, wanderer. Here is your reward.}
{243}{}{Thanks. Can I ask you a few more questions, first?}
{244}{}{Thanks.}
{245}{Ara_44}{Until we meet again, my friend. May the water you find in the desert not shine at you in the dark.}
{246}{Ara_45}{What are you doing? Put that back at once!}
{247}{Ara_46}{That is not yours. Please do not take it.}
{248}{Ara_47}{Stop that at once!}
{249}{Ara_48}{What are you doing here? I am resting, come back in the morning!}
{250}{Ara_49}{I am he. I lead this humble town of Shady Sands.}
{251}{Ara_49A}{Dharma was a great, religious man. You would do well to listen closely to his sayings.}
{252}{Ara_50}{She is my daughter. It is she that makes this hard life worth living.}
{253}{Ara_51}{Hmm, yes, yes. Razlo is our doctor. If it ails you, he can heal it. I would wager he is just a little north of here at this moment.}
{254}{Ara_52}{A fine young man, Seth. Captain of our guards. He is likely to be at the guardhouse.}
{255}{Ara_53}{A wonderful woman. She just celebrated her sixtieth birthday! She spends much time with Razlo, talking his ear off with her veritable treasure trove of stories.}
{256}{Ara_54}{Ummm, um, um. Very bad. There are two bands of raiders that we know of. They call themselves the Vipers and the Khans.}
{257}{Ara_55}{Be very careful with such as these. Raiders who are fanatically religious can be quite dangerous. No one here knows of their base.}
{258}{Ara_56}{Umm, yes, yes. The Khans are nastier than the Vipers, let me tell you. These barbarians attack from the southeast.}
{259}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{260}{Ara_58}{Yes, yes. yes. It is a rumor of a monster created during the War.}
{261}{}{}
{262}{Ara_60}{Junktown is south of here. Their merchants occasionally come to trade, but not often.}
{263}{Ara_61}{The Vipers and Khans both use spears. We know this from their attacks.}
{264}{Ara_62}{You will find it at the front of town. Seth will likely be there.}
{265}{Ara_63}{No one knows for certain, but the packs seem to be coming from the northeast.}
{266}{Ara_64}{I don't know.}
{267}{Ara_65}{I can't really say I have heard of that.}
{268}{Ara_66}{Hm, no. No, I have not heard of that.}
{269}{Ara_67}{As I said...}
{270}{Ara_68}{Like I mentioned earlier...}
{271}{Ara_69}{Like I said...}
{272}{Ara_70}{As I had told you before...}
{273}{Ara_71}{I shall not repeat myself so often as to make myself sound stupid. Please listen next time.}
{274}{Ara_72}{I will not stand here like a sputtering candle simply because you cannot listen.}
{275}{Ara_73}{Go talk to Seth about that. He'll know more than I.}
{276}{}{}
{277}{}{I will not waste my time on treacherous outsiders.}
{278}{}{Aradesh is furious and refuses to talk to you any more.}	# Line 278 was previously in GENCHAT, Line 170

# Tell Me About generic responses
{980}{Ara_64}{I don't know.}
{981}{Ara_65}{I can't really say I have heard of that.}
{982}{Ara_66}{Hm, no. No, I have not heard of that.}

{1000}{}{Aradesh|LEADER}
{1001}{}{Dharma}
{1002}{}{Tandi}
{1003}{}{Razlo|HELP}
{1004}{}{Raiders|RAIDERS}
{1005}{}{Vipers|VIPER}
{1006}{}{Khans|KHAN}
{1007}{}{Scorpions|Scorpion|Rad Scorpion|Radscorpions|Radscorpion}
{1008}{}{Claw|Claws|Deathclaw|Deathclaws}
{1009}{}{Junktown}
{1010}{}{Spear}
{1011}{}{Guard House|GUARDHOUSE|Guardhouse}
{1012}{}{Lair|NEST}
{1013}{}{Seth|SET|CAPTAIN}
{1014}{}{Shady|Sands|Shady Sands|Family}
{1015}{}{Hub|GUARD|GUARDS}

{1100}{Ara_49}{I am he. I lead this humble town of Shady Sands.}
{1101}{Ara_49A}{Dharma was a great, religious man. You would do well to listen closely to his sayings.}
{1102}{Ara_50}{She is my daughter. It is she that makes this hard life worth living.}
{1103}{Ara_51}{Hmm, yes, yes. Razlo is our doctor. If it ails you, he can heal it. I would wager he is just a little north of here at this moment.}
{1104}{Ara_54}{Ummm, um, um. Very bad. There are two bands of raiders that we know of. They call themselves the Vipers and the Khans.}
{1105}{Ara_55}{Be very careful with such as these. Raiders who are fanatically religious can be quite dangerous. No one here knows of their base.}
{1106}{Ara_56}{Umm, yes, yes. The Khans are nastier than the Vipers, let me tell you. These barbarians attack from the southeast.}
{1107}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1108}{Ara_58}{Yes, yes. yes. It is a rumor of a monster created during the War.}
{1109}{Ara_60}{Junktown is south of here. Their merchants occasionally come to trade, but not often.}
{1110}{Ara_61}{The Vipers and Khans both use spears. We know this from their attacks.}
{1111}{Ara_62}{You will find it at the front of town. Seth will likely be there.}
{1112}{Ara_63}{No one knows for certain, but the packs seem to be coming from the northeast.}
{1113}{Ara_52}{A fine young man, Seth. Captain of our guards. He is likely to be at the guardhouse.}
{1114}{Ara_23g}{Shady Sands is much like a family, one that keeps to itself.}
{1115}{Ara_73}{Go talk to Seth about that. He'll know more than I.}
