{100}{}{You see: Bob.}
{101}{}{No way I'll let you rob me blind!}
{102}{}{Hey, I don't want no trouble!}
{103}{}{Gimme an iguana on a stick.}
{104}{}{What can you tell me about a Water Chip?}
{105}{}{What can you tell me about Decker?}
{106}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{107}{}{Do you know anything about the missing caravans?}
{108}{}{What, me trouble? What gives you that impression?}
{109}{}{Me hungry! Grrrr!}
{110}{}{Hi. Welcome to Bob's Iguana Bits, the family eating place. May I take your order?}
{111}{}{Gimme an iguana on a stick.}
{112}{}{What can you tell me about a Water Chip?}
{113}{}{What can you tell me about Decker?}
{114}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{115}{}{Do you know anything about the missing caravans?}
{116}{}{Anything interesting happening in the Hub?}
{117}{}{Me hungry! Grrrr!}
{118}{}{Sorry, we're all out of iguana.}
{119}{}{We only have whole iguana on a stick. Twenty bucks each.}
{120}{}{We only have prime cut select. It tastes great, though. Eight bucks each.}
{121}{}{Sure. We got whole iguana on a stick for twenty bucks, and our prime cut pieces for eight bucks.}
{122}{}{I'll take a whole iguana.}
{123}{}{I'll take your prime cut.}
{124}{}{You know, I hear your prime cut tastes like chicken.}
{125}{}{No sissy portions! Me want all iguana! Ugh!}
{126}{}{Hmm, smell good! Prime cut make tummy happy!}
{127}{}{We don't serve that here. Anything else?}
{128}{}{Gimme an iguana on a stick.}
{129}{}{What can you tell me about Decker?}
{130}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{131}{}{Do you know anything about the missing caravans?}
{132}{}{Anything interesting happening in the Hub?}
{133}{}{Me hungry! Grrrr!}
{134}{}{Mr. Decker is a distinguished businessman in a less than distinguished business. Anything else?}
{135}{}{I want information on Doc Morbid.}
{136}{}{Gimme an iguana on a stick.}
{137}{}{Nothing.}
{138}{}{He was a mean son of a bitch and anyone who isn't glad he's dead is a damned liar. Can I take your order?}
{139}{}{Gimme an iguana on a stick.}
{140}{}{Tell me a little about the Water Merchants.}
{141}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{142}{}{Do you know anything about the missing caravans?}
{143}{}{Anything interesting happening in the Hub?}
{144}{}{Me hungry! Grrrr!}
{145}{}{I don't know what you're talking about. Okay. I'll pay you one hundred bucks if you keep your mouth shut. Take it and get out.}
{146}{}{I want two hundred.}
{147}{}{I'll take the hundred.}
{148}{}{I'm going to the police.}
{149}{}{Stop selling them. Now.}
{150}{}{Terrible business. Those poor people. Oh, those poor people. Losing their lives in such a ghastly way! Is there anything else I can do for you? Like feed you, perhaps?}
{151}{}{Gimme an iguana on a stick.}
{152}{}{What can you tell me about a Water Chip?}
{153}{}{What can you tell me about Decker?}
{154}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{155}{}{Anything interesting happening in the Hub?}
{156}{}{Nothing. Sorry to bring it up. I just hear stories. Now is there anything else I can do for you?}
{157}{}{Gimme an iguana on a stick.}
{158}{}{What can you tell me about a Water Chip?}
{159}{}{What can you tell me about Decker?}
{160}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{161}{}{Do you know anything about the missing caravans?}
{162}{}{Anything interesting happening in the Hub?}
{163}{}{Someone killed Decker. We're in mourning, at least until the Hub runs out of booze.}
{164}{}{Someone shot Sheriff Greene. Don't know about the deputy though.}
{165}{}{Daren Hightower was murdered. And all that money couldn't save him. Ironic, ain't it?}
{166}{}{Someone has really pissed off someone important, because I hear that there's a big hit out on some poor sod.}
{167}{}{Someone stole a necklace from the Hightowers. Man, did they ever make a big mistake. They're dead for sure.}
{168}{}{Someone killed Jain over at the Cathedral. I hear she was a real bitch!}
{169}{}{Well, the only new thing is that the Children of the Cathedral have taken over the hospital. It's pretty boring around here lately. Mind you, they're a strange crowd.}
{170}{}{Anything else?}
{171}{}{Gimme an iguana on a stick.}
{172}{}{What can you tell me about a Water Chip?}
{173}{}{What can you tell me about Decker?}
{174}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{175}{}{Do you know anything about the missing caravans?}
{176}{}{Sorry, you can't afford one.}
{177}{}{One whole iguana, coming up! Anything else?}
{178}{}{Gimme another iguana on a stick.}
{179}{}{What can you tell me about a Water Chip?}
{180}{}{What can you tell me about Decker?}
{181}{}{Do you know anything about the missing caravans?}
{182}{}{Anything interesting happening in the Hub?}
{183}{}{Me want another iguana!}
{184}{}{Me stuffed! URRRP!}
{185}{}{Sorry, you can't afford one.}
{186}{}{One iguana prime cut select, coming up! Anything else?}
{187}{}{Gimme another iguana on a stick.}
{188}{}{What can you tell me about a Water Chip?}
{189}{}{What can you tell me about Decker?}
{190}{}{Do you know anything about the missing caravans?}
{191}{}{Anything interesting happening in the Hub?}
{192}{}{Me want another iguana!}
{193}{}{Me stuffed! URRRP!}
{194}{}{Thank you. Come again!}
{195}{}{You must be new in town if you're asking me about the Water Merchants. Water is life. And you don't get much more powerful than life and death.}
{196}{}{Gimme an iguana on a stick.}
{197}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{198}{}{Do you know anything about the missing caravans?}
{199}{}{Anything interesting happening in the Hub?}
{200}{}{Me hungry! Grrrr!}
{201}{}{You greedy son of a bitch!}
{202}{}{You greedy whore!}
{203}{}{All right, you win. Here's your money. Take it and don't come back!}
{204}{}{I'd change your mind if I were you, friend. People have died for less in the Hub. Now get out and don't come back!}
{205}{}{Maybe I've been using some questionable portions, but it's not like I'm committing murder. Like Morbid's stuff is already dead, ain't it?}
{206}{}{I'm sure it is, Bob. And I'm sure the police will agree.}
{207}{}{Cannibalism is a crime against humanity, Bob. I'm going to see that you pay for your it.}
{208}{}{Maybe it is. Maybe it isn't. I don't care. It's immoral. Stop it.}
{209}{}{No way! I ain't letting you screw me! Eat this!}
{210}{}{I ain't going broke because of your scruples, but you're gonna die from them! Eat this!}
