{100}{}{This bookshelf is filled with religious and philosophical books. It's also very dusty.}
{101}{}{You take a book down, examine it, and put it back on the shelf. The shelf itself seems very sturdy.}
{102}{}{You find a hidden latch.}
{103}{}{That does nothing.}
{104}{}{The wall next to the bookshelf quietly slides out of the way.}
{105}{}{You fumble with the bookcase for a moment but fail to accomplish anything.}
{200}{}{The bookshelf is filled with religious and philosophical books.}
{201}{}{The latch will not budge.}

# Fo1in2
{202}{}{ finds a hidden latch.}
{203}{}{ fumbles with the bookcase for a moment but fails to accomplish anything.}
