{100}{}{You see a kind-looking woman in a doctor's uniform.}
{101}{}{You see: Lorri, the Head Doctor of the Brotherhood's medical facilities.}
{102}{}{Hello, how may I help you?}
{103}{}{I'm injured.}
{104}{}{I'm irradiated.}
{105}{}{Do you do operations?}
{106}{}{Tell me about the operations again.}
{107}{}{You fix?}
{108}{}{Are you injured? Let's see...}
{109}{}{That was the problem. There you go. Be more careful out there.}
{110}{}{Sorry, I can't help you if you won't tell me what's wrong.}
{111}{}{ You seem fine.}
{112}{}{There you are. I hope you feel better.}
{113}{}{There you go, but stop getting into so many fights!}
{114}{}{That should do, all fixed up.}
{115}{}{Good as new.}
{116}{}{All better!}
{117}{}{Radiation is very dangerous; you should be more careful.}
{118}{}{I don't have the time for games.}
{119}{}{Of course, but it's very costly and time consuming.}
{120}{}{Details?}
{121}{}{Okay, never mind.}
#
# 122 for Fallout Fixt if using Full install and/or Charimsa operation enabled:
{122}{}{Well, I can help make you stronger, more perceptive, increase your endurance, help improve your learning process, and increase your dexterity. I have also studied plastic surgery procedures. Which would you like more information on?}
#
# 222 is with "Bug Fixes Only" enabled, or Charisma operation disabled. Same message as VANILLA:
{222}{}{Well, I can help make you stronger, more perceptive, increase your endurance, help improve your learning process, and increase your dexterity. Which would you like more information on?}
#
{124}{}{Who are you?}
{125}{}{My name is Lorri. I lead the medical staff and administer all major surgeries and medical procedures. I am effectively the only Doctor here, thus I prefer to keep things on a first-name basis. And you are?}
{126}{}{Okay, which operation would you like to talk about?}
{127}{}{Strength.}
{128}{}{Perception.}
{129}{}{Endurance.}
{123}{}{Charisma.}
{130}{}{Intelligence.}
{131}{}{Agility.}
{132}{}{Never mind.}
{133}{}{That's easy to do, but there's a long recovery time. It only costs }
{134}{}{I'm }
{135}{}{I'll do it!}
{136}{}{I'll pass.}
{137}{}{Now that's a difficult operation. It costs }
#
# TRANSLATION NOTE: Player's name will be inserted after line 138. Then appends 152 and 142.
#                   Brotherhood of Steel calls everyone "Brother ____", even females.
#
{138}{}{It's a pleasure to meet you, Brother }
#
{139}{}{This one's not that difficult. It takes about a week and will cost }
{140}{}{I've been poisoned!}
{141}{}{This is the most complex and dangerous! It'll take 3 weeks and costs }
{142}{}{ Now, what can I do for you?}
{143}{}{This isn't that tough of an operation but it is very costly and time consuming. It will take 3 weeks and cost }
{144}{}{[Continue]}
{145}{}{This operation is moderately difficult with a long recovery time. It will cost }
{146}{}{Okay, there you go. I hope the foam didn't irritate your skin.}
{147}{}{I'm sorry, but I can't help you if you don't have the money.}
{148}{}{I'm sorry, but you are an outsider. After you're in the Brotherhood for ten years or so I'll be able to do the operation for free, but we have expenses and you're not a regular working member of the Brotherhood yet.}
{149}{}{Let me know when you have the necessary funds for this operation.}
{150}{}{I cannot accurately assess your physical strength while you are wearing Power Armor. Please remove it and speak with me again.}
#
#TRANSLATION NOTE: Player's name will be inserted between lines 151 and 152.
#
{151}{}{I'm }
{152}{}{.}
#
{153}{}{Did you want to ask about another one?}
#
# 155 and 157 are for stupid characters.
#
{155}{}{Tummy feel sick!}
{157}{}{Hep?}
{158}{}{Hello again, how may I help you?}
#
#STRENGTH
{154}{}{Okay, here goes nothing... Just kidding. We can start right away. (You breathe in the anesthetic and slowly slip away)}
{156}{}{So, how are we feeling? (You can already tell the difference) You're quite a talkative person in your sleep. You're free to go! Good day.}
#
#PERCEPTION
{159}{}{Out with the old and in with the new... Where are my pliers? (You drop like a rock into an abyss)}
{161}{}{Hmmm. You look exactly the same, but how do you feel? (Your senses seem much sharper) Well, you're taking up valuable bed space. Get going!}
#
#ENDURANCE
#Translation: "fall under" meaning fade into unconsciousness under the effect of the anesthetic
{164}{}{I hope you have a heart... (She winks at you as you fall under)}
{166}{}{Well, you do look a little bulkier now. (You feel great!) Let me know if there are any problems, and don't go swimming for at least an hour.}
#
#CHARISMA
{180}{}{I hope you don't end up with a lazy eye like the last one... (You struggle to fight the drugs but they are too powerful)}
{181}{}{My, my, you are striking. I really outdid myself. (She looks you up and down a few times and then seems to snap out of it) Oh, sorry, you're free to go now.}
#182 and 185 are said by player:
{182}{}{Thanks!}
{185}{}{Not as striking as you.}
#
#INTELLIGENCE
{168}{}{Now where's the brain again? What's this thing supposed to do? (You try to fight the drugs but it's a losing battle)}
{170}{}{Well, it looks like I got it all back in. Everything seems to be running just fine. (It's as if the pathways of your thoughts have direct links to everything in your head, and your memories are much crisper)}
#
#AGILITY
{174}{}{All right, let's give it a spin. Try not to flinch. (The drugs are so... friendly. Your slumber comes quickly)}
{176}{}{Okay, you're ready for duty. (You move your limbs and can feel the increased speed and control) All I ask of you is to please not damage my masterpiece.}
#
# NOT Lorri
#
{200}{}{You see the Doctor's assistant.}
{233}{}{ script but takes 3 weeks to heal.}
{237}{}{ script, but the recovery from this operation is only a week.}
{239}{}{ script.}
{241}{}{ script.}
{243}{}{ script.}
{245}{}{ script and takes 3 weeks to heal.}
{279}{}{You should see the Doctor.}
{280}{}{She's the Doctor, not me.}
{281}{}{I'm only in training.}
{282}{}{I can't help you, officially.}
{283}{}{Lorri's the Doctor.}
{284}{}{You have to ask the Doctor.}
{285}{}{Don't worry, she's just a kidder.}
{286}{}{She just likes to tease, don't worry.}
#
# Stat is already maxxed:
{500}{}{I'm sorry but this operation will not help you.}
#
{400}{}{Hmmm. If anyone here needs an intelligence enhancement, it would be you. In fact, I'll do it for 3000 script instead of the 6000 you would normally need for the operation. I can't guarantee that it will help you, but I think it would be worth a try. It will also take 3 weeks of recovery time. You probably don't understand this though, do you?}
{401}{}{Me want Smart.}
{402}{}{Do not want! Docs is scary...}
{403}{}{Very well then. Are you irradiated or hurt? I'll help you if I can.}
{404}{}{me Hurts.}
{405}{}{hAir fall Out!}
{406}{}{Nuh-uh.}
{407}{}{Okay. You're awake. Let's see here. Do you feel any smarter?}
{408}{}{Hunh?}
{409}{}{Yes!}
{410}{}{Damn! It was a failure. Well I didn't have much to work with. Sorry, you're just an idiot and will most likely remain an idiot. We can only do the operation once, sorry to say.}
{411}{}{Fantastic, it was a success! I was able to increase your IQ to an acceptable level. How does it feel to have half a brain?}
{412}{}{It's great. Thanks, Doc. Bye.}
{413}{}{There you go. All better.}
#
# for Fallout Fixt:
#
#Bionic Man, UNUSED:
{502}{}{What other operations can you perform?}
{503}{}{Well, technically I'm not supposed to talk about this, but we do have other procedures available. I warn you that some of them are very dangerous and have a risk of side-effects, while others are quite safe, but have an extremely long recovery time. Would you like more information?}
#Poison examine
{504}{}{Ah yes, let me see here...}
#
#Sex
#
{300}{}{Cute, but I'm not interested. Come back if you need medical attention.}
{301}{}{No offense honey, but you're a little below my standards. I'm flattered though.}
{302}{}{Oh, thank you so much. (She blushes) I don't really get any compliments. Being a Brotherhood Doctor is mostly just a stressful, thankless job. I like to joke around, to keep myself entertained and upbeat.}
{303}{}{I understand. Wouldn't it help to blow off some steam once in a while?}
{304}{}{You're welcome. Bye!}
{305}{}{Well... I do get lonely sometimes, and you don't get any 'vacation time' when you're the only doctor in the Brotherhood. Oh, what am I saying though? This is so silly.}
{306}{}{You should suck it up. Take pride in your work and the rest will follow.}
{307}{}{Life's short and then you die. Don't you want to enjoy it while it lasts?}
{308}{}{It's not silly at all. (Lightly touch her face, then lean in and kiss her)}
{309}{}{Yes, I suppose you're right. (She shakes her head and sighs, then recomposes and smiles) Well, back to work! Thank you for the compliment.}
{310}{}{(She thinks for a moment) You're right. And I do. Give me about ten minutes - I need to prep the exam table. (She smiles devilishly and bites her lower lip)}
{311}{}{(She takes your hand and leads you to her room...)}
{312}{}{That was beautiful. I... I think I'm in love with you. (She giggles) Just kidding! Alright, time to go. I have work to do.}
{313}{}{Oh wow. I haven't been fucked like that in years. I think I'm going to be sore for a week, but it was worth it. (She looks at you longingly) Let's do this again soon!}
{315}{}{Definitely. See you later.}
{314}{}{Hey there, gorgeous. Looking to have some more fun?}
{316}{}{What are you do- ... (She is startled at first, but quickly melts to your embrace and kisses you back tenderly, moaning softly. As your kissing becomes more passionate, she stops and pulls away) Come with me. (She stands and leads you to her quarters...)}
{317}{}{Yes! You make me feel so beautiful and wanted.}
{318}{}{(She smiles and takes your hand...)}
{319}{}{Well, I do need some brushing up on my anatomy lessons... (She winks)}
