{100}{}{This is a poorly-repaired slot machine. It costs 10 caps to play.}
{101}{}{You drop 10 caps into the slot machine and pull the handle.}
{102}{}{DING! DING! DING!}
# TRANSLATION NOTE: The space at the end of 103 is intentional. Do not remove it.
{103}{}{You get three grenades. Excellent! }
# TRANSLATION NOTE: The space at the beginning of 104 is intentional. Do not remove it.
{104}{}{ caps drop into the tray and you snatch them up.}
{105}{}{Ding! Ding! Ding!}
{106}{}{You get three bullets. Winner! 15 caps drop into the tray and you snatch them up.}
{107}{}{Ahh shucks! You lose.}
{108}{}{You don't have enough money to play.}
