{100}{}{You see a weather-beaten farmer.}
{101}{}{Good day.}
{102}{}{Hello.}
{103}{}{Hubip.}
{104}{}{Hello again.}
{105}{}{What can I do for you?}
{106}{}{What's your name?}
{107}{}{What can you tell me about your village?}
{108}{}{What are you doing?}
{109}{}{Nothing, thanks.}
{110}{}{I am called Curtis.}
{111}{}{Our village is small, but we support ourselves. Aside from the attacks by raiders and the occasional radscorpion, we have no problems. Aradesh is a good leader.}
{112}{}{I am a farmer. We irrigated the desert many years ago. Although the wasteland is harsh, it is possible to grow things with patience and time.}
{113}{}{I see. You seem to be doing pretty well.}
{114}{}{You have all of your fields planted right now? You could probably do better with crop rotation.}
{115}{}{Crop rotation? What's that?}
{116}{}{Never mind.}
{117}{}{You only plant some of your fields, allowing the others to get back some of the nutrients that the plants used up. You let the other fields become fertile again by just tilling up whatever grows there.}
{118}{}{Huh. Never thought of that. Makes sense, though. Good idea.}
{119}{}{Can I ask you another question?}
{200}{}{ experience for helping to improve the agriculture of Shady Sands.}
