{100}{}{Hi! Welcome to my previously owned car lot. Which one of these beauties interests you today?}
{101}{}{You must be joking. These cars are all wrecks.}
{102}{}{Uh, nothing, thanks.}
{103}{}{Lug!}
{104}{}{Oh, I'm sorry, you don't look like you can afford our financing rates.}
{105}{}{But, sir, these are fine examples of motor vehicles.}
{106}{}{Ma'am, these are excellent vehicles.}
{107}{}{They can't be in working condition.}
{108}{}{Yeah, right. Okay. Bye.}
{109}{}{These cars have been given a full 100-point service by our dedicated service department.}
{110}{}{And where is your service department?}
{111}{}{You are a loon.}
{112}{}{Goodbye.}
{113}{}{Right over there, sir. (The dealer points to nothing.)}
{114}{}{Right over there, ma'am. (The dealer points to nothing.)}
{115}{}{Where? There's nothing over there.}
{116}{}{You're crazy.}
{117}{}{What do you mean? They're working on a newly purchased '56 Corvega. An excellent buy, I might add.}
{118}{}{Okay, whatever you say.}
{119}{}{You're just insane.}
{120}{}{Bye.}
{121}{}{And we have an excellent warranty. You can bring it back to us for any oil changes, as well. The first one is free. What do you say?}
{122}{}{Throw in a full tank of gas and you have a deal.}
{123}{}{You need help.}
{124}{}{I'm leaving now.}
{125}{}{I'm sorry, we don't have any petrol. Maybe next time. Goodbye.}
{126}{}{I'm insulted. I don't have to take that from a customer. Have a good day.}
{127}{}{I'm on my coffee break; come back later.}
{128}{}{Go ahead and take one for a test drive.}
{129}{}{You should get the rust preventive paint with that.}
{130}{}{Can I interest you in an auto alarm?}
{131}{}{Hi! I'm Bob.}
