{100}{}{Remove the gangs from Scrapheap.}
{101}{}{If you do not kill off all the gangs they will seek vengeance.}
{102}{}{The Crypts and Fools fight over who controls the power generator.}
{200}{}{Scout for the Fools}
{201}{}{You need to go scout out the Crypts for the Fools.}
{300}{}{Scout for the Crypts}
{301}{}{You need to go scout out the Fools for the Crypts.}
{400}{}{The Power Generator}
{401}{}{Without the generator, the peasants will lead a poorer life.}
{402}{}{The generator is the most important thing in Scrapheap. Whomever controls it controls Scrapheap.}
{403}{}{There are exposed wires which lead away from the generator.}
{500}{}{Phil's Dog Problem}
{501}{}{Phil has some problem with a dog.}
{502}{}{The dog looks hungry enough to eat Phil.}
