{100}{}{This is a strange-looking diskette of some sort. Perhaps it can be used in your Pip-Boy 2000.}
{101}{}{Pip-Boy 2000 displays: "Downloading ... Aborting, data already exists!"}
{102}{}{Pip-Boy 2000 displays: "Downloading data ... ... ... Done. Have a nice day!"}
#
# Everything below is for Fallout Fixt:
#
{103}{}{You notice the disk has a faded and worn label that reads "Delta Experiments Log".}
{104}{}{You see: Delta Experiments Disk.}
#
# Delta Experiments Disk has had its contents moved here from PIPBOY.MSG (under GAME folder)
# to help fix the Too Many Pipboy Entries bug(s).
#
# It's now displayed in dialog window, similar to Radio and SecDisk and MutDisk.
#
{105}{}{The Military has deemed it necessary for us to research further in-depth the effects of wave technology upon living organisms. We have taken light and sound as the basis of our studies. By manipulating the amplitude of the light waves and magnifying the frequency, we have been able to get lasers which will cut through a few feet of steel. Unfortunately, the power to do such a task has not been fully developed. We have other scientists looking into this.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continue]}
