{100}{}{This is a strange-looking diskette of some sort. Perhaps it can be used in your Pip-Boy 2000.}
{101}{}{Pip-Boy 2000 displays: "Downloading ... Aborting, data already exists!"}
{102}{}{Pip-Boy 2000 displays: "Downloading data ... ... ... Done. Have a nice day!"}
#
# For Fallout Fixt:
#
{103}{}{You notice the disk has a faded and worn label that reads "Alpha Experiments Log".}
{104}{}{You see: Alpha Experiments Disk.}
