# Taken from ALLDOGS.msg to make unique strings for Dogmeat.
{100}{}{You see a dog. He seems to be following you.}
{101}{}{You see a dog.}
{102}{}{Woof!}
{103}{}{Grrr!}
{110}{}{You see: Dogmeat.}

{117}{}{Woof-woof!}
{118}{}{Ruff. Ruff.}
{119}{}{Woof!}
{120}{}{Woof?}

{200}{}{I think we have to talk about our distance.}
{201}{}{Actually you're at a good distance for now.} 

# Too many party members
{2500}{}{Grrrrr.}
{2510}{}{What is that? You don't like so much company, huh?}
{2511}{}{[Done]}
