{100}{}{You see: Dragon, a member of the Blades.}
{101}{}{}
{102}{}{}
{103}{}{You see a member of the Blades.}
{104}{}{You see a member of the Blades.}
{105}{}{You think that might be Books.}
{106}{}{You think that might be Scars.}
{107}{}{You think that might be Gunner.}
{108}{}{You think that might be Twitch.}
{109}{}{You think that might be Hammer.}
{110}{}{You think that might be Razor.}
{111}{}{Get lost! Can't you see I'm trying to get some rest!}
{112}{}{What are ya doin' roamin' around out here?}
{113}{}{Just looking at the stars.}
{114}{}{Out looking for you.}
{115}{}{Hunting.}
{116}{}{Your looking's gonna cost you dearly. What's the story? Tell me the truth, and you just might live.}
{117}{}{I'm really here to kill you.}
{118}{}{I want to end the gang wars.}
{119}{}{Just looking for home. It's right there: The moon.}
{120}{}{I think I'd be sorry about that, but I don't pay heed to dead people.}
{121}{}{Fat chance. Now get out of here before I send the night guard after you.}
{122}{}{My, you don't enjoy life much. I'll help you end it then.}
{123}{}{You found me. Now walk away or die!}
{124}{}{I think I'll go.}
{125}{}{I'd really rather live.}
{126}{}{What's the word on the Rippers?}
{127}{}{They're gonna kill ya!}
{128}{}{They're dead. Deathclaws killed'em all, see?}
{129}{}{Nothing yet.}
{130}{}{Great. Go take it to Razor.}
{131}{}{Don't lie to me. Get out!}
{132}{}{Then get your butt out of here and can the bastard!}
{133}{}{Yo, homie! Nice job you did on the Regulators!}
