# Fo1in2
{100}{}{You see: Floating Eye.}

# Message log entries from investigating and using skills
{150}{}{The robot is offline.}
{151}{}{unused}
{152}{}{The built-in battery is dead and needs to be replaced.}
{153}{}{It seems the robot is tied to the Glow power system. It can't operate outside.}
{154}{}{You have no idea what is wrong with the robot.}
{155}{}{The robots motions are too frantic. You can't inspect it.}
{156}{}{It seems its sensors are defect.}
{157}{}{unused}
{158}{}{It seems the robot is tied to the Glow power system. It can't operate outside.}
# You gain x ...
{159}{}{ experience for successfully repairing the robots sensors.}
{160}{}{You fail to repair the robots sensors.}
{161}{}{You might be able to use a Small Energy or a Microfusion cell to build a replacement battery.}
# You gain x ...
{162}{}{ experience for replacing the built-in battery with a hotwired Microfusion cell.}
{163}{}{The robot might not be as effective anymore as 100 years ago, but it works.}
{164}{}{You have no idea what you are doing here and destroy the robot in the process.}
{165}{}{You failed to improvise a battery.}

# Dialog after fixing the robot
{200}{}{[Click] SYSTEM ERROR. [Beep] Unit unable to process the last active task. Task manager is not responding. Orders?}
{201}{}{Do you understand me?}

{202}{}{Voice module online. System nominal. Orders?}
{203}{}{What was your last task?}

{204}{}{Accessing task queue ... Last task: Parameter security. Task canceled after suffering severe energy fluctuations. Battery overload. Hardware components damaged.}
{205}{}{What is your status?}

{206}{}{Maintenance status: OK ... Battery status: BAD ... Connection to local network: GOOD ... Weapon systems: ONLINE.}
{207}{}{Can you follow me?}

{208}{}{New task: NEGATIVE. Task queue full. Orders?}
{209}{}{Wipe the memory.}

{210}{}{Processing. Please wait ... [Beep]}
{211}{}{System rebooting. Please wait ... [Beep]}
{212}{}{[Click] SYSTEM ONLINE ... MEMORY LOAD 39% ... All systems nominal. Orders?}
{213}{}{Follow me.}

{214}{}{Uhh ... Maybe I should just wack you a little bit?}
{215}{}{ERROR. [Beep] System rebooting. Please wait.}
{216}{}{(You beat the robot, but nothing good happens)}
{217}{}{Well, at least I tried.}

# Repair partymember dialog
{900}{}{Floating Eye can't be repaired anymore at this time.}
{901}{}{Floating Eye has been repaired some.}
{902}{}{Floating Eye is all fixed now.}

# Primary party dialog
{1000}{}{Initialize parameters. All systems online. Orders?}
{1001}{}{}
	{1014}{}{You should perform maintenance on yourself now.}
	{1015}{}{We need to talk about what you can do.}
	{1020}{}{Let's talk about our formation.}
	{1030}{}{Okay, thanks.}
	{1040}{}{Follow me, I need your help again.}
	{1050}{}{[Done]}
	{1060}{}{Nevermind.}

{1004}{}{Processing orders ...}
{1005}{}{Calibrating new parameters.}
{1006}{}{Calibrating ...}

{1007}{}{Tasks?}
{1008}{}{Tasks?}
{1009}{}{Confirmed.}
{1010}{}{[Click] This unit is programmed to follow an automated parameter and / or VIP security protocoll. This unit also has a built-in long range scanner system for early threat recognition.}
{1011}{}{[Beep] This unit is equipped with an improved Wattz 2.4 taser-system for fast melee engagements.}

{1100}{}{This eyebot is fully repaired and ready to go.}
{1200}{}{Maintenance status: Good. No repairs necessary.}
{1300}{}{Maintenance status: Damaged. Suggesting additional repairs in the near future.}
{1400}{}{Maintenance status: Bad. Suggesting additional repairs in the near future.}
{1401}{}{Battery status: OK.}
{1402}{}{Battery status: GOOD.}

{1500}{}{We better stay together.}
{1501}{}{Confirmed. Standby.}
{1600}{}{Confirmed.}
{1700}{}{Close range formation mode confirmed.}
{1800}{}{Medium range formation mode confirmed.}
{1900}{}{Long range formation mode confirmed.}

# Too many party members
{2000}{}{Task failed to process. ERROR: Sensory overload. due to exceeding group size. Remaining standby.}
{2001}{}{Task confirmed. Cancel standby.}
{2002}{}{Loading ... Recursive task created ... Terminating input.}
	{2010}{}{Oh yeah, whatever then.}

{3500}{}{Maintenance status: Damaged. Additional repairs required.}
