{100}{}{You see the bartender.}
{101}{}{Yeah, whadda ya' want?}
{102}{}{Water.}
{103}{}{Beer.}
{104}{}{Liquor.}
{105}{}{Whatever will get me smashed the quickest.}
{106}{}{Nothing.}
{107}{}{Tuh?}
{108}{}{If ya' don't have the caps, get the hell out!}
{109}{}{Suit yerself.}
{110}{}{I think you've had enough, buddy.}
{111}{}{I think you've had enough, lady.}
{112}{}{Yeah... well beat it.}
{113}{}{That'll be two caps.}
{114}{}{Okay.}
{115}{}{No, thanks.}
{116}{}{That'll be five caps.}
{117}{}{Sure.}
{118}{}{That'll be ten caps.}
{119}{}{Hmmm, for one of your size...}
{120}{}{ }
{121}{}{ ten}
{122}{}{ twenty}
{123}{}{ thirty}
{124}{}{ forty}
{125}{}{ fifty}
{126}{}{ sixty}
{127}{}{ seventy}
{128}{}{ eighty}
{129}{}{ ninety}
{130}{}{ one hundred}
{131}{}{ caps ought to do it.}
{132}{}{Great! That'll be }
{133}{}{ caps again.}
{134}{}{Keep them comin'.}
{135}{}{Never mind.}
{136}{}{Here. (The bartender slides you a dirty tin cup full of some}
{137}{}{ murky water. After drinking the water, you have a strange}
{138}{}{ taste in your mouth.)}
{139}{}{Here. (The bartender slides you another cup full of the same}
{140}{}{ murky water, and after you drink it, you're reminded as to}
{141}{}{ how strange it tasted the last time...)}
{142}{}{This should be amusing... (The bartender keeps them coming and}
{143}{}{ you lose count. After a while you hear a muffled thump, then}
{144}{}{ you realize you're lying on the floor, face down...)}
{145}{}{Here we go again... (The bartender lines them up while everyone}
{146}{}{ around the bar chants...)}
{147}{}{ ...}
{148}{}{ ...}
{149}{}{ ...}
{150}{}{ (Soon everything begins to fade...)}
{151}{}{Didn't think you looked like someone that could hold their}
{152}{}{ liquor.}
{153}{}{That's a shame. We were all looking forward to seeing you}
{154}{}{ 'perform' again.}
{155}{}{Aww... you're not going to show us your 'stuff' again? Well}
{156}{}{ okay, here's your beer. Anything else?}
{157}{}{Are you sure you can resist the temptation? You were quite an}
{158}{}{ act the last time. Well, here you are. (The bartender hands}
{159}{}{ you a liquor bottle.) Anything else?}
{160}{}{Here you are. (The bartender hands you a beer bottle.) Anything}
{161}{}{ else?}
{162}{}{Get me smashed again!}
{163}{}{Here you are. (The bartender hands you a liquor bottle.)}
{164}{}{ Anything else?}
{165}{}{You have a very bad taste in your mouth.}
{166}{}{You think your head is about to explode.}
##
##
##
{167}{}{You see a Craps dealer.}
{168}{}{You see a Roulette dealer.}
{169}{}{You see a slot machine.}
{170}{}{You notice that the odds don't seem quite right.}
{171}{}{You think the dice are loaded.}
{172}{}{You think the table is rigged.}
{173}{}{Place your bets. }
{174}{}{5 caps.}
{175}{}{15 caps.}
{176}{}{25 caps.}
{177}{}{50 caps.}
{178}{}{No thanks.}
{179}{}{Rurh.}
##
## SLOT MACHINES
##
{180}{}{Sorry, but you're in no shape to place any bets. (You look at}
{181}{}{ the game and are thoroughly confused.)}
{182}{}{Sorry, better luck next time.}
{183}{}{Winner! You win back your bet.}
{184}{}{Ding Ding Ding! You win double your bet.}
{185}{}{JACKPOT! You win triple your bet!}
{186}{}{You've got to have the money to play, pal.}
{187}{}{You've got to have the money to play, lady.}
{188}{}{You notice that the odds seem about right.}
{189}{}{How much money do you put in?}
{190}{}{1 cap.}
{191}{}{2 caps.}
{192}{}{3 caps.}
{193}{}{4 caps.}
{194}{}{5 caps.}
{195}{}{Nothing.}
{196}{}{You don't know what to do with it, but it sure looks pretty.}
{197}{}{You lost.}
{198}{}{You win back your bet.}
{199}{}{You win double your money.}
{200}{}{You win triple your money!}
{201}{}{You don't have enough money.}
{202}{}{You currently have }
{203}{}{ caps. How many would you like to bet?}
{204}{}{ Do you want to play again?}
##
## Sduibek, Fallout Fixt
##
{205}{}{You lose all your money on the first spin, but win back }
{206}{}{ caps in the Radioactive Round!}
{207}{}{Winner! You win back your bet, and win }
{208}{}{Ding Ding Ding! You win double your bet, and also get }
{209}{}{JACKPOT! You win triple your bet, and also get }
{210}{}{ caps in the Radioactive Round!}
{211}{}{ cap in the Radioactive Round.}
{212}{}{ cap in the Radioactive Round.}
