{100}{}{You see a merchant from the Far Go Traders' caravan train.}
{101}{}{You see a merchant from the Crimson Caravans' caravan train.}
{102}{}{You see a merchant from the Water Merchants' caravan train.}
{103}{}{Did you want to return to the Hub? I'll pay you another 400 caps.}
{104}{}{Did you want to return to the Hub? I'll pay you another 600 caps.}
{105}{}{Did you want to return to the Hub? I'll pay you another 200 caps.}
{106}{}{Yes.}
{107}{}{No.}
{108}{}{Ug.}
