{100}{}{Watch yourself around the Doc, and I won't have to get medieval on your face.}
{101}{}{We're closed. Come back later.}
{102}{}{I gotta see the Doc.}
{103}{}{Okay, will do.}
{104}{}{It is very important that I see the doctor.}
{105}{}{Hnnn.}
{106}{}{Nice weather we're having, huh?}
{107}{}{That's just too bad. Get out of here, and don't come back until morning. This office isn't open at night.}
{108}{}{Hold on a second, I gotta check with the Doc.}
{109}{}{What do you want now?}
{110}{}{I gotta see the Doc.}
{111}{}{Is the doctor available?}
{112}{}{Hnnn!}
{113}{}{No way. The Doc is sleeping. Come back later.}
{114}{}{I dunno, why don't you talk to him yourself.}
{115}{}{Yeah, okay. Get out.}
{116}{}{Hey, this is private property. You'd better be leaving, now.}
{117}{}{Eat my dung.}
{118}{}{If you don't get out of my way, you'll be needing the doctor for personal reasons.}
{119}{}{Don't you know that women are the weaker sex?}
{120}{}{Think I'm weak? Watch this then...}
{121}{}{I'll just be leaving.}
{122}{}{Take your puny threats and run home to mamma. You're talking to a real man here.}
{123}{}{Think I'm weak? Watch this then...}
{124}{}{I'll just be leaving.}
{125}{}{Whoa! If you really want to see him, go right ahead.}
{126}{}{Well, when is the doctor here?}
{127}{}{The doc sees patients from 8 to 5. Now get outta here.}
{128}{}{When is the doctor here?}
{129}{}{I told you not to come back.}
