{100}{}{You see: Lou, of the Nightkin.}
{101}{}{You see: Sue, of the Nightkin.}
{102}{}{You see: Drew, of the Nightkin.}
{103}{}{You see: Kurt, of the Nightkin.}
{104}{}{You see: Bert, of the Nightkin.}
{105}{}{You see: Tyche, of the Nightkin.}
{106}{}{You see: Mike, of the Nightkin.}
{107}{}{You see: Char, of the Nightkin.}
{108}{}{You see: Reine, of the Nightkin.}
{109}{}{You see: Daggarth, of the Nightkin.}
{110}{}{Me was told to take you to do something. Something about normies. Me no remember what.}
{111}{}{Me think normies is stupid.}
{112}{}{All normies should die!}
{113}{}{Uthern a smart one. Uh huh.}
{114}{}{Boss say normies are nothings.}
{115}{}{Don't know why boss want these books.}
{116}{}{Me glad those stupid normies ain't around. They ugly.}
{117}{}{Me is better than you! Me is better than you!}
{118}{}{Me squish you now!}
{119}{}{Me squish you now!}## don't think it's needed but leaving here --Sduibek
