{100}{}{Towering before you is Garl, leader of the Khans.}
{101}{}{You think you can come here without challenge? This, the home of your deadliest enemies? We will see you dead. I will personally tear your heart out of your chest and eat it before my proud warriors!}
{102}{}{I killed you!}
{103}{}{I don't get it.}
{104}{}{Yes, you did. I've come back to haunt you.}
{105}{}{You should not have done that.}
{106}{}{I killed you!}
{107}{}{I don't get it.}
{108}{}{Yes, you did. I've come back to haunt you.}
{109}{}{You should not have done that.}
{110}{}{You would if you were my father, but you are not. You look like he did, but act different. No image of him remains to this day. You will just have to be removed.}
{111}{}{I don't believe it! I can't believe it!}
{112}{}{Believe this, buddy, and you're about to join me in hell!}
{113}{}{Don't tell me what I should have done, father. I rule the Khans now, and you are but worm meat.}
{114}{}{I still live.}
{115}{}{I should have killed you when you were a child.}
{116}{}{Don't tell me what I should have done, father. I rule the Khans now, and you are but worm meat.}
{117}{}{I still live.}
{118}{}{I should have killed you when you were a child.}
{119}{}{You should have. Now it's too late. I am Garl Death-Hand. I rule the Khans. You should be dead in your grave, and you will be again!}
{120}{}{I can see you standing before me, but I don't believe it. What do you want?}
{121}{}{I want the girl set free. Now.}
{122}{}{I want you to step down.}
{123}{}{I want riches to buy my way into Heaven.}
{124}{}{Pledge that you shall return to the grave, and it shall be so.}
{125}{}{I swear that I will leave.}
{126}{}{So be it. Release the Shady Sands woman and escort this one out of here...}
{127}{}{You don't rule here. You don't belong here. Death to the walking dead!}
{128}{}{Never!}
{129}{}{That's what I like: initiative. But you should not have killed them without my orders. I don't like too much initiative.}
{130}{}{What do you want?}
{131}{}{I want you to set the girl free.}
{132}{}{I want you to die.}
{133}{}{I've come in peace to negotiate the release of Tandi.}
{134}{}{Hngh!}
{135}{}{What makes you think I have her?}
{136}{}{I know you do. I followed you here.}
{137}{}{One of your followers told me.}
{138}{}{I know.}
{139}{}{I hate it when they do that. I will have to make that loudmouth pay for his crimes. After I finish up with you.}
{140}{}{Hmmm. Well then. What do you offer for her release?}
{141}{}{I represent a threat you don't even understand. Do you really want to risk our wrath?}
{142}{}{I will give you something of equal value.}
{143}{}{It would be good for your eternal soul.}
{144}{}{Your blood, spilled on the ground.}
{145}{}{Hmmm. For some reason, I believe you. You may take the girl, but do not return unless you seek our wrath.}
{146}{}{Ha! You should not threaten your betters.}
{147}{}{It must be valuable indeed. Show me.}
{148}{}{It pleases me. You may take the girl, but do not return.}
{149}{}{Your bribe is not worth my time. Kill him.}
{150}{}{You think a man, such as I, believes in the afterlife? This world is dying, and I shall take what I want! You will never realize the strength required to make such a decision!}
{151}{}{What do you want now?}
{152}{}{Nothing.}
{153}{}{I want the girl.}
{154}{}{Lorrk.}
{155}{}{Then you disturb me. Leave.}
{156}{}{You are barely tolerated by us. Why should we give one of our most prized possessions to you?}
{157}{}{It is only right.}
{158}{}{I have something of equal value.}
{159}{}{You will be allowed to live.}
{160}{}{Right?! I determine what is right around here. You are treading on dangerous ground.}
{161}{}{I'm sorry.}
{162}{}{Why should I care? I'm taking the girl.}
{163}{}{Yes, indeed you are. I don't tolerate frightened curs that have no backbone. And what we don't tolerate, we destroy. Kill him.}
{164}{}{Would you be willing to fight me over her?}
{165}{}{No, I'm a lover, not a fighter.}
{166}{}{Of course. Right now, just you and me.}
{167}{}{I'll take you and your whole gang on.}
{168}{}{Fine. We shall settle this with no weapons, but you can keep any armor you're wearing. Knock me out, and I'll let you take the woman and leave. I knock you out, you leave without her.}
{169}{}{Sounds good, let's go.}
{170}{}{This will be interesting, but not very sporting. Very well, let's do it.}
{171}{}{Okay.}
{172}{}{Hmm, you fight better than I expected. I haven't had a good beating since my father slapped me around the room. You deserve the Shady Sands woman. Take her and leave. Don't come back.}
{173}{}{Take your miserable hide and leave. If you ever return, I will not be so gentle.}
{174}{}{What do you want?}
{175}{}{I'm an explorer.}
{176}{}{I want to join.}
{177}{}{We don't like those kinds of people. We can't have that here. Kill him.}
{178}{}{You? Want to join us? Whatever for?}
{179}{}{To kick some serious ass.}
{180}{}{I like you guys. I want to bond with you.}
{181}{}{The Khans only accept the meanest and toughest SOBs around. You have to be bloodthirsty, violent, extreme. I don't think you can handle that. Can you?}
{182}{}{Yes.}
{183}{}{No.}
{184}{}{Then you had better leave. Do not return.}
{185}{}{I grow tired of these women. Kill them.}
{186}{}{No!}
{187}{}{Okay.}
{188}{}{You have proved my point. Only the Khans possess the will to survive! You do not. Kill him.}
{189}{}{You have proved my point. Only the Khans possess the will to survive! You do not. Kill her.}
{190}{}{Scum! You will pay for that!}
{191}{}{Ha! I like your style. A little sloppy, but it works. Consider yourself a friend of the Khans. Leave my sight now.}
{192}{}{What do you want now?}
{193}{}{Nothing.}
{194}{}{I want some weapons and armor.}
{195}{}{Grawp.}
{196}{}{You must fend for yourself.}
{197}{}{How dare you return to my sight? Kill him!}
{198}{}{How dare you return to my sight? Kill her!}
{200}{}{I came to party with you guys!}
{201}{}{Well, go get some more booze and women for our party then.}
{203}{}{I'll fight you one-on-one for Tandi.}
{204}{}{You're no Khan, you deserve no honor.}
{205}{}{Your bribe is not worth my time. Kill her.}
{206}{}{We don't like those kinds of people. We can't have that here. Kill her.}
{207}{}{Waaaug!}
{208}{}{Okay, you win. Take the girl and get out of here.}
{209}{}{Let the fight of honor begin!}

# Tell Me About generic responses
{980}{}{What do you want?}
{981}{}{I won't answer to you.}
{982}{}{You better piss off and get away from here.}

{1000}{}{Khans|KHANS|KHAN|RAIDER|RAIDERS|GREAT KHANS}
{1001}{}{Garl|GARL}
{1002}{}{Junktown|JUNKTOWN|JUNK TOWN}
{1003}{}{Shady Sands|SHADY SANDS|SHADY|SANDS}
{1004}{}{The Hub|HUB|THE HUB}
{1005}{}{Water}
{1006}{}{Tandi|TANDI}
{1007}{}{Chip|Water Chip|Waterchip}
{1008}{}{HELP|HURT|WOUNDED|INJURED|DOC|DOCTOR}
{1009}{}{JOIN|BECOME KHAN}

{1100}{}{That's us, you lackey.}
{1101}{}{I am the leader of the Khans. I am the most feared man in the wasteland.}
{1102}{}{They are to the southwest. We sometimes go there to relax after a hard day of pillaging.}
{1103}{}{Miserable little piss-ant community. I could crush them.}
{1104}{}{They are to the south. We trade with them. Mostly for water and ammo, but sometimes for weapons.}
{1105}{}{Why should I care?}
{1106}{}{I don't know anyone by that name.}
{1107}{}{A what?}
{1108}{}{Go and cry somewhere else.}
{1109}{}{YOU joining the Great Khans? Don't make me laugh!}
