{100}{}{You see: Garret.}
{101}{}{You shouldn't be here during the day; it makes Set unhappy. Come back at night.}
{102}{}{Oh, okay.}
{103}{}{He should learn to deal with his problems.}
{104}{}{That's not important. What is important is that I speak with him.}
{105}{}{You should talk to Set.}
{106}{}{You receive: a shotgun, 10 shotgun shells, 4 flares, 4 bottles of Nuka-Cola, and 200 caps.}
{107}{}{You receive: a shotgun, 10 shotgun shells and 100 caps.}
{108}{}{You receive: 4 flares, 4 bottles of Nuka-Cola, and 50 caps.}
{109}{}{You had better leave now.}
{110}{}{See you around.}
{111}{}{Is this all I get? I deserve more, and you'd better give it to me!}
{112}{}{Yerg.}
{113}{}{You need to leave here... immediately.}
{114}{}{Follow me. I'll see to your reward.}
{115}{}{I hope not, for your sake. Set was not too happy to have to use you. It might be a good idea to leave Necropolis... soon.}
{116}{}{I told you to leave.}
{117}{}{Whatever.}
{118}{}{Perhaps. Hmm. Here, take this as well.}
{119}{}{You receive 100 caps.}
{120}{}{Now leave.}
{121}{}{Hmm. Some things are missing from the fridge. It seems that we have been robbed.}
{200}{}{Garret ignores you.}
{201}{}{Here is your reward.}
{202}{}{You receive a large reward.}
{203}{}{You receive: }
{204}{}{a shotgun}
{205}{}{some shotgun shells}
{206}{}{some flares}
{207}{}{a flare}
{208}{}{a few bottles of Nuka-Cola}
{209}{}{a bottle of Nuka-Cola}
{210}{}{ caps}
