{100}{}{You see a police officer of the Hub.}
{101}{}{I wish I was stationed closer to my home.}
{102}{}{I wonder what happened to those caravans.}
{103}{}{Move along.}
{104}{}{You'd better keep your weapons holstered, stranger.}
{105}{}{Keep your nose clean.}
{106}{}{Do you have any commodities to declare?}
{107}{}{Don't be waving your weapon in my face.}
{108}{}{Put that away unless you want some jail time.}
{109}{}{Are you aiming that at me?}
{110}{}{I've heard of you. Watch it.}
{111}{}{We'll be keeping an eye on you.}
{112}{}{No fighting in our town, tough guy.}
{113}{}{We don't like baby-killers!}
{114}{}{Lay a hand on a kid and we'll hunt you down.}
{115}{}{I hate people like you.}
{116}{}{Don't call for help if you're in trouble.}
{117}{}{Hey, thanks for doing our work for us.}
{118}{}{We don't allow kill'n here, even if it is justified.}
{119}{}{I hear you're the one that killed the Deathclaw... thank you.}
{120}{}{Keep your nose clean while you're in our city.}
{121}{}{I would keep clear of Decker if I were you.}
{122}{}{Enjoy your stay.}
{123}{}{Welcome to the Hub!}
{124}{}{Greetings, stranger.}
{125}{}{Visit the Maltese Falcon for refreshing drinks.}
{126}{}{Follow the main road if you're looking for the market.}
{127}{}{Keep moving.}
{128}{}{Move along. Move along.}
{129}{}{We're here to Prevent and Survey.}
{130}{}{Keep that weapon under control while you're in our city.}
{131}{}{Don't you get into any fights with that.}
{132}{}{I'd recommend putting your weapon away.}
{133}{}{You should put that away... your weapon, that is.}
{134}{}{Welcome Paladin, it's been a while.}
{135}{}{You're that rowdy one. No more fighting, okay?}
{136}{}{You better not start another fight!}
{137}{}{It's you... keep that temper of yours under control.}
{138}{}{The Far Go Traders got wiped out. I can't believe it.}
{139}{}{The Water Merchants are gone. What a relief.}
{140}{}{The Crimson Caravan has been destroyed.}
{141}{}{Did you hear? The Underground has finally been wiped out!}
{142}{}{Decker's dead!}
{143}{}{The Decker problem has finally been solved.}
{144}{}{Watch your back; this isn't a safe place.}
{145}{}{Watch your scripts, guy.}
{146}{}{Watch your scripts, lady.}
{147}{}{Old Harold's good for telling tales.}
{148}{}{You shouldn't be here, it's not safe.}
{149}{}{Old Town's really fallen apart.}
{150}{}{This place smells.}
{151}{}{We should tear this whole area down.}
{152}{}{I know that damn Thieves' Circle is around here somewhere.}
{153}{}{Poor Harold - he's had a rough life.}
{154}{}{Keep your nose clean.}
{155}{}{Hey. I know you. No more fighting, okay?}
{156}{}{You'd better not be thinking of starting another fight!}
{157}{}{If we catch you fighting again, you're going in!}
{158}{}{Did you hear? The Far Go Traders got wiped out.}
{159}{}{The Water Merchants are history. That's a blessing.}
{160}{}{Someone killed off the Crimson Caravan.}
{161}{}{Did you hear? The Underground has finally been wiped out!}
{162}{}{Decker's dead!}
{163}{}{This town will be safer with Decker out of the picture.}
