{100}{}{You see a chanter from the Children.}
{101}{}{The Master will forgive your sins! Join us and be free! Praise to the Master and his mercy!}
{102}{}{Hello friend! Will you sing a song of praise with me? ...Once I was wandering blind, In a land that was so unkind...}
{103}{}{I hate to interrupt your hymn, but where might I meet the Master?}
{104}{}{Don't quit your day job.}
{105}{}{Who's in charge here?}
{106}{}{...but now I kiss the Master's behind...}
{107}{}{Happy! Happy! I sing song good!}
{108}{}{He finds you when and where you least expect it! Praise the Master! Praise the Holy Flame! Praise the world!}
{109}{}{What a wonderful joke! I used to have no sense of humor, but thanks to the Master, I am full of mirth! Praise the Master!}
{110}{}{The one who sits above. The one who sits below. The one who rests within. Praise the Master for such clarity of vision!}
{111}{}{Oh, if only I were so fortunate! Perhaps one day the Master will let me kiss his body parts. Praise the Master! Praise the Holy Flame!}
{112}{}{Hmm, that's not what I had in mind. You had better practice, my friend. Praise to the Master! Praise the Holy Flame!}
{113}{}{[Done]}
