{100}{}{You see a Knight.}
{101}{}{I wonder what the old turbine engines were really like.}
{102}{}{It would be great if we had a working automobile.}
{103}{}{Did you know man has been on the moon? Or I think that's what they said.}
{104}{}{I can't find the file I need.}
{105}{}{I'll be a Paladin someday.}
{106}{}{Talus is a skilled warrior. I would never want to have to go up against him.}
{107}{}{Thomas is the best fighter in the Brotherhood. I bet he could best Rhombus.}
{108}{}{I'd like to get my hands on those raiders. Show them what thieves deserve.}
{109}{}{That's it... what? Oh sorry. I can't talk right now.}
{110}{}{I wonder... huh? Oh, you made me lose my train of thought.}
{111}{}{I love working on new prototypes.}
{112}{}{When our supplies are limited, it can really be a challenge to find a way to use what we've got.}
{113}{}{I can't figure out why my last prototype didn't work.}
{114}{}{Sorry, can't talk right now.}
{115}{}{Vree's over there.}
{116}{}{Now where did I put that file...}
{117}{}{Where's that schematic?}
{118}{}{Well the computer says it should work; now what did I do wrong?}
