{100}{}{Stop!}
{101}{}{Die, human!}
{102}{}{To the death.}
{103}{}{You will pay for your sins!}
{104}{}{You are not supposed to be armed in this area, little brother. Explain yourself.}
{105}{}{You are not supposed to be armed in this area, little sister. Explain yourself.}
{106}{}{Hngg.}
{107}{}{It's okay, I work here.}
{108}{}{It's okay, I have a pass.}
{109}{}{I am armed by permission of the Lieutenant.}
{110}{}{What manner of treason is this?!}
{111}{}{Then show me your pass.}
{112}{}{I, uh, left it in my other robe.}
{113}{}{It's right here, stapled to the front of my gun.}
{114}{}{Hurry on your task then, but be warned: I'm watching you.}
{115}{}{Yes, little brother. What is it that you need from me?}
{116}{}{Yes, little sister. What is it that you need from me?}
{117}{}{Hng!}
{118}{}{Hmm, where's this Master guy?}
{119}{}{Praise to the Unity, brother.}
{120}{}{I am sorry, but you will have to find the way to Unity yourself.}
{121}{}{You are obviously a heathen! Pay for your sins!}
{122}{}{He resides on Level 3, as he must. Why do you ask such a silly question?}
{123}{}{Oh, uh, no reason.}
{124}{}{I am going to kick his ass from here to, uh, someplace really far away!}
{125}{}{What question? I said 'Hail to the Master, goodbye.'}
{126}{}{You insult me! Die!}
{127}{}{Praise to the Unity.}
{128}{}{You sound like you do not believe what you say. Could this be true? Or have you left the path of righteousness?}
{129}{}{You mistake the tremor in my voice for fear when it is actually a cold of some sort.}
{130}{}{I think your kind is doomed, actually. Here, let me prove it with some help from my friends...}
{131}{}{When you become one of us, you will not fear such minor things. Begone.}
{132}{}{What do you want this time? I have little time for your talk.}
{133}{}{Labbo!}
{134}{}{I have little time for your life... Die!}
{135}{}{Nothing, sorry.}
{136}{}{Praise to the Unity, brother.}
{137}{}{Just who are you? Let me see... Argh! An intruder...}
{138}{}{Move along. Do your part for the Unity and stop bothering me!}
{139}{}{Get going.}
{140}{}{Move along. Do your part for the Unity.}
