{100}{}{You see: Gideon, a normal-looking human. He is wearing a crown.}
{101}{}{Jason is a living god! Only the nullified may pass!}
{102}{}{Nullified? Are they somehow restricting your psychic powers by those devices you are wearing?}
{103}{}{Who's Jason?}
{104}{}{What do you mean by nullified?}
{105}{}{I just killed him, so he must be a dead god, now. Would you like to join him?}
{106}{}{Huh?}
{107}{}{The walls also have minds... I saw you... tomorrow?}
{108}{}{Others like you are in the wall?}
{109}{}{Never mind.}
{110}{}{I'd like to kill you now. Could you open this force field?}
{111}{}{Open the force field and I'll let you out.}
{112}{}{Uh, yeah. Are you the 'experiments' I'm looking for?}
{113}{}{Jason? Who's Jason?}
{114}{}{You just said... never mind.}
{115}{}{Stup.}
{116}{}{Yes, the walls are alive with those that have gone before.}
{117}{}{What happened to them?}
{118}{}{Uh, I've got to go.}
{119}{}{Meeting of the soul... melded with, to protect, the Master of all.}
{120}{}{I see. How do I protect myself from the protectors of the Master?}
{121}{}{What about the dogs of war?}
{122}{}{I need to protect the Master. How do I get to him?}
{123}{}{I can kill anyone or anything. Open this force field and I'll demonstrate.}
{124}{}{Goodbye.}
{125}{}{There is only peace and joining... the price... the pain... one must be blind... nulled.}
{126}{}{Well, I need to join. Where can I pick up one of those snazzy nullifiers?}
{127}{}{Great! How do I join?}
{128}{}{I'd like to join my gun with your head!}
{129}{}{I don't have time for this. Goodbye.}
{130}{}{I will anoint you... I must give what I must not.}
{131}{}{Thanks.}
{132}{}{No one's anointing me, you insane bastard!}
{133}{}{Anoint? Anoint me with what?}
{134}{}{No, thanks.}
{135}{}{You cannot kill the genius of... the all... you... hehf!}
{136}{}{Yeah, but I can cause it one hell of a lot of pain.}
{137}{}{I don't want to kill. I want to worship.}
{138}{}{Obviously. Goodbye.}
{139}{}{Phlegm! Insubstantial development... communication, null... end of death.}
{140}{}{The walls also have minds... I saw you... tomorrow was it?}
{141}{}{I'll take that as a yes.}
{142}{}{Great! How do I join?}
{143}{}{The blasphemous... decompose... death will be... salvation... strong!}
{144}{}{The minds... the walls... before the great one.}
{145}{}{Those who have gone before... must stop your journey.}
{146}{}{I need to change that.}
{147}{}{I must complete my journey; the Master wills it.}
{148}{}{Who? Did what?}
{149}{}{Yeah, but I can cause them a whole lot of pain.}
{150}{}{Sorry to disturb you again. Goodbye.}
{151}{}{I'd like to help you escape.}
{200}{}{You see: Moore, a scruffy-looking fellow. He is wearing a crown.}
{201}{}{You see a scruffy-looking fellow.}
{202}{}{The asphalt shall run red! I will crush!}
{203}{}{Exactly.}
{204}{}{What are you talking about?}
{205}{}{Yeah, it'll be red with your blood.}
{206}{}{Uh, yeah. Goodbye.}
{207}{}{Urgh!}
{208}{}{I will stop the motor! The Master gave me the power...}
{209}{}{Okay, Hank. I'd like to meet the Master, how do I get there?}
{210}{}{What motor?}
{211}{}{Of course! I understand completely...}
{212}{}{I'd like to split your head open, you blithering idiot.}
{213}{}{Oh, not you again. Goodbye.}
{214}{}{Only the powerful can pass, but they will be kept from passing.}
{215}{}{Open this force field, I want to show you my power.}
{216}{}{But I have to see the Master!}
{217}{}{Can you show me how?}
{218}{}{Gideon... Gideon speaks the way.}
{219}{}{Exactly.}
{300}{}{You see: Lucy, a normal-looking human female. She is wearing a crown.}
{301}{}{You see a human female. She is staring at your shoes.}
{302}{}{There is no place like home, no place like home, no place like home... [pacing back and forth]}
{303}{}{Hng!}
{304}{}{Stop that!}
{305}{}{What about this place? Isn't this your home?}
{306}{}{I agree. Completely and utterly. You're right... [she pauses for a moment.] What did you say? Oh, never you mind.}
{307}{}{(She looks at you intensely.) I will slay you for that! I will make your blood run red. Wait a minute. Blood is red, how can I make it run red? I can't very well do that. Hmmm. I need to think about this. Go away!}
{308}{}{My home is, uh, yeah. Here. Yeah, it's here. This is my home! [she jumps up and down] I am so happy! You can't believe how happy this makes me. I think I'm going to go punch the wall for a while.}
{309}{}{I'm busy. I almost have the solution to the environmental problems fucking this world over, but I can't stop thinking about purple dinosaurs. Is this a problem?}
{310}{}{Stop bugging me, I'm thinking...}
{400}{}{You see: Wiggum, a complete loser. He is wearing a crown.}
{401}{}{You see what looks to be a complete loser.}
{402}{}{I'm tired.}
{403}{}{My life is Hell.}
{404}{}{I'm tired of living.}
{405}{}{Darkness comes.}
{406}{}{Whatever.}
{500}{}{A sign on the wall reads: 'Warning! Do Not Disturb!'}
{501}{}{You earn }
{502}{}{ experience for convincing the psyker to give you a Nullifier.}
