{100}{}{You see a power generator. This must be what supplies electricity to the doors, elevators and lights in this complex.}
{101}{}{The generator is on.}
{102}{}{These generator seems to be offline. You wonder if you can start it back up.}
{103}{}{The generator is already on.}
{104}{}{You start up the generator, and all systems seem to be coming back online.}
{105}{}{You fail to start up the generator.}
{106}{}{You lack the knowledge to repair this system.}
###Reaching LVL5 exp msg, by Sduibek, for Fallout Fixt
{107}{}{You hear a constant mechanical humming on this level, which reminds you of something that you can't quite put your finger on...}
