{100}{}{You see: Guido.}
{101}{}{I say you just use brute force. It don't take that much to bust a knee cap.}
{102}{}{Who cares about shock value? We ain't artists, we're professionals. Uh, Leone, someone's trying to talk to us. Aren't we supposed to kill them if they do that?}
{103}{}{I say you just use brute force. It don't take that much to bust a knee cap.}
{104}{}{I ain't paid to talk.}
{105}{}{Who cares about shock value? We ain't artists, we're professionals. Uh, Leone, someone's trying to talk to us. Aren't we supposed to kill them if they do that?}
{106}{}{I say you just use brute force. It don't take that much to bust a knee cap.}
{107}{}{Who cares about shock value? We ain't artists, we're professionals. Uh, Leone, someone's trying to talk to us. Aren't we supposed to kill them if they do that?}
