{100}{}{You see: Gunther.}
{101}{}{You see a stern man in his thirties.}
{102}{}{Welcome to my humble house. What can I do for you?}
{103}{}{Could you tell me a little about the Hub?}
{104}{}{Where can I find some ammo and weapons around here?}
{105}{}{What do you do around here?}
{106}{}{Who's the law around here?}
{107}{}{Sure, what else would you like to know?}
{108}{}{It is a sprawling city, the largest I have seen in my life. The center of the town lies to the south, with the other areas branching off in each direction from there.}
{109}{}{Where can I find supplies?}
{110}{}{If I was looking for a job, where would be a good place to start?}
{111}{}{Can I ask you another question?}
{112}{}{Thanks for the info. Goodbye.}
{113}{}{I get everything that I need from Mitch down by the Maltese Falcon. Just head on south from here.}
{114}{}{I occasionally do a stint on one of the caravans that head out from here. If you're looking for that kind of work, just talk to one of the trading houses. I'm partial to the Far Go Traders, but I've worked with all of them.}
{115}{}{Well, I buy most of my stuff from Beth over in the Weapon Store. Got a pretty good selection.}
{116}{}{What would I do if I was looking for something a little more 'exotic'.}
{117}{}{Will mentioning your name help with the price?}
{118}{}{I've heard there is some guy over in Old Town that deals in stuff with a little more punch.}
{119}{}{Probably not, she's sweet on her bodyguard Sid. But, you might want to try Butch, he runs the Far Go Traders - which owns her store.}
{120}{}{I get by. I hire on with the caravans when I'm a little short on cash, and work for the farmers down south a bit.}
{121}{}{Well, you probably passed Deputy Fry on your way down here. His boss is Sheriff Greene, and you'll find him in the Police Station most of the time.}
{122}{}{Coookkiieee!}
{123}{}{I'm sorry, but you're not making any sense. Maybe Dr. Thorndyke with the Children can help you.}
