{100}{}{Sorry, no boxing today.}
{101}{}{Hnn.}
{102}{}{Uk, okay.}
{103}{}{When's the next match?}
{104}{}{You might try signing up with Gizmo. I hear he's always looking for new meat to toss in the ring.}
{105}{}{Try again tomorrow. Saul will be boxing then.}
{106}{}{You just missed it. Try again in a couple of days. Saul boxes every three days.}
{107}{}{Thanks.}
{108}{}{Who's Saul?}
{109}{}{Saul is the local champion. Saul is the current favorite of Gizmo.}
{110}{}{Hey, there. No boxing today.}
{111}{}{ Try again tomorrow.}
{112}{}{ Try again the day after tomorrow.}
{113}{}{So! Want to lay a bet on the fight?}
{114}{}{I've got better things to do with my money. Goodbye.}
{115}{}{What are the odds?}
{116}{}{No, thanks. Mind if I ask a few questions, though?}
{117}{}{}
{118}{}{Sorry, but today's match is already over.}
{119}{}{Oh. Well, never mind, then.}
{120}{}{Who do you want to bet on, Saul or the challenger? Odds favor Saul winning. Cost is 25 caps to bet; you get 50 if you win betting on Saul, 100 if you win betting on the challenger!}
{121}{}{I'll bet on Saul.}
{122}{}{I'll bet on the challenger.}
{123}{}{All right, I guess.}
{124}{}{Who's the boxer?}
{125}{}{Who runs these matches?}
{126}{}{Uh, never mind.}
{127}{}{Sorry, I don't have the time. Maybe later.}
{128}{}{Saul, the fastest fist in Junktown! He's a marvel of manly musculature! A pulsating power puncher!}
{129}{}{He's a nice guy, too.}
{130}{}{Um, yeah. So, who runs these matches?}
{131}{}{Thanks. See you around.}
{132}{}{Gizmo, the casino owner, employs Saul. He occasionally likes to watch a match or two, but mostly it's good money - people will bet a lot on a fight. And nobody has to get killed, unlike those death matches they supposedly have in the Hub.}
{133}{}{Death matches?}
{134}{}{Thanks.}
{135}{}{Well, it's just a rumor. But they say there's an underground fighting ring there where you can pay to watch people fight to the death. Not my kind of fight.}
{136}{}{Hmm. Thanks.}
{137}{}{Hey, what are you doing?}
{138}{}{Uh, nothing.}
{139}{}{You wanna start something, loser?}
{140}{}{Please quit it.}
{141}{}{Uh, no. Never mind. Forget I said anything.}
{142}{}{Well, well, looks like you're a winner! Here's your caps.}
{143}{}{Come back when you have enough caps to bet!}
{144}{}{Would you like to wait here until the fight starts at 2:00?}
{145}{}{Sure, what the heck.}
{146}{}{Nah, I got stuff to do. I'll be back later.}
{147}{}{Okay, but if you miss, the fight, you forfeit your bet!}
{148}{}{Let the fight begin!}
{149}{}{Please don't disturb me while the match is in progress.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{150}{}{Well, you can't win them all, my friend. Better luck next time.}
{151}{}{Well, you can't win them all, my friend. Better luck next time.}

{152}{}{Sorry, one bet per fight.}
