{100}{}{You see a desert bandit. Based on how the others look at her, she must have some position of importance or authority.}
{101}{}{I am Gwen. I'm one of Garl's advisors. Who are you?}
{102}{}{I'm }
{103}{}{. What do you do around here?}
{104}{}{I'm nobody special. Can you tell me about your camp?}
{105}{}{Hroo?}
{106}{}{I am the one who will sweep you off your feet, honey.}
{107}{}{As an advisor, I make sure that no low-lifes cause any trouble for Garl.}
{108}{}{And how do you do that?}
{109}{}{You and what army?}
{110}{}{I doubt you could do anything to stop anyone.}
{111}{}{Looks like all the low-lifes live here.}
{112}{}{Hmpf. If you're nobody special then I won't bother talking to you. Go away.}
{113}{}{I keep idiots like you from bothering Garl. Go away!}
{114}{}{I have ways to make certain undesirables are no longer here.}
{115}{}{I can see that I was wrong. You probably could do your job well. Goodbye.}
{116}{}{Prove it!}
{117}{}{Die!}
{118}{}{It's been so long since I've had a good fight. Too bad you are going to lose. Here is proof of my skills!}
{119}{}{You'll regret that remark. It will be your last!}
{120}{}{If that is the best you can do, then I will be doing the world a favor by killing you.}
{121}{}{Me and this army!}
{122}{}{You annoy me. Leave before I become truly angry.}
#
# Fallout Fixt:
#
{200}{}{You see: Gwen, the Khans' second-in-command and advisor to Garl.}
