{100}{}{You see a Brotherhood guard.}
{101}{}{Stay sharp Initiate!}
{102}{}{Looking good. Keep up the good work.}
{103}{}{Hello Initiate; everything is secure.}
{104}{}{Sorry, I shouldn't be talking to anyone. You know how it is.}
{105}{}{You should talk to Talus or Maxson if you have any questions.}
{106}{}{Vree's in the library during the day if you ever have technical questions.}
{107}{}{Rhombus is my idol.}
{108}{}{I wish I was training right now, this guard duty is a waste of time.}
{109}{}{Vree's my idol.}
{110}{}{Hi Brother }
{111}{}{.}
{200}{}{Only Scribes and Paladins are allowed in this room.}
{201}{}{You were warned. Now you will be dealt with.}
{202}{}{Sorry, only members of the Brotherhood can enter here.}
