{100}{}{You see: Harry, the Super Mutant.}
{101}{Harry_0}{Hey! You not look like ghoul. How come?}
{102}{}{That's because I dressed up really snazzy today.}
{103}{}{But I am a ghoul!}
{104}{}{Let me guess... because I'm not a ghoul?}
{105}{}{Uh?}
{106}{Harry_0a}{Huh?}
{107}{Harry_0a}{Huh?}
{108}{Harry_0b}{Whuh?}
{109}{}{Mom?}
{110}{Harry_01}{Oooo... That was snazzy like, huh?}
{111}{}{Nah, I was just fooling you, I'm not a ghoul}
{112}{}{What do you do here?}
{113}{Harry_02}{You not ghoul! I knew, I knew! Not fool Harry!}
{114}{}{Yeahhh, that's pretty obvious.}
{115}{}{You're right. And now that you know, I'll have to kill you.}
{116}{Harry_03}{You not ghoul. Orders say not-ghoul, not be here.}
{117}{}{Who's giving you orders?}
{118}{}{Okay, thanks. I'll be leaving now.}
{119}{Harry_04}{Lou tell me watch place. Not let no one in. Not normals most. Take normals to the Lou. Hey...}
{120}{}{But I'm not a normal!}
{121}{}{Okay, let's go see Lou.}
{122}{}{Frag it. How about, 'Not let you live.'}
{123}{Harry_05}{Oh ho-ho, you find out soooon.}
{124}{Harry_06}{Oh, uh, okay. Have nice... day.}
{125}{Harry_07}{Harry think he beat your head now.}
{126}{Harry_08}{Ooo... Harry confused. You not ghoul. You not normal. Hmm, what you? [mumbling]}
{127}{}{I'm a new race of Super Mutant.}
{128}{}{I'm a highly advanced robot.}
{129}{}{Alright, I am a normal.}
{130}{Harry_09}{No! Harry know you not. Not like you!}
{131}{Harry_10}{Oh, okay. Harry think what to do.}
{132}{Harry_11}{Not like you. Hurt you now. Bad.}
{133}{Harry_12}{Uh, hello, pretty lady. You look real nice.}
{134}{}{Are you busy? I could use a big, strong man.}
{135}{}{Move a little closer. I've got something for you.}
{136}{Harry_13}{Harry gotta guard this place. Gotta stay right here.}
{137}{}{Ahh, I understand. You have a good day, then.}
{138}{}{That makes me sad.}
{139}{Harry_14}{Hey, you a normal! Gotta take you to Lou. Now!}
{140}{}{Please, don't do it. Let me go.}
{141}{}{Ah, heck with it! Watch these feminine wiles, mutie!}
{142}{Harry_15}{Ohhh... Go away quick or Harry be in trouble.}
{143}{Harry_16}{Okay. Go now. Gotta keep eyes out for humans. Not have time for you.}
{144}{Harry_17}{What do you have for me?}
{145}{}{A whittle smack just for you...}
{146}{}{A whittle kiss just for you.}
{147}{Harry_18}{You hurt Harry's friends! I... hurt... you!}
{148}{Harry_19}{Ohhh... You again? What want now?}
{149}{}{I want you to take me to your superiors.}
{150}{}{Nothing, just passing through.}
{151}{}{I came back to kick your ass.}
{152}{Harry_20}{Um... Okay. Move along then.}
{153}{Harry_21}{Hey, you a normal! You come with Harry!}
{154}{Harry_22}{Hmm... Okay. Take ya to Lou.}
{155}{Harry_23}{Ummm... yes. You prime normal. The Lou will be happy. Take away, take away.}
{156}{}{Wait, wait! You don't understand.}
{157}{}{I'll kill you with my bare hands.}
{158}{Harry_24}{Not have to. Harry follow orders. Take to the Lou.}
{159}{Harry_25}{Harry not think so, but you can try. Let go, guys.}
{160}{Harry_26}{Hey, Harry hear about you. You break the Vats!}
{161}{}{Yep, I did. And now I'm going to take you out.}
{162}{}{Yes, I'm the one. What are you going to do about it?}
{163}{}{Uh-huh.}
{164}{Harry_27}{Uhh, me let you go. Okay? You not show face here again? Please?}
{165}{}{Not good enough.}
{166}{}{Goodbye. I don't expect to see you again.}
{167}{}{Uhh.}
{168}{Harry200}{Not have to tell you anything!}
{169}{Harry201}{You kill Larry!}
{170}{Harry202}{You kill Gary!}
{171}{Harry203}{You kill my brother, Barry!}
{172}{Harry204}{You kill Terry!}
{173}{Harry205}{You kill Sally! He did have lousy name. But not reason to kill him!}
{174}{Harry26}{Not bother me. Leave alone!}
{175}{Harry207}{Uhhh... Not know.}
{176}{Harry300}{I dunno, but think he like a boss people.}
{177}{Harry301}{He Lou Tenant. He my boss. Not tell him, but Harry could take on good day.}
{178}{Harry302}{Set a wuss. He think he run place, but we run.}
{179}{Harry303}{The what?}
{180}{Harry304}{Hmph! Punies.}
{181}{Harry305}{Weak. Not know why the Lou want normals. They suck!}
{182}{Harry306}{Here, dummy. [sigh] You stupid?}
{183}{Harry307}{The U-U-U-Un, I don't know.}
{184}{Harry308}{Nice for little guys. Harry hurt once and they make better. Make perfect again!}
{185}{}{HARRY FIGHT NOW!}
{186}{}{HARRY FIGHT NOW!}
{187}{}{HARRY FIGHT NOW!}
{188}{}{HARRY FIGHT NOW!}
{189}{}{HARRY WAIT 30 SECONDS!}
{190}{}{HARRY LEAVE NOW!}
{191}{}{You're not taking me anywhere!}
{192}{}{Okay, take me to your boss.}
{193}{}{The mutant ignores you.}



#
# Harry Tell-Me-Abouts
#
{970}{Harry_0b}{Whuh?}

{980}{Harry_0a}{Huh?}
{981}{Harry_0b}{Whuh?}
{982}{Harry207}{Uhhh... Not know.}
{983}{Harry303}{The what?}
{984}{Harry200}{Not have to tell you anything!}

{1000}{}{Master|Mutant Leader}
{1001}{}{Lou|Lieutenant|Lutenant|Loo|Lou Tenant|Lt}
{1002}{}{Set|Seth|Wuss}
{1003}{}{Water Shed|Watershed|Shed}
{1004}{}{Ghouls|Ghoul|Mutant|Mutants}
{1005}{}{Norms|Human|Normies|Normals}
{1006}{}{Necropolis|CITY OF DEAD|CITY OF THE DEAD}
{1007}{}{Unity}
{1008}{}{Children of the Cathedral|Children|Cathedral|CoC}
{1009}{}{Chip|Water Chip|Waterchip}
{1010}{}{Hall}
{1011}{}{Water}
{1012}{}{Larry|Barry|Gary|Terry|Sally}

{1100}{Harry300}{I don't know, but think he like a boss people.}
{1101}{Harry301}{He Lou Tenant. He my boss. Not tell him, but Harry could take on good day.}
{1102}{Harry302}{Set a wuss. He think he run place, but we run.}
{1103}{Harry306}{Here, dummy. Hmpf. You stupid?}
{1104}{Harry304}{Hmpf! Punies.}
{1105}{Harry305}{Weak. Not know why the Lou want normals. They suck!}
{1106}{Harry306}{Here, dummy. Hmpf. You stupid?}
{1107}{Harry307}{The U-U-U-Un, I don't know.}
{1108}{Harry308}{Nice for little guys. Harry hurt once and they make better. Make perfect again!}
{1109}{Harry303}{The what?}
{1110}{Harry207}{Uhhh... Not know.}
{1111}{Harry207}{Uhhh... Not know.}
{1112}{Harry200}{Not have to tell you anything!}
