{100}{}{You see: Billy.}
{101}{}{Hey! Leave my stuff alone!}
{102}{}{Hi there.}
{103}{}{Hi, what are you doing?}
{104}{}{Can I have a brahma?}
{105}{}{Hi. Uh, bye.}
{106}{}{Arg!}
{107}{}{Ta.}
{108}{}{Why would you want a brahma? Do you have a caravan? Well, it doesn't matter. I only take care of them. Dan is the one who owns them. He won't sell them though.}
{109}{}{Why?}
{110}{}{I was just kidding.}
{111}{}{Cuz of all the missing caravans. He doesn't have any to spare, the use caravans most of them. The others are sold to for food. Well I'd better stop talking, Dan will get mad if he sees me talking to a stranger.}
{112}{}{Oh, okay.}
{113}{}{Nothing... I mean, I'm taking care of the brahmin.}
{114}{}{What's the spear for? Are they dangerous? }
{115}{}{What's a brahmin?}
{116}{}{'What's a brahmin?' You must be joking. Brahmin are one of the major food sources and forms of transportation around here. They haul the caravans. Dan says this is a really important job, but it sucks. Oh, and by the way, it's 'brahma' - brahmin is plural. Dork.}
{117}{}{Oh, I knew that! }
{118}{}{Dan's right. You are doing a great job.}
{119}{}{Yeah, it looks that way. Have fun.}
{120}{}{Hey, you're one of those skags aren't you?}
{121}{}{Really? You think so? Jeee, thanks.}
{122}{}{You're not from around here are you. I'll give you one tip. Don't get caught stealing!}
{123}{}{Sure, thanks.}
{124}{}{I wouldn't dream of stealing. Stealing is wrong.}
{125}{}{Yeah, I think I'm starting to agree with you. This job isn't so bad really. It makes me feel good for some reason. Well, I've got to go before I get in trouble.}
{126}{}{Please don't hurt me or my brahmin.}
{127}{}{Don't hurt me!}
{128}{}{Stop it!}
{129}{}{Please leave me alone.}
{130}{}{You're scaring me.}
{131}{}{Hey what are you trying to do? I don't have anything you'd want.}
{132}{}{Stop that!}
{133}{}{Dangerous? No, not really. They call give you a really nasty bite, but they're pretty cool. They fart and burp a lot. I don't know why.}
{134}{}{So what's the spear for?}
{135}{}{Okay thanks.}
{136}{}{Oh, they can be awfully stubborn when I want them to do something. I just gently stick them to get them to move around... plus I don't want to get to close, they sometimes kick.}
{137}{}{Please don't talk to me, Dan is going to yell at me again. He really gets piss... I mean mad, when I'm not paying attention to what I'm doing.}
{138}{}{He's just trying to help. Work hard and I'm sure he'll be nicer.}
{139}{}{Here kid, take 50 caps and get away from this jerk. }
{140}{}{Okay.}
{141}{}{Aaaaaarg!}
{142}{}{Rhu?}
{143}{}{Please don't, I'm already in enough trouble.}
{144}{}{I AM working hard!}
{145}{}{I'm sorry, I didn't mean that. He's just trying to help you. }
{146}{}{No you aren't! You lazy little brat!}
{147}{}{Okay.}
{148}{}{Yeah, maybe you're right... actually he seems pretty cool, but I wish he wouldn't yell at me so much.}
{149}{}{Yeah, right.}

# said to male player
{150}{}{Up yours, you old fart!}
{152}{}{WOW! I can live on this for the rest of my life! Thanks a lot, mister!}

# said to female player
{151}{}{Up yours, you old hag!}
{153}{}{WOW! I can live on this for the rest of my life. Thanks a lot, ma'am!}

{154}{}{WOW! Thanks... Well...? You're just trying to get me in trouble again!}
{155}{}{Please don't talk to me, Dan is really mad.}
{156}{}{Don't worry. I had a talk with him, he'll try to be nicer to you.}
{157}{}{And he should be! You're a terrible kid!}
{158}{}{Wac.}
{159}{}{Hi!}
{160}{}{Those girls over there sure are dumb.}
{161}{}{Hi again.}
{162}{}{Brahmin are cool.}
{163}{}{Dan's taking me to the Falcon if I do a good job.}
{164}{}{Dan's going to take me on a caravan some day!}
{165}{}{I'm going to be an adventurer when I grow up.}
{166}{}{Really? Oh, okay. I hope you didn't hurt him. He's really not so bad. He just yells a lot.}
{167}{}{Hello again.}
{168}{}{What is it you do again? }
{169}{}{Can I have a brahma?}
{170}{}{Just stopping by to say how things where going. Bye.}
{171}{}{Arg!}
{172}{}{Ta.}
{173}{}{I better get back to work.}
{174}{}{Those girls over there sure are dumb.}
{175}{}{Hi again.}
{176}{}{I'm going to be an adventurer when I grow up.}
{177}{}{Brahmin sure do shi... uh, poop a lot.}
{178}{}{I can't talk right now.}
{179}{}{I don't want to get in trouble.}
