{100}{}{You see a caravan driver.}
{101}{}{Today's going to be a long day!}
{102}{}{I really don't want to work today.}
{103}{}{I hope we don't get raided... or worse.}
{104}{}{Sorry, we don't need anymore guards... I think.}
{105}{}{Sorry, we're full.}
{106}{}{You should check out the Merchant Market if you want a job.}
{107}{}{I hope we sell everything.}
{108}{}{I can't wait until we finish.}
{109}{}{Let's hit the road.}
{110}{}{I'm ready to kick some butt.}
{111}{}{We're out of here!}
{112}{}{It sure was hot today.}
{113}{}{Boy am I thirsty.}
{114}{}{What day is it?}
{115}{}{I'm off to the Falcon as soon as I'm done!}
{116}{}{Sorry, we're just getting back from a route.}
{117}{}{You should check out the Merchant Market if you want a job.}
{118}{}{Today's payday!}
{119}{}{I'm heading straight for Bob's!}
{120}{}{I've got to pay back the loan today!}
{121}{}{I'm so tired.}
{122}{}{That was a long trip!}
{123}{}{Time to call it a night, I guess.}
{124}{}{See ya tomorrow, folks.}
{125}{}{Oh man, what a night that was.}
{126}{}{I'm getting old...}
{200}{}{You see: Mat.}
{201}{}{I shall see you guys tomorrow. Don't let the bedbug bite you...}
{202}{}{Now that was a weird dream.}
{203}{}{Yes? How can I be of service?}
{204}{}{Duh?}
{205}{}{What is this place?}
{206}{}{Could you tell me where I could find a Water Chip?}
{207}{}{What are all these carts doing here?}
{208}{}{Oh. Excuse me I thought you were someone else. Bye.}
{209}{}{Yeah. You could die.}
{210}{}{Too long in the wastes, unh? That's too bad.}
{211}{}{This is the Hub. It is a trade center for the wastes. It's the biggest city I know of, you can find just about any thing you could want here. And if you're lookin' for work this is the place to be. It seems like just about everyone here is lookin' ta hire you for somethin' be it legal or not.}
{212}{}{Could you tell me where I could find a Water Chip?}
{213}{}{What are all of these carts doing here?}
{214}{}{Trade? What is it you trade?}
{215}{}{Where would I go to get a job?}
{216}{}{Goodbye.}
{217}{}{A Water Chip? Wow. You got me on that one. I've never heard of one of those. Maybe you should check the general store downtown, they may be able to help you.}
{218}{}{What are all of these carts doing here?}
{219}{}{Thank you. Goodbye.}
{220}{}{These are the caravans. We cart goods to just about all corners of the wastes. Junktown, The Brotherhood, Shady Sands, and numerous other places. Necropolis and the Glow are the only areas we steer clear of. I'm headin' this group and we will be leavin' shortly. The group across the street just arrived.}
{221}{}{This looks like the same caravan I saw earlier...}
{222}{}{What is it you trade?}
{223}{}{What is this place?}
{224}{}{Where would I go to get a job?}
{225}{}{Thank you. Goodbye.}
{226}{}{Hum... Lots of stuff. General stuff people need to live, food, water, lots of water. Water is probably the scarcest commodity in the wastes.}
{227}{}{Could you tell me where I could find a Water Chip?}
{228}{}{Where would I go to get a job?}
{229}{}{Thank you. Goodbye.}
{230}{}{You could ask just about anyone here in the Hub. Or you can check one of the job bulletin boards. There are a few of them around the Hub. Definitely more jobs than people here.}
{231}{}{What is this place?}
{232}{}{Could you tell me where I could find a Water Chip?}
{233}{}{What are all of these carts doing here?}
{234}{}{Thank you. Goodbye.}
{235}{}{[laughs] Yes. I guess you could say that. After a while they all start to look the same. But believe me they're not.}
{236}{}{You shall die for mocking me!!!}
{237}{}{Where would I go to get a job?}
{238}{}{Goodbye.}
{300}{}{You see: Luke.}
{301}{}{These are the caravans. We cart goods to just about all corners of the wastes. Junktown, The Brotherhood, Shady Sands, and numerous other places. We just got in and it's been a long trip. The group across the street is getting ready to depart.}
{400}{}{You see: John.}
{401}{}{What are you doing out here at this hour?}
{402}{}{You're an idiot. Get outta here you skag.}
{403}{}{A Water Chip? I never even heard of one of those.}
{404}{}{These are the caravans that I'm guarding. The merchants cart goods to just about all corners of the wastes, Junktown, The Brotherhood, Shady Sands, and numerous other places.}
{405}{}{Well... Lots of stuff. General stuff people need to live, food, water, lots of water. Since water probably is the most scarcest commodity in the wastes.}
{406}{}{You could ask just about anyone here in the Hub. Or you can check one of the job bulletin boards there are a few of them around the Hub.}
{407}{}{I'm a security guard hired by the merchants who own the goods in these carts. Dangerous job, but it pays well. Just the other night one of my coworkers was killed while watching over the caravans.}
{408}{}{What are the caravans?}
{409}{}{Ahhhh. [sarcastic] What a sad story. How would you like to join your friend?}
{410}{}{Bye.}

## Fallout Fixt:

{501}{}{You see: Caravan Guard.}
{502}{}{You see: Caravan Driver.}
{503}{}{You see: Caravan Driver.}
{504}{}{You see: Caravan Merchant.}
