{100}{}{You see the high-stakes Craps table. It costs 40 caps to play.}
{101}{}{You rolled a 7. You will!!}
#TRANSLATION NOTE: "Snake Eyes" in English means each of the dice rolled a 1.
{102}{}{You roll snake eyes. You lose.}
#TRANSLATION NOTE: Extra space at end of 103 is intentional, DO NOT remove it.
{103}{}{You rolled }
{104}{}{! You win!!}
#TRANSLATION NOTE: Extra space at end of 105 is intentional, DO NOT remove it.
{105}{}{You rolled }
{106}{}{. You lose.}
#TRANSLATION NOTE: Extra space at end of 107 is intentional, DO NOT remove it.
{107}{}{You rolled }
#TRANSLATION NOTE: Extra space at beginning of 108 is intentional, DO NOT remove it.
{108}{}{ before rolling your point. You lose.}
{109}{}{You rolled your point. You win.}
#TRANSLATION NOTE: Extra space at end of 110 is intentional, DO NOT remove it.
{110}{}{You rolled }
{111}{}{. This is your point. Rolling again.}
{112}{}{You earn 70 experience for killing the dealer.}
