{100}{}{You see an Elder of the Brotherhood.}
{101}{}{Greetings Initiate. I need to speak with you. [He motions for you to come closer.]}
{102}{}{About what?}
{103}{}{I don't have time right now.}
{104}{}{Err?}
{105}{}{There is an urgent matter I need you to help me with. It's Maxson. We are pretty sure he's gone off the deep end. He keeps babbling about an army massing to the north.}
{106}{}{ I'm not willing to send our troops up there into possibly irradiated areas, unless I've got absolute proof that this 'army' exists.}
{107}{}{ I need someone who isn't a friend of the old man. Someone I can get an honest report from. Are you willing to check the northern region?}
{108}{}{I'll do it.}
{109}{}{I can't do it right now. I've got other things I need to deal with.}
{110}{}{I've already seen a base to the north run by an army of mutants.}
{111}{}{Good. First go talk to Maxson if you haven't already. Report back to me when you've checked the northern territory. After that, we'll decide what to do with Maxson.}
{112}{}{Wish me luck.}
{113}{}{Have you explored the entire northern territory?}
{114}{}{Yes.}
{115}{}{No.}
{116}{}{And what do you have to report?}
{117}{}{I've found a base guarded by heavily armed mutants. It looks pretty bad.}
{118}{}{I didn't think so. You weren't gone for very long. Now, get back out there and don't come back until you have a FULL report.}
{119}{}{Yes, sir.}
{120}{}{I will inform the Elders. We will wait for Maxson's word on what to do. Go inform him on what you've found. Thanks for your help, Initiate.}
{121}{}{You're welcome.}
{122}{}{Then you will make time to hear me out.}
{123}{}{You've got my attention.}
{124}{}{You can go to hell old man.}
{125}{}{Forget it. I've got more important things to do.}
{126}{}{I understand. If you do travel up into that area and find anything, please, let me know.}
{127}{}{If I find anything that resembles an army up north, I will let you know.}
{128}{}{Good work with the mutants. We already heard that you destroyed their production facility. Thanks for taking care of that problem for us.}
{129}{}{No problem.}
{130}{}{Err? What kind of response is Err? Leave! Now!}
{131}{}{If it was up to me, you would be out of here.}
{132}{}{I have nothing to say to you.}
{133}{}{You should learn some respect.}
{134}{}{The meeting will come to order. All Elders are present and have agreed to hear out the claims of Brother }
{135}{}{. We shall determine what actions will be taken. Brother }
{136}{}{, tell us what you have seen to the north.}
{137}{}{During my explorations, I found a military installation being used by mutants. It is heavily guarded and patrolled regularly.}
{138}{}{Norfa?}
{139}{}{And what did these mutants look like?}
{140}{}{They are large humanoids. Their muscle mass is well beyond what a regular human could ever gain. There appear to be several of them guarding the gate in organized troops.}
{141}{}{They were big, greenish, and carrying weapons.}
{142}{}{As you may know, our Head Scribe, Vree, has done an autopsy on a creature very similar to what you have just described. Do you believe these are the same?}
{143}{}{Yes. The description of the creature is nearly identical.}
{144}{}{What threat do you assume these 'mutants' pose?}
{145}{}{Just as the Brotherhood has been gearing up for battle, this 'mutant army' has been preparing for something big.}
{146}{}{Frankly, your report has not shown us any proof that they are a threat to us. What proof can you give that they have hostile intentions.}
{147}{}{They have invaded Necropolis. They won't stop there. }
{148}{}{They are gathering an army. A heavily armed army. They certainly aren't going to just parade around. They intend to use it.}
{149}{}{So, by these actions they are taking, it is feasible that they will eventually come here?}
{150}{}{It is possible that they are already on their way here. The Brotherhood is the only real opposition they could have.}
{151}{}{I don't believe that shows hostility. They could simply be protecting themselves from attack. Even we have to deal with the occasional attack.}
{152}{}{If they attack, it will be NOTHING like the occasional attack you get from the raiders. This will be a slaughter. }
{153}{}{Since they are coming out of that old military installation, I would imagine that they would have weapons comparable to your own.}
{154}{}{What do you suggest? A preemptive strike at their military base?}
{155}{}{Yes. I don't want them to know we are coming though. A small team would stand a better chance of getting into their perimeter without being detected. }
{156}{}{That will only take care of one part of the problem. They're being led by a group coming out of the Boneyard Cathedral.}
{157}{}{So be it. You shall have three Paladins of my choosing to meet you at the Military Base to help you get inside. Elders, thank you for your time. Best of luck to you Initiate.}
{158}{}{If they are being led by a group out of the Boneyard Cathedral, then chances are they have a small army down there as well. }
{159}{}{If we take them out in the north, then it leaves our south side vulnerable. I can only spare a few men on this endeavor.}
{160}{}{Give me a few Paladins to take out their base to the north.}
{161}{}{Give me a few Paladins to take out their base to the south.}
{162}{}{So be it. You shall have two Paladins of my choosing to meet you at the Boneyard Cathedral. Elders, thank you for your time. Best of luck to you Initiate.}
{163}{}{So be it. You shall have three Paladins of my choosing to meet you at the Military Base to help you get inside. Elders, thank you for your time. Best of luck to you Initiate.}
{164}{}{Obviously we made a mistake. Elders, I am sorry for wasting your time. Would someone please remove this mental abomination?}
{165}{}{I am too busy planning a defensive strategy.}
{166}{}{You earn }
{167}{}{ experience for convincing the Brotherhood of Steel to help you take out the Mariposa military base.}

# Fo1in2
{168}{}{ experience for convincing the Brotherhood of Steel to help you take out the Boneyard Cathedral.}

