{100}{}{You see: Daren Hightower.}
{101}{}{Who are you?!? And who let you in?}
{102}{}{I have a message from a friend.}
{103}{}{Your life is in danger, and I need to speak with you.}
{104}{}{My name is }
{105}{}{. Leon let me in.}
{106}{}{My name? ...Death!}
{107}{}{I'm your worst nightmare.}
{108}{}{BoBo?}
{109}{}{I have no friends. What is your message?}
{110}{}{Decker sends his regards.}
{111}{}{Um... Bob sent me... ah... he said you overpaid him 100 caps and sent me to give it to you.}
{112}{}{There is no message really, I was just trying to talk my way out of this.}
{113}{}{I love you.}
{114}{}{Tell me something I don't know, you moron!}
{115}{}{Moron? I was trying to help you. You can go to Hell.}
{116}{}{Decker wants you dead and he hired me to do it.}
{117}{}{You obviously don't know that you're about to die!}
{118}{}{Forget it. I was just trying to help.}
{119}{}{It's been a pleasure meeting you }
{120}{}{. Now my assistant Leon will see you out of my home.}
{121}{}{I don't know any Bob, but I'll take the 100 caps and you can leave.}
{122}{}{Go to hell!}
{123}{}{Okay, here you go. Thanks for your time.}
{124}{}{Uhh... That BASTARD Bob didn't give me enough caps! I'll get 'em for you Mr. Hightower, honest I will!}
{125}{}{Think nothing of it. I always enjoy strangers coming into my home and giving me money. Leon, show this fool the door! Come back again, and my guards will have your head!}
{126}{}{Leon, show this fool the door! Come back again, and my guards will have your head!}
{127}{}{Guards! Assassin!}
