{100}{}{You see a locked strongbox.}
{101}{}{You see an unlocked strongbox.}
{102}{}{The strongbox is locked.}

{103}{}{While opening the strongbox, you detected and disarmed a trap.}
{104}{}{While opening the strongbox, you detected a trap, but accidentally set it off.}
{105}{}{While opening the strongbox, you detected a trap, but failed to disarm it.}
{106}{}{The strongbox is already unlocked.}
{107}{}{You successfully unlocked the strongbox.}
{108}{}{Your multiple attempts to unlock the strongbox have set off a trap.}
{109}{}{You were unable to unlock the strongbox, and the lock has become jammed.}
{110}{}{You were unable to unlock the strongbox.}
{111}{}{You find a trap on the strongbox and successfully disarm it.}
{112}{}{You find a trap on the strongbox.}
{113}{}{While searching the strongbox for traps, you accidentally set one off.}
{114}{}{You find nothing while searching the strongbox for traps.}
{115}{}{You successfully disarmed the trap.}
{116}{}{You accidentally set off the trap.}
{117}{}{You failed to disarm the trap.}
