{100}{}{You see: Jennifer.}
{101}{}{You see a Paladin.}
{102}{}{Excuse me, Brother. You should put away your weapon whenever you are in the Brotherhood. We are a friendly order, but as you know, times are rough.}
{103}{}{Some members of the Brotherhood might be offended if a stranger... I mean, a new Initiate... approaches them with a weapon.}
{104}{}{Good day, Initiate. How may I help you?}
{105}{}{Hello, Sister, it's good to see there are women of rank in this organization. I didn't know what to expect with a name like the Brotherhood.}
{106}{}{Hey there, legs. You are looking mighty fine. What time should I pick you up?}
{107}{}{Oooooga!}
{108}{}{Could you tell me where I might find our High Elder?}
{109}{}{Who's in charge of this hole?}
{110}{}{Where's this High Elder guy?}
{111}{}{Gruk!}
{112}{}{Maxson, the High Elder, can be found on the Fourth Floor. If you take the other elevator down to level four, he should be either in the Council Room or the Elders' rooms.}
{113}{}{You can ask one of the guards on that level; they should know where he is at the moment.}
{114}{}{Thank you.}
{115}{}{Where can I get some better weapons?}
{116}{}{You should talk to Talus. He might be able to help you, or at least tell you who to talk to.}
{117}{}{During the day, Talus is normally supervising in the training hall. Do you know where that is?}
{118}{}{Yes, I do. Thank you.}
{119}{}{No.}
{120}{}{Of course I do!}
{121}{}{The training hall is right around the corner. Just go down this corridor, make a left, go through the door at the end of the corridor and it will be through the door on your right.}
{122}{}{You have been extremely helpful. Thank you very much. I hope we can talk again soon. Good day.}
{123}{}{Training hall? Do you think I could get some training there? I am a member of the Brotherhood now, right?}
{124}{}{Thank you for your help, Sister. It's good to see there are women of rank in this organization. I didn't know what to expect with a name like the Brotherhood.}
{125}{}{Thanks, Sugar. You know, you're looking mighty fine. What do you say you and me check out each other's 'equipment' later? What time do you get off?}
{126}{}{Oh, that place. Okay, bye.}
{127}{}{Excuse me? Is there something wrong?}
{128}{}{Muk lug?}
{129}{}{I'm sorry, I don't think I can help you. You should go see the doctor. She's on the second level.}
{130}{}{Of course there are. Two of our five Elders are women, our Head Scribe is a woman, and we have many other women in all the different ranks.}
{131}{}{The women of the Brotherhood are also called Brothers. We don't call the women Sisters. This is the Brotherhood of Steel, after all, not the Brother and Sisterhood of Steel.}
{132}{}{Don't you find it peculiar that it is called the Brotherhood, implying that its members consist solely of men?}
{133}{}{But why is it called the Brotherhood, then?}
{134}{}{Well, it just seemed strange.}
{135}{}{I do not know. That has been our name all of my life. I'm sure there is a reason for it.}
{136}{}{I guess you're right.}
{137}{}{Well, it still seems a little strange to me.}
{138}{}{That is strange. I've never really put much thought into it. We've been the Brotherhood of Steel all of my life. Our ancestors must have had a reason for naming it so.}
{139}{}{But that doesn't mean things can't change.}
{140}{}{Yeah, you're probably right.}
{141}{}{So, is there anything else I can help you with?}
{142}{}{Yes, where can I find the High Elder?}
{143}{}{Where can I get better weapons?}
{144}{}{No, that's it. Bye.}
{145}{}{No, we're very strict when it comes to tradition. I don't think it could ever be changed. It doesn't bother me at all to be addressed as a Brother. That is curious, though.}
{146}{}{I think I'll have a talk with Vree. She might be able to give some insight as to why our ancestors decided to call us the Brotherhood of Steel.}
{147}{}{Who's Vree? One of the Elders?}
{148}{}{Vree's the Head Scribe. She is the one you should talk to if you have any technical questions, but don't disturb her during her meditations at night.}
{149}{}{She almost always stays in her room, which is also occupied by the mainframe on the third floor.}
{150}{}{Hole? How dare you talk like that about the Brotherhood. You are a member of our order now, and should be proud to be a member of the Brotherhood of Steel.}
{151}{}{Proud? Why? You're all just a bunch of robotic hop-heads, hiding from the real world. There's nothing to be proud of there.}
{152}{}{I'm sorry. I get a little carried away with myself sometimes.}
{153}{}{Yeah, right.}
{154}{}{Well, I guess we all do sometimes.}
{155}{}{So who is in charge of this place?}
{156}{}{Yeah. Well, I've got to go.}
{157}{}{Maxson, the High Elder. He's on the fourth floor.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Well, you are cute... but I don't think so. I don't think it would be a good idea to get involved with an outsider, anyway. You are cute, though, and somewhat attractive. }
{164}{}{I don't know if it's because you're an outsider or because of your extreme... lack of tact? So, 'honey', is there anything else I can do for you?}
{165}{}{Yeah, uh, I guess. Uh, who's in charge around here?}
{166}{}{Uh, okay... um. How about some weapons then? Where can I get my hands on some of those?}
{167}{}{Hmmph!}
{168}{}{No.}
{169}{}{That's... pretty funny. You are joking, I hope? Actually... don't answer that. I don't think I want to know.}
{170}{}{Yeah, REAL funny. Almost as much as your face!}
{171}{}{Thanks a lot. That's exactly what I needed to hear right now.}
{172}{}{I'm out of here.}
{173}{}{I'm sorry. It's just that you outsiders have such a strange way of talking to people sometimes. Is there anything I can help you with?}
{174}{}{Well, I guess I should talk to this High Elder person. Where is he at?}
{175}{}{I would like to get some better weapons. Who do I talk to about that?}
{176}{}{No.}
{177}{}{Are you for real? I haven't heard such a pitiful line in all my life!}
{178}{}{Yeah? Well, I don't get out much. Okay?}
{179}{}{Get out of my face, you walking garbage can!}
{180}{}{Pfft!}
{181}{}{Well, yes, you are a member of the Brotherhood, but the Elders have put a hold on all training of new Initiates.}
{182}{}{Why?}
{183}{}{Oh, that's just GREAT! Why the hell did I join this stupid group? Where's the door?!}
{184}{}{There are rumors about some kind of army. I think the Elders want to concentrate their resources on the ones that are already far enough along in their training to make a difference if we do have a big battle on our hands.}
{185}{}{We strongly believe that training a few fighters extremely well is better than giving mediocre training to a bunch of fighters. Saving lives is one of our primary objectives.}
{186}{}{You could probably get quite a bit out of the training just by watching. Brother Thomas is the best trainer we have ever had at the Brotherhood.}
{187}{}{Well, I'm to be working on the outside of the Brotherhood, right? It's a very hostile world out there and I'll be putting my life on the line every minute I'm out there. Don't you think I should be given training if I want or need it, or do you only 'say' it is your primary objective to 'save' lives?}
{188}{}{Thank you for the suggestion, I'll take a look.}
{189}{}{You're all a bunch of fools.}
{190}{}{Can you tell me where Maxson is?}
{191}{}{Well, I'm only repeating what I was told. If you talk to Thomas or Talus they might be able to make an exception.}
{192}{}{Okay, thanks.}
{193}{}{They'd better. I've jumped through enough hoops for you guys.}
{194}{}{So, can you tell me where Maxson is?}
{195}{}{Oh, my darling. When are we going to marry?}
{196}{}{You're looking so handsome, as always.}
{197}{}{Give me a kiss.}
{198}{}{I've missed you so much.}
{199}{}{I'll wait up for you.}
{200}{}{I've been thinking about you all day.}
{201}{}{You're so cute when you look at me like that.}
{202}{}{Don't scare me like that. I thought I'd never see you again.}
{203}{}{You didn't come by last night.}
{204}{}{How long has it been since I've last seen you? It seems like an eternity.}
{205}{}{I've missed you ever so much.}
{206}{}{Come to bed, honey.}
{207}{}{We can get married in the morning.}
{208}{}{I think we should have about five kids.}
{209}{}{Where do you want to go for our honeymoon? I hear the Children of the Cathedral have a beautiful place.}
{210}{}{My parents are still waiting to meet you.}
{211}{}{Why hello again. I hope things are well with you. I hope you've talked to Vree.}
{212}{}{Hello, Brother }
{213}{}{.}
{214}{}{Be careful if you go to the north. Our scouts never returned.}
{215}{}{Brother }
{216}{}{, it's good to see you again.}
{217}{}{Have you talked to Rhombus? He's the Head Knight. He's just right over there in that room.}
{218}{}{I don't have time to talk. I'm busy.}
{219}{}{Sorry, I'm not in the mood to talk to rude people.}
{220}{}{Don't bother me.}
{221}{}{What? Can't you go bother someone else?}
{222}{}{Go away.}
{223}{}{I don't want to talk to you.}
{224}{}{Initiate, get back to your studies.}
{225}{}{No time to talk, Initiate.}
{226}{}{Come over here, you hunk!}
{227}{}{Darling, over here!}
{228}{}{ I've missed you.}
{229}{}{I've got the nursery ready, darling.}
{230}{}{Hi, honey.}
{231}{}{I see you.}
{232}{}{You've got to meet my parents.}
{233}{}{Yoo hoo!}
{234}{}{Come here, my little snookums.}
{235}{}{Are you teasing me?}
{236}{}{You're playing hard to get, aren't you?}
{237}{}{Over here, sweaty!}
{238}{}{Hi honey!}
{239}{}{There you are. I was starting to worry.}
{240}{}{Come here and give me a kiss, handsome.}
{241}{}{Come on in, darling.}
