{100}{}{He looks like an experienced guardsman.}
{101}{}{You'd better watch yourself here.}
{102}{}{This isn't a good town to get in trouble in.}
{103}{}{Behave, and we won't have to get nasty.}
{104}{}{You're okay.}
{105}{}{Keep up the good work.}
{106}{}{Nice day, isn't it?}
{107}{}{This is Junktown. Nice place to live, as long as you stay on our good side.}
{108}{}{Watch out for Gizmo and his cronies.}
{109}{}{I like my boss.}
{110}{}{You'd better put that away. Junktown is a friendly place, friend, and we want to keep it that way.}
{111}{}{Put what away?}
{112}{}{Don't tell me what to do, loser boy.}
{113}{}{Sounds fair. By the way, what is the local law regarding weapons?}
{114}{}{Uh-oh.}
{115}{}{Your weapon, idiot. Killian won't take your arms away, but you'd better damn well keep them in your holster.}
{116}{}{Oh, sorry.}
{117}{}{No way! I ain't putting down my shooters for nobody!}
{118}{}{You'd better behave, since it's the law, and I enforce the law. Put your weapon away, don't draw it unless in self-defense, and you won't have a problem with us guards. Disobey the law, and we will return you to the lawless wasteland - dead or alive.}
{119}{}{Sure, since you put it that way.}
{120}{}{Bite your laws!}
{121}{}{Well, uh, fine with me. But you'd better be careful.}
{122}{}{Good you asked. No weapons can be drawn except in self-defense. If you start a fight, it's your fault. Other than that, it's your right to go around armed. Just don't pull a knife or gun without just cause. Have a good day.}
{123}{}{Hey you, no weapons! And I don't care if your momma dropped you on your head as a kid. No weapons.}
{124}{}{Hey! You! What are you doing sneaking around?}
{125}{}{Nothing.}
{126}{}{I'm not sneaking around. I just like to walk cautiously.}
{127}{}{Uhhh.}
{128}{}{Whatever you're doing, don't do it in this town.}
{129}{}{The guard stares at you for a moment. You see a look of recognition on his face, and then he pulls his weapon.}
{130}{}{Well, uh, okay. Whatever. Just don't do anything out of line.}
{131}{}{Thanks, bye.}
{132}{}{Certainly. I will throw caution to the wind, sir.}
{133}{}{Certainly. I will throw caution to the wind, ma'am.}
{134}{}{Put that weapon away, or face the consequences!}
{135}{}{Okay, that's enough warnings. Leave town, now, and never return, or face the consequences!}
{136}{}{Hey! What do you think you're doing?}
{137}{}{That's it, you've had it, buddy.}
{138}{}{You're in trouble now...}
{139}{}{You Skulz are under arrest!}
