{100}{}{You see: Kalnor, a Junktown guard.}
{101}{}{You'd better watch yourself here.}
{102}{}{This isn't a good town to get in trouble in.}
{103}{}{Behave, and we won't have to get nasty.}
{104}{}{You're okay.}
{105}{}{Keep up the good work.}
{106}{}{Nice day, isn't it?}
{107}{}{This is Junktown. Nice place to live, as long as you stay on our good side.}
{108}{}{Watch out for Gizmo and his cronies.}
{109}{}{I like my boss.}
{110}{}{You'd better put that away. Junktown is a friendly place, friend, and we want to keep it that way.}
{111}{}{Put what away?}
{112}{}{Don't tell me what to do, loser boy.}
{113}{}{Sounds fair. By the way, what is the local law regarding weapons?}
{114}{}{Uh, oh.}
{115}{}{Your weapon, idiot. Killian won't take your arms away, but you'd better damn well keep them in your holster.}
{116}{}{Oh, sorry.}
{117}{}{No way! I'm not putting down my shooters for nobody!}
{118}{}{You'd better behave, since it's the law, and I enforce the law. Put your weapon away. Don't draw it unless in self-defense and you won't have a problem with us guards. Disobey the law and we will return you to the lawless wasteland - dead or alive.}
{119}{}{Sure, since you put it that way.}
{120}{}{Bite your laws!}
{121}{}{Well, uh, fine with me. But you'd better be careful.}
{122}{}{Good you asked. No weapons can be drawn except in self-defense. If you start a fight, it's your fault. Other than that, it's your right to go around armed. Just don't pull a knife or gun without just cause. Have a good day.}
{123}{}{Hey you, no weapons! And I don't care if your momma dropped you on your head as a kid. No weapons.}
{124}{}{Hey! You! What are you doing sneaking around?}
{125}{}{Nothing.}
{126}{}{I'm not sneaking around. I just like to walk cautiously.}
{127}{}{Uhhh.}
{128}{}{Whatever you're doing, don't do it in this town.}
{129}{}{Hey! No shady characters in town! Get out of here before we throw you out!}
{130}{}{Well, uh, okay. Whatever. Just don't do anything out of line.}
{131}{}{Thanks, bye.}
{132}{}{Certainly. I will throw caution to the wind, sir.}
{133}{}{Certainly. I will throw caution to the wind, ma'am.}
{134}{}{You'd better watch your step around here, because we'll be watching you.}
{135}{}{Welcome to Junktown. What can I do for you?}
{136}{}{Nothing, thanks.}
{137}{}{What are you doing here? What is this place?}
{138}{}{Where can I get some supplies?}
{139}{}{Wa-wa!}
{140}{}{I dunno about that. You might want to check with Killian. He's to the north. That's up that way, okay?}
{141}{}{What does it look like? I'm a guard, and I'm keeping an eye out for strangers like you. And this place is called Junktown. Hey, don't laugh. I happen to like the name myself. We mostly do trading. Sometimes we trade with those stuck up bastards from Hub. Hey, you're not from the Hub are you?}
{142}{}{What? The Hub? Sure I am!}
{143}{}{Me? No, I'm not from the Hub.}
{144}{}{Then you must know most of the rules. Have a good day. And I am sorry about the bastards part, okay?}
{145}{}{Yeah! Hey, no problem. Bye.}
{146}{}{It's going to cause me some severe mental trauma. Later.}
{147}{}{Hmmm. Okay. It's not our place to ask questions. Have a good day and don't make any trouble.}
{148}{}{Oh, heck. The place for that is Darkwater's. Killian runs it. It's a little to the north. Killian has the best supplies in town.}
{149}{}{Thanks. Bye.}
{150}{}{You wanna show me where you keep YOUR supplies?}
{152}{}{Uh, no. Sorry, lady. I got work to do here.}
{153}{}{Have a nice day.}
{154}{}{Keep out of trouble.}
{155}{}{Boy, I sure hope my replacement gets here soon. It feels like I've been standing guard duty forever.}
{156}{}{I'm sorry, the gates are closed for the night. Come back in the morning.}
{157}{}{Hey, I need to get in!}
{158}{}{No problem. See you in the morning.}
{159}{}{I'm sorry to disturb you, sir, but I would like to enter your town. You can see that I would cause no harm.}
{160}{}{Hunh-huh!}
{161}{}{Come... back... day...}
{162}{}{Sorry, the rules are the rules. No strangers admitted during the night.}
{163}{}{Well, I shouldn't do this, but you seem like a nice enough person. Come on in, but don't make any trouble.}
{164}{}{Hey! It's you! Come on in, }
{165}{}{. Good to see you again!}
{166}{}{Hey, you'd better turn right around and walk back out of here.}
{167}{}{Go on in.}
