{100}{}{You see: Deputy Kenny.}
{101}{}{If you have business with the Hub police, please talk to Sheriff Greene. I only take care of his duties when the Sheriff is unavailable.}
{102}{}{I can't believe the Sheriff is really dead.}
{103}{}{There you are. I've been waiting for you to return. We heard the Sheriff was killed during the battle. It's hard to believe he's really gone. He was like a father to me.}
{104}{}{The Sheriff gave me instructions to carry out in the event that he did not return from the mission. He asked me to give you the remainder of your reward. I believe it was 1000 caps. [The Deputy hands you 1000 caps]}
{105}{}{This city owes you a debt of thanks. I only wish the Sheriff could be here to thank you himself. Goodbye.}
{106}{}{Oh my God! They killed Kenny! Those bastards!}
