{100}{}{The door is locked.}
{101}{}{You pick the lock.}
{102}{}{You attempt to pick the lock, but fail.}
{103}{}{While picking the lock, you manage to tweak the tumblers and jam it.}
{104}{}{The door isn't locked.}

# Fo1in2
{200}{}{ picks the lock.}
{201}{}{ attempts to pick the lock, but fails.}
{202}{}{While picking the lock, }
{203}{}{ manages to tweak the tumblers and jams it.}


