{100}{}{Knight}
{101}{}{I love working on new prototypes.}
{102}{}{When our supplies are limited it can really be a challenge to find a way to use what we've got.}
{103}{}{I can't figure out why my last prototype didn't work.}
{104}{}{Sorry, I can't talk right now.}
{105}{}{Vree's over there.}
{106}{}{Now where did I put that file?}
{107}{}{Where's that schematic?}
{108}{}{Well, the computer says it should work. Now what did I do wrong?}
