{100}{}{You see a heavily-muscled, scarred man with a mustache.}
{101}{}{You see: Lars, Sergeant of the Junktown guards.}
{102}{}{He bears the scars of previous wounds, and looks like an old hand.}
{103}{}{He has scars from knife and bullet injuries. His corded muscles show a man hardened by adversity.}
{104}{}{You know, it's not wise to try to steal from the guards here in Junktown, punk!}
{105}{}{Can I help you, stranger?}
{106}{}{So, what's there to do around here?}
{107}{}{Can you give me the big picture on Junktown?}
{108}{}{Who're you?}
{109}{}{Eergh.}
{110}{}{If you're in charge of the guards here, I think I have some information for you.}
{111}{}{Hey! You! We know about you, you monster!}
{112}{}{Plenty, so long as you stay on our good side. We got Killian Darkwater's store, where you can do some trading. And there's Gizmo's Casino, if you're a gambler. Or if you just want a drink, you can head on over to the Skum Pitt. Just don't get too rowdy.}
{113}{}{Hey, I like a rowdy time!}
{114}{}{Well, you'd best keep yourself under control. We're a free town but we don't tolerate stepping on other people's toes. Don't cause any problems and you won't give cause for me and my men to come down on you.}
{115}{}{What a stick in the mud!}
{116}{}{Look, buddy, my job here is to keep the peace, and if I have to break a few heads to do it, then a few people are going to be hurting. So just watch it.}
{117}{}{Me and my men here work for Killian Darkwater. We keep some order in this town, dealing with all of the murderers, thieves, and other scumbags who come in from the desert. If you want my advice, you'll also stay away from Gizmo. That fathead runs a crooked operation, but we just haven't been able to prove anything. He and his lackeys, the Skulz, are going to take the fall sometime soon, if Killian has anything to say about it.}
{118}{}{What a bummer. No fun here at all.}
{119}{}{Good to know that someone's keeping the peace around here. Thanks.}
{120}{}{So, what keeps you lawboys from just busting Gizmo and the Skulz?}
{121}{}{Hey, it's our job. But it's good to know that someone appreciates it. Thanks.}
{122}{}{Got to do it all proper like. We know that Gizmo runs a rigged operation and all, but we need hard evidence to bring him down. Same with the Skulz; they rough someone up, we bring one or two of 'em in, but nothing changes. We just don't have any direct evidence tying them to any of the killings or muggings.}
{123}{}{Maybe I can help you with that.}
{124}{}{Well, good luck.}
{125}{}{Hell, if you think you can get some dirt on either of them, we'd appreciate the help. Killian's the one to talk to if you want to talk about Gizmo. But if you can get some info on the Skulz, just come back to me and me and the boys will take care of them.}
{126}{}{Thanks. Watch your back.}
{127}{}{I'm the head of the guards here in Junktown. Name's Lars. For that matter, who are you, stranger?}
{128}{}{I'm }
{129}{}{.}
{130}{}{Buzz off, I don't have to tell you anything.}
{131}{}{Welcome to Junktown, }
{132}{}{. What can I help you with?}
{133}{}{Can you fill me in on Junktown?}
{134}{}{Just lookin' for something to do. Got any suggestions?}
{135}{}{Good day, traveler. Do you need something?}
{136}{}{What?}
{137}{}{I'm looking for a little work.}
{138}{}{Just stopping by to say hello.}
{139}{}{I have testimony about the illegal activities that the Skulz were involved in.}
{140}{}{Yes, I'm in charge of the guards here. What do you have for me?}
{141}{}{Nothing, just checking.}
{142}{}{I have some testimony from Sherry that the Skulz are involved in some illegal activities.}
{143}{}{So, you have some info on the Skulz, eh? What can you tell me?}
{144}{}{They're involved in some muggings and killings here.}
{145}{}{I've convinced one of them, Sherry, to testify that they were involved in criminal activity.}
{146}{}{That's great and all, but I can't just jail them all on one person's say-so. I need hard evidence or inside testimony.}
{147}{}{I'll see what I can do.}
{148}{}{I've got testimony from Sherry, a former gang member.}
{149}{}{Excellent. I'll pick her up for a few questions, and I'm sure that I'll get all the information that I need to put them away.}
{150}{}{Look, this isn't a game. People are getting hurt here. If you find some real evidence, come back, but otherwise, don't waste my time!}
{151}{}{If you're not averse to a little skullduggery, I need someone to get some hard evidence on the Skulz, proving that they're involved in illegal activities here. Or you can talk to Killian; he might have some work for you.}
{152}{}{Thanks for your assistance. Junktown's a little safer now, because of your help.}
{153}{}{Move along there, fella.}
{154}{}{ experience for taking a risky turn against the Skulz.}
{155}{}{You ready to help take down Gizmo?}
{156}{}{You bet. Let's nail that tub.}
{157}{}{No, I changed my mind.}
{158}{}{All right, let's do it.}
{159}{}{Well, you'd best wait here so you don't get caught in the crossfire.}
{160}{}{Killian sent me to help run Gizmo out of town.}
{161}{}{Killian sent me. We're going to take Gizmo down.}
{162}{}{Thanks for all your help. Here's 500 caps. You're always welcome in Junktown, friend.}
{163}{}{What? Hmm. We'll see about that. I'll send some men over to ambush them when they try it. You gonna be there?}
{164}{}{No thanks, I've done my good deed for the day.}
{165}{}{Yes.}
{166}{}{The Skulz are planning on killing Neal!}
{167}{}{Lars's men quickly eliminate the Skulz.}
{168}{}{Looks like Lars might still be alive, but he's definitely out of the fight.}
{169}{}{Wanderer, you just screwed up. We needed evidence so that we could take down Gizmo all nice and legal-like. Look, off the record, I'm happy to have that fat fuck out of the picture, but we can't condone murder. You better leave Junktown and never come back.}
{170}{}{We don't like your kind here. You've got about fifteen seconds before I blow your head off.}
{171}{}{Hello again! What can I do for you?}
{172}{}{Uh-huh.}
{173}{}{Nuh-uh.}
{174}{}{ experience for assisting in the elimination of the Skulz gang.}

{970}{}{That is my name.}
{971}{}{You are talking to me.}
{972}{}{That's me.}

{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}

{1000}{}{Killian|Kilian|Sheriff|Sherrif|Mayor}
{1001}{}{Gizmo}
{1002}{}{Junktown|Junk Town|Junk}
{1003}{}{Shady Sands|Shady|Sands}
{1004}{}{Hub}
{1005}{}{Water Chip|Waterchip|Chip}
{1006}{}{Casino|Gizmo's Casino|Gizmo's|Gizmos|Gizmos Casino}
{1007}{}{Store|General Store|Darkwater|Darkwaters}
{1008}{}{Deathclaw|Deathclaws|Claw|Claws}
{1009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid}
{1010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business}
{1011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside}
{1012}{}{Direction|Directions|Whereto|Where to}
{1013}{}{Fallout|Fall out|nuclear fallout}
{1014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev}
{1015}{}{Necropolis|City of the Dead|City of Dead}
{1016}{}{Boneyard|The Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard}
{1017}{}{Story|Stories|Rumor|Rumors|Rumour|Rumours}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{Skuls|Skulz|Skulls|Skullz}
{1020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders}
{1021}{}{Crash|Crash House}
{1022}{}{Beer|Booze}
{1023}{}{Brahmin|Brahmins|Brahma}
{1024}{}{Job|Work|Task|Money}

{1100}{}{Killian is the mayor. He runs a store.}
{1101}{}{He runs the casino. He's a crook.}
{1102}{}{This is Junktown.}
{1103}{}{Umm, I think it is a real small place. I've never been there.}
{1104}{}{It's a larger city somewhere to the south.}
{1105}{}{What? I'm sorry.}
{1106}{}{It's a large building in the northwest part of town.}
{1107}{}{Killian's store? It's in the center of town.}
{1108}{}{I dunno, but the name scares me.}
{1109}{}{If you're hurt, Doc Morbid can surely help you. His clinic is south of here.}
{1110}{}{Killian Darkwater runs the General Store. There you'll probably find what you need.}
{1111}{}{We've got some guards on patrol in the wastes. It's a dangerous place, but we manage.}
{1112}{}{Killian's store is right around the corner. If you're looking for a drink, the Skum Pitt is a to the north of here. There's also Gizmo's casino if you're looking for fun.}
{1113}{}{I'm happy it hasn't been raining like that in a while.}
{1114}{}{They'll hang you if you get caught stealing.}
{1115}{}{The City of the Dead, right? We've only heard some stories and rumors.}
{1116}{}{It's a place somewhere far south for all I know.}
{1117}{}{You know... Stuff.}
{1118}{}{That's our resident bar. The food's okay, but the beer's great.}
{1119}{}{We're keeping an eye on them. Why do you ask? Do you want to cause trouble?}
{1120}{}{Luckily we don't run into much problems with them down here. Heard it's much worse up north.}
{1121}{}{If you need a place to sleep, check with the Crash House.}
{1122}{}{No thanks.}
{1123}{}{We depend on them for trade with the Hub.}
{1124}{}{Talk to Killian. He's our Mayor and might have a job or two for you.}
