{100}{}{You see: Lasher, of the Children.}
{101}{}{I know who you are. You are a wicked, evil man and you must be punished.}
{102}{}{I know who you are. You are the devil in woman's form, but your shape will not save you.}
{103}{}{I know who you are. Your wickedness precedes you. You send the souls of children to Hades, before they can be cleansed of their perfidy. It is a black evil that you do, and you must be punished for it.}
{104}{}{I know who you are. You are walking death, a plague in human form. Where you step, blood flows like a river. But such iniquities can be ended by a righteous soul!}
{105}{}{How dare you disturb me! Don't you know how important my position is? Get out!}
{106}{}{You are unwise to draw your weapon on me. The Master's shield is upon me, and I may not be touched without retribution!}
{107}{}{I wouldn't mind the Master's shield myself.}
{108}{}{Nobody's ever accused me of being wise!}
{109}{}{I just want to speak with the man in charge.}
{110}{}{Nice rod you've got there! Is that why they call you 'Lasher'?}
{111}{}{Is it true that you enjoy abusing children?}
{112}{}{You wanna see unwise? It's unwise to give me lip, bitch!}
{113}{}{Why you talk so funny?}
{114}{}{Why have you come, Initiate? You know that I do not like to be disturbed.}
{115}{}{Forgive me, Father, but I am troubled.}
{116}{}{I seek the guidance of the Cathedral.}
{117}{}{I'm here to talk about your treatment of the Children.}
{118}{}{I just wanted to talk.}
{119}{}{Nice rod you've got there! Is that why they call you 'Lasher'?}
{120}{}{How would you like to never be disturbed again. I can arrange that!}
{121}{}{I dunno. Why I come? You know?}
{122}{}{How dare you enter my sanctuary with a weapon in your hand! Oaf! Get out!}
{123}{}{Who do you think you are, entering my sanctum with a drawn weapon. Get out!}
{124}{}{Forgive me, sir. But the forces of darkness are everywhere, and one never knows when you must defend yourself.}
{125}{}{I seek the guidance of the Cathedral.}
{126}{}{I'm here to talk about your treatment of the Children.}
{127}{}{I just wanted to talk.}
{128}{}{Nice rod you've got there! Is that why they call you Lasher?}
{129}{}{You don't like drawn weapons. You're gonna hate what I do with it next!}
{130}{}{Out? Which way out?}
{131}{}{My quarters are not open to those who have not been consecrated. I must ask you to leave at once.}
{132}{}{Forgive my intrusion, but I have important questions.}
{133}{}{I'm here to talk about your treatment of the Children.}
{134}{}{I wanted to ask you about consecration.}
{135}{}{Nice rod you've got there! Is that why they call you Lasher?}
{136}{}{This place don't look consecrated. I ain't killed anyone here yet.}
{137}{}{You stupid! I got plenty of conse...cra...tion...}
{138}{}{That is a privilege reserved for only the most faithful servants. Only baptism is a higher honor.}
{139}{}{And how does one earn baptism?}
{140}{}{I suppose you are teaching the children and preparing them for baptism.}
{141}{}{Can you help me to be baptized?}
{142}{}{Wow! You must be special!}
{143}{}{Too bad privileges ain't worth a radscorpion's ass when you're dead.}
{144}{}{I see no reason to converse with a fool. Away with you.}
{145}{}{You should speak to Father Morpheus. He is in the tower, but it is unlikely that the Nightkin will allow you to pass.}
{146}{}{Could you persuade the Nightkin to let me pass?}
{147}{}{What can you tell me about Morpheus?}
{148}{}{What can you tell me about the Nightkin.}
{149}{}{Thank you, sir.}
{150}{}{I have ways of getting around these sorts of problems.}
{151}{}{The rod is a holy instrument, through which I instruct my charges. Pain clears the mind of evil thoughts and allows them to better comprehend the glory of the Master.}
{152}{}{I see. So the Master's a pain?}
{153}{}{That's a horrible thing to do to children!}
{154}{}{Sounds kinky. How about trying some on me?}
{155}{}{I instruct the children. It is my duty. All children are wicked beasts. It is my duty to force them to evolve into human beings. Perhaps you have heard that I do not tolerate frivolity. This is true. I want my charges to suffer as much as possible.}
{156}{}{And are mutants more evolved than human beings?}
{157}{}{You heartless bastard!}
{158}{}{You never got laid, did you?}
{159}{}{Tell me more about your teaching methods.}
{160}{}{But what about the pleasure of killing? Ain't that allowed?}
{161}{}{You filthy brainless abomination! How dare you defile my presence! Get out! Out! Now!}
{162}{}{You are a woman, and therefore you are always troubled. It is an endemic condition of your breed. Tell me your problem, madam, and I will resolve it for you.}
{163}{}{If your heart was not so full of wickedness, sir, you would be at ease. A righteous heart knows no cares. Tell me your problem, but be quick!}
{164}{}{Tell me how to attain righteousness!}
{165}{}{I want to know more about the Cathedral.}
{166}{}{I want to know about the Master.}
{167}{}{You're alive. That's my problem, you son of a bitch!}
{168}{}{Learn to embrace pain as your closest friend, for pain is the most instructive force in the universe. Break yourself until you can exist no longer as an individual, then remake yourself into the Master's tool. That is the solution to all of your problems.}
{169}{}{So where can I find the most pain?}
{170}{}{Yeah, I want to get enough brain damage that I'll join a zombie cult! Dream on, pal!}
{171}{}{I would never have thought of that!}
{172}{}{It is? That sucks, pal!}
{173}{}{I already embrace pain. I just like to share it with my friends.}
{174}{}{Beasts chatter without meaning. Human beings think first, and then they talk. You must evolve into a human being before I will wish to speak you. Be gone.}
{175}{}{Your words are true. Very well, I will help you. But be quick.}
{176}{}{I must see Father Morpheus on an urgent matter.}
{177}{}{Tell me about the Cathedral.}
{178}{}{I was wondering where I could find the Master.}
{179}{}{I was wondering about the Children.}
{180}{}{The only thing I know that's quick is Death.}
{181}{}{There comes a time when you must find the answers to life's questions yourself, and that time is now. Begone!}
{182}{}{That is not my duty. Now begone.}
{183}{}{By the endurance of pain, by the acquisition of wisdom, and the performance of service. Pain is knowledge, wisdom is obedience, and service is courage. }
{184}{}{[More]}
{185}{}{You must reject the Light that nearly destroyed us all, and pledge yourself to the Darkness in which all are equal. Now that I have told you this thing, go seek it. Seek the Master and his wisdom.}
{186}{}{I have not consulted him, but I am certain he is pleased with the righteous souls I have brought him. It is difficult work, but I do it well. Unfortunately, it is also quite time consuming, which is why I must order to you to leave right now.}
{187}{}{A flatterer's tongue is in the mouth of a devil! A devil such as you! Get out of my sight!}
{188}{}{You foul mouthed beast! Begone! Learn some manners before you return.}
{189}{}{A reasonable request. Take this symbol. Show it to the Nightkin when you wish to pass.}
{190}{}{I cannot help you with that. Begone.}
{191}{}{He is our leader. He is close to the Master's counsels and knows many of his purposes. Is that all?}
{192}{}{Could you persuade the Nightkin to let me pass?}
{193}{}{Tell me more about Morpheus?}
{194}{}{What can you tell me about the Nightkin?}
{195}{}{Thank you, sir.}
{196}{}{So why do you follow this Morpheus bozo?}
{197}{}{They serve the Master. They bring the pain of healing to the world. Angels in the Night, who redeem the world by bloodshed. Curiosity is a foolhardy emotion, but doubly so when it comes to the Nightkin. That is your only warning. I have much to do now. Away with you.}
{198}{}{Your courtesy does you credit. Perhaps you are worthy to talk with Morpheus. If the Nightkin stops you, show them this symbol. Now, away with you!}
{199}{}{You are a fool if you think petty subterfuge will defeat the Nightkin. Get out of here!}
{200}{}{Decadence and ease prevents evolution, evolution that is necessary for survival in a harsh world. Fortunately, I am a hard man who cares nothing for seductive pleasures. I see that you disagree with me. I do not care about your opinion. Get out of here!}
{201}{}{Mutation is nothing to fear. Every birth is a mutation of our parents' DNA. We are all mutants. The only thing that matters is that the mutant is guided on a moral and productive path. This is my job. And this also ends this discussion. Leave me now.}
{202}{}{I deal out pain. If the animal is worthy and can learn from it, it evolves into a righteous soul. If it does not, it does not deserve to exist. On rare occasions, the animal is removed the genetic pool, although not as often as I would like. This happens more often with failed grown animals.}
{203}{}{And the Master approves of the teaching methods?}
{204}{}{You're a monster!}
{205}{}{I think I'll leave you now.}
{206}{}{Do you teach adults?}
{207}{}{Grown animals?}
{208}{}{Hey, I can remove them for you! No one else needs to know!}
{209}{}{You are an evil girl. You would do well to tread carefully here. The Nightkin do not enjoy rivals. Now begone!}
{210}{}{You are an evil man. You would do well to tread carefully here. The Nightkin do not enjoy rivals. Now begone!}
{211}{}{Righteousness is attained through struggle, trauma, and recovery. We are animals who must be continuously be broken until we accept the Master's truth without hesitation. Now that you have heard the truth, seek it with the body of your experiences. Get out of here.}
{212}{}{Your tongue is a wicked thing that is beyond redemption. Get out of my sight!}
{213}{}{The Cathedral teaches many things which an undisciplined mind is incapable of comprehending. Now I have other duties to perform. Away with you!}
{214}{}{As do I. It appears we have many things in common, but unfortunately, you irritate me beyond my ability to tolerate. Get out of here. Now.}
{215}{}{It is not my place to judge. You must persuade the Nightkin. Good luck. You will need it.}
{216}{}{The Cathedral is a sanctuary for the human race. When the apocalypse fell on this foul city, the Cathedral was spared, which allowed for the birth of the Master. Thus a healing darkness emerged from a terrible light.}
{217}{}{ When I came, I saw this place lacked a moral center, and so I have endeavored to administer teaching pain to a place once consumed with idle pleasure. That is all you need to know.}
{218}{}{It is said the Master waits below, in the Darkness, for the Light above betrayed mankind and nearly destroyed us. But many bless the Light, for they say it birthed the Master.}
{219}{}{ I do not know these things with certainty, and I have never had the privilege to see him. Now if you will excuse me, I have work to do.}
{220}{}{You were not particularly welcome here in the first place. Good riddance to you.}
{221}{}{Once I did, but many of methods were abandoned in favor of the loud noises you hear in the Auditorium amphitheater. It is a source of bitterness for me. Fortunately, I can still instruct the children. Now if you will excuse me, I have to prepare for their lessons.}
{222}{}{Uh... it is of course, a rare event, and the animal is given every chance to evolve. Now leave here! Leave here at once!}
{223}{}{[Done]}
{224}{}{This may be of some use to you. Take this symbol. Show it to the Nightkin when you wish to pass. It will allow you to see Father Morpheus.}

# Weapon-drawn timer is up, let's attack:
{250}{}{I told you to get out!}
