{100}{}{You see: Laura.}
{102}{laura0m}{Hello, my brother. May I be of service this glorious day?}
{104}{laura0f}{Hello, my sister. May I be of service this glorious day?}
{105}{}{Are you Laura?}
{106}{}{Can I ask you a few questions about the Children?}
{107}{}{What kind of "services" do you offer?}
{108}{}{Mom?}
{110}{laura1a}{That's very sweet of you, but no, I'm not. I'm sure you can find her somewhere else.}
{112}{laura2}{I most certainly am. Did you want something?}
{113}{}{Nicole sent me to talk to you.}
{114}{}{Uh... no. Never mind.}
{116}{laura3}{Nicole? I'm so sorry. I don't believe I know anyone by that name.}
{117}{}{Well, she told me to tell you 'Red Rider'.}
{118}{}{Sure you do! She sent me!}
{120}{laura4}{I'm sorry. I... I just don't know. Follow me to a place where we can talk.}
{122}{laura9}{I'm terribly sorry for your inconvenience. I hope it doesn't upset you.}
{124}{laura10}{Are you... certain? Uh... excuse my curiosity, but you seemed to be looking specifically for me.}
{125}{}{Well, Nicole sent me.}
{126}{}{Just heard about you and wanted to see what you looked like.}
{128}{laura11}{I... I'm sorry, but that sort of attention makes me a little nervous. Don't know why, it's silly of me, I know. Well, enjoy your walk.}
{130}{laura14}{Oh, I'm hardly an authority. You should see Morpheus, the High Priest. I'm sure he can help you much more than I.}
{132}{laura15}{But I only meant... oh... I have to go now.}
{134}{laura16g}{Well, hello again! Are you just walking or may I help?}
{136}{laura16b}{Is there... something I can help you with?}
{137}{}{Are you Laura?}
{138}{}{Can I ask you a few questions about the Children?}
{139}{}{Nothing, thanks.}
{140}{}{Uh, Mom?}
{142}{laura16a}{No. We already talked about this. You'll have to go somewhere else my friend.}
{144}{laura21}{Oh... I'm glad you found me. Nicole sent a list with the information I was supposed to find.}
{145}{}{So what did you get?}
{147}{laura22}{Um. There's so much I'm just... I'm not sure what you need or where to start. Is there something in particular you want to know about?}
{148}{}{Is there a secret entrance into the Inner Sanctum of the Church?}
{149}{}{What have you learned about The Master?}
{150}{}{What are the Children's plans?}
{151}{}{What's a nice girl like you doing in a place like this?}
{152}{}{Nothing more, thanks.}
{154}{laura24}{It's not the Inner Sanctum you want to enter.}
{155}{}{Then what?}
{157}{laura25}{I followed Morpheus down a back secret staircase. The guy activates a secret door at the bottom.}
{158}{}{Then what?}
{159}{}{Can you show me this door?}
{161}{laura26}{He uses this strange key to open it and disappears. I've never tried to follow him.}
{162}{}{Do you know where this key is?}
{163}{}{Why not?}
{165}{laura27}{Well, I'd say he keeps it on him.}
{166}{}{Will you show me the door now?}
{168}{laura28a}{Well, of course.}
{169}{}{Great. Let's go.}
{170}{}{Can I ask you a few more questions first?}
{172}{laura29}{Follow me.}
{174}{laura30a}{Okay, but we have to hurry.}
{176}{laura30b}{Oh, make it quick.}
{178}{laura31}{Believe me, if you've seen the Nightkin, you'd know why. Unless you're stupid.}
{179}{}{Maybe I am, but I'm not scared.}
{180}{}{I can understand that. Can we get back to the questions?}
{182}{laura32}{Oh, I see that's real funny. Lookit, I'm in the middle of this day in and day out. You have a problem with how I do this, you just keep it to yourself. Ya got it?}
{183}{}{What are you going to do, whine some more?}
{184}{}{If that's how you want it.}
{185}{}{You're right, I'm sorry. How about we get back to business?}
{187}{laura33}{Uh, not much. The Children worship him, and sometimes a huge vision of him appears in the main nave of the church.}
{188}{}{So he's real?}
{189}{}{Sounds scary.}
{191}{laura34}{Yes and no. I snuck up to the front one day and I found a strange mechanical device with a lens under the altar.}
{192}{}{Probably a holo-projector of some kind.}
{193}{}{So?}
{195}{laura35}{Huh... believe me, it was at first, but then I snuck up and looked at the altar when nobody was looking. And there's a device underneath with wires and a big lens.}
{196}{}{Probably a holo-projector of some kind.}
{197}{}{So?}
{199}{laura36}{So I'm pretty sure this Master is flesh and blood. And I also think I know where he is.}
{200}{}{Where?}
{202}{laura37}{Every once in a while, Morpheus will go through a secret staircase leading below the Church. And he enters a secret door with some kind of a key. I think the Master is down there.}
{203}{}{Can you show me this staircase right now?}
{204}{}{Do you know where this key is?}
{206}{laura38}{Now that's scary. Morpheus is preaching that the earth should be 'purged of the infidels,' and other crap like that. I think they're planning to take over everything!}
{207}{}{Can they do it?}
{208}{}{What's their first target?}
{210}{laura39}{Now you know, it could be. I mean, they have enough members, and the different hospitals in the towns are stocked full of weapons and explosives.}
{211}{}{We must tell the Followers.}
{212}{}{What are you going to do?}
{214}{laura40}{I was planning on it. In fact, after we're done, I'm heading over there.}
{215}{}{One quick question?}
{216}{}{I'll let you go then.}
{218}{laura41}{Okay. Good luck!}
{220}{laura42}{Well, I'm going to go warn Nicole. And hopefully, the Followers can send help to the other towns.}
{221}{}{I'd like to ask a few more questions first.}
{222}{}{Okay, I'll let you go then.}
{224}{laura43}{Adytum, that town doesn't have a chance in hell.}
{225}{}{What about the Followers?}
{226}{}{Can I help Adytum?}
{228}{laura44}{The Children don't think we're enough of a threat. We'll show 'em.}
{229}{}{Good. What do you plan to do?}
{230}{}{Can I help Adytum in any way?}
{232}{laura45}{Yeah, you can help 'em by getting to the Master. 'Bite the head off the snake and it won't coil around you,' as my grandmother used to say. She was kind of a handful.}
{233}{}{How do I get to him?}
{234}{}{Sound it. I need some more answers before you go.}
{235}{}{I'm on my way.}
{237}{laura46}{They plan to take over all the towns!}
{238}{}{Which ones?}
{240}{laura47}{Adytum's already fallen. The Hub is next.}
{241}{}{What're the Followers doing during this?}
{242}{}{Damn. What can I do?}
{244}{laura48}{We sent a group to help Adytum, and they were all wiped out. Nicole sent another one to the Hub. I just hope they get there in time.}
{245}{}{Damn. What can I do?}
{247}{laura49}{They've already taken out the Hub and Adytum! I think the Followers are next, so we're preparing our defense.}
{248}{}{Why are you here then?}
{249}{}{What can I do?}
{251}{laura50}{I'm here to keep an eye on the Children.}
{252}{}{What can I do?}
{254}{laura51}{The Children are setting up hospitals all over the place. Hmpf. I think they're trying to get people to trust them.}
{255}{}{Is it working?}
{256}{}{Is there anyway to stop them?}
{257}{}{That's the stupidest thing I ever heard!}
{259}{laura52}{Ah, it sure looks that way. I mean, people are flocking to their church. Can't they see it's a fake?}
{260}{}{You sure it is?}
{261}{}{How can I stop them?}
{263}{laura53}{For one thing, people seem to disappear a lot around here, while the number of Nightkin are slowly growing.}
{264}{}{Why?}
{265}{}{Doesn't look good. But I need more answers before I act.}
{267}{laura54}{I don't know. That's what you're here to find out, right?}
{269}{laura55}{Find the Master and stop him!}
{270}{}{What have you found out about this Master?}
{271}{}{I will.}
{273}{laura56}{Huh, I sure as hell hope so. Now, any more questions? }
{275}{laura57}{Actually, it's a good way to manipulate people, and this Master is damn good at it.}
{276}{}{No, I meant that's the stupidest thing I've heard from you. You're paranoid, aren't you?}
{277}{}{Well, I'll stop him.}
{278}{}{How can I stop this?}
{280}{laura58}{Excuse me?}
{281}{}{You heard me.}
{282}{}{Never mind.}
{284}{laura59}{Okay then. Good luck!}
{286}{laura60}{Uh heh... Waiting desperately for someone to use that pathetic line on me.}
{288}{laura61a}{So, what can I do for you now?}
{290}{laura61b}{Oh, what now?}
{291}{}{I need to ask you a few more questions.}
{292}{}{Nothing, thanks.}
{294}{laura62}{What are you doing? Put that down!}
{296}{laura63}{Hey! Get out of here!}
{297}{}{Or else what?}
{298}{}{Sorry, I'll go now.}
{300}{laura64}{Stop that!}
{302}{laura65}{What... what are you doing in here? You need to leave!}
{303}{}{No, you get out!}
{304}{}{Okay, I'll go.}
{306}{laura67}{Uh... I'm not sure about that. Go talk to Nicole.}
{308}{laura67a}{I'm not sure about that. Go talk to a High Priest.}
{309}{}{Well, as I said... }
{310}{}{I said... }
{311}{}{Well, as I said before... }
{312}{}{As I said before... }
{313}{}{Well, I'm quite certain I told you this already, but... }
{314}{}{Okay! I already told you this... }
{315}{}{Ah, once more? Well, I said... }
{316}{}{Again? I already said this... }
{317}{}{Oh dear, this is most disturbing. I simply will not say it again.}
{318}{}{Are you... Okay! Okay! Are you deaf? Read my lips, I'm not gonna to say this again.}
{319}{}{I believe that's quite enough. I'll not say it again.}
{320}{}{Not listening, huh? Too bad, I'm not gonna say it again.}
{321}{}{Oh, those are dreadful people. I'm not going to talk about them at all!}
{322}{}{Nicole probably told you about us. We're trying to knock some sense into those thick-skulled, gun-toting, violence-mongering nitwits
... Oh, present company excluded, of course.}
{323}{}{Well, I don't know who you're talking about.}
{324}{}{She leads the Followers. Pretty strong-willed. I trust her.}
{325}{}{The others are all so nice! It's wonderful here. We belong, we do good work... }
{326}{}{Oh, they're like a... blight on the world. Most are a waste and a few are just plain evil.}
{327}{}{Adytum, isn't that a town west of here?}
{328}{}{Adytum's a bit west from here. And the people there
... well, they're a little paranoid, so don't expect a hospitable welcome.}
{329}{}{Oh, he's wonderful. He leads us. You should talk to him!}
{330}{}{He preaches peace and enlightenment and all that crap, but he's scum. No two ways about it.}
{331}{}{Oh, I can't begin to describe him. Morpheus leads us. He can do justice to your question.}
{332}{}{Ah yes, the Master, he's the god these nuts worship. Personally, I don't think he's a god, just somebody into manipulating everyone.}
{333}{}{Nightkin? I don't know what you're talking about.}
{334}{}{They're the big, ugly enforcers of the Master and Morpheus.}
{335}{}{The what?}
{336}{}{What, you couldn't figure out that's the Master?}
{337}{}{It's the big place at the north end of the church, where Morpheus does all his ceremonies. I've been there, it's wonderful!}
{338}{}{It's at the north end of the church. I've watched Morpheus perform his little circus act there.}
{339}{}{Oh, you cannot go there. That's where Morpheus contemplates.}
{340}{}{That's where Morpheus and his cronies hang out. No one's allowed up there, though.}
{341}{}{They have proven themselves to the Church. The rest of us aspire to that.}
{342}{}{Oh yeah, these are the guys who've survived torture and who knows what else. Totally brainwashed and will do anything they're told.}
{343}{}{They are the High Priests.}
{344}{}{Ah, those are the High Priests. So far I think there's only thirteen, but I'm not really sure.}
{345}{}{That's not important.}
{346}{}{That's not important.}
{347}{}{I'm sorry. I simply don't have time for this.}
{348}{}{We don't have time to talk about that! Just keep to business.}
{349}{}{I'm not sure why you want to talk about that.}
{350}{}{Keep to the subject at hand, friend.}

# added by WG from genchat
{477}{}{Please, we must hurry. We don't have time to speak.}
{478}{}{Only Morpheus has the key to this door. I must leave now to let Nicole know what is going on here.}
{479}{}{Please, I have to get away from here before they find out who I am.}
# added by WG
{480}{}{Only Morpheus has the key to this door. I must leave now.}

# Fo1in2
{499}{}{You should leave now. I can handle the rest on my own.}



#
# Laura Tell-Me-Abouts
#


{1000}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{1001}{}{Nicole}
{1002}{}{Children of the Cathedral|Children|Cathedral|CoC}
{1003}{}{Morpheus}
{1004}{}{Master}
{1005}{}{Nightkin|Nightkins}
{1006}{}{Dark|Dark God|God}
{1007}{}{Auditorium}
{1008}{}{Sanctum}
{1009}{}{Servitors|Servitor}
{1010}{}{Order|High Order}
{1011}{}{Apocalypse}
{1012}{}{God}
{1013}{}{Mutants|Mutant}

{1100}{laura74}{Oh, those are dreadful people. I'm not going to talk about them at all!}
{1101}{laura75}{Well, I don't know who you're talking about.}
{1102}{laura76a}{The others are all so nice! It's wonderful here. We belong, we do good work... }
{1103}{laura78}{Oh, he's wonderful. He leads us. You should talk to him!}
{1104}{laura79}{Oh, I can't begin to describe him. Morpheus leads us. He can do justice to your question.}
{1105}{laura80}{Nightkin? I don't know what you're talking about.}
{1106}{laura81}{The what?}
{1107}{laura82}{It's the big place at the north end of the church, where Morpheus does all his ceremonies. I've been there, it's wonderful!}
{1108}{laura83}{Oh, you cannot go there. That's where Morpheus contemplates.}
{1109}{laura84}{They have proven themselves to the Church. The rest of us aspire to that.}
{1110}{laura85}{They are the High Priests.}
{1111}{laura74}{Oh, those are dreadful people. I'm not going to talk about them at all!}
{1112}{laura81}{The what?}
{1113}{laura80}{Nightkin? I don't know what you're talking about.}

