{100}{}{Oh no.}
{101}{}{You tripped a laser wire, setting off some type of defense mechanism. You take 1 point of damage.}
{102}{}{You tripped a laser wire, setting off some type of defense mechanism. You take }
{103}{}{ points of damage.}
{104}{}{You tripped a laser wire, setting off some type of defense mechanism.}

{105}{}{ has tripped a laser wire, setting off some type of defense mechanism.}
