{100}{}{You see a nervous ghoul with an air of authority.}
{101}{}{Thank you for not shooting first. Can I help you with anything?}
{102}{}{Yes, I'm looking for water.}
{103}{}{Sure, who are you?}
{104}{}{Nah.}
{105}{}{Ahh, if you like you may rest here, we will not harm you.}
{106}{}{Ahh.}
{107}{}{I am the leader of a simple people who have left the surface because of the others.}
{108}{}{Who has forced you down here?}
{109}{}{Geez, that's pretty dumb.}
{110}{}{Hmm. Okay. Bye.}
{111}{}{The surface of Necropolis and the water is controlled by Set and his ghouls. We are a much more peaceful group - which disgusts Set.}
{112}{}{Who is this Set?}
{113}{}{Well, I've taken care of Set. He won't bother you further.}
{114}{}{How then do you survive down here without water?}
{115}{}{Well I sure wouldn't like a bunch of pansies either, Set sounds like an okay guy.}
{116}{}{Set is a ghoul like us, but has assumed a certain amount of power in the above ground world. He is an oaf.}
{117}{}{He sounds a lot more interesting than you freaks.}
{118}{}{Why does he let you survive down here?}
{119}{}{He does not speak of it, however Set is afraid of not having enough people to defend Necropolis if it ever needed it. So, he gives us what water we need.}
{120}{}{Where does all of this water come from?}
{121}{}{I need water for my people! If you know where he gets it from, tell me now!}
{122}{}{I am looking for a Water Chip, to give my people the water they need. Do you know where I might find one?}
{123}{}{I wouldn't keep you guys around to defend a paper bag. So what's this about water?}
{124}{}{Up until recently we pumped our water from the ground, with a pump in the Watershed.}
{125}{}{Until recently? What has happened that changed things?}
{126}{}{How do I get to the Watershed?}
{127}{}{What is the Watershed?}
{128}{}{Since our pump stopped working, we have been getting our water from a place under the ground. I have heard that a water computer is being used to purify the water.}
{129}{}{Thanks.}
{130}{}{Where is that?}
{131}{}{The Watershed is to the north. You'll need to take the sewers to get there.}
{132}{}{You aren't thinking of taking the Water Chip from us are you?}
{133}{}{Umm... Me, no, I would never do such a thing. I am just going to see how it all works.}
{134}{}{Of course. My people need the Water Chip to survive.}
{135}{}{Why?}
{136}{}{If you take the Water Chip from us, then we will all die. With our water pump broken we need it to survive.}
{137}{}{Well, I really don't care about you and your people. We need the Water Chip for our own survival. Goodbye.}
{138}{}{Is it possible that your pump could be fixed?}
{139}{}{If that is the case then I can't let you leave my presence alive.}
{140}{}{I do not think that I believe you.}
{141}{}{I am sorry I did not mean to deceive you. What is wrong with taking the Water Chip?}
{142}{}{Well I don't really care. If you won't get out of my way, I'll just remove you myself.}
{143}{}{That may be difficult. The parts needed to fix the pump were lost in the sewers under the Watershed.}
{144}{}{Why is that so difficult?}
{145}{}{Do you mean these parts? [You show the parts you found to the ghoul leader]}
{146}{}{The sewers there are filled with monsters, and none of my people that I have sent to retrieve them have come back. Are you willing to retrieve the parts, so that the water pump can be fixed?}
{147}{}{Sounds like too much trouble; I think I'll just take the Water Chip.}
{148}{}{Yes.}
{149}{}{Since you guys are too incompetent to do this yourself, I guess I'll have to lend a hand.}
{150}{}{Thank you. When you get the parts, return here. It is possible that I can help you further.}
{151}{}{Okay, I'll be on my way then.}
{152}{}{Have you found the parts for the water pump yet?}
{153}{}{Not yet.}
{154}{}{Nope. And I've decided to forget the whole thing.}
{155}{}{Where was I supposed to find them again?}
{156}{}{Well I wish you luck then.}
{157}{}{You have returned. Do you have the parts needed to repair the water pump?}
{158}{}{Yes, here they are.}
{159}{}{Yeah, but I've decided to forget about fixing the water pump.}
{160}{}{Well it looks like you may need some help with the parts. Here are some books that we have found littered around. They may help you. Now please take the parts to the Watershed and repair the pump.}
{161}{}{Unfortunately I will be able to help you no further. Good luck with the water pump. Please take the parts to the Watershed and repair the pump.}
{162}{}{Have you fixed the water pump yet?}
{163}{}{No not yet, but I am still working on it.}
{164}{}{No, and I am not planning on it now.}
{165}{}{Yes those are the parts I was talking about. Thank the flow that you already have them.}
{166}{}{Is there anything else I should know?}
{167}{}{Well that's as close as they are going to get to the water pump.}
{168}{}{As I already told you, they can be found in the sewers underneath the Watershed. Go east from here, and then north. You will find the Watershed in that direction.}
{169}{}{Thanks for the directions. Goodbye.}
{170}{}{Well thank you for that service. Was there something else you wanted to know?}
{171}{}{How do you survive down here without water?}
{172}{}{It is where all the water is stored and handed out to us.}
{173}{}{Where is it located?}
{174}{}{Lately I have heard rumors that someone has taken over the control of the Watershed. However, our rations are still being delivered for some reason.}
{175}{}{How do I get to the Watershed?}
{176}{}{What is the Watershed?}
{177}{}{Thank you for repairing the water pump, and I hope all is well with your people when you return with what you have found.}
{178}{}{Thank you for your help. Goodbye.}
{179}{}{You have fixed the water pump and the flow has returned from the deep. However, I see you have not found what you are looking for.}
{180}{}{Yes, I cannot seem to find the location of the Water Chip.}
{181}{}{I have heard that it is located deeply below the Watershed. I wish you luck in searching for it.}
{182}{}{I see that you have what you came here to find. You realize that we will die if you take the Water Chip from us.}
{183}{}{Yes, but I am still working to fix the water pump. Where did you say I could find the parts?}
{184}{}{I need the Water Chip and I don't have time to deal with your problems.}
{185}{}{What other options do I have?}
{186}{}{I am tired of putting up with your snide remarks. I do not wish to speak with you any further.}
{187}{}{We once had a pump located in the Watershed that pumped the flow from the deep. However, it was broken and the parts needed to fix it were lost in the sewers directly below the Watershed.}
{189}{}{Why have you not retrieved the parts yourself?}
{190}{}{You have nothing to fear from us!}
{191}{}{I will speak with you before you leave.}
{192}{}{You have left me no choice, but to stop you myself.}
{193}{}{Wait, don't shoot!}
{194}{}{You have nothing to fear from us!}
{195}{}{I will speak with you before you leave.}
{196}{}{You have left me no choice, but to stop you myself.}
{200}{}{Tough luck.}
{201}{}{Can't the water pump be repaired?}
{202}{}{I'm sorry but my people need the chip to survive.}
{203}{}{Please don't take our chip. Without it we will die.}
{204}{}{Maybe, but the parts are lost in the sewers beneath the Watershed. With all those monsters there, we can't get them back.}
{205}{}{Sorry, I wish I could help.}
{206}{}{I'll find the parts.}
#
#  by Sduibek for Fallout Fixt:
#
{300}{}{You see: Undergrounder Leader.}


############ Tell Me Abouts

{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}

{1000}{}{Set}
{1001}{}{Master}
{1002}{}{Water}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Necropolis}
{1006}{}{Chip}

{1100}{}{He tries to control Necropolis, and has forced us under ground.}
{1101}{}{He has something to do with the Mutants. I don't know much more.}
{1102}{}{We get our water from the place under the Watershed. It might have something to do with that.}
{1103}{}{The broken water pump is there. Also, that's where the Mutants hand out the water from their new source.}
{1104}{}{Set's so-called palace.}
{1105}{}{City of the Dead, where we would like to live peacefully, if Set or the Mutants will let us.}
{1106}{}{We get our water from the place under the Watershed. It might have something to do with that.}


