{100}{}{You see a shifty-looking character.}
{101}{}{Pssst! Come 'ere.}
{102}{}{So'a, whatcha doin' in the Hub?}
{103}{}{I don't really see where that is any of your business.}
{104}{}{Why?}
{105}{}{Looking for something that I need.}
{106}{}{Where my Mommie?!?}
{107}{}{Not really sure big fella. I'll see ya around.}
{108}{}{Ahh.}
{109}{}{No sweat off my back. Just seein' if I could be neighborly like. [Lemmy turns away]}
{110}{}{Well, you look like a businessman. And I'm a businessman, and I thought we could, ah, discuss, ah, business.}
{111}{}{Well, what do you do around here?}
{112}{}{I think I'm just going to give you the business!}
{113}{}{I don't think I want to have anything to do with your 'business'.}
{114}{}{Well, we all got needs. I might be able to help with some of 'em. So what sort of needs do you got?}
{115}{}{Well, I'm really looking for a Water Chip. I need to get one back to my people.}
{116}{}{Needs, huh? I understand needs, but what might you know about satiating these needs?}
{117}{}{I have need of some information.}
{118}{}{I certainly don't need anything you might be talking about.}
{119}{}{I do a little bit of this, and a little bit of that. I get things and information for people, whatever they might need or be lookin' for.}
{120}{}{Well, I do need some things.}
{121}{}{Anything you can tell me about specifically?}
{122}{}{I'm looking for a Water Chip. You wouldn't happen to have one, would you?}
{123}{}{I'll see you later.}
{124}{}{Water Chip, hmmmm. Don't think I've heard of one of those things. If I's was you, I'd try the Water Merchants. They got a grip on all the water around here.}
{125}{}{So what do you do around here?}
{126}{}{So what else might you know about?}
{127}{}{Thanks for the information.}
{128}{}{Not a problem. If there's anything else you might be wanting, you come and talk to Lemmy first.}
{129}{}{So, you're lookin' for information, huh? Being a respectable businessman, I gots overhead, so I'll need a few caps to tell you what you need to know. Now that we got that straight, whattcha' wanna' know about?}
{130}{}{So, you think I might know a little more about those Water Chip things, huh? Well, you might be right. It's gonna' cost you, though. I think 500 bottle caps oughta' do it.}
{131}{}{Alright, what's the info?}
{132}{}{I'll give you 400 instead.}
{133}{}{I think you need to tell me, right now, and without the freakin' caps!}
{134}{}{Too rich for my blood.}
{135}{}{Now, now. I wouldn't be the man I am if I gave information away for less than it's worth. Come back when you've got the caps.}
{136}{}{Trying to intimidate poor old Lemmy, huh? Well, I's not afraid of the likes of you. I'll just be seein' you around.}
{137}{}{[Lemmy takes your money]}
{138}{}{Well, that's fair enough. I'll take that instead.}
{139}{}{Okay, okay, okay, see I was just kidding about paying for the info. Good joke, huh?}
{140}{}{Well, so here's what I know about the Water Chips. The thing I've heard is that they all used to come from the Vaults. So if I was lookin' for one, I'd find out where the rest of these Vaults were. I'm not sure where all the Vaults are exactly, but I've heard that there are about 4 around here somewhere's.}
{141}{}{I want to ask you a few more questions.}
{142}{}{Thanks.}
{143}{}{Sure, what else do you want to know about?}
{144}{}{Anything you know about Water Chips that you can tell me?}
{145}{}{What do you know about Decker?}
{146}{}{Do you know anything about the missing caravans?}
{147}{}{Well, I'm looking for a certain commodity, if you know what I mean.}
{148}{}{Nothing right now.}
{149}{}{Now, normally I don't mind selling information, but you're not gonna' get anything outta' Lemmy about Mr. Decker.}
{150}{}{Okay, but can I ask you about some other things?}
{151}{}{Thanks.}
{152}{}{Missing caravans, huh? Well, I might be knowin' a bit about those. It's gonna cost you 300 caps, though.}
{153}{}{Alright, what do you know?}
{154}{}{I'll give you 240.}
{155}{}{I think you need to tell me, right now, and without the freakin' caps!}
{156}{}{Too rich for my blood.}
{157}{}{Well, I'm not really that sure, but what I's heard is that it ain't what everybody thinks. Some new guy is getting into the action with some kind of mutants or something. But don't quote me on that.}
{158}{}{Figures. Is there anything I can quote you on, Lemmy?}
{159}{}{Can I ask you another question?}
{160}{}{Thanks.}
{161}{}{Now, you might be insinuating that Lemmy ain't a stand-up guy. Well, you's right. But Lemmy is an ALIVE type of guy.}
{162}{}{Okay, forget about it. Can I ask you another question?}
{163}{}{Well, I'm going to make you a lying down and not breathing type of guy!}
{164}{}{Forget about it. See ya'.}
{165}{}{Stuff for needs, huh? Well, I knows a guy over in Old Town that can probably fix you up with some stuff like that. But you know what? He needs to know who you are before you show up at his doorstep.}
{166}{}{Let me guess. This 'invite' is going to 'costs' me?}
{167}{}{I can see where this is going. I'll find him on my own.}
{168}{}{Exactly. So I'm thinking... only for you of course... 1000 caps so youse can talks to this guy without him blowing your head off first.}
{169}{}{Alright, I'll pay your price.}
{170}{}{How about 800 caps instead?}
{171}{}{Because you like me so much Lemmy, why don't you just do it for free? [As you flex your muscles]}
{172}{}{Can't afford that.}
{173}{}{Well, what you gotta' do is find your way over to Old Town. Over there is a guy named Vance. Just talk to him. Like I said, I'll let him know you're coming.}
{174}{}{You're all heart. Can I ask you a few more things?}
{175}{}{Thanks.}
{176}{}{Sorry man, got things to do. Nice chattin' with you, though.}
{177}{}{Well, you've come back to talk to your old friend Lemmy, huh? What's it I can help you with?}
{178}{}{Well, you look like a businesswoman. And I'm in business, so I thought we could, ah, discuss, ah, business.}
