#
#from GENLOCK.MSG
#
{100}{}{The container appears to be locked.}
{101}{}{You successfully pick the lock.}
{102}{}{This lock is beyond your ability to pick.}
{103}{}{You fail to pick the lock.}
{104}{}{The locker is already unlocked.}
{105}{}{You break your picks in the lock!}
{106}{}{You deftly pick the lock.}
#
#from LOCKER.MSG
#
{107}{}{The locker is locked.}
{108}{}{You broke your lockpicks.}
{109}{}{You unlock the locker.}
{110}{}{You fail to unlock the locker.}
#
# new for Fallout Fixt
#
{111}{}{The blast completely destroys the lock.}
{112}{}{The container is destroyed by the blast!}
