{100}{}{You see: Lorenzo.}
{101}{}{Sir, this is a respectable establishment. We don't do business with your kind. Go away.}
{102}{}{Maam, this is a respectable establishment. We don't do business with your kind. Go away.}
{103}{}{You're overdue on your loan. Please pay it now or I will become very upset. I dislike being upset.}
{104}{}{Don't threaten me, pal. You're not the only one with friends.}
{105}{}{I need more time. Please!}
{106}{}{I want to pay off my loan of }
{107}{}{ caps.}
{108}{}{I don't have it with me.}
{109}{}{Hi. So you've come to pay off your loan?}
{110}{}{Actually I was hoping you could share some information...}
{111}{}{I came for another loan.}
{112}{}{Maybe later.}
{113}{}{Runk?}
{114}{}{I warned you never to come back here. Okay boys, you know what to do!}
{115}{}{Well, if it isn't a potential customer! I'm Lorenzo the Munificent, at your service. I give out loans. Only ten percent daily interest, a maximum of ten days to repay. You won't find a more generous lending institution anywhere in the Hub!}
{116}{}{I came for a loan.}
{117}{}{You sound like a rip-off artist to me!}
{118}{}{Well, I suppose. What do you need to know about?}
{119}{}{What about those missing caravans?}
{120}{}{Tell me about Decker.}
{121}{}{What about the local police?}
{122}{}{What about the Children of the Cathedral?}
{123}{}{Tell me about yourself.}
{124}{}{Where does a person find work around here?}
{125}{}{Sorry. I don't do rumors. Don't ask me again.}
{126}{}{I warned you I don't do rumors. If you think I was just blowing smoke, you're wrong. Get out of here and don't come back, punk.}
{127}{}{Sorry pal, but I don't do more than one loan at a time. You want more, you gotta start paying. This is a business, not a charity.}
{128}{}{Fine. A pleasure doing business. Anything else?}
{129}{}{Idiot! You don't have enough to pay it off! Maybe you were thinking of something else...}
{130}{}{Actually I was hoping you could share some information...}
{131}{}{I came for another loan.}
{132}{}{Maybe later.}
{133}{}{Sure! Feel free to drop on by. We're always willing to help.}
{134}{}{Why don't you go run along and runk somewhere else. Get out of here! And don't come back.}
{135}{}{Hey, no threats! We're all civilized around here. Guido, Leone, why don't you show this gentleman how civilized we can be.}
{136}{}{Hey, no threats! We're all civilized around here. Guido, Leone, why don't you show this lady how civilized we can be.}
{137}{}{Time's up, pal. Guido, Leone, why don't you boys entertain me for a minute...}
{138}{}{You're lucky, friend.}
{139}{}{Actually I was hoping you could share some information...}
{140}{}{I'd like another loan.}
{141}{}{Maybe later.}
{142}{}{You don't have enough! How dare you try to cheat me! Guido, Leone, let's bury this loser.}
{143}{}{Fine. You have no loans outstanding with us. We lend in units of two hundred caps, with a maximum of one thousand caps. Remember, though, I'm not gonna lend you the big bucks until you've proven you can repay the smaller loans.}
{144}{}{I'd like }
{145}{}{1000}
{146}{}{800}
{147}{}{600}
{148}{}{400}
{149}{}{200}
{150}{}{ caps.}
{151}{}{I'd better pass on the loan.}
{152}{}{Guido, Leone, why don't you show him what ripping off really means. Start with his arms.}
{153}{}{Sorry pal, but idiots are too big of a credit risk. Get out of here.}
{154}{}{Deathclaw. It's got to be the Deathclaw. No one's safe anymore!}
{155}{}{What about the Deathclaw?}
{156}{}{Tell me about Decker.}
{157}{}{What about the local police?}
{158}{}{What about the Children of the Cathedral?}
{159}{}{Tell me about yourself.}
{160}{}{Where does a person find work around here?}
{161}{}{He's a great guy. A good source of jobs to pay off my loans. Tell him I sent you, you might get a bonus!}
{162}{}{What about those missing caravans?}
{163}{}{Bonus? What do you mean?}
{164}{}{What about the local police?}
{165}{}{What about the Children of the Cathedral?}
{166}{}{Tell me about yourself.}
{167}{}{Where does a person find work around here?}
{168}{}{They're great guys! It's true we have the occasional misunderstanding, but I think they're a credit to their species... [sotto voce] ...whichever one that is...}
{169}{}{What about those missing caravans?}
{170}{}{Tell me about Decker.}
{171}{}{Misunderstandings? Like what?}
{172}{}{What about the Children of the Cathedral?}
{173}{}{Tell me about yourself.}
{174}{}{Where does a person find work around here?}
{175}{}{I can't say I'm too impressed. I run an honest, respectable business, and they accuse me of being a thief! The nerve of those people. They think a vow of poverty gives them the right to judge me!}
{176}{}{What about those missing caravans?}
{177}{}{Tell me about Decker.}
{178}{}{What about the local police?}
{179}{}{Vow of poverty?}
{180}{}{Tell me about yourself.}
{181}{}{Where does a person find work around here?}
{182}{}{I'm just a respectable businessman, that's all. We Giovannis have been respectable businessmen since the days before the holocaust... now that's tradition!}
{183}{}{What about those missing caravans?}
{184}{}{Tell me about Decker.}
{185}{}{What about the local police?}
{186}{}{What about the Children of the Cathedral?}
{187}{}{What's your idea of respectable?}
{188}{}{Where does a person find work around here?}
{189}{}{You should try Mr. Decker. Exciting work at great prices! The best in town! And he's just across the street! You can't get better convenience than that!}
{190}{}{What about those missing caravans?}
{191}{}{Tell me about Decker.}
{192}{}{What about the local police?}
{193}{}{What about the Children of the Cathedral?}
{194}{}{Tell me about yourself.}
{195}{}{What kind of excitement?}
{196}{}{Forget it, you're too big of a credit risk. Get outta my sight and don't come back.}
{197}{}{Fine. One thousand caps. You've got 10 days to repay it.}
{198}{}{Fine. Eight hundred caps. You've got 10 days to repay it.}
{199}{}{Fine. Six hundred caps. You've got 10 days to repay it.}
{200}{}{Fine. Four hundred caps. You've got 10 days to repay it.}
{201}{}{Fine. Two hundred caps. You've got 10 days to repay it.}
{202}{}{Too bad. Feel free to employ our services at a later time.}
{203}{}{Man, some of the stories they say about that thing are just... well, they're something!}
{204}{}{Tell me about Decker.}
{205}{}{What about the local police?}
{206}{}{What about the Children of the Cathedral?}
{207}{}{Tell me about yourself.}
{208}{}{Where does a person find work around here?}
{209}{}{Well, bye!}
{210}{}{Well maybe not a bonus. But he's a great guy, trust me on that one!}
{211}{}{What about those missing caravans?}
{212}{}{What about the local police?}
{213}{}{What about the Children of the Cathedral?}
{214}{}{Tell me about yourself.}
{215}{}{Where does a person find work around here?}
{216}{}{Well, bye!}
{217}{}{Can you believe someone accused me of extortion? Fortunately, my good friend Decker set them straight!}
{218}{}{What about those missing caravans?}
{219}{}{Tell me about Decker.}
{220}{}{What about the Children of the Cathedral?}
{221}{}{Tell me about yourself.}
{222}{}{Where does a person find work around here?}
{223}{}{Well, bye!}
{224}{}{I'll bet their leader, this Morpheus character, he's not broke! No sir! I'll bet that over in L.A. Boneyard, he's just living it up!}
{225}{}{What about those missing caravans?}
{226}{}{Tell me about Decker.}
{227}{}{What about the local police?}
{228}{}{Tell me about yourself.}
{229}{}{Where does a person find work around here?}
{230}{}{Well, bye!}
{231}{}{You don't show us respect, you get hurt. How much more respectability can a man ask for?}
{232}{}{What about those missing caravans?}
{233}{}{Tell me about Decker.}
{234}{}{What about the local police?}
{235}{}{What about the Children of the Cathedral?}
{236}{}{Where does a person find work around here?}
{237}{}{Well, bye!}
{238}{}{Adventure, danger. You can really make a killing!}
{239}{}{What about those missing caravans?}
{240}{}{Tell me about Decker.}
{241}{}{What about the local police?}
{242}{}{What about the Children of the Cathedral?}
{243}{}{Tell me about yourself.}
{244}{}{Well, bye!}
{245}{}{See you around, pal!}
{246}{}{Hey, hey, hey... take your hands off that door, freak!}
{247}{}{That's it, freak! You will pay for that!}
{248}{}{I'm sorry, but I don't have the time for this. If you can't pay the full amount, give me what money you do have and our business relationship will be terminated permanently.}
{249}{}{Well, okay. You can have all of my caps.}
{250}{}{Oh! I just remembered! I have just enough to cover the whole loan!}
{251}{}{[Attempt to fool Lorenzo by giving him only }
{252}{}{ caps]}
{253}{}{Forget it! You're not getting one single cap out of me.}
{254}{}{[You give Lorenzo all of your caps]}
{255}{}{[You give Lorenzo }
{256}{}{ caps]}
{257}{}{You're full of crap! You've been holding out on me! I'm gonna to beat that money out of you!}
{258}{}{What a pity. I guess we'll just have to put some caps into you instead. Guido! Leone!}
{259}{}{All right. I suppose this will have to do. You do realize I can never deal with you again? If I see you in here again I will be forced to exact a much more severe penalty upon you.}
{260}{}{You make me sick. Give me the money and get out! Don't ever let me see you in here again!}
{261}{}{You don't have enough!}

# New:
	{300}{}{That's all. Bye!}
{310}{}{Hi. How can I help you?}
	{311}{}{I want to pay off my loan.}
{312}{}{Another loan? Did you even leave the building? How about you do something fun first? Maybe over in the Maltese Falcon! Come back to me later.}
{313}{}{Already? Did you even leave the building? I'm busy, come back another time!}





