{100}{}{You see a young woman with dark hair.}
{101}{}{You see Lorraine, a scav from Adytum.}
{102}{}{Hi. Are you new here?}
{103}{}{Yeah. Can you fill me in a little?}
{104}{}{Yes, I am. I'm called }
{105}{}{. }
{106}{}{Whuuu?}
{107}{}{I suppose. What do you need to know about?}
{108}{}{Who are you?}
{109}{}{Can you give me some information about L.A. Boneyard?}
{110}{}{Tell me a bit about the other residents of Adytum.}
{111}{}{What do you do for a living?}
{112}{}{Never mind, thanks.}
{113}{}{I'm Lorraine.}
{114}{}{Can I ask you a few questions?}
{115}{}{I'm a scav. I work with Sammael to collect stuff from the ruins, so that we can use it to build or trade.}
{116}{}{Why doesn't everybody here do that?}
{117}{}{How many scavs are there?}
{118}{}{Can I ask you about something different?}
{119}{}{Nice talking to you.}
{120}{}{Well you got the Deathclaws out there, plus the Regulators take a percentage off the top, plus some for protection here in Adytum. Guess people don't have the upfront cash, or the guts to stare a Deathclaw in the eye.}
{121}{}{What's the deal with the Regulators?}
{122}{}{How do you avoid the Deathclaws?}
{123}{}{Can I ask you about some other stuff?}
{124}{}{Thanks. Bye.}
{125}{}{Oh, there's half a dozen of us. Sammael was the first one, and he's still the best.}
{126}{}{Can I ask you about some other stuff?}
{127}{}{Interesting. Thanks.}
{128}{}{They keep the peace around here, and control all the money coming in and going out. The rest of the people here pretty much work for the Regulators, and that ain't the most forgiving job. Many of them don't ever see beyond the fence that surrounds this place.}
{129}{}{All that makes you wonder what Julianna was thinking.}
{130}{}{What do you mean about Julianna?}
{131}{}{Very nasty. Can I ask some other things?}
{132}{}{Thanks for the warning.}
{133}{}{Oh, she wound up falling for some Blade a while ago. Poor dear can't leave the town, of course, and Caleb would kill the young lad on sight. Very tragic.}
{134}{}{Uh... if you say so.}
{135}{}{Can I ask some other questions?}
{136}{}{Hmm. Thanks for filling me in. Bye.}
{137}{}{We only scavenge after dark. And we're very good at what we do. Sammael's got a little test that he likes to throw out at people, before he lets them become scavs.}
{138}{}{What's the test?}
{139}{}{Still sounds dangerous.}
{140}{}{I see. Mind if we back up a bit?}
{141}{}{Interesting. Bye.}
{142}{}{Sammael has the person hide somewhere within Adytum during the day. If he can't find the student in an hour, then he lets the person join the next scavenger party.}
{143}{}{What a stupid system!}
{144}{}{Seems to work. You're still alive.}
{145}{}{Huh. Can I ask you about some other things?}
{146}{}{Interesting. Bye.}
{147}{}{Come now, isn't there the faintest trace of a romantic in you? Really, it's too bad. Unrequited love and all of that. Tragic.}
{148}{}{Hmpf. Shows what you know. Tell that to Sammael. If you can find him.}
{149}{}{Yes, although it can be rough. It's very dangerous, especially if you're caught.}
{150}{}{No doubt. Can I ask about something else?}
{151}{}{Thanks for the info.}
{152}{}{Wow, I think you're a little beyond my help.}
{153}{}{This used to be a big city, called Los Angeles. But the bombs hit really hard. Now, there's just the Angel's Boneyard. We Adytowners are just trying to survive in the wreckage.}
{154}{}{Can you tell me more about Los Angeles?}
{155}{}{I see. Thanks.}

# interestingly, the german string is different is talking about making computer games
# "Hier lebten damals viele Menschen, und sie machten wichtige Dinge, wie z.B. Computerspiele. Soviel ich weiß haben sich die Überlebenden an einem riesigen Ort versteckt, der Vault genannt wurde. Erst Jahre später kamen sie dort wieder heraus. Einige von ihnen gründeten Adytum, doch die "
{156}{}{Lots of people lived here. From what I hear, the survivors hid in a big place called a Vault, and came out years later. Some of them started the Regulators and then founded Adytum, while the }

{157}{}{others formed the Blades. The Gun Runners aren't from here originally.}
{158}{}{Where is this Vault?}
{159}{}{What's the deal with the Regulators?}
{160}{}{Where are the Gun Runners from?}
{161}{}{Create computer games? I don't think that's particularly important.}
{162}{}{Thanks for your help.}
{163}{}{Well, supposedly it was somewhere south of here, but I don't know really. I think everyone left because it was broken.}
{164}{}{Can I ask you some more questions?}
{165}{}{Hmm. Thanks.}
{166}{}{I'm not really sure. I think they came from somewhere up north of here.}
{167}{}{What do you know about the Regulators?}
{168}{}{Can I ask about some other things?}
{169}{}{Thanks for the information.}
{170}{}{Who do you want to know about?}
{171}{}{Jon Zimmerman.}
{172}{}{Caleb.}
{173}{}{Miles.}
{174}{}{Tine.}
{175}{}{Smitty.}
{176}{}{Nobody.}
{177}{}{Zimmerman watches over our town. He makes sure that everyone gets fed, and that everybody has a job to do.}
{178}{}{Caleb is the leader of the Regulators. It's his job to protect Adytum. He seems to enjoy it a little more than he should.}
{179}{}{Ah, our resident chemist. Miles makes bullets, and he also built the water distiller that makes sure we get clean water from the well. He's working on an underground farm right now, but he's missing some parts.}
{180}{}{Tine runs the shop. It's in the bunker near the gate. He trades with the Hub merchants for us.}
{181}{}{Hmm. Smitty is a tinkerer of sorts. He's good at repair work. He casts bullets and fixes broken stuff around town.}
{182}{}{Can I ask about someone else?}
{183}{}{Can we talk about a different subject?}
{184}{}{Thanks.}
{185}{}{Are you kidding? If there weren't any computer games, you wouldn't be playing this game, would you?}

#Fo1in2
{200}{}{Hi again.}
