{100}{}{You see: General Maxson.}
{101}{}{What's the Brotherhood really about?}
{102}{}{I'll bet you know a lot of the history behind the Brotherhood.}
{103}{}{Heard any good rumors?}
{104}{}{I have some information to report.}
{105}{}{That's all. Thanks.}
{106}{Gen_1}{Hello, youngster. Cabbot said you wanted to talk. Look I'm uh... I'm pretty stacked up right now, so I'll uh... I'll help you out as long as you don't start flappin' your gums too much. You know, outsiders are like that, always jawin'... Hehehe. Kinda like me, huh?}
{107}{}{Outsiders? What do you mean by that?}
{108}{}{How 'bout a few questions then?}
{109}{Gen_2}{I can't. I just moderate these endless damn meetings. There's four Elders, and me, you see? I break up fights and tie votes. Now, if all four vote to pick our noses while an army rolls in here and kicks our collective butt, there's not a helluva lot I can do about it.}
{110}{}{Oh, well.}
{111}{}{That stinks. Why don't you do something?}
{112}{Gen_2a}{Tradition. It's hard to change our ways. Now, maybe if the Elders had some real info, they'd get off their brains and do something.}
{113}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in a long, long time. Well, near on twenty years now. }
{114}{}{Why me?}
{115}{}{I'm flattered. How about some of those questions now?}
{116}{Gen_4}{Because we need to do something. An army's gatherin', Hub caravans are disappearin', and our scouts sure as hell ain't gettin' the job done. So the Elders actually did something once and figured the right Outsider might have something to offer. That Outsider is you... We hope.}
{117}{}{What army?}
{118}{}{What about these missing caravans?}
{119}{}{Hmm. I guess there are some more things I need to ask then.}
{120}{}{What's the problem with the scouts?}
{121}{}{I have some info you might want.}
{122}{Gen_5}{When we heard about the missing caravans, we sent out a few scouts east and the north. The ones who went north never returned. One came back from the east. He talked about a score of strange beings, all muscle with burnin' eyes. The Elders aren't doin' squat, but I'm getting ready just the same.}
{123}{}{Twenty isn't an army. Why are you worried?}
{124}{}{Sounds like your guy baked in the sun too long.}
{125}{}{I'll do what I can.}
{126}{}{Did he say where to the east?}
{127}{}{I have some info you might want.}
{128}{Gen_6}{They may or may not be good scouts, but don't question the truthfulness of my men. We can revoke your Initiate status at any time.}
{129}{}{Sounds like you need me more than I need you.}
{130}{}{Sorry.}
{131}{Gen_7}{That's it. I warned the Elders that bringin' in an Outsider could be trouble. [shouting aside] Guards! There's an Initiate here who needs some quiet time to discover some manners. }
{132}{Gen_8}{You're an Outsider, but I expect you to learn our ways. I'll be watching. Now, ask your questions. }
{133}{Gen_9}{Good. Anything else you need to ask? }
{134}{Gen_10}{Deep in the mountains. He couldn't be more specific.}
{135}{}{Too bad. Can I ask you a few more questions?}
{136}{}{What about to the north?}
{137}{}{Go ahead. }
{138}{Gen_11a}{Yeah, fire away.}
{139}{Gen_11b}{Sure.}
{140}{Gen_11c}{Shoot.}
{141}{Gen_12}{I got a gut feeling there's a small force in the east and a much bigger one in the north. The Elders are collecting dust because none of the scouts returned from the north. I can't do anything but watch.}
{142}{}{Well, I'll do what I can.}
{143}{}{Why don't you do something?}
{144}{}{I think I'm in a bit over my head. Count me out.}
{145}{}{I have some info on that.}
{146}{Gen_13}{Well the merchants from the Hub told us a bunch of caravans disappeared on their way up north. I think there's an army in the mountains, but the Elders, well, they don't want to act until they're sure. }
{147}{}{Where did they disappear?}
{148}{}{Aren't you the High Elder? Why don't you do something?}
{149}{}{Didn't you do anything?}
{150}{}{I have some info on that.}
{151}{Gen_14}{The word I got was that the caravans disappeared around the southern tip of the mountains to the east. I imagine the Hub merchants can probably tell you more.}
{152}{}{Thanks. I've got some more questions, if that's okay.}
{153}{}{Thanks. I'll talk to you later.}
{154}{}{I have some info on that.}
{155}{Gen_15g}{See you around, Initiate. You're not so bad... for an Outsider.}
{156}{Gen_15n}{Goodbye, Initiate.}
{157}{Gen_15b}{Goodbye!}
{158}{Gen_16}{I grew up too isolated here. Can you imagine spending your whole life inside one small place, then having to go out into the world? }
{159}{}{Well, as a matter a fact...}
{160}{}{I guess I'm destined to be your scout, then.}
{161}{}{So because they didn't get out, I get to do your dirty work. Forget it.}
{162}{Gen_17}{Then you understand the problem. To survive, we need someone who knows the outside. Like you. }
{163}{}{Okay, I'll do it.}
{164}{}{I've got my own problems. I pass.}
{165}{Gen_18}{Well... with what I guess is coming, we don't have time for anyone who's gonna... not contribute. Now, you either work with us, or you take a hike.}
{166}{}{Well, if you put it that way, I'm in.}
{167}{}{Looks like a nice day for a stroll.}
{168}{Gen_19}{Your choice. Hope you can live with it. }
{169}{Gen_20}{What? It's who we are and what we live for. It's ideals. As you spend more time with us, hopefully, you'll understand.}
{170}{}{Yeah, but what do you actually do?}
{171}{}{I'm not too sure about this.}
{172}{Gen_21}{Our main goal is to survive. The Scribes copy old plans for weapons or design new ones, and the Knights make the guns from 'em. Most guns come from us.}
{173}{}{You trade the weapons to the Hub?}
{174}{}{That's all you do?}
{175}{}{Makes sense. There's a couple of other things I need to ask.}
{176}{Gen_22}{That's the way we get our supplies.}
{177}{}{Okay, I get it. There's a couple of other things I need to ask.}
{178}{}{Okay. I need to get going now, though.}
{179}{}{Guess I'm not too sure about this.}
{180}{Gen_23}{All? It's damn important. It's critical to our survival.}
{181}{}{Whatever. I need to ask a few more questions.}
{182}{}{Yeah, well, it's stupid.}
{183}{}{Okay, thanks. I really should be going now, though.}
{184}{Gen_26}{Then you need to get sure. Because being unsure is bound to get you killed.}
{185}{}{The more I know, the more sure I'll be.}
{186}{Gen_28}{Look I don't have time for a story that long right now. Here. All of us grew up on this. }
{187}{Gen_29n}{There's rumors concerning the missing caravans in the Hub, as well as the strange army brewing in the eastern mountains. }
{188}{}{Okay.}
{189}{}{What army?}
{190}{}{What about these missing caravans?}
{191}{}{I have some info on that.}
{192}{Gen_29b}{I don't take stock in rumors. }
{193}{Gen_30}{Ahh... Hello again, Initiate. Are things going well? }
{194}{}{Pretty good. Can I ask you a few more questions?}
{195}{}{Well, actually, it sucks.}
{196}{}{Yes, thanks, but I gotta go.}
{197}{Gen_32}{I'm sorry we're not what you're used to but you could show a little self-discipline. }
{198}{}{Sorry. Can I ask you a few more questions?}
{199}{}{Why? This place is a joke.}
{200}{}{I have to get going. Bye.}
{201}{Gen_34}{What the hell do you want now? }
{202}{}{I want to know why an idiot is in charge here.}
{203}{}{I need to ask a few more questions.}
{204}{}{Never mind, thanks.}
{205}{Gen_35}{Whaddya got? }
{206}{}{Sorry, I don't really have anything.}
{207}{}{The Hub caravans are being taken by huge, green mutants. They're gathering an army.}
{208}{}{There's a large army to the north controlled by someone called the Master.}
{209}{Gen_36}{You've seen 'em? This might actually get the Elders to do something. I'm gonna get on this, thanks!}
{210}{Gen_38}{Uh... What's he plan to do with this... army of his? }
{211}{}{He plans to take over the Brotherhood, the Hub, Junktown... everyone.}
{212}{}{How much are you paying for this information?}
{213}{Gen_39}{Finally! Well this'll get the Elders off their butts. We'll fortify the fortress and surprise those damn mutants.}
{214}{}{No! You don't understand. They are turning people into mutants and adding them to their army.}
{215}{}{Okay.}
{216}{Gen_40}{So?}
{217}{}{So, by the time they get here, they'll be unstoppable. And they have advanced weapons, like yours. You don't stand a chance.}
{218}{}{Well, okay. Maybe digging in is the right thing.}
{219}{Gen_41}{So what's your alternative?}
{220}{}{Help me attack the Master's base. I know where it is.}
{221}{Gen_42}{Hmmm. Not a bad plan. Tell you what, let me go try and beat it into the Elders. No guarantees, but I'll try.}
{222}{Gen_43}{Then get out. I have work to do.}
{223}{Gen_44}{Pretty interesting set of priorities and loyalties you got there.}
{224}{}{Loyal to myself. 500 caps. Take it or leave it.}
{225}{}{Oh... yeah. Okay, I'll tell you. He plans to take over everyone and everything.}
{226}{Gen_44a}{I'll take it. We need the information to save lives.}
{227}{}{Pretty simple. He's changing humans into mutants and he's got advanced weapons. He plans to take over everything.}
{228}{Gen_44b}{Well, if he does, hope you find a place to use your scripts.}
{229}{Gen_45}{Well, how about nothing! Guards, kick this fool out. By God! We'll defend the Brotherhood without your damn help.}
{230}{Gen_46}{What do you think you're doing? Put that down. Put it down now!}
{231}{Gen_47}{That's it. Guards! Take this idiot away!}
{232}{Gen_48}{Hey, hey, hey, hey! Hold on now. Stop that. Stop it right now!}
{233}{Gen_49}{Like I said...}
{234}{Gen_50}{I said...}
{235}{Gen_51}{I am not in the habit of repeating myself. So open your ears.}
{236}{Gen_52}{Look I told ya' already. It's not my fault if you didn't get it.}
{237}{Gen_52a}{That's where you are. You want the long version, go talk to Vree.}
{238}{Gen_52b}{Mathia's my assistant.}
{239}{Gen_53}{Oh, he's a good kid, even if he does want to be a Scribe.}
{240}{Gen_54}{Vree's the Head Scribe. She's usually in the library; she... always likes to talk.}
{241}{Gen_55}{We keep weapon specs and history there.}
{242}{Gen_56}{Rhombo's been here a long time. A bit stiff, but a helluva soldier.}
{243}{Gen_58}{Hehehe. A fine, handsome, upstanding man. The High Elder position is to mediate the meetings between the Elders. You see, two years ago I got talked into it. If I'd of known then...}
{244}{Gen_59}{Well you see there's four of them and that's about all they can ever agree on. They can't even agree if they want to piss, much less pick a pot to piss in.}
{245}{Gen_60}{Well that's what you are. Initiates train and learn to become Knights or Scribes.}
{246}{Gen_61}{Well, Scribes copy down the weapon specs. We've got information all the way back to my granddad. Sometimes a Scribe comes up with a new idea for a weapon. Hehehe. Doesn't happen too often. They all answer to Vree.}
{247}{Gen_62}{The Knights make the weapons. And when he's good enough, a Knight can advance to become a Paladin and then an Elder and so forth. Right now Rhombus is the head of the Knights.}
{248}{Gen_63}{Paladins are in charge of all security and outside activities. I remember tradin' with the Hub, goin' on scouting missions for the Elders. Ah man, those were good times.}
{249}{Gen_64}{The Hub's down to the southeast. They trade us food and things for the weapons we make here. Now if you're ever down there, you talk to Butch Harris.}
{250}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{251}{Gen_66}{They're the main ones we trade with. Not totally trustworthy, but not as bad as the others. }
{252}{Gen_67}{You can't trust them. A few years ago, they offered us water for a huge stockpile of weapons. We told them no, and you know what they did? Sent in thieves to steal the weapons! We caught 'em, but the Elders voted down going to the Hub to teach the merchants a lesson.}
{253}{Gen_68}{Holodisks? Hmm... I haven't seen those in a while.}
{254}{Gen_69}{Vree has it someplace in the Library.}
{255}{Gen_70}{Roger Maxson huh? Well he led our people here in the great Exodus, started the Brotherhood from scratch. Quite a leader.}
{256}{Gen_71}{Well that was when my granddad, Roger Maxson, led his soldiers here and started the Brotherhood. He never mentioned where they came from, but it doesn't really matter, 'cause... well, this is our home now.}
{257}{Gen_72}{Well I believe there's an army massing to the north and in the mountains to the east, but I don't have any way to prove it. The Elders, they won't even listen. }
{258}{Gen_73}{A bunch of religious whackos, if you ask me. I think their main church is in the Boneyard.}
{259}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{260}{Gen_76}{Well, there's not much to tell. I never ran into any of them. I've heard they're a problem for the people of Adytum, though.}
{261}{Gen_77}{That's a settlement down in the Boneyard. I went there... oh... a long time ago. I was on a scouting mission for the Elders.}
{262}{Gen_78}{Oh. Just another stupid rumor. Some people say it's a huge fanged monster and others say it's a vampire.}
{263}{Gen_79}{Oh, I don't know anything about that.}
{264}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{265}{Gen_81a}{Hell if I know.}
{266}{}{Surprised to see me? And let you have all the fun?}
{267}{}{How did you convince the Elders?}
{268}{Gen_82a}{Oh wasn't hard at all. I just calmly explained the situation. And bingo here we are. Lead on, my friend.}
{269}{Gen_83}{What are you doing in here? This is for Elders.}
{270}{}{Sorry, I'll just leave.}
{271}{}{I don't care, I'm staying.}
{272}{Gen_84}{Good, now shut the door on the way out.}
{273}{Gen_84a}{I'm telling you, do not interfere.}
{274}{Gen_85}{Ha! You forget. I used to teach this stuff.}
{275}{Gen_86}{Contrary to opinion, we don't want soldiers with no brains whatsoever.}
{276}{Gen_87}{Well, I suggest you talk to my assistant, Mathia, about that.}


# Alchemist: I'm not sure about exact naming of the Weapon Store. Check this place.
{278}{}{Excellent! Due to the successfully completed mission I grant you access to the weapon stock on the first level. Any more questions?}
{300}{}{Maybe you can tell me? Everyone here seems to be on edge. It's like you are getting ready to go to war, but no one knows with whom.}
{301}{}{Do you have any clues as to what's behind the disappearance of the caravans?}
{302}{}{I'll go scout out the area to the north and then report what I find.}
{303}{}{For 500 caps, I'll check out what's going on up there.}
{304}{}{For 1000 caps, I'll check out what's going on up north.}
{305}{}{I'm not sure if I want to get involved right now.}
{306}{}{Would it be possible for me to get a hold of some better weapons?}
{307}{}{Just a few questions first.}
{308}{}{No, I'll see you after I find out what's going on up there.}
{309}{}{Okay, bye.}
{310}{}{How do you know that your scouts didn't desert?}
{311}{}{I believe I've already run into the creatures you're describing. They are not to be taken lightly.}
{312}{}{Please forgive me. What do you think is the cause of the disappearance?}
{313}{}{Go ahead. Revoke it. See if I care.}
{314}{}{Sorry, but it would be too risky for me to go up there right now.}
{315}{}{Alright, I'll go, but can I get some better weapons first?}
{316}{}{Okay, I'll do it for 1000 caps.}
{317}{}{Take it or leave it.}
{318}{}{Never mind.}
{319}{}{Okay, okay, I'll do it for free.}
{320}{}{Very well, I'll see you when I get back.}
{321}{}{I have found proof that it is this army that is causing the disappearance of the caravans. It is an army of mutants. You have good reason to be worried. They look very formidable.}
{322}{}{It's apparent that someone needs to go up there and check it out.}
{323}{}{It's going to take more than a 'gut feeling' to get me to risk my life by going up there.}
{324}{}{I consider my life to be a fairly important priority.}
{325}{}{I just don't think I am ready for the task.}
{326}{}{I'm loyal to only one person.}
{327}{}{I can.}
{328}{}{Duh?}
{329}{}{Why does everyone here seem so edgy? It's like you're getting ready to go to war, but no one knows who the enemy is.}
{330}{}{I need to talk to you about the disappearance of the caravans. Do you have any insight on the matter?}
{331}{}{Never mind.}
{332}{}{I need to ask you some questions.}
{333}{}{Duh?}
{334}{}{I have some information on the area north of here.}
{335}{}{Can I ask you some questions?}
{336}{}{Never mind.}
{337}{}{Sorry, I didn't really have anything.}
{338}{}{I saw their base. It's crawling with mutants.}
{339}{}{I saw the mutant base to the north. They follow a leader they call the Master.}
{340}{}{You can't play defense on this one, Maxson.}
{341}{}{Well, it's obvious something needs to be done. It would be best if we attack the mutants before they attack us. We're going to need the Elders on our side for this one.}
{342}{}{I'm not quite sure what we should do about it right now. Let me gather some more information, and I'll get back to you.}
{343}{}{He plans to take over any human settlements he can.}
{344}{}{What can you tell me about the Brotherhood's history?}
{345}{}{What is the Brotherhood's main purpose?}
{346}{}{Who are the Elders?}
{347}{}{Do you know anything about the Deathclaw?}
{348}{}{Never mind.}
{349}{}{Can I ask you another question?}
{350}{}{Thank you.}
{351}{}{You earn }
{352}{}{ experience for scouting the desert to the north.}

#
# TRANSLATION NOTE: The following groups of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ('my friend' will be masculine); the second line is
# for the case of the player-character feminine ('my friend' will be feminine).
#

{353}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in a long, long time. Well, near on twenty years now. }
{354}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in a long, long time. Well, near on twenty years now. }
{355}{Gen_6}{They may or may not be good scouts, but don't question the truthfulness of my men. We can revoke your Initiate status at any time.}
{356}{Gen_6}{They may or may not be good scouts, but don't question the truthfulness of my men. We can revoke your Initiate status at any time.}
{357}{Gen_15n}{Goodbye, Initiate.}
{358}{Gen_15n}{Goodbye, Initiate.}
{359}{Gen_30}{Ahh... Hello again, Initiate. Are things going well? }
{360}{Gen_30}{Ahh... Hello again, Initiate. Are things going well? }

{400}{}{I've been to the mutant base to the north. Let's just say they are no longer a threat.}


# General Maxson Tell-Me-Abouts generic responses
{980}{Gen_79}{Oh, I don't know anything about that.}
{981}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{982}{Gen_81a}{Hell if I know.}

#
# General Maxson Tell-Me-Abouts
#

{1000}{}{Brotherhood}
{1001}{}{Mathia}
{1002}{}{Cabbot}
{1003}{}{Vree}
{1004}{}{Library}
{1005}{}{Rhombus}
{1006}{}{Elder}
{1007}{}{Elders}
{1008}{}{Initiates}
{1009}{}{Scribes}
{1010}{}{Knights}
{1011}{}{Paladins}
{1012}{}{Hub}
{1013}{}{Butch|Harris}
{1014}{}{Traders}
{1015}{}{Merchants}
{1016}{}{Disks|Discs|Holodisk|Holodisc|Holo-Disk|Holo-Disc}
{1017}{}{Player}
{1018}{}{Roger|Maxson}
{1019}{}{Exodus|War}
{1020}{}{Army}
{1021}{}{Cathedral}
{1022}{}{Angel's|Angels|Boneyard}
{1023}{}{Gangs}
{1024}{}{Adytum}
{1025}{}{Claw|Deathclaw|Death}
{1030}{}{Master}
{1032}{}{Caravans}
{1033}{}{Chip}

{1100}{Gen_52a}{That's where you are. You want the long version, go talk to Vree.}
{1101}{Gen_52b}{Mathia's my assistant.}
{1102}{Gen_53}{Oh, he's a good kid, even if he does want to be a Scribe.}
{1103}{Gen_54}{Vree's the Head Scribe. She's usually in the library; she... always likes to talk.}
{1104}{Gen_55}{We keep weapon specs and history there.}
{1105}{Gen_56}{Rhombo's been here a long time. A bit stiff, but a helluva soldier.}
{1106}{Gen_58}{Hehehe. A fine, handsome, upstanding man. The High Elder position is to mediate the meetings between the Elders. You see, two years ago I got talked into it. If I'd of known then...}
{1107}{Gen_59}{Well, you see, there's four of them and that's about all they can ever agree on. They can't even agree if they want to piss, much less pick a pot to piss in.}
{1108}{Gen_60}{Well that's what you are. Initiates train and learn to become Knights or Scribes.}
{1109}{Gen_61}{Well, Scribes copy down the weapon specs. We've got information dating all the way back to my granddad. Sometimes a Scribe comes up with a new idea for a weapon. Hehehe. Doesn't happen too often. They all answer to Vree.}
{1110}{Gen_62}{The Knights make the weapons. And when he's good enough, a Knight can advance to become a Paladin and then an Elder and so forth. Right now Rhombus is the head of the Knights.}
{1111}{Gen_63}{Paladins are in charge of all security and outside activities. I remember tradin' with the Hub, goin' on scouting missions for the Elders. Ah man, those were some good times.}
{1112}{Gen_64}{The Hub's down to the southeast. They trade us food and things for the weapons we make here. Now if you're ever down there, you talk to Butch Harris.}
{1113}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{1114}{Gen_66}{They're the main ones we trade with. Not totally trustworthy, but not as bad as the others.}
{1115}{Gen_67}{You want to hear about the Water Merchants. Hehehe, well you can't trust them. A few years ago, they offered us water for a huge stockpile of weapons. We told them no, and you know what they did? Sent in thieves to steal the weapons! We caught 'em, but the Elders voted down going to the Hub to teach the merchants a lesson.}
{1116}{Gen_68}{Holodisks? Hmm... I haven't seen those in a while.}
{1117}{Gen_69}{Vree has it someplace in the Library.}
{1118}{Gen_70}{Roger Maxson huh? Well he led our people here in the great Exodus, started the Brotherhood from scratch. Quite a leader.}
{1119}{Gen_71}{Well that was when my granddad, Roger Maxson, led his soldiers here and started the Brotherhood. He never mentioned where they came from, but it doesn't really matter, 'cause... well, this is our home now.}
{1120}{Gen_72}{Well I believe there's an army massing to the north and in the mountains to the east, but I don't have any way to prove it. The Elders, they won't even listen.}
{1121}{Gen_73}{A bunch of religious whackos, if you ask me. I think their main church is in the Boneyard.}
{1122}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{1123}{Gen_76}{Well, there's not much to tell. I never ran into any of them. I've heard they're a problem for the people of Adytum, though.}
{1124}{Gen_77}{That's a settlement down in the Boneyard. I went there... oh... a long time ago. I was on a scouting mission for the Elders.}
{1125}{Gen_78}{Oh. Just another stupid rumor. Some people say it's a huge fanged monster and others say it's a vampire.}
{1130}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{1133}{Gen_81a}{Hell if I know.}

