{100}{}{I can't believe the things that you have done.}
{101}{}{I don't care. I'm hurt. Heal me.}
{102}{}{Hngh!}
{103}{}{No. I have taken a vow to not hurt life, but I will not help you.}
{104}{}{Lack of intelligence is no excuse for what you have done. Go away, I will not speak to you anymore.}
{105}{}{Oh my, you're seriously wounded. Here, let me help you.}
{106}{}{Welcome back, }
{107}{}{. How goes the search?}
{108}{}{It's going okay.}
{109}{}{I need help.}
{110}{}{Lol?}
{111}{}{Hmm... Ah. Yes. Here, I found these. Use them when you need a boost.}
{112}{}{Good, keep up the good work. And let me know if you need anything.}
{113}{}{What can I do for you?}
{114}{}{I need healing.}
{115}{}{I need some drugs.}
{116}{}{I need some more stimpaks.}
{117}{}{D'oh!}
{118}{}{Duh.}
{119}{}{I'm not authorized to give you any. Sorry.}
{120}{}{What a stick in the mud! Thanks for nothing.}
{121}{}{I have an urgent need for them. Without the drugs, the safety of the Vault is in jeopardy!}
{122}{}{Sorry, I can't give them to you.}
{123}{}{Well, since you put it that way. But don't tell anyone that I let you have these. They are extremely addictive and dangerous to use.}
{124}{}{Thanks!}

{125}{}{Stimpaks are being rationed. You are welcome to what we have in the medical container on the wall. Take as many as you need, but use them sparingly. It will be a while before we'll be able to get you some more.}
{126}{}{Hmm. Let's see if you are hurt.}
{127}{}{You seem okay to me. Minor wounds will heal with time. Come back if you're in worse shape and we'll get you fixed up.}
{128}{}{You look hurt. Here, let me help you.}
{129}{}{If you need healing, come back here to me or use some of the stimpaks we have.}
{130}{}{Lie down here, and we will start the healing process.}
{131}{}{You are fully healed. Take care of yourself in the future, and do come back if you need any more healing. Have a good day!}
{132}{}{The medical scanners picked up some deadly radiation poisoning. Would you like us to attempt a healing? It will take a while.}
{133}{}{The medical scanners picked up some serious radiation poisoning. Would you like us to attempt a healing? It will take a while.}
{134}{}{The medical scanners picked up some major radiation poisoning. Would you like us to attempt a healing? It will take a while.}
{135}{}{The medical scanners picked up some mild radiation poisoning. Would you like us to attempt a healing? It will take a while.}
{136}{}{You see the Vault 13 medic.}
{137}{}{Okay, well let's have a look then. Hold still for a moment.}
{138}{}{No.}
{139}{}{Okay, do it.}
{140}{}{How long?}
{141}{}{How long will it take, and how much radiation can you remove?}
{142}{}{Na.}
{143}{}{Ya.}
{144}{}{Okay, fine, it's your body.}
{145}{}{It will take about }
{146}{}{ hours. RadAway would work a little faster, but we don't have any to spare. Shall we get started?}
{147}{}{No.}
{148}{}{Yes.}
{149}{}{It will take about }
{150}{}{ hours. I will be able to remove about }
{151}{}{ rads. RadAway would work a little faster, but we don't have any to spare. Shall we get started?}
{152}{}{No.}
{153}{}{Yes.}
{154}{}{This is going to be really, really painful.}
{155}{}{Don't worry, this shouldn't hurt at all.}
{156}{}{Okay, you should be feeling much better now. Be careful out there.}
{157}{}{I heard what you did, saving the Vault. Thank you.}
{158}{}{[More]}
{159}{}{The medic refuses to speak with you.}
{160}{}{Please don't do that.}
#
# Fallout Fixt:
#
{161}{}{I've been poisoned!}
{162}{}{I'm wildly irradiated, help me! My skin is melting off!}
{163}{}{You're welcome. Bye!}
{164}{}{[Continue]}
{165}{}{It will take less than }
{166}{}{an hour.}
{167}{}{ I will be able to completely heal you of your radiation sickness, which is }
{168}{}{ hours. I will be able to completely heal you of your radiation sickness, which is }
{169}{}{ and a half}
{170}{}{ RadAway would work a little faster, but we don't have any to spare. Shall we get started?}
{171}{}{Hmph.}
{172}{}{Looking for more of a kick? What kind of trouble have you been getting into? I shouldn't do this, but here, take these. No more for you though, and be careful.}

# Medic Tell-Me-Abouts

{1000}{}{Medic}
{1001}{}{Healing}

{1100}{}{I'm here at all times, to offer assistance and healing.}
{1101}{}{I can heal you if you are injured.}

# Fo1in2:
{2000}{}{Um, I need a growth removed. My sixth toe.}
{2001}{}{A sixth toe?! Interesting. Very interesting ... }
{2002}{}{Well, I can try. No guarantees, of course, as you have been in contact with the outside radiation far longer we anticipated ... it might just grow back.}
{2003}{}{So it actually DID grow back!}
	{2010}{}{I don't care. I want it off before it grows into a new me.}
	{2020}{}{Never mind then. I had some other questions...}
	{2030}{}{Forget it, then. Maybe I'll be back.}

{3000}{}{Okay then. Lie down here, and we will start with the operation right away.}
{3001}{}{That little friend of yours should be gone now. I hope. It's hard to squeeze out all of that mutated pus out of the bone marrow. Anyway, here you go.}
{3010}{}{Glad that's taken care of then. Say, there was another thing I needed...}
{3020}{}{It better not grow back this time. I mean it.}
{3030}{}{Much appreciated. I may be back.}





