{100}{}{You see a guard.}
{101}{}{What is your business here?}
{102}{}{Urr?}
{103}{}{I'm just looking around.}
{104}{}{I want to buy some weapons.}
{105}{}{}
{106}{}{}
{107}{}{I have no patience for jokes. If you do not leave this area now I will shoot you!}
{108}{}{We don't like nosy people. Go away now and I won't shoot you.}
{109}{}{}
{110}{}{}
{111}{}{You smell like a brahma but I bet you're not as intelligent.}
{112}{}{}
{113}{}{Ahh, very good. Customers are always welcome. Come in but please keep your weapons holstered. Go find Zack, he can set you up with anything you need.}
{114}{}{}
{115}{}{I need to speak to your boss. It is very important.}
{116}{}{Oh, okay. Gabriel will talk to you. Go on in.}
{117}{}{Yeah, I remember you. Go on in.}
{118}{}{I need to speak to Gabriel. It is very important.}
{119}{}{I want to buy weapons from Zack.}

# Fo1in2:
{200}{}{Go find Zack, he can set you up with anything you need.}

