{100}{}{You cannot bring yourself to root through the assorted bits.}
{101}{}{The cooler is filled with chunks of organs and body parts.}
{102}{}{The pieces in the cooler are cut into small chunks, and cooled for shipping. Nobody's getting any transplants from these bite-size pieces.}
{103}{}{Body parts fill the cooler.}
{104}{}{The cooler is full of body parts, cut into small chunks and packed in ice. Odd.}
