{100}{}{You see: Doc Morbid.}
{101}{}{I'm Doc Morbid, can I help you?}
{102}{}{Yeah, I need some help.}
{103}{}{I need some medical assistance.}
{104}{}{No, not today.}
{105}{}{Nng.}
{106}{}{Ya.}
{107}{}{Well, okay then. Do come back.}
{108}{}{Well, if not today, then perhaps sometime in the near future.}
{109}{}{Hopefully not. Bye.}
{110}{}{We'll just have to see, now won't we. But I doubt it.}
{111}{}{Hmm, lets have a look.}
{112}{}{You seem to be in nearly perfect health. That will be 10 caps for the examination.}
{113}{}{Ten caps for you to tell me that? You gotta be kidding.}
{114}{}{Here you go. Take your money.}
{115}{}{I never joke. Especially when it comes to physical trauma. You will pay or I'll have to resort to other forms of compensation, many of which are much more painful than just paying my fee.}
{116}{}{Okay, here's your money.}
{117}{}{Bite me. I'm leaving.}
{118}{}{Have it your way. Cougar, Flash. Show our 'patient' to the lab.}
{119}{}{Thank you for your business. Come again.}
{120}{}{It seems you do not have enough money to pay for my services. I have a very special way of dealing with debtors and liars - I don't. Flash and Cougar, take our newfound source of income to the lab for "processing".}
{121}{}{Okay, I have your test results:}
{122}{}{You are }
{123}{}{The total cost will be }
{124}{}{ caps. Payment is due before treatment. No exceptions. Will you pay?}
{125}{}{Yes, I will pay.}
{126}{}{No, I don't have the money. Will you float me?}
{127}{}{No.}
{128}{}{Ya.}
{129}{}{Nuh.}
{130}{}{No. I don't loan anyone, and I mean anyone, any amount of money. Go away, you pauper.}
{131}{}{It's your life. Goodbye.}
{132}{}{Excellent. Let's begin. This might hurt a little... }
{133}{}{There you go. Come back again!}
{134}{}{Oh, back so soon. What can I help you with?}
{135}{}{I need healing.}
{136}{}{Nothing, just making small talk.}
{137}{}{Wock!}
{138}{}{Please make it somewhere else, I'm busy.}
{139}{}{Hmmm. I don't like your looks, stranger. But what can I do for you? I never, ever turn away a paying customer.}
{140}{}{I need some help.}
{141}{}{I need some medical assistance.}
{142}{}{Nothing today, thanks.}
{143}{}{Hep.}
{144}{}{Oh, It's you again. I like your style, even if I don't like you. What can I help you with?}
{145}{}{I need healing.}
{146}{}{Nothing, just making small talk.}
{147}{}{Wock!}
{148}{}{Oh, It's a customer! What can I help you with?}
{149}{}{I need healing.}
{150}{}{Nothing, just making small talk.}
{151}{}{You seem excited to see me. Why?}
{152}{}{Wock!}
{153}{}{My business has dropped off recently. I'm happy to see any customers, these days. Not that I mind your company, of course.}
{154}{}{Excellent, I need some healing.}
{155}{}{Why has your business dropped off?}
{156}{}{Of course, I understand. Have a good day.}
{157}{}{Well, if you do need anything, please stop by. No one can beat my service!}
{158}{}{In case you haven't noticed, I got some competition.}
{159}{}{ Complaining to Killian won't do anything. He doesn't see anything wrong with the newcomers.}
{160}{}{ Those damn Children have moved in next door, and all, um, much of my business has gone to them. I don't like it, but I can't lower my prices to match theirs. I can only provide better service.}
{161}{}{Ahh, I do need some healing.}
{162}{}{Hmm, better prices, interesting. Thank you.}
{163}{}{Ahh, a repeat customer. Excellent these days! How can I help you?}
{164}{}{I need healing.}
{165}{}{Nothing, just making small talk.}
{166}{}{Wock!}
{167}{}{I hope you have a good reason for disturbing me. My time is extremely valuable.}
{168}{}{I'm dying here! Please help!}
{169}{}{I'm sorry for disturbing you, but I need assistance.}
{170}{}{Aggh!}
{171}{}{I don't find your humor funny. Please leave so I can return to my work.}
{172}{}{Hmm. Well, you seem fine to me. Perhaps you need some rest. Try the Crash House, around the corner. Good night.}
{173}{}{I'm sorry, I don't treat idiots at this time of night. Something about full moons and lunacy, I suppose. Have a good night.}
{174}{}{You again. I hope you have another good reason for disturbing me... }
{175}{}{I'm dying here! Please help!}
{176}{}{I'm sorry for disturbing you, but I need assistance.}
{177}{}{Aggh!}
{178}{}{perfectly healthy,}
{179}{}{slightly wounded,}
{180}{}{moderately wounded,}
{181}{}{seriously wounded,}
{182}{}{near death,}
{183}{}{ in my medical opinion.}
{184}{}{ according to my tests.}
{185}{}{ without a doubt.}
{186}{}{ in my humble opinion.}
{187}{}{ You are definitely suffering from poison.}
{188}{}{ You have been poisoned.}
{189}{}{ Did you know you are poisoned?}
{190}{}{ You have a deadly toxin in your bloodstream.}
{191}{}{ You have minor radiation poisoning.}
{192}{}{ You have some serious radiation poisoning.}
{193}{}{ Your body has absorbed an incredible amount of radiation.}
{194}{}{ I have never seen such readings on my radscanner. I think you are about to die. I give you two to three weeks.}
{195}{}{ There is not much I can do about it.}
{196}{}{I hope you have a good reason for disturbing me. My time is extremely valuable.}
{197}{}{I'm dying here! Please help!}
{198}{}{I'm sorry for disturbing you, but I need some assistance.}
{199}{}{Aggh!}
{200}{}{I don't find your humor funny. Please leave so I can return to my work.}
{201}{}{Hmm. Well, you seem fine to me. Perhaps you need some rest. Try the Crash House, around the corner. Good night.}
{202}{}{I'm sorry, I don't treat idiots at night. Something about full moons and lunacy, I suppose. Have a good night.}
{203}{}{You again. I hope you have another good reason for disturbing me... }
{204}{}{Trespasser! This is a private room!}
{205}{}{him!}
{206}{}{her!}
{207}{}{Throw down, butcher!}
{208}{}{Wait!}
{209}{}{Ack!}
{210}{}{Don't try to talk your way out of this one!}
{211}{}{Why should I?}
{212}{}{I'm no danger to you!}
{213}{}{I'm putting a stop to your operation, right here, right now!}
{214}{}{No! I won't let you shut down my operation! Gretch, get }
{215}{}{Why?!}
{216}{}{I know what you are doing here, and I won't stop you.}
{217}{}{You are obviously far more powerful than I am.}
{218}{}{That is true. Unfortunately, you have seen too much. Hmm.}
{219}{}{ You will have to be dealt with. Sorry.}
{220}{}{ You must prove your sincerity. And I might be able to make a little profit out of this deal.}
{221}{}{What do you mean?}
{222}{}{No deals, no way.}
{223}{}{Fine. Have it your way!}
{224}{}{I will take something from you. And then we will be even.}
{225}{}{Okay. }
{226}{}{No way.}
{227}{}{Excellent!}
{228}{}{Doc Morbid reaches up with a surgical tool, and, before you can react, removes one of your eyes. It is extremely painful.}
{229}{}{Now, half of what you have just seen is mine again.}
{230}{}{YOU RIPPED OUT MY EYE! YOU MOTHER... }
{231}{}{Now, now. Watch your language.}
{232}{}{The doctor is out.}
{233}{}{I know about you and Iguana Bob, you filthy butcher.}
{234}{}{Wh... what could you possibly mean?}
{235}{}{I had a little conversation with your troll... }
{236}{}{[He looks shiftily from side to side] That proves nothing. Gretch is a little... slow in the head. No one listens to him around here. You had best leave.}
{237}{}{Wait, can't we work something out?}


#TMA 
{970}{}{I'm Doc Morbid, can I help you?}

{980}{}{What's that?}
{981}{}{What are you babbling about?}
{982}{}{Is this a joke? I have no idea what that is.}

{1000}{}{Killian|Kilian|Sheriff|Sherrif|Mayor|Darkwater|Darkwaters}
{1001}{}{Gizmo}
{1002}{}{Junktown|Junk Town}
{1003}{}{Shady Sands|SHADY|SANDS}
{1004}{}{The Hub|HUB}
{1005}{}{Water Chip|Waterchip|Chip}
{1006}{}{Casino|Gizmo's Casino|Gizmo's|Gizmos|Gizmos Casino}
{1007}{}{Store|General Store}
{1008}{}{Deathclaw|Deathclaws|Claw|Claws}
{1009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid}
{1010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading}
{1011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside}
{1012}{}{Direction|Directions|Whereto|Where to}
{1013}{}{Fallout|Fall out|nuclear fallout}
{1014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev}
{1015}{}{Necropolis|City of the Dead|City of Dead}
{1016}{}{Boneyard|The Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard}
{1017}{}{Mutant|Mutants}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{Skuls|Skulz|Skulls|Skullz}
{1020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders}
{1021}{}{Crash|Crash House}

{1100}{}{Killian is the Mayor in town.}
{1101}{}{Gizmo runs the casino, and the boxing ring.}
{1102}{}{It's a quiet place for the most of it.}
{1103}{}{Never heard of.}
{1104}{}{Oh yes, the Hub. I have associates down there.}
{1105}{}{I don't know anything about that.}
{1106}{}{Gizmo runs it. Watch out for the slot machines, you can lose a lot of money if you play them.}
{1107}{}{Find the General Store if you keep heading up north in town.}
{1108}{}{I hear people talking about it, but I've never seen it. They say it roams the desert, striking mostly at night.}
{1109}{}{You're here. What do you want?}
{1110}{}{Killian Darkwater runs the General Store. Go there if you want to trade.}
{1111}{}{Why do you care? Junktown is obviously the better place.}
{1112}{}{I don't have time to show you the town. Ask someone else!}
{1113}{}{Just stay under a roof, okay?}
{1114}{}{They'll hang you if you get caught stealing.}
{1115}{}{I've heard about it. It's supposedly dangerous for non-mutants like us.}
{1116}{}{It's a place somewhere far south for all I know.}
{1117}{}{Horrible creatures. I pity them.}
{1118}{}{That's the bar a few houses north of here.}
{1119}{}{They are the local gang. Have to stick them back together every once in a while.}
{1120}{}{Luckily we don't run into much problems with them down here. Heard it's much worse up north.}
{1121}{}{If you need a place to sleep, check with the Crash House.}
