{100}{}{You see: Morpheus.}
{101}{MORP02}{I don't remember inviting anyone to my room? And yet I have a visitor. Why?}
{102}{}{Oh, I'm sorry. I seem to be lost.}
{103}{}{Because I have such a deal for you...}
{104}{}{I'm }
{105}{}{. What's yours?}
{106}{}{One of the Brothers sent me up here.}
{107}{}{Mom?}
{108}{MORP02A}{No. I'm Father Death...}
{109}{MORP03}{Well, my child, it's quite dangerous to explore places where you do not belong. Where were you heading that you ended up in my private chambers?}
{110}{}{I'm new, and I was looking for the bathroom. One of the other High Priests sent me up here.}
{111}{}{I was looking for the confessional, and one of the High Priests sent me up here. I'm really sorry I ended up here!}
{112}{}{Well, I'm not really lost.}
{113}{}{I was heading up here to kill you.}
{114}{}{I forget. I'll just go.}
{115}{MORP04}{Ahh... Heh heh heh. That would be Lasher. He so loves getting the worshipers in trouble. This is your lucky day, my ignorant little friend. You may leave now without incident. }
{116}{MORP04A}{ You were warned. Guards! }
{117}{MORP05A}{ You are a pathetic liar. Tell me the real reason you are here now... before I have you skinned alive. }
{118}{}{No really! I'm lost!}
{119}{}{All right, you got me. I'm here to offer you a deal.}
{120}{}{I'm just looking around.}
{121}{MORP06}{ I suspect you are a spy, sent by the Followers. I may be wrong, but I do not take chances. You must be eliminated. }
{122}{MORP07}{ What could you possibly offer me? }
{123}{}{I'm from a Vault. You know what that is, right?}
{124}{}{I'd like to offer you some information about your enemies.}
{125}{}{I was sent here by the Master. He wants me to spy on you.}
{126}{morp08}{Go on.}
{127}{}{I'd like to give your Master a bit of information about my Vault.}
{128}{}{I have some information for the Master about my Vault.}
{129}{}{Not so fast. I want to know what I can get for my information.}
{130}{MORP09}{ I do not have a master, you imbecile! }
{131}{}{Then what do you call the Master? Doesn't he control you?}
{132}{}{It sure looks like the Master controls you.}
{133}{}{Hey. Watch it with the insults!!}
{134}{}{I seem to have hit a nerve.}
{135}{MORP10}{ No one controls me. He and I are... partners. }
{136}{}{Yeah, right. You're a puppy on a short leash.}
{137}{}{It doesn't matter. I have information about a Vault he would want.}
{138}{}{He gives commands, right? And you follow them, no questions asked.}
{139}{MORP11}{ I do not tolerate insults. Guards! }
{140}{MORP12}{ Fine. I will take you to the Master. But if you are lying, he will know. }
{141}{}{Okay, fine.}
{142}{}{You're not taking me anywhere!}
{143}{MORP13}{ That is none of your concern. But if you are truly from a Vault, the Master will find out. Guards! Come along.}
{144}{MORP14}{You may keep your life. Now, tell me what you know. }
{145}{}{I'm from a Vault, and I'm willing to give the Master the location.}
{146}{}{Or what?}
{147}{}{I won't tell you anything.}
{148}{MORP15}{ No? Then I will take the information from you. Guards! }
{149}{MORP16}{ And who might my enemies be? }
{150}{}{Well, the Followers, for one.}
{151}{}{From where I stand, it looks like everyone.}
{152}{MORP17}{ Tell me what you know. }
{153}{}{I don't think so. Take me to the Master. Him, I'll tell.}
{154}{}{Let's just say I know something to help you out against them.}
{155}{MORP18}{ Give me the information or die a slow... lingering... death. }
{156}{}{Think the Master would be happy if you killed a vault-dweller?}
{157}{}{I'm only talking to the Master.}
{158}{MORP19}{Ahh... So you are the Vault Dweller I've been hearing about. Surprised? I have my sources. Now, I will take you as a gift to the Master. He'll be very pleased. }
{159}{}{How about we take you out in a bag, instead?}
{160}{}{And so will I.}
{161}{MORP20}{ A spy? Very foolish of you. It will be difficult to report to him when you are dead, won't it? }
{162}{MORP21}{ You are a bad liar. Now, tell me what you want. }
{163}{}{I'm from a Vault. You do know what that is, right?}
{164}{}{I'd like to offer you some information about your enemies.}
{165}{MORP23}{ How surprising. Now tell me why you are here. }
{166}{}{I'm from a Vault, and I'm willing to give the Master the location.}
{167}{}{I'd like to offer you some information about your enemies.}
{168}{}{You're not very intimidating.}
{169}{}{I won't tell you anything.}
{170}{MORP24}{ Oh, really? And how do you plan to do that? With your stunning wit and sharp tongue? }
{171}{}{No, with this...}
{172}{}{That would be too easy against you. I'll go the more challenging route.}
{173}{}{I think a bullet to the head will do.}
{174}{MORP26}{ Here's your deal. Tell me what you know, and you'll be able to walk out of here on both legs.}
{175}{}{I'm from a Vault, and I'm willing to give the Master the location.}
{176}{}{I'd like to offer you some information about your enemies.}
{177}{}{You're not very intimidating.}
{178}{}{I won't tell you anything.}
{179}{MORP27}{ I ask the questions, not you. Now, tell me what you are doing here. }
{180}{}{I'm just lost.}
{181}{}{I'm here to make you a deal.}
{182}{morp28}{Yes?}
{183}{}{Hi. I'm new to the Children and was wondering if I could ask you a few questions.}
{184}{}{Never mind.}
{185}{}{Nuhhh?}
{186}{morp29}{Of course, my child.}
{187}{}{Thanks...}
{188}{}{Never mind.}
{189}{}{What are the Children's plans?}
{190}{}{Changed my mind. No more questions.}
{191}{}{What you say if I told you I'm from a Vault?}
{192}{MORP31}{ Our plans? We are the messengers of evolution, my child. We follow the Master in his endless quest to heal the land and the people.}
{193}{}{Really? Just what kind of evolution are you teaching?}
{194}{}{What kind of healing?}
{195}{MORP32}{ We know there is a higher level, a glorious place humanity should strive to reach. Ours is the goal to find the life better, more fulfilling, than the present one, marred by hardship and strife. }
{196}{}{You're kidding, right?}
{197}{}{And have you found this higher level ?}
{198}{MORP33}{[Angry]Why you!... [Calmly] You are forgiven. Not everyone is capable of seeing the light. But, tell me my child, why did you join us? }
{199}{}{I had to see if this was as much of a joke as I'd heard. Now I know.}
{200}{}{Sorry. I guess I was out of line.}
{201}{morp34}{You know nothing.}
{202}{MORP35}{ Yes, you were, but you are forgiven. Now, if there are no more questions, I have work to do. }
{203}{}{Actually, there are some more.}
{204}{}{Nope, thanks.}
{205}{MORP36}{Of course. Please. Continue.}
{206}{MORP37}{ Yes, but you are... forgiven. Go in peace, my child. }
{207}{MORP38}{ No, but with faith and hope, we're certain to find it. But all this should be known to you, my child.}
{208}{}{I know, but just a few more questions, please.}
{209}{}{I know. Goodbye.}
{210}{MORP39}{ We cure the physical body to start. You've certainly seen our hospitals. Then we offer hope and healing for the spirit. }
{211}{}{Wow. I almost believed that. You're good!}
{212}{}{Where are these hospitals?}
{213}{MORP40}{ Our glorious effort has just reached Adytum and, of course, the Hub shines with our efforts there. But, I have a feeling there's more you wish to ask. }
{214}{MORP41}{ These are wondrous days. Junktown now joins in Adytum and the Hub in our quest to save body and soul. Is there more you wish to know, my child? }
{215}{}{As a matter of fact... }
{216}{}{Nothing. I gotta go.}
{217}{MORP42}{ The Children's vision now stretches from Adytum, to the Hub, Junktown, and now gently caresses Shady Sands. Why do you ask? }
{218}{}{Just wondering. Can I ask you a few more questions?}
{219}{}{Nothing. I gotta go.}
{220}{MORP42A}{ You are what? }
{221}{}{You heard me. Take me to see the Master, now!}
{222}{MORP42B}{ Uh, yes. Well. Please follow me. }
{223}{MORP42C}{ Oh, my child, you make no sense whatsoever. Please, find one of our physicians and get help. }
{224}{MORP45}{ My child, talk to Lasher. He'll help you with that. }
{225}{MORP46}{ I said... }
{226}{MORP47}{ Are you deaf? I said...}
{227}{MORP48}{ I will not repeat myself again! }
{228}{MORP49}{ I will not say it again! }
{229}{MORP50}{The Nightkin came to us a while ago. They might be hideous mutants but they are extremely loyal to the Children. As we all are.}
{230}{MORP51}{It is he who brought me the vision of the Unity and it is he who will bring peace to this troubled land.}
{231}{MORP52}{My child, you should know the Auditorium. I give my sermons there. }
{232}{MORP53}{Don't concern yourself with that. Only the High Priests may enter. }
{233}{MORP54}{I am but a humble servant of the Unity. }
{234}{MORP55}{We are the High Priests of the great Dark God. Thirteen of us are so blessed to pass his mighty words to the rest of the Children. }
{235}{MORP56}{I've no idea what you're talking about. }
{236}{MORP57}{The Children of the Cathedral hospitals provide the best care in all of this blasted, torn land. This care is vital to the Unity.}
{237}{MORP58}{The Unity is our search for a higher level of life, and unity with our fellow man. }
{238}{MORP59}{He is another High Priest. He spends much of his time in the studies. }
{239}{MORP60}{My heart bleeds for them. Led down a false path. They don't know their efforts will bring only pain and suffering to their fellow beings.}
{240}{MORP61}{Nicole is the unfortunate, confused leader of the Followers of the Apocalypse. }
{241}{MORP62}{Adytum is the city to the northeast of us. }
{242}{MORP63}{That's not important. }
{243}{MORP64}{That's nothing. You may ask something else. }
{244}{morp65}{Nothing to be concerned with.}
{245}{}{Master, I believe you will enjoy this... }
{500}{}{ experience for destroying the leader of the Children of the Cathedral.}


# Morpheus Tell-Me-Abouts generic responses
{980}{MORP63}{That's not important. }
{981}{MORP64}{That's nothing. You may ask something else. }
{982}{morp65}{Nothing to be concerned with.}


#
# Morpheus Tell-Me-Abouts
#


{1000}{}{Nightkin}
{1001}{}{Master}
{1002}{}{Auditorium}
{1003}{}{Sanctum}
{1004}{}{Morpheus}
{1005}{}{Order}
{1006}{}{Caravans}
{1007}{}{Hospitals}
{1008}{}{Unity}
{1009}{}{Lasher}
{1010}{}{Followers}
{1011}{}{Nicole}
{1012}{}{Adytum}
{1013}{}{Apocalypse}
{1014}{}{Mutants}
{1015}{}{Holy Flame}
{1016}{}{Children}
{1017}{}{Base}
{1018}{}{Chip}


{1100}{MORP50}{The Nightkin came to us a while ago. They might be hideous mutants but they are extremely loyal to the Children. As we all are.}
{1101}{MORP51}{It is he who brought me the vision of the Unity and it is he who will bring peace to this troubled land.}
{1102}{MORP52}{My child, you should know the Auditorium. I give my sermons there. }
{1103}{MORP53}{Don't concern yourself with that. Only the High Priests may enter. }
{1104}{MORP54}{I am but a humble servant of the Unity. }
{1105}{MORP55}{We are the High Priests of the great Dark God. Thirteen of us are so blessed to pass his mighty words to the rest of the Children. }
{1106}{MORP56}{I've no idea what you're talking about. }
{1107}{MORP57}{The Children of the Cathedral hospitals provide the best care in all of this blasted, torn land. This care is vital to the Unity.}
{1108}{MORP58}{The Unity is our search for a higher level of life, and unity with our fellow man. }
{1109}{MORP59}{He is another High Priest. He spends much of his time in the studies. }
{1110}{MORP60}{My heart bleeds for them. Led down a false path. They don't know their efforts will bring only pain and suffering to their fellow beings.}
{1111}{MORP61}{Nicole is the unfortunate, confused leader of the Followers of the Apocalypse. }
{1112}{MORP62}{Adytum is the city to the northeast of us. }
{1113}{MORP60}{My heart bleeds for them. Led down a false path. They don't know their efforts will bring only pain and suffering to their fellow beings.}
{1114}{MORP50}{The Nightkin came to us a while ago. They might be hideous mutants but they are extremely loyal to the Children. As we all are.}
{1115}{morp65}{Nothing to be concerned with.}
{1116}{morp65}{Nothing to be concerned with.}
{1117}{morp65}{Nothing to be concerned with.}
{1118}{morp65}{Nothing to be concerned with.}
