{100}{}{This motorcycle doesn't appear to be functional. Still, it looks to be in better shape than the other motorcycle
 in the area. Maybe this one can be fixed.}
{101}{}{Currently, this motorcycle doesn't appear to be functional. It needs a fuel cell controller.}

{200}{}{You successfully repair the motorcycle with the fuel cell controller.}
{210}{}{You fail to repair the motorcycle with the fuel cell controller.}

{220}{}{You successfully attach the fuel cell regulator.}
{230}{}{You fail to install the fuel cell regulator.}

{250}{}{The motorcycle is out of fuel. Refuel the vehicle to get it started again.}

{300}{}{You fail to repair the vehicle. Maybe with the fuel cell controller that Smitty was talking
 about it could be repaired.}

{400}{}{It would be too noisy to pop open the hood and work on the car.}

# Fo1in2:
{450}{}{The motorcycle isn't operational.}
{451}{}{The motorcycle doesn't require any repairs.}
{452}{}{The key fits!}
{453}{}{Looks like the fuel cell controller was removed as a precaution. Maybe it's still around somewhere here?}
{454}{}{Looks like you need a key to start the motorcycle.}

{500}{}{The motorcycle isn't big enough for your party!}
{501}{}{Not all of us will fit on the bike.}
{502}{}{Someone will have to wait here.}
{503}{}{The bike isn't big enough for all of us.}
{504}{}{That really won't work for us.}
{505}{}{I have a bad feeling about this.}

{510}{}{You charge the bike with more power.}
{511}{}{The bike is already fully charged.}
{512}{}{The bike is running at }
{513}{}{% power.}

{520}{}{The fuel cell regulator is missing.}


