{100}{}{You see: Neil, the head of the guard for the Followers.}
{101}{}{You see: Neil, the head of the guard for the Followers.}
{102}{}{If you seek someone to talk to, talk to Peter. I'm trying to get some sleep.}
{103}{}{Why are you here?}
{104}{}{Hrr. Arrooo?}
{105}{}{Nuh nuh.}
{106}{}{KILL!!}
{107}{}{I'm }
{108}{}{. I was sent to look for you.}
{109}{}{I'm }
{110}{}{. And you are dead.}
{111}{}{What can you tell me about the Followers?}
{112}{}{I have come to offer my assistance.}
{113}{}{I seek ways in which to instill peace upon this desolate wasteland.}
{114}{}{I am sorry, but I can't understand you. Now, what are you doing here?}
{115}{}{Nuh nuh.}
{116}{}{Me Kill!!}
{117}{}{Hep. Me hep.}
{118}{}{If you are doing nothing, then I suggest that you leave. Now!}
{119}{}{You wish to help? Maybe I can use you.}
{120}{}{Yes. Me hep! Me hep!}
{121}{}{No. No hep!}
{122}{}{You are simple enough to find this person that others are too smart to find. There is a spy around here who is giving our secrets to the Children. Find the spy. Kill the spy. Go.}
{123}{}{I thought as much. Be off with you.}
{124}{}{Figures that Jake doesn't think that I can get the job done right. He's the only one who could have sent you. Then you know about the spy.}
{125}{}{Jake didn't send me. One of your guards did.}
{126}{}{I know some. Jake was very short with words.}
{127}{}{What is this about a spy? Maybe I can help.}
{128}{}{My guards are no fools. They sent you to the right person. There is a leak in here, and we need to find out where it is and seal it.}
{129}{}{Have any leads?}
{130}{}{I'm a fighter, not a plumber. If you have leaks, talk to someone else.}
{131}{}{I think you are the leak. Die!!}
{132}{}{Forget it. I'm nobody's lackey.}
{133}{}{The only thing that we know so far is that the person has to have access to the Children's Cathedral. I think it may be one of our scouts.}
{134}{}{Okay. I will check it out right now.}
{135}{}{Are you sure it is not a guard?}
{136}{}{Tough luck then. You'll never catch the person now.}
{137}{}{I am quite certain. They only have access to the halls of the Followers. They are not allowed outside.}
{138}{}{Then I don't know who it could be.}
{139}{}{I'll look into the scouts then.}
{140}{}{I think there is a cover-up here. You die!}
{141}{}{That is why I am asking you to look around and see if you can find someone. Will you help?}
{142}{}{Yes.}
{143}{}{No.}
{144}{}{Thank you. This means a lot to us.}
{145}{}{Then I must detain you from warning anyone.}
{146}{}{How he ever became second in command is beyond me. Since he was so scarce in words, I will fill you in. We have a leak who is feeding the Children some of our movement patterns.}
{147}{}{Have any leads?}
{148}{}{I'm a fighter, not a plumber. If you have leaks, talk to someone else.}
{149}{}{I think you are the leak. Die!!}
{150}{}{Forget it. I'm nobody's lackey.}
{151}{}{You don't even know? I guess you wouldn't; most people in here don't. Someone is sneaking information of our movements to the Children. We need that person gone.}
{152}{}{Have any leads?}
{153}{}{I think you are the leak. Die!!}
{154}{}{Forget it. I'm nobody's lackey.}
{155}{}{How much are you willing to offer?}
{156}{}{I don't have much money. How about 200 caps?}
{157}{}{Sorry, I'm broke.}
{158}{}{Your life.}
{159}{}{Sounds fair to me.}
{160}{}{Now I will end this leak in the Followers!}
{161}{}{Tough luck then.}
{162}{}{What would you like to know?}
{163}{}{Who is the leader?}
{164}{}{Why are you attacking the Children?}
{165}{}{Where can I get some first aid?}
{166}{}{Nothing. Just checking.}
{167}{}{Nothing. Thank you.}
{168}{}{Our leader is Nicole. Really nice person, but a bit flighty. Anything else you want to know?}
{169}{}{Why are you attacking the Children?}
{170}{}{Where can I get some healing?}
{171}{}{Nothing. Just checking. [slap him]}
{172}{}{Nothing. Thank you.}
{173}{}{The Children are not what they appear to be. They are hiding something. Something related to those Nightkin. Anything else?}
{174}{}{Who is the leader?}
{175}{}{Where can I get some healing?}
{176}{}{Nothing. Just checking. [slap him]}
{177}{}{Nothing. Thank you.}
{178}{}{There is the Children's healer, but I don't trust them. We also have a doctor or nurse on duty here at all times. Anything else?}
{179}{}{Who is the leader?}
{180}{}{Why are you attacking the Children?}
{181}{}{Nothing. Just checking. [slap him]}
{182}{}{Nothing. Thank you.}
{183}{}{I am truly sorry to hear that. Pieces be with you!}
{184}{}{Who sent you?}
{185}{}{Your guard sent me.}
{186}{}{Jake sent me.}
{187}{}{I sent me.}
{188}{}{Never mind. Goodbye.}
{189}{}{A bit sure of yourself. I have no need for you. Talk to Nicole if you wish to offer your services. Good night.}
{190}{}{Then you will want to search out Nicole. She can help you better with that. Good evening.}
{191}{}{Go find that spy. We need to keep our plans secret still longer.}
{192}{}{Good job on finding and removing Heather. Her meddling nearly got everyone killed. I wish there was something more we could do.}
{193}{}{Perhaps I can help you once more.}
{194}{}{Good luck to you.}
{195}{}{How so?}
{196}{}{I can train the Followers in some skills for war. Maybe your chances will improve.}
{197}{}{I can leave. Goodbye.}
{198}{}{That would be wonderful. Thank you.}
{199}{}{Now you are a bit more prepared. Good evening.}
{200}{}{Thank you for your teachings. Now we have a chance to beat back those Children.}
