{100}{}{Get out of here!}
{101}{}{I've heard bad things about you, are they true?}
{102}{}{Hi.}
{103}{}{This is my place, wanna hang out for a while?}
{104}{}{Hmm, you look juicy... }
{105}{}{I hope you're not going to kick me out of here.}
{106}{}{No.}
{107}{}{That's a strange way to start a conversation.}
{108}{}{Hnnn.}
{109}{}{Oh, well, if you want to stay a while, go right ahead. I think we are safe here.}
{110}{}{Well, you gotta be careful these days. I hope you're having a better life than I am.}
{111}{}{Well, it's true. After what happened to my friends, I gotta protect my turf. I just hope you're not gonna kill me.}
{112}{}{No, I won't hurt you. Much.}
{113}{}{Why do you say that?}
{114}{}{Gack!}
{115}{}{No reason. Really.}
# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
{116}{}{Those 'helpful' healing guys wanted my friend's place, so they took it. I don't know what happened to my friends.}
{117}{}{ And Killian is too busy to help me.}
{118}{}{ Killian is too busy cleaning up Gizmo's mess to help.}
{119}{}{ Gizmo laughed at me when I asked for his help.}
{120}{}{ There's nobody around to help me.}
{121}{}{Are you safe?}
{122}{}{That's a shame.}
{123}{}{I hope so, I really hope so.}
{124}{}{Please leave me alone!}
