{100}{}{You see: Rae.}
{101}{}{You see a Super Mutant.}

{102}{}{You don't belong here.}

# Orig. line: "(seems confused and sad) I believe I do, but.. why are you here?"
{103}{}{I believe I do, but.. why are you here?}

{104}{}{Neither do you.}
{105}{}{Uh.. yes I do. The Master is having me scout around in disguise to check our security.}
{106}{}{Yes I do, I'm here to kill you.}
{107}{}{Okay, I'm leaving.}
{108}{}{huh.}
{109}{}{(sigh) What do you want now?}
{110}{}{I'm lost.. can you show me how to get to the Master? I need to kill him.}
{111}{}{Nothing. Goodbye.}
{112}{}{To see what you look like with all your skin ripped off your body, you mutant scum.}
{113}{}{What's wrong with you?}
{114}{}{great oogly moogly.}
{115}{}{I'm here to... contemplate the oneness of the Master.}
{116}{}{Of course. The unity brings peace. May I ask where you are from?}
{117}{}{I am as well. I made the pilgrimage from far away to see the Master with my own eyes.}
{118}{}{I have much to learn. How does one gain an audience with the Master?}
{119}{}{I did that yesterday. Today I'm contemplating what the Master would look like if I lit him on fire and roasted marshmallows over his putrid carcass.}
{120}{}{I think the Master is insane.}
{121}{}{I'm from... somewhere ..else.}
{122}{}{What a coincidence! So am I.}
{123}{}{Where?}
{124}{}{I'm from a Vault... I'm a pure strain human.}
{125}{}{What, are you an imbecile?}
{126}{}{Where are you from?}
{127}{}{(whispers) I'm from a Vault... I'm a pure strain human.}
{128}{}{I'd rather not say. Goodbye.}
{129}{}{A small village to the north of here.}
{130}{}{Why should I tell you? You're just a lackey for the 'Man'.}
{131}{}{Why would you tell me that? I should take you before the Master...}
{132}{}{But you won't}
{133}{}{You're welcome to try.}
{134}{}{Well, I should shove my gun down your throat and pull the trigger!}
{135}{}{Please don't.}
{136}{}{I know why you're in so much pain.}
{137}{}{I'll be going now.}
{138}{}{You're right... if only I could clear my head. There's something...}
{139}{}{I know why you can't clear your head.}
{140}{}{The Master keeps you from thinking clearly. Thinking disturbs the unity.}
{141}{}{The Master is the reason you are in such pain.}
{142}{}{Hey, I've got an idea - let's cut open the Master and see what's inside!!!}
{143}{}{Tell me! Please!!}
{144}{}{You used to be human, too. The Master dipped you in the Forced Evolutionary Virus and mutated you.}
{145}{}{Sorry, I can't.}
{146}{}{Only the Master can tell you everything.}
{147}{}{Only the Master can tell you everything. But you'd better talk to him quick, 'cause I'm on my way to kill him.}
{148}{}{Sorry, got to go.}
{149}{}{I should kill you for taunting me!}
{150}{}{I have a better idea - help me destroy the Master for doing this to you.}
{151}{}{No, you should kill the Master for doing this to you. I'm on my way to do just that... would you like to join me?}
{152}{}{Why? I'm not the one who turned you into a mutant!}
{153}{}{You're welcome to try.}
{154}{}{No thanks. Bye!}
{155}{}{Let's twist his head until his eyes pop out.}
{156}{}{You will never kill the Master. He cannot die.}
{157}{}{You're right. I'd better get out of here.}
{158}{}{We'll see about that.}
{159}{}{Hmmm. I wonder how he'll continue to live when his unity is destroyed...}
{160}{}{That can't be.. the Master.. protects... unifies...}
{161}{}{Well, you're a living example of 'unification', my friend. I know, I've seen the process. I'm here to stop the Master from 'unifying' anyone else.}
{162}{}{How does it feel to be protected and unified?}
{163}{}{Yeah, he protects himself by controlling everyone else.}
{164}{}{I've had enough of this. Goodbye.}
{165}{}{Leave now or I will be forced to deal with you.}
{166}{}{AAAUGH!!! (Grabs his head in pain and confusion) I.. can't...}
{167}{}{That's right, your friend the Master stripped you of everything you had in this world, including your humanity.}
{168}{}{You know that it's true... that's why you're so confused. You're fighting the mutation. Help me avenge you by destroying the Master!}
{169}{}{Sure you can. C'mon, let's kill the Master, it will be fun.} 
{170}{}{I'd better leave.}
{171}{}{I'm sorry you're in such pain, but it's the Master's fault.}
{172}{}{I will pull his eye out!! I'll tear his slimy little head from its cables!!!! You, get out of here... I'll take care of the Master.}
{173}{}{Great!!}
{174}{}{Thanks for the offer, but I'd like to do the job myself. Would you like to help?}
{175}{}{I'm going to stay here. I have some unfinished business.}

# Fo1in2
# You gain x experience ...
{200}{}{ for convincnig Rae to destroy the Master.}
{201}{}{ for convincing Rae to fight with you against the Master.}
{202}{}{It is done. Leave now.}

