{100}{}{You see: Mitch, the manager of the All-In-One Store.}
{101}{}{Looking for something?}
{102}{}{What're you looking for today?}
{103}{}{What can I help you with?}
{104}{}{I've got it all, what's it you need?}
{105}{}{Need supplies?}
{106}{}{Looking to buy?}
{107}{}{What'll it be?}
{108}{}{Got anything good to trade?}
{109}{}{What ya got?}
{110}{}{Make me an offer.}
{111}{}{I'll cut you a deal.}
{112}{}{Come again.}
{113}{}{Thanks, see you again soon.}
{114}{}{Bye.}
{115}{}{Watch your purse.}
{116}{}{If you need anything, just let me know.}
{117}{}{Watch your step.}
{118}{}{Find anything good, bring it back.}
{119}{}{Don't be a stranger.}
{120}{}{I have all the good stuff.}
{121}{}{What?}
{122}{}{Mitch runs this place, not me.}
{123}{}{I'm off to the Falcon when I'm off!}
{124}{}{Stay out of trouble.}
{125}{}{Watch it.}
{126}{}{You lookin' at me?}
{127}{}{I better not catch you stealing.}
{128}{}{Welcome to the All-In-One Store.}
{129}{}{Buy something already!}
{130}{}{You trying to cause trouble?}
{131}{}{We're closed.}
{132}{}{We're closed.}
