{100}{}{The hairs on the back of your neck rise. You feel something from the corridor ahead. The bile rises as your recognize the mass of flesh ahead - human parts in the wall itself. The worst part is that it is moving, calling to you.}
{101}{}{Your nose starts to bleed. You hear voices in your head. They are calling your name. Darkness washes over your eyes for a moment, but you recover.}
{102}{}{A voice calls to you. You turn you head and see the image of a forgotten friend, obviously dead. The worms fall from her rotted jaw as your headache grows.}
{103}{}{It is getting harder to move forward. Your foot seems bonded to the floor. You look down, and the flesh of the floor is crawling up your leg. Teeth gnaw at your knees. Still, your headache gets worse.}
{104}{}{Something catches your attention, a flash of movement from the ceiling, and then a sliver of bone pierces your eye! With it comes the thoughts of the dead and tortured!}
{105}{}{The pain in your head is maddening. You feel the sins of others wash over your soul. And it gets worse, as your sins answer them. Like madmen, they fight through your psyche, and in the process tear your personality apart.}
{106}{}{Your head is pulsing with the intrusive thoughts of others. The pain grows and grows. Suddenly, as if it never existed, the pain vanishes. You fall to the ground and weep. But something does not feel right.}
{107}{}{The pain in your head does not feel as bad as it did. The effects of this strange corridor do not feel as strong.}

#	Fallout Fixt -- Sduibek
#
{250}{}{You have permanently lost 1 point of Perception.}
{251}{}{You have permanently lost 1 point of Intelligence.}
