# Coast1  3 to 5 floaters or bloody floaters
{100}{}{You see several odd-looking floating creatures...}
#
# Coast2  4 to 7 manti or great manti
{111}{}{You are suddenly attacked by a swarm of mutated manti!}
#
# Coast3  8 to 12 rats
{101}{}{A swarm of rats is rapidly approaching!}
#
# Coast4  3 to 4 raiders, 3 to 5 peasants
{102}{}{You see a group of peasants being attacked by raiders!}
#
# Coast5  4 to 6 manti
# msg 111
#
# Coast6  fishermen
{103}{}{You see a few people out fishing.}
#
# Coast7  free items
{104}{}{There is a grisly corpse nearby that's been partially eaten. You've just lost your appetite.}
#

#
# NOT USED (from vanilla)
#
{105}{}{You stumble upon some water pools.}
{106}{}{Out of dire thirst, you drink some water... It doesn't taste so good.}
{107}{}{The water looks highly radioactive and foul.}
{108}{}{Ahhh...}
{109}{}{Arrgg...}
{110}{}{Yuck!}
