{100}{}{The security door is locked.}
{101}{}{The security door is not locked.}
{102}{}{You manage to unlock the security door.}
{103}{}{You fail to unlock the security door.}
{104}{}{You manage to trigger the passive alert on the door, clamping down the electronic lock. Good job, chromo.}
{105}{}{You earn }
{106}{}{ experience for picking the lock.}

# Fo1in2
{200}{}{ manages to unlock the security door.}
{201}{}{ fails to unlock the security door.}
{202}{}{ manages to trigger the passive alert on the door, clamping down the electronic lock.}
