{100}{}{You see: Talus.}
{101}{}{Hello, you must be the outsider Initiate. Nice to meet you. What can I do for you?}
{102}{}{Who is the leader of your organization?}
{103}{}{So, are you in charge around here?}
{104}{}{How do I get better weapons and equipment?}
{105}{}{Chagga!}
{106}{}{That would be the Council of Elders. More specifically, the High Elder, Maxson. The Elders make all the major decisions around here. If you need to speak with them, you'll find them on the fourth floor.}
{107}{}{So what do you do?}
{108}{}{No, we are directed by the Council of Elders. Maxson, the High Elder, would be the person in charge. If you need to speak with him, you'll find him on the fourth floor.}
{109}{}{I really need some better firepower.}
{110}{}{I'm the Senior Paladin, Rhombus's right-hand man. We're in charge of the Paladins and Knights. Right now I'm supervising training exercises. We're getting ready... for anything.}
{111}{}{You're getting ready for what?}
{112}{}{How can I get some weapons and equipment?}
{113}{}{There are rumors of a large force moving around in the mountains and desert. With the missing caravans and these rumors, we're just playing it safe.}
{115}{}{Really? Okay, thanks.}
{116}{}{In a hurry, are we? As an Initiate, you are entitled to a few things. I'll put in a clearance for combat armor and three orders for ammunition, bullets of your choice. Just see Michael in the next room for the supplies.}
{117}{}{I am very grateful, but do you by any chance have a weapon you can spare that might help my chances of survival out there?}
{118}{}{Thanks, what about some high-tech weapons?}
{119}{}{That's it? You've got to be kidding!}
{120}{}{I understand, but I'm really pressed for time and I really need some better firepower.}
{121}{}{Great! What do I have to do now? Climb the highest mountain?}
{122}{}{That sounds great. Why don't you start now?}
{123}{}{Well, I might be able to make an exception. You obviously have some good training. If you didn't you wouldn't have succeeded in that crazy quest the High Elder sent you on.}
{124}{}{Sometimes I don't know if he's trying to get help from the outside, or kill off the stupid. No offense. I'll tell you what. I'm sort of in a tight spot because the scouts I sent out a while back never returned.}
{125}{}{It was my idea, and I'm sort of taking some heat for it. If you can find out what happened to them, I'll make it worth your while.}
{126}{}{I'll think about it.}
{127}{}{Excuse me, Initiate. Please don't brandish your weapon. Put it away unless you plan on using it.}
{128}{}{Holster your weapon, Initiate. You're not in a training exercise, put it away.}
{129}{}{Would you stop waving your weapon around like that? You should... oh, never mind.}
{130}{}{Hello again, Brother }
{131}{}{. How can I help you?}
{132}{}{Who are the important people around here?}
{133}{}{Could you tell me about those important people again?}
{134}{}{How can I get some better equipment and weapons?}
{135}{}{Can I get some more ammo?}
{136}{}{Nothing, thanks.}
{137}{}{I can help you with that. As an Initiate, you are entitled to a few things. I'll put in a clearance for combat armor and three orders for ammunition, bullets of your choice.}
{138}{}{Just see Michael in the next room for the supplies.}
{139}{}{What about that metal suit you're wearing?}
{140}{}{Thanks, what about some high-tech weapons?}
{141}{}{Well, we are all important, but I know who you are referring to.}
{142}{}{That's not a problem. You should get to know your fellow Brothers well. I know there are a lot of us, and that it can be hard for some to remember us all.}
{143}{}{There's Rhombus. He's our Head Paladin, also known as the Master Knight. Then there's Vree; she's the Head Scribe. And of course we cannot forget our distinguished High Elder, Maxson.}
{144}{}{Tell me about Rhombus.}
{145}{}{Tell me about Vree.}
{146}{}{Tell me about Maxson.}
{147}{}{Rhombus is my best friend, mentor, idol, and father figure all combined into one. He's a little rough, but he has to be, to be in the position he's in.}
{148}{}{If you ever need to talk to him, he is normally in his office...  I mean room. That's on the other side of this level, across from the guard room.}
{149}{}{Of course we do. She's on the second level. Next to the learning room.}
{150}{}{Thanks, bye.}
{151}{}{Thank you. That's all I wanted to know.}
{152}{}{Vree is one of the most intelligent people I've ever known. I think she was born with the natural understanding of physics and chemistry.}
{153}{}{She spends every waking moment doing research or analyzing and reanalyzing anything she can get her hands on. If you ever need to talk to her, she can normally be found in her room, on the third floor.}
{154}{}{She's on the second level. Just go down to the second floor, make a left. You'll see it just past the learning room. I should get back to work. If you have any other questions just ask.}
{155}{}{As I said, she's on the second level. You can't miss it. It's the only other major room on the second floor besides the learning room.}
{156}{}{Okay, see ya.}
{157}{}{Maxson is one tough old man. He's the great, great grandson...  or was it great, great, great grandson? Well, anyway. He's the descendant of one of our founding fathers. He, of course, is the High Elder.}
{158}{}{You've built quite a reputation for yourself. The people I've checked with hold you in high regard. I don't think you need any help, you seem quite capable. However, if you help me with a little problem, I might be able to reward you with something.}
{159}{}{Thanks a lot, bye.}
{160}{}{That's it, thanks.}
{161}{}{You're getting on my nerves, little one. What do you want now?}
{162}{}{Nothing, just wanted to hear your pleasant voice.}
{163}{}{Sorry, didn't see you there.}
{164}{}{Cha Toh Weh Lo!}
{165}{}{Ug.}
{166}{}{Stop wasting my time!}
{167}{}{How did you get in here? Get out of my sight.}
{168}{}{I can give you a little more ammunition if you really need it. I'll have it authorized by the time you can talk to Michael.}
{169}{}{I just gave you some. You should learn to be more conservative with your ammunition.}
{170}{}{Sorry, you've had more than your share for this week. You'll have to make do with what you have. We don't have an endless supply of ammunition.}
{171}{}{I've heard about some of the things you've done and we don't take kindly to child killers. The Elders seem to think that there's something you can offer but I don't want to have anything to do with you.}
{172}{}{I only killed one.}
{173}{}{You don't know the whole story.}
{174}{}{I don't have to answer to you.}
{175}{}{You've built quite a reputation for yourself. I don't think you need any help, you seem quite capable. However, there is something I need looking into, and I might be able to help you if you can help me.}
{176}{}{Sure. What's the problem?}
{177}{}{No thanks and thanks for nothing.}
{178}{}{Sorry, I can't. Thanks for the armor, though.}
{179}{}{Since you were able to survive the wasteland alone, I think you're probably quite capable. However, I do have a problem that I could use some help with and I might be able to reward you for your help.}
{180}{}{No. I think you should leave.}
{181}{}{I sent one of our Initiates out to the Hub a short while back and we haven't heard back from him. If you can find out what happened to him I'd be very grateful.}
{182}{}{I'll check it out.}
{183}{}{I'll try but I can't promise anything.}
{184}{}{I told you to leave.}
{185}{}{Only? I don't think our order will be able to help you. Good day.}
{186}{}{I don't need to know the whole story. Good day.}
{187}{}{Thank you. I'll remember this and when I've seen that you've gained enough experience I might be able to give you something special from our order.}
{188}{}{Really? What?}
{189}{}{Give it to me now!}
{190}{}{Sounds good. Bye.}
{191}{}{I shouldn't say, but it's not a weapon. It's something that only the elite in our order can have, but since you are from the outside and are in greater need of it, I might be able to make an exception.}
{192}{}{Can't you tell me?}
{193}{}{Okay, bye.}
{194}{}{I think you probably already have an idea. Let's leave it at that.}
{195}{}{No, I'm not and I think you should leave, 'Initiate'.}
{196}{}{Only Paladins wear Power Armor, someday you may earn the right to wear it.}
{197}{}{Thanks, what about some high-tech weapons?}
{198}{}{Well I see we have a bright new addition to our order after all... [Talus leers at you.] Don't get cocky with me, Initiate. I'm not in the mood nor have I the patience!}
{199}{}{I thought you were smarter than that. I don't have to give you anything. You're lucky I don't kick you out of here, right now. I think you should leave, before I change my mind.}
{200}{}{That's okay. Anything you might find would be helpful.}
{201}{}{Brother }
{202}{}{! I've received word from Brother Jonathan. Thank you for rescuing him.}
{203}{}{I understand Decker's dead, you're more talented than I thought, and that's saying a lot.}
{204}{}{We'll make Decker pay for what he's done, you have my word on that.}
{205}{}{You're welcome.}
{206}{}{Lup?}
{207}{}{Hello stranger! I heard you're the one to thank for the safe return of my missing Initiate.}
{208}{}{I also understand that Decker's dead, you're quite an asset to our Brotherhood.}
{209}{}{We don't tolerate drug users around here. I suggest you see the doctor and clean yourself up.}
{210}{}{As for your reward, I'll give you the choice of one of the following:}
{211}{}{So which would you prefer?}
{212}{}{Rocket Launcher.}
{213}{}{Laser Pistol.}
{214}{}{Super Sledgehammer.}
{215}{}{Let me think about it.}
{216}{}{I'll key your authorization in right now. Go pick it up from Michael.}
{217}{}{, it is time you wore your own suit of Power Armor. This is a very special privilege for one so new to our order. Wear our Power Armor as a symbol of hope as you walk the wasteland, for someday when the world is ready we will surface and restore our battered Earth. Congratulations, you have made us all very proud. I'll send Michael the authorization.}
{218}{}{I see someone else already gave you your suit of Power Armor. I was hoping to give it to you myself, but that's all right. I hope it helps you in your quest.}
{219}{}{Watch your form!}
{220}{}{Pay attention, people.}
{221}{}{No slacking off!}
{222}{}{Behave over there, or you'll find yourself on night perimeter patrol.}
{223}{}{Quiet, don't make me bring Rhombus in here. He'll whup all your asses.}
{300}{}{Please, if you need something see me in the morning.}
{301}{}{I'll be in the training hall come morning. Talk to me then.}
{302}{}{What are you doing in here? These aren't your quarters.}
{303}{}{Good night Initiate, talk to me in the morning. It can't be that urgent.}
{304}{}{I'm tired and I want to go to bed, please leave.}
{305}{}{Do you normally bother people in their living quarters?}
{400}{}{You can always... wait a minute. Look me straight in the eyes... I thought so. You should lay off the drugs, they can really mess you up. If you don't watch it you'll end up like the skags at the Hub. So what was it you needed?}
{401}{}{Do you have a doctor? I'm hurt.}
{402}{}{Do you have a doctor?}
{403}{}{I'm done climbing that mountain.}
{404}{}{Where's your doctor located?}
{406}{}{Hmmm, I don't know. You may have proven yourself to be an Initiate but that doesn't mean we start handing over weapons to someone that might not be qualified, especially an outsider, no offense.}
{407}{}{Power Armor.}
{408}{}{You earn }
{409}{}{ experience for rescuing the Brotherhood of Steel Initiate from The Hub.}

#Fo1in2
{410}{}{Magneto-Laser Pistol.}

