{100}{}{You see: Tandi.}
{101}{}{What else is around these parts?}
{102}{}{What's going on around here?}
{103}{}{Have you heard any stories from down south?}
{104}{}{How do you like it here?}
{105}{}{Well, that's about it. Thanks for your time.}
{106}{TAND_1}{Hi! I heard there was a traveler in town, but I was kinda skeptical until I saw you. My name's Tandi, what's yours?}
{107}{}{My name is }
{108}{}{.}
{109}{}{The name is }
{110}{}{. Remember it.}
{111}{}{Uhhh?}
{112}{tand_2}{Well... how do you like our little town? Bored yet?}
{113}{}{It's okay. Can I ask you a few questions, though?}
{114}{}{Hell, yes. There's nothing to do here but watch the brahmin mate.}
{115}{}{I guess it's okay.}
{116}{}{Well, yes. It is a bit boring.}
{117}{TAND_3}{ Sure, I guess. I've never been out of here, so I don't know what help I can be. So, what'cha need?}
{118}{TAND_4}{Yeah. Well you don't live here. There's nothing interesting to do, and believe you me, Brahma Tipping gets old real fast.}
{119}{}{If you're so bored, why don't you leave?}
{120}{}{Well, I'm sure you're exaggerating.}
{121}{}{It seems nice and safe here.}
{122}{TAND_5}{Me, leave? I wish. I don't know enough to leave alone and no one else wants to go, and worst of all, my father says he would have a heart attack if something happened to me! }
{123}{}{Tough situation. Can I ask you a few questions, though?}
{124}{}{Shoot, I have to go. Good luck.}
{125}{TAND_6}{Uh... I have to stand over here now. }
{126}{TAND_12}{You live here all your life and see how you like it! Anything else you want to know?}
{127}{TAND_13}{Yeah, real safe... and so boring I think my brain's going to leak out of my ear at any moment.}
{128}{}{Why don't you leave?}
{129}{}{Sorry to hear that, but I don't have much time. Can I ask you a few questions?}
{130}{TAND_14}{Finally! Someone else who sees! Of course, you've probably been everywhere, so this must be hell for you.}
{131}{}{If you're so bored, why don't you leave?}
{132}{}{Well, I'm sure you're exaggerating.}
{133}{}{It seems nice and safe here.}
{134}{TAND_15}{Junktown's to the southwest, but I don't know how far. Then there's some weird place below that called the City of Death. Oh, oh yeah there's this other place... Oh, shoot, what was that? Oh, yeah, the Hub.}
{135}{tand_15a}{There's a bunch of cities down south. But since you're such a great traveler, I'm sure you know that already.}
{136}{}{Thanks.}
{137}{TAND_16}{No problem. Anything else?}
{138}{TAND_20}{We got radscorpions! I mean, I know it's not a good thing, but no one's died from the stings. And it's the closest thing to excitement we've got here!}
{139}{TAND_21}{Nothing much, since you whomped those radscorpions. Gee, I wish I could have seen that.}
{140}{TAND_22}{Same as always. Bo-ring.}
{142}{tand_23b}{Just stuff.}
{141}{tand_23g}{The weirdest story I've heard is about the Deathclaw.}
{143}{}{Thanks.}
{144}{}{Deathclaw?}
{145}{TAND_24}{It's okay, I guess. I mean, it is home and all, but it's so boring! You know, I want to see the world.}
{146}{}{If you're so bored, why don't you leave?}
{147}{}{Well, I'm sure it's not that bad.}
{148}{}{It seems nice and safe here.}
{150}{tand_27f}{Listen... uh... but I... uh... I-I like guys, okay? Whew! Uh, excuse me, I got stuff to do.}
{149}{tand_27m}{I'm not that kind of girl, mister. Go find a brahma or something.}
{151}{TAND_28}{Well, thanks for talking. We don't get many strangers here, so it's always good to talk to new people. Well, see ya!}
{152}{}{Bye.}
{153}{TAND_29}{Uh, listen. I have to go take care of the brahmin. It was, uh, nice talking to ya. }
{154}{tand_30a}{Hello again! What can I help you with now?}
{155}{}{Can I ask you a few more questions?}
{156}{}{Nothing. Goodbye.}
{157}{TAND_35}{Uh... hey, thanks. Later.}
{158}{TAND_36}{Hi! I was afraid that you were gone and I wasn't going to get a chance to thank you for rescuing me. Aw, that was great! Action, adventure... Anyway, if there's anything that I can do for you, you just ask.}
{159}{}{How about a few more questions?}
{160}{}{How about you and I... well, you know... get together.}
{161}{}{Nope, that's it, thanks.}
{162}{}{Dungh!!}
{163}{TAND_37}{Who are you? What do you want?}
{164}{}{My name is }
{165}{}{, and your father sent me.}
{166}{}{I'm your fairy godmother. What's it look like?}
{167}{}{Duh.}
{168}{TAND_38}{Father sent you!? Are you here to get me out?}
{169}{}{Yes, so just sit tight. I'll get you out.}
{170}{}{No, he just sent me to look at you.}
{171}{TAND_39}{Well, what's your plan?}
{172}{}{Just wait for the doors to open. Then run for it!}
{173}{}{I'm going to fight the Khan leader in exchange for your freedom.}
{174}{TAND_40}{That's it? That's your plan. Ugh! All right. But hurry. I heard them talking and I didn't like their plans. }
{175}{TAND_41}{You? Fight him? You got to be kidding me! [sigh] Listen, if you come up with another plan, let me know, okay? }
{176}{TAND_42}{Oh, aren't we the sarcastic one? Are you going to get me out, or what!?}
{177}{}{Yeah. Just hold on, and when you see the door open, run for it.}
{178}{}{I'm going to fight the Khan leader in exchange for your freedom.}
{179}{TAND_43}{Oh, it's you again! Are you going to get me out?}
{180}{}{Yes, so just sit tight. I'll get you out.}
{181}{}{No, I'm just stopping by to say hi.}
{182}{}{Duh.}
{183}{tand_43a}{Hello, anybody home? Could you get me out of here? Could you GET ME OUT OF HERE?!}
{184}{tand_43b}{This is no time to talk, we have to get out of here.}
{185}{TAND_44}{Aradesh is my father. He's okay, as far as dads go.}
{186}{TAND_45}{That's me. Who else did you think it was?}
{187}{TAND_46}{Razlo's the old guy on the east side of town. He's a pretty good doctor, though, even if he is a fossil. }
{188}{TAND_47}{Seth's the captain of the guards. My father tried to set us up once, but he is not my type.}
{189}{TAND_48}{Agatha's the oldest one here. We all love her, especially her stories. Go by and see her if you want a good yarn.}
{190}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{191}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{192}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them. }
{193}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{194}{TAND_53}{Junktown's a small city to the southwest. It's supposed to have pretty good trading, but my father won't even look into it. He says we need to stay 'protected'. Yeah, right. Caged is more like it. }
{195}{TAND_54}{The Hub is supposed to be a great city to the south. I've always wanted to see it, but I've never got the chance. }
{196}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets! }
{197}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{198}{TAND_63}{Hmm... Doesn't ring a bell. }
{199}{TAND_64}{Hmm... Nope. I never heard of it. }
{200}{TAND_65}{Hey! What do you think you're doing? Put that back! }
{201}{TAND_66}{That's it! I'm going to tell my father! }
{202}{TAND_67}{What the hell do you think you're doing? Stop that! }
{203}{TAND_68}{What are you doing here? You better leave before my father wakes up.}
{204}{TAND_69}{Like I said...}
{205}{TAND_70}{Listen, I already told you... }
{206}{TAND_71}{Again? Hello? How many times have I have to tell you this? You have too much wax in your ears or something?}
{207}{TAND_72}{Oh yeah, I heard of that, but you should go talk to Agatha. She'd know more than I would.}

{208}{}{Let's get outta here.}
{300}{}{Wow! This is nothing like Shady Sands.}
{301}{}{Hey, what's that over there?}
{302}{}{I can't wait to tell people in Shady Sands about the outside world.}
{303}{}{You seen any more radscorpions?}
{304}{}{Where are we going now?}
{305}{}{When are we going to get there?}


#
# Sex msgs, by Sduibek for Fallout Fixt:
#
{350}{TAND_16a}{Yeah, whatever.}

{399}{}{[Follow her]}
{407}{}{[Continue]}
{412}{}{[She smiles and leads you to her room]}

{400}{TAND_3}{Sure, I guess. I've never been out of here, so I don't know what help I can be. So, what'cha need?}
# no {401}{TAND_29}{[Over her shoulder so that Aradesh can hear] Uh, listen. I have to go take care of the brahmin. It was, uh, nice talking to ya. [Turns back to you and motions for you to follow her...]}

{402}{TAND_28}{Well, thanks for... "talking". [she winks and smiles] We don't get many strangers here, so it's always good to "talk" to new people. Well, seeya!}
# probably not {403}{TAND_35}{Uh... hey, thanks. Later. [she looks exhausted]}

{404}{}{Something I wouldn't want to be announcing to others. Let's go somewhere private and I'll tell you...}
{405}{}{You look rather... inexperienced. I want to teach you as much as I can. We should get started, there's a lot to go over. [wink]}
{406}{}{[sigh] More than you can provide, but I'll make do.}

{410}{TAND_14}{Finally! Someone else who sees! Of course, you've probably been everywhere, so this must be hell for you. [She shrugs and leads you to her room]}

{415}{}{I'd like to have some more fun, if you've got the time.}

##############


{980}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{981}{TAND_63}{Hmm... Doesn't ring a bell. }
{982}{TAND_64}{Hmm... Nope. I never heard of it. }

{1000}{}{Aradesh|ARADESH|FATHER|DAD|LEADER}
{1001}{}{Tandi|TANDI}
{1002}{}{Seth|SETH|CAPTAIN}
{1003}{}{Raiders|RAIDERS|RAIDER|Khans|KHANS|KHAN}
{1004}{}{Well|WELL}
{1005}{}{Scorpions|SCORPIONS|Scorpion|SCORPION|rad scorpion|RAD SCORPION|Radscorpions|RADSCORPIONS|Radscorpion|RADSCORPION}
{1006}{}{Claw|CLAW|DEATHCLAW|DEATHCLAWS|CLAWS}
{1007}{}{Junktown|JUNKTOWN}
{1008}{}{Hub|HUB}
{1009}{}{City|CITY|NECROPOLIS}
{1010}{}{Razlo|RAZLO}
{1011}{}{SEX}

{1100}{TAND_44}{Aradesh is my father. He's okay, as far as dads go.}
{1101}{TAND_45}{That's me. Who else did you think it was?}
# "1102 TAND_46 Razlo's the old guy on the east side of town. He's a pretty
# good doctor, though, even if he is a fossil." Wrong number! Removed with patch 1.3 from TeamX.
{1102}{TAND_47}{Seth's the captain of the guards. My father tried to set us up once, but he is not my type.}
{1103}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1104}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{1105}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them. }
{1106}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{1107}{TAND_53}{Junktown's a small city to the southwest. It's supposed to have pretty good trading, but my father won't even look into it. He says we need to stay 'protected'. Yeah, right. Caged is more like it. }
{1108}{TAND_54}{The Hub is supposed to be a great city to the south. I've always wanted to see it, but I've never got the chance. }
{1109}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets! }
# 1110 added with patch 1.3 from TeamX.
{1110}{TAND_46}{Razlo's the old guy on the east side of town. He's a pretty good doctor, though, even if he is a fossil. }
{1111}{tand_27m}{I'm not that kind of girl, mister. Go find a brahma or something.}

