{100}{}{You see a highly advanced Brotherhood computer.}
{101}{}{You are denied access to this terminal.}
{102}{}{The lesson finishes in six hours. You feel exhausted.}
{103}{}{You've already absorbed as much as you can.}
#
{200}{}{You see a computer. There are some pieces of something on it that might be human flesh.}
#
{201}{}{You fiddle with the computer for a while, but cannot get past the security system.}
{202}{}{This computer is functioning perfectly.}
{203}{}{You find an interesting data file on a secret base to the northwest.}
#
# A number is inserted between 204 and 205
{204}{}{You earn }
{205}{}{ experience for hacking into this computer.}
