{100}{}{You see: Theresa.}
{101}{}{Hello, }
{102}{}{. How fares your journey?}
{103}{}{It's going pretty well, thanks.}
{104}{}{Not very well.}
{105}{}{Hoogh!}
{106}{}{It's good to hear that. I knew that the outside world couldn't be as bad as everyone says. I mean, our ancestors lived outside, right? But that paranoid Overseer won't let us leave.}
{107}{}{The Overseer probably has his reasons.}
{108}{}{Actually, it's pretty bad out there.}
{109}{}{You're right; the outside world isn't all that bad.}
{110}{}{The Overseer is simply trying to protect us. The outside world is dangerous to the unprepared.}
{111}{}{Oh, I'm sorry to hear that. I hope that you're able to find the chip soon.}
{112}{}{Shouldn't be a problem.}
{113}{}{With all of the hazards I've been running in to, it may take some time.}
{114}{}{Hmm. I suppose it was too much to hope that the outside world had taught you to communicate. Oh well.}
{115}{}{And I suppose he chose you to go outside because he knew that you were under his thumb! He really just doesn't want to give up his control over us.}
{116}{}{I resent that remark!}
{117}{}{Actually, I think he believes that there's no reason to risk survival outside while it's still safe in here.}
{118}{}{Hmm. From what I've read, the outside isn't really all that dangerous. But I suppose that you would know better than I, wouldn't you?}
{119}{}{I knew that the outside couldn't be too bad. That's why I've been trying to convince some people to come outside with me. I think that we have a better chance of survival out there.}
{120}{}{What are you smoking!?}
{121}{}{That's probably a good idea.}
{122}{}{I suppose. I always figured that he just had some sort of power trip. But I guess that he wouldn't be the Overseer if he wasn't really concerned about our welfare, would he? I guess we should just wait and see if you can find the chip.}
{123}{}{Don't worry, I'll take care of it.}
{124}{}{Oh, come on! Wake up! If he thinks the outside is so dangerous, then how come he sent you out there? The man just has a control complex. You're a stupid tool and you don't even know it!}
{125}{}{Honestly, if he thought that the outside was that dangerous, he'd have sent a whole team with weapons and equipment, not just you. But you're his pawn, since he doesn't want anyone to realize what they're missing.}
{126}{}{Oh, get real! Do you really think that we can live in this Vault generation after generation? Maybe you can find a new chip, but what happens when the next thing breaks down? And the next?}
{127}{}{Huh. I guess you're right.}
{128}{}{Maybe we can't stay here forever. But rushing out into the world without preparation and without the consent of the group isn't the answer.}
{129}{}{A lot of us think so. That's why we're planning to take some supplies and head out in a few days. Say, do you have any advice for us?}
{130}{}{Sorry, I haven't really found much out there.}
{131}{}{You could head to this little village called Shady Sands, a few days east. They might help.}
{132}{}{Okay. Well, thanks.}
{133}{}{Oh, just go away! We don't need the help of one of the Overseer's pawns!}
{134}{}{Welcome to our meeting! As you have been picked by the Overseer to go outside, perhaps you can give us some advice before our move to the outdoors as well.}
{135}{}{Don't drink glowing water.}
{136}{}{Yeah... don't go.}
{137}{}{I think that your plans to leave are ill-advised.}
{138}{}{Hoooot!}
{139}{}{Thank you so much. I can see you're going to be a big help. Why don't you just leave?}
{140}{}{Sorry, I'm here to hear all of this.}
{141}{}{Fine then.}
{142}{}{Really? Considering our position, our lack of water, and the original purpose of this Vault, why do you think that we should stay?}
{143}{}{It's just a bad idea, is all.}
{144}{}{The outside world is too dangerous to the unprepared. It's best to have time to make proper preparations before going. The Overseer is trying to give the Vault that needed time.}
{145}{}{Well, considering that you have some experience with the outside, perhaps you have some valuable points to make.}
{146}{}{The outside is too dangerous and hostile. You wouldn't last long.}
{147}{}{I just need a little more time to find the Water Chip.}
{148}{}{If you can't give us good reasons why we shouldn't leave, then we're not going to wait here and die of water poisoning. Please don't get in our way.}
{149}{}{Sorry, folks, I can't let you do this.}
{150}{}{Very well. It's your choice.}
{151}{}{It's only a matter of time before we run out of water here. But the Vault was never meant to keep people inside forever! We have the people and the supplies to move outside now. We have a better chance.}
{152}{}{Outside is too dangerous.}
{153}{}{The Vault was made to release its inhabitants together as a group, not as a small band that will be quickly overwhelmed.}
{154}{}{Hmm. Perhaps you're right. There are probably other survivors out there, and they could be hostile, too. I guess we will need to wait for everyone else to be ready.}
{155}{}{We're well-prepared now. We have equipment and simulator training. A few hazards outside are better than dying slowly of thirst!}
{156}{}{Sorry, I can't let you leave now.}
{157}{}{Well, good luck then.}
{158}{}{I don't like it, but I suppose we will wait until everyone is ready to leave together.}
{159}{}{It's for the best. Trust me, I know what I'm talking about.}
{160}{}{Thank you all for coming again.}
{161}{}{Our plans are moving forward still.}
{162}{}{We are gathering more converts every week.}
{163}{}{Soon, we will have access to the gear we need.}
{164}{}{The Water Chip still has not been found. We must move soon.}
{165}{}{The Overseer cannot oppose such a large group.}
{166}{}{Be patient. We will only need to wait a few more weeks.}
{167}{}{Then, we will at last be free of the Vault and the Overseer.}
{168}{}{Remember to practice your outdoor skills in the simulators!}
{169}{}{Be well, everyone.}
{170}{}{Please hurry and find the Water Chip. We cannot wait much longer.}
{171}{}{Don't worry, I will.}
{172}{}{I didn't think you would succeed, but you did a good job. Thank you for saving us all.}
{173}{}{ experience for peacefully calming the Vault's revolutionary faction.}
{174}{}{Traitor! Why did you ever come back here? Now everybody will die!}
{175}{}{We've been over this before. Leave us alone.}
#
# Fallout Fixt:
#
{176}{}{If you're interested, we hold meetings at 5:00 p.m.}
{177}{}{You earn }
{178}{}{ experience for violently disbanding the Vault's revolutionary faction.}


# Theresa's Tell-Me-Abouts

{1000}{}{Chip}
{1001}{}{Vault}
{1002}{}{War}
{1003}{}{Outside}
{1004}{}{Overseer}
{1005}{}{Water}
{1006}{}{Water Chip}


{1100}{}{Without it, we won't have drinking water. We need to end our dependency upon such equipment and become self-sufficient instead.}
{1101}{}{The Vault has been home for a long time, but it's time for us to make our way outside now.}
{1102}{}{I think that we have learned our lesson. It's time to build a new world, not worry about the old one.}
{1103}{}{Outside is where we should be! It's the great adventure, to start anew and to live by our own skills and wits!}
{1104}{}{He's lost in the past. He won't accept that it's time for us to make our own future.}
{1105}{}{Without it, we won't have drinking water. We need to end our dependency upon such equipment and become self-sufficient instead.}
{1106}{}{Without it, we won't have drinking water. We need to end our dependency upon such equipment and become self-sufficient instead.}

