{100}{}{You see a man in dusty leather armor with a trenchcoat and gas mask.}
{101}{}{You see: Tycho, the Desert Ranger.}

{102}{}{Another new face. Travelers here are a dime a dozen. But you have the look of someone different. Care to join me for a drink?}
	{103}{}{Sorry, I'm rather pressed for time.}
	{104}{}{Sure.}
	{105}{}{Duh-wah?}

{106}{}{Delightful. I hope you don't mind your drink well-watered - they treat beer here like it's a potted plant.}
	{107}{}{So, what's your story?}
	{108}{}{Yeah, a drink of water. Never mind.}

{109}{}{I could ask the same of you. In the interest of amity, I suppose I'll tell first. I'm called Tycho. Came from out east, what used to be called Nevada.}
	{110}{}{That's a pretty long trip.}
	{111}{}{How did you survive all the dangers?}

{112}{}{Yeah, it was. Decided to take it easy for a while. This place shows some promise, just as soon as someone cleans up some of the scum.}
	{113}{}{Why don't you?}
	{114}{}{Yeah, I noticed. What do you know about those jerks?}

{115}{}{Had some pretty good training, and some good weapons, too. My grandfather was a Ranger way back when, and he taught my father everything he knew. Dad passed it on to me. So I know enough not to drink glowing water, so to speak.}
	{116}{}{Interesting. Thanks for the drink.}
	{117}{}{Really? Survival's tough these days. You must be pretty knowledgeable.}

{118}{}{Not my place. I'd rather not cross Killian, after all. He'll clean up this town when he gets around to it. A good man, mark my words. But watch out for that fellow Gizmo. Reminds me of another fat freak my father told me about back in Las Vegas.}
	{119}{}{Thanks for the tip, and the drink.}

{120}{}{There's two grades of scum here. One of 'em's the Skulz, a gang that hangs out in back of Marcelles' crash house. They're just grade-B twerps. But the other ones answer to a fat freak whose name you can probably guess. Runs the casino. Those guys are organized and dangerous.}
	{121}{}{I see. Thanks for the info.}

{122}{}{Yeah, well, my family taught me everything there is to know about survival. Don't drink water that's totally clear and free of insects and moss, for instance. Only poisonous or radioactive water would be that clean in the wilderness. Lots of other little things to look out for, too.}
	{123}{}{Like what?}

{124}{}{Well, if you've got some time, I could go over some pointers.}
	{125}{}{Sure, that would be great.}
	{126}{}{Sorry, I'm kind of pressed for time.}

{127}{}{Whoa, not so fast. We never finished introductions, remember? What's your name, stranger?}
	{128}{}{I'm }
	{129}{}{.}
	{130}{}{None of your business, you nut.}

{131}{}{Good to meet you. Step carefully, friend.}
{132}{}{Now, now, no need to get impolite. But with that attitude you'd best be on your way.}
	{133}{}{Bite me.}
	{134}{}{Whatever. See ya.}

{135}{}{What do you want?}
	{136}{}{Sorry to disturb your private time. Go wank somewhere else.}
	{137}{}{I need information about the gangers here.}
	{138}{}{I need information about the town.}

{139}{}{Hello again. How can I help you?}
	{140}{}{Killian's asked me to clean up this town, and I'd like your help.}

{141}{}{Well, this is the Skum Pitt, a wretched hive of villainy and all that. Just west of here is Gizmo's, a big casino. Word is the games are rigged. A little south of here is the Crash House, run by Marcelles, where you can get a night's sleep for way too many caps. Past that is Killian's. Killian runs a general store, and he also enforces the law in this town - a good man. Then south of there you have Doc Morbid, whose operation is a little funny, if you take my meaning.}
{142}{}{I hope that my little instruction course helped a bit.}
{143}{}{}

{144}{}{Word is out that you've been having some contact with Gizmo. I'd step carefully around that barrel of lard if I were you.}
	{145}{}{My business is none of yours.}
	{146}{}{Yeah, I work for Gizmo now. What's it to you?}

{147}{}{Fair enough. But watch your back. Gizmo isn't known for his consideration for his employees.}
{148}{}{Suffice to say that your employer has caused more than enough misery and strife in this town. Don't expect much help from anyone, least of all Gizmo. Too bad. You might've been able to change this town for the better.}

{149}{}{What can I do for you?}
	{150}{}{Any recommendations?}
	{151}{}{Thanks for your help. I think it's time to part ways.}
{152}{}{Yeah, I'd stay the hell away from whatever made that. Seriously, I've never seen anything like that. I think our best option is to move on, fast.}
{153}{}{Very well. I must say that it has been an honor and a pleasure.}
{154}{}{Watch out for radioactive hot spots. This place obviously sustained a direct nuclear strike, and secondary cascade radiation may be bad. I'd recommend avoiding this place completely if we can.}
{155}{}{Note the lack of any animal life for quite a distance. And the piles of bones. Whatever lives here is a real beast. Keep your weapon handy.}
{156}{}{A military place like this must have a central command room somewhere.}
{157}{}{I bet we could get through those force field generators with a little hot-wiring, or if we could find the force field control computer.}
{158}{}{There are many strange tales about Necropolis, the city of the dead. Stay alert, because it could get dangerous really fast.}
	{159}{}{I need to change formation.}
{160}{}{What distance do you want me at?}
	{161}{}{Stay close.}
	{162}{}{Keep a moderate distance.}
	{163}{}{Move out to longer range.}
	{164}{}{What sorts of weapon skills have you learned?}
{165}{}{Pretty good Ranger training. I'm skilled with small pistols and rifles. I can also use a spear, of course, in a pinch.}
	{166}{}{Uh, never mind.}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

{167}{}{Yeah, if you like your lizard well-done.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{Well it's about time. Lead on, sir, and let's do some street sweeping. I'd recommend knocking over Gizmo, if I may.}
{169}{}{Well it's about time. Lead on, maam, and let's do some street sweeping. I'd recommend knocking over Gizmo, if I may.}
{170}{}{Yes?}
	{171}{}{I think maybe we should stick together, after all.}
	{172}{}{Nothing. Never mind.}
{173}{}{ experience for recruiting Tycho, the Desert Ranger.}

# for Fallout Fixt:
	{174}{}{we be frend?}

{175}{}{You're going down}
{176}{}{Time for payback.}
{177}{}{Junktown's citizens will be avenged!}
{178}{}{Do you think you're above the law?}
{179}{}{I don't approve of scum like you}
{180}{}{All actions have consequences.}

{181}{}{You see: Tycho.}

# Healing
{300}{}{I'm all set.}
{301}{}{Got nothing that'll slow us down.}
{302}{}{You got anything to help?}
{303}{}{Maybe you should have a look at this.}

# Pushing
{310}{}{I'm moving.}
{311}{}{If you say so.}
{312}{}{That's better?}
{313}{}{Relax, be happy.}

#
# Tycho Tell-Me-Abouts
#

{1000}{}{Junktown}
{1001}{}{Rangers}
{1002}{}{Chip}
{1003}{}{War}
{1004}{}{Wastes}
{1005}{}{Followers}
{1006}{}{Cathedral}
{1007}{}{Garl}
{1008}{}{Master}
{1009}{}{Unity}
{1010}{}{Set}
{1011}{}{Watershed}
{1012}{}{Necropolis}
{1013}{}{Hall}
{1014}{}{Library}
{1015}{}{Overseer}
{1016}{}{Medic}
{1017}{}{Healing}
{1018}{}{Vault}
{1019}{}{Vault 13}
{1020}{}{Vault13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Boneyard}
{1024}{}{Shady}
{1025}{}{Sands}
{1026}{}{Hub}
{1027}{}{Casino}
{1028}{}{Store}
{1029}{}{Deathclaw}
{1030}{}{Exodus}
{1031}{}{Initiates}
{1032}{}{Paladins}
{1033}{}{Scribes}
{1034}{}{Children}
{1036}{}{Brotherhood}
{1037}{}{Vats}
{1038}{}{Military}
{1039}{}{Base}
{1041}{}{Apocalypse}
{1042}{}{Mutants}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Booze}
{1052}{}{Drugs}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulators}
{1058}{}{Scavs}
{1059}{}{Blades}
{1060}{}{Nicole}
{1061}{}{Lieutenant}
{1062}{}{Psychics}
{1063}{}{Experiments}
{1064}{}{Police}
{1065}{}{Merchants}

{1100}{}{Well, Junktown's not really home, but it's an interesting city. It has potential, although I don't know that building out of the refuse of the past is the best way to construct the future.}
{1101}{}{We Rangers hail from back east, what used to be called Nevada. Our heritage stretches back to the days of the Texas Rangers. We learn survival and combat skills in order to go out into the world and have a chance of surviving and making things better.}
{1102}{}{I haven't seen a relic of old technology like a Water Chip for a long time. Personally, you're better off depending on yourself, not on some piece of tech that you can't fix.}
{1103}{}{The War was a testament to human greed and insanity. Let's hope that we have learned enough to never repeat such folly.}
{1104}{}{The wastes are hostile and dangerous, even to the wary traveler. Radiation and strange creatures will take their toll. Tread with caution, and remember that everything you see and hear is a clue.}
{1105}{}{I'm sorry, I can't help you there.}
{1106}{}{I'm sorry, I can't help you there.}
{1107}{}{I'm sorry, I can't help you there.}
{1108}{}{I'm sorry, I can't help you there.}
{1109}{}{I'm sorry, I can't help you there.}
{1110}{}{I'm sorry, I can't help you there.}
{1111}{}{I'm sorry, I can't help you there.}
{1112}{}{The City of Death is well named. It lies in what used to be the little town of Bakersfield. Now, though, it's home to ghouls and worse.}
{1113}{}{I'm sorry, I can't help you there.}
{1114}{}{I'm sorry, I can't help you there.}
{1115}{}{I'm sorry, I can't help you there.}
{1116}{}{I'm sorry, I can't help you there.}
{1117}{}{I'm sorry, I can't help you there.}
{1118}{}{I've heard of the great underground Vaults. I don't know much about them, though.}
{1119}{}{I've heard of the great underground Vaults. I don't know much about them, though.}
{1120}{}{I've heard of the great underground Vaults. I don't know much about them, though.}
{1121}{}{Killian's a good man doing a difficult job.}
{1122}{}{Gizmo is... well, he strikes me as a crook. He'll get his in the end.}
{1123}{}{L.A. Boneyard? I'm told it's a place of gangs and hard life, near the coast.}
{1124}{}{I'm sorry, I can't help you there.}
{1125}{}{I'm sorry, I can't help you there.}
{1126}{}{The Hub's a giant mercantile community, just a short ways south of Junktown.}
{1127}{}{Gizmo's casino is probably one of the last places I'd want to go, unless I were going to step on Gizmo's neck. Not that I could get a foot past all the blubber.}
{1128}{}{Killian has a decent general store in Junktown.}
{1129}{}{Heard some tales about something faster, bigger, and meaner than any living creature has a right to be. Not too many, though, which means that it doesn't leave many survivors. Big claws, ferocious disposition.}
{1130}{}{I'm sorry, I can't help you there.}
{1131}{}{I'm sorry, I can't help you there.}
{1132}{}{I'm sorry, I can't help you there.}
{1133}{}{I'm sorry, I can't help you there.}
{1134}{}{I'm sorry, I can't help you there.}
{1136}{}{I'm sorry, I can't help you there.}
{1137}{}{I'm sorry, I can't help you there.}
{1138}{}{The military had several secret bases scattered about, I know. I just don't know where.}
{1139}{}{The military had several secret bases scattered about, I know. I just don't know where.}
{1141}{}{Nuclear armageddon was the result of pride and foolishness. Now, we're paying the price.}
{1142}{}{Certainly there are some strange things out there. I've seen mutated scorpions and 2-headed cows, and I've heard that Necropolis is home to ghouls, who seem human but are far different.}
{1143}{}{I'm sorry, I can't help you there.}
{1144}{}{I'm sorry, I can't help you there.}
{1145}{}{I'm sorry, I can't help you there.}
{1146}{}{I'm sorry, I can't help you there.}
{1147}{}{I'm sorry, I can't help you there.}
{1148}{}{I'm sorry, I can't help you there.}
{1149}{}{I'm sorry, I can't help you there.}
{1150}{}{I'm sorry, I can't help you there.}
{1151}{}{I prefer a good strong stout, or perhaps a Nuka-Cola.}
{1152}{}{I'd stay away from drugs if I were you. Sure, they can give you a boost, but you always wind up paying for it in the end.}
{1153}{}{I'm sorry, I can't help you there.}
{1154}{}{I'm sorry, I can't help you there.}
{1155}{}{I'm sorry, I can't help you there.}
{1156}{}{I'm sorry, I can't help you there.}
{1157}{}{I'm sorry, I can't help you there.}
{1158}{}{I'm sorry, I can't help you there.}
{1159}{}{I'm sorry, I can't help you there.}
{1160}{}{I'm sorry, I can't help you there.}
{1161}{}{I'm sorry, I can't help you there.}
{1162}{}{You mean telepathetics? Heh... seriously, I don't buy it.}
{1163}{}{I'm sorry, I can't help you there.}
{1164}{}{I'm sorry, I can't help you there.}
{1165}{}{Some merchants from the Hub visit Junktown and other cities on a regular basis.}

{1999}{}{I feel more powerful now!}
	{2000}{}{Let's discuss our combat tactics.}
{2001}{}{Yes?}
	{2010}{}{Draw your best weapon.}
	{2011}{}{Change your armor.}
	{2012}{}{Prefer ranged combat against close.}
	{2013}{}{Prefer close combat against ranged.}
	{2014}{}{Choose distance on your own.}
	{2015}{}{That's all for now.}
{2100}{}{All right.}
{2101}{}{Sure thing.}
{2102}{}{Well it's about time.}

# Any recommendations? NEW
{2200}{}{I'd recommend knocking over Gizmo, if I may.}

# Too many party members
{2500}{}{Thinking about it, you know what? I don't like the idea of travelling in a big squad like that. A smaller team and I'm with you.}
{2510}{}{Alright.}
{2511}{}{[Done]}

{3500}{}{I'm about due for some crutches and a wheelchair over here.}
{3501}{}{I'm glowing like a neon sign over here. Got any anti-radiation drugs?}
{3502}{}{I got some poison runnin' through my system. Got any antidote?}

# Mariposa prisoner
{3503}{}{Finally a friendly face. Lead the way!}
