{100}{}{You see a citizen of Vault 13.}
{101}{}{We didn't think that you were coming back. You have such a nice room, and we were a little crowded with her parents. I hope you don't mind.}
{102}{}{Yes, I do mind. Get out of my room!}
{103}{}{Nah, I don't care. Enjoy the room.}
{104}{}{It would be reassuring to have my own quarters back. Please find somewhere else to live.}
{105}{}{Hng.}
{106}{}{Look, I don't want to argue with you, but you obviously don't deserve this room anymore. Please leave.}
{107}{}{Look, we could really use the space. I hope you will reconsider.}
{108}{}{Well, let me think about it for a moment. Hmmm. No. Get out!}
{109}{}{Well, okay. You need it more than I do.}
{110}{}{Thanks! We really appreciate it. We put your stuff in the trunk.}
{111}{}{Well, I don't know. You don't seem to be using it very often, and we sure could use the space.}
{112}{}{Fine. Take it.}
{113}{}{I need this place to remember my roots. And besides, it's a good place to rest.}
{114}{}{Gee, I didn't think you would still care about this place from what I've heard. You have a good day. We'll go back to her mothers' place.}
{115}{}{We really like it here.}
{116}{}{You should leave. This isn't your place here anymore.}
