{100}{}{You see a woman.}
{101}{}{I do not wish to die, sir. I am not a soldier.}
{102}{}{I do not wish to die, ma'am. I am not a soldier.}
{103}{}{Start talking, and I'll let you live.}
{104}{}{Neither am I. I only kill when I have to.}
{105}{}{Aren't you going to praise the Master or something!}
{106}{}{I'll trade your life for a good stiff drink. Where do they keep the booze?}
{107}{}{Good night bitch!}
{108}{}{Me Big Soldier! Hah! Hah! Hah!}
{109}{}{I'm glad you came to talk to me. I heard what you said to Laura. You mustn't do this.}
{110}{}{What do you think I'm going to do?}
{111}{}{Laura? Who's Laura?}
{112}{}{Oh, oh.}
{113}{}{Oh, that was a big mistake! And it's gonna cost you.}
{114}{}{Wha tak? Raar!}
{115}{}{I think we've said all that needs to be said. Goodbye.}
{116}{}{I do not speak to people at the point of a weapon. Lower it, and we may talk.}
{117}{}{Hello again. I hope you've found this place interesting.}
{118}{}{I've seen higher forms of entertainment.}
{119}{}{Of course, sister. Praise the Master! Praise the Holy Flame!}
{120}{}{You know, every time I talk to someone, people keep repeating everything they say over and over again.}
{121}{}{Entertainment? Where's the booze!}
{122}{}{This place is boring! Where's the blood? Where's the death?}
{123}{}{Greetings Initiate. How may I be of service to you?}
{124}{}{I was a little nervous about our long range plans.}
{125}{}{What's going on around here?}
{126}{}{Where's the Master?}
{127}{}{Who's in charge here?}
{128}{}{Gimme a break sister. Nobody serves another person unless a gun's against their head!}
{129}{}{Hello, sir. Your reputation precedes you! Is there anything I can help you with?}
{130}{}{Hello, miss. Your reputation precedes you! Is there anything I can help you with?}
{131}{}{I was wondering what the Cathedral is all about.}
{132}{}{How does one become an Initiate?}
{133}{}{Where's the Master?}
{134}{}{Who's in charge here?}
{135}{}{Gimme a break sister. Nobody serves another person unless a gun's against their head!}
{136}{}{Hello, sir. Your reputation precedes you! Is there anything I can help you with?}
{137}{}{Hello, miss. Your reputation precedes you! Is there anything I can help you with?}
{138}{}{I was wondering what the Cathedral is all about.}
{139}{}{How does one become an Initiate?}
{140}{}{Where's the Master?}
{141}{}{Who's in charge here?}
{142}{}{Gimme a break sister. Nobody serves another person unless a gun's against their head!}
{143}{}{I know who you are. And you will forgive my rudeness, but I don't speak to psychotic killers. Goodbye.}
{144}{}{My reputation has been greatly exaggerated. Does the Cathedral judge people on rumor and innuendo?}
{145}{}{Psychotic killer? Who, me!}
{146}{}{Baby, I'm no psycho, I'm just plain nuts, and if you don't answer my questions I'll prove it!}
{147}{}{I do not form bonds of loyalty easily. And I do not break them easily either. I will tell you nothing.}
{148}{}{Good. Then we can leave each other alone and call it even.}
{149}{}{Praising the Master will not save my life. Go ahead, and do it. I can do nothing to stop you.}
{150}{}{There's a still somewhere away from the Cathedral. They don't permit drugs or alcohol around here.}
{151}{}{Attempt to take the key to the secret entrance from Morpheus and kill the Master.}
{152}{}{Why wouldn't I want to do that?}
{153}{}{I don't know what you're talking about.}
{154}{}{Why would I want to do that?}
{155}{}{Have you ever heard about knowing too much?}
{156}{}{The spy for the Followers of the Apocalypse who's currently in one of the meditation rooms.}
{157}{}{There's a spy here? We must inform the High Priests at once!}
{158}{}{I don't know what you're talking about.}
{159}{}{Why would I be spying on you?}
{160}{}{Have you ever heard about knowing too much?}
{161}{}{This place isn't about entertainment, it's about enlightenment. More importantly, it's about making the right choices about the destiny of the world. See you around.}
{162}{}{Riight. Sure. Of course. See you later.}
{163}{}{I know. I have a tendency to do that too, when I have nothing original to say. See you later.}
{164}{}{People who have the spirit of the Holy Flame need no other spirits. Or so they say. You know how that goes_}
{165}{}{Upstairs. Ask the Nightkin to shed your blood, they'll be more than happy to oblige.}
{166}{}{Because the Master is a necessary evil. Because somebody has to unite the world, and he's the only one in the area who has a chance to unify it.}
{167}{}{Anyone ever tell you that Unity is overrated?}
{168}{}{Why?}
{169}{}{I don't believe in necessary evils.}
{170}{}{I like this world just fine.}
{171}{}{I don't think I like this conversation.}
{172}{}{Very well, if you won't acknowledge what you said, I won't help you. Goodbye.}
{173}{}{Because you think that it's wrong for the Children to invade our neighbors. Because you think that killing the Master will stop it.}
{174}{}{And if I believed that, why would I be wrong?}
{175}{}{That's blasphemy!}
{176}{}{If you think that I believe it, why haven't you turned me over?}
{177}{}{Do I look like the sort of person who minds a good killing?}
{178}{}{Have you ever heard of being in over your head? No one, however well-armed or trained, can defeat a half dozen Nightkin. I'm a woman of peace. I'm trying to save you.}
{179}{}{Look at the people who caused the Apocalypse! They didn't believe in peace and unity, and look what they did to us! Unity is the only way to prevent this from happening again, and Unity must happen NOW, before the other Vaults around the world have a chance to muster their forces.}
{180}{}{You seem a little too intelligent for this pack of zombies.}
{181}{}{You want everyone to act like the people in this room? That's worse than being dead!}
{182}{}{You're crazy! That'll just lead to another Apocalypse.}
{183}{}{And why is the Master the best one to lead us?}
{184}{}{You've never taken a life? You aren't packing enough firepower to give the Brotherhood of Steel gun envy? Stop being such a hypocrite! You feel it's justified to defend yourself. The Master's defending humanity from another attack of self-destruction. It's all the same!}
{185}{}{How do you know there isn't someone better out there?}
{186}{}{Maybe I should consider this.}
{187}{}{So mass slaughter is all right if you intend to save the world?}
{188}{}{That's bullshit, Lady!}
{189}{}{What the hell kind of world do you think this is? It's a nightmare out there!}
{190}{}{How do you know there isn't something better out there?}
{191}{}{Maybe I should consider this.}
{192}{}{A world where I can be free to live my own life as I choose.}
{193}{}{Life ain't pretty, sister. Never has been, never will be.}
{194}{}{Tough. I don't like radiation and the Forced Evolutionary Virus, but I didn't have a choice about it. You can't always get what you want in this world. Sometimes you have to make compromises. And sometimes you have to open your mind to unpleasant ideas.}
{195}{}{Funny. I don't see the Master allowing his flock to do that.}
{196}{}{There's compromises, and there's genocide.}
{197}{}{Get out of my face!}
{198}{}{The only choice that concerns me right now is how long you're going to live.}
{199}{}{Maybe I'll be so intelligent that when the Master takes power, I'll be able to do something to help. Maybe you will too! Join us! Join us and change the world! Just think about it, that's all I ask!}
{200}{}{There have always been drones in any society. Forget them! We need drones, but we also need soldiers and queens. And you look like a good soldier at least. Consider what you could do, you could be very useful to our cause. Help us. Think about what I've said, that's all I ask!}
{201}{}{Or maybe we can overwhelm their defenses before they have time to build up again. Maybe we can unite the other Vaults and cities with one swift, clean stroke. A united world won't be perfect, but it will have a better chance of holding itself together. Think about it!}
{202}{}{I've looked at the locals. The Brotherhood of Steel and the Children of the Apocalypse just want to be left alone. The Hub thinks they can buy the world - what a pack of fools! Only the Master has the strength to do what must be done. Think about it!}
{203}{}{I'm glad to hear that. I hope you come to the right decision.}
{204}{}{No. It isn't all right. But it's the only option that has a chance of saving us over the long term, which is why I'm with these people. There's no better way! Think about it!}
{205}{}{Is it? Think about it. Think real hard. If you continue to oppose us, you'll die. You've seen our forces, you know there's more where that came from. A lot more! You can't stop us! But If you join us, you could save lives. Just think about it!}
{206}{}{I don't. But if I see someone else I like, I'll be in position to help them. None of the locals have a chance. They're all dead, or converted if they're fortunate. You can be one of the fortunate ones. Join us. Just think about it!}
{207}{}{The world won't stay like that. It never does. And if all we do is build packs of powerful enclaves, eventually one of them will get powerful enough to start the Apocalypse over again. Join us and unite the world before this happens! Think about it!}
{208}{}{And that's just a cowardly excuse that solves nothing. If life is shitty, we should try to change it. We owe it to ourselves and to our children. Do you think the world will stay the same when we divide ourselves into warring pieces? Think about it!}
{209}{}{Or maybe there's salvation disguised as genocide. Maybe the world won't be such a bad place if people work for the Master's vision. Perhaps we can even find ways to do it with less bloodshed. Think about it!}
{210}{}{Fine. But if you continue on your current path, you will die. I thought I should warn you.}
{211}{}{You can kill me. You'll prove my point, of course, but I'll still die. Your choice.}
{212}{}{Because of the Apocalypse! Look what it did to us! Unity is the only way to prevent this from happening again, and Unity must happen NOW, before the other Vaults around the world have a chance to muster their forces.}
{213}{}{You seem a little too intelligent for this pack of zombies.}
{214}{}{You want everyone to act like the people in this room? That's worse than being dead!}
{215}{}{I'll consider it.}
{216}{}{You're crazy! That'll just lead to another Apocalypse.}
{217}{}{And why is the Master the best one to lead us?}
{218}{}{I ain't a philosopher lady. I'm just someone who's good at killing.}
{219}{}{Because you're an intelligent and brave person who could be of great help to us. Yes, some of things we do are horrible. But our overall goal is not only good, it's necessary to the survival of the human race. Don't be so hasty to help the Followers. They don't have all the answers!}
{220}{}{You seem a little too intelligent for this pack of zombies.}
{221}{}{You want everyone to act like the people in this room? That's worse than being dead!}
{222}{}{I'll consider it.}
{223}{}{You're crazy! That'll just lead to another Apocalypse.}
{224}{}{And why is the Master the best one to lead us?}
{225}{}{I ain't a philosopher lady. I'm just someone who's good at killing.}
{226}{}{We all have a part to play. Some of us are mindless drones who do the work meant for stupid people. Some of us are thinkers. Some of us are killers. There's a place for you here if you want it. Please think about it!}
{227}{}{We have many things planned. The Holy Flame came first, which purged the world of evil. Then came the Master. Now we are at the time of Unity, when we struggle to conquer the divisions of the world. After Unity shall come Peace. The Age of Peace is the reason for all our struggles.}
{228}{}{Why must so many people die to attain peace?}
{229}{}{That sounds wonderful. Praise the Master!}
{230}{}{But wasn't the fire of the Apocalypse evil?}
{231}{}{This all sounds like bullshit to me.}
{232}{}{I'm sure you are. Nervousness is a wise emotion, it keeps us from prying into unpleasant corners, and prevents us from doing stupid things. Goodbye.}
{233}{}{Initiates seek the answers to questions. Which is what you should be doing. Goodbye.}
{234}{}{I don't know. People believe his spirit is within these walls. It certainly sounds like that to me.}
{235}{}{What do people say about his physical form?}
{236}{}{Did I hear a bit of skepticism?}
{237}{}{Is there even a Master, or is this a scam?}
{238}{}{That's an annoyingly vague answer.}
{239}{}{Thank you, sister.}
{240}{}{The High Priest of the Cathedral is Morpheus. He can be found in the Upper Sanctuary, but does not give personal audiences. You might persuade Father Lasher to vouch for you, he can be found down here, in the Rectory.}
{241}{}{Morpheus? Is he a good man?}
{242}{}{Why do they call him Lasher?}
{243}{}{And what about the Master?}
{244}{}{Is there anything else I should know?}
{245}{}{Thank you, sister.}
{246}{}{You may change your mind. Or you may lose your life. This all depends on your actions and your point of view. Goodbye.}
{247}{}{We have very similar interests. You have slain monsters and brigands and made the world a safer place. We plan to do the same, on a larger scale.}
{248}{}{What sort of scale?}
{249}{}{Who are the monsters and brigands that you're planning to slay?}
{250}{}{Does this have anything to do with the Holy Flame I keep hearing about?}
{251}{}{Sorry lady, but I don't believe a word of what you're saying.}
{252}{}{How wonderful. Praise the Master! Praise the Holy Flame!}
{253}{}{Peace, love, and Unity, of course. What else could we be about? But you can discover these things for yourself. Goodbye.}
{254}{}{You should spend several weeks of meditation and fasting here, and then approach one of the elders. Or you could volunteer for service work.}
{255}{}{I've noticed some of your people in other towns...}
{256}{}{Who do I approach about volunteering?}
{257}{}{Weeks! That's a long wait.}
{258}{}{What elder is the best to approach?}
{259}{}{Service work? Like killing your enemies?}
{260}{}{My apologies. At the very least, you might be honestly seeking redemption for your crimes. How may I help you.}
{261}{}{I was wondering what the Cathedral is all about.}
{262}{}{How does one become an Initiate?}
{263}{}{Where's the Master?}
{264}{}{Who's in charge here?}
{265}{}{Gimme a break sister! Nobody serves another person unless a gun's against their head!}
{266}{}{It is dangerous to allow a mad dog into one's house, just because you can't see its saliva. Goodbye.}
{267}{}{Then you have been maligned, because the entire Boneyard tells horror stories about you. And I have no desire to find out if they're true. Goodbye.}
{268}{}{No struggle comes without a price, and the greatest struggle inevitably enacts the greatest cost. That is the paradox of peace, I fear. Words to think about, at any rate. Goodbye.}
{269}{}{That is a paradox. Of course it was, but the greatest evils can lead to the greatest good. All it requires is intelligence and courage on the part of those who survive. Words to think about, at any rate. Goodbye.}
{270}{}{We shouldn't judge people by physical appearance. The Master's goal is noble, and that's all I need to know. As for what other people say, ask them.}
{271}{}{Perhaps a bit. The Master's vision is so ambitious and brilliant that I suppose I can be forgiven a few doubts. If I discouraged you, I apologize. I would suggest you seek hardier souls than mine for instruction. Goodbye.}
{272}{}{Of course there's a Master! Why wouldn't there be? We do many things, even some things I'm not entirely proud of, but deceit isn't one of them. The Master's vision of Peace and Unity is a true one. Goodbye.}
{273}{}{There's nothing vague about 'I don't know'. Goodbye sir.}
{274}{}{There's nothing vague about 'I don't know'. Goodbye miss].}
{275}{}{You're welcome sir. May the Master bless you with wisdom.}
{276}{}{You're welcome miss. May the Master bless you with wisdom.}
{277}{}{He's an intelligent man, and is trusted by the Master. That should be enough. May the Master bless you with wisdom. Goodbye.}
{278}{}{He educates the children, and does so harshly. Is there anything else?}
{279}{}{Morpheus? Is he a good man?}
{280}{}{Why should Lasher be allowed to hurt children?}
{281}{}{And what about the Master?}
{282}{}{Is there anything else I should know?}
{283}{}{Thank you, sister.}
{284}{}{I can tell you nothing that you don't already know. My apologies.}
{285}{}{Many things I'm sure. But these answers are best discovered on our own, not through rumor and innuendo. Goodbye.}
{286}{}{You are welcome, sir.}
{287}{}{You are welcome, miss.}
{288}{}{As large as possible. The world is in chaos. It needs order, or it will not survive. We will bring order, and prevent the monsters from hurting it again, as they did in the Apocalypse. Words to think about, at any rate. Goodbye.}
{289}{}{Those who would let their selfish desires oppose the better good of humanity. The Apocalypse was caused by human selfishness. If the world is to survive, this madness must be purged from the human heart. Words to think about, at any rate. Goodbye.}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{There was Deacon Olivier; no, she's gone now, and Father Pinochet, no, he's no longer available. I hesitate to mention Lasher, but he's the only one left now. Well, I'm sure you'll find a way. Good luck.}
{295}{}{Death is never a service, even when it's a necessity. Goodbye sir.}
{296}{}{Death is never a service, even when it's a necessity. Goodbye miss.}
{297}{}{That is something I've wondered myself. But such criticism is not warranted, I'm certain. Perhaps you should speak to the children.}
{298}{}{[Done]}
{299}{}{Me go.}
{300}{}{We have taken initiates in sooner, but the Church is performing some major Crusades, and I think we're being more selective than usual about recruits. But faith will persevere, and patience is a virtue. Good luck, my friend.}
{301}{}{We have taken initiates in sooner, but the Church is performing some major Crusades, and I think we're being more selective than usual about recruits. But faith will persevere, and patience is a virtue. Good luck, my friend.}
{302}{}{I know of no plans to invoke the Holy Flame again. The Sacred Fire was sacred only because it gives us a chance to purge the world of imperfection. It is our actions that will make the flame Holy. We must take the evils of the world and make them tools for Good. Just as your weapons defend your life, our actions defend the world. Farewell, friend.}
{303}{}{I know of no plans to invoke the Holy Flame again. The Sacred Fire was sacred only because it gives us a chance to purge the world of imperfection. It is our actions that will make the flame Holy. We must take the evils of the world and make them tools for Good. Just as your weapons defend your life, our actions defend the world. Farewell, friend.}
{304}{}{We perform many services for people. Healing the sick, feeding the hungry, teaching the young. I am quite proud of them. If you corner Father Morpheus, he may be able to tell you how to get involved with our hospices. Farewell, friend.}
{305}{}{We perform many services for people. Healing the sick, feeding the hungry, teaching the young. I am quite proud of them. If you corner Father Morpheus, he may be able to tell you how to get involved with our hospices. Farewell, friend.}
{306}{}{If you corner Father Morpheus, he may be able to tell you how to get involved with our hospices. Farewell, friend.}
{307}{}{If you corner Father Morpheus, he may be able to tell you how to get involved with our hospices. Farewell, friend.}

