{100}{}{You see a sleepy vault-dweller.}
{101}{}{You see a vault-dweller acting suspiciously.}
{102}{}{He seems to be avoiding your gaze.}
{103}{}{You spot the water thief!}
{104}{}{ experience for ending the threat to the Vault's water rations by killing the thief.}
{105}{}{Thanks for solving that case. This will help morale quite a bit.}
{106}{}{ experience for successfully capturing the water thief.}
{107}{}{Hello, }
{108}{}{.}
{109}{}{Hello. What are you doing here at this time?}
{110}{}{Eaah!}
{111}{}{I was worried about the Vault and had a nightmare. I couldn't get back to sleep so I thought I'd take a walk to relax.}
{112}{}{Okay.}
{113}{}{Have you seen anyone else around here?}
{114}{}{I'm sorry, but I'm looking for the water thief and I need to see what you're carrying.}
{115}{}{Yeah, some guy was acting suspicious back near the water ration room. He scared me. I hope he didn't see me.}
{116}{}{What did he look like?}
{117}{}{I'm sorry, but I still need to see what you're carrying.}
{118}{}{I didn't get a good look at him because I ran.}
{119}{}{Okay. Thanks anyway.}
{120}{}{Sure. I've got nothing to hide.}
{121}{}{[Search him]}
{122}{}{Don't touch me! I don't have anything. Now leave me alone!}
{123}{}{Okay. Sorry.}
{124}{}{Would you rather have a bullet in your head?}
{125}{}{I stole the water. I'm sorry. Please don't hurt me!}
{126}{}{I'm taking you to the officer.}
{127}{}{Okay, okay. I've got nothing to hide. Look for yourself.}
{128}{}{Well, good night.}
{129}{}{Good night.}
{130}{}{You find nothing.}
