/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

#include "..\headers\define.h"
//#include "..\headers\sfall\main.h"

#define NAME                    SCRIPT_ECGECKO

#include "..\headers\command.h"

procedure start;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure map_enter_p_proc;

variable starttile := 0;
/*
#define SetSelfFlag(x) 		set_flags(self_obj, x)
#define GetSelfFlag 			get_flags(self_obj)

#define set_ghost 			SetSelfFlag(GetSelfFlag bwor CFLG_NOSTEAL)
#define rem_ghost 			SetSelfFlag(GetSelfFlag bwand bwnot(CFLG_NOSTEAL))
*/
procedure map_enter_p_proc begin
   starttile := self_tile;
   set_self_team( TEAM_RND_GECKO );
   reg_anim_clear(self_obj);
   reg_anim_begin();
   self_rotate(Random(0, 5));
   reg_anim_end();
end

procedure start begin
   //SetSelfFlag(GetSelfFlag bwor CFLG_NOSTEAL);
   //SetSelfFlag(GetSelfFlag bwor CFLG_NODROP);

   //debug("GetSelfFlag: " + GetSelfFlag);
end

procedure critter_p_proc begin
   if (self_can_see_dude) then begin
      attack(dude_obj);
   end

   if (not anim_busy(self_obj)) then begin
      reg_anim_clear(self_obj);
      reg_anim_begin();
      self_walk_to_tile(tile_num_in_direction(starttile, Random(0, 5), Random(3, 10)));
      reg_anim_end();
   end
end

procedure destroy_p_proc begin
   variable tail:=0;

   if (dude_perk( PERK_gecko_skinning_perk )) then begin
       if ((self_pid == PID_GECKO) /*or (self_pid == PID_TOUGH_GECKO_SMALL)*/) then
            tail := create_object(PID_GECKO_PELT,0,0);
       // Begin Seraph's Code
       //else if ((obj_pid(self_obj) == PID_FIRE_GECKO) /*or (obj_pid(self_obj) == PID_TOUGH_FIRE_GECKO)*/) then
       //     tail := create_object(PID_FIRE_GECKO_PELT,0,0);
       // End Seraph's Code
       else if ((self_pid == PID_GOLDEN_GECKO) /*or (self_pid == PID_TOUGH_GOLDEN_GECKO)*/) then
            tail := create_object(PID_GOLDEN_GECKO_PELT,0,0);

      add_obj_to_inven(self_obj,tail);
   end
   else begin
      //set_proto_data(obj_pid(self_obj),PROTO_IT_FLAGS,ITEM_ACTION_USE);
     // rem_lootable;
   end
end
