/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Random Encounter scripts. These will be filled in more once they
   have been designed.
*/

procedure start;
procedure map_enter_p_proc;
procedure critter_p_proc;
procedure destroy_p_proc;

#include "..\headers\define.h"
//#include "..\headers\bhrnddst.h"

#define NAME                    SCRIPT_ECPLANT

#include "..\headers\command.h"

procedure start begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_RND_SPORE_PLANT);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_SPORE_PLANT);
end

procedure destroy_p_proc begin
end


procedure map_enter_p_proc begin
   variable item;

   if (map_first_run) then begin
       item:=create_object(PID_PLANT_SPIKE,0,0);
       add_mult_objs_to_inven(self_obj,item,10);
   end
end

procedure critter_p_proc begin
   if (obj_can_see_obj(self_obj,dude_obj)) then
       attack(dude_obj);
end

procedure use_obj_on_p_proc begin
end
