#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\modreact.h"

procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;

procedure Lance00;
procedure Lance00a;
procedure Lance01;
procedure Lance02;
procedure Lance03;
procedure Lance04;
procedure Lance04a;
procedure Lance05;
procedure Lance06;
procedure Lance07;
procedure Lance08;
procedure Lance09;
procedure Lance10;
procedure Lance11;
procedure Lance12;
procedure Lance13;
procedure Lance14;
procedure Lance15;
procedure Lance16;
procedure Lance17;
procedure Lance18;
procedure Lance19;
procedure Lance19a;
procedure Lance20;
procedure Lance21;
procedure Lance22;
procedure Lance23;
procedure Lance24;
procedure Lance25;
procedure Lance26;
procedure Lance27;
procedure Lance28;
procedure Lance29;
procedure Lance30;
procedure Lance31;
procedure Lance31a;
procedure Lance32;
procedure Lance33;
procedure Lance34;
procedure Lance35;
procedure Lance36;
procedure Lance37;
procedure Lance38;
procedure Lance39;
procedure Lance40;
procedure Lance41;
procedure Lance42;
procedure Lance43;
procedure Lance44;
procedure Lance45;
procedure Lance46;
procedure Lance47;
procedure Lance48;
procedure Lance49;
procedure Lance50;
procedure Lance51;
procedure Lance52;
procedure LanceCombat;
procedure LanceEnd;
procedure LanceLoot;

variable initial :=  0;
variable go_to_Shady;
variable go_to_Raiders;
//variable global_temp;
//variable dest_tile;
//variable step_tile;
//variable in_dialog;
//variable forced_node;
//variable restock_amt;
//variable restock_obj;
//variable restock_trash;
//variable removed_qty;

procedure start
begin
	

	if not(initial) then begin
		initial :=  1;
		set_self_team(TEAM_SHADY_SANDS );
		set_self_ai( AI_GUARD );
	end
	if (script_action == 12) then begin//<-- critter_p_proc - (can also be "Critter_Action") - do they see you, should they wander, should they attack you, etc..
		call critter_p_proc;
	end
	else begin
		if (script_action == 18) then begin//destroy_p_proc - Object or Critter has been killed or otherwise eradicated. Fall down go boom.
			call destroy_p_proc;
		end
		else begin
			if (script_action == 4) then begin//<---caught stealing! (pickup_p_proc)
				call pickup_p_proc;
			end
			else begin
				if (script_action == 11) then begin//<--- talk_p_proc (Face icon), can also call "do_dialogue" or "do_dialog"
					call talk_p_proc;
				end
				else begin
					if (script_action == 21) then begin//MOUSE-OVER DESCRIPTION -- look_at_p_proc - (usually brief length. hovered mouse over object, haven't clicked on it.)
						script_overrides;
						if ((global_var( GVAR_LANCE_STATUS ) bwand 1) != 0) then begin
							display_msg(message_str(SCRIPT_LANCE, 101));
						end
						else begin
							display_msg(message_str(SCRIPT_LANCE, 100));
						end
						script_overrides;
					end
				end
			end
		end
	end
end

procedure critter_p_proc
begin
	if ((global_var( GVAR_LANCE_STATUS ) bwand 2) != 0) then begin
		attack(dude_obj);
	end
end

procedure destroy_p_proc
begin

	inc_good_critter
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 4 );
	set_global_var( GVAR_LANCE_DEAD_ALREADY_SEEN, 1 );
end

procedure pickup_p_proc
begin
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 2 );
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	get_reaction
	if (shady_invaded) then begin//GLOBAL_VAR_12 = Shady Sands invaded
		if ((global_var( GVAR_LANCE_STATUS ) bwand 1) != 0) then begin
			call Lance52;
		end
		else begin
			start_gdialog(699, self_obj, 4, -1, -1);
			gsay_start;
			call Lance49;
			gsay_end;
			end_dialogue;
		end
	end
	else begin
		if ((global_var( GVAR_LANCE_STATUS ) bwand 1) != 0) then begin
			if (local_var(1) == 1) then begin
				call Lance02;
			end
			else begin
				start_gdialog(699, self_obj, 4, -1, -1);
				gsay_start;
				call Lance03;
				gsay_end;
				end_dialogue;
			end
		end
		else begin
			if (global_var( GVAR_ENEMY_SHADY_SANDS ) or (check_general_rep < -30) or (has_rep_berserker) or has_rep_childkiller) then begin
				if ((global_var( GVAR_TANDI_RESCUE ) == 2) and (global_var( GVAR_RADSCORPION_SEED ) == 2)) then begin
					start_gdialog(699, self_obj, 4, -1, -1);
					gsay_start;
					call Lance00;
					gsay_end;
					end_dialogue;
				end
				else begin
					call Lance01;
				end
			end
			else begin
				if (global_var( GVAR_WORLDMAPLIST_SHADY_SANDS ) < 2) then begin
					if (local_var(1) >= 2) then begin
						start_gdialog(699, self_obj, 4, -1, -1);
						gsay_start;
						call Lance04;
						gsay_end;
						end_dialogue;
					end
					else begin
						call Lance05;
					end
				end
				else begin
					start_gdialog(699, self_obj, 4, -1, -1);
					gsay_start;
					if (local_var(1) >= 2) then begin
						call Lance07;
					end
					else begin
						call Lance06;
					end
					gsay_end;
					end_dialogue;
				end
			end
		end
	end
	if (go_to_Shady) then begin
		gfade_out(1);
		game_time_advance(game_ticks(86400));
		load_map(MAP_SHADYW, 0);
	end
	if (go_to_Raiders) then begin
		gfade_out(1);
		game_time_advance(game_ticks(86400));
		load_map(MAP_RAIDERS, 0);
	end
end

procedure Lance00
begin
	BottomReact
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 1 );
	gsay_reply(699, 102);
	giq_option( 4, SCRIPT_LANCE, 103, Lance00a, BAD_REACTION );
	giq_option( 4, SCRIPT_LANCE, 104, Lance10, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 105, Lance11, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 106, Lance12, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 107, Lance13, NEUTRAL_REACTION );
end

procedure Lance00a
begin
	if ((dude_strength > 7) or dude_item_count( PID_PLASMA_RIFLE ) or dude_item_count( PID_LASER_RIFLE ) or dude_item_count( PID_ROCKET_LAUNCHER ) or dude_item_count( PID_MINIGUN )) then begin
		call Lance08;
	end
	else begin
		call Lance09;
	end
end

procedure Lance01
begin
	BottomReact
	float_msg(self_obj, message_str(SCRIPT_LANCE, 108), 0);
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 2 );
end

procedure Lance02
begin
	float_msg(self_obj, message_str(SCRIPT_LANCE, 109), 0);
end

procedure Lance03
begin
	gsay_reply(699, 110);
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 111, Lance14, NEUTRAL_REACTION );
	end
	if (tandi_is_kidnapped and (global_var( GVAR_TANDI_RESCUE ) == 1)) then begin
		giq_option( 4, SCRIPT_LANCE, 112, Lance15, NEUTRAL_REACTION );
	end
	if (global_var( GVAR_TANDI_RESCUE ) == 2) then begin
		giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 114, Lance17, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 115, Lance18, NEUTRAL_REACTION );
end

procedure Lance04
begin
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 1 );
	gsay_reply(699, 116);
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 111, Lance14, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 118, Lance04a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 119, Lance22, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 120, Lance23, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 121, Lance24, NEUTRAL_REACTION );
end

procedure Lance04a
begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call Lance19;
	end
	else begin
		call Lance20;
	end
end

procedure Lance05
begin
	float_msg(self_obj, message_str(SCRIPT_LANCE, 122), 0);
end

procedure Lance06
begin
	gsay_reply(699, message_str(SCRIPT_LANCE, 123) + dude_name + message_str(SCRIPT_LANCE, 124));
	giq_option( 4, SCRIPT_LANCE, 125, Lance25, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 127, Lance26, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 128, Lance28, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 121, Lance18, BAD_REACTION );
end

procedure Lance07
begin
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 1 );
	gsay_reply(699, message_str(SCRIPT_LANCE, 123) + dude_name + message_str(SCRIPT_LANCE, 130));
	giq_option( 4, SCRIPT_LANCE, 131, Lance29, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 111, Lance14, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 132, Lance00a, BAD_REACTION );
	giq_option( 4, SCRIPT_LANCE, 133, Lance30, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 121, Lance18, NEUTRAL_REACTION );
end

procedure Lance08
begin
	gsay_reply(699, 134);
	giq_option( 0, SCRIPT_MODREACT, 106, LanceLoot, BAD_REACTION );
end

procedure Lance09
begin
	gsay_message(699, 135, 51);
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 2 );
end

procedure Lance10
begin
	gsay_reply(699, 126);
	giq_option( 4, SCRIPT_LANCE, 136, Lance00a, BAD_REACTION );
	giq_option( 4, SCRIPT_LANCE, 137, Lance31, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 105, Lance11, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 106, Lance12, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 138, LanceCombat, BAD_REACTION );
end

procedure Lance11
begin
	BottomReact
	gsay_message(699, 139, 51);
end

procedure Lance12
begin
	gsay_message(699, 140, 51);
end

procedure Lance13
begin
	gsay_message(699, 141, 50);
end

procedure Lance14
begin
	gsay_reply(699, 142);
	giq_option( 4, SCRIPT_LANCE, 143, Lance14, NEUTRAL_REACTION );
	if ((global_var( GVAR_TANDI_RESCUE ) == 1) and tandi_is_kidnapped) then begin
		giq_option( 4, SCRIPT_LANCE, 112, Lance15, NEUTRAL_REACTION );
	end
	if (global_var( GVAR_TANDI_RESCUE ) == 2) then begin
		giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 114, Lance17, NEUTRAL_REACTION );
	if (global_var( GVAR_RADSCORPION_SEED ) == 2) then begin
		giq_option( 4, SCRIPT_LANCE, 144, Lance32, NEUTRAL_REACTION );
	end
end

procedure Lance15
begin
	gsay_reply(699, 145);
	giq_option( 4, SCRIPT_LANCE, 146, Lance33, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 147, Lance34, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 148, Lance35, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 149, Lance36, NEUTRAL_REACTION );
end

procedure Lance16
begin
	gsay_reply(699, 150);
	giq_option( 4, SCRIPT_LANCE, 151, Lance37, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 152, Lance38, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 144, Lance32, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 153, Lance39, NEUTRAL_REACTION );
end

procedure Lance17
begin
	gsay_reply(699, 154);
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 111, Lance14, NEUTRAL_REACTION );
	end
	if ((global_var( GVAR_TANDI_RESCUE ) == 1) and tandi_is_kidnapped) then begin
		giq_option( 4, SCRIPT_LANCE, 112, Lance15, NEUTRAL_REACTION );
	end
	if (global_var( GVAR_TANDI_RESCUE ) == 2) then begin
		giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 155, Lance17, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 156, Lance36, NEUTRAL_REACTION );
end

procedure Lance18
begin
	gsay_message(699, 157, 51);
end

procedure Lance19
begin
	gsay_reply(699, 158);
	giq_option( 4, SCRIPT_LANCE, 159, Lance19a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 160, Lance42, NEUTRAL_REACTION );
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 161, Lance43, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 162, Lance48, NEUTRAL_REACTION );
end

procedure Lance19a
begin
	if (dude_charisma > 6) then begin
		call Lance40;
	end
	else begin
		call Lance41;
	end
end

procedure Lance20
begin
	BottomReact
	gsay_message(699, 163, 51);
end

procedure Lance21
begin
	BottomReact
	gsay_message(699, 164, 51);
end

procedure Lance22
begin
	if (global_var( GVAR_WORLDMAPLIST_JUNKTOWN ) < 1) then
		set_global_var( GVAR_WORLDMAPLIST_JUNKTOWN, 1 );
	mark_on_map(AREA_JUNKTOWN)

	gsay_message(699, 165, 50);
end

procedure Lance23
begin
	BottomReact
	gsay_message(699, 166, 51);
end

procedure Lance24
begin
	gsay_message(699, 167, 51);
end

procedure Lance25
begin
	gsay_reply(699, 168);
	giq_option( 4, SCRIPT_LANCE, 169, Lance44, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 170, LanceCombat, BAD_REACTION );
	giq_option( 4, SCRIPT_LANCE, 171, Lance28, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 172, Lance31, NEUTRAL_REACTION );
end

procedure Lance26
begin
	gsay_reply(699, 173);
	giq_option( 4, SCRIPT_LANCE, 169, Lance44, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 170, Lance45, BAD_REACTION );
	giq_option( 4, SCRIPT_LANCE, 171, Lance28, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 172, Lance31, NEUTRAL_REACTION );
end

procedure Lance27
begin
	BottomReact
	gsay_reply(699, 174);
	giq_option( 0, SCRIPT_MODREACT, 106, LanceLoot, BAD_REACTION );
end

procedure Lance28
begin
	gsay_message(699, 175, 50);
end

procedure Lance29
begin
	gsay_reply(699, 176);
	giq_option( 4, SCRIPT_LANCE, 177, Lance46, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 178, Lance47, NEUTRAL_REACTION );
end

procedure Lance30
begin
	gsay_reply(699, 179);
	giq_option( 0, SCRIPT_MODREACT, 106, Lance29, NEUTRAL_REACTION );
end

procedure Lance31
begin
	gsay_reply(699, 180);
	giq_option( 0, SCRIPT_MODREACT, 106, Lance31a, BAD_REACTION );
end

procedure Lance31a
begin
	gsay_message(699, 181, 50);
end

procedure Lance32
begin
	gsay_reply(699, 182);
	if ((global_var( GVAR_QUEST_VAULT13_4_WATERCHIP ) == 1) and (dude_item_count( PID_WATER_CHIP ) == 0)) then begin
		giq_option( 4, SCRIPT_LANCE, 161, Lance43, NEUTRAL_REACTION );
	end
	if ((global_var( GVAR_TANDI_RESCUE ) == 1) and tandi_is_kidnapped) then begin
		giq_option( 4, SCRIPT_LANCE, 112, Lance15, NEUTRAL_REACTION );
	end
	if (global_var( GVAR_TANDI_RESCUE ) == 2) then begin
		giq_option( 4, SCRIPT_LANCE, 113, Lance16, NEUTRAL_REACTION );
	end
	giq_option( 4, SCRIPT_LANCE, 114, Lance17, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 183, Lance36, NEUTRAL_REACTION );
end

procedure Lance33
begin
	gsay_message(699, 184, 50);
	go_to_Shady := 1;
end

procedure Lance34
begin
	gsay_message(699, 185, 50);
	go_to_Raiders := 1;
end

procedure Lance35
begin
	gsay_message(699, 186, 50);
end

procedure Lance36
begin
	gsay_message(699, 187, 50);
end

procedure Lance37
begin
	gsay_message(699, 188, 50);
	call LanceLoot;
end

procedure Lance38
begin
	gsay_message(699, 189, 50);
end

procedure Lance39
begin
	gsay_message(699, 190, 49);
end

procedure Lance40
begin
	gsay_message(699, 191, 50);
	go_to_Shady := 1;
end

procedure Lance41
begin
	gsay_message(699, 192, 50);
end

procedure Lance42
begin
	gsay_message(699, 193, 50);
end

procedure Lance43
begin
	gsay_reply(699, 194);
	giq_option( 0, SCRIPT_MODREACT, 106, Lance36, NEUTRAL_REACTION );
end

procedure Lance44
begin
	gsay_message(699, 195, 50);
end

procedure Lance45
begin
	BottomReact
	gsay_message(699, 196, 51);
end

procedure Lance46
begin
	gsay_message(699, 197, 50);
	go_to_Shady := 1;
end

procedure Lance47
begin
	gsay_message(699, 198, 50);
end

procedure Lance48
begin
	gsay_message(699, 199, 50);
end

procedure Lance49
begin
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 1 );
	gsay_reply(699, 200);
	giq_option( 4, SCRIPT_LANCE, 201, Lance50, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 202, Lance51, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 203, Lance50, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_LANCE, 204, Lance51, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_LANCE, 205, Lance51, NEUTRAL_REACTION );
end

procedure Lance50
begin
	gsay_message(699, 206, 50);
end

procedure Lance51
begin
	gsay_message(699, 207, 50);
end

procedure Lance52
begin
	float_msg(self_obj, message_str(SCRIPT_LANCE, 208), 0);
end

procedure LanceCombat
begin
	set_global_var( GVAR_LANCE_STATUS, global_var( GVAR_LANCE_STATUS ) bwor 2 );
end

procedure LanceEnd
begin
end

procedure LanceLoot
begin
	inven_unwield( self_obj );
	move_obj_inven_to_obj(self_obj, dude_obj);
end









