
#
# Messages for Maps
#
#Darek regarding dream sequences:
#
# The intervals are 23 Oct 2241, 21 Jan 2242, 21 Apr 2242 and 20 Jul 2242 For Fallout 2, or adjusted for Fallout 1 the first one comes 05 Mars 2162, and you can just count the rest from there.
#
#If done on exit in map script of first map the movie will be played upon leaving map to worlmap, and will be hardly noticed (just a quick fade out).
#Should also add a "" in the map script for the new location, or the world map will display "unknown" and the fast travel button will be missing..
#

#
# Map Names for lookups
#  Note: This order must *NOT* change!
#
{0}{}{DESERT1.MAP}
{1}{}{DESERT2.MAP}
{2}{}{DESERT3.MAP}
{3}{}{HALLDED.MAP}
{4}{}{HOTEL.MAP}
{5}{}{WATRSHD.MAP}
{6}{}{VAULT13.MAP}
{7}{}{VAULTENT.MAP}
{8}{}{VAULTBUR.MAP}
{9}{}{VAULTNEC.MAP}
{10}{}{JUNKENT.MAP}
{11}{}{JUNKCSNO.MAP}
{12}{}{JUNKKILL.MAP}
{13}{}{BROHDENT.MAP}
{14}{}{BROHD12.MAP}
{15}{}{BROHD34.MAP}
{16}{}{CAVES.MAP}
{17}{}{CHILDRN1.MAP}
{18}{}{CHILDRN2.MAP}
{19}{}{CITY1.MAP}
{20}{}{COAST1.MAP}
{21}{}{COAST2.MAP}
{22}{}{COLATRUK.MAP}
{23}{}{FSAUSER.MAP}
{24}{}{RAIDERS.MAP}
{25}{}{SHADYE.MAP}
{26}{}{SHADYW.MAP}
{27}{}{GLOWENT.MAP}
{28}{}{LAADYTUM.MAP}
{29}{}{LAFOLLWR.MAP}
{30}{}{MBENT.MAP}
{31}{}{MBSTRG12.MAP}
{32}{}{MBVATS12.MAP}
{33}{}{MSTRLR12.MAP}
{34}{}{MSTRLR34.MAP}
{35}{}{V13ENT.MAP}
{36}{}{HUBENT.MAP}
{37}{}{DETHCLAW.MAP}
{38}{}{HUBDWNTN.MAP}
{39}{}{HUBHEIGT.MAP}
{40}{}{HUBOLDTN.MAP}
{41}{}{HUBWATER.MAP}
{42}{}{GLOW1.MAP}
{43}{}{GLOW2.MAP}
{44}{}{LABLADES.MAP}
{45}{}{LARIPPER.MAP}
{46}{}{LAGUNRUN.MAP}
{47}{}{CHILDEAD.MAP}
{48}{}{MBDEAD.MAP}
{49}{}{MOUNTN1.MAP}
{50}{}{MOUNTN2.MAP}
{51}{}{FOOT.MAP}
{52}{}{TARDIS.MAP}
{53}{}{TALKCOW.MAP}
{54}{}{USEDCAR.MAP}
{55}{}{BRODEAD.MAP}
{56}{}{DESCRVN1.MAP}
{57}{}{DESCRVN2.MAP}
{58}{}{MNTCRVN1.MAP}
{59}{}{MNTCRVN2.MAP}
{60}{}{VIPERS.MAP}
{61}{}{DESCRVN3.MAP}
{62}{}{MNTCRVN3.MAP}
{63}{}{DESCRVN4.MAP}
{64}{}{MNTCRVN4.MAP}
{65}{}{HUBMIS1.MAP}

#
# Map Names for (Automap) Descriptions
#  Note: This order must *NOT* change!
#
#  Note: The maximum description width is approximately:
#    "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#    but it's proportional, so you need to double-check it by
#    going into mapper/game and going to the automap for that map.
#
#  Note: Descriptions *MUST* *NOT* be empty, and so temporary
#    descriptions are just the map name itself (this also helps
#    pinpoint unfinished ones when you go through here).
#
{100}{}{Desert}                        # DESERT1.MAP
{101}{}{Desert}                        # DESERT2.MAP
{102}{}{Desert}                        # DESERT3.MAP
{103}{}{Necropolis}                    # HALLDED.MAP
{104}{}{Necropolis}                    # HOTEL.MAP
{105}{}{Necropolis}                    # WATRSHD.MAP
{106}{}{Vault 13}                      # VAULT13.MAP
{107}{}{Vault 15}                      # VAULTENT.MAP
{108}{}{Vault 15}                      # VAULTBUR.MAP
{109}{}{Necropolis}                    # VAULTNEC.MAP
{110}{}{Junktown}                      # JUNKENT.MAP
{111}{}{Junktown}                      # JUNKCSNO.MAP
{112}{}{Junktown}                      # JUNKKILL.MAP
{113}{}{Brotherhood of Steel}          # BROHDENT.MAP
{114}{}{Brotherhood of Steel}          # BROHD12.MAP
{115}{}{Brotherhood of Steel}          # BROHD34.MAP
{116}{}{Shady Sands}                   # CAVES.MAP
{117}{}{Children of the Cathedral}     # CHILDRN1.MAP
{118}{}{Children of the Cathedral}     # CHILDRN2.MAP
{119}{}{City Ruins}                    # CITY1.MAP
{120}{}{Coast}                         # COAST1.MAP
{121}{}{Coast}                         # COAST2.MAP
{122}{}{Desert}                        # COLATRUK.MAP
{123}{}{Desert}                        # FSAUSER.MAP
{124}{}{Raiders}                       # RAIDERS.MAP
{125}{}{Shady Sands}                   # SHADYE.MAP
{126}{}{Shady Sands}                   # SHADYW.MAP
{127}{}{Glow}                          # GLOWENT.MAP
{128}{}{Boneyard}                      # LAADYTUM.MAP
{129}{}{Boneyard}                      # LAFOLLWR.MAP
{130}{}{Military Base}                 # MBENT.MAP
{131}{}{Military Base}                 # MBSTRG12.MAP
{132}{}{Military Base}                 # MBVATS12.MAP
{133}{}{Military Base}                 # MSTRLR12.MAP
{134}{}{Military Base}                 # MSTRLR34.MAP
{135}{}{Vault 13}                      # V13ENT.MAP
{136}{}{Hub}                           # HUBENT.MAP
{137}{}{Hub}                           # DETHCLAW.MAP
{138}{}{Hub}                           # HUBDWNTN.MAP
{139}{}{Hub}                           # HUBHEIGT.MAP
{140}{}{Hub}                           # HUBOLDTN.MAP
{141}{}{Hub}                           # HUBWATER.MAP
{142}{}{Glow}                          # GLOW1.MAP
{143}{}{Glow}                          # GLOW2.MAP
{144}{}{Boneyard}                      # LABLADES.MAP
{145}{}{Boneyard}                      # LARIPPER.MAP
{146}{}{Boneyard}                      # LAGUNRUN.MAP
{147}{}{Children of the Cathedral}     # CHILDEAD.MAP
{148}{}{Military Base}                 # MBDEAD.MAP
{149}{}{Mountains}                     # MOUNTN1.MAP
{150}{}{Mountains}                     # MOUNTN2.MAP
{151}{}{Desert}                        # FOOT.MAP
{152}{}{Desert}                        # TARDIS.MAP
{153}{}{Desert}                        # TALKCOW.MAP
{154}{}{Desert}                        # USEDCAR.MAP
{155}{}{Brotherhood of Steel}          # BRODEAD.MAP
{156}{}{Desert}                        # DESCRVN1.MAP
{157}{}{Desert}                        # DESCRVN2.MAP
{158}{}{Mountains}                     # MNTCRVN1.MAP
{159}{}{Mountains}                     # MNTCRVN2.MAP
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}

{165}{}{Desert}                        # FOOT.MAP
{166}{}{Desert}                        # TARDIS.MAP
{167}{}{Desert}                        # USEDCAR.MAP
{168}{}{Desert}                        # COLATRUK.MAP
{169}{}{Desert}                        # FSAUSER.MAP
{170}{}{Desert}                        # TALKCOW.MAP
{171}{}{Temple}                        # ARTEMPLE.MAP
{172}{}{Temple}                        # ARTEMPLE.MAP
{173}{}{Desert}                        # rndforvr.MAP
{174}{}{Scrapheap}                     # JUNKDEMO.MAP

{175}{}{Shady Sands}                   # CAVES.MAP
{176}{}{Hub}                           # HUBMIS0.MAP
{177}{}{Hub}                           # DETHCLAW.MAP
{178}{}{City Ruins}                    # CITY2.MAP
{179}{}{City Ruins}                    # CITY3.MAP
{180}{}{Mountains}                     # CAVE0.MAP
{181}{}{Mountains}                     # CAVE1.MAP
{182}{}{Mountains}                     # CAVE2.MAP
{183}{}{Mountains}                     # CAVE3.MAP
{184}{}{Mountains}                     # CAVE4.MAP
{185}{}{Mountains}                     # CAVE5.MAP
{186}{}{Mountains}                     # MINE1.MAP
{187}{}{Mountains}                     # MINE2.MAP
{188}{}{Mountains}                     # MINE3.MAP

#
# City elevation names
#
# Format: 3 (max elevations), by city
#
# Desert, DESERT1.MAP
{200}{}{Desert}
{201}{}{}
{202}{}{}
# Desert, DESERT2.MAP
{203}{}{Desert}
{204}{}{}
{205}{}{}
# Desert, DESERT3.MAP
{206}{}{Desert}
{207}{}{}
{208}{}{}
# Necropolis Hall of the Dead, HALLDED.MAP
{209}{}{Sewers}
{210}{}{Hall}
{211}{}{}
# Necropolis Hotel of Doom, HOTEL.MAP
{212}{}{Sewers}
{213}{}{Hotel}
{214}{}{}
# Necropolis Watershed, WATRSHD.MAP
{215}{}{Sewers}
{216}{}{Watershed}
{217}{}{}
# Vault 13, VAULT13.MAP
{218}{}{Entrance}
{219}{}{Living Quarters}
{220}{}{Command Center}
# Buried Vault Entrance, VAULTENT.MAP
{221}{}{Cave Entrance}
{222}{}{}
{223}{}{}
# Buried Vault,  VAULTBUR.MAP
{224}{}{Caverns}
{225}{}{Living Quarters}
{226}{}{Command Center}
# Necropolis Vault, VAULTNEC.MAP
{227}{}{Sewers}
{228}{}{Living Quarters}
{229}{}{Command Center}
# Junktown Entrance, JUNKENT.MAP
{230}{}{Entrance}
{231}{}{Lab}
{232}{}{}
# Junktown Casino, JUNKCSNO.MAP
{233}{}{Casino}
{234}{}{}
{235}{}{}
# Junktown Killian's, JUNKKILL.MAP
{236}{}{Crash House}
{237}{}{}
{238}{}{}
# Brotherhood of Steel Entrance, BROHDENT.MAP
{239}{}{Entrance}
{240}{}{}
{241}{}{}
# Brotherhood of Steel (Upper Levels), BROHD12.MAP
{242}{}{Level 1}
{243}{}{Level 2}
{244}{}{}
# Brotherhood of Steel (Lower Levels), BROHD34.MAP
{245}{}{Level 3}
{246}{}{Level 4}
{247}{}{}
# Caves (Shady sands), CAVES.MAP
{248}{}{Caves}
{249}{}{}
{250}{}{}
# Cathedral, CHILDRN1.MAP
{251}{}{Entrance}
{252}{}{Tower Level 1}
{253}{}{}
# Cathedral Tower, CHILDRN2.MAP
{254}{}{Tower Level 2}
{255}{}{Tower Level 3}
{256}{}{Tower Level 4}
# City Ruins, CITY1.MAP
{257}{}{City Ruins}
{258}{}{}
{259}{}{}
# Coast, COAST1.MAP
{260}{}{Coast}
{261}{}{}
{262}{}{}
# Coast, COAST2.MAP
{263}{}{Coast}
{264}{}{}
{265}{}{}
# Desert, COLATRUK.MAP
{266}{}{Desert}
{267}{}{}
{268}{}{}
# Desert, FSAUSER.MAP
{269}{}{Desert}
{270}{}{}
{271}{}{}
# Raider's Camp, RAIDERS.MAP
{272}{}{Base}
{273}{}{}
{274}{}{}
# Shady Sands East, SHADYE.MAP
{275}{}{Garden}
{276}{}{Brahmin Pen}
{277}{}{}
# Shady Sands West, SHADYW.MAP
{278}{}{Town Hall}
{279}{}{}
{280}{}{}
# GLOWENT.MAP
{281}{}{Entrance}
{282}{}{}
{283}{}{}
# LAADYTUM.MAP
{284}{}{Adytum}
{285}{}{Underground}
{286}{}{}
# LAFOLLWR.MAP
{287}{}{Library}
{288}{}{Underground}
{289}{}{}
# Military Base Entrance, MBENT.MAP
{290}{}{Entrance}
{291}{}{}
{292}{}{}
# Military Base Stronghold, MBSTRG12.MAP
{293}{}{Stronghold Level 1}
{294}{}{Stronghold Level 2}
{295}{}{}
# Military Base Vats, MBVATS12.MAP
{296}{}{Vats Level 1}
{297}{}{Vats Level 2}
{298}{}{}
# Master's Lair (Upper Levels), MSTRLR12.MAP
{299}{}{Lair Level 1}
{300}{}{Lair Level 2}
{301}{}{}
# Master's Lair (Lower Levels), MSTRLR34.MAP
{302}{}{Lair Level 3}
{303}{}{Lair Level 4}
{304}{}{}
# Vault 13 Entrance, V13ENT.MAP
{305}{}{Cave Entrance}
{306}{}{}
{307}{}{}
# Hub Entrance, HUBENT.MAP
{308}{}{Entrance}
{309}{}{}
{310}{}{}
# DeathClaw's Lair, DETHCLAW.MAP
{311}{}{Lair}
{312}{}{}
{313}{}{}
# Hub Downtown, HUBDWNTN.MAP
{314}{}{Downtown}
{315}{}{Decker's Hideout}
{316}{}{}
# HUBHEIGT.MAP
{317}{}{Heights}
{318}{}{}
{319}{}{}
# Hub Old Town, HUBOLDTN.MAP
{320}{}{Old Town}
{321}{}{Thieves Circle}
{322}{}{}
# HUBWATER.MAP
{323}{}{Merchants}
{324}{}{}
{325}{}{}
# GLOW1.MAP
{326}{}{Level 1}
{327}{}{Level 2}
{328}{}{Level 3}
# GLOW2.MAP
{329}{}{Level 4}
{330}{}{Level 5}
{331}{}{Level 6}
# LABLADES.MAP
{332}{}{Downtown}
{333}{}{}
{334}{}{}
# LARIPPER.MAP
{335}{}{Warehouse}
{336}{}{Underground}
{337}{}{}
# LAGUNRUN.MAP
{338}{}{Fortress}
{339}{}{}
{340}{}{}
# CHILDEAD.MAP
{341}{}{Crater}
{342}{}{}
{343}{}{}
# MBDEAD.MAP
{344}{}{Ruins}
{345}{}{}
{346}{}{}
# MOUNTN1.MAP
{347}{}{Mountains}
{348}{}{}
{349}{}{}
# MOUNTN2.MAP
{350}{}{Mountains}
{351}{}{}
{352}{}{}
# FOOT.MAP
{353}{}{Desert}
{354}{}{}
{355}{}{}
# TARDIS.MAP
{356}{}{Desert}
{357}{}{}
{358}{}{}
# 53: Car Desert out-of-gas, CarDesrt.MAP
{359}{}{Desert}
{360}{}{}
{361}{}{}
# USEDCAR.MAP
{362}{}{Desert}
{363}{}{}
{364}{}{}
# BRODEAD.MAP
{365}{}{Ruins}
{366}{}{}
{367}{}{}
# DESCRVN1.MAP
{368}{}{Desert}
{369}{}{Desert}
{370}{}{Desert}
# DESCRVN2.MAP
{371}{}{Desert}
{372}{}{Desert}
{373}{}{Desert}
# MNTCRVN1.MAP
{374}{}{Mountains}
{375}{}{Mountains}
{376}{}{Mountains}
# MNTCRVN2.MAP
{377}{}{Mountains}
{378}{}{Mountains}
{379}{}{Mountains}
# DESCRVN3.MAP
{380}{}{Desert}
{381}{}{Desert}
{382}{}{Desert}
# MNTCRVN3.MAP
{383}{}{Mountains}
{384}{}{Mountains}
{385}{}{Mountains}
# DESCRVN4.MAP
{386}{}{Desert}
{387}{}{Desert}
{388}{}{Desert}
# MNTCRVN4.MAP
{389}{}{Mountains}
{390}{}{Mountains}
{391}{}{Mountains}
# DESERT1.MAP
{392}{}{Desert}
{393}{}{Desert}
{394}{}{Desert}
# HUBMIS0.MAP
{395}{}{Irwin's Farm}
{396}{}{}
{397}{}{}

# HUBMIS1.MAP UNUSED
{398}{}{Irwin's Farm}
{399}{}{}
{400}{}{}

# RNDDESER.MAP
{401}{}{Desert}
{402}{}{Desert}
{403}{}{Desert}
# rndmount.MAP
{404}{}{Mountains}
{405}{}{Mountains}
{406}{}{Mountains}
# rndcity.MAP
{407}{}{City Ruins}
{408}{}{City Ruins}
{409}{}{City Ruins}
# rndcoast.MAP
{410}{}{Coast}
{411}{}{Coast}
{412}{}{Coast}

# TALKCOW.MAP
{413}{}{Desert}
{414}{}{}
{415}{}{}

# Arroyo Temple, ARTEMPLE.MAP
{416}{}{Entrance}
{417}{}{}
{418}{}{}
# Arroyo Caves, ARCAVES.MAP
{419}{}{Temple: Foyer}
{420}{}{Temple: Hallway}
{421}{}{Temple: Inner Sanctum}
# Special Encounter: Guardian of Forever
{422}{}{Desert}
{423}{}{}
{424}{}{}

# 75: Scrapheap / Fo1 Demo
{425}{}{Town}
{426}{}{}
{427}{}{}

# 76: Copy of Caves (Shady sands), CAVES.MAP - used for optional location circle feature
{428}{}{Caves}
{429}{}{}
{430}{}{}
# 77: Copy of Irwine's Farm, HUBMIS0.MAP - used for optional location circle feature
{431}{}{Farm}
{432}{}{}
{433}{}{}
# 78: Copy of DeathClaw's Lair, DETHCLAW.MAP - used for optional location circle feature
{434}{}{Lair}
{435}{}{}
{436}{}{}

# 79: City Ruins, CITY2.MAP
{437}{}{City Ruins}
{438}{}{}
{439}{}{}
# 80: City Ruins, CITY3.MAP
{440}{}{City Ruins}
{441}{}{}
{442}{}{}

# 81: Random Encounter Cavern 0
{443}{}{Mountains}
{444}{}{}
{445}{}{}
# 82: Random Encounter Cavern 1
{446}{}{Mountains}
{447}{}{Cavern}
{448}{}{}
# 83: Random Encounter Cavern 2
{449}{}{Mountains}
{450}{}{Cavern}
{451}{}{}
# 84: Random Encounter Cavern 3
{452}{}{Mountains}
{453}{}{Cavern}
{454}{}{}
# 85: Random Encounter Cavern 4
{455}{}{Mountains}
{456}{}{Cavern}
{457}{}{}
# 86: Random Encounter Cavern 5
{458}{}{Mountains}
{459}{}{Cavern}
{460}{}{Mountains}

# 87: Random Encounter Mine 1
{461}{}{Mountains}
{462}{}{Mine}
{463}{}{Desert}
# 88: Random Encounter Mine 2
{464}{}{Mountains}
{465}{}{Mine}
{466}{}{Desert}
# 89: Random Encounter Mine 3
{467}{}{Mountains}
{468}{}{Mine}
{469}{}{Desert}

# 90: Vipers
{470}{}{Camp}
{471}{}{}
{472}{}{}

#
#  Short City names (Visible on the worldmap under green circle, Map, and Automaps interface)
#
{1500}{}{Vault 13}
{1501}{}{Vault 15}
{1502}{}{Shady Sands}
{1503}{}{Junktown}
{1504}{}{Raiders}
{1505}{}{Necropolis}
{1506}{}{Hub}
{1507}{}{Brotherhood}
{1508}{}{Military Base}
{1509}{}{Glow}
{1510}{}{Boneyard}
{1511}{}{Cathedral}
{1512}{}{unused} # Crater
{1513}{}{unused} # Ruins
{1514}{}{Nomads}
{1515}{}{unused}
{1516}{}{unused}
{1517}{}{unused}
{1518}{}{unused}
{1519}{}{unused}
{1520}{}{unused}
{1521}{}{Bike Outta Power}
{1522}{}{unused}
{1523}{}{unused}
{1524}{}{unused}
{1525}{}{unused}
{1526}{}{ }                   # Holds all desert encounter maps
{1527}{}{ }                   # Holds all mountain encounter maps
{1528}{}{ }                   # Holds all city encounter maps
{1529}{}{ }                   # Holds all coast encounter maps
{1530}{}{unused}
{1531}{}{unused}
{1532}{}{unused}
{1533}{}{unused}
{1534}{}{unused}
{1535}{}{unused}
{1536}{}{unused}
{1537}{}{unused}
{1538}{}{unused}
{1539}{}{unused}
{1540}{}{unused}
{1541}{}{unused}
{1542}{}{unused}
{1543}{}{unused}
{1544}{}{Caravan}             # Holds all caravan encounter maps
{1545}{}{unused}
{1546}{}{unused}
{1547}{}{ }                   # Holds all encounter maps but unused in Fo1in2
{1548}{}{unused}
{1549}{}{ }                   # Desert - triggered by player
{1550}{}{ }                   # Mountain - triggered by player
{1551}{}{ }                   # City - triggered by player
{1552}{}{ }                   # Coast - triggered by player
{1553}{}{Giant Footprint}     # FOOT
{1554}{}{Unusual Call Box}    # TARDIS
{1555}{}{Bob's Car Mart}      # USEDCAR
{1556}{}{Nuka-Cola Truck}     # COLATRUK
{1557}{}{Crashed Saucer}      # FSAUSER
{1558}{}{Brahmin Herd}        # TALKCOW
{1559}{}{Guardian of Forever} # Guardian of Forever
{1560}{}{Scrapheap}           # Fo1 Demo
{1561}{}{Caves}
{1562}{}{Irwin's Farm}
{1563}{}{Deathclaw Lair}
{1564}{}{ }                   # Holds all cavern encounter maps

#
# Error Messages
#
{1000}{}{Error: Not enough disk space to save map!}
