{100}{}{Rocket}
{200}{}{Plasma Ball}
{300}{}{Explosion}
{400}{}{Blood}
{500}{}{No-Trans hex}
{501}{}{}
{600}{}{knife}
{700}{}{spear}
{800}{}{EMP Explosion}
{900}{}{Laser Blast}
{1000}{}{Plasma Blast}
{1100}{}{Explosion}
{1200}{}{Scroll Blocker}
{1300}{}{Electricity Bolt}
{1400}{}{Explosion}
{1500}{}{Explosion}
{1600}{}{Exit Grid}
{1700}{}{Exit Grid}
{1800}{}{Exit Grid}
{1900}{}{Exit Grid}
{2000}{}{Exit Grid}
{2100}{}{Exit Grid}
{2200}{}{Exit Grid}
{2300}{}{Exit Grid}
{2400}{}{Flare}
{2500}{}{Grenade}
{2600}{}{Rock}
{2700}{}{Explosion}
{2800}{}{Explosion}
{2900}{}{Explosion}
{3000}{}{Molotov Cocktail}
{3100}{}{Exit Grid}
{3200}{}{Exit Grid}
{3300}{}{Exit Grid}
{3400}{}{Exit Grid}
{3500}{}{Exit Grid}
{3600}{}{Exit Grid}
{3700}{}{Exit Grid}
{3800}{}{Exit Grid}
{3900}{}{Exit Grid}
{4000}{}{Exit Grid}
{4100}{}{Exit Grid}
{4200}{}{Exit Grid}
{4300}{}{Exit Grid}
{4400}{}{Exit Grid}
{4500}{}{Exit Grid}
{4600}{}{Exit Grid}
{4700}{}{Robot Rocket}
{4701}{}{}
{4800}{}{Ka-Pow!}
{4801}{}{}
{4900}{}{Plant Spike}
{4901}{}{}
{5000}{}{Dual Plasma Ball}
{5100}{}{ground}
