{101}{}{}                                               #obj_dude
{102}{}{Elder.}                                         #elder
{103}{}{Barterman}                                      #barter
{104}{}{Bodyguard}                                      #bguard
{105}{}{Cow}                                            #cow
{106}{}{Gunrunner Moat Guard}                           #MoatGrd
{107}{}{Shady Sands Guard}                              #guard
{108}{}{Loser}                                          #loser
{109}{}{Shady Sands Peasant}                            #pleasant
{110}{}{Gunrunner}                                      #GunRnr
{111}{}{Entrance to Map}                                #map_init
{112}{}{Radscorpion}                                    #radscorp
{113}{}{Super Mutant Sentry}                            #mutant2
{114}{}{Shady Sands Well}                               #sswell
{115}{}{Set}                                            #set
{116}{}{Harry}                                          #harry
{117}{}{Stimpak}                                        #stimpack
{118}{}{Manhole Cover}                                  #cover
{119}{}{Manhole}                                        #manhole
{120}{}{Ladder}                                         #ladder
{121}{}{Chair}                                          #chair
{122}{}{Nuka Cola Machine}                              #coke
{123}{}{Manager's Desk}                                 #computer
{124}{}{Corpse}                                         #dead
{125}{}{Desk}                                           #desk
{126}{}{Ghoul Corpse}                                   #1dedgul1
{127}{}{Mole Rat}                                       #1molrat1
{128}{}{Manhole}                                        #1manhol1
{129}{}{Ladder}                                         #1ladder1
{130}{}{Ghoul Manager}                                  #ghoul
{131}{}{Map Script}                                     #alphhotl
{132}{}{Ghoul}                                          #genghoul
{133}{}{Aradesh}                                        #Aradesh
{134}{}{Brahmin}                                        #Brahmin
{135}{}{Cougar}                                         #Cougar
{136}{}{Flash}                                          #Flash
{137}{}{Junktown Guard}                                 #JtGenGrd
{138}{}{Junktown Peasant}                               #JtPeasnt
{139}{}{Butch}                                          #Butch
{140}{}{Cabbot}                                         #Cabbot
{141}{}{Children of the Cathedral Member}               #  Childmem
{142}{}{Decker}                                         #Decker
{143}{}{Elder}                                          #Elder
{144}{}{Gizmo}                                          #Gizmo
{145}{}{Harold}                                         #Harold
{146}{}{Jain}                                           #Jain
{147}{}{Killian}                                        #Killian
{148}{}{Laura}                                          #Laura
{149}{}{Loxley}                                         #Loxley
{150}{}{Lieutenant}                                     #Lt
{151}{}{Master}                                         #Master
{152}{}{Maxson}                                         #  Maxson
{153}{}{Morpheus}                                       #  Morph
{154}{}{Nicole}                                         #  Nicole
{155}{}{Overseer}                                       #  Over
{156}{}{Rhombus}                                        #  Rhombus
{157}{}{Tandi}                                          #  Tandi
{158}{}{Vree}                                           #  Vree
{159}{}{Mole Rat}                                       #  1MoleRat
{160}{}{Necropolis Airlock}                             #  AirLock
{161}{}{Barry}                                          #  Barry
{162}{}{Computer}                                       #  DeadComp
{163}{}{Door}                                           #  Door
{164}{}{Ganger Ghoul}                                   #  Ganger
{165}{}{Gary}                                           #  Gary
{166}{}{Ghoul}                                          #  Generic
{167}{}{Elder}                     				   		#  TMPLELDR.int     ; Temple elder script
{168}{}{Glowing One}                                    #  GenGlow1
{169}{}{Ghoul Corpse}                                   #  GhDead
{170}{}{Ghoul Sentry}                                   #  GhDorGrd
{171}{}{Ghoul Corpse}                                   #  GhGenDed
{172}{}{Set's Guard}                                    #  GhGuard
{173}{}{}                                				#  CARDESRT.int		; car out of gas!
{174}{}{Ghoul Refugee}                                  #  GhRefuge
{175}{}{Ghoul Guard}                                    #  GhZero
{176}{}{Caged Glowing One}                              #  GlowOne
{177}{}{Undergrounder}                                  #  Groundr
{178}{}{Spore Plant}                                    #  ECPlant.int
{179}{}{}                                               #  ECGecko.int
{180}{}{Larry}                                          #  Larry
{181}{}{Ganger Leader}                                  #  Leader
{182}{}{Ghoul Manager}                                  #  Manager
{183}{}{Mangled Corpse}                                 #  Mangled
{184}{}{Ghoul Peasant}                                  #  Meander
{185}{}{Super Mutant}                                   #  Mutant2
{186}{}{Water Computer}                                 #  NH2OComp
{187}{}{Water Pump}                                     #  NH2OPump
{188}{}{Wall}                                           #  OddWall
{189}{}{Ghoul Prisoner}                                 #  Prisonr
{190}{}{Sally}                                          #  Sally
{191}{}{Graffiti}                                       #  graffiti
{192}{}{Set's Cooler}                                   #  SetColer
{193}{}{Set's Desk}                                     #  SetDesk
{194}{}{Door}                                           #  SetDoor1
{195}{}{Set's Bodyguard}                                #  SetGuard
{196}{}{Wall}                                           #  SetSctDr
{197}{}{Odd Smell}                                      #  Smell
{198}{}{Stimpak}                                        #  StimPack
{199}{}{Necorpolis Storeroom}                           #  StoreRom
{200}{}{Super Mutant}                                   #  Super
{201}{}{Terry}                                          #  Terry
{202}{}{Garret}                                         #  Garret
{203}{}{Gretch}                                         #  Gretch
{204}{}{Morbid}                                         #  Morbid
{205}{}{Dumar}                                          #  Dumar
{206}{}{Barstow}                                        #  Barstow
{207}{}{Children of the Cathedral Initiate}             #  Genint
{208}{}{Children of the Cathedral Healer}               #  JtChidMem
{209}{}{Undergrounder Lookout}                          #  Lookout
{210}{}{Computer}                                       #  MachIV
{211}{}{Out of Business Sign}                           # ziClosed.int    ; Generic "Out of Business" signs
{212}{}{Desert}                                         #  RndDesrt
{213}{}{Shady Sands Guard}                              #  TGuard
{214}{}{Shady Sands Cook}                               #  cook
{215}{}{Shady Sands Citizen}                            #  citizen
{216}{}{Chair}                                          #  HousChar
{217}{}{Agatha's Bed}                                   #  AgathBed
{218}{}{Razlo's Bed}                                    #  RozBed
{219}{}{Razlo's Wife}                                   #  Wife
{220}{}{Dresser}                                        #  SDresser
{221}{}{Rug}                                            #  ShadyRug
{222}{}{Bookcase}                                       #  SBokcase
{223}{}{Fruit Jar}                                      #  MuteJar
{224}{}{Desk}                                           #  ShadDesk
{225}{}{Shelf}                                          #  CookShel
{226}{}{Table}                                          #  CookTabl
{227}{}{Mutated Fruit}                                  #  Fruit
{228}{}{Brahmin Pen Smell}                              #  PenSmell
{229}{}{Razlo}                                          #  Razlo
{230}{}{Vault 13 Citizen}                               #  ValtCtzn
{231}{}{Vault 13 Airlock}                               #  ValtLock
{232}{}{Vault 13 Monitor}                               #  ValtMon
{233}{}{Vault 13 Central Core}                          #  CoreComp
{234}{}{Vault 13 Library Computer}                      #  LibComp
{235}{}{Kalnor}                                         #  Assblow
{236}{}{Raider}                                         #  GenRaidr
{237}{}{Garl}                                           #  Garl
{238}{}{Raider Prisoner}                                #  RaidPris
{239}{}{Petrox}                                         #  Petrox
{240}{}{Tolya}                                          #  Tolya
{241}{}{Gwen}                                           #  Gwen
{242}{}{Diana}                                          #  Diana
{243}{}{Alya}                                           #  Alya
{244}{}{Living Quarters}                                #  LivingQ
{245}{}{Meeting Room}                                   #  Meeting
{246}{}{Storeroom}                                      #  BVStore
{247}{}{Library}                                        #  BVLib
{248}{}{Central Core}                                   #  BVCore
{249}{}{Meeting Room}                                   #  BVMeet
{250}{}{Living Quarters}                                #  BVLive
{251}{}{Living Quarters}                                #  UndrBed
{252}{}{Blocked Passage}                                #  RubChip
{253}{}{Blocked Passage}                                #  RubCore
{254}{}{Airlock}                                        ##  BVAirL
{255}{}{Hall of the Dead}                               #  HallDed1
{256}{}{Gabriel}                                        #  Gabriel
{257}{}{Craps Table}                                    #  HiCraps
{258}{}{Manhole}                                        #  NUp2Dwn1
{259}{}{Manhole}                                        #  NUp2Dwn2
{260}{}{Ladder}                                         #  NDwn2Up1
{261}{}{Ladder}                                         #  NDwn2Up2
{262}{}{Gate Guard}                                     #  GateDemo   ;
{263}{}{Water Ration Guard}                             #  WtrGrd
{264}{}{Watershed}                                      #  WatrShed
{265}{}{Manhole}                                        #  NWUp2Dn1
{266}{}{Manhole}                                        #  NWUp2Dn2
{267}{}{Manhole}                                        #  NWUp2Dn3
{268}{}{Vault 13 Citizen}                               #  Ration
{269}{}{Ladder}                                         #  NWDn2Up1
{270}{}{Ladder}                                         #  NWDn2Up2
{271}{}{Ladder}                                         #  NWDn2Up3
{272}{}{Andrew}                                         #  Andrew.int
{273}{}{Hotel of the Dead}                              #  HotelMap
{274}{}{Lorriane}                                       #  Lorian
{275}{}{Manhole}                                        #  NHUp2Dn1
{276}{}{Manhole}                                        #  NHUp2Dn2
{277}{}{Manhole}                                        #  NHUp2Dn3
{278}{}{Vault 13 Officer}                               #  Officer
{279}{}{Ladder}                                         #  NHDn2Up1
{280}{}{Ladder}                                         #  NHDn2Up2
{281}{}{Ladder}                                         #  NHDn2Up3
{282}{}{Radscorpion Caves}                              #  RadSCave
{283}{}{Seth}                                           #  Seth
{284}{}{Vault 13 Medic}                                 #  Medic
{285}{}{Vault 13 Citizen}                               #  GenVault
{286}{}{Junktown Casino}                                #  JunkCas
{287}{}{Junktown Crashhouse}                            #  JunkKill
{288}{}{Junktown Entrance}                              #  JunkEnt
{289}{}{Punching Bag}                                   #  ZSPnchBg.int    ; Punching Bag in the Sierra Depot
{290}{}{Airlock}                                        #  BVAir
{291}{}{Medical Cache}                                  #  BVCache
{292}{}{Vault 15 Entrance}                              #  BVEnt
{293}{}{Shady Sands}                                    #  ShadyEt
{294}{}{Shady Sands}                                    #  ShadyWst
{295}{}{Medical Lab}                                    #  MedLab
{296}{}{Abandonned Shack}                               #  shack
{297}{}{Seth}                                           #  Seth2
{298}{}{Brotherhood Scribe}                             #  SCRIBEA
{299}{}{Vault 13}                                       #  Vault13
{300}{}{Elevator}                                       #  BVElv1W
{301}{}{Elevator}                                       #  BVElv2E
{302}{}{Elevator}                                       #  BVElv2W
{303}{}{Elevator}                                       #  BVElv3
{304}{}{Broken Elevator}                                #  BVBroken
{305}{}{Brotherhood of Steel Entrance}                  #  BroHdEnt
{306}{}{Rat Breeding Pit}                               #  RatPit
{307}{}{Darkness}                                       #  FearDark
{308}{}{Cave Openning}                                  #  ValtLeav
{309}{}{Vault 13 Citizen}                               #  ValtCupl
{310}{}{Your Living Quarters}                           #  YourRoom
{311}{}{Katrina}                                        #  SSGuide
{312}{}{Cave Openning}                                  #  LiteLeav
{313}{}{Vault 13 Central Core}                          #  ValtCore
{314}{}{Computer}                                       #  VCompOp
{315}{}{Vault 13 Operations Room}                       #  ValtOp
{316}{}{Vautl 13 Security Room}                         #  ValtSec
{317}{}{Vault 13 Storage}                               #  ValtStor
{318}{}{Vault 13 Meeting Room}                          #  ValtMeet
{319}{}{Vault 13 Medical Lab}                           #  ValtMed
{320}{}{Scrapheap}                                      #  JunkDemo
{321}{}{Junktown Guard}                                 #  GuarDemo
{322}{}{}                                               #  WanRats
{323}{}{Flare}                                          #  Flare
{324}{}{Elevator}                                       #  ValEl1
{325}{}{Elevator}                                       #  ValEl2w
{326}{}{Elevator}                                       #  ValEl2e
{327}{}{Elevator}                                       #  ValEl3
{328}{}{Vault 15}                                       #  Vaultbur
{329}{}{Dog}                                            #  dog
{330}{}{Ghoul Guard}                                    #  GhRndGrd
{331}{}{Angry Ghoul}                                    #  GhKick
{332}{}{Super Mutant Guard}                             #  Mutant3
{333}{}{Super Mutant Sentry}                            #  Mutant4
{334}{}{Super Mutant}                                   #  Mutant5
{335}{}{Ian}                                            #  Ian
{336}{}{Curtis}                                         #  Curtis
{337}{}{Child}                                          #  Child
{338}{}{Raiders}                                        #  RaidMap
{339}{}{Mutated Fruit}                                  #  MutFruit
{340}{}{Raider Guard}                                   #  RaidGrd
{341}{}{Avellone}                                       #  Hunter
{342}{}{Dog}                                            #  Dog2
{343}{}{Duc}                                            #  Duc
{344}{}{City}                                           #  RndCity
{345}{}{Coast}                                          #  RndCoast
{346}{}{Mountain}                                       #  RndMtn
{347}{}{Hernandez}                                      #  Gambler
{348}{}{Caves}                                          #  VaultEnt
{349}{}{Miles}                                          #  Miles
{350}{}{Smitty}                                         #  Smitty
{351}{}{Adytowner}                                      #  Adytownr
{352}{}{Regulator}                                      #  Regulatr
{353}{}{Lorri}                                          #  Lorri
{354}{}{Sammael}                                        #  Sammael
{355}{}{Caleb}                                          #  Caleb
{356}{}{Taylor}                                         #  Taylor
{357}{}{Julianna}                                       #  Julie
{358}{}{Followers Scholar}                              #  FolSchol
{359}{}{Followers Initiate}                             #  FolInit
{360}{}{Nightkin Scout}                                 #  FlSupMut
{361}{}{Children of the Cathedral Scholar}              #  ChidScol
{362}{}{Children of the Cathedral Initiate}             #  ChidInit
{363}{}{Followers Scout}                                #  FolScout
{364}{}{Followers Guard}                                #  FolGuard
{365}{}{Thinker Super Mutant}                           #  ThSupMut
{366}{}{Heather}                                        #  Heather
{367}{}{Peter}                                          #  Peter
{368}{}{Jake}                                           #  Jake
{369}{}{Orfeo}                                          #  Orfeo
{370}{}{Marney}                                         #  Marney
{371}{}{Neil}                                           #  Neil
{372}{}{Amber}                                          #  Amber
{373}{}{Uthern}                                         #  Uthern
{374}{}{Talius}                                         #  Talius
{375}{}{Children of the Cathedral Guard}                #  ChdGuard
{376}{}{Children of the Cathedral Scout}                #  ChdScout
{377}{}{Super Mutant Scout}                             #  ScSupMut
{378}{}{Razor}                                          #  Razor
{379}{}{Blades Ganger}                                  #  Blade
{380}{}{Fire}                                           #  Fire
{381}{}{Beca}                                           #  Beca
{382}{}{Blades' Weaponsmaster}                          #  Dolgan
{383}{}{Michelle}                                       #  Michelle
{384}{}{Blades' Nightwatchman}                          #  Dragon
{385}{}{Romero}                                         #  Romero
{386}{}{Brotherhood of Steel}                           #  Brohd12
{387}{}{Brotherhood of Steel}                           #  Brohd34
{388}{}{Jon}                                            #  Jon
{389}{}{Prisoner}                                       #  RippPris
{390}{}{Brotherhood Scribe}                             #  SCRIBEB
{391}{}{Ladder}                                         #  BVLad
{392}{}{Charred Body}                                   #  CharBody
{393}{}{Dried Bones}                                    #  BoneBody
{394}{}{Corpse encased in odd armor}                    #  DeadBro
{395}{}{Holodisk}                                       #  GenDisk
{396}{}{Radiation Hotspot}                              #  HotSpot
{397}{}{Corpse encase in odd armor}                     #  PerNPwr
{398}{}{Secure Door}                                    #  Glo1Weap
{399}{}{Computer}                                       #  GloComp
{400}{}{Secure Door}                                    #  Glo3Supl
{401}{}{Generator}                                      #  GlowGen
{402}{}{Water Pump}                                     #  GlowPump
{403}{}{Living Quarters}                                #  SciRoom
{404}{}{Sentry Gun}                                     #  SentryGn
{405}{}{Door with red paint on it}                      #  GloRdDor
{406}{}{Door with blue paint on it}                     #  GloBlDor
{407}{}{Secure door}                                    #  Glo3Wep
{408}{}{Secured lockbox}                                #  GlwBox
{409}{}{Computer}                                       #  Tylier
{410}{}{Cage}                                           #  GlowCage
{411}{}{Table}                                          #  GlowTabl
{412}{}{Computer}                                       #  Zax
{413}{}{Unusual skeleton}                               #  GlwAlien
{414}{}{Note}                                           #  Freezer
{415}{}{Farli}                                          #  Farli
{416}{}{Darrel}                                         #  Darrel
{417}{}{Brotherhood Paladin Guard}                      #  PalGuard
{418}{}{Talus}                                          #  Talus
{419}{}{Sophia}                                         #  Sophia
{420}{}{Michael}                                        #  Michael
{421}{}{Secure Door}                                    #  Glo4Weap
{422}{}{Brotherhood Scribe}                             #  ScribeA
{423}{}{Brotherhood Scribe}                             #  ScribeB
{424}{}{Brotherhood Paladin Sentry}                     #  Sentry
{425}{}{Brotherhood Paladin}                            #  PaladinA
{426}{}{Brotherhood Paladin Guard}                      #  PaladinB
{427}{}{Brotherhood Paladin}                            #  PaladinC
{428}{}{Elevator with blue paint on it}                 #  GloBlElv
{429}{}{Brotherhood Knight}                             #  KnightA
{430}{}{Brotherhood Knight}                             #  KnightB
{431}{}{Desk}                                           #  GlowDesk
{432}{}{Weapons Systems Armed}                          #  WeapSys
{433}{}{Strange Holodisk}                               #  Artifact
{434}{}{Cabinet}                                        #  GloCabn
{435}{}{Noxious Fumes}                                  #  GasTrap
{436}{}{Lasers}                                         #  LazrTrap
{437}{}{Crazed Raider}                                  #  JtRaider
{438}{}{Sinthia}                                        #  Sinthia
{439}{}{Marcelles}                                      #  Marcelle
{440}{}{Secure Safe}                                    #  KillSafe
{441}{}{Bob}                                            #  JtBob
{442}{}{Trish}                                          #  Trish
{443}{}{Vault 13 Door}                                  #  V13Door
{444}{}{Door Computer}                                  #  V13Comp
{445}{}{Holodisk}                                       #  DiskA
{446}{}{Holodisk}                                       #  DiskD
{447}{}{Holodisk}                                       #  FEVDisk
{448}{}{Holodisk}                                       #  VreeDisk
{449}{}{Holodisk}                                       #  SecDisk
{450}{}{Holodisk}                                       #  CodeDisk
{451}{}{Gambler}                                        #  GenGambl
{452}{}{Phil}                                           #  Phil
{453}{}{Dogmeat}                                        #  Junkdog
{454}{}{Slot Machine}                                   #  ChepSlot
{455}{}{Slot Machine}                                   #  GoodSlot
{456}{}{Blackjack Table}                                #  LowJack
{457}{}{Blackjack Table}                                #  HighJack
{458}{}{Children of the Cathedral Technician}           #  ChocTech
{459}{}{Abel}                                           #  Abel
{460}{}{Force Field}                                    #  FieldA
{461}{}{Radio}                                          #  Radio
{462}{}{Sign}                                           #  VatSign
{463}{}{Very Secure Door}                               #  VConDoor
{464}{}{Computer}                                       #  ForcComp
{465}{}{Robobrain}                                      #  MrHandyA
{466}{}{Robobrain}                                      #  MrHandyB
{467}{}{Flip}                                           #  Flip
{468}{}{Computer}                                       #  RobCtrl
{469}{}{Nightkin Sargeant}                              #  VSgTeam9
{470}{}{Nightkin Sentry}                                #  VatTeam9
{471}{}{Computer}                                       #  VConComp
{472}{}{Lenore}                                         #  PeasantD
{473}{}{Computer}                                       #  DemoComp
{474}{}{Dog}                                            #  DemoDog
{475}{}{Lenore}                                         #  DemoPeas
{476}{}{Phil}                                           #  DemoPhil
{477}{}{Zack}                                           #  Zack
{478}{}{Theresa}                                        # theresa
{479}{}{Upset Vault 13 Citizen}                         # REBEL
{480}{}{Refridgerator}                                  # demodoor
{481}{}{Brotherhood Scribe}                             # SCRIBEC
{482}{}{Jason}                                          # JASON
{483}{}{Thug}                                           # THUG
{484}{}{Lasher}                                         # lasher
{485}{}{Vinnie}                                         # Vinnie
{486}{}{Victor}                                         # Victor
{487}{}{Shark}                                          # Shark
{488}{}{Sherry}                                         # Sherry
{489}{}{Tycho}                                          # Tycho
{490}{}{Skulz Ganger}                                   # GendSkulz
{491}{}{Slummer}                                        #Slummer
{492}{}{Zark}                                           #Zark
{493}{}{Calder}                                         # Calder
{494}{}{Nightkin Sentry}                                # ChidNite
{495}{}{Child with an Attitude}                         # ChidGAB
{496}{}{Chanter}                                        # GenChant
{497}{}{Ton}                                            # Barracus
{498}{}{Chanter}                                        # Chanter
{499}{}{Sister Francis}                                 # Francis
{500}{}{Dr. Wu}                                         # DocWu.int
{501}{}{Rutger}                                         # Rutger
{502}{}{Phrax}                                          # Phrax
{503}{}{Generator}                                      # DemoGen
{504}{}{Crypt Ganger}                                   #DemoCryp
{505}{}{Fool Ganger}                                    # DemoFool
{506}{}{Lenny}                                          #Lenny
{507}{}{Icepick}                                        #Icepick
{508}{}{Skizzer}                                        # Skizzer
{509}{}{Scrapheap Citizen}                              # Pez
{510}{}{Rock}                                           # Rock
{511}{}{Lex}                                            # Lex.int
{512}{}{Rayze}                                          # Rayze.int
{513}{}{Skippy}                                         #Skippy.int
{514}{}{Baka}                                           #Baka.int
{515}{}{Scout the Crypts}                               # scoutc.int
{516}{}{Scout the Fools}                                # scoutf.int
{517}{}{Follower of the Apocalypse}                     # FollMap.int
{518}{}{Computer}                                       # SemiComp
{519}{}{Irradiated Rat}                                 # RadRat
{520}{}{Refridgerator}                                  # NGarFrdg
{521}{}{Ladder}                                         # WtrLadr
{522}{}{Ladder}                                         #  NecVLadr
{523}{}{Manhole}                                        # NecVHole
{524}{}{Manhole}                                        # WtrHole
{525}{}{Necropolis Vault}                               # ValtNec
{526}{}{Town Map}                                       # TownMap
{527}{}{Airlock Door}                                   # MVAirloc.ssl
{528}{}{Bookshelf}                                      # MVBShelf.ssl
{529}{}{Bookshelf}                                      # MVSctShf.ssl
{530}{}{Caves}                                          # V13Cave
{531}{}{Secure Door}                                    # MvRCrDor
{532}{}{Command Center}                                 # COmmand
{533}{}{Super Mutant Sentry}                            # GenSupr
{534}{}{Krupper}                                        # Krupper
{535}{}{VanHaggen}                                      # Vanhag
{536}{}{Vasquez}                                        # Vasquez
{537}{}{Junktown Scout}                                 # JnkScout
{538}{}{Junktown Citizen}                               # PeasantC
{539}{}{Raider}                                         # GenRaid2
{540}{}{Jarvis}                                         # Jarvis
{541}{}{Stronghold}                                     # MBStrong
{542}{}{Vats}                                           # MBVats
{543}{}{Military Base Entrance}                         # MBEnt
{544}{}{Children of the Cathedral}                      #Childrn1.int
{545}{}{Children of the Cathedral}                      #Childrn2.int
{546}{}{Master's Vault}                                 #Master1.int
{547}{}{Master's Vault}                                 # Master2.int
{548}{}{Computer}                                       # MVComp
{549}{}{Nuclear Warhead}                                # MVNuke
{550}{}{Elevator}                                       # MVDwn2Up.int
{551}{}{Elevator}                                       # MVUp2Dwn.int
{552}{}{Stairwell}                                      # Chid2Mas.int
{553}{}{Staircase}                                      # Mas2Chid.int
{554}{}{Staircase}                                      # Chid2Twr.int
{555}{}{Stairwell}                                      # Tow2Chid.int
{556}{}{Door}                                           # COCDoor.int
{557}{}{Caves}                                          # Cave2v13.int
{558}{}{Vault 13}                                       # V132Cave.int
{559}{}{Secure Door}                                    # SecDoor.int
{560}{}{Spotlights}                                     # SPOTLITE
{561}{}{Water Thief}                                    # WtrThief.int
{562}{}{Jennifer}                                       # Jennifer.int
{563}{}{Explosion}                                      # Blast.int
{564}{}{Chair}                                          # UzChair.int
{565}{}{Cave wall}                                      # CaveWall.int
{566}{}{Elevator}                                       # Elev0.int
{567}{}{Elevator}                                       # Elev1.int
{568}{}{Elevator}                                       # Elev2.int
{569}{}{Elevator}                                       # Elev3.int
{570}{}{Elevator}                                       # Elev4.int
{571}{}{Elevator}                                       # Elev5.int
{572}{}{Elevator}                                       # Elev6.int
{573}{}{Barfly}                                         # Barfly.int
{574}{}{Vault 15}                                       # BV2Vault.int
{575}{}{Nuka Cola Truck}                                # ColaTruk.int
{576}{}{Flying Saucer}                                  # FSauser.int
{577}{}{The Glow}                                       # Glowent.int
{578}{}{The Glow}                                       # GlowMap1.int
{579}{}{The Glow}                                       # GlowMap2.int
{580}{}{L.A. Boneyard}                                  # LAAdytum.int
{581}{}{L.A. Boneyard}                                  #LABlades.int
{582}{}{L.A. Boneyard}                                  # LAGunRun.int
{583}{}{L.A. Boneyard}                                  # LARipper.int
{584}{}{The Hub}                                        # HubEnt.int
{585}{}{The Hub}                                        # HubDwnTn.int
{586}{}{The Hub}                                        # HubHeigt.int
{587}{}{The Hub}                                        # HubOldTn.int
{588}{}{The Hub}                                        # HubWater.int
{589}{}{Cave}                                           #DethCave.int
{590}{}{Strange Call Box}                               # DrWhoMap.int
{591}{}{Large Footprint}                                # LgFtPrnt.int
{592}{}{Used Car Lot}                                   # UsedCar.int
{593}{}{Herd of Brahmin}                                # TalkCows.int
{594}{}{Manhole}                                        # JTUp2Dn.int
{595}{}{Ladder}                                         # JTDn2Up.int
{596}{}{Viola}                                          # Viola.int
{597}{}{Surf}                                           # Surf.int
{598}{}{Door}                                           # ChocDoor.int
{599}{}{Dane}                                           # Dane.int
{600}{}{Jonathan}                                       # Jonathan.int
{601}{}{Brotherhood Student}                            # Student.int
{602}{}{Children of the Cathedral}                      # Cath2MV.int
{603}{}{Secure Door}                                    # Glo4Supl.int
{604}{}{Sewers}                                         # Hall2Mtl.int
{605}{}{Sewers}                                         # Hall2Shd.int
{606}{}{Hope}                                           # HUBHOPE.int    ; Hub - Singer in the Maltese Falcon
{607}{}{Lyle}                                           # Lyle.int
{608}{}{Neal}                                           # Neal.int
{609}{}{Floor}                                          # TrapFlor.int
{610}{}{Kenji}                                          # Kenji.int
{611}{}{The Glow}                                       # GEnt2Lv1.int
{612}{}{The Glow}                                       # GLv12Ent.int
{613}{}{Staircase}                                      # CTower1.int
{614}{}{Staircase}                                      # CTower2.int
{615}{}{Staircase}                                      # CTower3.int
{616}{}{Military Base}                                  # ExitBase.int
{617}{}{Radscorpion}                                    # SSRadSco.int
{618}{}{Lars}                                           # Lars.int
{619}{}{Elevator}                                       # Elev6_m1.int
{620}{}{Elevator}                                       # Elev7.int
{621}{}{Elevator}                                       # Elev9.int
{622}{}{Elevator}                                       # Elev10.int
{623}{}{Elevator}                                       # Elev11.int
{624}{}{Super Mutant Soldier}                           # GenMutan.int
{625}{}{Super Mutant Sargeant}                          # GenSarg.int
{626}{}{Very Secure Door}                               # MBOut2In.int
{627}{}{Trophy}                                         # Trophy.int
{628}{}{Saul}                                           # Saul.int
{629}{}{Gustofer}                                       # Gustofer.int
{630}{}{Robot}                                          # Robot.int
{631}{}{Nightkin Sentry}                                # VGateMut.int
{632}{}{Nightkin Sargeant}                              # VPLotMut.int
{633}{}{Nightkin Sentry}                                # VFenceMt.int
{634}{}{Holodisk}                                       # DoorCode.int
{635}{}{Garret}                                         # Guard2.int
{636}{}{Super Mutant Guard}                             # VDoorMut.int
{637}{}{Force Field}                                    # FieldB.int
{638}{}{Force Field}                                    # FieldC.int
{639}{}{Force Field}                                    # FieldD.int
{640}{}{Force Field}                                    # FieldE.int
{641}{}{Force Field}                                    # FieldF.int
{642}{}{Force Field}                                    # FieldG.int
{643}{}{Force Field}                                    # FieldH.int
{644}{}{Force Field}                                    # FieldI.int
{645}{}{Computer}                                       # ForceCon.int
{646}{}{Super Mutant Guard}                             # VTeam1.int
{647}{}{Super Mutant Guard}                             # VTeam2.int
{648}{}{Super Mutant Guard}                             # VTeam3.int
{649}{}{Super Mutant Guard}                             # VTeam4.int
{650}{}{Super Mutant Guard}                             # VTeam5.int
{651}{}{Super Mutant Guard}                             # VTeam6.int
{652}{}{Super Mutant Guard}                             # VTeam7.int
{653}{}{Super Mutant Guard}                             # VTeam8.int
{654}{}{Lorenzo's Guard}                                # avery.int
{655}{}{Lorenzo's Guard}                                # bill.int
{656}{}{Billy}                                          # billy.int
{657}{}{Bob}                                            # bob.int
{658}{}{Sign}                                           # bobsign.int
{659}{}{Lorenzo's Guard}                                # cally.int
{660}{}{Cleo}                                           # cleo.int
{661}{}{Caravan Driver}                                 # crvndrvr.int
{662}{}{Dan}                                            # dan.int
{663}{}{Dan's Wife}                                     # danwife.int
{664}{}{Hubbian}                                        # deadguy.int
{665}{}{Decker's Guard}                                 # deckgrd.int
{666}{}{Demetre}                                        # demetre.int
{667}{}{Deputy Fry}                                     # depfry.int
{668}{}{Dogmeat}                                        # dogmeat.int
{669}{}{Very Secure Door}                               # elecdoor.int
{670}{}{Floor}                                          # electrap.int
{671}{}{Farmer}                                         # femfarmr.int
{672}{}{Far Go Trader Guard}                            # fgtgard.int
{673}{}{Hub Police Officer}                             # gencop.int
{674}{}{Far Go Trader Merchant}                         # genfgt.int
{675}{}{Skag}                                           # genskag.int
{676}{}{Guido}                                          # guido.int
{677}{}{Secure Door}                                    # gunlock.int
{678}{}{Bodyguard}                                      # hbodgrd2.int
{679}{}{Children of the Cathedral Guard}                # hchdgrd.int
{680}{}{Farmer}                                         # hgenfarm.int
{681}{}{Hubbian Guard}                                  # hgengrd.int
{682}{}{Daren Hightower}                                # hightowr.int
{683}{}{Hightower's Guard}                              # htwrgrd.int
{684}{}{Hightower's Wife}                               # htwrwife.int
{685}{}{Hubber}                                         #/ hubber.int
{686}{}{Caravan Merchant}                               # hubcarvn.int
{687}{}{Hubbian Police Officer}                         # hubcop.int
{688}{}{Flower Child}                                   # hubflrcd.int
{689}{}{Jake}                                           # hubjake.int
{690}{}{Children of the Cathedral Patient}              # hubpatnt.int
{691}{}{Smitty}                                         # hubsmity.int
{692}{}{Jasmine}                                        # jasmine.int
{693}{}{Job Post}                                       # jobpost.int
{694}{}{Kane}                                           # kane.int
{695}{}{Keri}                                           # keri.int
{696}{}{Lorenzo's Guard}                                # leon.int
{697}{}{Lorenzo}                                        # lorenzo.int
{698}{}{Master Merchant}                                # mstmerch.int
{699}{}{Richie}                                         # richie.int
{700}{}{Rufus}                                          # rufus.int
{701}{}{Rutger}                                         # rutger.int
{702}{}{Sid}                                            # sid.int
{703}{}{Thorndyke}                                      # thorndyk.int
{704}{}{Troy}                                           # troy.int
{705}{}{Water Merchant Trader}                          # wmcarvn.int
{706}{}{Water Merchant Guard}                           # wtrMGrd.int
{707}{}{Computer}                                       # RadioCom.int
{708}{}{Super Mutant Sentry}                            # Comptrol.int
{709}{}{Caravan Merchant}                               # HGenCvan.int
{710}{}{Warning}                                        # VatWarn.int
{711}{}{Alarm}                                          # VatAlert.int
{712}{}{Floor}                                          # VPlasma.int
{713}{}{Floor}                                          # VBOOM.int
{714}{}{Floor}                                          # VLaser.int
{715}{}{Floor}                                          # VMonowir.int
{716}{}{Locker}                                         # VLocker.int
{717}{}{Beth}                                           # HBeth.int
{718}{}{Brotherhood Guard}                              # HallGrd.int
{719}{}{Brotherhood Guard}                              # RoomGrd.int
{720}{}{Brotherhood Trainer}                            # Spar.int
{721}{}{QA Cheat}                                       # Cheater.int
{722}{}{Izo}                                            # Izo.int
{723}{}{Katja}                                          # Katja.int
{724}{}{Manhole}                                        # Ady2Stor.int
{725}{}{Ladder}                                         # Stor2Ady.int
{726}{}{Ladder}                                         # FolDn2Up.int
{727}{}{Manhole}                                        # FolUp2Dn.int
{728}{}{Staircase}                                      # HDtDn2Up.int
{729}{}{Stairwell}                                      # HDtUp2Dn.int
{730}{}{Very Secure Door}                               # HDtVault.int
{731}{}{Mr. Handy}                                      # MrHandyC.int
{732}{}{Brotherhood Student}                            # Student.int
{733}{}{Thomas}                                         # Thomas.int
{734}{}{Modify Reaction}                                # ModReact.int
{735}{}{Manhole}                                        # Ady2Farm.int
{736}{}{Ladder}                                         # Farm2Ady.int
{737}{}{Manhole}                                        # Ady2Cell.int
{738}{}{Ladder}                                         # Cell2Ady.int
{739}{}{Gizmo's Guard}                                  # GizGuard.int
{740}{}{Ripper Ganger}                                  # ripper.int
{741}{}{Holodisk}                                       # MutDisk.int
{742}{}{Deathclaw}                                      # DethClaw.int
{743}{}{Deathclaw Spawn}                                # Deathspr.int
{744}{}{Fisherman}                                      # FishrMan.int
{745}{}{Fisherman's Son}                                # FishrSon.int
{746}{}{Unusual Call Box}                               # Tardis.int
{747}{}{Large Footprint}                                # FootMap.int
{748}{}{Unusual Call Box}                               # WhoMap.int
{749}{}{Brahmin}                                        # TalkCow.int
{750}{}{Herd of Brahmin}                                # TCowMap.int
{751}{}{Injured Peasant}                                # MissBro
{752}{}{Rough Guard}                                    # HubCaptr.int
{753}{}{Animate Forever}                                # animfrvr.int
{754}{}{Stairwell}                                      # ThfU2D.int
{755}{}{Staircase}                                      # ThfD2U.int
{756}{}{Newspaper Machine}                              # MVNews.int
{757}{}{Used Car Salesman}                              # Dealer.int
{758}{}{Used Car Lot}                                   # UsedCar.int
{759}{}{Brotherhood of Steel}                           # BroDead.int
{760}{}{Children of the Cathedral}                      # ChilDead.int
{761}{}{Military Base Entrance}                         # MBDead.int
{762}{}{Sarah}                                          # Sarah.int
{763}{}{Agatha}                                         # Agatha.int
{764}{}{Chuck}                                          # Chuck.int
{765}{}{Alan}                                           # Alan.int
{766}{}{Brenden}                                        # Brenden.int
{767}{}{Patrick}                                        # Patrick.int
{768}{}{Ismarc}                                         # Ismarc.int
{769}{}{Angry At You}                                   # Enemy.int
{770}{}{Alex}                                           # Alex.int
{771}{}{Gideon}                                         # Gideon.int
{772}{}{Jeremiah}                                       # Jerem.int
{773}{}{Super Mutant Guard}                             # AirGrd.int
{774}{}{Super Mutant Guard}                             # AirGrd2.int
{775}{}{Dr. Lorri}                                      # BOSLori.int
{776}{}{Moore}                                          # Moore.int
{777}{}{Lucy}                                           # Lucy.int
{778}{}{Wiggup}                                         # Wiggup.int
{779}{}{Mad Scientist}                                  # MadSci.int
{780}{}{Vincent}                                        # Vincent.int
{781}{}{Farm Parts}                                     # FARMPART.int
{782}{}{Prisoner}                                       # MLPrison.int
{783}{}{Prisoner}                                       # GenPris.int
{784}{}{Computer}                                       # PrisCon.int
{785}{}{Thomas}                                         # thomas2.int
{786}{}{Master's Pet}                                   # Monster.int
{787}{}{Computer}                                       # PsyCon.int
{788}{}{Rae}                                            # Ray.int
{789}{}{Very Secure Door}                               # BHDoor.int
{790}{}{Doctor's Assistant}                             # BOSAsIs.int
{791}{}{Your Roommate}                                  # RD1.int
{792}{}{Brotherhood of Steel Initiate}                  # GenInit.int
{793}{}{Coyote}                                         # Coyote.int
{794}{}{Super Mutant Senty}                             # Smone.int
{795}{}{Super Mutant Guard}                             # SMTwo.int
{796}{}{Sherrif Greene}                                 # Justin.int
{797}{}{Bartender}                                      # Falcon1.int
{798}{}{Hubbian Merchant}                               # Merch1.int
{799}{}{Lance}                                          # Lance.int
{800}{}{Raider}                                         # LoneRaid.int
{801}{}{}                               				# JGIZSIGN.int
{802}{}{Brotherhood Paladin Scout}                      # PalScout.int
{803}{}{Trent}                                          # Trent.int
{804}{}{Craps Dealer}                                   # HDealer.int
{805}{}{Slot Machine}                                   # HSlots.int
{806}{}{Drunk}                                          # HRndBar.int
{807}{}{Gambler}                                        # HGenGamb.int
{808}{}{Hooker}                                         # HHooker.int
{809}{}{John}                                           # HJohn.int
{810}{}{Dealer}                                         # HGenDeal.int
{811}{}{Praying Super Mutant}                           # Smpray.int
{812}{}{Praying Child of the Cathedral}                 # Cpray.int
{813}{}{Peasant}                                        # PeasVict.int
{814}{}{Roulette Dealer}                                # HRoulet.int
{815}{}{Junktown Peasant}                               # JunkPeas.int
{816}{}{Brotherhood Instructor}                         # Teacher.int
{817}{}{Brotherhood Scribe}                             # Genscrib.int
{818}{}{Brotherhood Knight}                             # Genknigh.int
{819}{}{Brotherhood Paladin}                            # Genpalad.int
{820}{}{Slot Machine}                                   # Hslots.int
{821}{}{Staircase}                                      # RipUp2Dn.int
{822}{}{Stairwell}                                      # RipDn2Up.int
{823}{}{Brotherhood Scribe}                             # Rd1Scrb1.int
{824}{}{Brotherhood Knight}                             # Rd1Knig.int
{825}{}{Computer Terminal}                              # term.int
{826}{}{Computer Terminal}                              # term1.int
{827}{}{Computer Terminal}                              # term2.int
{828}{}{Computer Terminal}                              # term3.int
{829}{}{Computer Terminal}                              # term4.int
{830}{}{Computer Terminal}                              # term5.int
{831}{}{Computer Terminal}                              # term6.int
{832}{}{Computer Terminal}                              # term7.int
{833}{}{Computer Terminal}                              # term8.int
{834}{}{Locker}                                         # Lccker.int
{835}{}{Mantis}                                         # Mantis.int
{836}{}{Work Table}                                     # WkTbl.int
{837}{}{Mad Scientist}                                  # MadBrot.int
{838}{}{Woman Prisoner}                                 # Women.int
{839}{}{Sink}                                           # Sink.int
{840}{}{Corridor of Revulsion}                          # Revulse.int
{841}{}{Generator}                                      # fieldgen.int
{842}{}{Computer}                                       # ElevCon.int
{843}{}{Zombie Guard}                                   # genzombi.int
{844}{}{Holodisk}                                       # BroHist.int
{845}{}{Holodisk}                                       # SopDisk.int
{846}{}{Holodisk}                                       # MaxDisk.int
{847}{}{Refridgerator}                                  # Fridg.int
{848}{}{Bookcase}                                       # HubSafe.int
{849}{}{Raider}                                         # GenRaidA.int
{850}{}{Raider}                                         # GenRaidB.int
{851}{}{Raider}                                         # GenRaidC.int
{852}{}{Merchant}                                       # GenMercA.int
{853}{}{Merchant}                                       # GenMercB.int
{854}{}{Merchant}                                       # GenMercC.int
{855}{}{Guard}                                          # GenGrdA.int
{856}{}{Guard}                                          # GenGrdB.int
{857}{}{Guard}                                          # GenGrdC.int
{858}{}{Brotherhood Paladin}                            # GenPalA.int
{859}{}{Brotherhood Paladin}                            # GenPalB.int
{860}{}{Brotherhood Paladin}                            # GenPalC.int
{861}{}{Caravaner}                                      # CrvnTeam.int
{862}{}{}                                               # CrvnMstr.int
{863}{}{Raider}                                         # CrvnEnmy.int
{864}{}{Wares For Sale}                                 # KillStor.int
{865}{}{Caravan Travelling}                             # CarEnctr.int
{866}{}{Commonly Said Things}                           # GenChat.int
{867}{}{Temporary Place}                                # TEMP
{868}{}{Temporary Place}                                # TEMP
{869}{}{Temporary Place}                                # TEMP
{870}{}{Knight Larry}                                   # LaryKnig.int
{871}{}{Vree's Scribe}                                  # VreScrib.int
{872}{}{Vree's Guard}                                   # vregrd.int
{873}{}{Maxson's Guard}                                 # MaxGrd.int
{874}{}{Jeremiah}                                       # Jerem2.int
{875}{}{Door}                                           # WoodDoor.int
{876}{}{Sturdy Door}                                    # MetlDoor.int
{877}{}{Caravan Travelling}                             # HubEnctr.int
{878}{}{Caravan Merchant}                               # HGenVan2.int
{879}{}{Far Go Traders Merchant}                        # FGTRtnVn.int
{880}{}{Crimson Caravans Merchant}                      # CCRtnVn.int
{881}{}{Water Merchants Trader}                         # WMRtnVn.int
{882}{}{Mitch}                                          # AllNOne.int
{883}{}{Shopkeeper}                                     # Armory.int
{884}{}{Wares For Sale}                                 # AdyStore.int
{885}{}{Diminishing Light}                              # ExitLite.int
{886}{}{Rope}                                           # Rope.int
{887}{}{Jake}                                           # ArmsDeal.int
{888}{}{Ghoul Guard}                                    # GDoor.int
{889}{}{Junktown Jail Cell}                             # JunkJail.int
{890}{}{Ghoul Sentry}                                   # Tread.int
{891}{}{Ghoul Sentry}                                   # Dirtnap.int
{892}{}{Glowing One}                                    # Valtglo.int
{893}{}{Computer}                                       # ValtComp.int
{894}{}{Farmer}                                         # RedFarm.int
{895}{}{Farmer}                                         # GrnFarm.int
{896}{}{Caravan Merchant}                               # HCaravn1.int
{897}{}{Caravan Merchant}                               # HCaravn2.int
{898}{}{Caravan Merchant}                               # HCaravn3.int
{899}{}{Caravan Merchant}                               # HCaravn4.int
{900}{}{Door}                                           # CRedDoor.int
{901}{}{Door}                                           # CBlkDoor.int
{902}{}{Mat}                                            # Mat.int
{903}{}{Luke}                                           # Luke.int
{904}{}{John}                                           # John.int
{905}{}{Door}                                           # JDoor.int
{906}{}{Library}                                        # Library.int
{907}{}{Rented Room}                                    # CrashRm.int
{908}{}{Door}                                           # JakeDoor.int
{909}{}{Desk}                                           # JakeDesk.int
{910}{}{Bookcase}                                       # Bookcase.int
{911}{}{Children of the Cathedral Technician}           # MLOps.int
{912}{}{Viscious}                                       # Viscious.int
{913}{}{Water Rations Storage Box}                      # VaultBox.int
{914}{}{Computer}                                       # MstrComp.int
{915}{}{Door}                                           # Childoor.int
{916}{}{Julio}                                          # HWMHost.int
{917}{}{Caravan Teamster}                               # CarvLead.int
{918}{}{Bookcase}                                       # GenBCase.int
{919}{}{Crack Assault Paladin}                          # BroInvad.int
{920}{}{Follower Scout}                                 # FolInvad.int
{921}{}{Mike}                                           # Mike.int
{922}{}{Vance}                                          # Vance.int
{923}{}{Drug Junkie}                                    # Junkie.int
{924}{}{Debris}                                         # NDebris.int
{925}{}{Debris}                                         # SDebris.int
{926}{}{Debris}                                         # EDebris.int
{927}{}{Debris}                                         # WDebris.int
{928}{}{Power Terminal}                                 # GPwrTerm.int
{929}{}{Footprints}                                     # FootPrnt.int
{930}{}{Water Merchant Guard}                           # WMGuard.int
{931}{}{Sentry Robot}                                   # GSenRob.int
{932}{}{Secure Door}                                    # GloYlDor.int
{933}{}{Merchant}                                       # WMGroup.int
{934}{}{Crimson Caravan Guard}                          # CCGuard.int
{935}{}{Boxing Guard}                                   # BoxGuard.int
{936}{}{Locker}                                         # GunCache.int
{937}{}{Very Solid Door}                                # SDoor.int
{938}{}{Stupid Mutant}                                  # PowerMut.int
{939}{}{Bulletin Board}                                 # bullbord.int
{940}{}{Gunrunners' Suitcase}                           # GunCase.int
{941}{}{Gunther}                                        # Gunther.int
{942}{}{Slappy}                                         # Slappy.int
{943}{}{Shopkeeper}                                     # CathShop
{944}{}{Table}                                          # CathCase.int
{945}{}{Kyle}                                           # Kyle.int
{946}{}{Lemmy}                                          # Lemmy.int
{947}{}{Guard}                                          # Bethgrd.int
{948}{}{Super Mutant Scout}                             # DCMutant.int
{949}{}{Far Go Trader Caravanner}                       # FGTCarvn.int
{950}{}{Super Mutant Patroller}                         # MutAmbsh.int
{951}{}{Lockbox}                                        # DocLokr.int
{952}{}{Refridgerator}                                  # CrashBox.int
{953}{}{Door}                                           # SkumDoor.int
{954}{}{Super Mutant Patroller}                         # SupAmbsh.int
{955}{}{Toxic sludge}                                   # MoatChek.int
{956}{}{Mysterious Stranger}                            # Stranger.int
{957}{}{}                                             # SupGrd.int
{958}{}{Very Secure Door}                               # SupDoor.int
{959}{}{Locker}                                         # VWepLokr.int
{960}{}{Brotherhood Locker}                             # BroLock.int
{961}{}{Vault Data Holodisk}                            # ValtDisk.int
{962}{}{Mrs. Staple}                                    # Staple.int
{963}{}{Alarm Light}                                    # Klaxon.int
{964}{}{Toggle Switch}                                  # Toggle.int
{965}{}{Knight Paul}                                    # Paul.int
{966}{}{Leon}                                           # HtwrLeon.int
{967}{}{Floor}                                          # VPlasTrap.int
{968}{}{Floor}                                          # VExldTrap.int
{969}{}{Floor}                                          # VElecTrap.int
{970}{}{George}                                         # HtwrGrge.int
{971}{}{Rick}                                           # HtwrRick.int
{972}{}{Strongbox}                                      # HtwrBox.int
{973}{}{Door}                                           # KilDoor1.int
{974}{}{Door}                                           # KilDoor2.int
{975}{}{Force Field Emitter}                            # Emiter1a.int
{976}{}{Force Field}                                    # Field1a.int
{977}{}{Cooler}                                         # MorbCool.int
{978}{}{Door}                                           # HtwrDoor.int
{979}{}{Force Field}                                    # Field1a.int
{980}{}{Force Field Emitter}                            # Emiter1a.int
{981}{}{Force Field}                                    # Field1a.int
{982}{}{Force Field Emitter}                            # Emiter1a.int
{983}{}{Force Field}                                    # Field1a.int
{984}{}{Force Field Emitter}                            # Emiter1a.int
{985}{}{Force Field}                                    # Field1a.int
{986}{}{Force Field Emitter}                            # Emiter1a.int
{987}{}{Force Field}                                    # Field1a.int
{988}{}{Force Field Emitter}                            # Emiter1a.int
{989}{}{Floater}                                        # Floater.int
{990}{}{Lenore}                                         # Lenore.int
{991}{}{Bob}                                            # BitsBob.int
{992}{}{Door}                                           # KaneDoor.int
{993}{}{Force Field}                                    # Field1a.int
{994}{}{Force Field Emitter}                            # Emiter1a.int
{995}{}{Force Field}                                    # Field1a.int
{996}{}{Force Field Emitter}                            # Emiter1a.int
{997}{}{Pain Field}                                     # PainFeld.int
{998}{}{Force Field}                                    # Field1a.int
{999}{}{Force Field Emitter}                            # Emiter1a.int
{1000}{}{Force Field}                                   # Field1a.int
{1001}{}{Force Field Emitter}                           # Emiter1a.int
{1002}{}{Force Field}                                   # Field1a.int
{1003}{}{Force Field Emitter}                           # Emiter1a.int
{1004}{}{Elevator Door}                                 # VBrokElv.int
{1005}{}{}                                              # Stuff.int
{1006}{}{Secured Door}                                  # ArmDoor.int
{1007}{}{Regulator Guard}                               # RegGuard.int
{1008}{}{Ghoul}                                         # HotGhoul.int
{1009}{}{Lt.'s Guard}                                   # LtGuard.int
{1010}{}{Computer}                                      # MorpComp.int
{1011}{}{Wall}                                          # SetDoor.int
{1012}{}{Invasion Mutant}                               # Invader.int
{1013}{}{Regulator Guard}                               # PGuard.int
{1014}{}{Deputy Fry}                                    # FryStub.int
{1015}{}{Mutant Guard}                                  # NukeGrd.int
{1016}{}{Master's Soldier}                              # Hord.int
{1017}{}{Dugan}                                         # Dugan.int
{1018}{}{MacRae}                                        # MacRae.int
{1019}{}{Crimson Caravan Guard}                         # CCGuard1.int
{1020}{}{Crimson Caravan Guard}                         # CCGuard2.int
{1021}{}{Mother Deathclaw}                              # MomClaw.int
{1022}{}{Deathclaw}                                     # RoamClaw.int
{1023}{}{Micheal}                                       # BYMike.int
{1024}{}{Christine}                                     # BYChris.int
{1025}{}{Greg}                                          # BYGreg.int
{1026}{}{Blade}                                         # InBlade.int
{1027}{}{Deathclaw Egg}                                 # EggClaw.int
{1028}{}{Radscorpion}                                   # Radscor2.int
{1029}{}{Box}                                           # VanceBox.int
{1030}{}{Box}                                           # BethBox.int
{1031}{}{Force Field Emitter}                           # Emiter1a.int
{1032}{}{Door}                                          # RhomDoor.int
{1033}{}{Locker}                                        # RhomLock.int
{1034}{}{Rat}                                           # WanRat2.int
{1035}{}{Irwin}                                         # Irwin.int
{1036}{}{Power Armor}                                   # Armor.int
{1037}{}{Lockbox}                                       # MitchBox.int
{1038}{}{Raider}                                        # FarmRaid.int
{1039}{}{Mathia}                                        # Mathia.int
{1040}{}{Floor}                                         # JTile.int
{1041}{}{Brahmin}                                       # Stampede.int
{1042}{}{Brotherhood Elder}                             # HighEld.int
{1043}{}{Mole Rat}                                      # MoleRat2.int
{1044}{}{Brotherhood Elder}                             # BroEld.int
{1045}{}{Ghoul}                                         # RanGhoul.int
{1046}{}{Ice Chest}                                     # IceChest.int
{1047}{}{Holodisk}                                      # LtCodes.int
{1048}{}{Force Field}                                   # PrisFeld.int
{1049}{}{Force Field}                                   # PsyField.int
{1050}{}{Kenny}                                         # Kenny.int
{1051}{}{Brotherhood Guard}                             # SuplyGrd.int
{1052}{}{Hub}                                           # HubMis0.int
{1053}{}{Griffith}                                      # GRIFFITH.int
{1054}{}{Locker}                                        # GenLock.int
{1055}{}{Holodisk}                                      # RegDisk.int
{1056}{}{Prisoner}                                      # HubPris.int
{1057}{}{Followers}                                     # LAFollwr.int
{1058}{}{Door}                                          # RaidDoor.int
{1059}{}{Damaged Force Field Emitter}                   # GenEmit.int
{1060}{}{Test}                                          #
{1061}{}{Cheater Item}                                  # Chitem.int
{1062}{}{Caravan Customer}                              # carcust.int
{1063}{}{Boxer}                                         # jboxer.int
{1064}{}{}                                              # stapbox.int
{1065}{}{}                                              # invaded.int    ; msg file for random encounter                                               # local_vars=15
{1066}{}{Brahmin}                                       # carcow.int     ; caravan cow                                                                 # local_vars=15
{1067}{}{}                                              # fke_dude.int   ; NOT USED  fake script for Rad Poison examine mod            		     # local_vars=15
{1068}{}{}                                              # alldogs.int    ; Combined entries from all dog's MSG files [Sduibek, Fallout Fixt]           # local_vars=15
{1069}{}{}                                              # bobstand.int   ; Bob's Iguana Stand (the actual stand itself) [Sduibek, Fallout Fixt]        # local_vars=15
{1070}{}{Hooker}                                        # HHookerD.int   ; "deactive" Hooker (from vanilla) at the Falcon in the Hub                   # local_vars=15
{1071}{}{}                                              # massacre.int   ; dead critters that spawn after Mutant Invasion(s) [Fallout Fixt]            # local_vars=15
{1072}{}{}                                              # redfield.int   ; script allowing the red fields in MB to be destroyed [Fallout Fixt]         # local_vars=15
{1073}{}{}                                              # GrnMtArm.int   ; GREEN MUTANT ARMOR - FEV Jar for Play As Super Mutant [Fallout Fixt]        # local_vars=15
{1074}{}{}                                              # MystStrn.int   ; alt for Mysterious Stranger                                                 # local_vars=15
{1075}{}{}                                              # cheatbox.int   ; cheatbox by Lexx                                                 			 # local_vars=15
{1076}{}{}                                              # niF2Hint.int   ; New Reno Fallout 2 Hintbook                   								# local_vars=1
{1077}{}{}                                              # rndenc.int 	 ; Script to load random encounter / rest location							# local_vars=0
{1078}{}{Motorcycle}                                    # MOTRCYCL.int   ; Drivable motorcycle 														# local_vars=3
{1079}{}{Trunk}                                         # MOTRTRNK.int   ; Motorcycle trunk															# local_vars=3
{1080}{}{}                           				    # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{1081}{}{Door}                           				# AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{1082}{}{Floor Plate}                    				# SprTrp0.int     ; Generic spear Trap (0)
{1083}{}{Floor Plate}                    				# SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{1084}{}{Floor Plate}                    				# SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{1085}{}{Floor Plate}                    				# SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{1086}{}{Floor Plate}                    				# SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{1087}{}{Spear Trap}                     				# ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{1088}{}{Spear Trap}                     				# ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{1089}{}{Spear Trap}                     				# ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{1090}{}{Spear Trap}                     				# ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{1091}{}{Spear Trap}                     				# ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{1092}{}{Spear Trap}                     				# ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{1093}{}{Spear Trap}                     				# ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{1094}{}{Spear Trap}                     				# ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{1095}{}{Spear Trap}                     				# ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{1096}{}{Spear Trap}                     				# ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{1097}{}{Spear Trap}                     				# ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{1098}{}{Spear Trap}                     				# ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{1099}{}{Spear Trap}                    				# ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{1100}{}{Spear Trap}                     				# ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{1101}{}{Spear Trap}                     				# ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{1102}{}{Spear Trap}                     				# ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{1103}{}{}                     				    		# ARCAVES.int     ; Temple map script
{1104}{}{}                     				   			# rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1105}{}{}                     				   			# ecGrdFrv.int    ; Guardian of Forever Rnd Enct spatial script
{1106}{}{Mine}                          				# IIMine.int      ; Mines in Raiders Cave
{1107}{}{Slot Machine}                   				# ziSlots.int     ; Generic Slot Machine
{1108}{}{Craps Dealer}                   				# zcCrpDel.int    ; Craps Dealer
{1109}{}{Casino Girl}                    				# ziDceGrl.int    ; Generic Casino Girl with Dice Game
{1110}{}{Buker}                  						# ENCQUACK.int    ; SD 3 - Encounter, old quack
{1111}{}{Locker}                        				# ziLocker.int    ; Generic Locker Script
{1112}{}{}                              				# ziWeakLk.int    ; Generic Weak Lock Watch Script
{1113}{}{}                              				# ziMedmLk.int    ; Generic Medium Lock Watch Script
{1114}{}{}                              				# ziHardLk.int    ; Generic Hard Lock Watch Script
