#include "..\headers\define.h"

procedure start;
procedure map_enter_p_proc;//    script_action == 15
procedure map_update_p_proc;//    script_action == 23
procedure use_p_proc;//    script_action == 6
procedure pickup_p_proc;//    script_action == 4
procedure use_skill_on_p_proc;//    script_action == 8

variable Free_To_Steal;

import variable Shop_Ptr;
import variable Shopkeeper_Ptr;


procedure start begin
end

procedure map_enter_p_proc
begin
	Shop_Ptr := self_obj;
end

procedure map_update_p_proc
begin
	Shop_Ptr := self_obj;
end

procedure use_p_proc
begin
	if (Shopkeeper_Ptr != 0) then begin
		script_overrides;
		add_timer_event(Shopkeeper_Ptr, 1, 1);
	end
end

procedure pickup_p_proc
begin
	if ((Shopkeeper_Ptr != 0) and (Free_To_Steal == 0)) then begin
		script_overrides;
		add_timer_event(Shopkeeper_Ptr, 1, 1);
	end
end

procedure use_skill_on_p_proc
begin
	if ((action_being_used == SKILL_STEAL) and (Shopkeeper_Ptr != 0)) then begin//-- STEAL
		if (is_success(roll_vs_skill(dude_obj, SKILL_STEAL, -10))) then begin
			Free_To_Steal := 1;
		end
		else begin
			script_overrides;
			add_timer_event(Shopkeeper_Ptr, 1, 2);
		end
	end
end

