#                                    T:\GURPS\CD\DATA\TEXT\GAME\COMBATAI.MSG
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Combat AI messages (ranges defined in data\data\ai.txt)
#

# 1. Guard 1 (Professional)
# Guard 1 should be used for caravan guards, soldiers, and other professional tough guys  who are paid to fight and don't particularly have much of an attitude. It's also very serious in tone.
#
#  running away
#
{1000}{}{}
{1001}{}{}
{1002}{}{Ústup!}
{1003}{}{Ústup!}
{1004}{}{Tohle za chcípnutí nestojí!}
{1005}{}{Tak to mi staèí}
#
# moving in to attack
#
{1006}{}{}
{1007}{}{Právì jsi udìlal obrovskou chybu!}
{1008}{}{Takovı jako ty tady zrovna nemilujeme!}
{1009}{}{Nesnáším takovıhle tıpky}
{1010}{}{}
{1011}{}{}
#
# attacking
#
{1012}{}{}
{1013}{}{}
{1014}{}{A teï chcípneš!}
{1015}{}{}
{1016}{}{}
{1017}{}{Pøiprav se na smrt}
{1018}{}{Teï uka, jakej jsi drsòák...}
{1019}{}{Ksindle}
{1020}{}{Bojuj!}
{1021}{}{}
#
# target being missed
#
{1022}{}{}
{1023}{}{Tohle dìlám od narození, ty grázle!}
{1024}{}{Ty na to nemáš}
{1025}{}{Tohle byla poslední chyba, co jsi udìlal!}
{1026}{}{Amatére!}
{1027}{}{}
#
# target hit in head
#
{1028}{}{Oooh! Ty zkurvy...}
{1029}{}{Tak za tohle tì zabiju}
{1030}{}{}
#
# target hit in left arm
#
{1031}{}{Áuu, moje ruka}
{1032}{}{Sakra, mám v prdeli ruku!}
{1033}{}{Moje rukááá!}
#
# target hit in right arm
#
{1034}{}{Ohhh, moje ruka}
{1035}{}{Kurva, pravá ruka v hajzlu!}
{1036}{}{Moje ruka!}
#
# target hit in torso
#
{1037}{}{Óooh!}
{1038}{}{Uch}
{1039}{}{Uff! Ta sedla!}
{1040}{}{Moje ebra!}
#
# target hit in right leg
#
{1041}{}{Auuu, moje noha}
{1042}{}{Tak za tohle mi zaplatíš!}
{1043}{}{Moje koleno!}
#
# target hit in left leg
#
{1044}{}{Nééé, do nohy néé!}
{1045}{}{Za tohle chcípneš!}
{1046}{}{Moje kolenóó!}
#
# target hit in eyes
#
{1047}{}{Do hajzlu, nevidím!}
{1048}{}{Kurva, moje oko!}
{1049}{}{}
#
# target hit in groin
#
{1050}{}{Oooooo, pøesnì mezi nohy!}
{1051}{}{}
{1052}{}{}
{1053}{}{Ohhh!}
{1054}{}{Áách!}
{1055}{}{Tak tohle bolelo}

# 2. Guard 2 (Gung-ho)
# Guard 2 should be used for really military types or military wannabes. It's a little over the top in places. He's a little bit conceited.
#
#  running away
#
{1100}{}{Posily!}
{1101}{}{}
{1102}{}{Pomóc, doktorááá!}
{1103}{}{Ústup! Ústup!}
{1104}{}{Mizíme! Mizíme!}
{1105}{}{Bitvu jsi moná vyhrál...}
#
# moving in to attack
#
{1106}{}{}
{1107}{}{}
{1108}{}{Já u tì nauèím slušnému chování!}
{1109}{}{Jseš mrtvola!}
{1110}{}{Do boje!}
{1111}{}{Pojïme pohøbít toho sráèe!}
#
# attacking
#
{1112}{}{Uij si tohle!}
{1113}{}{Teï tì dostanu!}
{1114}{}{Je èas chcípnout!}
{1115}{}{Tak jak se ti líbí tohle?}
{1116}{}{}
{1117}{}{Nepouštìj se do nìèeho, co nemùeš dokonèit!}
{1118}{}{Radši se zaèni modlit!}
{1119}{}{}
{1120}{}{}
{1121}{}{Pozdravuj v pekle!}
#
# target being missed
#
{1122}{}{}
{1123}{}{Tohle je to nejlepší co umíš?!}
{1124}{}{Tak dìlej ty posero, bojuj!}
{1125}{}{Pøíštì zkus taky míøit!}
{1126}{}{Civilisto!}
{1127}{}{}
#
# target hit in head (3)
#
{1128}{}{}
{1129}{}{Mùj ksicht!}
{1130}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{1131}{}{Zlomil jsi mi ruku!}
{1132}{}{Jedna zranìná ruka mì nezastaví!}
{1133}{}{}
#
# target hit in right arm
#
{1134}{}{Zlomil jsi mi ruku!}
{1135}{}{Jedna zranìná ruka mì nezastaví!}
{1136}{}{}
#
# target hit in torso
#
{1137}{}{Ufff! Tak tohle ani trochu nebolelo!}
{1138}{}{Uhhh!}
{1139}{}{Tak toho budeš litovat!}
{1140}{}{Oohh! Tak za tohle zaplatíš!}
#
# target hit in right leg
#
{1141}{}{Ohhh, moje noha!}
{1142}{}{Za tohle mi zaplatíš!}
{1143}{}{Takové škrábnutí mì nemùe zastavit!}
#
# target hit in left leg
#
{1144}{}{ouuu, moje noha!}
{1145}{}{Tenhle škrábanec mì nezastaví!}
{1146}{}{Budeš platit!}
#
# target hit in eyes
#
{1147}{}{Jsem slepı!}
{1148}{}{Strašnì mì pálí oèi!!!}
{1149}{}{Nevidím!}
#
# target hit in groin
#
{1150}{}{Oooh, mùj rozkrok!}
{1151}{}{Ach!}
{1152}{}{Uuuf!}
{1153}{}{Nemùu...dı..dıch..dıchat...}
{1154}{}{Nemùu...dıch..dıchat...}
{1155}{}{Ty sráèi...}

# 3. Guard 3 (Sadistic)
# Guard 3 is the henchman of really nasty people. He likes to hurt people, and makes no bones about it and is a bit of a coward.
#
#  running away
{1200}{}{Musím odtud vypadnout!}
{1201}{}{Já se vrátím...}
{1202}{}{Dneska mì nedostaneš!}
{1203}{}{Pøíštì, zrùdo!}
{1204}{}{To jsi ještì nevidìl všechno!}
{1205}{}{Za tohle zaplatíš -- pozdìji!}
#
# moving in to attack
#
{1206}{}{Jseš mrtvola!}
{1207}{}{Èerstvı masíèko...}
{1208}{}{Zatancuju si na tvım hrobì!}
{1209}{}{Všichni sem! Cvièení støelby na cíl!}
{1210}{}{}
{1211}{}{Tak tohle si uiju!}
#
# attacking (10)
#
{1212}{}{}
{1213}{}{Neunavuj se prosit o milost!}
{1214}{}{Tak tohle je ta nejlepší èást...}
{1215}{}{}
{1216}{}{Nadìlám z tebe rádlo pro psy!}
{1217}{}{Nemìl by sis zahrávat s ohnìm!}
{1218}{}{Doufám, e nechcípneš moc rychle!}
{1219}{}{Odejde jen jeden z nás}
{1220}{}{Chcípni!}
{1221}{}{Chcípáky jako ty si dávám k snídani}
{1222}{}{Nakrmím tebou svıho ochoèenıho leguána!}
{1223}{}{Poslední vìc, co uvidíš, bude mùj šklebící se ksicht}
{1224}{}{Tohle je moje oblíbená prácièka}
#
# target being missed (6)
#
{1225}{}{Byl bys dobrej klaun!}
{1226}{}{Tohle je to nejlepší, co umíš?!}
{1227}{}{}
{1228}{}{}
{1229}{}{Strašnì pomalej!}
{1230}{}{Nımande!}
#
# target hit in head (3)
#
{1231}{}{Ne do ksichtu!}
{1232}{}{Ouu!}
{1233}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{1234}{}{Ohh, moje ruka!}
{1235}{}{Zlomil jsi mi ruku!}
{1236}{}{Zranìná ruka mì nezastaví!}
#
# target hit in right arm
#
{1237}{}{Ouu, moje ruka!}
{1238}{}{Zlomil jsi mi ruku!}
{1239}{}{Zranìná ruka mì nezastaví!}
#
# target hit in torso
#
{1240}{}{Ouu, moje ebra!}
{1241}{}{Tenhle zásah byl zdarma}
{1242}{}{Myslím, e za tohle mi zaplatíš}
#
# target hit in right leg
#
{1243}{}{Moje noha!}
{1244}{}{Za tohle mi zaplatíš!}
{1245}{}{Auuu!}
#
# target hit in left leg
#
{1246}{}{Moje noha!}
{1247}{}{}
{1248}{}{Ouuuvajs!}
#
# target hit in eyes
#
{1249}{}{Ouuh! Moje oèi!}
{1250}{}{Moje oko! Tak tohle mi draze zaplatíš!}
{1251}{}{}
#
# target hit in groin
#
{1252}{}{Oooohh, mùj rozkrok!}
{1253}{}{Ouu! Tak tohle se musím nauèit...}
{1254}{}{Uff!}
{1255}{}{Uch!}
{1256}{}{Uhhh!}
{1257}{}{Ouu! Za tohle tì zabiju!}

# 4. Guard 4 (Humorous)
# Guard 4 is used when the designer wants to be silly with guards
#
#  running away (6)
#
{1300}{}{Neslyšel jsi nìkoho volat moje jméno?}
{1301}{}{}
{1302}{}{Pomóóc!!}
{1303}{}{Aaaaahhhh!}
{1304}{}{Zdrhejte!}
{1305}{}{}
#
# moving in to attack (6)
#
{1306}{}{Udìlám z tebe rozlámanej preclík}
{1307}{}{Koukni! Rozvázala se ti bota!}
{1308}{}{Poèkej a tì dostanu...}
{1309}{}{}
{1310}{}{Já ti dám takovou nakládaèku}
{1311}{}{}
#
# attacking (10)
#
{1312}{}{Teï dostaneš!}
{1313}{}{A mám tì!}
{1314}{}{A mám tì!}
{1315}{}{Jak se ti to líbí?}
{1316}{}{A co tohle?!}
{1317}{}{Tohle bude záitek, kterej ti trochu zmìní ivot}
{1318}{}{Tohohle asi nebudu litovat, có?}
{1319}{}{}
{1320}{}{}
{1321}{}{}
#
# target being missed (6)
#
{1322}{}{Ha ha, vedle!}
{1323}{}{Ne, ne, ne!}
{1324}{}{He he!}
{1325}{}{Ne, kdepak!}
{1326}{}{Jaká ubohost!}
{1327}{}{Mì se na kobylku nedostaneš}
#
# target hit in head (3)
#
{1328}{}{Pozor na vlasy!!!}
{1329}{}{Moje fuby! Pfifel fem o fuby!}
{1330}{}{Moje fuby! Moje fuby!}
#
# target hit in left arm
#
{1331}{}{Ouu, moje ruka}
{1332}{}{Ohh!}
{1333}{}{Ohh, nech toho!}
#
# target hit in right arm
#
{1334}{}{Ouu, moje ruka}
{1335}{}{Ohhh!}
{1336}{}{Ohh, okamitì s tím pøestaò!}
{1337}{}{Já nechci bıt levák!}
#
# target hit in torso
#
{1338}{}{Ouuu!}
{1339}{}{Tak tohle nebylo moc pìknı}
{1340}{}{Mohl bys mì aspoò litovat, aspoò já bych asi...}
{1341}{}{Myslím, e omdlím!}
{1342}{}{Copak jsem boxovací pytel?!}
{1343}{}{Ty teda nejsi zrovna lidumil!}
#
# target hit in right leg
#
{1344}{}{Ohh, moje noha}
{1345}{}{Ohh! Tak tohle mi nedìlej!}
{1346}{}{!}
#
# target hit in left leg
#
{1347}{}{Ohh, moje noha}
{1348}{}{Ouu! Ty jseš teda podlá svinì!}
{1349}{}{}
#
# target hit in eyes
#
{1350}{}{Co je to najednou za tmu?}
{1351}{}{Kde jsou všichni?}
{1352}{}{Ouuh, moje sítnice!}
#
# target hit in groin
#
{1353}{}{Oooohh, mùj rozkrok!}
{1354}{}{Mùj rozkrok pálí jak oheò!}
{1355}{}{Mùj rozkrok pálí jak oheò!}
{1356}{}{Nemù..u..dıch..dıchat...}
{1357}{}{}
{1358}{}{Ta bolest, ta bolest...}

# 5. Guard 5 (Perfunctory)
# Guard 5 is a guard who doesn't say much, or when he does, it's pretty short.
#
#  running away (6)
#
{1400}{}{Pryè odsud!!!}
{1401}{}{Nashle!}
{1402}{}{Aaaaahhhh!}
{1403}{}{}
{1404}{}{}
{1405}{}{Nashle pozdìji}
#
# moving in to attack
#
{1406}{}{}
{1407}{}{Jseš minulost!}
{1408}{}{Konec koèkování}
{1409}{}{Tady nìkdo chcípne!}
{1410}{}{Puste mì na nì!!!}
{1411}{}{}
#
# attacking
#
{1412}{}{Co bys rek tomuhle!}
{1413}{}{Zhebni!}
{1414}{}{Nulo}
{1415}{}{Zjeve}
{1416}{}{}
{1417}{}{Doufám, e tohle bolí}
{1418}{}{}
{1419}{}{}
{1420}{}{Pohrbím tì...}
{1421}{}{Jseš mrtvej}
#
# target being missed
#
{1422}{}{Vedle!}
{1423}{}{Tak tohle na mì dojem neudìlalo}
{1424}{}{}
{1425}{}{Jseš pomalej}
{1426}{}{Jseš nula}
{1427}{}{}
#
# target hit in head
#
{1428}{}{Tak tohle bolelo}
{1429}{}{Moje oèi!}
{1430}{}{Ouu! Mùj nos...}
#
# target hit in left arm
#
{1431}{}{Och!}
{1432}{}{Och! Moje ruka!}
{1433}{}{Ouu! Tys mi ji zlomil!}
#
# target hit in right arm
#
{1434}{}{Ách!}
{1435}{}{Ouu! Moje ruka!}
{1436}{}{Aouu! Moje ruka!}
#
# target hit in torso
#
{1437}{}{Ohh!}
{1438}{}{ouuc!}
{1439}{}{Uff!}
{1440}{}{Glp!}
{1441}{}{Ufff!}
{1442}{}{Ahh!}
#
# target hit in right leg
#
{1443}{}{Ouu!}
{1444}{}{Ouu! Moje koleno!}
{1445}{}{Ohh! Moje noha!}
#
#
# target hit in left leg
#
{1446}{}{Ouu!}
{1447}{}{Ouu! Moje koleno!}
{1448}{}{Ohh! Moje noha!}
#
# target hit in eyes
#
{1449}{}{Jsem slepı!}
{1450}{}{Nic nevidím!}
{1451}{}{Moje oko!}
#
# target hit in groin
#
{1452}{}{Mùj rozkrok!}
{1453}{}{Ouuuu!}
{1454}{}{Zatracenì, to bolí}
{1455}{}{Uuuf!}
{1456}{}{Uhh!}
{1457}{}{Nemùu..dıch..dıchat...}

# 6. Guard 6 (Smart-ass)
# Guard 6 is a guard who says a lot of wisecracks. Somewhat conceited.
#
#  running away (6)
#
{1500}{}{Mizím!}
{1501}{}{Padám!}
{1502}{}{}
{1503}{}{Moná to nebyl nejlepší nápad}
{1504}{}{Èlovìk by tam mohl pøijít k úrazu!}
{1505}{}{}
#
# moving in to attack (6)
#
{1506}{}{Èas na novı záøezy do paby}
{1507}{}{Práce není nikdy hotová}
{1508}{}{}
{1509}{}{U zase. A munice je tak drahá!}
{1510}{}{Nemìli mi dávat tuhle zpopelòovací slubu}
{1511}{}{Kdo si myslíš, e jsi?}
#
# attacking
#
{1512}{}{Sledujte profíka pøi práci}
{1513}{}{Dneska ráno jsi radši nemìl vstávat}
{1514}{}{Naereš se hlíny!}
{1515}{}{}
{1516}{}{Teï tì pošlu pod kytky...}
{1517}{}{}
{1518}{}{Pøeijí jen ti nejsilnìjší, ty jsi mimo}
{1519}{}{}
{1520}{}{Dìlej mrtvıho!}
{1521}{}{Budu to poslední, co uvidíš!}
#
# target being missed
#
{1522}{}{Netrefíš mì tak snadno}
{1523}{}{Aauuu. Minul jsi mì?}
{1524}{}{Zkoušej to dál a jednou se trefíš!}
{1525}{}{}
{1526}{}{Chceš, abych se nehıbal?}
{1527}{}{}
#
# target hit in head
#
{1528}{}{Aauuu}
{1529}{}{Zvoní mi v hlavì!}
{1530}{}{Aauuu. Moje ucho!}
#
# target hit in left arm
#
{1531}{}{Ou, moje ruka}
{1532}{}{Zlomil jsi mi ruku!}
{1533}{}{Ou... jak odzbrojující...}
#
# target hit in right arm
#
{1534}{}{Auu, moje ruka}
{1535}{}{Zlomil jsi mi ruku!}
{1536}{}{Ou... ty dokáeš èlovìka odzbrojit...}
#
# target hit in torso
#
{1537}{}{Ty si asi myslíš, e jsi fakt dobrej, co...}
{1538}{}{Ugh!}
{1539}{}{Uff!}
{1540}{}{Chceš si to zkusit znovu?}
{1541}{}{A vyrosteš, urèitì budeš chtít bejt tak dobrej jako já}
{1542}{}{To aspoò nebylo tak hnusnı jako tvùj ksicht!}
{1543}{}{Aauuu. Sakra!}
#
# target hit in right leg
#
{1544}{}{Aauuu}
{1545}{}{Jenom škrábnutí...a pár zlomenejch kostí}
{1546}{}{To koleno jsem stejnì nepotøeboval}
#
# target hit in left leg
#
{1547}{}{Ack!}
{1548}{}{Jenom škrábnutí...a pár zlomenejch kostí}
{1549}{}{To koleno jsem stejnì nepotøeboval}
#
# target hit in eyes
#
{1550}{}{Nevidím!}
{1551}{}{Aspoò se u nemusím koukat na ten tvùj hnusnej ksicht}
{1552}{}{Aspoò se u nemusím koukat na ten tvùj hnusnej ksicht}
#
# target hit in groin
#
{1553}{}{Moje koule!}
{1554}{}{To zaèíná bejt osobní}
{1555}{}{}
{1556}{}{A všechen sex je v prdeli!}
{1557}{}{Oh, to je bolest!}
{1558}{}{Aauuu. Tak tomuhle øíkám bolest!}

# 7. Guard 7 (Rookie)
# "I can hit a target real good when it ain't moving. I'm sure looking forward to some real action. Honest I am!" (Naive, and probably won't live long enough to learn)
#
#  running away
#
{1600}{}{Hej, tady bych taky moh zhebnout!}
{1601}{}{Tohle moná nebyl nejlepší nápad}
{1602}{}{Konèím!}
{1603}{}{Pomoc!}
{1604}{}{Áaaaa!}
{1605}{}{Musím odsud!}
#
# moving in to attack
#
{1606}{}{Koneènì se nìco poøádnıho dìje!}
{1607}{}{Se mnou by sis nemìl zahrávat!}
{1608}{}{Koneènì se mùu pøedvést v akci!}
{1609}{}{Tak a je to tady, co..?}
{1610}{}{}
{1611}{}{Tohle by mohla bejt sranda!}
#
# attacking
#
{1612}{}{Co tohle!}
{1613}{}{A mám tì!}
{1614}{}{A co tohle!}
{1615}{}{Jak se ti to líbí?}
{1616}{}{Chcípni, ty stvùro!}
{1617}{}{Ty zmutovaná mrcho!}
{1618}{}{Tak pojï!}
{1619}{}{}
{1620}{}{}
{1621}{}{}
#
# target being missed
#
{1622}{}{Cha, minul jsi mì!}
{1623}{}{Minuls!}
{1624}{}{Tak ty takhle?}
{1625}{}{Je tohle všechno co dokáeš?}
{1626}{}{Hej! Tohle mohlo bolet!}
{1627}{}{}
#
# target hit in head
#
{1628}{}{Aauuu}
{1629}{}{Mùj ksicht! Cos to udìlal!}
{1630}{}{Áááaamm! Mùj ksicht! Ne! To ne!}
#
# target hit in left arm
#
{1631}{}{Ou, moje ruka}
{1632}{}{Moje ruka, cos to s ní provedl?}
{1633}{}{Áaaaaa!}
#
# target hit in right arm
#
{1634}{}{Ou, moje ruka}
{1635}{}{Moje ruka, cos to s ní provedl?}
{1636}{}{Áaaaaa!}
#
# target hit in torso
#
{1637}{}{Auuu}
{1638}{}{}
{1639}{}{Ouííí! ouíí! ouu!}
{1640}{}{Tak tohle se mi teda nelíbí...}
{1641}{}{Hele, na mì pomalu, jsem teprve zaèáteèník}
{1642}{}{Uffff!}
{1643}{}{Ack!}
{1644}{}{Aau! To bolelo!}
#
# target hit in right leg
#
{1645}{}{Sakra, moje noha}
{1646}{}{Moje noha, cos to s ní provedl?}
{1647}{}{Áaaaaa!}
#
# target hit in left leg
#
{1648}{}{Sakra, moje noha}
{1649}{}{Moje noha!}
{1650}{}{Áaaaaa!}
#
# target hit in eyes
#
{1651}{}{Nevidím!}
{1652}{}{Moje oèi!}
{1653}{}{Pomozte mi nìkdo!}
#
# target hit in groin
#
{1654}{}{Aauuu. Moje tøíslo!}
{1655}{}{Úúúúúú, ty malej zasranej...}
{1656}{}{Urp!}
{1657}{}{Jsou tohle moje vnitønosti?}
{1658}{}{...nemùu...dejchat...}
{1659}{}{Ksakru, to bolelo!}

# 8. Bouncer
# Bouncer is a professional. Fighting scum is his business. The opponent is another loser who's caused too much trouble.
#
#  running away
#
{1700}{}{Kvùli tomuhle chcípnout nechci!}
{1701}{}{To mi za to nestojí!}
{1702}{}{Mìl bych se zdejchnout!}
{1703}{}{Moje povìst je v háji...}
{1704}{}{S tebou nemám problém}
{1705}{}{Pryè od tohohle šílence}
#
# moving in to attack
#
{1706}{}{Snad ne další sráè!}
{1707}{}{Tos pøehnal!}
{1708}{}{Tohle ti jen tak neprojde!}
{1709}{}{Pozdì!!}
{1710}{}{Rozmáèknu tì jako klíštì!}
{1711}{}{}
#
# attacking
#
{1712}{}{Tak takhle já nakládám s takovejma, co se mi vpletou do cesty}
{1713}{}{Zhasnìte svìtla...}
{1714}{}{Poèkej, tohle tì nauèí}
{1715}{}{Tak pojï, teï si to rozdáme!}
{1716}{}{}
{1717}{}{Tak schválnì co vydríš...}
{1718}{}{..si myslíš, e seš òákej frajer, co..?}
{1719}{}{Nemìl bys zaèínat nìco, co nemùeš dokonèit}
{1720}{}{Ty sis myslel, e ti tohle projde?}
{1721}{}{Takovı jako ty si dávám k snídani}
#
# target being missed
#
{1722}{}{Dìláš mi to lehèí...}
{1723}{}{Nic moc, kámo}
{1724}{}{V tobì snad není ani jeden sval!}
{1725}{}{Je tohle všechno, co dokáeš?}
{1726}{}{Snad sis nemyslel, e mì dostaneš..?}
{1727}{}{Tomuhle øíkáš boj, ty buzno!}
#
# target hit in head
#
{1728}{}{Zlomil jsi mi nos!}
{1729}{}{Aauuu. K èertu s tebou!}
{1730}{}{Sakra! To bolelo!}
#
# target hit in left arm
#
{1731}{}{Ou, moje ruka}
{1732}{}{Tak za tohle budeš trpìt!}
{1733}{}{Tohle byla chyba}
#
# target hit in right arm
#
{1734}{}{Ou, moje ruka}
{1735}{}{Tak za tohle budeš trpìt!}
{1736}{}{Tohle byla chyba}
#
# target hit in torso
#
# <no messages here>
#
# target hit in right leg
#
{1737}{}{Zase zkurvená noha!}
{1738}{}{Aauuu}
{1739}{}{Tohle byla chyba}
#
# target hit in left leg
#
{1740}{}{Aauuu. Snaíš se mì sejmout?}
{1741}{}{Aauuu}
{1742}{}{To bolelo...}
#
# target hit in eyes
#
{1743}{}{Nevidím!}
{1744}{}{Aouuu!}
{1745}{}{K tomu, abych ti zakroutil krkem, oèi nepotøebuju!}
#
# target hit in groin
#
{1746}{}{Oooo! Do koulí!}
{1747}{}{Oooo! Do koulí!}
{1748}{}{Oooo! Do koulí!}
{1749}{}{Auva! Moje chlouba!}
{1750}{}{Auva! Moje klenoty!}
{1751}{}{Urp!}

# 9. Loser
# Loser don't want no trouble. How's he survived so long?
#
#  running away
#
{1800}{}{Slitování!}
{1801}{}{Pomozte mi nìkdo!}
{1802}{}{Prosím neee!}
{1803}{}{Pomoc!}
{1804}{}{Aaaaa!}
{1805}{}{Slitování!}
#
# moving in to attack
#
{1806}{}{Hmm, uh, pøestaò!}
{1807}{}{Takovı jako ty nemám rád...}
{1808}{}{Fakt jsem nechtìl, aby to dopadlo takhle...}
{1809}{}{Asi bych se mìl bránit}
{1810}{}{Asi bych se mìl bránit}
{1811}{}{Doufal jsem, e k tomuhle nedojde...}
#
# attacking
#
{1812}{}{Co tohle!}
{1813}{}{Nemìl sis zaèínat!}
{1814}{}{Sám sis o to øek!}
{1815}{}{A co tohle?}
{1816}{}{}
{1817}{}{Ty svinì!}
{1818}{}{Tohle jsem nechtìl!}
{1819}{}{}
{1820}{}{Já jsem se prát nechtìl, ale...}
{1821}{}{Ty sketo!}
#
# target being missed
#
{1822}{}{}
{1823}{}{Netrefil ses!}
{1824}{}{Jo, tak tohle mohlo bolet!}
{1825}{}{Páni! Furt iju!}
{1826}{}{Hej! Tohle mohlo bolet!}
{1827}{}{Páni! Ještì furt iju!}
#
# target hit in head
#
{1828}{}{Mùj ksicht! Mùj ksicht!}
{1829}{}{Aauuu. To bolelo!}
{1830}{}{}
#
# target hit in left arm
#
{1831}{}{Ou, moje ruka}
{1832}{}{Aauuu}
{1833}{}{Zlomil jsi mi ruku!}
#
# target hit in right arm
#
{1834}{}{Ou, moje ruka}
{1835}{}{Úúúúúh!}
{1836}{}{Mùj Boe! Moje ruka!}
#
# target hit in torso
#
{1837}{}{Aauuu. Tohle fakt bolelo!}
{1838}{}{Asi omdlím}
{1839}{}{Ouuíí!}
{1840}{}{}
{1841}{}{To bolelo!}
{1842}{}{Nech mì bejt!}
{1843}{}{Oooou, to je bolest!}
#
# target hit in right leg
#
{1844}{}{Sakra, moje noha}
{1845}{}{Moje koleno!}
{1846}{}{Aauuu}
#
# target hit in left leg
#
{1847}{}{Sakra, moje noha}
{1848}{}{Moje koleno!}
{1849}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{1850}{}{Pane Boe, nevidím, aauuu!}
{1851}{}{Mùj ksicht! Moje oèi! Arrrrgh!}
{1852}{}{Moje oèi!}
#
# target hit in groin
#
{1853}{}{Ooooooooo, moje koule! Ooooooo...}
{1854}{}{Ouuuuu...To bolí!}
{1855}{}{Urp!}
{1856}{}{Ooorp! aooouw...}
{1857}{}{...nemùu...dejchat...}
{1858}{}{Kriste, to je bolest..}

# 10. Berserker
# Berserker just want trouble. How's he survived so long?
#
#  running away
#
{1900}{}{Beru si náhradní volno}
{1901}{}{Budu hned zpátky!}
{1902}{}{Mìj se, pankáèi!}
{1903}{}{Tohle byla prdel, ale já u konèím!}
{1904}{}{Za tohle mi zaplatíš - nìkdy jindy!}
{1905}{}{Tohle si musíme ještì nìkdy zopakovat!}
#
# moving in to attack
#
{1906}{}{Teï uvidíš, zaè je toho loket!}
{1907}{}{Èerstvı maso!}
{1908}{}{Ty prostì víš, jak mi udìlat radost!}
{1909}{}{Tak, a teï si s tebou pohraju!}
{1910}{}{Teï ti ukáu co proto!}
{1911}{}{Udìlám z tebe praseèí paštiku!}
#
# attacking
#
{1912}{}{}
{1913}{}{}
{1914}{}{Proboha nepros! Smrt by mìla bıt dùstojná.}
{1915}{}{Doufám, e nezaøveš hned!}
{1916}{}{Nìjakı poslední pøání?}
{1917}{}{Co tohle!}
{1918}{}{Chcípni! Chcípni! Chcípni!}
{1919}{}{Chcípni!}
{1920}{}{Tak se na tebe podíváme...zevnitø}
{1921}{}{Bude z tebe psí rádlo, kámo.}
#
# target being missed
#
{1922}{}{Ani náhodou!}
{1923}{}{}
{1924}{}{No ták, pankáèi, sna se trochu}
{1925}{}{Tohle je všechno, co umíš?}
{1926}{}{Tohle bude jednodušší, ne jsem èekal}
{1927}{}{Tohle bude jednodušší, ne jsem èekal}
#
# target hit in head
#
{1928}{}{Z toho bude dobrá jizva!}
{1929}{}{Tohle mì zaèíná srát}
{1930}{}{Zkus si to ještì, ty prase}
#
# target hit in left arm
#
{1931}{}{Zchromils mì!}
{1932}{}{}
{1933}{}{Zlomil jsi mi ruku, ale já ti zlomím vaz}
#
# target hit in right arm
#
{1934}{}{}
{1935}{}{To je jenom škrábnutí...}
{1936}{}{Zlomil jsi mi ruku, take já ti teï pøerazím vaz}
#
# target hit in torso
#
{1937}{}{}
{1938}{}{Úuuuf! Za tohle budeš trpìt...}
{1939}{}{Uuuuf!}
{1940}{}{Uuuuf!}
{1941}{}{Miluju zvuk lámanejch eber!}
{1942}{}{}
{1943}{}{Arg!}
#
# target hit in right leg
#
{1944}{}{Miluju zvuk lámanejch kostí}
{1945}{}{}
{1946}{}{Zlomil jsi mi nohu, ale já ti teï zlomím vaz}
#
# target hit in left leg
#
{1947}{}{Miluju zvuk lámanejch kostí}
{1948}{}{}
{1949}{}{Zlomil jsi mi nohu, ale já ti teï za to zlomím vaz}
#
# target hit in eyes
#
{1950}{}{Hej, já nevidím}
{1951}{}{Já nevidím. No, aspoò to teï bude fér.}
{1952}{}{Moje oèi, ty kurvo!}
#
# target hit in groin
#
{1953}{}{Aouuu, moje koule!}
{1954}{}{To byl ale podlej zásah}
{1955}{}{}
{1956}{}{}
{1957}{}{Take takhle ty chceš hrát...?}
{1958}{}{Ack!}

# 11. Peasant
# I work the land. Is this is what I get for years of hard work? Some well-armed troublemaker who's making my life miserable?
#
#  running away
#
{2000}{}{Vybij si zlost na nìkom jinım, prosím!}
{2001}{}{Mìj slitování!}
{2002}{}{Pomozte mi nìkdo!}
{2003}{}{Nech toho, prosím!}
{2004}{}{}
{2005}{}{Pro tohle chcípnout nechci!}
#
# moving in to attack
#
{2006}{}{Jen poèkej, a tì dostanu...}
{2007}{}{}
{2008}{}{Hej, ty!}
{2009}{}{Tebe tady nevidím rád}
{2010}{}{Tady jsem pánem já a nikdo jinej...}
{2011}{}{Kdo si myslíš, e jsi?}
#
# attacking
#
{2012}{}{}
{2013}{}{}
{2014}{}{Tak a tohle my dìláme s havìtí, jako jsi ty!}
{2015}{}{Ty zmutovaná zrùdo!}
{2016}{}{}
{2017}{}{Hodím tì psùm}
{2018}{}{Já tì nauèím!}
{2019}{}{Dobrá. Chtìls to sám.}
{2020}{}{Ty zvíøe!}
{2021}{}{}
#
# target being missed
#
{2022}{}{}
{2023}{}{Vidìl jsem chytøejší brahmíny ne ty}
{2024}{}{Jóóó!}
{2025}{}{Na mì si jen tak nepøijdeš}
{2026}{}{Díky bohu}
{2027}{}{Minuls!}
#
# target hit in head
#
{2028}{}{Ksakru to bolí!}
{2029}{}{Áaaachchch!}
{2030}{}{Ooo!}
#
# target hit in left arm
#
{2031}{}{Áaaaaou! moje ruka}
{2032}{}{Moje ruka!}
{2033}{}{Aauuu}
#
# target hit in right arm
#
{2034}{}{Áaaaou! moje ruka}
{2035}{}{Moje ruka!}
{2036}{}{Aauuu}
#
# target hit in torso
#
{2037}{}{Aauuu}
{2038}{}{To pìknì zabolelo...}
{2039}{}{Áaaa!}
{2040}{}{Aauuu}
{2041}{}{}
{2042}{}{Ufff!}
{2043}{}{Aauuu}
#
# target hit in right leg
#
{2044}{}{Aaaaaa! Moje noha}
{2045}{}{Moje noha!}
{2046}{}{Moje noha!}
#
# target hit in left leg
#
{2047}{}{Aaaaaa! Moje noha}
{2048}{}{Moje noha!}
{2049}{}{Aauuu}
#
# target hit in eyes
#
{2050}{}{Aaaaaa! Nevidím!}
{2051}{}{K èertu s tebou!}
{2052}{}{Moje oko!}
#
# target hit in groin
#
{2053}{}{Ouu}
{2054}{}{Oooooooooo!}
{2055}{}{...nemùu...dejchat...}
{2056}{}{}
{2057}{}{Kurva, to je bolest...}
{2058}{}{Sakra!}

# 12. Careful
# I don't want to fight. Just let me walk away.
#
#  running away
#
{2100}{}{Jako bych tu ani nikdy nebyl!}
{2101}{}{Slitování, slitování!}
{2102}{}{U dost, prosím!}
{2103}{}{Pomoc!}
{2104}{}{}
{2105}{}{Do toho se míchat nebudu}
#
# moving in to attack
#
{2106}{}{}
{2107}{}{}
{2108}{}{Fakt to dìlám nerad}
{2109}{}{Budu tì muset rozmáznout}
{2110}{}{Opravdu to dìlám nerad}
{2111}{}{Hlavnì, a se mi nic nestane}
#
# attacking
#
{2112}{}{}
{2113}{}{Øekl sis o to sám!}
{2114}{}{Nemám zrovna náladu se prát, no ale...}
{2115}{}{}
{2116}{}{Proè si zaèínáš?}
{2117}{}{Je mi líto, ale..!}
{2118}{}{Neber si to osobnì...}
{2119}{}{Snad ti moc neublíím}
{2120}{}{Je ti jasnı, e tohle sis zaèal ty}
{2121}{}{}
#
# target being missed
#
{2122}{}{Jóóó!}
{2123}{}{Tos opravdu nemusel}
{2124}{}{Hej! Tohle mohlo bolet!}
{2125}{}{Snad bysme se nemìli prát}
{2126}{}{Násilí ten skuteènı problém nevyøeší}
{2127}{}{Ty se vùbec nesoustøedíš}
#
# target hit in head
#
{2128}{}{Proboha, proè do ksichtu!}
{2129}{}{Aaa, moje hlava!}
{2130}{}{Aauuu. Moje ucho!}
#
# target hit in left arm
#
{2131}{}{Ou, moje ruka}
{2132}{}{Ouu!}
{2133}{}{Zlomil jsi mi ruku!}
#
# target hit in right arm
#
{2134}{}{Ou, moje ruka}
{2135}{}{Uff!}
{2136}{}{Zlomil jsi mi ruku!}
#
# target hit in torso
#
# <no messages here>
#
# target hit in right leg
#
{2137}{}{Sakra, moje noha}
{2138}{}{Moje koleno!}
{2139}{}{Aauuu. Noha v hajzlu!}
#
# target hit in left leg
#
{2140}{}{Sakra, moje noha}
{2141}{}{Moje koleno!}
{2142}{}{Aauuu. Noha v hajzlu!}
#
# target hit in eyes
#
{2143}{}{Nevidím!}
{2144}{}{Breèím krev!}
{2145}{}{To bolelo...}
#
# target hit in groin
#
{2146}{}{Oooooo, moje koule!}
{2147}{}{}
{2148}{}{}
{2149}{}{...nemùu...dejchat...}
{2150}{}{Moje poklady!}
{2151}{}{Oooo! Musím si lehnout...}

# 13.  Super Mutant
# We are Chosen! You are dead!
#
#  running away
#
{2200}{}{Bì!}
{2201}{}{Mì nedostaneš!}
{2202}{}{Ještì se vrátím!}
{2203}{}{Kámoši tì dostanou za mì!}
{2204}{}{Za tohle mi zaplatíš -- nìkdy jindy!}
{2205}{}{My jsme Vyvolení! Ty døív nebo pozdìji chcípneš!}
#
# moving in to attack
#
{2206}{}{Pøichází tvoje smrt!}
{2207}{}{Tvùj èas se naplnil!}
{2208}{}{Mnì lidské zbranì neublíí!}
{2209}{}{Budeš trpìt, velice trpìt!}
{2210}{}{Já drtím lebky holejma rukama!}
{2211}{}{Budoucnost jsme MY a vám se jen smìjem!}
#
# attacking
#
{2212}{}{Tohle je tvùj konec!}
{2213}{}{Teï u ti nikdo nepomùe!}
{2214}{}{Teï chcípneš!}
{2215}{}{Teï chcípneš nechutnou smrtí!}
{2216}{}{Do pekla se dostaneš ještì dnes!}
{2217}{}{Já se pøi zabíjení chechtám}
{2218}{}{Tvá krev budi moje víno!}
{2219}{}{Teï chcípneš!}
{2220}{}{Tohle je tvá smrt!}
{2221}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{2222}{}{Proè se bráníš?}
{2223}{}{Je tohle všechno, co lidi dokáou?!}
{2224}{}{Nemáš ádnou sílu!}
{2225}{}{Jseš mi k smíchu!}
{2226}{}{Co bylo tohle, útok?}
{2227}{}{Jseš úplnı hovno!}
#
# target hit in head
#
{2228}{}{Aaaaaa! Mùj ksicht!}
{2229}{}{Mùj ksicht! Tohle si odpykáš!}
{2230}{}{Aaaaaaa! Roztrhám tì na kusy!}
#
# target hit in left arm
#
{2231}{}{Aaaaaou!}
{2232}{}{Tomuhle øíkáš bolest? Dovol, abych se zasmál!}
{2233}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in right arm
#
{2234}{}{Áaaaaou!}
{2235}{}{Tomuhle ty øíkáš bolest? Dovol, abych se zasmál!}
{2236}{}{Áaaaaou! Za tohle ti zlomím vaz!}
#
# target hit in torso
#
{2237}{}{Áaaa!}
{2238}{}{Grrrr!}
{2239}{}{To byla chyba - tvoje!}
{2240}{}{Áaaa!}
{2241}{}{Grrrr!}
{2242}{}{Hahahaha! A tomuhle øíkáš bolest!}
{2243}{}{Arrr!}
#
# target hit in right leg
#
{2244}{}{Áaaaaou! Moje noha!}
{2245}{}{Tomuhle øíkáš bolest? Dovol, abych se zasmál!}
{2246}{}{Áaaaaou! Rozdrtím tì jako vìtvièku!}
#
# target hit in left leg
#
{2247}{}{Áaaaaou! Moje noha!}
{2248}{}{Tomuhle øíkáš bolest? To je k smíchu!}
{2249}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{2250}{}{Áaaaaou! Proklatı lidi. Jsem snad slepej!}
{2251}{}{Áaaaaou! To je bolest! Cos to proved?!}
{2252}{}{Áaaaaou! Za to tì budu muèit pekelnì dlouho!}
#
# target hit in groin
#
{2253}{}{To je jenom lidská slabost!}
{2254}{}{Tohle mi neublíí!}
{2255}{}{Vy lidi jste tak blbí!}
{2256}{}{Proè zrovna do koulí?}
{2257}{}{Tvoje smrt bude bolestivá, èlovìèe!}
{2258}{}{Za to si zaslouíš zemøít...}

# 14. Nightkin
# We are the Chosen of the Master, and all must bow before us. (Damn these bastards are really arrogant); my interpretation is that these boys are smarter and more cunning than garden variety Super Mutants.
#
# running away
#
{2300}{}{Ustup! Kliï se!}
{2301}{}{Vùdce tì za tohle znièí!}
{2302}{}{Ještì jsme neskonèili!}
{2303}{}{Stihne tì Vùdcova pomsta!}
{2304}{}{Tohle si odsereš -- pozdìjc!}
{2305}{}{Na tvém srdci si pochutnám nìkdy jindy!}
#
# moving in to attack
#
{2306}{}{Tvá smrt je bezodkladná}
{2307}{}{Rozzlobil jsi mì a teï za to zaplatíš!}
{2308}{}{Pøinesu další obìti Svatému plameni!}
{2309}{}{Kdo se postaví Jednotì, musí bıt odstranìn!}
{2310}{}{Smrt nepøátelùm Vùdce!}
{2311}{}{S vámi je konec, budoucnost patøí nám!}
#
# attacking
#
{2312}{}{Tohle je konec!}
{2313}{}{Nikdo, ani Bùh, ti teï nepomùe!}
{2314}{}{V hrobì se ti bude líbit!}
{2315}{}{Tohle je vùle Vùdce!}
{2316}{}{Dneska u se budeš smait v pekle!}
{2317}{}{Zemøeš mojí rukou}
{2318}{}{Ve jménu Vùdce, chcípni!}
{2319}{}{Takhle chutná smrt!}
{2320}{}{Spálí tì Svatı plamen!}
{2321}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{2322}{}{Jak smìšnı! Proè se vùbec namáháš vzdorovat?}
{2323}{}{Je tohle opravdu všechno, co to vaše lidstvo dokáe?}
{2324}{}{Jsi stejnì slabej na tìle jako na duchu!}
{2325}{}{Tohle byla tvá poslední chyba}
{2326}{}{Vùdce mì pøed nepøáteli ochrání!}
{2327}{}{Nemùeš ublíit Vyvolenım}
#
# target hit in head
#
{2328}{}{Za to budeš trpìt!}
{2329}{}{Za to budeš trpìt!}
{2330}{}{Áaaaaou! Roztrhám tì na kusy!}
#
# target hit in left arm
#
{2331}{}{Áaaaaou! Moje ruka}
{2332}{}{Áaaaaou! Já se jen tak lehce nevzdám!}
{2333}{}{Áaaaaou! Za tohle v tobì nezùstane jediná kost celá}
#
# target hit in right arm
#
{2334}{}{Áaaaaou! Moje ruka}
{2335}{}{Áaaaaou! Mì jen tak nedostaneš!}
{2336}{}{Áaaaaou! Toho budeš litovat}
#
# target hit in torso
#
{2337}{}{Áaaa!}
{2338}{}{Uf!}
{2339}{}{Vùdèe!}
{2340}{}{Poníil jsi mì...}
{2341}{}{Áaaa!}
{2342}{}{Grrr!}
#
# target hit in right leg
#
{2343}{}{Áaaaaou! Moje noha}
{2344}{}{Áaaaaou! Mì jen tak neporazíš!}
{2345}{}{Áaaaaou! Za tohle budeš pykat!}
#
# target hit in left leg
#
{2346}{}{Áaaaaou! Moje noha}
{2347}{}{Áaaaaou! Mì jen tak neporazíš!}
{2348}{}{Áaaaaou! Za tohle tì rozdrtím!}
#
# target hit in eyes
#
{2349}{}{Áaaaaou! Zasranej èlovìk! Oslepil jsi mì}
{2350}{}{Áaaaaou! Ta bolest! Cos mi to proved!}
{2351}{}{Áaaaaou! Za tohle budeš trpìt ve vìènı agónii!}
#
# target hit in groin
#
{2352}{}{Já nejsem taková citlivka jako vy lidi!}
{2353}{}{Moje svaly jsou pevnìjší ne tvoje!}
{2354}{}{Jaká smìšná taktika....!}
{2355}{}{Mùj Vùdce mì chrání, èlovìèe!}
{2356}{}{Pomsta bude sladká, èlovìèe!}
{2357}{}{Uff! Asi bych mìl vyzkoušet tvoje slabá místa}

# 15. Children, Brainwashed (Cathedral)
# The Master protects us, and none may bring us death or even suffering!
#
#  running away
#
{2400}{}{Vùdèe! Proè jsi mì opustil!}
{2401}{}{Vùdce mì pomstí!}
{2402}{}{Promiòte Vùdèe, ale u musím bìet!}
{2403}{}{Nebojíš se odplaty?}
{2404}{}{Svatı plamen nech mì chrání!}
{2405}{}{Pomoz mi Vùdèe, pomoz!}
#
# moving in to attack
#
{2406}{}{Vùdcovi nepøátelé musí shoøet ve Svatém plameni!}
{2407}{}{Vùdcovi nepøátelé musí zemøít!}
{2408}{}{Jednota zvítìzí!}
{2409}{}{Krev Dìtí bude pomstìna!}
{2410}{}{Mír musí bıt nasycen krví nepøátel!}
{2411}{}{Jednotu nebo smrt!}
#
# attacking
#
{2412}{}{Neutíkej, jsme pøátelé}
{2413}{}{Ve jménu Vùdce, zemøi!}
{2414}{}{Pohleï na Svatı plamen!}
{2415}{}{Polib oheò a vykopej si hrob!}
{2416}{}{Jednota!}
{2417}{}{Nikdo nezastaví postup míru!}
{2418}{}{Nezastavíš Jednotu!}
{2419}{}{Za Jednotu!}
{2420}{}{Vùdèe, poehnej mi!}
{2421}{}{Shoø ve Svatém plameni!}
#
# target being missed
#
{2422}{}{Vùdce mì ochraòuje!}
{2423}{}{Skloò se pøed Vùdcem, mì nemùeš zranit!}
{2424}{}{Díky, Vùdèe!}
{2425}{}{Vùdcova milost je obrovská!}
{2426}{}{Svatı plamen mì chrání!}
{2427}{}{Nedokáeš ublíit Dìtem}
#
# target hit in head
#
{2428}{}{Agghhh! Co mì to trefilo!}
{2429}{}{Vùdèe! Chraò mì!}
{2430}{}{Uff!}
#
# target hit in left arm
#
{2431}{}{Moje ruka!}
{2432}{}{Vùdce vyléèí má zranìní...}
{2433}{}{Vùdèe! Co mi to jenom udìlali!}
#
# target hit in right arm
#
{2434}{}{Ou, moje ruka}
{2435}{}{Vùdce vyléèí má zranìní...}
{2436}{}{Vùdèe! Co mi to jenom udìlali!}
#
# target hit in torso
#
{2437}{}{Uff!}
{2438}{}{Auua!}
{2439}{}{Vùdèe, ochraò mì!}
{2440}{}{Vùdèe, pomsti mì!}
{2441}{}{Gulp!}
#
# target hit in right leg
#
{2442}{}{Sakra, moje noha}
{2443}{}{Zlomil jsi mi nohu!}
{2444}{}{Vùdèe! Co mi to jenom udìlali!}
#
# target hit in left leg
#
{2445}{}{Moje noha!}
{2446}{}{Zlomil jsi mi nohu!}
{2447}{}{Vùdèe! Co mi to jenom udìlali!}
#
# target hit in eyes
#
{2448}{}{Vùdèe, jsem slepı!}
{2449}{}{Vùdèe, moje oèi hoøí!}
{2450}{}{Vùdèe, nevidím!}
#
# target hit in groin
#
{2451}{}{Oooooo, do slabin!}
{2452}{}{Vùdèe!}
{2453}{}{Vùdèe, ochraò mì od bolesti!}
{2454}{}{Ne...nemùu...dıchat...}
{2455}{}{Vùdèe, naši nepøátelé jsou krutí!}
{2456}{}{Vùdèe, naši nepøátelé jsou krutí!}

# 16. Children, Brainwashed (Hub)
# The Master protects us, and none may bring us death or even suffering!
#
#  running away
#
{2500}{}{Proè jsi mì opustil!}
{2501}{}{Budu pomstìn!}
{2502}{}{Promiò, ale u musím jít!}
{2503}{}{Nebojíš se odplaty?}
{2504}{}{Svatı plameni, ochraòuj mì!}
{2505}{}{Svatı plameni, vyveï mì pryè!}
#
# moving in to attack
#
{2506}{}{Nepøátelé shoøí ve Svatém plameni!}
{2507}{}{Nepøátelé musí zemøít!}
{2508}{}{Jednota zvítìzí!}
{2509}{}{Krev Dìtí bude pomstìna!}
{2510}{}{Mír musí bıt nasycen krví nepøátel!}
{2511}{}{}
#
# attacking
#
{2512}{}{Chcípni!}
{2513}{}{Chcípni ve jménu Plamene!}
{2514}{}{Pohleï na Svatı plamen!}
{2515}{}{Ve jménu míru, zemøi!}
{2516}{}{Jednota!}
{2517}{}{Nikdo nezastaví vítìzné taení míru!}
{2518}{}{Pohane!}
{2519}{}{Neutíkej, jsme pøátelé!}
{2520}{}{Vùdèe, poehnej mi!}
{2521}{}{Usmaíš se ve Svatém plameni, neznabohu!}
#
# target being missed
#
{2522}{}{Vùdce mì ochraòuje!}
{2523}{}{Skloò se pøed Plamenem, mì nemùeš zranit!}
{2524}{}{Tvùj bùh tì zradil!}
{2525}{}{Zlo se samo porazilo!}
{2526}{}{Svatı plamen mì chrání!}
{2527}{}{Nemùeš ublíit Dìtem}
#
# target hit in head
#
{2528}{}{Agghhh! Co to bylo!}
{2529}{}{Vùdèe! Pomoz mi!}
{2530}{}{Aauuu}
#
# target hit in left arm
#
{2531}{}{Ou, moje ruka}
{2532}{}{Zlomil jsi mi ruku!}
{2533}{}{Cos mi to proved!}
#
# target hit in right arm
#
{2534}{}{Ou, moje ruka}
{2535}{}{Zlomil jsi mi ruku!}
{2536}{}{Parchante!}
#
# target hit in torso
#
{2537}{}{Aaau! To bolelo!}
{2538}{}{!*&^@#!}
{2539}{}{Oh, oh, To bolelo!}
{2540}{}{Aaau!}
{2541}{}{Ooph!}
{2542}{}{Uff!}
#
# target hit in right leg
#
{2543}{}{Sakra, moje noha}
{2544}{}{Zlomil jsi mi nohu!}
{2545}{}{Cos to proved!}
#
# target hit in left leg
#
{2546}{}{Sakra, moje noha}
{2547}{}{Zlomil jsi mi nohu!}
{2548}{}{^%@!!}
#
# target hit in eyes
#
{2549}{}{Nevidím!}
{2550}{}{Moje oèi!}
{2551}{}{Byl jsem oslepen za své høíchy!}
#
# target hit in groin
#
{2552}{}{Oooooo, do slabin!}
{2553}{}{Oooooo, ty zbabìlèe!!}
{2554}{}{Plameni, ochraòuj mé sémì!}
{2555}{}{...nemùu...dejchat...}
{2556}{}{...nemùu...dejchat...}
{2557}{}{Naši nepøátelé jsou tak suroví!}

# 17. Children, Non-Brainwashed
# Get some zombies in here to take care of this pest!
#
#  running away
#
{2600}{}{Církev tì dostane!}
{2601}{}{Církev se o sebe dokáe postarat sama!}
{2602}{}{Pomoc!}
{2603}{}{}
{2604}{}{O tebe se postará jinı bøídil}
{2605}{}{Kvùli tomuhle se zabít nenechám!}
#
# moving in to attack
#
{2606}{}{}
{2607}{}{Do hrobu s tímhle pobudou!}
{2608}{}{Èas zemøít!}
{2609}{}{Tady nemáš co pohledávat!}
{2610}{}{Je èas vynést tohle smetí ven...}
{2611}{}{Budeš pykat za svoje „høíchy“...}
#
# attacking
#
{2612}{}{Tu máš!}
{2613}{}{Ty sráèi!}
{2614}{}{Chcípni!}
{2615}{}{Tak pojï, ty srabe, jestli si troufneš!}
{2616}{}{Já s tebou zatoèím}
{2617}{}{Já s tebou zatoèím}
{2618}{}{Èas zemøít...}
{2619}{}{Èas zemøít...}
{2620}{}{Polib mùj Svatı plamen, kámo!}
{2621}{}{Polib mùj Svatı plamen, kámo!}
#
# target being missed
#
{2622}{}{Ha, netrefa!}
{2623}{}{Takovej tupec!}
{2624}{}{Cha, minuls mì!}
{2625}{}{Jsi vìtší hovno, ne zombíci!}
{2626}{}{Kdo tì uèil míøit, prosím tì?}
{2627}{}{Jsi vìtší hovno, ne zombíci!}
#
# target hit in head
#
{2628}{}{Ugh!}
{2629}{}{Uff!}
{2630}{}{Kurva! To bolelo!}
#
# target hit in left arm
#
{2631}{}{Ou, moje ruka}
{2632}{}{To tì bude mrzet!}
{2633}{}{Za to ti zlámu hnáty!}
#
# target hit in right arm
#
{2634}{}{Ou, moje ruka}
{2635}{}{Toho budeš litovat!}
{2636}{}{Za to ti zlámu hnáty!}
#
# target hit in torso
#
# <no messages here>
#
# target hit in right leg
#
{2637}{}{Sakra, moje noha}
{2638}{}{Za to mi zaplatíš!}
{2639}{}{Ty mizero! Já tì dostanu!}
#
# target hit in left leg
#
{2640}{}{Sakra, moje noha}
{2641}{}{Toho budeš litovat!}
{2642}{}{Aauuu}
#
# target hit in eyes
#
{2643}{}{Tos nemìl, je po tobì!}
{2644}{}{Moje oko, za to budeš trpìt!}
{2645}{}{To by dokázal kadej!}
#
# target hit in groin
#
{2646}{}{Aaaa, to šlo do masa!}
{2647}{}{Sakra, To bolelo!}
{2648}{}{!%@$ #^%!@# ^#$%@^#!!!}
{2649}{}{Do prdele zepøedu!}
{2650}{}{}
{2651}{}{}

# 18. The Master
# Unity is its own protection. My enemies will not withstand me. Withstand.
#
#  running away
#
{2700}{}{Tenhle boj je zbyteènı}
{2701}{}{Pomsta bude sladká!}
{2702}{}{Tvoje radost nebude dlouho trvat!}
{2703}{}{Neporazíš Jednotu}
{2704}{}{Moji sluebníci mì ochrání!}
{2705}{}{Nadìje! Hlavnì neztrácet nadìji!}
#
# moving in to attack
#
{2706}{}{Tvoje høíchy budou teï potrestány}
{2707}{}{Všichni moji nepøátelé musí zemøít. Zemøít!}
{2708}{}{Jednota zvítìzí! Zvítìzí!}
{2709}{}{Nedovolíme ti znièit náš svìt}
{2710}{}{Budoucnost musí bıt zachránìna! Zachránìna!}
{2711}{}{Jednotu nebo smrt! Smrt!}
#
# attacking
#
{2712}{}{Zemøi!}
{2713}{}{Budeš totálnì znièen}
{2714}{}{Zpeèetil jsi svou zkázu}
{2715}{}{Za to zaplatíš! Zaplatíš!}
{2716}{}{Jednota!}
{2717}{}{Nikdo nezastaví taení míru! Míru!}
{2718}{}{U tì neèeká nic, ne oheò! Oheò!}
{2719}{}{Toto budi tvùj epitaf}
{2720}{}{Jsi hovno! Hovno!}
{2721}{}{Tvé bytí tu konèí}
#
# target being missed
#
{2722}{}{Namáháš se zbyteènì! Zbyteènì!}
{2723}{}{Nade mnou nemùeš zvítìzit!}
{2724}{}{Zase ses spletl}
{2725}{}{Zlo se samo porazilo!}
{2726}{}{Nepøeiješ}
{2727}{}{Tvùj vıkon je mizernı}
#
# target hit in head
#
{2728}{}{Zranìní hlavy}
{2729}{}{Ta bolest byla nepøíjemná}
{2730}{}{To mì neoslabí}
#
#
# target hit in frame
#
{2731}{}{Myslíš, e tohle mì poškodí?}
{2732}{}{Lehké zranìní, èlovìèe, lehké}
{2733}{}{Ta bolest byla trochu nepøíjemná}
{2734}{}{ádné škody na obvodech, které by nedaly pozdìji opravit}
{2735}{}{Zemøeš! Zemøeš!}
#
# target hit in CPU
#
{2736}{}{Zásah systému, nahrazeno}
{2737}{}{Zásah systému, lehké škody}
{2738}{}{Zásah systému, zásah systému, zásah systému}

# 19. Ghoul, Nasty
# Now you'll find out why it's called the Necropolis
#
#  running away
{2800}{}{Musím zmizet!}
{2801}{}{Hned jsem zpátky...}
{2802}{}{Dneska mì neoddìláš!}
{2803}{}{Zatím, normále!}
{2804}{}{Neslyšel jsi o mnì naposled!}
{2805}{}{Za to mi zaplatíš -- jindy!}
#
# moving in to attack
#
{2806}{}{Je po tobì!}
{2807}{}{Èerstvı masíèko...}
{2808}{}{Aaa, veèeøe je tu.}
{2809}{}{Áááá, mozeèky...}
{2810}{}{U ti kopu hrob...}
{2811}{}{Doufám, e ti nezruším i hlavu...}
#
# attacking (10)
#
{2812}{}{Pøišla na tebe øada!}
{2813}{}{Nenamáhej se prosit o slitování...}
{2814}{}{To si vychutnám}
{2815}{}{Jéé, to bude bolet!}
{2816}{}{}
{2817}{}{U se tìším na tvoje játra!}
{2818}{}{Hlavnì abys nechcíp moc brzo}
{2819}{}{Veèeøe!}
{2820}{}{Chcípni!}
{2821}{}{Takovı jako ty jím k snídani. A k obìdu...}
#
# target being missed (6)
#
{2822}{}{Ty mi nemùeš nic udìlat!}
{2823}{}{}
{2824}{}{Vedle, normále!}
{2825}{}{Vedle, normále!}
{2826}{}{Nezabiješ nìco, co ani netrefíš!}
{2827}{}{Pomalej!}
#
# target hit in head (3)
#
{2828}{}{Ooou, mùj krásnej ksichtík}
{2829}{}{Aauuu. Moje hlava!}
{2830}{}{Ufff!}
#
# target hit in left arm
#
{2831}{}{Moje ruka!}
{2832}{}{Aauuu}
{2833}{}{Aauuu!}
#
# target hit in right arm
#
{2834}{}{Ou, moje ruka}
{2835}{}{Zlomil jsi mi ruku!}
{2836}{}{Toho budeš litovat!}
#
# target hit in torso
#
{2837}{}{[Grunt!]}
{2839}{}{Kurva!}
{2840}{}{Grrr!}
{2841}{}{Toho budeš litovat!}
{2842}{}{Nech toho dokud je èas!}
{2843}{}{}
{2844}{}{}
#
# target hit in right leg
#
{2845}{}{Sakra, moje noha}
{2846}{}{Za to mi zaplatíš!}
{2847}{}{Áaaa! Zlomil jsi mi nohu, za to ti teï zlomím vaz!}
#
# target hit in left leg
#
{2848}{}{Moje noha!}
{2849}{}{}
{2850}{}{}
#
# target hit in eyes
#
{2851}{}{Teèe mi krev...moje oèi!}
{2852}{}{Moje oko! Tak tohle ti vrátím!}
{2853}{}{Ty bastarde!}
#
# target hit in groin
#
{2854}{}{Oooooo, moje koule!}
{2855}{}{Ooo! To se musím taky nauèit...}
{2856}{}{Ty nelidská svinì!}
{2857}{}{AAAAAAAAAAAACCCKKKKKK!}
{2858}{}{Urp!}
{2859}{}{Uff! Za tohle tì oddìlám!}

# 20. Super Mutant, Necropolis
# The lesser species need to know when to stand aside. (Damn, these bastards are arrogant)
#
#  running away
#
{2900}{}{Kliï se! Padej!}
{2901}{}{Dneska mì nedostaneš!}
{2902}{}{Ještì jsme spolu neskonèili!}
{2903}{}{Kámoši tì odkráglujou za mì!}
{2904}{}{Tohle si odskáèeš -- pozdìjc!}
{2905}{}{Na tvém srdci si pochutnám nìkdy jindy!}
#
# moving in to attack
#
{2906}{}{Zabiju tì, srabe!}
{2907}{}{Kdo nás jednou rozzlobí, zemøe!}
{2908}{}{Tvoje trapnı zbranì mi ublíit nemùou!}
{2909}{}{A hele, další obì si jde s námi hrát!}
{2910}{}{Skonèím jednou pro vdy tvoje trápení}
{2911}{}{}
#
# attacking
#
{2912}{}{}
{2913}{}{}
{2914}{}{Teï chcípneš!}
{2915}{}{Tohle my dìláme èeládce jako ty!}
{2916}{}{Tohle si vychutnám...}
{2917}{}{}
{2918}{}{Tvoji bohové tì zradili!}
{2919}{}{Rád si poslechnu tvùj øev!}
{2920}{}{Tak a teï chcípni!}
{2921}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{2922}{}{Ani se nesna, kreténe...}
{2923}{}{Tak tohle je ta vaše lidskost - nic moc?}
{2924}{}{Jseš stejnì slabej na tìle jako na duchu!}
{2925}{}{To byla tvoje poslední chyba}
{2926}{}{Blázne! A ty sis myslel, e mì porazíš?}
{2927}{}{Trapnı!}
#
# target hit in head
#
{2928}{}{Áaaaaou! Mùj ksicht!}
{2929}{}{Mùj ksicht! Za to budeš trpìt, zmrde!}
{2930}{}{Áaaaaou! Rozpáøu tì na kusy!}
#
# target hit in left arm
#
{2931}{}{Áaaaaou! Moje ruka}
{2932}{}{Áaaaaou! Mì jen tak neporazíš!}
{2933}{}{Áaaaaou! Za to ti pøerazím vaz!}
#
# target hit in right arm
#
{2934}{}{Áaaaaou! Moje ruka}
{2935}{}{Áaaaaou! Mì jen tak neporazíš!}
{2936}{}{Áaaaaou! Za to ti pøerazím vaz!}
#
# target hit in torso
#
{2937}{}{Nekropolis bude kvùli tobì trpìt}
{2938}{}{Uff!}
{2939}{}{Arg!}
{2940}{}{[Úsmìv]}
{2941}{}{To nebolí!}
{2942}{}{Pøece nejsi takovej sráè}
{2943}{}{I ghúlové jsou silnìjší ne ty!}
{2944}{}{}
{2945}{}{}
{2946}{}{Chacha, jakej trapnej pokus... (uff)}
#
# target hit in right leg
#
{2947}{}{Áaaaaou! Moje noha}
{2948}{}{Áaaaaou! Mì jen tak neporazíš!}
{2949}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in left leg
#
{2950}{}{Áaaaaou! Moje noha}
{2951}{}{Áaaaaou! Mì jen tak neporazíš!}
{2952}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{2953}{}{Áaaaaou! Proklatej èlovìk! Oslepil jsi mì!}
{2954}{}{Áaaaaou! Ta bolest! Cos to proved!}
{2955}{}{Áaaaaou! Za tohle tì stihne trest!}
#
# target hit in groin
#
{2956}{}{Nejsem takovej slaboch jako vy lidé!}
{2957}{}{Moje svaly jsou pevnìjší ne tvoje!}
{2958}{}{Nic lepšího bys tam nemìl?!}
{2959}{}{Tam mi neublííš, èlovìèe!}
{2960}{}{Pomsta tì nemine!}
{2961}{}{A co se podívat na tvoje slabiny...}

# 21. Guard, Raider
# You're dead! I do hope you have cool stuff...
#
#  running away
{3000}{}{Zachraò se kdo mùeš!}
{3001}{}{Kliï se odsud!}
{3002}{}{Vypadni!}
{3003}{}{Padej!}
{3004}{}{Zpátky!}
{3005}{}{Aaaaaaa!}
#
# moving in to attack
#
{3006}{}{Zaslouíš si smrt, sráèi!}
{3007}{}{Èerstvı maso...}
{3008}{}{Koøist!}
{3009}{}{Tenhle je mùj!}
{3010}{}{Dej mu!}
{3011}{}{}
#
# attacking (10)
#
{3012}{}{Uij si poslední chvilky ivota}
{3013}{}{Krev! Krev! Krev!}
{3014}{}{Vyrvu ti srdce!}
{3015}{}{RAAAAAAARRRR!!}
{3016}{}{Tvoje smìšnı zbranì budou moje trofej!}
{3017}{}{Smrt!}
{3018}{}{Tebe si dám já!}
{3019}{}{Za chvíli u si na tobì budou pochutnávat supi!}
{3020}{}{Krev, krev a tma!}
{3021}{}{}
{3022}{}{Zakrslej zmetku, je po tobì!}
#
# target being missed (6)
#
{3023}{}{Škoda námahy!}
{3024}{}{Jseš úplnı hovno!}
{3025}{}{Mám lepší krev ne ty!}
{3026}{}{iju!!}
{3027}{}{Jak smìšnı, jak trapnı!}
#
# target hit in head (3)
#
{3028}{}{Aaaah! Mùj ksicht!}
{3029}{}{#@$^!! %%$^&!!?!}
{3030}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{3031}{}{Au, moje ruka}
{3032}{}{Zlomil jsi mi ruku!}
{3033}{}{Za to zgebneš!}
#
# target hit in right arm
#
{3034}{}{Au, moje ruka}
{3035}{}{Zlomil jsi mi ruku!}
{3036}{}{Za to tì èeká smrt!}
#
# target hit in torso
#
{3037}{}{}
{3038}{}{Tomuhle øíkáš bolest!?}
{3039}{}{Aaau!}
{3040}{}{Uff!}
{3041}{}{Sakra! To bolelo!}
{3042}{}{Pojï sem, já ti ukáu!}
{3043}{}{Za to draze zaplatíš, to ti pøísahám!}
{3044}{}{Úúúch!}
{3045}{}{}
{3046}{}{Eegah! Ta sedla!}
#
# target hit in right leg
#
{3047}{}{Sakra, moje noha}
{3048}{}{Za to chcípneš!}
{3049}{}{Áaaa! Zlomil jsi mi nohu, já ti zlomím vaz!}
#
# target hit in left leg
#
{3050}{}{Sakra, moje noha}
{3051}{}{Za to chcípneš!}
{3052}{}{Áaaa!!}
#
# target hit in eyes
#
{3053}{}{Áaaa! Roztrhám tì na kusy!}
{3054}{}{Moje oko!}
{3055}{}{Moje oko! Zgebneš pomalu, ale jistì!}
#
# target hit in groin
#
{3056}{}{Oooooo, koule!}
{3057}{}{Ooo! ... budeš... tìce trpìt...}
{3058}{}{Ooo! Zabiju....tì...}
{3059}{}{Ooo! Zmrzaèím tì zmrde...}
{3060}{}{Urp!}
{3061}{}{Zabiju tì!}

# 22. Leader, Raider
# I feast on the hearts of my enemies!
#
#  running away
{3100}{}{Krejte mì!}
{3101}{}{Na ústup!}
{3102}{}{Drte pohromadì!}
{3103}{}{Padáme!}
{3104}{}{Zpátky!}
{3105}{}{Aaaaghhh!}
#
# moving in to attack
#
{3106}{}{Jdeme na to!}
{3107}{}{Èerstvı maso...}
{3108}{}{Koøist!}
{3109}{}{Tenhle je mùj!}
{3110}{}{Khanové do toho!}
{3111}{}{}
#
# attacking (10)
#
{3112}{}{Vradíme! Khanové!}
{3113}{}{Krev! Krev! Krev!}
{3114}{}{Jsem bùh!}
{3115}{}{RAAAAAAARRRR!!}
{3116}{}{Khanové jsou nepøemoitelní!}
{3117}{}{Já se nevzdávám! Nikdy!}
{3118}{}{Na tobì si pochutnám já!}
{3119}{}{U teï jseš jen maso pro supy!}
{3120}{}{Krev, krev a tma!}
{3121}{}{Khanové jsou silní!}
#
# target being missed (6)
#
{3122}{}{}
{3123}{}{Mnì jen tak nedostaneš!}
{3124}{}{Jsem neznièitelnı!}
{3125}{}{Moje krev vydrí víc ne tvoje!}
{3126}{}{RAAAAAAAAARRRR!!}
{3127}{}{Nejsi hoden se mnou bojovat!}
#
# target hit in head (3)
#
{3128}{}{Dobrá rána!}
{3129}{}{To byl tvùj poslední úder!}
{3130}{}{Mùj nos!}
#
# target hit in left arm
#
{3131}{}{Pøepral bych tì jednou rukou!}
{3132}{}{Zlomil jsi mi ruku! Aspoò to teï bude fér!}
{3133}{}{To byla tvá poslední rána!}
#
# target hit in right arm
#
{3134}{}{Pøeperu tì jednou rukou!}
{3135}{}{Zlomil jsi mi ruku! Aspoò jsme si teï rovni!}
{3136}{}{To byla tvá poslední rána!}
#
# target hit in torso
#
{3137}{}{Tvoje smrt bude krvavá!}
{3138}{}{U teï se tìším na šávu z tvıch oèí!}
{3139}{}{Kurnik!}
{3140}{}{Uff!}
{3141}{}{Aaau!}
{3142}{}{}
{3143}{}{Chchchr!}
{3144}{}{Zlomil jsi mi ebro. Teï ti já vyrvu tvoje - aby to bylo fér}
{3145}{}{}
{3146}{}{Ííííáá}

#
# target hit in right leg
#
{3147}{}{Tohle mi nezabrání tì zabít!}
{3148}{}{Za to chcípneš!}
{3149}{}{}
#
# target hit in left leg
#
{3150}{}{Tohle mi nezabrání tì zabít!}
{3151}{}{Za to chcípneš!}
{3152}{}{}
#
# target hit in eyes
#
{3153}{}{Áaaa! Roztrhám tì na kusy!}
{3154}{}{Moje oko! Mùj zrak za tvou smrt!!}
{3155}{}{Moje oko! Za to budeš umírat pomalu!}
#
# target hit in groin
#
{3156}{}{Oooooo, moje koule!}
{3157}{}{Ooo! budeš trpìt...svinì...}
{3158}{}{Ooo! ...zabiju...tì...}
{3159}{}{Ooo! utrhnu..ti tvoje........}
{3160}{}{Urp!}
{3161}{}{Moje muství mi nevezmeš!}

# 23. Peasant, Shady Sands
# Get out of Shady Sands, you troublemaking scum!
#
#  running away
#
{3200}{}{Nemysli si, e jsme spolu skonèili!}
{3201}{}{Pomozte...nìkdo!}
{3202}{}{Pomozte mi nìkdo!}
{3203}{}{Doèkáš se spravedlnosti!}
{3204}{}{Jednoho dne se doèkáš!}
{3205}{}{Za tohle se zabít nenechám!}
#
# moving in to attack
#
{3206}{}{}
{3207}{}{}
{3208}{}{}
{3209}{}{Lidi jako ty tu netrpíme!}
{3210}{}{Tady se nikdo nebude roztahovat...}
{3211}{}{V Shady Sands takovı nepotøebujeme!}
#
# attacking
#
{3212}{}{}
{3213}{}{Tak copak s tebou slabochu?}
{3214}{}{Tohle my dìláme s verbeí jako jsi ty!}
{3215}{}{}
{3216}{}{Takhle my tu øešíme nepøíjemnosti.}
{3217}{}{Poèkej, tohle tì nauèí!}
{3218}{}{A zetleješ, budeš se hodit na hnojení.}
{3219}{}{Dobrá. Øek sis o to sám.}
{3220}{}{Ty zvíøe!}
{3221}{}{Budeš litovat, e jsi sem vùbec pøišel!}
#
# target being missed
#
{3222}{}{Jsi horší ne si myslíš...}
{3223}{}{}
{3224}{}{Jsi tupìjší ne krtkopotkan}
{3225}{}{Shady Sands se nebojí nikoho a nièeho}
{3226}{}{}
{3227}{}{To byla tvoje poslední chyba}
#
# target hit in head
#
{3228}{}{Sakra!}
{3229}{}{Áááaamm!}
{3230}{}{Mùj ksicht! Mùj ksicht!}
#
# target hit in left arm
#
{3231}{}{Áááaamm! Moje ruka}
{3232}{}{Moje ruka!}
{3233}{}{Sakra, ruka v prdeli...}
#
# target hit in right arm
#
{3234}{}{Áááaamm! Moje ruka}
{3235}{}{Moje ruka!}
{3236}{}{Sakra, ruka v prdeli...}
#
# target hit in torso
#
{3237}{}{Aaau!}
{3238}{}{Doh!}
{3239}{}{}
{3240}{}{A chcípneš a trpíš i po smrti...}
{3241}{}{Chchchrrr!}
{3242}{}{}
{3243}{}{Proboha neeee...}
{3244}{}{}
{3245}{}{Tos nemìl...}
{3246}{}{Gack!}
#
# target hit in right leg
#
{3247}{}{Áááaamm! Moje noha}
{3248}{}{Moje noha!}
{3249}{}{Ksakru, noha v hajzlu...}
#
# target hit in left leg
#
{3250}{}{Áááaamm! Moje noha}
{3251}{}{Moje noha!}
{3252}{}{Ksakru, noha v hajzlu...}
#
# target hit in eyes
#
{3253}{}{Áááaamm! Aauuu!}
{3254}{}{Ksakru! Proè je taková tma!}
{3255}{}{Moje oko! Za tohle mi zaplatíš!}
#
# target hit in groin
#
{3256}{}{Oooooo, moje varle!}
{3257}{}{Oúúúúúúúufffffff!}
{3258}{}{Nemùu...popadnout...dech...}
{3259}{}{!}
{3260}{}{To je bolest, ááá ta bolest...}
{3261}{}{Sakra, to bolelo!}

# 24. Guard, Shady Sands
# I'm staying alert. Never know what's gonna walk out of the wastes
#
#  running away (6)
#
{3300}{}{Honem pryè}
{3301}{}{}
{3302}{}{Aaaaahhhh!}
{3303}{}{Co tøeba nìkdy jindy...}
{3304}{}{}
{3305}{}{Uvidíme se...zatím..}
#
# moving in to attack
#
{3306}{}{}
{3307}{}{Co zas chceš?}
{3308}{}{Já to vyjednám...}
{3309}{}{Snad ne další obejda!}
{3310}{}{Kdy to nejsou radškorpióni, tak jsou tu zas ty zatracenı nájezdníci...}
{3311}{}{}
#
# attacking
#
{3312}{}{}
{3313}{}{Chcípni svinì!}
{3314}{}{Sráèi}
{3315}{}{Máslo}
{3316}{}{}
{3317}{}{Jsi na øadì!}
{3318}{}{U docela sereš...}
{3319}{}{Tady máš nìco ze Shady Sands}
{3320}{}{U nás tu dlouho štvát nebudeš}
{3321}{}{U si chystej rakev}
#
# target being missed
#
{3322}{}{Nic moc}
{3323}{}{Zaèáteèníku}
{3324}{}{K smíchu}
{3325}{}{Pomalej}
{3326}{}{Jseš naprostı hovno}
{3327}{}{Mìl by sis najít nìco lepšího, tohle ti nejde}
#
# target hit in head
#
{3328}{}{To bolelo}
{3329}{}{Moje oèi!}
{3330}{}{Aauuu. Mám v hajzlu nos...}
#
# target hit in left arm
#
{3331}{}{Auu!}
{3332}{}{Auu! Moje ruka!}
{3333}{}{Aauuu. Zlomil jsi jí!}
#
# target hit in right arm
#
{3334}{}{Au}
{3335}{}{Auuu, moje ruka!}
{3336}{}{Auuu, zlomil jsi ji!}
#
# target hit in torso
#
{3337}{}{Sakra! To bolelo!}
{3338}{}{Aaau!}
{3339}{}{AAuuuu}
{3340}{}{}
{3341}{}{(dríc se za ebra) Aaau!}
{3342}{}{Hej! Ve mìstì ne!}
{3343}{}{Chchchrrr!}
{3344}{}{Au. Zklamali jste mì...}
{3345}{}{Uff!}
{3346}{}{To bolelo!}
#
# target hit in right leg
#
{3347}{}{Aauuu}
{3348}{}{Aauuu, moje koleno!}
{3349}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{3350}{}{Aauuu}
{3351}{}{Aauuu, moje koleno!}
{3352}{}{Aauuu, moje hnáta!}
#
# target hit in eyes
#
{3353}{}{Nevidím!}
{3354}{}{Nevidím vùbec nic!}
{3355}{}{Taková tma...}
#
# target hit in groin
#
{3356}{}{Oooooou, zase koule!}
{3357}{}{Aííííí!}
{3358}{}{Sakra, to bolelo}
{3359}{}{Ouff!}
{3360}{}{Urp!}
{3361}{}{...nemùu...dıchat...}

# 25. Leader, Shady Sands
# I don't want trouble, but it comes around often enough that I know how to deal with it.
#
#  running away (6)
#
{3400}{}{}
{3401}{}{}
{3402}{}{Potøebuju doktora}
{3403}{}{Co takhle nìkdy jindy...}
{3404}{}{Radši se nezaplést}
{3405}{}{Mìj se...}
#
# moving in to attack
#
{3406}{}{Teï jsi to posral, kámo}
{3407}{}{Co zas?}
{3408}{}{Tenhle je mùj...}
{3409}{}{Zas nìjakej kretén!}
{3410}{}{Kdy to nejsou radškorpióni, tak jsou to tyhle zmrdi...}
{3411}{}{}
#
# attacking
#
{3412}{}{}
{3413}{}{}
{3414}{}{Strupe}
{3415}{}{Máslo}
{3416}{}{Tohle my dìláme sráèùm jako jsi ty}
{3417}{}{Bolí??}
{3418}{}{Teï jsi v hajzlu}
{3419}{}{Tady máš nìco ze Shady Sands}
{3420}{}{Tady u se neukáeš... Nikdy!}
{3421}{}{Odsud se ivej nedostaneš}
#
# target being missed
#
{3422}{}{Nic moc}
{3423}{}{Nemìl by ses prát, kdy to neumíš}
{3424}{}{Smìšnı}
{3425}{}{Moc pomalej}
{3426}{}{}
{3427}{}{}
#
# target hit in head
#
{3428}{}{}
{3429}{}{Moje lebka!}
{3430}{}{Aauuu, kurva - mám po nosu...}
#
# target hit in left arm
#
{3431}{}{Aauuu}
{3432}{}{Aauuu. Moje ruka!}
{3433}{}{Aauuu, zlomil jsi ji!}
#
# target hit in right arm
#
{3434}{}{Aauuu}
{3435}{}{Aauuu. Moje ruka!}
{3436}{}{Aauuu. Zlomil jsi ji!}
#
# target hit in torso
#
{3437}{}{Aauuu}
{3438}{}{U Dharmy! To bolelo!}
{3439}{}{Kdo chce kam, pomozme mu tam...}
{3440}{}{Uff!}
{3441}{}{Uff! Tohle si odsereš...}
{3442}{}{Aauuu. To bolelo!}
{3443}{}{Aaau! To nebylo dvakrát pøíjemnı}
{3444}{}{Aauuu, proè???}
{3445}{}{Arg! Mìl bych se ovládat...}
{3446}{}{Aook! Vypadáš jak radškorpióní hovno!}
#
# target hit in right leg
#
{3447}{}{Aauuu}
{3448}{}{Aauuu, koleno!}
{3449}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{3450}{}{Aauuu}
{3451}{}{Aauuu, moje koleno!}
{3452}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{3453}{}{Moje oèi!}
{3454}{}{Agghh! Tak ty takhle...}
{3455}{}{Agghh! Ty malej zmrde...}
#
# target hit in groin
#
{3456}{}{Oooooo, moje nebohı koule!}
{3457}{}{Aieee!}
{3458}{}{[kòuèení]}
{3459}{}{Ouff!}
{3460}{}{Oooooo! To jsem neral! Aauuu}
{3461}{}{Oooooo! To bolelo. Asi stárnu nebo co.}

# 26. Ripper
# Rape him or kill him. I can never make up my mind.
#
#  running away
#
{3500}{}{Musím si nìco vyøídit.}
{3501}{}{Hned se vrátím!}
{3502}{}{Zatím!}
{3503}{}{}
{3504}{}{}
{3505}{}{Nìkdy si to zopakujem!}
#
# moving in to attack
#
{3506}{}{Kdo není se mnou, chcípne...}
{3507}{}{Èerstvı maso!}
{3508}{}{!}
{3509}{}{}
{3510}{}{Vytrhám ti støeva!}
{3511}{}{Smím prosit?!}
#
# attacking
#
{3512}{}{Stáhnu z tebe kùi zaiva!}
{3513}{}{}
{3514}{}{Ne tak rychle, uij si svou smrt}
{3515}{}{}
{3516}{}{Pøál sis smrt? Hned to bude!}
{3517}{}{Bude z tebe sexy mrtvola}
{3518}{}{Chcípni, chcípni, chcípni!}
{3519}{}{Lepší ne jsem èekal!}
{3520}{}{Co se tak podívat na tvoje vnitønosti...}
{3521}{}{A to jsem si myslel, e u dneska nebude ádná prdel...}
#
# target being missed
#
{3522}{}{}
{3523}{}{Tys mì ale vylekal!}
{3524}{}{No tak, chcípáku, sna se trochu!}
{3525}{}{Líp to neumíš?}
{3526}{}{Jseš proti mì pára z hovna!}
{3527}{}{Jde to líp ne jsem èekal}
#
# target hit in head
#
{3528}{}{To bude ale pìkná jizvièka!}
{3529}{}{O co ti jde, ty sráèi?}
{3530}{}{Ještì jednou, prdelko!!}
#
# target hit in left arm
#
{3531}{}{Miluju, já prostì miluju, jak praskaj kosti}
{3532}{}{Áááá, pán se naštval!}
{3533}{}{Ještì, miláèku, tak se mi to líbí}
#
# target hit in right arm
#
{3534}{}{Já prostì miluju ten zvuk, kdy praskaj kosti}
{3535}{}{Áááá, pán se nám naštval!}
{3536}{}{Ještì, kotì, tak to mám rád}
#
# target hit in torso
#
{3537}{}{Líbí se mi, kdy se zlobíš...}
{3538}{}{Ještì mì plácni, no tak...}
{3539}{}{Aaau! Oh, láska bolí, viï kotì!}
{3540}{}{Uff!}
{3541}{}{Doh!}
{3542}{}{Áaaa! A to je všechno?}
{3543}{}{Chchchrrr!}
{3544}{}{Ještì jednou, prosím...}
{3545}{}{Teï zas já}
{3546}{}{Oh, to bolí, to je bolest...}
#
# target hit in right leg
#
{3547}{}{Není nic lepšího, ne praskání kostí}
{3548}{}{Ooo, ty ses do toho dal!}
{3549}{}{}
#
# target hit in left leg
#
{3550}{}{Není nad praskání kostí}
{3551}{}{}
{3552}{}{Jó, to miluju!}
#
# target hit in eyes
#
{3553}{}{Hej, já nevidím!}
{3554}{}{Nevidím. Tvùj strach je ale cejtit na sto honù!}
{3555}{}{Moje oèi! Fakt tì eru, kámo}
#
# target hit in groin
#
{3556}{}{Oooooo, moje koule!}
{3557}{}{Ta sedla}
{3558}{}{Oooo! Mám to brát jako návrh k sòatku, kotì?}
{3559}{}{}
{3560}{}{Tak takhle se ti to líbí...}
{3561}{}{Ooooo, dobrá rána, kámo}

# 27. Blade
# I'm gonna tear you a new...
#
#  running away (6)
#
{3600}{}{}
{3601}{}{}
{3602}{}{}
{3603}{}{Ještì není po všem!}
{3604}{}{Odsud!}
{3605}{}{Tohle nemám zapotøebí...}
#
# moving in to attack
#
{3606}{}{Do útoku!}
{3607}{}{Bude mi potìšením upálit tì zaiva!}
{3608}{}{}
{3609}{}{Tady nám nìkdo umøe}
{3610}{}{Zabijte nìkdo toho vetøelce!}
{3611}{}{}
#
# attacking
#
{3612}{}{}
{3613}{}{Chcípni!}
{3614}{}{Zmetku!}
{3615}{}{Ne nadarmo nám øíkají Blades}
{3616}{}{}
{3617}{}{Tohle by mìlo bolet..}
{3618}{}{To se ti bude líbit}
{3619}{}{Tvùj skalp se mi bude hodit do sbírky!}
{3620}{}{Je po tobì}
{3621}{}{Teï se tìš na nejhorší}
#
# target being missed
#
{3622}{}{Bojovat se mnou je jako bojovat s Bohem!}
{3623}{}{Nic moc}
{3624}{}{No ták, pøedveï se trochu!}
{3625}{}{}
{3626}{}{Tvoje máti chrápala s Rozparovaèema, viï!}
{3627}{}{Odháníš mouchy, slabochu?}
#
# target hit in head
#
{3628}{}{}
{3629}{}{Ack!!}
{3630}{}{Aauuu, rozbil jsi mi nos...}
#
# target hit in left arm
#
{3631}{}{Aauuu}
{3632}{}{Aauuu, moje ruka!}
{3633}{}{Aauuu, zlomil jsi ji!}
#
# target hit in right arm
#
{3634}{}{Aauuu}
{3635}{}{Aauuu. Moje ruka!}
{3636}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in torso
#
{3637}{}{Aauuu}
{3638}{}{Aaaa, kurva!}
{3639}{}{Aaau! Tos' nemìl...}
{3640}{}{Aauuu, já ti ukáu...}
{3641}{}{Chchchrrr!}
{3642}{}{..nemùu..dıchat...}
{3643}{}{}
{3644}{}{Uff!}
{3645}{}{Ty mrcho! To bolelo!}
{3646}{}{}
#
# target hit in right leg
#
{3647}{}{Aauuu}
{3648}{}{Aauuu, moje koleno!}
{3649}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{3650}{}{Aauuu}
{3651}{}{Aauuu, moje koleno!}
{3652}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{3653}{}{Jsem slepı!}
{3654}{}{Nic nevidím!}
{3655}{}{Moje oèi! Ty jeden zmrde Rozparovaèskej...}
#
# target hit in groin
#
{3656}{}{Oooooo, varle, to bylo varle!}
{3657}{}{Aieee!}
{3658}{}{Sakra, to bolelo}
{3659}{}{Ouff!}
{3660}{}{Za tohle tì zabiju, ty malej tchoøi}
{3661}{}{Nemùu...popadnout..dech...}

# 28.  Gun Runners
# Are you trying to muscle in on our business?  serious in tone.
#
#  running away
#
{3700}{}{Ještì bych chtìl jednou vidìt vıchod slunce}
{3701}{}{To asi nebyl dobrı nápad}
{3702}{}{}
{3703}{}{}
{3704}{}{Na tohle já se mùu vy....!}
{3705}{}{To mi pro dnešek staèilo...}
#
# moving in to attack
#
{3706}{}{Strkáš nos do našich vìcí, jo?}
{3707}{}{Tak se zdá, e nìkdo právì udìlal velkou chybu!}
{3708}{}{}
{3709}{}{Kdo si myslíš, e jsi?}
{3710}{}{Jseš zvìdavej, co nabízíme?}
{3711}{}{Ty budeš litovat...}
#
# attacking
#
{3712}{}{}
{3713}{}{}
{3714}{}{}
{3715}{}{Jak se ti líbí tohle?}
{3716}{}{Zatoèím s tebou jako s mrtvou krysou}
{3717}{}{Co øíkáš tomuhle arzenálem?}
{3718}{}{Teï se ti podívám na zoubek...}
{3719}{}{Zabíjet je mùj koníèek}
{3720}{}{}
{3721}{}{To tì nauèí úctì}
#
# target being missed
#
{3722}{}{Snad jsi neèekal, e mì dostaneš?}
{3723}{}{Já tohle u dìlám léta}
{3724}{}{Tos´ neèekal, co?}
{3725}{}{To byla tvoje poslední chyba}
{3726}{}{Amatére}
{3727}{}{Tohle není jako støílet krtkopotkany, brácho.}
#
# target hit in head
#
{3728}{}{Aauuu, ty zkurvy...}
{3729}{}{Já tì zabiju}
{3730}{}{Urazím ti hlavu!}
#
# target hit in left arm
#
{3731}{}{Ou, moje ruka}
{3732}{}{Sakra. Moje ruka,...v prdeli!}
{3733}{}{Moje ruka!}
#
# target hit in right arm
#
{3734}{}{Ou, moje ruka}
{3735}{}{Sakra. Ruka v prdeli!}
{3736}{}{moje ruka!}
#
# target hit in torso
#
{3737}{}{I malej harant by to dokázal líp...}
{3738}{}{Aaau!}
{3739}{}{Tohle ti jednou musím vrátit}
{3740}{}{Uff!}
{3741}{}{}
{3742}{}{Sakra!}
{3743}{}{Zakrslej hajzlík!}
{3744}{}{}
{3745}{}{Chchchrrr!}
{3746}{}{Aaau!}
#
# target hit in right leg
#
{3747}{}{Sakra, moje noha}
{3748}{}{}
{3749}{}{Moje koleno!}
#
# target hit in left leg
#
{3750}{}{Sakra, moje noha}
{3751}{}{Tohle tì bude móc mrzet!}
{3752}{}{Moje koleno!}
#
# target hit in eyes
#
{3753}{}{Nic nevidím!}
{3754}{}{Moje oko! Tohle ti dám ještì serat!}
{3755}{}{Aaieeee! Nevidím!}
#
# target hit in groin
#
{3756}{}{Oooooo, moje tøíslo!}
{3757}{}{Tak takhle to chceš?}
{3758}{}{}
{3759}{}{Urp!}
{3760}{}{}
{3761}{}{Ta bolest, to je bolest...}

# 29. Regulator
# This one's better armed than usual. We need back-up, now!
#
#  running away
#
{3800}{}{Potøebuju posily!}
{3801}{}{Pomozte mi nìkdo!}
{3802}{}{Pøeskupit!}
{3803}{}{Zpátky! Zpátky!}
{3804}{}{Rychle odsud! Padáme!}
{3805}{}{Musíme najít nìjakı lepší místo!}
#
# moving in to attack
#
{3806}{}{Nepøítel na dosah!}
{3807}{}{Útoèej!}
{3808}{}{Spuste poplach! Já je zdrím!}
{3809}{}{Máme problém. Nechte to na mì.}
{3810}{}{Jdu je zadret!}
{3811}{}{Vyhledat cíl!}
#
# attacking
#
{3812}{}{Uboáku nemonej!}
{3813}{}{Skonèím jednou provdy tvoje trápení}
{3814}{}{Nejsi nic víc ne zvíøe!}
{3815}{}{Bejt tebou si znova nezaèínám}
{3816}{}{Ty u nikoho otravovat nebudeš}
{3817}{}{S takovejma holomkama nemám slitování!}
{3818}{}{Máš monost se naposledy pomodlit!}
{3819}{}{}
{3820}{}{Je s tebou amen}
{3821}{}{Uvidíme se v pekle}
#
# target being missed
#
{3822}{}{Jseš slabej jak tvoje vlastní chcanky, magore!}
{3823}{}{No tak, ty sráèi, neprotahuj to...}
{3824}{}{}
{3825}{}{Tos posral, slizáku!}
{3826}{}{Copak, snad se nebojíš, posero?}
{3827}{}{Nemysli si, e se nechám zabít jen tak.}
#
# target hit in head (3)
#
{3828}{}{Aaaaaau! No trocha štìstí...}
{3829}{}{Mùj ksicht!}
{3830}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{3831}{}{Aaaaaau! e by...}
{3832}{}{Jedna škrábnutá ruka mì nezastaví!}
{3833}{}{}
#
# target hit in right arm
#
{3834}{}{Aaaaaa! Náhoda...}
{3835}{}{Jedna posraná ruka mì nemùe rozházet!}
{3836}{}{Ten zvuk se mi nelíbí...}
#
# target hit in torso
#
# <no messages here>
#
# target hit in right leg
#
{3837}{}{Aaaa! Dobrá trefa!}
{3838}{}{}
{3839}{}{Mì tu nikdo mrzaèit nebude, kámo.}
#
# target hit in left leg
#
{3840}{}{Aaaaaa! Dobrá trefa!}
{3841}{}{}
{3842}{}{Mì tu nikdo mrzaèit nebude, kámo.}
#
# target hit in eyes
#
{3843}{}{Já jsem slepej!}
{3844}{}{Moje oèi...to je bolest!}
{3845}{}{Nic nevidím!}
#
# target hit in groin
#
{3846}{}{Oooooo, moje koule!}
{3847}{}{Zbabìlci vdycky míøej na koule}
{3848}{}{Sakra, to bolelo!}
{3849}{}{Nemùu....popadnout...dech...}
{3850}{}{Úúúú, ty sadistickej zkurvy....}
{3851}{}{Ty sketo...}

# 30. Adytowner
# They've broken through our defenses! Fall back!
#
#  running away
#
{3900}{}{Potøebuju posily!}
{3901}{}{Pomozte mi nìkdo!}
{3902}{}{}
{3903}{}{Zpátky! Ustupte!}
{3904}{}{Mizíme! Padáme!}
{3905}{}{Pomoc!}
#
# moving in to attack
#
{3906}{}{Za Adytum!}
{3907}{}{Jsme v ohroení!}
{3908}{}{Potøebuju posily!}
{3909}{}{Do toho!}
{3910}{}{Takovı jako ty tu nemáme rádi!}
{3911}{}{Do zbranì!}
#
# attacking
#
{3912}{}{Tohle je za Adytum!}
{3913}{}{Se zvíøatama tu dìláme tohle..!}
{3914}{}{Vítej v pekle, padouchu!}
{3915}{}{Na tvım místì bych to vzdal}
{3916}{}{Ty u nikoho otravovat nebudeš}
{3917}{}{ádnı slitování s padouchama jako ty!}
{3918}{}{Ještì máš èas se pomodlit!}
{3919}{}{}
{3920}{}{Jseš jednou nohou v hrobì}
{3921}{}{Doufám, e sis ivot uil. Teï u moc èasu nemáš}
#
# target being missed
#
{3922}{}{Pro tebe je škoda munice}
{3923}{}{}
{3924}{}{}
{3925}{}{Tak a teï já...}
{3926}{}{Nevyšlo, co...?}
{3927}{}{Nás jen tak nic nerozhází}
#
# target hit in head (3)
#
{3928}{}{Aaaaau. Pøímo do ksichtu}
{3929}{}{Mùj ksicht!}
{3930}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{3931}{}{Aggghh! moje ruka}
{3932}{}{Aauuu, to bolelo!}
{3933}{}{Sakra. To vypadá zle!}
#
# target hit in right arm
#
{3934}{}{Aggghh! Moje ruka}
{3935}{}{Aauuu, to bolelo!}
{3936}{}{Sakra. To vypadá zle}
#
# target hit in torso
#
{3937}{}{Aaau!}
{3938}{}{Uff! To bolelo!}
{3939}{}{Uff! Ne..mù..u...dejchat...}
{3940}{}{Tys mì dostal! Doktora!}
{3941}{}{To nic, to bude dobrı..}
{3942}{}{Áaaa!}
{3943}{}{Aaau! Ksakru!}
{3944}{}{Aauuu, ty sketo!}
{3945}{}{}
{3946}{}{}
#
# target hit in right leg
#
{3947}{}{Aggghh! Dobrej zásah!}
{3948}{}{Sakra, pøesnì do kolena...}
{3949}{}{Mì se nezbavíš, mizero. Au.}
#
# target hit in left leg
#
{3950}{}{Aggghh! Dobrej zásah!}
{3951}{}{Sakra, pøímo do kolena...}
{3952}{}{Mì se nezbavíš bastarde. Au.}
#
# target hit in eyes
#
{3953}{}{Nic nevidím. Pomozte mi nìkdo!}
{3954}{}{Sakra, pøímo do oèí!}
{3955}{}{Já nevidím!}
#
# target hit in groin
#
{3956}{}{Oooooo, kole, moje koule!}
{3957}{}{Yeah, zbabìlci vdycky míøej do koulí}
{3958}{}{Sakra, to bolelo!}
{3959}{}{Ne..mù..u...dejchat...}
{3960}{}{Oooouu. Ty sadistickı prase...}
{3961}{}{Ty kurvo...}

# 31. Generic Follower
# No retreat, no surrender, no slogans.
#
#  running away
#
{4000}{}{Mùe mì nìkdo krejt..?!}
{4001}{}{Pomozte mi nìkdo!}
{4002}{}{Doktora!}
{4003}{}{Zpátky! Zpátky!}
{4004}{}{Ustupte! Zpátky!}
{4005}{}{Pomoc!}
#
# moving in to attack
#
{4006}{}{To vypadá zle.}
{4007}{}{Jsme v ohroení!}
{4008}{}{Máme tu problém!}
{4009}{}{Ještì jednou do útoku!}
{4010}{}{Radši bych chcípnul, ne tì tu trpìl!}
{4011}{}{Zahráváš si na nesprávnım místì!}
#
# attacking
#
{4012}{}{Mìl jsi utéct dokud byl èas}
{4013}{}{Je naèase to skoncovat}
{4014}{}{}
{4015}{}{}
{4016}{}{Další mrtvola na cestì...}
{4017}{}{Tentokrát se tì zbavím napoøád}
{4018}{}{Pomodli se, budeš to potøebovat!}
{4019}{}{}
{4020}{}{}
{4021}{}{Teï u neuteèeš}
#
# target being missed
#
{4022}{}{Takhle nevyhraješ...}
{4023}{}{}
{4024}{}{Na mì nemáš...}
{4025}{}{Teï je øada na mì}
{4026}{}{Nemáš šanci, chápeš?!}
{4027}{}{Nás se nezbavíš}
#
# target hit in head (3)
#
{4028}{}{Aggghh! Pøímo do ksichtu.}
{4029}{}{Mùj ksicht!}
{4030}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{4031}{}{Aggghh! moje ruka}
{4032}{}{Aauuu, to bolelo!}
{4033}{}{Sakra. To vypadá zle.}
#
# target hit in right arm
#
{4034}{}{Aggghh! moje ruka}
{4035}{}{Aauuu, to bolelo!}
{4036}{}{Sakra. To vypadá zle.}
#
# target hit in torso
#
{4037}{}{Aauuu, to bolí...}
{4038}{}{}
{4039}{}{Uff! Nic lepšího neumíš?}
{4040}{}{Aaau! A ty si myslíš, e tohle mì dojme!?}
{4041}{}{Aaau!}
{4042}{}{Aaaa!}
{4043}{}{Uff!}
{4044}{}{Chchchrrr!}
{4045}{}{}
#
# target hit in right leg
#
{4047}{}{Aggghh! Moje noha!}
{4048}{}{Sakra, pøesnì do kolena...}
{4049}{}{Aggghh! Nemùu stát...}
#
# target hit in left leg
#
{4050}{}{Aggghh! Moje noha!}
{4051}{}{Sakra, pøesnì do kolena...}
{4052}{}{Aggghh! Nemùu stát...}
#
# target hit in eyes
#
{4053}{}{Oslepnul jsem! Pomozte mi nìkdo!}
{4054}{}{}
{4055}{}{Nevidím!}
#
# target hit in groin
#
{4056}{}{Oooooouu, moje koule!}
{4057}{}{}
{4058}{}{Sakra!}
{4059}{}{Nemù...u..dejchat...}
{4060}{}{}
{4061}{}{Ty sketo!}

# 32. Follower, Scout
# I don't see anything... wait! Look at the firepower on that mother!
#
#  running away
#
{4100}{}{}
{4101}{}{Pomozte mi nìkdo!}
{4102}{}{}
{4103}{}{Zpátky! Zpátky!}
{4104}{}{Padáme! Padáme!}
{4105}{}{Pomoc!}
#
# moving in to attack
#
{4106}{}{}
{4107}{}{Myslím, e tu máme problém}
{4108}{}{Vyøídím to rychle}
{4109}{}{Oddìláme je radši tady}
{4110}{}{Vypadá to na slušnou palebnou sílu}
{4111}{}{S náma si není radno zahrávat}
#
# attacking
#
{4112}{}{Mìl jsi zdrhnout, dokud byl èas}
{4113}{}{Je èas to skonèit}
{4114}{}{}
{4115}{}{Teï u nebudeš nebezpeènej}
{4116}{}{}
{4117}{}{}
{4118}{}{}
{4119}{}{O jednu havì v Kostnici ménì.}
{4120}{}{}
{4121}{}{Tohle dohraješ do konce}
#
# target being missed
#
{4122}{}{To je tvùj konec}
{4123}{}{}
{4124}{}{}
{4125}{}{A teï zase já..}
{4126}{}{Nemáš šanci!}
{4127}{}{}
#
# target hit in head (3)
#
{4128}{}{Áááááhhh!}
{4129}{}{}
{4130}{}{Mùj ksicht!}
#
# target hit in left arm
#
{4131}{}{Aggghh! Moje ruka}
{4132}{}{Tak tenhle pahejl u mi nebude k nièemu...}
{4133}{}{Sakra. To vypadá zle}
#
# target hit in right arm
#
{4134}{}{Aggghh! Moje ruka}
{4135}{}{Tak tenhle pahejl u mi k nièemu nebude...}
{4136}{}{Sakra. To vypadá zle}
#
# target hit in torso
#
{4137}{}{Aough! Mìl bych na tebe upozornit ostatní}
{4138}{}{Uff! ít, ít, nesmím zgebnout...}
{4139}{}{}
{4140}{}{Uff!}
{4141}{}{Bah!}
{4142}{}{Ack!}
{4143}{}{Au!}
{4144}{}{}
{4145}{}{}
{4146}{}{}
#
# target hit in right leg
#
{4147}{}{Aggghh! Moje noha!}
{4148}{}{Sakra, pøesnì do kolena...}
{4149}{}{Aggghh! Sotva stojím...}
#
# target hit in left leg
#
{4150}{}{Aggghh! Moje noha!}
{4151}{}{Sakra, pøesnì do kolena...}
{4152}{}{Aggghh! Sotva stojím...}
#
# target hit in eyes
#
{4153}{}{Nic nevidím! Moná kdybych si utøel tu krev...}
{4154}{}{Sakra, pøímo do oèí!}
{4155}{}{Nic nevidím!}
#
# target hit in groin
#
{4156}{}{}
{4157}{}{Eegah!}
{4158}{}{}
{4159}{}{Ne..mù..u..dejchat...}
{4160}{}{}
{4161}{}{}

# 33. Follower, Guard
# I will hold my position. You get out of here. Go!
#
#  running away
#
{4200}{}{}
{4201}{}{Špatnı krytí, dostal jsem to!}
{4202}{}{}
{4203}{}{}
{4204}{}{Padáme! Padáme!}
{4205}{}{Krejte mì nìkdo!}
#
# moving in to attack
#
{4206}{}{}
{4207}{}{}
{4208}{}{Braòte se!}
{4209}{}{}
{4210}{}{Vetøelci!}
{4211}{}{Právì jste si podepsali rozsudek smrti}
#
# attacking
#
{4212}{}{}
{4213}{}{}
{4214}{}{}
{4215}{}{Po tomhle u nikoho otravovat nebudeš...}
{4216}{}{Tohle bude bolet}
{4217}{}{Oddìlám tì...}
{4218}{}{}
{4219}{}{Pryè s havìtí z Kostnice}
{4220}{}{}
{4221}{}{Tohle si dohraješ do konce}
#
# target being missed
#
{4222}{}{Takhle to nevyhraješ}
{4223}{}{}
{4224}{}{}
{4225}{}{Teï zas já, jo...}
{4226}{}{Právì jsi udìlal velkou chybu}
{4227}{}{}
#
# target hit in head (3)
#
{4228}{}{Sakra!}
{4229}{}{}
{4230}{}{Asi mám zlomenej nos}
#
# target hit in left arm
#
{4231}{}{Moje ruka!}
{4232}{}{}
{4233}{}{To vypadá zle...}
#
# target hit in right arm
#
{4234}{}{Moje ruka!}
{4235}{}{No, tenhle pahejl u mi k nièemu nebude...}
{4236}{}{Sakra! To vypadá zle...}
#
# target hit in torso
#
{4237}{}{}
{4238}{}{}
{4239}{}{}
{4240}{}{Uff!}
{4241}{}{Bah!}
{4242}{}{Ack!}
{4243}{}{Aauuu}
{4244}{}{Uff! To mì mohlo zranit}
{4245}{}{Ksakru, to bolelo!}
{4246}{}{}
#
# target hit in right leg
#
{4247}{}{Moje noha!}
{4248}{}{Sakra, pøesnì do kolena...}
{4249}{}{Aggghh! Sotva stojím...}
#
# target hit in left leg
#
{4250}{}{Moje noha!}
{4251}{}{Sakra, pøesnì do kolena...}
{4252}{}{Aggghh! Sotva stojím...}
#
# target hit in eyes
#
{4253}{}{Nevidím!}
{4254}{}{Sakra, pøímo do oèí!}
{4255}{}{Nic nevidím!}
#
# target hit in groin
#
{4256}{}{Urgh! Moje vejce!}
{4257}{}{}
{4258}{}{To bolelo jak èert!}
{4259}{}{Nemùu..po..padnout..dech...}
{4260}{}{}
{4261}{}{}

# 34. Follower, Leader (aka Nicole)
# Time to do my duty.
#
#  running away
#
{4300}{}{Chtìlo by to najít lepší místo...}
{4301}{}{Špatnı krytí, dostala jsem to...}
{4302}{}{Ještì není po všem!}
{4303}{}{Seberte se....}
{4304}{}{Padáme!}
{4305}{}{Hrubá síla na tenhle boj nestaèí}
#
# moving in to attack
#
{4306}{}{Tohle zvládnu}
{4307}{}{Tohle nebude nic hezkıho!}
{4308}{}{Braòte se!}
{4309}{}{Tenhle sráè nemùe zhatit naše poslání!}
{4310}{}{}
{4311}{}{}
#
# attacking
#
{4312}{}{Z tohohle nemám ádnı potìšení}
{4313}{}{Je èas to ukonèit}
{4314}{}{}
{4315}{}{Nemìl jsi sem chodit}
{4316}{}{Tohle bude bolet}
{4317}{}{Nenechám tì znièit, co jsme vytvoøili}
{4318}{}{}
{4319}{}{Je mi líto, ale musím}
{4320}{}{K èertu s tebou, proè sis musel zaèínat?!}
{4321}{}{Je mi tì líto}
#
# target being missed
#
{4322}{}{Nenechám tì vyhrát}
{4323}{}{Jseš stejnì nemotornej jako krutej}
{4324}{}{My se o sebe umíme postarat}
{4325}{}{A teï zas já...}
{4326}{}{To byla tvoje poslední chyba}
{4327}{}{}
#
# target hit in head (3)
#
{4328}{}{Sakra. To bolí..}
{4329}{}{Lícní kost... To mì pøece nezastaví.}
{4330}{}{Asi mám zlomenej nos}
#
# target hit in left arm
#
{4331}{}{Moje ruka!}
{4332}{}{Hnáta v hajzlu. Nevadí...}
{4333}{}{Sakra! To vypadá zle}
#
# target hit in right arm
#
{4334}{}{Moje ruka!}
{4335}{}{Hnáta v hajzlu. Nevadí...}
{4336}{}{Sakra! To vypadá zle}
#
# target hit in torso
#
{4337}{}{}
{4338}{}{Uff!}
{4339}{}{}
{4340}{}{}
{4341}{}{Chchchrrr!}
{4342}{}{Ack!}
{4343}{}{Aauuu}
{4344}{}{Uff! Mùeš zabít mì, ale NÁS nikdy neporazíš}
{4345}{}{Áaaa!}
{4346}{}{}
#
# target hit in right leg
#
{4347}{}{Moje noha!}
{4348}{}{Sakra, pøesnì do kolena...}
{4349}{}{}
#
# target hit in left leg
#
{4350}{}{Moje noha!}
{4351}{}{Sakra, pøesnì do kolena...}
{4352}{}{Noha v prdeli! Ale to ještì nìjak pùjde..}
#
# target hit in eyes
#
{4353}{}{Nic nevidím! To mì pøece nezastaví...}
{4354}{}{Jsem slepá!}
{4355}{}{Nic nevidím!}
#
# target hit in groin
#
{4356}{}{Aough!!}
{4357}{}{}
{4358}{}{Uff!}
{4359}{}{}
{4360}{}{Eegah!}
{4361}{}{}

# 35. Ripper Leader
# I am the most evil man alive!
#
#  running away
#
{4400}{}{U teï je po tobì!}
{4401}{}{Hned jsem zpátky!}
{4402}{}{Mìj se, bastarde!}
{4403}{}{}
{4404}{}{Tebe si nechám na potom!}
{4405}{}{}
#
# moving in to attack
#
{4406}{}{Urazím ti šišku!}
{4407}{}{Èerstvı maso!}
{4408}{}{}
{4409}{}{}
{4410}{}{Seeru tì...pìknì po kouskách!}
{4411}{}{}
#
# attacking
#
{4412}{}{Vyøeu si z tebe totem!}
{4413}{}{}
{4414}{}{Ještì neumírej, chci tì vidìt trpìt.}
{4415}{}{Urazil jsi Krále Kostnice!}
{4416}{}{}
{4417}{}{Bude z tebe krásná mrtvolka}
{4418}{}{Chcípni! Chcípni! Chcípni!}
{4419}{}{}
{4420}{}{Ještì dneska si na tobì pochutnaj èervi.}
{4421}{}{Stáhnu tì z kùe - zaiva!}
#
# target being missed
#
{4422}{}{}
{4423}{}{No tak, srabe, sna se trochu!}
{4424}{}{No tak, sráèi, chceš se mnou bojovat nebo ne?!}
{4425}{}{Líp to neumíš?}
{4426}{}{Jseš pára z krysího hovna!}
{4427}{}{Já jsem nesmrtelnı!}
#
# target hit in head
#
{4428}{}{}
{4429}{}{}
{4430}{}{Ack!}
#
# target hit in left arm
#
{4431}{}{Miluju køupání kostí}
{4432}{}{}
{4433}{}{Takhle se mi to líbí, kotì!}
#
# target hit in right arm
#
{4434}{}{Moje ruka!}
{4435}{}{}
{4436}{}{Bastard! Moje ruka!}
#
# target hit in torso
#
{4437}{}{Moje prsa!}
{4438}{}{Áaaa! To bylo naposledy!!}
{4439}{}{}
{4440}{}{Chchchrrr!}
{4441}{}{Bah!}
{4442}{}{Ack! Jedna modøina....}
{4443}{}{Aauuu}
{4444}{}{Blázne!}
{4445}{}{Takhle se mùem pošuchovat celej den}
{4446}{}{}
#
# target hit in right leg
#
{4447}{}{Miluju køupání kostí}
{4448}{}{}
{4449}{}{}
#
# target hit in left leg
#
{4450}{}{Moje noha!}
{4451}{}{}
{4452}{}{Ty sketo!}
#
# target hit in eyes
#
{4453}{}{}
{4454}{}{Tvùj strach je stejnì cejtit na sto honù..!}
{4455}{}{Moje oèi! Tomu øíkám boj, kotì..}
#
# target hit in groin
#
{4456}{}{Ack! Moje koule!}
{4457}{}{}
{4458}{}{Oooo! Máš se mnou nìjakı úmysly, kotì?}
{4459}{}{}
{4460}{}{Tak takhle by se ti to líbilo..?}
{4461}{}{}

# 36. Blade, Scout
# Someone's approaching our turf!
#
#  running away (6)
#
{4500}{}{Jako bych tu nikdy nebyl!}
{4501}{}{}
{4502}{}{}
{4503}{}{Ještì jsi nevyhrál!}
{4504}{}{}
{4505}{}{Zatím se mìj}
#
# moving in to attack
#
{4506}{}{Do toho!}
{4507}{}{Je po tobì!}
{4508}{}{Rozhnìval sis špatnou partu!}
{4509}{}{Nikdo se nebude roztahovat na našem území!}
{4510}{}{}
{4511}{}{}
#
# attacking
#
{4512}{}{Já jsem váš pán!}
{4513}{}{Chcípni!}
{4514}{}{Skrèku..}
{4515}{}{Ne nadarmo nám øíkaj Blades}
{4516}{}{Postarám se o tvou závì}
{4517}{}{Bolí??}
{4518}{}{}
{4519}{}{}
{4520}{}{Zabiju tì}
{4521}{}{Je po tobì}
#
# target being missed
#
{4522}{}{...spravedlivìjší ne bùh..!}
{4523}{}{}
{4524}{}{No tak, pøedveï se trochu!}
{4525}{}{Jseš slabej jak nejhorší Rozparovaè!}
{4526}{}{}
{4527}{}{Je vidìt, e nejsi Blade!}
#
# target hit in head
#
{4528}{}{}
{4529}{}{Moje oèi!}
{4530}{}{Aauuu, zlomil mi nos!}
#
# target hit in left arm
#
{4531}{}{Aauuu}
{4532}{}{Aauuu, moje ruka!}
{4533}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in right arm
#
{4534}{}{Aauuu}
{4535}{}{Aauuu, moje ruka!}
{4536}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in torso
#
{4537}{}{Aauuu}
{4538}{}{Aaauuu, moje prsa!}
{4539}{}{Uff! Moje ebra!}
{4540}{}{Áááchhr}
{4541}{}{Ta bolest je k smíchu!}
{4542}{}{Chchchrrr!}
{4543}{}{To jseš tak slabej?}
{4544}{}{}
{4545}{}{Uff!}
{4546}{}{}
#
# target hit in right leg
#
{4547}{}{Aauuu}
{4548}{}{Aaauuu, moje koleno!}
{4549}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{4550}{}{Aauuu}
{4551}{}{Aauuu, moje koleno!}
{4552}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{4553}{}{Jsem slepej!}
{4554}{}{Nevidím!}
{4555}{}{Moje oèi! Ty sráèi...}
#
# target hit in groin
#
{4556}{}{Oooooo, moje koule!}
{4557}{}{Aieee!}
{4558}{}{Sakra, to bolelo}
{4559}{}{Uf!}
{4560}{}{Roztrhám tì na kusy}
{4561}{}{..ne..mù..u..dejchat...}

# 37. Blade, Leader
# Rippers, Followers, Children, I don't care
#
#  running away (6)
#
{4600}{}{}
{4601}{}{}
{4602}{}{Jenom doèasnej odklad, chudáku!}
{4603}{}{Ještì jsi nevyhrál!}
{4604}{}{Ještì se nesmìj. Na tvùj hrob budu chcát já!}
{4605}{}{Ještì se uvidíme}
#
# moving in to attack
#
{4606}{}{}
{4607}{}{}
{4608}{}{Zaplet jsi se do špatnı party!}
{4609}{}{}
{4610}{}{}
{4611}{}{Chcípni!}
#
# attacking
#
{4612}{}{}
{4613}{}{Chcípni!}
{4614}{}{}
{4615}{}{Jak by mìla bejt ta jizva velká?}
{4616}{}{}
{4617}{}{Doufám, e tohle bude bolet}
{4618}{}{}
{4619}{}{}
{4620}{}{Sám si tì pohøbím}
{4621}{}{Je po tobì}
#
# target being missed
#
{4622}{}{Já jsem tvùj pán!}
{4623}{}{}
{4624}{}{No tak, pøedveï se trochu!}
{4625}{}{Jseš mùj!}
{4626}{}{}
{4627}{}{}
#
# target hit in head
#
{4628}{}{To bolelo}
{4629}{}{Moje oèi!}
{4630}{}{Aauuu, mùj nos...}
#
# target hit in left arm
#
{4631}{}{Aauuu}
{4632}{}{Aauuu, moje ruka!}
{4633}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in right arm
#
{4634}{}{Aauuu}
{4635}{}{Aauuu moje ruka!}
{4636}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in torso
#
{4637}{}{Aauuu}
{4638}{}{Aauuu, mùj hrudník!}
{4639}{}{Uff! Moje ebra!}
{4640}{}{Áááchchrrr}
{4641}{}{Ha! Smìšná bolest!}
{4642}{}{Chchchrrr!}
{4643}{}{}
{4644}{}{}
{4645}{}{Uff!}
{4646}{}{Ou, jo, tak to mì probudilo!}
#
# target hit in right leg
#
{4647}{}{Aauuu}
{4648}{}{Aauuu, moje koleno!}
{4649}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{4650}{}{Aauuu}
{4651}{}{Aauuu, moje koleno!}
{4652}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{4653}{}{Jsem slepej!}
{4654}{}{Nic nevidím!}
{4655}{}{Moje oèi! Ty zmrde...}
#
# target hit in groin
#
{4656}{}{Oooooo, moje koule!}
{4657}{}{Aieee!}
{4658}{}{Sakra, to bolelo}
{4659}{}{Ouff!}
{4660}{}{Za to tì roztrhám na kusy}
{4661}{}{Ne-mù-u..dejchat..}

# 38. Gun Runners, Leader
# Are you trying to muscle in on our business?  serious in tone.
#
#  running away
#
{4700}{}{}
{4701}{}{Moná to nebyl nejlepší nápad}
{4702}{}{}
{4703}{}{}
{4704}{}{Pro tohle se zabít nenechám!}
{4705}{}{Moná bych to mìl zabalit...}
#
# moving in to attack
#
{4706}{}{}
{4707}{}{Nìkdo právì udìlal velkou chybu!}
{4708}{}{}
{4709}{}{Kdo si myslíš, e jsi?}
{4710}{}{Je èas se pøedvést}
{4711}{}{}
#
# attacking
#
{4712}{}{}
{4713}{}{Jen to tak zkouším!}
{4714}{}{}
{4715}{}{Jak se ti to líbí?}
{4716}{}{}
{4717}{}{A co tahle palebná síla?}
{4718}{}{Schválnì, co øekneš tomuhle...}
{4719}{}{}
{4720}{}{}
{4721}{}{}
#
# target being missed
#
{4722}{}{}
{4723}{}{}
{4724}{}{Tos neèekal, co...?}
{4725}{}{To byla tvoje poslední chyba}
{4726}{}{Zaèáteèníku}
{4727}{}{Dost slabı...!}
#
# target hit in head
#
{4728}{}{Aauuu, ty jeden zkurvy...}
{4729}{}{Já tì zabiju, ty svinì!}
{4730}{}{Urazím ti šišku!}
#
# target hit in left arm
#
{4731}{}{Au, moje ruka}
{4732}{}{Sakra. A mám po ruce!}
{4733}{}{Moje ruka!}
#
# target hit in right arm
#
{4734}{}{Au, moje ruka}
{4735}{}{Sakra. A mám po ruce!}
{4736}{}{Moje ruka!}
#
# target hit in torso
#
{4737}{}{Aauuu}
{4738}{}{Aauuu, hrudník!}
{4739}{}{Uff! Moje ebra!}
{4740}{}{}
{4741}{}{}
{4742}{}{}
{4743}{}{}
{4744}{}{To by moná chtìlo doktora... }
{4745}{}{}
{4746}{}{Uff!}
#
# target hit in right leg
#
{4747}{}{Sakra, moje noha}
{4748}{}{Za tohle mi zaplatíš!}
{4749}{}{Moje koleno!}
#
# target hit in left leg
#
{4750}{}{Sakra, moje noha}
{4751}{}{Za tohle mi zaplatíš!}
{4752}{}{Moje koleno!}
#
# target hit in eyes
#
{4753}{}{Nic nevidím!}
{4754}{}{Moje oko! Tohle si odpykáš!}
{4755}{}{}
#
# target hit in groin
#
{4756}{}{Oooooou, moje koule!}
{4757}{}{Tak ty takhle...!!}
{4758}{}{}
{4759}{}{Urp!}
{4760}{}{}
{4761}{}{Ty svinì!}

# 39. Adytum, Leader,
# We have a situation, and it's a bad one.
#
#  running away
#
{4800}{}{Potøebuju posily!}
{4801}{}{Pomozte mi nìkdo!}
{4802}{}{Doktora!}
{4803}{}{Zpátky! Zpátky!}
{4804}{}{Padáme! Padáme!}
{4805}{}{Jedem!}
#
# moving in to attack
#
{4806}{}{Tohle zvládnem..}
{4807}{}{Jsme v ohroení!}
{4808}{}{}
{4809}{}{Do útoku!}
{4810}{}{}
{4811}{}{Do zbranì!}
#
# attacking
#
{4812}{}{Za Adytum!}
{4813}{}{Takhle tady nakládáme se zvíøatama!}
{4814}{}{Vítej v pekle, slabochu}
{4815}{}{Uij si tìch posledních pár vteøin...}
{4816}{}{Ty u nikoho srát nebudeš}
{4817}{}{}
{4818}{}{Se mnou sis nemìl zaèínat}
{4819}{}{}
{4820}{}{}
{4821}{}{Je po tobì, lotøe!}
#
# target being missed
#
{4822}{}{}
{4823}{}{Ty jseš ale nebezpeènej, chudáèku...}
{4824}{}{}
{4825}{}{}
{4826}{}{To sis dìlal jenom srandu, viï...?}
{4827}{}{Takhle mì ale nezabiješ...}
#
# target hit in head (3)
#
{4828}{}{Sakra! Pøímo do ksichtu.}
{4829}{}{Mùj ksicht!}
{4830}{}{Mùj nos!}
#
# target hit in left arm
#
{4831}{}{Sakra! Moje ruka}
{4832}{}{Aauuu. To bolelo!}
{4833}{}{Sakra. To vypadá zle}
#
# target hit in right arm
#
{4834}{}{Sakra! Moje ruka}
{4835}{}{Aauuu. To bolelo!}
{4836}{}{Sakra. To vypadá zle}
#
# target hit in torso
#
{4837}{}{Aauuu}
{4838}{}{Aauuu, pøímo do prsou!}
{4839}{}{Uff! Do prsou!}
{4840}{}{Uff!}
{4841}{}{}
{4842}{}{Uff! Pøímo do støev!}
{4843}{}{Áaaa!}
{4844}{}{Aaau!}
{4845}{}{Uff!}
{4846}{}{..potøebuju..vzduch...}
#
# target hit in right leg
#
{4847}{}{Dobrá trefa!}
{4848}{}{Sakra, pøesnì do kolena...}
{4849}{}{Mì se nezbavíš, mizero.}
#
# target hit in left leg
#
{4850}{}{Dobrá trefa!}
{4851}{}{Sakra, pøesnì do kolena...}
{4852}{}{Mì se nezbavíš, mizero.}
#
# target hit in eyes
#
{4853}{}{Sakra, nic nevidím...}
{4854}{}{Sakra, pøímo do oèí!}
{4855}{}{Nevidím!}
#
# target hit in groin
#
{4856}{}{Oooooo, moje koule!}
{4857}{}{}
{4858}{}{Sakra, to bolelo!}
{4859}{}{..ne..mù..u..dejchat...}
{4860}{}{Ty sadistickej zmrde...}
{4861}{}{Ty sketo...}

# 40. Ghoul, Coward
# Maybe someone else should handle this
#
#  running away
{4900}{}{Rychle pryè!}
{4901}{}{}
{4902}{}{Slitování! Slitování!}
{4903}{}{}
{4904}{}{}
{4905}{}{}
#
# moving in to attack
#
{4906}{}{Proè se tohle musí stát právì mnì?!}
{4907}{}{To jsem tu snad sám?}
{4908}{}{Hodila by se òáká pomoc!}
{4909}{}{}
{4910}{}{}
{4911}{}{}
#
# attacking (10)
#
{4912}{}{Neber si to osobnì}
{4913}{}{}
{4914}{}{}
{4915}{}{}
{4916}{}{Zdá se, e ti budu muset ublíit}
{4917}{}{Prosím, spadni hned}
{4918}{}{Snad mì za tohle nezabiješ}
{4919}{}{}
{4920}{}{Je mi nìjak nevolno}
{4921}{}{}
#
# target being missed (6)
#
{4922}{}{Pøeil jsem to! Pøeil!}
{4923}{}{}
{4924}{}{Mìl jsi míøit trochu víc doprava}
{4925}{}{}
{4926}{}{Prostì teï nejsi ve svı kùi.}
{4927}{}{}
#
# target hit in head (3)
#
{4928}{}{Ne do tváøe!}
{4929}{}{Aauuu, moje hlava!}
{4930}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{4931}{}{Au, moje ruka}
{4932}{}{Zlomil jsi mi ruku!}
{4933}{}{Bylo to opravdu nutné?}
#
# target hit in right arm
#
{4934}{}{Au, moje ruka}
{4935}{}{Zlomil jsi mi ruku!}
{4936}{}{Bylo tohle opravdu nutné?}
#
# target hit in torso
#
{4937}{}{Uff!}
{4938}{}{Aauuu, to bolelo! A hodnì!}
{4939}{}{}
{4940}{}{Chchchrrr! Proè mì biješ?!}
{4941}{}{Ack! To bolelo!}
{4942}{}{Áaaa! Nech toho, jo...!}
{4943}{}{Aaau!}
{4944}{}{Uff!}
{4945}{}{Uff!}
{4946}{}{Uff! Chchchrrr! Áaaa! Aauuu! Ouie!}
#
# target hit in right leg
#
{4947}{}{Sakra, moje noha}
{4948}{}{Hej, to bolelo!}
{4949}{}{}
#
# target hit in left leg
#
{4950}{}{Sakra, moje noha}
{4951}{}{Hej, to bolelo!}
{4952}{}{Bylo to opravdu nutné?}
#
# target hit in eyes
#
{4953}{}{Áaaa! Moje sítnice!}
{4954}{}{Moje oko! Ach boe, já jsem snad slepı!}
{4955}{}{Proè je ivot tak tìkı?!}
#
# target hit in groin
#
{4956}{}{Oooooo, moje vejce!}
{4957}{}{Ooouuu! To bolelo!}
{4958}{}{To od tebe nebylo zrovna pìkné.}
{4959}{}{}
{4960}{}{Urp!}
{4961}{}{}

# 41. Ghoul, Normal
#
#  running away (6)
#
{5000}{}{Padám!}
{5001}{}{}
{5002}{}{Aaaaahhhh!}
{5003}{}{}
{5004}{}{}
{5005}{}{Zatím...}
#
# moving in to attack
#
{5006}{}{}
{5007}{}{}
{5008}{}{Nìkdo se tu musí nauèit slušnımu chování}
{5009}{}{Tady asi nìkdo zaøve}
{5010}{}{}
{5011}{}{}
#
# attacking
#
{5012}{}{}
{5013}{}{Chcípni!}
{5014}{}{Smrt a oheò!}
{5015}{}{Posero!}
{5016}{}{Atomovı oheò!}
{5017}{}{}
{5018}{}{Nemìl sis s náma zaèínat}
{5019}{}{Do Kráteru s tebou!}
{5020}{}{Zatluèu ti rakev}
{5021}{}{Jseš mrtvej!}
#
# target being missed
#
{5022}{}{}
{5023}{}{Nic moc}
{5024}{}{}
{5025}{}{U teï si kopej hrob}
{5026}{}{Mì mrtvıho neuvidíš!}
{5027}{}{A cos vùbec èekal?}
#
# target hit in head
#
{5028}{}{}
{5029}{}{Moje oèi!}
{5030}{}{Aauuu}
#
# target hit in left arm
#
{5031}{}{Aauuu}
{5032}{}{Aauuu, moje ruka!}
{5033}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in right arm
#
{5034}{}{Aauuu}
{5035}{}{Aauuu, moje ruka!}
{5036}{}{}
#
# target hit in torso
#
{5037}{}{Aauuu}
{5038}{}{Uff!}
{5039}{}{Au!}
{5040}{}{Gack!}
{5041}{}{Ááaaa!}
{5042}{}{Grrr!}
{5043}{}{}
{5044}{}{Za tohle ti zaiva vyrvu játra!}
{5045}{}{}
{5046}{}{Uff!}
#
# target hit in right leg
#
{5047}{}{Aauuu}
{5048}{}{Aauuu, moje koleno!}
{5049}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{5050}{}{Aauuu}
{5051}{}{Aauuu, moje koleno!}
{5052}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{5053}{}{Jsem slepej!}
{5054}{}{Nevidím!}
{5055}{}{Moje oko!}
#
# target hit in groin
#
{5056}{}{Oooooo, moje koule!}
{5057}{}{Ooo! To bolelo!}
{5058}{}{To nebylo zrovna pøátelskı gesto.}
{5059}{}{}
{5060}{}{Urp!}
{5061}{}{}

# 42.  Ghoul, Brave
# We'll seal your tomb for this.
#
#  running away (6)
#
{5100}{}{Zpátky!}
{5101}{}{Ústup!}
{5102}{}{Pøeskupit!}
{5103}{}{Ještì není po všem!}
{5104}{}{Já se vrátím!}
{5105}{}{Nevidíš nás naposled!}
#
# moving in to attack
#
{5106}{}{}
{5107}{}{}
{5108}{}{Do nìj, vetøelce jednoho!}
{5109}{}{Lidi si zaslouej smrt!}
{5110}{}{}
{5111}{}{}
#
# attacking
#
{5112}{}{Do Kráteru s tebou!}
{5113}{}{}
{5114}{}{Špinavá lidská èeládka!}
{5115}{}{}
{5116}{}{}
{5117}{}{Smrt, smrt!}
{5118}{}{Opeèem si tì na roštu!}
{5119}{}{}
{5120}{}{Je s tebou konec - jednou provdy!}
{5121}{}{Jseš jednou nohou v hrobì}
#
# target being missed
#
{5122}{}{Netrefa...}
{5123}{}{Mì jen tak nikdo nedostane!}
{5124}{}{Jseš úplnı lemro, èlovìèe}
{5125}{}{}
{5126}{}{Takhle to nevyhraješ, blbe}
{5127}{}{}
#
# target hit in head
#
{5128}{}{To bolelo}
{5129}{}{Moje oèi!}
{5130}{}{Aghh!}
#
# target hit in left arm
#
{5131}{}{Aghh!}
{5132}{}{Aauuu, moje ruka!}
{5133}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in right arm
#
{5134}{}{Aghh!}
{5135}{}{Aauuu, moje ruka!}
{5136}{}{Aauuu, zlomil jsi mi ruku!}
#
# target hit in torso
#
{5137}{}{Aauuu}
{5138}{}{Uff!}
{5139}{}{Aaau!}
{5140}{}{Gack!}
{5141}{}{Áaaa!}
{5142}{}{Grrr!}
{5143}{}{Uff! Jste všichni stejnı zmrdi}
{5144}{}{Za tohle si z tvıho péra udìlám hotdog!}
{5145}{}{}
{5146}{}{Uff!}
#
# target hit in right leg
#
{5147}{}{Aghh!}
{5148}{}{Aauuu, moje koleno!}
{5149}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{5150}{}{Aghh!}
{5151}{}{Aauuu, moje koleno!}
{5152}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{5153}{}{Opeèu tì jako selátko!}
{5154}{}{Nevidím!}
{5155}{}{Moje oko!}
#
# target hit in groin
#
{5156}{}{Oooooo, moje koule!}
{5157}{}{Uf!}
{5158}{}{V rakvi ti bude líp!}
{5159}{}{}
{5160}{}{Urp!}
{5161}{}{}

# 43. Super Mutant, Guard
# Humans try to hurt superhumans? Stupid humans!
#
#  running away
#
{5200}{}{Bìte!}
{5201}{}{Mì nedostaneš!}
{5202}{}{Hned jsem zpátky!}
{5203}{}{Oni tì dostanou za mì!}
{5204}{}{Za to mi jednou ošklivì zaplatíš!}
{5205}{}{Vyvolení jsme my, rozumíš? Ty musíš zemøít!}
#
# moving in to attack
#
{5206}{}{Smrt u ti líe paty!}
{5207}{}{Kdo otravuje Vyvolené, ten u nikdy nikoho otravovat nebude!}
{5208}{}{Lidskı zbranì mnì ublíit nemùou!}
{5209}{}{Budeš trpìt, obludo!}
{5210}{}{}
{5211}{}{To jseš tak blbej, e si s námi zaèínáš, nebo co...?}
#
# attacking
#
{5212}{}{}
{5213}{}{Teï u ti nikdo nepomùe!}
{5214}{}{}
{5215}{}{Teï chcípneš bolestnou smrtí!}
{5216}{}{Ty èlovìèí blázne!}
{5217}{}{Tvoje poslední utrpení...}
{5218}{}{}
{5219}{}{A teï si tì vychutnám}
{5220}{}{Nemùeš pøemoct Vyvolené!}
{5221}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{5222}{}{e se vùbec namáháš...!}
{5223}{}{Je tohle všechno, co lidi dokáou?!}
{5224}{}{Jseš horší ne kozí prd!}
{5225}{}{Jseš k smíchu, ty máslo!}
{5226}{}{Copak to bylo?}
{5227}{}{Jsem z Vyvolenıch!}
#
# target hit in head
#
{5228}{}{Áaaaaou! Mùj ksicht!}
{5229}{}{Mùj ksicht! Tohle se ti vrátí!}
{5230}{}{Áaaaaou! Udìlám z tebe sekanou!}
#
# target hit in left arm
#
{5231}{}{Áaaaaou!}
{5232}{}{}
{5233}{}{Áaaaaou! Zlomím ti vaz, ty sketo!}
#
# target hit in right arm
#
{5234}{}{Áaaaaou!}
{5235}{}{}
{5236}{}{Áaaaaou! Zlomím ti vaz, ty sketo!}
#
# target hit in torso
#
{5237}{}{Uff!}
{5238}{}{Grrr!}
{5239}{}{Za tohle tì zabiju!}
{5240}{}{Ty mì pøestaneš srát...!}
{5241}{}{Jseš jen pro smích!}
{5242}{}{Grrr!}
{5243}{}{Oh!}
{5244}{}{Já z tebou zatoèím!}
{5245}{}{Grrr! U mi zaèínáš vadit}
{5246}{}{Agh!}
#
# target hit in right leg
#
{5247}{}{Áaaaaou! Moje noha}
{5248}{}{}
{5249}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in left leg
#
{5250}{}{Áaaaaou! Moje noha}
{5251}{}{}
{5252}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{5253}{}{Áaaaaou! Proklatá lidská rasa, jsem slepej!}
{5254}{}{Áaaaaou! To je bolest! Cos to proved!}
{5255}{}{Áaaaaou! Za tohle tì nakrájím jak salám!}
#
# target hit in groin
#
{5256}{}{Tohle je jenom lidská slabost!}
{5257}{}{}
{5258}{}{Vy lidi jste tak blbı!}
{5259}{}{Proè tam?}
{5260}{}{Budu si tì pomalu opékat, jako selátko}
{5261}{}{}

# 44. Super Mutant, Normal
# Even weakest runt of Chosen better than most powerful human!
#
#  running away
#
{5300}{}{Uteète!}
{5301}{}{Mì nedostanete!}
{5302}{}{Musím odsud}
{5303}{}{}
{5304}{}{Za to mi zaplatíš jindy!}
{5305}{}{Chcípneš - døív nebo pozdìjc!}
#
# moving in to attack
#
{5306}{}{Kdo se opovauje obtìovat Vyvolené?}
{5307}{}{U mì sereš!}
{5308}{}{Lidskı zbranì mì nemùou ublíit!}
{5309}{}{}
{5310}{}{S nepøítelem ádnı slitování!}
{5311}{}{Naseru ti na hrob!}
#
# attacking
#
{5312}{}{}
{5313}{}{Teï u tì nic nezachrání!}
{5314}{}{Teï chcípneš!}
{5315}{}{Posereš se bolestí!}
{5316}{}{Pøetrhnu tì vejpùl!}
{5317}{}{}
{5318}{}{}
{5319}{}{Teï chcípneš}
{5320}{}{Tohle nepøeiješ!}
{5321}{}{Trp!}
#
# target being missed
#
{5322}{}{Jseš slabej jak slepièka!}
{5323}{}{Jseš nemonej...}
{5324}{}{Jseš slabej jako oøezané párátko!}
{5325}{}{}
{5326}{}{Ty troubo úchylnej?}
{5327}{}{Nejseš vùbec k nièemu}
#
# target hit in head
#
{5328}{}{Áaaaaou! Mùj ksicht!}
{5329}{}{Mùj ksicht! Budeš trpìt, ty chlévská mrvo!}
{5330}{}{Áaaaaou! Roztrhám tì na kusy!}
#
# target hit in left arm
#
{5331}{}{Áaaaaou!}
{5332}{}{Aauuu, málem jsi zranil Vyvoleného!}
{5333}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in right arm
#
{5334}{}{Áaaaaou!}
{5335}{}{}
{5336}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in torso
#
{5337}{}{Tak tuhle bolest ti vrátím!}
{5338}{}{Uff!}
{5339}{}{Au!}
{5340}{}{Hmm, to zavání prùserem}
{5341}{}{Grrr! Chcípni zmrde}
{5342}{}{Grrr!}
{5343}{}{I kdybys mì zabil, nikdy nevyhraješ!}
{5344}{}{Grrr!}
{5345}{}{Aauuu, to nebyl dobrej nápad, šoumene}
{5346}{}{}
#
# target hit in right leg
#
{5347}{}{Áaaaaou! Moje noha}
{5348}{}{}
{5349}{}{Áaaaaou! Za tohle ti ukousnu nehty na nohou i s nohama!}
#
# target hit in left leg
#
{5350}{}{Áaaaaou! Moje noha}
{5351}{}{Chceš snad ublíit Vyvolenému?!}
{5352}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{5353}{}{Áaaaaou! Jsem slepej!}
{5354}{}{Áaaaaou! To je bolest. Cos mi to proved?}
{5355}{}{Áaaaaou! To pálí jak èert!}
#
# target hit in groin
#
{5356}{}{To je jenom lidská slabost, trubko!}
{5357}{}{}
{5358}{}{}
{5359}{}{Myslíš, e tohle mi vadí, myšuldo?}
{5360}{}{Toho budeš litovat, úchyle!}
{5361}{}{}

# 45.  Super Mutant, Hostile
# Don't get in my way when I rip the human apart!
#
#  running away
#
{5400}{}{Uteète!}
{5401}{}{Mì nedostanete!}
{5402}{}{Já se vrátím!}
{5403}{}{}
{5404}{}{Odskáèeš si to pozdìjc!}
{5405}{}{Ještì jsem neøekl svoje poslední slovo!}
#
# moving in to attack
#
{5406}{}{Vypadá to, e u si ivota moc neuiješ, co...!}
{5407}{}{}
{5408}{}{Mnì lidskı zbranì nemùou ublíit!}
{5409}{}{Budeš trpìt, móc trpìt!}
{5410}{}{Ty budeš ale pìknı soustíèko!}
{5411}{}{Nemìl sis zaèínat, magore..}
#
# attacking
#
{5412}{}{}
{5413}{}{Teï u ti nikdo nepomùe!}
{5414}{}{Svìtu vládneme MY!}
{5415}{}{Teï chcípneš krutou smrtí!}
{5416}{}{Je po tobì, ty lidskej zmetku!}
{5417}{}{Teï chcípneš...a bude to bolet!!}
{5418}{}{}
{5419}{}{Rozmáznu tì jako paštiku}
{5420}{}{}
{5421}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{5422}{}{e se vùbec namáháš..!}
{5423}{}{Nic lepšího vy lidi neumíte?}
{5424}{}{Jseš horší ne abí trus!}
{5425}{}{}
{5426}{}{}
{5427}{}{MY jsme Vyvolení!}
#
# target hit in head
#
{5428}{}{Áaaaaou! Mùj ksicht!}
{5429}{}{Mùj ksicht! To si odsereš!}
{5430}{}{Áaaaaou! Roztrhám tì na kousky!}
#
# target hit in left arm
#
{5431}{}{Áaaaaou!}
{5432}{}{Tomuhle øíkáš bolest? Dovol, abych se zasmál!}
{5433}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in right arm
#
{5434}{}{Áaaaaou!}
{5435}{}{Tomuhle øíkáš bolest? Smìšnı!}
{5436}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in torso
#
{5437}{}{Mnì bolest nevadí, slabochu!}
{5438}{}{Uff! Zabiju tì!}
{5439}{}{Nesnáším takovı jako ty!}
{5440}{}{}
{5441}{}{Áaaa!}
{5442}{}{Grrr!}
{5443}{}{Au! O tebe se postarám sám!}
{5444}{}{}
{5445}{}{Grrr!}
{5446}{}{Uff!}
#
# target hit in right leg
#
{5447}{}{Áaaaaou! Moje noha}
{5448}{}{Tomuhle øíkáš bolest? Smìšnı!}
{5449}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in left leg
#
{5450}{}{Áaaaaou! Moje noha}
{5451}{}{Tomuhle øíkáš bolest? Smìšnı!}
{5452}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{5453}{}{Áaaaaou! Zasranı lidi! Jsem slepej!}
{5454}{}{Áaaaaou! To je bolest! Cos mi to proved!}
{5455}{}{Áaaaaou! Za to tì ulochtám k smrti!}
#
# target hit in groin
#
{5456}{}{}
{5457}{}{}
{5458}{}{Ty hloupej lidskej odpade!}
{5459}{}{Co to na mì zkoušíš, ty muflone?}
{5460}{}{Co kdybych to samı udìlal já tobì...}
{5461}{}{}

# 46. Super Mutant, Sergeant
# I lead the apocalypse. Corpses to the left, corpses to the right, and death in front of me.
#
#  running away
#
{5500}{}{Mizíme!}
{5501}{}{Mì nedostanete!}
{5502}{}{Nevidíme se naposledy!}
{5503}{}{Ještì není po všem!}
{5504}{}{Tvoje radost nebude trvat dlouho!}
{5505}{}{Vyvolení jsme MY a tebe èeká smrt!}
#
# moving in to attack
#
{5506}{}{Pojï sem, zaèínaj smrtelnı hrátky!}
{5507}{}{}
{5508}{}{Lidskı zbranì nám ublíit nemùou!}
{5509}{}{Budeš trpìt, ty vobejdo!}
{5510}{}{Na nás nemáš ani ty ani nikdo jinı!}
{5511}{}{}
#
# attacking
#
{5512}{}{}
{5513}{}{Nikdo ti nepomùe...}
{5514}{}{Páni jsme tu my!}
{5515}{}{Usmaím si tì k véèe!}
{5516}{}{Zgebni ty lidskej chlupe!}
{5517}{}{Teï chcípneš}
{5518}{}{Tvá krev budi mım vínem!}
{5519}{}{Teï tì rozplácnu jako kravskej lívanec}
{5520}{}{S Vyvolenıma se mìøit nemùeš!}
{5521}{}{Budeš trpìt, zmrde!}
#
# target being missed
#
{5522}{}{Jseš trapnej jako babièèiny baèkorky!}
{5523}{}{}
{5524}{}{Tomuhle øíkáš boj, ty lemro?}
{5525}{}{Jseš k smíchu}
{5526}{}{}
{5527}{}{}
#
# target hit in head
#
{5528}{}{Áaaaaou! Mùj ksicht!}
{5529}{}{Mùj ksicht! Za to mi zaplatíš!}
{5530}{}{Áaaaaou! Roztrhám tì na kousky!}
#
# target hit in left arm
#
{5531}{}{Áaaaaou!}
{5532}{}{Tomuhle øíkáš bolest? Smìšnı!}
{5533}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in right arm
#
{5534}{}{Áaaaaou!}
{5535}{}{}
{5536}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in torso
#
{5537}{}{Mì nedostaneš!}
{5538}{}{Za to z tebe naøeu nudle do polívky!}
{5539}{}{Teï sis nasral do bot!}
{5540}{}{Tak teï jsi mì naštval!}
{5541}{}{Uff!}
{5542}{}{Grrr!}
{5543}{}{Uff! Tenhle boj nepøeiješ}
{5544}{}{}
{5545}{}{Asi nevíš, s kım máš tu èest, ty pablbe}
{5546}{}{Za tohle si z tvı krve uvaøím polívku!}
#
# target hit in right leg
#
{5547}{}{Áaaaaou! Moje noha}
{5548}{}{}
{5549}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in left leg
#
{5550}{}{Áaaaaou! Moje noha}
{5551}{}{}
{5552}{}{Áaaaaou! Za to ti zlomím vaz!}
#
# target hit in eyes
#
{5553}{}{Áaaaaou! Proklatı lidi! Jsem slepej!}
{5554}{}{Áaaaaou! No ale k èemu oèi, zabiju tì i poslepu.}
{5555}{}{Áaaaaou! Z tvejch kostí vyøeu dìtem hraèky!}
#
# target hit in groin
#
{5556}{}{To je jenom lidská slabost!}
{5557}{}{}
{5558}{}{A z toho je vidìt, jak jsi blbej, troubo!}
{5559}{}{Proèpak to asi dìláš?}
{5560}{}{Jak bys nejradši skonal?}
{5561}{}{A takhle sis vyplácnul svojí poslední monost...!}

# 47.  Merchants
# Are you sure that we can't make other arrangements?
#
#  running away
#
{5600}{}{Pryè odsud!}
{5601}{}{Mìj slitování!}
{5602}{}{Nech mì!}
{5603}{}{Pomoc!}
{5604}{}{Aaaaahhhh!}
{5605}{}{Rychle pryè!}
#
# moving in to attack
#
{5606}{}{}
{5607}{}{Nedáváš nám moc na vıbìr!}
{5608}{}{Kdo si myslíš, e jsi?}
{5609}{}{Tady si nikdo vyskakovat nebude...}
{5610}{}{Mohli jsme se dohodnout...}
{5611}{}{To nebylo moudré, pøíteli}
#
# attacking
#
{5612}{}{Nemìl sis zaèínat nìco, na co prostì nemáš}
{5613}{}{Øek sis o to!}
{5614}{}{}
{5615}{}{Sviním jako ty já dìlám tohle...!}
{5616}{}{Vyereš si to do posledního sousta!}
{5617}{}{Jseš na øadì, šášulo!}
{5618}{}{}
{5619}{}{}
{5620}{}{Máš to spoèítanı}
{5621}{}{}
#
# target being missed
#
{5622}{}{Jóóooo!}
{5623}{}{Nevymìnil bych tì ani za svı pouitı slipy}
{5624}{}{Tohle ti zrovna nejde, co..}
{5625}{}{Jseš jenom nemonej strachy podìlanej šašek...}
{5626}{}{Já se ti divím - proè to prostì nezabalíš!}
{5627}{}{}
#
# target hit in head
#
{5628}{}{Do ksichtu ne!}
{5629}{}{}
{5630}{}{Aauuu, moje ucho!}
#
# target hit in left arm
#
{5631}{}{Ou, moje ruka}
{5632}{}{Jdi nìkam!}
{5633}{}{Zlomil jsi mi ruku!}
#
# target hit in right arm
#
{5634}{}{Ou, moje ruka}
{5635}{}{Jdi nìkam!}
{5636}{}{Zlomil jsi mi ruku!}
#
# target hit in torso
#
{5637}{}{Aauuu}
{5638}{}{Uff!}
{5639}{}{Aaau!}
{5640}{}{Gack!}
{5641}{}{Áaaa!}
{5642}{}{}
{5643}{}{Mìl jsem pøeci jen vyjednávat!}
{5644}{}{Uff! Kolik bych tak moh dostat za tvojí mrtvolu..?}
{5645}{}{Aauuu}
{5646}{}{Uff!}
#
# target hit in right leg
#
{5647}{}{Sakra, moje noha}
{5648}{}{Moje kolínko!}
{5649}{}{Aauuu, zlomil jsi mi nohu!}
#
# target hit in left leg
#
{5650}{}{Sakra, moje noha}
{5651}{}{Moje kolínko!}
{5652}{}{Aauuu, zlomil jsi mi nohu!}
#
# target hit in eyes
#
{5653}{}{Nevidím!}
{5654}{}{Ugggh. Mùj ksicht! Moje oèi!}
{5655}{}{Moje oèi! K èertu s tebou...}
#
# target hit in groin
#
{5656}{}{Oooooo, kulièky moje!}
{5657}{}{Oooooo, to bylo úlisnı, smraïochu.}
{5658}{}{Urp!}
{5659}{}{Ne..mù..u..dejchat...}
{5660}{}{}
{5661}{}{To je ale kurevská bolest...}

# 48. Peasant, Hub
# Hey, aren't the taxes bad enough? I don't need you messing up my life too!
#
#  running away
#
{5700}{}{Musím se odsud nìjak dostat!}
{5701}{}{Pryè, pryè!}
{5702}{}{Pomozte mi nìkdo!}
{5703}{}{Teï všichni zahyneme!}
{5704}{}{Jednoho dne se ti to všechno vrátí, abys vìdìl!}
{5705}{}{Tohle mi za to nestojí!}
#
# moving in to attack
#
{5706}{}{Teï u se utéct nedá}
{5707}{}{Kdo tì pustil do Hubu?}
{5708}{}{Hej ty!}
{5709}{}{Takovı jako ty tu nemáme rádi!}
{5710}{}{Tady si nikdo nebude vyskakovat...}
{5711}{}{Kdo si myslíš, e jsi?}
#
# attacking
#
{5712}{}{Co tohle!}
{5713}{}{Jak se ti líbí tohle?}
{5714}{}{A tohle dìláme pakái jako jsi ty!}
{5715}{}{Nìco na památku!}
{5716}{}{Sbohem!}
{5717}{}{}
{5718}{}{Ty jeden obtínej šleme slizkej!}
{5719}{}{}
{5720}{}{Ty zvíøe!}
{5721}{}{Budeš litovat, e jsi sem do Hubu kdy vkroèil!}
#
# target being missed
#
{5722}{}{Jsi horší ne si myslíš}
{5723}{}{}
{5724}{}{Jseš normální myší hovòous}
{5725}{}{}
{5726}{}{Se mnou to nebudeš mít lehkı}
{5727}{}{To byla chyba. Tvoje poslední.}
#
# target hit in head
#
{5728}{}{}
{5729}{}{Áááaamm!}
{5730}{}{Mùj ksicht! Mùj ksicht!}
#
# target hit in left arm
#
{5731}{}{Áááaa! Moje ruka}
{5732}{}{Moje ruka!}
{5733}{}{Á, ruka v jeteli...}
#
# target hit in right arm
#
{5734}{}{Áááaa! Moje ruka}
{5735}{}{Moje ruka!}
{5736}{}{Aaaauvajs, a teï je moje sakra ruka sakra nanic...}
#
# target hit in torso
#
{5737}{}{Aauuu}
{5738}{}{Uff!}
{5739}{}{Aaau!}
{5740}{}{Gack!}
{5741}{}{Áaaa!}
{5742}{}{Grrr!}
{5743}{}{!}
{5744}{}{}
{5745}{}{Aaau!}
{5746}{}{Uff!}
#
# target hit in right leg
#
{5747}{}{Áááaamm! Moje noha}
{5748}{}{Moje noha!}
{5749}{}{Ksakru, hnáta v hajzlu...}
#
# target hit in left leg
#
{5750}{}{Áááaamm! Moje noha}
{5751}{}{Moje noha!}
{5752}{}{Ksakru, hnáta v hajzlu...}
#
# target hit in eyes
#
{5753}{}{Áááaamm! Nevidím!}
{5754}{}{Ksakru! Joj, to to pálí...}
{5755}{}{Moje oko! Za to mi zaplatíš! Do posledního hovna...}
#
# target hit in groin
#
{5756}{}{Oooooo, moje kulky!}
{5757}{}{Oooooooooo!}
{5758}{}{Ne..mù..u..dejchat...}
{5759}{}{}
{5760}{}{To je ale kurva bolest...}
{5761}{}{Sakra, to bolelo!}

# 49. Thief, Hub
# You are taking this rather personally, sir.
#
#  running away
#
{5800}{}{}
{5801}{}{Pryè odsud!}
{5802}{}{Tady u nebudu ani vteøinu!}
{5803}{}{Na tohle mám ještì èas!}
{5804}{}{Honem pryè!}
{5805}{}{Tohle moc slibnì nevypadá...}
#
# moving in to attack
#
{5806}{}{Pojï si, pojï, ty èumáku ošklivej!}
{5807}{}{A máš po srandì!}
{5808}{}{Hej, ty!}
{5809}{}{Ty se mi vùbec nelíbíš, brouku...}
{5810}{}{Sem se nám nikdo vsírat nebude...}
{5811}{}{Kdo si myslíš, e jsi?}
#
# attacking
#
{5812}{}{}
{5813}{}{Jak by se ti líbilo tohle..?}
{5814}{}{Tumáš, pakái!}
{5815}{}{Tohle by tì mohlo uspat!}
{5816}{}{Ty nestoudná bramboro!}
{5817}{}{U tu fakt sereš pøíliš dlouho}
{5818}{}{Dìlá se mi z tebe nanic!}
{5819}{}{Nemùeš ít vìènì..!}
{5820}{}{To zas bude co uklízet, a tì oddìlám}
{5821}{}{Budeš litovat, es sem kdy vkroèil!}
#
# target being missed
#
{5822}{}{Je pro mì poniující bojovat s nulou jako ty}
{5823}{}{}
{5824}{}{Nejsi víc ne mrzká opièka}
{5825}{}{}
{5826}{}{Opravdu ses nemusel obtìovat}
{5827}{}{Ále, chybièka...tvoje poslední!}
#
# target hit in head
#
{5828}{}{Sakra to to bolí!}
{5829}{}{Áááaamm!}
{5830}{}{Mùj ksicht! Mùj krásnej ksichtíèek!}
#
# target hit in left arm
#
{5831}{}{Áááaamm! Moje ruka}
{5832}{}{Moje ruka!}
{5833}{}{Sakra a ruka v prdelce...}
#
# target hit in right arm
#
{5834}{}{Áááaamm! Moje ruka}
{5835}{}{Moje ruka!}
{5836}{}{Sakra a ruka v prdeli...}
#
# target hit in torso
#
{5837}{}{}
{5838}{}{Uff!}
{5839}{}{Aaau!}
{5840}{}{Uff! Moje ebírka}
{5841}{}{Kurva! To bolelo!}
{5842}{}{Aaau! Bolí, bolí!}
{5843}{}{Áaaa!}
{5844}{}{}
{5845}{}{}
{5846}{}{Uff!}
#
# target hit in right leg
#
{5847}{}{Áááaamm! Moje noha}
{5848}{}{Moje noha!}
{5849}{}{Ksakru, noha zkurvená...}
#
# target hit in left leg
#
{5850}{}{Áááaamm! Moje noha}
{5851}{}{Moje noha!}
{5852}{}{Ksakru, a na èem mám teï asi chodit...?}
#
# target hit in eyes
#
{5853}{}{Áááaamm! Nevidím!}
{5854}{}{Ksakru! Jejda, to pálí...}
{5855}{}{Cos to proved!}
#
# target hit in groin
#
{5856}{}{Oooooo, moje koule!}
{5857}{}{Nejsi nic ne mrzkej èervotoè!}
{5858}{}{}
{5859}{}{}
{5860}{}{}
{5861}{}{Sakra, to bolelo!}

# 50.  Mutant, Hub
# We've made a home for ourselves here, and we'll be damned if we just let you walk in and take it away from us.
#
#  running away (6)
#
{5900}{}{Honem odsud!}
{5901}{}{Papa!}
{5902}{}{Aaaaahhhh!}
{5903}{}{Moná pozdìjc, jo...}
{5904}{}{}
{5905}{}{Ještì se uvidíme}
#
# moving in to attack
#
{5906}{}{}
{5907}{}{Braòte svoje domovy!}
{5908}{}{Nìkdo tady potøebuje lekci}
{5909}{}{Á, tady to nìkdo schytá...}
{5910}{}{}
{5911}{}{Na Huby si nikdo otvírat hubu nebude!}
#
# attacking
#
{5912}{}{Tumáš!}
{5913}{}{Chcípni a u tak zùstaò!}
{5914}{}{A je po tobì!}
{5915}{}{Slabochu}
{5916}{}{Ty slizáku jeden!}
{5917}{}{Snad tì tohle bude bolet}
{5918}{}{Nemìl sis zaèínat, blbeèku}
{5919}{}{Do Kráteru s tebou!}
{5920}{}{K èertu s tebou!}
{5921}{}{Jsi mrtvej!}
#
# target being missed
#
{5922}{}{Netrefa, co...!}
{5923}{}{No nic moc teda}
{5924}{}{}
{5925}{}{Netrefíš mì tak snadno}
{5926}{}{Na mì si nepøijdeš!}
{5927}{}{A cos èekal, ty lemro?}
#
# target hit in head
#
{5928}{}{To bolelo}
{5929}{}{Ooo, bolí, lebka mì bolí!}
{5930}{}{Aauuu}
#
# target hit in left arm
#
{5931}{}{Aauuu}
{5932}{}{Aauuu, moje ruka!}
{5933}{}{Aauuu, loket!}
#
# target hit in right arm
#
{5934}{}{Aauuu}
{5935}{}{Aauuu, moje ruka!}
{5936}{}{Aauuu, loket!}

#
# target hit in torso
#
{5937}{}{Aauuu, moje ebra!}
{5938}{}{Uff!}
{5939}{}{Aaau!}
{5940}{}{}
{5941}{}{}
{5942}{}{Aaau! Jdi u nìkam!}
{5943}{}{Áaaa!}
{5944}{}{Aauuu}
{5945}{}{}
{5946}{}{Uff!}
#
# target hit in right leg
#
{5947}{}{Aauuu}
{5948}{}{Aauuu, koleno!}
{5949}{}{Aauuu, moje noha!}
#
#
# target hit in left leg
#
{5950}{}{Aauuu}
{5951}{}{Aauuu, koleno!}
{5952}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{5953}{}{Oslepl jsem!}
{5954}{}{Nic nevidím!}
{5955}{}{Moje oko!}
#
# target hit in groin
#
{5956}{}{Oooooo, koule moje nebohı!}
{5957}{}{Ooo! To to bolelo!}
{5958}{}{}
{5959}{}{}
{5960}{}{Urp!}
{5961}{}{}

# 51. Peasant, Junktown
# Wait a minute. I already pay to three different protection rackets. Be reasonable!
#
#  running away
#
{6000}{}{Vyber si nìkoho jiného!}
{6001}{}{Milost!}
{6002}{}{Pomozte mi nìkdo!}
{6003}{}{Nech mì!}
{6004}{}{Byl to hloupej nápad}
{6005}{}{Pro tohle nechcípnu!}
#
# moving in to attack
#
{6006}{}{Poèkej, a tì dostanu...}
{6007}{}{}
{6008}{}{Hej ty!}
{6009}{}{Ztra se nám z oèí!}
{6010}{}{}
{6011}{}{Znièím tì jak levnı hodinky}
#
# attacking
#
{6012}{}{Co tomu øíkáš!}
{6013}{}{Jak se ti líbí tohle?}
{6014}{}{Zemøi!}
{6015}{}{Mutantí pako!}
{6016}{}{Dám si tì k snídani}
{6017}{}{Psi budou mít co rát}
{6018}{}{}
{6019}{}{Tak jo. Chtìl jsi to sám.}
{6020}{}{}
{6021}{}{}
#
# target being missed
#
{6022}{}{Nejsi moc dobrej}
{6023}{}{Nìco lepšího nepøedvedeš?}
{6024}{}{}
{6025}{}{}
{6026}{}{}
{6027}{}{Ostuda, co}
#
# target hit in head
#
{6028}{}{Sakra!}
{6029}{}{Proè zrovna do hlavy}
{6030}{}{Mùj oblièej! Mùj oblièej!}
#
# target hit in left arm
#
{6031}{}{Áááaamm! Moje ruka}
{6032}{}{Moje ruka!}
{6033}{}{Och, To bolelo!}
#
# target hit in right arm
#
{6034}{}{Áááaamm! Moje ruka}
{6035}{}{Moje ruka!}
{6036}{}{}

#
# target hit in torso
#
{6037}{}{}
{6038}{}{Uff!}
{6039}{}{Aaau!}
{6040}{}{Uff! To bylo do eber}
{6041}{}{Ugh! To bolelo!}
{6042}{}{Sakra! Kálím na tebe!}
{6043}{}{Áaaa!}
{6044}{}{Oh, moje ebra!}
{6045}{}{Aauuu!!}
{6046}{}{Uff!}
#
# target hit in right leg
#
{6047}{}{Áááaamm! Moje noha}
{6048}{}{Moje noha!}
{6049}{}{A je po koleni}
#
# target hit in left leg
#
{6050}{}{Áááaamm! Moje noha}
{6051}{}{Moje noha!}
{6052}{}{A je po koleni}
#
# target hit in eyes
#
{6053}{}{Áááaamm! Mám mejdlo v oèích nebo co!}
{6054}{}{Moje oèi! Moje oèi!}
{6055}{}{Moje oko! Vra mi ho!}
#
# target hit in groin
#
{6056}{}{Oooooo, to nepotìší!}
{6057}{}{Oooooooooo!}
{6058}{}{Ne...mù..u..dıchat...}
{6059}{}{}
{6060}{}{Ta bolest je nesnesitelná...}
{6061}{}{Sakra, to bolelo!}

# 52. Guard, Junktown
# We don't need people making things worse than they already are.
#
#  running away
#
{6100}{}{Padám pryè!}
{6101}{}{Kam jsem to zase vlezl}
{6102}{}{Hele, vyber si nìkoho jinıho!}
{6103}{}{Páèko!}
{6104}{}{Já chci ít!}
{6105}{}{U toho bylo dost}
#
# moving in to attack
#
{6106}{}{Hej ty!}
{6107}{}{První lekce je zdarma}
{6108}{}{Ztra se, dokud je èas!}
{6109}{}{Trochu úcty ke starším!}
{6110}{}{Èas se naplnil...}
{6111}{}{U to nebude dlouho trvat...}
#
# attacking
#
{6112}{}{}
{6113}{}{}
{6114}{}{}
{6115}{}{Líbí?}
{6116}{}{}
{6117}{}{}
{6118}{}{Jak to snášíš...}
{6119}{}{Holoto}
{6120}{}{}
{6121}{}{Je to v tvım zájmu}
#
# target being missed
#
{6122}{}{Oèi po babièce?}
{6123}{}{}
{6124}{}{To byla ubohost}
{6125}{}{Neplatnı pokus}
{6126}{}{Amatére}
{6127}{}{Kdo tì trénoval?}
#
# target hit in head
#
{6128}{}{Aauuu, ty zkurvys...}
{6129}{}{Zlomil jsi mi nos!}
{6130}{}{Urvu ti uši!}
#
# target hit in left arm
#
{6131}{}{Ou, moje ruka}
{6132}{}{To byla ohromná chyba, ty skunku}
{6133}{}{Moje ruka!}
#
# target hit in right arm
#
{6134}{}{Ou, moje ruka}
{6135}{}{To byla ohromná chyba, ty skunku}
{6136}{}{Moje ruka!}
#
# target hit in torso
#
{6137}{}{Urp!}
{6138}{}{Uff!}
{6139}{}{Jau!}
{6140}{}{}
{6141}{}{Ugh! To bolelo!}
{6142}{}{Aaau!}
{6143}{}{Áaaa!}
{6144}{}{Oh, to mi prasklo ebro!}
{6145}{}{Aauuu!! Moje slezina!}
{6146}{}{Uff!}
#
# target hit in right leg
#
{6147}{}{Sakra, moje noha}
{6148}{}{Zabiju tì i v kleèe!}
{6149}{}{To bylo koleno!}
#
# target hit in left leg
#
{6150}{}{Sakra, moje noha}
{6151}{}{Zabiju tì i v kleèe!}
{6152}{}{Koleno!}
#
# target hit in eyes
#
{6153}{}{To u je noc?!}
{6154}{}{Tak to jsem ještì nevidìl}
{6155}{}{Kam jste všichni zmizeli!}
#
# target hit in groin
#
{6156}{}{Oooooo, do voøechù!}
{6157}{}{To bude bolet do pøíštího pátku}
{6158}{}{}
{6159}{}{Uff!}
{6160}{}{}
{6161}{}{}

# 53. Killian
# I ain't happy about killing you, but if you're set on causing trouble, push has gotta come to shove
#
#  running away
#
{6200}{}{Ještì se uvidíme. Sázka?}
{6201}{}{Dáme odvetu. Pozdìji}
{6202}{}{Tohle kolo jsi vyhrál, ale hra ještì nekonèí}
{6203}{}{Najdu si tì jindy}
{6204}{}{Radši se ztra z mìsta}
{6205}{}{Ještì není konec, pøíteli.}
#
# moving in to attack
#
{6206}{}{}
{6207}{}{Teï uvidíš}
{6208}{}{}
{6209}{}{Trochu úcty by neškodilo!}
{6210}{}{}
{6211}{}{}
#
# attacking
#
{6212}{}{}
{6213}{}{}
{6214}{}{}
{6215}{}{A co tohle?}
{6216}{}{}
{6217}{}{}
{6218}{}{Tak se uka...}
{6219}{}{Lùzo}
{6220}{}{}
{6221}{}{Vykopu tì z mìsta}
#
# target being missed
#
{6222}{}{Patøíš do niší ligy}
{6223}{}{}
{6224}{}{Stoupnu si blí}
{6225}{}{Mìl bys to skonèit, dokud ještì iješ}
{6226}{}{Amatére}
{6227}{}{}
#
# target hit in head
#
{6228}{}{Aauuu, kurva to bolí...}
{6229}{}{}
{6230}{}{Tohle ti vrátím!}
#
# target hit in left arm
#
{6231}{}{Ou, moje ruka}
{6232}{}{Zaèínáš mì srát}
{6233}{}{Moje ruka!}
#
# target hit in right arm
#
{6234}{}{Ou, moje ruka}
{6235}{}{Zaèínáš mì srát}
{6236}{}{Moje ruka!}
#
# target hit in torso
#
{6237}{}{Ahh!}
{6238}{}{Uff!}
{6239}{}{Au!}
{6240}{}{Uff! Chceš vidìt mı játra?}
{6241}{}{}
{6242}{}{}
{6243}{}{}
{6244}{}{Oh, moje ebra!}
{6245}{}{}
{6246}{}{}
#
# target hit in right leg
#
{6247}{}{Sakra, moje noha}
{6248}{}{Dobrá trefa. Teï zase já}
{6249}{}{Moje koleno!}
#
# target hit in left leg
#
{6250}{}{Sakra, moje noha}
{6251}{}{Dobrá trefa. Teï zase já}
{6252}{}{Moje koleno!}
#
# target hit in eyes
#
{6253}{}{Nevidím!}
{6254}{}{Trochu se nám sešeøilo}
{6255}{}{}
#
# target hit in groin
#
{6256}{}{Aaaaough!!!}
{6257}{}{}
{6258}{}{Hej, ádnı podpásovky}
{6259}{}{Ufff!}
{6260}{}{}
{6261}{}{}

# 54. Thug, Junktown
#
#  running away
{6300}{}{Musím jít!}
{6301}{}{Vrátím se...}
{6302}{}{Za to jednou zaplatíš!}
{6303}{}{Seru na vás, du domù!}
{6304}{}{Ještì se setkáme!}
{6305}{}{Vyøídíme to pozdìji!}
#
# moving in to attack
#
{6306}{}{}
{6307}{}{Èerstvı maso...}
{6308}{}{Pochèiju tvùj hrob}
{6309}{}{}
{6310}{}{Èas zabíjet!}
{6311}{}{}
#
# attacking (10)
#
{6312}{}{}
{6313}{}{Nestyï se øvát}
{6314}{}{To se ti musí líbit.}
{6315}{}{}
{6316}{}{Psùm budeš chutnat}
{6317}{}{Nikdo nám Junktown nevezme}
{6318}{}{}
{6319}{}{Za tebe bude pøíplatek}
{6320}{}{Pa!}
{6321}{}{Dám si tì ke svaèinì}
#
# target being missed (6)
#
{6322}{}{}
{6323}{}{To je všechno?}
{6324}{}{}
{6325}{}{Pøíštì zkus míøit...}
{6326}{}{}
{6327}{}{Páro z hovna}
#
# target hit in head (3)
#
{6328}{}{Do ksichtu ne!}
{6329}{}{Ah, mám migrénu}
{6330}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{6331}{}{Ou, moje ruka}
{6332}{}{Zlomil jsi mi ruku!}
{6333}{}{}
#
# target hit in right arm
#
{6334}{}{Ou, moje ruka}
{6335}{}{Zlomil jsi mi ruku!}
{6336}{}{}
#
# target hit in torso
#
{6337}{}{Aaau! To bolelo}
{6338}{}{Uff!}
{6339}{}{Aaau!}
{6340}{}{}
{6341}{}{Ugh! To bolelo!}
{6342}{}{}
{6343}{}{Uff!}
{6344}{}{Nakopu tì do eber}
{6345}{}{Ah!}
{6346}{}{Uff!}
#
# target hit in right leg
#
{6347}{}{Sakra, moje noha}
{6348}{}{To mi zaplatíš!}
{6349}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{6350}{}{Sakra, moje noha}
{6351}{}{}
{6352}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{6353}{}{Áaaa!}
{6354}{}{Moje oèi....Moje oèi...}
{6355}{}{Mìl jsem oèi po tátovi, ty parchante}
#
# target hit in groin
#
{6356}{}{Oooooo, to cejtim a v krku!}
{6357}{}{}
{6358}{}{}
{6359}{}{}
{6360}{}{Uff!}
{6361}{}{Aauuu, jen co je seberu, tak tì zabiju!}

# 55. Skulz_Gang
#
#  running away
{6400}{}{Musím jít!}
{6401}{}{Vrátím se...}
{6402}{}{Pomóc!}
{6403}{}{Zdrháme!}
{6404}{}{Ještì to neskonèilo!}
{6405}{}{}
#
# moving in to attack
#
{6406}{}{}
{6407}{}{Èerstvı maso...}
{6408}{}{Vítej v Junktownu. Dobrı místo na umírání!}
{6409}{}{Lebkouni! Do boje!}
{6410}{}{Do práce!}
{6411}{}{}
#
# attacking (10)
#
{6412}{}{Tvoje lebka se mi hodí do sbírky}
{6413}{}{Nestyï se øvát}
{6414}{}{Líbí?}
{6415}{}{}
{6416}{}{Psùm budeš chutnat}
{6417}{}{Kam to bylo?}
{6418}{}{Neumírej ještì}
{6419}{}{}
{6420}{}{Vzdej to!}
{6421}{}{}
#
# target being missed (6)
#
{6422}{}{}
{6423}{}{Na mì nemáš!}
{6424}{}{}
{6425}{}{Uboátko, co takhle zamíøit!}
{6426}{}{}
{6427}{}{Haha!}
#
# target hit in head (3)
#
{6428}{}{Ne do tváøe!}
{6429}{}{To bude jizvièka}
{6430}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{6431}{}{Ou, moje ruka}
{6432}{}{Zlomil jsi mi ruku!}
{6433}{}{Moje ruka! Moje ruka!}
#
# target hit in right arm
#
{6434}{}{Ou, moje ruka}
{6435}{}{Zlomil jsi mi ruku!}
{6436}{}{Moje ruka! Moje ruka!}
#
# target hit in torso (bug fixed by WG: 60xx -> 64xx)
#
{6437}{}{Jau! To bolí!}
{6438}{}{Uff! To si vodsereš}
{6439}{}{Chchchrrr}
{6440}{}{Chchchrrr! Plíce... vzduch...}
{6441}{}{Udìlám si z tvı kùe spacák!}
{6442}{}{Sakra!}
{6443}{}{Uff!}
{6444}{}{To se ti to trefuje!}
{6445}{}{Uff!}
{6446}{}{Aaau!}
#
# target hit in right leg
#
{6447}{}{Sakra, moje noha}
{6448}{}{Berle jsou tak drahı!}
{6449}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{6450}{}{Sakra, moje noha}
{6451}{}{Berle jsou tak drahı!}
{6452}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{6453}{}{Áaaa! Moje oèi!}
{6454}{}{Moje oèi.... ne moje oèi...}
{6455}{}{}
#
# target hit in groin
#
{6456}{}{Oooooo, vejce!}
{6457}{}{}
{6458}{}{}
{6459}{}{}
{6460}{}{Urp!}
{6461}{}{Aauuu, to u se nespraví!}

# 56. Gizmo
#
#  running away
#{6500}{}{Gotta get outta here!}
#{6501}{}{I'll be back...}
#{6502}{}{Help!}
#{6503}{}{Run away!}
#{6504}{}{You ain't heard the last of me!}
#{6505}{}{You're getting payback, I promise!}
#
# moving in to attack
#
{6506}{}{Je po všem, modli se za svou duši!}
{6507}{}{Nemìl ses mi plést do cesty}
{6508}{}{Chtìlo by to zmìnit postoj, sráèi.}
{6509}{}{Gizma naštveš jenom jednou}
{6510}{}{Tvoje hranice u hoøí}
{6511}{}{Je mi z tebe zle}
#
# attacking (10)
#
{6512}{}{Dám si tvoje kosti do sbírky}
{6513}{}{Tak to je tvùj konec}
{6514}{}{Tohle mì baví.}
{6515}{}{Oooo, to asi bolelo!}
{6516}{}{Nevybral sis pìknou smrt}
{6517}{}{Junktown je mùj}
{6518}{}{Neumírej ještì, veèírek teprve zaèíná}
{6519}{}{Roztrhám tì na kusy!}
{6520}{}{Hele, mrtvola!}
{6521}{}{Vyzkoušej tohle!}
#
# target being missed (6)
#
{6522}{}{To bylo velkorysé}
{6523}{}{Mìl sis vzít nìco proti tøesení rukou}
{6524}{}{Jsi vìtší nula ne Killian}
{6525}{}{}
{6526}{}{Poslední rána nic moc!}
{6527}{}{}
#
# target hit in head (3)
#
{6528}{}{}
{6529}{}{Co ses to opováil!}
{6530}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{6531}{}{Ty špinavej, radškorpióny líbající...}
{6532}{}{Zlomil jsi mi ruku!}
{6533}{}{Moje ruka! Moje ruka!}
#
# target hit in right arm
#
{6534}{}{Ty špinavej, radškorpióny líbající...}
{6535}{}{Zlomil jsi mi ruku!}
{6536}{}{Moje ruka! Moje ruka!}
#
# target hit in torso
#
{6537}{}{}
{6538}{}{}
{6539}{}{Uff!}
{6540}{}{Uff! Moje ebra...}
{6541}{}{!}
{6542}{}{Aauuu}
{6543}{}{Áaaa!}
{6544}{}{Tohle si nikdo nesmí dovolit, nikdo!}
{6545}{}{Aauuu!!}
{6546}{}{Uff!}
#
# target hit in right leg
#
{6547}{}{Sakra, moje noha}
{6548}{}{Sotva... stojím...}
{6549}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{6550}{}{Sakra, moje noha}
{6551}{}{Sotva... stojím...}
{6552}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{6553}{}{Uggh! Neeeee!}
{6554}{}{Moje oèi.... Moje oèi...}
{6555}{}{}
#
# target hit in groin
#
{6556}{}{Oooooo, moje pıcha!}
{6557}{}{Ooo! Obstojnì, pitomèe}
{6558}{}{Ooo! U máš rakev?}
{6559}{}{Ooo! Jsi mrtvìjší ne Elvis}
{6560}{}{Urp!}
{6561}{}{Aauuu, zùstanu bezdìtnı!}

# 57. Sellbabies
# Attacking a defenseless woman? Eat my Uzi, you son of a bitch!
#
#  running away
#
{6600}{}{Padáme!}
{6601}{}{Milost!}
{6602}{}{Nech toho!}
{6603}{}{Pomoc!}
{6604}{}{Aaaaahhhh!}
{6605}{}{}
#
# moving in to attack
#
{6606}{}{Hej!}
{6607}{}{}
{6608}{}{Kdo si myslíš, e jsi?}
{6609}{}{Tady se nikdo roztahovat nebude...}
{6610}{}{Je to tvoje volba...}
{6611}{}{Zasranej mátijebe...}
#
# attacking
#
{6612}{}{}
{6613}{}{Øíkal sis o to!}
{6614}{}{}
{6615}{}{}
{6616}{}{Proè ses do toho pouštìl?}
{6617}{}{Chcípni, ty zkurvys...}
{6618}{}{Neber to osobnì...}
{6619}{}{Zaslouíš víc!}
{6620}{}{Budeš toho ještì litovat}
{6621}{}{}
#
# target being missed
#
{6622}{}{Pch!}
{6623}{}{Nemusíš mi nadrovat}
{6624}{}{Jsi opravdová hanba všech støelcù}
{6625}{}{S podobnım jsem chodívala}
{6626}{}{Jsi krátkozrakı od dìtství?}
{6627}{}{}
#
# target hit in head
#
{6628}{}{Mùj ksicht!}
{6629}{}{Ach, moje migréna}
{6630}{}{Já chtìla bıt modelkou!}
#
# target hit in left arm
#
{6631}{}{Ou, moje ruka}
{6632}{}{Chceš mì zchromit!}
{6633}{}{Moje ruka!}
#
# target hit in right arm
#
{6634}{}{Ou, moje ruka}
{6635}{}{Chceš mì zchromit!}
{6636}{}{Zlomil jsi mi ruku!}
#
# target hit in torso
#
{6637}{}{Aauuu}
{6638}{}{!}
{6639}{}{Aauuu. To bolelo!}
{6640}{}{}
{6641}{}{enskım se na prsa nemíøí!}
{6642}{}{Aauuu!}
{6643}{}{Aaau!}
{6644}{}{Aauuu. Ty mròavej...}
{6645}{}{&*$#@!}
{6646}{}{#$#@! Ty vøede!}
#
# target hit in right leg
#
{6647}{}{Moje noha!!!}
{6648}{}{To bylo koleno!}
{6649}{}{Aauuu, do nohy nééé!}
#
# target hit in left leg
#
{6650}{}{Sakra, moje noha}
{6651}{}{To bylo koleno!}
{6652}{}{}
#
# target hit in eyes
#
{6653}{}{Rozmazal jsi mi stíny!}
{6654}{}{Moje.. øasenka... Moje oèi!}
{6655}{}{Parchante! Zabiju tì poslepu!}
#
# target hit in groin
#
{6656}{}{Vìtšinou asi bojuješ s chlapama, co}
{6657}{}{}
{6658}{}{Ty pouštní hovno!}
{6659}{}{Ou, mùj bobr!}
{6660}{}{Ty slizká zrùdo!}
{6661}{}{Jak by se to líbilo tobì!}

# 58. Brotherhood_Initiate
# This is a chance to prove myself!
#
#  running away
#
{6700}{}{Potøebuju posily!}
{6701}{}{Pomozte mi nìkdo!}
{6702}{}{}
{6703}{}{Zpátky!}
{6704}{}{Padáme!}
{6705}{}{Pøíštì!}
#
# moving in to attack
#
{6706}{}{Do boje!}
{6707}{}{}
{6708}{}{}
{6709}{}{Nemìl sis zaèínat}
{6710}{}{Doufám, e mì Paladinové sledují}
{6711}{}{}
#
# attacking
#
{6712}{}{}
{6713}{}{}
{6714}{}{Teï chcípneš!}
{6715}{}{Jak se ti to líbí?}
{6716}{}{Bojuj s nejlepšími, zemøi s ostatními}
{6717}{}{Nezaèínej nìco, co nemùeš dokonèit}
{6718}{}{}
{6719}{}{A co tohle!}
{6720}{}{}
{6721}{}{Uvidíme se v pekle}
#
# target being missed
#
{6722}{}{Pøiznej si to. Jsi mimo.}
{6723}{}{Víc neumíš?}
{6724}{}{Nulo! Bojuj!}
{6725}{}{}
{6726}{}{My jsme mistøi boje!}
{6727}{}{Na Bratrstvo nemáš!}
#
# target hit in head (3)
#
{6728}{}{Za to tì sejmu}
{6729}{}{Aauuu}
{6730}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{6731}{}{Zlomil jsi mi ruku!}
{6732}{}{Zlomená ruka mì nezastaví!}
{6733}{}{}
#
# target hit in right arm
#
{6734}{}{Zlomil jsi mi ruku!}
{6735}{}{Zlomená ruka mì nezastaví!}
{6736}{}{}
#
# target hit in torso
#
{6737}{}{Zlomil jsi mi ebro!}
{6738}{}{Uff!}
{6739}{}{Aaau!}
{6740}{}{Uff! Tak tohle je bolest...}
{6741}{}{Aauuu, na tohle mì nepøipravili!}
{6742}{}{Uf! Jestli padnu, Bratrstvo mì pomstí!}
{6743}{}{Aaau!}
{6744}{}{}
{6745}{}{Oh! Moje ebra! To mi zaplatíš}
{6746}{}{Uff!}
#
# target hit in right leg
#
{6747}{}{Sakra, moje noha}
{6748}{}{Za tohle, kurva, zaplatíš!}
{6749}{}{Mì nezchromíš, jau ...jejda}
#
# target hit in left leg
#
{6750}{}{Sakra, moje noha}
{6751}{}{Za tohle, kurva, zaplatíš!}
{6752}{}{Mì nezchromíš, jau ...jejda.}
#
# target hit in eyes
#
{6753}{}{Ještì jsem nedoèetl jednu kníku!}
{6754}{}{Moje oèi jsou v plamenech!}
{6755}{}{Ještì se uvidíme! Moná!}
#
# target hit in groin
#
{6756}{}{Oooooo, do koulí!}
{6757}{}{}
{6758}{}{Koule v prdeli...}
{6759}{}{Jen...co...popadnu...dech...}
{6760}{}{Za to ti to vrátím!}
{6761}{}{Ty srabe...}

# 59. Brotherhood_Scribe
# I'm no Knight, but I can defend myself
#
#  running away
#
{6800}{}{Posily!}
{6801}{}{U mì to tu nebaví}
{6802}{}{Ústup!}
{6803}{}{Zpátky!}
{6804}{}{Padáme!}
{6805}{}{Tady u nebudu ani minutu}
#
# moving in to attack
#
{6806}{}{}
{6807}{}{}
{6808}{}{Poèkej chvilku...}
{6809}{}{Nemìl ses do toho pouštìt}
{6810}{}{}
{6811}{}{Jdu do toho!}
#
# attacking
#
{6812}{}{Zásah!}
{6813}{}{Mám tì!}
{6814}{}{Teï chcípneš!}
{6815}{}{Líbilo?}
{6816}{}{Vím, jak na tebe}
{6817}{}{To tì asi vyøadí z boje, co}
{6818}{}{}
{6819}{}{Co øíkáš tomuhle!}
{6820}{}{}
{6821}{}{}
#
# target being missed
#
{6822}{}{Nedá se nic dìlat. Jsi nula}
{6823}{}{Víc nepøedvedeš?}
{6824}{}{Ty malej chudáèku}
{6825}{}{To byla ubohost}
{6826}{}{Tvoje neschopnost mì uráí}
{6827}{}{Na Bratrstvo si nepøijdeš!}
#
# target hit in head (3)
#
{6828}{}{Ah!}
{6829}{}{Aauuu}
{6830}{}{Ooo, mùj nos!}
#
# target hit in left arm
#
{6831}{}{To bylo do brnìní}
{6832}{}{Ooo, moje ruka}
{6833}{}{Necítím ruku}
#
# target hit in right arm
#
{6834}{}{To bylo do brnìní}
{6835}{}{Ooo, moje ruka}
{6836}{}{Necítím ruku}
#
# target hit in torso
#
{6837}{}{}
{6838}{}{Uff!}
{6839}{}{}
{6840}{}{Uff! Bolest je moje stará známá}
{6841}{}{}
{6842}{}{Uff! Bratrstvo pomstí mou smrt!}
{6843}{}{Aaau!}
{6844}{}{}
{6845}{}{Oh! Do eber. Proè?}
{6846}{}{Uff!}
#
# target hit in right leg
#
{6847}{}{Sakra, moje noha}
{6848}{}{Ooo, moje koleno!}
{6849}{}{Ou}
#
# target hit in left leg
#
{6850}{}{Sakra, moje noha}
{6851}{}{Ooo, kolenoooo}
{6852}{}{Ou...}
#
# target hit in eyes
#
{6853}{}{Nìco mi spadlo do oka!}
{6854}{}{Kde je vıchod? Nic nevidím!}
{6855}{}{Moje oèi!}
#
# target hit in groin
#
{6856}{}{Oooooo, to šlo pøesnì!}
{6857}{}{Oooooo, asi budu breèet}
{6858}{}{Oooooo, to bolelo...}
{6859}{}{Jen...co...popadnu...dech...}
{6860}{}{Trefil mì sem! Pomoc!}
{6861}{}{To bolelo...}

# 60. Brotherhood_Knight
# I don't need to be a Paladin to take care of you
#
#  running away
#
{6900}{}{Posily!}
{6901}{}{Pro nìco si jenom dojdu}
{6902}{}{Ústup}
{6903}{}{Zpátky!}
{6904}{}{Padáme!}
{6905}{}{U musím jít}
#
# moving in to attack
#
{6906}{}{Do boje!}
{6907}{}{Nechte mi ho!}
{6908}{}{}
{6909}{}{Tak do práce}
{6910}{}{}
{6911}{}{Jdu do toho!}
#
# attacking
#
{6912}{}{Èas skoncovat to je tady}
{6913}{}{Mám tì!}
{6914}{}{Teï chcípneš!}
{6915}{}{Je po všem!}
{6916}{}{Padni k zemi!}
{6917}{}{To by ti mohlo staèit}
{6918}{}{}
{6919}{}{Tak z èeho tì vyrobili?}
{6920}{}{Jen se rozcvièuju}
{6921}{}{Pøichází bouøe}
#
# target being missed
#
{6922}{}{Chybí ti trénink}
{6923}{}{Mimino by to svedlo líp}
{6924}{}{Miø víc vlevo}
{6925}{}{To byla ubohost}
{6926}{}{To mì uráí}
{6927}{}{Dej se na vyšívání}
#
# target hit in head (3)
#
{6928}{}{Ah!}
{6929}{}{Aauuu}
{6930}{}{Ooo}
#
# target hit in left arm
#
{6931}{}{Poškozené brnìní}
{6932}{}{Aauuu}
{6933}{}{Moje ruka je bez citu}
#
# target hit in right arm
#
{6934}{}{Poškozené brnìní}
{6935}{}{Aauuu}
{6936}{}{Moje ruka je bez citu}
#
# target hit in torso
#
{6937}{}{Aauuu, na to jsem pøipraven!}
{6938}{}{Uff!}
{6939}{}{Aaau!}
{6940}{}{Uff! u mi bylo hùø}
{6941}{}{Aauuu, to byla slušná rána!}
{6942}{}{Bratøi mì pomstí!}
{6943}{}{Aaau!}
{6944}{}{Áaaa!}
{6945}{}{}
{6946}{}{Uff!}
#
# target hit in right leg
#
{6947}{}{Sakra, moje noha}
{6948}{}{}
{6949}{}{Ou}
#
# target hit in left leg
#
{6950}{}{Sakra, moje noha}
{6951}{}{}
{6952}{}{Ou...}
#
# target hit in eyes
#
{6953}{}{Aggghh!}
{6954}{}{Oslepil jsi mì! Pomozte mi nìkdo!}
{6955}{}{Moje oèi!}
#
# target hit in groin
#
{6956}{}{Oooooo, to byla surovost!}
{6957}{}{Oooooo, co si teï poènu}
{6958}{}{Oooooo, To bolelo...}
{6959}{}{Ne...mùu...dıchat...}
{6960}{}{Zkus bojovat fér}
{6961}{}{To bolelo...}

# 61. Brotherhood_Paladin
# We are the Elite.
#
#  running away
#
{7000}{}{Ústup! Ústup! Mizíme!}
{7001}{}{Tenhle boj mì nebaví}
{7002}{}{Na chvíli si odskoèím}
{7003}{}{Zabojuju si nìkdy pøíštì}
{7004}{}{Tady u nijak nepomùu}
{7005}{}{}
#
# moving in to attack
#
{7006}{}{Do útoku!}
{7007}{}{Pøicházím na scénu!}
{7008}{}{To bude hned hotovo}
{7009}{}{Tak zase do práce}
{7010}{}{Utišíme toho køiklouna}
{7011}{}{Jdu do toho!}
#
# attacking
#
{7012}{}{Uij si ten zbyteèek ivota, co máš}
{7013}{}{Pozdravuj pøedky!}
{7014}{}{Takhle se to dìlá}
{7015}{}{Je po všem!}
{7016}{}{Útoèíme!}
{7017}{}{Není to špatnej trénink, ale u to ukonèíme}
{7018}{}{}
{7019}{}{Podíváme se, z èeho tì vyrobili}
{7020}{}{Dost zábavy, do práce}
{7021}{}{U teï je mi tì líto}
#
# target being missed
#
{7022}{}{Ty slabochu!}
{7023}{}{Víc neumíš?}
{7024}{}{Ber to trochu serióznì}
{7025}{}{Dívej se pøi míøení na cíl, blbe!}
{7026}{}{Víc chyb u nestihneš}
{7027}{}{Mìl jsi zùstat doma}
#
# target hit in head (3)
#
{7028}{}{Hmm, to bolelo!}
{7029}{}{Uh!}
{7030}{}{Ooo}
#
# target hit in left arm
#
{7031}{}{Znìlo to jako prasknutí}
{7032}{}{Hmm, zásah do pøedloktí}
{7033}{}{Vùbec necejtim ruku.}
#
# target hit in right arm
#
{7034}{}{Znìlo to jako prasknutí}
{7035}{}{Hmm, zásah do pøedloktí}
{7036}{}{Vùbec necejtim ruku.}
#
# target hit in torso
#
{7037}{}{Aauuu, ty pse!}
{7038}{}{Uff!}
{7039}{}{Aaau!}
{7040}{}{Uff! Máma mì tloukla silnìjc}
{7041}{}{Aauuu, ty hulváte!}
{7042}{}{Uff! Bratrstvo mì pomstí!}
{7043}{}{Ovládnu svou bolest stejnì jako tebe!}
{7044}{}{Jo...bolest je mùj starej pøítel}
{7045}{}{}
{7046}{}{To je jenom do masa!}
#
# target hit in right leg
#
{7047}{}{Hmm, jenom do nohy}
{7048}{}{Asi jsem pøišel o nohu!}
{7049}{}{Ou}
#
# target hit in left leg
#
{7050}{}{Hmm, jenom do nohy}
{7051}{}{Asi jsem pøišel o nohu}
{7052}{}{Ou...}
#
# target hit in eyes
#
{7053}{}{Aggghh!}
{7054}{}{Rozsvite!}
{7055}{}{Moje oèi!}
#
# target hit in groin
#
{7056}{}{Oooooo, moje chlouba!}
{7057}{}{Zaèínám toho zmrda nesnášet}
{7058}{}{U mi bylo líp}
{7059}{}{Tak ten pièus míøí pod pás}
{7060}{}{Udìlám z tebe dva}
{7061}{}{ádnı další špinavı údery, prase}

# 62. Brotherhood_Elders
# Insolent pup. Why do you bother us with idle chatter when there are enemies to fight
#
#  running away
#
{7100}{}{Kryjte mì!}
{7101}{}{Neple si to se zbabìlostí, pse.}
{7102}{}{Nìjak se mi nedaøí!}
{7103}{}{Pøíštì, pse.}
{7104}{}{Nemysli si, e je po všem.}
{7105}{}{}
#
# moving in to attack
#
{7106}{}{Do práce.}
{7107}{}{To si musím udìlat všechno sám?}
{7108}{}{To bude hned}
{7109}{}{To bude zajímavé}
{7110}{}{Nìkdo tady udìlal chybu}
{7111}{}{Nìkdo nás chce rušit? Co je to za blba!}
#
# attacking
#
{7112}{}{To je snadné}
{7113}{}{Pøipravit, zacílit, pal...}
{7114}{}{Tak se to dìlá}
{7115}{}{Brzo bude po všem!}
{7116}{}{Do boje!}
{7117}{}{Hezkı trénink, ale u je málo èasu}
{7118}{}{Ukonèíme tvoje trápení}
{7119}{}{Tvrdá lekce pro nìkoho tak mladého}
{7120}{}{Dost blbnutí}
{7121}{}{Dárek od Starších, dítì.}
#
# target being missed
#
{7122}{}{To byl ubohı pokus}
{7123}{}{Trvalo mi 20 let, ne jsem se nauèil takhle uhıbat}
{7124}{}{Vlohy máš, ale trénink nestál za nic}
{7125}{}{Zkušenost nièím nenahradíš}
{7126}{}{Teï... je øada na mì}
{7127}{}{Mìl jsi zùstat doma}
#
# target hit in head (3)
#
{7128}{}{Hmm, to bolelo!}
{7129}{}{Uh!}
{7130}{}{Ooo, dobrá trefa}
#
# target hit in left arm
#
{7131}{}{}
{7132}{}{Hmm, do pøedloktí}
{7133}{}{Necítím ruku. A není to poprvé}
#
# target hit in right arm
#
{7134}{}{}
{7135}{}{Hmm, do pøedloktí}
{7136}{}{Necítím ruku. A není to poprvé}
#
# target hit in torso
#
{7137}{}{To nebolí!}
{7138}{}{Já iju!}
{7139}{}{Já iju! Bolí to, ale iju!}
{7140}{}{Aauuu, teï jsi udìlal velkou chybu}
{7141}{}{Uff! Bratrstvo zvítìzí!}
{7142}{}{Uff! Bratrstvo mì pomstí!}
{7143}{}{Uff!}
{7144}{}{Chchchrrr!}
{7145}{}{To bolelo!}
{7146}{}{Za tohle pocítíš hnìv Bratrstva!}
#
# target hit in right leg
#
{7147}{}{Hmm, do nohy}
{7148}{}{Podlamujou se mi nohy!}
{7149}{}{To nebylo pìkné}
#
# target hit in left leg
#
{7150}{}{Hmm, do nohy}
{7151}{}{Podlamujou se mi nohy}
{7152}{}{To nebylo pìkné}
#
# target hit in eyes
#
{7153}{}{Musím zùstat v klidu, pamatuju si, kam míøit}
{7154}{}{A sakra, do oèí. To rozhodnì nepotìší.}
{7155}{}{Moje oèi!}
#
# target hit in groin
#
{7156}{}{Oooooo, to snad ne!}
{7157}{}{}
{7158}{}{Tohle dítì se mì pokouší vyprovokovat}
{7159}{}{}
{7160}{}{Roztrhnu tì vejpùl}
{7161}{}{Špinavej trik, pse}

# 63. Brotherhood_Rhombus
#
#  running away
#
{7200}{}{Jen si pro nìco dojdu!}
{7201}{}{Volají mì z práce}
{7202}{}{Vydrte!}
{7203}{}{Nechám to na jindy}
{7204}{}{Tady mì to nebaví}
{7205}{}{}
#
# moving in to attack
#
{7206}{}{Poèkej chvíli!}
{7207}{}{Nechte mi ho!}
{7208}{}{Postarám se o toho psa.}
{7209}{}{Dovol, abych tì seznámil s bolestí}
{7210}{}{Drzej malej parchant}
{7211}{}{Do práce!}
#
# attacking
#
{7212}{}{U tu dlouho nepobudeš}
{7213}{}{Unavuješ mì}
{7214}{}{Tak to dokonèíme}
{7215}{}{Je po všem!}
{7216}{}{Takhle to dìlají profíci}
{7217}{}{U mì zaèínáš srát}
{7218}{}{}
{7219}{}{Chtìl jsi to sám, prcku}
{7220}{}{U mì to nebaví}
{7221}{}{Je mi tì skoro líto}
#
# target being missed
#
{7222}{}{Umíš akorát tak hovno}
{7223}{}{Neser mì}
{7224}{}{Mohl bys to brát trochu vánì?}
{7225}{}{Moc dlouhou praxi asi nemáš, co?}
{7226}{}{Slepej trotle}
{7227}{}{Mìl jsi zùstat s mámou}
#
# target hit in head (3)
#
{7228}{}{Hmm, To bolelo!}
{7229}{}{Uh!}
{7230}{}{Ooo}
#
# target hit in left arm
#
{7231}{}{}
{7232}{}{Hmm, do pracky}
{7233}{}{Moje ruka, necítím jí!}
#
# target hit in right arm
#
{7234}{}{}
{7235}{}{Hmm, ruka v øiti}
{7236}{}{Moje ruka, necítím jí!}
#
# target hit in torso
#
{7237}{}{To nebolííííí!}
{7238}{}{Uff! Zrádnej èokle!}
{7239}{}{Uff! Drzá kryso! Tìš se!}
{7240}{}{Aauuu, teï jsi udìlal chybu}
{7241}{}{Aaau!}
{7242}{}{Uff! Bratrstvo pomstí mou smrt}
{7243}{}{Uff!}
{7244}{}{Bolest mi nevadí}
{7245}{}{To bolelo!}
{7246}{}{}
#
# target hit in right leg
#
{7247}{}{To ti nepomùe, stejnì tì zabiju}
{7248}{}{Podlamujou se mi nohy!}
{7249}{}{Ou}
#
# target hit in left leg
#
{7250}{}{To ti nepomùe, stejnì tì zabiju}
{7251}{}{Podlamujou se mi nohy}
{7252}{}{Ou...}
#
# target hit in eyes
#
{7253}{}{Aggghh!}
{7254}{}{Ty parchante!}
{7255}{}{Moje oèi!}
#
# target hit in groin
#
{7256}{}{Drádíš hada bosou nohou, dítì!}
{7257}{}{}
{7258}{}{U mi bylo líp}
{7259}{}{}
{7260}{}{Dostaneš takovou, e druhou nedoèkáš}
{7261}{}{To se od tebe dalo èekat}

# 64. Children, Morpheus
# You actually expect to kill me?
#
#  running away (6)
#
{7300}{}{Byla to zábava, ale u musím jít.}
{7301}{}{To je na nic, sbohem, pitomèe!}
{7302}{}{Nemám tolik èasu}
{7303}{}{Nebudu si s tebou špinit ruce!}
{7304}{}{Nechám to na Nightkinech}
{7305}{}{Sbohem, blázne. U se neuvidíme}
#
# moving in to attack
#
{7306}{}{U dlouho jsem se nehrabal v cizích støevech!}
{7307}{}{Za tohle zemøeš!}
{7308}{}{Nakrmím tebou krysy!}
{7309}{}{Další vyrušení!}
{7310}{}{Tohle ti neprojde!}
{7311}{}{Tohle u pøesahuje všechny hranice}
#
# attacking
#
{7312}{}{Tumáš!}
{7313}{}{Vykoupu tì v Plameni!}
{7314}{}{Takhle krotím zvìø}
{7315}{}{Ty malá kryso!}
{7316}{}{Tvùj øev mi lahodí!}
{7317}{}{Tohle je jen zaèátek, parchante!}
{7318}{}{Jsem Morpheus, vládnu temnou tyèí!}
{7319}{}{Upálím tì!}
{7320}{}{Jsem Morpheus, pán Smrti!}
{7321}{}{Ukonèím tvoje trápení}
#
# target being missed
#
{7322}{}{To je nuda}
{7323}{}{Nebyl jsem léta u Rozparovaèù jen tak pro nic za nic!}
{7324}{}{Smìšné}
{7325}{}{Kurvy se perou líp}
{7326}{}{Jsi po nemoci, nebo je se na víc nezmùeš?}
{7327}{}{Rouhaèi, vyvìsíme si tvoji mrtvolu na vrata}
#
# target hit in head
#
{7328}{}{Agggh!}
{7329}{}{Moje oèi!}
{7330}{}{Náhoda!}
#
# target hit in left arm
#
{7331}{}{Aauuu}
{7332}{}{Aauuu, moje ruka!}
{7333}{}{Aauuu, proklínám tì!}
#
# target hit in right arm
#
{7334}{}{Aauuu}
{7335}{}{Aauuu, moje ruka!}
{7336}{}{Aauuu, máš posranı štìstí!}
#
# target hit in torso
#
{7337}{}{Sakra, máš kliku!}
{7338}{}{Aauuu, já se nevzdám!}
{7339}{}{Jsi vánì jak vìtvièka v ptáku!}
{7340}{}{Teï sis to posral navìky}
{7341}{}{Aauuu}
{7342}{}{Aauu!}
{7343}{}{Uff!}
{7344}{}{Chchchrrr!}
{7345}{}{Oh, To bolelo!}
{7346}{}{Za tohle tì mí stoupenci ukøiují!}
#
# target hit in right leg
#
{7347}{}{Aauuu}
{7348}{}{Aauuu, koleno!}
{7349}{}{Aauuu, Moje noha!}
#
#
# target hit in left leg
#
{7350}{}{Aauuu}
{7351}{}{Aauuu, koleno!}
{7352}{}{Aauuu, moje noha!}
#
# target hit in eyes
#
{7353}{}{Moje oèi! Ty podlá svinì!}
{7354}{}{Utrhám ti hnáty!}
{7355}{}{Agghh! Ty špinavej zkurvys...}
#
# target hit in groin
#
{7356}{}{Oooooo, do vajec!}
{7357}{}{Aieee!}
{7358}{}{To mi zaplatíš!}
{7359}{}{Ouff!}
{7360}{}{To hle tì bude stát ivot!}
{7361}{}{Jak si dovoluješ útoèit na chloubu Morpheuse!}

# 65. Children, Lasher
# Child, you must be disciplined
#
#  running away (6)
#
{7400}{}{U jsem tì potrestal dost, dítì}
{7401}{}{Nemìl bys odporovat, promluvme si o tom.}
{7402}{}{U na tebe nemám èas}
{7403}{}{Nebudu u se s tebou špinit!}
{7404}{}{Nightkinové si s tebou pohrajou}
{7405}{}{Potrestám tì pozdìji}
#
# moving in to attack
#
{7406}{}{Øekl sis o trest}
{7407}{}{Dostaneš lekci}
{7408}{}{Stùj klidnì. Bude to bolet.}
{7409}{}{Nauèím tì zpùsobùm, dítì.}
{7410}{}{Ta dnešní mláde nemá vychování. Je èas to zmìnit.}
{7411}{}{Øekl sis o bolest, pohane.}
#
# attacking
#
{7412}{}{Pocítíš mùj biè a bude se ti líbit!}
{7413}{}{Opláchnu tì Svatım plamenem!}
{7414}{}{Pøiznej, e si sereš do trenek!}
{7415}{}{Zaslouíš trest!}
{7416}{}{Køiè, dítì. V bolesti je vykoupení!}
{7417}{}{Tvá bolest mì netìší.}
{7418}{}{Pøiznej své høíchy! Pøiznej je!}
{7419}{}{Jsi nesvatı pohan. Pøiznej to!}
{7420}{}{Tvùj odpor je jen dalším høíchem. Vzdej se!}
{7421}{}{Podvol se boské moci a budeš oèištìn!}
#
# target being missed
#
{7422}{}{Je vidìt, e jsi mimo}
{7423}{}{U mì to nebaví, ale ještì to vydrím}
{7424}{}{Tebe u se asi spasit nepodaøí.}
{7425}{}{Nedaøí se, co?}
{7426}{}{Kdy takhle útoèíš, zaèínám tì mít rád}
{7427}{}{Vzdej to, to je škoda munice!}
#
# target hit in head
#
{7428}{}{Snáším tvé rány s klidem, dítì.}
{7429}{}{Mì neublííš, mùj mozek je svatı}
{7430}{}{To vydrím}
#
# target hit in left arm
#
{7431}{}{Vùdce je mım štítem. Tohle mì nebolí.}
{7432}{}{Jsem chránìn Všemi svatımi.}
{7433}{}{To nestálo za nic, Plamen mì vyléèí.}
#
# target hit in right arm
#
{7434}{}{Vùdce je mım štítem. Tohle mì nebolí.}
{7435}{}{Jsem chránìn Všemi svatımi.}
{7436}{}{To nestálo za nic, Plamen mì vyléèí.}
#
# target hit in torso
#
{7437}{}{V bolesti je vykoupení, dítì.}
{7438}{}{Chápu bolest. Co ty?}
{7439}{}{Moná mì to bolí, ale je mi to jedno}
{7440}{}{Ještì jednou, to se mi líbilo}
{7441}{}{Vùdce mi dá sílu pøeít}
{7442}{}{Chchchrrr! Jsi jen dítì}
{7443}{}{Mé tìlo jen schránka}
{7444}{}{Nezastavíš Jednotu}
{7445}{}{Cítím tvou bolest, dítì}
{7446}{}{Nezkoušej to znovu!}
#
# target hit in right leg
#
{7447}{}{Po bolesti pøijde vykoupení, mé dítì.}
{7448}{}{Vùdce bude mıma nohama, dítì.}
{7449}{}{Kadé oslabení tìla posílí mou duši.}
#
#
# target hit in left leg
#
{7450}{}{Po bolesti pøijde vykoupení, mé dítì.}
{7451}{}{Vùdce bude mıma nohama, dítì.}
{7452}{}{Kadé oslabení tìla posílí mou duši.}
#
# target hit in eyes
#
{7453}{}{Po bolesti pøijde vykoupení, mé dítì.}
{7454}{}{ádná obì není dost velká.}
{7455}{}{Kadé oslabení tìla posílí mou duši.}
#
# target hit in groin
#
{7456}{}{I kdy je mùj hasiè mìkkı, má duše je tvrdá!}
{7457}{}{Bolest je jen pøedstava slabé mysli, to rozchodím}
{7458}{}{Mé utrpení mì posiluje}
{7459}{}{Ouff!}
{7460}{}{Dokonce i v boji dokazuješ, jakı jsi uboák}
{7461}{}{Tvé høíchy se tímto násobí!}

# 66. Hub, Jain
# Blasphemers must die!
#
#  running away (6)
#
{7500}{}{Èasem z tebe vyenu to zlo!}
{7501}{}{JE na tobì znamení Dìtí!}
{7502}{}{Ještì se uvidíme!}
{7503}{}{Vrátím se, a z tebe bude mrtvola!}
{7504}{}{Necháme to na jindy}
{7505}{}{Ještì to neskonèilo!}
#
# moving in to attack
#
{7506}{}{Potrestáme kacíøe!}
{7507}{}{Smrt nese jméno Svatı Plamen!}
{7508}{}{Jak se opovauješ nás rušit!}
{7509}{}{Musíme tì nauèit zpùsobùm}
{7510}{}{Dìti, zniète vetøelce!}
{7511}{}{To tì zabolí, dítì}
#
# attacking
#
{7512}{}{Tohle je tvùj trest!}
{7513}{}{Kacíø!}
{7514}{}{Klaò se Dìtem!}
{7515}{}{Ve jménu Plamene, zemøi!}
{7516}{}{Pøichází temnota}
{7517}{}{Chystej si míry na rakev!}
{7518}{}{Náruè smrti se otevírá!}
{7519}{}{Nakrmíš Svatı plamen!}
{7520}{}{Trp, blázne!}
{7521}{}{Snad koneènì pochopíš!}

#
# target being missed
#
{7522}{}{Takovou nulu jsem ještì nepotkal}
{7523}{}{Nemùeš mi ublíit.}
{7524}{}{S tímhle u asi nic nenadìláme}
{7525}{}{To bylo urèeno mì?}
{7526}{}{Plamen mì chrání!}
{7527}{}{Mám pøijít blí}
#
# target hit in head
#
{7528}{}{Ty malej parchante!}
{7529}{}{Za to chcípneš pomalu!}
{7530}{}{Aauuu}
#
# target hit in left arm
#
{7531}{}{Vùdce je mi štítem, nic mì nebolí}
{7532}{}{Smrt si tì brzy najde!}
{7533}{}{Aauuu}
#
# target hit in right arm
#
{7534}{}{Vùdce je mi štítem, nic mì nebolí}
{7535}{}{Smrt si tì brzy najde!}
{7536}{}{Aauuu}
#
# target hit in torso
#
{7537}{}{Prase!}
{7538}{}{Aauuu}
{7539}{}{Vztahuješ ruce na svatou osobu!}
{7540}{}{Uff! To ti neprojde}
{7541}{}{Aauuu, potrestám tì za tvé høíchy}
{7542}{}{Aauuu, jsi hovado}
{7543}{}{Och!}
{7544}{}{Vùdce mì ochrání pøed tvımi uboárnami}
{7545}{}{Aauuu}
{7546}{}{Uff!}
#
# target hit in right leg
#
{7547}{}{Vùdce je mım štítem}
{7548}{}{Má krev je obìtí míru}
{7549}{}{Aauuu}
#
#
# target hit in left leg
#
{7550}{}{Po bolesti pøichází odpuštìní, dítì}
{7551}{}{Má krev je obìtí míru}
{7552}{}{Aauuu}
#
# target hit in eyes
#
{7553}{}{Moje oèi!}
{7554}{}{Aggh! Ïáble!}
{7555}{}{Moje oèi jsou v jednom ohni!}
#
# target hit in groin
#
{7556}{}{Ty zrùdo!}
{7557}{}{Tìší tì to?!}
{7558}{}{Utrpení mì posiluje}
{7559}{}{Ouff!}
{7560}{}{Teï se ukazuješ v pìkném svìtle}
{7561}{}{Za své høíchy budeš pykat!}

# 67. Hub, Underground
# You don't understand what you're messing with
#
#  running away
{7600}{}{Na to nemám èas}
{7601}{}{Nemám èas na umírání!}
{7602}{}{Za to zaplatíš!}
{7603}{}{}
{7604}{}{Ještì se uvidíme!}
{7605}{}{Potkáme se jindy!}
#
# moving in to attack
#
{7606}{}{Rozluè se s blízkımi!}
{7607}{}{Vybral sis špatnı osud!}
{7608}{}{Poseru tvùj hrob}
{7609}{}{Koupil sis právì dùm dva metry pod zemí!}
{7610}{}{Krysy se postarají o zbytek!}
{7611}{}{Tvùj ivot pro mì nic neznamená}
#
# attacking (10)
#
{7612}{}{Èas nakrmit èervy!}
{7613}{}{Mrtvej budeš ještì ošklivìjší}
{7614}{}{}
{7615}{}{Jsi na øadì!}
{7616}{}{Za okamik se setkáš s prastrıèkem}
{7617}{}{Povìsím si tì doma na zeï!}
{7618}{}{}
{7619}{}{Za tebe dostanu pøíplatek}
{7620}{}{Chcípneš!}
{7621}{}{Zaèni si kopat hrob}
#
# target being missed (6)
#
{7622}{}{Co to bylo, varovnı vıstøel nebo to líp neumíš?}
{7623}{}{Ty jsi chtìl minout, e jo}
{7624}{}{}
{7625}{}{Tak takhle se míjí cíl, díky, e jsi mi to ukázal.}
{7626}{}{Stoupnu si trochu blí!}
{7627}{}{Chudáku}
#
# target hit in head (3)
#
{7628}{}{}
{7629}{}{Ach, bolí mì hlava}
{7630}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{7631}{}{Ou, moje ruka}
{7632}{}{Zlomil jsi mi ruku!}
{7633}{}{Touhle stejnì nepíšu}
#
# target hit in right arm
#
{7634}{}{Ou, moje ruka}
{7635}{}{Zlomil jsi mi ruku!}
{7636}{}{To byla moje oblíbená ruka!}
#
# target hit in torso
#
{7637}{}{Uff!}
{7638}{}{To bolelo!}
{7639}{}{Zkus to znova!}
{7640}{}{Uff!}
{7641}{}{Chchchrrr!}
{7642}{}{Ou, jebat všechny!}
{7643}{}{Ah, Uff!}
{7644}{}{Aaau!}
{7645}{}{Aaau! To bolelo!}
{7646}{}{Hej! To jsem neèekal!}
#
# target hit in right leg
#
{7647}{}{Sakra, moje noha}
{7648}{}{Za tohle, kurva, zaplatíš!}
{7649}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{7650}{}{Sakra, moje noha}
{7651}{}{Za tohle, kurva, zaplatíš!}
{7652}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{7653}{}{Áaaa! To je najednou šero!}
{7654}{}{Moje oèi.... To ne, moje oèi...}
{7655}{}{Zbabìlá rána!}
#
# target hit in groin
#
{7656}{}{Oooooo, snad mi neupadne!}
{7657}{}{Ooo! Tohle se musím nauèit...}
{7658}{}{To mì bude bolet eštì zejtra}
{7659}{}{Pod pás to neplatí}
{7660}{}{Ufff!}
{7661}{}{Aauuu, za to tì zabiju!}

# 68. Hub, Police
# You're under arrest! I love saying that!
#
#  running away
#
{7700}{}{}
{7701}{}{Asi to nebyl nejlepší nápad}
{7702}{}{Mohli by mì odzbrojit}
{7703}{}{}
{7704}{}{Pro tohle nechcípnu!}
{7705}{}{To je na mì moc}
#
# moving in to attack
#
{7706}{}{Hej ty!}
{7707}{}{Nìkdo si koleduje o problémy}
{7708}{}{Takovı tady nesnášíme!}
{7709}{}{Kdo si myslíš, e jsi?}
{7710}{}{}
{7711}{}{Policie!}
#
# attacking
#
{7712}{}{Co tohle!}
{7713}{}{Mám tì!}
{7714}{}{Lehni si a nohy od sebe}
{7715}{}{Jak se ti to líbí?}
{7716}{}{}
{7717}{}{Tak do toho}
{7718}{}{Myslíš, e vyhraješ? Zamysli se ještì}
{7719}{}{Sráèi}
{7720}{}{Zatıkám tì!}
{7721}{}{Chtìlo by to víc úcty}
#
# target being missed
#
{7722}{}{Nechceš mì tím podplatit, e ne?}
{7723}{}{Já jsem profík}
{7724}{}{Nejsi moc dobrej}
{7725}{}{Poslední chyba, nulo}
{7726}{}{Amatére}
{7727}{}{Kdo tì uèil bojovat, babièka?}
#
# target hit in head
#
{7728}{}{Aauuu, zkurvysy...}
{7729}{}{Za to tì zabiju}
{7730}{}{Narvu ti hlavu do zadku!}
#
# target hit in left arm
#
{7731}{}{Ou, moje ruka}
{7732}{}{Sakra. Moje ruka je zlomená!}
{7733}{}{Moje ruka!}
#
# target hit in right arm
#
{7734}{}{Ou, moje ruka}
{7735}{}{Sakra. Moje ruka, necítím ji!}
{7736}{}{Moje ruka!}
#
# target hit in torso
#
{7737}{}{Jednou mì kousnul mravenec a bolelo to víc!}
{7738}{}{Støílet na dùstojníka je nezákonné!}
{7739}{}{Aaau!}
{7740}{}{Uff!}
{7741}{}{U tì mám plnı zuby!}
{7742}{}{Za to budeš trpìt}
{7743}{}{Ještì jednou a vyøídíme to bez soudu}
{7744}{}{Dìlej to nìkomu jinımu}
{7745}{}{Uff! Vzdej se!}
{7746}{}{}
#
# target hit in right leg
#
{7747}{}{Sakra, moje noha}
{7748}{}{Za tohle, kurva, zaplatíš!}
{7749}{}{Moje koleno!}
#
# target hit in left leg
#
{7750}{}{Sakra, moje noha}
{7751}{}{Za tohle, kurva, zaplatíš!}
{7752}{}{Do jabka!}
#
# target hit in eyes
#
{7753}{}{Kde mám brıle!}
{7754}{}{Moje oko! Vypadám jako ika!}
{7755}{}{Moje oèi, snad to doroste!}
#
# target hit in groin
#
{7756}{}{Oooooo.. on mi upadnul!}
{7757}{}{To do veèera nepøejde}
{7758}{}{Mám ještì prsty!}
{7759}{}{Urp!}
{7760}{}{To bylo osobní!}
{7761}{}{Ksakru, to bolelo}

# 69. Decker
#
#  running away
{7800}{}{Sejdeme se pozdìji!}
{7801}{}{Já se vrátím...}
{7802}{}{Jsi mrtvola, slyšíš!}
{7803}{}{U tì vidím mrtvıho!}
{7804}{}{Ještì o mì uslyšíš!}
{7805}{}{To ti vrátím, slibuju!}
#
# moving in to attack
#
{7806}{}{Je po všem. Dobrou!}
{7807}{}{Nemìl jsi mì nikdy potkat}
{7808}{}{Podívej se na to jinak, blbe}
{7809}{}{Jsi omyl, kterı já napravím}
{7810}{}{Tohle je rychlík do pekla, sráèi}
{7811}{}{Nìkdo tu chcípne}
#
# attacking (10)
#
{7812}{}{Do práce!}
{7813}{}{Tohle jsou moje metody}
{7814}{}{To si uiju}
{7815}{}{To bude bolet!}
{7816}{}{Narazil na špatnıho chlápka}
{7817}{}{Nikdo se mi nebude protivit}
{7818}{}{Doufám, e budeš umírat pomalu}
{7819}{}{Nauè se to jméno: Decker!}
{7820}{}{Konèíme!}
{7821}{}{Jak se ti to líbí!}
#
# target being missed (6)
#
{7822}{}{To bylo ubohé}
{7823}{}{Je toho na tebe moc, co!}
{7824}{}{Asi jsem se hnul, co? Promiò}
{7825}{}{To je nad tvoje síly, viï}
{7826}{}{To byla poslední rána!}
{7827}{}{Nulo}
#
# target hit in head (3)
#
{7828}{}{Moje hlava!}
{7829}{}{Co sis to dovolil!}
{7830}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{7831}{}{Ty špinavej, radškorpióny líbající...}
{7832}{}{Zlomil jsi mi ruku!}
{7833}{}{Moje ruka! Moje ruka!}
#
# target hit in right arm
#
{7834}{}{Ty špinavej, radškorpióny líbající...}
{7835}{}{Zlomil jsi mi ruku!}
{7836}{}{Moje ruka! Moje ruka!}
#
# target hit in torso
#
{7837}{}{Jsi jenom obyèejnej zkurvysyn, víš to?}
{7838}{}{Uff! Jsem slabej na plíce!}
{7839}{}{Aauuu, jsem snad boxovací pytel?}
{7840}{}{Uff!}
{7841}{}{Aauuu}
{7842}{}{Tohle nesnáším, u to nedìlej}
{7843}{}{Uff! Mìl jsi monost pøeít a posral sis jí!}
{7844}{}{Aauuu, to bylo velmi ošklivé}
{7845}{}{Uff! To si budu pamatovat...}
{7846}{}{Chchchrrr! Já... ne... vzduch...}
#
# target hit in right leg
#
{7847}{}{Sakra, moje noha}
{7848}{}{Ooo.... ty špíno!}
{7849}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{7850}{}{Sakra, moje noha}
{7851}{}{Ooo.... ty špíno!}
{7852}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{7853}{}{Vidím jenom krev, samou krev...}
{7854}{}{Moje oèi.... Moje oèi...}
{7855}{}{Kde mám bílou hùl?!}
#
# target hit in groin
#
{7856}{}{Oooooo, pøed chvílí byly dvì!}
{7857}{}{Ooo! Dobrá trefa, hajzle}
{7858}{}{Ooo! Teï sis podepsal ortel, hovado}
{7859}{}{Ooo! Zaiva tì upeèu v Kráteru!}
{7860}{}{Urp!}
{7861}{}{Aauuu, za to chcípneš!}

# 70. Kane
# Mr. Decker says you're a problem.
#
#  running away
{7900}{}{Sejdeme se pozdìji!}
{7901}{}{Já se vrátím...}
{7902}{}{Jsi mrtvola, slyšíš!}
{7903}{}{U tì vidím mrtvıho!}
{7904}{}{Ještì o mì uslyšíš!}
{7905}{}{To ti vrátím, slibuju!}
#
# moving in to attack
#
{7906}{}{Opravuju takovıhle chyby rád}
{7907}{}{Nemìl jsi obtìovat pana Deckera}
{7908}{}{Zmìním tvùj postoj}
{7909}{}{Pan Decker tì nemá rád}
{7910}{}{Koupil sis lístek do pekla}
{7911}{}{Nìkdo tu brzo umøe}
#
# attacking (10)
#
{7912}{}{Tumáš!}
{7913}{}{Dostaneš první lekci zdarma}
{7914}{}{Tohle je vzkaz od Deckera}
{7915}{}{Nìkdo bude škemrat o milost!}
{7916}{}{Vybral sis špatnı lidi}
{7917}{}{Decker tì pozdravuje.}
{7918}{}{U je na omluvy pozdì}
{7919}{}{Nikdo nepoplive Deckera!}
{7920}{}{Smrt!}
{7921}{}{Co øíkáš tomuhle!}
#
# target being missed (6)
#
{7922}{}{To byla ubohost}
{7923}{}{Vedle, vedle, hehehehe!}
{7924}{}{Nauè se míøit}
{7925}{}{Nemáš dneska den, co}
{7926}{}{Na koho jsi míøil?}
{7927}{}{To nebylo dobrı. A bude hùø.}
#
# target hit in head (3)
#
{7928}{}{Píská mi v uších!}
{7929}{}{Oooo...}
{7930}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{7931}{}{Oooo...}
{7932}{}{Zlomil jsi mi ruku!}
{7933}{}{Moje ruka!}
#
# target hit in right arm
#
{7934}{}{Oooo...}
{7935}{}{Zlomil jsi mi ruku!}
{7936}{}{Moje ruka!}
#
# target hit in torso
#
{7937}{}{Uff! Mì tak snadno nedostaneš...}
{7938}{}{Uff! Moje ebra!}
{7939}{}{Aauuu, co to bylo za ránu?}
{7940}{}{Ha! Udìlám si z tvejch zad høištì na piškvorky!}
{7941}{}{Uff! Jste všichni stejní...}
{7942}{}{Uff! Nemohu... dıchat...}
{7943}{}{Aaau!}
{7944}{}{Aauuu. Seru na tì, šmejde!}
{7945}{}{Ach, ráèi...}
{7946}{}{Áaaa! To bylo ebro!}
#
# target hit in right leg
#
{7947}{}{Sakra, moje noha}
{7948}{}{Oooo....}
{7949}{}{Do prdele, moje koleno!}
#
# target hit in left leg
#
{7950}{}{Sakra, moje noha}
{7951}{}{Oooo....}
{7952}{}{Do prdele, moje koleno}
#
# target hit in eyes
#
{7953}{}{Oèi v pièi...}
{7954}{}{Moje oèi....}
{7955}{}{Podlá rána!}
#
# target hit in groin
#
{7956}{}{Oooooo, to bylo do hadièky!}
{7957}{}{Ooo! Tuhle pozornost ti vrátím}
{7958}{}{Ooo! Co tomu øekne moje holka}
{7959}{}{Ooo! To nebylo fér}
{7960}{}{Urp!}
{7961}{}{Aauuu, Chceš mì vykastrovat?}

# 71. Little Kids
# Mommy!
#
#  running away
#
{8000}{}{Táta tì zabije! Poèkej tu, a pøijde!}
{8001}{}{Mamíí!!!}
{8002}{}{Pomozte mi nìkdo!}
{8003}{}{Pomoc!}
{8004}{}{Aaaaahhhh!}
{8005}{}{Uaaaaahhhh!!}
#
# moving in to attack
#
{8006}{}{Hej ty!}
{8007}{}{Nesnáším tì!}
{8008}{}{}
{8009}{}{Jsi nepovedenej mutant!}
{8010}{}{Nìkdo ti dá lekci!}
{8011}{}{Zabiju tì!}
#
# attacking
#
{8012}{}{Padni!}
{8013}{}{Zabiju tì!}
{8014}{}{Ty mutantí nulo!}
{8015}{}{Špíno z Kráteru!}
{8016}{}{Fuj, radši chcípni!}
{8017}{}{Tvou mámu znásilnil potkan!}
{8018}{}{Nakrm èervy!}
{8019}{}{Trochu tì upravím!}
{8020}{}{Hnusáku!}
{8021}{}{Spíš se škorpiónama, fuj. Milenec škorpiónù!}
#
# target being missed
#
{8022}{}{Tvoje máma je z Kráteru!}
{8023}{}{Miø poøádnì!}
{8024}{}{Netrefíš ani dìcko}
{8025}{}{Mám jít blí?!}
{8026}{}{Vedle, bezmozku!}
{8027}{}{Co to mìlo znamenat?}
#
# target hit in head
#
{8028}{}{Mùj oblièej!}
{8029}{}{Oooo, to bolelo...}
{8030}{}{Aauuu, moje ucho!}
#
# target hit in left arm
#
{8031}{}{Ou, moje ruka}
{8032}{}{Oooo, to bolelo...}
{8033}{}{Zlomil jsi mi ruku! Tatííí!}
#
# target hit in right arm
#
{8034}{}{Ou, moje ruka}
{8035}{}{Oooo, to bolelo}
{8036}{}{Zlomil jsi mi ruku! Tatíííí!}
#
# target hit in torso
#
{8037}{}{Aauuu}
{8038}{}{Aauuu. Mami, ten èlovìk mi ubliuje!}
{8039}{}{Aaau! To stálo za to!}
{8040}{}{Aauuu. Bıt vìtší, tak tì zbiju!}
{8041}{}{Ouie! Ouie! Ouie! Mamííííí!}
{8042}{}{Aauuu. Mùj táta je vìtší ne tvùj!}
{8043}{}{Oooo, Budu... bre... èet! Bùùùùù!}
{8044}{}{Aaau!}
{8045}{}{Aauuu}
{8046}{}{Aauuu. Aauuu. Surovèe!}
#
# target hit in right leg
#
{8047}{}{Sakra, moje noha}
{8048}{}{Do kolene!}
{8049}{}{Zlomil jsi mi nohu! Tatííí!}
#
# target hit in left leg
#
{8050}{}{Sakra, moje noha}
{8051}{}{Moje koleno!}
{8052}{}{Zlomil jsi mi nohu! Tatííí!}
#
# target hit in eyes
#
{8053}{}{Aaaaaahhhh!!!}
{8054}{}{Kde jsou všichni?}
{8055}{}{Dneska je òák brzo tma...}
#
# target hit in groin
#
{8056}{}{Oooooo, mùj pindík!}
{8057}{}{Aauuu ty smradlavej krtku!}
{8058}{}{Urp!}
{8059}{}{Nemùu...dıch...dıchat...}
{8060}{}{Ooooo...}
{8061}{}{Bolí, to bolí...}

# 72. Robots
# Target acquired
#
#  running away
#
{8100}{}{Aktivována volba: ústup}
{8101}{}{Taktickı plán: Zpátky}
{8102}{}{Bojové vısledky nízké. Návrat povolen}
{8103}{}{Taktická analıza: doporuèen ústup}
{8104}{}{Nahrávám ústupovı program}
{8105}{}{Návratová sekvence aktivována}
#
# moving in to attack
#
{8106}{}{Cíl vyhledán!}
{8107}{}{Znièit! Znièit!}
{8108}{}{Humanoid nesmí uniknout}
{8109}{}{Znièit vetøelce}
{8110}{}{Bojová sekvence aktivována}
{8111}{}{Nahrávám bojovı program}
#
# attacking
#
{8112}{}{Bojová sekvence aktivována}
{8113}{}{Útok na cíl}
{8114}{}{Aktivuji útoènı mód}
{8115}{}{Vetøelec musí bıt znièen!}
{8116}{}{Volba taktickıch variant hotova}
{8117}{}{Útok zahájen}
{8118}{}{Cíl bude znièen}
{8119}{}{Likvidace nepøítele zahájena}
{8120}{}{Cíl musí bıt znièen}
{8121}{}{Útoèná sekvence zapoèata}
#
# target being missed
#
{8122}{}{Analıza. Obrannı manévr úspìšnı}
{8123}{}{Analıza. Útok neúspìšnı.}
{8124}{}{Útok selhal. Vıpoèet protiúderu}
{8125}{}{Jednotka nepoškozena}
{8126}{}{Pøepoèítávám útoèné schopnosti protivníka}
{8127}{}{Analıza. Objekt chybuje v útoku. Jednotka nezasaena}
#
# target hit in CPU
#
{8128}{}{Varování, chyba procesoru registrována!}
{8129}{}{Varování! Závada procesoru! Jednotka oslabena!}
{8130}{}{Varování! Závada procesoru! Pøesmìrování funkcí!}
#
# target hit in left manipulator
#
{8131}{}{Manipulátor zasaen}
{8132}{}{Zásah do levého manipulátoru. Posuzuji škody}
{8133}{}{Manipulátor zasaen. Pokus o náhradu}
#
# target hit in right manipulator
#
{8134}{}{Manipulátor zasaen}
{8135}{}{Zásah do pravého manipulátoru. Posuzuji škody}
{8136}{}{Manipulátor zasaen. Pokus o náhradu}
#
# target hit in frame
#
{8137}{}{Zásah do trupu. Oprava poškození}
{8138}{}{Zásah do trupu. Aktivovány vnitøní opravy}
{8139}{}{Hlavní tìleso pod palbou}
{8140}{}{Plátování poškozeno}
{8141}{}{Hlavní tìleso pod palbou. Opravuji}
{8142}{}{Jednotka pod palbou}
{8143}{}{Pokus o úhybnı manévr}
{8144}{}{Brzzt!}
{8145}{}{Drobné škody}
{8146}{}{Brzzt!}
#
# target hit in right motivator
#
{8147}{}{Motivátor zasaen}
{8148}{}{Zásah do motivátoru. Posuzuji škody}
{8149}{}{Motivátor zasaen. Pokus o náhradu}
#
# target hit in left motivator
#
{8150}{}{Motivátor zasaen}
{8151}{}{Zásah do motivátoru. Posuzuji škody}
{8152}{}{Motivátor zasaen. Pokus o náhradu}
#
# target hit in sensors
#
{8153}{}{Senzor zasaen! Senzor zasaen!}
{8154}{}{Senzory poškozeny! Senzory poškozeny!}
{8155}{}{Senzorovı systém poškozen, pokus o pøeklenutí}
#
# target hit in regulator
#
{8156}{}{Regulátor poškozen!}
{8157}{}{Regulátor zasaen! Regulátor zasaen!}
{8158}{}{Regulátor zasaen! Pøesmìrování systému!}

# 73. Marcelles
# Nobody trashes my place and gets away with it!
#
#  running away
#
{8200}{}{Pro tohle nechcípnu!}
{8201}{}{Za to ta práce nestojí!}
{8202}{}{Dostaòte ho!}
{8203}{}{Mám po povìsti...}
{8204}{}{Auua!}
{8205}{}{Seru na to!}
#
# moving in to attack
#
{8206}{}{Další tupec!}
{8207}{}{Zašel jsi moc daleko!}
{8208}{}{Mìl jsi jít, dokud byl èas!}
{8209}{}{Pozdì!}
{8210}{}{Tady se mi nikdo obsírat nebude!}
{8211}{}{Hej ty!}
#
# attacking
#
{8212}{}{Tohle dìlám potíistùm!}
{8213}{}{Zhasnìte svìtla...}
{8214}{}{To tì nauèí nedìlat potíe}
{8215}{}{Jsi na øadì!}
{8216}{}{Je po tobì}
{8217}{}{Podíváme se, co sneseš...}
{8218}{}{Sráèi}
{8219}{}{Vzdáváš se?}
{8220}{}{Co tomu øíkáš?}
{8221}{}{Takovı si dávám ke snídani}
#
# target being missed
#
{8222}{}{To mìl bejt varovnej vıstøel?!}
{8223}{}{Nejsi jen blbec, jsi neschopnej blbec!}
{8224}{}{Ty uboáku!}
{8225}{}{Víc toho neumíš?}
{8226}{}{Tímhle mì nesbalíš, brouku}
{8227}{}{Daøí se ti takhle poøád, nebo to byla vıjimka?}
#
# target hit in head
#
{8228}{}{Zlomil jsi mi nos!}
{8229}{}{Nepotøebuju slyšet}
{8230}{}{Sakra! To bolelo!}
#
# target hit in left arm
#
{8231}{}{Ou, moje ruka}
{8232}{}{Mùeš mì zmrzaèit, ale prdel ti stejnì nakopu}
{8233}{}{To byla chyba}
#
# target hit in right arm
#
{8234}{}{Ou, moje ruka}
{8235}{}{Mùeš mì zmrzaèit, ale prdel ti stejnì nakopu}
{8236}{}{To byla chyba}
#
# target hit in torso
#
{8237}{}{Aauuu}
{8238}{}{To byla chyba}
{8239}{}{Uff!}
{8240}{}{Aauuu. Jak chceš!}
{8241}{}{Aauuu. Teï u to beru osobnì}
{8242}{}{Uff!}
{8243}{}{Áaaa!}
{8244}{}{Au!}
{8245}{}{Uff! Mám tady brokovnici a ...}
{8246}{}{Gulp!}
#
# target hit in right leg
#
{8247}{}{Zase zlomená noha, to snad ne...}
{8248}{}{Mùeš mì zmrzaèit, ale prdel ti stejnì nakopu}
{8249}{}{To byla chyba}
#
# target hit in left leg
#
{8250}{}{Zase zlomená noha, to snad ne...}
{8251}{}{Mùeš mì zmrzaèit, ale prdel ti stejnì nakopu}
{8252}{}{To byla chyba}
#
# target hit in eyes
#
{8253}{}{Kam se podìlo slunce?!}
{8254}{}{Jsem ráda, e na tebe nevidím!}
{8255}{}{Aauuu, šastná trefa...}
#
# target hit in groin
#
{8256}{}{Oooooo, do slabin!}
{8257}{}{To bylo trochu osobní!}
{8258}{}{No tak, ještì se neznáme tak dlouho}
{8259}{}{Já jsem enská, ty tupèe.}
{8260}{}{U holky to tolik nevadí, blbe}
{8261}{}{Uff!}

# 74. Rats
# Squeak!
#
#  running away
#
{8300}{}{Písk!}
#
# target being missed
#
{8301}{}{Písk!!}
#
# target hit in torso
#
{8302}{}{Písk!}
#
# target hit in groin
#
{8303}{}{Pííísk}

# 75. Ian
# former caravan guard
#
#  running away
#
{8400}{}{Èas vypadnout jinam!}
{8401}{}{Auuua!}
{8402}{}{Zpátky!}
#
# moving in to attack
#
{8403}{}{Tohle tì bude mrzet víc ne mì.}
{8404}{}{Obul jsem si svoje oblíbenı rozkopávaèky prdelí.}
{8405}{}{Skoncujeme to hned.}
#
# attacking
#
{8406}{}{Uij si to.}
{8407}{}{Co tohle.}
{8408}{}{Dostal jsem tì!}
#
# target being missed
#
{8409}{}{Nulo!}
{8410}{}{Sna se víc!}
#
# target hit in head
#
{8411}{}{Ksakru, to bolelo!}
{8412}{}{Zlomil jsi mi nos!}
#
# target hit in left arm
#
{8413}{}{Agh! Zlomil jsi mi ruku!}
{8414}{}{Moje ruka je v kıblu!}
#
# target hit in right arm
#
{8415}{}{Agh! Zlomil jsi mi ruku!}
{8416}{}{Moje ruka je v kıblu!}
#
# target hit in torso
#
{8417}{}{Uff!}
{8418}{}{Áaaa!}
{8419}{}{Za to zaplatíš...}
{8420}{}{No tak, zkus to znova!}
#
# target hit in right leg
#
{8421}{}{Aauuu. Zlomil jsi mi nohu!}
{8422}{}{Uch! Moje koleno!}
#
# target hit in left leg
#
{8423}{}{Aauuu. Zlomil jsi mi nohu!}
{8424}{}{Uch! Moje koleno!}
#
# target hit in eyes
#
{8425}{}{Aah! Kde se vzala ta mlha!}
{8426}{}{Sundejte mi z hlavy ten pytel!}
#
# target hit in groin
#
{8427}{}{Oooohhh...}

# 76. Tycho
# Desert ranger
#
#  running away
#
{8500}{}{Èas na taktickı ústup.}
#
# moving in to attack
#
{8501}{}{To bude hned.}
{8502}{}{Do práce.}
#
# attacking
#
{8503}{}{Nakrmím tì olovem.}
{8504}{}{Pøeju krásnej den.}
{8505}{}{Nìco tu pro tebe mám.}
#
# target being missed
#
{8506}{}{Skoro}
{8507}{}{Blízko, ale eštì to trénuj.}
#
# target hit in head
#
{8508}{}{Ou. Dobrá trefa.}
{8509}{}{Uff}
{8510}{}{Další kousek ucha v hajzlu . . .}
{8511}{}{Ksakru, fo byl mùj fub...}
#
# target hit in left arm
#
{8512}{}{Uff}
{8513}{}{Tu ruku jsem stejnì nepotøeboval.}
#
# target hit in right arm
#
{8514}{}{Ou}
{8515}{}{Sakra, touhle jsem se rád šoural v nose}
#
# target hit in torso
#
{8516}{}{Ou.}
{8517}{}{Ksakru, to bylo ebro.}
{8518}{}{Jestli mì chceš zabít, tref se do hlavy.}
#
# target hit in right leg
#
{8519}{}{Moná mì zbrzdíš, ale stejnì tì dostanu.}
{8520}{}{Nohu u jsem zlomenou mìl.}
#
# target hit in left leg
#
{8521}{}{Moná mì zbrzdíš, ale stejnì tì dostanu.}
{8522}{}{Nohu u jsem zlomenou mìl.}
#
# target hit in eyes
#
{8523}{}{Kde se schováváš.}
{8524}{}{Zabije tì slepec, není ti hanba.}
#
# target hit in groin
#
{8525}{}{Ugh! Øeknìme remíza?!}
{8526}{}{Oh, moje koule...}
{8527}{}{To bolelo.}

# 77. Vault Dwellers
# We just want to live in peace - and, oh, why did you come back?
#
#  running away
#
{8600}{}{Musím jít}
{8601}{}{Mám nìco dùleitìjšího}
{8602}{}{Co je to s tebou?}
{8603}{}{Pomozte mi nìkdo!}
{8604}{}{Tohle není moje hobby}
{8605}{}{Mùj boe, to ne!}
#
# moving in to attack
#
{8606}{}{Zrádèe!}
{8607}{}{To snad není pravda!}
{8608}{}{Musel jsi venku zešílet!}
{8609}{}{Zešílel jsi?!}
{8610}{}{Braòte Vault!}
{8611}{}{Byl jsi mùj pøítel!}
#
# attacking
#
{8612}{}{Nemìl ses vracet}
{8613}{}{A to jsme bıvali pøátelé!}
{8614}{}{Nemìl jsi chodit ven}
{8615}{}{Ahoj, pøíteli}
{8616}{}{Zbavím tì toho utrpení}
{8617}{}{Zbavím tì toho utrpení}
{8618}{}{Tohle mì nijak netìší}
{8619}{}{Zešílel jsi v poušti?!}
{8620}{}{Musím to udìlat}
{8621}{}{Jsi parchant a zrádce}
#
# target being missed
#
{8622}{}{Mimo, a o dost}
{8623}{}{Za mlada jsi byl šikovnìjší}
{8624}{}{Nezmìnil ses, poøád neumíš míøit}
{8625}{}{Tohle ti ještì moc nejde}
{8626}{}{Takhle nevyhraješ}
{8627}{}{Jak jsi mohl venku pøeít s touhle muškou?}
#
# target hit in head
#
{8628}{}{Oh, moje bolavá hlava!}
{8629}{}{Uh}
{8630}{}{Ooo}
#
# target hit in left arm
#
{8631}{}{Moje ruka!}
{8632}{}{Aauuu nìco prasklo...}
{8633}{}{Necítím levou ruku}
#
# target hit in right arm
#
{8634}{}{Moje ruka!}
{8635}{}{Aauuu, nìco prasklo...}
{8636}{}{Pravá ruka je v hajzlu}
#
# target hit in torso
#
{8637}{}{Aauuu}
{8638}{}{Uff! A to jsme bıvali pøátelé...}
{8639}{}{Uff!}
{8640}{}{Aauuu. Tak ta sedla!}
{8641}{}{Aauuu. Teï jsem se nasral}
{8642}{}{Uff! Tohle ti oplatím}
{8643}{}{Áaaa!}
{8644}{}{Aaau! A teï zaènem bojovat}
{8645}{}{Bojuješ poøád jak posera}
{8646}{}{Ufff!}
#
# target hit in right leg
#
{8647}{}{Aauuu}
{8648}{}{Moje noha, necítím ji}
{8649}{}{Ou, koleno}
#
# target hit in left leg
#
{8650}{}{Hej, tuhle budu ještì potøebovat!}
{8651}{}{Moje noha, necítím ji}
{8652}{}{Ou, koleno}
#
# target hit in eyes
#
{8653}{}{Áááaamm!}
{8654}{}{Vypli proud?!}
{8655}{}{Moje oèi!}
#
# target hit in groin
#
{8656}{}{U jako harant jsi byl sketa...}
{8657}{}{To se ti povedlo}
{8658}{}{U mi bylo líp...}
{8659}{}{Ooo, do slabin!}
{8660}{}{Nejpodlejší bojovník z Vaultu, tos byl vdycky}
{8661}{}{Poèkej, a se nadechnu!}

# 78. Garl during Honor Fight
# I'm fighting you over Tandi.  I shall triumph, unless you win!
#
#  running away
#
{8700}{}{Fajn, vezmi si ji!}
{8701}{}{Ta èubka je tvoje!}
{8702}{}{Tandi je tvoje. Nech mì bıt!}
{8703}{}{Jo, mùeš si ji odvést!}
{8704}{}{Tandi je tvoje. Nech mì bıt!}
{8705}{}{Ta èubka je tvoje!}
#
# moving in to attack
#
{8706}{}{A souboj cti zaène!}
{8707}{}{}
{8708}{}{}
{8709}{}{Toho si podám já!}
{8710}{}{Za Khany!}
{8711}{}{}
#
# attacking (10)
#
{8712}{}{}
{8713}{}{}
{8714}{}{Jsem nejlepší!}
{8715}{}{RAAAAAAARRRR!!}
{8716}{}{}
{8717}{}{}
{8718}{}{Zabiju tì!}
{8719}{}{}
{8720}{}{}
{8721}{}{}
#
# target being missed (6)
#
{8722}{}{}
{8723}{}{}
{8724}{}{}
{8725}{}{A teï to zkus s otevøenıma oèima!}
{8726}{}{}
{8727}{}{Nejsi hoden se mnou bojovat!}
#
# target hit in head (3)
#
{8728}{}{Dobrá trefa!}
{8729}{}{}
{8730}{}{}
#
# target hit in left arm
#
{8731}{}{}
{8732}{}{Zlomil jsi mi ruku! Teï jsme vyrovnaní!}
{8733}{}{}
#
# target hit in right arm
#
{8734}{}{}
{8735}{}{Zlomil jsi mi ruku! Teï jsme vyrovnaní!}
{8736}{}{}
#
# target hit in torso
#
{8737}{}{}
{8738}{}{}
{8739}{}{}
{8740}{}{Uff!}
{8741}{}{Aaau!}
{8742}{}{}
{8743}{}{}
{8744}{}{}
{8745}{}{}
{8746}{}{Áaaa! To bolelo!}

#
# target hit in right leg
#
{8747}{}{}
{8748}{}{Podrazácká rána!}
{8749}{}{}
#
# target hit in left leg
#
{8750}{}{}
{8751}{}{Podrazácká rána!}
{8752}{}{}
#
# target hit in eyes
#
{8753}{}{}
{8754}{}{}
{8755}{}{To nebylo moc èestné!}
#
# target hit in groin
#
{8756}{}{Oooooo, moje koule!}
{8757}{}{}
{8758}{}{}
{8759}{}{}
{8760}{}{Uff!}
{8761}{}{Mé muství mi nevezmeš!}
#
############################################
# 123 Mysterious Stranger / Tough Person in Fo2
############################################
#
# target hit in head
#
{8800}{}{Au! Ty zkurvy...}
{8801}{}{Mám zlomenej nos!}
{8802}{}{Utrhnu ti hlavu!}
{8803}{}{Dostal jsem to do lebky, kurva!}
{8804}{}{Budeš se muset víc snait, ale ne o moc.}
{8805}{}{Jau, za to zaplatíš.}
{8806}{}{A hele, lítaj kolem mì ptáèkové.}
{8807}{}{To bolelo.}
{8808}{}{Nìkdo mi zkurvil mùj krásnej oblièej.}
{8809}{}{Zùstane mi tam jizva.}
#
# target hit in left arm
#
{8810}{}{Au, moje ruka.}
{8811}{}{Nìkdo tady právì udìlal nejvìtší chybu svıho ivota.}
{8812}{}{Moje ruka!}
{8813}{}{Hehe, já jsem pravák.}
{8814}{}{Zabiju tì i jednou rukou.}
{8815}{}{Ty prsty stejnì nepotøebuju.}
{8816}{}{Na tebe mi bohatì staèí jedinej prst.}
{8817}{}{Zatracenì, ten prst mi bude pøi švihu chybìt.}
{8818}{}{Stejnì tì dostanu.}
{8819}{}{Zatracenì, mám teï ruku vejpùl.}
#
# target hit in right arm
#
{8820}{}{Au, moje ruka.}
{8821}{}{Nìkdo tady právì udìlal nejvìtší chybu svıho ivota.}
{8822}{}{Moje ruka!}
{8823}{}{Dostanu tì i levaèkou.}
{8824}{}{Haha, já jsem stejnì levák.}
{8825}{}{Chceš mì odzbrojit, jo?}
{8826}{}{To mì nezastaví.}
{8827}{}{Poøád na tebe mùu pouít druhou ruku.}
{8828}{}{Zatracenì, to bolelo.}
{8829}{}{Mmm, zùstane mi tam jizva.}
#
# target hit in torso
#
{8830}{}{Ble!}
{8831}{}{Uuf!}
{8832}{}{Jauvajs!}
{8833}{}{Jo, to mi zlomilo pár eber.}
{8834}{}{Uf! To bolelo!}
{8835}{}{Jauvajs!}
{8836}{}{Aááá!}
{8837}{}{Ajaj, asi mám zlomenı ebro!}
{8838}{}{Au!!! Moje bøicho!}
{8839}{}{Jo, aspoò mám motivaci.}
{8840}{}{Tak teï jsem se nasral.}
{8841}{}{To se mi vùbec nelíbilo.}
{8842}{}{A sakra, praskla mi plíce.}
{8843}{}{Jenom èerv jako ty dává rány do bøicha.}
{8844}{}{Svoje dìravı orgány vymìním za ty tvoje.}
{8845}{}{Sakra, jseš lepší ne vypadáš. Ale stejnì tì dostanu.}
{8846}{}{To nebylo hezkı. Asi ti budu muset dát lekci chování.}
{8847}{}{To byla jen náhoda.}
{8848}{}{Chci vidìt, jak se budeš tváøit, a ti udìlám to samı.}
{8849}{}{Asi stárnu. Ono to docela bolelo.}
{8850}{}{Budeš se muset víc snait.}
{8851}{}{Ještì poøád tì bez problému dostanu.}
{8852}{}{Tìsnì vedle plíce... aspoò myslím.}
{8853}{}{Mám v sobì fakt hodnì krve. Teda, u ne.}
{8854}{}{Zatracenì, to bolí!}
{8855}{}{Kurva! Ty bastarde!}
{8856}{}{Nikdo ivej do mì takhle støílet nebude.}
{8857}{}{A popadnu dech (kuc kuc), tak si pro tebe dojdu.}
{8858}{}{Nìco se ve mnì pøetrhlo.}
{8859}{}{To tì bude mrzet.}
#
# target hit in right leg
#
{8860}{}{Au, moje noha.}
{8861}{}{Klidnì mùu sedìt, stejnì tì zabiju!}
{8862}{}{Moje koleno!}
{8863}{}{Moje achilovka!}
{8864}{}{Jaùùùùùù!!}
{8865}{}{A mám po foxtrotu.}
{8866}{}{Já tì nauèím trhat mi prsty na noze.}
{8867}{}{Mám zlomenou nohu! Za to tì roztrhnu vejpùl!}
{8868}{}{Kde mám sakra obvazy?}
{8869}{}{Kurva, bolí mì noha.}
#
# target hit in left leg
#
{8870}{}{Au, moje noha.}
{8871}{}{Klidnì mùu sedìt, stejnì tì zabiju!}
{8872}{}{Moje koleno!}
{8873}{}{Budu chvíli kulhat.}
{8874}{}{Pojï sem, to se mám za tebou belhat?}
{8875}{}{Sakra, to mi skoro utrhlo nohu.}
{8876}{}{To mì zpomalí na celou sezónu.}
{8877}{}{Budu muset jezdit na kriplkáøe.}
{8878}{}{Mám ještì jednu nohu.}
{8879}{}{Haha, to byla moje umìlá noha.}
#
# target hit in eyes
#
{8880}{}{Nic nevidím!}
{8881}{}{Tahle bitka je èím dál horší.}
{8882}{}{Tak to bylo fakt ubohı!}
{8883}{}{Kurva, nic nevidím!}
{8884}{}{Ty èuráku, nic nevidím!}
{8885}{}{Za tohle ti rozmaèkám oèi jako citron!}
{8886}{}{Kurva, mám utrenı oko!}
{8887}{}{Do hajzlu, oko mi visí jenom na nervu.}
{8888}{}{Ještì poøád tì slyším.}
{8889}{}{Opova se ještì jednou šáhnout na moje zasranı oèi!}
#
# target hit in groin
#
{8890}{}{Oooooo, mùj rozkrok!}
{8891}{}{To bude ráno bolet.}
{8892}{}{Zasranej srabe!}
{8893}{}{Ble!}
{8894}{}{To ti ani trochu nepomùe.}
{8895}{}{Bylo mi jasnı, e se o nìco takovıho pokusíš.}
{8896}{}{Bavíš se?}
{8897}{}{Za to ti urvu ty tvoje a donutím tì je serat.}
{8898}{}{Musím si na chvíli odpoèinout.}
{8899}{}{Budeš se muset víc snait, nosím suspík.}
#
