#
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#

#
# Special holiday dates
#
{100}{}{Šastnı Novı rok!}      # New years
{101}{}{Šastnı Valentın!}     # April fools
{102}{}{Veselého Apríla!}      # April fools
{103}{}{Šastnı Den expedice!}            # Shipping day!
{104}{}{Šastnı Den nezávislosti!}    # Independence day
{105}{}{Šastnı Halloween!}           # Halloween
{106}{}{Šastnı Den díkùvzdání!}    # Thanksgiving
{107}{}{Veselé Vánoce!}           # X-mas

#
# System messages
#
{200}{}{VÍCE}
{201}{}{ZPÌT}
{202}{}{STAV}
{203}{}{Nemáš ádné úkoly.}
{204}{}{VODÍTKA}  # clues gone
{205}{}{AUTOMAPY}
{206}{}{VIDEO ARCHÍVY}
{207}{}{DATA}
{208}{}{}
{209}{}{}
{210}{}{- úkoly}
{211}{}{DATA}
{212}{}{z}
{213}{}{Strana}
{214}{}{HOTOVO}
{215}{}{Na tomto místì nemùeš odpoèívat!}

#
# Alarm clock
#
{300}{}{BUDÍK}
{301}{}{Hit body}
{302}{}{Odpoèívat deset minut}
{303}{}{Odpoèívat pùl hodiny}
{304}{}{Odpoèívat hodinu}
{305}{}{Odpoèívat dvì hodiny}
{306}{}{Odpoèívat tøi hodiny}
{307}{}{Odpoèívat ètyøi hodiny}
{308}{}{Odpoèívat pìt hodin}
{309}{}{Odpoèívat šest hodin}
{310}{}{Odpoèívat do rána (0800)}
{311}{}{Odpoèívat do poledne (1200)}
{312}{}{Odpoèívat do veèera (1800)}
{313}{}{Odpoèívat do pùlnoci (0000)}
{314}{}{Odpoèívat do plného uzdravení}
{315}{}{Odpoèívat do uzdravení celé skupiny}

# Fo1 resting times
{320}{}{Odpoèívat deset minut}
{321}{}{Odpoèívat pùl hodiny}
{322}{}{Odpoèívat hodinu}
{323}{}{Odpoèívat dvì hodiny}
{324}{}{Odpoèívat tøi hodiny}
{325}{}{Odpoèívat ètyøi hodiny}
{326}{}{Odpoèívat pìt hodin}
{327}{}{Odpoèívat šest hodin}
{328}{}{Odpoèívat do rána (0600)}
{329}{}{Odpoèívat do poledne (1200)}
{330}{}{Odpoèívat do veèera (1800)}
{331}{}{Odpoèívat do pùlnoci (0000)}
{332}{}{Odpoèívat do plného uzdravení}
{333}{}{Odpoèívat do uzdravení celé skupiny}

#
# Holodisk titles
#
{400}{}{Záznam experimentu FEV}
{401}{}{Bezpeènostní záznam}
{402}{}{Dávnı záznam Bratrstva}
{403}{}{Záznam experimentu Alpha}
{404}{}{Záznam experimentu Delta}
{405}{}{Vreeiny poznatky o mutantech}
{406}{}{Kodex Bratrstva}
{407}{}{Záznam vysílání mutantù}
{408}{}{Páska Bratrstva}
{409}{}{Sophiiny záznamy}
{410}{}{Maxsonùv záznam}
{411}{}{Audio deník Richarda Greye}
{412}{}{Deník kapitána Maxsona}
{413}{}{Vızkum FEV}
{414}{}{Specifikace energozbroje}
{415}{}{Záznamy o West Tech}
{416}{}{Lokace Vaultù v34.129}
{417}{}{Vysílání Regulátorù}
{418}{}{RESERVED (available)}
{419}{}{RESERVED (available)}
{420}{}{RESERVED (available)}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{Logo Interplay}               	# Not show in Pip-Boy 2000
{501}{}{MacPlay Logo}                 	# MacPlay version ,Not show in Pip-Boy 2000
{502}{}{Správcùv briefing}
{503}{}{Znièení Nádrí}
{504}{}{Znièení Katedrály}
{505}{}{Ponoøení do Nádrí}
{506}{}{Invaze do Vaultu 13}
{507}{}{ }
{508}{}{ }
{509}{}{ }
{510}{}{Odchod z Vaultu} 					# Male
{511}{}{Odchod z Vaultu} 					# Female
{512}{}{Vault 13 a voda}
{513}{}{Vault 13 dochází voda}
{514}{}{Vault 13 došla voda}
{515}{}{ }
{516}{}{ }

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Clues}  # Clues gone
{602}{}{Automaps}
{603}{}{Archives}
{604}{}{Alarm Clock}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Welcome to the Rob Co Pipboy 2000.}
{607}{}{So long.}
{608}{}{Wake up.}


#
# Status thread text
#
# Format:
# 0 City name
# 1 ... 9 thread/quest name
#
{700}{}{Vault 13}
{701}{}{Uklidnit skupinu rebelù.}
{702}{}{Znièit Vùdce mutantù.}
{703}{}{Znièit zdroj mutantù.}
{704}{}{Najít Vodní èip.}
{705}{}{Najít zlodìje vody.}
{706}{}{Pomoct medikovi syntetizovat protilátku.}
{707}{}{Zjistit informace o vnìjším svìtì z knihovních terminálù.}
#
{710}{}{Vault 15}
{711}{}{Hledat vodítka a informace.}
{712}{}{Najít vodní èip.}
#
{720}{}{Shady Sands}
{721}{}{Uzdravit Jarvise z otravy radškorpióním jedem.}
{722}{}{Vyrobit protijed.}
{723}{}{Zachránit Tandi.}
{724}{}{Zastavit radškorpióny.}
{725}{}{Pomoct Shady Sands zlepšit úrodu.}
{726}{}{Promluvit s Katrinou.}
{727}{}{Najmout Iana.}
#
{730}{}{Junktown}
{731}{}{Pomoci Saulovi.}
{732}{}{Zlikvidovat Killiana.}
{733}{}{Zachránit Sinthii.}
{734}{}{Zachránit Trish.}
{735}{}{Zastavit Gizma.}
{736}{}{Zlikvidovat gang Lebkounù.}
#
{740}{}{Nájezdníci}
{741}{}{Pøipoj se ke Khanùm.}
{742}{}{Zniè Khany.}
{743}{}{Zabij otroky.}
{744}{}{Zachraò otroky.}
#
{750}{}{Nekropolis}
{751}{}{Odstranit z Vodárny supermutanty.}
{752}{}{Opravit vodní èerpadlo v Nekropolis.}
#
{760}{}{Hub}
{761}{}{Zabít Páraèe.}
{762}{}{Zbavit se Jain.}
{763}{}{Zbavit se Darena Hightowera.}
{764}{}{Rozluštit záhadu ztracenıch karavan.}
{765}{}{Ukrást Obchodníkùm s vodou náhrdelník.}
#
{770}{}{Bratrstvo oceli}
{771}{}{Stát se Zasvìcencem.}
{772}{}{Zachránit Zasvìcence z Hubu.}
#
{780}{}{Vojenská základna}
#
{790}{}{Kráter}
{791}{}{Odstranit ze zaøízení pasti.}
{792}{}{Obnovit dodávku energie.}
#
{800}{}{Kostnice}
{801}{}{Stát se èlenem Blades.}
{802}{}{Doruèit medailón Romerovi.}
{803}{}{Doruèit zásilku od Gun Runnerù.}
{804}{}{Vypátrat špióna Dìtí katedrály u Následovníkù.}
{805}{}{Opravit pro Adytum jejich hydroponickou farmu.}
{806}{}{Zachránit Jasona Zimmermana.}
{807}{}{Zastavit útoky gangù na Adytum.}
#
{810}{}{Katedrála}


#
# Holodisk text
#

# *** FEV Experiment Disk ***
{1000}{}{• Datum zápisu: 21. bøezen, 2075}
{1001}{}{Major Barnett pøikázal zahájit experimenty s kmenem}
{1002}{}{panimunitního viru è. 10-011, kterı byl pojmenován}
{1003}{}{FEV (Forced Evolutionary Virus). Spíše ne na jeho}
{1004}{}{hlavní efekt replikaèní stability, má bıt hlavní}
{1005}{}{zájem soustøedìn na vedlejší úèinky virové struktury.}
{1006}{}{Major vìøí, e nová struktura je dalším logickım }
{1007}{}{krokem vıvoje bunìk savcù. Experimenty s}
{1008}{}{jednobunìènımi organismy mají skvìlé vısledky.}
{1009}{}{Zatímco jejich základní metabolické procesy zùstávají}
{1010}{}{prakticky beze zmìn, jejich odolnost vùèi infekcím}
{1011}{}{a radiaci pøedèí všechny naše døívìjší pøedpoklady.}
{1012}{}{Addendum: na chloroplasty se jeví virus bez úèinku.}
{1013}{}{Další experimentování s rostlinnımi buòkami bylo }
{1014}{}{z pøíkazu majora Barnetta zastaveno.}
{1015}{}{**END-PAR**}
# -
{1016}{}{• Datum zápisu: 9. kvìten, 2075}
{1017}{}{Infikovali jsme FEV nìkolik rùznıch druhù ploštìnek. }
{1018}{}{Bìhem nìkolika hodin zvìtšily ploštìnky svou velikost o 28%}
{1019}{}{a populace stala rezistentní vùèi 39 druhùm virové}
{1020}{}{nákazy. Všechny vzorky si své novì nabyté vlastnosti}
{1021}{}{podrely i v dalších generacích a nová struktura DNK }
{1022}{}{plnì pøešla do jejich genové vıbavy.}
{1023}{}{Zkoumané subjekty se ovšem reprodukují pouze }
{1024}{}{asexuálnì. Experimenty s dalšími druhy hmyzu }
{1025}{}{nebylo mono provést. Major Barnett je nechal }
{1026}{}{a do odvolání pozastavit.}
{1027}{}{**END-PAR**}
# -
{1028}{}{• Datum zápisu: 30. èerven, 2075}
{1029}{}{Nìkolik chovù bílıch laboratorních myší bylo plnì}
{1030}{}{infikováno virem FEV. Opìt bylo u po nìkolika hodinách}
{1031}{}{zaznamenáno zvìtšení tìlesné velikosti a po 9-ti dnech}
{1032}{}{se tato hodnota stabilizovala na vzrùstu 31% oproti}
{1033}{}{kontrolní skupinì. Pitva prokázala nejvìtší míru nárùstu}
{1034}{}{u pøíènì pruhované svalové tkánì a urèitıch vnitøních,}
{1035}{}{orgánù, pøedevším pak u jater, srdce a ledvin. Rovnì}
{1036}{}{se k našemu pøekvapení ukázalo, e infikované myši byly}
{1037}{}{schopny nalézt správnou cestu bludištìm v ménì ne}
{1038}{}{polovièním èase oproti kontrolní skupinì. Tyto signály}
{1039}{}{bude ovšem tøeba potvrdit ještì dalšími testy.}
{1040}{}{**END-PAR**}
# -
{1041}{}{• Datum zápisu: 9. listopad, 2075}
{1042}{}{Infikovali jsme FEV 218 laboratorních králíkù. Polovinì }
{1043}{}{testovanıch subjektù byly implantovány elektrody }
{1044}{}{za úèelem monitorování EEG aktivity pøed a po }
{1045}{}{infikování viru. Zvıšení elektrické aktivity mozku }
{1046}{}{bylo v prùmìru zaznamenáno 3.2 sekund po aplikaci viru.}
{1047}{}{Opìt bylo pozorováno typické zvìtšení svalové hmoty.}
{1048}{}{Nicménì byla rovnì zaznamenána zvıšená agresivita}
{1049}{}{(speciálnì mezi samci) testovací skupiny. Rozbor}
{1050}{}{pøírùstku mozkové tkánì zpùsobeného FEV, ukázal }
{1051}{}{na zvıšené mnoství dendritickıch spojení a to zvláštì }
{1052}{}{u limbického systému a ve frontálním cortexu.}
{1053}{}{**END-PAR**}
# -
{1054}{}{• Datum zápisu: 12. leden, 2076}
{1055}{}{Se šarí 11-011 jsme dosáhli zlepšení úèinnosti mitotického }
{1056}{}{cyklu o 43%. Infikovali jsme touto novou odrùdou viru}
{1057}{}{53 mıvalù. V pøídavku k u oèekávanému zvìtšení}
{1058}{}{tìlesné hmotnosti, prokázaly reakèní testy i zvıšení}
{1059}{}{inteligence a manuální zruènosti a to o 19 bodù}
{1060}{}{dle Schuler-Kappova indexu. }
{1061}{}{Naneštìstí nìkolik testovacích subjektù uprchlo z}
{1062}{}{poškozené klece a muselo bıt odchyceno a usmrceno. }
{1063}{}{Major Barnett naøídil likvidaci všech zbıvajících subjektù.}
{1064}{}{Nicménì pøi koneèném sèítání nám chybìly dva páry.}
{1065}{}{**END-PAR**}
# -
{1066}{}{• Datum zápisu: 13. kvìten, 2076}
{1067}{}{Zabudovali jsme do struktury FEV nìkolik novıch}
{1068}{}{genovıch sekvencí dodanıch poradním tımem majora}
{1069}{}{Barnetta. S dávkou 11-101a jsme potom infikovali}
{1070}{}{23 psù z èistokrevnıch i míšenıch plemen, všechny}
{1071}{}{støedního vzrùstu. Zvìtšení tìlesné velikosti bylo }
{1072}{}{doprovázeno i zvıšenou agresivitou, bez signifikantních}
{1073}{}{známek nárùstu inteligence. V dalších pokusech plánujeme}
{1074}{}{zkøíit 92 rùznıch párù s vyuitím 11-011. Všechny}
{1075}{}{subjekty byly po 14-ti tıdnech pozorování zlikvidovány.}
{1076}{}{**END-PAR**}
# -
{1077}{}{• Datum zápisu: 4. øíjen, 2076}
{1078}{}{Dokonèili jsme køíení. 15 šimpanzù bylo infikováno}
{1079}{}{šarí 11-111. Bezprecedentní nárùst imunity i vzrùstu.}
{1080}{}{Pokusy vyvolat u testovanıch subjektù zhoubné}
{1081}{}{nádorové bujení pomocí radiologickıch a chemickıch}
{1082}{}{èinidel, byly neúspìšné. Prudkı nárùst agresivity}
{1083}{}{zvíøat vedl k jejich vzájemné izolaci. Dva subjekty}
{1084}{}{byli postieni prudkımi epileptickımi záchvaty}
{1085}{}{a zemøeli. Všechny zbıvající byli poté zlikvidovány.}
{1086}{}{**END-PAR**}
# -
{1087}{}{• Datum zápisu: 7. leden, 2077}
{1088}{}{Major Barnett pøikázal pøevést veškerı vızkum FEV }
{1089}{}{na vojenskou základnu Mariposa. Plánuje v projektu }
{1090}{}{pokraèovat experimentováním na dobrovolnících }
{1091}{}{z øad armády. Jsem dùraznì proti tomu a ádám, aby }
{1092}{}{bylo zaprotokolováno, e ani já ani mùj tım}
{1093}{}{nedoporuèujeme testování na lidskıch subjektech.}
{1094}{}{**END-DISK**}

# *** Security Disk ***
{2000}{}{Security override Gamma Omicron Delta.}
{2001}{}{**END-DISK**}

# *** Ancient Brotherhood Disk ***
{3000}{}{Kapitán Maxson mìl pravdu. Tohle místo je smrt.}
{3001}{}{Tenhle záznam poøizuji proto, e kdybychom nedokázali}
{3002}{}{dojít nazpátek, doufám, e jednou nìkdo objeví,}
{3003}{}{co se s námi stalo.}
{3004}{}{**END-PAR**}
# -
{3005}{}{Po 20-ti dnech pekla jsme dorazili do vızkumné základny}
{3006}{}{West Tech. Pak se ukázalo, e cesta byla ta lehèí èást.}
{3007}{}{Úroveò radiace zaèala stoupat hned jak jsme zdálky}
{3008}{}{uvidìli ten gigantickı kráter. Prohlédli jsme naše zásoby}
{3009}{}{a spoèítali si, e v brnìní a s antiradiaèními}
{3010}{}{prostøedky,které máme k dispozici, bychom se mohli }
{3011}{}{odváit krátkého prùzkumu. Vím, e je to riziko, ale}
{3012}{}{technologie, kterou mùe skrıvat, je dostateèna odmìna.}
{3013}{}{**END-PAR**}
# -
{3014}{}{Sešplhali jsme kráterem do prvního patra a všechno}
{3015}{}{se zdálo bìet podle plánu. Energetické systémy}
{3016}{}{komplexu byly odpojené, take jsme ani nemuseli}
{3017}{}{pøemosovat bezpeènostní èidla. Aspoò jsme si to mysleli. }
{3018}{}{V prvním patøe nebylo nic cenného, proto jsme šli dál.}
{3019}{}{**END-PAR**}
# -
{3020}{}{Na druhém patøe to vypadalo stejnì.}
{3021}{}{**END-PAR**}
# -
{3022}{}{Jakmile Jensen vkroèil do tøetího patra zaèalo peklo.}
{3023}{}{Bezpeènostní senzory byly spáleny a vyøazeny pouze}
{3024}{}{na prvních dvou podlaích, ne však na tøetím.}
{3025}{}{Jensen byl rozsekán na kousky døív, ne staèil zjistit}
{3026}{}{co se dìje. Ještì nikdy jsme nevidìli zbranì, které by}
{3027}{}{tak lehce pronikaly energozbrojí. Mui okolo mì}
{3028}{}{padali jako mouchy, ani mìli sebemenší šanci vystøelit.}
{3029}{}{Pokoušel jsem se tım pøeskupit, ale do prvního patra}
{3030}{}{se spolu mnou dokázali dostat jen Soto a Camarillo.}
{3031}{}{**END-PAR**}
# -
{3032}{}{Fakt, e cítím Sotovo spálené maso v místech, kde bylo}
{3033}{}{jeho energozbroj proraena, znamená e moje vlastní}
{3034}{}{brnìní u není nadále vzduchotìsné. Take polykám}
{3035}{}{mnohem víc radiace, ne jsem pùvodnì plánoval. Z mojí}
{3036}{}{hydrauliky se alarmujícím tempem ztrácí kapalina. Musím}
{3037}{}{se z tohohle prokletého místa dostat rychle pryè.}
{3038}{}{**END-PAR**}
# -
{3039}{}{Camarillo vypadá fyzicky celkem v poøádku, ale víc ne }
{3040}{}{hodinu byl mimo a mumlal nìco o dehennì. Ten bastard }
{3041}{}{si vzal všechny naše zbıvající antiradiaèní prostøedky.}
{3042}{}{**END-PAR**}
# -
{3043}{}{Zbyli jsme jen Soto a já. Kdy nedostaneme ty }
{3044}{}{antiradianty, nedojdeme odtud moc daleko. }
{3045}{}{Pokusím se najít Camarilla}
{3046}{}{døív ne u bude pozdì.}
{3047}{}{**END-PAR**}
# -
{3048}{}{Serant D. Allen, armáda Spojenıch Státù.}
{3049}{}{**END-DISK**}


#  *** Alpha Experiment Disk ***
{4000}{}{Projekt prototypu Panimunitního Viru}
{4001}{}{**END-PAR**}
# -
{4002}{}{S úmyslem vyrovnat momentální pøevahu }
{4003}{}{bakteriologického a virového vızkumu}
{4004}{}{Èínské vlády, vytvoøili jsme fragment viru }
{4005}{}{sestávající z kyseliny ribonukleové (RNK) }
{4006}{}{uzavøené v pouzdøe z proteinovıch lipidù. Tento fragment }
{4007}{}{obsahuje speciálnì vytvoøenou sekvenci ozáøenıch}
{4008}{}{aminokyselin (RAK), která je schopna pøipojení}
{4009}{}{k nespecifikovanım vazbám kyseliny deoxyribonukleové}
{4010}{}{(DNK) a urychlit tak nereplikaèní mitózu bunìk.}
{4011}{}{Vısledná hostitelská buòka je poté ponechána}
{4012}{}{se ètyøspirálovou strukturou DNK.}
{4013}{}{**END-PAR**}
# -
{4014}{}{Prvotní testy jsou slibné. Virus lehce proniká bunìènou }
{4015}{}{membránou a pøipojuje se pøímo k hostitelské }
{4016}{}{DNK v jádøe. Mitóza bunìèné struktury zaèíná }
{4017}{}{témìø okamitì. Cytokinezi je zabránìno dùslednou }
{4018}{}{kontrolou dispozic kinetochorickıch vláken bìhem }
{4019}{}{procesu anafáze. Celı mitotickı cyklus je ukonèen}
{4020}{}{pøiblinì po 2 hodinách, aèkoli fenotypickı projev}
{4021}{}{nové struktury mùe bıt patrnı }
{4022}{}{a po nìkolika dnech nebo tıdnech.}
{4023}{}{**END-PAR**}
# -
{4024}{}{K pøídavku k velmi efektivní odolnosti proti bakteriálnímu }
{4025}{}{a virovému napadení se ètyøšroubovicová struktura jeví }
{4026}{}{témìø dokonale imunní vùèi chybám indukovanım v procesu}
{4027}{}{dìlení a to právì díky multiplicitì základní sekvence.}
{4028}{}{Tkáò vystavená pronikavé radiaci nevykazuje v základních}
{4029}{}{sekvencích ádné mutace. Rovnì mechanismy ribozómù }
{4030}{}{syntetizující protein jsou neporušeny.}
{4031}{}{**END-PAR**}
# -
{4032}{}{Více ne 80% vzorkù obsahovalo ètyøšroubovicovou}
{4033}{}{DNK. Nejvìtší citlivost na virus vykazuje tkáò svalù }
{4034}{}{a kostí, rovnì spolu se sekreèními buòkami. }
{4035}{}{Nejménì ovlivnitelné jsou senzorické a neurální buòky.}
{4036}{}{Kupodivu byla mitóza vyvolána i u normálnì nedìlitelnıch}
{4037}{}{nervovıch a nesomatickıch bunìk.}
{4038}{}{K pøesnìjšímu urèení vlivù na tyto buòky bude}
{4039}{}{potøeba provést ještì další experimenty.}
{4040}{}{**END-DISK**}


# *** Delta Experiment Disk ***
{5000}{}{Ministerstvo obrany pokládalo za nezbytné}
{5001}{}{prozkoumat hloubìji úèinky vlnové technologie}
{5002}{}{na ivé organismy. Jako základ pro naši studii}
{5003}{}{jsme pojali svìtlo a zvuk. Manipulací s amplitudou}
{5004}{}{svìtelnıch vln a postupnım zvyšováním frekvence}
{5005}{}{jsme byli schopni vyrobit prototypy laserù,}
{5006}{}{umoòující proøíznout a nìkolik stop oceli.}
{5007}{}{Naneštìstí zatím nemáme zdroj potøebné energie.}
{5008}{}{Pro tento vızkum hodláme vyèlenít nìkolik vìdcù.}
{5009}{}{**END-DISK**}


# *** Vree's Experiment Disk ***
{6000}{}{• Poèáteèní pozorování}
{6001}{}{**END-PAR**}
# -
{6002}{}{Tohle je opravdu podivuhodné. Nìkolik našich Rytíøù }
{6003}{}{nalezlo pøi prùzkumné expedici neobvyklého tvora. Tento }
{6004}{}{tvor se zdá bıt humanoidního typu a velice }
{6005}{}{pravdìpodobnì je odnoí lidského rodu. Nicménì v celkové }
{6006}{}{struktuøe je daleko více rozdílù ne u normálních lidí.}
{6007}{}{**END-PAR**}
# -
{6008}{}{Podle pøedbìného vyšetøení se ukazuje, e}
{6009}{}{bunìèná struktura tvora je pøíbuzná lidské.}
{6010}{}{Døíve ne provedu hlubší rozbor a vyvodím z nìj závìry, }
{6011}{}{chci zmìøit pár základních statistickıch údajù subjektu.}
{6012}{}{**END-PAR**}
# -
{6013}{}{• Statistická data Subjektu A:}
{6014}{}{**END-PAR**}
# -
{6015}{}{Vıška:   3.2 metrù}
{6016}{}{Váha:    363.21 kg}
{6017}{}{Pohlaví: Neurèitelné}
{6018}{}{Barva pokoky: Pod umìlım osvìtlením pøevauje šedá }
{6019}{}{s lehkımi odstíny zelené. Nelze ovšem vylouèit, e je to}
{6020}{}{zavinìno rozkladem nebo pùsobením povìtrnostních vlivù.}
{6021}{}{Pokoka je extrémnì tuhá a odolává i øezu skalpelem.}
{6022}{}{**END-PAR**}
{6023}{}{Tkáòovı rozbor (v % hmotnosti):}
{6024}{}{Svalstvo:            77.41% }
{6025}{}{Kosti:               10.23%}
{6026}{}{Tuk:                  3.02%}
{6027}{}{Ostatní tkánì:        9.34%}
{6028}{}{**END-PAR**}
{6029}{}{Bunìèná struktura:}
{6030}{}{Kultura vykazuje vyšší øád bunìèného dìlení.}
{6031}{}{Mitóza probíhá a o 15% rychleji ne}
{6032}{}{normální lidské populace.}
{6033}{}{Struktura bunìk je nicménì velice podobná}
{6034}{}{lidské.}
{6035}{}{Genetickı rozbor vykazuje vysokı stupeò korelace}
{6036}{}{mezi subjektem a druhem Homo Sapiens. Jako}
{6037}{}{nejpravdìpodobnìjší hypotéza se jeví mutace}
{6038}{}{zbytkovımi radiaèními a biochemickımi èinidly z}
{6039}{}{dob války. Šroubovice DNK se jeví naprosto kompletní.}
{6040}{}{Všechny narušené geny i geny indisponující k }
{6041}{}{dìdiènım chorobám byly ze systému odstranìny.}
{6042}{}{Rovnì prameny RNK vykazují známky manipulace}
{6043}{}{za úèelem navıšení transmise signálù.}
{6044}{}{**END-PAR**}
# -
{6045}{}{• Prvotní hypotéza}
{6046}{}{**END-PAR**}
# -
{6047}{}{S pøihlédnutím k zvıšenému mnoství neurálních}
{6048}{}{transmiterù a synaptickıch pøijímaèù pøedpokládám,}
{6049}{}{e subjekt musel mít znaènì rychlejší reflexy a}
{6050}{}{ostøejší smysly ne lidé. Vycházejíc ze zprávy Rytíøù}
{6051}{}{o oblasti, ve které byl subjekt nalezena a která je}
{6052}{}{suchá, neplodná, radioaktivní a s vysokou koncentrací,}
{6053}{}{chemickıch slouèenin, je udivující, e subjekt dokázal}
{6054}{}{pøeít tak dlouho. Urèuji pravdìpodobnou pøíèinu smrti.}
{6055}{}{**END-PAR**}
# -
{6056}{}{• Vısledky z testù provedenıch na Subjektu A:}
{6057}{}{**END-PAR**}
# -
{6058}{}{Vizuální pozorování:}
{6059}{}{Èernı spálenı prach poblí místa vniku nabízí }
{6060}{}{hypotézu zásahu kulkou.}
{6061}{}{1.2 cm dlouhá trná rána na lıtku pravé nohy }
{6062}{}{vypadá, e byla zpùsobena zuby. Provedu}
{6063}{}{testy na nakaení vzteklinou.}
{6064}{}{Kùe je pùsobením povìtrnostních vlivù suchá a šupinatá.}
{6065}{}{**END-PAR**}
# -
{6066}{}{Vısledky testu:}
{6067}{}{Úroveò ozáøení: 12 rad.}
{6068}{}{Test vztekliny:  bez nálezu.}
{6069}{}{Hydrochlorickı plyn: bez nálezu}
{6070}{}{Úroveò chlorinu: .07%}
{6071}{}{Obsah síranù: .02%}
{6072}{}{Phase Shifting Virus:  bez nálezu}
{6073}{}{Gamma Cyclotronic Virus: bez nálezu}
{6074}{}{Forced Evolutionary Virus II: vícenásobné pøedávkování}
{6075}{}{**END-PAR**}
# -
{6076}{}{• Hypotézy}
{6077}{}{**END-PAR**}
# -
{6078}{}{Ze svého pozorování vyvozuji, e testovanı subjekt }
{6079}{}{byl zabit v boji s nejménì dvìma lidmi a tøemi }
{6080}{}{zvíøaty velikosti bìného psa.}
{6081}{}{Co je ale skuteènì udivující, je rozloha virové}
{6082}{}{infekce v subjektu. Èetla jsem kdysi, e nìkteøí}
{6083}{}{pøedváleèní vìdci provádìli s podobnım virem}
{6084}{}{experimenty. Všechny záznamy o vızkumu byly ale}
{6085}{}{znièeny.}
{6086}{}{**END-PAR**}
# -
{6087}{}{Vızkum tohoto viru údajnì vedl k mnoha velice zajímavım }
{6088}{}{objevùm. Pøedávkování tímto virem mìlo za následek}
{6089}{}{podivuhodné mutace. K nim lze poèítat i zmìnu }
{6090}{}{svalové a kostní struktury. Pøedevším pak byly }
{6091}{}{všechny indisponující geny, které lidská buòka obsahuje }
{6092}{}{odstranìny a promíchány takovım zpùsobem, }
{6093}{}{aby bylo dosaeno té nejlepší moné kombinace. Zatímco}
{6094}{}{proces, kterım to probíhá, zùstává neznámı, velice}
{6095}{}{známé jsou jeho vedlejší efekty. Tím nejvánìjším je}
{6096}{}{sterilita. Testované subjekty byly neschopné další}
{6097}{}{reprodukce a u s mutanty nebo pùvodními lidmi.}
{6098}{}{Dalším vedlejším efektem je zmìna pigmentace}
{6099}{}{epidermu. Délka ivota se prodluuje o 10%.}
{6100}{}{Intelekt je sníen v prùmìru o 30%.}
{6101}{}{**END-PAR**}
# -
{6102}{}{• Závìry}
{6103}{}{**END-PAR**}
# -
{6104}{}{Vycházejíc z tìchto informací, lze snadno extrapolovat,}
{6105}{}{e lidská rasa je schopna tyto mutanty jednoduše }
{6106}{}{pøeít. Nicménì samotnı fakt tak supervysoké}
{6107}{}{koncentrace viru v tìle mutanta mì vede k závìru,}
{6108}{}{e musí existovat místo, které je produkuje. Ale jak}
{6109}{}{a kde by to mohlo bıt, to si netroufám odhadovat.}
{6110}{}{**END-DISK**}


# *** Brotherhood of Steel Honor Code ***
# *** Maxson's History ***
{7000}{}{Mùj otec byl èlenem vládní ochranky na tajné vojenské základnì}
{7001}{}{v poušti jiní Kalifornie. Byl to typickı vojenskı policista,}
{7002}{}{nejvíc si pamatuji jeho sílu. Kdy nastal èas revoluce}
{7003}{}{respektoval jsem jeho pøesvìdèení. Zùstal vzadu,}
{7004}{}{aby pomohl slabım a zranìnım, vèetnì vìdcù.}
{7005}{}{Svìøil mne i moji matku do rukou}
{7006}{}{svého nejlepšího pøítele a pøikázal nám}
{7007}{}{odejít do pouštì spolu s ostatními rebely.}
{7008}{}{**END-PAR**}
# -
{7009}{}{Nás pár odešlo do pustiny. Jediná vìc, na kterou jsem}
{7010}{}{byl schopen myslet byla, e u svého otce nikdy neuvidím.}
{7011}{}{On vìdìl, e zùstat vzadu, znamená smrt. A pøesto zùstal.}
{7012}{}{Zùstal vìrnı vlajce a odznaku,}
{7013}{}{které nosil.}
{7014}{}{**END-PAR**}
# -
{7015}{}{Idiot jeden.}
{7016}{}{**END-PAR**}
# -
{7017}{}{Zemøel kvùli slabosti jinıch. Tohle u se nikdy nesmí}
{7018}{}{nikomu z nás stát. Staneme se nezávislımi. Budeme}
{7019}{}{stráci vìdomostí a tradic. My konec civilizace}
{7020}{}{pøeijeme. Pøevezmeme odpovìdnost za naše èiny}
{7021}{}{a budeme se umìt vypoøádat i s}
{7022}{}{èiny tìch ostatních.}
{7023}{}{**END-PAR**}
# -
{7024}{}{A toto odkazuji tobì Maxsone, mùj synu. Bratrstvo}
{7025}{}{Oceli je jen jméno. My jsme bratrstvo. Na rozdíl}
{7026}{}{od mého otce my budeme stát bok po boku s tìmi,}
{7027}{}{kdo sdílejí naše pøesvìdèení a naši víru. My jsme Ocel.}
{7028}{}{Jsme tvrdí. A byli jsme vybroušeni do ostré èepele.}
{7029}{}{**END-PAR**}
# -
{7030}{}{Vdy si pamatujte na oheò, ve kterém jsme byli vykováni.}
{7031}{}{Nikdy nezapomeòte. }
{7032}{}{Motto z minulosti a naše heslo dneška.}
{7033}{}{**END-DISK**}

# *** Mutant disk *** (bug fixed by WG: 8011 was duplicated)
{8000}{}{Poslaná zpráva: Základno, tady tım Lapaèù èíslo dva,}
{8001}{}{jak mì slyšíte? Pøepínám.}
{8002}{}{**END-PAR**}
# -
{8003}{}{Pøijatá zpráva: Slyšíme vás hlasitì a èistì, podejte}
{8004}{}{hlášení. Pøepínám.}
{8005}{}{**END-PAR**}
# -
{8006}{}{Poslaná zpráva: Ukoøistili jsme ètyøi mue, dvì eny}
{8007}{}{a zboí z jejich karavany. Nejsou nijak zvláš }
{8008}{}{kontaminováni. Vyøiïte poruèíkovi, e je posíláme }
{8009}{}{napøed, mìli by bıt schopni proces pøeít.}
{8010}{}{Poèkáme tu nìkolik dní a zkusíme najít}
{8011}{}{a zajmout další karavanu. Pøepínám.}
{8012}{}{**END-PAR**}
# -
{8013}{}{Pøijatá zpráva: Rozumím. Mìli jste }
{8014}{}{pøi akci nìjaké ztráty? Pøepínám.}
{8015}{}{**END-PAR**}
# -
{8016}{}{Poslaná zpráva: Negativní. Další èistá práce. Základno,}
{8017}{}{vyøiïte prosím tımu Lapaèù jedna, e jsme zaznamenali stejnı}
{8018}{}{problém jako oni. Jeden z našich pátraèù se nevrátil}
{8019}{}{ze své patroly. Nìkolik dalších pátraèù ohlásilo, e}
{8020}{}{minulou noc zahlédlo poblí našeho tábora nìco velkého}
{8021}{}{a velmi rychlého. Chystám se to osobnì prozkoumat }
{8022}{}{zítra ráno v 06.00 hodin. Pøepínám.}
{8023}{}{**END-PAR**}
# -
{8024}{}{Pøijatá zpráva: Rozumím. Budeme èekat na vaše hlášení.}
{8025}{}{Pokud to bude moné, pokuste se to chytit. Vùdce by to}
{8026}{}{velmi potìšilo. Konec.}
{8027}{}{**END-DISK**}


# *** Military Base Disk***
{9000}{}{• 10. øíjen, 2077}
{9001}{}{Já, Roger Maxson, kapitán, èíslo 072389 jsem zaèal tento}
{9002}{}{záznam psát proto, e to s ádnım z nás nevypadá pøíliš}
{9003}{}{rùovì a já chci aby se budoucí lidé mohli dozvìdìt, co}
{9004}{}{se tu doopravdy stalo. }
{9005}{}{**END-PAR**}
# -
{9006}{}{Všechno to peklo zaèalo, kdy jsme koneènì objevili,}
{9007}{}{co tu ti bastardi v bílıch pláštích provádìjí.}
{9008}{}{Plukovník se zamknul ve své kanceláøi a vypadá to,}
{9009}{}{e se naprosto psychicky zhroutil. Moji mui}
{9010}{}{volají po krvi. Hledají u mì odpovìdi na své otázky,}
{9011}{}{ale já sám nevím, co mám dìlat. Ale nìkdo by mìl nìco}
{9012}{}{udìlat, døív, ne se tohle místo zmìní v krvavou lázeò.}
{9013}{}{**END-PAR**}
# -
{9014}{}{• 12. øíjen 2077}
{9015}{}{Pokadé, kdy dostaneme zprávu shora, všechno se}
{9016}{}{tu pøiostøí. Válka se vyvíjí velmi špatnì}
{9017}{}{a tohle místo se vším tím chaosem okolo, je na }
{9018}{}{nejlepší cestì k úplné vzpouøe. Dnes jsem zabránil rvaèce jednoho}
{9019}{}{z mıch muù s vìdcem a poádal vìdce, aby nám}
{9020}{}{vyloili, co je úèelem jejich vızkumu.}
{9021}{}{**END-PAR**}
# -
{9022}{}{• 13. øíjen 2077}
{9023}{}{Dnes jsem zabil èlovìka. Vyslechl jsem šéfa vìdcù}
{9024}{}{Andersona a on mi popsal naprosto detailnì jejich}
{9025}{}{nelidské experimenty. Øíkal, e dostal rozkazy pøímo}
{9026}{}{ze sídla vlády, ale já tomu nevìøím. Zaèal køièet nìco o tom}
{9027}{}{jak jen poslouchá rozkazy a o vojenském duchu}
{9028}{}{a já ho zastøelil. Snaím si nalhat, e jsem to udìlal}
{9029}{}{proto abych zabránil úplné vzpouøe}
{9030}{}{ale sám sobì nevìøím.}
{9031}{}{**END-PAR**}
# -
{9032}{}{• 15. øíjen 2077}
{9033}{}{Znovu jsem zkoušel promluvit pøes dveøe s plukovníkem, }
{9034}{}{ale vypadá to, e definitivnì ztratil kontakt s realitou.}
{9035}{}{Spolu s nìkolika mui jsme vyrazili dveøe právì}
{9036}{}{vèas abychom vidìli jeho hlavu vybuchnout. Ještì pøedtím }
{9037}{}{ne zmáèkl spouš øekl, e toho všeho velmi lituje.}
{9038}{}{**END-PAR**}
# -
{9039}{}{• 18. øíjen 2077}
{9040}{}{Vypadá to, e zabitím pana Velkého Teoretika jsem }
{9041}{}{si vytvoøil pozici vùdce. Mui mì teï poslouchají }
{9042}{}{na slovo. Vıslechy vìdcù konèí standardnì jejich popravou.}
{9043}{}{Nejdéle zapírala šéfová projektu, ale koneènı vısledek }
{9044}{}{byl ten samı jako u ostatních. Její argumenty o rozkazech}
{9045}{}{shora byly nedostaèující. Zaèínám z toho všeho mít}
{9046}{}{opravdu špatnı pocit a bojím se, jak to nakonec}
{9047}{}{skonèí. U nedokáu nadále lhát sám sobì }
{9048}{}{o svıch dùvodech k popravám vìdcù.}
{9049}{}{**END-PAR**}
# -
{9050}{}{• 20. øíjen 2077}
{9051}{}{Dnes jsem koneènì odvysílal report na velitelství.}
{9052}{}{Poøád nechápu, proè sem ještì nikoho neposlali, aby tu }
{9053}{}{zjistil, co se stalo, e jsme pøestali odpovídat na jejich}
{9054}{}{vysílání. Ale u na tom nezáleí}
{9055}{}{No dobøe, tak teï tedy pøijdou. Oznámil jsem jim naše vystoupení}
{9056}{}{z unie. Co o mnì asi øeknou budoucí historici?}
{9057}{}{**END-PAR**}
# -
{9058}{}{• 22. øíjen 2077}
{9059}{}{Co se to tam sakra dìje? Oznámili jsme naší úplnou}
{9060}{}{dezerci z armády a e nebudeme nadále pøijímat}
{9061}{}{rozkazy vlády a co se stalo? Nic.}
{9062}{}{Tohle se mi nechce líbit.}
{9063}{}{**END-PAR**}
# -
{9064}{}{• 23. øíjen 2077}
{9065}{}{Poøád nemùu uvìøit, e to ti bastardi nakonec udìlali.}
{9066}{}{A se všichni smaí v pekle. Nechali odpálit nukleární rakety.}
{9067}{}{Von Felden se z nás právì snail vypáèit, co se tu opravdu }
{9068}{}{stalo, kdy jsme s ním najednou kompletnì ztratili spojení.}
{9069}{}{Cítím v kostech, e vızkumná základna byla tìce zasaena. Nevím proè, }
{9070}{}{øíkejte si tomu pro mì za mì „tušení“. Je nepochopitelné, }
{9071}{}{e na nás dosud ádnı útok nesmìøoval. Ale jsem si jistı, }
{9072}{}{e svùj omyl u nebude mít Èína pøíleitost napravit. Naštìstí}
{9073}{}{jsme u vèera pøestìhovali naše rodiny z okolních domkù}
{9074}{}{na základnu. Poøád ještì nevíme jestli spad zasáhl}
{9075}{}{i naši oblast.}
{9076}{}{**END-PAR**}
# -
{9077}{}{• 25. øíjen 2077}
{9078}{}{Serant Platner se nabídl k dobrovolnému vıletu na povrch, }
{9079}{}{aby mohl provést mìøení atmosféry. Zatím to vypadá,}
{9080}{}{e se radiace a o tolik nezvıšila. Protoe mìl obleèené}
{9081}{}{svoji energo zbroj, nehrozilo mu akutní nebezpeèí ozáøení.}
{9082}{}{Ale pokud by byl zasaen, musel bych ho nechat vyhostit.}
{9083}{}{Na základnì není ádné odpovídající }
{9084}{}{dekontaminaèní zaøízení.}
{9085}{}{**END-PAR**}
# -
{9086}{}{• 26. øíjen 2077}
{9087}{}{Pøesvìdèil jsem svoje mue, e bychom mìli dùstojnì pohøbít vìdce. }
{9088}{}{Ani nevím proè... moná jsem tím chtìl ulehèit svému svìdomí.}
{9089}{}{Koneènì jsem zaèal vìøit jejich historkám, teï kdy u je}
{9090}{}{poslední z nich po smrti.  }
{9091}{}{**END-PAR**}
# -
{9092}{}{Mùj boe, co se to ze mnì stalo? }
{9093}{}{**END-PAR**}
# -
{9094}{}{• 27. øíjen 2077}
{9095}{}{Dnes opouštíme tohle bohem zatracené místo. Vedu tenhle }
{9096}{}{exodus do starého vládního bunkru v Lost Hills.}
{9097}{}{Ponechávám tu tenhle záznam pohøbenı a odevzdávám ho}
{9098}{}{i s celım tímhle místem jeho osudu. Kdo ví, moná}
{9099}{}{ho jednoho dne nìkdo najde...}
{9100}{}{**END-DISK**}

# *** Sophia Disk ***
{10000}{}{Exodus z té prokleté základny byl èasem zkoušky pro}
{10001}{}{mue i jejich rodiny. Zatímco okolo nebyl témìø }
{10002}{}{ádnı radioaktivní spad s ním by se museli potıkat,}
{10003}{}{byli obklopeni spadem lidskosti. Potulné bandy }
{10004}{}{psychotickıch lupièù se neustále pokoušeli napadat}
{10005}{}{tuto vznešenou skupinu. }
{10006}{}{**END-PAR**}
# -
{10007}{}{Skupina sama nebyla v nebezpeèí, díky tomu, e mìli}
{10008}{}{obleèeno posvátné Brnìní moci. Èlenové jejich rodin }
{10009}{}{ale takové štìstí nemìli. A jakmile ta okolní chátra }
{10010}{}{zjistila, jak snadnım jsou cílem, zaèala na neozbrojené }
{10011}{}{civilisty støílet z bezpeèné vzdálenosti. }
{10012}{}{**END-PAR**}
# -
{10013}{}{Pro kadého èlena Exodu znamenala cesta ještì mnoho }
{10014}{}{bolestnıch ztrát. Za kadého èlena Exodu, kterı takto padl,}
{10015}{}{si naši šlechetní bratøi vzali dva ivoty z pustiny.}
{10016}{}{**END-PAR**}
# -
{10017}{}{Koneènì naši praotcové dorazili do bezpeèí }
{10018}{}{bunkru. Kapitán Maxson, náš velkı Osvoboditel ho}
{10019}{}{vyhlásil naším novım domovem a tak se také stalo.}
{10020}{}{**END-PAR**}
# -
{10021}{}{Bìhem èasu se stal tento bunkr naším domovem, naším}
{10022}{}{chrámem a naší spásou pøed terorem vnìjšího svìta.}
{10023}{}{Zaèali jsme naši pevnost budovat a utváøet v}
{10024}{}{nìco slavného, v krásu, kterou tento o technologii }
{10025}{}{oloupenı svìt dosud nevidìl.}
{10026}{}{**END-PAR**}
# -
{10027}{}{Ale stále ještì mezi námi byli takoví, kdo touili mít}
{10028}{}{ještì víc. Tyto nepokojné duše poadovali, abychom se }
{10029}{}{vypravili na jihovıchod, pátrat po dokonalejší}
{10030}{}{technologii, která tam mìla bıt uloena.}
{10031}{}{**END-PAR**}
# -
{10032}{}{Kapitán Maxson tyto prudké mladíky varoval, e}
{10033}{}{vızkumná základna byla témìø urèitì znièena, ale}
{10034}{}{oni nechtìli naslouchat jeho slovùm.}
{10035}{}{Oblékli si posvátnou zbroj a odešli hledat svùj}
{10036}{}{Svatı Grál. Pøedtím však pyšnì mluvili o našem}
{10037}{}{Osvoboditeli a zpochybòovali jeho odvahu!}
{10038}{}{**END-PAR**}
# -
{10039}{}{A nikdy jsme ji o tìch muích neslyšeli.}
{10040}{}{**END-DISK**}

# *** Maxson Disk ***
{11000}{}{Po náhlé smrti plukovníka Roberta Spindela jsem se}
{11001}{}{stal velícím dùstojníkem základny. Z mého pøíkazu}
{11002}{}{bylo veškeré osazenstvo bezpeènostního tımu základny}
{11003}{}{pøemístìno do vládního bunkru v Lost Hills.}
{11004}{}{**END-PAR**}
# -
{11005}{}{Tento pokyn zahrnuje rovnì rodiny dùstojníkù}
{11006}{}{a dobrovolníky.}
{11007}{}{**END-PAR**}
# -
{11008}{}{Do doby ne bude øádnım zástupcem }
{11009}{}{Ministerstva Obrany naøízeno jinak, zùstává }
{11010}{}{tento pøíkaz v platnosti.}
{11011}{}{**END-PAR**}
# -
{11012}{}{Pokyn 1: Veškerı vojenskı personál i jejich rodiny }
{11013}{}{vyklidí bázi k 25. øíjnu 2077 do 08.00 hod. Všichni, na }
{11014}{}{které se vztahuje tento pøíkaz se pøemístí do báze}
{11015}{}{ve Ztracenıch Horách. Dezerce nebude tolerována.}
{11016}{}{**END-PAR**}
# -
{11017}{}{Pokyn 2: Všem civilním zamìstnancùm se a do }
{11018}{}{obdrení dalších pokynù z jejich velitelství}
{11019}{}{naøizuje zùstat na základnì.}
{11020}{}{**END-PAR**}
# -
{11021}{}{Pokyn 3: Vybavení pokládané za nezbytné k pøeití}
{11022}{}{vojenského personálu základny, mu bude ze skladù }
{11023}{}{neprodlenì vydáno. Dùstojníkùm bude za tímto úèelem}
{11024}{}{vystaveno speciální povolení.}
{11025}{}{**END-PAR**}
# -
{11026}{}{Pokyn 4: Protoe se jedná o váleènou operaci,}
{11027}{}{vztahují se s okamitou platností na veškerı vojenskı }
{11028}{}{i civilní personál báze vojenská naøízení a zákony.}
{11029}{}{**END-PAR**}
# -
{11030}{}{Pokyn 5: Do doby, ne bude zøízeno trvalé }
{11031}{}{a autorizované spojení s Ministerstvem Obrany, }
{11032}{}{budou tato naøízení precedentní i pro}
{11033}{}{všechny budoucí rozkazy.}
{11034}{}{**END-PAR**}
# -
{11035}{}{Kapitán Maxson}
{11036}{}{24. øíjen 2077}
{11037}{}{**END-DISK**}

# *** Richard Grey audio diary ***
{12000}{}{                                                    0000 - 0004}
{12001}{}{Umírám. Tohle musím dopsat døív, ne mì ta bolest}
{12002}{}{definitivnì zlomí.}
{12003}{}{**END-PAR**}
# -
{12004}{}{Záznam: o0044 -o0057}
{12005}{}{Nemùu uvìøit, e se mi nakonec podaøilo vyškrábat se}
{12006}{}{ven z té nádre. Ten sliz mi fyzicky nijak neublíil, ale}
{12007}{}{málem jsem se v nìm utopil. Ani nevím, co se stalo s}
{12008}{}{Haroldem. Stál hned vedle, kdy mì ten jeøáb srazil do}
{12009}{}{nádre. Musel bıt zabit, jinak by se mi urèitì pokusil}
{12010}{}{pomoci. Francine je mrtvá, zabil ji}
{12011}{}{jeden z tìch robotù.}
{12012}{}{**END-PAR**}
# -
{12013}{}{Záznam: o0058 -o0096}
{12014}{}{Ani nevím, kolik èasu u prošlo. Podaøilo se mi hacknout}
{12015}{}{se do poèítaèe, vypnout roboty a spustit tohle }
{12016}{}{nahrávání, ale teï mám pocit, jako by moje vìdomí }
{12017}{}{chvílemi odplouvalo pryè. V mé hlavì u je jenom bolest...}
{12018}{}{**END-PAR**}
# -
{12019}{}{Záznam: o0028 -o0043}
{12020}{}{Ten zelenı sliz, do kterého jsem spadl, je právì ten}
{12021}{}{hledanı zdroj všech tìch mutací okolo. Moje kùe hnisá}
{12022}{}{a odlupuje se. Na jinıch místech zase vytváøí puchıøe }
{12023}{}{a z nich zaèíná vytékat nìjaká zelená hlenovitá}
{12024}{}{substance. Ale jsou dny, kdy se bolest dá i vydret.}
{12025}{}{**END-PAR**}
# -
{12026}{}{Záznam: o0044 -o0057}
{12027}{}{U dokáu zase ujít i nìkolik metrù... Teï se mi zdá}
{12028}{}{nepochopitelné, e jsem se dokázal vyškrábat celou tu}
{12029}{}{cestu od nádrí a sem. Kupodivu se u ale cítím }
{12030}{}{silnìjší i kdy mám stále ještì bolesti. A taky se }
{12031}{}{mi zdá, jako by se všechno kolem mnì zmenšovalo.}
{12032}{}{**END-PAR**}
# -
{12033}{}{Záznam: o0058 -o0096}
{12034}{}{Myslím, e jsem dnes snìdl jednu z tìch mutovanıch vìcí,}
{12035}{}{co tu okolo cupitají. Døíve, ne jsem si staèil uvìdomit}
{12036}{}{co se dìje, vymrštilo se z mého bøicha nìjaké chapadlo}
{12037}{}{a chytilo toho ubohého tvoreèka. A v okamiku, kdy }
{12038}{}{vtáhlo toho hlodavce do mıch støev, pocítil jsem dotek}
{12039}{}{jeho myšlenek. Aspoò myslím. Je taky docela}
{12040}{}{pravdìpodobné, e se ze mnì pomalu stává šílenec}
{12041}{}{a nejsem u schopen rozlišovat, co je skuteènost a co}
{12042}{}{halucinace. A moná, e ve skuteènosti právì teï }
{12043}{}{umírám v té nádri a všechno tohle je jen má pøedstava.}
{12044}{}{**END-PAR**}
# -
{12045}{}{Záznam: o0097 -o0111}
{12046}{}{Všechno mi kadım dnem pøipadá jasnìjší a zøetelnìjší.}
{12047}{}{Ten toxin opravdu zdokonalil mojí mysl. Cítím, e i tìm}
{12048}{}{nejsloitìjším filosofickım otázkám dokáu porozumìt}
{12049}{}{pøímo a jednoduše. Je mi, jako by nìco odlouplo všechny}
{12050}{}{vrstvy a závoje z mého mozku. Co by se asi stalo,}
{12051}{}{kdybych ponoøil jedno z tìch zvíøat do nádre}
{12052}{}{na trochu delší dobu? Mohlo by tak získat vìdomí?}
{12053}{}{**END-PAR**}
# -
{12054}{}{Záznam: o0112 -o0134}
{12055}{}{S tìmi zvíøaty se dìjí ty nejpodivuhodnìjší vìci.}
{12056}{}{Stávají se chytøejšími a mnohem víc se zajímají o své}
{12057}{}{okolí. A jednou jsem ponoøil najednou psa a krysu}
{12058}{}{a oni se SPOJILI dohromady. Nejsou to u dva oddìlení}
{12059}{}{tvorové, ale je to i víc ne jenom jeden.}
{12060}{}{Moná, e tohle je budoucnost - spojit rùzné tvory }
{12061}{}{dohromady do jedné jediné, harmonické jednoty.}
{12062}{}{Teï u nejím vytváøená zvíøata jen pro vıivu,}
{12063}{}{teï se stávám nástrojem skrz kterı bude}
{12064}{}{dosaena jednota tvorstva. Jsem u mnohem víc}
{12065}{}{ne jen pouhı èlovìk.}
{12066}{}{**END-PAR**}
# -
{12067}{}{Záznam: o0135 -o0139}
{12068}{}{Nastává èas pøivést ostatní tvory ke slávì a míru, }
{12069}{}{které nám pøinese Jednota.}
{12070}{}{**END-PAR**}
# -
{12071}{}{Záznam: o0140 -o0153}
{12072}{}{Do mého domova koneènì zabloudila jedna ztracená duše.}
{12073}{}{Byl jsem tak pøekvapenı, e jsem ho pohltil ještì pøed}
{12074}{}{ponoøením. Chyba, kterou u nesmím opakovat. Jeho mysl}
{12075}{}{byla pro mé nové poznávací schopnosti pøíliš primitivní.}
{12076}{}{**END-PAR**}
# -
{12077}{}{Záznam: o0154 -o0172}
{12078}{}{Sliz v nádrích je virus zvanı Forced Evolutionary Virus.}
{12079}{}{Informaci jsem získal z mé novì vypìstované neurolinky}
{12080}{}{s poèítaèem základny. Abych byl pøipraven pro úkol, kterı}
{12081}{}{jsem si vytknul, zaèal jsem mìnit sám sebe vstøikováním}
{12082}{}{malıch dávek viru do rùznıch èástí svého tìla.}
{12083}{}{**END-PAR**}
# -
{12084}{}{Záznam: o0173 -o0198}
{12085}{}{Tìch pár poutníkù, kteøí sem našli cestu pro mì}
{12086}{}{znamenalo velké zklamání. Vypadá to, e nemutují }
{12087}{}{správnım zpùsobem. To nejlepší, co jsem byl schopen }
{12088}{}{vytvoøit, je pár velkıch tupıch mutantù. Vìtšina z nich }
{12089}{}{si nepamatuje vùbec nic z doby, ne jsem je povolal do}
{12090}{}{naší úasné Jednoty. Pouívám je jen jako potravu. }
{12091}{}{Z jejich myslí nezískávám nic.}
{12092}{}{**END-PAR**}
# -
{12093}{}{Záznam: o0199 -o0236}
{12094}{}{Oh velkı stvoøiteli!! Koneènì se mi podaøilo pocítit radost}
{12095}{}{z dokonalého splynutí s další duší! Ale tenhle nebyl jako}
{12096}{}{ostatní, jeho stupeò ozáøení byl velmi nízkı. Vìøím, e}
{12097}{}{to je ten faktor, kterı jsme celou tu dobu pøehlíeli.}
{12098}{}{Zdá se, e konverze je úspìšnìjší, pokud subjekt}
{12099}{}{neutrpìl ádné vìtší poškození radiací. Ještì nikdy jsem}
{12100}{}{nepocítil takovou slast, jako pøi pohlcování jeho mysli.}
{12101}{}{**END-PAR**}
# -
{12102}{}{Záznam: o0237 -o0281}
{12103}{}{Zaèínáme vytváøet armádu, která svùj smysl zasvìtí}
{12104}{}{sjednocení veškeré podivuhodné rozmanitosti ivota.}
{12105}{}{Vytrénovali jsme je tak, aby byli schopni pokraèovat }
{12106}{}{v naší práci zde, zatímco my vyhledáme více obydlenou.}
{12107}{}{oblast, abychom do sebe mohli pøijmout její obyvatele.}
{12108}{}{Zaèínáme pociovat úbytek vhodnıch tìl. Musíme najít}
{12109}{}{místo se zdrojem vìdomostí a stálım pøísunem biomasy.}
{12110}{}{**END-PAR**}
# -
{12111}{}{Záznam: o0282 -o0303}
{12112}{}{Pøestali jsme se zvìtšovat do doby ne toto naše nové}
{12113}{}{unifikaèní centrum najdeme. A dorazíme na ono místo, }
{12114}{}{budeme pokraèovat v jídle a rùstu, dokud nepøineseme}
{12115}{}{mír a jednotu celému svìtu.}
{12116}{}{**END-DISK**}

# *** Captain Maxson's Diary ***
{13000}{}{• 10. øíjen, 2077}
{13001}{}{Já, Roger Maxson, kapitán, èíslo 072389 jsem zaèal psát}
{13002}{}{tento záznam proto, e to teï s námi nevypadá pøíliš}
{13003}{}{rùovì a já chci aby se budoucí lidé mohli dozvìdìt, co}
{13004}{}{se tu doopravdy stalo. Všechno to peklo zaèalo, kdy}
{13005}{}{jsme koneènì objevili, co tu ti bastardi v bílıch pláštích}
{13006}{}{provádìjí. Plukovník se zamknul ve své kanceláøi a }
{13007}{}{vypadá to, e se naprosto psychicky zhroutil. Moji mui}
{13008}{}{volají po krvi. Hledají u mì odpovìdi na své otázky,}
{13009}{}{ale já sám nevím, co mám dìlat. Nìkdo by mìl nìco}
{13010}{}{udìlat, døív, ne se tohle místo zmìní}
{13011}{}{v krvavou lázeò.}
{13012}{}{**END-PAR**}
# -
{13013}{}{• 12. øíjen 2077}
{13014}{}{Pokadé, kdy dostaneme zprávu shora, všechno se}
{13015}{}{tu pøiostøí. Válka se vyvíjí velmi špatnım smìrem}
{13016}{}{a tohle místo se vším tím chaosem okolo, je na }
{13017}{}{nejlepší cestì k úplné vzpouøe. Dnes jsem zabránil }
{13018}{}{rvaèce jednoho z mıch muù s vìdcem a poádal vìdce,}
{13019}{}{aby nám vyloili, co je úèelem jejich vızkumu.}
{13020}{}{**END-PAR**}
# -
{13021}{}{• 13. øíjen 2077}
{13022}{}{Dnes jsem zabil èlovìka. Vyslechl jsem šéfa vìdcù}
{13023}{}{Andersona a on mi popsal naprosto detailnì jejich}
{13024}{}{nelidské experimenty. Øíkal, e dostal rozkazy pøímo}
{13025}{}{ze sídla vlády, ale já tomu nevìøím. Zaèal køièet nìco}
{13026}{}{o tom jak jen poslouchá rozkazy a o vojenském duchu}
{13027}{}{a já ho zastøelil. Øíkám si, e jsem to udìlal proto,}
{13028}{}{abych zabránil úplné vzpouøe, ale sám sobì nevìøím.}
{13029}{}{**END-PAR**}
# -
{13030}{}{• 15. øíjen 2077}
{13031}{}{Znovu jsem zkoušel promluvit pøes dveøe s plukovníkem,}
{13032}{}{ale vypadá to, e definitivnì ztratil kontakt s realitou.}
{13033}{}{Spolu s nìkolika mui jsme vyrazili dveøe právì vèas}
{13034}{}{abychom vidìli jeho hlavu vybuchnout. Ještì pøedtím}
{13035}{}{ne zmáèkl spouš øekl, e toho všeho velmi lituje.}
{13036}{}{**END-PAR**}
# -
{13037}{}{• 18. øíjen 2077}
{13038}{}{Vypadá to, e zabitím pana Velkého Teoretika jsem}
{13039}{}{si vytvoøil pozici vùdce. Mui mì teï poslouchají}
{13040}{}{na slovo. Vıslechy vìdcù konèí standardnì jejich}
{13041}{}{popravou. Nejdéle zapírala šéfová projektu, ale }
{13042}{}{koneènı vısledek byl ten samı jako u ostatních.}
{13043}{}{Její argumenty o rozkazech shora byly nedostaèující.}
{13044}{}{Zaèínám z toho všeho mít opravdu špatnı pocit a bojím }
{13045}{}{se jak to nakonec skonèí. U nedokáu nadále lhát }
{13046}{}{sám sobì o svıch dùvodech k popravám vìdcù.}
{13047}{}{**END-PAR**}
# -
{13048}{}{• 20. øíjen 2077}
{13049}{}{Dnes jsem koneènì odvysílal report na velitelství.}
{13050}{}{Poøád nechápu, proè sem ještì nikoho neposlali, aby}
{13051}{}{tu zjistil co se stalo, e jsme pøestali odpovídat}
{13052}{}{na jejich vysílání. Ale u na tom nezáleí.}
{13053}{}{No dobøe, tak teï tedy pøijdou. Oznámil jsem jim naše }
{13054}{}{vystoupení z unie. Dìjiny si pamatují Jeffersona Davise.}
{13055}{}{Co budou øíkat historici o mnì?}
{13056}{}{**END-PAR**}
# -
{13057}{}{• 22. øíjen 2077}
{13058}{}{Co se to tam sakra dìje? Oznámili jsme naší úplnou}
{13059}{}{dezerci z armády a e nebudeme nadále pøijímat}
{13060}{}{rozkazy vlády a co se stalo? Nic.}
{13061}{}{Tohle se mi nechce líbit.}
{13062}{}{**END-PAR**}
# -
{13063}{}{• 23. øíjen 2077}
{13064}{}{Poøád nemùu uvìøit, e to ti bastardi nakonec udìlali.}
{13065}{}{A se všichni smaí v pekle. Nechali odpálit nukleární}
{13066}{}{rakety. Von Felden se z nás právì snail vypáèit, co se }
{13067}{}{tu opravdu stalo, kdy jsme s ním najednou kompletnì}
{13068}{}{ztratili spojení. Cítím v kostech, e vızkumná základna}
{13069}{}{byla tìce zasaena. Nevím proè øíkejte si tomu pro mì a}
{13070}{}{za mì „tušení“. Je nepochopitelné e na nás dosud ádnı}
{13071}{}{útok nesmìøoval. Ale jsem si jistı, e svùj omyl u}
{13072}{}{nebude mít Èína pøíleitost napravit. Naštìstí jsme u }
{13073}{}{vèera pøestìhovali naše rodiny z okolních domkù na}
{13074}{}{základnu. Poøád nevíme jestli spad zasáhl i naši oblast.}
{13075}{}{**END-PAR**}
# -
{13076}{}{• 25. øíjen 2077}
{13077}{}{Serant Platner se nabídl k dobrovolnému vıletu na}
{13078}{}{povrch, aby mohl provést mìøení atmosféry. Zatím to}
{13079}{}{vypadá, e se radiace a o tolik nezvıšila. Protoe}
{13080}{}{mìl obleèenou svoji energozbroj, nehrozilo mu akutní}
{13081}{}{nebezpeèí ozáøení. Ale pokud by byl zasaen, musel bych }
{13082}{}{ho nechat vyhostit. Na základnì toti není ádné}
{13083}{}{odpovídající dekontaminaèní zaøízení.}
{13084}{}{**END-PAR**}
# -
{13085}{}{• 26. øíjen 2077}
{13086}{}{Pøesvìdèil jsem svoje mue, e bychom mìli pohøbít vìdce.}
{13087}{}{Ani nevím proè... moná jsem chtìl ulehèit svému svìdomí.}
{13088}{}{Kdy poslední z nich umíral, zaèal jsem vìøit jejich}
{13089}{}{historkám. Mùj boe, co se to ze mnì stalo?}
{13090}{}{**END-PAR**}
# -
{13091}{}{• 27. øíjen 2077}
{13092}{}{Dnes opouštíme tohle bohem zatracené místo. Vedu tenhle}
{13093}{}{exodus do starého vládního bunkru v Lost Hills.}
{13094}{}{Ponechávám tu tenhle záznam pohøbenı a odevzdávám ho}
{13095}{}{i s celım tímhle místem jeho osudu. Kdo ví, moná}
{13096}{}{ho jednoho dne nìkdo najde...}
{13097}{}{**END-DISK**}


# Computer Download of the FEV project
# Uses the global var COMPUTER_FEV

{14000}{}{Historie vızkumu FEV:}
{14001}{}{**END-PAR**}
{14002}{}{2073. Jak se s rozvojem jejich biologickıch zbraní}
{14003}{}{postupnì zvyšovala i agresivita Èíny, cítila vláda}
{14004}{}{Spojenıch Státù nutnost protiopatøení. Z tohoto}
{14005}{}{dùvodu byl 15-tého záøí 2073 oficiálnì zahájen}
{14006}{}{projekt Pan-Imunitního Viru (PIV). }
{14007}{}{**END-PAR**}
#
{14008}{}{2075. Stále zøetelnìji se ukazuje, e nejlepší zpùsob}
{14009}{}{jak bojovat s novì vytváøenımi biologickımi zbranìni}
{14010}{}{je prostøednictvím modifikované DNK, tak aby tato u}
{14011}{}{nebyla nadále citlivá vùèi standardním virovım infekcím.}
{14012}{}{**END-PAR**}
#
{14013}{}{2076. Velice brzy po zahájení projektu PIV se objevují}
{14014}{}{nepøedvídané vedlejší efekty. Testy na zvíøecích}
{14015}{}{subjektech naznaèují abnormální rychlost rùstu svalové}
{14016}{}{i kostní tkánì, spojené se zvıšením mozkové aktivity.}
{14017}{}{Vláda USA obdrela kompletní zprávu o tìchto objevech}
{14018}{}{a v zájmu národní bezpeènosti se rozhodla pøemístit}
{14019}{}{vızkumnı tım na støeené místo. Projekt dostal TOP}
{14020}{}{prioritu a oznaèení FEV (Forced Evolutionary Virus).}
{14021}{}{**END-PAR**}
#
{14022}{}{2077. Projekt FEV se blíí úspìšnému zakonèení. Testy}
{14023}{}{na laboratorních zvíøatech jsou témìø 100%-nì úspìšné.}
{14024}{}{Velikost i hustota svalovıch vláken se v prùmìru zvyšují}
{14025}{}{o 60%. Hodnota mìøitelné inteligence se zvyšuje o 200%.}
{14026}{}{I kdy je teoreticky popsán, efekt na lidské subjekty}
{14027}{}{zùstává dosud neznámı. Protoe si vláda pøeje}
{14028}{}{pokraèovat v dalším testování, je vybudováno velké}
{14029}{}{vızkumné zaøízení v lokaci Mariposa v centrální}
{14030}{}{Kalifornii. V této nové základnì se pokraèuje }
{14031}{}{v testování FEV viru na dobrovolnících z øad armády.}
{14032}{}{**END-DISK**}


# Computer Download of the Power Armor Specs
# Uses the global var COMPUTER_POWER_ARMOR

{15000}{}{Model T-51b Aktivní Pìchotní Brnìní (zkrácenì Energo}
{15001}{}{zbroj) je zkonstruován s vyuitím nejmodernìjších}
{15002}{}{ochrannıch prvkù a to pro civilní i vojenské pouití.}
{15003}{}{Micro-fúzní reaktor TX-28 generuje 60.000 Wattù pro}
{15004}{}{napájení hydraulickıch systémù zabudovanıch pøímo v}
{15005}{}{obleku. Povrch obleku T-51b je vyroben z velice lehkıch}
{15006}{}{polylaminátovıch kompozitù a dokáe absorbovat více ne}
{15007}{}{2.500 Joulù kinetické energie na ètvereèní centimetr.}
{15008}{}{Pláš ze støíbra o tloušce 10 mikronù je schopen}
{15009}{}{odrazit laserové a radiaèní emise bez vìtšího poškození.}
{15010}{}{**END-DISK**}


# Computer Download of the Personnel Records
# Uses the global var COMPUTER_RECORDS

{16000}{}{Robert Anderson}
{16001}{}{Vızkumník-Asistent}
{16002}{}{Bezpeènostní provìøení: Modrá}
{16003}{}{Umístìní: Vojenská základna Mariposa}
{16004}{}{**END-PAR**}
#
{16005}{}{Nick Davis}
{16006}{}{Øeditel divize NBC základny West Tech}
{16007}{}{Bezpeènostní provìøení: Modrá}
{16008}{}{Umístìní: Vızkumné zaøízení West Tech}
{16009}{}{**END-PAR**}
#
{16010}{}{John Isaac}
{16011}{}{Vızkumník-Asistent}
{16012}{}{Bezpeènostní provìøení: Èervená}
{16013}{}{Umístìní: Vızkumné zaøízení West Tech}
{16014}{}{**END-PAR**}
#
{16015}{}{Steve Remco}
{16016}{}{Vızkumník-Asistent}
{16017}{}{Bezpeènostní provìøení: Modrá}
{16018}{}{Umístìní: Vojenská báze Mariposa}
{16019}{}{**END-PAR**}
#
{16020}{}{Charles Rignhold}
{16021}{}{Vedoucí vızkumu Laserovıch zbraní}
{16022}{}{Bezpeènostní provìøení: Modrá}
{16023}{}{Umístìní: Vızkumné zaøízení West Tech}
{16024}{}{**END-PAR**}
#
{16025}{}{Michele Santose}
{16026}{}{Technik-laborant}
{16027}{}{Bezpeènostní provìøení: Èervená}
{16028}{}{Umístìní: Vızkumné zaøízení West Tech}
{16029}{}{**END-PAR**}
#
{16030}{}{Erin Shellmanová}
{16031}{}{Technik-laborant}
{16032}{}{Bezpeènostní provìøení: Modrá}
{16033}{}{Umístìní: Vojenská základna Mariposa}
{16034}{}{**END-PAR**}
#
{16035}{}{Leon VonFelden}
{16036}{}{Vedoucí vızkumu FEV}
{16037}{}{Bezpeènostní provìøení: Modrá}
{16038}{}{Umístìní: Vojenská základna Mariposa}
{16039}{}{**END-DISK**}

# Holodisk from the Brotherhood Library
# uses the global var BROTHERHOOD_LIBRARY_DISK

{17000}{}{Lokace Vaultù v34.129 revize C (Západ USA)}
{17001}{}{**END-PAR**}
#
{17002}{}{Ahoj a vítej v nejèerstvìjší edici propagaèní broury}
{17003}{}{spoleènosti Vault Tec. pro oblast USA-západ. Doufáme,}
{17004}{}{e se ti naše brourka zalíbí a pamatuj, e Vault není}
{17005}{}{jen pro horních deset tisíc, ale skuteènì pro kadého.}
{17006}{}{**END-PAR**}
#
{17007}{}{Vault 12}
{17008}{}{**END-PAR**}
#
{17009}{}{Pøímo pod rozsáhlou metropolí Bakersfield, leí}
{17010}{}{technologicky pozoruhodnı Vault 12. Byl vybudován}
{17011}{}{s ohledem na maximální pohodlí jeho budoucích obyvatel.}
{17012}{}{Vaultu 12 bylo udìleno ocenìní „Vault Roku“}
{17013}{}{za jeho zvláštní pozornost k neustálé pohotovosti.}
{17014}{}{Pohøben hluboko pod zemí poskytne svım obyvatelùm}
{17015}{}{bezprecedentní ochranu. Stejnì jako ostatní}
{17016}{}{Vaulty, byl i Vault 12 vybaven nejmodernìjším systémem}
{17017}{}{èištìní a dekontaminace vody. Tento systém je schopen}
{17018}{}{pøefiltrovat veškerı odpad v kanálech Bakersfieldu a}
{17019}{}{mùe tak dodávat a 15,000 galonù èisté,}
{17020}{}{osvìující pitné vody dennì.}
{17021}{}{**END-PAR**}
#
{17022}{}{Vault 13}
{17023}{}{**END-PAR**}
#
{17024}{}{Poloen v pøekrásném hornatém terénu severozápadnì}
{17025}{}{od Vaultu 12, nabízí tento Vault svım obyvatelùm}
{17026}{}{nekoneèné mnoství èisté vody. Povìsti o tom, e }
{17027}{}{vodní plochy této oblasti mohou bıt v pøípadì }
{17028}{}{nukleární války lehce kontaminovány byly prošetøeny }
{17029}{}{Úøadem pro Vodu a Energii a shledány naprosto}
{17030}{}{bezpøedmìtné. A pro pøípad, e by voda v oblasti byla}
{17031}{}{opravdu zamoøena (jakkoliv je to nepravdìpodobné) byl}
{17032}{}{Vault 13 vybaven vládou atestovanım systémem}
{17033}{}{èištìní a dekontaminace vody. Protoe je tento systém}
{17034}{}{schopen pracovat bez poruch více ne 250,000 hodin,}
{17035}{}{nemají se jeho budoucí obyvatelé èeho obávat.}
{17036}{}{**END-PAR**}
#
{17037}{}{Vault 15}
{17038}{}{**END-PAR**}
#
{17039}{}{Pøímo na vıchod od Vaultu 13 leí Vault 15. Konstrukce}
{17040}{}{a vıstavba tohoto Vaultu probìhla extrémnì hladce}
{17041}{}{a rychle. Zvláštní úsilí bylo vìnováno posílení zdí na}
{17042}{}{tøetím podlaí, k zajištìní bezpeèí všech jeho budoucích}
{17043}{}{obyvatel proti všem událostem, které by mohly nastat}
{17044}{}{a to i vèetnì rozsáhlého zemìtøesení. Nebo i v takovém}
{17045}{}{pøípadì dokáou øídící poèítaèe Vaultu pokraèovat ve}
{17046}{}{své èinnosti. Konkstruèní metody novì stavìnıch}
{17047}{}{Vaultù vedly i k mnoha velmi pozoruhodnım vylepšením}
{17048}{}{provedenım na tomto skuteènì imponujícím Vaultu.}
{17049}{}{**END-DISK**}

#Regulator Disk from Blades

{18000}{}{Monitorované vysílání Regulátorù:}
{18001}{}{**END-PAR**}
{18002}{}{Poslaná zpráva: Patrola Regulátor 1 základnì.}
{18003}{}{Jak mì slyšíte? Pøepínám.}
{18004}{}{**END-PAR**}
{18005}{}{Pøijatá zpráva: Tady báze Regulátorù. Na pøíjmu}
{18006}{}{velitel Caleb. Podejte hlášení. Pøepínám.}
{18007}{}{**END-PAR**}
{18008}{}{Poslaná zpráva: Pane, ano pane! Tady Regulátor druhé tøídy}
{18009}{}{Cravotta. Zase jsme chytili toho Zimmermanova kluka,}
{18010}{}{jak se pokouší dostat do Adytum, pane.}
{18011}{}{Jaké jsou pøíkazy? Pøepínám.}
{18012}{}{**END-PAR**}
{18013}{}{Pøijatá zpráva: Do prdele! U zase! No dobøe, tentokrát u je to}
{18014}{}{definitivnì naposled. Zlikvidujte ho a chci, aby to vypadalo}
{18015}{}{jako, kdyby to udìlali Blades.}
{18016}{}{Jasnı? Pøepínám.}
{18017}{}{**END-PAR**}
{18018}{}{Poslaná zpráva: Pane? Uh... rozumìl jsem správnì, pane?}
{18019}{}{Myslíte, zabít ho? Pøepínám.}
{18020}{}{**END-PAR**}
{18021}{}{Pøijatá zpráva: Pøesnì tak, Regulátore.}
{18022}{}{A chci to poøádnì krvavı. Narate ho na kùl venku pøed stráním}
{18023}{}{stanovištìm - oh, a taky mu vyøíznìte jazyk, aby nemohl køièet,}
{18024}{}{zatímco se budeme pokoušet „zachránit“ tu jeho nešastnou prdel.}
{18025}{}{Jasnı?}
{18026}{}{**END-PAR**}
{18027}{}{Poslaná zpráva: Provedu, pane. Konec.}
{18028}{}{**END-PAR**}
{18029}{}{Konec pøenosu.}
{18030}{}{**END-DISK**}
