#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Rychlý metabolismus}
{101}{}{Rváè}
{102}{}{Mròous}
{103}{}{Jednoruký}
{104}{}{Obratný}
{105}{}{Kamikaze}
{106}{}{Tìžká ruka}
{107}{}{Rychlostøelec}
{108}{}{Krvák}
{109}{}{Poznamenaný}
{110}{}{Dobrák}
{111}{}{Narkoman}
{112}{}{Abstinent}
{113}{}{Noèní pták}  # was: Sex Appeal
{114}{}{Zkušený}
{115}{}{Talentovaný}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{Tvoje látková výmìna je dvakrát rychlejší než u normálních lidí. To znamená, že jsi ménì odolný vùèi radiaci a jedùm, ale tvé tìlo se rychleji léèí z utrpìných zranìní.}
{201}{}{Trochu pomalejší, ale trochu mohutnìjší. Možná svého soupeøe až tak èasto nezasáhneš, ale když ano, tak to setsakramentsky pocítí! Celkové množství tvých Akèních bodù je sníženo, ale tvá Síla je navýšena.}
{202}{}{Nejsi tak vysoký jako ostatní obyvatelé Vaultu, ale to tì nikdy netrápilo. Neuneseš sice moc nákladu, zato jsi pohyblivìjší a mrštnìjší.}
{203}{}{Jedna z tvých rukou je neobvykle dominantní. Vynikáš s jednoruèními zbranìmi, zato ovládání dvouruèních ti dìlá problémy.}
{204}{}{Tvoje útoky vykazují velkou míru obratnosti. Nezpùsobuješ soupeøùm až tolik poškození, zato se ti èastìji podaøí kritický zásah.}
{205}{}{Protože se nièeho nebojíš, mùžeš v boji mnohem døív reagovat. To ponìkud redukuje tvou Tøídu zbroje, ale tvùj postøeh je v boji mnohem rychlejší.}
{206}{}{To že umíš udeøit tvrdìji neznamená také, že to dìláš lépe. Tvé útoky se vyznaèují velkou brutalitou, ale postrádají obratnost. Jen málokdy se ti podaøí kritický zásah, ale vždy nadìláš hodnì škody.}
{207}{}{Nemáš èas na to, abys peèlivì zamìøil svùj útok, protože útoèíš rychleji než druzí. Na druhé stranì tì používání zbraní stojí o 1 AB ménì.}
{208}{}{Nìjakým podivným øízením osudu lidé kolem tebe umírají násilnì. Vždy uvidíš ten nejhorší možný zpùsob, jakým mohou ostatní zemøít.}
{209}{}{Ta dobrá zpráva je, že všem okolo tebe v boji èastìji nìco selže. Ta špatná zpráva je, že se to stává i tobì!}
{210}{}{Bìhem svého života ses zamìøoval pøedevším na studium nebojových umìní. Se svými bojovými schopnostmi zaèínáš na nižším stupni, ale 1. POMOC, DOKTOR, ØEÈ a OBCHOD jsou podstatnì vylepšeny.}
{211}{}{Snadnìji se stáváš závislým na drogách. Tvoje šance stát se závislým jsou dvojnásobné, ale na druhé stranì se ze závislosti zotavuješ rychleji.}
{212}{}{Drogy mají na tvou postavu jen polovièní efekt, ale tvé šance stát se na nich závislým jsou rovnìž jen 50%-ní oproti ostatním lidem.}
{213}{}{Jako noèní pták jsi èilejší po západu slunce. INTELIGENCE a VNÍMAVOST jsou bìhem noci na vyšší úrovni, ale pøes den ochabují.}
{214}{}{Protože jsi zlepšování svých schopností vìnoval víc èasu než ostatní, obdržíš v každé úrovni navíc 5 bodù. Výmìnou za to získáš extra schopnost (Perk) jen jednou za ètyøi úrovnì.}
{215}{}{Máš více vrozených schopností než ostatní. Tvoje primární vlastnosti budou každá povýšena o 1, ale do zaèátku ztratíš 10% na všech schopnostech. Pøi postupu na vyšší úroveò obdržíš o 5 bodù schopností ménì.}
