/*

	Encounter - Generic Raider

*/

#include "..\headers\define.h"

#define NAME                    SCRIPT_GENRAIDA
#define TOWN_REP_VAR            (GVAR_TOWN_REP_RAIDERS)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;

variable tmp_hostile;
variable initial := 0;
variable scared;

procedure start begin
	if not(initial) then begin
		initial := 1;
		set_self_team(TEAM_RAIDERS);
		set_self_ai(20 + random(0, 1));
	end
end

procedure critter_p_proc begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		scared := 1;
		attack(dude_obj);
	end
	else begin
		if (tile_distance_objs(self_obj, dude_obj) < 12) then begin
			if (scared) then begin
				call flee_dude;
			end
			else begin
				tmp_hostile := 1;
			end
		end
	end
end

procedure destroy_p_proc begin
	inc_evil_critter
end

procedure pickup_p_proc begin
	if (not(scared)) then begin
		tmp_hostile := 1;
	end
end
