#include "..\headers\define.h"

procedure start;


procedure start
begin
	if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
		if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
			if (local_var(0) == 0) then begin
				if (get_critter_stat(dude_obj, 4) > 6) then begin
					display_msg(message_str(111, 100));
				end
				else begin
					display_msg(message_str(111, 101));
				end
				set_local_var(0, 1);
			end
		end
	end
end

