#include "..\headers\define.h"

procedure start;
procedure use_p_proc;//    script_action == 6
procedure use_skill_on_p_proc;//    script_action == 8


procedure start
begin
	if (script_action == 6) then begin//use_p_proc - Use, Activate, or Manipulate the Object or Item
		call use_p_proc;
	end
	else begin
		if (script_action == 8) then begin//<-- use_skill_on_p_proc
			call use_skill_on_p_proc;
		end
	end
end

procedure use_p_proc
begin
	if (global_var(WATER_CHIP_5) == 0) then begin
		set_global_var(WATER_CHIP_5, 1);
	end
	else begin
		set_global_var(WATER_CHIP_5, 0);
	end
end

procedure use_skill_on_p_proc
begin
	if (action_being_used == 13) then begin//-- REPAIR
		script_overrides;
		display_msg(message_str(864, 100));
	end
	else begin
		if (action_being_used == 12) then begin//-- SCIENCE
			script_overrides;
			display_msg(message_str(864, 101));
		end
	end
end

