/*

	Followers of the Apocalypse - Nicole

*/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_NICOLE
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BONEYARD)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure talk_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;

procedure Nicole00;
procedure Nicole01;
procedure Nicole02;
procedure Nicole04;
procedure Nicole05;
procedure Nicole06;
procedure Nicole07;
procedure Nicole08;
procedure Nicole08a;
procedure Nicole09;
procedure Nicole10;
procedure Nicole11;
procedure Nicole12;
procedure Nicole13;
procedure Nicole14;
procedure Nicole15;
procedure Nicole16;
procedure Nicole17;
procedure Nicole18;
procedure Nicole19;
procedure Nicole20;
procedure Nicole21;
procedure Nicole21a;
procedure Nicole25;
procedure Nicole26;
procedure Nicole27;
procedure Nicole28;
procedure Nicole29;
procedure Nicole30;
procedure Nicole31;
procedure Nicole32;
procedure Nicole33;
procedure Nicole34;
procedure Nicole35;
procedure Nicole36;
procedure Nicole37;
procedure Nicole39;
procedure Nicole41;
procedure Nicole50;
procedure Nicole51;
procedure Nicole52;
procedure Nicole53;
procedure Nicole54;
procedure Nicole55;
procedure Nicole78;
procedure NicoleMore;
procedure NicoleShowOut;
procedure NicoleEnd;

#define LVAR_TALKED_TO_NICOLE 		(4)

variable Only_Once := 1;
variable ThiefFlag;
variable DisplayMessage := 100;

procedure Start begin
	if self_obj != 0 then begin
		set_global_var( GVAR_IS_NICOLE_ALIVE, 1 );
	end
	else begin
		set_global_var( GVAR_IS_NICOLE_ALIVE, 0 );
	end

	if Only_Once then begin
		set_self_team(TEAM_LA_FOLLOWERS );
		Only_Once := 0;
	end
end

procedure map_enter_p_proc begin
   if map_first_run then
      self_caps_adjust( random(50, 150) );
end

procedure look_at_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_NICOLE, 100));
end

procedure description_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_NICOLE, 100));
end

procedure talk_p_proc begin
	dude_look_at_self;

	get_reaction

	if (global_var( GVAR_ENEMY_FOLLOWERS ) == 1) then begin
		float_msg( self_obj, message_str(SCRIPT_ENEMY, random(100, 104)), FLOAT_MSG_RED );
	end
	else begin
		if ((local_var(LVAR_TALKED_TO_NICOLE) == 1) and (dude_iq < 4)) then begin
			float_msg( self_obj, message_str(SCRIPT_NICOLE, 286), FLOAT_MSG_NORMAL );
		end
		else begin
			if (local_var(2) == 0) then begin
				set_local_var(2, 1);
				set_local_var(1, 3);
				LevelToReact
			end
			start_gdialog(54, self_obj, 4, 19, BACKGROUND_FOLLOWER);
			gsay_start;
			if (local_var(LVAR_TALKED_TO_NICOLE) == 0) then begin
				call Nicole01;
			end
			else begin
				DisplayMessage := 132;
				call Nicole00;
			end
			gsay_end;
			end_dialogue;
			if (local_var(5) == 1) then begin
				gfade_in(1);
				set_local_var(5, 0);
			end
		end
	end
end

procedure damage_p_proc begin
	if (source_obj == dude_obj) then begin
		set_global_var( GVAR_ENEMY_FOLLOWERS, 1 );
	end
end

procedure destroy_p_proc begin
	set_global_var( GVAR_IS_NICOLE_ALIVE, 0 );

	if (source_obj == dude_obj) then begin
		inc_good_critter
		set_global_var( GVAR_ENEMY_FOLLOWERS, 1 );
	end
end

procedure critter_p_proc begin
	if (self_can_see_dude) then begin
		if (global_var( GVAR_ENEMY_FOLLOWERS ) == 1) then begin
			attack(dude_obj);
		end
	end
end

procedure pickup_p_proc begin
   //ThiefFlag := 1;
   dialogue_system_enter;
	//set_global_var(ENEMY_FOLLOWERS, 1);
end

procedure Nicole00 begin
	gsay_reply( SCRIPT_NICOLE, DisplayMessage );
	gsay_option( SCRIPT_NICOLE, 101, Nicole29, 50 );
	gsay_option( SCRIPT_NICOLE, 102, Nicole02, 50 );
	if (global_var( GVAR_MASTER_BLOWN ) == 0) then begin
		NOption( 319, Nicole50, 4 );
	end
	gsay_option( SCRIPT_NICOLE, 131, Nicole14, 50 );
end

procedure Nicole01 begin
	gsay_reply( SCRIPT_NICOLE, 105 );
	NOption( 106, Nicole02, 4 );
	BOption( 107, Nicole11, 4 );
	NOption( 108, Nicole09, 4 );
	NOption( 109, Nicole15, 4 );
	NOption( 110, Nicole78, -3 );
	set_local_var(LVAR_TALKED_TO_NICOLE, 1);
end

procedure Nicole02
begin
	gsay_reply( SCRIPT_NICOLE, 111 );
	gsay_option( SCRIPT_NICOLE, 112, Nicole04, 50 );
end

procedure Nicole04
begin
	gsay_reply( SCRIPT_NICOLE, 113 );
	gsay_option( SCRIPT_NICOLE, 114, Nicole05, 50 );
	gsay_option( SCRIPT_NICOLE, 115, Nicole11, 51 );
end

procedure Nicole05
begin
	gsay_reply( SCRIPT_NICOLE, 116 );
	gsay_option( SCRIPT_NICOLE, 117, Nicole06, 50 );
end

procedure Nicole06
begin
	gsay_reply( SCRIPT_NICOLE, 118 );
	gsay_option( SCRIPT_NICOLE, 119, Nicole07, 50 );
	gsay_option( SCRIPT_NICOLE, 123, Nicole08, 50 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 121, Nicole08a, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 121, Nicole11, 51 );
	end
end

procedure Nicole07
begin
	gsay_reply( SCRIPT_NICOLE, 122 );
	gsay_option( SCRIPT_NICOLE, 123, Nicole08, 50 );
	gsay_option( SCRIPT_NICOLE, 124, Nicole28, 50 );
	gsay_option( SCRIPT_NICOLE, 125, Nicole19, 49 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 126, Nicole08a, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 126, Nicole11, 51 );
	end
end

procedure Nicole08
begin
	gsay_message( SCRIPT_NICOLE, 127, 50 );
	DisplayMessage := 129;
	call NicoleMore;
end

procedure Nicole08a
begin
	gsay_message( SCRIPT_NICOLE, 128, 50 );
	DisplayMessage := 129;
	call NicoleMore;
end

procedure Nicole09
begin
	DisplayMessage := 132;
	call Nicole00;
end

procedure Nicole10
begin
	gsay_message( SCRIPT_NICOLE, 133, 50 );
	call NicoleShowOut;
end

procedure Nicole11
begin
	DownReactLevel
	gsay_reply( SCRIPT_NICOLE, 134 );
	gsay_option( SCRIPT_NICOLE, 135, Nicole12, 50 );
	gsay_option( SCRIPT_NICOLE, 136, Nicole13, 50 );
end

procedure Nicole12
begin
	BottomReact
	gsay_message( SCRIPT_NICOLE, 137, 50 );
	call NicoleShowOut;
end

procedure Nicole13
begin
	DisplayMessage := 138;
	call NicoleMore;
end

procedure Nicole14
begin
	gsay_message( SCRIPT_NICOLE, 141, 50 );
end

procedure Nicole15
begin
	gsay_reply( SCRIPT_NICOLE, 142 );
	gsay_option( SCRIPT_NICOLE, 143, Nicole16, 50 );
end

procedure Nicole16
begin
	gsay_reply( SCRIPT_NICOLE, 144 );
	gsay_option( SCRIPT_NICOLE, 145, Nicole17, 50 );
	gsay_option( SCRIPT_NICOLE, 146, Nicole25, 50 );
end

procedure Nicole17
begin
	gsay_reply( SCRIPT_NICOLE, 147 );
	gsay_option( SCRIPT_NICOLE, 148, Nicole07, 50 );
	gsay_option( SCRIPT_NICOLE, 149, Nicole18, 50 );
end

procedure Nicole18
begin
	gsay_reply( SCRIPT_NICOLE, 151 );
	gsay_option( SCRIPT_NICOLE, 152, Nicole19, 49 );
	gsay_option( SCRIPT_NICOLE, 153, Nicole20, 50 );
end

procedure Nicole19
begin
	DisplayMessage := 154;
	call NicoleMore;
end

procedure Nicole20
begin
	gsay_reply( SCRIPT_NICOLE, 157 );
	gsay_option( SCRIPT_NICOLE, 158, Nicole21, 50 );
	gsay_option( SCRIPT_NICOLE, 159, Nicole21a, 51 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 160, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 160, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 164, Nicole14, 50 );
end

procedure Nicole21
begin
	gsay_reply( SCRIPT_NICOLE, 161 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 163, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 163, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 164, Nicole14, 50 );
end

procedure Nicole21a
begin
	gsay_reply( SCRIPT_NICOLE, 162 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 163, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 163, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 164, Nicole14, 50 );
end

procedure Nicole25
begin
	gsay_reply( SCRIPT_NICOLE, 175 );
	gsay_option( SCRIPT_NICOLE, 176, Nicole26, 50 );
	gsay_option( SCRIPT_NICOLE, 177, Nicole11, 50 );
	gsay_option( SCRIPT_NICOLE, 178, Nicole27, 50 );
end

procedure Nicole26
begin
	DisplayMessage := 179;
	call NicoleMore;
end

procedure Nicole27
begin
	DisplayMessage := 182;
	call NicoleMore;
end

procedure Nicole28
begin
	gsay_reply( SCRIPT_NICOLE, 185 );
	gsay_option( SCRIPT_NICOLE, 186, Nicole19, 49 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 187, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 187, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 188, Nicole14, 50 );
end

procedure Nicole29
begin
	gsay_reply( SCRIPT_NICOLE, 189 );
	gsay_option( SCRIPT_NICOLE, 190, Nicole30, 50 );
	gsay_option( SCRIPT_NICOLE, 191, Nicole31, 50 );
	gsay_option( SCRIPT_NICOLE, 192, Nicole04, 50 );
end

procedure Nicole30
begin
	gsay_reply( SCRIPT_NICOLE, 193 );
	gsay_option( SCRIPT_NICOLE, 194, Nicole31, 50 );
	gsay_option( SCRIPT_NICOLE, 195, Nicole36, 50 );
end

procedure Nicole31
begin
	gsay_reply( SCRIPT_NICOLE, 196 );
	gsay_option( SCRIPT_NICOLE, 197, Nicole39, 50 );
	gsay_option( SCRIPT_NICOLE, 198, Nicole11, 50 );
	gsay_option( SCRIPT_NICOLE, 199, Nicole32, 50 );
	gsay_option( SCRIPT_NICOLE, 195, Nicole36, 50 );
end

procedure Nicole32
begin
	gsay_reply( SCRIPT_NICOLE, 201 );
	gsay_option( SCRIPT_NICOLE, 202, Nicole33, 50 );
	gsay_option( SCRIPT_NICOLE, 195, Nicole36, 50 );
end

procedure Nicole33
begin
	gsay_reply( SCRIPT_NICOLE, 204 );
	gsay_option( SCRIPT_NICOLE, 205, Nicole11, 50 );
	gsay_option( SCRIPT_NICOLE, 206, Nicole34, 50 );
	gsay_option( SCRIPT_NICOLE, 207, Nicole36, 50 );
end

procedure Nicole34
begin
	gsay_reply( SCRIPT_NICOLE, 208 );
	gsay_option( SCRIPT_NICOLE, 209, Nicole36, 50 );
	gsay_option( SCRIPT_NICOLE, 210, Nicole35, 50 );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 211, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 211, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 212, Nicole14, 50 );
end

procedure Nicole35
begin
	gsay_message( SCRIPT_NICOLE, 213, 50 );
	DownReactLevel
end

procedure Nicole36
begin
	gsay_reply( SCRIPT_NICOLE, 214 );
	gsay_option( SCRIPT_NICOLE, 215, Nicole37, 50 );
	gsay_option( SCRIPT_NICOLE, 216, Nicole41, 50 );
end

procedure Nicole37
begin
	gsay_reply( SCRIPT_NICOLE, 217 );
	gsay_option( SCRIPT_NICOLE, 218, Nicole39, 50 );
	gsay_option( SCRIPT_NICOLE, 219, Nicole41, 50 );
end

procedure Nicole39
begin
	DisplayMessage := 220;
	TopReact
	call NicoleMore;
end

procedure Nicole41
begin
	gsay_reply( SCRIPT_NICOLE, 223 );
	gsay_option( SCRIPT_NICOLE, 224, Nicole00, 50 );
	gsay_option( SCRIPT_NICOLE, 225, NicoleEnd, 50 );
end

procedure Nicole50 begin
	DisplayMessage := 132;
	gsay_reply( SCRIPT_NICOLE, 307 );
	gsay_option( SCRIPT_NICOLE, 320, Nicole51, 50 );
	gsay_option( SCRIPT_NICOLE, 321, Nicole00, 50 );
end

procedure Nicole51
begin
	gsay_reply( SCRIPT_NICOLE, DisplayMessage );
	gsay_option( SCRIPT_NICOLE, 322, Nicole52, 50 );
	gsay_option( SCRIPT_NICOLE, 323, Nicole53, 50 );
	gsay_option( SCRIPT_NICOLE, 324, Nicole54, 50 );
	gsay_option( SCRIPT_NICOLE, 321, Nicole00, 50 );
	gsay_option( SCRIPT_NICOLE, 326, Nicole14, 50 );
end

procedure Nicole52
begin
	DisplayMessage := 299;
	call Nicole51;
end

procedure Nicole53
begin
	DisplayMessage := 185;
	call Nicole51;
end

procedure Nicole54
begin
	gsay_reply( SCRIPT_NICOLE, 251 );
	gsay_option( SCRIPT_NICOLE, 325, Nicole55, 50 );
	set_global_var( GVAR_FOLLOWER_MACHO_HELP, 1 );
end

procedure Nicole55 begin
	set_global_var( GVAR_SHADOW_PASSWORD, 1 );
	gsay_message( SCRIPT_NICOLE, 254, 50 );
end

procedure Nicole78
begin
	gsay_message( SCRIPT_NICOLE, 291, 50 );
end

procedure NicoleMore begin
	gsay_reply( SCRIPT_NICOLE, DisplayMessage );
	if (local_var(1) >= 2) then begin
		gsay_option( SCRIPT_NICOLE, 155, Nicole09, 50 );
	end
	else begin
		gsay_option( SCRIPT_NICOLE, 155, Nicole10, 51 );
	end
	gsay_option( SCRIPT_NICOLE, 131, Nicole14, 50 );
end

procedure NicoleShowOut begin
	gfade_out(1);
	move_to(dude_obj, 23883, 0);
	set_local_var(5, 1);
end

procedure NicoleEnd begin
end
