/*

	Brotherhood - Cabbot, the door guard

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\MAPNECRO.h"

#define NAME                    SCRIPT_CABBOT
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BOS)

#include "..\headers\command.h"
#include "..\headers\ModReact.h"

/* Standard Script Procedures */
procedure start;
procedure talk_p_proc;
procedure damage_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc;

procedure cabbot01;
procedure cabbot02;
procedure cabbot04;
procedure cabbot05;
procedure cabbot05a;
procedure cabbot06;
procedure cabbot07;
procedure cabbot09;
procedure cabbot10;
procedure cabbot12;
procedure cabbot16;
procedure cabbot17;
procedure cabbot18;
procedure cabbot19;
procedure cabbot20;
procedure cabbot21;
procedure cabbot21_1;
procedure cabbot22;
procedure cabbot23;
procedure cabbot24;
procedure cabbot25;
procedure cabbot27;
procedure cabbot28;
procedure cabbot31;
procedure cabbot32;
procedure cabbot33;
procedure cabbot34;
procedure cabbot35;
procedure cabbot36;
procedure cabbot37;
procedure cabbot38;
procedure cabbot39;
procedure cabbot40;
procedure cabbot41;
procedure cabbot42;
procedure cabbot43;
procedure cabbot44;
procedure cabbot45;
procedure cabbot46;
procedure cabbot47;
procedure cabbot48;
procedure cabbot06a;
procedure cabbot07a;
procedure cabbot16a;
procedure cabbot19a;
procedure cabbot23a;
procedure cabbot33a;
procedure cabbotx;
procedure cabbotx1;
procedure cabbotx3;
procedure cabbotx6;
procedure cabbotx7;
procedure cabbotx8;
procedure cabbot35a;
procedure cabbot49;
procedure cabbot50;
procedure cabbot51;
procedure cabbot52;
procedure cabbot53;
procedure cabbot54;
procedure cabbot55;
procedure cabbot56;
procedure cabbot57;
procedure cabbot58;
procedure cabbot59;
procedure cabbot60;
procedure cabbot61;
procedure cabbot62;
procedure cabbot63;
procedure cabbot64;
procedure cabbot65;
procedure cabbot66;
procedure cabbot67;
procedure cabbot68;
procedure cabbot69;
procedure cabbotend;
procedure cabbotopen;
procedure combat;

procedure cheat_1;

#define LVAR_Here_Before       		(4)

import variable Door_ptr;
import variable Cabbot_Ptr;

variable VATS;
variable MALE;
variable SEXY;
variable tmp_hostile;
variable ILLEGAL;
variable Only_Once := 1;
variable temp;

procedure start begin
	if Only_Once then begin
		Only_Once := 0;
		Cabbot_Ptr := self_obj;
		set_self_team(TEAM_BROTHERHOOD );
		set_self_ai( AI_BROTHERHOOD_KNIGHT );
	end
end

procedure damage_p_proc begin
	set_global_var(ENEMY_BROTHERHOOD, 1);
end

procedure critter_p_proc begin
	if local_var(7) == 1 then begin
		set_local_var(7, 2);
		set_global_var( GVAR_PLAYER_REPUTATION, global_var( GVAR_PLAYER_REPUTATION ) + 1 );
		display_msg(message_str(SCRIPT_CABBOT, 232));
		give_exp_points(EXP_BECOME_INITITAT);
	end
	if (global_var(ENEMY_BROTHERHOOD)) then begin
		tmp_hostile := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		tmp_hostile := 0;
	end
	if (tmp_hostile) then begin
		set_global_var(ENEMY_BROTHERHOOD, 1);
		tmp_hostile := 0;
		attack(dude_obj);
	end
	else begin
		if (local_var(5) == 0) then begin
			if (global_var(QUEST_BROHOOD_1_JOIN_THEM) == 2) then begin
				add_timer_event(self_obj, game_ticks(1), 1);
			end
		end
		else begin
			if (local_var(5) == 1) then begin
				if (tile_num(self_obj) == 20706) then begin//20906) then begin
					set_local_var(5, 2);
					anim(self_obj, 1000, 2);
				end
				else begin
					animate_move_obj_to_tile(self_obj, 20706, 0);//20906, 0);
				end
			end
		end
	end
end

procedure pickup_p_proc begin
	if (source_obj == dude_obj) then begin
		tmp_hostile := 1;
	end
end

procedure talk_p_proc begin
	dude_look_at_critter;
	if (global_var(QUEST_BROHOOD_1_JOIN_THEM) == 5) then begin
		float_msg(self_obj, message_str(SCRIPT_CABBOT, 233), 2);
	end
	else begin
		get_reaction
		start_gdialog(NAME, self_obj, 4, HEAD_CABBOT, BACKGROUND_BHOOD);
		gsay_start;
		if (local_var(LVAR_Here_Before) == 1) then begin
			if (global_var(QUEST_BROHOOD_1_JOIN_THEM) == 1) then begin
				call cabbot24;
			end
			else if (global_var(QUEST_BROHOOD_1_JOIN_THEM) == 2) then begin
				call cabbot36;
			end
			else if (global_var(WITH_CARAVAN) == 1) then begin // TODO: Wrong gvar???? Does this make sense here????
				call cabbot33;
			end
			else begin
				if (local_var(LVAR_reaction) >= 50) then begin
					call cabbot19;
				end
				else begin
					call cabbot21;
				end
			end
		end
		else begin
			call cabbot01;
		end
		gsay_end;
		end_dialogue;
	end
end

procedure destroy_p_proc begin
	rm_timer_event(self_obj);

	if obj_in_party(source_obj) then begin
		set_global_var(ENEMY_BROTHERHOOD, 1);
	end
	inc_good_critter
	rm_timer_event(self_obj);
end

procedure look_at_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_CABBOT, 100));
end

procedure timed_event_p_proc begin
	set_local_var(5, 1);
	use_obj(Door_ptr);
end

procedure cabbot01 begin
	set_local_var(LVAR_Here_Before, 1);
	gsay_reply(40, 101);
	NOption( 103, cabbot17, 4 );
	NOption( 105, cabbot04, 4 );
	NOption( 106, cabbot12, 4 );
	NOption( 107, cabbot10, 4 );
	NOption( 102, cabbot02, 4 );
	NOption( 104, cabbot46, -3 );

	if (debug_mode) then begin
		NOption("*** Cheat: Let me in! ***",cheat_1,004);
	end
end

procedure cheat_1 begin
	set_global_var(ARTIFACT_DISK_FOUND_GIVEN, 2);
	set_global_var(QUEST_BROHOOD_1_JOIN_THEM, 2);
	TopReact
	call cabbot27;
end

procedure cabbot02
begin
	gsay_reply(40, 108);
	NOption( 109, cabbot17, 5 );
	NOption( 110, cabbot16, 4 );
	NOption( 111, cabbot04, 5 );
	NOption( 112, cabbot12, 4 );
	NOption( 113, cabbot10, 4 );
end

procedure cabbot04 begin
	gsay_message(40, 114, 50);
	set_local_var(6, 1);
	gfade_out(1);
	game_time_advance(game_ticks(600));
	gfade_in(1);
	call cabbot05;
end

procedure cabbot05
begin
	gsay_reply(40, 115);
	NOption( 116, cabbot06, 4 );
	NOption( 117, cabbot10, 4 );
	NOption( 118, cabbot05a, 6 );
end

procedure cabbot05a
begin
	gsay_reply(40, 119);
	NOption( 120, cabbot06, 4 );
	NOption( 121, cabbot17, 6 );
	NOption( 122, cabbot10, 4 );
end

procedure cabbot06
begin
	gsay_reply(40, 123);
	if global_var(WORLDMAPLIST_THE_GLOW) == 0 then
		set_global_var(WORLDMAPLIST_THE_GLOW, 1);
	mark_on_map(AREA_GLOW)

	NOption( 124, cabbot07, 7 );
	if ((global_var(ARTIFACT_HOLODISK_USED) > 0) or (global_var(ARTIFACT_HOLODISK_POINTER) > 0) or (global_var(ARTIFACT_DISK_FOUND_GIVEN) > 0)) and (global_var(QUEST_BROHOOD_1_JOIN_THEM) != 2) then begin// ARTIFACT_HOLODISK_USED, ARTIFACT_HOLODISK_POINTER, ARTIFACT_DISK_FOUND_GIVEN
		set_global_var(QUEST_BROHOOD_1_JOIN_THEM, 1);
		UpReactLevel
		NOption( 234, cabbotx3, 4 );
	end
	else begin
		NOption( 125, cabbot09, 4 );
	end
	BOption( 126, cabbot06a, 4 );
end

procedure cabbot07
begin
	gsay_reply(40, 127);
	if ((global_var(ARTIFACT_HOLODISK_USED) > 0) or (global_var(ARTIFACT_HOLODISK_POINTER) > 0) or (global_var(ARTIFACT_DISK_FOUND_GIVEN) > 0)) and (global_var(QUEST_BROHOOD_1_JOIN_THEM) != 2) then begin// ARTIFACT_HOLODISK_USED, ARTIFACT_HOLODISK_POINTER, ARTIFACT_DISK_FOUND_GIVEN
		set_global_var(QUEST_BROHOOD_1_JOIN_THEM, 1);
		UpReactLevel
		NOption( 234, cabbotx3, 4 );
	end
	else begin
		NOption( 128, cabbot09, 4 );
	end
	BOption( 129, cabbot07a, 4 );
end

procedure cabbot09 begin
	gsay_message(40, 130, 49);
	set_global_var(QUEST_BROHOOD_1_JOIN_THEM, 1);
	UpReactLevel
	call cabbotx;
end

procedure cabbot10 begin
	gsay_message(40, 131, 50);
end

procedure cabbot12
begin
	gsay_reply(40, 132);
	NOption( 133, cabbot04, 5 );
	NOption( 134, cabbot10, 4 );
	NOption( 135, cabbot17, 5 );
end

procedure cabbot16 begin
	gsay_reply(40, 136);
	NOption( 137, cabbot17, 5 );
	NOption( 138, cabbot04, 5 );
	BOption( 139, cabbot16a, 4 );
	NOption( 140, cabbot10, 4 );
end

procedure cabbot17
begin
	gsay_message(40, 141, 51);
	call cabbotx;
end

procedure cabbot18
begin
	gsay_message(40, 142, 51);
	call cabbotx;
end

procedure cabbot19
begin
	if (local_var(1) >= 3) then begin
		gsay_reply(40, 143);
	end
	else begin
		gsay_reply(40, 144);
	end
	NOption( 145, cabbot05, 5 );
	NOption( 146, cabbot17, 5 );
	BOption( 147, cabbot19a, 4 );
	NOption( 104, cabbot46, -3 );
end

procedure cabbot20
begin
	gsay_message(40, 148, 50);
	call cabbotx;
end

procedure cabbot21 begin
	gsay_reply(40, 149);
	NOption( 150, cabbot21_1, 5 );
	NOption( 151, cabbotx, 4 );
end

procedure cabbot21_1
begin
	if (dude_is_male) then begin
		if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
			call cabbot23;
		end
		else begin
			call cabbot22;
		end
	end
	else begin
		call cabbot23;
	end
end

procedure cabbot22
begin
	gsay_message(40, 152, 50);
	call cabbotx;
end

procedure cabbot23
begin
	if (local_var(1) < 2) then begin
		set_local_var(1, 2);
		LevelToReact
	end
	gsay_reply(40, 153);
	NOption( 154, cabbot05, 5 );
	NOption( 155, cabbot17, 5 );
	BOption( 156, cabbot23a, 4 );
end

procedure cabbot24 begin
	gsay_reply(40, 157);
	NOption( 158, cabbot25, 4 );
	NOption( 159, cabbot32, 4 );
end

procedure cabbot25
begin
	gsay_reply(40, 160);
	NOption( 161, cabbotx3, 4 );
	NOption( 162, cabbot32, 4 );
end

procedure cabbot27
begin
	gsay_reply(40, 163);
	NOption( 164, cabbotopen, 4 );
end

procedure cabbot28
begin
	gsay_reply(40, 165);
	NOption( 166, cabbot31, 4 );
end

procedure cabbot31
begin
	gsay_message(40, 168, 50);
	call cabbotx;
end

procedure cabbot32
begin
	gsay_message(40, 169, 50);
	call cabbotx;
end

procedure cabbot33 begin
	if (local_var(1) >= 3) then begin
		gsay_reply(40, 170);
	end
	else begin
		if (local_var(1) <= 1) then begin
			gsay_reply(40, 171);
		end
		else begin
			gsay_reply(40, 172);
		end
	end
	NOption( 173, cabbot34, 4 );
	BOption( 174, cabbot33a, 4 );
end

procedure cabbot34 begin
	if (local_var(1) >= 3) then begin
		gsay_message(40, 175, 49);
	end
	else begin
		if (local_var(1) <= 1) then begin
			gsay_message(40, 176, 51);
		end
		else begin
			gsay_message(40, 177, 50);
		end
	end
	call cabbotx6;
end

procedure cabbot35 begin
	NOption( 178, cabbot38, 5 );
	NOption( 179, cabbot42, 5 );
	NOption( 180, cabbot37, 4 );
end

procedure cabbot36 begin
	if (local_var(1) >= 3) then begin
		gsay_reply(40, 182);
	end
	else begin
		if (local_var(1) <= 1) then begin
			gsay_reply(40, 183);
		end
		else begin
			gsay_reply(40, 184);
		end
	end
	NOption( 185, cabbot35a, 5 );
	NOption( 186, cabbot37, 4 );
end

procedure cabbot37
begin
	gsay_message(40, 187, 50);
	call cabbotx7;
end

procedure cabbot38
begin
	gsay_reply(40, 188);
	NOption( 189, cabbot39, 5 );
	NOption( 190, cabbot40, 5 );
end

procedure cabbot39
begin
	gsay_reply(40, 191);
	NOption( 192, cabbot35a, 5 );
	NOption( 193, cabbot37, 4 );
end

procedure cabbot40
begin
	gsay_reply(40, 194);
	NOption( 195, cabbot41, 6 );
	NOption( 196, cabbot35a, 5 );
	NOption( 197, cabbot37, 4 );
end

procedure cabbot41
begin
	gsay_reply(40, 198);
	NOption( 199, cabbot35a, 4 );
	NOption( 200, cabbot37, 4 );
end

procedure cabbot42
begin
	gsay_reply(40, 201);
	NOption( 202, cabbot39, 4 );
	NOption( 203, cabbot35a, 5 );
	NOption( 204, cabbot37, 4 );
end

procedure cabbot43
begin
	DownReactLevel
	ILLEGAL := 1;
	float_msg(self_obj, message_str(SCRIPT_CABBOT, 205), 2);
end

procedure cabbot44
begin
	DownReactLevel
	ILLEGAL := 1;
	float_msg(self_obj, message_str(SCRIPT_CABBOT, 206), 2);
	call cabbotx8;
end

procedure cabbot45
begin
	DownReactLevel
	ILLEGAL := 1;
	float_msg(self_obj, message_str(SCRIPT_CABBOT, 207), 2);
end

procedure cabbot46 begin
	gsay_message(40, 208, 50);
	call cabbotx;
end

procedure cabbot47
begin
	gsay_message(40, 209, 50);
end

procedure cabbot48
begin
	gsay_message(40, 210, 50);
end

procedure cabbot06a
begin
	DownReactLevel
	call cabbot10;
end

procedure cabbot07a
begin
	DownReactLevel
	LevelToReact
	call cabbot10;
end

procedure cabbot16a
begin
	BottomReact
	call cabbot18;
end

procedure cabbot19a
begin
	DownReactLevel
	LevelToReact
	call cabbot20;
end

procedure cabbot23a
begin
	DownReactLevel
	call cabbot20;
end

procedure cabbot33a
begin
	DownReactLevel
	call cabbot34;
end

procedure cabbotx
begin
end

procedure cabbotx1
begin
	call cabbot05;
end

procedure cabbotx3
begin
	if ((global_var(ARTIFACT_HOLODISK_USED) > 0) or (global_var(ARTIFACT_HOLODISK_POINTER) > 0) or (global_var(ARTIFACT_DISK_FOUND_GIVEN) > 0)) and (global_var(QUEST_BROHOOD_1_JOIN_THEM) != 2) then begin// ARTIFACT_HOLODISK_USED, ARTIFACT_HOLODISK_POINTER, ARTIFACT_DISK_FOUND_GIVEN
		if local_var(7) == 0 then begin
			set_local_var(7, 1);
		end
		set_global_var(ARTIFACT_DISK_FOUND_GIVEN, 2);
		set_global_var(QUEST_BROHOOD_1_JOIN_THEM, 2);
		TopReact
		call cabbot27;
	end
	else begin
		call cabbot31;
	end
end

procedure cabbotx6
begin
end

procedure cabbotx7
begin
end

procedure cabbotx8
begin
end

procedure cabbot35a
begin
	gsay_message(40, 181, 50);
	call cabbot35;
end

procedure cabbot49
begin
	gsay_message(40, 211, 50);
end

procedure cabbot50
begin
	gsay_message(40, 212, 50);
end

procedure cabbot51
begin
	gsay_message(40, 213, 50);
end

procedure cabbot52
begin
	gsay_message(40, 214, 50);
end

procedure cabbot53
begin
	gsay_message(40, 215, 50);
end

procedure cabbot54
begin
	gsay_message(40, 216, 50);
end

procedure cabbot55
begin
	gsay_message(40, 217, 50);
end

procedure cabbot56
begin
	gsay_message(40, 218, 50);
end

procedure cabbot57
begin
	gsay_message(40, 219, 50);
end

procedure cabbot58
begin
	gsay_message(40, 220, 50);
end

procedure cabbot59
begin
	gsay_message(40, 221, 50);
end

procedure cabbot60
begin
	gsay_message(40, 222, 50);
end

procedure cabbot61
begin
	gsay_message(40, 223, 50);
end

procedure cabbot62
begin
	gsay_message(40, 224, 50);
end

procedure cabbot63
begin
	gsay_message(40, 225, 50);
end

procedure cabbot64
begin
	gsay_message(40, 226, 50);
end

procedure cabbot65
begin
	gsay_message(40, 227, 50);
end

procedure cabbot66
begin
	gsay_message(40, 228, 50);
end

procedure cabbot67
begin
	gsay_message(40, 229, 50);
end

procedure cabbot68
begin
	gsay_message(40, 230, 50);
end

procedure cabbot69
begin
	gsay_message(40, 231, 50);
end

procedure cabbotend
begin
end

procedure cabbotopen
begin
end

procedure combat
begin
	tmp_hostile := 1;
end






