{100}{}{Vidíš Ambera, uèitele Následovníkù.}
{101}{}{Teï je èas odpoèinku. Pøijï prosím nìkdy bìhem veèera.}
{102}{}{Vítej vznešenı poutníku. Pøišel jsi sem studovat?}
{103}{}{Ne. Ve skuteènosti jsem pøišel zabíjet.}
{104}{}{To záleí na tom, èemu mì chceš uèit.}
{105}{}{Ano, chci se uèit.}
{106}{}{To je mi opravdu líto, e to øíkáš. Následovníci vìøí, e mír je to nejcennìjší na svìtì. Proto jsme se zøekli všeho násilí. Dobrou noc.}
{107}{}{Jsem vzdìlán v mnoha jazycích a umìních. Chceš se nìèemu z toho uèit?}
{108}{}{Lituju, ale já se potøebuju nauèit ty vìci, které mi pomùou pøeít.}
{109}{}{Na takové nesmysly nemám èas. Sbohem.}
{110}{}{Moná bych si mohl poslechnout jednu nebo dvì písnì.}
{111}{}{A mùeš mì nauèit i nìco jiného?}
{112}{}{Ach tak, máme tu nìkoho, kdo studuje sám velkı ivot. V takovém pøípadì tì mùu nauèit nìèemu z praktické botaniky, ale studium zabere delší dobu a vısledky jsou nejisté.}
{113}{}{Fajn, jen mì uè.}
{114}{}{Prosím, nauè mì všechno co se dá.}
{115}{}{Lituju, ale na kytky opravdu nemám èas. Sbohem.}
{116}{}{Není nutné chovat se tak hrubì. Omluv se nebo tì nebudu uèit.}
{117}{}{Promiò. Budeš mì prosím uèit?}
{118}{}{Zapomeò na to.}
{119}{}{To u je lepší. Mùeme zaèít s tvım studiem.}
{120}{}{Jsi bystrı uèedník. Pøeji ti, a všechny své budoucí zkoušky zvládneš tak lehce jako ty dnešní. Jdi v pokoji.}
{121}{}{Vypadáš velmi schopnì. Ké budoucnost obmìkèí tvé srdce a osvítí tvou mysl.}
{122}{}{Vıbornì, budu tì tedy uèit zpùsoby, jak pøeít.}
{123}{}{Jsi bystrı uèedník. Pøeji ti, a všechny své budoucí zkoušky zvládneš tak lehce jako ty dnešní. Jdi v pokoji.}
{124}{}{Tvoje slova mì nepøesvìdèují. Myslím, e chceš mé dary vyuít pro páchání zla. Sbohem.}
{125}{}{Ach, student umìní. To je v tomhle svìtì velmi vzácné. Moná je pøece jen nìjaká nadìje. Kadá píseò je ale dosti dlouhá. Kterou z nich chceš slyšet?}
{126}{}{SWEET LULLABY od Deep Forrest}
{127}{}{BALADA O AVATAROVI.}
{128}{}{DE PROFUNDIS.}
{129}{}{CANTARA.}
{130}{}{Podivuhodná práce. Mìl bych ti sehnat posluchaèe.}
{131}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{132}{}{Podivuhodná práce. Mìl bych ti sehnat posluchaèe.}
{133}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{134}{}{Podivuhodná práce. Mìl bych ti sehnat posluchaèe.}
{135}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{136}{}{Podivuhodná práce. Mìl bych ti sehnat posluchaèe.}
{137}{}{Musím si odpoèinout. To vyuèování mì velmi vysiluje. Hodnì štìstí.}
{138}{}{Obávám se, e jsem se u moc zdrel. Lituji.}
{139}{}{Mír a krása to je vše, èemu tì mohu uèit. Je mi líto, e nic z toho tì nezajímá. Pøeji ti krásnı den.}
{140}{}{Mohu tì nauèit zpùsobùm starıch potulnıch zpìvákù.}
{141}{}{Bylo by mi ctí slyšet jednu z tvıch písní.}
{142}{}{Moná nìkdy jindy. Ale díky.}
{143}{}{Doufal jsem, e se tu nauèím nìèemu, co mi v ivotì pomùe trochu víc.}
{144}{}{Nepotøebuješ nic z mého umìní. Takoví jako ty nauèili mírumilovné lidi válce. Truchlím pro nì.}
