{100}{}{Vidíš Staršího Bratrstva.}
{101}{}{Vítej Zasvìcenèe. Musíme si spolu promluvit. (Pokyne ti, abys k nìmu pøistoupil blí.)}
{102}{}{A o èem?}
{103}{}{Právì teï nemám èas.}
{104}{}{Cháfel?}
{105}{}{Je tu naléhavá záleitost a já potøebuju, abys mi s ní pomohl. Jde o Maxsona. Vypadá to, e se dostal a na dno svıch duševních sil. Nepøestává vanit o armádì shromaïující se na severu.}
{106}{}{Nechci naše vojáky posílat tam do tìch oblastí zamoøenıch radioaktivitou, dokud nebudu mít pøesvìdèivı dùkaz, e ta "armáda" opravdu existuje.}
{107}{}{Potøebuju nìkoho nezávislého. Nìkoho, kdo podá èestné a pravdivé hlášení. Jsi ochotnı prozkoumat ten severní region?}
{108}{}{Udìlám to.}
{109}{}{Teï to udìlat nemùu. Mám ještì další vìci, které musím nejdøív zaøídit.}
{110}{}{Našel jsem na severu základnu vedenou armádou mutantù.}
{111}{}{Dobøe. Pokud jsi to ještì neudìlal, tak si jdi nejdøív promluvit s Maxsonem. A a prozkoumáš to severní teritorium, vra se ke mnì s hlášením. Potom se rozhodneme, co udìláme s Maxsonem.}
{112}{}{Popøej mi štìstí.}
{113}{}{U jsi prozkoumal celou severní oblast?}
{114}{}{Ano.}
{115}{}{Ne.}
{116}{}{A jaké je tvoje hlášení?}
{117}{}{Našel jsem základnu chránìnou tìce ozbrojenımi mutanty. Vypadá to s námi dost bledì.}
{118}{}{To si nemyslím. Byl jsi pryè pøíliš krátkou dobu. A teï jdi a sem se nevracej, dokud nebudeš moci podat ÚPLNİ report.}
{119}{}{Ano, pane.}
{120}{}{Budu informovat Radu Starších. Poèkáme na Maxsonovo rozhodnutí, co dìlat. Jdi a informuj ho o tom, cos objevil. Díky za tvou pomoc, Zasvìcenèe.}
{121}{}{Není zaè.}
{122}{}{Tak si ten èas udìlej a vyslechni mì.}
{123}{}{Jsem jedno véélkı ucho.}
{124}{}{Ty mi mùeš tak akorát políbit, dìdulo.}
{125}{}{Zapomeò na to. Mám na starosti dùleitìjší vìci.}
{126}{}{Rozumím. Ale kdybys mìl cestu tím smìrem a cokoliv tam objevil, dej mi prosím vìdìt.}
{127}{}{Kdybych na severu našel nìco, co pøipomíná armádu, dám ti vìdìt.}
{128}{}{Dobrá práce s tìmi mutanty. U jsme slyšeli, e jsi znièil i jejich produkèní zaøízení. Díky, es za nás vyøešil ten problém.}
{129}{}{No problem.}
{130}{}{Cháfel? Co je to za nesmysl ten "Cháfel"? Odejdi! Hned!}
{131}{}{Kdyby to záleelo na mnì, u bys tu nebyl.}
{132}{}{Nemám, co bych ti øekl.}
{133}{}{Mìl bys se nauèit troše úcty.}
{134}{}{Schùzka bude podle plánu. Všichni Starší jsou zde a souhlasí, e si vyslechnou hlášení Bratra }
{135}{}{. Potom rozhodneme, jaké akce budou následovat. Bratøe }
{136}{}{, øekni nám co jsi vidìl na severu.}
{137}{}{Bìhem mého prùzkumu jsem našel vojenskou základnu pouívanou mutanty. To zaøízení je chránìno tìce ozbrojenımi stráemi a peèlivì støeeno.}
{138}{}{Séfer?}
{139}{}{A jak ti mutanti vypadají?}
{140}{}{Jsou to mohutné, humanoidní typy. Jejich svalová hmota je mnohem vìtší, ne u kteréhokoliv bìného èlovìka. Vypadají velice organizovanì a nìkolik z nich chrání vstup.}
{141}{}{Jsou velcí, nazelenalí a mají zbranì.}
{142}{}{Jak moná víš, náš Hlavní písaø Vree zhotovila autopsii tvora velice podobného tomu, kterého jsi právì popsal. Myslíš, e je to ten samı typ?}
{143}{}{Ano. Ten popis do puntíku souhlasí.}
{144}{}{Jakou hrozbu pro nás tito "mutanti" pøedstavují?}
{145}{}{Stejnì jako se Bratrstvo vyzbrojuje do bitvy i tato "armáda mutantù" se pøipravuje na nìco velkého.}
{146}{}{Upøímnì øeèeno, tvoje hlášení nás nepøesvìdèilo, e pro nás pøedstavují ohroení. Nemáš ádnı dùkaz, e vùèi nám mají nepøátelské úmysly.}
{147}{}{Obsadili Nekropolis. Urèitì tam nezùstanou jen tak stát. }
{148}{}{Shromaïují armádu. Tìce ozbrojenou armádu. Urèitì ji nemají jen tak na parádu. Zamıšlí ji pouít.}
{149}{}{No a pøi všech z tìchhle akcích, co provádìjí, není pravdìpodobné, e mohou pøijít i sem?}
{150}{}{Je moné, e u jsou na cestì sem. Bratrstvo je jedinı vánìjší protivník, kterého mají.}
{151}{}{Nevìøím, e jsou to nepøátelé. Mùou taky jednoduše chránit sami sebe pøed útokem. I my jsme obèas napadáni bandity a tak.}
{152}{}{Pokud oni zaútoèí, tak to nebude NIC podobného tìm zøídkavım útokùm lupièù. Bude to masakr. }
{153}{}{Protoe pøicházejí ze staré vojenské základny, umím si docela dobøe pøedstavit, e mají zbranì, které se vyrovnají tìm našim.}
{154}{}{Co navrhuješ? Preventivní útok na jejich základnu?}
{155}{}{Ano. Ale nechci, aby vìdìli, e se na nì chystáme.  Malı tım by mohl mít vìtší šanci dostat se a k nim, ani by ho zaznamenali. }
{156}{}{To vyøeší jen jednu èást problému. Jsou vedeni skupinou pocházející z Katedrály v Pohøebišti.}
{157}{}{Tak se i stane. Dostaneš tøi Paladiny, které ti osobnì vyberu a setkáš se s nimi u té Vojenské základny. Pomohou ti dostat se dovnitø. Rado Starších, dìkuji vám za váš èas. Hodnì štìstí, Zasvìcenèe.}
{158}{}{Pokud jsou vedeni skupinou v Katedrále v Pohøebišti, pak je tu šance, e tam dole mají jen malou pohotovostní armádu. }
{159}{}{Kdy je napadneme na severu, pak se odkryjeme a naše jiní strana se stane zranitelnou. Proto mùu pro takovou akci postrádat jen nìkolik muù.}
{160}{}{Dejte mi nìkolik Paladinù, aby mi pomohli dobıt tu jejich základnu na severu.}
{161}{}{Dejte mi nìkolik Paladinù, aby mi pomohli dobıt tu jejich základnu na jihu.}
{162}{}{Tak se i stane. Dostaneš dva Paladiny, které ti osobnì vyberu a setkáš se s nimi v Pohøebišti u Katedrály. Rado Starších, dìkuji vám za váš èas. Hodnì štìstí Zasvìcenèe.}
{163}{}{Tak se i stane. Dostaneš tøi Paladiny, které ti osobnì vyberu a setkáš se s nimi u té Vojenské základny. Pomohou ti dostat se dovnitø. Rado Starších, dìkuji vám za váš èas. Hodnì štìstí, Zasvìcenèe.}
{164}{}{Zøejmì jsme se zmılili. Starší, promiòte, e jsem pøipravil o váš èas. Mohl by prosím nìkdo odstranit tohohle debila?}
{165}{}{Nemám èas, musím plánovat naši obrannou strategii.}
{166}{}{Obdrel jsi }
{167}{}{ zkušenostních bodù za to, e se ti podaøilo pøesvìdèit Starší, aby ti pomohli s útokem na vojenskou základnu Mariposa.}

# Fo1in2
{168}{}{ zkušenostních bodù za to, e se ti podaøilo pøesvìdèit Starší, aby ti pomohli s útokem na Katedrálu.}
