{100}{}{Vidíš Lashera, jednoho z Dìtí Katedrály.}
{101}{}{U vím, kdo jsi. Jsi monstrum plné høíchu posedlé ïáblem, a za to musíš bıt potrestán.}
{102}{}{U vím, kdo jsi. Jsi ïábel v enské podobì, ale to tì nemùe zachránit pøed spravedlivou odplatou.}
{103}{}{U vím, kdo jsi. Tvá høíšná povìst tì pøedchází. Poslal jsi dìtské duše Hádovi pøedtím, ne se mohly oèistit. To je nejhorší høích a budeš za to potrestán.}
{104}{}{U vím, kdo jsi. Jsi chodící smrt, mor v lidské podobì. Kamkoliv vkroèíš, krev teèe proudem. Ale takové hrùzy musí skonèit a musí to udìlat nìkdo s neposkvrnìnou duší!}
{105}{}{Blázne, jak sis mohl dovolit mì vyrušit! Nevíš, jak vıznamné postavení mám? Vypadni!}
{106}{}{Ty jsi se musel zbláznit! Vytáhnout na mì zbraò. Chrání mì Vùdcùv štít a nedotkneš se mì bez odplaty!}
{107}{}{Nevadilo by mi si vyzkoušet odolnost tvého štítu osobnì.}
{108}{}{Nikdo nikdy neøíkal, e sem nìjakej chytrák!}
{109}{}{Chci si jenom promluvit s nìkım, kdo to tady vede.}
{110}{}{Máš pìknou hùl. 'Lasher' ti øíkají kvùli ní?}
{111}{}{Je to pravda, e rád zneuíváš dìti?}
{112}{}{Seš takovej hlupák? Není moudrı mì takhle uráet, kreténe!}
{113}{}{Hehe, co to meleš za nesmysly?}
{114}{}{Proè jsi pøišel, Zasvìcenı? Víš, e mì nikdo nemá rušit.}
{115}{}{Odpus mi, Otèe, ale mám problémy.}
{116}{}{Chci pøijmout vedení Katedrály.}
{117}{}{Jsem tu kvùli tvému zacházení s Dìtmi.}
{118}{}{Chtìl jsem si jenom promluvit.}
{119}{}{Máš pìknou hùl. 'Lasher' ti øíkají kvùli ní?}
{120}{}{Tak ty bys u nechtìl bıt víckrát rušen? To s radostí zaøídím!}
{121}{}{Nevím. Proè jsem tady? Víš to ty?}
{122}{}{Ty jsi se zbláznil, vejít do mé svatynì se zbraní v ruce! VYPADNI!}
{123}{}{Kdo si myslíš, e jsi. Vstoupit do mé svatynì s tasenou zbraní. Vypadni!}
{124}{}{Promiòte, pane. Ale síly temnot jsou všude a nikdy není jisté, kdy se budu muset bránit.}
{125}{}{Chci pøijmout vedení Katedrály.}
{126}{}{Jsem tu kvùli tvému zacházení s Dìtmi.}
{127}{}{Chtìl jsem si jenom promluvit.}
{128}{}{Máš pìknou hùl. 'Lasher' ti øíkají kvùli ní?}
{129}{}{Nelíbí se ti tasené zbranì? Tak to, co se s nima chystám udìlat, se ti bude líbit ještì míò!}
{130}{}{Ven? A kudy?}
{131}{}{Moje pokoje nejsou pøístupné tìm, co nejsou zasvìcení. Musím tì poádat, abys odešel.}
{132}{}{Promiò mi tu nezdvoøilost, ale potøebuju vìdìt pár dùleitıch vìcí.}
{133}{}{Jsem tu kvùli tvému zacházení s Dìtmi.}
{134}{}{Chtìl jsem si promluvit o zasvìcení.}
{135}{}{Máš pìknou hùl. 'Lasher' ti øíkají kvùli ní?}
{136}{}{Ale tohle místo ještì není 'zasvìcené'. Zatím sem tu toti nikoho nesejmul.}
{137}{}{Uboáku! Mám hodnì vy..svì..ce..ní. . .}
{138}{}{To je privilegium hodné pouze tìch nejvìrnìjších sluebníkù. Zasvìcení je pro nì nejvyšší ocenìní.}
{139}{}{A jak mùu získat zasvìcení?}
{140}{}{Chápu správnì, e uèíš Dìti a pøipravuješ je pro zasvìcení?}
{141}{}{Mùeš mi pomoci stát se zasvìcenım?}
{142}{}{Wow! To musíš bıt nìco extra!}
{143}{}{To je problém, protoe takové ocenìní je mrtvému platné jako radškorpióní prdel.}
{144}{}{Bavit se s bláznem nemá cenu. Sbohem.}
{145}{}{Mìl bys zajít za Otcem Morpheusem. Pøebıvá ve vìi, ale je nepravdìpodobné, e tì Nightkin pustí dovnitø.}
{146}{}{Mohl bys øíct Nightkinovi, aby mì pustil dovnitø?}
{147}{}{Mùeš mi øíct nìco blišího o Morpheusovi?}
{148}{}{Mùeš mi øíct nìco blišího o Nightkinovi.}
{149}{}{Dìkuji, pane.}
{150}{}{Takovım problémùm se dokáu vyhnout.}
{151}{}{Hùl je svatı nástroj, kterım udìluji svá poehnání. Bolest èistí mysl od zlıch myšlenek a umoòuje lepší pochopení Vùdcovy slávy.}
{152}{}{To vidím. Take Vùdce znamená hlavnì bolest?}
{153}{}{To je ale pøíšerné, kdy to dìláš dìtem!}
{154}{}{To vypadá pìknì perverznì. Nechceš to na mì vyzkoušet?}
{155}{}{Já ehnám dìtem, to je má práce. Všechny jsou zrozené jako høíšné bestie a mım úkolem je donutit je stát se lidskımi bytostmi. Moná u jsi slyšel, e nesnáším pošetilost. To je pravda, a proto mé poehnání je tak bolestivé.}
{156}{}{A mutanti jsou nìco více ne lidské bytosti?}
{157}{}{Ty bezcitnı bastarde!}
{158}{}{Ty sis nikdy nezašukal, e ne?}
{159}{}{Øekni mi nìco více o tvıch vıukovıch metodách.}
{160}{}{A co potìšení ze zabíjení? Není povolené i to?}
{161}{}{Ty oplzlá, bezmozká zrùdo! Znesvìtil jsi mì svou pøítomností! Vypadni! Ven! Teï!}
{162}{}{Ty jsi ena, a proto jsi navdy zatracená. To je vìèné prokletí tvého rodu, ale já ho za tebe vyøeším.}
{163}{}{Pokud je tvé srdce tak špatné, mùeš bıt klidnı. Spravedlivé srdce nezná pochyby. Vysvìtli mi svùj problém, ale rychle!}
{164}{}{Øekni mi, jak dosáhnout spravedlnosti!}
{165}{}{Chci vìdìt více o Katedrále.}
{166}{}{Chci vìdìt více o Vùdci.}
{167}{}{Ty jsi naivu a to je mùj problém, zkurvysyne!}
{168}{}{Nauè se ít se svou bolestí jako se svım nejbliším pøítelem, protoe právì bolest je tvou nejvìtší silou. Trızni se tak dlouho, a pøijdeš o svou individualitu a potom se staneš Vùdcovım nástrojem. To bude øešení všech tvıch problémù.}
{169}{}{No a kde tedy najdu nejvíc bolesti?}
{170}{}{Jasnì, chci bolestí zblbnout, abych se mohl pøipojit k zombíckému kultu. Tak o tom si nech jenom zdát, kámo!}
{171}{}{To by mì nikdy ani nenapadlo!}
{172}{}{To je všechno? Tak to je dost ubohı, kámo!}
{173}{}{Bolest vdy uvítám a rád jí sdílím se svımi pøáteli.}
{174}{}{Zvíøata melou bez pøemıšlení, ale lidské bytosti nejdøív myslí, a potom teprve mluví. A ty musíš nejdøív v lidskou bytost dospìt, ne s tebou budu chtít mluvit. Teï odejdi.}
{175}{}{Máš pravdu. No dobøe, tak ti tedy pomohu. ale rychle.}
{176}{}{Musím vidìt Otce Morpheuse, je to naléhavé.}
{177}{}{Øekni mi nìco o Katedrále.}
{178}{}{To jsem zvìdavı, kde najdu Vùdce.}
{179}{}{To jsem zvìdavı na ty Dìti.}
{180}{}{Jediná vìc, o které vím, e je opravdu rychlá, je Smrt!}
{181}{}{Pøichází èas, kdy si musíš najít odpovìdi na ivotní otázky a já ti v tom pomùu . . . TEÏ!}
{182}{}{To není moje vìc. Padej.}
{183}{}{Snášením bolesti, získáním moudrosti a vìrnou slubou. Bolest znamená poznání, moudrost znamená poslušnost a sluba pøináší odvahu. }
{184}{}{[Více]}
{185}{}{Musíš odvrhnout Svìtlo, které nás málem všechny znièilo a zavázat se Temnotám, ve kterıch jsme si všichni rovni. Nyní, kdy jsem ti vysvìtlil podstatu, vydej se hledat Vùdce a jeho moudrost.}
{186}{}{Neporadil jsem se s ním, ale jsem si jistı, e je spokojen s dušemi spravedlivıch, které jsem mu pøivedl. Je to tìká práce, ale já jsem ji udìlal dobøe. Bohuel je také nároèná na èas, a proto se s tebou teï musím rozlouèit.}
{187}{}{Lichotnı jazyk je v tlamì démona! Démona jako ty. Vypadni mi z oèí!}
{188}{}{Ty køivohubı ksichte, ztra se mi z oèí a nevracej se døív, ne se nauèíš, jak se máš správnì chovat.}
{189}{}{To je rozumnı dùvod. Vezmi si tenhle symbol a uka ho Nightkinovi, a okolo nìj budeš procházet.}
{190}{}{S tím ti nepomùu. Jdi pryè.}
{191}{}{On nás vede. Je blízko samotnému Vùdci a zná jeho zámìry. Je to všechno?}
{192}{}{Mùeš pøemluvit Nightkina, aby mì pustil?}
{193}{}{Øekni mi ještì nìco o Morpheovi.}
{194}{}{Co mi mùeš øíct o Nightkinovi?}
{195}{}{Díky.}
{196}{}{Tak proè tedy posloucháš kápu Morphea?}
{197}{}{Oni slouí Vùdci. Pøinášejí bolest léèení svìtu. Andìlé temnot, kteøí vykoupí Svìt krvavou lázní. Zvìdavost je nebezpeèná vlastnost a to platí dvojnásob, pokud je zamìøená na Nightkina. Teï musím pracovat, odejdi.}
{198}{}{Tvá zdvoøilost se mi líbí. Nejspíš si zaslouíš vidìt Morphea. A pùjdeš okolo Nightkina, uka mu tenhle symbol a on tì pustí. A teï jdi.}
{199}{}{Ty musíš bıt blázen, pokud si myslíš, e takovou trapnou lstí oklameš Nightkina. Vypadni odtud!}
{200}{}{Úpadek a pohodlí brání evoluci, a ta je nutná pro pøeití v tomhle drsném svìtì. Naštìstí, jsem mu s pevnou vùlí a odolávám svùdnım lákadlùm. Vidím, e nesdílíš mou filosofii, ale to je mi ukradené. Ztra se mi z oèí!}
{201}{}{Mutace se nemusíš obávat. Kadé novì narozené dítì má mutovanou DNA svıch rodièù. Všichni jsme mutanti, a tak jediná vìc, na které záleí, je naše pevná morálka a produktivita. A to je moje práce. A teï u jdi.}
{202}{}{Rozdávám bolest. Pokud je toho zvíøe hodné a chce se uèit, mùe se stát spravedlivou duší. Pokud toho není schopno, tak si nezaslouí ít.}
{203}{}{A Vùdce souhlasí s takovımi metodami?}
{204}{}{Jsi monstrum!}
{205}{}{Myslím, e tì radši opustím.}
{206}{}{Uèíš taky dospìlé?}
{207}{}{Dospìlá zvíøata?}
{208}{}{Hej, mùu je odstranit za tebe. Nikdo se to nemusí dozvìdìt!}
{209}{}{Ty jsi odporná ena. Mìla bys tu radši lehce našlapovat, Nightkin nemá rád soupeøe. Teï vypadni!}
{210}{}{Ty jsi odpornı èlovìk. Mìl bys tu radši lehce našlapovat, Nightkin nemá rád soupeøe. Teï vypadni!}
{211}{}{Spravedlnosti je dosaeno skrze boj, zranìní a uzdravení. Všichni jsme zvíøata, která musí bıt neustále pokoøována, aby pøijmula Vùdcovu pravdu bez váhání. Teï kdy jsi slyšel pravdu, tak se ji sna pochopit. Ted mì nech samotného.}
{212}{}{Tvùj jazyk budi navìky proklet bez monosti vykoupení. Ztra se mi z oèí!}
{213}{}{Katedrála uèí mnoho vìcí, které jsou pro nedisciplinovanou mysl nemoné pochopit. A teï mì u nezdruj, mám dùleitìjší úkoly.}
{214}{}{Stejnì tak já. Vidím, e máme spoustu vìcí spoleènıch, ale naneštìstí mì dokáeš vyprovokovat daleko za hranice mého sebeovládání. A proto vypadni. Teï. Hned!}
{215}{}{To já nemohu posoudit. Musíš pøesvìdèit Nightkina. Hodnì štìstí. Budeš ho toti potøebovat.}
{216}{}{Katedrála je svatynì lidské rasy. Kdy apokalypsa udeøila na toto místo, katedrála byla ušetøena. To umonilo zrození Vùdce, a tak povznášející temnota povstala z odporného svìtla.}
{217}{}{Kdy jsem pøišel, vidìl jsem pouze místo bez morálky a pevnıch zásad. A tak jsem zorganizoval spoleèenství a zaèal ehnat bolestí. To je vše, co potøebuješ vìdìt.}
{218}{}{Øíká se, e Vùdce èekal dole, v Temnotách, ne svìtlo zradilo Lidstvo a témìø ho znièilo. A teï ehnáme Svìtlu, e zrodilo Vùdce.}
{219}{}{ Tohle ale nevím jistì a nikdy jsem nemìl to štìstí Ho spatøit. Teï, pokud mì omluvíš, se musím vìnovat své práci.}
{220}{}{Tak za prvé, nebyl jsi tu pøíliš vítán.}
{221}{}{Dìlával jsem to, ale mnoho postupù bylo zapomenuto ve prospìch tìch hlasitıch zvukù, které slyšíš z Auditoria. To je pro mì zdrojem roztrpèení a hoøkosti. Naštìstí ale stále mohu uèit dìti. Teï mi promiò, musím si pøipravit nìjaké další lekce.}
{222}{}{Uh... to je samozøejmì vzácná událost a zvíøeti se dostane veškeré podpory, aby se vyvinulo. Teï u koneènì jdi. Jdi pryè!}
{223}{}{[HOTOVO]}
{224}{}{To bysme mohli pouít. Vezmi si tenhle symbol. Uka ho Nightkinovi, a ten tì nechá projít. Umoní ti to se setkat s Otcem Morpheusem.}

# Weapon-drawn timer is up, let's attack:
{250}{}{Varoval jsem tì!}
