{100}{}{Vidíš špinavého a nemytého vìznì.}
{101}{}{Vìzeò z druhé cely vypadá jinak než ostatní. Stojí vzpøímenì a dívá se ti pøímo do oèí.}
{102}{}{Vìzeò slepì civí do zdi.}
{103}{}{Vìzeò ignoruje tvùj pokus o rozhovor.}
{104}{}{Chvíli tì s divokým výrazem pozoroval, a pak se otoèil.}
{105}{}{Chvíli se na tebe zadívala, a pak zaèala slintat.}
{106}{}{Žádná odpovìï.}
{107}{}{Jsme volní! Jsme volní!}
{108}{}{Takoví jako ty jsou odporní. Nemluv na mì.}
{109}{}{Quib!}
{110}{}{Nemáš žádné právo se mnou takhle mluvit.}
{111}{}{Ty mi nerozumíš. Jsem tu proto, abych tì zachránil.}
{112}{}{Netahej mì za nos.}
{113}{}{Nemám žádné pravomoce a klidnì bych se na to mìl vyprdnout. Bìž pryè a nech nás o samotì.}
{114}{}{Odmítám ti cokoliv øíct. Nech mì o samotì.}
{115}{}{Hng!}
{116}{}{Jsem tady opravdu proto, abych tì zachránil. Jsem normální èlovìk.}
{117}{}{Jestli to chceš dìlat takhle. Jistì. Sbohem.}
{118}{}{Nepamatuješ si, že si tenhle trik zkoušel už minulý víkend? Nepodlehl jsem tomu tenkrát a nepodlehnu tomu ani teï.}
{119}{}{Cože? Žádná zástìrka za kterou se lze schovat? Tvá zrádná povaha je ti vlastní.}
{120}{}{Jsem tady, abych tì zachránil.}
{121}{}{Pak tedy sbohem.}
{122}{}{Jsi krutý. Nech nás o samotì.}
{123}{}{Nebudu plivat špínu na své lidi. Nemùžeš donutit èlovìka, aby zradil sám sebe, pouze ho mùžeš nechat zemøít.}
{124}{}{Ty tomu fakt nevìøíš. Jsem lidská bytost a chci vás zachránit.}
{125}{}{Nebudu tì nutit vùbec k nièemu, ani kdybys mìl tlít v pekle. Sám o sobì mi už prokazuješ dobrou službu.}
{126}{}{Poøád si ze mì utahuješ.}
{127}{}{Z úst muže vycházejí hadí slova.}
{128}{}{Správnì, to se dalo èekat. Bìž pryè, a nech nás být.}
{200}{}{Vìzni vypadají špinavì a unavenì. Obojky okolo jejich krkù vypadají novì a blyští se.}
{201}{}{Vìzni se k tobì otoèili a zírají na tebe prázdným pohledem. Všimnul sis obojkù okolo jejich krkù.}
{300}{}{Cedule na zdi øíká: "Zákaz Vstupu. Bezpeènostní Zóna. Pouze pro dozorce!"}
{301}{}{Získal jsi }
{302}{}{ bodù zkušeností za vysvobození vìzòù z jejich utrpení.}
