#############################################################
#  Message File: ktgoo.msg                                  #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: March 1, 1998                                   #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vidíš radioaktivní sliz.}
{101}{}{Vidíš radioaktivní sliz.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

{110}{}{Sakra - to pálí.}
{120}{}{Holínky tì chrání pøed slizem.}
{130}{}{Tvoje holínky se rozpustily.}
{140}{}{Tvoje nohy zaèínají pálet a svìdit.}
{150}{}{Tvoje nohy na chvíli pálí a svìdí, ale pak to pøestane.}
