{100}{}{Vidíš muže v tvrzeném koženém brnìní se spoustou podivných serepetièek.}
{101}{}{Vidíš Patricka, Kelta.}
{102}{}{Buï pozdraven, poutníku. Co tì pøivádí tak daleko?}
{103}{}{Jen cestuji.}
{104}{}{Ehm, proè sebou táhneš všechnu tu veteš?}
{105}{}{Potøebuju najít vodní èip.}
{106}{}{Zabíjím každého, kdo se mi dostane na dostøel. Pøiprav se na smrt.}
{107}{}{Lub!}
{108}{}{Aha. Tedy nìco jako já.}
{109}{}{Och? Nepatøíš k žádné z místních komunit?}
{110}{}{Ukážeš mi smìr k nejbližším lidským obydlím?}
{111}{}{Tak co mi o sobì povíš?}
{112}{}{Hm, na vidìnou.}
{113}{}{To není veteš. To je obchodní sortiment!}
{114}{}{Aha, dobøe. Sbohem.}
{115}{}{Uh huh. Tak co mi o sobì povíš?}
{116}{}{Hmm. Nic takového jsem ještì nevidìl. V èem je problém?}
{117}{}{Èip øídí kontrolu èistoty vody v mém Vaultu. A teï nám odešel.}
{118}{}{Je to rozbitý.}
{119}{}{Putuji z místa na místo a vydìlávám si na živobytí hudbou a obèasnými opravami.}
{120}{}{Co dìláš za práce?}
{121}{}{Jaké písnièky zpíváš?}
{122}{}{Rád jsem tì poznal, sbohem a na vidìnou.}
{123}{}{Pokud pùjdeš k pobøeží, za týden dorazíš k Shady Sands a pár dní na jih je Junktown. Hub je dalších pár dní cesty do vnitrozemí na jih od Juntownu. Vyhni se Nekropoli na východì. Nestojí za ty trable.}
{124}{}{Co víš o Shady Sands?}
{125}{}{Co víš o Junktownu?}
{126}{}{Co víš o Hubu?}
{127}{}{Co víš o Nekropoli?}
{128}{}{S tím ti asi nepomùžu, nemìl jsem moc možností studovat pøedváleèné technologie používané ve Vaultech.}
{129}{}{Vìtšinou drobnì elektrické a mechanické opravy. Pomohl jsem v Junktownu s veøejným osvìtlením a ukázal lidem v Shady Sands modernìjší varianty kamen a pecí.}
{130}{}{Vážnì? Dokázal bys opravit vodní èip?}
{131}{}{Och, vìtšinou staré folkové písnì a keltskou hudbu. Je to zmìna rytmu.}
{132}{}{Znal bys tøeba "Deireadh An Tuath", nebo jak se to jmenuje?}
{133}{}{Aha. Co ještì dìláš?}
{134}{}{Shady Sands je malá sobìstaèná vesnice. Vede ji Aradesh, pøímý a silný vùdce. Tìžce pracují a jsou mírumilovní. Oni jsou asi nejlepší možnost nové civilizace.}
{135}{}{Shady Sands je malá farmáøská vesnice. Vedl je Aradesh, který prý zemøel. Je to škoda, bez nìj nevím, jestli komunita pøežije.}
{136}{}{Junktown? Malé obchodní mìsteèko. Podivné místo, dokud si nezvykneš. Vede ho Killian Darkwater, pøísný, ale spravedlivý starosta.}
{137}{}{Junktown? Malé obchodní mìsteèko. Podivné místo, dokud si nezvykneš. Vede ho Gizmo, herní magnát a kápo veškerého zloèinu.}
{138}{}{Junktown? Malé obchodní mìsteèko. Nic neobvyklého.}
{139}{}{Hub je významným centrem obchodu. Øíká se, že tam mùžeš sehnat prakticky cokoli, a já tvrdím, že to není nic dobrého.}
{140}{}{Nekropolis je mìsto mrtvých. Obývají ho ghúlové, potomci obyvatel místního Vaultu. Øíká se, že Vault nìjakým zpùsobem pøestal fungovat a z obyvatel se stali souèasní požíraèi mrtvol.}
{141}{}{Podle všeho bylo Nekropolis vyhlazeno armádou supermutantù. Být tebou, vyhnu se mu na sto honù.}
{142}{}{Myslíš, že by se z toho Vaultu daly zachránit souèástky, které tak nutnì sháním?}
{143}{}{Možná, ale neriskoval bych to kvùli jednomu èipu. Ghúlové prý mají nìjakého nového mocného kapitána.}
{144}{}{Proè, ovšem. Chceš si poslechnout?}
{145}{}{Jistì.}
{146}{}{Ani ne.}
{147}{}{[Patrick zpívá písnì a oba se oddáváte vzpomínkám. Cítíš se osvìžen.]}
{148}{}{Rád tì zase vidím. Chceš nìjak pomoct?}
{149}{}{Jo, potøeboval bych trochu nasmìrovat?}
{150}{}{Ne to nic, díky.}
