{100}{}{Vidíš boxera Saula.}
{101}{}{Vidíš drsnì vypadajícího svalovce.}
{102}{}{Má léty bojù vypracované tìlo a jeho postoj prozrazuje zkušeného boxera.}
{103}{}{Aha, dobrá, hodnì štìstí.}
{104}{}{Tohle není místo na boj se zbranìmi, pøíteli. Ale pokud bys mì chtìl vyzkoušet v ringu, mùžeš to kdykoli zkusit.}
{105}{}{Co chceš?}
{106}{}{Ano?}
{107}{}{Co tady dìláš?}
{108}{}{Drsòák, co? Vsadim se, že bych tì dostal.}
{109}{}{Jmenuju se }
{110}{}{. Jenom se tu porozhlížim.}
{111}{}{[Saul se srdeènì smìje.] Já jsem boxer! Proè se ptáš?}
{112}{}{He, nakopal bych ti prdel.}
{113}{}{Hmm. A co ješte?}
{114}{}{Ehm, ne díky.}
{115}{}{Saul je v bezvìdomí.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{}
{122}{}{}
{123}{}{}
{124}{}{[Saul se smìje srdeènì.]}
{125}{}{[Saul se smìje výhrùžnì.]}
{126}{}{Dobrá. To by mìlo jít rychle.}
{127}{}{Buï nìco navrhni nebo drž hubu.}
{128}{}{Jo, seš na správnym místì, pokud hledáš nìkoho, kdo tvùj hnusnej ksicht trochu vyspraví.}
{129}{}{Jsem Saul.}
{130}{}{Ale ne, díky. Mùžu se na nìco zeptat?}
{131}{}{Žiješ v Junktownu dlouho?}
{132}{}{Rád jsem tì poznal, uvidíme se pozdìji.}
{133}{}{Ano.}
{134}{}{Jsem tu odjakživa. Vyrostl jsem tady.}
{135}{}{Co mi prozradíš o Junktownu?}
{136}{}{Jak ses stal boxerem?}
{137}{}{Hmm. Dobøe, cizinèe, dìlám pro Gizma. Vlastní tady velký kasino a platí, alespoò nám bojovníkùm, dost dobøe. Co bys chtìl ještì vìdìt?}
{138}{}{Co se tady dá dìlat?}
{139}{}{Øekneš mi nìco o Gizmovi a jeho kasinu?}
{140}{}{Pár let už boxuju.}
{141}{}{V dìtství jsem se poøád rval s bráchama. Jednou Junktown pøepadla skupinka nájezdníkù a já jednoho srazil k zemi døív, než staèil tasit zbraò. Prostì klika, ale Gizmo poøádal organizované zápasy a já potøeboval prachy. Od tý doby boxuju.}
{142}{}{Co se stalo tvým bratrùm?}
{143}{}{Co se dá v tomhle mìstì dìlat?}
{144}{}{Mùžeš mi øíct nìco o svém šéfovi?}
{145}{}{Jestli sháníš zásoby, nejlepší bude zastavit se v obchodì Killiana Darkwatera, najdeš ho na jihovýchod od nás. Ubytování se dá zajistit v hotlu Crash House, ten je tady poblíž. Jestli se tu zdržíš dýl, na sklenièku mùžeš zaskoèit do Skum Pittu, ale dej pøi tom pozor na gang Lebkounù.}
{146}{}{Co jsou zaè ty Lebkouni?}
{147}{}{Tak mi øekni nìco o kasinu.}
{148}{}{Gizmovo kasino je rájem všech hazardních hráèù. Je tam spousta pøíležitostí, jak strávit èas hazardem, pokud tì to baví! Podle mì je to nejlepší místo na sever od Hubu!}
{149}{}{Co jinýho se tu dá ještì dìlat?}
{150}{}{Mýho bráchu Jamese zabili pøi nájezdu pøed pár lety. Krátce potom se sebral mùj druhej brácha, Darrell, a vyrazil nìkam na jih hledat mýtickej Kráter, místo, kde se prej daj najít starý poklady, nebo tak nìco. Nikdy už se nevrátil.}
{151}{}{Proè zùstáváš v Junktownu?}
{152}{}{Uf, nezmìníme radìji téma?}
{153}{}{Tvoje ztráta mì mrzí.}
{154}{}{Víš ještì nìco o tom legendárním Kráteru?}
{155}{}{Díky. Už je to pár let, ale poøád o tom nerad mluvim.}
{156}{}{Mùžu se ještì na nìco zeptat?}
{157}{}{Žiju tady. Rád boxuju, s Trish se mi nežije špatnì, a nijak netoužím odejít.}
{158}{}{Ah. Tak fajn. Nevadí, když zmìníme téma?}
{159}{}{Jo, Trish jsem potkal.}
{160}{}{Dobrá, co tedy?}
{161}{}{Život tady je drsnej. Nejde o to, jak tvrdý dáváš rány, ale jak tvrdý rány umíš pøijmout a pokraèovat dál. Nezapomínej, možná boxuješ skvìle, ale já jsem skvìlej boxer. A nezapomeò mít ruce vzhùru a hýbat boky jako bys tanèil... pìknì do rytmu, levá... pravá... úhyb... úder, úder... S èím ti ještì mohu pomoci?}
{162}{}{Co se tu dá dìlat?}
{163}{}{Prozradíš mi ještì nìco o svém šéfovi?}
{164}{}{[Poklepáváš na svou zbraò] Chci aby ses seznámil s mým pøítelíèkem.}
{165}{}{Díky za pokec. Ještì se uvidíme.}
{166}{}{Lebkouni jsou jen banda místních spratkù. Zdržují se v zadní èásti Crash House nebo ve Skum Pittu. Dej si na nì pozor... Rádi vyvolávají rvaèky a hrajou si s nožema.}
{167}{}{Díky za radu. Dám si pozor.}
{168}{}{Aha. Ještì nìco, co bych mìl vìdìt?}
{169}{}{Dobøe, pracky pryè, jasný?}
{170}{}{Je pro mì hroznì dùležitá.}
{171}{}{[Saul se mraèí.] Ale jí se nelíbí, že boxuju. Nemùže pochopit, že je to pøesnì to, co chci dìlat.}
{172}{}{Prostì jí záleží na tvém zdraví. Urèitì nesnáší, když tì nìkdo mlátí nebo když nasazuješ krk pro Gizma. Pokud tohle nìjak nevyøešíš, mohl bys o ni pøijít.}
{173}{}{Myslím, že se o tebe bojí.}
{174}{}{Mohli bychom mluvit o nìèem jiném?}
{175}{}{Dobrá, ještì se uvidíme.}
{176}{}{Takhle jsem o tom nikdy neuvažoval. Mìl jsem za to, že prostì nemá ráda moje boxování. Budu si s ní o tom muset promluvit. Díky.}
{177}{}{Eh, prostì nemá ráda boxování, to je všechno.}
{178}{}{Mùžeme mluvit o nìèem jiném?}
{179}{}{Na vidìnou.}
{180}{}{Á, zase ty. Co potøebuješ?}
{181}{}{Zdravím tì.}
{182}{}{Myslím že jsi slaboch a hravì tì porazím! Dáme zápas?}
{183}{}{Potøebuju si s tebou promluvit o Trish.}
{184}{}{Prozradíš mi nìco o Junktownu?}
{185}{}{Podle toho, co jsem slyšel, Kráter je hluboká ïoura, která v noci záøí do dálky. Mìl by být hodnì daleko na jihu, ale kde pøesnì, to nevím. Øíká se, že Kráter obývají hordy všemožných zmutovaných pøíšer, které stráží technologie z pøedváleèné éry.}
{186}{}{Aha. Dík za informace.}
{187}{}{Zajímavé. Mùžeš mi øíct víc?}
{188}{}{Bez hlavy to pùjde dost tìžko, køupane.}

# Fo1in2
{200}{}{Mluvil jsem s Trish.}
