{100}{}{Zpozoroval jsi funkèní bezpeènostní kameru.}
{101}{}{Zpozoroval jsi skryté zbranì sledující tvùj pohyb.}
{102}{}{Skryté zbranì zahajují palbu! Uskakováním a klièkováním se ti daøí vyhnout se zranìní!}
{103}{}{Skryté zbranì zahajují palbu! Klièkuješ a ustupuješ, utržil jsi jen pár škrábancù.}
{104}{}{Utrpìl jsi }
{105}{}{ zranìní.}
{106}{}{Skryté zbranì zahajují palbu! Pøekvapen uskakuješ a padáš, jen s lehèími zranìními.}
{107}{}{Utrpìl jsi }
{108}{}{ zranìní.}
{109}{}{Skryté zbranì zahajují palbu! Jsi zasažen!}
{110}{}{Utrpìl jsi }
{111}{}{ zranìní.}
