{100}{}{Vidíš Sharka.}
{101}{}{Vidíš mue se zpilovanımi zuby.}
{102}{}{Ty dìvko!}
{103}{}{Á, èerstvı krmivo! Co tì pøivádí na naše území, kámo? Trochu se pobavíme? Na tvùj úèet, samozøejmì.}
{104}{}{Vlastnì jsem pøišel nakopat pár prdelí a vejknout si . . .  zbytek si mùeš domyslet.}
{105}{}{Èím se tady bavíte?}
{106}{}{Uf, vlastnì jsem na odchodu, sbohem.}
{107}{}{Jen jsem se stavil na pár panákù a trochu . . . povyraení.}
{108}{}{Glopf!}
{109}{}{Pozéry jako ty tady bièujeme!}
{110}{}{Ne tak rychle! Nikdo jen tak neodejde, ani by zaplatil daò bolesti.}
{111}{}{Myslím, e to udìláš. Pánové, chyte ji.}
{112}{}{Dovolte, abych vám pøedstavil vıbìrèího daní. [Hluboce se ukloní a sáhne po zbrani] Prosím øíkejte mu Pan Kladivo!}
{113}{}{To nemyslím!}
{114}{}{Dobrá, pro dnešní veèerní potìšení jsme se rozhodli rozsekat tohle místo na kousky! He. Posbírejte, co mùete a a teèe krev, co?}
{115}{}{Myslím, e si dám pivo.}
{116}{}{Štípnout a rozbít? Poèítejte se mnou!}
{117}{}{Dneska veèer ne, bolí mì hlava.}
{118}{}{Ne, radši bych si dal nìco k jídlu . . . co tøeba grilovanıho raloka!}
{119}{}{Ach, ty posero. Utíkej zpátky k mamince.}
{120}{}{Zase ty? Sakra, nìkdo je prostì nepouèitelnej!}
{121}{}{Zastavil jsem se jen na pár drinkù.}
{122}{}{U mizím, nevadí.}
{123}{}{Glorpf!}
{124}{}{To není špatnej nápad. Asi si taky jedno dám. Krveprolití je potøeba vdycky spláchnout nìjakym pivem!}
{125}{}{Myslel jsem, e u to chápeš. Asi jsem se splet. Nevadí, aspoò bude nìjaká legrace, a tì budu mlátit!}
{126}{}{Vrátíme se, staøíku. Ještì to neskonèilo.}

# TMA
{970}{}{To jsem já.}
{971}{}{Kdo se ptá?}
{972}{}{Koleduješ si?}

{980}{}{Snaíš se mì nasrat? Padej!}
{981}{}{Kliï se mi z oèí.}
{982}{}{Neser.}
