{100}{}{Vidíš Sinthii, pøitalivou šlapku.}
{101}{}{Vidíš našpulenou, pìknou enu.}
{102}{}{Hej zlato, jak se máš?}
{103}{}{Fajn. Sbohem.}
{104}{}{Docela fajn, ale mohlo by bejt líp.}
{105}{}{Uhh.}
{106}{}{Oh, brouku, rozumím. Mìl by ses vrátit k mámì. A budeš potøebovat lásku, tak se vra!}
{107}{}{Jo, zlato, tobì taky.}
{108}{}{Najdeš cokoli nebo kohokoli hledáš, zlato, a bude ti líp, jsem si jistá.}
{109}{}{S tím ti snad mùu pomoct.}
{110}{}{Moná mùeš. Jaká je tvoje taxa?}
{111}{}{Nenechal bych svıho psa, aby se tì dotknul.}
{112}{}{Och, zlato, kdy ses zeptal . . . víc ne si mùeš dovolit. Moná pøíštì, fešáku. Mìj se.}
{113}{}{Och, brouku, to je prostì nechutné.}
{114}{}{Och, boe, pomoz mi, prosím.}
{115}{}{Prosím, nedovol, aby mì zabil.}
{116}{}{Jsem mladá, nechci ještì umøít.}
{117}{}{Och, boe, jsem pøíliš krásná, abych zemøela.}
{118}{}{Dík za to, cos udìlal. Nikdo pøedtím se o mì takhle nikdy nestaral.}
{119}{}{Pozdìji se o tebe mùu opravdu postarat.}
{120}{}{Nemáš zaè.}
{121}{}{Unh.}
{122}{}{Ještì jednou dík.}
{123}{}{Musíš myslet jen na to? Pche. To jsou lidi.}
{124}{}{Myslím tím, mùj šéf ani neposlal pár svıch zabijákù, aby pomohli. Pøedpokládal bys, e za všechny ty peníze, co tomu hajzlovi vydìlávám, aspoò dodrí svou èást dohody.}
{125}{}{Kdo je tvùj šéf?}
{126}{}{Jaká dohoda?}
{127}{}{Gizmo, jak jinak. Má pod palcem všechnu špinavost ve mìstì. Killiana nezajímám já, ani mnì podobné... nehnul by pro nás brvou. Kdybych Gizmovi nevydìlávala hromady prachù, musela bych pro nìj dìlat jinı vìci.}
{128}{}{A, zlato, tyhle myšlenky mi nedìlají dvakrát dobøe na aludek.}
{129}{}{Co má ještì Gizmo pod palcem?}
{130}{}{Mìla bys s tím seknout a vzít ivot do vlastních rukou.}
{131}{}{To se ti øekne. Ale co jinıho mùu dìlat? Vypadá to, e byl mùj ivot byl navren nìkım jinım. No, dobrá. Dívka má zpøíjemòovat ivot.}
{132}{}{Ale zlato, tohle je zadarmo.}
{133}{}{Ještì jednou díky, zlato. My eny musíme dret pospolu.}
{134}{}{Má pod palcem všechno to špatnı v tomhle mìste. Vlastní kasino. Vlastní mì a pár dalších holek, dokonce i Lebkouny. Slyšela jsem, e by chtìl získat i Nealùv bar. [Sintia si vytáhne jednu cigaretu z krabièky a vloí si ji mezi své rùové rty.] Mìla jsem tady kamarádky ale Izo s nimi nebyl spokojenı. Gizmo je pak prodal nìkam do Hubu. Doufám e jsou v poøádku. Chybí mi... holky moje. [Bøeèí.]}
{135}{}{Dr se od nìj dál, platí? Vìø mi, není takovı, jakım se snaí pøed tebou vypadat. Dr se stranou.}
{136}{}{Gizmo by se chtìl postarat o Killiana, jestli mi rozumíš.}
{137}{}{Drahoušku, víš.. starám se o chlapy a ti se na oplátku starají o mì. Gizmo dostává 25% a za to mì chrání. Taká byla naše dohoda. Ale vidìl jsi sám zlato... Nikoho neposlal. [Pláèe] }
{138}{}{Co ještì Gizmo øídí?}
{139}{}{Cítíš, jako bys zaplatil další návštìvu Sinthie.}
{140}{}{Moná by Sinthia uvítala spoleènost . . .}
{141}{}{Ty sráèi! Zabils ho! Proè jsi ho musel zabít? Ty parchante! Nemùu tomu uvìøit. Vdy si chtìl jenom trochu s nìkım popovídat. Lidskı ivot je ti úplnì jedno, co?}
{142}{}{Ty krkávo! Zabilas ho! Proè jsi ho musela zabít? Ty dìvko! Nemùu tomu uvìøit. Vdy si chtìl jenom trochu s nìkım popovídat. Lidskı ivot je ti úplnì jedno, co?}
{143}{}{Koukej sakra vypadnout z mıho pokoje!}
{144}{}{Zabils ho! Nemùu tomu uvìøit. Vdy si chtìl jenom trochu s nìkım popovídat. . . .}
{145}{}{Není mrtvı. Uhodil se jenom do hlavy, kdy vstával.}
{146}{}{Hnnn.}
{147}{}{Jo, jasnì. Sakra, vypadni z mıho pokoje!}
{148}{}{Jé, promiò. Myslela jsem, e je mrtvı. e jsi ho zabil. Není zas tak špatnej chlápek. Je jen trochu opuštìnej.}
{149}{}{V pohodì.}
{150}{}{Zase ty. S èím ti mùu tentokrát pomoci?}
{151}{}{Jen jsem se stavil podívat, jak se máš.}
{152}{}{Mám $40, jestli ty máš 10 minut.}
{153}{}{Potøeboval bych vìdìt ještì nìco o tvym šéfovi.}
{154}{}{Ale, zlato, to si nemyslím. Pøedstav si, jak by dìti mohly dopadnout.}
{155}{}{Perfektnì, díky tobì, drahoušku.}
{156}{}{Co chceš vìdìt, zlato, ale rychle. Jsem v práci, víš.}
{157}{}{Kolik má stráí?}
{158}{}{Kde má schované peníze?}
{159}{}{Má nìjakı slabiny?}
{160}{}{Díky, panenko, u nic vìdìt nepotøebuju.}
{161}{}{Hmm. Vím o osmi, osobnì, jestli mi rozumíš. Myslím, e má ještì dalších deset nebo tak.}
{162}{}{Peníze? Jak to mám vìdìt? Bere si jenom moje, neukazuje mi ty svoje. Pravdìpodobnì je má v lonici, ale všechno co vím je, e je bude mít nìkde, kam slunce nesvítí a to je v jeho pøípadì dost širokı pojem.}
{163}{}{Jedinì to, e si myslí, e ádné nemá. Jo, a taky je to tlustej špekoun, kterej není nejpohyblivìjší. Musí mít pomocníky, aby se mohl pohybovat. A pøesto musí pouívat malou trojkolku. Che che.}
{164}{}{Zlato, jsi skvìlá.}
{165}{}{Jasnì, zlato, pro tebe.}
{166}{}{Bude se ti to líbit.}
{167}{}{Zlato, potøebuješ víc penìz. Mám tì ráda, ale musím myslet i na sebe.}
{168}{}{Mám právo odmítnout a zlato, ty se ke mì ani nepøiblííš!}
{169}{}{Sinthia je ospalá.}
{170}{}{Sinthia je v jednom kole.}
{171}{}{Sinthia s tebou odmítá mluvit.}
{172}{}{Sory, lásko, nedìlám blázny.}
{173}{}{Vezmi si prachy, svùj postoj a svıho mròouse nìkam jinam!}
{174}{}{Och, boe, pomozte mi nìkdo!}
{175}{}{Získal jsi }
{176}{}{ bodù zkušenosti za úspìšnou záchranu Sinthie.}
{177}{}{Stráe odvlekli bezvìdomého nájezdníka.}
#
