{100}{}{Vidíš pouštního lupièe Tolyu.}
{101}{}{Ahoj, já jsem Tolya. Vypadá to, že jsi pøišel z pouštì. Kdo jsi?}
{102}{}{Jmenuju se }
{103}{}{. Co dìláš?}
{104}{}{Mùžeš mi nìco øíct o tvém táboru?}
{105}{}{Urgh?}
{106}{}{Jako nájezdník prozkoumávám zemi a hledám nové zásoby. Pár mìst už bylo poctìno naší pøítomností.}
{107}{}{Jinak øeèeno, okrádáš lidi, které navštívíš.}
{108}{}{Hej, to je od tebe opravdu skvìlé. Vìøím, že Garl je s tebou spokojen.}
{109}{}{Kde si všude byl?}
{110}{}{Tak hele, Garl mi øekl, abych nikdy nemluvil s cidzinci. Jenže ja si s takovýma rád pokecám. Když Garl potrebuje nìco zjistit, obráti se na mì. Kluci mi sem pøivedou lidi, co vìdí víc než já a pak si s nimi "povídám". Nìkdy se musím ptát docela drsnì. Tak napøíklad dnes v noci jsem zabil tøi chlapy. Pøedtím jsem je muèil. Fòukali a škemrali a fakt hodne køièeli. Jo køièí až dokud je nezlomím! Miluju muèení.. ale to je jenom taková pøedehra. Tak co myslíš? Teï máš pár dobrejch dùvodù øíct mi to svý blbý jméno!}
{111}{}{Máš pravdu. Jsem }
{112}{}{. Øekneš mi nìco o svojí komunitì?}
{113}{}{Podívej, ty idiote. Nemám ti co øíct.}
{114}{}{Bìž nìkam, èurdo.}
{115}{}{Nikdy nekrademe. Bereme jen to, co mají ostatní navíc, a pak to rozdìlíme mezi hladové.}
{116}{}{Takže, prostì kradete.}
{117}{}{To zní jako skvìlá myšlenka.}
{118}{}{V Pustinì jsem už navštívil mnoho míst. Nejbližší místa, kde jsem byl, jsou Shady Sands a Junktown. Tam jsou za naše návštìvy velmi vdìèní.}
{119}{}{Ty jsi byl v Shady Sands?}
{120}{}{Kde je Junktown?}
{121}{}{Zaèínáš být otravný. Myslím, že tenhle jednoduchý problémek vyøeším.}
{122}{}{Jsme Khanové a náš vùdce je Garl Smrtihnát. Jsme nejobávanìjší skupina v pustinì. Bereme si, co chceme a když se nám nekdo postaví do cesty, zaplatí za to životem!}
{123}{}{Ano, èas od èasu do Shady Sands jezdíme. Dodává to trochu vzruchu jinak pøíliš jednotvárnému životu.}
{124}{}{A co Junktown?}
{125}{}{Proè? Junktown je odsud jen kousek na jih. Jdi pár mílí rovnì, a u umírajícího kaktusu doprava. Nemùžeš to minout!}
{126}{}{Také jsi øekl, že už jsi byl v Shady Sands.}
{127}{}{Teï mì neotravuj. Pøipravuju se na další výlet.}
#
# Fallout Fixt:
#
{200}{}{Vidíš Tolyu, kuchaøe Khanù.}
