{100}{}{Vidíš Viktora.}
{101}{}{Vidíš èlena gangu.}
{102}{}{Aaaaggghhh . . .}
{103}{}{Nová krev. Heh. Heh heh.}
{104}{}{Um, Jóó. Uh, Myslím, e pùjdu.}
{105}{}{Ty nejsi pøíliš šastnı èlovìk, e ne?}
{106}{}{Huh huh!}
{107}{}{Ne, nikam nepùjdeš! To jako co zkùšaš?! Co?! Myslím, e tady chvíli se mnou ještì zùstaneš!}
{108}{}{Proè to øíkáš? Já jsem šastnı. Jsem šastnı, protoe tady všude je spousta vìcí, ze kterejch cáká krev.}
{109}{}{Jsi fakt nechutnej, víš to?}
{110}{}{Um, Jo. Èau.}
{111}{}{Ah, ano, umìlecké ocenìní. Uh, tomu rozumím. Myslím.}
{112}{}{Nééé! Neøíkej TO! To mi øíkala moje matka! TY prde! Za to budeš pykat! [Pøestává se ovládat] Viï, e jsem tvùj hodnej chlapeèek, mami?}
{113}{}{Nìkdo, kdo mi rozumí! Koneènì!}
{114}{}{Zdravíèko, ty mùj umìlèe.}
{115}{}{Ha! Ha! Heh heh hee! Ho ho ha!}
{116}{}{Chrrrrr}
{117}{}{Victore, u jsem ti nìkdy øekl, e seš opravdu nechutnej?}
{118}{}{Uh, ahoj.}
