{100}{}{Podaøilo se ti vyhnout nebezpeènému monovláknu jdoucího napøíè chodbou.}
{101}{}{Cítíš intenzivní bolest v nohou. Monovlákno tì pøeøízlo vejpùl.}
{102}{}{Poranilo ti to na nìkolika místech pravou nohu.}
{103}{}{Poranilo ti to na nìkolika místech levou nohu.}
{104}{}{Tìsnì pøed tím, než by ti monovlákno uøízlo ruce, se ti podaøilo zneškodnit past a tím se jí vyhnout.}
{105}{}{Zkusil si zneškodnit monovlákno, ale nìjak se ti to nedaøí. Radìji si uhnul pøed tím, než tì pøeøízlo vejpùl.}
{106}{}{Zkusil si zneškodnit monovlákno, ale vyklouzlo ti a ošklivì jsi se poøezal.}
