{100}{}{Vidíš hlídaèe vody.}
{101}{}{Á, }
{102}{}{. Jak se máš?}
{103}{}{Ahoj. Jak de ivot?}
{104}{}{Gahh!}
{105}{}{Take Gahh! no . . . Je mi líto, e ses nikdy nenauèil mluvit. Mohli jsme bıt dobøí pøátelé.}
{106}{}{Ouuu.}
{107}{}{Necítím se moc dobøe. Nìkdo mì praštil velkou trubkou do hlavy. Byl jsem u doktora, ale hlava mì poøád bolí. Doufám, e toho hajzla, co mì praštil, nìkdo chytí.}
{108}{}{Proè to udìlal?}
{109}{}{Ufff.}
{110}{}{No, zaútoèili na mì jednou pozdì veèer. Obyèejnì odcházím okolo osmé nebo trochu døív, ale tenkrát jsem tam zùstal do noci, protoe nìkdo ukrad trochu vody a já kontroloval naše zásoby. Pak u si jen pamatuji, e sem se probudil na ozdravovnì s velkou boulí na hlavì. Poslední dobou se tu dìjou divnı vìci. Moná se bude kvùli vodì brzo i zabíjet a já poøád nevím, co proti tomu budeme dìlat.}
{111}{}{Uvidím co mùu udìlat.}
{112}{}{To je mi líto. Doufám, e ti bude brzo líp.}
{113}{}{Tady je voda.}
{114}{}{Tady je tvá denní dávka.}
{115}{}{Hej! Co si myslíš, e dìláš?!?}
{116}{}{Prosím, neber si pøíliš mnoho z našich zásob. Budeme je potøebovat.}
{117}{}{Nahrál jsi své záznamy do systémové knihovny poèítaèe. Mìl by ses vrátit ke Správci, abys dokonèil své hlášení.}
# TRANSLATION NOTE
# The player-character's name is inserted by code between lines 118 and 119.
{118}{}{Á, }
{119}{}{. Dobrı den.}
{120}{}{Ahoj. Co se tady dìlo?}
{121}{}{Øeknìme, co tady dìláš?}
{122}{}{Situace ve Vaultu je poslední dobou hodnì napjatá. Lidé se zaèali vypoøádávat se stresem rùznımi zpùsoby. Nìkdo se opíjí, jinı breèí a našli se i takoví co zaèali ít velmi... prostopášnım ivotním stylem. Hele, a si kadı spí s kım chce, ale bùh mi pomáhej, pokud budu muset øešit další mileneckou hádku. Dokonce se nám tady zaèali mnoit i konspiraèní teorie, e správce Jacoren je ve skuteènosti ještìr v pøevleku. Prosím, pospìš si s hledáním toho èipu, protoe se bojím, e nám tady všem hrábne ještì døív, ne nám dojde voda...}
{123}{}{Peèlivì jsem rozdìlil dávky vody a ujistil se, e se nikdo nepokusí vzít víc vody, ne je jeho díl, take si nemyslím, e budeme mít nìjaké problémy.}
{124}{}{Hmm. Dobrá práce, pokraèujte tak dál.}
{125}{}{Ty také. Doufám, e brzy najdeš ten èip, take se budeme moci všichni vrátit k normálnímu ivotu.}
{126}{}{Jestli potøebuješ nìjaké zásoby, vezmi si, co potøebuješ, protoe tvùj úkol je velmi dùleitı. U nám toho ale moc nezbıvá, take si toho, prosím, neber pøíliš.}
{127}{}{Mohu si vzít nìjaké zásoby?}



{1000}{}{Davka}
{1001}{}{Davky}
{1002}{}{Zasoby}
{1003}{}{Voda}


{1100}{}{Rozdìlil jsem ráno další dávky vody. Ty je teï nebudeš potøebovat, kdy jdeš ven.}
{1101}{}{Rozdìlil jsem ráno další dávky vody. Ty je teï nebudeš potøebovat, kdy jdeš ven.}
{1102}{}{U nám moc zásob nezbıvá. Mùeš si trochu vzít, co potøebuješ, ale prosím neber si moc.}
{1103}{}{U nám moc zásob nezbıvá. Mùeš si trochu vzít, co potøebuješ, ale prosím neber si moc.}
