/*

   Boneyard - unused, Jason Zimmerman is dead

*/


#include "define.h"

#define NAME                    SCRIPT_JASON
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BONEYARD)

#include "command.h"

procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure talk_p_proc;

procedure Jason01;
procedure Jason02;
procedure Jason03;
procedure Jason04;
procedure Jason05;
procedure Jason06;
procedure Jason07;
procedure Jason08;
procedure Jason09;
procedure Jason10;
procedure Jason11;
procedure Jason12;
procedure Jason13;
procedure Jason14;
procedure Jason15;
procedure Jason16;
procedure Jason17;
procedure Jason18;
procedure Jason19;
procedure Jason20;
procedure Jason21;
procedure Jason22;
procedure Jason23;
procedure follow_player;

variable following;
variable initial := 0;

procedure start begin
   if not(initial) then begin
      set_self_team(TEAM_LA_ADYTOWNER);
      initial := 1;
   end
end

procedure critter_p_proc begin
   if (following) then begin
      call follow_player;
   end
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure look_at_p_proc begin
   script_overrides;
   if (not(local_var(1))) then begin
      display_msg(mstr(101));
   end
   else begin
      display_msg(mstr(100));
   end
end

procedure talk_p_proc begin
   dude_look_at_self;
   start_gdialog(382, self_obj, 4, -1, -1);
   gsay_start;
   if (CUR_MAP_LARIPPER) then begin
      if (following) then begin
         call Jason23;
      end
      else begin
         call Jason19;
      end
   end
   if (local_var(0)) then begin
      call Jason18;
   end
   else begin
      if (local_var(1)) then begin
         call Jason16;
      end
      else begin
         call Jason01;
      end
   end
   gsay_end;
   end_dialogue;
end

procedure Jason01 begin
   Reply(102);
   NOption(103, Jason05, 4);
   NOption(104, Jason13, 4);
   NOption(105, Jason08, 4);
   NOption(106, Jason07, 4);
   NLowOption(107, Jason02);
end

procedure Jason02 begin
   NMessage(108);
end

procedure Jason03 begin
   NMessage(109);
   NMessage(110);
end

procedure Jason04 begin
   NMessage(111);
   NMessage(112);
end

procedure Jason05 begin
   Reply(113);
   NOption(114, Jason06, 4);
   NOption(115, Jason14, 4);
end

procedure Jason06 begin
   Reply(116);
   NOption(117, Jason07, 4);
   NOption(118, Jason08, 4);
   NOption(119, Jason15, 6);
end

procedure Jason07 begin
   Reply(120);
   NOption(121, Jason12, 4);
   NOption(122, Jason08, 4);
end

procedure Jason08 begin
   Reply(123);
   NOption(124, Jason12, 4);
end

procedure Jason09 begin
   Reply(125);
   NOption(126, Jason10, 4);
   NOption(127, Jason11, 4);
end

procedure Jason10 begin
   NMessage(128);
end

procedure Jason11 begin
   NMessage(129);
end

procedure Jason12 begin
   NMessage(130);
end

procedure Jason13 begin
   NMessage(131);
   set_local_var(0, 1);
end

procedure Jason14 begin
   NMessage(132);
   call Jason10;
end

procedure Jason15 begin
   NMessage(133);
   call Jason11;
end

procedure Jason16 begin
   Reply(134);
   NOption(135, Jason08, 4);
   NOption(136, Jason17, 4);
end

procedure Jason17 begin
   NMessage(137);
end

procedure Jason18 begin
   NMessage(138);
end

procedure Jason19 begin
   Reply(139);
   NLowOption(140, Jason20);
   NOption(141, Jason20, 4);
   NOption(142, Jason21, 4);
   NOption(143, Jason22, 4);
end

procedure Jason20 begin
   NMessage(144);
   set_self_team(TEAM_PLAYER);
   following := 1;
end

procedure Jason21 begin
   NMessage(145);
end

procedure Jason22 begin
   Reply(146);
   NOption(147, Jason20, 4);
   NOption(148, Jason21, 4);
end

procedure Jason23 begin
   NMessage(149);
end

procedure follow_player begin
   if (tile_distance_objs(self_obj, dude_obj) > 7) then begin
      self_run_to_tile(dude_tile);
   end
   else begin
      if (tile_distance_objs(self_obj, dude_obj) > 3) then begin
         self_walk_to_tile(dude_tile);
      end
      else begin
         self_walk_to_tile(self_tile);
      end
   end
end
