/*

   Vault 15 - Elevator on level 2

*/

#include "define.h"

#define NAME                    SCRIPT_BVELV3

#include "command.h"

procedure start;
procedure use_p_proc;

procedure start begin
end

procedure use_p_proc begin
   if ((anim_busy(dude_obj) != 0) or (anim_busy(dude_obj) == 0)) then begin
      script_overrides;
      move_to(dude_obj, 23102, 1);
      dude_rotate(2);
   end
end

