#include "define.h"

#define NAME                    SCRIPT_BVSTORE

#include "command.h"

procedure start;

procedure start begin
end

procedure spatial_p_proc begin
   if source_is_dude then begin
      if (local_var(0) == 0) then begin
         set_local_var(0, 1);
         if (dude_stat_success(STAT_pe, 0)) then begin
            display_msg(mstr(101));
         end
         set_local_var(0, 1);
      end
   end
end
