#include "define.h"

#define NAME                    SCRIPT_MEETING

#define LVAR_Only_Once        (0)

#include "command.h"

procedure start;

procedure start begin
end

procedure spatial_p_proc begin
   if source_is_dude then begin
      if (local_var(LVAR_Only_Once) == 0) then begin
         set_local_var(LVAR_Only_Once, 1);
         if (dude_stat_success(STAT_iq, 0)) then begin
            display_msg(mstr(100));
         end
      end
   end
end
