#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
#
{100}{}{ HECHO}
{101}{}{OPCIONES}
{102}{}{CANCELAR}
{103}{}{IMPRIMIR}
{104}{}{EDAD}
{105}{}{SEXO}
{106}{}{NOMBRE}
{107}{}{HOMBRE}
{108}{}{MUJER}
{109}{}{VENTAJAS}
{110}{}{KARMA}
{111}{}{MUERTES}
{112}{}{PTS. TÉCNICOS}
{113}{}{Nivel:}
{114}{}{Exp:}
{115}{}{Próx. Nivel:}
{116}{}{PUNTOS PERSONAJE}
{117}{}{TÉCNICAS}
{118}{}{¡Debes usar todos los puntos de} # 1
{119}{}{personaje antes de empezar a jugar!}         # 2
#
{120}{}{Puntos de Personaje}
{121}{}{Cantidad libre de puntos de personaje que se pueden añadir a uno de los estados básicos.}
{122}{}{Próximo Nivel}
{123}{}{Puntos de experiencia requeridos para obtener el siguiente nivel.}
{124}{}{Ventajas}
{125}{}{Karma}
{126}{}{Muertes}
{127}{}{Las Ventajas añaden habilidades adicionales. En cada tercer nivel de experiencia podrás elegir una Ventaja.}
{128}{}{Son los efectos de las decisiones que tomas durante la partida.}
{129}{}{Lleva la cuenta del tipo y cantidad de criaturas que has aniquilado, o que han sido asesinadas en tu presencia.}
{130}{}{Puntos Técnicos}
{131}{}{Usa los puntos de técnica disponibles para aumentar el nivel de una técnica.}
#
{132}{}{Nivel máximo.}        # 1
{133}{}{Imposible aumentarlo.}  # 2
{134}{}{Nivel mínimo.}        # 1
{135}{}{Imposible disminuirlo.}  # 2
{136}{}{No hay Pts. Técnicos disponibles}
{137}{}{Base:}
{138}{}{PTS. DE TÉCNICA}
{139}{}{EXTRAS OPCIONALES}
{140}{}{¡Ya tienes el máximo de} # 1
{141}{}{tres habilidades!}               # 2
{142}{}{¡Debes seleccionar todas las habilidades}  # 1
{143}{}{antes de empezar a jugar!}       # 2
{144}{}{Técnicas Destacadas}
{145}{}{Estas son técnicas en las que tu personaje se especializa. Cada técnica aumenta en +20%, y crece el doble de deprisa. Debes escoger tres técnicas.}
{146}{}{Extras Opcionales}
{147}{}{Los Extras opcionales describen más detalladamente a tus personajes. Todos los extras tendrán efectos positivos y negativos. Puedes escoger hasta dos extras durante la creación.}
{148}{}{¡Ya tienes el máximo de} # 1
{149}{}{dos extras!}                     # 2
{150}{}{Técnicas}
{151}{}{Las técnicas son conocimiento adquirido. Éstas aumentan con la experiencia, o durante los sucesos especiales del juego. Cuanto mayor sea tu nivel en una técnica, mejor serás en ella.}
#
{152}{}{ESCOGE UNA VENTAJA}
{153}{}{ESCOGE UN EXTRA NUEVO}
{154}{}{PIERDE UN EXTRA}
{155}{}{ESCOGE UNA NUEVA TÉCNICA DESTACADA}
{156}{}{EXTRAS}
#
{157}{}{¡Todos los estados deben estar entre} # 1
{158}{}{1 y 10 antes de empezar a jugar!}          # 2


#
# Abbreviated basic stat levels
#
{200}{}{M.Malo}  # Terrible
{201}{}{Malo}    # Bad
{202}{}{Pobre}   # Poor
{203}{}{Justo}   # Fair
{204}{}{Medio}   # Average
{205}{}{Bien}   # Good
{206}{}{M.Bien} # Very Good
{207}{}{Genial}  # Great
{208}{}{Exclnt}  # Excellent
{209}{}{Héroe} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{PS          }
{301}{}{Pts. de Acción}
{302}{}{C. Armadura}
{303}{}{Daño Desarmado}
{304}{}{Daño en Melé}
{305}{}{Res. Daño}
{306}{}{Res. Veneno}
{307}{}{Res. Radiación}
{308}{}{Secuencia}
{309}{}{R. Curación}
{310}{}{Daño Crítico}
{311}{}{Peso Máx.}
{312}{}{Envenenado}
{313}{}{Radiactivo}
{314}{}{Daño Ocular}
{315}{}{Herido Brazo Der.}
{316}{}{Herido Brazo Izq.}
{317}{}{Herida Pierna Der.}
{318}{}{Herida Pierna Izq.}

#
# Damage info texts
#
# Poisoned
{400}{}{Tu personaje ha sido envenenado. El veneno te dañará durante un tiempo, hasta que te cures o hasta que salga de tu sistema.}
# Radiation
{401}{}{Tu personaje sufre una seria intoxicación radioactiva. Cuanto mayor sea el daño radiactivo, más mortal será su efecto.}
# Eye Damage
{402}{}{Esto significa que tu personaje ha sido gravemente herido en uno o en ambos ojos. Esto afecta a tu Percepción.}
# Crippled right arm
{403}{}{Has sido gravemente herido en el brazo derecho, no te funciona bien. Si tienes un brazo herido, no puedes usar armas de dos manos. Si tienes ambos brazos heridos, no puedes atacar con armas.}
# Crippled left arm
{404}{}{El brazo izquierdo de tu personaje ha sido gravemente herido, no funciona bien. Si tienes un brazo herido, no puedes usar armas de dos manos. Si tienes ambos brazos heridos, no puedes atacar con armas.}
# Crippled right leg
{405}{}{Tu personaje tiene la pierna derecha herida.}
# Crippled left leg
{406}{}{Tu personaje tiene la pierna izquierda herida.}

# Month strings
{500}{}{Enero}
{501}{}{Febrero}
{502}{}{Marzo}
{503}{}{Abril}
{504}{}{Mayo}
{505}{}{Junio}
{506}{}{Julio}
{507}{}{Agosto}
{508}{}{Septiembre}
{509}{}{Octubre}
{510}{}{Noviembre}
{511}{}{Diciembre}

#
# Option menu text
#
{600}{}{GUARDAR}
{601}{}{CARGAR}
{602}{}{IMPRIMIR ARCHIVO}
{603}{}{ELIMINAR}
{604}{}{HECHO}
{605}{}{¿Seguro que quieres eliminar}      # line 1
{606}{}{el personaje actual?}                 # line 2
{607}{}{ fue guardado con éxito.}
{608}{}{ fue cargado con éxito.}
{609}{}{ya existe.}
{610}{}{¿Deseas reemplazarlo?}
{611}{}{Error al guardar }
{612}{}{Error al cargar }
{613}{}{Archivo de personaje inválido.}
{614}{}{Datos de personaje inválidos.}
{615}{}{¡Error al leer lista de archivos!}
{616}{}{IMPRIMIR}
{617}{}{JUGADOR}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}                   # Title line 1
{621}{}{REFUGIO 13 INFORMES DEL PERSONAL} # Title line 2
{622}{}{horas} # Title line 3
# -
# -
#{000}{}{        Fuerza: 00  Puntos de Salud: 000/000        Secuencia: 00}
#{000}{}{    Percepción: 00   Clase Armadura: 000       Ritmo Curación: 00}
#{000}{}{   Resistencia: 00   Pts. de Acción: 000  Oportunidad Crítico: 000%}
#{000}{}{       Carisma: 00        Daño Melé: 000          Peso Máximo: 000 lbs.}
#{000}{}{  Inteligencia: 00        Res. Daño: 000%}
#{000}{}{      Agilidad: 00   Res. Radiación: 000%}
#{000}{}{        Suerte: 00      Res. Veneno: 000%}
#
{623}{}{ ::: Estadísticas :::}
{624}{}{             Fuerza:}
{625}{}{    Puntos de Salud:}
{626}{}{          Secuencia:}
# -
{627}{}{         Percepción:}
{628}{}{    Clase de Coraza:}
{629}{}{  Ritmo de Curación:}
# -
{630}{}{        Resistencia:}
{631}{}{   Puntos de Acción:}
{632}{}{Oportunidad Crítico:}
# -
{633}{}{            Carisma:}
{634}{}{       Daño de Melé:}
{635}{}{        Peso Máximo:}
# -
{636}{}{       Inteligencia:}
{637}{}{          Res. Daño:}
# -
{638}{}{           Agilidad:}
{639}{}{     Res. Radiación:}
# -
{640}{}{             Suerte:}
{641}{}{        Res. Veneno:}
# -
# -
#{000}{}{ Nombre: 01234567890       Edad: 00             Género: Mujer}
{642}{}{Nombre:}
{643}{}{Edad:}
{644}{}{          Género:}
{645}{}{Hombre}
{646}{}{Mujer}
#-
#{000}{}{ Nivel: 00                 Exp: 000,000    Prox. Nivel: 000,000}
{647}{}{ Nivel:}
{648}{}{                Exp:}
{649}{}{Prox. Nivel:}
#-
{650}{}{ ::: Extras :::          ::: Ventajas :::          ::: Karma :::}
#-
{651}{}{ ::: Técnicas :::                   ::: Muertes :::}
#-
{652}{}{ ::: Inventario :::}
#-
{653}{}{                                      Peso Total:}

#
# Karma name strings
#
{1000}{}{Reputación (General) }
{1001}{}{Pirado}
{1002}{}{Campeón}
{1003}{}{Asesino}
{1004}{}{Enganchado a la Nuka-Cola}
{1005}{}{Enganchado al Buffout}
{1006}{}{Enganchado al Mentats}
{1007}{}{Enganchado al Psycho}
{1008}{}{Enganchado al FueraRad}
{1009}{}{Enganchado al Alcohol}
#
# Karma description strings
#
{1100}{}{Esto representa tu reputación. Cuanto más alto sea el número, más conocido y respetado eres. Si tu reputación es negativa, algunos te odiarán por tus malvadas acciones.}
{1101}{}{Has matado a mucha gente. No suele ser bien conocido por esto. Pero en fin, al menos les gustarás un poco a los que van por el mal camino.}
{1102}{}{Tus acciones te han revelado como un campeón de la gente. Tu lucha contra el mal y los villanos es ampliamente reconocida. La gente honrada te respetará más.}
{1103}{}{Eres un asesino, matas por placer. Eres una persona mala, malísima.}
{1104}{}{Te encanta la Nuka-Cola, la cola del mundo postnuclear.}
{1105}{}{Te pirran los Esteroides. Debes tomarlos con regularidad o sufrirás los efectos de la abstinencia.}
{1106}{}{Estás enganchado a los Mentats. Debes tomar esta droga o tendrás el mono.}
{1107}{}{Si no tomas Psycho regularmente, sufrirás. Si los haces, serán los demás los que sufrirán.}
{1108}{}{El cuerpo te pide Radaway. Mientras no estés en peligro de muerte, debes colocarte con regularidad.}
{1109}{}{Tienes un problema con el alcohol. Lo cierto es que tienes muchos problemas con la bebida.}
{1110}{}{TEMPORAL - ¿Qué es esto?}


#
# Special Demo version only text
#
{5000}{}{Lo siento, sólo puedes imprimir la}   # 1
{5001}{}{versión completa de tu personaje.}   # 2
{5002}{}{Lo siento, sólo puedes guardar la}    # 1
{5003}{}{versión completa de tu personaje.}   # 2
{5004}{}{Lo siento, sólo puedes cargar la versión} # 1
{5005}{}{completa de un personaje guardado.}   # 2
{5006}{}{MODO TRAMPOSO}
{5007}{}{No disponible en la demo.}



