#
# Inventory messages from inventry.c
#
{0}{}{FU}
{1}{}{PE}
{2}{}{RE}
{3}{}{CA}
{4}{}{IN}
{5}{}{AG}
{6}{}{SU}
{7}{}{PS}
{8}{}{C. Armadura}
{9}{}{Normal}
{10}{}{Láser}
{11}{}{Fuego}
{12}{}{Plasma}
{13}{}{Explosión}
{14}{}{Ningún objeto}
{15}{}{Dñ:}    
{16}{}{Alc:}    
{17}{}{Muni:}     
{18}{}{(No lleva)}
{19}{}{No tienes suficientes puntos de acción para usar el inventario.}
{20}{}{Peso:} 
{21}{}{MOVER OBJETOS}
{22}{}{TODO}
{23}{}{PONER HORA}
{24}{}{Daño desarmado:}
{25}{}{No puedes recoger esto. Llevas ya todo el peso que puedes.}
{26}{}{No hay espacio para ese objeto.}
{27}{}{Vale, es un buen trato.}
{28}{}{No, tu oferta no es suficiente.}
{29}{}{Ganas %d puntos de experiencia por usar con éxito tu técnica (Robar).}

