#
# Item.c messages
#
{1}{}{Has ganado %d %s.}
{2}{}{Has perdido %d %s.}
{3}{}{Te encuentras mejor.}
{4}{}{Sufres un ataque mortal al corazón por sobredosis.}
{5}{}{%s no tiene más cargas.}
{6}{}{%s está encendido.}
{7}{}{%s está apagado.}
{8}{}{Te pasas el contador Geiger por el cuerpo. El marcador REM indica: %d}
{9}{}{Sólo se puede usar este objeto desde la barra del interfaz.}
{10}{}{No pasa nada.}

