
#
# Messages for Maps
#

#
# Map Names for lookups
#	Note: This order must *NOT* change!
#
{0}{}{DESERT1.MAP}
{1}{}{DESERT2.MAP}
{2}{}{DESERT3.MAP}
{3}{}{HALLDED.MAP}
{4}{}{HOTEL.MAP}
{5}{}{WATRSHD.MAP}
{6}{}{VAULT13.MAP}
{7}{}{VAULTENT.MAP}
{8}{}{VAULTBUR.MAP}
{9}{}{VAULTNEC.MAP}
{10}{}{JUNKENT.MAP}
{11}{}{JUNKCSNO.MAP}
{12}{}{JUNKKILL.MAP}
{13}{}{BROHDENT.MAP}
{14}{}{BROHD12.MAP}
{15}{}{BROHD34.MAP}
{16}{}{CAVES.MAP}
{17}{}{CHILDRN1.MAP}
{18}{}{CHILDRN2.MAP}
{19}{}{CITY1.MAP}
{20}{}{COAST1.MAP}
{21}{}{COAST2.MAP}
{22}{}{COLATRUK.MAP}
{23}{}{FSAUSER.MAP}
{24}{}{RAIDERS.MAP}
{25}{}{SHADYE.MAP}
{26}{}{SHADYW.MAP}
{27}{}{GLOWENT.MAP}
{28}{}{LAADYTUM.MAP}
{29}{}{LAFOLLWR.MAP}
{30}{}{MBENT.MAP}
{31}{}{MBSTRG12.MAP}
{32}{}{MBVATS12.MAP}
{33}{}{MSTRLR12.MAP}
{34}{}{MSTRLR34.MAP}
{35}{}{V13ENT.MAP}
{36}{}{HUBENT.MAP}
{37}{}{DETHCLAW.MAP}
{38}{}{HUBDWNTN.MAP}
{39}{}{HUBHEIGT.MAP}
{40}{}{HUBOLDTN.MAP}
{41}{}{HUBWATER.MAP}
{42}{}{GLOW1.MAP}
{43}{}{GLOW2.MAP}
{44}{}{LABLADES.MAP}
{45}{}{LARIPPER.MAP}
{46}{}{LAGUNRUN.MAP}
{47}{}{CHILDEAD.MAP}
{48}{}{MBDEAD.MAP}
{49}{}{MOUNTN1.MAP}
{50}{}{MOUNTN2.MAP}
{51}{}{FOOT.MAP}
{52}{}{TARDIS.MAP}
{53}{}{TALKCOW.MAP}
{54}{}{USEDCAR.MAP}
{55}{}{BRODEAD.MAP}
{56}{}{DESCRVN1.MAP}
{57}{}{DESCRVN2.MAP}
{58}{}{MNTCRVN1.MAP}
{59}{}{MNTCRVN2.MAP}
{60}{}{VIPERS.MAP}
{61}{}{DESCRVN3.MAP}
{62}{}{MNTCRVN3.MAP}
{63}{}{DESCRVN4.MAP}
{64}{}{MNTCRVN4.MAP}
{65}{}{HUBMIS1.MAP}

#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{Desierto}										 // DESERT1.MAP
{101}{}{Desierto}										 // DESERT2.MAP
{102}{}{Desierto}										 // DESERT3.MAP
{103}{}{Necrópolis}                           // HALLDED.MAP
{104}{}{Necrópolis}                           // HOTEL.MAP
{105}{}{Necrópolis}                           // WATRSHD.MAP
{106}{}{Refugio 13} 									 // VAULT13.MAP
{107}{}{Refugio 15}                             // VAULTENT.MAP
{108}{}{Refugio 15} 									 // VAULTBUR.MAP
{109}{}{Necrópolis}                           // VAULTNEC.MAP
{110}{}{Ciudad Vertedero}                             // JUNKENT.MAP
{111}{}{Ciudad Vertedero}                             // JUNKCSNO.MAP
{112}{}{Ciudad Vertedero}                             // JUNKKILL.MAP
{113}{}{La Hermandad}                          // BROHDENT.MAP
{114}{}{La Hermandad}                          // BROHD12.MAP
{115}{}{La Hermandad}                          // BROHD34.MAP
{116}{}{Arenas Sombrías}                          // CAVES.MAP
{117}{}{La Catedral}                            // CHILDRN1.MAP
{118}{}{La Catedral}                            // CHILDRN2.MAP
{119}{}{Ruinas de la Ciudad}									 // CITY1.MAP
{120}{}{Costa} 										 // COAST1.MAP
{121}{}{Costa} 										 // COAST2.MAP
{122}{}{Desierto}										 // COLATRUK.MAP
{123}{}{Desierto}										 // FSAUSER.MAP
{124}{}{Piratas}                              // RAIDERS.MAP
{125}{}{Arenas Sombrías}                          // SHADYE.MAP
{126}{}{Arenas Sombrías}                          // SHADYW.MAP
{127}{}{El Ardor}											 // GLOWENT.MAP
{128}{}{El Cementerio}                             // LAADYTUM.MAP
{129}{}{El Cementerio}                             // LAFOLLWR.MAP
{130}{}{Base Militar}                        // MBENT.MAP
{131}{}{Base Militar}                        // MBSTRG12.MAP
{132}{}{Base Militar}                        // MBVATS12.MAP
{133}{}{Base Militar}                        // MSTRLR12.MAP
{134}{}{Base Militar}                        // MSTRLR34.MAP
{135}{}{Refugio 13}                             // V13ENT.MAP
{136}{}{El Eje}                                  // HUBENT.MAP
{137}{}{El Eje}                                  // DETHCLAW.MAP
{138}{}{El Eje}                                  // HUBDWNTN.MAP
{139}{}{El Eje}                                  // HUBHEIGT.MAP
{140}{}{El Eje}                                  // HUBOLDTN.MAP
{141}{}{El Eje}                                  // HUBWATER.MAP
{142}{}{El Ardor}											 // GLOW1.MAP
{143}{}{El Ardor}											 // GLOW2.MAP
{144}{}{El Cementerio}                             // LABLADES.MAP
{145}{}{El Cementerio}                             // LARIPPER.MAP
{146}{}{El Cementerio}                             // LAGUNRUN.MAP
{147}{}{La Catedral}                            // CHILDEAD.MAP
{148}{}{Base Militar}                             // MBDEAD.MAP
{149}{}{Montañas}									 // MOUNTN1.MAP
{150}{}{Montañas}									 // MOUNTN2.MAP
{151}{}{Desierto}										 // FOOT.MAP
{152}{}{Desierto}										 // TARDIS.MAP
{153}{}{Desierto}										 // TALKCOW.MAP
{154}{}{Desierto}										 // USEDCAR.MAP
{155}{}{La Hermandad}                          // BRODEAD.MAP
{156}{}{Desierto}										 // DESCRVN1.MAP
{157}{}{Desierto}										 // DESCRVN2.MAP
{158}{}{Montañas}									 // MNTCRVN1.MAP
{159}{}{Montañas}									 // MNTCRVN2.MAP
{160}{}{Campamento Víbora}
{161}{}{Desierto}
{162}{}{Montañas}
{163}{}{Desierto}
{164}{}{Montañas}


#
# City elevation names
#
# Format: 3 (max elevations), by city
#
# Desert, DESERT1.MAP
{200}{}{}
{201}{}{}
{202}{}{}
# Desert, DESERT2.MAP
{203}{}{}
{204}{}{}
{205}{}{}
# Desert, DESERT3.MAP
{206}{}{}
{207}{}{}
{208}{}{}
# Necropolis Hall of the Dead, HALLDED.MAP
{209}{}{Alcantarillas}
{210}{}{Sala}
{211}{}{}
# Necropolis Hotel of Doom, HOTEL.MAP
{212}{}{Alcantarillas}
{213}{}{Hotel}
{214}{}{}
# Necropolis Watershed, WATRSHD.MAP
{215}{}{Alcantarillas}
{216}{}{Almacén de Agua}
{217}{}{}
# Vault 13, VAULT13.MAP
{218}{}{Entrada}
{219}{}{Aposentos}
{220}{}{Centro de Mando}
# Buried Vault Entrance, VAULTENT.MAP
{221}{}{Entrada a Cueva}
{222}{}{}
{223}{}{}
# Buried Vault,  VAULTBUR.MAP
{224}{}{Cavernas}
{225}{}{Aposentos}
{226}{}{Centro de Mando}
# Necropolis Vault, VAULTNEC.MAP
{227}{}{Alcantarillas}
{228}{}{Aposentos}
{229}{}{Centro de Mando}
# Junktown Entrance, JUNKENT.MAP
{230}{}{Entrada}
{231}{}{Laboratorio}
{232}{}{}
# Junktown Casino, JUNKCSNO.MAP
{233}{}{Casino}
{234}{}{}
{235}{}{}
# Junktown Killian's, JUNKKILL.MAP
{236}{}{Posada}
{237}{}{}
{238}{}{}
# Brotherhood of Steel Entrance, BROHDENT.MAP
{239}{}{Entrada}
{240}{}{}
{241}{}{}
# Brotherhood of Steel (Upper Levels), BROHD12.MAP
{242}{}{Nivel 1}
{243}{}{Nivel 2}
{244}{}{}
# Brotherhood of Steel (Lower Levels), BROHD34.MAP
{245}{}{Nivel 3}
{246}{}{Nivel 4}
{247}{}{}
# Caves (Shady sands), CAVES.MAP
{248}{}{Cuevas}
{249}{}{}
{250}{}{}
# Cathedral, CHILDRN1.MAP
{251}{}{Entrada}
{252}{}{Torre Nivel 1}
{253}{}{}
# Cathedral Tower, CHILDRN2.MAP
{254}{}{Torre Nivel 2}
{255}{}{Torre Nivel 3}
{256}{}{Torre Nivel 4}
# City Ruins, CITY1.MAP
{257}{}{}
{258}{}{}
{259}{}{}
# Coast, COAST1.MAP
{260}{}{}
{261}{}{}
{262}{}{}
# Coast, COAST2.MAP
{263}{}{}
{264}{}{}
{265}{}{}
# Desert, COLATRUK.MAP
{266}{}{Especial}
{267}{}{}
{268}{}{}
# Desert, FSAUSER.MAP
{269}{}{Especial}
{270}{}{}
{271}{}{}
# Raider's Camp, RAIDERS.MAP
{272}{}{Base}
{273}{}{}
{274}{}{}
# Shady Sands East, SHADYE.MAP
{275}{}{Campo de Cultivo}
{276}{}{Corral de Brahmins}
{277}{}{}
# Shady Sands West, SHADYW.MAP
{278}{}{Ayuntamiento}
{279}{}{}
{280}{}{}
# GLOWENT.MAP
{281}{}{Entrada}
{282}{}{}
{283}{}{}
# LAADYTUM.MAP
{284}{}{Adytum}
{285}{}{Subterráneo}
{286}{}{}
# LAFOLLWR.MAP
{287}{}{Biblioteca}
{288}{}{Subterráneo}
{289}{}{}
# Military Base Entrance, MBENT.MAP
{290}{}{Entrada}
{291}{}{}
{292}{}{}
# Military Base Stronghold, MBSTRG12.MAP
{293}{}{Fortaleza Nivel 1}
{294}{}{Fortaleza Nivel 2}
{295}{}{}
# Military Base Vats, MBVATS12.MAP
{296}{}{Tanques Nivel 1}
{297}{}{Tanques Nivel 2}
{298}{}{}
# Master's Lair (Upper Levels), MSTRLR12.MAP
{299}{}{Guarida Nivel 1}
{300}{}{Guarida Nivel 2}
{301}{}{}
# Master's Lair (Lower Levels), MSTRLR34.MAP
{302}{}{Guarida Nivel 3}
{303}{}{Guarida Nivel 4}
{304}{}{}
# Vault 13 Entrance, V13ENT.MAP
{305}{}{Entrada a Cueva}
{306}{}{}
{307}{}{}
# Hub Entrance, HUBENT.MAP
{308}{}{Entrada}
{309}{}{}
{310}{}{}
# DeathClaw's Lair, DETHCLAW.MAP
{311}{}{Guarida}
{312}{}{}
{313}{}{}
# Hub Downtown, HUBDWNTN.MAP
{314}{}{Centro ciudad}
{315}{}{Escondrijo de Decker}
{316}{}{}
# HUBHEIGT.MAP
{317}{}{Alturas}
{318}{}{}
{319}{}{}
# Hub Old Town, HUBOLDTN.MAP
{320}{}{Ciudad Antigua}
{321}{}{Gremio de los Ladrones}
{322}{}{}
# HUBWATER.MAP
{323}{}{Mercaderes}
{324}{}{}
{325}{}{}
# GLOW1.MAP
{326}{}{Nivel 1}
{327}{}{Nivel 2}
{328}{}{Nivel 3}
# GLOW2.MAP
{329}{}{Nivel 4}
{330}{}{Nivel 5}
{331}{}{Nivel 6}
# LABLADES.MAP
{332}{}{Centro ciudad}
{333}{}{}
{334}{}{}
# LARIPPER.MAP
{335}{}{Almacén} 
{336}{}{Clandestinos}
{337}{}{}
# LAGUNRUN.MAP
{338}{}{Fortaleza}
{339}{}{}
{340}{}{}
# CHILDEAD.MAP
{341}{}{Cráter}
{342}{}{}
{343}{}{}
# MBDEAD.MAP
{344}{}{Ruinas}
{345}{}{}
{346}{}{}
# MOUNTN1.MAP
{347}{}{}
{348}{}{}
{349}{}{}
# MOUNTN2.MAP
{350}{}{}
{351}{}{}
{352}{}{}
# FOOT.MAP
{353}{}{Especial}
{354}{}{}
{355}{}{}
# TARDIS.MAP
{356}{}{Especial}
{357}{}{}
{358}{}{}
# TALKCOW.MAP
{359}{}{Especial}
{360}{}{}
{361}{}{}
# USEDCAR.MAP
{362}{}{Especial}
{363}{}{}
{364}{}{}
# BRODEAD.MAP
{365}{}{Ruinas}
{366}{}{}
{367}{}{}
# DESCRVN1.MAP
{368}{}{}
{369}{}{}
{370}{}{}
# DESCRVN2.MAP
{371}{}{}
{372}{}{}
{373}{}{}
# MNTCRVN1.MAP
{374}{}{}
{375}{}{}
{376}{}{}
# MNTCRVN2.MAP
{377}{}{}
{378}{}{}
{379}{}{}
# VIPERS.MAP
{380}{}{}
{381}{}{}
{382}{}{}
# DESCRVN3.MAP
{383}{}{}
{384}{}{}
{385}{}{}
# MNTCRVN3.MAP
{386}{}{}
{387}{}{}
{388}{}{}
# DESCRVN4.MAP
{389}{}{}
{390}{}{}
{391}{}{}
# MNTCRVN4.MAP
{392}{}{}
{393}{}{}
{394}{}{}
# HUBMIS1.MAP
{395}{}{}
{396}{}{}
{397}{}{}

#
#	Short City names
#
{500}{}{Refugio 13}
{501}{}{Refugio 15}
{502}{}{Arenas Sombrías}
{503}{}{Ciudad Vertedero}
{504}{}{Piratas}
{505}{}{Necrópolis}
{506}{}{El Eje}
{507}{}{La Hermandad}
{508}{}{Base Militar}
{509}{}{El Ardor}
{510}{}{El Cementerio}
{511}{}{La Catedral}



#
# Error Messages
#
{1000}{}{Error: ¡No hay suficiente espacio para guardar el mapa!}