#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{¿Seguro que quieres salir?}
{1}{}{Versión Demo}
{2}{}{Se usará el personaje por defecto.}
{3}{}{Pantalla guardada.}
{4}{}{Partida Cargar Rápido cargada con éxito.}
{5}{}{Partida Guardar Rápido guardada con éxito.}
{6}{}{Sobrepasado límite de tiempo de la demo.}
{7}{}{¡PIPBoy no disponible durante el combate!}
{8}{}{Error al guardar pantalla.}
{9}{}{INTRODUCCIÓN}
{10}{}{NUEVA PARTIDA}
{11}{}{CARGAR PARTIDA}
{12}{}{OPCIONES}
{13}{}{CRÉDITOS}
{14}{}{SALIR}
{15}{}{Puntos de Acción}
{16}{}{Puntos de Salud}
{17}{}{El Sensor de Movimiento no está instalado.}
{18}{}{El Sensor de Movimiento no está cargado.}
#
# Game config text. Defined in gconfig.c
#
{100}{}{¡Error al guardar config de la partida!}
{101}{}{Configuraciones de la partida no guardadas.}
#
# Some radiation messages used in critter.c
#
{1000}{}{Sientes muchas nauseas.}
{1001}{}{Sientes muchas nauseas, después de vomitar un poco te sientes cansado.}
{1002}{}{Sientes gran cansancio, no paras de vomitar y tu recuperación es difícil.}
{1003}{}{Tienes una violenta hemorragia. Estás muy mal y se te está cayendo el pelo.}
{1004}{}{Tienes una violenta hemorragia. Tus vómitos están manchados de sangre. La piel se despega de tus huesos.}
{1005}{}{Te sangran los intestinos y tienes una fuerte diarrea. Te sientes hinchado y sufres gran agonía.}
{1006}{}{La radiación te han matado.}
{1007}{}{Has recibido una fuerte dosis de radiación.}
{1008}{}{El contador geiger hace "Clic".}
{1009}{}{El contador geiger hace "Clic" repetidas veces.}
#
# Message used in actions.c
#
{2000}{}{No puedes llegar ahí.}
{2001}{}{El cerrojo está atascado.}
#
# poison messages from critter.c
#
{3000}{}{¡Te han envenenado!}
{3001}{}{Sufres de envenenamiento.}
#
# from queue.c
#
{4000}{}{Por culpa de tu torpeza, el explosivo se acciona antes de tiempo.}
#
# from combatai.c
#
{5000}{}{usa}
{5001}{}{se ha quedado sin munición para}
{5002}{}{recarga su}
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{¿Preguntar sobre qué?}

