{100}{}{Cohete}
{200}{}{Bola de Plasma}
{300}{}{Explosión}
{400}{}{Sangre}
{500}{}{Hexágono no-trans}
{501}{}{}
{600}{}{Cuchillo}
{700}{}{Lanza}
{800}{}{Explosión IEM}
{900}{}{Fogonazo Láser}
{1000}{}{Fogonazo Plasma}
{1100}{}{Explosión}
{1200}{}{Cierre de Manuscrito}
{1300}{}{Interruptor Electricidad}
{1400}{}{Explosión}
{1500}{}{Explosión}
{1600}{}{Red de Salida}
{1700}{}{Red de Salida}
{1800}{}{Red de Salida}
{1900}{}{Red de Salida}
{2000}{}{Red de Salida}
{2100}{}{Red de Salida}
{2200}{}{Red de Salida}
{2300}{}{Red de Salida}
{2400}{}{Bengala}
{2500}{}{Granada}
{2600}{}{Roca}
{2700}{}{Explosión}
{2800}{}{Explosión}
{2900}{}{Explosión}
{3000}{}{Cóctel Molotov}
{3100}{}{Red de Salida}
{3200}{}{Red de Salida}
{3300}{}{Red de Salida}
{3400}{}{Red de Salida}
{3500}{}{Red de Salida}
{3600}{}{Red de Salida}
{3700}{}{Red de Salida}
{3800}{}{Red de Salida}
{3900}{}{Red de Salida}
{4000}{}{Red de Salida}
{4100}{}{Red de Salida}
{4200}{}{Red de Salida}
{4300}{}{Red de Salida}
{4400}{}{Red de Salida}
{4500}{}{Red de Salida}
{4600}{}{Red de Salida}

