{100}{}{Armadura de Cuero}
{101}{}{Tu indumentaria básica de cuero. Curtida a mano con pelo de brahmin.}
{200}{}{Armadura de Metal}
{201}{}{Láminas de metal ensambladas que conforman una coraza.}
{300}{}{Armadura de Energía}
{301}{}{Una armadura de autocontención de alta tecnología. Dotada de un reactor de microfusión con combustible suficiente para durar cien años.}
{400}{}{Cuchillo}
{401}{}{Un arma cortante de hoja afilada. FU Mín.: 2.}
{500}{}{Porra}
{501}{}{Una barra de uso militar o policial. De madera maciza. FU Mín.: 3.}
{600}{}{Almádena}
{601}{}{Un gran martillo con un mango enorme. Muy popular entre los musculosos. FU Mín.: 6.}
{700}{}{Lanza}
{701}{}{Un arma de hoja afilada. El mango es de madera y la hoja de acero forjado. FU Mín.: 4.}
{800}{}{Pistola de 10mm}
{801}{}{Una pistola de 10mm modelo Colt 6520 de carga automática. Cada vez que aprietes el gatillo, el arma se recargará automáticamente hasta que el cargador esté vacío. Cuando quieras efectuar un único disparo, utiliza esta potente arma. FU Mín.: 3.}
{900}{}{SFL de 10mm}
{901}{}{Subfusil H&K MP9 (variante de 10mm). Un SFL de tamaño medio, compatible con los modos de disparo simple y de ráfaga. FU Mín.: 4.}
{1000}{}{Rifle de Caza}
{1001}{}{Un rifle semiautomático Colt Rangemaster, de calibre .223. Sólo de un único disparo. FU Mín.: 5.}
{1100}{}{Lanzallamas}
{1101}{}{Un lanzallamas modelo Flambe 450, variante varmiter. Dispara un líquido inflamable y extremadamente caliente. Para funcionar correctamente necesita un combustible específico. FU Mín.: 6.}
{1200}{}{Ametralladora}
{1201}{}{Un fusil tipo Rockwell CZ53. Un fusil de cañón múltiple que dispara balas de 5mm a más de 60.000 RPM. FU Mín.: 7.}
{1300}{}{Lanzamisiles}
{1301}{}{Un lanzamisiles Rockwell BigBazooka. Dotado de un gatillo exclusivo de 3 lb. Dispara Misiles normales o PB. FU Mín.: 6.}
{1400}{}{Misil Explosivo}
{1401}{}{Un misil con gran cabeza explosiva.}
{1500}{}{Rifle de Plasma}
{1501}{}{Un rifle de plasma Winchester modelo P94. Un arma de energía de rango industrial que dispara plasma candente a través de un cañón superconductor. Reforzado con células de microfusión. FU Mín.: 6.}
{1600}{}{Pistola Láser}
{1601}{}{Una Pistola Láser Wattz 1000. Modelo civil, por lo que su potencia en vatios es menor que la de las versiones militar y policial. Utiliza pequeñas células de energía. FU Mín.: 3.}
{1700}{}{Armadura de Combate}
{1701}{}{Una coraza de alta tecnología fabricada con sofisticados polímeros defensivos.}
{1800}{}{Águila del Desierto .44}
{1801}{}{Una antigua pistola Águila del Desierto, Mágnum .44. Su presencia en las películas de finales del siglo XX hizo de esta pistola una de las más populares de todos los tiempos. FU Mín.: 4.}
{1900}{}{Piedra}
{1901}{}{Es una piedra. Un modelo de Granite-Inc. Es una versión actualizada. FU Mín.: 1.}
{2000}{}{Palanca}
{2001}{}{Una pieza de metal muy sólida y pesada, diseñada especialmente para hacer fuerza. O machacar cabezas. FU Mín.: 5.}
{2100}{}{Puño Americano}
{2101}{}{Puño reforzado hecho de acero. Protegen tu mano y provocan mucho daño en un combate desarmado. FU Mín.: 1.}
{2200}{}{Pistola de 14mm}
{2201}{}{Una pistola automática Sig-Sauer de 14mm. Grande, de disparo simple. Un excelente trabajo artesanal. FU Mín.: 4.}
{2300}{}{Rifle de Asalto}
{2301}{}{Un Rifle de Asalto de 5mm AK-112. Un antiguo modelo militar, en desuso desde la guerra. Puede efectuar disparos únicos o disparar ráfagas, utilizando las municiones de alta velocidad de 5mm. FU Mín.: 5.}
{2400}{}{Pistola de Plasma}
{2401}{}{Pistola de Plasma Glock 86. Diseñada por Gaston Glock AI. Dispara piezas de plasma incandescentes. Reforzada con una pequeña célula de energía. FU Mín.: 4.}
{2500}{}{Granada (Frag.)}
{2501}{}{Una granada de fragmentación estándar. Contiene una pequeña cantidad de explosivos y el depósito compone la mayor parte de los fragmentos letales. Explota por contacto. FU Mín.: 3.}
{2600}{}{Granada (Plasma)}
{2601}{}{Una unidad de lanzamiento sellada magnéticamente con explosivos de detonación. Provoca una explosión de plasma candente por contacto. FU Mín.: 4.}
{2700}{}{Granada (IEM)}
{2701}{}{Una granada de mano electromagnética que genera un intenso campo magnético al explotar. No afecta a las criaturas biológicas. Explosión por contacto. FU Mín.: 4.}
{2800}{}{Ametralladora Láser}
{2801}{}{Una Ametrallodra Láser H&K L30. Diseñado específicamente para uso militar, estaba en período de prueba al inicio de la guerra. Sus cañones múltiples permiten los disparos de largo alcance antes de que se caliente en exceso. Reforzado con células de microfusión. FU Mín.: 6.}
{2900}{}{BHC de 10mm}
{2901}{}{Munición. Calibre: 10mm, balas huecas con camisa.}
{3000}{}{PB de 10mm}
{3001}{}{Munición. Calibre: 10mm, perforación blindada.}
{3100}{}{BHC de Magnum .44}
{3101}{}{Munición. Calibre: Magnum .44, balas huecas con camisa.}
{3200}{}{Combustible: Lanzallamas}
{3201}{}{Cilindro que contiene un combustible líquido altamente inflamable para lanzallamas.}
{3300}{}{PB de 14mm}
{3301}{}{Munición de gran calibre: 14mm, perforación blindada.}
{3400}{}{CM .223}
{3401}{}{Munición. Calibre: .223, camisa de metal.}
{3500}{}{BHC de 5mm}
{3501}{}{Munición ligera, pequeña. Calibre: 5mm, balas huecas con camisa.}
{3600}{}{PB de 5mm}
{3601}{}{Munición ligera, pequeña. Calibre: 5mm, perforación blindada.}
{3700}{}{Misil PB}
{3701}{}{Un cohete con un explosivo menor pero diseñado para perforar superficies blindadas.}
{3800}{}{Célula de Energía}
{3801}{}{Una pequeña unidad de almacenamiento de energía de autocontención.}
{3900}{}{Célula MF}
{3901}{}{Una unidad de producción de energía de tamaño medio. Es una planta de microfusión de autocontención.}
{4000}{}{Estimulante}
{4001}{}{Un fármaco con poderes curativos. Cuando se inyecta, cura inmediatamente las heridas leves.}
{4100}{}{Chapas de Botella}
{4101}{}{Esta bolsa contiene tus chapas de botellas.}
{4200}{}{Nevera}
{4201}{}{Un refrigerador. Sin congelante.}
{4300}{}{Cajón de Hielo}
{4301}{}{Un cajón de hielo anticuado. Las bisagras aún están bien.}
{4400}{}{Cajón de Hielo}
{4401}{}{Un cajón de hielo anticuado. Las bisagras aún están bien.}
{4500}{}{Cuchillo Arrojadizo}
{4501}{}{Un cuchillo diseñado para ser lanzado. Hecho de titanio y forjado con láser. FU Mín.: 3.}
{4600}{}{Bolsa}
{4601}{}{Una bolsa de tamaño medio. Tejida con pelo de Brahmin.}
{4700}{}{Botiquín de 1º Auxilios}
{4701}{}{Un pequeño botiquín con el equipo médico básico. Vendajes, esparadrapo, líquido antiséptico y demás.}
{4800}{}{Radaway}
{4801}{}{Una solución química que absorbe las partículas radiactivas y las incorpora a tu sistema. Tarda tiempo en funcionar.}
{4900}{}{Antídoto}
{4901}{}{Una botella que contiene un antídoto contra el veneno de fabricación casera. Un líquido lechoso con trozos de carne de Escorpión Rad.}
{5000}{}{Objeto Reservado}
{5001}{}{Es un objeto reservado. NO LO USES.}
{5100}{}{Dinamita}
{5101}{}{Un potente explosivo compuesto de nitroglicerina mezclada con una sustancia absorbente llamada kiselguhr. Incluye un temporizador.}
{5200}{}{Contador Géiger}
{5201}{}{Un contador géiger de Wattz Electronics modelo C-Radz. Detecta la presencia e intensidad de los campos radiactivos.}
{5300}{}{Mentats}
{5301}{}{Una caja de pastillas que alteran la mente. Aumenta las funciones relacionadas con la memoria y acelera otros procesos mentales. Causa adicción.}
{5400}{}{Sigilante}
{5401}{}{Un dispositivo personal de RobCo, modelo Stealth Boy 3001. Genera un campo de modulación que transmite la luz reflejada de un lado de un objeto al otro.}
{5500}{}{Chip de agua}
{5501}{}{Un chip de sistema de control de purificación del agua. Se parece al chip que necesita tu Refugio.}
{5600}{}{Placas de Identificación}
{5601}{}{Un grupo de placas de identificación militar de soldado. Se puede leer el nombre de Darkwater, pero no mucho más.}
{5700}{}{Micrófono}
{5701}{}{Un micrófono en miniatura y un dispositivo de transmisión.}
{5800}{}{Cinta}
{5801}{}{Una cinta de holodisco de Wattz Electronics. Esta cinta parece estar en muy mal estado.}
{5900}{}{Sensor de Movimiento}
{5901}{}{Un sensor de movimiento de Wattz Electronics modelo C-U. Detecta el movimiento del material biológico en una distancia en metros utilizando un dispositivo de radar.}
{6000}{}{Estantería}
{6001}{}{Una estantería de madera.}
{6100}{}{Estantería}
{6101}{}{Una estantería de madera.}
{6200}{}{Estantería}
{6201}{}{Una estantería de madera.}
{6300}{}{Estantería}
{6301}{}{Una estantería de madera.}
{6400}{}{Estantería}
{6401}{}{Una estantería de madera.}
{6500}{}{Estantería}
{6501}{}{Una estantería de madera.}
{6600}{}{Mesa}
{6601}{}{Una mesa de madera.}
{6700}{}{Mesa}
{6701}{}{Una mesa de madera.}
{6800}{}{Ropero}
{6801}{}{Un ropero de madera.}
{6900}{}{Ropero}
{6901}{}{Un ropero de madera.}
{7000}{}{Ropero}
{7001}{}{Un ropero de madera.}
{7100}{}{Fruta}
{7101}{}{Una fruta extraña. Sin colorantes ni conservantes añadidos.}
{7200}{}{Maletín}
{7201}{}{Un maletín, con una etiqueta de Made-in-the-USA. De cuero. En buen estado, pero la combinación está rota.}
{7300}{}{Enciclopedia de la Ciencia}
{7301}{}{Una pila de libros que contienen información sobres la rama científica.}
{7400}{}{Chupa de Cuero}
{7401}{}{Una cazadora de cuero pesada y negra.}
{7500}{}{Herramienta}
{7501}{}{Una fantástica herramienta que sirve para numerosas utilidades.}
{7600}{}{Libro de Electrónica}
{7601}{}{Un manual de estudio sobre electrónica. Una nota en la tapa pone que está dirigido al "¡joven electricista que todos llevamos dentro!"}
{7700}{}{Ganzúas Electrónicas}
{7701}{}{Unas ganzúas electrónicas de micromanipulación de Wattz Electronics. Para los cerrojos electrónicos y otros dispositivos de seguridad.}
{7800}{}{Dibujo Borroso}
{7801}{}{Una imagen de un cantante. Muy vieja. La imagen tiene un revestimiento de fieltro que está en buen estado.}
{7900}{}{Bengala}
{7901}{}{Una bengala. Emite luz durante unos momentos. El papel está algo deteriorado, pero por lo demás está en buen estado. Tuerce la parte superior para encenderla.}
{8000}{}{Libro de 1º Auxilios}
{8001}{}{Un libro de estudio de los conceptos y usos de los primeros auxilios.}
{8100}{}{Pincho de Iguana}
{8101}{}{Una iguana asada en su propia piel.}
{8200}{}{Llave}
{8201}{}{Una llave. Una llave abrirá un cerrojo específico.}
{8300}{}{Juego de Llaves}
{8301}{}{Numerosas llaves.}
{8400}{}{Ganzúas}
{8401}{}{Una juego de ganzúas. Incluye todas las ganzúas y llaves de tensión para abrir cerrojos de clavija y de tambor convencionales.}
{8500}{}{Explosivo Plástico}
{8501}{}{Una mezcla de Córdex, un tipo de explosivo plástico de uso militar. Muy estable, y con gran poder de destrucción. Incluye un temporizador.}
{8600}{}{Manual de Explorador}
{8601}{}{Un libro sobre los métodos e ideales de la Exploración. Información muy práctica relativa a la vida en el exterior.}
{8700}{}{Esteroides}
{8701}{}{Esteroides muy avanzados. Aumentan la fuerza y los reflejos. Causan convulsiones intensas.}
{8800}{}{Reloj}
{8801}{}{Un reloj caro. No funciona, pero es muy bonito.}
{8900}{}{Motor}
{8901}{}{Un motor eléctrico de 40 caballos.}
{9000}{}{Mochila}
{9001}{}{Una mochila normal, con cinchas opcionales.}
{9100}{}{Maletín de Médico}
{9101}{}{Este maletín negro contiene los instrumentos y fármacos utilizados por los médicos en el desempeño de su trabajo.}
{9200}{}{Cola de Escorpión}
{9201}{}{Una mutilada cola de un Escorpión Rad.}
{9300}{}{Bolsa}
{9301}{}{Una bolsa de tamaño medio. Tejida con piel de brahmin.}
{9400}{}{Escopeta}
{9401}{}{Una escopeta de doble cañón del calibre 12 Winchester Widowmaker. De cañón corto, con empuñadura de caoba. FU Mín.: 4.}
{9500}{}{Cartucho de Escopeta}
{9501}{}{Munición de escopeta. Esta munición está marcada: "Cartuchos del Calibre 12, no recomendados a menores de 3 años."}
{9600}{}{Llave de Acceso Roja}
{9601}{}{Una llave de seguridad electrónica, con código de color rojo.}
{9700}{}{Llave de Acceso Azul}
{9701}{}{Una llave de seguridad electrónica, con código de color azul.}
{9800}{}{Chatarra}
{9801}{}{Un montón de piezas de chatarra. Un poco de todo.}
{9900}{}{Horquilla de Oro}
{9901}{}{Una valiosa horquilla de oro.}
{10000}{}{Radio}
{10001}{}{Una radio modelo 2043B, de los técnicos de Wattz Electronics. Fiable, dura, camuflada. Con interfaz opcional RS-121.}
{10100}{}{Mechero}
{10101}{}{Un mechero de plata, de butano, en buen estado.}
{10200}{}{Armas y Balas}
{10201}{}{Un periodicucho sobre armas. Una revista dedicada al uso práctico de las armas de fuego y alguna que otra revisión de las últimas tendencias.}
{10300}{}{Pincho de Iguana}
{10301}{}{Carne asada y verduras en un pincho de cocina.}
{10400}{}{Grabadora de Cintas}
{10401}{}{Una grabadora de cintas de Wattz Electronics modelo Tócala-Para-Mí. Reproduce y graba las cintas Graba-Una-Vez de alta densidad de 30 minutos.}
{10500}{}{Llave}
{10501}{}{Una llave especial.}
{10600}{}{Nuka-Cola}
{10601}{}{Una botella de Nuka-Cola, el refresco de la era postnuclear. Caliente y sin gas.}
{10700}{}{Huesos}
{10701}{}{Una colección de huesos extraños.}
{10800}{}{Huesos}
{10801}{}{Una colección de huesos extraños.}
{10900}{}{Rad-X}
{10901}{}{Fármacos anti-radiación para ingerir antes de la exposición. No se conocen efectos secundarios.}
{11000}{}{Psycho}
{11001}{}{Un sistema exclusivo lleno de sustancias químicas extrañas y desconocidas de probable origen militar. Se supone que aumenta el potencial de combate de un soldado.}
{11100}{}{CM de Magnum .44}
{11101}{}{Munición. Calibre: Magnum .44, camisa de metal.}
{11200}{}{Urna}
{11201}{}{Una bonita urna dorada, con el nombre "Harriet" inscrito en su parte delantera y que contiene cenizas.}
{11300}{}{Túnica}
{11301}{}{Una túnica de los Niños de la Catedral.}
{11400}{}{Mano Manipuladora}
{11401}{}{Un manipulador cibernético con la forma de una mano. Deteriorada debido a la naturaleza húmeda del proceso de eliminación.}
{11500}{}{Superalmádena}
{11501}{}{Un enorme martillo fabricado por los Niños de la Catedral, utilizando la tecnología láser más puntera. Incluye un dispositivo de almacenamiento de energía cinética que aumenta el impacto del golpe. FU Mín.: 5.}
{11600}{}{Destripador}
{11601}{}{Una vibronavaja de Destripador(tm). Reforzada con una pequeña célula de energía, su hoja destripa y desgarra el objetivo. FU Mín.: 4.}
{11700}{}{Flor}
{11701}{}{Una bonita flor.}
{11800}{}{Rifle Láser}
{11801}{}{Un rifle Láser Wattz 2000. Utiliza células de microfusión para la emisión de láser y un cañón aumentando para la obtención de mayor alcance. FU Mín.: 6.}
{11900}{}{Collar}
{11901}{}{Un collar de aspecto caro, hecho de plata, oro y diamantes engarzados.}
{12000}{}{Blaster Alienígena}
{12001}{}{Un arma extraña de clara procedencia alienígena. Parece contener pequeñas células de energía. FU Mín.: 2.}
{12100}{}{Balas 9mm}
{12101}{}{Una colección de antiguas balas de 9x19mm. Muy engrasadas para impedir su deterioro ambiental. Balas estándar.}
{12200}{}{Mauser de 9mm}
{12201}{}{Una pistola Mauser M/96, Parabellum 9x19mm. En excelente estado. Extremadamente preciso. FU Mín.: 3.}
{12300}{}{Nulificador Psíquico}
{12301}{}{Un dispositivo extraño construido utilizando vieja tecnología.}
{12400}{}{Cerveza}
{12401}{}{Una especie de cerveza de fermentación casera.}
{12500}{}{Alcohol}
{12501}{}{Una bebida antigua, de antes de la Guerra.}
{12600}{}{Petaca de Agua}
{12601}{}{Un contenedor para el almacenamiento y la conservación de agua u otros líquidos.}
{12700}{}{Cuerda}
{12701}{}{Una cuerda gruesa y fuerte. De unos 45 pies de longitud.}
{12800}{}{Taquilla}
{12801}{}{Tu taquilla habitual. Contiene cachivaches, se encuentra a los pies de la cama y puede cerrarse con candado.}
{12900}{}{Taquilla}
{12901}{}{Tu taquilla habitual. Contiene cachivaches, se encuentra a los pies de la cama y puede cerrarse con candado.}
{13000}{}{Taquilla}
{13001}{}{Tu taquilla habitual. Contiene cachivaches, se encuentra a los pies de la cama y puede cerrarse con candado.}
{13100}{}{Taquilla}
{13101}{}{Tu taquilla habitual. Contiene cachivaches, se encuentra a los pies de la cama y puede cerrarse con candado.}
{13200}{}{Taquilla}
{13201}{}{Un contenedor de almacenamiento.}
{13300}{}{Taquilla}
{13301}{}{Un contenedor de almacenamiento.}
{13400}{}{Taquilla}
{13401}{}{Un contenedor de almacenamiento.}
{13500}{}{Taquilla}
{13501}{}{Un contenedor de almacenamiento.}
{13600}{}{Taquilla}
{13601}{}{Un contenedor de almacenamiento.}
{13700}{}{Taquilla}
{13701}{}{Un contenedor de almacenamiento.}
{13800}{}{Taquilla}
{13801}{}{Un contenedor de almacenamiento.}
{13900}{}{Taquilla}
{13901}{}{Un contenedor de almacenamiento.}
{14000}{}{Tarjeta de Acceso}
{14001}{}{Una tarjeta de acceso de seguridad. Aún funciona.}
{14100}{}{Insignia de los NDC}
{14101}{}{Una insignia con el símbolo de los Niños de la Catedral. En un lateral puedes observar protuberancias que te recuerdan a las muescas de una llave.}
{14200}{}{Insignia de los NDC}
{14201}{}{Una insignia con el símbolo de los Niños de la Catedral. En un lateral puedes observar protuberancias que te recuerdan a las muescas de una llave.}
{14300}{}{Rifle de Francotirador}
{14301}{}{Un rifle de francotirador DKS-501. Excelente arma con gran alcance de tiro. Originariamente del calibre .308, éste arma usa el calibre .223, mucho más frecuente. FU Mín.: 5.}
{14400}{}{Superestimulante}
{14401}{}{Un fármaco con poder curativo. Muy potente. Los superestimulantes provocarán algo de daño tras un período de tiempo debido a la potente naturaleza de los fármacos utilizados.}
{14500}{}{Estantería}
{14501}{}{Una estantería de madera.}
{14600}{}{Estantería}
{14601}{}{Una estantería de madera.}
{14700}{}{Estantería}
{14701}{}{Una estantería de madera.}
{14800}{}{Estantería}
{14801}{}{Una estantería de madera.}
{14900}{}{Estantería}
{14901}{}{Una estantería de madera.}
{15000}{}{Estantería}
{15001}{}{Una estantería de madera.}
{15100}{}{Repisas}
{15101}{}{Un grupo de repisas de madera.}
{15200}{}{Repisas}
{15201}{}{Un grupo de repisas de madera.}
{15300}{}{Repisas}
{15301}{}{Un grupo de repisas de madera.}
{15400}{}{Repisas}
{15401}{}{Un grupo de repisas de madera.}
{15500}{}{Repisas}
{15501}{}{Un grupo de repisas de madera.}
{15600}{}{Repisas}
{15601}{}{Un grupo de repisas de madera.}
{15700}{}{Banco de Trabajo}
{15701}{}{Una mesa de trabajo. Sí, es un banco de trabajo estándar, viejo, desvencijado. Parece agradable sentarse ahí.}
{15800}{}{Tablón de Herramientas}
{15801}{}{Este tablón sostiene una variedad de herramientas sobre el tan popular banco de trabajo.}
{15900}{}{Cóctel Molotov}
{15901}{}{Una granada inflamable de fabricación casera. FU Mín.: 3.}
{16000}{}{Picana Eléctrica}
{16001}{}{Una picana eléctrica para granjeros modelo Mejor Amigo de la firma Wattz Electronics. Utiliza como alimentación pequeñas células de energía. FU Mín.: 4.}
{16100}{}{Rifle BB Red Ryder}
{16101}{}{Rifle BB Red Ryder (Jinete Rojo). Un clásico. FU Mín.: 3.}
{16200}{}{Rifle BB Red Ryder EL}
{16201}{}{Una Edición Limitada del Rifle BB Red Ryder (Jinete Rojo). Todo un clásico. FU Mín.: 3.}
{16300}{}{BB's}
{16301}{}{Un lote de BB's de antes de la guerra. En excelente estado. De acero inoxidable.}
{16400}{}{Cinta de la Hermandad}
{16401}{}{Un Holodisco con información sobre la Hermandad del Acero.}
{16500}{}{Chiringuito de Iguanas}
{16501}{}{La casa de las Delicias de Iguana de Bob. ¿Quién no se comería una iguana fresca a la parrilla?}
{16600}{}{Mesa}
{16601}{}{Una mesa normal. Para poner cachivaches.}
{16700}{}{Mesa}
{16701}{}{Una mesa normal. Para poner cachivaches.}
{16800}{}{Cachivaches}
{16801}{}{Objetos de todo tipo conocidos como "cachivaches".}
{16900}{}{Cachivaches}
{16901}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17000}{}{Cachivaches}
{17001}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17100}{}{Cachivaches}
{17101}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17200}{}{Cachivaches}
{17201}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17300}{}{Cachivaches}
{17301}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17400}{}{Cachivaches}
{17401}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17500}{}{Cachivaches}
{17501}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17600}{}{Cachivaches}
{17601}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17700}{}{Cachivaches}
{17701}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17800}{}{Cachivaches}
{17801}{}{Objetos de todo tipo conocidos como "cachivaches".}
{17900}{}{Cachivaches}
{17901}{}{Objetos de todo tipo conocidos como "cachivaches".}
{18000}{}{Cajón}
{18001}{}{Un cajón de madera lleno de cosas normales.}
{18100}{}{Mesa}
{18101}{}{Una mesa normal. Cuando has visto una mesa, las has visto todas.}
{18200}{}{Mesa}
{18201}{}{Una mesa normal.}
{18300}{}{Mesa}
{18301}{}{Una mesa normal.}
{18400}{}{Mesa}
{18401}{}{Una mesa normal.}
{18500}{}{Mesa}
{18501}{}{Una mesa normal.}
{18600}{}{Mesa}
{18601}{}{Una mesa normal.}
{18700}{}{Mesa}
{18701}{}{Una mesa normal.}
{18800}{}{Taquilla}
{18801}{}{Una taquilla.}
{18900}{}{Taquilla}
{18901}{}{Una taquilla.}
{19000}{}{Experimento VEF (Holocinta)}
{19001}{}{Una holocinta que contiene información médica. Puede utilizarse para copiar datos en tu PIPBoy.}
{19100}{}{Disco de Seguridad}
{19101}{}{Una holocinta con una etiqueta que pone "Identificador de Seguridad". Puedes usarla para copiar esos datos en tu PIPBoy.}
{19200}{}{Experimento Alfa (Holocinta)}
{19201}{}{La etiqueta de esta holocinta pone: "Identificador de Experimento Alfa"}
{19300}{}{Experimento Delta (Holocinta)}
{19301}{}{La etiqueta de esta holocinta pone: "Identificador de Experimento Delta"}
{19400}{}{Experimento de Vree (Holocinta)}
{19401}{}{Esta Holocinta contiene evidencias médicas de Vree, de la Hermandad del Acero. Puede utilizarse para copiar datos en tu PIPBoy.}
{19500}{}{El Código del Honor (Holocinta)}
{19501}{}{Una Holocinta con un símbolo de la Hermandad del Acero. Usa la cinta para copiar datos en tu PIPBoy.}
{19600}{}{Transmisiones Mutantes}
{19601}{}{Parece que esta cinta se utilizaba para grabar datos de sonido de una radio. Úsala para copiar información en tu PIPBoy.}
{19700}{}{Caja}
{19800}{}{Caja}
{19900}{}{Caja}
{20000}{}{Caja}
{20100}{}{Caja}
{20200}{}{Caja}
{20300}{}{Caja}
{20400}{}{Caja}
{20500}{}{Bengala}
{20501}{}{Una Bengala. Proporciona luz durante un corto espacio de tiempo. El papel está algo desgastado, pero por lo demás está en perfecto estado. Está encendida.}
{20600}{}{Dinamita}
{20601}{}{Un potente explosivo compuesto de nitroglicerina y una absorbente sustancia llamada kiselguhr. Incorpora un temporizador, que está en funcionamiento.}
{20700}{}{Contador Géiger}
{20701}{}{Un contador géiger modelo C-Radz de Wattz Electronics. Detecta la presencia y la intensidad de los campos radiactivos. Está activado.}
{20800}{}{Sensor de Movilidad}
{20801}{}{Un sensor de movilidad modelo C-U de Wattz Electronics. Detecta el movimiento de cualquier material biológico en una distancia en metros usando un dispositivo graduado de radar. Está activado.}
{20900}{}{Explosivos Plásticos}
{20901}{}{Un trozo de Cordex, un tipo de explosivo plástico de uso militar. Muy estable y altamente destructivo. Incorpora un reloj, que está en funcionamiento.}
{21000}{}{Stealth Boy}
{21001}{}{Un dispositivo de transmisión personal de la firma RobCo, modelo Stealth Boy 3001. Genera un campo de modulación que transmite la luz reflejada de un lado del objeto al otro.}
{21100}{}{Huesos}
{21101}{}{Estás viendo a Ed. Ed está muerto.}
{21200}{}{Tandi}
{21201}{}{Estás negociando la liberación de Tandi.}
{21300}{}{Restos de Gizmo}
{21301}{}{Gizmo, el antiguo capo de Ciudad Vertedero, está muerto. Y además apesta.}
{21400}{}{Mesa}
{21401}{}{Una mesa. Tras un riguroso análisis, concluyes que es una mesa.}
{21500}{}{Historia de la Hermandad}
{21501}{}{Una Holocinta que contiene información relativa a la Hermandad del Acero. Puede utilizarse para introducir información en tu PIPBoy 2000.}
{21600}{}{Historia de Maxson}
{21700}{}{Periódico de Maxson}
{21800}{}{Curación Leve}
{21801}{}{Negocia esta opción si deseas una curación leve.}
{21900}{}{Curación Media}
{21901}{}{Negocia esta opción si deseas una curación media.}
{22000}{}{Curación Fuerte}
{22001}{}{Negocia esta opción si deseas una curación fuerte y duradera.}
{22100}{}{Tarjeta de Seguridad}
{22101}{}{Una tarjeta maestra con un código de seguridad insertado en su sistema.}
{22200}{}{Conmutador de Campo}
{22201}{}{Un dispositivo de transmisión electrónica con una palanca de activación muy sencilla y grande. Parece de fabricación reciente y diseñada para alguien con grandes manos.}
{22300}{}{Llave de Acceso Amarilla}
{22301}{}{Una llave de seguridad electrónica con código de color amarillo.}
{22400}{}{Pequeña Estatuilla}
{22401}{}{Crees que se trata de una imagen del "PIPBoy", pero no estás seguro.}
{22500}{}{No Tienes Ni Idea}
{22501}{}{Tras un análisis más detallado, sigues sin tener ni idea de lo que se trata.}
{22600}{}{Paquete de Fideos}
{22601}{}{No sabes lo que significa "Instant Spaghetti".}
{22700}{}{Cajita Oxidada o algo así}
{22701}{}{Una comida de televisión. No lo sabes, pero está claro que no es comestible. Y te preguntas si algún día lo fue.}
{22800}{}{Manual Técnico}
{22801}{}{Un manual de reparación de la Armadura de Energía T-51b.}
{22900}{}{Pieza de Maquinaria}
{22901}{}{Estás viendo un Motivador Sistólico. Esta extraña pieza de maquinaria es muy pequeña.}
{23000}{}{Grabaciones del Refugio}
{23001}{}{Un compendio de acontecimientos y otras grabaciones importantes de un sistema informático del Refugio. Puede estar dañado.}
{23100}{}{Clave de Seguridad (BM)}
{23101}{}{ }
{23200}{}{Armadura de Energía (R)}
{23201}{}{Una Armadura de Energía T-51b reforzada. El proceso de refuerzo ha aumentado la capacidad defensiva de esta sofisticada armadura.}
{23300}{}{Rifle Turbo de Plasma}
{23301}{}{Un rifle de plasma Winchester P94 modificado. La cámara de almacenamiento de plasma ha sido fundida a fuego vivo para acelerar el proceso de formación de las piezas de plasma. FU Mín.: 6.}
{23400}{}{Puño con Pinchos}
{23401}{}{Una versión mejorada del clásico puño americano. El puño con pinchos hace más daño al desgarrar la carne de tu oponente en un combate sin armas. FU Mín.: 1.}
{23500}{}{Puño de Energía}
{23501}{}{Un Puño de Energía "Enorme Amenaza" de la firma BeatCo. Muchos lo consideran el arma más sofisticada del combate sin armas. Otros se limitan a temblar. Está reforzado con pequeñas células de energía. FU Mín.: 1.}
{23600}{}{Cuchillo de Combate}
{23601}{}{Un cuchillo de combate de alta calidad, la empuñadura es de SharpWit, Inc. ¡La hoja de este cuchillo tiene una garantía de más de diez años! FU Mín.: 2.}
{23700}{}{Anales de Química}
{23701}{}{Una variada selección de literatura del campo de la Química. Los artículos sobre Química Molecular son especialmente interesantes.}
{23800}{}{Transmisión de Regulador}
{23801}{}{Una holocinta que graba una transmisión de audio.}
{23900}{}{Armad. de la Hermandad}
{23901}{}{Una versión superior de la Armadura de Combate. La Hermandad del Acero ha efectuado mejoras sobre la versión estándar.}
{24000}{}{Armadura Tesla}
{24001}{}{Esta brillante armadura proporciona una protección inigualable frente a los ataques de energía. Los tres vástagos de bobina de tracción repelen muchos de los ataques de energía recibidos.}
{24100}{}{Pistola .223}
{24101}{}{Una pistola .223 modificada y recortada. Se trata de un arma única en su especie, hecha con amor y destreza. FU Mín.: 5.}
{24200}{}{Escopeta de Combate}
{24201}{}{Una escopeta de combate Winchester City-Killer del calibre 12, de la variante bullpup. En excelente estado, está dotada del modificador ambiental de Batalla en el Desierto para una mayor precisión. FU Mín.: 5.}
