{100}{}{Habitante del Refugio}
{101}{}{}
{200}{}{Ciudadano}
{201}{}{Macho humano vestido con una armadura de cuero.}
{300}{}{Ciudadano}
{301}{}{Macho humano vestido con una armadura pesada de acero.}
{400}{}{Mendigo}
{401}{}{Un patético mendigo.}
{500}{}{Campesino}
{501}{}{}
{600}{}{Habitante del Refugio}
{601}{}{}
{700}{}{Armadura de Energía}
{800}{}{Supervisor del Refugio}
{900}{}{Supermutante}
{901}{}{}
{1000}{}{Gran Rata Topo}
{1001}{}{}
{1100}{}{Escorpión Rad}
{1101}{}{Escorpión Rad}
{1200}{}{Persona con Túnica}
{1300}{}{Mercader}
{1301}{}{}
{1400}{}{Guardia Zombi}
{1401}{}{}
{1500}{}{Armadura de Combate Hembra}
{1600}{}{Resplandeciente}
{1601}{}{}
{1700}{}{Hombre de la Chupa de Cuero}
{1800}{}{Campesino}
{1900}{}{Mujer de la Chupa de Cuero}
{2000}{}{Campesino}
{2100}{}{Armadura de Combate Macho}
{2200}{}{Ciudadana}
{2201}{}{Hembra humana vestida con una atractiva Armadura de acero.}
{2300}{}{Teniente Supermutante}
{2301}{}{}
{2400}{}{Ciudadana}
{2401}{}{Hembra humana vestida con una Armadura de cuero protectora.}
{2500}{}{Nocturno}
{2501}{}{}
{2600}{}{Habitante del Refugio}
{2601}{}{}
{2700}{}{Guardia Macho}
{2800}{}{Brahmin}
{2801}{}{Una vaca mutante con dos cabezas.}
{2900}{}{Campesino}
{3000}{}{Campesino}
{3100}{}{Hombre con Armadura de Cuero}
{3200}{}{Campesino}
{3201}{}{}
{3300}{}{Urbanita}
{3301}{}{}
{3400}{}{Habitante de Refugio}
{3500}{}{Habitante de Refugio}
{3501}{}{}
{3600}{}{Perro}
{3601}{}{Un canino, probablemente una mezcla de razas.}
{3700}{}{Mujer}
{3800}{}{Hombre}
{3900}{}{Campesino}
{3901}{}{}
{4000}{}{Campesino}
{4001}{}{}
{4100}{}{Persona con Armadura de Energía}
{4200}{}{Niño}
{4201}{}{}
{4300}{}{Centauro Inferior}
{4301}{}{}
{4400}{}{Manitas}
{4500}{}{Nómada}
{4501}{}{}
{4600}{}{Escriba}
{4700}{}{Supervisor}
{4800}{}{Rata de Cueva}
{4801}{}{}
{4900}{}{Gizmo}
{5000}{}{Maestro}
{5100}{}{Garra Mortal}
{5101}{}{}
{5200}{}{Técnico}
{5201}{}{}
{5300}{}{Técnico}
{5301}{}{}
{5400}{}{Técnico}
{5401}{}{}
{5500}{}{Guardia}
{5501}{}{}
{5600}{}{Guardia}
{5601}{}{}
{5700}{}{Guardia}
{5800}{}{Técnico}
{5801}{}{}
{5900}{}{Urbanita}
{5901}{}{}
{6000}{}{Vago}
{6001}{}{}
{6100}{}{Trabajador}
{6101}{}{}
{6200}{}{Estudiante de la Catedral}
{6201}{}{}
{6300}{}{Tandi}
{6400}{}{Aradesh}
{6500}{}{Seth}
{6600}{}{Mercader}
{6601}{}{}
{6700}{}{Guardia}
{6701}{}{}
{6800}{}{Mantis}
{6801}{}{}
{6900}{}{Robomente}
{7000}{}{Guardia Pirata}
{7100}{}{Urbanita}
{7101}{}{}
{7200}{}{Urbanita}
{7201}{}{}
{7300}{}{Consejero de Garl}
{7400}{}{Urbanita}
{7401}{}{}
{7500}{}{Pirata}
{7600}{}{Ian}
{7700}{}{Ojo Flotante}
{7800}{}{Rata Cerdo}
{7801}{}{}
{7900}{}{Killian Darkwater}
{8000}{}{Lars}
{8100}{}{Izo}
{8200}{}{Viajero}
{8201}{}{}
{8300}{}{Urbanita}
{8301}{}{}
{8400}{}{Urbanita}
{8401}{}{}
{8500}{}{Viajero}
{8501}{}{}
{8600}{}{Campesino}
{8601}{}{}
{8700}{}{Urbanita}
{8701}{}{}
{8800}{}{Mercader}
{8801}{}{}
{8900}{}{Extraño}
{8901}{}{}
{9000}{}{Guardia}
{9001}{}{}
{9100}{}{Granjero}
{9101}{}{}
{9200}{}{Mercader}
{9201}{}{}
{9300}{}{Campesino}
{9301}{}{}
{9400}{}{Neal}
{9500}{}{Campesino}
{9501}{}{}
{9600}{}{Trabajador}
{9601}{}{}
{9700}{}{Mercader}
{9800}{}{Campesino}
{9801}{}{}
{9900}{}{Gorila}
{9901}{}{}
{10000}{}{Extraño}
{10001}{}{}
{10100}{}{Niño de la Catedral}
{10200}{}{Vinnie}
{10201}{}{}
{10300}{}{Viajero}
{10301}{}{}
{10400}{}{Set}
{10500}{}{Garret}
{10600}{}{Necrófago}
{10601}{}{}
{10700}{}{Guardia Nocturno}
{10701}{}{}
{10800}{}{Supermutante Rudo}
{10801}{}{}
{10900}{}{Guardia Necrófago}
{10901}{}{}
{11000}{}{Miembro de la Resistencia}
{11001}{}{}
{11100}{}{Dan}
{11200}{}{Sheriff Greene}
{11300}{}{Suplente Fry}
{11400}{}{Kane}
{11500}{}{Demetre}
{11600}{}{Keri}
{11700}{}{Rutger}
{11800}{}{Daren Hightower}
{11900}{}{Martha}
{12000}{}{Lorenzo}
{12100}{}{Jacob}
{12200}{}{Albóndiga}
{12300}{}{Jasmine}
{12400}{}{Troy}
{12500}{}{Darrell}
{12600}{}{Talus}
{12700}{}{Thomas}
{12800}{}{Mathia}
{12900}{}{Cuchilla}
{13000}{}{Tangler}
{13100}{}{Talius}
{13200}{}{Gabriel}
{13300}{}{Avellone}
{13400}{}{Van Hagan}
{13500}{}{Surf}
{13600}{}{Fustigador}
{13700}{}{Barracus}
{13800}{}{Jeremiah}
{13900}{}{Médico Supermutante}
{14000}{}{Gideon}
{14001}{}{Sus manos brillan con una extraña energía.}
{14100}{}{Dominic}
{14101}{}{Sus ojos desprenden una extraña energía.}
{14200}{}{Lucy}
{14201}{}{Su cabeza desprende una extraña energía.}
{14300}{}{Escalofrío}
{14301}{}{Su cuerpo desprende pequeñas ráfagas de energía.}
{14400}{}{Viscoso}
{14500}{}{Teniente Supermutante}
{14600}{}{Laura}
{14700}{}{Morfeo}
{14800}{}{Nicole}
{14900}{}{Vree}
{15000}{}{Maxson}
{15100}{}{Rhombus}
{15200}{}{Cabbot}
{15300}{}{Decker}
{15400}{}{Butch}
{15500}{}{Loxley}
{15600}{}{Jain}
{15700}{}{Harold}
{15800}{}{Harry}
{15900}{}{Rata Ruda}
{15901}{}{}
{16000}{}{Rata Contaminada}
{16001}{}{}
{16100}{}{Rata Ruda Contaminada}
{16101}{}{}
{16200}{}{Rata Topo Inferior}
{16201}{}{}
{16300}{}{Coyote}
{16301}{}{}
{16400}{}{Gran Brahmin}
{16401}{}{}
{16500}{}{Secuaz de Garra Mortal}
{16501}{}{}
{16600}{}{Escorpión Rad Repugnante}
{16601}{}{}
{16700}{}{Nómada Sangriento}
{16701}{}{}
{16800}{}{Centauro Mayor}
{16801}{}{}
{16900}{}{Campesino Humilde}
{16901}{}{}
{17000}{}{Campesino}
{17001}{}{}
{17100}{}{Granjero}
{17101}{}{}
{17200}{}{Trabajador}
{17201}{}{}
{17300}{}{Granjero}
{17301}{}{}
{17400}{}{Mercader}
{17401}{}{}
{17500}{}{Guardia}
{17501}{}{}
{17600}{}{Gran Mantis}
{17601}{}{}
{17700}{}{Rata Cerdo Media}
{17701}{}{}
{17800}{}{Granjero}
{17801}{}{}
{17900}{}{Trabajador}
{17901}{}{}
{18000}{}{Mercader}
{18001}{}{}
{18100}{}{Guardia}
{18101}{}{}
{18200}{}{Del Ardor}
{18201}{}{}
{18300}{}{Resplandeciente Loco}
{18301}{}{}
{18400}{}{Zombi}
{18401}{}{}
{18500}{}{Guardia}
{18501}{}{}
{18600}{}{Guardia Supermutante}
{18601}{}{}
{18700}{}{Supermutante Medio}
{18701}{}{}
{18800}{}{Supermutante Loco}
{18900}{}{Supermutante Mortal}
{19000}{}{Nocturno Duro}
{19001}{}{}
{19100}{}{Nocturno Mortal}
{19101}{}{}
{19200}{}{Nocturno Superior}
{19300}{}{Nocturno Maestro}
{19301}{}{}
{19400}{}{Guardia}
{19401}{}{}
{19500}{}{Mercader}
{19501}{}{}
{19600}{}{Guardia}
{19601}{}{}
{19700}{}{Guardia}
{19701}{}{}
{19800}{}{Guardia}
{19801}{}{}
{19900}{}{Niña}
{19901}{}{}
{20000}{}{Escriba}
{20100}{}{Guardia}
{20101}{}{}
{20200}{}{Extraño}
{20201}{}{}
{20300}{}{Gorila}
{20301}{}{}
{20400}{}{Mercenario}
{20401}{}{}
{20500}{}{Guardia}
{20501}{}{}
{20600}{}{Habitante del Refugio}
{20700}{}{Garl}
{20800}{}{Doc Mórbid}
{20900}{}{Gretch}
{21000}{}{Tycho}
{21100}{}{Jonathan}
{21200}{}{Jacob}
{21300}{}{Mary}
{21400}{}{Rachael}
{21500}{}{Caleb}
{21600}{}{Viajero}
{21700}{}{Extraño}
{21800}{}{Gorila}
{21900}{}{Mercenario}
{22000}{}{Guardia}
{22100}{}{Urbanita}
{22200}{}{Extraño}
{22300}{}{Gorila}
{22400}{}{Mercenario}
{22500}{}{Guardia}
{22600}{}{Urbanita}
{22700}{}{Viajero}
{22800}{}{Extraño}
{22900}{}{Gorila}
{23000}{}{Mercenario}
{23100}{}{Guardia}
{23200}{}{Urbanita}
{23300}{}{Viajero}
{23400}{}{Mercenario}
{23500}{}{Guardia}
{23600}{}{Viajero}
{23700}{}{Extraño}
{23800}{}{Gorila}
{23900}{}{Mercenario}
{24000}{}{Guardia}
{24100}{}{Gorila}
{24200}{}{Mercenario}
{24300}{}{Guardia}
{24400}{}{Viajero}
{24500}{}{Extraño}
{24600}{}{Gorila}
{24700}{}{Mercenario}
{24800}{}{Guardia}
{24900}{}{Viajero}
{25000}{}{Extraño}
{25100}{}{Gorila}
{25200}{}{Mercenario}
{25300}{}{Guardia}
{25400}{}{Viajero}
{25500}{}{Extraño}
{25600}{}{Gorila}
{25700}{}{Mercenario}
{25800}{}{Guardia}
{25900}{}{Viajero}
{26000}{}{Extraño}
{26100}{}{Gorila}
{26200}{}{Mercenario}
{26300}{}{Guardia}
{26400}{}{Caballero Iniciado}
{26500}{}{Caballero Iniciado Superior}
{26600}{}{Caballero Aprendiz}
{26700}{}{Caballero Viajante}
{26800}{}{Caballero Superior}
{26900}{}{Caballero Iniciado}
{27000}{}{Caballero Iniciado Superior}
{27100}{}{Caballero Aprendiz}
{27200}{}{Caballero Viajante}
{27300}{}{Caballero Superior}
{27400}{}{Paladín Inferior}
{27500}{}{Paladín}
{27600}{}{Paladín Superior}
{27700}{}{Paladín Inferior}
{27800}{}{Paladín}
{27900}{}{Paladín Superior}
{28000}{}{Escriba Iniciado}
{28100}{}{Escriba Iniciado Superior}
{28200}{}{Escriba Aprendiz}
{28300}{}{Escriba Viajante}
{28400}{}{Escriba Superior}
{28500}{}{Escriba Iniciado}
{28600}{}{Escriba Iniciado Superior}
{28700}{}{Escriba Aprendiz}
{28800}{}{Escriba Viajante}
{28900}{}{Escriba Superior}
{29000}{}{Hombre con Túnica}
{29100}{}{Niño del Maestro}
{29200}{}{Estudiante de la Catedral}
{29300}{}{Mujer con Túnica}
{29400}{}{Niño del Maestro}
{29500}{}{Mascota del Maestro}
{29600}{}{Gorila del Maestro}
{29700}{}{Guardia del Maestro}
{29800}{}{Mascota del Maestro}
{29900}{}{Gorila del Maestro}
{30000}{}{Guardia del Maestro}
{30100}{}{Doctor}
{30200}{}{Katja}
{30300}{}{Sasha}
{30301}{}{Estás viendo a una perra Husky esperando pacientemente a su dueño.}
{30400}{}{Extraño Misterioso}
{30500}{}{Necrófago Descerebrado}
{30600}{}{Observador, Mk II}
{30700}{}{Huevo}
{30701}{}{Huevo de Garra Mortal}
{30800}{}{Dugan}
{30900}{}{Madre Garra Mortal}
{31000}{}{Martillo}
{31100}{}{Viajero Muerto}
{31200}{}{Kenji}

