#
# Messages for Prototypes
#
# strings
#
{10}{}{<Nada>}

#
# Material Types
#
{100}{}{Cristal}
{101}{}{Metal}
{102}{}{Plástico}
{103}{}{Madera}
{104}{}{Porquería}
{105}{}{Piedra}
{106}{}{Cemento}
{107}{}{Cuero}

#
# Item Types
#
{150}{}{Armadura}
{151}{}{Contenedor}
{152}{}{Droga}
{153}{}{Arma}
{154}{}{Munición}
{155}{}{Objetos Variados}
{156}{}{Llave}

#
# Scenery Types
#
{200}{}{Portal}
{201}{}{Escaleras}
{202}{}{Ascensor}
{203}{}{Base de Escalera}
{204}{}{Final de Escalera}
{205}{}{Escenario Genérico}

#
# Damage Code Types
#
{250}{}{normal_dam}
{251}{}{laser}
{252}{}{fire}
{253}{}{plasma}
{254}{}{electrical}
{255}{}{emp}
{256}{}{explosion}

#
# Caliber Types for weapons
#
{300}{}{Ninguno}
{301}{}{Cohete}
{302}{}{Combustible de Lanzallamas}
{303}{}{Célula de Energía C}
{304}{}{Célula de Energía D}
{305}{}{.223}
{306}{}{5mm}
{307}{}{Calibre .40}
{308}{}{10mm}
{309}{}{Calibre .44}
{310}{}{14mm}
{311}{}{Calibre 12}
{312}{}{9mm}
{313}{}{BB}

#
# Race Types
#
{350}{}{Caucasiano}
{351}{}{Africano}

#
# Body Types
#
{400}{}{Bípedo}
{401}{}{Cuadrúpedo}
{402}{}{Robótico}
#
# Kill Types names
#
{450}{}{Hombres}
{451}{}{Mujeres}
{452}{}{Niños}
{453}{}{Supermutantes}
{454}{}{Necrófagos}
{455}{}{Brahmins}
{456}{}{Escorpiones Rad}
{457}{}{Ratas}
{458}{}{Nómadas}
{459}{}{Centauros}
{460}{}{Robots}
{461}{}{Perros}
{462}{}{Mantis}
{463}{}{Garras Mortales}
{464}{}{Maestro}       # Not displayed!
#
# Kill type info descriptions
#
{465}{}{Esta línea muestra el número de humanos de sexo masculino que has matado en el transcurso de tus aventuras.}
{466}{}{Esta línea muestra el número de humanos de sexo femenino que has matado en el transcurso de tus aventuras.}
{467}{}{Esta línea muestra el número de niños humanos que has matado en el transcurso de tus aventuras. Canalla.}
{468}{}{Número de Supermutantes que has liquidado en el transcurso de tus aventuras.}
{469}{}{Esta línea muestra el número de Necrófagos de ambos sexos que has matado en el transcurso de tus aventuras.}
{470}{}{Esta línea muestra el número de Brahmins (vacas mutantes) que has liquidado en tus viajes.}
{471}{}{Número de Escorpiones Rad mutantes que has matado durante tu aventura.}
{472}{}{Número de ratas que has matado. Incluye a todos los miembros de la familia de las ratas.}
{473}{}{Este es el número de Nómadas mutantes que has matado.}
{474}{}{Tu lista de bajas de Centauros mutantes.}
{475}{}{Este es el número de robots que has destruido o desarmado.}
{476}{}{El número total de perros que has mandado a la gran perrera del cielo.}
{477}{}{Esta línea muestra el número total del Mantis muertas, o de grandes insectos mutantes parecidas a las mantis, que has aniquilado.}
{478}{}{Esta línea muestra que has liquidado a la Garra Mortal o a cualquiera de sus seguidores.}
{479}{}{No se muestra. ¡Error!}

#
# Use text
#
{480}{}{Ves: %s.}

#
# Use Container text
#
{485}{}{Examinas: %s.}
{486}{}{Cierras: %s.}
{487}{}{Está cerrada.} # new

#
# Look text
#
{490}{}{Ves: %s.}
{491}{}{Ves un cadáver: %s.}
{492}{}{Ves los restos de: %s.}
{493}{}{No ves nada fuera de lo común.}

#
# Examine text
#
{500}{}{no tener pulso }
{501}{}{estar a punto de morir }
{502}{}{tener heridas graves }
{503}{}{tener heridas }
{504}{}{gozar de buena salud }

#
# Examine text messages
#
{518}{}{Pareces %s }
{519}{}{%s %s }
{520}{}{Pareces %s.}
{521}{}{%s %s.}
{522}{}{Parece %s}
{523}{}{Parece %s}
{524}{}{Parece %s}
# (note: hps are short for hit-points)
{525}{}{%s tiene %d/%d PS.}
# (note: this is for guns that have ammo)
{526}{}{Tiene %d/%d disparos de %s.}
{530}{}{y tiene las extremidades dañadas.}  # These append to lines 500-504
{531}{}{pero tiene las extremidades dañadas.}
{532}{}{y tiene las extremidades dañadas.}
{533}{}{pero tiene las extremidades dañadas.}
# (note: hps are short for hit-points)
{535}{}{Tiene %d/%d PS}
{536}{}{Tiene %d/%d PS}
{537}{}{Tiene %d/%d PS}
{540}{}{Pesa %d libras.}
{541}{}{Pesa %d libra.}
{544}{}{, }
{545}{}{.}
{546}{}{ y está empuñando un %s.}
{547}{}{ y está empuñando un %s con %d/%d disparos de %s.}

#
# Examine text error messages
#
{550}{}{\nError: ¡lookup_val fuera de alcance!}
{551}{}{\nError: obj_examine: ¡proto_ptr ha fallado!}

#
# Use text messages
#
{580}{}{Usas el %s.}
{581}{}{Usas el %s sobre %s.}
{582}{}{Eso no sirve para nada.}
{583}{}{Para tu consternación descubres que ya está muerto.}
{584}{}{Cuando llegas, descubres que ya está muerto.}
{585}{}{Lástima, llegas demasiado tarde.} # This is relating to a critter being dead.
{586}{}{Eso no funciona con los muertos.}
{587}{}{Enciendes la bengala.}
{588}{}{La bengala ya está encendida.}
{589}{}{Pones en hora el reloj.}
{590}{}{¡El reloj ya está en funcionamiento!}

#
# Experience-Point messages
#
{620}{}{Ganas %d puntos de experiencia por matar: %s.}
{621}{}{%s ganas %d puntos de experiencia.}
{622}{}{Por vencer a tus enemigos, }  # 622-626 prepend to line 621
{623}{}{Por acabar con tus oponentes, }
{624}{}{Vences en el combate, }
{625}{}{Por acabar con tus enemigos, }
{626}{}{Por destruir a tus enemigos sin recibir ni un rasguño, }

#
# Dialog messages
#
{650}{}{[Hecho]}
{651}{}{[Más]}
{652}{}{Más}
{653}{}{[Atrás]}
{654}{}{Atrás}     # changed number from 653
{655}{}{Continuar}    # new
{656}{}{Err...}   # new
{660}{}{Allí no puedes ver.}
{661}{}{Demasiado lejos.}

#
# Not Enough AP message
#
{700}{}{No tienes puntos de acción suficientes.}
#
# Book messages
#
{800}{}{Lees el libro.}
{801}{}{No aprendes nada nuevo.}
{802}{}{Aprendes nueva información científica.}
{803}{}{Aprendes mucho sobre reparación de aparatos electrónicos.}
{804}{}{Aprendes nuevas técnicas de curación de heridas.}
{805}{}{Aprendes cómo manejar mejor tus armas.}
{806}{}{Aprendes mucho sobre supervivencia salvaje.}
#
# Use on messages (and some extra stuff that Jesse needed)
#
{900}{}{Los suministros del maletín médico se han agotado.}
{901}{}{Los suministros del botiquín de primeros auxilios se han agotado.}
{902}{}{No puedes hacer eso en combate.}
{903}{}{Esa persona no hará trueques contigo.}
{904}{}{Esa persona no tiene nada que decirte.}
{905}{}{No puedes levantar ese objeto. Estás en tu máxima capacidad de peso.}

# Kill Types names
#
{1450}{}{Hombres}
{1451}{}{Mujeres}
{1452}{}{Niños}
{1453}{}{Supermutantes}
{1454}{}{Necrófagos}
{1455}{}{Brahmines}
{1456}{}{Escorpiones}
{1457}{}{Ratas}
{1458}{}{Nómadas}
{1459}{}{Centauros}
{1460}{}{Robots}
{1461}{}{Perros}
{1462}{}{Mantis}
{1463}{}{Garras mortales}
{1464}{}{Plantas}
{1465}{}{Geckos}
{1466}{}{Aliens}
{1467}{}{Hormigas gigantes}
{1468}{}{Jefes Finales}
#
# Kill type info descriptions
#
{1469}{}{Esta línea muestra el número de hombres a las que has matado durante el curso de tus aventuras.}
{1470}{}{Esta línea muestra el número de mujeres a las que has matado durante el curso de tus aventuras.}
{1471}{}{El número de niños a los que has matado durante el curso de tus aventuras. Monstruo.}
{1472}{}{El número de supermutantes a los que has asesinado durante el curso de tus aventuras.}
{1473}{}{El número de necrófagos machos y hembras que has matado durante el curso de tus aventuras.}
{1474}{}{El número de brahmines que has descuartizado durante tus viajes.}
{1475}{}{El número de escorpiones mutantes a los que has dado muerte durante tu aventura.}
{1476}{}{El número de ratas que has matado. Incluye a todos los miembros de la familia de los roedores.}
{1477}{}{El número de Nómadas mutantes a los que has dado muerte.}
{1478}{}{El número de centauros mutantes muertos.}
{1479}{}{El número de robots que has destruido o desmontado.}
{1480}{}{El número total de perros que has enviado al cielo de los perros.}
{1481}{}{El número total de mantis, o bichos similares que has aplastado hasta ahora.}
{1482}{}{La cantidad de Garras mortales que has matado, y cualquiera de su estirpe.}
{1483}{}{La cantidad de plantas que has arrancado de este mundo.}
{1484}{}{El número de lagartos que has borrado de la faz de la tierra.}
{1485}{}{La cantidad de alienigenas asesinados con tus propias manos.}
{1486}{}{El número de insectos que has exterminado en el Yermo.}
{1487}{}{La cantidad de guardaespaldas maniacos homicidas cibernéticos creados por ingeniería genética que has matado.}


