#
# Quest descriptions
#
#    Please leave space between the areas (like 100 or so)
#

#
# Refugio 13 Quests
#
{100}{}{Encontrar el chip de agua.} 				#fo1 vanilla
{101}{}{Acaba con los rebeldes.}			        #fo1 vanilla
{102}{}{Encontrar al ladrón de agua.}				#fo1 vanilla
{103}{}{Destruye al líder mutante.}			        #fo1 vanilla
{104}{}{Destruye el origen de los mutantes.}	    #fo1 vanilla
{105}{}{Ayuda al médico a lograr el antídoto.}
{106}{}{Aprende del mundo en la biblioteca.}
{107}{}{Consigue entrar en la armería.}
{108}{}{Consigue volver a entrar al refugio.}
{109}{}{Mata al supervisor del refugio.}
{110}{}{Mata a todos los habitantes del Refugio 13.}
{120}{}{Encuentra el chip de agua.}

#
# Refugio 15 Quests
#
{200}{}{Busca pistas e información.}
{201}{}{Busca un chip de agua.}
{202}{}{Encuentra una forma de bajar por el hueco del ascensor.}
{203}{}{Encuentra los objetos ocultos.}
{204}{}{Mata a todas las ratas.}

#
# Shady Sands Quests
#
{300}{}{Habla con Katrina.}
{301}{}{Contrata a Ian.}
{302}{}{Detén a los radscorpiones.}							#fo1 vanilla
{303}{}{Ayuda a Razlo a encontrar una cura para el veneno de radscorpión.}	#fo1 vanilla
{304}{}{Cura a Jarvis del veneno de radscorpión.}				#fo1 vanilla
{305}{}{Rescata a Tandi de los Khans.}						#fo1 vanilla
{306}{}{Ayuda a Shady Sands a mejorar el rendimiento de sus cultivos.}
{307}{}{Guía a Seth y a los guardias para destruir a los Khans.}

#
# Ciudad Vertedero Quests
#
{400}{}{Ayuda a Saul.}										#fo1 vanilla
{401}{}{Mata a Killian.}									#fo1 vanilla
{402}{}{Rescata a Sinthia.}									#fo1 vanilla
{403}{}{Salva a Trish.}										#fo1 vanilla
{404}{}{Detén a Gizmo.}										#fo1 vanilla
{405}{}{Desarticula la banda de los Skulz.}					#fo1 vanilla
{406}{}{Únete a los Skulz.}
{407}{}{Roba la urna de Neal del Skum Pitt.}
{408}{}{RESERVED}

#
# Raiders Quests
#
{500}{}{Únete a los Khans.}
{501}{}{Destruye a los Khans.}
{502}{}{Mata a los esclavos.}
{503}{}{Salva a los esclavos.}
{504}{}{Avergüenza a Garl venciéndolo en combate cuerpo a cuerpo.}
{505}{}{Libera al prisionero.}
{506}{}{Libera a Tandi.}
{507}{}{Únete a los Khans en una incursión a Shady Sands.}
{508}{}{Abusa de los esclavos.}
{509}{}{Reemplaza a Garl como líder de los Khans.}

#
# Necropolis Quests
#
{600}{}{Destruye a los supermutantes en la Planta de Agua.}
{601}{}{Repara la bomba de agua de Necropolis.}
{602}{}{Rescata al prisionero.}
{603}{}{Recupera el chip de agua.}
{604}{}{Permite que los supermutantes de la Planta de Agua se marchen pacíficamente.}
{605}{}{Seduce a Harry.}
{606}{}{Recibe la recompensa de Set por eliminar a los supermutantes.}
{607}{}{Infiltrate en el Salón de los Muertos de Set.}
{608}{}{Encuentra una entrada a la Planta de Agua.}

#
# El Centro Quests
#
{700}{}{Encuentra y destruye al Deathclaw.}			        #fo1 vanilla
{701}{}{Elimina a Jain.}								    #fo1 vanilla
{702}{}{Elimina al comerciante.}							    #fo1 vanilla
{703}{}{Encuentra las caravanas desaparecidas.}			    #fo1 vanilla
{704}{}{Roba el collar a los Comerciantes.}				    #fo1 vanilla
{705}{}{Únete al Círculo de Ladrones.}
{706}{}{Elimina a Decker.}
{707}{}{Envía agua al Refugio 13.}
{708}{}{Hazte guardia de los Comerciantes de Agua.}
{709}{}{Hazte guardia de los Comerciantes Far Go.}
{710}{}{Hazte guardia de la Caravana Carmesí.}
{711}{}{Deshazte de los saqueadores en la Granja de Irwin.}

#
# Hermandad del Acero Quests
#
{800}{}{Conviértete en Iniciado.}					        #fo1 vanilla
{801}{}{Rescata al Iniciado en The Hub.}					    #fo1 vanilla
{802}{}{Conviértete en Caballero.}
{803}{}{Aprende de las computadoras de la biblioteca.}
{804}{}{Recibe operaciones de Lori.}
{805}{}{Seduce a Jennifer.}
{806}{}{Seduce a Lorri.}
{807}{}{Roba el Motivador Sistólico.}
{808}{}{Ayuda a Sophia y Michael.}
{809}{}{Consigue acceso a la Armería.}
{810}{}{Encuentra las ruinas de la Antigua Orden.}
{811}{}{Explora el área al norte.}
{812}{}{Consigue que la Hermandad ayude en la Base Militar.}
{813}{}{RESERVED}
{814}{}{RESERVED}
{815}{}{RESERVED}
{816}{}{RESERVED}
{817}{}{RESERVED}
{818}{}{RESERVED}

#
# Base Militar Quests
#
{900}{}{Consigue entrar en la base.}
{901}{}{Consigue entrar en la base sin ser detectado.}
{902}{}{Engaña a los mutantes para que abandonen sus puestos de guardia.}
{903}{}{Desactiva los campos de fuerza.}
{904}{}{Mata al Teniente.}
{905}{}{Destruye las Cubas.}

#
# The Glow Quests
#
{1000}{}{Consigue entrar en The Glow.}
{1001}{}{Desactiva las trampas de la instalación.}			#fo1 vanilla
{1002}{}{Enciende la energía en The Glow.}			        #fo1 vanilla

#
# L.A. Boneyard / Adytum Quests
#
{1100}{}{Conviértete en un Blade.}					        #fo1 vanilla
{1101}{}{Entrega el relicario a Romero.}					    #fo1 vanilla
{1102}{}{Entrega el paquete de los Gun Runners.}			    #fo1 vanilla
{1103}{}{Encuentra al espía de los Niños entre los Seguidores.}	#fo1 vanilla
{1104}{}{Repara las granjas hidropónicas de Adytum.}			#fo1 vanilla
{1105}{}{Rescata a Jason Zimmerman.}						    #fo1 vanilla
{1106}{}{Detén a las bandas que atacan Adytum.}			    #fo1 vanilla
{1107}{}{Mata a la Madre Deathclaw.}
{1108}{}{Convence a los Gun Runners de que provean a los Blades.}
{1109}{}{Mata al líder del ejército mutante en Necropolis.}
{1110}{}{RESERVED}
{1111}{}{RESERVED}

#
# Cathedral / Master's Vault Quests
#
{1200}{}{Consigue entrar en la Cámara del Maestro.}
{1201}{}{Convence a Rae de unirse a ti contra el Maestro.}
{1202}{}{Mata a Morpheus.}
{1203}{}{Mata al Maestro.}
{1204}{}{Configura el temporizador de la bomba.}

#
# Caravan Run Quests
#
{1300}{}{Ayuda a descargar la Caravana.}

#
# 
#
{1400}{}{RESERVED}
{1401}{}{RESERVED}
{1402}{}{RESERVED}
{1403}{}{RESERVED}

#
# 
#
{1500}{}{RESERVED}
{1501}{}{RESERVED}
{1502}{}{RESERVED}
{1503}{}{RESERVED}
{1504}{}{RESERVED}
{1505}{}{RESERVED}
{1506}{}{RESERVED}
{1507}{}{RESERVED}
{1508}{}{RESERVED}
{1509}{}{RESERVED}
{1510}{}{RESERVED}
{1511}{}{RESERVED}
{1512}{}{RESERVED}
{1513}{}{RESERVED}
{1514}{}{RESERVED}
{1515}{}{RESERVED}
{1516}{}{RESERVED}

#
# 
#
{1600}{}{RESERVED}
{1601}{}{RESERVED}
{1602}{}{RESERVED}

#
# 
#
{1700}{}{RESERVED}

#
# 
#
{1800}{}{RESERVED}

#
# 
#
{1900}{}{RESERVED}

#
# 
#
{2000}{}{RESERVED}

#
# 
#
{2100}{}{RESERVED}

#
# 
#
{2200}{}{RESERVED}

#
# 
#
{2300}{}{RESERVED}

#
# 
#
{2400}{}{RESERVED}

#
# 
#
{2500}{}{RESERVED}

#
# 
#
{2600}{}{RESERVED}

#
# Desert Encounter Quests
#
{2700}{}{RESERVED}

#
# Mountain Encounter Quests
#
{2800}{}{RESERVED}

#
# Ruined City Encounter Quests
#
{2900}{}{RESERVED}

#
# Coast Encounter Quests
#
{3000}{}{RESERVED}

#
# 
#
{3100}{}{RESERVED}

#
# 
#
{3200}{}{RESERVED}
{3201}{}{RESERVED}
{3202}{}{RESERVED}
{3203}{}{RESERVED}
