#
#   Messages from skilldex.c
#
{100}{}{  TÉCNICAS}
{101}{}{CANCELAR}
{102}{}{SIGILO}
{103}{}{GANZÚA}
{104}{}{ROBAR}
{105}{}{TRAMPAS}
{106}{}{1 AUXILIOS}
{107}{}{MÉDICO}
{108}{}{CIENCIA}
{109}{}{REPARAR}

