#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Metabolismo Rápido}
{101}{}{Fornido}
{102}{}{Enjuto}
{103}{}{Mano Dominante}
{104}{}{Refinado}
{105}{}{Kamikaze}
{106}{}{Bestia}
{107}{}{Tirador Rápido}
{108}{}{Masacre}
{109}{}{Gafe}
{110}{}{Buena Persona}
{111}{}{Enganchado}
{112}{}{Inmunizado}
{113}{}{Noctámbulo}
{114}{}{Habilidoso}
{115}{}{Capacitado}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{Tu tasa metabólica es dos veces la normal. Esto significa que presentas menos resistencia a la radiación y al veneno, pero tu cuerpo se recupera antes.}
{201}{}{Algo más lento pero más fuerte. Puede que no golpees con tanta frecuencia, ¡pero lo sentirán cuando lo hagas! Tus puntos totales de acción han bajado, pero tu Fuerza ha aumentado.}
{202}{}{No eres tan grande como los otros habitantes del Refugio, pero eso nunca te ha detenido. No puedes transportar tanta carga, pero eres más ágil.}
{203}{}{Una de tus manos es muy dominante. Eres infalible con las armas de una sola mano, pero las armas que requieren el uso de las dos te suponen un problema.}
{204}{}{Tus ataques demuestran mucha precisión. No causas daño con tanta frecuencia pero tus golpes son certeros.}
{205}{}{Como no prestas atención a las amenazas, actúas con mucha más rapidez en un turno. Esto reduce la clase de armadura a lo que llevas puesto, pero reaccionas con mayor rapidez en una ronda de combate.}
{206}{}{Atacas con más crudeza pero no mejor. Tus ataques son muy brutales pero imprecisos. No sueles causar daños críticos, pero siempre causarás más daño en melé.}
{207}{}{No tienes tiempo para preparar un ataque controlado, aunque atacas con más rapidez que las personas normales. Por ello utilizar un arma te cuesta un punto menos de acción.}
{208}{}{Por alguna extraña circunstancia del destino, la gente que te rodea muere violentamente. Eres testigo constante de las peores muertes.}
{209}{}{Lo bueno es que todos los que te rodean tienen más fallos críticos durante el combate. ¡Lo malo es que tú también!}
{210}{}{De pequeño estudiaste técnicas poco combativas. Tus habilidades en combate comienzan en un nivel más bajo, pero en Primeros Auxilios, Médico, Conversación y Trueque has mejorado notablemente.}
{211}{}{Te vuelves adicto a las sustancias químicas con más facilidad. Tu predisposición a engancharte a las drogas es dos veces la normal, pero te recuperas con más facilidad de sus efectos nocivos.}
{212}{}{Las sustancias químicas sólo te afectan la mitad que a los demás y tu predisposición a engancharte es sólo un 50% de la normal.}
{213}{}{Por tu condición de noctámbulo, estás más despierto cuando el sol se pone. Tu Inteligencia y Percepción mejoran por la noche pero durante el día se enturbian.}
{214}{}{Has dedicado más tiempo que lo normal en tus estudios. Comienzas con niveles de técnica superiores. La desventaja es que no ganas tantas habilidades extra. Ganarás una Ventaja cada cuatro niveles.}
{215}{}{Tienes habilidades innatas, pero has ignorado tus estudios. Recibes +1 punto a tus puntos de personaje, pero al comenzar pierdes 10% en todas las técnicas y recibes 5 puntos de técnica menos por nivel.}

