#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by town and world map
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#

#
# Town map selection names
#
# Format:
#	city type.
#	Up to 10 selection names
#
# Vault 13
{200}{}{Entrada a la Caverna}
{201}{}{Entrada}
{202}{}{Aposentos}
{203}{}{Centro de Mando}
#
# Vault 15
{210}{}{Entrada del Desierto}
{211}{}{Cavernas/Entrada}
{212}{}{Aposentos}
{213}{}{Centro de Mando}
#
# Shady Sands
{220}{}{Entrada}
{221}{}{Campo de Cultivo}
{222}{}{Corral de Brahmins}
#
# Junktown
{230}{}{Entrada}
{231}{}{Posada}
{232}{}{Casino}
#
# Raiders
{240}{}{Base}
#
# Necropolis
{250}{}{Hotel}
{251}{}{Sala}
{252}{}{Almacén de Agua}
#
# Hub
{260}{}{Entrada}
{261}{}{Centro ciudad}
{262}{}{Alturas}
{263}{}{Ciudad Antigua}
{264}{}{Mercaderes}
{265}{}{Cueva}
#
# Brotherhood
{270}{}{Entrada}
{271}{}{Nivel 1}
{272}{}{Nivel 2}
{273}{}{Nivel 3}
{274}{}{Nivel 4}
#
# Military Base
{280}{}{Entrada}
{281}{}{Fortaleza Nivel 1}
{282}{}{Fortaleza Nivel 2}
{283}{}{Tanques Nivel 1}
{284}{}{Tanques Nivel 2}
#
# Glow
{290}{}{Cráter}
{291}{}{Nivel 1}
#
# Cementerio
{300}{}{Adytum}
{301}{}{Centro ciudad}
{302}{}{Biblioteca}
{303}{}{Fortaleza}
{304}{}{Almacén}
#
# Catedral
{310}{}{Entrada}
{311}{}{Interior}

# Misc messages
{500}{}{¡Has ganado 10.000 puntos de experiencia!}
{501}{}{Ruinas}

#
# Terrain type names for world map hover button
#
{1000}{}{Desierto}
{1001}{}{Montañas}
{1002}{}{Ciudad}
{1003}{}{Costa}
{1004}{}{Desconocido}  # Unknown/visited city

