/*

   Stuff you can change via fo1_settings.ini file

*/

#include "..\headers\define.h"

procedure start;

procedure settings;

procedure start begin
   if (game_loaded) then begin
   	set_global_script_type(0);
   	call settings;
   	//debug("load settings");
   end
end

procedure settings begin

   //===================================================
   // Debug:
   set_global_var(CHEAT_DEBUG_MENU_ENABLED,        get_ini_setting("config\\fo1_settings.ini|DEBUG|CHEAT_DEBUG_MENU_ENABLED"));
   set_global_var(DEBUG_MODE_MESSAGES_ON,          get_ini_setting("config\\fo1_settings.ini|DEBUG|DEBUG_MODE_MESSAGES_ON"));
   set_global_var(CHEAT_START_ITEMS_ENABLED,       get_ini_setting("config\\fo1_settings.ini|DEBUG|CHEAT_START_ITEMS_ENABLED"));

	//===================================================
	// Fo1in2:
	set_global_var(GVAR_DISABLE_FLUFF_ENCOUNTER,		get_ini_setting("config\\fo1_settings.ini|Fo1in2|GVAR_DISABLE_FLUFF_ENCOUNTER"));

   //===================================================
   // FIXT:
   set_global_var(FIXT_BUGFIXES_ONLY,              get_ini_setting("config\\fo1_settings.ini|FIXT|FIXT_BUGFIXES_ONLY"));
   set_global_var(AGATHA_IS_ENABLED,               get_ini_setting("config\\fo1_settings.ini|FIXT|AGATHA_IS_ENABLED"));
   set_global_var(BOS_LORRI_CHA_ENABLED,           get_ini_setting("config\\fo1_settings.ini|FIXT|BOS_LORRI_CHA_ENABLED"));
   set_global_var(CHILDKILLER_PIC_RESTORE,         get_ini_setting("config\\fo1_settings.ini|FIXT|CHILDKILLER_PIC_RESTORE"));
   set_global_var(MYST_STRANGER_RESPAWNS,          get_ini_setting("config\\fo1_settings.ini|FIXT|MYST_STRANGER_RESPAWNS"));
   set_global_var(HIT_GIVES_RADS_GHOULS,           get_ini_setting("config\\fo1_settings.ini|FIXT|HIT_GIVES_RADS_GHOULS"));
   set_global_var(DISPLAY_PLVL_ON_LVLUP,           get_ini_setting("config\\fo1_settings.ini|FIXT|DISPLAY_PLVL_ON_LVLUP"));
   set_global_var(ENABLE_HOOKERS,                  get_ini_setting("config\\fo1_settings.ini|FIXT|ENABLE_HOOKERS"));
   set_global_var(HIT_GIVES_RADS_FLOATERS,         get_ini_setting("config\\fo1_settings.ini|FIXT|HIT_GIVES_RADS_FLOATERS"));
   set_global_var(STAPLE_INIT_NUM_BOOKS,           get_ini_setting("config\\fo1_settings.ini|FIXT|STAPLE_INIT_NUM_BOOKS"));
   set_global_var(STAPLE_BOOKS_RESPAWN_MIN,        get_ini_setting("config\\fo1_settings.ini|FIXT|STAPLE_BOOKS_RESPAWN_MIN"));
   set_global_var(STAPLE_BOOKS_RESPAWN_MAX,        get_ini_setting("config\\fo1_settings.ini|FIXT|STAPLE_BOOKS_RESPAWN_MAX"));
   set_global_var(STAPLE_DIFFICULTY_BASED,         get_ini_setting("config\\fo1_settings.ini|FIXT|STAPLE_DIFFICULTY_BASED"));
   set_global_var(PLAYER_CAN_LVL_PAST_21,          get_ini_setting("config\\fo1_settings.ini|FIXT|PLAYER_CAN_LVL_PAST_21"));
   set_global_var(FULL_HP_ON_LVLUP,                get_ini_setting("config\\fo1_settings.ini|FIXT|FULL_HP_ON_LVLUP"));
   set_global_var(BITS_BOB_GOES_TO_JAIL,           get_ini_setting("config\\fo1_settings.ini|FIXT|BITS_BOB_GOES_TO_JAIL"));
   set_global_var(FORTUNE_FINDER_HOW_MUCH,         get_ini_setting("config\\fo1_settings.ini|FIXT|FORTUNE_FINDER_HOW_MUCH"));
   set_global_var(MYST_STRANGER_CHANCE,            get_ini_setting("config\\fo1_settings.ini|FIXT|MYST_STRANGER_CHANCE"));
   set_global_var(MYST_STRANGER_LUCK_BASED,        get_ini_setting("config\\fo1_settings.ini|FIXT|MYST_STRANGER_LUCK_BASED"));
   set_global_var(MYST_STRANGER_HAS_ARMOR,         get_ini_setting("config\\fo1_settings.ini|FIXT|MYST_STRANGER_HAS_ARMOR"));
   set_global_var(HUNTER_RESPAWNS,                 get_ini_setting("config\\fo1_settings.ini|FIXT|HUNTER_RESPAWNS"));
   set_global_var(ANIMAL_FRIEND_RADSCORPS,         get_ini_setting("config\\fo1_settings.ini|FIXT|ANIMAL_FRIEND_RADSCORPS"));
   set_global_var(KILLIAN_WARES_MERGED,            get_ini_setting("config\\fo1_settings.ini|FIXT|KILLIAN_WARES_MERGED"));
   set_global_var(POWER_ARMOR_WEIGHTS	,           get_ini_setting("config\\fo1_settings.ini|FIXT|POWER_ARMOR_WEIGHTS"));
   set_global_var(EXPLOSIVES_RUIN_LOCKERS,         get_ini_setting("config\\fo1_settings.ini|FIXT|EXPLOSIVES_RUIN_LOCKERS"));
   set_global_var(MALE_PLAYER_SMOKES,              get_ini_setting("config\\fo1_settings.ini|FIXT|MALE_PLAYER_SMOKES"));
   set_global_var(RANDOM_ENC_IGNORE_LUCK,          get_ini_setting("config\\fo1_settings.ini|FIXT|RANDOM_ENC_IGNORE_LUCK"));
   set_global_var(RANDOM_ENC_DIFF_BASED,           get_ini_setting("config\\fo1_settings.ini|FIXT|RANDOM_ENC_DIFF_BASED"));
   set_global_var(RANDOM_ENC_LEVEL_BASED,          get_ini_setting("config\\fo1_settings.ini|FIXT|RANDOM_ENC_LEVEL_BASED"));
   set_global_var(ARMOR_DESTROY_MOD,               get_ini_setting("config\\fo1_settings.ini|FIXT|ARMOR_DESTROY_MOD"));
   set_global_var(ARMOR_EQUIP_MOD,                 get_ini_setting("config\\fo1_settings.ini|FIXT|ARMOR_EQUIP_MOD"));
   set_global_var(MR_HANDYC_HIRELING,              get_ini_setting("config\\fo1_settings.ini|FIXT|MR_HANDYC_HIRELING"));
   set_global_var(MBASE_RED_ONLY_PLAYER,           get_ini_setting("config\\fo1_settings.ini|FIXT|MBASE_RED_ONLY_PLAYER"));
   set_global_var(MBASE_RED_ONLY_PARTY,            get_ini_setting("config\\fo1_settings.ini|FIXT|MBASE_RED_ONLY_PARTY"));
   set_global_var(PLAYER_LOOTS_MEAT_BODIES,        get_ini_setting("config\\fo1_settings.ini|FIXT|PLAYER_LOOTS_MEAT_BODIES"));
   set_global_var(GIFTED_MINUS_10_PERLEVEL,        get_ini_setting("config\\fo1_settings.ini|FIXT|GIFTED_MINUS_10_PERLEVEL"));
   set_global_var(WILD_WASTELAND,                  get_ini_setting("config\\fo1_settings.ini|FIXT|WILD_WASTELAND"));
   set_global_var(HOW_INVASIONS_STOPPED,           get_ini_setting("config\\fo1_settings.ini|FIXT|HOW_INVASIONS_STOPPED"));
   set_global_var(CAN_PLAY_AFTER_V13_DEAD,         get_ini_setting("config\\fo1_settings.ini|FIXT|CAN_PLAY_AFTER_V13_DEAD"));
   set_global_var(GAME_CONTINUES_AS_MUTANT,        get_ini_setting("config\\fo1_settings.ini|FIXT|GAME_CONTINUES_AS_MUTANT"));
   set_global_var(IRONMAN_MODE,                    get_ini_setting("config\\fo1_settings.ini|FIXT|IRONMAN_MODE"));
   set_global_var(ANIMAL_FRIEND_JOIN_TEAM,         get_ini_setting("config\\fo1_settings.ini|FIXT|ANIMAL_FRIEND_JOIN_TEAM"));
   set_global_var(HIT_GIVES_RADS_CENTAURS,         get_ini_setting("config\\fo1_settings.ini|FIXT|HIT_GIVES_RADS_CENTAURS"));
   set_global_var(HIT_GIVES_MORE_RADS_RATS,        get_ini_setting("config\\fo1_settings.ini|FIXT|HIT_GIVES_MORE_RADS_RATS"));
   set_global_var(HIT_GIVES_MORE_RADS_GLOW,        get_ini_setting("config\\fo1_settings.ini|FIXT|HIT_GIVES_MORE_RADS_GLOW"));
   //set_global_var(DOCTOR_SHOW_RADS_POISON,         get_ini_setting("config\\fo1_settings.ini|FIXT|DOCTOR_SHOW_RADS_POISON"));
   set_global_var(BOS_LORRI_SEX_ENABLED,           get_ini_setting("config\\fo1_settings.ini|FIXT|BOS_LORRI_SEX_ENABLED"));
   set_global_var(TANDI_SEX_ENABLED,               get_ini_setting("config\\fo1_settings.ini|FIXT|TANDI_SEX_ENABLED"));
   set_global_var(CAVES_LIGHT_LEVEL,               get_ini_setting("config\\fo1_settings.ini|FIXT|CAVES_LIGHT_LEVEL"));
   set_global_var(BOS_LORRI_NUM_OPS_ALLOWED,       get_ini_setting("config\\fo1_settings.ini|FIXT|BOS_LORRI_NUM_OPS_ALLOWED"));
   set_global_var(CHILDKILLER_NUM_KILLS,           get_ini_setting("config\\fo1_settings.ini|FIXT|CHILDKILLER_NUM_KILLS"));
   set_global_var(CHILDKILLER_FROM_HOMIES,         get_ini_setting("config\\fo1_settings.ini|FIXT|CHILDKILLER_FROM_HOMIES"));
   set_global_var(FADE_TIMES_INCREASED,            get_ini_setting("config\\fo1_settings.ini|FIXT|FADE_TIMES_INCREASED"));
   set_global_var(LONG_FADES_INCREASED,            get_ini_setting("config\\fo1_settings.ini|FIXT|LONG_FADES_INCREASED"));
   set_global_var(STAPLE_RESTOCK_WEEKS,            get_ini_setting("config\\fo1_settings.ini|FIXT|STAPLE_RESTOCK_WEEKS"));

end
