#include "..\headers\define.h"

procedure start;
variable test;

procedure start begin
end

procedure use_obj_on_p_proc begin
   if (obj_pid(obj_being_used_with) == PID_PLASTIC_EXPLOSIVES) then begin// Plastic Explosives
      script_overrides;
      test := roll_vs_skill(dude_obj, SKILL_TRAPS, 0);
      if (is_success(test)) then begin
         display_msg(message_str(SCRIPT_BLAST, 100));
         give_exp_points(10);
         display_msg(message_str(SCRIPT_BLAST, 103));
      end
      else begin
         if (is_critical(test)) then begin
            display_msg(message_str(SCRIPT_BLAST, 101));
            critter_dmg(dude_obj, random(40, 80), DMG_explosion);
         end
         else begin
            display_msg(message_str(SCRIPT_BLAST, 102));
         end
      end
   end
end
