#include "..\headers\define.h"
#include "..\headers\command.h"

procedure start;


procedure start begin
end

procedure spatial_p_proc begin
  if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
	 if (local_var(0) == 0) then begin
		if (dude_iq > 6) then begin
		   display_msg(message_str(SCRIPT_BLKROOM, 100));
		end
		else begin
		   display_msg(message_str(SCRIPT_BLKROOM, 101));
		end
		set_local_var(0, 1);
	 end
  end
end
