/*

   ???

*/

#include "..\headers\define.h"
#include "..\headers\mbase.h"

#define NAME                    SCRIPT_SEMICOMP

#include "..\headers\command.h"

procedure start;
procedure look_at_p_proc;
procedure use_skill_on_p_proc;

procedure search;
procedure skills;

procedure start begin
	if (local_var(0) == 0) then begin
		set_local_var(0, random(1, 9));
	end
end

procedure look_at_p_proc begin
	script_overrides;
	call search;
end

procedure use_skill_on_p_proc begin
	script_overrides;
	call skills;
end

procedure search begin
	if (tile_distance_objs(self_obj, dude_obj) > 3) then begin
		display_msg(mstr(100));
	end
	else if (local_var(0) == 1) then begin
		display_msg(mstr(102));
	end
	else if (local_var(0) == 2) then begin
		display_msg(mstr(103));
	end
	else if (local_var(0) == 3) then begin
		display_msg(mstr(104));
	end
	else if (local_var(0) == 4) then begin
		display_msg(mstr(105));
	end
	else if (local_var(0) == 5) then begin
		display_msg(mstr(106));
	end
	else if (local_var(0) == 6) then begin
		display_msg(mstr(107));
	end
	else if (local_var(0) == 7) then begin
		display_msg(mstr(108));
	end
	else if (local_var(0) == 8) then begin
		display_msg(mstr(109));
	end
	else if (local_var(0) == 9) then begin
		display_msg(mstr(111));
	end
end

procedure skills begin
	if ((action_being_used == SKILL_REPAIR) or (action_being_used == SKILL_SCIENCE)) then
		display_msg(mstr(101));
	else
		display_msg(mstr(102));
end
