#include "define.h"
#include "command.h"

procedure start;
procedure map_enter_p_proc;

procedure start;

procedure destroy_p_proc begin
end

procedure look_at_p_proc begin
   display_msg("my pid is: " + self_pid);
   display_msg("my fid is: " + self_fid);
end

procedure map_enter_p_proc begin
   //display_msg("pid is: " + self_pid);
end

procedure start begin
   display_msg("pid is: " + self_pid);
end
