#include "..\headers\define.h"

procedure start;


procedure start
begin
	if ((script_action == 21) or (script_action == 3)) then begin// 21 is look_at, 3 is description (Binoculars)   //NEED TO FIX THIS, DUPLICATE DESCRIPTIONS IS BULLSHIT. --Sduibek
		script_overrides;
		display_msg(message_str(428, 100));
	end
	else begin
		if (script_action == 8) then begin//<-- use_skill_on_p_proc
			script_overrides;
			display_msg(message_str(428, 101));
		end
	end
end

