#include "..\headers\define.h"

procedure start;

variable HEREBEFORE;


procedure start
begin
	if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
		if source_obj == dude_obj then begin
			if (HEREBEFORE == 0) then begin
				if ((anim_busy(dude_obj) == 0) or (anim_busy(dude_obj) == 1)) then begin
					script_overrides;
					load_map("hotel.map", 5);
				end
			end
		end
	end
end

