#include "..\headers\define.h"

procedure start;


procedure start
begin
	if ((script_action == 21) or (script_action == 3)) then begin// 21 is look_at, 3 is description (Binoculars)   //NEED TO FIX THIS, DUPLICATE DESCRIPTIONS IS BULLSHIT. --Sduibek
		script_overrides;
		if ((global_var(WORLDMAPLIST_BROTHERHOOD) == 2) and is_success(do_check(dude_obj, STAT_pe, 0))) then begin
			display_msg(message_str(SCRIPT_PERNPWR, 100));
		end
		else begin
			display_msg(message_str(SCRIPT_PERNPWR, 101));
		end
	end
	else begin
		if (script_action == 8) then begin//<-- use_skill_on_p_proc
			script_overrides;
			if (action_being_used == SKILL_DOCTOR) then begin//-- DOCTOR
				if (is_success(roll_vs_skill(dude_obj, SKILL_DOCTOR, 0))) then begin
					display_msg(message_str(SCRIPT_PERNPWR, 102));
				end
				else begin
					display_msg(message_str(SCRIPT_PERNPWR, 103));
				end
			end
			else begin
				display_msg(message_str(SCRIPT_PERNPWR, 104));
			end
		end
	end
end

