#include "..\headers\define.h"

procedure start;


procedure start
begin
	if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
		if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
			if (local_var(0) == 0) then begin
				set_local_var(0, 1);
				display_msg(message_str(303, 100));
			end
		end
	end
end

