/*
   Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/


#include "..\headers\define.h"
#define NAME                    SCRIPT_ANIMFRVR
#include "..\headers\command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure combat_p_proc;

procedure start begin
   call map_update_p_proc;
end

procedure map_enter_p_proc begin
   reg_anim_clear(self_obj);
   //reg_anim_combat_check(0); <- This will kill all combat in this map. :>
   reg_anim_begin();
   reg_anim_animate_forever(self_obj, ANIM_stand);
   reg_anim_end();
end

procedure map_update_p_proc begin
   reg_anim_clear(self_obj);
   //reg_anim_combat_check(0); <- This will kill all combat in this map. :>
   reg_anim_begin();
   reg_anim_animate_forever(self_obj, ANIM_stand);
   reg_anim_end();
end

procedure combat_p_proc begin
   //call map_update_p_proc;
end
