#include "..\headers\define.h"
#include "..\headers\command.h"

procedure start;
procedure use_p_proc;
procedure use_skill_on_p_proc;

procedure Coke01;

variable caps;

procedure start begin
end

procedure use_p_proc begin
	script_overrides;
	call Coke01;
end

procedure Coke01 begin
	set_local_var(0, 1);
	caps := (random(1, 2) + random(1, 2) + random(1, 2)) + (dude_luck - 3);
// LCK1 = 1 to 4
// LCK5 = 5 to 8
// LCK10 = 10 to 13
	dude_caps_adjust(caps);
	display_msg(message_str(SCRIPT_COKE, 101));
end

procedure use_skill_on_p_proc begin
	if not(local_var(0)) then begin
		script_overrides;
		if (action_being_used == SKILL_REPAIR) then begin//-- REPAIR
			if (is_success(roll_vs_skill(dude_obj, SKILL_REPAIR, 0))) then begin
				call Coke01;
			end
		end
		else if (action_being_used == SKILL_SCIENCE) then begin
			if (is_success(roll_vs_skill(dude_obj, SKILL_SCIENCE, 0))) then begin
				call Coke01;
			end
		end
	end
end
