/*

   Generic gambler

*/

/* Include Files */
#include "define.h"
//#include "area/necropolis.h"

#define NAME                    SCRIPT_GAMBLER
//#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */
procedure start;
procedure see_stuff;
procedure talk_p_proc;
procedure destroy_p_proc;

procedure Hernandez01;
procedure Hernandez02;
procedure Hernandez03;
procedure Hernandez04;
procedure Hernandez05;
procedure Hernandez06;
procedure Hernandez07;
procedure Hernandez08;
procedure Hernandez09;
procedure Hernandez10;
procedure Hernandez11;
procedure Hernandez12;
procedure Hernandez13;
procedure Hernandez14;
procedure Hernandezend;

variable known;

procedure start begin
end

procedure timed_event_p_proc begin
   attack(dude_obj);
end

procedure look_at_p_proc begin
   call see_stuff;
end

procedure description_p_proc begin
   call see_stuff;
end

procedure see_stuff begin
   script_overrides;
   if (known) then
      display_msg(mstr(100));
   else
      display_msg(mstr(101));
end

procedure talk_p_proc begin
   dude_look_at_self;
   start_gdialog(247, self_obj, 4, -1, -1);
   gsay_start;
   if (known) then begin
      call Hernandez01;
   end
   else begin
      call Hernandez12;
   end
   gsay_end;
   end_dialogue;
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure Hernandez01 begin
   Reply(102);
   known := 1;
   NOption(103, Hernandez02, 4);
   NOption(104, Hernandez03, 4);
   NLowOption(105, Hernandez04);
end

procedure Hernandez02 begin
   NMessage(106);
   NOption(107, Hernandez03, 4);
   NOption(108, Hernandez09, 5);
   NOption(109, Hernandez11, 5);
end

procedure Hernandez03 begin
   variable LVar0 := 0;
   variable LVar1 := 0;
   LVar0 := do_check(dude_obj, STAT_pe, 0);
   LVar1 := mstr(110);
   if (is_success(LVar0)) then begin
      LVar1 := LVar1 + mstr(111);
   end
   NMessage(LVar1);
   Reply(112);
   NOption(113, Hernandez05, 4);
   NOption(114, Hernandez06, 4);
   if (is_success(LVar0)) then begin
      NOption(115, Hernandez14, 4);
   end
end

procedure Hernandez04 begin
   NMessage(116);
end

procedure Hernandez05 begin
   NMessage(117);
end

procedure Hernandez06 begin
   NMessage(118);
end

procedure Hernandez07 begin
   Reply(119);
   NOption(120, Hernandez08, 4);
   NOption(121, Hernandez03, 4);
end

procedure Hernandez08 begin
end

procedure Hernandez09 begin
   NMessage(122);
   Reply(123);
   NOption(124, Hernandez07, 4);
   NOption(125, Hernandez10, 6);
end

procedure Hernandez10 begin
   NMessage(126);
end

procedure Hernandez11 begin
   Reply(127);
   NOption(128, Hernandez03, 4);
end

procedure Hernandez12 begin
   if (dude_is_male) then begin
      Reply(136);
   end
   else begin
      Reply(137);
   end
   NOption(130, Hernandez13, 4);
   NOption(131, Hernandezend, 4);
end

procedure Hernandez13 begin
   NMessage(132);
   NOption(133, Hernandezend, 4);
   NOption(134, Hernandez14, 4);
end

procedure Hernandez14 begin
   NMessage(135);
   add_timer_event(self_obj, 5, 1);
end

procedure Hernandezend begin
end
