#include "define.h"
#include "command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;

procedure lighting;

procedure start begin
end

procedure map_enter_p_proc begin
   call lighting;
end

procedure map_update_p_proc begin
   call lighting;
end

procedure lighting begin
   if (morning) then begin
      obj_set_light_level(self_obj, game_time_hour - 600 + 40, 8);
   end
   else if (evening) then begin
      obj_set_light_level(self_obj, 100 - (game_time_hour - 1800), 8);
   end
   else if day then begin
      obj_set_light_level(self_obj, 100, 8);
   end
   else begin
      obj_set_light_level(self_obj, 40, 8);
   end
end
