#
# Inventory messages from inventry.c
#
{0}{}{SÍ}
{1}{}{VN}
{2}{}{OD}
{3}{}{CH}
{4}{}{IN}
{5}{}{HB}
{6}{}{ŠT}
{7}{}{  HitBody}
{8}{}{  Tø.Zbroje}
{9}{}{  Normal}
{10}{}{  Laser}
{11}{}{  Oheò}
{12}{}{  Plazma}
{13}{}{  Exploze}
{14}{}{Prázdná ruka}
{15}{}{Pošk:}
{16}{}{Dsh:}
{17}{}{Náb.:}
{18}{}{(Neobleèeno)}
{19}{}{Nemáš dost akèních bodù pro vstup do inventáøe.}
{20}{}{Náklad:}
{21}{}{PØESUÒ VÌCI}
{22}{}{VŠE}
{23}{}{NASTAV ÈASOVAÈ}
{24}{}{Poškození:}
{25}{}{Nemùžeš to vzít. Víc už toho neuneseš.}
{26}{}{Pro tuhle vìc tu není dostatek volného místa.}
{27}{}{Souhlasím. To je dobrý obchod.}
{28}{}{Ne, tvoje nabídka není dost dobrá.}
{29}{}{Získáváš %d zkuš. bodù za úspìšné použití dovednosti "Kradení".}
{30}{}{Váha}
{31}{}{Promiò, ale víc už neuneseš.}
{32}{}{Promiò, ale je to pøíliš tìžké.}

{50}{}{Nenacházíš nic, co by se dalo vzít.}
