#
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#

# System
{100}{}{NAÈÍST HRU (F5)}              # Titles
{101}{}{RYCHL NAÈTENÍ(F7)}
{102}{}{ULOŽIT HRU (F4)}
{103}{}{RYCHLÉ ULOŽENÍ(F6)}
{104}{}{OK}
{105}{}{ZRUŠIT}
{106}{}{Chyba pøi naètení seznamu uloženýh pozic!} # Line 1
{107}{}{Adresáø pro uloženou pozici:}    # Line 2
{108}{}{Neexistuje nebo je poškozen.} # Line 3
{109}{}{ULOŽIT SOUÈASNOU HRU}
{110}{}{NAÈÍST ULOŽENOU HRU}
{111}{}{- PRÁZDNÁ POZICE -}
{112}{}{- POŠKOZENÁ POZICE -}
{113}{}{- STARÁ VERZE -}
{114}{}{Prázdná pozice.}
{115}{}{Chyba!}
{116}{}{Stará verze.}
{117}{}{LED}                            # Months
{118}{}{ÚNO}
{119}{}{BØE}
{120}{}{DUB}
{121}{}{KVÌ}
{122}{}{ÈEN}
{123}{}{ÈEC}
{124}{}{SRP}
{125}{}{ZÁØ}
{126}{}{ØIJ}
{127}{}{LIS}
{128}{}{PRO}
{129}{}{ÚROVEÒ}
{130}{}{POPIS}
{131}{}{Uložená pozice již existuje. Pøepsat?}
{132}{}{Chyba pøi ukložení hry!}             # Line 1
{133}{}{Není možné hru uložit.}           # Line 2
{134}{}{Chyba pøi naètení hry!}            # Line 1
{135}{}{Není možné hru naèíst.}           # Line 2
{136}{}{Pozice je ze staré verze.}
{137}{}{Mapa}

{140}{}{Hra byla uložena.}
{141}{}{Hra byla naètena.}
#
# Demo versions only
#
{200}{}{Promiò ale v demo verzi } # 1
{201}{}{není možné ukládat ani nahrávat.}         # 2
