#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Vault 13 Quests
#
{100}{}{Najdi vodní èip} 				#fo1 vanilla
{101}{}{Uklidni skupinu rebelù}			#fo1 vanilla
{102}{}{Najdi zlodìje vody}				#fo1 vanilla
{103}{}{Zniè Vùdce mutantù}			#fo1 vanilla
{104}{}{Zniè zdroj mutantù}	#fo1 vanilla
{105}{}{Pomoz doktorovi syntetizovat protijed}
{106}{}{Najdi v knihovnì informace o venkovní svìtì}
{107}{}{Získej pøístup do Zbrojnice}
{108}{}{Získej pøístup zpátky do Vaultu}
{109}{}{Zabij Správce}
{110}{}{Zabij všechny obyvatele Vaultu 13}
{120}{}{Najdi vodní èip}
#
# Vault 15 Quests
#
{200}{}{Najdi nìjaké uiteèné informace}
{201}{}{Najdi vodní èip}
{202}{}{Spus se dolù vıtahovou šachtou}
{203}{}{Najdi skryté pøedmìty}
{204}{}{Zabij všechny krysy}
#
# Shady Sands Quests
#
{300}{}{Promluv si s Katrinou}
{301}{}{Naverbuj Iana}
{302}{}{Zastav radškorpiony}							#fo1 vanilla
{303}{}{Pomoz Razlovi vytvoøit protijed}	#fo1 vanilla
{304}{}{Vyleè Jarvise z otravy radškorpióním jedem}				#fo1 vanilla
{305}{}{Zachraò Tandi}					#fo1 vanilla
{306}{}{Pomoz farmáøùm v Shady Sands s jejich úrodou}
{307}{}{Veï Setha se stránımi a zniète Khany}

#
# Junktown Quests
#
{400}{}{Pomo Saulovi}										#fo1 vanilla
{401}{}{Zabij Killiana}									#fo1 vanilla
{402}{}{Zachraò Sinthii}								#fo1 vanilla
{403}{}{Zachraò Trish}									#fo1 vanilla
{404}{}{Zbav se Gizma}									#fo1 vanilla
{405}{}{Zlikviduj gang Lebkounù}							#fo1 vanilla
{406}{}{Pøidej se k Lebkounùm}
{407}{}{Ukradni Nealovi urnu z Skum Pitt}
{408}{}{RESERVED}

#
# Raiders Quests
#
{500}{}{Pøidej se ke Khanum}
{501}{}{Zniè Khany}
{502}{}{Zabij všechny otroky}
{503}{}{Osvoboï všechny otroky}
{504}{}{Vyzvi Garla na souboj a pora ho}
{505}{}{Osvoboï vìznì}
{506}{}{Osvoboï Tandi}
{507}{}{Pøidej se ke Khanum pøi nájezdu na Shady Sands}
{508}{}{Zneuij otroky}
{509}{}{Nahraï Garla jako novı vùdce Khanu}

#
# Necropolis Quests
#
{600}{}{Zbav se supermutantù ve Vodárnì}
{601}{}{Oprav vodní èerpadlo v Nekropolis}
{602}{}{Osvoboï vìznì}
{603}{}{Získej Vodní èip}
{604}{}{Pøesvìè supermutanty ve Vodárnì aby odešli}
{605}{}{Sveï Harryho}
{606}{}{Vyzvedni si od Seta odmìnu za odstranìní se supermutantù}
{607}{}{Vpli se do Setovy Haly mrtvıch}
{608}{}{Najdi vstup do Vodárny}

#
# The Hub Quests
#
{700}{}{Najdi a zabij Páraèe}			#fo1 vanilla
{701}{}{Zbav se Jain}							#fo1 vanilla
{702}{}{Zbav se Darena Hightowera}						#fo1 vanilla
{703}{}{Rozlušti záhadu ztracenıch karavan}					#fo1 vanilla
{704}{}{Ukradni Kupcùm s vodou náhrdelník}			#fo1 vanilla
{705}{}{Staò se èlenem Cechu zlodìjù}
{706}{}{Zbav Deckera}
{707}{}{Vyprav karavanu s vodu do Vaultu 13}
{708}{}{Staò se stránım Kupcù s vodou}
{709}{}{Staò se stránım Far Go Traders}
{710}{}{Staò se stránım Karmínové karavany}
{711}{}{Zbav se nájezdníkù na Irwinovì farmì}

#
# Brotherhood of Steel Quests
#
{800}{}{Staò se Zasvìcencem}						#fo1 vanilla
{801}{}{Zachraò Zasvìcence z Hubu}				#fo1 vanilla
{802}{}{Staò se Rytíøem}
{803}{}{Prostuduj poèítaèe v knihovnì}
{804}{}{Nech si od Lorri udìlat operace}
{805}{}{Oprav Energetickou zbroj.}
{806}{}{Sveï Lorri}
{807}{}{Ukradni systolickı motivátor}
{808}{}{Dones Pulzní granáty Sophii.}
{809}{}{Získej pøístup do zbrojnice}
{810}{}{Najdi ruiny prastarého øádu}
{811}{}{Prozkoumejte oblast na sever}
{812}{}{Získejte pomoc Bratrstva pøi útoku na Vojenskou základnu}
{813}{}{RESERVED}
{814}{}{RESERVED}
{815}{}{RESERVED}
{816}{}{RESERVED}
{817}{}{RESERVED}
{818}{}{RESERVED}

#
# Military Base Quests
#
{900}{}{Získej pøístup do základny}
{901}{}{Dostaò se do základny ani by tì nìkdo odhalil}
{902}{}{Pøesvìdè mutanty na strái aby opustili své stanovištì}
{903}{}{Deaktivuj silová pole}
{904}{}{Zabij Poruèíka}
{905}{}{Zniè Nádre s FEV virem}

#
# The Glow Quests
#
{1000}{}{Dostaò se do hlubin kráteru}
{1001}{}{Zneškodni všechny pasti}		#fo1 vanilla
{1002}{}{Obnov dodávku energie}			#fo1 vanilla

#
# L.A. Boneyard / Adytum Quests
#
{1100}{}{Staò se èlenem Blades}						#fo1 vanilla
{1101}{}{Doruèit medailon Romerovi}			#fo1 vanilla
{1102}{}{Doruèit zásilku od Gun Runnerù}	#fo1 vanilla
{1103}{}{Vypátrej špióna Dìtí Katedrály u Následovníkù}	#fo1 vanilla
{1104}{}{Opravit pro Adytum jejich hydroponickou farmu}		#fo1 vanilla
{1105}{}{Zachránit Jasona Zimmermana}				#fo1 vanilla
{1106}{}{Zastavit útoky gangù na Adytum}	#fo1 vanilla
{1107}{}{Zabij matku Páraèù}
{1108}{}{Pøesvìdèit Gun Runnery aby zásobovali Blades}
{1109}{}{Zbav se velitele mutantù v Nekropolisu.}
{1110}{}{RESERVED}
{1111}{}{RESERVED}

#
# Cathedral / Master's Vault Quests
#
{1200}{}{Získej pøístup do Vùdcova Vaultu}
{1201}{}{Pøesvìdè Rae aby ti pomohla proti Vùdci}
{1202}{}{Zabij Morpheuse}
{1203}{}{Zabij Vùdce}
{1204}{}{Spus odpoèítávání bomby}

#
# Caravan Run Quests
#
{1300}{}{Pomo vyloit karavanu}

#
# 
#
{1400}{}{RESERVED}
{1401}{}{RESERVED}
{1402}{}{RESERVED}
{1403}{}{RESERVED}

#
# 
#
{1500}{}{RESERVED}
{1501}{}{RESERVED}
{1502}{}{RESERVED}
{1503}{}{RESERVED}
{1504}{}{RESERVED}
{1505}{}{RESERVED}
{1506}{}{RESERVED}
{1507}{}{RESERVED}
{1508}{}{RESERVED}
{1509}{}{RESERVED}
{1510}{}{RESERVED}
{1511}{}{RESERVED}
{1512}{}{RESERVED}
{1513}{}{RESERVED}
{1514}{}{RESERVED}
{1515}{}{RESERVED}
{1516}{}{RESERVED}

#
# 
#
{1600}{}{RESERVED}
{1601}{}{RESERVED}
{1602}{}{RESERVED}

#
# 
#
{1700}{}{RESERVED}

#
# 
#
{1800}{}{RESERVED}

#
# 
#
{1900}{}{RESERVED}

#
# 
#
{2000}{}{RESERVED}

#
# 
#
{2100}{}{RESERVED}

#
# 
#
{2200}{}{RESERVED}

#
# 
#
{2300}{}{RESERVED}

#
# 
#
{2400}{}{RESERVED}

#
# 
#
{2500}{}{RESERVED}

#
# 
#
{2600}{}{RESERVED}

#
# Desert Encounter Quests
#
{2700}{}{RESERVED}

#
# Mountain Encounter Quests
#
{2800}{}{RESERVED}

#
# Ruined City Encounter Quests
#
{2900}{}{RESERVED}

#
# Coast Encounter Quests
#
{3000}{}{RESERVED}

#
# 
#
{3100}{}{RESERVED}

#
# 
#
{3200}{}{RESERVED}
{3201}{}{RESERVED}
{3202}{}{RESERVED}
{3203}{}{RESERVED}
