/*

   Classic Worldmap Mod - Add town titles to the green city circles

   TODO:
    - Needs Sfall command to override wm text shown under the green circle.
    - Just rewriting text in MAP.msg doesn't work, because then the Map AND Automaps screens won't have the town locations visible.

*/

/* Include Files */
#include "../headers/define.h"
#include "../headers/command.h"
#include "../headers/sfall/sfall.h"

procedure start;
procedure mark_locations;
procedure StdProcedure_handler;

procedure start begin
   if (game_loaded) then begin
      set_global_script_type(0);
      register_hook_proc(HOOK_GAMEMODECHANGE, mark_locations);
   end
end

procedure mark_locations begin
   if (get_game_mode == WORLDMAP) then begin
      if (town_known(AREA_VAULT_13) >= MARK_STATE_KNOWN) then
         set_town_title(00, "Vault 13");
      else
         set_town_title(00, "Unknown");

      if (town_known(AREA_VAULT_15) >= MARK_STATE_KNOWN) then
         set_town_title(01, "Vault 15");
      else
         set_town_title(01, "Unknown");

      if (town_known(AREA_SHADY_SANDS) >= MARK_STATE_KNOWN) then
         set_town_title(02, "Shady Sands");
      else
         set_town_title(02, "Unknown");

      if (town_known(AREA_JUNKTOWN) >= MARK_STATE_KNOWN) then
         set_town_title(03, "Junktown");
      else
         set_town_title(03, "Unknown");

      if (town_known(AREA_RAIDERS) >= MARK_STATE_KNOWN) then
         set_town_title(04, "Raiders");
      else
         set_town_title(04, "Unknown");

      if (town_known(AREA_NECROPOLIS) >= MARK_STATE_KNOWN) then
         set_town_title(05, "Necropolis");
      else
         set_town_title(05, "Unknown");

      if (town_known(AREA_HUB) >= MARK_STATE_KNOWN) then
         set_town_title(06, "Hub");
      else
         set_town_title(06, "Unknown");

      if (town_known(AREA_BROTHERHOOD) >= MARK_STATE_KNOWN) then
         set_town_title(07, "Brotherhood");
      else
         set_town_title(07, "Unknown");

      if (town_known(AREA_MILITARY_BASE) >= MARK_STATE_KNOWN) then
         set_town_title(08, "Military Base");
      else
         set_town_title(08, "Unknown");

      if (town_known(AREA_GLOW) >= MARK_STATE_KNOWN) then
         set_town_title(09, "Glow");
      else
         set_town_title(09, "Unknown");

      if (town_known(AREA_BONEYARD) >= MARK_STATE_KNOWN) then
         set_town_title(10, "Boneyard");
      else
         set_town_title(10, "Unknown");

      if (town_known(AREA_CATHEDRAL) >= MARK_STATE_KNOWN) then
         set_town_title(11, "Cathedral");
      else
         set_town_title(11, "Unknown");

      if (town_known(AREA_CAR_OUTTA_GAS) >= MARK_STATE_KNOWN) then
         set_town_title(21, "Bike Outta Gas");
      else
         set_town_title(21, "Unknown");

      if (town_known(AREA_SPECIAL_RND_FOOT) >= MARK_STATE_KNOWN) then
         set_town_title(53, "Special");
      else
         set_town_title(53, "Unknown");
      if (town_known(AREA_SPECIAL_RND_TARDIS) >= MARK_STATE_KNOWN) then
         set_town_title(54, "Special");
      else
         set_town_title(54, "Unknown");
      if (town_known(AREA_SPECIAL_RND_USEDCAR) >= MARK_STATE_KNOWN) then
         set_town_title(55, "Special");
      else
         set_town_title(55, "Unknown");
      if (town_known(AREA_SPECIAL_RND_COLATRUK) >= MARK_STATE_KNOWN) then
         set_town_title(56, "Special");
      else
         set_town_title(56, "Unknown");
      if (town_known(AREA_SPECIAL_RND_FSAUSER) >= MARK_STATE_KNOWN) then
         set_town_title(57, "Special");
      else
         set_town_title(57, "Unknown");
      if (town_known(AREA_SPECIAL_RND_TALKCOW) >= MARK_STATE_KNOWN) then
         set_town_title(58, "Special");
      else
         set_town_title(58, "Unknown");
      if (town_known(AREA_SPECIAL_RND_TEMPLE) >= MARK_STATE_KNOWN) then
         set_town_title(59, "Special");
      else
         set_town_title(59, "Unknown");

      if (town_known(AREA_SCRAPHEAP) >= MARK_STATE_KNOWN) then
         set_town_title(60, "Scrapheap");
      else
         set_town_title(60, "Unknown");

      if (town_known(AREA_SHADY_CAVES) >= MARK_STATE_KNOWN) then
         set_town_title(61, "Caves");
      else
         set_town_title(61, "Unknown");
      if (town_known(AREA_HUB_FARM) >= MARK_STATE_KNOWN) then
         set_town_title(62, "Farm");
      else
         set_town_title(62, "Unknown");
      if (town_known(AREA_HUB_LAIR) >= MARK_STATE_KNOWN) then
         set_town_title(63, "Lair");
      else
         set_town_title(63, "Unknown");
   end
end
