{100}{}{Tu vois une vieille dame.}
{101}{}{Tu vois Agatha.}
{102}{}{Cette femme est ridée et grise, elle a encore de l'esprit et une forte personnalité.}
{103}{}{Tu es quelqu'un de mauvais. Je n'ai rien à dire aux gens comme toi.}
{104}{}{C'est vraiment inquiétant lorsque les jeunes sont menacés. La perte de Tandi serait une chose terrible.}
{105}{}{Gnné.}
{106}{}{D'accord.}
{107}{}{Pourquoi ?}
{108}{}{Que veux-tu dire ?}
{109}{}{Je sais que tu feras de ton mieux, mon enfant. Trouve Tandi, aide-la à se sauver et ramène-la à Aradesh. Tu ferais une énorme faveur à cette communauté et cela te rendrait populaire parmi nous.}
{110}{}{Aradesh aime sa fille plus que tout. C'est cet amour qui a fait de lui un pilier de cette communauté. Sans cet amour il serait perdu, et les Sables Ombragés seraient les suivants certainement..}
{111}{}{Je ferai de mon mieux. Au revoir.}
{112}{}{Je pourrais avoir besoin d'aide.}
{113}{}{Hmmm. Nous verrons bien.}
{114}{}{J'ai le sentiment qu'elle est emprisonnée. Elle était la cible du mal, tu sais. Ce mal est très puissant au Sud-Est. Je suis certain que tu la trouveras là-bas. Bonne chance.}
{115}{}{Merci.}
{116}{}{Tu n'est pas au courant ? Tandi a disparue. Je pense qu'elle a été kidnappée, Aradesh est le plus affecté. C'est un grand malheur pour nous..}
{117}{}{J'ai entendu dire que tu avais sauvé Tandi. C'était la bonne chose à faire. Ton karma est puissant, j'ai beaucoup d'espoir en toi pour l'avenir.}
{118}{}{Je suis vraiment triste pour Tandi. C'était une jeune femme si charmante. Elle aurait fait le bien dans sa vie.}
{119}{}{Bonjour. Tu dois être l'étranger dont tout le monde parle. [Agatha soupire.] Comment puis-je t'aider ?}
{120}{}{Hgnné ?}
{121}{}{Qui es-tu ?}
{122}{}{Tu sembles si fatiguée. Quelque chose ne va pas ?}
{123}{}{Pourquoi tu sembles si fatiguée ?}
{124}{}{Ne me parle pas, la vieille.}
{125}{}{Tu as plus besoin d'aide que ce que je peux t'apporter, mon enfant. Que Dharma soit avec toi.}
{126}{}{Mon nom est Agatha. Je suis la conteuse des Sables Ombragés. C'est mon travail de garder la mémoire de ce village et de raconter des histoires pour que personne ne les oublie.}
{127}{}{Raconte-moi une histoire.}
{128}{}{D'accord, comme tu veux.}
{129}{}{C'est une bonne chose de ne pas oublier.}
{130}{}{Je suis désolée mon enfant, je suis fatiguée maintenant. Je dois me reposer. Reviens plus tard.}
{131}{}{C'est tout à fait juste. [Agatha te dévisage pendant un moment.] C'est une bonne chose que les jeunes se souviennent, mais c'est très difficile d'agir avec le poids de l'histoire. Parfois, les chemins que nous prenons ont été déterminés par des événements très anciens. Que Dharma soit avec toi. Je dois me reposer un peu. Reviens plus tard, quand ça ira mieux, nous parlerons encore.}
{132}{}{C'est gentil de demander. Je suis vieille c'est tout. J'ai du mal à dormir la nuit. Je ferme les yeux... [Agatha marque une pause.] Mais je ne me repose pas pour autant. Tu sais, c'est juste mes vieux os qui me font mal..}
{133}{}{Je suis désolée, je suis vraiment fatiguée. Pourrais-tu revenir plus tard ?}
{134}{}{Au r'voir.}
{135}{}{D'accord.}
{136}{}{Pourquoi es-tu si fatiguée ?}
{137}{}{Je ne dors pas très bien la nuit, mon enfant. Cela doit être à cause de mon âge.}
{138}{}{Bonjour. Tu sembles en forme. Tu me rappelles un de mes propres enfants.}
{139}{}{Arreuh.}
{140}{}{Je suis là pour une histoire.}
{141}{}{Je suis heureux de voir que tu te sens mieux.}
{142}{}{Merci. Salut.}
{143}{}{Tu me rappelles vraiment un de mes bébés. Quand elle était âgée de quelque mois, cependant.}
{144}{}{Merci. Dharma dit que le fermier qui fait pousser la politesse, pourra vivre heureux à la fin de la saison.}
{145}{}{S'il te plaît, raconte-moi une histoire.}
{146}{}{Ce Dharma a tout l'air d'un idiot.}
{147}{}{Tu insultes les anciens. Je n'ai plus rien à te dire.}

#Fo1in2
{200}{}{Very well then ... [You sit down and listen to Agatha's story for a while]}

