{100}{}{Voici un Chevalier.}
{101}{}{L'étude se trouve juste là, si c'est ce que tu cherches.}
{102}{}{As-tu perdu ton chemin ? L'étude est juste là.}
{103}{}{Le laboratoire médical est juste au coin.}
