{100}{}{L'étagère est remplie de livres religieux et philosophiques entièrement recouverts de poussière.}
{101}{}{Tu prends un livre pour l'examiner, puis tu le remets rapidement en place. L'étagère semble particulièrement robuste.}
{102}{}{Tu découvres un levier dissimulé.}
{103}{}{Ca n'a aucun effet.}
{104}{}{Le mur à côté de l'étagère s'écarte doucement en glissant sur lui-même.}
{105}{}{Tu fouilles un moment la bibliothèque sans rien trouver.}
{200}{}{L'étagère est remplie de livres religieux et philosophiques.}
{201}{}{Le levier ne veut pas bouger.}

# Fo1in2
{202}{}{ finds a hidden latch.}
{203}{}{ fumbles with the bookcase for a moment but fails to accomplish anything.}
