{100}{}{Tu vois l'assistante du Docteur.}
{179}{}{Tu devrais aller voir le Docteur.}
{180}{}{C'est elle le Docteur, pas moi.}
{181}{}{Je suis encore en stage, ici.}
{182}{}{Officiellement, je peux pas t'aider.}
{183}{}{Lorri est le Docteur.}
{184}{}{Tu devrais demander au Docteur.}
{185}{}{Ne t'inquiète pas, elle fait ça exprès.}
{186}{}{Elle aime bien taquiner les gens, c'est tout.}
