{100}{}{Voici un employé des Caravanes Ecarlates.}
{101}{}{Voici un employé des Marchands d'Eau.}
{102}{}{Voici un employé des Marchands du Lointain.}
{103}{}{Bonjour. Tu cherches du travail ?}
{104}{}{Oui.}
{105}{}{Non.}
{106}{}{Formidable. Nous cherchons un nouveau garde. Cela t'intéresse ?}
{107}{}{Ok. Si t'as besoin de travail, passe et nous verrons ce que nous pouvons faire.}
{108}{}{Tant pis. Salut.}
{109}{}{Formidable. Nous avons des caravanes à destination : du Cimetière, de Dépôtville, de Nécropolis et de la Confrérie de l'Acier. Pour laquelle veux-tu travailler ?}
{110}{}{Formidable. Nous avons des caravanes à destination : du Cimetière, de Dépôtville et de la Confrérie de l'Acier. Pour laquelle veux-tu travailler ?}
{111}{}{Formidable. Nous avons des caravanes à destination du Cimetière et de Dépôtville. Pour laquelle veux-tu travailler ?}
{112}{}{Le Cimetière.}
{113}{}{Dépôtville.}
{114}{}{La Confrérie de l'Acier.}
{115}{}{Nécropolis.}
{116}{}{Aucune.}
{117}{}{Parfait. Allons-y.}
