{100}{}{Voici un petit enfant.}
{101}{}{Salut !}
{102}{}{Bonjour.}
{103}{}{Où sont tes parents ?}
{104}{}{Beuh.}
{105}{}{Ché pas. Quelque part par là.}
{106}{}{Tu es drôle !}
{107}{}{Hé, tu vas tuer quelqu'un ?}
{108}{}{Oui.}
{109}{}{Non !}
{110}{}{Ahhh.}
{111}{}{J'vais l'dire à ma maman !}
{112}{}{Alors tu devrais pas porter ton arme comme ça}

{980}{}{Hein ?}
{981}{}{Ché pas. Demande à ma maman.}
{982}{}{Demande à mon papa.}

# Shady Sands kids
{1000}{}{Griffemort|GRIFFEMORTS|GRIFFE|GRIFFES|MORT}
{1001}{}{Pillards|Pillard}
{1002}{}{Dépôtville|Dépot Ville|Dépotville}
{1003}{}{Brahmine|Brahmin}
{1004}{}{Puce|Puce eau|Puce d'eau}
{1005}{}{Marchands}
{1006}{}{Khans|Khan}
{1007}{}{Garl}
{1008}{}{Sables Ombragés|Sables|Ombragés}
{1009}{}{Centre|Le Centre}
{1010}{}{Tandi}
{1011}{}{Aradesh|Chef}
{1012}{}{Seth|Set}
{1013}{}{Razlo|Docteur|Doc}

{1100}{}{Ouah ! Un monstre cauchemardesque !}
{1101}{}{Méchants !}
{1102}{}{Je sais pas.}
{1103}{}{Des gros trucs qui puent.}
{1104}{}{Demande à ma maman.}
{1105}{}{Drôles de chants de marins.}
{1106}{}{Méchants !}
{1107}{}{Sale type.}
{1108}{}{J'te l'dirai pas.}
{1109}{}{Grande ville.}
{1110}{}{J'te l'dirai pas.}
{1111}{}{Non, j' te dirai rien.}
{1112}{}{Ma maman veut pas que je parle de lui.}
{1113}{}{Mon papa trouve qu'il est bizarre.}

# Hub kids
{2000}{}{Police|Gardes|Garde}
{2001}{}{Caravanes|Caravane}
{2002}{}{Marchands}
{2003}{}{Enfants|Enfant}
{2004}{}{Nécropolis}
{2005}{}{Le Rayon|Rayon}
{2006}{}{Confrérie|Confrérie de l'Acier|CDA|Confrérie Acier}
{2007}{}{Cimetière}
{2008}{}{Tours}
{2009}{}{Ville|La Ville}
{2010}{}{Centre-ville}
{2011}{}{Hauteurs|Les Hauteurs}
{2012}{}{Le Cimetière}
{2013}{}{Cimetière de L.A.}

{2100}{}{Des grands.}
{2101}{}{Il y a cette puanteur qui les attire.}
{2102}{}{Ils sont gentils. Ils me donnent des bonbons.}
{2103}{}{Ils aiment pas jouer à cache-cache.}
{2104}{}{Un endroit effrayant.}
{2105}{}{Un endroit dégoûtant.}
{2106}{}{Un endroit effrayant.}
{2107}{}{Un endroit effrayant.}
{2108}{}{Maman ne nous laissera pas jouer là.}
{2109}{}{Papa nous dit tout le temps de jouer là.}
{2110}{}{Un endroit pour les grands.}
{2111}{}{Un endroit pour les grands.}
{2112}{}{Un endroit effrayant.}
{2113}{}{Un endroit effrayant.}


# Fo1in2
# Razlo's kids
{300}{}{Papa est juste là ! Tu le vois pas ?}
{301}{}{Maman est juste là ! Tu la vois pas ?}
