{100}{}{Tu fermes la plaque d'égout.}
{101}{}{Tu ouvres la plaque d'égout et tu essaies de percer l'obscurité. Tu vois une échelle qui mène aux égouts.}
{102}{}{Tu forces, mais la plaque métallique est trop lourde pour ta faible constitution physique. Tu ressens un craquement dans le dos.}
{103}{}{La plaque d'égout est lourde et difficile à soulever.}
