{100}{}{Le générateur a été saboté. Il ne fonctionne plus.}
{101}{}{Voici un générateur d'énergie. C'est la seule source d'énergie de Tas-de-Ferraille.}
{102}{}{Tu coupes quelques fils du transformateur. Le générateur ne fonctionne plus.}
{103}{}{Les coupe-circuits n'ont plus d'utilité.}
{104}{}{Cet objet n'a plus d'effet sur le générateur.}
{105}{}{Le générateur te semble tout à fait normal.}
{106}{}{Le générateur semble protégé ; mais tu aperçois un ensemble de fils entre le transformateur et le générateur.}
{107}{}{Ce gros générateur te semble tout à fait normal.}
{108}{}{Tu ne peux rien savoir de plus sur le générateur.}
{109}{}{Les fils peuvent être réparés, mais cela peut prendre du temps, et le résultat n'est pas garanti.}
{110}{}{Le générateur endommagé te semble tout à fait normal.}
{111}{}{Tu ne peux rien réparer de plus.}
{112}{}{Inutile de réparer le générateur. Il fonctionne très bien.}
{113}{}{Tu ne peux pas réparer le générateur puisqu'il fonctionne bien.}
{114}{}{Tu répares le générateur même si cela te prend des heures. Lorsque le courant est rétabli et que les bandes ont déserté les lieux, les habitants de la ville te sont reconnaissants. Ils te donnent des renseignements précieux. Ta mission à Tas-de-Ferraille est terminée. Ta quête de la puce d'eau suit son cours.}
{115}{}{Tu ne peux pas réparer le générateur. Les habitants de Tas-de-Ferraille vivront dans la misère sans cette énergie ; mais les bandes ayant déserté les lieux, ils pourront au moins mener leur existence comme ils l'entendent. Ce que tu avais à faire à Tas-de-Ferraille est terminé. Ta mission consistant à trouver la puce d'eau suit son cours.}
{116}{}{Les manipulations n'ont aucun effet sur le générateur.}
{117}{}{Cette compétence n'a aucun effet sur le générateur.}
{118}{}{Le générateur fonctionne déjà.}
{119}{}{Impossible de démarrer le générateur : il est en panne.}
