# Taken from ALLDOGS.msg to make unique strings for Dogmeat.
{100}{}{Tu vois un chien. On dirait qu'il te suit.}
{101}{}{Tu vois un chien.}
{102}{}{Ouaf !}
{103}{}{Grrr !}
{110}{}{Tu vois : Canigou.}

{117}{}{Ouaf-Ouaf !}
{118}{}{Ruff. Ruff.}
{119}{}{Ouaf !}
{120}{}{Wouf ?}

{200}{}{Je pense que nous devrions discuter de la distance.}
{201}{}{En fait je pense que tu es à bonne distance pour le moment.} 

# Too many party members
{2500}{}{Grrrrr.}
{2510}{}{Qu'y a-t-il ? Tu n'aime pas trop la compagnie, hein ?}
{2511}{}{[Fait]}

# Fo1in2
{3500}{}{*Chouine*}
{3501}{}{Aouuuuuuu ! *chouine*}
{3502}{}{}

