# Fo1in2
{100}{}{Tu vois: Un Eyebot.}

# Message log entries from investigating and using skills
{150}{}{Le robot est éteint.}
{151}{}{non utilisé}
{152}{}{Les batteries intégrées sont mortes et doivent être remplacées.à}
{153}{}{On dirait que le robot est relié au système d'alimentation du Rayon. Il ne peut pas fonctionner à l'extérieur.}
{154}{}{Tu n'as aucune idée de ce qui ne fonctionne pas avec ce robot.}
{155}{}{Les actuateurs du robot sont complètement erratiques. Tu ne peux pas les inspecter.}
{156}{}{On dirait que les capteurs sont défectueurs.}
{157}{}{non utilisé}
{158}{}{On dirait que le robot est relié au système d'alimentation du Rayon. Il ne peut pas fonctionner à l'extérieur.}
# You gain x ...
{159}{}{ points d'expériences pour avoir réparé les capteurs du robot.}
{160}{}{Tu n'arrives pas à réparer les capteurs du robot.}
{161}{}{Tu penses pouvoir utiliser un cellule à microfusion pour en faire une batterie de rechange.}
# You gain x ...
{162}{}{ points d'expérience pour avoir remplacé la batterie d'origine par une celulle à microfusion.}
{163}{}{Le robot ne sera pas aussi efficace qu'il y a 100 ans, mais il fonctionne.}
{164}{}{Tu n'as aucune idée de ce que tu fais et tu fini par détruire complètement le robot.}
{165}{}{Tu échoues à fabriquer une batterie improvisée.}

# Dialog after fixing the robot
{200}{}{[Clic] ERREUR SYSTEME. [Bip] L'unité ne peut pas traiter la dernière tâche. Le gestionnaire des tâches ne répond plus. Quels sont les ordres ?}
{201}{}{Tu me comprends ?}

{202}{}{Module de voix connecté. Système nominal. Quels sont les ordres ?}
{203}{}{Quelle est ta dernière tâche ?}

{204}{}{Accès à la pile des tâches ... Dernière tâche : Paramètre de sécurité. Tâche annulée après de nombreuses fluctuations énergétiques. Batterie surchargée. Composants matériels endommagés.}
{205}{}{Quel est le statut ?}

{206}{}{Etat général : OK ... Statut de la batterie : Mauvais ... Connection au réseau local : BONNE ... Système de combat : Opérationel.}
{207}{}{Tu veux me suivre ?}

{208}{}{Tâche suivante : NEGATIF. Pile de tâche pleine. Quels sont les ordres ?}
{209}{}{Nettoyer le disque dur.}

{210}{}{Traitement. Veuillez patienter ... [Bip]}
{211}{}{Redémarrage système. Veuillez patienter ... [Bip]}
{212}{}{[Clic] SYSTEME ACTIVE ... MEMOIRE PLEINE A 39% ... Tous les systèmes sont opérationels. Quels sont les ordres ?}
{213}{}{Suis moi.}

{214}{}{Euuh ... Et si je te tapais un peu dessus ?}
{215}{}{ERREUR. [Bip] Redémarrage système. Veuillez patienter.}
{216}{}{(Tu frappe le robot, mais rien ne se passe)}
{217}{}{Bon, au moins j'aurais essayé.}

# Repair partymember dialog
{900}{}{L'Eyebot ne peut plus être réparé pour le moment.}
{901}{}{L'Eyebot a été un peu réparé.}
{902}{}{L'Eyebot est entièrement réparé.}

# Primary party dialog
{1000}{}{Initialisation des paramètres.}
{1001}{}{}
	{1014}{}{Tu devrais effectuer une maintenance sur toi-même.}
	{1015}{}{Nous devons parler de ce que tu sais faire.}
	{1020}{}{Parlons de notre formation.}
	{1030}{}{Ok, merci.}
	{1040}{}{Suis-moi, j'ai besoin de ton aide à nouveau.}
	{1050}{}{[Terminé]}
	{1060}{}{Sans importance.}

{1004}{}{Traitement des ordres ...}
{1005}{}{Calibration des paramètres.}
{1006}{}{Calibration ...}

{1007}{}{Tâches ?}
{1008}{}{Tâches ?}
{1009}{}{Confirmé.}
{1010}{}{[Bip] L'unité #462 peut réaliser les remplacements de noyaux nucléaires, le nettoyage des matières dangereuses, le nettoyage des radiations, les procédures de réparation mécanique de base et la promenade du chien.}
{1011}{}{[Bip] L'unité #462 est programmé pour utiliser les armes à énergie ou les miniguns.}

{1100}{}{Cet Eyebot est entièrement réparé et prêt à partir.}
{1200}{}{Etat général : Bon. Aucune réparation est nécessaire.}
{1300}{}{Etat général : Endommagé. Suggestion de réparation additionelles dans un futur proche.}
{1400}{}{Etat général : Mauvais. Suggestion de réparation additionelles additional repairs in the near future.}
{1401}{}{Etat de la batterie : Correct.}
{1402}{}{Etat de la batterie : Excellent.}

{1500}{}{Nous devrions rester ensemble.}
{1501}{}{Confirmé. En attente.}
{1600}{}{Confirmé.}
{1700}{}{Mode de formation rapprochée confirmée.}
{1800}{}{Mode de formation en distance légère confirmée.}
{1900}{}{Mode de formation en distance éloignée confirmée.}

# Too many party members
{2000}{}{La tâche a échouée. ERREUR: Capteurs saturés. Taille du groupe trop élevée. En attente.}
{2001}{}{Tâche confirmée. Annulation de l'attente.}
{2002}{}{Chargement ... Tâche récursive crée ... Arrêt des commandes.}
	{2010}{}{Oh d'accord, comme tu voudras.}

{3500}{}{Etat général : Endommagé. Réparations requises.}
