{100}{}{Pompe à hydropressurisation, fil métallique électro-fibreux, protection de vide magnétique, courroie d'alimentation, adaptateurs trois broches... une vraie collection de pièces détachées.}
{101}{}{Miles pourrait sans doute utiliser ces pièces détachées pour réparer les fermes hydroponiques.}
