{100}{}{Tu déverrouilles la porte.}
{101}{}{Sans le faire exprès, tu bloques le verrou de la porte.}
{102}{}{Tu n'arrives pas à ouvrir ce verrou.}
{103}{}{Tu n'as pas réussi à crocheter le verrou.}
{104}{}{La porte est verrouillée.}
{105}{}{La porte est déverrouillée.}
