{100}{}{Ce terminal semble avoir été détruit par l'explosion.}
{101}{}{Cet ordinateur semble avoir pu mémoriser des méga-octets de données.}
{102}{}{Tu te demandes quel genre de données a pu contenir cet ordinateur.}
{103}{}{On dirait que cet ordinateur était connecté à un grand système.}
