{100}{}{Tu vois un générateur.}
{101}{}{Les générateurs sont en marche.}
{102}{}{Ces générateurs semblent déconnectés. Tu te demandes s'il est possible de les redémarrer.}
{103}{}{Ces générateurs sont déjà en marche.}
{104}{}{Tu démarres les générateurs et tous les systèmes semblent se reconnecter.}
{105}{}{Tu n'arrives pas à démarrer les générateurs.}
{106}{}{Tu ne sais pas comment réparer ce système.}

###Reaching LVL5 exp msg, by Sduibek, for Fallout Fixt
{107}{}{Tu entends un bourdonnement mécanique constant, cela te rappelle quelque chose mais tu ne sais plus quoi...}

