{100}{}{Un cadavre congelé.}
{101}{}{Il n'est manifestement pas d'origine terrestre.}
{102}{}{Ce corps pourrait bien résulter d'une quelconque expérience génétique.}
{103}{}{Quoi ? C'est un corps mort.}
{104}{}{Ce corps congelé est bizarre.}
