{100}{}{Voici Guido.}
{101}{}{Ah, t'utilises rien que la force. Il m'en faut pas tant pour faire la peau à quelqu'un.}
{102}{}{Ah, on s'en fout de la méthode ! On n'est pas des artistes, on est des professionnels. Euh, Léone, y'a quelqu'un qu'essaie de nous causer. C'est pas prévu qu'on tue dans ces cas-là ?}
{103}{}{Ah, t'utilises rien que la force. Il m'en faut pas tant pour faire la peau à quelqu'un.}
{104}{}{J'suis pas payé pour causer.}
{105}{}{Ah, on s'en fout de la méthode ! On n'est pas des artistes, on est des professionnels. Euh, Léone, y'a quelqu'un ici qu'essaie de nous causer. C'est pas prévu qu'on tue dans ces cas-là ?}
{106}{}{Ah, t'utilises rien que la force. Il m'en faut pas tant pour faire la peau à quelqu'un..}
{107}{}{Ah, on s'en fout de la méthode ! On n'est pas des artistes, on est des professionnels. Euh, Léone, y'a quelqu'un qu'essaie de nous causer. C'est pas prévu qu'on tue dans ces cas-là ?}
