{100}{}{Voici Jacob, le marchand d'armes.}
{101}{}{Salut ! Bienvenue chez Jake. J'ai de belles choses en magasin. Faut pas hésiter à jeter un coup d'oeil.}
{102}{}{Je voudrais faire un marché avec toi.}
{103}{}{Qu'est-ce que tu vends ici ?}
{104}{}{Est-ce que tu as entendu parler d'une puce d'eau ?}
{105}{}{Parle-moi un peu de toi.}
{106}{}{Laisse tomber. Salut.}
{107}{}{vEux.}
{108}{}{vEux pAs.}
{109}{}{Je vends des armes de haute volée. Ce qui se fait de mieux de ce côté-ci de la ville, et vu que la Confrérie refuse de traiter avec les étrangers, je peux dire que je suis le meilleur. J'ai un fusil d'embuscade et tu peux toujours courir pour trouver du carburant pour lance-flammes ailleurs dans le désert. Ah, ouais... J'ai aussi un compteur Geiger. Une pièce rare.}
{110}{}{Montre-moi ce que tu as.}
{111}{}{Parle-moi de ton fusil d'embuscade.}
{112}{}{Pour quoi faire un compteur Geiger ?}
{113}{}{On verra plus tard. Salut.}
{114}{}{L'ami, t'aimes les choses rares ! Où t'étais quand je vendais des balles d'uranium appauvri ? Pourtant, j'ai rien niveau puces. Y'a jamais eu de demande. Rien d'autre ?}
{115}{}{Montre-moi ce que tu as.}
{116}{}{Alors, dis-moi ce que tu as.}
{117}{}{Parle-moi un peu de toi.}
{118}{}{Eh ben, j'ai pas mal roulé ma bosse. Autrefois, je faisais partie du Syndicat des Travailleurs de l'Atome. Un peu comme la Confrérie, mais en moins sympa. Ils voulaient rester entre eux... et moi, je voulais voir du pays et être mon propre patron, alors je l'ai quitté.}
{119}{}{Voyons ce que tu as.}
{120}{}{Dis-moi ce que tu as.}
{121}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{122}{}{Salut, l'ami. Je repasserai peut-être plus tard.}
{123}{}{Ahh, le DKS est une arme à longue portée de qualité. A l'origine, c'était un .308 mais on a trafiqué sa chambre pour pouvoir utiliser des balles .223. On a également adapté le canon. Mais le plus important... regarde-moi cette gâchette. Souple, non ? Elle marche à merveille maintenant. En clair, c'est ce qu'il y a de mieux pour tous types de chasse...}
{124}{}{Ca semble bien. Voyons si l'on peut conclure l'affaire.}
{125}{}{Pour quoi faire un compteur Geiger ?}
{126}{}{On verra peut-être plus tard. Salut.}
{127}{}{Pour quoi faire un compteur Geiger !? [Rires] Même si ça fait près de 80 ans que la bombe est tombée, il y a encore des radiations un peu partout, imbécile. On peut pas la voir mais elle est bien là. Je suis prêt à parier que tu en as pris une sacrée dose. C'est la même chose pour tout le monde ici dans le désert.}
{128}{}{Montre-moi ce que tu as à vendre.}
{129}{}{Parle-moi de ces radiations.}
{130}{}{Comment ça marche un compteur Geiger ?}
{131}{}{Imbécile ?! T'as l'habitude d'insulter tes clients ? Si tu crois que je vais te prendre quelque chose maintenant, là tu te plantes.}
{132}{}{Y'en a qui appellent ça le Fantôme de la Mort. Ils n'ont pas tort. Ca ne se voit pas, ça ne s'entend pas et ça ne sent rien. Ca s'accumule simplement dans ton système. Quand tu t'en rends compte, c'est déjà trop tard. Plus tu fréquentes les zones contaminées, plus elles radiations s'accumulent pour ne plus quitter ton système. Jamais. Les radiations ne cessent de s'accumuler. Enfin... à moins que tu ne mettes la main sur du RadAway.}
{133}{}{Voyons si on peut conclure l'affaire.}
{134}{}{Comment ça marche un compteur Geiger ?}
{135}{}{Où est-ce que je pourrais trouver du RadAway ? On n'en voit pas tous les jours en magasin.}
{136}{}{Ouah. T'en sais des choses. On voit que t'as roulé ta bosse.}
{137}{}{Merci pour le tuyau. Salut.}
{138}{}{En fait, c'est assez simple. Ca te permet de connaître ton niveau de contamination. Tout va bien tant que tu restes au-dessous de 100. Au-dessus de 100, les ennuis commencent. Le pire, c'est que tu ne sais pas si tu as pris des radiations avant plusieurs jours. Au-dessus de 1000, t'es cuit - à moins d'avoir un bon paquet de RadAway sous la main.}
{139}{}{Voyons si l'on peut conclure l'affaire.}
{140}{}{Qu'est-ce que tu peux me dire au sujet des radiations ?}
{141}{}{C'est pas à moi que tu la feras. Salut.}
{142}{}{Laisse tomber.}
{143}{}{}
{144}{}{vEut.}
{145}{}{Moi partir.}
{146}{}{Oui.}
{147}{}{Non. Je ne fais que jeter un oeil.}
{148}{}{Je ne veux pas d'ennuis. Si tu veux qu'on fasse affaire, allons-y. Sinon, va-t'en.}
{149}{}{Prendre.}
{150}{}{Moi partir.}
{151}{}{Voyons ce que tu as.}
{152}{}{Tu peux aller te faire foutre. Je vais où je veux quand je veux !}
{153}{}{Je m'en vais.}
{154}{}{Qu'est-ce tu fabriques ici ?!?!?}
{155}{}{Je m'en occupe pas. Dès que j'en trouve, je le garde pour moi. Juste en face, il y a quelqu'un qui pourrait peut-être t'aider. Il s'appelle Vance. Ne lui pose pas trop de questions. Disons juste que c'est dans son rayon d'expertise. Dis-lui que c'est Jacob qui t'envoie et je pense que ça ira.}
{156}{}{Comment ça marche un compteur Geiger ?}
{157}{}{Merci pour le tuyau. Salut.}
{158}{}{Voici ce que j'ai.}
{159}{}{Salut.}
{160}{}{Merci.}
{161}{}{Ok.}
{162}{}{Les mutants les ont chassés il y a 10 ans environ. C'est pour ça que je pense avoir fait le bon choix en venant m'installer ici. Les flics n'aiment pas trop mon business et j'ai été menacé plusieurs fois mais je suis sacrément plus honnête que n'importe quel autre commerçant ici.}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{163}{}{Hé, comment ça va l'ami ? Tu cherches à acheter quelque chose ?}
{164}{}{Hé, comment ça va l'amie ? Tu cherches à acheter quelque chose ?}
{165}{}{Tu as un choix excellent. Mais je recherche quelque chose avec davantage de punch. Sais-tu où je devrais aller ?}
{166}{}{Et bien, tu devrais essayer les Contrebandiers, au Cimetière de L.A. Ils ont peut-être ce que tu cherches. J'ai aussi entendu dire que les mecs de la Confrérie de l'Acier proposent du matériel assez puissant. Tu devrais passer les voir aussi.}

# Fo1in2
# Upgrade Weapons
	{1999}{}{Tu peux modifier ou améliorer une arme ?}

{2000}{}{Bien sûr que je peux. Tu as quoi ?}
{2001}{}{Bien sûr que je peux, mais tu n'as rien que je puisse améliorer. Amène moi des fusils ou des pistolets euh.. "normaux" et nous pourrons t'aider.}
	{2010}{}{Tu peux faire quelque chose avec ces pistolets ?}
	{2020}{}{Un de mes fusil pourrait avoir besoin d'amélioration.}
	{2025}{}{Tu peux améliorer mon lance-flammes ?}
	{2030}{}{Que peut-tu faire avec cet aiguillon à bétail ?}
	{2040}{}{Non rien. J'aimerai te parler d'autre chose...}
	{2050}{}{En fait non, rien aujourd'hui.}

{2100}{}{Montre-moi ce que tu as.} # unused
	{2110}{}{En fait, pourrais-tu améliorer une autre arme à la place ?}
	{2120}{}{Non rien. J'ai besoin d'autre chose...}
	{2130}{}{En fait aucune. Je dois y aller.}
	{2140}{}{Trop cher pour moi. Je reviendrais quand j'aurais plus d'argent.}

# Pistols
{2200}{}{Nous pouvons ajouter un rechargement rapide sur ce magnum pour }
{2201}{}{Ce Desert Eagle que tu as... si tu veux, nous pouvons y ajouter une extension de chargeur pour }
{2202}{}{ caps.}
{2203}{}{Oh wow, I see you have a Mauser M/96 there! Not easy to get ammo for that nowadays. If you want, I can convert it to 10mm for }
	{2210}{}{Mettez un chargeur rapide sur le Magnum.}
	{2220}{}{Augmentez la taille du chargeur de ce Desert Eagle.}
	{2230}{}{Convert the Mauser to 10mm.}

# Rifles
{2300}{}{Nous pouvons mettez une lunette sur ce fusil de chasse pour }
{2301}{}{Ce fusil d'assaut que tu as... Nous pouvons augmenter la taille du chargeur pour }
{2302}{}{J'ai une lunette de vision de nuit pour ton fusil d'assaut amélioré pour }
{2303}{}{Ton fusil de combat... Je peux y mettre un chargeur tambour pour }
	{2310}{}{Très bien alors... Mettons une lunette sur ce fusil de chasse.}
	{2320}{}{Augmenter la taille du chargeur pour le fusil d'assaut AK-112.}
	{2330}{}{Mettre un viseur de nuit sur l'AK-198.}
	{2340}{}{Ajouter un chargeur tambour à ton Winchester City-Killer.}

# Melee
{2400}{}{Tu veux booster un peu ton aiguillon à bétail ? Nous pouvons le Sur-alimenter pour }
{2410}{}{D'accord.}

# Big Guns
{2500}{}{Laisse moi regarder... Oui nous pouvons faire quelque chose pour }
{2510}{}{Cool. Faisons ça.}

{2600}{}{Attends ici.}
{2601}{}{Et voilà. Autre chose ?}
