# Chris Avellone is a male bounty hunter. He has an abrupt attitude and is serious about
# his money. He does not like child killers (which is the only way the player will meet him).

{100}{}{Voici un chasseur de primes très costaud avec une pancarte où l'on peut lire, "Je suis Christopher et tu es mon bifteck".}
# Bounty Hunter is considered Male term

{101}{}{Qu'est-ce que tu veux ?}
{102}{}{Un beignet.}
{103}{}{Qu'est-ce que tu fais ici ?}
{104}{}{Je me promène.}
{105}{}{Rien.}
{106}{}{Ici, on n'aime pas trop ceux qui se la jouent. Décampe.}
# Alternate for "Buzz off" could be "Get lost" or "Get out of here"

{107}{}{Cette blague n'était déjà pas marrante la première fois. Tu es sur le point de découvrir pourquoi je suis l'un des chasseurs de primes les plus craints du désert. Et je me ferai même pas payer pour ça !}
{108}{}{C'est pas tes oignons.}
{109}{}{Bon, va voir ailleurs si j'y suis.}
# Alternate for "poke around" could be "Look around"

{110}{}{Tu savais que ta tête a été mise à prix pour }
{200}{}{ caps, pour avoir assassiné des enfants ? C'est le moment de rafler la mise !}
# Children is considered male plural

{111}{}{[Christopher te regarde avec attention, envisageant quelque chose... on dirait qu'il vient de prendre une décision] Dis-moi, à quel rythme rends-tu visite au Centre ou à Dépotville ?}
{112}{}{Assez souvent, pourquoi cette question ?}
{113}{}{Et bien, tu vois... Le travail m'occupe presque à plein temps et je n'ai aucune opportunité pour me rendre là-bas. Et en tant que fumeur invétéré, un bon vieux briquet Zippo me manque terriblement. On dit que de nombreux objets d'avant-guerre peuvent se trouver dans les magasins là-bas. Si tu me rapportes un Zippo, je partagerai avec toi des informations au sujet des bases voisines. Je pense que cela pourrait t'être utile !}
{114}{}{Quel dommage. On dirait que je me suis trompé sur ton compte. Dégage de là.}
{115}{}{Pourquoi pas, je t'en trouverai un.}
{116}{}{Ok.}
{117}{}{Hé, j'en ai justement un ici. J'en ai pas vraiment besoin et je peux te le donner en échange d'informations.}
{118}{}{Merci ! [Il prend le briquet] Donc, qu'as-tu besoin de savoir, exactement ?}
{119}{}{Voici ton briquet. Il est temps de me donner des informations.}
{120}{}{Pas d'autres questions, merci.}
{121}{}{[SUITE]}
{122}{}{Que veux-tu savoir d'autre ?}
{123}{}{Je cherche des informations.}
{124}{}{beuuh.. que ?}
{125}{}{T'es sérieux ? Hors de ma vue !}
{126}{}{Je vais rendre service au monde en te logeant une balle dans le crâne !}
#
# Tell-Me-Abouts
{970}{}{That is my name.}
{971}{}{You are talking to me.}
{972}{}{That's me.}

{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}

{1000}{}{Adytum|Adytown}
{1001}{}{Followers|Apocalypse|Followers of the Apocalypse|FoA}
{1002}{}{Children of the Cathedral|Children|Cathedral|CoC}
{1003}{}{Rippers|Ripper}
{1004}{}{Blades|Blade}
{1005}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{1006}{}{Hub}
{1007}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{1010}{}{Junktown|Junk Town}
{1011}{}{Nicole}

{1110}{}{A small town to the south. Occasionally some of them visit.}
{1111}{}{Those are the peace-loving freaks who live near us.}
{1112}{}{A strange cult south of Adytum and in the Boneyard. Nicole says that they are up to something.}
{1113}{}{An ultra-violent gang to our west. It was, at least... I don't really know what happened but their base is swarming with Deathclaws now.}
{1114}{}{A gang to the east. They use vibro-knives.}
{1115}{}{A gang that came from the Hub, and sells guns. They are north of here.}
{1116}{}{The Hub is a large city of traders and businesses to the east.}
{1117}{}{This place is the Angel's Boneyard, the remnants of the old city of Los Angeles.}
{1120}{}{Junktown is a small city just north of the Hub.}
{1121}{}{She's the leader of the Followers.}
