{100}{}{Voici un technicien. Il travaille d'arrache-pied pour l'Unité et le Maître.}
{101}{}{Nous faisons le travail du Maître.}
{102}{}{Nous faisons le travail du Maître ! Personne ne peut noue interrompre !}
{103}{}{Maître ! Une intrusion !}
{200}{}{Voici Vicieux, un chef des super mutants. Il a l'air déplaisant.}
{201}{}{Voici un super mutant à l'air déplaisant.}
{202}{}{Que la volonté du Maître règne ! Quelles nouvelles me rapportes-tu ?}
{203}{}{Beuf !}
{204}{}{Euh, la guerre se passe bien.}
{205}{}{J'ai un message pour le Maître de la part de son Lieutenant. Je dois voir le Maître sur-le-champ.}
{206}{}{Les seules nouvelles, c'est que tu vas pas tarder à faire de l'engrais.}
{207}{}{Une intrusion !}
{208}{}{Qui que tu sois, tes manières te trahissent. Ta menace a assez duré !}
{209}{}{Tu plaisantes certainement. Ou plutôt, tu mens !}
{210}{}{Euh, ouais, et alors ?}
{211}{}{Mais non. Le Lieutenant n'a pas voulu transmettre ce message par les voies habituelles. Je dois voir le Maître sur le champ ! C'est urgent !}
{212}{}{Bon, passe par la porte, et fais attention au Couloir. Je suppose que tu as ta protection en place ?}
{213}{}{Bien sûr. Merci. Que l'Unité règne !}
{214}{}{Non, pas vraiment. Il faut ?}
{215}{}{Bien sûr ! Espère pas passer le corridor sans ça. Qu'est-ce que t'as fait de ton annulateur ?}
{216}{}{Je l'ai laissé dans mes autres robes.}
{217}{}{Le Lieutenant n'a pas eu le temps de m'en donner un.}
{218}{}{Ah, c'te bonne blague. [S'interrompt] J'en n'ai pas, ça se voit. Faut que t'ailles en chercher un au deuxième étage. Que l'Unité règne !}
{219}{}{Ou il a fait l'imbécile, ou tu n'es pas ce que tu parais être. Alors ?}
{220}{}{C'est évident, c'est un imbécile.}
{221}{}{La deuxiéme solution.}
{222}{}{File et poursuis ta mission. J'ai pas de temps à perdre avec toi.}
{300}{}{Il y a un petit tas de mégots dans le coin de la pièce.}
{301}{}{Le super mutant se dirige vers un côté de la pièce et allume une cigarette.}
{302}{}{Ce super mutant a une cigarette qui pendouille aux lèvres.}
{303}{}{Le super mutant jette le mégot dans le coin.}
