{100}{}{Voici Doc Morbide.}
{101}{}{Je suis Doc Morbide, je peux t'aider ?}
{102}{}{Oui, j'ai besoin d'aide.}
{103}{}{J'ai besoin de soins médicaux.}
{104}{}{Non, pas aujourd'hui.}
{105}{}{Beof.}
{106}{}{Ouais.}
{107}{}{Bon, d'accord. N'hésite pas à revenir.}
{108}{}{Bon, si c'est pas aujourd'hui, alors peut-être un de ces jours.}
{109}{}{J'espère que non. Au revoir.}
{110}{}{Faut voir, hein ? Mais, je crois pas.}
{111}{}{Hum, voyons voir ça.}
{112}{}{Tu me parais en parfaite santé. Bon, ça fera 10 caps pour la consultation.}
{113}{}{Dix caps pour que tu me dises ça ? Tu rigoles !}
{114}{}{Tiens. Prends ton argent.}
{115}{}{Je ne plaisante jamais. Surtout pour des traumatismes physiques. Tu débourses ou je devrai recourir à d'autres moyens de paiement... qui risquent de te coûter plus cher.}
{116}{}{D'accord, voilà ton argent.}
{117}{}{Rien à cirer. Je m'tire.}
{118}{}{Comme tu veux. Cougar, Flash ! Conduisez notre "patient" au labo.}
{119}{}{Merci pour ta confiance. N'hésite pas à revenir.}
{120}{}{T'as pas assez d'argent. Les débiteurs ont droit à un traitement très spécial... Flash, Cougar ! Emmenez notre nouvelle source de revenu au labo et appliquez le traitement.}
{121}{}{D'accord, j'ai tes résultats d'examen :}
{122}{}{Diagnostic : }
{123}{}{Ca fait au total }
{124}{}{caps. A payer avant le traitement. Pas d'exceptions. Alors, tu paies ?}
{125}{}{Oui.}
{126}{}{Non, j'ai pas l'argent. Tu me fais crédit ?}
{127}{}{Non.}
{128}{}{Ouais.}
{129}{}{Nan.}
{130}{}{Non. Je prête à personne, c'est clair : rien -à personne. Tire-toi, pauvre loque.}
{131}{}{C'est ta vie, pas la mienne. Salut.}
{132}{}{Excellent. Allons-y. Ca risque de faire un peu mal...}
{133}{}{Et voilà. N'hésite pas à revenir !}
{134}{}{Oh, te revoilà déjà. Que veux-tu ?}
{135}{}{Faut me soigner.}
{136}{}{Rien, je viens juste bavarder.}
{137}{}{Beuf !}
{138}{}{Bon, va voir ailleurs, j'ai à faire.}
{139}{}{Hum. Ta tête me revient pas trop mais je refuse jamais un client qui paie. Que veux-tu ?}
{140}{}{J'ai besoin d'aide.}
{141}{}{J'ai besoin de soins médicaux.}
{142}{}{Rien pour aujourd'hui, merci.}
{143}{}{Ben.}
{144}{}{Oh, encore toi. Tes manières me plaisent, même si je t'aime pas. Que veux-tu ?}
{145}{}{Faut me soigner.}
{146}{}{Rien, je viens juste bavarder.}
{147}{}{Pouf !}
{148}{}{Oh, un client ! Qu'est-ce que je peux faire pour toi ?}
{149}{}{Faut me soigner.}
{150}{}{Rien, je viens juste bavarder.}
{151}{}{T'as l'air drôlement content de me revoir. Pourquoi ?}
{152}{}{Beuh !}
{153}{}{Les affaires ont chuté ces derniers temps. Je suis content de voir des clients. Non que ta compagnie me déplaise, bien sûr.}
{154}{}{Excellent, faut me soigner.}
{155}{}{Pourquoi tes affaires ont chuté ?}
{156}{}{Bien sûr, je comprends. Bonne journée.}
{157}{}{Enfin, si t'as besoin, adresse-toi à moi. Un service imbattable !}
{158}{}{Je sais pas si t'as vu, mais j'ai de la concurrence.}
{159}{}{A quoi bon se plaindre à Killian ! Il a rien contre les nouveaux venus.}
{160}{}{Ces maudits Enfants se sont installés juste à côté, et ils m'ont pris beaucoup de ma clientèle. Ca me plaît pas, mais impossible de baisser mes prix. Il me retse qu'une seule solution : fournir de meilleures prestations.}
{161}{}{Ah, faut vraiment que tu me soignes.}
{162}{}{Hum, de meilleurs prix, intéressant ! Merci.}
{163}{}{Ah, un client régulier. Ca fait plaisir par les temps qui courent ! Que veux-tu ?}
{164}{}{Faut que tu me soignes.}
{165}{}{Rien, je viens juste bavarder.}
{166}{}{Beuf !}
{167}{}{J'espère que t'as une bonne raison de me déranger. Mon temps est précieux.}
{168}{}{Je vais mourir ! Pitié, au secours !}
{169}{}{Pardon pour le dérangement, mais j'ai besoin d'aide.}
{170}{}{Ahhh !}
{171}{}{Je te trouve pas drôle du tout. S'il te plaît, file et laisse-moi travailler.}
{172}{}{Hum. Bon, je te vois rien d'anormal. T'as peut-être besoin de repos. Essaie la Crash House, juste au coin. Bonne nuit.}
{173}{}{Je regrette. Je soigne pas les imbéciles aux heures tardives. Sans doute la pleine lune qui te travaille. Bonne nuit.}
{174}{}{Encore toi. J'espère que t'as encore une bonne raison de me déranger...}
{175}{}{Je vais mourir ! Pitié, au secours !}
{176}{}{Pardon pour le dérangement, mais j'ai besoin d'aide.}
{177}{}{Ahhh !}
{178}{}{en parfaite santé,}
{179}{}{blessures légères,}
{180}{}{blessures sans gravité,}
{181}{}{blessures graves,}
{182}{}{sur le point de mourir,}
{183}{}{ du point de vue médical.}
{184}{}{ d'après mes examens.}
{185}{}{ sans aucun doute.}
{186}{}{ à mon humble avis.}
{187}{}{ Tu souffres d'un empoisonnement.}
{188}{}{ Tu es vicitme d'un empoisonnement.}
{189}{}{ Tu sais que tu es victime d'un empoisonnement ?}
{190}{}{ Ton sang contient une toxine mortelle.}
{191}{}{ Tu souffres d'un empoisonnement mineur par radiation.}
{192}{}{ Tu souffres d'un grave empoisonnement par radiation.}
{193}{}{ Ton corps a absorbé une quantité incroyable de radiations.}
{194}{}{ Mon scanner de radiations n'a jamais enregistré de pareils résultats. Tu vas bientôt rendre l'âme. Je te donne deux ou trois semaines.}
{195}{}{Je ne peux pas y faire grand-chose.}
{196}{}{J'espère que t'as une bonne raison de me déranger. Mon temps est précieux.}
{197}{}{Je vais mourir ! Pitié, au secours !}
{198}{}{Pardon pour le dérangement, mais j'ai besoin d'aide.}
{199}{}{Ahhh !}
{200}{}{Je te trouve pas drôle du tout. S'il te plaît, file et laisse-moi travailler.}
{201}{}{Hum. Bon, je te vois rien d'anormal. T'as peut-être besoin de repos. Essaie la Crash House, juste au coin. Bonne nuit.}
{202}{}{Je regrette. Je soigne pas les imbéciles aux heures tardives. Sans doute la pleine lune qui te travaille. Bonne nuit.}
{203}{}{Encore toi. J'espère que t'as encore une bonne raison de me déranger...}
{204}{}{Eh, où tu vas !? C'est privé ici !}
{205}{}{lui !}
{206}{}{elle !}
{207}{}{Arrête, boucher !}
{208}{}{Attends !}
{209}{}{Ahhh !}
{210}{}{Essaie pas de noyer le poisson !}
{211}{}{Et pourquoi je devrais ?}
{212}{}{Tu risques absolument rien avec moi !}
{213}{}{Bon, j'arrête de t'opérer illico !}
{214}{}{Non ! Je vais pas te laisser saboter mon opération ! Gretch, va chercher }
{215}{}{Pourquoi ?!}
{216}{}{Je sais ce que tu fais ici, et je t'en empêcherai pas.}
{217}{}{Bon, pas de doute, t'as bien plus de force que moi.}
{218}{}{C'est vrai. Malheureusement, t'en as trop vu. Hum.}
{219}{}{Faut qu'on s'occupe de toi. Mes excuses.}
{220}{}{Tu dois prouver ta sincérité. Et je pourrais peut-être bien tirer un petit bénéfice dans l'affaire.}
{221}{}{Qu'est-ce que tu veux dire ?}
{222}{}{Pas question de marché.}
{223}{}{Très bien. Comme tu veux !}
{224}{}{Je vais te prendre quelque chose. Comme ça, on sera à égalité.}
{225}{}{D'accord.}
{226}{}{Pas question.}
{227}{}{Excellent !}
{228}{}{Doc Morbide saisit son outil chirurgical et, avant que tu ne puisses réagir, il t'enlève un oeil. C'est extrêmement douloureux.}
{229}{}{Voilà, la moitié de ce que tu viens de voir m'appartient à nouveau.}
{230}{}{TU M'AS ARRACHE UN OEIL !! ESPECE D'EN&#%*... !!}
{231}{}{Allons, allons ! Un peu de tenue.}
{232}{}{Le docteur est sorti.}
{233}{}{Je sais des choses sur toi et sur Bob de l'Iguane Rôti, espèce de sale boucher !}
{234}{}{Que... que veux-tu dire ?}
{235}{}{J'ai eu une petite conversation avec ton gnome...}
{236}{}{[Il jette autour de lui des regards sournois] Ca prouve rien. Gretch a l'esprit un peu... lent. Personne ne l'écoute dans le coin. Tu ferais mieux de filer.}
{237}{}{Attends, ne peut on pas mettre quelque chose au point ?}


#TMA 
{970}{}{I'm Doc Morbid, can I help you?}

{980}{}{What's that?}
{981}{}{What are you babbling about?}
{982}{}{Is this a joke? I have no idea what that is.}

{1000}{}{Killian|Kilian|Sheriff|Sherrif|Mayor|Darkwater|Darkwaters}
{1001}{}{Gizmo}
{1002}{}{Junktown|Junk Town}
{1003}{}{Shady Sands|SHADY|SANDS}
{1004}{}{The Hub|HUB}
{1005}{}{Water Chip|Waterchip|Chip}
{1006}{}{Casino|Gizmo's Casino|Gizmo's|Gizmos|Gizmos Casino}
{1007}{}{Store|General Store}
{1008}{}{Deathclaw|Deathclaws|Claw|Claws}
{1009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid}
{1010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading}
{1011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside}
{1012}{}{Direction|Directions|Whereto|Where to}
{1013}{}{Fallout|Fall out|nuclear fallout}
{1014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev}
{1015}{}{Necropolis|City of the Dead|City of Dead}
{1016}{}{Boneyard|The Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard}
{1017}{}{Mutant|Mutants}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{Skuls|Skulz|Skulls|Skullz}
{1020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders}
{1021}{}{Crash|Crash House}

{1100}{}{Killian is the Mayor in town.}
{1101}{}{Gizmo runs the casino, and the boxing ring.}
{1102}{}{It's a quiet place for the most of it.}
{1103}{}{Never heard of.}
{1104}{}{Oh yes, the Hub. I have associates down there.}
{1105}{}{I don't know anything about that.}
{1106}{}{Gizmo runs it. Watch out for the slot machines, you can lose a lot of money if you play them.}
{1107}{}{Find the General Store if you keep heading up north in town.}
{1108}{}{I hear people talking about it, but I've never seen it. They say it roams the desert, striking mostly at night.}
{1109}{}{You're here. What do you want?}
{1110}{}{Killian Darkwater runs the General Store. Go there if you want to trade.}
{1111}{}{Why do you care? Junktown is obviously the better place.}
{1112}{}{I don't have time to show you the town. Ask someone else!}
{1113}{}{Just stay under a roof, okay?}
{1114}{}{They'll hang you if you get caught stealing.}
{1115}{}{I've heard about it. It's supposedly dangerous for non-mutants like us.}
{1116}{}{It's a place somewhere far south for all I know.}
{1117}{}{Horrible creatures. I pity them.}
{1118}{}{That's the bar a few houses north of here.}
{1119}{}{They are the local gang. Have to stick them back together every once in a while.}
{1120}{}{Luckily we don't run into much problems with them down here. Heard it's much worse up north.}
{1121}{}{If you need a place to sleep, check with the Crash House.}
