{100}{}{Voici le Chevalier Paul.}
{101}{}{Ahhh, alors c'est toi la jeune recrue. Bienvenue. En quoi je peux t'aider ?}
{102}{}{Qui es-tu et que fais-tu ici ?}
{103}{}{Où puis-je me procurer des armes ?}
{104}{}{Vree m'a dit que je pourrais voir une nouvelle arme.}
{105}{}{T'aurais pas une puce d'eau ?}
{106}{}{T'aurais pas des pièces de SuperArmure ?}
{107}{}{Que quoi ?}
{108}{}{Euh rien, merci.}
{109}{}{Je suis Paul, le responsable du Développement des Armes à Energie.}
{110}{}{Quel genre d'armes à énergie ?}
{111}{}{T'aurais pas le pistolet laser conçu par Vree ?}
{112}{}{Laser, Plasma... tout ce que tu veux, je le fabrique... ou du moins, je le re-fabrique.}
{113}{}{C'est possible de m'en procurer un ?}
{114}{}{Super. Continue comme ça. Salut.}
{115}{}{Pour avoir une arme, faudrait que tu vois Michael. Mais il ne peut pas te donner d'autorisation. Pour ça, faut voir Talus.}
{116}{}{D'accord. Où je peux les trouver ?}
{117}{}{D'accord. Merci pour les infos, salut.}
{118}{}{Tous deux sont au premier étage de la base. D'habitude, Talus est dans la salle d'entraînement et Michael, dans la salle de stockage.}
{119}{}{Merci. Je peux encore te poser quelques questions ?}
{120}{}{Merci. Faut que je parte.}
{121}{}{Certainement. En quoi je peux t'aider ?}
{122}{}{Où je peux me procurer de nouvelles armes ?}
{123}{}{T'aurais pas une puce d'eau ?}
{124}{}{T'aurais pas des pièces de SuperArmure ?}
{125}{}{Je peux voir le nouveau pistolet laser ?}
{126}{}{Euh, faut que je parte. Salut.}
{127}{}{Oui. Le nec plus ultra de la technologie des armes de poing. [Il prend un petit pistolet sur une table de travail et te le tend.]}
{128}{}{Beau bijou, je peux le garder ?}
{129}{}{Quel genre de dégâts ça fait sur une personne ?}
{130}{}{Celui-là te servira pas à grand-chose. Il manque encore la lunette et l'amplificateur. [Il te reprend le pistolet et le repose sur la table.] Si t'en veux vraiment un, adresse-toi à Talus ou à Michael.}
{131}{}{Merci. Où je peux les trouver ?}
{132}{}{Merci, faut que je parte.}
{133}{}{Je peux encore te poser quelques questions ?}
{134}{}{Une puce d'eau ? Comme celle des anciens Abris Tech ?}
{135}{}{Oui ! T'en as une ?}
{136}{}{Non. Ces puces, de la camelote qui tombe toujours en panne ! On purifie pas notre eau ici, c'est le Centre qui nous la livre par caravanes.}
{137}{}{D'accord. Merci. Bon, je dois continuer à chercher. Salut.}
{138}{}{Je peux encore te poser quelques questions ?}
{139}{}{Dans des mains expertes, ça peut couper quelqu'un en deux. Le rayon déchire la chair en un éclair.}
{140}{}{Je peux le garder ?}
{141}{}{Non. Je travaille seulement sur les Armes à énergie. Si t'as des questions sur la SuperArmure, adresse-toi à Kyle.}
{142}{}{En fait, Kyle n'a pas les pièces, c'est pour ça que je les cherche.}
{143}{}{Merci. Salut.}
{144}{}{Je regrette, là-dessus, je ne peux pas t'aider.}
{145}{}{Merci. Faut que je parte. Salut.}
{146}{}{Je peux encore te poser quelques questions ?}
{147}{}{Re-bonjour, Initié }
{148}{}{. En quoi je peux t'aider ?}
{149}{}{Qui es-tu et que fais-tu ici ?}
{150}{}{Où puis-je me procurer des armes ?}
{151}{}{Vree m'a dit que je pourrais voir une nouvelle arme.}
{152}{}{T'aurais pas une puce d'eau ?}
{153}{}{T'aurais pas des pièces de SuperArmure ?}
{154}{}{Que quoi ?}
{155}{}{Euh rien, merci.}
{156}{}{Hum... file avant de déblatérer sur quelque chose d'important.}
