{100}{}{Voici un paysan.}
{101}{}{Oh, en v'là un qui détale devant un malheureux clebs. Phil, sûr que tu lui as montré !}
{102}{}{Qu'est-ce que tu fous, Phil ? Tu r'fais tes lacets ?}
{103}{}{Bon sang, ce chien a l'air d'avoir les crocs ! Sûr qu'il veut te bouffer tout cru, Phil !}
{104}{}{C'est p't-être un peu exagéré, pour un pauv' clébard sans défense, tu crois pas ?}
{105}{}{Sûr qu'c'est un gentil toutou que t'as là.}
{106}{}{Sûr qu'Phil te s'rait reconnaissant si tu le débarrassais de son chien.}
{107}{}{Merci d'avoir pris le temps de t'occuper de ce chien.}
