{100}{}{Voici Jerry, un jeune Initié.}
{101}{}{Voici un Chevalier Initié.}
{102}{}{Voici un Scribe Initié.}
{103}{}{Bonjour ! Tu dois être Frère }
{104}{}{, la jeune recrue. Je suis Jerry, ton nouveau camarade de chambre. Moi aussi, je suis un initié ! J'ai beaucoup étudié. Tu es un Chevalier ou Scribe Initié ?}
{105}{}{J'ai pas décidé.}
{106}{}{Chevalier.}
{107}{}{Scribe.}
{108}{}{Euh.}
{109}{}{Ouais, devenir Chevalier, ce serait super ! Ils voient plein de choses et c'est eux qui construisent tout. J'ai pas encore décidé mais je pencherais plutôt pour Chevalier. Je t'ennuie ? Y'en a qui me trouvent trop bavard, mais je crois qu'ils comprennent pas. C'est simplement que j'ai beaucoup à dire.}
{110}{}{Non, pas du tout.}
{111}{}{Faut que j'y aille. Un vrai plaisir d'avoir fait ta connaissance !}
{112}{}{Ouais, les Scribes jouent un rôle tellement créatif. Ca doit être chouette d'inventer de nouvelles armes, de modifier des anciennes et de tout consigner sur tous les objets de la Confrérie. Je t'ennuie ? Y'en a qui me trouvent trop bavard, mais je crois qu'ils comprennent pas. C'est simplement que j'ai beaucoup à dire.}
{113}{}{Ouais, j'arrive pas à me décider. C'est dur, les deux sont passionnants. Au fait, si tu préfères le lit du haut, dis-le, ça m'est égal.}
{114}{}{Merci, salut.}
{115}{}{Tu te sens bien ? Peut-être devrais-tu voir le médecin ou te reposer. Bon, faut que je retourne étudier. Salut.}
{116}{}{Oh, ça me fait plaisir que tu sois mon nouveau camarade de chambre. Le dernier portait toujours des boules Quiès, je sais pas pourquoi. Bref, laisse les affaires que tu veux ici, je prends pas beaucoup de place. Si tu préfères le lit du haut, je peux changer... Tu ronfles pas, par hasard ? Oh, ça fait rien. A plus.}
{117}{}{Ouais, c'est ce que je pensais. Ah, ça me fait plaisir que tu sois mon nouveau camarade de chambre. Le dernier portait toujours des boules Quiès, je sais pas pourquoi. Bref, laisse les affaires que tu veux ici, je prends pas beaucoup de place. Si tu préfères le lit du haut, je peux changer... Tu ronfles pas, par hasard ? Oh, ça fait rien. A plus.}
{118}{}{N'hésite pas à me dire si je ronfle.}
{119}{}{Thomas dit que je parle trop.}
{120}{}{Talus dit que je ferais un bon Chevalier si je parlais pas tant.}
{121}{}{Ca fait plaisir de te revoir, camarade de chambre !}
{122}{}{J'ai mal dormi cette nuit.}
{123}{}{Re-bonjour.}
{124}{}{Faut que je parte en patrouille demain.}
{125}{}{Je serai Initié Senior dans quelques années.}
{126}{}{C'est pas ta chambre, va-t'en s'il te plaît.}
{127}{}{Je crois que tu partages la chambre de Jerry.}
{128}{}{Bonne chance, tu vas partager la chambre de Jerry la pie.}
{129}{}{Qu'est-ce tu fais ici ?}
{130}{}{Tu fais aussi partie des Initiés ?}
{131}{}{Tu visites ?}
{132}{}{Ta chambre est la première à gauche en entrant.}
