# For lines 177 and 180 and 181, spaces are intentional.
# Line 177 is prepended to encounter type. (they begin at 183 below)
{177}{}{Tu rencontres }
{178}{}{Oui.}
{179}{}{Non.}
{180}{}{Tu obtiens }
{181}{}{ points d'expérience pour avoir utilisé ta compétence Vie en plein air à bon escient.}
# Line 182 is appended after 177 and the encounter type. Period and space is intentional.
{182}{}{. Souhaitez vous engager le combat ?}
# These are apended to line 177.
{183}{}{des Flotteurs}
{184}{}{des Mantes religieuses}
{185}{}{des Rats}
{186}{}{des Paysants attaqués par des Pillards}

{289}{}{Tu tombes sur un groupe de gecko affamés.}
{290}{}{Tu es attaqué par des geckos de feu !}
{291}{}{Tu tombes sur dun groupe de fire gecko vicieux.}

#
# 100 to 103 are NOT USED, looks like it was old code for finding the Radscorpion Cave from the worldmap.
#
{100}{}{A première vue, ils n'ont pas dû voyager bien loin. Ils doivent avoir un repaire près d'ici.}
{101}{}{On dirait qu'ils ne venaient pas de très loin.}
{102}{}{On dirait qu'ils venaient de quelque part au Nord d'ici.}
{103}{}{Apparemment, ils erraient dans le désert.}

{106}{}{Tu tombes sur un important groupe de radscorpions !}
{107}{}{Tu tombes sur un groupe de radscorpions.}
{108}{}{Tu tombes sur une famille de rataupes.}

# DEHYDRATION ENCOUNTERS
{109}{}{Tu parviens à éviter la déshydratation en trouvant de l'eau. Les recherches t'ont prit 1 heure.}
{110}{}{Tu parviens à éviter la déshydratation en trouvant de l'eau. Les recherches t'ont prit }
{111}{}{ heures.}
{112}{}{Tes réserves d'eau sont épuisées, et tes recherches ont échoué à trouver de l'eau. Tu souffres de déshydratation sévère, causant }
{113}{}{ points de dégats.}
{114}{}{Tes réserves d'eau sont épuisées, et tes recherches ont pris }
{115}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds }
{116}{}{ points de dégats.}
{117}{}{Tu recherches de l'eau dans le désert pendant 1 heure mais tu n'en trouves pas assez pour étancher ta soif. Tu perds un point d'impact.}
{118}{}{Tu recherches de l'eau dans le désert pendant 1 heure mais tu n'en trouves pas assez pour étancher ta soif. Tu perds }
{119}{}{ points de dégats.}
{120}{}{Tu recherches de l'eau dans le désert pendant }
{121}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds 1 points de dégats.}
{122}{}{Tu recherches de l'eau dans le désert pendant }
{123}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds }
{124}{}{ points de dégats.}

{125}{}{Tu parviens à éviter la déshydratation en utilisant tes ressources en eau.}

{1250}{}{Tu évites la déshydratation en piochant dans tes réserves de }
{1251}{}{.}
{1160}{}{un point de dégats.}

# CRITICAL SUCCESS ON OUTDOORSMAN CHECK
{147}{}{Tu t'efforces à trouver de l'eau afin d'éviter la déshydratation. Les recherches t'ont prit 1 heure.}
{138}{}{ Tu remplis  }
{159}{}{tes flasques}
{160}{}{ avec l'eau potable.}
{165}{}{Tu reçois }
{166}{}{ points d'expérience pour avoir utilisé avec succès ta compétence Vie en plein air.}

# NORTH_TABLE ENCOUNTERS
#
#
# North1
#
# if pass Perception check or have Awareness:
#   197 Uh-oh... a raiding party !
# else is:
{105}{}{EMBUSCADE !!}
#
# North2
#
{104}{}{Tu tombes sur une violente échauffourée entre des radscorpions et des rataupes.}
#
# North3
#
#
# North6
#
# -Dehydration-
#
# SOUTH_TABLE ENCOUNTERS
#
# South1 -- change this encounter to something else ??
#
{131}{}{PANIQUE !!}
#
# South2
#
{132}{}{Tu tombes sur un important groupe de radscorpions !}
#
# South3
#
# -Dehydration-
#
# South4 -- change this encounter to something else
#
# 143 "Raiders !!!"
#
# South5
#
{144}{}{Tu tombes sur un grand rassemblement de rataupes.}
#
# South6
#
{145}{}{Tu rencontres une bande de radscorpions sauvages.}
#
#
# SHADY ENCOUNTERS
#
#
# Shady1
#
{146}{}{Tu rencontres des paysans victimes d'une attaque.}
#
# Shady2
#
# -Dehydration-
#
# Shady3
#
{169}{}{Tu tombes sur une famille de radscorpions.}
#
# Shady4
#
{170}{}{Tu tombes sur un marchand nomade et ses gardes.}
#
# unless he's dead, then you get
#
{305}{}{Tu découvres les restes des gardes hostiles de Duc le marchand.}
#
# once that has been seen, call Shady3
#
# Shady5
#
{175}{}{Tu rencontres un voyageur.}
# or if killed,
{171}{}{Tu découvres un voyageur mort.}
#
# else call Shady2
#
# Shady
#
{126}{}{Tu tombes sur des radscorpions chassant des rataupes.}
{127}{}{Des humanoïdes hostiles, maigres et à la peau verdâtre s'approchent.}
{128}{}{Des déchets et des pierres sont éparpillés. Tu te demandes s'il reste quelque chose de valeur.}
#
# UNUSED ENTRY:
{129}{}{Un radscorpion solitaire te tend une embuscade !}
#
{130}{}{Tu remarques un cadavre partiellement dévoré.}
{134}{}{Un groupe d'horribles radscorpions venant du désert attaque !}
{135}{}{Tu rencontres un groupe de gardes en patrouille.}
{136}{}{Tu rencontres un marchand accompagné de plusieurs gardes.}
{174}{}{Tu tombes sur les restes d'un marchand et de ces gardes.}
{137}{}{Tu tombes sur un paysan gardant des brahmines.}
{139}{}{Des radscorpions chassant des rataupes au milieu des ruines d'un village.}
{172}{}{Tu découvres des objets éparpillés au sol.}
{176}{}{Tu te retrouves au milieu de ruines et d'immeubles abandonnés.}
#
#
# RAIDER_TABLE ENCOUNTERS
#
#
# Raider1
#
{133}{}{Des pillards te tendent une embuscade !}
#
# Raider2 - half chance of either msg displayed, but encounter the same
#
{143}{}{Des pillards !!}
{197}{}{Oh-oh... une fête de pillards !}
#
# Raider3
#
{173}{}{Tu aperçois les restes d'une caravane mise à sac par des pillards.}
#
# Raider4
#
{310}{}{Un petit groupe de pillards attaque !}
#
# Raider5 - 198 always, plus 196 half the time
#
{198}{}{Tu aperçois un pillard solitaire.}
{196}{}{Radscorpions en approche !}
#
# Raider6 - displays and runs both (because bodies are empty)
#
{199}{}{Tu découvres les restes d'un champ de bataille jonché de cadavres.}
#plus 196
#
#
{223}{}{Tu aperçois une meute errante de coyotes sauvages.}
{200}{}{Radscorpions en vue !}
{224}{}{Tu aperçois des individus à l'affût.}
{225}{}{Tu tombes sur une petite fête entre des marchands et leurs gardes.}
{226}{}{Tu assistes à une petite échauffourée : des hommes contre des mutants !}
{227}{}{Une immense horde de radscorpions arrive dans cette direction !}
#
{250}{}{Des hommes portant des SuperArmures se dirigent vers toi.}
{251}{}{Tu aperçois un groupe de marchands et de gardes.}
{252}{}{Tu assistes à une violente échauffourée entre des pillards du désert et un groupe d'hommes en SuperArmures.}
{253}{}{Tu aperçois des mutants explorant une parcelle de terre hostile.}
{254}{}{Tu aperçois d'étranges créatures...}
{256}{}{Une patrouille de super mutants passe tout près !}

{257}{}{Tu aperçois les ruines d'un petit village.}

# UNUSED ENTRY:
{255}{}{Tu trouves des objets.}

{279}{}{Devant toi, tu aperçois des déchets éparpillés dans le sable.}
{280}{}{Tu tombes sur une bataille de super mutants.}
{281}{}{Tu tombes sur une bande de créatures bizarres.}
{282}{}{Tu tombes sur une bande de radscorpions affamés.}
{283}{}{Tu as des nausées et l'air semble vaciller avec la chaleur. Soudain, une créature mutante approche.}
{284}{}{Tu tombes sur d'étranges créatures flottantes.}
{285}{}{Tu rencontres quelque chose semblant tout droit sorti d'un vieux film de science-fiction.}
{286}{}{Le Griffemort !!}
{287}{}{Tu tombes sur une bande de radscorpions en déplacement. Ils semblent fuir quelque chose...}
{288}{}{Tu rencontres une créature mutante du désert.}
#
{299}{}{Tu aperçois des radscorpions.}
{300}{}{Tu rencontres un paysan en haillons.}
{301}{}{Tu rencontres un rataupe.}

# was: "The Deathclaw !!"
{302}{}{Un jeune Griffemort semblant penser que tu es son casse-croûte.}

{303}{}{Tu tombes sur une bande de radscorpions en déplacement.}
#
{306}{}{Une patrouille de mutants passe tout près, accompagnée d'étranges créatures !}
{307}{}{Tu te fais prendre en embuscade par une petite équipe de super mutants.}
{308}{}{Il semble que tu te retrouves au coeur d'une violente guerre entre bandes !}
{309}{}{Un groupe de bandits hostiles t'attaque !}
{311}{}{Un petit groupe de bandits attaque !}
{313}{}{Soudain, une nuée de mantes mutantes t'attaque !}

# UNUSED ENTRY:
{312}{}{Soudain, des rats t'attaquent !}

# SPECIAL ENCOUNTERS TEXT:
{314}{}{Hé ! Ils sont vraiment là.}
{315}{}{Tu aperçois un camion renversé.}
{316}{}{Tu découvres des épaves de voitures en plein milieu du désert.}
{317}{}{Au Nord-Est, tu aperçois une cabine de police.}
{318}{}{Tu rencontres une horde de Brahmines sauvages. C'est étrange...}
#
# Fo1in2:
{400}{}{Vous êtes tombé sur un groupe de geckos.}
{401}{}{Vous êtes tombé sur un groupe de geckos doré.}
{402}{}{Des chasseurs de prime !}
{403}{}{Tu vois des chasseurs au loin.}
{404}{}{Un groupe de guerriers tribales cherchant vengeance !}
