{100}{}{Tu vois Romero.}
{103}{}{Tu vois un membre des Ecorcheurs.}
{104}{}{Tu vois un membre des Ecorcheurs.}
{105}{}{Tu penses que c'est Books.}
{106}{}{Tu penses que c'est Scars.}
{107}{}{Tu penses que c'est Gunner.}
{108}{}{Tu penses que c'est Twitch.}
{109}{}{Tu penses que c'est Hammer.}
{110}{}{Tu penses que c'est Razor.}
{111}{}{Vas t'en !}
{112}{}{Quoi ? Que veux-tu dire ?}
{113}{}{Jamais !}
{114}{}{Je suis ici pour parler de paix.}
{115}{}{Ok.}
{116}{}{Ici, c'est moi qui pose les questions. Que fais tu ici ?}
{117}{}{Je suis ici pour trouver un ami.}
{118}{}{Je suis ici pour parler de paix.}
{119}{}{Je veux mettre fin à la guerre des gangs dans le Sanctuaire !}
{120}{}{Je veux boire le sang des Ecorcheurs !}
{121}{}{Alors tu cherches au mauvais endroit. Laisse moi.}
{122}{}{Tu dois être une de ces petites mauviettes des robes violettes. Sors d'ici avant qu'on t'explose le crâne.}
{123}{}{Attend ! Je ne sais pas de quoi tu parles. Je suis là pour le Sanctuaire. Ils veulent que je fasse en sorte que tout le monde les laisse tranquilles.}
{124}{}{La paix !}
{125}{}{Désolé. Je m'en vais maintenant.}
{126}{}{Hmm. Si tu es vraiment du Sanctuaire, alors tu es encore un perdant. La paix n'existera jamais tant que ces Régulateurs seront dans les parages.}
{127}{}{Que veux-tu dire ?}
{128}{}{Uh, bien sûr.}
{129}{}{Demande à Razor. Elle te donnera des explications sur ces consanguins sanguinaires.}
{130}{}{Dégage !}
{131}{}{Hé, maintenant que tu es un Ecorcheur, j'ai besoin que tu m'accordes une faveur.}
{132}{}{Bien sûr.}
{133}{}{Qu'est-ce que c'est ?}
{134}{}{Pas question.}
{135}{}{Super. Amène ce médaillon à Julianna. Dis lui que j'espère la voir bientôt.}
{136}{}{Il semblerai que je sois tombé amoureux d'une fille au Sanctuaire. Les Régulateurs nous tirent dessus à vue, alors je ne peux pas aller la voir.}
{137}{}{En quoi puis-je t'aider ?}
{138}{}{Allez raconte l'histoire.}
{139}{}{Dure situation.}
{140}{}{Si tu apportes ce médaillon à Julianna, j'aurai une dette envers toi.}
{141}{}{Aucun soucis.}
{142}{}{Trouve quelqu'un d'autre.}
{143}{}{Avec des alliés tels que toi, qui a besoin d'ennemis ? Bonne journée !}
{144}{}{Je penses qu'elle m'aime aussi, mais je n'en sais pas plus. Les Ecorcheurs ne prendront pas le risque de me laisser essayer de me faufiler dans le Sanctuaire.}
{145}{}{Dure situation.}
{146}{}{Ok, je vais te donner un coup de main.}
{147}{}{Merci ! Elle m'a envoyé un message. Nous allons nous rejoindre chez les Disciples pour nous marier.}
{148}{}{Bienvenue.}
{149}{}{Merci beaucoup. Nous allons maintenant rester ici avec les Disciples, où nous pouvons être des heureux mariés.}
