{100}{}{Voici Seth, le guide revenant aux Sables Ombragés.}
{101}{}{Dépêchons-nous de nous débarrasser de ces radscorpions !}
{102}{}{Rentrons aux Sables Ombragés et prévenons-les que les radscorpions sont partis.}
