{100}{}{Voici Le Requin.}
{101}{}{Voici un homme aux dents limées.}
{102}{}{Espèce d'ordure !}
{103}{}{Hé, toi ! Alors, qu'est-ce qui t'amène sur notre territoire, camarade ? Tu as envie de t'amuser un peu ? A tes frais, bien sûr.}
{104}{}{Je suis venu ici pour botter des culs et mâcher du chewing-gum... je pense que tu devines la suite.}
{105}{}{Qu'est-ce qu'on peut faire pour s'amuser par ici ?}
{106}{}{Euh, je m'en allais. Au revoir.}
{107}{}{J'étais juste là pour boire un verre et me... divertir.}
{108}{}{Gloup !}
{109}{}{Ici, les pots de colle comme toi, on les tabasse !}
{110}{}{Pas si vite ! Personne ne passe sur notre territoire sans payer la taxe de souffrance.}
{111}{}{Ok. Saisissez-la, les gars.}
{112}{}{Laisse-moi te présenter au responsable des taxes. On l'appelle M. Marteau !}
{113}{}{Je ne crois pas !}
{114}{}{Eh bien, pour cette soirée de divertissement, nous avons décidé de saccager cet endroit ! Hé. Prends tout ce que tu peux emporter et faisons couler un peu de sang, hein ?}
{115}{}{Je crois que je vais prendre un verre.}
{116}{}{Frapper et boire ? Ne m'oublie pas !}
{117}{}{Pas ce soir, j'ai mal à la tête.}
{118}{}{Non, je préférerais manger quelque chose... peut-être du requin grillé !}
{119}{}{Ah, espèce de lâche. Retourne voir ta maman !}
{120}{}{Encore toi ? Ah, il y en a qui ne comprennent jamais rien !}
{121}{}{J'avais juste envie de boire un verre.}
{122}{}{Je m'en vais, tant pis.}
{123}{}{Gloup !}
{124}{}{Ce n'est pas une mauvaise idée. Je crois que je vais faire la même chose. Un carnage s'accompagne toujours d'une bonne bière, c'est évident !}
{125}{}{Je croyais que tu avais pigé qu'il valait mieux pour toi que tu fiches le camp. Je suppose que j'avais tort. Eh bien, au moins je vais bien m'amuser avec toi !}
{126}{}{Nous reviendrons, vieil homme. Ce n'est pas fini.}

# TMA
{970}{}{C'est moi.}
{971}{}{Qui le demande ?}
{972}{}{Tu cherches les ennuis ?}

{980}{}{Tu essaies de m'faire chier ? Dégage !}
{981}{}{Hors de ma vue.}
{982}{}{Casse-toi.}
