{100}{}{Voici Talius, un membre des Disciples.}
{101}{}{Va t'en, s'il te plaît. Je voudrais être tranquille. Reviens dans la journée.}
{102}{}{Salut, ma soeur. Je m'appelle Talius. Que puis-je faire pour toi aujourd'hui ?}
{103}{}{Salut, mon frère. Je m'appelle Talius. Que puis-je faire pour toi aujourd'hui ?}
{104}{}{Hein ?}
{105}{}{Moi }
{106}{}{. Moi }
{107}{}{.}
{108}{}{Je m'appelle }
{109}{}{. Que fais-tu ici ?}
{110}{}{Tu peux mourir !}
{111}{}{Ne t'en fais pas pour moi, Mutant ! Comment as-tu fait pour entrer ici ?}
{112}{}{Salut. On m'appelle }
{113}{}{. Pourquoi as-tu décidé de venir dans le royaume des Disciples ?}
{114}{}{Peux-tu m'expliquer comment une de tes altérations est entrée dans les Disciples ?}
{115}{}{Je vois que tu n'as pas l'esprit très vif. Moi aussi, j'avais ton intelligence autrefois. Mais, grâce aux enseignements des Disciples, j'ai réussi à transcender mes défauts.}
{116}{}{Je ne sais pas.}
{117}{}{Trop intelligent. Maintenant, tu vas mourir.}
{118}{}{Excuse-moi. Je me laisse aller par moments. Voudrais-tu d'une aide intellectuelle ?}
{119}{}{Ouais. Toi !}
{120}{}{Hé ! Hé !}
{121}{}{Tiens. Prends ces jolies pilules. Elles stimuleront ton intelligence.}
{122}{}{Oui, }
{123}{}{. Tu me fais plaisir. Comment puis-je t'aider ?}
{124}{}{Quoi ?}
{125}{}{Cerveau fait mal. Moi tuer toi. Prendre cerveau.}
{126}{}{Je suis là pour aider ces gentilles personnes à comprendre les rouages des Enfants de la Cathédrale.}
{127}{}{Alors, tu espionnes pour le compte des Enfants ?}
{128}{}{Que peux-tu savoir sur les Enfants ?}
{129}{}{De quoi es-tu capable ? Tu es un mutant.}
{130}{}{Non, je ne suis pas un espion. Même si beaucoup le croient. Il y a un espion dans notre humble demeure. Mais nous n'avons pas encore réussi à le surprendre.}
{131}{}{Alors, comment aides-tu les Disciples ?}
{132}{}{Dis-moi ce que tu sais sur cet espion. Je pourrai peut-être t'aider.}
{133}{}{Pas de bol, Mutant !}
{134}{}{Je crois que j'ai trouvé l'espion. Finis les problèmes !}
{135}{}{Autrefois, j'étais comme toi. Mais, après l'arrivée des Ténébreux à Nécropolis, voilà ce que je suis devenu.}
{136}{}{C'est terrible. Pas de bol. A bientôt.}
{137}{}{Pourquoi étais-tu à Nécropolis ?}
{138}{}{D'où viens-tu ?}
{139}{}{Et maintenant, je vais à nouveau te transformer. Repose en paix.}
{140}{}{Il y a quelques temps, je vivais dans un endroit situé très loin au Nord d'ici. Ils avaient un problème avec l'approvisionnement d'eau et ils cherchaient des gens pour le résoudre.}
{141}{}{Alors, tu as voulu te porter volontaire.}
{142}{}{Où se trouvait cet endroit ?}
{143}{}{As-tu trouvé une solution à ce problème ?}
{144}{}{Mais pourquoi Nécropolis ?}
{145}{}{Oui. Le dirigeant de la communauté m'a donné un fusil et des munitions. Mais je les ai perdus et les années ont passé. Et comme je n'ai rien trouvé, je n'ai jamais pu rentrer.}
{146}{}{C'est vraiment terrible. J'aimerais pouvoir faire quelque chose.}
{147}{}{Dommage. Je dois partir.}
{148}{}{Où se trouvait cet endroit ?}
{149}{}{As-tu trouvé un moyen de résoudre ce problème d'eau ?}
{150}{}{Pourquoi es-tu allé à Nécropolis ?}
{151}{}{Il y a une chose que tu peux faire pour moi. Celui qui m'a fait ça doit être arrêté.}
{152}{}{Qui est-ce ?}
{153}{}{Leur chef est le responsable d'une armée de mutants. Il enlève des humains de pure souche pour les transformer. Je n'en sais pas plus parce que j'ai perdu connaissance avant le processus.}
{154}{}{Alors, je les tuerai pour toi.}
{155}{}{Cela me paraît trop risqué. Je m'en vais.}
{156}{}{Je te remercie de ta gentillesse. Tu me rends un grand service. S'il te plaît, accepte ceci en témoignage de ma reconnaissance. Je l'ai volé sur le cadavre d'un renégat décédé.}
{157}{}{Alors, que la paix soit avec toi. Je peux comprendre ton malaise. Peut-être que quelqu'un d'autre viendra m'aider à éradiquer cette menace. Bonne journée.}
{158}{}{L'endroit dont je suis originaire se trouvait dans les montagnes, très loin au Nord. C'était un petit abri où vivaient beaucoup de gens.}
{159}{}{As-tu trouvé une solution à ce problème d'eau ?}
{160}{}{Pourquoi es-tu allé à Nécropolis ?}
{161}{}{Quel était le nom de cet Abri ?}
{162}{}{Ca me semble intéressant. Je vais y aller.}
{163}{}{Hélas, jamais. J'ai entendu dire que d'autres avaient été envoyés par l'abri pour rechercher un moyen de réparer la pompe à eau.}
{164}{}{Je n'ai rien su d'autre à leur sujet.}
{165}{}{Pourquoi es-tu allé à Nécropolis ?}
{166}{}{Quel était le nom de cet Abri ?}
{167}{}{Ca me semble intéressant. Je vais y aller.}
{168}{}{J'ai entendu les autres voyageurs dire que Nécropolis avait un moyen de produire de l'eau très facilement.}
{169}{}{Alors, j'y ai été pour voir comment ils s'y prenaient.}
{170}{}{Qu'as-tu trouvé ?}
{171}{}{Les as-tu tués ?}
{172}{}{Tu te sens chez toi là ?}
{173}{}{Là-bas, j'ai découvert un grand nombre de Mutants. Ce sont eux qui m'ont piégé et donné ma forme actuelle.}
{174}{}{Apparemment, ils ont fait une erreur, car j'ai évolué différemment des autres.}
{175}{}{Trop dur. A bientôt.}
{176}{}{Je tâcherai de me méfier d'eux. Merci du renseignement.}
{177}{}{Qui est leur chef ?}
{178}{}{Non. Je n'ai tué que quelques mutants. Il y en avait un autre, un Goule, appelé Set, qui m'a aidé à anéantir la plupart d'entre eux.}
{179}{}{D'après ce que je sais, il n'est resté qu'une demi-douzaine de mutants.}
{180}{}{Ca a l'air intéressant. Eh bien, à plus tard.}
{181}{}{Les autres sont partis maintenant. Et Set va bien.}
{182}{}{C'est une bonne nouvelle. Ca me fait très plaisir d'apprendre que le mal a été détruit et qu'une ville a été libérée. Prends ça, s'il te plaît.}
{183}{}{Les sarcasmes et le manque de considération ne m'empêcheront pas de tenter de faire le bien. Il est temps que tu partes. Bonne journée.}
{184}{}{Mon abri n'avait pas de nom. Il portait simplement le numéro 13.}
{185}{}{C'est de là que je viens.}
{186}{}{Jamais entendu parler de cet endroit.}
{187}{}{Merci du renseignement. Maintenant, je vais aller en parler à ces Mutants.}
{188}{}{Vraiment ? Le Dirigeant a-t-il finalement trouvé une solution pour permettre aux gens de quitter l'Abri ?}
{189}{}{Non, il continue à avoir peur du monde extérieur.}
{190}{}{Non, il craint pour la sécurité des habitants.}
{191}{}{Oui, il pense qu'il n'y a pas de danger.}
{192}{}{C'est ce que je croyais. Il a toujours été très prudent. Je le plains d'avoir tant de responsabilités. Je te souhaite de mieux t'en sortir que moi au cours de cette quête.}
{193}{}{Ca me fait plaisir d'apprendre qu'il a enfin écouté sa raison et qu'il leur a permis de partir. Même si la vie à l'extérieur est loin d'être facile, ce sera une bonne chose de rebâtir le monde. Adieu, camarade.}
{194}{}{Venant du monde extérieur, je doute que tu l'aurais fait. Maintenant, je dois me retirer. S'il te plaît, fais attention à ces créatures avides de destruction.}
{195}{}{Non, je doute que tu aies été capable d'en faire autant.}
{196}{}{Essaie de m'arrêter.}
{197}{}{Pourquoi dis-tu cela ?}
{198}{}{Parce que je vais t'arrêter.}
{199}{}{Je ne sais pas grand-chose. Tout ce que je sais, c'est que nos éclaireurs sont les seuls à avoir jamais infiltré les Enfants pour les espionner. Personne d'autre ne peut y aller en raison du danger.}
{200}{}{Alors, c'est peut-être un éclaireur. Je vais chercher dans cette direction.}
{201}{}{Je crois que c'est toi. Maintenant, tu vas mourir !}
{202}{}{J'aurais aimé que tu aies une intelligence plus développée. Tant pis, je vais vite me débarrasser de toi.}
{203}{}{Tout ce que je sais sur les Enfants, c'est qu'ils sont de mèche avec ces super mutants appelés les Ténébreux.}
{204}{}{Ce sont eux qui m'ont transformé, à Nécropolis.}
{205}{}{C'est terrible. Pas de bol. A bientôt.}
{206}{}{Pourquoi étais-tu à Nécropolis ?}
{207}{}{D'où viens-tu ?}
{208}{}{Et maintenant, je vais à nouveau te transformer. Repose en paix.}
{209}{}{Même si mon apparence est différente, j'ai beaucoup de connaissances à transmettre à ceux qui voudront bien m'écouter.}
{210}{}{Je n'ai pas de temps pour ça, je m'en vais.}
{211}{}{Que peux-tu me dire ?}
{212}{}{Ceux que les Disciples et les Enfants appellent les Ténébreux ne sont pas ce qu'ils paraissent. Ils ont été créés par un individu appelé le Lieutenant. Et je pense qu'il obéit lui-même aux ordres de quelqu'un d'autre.}
{213}{}{Quelques informations. Bon, je m'en vais.}
{214}{}{Que peux-tu me dire sur ce Lieutenant ?}
{215}{}{Je ne sais pas grand-chose sur lui. La dernière fois que je l'ai vu, avant ma transformation prématurée, il recherchait des humains de pure souche.}
{216}{}{Je vais y réfléchir un moment. Merci.}
{217}{}{Peux-tu émettre une hypothèse pour expliquer tout ceci ?}
{218}{}{Pour l'instant, je n'ai aucune certitude. Peut-être qu'un autre groupe cherchant à les arrêter le saurait.}
{219}{}{Merci. Bonne journée.}
{220}{}{Je regrette, mais je ne peux pas tolérer une telle insolence. Va t'en.}
{221}{}{Je n'ai pas eu de mal à entrer chez les Disciples, je t'assure. Ce sont les Disciples qui m'ont sauvé et empêché ma transformation en bête atroce.}
{222}{}{Je ne comprends pas tout. Continue, s'il te plaît.}
{223}{}{Autrefois, j'étais comme toi : un humain de pure souche. Mais, à cause de l'intervention des Ténébreux, j'ai été envoyé dans un endroit très loin d'ici.}
{224}{}{Continue, s'il te plaît.}
{225}{}{Je n'étais pas en état d'observer ce qui se passait. Tout ce que je sais, c'est que je me suis réveillé ici et que j'ai été soigné par le bon médecin.}
{226}{}{Ca me fait beaucoup de peine d'entendre tous tes malheurs. Je trouverai ceux qui t'ont fait ça et je ferai ce qu'il faut.}
{227}{}{Ca me fait de la peine pour toi. Hélas, j'ai déjà assez de mal à tenter de survivre. Adieu.}
{228}{}{S'il te plaît, rends la justice et arrête celui qui cherche à ruiner la confiance des Disciples.}
{229}{}{Excellent travail, merci d'avoir anéanti l'espion, Heather.}
{230}{}{Voici un abominable Goule.}
{231}{}{Pourtant, il te rappelle quelqu'un.}
{232}{}{Hélas, je n'ai plus de temps à perdre avec toi. Bonne journée.}

#Fo1in2
{300}{}{Salutations, ma soeur. Je m'appelle Talius. Que puis-je faire pour toi aujourd'hui ?}
{301}{}{Salutations, mon frère. Je m'appelle Talius. Que puis-je faire pour toi aujourd'hui ?}
	{302}{}{Que fais-tu ici ?}
	{303}{}{Pourquoi as-tu décidé de venir dans le royaume des Disciples ?}

{304}{}{Salutations, ma soeur. Est-ce que tu t'es occupé du chef des mutants à Necropolis ?}
{305}{}{Salutations, mon frère. Est-ce que tu t'es occupé du chef des mutants à Necropolis ?}
	{306}{}{J'y travaille encore. Je reviendrais.}
	{307}{}{Le chef des mutants est de l'histoire ancienne.}

# float after Harry is killed
{350}{}{Je te remercie d'avoir réussi à te débarraser des mutants à Necropolis.}

# Gain x Experience...
{400}{}{ pour avoir aidé Talius.}
