{100}{}{Voici un homme vêtu d'une armure en cuir poussiéreuse, d'un trench-coat et d'un masque à gaz.}
{101}{}{Voici Tycho, un des Rangers du Désert.}
{102}{}{Une nouvelle tête. Les voyageurs courent les rues ici. Mais tu n'as pas l'air comme les autres. Veux-tu te joindre à moi pour boire un verre ?}
	{103}{}{Excuse-moi mais je n'ai pas le temps.}
	{104}{}{Avec plaisir.}
	{105}{}{Que-Quoi ?}

{106}{}{Formidable. J'espère que tu ne vois pas d'inconvénient à déguster une boisson bien arrosée. Ils ne savent pas faire la bière ici.}
	{107}{}{Eh bien, quelle est ton histoire ?}
	{108}{}{Ouais, un verre d'eau. Qu'importe.}

{109}{}{Je pourrais te demander la même chose. Je pense que je devrais me présenter. Je m'appelle Tycho. Je suis originaire de l'Est, d'un endroit qui s'appelait autrefois le Nevada.}
	{110}{}{Ton voyage pour arriver jusqu'ici a du être long...}
	{111}{}{Comment as-tu fait pour survivre à tous les dangers ?}

{112}{}{Ouais, en effet. J'avais décidé de prendre du bon temps. Cet endroit peut être sympa... enfin il le sera quand quelqu'un l'aura débarrassé de ses ordures.}
	{113}{}{Pourquoi ne t'en charges-tu pas ?}
	{114}{}{Oui, j'ai remarqué. Que sais-tu sur ces connards ?}

{115}{}{Je suis bien entraîné et bien armé. Mon grand-père était guide et il a appris à mon père tout ce qu'il savait. Mon père me l'a ensuite appris à son tour. Alors j'en connais assez pour ne pas boire d'eau qui brille et pour ne pas trop parler.}
	{116}{}{Intéressant. Merci pour le verre.}
	{117}{}{Vraiment ? Difficile de survivre de nos jours. Tu dois connaître beaucoup de choses.}

{118}{}{Après tout, je préférerais ne pas croiser Killian. Il nettoiera cette ville lorsqu'il y viendra. C'est un homme bon, et je pèse mes mots. Mais méfie-toi de ce Gizmo. Il me fait penser à un autre sale type dont mon père m'avait parlé de retour de Las Vegas.}
	{119}{}{Merci pour le conseil et pour le verre.}

{120}{}{Il y a deux types de vermines ici. Les Skulz sont une bande qui agissent pour le compte de Marcelles. Ce sont des andouilles de seconde zone. Mais les autres obéissent à un sale type dont tu devines sans doute le nom. Il tient le casino. Ces types sont organisés et dangereux.}
	{121}{}{Je vois. Merci pour le renseignement.}

{122}{}{Ouais, eh bien, ma famille m'a appris tout ce qu'il fallait savoir pour survivre. Comme de ne pas boire de l'eau claire, exempte d'insectes et de mousse. Seules les eaux empoisonnées ou radioactives peuvent être si claires dans le désert ! Tout comme un tas d'autres petites choses auxquelles il faut faire gaffe.}
	{123}{}{Comme quoi ?}

{124}{}{Eh bien, si tu as un peu de temps, je pourrais te donner quelques tuyaux.}
	{125}{}{Certainement, ce serait formidable.}
	{126}{}{Excuse-moi mais je n'ai pas vraiment le temps.}

{127}{}{Eh, pas si vite. Nous n'avons pas terminé les présentations, tu t'en souviens ? C'est quoi ton nom ?}
	{128}{}{Je m'appelle }
	{129}{}{.}
	{130}{}{Cela ne te regarde pas, imbécile.}

{131}{}{Cette rencontre fut un plaisir ! Fais attention à toi.}
{132}{}{Hé, hé, tu peux ranger ton impolitesse. Si tu continues comme ça, je te conseille de foutre le camp !}
	{133}{}{Frappe-moi.}
	{134}{}{Qu'importe. Au revoir.}

{135}{}{Que veux-tu ?}
	{136}{}{Excuse-moi d'abuser de ton temps. Va te faire voir.}
	{137}{}{J'ai besoin de renseignements sur les bandits dans le coin.}
	{138}{}{J'ai besoin de renseignements sur la ville.}

{139}{}{Rebonjour. Que puis-je faire pour toi ?}
	{140}{}{Killian veut que je nettoie cette ville et j'aimerais que tu m'aides.}

{141}{}{Eh bien, voici le Skum Pitt, la retraite des voyous. A l'Ouest d'ici se trouve le grand casino de Gizmo. On dit que les jeux y sont truqués. Au Sud se trouve la Crash House, tenue par Marcelles, où tu peux dormir pur pas trop cher. Ensuite, il y a chez Killian. Killian tient un magasin et il fait également régner la loi dans cette ville. C'est un homme bien. Encore au Sud vit Doc Morbide, un gars assez marrant, si tu vois ce que je veux dire.}
{142}{}{J'espère que ces petites indications te seront utiles.}
{143}{}{}

{144}{}{On dit que tu as eu quelques contacts avec Gizmo. Je me méfierais de ce tas de graisse si j'étais toi...}
	{145}{}{Ce sont mes affaires.}
	{146}{}{Ouais, je travaille pour Gizmo désormais. Ca te va ?}

{147}{}{Très bien mais fais quand même attention à toi. Gizmo n'est pas du genre à avoir beaucoup de respect pour ses employés.}
{148}{}{Il est important de souligner que ton employeur est responsable de tous les malheurs de cette ville. N'espère rien de quiconque et surtout pas de Gizmo ! Dommage. Tu aurais été capable d'améliorer la situation de cette ville...}

{149}{}{Que puis-je pour toi ?}
	{150}{}{Des recommandations ?}
	{151}{}{Merci de ton aide. Je pense qu'il est temps de nous séparer.}
{152}{}{Ouais, je préfère rester loin de ce qui a fait ça. Sérieusement, je n'ai jamais rien vu de tel. Je pense que nous devrions partir et vite.}
{153}{}{Très bien. Je dois dire que ce fut un honneur et un plaisir.}
{154}{}{Fais attention aux zones rouges radioactives ! De toute évidence, cet endroit a été touché par une bombe nucléaire et les phénomènes de radiations en cascades sont très dangereux. Je te conseille d'éviter à tout prix cet endroit si tu le peux.}
{155}{}{Remarque l'absence d'animaux dans les environs. Et tous ces ossements. Une terrible créature doit vivre ici. Ne te sépare pas de ton arme !}
{156}{}{Un site militaire comme celui-là doit nécessairement disposer d'une salle de contrôle centrale quelque part.}
{157}{}{Je parie que nous pourrions accéder à ces générateurs de champs de forces en utilisant, par exemple, un ordinateur de contrôle de champs de forces.}
{158}{}{On raconte des choses étranges au sujet de Nécropolis, la ville des morts. Fais très attention car tout pourrait aller très vite.}
	{159}{}{Je dois changer ma formation.}
{160}{}{A quelle distance veux-tu que je me mette ?}
	{161}{}{Ne t'éloigne pas.}
	{162}{}{Reste à distance.}
	{163}{}{Déplace-toi un peu plus loin.}
	{164}{}{Quelles sont tes compétences en matière d'armes ?}
{165}{}{J'ai suivi un bon entraînement de Guide. Je suis doué avec les pistolets et les petites mitrailettes. Je peux aussi utiliser une lance, au cas où.}
{166}{}{Euh, qu'importe.}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#
{167}{}{Ouais, si tu aimes ton lézard bien cuit.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{Eh bien il est presque temps. Mon ami, allons nettoyer les rues ! Gizmo est une très bonne cible, si je peux me permettre.}
{169}{}{Eh bien il est presque temps. Mon amie, allons nettoyer les rues ! Gizmo est une très bonne cible, si je peux me permettre.}
{170}{}{Oui ?}
	{171}{}{Après tout, je pense que nous devrions rester ensemble.}
	{172}{}{Rien. Peu importe.}
{173}{}{ points d'expérience pour avoir recruté Tycho, le guide du désert.}

# for Fallout Fixt:
	{174}{}{Nous être amis ?}

{175}{}{Tu va payer.}
{176}{}{C'est l'heure de la revanche.}
{177}{}{Les citoyens de Dépôtville doivent être vengés.}
{178}{}{Tu te crois au-dessus des lois ?}
{179}{}{Je ne tolère pas les ordures comme toi.}
{180}{}{Toutes les actions ont des conséquences.}

{181}{}{Tu vois : Tycho.}

# Healing
{300}{}{Ok, tout est parfait.}
{301}{}{Je n'ai rien qui pourrais nous freiner.}
{302}{}{Tu n'aurais rien pour m'aider ?}
{303}{}{Peut-être que tu devrais jeter un oeil sur ma blessure.}

# Pushing
{310}{}{Je bouge.}
{311}{}{Si tu le dit.}
{312}{}{C'est mieux ?}
{313}{}{On se détend, tout va bien.}

#
# Tycho Tell-Me-Abouts
#

{1000}{}{Dépôtville}
{1001}{}{Rangers}
{1002}{}{Puce}
{1003}{}{Guerre}
{1004}{}{Désert}
{1005}{}{Disciples}
{1006}{}{Cathédrale}
{1007}{}{Garl}
{1008}{}{Maître}
{1009}{}{Unité}
{1010}{}{Set}
{1011}{}{Réservoir}
{1012}{}{Nécropolis}
{1013}{}{Hall}
{1014}{}{Bibliothèque}
{1015}{}{Dirigeant}
{1016}{}{Médecin}
{1017}{}{Guérison}
{1018}{}{Abri}
{1019}{}{Abri-13}
{1020}{}{Abris}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Cimetière de L.A.}
{1024}{}{Sables}
{1025}{}{Ombragés}
{1026}{}{Centre}
{1027}{}{Casino}
{1028}{}{Magasin}
{1029}{}{Griffemort}
{1030}{}{Exode}
{1031}{}{Initiés}
{1032}{}{Paladins}
{1033}{}{Scribes}
{1034}{}{Enfants}
{1036}{}{Confrérie}
{1037}{}{Cuves}
{1038}{}{Base}
{1039}{}{Militaire}
{1041}{}{Apocalypse}
{1042}{}{Mutants}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Alcool}
{1052}{}{stimulants}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Régulateurs}
{1058}{}{Fouineurs}
{1059}{}{Ecorcheurs}
{1060}{}{Nicole}
{1061}{}{Lieutenant}
{1062}{}{Médiums}
{1063}{}{Expériences}
{1064}{}{Police}
{1065}{}{Marchands}

{1100}{}{Eh bien, Dépôtville c'est pas le paradis mais c'est une ville intéressante. Elle a un certain potentiel, même si je ne sais pas si construire avec les déchêts du passé est la meilleure solution pour l'avenir.}
{1101}{}{Nous, les guides, venons de l'Est, de ce qui s'appelait autrefois le Nevada. Notre héritage remonte à l'époque des Guides du Texas. Nous apprenons les techniques de survie et de combat pour affronter le monde et survivre.}
{1102}{}{Cela fait longtemps que je n'ai pas vu une relique de la vieille technologie, comme une puce d'eau. Je pense que vous devriez compter sur vous-mêmes plutôt que sur un mécanisme que vous ne pouvez même pas réparer.}
{1103}{}{La Guerre fut le résultat de l'avidité et de la folie humaine. Espérons que nous en ayons suffisamment appris pour qu'une telle folie ne se reproduise pas.}
{1104}{}{Le désert est hostile et dangereux, même pour les voyageurs avertis. Les radiations et les créatures étranges y grouillent. Fais preuve de prudence et n'oublie pas que tout ce que tu vois et entends est un indice.}
{1105}{}{Désolé mais je ne peux pas t'aider.}
{1106}{}{Désolé mais je ne peux pas t'aider.}
{1107}{}{Désolé mais je ne peux pas t'aider.}
{1108}{}{Désolé mais je ne peux pas t'aider.}
{1109}{}{Désolé mais je ne peux pas t'aider.}
{1110}{}{Désolé mais je ne peux pas t'aider.}
{1111}{}{Désolé mais je ne peux pas t'aider.}
{1112}{}{La Cité de la Mort porte bien son nom. Elle est située sur l'ancienne petite ville de Bakersfield. Et aujourd'hui, elle abrite les Goules et autres créatures.}
{1113}{}{Désolé mais je ne peux pas t'aider.}
{1114}{}{Désolé mais je ne peux pas t'aider.}
{1115}{}{Désolé mais je ne peux pas t'aider.}
{1116}{}{Désolé mais je ne peux pas t'aider.}
{1117}{}{Désolé mais je ne peux pas t'aider.}
{1118}{}{J'ai entendu parler des grands Abris souterrains. Mais je n'en sais pas plus.}
{1119}{}{J'ai entendu parler des grands Abris souterrains. Mais je n'en sais pas plus.}
{1120}{}{J'ai entendu parler des grands Abris souterrains. Mais je n'en sais pas plus.}
{1121}{}{Killian est un type bien qui fait un travail difficile.}
{1122}{}{Gizmo est... Il a très mal agi avec moi. Mais il finira bien par le payer.}
{1123}{}{Le Cimetière de L.A. ? J'ai entendu dire que les bandes y vivaient et que c'était un endroit pénible.}
{1124}{}{Désolé mais je ne peux pas t'aider.}
{1125}{}{Désolé mais je ne peux pas t'aider.}
{1126}{}{Le Centre est une gigantesque communauté mercantile située au Sud de Dépôtville.}
{1127}{}{Le casino de Gizmo est bien le dernier endroit où j'aimerais me rendre, à moins de pouvoir m'attaquer à Gizmo en personne. Cela me ferait plaisir.}
{1128}{}{Killian possède un bon magasin à Dépôtville.}
{1129}{}{J'ai entendu parler de quelque chose de plus rapide, de plus grand et de plus redoutable que toutes les créatures existantes. Les survivants sont peu nombreux. D'énormes griffes et un comportement féroce.}
{1130}{}{Désolé mais je ne peux pas t'aider.}
{1131}{}{Désolé mais je ne peux pas t'aider.}
{1132}{}{Désolé mais je ne peux pas t'aider.}
{1133}{}{Désolé mais je ne peux pas t'aider.}
{1134}{}{Désolé mais je ne peux pas t'aider.}
{1136}{}{Désolé mais je ne peux pas t'aider.}
{1137}{}{Désolé mais je ne peux pas t'aider.}
{1138}{}{Les militaires disposaient de quelques bases secrètes dispersées dans le coin. Mais je ne sais pas où exactement.}
{1139}{}{Les militaires disposaient de quelques bases secrètes dispersées dans le coin. Mais je ne sais pas où exactement.}
{1141}{}{La catastrophe nucléaire fut le résultat de beaucoup de fierté et de stupidité. Maintenant, nous en payons le prix.}
{1142}{}{Il se passe des choses étranges là-bas. J'y ai vu des scorpions géants et des vaches à deux têtes et j'ai entendu dire que Nécropolis abritait des Goules à l'apparence humaine.}
{1143}{}{Désolé mais je ne peux pas t'aider.}
{1144}{}{Désolé mais je ne peux pas t'aider.}
{1145}{}{Désolé mais je ne peux pas t'aider.}
{1146}{}{Désolé mais je ne peux pas t'aider.}
{1147}{}{Désolé mais je ne peux pas t'aider.}
{1148}{}{Désolé mais je ne peux pas t'aider.}
{1149}{}{Désolé mais je ne peux pas t'aider.}
{1150}{}{Désolé mais je ne peux pas t'aider.}
{1151}{}{Je préfère une bonne bière brune ou peut-être un Nuka-Cola.}
{1152}{}{Si j'étais toi, j'éviterais les stimulants. Certes, ils peuvent t'aider à court terme, mais tu finiras par le payer.}
{1153}{}{Désolé mais je ne peux pas t'aider.}
{1154}{}{Désolé mais je ne peux pas t'aider.}
{1155}{}{Désolé mais je ne peux pas t'aider.}
{1156}{}{Désolé mais je ne peux pas t'aider.}
{1157}{}{Désolé mais je ne peux pas t'aider.}
{1158}{}{Désolé mais je ne peux pas t'aider.}
{1159}{}{Désolé mais je ne peux pas t'aider.}
{1160}{}{Désolé mais je ne peux pas t'aider.}
{1161}{}{Désolé mais je ne peux pas t'aider.}
{1162}{}{Tu veux parler de télépathie ? Hé, sérieusement... je ne te crois pas.}
{1163}{}{Désolé mais je ne peux pas t'aider.}
{1164}{}{Désolé mais je ne peux pas t'aider.}
{1165}{}{Quelques marchands du Centre viennent régulièrement à Dépôtville et dans d'autres villes.}

{1999}{}{Je me sens plus fort maintenant !}
	{2000}{}{Discutons de notre tactique de combat.}
{2001}{}{Oui ?}
	{2010}{}{Utilise ta meilleure arme.}
	{2011}{}{Change ton armure.}
	{2012}{}{Préfère le combat à distance plutôt que rapproché.}
	{2013}{}{Préfère le combat rapproché plutôt qu'à distance.}
	{2014}{}{Choisis la distance qui t'arrange.}
	{2015}{}{C'est tout pour l'instant.}
{2100}{}{Très bien.}
{2101}{}{Bien reçu.}
{2102}{}{Ah, il était temps.}

# Any recommendations? NEW
{2200}{}{Je te recommenderai d'en finir avec Gizmo, si je peux me permettre.}

# Too many party members
{2500}{}{En y pensant, tu sais quoi ? Je n'aime pas trop l'idée de voyager avec une escouade aussi grande. Avec une équipe plus petite je viendrais avec plaisir.}
{2510}{}{Très bien.}
{2511}{}{[Terminé]}

{3500}{}{Je suis bon pour les béquilles ou le fauteil roulant juste là.}
{3501}{}{Je suis luminescent comme un néon là. Tu n'aurais pas de l'anti-rad ?}
{3502}{}{J'ai du poinson dans mes veines. Tu n'aurais pas un peu d'antidote ?}

# Mariposa prisoner
{3503}{}{Enfin un visage amical. Je te suis !}
