{100}{}{Voici Victor.}
{101}{}{Voici le membre d'une bande.}
{102}{}{Aaaahhh...}
{103}{}{Du sang frais. Hé. Hé, hé.}
{104}{}{Hmm, ouais. Euh, je crois que je vais m'en aller.}
{105}{}{Tu n'es pas une personne très heureuse, n'est-ce pas ?}
{106}{}{Euh... Euh...}
{107}{}{En fait, je crois que je vais te garder un peu avec moi.}
{108}{}{Pourquoi dis-tu ça ? Je suis quelqu'un de très heureux. Oui, parce que ça saigne, et j'aime le sang.}
{109}{}{Tu sais que tu es complètement malade ?}
{110}{}{Hum, ouais. Au revoir.}
{111}{}{Ah, oui, c'est une appréciation artistique. Euh, je peux le comprendre. Je crois.}
{112}{}{Ne dis pas ça ! Ma mère disait ça tout le temps ! Je vais te le faire payer ! Je suis un gars bien, hein maman ?}
{113}{}{Quelqu'un qui me comprend ! Enfin !}
{114}{}{Rebonjour, camarade artiste.}
{115}{}{Ha ! Ha ! Hé hé hé ! Hi ha ha !}
{116}{}{Zzzzz}
{117}{}{Victor, t'ai-je déjà dit que tu étais complètement malade ?}
{118}{}{Euh, salut.}
