#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\modreact.h"

procedure start;    variable SrcObj := 0;    variable SrcIsParty := 0;
procedure critter_p_proc;//    script_action == 12
procedure damage_p_proc;//    script_action == 14
procedure destroy_p_proc;//    script_action == 18
procedure look_at_p_proc;//    script_action == 21
procedure map_enter_p_proc;//    script_action == 15
procedure pickup_p_proc;//    script_action == 4
procedure talk_p_proc;//    script_action == 11
procedure timed_event_p_proc;//    script_action == 22

procedure Shark01;
procedure Shark01a;
procedure Shark02;
procedure Shark03;
procedure Shark04;
procedure Shark04a;
procedure Shark04b;
procedure Shark05;
procedure Shark06;
procedure Shark07;
procedure Shark08;
procedure SharkEnd;

procedure SharkCombat;

import variable removal_ptr;
import variable Trish_ptr;

variable night_person;
variable wake_time;
variable sleep_time;
variable home_tile;
variable sleep_tile;

variable tmp_deset_tile := 7000;
variable tmp_hostile;
variable timer_set;
variable sleeping_disabled;
variable waypoint;

#define LVAR_Sleeping 							(5)

procedure start begin
	
end

procedure critter_p_proc
begin
	if (global_var(DUDE_ENEMY_SKULZ) == 1) then begin
		if (obj_can_see_obj(self_obj, dude_obj)) then begin
			attack(dude_obj);
		end
	end
	if (tmp_hostile) then begin// This must come FIRST as an if/then/else before "attack dude" type code, otherwise it runs too soon and can override other attack calls
		tmp_hostile := 0;
		attack(dude_obj);
	end
	else begin
		if ((global_var(DESTROY_VATS_10) == 1) and (local_var(6) == 0)) then begin
			add_timer_event(self_obj, game_ticks(3), 3);
			set_local_var(6, 1);
		end
		else begin
			if (global_var(BUST_SKULZ) != 2) then begin
				if (tile_num(self_obj) != tmp_deset_tile) then begin
					animate_move_obj_to_tile(self_obj, tmp_deset_tile, 0);
				end
				else begin
					if (waypoint == 1) then begin
						waypoint := 0;
						tmp_deset_tile := 33519;
					end
				end
				if (sleeping_disabled == 0) then begin
					sleeping
				end
			end
		end
	end
end

procedure damage_p_proc
begin
	if ((source_obj == dude_obj) and (map_var(0) == 1)) then begin
		set_map_var(1, 1);
	end
end

procedure destroy_p_proc
begin
	rm_timer_event(self_obj);

	if source_obj > 0 then begin  SrcObj := 0;  SrcIsParty := 0;  SrcObj := obj_pid(source_obj);  if party_member_obj(SrcObj) then begin  SrcIsParty := 1;  end  end    if (source_obj == dude_obj) or (SrcIsParty == 1) then begin
		set_global_var(DUDE_ENEMY_SKULZ, 1);
	end
	inc_evil_critter
	rm_timer_event(self_obj);
end

procedure look_at_p_proc
begin
	script_overrides;
	if (local_var(4)) then begin
		display_msg(message_str(SCRIPT_SHARK, 100));
	end
	else begin
		display_msg(message_str(SCRIPT_SHARK, 101));
	end
end

procedure map_enter_p_proc
begin
	sleep_time := 2230;
	wake_time := 1530;
	home_tile := 20486;
	sleep_tile := 7000;
	critter_add_trait(self_obj, 1, 6, 14);
	critter_add_trait(self_obj, 1, 5, 58);
	if ((global_var(BUST_SKULZ) == 2) or (global_var(DESTROY_VATS_10) == 1)) then begin
		move_to(self_obj, 7000, 0);
		if (metarule(22, 0) == 0) then begin    set_obj_visibility(self_obj, 1);    end//  MAKE INVISIBLE
		sleeping_disabled := 1;
		removal_ptr := self_obj;
	end
	else begin
		tmp_deset_tile := home_tile;
	end
end

procedure pickup_p_proc
begin
	tmp_hostile := 1;
end

procedure talk_p_proc
begin
	anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
	start_gdialog(387, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(4) == 0) then begin
		call Shark01;
	end
	else begin
		if (local_var(1) < 2) then begin
			call Shark08;
		end
		else begin
			call Shark06;
		end
	end
	gsay_end;
	end_dialogue;
end

procedure timed_event_p_proc
begin
	if (fixed_param == 1) then begin
		waypoint := 1;
		tmp_deset_tile := 26495;
	end
	else begin
		if (fixed_param == 2) then begin
			if (Trish_ptr != 0) then begin
				attack_complex(Trish_ptr, 0, 1, 0, 0, 30000, 0, 0);
			end
		end
		else begin
			if (fixed_param == 3) then begin
				float_msg(self_obj, message_str(SCRIPT_SHARK, 126), 2);
				add_timer_event(self_obj, game_ticks(5), 1);
				sleeping_disabled := 1;
			end
		end
	end
end

procedure Shark01
begin
	set_local_var(4, 1);
	gsay_reply(387, 103);
	giq_option(4, 387, 104, SharkCombat, 51);
	giq_option(4, 387, 105, Shark02, 50);
	giq_option(4, 387, 106, Shark03, 50);
	giq_option(5, 387, 107, Shark01a, 49);
	giq_option(-3, 387, 108, Shark05, 50);
end

procedure Shark01a
begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call Shark04;
	end
	else begin
		call Shark03;
	end
end

procedure Shark02
begin
	gsay_message(387, 109, 51);
	call SharkCombat;
end

procedure Shark03
begin
	variable LVar0 := 0;
	LVar0 := message_str(SCRIPT_SHARK, 110);
	if (get_critter_stat(dude_obj, STAT_gender) == 1) then begin
		LVar0 := LVar0 + message_str(SCRIPT_SHARK, 111);
	end
	else begin
		LVar0 := LVar0 + message_str(SCRIPT_SHARK, 112);
	end
	gsay_reply(387, LVar0);
	giq_option(4, 387, 113, SharkCombat, 50);
end

procedure Shark04
begin
	UpReactLevel
	gsay_reply(387, 114);
	giq_option(4, 387, 115, timed_event_p_proc, 50);
	giq_option(4, 387, 116, Shark04b, 49);
	giq_option(4, 387, 117, Shark04a, 50);
	giq_option(4, 387, 118, SharkCombat, 51);
end

procedure Shark04a
begin
	if (not(is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0)))) then begin
		DownReactLevel
	end
	call Shark05;
end

procedure Shark04b
begin
	UpReactLevel
	add_timer_event(self_obj, game_ticks(3), 2);
end

procedure Shark05
begin
	gsay_message(387, 119, 50);
end

procedure Shark06
begin
	gsay_reply(387, 120);
	giq_option(4, 387, 121, Shark07, 50);
	giq_option(4, 387, 122, Shark03, 50);
	giq_option(-3, 387, 123, Shark05, 50);
end

procedure Shark07
begin
	gsay_message(387, 124, 50);
	call SharkCombat;
end

procedure Shark08
begin
	gsay_message(387, 125, 50);
	call SharkCombat;
end

procedure SharkCombat
begin
	tmp_hostile := 1;
end

procedure SharkEnd
begin
end

