#include "..\headers\define.h"
#include "..\headers\command.h"

procedure start;
procedure start
begin
	display_msg("FieldF: tile_num " + self_tile + ", elevation " + self_elevation + ", map " + cur_map_index);
end

/*

#include "..\headers\define.h"

procedure start;
procedure use_p_proc;//    script_action == 6
procedure spatial_p_proc;//    script_action == 2
procedure turn_field_on;
procedure turn_field_off;
procedure toggle_field;

variable initial :=  0;
variable on_tile;

import variable field_change;


procedure start
begin
	display_msg("FieldF: tile_num " + self_tile + ", elevation " + self_elevation + ", map " + cur_map_index);
	if (map_first_run) then begin
		//display_msg("INIT FIELDF.SSL at map number " + cur_map_index + " and elevation " + elevation(self_obj));
		//display_msg("Please take a screenshot now and send to Sduibek. Thanks!");
	end
	if (not(initialized)) then begin
		if (self_pid == PID_NS_PAIN_FIELD) then begin
			set_map_var(0, self_obj);
		end
		call use_p_proc;
		initial :=  1;
	end
	else begin
		if (script_action == 6) then begin//use_p_proc - Use, Activate, or Manipulate the Object or Item
			call use_p_proc;
		end
		else begin
			if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
				call spatial_p_proc;
			end
		end
	end
end

procedure use_p_proc
begin
	if (global_var( GVAR_FORCE_FIELDS_OFF )) then begin
		field_change := "off";
	end
	if (source_obj != dude_obj) then begin
		if (field_change == "toggle") then begin
			call toggle_field;
		end
		else begin
			if (field_change == "off") then begin
				call turn_field_off;
			end
			else begin
				if (field_change == "on") then begin
					call turn_field_on;
				end
			end
		end
	end
end

procedure spatial_p_proc
begin
	if (map_var(14) == 0) then begin
		if (tile_num(source_obj) == self_tile) then begin
			if (on_tile) then begin
				on_tile := 1;
				critter_dmg( source_obj, random(10, 20), DMG_electrical );
			end
		end
		else begin
			on_tile := 0;
		end
	end
end

procedure turn_field_on
begin
	set_map_var(14, 0);
	if not(is_loading_game) then begin    set_self_visible;    end//  MAKE VISIBLE
end

procedure turn_field_off
begin
	if not(is_loading_game) then begin    set_self_invisible;    end//  MAKE INVISIBLE
	set_local_var(14, 1);
end

procedure toggle_field
begin
	if (map_var(14) == 1) then begin
		call turn_field_on;
	end
	else begin
		call turn_field_off;
	end
end

*/
