#include "..\headers\define.h"

procedure start;    variable SrcObj := 0;    variable SrcIsParty := 0;
procedure critter_p_proc;//    script_action == 12
procedure destroy_p_proc;//    script_action == 18
procedure talk_p_proc;//    script_action == 11
procedure Sarah00;
procedure Sarah01;
procedure sarah02;
procedure Sarah03;
procedure Sarah04;
procedure Sarah05;
procedure Sarah06;
procedure Sarah07;
procedure Sarah08;
procedure Sarah09;
procedure Sarah10;
procedure SarahEnd;

variable initial :=  0;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;



procedure start
begin
	
	
	if not(initial) then begin
		set_self_team(TEAM_NECROPOLIS_MUTANT );
		set_self_ai( AI_BRAINWASHED_CHILDREN );
		initial :=  1;
	end
	else begin
		if (script_action == 12) then begin//<-- critter_p_proc - (can also be "Critter_Action") - do they see you, should they wander, should they attack you, etc..
			call critter_p_proc;
		end
		else begin
			if (script_action == 18) then begin//destroy_p_proc - Object or Critter has been killed or otherwise eradicated. Fall down go boom.
				call destroy_p_proc;
			end
			else begin
				if (script_action == 11) then begin//<--- talk_p_proc (Face icon), can also call "do_dialogue" or "do_dialog"
					call talk_p_proc;
				end
			end
		end
	end
end

procedure critter_p_proc
begin
	if (map_var(8) == 3) then begin
		if (local_var(4) == 0) then begin
			if (tile_distance_objs(self_obj, dude_obj) < 12) then begin
				if (obj_can_see_obj(self_obj, dude_obj)) then begin
					dialogue_system_enter;
				end
			end
		end
	end
end

procedure destroy_p_proc
begin

	if source_obj > 0 then begin  SrcObj := 0;  SrcIsParty := 0;  SrcObj := obj_pid(source_obj);  if party_member_obj(SrcObj) then begin  SrcIsParty := 1;  end  end    if (source_obj == dude_obj) or (SrcIsParty == 1) then begin
		if (((global_var(NUM_BAD_MONSTERS_KILLED) + global_var(NUM_GOOD_MONSTERS_KILLED)) >= 25) and ((global_var(NUM_GOOD_MONSTERS_KILLED) > (2 * global_var(NUM_BAD_MONSTERS_KILLED))) or (global_var(BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(BERSERKER_REPUTATION, 1);
			set_global_var(CHAMPION_REPUTATION, 0);
		end
		if (((global_var(NUM_BAD_MONSTERS_KILLED) + global_var(NUM_GOOD_MONSTERS_KILLED)) >= 25) and ((global_var(NUM_BAD_MONSTERS_KILLED) > (3 * global_var(NUM_GOOD_MONSTERS_KILLED))) or (global_var(CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(CHAMPION_REPUTATION, 1);
			set_global_var(BERSERKER_REPUTATION, 0);
		end
		set_global_var(NUM_GOOD_MONSTERS_KILLED, global_var(NUM_GOOD_MONSTERS_KILLED) + 1);// THIS MONSTER WAS A GOOD GUY. INCREASE GoodGuysKilled COUNTER
		if ((global_var(NUM_GOOD_MONSTERS_KILLED) % 2) == 0) then begin
			set_global_var(PLAYER_REPUTATION_GENERAL, (global_var(PLAYER_REPUTATION_GENERAL) - 1));
		end
	end
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	if (local_var(4)) then begin
		if (map_var(8) == 3) then begin
			float_msg(self_obj, message_str(SCRIPT_SARAH, 105), 0);
		end
		else begin
			if ((get_critter_stat(dude_obj, STAT_iq) < 4) and (dude_is_male)) then begin
				float_msg(self_obj, message_str(SCRIPT_SARAH, 117), 0);
			end
			else begin
				if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
					call Sarah10;
				end
				else begin
					float_msg(self_obj, message_str(SCRIPT_SARAH, 118), 0);
				end
			end
		end
	end
	else begin
		set_local_var(4, 1);
		start_gdialog(662, self_obj, 4, -1, -1);
		gsay_start;
		if (map_var(8) == 3) then begin
			call Sarah00;
		end
		else begin
			call Sarah05;
		end
		gsay_end;
		end_dialogue;
	end
end

procedure Sarah00
begin
	gsay_reply(662, 100);
	giq_option(-3, 662, 101, Sarah01, 51);
	giq_option(4, 662, 102, SarahEnd, 51);
	giq_option(5, 662, 103, Sarah01, 51);
	giq_option(7, 662, 104, sarah02, 51);
end

procedure Sarah01
begin
	gsay_message(662, 105, 51);
end

procedure sarah02
begin
	gsay_reply(662, 106);
	giq_option(7, 662, 107, Sarah03, 51);
	giq_option(7, 662, 108, Sarah04, 51);
end

procedure Sarah03
begin
	gsay_reply(662, 109);
	giq_option(7, 662, 110, Sarah01, 51);
	giq_option(7, 662, 111, Sarah04, 51);
end

procedure Sarah04
begin
	gsay_message(662, 112, 51);
end

procedure Sarah05
begin
	gsay_reply(662, 113);
	giq_option(-3, 662, 114, Sarah06, 50);
	giq_option(4, 662, 115, Sarah07, 50);
	giq_option(6, 662, 116, Sarah09, 50);
end

procedure Sarah06
begin
	gsay_message(662, 117, 50);
end

procedure Sarah07
begin
	gsay_reply(662, 118);
	giq_option(4, 662, 119, SarahEnd, 50);
	giq_option(6, 662, 120, Sarah08, 50);
end

procedure Sarah08
begin
	gsay_reply(662, 121);
	giq_option(4, 662, 119, SarahEnd, 51);
end

procedure Sarah09
begin
	gsay_message(662, 122, 50);
end

procedure Sarah10
begin
	float_msg(self_obj, message_str(SCRIPT_SARAH, 123), 0);
end

procedure SarahEnd
begin
end



