#include "..\headers\define.h"

procedure start;
procedure description_p_proc;//    script_action == 3
procedure spatial_p_proc;//    script_action == 2
procedure use_skill_on_p_proc;//    script_action == 8

variable initial :=  0;

import variable removal_ptr;


procedure start
begin
	if (map_first_run) then begin
		//display_msg("INIT VATALERT.SSL at map number " + cur_map_index + " and elevation " + elevation(self_obj));
		//display_msg("Please take a screenshot now and send to Sduibek. Thanks!");
	end
	if not(initial) then begin
		initial :=  1;
	end
	else begin
		if (script_action == 3) then begin//DETAILED ON-CLICK DESCRIPTION (Binoculars icon) - description_p_proc
			call description_p_proc;
		end
		else begin
			if (script_action == 2) then begin// spatial_p_proc - Player is on or near hex of the location or object this script is using
				call spatial_p_proc;
			end
			else begin
				if (script_action == 8) then begin//<-- use_skill_on_p_proc
					call use_skill_on_p_proc;
				end
			end
		end
	end
end

procedure description_p_proc
begin
	variable LVar0 := 0;
	LVar0 := message_str(SCRIPT_VATALERT, 100);
	if (not(local_var(0))) then begin
		if (not(is_success(do_check(dude_obj, STAT_pe, dude_awareness)))) then begin
			LVar0 := message_str(SCRIPT_VATALERT, 101);
		end
		else begin
			set_local_var(0, 1);
		end
	end
	display_msg(LVar0);
end

procedure spatial_p_proc
begin
	if (map_var(7) == 0) then begin
		if (not(is_success(do_check(dude_obj, STAT_lu, 0)))) then begin
			set_global_var(VATS_ALERT, 1);
			set_map_var(7, 1);
			display_msg(message_str(SCRIPT_VATALERT, 102));
			move_to(self_obj, 7000, 0);
			removal_ptr := self_obj;
		end
	end
	else begin
		display_msg(message_str(SCRIPT_VATALERT, 103));
	end
end

procedure use_skill_on_p_proc
begin
	if (action_being_used == SKILL_TRAPS) then begin//-- TRAPS
		if (local_var(0)) then begin
			script_overrides;
			if (is_success(roll_vs_skill(dude_obj, SKILL_TRAPS, 0))) then begin
				display_msg(message_str(SCRIPT_VATALERT, 104));
				move_to(self_obj, 7000, 0);
				removal_ptr := self_obj;
				set_map_var(12, 1);
			end
			else begin
				display_msg(message_str(SCRIPT_VATALERT, 105));
			end
		end
	end
end



