#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\modreact.h"

procedure start;    variable SrcObj := 0;    variable SrcIsParty := 0;
procedure Critter_Action;//    script_action == 12
procedure damage_p_proc;//    script_action == 14
procedure description_p_proc;//    script_action == 3
procedure destroy_p_proc;//    script_action == 18
procedure look_at_p_proc;//    script_action == 21
procedure talk_p_proc;//    script_action == 11

procedure alya00;
procedure alya01;
procedure alya02;
procedure alya03;
procedure alya04;
procedure alya05;
procedure alya06;
procedure alya07;
procedure alya08;
procedure alya09;
procedure alya10;
procedure alyaend;

procedure combat;

variable tmp_hostile;
variable initial :=  0;
variable rndz;

procedure PickDeadBodyType;
variable DeathType := 56;


procedure start
begin
	if global_var(GVAR_SHADY_SANDS_WAS_INVADED) then begin
		if (cur_map_index == MAP_RAIDERS) then begin //  RAIDERS - KHANS
			if (local_var(6) != 1) then begin
				set_local_var(6, 1);
				call PickDeadBodyType;
				kill_critter(self_obj, DeathType);
			end
		end
	end
	else begin
		

		if not(initial) then begin
			initial :=  1;
			critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM, 6);
			critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET, 21);
			debug_msg("ALYA init.");
		end
		if (script_action == 21) then begin//MOUSE-OVER DESCRIPTION -- look_at_p_proc - (usually brief length. hovered mouse over object, haven't clicked on it.)
			call look_at_p_proc;
		end
		else begin
			if (script_action == 3) then begin//DETAILED ON-CLICK DESCRIPTION (Binoculars icon) - description_p_proc
				call description_p_proc;
			end
			else begin
				if (script_action == 11) then begin//<--- talk_p_proc (Face icon), can also call "do_dialogue" or "do_dialog"
					call talk_p_proc;
				end
				else begin
					if (script_action == 22) then begin//<-- timed_event_p_proc -- called by ADD_TIMER_EVENT commands. "fixed_param==#" in this procedure is the number of the event in question (i.e. Add_Timer_Event dude,5,1 would be fixed_param 1)
						if (tile_distance_objs(self_obj, dude_obj) < 8) then begin
							call combat;
						end
					end
					else begin
						if (script_action == 4) then begin//<---caught stealing! (pickup_p_proc)
							tmp_hostile := 1;
						end
						else begin
							if (script_action == 12) then begin//<-- critter_p_proc - (can also be "Critter_Action") - do they see you, should they wander, should they attack you, etc..
								call Critter_Action;
							end
							else begin
								if (script_action == 14) then begin//<-- damage_p_proc - has this Critter or Object been shot, hit with TNT, punched, etc.
									call damage_p_proc;
								end
								else begin
									if (script_action == 18) then begin//destroy_p_proc - Object or Critter has been killed or otherwise eradicated. Fall down go boom.
										call destroy_p_proc;
									end
								end
							end
						end
					end
				end
			end
		end
	end
end

procedure alya00
begin
	gsay_reply(143, 101);
	if ((global_var(TANDI_RESCUE) == 1) and (global_var(TANDI_TALKED_ABOUT) == 1)) then begin
		giq_option(4, 143, 102, alya01, 50);
	end
	if (dude_is_male) then begin
		giq_option(4, 143, 103, alya02, 50);
	end
	giq_option(4, 143, 104, alya03, 50);
	giq_option(4, 143, 105, alyaend, 50);
	giq_option(-3, 143, 106, alya05, 50);
end

procedure alya01
begin
	gsay_message(143, 107, 50);
end

procedure alya02
begin
	gsay_message(143, 108, 50);
	call combat;
end

procedure alya03
begin
	gsay_reply(143, 109);
	giq_option(4, 143, 110, alya04, 50);
	giq_option(4, 143, 111, alya09, 50);
	giq_option(4, 143, 112, alyaend, 50);
end

procedure alya04
begin
	gsay_reply(143, 113);
	giq_option(4, 143, 114, alya06, 50);
	giq_option(4, 143, 115, alya08, 50);
	giq_option(4, 143, 116, alyaend, 50);
end

procedure alya05
begin
	gsay_message(143, 117, 50);
end

procedure alya06
begin
	gsay_reply(143, 118);
	giq_option(4, 143, 119, alya07, 50);
	giq_option(4, 143, 120, combat, 50);
	giq_option(4, 143, 121, alyaend, 50);
end

procedure alya07
begin
	gsay_message(143, 122, 50);
	call combat;
end

procedure alya08
begin
	gsay_message(143, 123, 50);
	add_timer_event(self_obj, game_ticks(15), 1);
end

procedure alya09
begin
	gsay_message(143, 124, 50);
end

procedure alya10
begin
	gsay_message(143, 125, 50);
end

procedure alyaend
begin
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	if (global_var(MISTAKEN_ID) == 1) then begin//Raiders think you are Garl's father
		float_msg(self_obj, message_str(SCRIPT_GENRAIDR, random(102, 106)), 8);
	end
	else begin
		set_local_var(7, 1);
		set_local_var(3, 1);
		get_reaction
		start_gdialog(143, self_obj, 4, -1, -1);
		gsay_start;
		if (local_var(4) == 5) then begin
			call alya10;
		end
		else begin
			set_local_var(4, local_var(4) + 1);
			call alya00;
		end
		gsay_end;
		end_dialogue;
	end
end

procedure combat
begin
	if (global_var(MISTAKEN_ID) == 1) then begin//Raiders think you are Garl's father
critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM, 87);
	end
	tmp_hostile := 1;
end

procedure Critter_Action
begin
//	variable LVar0 := 0;
//	rndz := random(0, 500);
//	set_local_var(10, game_time);
//	set_local_var(11, game_time + 5);

	if (global_var(TANDI_HIRELING_STATUS) == 2) then begin
		set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
	end
	else begin
		if (global_var(MISTAKEN_ID)) then begin//Raiders think you are Garl's father
			variable LVar0 := 0;
			rndz := random(0, 500);
			set_global_var(ENEMY_RAIDERS, 0);
			if ((tile_distance_objs(self_obj, dude_obj) < 5) and (rndz == 0)) then begin
				LVar0 := tile_num_in_direction(tile_num(self_obj), random(0, 5), 3);
				if ((tile_distance(tile_num(self_obj), LVar0) > 2) and (rndz == 0)) then begin
					if (rndz == 0) then begin
						float_msg(self_obj, message_str(SCRIPT_GENRAIDR, random(102, 106)), 8);
					end
					animate_move_obj_to_tile(self_obj, LVar0, 0);
				end
			end
		end
		else begin
			if global_var(TANDI_ESCAPE) then begin
				set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
			end
			if (obj_can_see_obj(self_obj, dude_obj)) then begin
				if (global_var(RAID_LOOTING)) then begin//  "RAID_LOOTING" (are you stealing from them)
					set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
				end
			end
			if (map_var(2) == 1) then begin
				set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
			end
		end
	end
	if (global_var(ENEMY_RAIDERS) and obj_can_see_obj(self_obj, dude_obj)) then begin
		tmp_hostile := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		tmp_hostile := 0;
	end
	if (tmp_hostile) then begin// This must come FIRST as an if/then/else before "attack dude" type code, otherwise it runs too soon and can override other attack calls
		tmp_hostile := 0;
		set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
		attack(dude_obj);
	end
end

procedure damage_p_proc
begin
	if source_obj > 0 then begin  SrcObj := 0;  SrcIsParty := 0;  SrcObj := obj_pid(source_obj);  if party_member_obj(SrcObj) then begin  SrcIsParty := 1;  end  end    if (source_obj == dude_obj) or (SrcIsParty == 1) then begin
		if (global_var(MISTAKEN_ID) == 0) then begin//PC was (is?) not mistaken for Garl's father
			set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
		end
	end
end



procedure destroy_p_proc
begin
	set_global_var(TOTAL_RAIDERS, (global_var(TOTAL_RAIDERS) - 1));// Number of raiders left
	if source_obj > 0 then begin  SrcObj := 0;  SrcIsParty := 0;  SrcObj := obj_pid(source_obj);  if party_member_obj(SrcObj) then begin  SrcIsParty := 1;  end  end    if (source_obj == dude_obj) or (SrcIsParty == 1) then begin
		set_global_var(ENEMY_RAIDERS, 1);//ENEMY_RAIDERS
		set_global_var(GARLS_FRIEND, 0);//GARLS_FRIEND
	end
	rm_timer_event(self_obj);

	inc_evil_critter
//
// "ARMOR DESTROY ON DEATH" MOD:
//
fixt_destroy_armor
	rm_timer_event(self_obj);
end

procedure description_p_proc
begin
	if not(local_var(7)) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_ALYA, 200));
	end
	set_local_var(7, 1);
end

procedure look_at_p_proc
begin
	script_overrides;
	if not(local_var(7)) then begin
		display_msg(message_str(SCRIPT_ALYA, 100));
	end
	else begin
		display_msg(message_str(SCRIPT_ALYA, 200));
	end
end

procedure PickDeadBodyType
begin
	pick_dead_body_type
end
