/*

   Interface Upscaled - Warning message

*/

#include "define.h"
#include "sfall/sfall.rotators.h"

procedure start;

procedure warning_resolution;
procedure warning_interface;

variable ini_val;

procedure start begin
   if (game_loaded) then begin
      set_global_script_type(0);

      if (get_screen_width < 890) or (get_screen_height < 720) then begin
         call warning_resolution in 1;
      end
      else begin
         ini_val := get_ini_setting("ddraw.ini|Interface|ExpandWorldMap");
         if (ini_val <= 0) then begin
            call warning_interface in 1;
         end
      end
   end
end

procedure warning_resolution begin
   ini_val := get_ini_setting("f2_res.ini|MAIN|SCALE_2X");
   if (ini_val > 0) then
      create_message_window("Warning:\nScreen resolution too low\nDisable 'SCALING X2' in graphic settings!");
   else
      create_message_window("Warning:\nScreen resolution too low\nResolution for 'Interface Upscaled'-mod must be at least 890x720px!");
end

procedure warning_interface begin
   create_message_window("WARNING:\n'ExpandWorldMap' in ddraw.ini disabled\n'Interface Upscaled'-mod will not work correctly!");
end
