/*

   Brotherhood - Darrel
   Guy next to Cabbot.

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_DARREL
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BOS)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure damage_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;

procedure start_dialogue;

procedure Darrel01;
procedure Darrel02;
procedure Darrel02a;
procedure Darrel02b;
procedure Darrel02c;
procedure Darrel03;
procedure Darrel04;
procedure Darrel05;
procedure Darrel06;
procedure Darrel07;
procedure Darrel08;
procedure Darrel09;
procedure Darrel10;
procedure Darrel11;
procedure Darrel12;
procedure Darrel13;
procedure Darrel14;
procedure Darrel15;
procedure Darrel16;
procedure Darrel58;
procedure Darrel59;
procedure Darrel60;
procedure Darrel61;
procedure Darrel62;
procedure Darrel63;
procedure Darrel64;
procedure Darrel66;
procedure Darrel67;
procedure Darrel68;
procedure Darrel69;
procedure Darrel70;
procedure Darrel71;
procedure Darrel72;
procedure Darrel73;
procedure Darrel75;
procedure Darrel76;
procedure DarrelEnd;
procedure giveradx;
procedure combat;

variable known;
variable Only_Once := 1;
variable tmp_hostile;
variable radx;
variable second;
variable ccount;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      set_self_team(TEAM_BROTHERHOOD);
      set_self_ai(AI_BROTHERHOOD_KNIGHT);
   end
end

procedure look_at_p_proc begin
   script_overrides;
   if (known) then begin
      display_msg(mstr(100));
   end
   else begin
      display_msg(mstr(101));
   end
end

procedure damage_p_proc begin
   set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
end

procedure critter_p_proc begin
   if (global_var(GVAR_ENEMY_BROTHERHOOD)) then begin
      tmp_hostile := 1;
   end
   if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
      tmp_hostile := 0;
   end
   if (tmp_hostile) then begin
      set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
      tmp_hostile := 0;
      attack(dude_obj);
   end
   if (local_var(5) == 0) then begin
      if (global_var(GVAR_QUEST_BROHOOD_1_JOIN_THEM) == 1) then begin
         call Darrel58;
      end
   end
end

procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   set_tma_data_generic(TMA_MSG_BOS);
   
   dude_look_at_self;
   if (global_var(GVAR_QUEST_BROHOOD_1_JOIN_THEM) == 5) then begin
      float_msg(self_obj, message_str(SCRIPT_CABBOT, 233), FLOAT_MSG_RED);
   end
   else if (local_var(4) == 0) then begin
      call start_dialogue;
   end
   else if (global_var(GVAR_QUEST_BROHOOD_1_JOIN_THEM) == 2) then begin
      call Darrel73;
   end
   else begin
      call start_dialogue;
   end
end

procedure destroy_p_proc begin
   set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
   inc_good_critter
end

procedure start_dialogue begin
   get_reaction
   if (global_var(GVAR_QUEST_BROHOOD_1_JOIN_THEM) == 1) then begin
      if (second) then begin
         start_dialog_at_node(Darrel71);
      end
      else begin
         second := 1;
         start_dialog_at_node(Darrel59);
      end
   end
   else begin
      if (local_var(4) == 0) then begin
         start_dialog_at_node(Darrel01);
      end
      else begin
         call Darrel16;
      end
   end
   set_local_var(4, 1);
end

procedure Darrel01 begin
   Reply(102);
   NLowOption(103, Darrel02);
   NOption(104, Darrel03, 4);
   if (global_var(GVAR_NECROP_WATER_CHIP_TAKEN) != 1) then begin
      NOption(105, Darrel04, 4);
   end
   if (global_var(GVAR_MISSING_CARAVAN) == 1) then begin
      NOption(106, Darrel75, 4);
   end
   NOption(107, DarrelEnd, 4);
end

procedure Darrel02 begin
   if (local_var(6) == 0) then begin
      Reply(108);
      NLowOption(300, Darrel02a);
   end
   else begin
      NMessage(108);
   end
end

procedure Darrel02a begin
   Reply(209);
   NLowOption(300, Darrel02b);
end

procedure Darrel02b begin
   Reply(210);
   NLowOption(300, Darrel02c);
end

procedure Darrel02c
begin
   Reply(211);
   NLowOption(300, giveradx);
end

procedure Darrel03
begin
   Reply(110);
   NOption(111, Darrel05, 4);
   NOption(112, Darrel12, 4);
   NOption(113, Darrel06, 4);
   NOption(114, DarrelEnd, 4);
end

procedure Darrel04
begin
   Reply(115);
   NOption(116, Darrel07, 4);
   NOption(201, DarrelEnd, 4);
   NOption(118, Darrel11, 4);
end

procedure Darrel05
begin
   Reply(119);
   if (has_rep_berserker) then begin
      NOption(120, DarrelEnd, 4);
   end
   NOption(121, Darrel08, 4);
   NOption(122, Darrel09, 4);
end

procedure Darrel06
begin
   Reply(123);
   NOption(202, DarrelEnd, 4);
   NOption(125, Darrel04, 4);
end

procedure Darrel07
begin
   Reply(126);
   NOption(202, DarrelEnd, 4);
   NOption(127, Darrel03, 4);
end

procedure Darrel08
begin
   Reply(128);
   NOption(129, Darrel10, 4);
   NOption(130, Darrel11, 4);
end

procedure Darrel09
begin
   Reply(109);
   NOption(129, Darrel10, 4);
   NOption(130, Darrel11, 4);
end

procedure Darrel10
begin
   Reply(131);
   NOption(132, Darrel07, 4);
   NOption(133, Darrel11, 4);
end

procedure Darrel11
begin
   NMessage(134);
end

procedure Darrel12
begin
   Reply(135);
   NOption(136, Darrel13, 4);
   NOption(137, Darrel15, 4);
   NOption(203, DarrelEnd, 4);
end

procedure Darrel13
begin
   Reply(139);
   NOption(140, Darrel13, 4);
   NOption(132, Darrel07, 4);
   NOption(204, DarrelEnd, 4);
end

procedure Darrel14
begin
   Reply(143);
   if (has_rep_berserker) then begin
      BOption(144, combat, 4);
   end
   NOption(141, Darrel07, 4);
   NOption(146, Darrel05, 4);
   NOption(145, DarrelEnd, 4);
end

procedure Darrel15
begin
   Reply(147);
   NOption(148, Darrel14, 4);
   NOption(149, Darrel07, 4);
   NOption(203, DarrelEnd, 4);
end

procedure Darrel16
begin
   float_msg(self_obj, mstr(151), FLOAT_MSG_RED);
end

procedure Darrel58
begin
   set_local_var(5, 1);
   if (dude_is_male) then begin
      float_msg(self_obj, mstr(152), FLOAT_MSG_RED);
   end
   else begin
      float_msg(self_obj, mstr(153), FLOAT_MSG_RED);
   end
end

procedure Darrel59
begin
   Reply(154);
   NOption(155, Darrel60, 4);
   NOption(156, Darrel61, 4);
   NOption(157, Darrel62, 4);
   NOption(158, DarrelEnd, 4);
   NLowOption(103, Darrel02);
end

procedure Darrel60
begin
   Reply(159);
   NOption(160, Darrel63, 4);
   NOption(161, Darrel63, 4);
   NOption(162, Darrel64, 4);
   NOption(163, Darrel61, 4);
end

procedure Darrel61
begin
   Reply(164);
   NOption(165, Darrel66, 4);
   NOption(166, Darrel67, 4);
end

procedure Darrel62
begin
   NMessage(167);
end

procedure Darrel63
begin
   Reply(168);
   NOption(203, DarrelEnd, 4);
   NOption(170, Darrel72, 4);
end

procedure Darrel64
begin
   Reply(171);
   NOption(205, DarrelEnd, 4);
   NOption(170, Darrel69, 4);
end

procedure Darrel66 begin
   Reply(174);
   NOption(175, Darrel68, 4);
   NOption(176, DarrelEnd, 4);
   NOption(177, Darrel63, 4);
   NOption(206, DarrelEnd, 4);
end

procedure Darrel67 begin
   Reply(179);
   NOption(180, Darrel64, 4);
   NOption(203, DarrelEnd, 4);
end

procedure Darrel68 begin
   Reply(181);
   NOption(182, DarrelEnd, 4);
   NOption(183, Darrel63, 4);
   NOption(184, DarrelEnd, 4);
end

procedure Darrel69 begin
   Reply(189);
   NOption(203, DarrelEnd, 4);
   NOption(190, Darrel72, 4);
end

procedure Darrel70 begin
   Reply(168);
   NOption(203, DarrelEnd, 4);
   NOption(190, Darrel72, 4);
end

procedure Darrel71 begin
   Reply(191);
   NOption(188, Darrel72, 4);
   NOption(192, DarrelEnd, 4);
   NLowOption(103, Darrel02);
end

procedure Darrel72 begin
   Reply(193);
   NOption(186, Darrel69, 4);
   NOption(187, Darrel70, 4);
   if (global_var(GVAR_MISSING_CARAVAN) == 1) then begin
      NOption(106, Darrel75, 4);
   end
   NOption(207, DarrelEnd, 4);
end

procedure Darrel73 begin
   ccount := ccount + 1;
   if (ccount < 6) then begin
      float_msg(self_obj, message_str(SCRIPT_RD1SCRB1, 200 + random(0, 2)), FLOAT_MSG_RED);
   end
   else if (ccount < 9) then begin
      float_msg(self_obj, message_str(SCRIPT_RD1SCRB1, 203 + random(0, 4)), FLOAT_MSG_RED);
   end
   else if (ccount < 12) then begin
      float_msg(self_obj, message_str(SCRIPT_RD1SCRB1, 209 + random(0, 3)), FLOAT_MSG_RED);
   end
   else begin
      display_msg(message_str(SCRIPT_RD1SCRB1, 213));
   end
end

procedure Darrel75 begin
   Reply(195);
   NOption(196, Darrel11, 4);
   NOption(197, Darrel76, 4);
   NOption(104, Darrel03, 4);
   NOption(198, DarrelEnd, 4);
end

procedure Darrel76 begin
   Reply(199);
   NOption(104, Darrel03, 4);
   if (global_var(GVAR_NECROP_WATER_CHIP_TAKEN) != 1) then begin
      NOption(105, Darrel04, 4);
   end
   NOption(208, DarrelEnd, 4);
end

procedure DarrelEnd begin
end

procedure giveradx begin
   set_local_var(6, 1);
   radx := create_object(PID_RAD_X, 0, 0);
   add_obj_to_inven(dude_obj, radx);
   Reply(212);
   NLowOption(300, DarrelEnd);
end

procedure combat begin
   tmp_hostile := 1;
end
