/*

   Brotherhood - Jonathan - unused

*/

/* Include Files */
#include "define.h"
//#include "area/necropolis.h"

#define NAME                    SCRIPT_JONATHAN
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BOS)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure timed_event_p_proc;
procedure destroy_p_proc;

procedure spar;

import variable Student_ptr;

variable initial := 0;
variable armed;
variable tmp_round;
variable v;

procedure start begin
   if not(initial) then begin
      initial := 1;
      set_self_team(TEAM_BROTHERHOOD);
      set_self_ai(AI_BROTHERHOOD_KNIGHT);
   end
end

procedure critter_p_proc begin
   if (tmp_round < 1) then begin
      tmp_round := (tmp_round + 1);
      add_timer_event(self_obj, game_ticks(5), 0);
   end
end

procedure timed_event_p_proc begin
   if (tmp_round < 7) then begin
      call spar;
   end
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure spar begin
   if (tmp_round == 1) then begin
      anim(Student_ptr, ANIM_throw_punch, 0);
      anim(self_obj, ANIM_dodge_anim, 0);
      v := 2;
   end
   else if (tmp_round == 2) then begin
      anim(self_obj, ANIM_throw_punch, 0);
      anim(Student_ptr, ANIM_hit_from_front, 0);
      v := 2;
   end
   else if (tmp_round == 3) then begin
      anim(self_obj, ANIM_throw_punch, 0);
      anim(Student_ptr, ANIM_dodge_anim, 0);
      v := 2;
   end
   else if (tmp_round == 4) then begin
      anim(self_obj, ANIM_kick_leg, 0);
      v := 1;
   end
   else if (tmp_round == 5) then begin
      anim(Student_ptr, ANIM_fall_back, 0);
      v := 2;
   end
   else if (tmp_round == 6) then begin
      anim(self_obj, ANIM_stand, 0);
      anim(Student_ptr, ANIM_back_to_standing, 0);
      v := 2;
   end
   tmp_round := tmp_round + 1;
   add_timer_event(self_obj, game_ticks(v), 0);
end
