/*

   Brotherhood of Steel - Generic guard (near Maxson?)
   This is exactly the same code as HALLGRD.ssl!

*/

/* Include Files */
#include "define.h"
//#include "maparea/brotherhood.h"

#define NAME                    SCRIPT_MAXGRD
#define TOWN_REP_VAR            (GVAR_TOWN_REP_BOS)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */
procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;

variable tmp_hostile;
variable Pick;
variable Only_Once := 1;
variable message;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      set_self_team(TEAM_BROTHERHOOD);
      set_self_ai(AI_BROTHERHOOD_PALADIN);
   end
end

procedure combat begin
   tmp_hostile := 1;
end

procedure critter_p_proc begin
   if REP_ENEMY_BOS then begin
      tmp_hostile := 1;
   end
   if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
      tmp_hostile := 0;
   end
   if (tmp_hostile) then begin
      set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure pickup_p_proc begin
   if source_is_dude then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   dude_look_at_self;
   Pick := random(1, 9);
   if (Pick == 1) then begin
      message := message_str(SCRIPT_HALLGRD, 101);
   end
   else if (Pick == 2) then begin
      message := message_str(SCRIPT_HALLGRD, 102);
   end
   else if (Pick == 3) then begin
      message := message_str(SCRIPT_HALLGRD, 103);
   end
   else if (Pick == 4) then begin
      message := message_str(SCRIPT_HALLGRD, 104);
   end
   else if (Pick == 5) then begin
      message := message_str(SCRIPT_HALLGRD, 105);
   end
   else if (Pick == 6) then begin
      message := message_str(SCRIPT_HALLGRD, 106);
   end
   else if (Pick == 7) then begin
      message := message_str(SCRIPT_HALLGRD, 107);
   end
   else if (Pick == 8) then begin
      message := message_str(SCRIPT_HALLGRD, 108);
   end
   else if (Pick == 9) then begin
      message := message_str(SCRIPT_HALLGRD, 110) + dude_name + message_str(SCRIPT_HALLGRD, 111);
   end
   float_msg(self_obj, message, FLOAT_MSG_NORMAL);
end

procedure destroy_p_proc begin
   set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
   inc_good_critter
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(message_str(SCRIPT_HALLGRD, 100));
end
