/*

	Caravaneer

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_CCVAN
//#define TOWN_REP_VAR            (GVAR_TOWN_REP_BONEYARD)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;

procedure caravan00;
procedure caravan01;
procedure caravan02;
procedure caravan03;
procedure caravan03a;
procedure caravan03b;
procedure caravan03c;
procedure caravan03d;
procedure caravan04;

variable tmp_hostile;
variable Only_Once := 1;

procedure start begin
	if Only_Once then begin
		Only_Once := 0;
		if debug_mode then begin
			//display_msg("INIT CCVAN.SSL at map number " + cur_map_index + " and elevation " + elevation(self_obj));
		end
		set_self_team(TEAM_HUB_FAR_GO_TRADERS );
		set_self_ai( AI_MERCHANT );
	end
end

procedure combat
begin
	tmp_hostile := 1;
end

procedure critter_p_proc
begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		attack(dude_obj);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		tmp_hostile := 1;
	end
end

procedure talk_p_proc
begin
	dude_look_at_self;
	get_reaction
	start_gdialog(767, self_obj, 4, -1, -1);
	gsay_start;
	call caravan00;
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_CCVAN, 100));
end

procedure caravan00
begin
	gsay_reply( SCRIPT_CCVAN, 103 );
	giq_option( 0, SCRIPT_CCVAN, 104, caravan01, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 105, caravan02, NEUTRAL_REACTION );
end

procedure caravan01
begin
	gsay_reply( SCRIPT_CCVAN, 106 );
	giq_option( 0, SCRIPT_CCVAN, 104, caravan03, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 105, caravan02, NEUTRAL_REACTION );
end

procedure caravan02
begin
	gsay_message( SCRIPT_CCVAN, 107, 50 );
end

procedure caravan03
begin
	gsay_reply( SCRIPT_CCVAN, 109 );
	giq_option( 0, SCRIPT_CCVAN, 112, caravan03a, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 113, caravan03b, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 114, caravan03c, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 115, caravan03d, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_CCVAN, 116, caravan04, NEUTRAL_REACTION );
end

procedure caravan03a
begin
	variable LVar0 := 0;
	gsay_message( SCRIPT_CCVAN, 117, 50 );
	set_global_var( GVAR_CRIMSON_CARAVANS_STATUS, 1 );
	LVar0 := random(1, 4);
	dude_caps_adjust( 600 );
	if (LVar0 < 3) then begin
		LVar0 := random(1, 4);
		if (LVar0 == 1) then begin
			load_map(MAP_DESCRVN1, 1);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
		else begin
			load_map(MAP_DESCRVN1, 2);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
	end
	else begin
		load_map(MAP_DESCRVN1, 3);
		set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
	end
end

procedure caravan03b
begin
	variable LVar0 := 0;
	gsay_message( SCRIPT_CCVAN, 117, 50 );
	set_global_var( GVAR_CRIMSON_CARAVANS_STATUS, 1 );
	LVar0 := random(1, 4);
	dude_caps_adjust( 600 );
	if (LVar0 < 3) then begin
		LVar0 := random(1, 4);
		if (LVar0 == 1) then begin
			load_map(MAP_MNTCRVN1, 1);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
		else begin
			load_map(MAP_MNTCRVN1, 2);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
	end
	else begin
		load_map(MAP_MNTCRVN1, 3);
		set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
	end
end

procedure caravan03c
begin
	variable LVar0 := 0;
	gsay_message( SCRIPT_CCVAN, 117, 50 );
	set_global_var( GVAR_CRIMSON_CARAVANS_STATUS, 1 );
	LVar0 := random(1, 4);
	dude_caps_adjust( 600 );
	if (LVar0 < 3) then begin
		LVar0 := random(1, 4);
		if (LVar0 == 1) then begin
			load_map(MAP_MNTCRVN2, 1);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
		else begin
			load_map(MAP_MNTCRVN2, 2);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
	end
	else begin
		load_map(MAP_MNTCRVN2, 3);
		set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
	end
end

procedure caravan03d
begin
	variable LVar0 := 0;
	gsay_message( SCRIPT_CCVAN, 117, 50 );
	set_global_var( GVAR_CRIMSON_CARAVANS_STATUS, 1 );
	LVar0 := random(1, 4);
	dude_caps_adjust( 600 );
	if (LVar0 < 3) then begin
		LVar0 := random(1, 4);
		if (LVar0 == 1) then begin
			load_map(MAP_DESCRVN2, 1);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
		else begin
			load_map(MAP_DESCRVN2, 2);
			set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
		end
	end
	else begin
		load_map(MAP_DESCRVN2, 3);
		set_global_var( GVAR_VAULT13_WATER_DAYS_LEFT, global_var( GVAR_VAULT13_WATER_DAYS_LEFT ) - 1 );
	end
end

procedure caravan04
begin
	gsay_message( SCRIPT_CCVAN, 108, 50 );
end
