#include "..\headers\define.h"

#define NAME                    SCRIPT_NDEBRIS

#include "..\headers\command.h"

procedure start;

procedure start begin
end

procedure spatial_p_proc begin
   if source_obj == dude_obj then begin
      if (map_var(2) == 0) then begin
         set_map_var(2, 1);
         set_map_var(4, map_var(4) + 1);
         if (map_var(4) > 3) then begin
            display_msg(mstr(104));
         end
         else begin
            display_msg(mstr(102));
         end
      end
   end
end
