/*

   Necropolis - Vault, when entering the storage room on lvl 3.

*/

#include "define.h"

#define NAME                    SCRIPT_STOREROM

#include "command.h"

procedure start;

procedure start begin
end

procedure spatial_p_proc begin
   if source_obj == dude_obj then begin
      if (local_var(0) != 1) then begin
         display_msg(mstr(100));
         set_local_var(0, 1);
      end
   end
end
