/*

   Runs before any other global script

*/

#include "debug.h"
#include "voodoo.h"
#include "voodoo_lib.h"

procedure start
begin
   variable init := VOODOO_Init(); // must be called before any other voodoo magick

   if(init) then // run only once per session
   begin
      VOODOO_CalcHook;
   end

   // Reset to check if Classic WM mod is enabled
   set_global_var(GVAR_ENABLE_CLASSIC_WM, 0);
end
