#include "debug.h"
#include "itempid.h"
#include "sfall/sfall.h"
#include "sfall/define_extra.h"

procedure APCostTweak(variable pid, variable idx, variable tweak)
begin
    variable ap, idxReal := PROTO_WP_APCOST_1 + idx - 1;

    if((idx < 1 or idx > 2) or tweak == 0) then
        return;

    ap := get_proto_data(pid, idxReal);
    set_proto_data(pid, idxReal, ap + tweak);

    debug("[PID " + pid + "] APCOST" + idx + ": " + ap + " -> " + (ap + tweak));
end

procedure start
begin
    if(game_loaded) then
    begin
        call APCostTweak(PID_PLASMA_RIFLE, 1, 1);
        call APCostTweak(PID_TURBO_PLASMA_RIFLE, 1, 1);
        intface_redraw;
    end
end
