/*

   Fallout et Tu - Settings

   Reads data from the fo1_settings.ini file and switches GVAR's accordingly.

*/

#include "..\headers\define.h"

procedure start;

procedure settings;

#define ini_path                            "config\\fo1_settings.ini"
//#define ini_settings(gvar, option_name)   set_global_var(gvar, get_ini_setting(ini_path + "|" + section + "|" + option_name))
#define gvar_settings(gvar)                 set_global_var(gvar, get_ini_setting(ini_path + "|" + section + "|" + #gvar))

procedure start begin
   if (game_loaded) then begin
      set_global_script_type(0);
      call settings;
   end
end

procedure settings begin
variable section;

   // Show ddraw warning
   //if (get_ini_setting("ddraw.ini|Debugging|Fallout1Behavior") != 1) then
   //   float_msg(dude_obj, "Warning! <Fallout1Behavior> has been disabled in the ddraw.ini! Some scripts will break now!", FLOAT_MSG_WARNING);

   //===================================================
   //    Debug
   //===================================================
   section := "DEBUG";
   gvar_settings(GVAR_CHEAT_DEBUG_MENU_ENABLED);
   gvar_settings(GVAR_DEBUG_MODE_MESSAGES_ON);

   //===================================================
   //    Fo1in2
   //===================================================
   section := "Fo1in2";
   gvar_settings(GVAR_ENABLE_MOTORCYCLE);
   gvar_settings(GVAR_DISABLE_FLUFF_ENCOUNTER);
   gvar_settings(GVAR_UNLIMITED_PARTY_MEMBERS);
   gvar_settings(GVAR_MR_HANDYC_HIRELING);
   gvar_settings(GVAR_AUTO_DOORS_CLOSING);
   gvar_settings(GVAR_ARMOR_DESTROY_MOD);
   gvar_settings(GVAR_ENABLE_FO2_MERCHANT_RESTOCK);
   gvar_settings(GVAR_ENABLE_UNLIMITED_HPA);

   // Satellite locations:
   gvar_settings(GVAR_ENABLE_SATELLITE_LOCATIONS);
   if fo1in2_satellite_loc_disabled then begin
      invisible_on_map(AREA_SHADY_CAVES)
      invisible_on_map(AREA_HUB_FARM)
      invisible_on_map(AREA_HUB_LAIR)
   end

   // Invasion timer:
   gvar_settings(GVAR_FOLLOWERS_INVADED_DATE);
   gvar_settings(GVAR_NECROPOLIS_INVADED_DATE);
   gvar_settings(GVAR_THE_HUB_INVADED_DATE);
   gvar_settings(GVAR_BROTHERHOOD_INVADED_DATE);
   gvar_settings(GVAR_JUNKTOWN_INVADED_DATE);
   gvar_settings(GVAR_SHADY_SANDS_INVADED_DATE);
   gvar_settings(GVAR_VAULT_13_INVADED_DATE);

   //===================================================
   //    FIXT
   //===================================================
   section := "FIXT";
   gvar_settings(GVAR_FIXT_BUGFIXES_ONLY);

   gvar_settings(GVAR_AGATHA_IS_ENABLED);
   gvar_settings(GVAR_BOS_LORRI_CHA_ENABLED);
   gvar_settings(GVAR_ENABLE_HOOKERS);
   gvar_settings(GVAR_STAPLE_RESTOCK_WEEKS);
   gvar_settings(GVAR_STAPLE_INIT_NUM_BOOKS);
   gvar_settings(GVAR_STAPLE_BOOKS_RESPAWN_MIN);
   gvar_settings(GVAR_STAPLE_BOOKS_RESPAWN_MAX);
   gvar_settings(GVAR_STAPLE_DIFFICULTY_BASED);
   gvar_settings(GVAR_BITS_BOB_GOES_TO_JAIL);
   gvar_settings(GVAR_FORTUNE_FINDER_HOW_MUCH);
   gvar_settings(GVAR_HUNTER_RESPAWNS);
   gvar_settings(GVAR_EXPLOSIVES_RUIN_LOCKERS);
   gvar_settings(GVAR_MBASE_RED_ONLY_PLAYER);
   gvar_settings(GVAR_MBASE_RED_ONLY_PARTY);
   gvar_settings(GVAR_WILD_WASTELAND);
   gvar_settings(GVAR_IRONMAN_MODE);
   gvar_settings(GVAR_BOS_LORRI_SEX_ENABLED);
   gvar_settings(GVAR_BOS_LORRI_NUM_OPS_ALLOWED);

end
