{100}{}{You have broken out of the jail. You're now definitely a fugitive in Junktown!}
{101}{}{The door looks solid, and has a stout lock. Still, locks can be picked, and doors can be destroyed.}
{102}{}{The door is locked.}
{103}{}{You unlock the door.}
{104}{}{You lock the door.}
{105}{}{You fail to unlock the door.}
{106}{}{You fail to lock the door.}
{107}{}{You earn 250 experience for busting out of jail!}
