{100}{}{You see: Michael.}
{101}{}{Well, I guess that's what the problem was. You should see the Doctor, she's on level two.}
{102}{}{You're fine as far as I can tell.}
{103}{}{The supply room is off limits my son. Only myself and two others have access to that room. If you need 
something, you need to talk to me about it.}
{104}{}{The supply room is off limits ma'am. Only myself and two others have access to that room. If you need 
something, you need to talk to me about it.}
{105}{}{Didn't you hear me? I said that the rooms are off limits.}
{106}{}{Hello, Brother. How can I help you?}
{107}{}{Please excuse me for asking, but what do you do for our Brotherhood?}
{108}{}{What do you do around here?}
{109}{}{I've been injured. Can you heal me?}
{110}{}{Urak Chufar!}
{111}{}{I'm sorry, but I don't understand what you want. If you need supplies, you need to have authorization.}
{112}{}{Taga ma.}
{113}{}{Caroo!}
{114}{}{I still don't understand you. Maybe you need to see the Doctor; she's on level two.}
{115}{}{You should see the Doctor. She's on level two.}
{116}{}{Oh, nothing quite as glorious as our Paladins. I just run the supply room, checking equipment and other supplies out to people.}
{117}{}{I was sent here by... Bob. He wanted me to get him... that new high tech weapon-thingy. He said to bring it right away.}
{118}{}{I'd like to check out something. How do I do that?}
{119}{}{Oh, that's nice. Bye.}
{120}{}{Bob? Bob who? What are you talking about? What new high tech weapon-thingy? I need 
more specifics than that, and you must have the who ever it is get me the proper authorization. 
I cannot give anything without authorization.}
{121}{}{Oh, you mean the laser pistol? Okay, hold on a second please. I don't have any 
authorization from a Bob to give anyone a laser. Oh, wait a second. I get it. Those girls downstairs 
think they are really funny don't they. I wish they would stop bothering me.}
{122}{}{Well, you know. They told me not to tell you, but it's just because they like you so much. I think one of them 
has a crush on you.}
{123}{}{Sorry, I had no idea what they were up to. They told me to come up here and tell you this, and that you would get a big kick out of it.}
{124}{}{I'm sorry. It was a bad joke. I was just kidding around with you.}
{125}{}{You're doing it again! Stop tormenting me! They are so cruel! I can't believe you would stoop to their 
level. Us guys are supposed to stick together.}
{126}{}{You're lying! You're in cahoots with them. How could you be so cruel?}
{127}{}{Really? You wouldn't be pulling my leg again would you? No, you seem like a good lad. They 
probably forced you to do this. You know, I've caught Lara looking at me during Training. I bet it was her, right?}
{128}{}{Yep, you got it. She's the one. Don't tell her I told you. She would kill me.}
{129}{}{No, I'm sorry. I was just messing with you. No one sent me here.}
{130}{}{You're doing it again! Stop tormenting me! You women are so cruel!}
{131}{}{Really? You wouldn't be pulling my leg again would you? No, you seem like a good lass. They 
probably forced you to do this. You know, I've caught Lara looking at me during Training. I bet it was her, right?}
{132}{}{Yep, you got it. She's the one. Don't tell her I told you. She would kill me.}
{133}{}{No, I'm sorry. I was just messing with you. No one sent me here.}
{134}{}{Well, I don't know what to say. I've always sorta had a crush on her, but I didn't want to act, 
because I didn't know if she felt the same way or not. Next time I see her, I think I'll ask her out. 
Maybe I'll try and get on the same patrol as her and surprise her with a nice romantic dinner. Thanks 
a lot. You have really made my day. Here, take these. You should be able to find some use for them. They're electromagnetic
pulse grenades. Very useful against robots. Hopefully, you'll never have to use them. Bye.}
{135}{}{That's not very nice of you. Why would you say something like that if it wasn't true? Some people!}
{136}{}{Oh. You've got a strange sense of humor. Well, don't bother me unless you have something to check out.}
{137}{}{Oh, those girls are always giving me a hard time. I don't know why they keep doing it. That Lara sure is 
cute though. I've liked her for quite some time. I knew her when she was younger. She was such a darling. 
Now she's older, and she treats me so terribly. I've never done anything to deserve this.}
{138}{}{Well, maybe she likes you. Did you ever think about that? She just might not know how to approach you. You should ask her. If you really do like her, what do you have to lose?}
{139}{}{Maybe she likes you.}
{140}{}{Uh, yeah. Okay. Bye.}
{141}{}{You know, you're right. What have I got to lose? The next time I see her, I think I will ask her out. Maybe I'll try and get on the same patrol as here and surprise her with a nice romantic dinner. Thanks a lot. You have really made my day. Here, take these. You should be able to find a use for them. They are dexterity boosters. Be careful with them; they can be highly addictive. Bye.}
{142}{}{No, that's not likely. Women sure do confuse me sometimes. I can read and understand any new 
schematic they put in front of me, but when it comes to women I'm at a total loss. Thanks anyway.}
{143}{}{No, that's not likely. You women sure do confuse me sometimes. I can read and understand any new 
schematic they put in front of me, but when it comes to women I'm at a total loss. Thanks anyway.}
{144}{}{You need to have the proper authorization. Only specific people can give authorization to check out items from the supply room.}
{145}{}{Oh. Okay, thanks. Who do I need to talk to then?}
{146}{}{I have been given authorization to check something out. Could you check the terminal to see if it went through yet?}
{147}{}{Who can give me authorization?}
{148}{}{Well, there are quite a few people actually; but Talus is the person you should probably talk to. You 
might also want to check with Mathia, she might be able to help you, too.}
{149}{}{Where can I find Mathia?}
{150}{}{Where's Talus?}
{151}{}{Okay, thanks.}
{152}{}{Mathia is Maxon's assistant. She is technically the High Elder's assistant, but she works with all the other Elders. She is normally in the Elders' Rooms. That's located on the fourth floor.}
{153}{}{Okay. Where's Talus?}
{154}{}{Okay. Thanks. Bye.}
{155}{}{Why, he's in the training room to my left.}
{156}{}{Great. Now, could you also direct me to where I can find Mathia?}
{157}{}{How about Mathia?}
{158}{}{Thanks. Talk to you later.}
{159}{}{Yes, during the day she is normally in the Elders' Rooms. That's located on the fourth floor.}
{160}{}{Thank you. You have been very helpful.}
{161}{}{Well, here's the drug you had authorization for. Be careful with that. They can become addictive if you use 
them too often. Detoxing and withdrawals are not much fun, but I guess they're pretty much the same thing. 
Use at your own risk. Is there anything else I can do for you?}
{162}{}{No, that's it. Thanks.}
{163}{}{Yes, I have something else to pick up.}
{164}{}{Well, here's the drug you wanted. That's some handy stuff. I'm sure it will be useful. Did you need 
something else?}
{165}{}{No, that's it. Thanks.}
{166}{}{Yes, I have something else to pick up.}
{167}{}{Okay, I've got some of that. You never can have enough ammo right? Well, there you are. Anything else?}
{168}{}{No, that's it. Thanks.}
{169}{}{Yes, I have something else to pick up.}
{170}{}{Oh, these can really be dangerous. Just be sure you are far enough away when they go off. There 
you are. Anything else?}
{171}{}{No, that's it. Thanks.}
{172}{}{Yes, I have something else to pick up.}
{173}{}{Ah, nothing like a good weapon by your side. Anything else?}
{174}{}{No, that's it. Thanks.}
{175}{}{Yes, I have something else to pick up.}
{176}{}{A good defense is the best offense. Or was it the other way around? Well, it doesn't matter. Here's 
your armor. Be sure to take care of it. I can't give out more than one set. Was there another item you needed?}
{177}{}{No, that's it. Thanks.}
{178}{}{Yes, I have something else to pick up.}
{179}{}{Well, this can be useful in the right hands. Here you go. Anything else?}
{180}{}{No, that's it. Thanks.}
{181}{}{Yes, I have something else to pick up.}
{182}{}{Oh, something else? Sorry, I must have missed it. Let me see.}
{183}{}{Hello, again. How are you doing today? How can I help you?}
{184}{}{Is there anything I can help you with? You seem to be awfully busy.}
{185}{}{I have something to pick up.}
{186}{}{Nothing, bye.}
{187}{}{Could you ever possibly help me? I don't think so. Get out of my way.}
{188}{}{Okay, let me see here.}
{189}{}{Ah, yes. You do have authorization to check something out.}
{190}{}{Well actually, Sophia has been in need of some EMP grenades but I haven't had a chance to run them down to her yet. Do you think you could run them down for me?}
{191}{}{Sure. Hand them over.}
{192}{}{Sorry, I don't have time. Hope you can find someone else.}
{193}{}{What do I look like, your lackey?}
{194}{}{Okay, there you go. Sophia is one of the two Assistant Head Scribes for Vree. She is normally in the Library on the third floor.}
{195}{}{Why haven't you delivered the items I gave you? Sophia is expecting them.}
{196}{}{I'm sorry. Could you tell me where she is again?}
{197}{}{I lost them. Can I have some more?}
{198}{}{I'm sorry, I lost track of time.}
{199}{}{Ha! You thought I would actually deliver it? You're dumber than you look!}
{200}{}{She is normally in the Library on the third floor.}
{201}{}{Guards! We have a thief! Show him what we do to those that betray the Brotherhood.}
{202}{}{Guards! We have a thief! Show her what we do to those that betray the Brotherhood.}
{203}{}{Sorry, I'm not talking to the likes of you.}
{204}{}{Likely story. I knew I shouldn't have trusted someone like you.}
{205}{}{I can't believe you'd show your face around here again. I hope the grenades were useful, you're never getting anything from me again. I don't care who supposedly gives you authorization.}
{206}{}{Why hello again. Sophia says you delivered the grenades. That was very kind of you. She is working on a better version and needed to see if the circuitry was compatible.}
{207}{}{What do you want.}
{208}{}{Just give me what I have to pick up and I'll be out of your way.}
{209}{}{Nothing.}
{210}{}{Well fine. Let me just check and see if I have an order.}
{211}{}{Okay, you need some ammunition do you. Well what kind did you need?}
{212}{}{I don't know.}
{213}{}{10mm Jacketed Hollow Point.}
{214}{}{10mm Armor Piercing.}
{215}{}{44 Magnum Jacketed Hollow Point.}
{216}{}{44 Magnum Full Metal Jacket.}
{217}{}{14mm Armor Piercing}
{218}{}{.223 Full Metal Jacket.}
{219}{}{5mm Jacketed Hollow Point.}
{220}{}{5mm Armor Piercing.}
{221}{}{Shotgun shells.}
{222}{}{Well you need to find out what type of ammunition you need before I can give it to you. Just examine the weapon that you requested ammunition for. When you figure it out, just give me a holler.}
{223}{}{Ah, a rocket launcher... nothing like a good weapon by your side. So, will that be it?}
{224}{}{No, that's it. Thanks.}
{225}{}{Yes, I have something else to pick up.}
{226}{}{Ah yes, here is the fine pistol you're looking for. So, will that be it?}
{227}{}{No, that's it. Thanks.}
{228}{}{Yes, I have something else to pick up.}
{229}{}{A good defense is the best offense. Or was it the other way around? Well, it doesn't matter. Here's 
your armor. Be sure to take care of it. I can't give out more than one set. Was there another item you needed?}
{230}{}{No, that's it. Thanks.}
{231}{}{Yes, I have something else to pick up.}
{232}{}{Hmmm... Power Armor. Be sure to take care of it. I can't give out more than one set. Was there another item you needed?}
{233}{}{No, that's it. Thanks.}
{234}{}{Yes, I have something else to pick up.}
{235}{}{Well, this can be useful in the right hands. Here you go. Anything else?}
{236}{}{No, that's it. Thanks.}
{237}{}{Yes, I have something else to pick up.}
{240}{}{I'm looking for a Systolic Motivator.}
{241}{}{Do you have the proper authorization?}
{242}{}{Yes. I was sent up here to get a Systolic Motivator.}
{243}{}{No I don't, but it is imperative that I get that part.}
{244}{}{Kyle sent me up to get the part.}
{245}{}{No. How do I get authorization?}
{246}{}{Let me look here. [He checks his terminal] Well I don't see a request for a Systolic Motivator. You'll need to get the proper authorization.}
{247}{}{Now look! I don't want any trouble. Just give me the damn part.}
{248}{}{Come on? Please. I really need this part.}
{249}{}{Okay. Sorry to bother you.}
{250}{}{You don't? Ordinance was supposed to send one down yesterday. Look, can you help me out? If I don't get this part it's gonna be my ass. I'm sure the form will be here later today.}
{251}{}{Okay. Here you go. Just don't tell anyone that I gave this to you. Rhombus would have my head if he knew I had given the parts out without proper authorization.}
{252}{}{Thank you. Bye.}
{253}{}{I would give it to you if I could. But I can't. Not without proper authorization.}
{254}{}{You know Michael, you're probably one of the brightest guys I've talked to here. But I don't understand why you're giving me such a hard time. I really need that part.}
{255}{}{Oh... Well. I guess I understand. I don't know what I'm going to do, though.}
{256}{}{Just give it to me.}
{257}{}{If you don't have authorization you can't get replacement parts.} 
{258}{}{Come on? Please. I really need this part.}
{259}{}{Okay. Sorry to bother you. Bye.}
{260}{}{Kyle? Is this about that old junked Power Armor?}
{261}{}{Yes.}
{262}{}{No.}
{263}{}{You can tell him that when he gets that unit back to its original glory, then and only then will he get the authorization he needs. Goodbye.}
{264}{}{You don't. First Kyle needs to see the unit in need of repair. If he feels the repair is warranted he then puts in a parts request. Rhombus reviews the requests and determines which ones are viable. Go talk to Kyle. Bye.}
{265}{}{Goodbye.}
{266}{}{Oh... yeah, well Kyle sent me. Could you check your terminal one more time?}
{267}{}{But Rhombus sent me.}
{268}{}{You're not getting the part and that's final. I told you what you need to do and I'm not going to repeat myself.}
{300}{}{It seems that Sophia really likes you. She asked me to give you these almost-expired batteries. We need to free some space in the storage unit for her research anyway. }

{500}{}{[More]}
{501}{}{[Back]}
