#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\headers\modreact.h"

procedure start;    variable SrcObj := 0;    variable SrcIsParty := 0;
procedure look_at_p_proc;//    script_action == 21
procedure description_p_proc;//    script_action == 3
procedure talk_p_proc;//    script_action == 11
procedure critter_p_proc;//    script_action == 12
procedure damage_p_proc;//    script_action == 14
procedure destroy_p_proc;//    script_action == 18
procedure pickup_p_proc;//    script_action == 4
procedure DialogWeapon;
procedure DialogFirstTime;
procedure DialogSubsequent;
procedure DialogExit;
procedure DialogMain1;
procedure DialogMain2;
procedure DialogMain3;
procedure DialogMain4;
procedure DialogMain5;
procedure DialogMain6;

import variable RegGuard1;
import variable RegGuard2;

variable Only_Once := 1;
variable tmp_hostile;

procedure Start
begin
	

	if Only_Once then begin
		/* has how many? */    if (self_item_count( PID_BOTTLE_CAPS ) == 0) then begin
			item_caps_adjust(self_obj, random(2, 20));
		end
		set_self_team(TEAM_LA_REGULATORS );
		set_self_ai( AI_REGULATORS );
		if (local_var(6) == 0) then begin
			set_map_var(1, map_var(1) + 1);
			set_local_var(6, 1);
		end
		if (global_var( GVAR_BLADES_STATUS ) == 9103) then begin
			variable LVar0;
			LVar0 := global_var(WATER_CHIP_11);
			if (LVar0 == 0) then begin
				RegGuard1 := self_obj;
			end
			else begin
				if (LVar0 == 1) then begin
					RegGuard2 := self_obj;
				end
			end
			LVar0 := LVar0 + 1;
			set_global_var(WATER_CHIP_11, LVar0);
		end
		else begin
			RegGuard1 := 0;
			RegGuard2 := 0;
		end
		Only_Once := 0;
	end
end



procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_REGULATR, 100));
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_REGULATR, 100));
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	if ((global_var(ENEMY_ADYTUM) == 1) or (global_var( GVAR_DUDE_ENEMY_REGULATORS ) == 1) or (global_var( GVAR_BLADES_STATUS ) == 9103)) then begin
		float_msg(self_obj, message_str(SCRIPT_ENEMY, random(100, 105)), 2);
	end
	else begin
		get_reaction
		start_gdialog(252, self_obj, -1, -1, -1);
		gsay_start;
		if (dude_is_armed) then begin
			call DialogWeapon;
		end
		else begin
			if (local_var(4) == 0) then begin
				set_local_var(4, 1);
				call DialogFirstTime;
			end
			else begin
				call DialogSubsequent;
			end
		end
		gsay_end;
		end_dialogue;
	end
end

procedure critter_p_proc
begin
	if (obj_can_see_obj(self_obj, dude_obj)) then begin
		if ((global_var( GVAR_BLADES_STATUS ) == 9103) and (local_var(5) == 0)) then begin
			attack(dude_obj);
			set_global_var( GVAR_DUDE_ENEMY_REGULATORS, 1 );//  ENEMY_REGULATOR == 1
		end
		else begin
			if ((global_var(ENEMY_ADYTUM) == 1) or (global_var( GVAR_DUDE_ENEMY_REGULATORS ) == 1)) then begin
				attack(dude_obj);
			end
			else begin
				if (global_var( GVAR_BLADES_STATUS ) != 9103) then begin
					if (map_var(0) == 0) then begin
						set_map_var(0, 1);
						dialogue_system_enter;
					end
				end
			end
		end
	end
end

procedure damage_p_proc
begin
	if (source_obj == dude_obj) then begin
		set_global_var( GVAR_DUDE_ENEMY_REGULATORS, 1 );//  ENEMY_REGULATOR == 1
	end
end

procedure destroy_p_proc
begin

	set_map_var(1, (map_var(1) - 1));
	if (source_obj == dude_obj) then begin
		if (((global_var( GVAR_BAD_MONSTER ) + global_var( GVAR_GOOD_MONSTER )) >= 25) and ((global_var( GVAR_GOOD_MONSTER ) > (2 * global_var( GVAR_BAD_MONSTER ))) or (global_var( GVAR_BERSERKER_REPUTATION ) == 1))) then begin
			set_global_var(BERSERKER_REPUTATION, 1);
			set_global_var( GVAR_CHAMPION_REPUTATION, 0 );
		end
		if (((global_var( GVAR_BAD_MONSTER ) + global_var( GVAR_GOOD_MONSTER )) >= 25) and ((global_var( GVAR_BAD_MONSTER ) > (3 * global_var( GVAR_GOOD_MONSTER ))) or (global_var( GVAR_CHAMPION_REPUTATION ) == 1))) then begin
			set_global_var( GVAR_CHAMPION_REPUTATION, 1 );
			set_global_var(BERSERKER_REPUTATION, 0);
		end
		set_global_var( GVAR_BAD_MONSTER, global_var( GVAR_BAD_MONSTER ) + 1 );// THIS MONSTER WAS A BAD GUY. INCREASE BadGuysKilled COUNTER
		if ((global_var( GVAR_BAD_MONSTER ) % 6) == 0) then begin
			set_global_var( GVAR_PLAYER_REPUTATION, global_var( GVAR_PLAYER_REPUTATION ) + 1 );
		end
		set_global_var( GVAR_DUDE_ENEMY_REGULATORS, 1 );//  ENEMY_REGULATOR == 1
	end
	if (map_var(1) == 0) then begin
		terminate_combat;
	end
end

procedure pickup_p_proc
begin
	set_global_var( GVAR_DUDE_ENEMY_REGULATORS, 1 );//  ENEMY_REGULATOR == 1
end

procedure DialogWeapon
begin
	gsay_message(252, 131, 50);
end

procedure DialogFirstTime
begin
	gsay_reply(252, 103);
	giq_option( -3, SCRIPT_REGULATR, 106, DialogMain1, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_REGULATR, 104, DialogMain1, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_REGULATR, 105, DialogMain2, NEUTRAL_REACTION );
end

procedure DialogSubsequent
begin
	gsay_reply(252, 111);
	giq_option( -3, SCRIPT_REGULATR, 106, DialogMain1, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_REGULATR, 104, DialogMain1, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_REGULATR, 105, DialogMain2, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_REGULATR, 114, DialogExit, NEUTRAL_REACTION );
end

procedure DialogExit
begin
end

procedure DialogMain1
begin
	if (global_var(QUEST_BONEYARD_7_GANG_WAR) == 0) then begin
		gsay_message(252, 107, 50);
	end
	else begin
		gsay_message(252, 110, 50);
	end
end

procedure DialogMain2
begin
	if (local_var(1) < 2) then begin
		gsay_message(252, 116, 50);
	end
	else begin
		gsay_reply(252, 117);
		giq_option( -3, SCRIPT_REGULATR, 106, DialogExit, NEUTRAL_REACTION );
		giq_option( 4, SCRIPT_REGULATR, 118, DialogMain3, NEUTRAL_REACTION );
		giq_option( 4, SCRIPT_REGULATR, 119, DialogMain4, NEUTRAL_REACTION );
		giq_option( 5, SCRIPT_REGULATR, 120, DialogMain5, NEUTRAL_REACTION );
		giq_option( 6, SCRIPT_REGULATR, 121, DialogMain6, NEUTRAL_REACTION );
		giq_option( 4, SCRIPT_REGULATR, 114, DialogExit, NEUTRAL_REACTION );
	end
end

procedure DialogMain3
begin
	gsay_message(252, 123, 50);
	call DialogMain2;
end

procedure DialogMain4
begin
	gsay_message(252, 124, 50);
	call DialogMain2;
end

procedure DialogMain5
begin
	if (global_var(QUEST_BONEYARD_7_GANG_WAR) == 0) then begin
		gsay_message(252, 125, 50);
	end
	else begin
		if (global_var(QUEST_BONEYARD_7_GANG_WAR) == 1) then begin
			gsay_message(252, 126, 50);
		end
		else begin
			gsay_message(252, 127, 50);
		end
	end
end

procedure DialogMain6
begin
	gsay_message(252, 128, 50);
	gsay_message(252, 129, 50);
	call DialogMain2;
end







