/*

	Boneyard - Thug?

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\MAPLAADYTUM.h"

#define NAME                    SCRIPT_THUG
//#define TOWN_REP_VAR            (GVAR_TOWN_REP_BONEYARD)

#include "..\headers\command.h"
#include "..\headers\ModReact.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;

variable initial :=  0;
variable tmp_hostile;
variable my_script_mode;

procedure start begin
	if not(initial) then begin
		initial :=  1;
		set_self_team( TEAM_29 );
		set_self_ai( AI_BOUNCER );
		if (cur_map_index != MAP_LAFOLLWR) then begin
			//tmp_hostile := 1;
			//attack(dude_obj);
			my_script_mode := 1;
		end
		else begin
			if (global_var( GVAR_HUNTER_STATUS ) == 3) then begin
				move_to(self_obj, 7000, 0);
				if not(is_loading_game) then begin    set_self_invisible;    end//  MAKE INVISIBLE
			end
		end
	end
	if (not(my_script_mode)) then begin
		if (script_action == 18) then begin//destroy_p_proc - Object or Critter has been killed or otherwise eradicated. Fall down go boom.
			call destroy_p_proc;
		end
		else begin
			if (script_action == 12) then begin//<-- critter_p_proc - (can also be "Critter_Action") - do they see you, should they wander, should they attack you, etc..
				call critter_p_proc;
			end
			else begin
				if (script_action == 4) then begin//<---caught stealing! (pickup_p_proc)
					call pickup_p_proc;
				end
				else begin
					if (script_action == 11) then begin//<--- talk_p_proc (Face icon), can also call "do_dialogue" or "do_dialog"
						call talk_p_proc;
					end
				end
			end
		end
	end
	else begin
		if (script_action == 18) then begin//destroy_p_proc - Object or Critter has been killed or otherwise eradicated. Fall down go boom.
			call destroy_p_proc;
		end
	end
end

procedure critter_p_proc
begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		attack(dude_obj);
	end
end

procedure pickup_p_proc
begin
	tmp_hostile := 1;
end

procedure talk_p_proc
begin
	dude_look_at_critter;
	float_msg(self_obj, message_str(SCRIPT_THUG, 100), 0);
end

procedure destroy_p_proc
begin
	variable removal_ptr := 0;
	if self_item( PID_METAL_ARMOR ) then begin// metal armor
		if random(0, 10) then begin
			removal_ptr := self_item( PID_METAL_ARMOR );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_RIPPER ) then begin// ripper
		if random(0, 10) then begin
			removal_ptr := self_item( PID_RIPPER );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_SUPER_SLEDGE ) then begin// supersledge
		if random(0, 10) then begin
			removal_ptr := self_item( PID_SUPER_SLEDGE );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_POWER_FIST ) then begin// powerfist
		if random(0, 10) then begin
			removal_ptr := self_item( PID_POWER_FIST );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_SNIPER_RIFLE ) then begin// sniper rifle
		if random(0, 10) then begin
			removal_ptr := self_item( PID_SNIPER_RIFLE );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_14MM_PISTOL ) then begin// 14mm pistol
		if random(0, 10) then begin
			removal_ptr := self_item( PID_14MM_PISTOL );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_223_PISTOL ) then begin// .223 pistol
		if random(0, 10) then begin
			removal_ptr := self_item( PID_223_PISTOL );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_PLASMA_PISTOL ) then begin// plasma pistol
		if random(0, 10) then begin
			removal_ptr := self_item( PID_PLASMA_PISTOL );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end
	if self_item( PID_COMBAT_SHOTGUN ) then begin// combat shotgun
		if random(0, 10) then begin
			removal_ptr := self_item( PID_COMBAT_SHOTGUN );
			rm_obj_from_inven(self_obj, removal_ptr);
			destroy_object(removal_ptr);
		end
	end

end




