/*

	Cathedral - Chanter

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_CHANTER
#define TOWN_REP_VAR            (GVAR_TOWN_REP_CATHEDRAL)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure Chant01;
procedure Chant02;
procedure Chant03;
procedure Chant04;
procedure Chant05;
procedure Chant06;
procedure Chant07;
procedure ChantEnd;
procedure Combat;

variable tmp_hostile;
variable Only_Once := 1;

procedure destroy_p_proc;

procedure start begin
	if Only_Once then begin
		Only_Once := 0;
		set_self_team(TEAM_CATHEDRAL );
		set_self_ai( AI_CHILDREN_TRUE );
	end
end

procedure look_at_p_proc begin
	script_overrides;
	display_msg(message_str(NAME, 100));
end

procedure description_p_proc begin
	script_overrides;
	display_msg(message_str(NAME, 100));
end

procedure critter_p_proc begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		attack(dude_obj);
	end
end

procedure pickup_p_proc begin
   tmp_hostile := 1;
end

procedure talk_p_proc begin
	script_overrides;
	if (global_var( GVAR_CATHEDRAL_ENEMY ) == 1) then begin
		float_msg( self_obj, message_str(NAME, 101), FLOAT_MSG_NORMAL );
	end
	else begin
		start_gdialog(398, self_obj, 4, -1, -1);
		gsay_start;
		call Chant01;
		gsay_end;
		end_dialogue;
	end
end

procedure Chant01 begin
	gsay_reply( NAME, 102 );
	giq_option( 7, NAME, 103, Chant02, NEUTRAL_REACTION );
	giq_option( 4, NAME, 104, Chant03, NEUTRAL_REACTION );
	giq_option( 4, NAME, 105, Chant04, NEUTRAL_REACTION );
	if (global_var( GVAR_ALCOHOL_ADDICT ) == 1) then begin
		giq_option( 4, NAME, 106, Chant05, NEUTRAL_REACTION );
	end
	if (has_rep_berserker) then begin
		giq_option( 4, NAME, 107, Chant05, NEUTRAL_REACTION );
	end
	giq_option( -3, NAME, 108, Chant06, NEUTRAL_REACTION );
end

procedure Chant02 begin
	gsay_message( NAME, 109, NEUTRAL_REACTION );
end

procedure Chant03 begin
	gsay_message( NAME, 110, NEUTRAL_REACTION );
end

procedure Chant04 begin
	gsay_message( NAME, 111, NEUTRAL_REACTION );
end

procedure Chant05 begin
	gsay_message( NAME, 112, NEUTRAL_REACTION );
end

procedure Chant06 begin
	gsay_message( NAME, 113, GOOD_REACTION );
end

procedure Chant07 begin
	if (dude_is_male) then begin
		gsay_message( NAME, 114, GOOD_REACTION );
	end
	else begin
		gsay_message( NAME, 115, GOOD_REACTION );
	end
end

procedure ChantEnd begin
end

procedure Combat begin
	tmp_hostile := 1;
end

procedure destroy_p_proc begin
	inc_good_critter
end
