#include "define.h"

procedure start;

procedure start begin
   if (script_action == use_proc) then begin
      script_overrides;
      if source_is_dude then begin
         script_overrides;
         if ((anim_busy(dude_obj) != 0) or (anim_busy(dude_obj) == 0)) then begin
            play_sfx("SODOORSF");
            reg_anim_clear(dude_obj);
            move_to(dude_obj, 19701, 0);
         end
      end
   end
end
