/*

   Cathedral - Moore

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_GIDEON
#define TOWN_REP_VAR            (GVAR_TOWN_REP_CATHEDRAL)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;

procedure dialog_end;
procedure moore00;
procedure moore01;
procedure moore02;
procedure moore03;
procedure moore04;

variable tmp_hostile;
variable Only_Once := 1;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      set_self_team(TEAM_50);
      set_self_ai(AI_BRAINWASHED_CHILDREN);
   end
end

procedure combat begin
   tmp_hostile := 1;
end

procedure critter_p_proc begin
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   dude_look_at_self;
   get_reaction

   if (local_var(4) == 0) then begin
      start_dialog_at_node(moore00);
   end
   else begin
      start_dialog_at_node(moore01);
   end
   set_local_var(4, 1);
end

procedure destroy_p_proc begin
   inc_inv_evil_crit
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(200));
end

procedure dialog_end begin
end

procedure moore00 begin
   Reply(202);
   giq_option(8, NAME, 203, moore03, 49 + random(0, 2));
   giq_option(4, NAME, 204, moore02, 49 + random(0, 2));
   if (has_rep_berserker) then begin
      giq_option(4, NAME, 205, moore04, 49 + random(0, 2));
   end
   giq_option(4, NAME, 206, dialog_end, 49 + random(0, 2));
   giq_option(-3, NAME, 207, moore04, 49 + random(0, 2));
end

procedure moore01 begin
   Reply(208);
   giq_option(8, NAME, 209, moore03, 49 + random(0, 2));
   giq_option(4, NAME, 210, moore04, 49 + random(0, 2));
   giq_option(4, NAME, 211, moore02, 49 + random(0, 2));
   if (has_rep_berserker) then begin
      giq_option(4, NAME, 212, moore02, 49 + random(0, 2));
   end
   giq_option(4, NAME, 213, dialog_end, 49 + random(0, 2));
end

procedure moore02 begin
   Reply(214);
   giq_option(4, NAME, 216, moore03, 49 + random(0, 2));
   giq_option(4, NAME, 217, moore04, 49 + random(0, 2));
end

procedure moore03 begin
   gsay_message(NAME, 218, 49 + random(0, 2));
   call dialog_end;
end

procedure moore04 begin
   gsay_message(NAME, 219, 49 + random(0, 2));
   call dialog_end;
end
