#include "define.h"

#define NAME                    SCRIPT_MVRCRDOR

#include "command.h"

procedure start;

procedure use_stuff;
procedure pick_lock;

variable unlocked;
variable bonus;

procedure start begin
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure description_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure use_p_proc begin
   call use_stuff;
end

procedure use_obj_on_p_proc begin
   variable Item := obj_pid(obj_being_used_with);

   if (Item == PID_ELECTRONIC_LOCKPICKS) then begin
      bonus := -20;
      call pick_lock;
   end
   else if (Item == PID_ELEC_LOCKPICK_MKII) then begin
      bonus := -10;
      call pick_lock;
   end
end

procedure damage_p_proc begin
   display_msg(message_str(SCRIPT_DOOR, 193));
end

procedure use_stuff begin
   if (not(unlocked)) then begin
      script_overrides;
      display_msg(mstr(101));
   end
end

procedure pick_lock begin
   script_overrides;
   if (unlocked) then begin
      display_msg(mstr(102));
   end
   else begin
      if (dude_skill_success(SKILL_LOCKPICK, bonus)) then begin
         display_msg(mstr(103));
         unlocked := 1;
      end
      else begin
         display_msg(mstr(104));
      end
   end
end
