/*

	Cathedral - Viola

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\maps\v13ent.h"

#define NAME                    SCRIPT_VIOLA
#define TOWN_REP_VAR            (GVAR_TOWN_REP_CATHEDRAL)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;

procedure viola00;
procedure viola01;
procedure viola02;
procedure viola03;
procedure viola04;
procedure viola05;
procedure viola05a;
procedure viola06;
procedure viola06a;
procedure viola07;
procedure viola07a;
procedure viola08;
procedure viola08a;
procedure viola09;
procedure viola10;
procedure viola11;
procedure viola12;
procedure viola13;
procedure viola14;
procedure viola15;
procedure viola16;
procedure viola17;
procedure viola18;
procedure viola19;
procedure viola20;
procedure viola21;
procedure viola22;
procedure viola23;
procedure viola24;
procedure viola25;
procedure viola26;
procedure viola27;
procedure viola28;
procedure viola29;
procedure viola30;
procedure viola31;
procedure viola32;
procedure viola33;
procedure viola34;
procedure viola35;
procedure viola36;
procedure viola37;
procedure viola38;
procedure viola39;
procedure viola40;
procedure viola41;
procedure viola42;
procedure viola43;
procedure viola44;
procedure viola45;
procedure viola46;
procedure viola47;
procedure viola48;
procedure viola49;
procedure viola50;
procedure viola51;
procedure viola52;
procedure viola53;
procedure viola53a;
procedure viola54;
procedure viola55;
procedure viola56;
procedure viola57;
procedure viola58;
procedure viola59;
procedure viola60;
procedure viola61;
procedure viola62;
procedure viola63;
procedure viola64;
procedure viola65;
procedure viola66;
procedure viola67;
procedure viola68;
procedure viola69;
procedure viola70;
procedure viola71;
procedure viola72;
procedure viola73;
procedure viola74;
procedure viola75;
procedure viola76;
procedure violadone;
procedure violaend;
procedure violacombat;
procedure weapon_check;

variable tmp_hostile;
variable armed;
variable GENDER;
variable LASHERKNOWN;
variable Only_Once := 1;
variable TALKEDTOLAURA;
variable LAURAWARNING;

variable SrcObj := 0;
variable SrcIsParty := 0;

procedure start begin
	if Only_Once then begin
		set_self_team(TEAM_CATHEDRAL);
		set_self_ai(AI_CHILDREN_TRUE);
		Only_Once := 0;
	end
end

procedure look_at_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_VIOLA, 100));
end

procedure description_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_VIOLA, 100));
end

procedure critter_p_proc begin
	if (tmp_hostile) then begin
		tmp_hostile := 0;
		attack(dude_obj);
	end
end

procedure pickup_p_proc begin
	tmp_hostile := 1;
end

procedure destroy_p_proc begin
	if (source_obj == dude_obj) then begin
		inc_inv_evil_crit
	end
end

procedure talk_p_proc begin
	dude_look_at_self;
	GENDER := dude_gender;
	call weapon_check;
	start_dialog( self_obj, 4 );
	gsay_start;
	if ((local_var(4) == 1) and (dude_iq < 4)) then begin
		gsay_message( SCRIPT_VIOLA, 143, BAD_REACTION );
	end
	else begin
		if ((global_var( GVAR_CATHEDRAL_ENEMY ) == 1) and not(dude_wearing_coc_robe)) then begin
			call viola00;
		end
		else begin
			if (TALKEDTOLAURA == 1) then begin
				if (LAURAWARNING == 0) then begin
					call viola01;
				end
				else begin
					call viola02;
				end
			end
			else begin
				if (armed == 1) then begin
					call viola03;
				end
				else begin
					if ((local_var(4) == 1) and (LAURAWARNING == 0)) then begin
						call viola04;
					end
					else begin
						if (armed == 0) then begin
							if dude_wearing_coc_robe then begin
								call viola05;
							end
							else begin
								if (has_rep_champion) then begin
									call viola06;
								end
								else begin
									if (has_rep_childkiller and (has_rep_berserker)) then begin
										call viola07;
									end
									else begin
										call viola08;
									end
								end
							end
						end
					end
				end
			end
		end
	end
	set_local_var(4, 1);
	gsay_end;
	end_dialogue;
end

procedure viola00 begin
	if (GENDER == 0) then begin
		gsay_reply( SCRIPT_VIOLA, 101 );
	end
	else begin
		gsay_reply( SCRIPT_VIOLA, 102 );
	end
	NOption( 103, viola09, 7 );
	NOption( 104, viola10, 7 );
	NOption( 105, viola11, 4 );
	if (global_var( GVAR_ALCOHOL_ADDICT ) == 1) then begin
		NOption( 106, viola12, 4 );
	end
	NOption( 107, violacombat, 4 );
	NOption( 299, violaend, -3 );
	NOption( 108, violacombat, -3 );
end

procedure viola01 begin
	LAURAWARNING := 1;
	gsay_reply( SCRIPT_VIOLA, 109 );
	NOption( 110, viola13, 7 );
	NOption( 111, viola14, 4 );
	NOption( 112, viola15, 4 );
	if (has_rep_berserker) then begin
		NOption( 113, violacombat, 4 );
	end
	NOption( 114, violaend, -3 );
end

procedure viola02 begin
	gsay_message( SCRIPT_VIOLA, 115, NEUTRAL_REACTION );
end

procedure viola03 begin
	debug("msg!!");
	gsay_message( SCRIPT_VIOLA, 116, NEUTRAL_REACTION );
end

procedure viola04 begin
	gsay_reply( SCRIPT_VIOLA, 117 );
	NOption( 118, viola15, 7 );
	NOption( 119, viola16, 4 );
	NOption( 120, viola17, 4 );
	if (global_var( GVAR_ALCOHOL_ADDICT ) == 1) then begin
		NOption( 121, viola18, 4 );
	end
	if (has_rep_berserker) then begin
		NOption( 122, viola19, 4 );
	end
	NOption( 299, violaend, -3 );
end

procedure viola05 begin
	gsay_reply( SCRIPT_VIOLA, 123 );
	NOption( 124, viola05a, 7 );
	NOption( 125, viola46, 4 );
	NOption( 126, viola47, 4 );
	NOption( 127, viola48, 4 );
	if (has_rep_berserker) then begin
		NOption( 128, viola49, 4 );
	end
end

procedure viola05a begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call viola44;
	end
	else begin
		call viola45;
	end
end

procedure viola06 begin
	if (GENDER == 0) then begin
		gsay_reply( SCRIPT_VIOLA, 129 );
	end
	else begin
		gsay_reply( SCRIPT_VIOLA, 130 );
	end
	NOption( 131, viola06a, 7 );
	NOption( 132, viola52, 4 );
	NOption( 133, viola47, 4 );
	NOption( 134, viola48, 4 );
	if (has_rep_berserker) then begin
		NOption( 135, viola49, 4 );
	end
end

procedure viola06a begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call viola50;
	end
	else begin
		call viola51;
	end
end

procedure viola07 begin
	if (GENDER == 0) then begin
		gsay_reply( SCRIPT_VIOLA, 136 );
	end
	else begin
		gsay_reply( SCRIPT_VIOLA, 137 );
	end
	NOption( 138, viola07a, 7 );
	NOption( 139, viola52, 4 );
	NOption( 140, viola47, 4 );
	NOption( 141, viola48, 4 );
	if (has_rep_berserker) then begin
		NOption( 142, viola49, 4 );
	end
end

procedure viola07a begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call viola50;
	end
	else begin
		call viola51;
	end
end

procedure viola08 begin
	gsay_reply( SCRIPT_VIOLA, 143 );
	NOption( 144, viola08a, 7 );
	NOption( 145, viola55, 4 );
	if (has_rep_berserker) then begin
		NOption( 146, viola40, 4 );
	end
	NOption( 299, violaend, -3 );
end

procedure viola08a begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call viola53;
	end
	else begin
		call viola54;
	end
end

procedure viola09 begin
	gsay_message( SCRIPT_VIOLA, 147, NEUTRAL_REACTION );
end

procedure viola10 begin
	gsay_message( SCRIPT_VIOLA, 148, NEUTRAL_REACTION );
end

procedure viola11 begin
	gsay_message( SCRIPT_VIOLA, 149, NEUTRAL_REACTION );
end

procedure viola12 begin
	gsay_message( SCRIPT_VIOLA, 150, NEUTRAL_REACTION );
end

procedure viola13 begin
	gsay_reply( SCRIPT_VIOLA, 151 );
	NOption( 152, viola20, 7 );
	NOption( 153, viola21, 4 );
	NOption( 154, viola22, 4 );
	if (has_rep_berserker) then begin
		NOption( 155, viola23, 4 );
	end
end

procedure viola14
begin
	gsay_reply( SCRIPT_VIOLA, 156 );
	NOption( 157, viola16, 7 );
	NOption( 158, viola21, 4 );
	NOption( 159, viola22, 4 );
	if (has_rep_berserker) then begin
		NOption( 160, viola23, 4 );
	end
end

procedure viola15
begin
	gsay_message( SCRIPT_VIOLA, 161, NEUTRAL_REACTION );
end

procedure viola16
begin
	gsay_message( SCRIPT_VIOLA, 162, NEUTRAL_REACTION );
end

procedure viola17
begin
	gsay_message( SCRIPT_VIOLA, 163, NEUTRAL_REACTION );
end

procedure viola18
begin
	gsay_message( SCRIPT_VIOLA, 164, NEUTRAL_REACTION );
end

procedure viola19
begin
	gsay_message( SCRIPT_VIOLA, 165, NEUTRAL_REACTION );
end

procedure viola20
begin
	gsay_reply( SCRIPT_VIOLA, 166 );
	NOption( 167, viola24, 7 );
	NOption( 168, viola24, 4 );
	NOption( 169, viola25, 4 );
	NOption( 170, viola26, 4 );
	NOption( 171, viola27, 4 );
end

procedure viola21
begin
	gsay_message( SCRIPT_VIOLA, 172, NEUTRAL_REACTION );
end

procedure viola22
begin
	gsay_reply( SCRIPT_VIOLA, 173 );
	NOption( 174, viola41, 7 );
	NOption( 175, viola21, 4 );
	NOption( 176, viola42, 4 );
	if (has_rep_berserker) then begin
		NOption( 177, viola43, 4 );
	end
end

procedure viola23
begin
	gsay_message( SCRIPT_VIOLA, 178, NEUTRAL_REACTION );
end

procedure viola24
begin
	gsay_reply( SCRIPT_VIOLA, 179 );
	NOption( 180, viola28, 7 );
	NOption( 181, viola29, 7 );
	NOption( 182, viola30, 4 );
	NOption( 183, viola31, 4 );
end

procedure viola25
begin
	gsay_reply( SCRIPT_VIOLA, 184 );
	NOption( 185, viola31, 7 );
	NOption( 186, viola32, 4 );
	NOption( 187, viola33, 4 );
	if (has_rep_berserker) then begin
		NOption( 188, viola34, 4 );
	end
end

procedure viola26
begin
	gsay_reply( SCRIPT_VIOLA, 189 );
	NOption( 190, viola35, 7 );
	NOption( 191, viola32, 4 );
	NOption( 192, viola36, 4 );
	if (has_rep_berserker) then begin
		NOption( 193, viola37, 4 );
	end
end

procedure viola27
begin
	gsay_reply( SCRIPT_VIOLA, 194 );
	NOption( 195, viola29, 7 );
	NOption( 196, viola38, 4 );
	NOption( 197, viola39, 4 );
	if (has_rep_berserker) then begin
		NOption( 198, viola40, 4 );
	end
end

procedure viola28
begin
	gsay_message( SCRIPT_VIOLA, 199, NEUTRAL_REACTION );
end

procedure viola29
begin
	gsay_message( SCRIPT_VIOLA, 200, NEUTRAL_REACTION );
end

procedure viola30
begin
	gsay_message( SCRIPT_VIOLA, 201, NEUTRAL_REACTION );
end

procedure viola31
begin
	gsay_message( SCRIPT_VIOLA, 202, NEUTRAL_REACTION );
end

procedure viola32
begin
	gsay_message( SCRIPT_VIOLA, 203, NEUTRAL_REACTION );
end

procedure viola33
begin
	gsay_message( SCRIPT_VIOLA, 204, NEUTRAL_REACTION );
end

procedure viola34
begin
	gsay_message( SCRIPT_VIOLA, 205, NEUTRAL_REACTION );
end

procedure viola35
begin
	gsay_message( SCRIPT_VIOLA, 206, NEUTRAL_REACTION );
end

procedure viola36
begin
	gsay_message( SCRIPT_VIOLA, 207, NEUTRAL_REACTION );
end

procedure viola37
begin
	gsay_message( SCRIPT_VIOLA, 208, NEUTRAL_REACTION );
end

procedure viola38
begin
	gsay_message( SCRIPT_VIOLA, 209, NEUTRAL_REACTION );
end

procedure viola39
begin
	gsay_message( SCRIPT_VIOLA, 210, NEUTRAL_REACTION );
end

procedure viola40
begin
	gsay_message( SCRIPT_VIOLA, 211, NEUTRAL_REACTION );
end

procedure viola41
begin
	gsay_reply( SCRIPT_VIOLA, 212 );
	NOption( 213, viola28, 7 );
	NOption( 214, viola29, 7 );
	NOption( 215, viola32, 4 );
	NOption( 216, viola30, 4 );
	NOption( 217, viola31, 4 );
	if (has_rep_berserker) then begin
		NOption( 218, viola43, 4 );
	end
end

procedure viola42
begin
	gsay_reply( SCRIPT_VIOLA, 219 );
	NOption( 220, viola28, 7 );
	NOption( 221, viola29, 7 );
	NOption( 222, viola32, 4 );
	NOption( 223, viola30, 4 );
	NOption( 224, viola31, 4 );
	if (has_rep_berserker) then begin
		NOption( 225, viola43, 4 );
	end
end

procedure viola43
begin
	gsay_message( SCRIPT_VIOLA, 226, NEUTRAL_REACTION );
end

procedure viola44
begin
	gsay_reply( SCRIPT_VIOLA, 227 );
	NOption( 228, viola56, 7 );
	NOption( 229, viola16, 4 );
	NOption( 230, viola57, 4 );
	if (has_rep_berserker) then begin
		NOption( 231, viola49, 4 );
	end
end

procedure viola45
begin
	gsay_message( SCRIPT_VIOLA, 232, NEUTRAL_REACTION );
end

procedure viola46
begin
	gsay_message( SCRIPT_VIOLA, 233, NEUTRAL_REACTION );
end

procedure viola47
begin
	gsay_reply( SCRIPT_VIOLA, 234 );
	NOption( 235, viola58, 7 );
	NOption( 236, viola59, 7 );
	NOption( 237, viola60, 4 );
	NOption( 238, viola61, 4 );
	NOption( 239, viola62, 4 );
end

procedure viola48
begin
	gsay_reply( SCRIPT_VIOLA, 240 );
	NOption( 241, viola63, 7 );
	NOption( 242, viola64, 7 );
	NOption( 243, viola65, 4 );
	NOption( 244, viola66, 4 );
	NOption( 245, viola67, 4 );
end

procedure viola49
begin
	gsay_message( SCRIPT_VIOLA, 246, NEUTRAL_REACTION );
end

procedure viola50
begin
	gsay_reply( SCRIPT_VIOLA, 247 );
	NOption( 248, viola68, 7 );
	NOption( 249, viola69, 7 );
	NOption( 250, viola70, 7 );
	NOption( 251, viola49, 7 );
	NOption( 252, viola16, 7 );
end

procedure viola51
begin
	gsay_message( SCRIPT_VIOLA, 253, NEUTRAL_REACTION );
end

procedure viola52
begin
	gsay_reply( SCRIPT_VIOLA, 254 );
	NOption( 255, viola71, 7 );
	NOption( 256, viola72, 7 );
	NOption( 257, viola73, 4 );
	NOption( 258, viola74, 4 );
	if (has_rep_berserker) then begin
		NOption( 259, viola75, 4 );
	end
end

procedure viola53
begin
	gsay_reply( SCRIPT_VIOLA, 260 );
	NOption( 261, viola53a, 7 );
	NOption( 262, viola52, 4 );
	NOption( 263, viola47, 4 );
	NOption( 264, viola48, 4 );
	NOption( 265, viola49, 4 );
end

procedure viola53a
begin
	if (is_success(roll_vs_skill(dude_obj, SKILL_SPEECH, 0))) then begin
		call viola50;
	end
	else begin
		call viola51;
	end
end

procedure viola54
begin
	gsay_message( SCRIPT_VIOLA, 266, NEUTRAL_REACTION );
end

procedure viola55
begin
	gsay_message( SCRIPT_VIOLA, 267, NEUTRAL_REACTION );
end

procedure viola56
begin
	gsay_message( SCRIPT_VIOLA, 268, NEUTRAL_REACTION );
end

procedure viola57
begin
	gsay_message( SCRIPT_VIOLA, 269, NEUTRAL_REACTION );
end

procedure viola58
begin
	gsay_message( SCRIPT_VIOLA, 270, NEUTRAL_REACTION );
end

procedure viola59
begin
	gsay_message( SCRIPT_VIOLA, 271, NEUTRAL_REACTION );
end

procedure viola60
begin
	gsay_message( SCRIPT_VIOLA, 272, NEUTRAL_REACTION );
end

procedure viola61
begin
	if (GENDER == 0) then begin
		gsay_message( SCRIPT_VIOLA, 273, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 274, NEUTRAL_REACTION );
	end
end

procedure viola62
begin
	if (GENDER == 0) then begin
		gsay_message( SCRIPT_VIOLA, 275, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 276, NEUTRAL_REACTION );
	end
end

procedure viola63
begin
	gsay_message( SCRIPT_VIOLA, 277, NEUTRAL_REACTION );
end

procedure viola64
begin
	gsay_reply( SCRIPT_VIOLA, 278 );
	NOption( 279, viola63, 7 );
	NOption( 280, viola76, 7 );
	NOption( 281, viola65, 4 );
	NOption( 282, viola66, 4 );
	NOption( 283, viola67, 4 );
end

procedure viola65
begin
	gsay_message( SCRIPT_VIOLA, 284, NEUTRAL_REACTION );
end

procedure viola66
begin
	gsay_message( SCRIPT_VIOLA, 285, NEUTRAL_REACTION );
end

procedure viola67
begin
	if (GENDER == 0) then begin
		gsay_message( SCRIPT_VIOLA, 286, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 287, NEUTRAL_REACTION );
	end
end

procedure viola68
begin
	gsay_message( SCRIPT_VIOLA, 288, NEUTRAL_REACTION );
end

procedure viola69
begin
	gsay_message( SCRIPT_VIOLA, 289, NEUTRAL_REACTION );
end

procedure viola70
begin
	if (dude_is_male) then begin
		gsay_message( SCRIPT_VIOLA, 302, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 303, NEUTRAL_REACTION );
	end
end

procedure viola71
begin
	if (dude_is_male) then begin
		gsay_message( SCRIPT_VIOLA, 304, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 305, NEUTRAL_REACTION );
	end
end

procedure viola72
begin
	if (dude_is_male) then begin
		gsay_message( SCRIPT_VIOLA, 306, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 307, NEUTRAL_REACTION );
	end
end

procedure viola73
begin
	if (dude_is_male) then begin
		gsay_message( SCRIPT_VIOLA, 300, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 301, NEUTRAL_REACTION );
	end
end

procedure viola74
begin
	gsay_message( SCRIPT_VIOLA, 294, NEUTRAL_REACTION );
end

procedure viola75
begin
	if (GENDER == 0) then begin
		gsay_message( SCRIPT_VIOLA, 295, NEUTRAL_REACTION );
	end
	else begin
		gsay_message( SCRIPT_VIOLA, 296, NEUTRAL_REACTION );
	end
end

procedure viola76
begin
	gsay_message( SCRIPT_VIOLA, 297, NEUTRAL_REACTION );
end

procedure violadone
begin
	gsay_option( SCRIPT_VIOLA, 298, violaend, 50 );
end

procedure violaend begin
end

procedure violacombat begin
	set_global_var( GVAR_CATHEDRAL_ENEMY, 1 );
	tmp_hostile := 1;
end

procedure weapon_check begin

	if (dude_is_armed) then begin
		armed := 1;
	end
	else begin
		armed := 0;
	end
end
