/*

   Cathedral - Tower

*/

#include "define.h"
#include "updatmap.h"
#include "command.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;

export variable signal_mutants;
export variable Master_Ptr;

export variable Morpheus_Ptr;

procedure start begin
end

procedure map_enter_p_proc begin
   Lighting;

   set_global_var(GVAR_LOAD_MAP_INDEX, 0);
end

procedure map_update_p_proc begin
   Lighting;
end
