/*

   Mariposa - Ruins

*/

#include "define.h"
#include "command.h"
#include "updatmap.h"
#include "sfall/main.h"

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;

variable party_elevation;
variable dude_start_hex;

procedure start begin
end

procedure map_enter_p_proc begin
   override_map_start(133, 111, 0, 5);

   Lighting;

   if get_car_from_worldmap then begin
      override_map_start_hex(22321, 0, 0);
   end

   set_global_var(GVAR_LOAD_MAP_INDEX, 0);
end

procedure map_update_p_proc begin
   Lighting;
end

procedure map_exit_p_proc begin
   if not(is_story_finished) and waterchip_returned and master_killed and vats_destruction_started then begin
      force_encounter_with_flags(MAP_V13ENT, ENCOUNTER_FLAG_FADEOUT);
   end
end
