/*

	The Glow - Zax, the super computer

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_ZAX
#define TOWN_REP_VAR            (GVAR_TOWN_REP_GLOW)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */
procedure start;
procedure talk_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;

procedure ZAX01;
procedure ZAX02;
procedure ZAX03;
procedure ZAX04;
procedure ZAX05;
procedure ZAX06;
procedure ZAX07;
procedure ZAX08;
procedure ZAX09;
procedure ZAX10;
procedure ZAX11;
procedure ZAX12;
procedure ZAX13;
procedure ZAX14;
procedure ZAX15;
procedure ZAX16;
procedure ZAX17;
procedure ZAX18;
procedure ZAX19;
procedure ZAX20;
procedure ZAX21;
procedure ZAX22;
procedure ZAX23;
procedure ZAX24;
procedure ZAX25;
procedure ZAXClearance;

procedure Term01;
procedure Term02;
procedure Term03;
procedure Term03a;
procedure Term04;
procedure Term05;
procedure Term06;
procedure Term06a;
procedure Term07;
procedure Term08;
procedure Term09;
procedure Term09a;
procedure Term10;
procedure Term11;
procedure Term11a;
procedure Term12;
procedure Term13;
procedure Term14;
procedure Term14a;
procedure Term15;
procedure TermEnd;
procedure TermStart;

procedure Mainframe00;
procedure Mainframe01;
procedure Mainframe02;
procedure Mainframe03;
procedure Mainframe04;
procedure Mainframe04a;
procedure Mainframe05;
procedure Mainframe05a;
procedure Mainframe05b;
procedure Mainframe05c;
procedure Mainframe06;
procedure Mainframe06a;
procedure Mainframe07;
procedure Mainframe07a;
procedure Mainframe08;
procedure Mainframe08a;
procedure Mainframe09;
procedure Mainframe10;

// for Fallout Fixt:
procedure ChessBlack;
procedure ChessWhite;
procedure ChessLongTourn;
procedure ChessTourn;
procedure ChessShortTourn;
procedure ChessQuick;
procedure ChessBlitz;
procedure ChessBullet;
procedure ChessPLAY;
procedure ChessLength;

variable BLACK;
variable WHITE;
variable Length;
variable ZAXroll;
variable XP;
variable Penalty;
variable LuckBonus;
variable PlayerRoll;

procedure start begin
end

procedure use_p_proc begin
	dialogue_system_enter;
end

procedure look_at_p_proc begin
	script_overrides;
	if (local_var(4) == 1) then begin
		display_msg(message_str(SCRIPT_ZAX, 100));
	end
	else begin
		display_msg(message_str(SCRIPT_ZAX, 101));
	end
end

procedure description_p_proc begin
	if (local_var(4) == 1) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_ZAX, 101));
	end
end

procedure talk_p_proc begin
	script_overrides;
	dude_look_at_self;
	start_gdialog(312, self_obj, 4, -1, -1);
	gsay_start;
	call ZAX01;
	gsay_end;
	end_dialogue;
end

procedure ZAX01 begin
	gsay_reply(312, 102);
	if (local_var(4) == 0) then begin
		giq_option( 5, SCRIPT_ZAX, 103, ZAX02, NEUTRAL_REACTION );
	end
	giq_option( 5, SCRIPT_ZAX, 105, ZAX04, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 106, ZAX12, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_GPWRTERM, 200, Mainframe00, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 108, ZAX13, NEUTRAL_REACTION );
	giq_option( -4, SCRIPT_ZAX, 109, ZAX05, NEUTRAL_REACTION );
end

procedure ZAX02 begin
	set_local_var(4, 1);
	gsay_reply(312, 110);
	giq_option( 5, SCRIPT_ZAX, 111, ZAX06, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 112, ZAX04, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 113, ZAX07, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 114, ZAX08, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_ZAX, 115, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX03
begin
	gsay_message(312, 116, 50);
	set_local_var(5, 1);
	call ZAX01;
end

procedure ZAX04
begin
	call ZAXClearance;
	gsay_reply(828, message_str(SCRIPT_GPWRTERM, 211) + message_str(SCRIPT_GPWRTERM, 241) + message_str(SCRIPT_GPWRTERM, 242) + message_str(SCRIPT_GPWRTERM, 243));
	giq_option( 7, SCRIPT_ZAX, 119, ZAX21, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 120, ZAX15, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 121, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX05
begin
	gsay_message(312, 122, 50);
end

procedure ZAX06
begin
	call ZAXClearance;
	gsay_reply(312, 123);
	giq_option( 5, SCRIPT_ZAX, 124, ZAX14, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 125, ZAX15, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 126, ZAX07, NEUTRAL_REACTION );
end

procedure ZAX07
begin
	gsay_reply(312, 127);
	giq_option( 7, SCRIPT_ZAX, 128, ZAX08, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 121, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX08
begin
	gsay_message(312, 129, 50);
	gsay_reply(312, 130);
	giq_option( 5, SCRIPT_ZAX, 131, ZAX01, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 132, ZAX09, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 133, ZAX11, NEUTRAL_REACTION );
end

procedure ZAX09
begin
	gsay_message(312, 134, 50);
	gsay_reply(312, 135);
	giq_option( 7, SCRIPT_ZAX, 136, ZAX10, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 137, ZAX01, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 138, ZAX11, NEUTRAL_REACTION );
end

procedure ZAX10
begin
	gsay_message(312, 139, 50);
	gsay_reply(312, 140);
	giq_option( 7, SCRIPT_ZAX, 141, ZAX01, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 142, ZAX11, NEUTRAL_REACTION );
end

procedure ZAX11
begin
	gsay_message(312, 143, 50);
	gsay_message(312, 144, 50);
	gsay_reply(312, 145);
	giq_option( 5, SCRIPT_ZAX, 146, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 147, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX12 begin
	gsay_reply(312, message_str(SCRIPT_ZAX, 148) + local_var(11) + message_str(SCRIPT_ZAX, 228) + local_var(12) + message_str(SCRIPT_ZAX, 229) + local_var(13) + message_str(SCRIPT_ZAX, 230));
	giq_option( 5, SCRIPT_ZAX, 215, ChessBlack, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 216, ChessWhite, NEUTRAL_REACTION );
end

procedure ChessBlack begin
	BLACK := 1;
	WHITE := 0;
	call ChessLength;
end

procedure ChessWhite begin
	WHITE := 1;
	BLACK := 0;
	call ChessLength;
end

procedure ChessLength begin
	gsay_reply(312, 217);
	giq_option( 5, SCRIPT_ZAX, 218, ChessLongTourn, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 219, ChessTourn, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 220, ChessShortTourn, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 221, ChessQuick, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 222, ChessBlitz, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 223, ChessBullet, NEUTRAL_REACTION );
end

procedure ChessLongTourn begin
	Length := 360;//  6 hours
	Penalty := random(1, 3) + random(1, 3) + random(1, 3);
	LuckBonus := 0;
	XP := 700;// 650 or 750
	call ChessPLAY;
end

procedure ChessTourn
begin
	Length := 240;//  4 hours
	Penalty := random(1, 3) + random(1, 3);
	LuckBonus := 0;
	XP := 600;// 550 or 650
	call ChessPLAY;
end

procedure ChessShortTourn
begin
	Length := 120;//  2 hours
	Penalty := random(1, 3);
	LuckBonus := 0;
	XP := 500;// 450 or 550
	call ChessPLAY;
end

procedure ChessQuick
begin
	Length := 60;//   1 hour
	Penalty := 0;
	LuckBonus := 0;
	XP := 450;// 400 or 500
	call ChessPLAY;
end

procedure ChessBlitz
begin
	Length := 30;//  minutes
	Penalty := 0;
	if dude_luck > 5 then begin
		LuckBonus := dude_luck - 5;
	end
	XP := 350;// 300 or 400
	call ChessPLAY;
end

procedure ChessBullet
begin
	Length := 6;//  minutes
	Penalty := 0;
	if dude_luck > 5 then begin
		LuckBonus := dude_luck;
	end
	XP := 250;// 200 or 300
	call ChessPLAY;
end

procedure ChessPLAY begin
	gfade_out(1);
	game_time_advance(10 * 60 * Length);// how many minutes
	gfade_in(1);
	if dude_iq == 10 then begin
// ZAX rolls 1 to 101
		ZAXroll := 1 + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10) + random(0, 10);
		PlayerRoll := (50 - Penalty) + LuckBonus;
		if BLACK == 1 then begin
			XP := (XP + 50);
			PlayerRoll := (PlayerRoll - (random(1, 3) + random(1, 3)));
		end
		else begin
			if WHITE == 1 then begin
				XP := (XP - 50);
				PlayerRoll := (PlayerRoll + (random(1, 3) + random(1, 3)));
			end
		end
		if PlayerRoll == ZAXroll then begin
			set_local_var(12, local_var(12) + 1);// Draws
			gsay_reply(312, 225);
		end
		else begin
			if PlayerRoll > ZAXroll then begin
				set_local_var(11, local_var(11) + 1);// Wins
				if local_var(6) == 0 then begin
					set_local_var(6, 1);// already_got_XP flag
					display_msg(message_str(SCRIPT_ZAX, 226) + XP + message_str(SCRIPT_ZAX, 227));
					give_exp_points(XP);

					inc_glow_rep(REP_BONUS_DEFEAT_ZAX);
				end
				gsay_reply(312, 149);
			end
			else begin
				set_local_var(13, local_var(13) + 1);// Losses
				gsay_reply(312, 150);
			end
		end
	end
	else begin
		set_local_var(13, local_var(13) + 1);// Losses
		gsay_reply(312, 224);
	end
	giq_option( 5, SCRIPT_ZAX, 151, ZAX12, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 152, ZAX01, NEUTRAL_REACTION );
end

procedure ZAX13
begin
	gsay_message(312, 153, 50);
end

procedure ZAX14
begin
	gsay_reply(312, 154);
	giq_option( 5, SCRIPT_ZAX, 155, ZAX13, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 156, ZAX01, NEUTRAL_REACTION );
end

procedure ZAX15
begin
	gsay_message(312, 157, 50);
	gsay_reply(312, 158);
	giq_option( 5, SCRIPT_ZAX, 159, ZAX16, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 160, ZAX17, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 161, ZAX18, NEUTRAL_REACTION );
end

procedure ZAX16
begin
	gsay_reply(312, 162);
	giq_option( 5, SCRIPT_ZAX, 163, ZAX01, NEUTRAL_REACTION );
	giq_option( 7, SCRIPT_ZAX, 164, ZAX17, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 165, ZAX18, NEUTRAL_REACTION );
end

procedure ZAX17
begin
	gsay_reply(312, 166);
	giq_option( 5, SCRIPT_ZAX, 167, ZAX01, NEUTRAL_REACTION );
	giq_option( 9, SCRIPT_ZAX, 168, ZAX18, NEUTRAL_REACTION );
end

procedure ZAX18
begin
	gsay_message(312, 169, 50);
	gsay_message(312, 170, 50);
	gsay_message(312, 171, 50);
	gsay_message(312, 172, 50);
	gsay_reply(312, 173);
	giq_option( 9, SCRIPT_ZAX, 174, ZAX19, NEUTRAL_REACTION );
	giq_option( 10, SCRIPT_ZAX, 175, ZAX20, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 176, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 177, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX19
begin
	gsay_message(312, 178, 50);
	gsay_message(312, 179, 50);
	gsay_reply(312, 180);
	giq_option( 10, SCRIPT_ZAX, 181, ZAX20, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 182, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 183, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX20
begin
	gsay_reply(312, 184);
	giq_option( 9, SCRIPT_ZAX, 185, ZAX19, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 186, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 187, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX21
begin
	gsay_reply(312, 188);
	giq_option( 5, SCRIPT_ZAX, 189, ZAX22, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 190, ZAX23, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 191, ZAX24, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 192, ZAX01, NEUTRAL_REACTION );
end

procedure ZAX22
begin
	gsay_reply(312, 193);
	giq_option( 5, SCRIPT_ZAX, 194, ZAX23, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 195, ZAX24, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 196, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 197, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX23
begin
	gsay_reply(312, 198);
	giq_option( 5, SCRIPT_ZAX, 199, ZAX22, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 200, ZAX24, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 201, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 202, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX24
begin
	gsay_reply(312, 203);
	giq_option( 5, SCRIPT_ZAX, 204, ZAX22, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 205, ZAX23, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 206, ZAX01, NEUTRAL_REACTION );
	giq_option( 5, SCRIPT_ZAX, 207, ZAX13, NEUTRAL_REACTION );
end

procedure ZAX25
begin
	gsay_message(312, 208, 50);
	if (global_var( GVAR_WEAPON_LOCKER ) == 1) then begin
		gsay_message(312, 209, 50);
		set_global_var( GVAR_WEAPON_LOCKER, 2 );
	end
end

procedure ZAXClearance
begin
	if (global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF )) then begin
		gsay_message(312, 210, 50);
		gsay_message(312, 211, 50);
		set_global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF, 0 );
	end
end

procedure Term01 begin
	gsay_reply(828, 100);
	giq_option( 4, SCRIPT_GPWRTERM, 101, Term02, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 102, Term10, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_GPWRTERM, 103, Mainframe02, NEUTRAL_REACTION );
end

procedure Term02
begin
	gsay_reply(828, 104);
	giq_option( 4, SCRIPT_GPWRTERM, 105, Term03, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 106, Term06, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 107, Term01, NEUTRAL_REACTION );
end

procedure Term03
begin
	gsay_reply(828, 108);
	giq_option( 4, SCRIPT_GPWRTERM, 109, Term03a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 110, Term02, NEUTRAL_REACTION );
end

procedure Term03a
begin
	if (global_var( GVAR_QUEST_GLOW_2_START_POWER ) != 2) then begin
		call Term04;
	end
	else begin
		set_global_var( GVAR_GLOW_POWER, 2 );
	end
end

procedure Term04
begin
	gsay_reply(828, 111);
	giq_option( 8, SCRIPT_GPWRTERM, 112, Term05, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 113, Term02, NEUTRAL_REACTION );
end

procedure Term05
begin
	gsay_reply(828, 114);
	giq_option( 4, SCRIPT_GPWRTERM, 115, Term02, NEUTRAL_REACTION );
end

procedure Term06 begin
	gsay_reply(828, 116);
	giq_option( 4, SCRIPT_GPWRTERM, 117, Term06a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 118, Term02, NEUTRAL_REACTION );
end

procedure Term06a begin
	set_global_var( GVAR_GLOW_POWER, 0 );
end

procedure Term07 begin
	gsay_reply(828, 119);
	giq_option( 4, SCRIPT_GPWRTERM, 120, Term08, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_GPWRTERM, 121, Mainframe02, NEUTRAL_REACTION );
end

procedure Term08 begin
	gsay_reply(828, 122);
	giq_option( 4, SCRIPT_GPWRTERM, 123, Term09a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 124, Term07, NEUTRAL_REACTION );
end

procedure Term09 begin
	gsay_reply(828, 125);
	giq_option( -3, SCRIPT_GPWRTERM, 126, Term09a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 127, Term09a, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_GPWRTERM, 128, Mainframe02, NEUTRAL_REACTION );
end

procedure Term09a begin
	set_global_var( GVAR_GLOW_POWER, 1 );
end

procedure Term10 begin
	gsay_reply(828, 129);
	giq_option( -3, SCRIPT_GPWRTERM, 130, Term11, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 131, Term13, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 132, Term01, NEUTRAL_REACTION );
end

procedure Term11 begin
	gsay_reply(828, 133);
	giq_option( -3, SCRIPT_GPWRTERM, 134, Term11a, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 135, Term10, NEUTRAL_REACTION );
end

procedure Term11a begin
	if (global_var( GVAR_QUEST_GLOW_2_START_POWER ) != 2) then begin
		call Term12;
	end
	else begin
		set_global_var( GVAR_GLOW_POWER, 2 );
	end
end

procedure Term12 begin
	gsay_reply(828, 136);
	giq_option( -3, SCRIPT_GPWRTERM, 137, Term10, NEUTRAL_REACTION );
end

procedure Term13 begin
	gsay_reply(828, 138);
	giq_option( -3, SCRIPT_GPWRTERM, 148, Term06a, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 137, Term10, NEUTRAL_REACTION );
end

procedure Term14 begin
	gsay_reply(828, 139);
	giq_option( 4, SCRIPT_GPWRTERM, 140, Term14a, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 141, Term15, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 142, Term15, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 143, Term14a, NEUTRAL_REACTION );
	giq_option( -3, SCRIPT_GPWRTERM, 144, Term15, NEUTRAL_REACTION );
	giq_option( 0, SCRIPT_GPWRTERM, 145, Mainframe02, NEUTRAL_REACTION );
end

procedure Term14a begin
	set_global_var( GVAR_GLOW_POWER, 1 );
	if (global_var( GVAR_QUEST_GLOW_2_START_POWER ) == 2) then begin
		call Term01;
	end
end

procedure Term15 begin
	gsay_reply(828, 146);
	giq_option( 0, SCRIPT_GPWRTERM, 147, Mainframe02, NEUTRAL_REACTION );
end

procedure TermEnd
begin
end

procedure TermStart
begin
	if (global_var( GVAR_GLOW_POWER ) == 0) then begin
		call Term14;
	end
	else begin
		if (global_var( GVAR_GLOW_POWER ) == 1) then begin
			call Term01;
		end
		else begin
			call Term09;
		end
	end
end

procedure Mainframe00
begin
	if (has_skill(dude_obj, SKILL_SCIENCE) >= 25) then begin
		set_local_var(8, 0);
	end
	if (local_var(8) == 0) then begin
		if (local_var(7) == 1) then begin
			call Mainframe01;
		end
		else begin
			if (is_success(roll_vs_skill(dude_obj, SKILL_SCIENCE, -10))) then begin
				set_local_var(7, 1);
				call Mainframe01;
			end
			else begin
				if (has_skill(dude_obj, SKILL_SCIENCE) < 25) then begin
					set_local_var(8, 1);
				end
				gsay_message(828, 201, 50);
			end
		end
	end
	else begin
		gsay_message(828, 201, 50);
		display_msg(message_str(SCRIPT_ZAX, 214));
	end
end

procedure Mainframe01
begin
	gsay_reply(828, 202);
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 204, ZAX01, NEUTRAL_REACTION );
end

procedure Mainframe02
begin
	gsay_reply(828, 206);
	giq_option( 4, SCRIPT_GPWRTERM, 207, Mainframe03, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 208, Mainframe04, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 209, Mainframe05, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 210, TermStart, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 204, ZAX01, NEUTRAL_REACTION );
end

procedure Mainframe03
begin
	gsay_reply(828, message_str(SCRIPT_GPWRTERM, 211) + message_str(SCRIPT_GPWRTERM, 241) + message_str(SCRIPT_GPWRTERM, 242) + message_str(SCRIPT_GPWRTERM, 243));
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe04
begin
	if ((global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF ) == 0) and (global_var( GVAR_GLOW_POWER ) == 2)) then begin
		gsay_reply(828, 212);
	end
	else begin
		gsay_reply(828, 213);
	end
	if (global_var( GVAR_GLOW_POWER ) == 2) then begin
		if (global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF ) == 0) then begin
			giq_option( 4, SCRIPT_GPWRTERM, 214, Mainframe04a, NEUTRAL_REACTION );
		end
		else begin
			giq_option( 4, SCRIPT_GPWRTERM, 215, Mainframe04a, NEUTRAL_REACTION );
		end
	end
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe04a begin
	game_time_advance(game_ticks(600));
	if (has_skill(dude_obj, SKILL_SCIENCE) >= 40) then begin
		set_local_var(9, 0);
	end
// HOLODISK_SECDISK_GLOW //  484  // ! Fallout Fixt: SECDISK.SSL, has read it?
	if (global_var( GVAR_SECDISK_HOLODISK_FLAG ) == 1) then begin
		if (global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF ) == 0) then begin
			set_global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF, 1 );
		end
		else begin
			set_global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF, 0 );
		end
		if (local_var(10) == 0) then begin
			give_exp_points(EXP_MAINFRAME_ACCESS);
			display_msg(message_str(SCRIPT_ZAX, 213));
			set_local_var(10, 1);
		end
		call Mainframe09;
	end
	if (local_var(9) == 0) then begin
		if (is_success(roll_vs_skill(dude_obj, SKILL_SCIENCE, -25))) then begin
			if (global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF ) == 0) then begin
				set_global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF, 1 );
			end
			else begin
				set_global_var( GVAR_QUEST_GLOW_1_TRAPS_OFF, 0 );
			end
			if (local_var(10) == 0) then begin
				give_exp_points(EXP_MAINFRAME_ACCESS);
				display_msg(message_str(SCRIPT_ZAX, 213));
				set_local_var(10, 1);
			end
			call Mainframe09;
		end
		else begin
			if (has_skill(dude_obj, SKILL_SCIENCE) < 40) then begin
				set_local_var(9, 1);
			end
			call Mainframe10;
		end
	end
	else begin
		if (local_var(9) == 1) then begin
			display_msg(message_str(SCRIPT_ZAX, 214));
			call Mainframe10;
		end
		else begin
			call Mainframe10;
		end
	end
end

procedure Mainframe05 begin
	gsay_reply(828, 216);
	giq_option( 4, SCRIPT_GPWRTERM, 217, Mainframe05a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 218, Mainframe05b, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 219, Mainframe05c, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe05a begin
	call Mainframe06;
end

procedure Mainframe05b begin
	call Mainframe07;
end

procedure Mainframe05c begin
	call Mainframe08;
end

procedure Mainframe06 begin
	gsay_message(828, 220, 50);
	gsay_message(828, 221, 50);
	gsay_message(828, 222, 50);
	gsay_message(828, 223, 50);
	gsay_message(828, 224, 50);
	gsay_message(828, 225, 50);
	gsay_message(828, 226, 50);
	gsay_message(828, 227, 50);
	gsay_reply(828, 228);
	giq_option( 4, SCRIPT_GPWRTERM, 229, Mainframe06a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 230, Mainframe05, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe06a begin
	set_global_var( GVAR_HOLODISK_PERSONNEL_RECORD, 1 );
	call Mainframe05;
end

procedure Mainframe07 begin
	gsay_reply(828, message_str(SCRIPT_GPWRTERM, 231) + message_str(SCRIPT_GPWRTERM, 250) + message_str(SCRIPT_GPWRTERM, 251) + message_str(SCRIPT_GPWRTERM, 252));
	giq_option( 4, SCRIPT_GPWRTERM, 229, Mainframe07a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 230, Mainframe05, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe07a begin
	set_global_var( GVAR_HOLODISK_POWER_ARMOR_SPEC, 1 );
	call Mainframe05;
end

procedure Mainframe08 begin
	gsay_message(828, message_str(SCRIPT_GPWRTERM, 232) + message_str(SCRIPT_GPWRTERM, 233), 50);
	gsay_message(828, message_str(SCRIPT_GPWRTERM, 234) + message_str(SCRIPT_GPWRTERM, 235), 50);
	gsay_reply(828, message_str(SCRIPT_GPWRTERM, 236) + message_str(SCRIPT_GPWRTERM, 237) + message_str(SCRIPT_GPWRTERM, 238));
	giq_option( 4, SCRIPT_GPWRTERM, 229, Mainframe08a, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 230, Mainframe05, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe08a begin
	set_global_var( GVAR_HOLODISK_FEV_SUMMARY_INFO, 1 );
	call Mainframe05;
end

procedure Mainframe09 begin
	gsay_reply(828, 239);
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end

procedure Mainframe10 begin
	game_time_advance(game_ticks(18000));
	gsay_reply(828, 240);
	giq_option( 4, SCRIPT_GPWRTERM, 203, Mainframe02, NEUTRAL_REACTION );
	giq_option( 4, SCRIPT_GPWRTERM, 205, TermEnd, NEUTRAL_REACTION );
end



