#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Rafales}
{1}{}{Fuite}
{2}{}{Armes préf.}
{3}{}{Distance}
{4}{}{Cible}
{5}{}{Stimulants}

{10}{}{Fait}
{11}{}{Annuler}

#
# Burst options.
#
{99}{}{Non applicable.}
{100}{}{Toujours !}
{101}{}{Peu importe si je me fais toucher.}
{102}{}{Attention à ne pas me toucher.}
{103}{}{Fais bien attention à ne pas me toucher.}
{104}{}{Attention à ne surtout pas me toucher.}

#
# Run away options.
#
{200}{}{Si tu es un horrible lâche.}
{201}{}{Si ton doigt te fait mal.}
{202}{}{Si tu saignes un peu.}
{203}{}{Si tu ne te sens pas bien.}
{204}{}{Si tu as besoin d'un garrot.}
{205}{}{Jamais !}

#
# Weapon pref options.
#
{300}{}{Aucune préférence.}
{301}{}{De Rixe.}
{302}{}{De Rixe plutôt que longue portée.}
{303}{}{Longue portée plutôt que de Rixe.}
{304}{}{Longue portée.}
{305}{}{Pas d'arme.}

#
# Distance options.
#
{400}{}{Reste près de moi.}
{401}{}{A l'attaque !}
{402}{}{Canarde l'ennemi à distance.}
{403}{}{Comme tu préfères.}
{404}{}{Reste où tu es.}

#
# Attack who options.
#
{500}{}{Mon attaquant.}
{501}{}{Le plus fort.}
{502}{}{Le plus faible.}
{503}{}{Qui tu veux.}
{504}{}{Le plus proche.}

#
# Chem use options.
#
{600}{}{Je ne prends rien.}
{601}{}{Utiliser un Stimpak dès que ça fait mal.}
{602}{}{Utiliser un Stimpak quand ça fait très mal.}
{603}{}{Utiliser des stimulants de temps en temps.}
{604}{}{Utiliser des stimulants régulièrement.}
