#
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
#
#
{100}{}{VALIDER}
{101}{}{OPTIONS}
{102}{}{ANNULER}
{103}{}{IMPRIMER}
{104}{}{AGE}
{105}{}{SEXE}
{106}{}{NOM}
{107}{}{MASC.}
{108}{}{FEM.}
{109}{}{APTITUDES}
{110}{}{KARMA}
{111}{}{VICTIMES}
{112}{}{POINTS COMP.}
{113}{}{Niveau}
{114}{}{Exp}
{115}{}{Niveau suiv.}
{116}{}{PTS PERSO.}
{117}{}{COMPETENCES}
{118}{}{Tu dois utiliser tous tes points de }  # 1
{119}{}{personnage avant de lancer le jeu !} # 2
#
##
## NOTE: Each line in the description box holds roughly 40 characters in English. Meaning to add a blank line, add 40 spaces and then reduce as needed.
##       This will differ based on words used (since it wraps based on the word length)  --Sduibek, Fallout Fixt
##
#
{120}{}{Points de personnage}
{121}{}{Nombre de points de personnage disponibles pouvant être ajoutés à l'une des statistiques de base.}
{122}{}{Niveau suivant}
{123}{}{Nombre de points d'expérience requis pour passer au niveau suivant.}
{124}{}{Aptitudes}
{125}{}{Karma}
{126}{}{Victimes}
{127}{}{Les aptitudes offrent des compétences supplémentaires. Tu peux choisir une aptitude tous les trois niveaux d'expérience.}
{128}{}{Reflète les effets des choix que tu effectues pendant le jeu.}
{129}{}{Indicateur répertoriant le type et le nombre de créatures que tu as éliminées ou que tu as vu se faire tuer.}
{130}{}{Points de compétence}
{131}{}{Utilise tes points de compétence disponibles pour accroître le niveau d'une compétence.}
#
{132}{}{Niveau maximum.} # 1
{133}{}{Impossible de l'augmenter.} # 2
{134}{}{Niveau minimum.} # 1
{135}{}{Impossible de décroître.}
{136}{}{Pas assez de point(s) de compétence.} # 2
{137}{}{Base :}
{138}{}{ATOUTS}
{139}{}{QUALITES FACULTATIVES (TRAITS)}
{140}{}{Tu possèdes déjà les trois } # 1
{141}{}{atouts personnels maximaux !}# 2
{142}{}{Tu dois sélectionner tous les atouts }# 1
{143}{}{personnels avant de lancer le jeu !}# 2
{144}{}{Atouts personnels }
{145}{}{Les atouts personnels correspondent aux spécialités de ton personnage. Chaque atout personnel donne +20% et augmente deux fois plus vite. Tu dois sélectionner trois atouts personnels.}
{146}{}{Qualités facultatives (traits)}
{147}{}{Les qualités facultatives (traits) présentent ton personnage plus en détail. Toutes les qualités ont des effets positifs et négatifs. Pour créer ton personnage, tu peux choisir au maximum deux qualités.}
{148}{}{Tu possèdes déjà les } # 1
{149}{}{2 qualités autorisées !}# 2
{150}{}{Compétences}
{151}{}{Correspondent aux connaissances acquises. Augmentent selon l'expérience ou les événements. Tes performances sont meilleures quand le niveau de la compétence est élevé.}
#
{152}{}{SELECTIONNE UNE APTITUDE}
{153}{}{SELECTIONNE UNE QUALITE (TRAIT)}
{154}{}{RENONCE A UNE QUALITE (TRAIT)}
{155}{}{SELECTIONNE UN NOUVEL ATOUT}
{156}{}{QUALITES (TRAITS)}
#
{157}{}{Toutes les statistiques doivent être comprises entre 1 et 10}# 1
{158}{}{avant de lancer le jeu !}# 2
# Fallout 2:
{160}{}{Attention : tu n'as pas changé le nom } # 1
{161}{}{de ton personnage. Continuer ?}        # 2

{175}{}{Niveau suiv. :}  # Short for Level:


#
#
#
# Abbreviated basic stat levels
#
{200}{}{Nul}
{201}{}{Mauv.}
{202}{}{Faible}
{203}{}{Moyen}
{204}{}{Normal}
{205}{}{Bon}
{206}{}{T. bon}
{207}{}{Super}
{208}{}{Exclt}
{209}{}{Héros}
#
#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{PI}
{301}{}{Points d'action}
{302}{}{Cla. d'armure}
{303}{}{Dégâts en Rixe}
{304}{}{Dégâts en Mélée}
{305}{}{Rés. dégâts}
{306}{}{Rés. poison}
{307}{}{Rés. radiations}
{308}{}{Séquence}
{309}{}{Vit. guérison}
{310}{}{Coups critiques}
{311}{}{Charge max.}
{312}{}{Empoisonnement}
{313}{}{Irradiation}
{314}{}{Blessure à l'œil}
{315}{}{Bras dr. estropié}
{316}{}{Bras g. estropié}
{317}{}{Jambe dr. estropiée}
{318}{}{Jambe g. estropiée}
#
#
# Damage info texts
#
# Poisoned
{400}{}{Ton personnage a été empoisonné. Le poison agira un certain temps, jusqu'à ce que le mal soit éradiqué ou jusqu'à ce qu'il soit soigné. L'Endurence augmente ta résistance au poison.}
{401}{}{Ton personnage a été sérieusement irradié. Plus les radiations sont importantes, plus leurs effets sont mortels. Monter à 1000 ou plus signifie généralement une mort certaine.}
# Eye Damage
{402}{}{Cela signifie que ton personnage a été sérieusement touché à un œil ou aux deux yeux. Ta perception en sera affectée.}
# Crippled right arm
{403}{}{Le bras droit du personnage a été gravement touché et estropié. Lorsqu'un bras est estropié, tu ne peux plus utiliser d'armes à deux mains. Lorsque les deux bras sont estropiés, tu ne peux plus utiliser d'arme pour attaquer.}
# Crippled left arm
{404}{}{Le bras gauche du personnage a été gravement touché et estropié. Lorsqu'un bras est estropié, tu ne peux plus utiliser d'armes à deux mains. Lorsque les deux bras sont estropiés, tu ne peux plus utiliser d'arme pour attaquer.}
# Crippled right leg
{405}{}{La jambe droite de ton personnage est estropiée. Cela affecte ta vitesse en combat, et tu ne peux pas courir.}
# Crippled left leg
{406}{}{La jambe gauche de ton personnage est estropiée. Cela affecte ta vitesse en combat, et tu ne peux pas courir.}
#
# Month strings
{500}{}{janvier}
{501}{}{février}
{502}{}{mars}
{503}{}{avril}
{504}{}{mai}
{505}{}{juin}
{506}{}{juillet}
{507}{}{août}
{508}{}{septembre}
{509}{}{octobre}
{510}{}{novembre}
{511}{}{décembre}
#
#
# Option menu text
#
{600}{}{SAUVEGARDER}
{601}{}{CHARGER}
{602}{}{IMPRIMER}
{603}{}{EFFACER}
{604}{}{VALIDER}
{605}{}{Veux-tu vraiment supprimer} # line 1
{606}{}{ce personnage ?}  # line 2
{607}{}{ a été sauvegardé.}
{608}{}{ a été chargé.}
{609}{}{existe déjà.}
{610}{}{Ecraser la sauvegarde precedente ?}
{611}{}{Erreur à la sauvegarde}
{612}{}{Erreur au chargement}
{613}{}{Fichier personnage incorrect.}
{614}{}{Données personnage incorrectes.}
{615}{}{Erreur à la lecture de la liste de fichiers !}
{616}{}{IMPRIMER}
{617}{}{JOUEUR}
{618}{}{BLANK.GCD}
#
#
# ASCII text file printing text
#
{620}{}{FALLOUT}   # Title line 1
{621}{}{REGISTRE DU PERSONNEL DE L'ABRI 13}    # Title line 2
{622}{}{heures}    # Title line 3
# -
# -
#      Strength: 00        Hit Points: 000/000          Sequence: 00
#    Perception: 00       Armor Class: 000          Healing Rate: 00
#     Endurance: 00     Action Points: 000       Critical Chance: 000%
#      Charisma: 00      Melee Damage: 000          Carry Weight: 000 lbs.
#  Intelligence: 00       Damage Res.: 000%
#       Agility: 00    Radiation Res.: 000%
#          Luck: 00       Poison Res.: 000%
#
{623}{}{ ::: Statistiques :::}
{624}{}{       Force :}
{625}{}{        Points d'impact :}
{626}{}{        Séquence :}
# -
{627}{}{     Perception :}
{628}{}{       Cla. d'armure :}
{629}{}{        Vit. guérison :}
# -
{630}{}{      Endurance :}
{631}{}{     Points d'action :}
{632}{}{      Coups critiques :}
# -
{633}{}{       Charisme :}
{634}{}{      Dégâts en rixe :}
{635}{}{         Charge max. :}
# -
{636}{}{   Intelligence :}
{637}{}{       Rés. dégâts :}
# -
{638}{}{        Agilité :}
{639}{}{    Rés. radiations :}
# -
{640}{}{           Chance :}
{641}{}{       Rés. poison :}
# -
# -
# Name: 01234567890        Age: 00         Gender: Female
{642}{}{  Nom :}
{643}{}{Age :}
{644}{}{               Sexe :}
{645}{}{Masc.}
{646}{}{Fém.}
#-
# Level: 00                 Exp: 000,000    Next Level: 000,000
{647}{}{Niveau :}
{648}{}{                Exp :}
{649}{}{Niveau suivant :}
#-
{650}{}{ ::: Qualités (Traits):::}
{651}{}{ ::: Aptitudes :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: Compétences :::                ::: Victimes :::}
#-
{654}{}{ ::: Inventaire :::}
#-
{655}{}{                                      Charge totale :}
{656}{}{ ::: Dépendances :::}
{657}{}{ ::: Réputation :::}


#
#
# Karma name strings
#
#
{1000}{}{Réputation (générale) }
{1001}{}{Folie Furieuse !}
{1002}{}{Champion}
{1003}{}{Tueur d'enfants}
{1004}{}{Obsédé du Nuka Cola}
{1005}{}{Taré de la gonflette (dépendance au Buffout)}
{1006}{}{Fondu du crâne (dépendance au Mentats)}
{1007}{}{Psychopathe ! (dépendance au Psycho)}
{1008}{}{Rayonnant (dépendance au RadAway)}
{1009}{}{Alcoolique}
{1010}{}{Dépendance au Jet}
{1011}{}{Dépendance au jeu de cartes Tragic}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Bête de sexe}
{1014}{}{Boxeur}
{1015}{}{Gigolo}
{1016}{}{Fossoyeur}
{1017}{}{Membre de la Famille Salvatore}
{1018}{}{Marié(e)}
{1019}{}{Star du porno}
{1020}{}{Esclavagiste}
{1021}{}{Vierge du Désert}
{1022}{}{Membre de la Famille Bishop}
{1023}{}{Membre de la Famille Mordino}
{1024}{}{Membre de la Famille Wright}
{1025}{}{Séparé(e)}
{1026}{}{Fumeur}

#
# Karma description strings
#
{1100}{}{Statistique reflétant ta réputation générale. Plus cette valeur est élevée, plus on te respecte. Si ta réputation est négative, cela signifie que certains te détestent pour tes actions malveillantes.}
{1101}{}{Tu as tué beaucoup de gens. Il est préférable de ne pas t'en vanter. Pourtant cela peut aussi t'attirer les faveurs de certaines personnes malveillantes.}
{1102}{}{Tes actions ont fait de toi un champion. Ta lutte contre le mal et l'infamie est largement reconnue. Cela peut t'attirer les faveurs de personnes honorables.}
{1103}{}{Tu as tué des jeunes gens, des jeunes du désert, ce qui est très mal vu. Tu es un être diabolique.}
{1104}{}{Tu raffoles de Nuka-Cola, le soda du monde post-nucléaire.}
{1105}{}{Tu dois prendre du Buffout régulièrement pour te sentir bien.}
{1106}{}{Tu dois prendre des Mentats régulièrement pour te sentir bien.}
{1107}{}{Si tu n'absorbes pas régulièrement du Psycho, tu souffres. Et si tu souffres, tu fais souffrir les autres.}
{1108}{}{Ton corps est devenu dépendant de l'Anti-Rad. Bien que ta vie ne soit pas en danger, tu dois en prendre régulièrement.}
{1109}{}{Tu as un problème avec la bouteille. Et ton alcoolisme entraîne beaucoup d'autres problèmes.}
{1110}{}{Tu es accro stimulants. Tu dois prendre du Jet régulièrement.}
{1111}{}{C'est tragique, tu es accro au jeu de cartes Tragic. Tu es constamment à la recherche de nouvelles cartes.}
{1112}{}{TEMPORAIRE - Qu'est-ce que c'est que ça ?}
{1113}{}{Le sexe, les préliminaires, ça te connaît. Tu sais donner du plaisir à une personne du sexe opposé de sorte qu'elle en redemande.}
{1114}{}{Tu es le champion de Californie du Nord catégorie poids lourd. Tu as droit à la gloire, au respect, à l'amour des foules... Ainsi qu'un bonus à la résistance et à la compétence Corps à Corps.}
{1115}{}{Soyons francs : tu coucherais avec tout ce qui a deux jambes. Parfois, tu ne te donnes même pas la peine de vérifier.}
{1116}{}{Ils sont morts, ils s'en fichent, non ? Telle est ta devise, à présent. Déterrer les restes des autres est beaucoup plus qu'un passe-temps pour toi.}
{1117}{}{Tu es un Membre de la Famille Salvatore. On te connaît, on te respecte, et le chapeau mou te va à ravir.}
{1118}{}{On t'a passé l'anneau au doigt. Hé c'est ton problème, pas le nôtre.}
{1119}{}{Tu es la nouvelle étoile du sexe, et tes exploits sont connus de tout New Reno.}
{1120}{}{Tout le monde sait que tu es membre de la Guilde des Esclavagistes. Le tatouage sur ton front proclame ton allégeance à la face du monde.}
{1121}{}{Il faut que tu sortes un peu. Tes performances sexuelles sont... bon, avouons-le, médiocres.}
{1122}{}{Tu es un Membre de la Famille Bishop. On te connaît, on te respecte, et le chapeau mou te va à ravir.}
{1123}{}{Tu es un Membre de la Famille Mordino. On te connaît, on te respecte, et le chapeau mou te va à ravir.}
{1124}{}{Tu es un Membre de la Famille Wright. On te connaît, on te respecte, et le chapeau mou te va à ravir.}
{1125}{}{Ta moitié est partie. J'espère que tu es content(e).}
{1126}{}{Tu es un fumeur. Ils disent que ça va te tuer, mais tu n'es pas encore mort. De toute façon, c'est une sacrée bonne manière pour mourir dans un monde post-apocalyptique.}

#
# Town reputations
#
{2000}{}{Idolâtré}
{2001}{}{Aimé}
{2002}{}{Accepté}
{2003}{}{Neutre}
{2004}{}{Antipathie}
{2005}{}{Haï}
{2006}{}{Diffamé}

{2100}{}{Tout le monde dans le coin aimerait te ressembler. La ville entière te fait fête et te considère comme l'exemple à suivre.}
{2101}{}{Les gens te saluent, de la voix et du geste, chaque fois qu'ils te voient en ce lieu. Tout le monde a entendu parler de toi, et en bien.}
{2102}{}{Même si on ne te reçoit pas à bras ouverts, on te gratifie d'un signe de tête quand tu croises quelqu'un dans la rue. Il y a pire, comme traitement.}
{2103}{}{Bien qu'ils se méfient des étrangers, les gens du coin te laissent le bénéfice du doute... pour l'instant.}
{2104}{}{Tu viens d'ailleurs, comme tant d'autres par ici. Et tu ne dois pas valoir grand-chose.}
{2105}{}{Tu as prouvé aux gens du coin que leur défiance initiale à ton égard était justifiée. On te dévisage et on baisse le ton en ta présence. On sait bien que tu n'as rien d'un ange.}
{2106}{}{On te dévisage, on marmonne, on change de trottoir sur ton passage. Il y en a même qui se retournent et qui crachent par terre. Tout le monde sait bien que tu es la pire vermine qu'on ait jamais vue par ici.}

#
# Karma status strings
#
{3000}{}{Sauveur des Damnés}
{3001}{}{Gardien du Désert}
{3002}{}{Bouclier de l'Espoir}
{3003}{}{Défenseur}
{3004}{}{Nomade}
{3005}{}{Traître}
{3006}{}{Epée du Désespoir}
{3007}{}{Fléau du Désert}
{3008}{}{Enfant du Démon}

#
# Karma section titles.
#
{4000}{}{Réputation}
{4001}{}{Dépendances}

#
# Karma section descriptions.
#
{4100}{}{Il s'agit de ta réputation en fonction d'un lieu donné.}
{4101}{}{Tout ce dont tu raffoles (et dépends).}

#
# Special Demo version only text
#
{5000}{}{Imprimer un personnage n'est}   # 1
{5001}{}{possible que dans la version complète.}   # 2
{5002}{}{Sauvegarder un personnage n'est}    # 1
{5003}{}{possible que dans la version complète.}   # 2
{5004}{}{Charger un personnage sauvegardé n'est } # 1
{5005}{}{possible que dans la version complète.}   # 2
{5006}{}{MODE TRICHE}
{5007}{}{Non disponible dans la démo.}
