##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
# (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{Habitant de l'Abri}
{200}{}{Citadin}
{201}{}{Homme portant des vêtements de protection en cuir.}
{300}{}{Citadin}
{301}{}{Homme portant une lourde armure en acier.}
{400}{}{Pauvre type}
{401}{}{Pauvre type pathétique.}
{500}{}{Paysan}
{600}{}{Habitant de l'Abri}
{700}{}{SuperArmure}
{800}{}{Dirigeant de l'Abri}
{900}{}{Super Mutant}
{1000}{}{Gros Rataupe}
{1100}{}{Radscorpion}
{1101}{}{Un scorpion mutant géant.}
{1200}{}{Personne en Robe}
{1300}{}{Marchand}
{1400}{}{Garde Zombie}
{1401}{}{Autrefois, c'était un homme, ou descendait de l'homme. La détérioration des tissus est probablement due à de l'acide ou aux radiations.}
{1500}{}{Femme en armure de combat}
{1600}{}{Rayonnant}
{1601}{}{Cet humanoïde est fortement irradié. Alors qu'il était autrefois humain et civilisé, il est revenu à un mode de vie plus primitif et sauvage.}
{1700}{}{Homme en veste de cuir}
{1800}{}{Paysan}
{1900}{}{Femme en veste de cuir}
{2000}{}{Paysan}
{2100}{}{Homme en armure de combat}
{2200}{}{Citadine}
{2201}{}{Femme portant une belle armure en acier.}
{2300}{}{Lieutenant Super Mutant}
{2400}{}{Ténébreux}
{2500}{}{Citadine}
{2501}{}{Femme humaine portant une armure de protection en cuir.}
{2600}{}{Habitant de l'Abri}
{2700}{}{Garde}
{2800}{}{Brahmine}
{2900}{}{Paysan}
{3000}{}{Paysan}
{3100}{}{Homme en armure de cuir}
{3200}{}{Paysan}
{3300}{}{Citoyen}
{3400}{}{Habitant de l'Abri}
{3500}{}{Habitant de l'Abri}
{3600}{}{Chien}
{3601}{}{Chien, probablement bâtard.}
{3700}{}{Femme}
{3800}{}{Homme}
{3900}{}{Paysan}
{4000}{}{Paysan}
{4100}{}{Personne en SuperArmure}
{4200}{}{Garçon}
{4300}{}{Petit Centaure}
{4400}{}{Mr. Handy}
{4500}{}{Flotteur}
{4600}{}{Scribe}
{4700}{}{Dirigeant}
{4800}{}{Rat des cavernes}
{4900}{}{Gizmo}
{5000}{}{Le Maître}
{5100}{}{Griffemort}
{5101}{}{Beaucoup de mythes et de rumeurs existent sur ces créatures, mais leur véritable origine reste inconnue. Enorme, résistant, rapide.}
{5200}{}{Technicien}
{5300}{}{Technicien}
{5400}{}{Technicien}
{5500}{}{Garde}
{5600}{}{Garde}
{5700}{}{Garde}
{5800}{}{Technicien}
{5900}{}{Citoyen}
{6000}{}{Clochard}
{6100}{}{Travailleur}
{6200}{}{Edudiant de la Cathédrale}
{6300}{}{Tandi}
{6400}{}{Aradesh}
{6500}{}{Seth}
{6600}{}{Marchand}
{6700}{}{Garde}
{6800}{}{Mante}
{6900}{}{Robocerveau}
{7000}{}{Garde Pillard}
{7100}{}{Citoyen}
{7200}{}{Citoyen}
{7300}{}{Conseiller de Garl}
{7400}{}{Citoyen}
{7500}{}{Pillard}
{7600}{}{Ian}
{7700}{}{Oeil flottant MkII}
{7800}{}{Rat-Cochon}
{7900}{}{Killian Darkwater}
{8000}{}{Lars}
{8100}{}{Izo}
{8200}{}{Voyageur}
{8300}{}{Citoyen}
{8400}{}{Citoyen}
{8500}{}{Voyageur}
{8600}{}{Paysan}
{8700}{}{Citoyen}
{8800}{}{Marchand}
{8900}{}{Etranger}
{9000}{}{Garde}
{9100}{}{Fermier}
{9200}{}{Marchand}
{9300}{}{Paysan}
{9400}{}{Neal}
{9500}{}{Paysan}
{9600}{}{Travailleur}
{9700}{}{Marchand}
{9800}{}{Paysan}
{9900}{}{Voyou}
{10000}{}{Etranger}
{10100}{}{Enfant de la Cathédrale}
{10200}{}{Vinnie}
{10300}{}{Voyageur}
{10400}{}{Set}
{10500}{}{Garret}
{10600}{}{Goule}
{10601}{}{Un Goule hautement irradiée. Ses muscles et sa matière cérébrale ont pourri, mais il était autrefois l'habitant d'un abri, comme toi.}
{10700}{}{Garde Ténébreux}
{10800}{}{Super Mutant costaud}
{10900}{}{Garde Goule}
{10901}{}{Cet humanoïde est fortement irradié. Alors qu'il était autrefois humain et civilisé, il est revenu à un mode de vie plus primitif et sauvage.}
{11000}{}{Membre de l'Underground}
{11100}{}{Dan}
{11200}{}{Shérif Greene}
{11300}{}{Député Fry}
{11400}{}{Kane}
{11500}{}{Demetre}
{11600}{}{Keri}
{11700}{}{Rutger}
{11800}{}{Daren Hightower}
{11900}{}{Martha}
{12000}{}{Lorenzo}
{12100}{}{Jacob}
{12200}{}{Canigou}
{12300}{}{Jasmine}
{12400}{}{Troy}
{12500}{}{Darrell}
{12600}{}{Talus}
{12700}{}{Thomas}
{12800}{}{Mathia}
{12900}{}{Razor}
{13000}{}{Tangler}
{13100}{}{Talius}
{13200}{}{Gabriel}
{13300}{}{Avellone}
{13400}{}{VanHagan}
{13500}{}{Surf}
{13600}{}{Lasher}
{13700}{}{Barracus}
{13800}{}{Jérémie}
{13900}{}{Médecin Super Mutant}
{14000}{}{Gidéon}
{14001}{}{Ses mains rayonnent d'une étrange énergie.}
{14100}{}{Dominic}
{14101}{}{Une étrange énergie flamboie dans ses yeux.}
{14200}{}{Lucy}
{14201}{}{Sa tête rayonne d'une étrange énergie.}
{14300}{}{Wiggup}
{14301}{}{De petites étincelles d'énergie flamboient sur son corps.}
{14400}{}{Vicieux}
{14500}{}{Lieutenant Super Mutant}
{14600}{}{Laura}
{14700}{}{Morpheus}
{14800}{}{Nicole}
{14900}{}{Vree}
{15000}{}{Maxson}
{15100}{}{Rhombus}
{15200}{}{Cabbot}
{15300}{}{Decker}
{15400}{}{Butch}
{15500}{}{Loxley}
{15600}{}{Jain}
{15700}{}{Harold}
{15800}{}{Harry}
{15900}{}{Rat robuste}
{16000}{}{Rat irradié}
{16100}{}{Rat robuste irradié}
{16200}{}{Petit Rataupe}
{16300}{}{Coyote}
{16400}{}{Grande Brahmine}
{16500}{}{Progéniture de Griffemort}
{16501}{}{Une version plus petite et plus jeune de ses terrifiants congénères, mais pas moins dangereux.}
{16600}{}{Radscorpion laid}
{16700}{}{Flotteur sanglant}
{16800}{}{Grand Centaure}
{16900}{}{Paysan modeste}
{17000}{}{Paysan}
{17100}{}{Fermier}
{17200}{}{Travailleur}
{17300}{}{Fermier}
{17400}{}{Marchand}
{17500}{}{Garde}
{17600}{}{Grande mante}
{17700}{}{Rat-Cochon féroce}
{17800}{}{Fermier}
{17900}{}{Travailleur}
{18000}{}{Marchand}
{18100}{}{Garde}
{18200}{}{Rayonnant}
{18201}{}{Cet humanoïde est fortement irradié. Autrefois, il était un homme, ou descendait de l'homme. La détérioration des tissus est probablement due à de l'acide ou aux radiations.}
{18300}{}{Rayonnant fou}
{18301}{}{Ce Goule irradié a encore suffisamment de matière cérébrale et de fonction motrice pour pouvoir parler clairement.}
{18400}{}{Zombie}
{18401}{}{Cet humanoïde est fortement irradié. Alors qu'il était autrefois humain et civilisé, il est passé à un mode de vie plus primitif et sauvage.}
{18500}{}{Garde}
{18600}{}{Garde Super Mutant}
{18700}{}{Super Mutant féroce}
{18800}{}{Super Mutant fou}
{18900}{}{Super Mutant meurtrier}
{19000}{}{Ténébreux costaud}
{19100}{}{Ténébreux meurtrier}
{19200}{}{SuperTénébreux}
{19300}{}{Maître-Ténébreux}
{19400}{}{Garde}
{19500}{}{Marchand}
{19600}{}{Garde}
{19700}{}{Garde}
{19800}{}{Garde}
{19900}{}{Fille}
{20000}{}{Scribe}
{20100}{}{Garde}
{20200}{}{Etranger}
{20300}{}{Voyou}
{20400}{}{Mercenaire}
{20500}{}{Garde}
{20600}{}{Habitant de l'Abri}
{20700}{}{Garl}
{20800}{}{Doc Morbide}
{20900}{}{Gretch}
{21000}{}{Tycho}
{21100}{}{Jonathan}
{21200}{}{Jacob}
{21300}{}{Mary}
{21400}{}{Rachael}
{21500}{}{Caleb}
{21600}{}{Voyageur}
{21700}{}{Etranger}
{21800}{}{Voyou}
{21900}{}{Mercenaire}
{22000}{}{Garde}
{22100}{}{Citoyen}
{22200}{}{Etranger}
{22300}{}{Voyou}
{22400}{}{Mercenaire}
{22500}{}{Garde}
{22600}{}{Citoyen}
{22700}{}{Voyageur}
{22800}{}{Etranger}
{22900}{}{Voyou}
{23000}{}{Mercenaire}
{23100}{}{Garde}
{23200}{}{Citoyen}
{23300}{}{Voyageur}
{23400}{}{Mercenaire}
{23500}{}{Garde}
{23600}{}{Voyageur}
{23700}{}{Etranger}
{23800}{}{Voyou}
{23900}{}{Mercenaire}
{24000}{}{Garde}
{24100}{}{Voyou}
{24200}{}{Mercenaire}
{24300}{}{Garde}
{24400}{}{Voyageur}
{24500}{}{Etranger}
{24600}{}{Voyou}
{24700}{}{Mercenaire}
{24800}{}{Garde}
{24900}{}{Voyageur}
{25000}{}{Etranger}
{25100}{}{Voyou}
{25200}{}{Mercenaire}
{25300}{}{Garde}
{25400}{}{Voyageur}
{25500}{}{Etranger}
{25600}{}{Voyou}
{25700}{}{Mercenaire}
{25800}{}{Garde}
{25900}{}{Voyageur}
{26000}{}{Etranger}
{26100}{}{Voyou}
{26200}{}{Mercenaire}
{26300}{}{Garde}
{26400}{}{Chevalier Initié}
{26500}{}{Chevalier Initié Senior}
{26600}{}{Apprenti Chevalier}
{26700}{}{Compagnon Chevalier}
{26800}{}{Chevalier Senior}
{26900}{}{Chevalier Initié}
{27000}{}{Chevalier Initié Senior}
{27100}{}{Apprenti Chevalier}
{27200}{}{Compagnon Chevalier}
{27300}{}{Chevalier Senior}
{27400}{}{Paladin Junior}
{27500}{}{Paladin}
{27600}{}{Paladin Senior}
{27700}{}{Paladin Junior}
{27800}{}{Paladin}
{27900}{}{Paladin Senior}
{28000}{}{Scribe Initié}
{28100}{}{Scribe Initié Senior}
{28200}{}{Apprenti Scribe}
{28300}{}{Compagnon Scribe}
{28400}{}{Scribe Senior}
{28500}{}{Scribe Initié}
{28600}{}{Scribe Initié Senior}
{28700}{}{Apprenti Scribe}
{28800}{}{Compagnon Scribe}
{28900}{}{Scribe Senior}
{29000}{}{Homme en robe}
{29100}{}{Enfant du Maître}
{29200}{}{Etudiant de la Cathédrale}
{29300}{}{Femme en robe}
{29400}{}{Enfant du Maître}
{29500}{}{Animal du Maître}
{29600}{}{Voyou du Maître}
{29700}{}{Garde du Maître}
{29800}{}{Animal du Maître}
{29900}{}{Voyou du Maître}
{30000}{}{Garde du Maître}
{30100}{}{Docteur}
{30200}{}{Katja}
{30300}{}{Sasha}
{30301}{}{Voici un Husky Sibérien attendant patiemment son maître.}
{30400}{}{Mystérieux étranger}
{30500}{}{Goule irresponsable}
{30501}{}{Un Goule hautement irradié. Ses muscles et sa matière cérébrale ont pourri, mais il autrefois l'habitant d'un abri comme toi.}
{30600}{}{Oeil flottant}
{30700}{}{Oeuf}
{30701}{}{Oeuf de Griffemort}
{30800}{}{Dugan}
{30900}{}{Mère Griffemort}
{31000}{}{Hammer}
{31100}{}{Voyageur mort}
{31200}{}{Kenji}
{31300}{}{Mr. Handy C}
{31400}{}{Ian}
{31500}{}{Ian}
{31600}{}{Ian}
{31700}{}{Ian}
{31800}{}{Tycho}
{31900}{}{Tycho}
{32000}{}{Tycho}
{32100}{}{Tycho}
{32200}{}{Katja}
{32300}{}{Katja}
{32400}{}{Katja}
{32500}{}{Katja}
{32600}{}{Canigou}
{32700}{}{Canigou}
{32800}{}{Canigou}
{32900}{}{Canigou}
{33000}{}{Etranger Mystérieux}
{33100}{}{Dr. Buker}
{33200}{}{Radscorpion}
{33201}{}{Un petit scorpion mutant.}
{33300}{}{Plante à Spores}
{33301}{}{Une plante carnivore.}
{33400}{}{Un Robot Sentinelle}
{33500}{}{Gecko}
{33600}{}{Gecko Doré}
{33700}{}{Gecko de Feu}
{33800}{}{Fourmi Géante}
{33900}{}{Chasseur-cueilleur}
{34000}{}{Chasseur-cueilleur}
{34100}{}{Hope}
{34101}{}{Une belle jeune femme dans une belle robe noire.}
{34200}{}{Un bébé Griffemort}
{34300}{}{Chien Sauvage}
{34301}{}{Un chien féroce de race batarde.}
{34400}{}{Roi des Egouts}
{34401}{}{Un énorme rat albinos.}
