#
# Messages for Prototypes
#
# strings
#
{10}{}{<Aucun>}

#
# Material Types
#
{100}{}{Verre}
{101}{}{Métal}
{102}{}{Plastique}
{103}{}{Bois}
{104}{}{Terre}
{105}{}{Pierre}
{106}{}{Ciment}
{107}{}{Cuir}

#
# Item Types
#
{150}{}{Armure}
{151}{}{Conteneur}
{152}{}{Stimulants}
{153}{}{Arme}
{154}{}{Munitions}
{155}{}{Divers}
{156}{}{Clé}

#
#Scenery Types
#
{200}{}{Portail}
{201}{}{Escaliers}
{202}{}{Ascenseur}
{203}{}{Base de l'échelle}
{204}{}{Sommet de l'échelle}
{205}{}{Paysage ordinaire}

#
#Damage Code Types
#
{250}{}{normal_dam}
{251}{}{laser}
{252}{}{feu}
{253}{}{plasma}
{254}{}{électrique}
{255}{}{emp}
{256}{}{explosion}

#
# Caliber Types for weapons
#
{300}{}{Aucun}
{301}{}{Roquette}
{302}{}{Combustible pour lance-flammes}
{303}{}{Cellule énergétique C}
{304}{}{Cellule énergétique D}
{305}{}{.223}
{306}{}{5 mm}
{307}{}{Cal. .40}
{308}{}{10 mm}
{309}{}{Cal. .44}
{310}{}{14 mm}
{311}{}{Calibre 12}
{312}{}{9 mm}
{313}{}{BB}
{314}{}{Cal. .45}
{315}{}{Calibre 2 mm}
{316}{}{4,7 mm, sans douille}
{317}{}{Needler HN}
{318}{}{7,62 mm}

#
# Race Types
#
{350}{}{Caucasien}
{351}{}{Africain}

#
# Body Types
#
{400}{}{Bipède}
{401}{}{Quadrupède}
{402}{}{Robotique}
#
# Kill Types names
#
# Note: These were moved to 1450+ to handle new ones!
{450}{}{Homme(s)}
{451}{}{Femme(s)}
{452}{}{Enfant(s)}
{453}{}{Super Mutant(s}
{454}{}{Goule(s)}
{455}{}{Brahmine(s)}
{456}{}{Radscorpion(s)}
{457}{}{Rat(s)}
{458}{}{Flotteur(s)}
{459}{}{Centaure(s)}
{460}{}{Robot(s)}
{461}{}{Chien(s)}
{462}{}{Mante(s)}
{463}{}{Griffemort(s)}
{464}{}{Plante(s)}
#
# Kill type info descriptions
#
{465}{}{Cette ligne indique le nombre d'hommes humains que tu as tués au cours de tes aventures.}
{466}{}{Cette ligne indique le nombre de femmes humaines que tu as tuées au cours de tes aventures.}
{467}{}{Cette ligne indique le nombre d'enfants humains que tu as tués au cours de tes aventures. Ordure !}
{468}{}{Nombre de Super Mutants que tu as exterminés au cours de tes aventures.}
{469}{}{Cette ligne indique le nombre de Goules (hommes et femmes) que tu as tuées au cours de tes aventures.}
{470}{}{Cette ligne indique le nombre de Brahmines (vaches mutantes) que tu as transformées en côtelettes au cours de tes tribulations.}
{471}{}{Nombre de radscorpions (scorpions mutants) que tu as mis à mort au cours de tes aventures.}
{472}{}{Nombre de rats que tu as tués, tous les membres de la famille des rats compris.}
{473}{}{Il s'agit du nombre de Flotteurs que tu as mis à mort.}
{474}{}{Ton tableau de chasse concernant les Centaures.}
{475}{}{Il s'agit du nombre de robots que tu as détruits ou démantelés.}
{476}{}{Nombre de chiens que tu as envoyés au paradis des animaux.}
{477}{}{Cette ligne indique le nombre total de mantes ou de gros insectes de la famille des mantes que tu as écrasés jusqu'ici.}
{478}{}{Cette ligne indique le nombre total de Griffemorts de tout âge que tu as exterminés.}
{479}{}{Cette ligne indique le nombre de plantes que tu as arrachées à ce monde.}

#
# Use text
#
{480}{}{Tu vois : %s.}

#
# Use Container text
#
{485}{}{Tu explores : %s.}
{486}{}{Tu fermes : %s.}
{487}{}{C'est verrouillé.} #new

#
#Look text
#
{490}{}{Tu vois : %s.}
{491}{}{Tu vois un cadavre : %s.}
{492}{}{Tu vois les restes de : %s.}
{493}{}{Tu ne vois rien d'inhabituel.}

#
#Examine text
#
{500}{}{sans vie}
{501}{}{d'être à l'agonie}
{502}{}{grièvement blessé}
{503}{}{mal en point}
{504}{}{indemne}

#
# Examine text messages
#
{510}{}{Mod. CA : %d}
{511}{}{Mod. RD : %d}
{512}{}{Mod. Dégâts : %d/%d}
{518}{}{Tu as l'air %s }
{519}{}{%s %s }
{520}{}{Tu as l'air %s.}
{521}{}{%s %s.}
{522}{}{Il a l'air %s }
{523}{}{Elle a l'air %s }
{524}{}{L'adversaire a l'air %s }
#(note:  hps are short for hit-points)
{525}{}{%s a %d/%d PI.}
#(note: this is for guns that have ammo)
{526}{}{Capacité : %d/%d coup(s) de %s.}
{530}{}{et a les membres estropiés.}#These append to lines 500-504
{531}{}{mais a les membres estropiés.}
{532}{}{et ont les membres estropiés.}
{533}{}{mais ont les membres estropiés.}
#(note: hps are short for hit-points)
{535}{}{Il a %d/%d PI }
{536}{}{Elle a %d/%d PI }
{537}{}{PI : %d/%d }
{540}{}{Pèse %d livres.}
{541}{}{Pèse %d livre.}
{544}{}{, }
{545}{}{.}
{546}{}{et manie : %s.}
{547}{}{et manie : %s avec %d/%d coups de %s.}
{548}{}{La voiture n'a pas l'air de fonctionner pour l'instant.}
{549}{}{La voiture roule à une puissance de %d%%.}

#
# Examine text error messages
#
{550}{}{\nErreur : lookup_val hors limite !}
{551}{}{\nErreur : obj_examine : Echec de proto_ptr !}

#
# Use text messages
#
{580}{}{Utilisation de : %s.}
{581}{}{Utilisation de : %s sur %s.}
{582}{}{Aucun effet.}
{583}{}{Avec consternation, tu constates que la mort a déjà fait son oeuvre.}
{584}{}{En t'approchant, tu te rends compte que la mort a déjà fait son oeuvre.}
{585}{}{Hélas, tu arrives trop tard.} # This is relating to a critter being dead.
{586}{}{Ca ne marche pas sur les morts.}
{587}{}{Tu allumes la fusée éclairante.}
{588}{}{La fusée éclairante est allumée.}
{589}{}{Tu règles la minuterie.}
{590}{}{La minuterie est déjà lancée !}
{595}{}{Tu recharges la voiture.}
{596}{}{La voiture a déjà fait le plein d'énergie.}
{597}{}{L'entrée semble être bloquée.}

#
# Experience-Point messages
#
{620}{}{Tu gagnes %d points d'expérience pour avoir tué : %s.}
{621}{}{%s, tu gagnes %d points d'exp.}
{622}{}{Pour avoir tenu tes ennemis en échec} # 622-626 prepend to line 621
{623}{}{Pour avoir décimé tes adversaires}
{624}{}{Tu es le vainqueur du combat}
{625}{}{Pour avoir écrasé tes ennemis}
{626}{}{Pour avoir anéanti tes ennemis sans une égratignure}

#
#Dialog messages
#
{650}{}{[Terminé]}
{651}{}{[Suite]}
{652}{}{Suite}
{653}{}{[Retour]}
{654}{}{Retour}#changed number from 653
{655}{}{Continuer}#new
{656}{}{Err...}#new
{660}{}{Impossible de voir par là.}
{661}{}{Trop loin.}
{670}{}{Ok.}    # F2: Used in PM: CombatAI settings
{671}{}{Sûr.}    # F2: Used in PM: CombatAI settings
{672}{}{Comme tu veux.}       # F2: Used in PM: CombatAI settings
{673}{}{Tout ce que tu voudras.}  # F2: Used in PM: CombatAI settings
{674}{}{Je vais essayer.}          # F2: Used in PM: CombatAI settings
{675}{}{Je ne peux pas faire ça.}   # F2: Used in PM: CombatAI settings
{676}{}{Je ne pense pas pouvoir faire ça.}   # F2: Used in PM: CombatAI settings
{677}{}{Arf !}   # F2: Used in PM: CombatAI settings -- RoboDog
{678}{}{Ouah !}  # F2: Used in PM: CombatAI settings -- RoboDog

#
# Not Enough AP message
#
{700}{}{Tu n'as pas assez de points d'action.}
#
#Book messages
#
{800}{}{Tu lis le livre.}
{801}{}{Tu n'apprends rien de nouveau.}
{802}{}{Tu apprends de nouvelles informations scientifiques.}
{803}{}{Tu apprends beaucoup sur la réparation du matériel électronique endommagé.}
{804}{}{Tu apprends de nouvelles méthodes de soins.}
{805}{}{Tu apprends comment mieux manier tes fusils.}
{806}{}{Tu apprends beaucoup sur les techniques de survie en milieu naturel.}
#
#Use on messages (and some extra stuff that Jesse needed)
#
{900}{}{La trousse de médecin est presque vide.}
{901}{}{La trousse de secours est presque vide.}
{902}{}{Impossible en situation de combat.}
{903}{}{Cette personne ne veut pas faire de troc avec toi.}
{904}{}{Cette personne n'a rien à t'apprendre.}
{905}{}{Impossible de ramasser cet objet. Tu es à ta capacité de charge maximale.}
{910}{}{Les fournitures de la trousse du technicien médical s'épuisent.}
{911}{}{Les produits de la trousse de secours du médecin sur le terrain s'épuisent.}
{913}{}{Cette créature ne peut rien transporter.}


#
# Kill Types names
#
{1450}{}{Homme(s)}
{1451}{}{Femme(s)}
{1452}{}{Enfant(s)}
{1453}{}{Super Mutant(s)}
{1454}{}{Goule(s)}
{1455}{}{Brahmine(s)}
{1456}{}{Radscorpion(s)}
{1457}{}{Rat(s)}
{1458}{}{Flotteur(s)}
{1459}{}{Centaure(s)}
{1460}{}{Robot(s)}
{1461}{}{Chien(s)}
{1462}{}{Mante(s)}
{1463}{}{Griffemort(s)}
{1464}{}{Plante(s)}
{1465}{}{Gecko(s)}
{1466}{}{Alien(s)}
{1467}{}{Fourmi(s) géante(s)}
{1468}{}{Gros Méchant Boss}
#
# Kill type info descriptions
#
{1469}{}{Cette ligne indique le nombre d'hommes humains que tu as tués au cours de tes aventures.}
{1470}{}{Cette ligne indique le nombre de femmes humaines que tu as tuées au cours de tes aventures.}
{1471}{}{Cette ligne indique le nombre d'enfants humains que tu as tués au cours de tes aventures. Ordure !}
{1472}{}{Nombre de Super Mutants que tu as exterminés au cours de tes aventures.}
{1473}{}{Cette ligne indique le nombre de Goules (hommes et femmes) que tu as tuées au cours de tes aventures.}
{1474}{}{Cette ligne indique le nombre de Brahmines (vaches mutantes) que tu as transformées en côtelettes au cours de tes tribulations.}
{1475}{}{Nombre de radscorpions (scorpions mutants) que tu as mis à mort au cours de tes aventures.}
{1476}{}{Nombre de rats que tu as tués, tous les membres de la famille des rats compris.}
{1477}{}{Il s'agit du nombre de Flotteurs que tu as mis à mort.}
{1478}{}{Ton tableau de chasse concernant les Centaures.}
{1479}{}{Il s'agit du nombre de robots que tu as détruits ou démantelés.}
{1480}{}{Nombre de chiens que tu as envoyés au paradis des animaux.}
{1481}{}{Cette ligne indique le nombre total de mantes ou de gros insectes de la famille des mantes que tu as écrasés jusqu'ici.}
{1482}{}{Cette ligne indique le nombre total de Griffemorts de tout âge que tu as exterminés.}
{1483}{}{Cette ligne indique le nombre de plantes que tu as arrachées à ce monde.}
{1484}{}{Le nombre de jolis lézards que tu as exterminés.}
{1485}{}{Le nombre de créatures d'un autre monde que tu as détruites.}
{1486}{}{Le nombre de créatures à l'apparence d'insecte que tu as exterminées dans le désert.}
{1487}{}{Le nombre de gardes du corps cyborgs maniaques issus du génie génétique que tu as refroidis.}