#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Vault 13 Quests
#
{100}{}{Trouver la puce d'eau.} 				#fo1 vanilla
{101}{}{Calmer la faction rebelle.}				#fo1 vanilla
{102}{}{Trouver le voleur d'eau.}				#fo1 vanilla
{103}{}{Détruire le chef des Mutants.}			#fo1 vanilla
{104}{}{Détruire la source des Mutants.}		#fo1 vanilla
{105}{}{Aider le docteur à fabriquer de l'Antidote.}
{106}{}{Trouver des indices sur le monde extérieur dans les ordinateurs de la bibliothèque.}
{107}{}{Obtenir l'accès à l'Armurerie.}
{108}{}{Obtenir l'accès à l'Abri.}
{109}{}{Tuer le Superviseur.}
{110}{}{Tuer tous les habitants de l'Abri 13.}
{120}{}{Trouver la puce d'eau.}
{130}{}{RESERVED}
{140}{}{RESERVED}
#
# Vault 15 Quests
#
{200}{}{Rechercher des indices et des informations.}
{201}{}{Rechercher une puce d'eau.}
{202}{}{Trouver un moyen d'accès par la cage d'ascenceur.}
{203}{}{Trouver les objets cachés.}
{204}{}{Tuer tous les rats.}
{205}{}{RESERVED}
{206}{}{RESERVED}
{207}{}{RESERVED}
{208}{}{RESERVED}
{209}{}{RESERVED}
{210}{}{RESERVED}

#
# Shady Sands Quests
#
{300}{}{Parler à Katrina.}
{301}{}{Recruter Ian.}
{302}{}{Arrêter les radscorpions.}									#fo1 vanilla
{303}{}{Aide Razlo à trouver un antidote au venin de radscorpion.}	#fo1 vanilla
{304}{}{Guérir Jarvis du poison de radscorpion.}					#fo1 vanilla
{305}{}{Sauver Tandi des Pillards.}									#fo1 vanilla
{306}{}{Aider les Sables Ombragés à améliorer leur récoltes.}
{307}{}{Mener Seth et les gardes pour détruire les Khans.}

#
# Junktown Quests
#
{400}{}{Aider Saul.}									#fo1 vanilla
{401}{}{Tuer Killian.}									#fo1 vanilla
{402}{}{Sauver Cynthia.}								#fo1 vanilla
{403}{}{Sauver Trish.}									#fo1 vanilla
{404}{}{Arrêter Gizmo.}									#fo1 vanilla
{405}{}{Démanteler le gang des Skulz.}					#fo1 vanilla
{406}{}{Rejoindre les Skulz.}
{407}{}{Voler l'urne de Neal au Skum Pitt.}
{408}{}{RESERVED}

#
# Raiders Quests
#
{500}{}{Rejoindre les Khans.}
{501}{}{Detruire les Khans.}
{502}{}{Tuer les esclaves.}
{503}{}{Sauver les esclaves.}
{504}{}{Couvrir de honte Garl en le battant à main nues.}
{505}{}{Libérer le prisonnier.}
{506}{}{Libérer Tandi.}
{507}{}{Participer au raid des Sables Ombragés avec les Khans.}
{508}{}{Malmener les esclaves.}
{509}{}{Remplacer Garl en tant que leader des Khans.}

#
# Necropolis Quests
#
{600}{}{Détruire les Super Mutants au réservoir.}
{601}{}{Réparez la pompe à eau de Nécropolis.}
{602}{}{Sauver le prisonier.}
{603}{}{Recupérer la puce d'eau.}
{604}{}{Permettre aux Super Mutants du réservoir de partir pacifiquement.}
{605}{}{Séduire Harry.}
{606}{}{Obtenir la récompense de Set pour vous être débarrassés des Super Mutants.}
{607}{}{S'infiltrer dans le bâtiment de Set.}
{608}{}{Entrer à l'intérieur du réservoir.}

#
# The Hub Quests
#
{700}{}{Trouver et éliminer le Griffemort.}			#fo1 vanilla
{701}{}{Liquider Jain.}								#fo1 vanilla
{702}{}{Liquider le marchand.}						#fo1 vanilla
{703}{}{Rechercher les caravanes disparues.}		#fo1 vanilla
{704}{}{Voler le collier aux Marchands.}			#fo1 vanilla
{705}{}{Rejoindre le Cercle des Voleurs.}
{706}{}{Se débarrasser de Decker.}
{707}{}{Envoyer l'eau à l'Abri 13.}
{708}{}{Devenir un garde des Marchands d'eau.}
{709}{}{Devenir un garde des Marchands du Lointain.}
{710}{}{Devenir un garde de la Caravane Ecarlate.}
{711}{}{Se débarraser des pillards à la Ferme d'Irwin.}

#
# Brotherhood of Steel Quests
#
{800}{}{Devenir un Initié.}						#fo1 vanilla
{801}{}{Sauver l'Initié du Centre.}				#fo1 vanilla
{802}{}{Devenir un Chevalier.}
{803}{}{Fouiller dans les ordinateurs de la bibliothèque.}
{804}{}{Recevoir les ordres de Lorri.}
{805}{}{Seduire Jennifer.}
{806}{}{Seduire Lorri.}
{807}{}{Voler le Motivateur Systolique.}
{808}{}{Aider Sophia et Michael.}
{809}{}{Accéder à l'Armurerie.}
{810}{}{Trouver les Ruines de l'Ancien Ordre.}
{811}{}{Explorer la zone du Nord.}
{812}{}{Obtenir de l'aide de la Confrérie à la Base Militaire.}
{813}{}{RESERVED}
{814}{}{RESERVED}
{815}{}{RESERVED}
{816}{}{RESERVED}
{817}{}{RESERVED}
{818}{}{RESERVED}

#
# Military Base Quests
#
{900}{}{Obtenir l'accès à la base.}
{901}{}{Obtenir l'accès à la base sans se faire repérer.}
{902}{}{Pousser les Mutants à quitter leur poste de garde.}
{903}{}{Désactiver les champs de force.}
{904}{}{Tuer le Lieutenant.}
{905}{}{Détruire les Cuves.}

#
# The Glow Quests
#
{1000}{}{Obtenir l'accès au Rayon.}
{1001}{}{Désarmer les pièges de l'installation.}#fo1 vanilla
{1002}{}{Restaurer le courant au Rayon.}		#fo1 vanilla

#
# L.A. Boneyard / Adytum Quests
#
{1100}{}{Devenir un membre des Blade.}										#fo1 vanilla
{1101}{}{Apporter le pendentif à Romero.}									#fo1 vanilla
{1102}{}{Livrer le colis des Contrebandiers.}								#fo1 vanilla
{1103}{}{Rechercher l'Enfant de la Cathédrale espion parmi les Disciples.}	#fo1 vanilla
{1104}{}{Réparer les fermes hydroponiques dans le Sanctuaire.}				#fo1 vanilla
{1105}{}{Sauver Jason Zimmerman.}											#fo1 vanilla
{1106}{}{Empêcher les gangs d'attaquer le Sanctuaire.}						#fo1 vanilla
{1107}{}{Tuer la Mère Griffemort.}
{1108}{}{Convaincre les Contrebandiers d'approvisionner les Blades.}
{1109}{}{RESERVED}
{1110}{}{RESERVED}
{1111}{}{RESERVED}

#
# Cathedral / Master's Vault Quests
#
{1200}{}{Accéder à l'Abri du Maître.}
{1201}{}{Convaincre Rae de te rejoindre contre le Maitre.}
{1202}{}{Tuer Morpheus.}
{1203}{}{Tuer le Maitre.}
{1204}{}{Enclencher le compte à rebourd de la bombe.}

#
# Caravan Run Quests
#
{1300}{}{Aider à décharger la Caravane.}

#
# 
#
{1400}{}{RESERVED}
{1401}{}{RESERVED}
{1402}{}{RESERVED}
{1403}{}{RESERVED}

#
# 
#
{1500}{}{RESERVED}
{1501}{}{RESERVED}
{1502}{}{RESERVED}
{1503}{}{RESERVED}
{1504}{}{RESERVED}
{1505}{}{RESERVED}
{1506}{}{RESERVED}
{1507}{}{RESERVED}
{1508}{}{RESERVED}
{1509}{}{RESERVED}
{1510}{}{RESERVED}
{1511}{}{RESERVED}
{1512}{}{RESERVED}
{1513}{}{RESERVED}
{1514}{}{RESERVED}
{1515}{}{RESERVED}
{1516}{}{RESERVED}

#
# 
#
{1600}{}{RESERVED}
{1601}{}{RESERVED}
{1602}{}{RESERVED}

#
# 
#
{1700}{}{RESERVED}

#
# 
#
{1800}{}{RESERVED}

#
# 
#
{1900}{}{RESERVED}

#
# 
#
{2000}{}{RESERVED}

#
# 
#
{2100}{}{RESERVED}

#
# 
#
{2200}{}{RESERVED}

#
# 
#
{2300}{}{RESERVED}

#
# 
#
{2400}{}{RESERVED}

#
# 
#
{2500}{}{RESERVED}

#
# 
#
{2600}{}{RESERVED}

#
# Desert Encounter Quests
#
{2700}{}{RESERVED}

#
# Mountain Encounter Quests
#
{2800}{}{RESERVED}

#
# Ruined City Encounter Quests
#
{2900}{}{RESERVED}

#
# Coast Encounter Quests
#
{3000}{}{RESERVED}

#
# 
#
{3100}{}{RESERVED}

#
# 
#
{3200}{}{RESERVED}
{3201}{}{RESERVED}
{3202}{}{RESERVED}
{3203}{}{RESERVED}

