#
#   Messages from skilldex.c
#
{100}{}{ATOUTS}
{101}{}{ANNULER}
{102}{}{INFILTR.}
{103}{}{CROCH.}
{104}{}{VOLEUR}
{105}{}{PIEGES}
{106}{}{SECOUR.}
{107}{}{MEDECINE}
{108}{}{SCIENCE}
{109}{}{REPAR.}
