#ifndef TEAMS_H
#define TEAMS_H

/*******************************************************************************
                                Номера команд
*******************************************************************************/

#define TEAM_PLAYER						(0)
#define TEAM_VAULT13					(1)
#define TEAM_SHADY_SANDS				(2)
//#define TEAM_							(3)
//#define TEAM_							(4)
#define TEAM_RADSCORPIONS				(5)
#define TEAM_RAIDERS					(6)
#define TEAM_RATS						(9)
#define TEAM_JUNKTOWN_GUARD				(12)
#define TEAM_JUNKTOWN_GIZMO				(13)
#define TEAM_JUNKTOWN_SKULZ				(14)
#define TEAM_JUNKTOWNER					(16)
#define TEAM_JUNKTOWN_RAIDER			(18)
#define TEAM_JUNKTOWN_MORBID			(19)
#define TEAM_CATHEDRAL					(20)
#define TEAM_NECROPOLIS_GANGER			(30)
#define TEAM_NECROPOLIS_UNDERGROUND		(31)
//#define TEAM_NECROPOLIS_MINDLESS		(32)
//#define TEAM_PLACE_HOLDER				(33)
#define TEAM_NECROPOLIS_MUTANT			(34)
#define TEAM_HUB_WATER_MERCHANTS		(35)
#define TEAM_HUB_FAR_GO_TRADERS			(36)
#define TEAM_HUB_CRIMSON_CARAVANS		(37)
#define TEAM_HUB_UNDERGROUND			(38)
#define TEAM_HUB_THIEVES_CIRCLE			(39)
#define TEAM_HUB_POLICE					(40)
#define TEAM_HUB_SKAG					(41)
#define TEAM_BROTHERHOOD				(44)
#define TEAM_LA_FOLLOWERS				(46)
#define TEAM_LA_BLADES					(47)
#define TEAM_LA_GUN_RUNNERS				(48)
#define TEAM_LA_ADYTOWNER				(49)
#define TEAM_MASTER_LAIR				(55)
#define TEAM_DAN_THE_BRAHMIN_MAN		(62)
#define TEAM_HUB_CARTS_GUARD			(64)
#define TEAM_HUB_FARMER					(65)
#define TEAM_HUB_CATHEDRAL				(72)
#define TEAM_HUB_FLC					(73)
#define TEAM_HUB_VANCE					(81)
#define TEAM_LA_REGULATORS				(89)

#endif // TEAMS_H
