/*

	The Glow Special Forces Operations terminal

      !CUT CONTENT - UNUSED!

*/

/* Include Files */
#include "..\headers\define.h"
#include "..\headers\glow.h"

#define NAME                    SCRIPT_SENTRYGN

#include "..\headers\command.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;
procedure spatial_p_proc;
procedure timed_event_p_proc;

variable LVar0 := 0;
variable LVar1 := 0;

procedure start begin
end

procedure map_enter_p_proc begin
end

procedure spatial_p_proc begin
	if ((local_var(0) == 0) and ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj))) then begin
		display_msg(mstr(100));
		set_local_var(0, 1);
	end
	if ((local_var(1) == 0) and ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) and glow_power_online and glow_traps_active) then begin
		display_msg(mstr(101));
		set_local_var(1, 1);
		add_timer_event(self_obj, game_ticks(7), 1);
	end
end

procedure timed_event_p_proc begin
	LVar0 := random(1, 6) + 2;
	LVar1 := do_check( source_obj, STAT_ag, 0 );

	if (is_success(LVar1)) then begin
		if (is_critical(LVar1)) then begin
			if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
				display_msg(mstr(102));
			end
		end
		else begin
			if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
				display_msg(mstr(103));
			end
			critter_dmg( source_obj, LVar0, DMG_normal_dam );
			display_msg(mstr(104) + LVar0 + mstr(105));
		end
	end
	else begin
		if (is_critical(LVar1)) then begin
			if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
				display_msg(mstr(106));
			end
			critter_dmg( source_obj, LVar0, DMG_normal_dam );
			display_msg(mstr(107) + LVar0 + mstr(108));
		end
		else begin
			if ((source_obj == dude_obj) or (obj_type(source_obj) == dude_obj)) then begin
				display_msg(mstr(109));
			end
			critter_dmg( source_obj, LVar0, DMG_normal_dam );
			display_msg(mstr(110) + LVar0 + mstr(111));
		end
	end
	set_local_var(1, 0);
end
