#include "..\headers\define.h"

procedure start;
procedure MsgCheck;
// lvar0 == alreadyhave
//lvar1 == haveitem description

procedure start
begin
	call MsgCheck;
	if ((script_action == 21) or (script_action == 3)) then begin// 21 is look_at, 3 is description (Binoculars)   //NEED TO FIX THIS, DUPLICATE DESCRIPTIONS IS BULLSHIT. --Sduibek
		script_overrides;
		call MsgCheck;
		display_msg(message_str(SCRIPT_ARTIFACT, 105));
	end
	else begin
		if (script_action == 6) then begin//use_p_proc - Use, Activate, or Manipulate the Object or Item
			script_overrides;
			call MsgCheck;
			if (local_var(0) == 1) then begin
				display_msg(message_str(SCRIPT_ARTIFACT, 101));
			end
			else begin
				set_local_var(0, 1);
				display_msg(message_str(SCRIPT_ARTIFACT, 102));
				set_global_var( GVAR_HOLODISK_BROTHER_HISTORY, 1 );
				display_msg(message_str(SCRIPT_GENCHAT, 103) + "100" + message_str(SCRIPT_GENCHAT, 104));
				give_exp_points(100);
			end
		end
	end
end

procedure MsgCheck
begin
	if not(local_var(1)) then begin
		set_local_var(1, 1);
		////display_msg("INIT_BROHIST.SSL - please tell Sduibek when and where you saw this message. Thank you!");
		debug_msg("INIT_BROHIST.SSL - please tell Sduibek when and where you saw this message. Thank you!");
	end
end


