/*

   Military Base - Force Field

   UNUSED

*/

#include "..\headers\define.h"
#include "..\headers\mbase.h"

#define NAME                    SCRIPT_EMITER1D

#include "..\headers\command.h"

procedure start;
procedure damage_p_proc;

#define ACTIVE       (0)
#define DESTROYED    (1)

#define LVAR_FF_Status        (0)

procedure start begin
end

procedure damage_p_proc begin
end
