/*

   Mariposa, Lou guard?

*/

/* Include Files */
#include "define.h"
//#include "necropolis.h"

#define NAME                    SCRIPT_LTGUARD
#define TOWN_REP_VAR            (GVAR_TOWN_REP_MBASE)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure map_enter_p_proc;

variable tmp_hostile;

procedure start begin
end

procedure critter_p_proc begin
   if (tile_distance_objs(self_obj, dude_obj) < 6) then begin
      tmp_hostile := 1;
   end
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure map_enter_p_proc begin
   set_self_team(TEAM_NECROPOLIS_MUTANT);
   set_self_ai(AI_SUPER_MUTANT_AGGRESSIVE);
end
