/*

   Hub - Fry, the police guy in Decker's lair

*/

/* Include Files */
#include "define.h"
#include "maps/hubdwntn.h"

#define NAME                    SCRIPT_FRYSTUB
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */

procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;

variable tmp_hostile;
variable Only_Once := 1;

import variable Fry_Stub_Ptr;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      Fry_Stub_Ptr := self_obj;
      if not(is_loading_game) then set_self_invisible;
      set_self_team(TEAM_PLAYER);
      set_self_ai(AI_HUB_POLICE);
   end
end

procedure combat begin
   tmp_hostile := 1;
end

procedure critter_p_proc begin
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure pickup_p_proc begin
   if source_is_dude then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   dude_look_at_self;
   get_reaction
   float_msg(self_obj, mstr(101), FLOAT_MSG_RED);
end

procedure destroy_p_proc begin
   set_global_var(GVAR_FRY_DEAD, 1);
   inc_good_critter
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure combat_p_proc begin
   if (map_var(MVAR_UNDERGROUND_SURRENDERED) == 1) then begin
      script_overrides;
   end
end

procedure damage_p_proc begin
   if source_is_dude then begin
      if (map_var(MVAR_COPS_IN_HIDEOUT) == 0) then begin
         set_global_var(GVAR_ENEMY_HUB, 1);
      end
   end
end
