/*

   Hub - Caravan

*/

/* Include Files */
#include "..\headers\define.h"
//#include "..\headers\necropolis.h"

#define NAME                    SCRIPT_HGENCVAN
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "..\headers\command.h"
#include "..\headers\modreact.h"

/* Standard Script Procedures */

procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc;
procedure damage_p_proc;

procedure CaravanMorning;
procedure CaravanEvening;
procedure CaravanNight;
procedure SendToWork;
procedure SendToSleep;
procedure WakeUpCall;

variable tmp_hostile;
variable Only_Once := 1;
variable SetDayNight;
variable Sleeping;
variable LastMove;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      set_self_team(TEAM_HUB_CARTS_GUARD);
      set_self_ai(AI_MERCHANT);
      call SendToWork;
   end
end

procedure combat
begin
   tmp_hostile := 1;
end

procedure critter_p_proc
begin
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure pickup_p_proc
begin
   if (source_obj == dude_obj) then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   dude_look_at_self;
   get_reaction
   if ((game_time_hour >= 2200) or (game_time_hour < 600)) then begin
      call CaravanNight;
   end
   else if (game_time_hour >= 1400) then begin
      call CaravanEvening;
   end
   else if (game_time_hour >= 600) then begin
      call CaravanMorning;
   end
end

procedure destroy_p_proc
begin
   rm_timer_event(self_obj);

   inc_good_critter
   rm_timer_event(self_obj);
end

procedure look_at_p_proc
begin
   script_overrides;
   display_msg(mstr(501));
end

procedure timed_event_p_proc
begin
   if (morning or (day)) then begin
      call SendToWork;
   end
end

procedure damage_p_proc
begin
   if (source_obj == dude_obj) then begin
      set_global_var(GVAR_ENEMY_HUB, 1);
   end
end

procedure CaravanMorning begin
   script_overrides;
   float_msg(self_obj, mstr(random(101, 111)), FLOAT_MSG_RED);
end

procedure CaravanEvening begin
   script_overrides;
   float_msg(self_obj, mstr(random(112, 122)), FLOAT_MSG_RED);
end

procedure CaravanNight begin
   variable LVar0 := 0;
   LVar0 := random(1, 3);
   if (LVar0 == 1) then begin
      float_msg(self_obj, mstr(random(201, 202)), FLOAT_MSG_RED);
   end
   if (LVar0 == 2) then begin
      float_msg(self_obj, mstr(random(123, 126)), FLOAT_MSG_RED);
   end
   if (LVar0 == 3) then begin
      float_msg(self_obj, mstr(401), FLOAT_MSG_RED);
   end
end

procedure SendToWork begin
   variable LVar0 := 0;
   variable LVar1 := 0;
   LVar0 := 0;
   LVar1 := random(10, 30);
   while(LVar0 == 0) do begin
      LVar0 := random(1, 12);
      if (LVar0 == 1) then begin
         LVar0 := 10518;
      end
      else if (LVar0 == 2) then begin
         LVar0 := 11117;
      end
      else if (LVar0 == 3) then begin
         LVar0 := 11115;
      end
      else if (LVar0 == 4) then begin
         LVar0 := 10913;
      end
      else if (LVar0 == 5) then begin
         LVar0 := 10711;
      end
      else if (LVar0 == 6) then begin
         LVar0 := 10313;
      end
      else if (LVar0 == 7) then begin
         LVar0 := 10115;
      end
      else if (LVar0 == 8) then begin
         LVar0 := 9913;
      end
      else if (LVar0 == 9) then begin
         LVar0 := 10111;
      end
      else if (LVar0 == 10) then begin
         LVar0 := 9918;
      end
      else if (LVar0 == 11) then begin
         LVar0 := 11317;
      end
      else if (LVar0 == 12) then begin
         LVar0 := 11111;
      end
      if (LVar0 == LastMove) then begin
         LVar0 := 0;
      end
   end
   LastMove := LVar0;
   reg_anim_clear(self_obj);
   reg_anim_begin();
   reg_anim_obj_move_to_tile(self_obj, LVar0, -1);
   reg_anim_end();
   add_timer_event(self_obj, game_ticks(LVar1), 1);
end

procedure SendToSleep begin
   if (Sleeping == 0) then begin
      Sleeping := 1;
      if ((SetDayNight == 1) and (random(0, 100) >= 80)) then begin
         float_msg(self_obj, mstr(123), FLOAT_MSG_RED);
      end
      SetDayNight := 0;
   end
end

procedure WakeUpCall begin
   if (SetDayNight == 0) then begin
      SetDayNight := 1;
      if not(is_loading_game) then begin    set_self_visible;    end//  MAKE VISIBLE
      add_timer_event(self_obj, game_ticks(1), 1);
      if ((Sleeping == 1) and (random(0, 100) >= 80)) then begin
         float_msg(self_obj, mstr(125), FLOAT_MSG_RED);
      end
      Sleeping := 0;
   end
end
