/*

   Hub - Rutger

*/

/* Include Files */
#include "define.h"
#include "maps/hubdwntn.h"

#define NAME                    SCRIPT_RUTGER
#define TOWN_REP_VAR            (GVAR_TOWN_REP_HUB)

#include "command.h"
#include "modreact.h"

/* Standard Script Procedures */
procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure damage_p_proc;
procedure look_at_p_proc;

procedure Rutger00;
procedure Rutger00a;
procedure Rutger00b;
procedure Rutger01;
procedure Rutger02;
procedure Rutger03;
procedure Rutger04;
procedure Rutger05;
procedure Rutger06;
procedure Rutger07;
procedure Rutger08;
procedure Rutger09;
procedure Rutger10;
procedure Rutger11;
procedure Rutger11a;
procedure Rutger12;
procedure Rutger13;
procedure Rutger14;
procedure Rutger15;
procedure Rutger16;
procedure Rutger17;
procedure Rutger17a;
procedure Rutger18;
procedure Rutger19;
procedure Rutger20;
procedure Rutger21;
procedure Rutger22;
procedure Rutger22a;
procedure Rutger23;
procedure Rutger24;
procedure Rutger25;
procedure Rutger26;
procedure Rutger27;
procedure Rutger28;
procedure Rutger29;
procedure Rutger29a;
procedure Rutger29b;
procedure Rutger30;
procedure Rutger31;
procedure Rutger32;
procedure Rutger33;
procedure Rutger34;
procedure Rutger35;
procedure Rutger36;
procedure Rutger37;
procedure Rutger38;
procedure Rutger39;
procedure Rutger39a;
procedure Rutger40;
procedure Rutger40a;
procedure Rutger40b;
procedure Rutger41;
procedure Rutger42;
procedure Rutger43;
procedure Rutger44;
procedure Rutger45;
procedure Rutger46;
procedure Rutger47;
procedure Rutger48;
procedure Rutger49;
procedure Rutger50;
procedure Rutger51;
procedure Rutger52;
procedure Rutger53;
procedure Rutger54;
procedure Rutger55;
procedure Rutger55a;
procedure Rutger56;
procedure Rutger56a;
procedure Rutger57;
procedure Rutger58;
procedure Rutger59;
procedure Rutger60;
procedure Rutger61;
procedure Rutger62;
procedure Rutger63;
procedure Rutger64;
procedure Rutger65;
procedure Rutger67;
procedure Rutger68;
procedure Rutger69;
procedure Rutger70;
procedure Rutger71;
procedure Rutger72;
procedure Rutger73;
procedure Rutger74;
procedure Rutger75;
procedure Rutger76;
procedure RutgerEnd;
procedure RutgerEndBad;
procedure RutgerAbandoned;
procedure RutgerLost;

variable tmp_hostile;
variable Only_Once := 1;

procedure start begin
   if Only_Once then begin
      Only_Once := 0;
      set_self_team(TEAM_HUB_FAR_GO_TRADERS);
      set_self_ai(AI_GUARD_HUMOROUS);
   end
end

procedure combat begin
   tmp_hostile := 1;
end

procedure critter_p_proc begin
   if (tmp_hostile) then begin
      tmp_hostile := 0;
      attack(dude_obj);
   end
end

procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
      tmp_hostile := 1;
   end
end

procedure talk_p_proc begin
   set_tma_data_generic(TMA_MSG_HUBDWNTN);

   dude_look_at_self;
   get_reaction
   if (dude_iq < 4) then begin
      float_msg(dude_obj, mstr(314), FLOAT_MSG_GREEN);
      float_msg(self_obj, mstr(315), FLOAT_MSG_RED);
   end
   else if (cathedral_destroyed and not(military_base_destoryed) and (local_var(8) == 0)) then begin
      set_local_var(8, 1);
      set_local_var(4, 1);
      start_dialog_at_node(Rutger55);
   end
   else if not(cathedral_destroyed) and military_base_destoryed and (local_var(8) == 0) then begin
      set_local_var(8, 1);
      set_local_var(4, 1);
      start_dialog_at_node(Rutger58);
   end
   else if ((map_var(MVAR_FGT_HOSTILE) == 1) or (map_var(35) == 1)) then begin
      set_local_var(4, 1);
      start_dialog_at_node(Rutger74);
   end
   else if (local_var(4) == 0) then begin
      set_local_var(4, 1);
      start_dialog_at_node(Rutger00);
   end
   else if (map_var(MVAR_SENT_TO_BUTCH) == 0) then begin
      if (local_var(1) >= 2) then begin
         start_dialog_at_node(Rutger73);
      end
      else begin
         start_dialog_at_node(Rutger74);
      end
   end
   else if ((map_var(MVAR_SENT_TO_BUTCH) == 1) and (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 0)) then begin
      call Rutger21;
   end
   else if (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 3) then begin
      start_dialog_at_node(Rutger54);
   end
   else if (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 4) then begin
      start_dialog_at_node(Rutger56);
   end
   else if (local_var(6) == 0) then begin
      if (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 2) then begin
         start_dialog_at_node(Rutger17);
      end
      else if (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 1) then begin
         start_dialog_at_node(Rutger25);
      end
      else if (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 0) then begin
         call Rutger21;
      end
   end
   else if ((local_var(6) == 1) and (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) == 1)) then begin
      start_dialog_at_node(Rutger22);
   end
end

procedure destroy_p_proc begin
   inc_good_critter
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
      set_global_var(GVAR_ENEMY_HUB, 1);
   end
end

procedure look_at_p_proc begin
   script_overrides;
   display_msg(mstr(100));
end

procedure Rutger00 begin
   Reply(101);
   if (global_var(GVAR_QUEST_VAULT13_4_WATERCHIP) != 2) then begin
      NOption(102, Rutger03, 4);
   end
   if (map_var(43) == 1) then begin
      NOption(103, Rutger00a, 4);
   end
   else begin
      NOption(104, Rutger00a, 4);
   end
   NOption(105, Rutger07, 4);
   NOption(106, RutgerEnd, 4);
   NLowOption(107, Rutger00b);
end

procedure Rutger00a begin
   if (has_rep_berserker) then begin
      call Rutger10;
   end
   else if has_rep_childkiller then begin
      call Rutger11;
   end
   else if (has_rep_champion) then begin
      call Rutger15;
   end
   else if ((map_var(35) == 1) or (map_var(MVAR_FGT_HOSTILE) == 1)) then begin
      call Rutger75;
   end
   else begin
      call Rutger16;
   end
end

procedure Rutger00b begin
   if (dude_strength <= 6) then begin
      call Rutger01;
   end
   else begin
      call Rutger02;
   end
end

procedure Rutger01 begin
   BMessage(108);
end

procedure Rutger02 begin
   NMessage(109);
end

procedure Rutger03 begin
   Reply(110);
   if (global_var(GVAR_WORLDMAPLIST_JUNKTOWN) > 0) then begin
      NOption(111, Rutger04, 4);
   end
   else begin
      NOption(112, Rutger04, 4);
   end
   NOption(113, RutgerEnd, 4);
end

procedure Rutger04 begin
   Reply(114);
   NOption(115, Rutger05, 4);
   if (map_var(43) == 1) then begin
      NOption(116, Rutger00a, 4);
   end
   else begin
      NOption(117, Rutger00a, 4);
   end
   NOption(118, RutgerEnd, 4);
end

procedure Rutger05 begin
   Reply(119);
   NOption(120, Rutger06, 4);
   NOption(121, RutgerEnd, 4);
end

procedure Rutger06 begin
   Reply(122);
   NOption(123, Rutger07, 4);
   NOption(124, RutgerEnd, 4);
end

procedure Rutger07 begin
   if (local_var(5) == 0) then begin
      set_local_var(5, 1);
      Reply(125);
   end
   else begin
      Reply(126);
   end
   NOption(127, Rutger08, 4);
   NOption(128, RutgerEnd, 4);
   if (map_var(43) == 1) then begin
      NOption(129, Rutger00a, 4);
   end
   else begin
      NOption(130, Rutger00a, 4);
   end
end

procedure Rutger08 begin
   Reply(131);
   NOption(132, Rutger09, 4);
   NOption(133, RutgerEnd, 4);
end

procedure Rutger09 begin
   Reply(134);
   NOption(135, RutgerEndBad, 4);
   NOption(136, RutgerEnd, 4);
   if (map_var(43) == 1) then begin
      NOption(129, Rutger00a, 4);
   end
   else begin
      NOption(130, Rutger00a, 4);
   end
end

procedure Rutger10 begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   NMessage(139);
end

procedure Rutger11 begin
   Reply(140);
   NOption(141, Rutger11a, 4);
   NOption(142, Rutger14, 4);
end

procedure Rutger11a begin
   if (is_success(do_check(dude_obj, STAT_ch, -1))) then begin
      call Rutger12;
   end
   else begin
      call Rutger13;
   end
end

procedure Rutger12 begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   NMessage(143);
end

procedure Rutger13 begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   if (dude_is_male) then begin
      BMessage(144);
   end
   else begin
      BMessage(145);
   end
end

procedure Rutger14 begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   NMessage(146);
end

procedure Rutger15 begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   NMessage(147);
end

procedure Rutger16
begin
   set_map_var(MVAR_SENT_TO_BUTCH, 1);
   NMessage(148);
end

procedure Rutger17
begin
   Reply(149);
   NOption(150, RutgerEndBad, 4);
   NOption(151, Rutger17a, 4);
   NOption(152, RutgerEnd, 4);
   NLowOption(153, Rutger18);
end

procedure Rutger17a
begin
   if (is_success(do_check(dude_obj, STAT_ch, 1))) then begin
      call Rutger19;
   end
   else begin
      call Rutger20;
   end
end

procedure Rutger18
begin
   BMessage(154);
end

procedure Rutger19
begin
   set_map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS, 1);
   set_global_var(GVAR_MISSING_CARAVAN, 1);
   set_map_var(10, 1);
   set_map_var(56, 1);
   NMessage(155);
   call Rutger25;
end

procedure Rutger20
begin
   set_map_var(35, 1);
   set_map_var(MVAR_FGT_HOSTILE, 1);
   set_map_var(10, 0);
   BottomReact
   BMessage(156);
end

procedure Rutger21
begin
   float_msg(self_obj, mstr(157), FLOAT_MSG_RED);
end

procedure Rutger22
begin
   Reply(159);
   if (global_var(GVAR_WORLDMAPLIST_MILITARYBASE) == 2) or (global_var(GVAR_DCMUTANT_GAVE_DISK) > 0) or (global_var(GVAR_HOLODISK_MUTANT) == 1) then begin// BEEN_TO_MB_ENTRANCE, RECEIVED_DCMUTANT_DISK, USED_DCMUTANT_DISK
      NOption(312, Rutger76, 4);
   end
   else begin
      NOption(160, Rutger23, 4);
   end
   NOption(161, Rutger26, 4);
   if (map_var(35) == 0) then begin
      NOption(162, Rutger22a, 4);
   end
   NOption(163, RutgerEnd, 4);
   NLowOption(164, Rutger24);
end

procedure Rutger22a
begin
   if ((map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) != 3) and (map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS) != 4)) then begin
      call Rutger63;
   end
   else begin
      if (map_var(36) == 1) then begin
         call Rutger71;
      end
   end
end

procedure Rutger23
begin
   NMessage(165);
end

procedure Rutger24
begin
   BMessage(166);
end

procedure Rutger25
begin
   set_local_var(6, 1);
   set_global_var(GVAR_MISSING_CARAVANS_STATUS, 1);
   set_map_var(33, 1);
   Reply(167);
   call Rutger29;
end

procedure Rutger26
begin
   NMessage(168);
   call Rutger25;
end

procedure Rutger27 begin
   Reply(169);
   NOption(170, Rutger28, 4);
   NOption(171, Rutger30, 4);
end

procedure Rutger28 begin
   Reply(172);
   call Rutger29;
end

procedure Rutger29 begin
   if (global_var(GVAR_QUEST_BROHOOD_1_JOIN_THEM) != 2) then begin
      NOption(173, Rutger29a, 4);
   end
   else begin
      NOption(174, Rutger29b, 4);
   end
   if (map_var(8) == 1) then begin
      NOption(175, Rutger38, 4);
   end
   NOption(176, Rutger37, 4);
   NOption(177, RutgerEnd, 4);
end

procedure Rutger29a begin
   if dude_wearing_bos_power_armor then begin
      call Rutger27;
   end
   else begin
      call Rutger31;
   end
end

procedure Rutger29b begin
   if dude_wearing_bos_power_armor then begin
      call Rutger32;
   end
   else begin
      call Rutger33;
   end
end

procedure Rutger30
begin
   Reply(178);
   call Rutger29;
end

procedure Rutger31
begin
   Reply(179);
   call Rutger29;
end

procedure Rutger32 begin
   Reply(180);
   call Rutger29;
end

procedure Rutger33
begin
   Reply(181);
   NOption(182, Rutger34, 4);
   NOption(183, Rutger35, 4);
   NOption(184, Rutger36, 4);
end

procedure Rutger34
begin
   Reply(185);
   call Rutger29;
end

procedure Rutger35
begin
   Reply(186);
   call Rutger29;
end

procedure Rutger36
begin
   Reply(187);
   call Rutger29;
end

procedure Rutger37
begin
   set_map_var(10, 1);
   Reply(188);
   call Rutger29;
end

procedure Rutger38
begin
   Reply(189);
   call Rutger29;
end

procedure Rutger39
begin
   Reply(190);
   NOption(191, Rutger39a, 4);
   NOption(192, RutgerEnd, 4);
   NLowOption(193, Rutger24);
   NLowOption(194, Rutger24);
end

procedure Rutger39a
begin
   if (map_var(42) == 16777267) then begin
      call Rutger49;
   end
   else begin
      if (map_var(42) == 1) then begin
         call Rutger50;
      end
      else begin
         if (map_var(42) == 2) then begin
            call Rutger51;
         end
         else begin
            call Rutger40;
         end
      end
   end
end

procedure Rutger40
begin
   Reply(195);
   NOption(196, Rutger40a, 4);
   NOption(197, Rutger47, 4);
   NOption(198, Rutger40b, 4);
   NOption(199, Rutger41, 4);
end

procedure Rutger40a
begin
   if (is_success(do_check(dude_obj, STAT_ch, 1))) then begin
      call Rutger42;
   end
   else begin
      call Rutger44;
   end
end

procedure Rutger40b
begin
   if (is_success(do_check(dude_obj, STAT_ch, -2))) then begin
      call Rutger45;
   end
   else begin
      call Rutger46;
   end
end

procedure Rutger41
begin
   if (dude_is_male) then begin
      BMessage(200);
   end
   else begin
      BMessage(201);
   end
end

procedure Rutger42
begin
   Reply(202);
   NOption(203, Rutger43, 4);
   NOption(204, Rutger47, 4);
   NOption(205, RutgerEnd, 4);
end

procedure Rutger43
begin
   NMessage(206);
end

procedure Rutger44
begin
   BMessage(207);
end

procedure Rutger45
begin
   Reply(208);
   NOption(209, Rutger47, 4);
   NOption(210, Rutger44, 4);
end

procedure Rutger46
begin
   BMessage(211);
end

procedure Rutger47
begin
   Reply(212);
   if (global_var(GVAR_DCMUTANT_GAVE_DISK) > 0) or (global_var(GVAR_HOLODISK_MUTANT) == 1) then begin// RECEIVED_DCMUTANT_DISK, USED_DCMUTANT_DISK
      if (global_var(GVAR_KILL_DEATHCLAW) == 2) then begin
         NOption(213, Rutger48, 4);
      end
      else begin
         NOption(214, Rutger48, 4);
      end
   end
   else begin
      NOption(215, RutgerEnd, 4);
   end
   NOption(216, RutgerEnd, 4);
   NOption(217, RutgerEnd, 4);
end

procedure Rutger48
begin
   TopReact
   dude_caps_adjust(800);
   set_map_var(42, 2);
   set_map_var(36, 1);
   set_map_var(35, 0);
   set_map_var(MVAR_FGT_HOSTILE, 0);
   set_map_var(10, 1);
   set_map_var(MVAR_MISSING_CARAVAN_QUEST_STATUS, 4);
   set_global_var(GVAR_PLAYER_REPUTATION, check_general_rep + 5);// Reputation
   set_global_var(GVAR_DCMUTANT_GAVE_DISK, 2);// Flag to indicate removal of the holodisk from player (destroy_object)

   give_xp(EXP_MISSING_CARAVAN_MUTANT_ARMY);

   GMessage(218);
end

procedure Rutger49
begin
   Reply(219);
   NOption(220, Rutger40a, 4);
   NOption(221, Rutger47, 4);
   NOption(222, Rutger40b, 4);
   NOption(223, Rutger41, 4);
end

procedure Rutger50
begin
   Reply(224);
   NOption(225, Rutger40a, 4);
   NOption(226, Rutger47, 4);
   NOption(227, Rutger40b, 4);
   NOption(228, Rutger41, 4);
end

procedure Rutger51
begin
   Reply(229);
   if (global_var(GVAR_DCMUTANT_GAVE_DISK) > 0) or (global_var(GVAR_HOLODISK_MUTANT) == 1) then begin// RECEIVED_DCMUTANT_DISK, USED_DCMUTANT_DISK
      if (global_var(GVAR_KILL_DEATHCLAW) == 2) then begin
         NOption(230, Rutger48, 4);
      end
      else begin
         NOption(231, Rutger48, 4);
      end
   end
   else begin
      NOption(232, RutgerEnd, 4);
   end
   NOption(233, RutgerEnd, 4);
end

procedure Rutger52
begin
   Reply(234);
   if (global_var(GVAR_DCMUTANT_GAVE_DISK) > 0) or (global_var(GVAR_HOLODISK_MUTANT) == 1) then begin// RECEIVED_DCMUTANT_DISK, USED_DCMUTANT_DISK
      NOption(235, Rutger48, 4);
   end
   else begin
      if (global_var(GVAR_KILL_DEATHCLAW) == 2) then begin
         NOption(236, Rutger53, 4);
      end
   end
   NOption(237, RutgerEnd, 4);
   NLowOption(238, Rutger24);
end

procedure Rutger53
begin
   NMessage(239);
end

procedure Rutger54
begin
   Reply(240);
   NOption(241, Rutger39a, 4);
   NOption(242, RutgerEnd, 4);
end

procedure Rutger55
begin
   Reply(243);
   if (has_rep_berserker) then begin
      NOption(244, Rutger59, 4);
   end
   else begin
      if (has_rep_champion) then begin
         NOption(245, Rutger59, 4);
      end
      else begin
         NOption(246, Rutger59, 4);
      end
   end
   NOption(247, Rutger55a, 4);
   NOption(248, RutgerEnd, 4);
   NLowOption(249, RutgerEnd);
end

procedure Rutger55a
begin
   if ((map_var(MVAR_FGT_HOSTILE) == 1) or (map_var(35) == 1)) then begin
      call Rutger67;
   end
   else begin
      if (global_var(GVAR_FARGO_JOB) == 5) then begin
         call RutgerLost;
      end
      else begin
         if (global_var(GVAR_FARGO_JOB) == 3) then begin
            call RutgerAbandoned;
         end
         else begin
            if (map_var(36) == 1) then begin
               call Rutger71;
            end
            else begin
               call Rutger62;
            end
         end
      end
   end
end

procedure Rutger56
begin
   if (dude_is_male) then begin
      Reply(250);
   end
   else begin
      if (dude_charisma >= 7) then begin
         Reply(252);
      end
      else begin
         Reply(253);
      end
   end
   NOption(254, Rutger55a, 4);
   NOption(255, Rutger56a, 4);
   NLowOption(256, Rutger24);
end

procedure Rutger56a begin
   if (cathedral_destroyed or military_base_destoryed) then begin
      call Rutger57;
   end
   else begin
      call Rutger61;
   end
end

procedure Rutger57 begin
   GMessage(257);
end

procedure Rutger58 begin
   Reply(258);
   if (has_rep_berserker) then begin
      NOption(259, Rutger60, 4);
   end
   else begin
      if (has_rep_champion) then begin
         NOption(260, Rutger60, 4);
         NOption(261, Rutger60, 4);
      end
      else begin
         NOption(262, Rutger61, 4);
      end
   end
   NOption(263, Rutger55a, 4);
   NOption(248, RutgerEnd, 4);
   NLowOption(264, RutgerEnd);
end

procedure Rutger59 begin
   NMessage(265);
end

procedure Rutger60 begin
   NMessage(266);
end

procedure Rutger61 begin
   NMessage(267);
end

procedure Rutger62 begin
   Reply(268);
   NOption(269, Rutger65, 4);
   NOption(270, Rutger64, 4);
end

procedure Rutger63 begin
   Reply(271);
   NOption(272, Rutger68, 4);
   NOption(273, Rutger70, 4);
   NOption(274, RutgerEnd, 4);
end

procedure Rutger64 begin
   NMessage(275);
end

procedure Rutger65 begin
   set_map_var(36, 1);
   NMessage(276);
end

procedure Rutger67 begin
   if (local_var(7) == 0) then begin
      set_local_var(7, 1);
      NMessage(279);
   end
   NMessage(280);
end

procedure Rutger68 begin
   Reply(281);
   NOption(282, Rutger72, 4);
   NOption(283, Rutger69, 4);
   NOption(284, Rutger70, 4);
end

procedure Rutger69 begin
   NMessage(285);
end

procedure Rutger70 begin
   set_map_var(36, 1);
   NMessage(286);
end

procedure Rutger71 begin
   set_map_var(36, 1);
   NMessage(287);
end

procedure Rutger72 begin
   Reply(289);
   NOption(290, RutgerEnd, 4);
   NOption(291, Rutger70, 4);
end

procedure Rutger73 begin
   Reply(292);
   if (global_var(GVAR_QUEST_VAULT13_4_WATERCHIP) != 2) then begin
      NOption(294, Rutger03, 4);
   end
   if (map_var(43) == 1) then begin
      NOption(295, Rutger00a, 4);
   end
   else begin
      NOption(296, Rutger00a, 4);
   end
   NOption(297, Rutger07, 4);
   NOption(298, RutgerEnd, 4);
   NLowOption(299, Rutger00b);
end

procedure Rutger74 begin
   Reply(random(300, 303));
   if (global_var(GVAR_QUEST_VAULT13_4_WATERCHIP) != 2) then begin
      NOption(305, Rutger03, 4);
   end
   if (map_var(43) == 1) then begin
      NOption(306, Rutger00a, 4);
   end
   else begin
      NOption(307, Rutger00a, 4);
   end
   NOption(308, Rutger07, 4);
   NOption(309, RutgerEnd, 4);
   NLowOption(310, Rutger00b);
end

procedure Rutger75 begin
   NMessage(311);
end

procedure Rutger76 begin
   NMessage(313);
end

procedure RutgerEnd begin
end

procedure RutgerEndBad begin
   DownReactLevel
end

procedure RutgerAbandoned begin
   NMessage(277);
end

procedure RutgerLost begin
   set_map_var(35, 1);
   set_map_var(10, 0);
   set_global_var(GVAR_FARGO_JOB, 6);
   NMessage(279);
end
