#include "..\headers\define.h"

#define NAME                    SCRIPT_CORECOMP

#include "..\headers\command.h"

procedure start;
procedure description_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;

procedure start begin
end

procedure description_p_proc begin
	script_overrides;
	display_msg(message_str(NAME, 100));
end

procedure use_p_proc begin
	script_overrides;
	display_msg(message_str(SCRIPT_VALTCOMP, 100));
end

procedure use_skill_on_p_proc begin
	if (action_being_used == SKILL_SCIENCE) then begin
		script_overrides;
		if (is_success(roll_vs_skill(dude_obj, action_being_used, 0))) then begin
			if ((GAME_TIME_IN_DAYS) >= 90) then begin
				display_msg(message_str(NAME, 101));
			end
			else begin
				display_msg(message_str(NAME, 102));
			end
		end
		else begin
			display_msg(message_str(NAME, 103));
		end
	end
end

