#include "..\headers\define.h"

#define NAME                    SCRIPT_VALTLEAV

#include "..\headers\command.h"

procedure start;
procedure spatial_p_proc;

procedure start begin
end

procedure spatial_p_proc begin
   if source_obj == dude_obj then begin
      if not(local_var(0)) then begin
         set_local_var(0, 1);
         if (game_time_hour >= 1900) or (game_time_hour < 500) then begin
            display_msg(mstr(101));
         end
         else begin
            display_msg(mstr(100));
         end
      end
   end
end
