#include "..\headers\define.h"

#define NAME                    SCRIPT_VALTMED

#include "..\headers\command.h"

procedure start;
procedure spatial_p_proc;

procedure start begin
end

procedure spatial_p_proc begin
   if (source_obj == dude_obj) then begin
      if (not(local_var(0))) then begin
         display_msg(mstr(100));
         set_local_var(0, 1);
      end
   end
end
