name: Tools

on:
 push:
  paths:
  - '.github/workflows/tools.debugger.yml'
  - 'Tools/Debugger/**'

jobs:

 Debugger:
  name:    Debugger (${{ matrix.platform }})
  runs-on: windows-latest
  strategy:
   matrix:
    platform: [x86] # x64 disabled

  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name:  Build
    run:   |
           :
           MSBUILD_EXE="$("/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)"
           "$MSBUILD_EXE" Tools/Debugger/Debugger.sln -p:Configuration=Release -p:Platform=${{ matrix.platform }}
    shell: bash
